Qt 4.8: /src/gui/kernel/qapplication_x11.cpp File Reference
qapplication_x11.cpp File Reference
#include "qplatformdefs.h"
#include "qcolormap.h"
#include "qdesktopwidget.h"
#include "qapplication.h"
#include "qapplication_p.h"
#include "qcursor.h"
#include "qwidget.h"
#include "qbitarray.h"
#include "qpainter.h"
#include "qfile.h"
#include "qpixmapcache.h"
#include "qdatetime.h"
#include "qtextcodec.h"
#include "qdatastream.h"
#include "qbuffer.h"
#include "qsocketnotifier.h"
#include "qsessionmanager.h"
#include "qclipboard.h"
#include "qwhatsthis.h"
#include "qsettings.h"
#include "qstylefactory.h"
#include "qfileinfo.h"
#include "qdir.h"
#include "qhash.h"
#include "qevent.h"
#include "qevent_p.h"
#include "qvarlengtharray.h"
#include "qdebug.h"
#include <private/qcrashhandler_p.h>
#include <private/qcolor_p.h>
#include <private/qcursor_p.h>
#include <private/qiconloader_p.h>
#include <qgtkstyle.h>
#include "qstyle.h"
#include "qmetaobject.h"
#include "qtimer.h"
#include "qlibrary.h"
#include <private/qgraphicssystemfactory_p.h>
#include "qguiplatformplugin_p.h"
#include "qkde_p.h"
#include <wacomcfg.h>
#include "qguieventdispatcher_glib_p.h"
#include "qeventdispatcher_x11_p.h"
#include <private/qpaintengine_x11_p.h>
#include <private/qkeymapper_p.h>
#include "qinputcontext.h"
#include "qinputcontextfactory.h"
#include <X11/extensions/Xfixes.h>
#include "qt_x11_p.h"
#include "qx11info_x11.h"
#include <X11/keysymdef.h>
#include <X11/extensions/XI.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <locale.h>
#include "qwidget_p.h"
#include <private/qbackingstore_p.h>
#include <X11/SM/SMlib.h>
#include "qapplication_x11.moc"
Classes
struct PaintEventInfo
class QETWidget
class QSessionManagerPrivate
class QSmSocketReceiver
struct QT_smcConn
struct qt_sync_request_event_data
struct qt_tablet_motion_data
struct qt_xfixes_selection_event_data
Macros
#define class c_class
#define QT_GUI_DOUBLE_CLICK_RADIUS 5
#define QT_NO_UNSETENV
#define XINPUT_LOAD(symbol) symbol
#define XK_MISCELLANY
#define XWACOM_PARAM_TOOLID 322
#define XWACOM_PARAM_TOOLSERIAL 323
Typedefs
typedef int(* PtrWacomConfigCloseDevice) (WACOMDEVICE *)
typedef int *(* PtrWacomConfigGetRawParam) (WACOMDEVICE *, int, int *, int, unsigned *)
typedef WACOMCONFIG *(* PtrWacomConfigInit) (Display *, WACOMERRORFUNC)
typedef WACOMDEVICE *(* PtrWacomConfigOpenDevice) (WACOMCONFIG *, const char *)
typedef void(* PtrWacomConfigTerm) (WACOMCONFIG *)
typedef bool(* QX11FilterFunction) (XEvent *event)
Functions
void fetchWacomToolId (int &deviceType, qint64 &serialId)
static void getXDefault (const char *group, const char *key, int *val)
static void getXDefault (const char *group, const char *key, double *val)
static void getXDefault (const char *group, const char *key, bool *val)
static Bool isPaintOrScrollDoneEvent (Display *, XEvent *ev, XPointer a)
void qPRCleanup (QWidget *widget)
void qPRCreate (const QWidget *widget, Window oldwin)
static QETWidget * qPRFindWidget (Window oldwin)
void qt_change_net_wm_state (const QWidget *w, bool set, Atom one, Atom two=0)
bool qt_check_clipboard_sentinel ()
static void qt_check_focus_model ()
bool qt_check_selection_sentinel ()
void qt_cleanup ()
void qt_desktopwidget_update_workarea ()
static void qt_get_net_supported ()
static void qt_get_net_virtual_roots ()
void qt_init (QApplicationPrivate *priv, int, Display *display, Qt::HANDLE visual, Qt::HANDLE colormap)
Q_GUI_EXPORT void qt_installX11EventFilter (QX11FilterFunction func)
static void * qt_load_library_runtime (const char *library, int vernum, int highestVernum, const char *symbol)
Try to resolve a symbol from library with the version specified by vernum.
static Bool qt_mouseMotion_scanner (Display *, XEvent *event, XPointer arg)
void qt_net_remove_user_time (QWidget *tlw)
void qt_net_update_user_time (QWidget *tlw, unsigned long timestamp)
bool qt_nograb ()
Q_GUI_EXPORT void qt_removeX11EventFilter (QX11FilterFunction func)
static void qt_save_rootinfo ()
static void qt_set_input_encoding ()
static void qt_set_x11_resources (const char *font=0, const char *fg=0, const char *bg=0, const char *button=0)
static Bool qt_sync_request_scanner (Display *, XEvent *event, XPointer arg)
QTabletDeviceDataList * qt_tablet_devices ()
static Bool qt_tabletMotion_scanner (Display *, XEvent *event, XPointer arg)
Q_GUI_EXPORT bool qt_try_modal (QWidget *, XEvent *)
void qt_updated_rootinfo ()
bool qt_wstate_iconified (WId winid)
Q_GUI_EXPORT void qt_x11_apply_settings_in_all_apps ()
static void qt_x11_create_intern_atoms ()
static bool qt_x11EventFilter (XEvent *ev)
static int qt_x_errhandler (Display *dpy, XErrorEvent *err)
bool qt_xfixes_clipboard_changed (Window clipboardOwner, Time timestamp)
static Bool qt_xfixes_scanner (Display *, XEvent *event, XPointer arg)
bool qt_xfixes_selection_changed (Window selectionOwner, Time timestamp)
static int qt_xio_errhandler (Display *)
static void resetSmState ()
bool runningUnderDebugger ()
static void sm_dieCallback (SmcConn smcConn, SmPointer clientData)
static void sm_interactCallback (SmcConn smcConn, SmPointer clientData)
static void sm_performSaveYourself (QSessionManagerPrivate *)
static void sm_saveCompleteCallback (SmcConn smcConn, SmPointer clientData)
static void sm_saveYourselfCallback (SmcConn smcConn, SmPointer clientData, int saveType, Bool shutdown, int interactStyle, Bool fast)
static void sm_saveYourselfPhase2Callback (SmcConn smcConn, SmPointer clientData)
static void sm_setProperty (const char *name, const char *type, int num_vals, SmPropValue *vals)
static void sm_setProperty (const QString &name, const QString &value)
static void sm_setProperty (const QString &name, const QStringList &value)
static void sm_shutdownCancelledCallback (SmcConn smcConn, SmPointer clientData)
static bool translateBySips (QWidget *that, QRect &paintRect)
static Qt::MouseButtons translateMouseButtons (int s)
Variables
static bool app_do_modal = false
static bool app_save_rootinfo = false
static const char * appBGCol = 0
static const char * appBTNCol = 0
static const char * appClass = 0
static bool appDoGrab = false
static const char * appFGCol = 0
static const char * appFont = 0
static const char * appName = 0
static bool appNoGrab = false
static bool appSync = false
static Window curWin = 0
static Window mouseActWindow = 0
static Qt::MouseButton mouseButtonPressed = Qt::NoButton
static Time mouseButtonPressTime = 0
static Qt::MouseButtons mouseButtonState = Qt::NoButton
static short mouseGlobalXPos
static short mouseGlobalYPos
static short mouseXPos
static short mouseYPos
static const char * mwGeometry = 0
static const char * mwTitle = 0
static int openPopupCount = 0
static int(* original_x_errhandler)(Display *dpy, XErrorEvent *)
static int(* original_xio_errhandler)(Display *dpy)
static bool popupGrabOk
static Window pressed_window = XNone
static PtrWacomConfigCloseDevice ptrWacomConfigCloseDevice = 0
static PtrWacomConfigGetRawParam ptrWacomConfigGetRawParam = 0
static PtrWacomConfigInit ptrWacomConfigInit = 0
static PtrWacomConfigOpenDevice ptrWacomConfigOpenDevice = 0
static PtrWacomConfigTerm ptrWacomConfigTerm = 0
uchar qt_alt_mask = 0
QWidget * qt_button_down = 0
uchar qt_hyper_mask = 0
QTextCodec * qt_input_mapper = 0
bool qt_is_gui_used
QPointer< QWidget > qt_last_mouse_receiver = 0
uchar qt_meta_mask = 0
QWidgetList * qt_modal_stack
uchar qt_mode_switch_mask = 0
static QWidget * qt_popup_down = 0
bool qt_sm_blockUserInput = false
uchar qt_super_mask = 0
bool qt_tabletChokeMouse
bool qt_use_rtl_extensions = false
Q_GUI_EXPORT QX11Data * qt_x11Data = 0
bool qt_xdnd_dragging
Q_GUI_EXPORT int qt_xfocusout_grab_counter = 0
int qt_ximComposingKeycode =0
char * qt_ximServer = 0
static bool replayPopupMouseEvent = false
static bool sm_cancel
static bool sm_in_phase2
static bool sm_interactionActive
static int sm_interactStyle
static bool sm_isshutdown
static bool sm_phase2
static QSmSocketReceiver * sm_receiver = 0
static int sm_saveType
static bool sm_smActive
static bool sm_waitingForInteraction
static SmcConn smcConnection = 0
static QWidgetMapper * wPRmapper = 0
static const char * x11_atomnames
Macro Definition Documentation
class
#define class c_class
Definition at line 92 of file qapplication_x11.cpp.
QT_GUI_DOUBLE_CLICK_RADIUS
#define QT_GUI_DOUBLE_CLICK_RADIUS 5
Definition at line 99 of file qapplication_x11.cpp.
Referenced by QETWidget::translateMouseEvent().
QT_NO_UNSETENV
#define QT_NO_UNSETENV
Definition at line 148 of file qapplication_x11.cpp.
XINPUT_LOAD
#define XINPUT_LOAD (symbol) symbol
Definition at line 505 of file qapplication_x11.cpp.
Referenced by qt_init().
XK_MISCELLANY
#define XK_MISCELLANY
Definition at line 126 of file qapplication_x11.cpp.
XWACOM_PARAM_TOOLID
#define XWACOM_PARAM_TOOLID 322
Definition at line 1565 of file qapplication_x11.cpp.
Referenced by fetchWacomToolId().
XWACOM_PARAM_TOOLSERIAL
#define XWACOM_PARAM_TOOLSERIAL 323
Definition at line 1566 of file qapplication_x11.cpp.
Referenced by fetchWacomToolId().
Typedef Documentation
PtrWacomConfigCloseDevice
typedef int(* PtrWacomConfigCloseDevice) (WACOMDEVICE *)
Definition at line 1571 of file qapplication_x11.cpp.
PtrWacomConfigGetRawParam
typedef int*(* PtrWacomConfigGetRawParam) (WACOMDEVICE *, int, int *, int, unsigned *)
Definition at line 1570 of file qapplication_x11.cpp.
PtrWacomConfigInit
typedef WACOMCONFIG*(* PtrWacomConfigInit) (Display *, WACOMERRORFUNC)
Definition at line 1568 of file qapplication_x11.cpp.
PtrWacomConfigOpenDevice
typedef WACOMDEVICE*(* PtrWacomConfigOpenDevice) (WACOMCONFIG *, const char *)
Definition at line 1569 of file qapplication_x11.cpp.
PtrWacomConfigTerm
typedef void(* PtrWacomConfigTerm) (WACOMCONFIG *)
Definition at line 1572 of file qapplication_x11.cpp.
QX11FilterFunction
typedef bool(* QX11FilterFunction) (XEvent *event)
Definition at line 403 of file qapplication_x11.cpp.
Function Documentation
fetchWacomToolId()
void fetchWacomToolId (int & deviceType, qint64 & serialId)
Definition at line 4588 of file qapplication_x11.cpp.
Referenced by QETWidget::translateXinputEvent().
 {
     if (ptrWacomConfigInit == 0) // we actually have the lib
         return;
     WACOMCONFIG *config = ptrWacomConfigInit(X11->display, 0);
     if (config == 0)
         return;
     WACOMDEVICE *device = ptrWacomConfigOpenDevice (config, wacomDeviceName()->constData());
     if (device == 0)
         return;
     unsigned keys[1];
     int serialInt;
     ptrWacomConfigGetRawParam (device, XWACOM_PARAM_TOOLSERIAL, &serialInt, 1, keys);
     serialId = serialInt;
     int toolId;
     ptrWacomConfigGetRawParam (device, XWACOM_PARAM_TOOLID, &toolId, 1, keys);
     switch(toolId) {
     case 0x007: /* Mouse 4D and 2D */
     case 0x017: /* Intuos3 2D Mouse */
     case 0x094:
     case 0x09c:
         deviceType = QTabletEvent::FourDMouse;
         break;
     case 0x096: /* Lens cursor */
     case 0x097: /* Intuos3 Lens cursor */
         deviceType = QTabletEvent::Puck;
         break;
     case 0x0fa:
     case 0x81b: /* Intuos3 Classic Pen Eraser */
     case 0x82a: /* Eraser */
     case 0x82b: /* Intuos3 Grip Pen Eraser */
     case 0x85a:
     case 0x91a:
     case 0x91b: /* Intuos3 Airbrush Eraser */
     case 0xd1a:
         deviceType = QTabletEvent::XFreeEraser;
         break;
     case 0x112:
     case 0x912:
     case 0x913: /* Intuos3 Airbrush */
     case 0xd12:
         deviceType = QTabletEvent::Airbrush;
         break;
     case 0x012:
     case 0x022:
     case 0x032:
     case 0x801: /* Intuos3 Inking pen */
     case 0x812: /* Inking pen */
     case 0x813: /* Intuos3 Classic Pen */
     case 0x822: /* Pen */
     case 0x823: /* Intuos3 Grip Pen */
     case 0x832: /* Stroke pen */
     case 0x842:
     case 0x852:
     case 0x885: /* Intuos3 Marker Pen */
     default: /* Unknown tool */
         deviceType = QTabletEvent::Stylus;
     }
     /* Close device and return */
     ptrWacomConfigCloseDevice (device);
     ptrWacomConfigTerm(config);
 }
getXDefault() [1/3]
static void getXDefault (const char * group, const char * key, int * val) static
Definition at line 1589 of file qapplication_x11.cpp.
 {
     char *str = XGetDefault(X11->display, group, key);
     if (str) {
         char *end = 0;
         int v = strtol(str, &end, 0);
         if (str != end)
             *val = v;
         // otherwise use fontconfig to convert the string to integer
         else
             FcNameConstant((FcChar8 *) str, val);
     }
 }
getXDefault() [2/3]
static void getXDefault (const char * group, const char * key, double * val) static
Definition at line 1603 of file qapplication_x11.cpp.
 {
     char *str = XGetDefault(X11->display, group, key);
     if (str) {
         bool ok;
         double v = QByteArray(str).toDouble(&ok);
         if (ok)
             *val = v;
     }
 }
getXDefault() [3/3]
static void getXDefault (const char * group, const char * key, bool * val) static
Definition at line 1614 of file qapplication_x11.cpp.
 {
     char *str = XGetDefault(X11->display, group, key);
     if (str) {
         char c = str[0];
         if (isupper((int)c))
             c = tolower(c);
         if (c == 't' || c == 'y' || c == '1')
             *val = true;
         else if (c == 'f' || c == 'n' || c == '0')
             *val = false;
         if (c == 'o') {
             c = str[1];
             if (isupper((int)c))
                 c = tolower(c);
             if (c == 'n')
                 *val = true;
             if (c == 'f')
                 *val = false;
         }
     }
 }
isPaintOrScrollDoneEvent()
static Bool isPaintOrScrollDoneEvent (Display * , XEvent * ev, XPointer a) static
Definition at line 5166 of file qapplication_x11.cpp.
Referenced by QETWidget::translatePaintEvent().
 {
     PaintEventInfo *info = (PaintEventInfo *)a;
     if (ev->type == Expose || ev->type == GraphicsExpose
         || (ev->type == ClientMessage && ev->xclient.message_type == ATOM(_QT_SCROLL_DONE)))
     {
         if (ev->xexpose.window == info->window)
             return True;
     }
     return False;
 }
qPRCleanup()
void qPRCleanup (QWidget * widget)
Definition at line 3123 of file qapplication_x11.cpp.
Referenced by QWidgetPrivate::isBackgroundInherited(), and QApplication::x11ProcessEvent().
 {
     QETWidget *etw = static_cast<QETWidget *>(const_cast<QWidget *>(widget));
     if (!(wPRmapper && widget->testAttribute(Qt::WA_WState_Reparented)))
         return;                                        // not a reparented widget
     QWidgetMapper::Iterator it = wPRmapper->begin();
     while (it != wPRmapper->constEnd()) {
         QWidget *w = *it;
         if (w == etw) {                       // found widget
             etw->setAttribute(Qt::WA_WState_Reparented, false); // clear flag
             it = wPRmapper->erase(it);// old window no longer needed
         } else {
             ++it;
         }
     }
     if (wPRmapper->size() == 0) {        // became empty
         delete wPRmapper;                // then reset alt mapper
         wPRmapper = 0;
     }
 }
qPRCreate()
void qPRCreate (const QWidget * widget, Window oldwin)
Definition at line 3113 of file qapplication_x11.cpp.
Referenced by QWidgetPrivate::isBackgroundInherited().
 {                                                // QWidget::reparent mechanism
     if (!wPRmapper)
         wPRmapper = new QWidgetMapper;
     QETWidget *w = static_cast<QETWidget *>(const_cast<QWidget *>(widget));
     wPRmapper->insert((int)oldwin, w);        // add old window to mapper
     w->setAttribute(Qt::WA_WState_Reparented);        // set reparented flag
 }
qPRFindWidget()
static QETWidget* qPRFindWidget (Window oldwin) static
Definition at line 3144 of file qapplication_x11.cpp.
Referenced by QApplication::x11ProcessEvent().
 {
     return wPRmapper ? (QETWidget*)wPRmapper->value((int)oldwin, 0) : 0;
 }
qt_change_net_wm_state()
void qt_change_net_wm_state (const QWidget * w, bool set, Atom one, Atom two = 0)
Definition at line 413 of file qwidget_x11.cpp.
Referenced by qstring_to_xtp(), and QApplication::syncX().
 {
     if (!w->isVisible()) // not managed by the window manager
         return;
     XEvent e;
     e.xclient.type = ClientMessage;
     e.xclient.message_type = ATOM(_NET_WM_STATE);
     e.xclient.display = X11->display;
     e.xclient.window = w->internalWinId();
     e.xclient.format = 32;
     e.xclient.data.l[0] = set ? 1 : 0;
     e.xclient.data.l[1] = one;
     e.xclient.data.l[2] = two;
     e.xclient.data.l[3] = 0;
     e.xclient.data.l[4] = 0;
     XSendEvent(X11->display, RootWindow(X11->display, w->x11Info().screen()),
                false, (SubstructureNotifyMask | SubstructureRedirectMask), &e);
 }
qt_check_clipboard_sentinel()
bool qt_check_clipboard_sentinel ()
Definition at line 1485 of file qclipboard_x11.cpp.
Referenced by qt_xfixes_clipboard_changed(), and QApplication::x11ProcessEvent().
 {
     bool doIt = true;
     if (owner && !X11->use_xfixes) {
         unsigned char *retval;
         Atom actualType;
         int actualFormat;
         unsigned long nitems, bytesLeft;
         if (XGetWindowProperty(X11->display,
                                QApplication::desktop()->screen(0)->internalWinId(),
                                ATOM(_QT_CLIPBOARD_SENTINEL), 0, 2, False, XA_WINDOW,
                                &actualType, &actualFormat, &nitems, &bytesLeft,
                                &retval) == Success) {
             Window *owners = (Window *)retval;
             if (actualType == XA_WINDOW && actualFormat == 32 && nitems == 2) {
                 Window win = owner->internalWinId();
                 if (owners[0] == win || owners[1] == win)
                     doIt = false;
             }
             XFree(owners);
         }
     }
     if (doIt) {
         if (waiting_for_data) {
             pending_clipboard_changed = true;
             if (! pending_timer_id)
                 pending_timer_id = QApplication::clipboard()->startTimer(0);
             doIt = false;
         } else {
             clipboardData()->clear();
         }
     }
     return doIt;
 }
qt_check_focus_model()
static void qt_check_focus_model () static
Definition at line 1550 of file qapplication_x11.cpp.
Referenced by QApplication::x11ProcessEvent().
 {
     Window fw = XNone;
     int unused;
     XGetInputFocus(X11->display, &fw, &unused);
     if (fw == PointerRoot)
         X11->focus_model = QX11Data::FM_PointerRoot;
     else
         X11->focus_model = QX11Data::FM_Other;
 }
qt_check_selection_sentinel()
bool qt_check_selection_sentinel ()
Definition at line 1433 of file qclipboard_x11.cpp.
Referenced by qt_xfixes_selection_changed(), and QApplication::x11ProcessEvent().
 {
     bool doIt = true;
     if (owner && !X11->use_xfixes) {
         /*
           Since the X selection mechanism cannot give any signal when
           the selection has changed, we emulate it (for Qt processes) here.
           The notification should be ignored in case of either
           a) This is the process that did setData (because setData()
           then has already emitted dataChanged())
           b) This is the process that owned the selection when dataChanged()
           was called (because we have then received a SelectionClear event,
           and have already emitted dataChanged() as a result of that)
         */
         unsigned char *retval;
         Atom actualType;
         int actualFormat;
         ulong nitems;
         ulong bytesLeft;
         if (XGetWindowProperty(X11->display,
                                QApplication::desktop()->screen(0)->internalWinId(),
                                ATOM(_QT_SELECTION_SENTINEL), 0, 2, False, XA_WINDOW,
                                &actualType, &actualFormat, &nitems,
                                &bytesLeft, &retval) == Success) {
             Window *owners = (Window *)retval;
             if (actualType == XA_WINDOW && actualFormat == 32 && nitems == 2) {
                 Window win = owner->internalWinId();
                 if (owners[0] == win || owners[1] == win)
                     doIt = false;
             }
             XFree(owners);
         }
     }
     if (doIt) {
         if (waiting_for_data) {
             pending_selection_changed = true;
             if (! pending_timer_id)
                 pending_timer_id = QApplication::clipboard()->startTimer(0);
             doIt = false;
         } else {
             selectionData()->clear();
         }
     }
     return doIt;
 }
qt_cleanup()
void qt_cleanup ()
Definition at line 2680 of file qapplication_x11.cpp.
Referenced by QApplication::~QApplication(), and QApplicationPrivate::~QApplicationPrivate().
 {
     if (app_save_rootinfo)                        // root window must keep state
         qt_save_rootinfo();
     if (qt_is_gui_used) {
         QPixmapCache::clear();
         QCursorData::cleanup();
         QFont::cleanup();
         QColormap::cleanup();
 #if !defined (QT_NO_TABLET)
         QTabletDeviceDataList *devices = qt_tablet_devices();
         if (X11->ptrXCloseDevice)
             for (int i = 0; i < devices->size(); ++i)
                 X11->ptrXCloseDevice(X11->display, (XDevice*)devices->at(i).device);
         devices->clear();
 #endif
     }
 #ifndef QT_NO_XRENDER
     for (int i = 0; i < X11->solid_fill_count; ++i) {
         if (X11->solid_fills[i].picture)
             XRenderFreePicture(X11->display, X11->solid_fills[i].picture);
     }
     for (int i = 0; i < X11->pattern_fill_count; ++i) {
         if (X11->pattern_fills[i].picture)
             XRenderFreePicture(X11->display, X11->pattern_fills[i].picture);
     }
 #endif
 #if !defined(QT_NO_IM)
     delete QApplicationPrivate::inputContext;
     QApplicationPrivate::inputContext = 0;
 #endif
     // Reset the error handlers
     if (qt_is_gui_used)
         XSync(X11->display, False); // sync first to process all possible errors
     XSetErrorHandler(original_x_errhandler);
     XSetIOErrorHandler(original_xio_errhandler);
     if (X11->argbColormaps) {
         for (int s = 0; s < X11->screenCount; s++) {
             if (X11->argbColormaps[s])
                 XFreeColormap(X11->display, X11->argbColormaps[s]);
         }
     }
     if (qt_is_gui_used && !X11->foreignDisplay)
         XCloseDisplay(X11->display);                // close X display
     X11->display = 0;
     delete [] X11->screens;
     delete [] X11->argbVisuals;
     delete [] X11->argbColormaps;
     if (X11->foreignDisplay) {
         delete [] (char *)appName;
         appName = 0;
     }
     delete [] (char *)appClass;
     appClass = 0;
     if (X11->net_supported_list)
         delete [] X11->net_supported_list;
     X11->net_supported_list = 0;
     if (X11->net_virtual_root_list)
         delete [] X11->net_virtual_root_list;
     X11->net_virtual_root_list = 0;
     delete X11;
     X11 = 0;
 }
qt_desktopwidget_update_workarea()
void qt_desktopwidget_update_workarea ()
Definition at line 59 of file qdesktopwidget_x11.cpp.
Referenced by QApplication::x11ProcessEvent().
 {
     qt_desktopwidget_workarea_dirty = true;
 }
qt_get_net_supported()
static void qt_get_net_supported () static
Definition at line 1389 of file qapplication_x11.cpp.
Referenced by qt_init(), and QApplication::x11ProcessEvent().
 {
     Atom type;
     int format;
     long offset = 0;
     unsigned long nitems, after;
     unsigned char *data = 0;
     int e = XGetWindowProperty(X11->display, QX11Info::appRootWindow(),
                                ATOM(_NET_SUPPORTED), 0, 0,
                                False, XA_ATOM, &type, &format, &nitems, &after, &data);
     if (data)
         XFree(data);
     if (X11->net_supported_list)
         delete [] X11->net_supported_list;
     X11->net_supported_list = 0;
     if (e == Success && type == XA_ATOM && format == 32) {
         QBuffer ts;
         ts.open(QIODevice::WriteOnly);
         while (after > 0) {
             XGetWindowProperty(X11->display, QX11Info::appRootWindow(),
                                ATOM(_NET_SUPPORTED), offset, 1024,
                                False, XA_ATOM, &type, &format, &nitems, &after, &data);
             if (type == XA_ATOM && format == 32) {
                 ts.write(reinterpret_cast<char *>(data), nitems * sizeof(long));
                 offset += nitems;
             } else
                 after = 0;
             if (data)
                 XFree(data);
         }
         // compute nitems
         QByteArray buffer(ts.buffer());
         nitems = buffer.size() / sizeof(Atom);
         X11->net_supported_list = new Atom[nitems + 1];
         Atom *a = (Atom *) buffer.data();
         uint i;
         for (i = 0; i < nitems; i++)
             X11->net_supported_list[i] = a[i];
         X11->net_supported_list[nitems] = 0;
     }
 }
qt_get_net_virtual_roots()
static void qt_get_net_virtual_roots () static
Definition at line 1457 of file qapplication_x11.cpp.
Referenced by qt_init(), and QApplication::x11ProcessEvent().
 {
     if (X11->net_virtual_root_list)
         delete [] X11->net_virtual_root_list;
     X11->net_virtual_root_list = 0;
     if (!X11->isSupportedByWM(ATOM(_NET_VIRTUAL_ROOTS)))
         return;
     Atom type;
     int format;
     long offset = 0;
     unsigned long nitems, after;
     unsigned char *data;
     int e = XGetWindowProperty(X11->display, QX11Info::appRootWindow(),
                                ATOM(_NET_VIRTUAL_ROOTS), 0, 0,
                                False, XA_ATOM, &type, &format, &nitems, &after, &data);
     if (data)
         XFree(data);
     if (e == Success && type == XA_ATOM && format == 32) {
         QBuffer ts;
         ts.open(QIODevice::WriteOnly);
         while (after > 0) {
             XGetWindowProperty(X11->display, QX11Info::appRootWindow(),
                                ATOM(_NET_VIRTUAL_ROOTS), offset, 1024,
                                False, XA_ATOM, &type, &format, &nitems, &after, &data);
             if (type == XA_ATOM && format == 32) {
                 ts.write(reinterpret_cast<char *>(data), nitems * 4);
                 offset += nitems;
             } else
                 after = 0;
             if (data)
                 XFree(data);
         }
         // compute nitems
         QByteArray buffer(ts.buffer());
         nitems = buffer.size() / sizeof(Window);
         X11->net_virtual_root_list = new Window[nitems + 1];
         Window *a = (Window *) buffer.data();
         uint i;
         for (i = 0; i < nitems; i++)
             X11->net_virtual_root_list[i] = a[i];
         X11->net_virtual_root_list[nitems] = 0;
     }
 }
qt_init()
void qt_init (QApplicationPrivate * priv, int , Display * display = 0, Qt::HANDLE visual = 0, Qt::HANDLE colormap = 0)
Definition at line 1666 of file qapplication_x11.cpp.
Referenced by QApplicationPrivate::construct(), and QApplicationPrivate::~QApplicationPrivate().
 {
     X11 = new QX11Data;
     X11->display = display;
     X11->displayName = 0;
     X11->foreignDisplay = (display != 0);
     X11->focus_model = -1;
     // RANDR
     X11->use_xrandr = false;
     X11->xrandr_major = 0;
     X11->xrandr_eventbase = 0;
     X11->xrandr_errorbase = 0;
     // RENDER
     X11->use_xrender = false;
     X11->xrender_major = 0;
     X11->xrender_version = 0;
     // XFIXES
     X11->use_xfixes = false;
     X11->xfixes_major = 0;
     X11->xfixes_eventbase = 0;
     X11->xfixes_errorbase = 0;
     // XInputExtension
     X11->use_xinput = false;
     X11->xinput_major = 0;
     X11->xinput_eventbase = 0;
     X11->xinput_errorbase = 0;
     X11->use_xkb = false;
     X11->xkb_major = 0;
     X11->xkb_eventbase = 0;
     X11->xkb_errorbase = 0;
     // MIT-SHM
     X11->use_mitshm = false;
     X11->use_mitshm_pixmaps = false;
     X11->mitshm_major = 0;
     X11->sip_serial = 0;
     X11->net_supported_list = 0;
     X11->net_virtual_root_list = 0;
     X11->wm_client_leader = 0;
     X11->screens = 0;
     X11->argbVisuals = 0;
     X11->argbColormaps = 0;
     X11->screenCount = 0;
     X11->time = CurrentTime;
     X11->userTime = CurrentTime;
     X11->ignore_badwindow = false;
     X11->seen_badwindow = false;
     X11->motifdnd_active = false;
     X11->default_im = QLatin1String("imsw-multi");
     priv->inputContext = 0;
     // colormap control
     X11->visual_class = -1;
     X11->visual_id = -1;
     X11->color_count = 0;
     X11->custom_cmap = false;
     // outside visual/colormap
     X11->visual = reinterpret_cast<Visual *>(visual);
     X11->colormap = colormap;
     // Fontconfig
     X11->has_fontconfig = false;
 #if !defined(QT_NO_FONTCONFIG)
     if (qgetenv("QT_X11_NO_FONTCONFIG").isNull())
         X11->has_fontconfig = FcInit();
     X11->fc_antialias = true;
 #endif
 #ifndef QT_NO_XRENDER
     memset(X11->solid_fills, 0, sizeof(X11->solid_fills));
     for (int i = 0; i < X11->solid_fill_count; ++i)
         X11->solid_fills[i].screen = -1;
     memset(X11->pattern_fills, 0, sizeof(X11->pattern_fills));
     for (int i = 0; i < X11->pattern_fill_count; ++i)
         X11->pattern_fills[i].screen = -1;
 #endif
     X11->startupId = 0;
     int argc = priv->argc;
     char **argv = priv->argv;
     if (X11->display) {
         // Qt part of other application
         // Set application name and class
         appName = qstrdup("Qt-subapplication");
         char *app_class = 0;
         if (argv) {
             const char* p = strrchr(argv[0], '/');
             app_class = qstrdup(p ? p + 1 : argv[0]);
             if (app_class[0])
                 app_class[0] = toupper(app_class[0]);
         }
         appClass = app_class;
     } else {
         // Qt controls everything (default)
         if (QApplication::testAttribute(Qt::AA_X11InitThreads))
             XInitThreads();
         // Set application name and class
         char *app_class = 0;
         if (argv && argv[0]) {
             const char *p = strrchr(argv[0], '/');
             appName = p ? p + 1 : argv[0];
             app_class = qstrdup(appName);
             if (app_class[0])
                 app_class[0] = toupper(app_class[0]);
         }
         appClass = app_class;
     }
     // Install default error handlers
     original_x_errhandler = XSetErrorHandler(qt_x_errhandler);
     original_xio_errhandler = XSetIOErrorHandler(qt_xio_errhandler);
     // Get command line params
     int j = argc ? 1 : 0;
     for (int i=1; i<argc; i++) {
         if (argv[i] && *argv[i] != '-') {
             argv[j++] = argv[i];
             continue;
         }
         QByteArray arg(argv[i]);
         if (arg == "-display") {
             if (++i < argc && !X11->display)
                 X11->displayName = argv[i];
         } else if (arg == "-fn" || arg == "-font") {
             if (++i < argc)
                 appFont = argv[i];
         } else if (arg == "-bg" || arg == "-background") {
             if (++i < argc)
                 appBGCol = argv[i];
         } else if (arg == "-btn" || arg == "-button") {
             if (++i < argc)
                 appBTNCol = argv[i];
         } else if (arg == "-fg" || arg == "-foreground") {
             if (++i < argc)
                 appFGCol = argv[i];
         } else if (arg == "-name") {
             if (++i < argc)
                 appName = argv[i];
         } else if (arg == "-title") {
             if (++i < argc)
                 mwTitle = argv[i];
         } else if (arg == "-geometry") {
             if (++i < argc)
                 mwGeometry = argv[i];
         } else if (arg == "-im") {
             if (++i < argc)
                 qt_ximServer = argv[i];
         } else if (arg == "-ncols") {   // xv and netscape use this name
             if (++i < argc)
                 X11->color_count = qMax(0,atoi(argv[i]));
         } else if (arg == "-visual") {  // xv and netscape use this name
             if (++i < argc && !X11->visual) {
                 QString s = QString::fromLocal8Bit(argv[i]).toLower();
                 if (s == QLatin1String("staticgray"))
                     X11->visual_class = StaticGray;
                 else if (s == QLatin1String("grayscale"))
                     X11->visual_class = XGrayScale;
                 else if (s == QLatin1String("staticcolor"))
                     X11->visual_class = StaticColor;
                 else if (s == QLatin1String("pseudocolor"))
                     X11->visual_class = PseudoColor;
                 else if (s == QLatin1String("truecolor"))
                     X11->visual_class = TrueColor;
                 else if (s == QLatin1String("directcolor"))
                     X11->visual_class = DirectColor;
                 else
                     X11->visual_id = static_cast<int>(strtol(argv[i], 0, 0));
             }
 #ifndef QT_NO_XIM
         } else if (arg == "-inputstyle") {
             if (++i < argc) {
                 QString s = QString::fromLocal8Bit(argv[i]).toLower();
                 if (s == QLatin1String("onthespot"))
                     qt_xim_preferred_style = XIMPreeditCallbacks |
                                              XIMStatusNothing;
                 else if (s == QLatin1String("overthespot"))
                     qt_xim_preferred_style = XIMPreeditPosition |
                                              XIMStatusNothing;
                 else if (s == QLatin1String("offthespot"))
                     qt_xim_preferred_style = XIMPreeditArea |
                                              XIMStatusArea;
                 else if (s == QLatin1String("root"))
                     qt_xim_preferred_style = XIMPreeditNothing |
                                              XIMStatusNothing;
             }
 #endif
         } else if (arg == "-cmap") {    // xv uses this name
             if (!X11->colormap)
                 X11->custom_cmap = true;
         }
         else if (arg == "-sync")
             appSync = !appSync;
 #if defined(QT_DEBUG)
         else if (arg == "-nograb")
             appNoGrab = !appNoGrab;
         else if (arg == "-dograb")
             appDoGrab = !appDoGrab;
 #endif
         else
             argv[j++] = argv[i];
     }
     priv->argc = j;
 #if defined(QT_DEBUG) && defined(Q_OS_LINUX)
     if (!appNoGrab && !appDoGrab && runningUnderDebugger()) {
         appNoGrab = true;
         qDebug("Qt: gdb: -nograb added to command-line options.\n"
                "\t Use the -dograb option to enforce grabbing.");
     }
 #endif
     // Connect to X server
     if (qt_is_gui_used && !X11->display) {
         if ((X11->display = XOpenDisplay(X11->displayName)) == 0) {
             qWarning("%s: cannot connect to X server %s", appName,
                      XDisplayName(X11->displayName));
             QApplicationPrivate::reset_instance_pointer();
             exit(1);
         }
         if (appSync)                                // if "-sync" argument
             XSynchronize(X11->display, true);
     }
     // Common code, regardless of whether display is foreign.
     // Get X parameters
     if (qt_is_gui_used) {
         X11->defaultScreen = DefaultScreen(X11->display);
         X11->screenCount = ScreenCount(X11->display);
         int formatCount = 0;
         XPixmapFormatValues *values = XListPixmapFormats(X11->display, &formatCount);
         for (int i = 0; i < formatCount; ++i)
             X11->bppForDepth[values[i].depth] = values[i].bits_per_pixel;
         XFree(values);
         X11->screens = new QX11InfoData[X11->screenCount];
         X11->argbVisuals = new Visual *[X11->screenCount];
         X11->argbColormaps = new Colormap[X11->screenCount];
         for (int s = 0; s < X11->screenCount; s++) {
             QX11InfoData *screen = X11->screens + s;
             screen->ref = 1; // ensures it doesn't get deleted
             screen->screen = s;
             int widthMM = DisplayWidthMM(X11->display, s);
             if (widthMM != 0) {
                 screen->dpiX = (DisplayWidth(X11->display, s) * 254 + widthMM * 5) / (widthMM * 10);
             } else {
                 screen->dpiX = 72;
             }
             int heightMM = DisplayHeightMM(X11->display, s);
             if (heightMM != 0) {
                 screen->dpiY = (DisplayHeight(X11->display, s) * 254 + heightMM * 5) / (heightMM * 10);
             } else {
                 screen->dpiY = 72;
             }
             X11->argbVisuals[s] = 0;
             X11->argbColormaps[s] = 0;
         }
 #ifndef QT_NO_XRENDER
         int xrender_eventbase,  xrender_errorbase;
         // See if XRender is supported on the connected display
         if (XQueryExtension(X11->display, "RENDER", &X11->xrender_major,
                             &xrender_eventbase, &xrender_errorbase)
             && XRenderQueryExtension(X11->display, &xrender_eventbase,
                                      &xrender_errorbase)) {
             // Check the version as well - we need v0.4 or higher
             int major = 0;
             int minor = 0;
             XRenderQueryVersion(X11->display, &major, &minor);
             if (qgetenv("QT_X11_NO_XRENDER").isNull()) {
                 X11->use_xrender = (major >= 0 && minor >= 5);
                 X11->xrender_version = major*100+minor;
                 // workaround for broken XServer on Ubuntu Breezy (6.8 compiled with 7.0
                 // protocol headers)
                 if (X11->xrender_version == 10
                     && VendorRelease(X11->display) < 60900000
                     && QByteArray(ServerVendor(X11->display)).contains("X.Org"))
                     X11->xrender_version = 9;
             }
         }
 #endif // QT_NO_XRENDER
 #ifndef QT_NO_MITSHM
         int mitshm_minor;
         int mitshm_major;
         int mitshm_eventbase;
         int mitshm_errorbase;
         int mitshm_pixmaps;
         if (XQueryExtension(X11->display, "MIT-SHM", &X11->mitshm_major,
                             &mitshm_eventbase, &mitshm_errorbase)
             && XShmQueryVersion(X11->display, &mitshm_major, &mitshm_minor,
                                 &mitshm_pixmaps))
         {
             QString displayName = QLatin1String(XDisplayName(NULL));
             // MITSHM only works for local displays, so do a quick check here
             // to determine whether the display is local or not (not 100 % accurate).
             // BGR server layouts are not supported either, since it requires the raster
             // engine to work on a QImage with BGR layout.
             bool local = displayName.isEmpty() || displayName.lastIndexOf(QLatin1Char(':')) == 0;
             if (local && (qgetenv("QT_X11_NO_MITSHM").toInt() == 0)) {
                 Visual *defaultVisual = DefaultVisual(X11->display, DefaultScreen(X11->display));
                 X11->use_mitshm = ((defaultVisual->red_mask == 0xff0000
                                     || defaultVisual->red_mask == 0xf800)
                                    && (defaultVisual->green_mask == 0xff00
                                        || defaultVisual->green_mask == 0x7e0)
                                    && (defaultVisual->blue_mask == 0xff
                                        || defaultVisual->blue_mask == 0x1f));
                 X11->use_mitshm_pixmaps = X11->use_mitshm && mitshm_pixmaps;
             }
         }
 #endif // QT_NO_MITSHM
         // initialize the graphics system - order is imporant here - it must be done before
         // the QColormap::initialize() call
         QApplicationPrivate::graphics_system = QGraphicsSystemFactory::create(QApplicationPrivate::graphics_system_name);
         QColormap::initialize();
         // Support protocols
         X11->xdndSetup();
         // Finally create all atoms
         qt_x11_create_intern_atoms();
         // initialize NET lists
         qt_get_net_supported();
         qt_get_net_virtual_roots();
 #ifndef QT_NO_XRANDR
         // See if XRandR is supported on the connected display
         if (XQueryExtension(X11->display, "RANDR", &X11->xrandr_major,
                             &X11->xrandr_eventbase, &X11->xrandr_errorbase)) {
 #  ifdef QT_RUNTIME_XRANDR
             X11->ptrXRRSelectInput = 0;
             X11->ptrXRRUpdateConfiguration = 0;
             X11->ptrXRRRootToScreen = 0;
             X11->ptrXRRQueryExtension = 0;
             QLibrary xrandrLib(QLatin1String("Xrandr"), 2);
             xrandrLib.setLoadHints(QLibrary::ImprovedSearchHeuristics);
             if (!xrandrLib.load()) { // try without the version number
                 xrandrLib.setFileName(QLatin1String("Xrandr"));
                 xrandrLib.load();
             }
             if (xrandrLib.isLoaded()) {
                 X11->ptrXRRSelectInput =
                     (PtrXRRSelectInput) xrandrLib.resolve("XRRSelectInput");
                 X11->ptrXRRUpdateConfiguration =
                     (PtrXRRUpdateConfiguration) xrandrLib.resolve("XRRUpdateConfiguration");
                 X11->ptrXRRRootToScreen =
                     (PtrXRRRootToScreen) xrandrLib.resolve("XRRRootToScreen");
                 X11->ptrXRRQueryExtension =
                     (PtrXRRQueryExtension) xrandrLib.resolve("XRRQueryExtension");
             }
 #  else
             X11->ptrXRRSelectInput = XRRSelectInput;
             X11->ptrXRRUpdateConfiguration = XRRUpdateConfiguration;
             X11->ptrXRRRootToScreen = XRRRootToScreen;
             X11->ptrXRRQueryExtension = XRRQueryExtension;
 #  endif
             if (X11->ptrXRRQueryExtension
                 && X11->ptrXRRQueryExtension(X11->display, &X11->xrandr_eventbase, &X11->xrandr_errorbase)) {
                 // XRandR is supported
                 X11->use_xrandr = true;
             }
         }
 #endif // QT_NO_XRANDR
 #ifndef QT_NO_XRENDER
         if (X11->use_xrender) {
             // XRender is supported, let's see if we have a PictFormat for the
             // default visual
             XRenderPictFormat *format =
                 XRenderFindVisualFormat(X11->display,
                                         (Visual *) QX11Info::appVisual(X11->defaultScreen));
             if (!format) {
                 X11->use_xrender = false;
             }
         }
 #endif // QT_NO_XRENDER
 #ifndef QT_NO_XFIXES
         // See if Xfixes is supported on the connected display
         if (XQueryExtension(X11->display, "XFIXES", &X11->xfixes_major,
                             &X11->xfixes_eventbase, &X11->xfixes_errorbase)) {
             X11->ptrXFixesQueryExtension  = XFIXES_LOAD_V1(XFixesQueryExtension);
             X11->ptrXFixesQueryVersion    = XFIXES_LOAD_V1(XFixesQueryVersion);
             X11->ptrXFixesSetCursorName   = XFIXES_LOAD_V2(XFixesSetCursorName);
             X11->ptrXFixesSelectSelectionInput = XFIXES_LOAD_V2(XFixesSelectSelectionInput);
             if(X11->ptrXFixesQueryExtension && X11->ptrXFixesQueryVersion
                && X11->ptrXFixesQueryExtension(X11->display, &X11->xfixes_eventbase,
                                                &X11->xfixes_errorbase)) {
                 // Xfixes is supported.
                 // Note: the XFixes protocol version is negotiated using QueryVersion.
                 // We supply the highest version we support, the X server replies with
                 // the highest version it supports, but no higher than the version we
                 // asked for. The version sent back is the protocol version the X server
                 // will use to talk us. If this call is removed, the behavior of the
                 // X server when it receives an XFixes request is undefined.
                 int major = 3;
                 int minor = 0;
                 X11->ptrXFixesQueryVersion(X11->display, &major, &minor);
                 X11->use_xfixes = (major >= 1);
                 X11->xfixes_major = major;
             }
         } else {
             X11->ptrXFixesQueryExtension  = 0;
             X11->ptrXFixesQueryVersion    = 0;
             X11->ptrXFixesSetCursorName   = 0;
             X11->ptrXFixesSelectSelectionInput = 0;
         }
 #endif // QT_NO_XFIXES
 #ifndef QT_NO_XCURSOR
 #ifdef QT_RUNTIME_XCURSOR
         X11->ptrXcursorLibraryLoadCursor = 0;
         QLibrary xcursorLib(QLatin1String("Xcursor"), 1);
         xcursorLib.setLoadHints(QLibrary::ImprovedSearchHeuristics);
         bool xcursorFound = xcursorLib.load();
         if (!xcursorFound) { //try without the version number
             xcursorLib.setFileName(QLatin1String("Xcursor"));
             xcursorFound = xcursorLib.load();
         }
         if (xcursorFound) {
             X11->ptrXcursorLibraryLoadCursor =
                 (PtrXcursorLibraryLoadCursor) xcursorLib.resolve("XcursorLibraryLoadCursor");
         }
 #else
         X11->ptrXcursorLibraryLoadCursor = XcursorLibraryLoadCursor;
 #endif // QT_RUNTIME_XCURSOR
 #endif // QT_NO_XCURSOR
 #ifndef QT_NO_XSYNC
         int xsync_evbase, xsync_errbase;
         int major, minor;
         if (XSyncQueryExtension(X11->display, &xsync_evbase, &xsync_errbase))
             XSyncInitialize(X11->display, &major, &minor);
 #endif // QT_NO_XSYNC
 #ifndef QT_NO_XINERAMA
 #ifdef QT_RUNTIME_XINERAMA
         X11->ptrXineramaQueryExtension = 0;
         X11->ptrXineramaIsActive = 0;
         X11->ptrXineramaQueryScreens = 0;
         QLibrary xineramaLib(QLatin1String("Xinerama"), 1);
         xineramaLib.setLoadHints(QLibrary::ImprovedSearchHeuristics);
         bool xineramaFound = xineramaLib.load();
         if (!xineramaFound) { //try without the version number
             xineramaLib.setFileName(QLatin1String("Xinerama"));
             xineramaFound = xineramaLib.load();
         }
         if (xineramaFound) {
             X11->ptrXineramaQueryExtension =
                 (PtrXineramaQueryExtension) xineramaLib.resolve("XineramaQueryExtension");
             X11->ptrXineramaIsActive =
                 (PtrXineramaIsActive) xineramaLib.resolve("XineramaIsActive");
             X11->ptrXineramaQueryScreens =
                 (PtrXineramaQueryScreens) xineramaLib.resolve("XineramaQueryScreens");
         }
 #else
         X11->ptrXineramaQueryScreens = XineramaQueryScreens;
         X11->ptrXineramaIsActive = XineramaIsActive;
         X11->ptrXineramaQueryExtension = XineramaQueryExtension;
 #endif // QT_RUNTIME_XINERAMA
 #endif // QT_NO_XINERAMA
 #ifndef QT_NO_XINPUT
         // See if Xinput is supported on the connected display
         X11->ptrXCloseDevice = 0;
         X11->ptrXListInputDevices = 0;
         X11->ptrXOpenDevice = 0;
         X11->ptrXFreeDeviceList = 0;
         X11->ptrXSelectExtensionEvent = 0;
         X11->use_xinput = XQueryExtension(X11->display, "XInputExtension", &X11->xinput_major,
                                           &X11->xinput_eventbase, &X11->xinput_errorbase);
         if (X11->use_xinput) {
             X11->ptrXCloseDevice = XINPUT_LOAD(XCloseDevice);
             X11->ptrXListInputDevices = XINPUT_LOAD(XListInputDevices);
             X11->ptrXOpenDevice = XINPUT_LOAD(XOpenDevice);
             X11->ptrXFreeDeviceList = XINPUT_LOAD(XFreeDeviceList);
             X11->ptrXSelectExtensionEvent = XINPUT_LOAD(XSelectExtensionEvent);
         }
 #endif // QT_NO_XINPUT
 #ifndef QT_NO_XKB
         int xkblibMajor = XkbMajorVersion;
         int xkblibMinor = XkbMinorVersion;
         X11->use_xkb = XkbQueryExtension(X11->display,
                                          &X11->xkb_major,
                                          &X11->xkb_eventbase,
                                          &X11->xkb_errorbase,
                                          &xkblibMajor,
                                          &xkblibMinor);
         if (X11->use_xkb) {
             // If XKB is detected, set the GrabsUseXKBState option so input method
             // compositions continue to work (ie. deadkeys)
             unsigned int state = XkbPCF_GrabsUseXKBStateMask;
             (void) XkbSetPerClientControls(X11->display, state, &state);
             // select for group change events
             XkbSelectEventDetails(X11->display,
                                   XkbUseCoreKbd,
                                   XkbStateNotify,
                                   XkbAllStateComponentsMask,
                                   XkbGroupStateMask);
             // current group state is queried when creating the keymapper, no need to do it here
         }
 #endif
 #if !defined(QT_NO_FONTCONFIG)
         int dpi = 0;
         getXDefault("Xft", FC_DPI, &dpi);
         if (dpi) {
             for (int s = 0; s < ScreenCount(X11->display); ++s) {
                 QX11Info::setAppDpiX(s, dpi);
                 QX11Info::setAppDpiY(s, dpi);
             }
         }
         double fc_scale = 1.;
         getXDefault("Xft", FC_SCALE, &fc_scale);
         X11->fc_scale = fc_scale;
         for (int s = 0; s < ScreenCount(X11->display); ++s) {
             int subpixel = FC_RGBA_UNKNOWN;
 #if !defined(QT_NO_XRENDER) && (RENDER_MAJOR > 0 || RENDER_MINOR >= 6)
             if (X11->use_xrender) {
                 int rsp = XRenderQuerySubpixelOrder(X11->display, s);
                 switch (rsp) {
                 default:
                 case SubPixelUnknown:
                     subpixel = FC_RGBA_UNKNOWN;
                     break;
                 case SubPixelHorizontalRGB:
                     subpixel = FC_RGBA_RGB;
                     break;
                 case SubPixelHorizontalBGR:
                     subpixel = FC_RGBA_BGR;
                     break;
                 case SubPixelVerticalRGB:
                     subpixel = FC_RGBA_VRGB;
                     break;
                 case SubPixelVerticalBGR:
                     subpixel = FC_RGBA_VBGR;
                     break;
                 case SubPixelNone:
                     subpixel = FC_RGBA_NONE;
                     break;
                 }
             }
 #endif
             char *rgba = XGetDefault(X11->display, "Xft", FC_RGBA);
             if (rgba) {
                 char *end = 0;
                 int v = strtol(rgba, &end, 0);
                 if (rgba != end) {
                     subpixel = v;
                 } else if (qstrncmp(rgba, "unknown", 7) == 0) {
                     subpixel = FC_RGBA_UNKNOWN;
                 } else if (qstrncmp(rgba, "rgb", 3) == 0) {
                     subpixel = FC_RGBA_RGB;
                 } else if (qstrncmp(rgba, "bgr", 3) == 0) {
                     subpixel = FC_RGBA_BGR;
                 } else if (qstrncmp(rgba, "vrgb", 4) == 0) {
                     subpixel = FC_RGBA_VRGB;
                 } else if (qstrncmp(rgba, "vbgr", 4) == 0) {
                     subpixel = FC_RGBA_VBGR;
                 } else if (qstrncmp(rgba, "none", 4) == 0) {
                     subpixel = FC_RGBA_NONE;
                 }
             }
             X11->screens[s].subpixel = subpixel;
         }
         getXDefault("Xft", FC_ANTIALIAS, &X11->fc_antialias);
 #ifdef FC_HINT_STYLE
         X11->fc_hint_style = -1;
         getXDefault("Xft", FC_HINT_STYLE, &X11->fc_hint_style);
 #endif
 #if 0
         // ###### these are implemented by Xft, not sure we need them
         getXDefault("Xft", FC_AUTOHINT, &X11->fc_autohint);
         getXDefault("Xft", FC_HINTING, &X11->fc_autohint);
         getXDefault("Xft", FC_MINSPACE, &X11->fc_autohint);
 #endif
 #endif // QT_NO_XRENDER
         // initialize key mapper
         QKeyMapper::changeKeyboard();
         // Misc. initialization
 #if 0 //disabled for now..
         QSegfaultHandler::initialize(priv->argv, priv->argc);
 #endif
         QCursorData::initialize();
     }
     QFont::initialize();
     if(qt_is_gui_used) {
         qApp->setObjectName(QString::fromLocal8Bit(appName));
         int screen;
         for (screen = 0; screen < X11->screenCount; ++screen) {
             XSelectInput(X11->display, QX11Info::appRootWindow(screen),
                          KeymapStateMask | EnterWindowMask | LeaveWindowMask | PropertyChangeMask);
 #ifndef QT_NO_XRANDR
             if (X11->use_xrandr)
                 X11->ptrXRRSelectInput(X11->display, QX11Info::appRootWindow(screen), True);
 #endif // QT_NO_XRANDR
         }
     }
     if (qt_is_gui_used) {
         // Attempt to determine the current running X11 Desktop Enviornment
         // Use dbus if/when we can, but fall back to using windowManagerName() for now
 #ifndef QT_NO_XFIXES
         if (X11->ptrXFixesSelectSelectionInput)
             X11->ptrXFixesSelectSelectionInput(X11->display, QX11Info::appRootWindow(), ATOM(_NET_WM_CM_S0),
                                        XFixesSetSelectionOwnerNotifyMask
                                        | XFixesSelectionWindowDestroyNotifyMask
                                        | XFixesSelectionClientCloseNotifyMask);
 #endif // QT_NO_XFIXES
         X11->compositingManagerRunning = XGetSelectionOwner(X11->display,
                                                             ATOM(_NET_WM_CM_S0));
         X11->desktopEnvironment = DE_UNKNOWN;
         X11->desktopVersion = 0;
         Atom type;
         int format;
         unsigned long length, after;
         uchar *data = 0;
         int rc;
         do {
             if (!qgetenv("KDE_FULL_SESSION").isEmpty()) {
                 X11->desktopEnvironment = DE_KDE;
                 X11->desktopVersion = qgetenv("KDE_SESSION_VERSION").toInt();
                 break;
             }
             if (qgetenv("DESKTOP_SESSION") == "gnome") {
                 X11->desktopEnvironment = DE_GNOME;
                 break;
             }
             // GNOME_DESKTOP_SESSION_ID is deprecated for some reason, but still check it
             if (!qgetenv("GNOME_DESKTOP_SESSION_ID").isEmpty()) {
                 X11->desktopEnvironment = DE_GNOME;
                 break;
             }
             rc = XGetWindowProperty(X11->display, QX11Info::appRootWindow(), ATOM(_DT_SAVE_MODE),
                                     0, 2, False, XA_STRING, &type, &format, &length,
                                     &after, &data);
             if (rc == Success && length) {
                 if (!strcmp(reinterpret_cast<char *>(data), "xfce4")) {
                     // Pretend that xfce4 is gnome, as it uses the same libraries.
                     // The detection above is stolen from xdg-open.
                     X11->desktopEnvironment = DE_GNOME;
                     break;
                 }
                 // We got the property but it wasn't xfce4. Free data before it gets overwritten.
                 XFree(data);
                 data = 0;
             }
             rc = XGetWindowProperty(X11->display, QX11Info::appRootWindow(), ATOM(DTWM_IS_RUNNING),
                                     0, 1, False, AnyPropertyType, &type, &format, &length,
                                     &after, &data);
             if (rc == Success && length) {
                 // DTWM is running, meaning most likely CDE is running...
                 X11->desktopEnvironment = DE_CDE;
                 break;
             }
             rc = XGetWindowProperty(X11->display, QX11Info::appRootWindow(),
                                     ATOM(_SGI_DESKS_MANAGER), 0, 1, False, XA_WINDOW,
                                     &type, &format, &length, &after, &data);
             if (rc == Success && length) {
                 X11->desktopEnvironment = DE_4DWM;
                 break;
             }
             if (XGetWindowProperty(X11->display, QX11Info::appRootWindow(),
                                ATOM(_NET_SUPPORTING_WM_CHECK),
                                0, 1024, False, XA_WINDOW, &type,
                                &format, &length, &after, &data) == Success) {
                 if (type == XA_WINDOW && format == 32) {
                     Window windowManagerWindow = *((Window*) data);
                     XFree(data);
                     data = 0;
                     if (windowManagerWindow != XNone) {
                         Atom utf8atom = ATOM(UTF8_STRING);
                         if (XGetWindowProperty(QX11Info::display(), windowManagerWindow, ATOM(_NET_WM_NAME),
                                                0, 1024, False, utf8atom, &type,
                                                &format, &length, &after, &data) == Success) {
                             if (type == utf8atom && format == 8) {
                                 if (qstrcmp((const char *)data, "MCompositor") == 0)
                                     X11->desktopEnvironment = DE_MEEGO_COMPOSITOR;
                             }
                         }
                     }
                 }
             }
         } while(0);
         if (data)
             XFree((char *)data);
 #if !defined(QT_NO_STYLE_GTK)
         if (X11->desktopEnvironment == DE_GNOME) {
             static bool menusHaveIcons = QGtkStyle::getGConfBool(QLatin1String("/desktop/gnome/interface/menus_have_icons"), true);
             QApplication::setAttribute(Qt::AA_DontShowIconsInMenus, !menusHaveIcons);
         }
 #endif
         qt_set_input_encoding();
         qt_set_x11_resources(appFont, appFGCol, appBGCol, appBTNCol);
         // be smart about the size of the default font. most X servers have helvetica
         // 12 point available at 2 resolutions:
         //     75dpi (12 pixels) and 100dpi (17 pixels).
         // At 95 DPI, a 12 point font should be 16 pixels tall - in which case a 17
         // pixel font is a closer match than a 12 pixel font
         int ptsz = (X11->use_xrender
                     ? 9
                     : (int) (((QX11Info::appDpiY() >= 95 ? 17. : 12.) *
                               72. / (float) QX11Info::appDpiY()) + 0.5));
         if (!QApplicationPrivate::sys_font) {
             // no font from settings or RESOURCE_MANAGER, provide a fallback
             QFont f(X11->has_fontconfig ? QLatin1String("Sans Serif") : QLatin1String("Helvetica"),
                     ptsz);
             QApplicationPrivate::setSystemFont(f);
         }
 #if !defined (QT_NO_TABLET)
         if (X11->use_xinput) {
             int ndev,
                 i,
                 j;
             bool gotStylus,
                 gotEraser;
             XDeviceInfo *devices = 0, *devs;
             XInputClassInfo *ip;
             XAnyClassPtr any;
             XValuatorInfoPtr v;
             XAxisInfoPtr a;
             XDevice *dev = 0;
             if (X11->ptrXListInputDevices) {
                 devices = X11->ptrXListInputDevices(X11->display, &ndev);
                 if (!devices)
                     qWarning("QApplication: Failed to get list of tablet devices");
             }
             if (!devices)
                 ndev = -1;
             QTabletEvent::TabletDevice deviceType;
             for (devs = devices, i = 0; i < ndev && devs; i++, devs++) {
                 dev = 0;
                 deviceType = QTabletEvent::NoDevice;
                 gotStylus = false;
                 gotEraser = false;
 #if defined(Q_OS_IRIX)
                 QString devName = QString::fromLocal8Bit(devs->name).toLower();
                 if (devName == QLatin1String(WACOM_NAME)) {
                     deviceType = QTabletEvent::Stylus;
                     gotStylus = true;
                 }
 #else
                 // qDebug() << "found input device" << devs->name << "type" << devs->type << XGetAtomName(X11->display, devs->type);
                 if (devs->type == ATOM(XWacomStylus) || devs->type == ATOM(XTabletStylus) || devs->type == ATOM(XTablet)) {
                     deviceType = QTabletEvent::Stylus;
                     if (wacomDeviceName()->isEmpty())
                         wacomDeviceName()->append(devs->name);
                     gotStylus = true;
                 } else if (devs->type == ATOM(XWacomEraser) || devs->type == ATOM(XTabletEraser)) {
                     deviceType = QTabletEvent::XFreeEraser;
                     gotEraser = true;
                 }
 #endif
                 if (deviceType == QTabletEvent::NoDevice)
                     continue;
                 if (gotStylus || gotEraser) {
                     if (X11->ptrXOpenDevice)
                         dev = X11->ptrXOpenDevice(X11->display, devs->id);
                     if (!dev)
                         continue;
                     QTabletDeviceData device_data;
                     device_data.deviceType = deviceType;
                     device_data.eventCount = 0;
                     device_data.device = dev;
                     device_data.xinput_motion = -1;
                     device_data.xinput_key_press = -1;
                     device_data.xinput_key_release = -1;
                     device_data.xinput_button_press = -1;
                     device_data.xinput_button_release = -1;
                     device_data.xinput_proximity_in = -1;
                     device_data.xinput_proximity_out = -1;
                     device_data.widgetToGetPress = 0;
                     if (dev->num_classes > 0) {
                         for (ip = dev->classes, j = 0; j < dev->num_classes;
                              ip++, j++) {
                             switch (ip->input_class) {
                             case KeyClass:
                                 DeviceKeyPress(dev, device_data.xinput_key_press,
                                                device_data.eventList[device_data.eventCount]);
                                 if (device_data.eventList[device_data.eventCount])
                                     ++device_data.eventCount;
                                 DeviceKeyRelease(dev, device_data.xinput_key_release,
                                                  device_data.eventList[device_data.eventCount]);
                                 if (device_data.eventList[device_data.eventCount])
                                     ++device_data.eventCount;
                                 break;
                             case ButtonClass:
                                 DeviceButtonPress(dev, device_data.xinput_button_press,
                                                   device_data.eventList[device_data.eventCount]);
                                 if (device_data.eventList[device_data.eventCount])
                                     ++device_data.eventCount;
                                 DeviceButtonRelease(dev, device_data.xinput_button_release,
                                                     device_data.eventList[device_data.eventCount]);
                                 if (device_data.eventList[device_data.eventCount])
                                     ++device_data.eventCount;
                                 break;
                             case ValuatorClass:
                                 // I'm only going to be interested in motion when the
                                 // stylus is already down anyway!
                                 DeviceMotionNotify(dev, device_data.xinput_motion,
                                                    device_data.eventList[device_data.eventCount]);
                                 if (device_data.eventList[device_data.eventCount])
                                     ++device_data.eventCount;
                                 ProximityIn(dev, device_data.xinput_proximity_in, device_data.eventList[device_data.eventCount]);
                                 if (device_data.eventList[device_data.eventCount])
                                     ++device_data.eventCount;
                                 ProximityOut(dev, device_data.xinput_proximity_out, device_data.eventList[device_data.eventCount]);
                                 if (device_data.eventList[device_data.eventCount])
                                     ++device_data.eventCount;
                             default:
                                 break;
                             }
                         }
                     }
                     // get the min/max value for pressure!
                     any = (XAnyClassPtr) (devs->inputclassinfo);
                     for (j = 0; j < devs->num_classes; j++) {
                         if (any->c_class == ValuatorClass) {
                             v = (XValuatorInfoPtr) any;
                             a = (XAxisInfoPtr) ((char *) v +
                                                 sizeof (XValuatorInfo));
 #if defined (Q_OS_IRIX)
                             // I'm not exaclty wild about this, but the
                             // dimensions of the tablet are more relevant here
                             // than the min and max values from the axis
                             // (actually it seems to be 2/3 or what is in the
                             // axis.  So we'll try to parse it from this
                             // string. --tws
                             char returnString[SGIDeviceRtrnLen];
                             int tmp;
                             if (XSGIMiscQueryExtension(X11->display, &tmp, &tmp)
                                 && XSGIDeviceQuery(X11->display, devs->id,
                                                    "dimensions", returnString)) {
                                 QString str = QLatin1String(returnString);
                                 int comma = str.indexOf(',');
                                 device_data.minX = 0;
                                 device_data.minY = 0;
                                 device_data.maxX = str.left(comma).toInt();
                                 device_data.maxY = str.mid(comma + 1).toInt();
                             } else {
                                 device_data.minX = a[WAC_XCOORD_I].min_value;
                                 device_data.maxX = a[WAC_XCOORD_I].max_value;
                                 device_data.minY = a[WAC_YCOORD_I].min_value;
                                 device_data.maxY = a[WAC_YCOORD_I].max_value;
                             }
                             device_data.minPressure = a[WAC_PRESSURE_I].min_value;
                             device_data.maxPressure = a[WAC_PRESSURE_I].max_value;
                             device_data.minTanPressure = a[WAC_TAN_PRESSURE_I].min_value;
                             device_data.maxTanPressure = a[WAC_TAN_PRESSURE_I].max_value;
                             device_data.minZ = a[WAC_ZCOORD_I].min_value;
                             device_data.maxZ = a[WAC_ZCOORD_I].max_value;
 #else
                             device_data.minX = a[0].min_value;
                             device_data.maxX = a[0].max_value;
                             device_data.minY = a[1].min_value;
                             device_data.maxY = a[1].max_value;
                             device_data.minPressure = a[2].min_value;
                             device_data.maxPressure = a[2].max_value;
                             device_data.minTanPressure = 0;
                             device_data.maxTanPressure = 0;
                             device_data.minZ = 0;
                             device_data.maxZ = 0;
 #endif
                             // got the max pressure no need to go further...
                             break;
                         }
                         any = (XAnyClassPtr) ((char *) any + any->length);
                     } // end of for loop
                     tablet_devices()->append(device_data);
                 } // if (gotStylus || gotEraser)
             }
             if (X11->ptrXFreeDeviceList)
                 X11->ptrXFreeDeviceList(devices);
         }
 #endif // QT_NO_TABLET
         X11->startupId = getenv("DESKTOP_STARTUP_ID");
         if (X11->startupId) {
 #ifndef QT_NO_UNSETENV
             unsetenv("DESKTOP_STARTUP_ID");
 #else
             // it's a small memory leak, however we won't crash if Qt is
             // unloaded and someones tries to use the envoriment.
             putenv(strdup("DESKTOP_STARTUP_ID="));
 #endif
         }
    } else {
         // read some non-GUI settings when not using the X server...
         if (QApplication::desktopSettingsAware()) {
             QSettings settings(QSettings::UserScope, QLatin1String("Trolltech"));
             settings.beginGroup(QLatin1String("Qt"));
             // read library (ie. plugin) path list
             QString libpathkey = QString::fromLatin1("%1.%2/libraryPath")
                                  .arg(QT_VERSION >> 16)
                                  .arg((QT_VERSION & 0xff00) >> 8);
             QStringList pathlist =
                 settings.value(libpathkey).toString().split(QLatin1Char(':'));
             if (! pathlist.isEmpty()) {
                 QStringList::ConstIterator it = pathlist.constBegin();
                 while (it != pathlist.constEnd())
                     QApplication::addLibraryPath(*it++);
             }
             QString defaultcodec = settings.value(QLatin1String("defaultCodec"),
                                                   QVariant(QLatin1String("none"))).toString();
             if (defaultcodec != QLatin1String("none")) {
                 QTextCodec *codec = QTextCodec::codecForName(defaultcodec.toLatin1());
                 if (codec)
                     QTextCodec::setCodecForTr(codec);
             }
             settings.endGroup(); // Qt
         }
     }
 #if !defined (Q_OS_IRIX) && !defined (QT_NO_TABLET)
     QLibrary wacom(QString::fromLatin1("wacomcfg"), 0); // version 0 is the latest release at time of writing this.
     wacom.setLoadHints(QLibrary::ImprovedSearchHeuristics);
     // NOTE: C casts instead of reinterpret_cast for GCC 3.3.x
     ptrWacomConfigInit = (PtrWacomConfigInit)wacom.resolve("WacomConfigInit");
     ptrWacomConfigOpenDevice = (PtrWacomConfigOpenDevice)wacom.resolve("WacomConfigOpenDevice");
     ptrWacomConfigGetRawParam  = (PtrWacomConfigGetRawParam)wacom.resolve("WacomConfigGetRawParam");
     ptrWacomConfigCloseDevice = (PtrWacomConfigCloseDevice)wacom.resolve("WacomConfigCloseDevice");
     ptrWacomConfigTerm = (PtrWacomConfigTerm)wacom.resolve("WacomConfigTerm");
     if (ptrWacomConfigInit == 0 || ptrWacomConfigOpenDevice == 0 || ptrWacomConfigGetRawParam == 0
         || ptrWacomConfigCloseDevice == 0 || ptrWacomConfigTerm == 0) { // either we have all, or we have none.
             ptrWacomConfigInit = 0;
             ptrWacomConfigOpenDevice = 0;
             ptrWacomConfigGetRawParam  = 0;
             ptrWacomConfigCloseDevice = 0;
             ptrWacomConfigTerm = 0;
     }
 #endif
 }
qt_installX11EventFilter()
Q_GUI_EXPORT void qt_installX11EventFilter (QX11FilterFunction func)
Definition at line 407 of file qapplication_x11.cpp.
Referenced by QMeeGoGraphicsSystemSwitchHandler::QMeeGoGraphicsSystemSwitchHandler().
 {
     Q_ASSERT(func);
     if (QList<QX11FilterFunction> *list = x11Filters())
         list->append(func);
 }
qt_load_library_runtime()
static void* qt_load_library_runtime (const char * library, int vernum, int highestVernum, const char * symbol) static
Try to resolve a symbol from library with the version specified by vernum.
Warning
This function is not part of the public interface.
Note that, in the case of the Xfixes library, vernum is not the same as XFIXES_MAJOR - it is a part of soname and may differ from the Xfixes version.
Definition at line 474 of file qapplication_x11.cpp.
 {
     QList<int> versions;
     // we try to load in the following order:
     // explicit version -> the default one -> (from the highest (highestVernum) to the lowest (vernum) )
     if (vernum != -1)
         versions << vernum;
     versions << -1;
     if (vernum != -1) {
         for(int i = highestVernum; i > vernum; --i)
             versions << i;
     }
     Q_FOREACH(int version, versions) {
         QLatin1String libName(library);
         QLibrary xfixesLib(libName, version);
         xfixesLib.setLoadHints(QLibrary::ImprovedSearchHeuristics);
         void *ptr = xfixesLib.resolve(symbol);
         if (ptr)
             return ptr;
     }
     return 0;
 }
qt_mouseMotion_scanner()
static Bool qt_mouseMotion_scanner (Display * , XEvent * event, XPointer arg) static
Definition at line 4662 of file qapplication_x11.cpp.
Referenced by QETWidget::translateXinputEvent().
 {
     qt_tablet_motion_data *data = (qt_tablet_motion_data *) arg;
     if (data->error)
         return false;
     if (event->type == MotionNotify)
         return true;
     data->error = event->type != data->tabletMotionType; // we stop compression when another event gets in between.
     return false;
 }
qt_net_remove_user_time()
void qt_net_remove_user_time (QWidget * tlw)
Definition at line 1508 of file qapplication_x11.cpp.
Referenced by QWidgetPrivate::isBackgroundInherited(), and qt_net_update_user_time().
 {
     Q_ASSERT(tlw);
     QTLWExtra *extra = tlw->d_func()->maybeTopData();
     if (extra && extra->userTimeWindow) {
         Q_ASSERT(tlw->internalWinId());
         XDeleteProperty(X11->display, tlw->internalWinId(), ATOM(_NET_WM_USER_TIME_WINDOW));
         XDestroyWindow(X11->display, extra->userTimeWindow);
         extra->userTimeWindow = 0;
     }
 }
qt_net_update_user_time()
void qt_net_update_user_time (QWidget * tlw, unsigned long timestamp)
Definition at line 1520 of file qapplication_x11.cpp.
Referenced by qstring_to_xtp(), and QApplication::x11ProcessEvent().
 {
     Q_ASSERT(tlw);
     Q_ASSERT(tlw->isWindow());
     Q_ASSERT(tlw->testAttribute(Qt::WA_WState_Created));
     QTLWExtra *extra = tlw->d_func()->topData();
     WId wid = tlw->internalWinId();
     const bool isSupportedByWM = X11->isSupportedByWM(ATOM(_NET_WM_USER_TIME_WINDOW));
     if (extra->userTimeWindow || isSupportedByWM) {
         if (!extra->userTimeWindow) {
             extra->userTimeWindow = XCreateSimpleWindow(X11->display,
                                                         tlw->internalWinId(),
                                                         -1, -1, 1, 1, 0, 0, 0);
             wid = extra->userTimeWindow;
             XChangeProperty(X11->display, tlw->internalWinId(), ATOM(_NET_WM_USER_TIME_WINDOW),
                             XA_WINDOW, 32, PropModeReplace,
                             (unsigned char *)&wid, 1);
             XDeleteProperty(X11->display, tlw->internalWinId(), ATOM(_NET_WM_USER_TIME));
         } else if (!isSupportedByWM) {
             // WM no longer supports it, then we should remove the
             // _NET_WM_USER_TIME_WINDOW atom.
             qt_net_remove_user_time(tlw);
         } else {
             wid = extra->userTimeWindow;
         }
     }
     XChangeProperty(X11->display, wid, ATOM(_NET_WM_USER_TIME),
                     XA_CARDINAL, 32, PropModeReplace, (unsigned char *) &timestamp, 1);
 }
qt_nograb()
bool qt_nograb ()
Definition at line 2825 of file qapplication_x11.cpp.
Referenced by QWidget::grabKeyboard(), QWidget::grabMouse(), qstring_to_xtp(), qt_grab_cursor(), qt_tablet_cleanup(), QWidget::releaseKeyboard(), and QWidget::releaseMouse().
 {
 #if defined(QT_DEBUG)
     return appNoGrab;
 #else
     return false;
 #endif
 }
qt_removeX11EventFilter()
Q_GUI_EXPORT void qt_removeX11EventFilter (QX11FilterFunction func)
Definition at line 415 of file qapplication_x11.cpp.
 {
     Q_ASSERT(func);
     if (QList<QX11FilterFunction> *list = x11Filters())
         list->removeOne(func);
 }
qt_save_rootinfo()
void qt_save_rootinfo () static
Definition at line 2762 of file qapplication_x11.cpp.
Referenced by qt_cleanup().
 {
     Atom type;
     int format;
     unsigned long length, after;
     uchar *data = 0;
     if (ATOM(_XSETROOT_ID)) {                        // kill old pixmap
         if (XGetWindowProperty(X11->display, QX11Info::appRootWindow(),
                                  ATOM(_XSETROOT_ID), 0, 1,
                                  True, AnyPropertyType, &type, &format,
                                  &length, &after, &data) == Success) {
             if (type == XA_PIXMAP && format == 32 && length == 1 &&
                  after == 0 && data) {
                 XKillClient(X11->display, *((Pixmap*)data));
             }
             Pixmap dummy = XCreatePixmap(X11->display, QX11Info::appRootWindow(),
                                           1, 1, 1);
             XChangeProperty(X11->display, QX11Info::appRootWindow(),
                              ATOM(_XSETROOT_ID), XA_PIXMAP, 32,
                              PropModeReplace, (uchar *)&dummy, 1);
             XSetCloseDownMode(X11->display, RetainPermanent);
         }
     }
     if (data)
         XFree((char *)data);
 }
qt_set_input_encoding()
static void qt_set_input_encoding () static
Definition at line 1092 of file qapplication_x11.cpp.
Referenced by QApplication::x11ProcessEvent().
 {
     Atom type;
     int format;
     ulong  nitems, after = 1;
     unsigned char *data = 0;
     int e = XGetWindowProperty(X11->display, QX11Info::appRootWindow(),
                                 ATOM(_QT_INPUT_ENCODING), 0, 1024,
                                 False, XA_STRING, &type, &format, &nitems,
                                 &after, &data);
     if (e != Success || !nitems || type == XNone) {
         // Always use the locale codec, since we have no examples of non-local
         // XIMs, and since we cannot get a sensible answer about the encoding
         // from the XIM.
         qt_input_mapper = QTextCodec::codecForLocale();
     } else {
         if (!qstricmp((char *)data, "locale"))
             qt_input_mapper = QTextCodec::codecForLocale();
         else
             qt_input_mapper = QTextCodec::codecForName((char *)data);
         // make sure we have an input codec
         if(!qt_input_mapper)
             qt_input_mapper = QTextCodec::codecForName("ISO 8859-1");
     }
     if (qt_input_mapper && qt_input_mapper->mibEnum() == 11) // 8859-8
         qt_input_mapper = QTextCodec::codecForName("ISO 8859-8-I");
     if(data)
         XFree((char *)data);
 }
qt_set_x11_resources()
static void qt_set_x11_resources (const char * font = 0, const char * fg = 0, const char * bg = 0, const char * button = 0) static
Definition at line 1126 of file qapplication_x11.cpp.
Referenced by QApplication::x11ProcessEvent().
 {
     QString resFont, resFG, resBG, resButton, resEF, sysFont, selectBackground, selectForeground;
     QApplication::setEffectEnabled(Qt::UI_General, false);
     QApplication::setEffectEnabled(Qt::UI_AnimateMenu, false);
     QApplication::setEffectEnabled(Qt::UI_FadeMenu, false);
     QApplication::setEffectEnabled(Qt::UI_AnimateCombo, false);
     QApplication::setEffectEnabled(Qt::UI_AnimateTooltip, false);
     QApplication::setEffectEnabled(Qt::UI_FadeTooltip, false);
     QApplication::setEffectEnabled(Qt::UI_AnimateToolBox, false);
     bool paletteAlreadySet = false;
     if (QApplication::desktopSettingsAware()) {
         // first, read from settings
         QApplicationPrivate::x11_apply_settings();
         // the call to QApplication::style() below creates the system
         // palette, which breaks the logic after the RESOURCE_MANAGER
         // loop... so I have to save this value to be able to use it later
         paletteAlreadySet = (QApplicationPrivate::sys_pal != 0);
         // second, parse the RESOURCE_MANAGER property
         int format;
         ulong  nitems, after = 1;
         QString res;
         long offset = 0;
         Atom type = XNone;
         while (after > 0) {
             uchar *data = 0;
             if (XGetWindowProperty(X11->display, QX11Info::appRootWindow(0),
                                    ATOM(RESOURCE_MANAGER),
                                    offset, 8192, False, AnyPropertyType,
                                    &type, &format, &nitems, &after,
                                    &data) != Success) {
                 res = QString();
                 break;
             }
             if (type == XA_STRING)
                 res += QString::fromLatin1((char*)data);
             else
                 res += QString::fromLocal8Bit((char*)data);
             offset += 2048; // offset is in 32bit quantities... 8192/4 == 2048
             if (data)
                 XFree((char *)data);
         }
         QString key, value;
         int l = 0, r;
         QString apn = QString::fromLocal8Bit(appName);
         QString apc = QString::fromLocal8Bit(appClass);
         int apnl = apn.length();
         int apcl = apc.length();
         int resl = res.length();
         while (l < resl) {
             r = res.indexOf(QLatin1Char('\n'), l);
             if (r < 0)
                 r = resl;
             while (res.at(l).isSpace())
                 l++;
             bool mine = false;
             QChar sc = res.at(l + 1);
             if (res.at(l) == QLatin1Char('*') &&
                 (sc == QLatin1Char('f') || sc == QLatin1Char('b') || sc == QLatin1Char('g') ||
                  sc == QLatin1Char('F') || sc == QLatin1Char('B') || sc == QLatin1Char('G') ||
                  sc == QLatin1Char('s') || sc == QLatin1Char('S')
                  // capital T only, since we're looking for "Text.selectSomething"
                  || sc == QLatin1Char('T'))) {
                 // OPTIMIZED, since we only want "*[fbgsT].."
                 QString item = res.mid(l, r - l).simplified();
                 int i = item.indexOf(QLatin1Char(':'));
                 key = item.left(i).trimmed().mid(1).toLower();
                 value = item.right(item.length() - i - 1).trimmed();
                 mine = true;
             } else if ((apnl && res.at(l) == apn.at(0)) || (appClass && apcl && res.at(l) == apc.at(0))) {
                 if (res.mid(l,apnl) == apn && (res.at(l+apnl) == QLatin1Char('.')
                                                || res.at(l+apnl) == QLatin1Char('*'))) {
                     QString item = res.mid(l, r - l).simplified();
                     int i = item.indexOf(QLatin1Char(':'));
                     key = item.left(i).trimmed().mid(apnl+1).toLower();
                     value = item.right(item.length() - i - 1).trimmed();
                     mine = true;
                 } else if (res.mid(l,apcl) == apc && (res.at(l+apcl) == QLatin1Char('.')
                                                       || res.at(l+apcl) == QLatin1Char('*'))) {
                     QString item = res.mid(l, r - l).simplified();
                     int i = item.indexOf(QLatin1Char(':'));
                     key = item.left(i).trimmed().mid(apcl+1).toLower();
                     value = item.right(item.length() - i - 1).trimmed();
                     mine = true;
                 }
             }
             if (mine) {
                 if (!font && key == QLatin1String("systemfont"))
                     sysFont = value.left(value.lastIndexOf(QLatin1Char(':')));
                 if (!font && key == QLatin1String("font"))
                     resFont = value;
                 else if (!fg && !paletteAlreadySet) {
                     if (key == QLatin1String("foreground"))
                         resFG = value;
                     else if (!bg && key == QLatin1String("background"))
                         resBG = value;
                     else if (!bg && !button && key == QLatin1String("button.background"))
                         resButton = value;
                     else if (key == QLatin1String("text.selectbackground")) {
                         selectBackground = value;
                     } else if (key == QLatin1String("text.selectforeground")) {
                         selectForeground = value;
                     }
                 } else if (key == QLatin1String("guieffects"))
                     resEF = value;
                 // NOTE: if you add more, change the [fbg] stuff above
             }
             l = r + 1;
         }
     }
     if (!sysFont.isEmpty())
         resFont = sysFont;
     if (resFont.isEmpty())
         resFont = QString::fromLocal8Bit(font);
     if (resFG.isEmpty())
         resFG = QString::fromLocal8Bit(fg);
     if (resBG.isEmpty())
         resBG = QString::fromLocal8Bit(bg);
     if (resButton.isEmpty())
         resButton = QString::fromLocal8Bit(button);
     if (!resFont.isEmpty()
         && !X11->has_fontconfig
         && !QApplicationPrivate::sys_font) {
         // set application font
         QFont fnt;
         fnt.setRawName(resFont);
         // the font we get may actually be an alias for another font,
         // so we reset the application font to the real font info.
         if (! fnt.exactMatch()) {
             QFontInfo fontinfo(fnt);
             fnt.setFamily(fontinfo.family());
             fnt.setRawMode(fontinfo.rawMode());
             if (! fnt.rawMode()) {
                 fnt.setItalic(fontinfo.italic());
                 fnt.setWeight(fontinfo.weight());
                 fnt.setUnderline(fontinfo.underline());
                 fnt.setStrikeOut(fontinfo.strikeOut());
                 fnt.setStyleHint(fontinfo.styleHint());
                 if (fnt.pointSize() <= 0 && fnt.pixelSize() <= 0) {
                     // size is all wrong... fix it
                     qreal pointSize = fontinfo.pixelSize() * 72. / (float) QX11Info::appDpiY();
                     if (pointSize <= 0)
                         pointSize = 12;
                     fnt.setPointSize(qRound(pointSize));
                 }
             }
         }
         QApplicationPrivate::setSystemFont(fnt);
     }
     // QGtkStyle sets it's own system palette
     bool gtkStyle = QApplicationPrivate::app_style && QApplicationPrivate::app_style->inherits("QGtkStyle");
     bool kdeColors = (QApplication::desktopSettingsAware() && X11->desktopEnvironment == DE_KDE);
     if (!gtkStyle && (kdeColors || (button || !resBG.isEmpty() || !resFG.isEmpty()))) {// set app colors
         bool allowX11ColorNames = QColor::allowX11ColorNames();
         QColor::setAllowX11ColorNames(true);
         (void) QApplication::style();  // trigger creation of application style and system palettes
         QColor btn;
         QColor bg;
         QColor fg;
         QColor bfg;
         QColor wfg;
         if (!resBG.isEmpty())
             bg = QColor(resBG);
         if (!bg.isValid())
             bg = QApplicationPrivate::sys_pal->color(QPalette::Active, QPalette::Window);
         if (!resFG.isEmpty())
             fg = QColor(resFG);
         if (!fg.isValid())
             fg = QApplicationPrivate::sys_pal->color(QPalette::Active, QPalette::WindowText);
         if (!resButton.isEmpty())
             btn = QColor(resButton);
         else if (!resBG.isEmpty())
             btn = bg;
         if (!btn.isValid())
             btn = QApplicationPrivate::sys_pal->color(QPalette::Active, QPalette::Button);
         int h,s,v;
         fg.getHsv(&h,&s,&v);
         QColor base = Qt::white;
         bool bright_mode = false;
         if (v >= 255 - 50) {
             base = btn.darker(150);
             bright_mode = true;
         }
         QPalette pal(fg, btn, btn.lighter(125), btn.darker(130), btn.darker(120), wfg.isValid() ? wfg : fg, Qt::white, base, bg);
         QColor disabled((fg.red()   + btn.red())  / 2,
                         (fg.green() + btn.green())/ 2,
                         (fg.blue()  + btn.blue()) / 2);
         pal.setColorGroup(QPalette::Disabled, disabled, btn, btn.lighter(125),
                           btn.darker(130), btn.darker(150), disabled, Qt::white, Qt::white, bg);
         QColor highlight, highlightText;
         if (!selectBackground.isEmpty() && !selectForeground.isEmpty()) {
             highlight = QColor(selectBackground);
             highlightText = QColor(selectForeground);
         }
         if (highlight.isValid() && highlightText.isValid()) {
             pal.setColor(QPalette::Highlight, highlight);
             pal.setColor(QPalette::HighlightedText, highlightText);
             // calculate disabled colors by removing saturation
             highlight.setHsv(highlight.hue(), 0, highlight.value(), highlight.alpha());
             highlightText.setHsv(highlightText.hue(), 0, highlightText.value(), highlightText.alpha());
             pal.setColor(QPalette::Disabled, QPalette::Highlight, highlight);
             pal.setColor(QPalette::Disabled, QPalette::HighlightedText, highlightText);
         } else if (bright_mode) {
             pal.setColor(QPalette::HighlightedText, base);
             pal.setColor(QPalette::Highlight, Qt::white);
             pal.setColor(QPalette::Disabled, QPalette::HighlightedText, base);
             pal.setColor(QPalette::Disabled, QPalette::Highlight, Qt::white);
         } else {
             pal.setColor(QPalette::HighlightedText, Qt::white);
             pal.setColor(QPalette::Highlight, Qt::darkBlue);
             pal.setColor(QPalette::Disabled, QPalette::HighlightedText, Qt::white);
             pal.setColor(QPalette::Disabled, QPalette::Highlight, Qt::darkBlue);
         }
         pal = qt_guiPlatformPlugin()->palette().resolve(pal);
         QApplicationPrivate::setSystemPalette(pal);
         QColor::setAllowX11ColorNames(allowX11ColorNames);
     }
     if (!resEF.isEmpty()) {
         QStringList effects = resEF.split(QLatin1Char(' '));
         QApplication::setEffectEnabled(Qt::UI_General, effects.contains(QLatin1String("general")));
         QApplication::setEffectEnabled(Qt::UI_AnimateMenu,
                                        effects.contains(QLatin1String("animatemenu")));
         QApplication::setEffectEnabled(Qt::UI_FadeMenu,
                                        effects.contains(QLatin1String("fademenu")));
         QApplication::setEffectEnabled(Qt::UI_AnimateCombo,
                                        effects.contains(QLatin1String("animatecombo")));
         QApplication::setEffectEnabled(Qt::UI_AnimateTooltip,
                                        effects.contains(QLatin1String("animatetooltip")));
         QApplication::setEffectEnabled(Qt::UI_FadeTooltip,
                                        effects.contains(QLatin1String("fadetooltip")));
         QApplication::setEffectEnabled(Qt::UI_AnimateToolBox,
                                        effects.contains(QLatin1String("animatetoolbox")));
     }
     QIconLoader::instance()->updateSystemTheme();
 }
qt_sync_request_scanner()
static Bool qt_sync_request_scanner (Display * , XEvent * event, XPointer arg) static
Definition at line 796 of file qapplication_x11.cpp.
Referenced by QETWidget::translateConfigEvent().
 {
     qt_sync_request_event_data *data =
         reinterpret_cast<qt_sync_request_event_data*>(arg);
     if (event->type == ClientMessage &&
         event->xany.window == data->window &&
         event->xclient.message_type == ATOM(WM_PROTOCOLS) &&
         (Atom)event->xclient.data.l[0] == ATOM(_NET_WM_SYNC_REQUEST)) {
         QWidget *w = QWidget::find(event->xany.window);
         if (QTLWExtra *tlw = ((QETWidget*)w)->d_func()->maybeTopData()) {
             const ulong timestamp = (const ulong) event->xclient.data.l[1];
             if (timestamp > X11->time)
                 X11->time = timestamp;
             if (timestamp == CurrentTime || timestamp > tlw->syncRequestTimestamp) {
                 tlw->syncRequestTimestamp = timestamp;
                 tlw->newCounterValueLo = event->xclient.data.l[2];
                 tlw->newCounterValueHi = event->xclient.data.l[3];
             }
         }
         return true;
     }
     return false;
 }
qt_tablet_devices()
QTabletDeviceDataList* qt_tablet_devices ()
Definition at line 395 of file qapplication_x11.cpp.
Referenced by getNetWmState(), qt_cleanup(), QETWidget::translateMouseEvent(), QETWidget::translateXinputEvent(), and QApplication::x11ProcessEvent().
 {
     return tablet_devices();
 }
qt_tabletMotion_scanner()
static Bool qt_tabletMotion_scanner (Display * , XEvent * event, XPointer arg) static
Definition at line 4675 of file qapplication_x11.cpp.
Referenced by QETWidget::translateXinputEvent().
 {
     qt_tablet_motion_data *data = (qt_tablet_motion_data *) arg;
     if (data->error)
         return false;
     if (event->type == data->tabletMotionType) {
         const XDeviceMotionEvent *const motion = reinterpret_cast<const XDeviceMotionEvent*>(event);
         if (data->filterByWidget) {
             const QPoint curr(motion->x, motion->y);
             const QWidget *w = data->etWidget;
             const QWidget *const child = w->childAt(curr);
             if (child) {
                 w = child;
             }
             if (w == data->widget)
                 return true;
         } else {
             return true;
         }
     }
     data->error = event->type != MotionNotify; // we stop compression when another event gets in between.
     return false;
 }
qt_try_modal()
bool qt_try_modal (QWidget * widget, XEvent * event)
Definition at line 3995 of file qapplication_x11.cpp.
Referenced by QApplication::x11ProcessEvent().
 {
     if (qt_xdnd_dragging) {
         // allow mouse events while DnD is active
         switch (event->type) {
         case ButtonPress:
         case ButtonRelease:
         case MotionNotify:
             return true;
         default:
             break;
         }
     }
     // allow mouse release events to be sent to widgets that have been pressed
     if (event->type == ButtonRelease) {
         QWidget *alienWidget = widget->childAt(widget->mapFromGlobal(QPoint(event->xbutton.x_root,
                                                                             event->xbutton.y_root)));
         if (widget == qt_button_down || (alienWidget && alienWidget == qt_button_down))
             return true;
     }
     if (QApplicationPrivate::tryModalHelper(widget))
         return true;
     // disallow mouse/key events
     switch (event->type) {
     case ButtonPress:
     case ButtonRelease:
     case MotionNotify:
     case XKeyPress:
     case XKeyRelease:
     case EnterNotify:
     case LeaveNotify:
     case ClientMessage:
         return false;
     default:
         break;
     }
     return true;
 }
qt_updated_rootinfo()
void qt_updated_rootinfo ()
Definition at line 2790 of file qapplication_x11.cpp.
 {
     app_save_rootinfo = true;
 }
qt_wstate_iconified()
bool qt_wstate_iconified (WId winid)
Definition at line 2796 of file qapplication_x11.cpp.
 {
     Atom type;
     int format;
     unsigned long length, after;
     uchar *data = 0;
     int r = XGetWindowProperty(X11->display, winid, ATOM(WM_STATE), 0, 2,
                                  False, AnyPropertyType, &type, &format,
                                  &length, &after, &data);
     bool iconic = false;
     if (r == Success && data && format == 32) {
         // quint32 *wstate = (quint32*)data;
         unsigned long *wstate = (unsigned long *) data;
         iconic = (*wstate == IconicState);
         XFree((char *)data);
     }
     return iconic;
 }
qt_x11_apply_settings_in_all_apps()
Q_GUI_EXPORT void qt_x11_apply_settings_in_all_apps ()
Definition at line 853 of file qapplication_x11.cpp.
 {
     QByteArray stamp;
     QDataStream s(&stamp, QIODevice::WriteOnly);
     s << QDateTime::currentDateTime();
     XChangeProperty(QX11Info::display(), QX11Info::appRootWindow(0),
                     ATOM(_QT_SETTINGS_TIMESTAMP), ATOM(_QT_SETTINGS_TIMESTAMP), 8,
                     PropModeReplace, (unsigned char *)stamp.data(), stamp.size());
 }
qt_x11_create_intern_atoms()
static void qt_x11_create_intern_atoms () static
Definition at line 825 of file qapplication_x11.cpp.
Referenced by qt_init().
 {
     const char *names[QX11Data::NAtoms];
     const char *ptr = x11_atomnames;
     int i = 0;
     while (*ptr) {
         names[i++] = ptr;
         while (*ptr)
             ++ptr;
         ++ptr;
     }
     Q_ASSERT(i == QX11Data::NPredefinedAtoms);
     QByteArray settings_atom_name("_QT_SETTINGS_TIMESTAMP_");
     settings_atom_name += XDisplayName(X11->displayName);
     names[i++] = settings_atom_name;
     Q_ASSERT(i == QX11Data::NAtoms);
 #if defined(XlibSpecificationRelease) && (XlibSpecificationRelease >= 6)
     XInternAtoms(X11->display, (char **)names, i, False, X11->atoms);
 #else
     for (i = 0; i < QX11Data::NAtoms; ++i)
         X11->atoms[i] = XInternAtom(X11->display, (char *)names[i], False);
 #endif
 }
qt_x11EventFilter()
static bool qt_x11EventFilter (XEvent * ev) static
Definition at line 424 of file qapplication_x11.cpp.
Referenced by QETWidget::translateConfigEvent(), QETWidget::translateMouseEvent(), QETWidget::translatePaintEvent(), and QApplication::x11ProcessEvent().
 {
     long unused;
     if (qApp->filterEvent(ev, &unused))
         return true;
     if (const QList<QX11FilterFunction> *list = x11Filters()) {
         for (QList<QX11FilterFunction>::const_iterator it = list->constBegin(); it != list->constEnd(); ++it) {
             if ((*it)(ev))
                 return true;
         }
     }
     return qApp->x11EventFilter(ev);
 }
qt_x_errhandler()
static int qt_x_errhandler (Display * dpy, XErrorEvent * err) static
Definition at line 655 of file qapplication_x11.cpp.
Referenced by QGtkStylePrivate::getIconThemeName(), QGtkStylePrivate::initGtkWidgets(), and qt_init().
 {
     if (X11->display != dpy) {
         // only handle X errors for our display
         return 0;
     }
     switch (err->error_code) {
     case BadAtom:
         if (err->request_code == 20 /* X_GetProperty */
             && (err->resourceid == XA_RESOURCE_MANAGER
                 || err->resourceid == XA_RGB_DEFAULT_MAP
                 || err->resourceid == ATOM(_NET_SUPPORTED)
                 || err->resourceid == ATOM(_NET_SUPPORTING_WM_CHECK)
                 || err->resourceid == ATOM(XdndProxy)
                 || err->resourceid == ATOM(XdndAware))) {
             // Perhaps we're running under SECURITY reduction? :/
             return 0;
         }
         break;
     case BadWindow:
         if (err->request_code == 2 /* X_ChangeWindowAttributes */
             || err->request_code == 38 /* X_QueryPointer */) {
             for (int i = 0; i < ScreenCount(dpy); ++i) {
                 if (err->resourceid == RootWindow(dpy, i)) {
                     // Perhaps we're running under SECURITY reduction? :/
                     return 0;
                 }
             }
         }
         X11->seen_badwindow = true;
         if (err->request_code == 25 /* X_SendEvent */) {
             for (int i = 0; i < ScreenCount(dpy); ++i) {
                 if (err->resourceid == RootWindow(dpy, i)) {
                     // Perhaps we're running under SECURITY reduction? :/
                     return 0;
                 }
             }
             if (X11->xdndHandleBadwindow()) {
                 qDebug("xdndHandleBadwindow returned true");
                 return 0;
             }
         }
         if (X11->ignore_badwindow)
             return 0;
         break;
     default:
 #if !defined(QT_NO_XINPUT)
         if (err->request_code == X11->xinput_major
             && err->error_code == (X11->xinput_errorbase + XI_BadDevice)
             && err->minor_code == 3 /* X_OpenDevice */) {
             return 0;
         }
 #endif
         break;
     }
     char errstr[256];
     XGetErrorText( dpy, err->error_code, errstr, 256 );
     char buffer[256];
     char request_str[256];
     qsnprintf(buffer, 256, "%d", err->request_code);
     XGetErrorDatabaseText(dpy, "XRequest", buffer, "", request_str, 256);
     if (err->request_code < 128) {
         // X error for a normal protocol request
         qWarning( "X Error: %s %d\n"
                   "  Major opcode: %d (%s)\n"
                   "  Resource id:  0x%lx",
                   errstr, err->error_code,
                   err->request_code,
                   request_str,
                   err->resourceid );
     } else {
         // X error for an extension request
         const char *extensionName = 0;
         if (err->request_code == X11->xrender_major)
             extensionName = "RENDER";
         else if (err->request_code == X11->xrandr_major)
             extensionName = "RANDR";
         else if (err->request_code == X11->xinput_major)
             extensionName = "XInputExtension";
         else if (err->request_code == X11->mitshm_major)
             extensionName = "MIT-SHM";
 #ifndef QT_NO_XKB
         else if(err->request_code == X11->xkb_major)
             extensionName = "XKEYBOARD";
 #endif
         char minor_str[256];
         if (extensionName) {
             qsnprintf(buffer, 256, "%s.%d", extensionName, err->minor_code);
             XGetErrorDatabaseText(dpy, "XRequest", buffer, "", minor_str, 256);
         } else {
             extensionName = "Uknown extension";
             qsnprintf(minor_str, 256, "Unknown request");
         }
         qWarning( "X Error: %s %d\n"
                   "  Extension:    %d (%s)\n"
                   "  Minor opcode: %d (%s)\n"
                   "  Resource id:  0x%lx",
                   errstr, err->error_code,
                   err->request_code,
                   extensionName,
                   err->minor_code,
                   minor_str,
                   err->resourceid );
     }
     // ### we really should distinguish between severe, non-severe and
     // ### application specific errors
     return 0;
 }
qt_xfixes_clipboard_changed()
bool qt_xfixes_clipboard_changed (Window clipboardOwner, Time timestamp)
Definition at line 1538 of file qclipboard_x11.cpp.
Referenced by QApplication::x11ProcessEvent().
 {
     QClipboardData *d = clipboardData();
 #ifdef QCLIPBOARD_DEBUG
     DEBUG("qt_xfixes_clipboard_changed: owner = %u; clipboardOwner = %u; internal timestamp = %u; external timestamp = %u",
           (unsigned int)(owner ? (int)owner->internalWinId() : 0), (unsigned int)clipboardOwner,
           (unsigned int)(d ? d->timestamp : 0), (unsigned int)timestamp);
 #endif
     if (!owner || (clipboardOwner && clipboardOwner != owner->internalWinId()) ||
         (!clipboardOwner && (d->timestamp == CurrentTime || d->timestamp < timestamp)))
         return qt_check_clipboard_sentinel();
     return false;
 }
qt_xfixes_scanner()
static Bool qt_xfixes_scanner (Display * , XEvent * event, XPointer arg) static
Definition at line 549 of file qapplication_x11.cpp.
Referenced by QApplication::x11ProcessEvent().
 {
     qt_xfixes_selection_event_data *data =
         reinterpret_cast<qt_xfixes_selection_event_data*>(arg);
     if (event->type == X11->xfixes_eventbase + XFixesSelectionNotify) {
         XFixesSelectionNotifyEvent *xfixes_event = reinterpret_cast<XFixesSelectionNotifyEvent*>(event);
         if (xfixes_event->selection == data->selection)
             return true;
     }
     return false;
 }
qt_xfixes_selection_changed()
bool qt_xfixes_selection_changed (Window selectionOwner, Time timestamp)
Definition at line 1524 of file qclipboard_x11.cpp.
Referenced by QApplication::x11ProcessEvent().
 {
     QClipboardData *d = selectionData();
 #ifdef QCLIPBOARD_DEBUG
     DEBUG("qt_xfixes_selection_changed: owner = %u; selectionOwner = %u; internal timestamp = %u; external timestamp = %u",
           (unsigned int)(owner ? (int)owner->internalWinId() : 0), (unsigned int)selectionOwner,
           (unsigned int)(d ? d->timestamp : 0), (unsigned int)timestamp);
 #endif
     if (!owner || (selectionOwner && selectionOwner != owner->internalWinId()) ||
         (!selectionOwner && (d->timestamp == CurrentTime || d->timestamp < timestamp)))
         return qt_check_selection_sentinel();
     return false;
 }
qt_xio_errhandler()
static int qt_xio_errhandler (Display *) static
Definition at line 772 of file qapplication_x11.cpp.
Referenced by qt_init().
 {
     qWarning("%s: Fatal IO error: client killed", appName);
     QApplicationPrivate::reset_instance_pointer();
     exit(1);
     //### give the application a chance for a proper shutdown instead,
     //### exit(1) doesn't help.
     return 0;
 }
resetSmState()
static void resetSmState () static
Definition at line 5618 of file qapplication_x11.cpp.
Referenced by sm_dieCallback(), sm_saveCompleteCallback(), sm_saveYourselfCallback(), sm_shutdownCancelledCallback(), and QSmSocketReceiver::socketActivated().
 {
 //    sm_waitingForPhase2 = false; ### never used?!?
     sm_waitingForInteraction = false;
     sm_interactionActive = false;
     sm_interactStyle = SmInteractStyleNone;
     sm_smActive = false;
     qt_sm_blockUserInput = false;
     sm_isshutdown = false;
 //    sm_shouldbefast = false; ### never used?!?
     sm_phase2 = false;
     sm_in_phase2 = false;
 }
runningUnderDebugger()
bool runningUnderDebugger ()
Definition at line 1641 of file qapplication_x11.cpp.
Referenced by qt_init().
 {
     const QString parentProc = QLatin1String("/proc/") + QString::number(getppid());
     const QFileInfo parentProcExe(parentProc + QLatin1String("/exe"));
     if (parentProcExe.isSymLink())
         return parentProcExe.symLinkTarget().endsWith(QLatin1String("/gdb"));
     QFile f(parentProc + QLatin1String("/cmdline"));
     if (!f.open(QIODevice::ReadOnly))
         return false;
     QByteArray s;
     char c;
     while (f.getChar(&c) && c) {
         if (c == '/')
             s.clear();
         else
             s += c;
     }
     return s == "gdb";
 }
sm_dieCallback()
static void sm_dieCallback (SmcConn smcConn, SmPointer clientData) static
Definition at line 5811 of file qapplication_x11.cpp.
Referenced by QSmSocketReceiver::socketActivated().
 {
     if (smcConn != smcConnection)
         return;
     resetSmState();
     QEvent quitEvent(QEvent::Quit);
     QApplication::sendEvent(qApp, &quitEvent);
 }
sm_interactCallback()
static void sm_interactCallback (SmcConn smcConn, SmPointer clientData) static
Definition at line 5836 of file qapplication_x11.cpp.
Referenced by QSmSocketReceiver::socketActivated().
 {
     if (smcConn != smcConnection)
         return;
     if (sm_waitingForInteraction)
         ((QSessionManagerPrivate *) clientData)->eventLoop->exit();
 }
sm_performSaveYourself()
static void sm_performSaveYourself (QSessionManagerPrivate * smd) static
Definition at line 5710 of file qapplication_x11.cpp.
Referenced by sm_saveYourselfCallback(), and sm_saveYourselfPhase2Callback().
 {
     if (sm_isshutdown)
         qt_sm_blockUserInput = true;
     QSessionManager* sm = smd->sm;
     // generate a new session key
     timeval tv;
     gettimeofday(&tv, 0);
     smd->sessionKey  = QString::number(qulonglong(tv.tv_sec)) + QLatin1Char('_') + QString::number(qulonglong(tv.tv_usec));
     QStringList arguments = qApp->arguments();
     QString argument0 = arguments.isEmpty() ? qApp->applicationFilePath() : arguments.at(0);
     // tell the session manager about our program in best POSIX style
     sm_setProperty(QString::fromLatin1(SmProgram), argument0);
     // tell the session manager about our user as well.
     struct passwd *entryPtr = 0;
 #if defined(_POSIX_THREAD_SAFE_FUNCTIONS) && (_POSIX_THREAD_SAFE_FUNCTIONS - 0 > 0)
     QVarLengthArray<char, 1024> buf(qMax<long>(sysconf(_SC_GETPW_R_SIZE_MAX), 1024L));
     struct passwd entry;
     while (getpwuid_r(geteuid(), &entry, buf.data(), buf.size(), &entryPtr) == ERANGE) {
         if (buf.size() >= 32768) {
             // too big already, fail
             static char badusername[] = "";
             entryPtr = &entry;
             entry.pw_name = badusername;
             break;
         }
         // retry with a bigger buffer
         buf.resize(buf.size() * 2);
     }
 #else
     entryPtr = getpwuid(geteuid());
 #endif
     if (entryPtr)
         sm_setProperty(QString::fromLatin1(SmUserID), QString::fromLatin1(entryPtr->pw_name));
     // generate a restart and discard command that makes sense
     QStringList restart;
     restart  << argument0 << QLatin1String("-session")
              << smd->sessionId + QLatin1Char('_') + smd->sessionKey;
     if (qstricmp(appName, QX11Info::appClass()) != 0)
         restart << QLatin1String("-name") << qAppName();
     sm->setRestartCommand(restart);
     QStringList discard;
     sm->setDiscardCommand(discard);
     switch (sm_saveType) {
     case SmSaveBoth:
         qApp->commitData(*sm);
         if (sm_isshutdown && sm_cancel)
             break; // we cancelled the shutdown, no need to save state
     // fall through
     case SmSaveLocal:
         qApp->saveState(*sm);
         break;
     case SmSaveGlobal:
         qApp->commitData(*sm);
         break;
     default:
         break;
     }
     if (sm_phase2 && !sm_in_phase2) {
         SmcRequestSaveYourselfPhase2(smcConnection, sm_saveYourselfPhase2Callback, (SmPointer*) smd);
         qt_sm_blockUserInput = false;
     }
     else {
         // close eventual interaction monitors and cancel the
         // shutdown, if required. Note that we can only cancel when
         // performing a shutdown, it does not work for checkpoints
         if (sm_interactionActive) {
             SmcInteractDone(smcConnection, sm_isshutdown && sm_cancel);
             sm_interactionActive = false;
         }
         else if (sm_cancel && sm_isshutdown) {
             if (sm->allowsErrorInteraction()) {
                 SmcInteractDone(smcConnection, True);
                 sm_interactionActive = false;
             }
         }
         // set restart and discard command in session manager
         sm_setProperty(QString::fromLatin1(SmRestartCommand), sm->restartCommand());
         sm_setProperty(QString::fromLatin1(SmDiscardCommand), sm->discardCommand());
         // set the restart hint
         SmPropValue prop;
         prop.length = sizeof(int);
         int value = sm->restartHint();
         prop.value = (SmPointer) &value;
         sm_setProperty(SmRestartStyleHint, SmCARD8, 1, &prop);
         // we are done
         SmcSaveYourselfDone(smcConnection, !sm_cancel);
     }
 }
sm_saveCompleteCallback()
static void sm_saveCompleteCallback (SmcConn smcConn, SmPointer clientData) static
Definition at line 5829 of file qapplication_x11.cpp.
Referenced by QSmSocketReceiver::socketActivated().
 {
     if (smcConn != smcConnection)
         return;
     resetSmState();
 }
sm_saveYourselfCallback()
static void sm_saveYourselfCallback (SmcConn smcConn, SmPointer clientData, int saveType, Bool shutdown, int interactStyle, Bool fast) static
Definition at line 5687 of file qapplication_x11.cpp.
Referenced by QSmSocketReceiver::socketActivated().
 {
     if (smcConn != smcConnection)
         return;
     sm_cancel = false;
     sm_smActive = true;
     sm_isshutdown = shutdown;
     sm_saveType = saveType;
     sm_interactStyle = interactStyle;
 //    sm_shouldbefast = fast; ### never used?!?
     // ugly workaround for broken libSM. libSM should do that _before_
     // actually invoking the callback in sm_process.c
     ((QT_smcConn*)smcConn)->save_yourself_in_progress = true;
     if (sm_isshutdown)
         ((QT_smcConn*)smcConn)->shutdown_in_progress = true;
     sm_performSaveYourself((QSessionManagerPrivate*) clientData);
     if (!sm_isshutdown) // we cannot expect a confirmation message in that case
         resetSmState();
 }
sm_saveYourselfPhase2Callback()
static void sm_saveYourselfPhase2Callback (SmcConn smcConn, SmPointer clientData) static
Definition at line 5844 of file qapplication_x11.cpp.
Referenced by sm_performSaveYourself().
 {
     if (smcConn != smcConnection)
         return;
     sm_in_phase2 = true;
     sm_performSaveYourself((QSessionManagerPrivate*) clientData);
 }
sm_setProperty() [1/3]
static void sm_setProperty (const char * name, const char * type, int num_vals, SmPropValue * vals) static
Definition at line 5635 of file qapplication_x11.cpp.
Referenced by sm_performSaveYourself(), and sm_setProperty().
 {
     if (num_vals) {
       SmProp prop;
       prop.name = (char*)name;
       prop.type = (char*)type;
       prop.num_vals = num_vals;
       prop.vals = vals;
       SmProp* props[1];
       props[0] = &prop;
       SmcSetProperties(smcConnection, 1, props);
     }
     else {
       char* names[1];
       names[0] = (char*) name;
       SmcDeleteProperties(smcConnection, 1, names);
     }
 }
sm_setProperty() [2/3]
static void sm_setProperty (const QString & name, const QString & value) static
Definition at line 5656 of file qapplication_x11.cpp.
 {
     QByteArray v = value.toUtf8();
     SmPropValue prop;
     prop.length = v.length();
     prop.value = (SmPointer) v.constData();
     sm_setProperty(name.toLatin1().data(), SmARRAY8, 1, &prop);
 }
sm_setProperty() [3/3]
static void sm_setProperty (const QString & name, const QStringList & value) static
Definition at line 5665 of file qapplication_x11.cpp.
 {
     SmPropValue *prop = new SmPropValue[value.count()];
     int count = 0;
     QList<QByteArray> vl;
     for (QStringList::ConstIterator it = value.begin(); it != value.end(); ++it) {
       prop[count].length = (*it).length();
       vl.append((*it).toUtf8());
       prop[count].value = (char*)vl.last().data();
       ++count;
     }
     sm_setProperty(name.toLatin1().data(), SmLISTofARRAY8, count, prop);
     delete [] prop;
 }
sm_shutdownCancelledCallback()
static void sm_shutdownCancelledCallback (SmcConn smcConn, SmPointer clientData) static
Definition at line 5820 of file qapplication_x11.cpp.
Referenced by QSmSocketReceiver::socketActivated().
 {
     if (smcConn != smcConnection)
         return;
     if (sm_waitingForInteraction)
         ((QSessionManagerPrivate *) clientData)->eventLoop->exit();
     resetSmState();
 }
translateBySips()
static bool translateBySips (QWidget * that, QRect & paintRect) static
Definition at line 5185 of file qapplication_x11.cpp.
Referenced by QETWidget::translatePaintEvent().
 {
     int dx=0, dy=0;
     int sips=0;
     for (int i = 0; i < X11->sip_list.size(); ++i) {
         const QX11Data::ScrollInProgress &sip = X11->sip_list.at(i);
         if (sip.scrolled_widget == that) {
             if (sips) {
                 dx += sip.dx;
                 dy += sip.dy;
             }
             sips++;
         }
     }
     if (sips > 1) {
         paintRect.translate(dx, dy);
         return true;
     }
     return false;
 }
translateMouseButtons()
static Qt::MouseButtons translateMouseButtons (int s) static
Definition at line 4186 of file qapplication_x11.cpp.
Referenced by QETWidget::translateMouseEvent().
 {
     Qt::MouseButtons ret = 0;
     if (s & Button1Mask)
         ret |= Qt::LeftButton;
     if (s & Button2Mask)
         ret |= Qt::MidButton;
     if (s & Button3Mask)
         ret |= Qt::RightButton;
     return ret;
 }
Variable Documentation
app_do_modal
bool app_do_modal = false static
Definition at line 352 of file qapplication_x11.cpp.
Referenced by QApplication::x11EventFilter(), and QApplication::x11ProcessEvent().
app_save_rootinfo
bool app_save_rootinfo = false static
Definition at line 351 of file qapplication_x11.cpp.
Referenced by qt_cleanup(), and qt_updated_rootinfo().
appBGCol
const char* appBGCol = 0 static
Definition at line 340 of file qapplication_x11.cpp.
Referenced by qt_init().
appBTNCol
const char* appBTNCol = 0 static
Definition at line 342 of file qapplication_x11.cpp.
Referenced by qt_init().
appClass
const char* appClass = 0 static
Definition at line 338 of file qapplication_x11.cpp.
Referenced by QX11Info::appClass(), qt_cleanup(), qt_init(), and qt_set_x11_resources().
appDoGrab
bool appDoGrab = false static
Definition at line 349 of file qapplication_x11.cpp.
Referenced by qt_init().
appFGCol
const char* appFGCol = 0 static
Definition at line 341 of file qapplication_x11.cpp.
Referenced by qt_init().
appFont
const char* appFont = 0 static
Definition at line 339 of file qapplication_x11.cpp.
Referenced by qt_init(), and QApplicationPrivate::x11_apply_settings().
appName
const char* appName = 0 static
Definition at line 337 of file qapplication_x11.cpp.
Referenced by qt_cleanup(), qt_init(), qt_set_x11_resources(), qt_wstate_iconified(), qt_xio_errhandler(), and sm_performSaveYourself().
appNoGrab
bool appNoGrab = false static
Definition at line 348 of file qapplication_x11.cpp.
Referenced by qt_init(), and qt_nograb().
appSync
bool appSync = false static
Definition at line 346 of file qapplication_x11.cpp.
Referenced by qt_init().
curWin
Window curWin = 0 static
Definition at line 353 of file qapplication_x11.cpp.
Referenced by QApplication::x11EventFilter(), and QApplication::x11ProcessEvent().
mouseActWindow
Window mouseActWindow = 0 static
Definition at line 373 of file qapplication_x11.cpp.
Referenced by QETWidget::translateMouseEvent().
mouseButtonPressed
Qt::MouseButton mouseButtonPressed = Qt::NoButton static
Definition at line 374 of file qapplication_x11.cpp.
Referenced by QETWidget::translateMouseEvent().
mouseButtonPressTime
Time mouseButtonPressTime = 0 static
Definition at line 376 of file qapplication_x11.cpp.
Referenced by QETWidget::translateMouseEvent().
mouseButtonState
Qt::MouseButtons mouseButtonState = Qt::NoButton static
Definition at line 375 of file qapplication_x11.cpp.
Referenced by QApplication::qwsProcessEvent(), and QETWidget::translateMouseEvent().
mouseGlobalXPos
short mouseGlobalXPos static
Definition at line 378 of file qapplication_x11.cpp.
Referenced by QETWidget::translateMouseEvent().
mouseGlobalYPos
short mouseGlobalYPos static
Definition at line 378 of file qapplication_x11.cpp.
Referenced by QETWidget::translateMouseEvent().
mouseXPos
short mouseXPos static
Definition at line 377 of file qapplication_x11.cpp.
Referenced by QETWidget::translateMouseEvent().
mouseYPos
short mouseYPos static
Definition at line 377 of file qapplication_x11.cpp.
Referenced by QETWidget::translateMouseEvent().
mwGeometry
const char* mwGeometry = 0 static
Definition at line 343 of file qapplication_x11.cpp.
Referenced by QApplicationPrivate::applyX11SpecificCommandLineArguments(), and qt_init().
mwTitle
const char* mwTitle = 0 static
Definition at line 344 of file qapplication_x11.cpp.
Referenced by QApplicationPrivate::applyX11SpecificCommandLineArguments(), and qt_init().
openPopupCount
int openPopupCount = 0 static
Definition at line 4054 of file qapplication_x11.cpp.
Referenced by QETWidget::translateMouseEvent().
original_x_errhandler
int(* original_x_errhandler) (Display *dpy, XErrorEvent *) static
Definition at line 652 of file qapplication_x11.cpp.
Referenced by qt_cleanup(), and qt_init().
original_xio_errhandler
int(* original_xio_errhandler) (Display *dpy) static
Definition at line 653 of file qapplication_x11.cpp.
Referenced by qt_cleanup(), and qt_init().
popupGrabOk
bool popupGrabOk static
Definition at line 387 of file qapplication_x11.cpp.
pressed_window
Window pressed_window = XNone static
Definition at line 383 of file qapplication_x11.cpp.
Referenced by QApplication::x11ProcessEvent().
ptrWacomConfigCloseDevice
PtrWacomConfigCloseDevice ptrWacomConfigCloseDevice = 0 static
Definition at line 1577 of file qapplication_x11.cpp.
Referenced by fetchWacomToolId().
ptrWacomConfigGetRawParam
PtrWacomConfigGetRawParam ptrWacomConfigGetRawParam = 0 static
Definition at line 1576 of file qapplication_x11.cpp.
Referenced by fetchWacomToolId().
ptrWacomConfigInit
PtrWacomConfigInit ptrWacomConfigInit = 0 static
Definition at line 1574 of file qapplication_x11.cpp.
Referenced by fetchWacomToolId().
ptrWacomConfigOpenDevice
PtrWacomConfigOpenDevice ptrWacomConfigOpenDevice = 0 static
Definition at line 1575 of file qapplication_x11.cpp.
Referenced by fetchWacomToolId().
ptrWacomConfigTerm
PtrWacomConfigTerm ptrWacomConfigTerm = 0 static
Definition at line 1578 of file qapplication_x11.cpp.
Referenced by fetchWacomToolId().
qt_alt_mask
uchar qt_alt_mask = 0
Definition at line 364 of file qapplication_x11.cpp.
Referenced by q_getKeyboardLocale(), translateModifiers(), and QX11Data::translateModifiers().
qt_button_down
QWidget* qt_button_down = 0
Definition at line 453 of file qapplication_x11.cpp.
Referenced by flipPoint(), QWidgetPrivate::paintBackground(), QMacWindowFader::performFade(), qt_mac_update_cursor(), qt_mac_updateCursorWithWidgetUnderMouse(), QApplicationPrivate::sendMouseEvent(), and QETWidget::translateMouseEvent().
qt_hyper_mask
uchar qt_hyper_mask = 0
Definition at line 367 of file qapplication_x11.cpp.
Referenced by q_getKeyboardLocale(), and translateKeySym().
qt_input_mapper
QTextCodec* qt_input_mapper = 0
Definition at line 443 of file qapplication_x11.cpp.
Referenced by translateKeySym().
qt_is_gui_used
bool qt_is_gui_used
Definition at line 492 of file qapplication.cpp.
Referenced by qt_cleanup(), and qt_init().
qt_last_mouse_receiver
QPointer<QWidget> qt_last_mouse_receiver = 0
Definition at line 454 of file qapplication_x11.cpp.
Referenced by QMacWindowFader::performFade(), QApplicationPrivate::sendMouseEvent(), QApplication::x11EventFilter(), and QApplication::x11ProcessEvent().
qt_meta_mask
uchar qt_meta_mask = 0
Definition at line 365 of file qapplication_x11.cpp.
Referenced by q_getKeyboardLocale(), translateKeySym(), translateModifiers(), and QX11Data::translateModifiers().
qt_modal_stack
QWidgetList* qt_modal_stack
Definition at line 564 of file qapplication.cpp.
Referenced by QApplication::x11EventFilter().
qt_mode_switch_mask
uchar qt_mode_switch_mask = 0
Definition at line 368 of file qapplication_x11.cpp.
Referenced by q_getKeyboardLocale(), and QX11Data::translateModifiers().
qt_popup_down
QWidget* qt_popup_down = 0 static
Definition at line 455 of file qapplication_x11.cpp.
qt_sm_blockUserInput
bool qt_sm_blockUserInput = false
Definition at line 389 of file qapplication_x11.cpp.
Referenced by qt_keyrelease_scanner(), resetSmState(), sm_performSaveYourself(), QETWidget::translateMouseEvent(), and QApplication::x11ProcessEvent().
qt_super_mask
uchar qt_super_mask = 0
Definition at line 366 of file qapplication_x11.cpp.
Referenced by q_getKeyboardLocale(), and translateKeySym().
qt_tabletChokeMouse
bool qt_tabletChokeMouse
Definition at line 526 of file qapplication.cpp.
Referenced by QApplication::notify(), qt_tablet_devices(), QETWidget::translateMouseEvent(), and QApplication::x11ProcessEvent().
qt_use_rtl_extensions
bool qt_use_rtl_extensions = false
Definition at line 371 of file qapplication_x11.cpp.
Referenced by QLineEdit::contextMenuEvent(), QTextControl::createStandardContextMenu(), QLineEdit::createStandardContextMenu(), getFontSet(), QKeyMapperPrivate::isADeadKey(), QWinInputContext::QWinInputContext(), QXIMInputContext::QXIMInputContext(), translateKeySym(), and QApplicationPrivate::x11_apply_settings().
qt_x11Data
QX11Data * qt_x11Data = 0
Definition at line 332 of file qapplication_x11.cpp.
Referenced by QX11Data::badwindow(), QX11Data::ignoreBadwindow(), and x11Time().
qt_xdnd_dragging
bool qt_xdnd_dragging
Definition at line 237 of file qdnd_x11.cpp.
Referenced by QX11Data::dndEnable(), findRealWindow(), qt_try_modal(), QETWidget::translateMouseEvent(), QApplication::x11ProcessEvent(), and QX11Data::xdndHandleDrop().
qt_xfocusout_grab_counter
Q_GUI_EXPORT int qt_xfocusout_grab_counter = 0
Definition at line 391 of file qapplication_x11.cpp.
Referenced by QApplication::x11ProcessEvent().
qt_ximComposingKeycode
int qt_ximComposingKeycode =0
Definition at line 442 of file qapplication_x11.cpp.
Referenced by translateKeySym(), and QXIMInputContext::x11FilterEvent().
qt_ximServer
char* qt_ximServer = 0
Definition at line 345 of file qapplication_x11.cpp.
Referenced by qt_init(), and QXIMInputContext::QXIMInputContext().
replayPopupMouseEvent
bool replayPopupMouseEvent = false static
Definition at line 386 of file qapplication_x11.cpp.
Referenced by QETWidget::translateMouseEvent().
sm_cancel
bool sm_cancel static
Definition at line 5596 of file qapplication_x11.cpp.
sm_in_phase2
bool sm_in_phase2 static
Definition at line 5602 of file qapplication_x11.cpp.
sm_interactionActive
bool sm_interactionActive static
Definition at line 5592 of file qapplication_x11.cpp.
sm_interactStyle
int sm_interactStyle static
Definition at line 5594 of file qapplication_x11.cpp.
sm_isshutdown
bool sm_isshutdown static
Definition at line 5599 of file qapplication_x11.cpp.
sm_phase2
bool sm_phase2 static
Definition at line 5601 of file qapplication_x11.cpp.
sm_receiver
QSmSocketReceiver* sm_receiver = 0 static
Definition at line 5604 of file qapplication_x11.cpp.
Referenced by QSmSocketReceiver::socketActivated().
sm_saveType
int sm_saveType static
Definition at line 5595 of file qapplication_x11.cpp.
sm_smActive
bool sm_smActive static
Definition at line 5593 of file qapplication_x11.cpp.
sm_waitingForInteraction
bool sm_waitingForInteraction static
Definition at line 5598 of file qapplication_x11.cpp.
smcConnection
SmcConn smcConnection = 0 static
Definition at line 5591 of file qapplication_x11.cpp.
Referenced by QSmSocketReceiver::socketActivated().
wPRmapper
QWidgetMapper* wPRmapper = 0 static
Definition at line 3111 of file qapplication_x11.cpp.
Referenced by qPRCleanup().
x11_atomnames
const char* x11_atomnames static
Definition at line 173 of file qapplication_x11.cpp.
Referenced by qt_x11_create_intern_atoms().