Qt 4.8: /src/gui/kernel/qapplication_win.cpp File Reference
qapplication_win.cpp File Reference
#include "qguifunctions_wince.h"
#include "qmenubar.h"
#include "qapplication.h"
#include "qdesktopwidget.h"
#include "qevent.h"
#include "private/qeventdispatcher_win_p.h"
#include "qeventloop.h"
#include "qclipboard.h"
#include "qcursor.h"
#include "qdatetime.h"
#include "qpointer.h"
#include "qhash.h"
#include "qmetaobject.h"
#include "qmime.h"
#include "qpainter.h"
#include "qpixmapcache.h"
#include "qsessionmanager.h"
#include "qstyle.h"
#include "qwhatsthis.h"
#include "qwidget.h"
#include "qcolormap.h"
#include "qlayout.h"
#include "qtooltip.h"
#include "qt_windows.h"
#include "qscrollbar.h"
#include "private/qwininputcontext_p.h"
#include "private/qcursor_p.h"
#include "private/qmath_p.h"
#include "private/qapplication_p.h"
#include "private/qbackingstore_p.h"
#include "private/qwindowsurface_raster_p.h"
#include "qdebug.h"
#include <private/qkeymapper_p.h>
#include <private/qlocale_p.h>
#include <private/qsystemlibrary_p.h>
#include "qevent_p.h"
#include "qmutex.h"
#include "qaccessible.h"
#include <oleacc.h>
#include <bldver.h>
#include <windowsx.h>
#include <limits.h>
#include <string.h>
#include <ctype.h>
#include <stdio.h>
#include <math.h>
#include <wintab.h>
#include <pktdef.h>
#include "private/qwidget_p.h"
Classes
class QETWidget
class QGuiEventDispatcherWin32
struct QWinConfigRequest
struct SHRGINFO
struct tagTOUCHINPUT
struct tagTRACKMOUSEEVENT
Macros
#define __export
#define APPCOMMAND_BASS_BOOST 20
#define APPCOMMAND_BASS_DOWN 19
#define APPCOMMAND_BASS_UP 21
#define APPCOMMAND_BROWSER_BACKWARD 1
#define APPCOMMAND_BROWSER_FAVORITES 6
#define APPCOMMAND_BROWSER_FORWARD 2
#define APPCOMMAND_BROWSER_HOME 7
#define APPCOMMAND_BROWSER_REFRESH 3
#define APPCOMMAND_BROWSER_SEARCH 5
#define APPCOMMAND_BROWSER_STOP 4
#define APPCOMMAND_CLOSE 31
#define APPCOMMAND_COPY 36
#define APPCOMMAND_CORRECTION_LIST 45
#define APPCOMMAND_CUT 37
#define APPCOMMAND_DICTATE_OR_COMMAND_CONTROL_TOGGLE 43
#define APPCOMMAND_FIND 28
#define APPCOMMAND_FORWARD_MAIL 40
#define APPCOMMAND_HELP 27
#define APPCOMMAND_LAUNCH_APP1 17
#define APPCOMMAND_LAUNCH_APP2 18
#define APPCOMMAND_LAUNCH_MAIL 15
#define APPCOMMAND_LAUNCH_MEDIA_SELECT 16
#define APPCOMMAND_MEDIA_CHANNEL_DOWN 52
#define APPCOMMAND_MEDIA_CHANNEL_UP 51
#define APPCOMMAND_MEDIA_FAST_FORWARD 49
#define APPCOMMAND_MEDIA_NEXTTRACK 11
#define APPCOMMAND_MEDIA_PAUSE 47
#define APPCOMMAND_MEDIA_PLAY 46
#define APPCOMMAND_MEDIA_PLAY_PAUSE 14
#define APPCOMMAND_MEDIA_PREVIOUSTRACK 12
#define APPCOMMAND_MEDIA_RECORD 48
#define APPCOMMAND_MEDIA_REWIND 50
#define APPCOMMAND_MEDIA_STOP 13
#define APPCOMMAND_MIC_ON_OFF_TOGGLE 44
#define APPCOMMAND_MICROPHONE_VOLUME_DOWN 25
#define APPCOMMAND_MICROPHONE_VOLUME_MUTE 24
#define APPCOMMAND_MICROPHONE_VOLUME_UP 26
#define APPCOMMAND_NEW 29
#define APPCOMMAND_OPEN 30
#define APPCOMMAND_PASTE 38
#define APPCOMMAND_PRINT 33
#define APPCOMMAND_REDO 35
#define APPCOMMAND_REPLY_TO_MAIL 39
#define APPCOMMAND_SAVE 32
#define APPCOMMAND_SEND_MAIL 41
#define APPCOMMAND_SPELL_CHECK 42
#define APPCOMMAND_TREBLE_DOWN 22
#define APPCOMMAND_TREBLE_UP 23
#define APPCOMMAND_UNDO 34
#define APPCOMMAND_VOLUME_DOWN 9
#define APPCOMMAND_VOLUME_MUTE 8
#define APPCOMMAND_VOLUME_UP 10
#define COLOR_MENUBAR 30
#define COLOR_MENUHILIGHT 29
#define CSR_TYPE 20
#define FAPPCOMMAND_KEY 0
#define FAPPCOMMAND_MASK 0xF000
#define FAPPCOMMAND_MOUSE 0x8000
#define FAPPCOMMAND_OEM 0x1000
#define FE_FONTSMOOTHINGCLEARTYPE 0x0002
#define GET_APPCOMMAND_LPARAM(lParam) ((short)(HIWORD(lParam) & ~FAPPCOMMAND_MASK))
#define GET_DEVICE_LPARAM(lParam) ((WORD)(HIWORD(lParam) & FAPPCOMMAND_MASK))
#define GET_FLAGS_LPARAM(lParam) (LOWORD(lParam))
#define GET_KEYSTATE_LPARAM(lParam) GET_FLAGS_LPARAM(lParam)
#define GET_KEYSTATE_WPARAM(wParam) (LOWORD(wParam))
#define GET_MOUSEORKEY_LPARAM GET_DEVICE_LPARAM
#define GET_XBUTTON_WPARAM(wParam) (HIWORD(wParam))
#define GID_PRESSANDTAP 7
#define GID_ROLLOVER GID_PRESSANDTAP
#define GID_TWOFINGERTAP 6
#define GID_ZOOM 3
#define GN_CONTEXTMENU 1000
#define IMR_CONFIRMRECONVERTSTRING 0x0005
#define IMR_RECONVERTSTRING 4
#define MK_XBUTTON1 0x0020
#define MK_XBUTTON2 0x0040
#define PACKETDATA
#define PACKETMODE 0
#define PEEKMESSAGE_IS_BROKEN 1
#define RETURN(x) { inLoop=false;return x; }
#define SHRG_NOANIMATION 0x00000010
#define SHRG_RETURNCMD 0x00000001
#define SPI_GETFONTSMOOTHINGTYPE 0x200A
#define SPI_SETFONTSMOOTHINGTYPE 0x200B
#define SPI_SETSIPINFO 224
#define TOUCHEVENTF_DOWN 0x0002
#define TOUCHEVENTF_INRANGE 0x0008
#define TOUCHEVENTF_MOVE 0x0001
#define TOUCHEVENTF_NOCOALESCE 0x0020
#define TOUCHEVENTF_PALM 0x0080
#define TOUCHEVENTF_PEN 0x0040
#define TOUCHEVENTF_PRIMARY 0x0010
#define TOUCHEVENTF_UP 0x0004
#define TOUCHINPUTMASKF_CONTACTAREA 0x0004
#define TOUCHINPUTMASKF_EXTRAINFO 0x0002
#define TOUCHINPUTMASKF_TIMEFROMSYSTEM 0x0001
#define WM_APPCOMMAND 0x0319
#define WM_GETOBJECT 0x003D
#define WM_MOUSELEAVE 0x02A3
#define WM_THEMECHANGED 0x031A
#define WM_TOUCH 0x0240
#define WM_XBUTTONDBLCLK 0x020D
#define WM_XBUTTONDOWN 0x020B
#define WM_XBUTTONUP 0x020C
#define XBUTTON1 0x0001
#define XBUTTON2 0x0002
Typedefs
typedef DWORD(API * AygRecognizeGesture) (SHRGINFO *)
typedef struct tagTRACKMOUSEEVENT * LPTRACKMOUSEEVENT
typedef struct tagTOUCHINPUT * PTOUCHINPUT
typedef BOOL(WINAPI * PtrSetProcessDPIAware) (VOID)
typedef BOOL(API * PtrWTClose) (HCTX)
typedef BOOL(API * PtrWTEnable) (HCTX, BOOL)
typedef BOOL(API * PtrWTGet) (HCTX, LPLOGCONTEXT)
typedef UINT(API * PtrWTInfo) (UINT, UINT, LPVOID)
typedef HCTX(API * PtrWTOpen) (HWND, LPLOGCONTEXT, BOOL)
typedef BOOL(API * PtrWTOverlap) (HCTX, BOOL)
typedef int(API * PtrWTPacketsGet) (HCTX, int, LPVOID)
typedef int(API * PtrWTQueueSizeGet) (HCTX)
typedef BOOL(API * PtrWTQueueSizeSet) (HCTX, int)
typedef QHash< quint64, QTabletDeviceData > QTabletCursorInfo
typedef struct tagTOUCHINPUT TOUCHINPUT
typedef struct tagTRACKMOUSEEVENT TRACKMOUSEEVENT
typedef QHash< QString, int > WinClassNameHash
Functions
static void alert_widget (QWidget *widget, int duration)
static void initWinTabFunctions ()
uint qGlobalPostedEventsCount ()
void qt_cleanup ()
QRgb qt_colorref2qrgb (COLORREF col)
IAccessible * qt_createWindowsAccessible (QAccessibleInterface *object)
QRegion qt_dirtyRegion (QWidget *)
QWidget * qt_get_tablet_widget ()
Q_GUI_EXPORT const QString qt_getRegisteredWndClass ()
QCursor * qt_grab_cursor ()
void qt_init (QApplicationPrivate *priv, int)
static bool qt_is_translatable_mouse_event (UINT message)
QFont qt_LOGFONTtoQFont (LOGFONT &lf, bool scale)
bool qt_nograb ()
const QString qt_reg_winclass (QWidget *w)
bool qt_sendSpontaneousEvent (QObject *, QEvent *)
static void qt_set_windows_color_resources ()
static void qt_set_windows_font_resources ()
static void qt_set_windows_resources ()
static void qt_set_windows_updateScrollBar (QWidget *widget)
static bool qt_try_modal (QWidget *, MSG *, int &ret)
HRGN qt_tryCreateRegion (QRegion::RegionType type, int left, int top, int right, int bottom)
static BOOL WINAPI qt_updateLayeredWindowIndirect (HWND hwnd, const Q_UPDATELAYEREDWINDOWINFO *info)
Q_GUI_EXPORT HDC qt_win_display_dc ()
void qt_win_eatMouseMove ()
Qt::KeyboardModifiers qt_win_getKeyboardModifiers ()
static void qt_win_read_cleartype_settings ()
void qt_win_set_cursor (QWidget *w, bool force)
void qt_wince_hide_taskbar (HWND hwnd)
bool qt_wince_is_high_dpi ()
bool qt_wince_is_mobile ()
bool qt_wince_is_pocket_pc ()
bool qt_wince_is_smartphone ()
LRESULT QT_WIN_CALLBACK QtWndProc (HWND, UINT, WPARAM, LPARAM)
static void qWinProcessConfigRequests ()
void qWinRequestConfig (WId id, int req, int x, int y, int w, int h)
static void releaseAutoCapture ()
static void resolveAygLibs ()
static void setAutoCapture (HWND)
static void tabletInit (const quint64 uniqueId, const UINT csr_type, HCTX hTab)
static void tabletUpdateCursor (QTabletDeviceData &tdd, const UINT currentCursor)
static int translateButtonState (int s, int type, int button)
static void unregWinClasses ()
Variables
static bool app_do_modal = false
static bool appNoGrab = false
static HWND autoCaptureWnd = 0
static bool aygResolved = false
static QList< QWinConfigRequest * > * configRequests = 0
QTabletDeviceData currentTabletPointer
static HWND curWin = 0
static HDC displayDC = 0
static bool effect_override = false
static HWND imeParentWnd = 0
static bool inLoop = false
static int inputcharset = CP_ACP
static PACKET localPacketBuf [QT_TABLET_NPACKETQSIZE]
static const ushort mouseTbl []
QPointF oldHiResTabletGlobalPosF
static QPointer< QWidget > popupButtonFocus
static AygRecognizeGesture ptrRecognizeGesture = 0
static PtrSetProcessDPIAware ptrSetProcessDPIAware = 0
PtrUpdateLayeredWindow ptrUpdateLayeredWindow = 0
PtrUpdateLayeredWindowIndirect ptrUpdateLayeredWindowIndirect = 0
static PtrWTEnable ptrWTEnable = 0
static PtrWTGet ptrWTGet = 0
static PtrWTInfo ptrWTInfo = 0
static PtrWTOverlap ptrWTOverlap = 0
static PtrWTPacketsGet ptrWTPacketsGet = 0
bool qt_app_has_font
QWidget * qt_button_down = 0
Q_GUI_EXPORT bool qt_cleartype_enabled
QDesktopWidget * qt_desktopWidget
Q_GUI_EXPORT qreal qt_fontsmoothing_gamma
bool qt_is_gui_used
QPointer< QWidget > qt_last_mouse_receiver = 0
QWidgetList * qt_modal_stack
QSessionManager * qt_session_manager_self
HCTX qt_tablet_context
bool qt_tablet_tilt_support
bool qt_tabletChokeMouse
bool qt_use_rtl_extensions = false
Q_GUI_EXPORT bool qt_win_ignoreNextMouseReleaseEvent = false
Q_GUI_EXPORT bool qt_win_owndc_required
static bool replayPopupMouseEvent = false
static bool sm_blockUserInput = false
static bool sm_cancel
static bool sm_smActive = false
Macro Definition Documentation
__export
#define __export
Definition at line 460 of file qapplication_win.cpp.
APPCOMMAND_BASS_BOOST
#define APPCOMMAND_BASS_BOOST 20
Definition at line 352 of file qapplication_win.cpp.
Referenced by QtWndProc().
APPCOMMAND_BASS_DOWN
#define APPCOMMAND_BASS_DOWN 19
Definition at line 351 of file qapplication_win.cpp.
Referenced by QtWndProc().
APPCOMMAND_BASS_UP
#define APPCOMMAND_BASS_UP 21
Definition at line 353 of file qapplication_win.cpp.
Referenced by QtWndProc().
APPCOMMAND_BROWSER_BACKWARD
#define APPCOMMAND_BROWSER_BACKWARD 1
Definition at line 333 of file qapplication_win.cpp.
APPCOMMAND_BROWSER_FAVORITES
#define APPCOMMAND_BROWSER_FAVORITES 6
Definition at line 338 of file qapplication_win.cpp.
APPCOMMAND_BROWSER_FORWARD
#define APPCOMMAND_BROWSER_FORWARD 2
Definition at line 334 of file qapplication_win.cpp.
APPCOMMAND_BROWSER_HOME
#define APPCOMMAND_BROWSER_HOME 7
Definition at line 339 of file qapplication_win.cpp.
APPCOMMAND_BROWSER_REFRESH
#define APPCOMMAND_BROWSER_REFRESH 3
Definition at line 335 of file qapplication_win.cpp.
APPCOMMAND_BROWSER_SEARCH
#define APPCOMMAND_BROWSER_SEARCH 5
Definition at line 337 of file qapplication_win.cpp.
APPCOMMAND_BROWSER_STOP
#define APPCOMMAND_BROWSER_STOP 4
Definition at line 336 of file qapplication_win.cpp.
APPCOMMAND_CLOSE
#define APPCOMMAND_CLOSE 31
Definition at line 367 of file qapplication_win.cpp.
APPCOMMAND_COPY
#define APPCOMMAND_COPY 36
Definition at line 372 of file qapplication_win.cpp.
APPCOMMAND_CORRECTION_LIST
#define APPCOMMAND_CORRECTION_LIST 45
Definition at line 381 of file qapplication_win.cpp.
APPCOMMAND_CUT
#define APPCOMMAND_CUT 37
Definition at line 373 of file qapplication_win.cpp.
APPCOMMAND_DICTATE_OR_COMMAND_CONTROL_TOGGLE
#define APPCOMMAND_DICTATE_OR_COMMAND_CONTROL_TOGGLE 43
Definition at line 379 of file qapplication_win.cpp.
APPCOMMAND_FIND
#define APPCOMMAND_FIND 28
Definition at line 364 of file qapplication_win.cpp.
Referenced by QtWndProc().
APPCOMMAND_FORWARD_MAIL
#define APPCOMMAND_FORWARD_MAIL 40
Definition at line 376 of file qapplication_win.cpp.
APPCOMMAND_HELP
#define APPCOMMAND_HELP 27
Definition at line 363 of file qapplication_win.cpp.
Referenced by QtWndProc().
APPCOMMAND_LAUNCH_APP1
#define APPCOMMAND_LAUNCH_APP1 17
Definition at line 349 of file qapplication_win.cpp.
APPCOMMAND_LAUNCH_APP2
#define APPCOMMAND_LAUNCH_APP2 18
Definition at line 350 of file qapplication_win.cpp.
APPCOMMAND_LAUNCH_MAIL
#define APPCOMMAND_LAUNCH_MAIL 15
Definition at line 347 of file qapplication_win.cpp.
APPCOMMAND_LAUNCH_MEDIA_SELECT
#define APPCOMMAND_LAUNCH_MEDIA_SELECT 16
Definition at line 348 of file qapplication_win.cpp.
APPCOMMAND_MEDIA_CHANNEL_DOWN
#define APPCOMMAND_MEDIA_CHANNEL_DOWN 52
Definition at line 388 of file qapplication_win.cpp.
APPCOMMAND_MEDIA_CHANNEL_UP
#define APPCOMMAND_MEDIA_CHANNEL_UP 51
Definition at line 387 of file qapplication_win.cpp.
APPCOMMAND_MEDIA_FAST_FORWARD
#define APPCOMMAND_MEDIA_FAST_FORWARD 49
Definition at line 385 of file qapplication_win.cpp.
APPCOMMAND_MEDIA_NEXTTRACK
#define APPCOMMAND_MEDIA_NEXTTRACK 11
Definition at line 343 of file qapplication_win.cpp.
APPCOMMAND_MEDIA_PAUSE
#define APPCOMMAND_MEDIA_PAUSE 47
Definition at line 383 of file qapplication_win.cpp.
APPCOMMAND_MEDIA_PLAY
#define APPCOMMAND_MEDIA_PLAY 46
Definition at line 382 of file qapplication_win.cpp.
APPCOMMAND_MEDIA_PLAY_PAUSE
#define APPCOMMAND_MEDIA_PLAY_PAUSE 14
Definition at line 346 of file qapplication_win.cpp.
APPCOMMAND_MEDIA_PREVIOUSTRACK
#define APPCOMMAND_MEDIA_PREVIOUSTRACK 12
Definition at line 344 of file qapplication_win.cpp.
APPCOMMAND_MEDIA_RECORD
#define APPCOMMAND_MEDIA_RECORD 48
Definition at line 384 of file qapplication_win.cpp.
APPCOMMAND_MEDIA_REWIND
#define APPCOMMAND_MEDIA_REWIND 50
Definition at line 386 of file qapplication_win.cpp.
APPCOMMAND_MEDIA_STOP
#define APPCOMMAND_MEDIA_STOP 13
Definition at line 345 of file qapplication_win.cpp.
APPCOMMAND_MIC_ON_OFF_TOGGLE
#define APPCOMMAND_MIC_ON_OFF_TOGGLE 44
Definition at line 380 of file qapplication_win.cpp.
APPCOMMAND_MICROPHONE_VOLUME_DOWN
#define APPCOMMAND_MICROPHONE_VOLUME_DOWN 25
Definition at line 361 of file qapplication_win.cpp.
APPCOMMAND_MICROPHONE_VOLUME_MUTE
#define APPCOMMAND_MICROPHONE_VOLUME_MUTE 24
Definition at line 360 of file qapplication_win.cpp.
APPCOMMAND_MICROPHONE_VOLUME_UP
#define APPCOMMAND_MICROPHONE_VOLUME_UP 26
Definition at line 362 of file qapplication_win.cpp.
APPCOMMAND_NEW
#define APPCOMMAND_NEW 29
Definition at line 365 of file qapplication_win.cpp.
APPCOMMAND_OPEN
#define APPCOMMAND_OPEN 30
Definition at line 366 of file qapplication_win.cpp.
APPCOMMAND_PASTE
#define APPCOMMAND_PASTE 38
Definition at line 374 of file qapplication_win.cpp.
APPCOMMAND_PRINT
#define APPCOMMAND_PRINT 33
Definition at line 369 of file qapplication_win.cpp.
APPCOMMAND_REDO
#define APPCOMMAND_REDO 35
Definition at line 371 of file qapplication_win.cpp.
APPCOMMAND_REPLY_TO_MAIL
#define APPCOMMAND_REPLY_TO_MAIL 39
Definition at line 375 of file qapplication_win.cpp.
APPCOMMAND_SAVE
#define APPCOMMAND_SAVE 32
Definition at line 368 of file qapplication_win.cpp.
APPCOMMAND_SEND_MAIL
#define APPCOMMAND_SEND_MAIL 41
Definition at line 377 of file qapplication_win.cpp.
APPCOMMAND_SPELL_CHECK
#define APPCOMMAND_SPELL_CHECK 42
Definition at line 378 of file qapplication_win.cpp.
APPCOMMAND_TREBLE_DOWN
#define APPCOMMAND_TREBLE_DOWN 22
Definition at line 354 of file qapplication_win.cpp.
Referenced by QtWndProc().
APPCOMMAND_TREBLE_UP
#define APPCOMMAND_TREBLE_UP 23
Definition at line 355 of file qapplication_win.cpp.
Referenced by QtWndProc().
APPCOMMAND_UNDO
#define APPCOMMAND_UNDO 34
Definition at line 370 of file qapplication_win.cpp.
APPCOMMAND_VOLUME_DOWN
#define APPCOMMAND_VOLUME_DOWN 9
Definition at line 341 of file qapplication_win.cpp.
APPCOMMAND_VOLUME_MUTE
#define APPCOMMAND_VOLUME_MUTE 8
Definition at line 340 of file qapplication_win.cpp.
APPCOMMAND_VOLUME_UP
#define APPCOMMAND_VOLUME_UP 10
Definition at line 342 of file qapplication_win.cpp.
COLOR_MENUBAR
#define COLOR_MENUBAR 30
Definition at line 297 of file qapplication_win.cpp.
COLOR_MENUHILIGHT
#define COLOR_MENUHILIGHT 29
Definition at line 296 of file qapplication_win.cpp.
CSR_TYPE
#define CSR_TYPE 20
Definition at line 179 of file qapplication_win.cpp.
Referenced by QtWndProc().
FAPPCOMMAND_KEY
#define FAPPCOMMAND_KEY 0
Definition at line 324 of file qapplication_win.cpp.
Referenced by QtWndProc().
FAPPCOMMAND_MASK
#define FAPPCOMMAND_MASK 0xF000
Definition at line 326 of file qapplication_win.cpp.
FAPPCOMMAND_MOUSE
#define FAPPCOMMAND_MOUSE 0x8000
Definition at line 323 of file qapplication_win.cpp.
FAPPCOMMAND_OEM
#define FAPPCOMMAND_OEM 0x1000
Definition at line 325 of file qapplication_win.cpp.
FE_FONTSMOOTHINGCLEARTYPE
#define FE_FONTSMOOTHINGCLEARTYPE 0x0002
Definition at line 237 of file qapplication_win.cpp.
Referenced by qt_win_read_cleartype_settings().
GET_APPCOMMAND_LPARAM
#define GET_APPCOMMAND_LPARAM (lParam) ((short)(HIWORD(lParam) & ~FAPPCOMMAND_MASK))
Definition at line 327 of file qapplication_win.cpp.
Referenced by QtWndProc().
GET_DEVICE_LPARAM
#define GET_DEVICE_LPARAM (lParam) ((WORD)(HIWORD(lParam) & FAPPCOMMAND_MASK))
Definition at line 328 of file qapplication_win.cpp.
Referenced by QtWndProc().
GET_FLAGS_LPARAM
#define GET_FLAGS_LPARAM (lParam) (LOWORD(lParam))
Definition at line 330 of file qapplication_win.cpp.
GET_KEYSTATE_LPARAM
#define GET_KEYSTATE_LPARAM (lParam) GET_FLAGS_LPARAM(lParam)
Definition at line 331 of file qapplication_win.cpp.
Referenced by QtWndProc().
GET_KEYSTATE_WPARAM
#define GET_KEYSTATE_WPARAM (wParam) (LOWORD(wParam))
Definition at line 307 of file qapplication_win.cpp.
Referenced by QETWidget::translateWheelEvent().
GET_MOUSEORKEY_LPARAM
#define GET_MOUSEORKEY_LPARAM GET_DEVICE_LPARAM
Definition at line 329 of file qapplication_win.cpp.
GET_XBUTTON_WPARAM
#define GET_XBUTTON_WPARAM (wParam) (HIWORD(wParam))
Definition at line 308 of file qapplication_win.cpp.
Referenced by QETWidget::translateMouseEvent().
GID_PRESSANDTAP
#define GID_PRESSANDTAP 7
Definition at line 127 of file qapplication_win.cpp.
GID_ROLLOVER
#define GID_ROLLOVER GID_PRESSANDTAP
Definition at line 128 of file qapplication_win.cpp.
Referenced by QETWidget::translateGestureEvent().
GID_TWOFINGERTAP
#define GID_TWOFINGERTAP 6
Definition at line 126 of file qapplication_win.cpp.
Referenced by QETWidget::translateGestureEvent().
GID_ZOOM
#define GID_ZOOM 3
Definition at line 125 of file qapplication_win.cpp.
Referenced by QETWidget::translateGestureEvent().
GN_CONTEXTMENU
#define GN_CONTEXTMENU 1000
Definition at line 205 of file qapplication_win.cpp.
Referenced by QtWndProc().
IMR_CONFIRMRECONVERTSTRING
#define IMR_CONFIRMRECONVERTSTRING 0x0005
Definition at line 193 of file qapplication_win.cpp.
Referenced by QtWndProc().
IMR_RECONVERTSTRING
#define IMR_RECONVERTSTRING 4
Definition at line 189 of file qapplication_win.cpp.
Referenced by QtWndProc().
MK_XBUTTON1
#define MK_XBUTTON1 0x0020
Definition at line 313 of file qapplication_win.cpp.
Referenced by decodeMSG(), and translateButtonState().
MK_XBUTTON2
#define MK_XBUTTON2 0x0040
Definition at line 314 of file qapplication_win.cpp.
Referenced by decodeMSG(), and translateButtonState().
PACKETDATA
#define PACKETDATA
Value:
(PK_X | PK_Y | PK_BUTTONS | PK_NORMAL_PRESSURE | PK_TANGENT_PRESSURE \
                     | PK_ORIENTATION | PK_CURSOR | PK_Z)
Definition at line 173 of file qapplication_win.cpp.
PACKETMODE
#define PACKETMODE 0
Definition at line 175 of file qapplication_win.cpp.
PEEKMESSAGE_IS_BROKEN
#define PEEKMESSAGE_IS_BROKEN 1
RETURN
#define RETURN (x) { inLoop=false;return x; }
Definition at line 1460 of file qapplication_win.cpp.
Referenced by QtWndProc().
SHRG_NOANIMATION
#define SHRG_NOANIMATION 0x00000010
Definition at line 207 of file qapplication_win.cpp.
Referenced by QtWndProc().
SHRG_RETURNCMD
#define SHRG_RETURNCMD 0x00000001
Definition at line 206 of file qapplication_win.cpp.
Referenced by QtWndProc().
SPI_GETFONTSMOOTHINGTYPE
#define SPI_GETFONTSMOOTHINGTYPE 0x200A
Definition at line 234 of file qapplication_win.cpp.
Referenced by qt_win_read_cleartype_settings().
SPI_SETFONTSMOOTHINGTYPE
#define SPI_SETFONTSMOOTHINGTYPE 0x200B
Definition at line 231 of file qapplication_win.cpp.
Referenced by QtWndProc().
SPI_SETSIPINFO
#define SPI_SETSIPINFO 224
Definition at line 211 of file qapplication_win.cpp.
Referenced by QtWndProc().
TOUCHEVENTF_DOWN
#define TOUCHEVENTF_DOWN 0x0002
Definition at line 138 of file qapplication_win.cpp.
Referenced by QApplicationPrivate::translateTouchEvent().
TOUCHEVENTF_INRANGE
#define TOUCHEVENTF_INRANGE 0x0008
Definition at line 140 of file qapplication_win.cpp.
TOUCHEVENTF_MOVE
#define TOUCHEVENTF_MOVE 0x0001
Definition at line 137 of file qapplication_win.cpp.
TOUCHEVENTF_NOCOALESCE
#define TOUCHEVENTF_NOCOALESCE 0x0020
Definition at line 142 of file qapplication_win.cpp.
TOUCHEVENTF_PALM
#define TOUCHEVENTF_PALM 0x0080
Definition at line 144 of file qapplication_win.cpp.
TOUCHEVENTF_PEN
#define TOUCHEVENTF_PEN 0x0040
Definition at line 143 of file qapplication_win.cpp.
TOUCHEVENTF_PRIMARY
#define TOUCHEVENTF_PRIMARY 0x0010
Definition at line 141 of file qapplication_win.cpp.
Referenced by QApplicationPrivate::translateTouchEvent().
TOUCHEVENTF_UP
#define TOUCHEVENTF_UP 0x0004
Definition at line 139 of file qapplication_win.cpp.
Referenced by QApplicationPrivate::translateTouchEvent().
TOUCHINPUTMASKF_CONTACTAREA
#define TOUCHINPUTMASKF_CONTACTAREA 0x0004
Definition at line 148 of file qapplication_win.cpp.
Referenced by QApplicationPrivate::translateTouchEvent().
TOUCHINPUTMASKF_EXTRAINFO
#define TOUCHINPUTMASKF_EXTRAINFO 0x0002
Definition at line 147 of file qapplication_win.cpp.
TOUCHINPUTMASKF_TIMEFROMSYSTEM
#define TOUCHINPUTMASKF_TIMEFROMSYSTEM 0x0001
Definition at line 146 of file qapplication_win.cpp.
WM_APPCOMMAND
#define WM_APPCOMMAND 0x0319
Definition at line 319 of file qapplication_win.cpp.
Referenced by QtWndProc().
WM_GETOBJECT
#define WM_GETOBJECT 0x003D
Definition at line 110 of file qapplication_win.cpp.
Referenced by QtWndProc().
WM_MOUSELEAVE
#define WM_MOUSELEAVE 0x02A3
Definition at line 402 of file qapplication_win.cpp.
Referenced by decodeMSG(), qt_try_modal(), and QtWndProc().
WM_THEMECHANGED
#define WM_THEMECHANGED 0x031A
Definition at line 293 of file qapplication_win.cpp.
Referenced by QtWndProc().
WM_TOUCH
#define WM_TOUCH 0x0240
Definition at line 133 of file qapplication_win.cpp.
Referenced by QtWndProc().
WM_XBUTTONDBLCLK
#define WM_XBUTTONDBLCLK 0x020D
Definition at line 304 of file qapplication_win.cpp.
Referenced by qt_is_translatable_mouse_event(), and QtWndProc().
WM_XBUTTONDOWN
#define WM_XBUTTONDOWN 0x020B
Definition at line 302 of file qapplication_win.cpp.
Referenced by qt_is_translatable_mouse_event(), and QtWndProc().
WM_XBUTTONUP
#define WM_XBUTTONUP 0x020C
Definition at line 303 of file qapplication_win.cpp.
Referenced by QtWndProc().
XBUTTON1
#define XBUTTON1 0x0001
Definition at line 309 of file qapplication_win.cpp.
Referenced by QETWidget::translateMouseEvent().
XBUTTON2
#define XBUTTON2 0x0002
Definition at line 310 of file qapplication_win.cpp.
Referenced by QETWidget::translateMouseEvent().
Typedef Documentation
AygRecognizeGesture
typedef DWORD(API * AygRecognizeGesture) (SHRGINFO *)
Definition at line 215 of file qapplication_win.cpp.
LPTRACKMOUSEEVENT
typedef struct tagTRACKMOUSEEVENT * LPTRACKMOUSEEVENT
PTOUCHINPUT
typedef struct tagTOUCHINPUT * PTOUCHINPUT
PtrSetProcessDPIAware
typedef BOOL(WINAPI * PtrSetProcessDPIAware) (VOID)
Definition at line 755 of file qapplication_win.cpp.
PtrWTClose
typedef BOOL(API * PtrWTClose) (HCTX)
Definition at line 245 of file qapplication_win.cpp.
PtrWTEnable
typedef BOOL(API * PtrWTEnable) (HCTX, BOOL)
Definition at line 247 of file qapplication_win.cpp.
PtrWTGet
typedef BOOL(API * PtrWTGet) (HCTX, LPLOGCONTEXT)
Definition at line 250 of file qapplication_win.cpp.
PtrWTInfo
typedef UINT(API * PtrWTInfo) (UINT, UINT, LPVOID)
Definition at line 246 of file qapplication_win.cpp.
PtrWTOpen
typedef HCTX(API * PtrWTOpen) (HWND, LPLOGCONTEXT, BOOL)
Definition at line 244 of file qapplication_win.cpp.
PtrWTOverlap
typedef BOOL(API * PtrWTOverlap) (HCTX, BOOL)
Definition at line 248 of file qapplication_win.cpp.
PtrWTPacketsGet
typedef int(API * PtrWTPacketsGet) (HCTX, int, LPVOID)
Definition at line 249 of file qapplication_win.cpp.
PtrWTQueueSizeGet
typedef int(API * PtrWTQueueSizeGet) (HCTX)
Definition at line 251 of file qapplication_win.cpp.
PtrWTQueueSizeSet
typedef BOOL(API * PtrWTQueueSizeSet) (HCTX, int)
Definition at line 252 of file qapplication_win.cpp.
QTabletCursorInfo
typedef QHash<quint64, QTabletDeviceData> QTabletCursorInfo
Definition at line 284 of file qapplication_win.cpp.
TOUCHINPUT
typedef struct tagTOUCHINPUT TOUCHINPUT
TRACKMOUSEEVENT
typedef struct tagTRACKMOUSEEVENT TRACKMOUSEEVENT
WinClassNameHash
typedef QHash<QString, int> WinClassNameHash
Definition at line 959 of file qapplication_win.cpp.
Function Documentation
alert_widget()
static void alert_widget (QWidget * widget, int duration) static
Definition at line 1348 of file qapplication_win.cpp.
Referenced by QtWndProc().
 {
 #ifdef Q_OS_WINCE
     Q_UNUSED(widget);
     Q_UNUSED(duration);
 #else
     bool stopFlash = duration < 0;
     if (widget && (!widget->isActiveWindow() || stopFlash)) {
         DWORD timeOut = GetCaretBlinkTime();
         if (timeOut <= 0)
             timeOut = 250;
         UINT flashCount;
         if (duration == 0)
             flashCount = 10;
         else
             flashCount = duration/timeOut;
         FLASHWINFO info;
         info.cbSize = sizeof(info);
         info.hwnd = widget->window()->winId();
         info.dwFlags = stopFlash ? FLASHW_STOP : FLASHW_TRAY;
         info.dwTimeout = stopFlash ? 0 : timeOut;
         info.uCount = stopFlash ? 0 : flashCount;
         FlashWindowEx(&info);
     }
 #endif
 }
initWinTabFunctions()
static void initWinTabFunctions () static
Definition at line 3762 of file qapplication_win.cpp.
Referenced by qt_init().
 {
 #if defined(Q_OS_WINCE)
     return;
 #else
     if (!qt_is_gui_used)
         return;
     QSystemLibrary library(QLatin1String("wintab32"));
     ptrWTInfo = (PtrWTInfo)library.resolve("WTInfoW");
     ptrWTGet = (PtrWTGet)library.resolve("WTGetW");
     ptrWTEnable = (PtrWTEnable)library.resolve("WTEnable");
     ptrWTOverlap = (PtrWTEnable)library.resolve("WTOverlap");
     ptrWTPacketsGet = (PtrWTPacketsGet)library.resolve("WTPacketsGet");
 #endif // Q_OS_WINCE
 }
qGlobalPostedEventsCount()
uint qGlobalPostedEventsCount ()
Definition at line 348 of file qcoreapplication.cpp.
Referenced by alert_widget().
 {
     QThreadData *currentThreadData = QThreadData::current();
     return currentThreadData->postEventList.size() - currentThreadData->postEventList.startOffset;
 }
qt_cleanup()
void qt_cleanup ()
Definition at line 910 of file qapplication_win.cpp.
 {
     unregWinClasses();
     QPixmapCache::clear();
 #ifndef QT_NO_CURSOR
     if (QApplication::type() != QApplication::Tty)
         QCursorData::cleanup();
 #endif
     QFont::cleanup();
     QColormap::cleanup();
     if (displayDC) {
         ReleaseDC(0, displayDC);
         displayDC = 0;
     }
 #ifndef QT_NO_IM
     delete QApplicationPrivate::inputContext;
     QApplicationPrivate::inputContext = 0;
 #endif
 #ifndef Q_WS_WINCE
   // Deinitialize OLE/COM
     OleUninitialize();
 #endif
 }
qt_colorref2qrgb()
QRgb qt_colorref2qrgb (COLORREF col)
Definition at line 412 of file qapplication_win.cpp.
Referenced by qt_set_windows_color_resources().
 {
     return qRgb(GetRValue(col),GetGValue(col),GetBValue(col));
 }
qt_createWindowsAccessible()
IAccessible* qt_createWindowsAccessible (QAccessibleInterface * object)
Definition at line 713 of file qaccessible_win.cpp.
Referenced by QtWndProc().
 {
     QWindowsAccessible *acc = new QWindowsAccessible(access);
     IAccessible *iface;
     acc->QueryInterface(IID_IAccessible, (void**)&iface);
     return iface;
 }
qt_dirtyRegion()
QRegion qt_dirtyRegion (QWidget *)
Definition at line 1111 of file qwidget.cpp.
Referenced by QWidgetBackingStore::hasStaticContents(), and QETWidget::translatePaintEvent().
 {
     if (!widget)
         return QRegion();
     QWidgetBackingStore *bs = qt_widget_private(widget)->maybeBackingStore();
     if (!bs)
         return QRegion();
     return bs->dirtyRegion(widget);
 }
qt_get_tablet_widget()
QWidget* qt_get_tablet_widget ()
Definition at line 137 of file qwidget_win.cpp.
Referenced by QtWndProc().
 {
     return qt_tablet_widget;
 }
qt_getRegisteredWndClass()
Q_GUI_EXPORT const QString qt_getRegisteredWndClass ()
Definition at line 1118 of file qapplication_win.cpp.
Referenced by pfiToQGLFormat().
 {
     return qt_reg_winclass(0);
 }
qt_grab_cursor()
QCursor* qt_grab_cursor ()
Definition at line 858 of file qwidget_win.cpp.
Referenced by qt_try_modal(), and QETWidget::translateMouseEvent().
 {
     return mouseGrbCur;
 }
qt_init()
void qt_init (QApplicationPrivate * priv, int)
Definition at line 765 of file qapplication_win.cpp.
 {
     int argc = priv->argc;
     char **argv = priv->argv;
     int i, j;
   // Get command line params
     j = argc ? 1 : 0;
     for (i=1; i<argc; i++) {
         if (argv[i] && *argv[i] != '-') {
             argv[j++] = argv[i];
             continue;
         }
 #if defined(QT_DEBUG)
         if (qstrcmp(argv[i], "-nograb") == 0)
             appNoGrab = !appNoGrab;
         else
 #endif // QT_DEBUG
             argv[j++] = argv[i];
     }
     if(j < priv->argc) {
         priv->argv[j] = 0;
         priv->argc = j;
     }
 #ifndef Q_WS_WINCE
     // No message boxes but important ones
     SetErrorMode(SetErrorMode(0) | SEM_FAILCRITICALERRORS|SEM_NOOPENFILEERRORBOX);
 #endif
 #ifndef Q_WS_WINCE
     // Initialize OLE/COM
     //         S_OK means success and S_FALSE means that it has already
     //         been initialized
     HRESULT r;
     r = OleInitialize(0);
     if (r != S_OK && r != S_FALSE) {
         qWarning("Qt: Could not initialize OLE (error %x)", (unsigned int)r);
     }
 #endif
     // Misc. initialization
 #if defined(QT_DEBUG) && !defined(Q_WS_WINCE)
     GdiSetBatchLimit(1);
 #endif
     // initialize key mapper
     QKeyMapper::changeKeyboard();
     QColormap::initialize();
     QFont::initialize();
 #ifndef QT_NO_CURSOR
     if (QApplication::type() != QApplication::Tty)
         QCursorData::initialize();
 #endif
     qApp->setObjectName(priv->appName());
     // default font
 #ifndef Q_WS_WINCE
     HGDIOBJ stockFont = GetStockObject(DEFAULT_GUI_FONT);
 #else
     HGDIOBJ stockFont = GetStockObject(SYSTEM_FONT);
 #endif
     LOGFONT lf;
     GetObject(stockFont, sizeof(lf), &lf);
     QFont systemFont = qt_LOGFONTtoQFont(lf, true);
 #ifndef Q_WS_WINCE
     if (systemFont.family() == QLatin1String("MS Shell Dlg")) {
         systemFont.setFamily(QLatin1String("MS Shell Dlg 2"));
     }
 #endif
     QApplicationPrivate::setSystemFont(systemFont);
     // QFont::locale_init();  ### Uncomment when it does something on Windows
     if (QApplication::desktopSettingsAware())
         qt_set_windows_resources();
 #ifndef QT_NO_TABLETEVENT
     initWinTabFunctions();
 #endif // QT_NO_TABLETEVENT
 #ifndef QT_NO_IM
     QApplicationPrivate::inputContext = new QWinInputContext(0);
 #endif
     // Read the initial cleartype settings...
     qt_win_read_cleartype_settings();
     qt_win_owndc_required = false;
     extern void qt_win_initialize_directdraw();
     qt_win_initialize_directdraw();
 #ifndef Q_OS_WINCE
     QSystemLibrary user32(QLatin1String("user32"));
     ptrUpdateLayeredWindowIndirect = (PtrUpdateLayeredWindowIndirect)user32.resolve("UpdateLayeredWindowIndirect");
     ptrUpdateLayeredWindow = (PtrUpdateLayeredWindow)user32.resolve("UpdateLayeredWindow");
     if (ptrUpdateLayeredWindow && !ptrUpdateLayeredWindowIndirect)
         ptrUpdateLayeredWindowIndirect = qt_updateLayeredWindowIndirect;
     // Notify Vista and Windows 7 that we support highter DPI settings
     ptrSetProcessDPIAware = (PtrSetProcessDPIAware)user32.resolve("SetProcessDPIAware");
     if (ptrSetProcessDPIAware)
         ptrSetProcessDPIAware();
 #endif
 #ifndef QT_NO_GESTURES
     priv->GetGestureInfo = 0;
     priv->GetGestureExtraArgs = 0;
     priv->CloseGestureInfoHandle = 0;
     priv->SetGestureConfig = 0;
     priv->GetGestureConfig = 0;
     priv->BeginPanningFeedback = 0;
     priv->UpdatePanningFeedback = 0;
     priv->EndPanningFeedback = 0;
 #if defined(Q_WS_WINCE_WM) && defined(QT_WINCE_GESTURES)
     priv->GetGestureInfo = (PtrGetGestureInfo) &TKGetGestureInfo;
     priv->GetGestureExtraArgs = (PtrGetGestureExtraArgs) &TKGetGestureExtraArguments;
 #elif !defined(Q_WS_WINCE)
   #if !defined(QT_NO_NATIVE_GESTURES)
     priv->GetGestureInfo = (PtrGetGestureInfo)user32.resolve("GetGestureInfo");
     priv->GetGestureExtraArgs = (PtrGetGestureExtraArgs)user32.resolve("GetGestureExtraArgs");
     priv->CloseGestureInfoHandle = (PtrCloseGestureInfoHandle)user32.resolve("CloseGestureInfoHandle");
     priv->SetGestureConfig = (PtrSetGestureConfig)user32.resolve("SetGestureConfig");
     priv->GetGestureConfig = (PtrGetGestureConfig)user32.resolve("GetGestureConfig");
   #endif // QT_NO_NATIVE_GESTURES
     QSystemLibrary libTheme(QLatin1String("uxtheme"));
     priv->BeginPanningFeedback = (PtrBeginPanningFeedback)libTheme.resolve("BeginPanningFeedback");
     priv->UpdatePanningFeedback = (PtrUpdatePanningFeedback)libTheme.resolve("UpdatePanningFeedback");
     priv->EndPanningFeedback = (PtrEndPanningFeedback)libTheme.resolve("EndPanningFeedback");
 #endif
 #endif // QT_NO_GESTURES
 }
qt_is_translatable_mouse_event()
static bool qt_is_translatable_mouse_event (UINT message) static
Definition at line 1462 of file qapplication_win.cpp.
Referenced by QtWndProc().
 {
     return (((message >= WM_MOUSEFIRST && message <= WM_MOUSELAST) ||
                 (message >= WM_XBUTTONDOWN && message <= WM_XBUTTONDBLCLK))
             && message != WM_MOUSEWHEEL
             && message != WM_MOUSEHWHEEL)
 #ifndef Q_WS_WINCE
             || (message >= WM_NCMOUSEMOVE && message <= WM_NCMBUTTONDBLCLK)
 #endif
             ;
 }
qt_LOGFONTtoQFont()
QFont qt_LOGFONTtoQFont (LOGFONT & lf, bool scale)
Definition at line 64 of file qfont_win.cpp.
Referenced by QETWidget::forceUpdate(), qt_init(), and qt_set_windows_font_resources().
 {
     QString family = QString::fromWCharArray(lf.lfFaceName);
     QFont qf(family);
     qf.setItalic(lf.lfItalic);
     if (lf.lfWeight != FW_DONTCARE)
         qf.setWeight(weightFromInteger(lf.lfWeight));
     int lfh = qAbs(lf.lfHeight);
     qf.setPointSizeF(lfh * 72.0 / GetDeviceCaps(shared_dc(),LOGPIXELSY));
     qf.setUnderline(false);
     qf.setOverline(false);
     qf.setStrikeOut(false);
     return qf;
 }
qt_nograb()
bool qt_nograb ()
Definition at line 950 of file qapplication_win.cpp.
Referenced by qt_try_modal().
 {
 #if defined(QT_DEBUG)
     return appNoGrab;
 #else
     return false;
 #endif
 }
qt_reg_winclass()
const QString qt_reg_winclass (QWidget * w)
Definition at line 969 of file qapplication_win.cpp.
Referenced by qt_getRegisteredWndClass(), qt_tablet_cleanup(), and qt_tablet_cleanup_wce().
 {
     Qt::WindowFlags flags = w ? w->windowFlags() : (Qt::WindowFlags)0;
     Qt::WindowFlags type = flags & Qt::WindowType_Mask;
     uint style;
     bool icon;
     QString cname;
     if (w && qt_widget_private(w)->isGLWidget) {
         cname = QLatin1String("QGLWidget");
         style = CS_DBLCLKS;
 #ifndef Q_WS_WINCE
         style |= CS_OWNDC;
 #endif
         icon  = true;
     } else if (w && (flags & Qt::MSWindowsOwnDC)) {
         cname = QLatin1String("QWidgetOwnDC");
         style = CS_DBLCLKS;
 #ifndef Q_WS_WINCE
         style |= CS_OWNDC;
 #endif
         icon  = true;
     } else if (w && (type == Qt::Tool || type == Qt::ToolTip)) {
         style = CS_DBLCLKS;
         if (type == Qt::ToolTip || w->inherits("QTipLabel") || w->inherits("QAlphaWidget")) {
             if ((QSysInfo::WindowsVersion >= QSysInfo::WV_XP
                 && (QSysInfo::WindowsVersion & QSysInfo::WV_NT_based))) {
                 style |= CS_DROPSHADOW;
             }
             cname = QLatin1String("QToolTip");
         } else {
             cname = QLatin1String("QTool");
         }
 #ifndef Q_WS_WINCE
         style |= CS_SAVEBITS;
 #endif
         icon = false;
     } else if (w && (type == Qt::Popup)) {
         cname = QLatin1String("QPopup");
         style = CS_DBLCLKS;
 #ifndef Q_WS_WINCE
         style |= CS_SAVEBITS;
 #endif
         if ((QSysInfo::WindowsVersion >= QSysInfo::WV_XP
             && (QSysInfo::WindowsVersion & QSysInfo::WV_NT_based)))
             style |= CS_DROPSHADOW;
         icon = false;
     } else {
         cname = QLatin1String("QWidget");
         style = CS_DBLCLKS;
         icon  = true;
     }
 #ifndef Q_WS_WINCE
     // force CS_OWNDC when the GL graphics system is
     // used as the default renderer
     if (qt_win_owndc_required)
         style |= CS_OWNDC;
 #endif
 #ifdef Q_OS_WINCE
     // We need to register the classes with the
     // unique ID on WinCE to make sure we can
     // move the windows to the front when starting
     // a second instance.
     wchar_t uniqueAppID[MAX_PATH];
     GetModuleFileName(0, uniqueAppID, MAX_PATH);
     cname = QString::number(RegisterWindowMessage(
               (const wchar_t *) QString::fromWCharArray(uniqueAppID).toLower().replace(QLatin1Char('\\'),
               QLatin1Char('_')).utf16()));
 #endif
     // since multiple Qt versions can be used in one process
     // each one has to have window class names with a unique name
     // The first instance gets the unmodified name; if the class
     // has already been registered by another instance of Qt then
     // add an instance-specific ID, the address of the window proc.
     static int classExists = -1;
     if (classExists == -1) {
         WNDCLASS wcinfo;
         classExists = GetClassInfo((HINSTANCE)qWinAppInst(), (wchar_t*)cname.utf16(), &wcinfo);
         classExists = classExists && wcinfo.lpfnWndProc != QtWndProc;
     }
     if (classExists)
         cname += QString::number((quintptr)QtWndProc);
     if (winclassNames()->contains(cname))        // already registered in our list
         return cname;
 #ifndef Q_WS_WINCE
     WNDCLASSEX wc;
     wc.cbSize       = sizeof(WNDCLASSEX);
 #else
     WNDCLASS wc;
 #endif
     wc.style        = style;
     wc.lpfnWndProc  = (WNDPROC)QtWndProc;
     wc.cbClsExtra   = 0;
     wc.cbWndExtra   = 0;
     wc.hInstance    = qWinAppInst();
     if (icon) {
         wc.hIcon = (HICON)LoadImage(qWinAppInst(), L"IDI_ICON1", IMAGE_ICON, 0, 0, LR_DEFAULTSIZE);
 #ifndef Q_WS_WINCE
         if (wc.hIcon) {
             int sw = GetSystemMetrics(SM_CXSMICON);
             int sh = GetSystemMetrics(SM_CYSMICON);
             wc.hIconSm = (HICON)LoadImage(qWinAppInst(), L"IDI_ICON1", IMAGE_ICON, sw, sh, 0);
         } else {
             wc.hIcon = (HICON)LoadImage(0, IDI_APPLICATION, IMAGE_ICON, 0, 0, LR_DEFAULTSIZE | LR_SHARED);
             wc.hIconSm = 0;
         }
 #endif
     } else {
         wc.hIcon    = 0;
 #ifndef Q_WS_WINCE
         wc.hIconSm  = 0;
 #endif
     }
     wc.hCursor      = 0;
 #ifndef Q_WS_WINCE
     HBRUSH brush = 0;
     if (w && !qt_widget_private(w)->isGLWidget)
         brush = (HBRUSH)GetSysColorBrush(COLOR_WINDOW);
     wc.hbrBackground = brush;
 #else
     wc.hbrBackground = 0;
 #endif
     wc.lpszMenuName  = 0;
     wc.lpszClassName = (wchar_t*)cname.utf16();
 #ifndef Q_WS_WINCE
     ATOM atom = RegisterClassEx(&wc);
 #else
     ATOM atom = RegisterClass(&wc);
 #endif
 #ifndef QT_NO_DEBUG
     if (!atom)
         qErrnoWarning("QApplication::regClass: Registering window class failed.");
 #else
     Q_UNUSED(atom);
 #endif
     winclassNames()->insert(cname, 1);
     return cname;
 }
qt_sendSpontaneousEvent()
bool qt_sendSpontaneousEvent (QObject * , QEvent *)
Definition at line 5779 of file qapplication.cpp.
Referenced by QtWndProc(), and QETWidget::translateGestureEvent().
 {
     return QCoreApplication::sendSpontaneousEvent(receiver, event);
 }
qt_set_windows_color_resources()
static void qt_set_windows_color_resources () static
Definition at line 504 of file qapplication_win.cpp.
Referenced by QtWndProc().
 {
     // Do the color settings
     QPalette pal;
     pal.setColor(QPalette::WindowText,
                  QColor(qt_colorref2qrgb(GetSysColor(COLOR_WINDOWTEXT))));
     pal.setColor(QPalette::Button,
                  QColor(qt_colorref2qrgb(GetSysColor(COLOR_BTNFACE))));
     pal.setColor(QPalette::Light,
                  QColor(qt_colorref2qrgb(GetSysColor(COLOR_BTNHIGHLIGHT))));
     pal.setColor(QPalette::Dark,
                  QColor(qt_colorref2qrgb(GetSysColor(COLOR_BTNSHADOW))));
     pal.setColor(QPalette::Mid, pal.button().color().darker(150));
     pal.setColor(QPalette::Text,
                  QColor(qt_colorref2qrgb(GetSysColor(COLOR_WINDOWTEXT))));
     pal.setColor(QPalette::BrightText,
                  QColor(qt_colorref2qrgb(GetSysColor(COLOR_BTNHIGHLIGHT))));
     pal.setColor(QPalette::Base,
                  QColor(qt_colorref2qrgb(GetSysColor(COLOR_WINDOW))));
     pal.setColor(QPalette::Window,
                  QColor(qt_colorref2qrgb(GetSysColor(COLOR_BTNFACE))));
     pal.setColor(QPalette::ButtonText,
                  QColor(qt_colorref2qrgb(GetSysColor(COLOR_BTNTEXT))));
     pal.setColor(QPalette::Midlight,
                  QColor(qt_colorref2qrgb(GetSysColor(COLOR_3DLIGHT))));
     pal.setColor(QPalette::Shadow,
                  QColor(qt_colorref2qrgb(GetSysColor(COLOR_3DDKSHADOW))));
     pal.setColor(QPalette::Highlight,
                  QColor(qt_colorref2qrgb(GetSysColor(COLOR_HIGHLIGHT))));
     pal.setColor(QPalette::HighlightedText,
                  QColor(qt_colorref2qrgb(GetSysColor(COLOR_HIGHLIGHTTEXT))));
 #if defined(Q_WS_WINCE)
     // ### hardcoded until I find out how to get it from the system settings.
     pal.setColor(QPalette::LinkVisited, pal.highlight().color().dark(150));
     pal.setColor(QPalette::Link, pal.highlight().color().light(130));
     // Background == Base on Windows CE
     if (qt_wince_is_smartphone() || qt_wince_is_pocket_pc())
       pal.setColor(QPalette::Background, pal.base().color());
 #else
     pal.setColor(QPalette::Link, Qt::blue);
     pal.setColor(QPalette::LinkVisited, Qt::magenta);
 #endif
     pal.setColor(QPalette::Inactive, QPalette::Button, pal.button().color());
     pal.setColor(QPalette::Inactive, QPalette::Window, pal.background().color());
     pal.setColor(QPalette::Inactive, QPalette::Light, pal.light().color());
     pal.setColor(QPalette::Inactive, QPalette::Dark, pal.dark().color());
     if (pal.midlight() == pal.button())
         pal.setColor(QPalette::Midlight, pal.button().color().lighter(110));
     if (pal.background() != pal.base()) {
         pal.setColor(QPalette::Inactive, QPalette::Highlight, pal.color(QPalette::Inactive, QPalette::Window));
         pal.setColor(QPalette::Inactive, QPalette::HighlightedText, pal.color(QPalette::Inactive, QPalette::Text));
     }
     const QColor bg = pal.background().color();
     const QColor fg = pal.foreground().color(), btn = pal.button().color();
     QColor disabled((fg.red()+btn.red())/2,(fg.green()+btn.green())/2,
                      (fg.blue()+btn.blue())/2);
     pal.setColorGroup(QPalette::Disabled, pal.foreground(), pal.button(), pal.light(),
         pal.dark(), pal.mid(), pal.text(), pal.brightText(), pal.base(), pal.background() );
     pal.setColor(QPalette::Disabled, QPalette::WindowText, disabled);
     pal.setColor(QPalette::Disabled, QPalette::Text, disabled);
     pal.setColor(QPalette::Disabled, QPalette::ButtonText, disabled);
     pal.setColor(QPalette::Disabled, QPalette::Highlight,
                   QColor(qt_colorref2qrgb(GetSysColor(COLOR_HIGHLIGHT))));
     pal.setColor(QPalette::Disabled, QPalette::HighlightedText,
                   QColor(qt_colorref2qrgb(GetSysColor(COLOR_HIGHLIGHTTEXT))));
     pal.setColor(QPalette::Disabled, QPalette::Base, bg);
     QApplicationPrivate::setSystemPalette(pal);
     QApplicationPrivate::initializeWidgetPaletteHash();
     QColor ttip(qt_colorref2qrgb(GetSysColor(COLOR_INFOBK)));
     QColor ttipText(qt_colorref2qrgb(GetSysColor(COLOR_INFOTEXT)));
     {
 #ifndef QT_NO_TOOLTIP
         QPalette tiplabel(pal);
         tiplabel.setColor(QPalette::All, QPalette::Button, ttip);
         tiplabel.setColor(QPalette::All, QPalette::Window, ttip);
         tiplabel.setColor(QPalette::All, QPalette::Text, ttipText);
         tiplabel.setColor(QPalette::All, QPalette::WindowText, ttipText);
         tiplabel.setColor(QPalette::All, QPalette::ButtonText, ttipText);
         tiplabel.setColor(QPalette::All, QPalette::Button, ttip);
         tiplabel.setColor(QPalette::All, QPalette::Window, ttip);
         tiplabel.setColor(QPalette::All, QPalette::Text, ttipText);
         tiplabel.setColor(QPalette::All, QPalette::WindowText, ttipText);
         tiplabel.setColor(QPalette::All, QPalette::ButtonText, ttipText);
         const QColor fg = tiplabel.foreground().color(), btn = tiplabel.button().color();
         QColor disabled((fg.red()+btn.red())/2,(fg.green()+btn.green())/2,
                          (fg.blue()+btn.blue())/2);
         tiplabel.setColor(QPalette::Disabled, QPalette::WindowText, disabled);
         tiplabel.setColor(QPalette::Disabled, QPalette::Text, disabled);
         tiplabel.setColor(QPalette::Disabled, QPalette::Base, Qt::white);
         tiplabel.setColor(QPalette::Disabled, QPalette::BrightText, Qt::white);
         QToolTip::setPalette(tiplabel);
 #endif //QT_NO_TOOLTIP
     }
 }
qt_set_windows_font_resources()
static void qt_set_windows_font_resources () static
Definition at line 609 of file qapplication_win.cpp.
Referenced by QtWndProc().
 {
 #ifndef Q_WS_WINCE
     NONCLIENTMETRICS ncm;
     ncm.cbSize = FIELD_OFFSET(NONCLIENTMETRICS, lfMessageFont) + sizeof(LOGFONT);
     SystemParametersInfo(SPI_GETNONCLIENTMETRICS, ncm.cbSize , &ncm, 0);
     QFont menuFont = qt_LOGFONTtoQFont(ncm.lfMenuFont, true);
     QFont messageFont = qt_LOGFONTtoQFont(ncm.lfMessageFont, true);
     QFont statusFont = qt_LOGFONTtoQFont(ncm.lfStatusFont, true);
     QFont titleFont = qt_LOGFONTtoQFont(ncm.lfCaptionFont, true);
     LOGFONT lfIconTitleFont;
     SystemParametersInfo(SPI_GETICONTITLELOGFONT, sizeof(lfIconTitleFont), &lfIconTitleFont, 0);
     QFont iconTitleFont = qt_LOGFONTtoQFont(lfIconTitleFont, true);
     QApplication::setFont(menuFont, "QMenu");
     QApplication::setFont(menuFont, "QMenuBar");
     QApplication::setFont(messageFont, "QMessageBox");
     QApplication::setFont(statusFont, "QTipLabel");
     QApplication::setFont(statusFont, "QStatusBar");
     QApplication::setFont(titleFont, "Q3TitleBar");
     QApplication::setFont(titleFont, "QWorkspaceTitleBar");
     QApplication::setFont(iconTitleFont, "QAbstractItemView");
     QApplication::setFont(iconTitleFont, "QDockWidgetTitle");
 #else
     LOGFONT lf;
     HGDIOBJ stockFont = GetStockObject(SYSTEM_FONT);
     GetObject(stockFont, sizeof(lf), &lf);
     QFont systemFont = qt_LOGFONTtoQFont(lf, true);
     QApplicationPrivate::setSystemFont(systemFont);
     QFont smallerFont = systemFont;
     if (qt_wince_is_mobile()) {
         smallerFont.setPointSize(systemFont.pointSize()-1);
         QApplication::setFont(smallerFont, "QTabBar");
         smallerFont.setBold(true);
         QApplication::setFont(smallerFont, "QAbstractButton");
     }
 #endif// Q_WS_WINCE
 }
qt_set_windows_resources()
static void qt_set_windows_resources () static
Definition at line 674 of file qapplication_win.cpp.
Referenced by qt_init().
 {
     if (QApplication::type() != QApplication::Tty)
         (void) QApplication::style(); // trigger creation of application style
     qt_set_windows_font_resources();
     qt_set_windows_color_resources();
 }
qt_set_windows_updateScrollBar()
static void qt_set_windows_updateScrollBar (QWidget * widget) static
Definition at line 734 of file qapplication_win.cpp.
Referenced by QtWndProc().
 {
     QList<QObject*> children = widget->children();
     for (int i = 0; i < children.size(); ++i) {
         QObject *o = children.at(i);
         if(!o->isWidgetType())
             continue;
         if (QWidget *w = static_cast<QWidget *>(o))
             qt_set_windows_updateScrollBar(w);
     }
 #ifndef QT_NO_SCROLLBAR
     if (qobject_cast<QScrollBar*>(widget))
         widget->updateGeometry();
 #endif
 }
qt_try_modal()
bool qt_try_modal (QWidget * widget, MSG * msg, int & ret) static
Definition at line 2767 of file qapplication_win.cpp.
Referenced by QtWndProc(), and QETWidget::translateWheelEvent().
 {
 #if defined(Q_OS_WINCE)
     Q_UNUSED(ret);
 #endif
     QWidget * top = 0;
     if (QApplicationPrivate::tryModalHelper(widget, &top))
         return true;
     int type = msg->message;
     bool block_event = false;
 #ifndef Q_WS_WINCE
     if (type != WM_NCHITTEST) {
 #endif
         if ((type >= WM_MOUSEFIRST && type <= WM_MOUSELAST) ||
              type == WM_MOUSEWHEEL || type == WM_MOUSEHWHEEL ||
              type == WM_MOUSELEAVE ||
              (type >= WM_KEYFIRST && type <= WM_KEYLAST)
 #ifndef Q_WS_WINCE
             || type == WM_NCMOUSEMOVE
 #endif
          ) {
             if (type == WM_MOUSEMOVE
 #ifndef Q_WS_WINCE
                  || type == WM_NCMOUSEMOVE
 #endif
             ) {
 #ifndef QT_NO_CURSOR
                 QCursor *c = qt_grab_cursor();
                 if (!c)
                     c = QApplication::overrideCursor();
                 if (c)                                // application cursor defined
                     SetCursor(c->handle());
                 else
                     SetCursor(QCursor(Qt::ArrowCursor).handle());
 #endif // QT_NO_CURSOR
             }
             block_event = true;
         } else if (type == WM_CLOSE) {
             block_event = true;
         }
 #ifndef Q_WS_WINCE
         else if (type == WM_MOUSEACTIVATE || type == WM_NCLBUTTONDOWN){
             if (!top->isActiveWindow()) {
                 top->activateWindow();
             } else {
                 QApplication::beep();
             }
             block_event = true;
             ret = MA_NOACTIVATEANDEAT;
         } else if (type == WM_SYSCOMMAND) {
             if (!(msg->wParam == SC_RESTORE && widget->isMinimized()))
                 block_event = true;
         }
     }
 #endif
     return !block_event;
 }
qt_tryCreateRegion()
HRGN qt_tryCreateRegion (QRegion::RegionType type, int left, int top, int right, int bottom)
Definition at line 55 of file qregion_win.cpp.
Referenced by QtWndProc().
 {
     const int tries = 10;
     for (int i = 0; i < tries; ++i) {
         HRGN region = 0;
         switch (type) {
         case QRegion::Rectangle:
             region = CreateRectRgn(left, top, right, bottom);
             break;
         case QRegion::Ellipse:
 #ifndef Q_OS_WINCE
             region = CreateEllipticRgn(left, top, right, bottom);
 #endif
             break;
         }
         if (region) {
             if (GetRegionData(region, 0, 0))
                 return region;
             else
                 DeleteObject(region);
         }
     }
     return 0;
 }
qt_updateLayeredWindowIndirect()
static BOOL WINAPI qt_updateLayeredWindowIndirect (HWND hwnd, const Q_UPDATELAYEREDWINDOWINFO * info) static
Definition at line 759 of file qapplication_win.cpp.
Referenced by qt_init().
 {
     return (*ptrUpdateLayeredWindow)(hwnd, info->hdcDst, info->pptDst, info->psize, info->hdcSrc,
                                      info->pptSrc, info->crKey, info->pblend, info->dwFlags);
 }
qt_win_display_dc()
Q_GUI_EXPORT HDC qt_win_display_dc ()
Definition at line 942 of file qapplication_win.cpp.
Referenced by QWindowsXPStylePrivate::buffer(), QWindowsXPStyle::drawComplexControl(), QRasterWindowSurface::flush(), QAxHostWidget::paintEvent(), qt_grab_cursor(), and QWindowsXPStylePrivate::tabBody().
 {
     Q_ASSERT(qApp && qApp->thread() == QThread::currentThread());
     if (!displayDC)
         displayDC = GetDC(0);
     return displayDC;
 }
qt_win_eatMouseMove()
void qt_win_eatMouseMove ()
Definition at line 3016 of file qapplication_win.cpp.
Referenced by QPrintDialogPrivate::openWindowsPrintDialogModally(), qt_win_clean_up_OFN(), qt_win_get_existing_directory(), qt_win_get_open_file_name(), qt_win_get_open_file_names(), and qt_win_get_save_file_name().
 {
     // after closing a windows dialog with a double click (i.e. open a file)
     // the message queue still contains a dubious WM_MOUSEMOVE message where
     // the left button is reported to be down (wParam != 0).
     // remove all those messages (usually 1) and post the last one with a
     // reset button state
     MSG msg = {0, 0, 0, 0, 0, {0, 0} };
     while (PeekMessage(&msg, 0, WM_MOUSEMOVE, WM_MOUSEMOVE, PM_REMOVE))
         ;
     if (msg.message == WM_MOUSEMOVE)
         PostMessage(msg.hwnd, msg.message, 0, msg.lParam);
 }
qt_win_getKeyboardModifiers()
Qt::KeyboardModifiers qt_win_getKeyboardModifiers ()
Definition at line 1303 of file qapplication_win.cpp.
Referenced by QtWndProc(), and QETWidget::translateMouseEvent().
 {
     Qt::KeyboardModifiers modifiers = Qt::NoModifier;
     if (GetKeyState(VK_SHIFT) < 0)
         modifiers |= Qt::ShiftModifier;
     if (GetKeyState(VK_CONTROL) < 0)
         modifiers |= Qt::ControlModifier;
     if (GetKeyState(VK_MENU) < 0)
         modifiers |= Qt::AltModifier;
     return modifiers;
 }
qt_win_read_cleartype_settings()
static void qt_win_read_cleartype_settings () static
Definition at line 651 of file qapplication_win.cpp.
Referenced by qt_init(), and QtWndProc().
 {
     UINT result = 0;
 #ifdef Q_OS_WINCE
     if (SystemParametersInfo(SPI_GETFONTSMOOTHING, 0, &result, 0))
         qt_cleartype_enabled = result;
 #else
     if (SystemParametersInfo(SPI_GETFONTSMOOTHINGTYPE, 0, &result, 0))
         qt_cleartype_enabled = (result == FE_FONTSMOOTHINGCLEARTYPE);
 #endif
     int winSmooth;
     if (SystemParametersInfo(0x200C /* SPI_GETFONTSMOOTHINGCONTRAST */, 0, &winSmooth, 0)) {
         qt_fontsmoothing_gamma = winSmooth / qreal(1000.0);
     } else {
         qt_fontsmoothing_gamma = 1.0;
     }
     // Safeguard ourselves against corrupt registry values...
     if (qt_fontsmoothing_gamma > 5 || qt_fontsmoothing_gamma < 1)
         qt_fontsmoothing_gamma = qreal(1.4);
 }
qt_win_set_cursor()
void qt_win_set_cursor (QWidget * w, bool force)
Definition at line 1282 of file qapplication_win.cpp.
Referenced by QApplicationPrivate::dispatchEnterLeave().
 {
     static QPointer<QWidget> lastUnderMouse = 0;
     if (force) {
         lastUnderMouse = w;
     } else if (w->testAttribute(Qt::WA_WState_Created) && lastUnderMouse
                && lastUnderMouse->effectiveWinId() == w->effectiveWinId()) {
         w = lastUnderMouse;
     }
     if (!curWin && w && w->internalWinId())
         return;
     QWidget* cW = w && !w->internalWinId() ? w : QWidget::find(curWin);
     if (!cW || cW->window() != w->window() ||
          !cW->isVisible() || !cW->underMouse() || QApplication::overrideCursor())
         return;
     SetCursor(cW->cursor().handle());
 }
qt_wince_hide_taskbar()
void qt_wince_hide_taskbar (HWND hwnd)
Definition at line 361 of file qguifunctions_wince.cpp.
Referenced by QtWndProc(), and QETWidget::translateConfigEvent().
{
     if (ptrAygFullScreen)
         ptrAygFullScreen(hwnd, SHFS_HIDETASKBAR | SHFS_HIDESIPBUTTON | SHFS_HIDESTARTICON);
 }
qt_wince_is_high_dpi()
bool qt_wince_is_high_dpi ()
Definition at line 300 of file qguifunctions_wince.cpp.
{
     if (!qt_wince_is_pocket_pc())
         return false;
     HDC deviceContext = GetDC(0);
     int dpi = GetDeviceCaps(deviceContext, LOGPIXELSX);
     ReleaseDC(0, deviceContext);
     if ((dpi < 1000) && (dpi > 0))
         return dpi > 96;
     else
         return false;
 }
qt_wince_is_mobile()
bool qt_wince_is_mobile ()
Definition at line 296 of file qguifunctions_wince.cpp.
Referenced by qt_set_windows_font_resources().
{
      return (qt_wince_is_smartphone() || qt_wince_is_pocket_pc());
 }
qt_wince_is_pocket_pc()
bool qt_wince_is_pocket_pc ()
Definition at line 289 of file qguifunctions_wince.cpp.
Referenced by qt_set_windows_color_resources().
{
     return qt_wince_is_platform(QString::fromLatin1("PocketPC"));
 }
qt_wince_is_smartphone()
bool qt_wince_is_smartphone ()
Definition at line 293 of file qguifunctions_wince.cpp.
Referenced by qt_set_windows_color_resources().
{
        return qt_wince_is_platform(QString::fromLatin1("Smartphone"));
 }
QtWndProc()
LRESULT QT_WIN_CALLBACK QtWndProc (HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam)
Definition at line 1475 of file qapplication_win.cpp.
Referenced by qt_reg_winclass(), qt_show_system_menu(), and qt_tablet_cleanup_wce().
 {
     bool result = true;
     QEvent::Type evt_type = QEvent::None;
     QETWidget *widget = 0;
         // there is no need to process pakcets from tablet unless
         // it is actually on the tablet, a flag to let us know...
         int nPackets;        // the number of packets we get from the queue
     long res = 0;
     if (!qApp)                                // unstable app state
 #ifndef QT_NO_IM
         RETURN(QWinInputContext::DefWindowProc(hwnd,message,wParam,lParam))
 #else
         return res;
 #endif // QT_NO_IM
     QScopedLoopLevelCounter loopLevelCounter(QThreadData::get2(qApp->thread()));
 #if 0
     // make sure we update widgets also when the user resizes
     if (inLoop && qApp->loopLevel())
         qApp->sendPostedEvents(0, QEvent::Paint);
 #endif
     inLoop = true;
     MSG msg;
     msg.hwnd = hwnd;                                // create MSG structure
     msg.message = message;                        // time and pt fields ignored
     msg.wParam = wParam;
     msg.lParam = lParam;
     msg.pt.x = GET_X_LPARAM(lParam);
     msg.pt.y = GET_Y_LPARAM(lParam);
     // If it's a non-client-area message the coords are screen coords, otherwise they are
     // client coords.
 #ifndef Q_WS_WINCE
     if (message < WM_NCMOUSEMOVE || message > WM_NCMBUTTONDBLCLK)
 #endif
         ClientToScreen(msg.hwnd, &msg.pt);
     /*
     // sometimes the autograb is not released, so the clickevent is sent
     // to the wrong window. We ignore this for now, because it doesn't
     // cause any problems.
     if (msg.message == WM_LBUTTONDOWN || msg.message == WM_RBUTTONDOWN || msg.message == WM_MBUTTONDOWN) {
         HWND handle = WindowFromPoint(msg.pt);
         if (msg.hwnd != handle) {
             msg.hwnd = handle;
             hwnd = handle;
         }
     }
     */
 #if defined(QT_NON_COMMERCIAL)
     QT_NC_WNDPROC
 #endif
     // send through app filter
     if (qApp->filterEvent(&msg, &res))
         return res;
     // close any opened ime candidate window (enabled only on a popup widget)
     if (imeParentWnd  && QApplication::activePopupWidget()
         && (message == WM_MBUTTONDOWN || message == WM_XBUTTONDOWN
         || message == WM_LBUTTONDOWN || message == WM_RBUTTONDOWN
 #ifndef Q_WS_WINCE
         || message == WM_NCMBUTTONDOWN || message == WM_NCLBUTTONDOWN
         || message == WM_NCRBUTTONDOWN)) {
 #else
                                       )) {
 #endif
             ::SendMessage(imeParentWnd, WM_IME_ENDCOMPOSITION, 0, 0);
     }
     switch (message) {
 #ifndef Q_WS_WINCE
 #ifndef QT_NO_SESSIONMANAGER
     case WM_QUERYENDSESSION: {
         if (sm_smActive) // bogus message from windows
             RETURN(true);
         sm_smActive = true;
         sm_blockUserInput = true; // prevent user-interaction outside interaction windows
         sm_cancel = false;
         if (qt_session_manager_self)
             qApp->commitData(*qt_session_manager_self);
         if (lParam & ENDSESSION_LOGOFF) {
             _flushall();
         }
         RETURN(!sm_cancel);
     }
     case WM_ENDSESSION: {
         sm_smActive = false;
         sm_blockUserInput = false;
         bool endsession = (bool) wParam;
         // we receive the message for each toplevel window included internal hidden ones,
         // but the aboutToQuit signal should be emitted only once.
         QApplicationPrivate *qAppPriv = QApplicationPrivate::instance();
         if (endsession && !qAppPriv->aboutToQuitEmitted) {
             qAppPriv->aboutToQuitEmitted = true;
             int index = QApplication::staticMetaObject.indexOfSignal("aboutToQuit()");
             qApp->qt_metacall(QMetaObject::InvokeMetaMethod, index,0);
             // since the process will be killed immediately quit() has no real effect
             QApplication::quit();
         }
         RETURN(0);
     }
 #endif
     case WM_DISPLAYCHANGE:
         if (QApplication::type() == QApplication::Tty)
             break;
         if (qt_desktopWidget) {
             qt_desktopWidget->move(GetSystemMetrics(76), GetSystemMetrics(77));
             QSize sz(GetSystemMetrics(78), GetSystemMetrics(79));
             if (sz == qt_desktopWidget->size()) {
                  // a screen resized without changing size of the virtual desktop
                 QResizeEvent rs(sz, qt_desktopWidget->size());
                 QApplication::sendEvent(qt_desktopWidget, &rs);
             } else {
                 qt_desktopWidget->resize(sz);
             }
         }
         break;
 #endif
     case WM_SETTINGCHANGE:
 #ifdef Q_WS_WINCE
         // CE SIP hide/show
         if (qt_desktopWidget && wParam == SPI_SETSIPINFO) {
             QResizeEvent re(QSize(0, 0), QSize(0, 0)); // Calculated by QDesktopWidget
             QApplication::sendEvent(qt_desktopWidget, &re);
             break;
         }
 #endif
         // ignore spurious XP message when user logs in again after locking
         if (QApplication::type() == QApplication::Tty)
             break;
         if (QApplication::desktopSettingsAware() && wParam != SPI_SETWORKAREA) {
             widget = (QETWidget*)QWidget::find(hwnd);
             if (widget) {
                 if (wParam == SPI_SETNONCLIENTMETRICS)
                     widget->markFrameStrutDirty();
             }
         }
         else if (qt_desktopWidget && wParam == SPI_SETWORKAREA) {
             qt_desktopWidget->move(GetSystemMetrics(76), GetSystemMetrics(77));
             QSize sz(GetSystemMetrics(78), GetSystemMetrics(79));
             if (sz == qt_desktopWidget->size()) {
                  // a screen resized without changing size of the virtual desktop
                 QResizeEvent rs(sz, qt_desktopWidget->size());
                 QApplication::sendEvent(qt_desktopWidget, &rs);
             } else {
                 qt_desktopWidget->resize(sz);
             }
         }
         if (wParam == SPI_SETFONTSMOOTHINGTYPE) {
             qt_win_read_cleartype_settings();
             foreach (QWidget *w, QApplication::topLevelWidgets()) {
                 if (!w->isVisible())
                     continue;
                 ((QETWidget *) w)->forceUpdate();
             }
         }
         break;
     case WM_SYSCOLORCHANGE:
         if (QApplication::type() == QApplication::Tty)
             break;
         if (QApplication::desktopSettingsAware()) {
             widget = (QETWidget*)QWidget::find(hwnd);
             if (widget && !widget->parentWidget())
                 qt_set_windows_color_resources();
         }
         break;
     case WM_LBUTTONDOWN:
     case WM_MBUTTONDOWN:
     case WM_RBUTTONDOWN:
     case WM_XBUTTONDOWN:
     case WM_LBUTTONDBLCLK:
     case WM_RBUTTONDBLCLK:
     case WM_MBUTTONDBLCLK:
     case WM_XBUTTONDBLCLK:
         if (qt_win_ignoreNextMouseReleaseEvent)
             qt_win_ignoreNextMouseReleaseEvent = false;
         break;
     case WM_LBUTTONUP:
     case WM_MBUTTONUP:
     case WM_RBUTTONUP:
     case WM_XBUTTONUP:
         if (qt_win_ignoreNextMouseReleaseEvent) {
             qt_win_ignoreNextMouseReleaseEvent = false;
             if (qt_button_down && qt_button_down->internalWinId() == autoCaptureWnd) {
                 releaseAutoCapture();
                 qt_button_down = 0;
             }
             RETURN(0);
         }
         break;
     default:
         break;
     }
     if (!widget)
         widget = (QETWidget*)QWidget::find(hwnd);
     if (!widget)                                // don't know this widget
         goto do_default;
     if (app_do_modal)        {                        // modal event handling
         int ret = 0;
         if (!qt_try_modal(widget, &msg, ret))
             RETURN(ret);
     }
     res = 0;
     if (widget->winEvent(&msg, &res))                // send through widget filter
         RETURN(res);
     if (qt_is_translatable_mouse_event(message)) {
         if (QApplication::activePopupWidget() != 0) { // in popup mode
             POINT curPos = msg.pt;
             QWidget* w = QApplication::widgetAt(curPos.x, curPos.y);
             if (w)
                 widget = (QETWidget*)w;
         }
         if (!qt_tabletChokeMouse) {
             result = widget->translateMouseEvent(msg);        // mouse event
 #if defined(Q_WS_WINCE) && !defined(QT_NO_CONTEXTMENU)
             if (message == WM_LBUTTONDOWN && widget != QApplication::activePopupWidget()) {
                 QWidget* alienWidget = widget;
                 if ((alienWidget != QApplication::activePopupWidget()) && (alienWidget->contextMenuPolicy() != Qt::PreventContextMenu)) {
                     QPoint pos(GET_X_LPARAM(lParam), GET_Y_LPARAM(lParam));
                     QPoint globalPos(msg.pt.x, msg.pt.y);
                     // In case we are using Alien, then the widget to
                     // send the context menu event is a different one
                     if (!alienWidget->testAttribute(Qt::WA_NativeWindow) && !alienWidget->testAttribute(Qt::WA_PaintOnScreen)) {
                         alienWidget = QApplication::widgetAt(globalPos);
                         if (alienWidget)
                             pos = alienWidget->mapFromGlobal(globalPos);
                     }
                     if (alienWidget) {
                         SHRGINFO shrg;
                         shrg.cbSize = sizeof(shrg);
                         shrg.hwndClient = hwnd;
                         shrg.ptDown.x = GET_X_LPARAM(lParam);
                         shrg.ptDown.y = GET_Y_LPARAM(lParam);
                         shrg.dwFlags = SHRG_RETURNCMD | SHRG_NOANIMATION;
 #ifndef QT_NO_GESTURES
                         resolveAygLibs();
                         if (ptrRecognizeGesture && (ptrRecognizeGesture(&shrg) == GN_CONTEXTMENU)) {
                             if (QApplication::activePopupWidget())
                                 QApplication::activePopupWidget()->close();
                             QContextMenuEvent e(QContextMenuEvent::Mouse, pos, globalPos);
                             result = qt_sendSpontaneousEvent(alienWidget, &e);
                         }
 #endif // QT_NO_GESTURES
                     }
                 }
             }
 #endif
         } else {
             // Sometimes we only get a WM_MOUSEMOVE message
             // and sometimes we get both a WM_MOUSEMOVE and
             // a WM_LBUTTONDOWN/UP, this creates a spurious mouse
             // press/release event, using the PeekMessage
             // will help us fix this.  This leaves us with a
             // question:
             //    This effectively kills using the mouse AND the
             //    tablet simultaneously, well creates wacky input.
             //    Is this going to be a problem? (probably not)
             bool next_is_button = false;
             bool is_mouse_move = (message == WM_MOUSEMOVE);
             if (is_mouse_move) {
                 MSG msg1;
                 if (PeekMessage(&msg1, msg.hwnd, WM_MOUSEFIRST,
                                 WM_MOUSELAST, PM_NOREMOVE))
                     next_is_button = (msg1.message == WM_LBUTTONUP
                                        || msg1.message == WM_LBUTTONDOWN);
             }
             if (!is_mouse_move || (is_mouse_move && !next_is_button))
                 qt_tabletChokeMouse = false;
         }
     } else {
         switch (message) {
         case WM_TOUCH:
             result = QApplicationPrivate::instance()->translateTouchEvent(msg);
             break;
         case WM_KEYDOWN:                        // keyboard event
         case WM_SYSKEYDOWN:
             qt_keymapper_private()->updateKeyMap(msg);
             // fall-through intended
         case WM_KEYUP:
         case WM_SYSKEYUP:
 #if Q_OS_WINCE_WM
         case WM_HOTKEY:
             if(HIWORD(msg.lParam) == VK_TBACK) {
                 const bool hotKeyDown = !(LOWORD(msg.lParam) & MOD_KEYUP);
                 msg.lParam = 0x69 << 16;
                 msg.wParam = VK_BACK;
                 if (hotKeyDown) {
                     msg.message = WM_KEYDOWN;
                     qt_keymapper_private()->updateKeyMap(msg);
                 } else {
                     msg.message = WM_KEYUP;
                 }
             }
             // fall-through intended
 #endif
         case WM_IME_CHAR:
         case WM_IME_KEYDOWN:
         case WM_CHAR: {
             MSG msg1;
             bool anyMsg = PeekMessage(&msg1, msg.hwnd, 0, 0, PM_NOREMOVE);
             if (anyMsg && msg1.message == WM_DEADCHAR) {
                 result = true; // consume event since there is a dead char next
                 break;
             }
             QWidget *g = QWidget::keyboardGrabber();
             if (g && qt_get_tablet_widget() && hwnd == qt_get_tablet_widget()->winId()) {
                 // if we get an event for the internal tablet widget,
                 // then don't send it to the keyboard grabber, but
                 // send it to the widget itself (we don't use it right
                 // now, just in case).
                 g = 0;
             }
             if (g)
                 widget = (QETWidget*)g;
             else if (QApplication::activePopupWidget())
                 widget = (QETWidget*)QApplication::activePopupWidget()->focusWidget()
                        ? (QETWidget*)QApplication::activePopupWidget()->focusWidget()
                        : (QETWidget*)QApplication::activePopupWidget();
             else if (QApplication::focusWidget())
                 widget = (QETWidget*)QApplication::focusWidget();
             else if (!widget || widget->internalWinId() == GetFocus()) // We faked the message to go to exactly that widget.
                 widget = (QETWidget*)widget->window();
             if (widget->isEnabled())
                 result = sm_blockUserInput
                             ? true
                             : qt_keymapper_private()->translateKeyEvent(widget, msg, g != 0);
             break;
         }
         case WM_SYSCHAR:
             result = true;                        // consume event
             break;
         case WM_MOUSEWHEEL:
         case WM_MOUSEHWHEEL:
             result = widget->translateWheelEvent(msg);
             break;
         case WM_APPCOMMAND:
             {
                 uint cmd = GET_APPCOMMAND_LPARAM(lParam);
                 uint uDevice = GET_DEVICE_LPARAM(lParam);
                 uint dwKeys = GET_KEYSTATE_LPARAM(lParam);
                 int state = translateButtonState(dwKeys, QEvent::KeyPress, 0);
                 switch (uDevice) {
                 case FAPPCOMMAND_KEY:
                     {
                         int key = 0;
                         switch(cmd) {
                         case APPCOMMAND_BASS_BOOST:
                             key = Qt::Key_BassBoost;
                             break;
                         case APPCOMMAND_BASS_DOWN:
                             key = Qt::Key_BassDown;
                             break;
                         case APPCOMMAND_BASS_UP:
                             key = Qt::Key_BassUp;
                             break;
                         case APPCOMMAND_TREBLE_DOWN:
                             key = Qt::Key_TrebleDown;
                             break;
                         case APPCOMMAND_TREBLE_UP:
                             key = Qt::Key_TrebleUp;
                             break;
                         case APPCOMMAND_HELP:
                             key = Qt::Key_Help;
                             break;
                         case APPCOMMAND_FIND:
                             key = Qt::Key_Search;
                             break;
                         default:
                             break;
                         }
                         if (key) {
                             bool res = false;
                             QWidget *g = QWidget::keyboardGrabber();
                             if (g)
                                 widget = (QETWidget*)g;
                             else if (QApplication::focusWidget())
                                 widget = (QETWidget*)QApplication::focusWidget();
                             else
                                 widget = (QETWidget*)widget->window();
                             if (widget->isEnabled()) {
                                 res = QKeyMapper::sendKeyEvent(widget, g != 0, QEvent::KeyPress, key,
                                                                Qt::KeyboardModifier(state),
                                                                QString(), false, 0, 0, 0, 0);
                             }
                             if (res)
                                 return true;
                         }
                     }
                     break;
                 default:
                     break;
                 }
                 result = false;
             }
             break;
 #ifndef Q_WS_WINCE
         case WM_NCHITTEST:
             if (widget->isWindow()) {
                 QPoint pos = widget->mapFromGlobal(QPoint(GET_X_LPARAM(lParam), GET_Y_LPARAM(lParam)));
                 // don't show resize-cursors for fixed-size widgets
                 QRect fs = widget->frameStrut();
                 if (!widget->isMinimized()) {
                     if (widget->minimumHeight() == widget->maximumHeight()) {
                         if (pos.y() < -(fs.top() - fs.left()))
                             return HTCAPTION;
                         if (pos.y() >= widget->height())
                             return HTBORDER;
                     }
                     if (widget->minimumWidth() == widget->maximumWidth() && (pos.x() < 0 || pos.x() >= widget->width()))
                         return HTBORDER;
                 }
             }
             result = false;
             break;
 #endif
         case WM_SYSCOMMAND: {
 #ifndef Q_WS_WINCE
             bool window_state_change = false;
             Qt::WindowStates oldstate = Qt::WindowStates(widget->dataPtr()->window_state);
             // MSDN:In WM_SYSCOMMAND messages, the four low-order bits of the wParam parameter are
             // used internally by the system. To obtain the correct result when testing the value of
             // wParam, an application must combine the value 0xFFF0 with the wParam value by using
             // the bitwise AND operator.
             switch(0xfff0 & wParam) {
             case SC_CONTEXTHELP:
 #ifndef QT_NO_WHATSTHIS
                 QWhatsThis::enterWhatsThisMode();
 #endif
                 DefWindowProc(hwnd, WM_NCPAINT, 1, 0);
                 break;
 #if defined(QT_NON_COMMERCIAL)
                 QT_NC_SYSCOMMAND
 #endif
             case SC_MINIMIZE:
                 window_state_change = true;
                 widget->dataPtr()->window_state |= Qt::WindowMinimized;
                 if (widget->isVisible()) {
                     QHideEvent e;
                     qt_sendSpontaneousEvent(widget, &e);
                     widget->hideChildren(true);
                     const QString title = widget->windowIconText();
                     if (!title.isEmpty())
                         widget->setWindowTitle_helper(title);
                 }
                 result = false;
                 break;
             case SC_MAXIMIZE:
                 if(widget->isWindow())
                     widget->topData()->normalGeometry = widget->geometry();
             case SC_RESTORE:
                 window_state_change = true;
                 if ((0xfff0 & wParam) == SC_MAXIMIZE)
                     widget->dataPtr()->window_state |= Qt::WindowMaximized;
                 else if (!widget->isMinimized())
                     widget->dataPtr()->window_state &= ~Qt::WindowMaximized;
                 if (widget->isMinimized()) {
                     widget->dataPtr()->window_state &= ~Qt::WindowMinimized;
                     widget->showChildren(true);
                     QShowEvent e;
                     qt_sendSpontaneousEvent(widget, &e);
                     const QString title = widget->windowTitle();
                     if (!title.isEmpty())
                         widget->setWindowTitle_helper(title);
                 }
                 result = false;
                 break;
             default:
                 result = false;
                 break;
             }
             if (window_state_change) {
                 QWindowStateChangeEvent e(oldstate);
                 qt_sendSpontaneousEvent(widget, &e);
             }
 #endif // #ifndef Q_OS_WINCE
             break;
         }
         case WM_SETTINGCHANGE:
             if ( QApplication::type() == QApplication::Tty )
                 break;
             if (!msg.wParam) {
 #ifdef Q_WS_WINCE
                 // On Windows CE, lParam parameter is a constant, not a char pointer.
                 if (msg.lParam == INI_INTL) {
 #else
                 QString area = QString::fromWCharArray((wchar_t*)msg.lParam);
                 if (area == QLatin1String("intl")) {
 #endif
                     QLocalePrivate::updateSystemPrivate();
                     if (!widget->testAttribute(Qt::WA_SetLocale))
                         widget->dptr()->setLocale_helper(QLocale(), true);
                     QEvent e(QEvent::LocaleChange);
                     QApplication::sendEvent(qApp, &e);
                 }
             }
             else if (msg.wParam == SPI_SETICONTITLELOGFONT) {
                 if (QApplication::desktopSettingsAware()) {
                     widget = (QETWidget*)QWidget::find(hwnd);
                     if (widget && !widget->parentWidget()) {
                         qt_set_windows_font_resources();
                     }
                 }
             }
             else if (msg.wParam == SPI_SETNONCLIENTMETRICS) {
                 widget = (QETWidget*)QWidget::find(hwnd);
                 if (widget && !widget->parentWidget()) {
                     qt_set_windows_updateScrollBar(widget);
                     QEvent e(QEvent::LayoutRequest);
                     QApplication::sendEvent(widget, &e);
                 }
         }
             break;
         case WM_PAINT:                                // paint event
         case WM_ERASEBKGND:                        // erase window background
             result = widget->translatePaintEvent(msg);
             break;
 #ifndef Q_WS_WINCE
         case WM_ENTERSIZEMOVE:
             autoCaptureWnd = hwnd;
             break;
         case WM_EXITSIZEMOVE:
             autoCaptureWnd = 0;
             break;
 #endif
         case WM_MOVE:                                // move window
         case WM_SIZE:                                // resize window
             result = widget->translateConfigEvent(msg);
             break;
         case WM_ACTIVATEAPP:
             if (wParam == FALSE) {
                 QApplication::setActiveWindow(0);
                 // Another application was activated while our popups are open,
                 // then close all popups.  In case some popup refuses to close,
                 // we give up after 1024 attempts (to avoid an infinite loop).
                 int maxiter = 1024;
                 QWidget *popup;
                 while ((popup=QApplication::activePopupWidget()) && maxiter--)
                     popup->close();
             }
             break;
         case WM_ACTIVATE:
             if ( QApplication::type() == QApplication::Tty )
                 break;
             if (ptrWTOverlap && ptrWTEnable) {
                 // cooperate with other tablet applications, but when
                 // we get focus, I want to use the tablet...
                 if (qt_tablet_context && GET_WM_ACTIVATE_STATE(wParam, lParam)) {
                     if (ptrWTEnable(qt_tablet_context, true))
                         ptrWTOverlap(qt_tablet_context, true);
                 }
             }
             if (QApplication::activePopupWidget() && LOWORD(wParam) == WA_INACTIVE &&
                 QWidget::find((HWND)lParam) == 0) {
                 // Another application was activated while our popups are open,
                 // then close all popups.  In case some popup refuses to close,
                 // we give up after 1024 attempts (to avoid an infinite loop).
                 int maxiter = 1024;
                 QWidget *popup;
                 while ((popup=QApplication::activePopupWidget()) && maxiter--)
                     popup->close();
             }
             if (LOWORD(wParam) != WA_INACTIVE) {
                 // WM_ACTIVATEAPP handles the "true" false case, as this is only when the application
                 // loses focus. Doing it here would result in the widget getting focus to not know
                 // where it got it from; it would simply get a 0 value as the old focus widget.
 #ifdef Q_WS_WINCE
                 {
 #ifdef Q_WS_WINCE_WM
                     // On Windows mobile we do not receive WM_SYSCOMMAND / SC_MINIMIZE messages.
                     // Thus we have to unset the minimized state explicitly. We must do this for all
                     // top-level widgets, because we get the HWND of a random widget here.
                     foreach (QWidget* tlw, QApplication::topLevelWidgets()) {
                         if (tlw->isMinimized())
                             tlw->setWindowState(tlw->windowState() & ~Qt::WindowMinimized);
                     }
 #else
                     // On Windows CE we do not receive WM_SYSCOMMAND / SC_MINIMIZE messages.
                     // Thus we have to unset the minimized state explicitly.
                     if (widget->windowState() & Qt::WindowMinimized)
                         widget->setWindowState(widget->windowState() & ~Qt::WindowMinimized);
 #endif  // Q_WS_WINCE_WM
 #else
                 if (!(widget->windowState() & Qt::WindowMinimized)) {
 #endif
                     // Ignore the activate message send by WindowsXP to a minimized window
 #ifdef Q_WS_WINCE_WM
                     if  (widget->windowState() & Qt::WindowFullScreen)
                         qt_wince_hide_taskbar(widget->winId());
 #endif
                     qApp->winFocus(widget, true);
                     // reset any window alert flashes
                     alert_widget(widget, -1);
                 }
             }
             // Windows tries to activate a modally blocked window.
             // This happens when restoring an application after "Show Desktop"
             if (app_do_modal && LOWORD(wParam) == WA_ACTIVE) {
                 QWidget *top = 0;
                 if (!QApplicationPrivate::tryModalHelper(widget, &top) && top && widget != top) {
                     if (top->isVisible()) {
                         top->activateWindow();
                     } else {
                         // This is the case when native file dialogs are shown
                         QWidget *p = (top->parentWidget() ? top->parentWidget()->window() : 0);
                         if (p && p->isVisible())
                             p->activateWindow();
                     }
                 }
             }
             break;
 #ifndef Q_WS_WINCE
             case WM_MOUSEACTIVATE:
                 if (widget->window()->windowType() == Qt::Tool) {
                     QWidget *w = widget;
                     if (!w->window()->focusWidget()) {
                         while (w && (w->focusPolicy() & Qt::ClickFocus) == 0) {
                             if (w->isWindow()) {
                                 QWidget *fw = w;
                                 while ((fw = fw->nextInFocusChain()) != w && fw->focusPolicy() == Qt::NoFocus)
                                     ;
                                 if (fw != w)
                                    break;
                                 QWidget *pw = w->parentWidget();
                                 while (pw) {
                                     pw = pw->window();
                                     if (pw && pw->isVisible() && pw->focusWidget()) {
                                         Q_ASSERT(pw->testAttribute(Qt::WA_WState_Created));
                                         SetWindowPos(pw->internalWinId(), HWND_TOP, 0, 0, 0, 0, SWP_NOSIZE | SWP_NOMOVE);
                                         break;
                                     }
                                     pw = pw->parentWidget();
                                 }
                                 RETURN(MA_NOACTIVATE);
                             }
                             w = w->parentWidget();
                         }
                     }
                 }
                 RETURN(MA_ACTIVATE);
                 break;
 #endif
             case WM_SHOWWINDOW:
                 if (lParam == SW_PARENTOPENING) {
                     if (widget->testAttribute(Qt::WA_WState_Hidden))
                         RETURN(0);
                 }
                 if (widget->isWindow() && widget->testAttribute(Qt::WA_WState_Visible)
                     && !widget->testWindowState(Qt::WindowMinimized)) {
                     if (lParam == SW_PARENTOPENING) {
                         QShowEvent e;
                         qt_sendSpontaneousEvent(widget, &e);
                         widget->showChildren(true);
                     } else if (lParam == SW_PARENTCLOSING) {
                         QHideEvent e;
                         qt_sendSpontaneousEvent(widget, &e);
                         widget->hideChildren(true);
                     }
                 }
                 if  (!wParam && autoCaptureWnd == widget->internalWinId())
                     releaseAutoCapture();
                 result = false;
                 break;
         case WM_PALETTECHANGED:                        // our window changed palette
             if (QColormap::hPal() && (WId)wParam == widget->internalWinId())
                 RETURN(0);                        // otherwise: FALL THROUGH!
             // FALL THROUGH
         case WM_QUERYNEWPALETTE:                // realize own palette
             if (QColormap::hPal()) {
                 Q_ASSERT(widget->testAttribute(Qt::WA_WState_Created));
                 HDC hdc = GetDC(widget->internalWinId());
                 HPALETTE hpalOld = SelectPalette(hdc, QColormap::hPal(), FALSE);
                 uint n = RealizePalette(hdc);
                 if (n)
                     InvalidateRect(widget->internalWinId(), 0, TRUE);
                 SelectPalette(hdc, hpalOld, TRUE);
                 RealizePalette(hdc);
                 ReleaseDC(widget->internalWinId(), hdc);
                 RETURN(n);
             }
             break;
         case WM_CLOSE:                                // close window
             widget->translateCloseEvent(msg);
             RETURN(0);                                // always handled
         case WM_DESTROY:                        // destroy window
             if (hwnd == curWin) {
                 QWidget *enter = QWidget::mouseGrabber();
                 if (enter == widget)
                     enter = 0;
                 QApplicationPrivate::dispatchEnterLeave(enter, widget);
                 curWin = enter ? enter->effectiveWinId() : 0;
                 qt_last_mouse_receiver = enter;
             }
             if (widget == popupButtonFocus)
                 popupButtonFocus = 0;
             result = false;
             break;
 #ifndef Q_WS_WINCE
         case WM_WINDOWPOSCHANGING:
             {
                 result = false;
                 if (widget->isWindow()) {
                     WINDOWPOS *winPos = (WINDOWPOS *)lParam;
                     if (widget->layout() && widget->layout()->hasHeightForWidth()
                         && !(winPos->flags & (SWP_NOCOPYBITS | SWP_NOSIZE))) {
                         QRect fs = widget->frameStrut();
                         QRect rect = widget->geometry();
                         QRect newRect = QRect(winPos->x + fs.left(),
                                               winPos->y + fs.top(),
                                               winPos->cx - fs.left() - fs.right(),
                                               winPos->cy - fs.top() - fs.bottom());
                         QSize newSize = QLayout::closestAcceptableSize(widget, newRect.size());
                         int dh = newSize.height() - newRect.height();
                         int dw = newSize.width() - newRect.width();
                         if (!dw && ! dh)
                             break; // Size OK
                         if (rect.y() != newRect.y()) {
                             newRect.setTop(newRect.top() - dh);
                         } else {
                             newRect.setBottom(newRect.bottom() + dh);
                         }
                         if (rect.x() != newRect.x()) {
                             newRect.setLeft(newRect.left() - dw);
                         } else {
                             newRect.setRight(newRect.right() + dw);
                         }
                         winPos->x = newRect.x() - fs.left();
                         winPos->y = newRect.y() - fs.top();
                         winPos->cx = newRect.width() + fs.left() + fs.right();
                         winPos->cy = newRect.height() + fs.top() + fs.bottom();
                         RETURN(0);
                     }
                     if (widget->windowFlags() & Qt::WindowStaysOnBottomHint) {
                         winPos->hwndInsertAfter = HWND_BOTTOM;
                     }
                 }
             }
             break;
         case WM_GETMINMAXINFO:
             if (widget->xtra()) {
                 MINMAXINFO *mmi = (MINMAXINFO *)lParam;
                 QWExtra *x = widget->xtra();
                 QRect fs = widget->frameStrut();
                 if ( x->minw > 0 )
                     mmi->ptMinTrackSize.x = x->minw + fs.right() + fs.left();
                 if ( x->minh > 0 )
                     mmi->ptMinTrackSize.y = x->minh + fs.top() + fs.bottom();
                 qint32 maxw = (x->maxw >= x->minw) ? x->maxw : x->minw;
                 qint32 maxh = (x->maxh >= x->minh) ? x->maxh : x->minh;
                 if ( maxw < QWIDGETSIZE_MAX ) {
                     mmi->ptMaxTrackSize.x = maxw + fs.right() + fs.left();
                     // windows with title bar have an implicit size limit of 112 pixels
                     if (widget->windowFlags() & Qt::WindowTitleHint)
                         mmi->ptMaxTrackSize.x = qMax<long>(mmi->ptMaxTrackSize.x, 112);
                 }
                 if ( maxh < QWIDGETSIZE_MAX )
                     mmi->ptMaxTrackSize.y = maxh + fs.top() + fs.bottom();
                 RETURN(0);
             }
             break;
 #ifndef QT_NO_CONTEXTMENU
             case WM_CONTEXTMENU:
             {
                 // it's not VK_APPS or Shift+F10, but a click in the NC area
                 if (lParam != (int)0xffffffff) {
                     result = false;
                     break;
                 }
                 QWidget *fw = QWidget::keyboardGrabber();
                 if (!fw) {
                     if (QApplication::activePopupWidget())
                         fw = (QApplication::activePopupWidget()->focusWidget()
                                                   ? QApplication::activePopupWidget()->focusWidget()
                                                   : QApplication::activePopupWidget());
                     else if (QApplication::focusWidget())
                         fw = QApplication::focusWidget();
                     else if (widget)
                         fw = widget->window();
                 }
                 if (fw && fw->isEnabled()) {
                     QPoint pos = fw->inputMethodQuery(Qt::ImMicroFocus).toRect().center();
                     QContextMenuEvent e(QContextMenuEvent::Keyboard, pos, fw->mapToGlobal(pos),
                                       qt_win_getKeyboardModifiers());
                     result = qt_sendSpontaneousEvent(fw, &e);
                 }
             }
             break;
 #endif
 #endif
 #ifndef QT_NO_IM
         case WM_IME_STARTCOMPOSITION:
         case WM_IME_ENDCOMPOSITION:
         case WM_IME_COMPOSITION: {
             QWidget *fw = QApplication::focusWidget();
             QWinInputContext *im = fw ? qobject_cast<QWinInputContext *>(fw->inputContext()) : 0;
             if (fw && im) {
                 if(message == WM_IME_STARTCOMPOSITION)
                     result = im->startComposition();
                 else if (message == WM_IME_ENDCOMPOSITION)
                     result = im->endComposition();
                 else if (message == WM_IME_COMPOSITION)
                     result = im->composition(lParam);
             }
             break;
         }
         case WM_IME_REQUEST: {
             QWidget *fw = QApplication::focusWidget();
             QWinInputContext *im = fw ? qobject_cast<QWinInputContext *>(fw->inputContext()) : 0;
             if (fw && im) {
                 if(wParam == IMR_RECONVERTSTRING) {
                     int ret = im->reconvertString((RECONVERTSTRING *)lParam);
                     if (ret == -1) {
                         result = false;
                     } else {
                         return ret;
                     }
                 } else if (wParam == IMR_CONFIRMRECONVERTSTRING) {
                     RETURN(TRUE);
                 } else {
                     // in all other cases, call DefWindowProc()
                     result = false;
                 }
             }
             break;
         }
 #endif // QT_NO_IM
 #ifndef Q_WS_WINCE
         case WM_CHANGECBCHAIN:
         case WM_DRAWCLIPBOARD:
 #endif
         case WM_RENDERFORMAT:
         case WM_RENDERALLFORMATS:
 #ifndef QT_NO_CLIPBOARD
         case WM_DESTROYCLIPBOARD:
             if (qt_clipboard) {
                 QClipboardEvent e(reinterpret_cast<QEventPrivate *>(&msg));
                 qt_sendSpontaneousEvent(qt_clipboard, &e);
                 RETURN(0);
             }
             result = false;
             break;
 #endif //QT_NO_CLIPBOARD
 #ifndef QT_NO_ACCESSIBILITY
         case WM_GETOBJECT:
             {
 #if !defined(Q_OS_WINCE)
                 /* On Win64, lParam can be 0x00000000fffffffc or 0xfffffffffffffffc (!),
                    but MSDN says that lParam should be converted to a DWORD
                    before its compared against OBJID_CLIENT
                 */
                 const DWORD dwObjId = (DWORD)lParam;
                 // Ignoring all requests while starting up
                 if (QApplication::startingUp() || QApplication::closingDown() || dwObjId != OBJID_CLIENT) {
                     result = false;
                     break;
                 }
                 typedef LRESULT (WINAPI *PtrLresultFromObject)(REFIID, WPARAM, LPUNKNOWN);
                 static PtrLresultFromObject ptrLresultFromObject = 0;
                 static bool oleaccChecked = false;
                 if (!oleaccChecked) {
                     QSystemLibrary oleacclib(QLatin1String("oleacc"));
                     ptrLresultFromObject = (PtrLresultFromObject)oleacclib.resolve("LresultFromObject");
                     oleaccChecked = true;
                 }
                 if (ptrLresultFromObject) {
                     QAccessibleInterface *acc = QAccessible::queryAccessibleInterface(widget);
                     if (!acc) {
                         result = false;
                         break;
                     }
                     // and get an instance of the IAccessibile implementation
                     IAccessible *iface = qt_createWindowsAccessible(acc);
                     res = ptrLresultFromObject(IID_IAccessible, wParam, iface);  // ref == 2
                     iface->Release(); // the client will release the object again, and then it will destroy itself
                     if (res > 0)
                         RETURN(res);
                 }
 #endif
             }
             result = false;
             break;
         case WM_GETTEXT:
             if (!widget->isWindow()) {
                 int ret = 0;
                 QAccessibleInterface *acc = QAccessible::queryAccessibleInterface(widget);
                 if (acc) {
                     QString text = acc->text(QAccessible::Name, 0);
                     if (text.isEmpty())
                         text = widget->objectName();
                     ret = qMin<int>(wParam - 1, text.size());
                     text.resize(ret);
                     memcpy((void *)lParam, text.utf16(), (text.size() + 1) * sizeof(ushort));
                     delete acc;
                 }
                 if (!ret) {
                     result = false;
                     break;
                 }
                 RETURN(ret);
             }
             result = false;
             break;
 #endif
         case WT_PACKET:
             if (ptrWTPacketsGet) {
                 if ((nPackets = ptrWTPacketsGet(qt_tablet_context, QT_TABLET_NPACKETQSIZE, &localPacketBuf))) {
                     result = widget->translateTabletEvent(msg, localPacketBuf, nPackets);
                 }
             }
             break;
         case WT_PROXIMITY:
             #ifndef QT_NO_TABLETEVENT
             if (ptrWTPacketsGet && ptrWTInfo) {
                 const bool enteredProximity = LOWORD(lParam) != 0;
                 PACKET proximityBuffer[1]; // we are only interested in the first packet in this case
                 const int totalPacks = ptrWTPacketsGet(qt_tablet_context, 1, proximityBuffer);
                 if (totalPacks > 0) {
                     const UINT currentCursor = proximityBuffer[0].pkCursor;
                     UINT csr_physid;
                     ptrWTInfo(WTI_CURSORS + currentCursor, CSR_PHYSID, &csr_physid);
                     UINT csr_type;
                     ptrWTInfo(WTI_CURSORS + currentCursor, CSR_TYPE, &csr_type);
                     const UINT deviceIdMask = 0xFF6; // device type mask && device color mask
                     quint64 uniqueId = (csr_type & deviceIdMask);
                     uniqueId = (uniqueId << 32) | csr_physid;
                     // initialising and updating the cursor should be done in response to
                     // WT_CSRCHANGE. We do it in WT_PROXIMITY because some wintab never send
                     // the event WT_CSRCHANGE even if asked with CXO_CSRMESSAGES
                     const QTabletCursorInfo *const globalCursorInfo = tCursorInfo();
                     if (!globalCursorInfo->contains(uniqueId))
                         tabletInit(uniqueId, csr_type, qt_tablet_context);
                     currentTabletPointer = globalCursorInfo->value(uniqueId);
                     tabletUpdateCursor(currentTabletPointer, currentCursor);
                 }
                 qt_tabletChokeMouse = false;
                 QTabletEvent tabletProximity(enteredProximity ? QEvent::TabletEnterProximity
                                                               : QEvent::TabletLeaveProximity,
                                              QPoint(), QPoint(), QPointF(), currentTabletPointer.currentDevice, currentTabletPointer.currentPointerType, 0, 0,
                                              0, 0, 0, 0, 0, currentTabletPointer.llId);
                 QApplication::sendEvent(qApp, &tabletProximity);
             }
             #endif // QT_NO_TABLETEVENT
             break;
 #ifdef Q_WS_WINCE_WM
         case WM_SETFOCUS: {
             HIMC hC;
             hC = ImmGetContext(hwnd);
             ImmSetOpenStatus(hC, TRUE);
             ImmEscape(NULL, hC, IME_ESC_SET_MODE, (LPVOID)IM_SPELL);
             result = false;
         }
         break;
 #endif
         case WM_KILLFOCUS:
             if (!QWidget::find((HWND)wParam)) { // we don't get focus, so unset it now
                 if (!widget->hasFocus()) // work around Windows bug after minimizing/restoring
                     widget = (QETWidget*)QApplication::focusWidget();
                 HWND focus = ::GetFocus();
                 //if there is a current widget and the new widget belongs to the same toplevel window
                 //or if the current widget was embedded into non-qt window (i.e. we won't get WM_ACTIVATEAPP)
                 //then we clear the focus on the widget
                 //in case the new widget belongs to a different widget hierarchy, clearing the focus
                 //will be handled because the active window will change
                 const bool embedded = widget && ((QETWidget*)widget->window())->topData()->embedded;
                 if (widget && (embedded || ::IsChild(widget->window()->internalWinId(), focus))) {
                     widget->clearFocus();
                     result = true;
                 } else {
                     result = false;
                 }
             } else {
                 result = false;
             }
             break;
         case WM_THEMECHANGED:
             if ((widget->windowType() == Qt::Desktop) || !qApp || QApplication::closingDown()
                                                          || QApplication::type() == QApplication::Tty)
                 break;
             if (widget->testAttribute(Qt::WA_WState_Polished))
                 QApplication::style()->unpolish(widget);
             if (widget->testAttribute(Qt::WA_WState_Polished))
                 QApplication::style()->polish(widget);
             widget->repolishStyle(*QApplication::style());
             if (widget->isVisible())
                 widget->update();
             break;
 #ifndef Q_WS_WINCE
         case WM_INPUTLANGCHANGE: {
             wchar_t info[7];
             if (!GetLocaleInfo(MAKELCID(lParam, SORT_DEFAULT), LOCALE_IDEFAULTANSICODEPAGE, info, 6)) {
                 inputcharset = CP_ACP;
             } else {
                 inputcharset = QString::fromWCharArray(info).toInt();
             }
             QKeyMapper::changeKeyboard();
             break;
         }
 #else
         case WM_COMMAND: {
             bool OkCommand = (LOWORD(wParam) == 0x1);
             bool CancelCommand = (LOWORD(wParam) == 0x2);
             if (OkCommand)
                 QApplication::postEvent(widget, new QEvent(QEvent::OkRequest));
             if (CancelCommand)
                 widget->showMinimized();
             else
 #ifndef QT_NO_MENUBAR
                 QMenuBar::wceCommands(LOWORD(wParam));
 #endif
             result = true;
         }
             break;
         case WM_HELP:
             QApplication::postEvent(widget, new QEvent(QEvent::HelpRequest));
             result = true;
             break;
 #endif
         case WM_MOUSELEAVE:
             // We receive a mouse leave for curWin, meaning
             // the mouse was moved outside our widgets
             if (widget->internalWinId() == curWin) {
                 bool dispatch = !widget->underMouse();
                 // hasMouse is updated when dispatching enter/leave,
                 // so test if it is actually up-to-date
                 if (!dispatch) {
                     QRect geom = widget->geometry();
                     if (widget->parentWidget() && !widget->isWindow()) {
                         QPoint gp = widget->parentWidget()->mapToGlobal(widget->pos());
                         geom.setX(gp.x());
                         geom.setY(gp.y());
                     }
                     QPoint cpos = QCursor::pos();
                     dispatch = !geom.contains(cpos);
                     if ( !dispatch && !QWidget::mouseGrabber()) {
                         QWidget *hittest = QApplication::widgetAt(cpos);
                         dispatch = !hittest || hittest->internalWinId() != curWin;
                     }
                     if (!dispatch) {
                         HRGN hrgn = qt_tryCreateRegion(QRegion::Rectangle, 0,0,0,0);
                         if (GetWindowRgn(curWin, hrgn) != ERROR) {
                             QPoint lcpos = widget->mapFromGlobal(cpos);
                             dispatch = !PtInRegion(hrgn, lcpos.x(), lcpos.y());
                         }
                         DeleteObject(hrgn);
                     }
                 }
                 if (dispatch) {
                     if (qt_last_mouse_receiver && !qt_last_mouse_receiver->internalWinId())
                         QApplicationPrivate::dispatchEnterLeave(0, qt_last_mouse_receiver);
                     else
                         QApplicationPrivate::dispatchEnterLeave(0, QWidget::find((WId)curWin));
                     curWin = 0;
                     qt_last_mouse_receiver = 0;
                 }
             }
             break;
         case WM_CANCELMODE:
             {
                 // this goes through QMenuBar's event filter
                 QEvent e(QEvent::ActivationChange);
                 QApplication::sendEvent(qApp, &e);
             }
             break;
         case WM_IME_NOTIFY:
             // special handling for ime, only for widgets in a popup
             if (wParam  == IMN_OPENCANDIDATE) {
                 imeParentWnd = hwnd;
                 if (QApplication::activePopupWidget()) {
                     // temporarily disable the mouse grab to allow mouse input in
                     // the ime candidate window. The actual handle is untouched
                     if (autoCaptureWnd)
                         ReleaseCapture();
                 }
             } else if (wParam  == IMN_CLOSECANDIDATE) {
                 imeParentWnd = 0;
                 if (QApplication::activePopupWidget()) {
                     // undo the action above, when candidate window is closed
                     if (autoCaptureWnd)
                         SetCapture(autoCaptureWnd);
                 }
             }
             result = false;
             break;
 #ifndef QT_NO_GESTURES
 #if !defined(Q_WS_WINCE) || defined(QT_WINCE_GESTURES)
         case WM_GESTURE: {
             GESTUREINFO gi;
             memset(&gi, 0, sizeof(GESTUREINFO));
             gi.cbSize = sizeof(GESTUREINFO);
             QApplicationPrivate *qAppPriv = QApplicationPrivate::instance();
             BOOL bResult = false;
             if (qAppPriv->GetGestureInfo)
                 bResult = qAppPriv->GetGestureInfo((HANDLE)msg.lParam, &gi);
             if (bResult) {
                 if (gi.dwID == GID_BEGIN) {
                     // find the alien widget for the gesture position.
                     // This might not be accurate as the position is the center
                     // point of two fingers for multi-finger gestures.
                     QPoint pt(gi.ptsLocation.x, gi.ptsLocation.y);
                     QWidget *w = widget->childAt(widget->mapFromGlobal(pt));
                     qAppPriv->gestureWidget = w ? w : widget;
                 }
                 if (qAppPriv->gestureWidget)
                     static_cast<QETWidget*>(qAppPriv->gestureWidget)->translateGestureEvent(msg, gi);
                 if (qAppPriv->CloseGestureInfoHandle)
                     qAppPriv->CloseGestureInfoHandle((HANDLE)msg.lParam);
                 if (gi.dwID == GID_END)
                     qAppPriv->gestureWidget = 0;
             } else {
                 DWORD dwErr = GetLastError();
                 if (dwErr > 0)
                     qWarning() << "translateGestureEvent: error = " << dwErr;
             }
             result = true;
             break;
         }
 #endif // !defined(Q_WS_WINCE) || defined(QT_WINCE_GESTURES)
 #endif // QT_NO_GESTURES
 #ifndef QT_NO_CURSOR
         case WM_SETCURSOR: {
             QCursor *ovr = QApplication::overrideCursor();
             if (ovr) {
                 SetCursor(ovr->handle());
                 RETURN(TRUE);
             }
             result = false;
             break;
         }
 #endif
         default:
             result = false;                        // event was not processed
             break;
         }
     }
     if (evt_type != QEvent::None) {                // simple event
         QEvent e(evt_type);
         result = qt_sendSpontaneousEvent(widget, &e);
     }
     if (result)
         RETURN(false);
 do_default:
 #ifndef QT_NO_IM
     RETURN(QWinInputContext::DefWindowProc(hwnd,message,wParam,lParam))
 #else
     RETURN(TRUE);
 #endif
 }
qWinProcessConfigRequests()
static void qWinProcessConfigRequests () static
Definition at line 1162 of file qapplication_win.cpp.
Referenced by QGuiEventDispatcherWin32::processEvents().
 {
     if (!configRequests)
         return;
     QWinConfigRequest *r;
     for (;;) {
         if (configRequests->isEmpty())
             break;
         r = configRequests->takeLast();
         QWidget *w = QWidget::find(r->id);
         QRect rect(r->x, r->y, r->w, r->h);
         int req = r->req;
         delete r;
         if ( w ) {                              // widget exists
             if (w->testAttribute(Qt::WA_WState_ConfigPending))
                 return;                         // biting our tail
             if (req == 0)
                 w->move(rect.topLeft());
             else if (req == 1)
                 w->resize(rect.size());
             else
                 w->setGeometry(rect);
         }
     }
     delete configRequests;
     configRequests = 0;
 }
qWinRequestConfig()
void qWinRequestConfig (WId id, int req, int x, int y, int w, int h)
Definition at line 1148 of file qapplication_win.cpp.
Referenced by qt_grab_cursor(), and qt_tablet_cleanup_wce().
 {
     if (!configRequests)                        // create queue
         configRequests = new QList<QWinConfigRequest*>;
     QWinConfigRequest *r = new QWinConfigRequest;
     r->id = id;                                        // create new request
     r->req = req;
     r->x = x;
     r->y = y;
     r->w = w;
     r->h = h;
     configRequests->append(r);                // store request in queue
 }
releaseAutoCapture()
static void releaseAutoCapture () static
Definition at line 2938 of file qapplication_win.cpp.
Referenced by qt_try_modal(), QtWndProc(), setAutoCapture(), QETWidget::translateMouseEvent(), QETWidget::translateTabletEvent(), and QApplication::winMouseButtonUp().
 {
     if (autoCaptureWnd) {
         ReleaseCapture();
         autoCaptureWnd = 0;
     }
 }
resolveAygLibs()
static void resolveAygLibs () static
Definition at line 218 of file qapplication_win.cpp.
Referenced by QtWndProc().
 {
     if (!aygResolved) {
         QSystemLibrary ayglib(QLatin1String("aygshell"));
         ptrRecognizeGesture = (AygRecognizeGesture) ayglib.resolve("SHRecognizeGesture");
         aygResolved = true;
     }
 }
setAutoCapture()
static void setAutoCapture (HWND h) static
Definition at line 2930 of file qapplication_win.cpp.
Referenced by qt_try_modal(), and QETWidget::translateMouseEvent().
 {
     if (autoCaptureWnd)
         releaseAutoCapture();
     autoCaptureWnd = h;
     SetCapture(h);
 }
tabletInit()
static void tabletInit (const quint64 uniqueId, const UINT csr_type, HCTX hTab) static
Definition at line 3502 of file qapplication_win.cpp.
Referenced by QtWndProc().
 {
     Q_ASSERT(ptrWTInfo);
     Q_ASSERT(ptrWTGet);
     Q_ASSERT(!tCursorInfo()->contains(uniqueId));
     /* browse WinTab's many info items to discover pressure handling. */
     AXIS np;
     LOGCONTEXT lc;
     /* get the current context for its device variable. */
     ptrWTGet(hTab, &lc);
     /* get the size of the pressure axis. */
     QTabletDeviceData tdd;
     tdd.llId = uniqueId;
     ptrWTInfo(WTI_DEVICES + lc.lcDevice, DVC_NPRESSURE, &np);
     tdd.minPressure = int(np.axMin);
     tdd.maxPressure = int(np.axMax);
     ptrWTInfo(WTI_DEVICES + lc.lcDevice, DVC_TPRESSURE, &np);
     tdd.minTanPressure = int(np.axMin);
     tdd.maxTanPressure = int(np.axMax);
     LOGCONTEXT lcMine;
     /* get default region */
     ptrWTInfo(WTI_DEFCONTEXT, 0, &lcMine);
     tdd.minX = 0;
     tdd.maxX = int(lcMine.lcInExtX) - int(lcMine.lcInOrgX);
     tdd.minY = 0;
     tdd.maxY = int(lcMine.lcInExtY) - int(lcMine.lcInOrgY);
     tdd.minZ = 0;
     tdd.maxZ = int(lcMine.lcInExtZ) - int(lcMine.lcInOrgZ);
     const uint cursorTypeBitMask = 0x0F06; // bitmask to find the specific cursor type (see Wacom FAQ)
     if (((csr_type & 0x0006) == 0x0002) && ((csr_type & cursorTypeBitMask) != 0x0902)) {
         tdd.currentDevice = QTabletEvent::Stylus;
     } else {
         switch (csr_type & cursorTypeBitMask) {
             case 0x0802:
                 tdd.currentDevice = QTabletEvent::Stylus;
                 break;
             case 0x0902:
                 tdd.currentDevice = QTabletEvent::Airbrush;
                 break;
             case 0x0004:
                 tdd.currentDevice = QTabletEvent::FourDMouse;
                 break;
             case 0x0006:
                 tdd.currentDevice = QTabletEvent::Puck;
                 break;
             case 0x0804:
                 tdd.currentDevice = QTabletEvent::RotationStylus;
                 break;
             default:
                 tdd.currentDevice = QTabletEvent::NoDevice;
         }
     }
     tCursorInfo()->insert(uniqueId, tdd);
 }
tabletUpdateCursor()
static void tabletUpdateCursor (QTabletDeviceData & tdd, const UINT currentCursor) static
Definition at line 3575 of file qapplication_win.cpp.
Referenced by QtWndProc().
 {
     switch (currentCursor % 3) { // %3 for dual track
     case 0:
         tdd.currentPointerType = QTabletEvent::Cursor;
         break;
     case 1:
         tdd.currentPointerType = QTabletEvent::Pen;
         break;
     case 2:
         tdd.currentPointerType = QTabletEvent::Eraser;
         break;
     default:
         tdd.currentPointerType = QTabletEvent::UnknownPointer;
     }
 }
translateButtonState()
static int translateButtonState (int s, int type, int button) static
Definition at line 2985 of file qapplication_win.cpp.
Referenced by QtWndProc(), QETWidget::translateMouseEvent(), and QETWidget::translateWheelEvent().
 {
     Q_UNUSED(type);
     Q_UNUSED(button);
     int bst = 0;
     if (s & MK_LBUTTON)
         bst |= Qt::LeftButton;
     if (s & MK_MBUTTON)
         bst |= Qt::MidButton;
     if (s & MK_RBUTTON)
         bst |= Qt::RightButton;
     if (s & MK_SHIFT)
         bst |= Qt::ShiftModifier;
     if (s & MK_CONTROL)
         bst |= Qt::ControlModifier;
     if (s & MK_XBUTTON1)
         bst |= Qt::XButton1;
     if (s & MK_XBUTTON2)
         bst |= Qt::XButton2;
     if (GetKeyState(VK_MENU) < 0)
         bst |= Qt::AltModifier;
     if ((GetKeyState(VK_LWIN) < 0) ||
          (GetKeyState(VK_RWIN) < 0))
         bst |= Qt::MetaModifier;
     return bst;
 }
unregWinClasses()
static void unregWinClasses () static
Definition at line 1123 of file qapplication_win.cpp.
Referenced by qt_cleanup().
 {
     WinClassNameHash *hash = winclassNames();
     QHash<QString, int>::ConstIterator it = hash->constBegin();
     while (it != hash->constEnd()) {
         UnregisterClass((wchar_t*)it.key().utf16(), qWinAppInst());
         ++it;
     }
     hash->clear();
 }
Variable Documentation
app_do_modal
bool app_do_modal = false static
Definition at line 441 of file qapplication_win.cpp.
Referenced by QtWndProc().
appNoGrab
bool appNoGrab = false static
Definition at line 438 of file qapplication_win.cpp.
Referenced by qt_init(), and qt_nograb().
autoCaptureWnd
HWND autoCaptureWnd = 0 static
Definition at line 450 of file qapplication_win.cpp.
Referenced by QtWndProc(), and QETWidget::translateTabletEvent().
aygResolved
bool aygResolved = false static
Definition at line 217 of file qapplication_win.cpp.
Referenced by resolveAygLibs().
configRequests
QList<QWinConfigRequest*>* configRequests = 0 static
Definition at line 1146 of file qapplication_win.cpp.
Referenced by qWinProcessConfigRequests().
currentTabletPointer
QTabletDeviceData currentTabletPointer
Definition at line 286 of file qapplication_win.cpp.
curWin
HWND curWin = 0 static
Definition at line 422 of file qapplication_win.cpp.
Referenced by qt_qpa_set_cursor(), QtWndProc(), and QETWidget::translateMouseEvent().
displayDC
HDC displayDC = 0 static
Definition at line 423 of file qapplication_win.cpp.
Referenced by qt_win_display_dc(), qt_wince_GetDIBits(), and QtHDC::QtHDC().
effect_override
bool effect_override = false static
Definition at line 4081 of file qapplication_win.cpp.
imeParentWnd
HWND imeParentWnd = 0 static
Definition at line 451 of file qapplication_win.cpp.
inLoop
bool inLoop = false static
Definition at line 1457 of file qapplication_win.cpp.
inputcharset
int inputcharset = CP_ACP static
Definition at line 1458 of file qapplication_win.cpp.
localPacketBuf
PACKET localPacketBuf[QT_TABLET_NPACKETQSIZE] static
Definition at line 260 of file qapplication_win.cpp.
Referenced by QETWidget::markFrameStrutDirty(), and QtWndProc().
mouseTbl
const ushort mouseTbl[] static
Definition at line 2953 of file qapplication_win.cpp.
oldHiResTabletGlobalPosF
QPointF oldHiResTabletGlobalPosF
Definition at line 263 of file qapplication_win.cpp.
Referenced by QETWidget::translateTabletEvent().
popupButtonFocus
QPointer<QWidget> popupButtonFocus static
Definition at line 444 of file qapplication_win.cpp.
Referenced by QETWidget::translateMouseEvent().
ptrRecognizeGesture
AygRecognizeGesture ptrRecognizeGesture = 0 static
Definition at line 216 of file qapplication_win.cpp.
Referenced by QtWndProc(), and resolveAygLibs().
ptrSetProcessDPIAware
PtrSetProcessDPIAware ptrSetProcessDPIAware = 0 static
Definition at line 756 of file qapplication_win.cpp.
Referenced by qt_init().
ptrUpdateLayeredWindow
PtrUpdateLayeredWindow ptrUpdateLayeredWindow = 0
Definition at line 757 of file qapplication_win.cpp.
Referenced by qt_grab_cursor().
ptrUpdateLayeredWindowIndirect
PtrUpdateLayeredWindowIndirect ptrUpdateLayeredWindowIndirect = 0
Definition at line 758 of file qapplication_win.cpp.
Referenced by QRasterWindowSurface::flush(), and qt_grab_cursor().
ptrWTEnable
PtrWTEnable ptrWTEnable = 0 static
Definition at line 255 of file qapplication_win.cpp.
Referenced by initWinTabFunctions(), and QtWndProc().
ptrWTGet
PtrWTGet ptrWTGet = 0 static
Definition at line 258 of file qapplication_win.cpp.
Referenced by initWinTabFunctions(), and tabletInit().
ptrWTInfo
PtrWTInfo ptrWTInfo = 0 static
Definition at line 254 of file qapplication_win.cpp.
Referenced by initWinTabFunctions(), qt_tablet_init_wce(), QtWndProc(), and tabletInit().
ptrWTOverlap
PtrWTOverlap ptrWTOverlap = 0 static
Definition at line 256 of file qapplication_win.cpp.
Referenced by initWinTabFunctions(), and QtWndProc().
ptrWTPacketsGet
PtrWTPacketsGet ptrWTPacketsGet = 0 static
Definition at line 257 of file qapplication_win.cpp.
Referenced by initWinTabFunctions(), and QtWndProc().
qt_app_has_font
bool qt_app_has_font
Referenced by QETWidget::forceUpdate().
qt_button_down
QWidget* qt_button_down = 0
Definition at line 447 of file qapplication_win.cpp.
Referenced by QETWidget::translateTabletEvent().
qt_cleartype_enabled
Q_GUI_EXPORT bool qt_cleartype_enabled
Definition at line 241 of file qapplication_win.cpp.
Referenced by QGL2PaintEngineEx::begin(), QRasterPaintEngine::begin(), QFontEngineWin::getSfntTableData(), isPowerOfTwo(), and qt_win_read_cleartype_settings().
qt_desktopWidget
QDesktopWidget* qt_desktopWidget
Definition at line 560 of file qapplication.cpp.
qt_fontsmoothing_gamma
Q_GUI_EXPORT qreal qt_fontsmoothing_gamma
Definition at line 240 of file qapplication_win.cpp.
Referenced by fontSmoothingApproximately(), qt_build_pow_tables(), and qt_win_read_cleartype_settings().
qt_is_gui_used
bool qt_is_gui_used
Definition at line 492 of file qapplication.cpp.
Referenced by QETWidget::translateTabletEvent().
qt_last_mouse_receiver
QPointer<QWidget> qt_last_mouse_receiver = 0
Definition at line 448 of file qapplication_win.cpp.
Referenced by QtWndProc(), and QETWidget::translateMouseEvent().
qt_modal_stack
QWidgetList* qt_modal_stack
Definition at line 564 of file qapplication.cpp.
Referenced by QtWndProc().
qt_session_manager_self
QSessionManager* qt_session_manager_self
Definition at line 5053 of file qapplication.cpp.
qt_tablet_context
HCTX qt_tablet_context
Definition at line 261 of file qapplication_win.cpp.
Referenced by qt_tablet_cleanup(), qt_tablet_cleanup_wce(), qt_tablet_init(), qt_tablet_init_wce(), and QtWndProc().
qt_tablet_tilt_support
bool qt_tablet_tilt_support
Definition at line 262 of file qapplication_win.cpp.
Referenced by qt_tablet_init(), qt_tablet_init_wce(), and QETWidget::translateTabletEvent().
qt_tabletChokeMouse
bool qt_tabletChokeMouse
Definition at line 526 of file qapplication.cpp.
Referenced by QtWndProc().
qt_use_rtl_extensions
bool qt_use_rtl_extensions = false
Definition at line 266 of file qapplication_win.cpp.
qt_win_ignoreNextMouseReleaseEvent
Q_GUI_EXPORT bool qt_win_ignoreNextMouseReleaseEvent = false
Definition at line 434 of file qapplication_win.cpp.
Referenced by QAxClientSite::qt_metacall().
qt_win_owndc_required
Q_GUI_EXPORT bool qt_win_owndc_required
Definition at line 242 of file qapplication_win.cpp.
Referenced by QGLGraphicsSystem::QGLGraphicsSystem(), qt_init(), and qt_reg_winclass().
replayPopupMouseEvent
bool replayPopupMouseEvent = false static
Definition at line 431 of file qapplication_win.cpp.
sm_blockUserInput
bool sm_blockUserInput = false static
Definition at line 426 of file qapplication_win.cpp.
sm_cancel
bool sm_cancel static
Definition at line 429 of file qapplication_win.cpp.
sm_smActive
bool sm_smActive = false static
Definition at line 427 of file qapplication_win.cpp.