Qt 4.8: /src/corelib/arch/qatomic_powerpc.h File Reference
qatomic_powerpc.h File Reference
Macros
#define Q_ATOMIC_INT_FETCH_AND_ADD_IS_ALWAYS_NATIVE
#define Q_ATOMIC_INT_FETCH_AND_STORE_IS_ALWAYS_NATIVE
#define Q_ATOMIC_INT_REFERENCE_COUNTING_IS_ALWAYS_NATIVE
#define Q_ATOMIC_INT_TEST_AND_SET_IS_ALWAYS_NATIVE
#define Q_ATOMIC_POINTER_FETCH_AND_ADD_IS_ALWAYS_NATIVE
#define Q_ATOMIC_POINTER_FETCH_AND_STORE_IS_ALWAYS_NATIVE
#define Q_ATOMIC_POINTER_TEST_AND_SET_IS_ALWAYS_NATIVE
Functions
int q_atomic_decrement (volatile int *)
int q_atomic_fetch_and_add_acquire_int (volatile int *ptr, int valueToAdd)
void * q_atomic_fetch_and_add_acquire_ptr (volatile void *ptr, qptrdiff valueToAdd)
int q_atomic_fetch_and_add_int (volatile int *ptr, int valueToAdd)
void * q_atomic_fetch_and_add_ptr (volatile void *ptr, qptrdiff valueToAdd)
int q_atomic_fetch_and_add_release_int (volatile int *ptr, int valueToAdd)
void * q_atomic_fetch_and_add_release_ptr (volatile void *ptr, qptrdiff valueToAdd)
int q_atomic_fetch_and_store_acquire_int (volatile int *ptr, int newValue)
int q_atomic_fetch_and_store_acquire_ptr (volatile void *ptr, void *newValue)
int q_atomic_fetch_and_store_release_int (volatile int *ptr, int newValue)
int q_atomic_fetch_and_store_release_ptr (volatile void *ptr, void *newValue)
int q_atomic_increment (volatile int *)
int q_atomic_set_int (volatile int *, int)
void * q_atomic_set_ptr (volatile void *, void *)
int q_atomic_test_and_set_acquire_int (volatile int *ptr, int expectedValue, int newValue)
int q_atomic_test_and_set_acquire_ptr (volatile void *ptr, void *expectedValue, void *newValue)
int q_atomic_test_and_set_int (volatile int *ptr, int expectedValue, int newValue)
int q_atomic_test_and_set_ptr (volatile void *ptr, void *expectedValue, void *newValue)
int q_atomic_test_and_set_release_int (volatile int *ptr, int expectedValue, int newValue)
int q_atomic_test_and_set_release_ptr (volatile void *ptr, void *expectedValue, void *newValue)
Macro Definition Documentation
Q_ATOMIC_INT_FETCH_AND_ADD_IS_ALWAYS_NATIVE
#define Q_ATOMIC_INT_FETCH_AND_ADD_IS_ALWAYS_NATIVE
Definition at line 70 of file qatomic_powerpc.h.
Q_ATOMIC_INT_FETCH_AND_STORE_IS_ALWAYS_NATIVE
#define Q_ATOMIC_INT_FETCH_AND_STORE_IS_ALWAYS_NATIVE
Definition at line 63 of file qatomic_powerpc.h.
Q_ATOMIC_INT_REFERENCE_COUNTING_IS_ALWAYS_NATIVE
#define Q_ATOMIC_INT_REFERENCE_COUNTING_IS_ALWAYS_NATIVE
Definition at line 49 of file qatomic_powerpc.h.
Q_ATOMIC_INT_TEST_AND_SET_IS_ALWAYS_NATIVE
#define Q_ATOMIC_INT_TEST_AND_SET_IS_ALWAYS_NATIVE
Definition at line 56 of file qatomic_powerpc.h.
Q_ATOMIC_POINTER_FETCH_AND_ADD_IS_ALWAYS_NATIVE
#define Q_ATOMIC_POINTER_FETCH_AND_ADD_IS_ALWAYS_NATIVE
Definition at line 95 of file qatomic_powerpc.h.
Q_ATOMIC_POINTER_FETCH_AND_STORE_IS_ALWAYS_NATIVE
#define Q_ATOMIC_POINTER_FETCH_AND_STORE_IS_ALWAYS_NATIVE
Definition at line 86 of file qatomic_powerpc.h.
Q_ATOMIC_POINTER_TEST_AND_SET_IS_ALWAYS_NATIVE
#define Q_ATOMIC_POINTER_TEST_AND_SET_IS_ALWAYS_NATIVE
Definition at line 77 of file qatomic_powerpc.h.
Function Documentation
q_atomic_decrement()
int q_atomic_decrement (volatile int *)
q_atomic_fetch_and_add_acquire_int()
int q_atomic_fetch_and_add_acquire_int (volatile int * ptr, int valueToAdd)
q_atomic_fetch_and_add_acquire_ptr()
void* q_atomic_fetch_and_add_acquire_ptr (volatile void * ptr, qptrdiff valueToAdd)
Referenced by QBasicAtomicPointer< QBrushData >::fetchAndAddAcquire().
q_atomic_fetch_and_add_int()
int q_atomic_fetch_and_add_int (volatile int * ptr, int valueToAdd)
q_atomic_fetch_and_add_ptr()
void* q_atomic_fetch_and_add_ptr (volatile void * ptr, qptrdiff valueToAdd)
q_atomic_fetch_and_add_release_int()
int q_atomic_fetch_and_add_release_int (volatile int * ptr, int valueToAdd)
q_atomic_fetch_and_add_release_ptr()
void* q_atomic_fetch_and_add_release_ptr (volatile void * ptr, qptrdiff valueToAdd)
Referenced by QBasicAtomicPointer< QBrushData >::fetchAndAddRelease().
q_atomic_fetch_and_store_acquire_int()
int q_atomic_fetch_and_store_acquire_int (volatile int * ptr, int newValue)
Referenced by QBasicAtomicInt::fetchAndStoreAcquire().
q_atomic_fetch_and_store_acquire_ptr()
int q_atomic_fetch_and_store_acquire_ptr (volatile void * ptr, void * newValue)
Referenced by QBasicAtomicPointer< QBrushData >::fetchAndStoreAcquire().
q_atomic_fetch_and_store_release_int()
int q_atomic_fetch_and_store_release_int (volatile int * ptr, int newValue)
Referenced by QBasicAtomicInt::fetchAndStoreRelease().
q_atomic_fetch_and_store_release_ptr()
int q_atomic_fetch_and_store_release_ptr (volatile void * ptr, void * newValue)
Referenced by QBasicAtomicPointer< QBrushData >::fetchAndStoreRelease().
q_atomic_increment()
int q_atomic_increment (volatile int *)
q_atomic_set_int()
int q_atomic_set_int (volatile int * , int)
q_atomic_set_ptr()
void* q_atomic_set_ptr (volatile void * , void *)
q_atomic_test_and_set_acquire_int()
int q_atomic_test_and_set_acquire_int (volatile int * ptr, int expectedValue, int newValue)
q_atomic_test_and_set_acquire_ptr()
int q_atomic_test_and_set_acquire_ptr (volatile void * ptr, void * expectedValue, void * newValue)
q_atomic_test_and_set_int()
int q_atomic_test_and_set_int (volatile int * ptr, int expectedValue, int newValue)
q_atomic_test_and_set_ptr()
int q_atomic_test_and_set_ptr (volatile void * ptr, void * expectedValue, void * newValue)
q_atomic_test_and_set_release_int()
int q_atomic_test_and_set_release_int (volatile int * ptr, int expectedValue, int newValue)
q_atomic_test_and_set_release_ptr()
int q_atomic_test_and_set_release_ptr (volatile void * ptr, void * expectedValue, void * newValue)