Qt 4.8: /src/corelib/arch/qatomic_alpha.h File Reference
qatomic_alpha.h File Reference
Macros
#define Q_ATOMIC_INT_FETCH_AND_ADD_IS_ALWAYS_NATIVE
#define Q_ATOMIC_INT_FETCH_AND_STORE_IS_ALWAYS_NATIVE
#define Q_ATOMIC_INT_REFERENCE_COUNTING_IS_ALWAYS_NATIVE
#define Q_ATOMIC_INT_TEST_AND_SET_IS_ALWAYS_NATIVE
#define Q_ATOMIC_POINTER_FETCH_AND_ADD_IS_ALWAYS_NATIVE
#define Q_ATOMIC_POINTER_FETCH_AND_STORE_IS_ALWAYS_NATIVE
#define Q_ATOMIC_POINTER_TEST_AND_SET_IS_ALWAYS_NATIVE
Functions
Q_CORE_EXPORT int q_atomic_decrement (volatile int *ptr)
Q_CORE_EXPORT int q_atomic_fetch_and_add_acquire_int (volatile int *ptr, int value)
Q_CORE_EXPORT int q_atomic_fetch_and_add_int (volatile int *ptr, int value)
Q_CORE_EXPORT int q_atomic_fetch_and_add_release_int (volatile int *ptr, int value)
Q_CORE_EXPORT int q_atomic_increment (volatile int *ptr)
Q_CORE_EXPORT int q_atomic_set_int (volatile int *ptr, int newval)
Q_CORE_EXPORT void * q_atomic_set_ptr (volatile void *ptr, void *newval)
Q_CORE_EXPORT int q_atomic_test_and_set_acquire_int (volatile int *ptr, int expected, int newval)
Q_CORE_EXPORT int q_atomic_test_and_set_int (volatile int *ptr, int expected, int newval)
Q_CORE_EXPORT int q_atomic_test_and_set_ptr (volatile void *ptr, void *expected, void *newval)
Q_CORE_EXPORT int q_atomic_test_and_set_release_int (volatile int *ptr, int expected, int newval)
Macro Definition Documentation
Q_ATOMIC_INT_FETCH_AND_ADD_IS_ALWAYS_NATIVE
#define Q_ATOMIC_INT_FETCH_AND_ADD_IS_ALWAYS_NATIVE
Definition at line 70 of file qatomic_alpha.h.
Q_ATOMIC_INT_FETCH_AND_STORE_IS_ALWAYS_NATIVE
#define Q_ATOMIC_INT_FETCH_AND_STORE_IS_ALWAYS_NATIVE
Definition at line 63 of file qatomic_alpha.h.
Q_ATOMIC_INT_REFERENCE_COUNTING_IS_ALWAYS_NATIVE
#define Q_ATOMIC_INT_REFERENCE_COUNTING_IS_ALWAYS_NATIVE
Definition at line 49 of file qatomic_alpha.h.
Q_ATOMIC_INT_TEST_AND_SET_IS_ALWAYS_NATIVE
#define Q_ATOMIC_INT_TEST_AND_SET_IS_ALWAYS_NATIVE
Definition at line 56 of file qatomic_alpha.h.
Q_ATOMIC_POINTER_FETCH_AND_ADD_IS_ALWAYS_NATIVE
#define Q_ATOMIC_POINTER_FETCH_AND_ADD_IS_ALWAYS_NATIVE
Definition at line 95 of file qatomic_alpha.h.
Q_ATOMIC_POINTER_FETCH_AND_STORE_IS_ALWAYS_NATIVE
#define Q_ATOMIC_POINTER_FETCH_AND_STORE_IS_ALWAYS_NATIVE
Definition at line 86 of file qatomic_alpha.h.
Q_ATOMIC_POINTER_TEST_AND_SET_IS_ALWAYS_NATIVE
#define Q_ATOMIC_POINTER_TEST_AND_SET_IS_ALWAYS_NATIVE
Definition at line 77 of file qatomic_alpha.h.
Function Documentation
q_atomic_decrement()
Q_CORE_EXPORT int q_atomic_decrement (volatile int * ptr)
Referenced by QBasicAtomicInt::deref(), and QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree().
q_atomic_fetch_and_add_acquire_int()
Q_CORE_EXPORT int q_atomic_fetch_and_add_acquire_int (volatile int * ptr, int value)
Referenced by QBasicAtomicInt::fetchAndAddAcquire(), and QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree().
q_atomic_fetch_and_add_int()
Q_CORE_EXPORT int q_atomic_fetch_and_add_int (volatile int * ptr, int value)
Referenced by QBasicAtomicInt::fetchAndAddRelaxed(), and QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree().
q_atomic_fetch_and_add_release_int()
Q_CORE_EXPORT int q_atomic_fetch_and_add_release_int (volatile int * ptr, int value)
Referenced by QBasicAtomicInt::fetchAndAddRelease(), and QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree().
q_atomic_increment()
Q_CORE_EXPORT int q_atomic_increment (volatile int * ptr)
Referenced by QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), and QBasicAtomicInt::ref().
q_atomic_set_int()
Q_CORE_EXPORT int q_atomic_set_int (volatile int * ptr, int newval)
Referenced by QBasicAtomicInt::fetchAndStoreRelaxed(), and QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree().
q_atomic_set_ptr()
Q_CORE_EXPORT void* q_atomic_set_ptr (volatile void * ptr, void * newval)
Referenced by QBasicAtomicPointer< QBrushData >::fetchAndStoreRelaxed(), and QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree().
q_atomic_test_and_set_acquire_int()
Q_CORE_EXPORT int q_atomic_test_and_set_acquire_int (volatile int * ptr, int expected, int newval)
Referenced by QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), and QBasicAtomicInt::testAndSetAcquire().
q_atomic_test_and_set_int()
Q_CORE_EXPORT int q_atomic_test_and_set_int (volatile int * ptr, int expected, int newval)
Referenced by QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), and QBasicAtomicInt::testAndSetRelaxed().
q_atomic_test_and_set_ptr()
Q_CORE_EXPORT int q_atomic_test_and_set_ptr (volatile void * ptr, void * expected, void * newval)
Referenced by QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), and QBasicAtomicPointer< QBrushData >::testAndSetRelaxed().
q_atomic_test_and_set_release_int()
Q_CORE_EXPORT int q_atomic_test_and_set_release_int (volatile int * ptr, int expected, int newval)
Referenced by QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), and QBasicAtomicInt::testAndSetRelease().