Qt 4.8: /src/xmlpatterns/data/qatomicmathematicians.cpp File Reference
qatomicmathematicians.cpp File Reference
#include <math.h>
#include <qnumeric.h>
#include "qabstractdatetime_p.h"
#include "qabstractduration_p.h"
#include "qabstractfloat_p.h"
#include "qdaytimeduration_p.h"
#include "qdecimal_p.h"
#include "qinteger_p.h"
#include "qpatternistlocale_p.h"
#include "qatomicmathematicians_p.h"
Functions
static QString divZeroInvalid ()
static QString idivZeroInvalid ()
static QString modZeroInvalid ()
Function Documentation
divZeroInvalid()
static QString divZeroInvalid () inline static
Definition at line 70 of file qatomicmathematicians.cpp.
Referenced by QPatternist::DecimalMathematician::calculate(), and QPatternist::IntegerMathematician::calculate().
 {
     return QtXmlPatterns::tr("Division (%1) by zero (%2) is undefined.")
              .arg(formatKeyword("div"))
              .arg(formatData("0"));
 }
idivZeroInvalid()
static QString idivZeroInvalid () inline static
Definition at line 63 of file qatomicmathematicians.cpp.
Referenced by QPatternist::DecimalMathematician::calculate(), and QPatternist::IntegerMathematician::calculate().
 {
     return QtXmlPatterns::tr("Integer division (%1) by zero (%2) is undefined.")
              .arg(formatKeyword("idiv"))
              .arg(formatData("0"));
 }
modZeroInvalid()
static QString modZeroInvalid () inline static
Definition at line 77 of file qatomicmathematicians.cpp.
Referenced by QPatternist::DecimalMathematician::calculate(), and QPatternist::IntegerMathematician::calculate().
 {
     return QtXmlPatterns::tr("Modulus division (%1) by zero (%2) is undefined.")
              .arg(formatKeyword("mod"))
              .arg(formatData("0"));
 }