Qt 4.8: /src/corelib/thread/qatomic.h File Reference
qatomic.h File Reference
#include <QtCore/qglobal.h>
#include <QtCore/qbasicatomic.h>
Classes
class QAtomicInt
The QAtomicInt class provides platform-independent atomic operations on integers.
class QAtomicPointer< T >
The QAtomicPointer class is a template class that provides platform-independent atomic operations on pointers.
Functions
template<typename T >
void qAtomicAssign (T *&d, T *x)
This is a helper for the assignment operators of implicitly shared classes.
template<typename T >
void qAtomicDetach (T *&d)
This is a helper for the detach method of implicitly shared classes.
Function Documentation
qAtomicAssign()
template<typename T > void qAtomicAssign (T *& d, T * x) inline
This is a helper for the assignment operators of implicitly shared classes.
Your assignment operator should look like this:
Definition at line 195 of file qatomic.h.
Referenced by QColormap::hPal(), QSqlRecord::operator=(), QSqlField::operator=(), QSqlQuery::operator=(), QColormap::operator=(), QDBusMessage::operator=(), QPen::operator=(), QDBusArgument::operator=(), QSqlDatabase::operator=(), QUrl::operator=(), QKeySequence::operator=(), and qt_conv16ToRgb().
 {
     if (d == x)
         return;
     x->ref.ref();
     if (!d->ref.deref())
         delete d;
     d = x;
 }
qAtomicDetach()
template<typename T > void qAtomicDetach (T *& d) inline
This is a helper for the detach method of implicitly shared classes.
Your private class needs a copy constructor which copies the members and sets the refcount to 1. After that, your detach function should look like this:
Definition at line 214 of file qatomic.h.
Referenced by QSqlField::detach(), QSqlRecord::detach(), QScopedSharedPointer< QScriptDebuggerConsoleCommandGroupDataPrivate >::detach(), operator>>(), QUrl::resolved(), and QKeySequence::setKey().
 {
     if (d->ref == 1)
         return;
     T *x = d;
     d = new T(*d);
     if (!x->ref.deref())
         delete x;
 }