Qt 4.8: /src/network/kernel/qauthenticator.cpp File Reference
qauthenticator.cpp File Reference
#include <qauthenticator.h>
#include <qauthenticator_p.h>
#include <qdebug.h>
#include <qhash.h>
#include <qbytearray.h>
#include <qcryptographichash.h>
#include <qhttp.h>
#include <qiodevice.h>
#include <qdatastream.h>
#include <qendian.h>
#include <qstring.h>
#include <qdatetime.h>
Classes
class QNtlmBuffer
class QNtlmPhase1Block
class QNtlmPhase1BlockBase
class QNtlmPhase2Block
class QNtlmPhase2BlockBase
class QNtlmPhase3Block
class QNtlmPhase3BlockBase
Macros
#define AVTIMESTAMP 7
#define NTLMSSP_NEGOTIATE_128 0x20000000
#define NTLMSSP_NEGOTIATE_56 0x80000000
#define NTLMSSP_NEGOTIATE_ALWAYS_SIGN 0x00008000
#define NTLMSSP_NEGOTIATE_DATAGRAM 0x00000040
#define NTLMSSP_NEGOTIATE_DOMAIN_SUPPLIED 0x00001000
#define NTLMSSP_NEGOTIATE_KEY_EXCHANGE 0x40000000
#define NTLMSSP_NEGOTIATE_LM_KEY 0x00000080
#define NTLMSSP_NEGOTIATE_LOCAL_CALL 0x00004000
#define NTLMSSP_NEGOTIATE_NTLM 0x00000200
#define NTLMSSP_NEGOTIATE_NTLM2 0x00080000
#define NTLMSSP_NEGOTIATE_OEM 0x00000002
#define NTLMSSP_NEGOTIATE_SEAL 0x00000020
#define NTLMSSP_NEGOTIATE_SIGN 0x00000010
#define NTLMSSP_NEGOTIATE_TARGET_INFO 0x00800000
#define NTLMSSP_NEGOTIATE_UNICODE 0x00000001
#define NTLMSSP_NEGOTIATE_WORKSTATION_SUPPLIED 0x00002000
#define NTLMSSP_REQUEST_TARGET 0x00000004
#define NTLMSSP_TARGET_TYPE_DOMAIN 0x00010000
#define NTLMSSP_TARGET_TYPE_SERVER 0x00020000
#define NTLMSSP_TARGET_TYPE_SHARE 0x00040000
Functions
static QByteArray clientChallenge (const QAuthenticatorPrivate *ctx)
static QByteArray digestMd5ResponseHelper (const QByteArray &alg, const QByteArray &userName, const QByteArray &realm, const QByteArray &password, const QByteArray &nonce, const QByteArray &nonceCount, const QByteArray &cNonce, const QByteArray &qop, const QByteArray &method, const QByteArray &digestUri, const QByteArray &hEntity)
static QDataStream & operator<< (QDataStream &s, const QNtlmBuffer &b)
static QDataStream & operator<< (QDataStream &s, const QNtlmPhase1Block &b)
static QDataStream & operator<< (QDataStream &s, const QNtlmPhase3Block &b)
static QDataStream & operator>> (QDataStream &s, QNtlmBuffer &b)
static QByteArray qCreatev2Hash (const QAuthenticatorPrivate *ctx, QNtlmPhase3Block *phase3)
QByteArray qEncodeHmacMd5 (QByteArray &key, const QByteArray &message)
static QByteArray qEncodeLmv2Response (const QAuthenticatorPrivate *ctx, const QNtlmPhase2Block &ch, QNtlmPhase3Block *phase3)
static int qEncodeNtlmBuffer (QNtlmBuffer &buf, int offset, const QByteArray &s)
static int qEncodeNtlmString (QNtlmBuffer &buf, int offset, const QString &s, bool unicode)
static QByteArray qEncodeNtlmv2Response (const QAuthenticatorPrivate *ctx, const QNtlmPhase2Block &ch, QNtlmPhase3Block *phase3)
static QByteArray qExtractServerTime (const QByteArray &targetInfoBuff)
static bool qNtlmDecodePhase2 (const QByteArray &data, QNtlmPhase2Block &ch)
static QByteArray qNtlmPhase1 ()
static QByteArray qNtlmPhase3 (QAuthenticatorPrivate *ctx, const QByteArray &phase2data)
static void qStreamNtlmBuffer (QDataStream &ds, const QByteArray &s)
static void qStreamNtlmString (QDataStream &ds, const QString &s, bool unicode)
static QByteArray qStringAsUcs2Le (const QString &src)
static QString qStringFromUcs2Le (const QByteArray &src)
Variables
const int blockSize = 64
const quint8 hirespversion = 1
const int nDigestLen = 16
const quint8 respversion = 1
Macro Definition Documentation
AVTIMESTAMP
#define AVTIMESTAMP 7
Definition at line 822 of file qauthenticator.cpp.
Referenced by qExtractServerTime().
NTLMSSP_NEGOTIATE_128
#define NTLMSSP_NEGOTIATE_128 0x20000000
Definition at line 804 of file qauthenticator.cpp.
NTLMSSP_NEGOTIATE_56
#define NTLMSSP_NEGOTIATE_56 0x80000000
Definition at line 817 of file qauthenticator.cpp.
NTLMSSP_NEGOTIATE_ALWAYS_SIGN
#define NTLMSSP_NEGOTIATE_ALWAYS_SIGN 0x00008000
Definition at line 765 of file qauthenticator.cpp.
NTLMSSP_NEGOTIATE_DATAGRAM
#define NTLMSSP_NEGOTIATE_DATAGRAM 0x00000040
Definition at line 726 of file qauthenticator.cpp.
NTLMSSP_NEGOTIATE_DOMAIN_SUPPLIED
#define NTLMSSP_NEGOTIATE_DOMAIN_SUPPLIED 0x00001000
Definition at line 745 of file qauthenticator.cpp.
NTLMSSP_NEGOTIATE_KEY_EXCHANGE
#define NTLMSSP_NEGOTIATE_KEY_EXCHANGE 0x40000000
Definition at line 812 of file qauthenticator.cpp.
NTLMSSP_NEGOTIATE_LM_KEY
#define NTLMSSP_NEGOTIATE_LM_KEY 0x00000080
Definition at line 732 of file qauthenticator.cpp.
NTLMSSP_NEGOTIATE_LOCAL_CALL
#define NTLMSSP_NEGOTIATE_LOCAL_CALL 0x00004000
Definition at line 759 of file qauthenticator.cpp.
NTLMSSP_NEGOTIATE_NTLM
#define NTLMSSP_NEGOTIATE_NTLM 0x00000200
Definition at line 737 of file qauthenticator.cpp.
Referenced by QNtlmPhase1Block::QNtlmPhase1Block(), qNtlmPhase3(), and QNtlmPhase3Block::QNtlmPhase3Block().
NTLMSSP_NEGOTIATE_NTLM2
#define NTLMSSP_NEGOTIATE_NTLM2 0x00080000
Definition at line 792 of file qauthenticator.cpp.
NTLMSSP_NEGOTIATE_OEM
#define NTLMSSP_NEGOTIATE_OEM 0x00000002
Definition at line 703 of file qauthenticator.cpp.
Referenced by qNtlmPhase3().
NTLMSSP_NEGOTIATE_SEAL
#define NTLMSSP_NEGOTIATE_SEAL 0x00000020
Definition at line 721 of file qauthenticator.cpp.
NTLMSSP_NEGOTIATE_SIGN
#define NTLMSSP_NEGOTIATE_SIGN 0x00000010
Definition at line 715 of file qauthenticator.cpp.
NTLMSSP_NEGOTIATE_TARGET_INFO
#define NTLMSSP_NEGOTIATE_TARGET_INFO 0x00800000
Definition at line 799 of file qauthenticator.cpp.
Referenced by QNtlmPhase3Block::QNtlmPhase3Block().
NTLMSSP_NEGOTIATE_UNICODE
#define NTLMSSP_NEGOTIATE_UNICODE 0x00000001
Definition at line 698 of file qauthenticator.cpp.
Referenced by operator<<(), QNtlmPhase1Block::QNtlmPhase1Block(), qNtlmPhase3(), and QNtlmPhase3Block::QNtlmPhase3Block().
NTLMSSP_NEGOTIATE_WORKSTATION_SUPPLIED
#define NTLMSSP_NEGOTIATE_WORKSTATION_SUPPLIED 0x00002000
Definition at line 752 of file qauthenticator.cpp.
NTLMSSP_REQUEST_TARGET
#define NTLMSSP_REQUEST_TARGET 0x00000004
Definition at line 709 of file qauthenticator.cpp.
Referenced by QNtlmPhase1Block::QNtlmPhase1Block().
NTLMSSP_TARGET_TYPE_DOMAIN
#define NTLMSSP_TARGET_TYPE_DOMAIN 0x00010000
Definition at line 771 of file qauthenticator.cpp.
NTLMSSP_TARGET_TYPE_SERVER
#define NTLMSSP_TARGET_TYPE_SERVER 0x00020000
Definition at line 777 of file qauthenticator.cpp.
NTLMSSP_TARGET_TYPE_SHARE
#define NTLMSSP_TARGET_TYPE_SHARE 0x00040000
Definition at line 784 of file qauthenticator.cpp.
Function Documentation
clientChallenge()
static QByteArray clientChallenge (const QAuthenticatorPrivate * ctx) static
Definition at line 1222 of file qauthenticator.cpp.
Referenced by qEncodeLmv2Response(), and qEncodeNtlmv2Response().
 {
     Q_ASSERT(ctx->cnonce.size() >= 8);
     QByteArray clientCh = ctx->cnonce.right(8);
     return clientCh;
 }
digestMd5ResponseHelper()
static QByteArray digestMd5ResponseHelper (const QByteArray & alg, const QByteArray & userName, const QByteArray & realm, const QByteArray & password, const QByteArray & nonce, const QByteArray & nonceCount, const QByteArray & cNonce, const QByteArray & qop, const QByteArray & method, const QByteArray & digestUri, const QByteArray & hEntity) static
Definition at line 577 of file qauthenticator.cpp.
Referenced by QAuthenticatorPrivate::digestMd5Response().
 {
     QCryptographicHash hash(QCryptographicHash::Md5);
     hash.addData(userName);
     hash.addData(":", 1);
     hash.addData(realm);
     hash.addData(":", 1);
     hash.addData(password);
     QByteArray ha1 = hash.result();
     if (alg.toLower() == "md5-sess") {
         hash.reset();
         // RFC 2617 contains an error, it was:
         // hash.addData(ha1);
         // but according to the errata page at http://www.rfc-editor.org/errata_list.php, ID 1649, it
         // must be the following line:
         hash.addData(ha1.toHex());
         hash.addData(":", 1);
         hash.addData(nonce);
         hash.addData(":", 1);
         hash.addData(cNonce);
         ha1 = hash.result();
     };
     ha1 = ha1.toHex();
     // calculate H(A2)
     hash.reset();
     hash.addData(method);
     hash.addData(":", 1);
     hash.addData(digestUri);
     if (qop.toLower() == "auth-int") {
         hash.addData(":", 1);
         hash.addData(hEntity);
     }
     QByteArray ha2hex = hash.result().toHex();
     // calculate response
     hash.reset();
     hash.addData(ha1);
     hash.addData(":", 1);
     hash.addData(nonce);
     hash.addData(":", 1);
     if (!qop.isNull()) {
         hash.addData(nonceCount);
         hash.addData(":", 1);
         hash.addData(cNonce);
         hash.addData(":", 1);
         hash.addData(qop);
         hash.addData(":", 1);
     }
     hash.addData(ha2hex);
     return hash.result().toHex();
 }
operator<<() [1/3]
static QDataStream& operator<< (QDataStream & s, const QNtlmBuffer & b) static
Definition at line 938 of file qauthenticator.cpp.
 {
     s << b.len << b.maxLen << b.offset;
     return s;
 }
operator<<() [2/3]
static QDataStream& operator<< (QDataStream & s, const QNtlmPhase1Block & b) static
Definition at line 995 of file qauthenticator.cpp.
{
     bool unicode = (b.flags & NTLMSSP_NEGOTIATE_UNICODE);
     s.writeRawData(b.magic, sizeof(b.magic));
     s << b.type;
     s << b.flags;
     s << b.domain;
     s << b.workstation;
     if (!b.domainStr.isEmpty())
         qStreamNtlmString(s, b.domainStr, unicode);
     if (!b.workstationStr.isEmpty())
         qStreamNtlmString(s, b.workstationStr, unicode);
     return s;
 }
operator<<() [3/3]
static QDataStream& operator<< (QDataStream & s, const QNtlmPhase3Block & b) static
Definition at line 1011 of file qauthenticator.cpp.
{
     bool unicode = (b.flags & NTLMSSP_NEGOTIATE_UNICODE);
     s.writeRawData(b.magic, sizeof(b.magic));
     s << b.type;
     s << b.lmResponse;
     s << b.ntlmResponse;
     s << b.domain;
     s << b.user;
     s << b.workstation;
     s << b.sessionKey;
     s << b.flags;
     if (!b.domainStr.isEmpty())
         qStreamNtlmString(s, b.domainStr, unicode);
     qStreamNtlmString(s, b.userStr, unicode);
     if (!b.workstationStr.isEmpty())
         qStreamNtlmString(s, b.workstationStr, unicode);
     // Send auth info
     qStreamNtlmBuffer(s, b.lmResponseBuf);
     qStreamNtlmBuffer(s, b.ntlmResponseBuf);
     return s;
 }
operator>>()
static QDataStream& operator>> (QDataStream & s, QNtlmBuffer & b) static
Definition at line 944 of file qauthenticator.cpp.
 {
     s >> b.len >> b.maxLen >> b.offset;
     return s;
 }
qCreatev2Hash()
static QByteArray qCreatev2Hash (const QAuthenticatorPrivate * ctx, QNtlmPhase3Block * phase3) static
Definition at line 1199 of file qauthenticator.cpp.
Referenced by qEncodeLmv2Response(), and qEncodeNtlmv2Response().
 {
     Q_ASSERT(phase3 != 0);
     // since v2 Hash is need for both NTLMv2 and LMv2 it is calculated
     // only once and stored and reused
     if(phase3->v2Hash.size() == 0) {
         QCryptographicHash md4(QCryptographicHash::Md4);
         QByteArray passUnicode = qStringAsUcs2Le(ctx->password);
         md4.addData(passUnicode.data(), passUnicode.size());
         QByteArray hashKey = md4.result();
         Q_ASSERT(hashKey.size() == 16);
         // Assuming the user and domain is always unicode in challenge
         QByteArray message =
                 qStringAsUcs2Le(ctx->extractedUser.toUpper()) +
                 qStringAsUcs2Le(phase3->domainStr);
         phase3->v2Hash = qEncodeHmacMd5(hashKey, message);
     }
     return phase3->v2Hash;
 }
qEncodeHmacMd5()
QByteArray qEncodeHmacMd5 (QByteArray & key, const QByteArray & message)
Definition at line 1139 of file qauthenticator.cpp.
Referenced by qCreatev2Hash(), qEncodeLmv2Response(), and qEncodeNtlmv2Response().
 {
     Q_ASSERT_X(!(message.isEmpty()),"qEncodeHmacMd5", "Empty message check");
     Q_ASSERT_X(!(key.isEmpty()),"qEncodeHmacMd5", "Empty key check");
     QCryptographicHash hash(QCryptographicHash::Md5);
     QByteArray hMsg;
     QByteArray iKeyPad(blockSize, 0x36);
     QByteArray oKeyPad(blockSize, 0x5c);
     hash.reset();
     // Adjust the key length to blockSize
     if(blockSize < key.length()) {
         hash.addData(key);
         key = hash.result(); //MD5 will always return 16 bytes length output
     }
     //Key will be <= 16 or 20 bytes as hash function (MD5 or SHA hash algorithms)
     //key size can be max of Block size only
     key = key.leftJustified(blockSize,0,true);
     //iKeyPad, oKeyPad and key are all of same size "blockSize"
     //xor of iKeyPad with Key and store the result into iKeyPad
     for(int i = 0; i<key.size();i++) {
         iKeyPad[i] = key[i]^iKeyPad[i];
     }
     //xor of oKeyPad with Key and store the result into oKeyPad
     for(int i = 0; i<key.size();i++) {
         oKeyPad[i] = key[i]^oKeyPad[i];
     }
     iKeyPad.append(message); // (K0 xor ipad) || text
     hash.reset();
     hash.addData(iKeyPad);
     hMsg = hash.result();
                     //Digest gen after pass-1: H((K0 xor ipad)||text)
     QByteArray hmacDigest;
     oKeyPad.append(hMsg);
     hash.reset();
     hash.addData(oKeyPad);
     hmacDigest = hash.result();
                     // H((K0 xor opad )|| H((K0 xor ipad) || text))
     /*hmacDigest should not be less than half the length of the HMAC output
       (to match the birthday attack bound) and not less than 80 bits
       (a suitable lower bound on the number of bits that need to be
       predicted by an attacker).
       Refer RFC 2104 for more details on truncation part */
     /*MD5 hash always returns 16 byte digest only and HMAC-MD5 spec
       (RFC 2104) also says digest length should be 16 bytes*/
     return hmacDigest;
 }
qEncodeLmv2Response()
static QByteArray qEncodeLmv2Response (const QAuthenticatorPrivate * ctx, const QNtlmPhase2Block & ch, QNtlmPhase3Block * phase3) static
Definition at line 1326 of file qauthenticator.cpp.
Referenced by qNtlmPhase3().
 {
     Q_ASSERT(phase3 != 0);
     // return value stored in phase3
     qCreatev2Hash(ctx, phase3);
     QByteArray message((const char*)ch.challenge, sizeof(ch.challenge));
     QByteArray clientCh = clientChallenge(ctx);
     message.append(clientCh);
     QByteArray lmChallengeResp = qEncodeHmacMd5(phase3->v2Hash, message);
     lmChallengeResp.append(clientCh);
     return lmChallengeResp;
 }
qEncodeNtlmBuffer()
static int qEncodeNtlmBuffer (QNtlmBuffer & buf, int offset, const QByteArray & s) static
Definition at line 918 of file qauthenticator.cpp.
Referenced by qEncodeNtlmString(), and qNtlmPhase3().
 {
     buf.len = s.size();
     buf.maxLen = buf.len;
     buf.offset = (offset + 1) & ~1;
     return buf.offset + buf.len;
 }
qEncodeNtlmString()
static int qEncodeNtlmString (QNtlmBuffer & buf, int offset, const QString & s, bool unicode) static
Definition at line 927 of file qauthenticator.cpp.
Referenced by qNtlmPhase3().
 {
     if (!unicode)
         return qEncodeNtlmBuffer(buf, offset, s.toLatin1());
     buf.len = 2 * s.length();
     buf.maxLen = buf.len;
     buf.offset = (offset + 1) & ~1;
     return buf.offset + buf.len;
 }
qEncodeNtlmv2Response()
static QByteArray qEncodeNtlmv2Response (const QAuthenticatorPrivate * ctx, const QNtlmPhase2Block & ch, QNtlmPhase3Block * phase3) static
Definition at line 1255 of file qauthenticator.cpp.
Referenced by qNtlmPhase3().
 {
     Q_ASSERT(phase3 != 0);
     // return value stored in phase3
     qCreatev2Hash(ctx, phase3);
     QByteArray temp;
     QDataStream ds(&temp, QIODevice::WriteOnly);
     ds.setByteOrder(QDataStream::LittleEndian);
     ds << respversion;
     ds << hirespversion;
     //Reserved
     QByteArray reserved1(6, 0);
     ds.writeRawData(reserved1.constData(), reserved1.size());
     quint64 time = 0;
     QByteArray timeArray;
     if(ch.targetInfo.len)
     {
         timeArray = qExtractServerTime(ch.targetInfoBuff);
     }
     //if server sends time, use it instead of current time
     if(timeArray.size()) {
         ds.writeRawData(timeArray.constData(), timeArray.size());
     } else {
         QDateTime currentTime(QDate::currentDate(),
                               QTime::currentTime(), Qt::UTC);
         // number of seconds between 1601 and epoc(1970)
         // 369 years, 89 leap years
         // ((369 * 365) + 89) * 24 * 3600 = 11644473600
         time = Q_UINT64_C(currentTime.toTime_t() + 11644473600);
         // represented as 100 nano seconds
         time = Q_UINT64_C(time * 10000000);
         ds << time;
     }
     //8 byte client challenge
     QByteArray clientCh = clientChallenge(ctx);
     ds.writeRawData(clientCh.constData(), clientCh.size());
     //Reserved
     QByteArray reserved2(4, 0);
     ds.writeRawData(reserved2.constData(), reserved2.size());
     if (ch.targetInfo.len > 0) {
         ds.writeRawData(ch.targetInfoBuff.constData(),
                         ch.targetInfoBuff.size());
     }
     //Reserved
     QByteArray reserved3(4, 0);
     ds.writeRawData(reserved3.constData(), reserved3.size());
     QByteArray message((const char*)ch.challenge, sizeof(ch.challenge));
     message.append(temp);
     QByteArray ntChallengeResp = qEncodeHmacMd5(phase3->v2Hash, message);
     ntChallengeResp.append(temp);
     return ntChallengeResp;
 }
qExtractServerTime()
static QByteArray qExtractServerTime (const QByteArray & targetInfoBuff) static
Definition at line 1230 of file qauthenticator.cpp.
Referenced by qEncodeNtlmv2Response().
 {
     QByteArray timeArray;
     QDataStream ds(targetInfoBuff);
     ds.setByteOrder(QDataStream::LittleEndian);
     quint16 avId;
     quint16 avLen;
     ds >> avId;
     ds >> avLen;
     while(avId != 0) {
         if(avId == AVTIMESTAMP) {
             timeArray.resize(avLen);
             //avLen size of QByteArray is allocated
             ds.readRawData(timeArray.data(), avLen);
             break;
         }
         ds.skipRawData(avLen);
         ds >> avId;
         ds >> avLen;
     }
     return timeArray;
 }
qNtlmDecodePhase2()
static bool qNtlmDecodePhase2 (const QByteArray & data, QNtlmPhase2Block & ch) static
Definition at line 1345 of file qauthenticator.cpp.
Referenced by qNtlmPhase3().
 {
     Q_ASSERT(QNtlmPhase2BlockBase::Size == sizeof(QNtlmPhase2BlockBase));
     if (data.size() < QNtlmPhase2BlockBase::Size)
         return false;
     QDataStream ds(data);
     ds.setByteOrder(QDataStream::LittleEndian);
     if (ds.readRawData(ch.magic, 8) < 8)
         return false;
     if (strncmp(ch.magic, "NTLMSSP", 8) != 0)
         return false;
     ds >> ch.type;
     if (ch.type != 2)
         return false;
     ds >> ch.targetName;
     ds >> ch.flags;
     if (ds.readRawData((char *)ch.challenge, 8) < 8)
         return false;
     ds >> ch.context[0] >> ch.context[1];
     ds >> ch.targetInfo;
     if (ch.targetName.len > 0) {
         if (ch.targetName.len + ch.targetName.offset >= (unsigned)data.size())
             return false;
         ch.targetNameStr = qStringFromUcs2Le(data.mid(ch.targetName.offset, ch.targetName.len));
     }
     if (ch.targetInfo.len > 0) {
         if (ch.targetInfo.len + ch.targetInfo.offset > (unsigned)data.size())
             return false;
         ch.targetInfoBuff = data.mid(ch.targetInfo.offset, ch.targetInfo.len);
     }
     return true;
 }
qNtlmPhase1()
static QByteArray qNtlmPhase1 () static
Definition at line 1040 of file qauthenticator.cpp.
Referenced by QAuthenticatorPrivate::calculateResponse().
 {
     QByteArray rc;
     QDataStream ds(&rc, QIODevice::WriteOnly);
     ds.setByteOrder(QDataStream::LittleEndian);
     QNtlmPhase1Block pb;
     ds << pb;
     return rc;
 }
qNtlmPhase3()
static QByteArray qNtlmPhase3 (QAuthenticatorPrivate * ctx, const QByteArray & phase2data) static
Definition at line 1388 of file qauthenticator.cpp.
Referenced by QAuthenticatorPrivate::calculateResponse().
 {
     QNtlmPhase2Block ch;
     if (!qNtlmDecodePhase2(phase2data, ch))
         return QByteArray();
     QByteArray rc;
     QDataStream ds(&rc, QIODevice::WriteOnly);
     ds.setByteOrder(QDataStream::LittleEndian);
     QNtlmPhase3Block pb;
     bool unicode = ch.flags & NTLMSSP_NEGOTIATE_UNICODE;
     pb.flags = NTLMSSP_NEGOTIATE_NTLM;
     if (unicode)
         pb.flags |= NTLMSSP_NEGOTIATE_UNICODE;
     else
         pb.flags |= NTLMSSP_NEGOTIATE_OEM;
     int offset = QNtlmPhase3BlockBase::Size;
     Q_ASSERT(QNtlmPhase3BlockBase::Size == sizeof(QNtlmPhase3BlockBase));
     // for kerberos style user@domain logins, NTLM domain string should be left empty
     if (ctx->userDomain.isEmpty() && !ctx->extractedUser.contains(QLatin1Char('@'))) {
         offset = qEncodeNtlmString(pb.domain, offset, ch.targetNameStr, unicode);
         pb.domainStr = ch.targetNameStr;
     } else {
         offset = qEncodeNtlmString(pb.domain, offset, ctx->userDomain, unicode);
         pb.domainStr = ctx->userDomain;
     }
     offset = qEncodeNtlmString(pb.user, offset, ctx->extractedUser, unicode);
     pb.userStr = ctx->extractedUser;
     offset = qEncodeNtlmString(pb.workstation, offset, ctx->workstation, unicode);
     pb.workstationStr = ctx->workstation;
     // Get LM response
 #ifdef NTLMV1_CLIENT
     pb.lmResponseBuf = qEncodeLmResponse(ctx, ch);
 #else
     if (ch.targetInfo.len > 0) {
         pb.lmResponseBuf = QByteArray();
     } else {
         pb.lmResponseBuf = qEncodeLmv2Response(ctx, ch, &pb);
     }
 #endif
     offset = qEncodeNtlmBuffer(pb.lmResponse, offset, pb.lmResponseBuf);
     // Get NTLM response
 #ifdef NTLMV1_CLIENT
     pb.ntlmResponseBuf = qEncodeNtlmResponse(ctx, ch);
 #else
     pb.ntlmResponseBuf = qEncodeNtlmv2Response(ctx, ch, &pb);
 #endif
     offset = qEncodeNtlmBuffer(pb.ntlmResponse, offset, pb.ntlmResponseBuf);
     // Encode and send
     ds << pb;
     return rc;
 }
qStreamNtlmBuffer()
static void qStreamNtlmBuffer (QDataStream & ds, const QByteArray & s) static
Definition at line 899 of file qauthenticator.cpp.
Referenced by operator<<(), and qStreamNtlmString().
 {
     ds.writeRawData(s.constData(), s.size());
 }
qStreamNtlmString()
static void qStreamNtlmString (QDataStream & ds, const QString & s, bool unicode) static
Definition at line 905 of file qauthenticator.cpp.
Referenced by operator<<().
 {
     if (!unicode) {
         qStreamNtlmBuffer(ds, s.toLatin1());
         return;
     }
     const ushort *d = s.utf16();
     for (int i = 0; i < s.length(); ++i)
         ds << d[i];
 }
qStringAsUcs2Le()
static QByteArray qStringAsUcs2Le (const QString & src) static
Definition at line 1051 of file qauthenticator.cpp.
Referenced by qCreatev2Hash(), and qStringFromUcs2Le().
 {
     QByteArray rc(2*src.length(), 0);
     const unsigned short *s = src.utf16();
     unsigned short *d = (unsigned short*)rc.data();
     for (int i = 0; i < src.length(); ++i) {
         d[i] = qToLittleEndian(s[i]);
     }
     return rc;
 }
qStringFromUcs2Le()
static QString qStringFromUcs2Le (const QByteArray & src) static
Definition at line 1063 of file qauthenticator.cpp.
Referenced by qNtlmDecodePhase2().
 {
     Q_ASSERT(src.size() % 2 == 0);
     unsigned short *d = (unsigned short*)src.data();
     for (int i = 0; i < src.length() / 2; ++i) {
         d[i] = qFromLittleEndian(d[i]);
     }
     return QString((const QChar *)src.data(), src.size()/2);
 }
Variable Documentation
blockSize
const int blockSize = 64
Definition at line 829 of file qauthenticator.cpp.
Referenced by elapsed(), QFSFileEnginePrivate::longFileName(), operator>>(), QByteArray::operator>>(), qEncodeHmacMd5(), QFontEngineQPA::QFontEngineQPA(), QFontEngineQPF::QFontEngineQPF(), QDataStream::readBytes(), QGIFFormat::scan(), QDataStream::skipRawData(), QIODevice::write(), and QFtpDTP::writeData().
hirespversion
const quint8 hirespversion = 1
Definition at line 832 of file qauthenticator.cpp.
Referenced by qEncodeNtlmv2Response().
nDigestLen
const int nDigestLen = 16
Definition at line 830 of file qauthenticator.cpp.
respversion
const quint8 respversion = 1
Definition at line 831 of file qauthenticator.cpp.
Referenced by qEncodeNtlmv2Response().