Qt 4.8: /src/activeqt/control/qaxfactory.h File Reference
qaxfactory.h File Reference
#include <QtCore/qhash.h>
#include <QtCore/quuid.h>
#include <QtCore/qfactoryinterface.h>
#include <QtCore/qmetaobject.h>
#include <QtCore/qstringlist.h>
Classes
class QAxClass< T >
class QAxFactory
The QAxFactory class defines a factory for the creation of COM components.
Macros
#define Q_COM_METATYPE_DECLARED
#define QAXCLASS(Class)
This macro adds a creatable COM class Class to the QAxFactory declared with the QAXFACTORY_BEGIN() macro.
#define QAXFACTORY_BEGIN(IDTypeLib, IDApp)
This macro can be used to export multiple QObject classes through an implicitly declared QAxFactory implementation.
#define QAXFACTORY_DEFAULT(Class, IIDClass, IIDInterface, IIDEvents, IIDTypeLib, IIDApp)
This macro can be used to export a single QObject subclass Class a this COM server through an implicitly declared QAxFactory implementation.
#define QAXFACTORY_END()
Completes the QAxFactory declaration started with the QAXFACTORY_BEGIN() macro.
#define QAXFACTORY_EXPORT(IMPL, TYPELIB, APPID)
This macro can be used to export a QAxFactory implementation Class from a COM server.
#define QAXTYPE(Class)
This macro adds a non-creatable COM class Class to the QAxFactory declared with the QAXFACTORY_BEGIN().
Functions
bool qax_startServer (QAxFactory::ServerType)
bool qax_stopServer ()
QAxFactory * qAxFactory ()
Macro Definition Documentation
Q_COM_METATYPE_DECLARED
#define Q_COM_METATYPE_DECLARED
Definition at line 300 of file qaxfactory.h.
QAXCLASS
#define QAXCLASS (Class)
Value:
factory = new QAxClass<Class>(typeLibID(), appID()); \
            qRegisterMetaType<Class*>(#Class"*"); \
            keys = factory->featureList(); \
            for (it = keys.begin(); it != keys.end(); ++it) { \
                factoryKeys += *it; \
                factories.insert(*it, factory); \
                creatable.insert(*it, true); \
            }\
This macro adds a creatable COM class Class to the QAxFactory declared with the QAXFACTORY_BEGIN() macro.
See also
QAXFACTORY_BEGIN(), QAXTYPE(), QAXFACTORY_END(), Q_CLASSINFO()
Definition at line 223 of file qaxfactory.h.
QAXFACTORY_BEGIN
#define QAXFACTORY_BEGIN (IDTypeLib, IDApp)
Value:
QT_BEGIN_NAMESPACE \
    class QAxFactoryList : public QAxFactory \
    { \
        QStringList factoryKeys; \
        QHash<QString, QAxFactory*> factories; \
        QHash<QString, bool> creatable; \
    public: \
        QAxFactoryList() \
        : QAxFactory(IDTypeLib, IDApp) \
        { \
            QAxFactory *factory = 0; \
            QStringList keys; \
            QStringList::Iterator it; \
This macro can be used to export multiple QObject classes through an implicitly declared QAxFactory implementation.
All QObject classes have to declare the ClassID, InterfaceID and EventsID (if applicable) through the Q_CLASSINFO() macro. All declarations will be in a type library with the id IDTypeLib, and if the server is an executable server then it will have the application id IDApp.
This macro needs to be used together with the QAXCLASS(), QAXTYPE() and QAXFACTORY_END() macros.
QAXFACTORY_BEGIN(
    "{01234567-89AB-CDEF-0123-456789ABCDEF}", // type library ID
    "{01234567-89AB-CDEF-0123-456789ABCDEF}"  // application ID
)
    QAXCLASS(Class1)
    QAXCLASS(Class2)
QAXFACTORY_END()
Definition at line 208 of file qaxfactory.h.
QAXFACTORY_DEFAULT
#define QAXFACTORY_DEFAULT (Class, IIDClass, IIDInterface, IIDEvents, IIDTypeLib, IIDApp)
This macro can be used to export a single QObject subclass Class a this COM server through an implicitly declared QAxFactory implementation.
This macro exports the class Class as a COM coclass with the CLSID ClassID. The properties and slots will be declared through a COM interface with the IID InterfaceID, and signals will be declared through a COM event interface with the IID EventID. All declarations will be in a type library with the id LibID, and if the server is an executable server then it will have the application id AppID.
#include <qaxfactory.h>
#include "theactivex.h"
QAXFACTORY_DEFAULT(
    TheActiveX,               // widget class
    "{01234567-89AB-CDEF-0123-456789ABCDEF}", // class ID
    "{01234567-89AB-CDEF-0123-456789ABCDEF}", // interface ID
    "{01234567-89AB-CDEF-0123-456789ABCDEF}", // event interface ID
    "{01234567-89AB-CDEF-0123-456789ABCDEF}", // type library ID
    "{01234567-89AB-CDEF-0123-456789ABCDEF}"  // application ID
)
See also
QAXFACTORY_EXPORT(), QAXFACTORY_BEGIN()
Definition at line 138 of file qaxfactory.h.
QAXFACTORY_END
#define QAXFACTORY_END ()
Completes the QAxFactory declaration started with the QAXFACTORY_BEGIN() macro.
See also
QAXFACTORY_BEGIN(), QAXCLASS(), QAXTYPE()
Definition at line 243 of file qaxfactory.h.
QAXFACTORY_EXPORT
#define QAXFACTORY_EXPORT (IMPL, TYPELIB, APPID)
Value:
QT_BEGIN_NAMESPACE \
    QAxFactory *qax_instantiate()       \
    {                           \
        IMPL *impl = new IMPL(QUuid(TYPELIB), QUuid(APPID));    \
        return impl;                    \
    } \
    QT_END_NAMESPACE
This macro can be used to export a QAxFactory implementation Class from a COM server.
All declarations will be in a type library with the id LibID, and if the server is an executable server then it will have the application id AppID.
QAXFACTORY_EXPORT(
    MyFactory,                        // factory class
    "{01234567-89AB-CDEF-0123-456789ABCDEF}", // type library ID
    "{01234567-89AB-CDEF-0123-456789ABCDEF}"  // application ID
)
See also
QAXFACTORY_BEGIN()
Definition at line 129 of file qaxfactory.h.
QAXTYPE
#define QAXTYPE (Class)
Value:
factory = new QAxClass<Class>(typeLibID(), appID()); \
            qRegisterMetaType<Class*>(#Class"*"); \
            keys = factory->featureList(); \
            for (it = keys.begin(); it != keys.end(); ++it) { \
                factoryKeys += *it; \
                factories.insert(*it, factory); \
                creatable.insert(*it, false); \
            }\
This macro adds a non-creatable COM class Class to the QAxFactory declared with the QAXFACTORY_BEGIN().
The class Class can be used in APIs of other COM classes exported through QAXTYPE() or QAXCLASS().
Instances of type Class can only be retrieved using APIs of already instantiated objects.
See also
QAXFACTORY_BEGIN(), QAXCLASS(), QAXFACTORY_END(), Q_CLASSINFO()
Definition at line 233 of file qaxfactory.h.
Function Documentation
qax_startServer()
bool qax_startServer (QAxFactory::ServerType)
Definition at line 127 of file qaxservermain.cpp.
Referenced by QAxFactory::startServer().
 {
     if (qAxIsServer)
         return true;
     const QStringList keys = qAxFactory()->featureList();
     if (!keys.count())
         return false;
     if (!qAxFactory()->isService())
         StartMonitor();
     classRegistration = new DWORD[keys.count()];
     int object = 0;
     for (QStringList::ConstIterator key = keys.begin(); key != keys.end(); ++key, ++object) {
         IUnknown* p = 0;
         CLSID clsid = qAxFactory()->classID(*key);
         // Create a QClassFactory (implemented in qaxserverbase.cpp)
         HRESULT hRes = GetClassObject(clsid, IID_IClassFactory, (void**)&p);
         if (SUCCEEDED(hRes))
             hRes = CoRegisterClassObject(clsid, p, CLSCTX_LOCAL_SERVER,
                 type == QAxFactory::MultipleInstances ? REGCLS_MULTIPLEUSE : REGCLS_SINGLEUSE,
                 classRegistration+object);
         if (p)
             p->Release();
     }
     qAxIsServer = true;
     return true;
 }
qax_stopServer()
bool qax_stopServer ()
Definition at line 162 of file qaxservermain.cpp.
Referenced by QAxFactory::startServer(), and QAxFactory::stopServer().
 {
     if (!qAxIsServer || !classRegistration)
         return true;
     qAxIsServer = false;
     const QStringList keys = qAxFactory()->featureList();
     int object = 0;
     for (QStringList::ConstIterator key = keys.begin(); key != keys.end(); ++key, ++object)
         CoRevokeClassObject(classRegistration[object]);
     delete []classRegistration;
     classRegistration = 0;
     Sleep(dwPause); //wait for any threads to finish
     return true;
 }
qAxFactory()
QAxFactory* qAxFactory ()
Definition at line 81 of file qaxserver.cpp.
Referenced by qax_create_object_wrapper(), qax_startServer(), qax_stopServer(), QVariantToVARIANT(), and QAxFactory::registerActiveObject().
 {
     if (!qax_factory) {
         bool hadQApp = qApp != 0;
         qax_factory = qax_instantiate();
         // QAxFactory created a QApplication
         if (!hadQApp && qApp)
             qax_ownQApp = true;
         // register all types with metatype system as pointers
         QStringList keys(qax_factory->featureList());
         for (int i = 0; i < keys.count(); ++i) {
             QString key(keys.at(i));
             qRegisterMetaType((key + QLatin1Char('*')).toLatin1(), (void**)(quintptr)-1);
         }
     }
     return qax_factory;
 }