Qt 4.8: /src/activeqt/control/qaxserver.cpp File Reference
qaxserver.cpp File Reference
#include "qaxbindable.h"
#include "qaxfactory.h"
#include <qapplication.h>
#include <qdatetime.h>
#include <qdir.h>
#include <qmap.h>
#include <qmenubar.h>
#include <qmetaobject.h>
#include <qsettings.h>
#include <qvariant.h>
#include <qtextstream.h>
#include <qt_windows.h>
#include <olectl.h>
Macros
#define Q_REQUIRED_RPCNDR_H_VERSION 475
#define STRIPCB(x) x = x.mid(1, x.length()-2)
Functions
static QByteArray addDefaultArguments (const QByteArray &prototype, int numDefArgs)
static HRESULT classIDL (QObject *o, const QMetaObject *mo, const QString &className, bool isBindable, QTextStream &out)
static QByteArray convertTypes (const QByteArray &qtype, bool *ok)
HRESULT __stdcall DumpIDL (const QString &outfile, const QString &ver)
static bool ignore (const char *test, const char *const *table)
bool ignoreProps (const char *test)
bool ignoreSlots (const char *test)
static QByteArray prototype (const QList< QByteArray > &parameterTypes, const QList< QByteArray > &parameterNames, bool *ok)
QString qax_clean_type (const QString &type, const QMetaObject *mo)
QAxFactory * qax_instantiate ()
void qax_shutDown ()
void qAxCleanup ()
QAxFactory * qAxFactory ()
QString qAxInit ()
unsigned long qAxLock ()
unsigned long qAxLockCount ()
unsigned long qAxUnlock ()
static QByteArray renameOverloads (const QByteArray &name)
static QByteArray replaceKeyword (const QByteArray &name)
HRESULT UpdateRegistry (BOOL bRegister)
Variables
CLSID CLSID_QPoint
CLSID CLSID_QRect
CLSID CLSID_QSize
static QList< QByteArray > enums
static QList< QByteArray > enumValues
static const char *const ignore_props []
static const char *const ignore_slots []
static int initCount = 0
static const char *const keyword_map [][2]
static QMap< QByteArray, int > mapping
bool qax_disable_inplaceframe
static QAxFactory * qax_factory = 0
bool qax_ownQApp
HANDLE qAxInstance = 0
bool qAxIsServer = false
wchar_t qAxModuleFilename [MAX_PATH]
static unsigned long qAxModuleRef = 0
static CRITICAL_SECTION qAxModuleSection
bool qAxOutProcServer = false
ITypeLib * qAxTypeLibrary = 0
static QList< QByteArray > subtypes
static const char *const type_map [][2]
Macro Definition Documentation
Q_REQUIRED_RPCNDR_H_VERSION
#define Q_REQUIRED_RPCNDR_H_VERSION 475
Definition at line 61 of file qaxserver.cpp.
STRIPCB
#define STRIPCB (x) x = x.mid(1, x.length()-2)
Definition at line 683 of file qaxserver.cpp.
Referenced by classIDL(), and DumpIDL().
Function Documentation
addDefaultArguments()
static QByteArray addDefaultArguments (const QByteArray & prototype, int numDefArgs) static
Definition at line 727 of file qaxserver.cpp.
Referenced by classIDL().
 {
     // nothing to do, or unsupported anyway
     if (!numDefArgs || prototype.contains("/**"))
         return prototype;
     QByteArray ptype(prototype);
     int in = -1;
     while (numDefArgs) {
         in = ptype.lastIndexOf(']', in);
         ptype.replace(in, 1, ",optional]");
         in = ptype.indexOf(' ', in) + 1;
         QByteArray type = ptype.mid(in, ptype.indexOf(' ', in) - in);
         if (type == "enum")
             type += ' ' + ptype.mid(in + 5, ptype.indexOf(' ', in + 5) - in - 5);
         ptype.replace(in, type.length(), QByteArray("VARIANT /*was: ") + type + "*/");
         --numDefArgs;
     }
     return ptype;
 }
classIDL()
static HRESULT classIDL (QObject * o, const QMetaObject * mo, const QString & className, bool isBindable, QTextStream & out) static
Definition at line 749 of file qaxserver.cpp.
 {
     int id = 1;
     int i = 0;
     if (!mo)
         return 3;
     QString topclass = qAxFactory()->exposeToSuperClass(className);
     if (topclass.isEmpty())
         topclass = QLatin1String("QObject");
     bool hasStockEvents = qAxFactory()->hasStockEvents(className);
     const QMetaObject *pmo = mo;
     do {
         pmo = pmo->superClass();
     } while (pmo && topclass != QString::fromLatin1(pmo->className()));
     int enumoff = pmo ? pmo->enumeratorOffset() : mo->enumeratorOffset();
     int methodoff = pmo ? pmo->methodOffset() : mo->methodOffset();
     int propoff = pmo ? pmo->propertyOffset() : mo->propertyOffset();
     int qtProps = 0;
     int qtSlots = 0;
     bool control = false;
     if (o && o->isWidgetType()) {
         qtProps = QWidget::staticMetaObject.propertyCount();
         qtSlots = QWidget::staticMetaObject.methodCount();
         control = true;
     }
     QString classID = qAxFactory()->classID(className).toString().toUpper();
     if (QUuid(classID).isNull())
         return 4;
     STRIPCB(classID);
     QString interfaceID = qAxFactory()->interfaceID(className).toString().toUpper();
     if (QUuid(interfaceID).isNull())
         return 5;
     STRIPCB(interfaceID);
     QString eventsID = qAxFactory()->eventsID(className).toString().toUpper();
     bool hasEvents = !QUuid(eventsID).isNull();
     STRIPCB(eventsID);
     QString cleanClassName = qax_clean_type(className, mo);
     QString defProp(QLatin1String(mo->classInfo(mo->indexOfClassInfo("DefaultProperty")).value()));
     QString defSignal(QLatin1String(mo->classInfo(mo->indexOfClassInfo("DefaultSignal")).value()));
     for (i = enumoff; i < mo->enumeratorCount(); ++i) {
         const QMetaEnum enumerator = mo->enumerator(i);
         if (enums.contains(enumerator.name()))
             continue;
         enums.append(enumerator.name());
         out << "\tenum " << enumerator.name() << " {" << endl;
         for (int j = 0; j < enumerator.keyCount(); ++j) {
             QByteArray key(enumerator.key(j));
             while (enumValues.contains(key)) {
                 key += '_';
             }
             enumValues.append(key);
             uint value = (uint)enumerator.value(j);
             key = key.leftJustified(20);
             out << "\t\t" << key << "\t= ";
             if (enumerator.isFlag())
                 out << "0x" << QByteArray::number(value, 16).rightJustified(8, '0');
             else
                 out << value;
             if (j < enumerator.keyCount()-1)
                 out << ", ";
             out << endl;
         }
         out << "\t};" << endl << endl;
     }
     // mouse cursor enum for QCursor support
     if (!enums.contains("MousePointer")) {
         enums.append("MousePointer");
         out << "\tenum MousePointer {" << endl;
         out << "\t\tArrowCursor             = " << Qt::ArrowCursor << ',' << endl;
         out << "\t\tUpArrowCursor           = " << Qt::UpArrowCursor << ',' << endl;
         out << "\t\tCrossCursor             = " << Qt::CrossCursor << ',' << endl;
         out << "\t\tWaitCursor              = " << Qt::WaitCursor << ',' << endl;
         out << "\t\tIBeamCursor             = " << Qt::IBeamCursor << ',' << endl;
         out << "\t\tSizeVerCursor           = " << Qt::SizeVerCursor << ',' << endl;
         out << "\t\tSizeHorCursor           = " << Qt::SizeHorCursor << ',' << endl;
         out << "\t\tSizeBDiagCursor         = " << Qt::SizeBDiagCursor << ',' << endl;
         out << "\t\tSizeFDiagCursor         = " << Qt::SizeFDiagCursor << ',' << endl;
         out << "\t\tSizeAllCursor           = " << Qt::SizeAllCursor << ',' << endl;
         out << "\t\tBlankCursor             = " << Qt::BlankCursor << ',' << endl;
         out << "\t\tSplitVCursor            = " << Qt::SplitVCursor << ',' << endl;
         out << "\t\tSplitHCursor            = " << Qt::SplitHCursor << ',' << endl;
         out << "\t\tPointingHandCursor      = " << Qt::PointingHandCursor << ',' << endl;
         out << "\t\tForbiddenCursor         = " << Qt::ForbiddenCursor << ',' << endl;
         out << "\t\tWhatsThisCursor         = " << Qt::WhatsThisCursor << ',' << endl;
         out << "\t\tBusyCursor\t= " << Qt::BusyCursor << endl;
         out << "\t};" << endl << endl;
     }
     if (!enums.contains("FocusPolicy")) {
         enums.append("FocusPolicy");
         out << "\tenum FocusPolicy {" << endl;
         out << "\t\tNoFocus             = " << Qt::NoFocus << ',' << endl;
         out << "\t\tTabFocus            = " << Qt::TabFocus << ',' << endl;
         out << "\t\tClickFocus          = " << Qt::ClickFocus << ',' << endl;
         out << "\t\tStrongFocus         = " << Qt::StrongFocus << ',' << endl;
         out << "\t\tWheelFocus          = " << Qt::WheelFocus << endl;
         out << "\t};" << endl << endl;
     }
     out << endl;
     out << "\t[" << endl;
     out << "\t\tuuid(" << interfaceID << ")," << endl;
     out << "\t\thelpstring(\"" << cleanClassName << " Interface\")" << endl;
     out << "\t]" << endl;
     out << "\tdispinterface I" << cleanClassName  << endl;
     out << "\t{" << endl;
     out << "\tproperties:" << endl;
     for (i = propoff; i < mo->propertyCount(); ++i) {
         const QMetaProperty property = mo->property(i);
         /*  if (property.testFlags(QMetaProperty::Override))
         continue;*/
         if (i <= qtProps && ignoreProps(property.name()))
             continue;
         if (!property.name() || mo->indexOfProperty(property.name()) > i)
             continue;
         bool ok = true;
         QByteArray type(convertTypes(property.typeName(), &ok));
         QByteArray name(replaceKeyword(property.name()));
         if (!ok)
             out << "\t/****** Property is of unsupported datatype" << endl;
         out << "\t\t[id(" << id << ')';
         if (!property.isWritable())
             out << ", readonly";
         if (isBindable && property.isScriptable(o))
             out << ", bindable";
         if (!property.isDesignable(o))
             out << ", nonbrowsable";
         if (isBindable)
             out << ", requestedit";
         if (defProp == QLatin1String(name))
             out << ", uidefault";
         out << "] " << type << ' ' << name << ';' << endl;
         if (!ok)
             out << "\t******/" << endl;
         ++id;
     }
     out << endl;
     out << "\tmethods:" << endl;
     int numDefArgs = 0;
     QByteArray outBuffer;
     for (i = methodoff; i < mo->methodCount(); ++i) {
         const QMetaMethod slot = mo->method(i);
         if (slot.access() != QMetaMethod::Public || slot.methodType() == QMetaMethod::Signal)
             continue;
         if (slot.attributes() & QMetaMethod::Cloned) {
             ++numDefArgs;
             continue;
         }
         if (!outBuffer.isEmpty()) {
             outBuffer = addDefaultArguments(outBuffer, numDefArgs);
             numDefArgs = 0;
             out << outBuffer;
             outBuffer = QByteArray();
         }
         QByteArray signature(slot.signature());
         QByteArray name(signature.left(signature.indexOf('(')));
         if (i <= qtSlots && ignoreSlots(name))
             continue;
         signature = signature.mid(name.length() + 1);
         signature.truncate(signature.length() - 1);
         name = renameOverloads(replaceKeyword(name));
         if (ignoreSlots(name))
             continue;
         QList<QByteArray> parameterTypes(slot.parameterTypes());
         QList<QByteArray> parameterNames(slot.parameterNames());
         bool ok = true;
         QByteArray type = slot.typeName();
         if (type.isEmpty())
             type = "void";
         else
             type = convertTypes(type, &ok);
         QByteArray ptype(prototype(parameterTypes, parameterNames, &ok));
         if (!ok)
             outBuffer += "\t/****** Slot parameter uses unsupported datatype\n";
         outBuffer += "\t\t[id(" + QString::number(id).toLatin1() + ")] " + type + ' ' + name + '(' + ptype + ");\n";
         if (!ok)
             outBuffer += "\t******/\n";
         ++id;
     }
     if (!outBuffer.isEmpty()) {
         outBuffer = addDefaultArguments(outBuffer, numDefArgs);
         numDefArgs = 0;
         out << outBuffer;
         outBuffer = QByteArray();
     }
     out << "\t};" << endl << endl;
     mapping.clear();
     id = 1;
     if (hasEvents) {
         out << "\t[" << endl;
         out << "\t\tuuid(" << eventsID << ")," << endl;
         out << "\t\thelpstring(\"" << cleanClassName << " Events Interface\")" << endl;
         out << "\t]" << endl;
         out << "\tdispinterface I" << cleanClassName << "Events" << endl;
         out << "\t{" << endl;
         out << "\tproperties:" << endl;
         out << "\tmethods:" << endl;
         if (hasStockEvents) {
             out << "\t/****** Stock events ******/" << endl;
             out << "\t\t[id(DISPID_CLICK)] void Click();" << endl;
             out << "\t\t[id(DISPID_DBLCLICK)] void DblClick();" << endl;
             out << "\t\t[id(DISPID_KEYDOWN)] void KeyDown(short* KeyCode, short Shift);" << endl;
             out << "\t\t[id(DISPID_KEYPRESS)] void KeyPress(short* KeyAscii);" << endl;
             out << "\t\t[id(DISPID_KEYUP)] void KeyUp(short* KeyCode, short Shift);" << endl;
             out << "\t\t[id(DISPID_MOUSEDOWN)] void MouseDown(short Button, short Shift, OLE_XPOS_PIXELS x, OLE_YPOS_PIXELS y);" << endl;
             out << "\t\t[id(DISPID_MOUSEMOVE)] void MouseMove(short Button, short Shift, OLE_XPOS_PIXELS x, OLE_YPOS_PIXELS y);" << endl;
             out << "\t\t[id(DISPID_MOUSEUP)] void MouseUp(short Button, short Shift, OLE_XPOS_PIXELS x, OLE_YPOS_PIXELS y);" << endl << endl;
         }
         for (i = methodoff; i < mo->methodCount(); ++i) {
             const QMetaMethod signal = mo->method(i);
             if (signal.methodType() != QMetaMethod::Signal)
                 continue;
             QByteArray signature(signal.signature());
             QByteArray name(signature.left(signature.indexOf('(')));
             signature = signature.mid(name.length() + 1);
             signature.truncate(signature.length() - 1);
             QList<QByteArray> parameterTypes(signal.parameterTypes());
             QList<QByteArray> parameterNames(signal.parameterNames());
             bool isDefault = defSignal == QLatin1String(name);
             name = renameOverloads(replaceKeyword(name));
             bool ok = true;
             QByteArray type = signal.typeName();
             if (!type.isEmpty()) // signals with return value not supported
                 continue;
             QByteArray ptype(prototype(parameterTypes, parameterNames, &ok));
             if (!ok)
                 out << "\t/****** Signal parameter uses unsupported datatype" << endl;
             out << "\t\t[id(" << id << ')';
             if (isDefault)
                 out << ", uidefault";
             out << "] void " << name << '(' << ptype << ");" << endl;
             if (!ok)
                 out << "\t******/" << endl;
             ++id;
         }
         out << "\t};" << endl << endl;
     }
     out << "\t[" << endl;
     if (qstricmp(mo->classInfo(mo->indexOfClassInfo("Aggregatable")).value(), "no"))
         out << "\t\taggregatable," << endl;
     if (!qstricmp(mo->classInfo(mo->indexOfClassInfo("RegisterObject")).value(), "yes"))
         out << "\t\tappobject," << endl;
     if (mo->classInfo(mo->indexOfClassInfo("LicenseKey")).value())
         out << "\t\tlicensed," << endl;
     const char *helpString = mo->classInfo(mo->indexOfClassInfo("Description")).value();
     if (helpString)
         out << "\t\thelpstring(\"" << helpString << "\")," << endl;
     else
         out << "\t\thelpstring(\"" << cleanClassName << " Class\")," << endl;
     const char *classVersion = mo->classInfo(mo->indexOfClassInfo("Version")).value();
     if (classVersion)
         out << "\t\tversion(" << classVersion << ")," << endl;
     out << "\t\tuuid(" << classID << ')';
     if (control) {
         out << ", " << endl;
         out << "\t\tcontrol";
     } else if (!o) {
         out << ", " << endl;
         out << "\t\tnoncreatable";
     }
     out << endl;
     out << "\t]" << endl;
     out << "\tcoclass " << cleanClassName << endl;
     out << "\t{" << endl;
     out << "\t\t[default] dispinterface I" << cleanClassName << ';' << endl;
     if (hasEvents)
         out << "\t\t[default, source] dispinterface I" << cleanClassName << "Events;" << endl;
     out << "\t};" << endl;
     return S_OK;
 }
convertTypes()
static QByteArray convertTypes (const QByteArray & qtype, bool * ok) static
Definition at line 494 of file qaxserver.cpp.
Referenced by classIDL(), and prototype().
 {
     qRegisterMetaType("IDispatch*", (void**)0);
     qRegisterMetaType("IUnknown*", (void**)0);
     *ok = false;
     int i = 0;
     while (type_map[i][0]) {
         if (qtype == type_map[i][0] && type_map[i][1]) {
             *ok = true;
             return type_map[i][1];
         }
         ++i;
     }
     if (enums.contains(qtype)) {
         *ok = true;
         return "enum " + qtype;
     }
     if (subtypes.contains(qtype)) {
         *ok = true;
     } else if (qtype.endsWith('*')) {
         QByteArray cleanType = qtype.left(qtype.length() - 1);
         const QMetaObject *mo = qAxFactory()->metaObject(QString::fromLatin1(cleanType.constData()));
         if (mo) {
             cleanType = qax_clean_type(QString::fromLatin1(cleanType), mo).toLatin1();
             if (subtypes.contains(cleanType)) {
                 *ok = true;
                 return cleanType + '*';
             }
         }
     }
     return qtype;
 }
DumpIDL()
HRESULT __stdcall DumpIDL (const QString & outfile, const QString & ver)
Definition at line 1062 of file qaxserver.cpp.
Referenced by classIDL(), and WinMain().
 {
     qAxIsServer = false;
     QTextStream out;
     if (outfile.contains(QLatin1String("\\"))) {
         QString outpath = outfile.left(outfile.lastIndexOf(QLatin1String("\\")));
         QDir dir;
         dir.mkpath(outpath);
     }
     QFile file(outfile);
     file.remove();
     QString filebase = QString::fromWCharArray(qAxModuleFilename);
     filebase = filebase.left(filebase.lastIndexOf(QLatin1Char('.')));
     QString appID = qAxFactory()->appID().toString().toUpper();
     if (QUuid(appID).isNull())
         return 1;
     STRIPCB(appID);
     QString typeLibID = qAxFactory()->typeLibID().toString().toUpper();
     if (QUuid(typeLibID).isNull())
         return 2;
     STRIPCB(typeLibID);
     QString typelib = filebase.right(filebase.length() - filebase.lastIndexOf(QLatin1String("\\"))-1);
     if (!file.open(QIODevice::WriteOnly))
         return -1;
     out.setDevice(&file);
     QString version(ver.unicode(), ver.length());
     while (version.count(QLatin1Char('.')) > 1) {
         int lastdot = version.lastIndexOf(QLatin1Char('.'));
         version = version.left(lastdot) + version.right(version.length() - lastdot - 1);
     }
     if (version.isEmpty())
         version = QLatin1String("1.0");
     QString idQRect(QUuid(CLSID_QRect).toString());
     STRIPCB(idQRect);
     QString idQSize(QUuid(CLSID_QSize).toString());
     STRIPCB(idQSize);
     QString idQPoint(QUuid(CLSID_QPoint).toString());
     STRIPCB(idQPoint);
     out << "/****************************************************************************" << endl;
     out << "** Interface definition generated for ActiveQt project" << endl;
     out << "**" << endl;
     out << "**     '" << QString::fromWCharArray(qAxModuleFilename) << '\'' << endl;
     out << "**" << endl;
     out << "** Created:  " << QDateTime::currentDateTime().toString() << endl;
     out << "**" << endl;
     out << "** WARNING! All changes made in this file will be lost!" << endl;
     out << "****************************************************************************/" << endl << endl;
     out << "import \"ocidl.idl\";" << endl;
     out << "#include <olectl.h>" << endl << endl;
     // dummy application to create widgets
     bool delete_qApp = false;
     if (!qApp) {
         int argc;
         (void)new QApplication(argc, 0);
         delete_qApp = true;
     }
     out << '[' << endl;
     out << "\tuuid(" << typeLibID << ")," << endl;
     out << "\tversion(" << version << ")," << endl;
     out << "\thelpstring(\"" << typelib << ' ' << version << " Type Library\")" << endl;
     out << ']' << endl;
     out << "library " << typelib << "Lib" << endl;
     out << '{' << endl;
     out << "\timportlib(\"stdole32.tlb\");" << endl;
     out << "\timportlib(\"stdole2.tlb\");" << endl << endl;
     QStringList keys = qAxFactory()->featureList();
     QStringList::ConstIterator key;
     out << "\t/************************************************************************" << endl;
     out << "\t** If this causes a compile error in MIDL you need to upgrade the" << endl;
     out << "\t** Platform SDK you are using. Download the SDK from msdn.microsoft.com" << endl;
     out << "\t** and make sure that both the system and the Visual Studio environment" << endl;
     out << "\t** use the correct files." << endl;
     out << "\t**" << endl;
 #ifndef Q_CC_BOR
 #if __REQUIRED_RPCNDR_H_VERSION__ < Q_REQUIRED_RPCNDR_H_VERSION
     out << "\t** Required version of MIDL could not be verified. QRect, QSize and QPoint" << endl;
     out << "\t** support needs an updated Platform SDK to be installed." << endl;
     out << "\t*************************************************************************" << endl;
 #else
     out << "\t************************************************************************/" << endl;
 #endif
     out << endl;
     out << "\t[uuid(" << idQRect << ")]" << endl;
     out << "\tstruct QRect {" << endl;
     out << "\t\tint left;" << endl;
     out << "\t\tint top;" << endl;
     out << "\t\tint right;" << endl;
     out << "\t\tint bottom;" << endl;
     out << "\t};" << endl << endl;
     out << "\t[uuid(" << idQSize << ")]" << endl;
     out << "\tstruct QSize {" << endl;
     out << "\t\tint width;" << endl;
     out << "\t\tint height;" << endl;
     out << "\t};" << endl << endl;
     out << "\t[uuid(" << idQPoint << ")]" << endl;
     out << "\tstruct QPoint {" << endl;
     out << "\t\tint x;" << endl;
     out << "\t\tint y;" << endl;
     out << "\t};" << endl;
 #if __REQUIRED_RPCNDR_H_VERSION__ < Q_REQUIRED_RPCNDR_H_VERSION
     out << "\t*/" << endl;
 #endif
 #else
     out << "\t** Custom data types not supported with Borland." << endl;
     out << "\t*************************************************************************" << endl;
 #endif
     out << endl;
     out << "\t/* Forward declaration of classes that might be used as parameters */" << endl << endl;
     int res = S_OK;
     for (key = keys.begin(); key != keys.end(); ++key) {
         QByteArray className = (*key).toLatin1();
         const QMetaObject *mo = qAxFactory()->metaObject(QString::fromLatin1(className.constData()));
         // We have meta object information for this type. Forward declare it.
         if (mo) {
             QByteArray cleanType = qax_clean_type(*key, mo).toLatin1();
             out << "\tcoclass " << cleanType << ';' << endl;
             subtypes.append(cleanType);
             qRegisterMetaType(cleanType, (void**)0);
             cleanType += '*';
             subtypes.append(cleanType);
             qRegisterMetaType(cleanType, (void**)0);
         }
     }
     out << endl;
     for (key = keys.begin(); key != keys.end(); ++key) {
         QByteArray className = (*key).toLatin1();
         const QMetaObject *mo = qAxFactory()->metaObject(QString::fromLatin1(className.constData()));
         // We have meta object information for this type. Define it.
         if (mo) {
             QObject *o = qAxFactory()->createObject(QString::fromLatin1(className.constData()));
             // It's not a control class, so it is actually a subtype. Define it.
             if (!o)
                 res = classIDL(0, mo, QString::fromLatin1(className), false, out);
             delete o;
         }
     }
     out << endl;
     if (res != S_OK)
         goto ErrorInClass;
     for (key = keys.begin(); key != keys.end(); ++key) {
         QByteArray className = (*key).toLatin1();
         QObject *o = qAxFactory()->createObject(QString::fromLatin1(className.constData()));
         if (!o)
             continue;
         const QMetaObject *mo = o->metaObject();
         QAxBindable *bind = (QAxBindable*)o->qt_metacast("QAxBindable");
         bool isBindable =  bind != 0;
         QByteArray cleanType = qax_clean_type(*key, mo).toLatin1();
         subtypes.append(cleanType);
         subtypes.append(cleanType + '*');
         res = classIDL(o, mo, QString::fromLatin1(className.constData()), isBindable, out);
         delete o;
         if (res != S_OK)
             break;
     }
     out << "};" << endl;
     out.flush();
 ErrorInClass:
     if (delete_qApp)
         delete qApp;
     if (res != S_OK) {
         file.close();
         file.remove();
     }
     return res;
 }
ignore()
static bool ignore (const char * test, const char *const * table) static
Definition at line 660 of file qaxserver.cpp.
Referenced by QGridLayoutRowData::calculateGeometries(), QGridLayoutRowData::dump(), QMainWindow::event(), ignoreProps(), ignoreSlots(), QTextEngine::itemize(), QDeclarativeTextInput::keyPressEvent(), QGridLayoutRowData::reset(), QWSCalibratedMouseHandler::sendFiltered(), QNetworkSessionPrivate::setALREnabled(), QScriptDebuggerBackend::setIgnoreExceptions(), QDeclarativeConnections::setIgnoreUnknownSignals(), QTextControl::setIgnoreUnusedNavigationEvents(), QBoxLayoutPrivate::setupGeom(), QGridLayoutRowData::stealBox(), QTextControl::toHtml(), QGridLayoutRowData::totalBox(), and QNetworkSessionPrivateImpl::~QNetworkSessionPrivateImpl().
 {
     if (!test)
         return true;
     int i = 0;
     while (table[i]) {
         if (!strcmp(test, table[i]))
             return true;
         ++i;
     }
     return false;
 }
ignoreProps()
bool ignoreProps (const char * test)
Definition at line 678 of file qaxserver.cpp.
Referenced by classIDL(), QAxServerBase::isPropertyExposed(), and QAxServerBase::removeMenu().
 {
     return ignore(test, ignore_props);
 }
ignoreSlots()
bool ignoreSlots (const char * test)
Definition at line 673 of file qaxserver.cpp.
Referenced by classIDL(), and QAxServerBase::removeMenu().
 {
     return ignore(test, ignore_slots);
 }
prototype()
static QByteArray prototype (const QList< QByteArray > & parameterTypes, const QList< QByteArray > & parameterNames, bool * ok) static
Definition at line 685 of file qaxserver.cpp.
Referenced by MetaObjectGenerator::addSetterSlot(), MetaObjectGenerator::addSignal(), MetaObjectGenerator::addSlot(), QScriptObjectSnapshot::capture(), classIDL(), QScriptEnginePrivate::create(), MetaObjectGenerator::createPrototype(), QScriptEngine::fromScriptValue(), QScriptEnginePrivate::get(), QAxServerBase::Invoke(), MetaObjectGenerator::metaObject(), namedPrototype(), QScriptEngine::newFunction(), MetaObjectGenerator::paramList(), QDBusMetaObjectGenerator::parseMethods(), QDBusMetaObjectGenerator::parseSignals(), QScriptEnginePrivate::pushContext(), qax_generateDocumentation(), qScriptRegisterMetaType(), qScriptRegisterSequenceMetaType(), qt_add_qmlxmlhttprequest(), MetaObjectGenerator::readEventInterface(), MetaObjectGenerator::readFuncsInfo(), QScriptEnginePrivate::setDefaultPrototype(), QGL2PaintEngineEx::state(), QVGPaintEngine::state(), and QAxMetaObject::~QAxMetaObject().
 {
     QByteArray prototype;
     for (int p = 0; p < parameterTypes.count() && *ok; ++p) {
         bool out = false;
         QByteArray type(parameterTypes.at(p));
         QByteArray name(parameterNames.at(p));
         if (type.endsWith('&')) {
             out = true;
             type.truncate(type.length() - 1);
         } else if (type.endsWith("**")) {
             out = true;
             type.truncate(type.length() - 1);
         } else if (type.endsWith('*') && !subtypes.contains(type)) {
             type.truncate(type.length() - 1);
         }
         if (type.isEmpty()) {
             *ok = false;
             break;
         }
         type = convertTypes(type, ok);
         if (!out)
             prototype += "[in] " + type + ' ';
         else
             prototype += "[in,out] " + type + ' ';
         if (out)
             prototype += '*';
         if (name.isEmpty())
             prototype += 'p' + QByteArray::number(p);
         else
             prototype += "p_" + replaceKeyword(name);
         if (p < parameterTypes.count() - 1)
             prototype += ", ";
     }
     return prototype;
 }
qax_clean_type()
QString qax_clean_type (const QString & type, const QMetaObject * mo)
Definition at line 191 of file qaxserver.cpp.
Referenced by classIDL(), and convertTypes().
 {
     if (mo) {
         int classInfoIdx = mo->indexOfClassInfo("CoClassAlias");
         if (classInfoIdx != -1) {
             const QMetaClassInfo classInfo = mo->classInfo(classInfoIdx);
             return QLatin1String(classInfo.value());
         }
     }
     QString alias(type);
     alias.remove(QLatin1String("::"));
     return alias;
 }
qax_instantiate()
QAxFactory* qax_instantiate ()
Referenced by qAxFactory().
qax_shutDown()
void qax_shutDown ()
Definition at line 117 of file qaxservermain.cpp.
Referenced by qAxUnlock().
 {
     qAxActivity = true;
     if (hEventShutdown)
         SetEvent(hEventShutdown); // tell monitor that we transitioned to zero
 }
qAxCleanup()
void qAxCleanup ()
Definition at line 139 of file qaxserver.cpp.
Referenced by DllMain(), and WinMain().
 {
     if (!initCount)
         qWarning("qAxInit/qAxCleanup mismatch");
     if (--initCount)
         return;
     delete qax_factory;
     qax_factory = 0;
     if (qAxTypeLibrary) {
         qAxTypeLibrary->Release();
         qAxTypeLibrary = 0;
     }
     DeleteCriticalSection(&qAxModuleSection);
 }
qAxFactory()
QAxFactory* qAxFactory ()
Definition at line 81 of file qaxserver.cpp.
Referenced by classIDL(), convertTypes(), QClassFactory::CreateInstance(), QClassFactory::CreateInstanceHelper(), QClassFactory::CreateInstanceLic(), DumpIDL(), QAxServerBase::ensureMetaData(), QAxServerBase::EnumVerbs(), QAxServerBase::GetClassID(), QAxServerBase::GetClassInfo(), QAxServerBase::GetGUID(), QClassFactory::GetLicInfo(), QAxServerBase::GetMiscStatus(), QAxServerBase::GetUserClassID(), QAxServerBase::internalConnect(), QAxServerBase::internalCreate(), QAxServerBase::InternalQueryInterface(), qax_create_object_wrapper(), qax_startServer(), qax_stopServer(), QClassFactory::QClassFactory(), QAxServerBase::qt_metacall(), QVariantToVARIANT(), QAxFactory::registerActiveObject(), QAxServerBase::registerActiveObject(), QClassFactory::RequestLicKey(), and UpdateRegistry().
 {
     if (!qax_factory) {
         bool hadQApp = qApp != 0;
         qax_factory = qax_instantiate();
         // QAxFactory created a QApplication
         if (!hadQApp && qApp)
             qax_ownQApp = true;
         // register all types with metatype system as pointers
         QStringList keys(qax_factory->featureList());
         for (int i = 0; i < keys.count(); ++i) {
             QString key(keys.at(i));
             qRegisterMetaType((key + QLatin1Char('*')).toLatin1(), (void**)(quintptr)-1);
         }
     }
     return qax_factory;
 }
qAxInit()
QString qAxInit ()
Definition at line 111 of file qaxserver.cpp.
Referenced by DllMain(), UpdateRegistry(), and WinMain().
 {
     static QString libFile;
     if (initCount++)
         return libFile;
     InitializeCriticalSection(&qAxModuleSection);
     libFile = QString::fromWCharArray(qAxModuleFilename);
     libFile = libFile.toLower();
     if (LoadTypeLibEx((wchar_t*)libFile.utf16(), REGKIND_NONE, &qAxTypeLibrary) == S_OK)
         return libFile;
     int lastDot = libFile.lastIndexOf(QLatin1Char('.'));
     libFile = libFile.left(lastDot) + QLatin1String(".tlb");
     if (LoadTypeLibEx((wchar_t*)libFile.utf16(), REGKIND_NONE, &qAxTypeLibrary) == S_OK)
         return libFile;
     lastDot = libFile.lastIndexOf(QLatin1Char('.'));
     libFile = libFile.left(lastDot) + QLatin1String(".olb");
     if (LoadTypeLibEx((wchar_t*)libFile.utf16(), REGKIND_NONE, &qAxTypeLibrary) == S_OK)
         return libFile;
     libFile = QString();
     return libFile;
 }
qAxLock()
unsigned long qAxLock ()
Definition at line 158 of file qaxserver.cpp.
Referenced by QAxServerBase::init(), and QClassFactory::LockServer().
 {
     EnterCriticalSection(&qAxModuleSection);
     unsigned long ref = ++qAxModuleRef;
     LeaveCriticalSection(&qAxModuleSection);
     return ref;
 }
qAxLockCount()
unsigned long qAxLockCount ()
Definition at line 180 of file qaxserver.cpp.
Referenced by DllCanUnloadNow(), and MonitorProc().
 {
     return qAxModuleRef;
 }
qAxUnlock()
unsigned long qAxUnlock ()
Definition at line 166 of file qaxserver.cpp.
Referenced by QClassFactory::LockServer(), and QAxServerBase::~QAxServerBase().
 {
     if (!initCount) // cleaned up already
         return 0;
     EnterCriticalSection(&qAxModuleSection);
     unsigned long ref = --qAxModuleRef;
     LeaveCriticalSection(&qAxModuleSection);
     if (!ref)
         qax_shutDown();
     return ref;
 }
renameOverloads()
static QByteArray renameOverloads (const QByteArray & name) static
Definition at line 579 of file qaxserver.cpp.
Referenced by classIDL().
 {
     QByteArray newName = name;
     int n = mapping.value(name);
     if (mapping.contains(name)) {
         int n = mapping.value(name);
         newName = name + '_' + QByteArray::number(n);
         mapping.insert(name, n+1);
     } else {
         mapping.insert(name, 1);
     }
     return newName;
 }
replaceKeyword()
static QByteArray replaceKeyword (const QByteArray & name) static
Definition at line 566 of file qaxserver.cpp.
Referenced by classIDL(), and prototype().
 {
     int i = 0;
     while (keyword_map[i][0]) {
         if (name == keyword_map[i][0] && keyword_map[i][1])
             return keyword_map[i][1];
         ++i;
     }
     return name;
 }
UpdateRegistry()
HRESULT UpdateRegistry (BOOL bRegister)
Definition at line 208 of file qaxserver.cpp.
Referenced by WinMain().
 {
     qAxIsServer = false;
     QString file = QString::fromWCharArray(qAxModuleFilename);
     QString path = file.left(file.lastIndexOf(QLatin1Char('\\'))+1);
     QString module = file.right(file.length() - path.length());
     module = module.left(module.lastIndexOf(QLatin1Char('.')));
     const QString appId = qAxFactory()->appID().toString().toUpper();
     const QString libId = qAxFactory()->typeLibID().toString().toUpper();
     QString libFile = qAxInit();
     QString typeLibVersion;
     TLIBATTR *libAttr = 0;
     if (qAxTypeLibrary)
         qAxTypeLibrary->GetLibAttr(&libAttr);
     if (!libAttr)
         return SELFREG_E_TYPELIB;
     DWORD major = libAttr->wMajorVerNum;
     DWORD minor = libAttr->wMinorVerNum;
     typeLibVersion = QString::number((uint)major) + QLatin1Char('.') + QString::number((uint)minor);
     if (bRegister)
         RegisterTypeLib(qAxTypeLibrary, (wchar_t*)libFile.utf16(), 0);
     else
         UnRegisterTypeLib(libAttr->guid, libAttr->wMajorVerNum, libAttr->wMinorVerNum, libAttr->lcid, libAttr->syskind);
     qAxTypeLibrary->ReleaseTLibAttr(libAttr);
     if (typeLibVersion.isEmpty())
         typeLibVersion = QLatin1String("1.0");
     // check whether the user has permission to write to HKLM\Software\Classes
     // if not, use HKCU\Software\Classes
     QString keyPath(QLatin1String("HKEY_LOCAL_MACHINE\\Software\\Classes"));
     QSettings test(keyPath, QSettings::NativeFormat);
     if (!test.isWritable())
         keyPath = QLatin1String("HKEY_CURRENT_USER\\Software\\Classes");
     QSettings settings(keyPath, QSettings::NativeFormat);
     // we try to create the ActiveX widgets later on...
     bool delete_qApp = false;
     if (!qApp) {
         int argc = 0;
         (void)new QApplication(argc, 0);
         delete_qApp = true;
     }
     if (bRegister) {
         if (qAxOutProcServer) {
             settings.setValue(QLatin1String("/AppID/") + appId + QLatin1String("/."), module);
             settings.setValue(QLatin1String("/AppID/") + module + QLatin1String(".EXE/AppID"), appId);
         }
         QStringList keys = qAxFactory()->featureList();
         for (QStringList::Iterator key = keys.begin(); key != keys.end(); ++key) {
             QString className = *key;
             QObject *object = qAxFactory()->createObject(className);
             const QMetaObject *mo = qAxFactory()->metaObject(className);
             const QString classId = qAxFactory()->classID(className).toString().toUpper();
             className = qax_clean_type(className, mo);
             if (object) { // don't register subobject classes
                 QString classVersion = mo ? QString::fromLatin1(mo->classInfo(mo->indexOfClassInfo("Version")).value()) : QString();
                 if (classVersion.isNull())
                     classVersion = QLatin1String("1.0");
                 bool insertable = mo && !qstricmp(mo->classInfo(mo->indexOfClassInfo("Insertable")).value(), "yes");
                 bool control = object->isWidgetType();
                 const QString classMajorVersion = classVersion.left(classVersion.indexOf(QLatin1Char('.')));
                 uint olemisc = OLEMISC_SETCLIENTSITEFIRST
                     |OLEMISC_ACTIVATEWHENVISIBLE
                     |OLEMISC_INSIDEOUT
                     |OLEMISC_CANTLINKINSIDE
                     |OLEMISC_RECOMPOSEONRESIZE;
                 if (!control)
                     olemisc |= OLEMISC_INVISIBLEATRUNTIME;
                 else if (object->findChild<QMenuBar*>() && !qax_disable_inplaceframe)
                     olemisc |= OLEMISC_WANTSTOMENUMERGE;
                 settings.setValue(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion + QLatin1String("/."), className + QLatin1String(" Class"));
                 settings.setValue(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion + QLatin1String("/CLSID/."), classId);
                 if (insertable)
                     settings.setValue(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion + QLatin1String("/Insertable/."), QVariant(QLatin1String("")));
                 settings.setValue(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1String("/."), className + QLatin1String(" Class"));
                 settings.setValue(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1String("/CLSID/."), classId);
                 settings.setValue(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1String("/CurVer/."), module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion);
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/."), className + QLatin1String(" Class"));
                 if (file.endsWith(QLatin1String("exe"), Qt::CaseInsensitive))
                     settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/AppID"), appId);
                 if (control)
                     settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/Control/."), QVariant(QLatin1String("")));
                 if (insertable)
                     settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/Insertable/."), QVariant(QLatin1String("")));
                 if (file.right(3).toLower() == QLatin1String("dll"))
                     settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/InProcServer32/."), file);
                 else
                     settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/LocalServer32/."),
                                       QLatin1Char('\"') + file + QLatin1String("\" -activex"));
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/MiscStatus/."), control ? QLatin1String("1") : QLatin1String("0"));
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/MiscStatus/1/."), QString::number(olemisc));
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/Programmable/."), QVariant(QLatin1String("")));
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/ToolboxBitmap32/."), QLatin1Char('\"') +
                                   file + QLatin1String("\", 101"));
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/TypeLib/."), libId); settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/Version/."), classVersion);
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/VersionIndependentProgID/."), module + QLatin1Char('.') + className);
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/ProgID/."), module + QLatin1Char('.') + className + QLatin1Char('.') + classVersion.left(classVersion.indexOf(QLatin1Char('.'))));
                 QString mime = QLatin1String(mo->classInfo(mo->indexOfClassInfo("MIME")).value());
                 if (!mime.isEmpty()) {
                     QStringList mimeTypes = mime.split(QLatin1Char(';'));
                     for (int m = 0; m < mimeTypes.count(); ++m) {
                         mime = mimeTypes.at(m);
                         if (mime.isEmpty())
                             continue;
                         QString extension;
                         while (mime.contains(QLatin1Char(':'))) {
                             extension = mime.mid(mime.lastIndexOf(QLatin1Char(':')) + 1);
                             mime = mime.left(mime.length() - extension.length() - 1);
                             // Prepend '.' before extension, if required.
                             extension = extension.trimmed();
                             if (extension[0] != QLatin1Char('.'))
                                 extension = QLatin1Char('.') + extension;
                         }
                         if (!extension.isEmpty()) {
                             settings.setValue(QLatin1Char('/') + extension + QLatin1String("/."), module + QLatin1Char('.') + className);
                             settings.setValue(QLatin1Char('/') + extension + QLatin1String("/Content Type"), mime);
                             mime = mime.replace(QLatin1Char('/'), QLatin1Char('\\'));
                             settings.setValue(QLatin1String("/MIME/Database/Content Type/") + mime + QLatin1String("/CLSID"), classId);
                             settings.setValue(QLatin1String("/MIME/Database/Content Type/") + mime + QLatin1String("/Extension"), extension);
                         }
                     }
                 }
                 delete object;
             }
             qAxFactory()->registerClass(*key, &settings);
         }
     } else {
         if (qAxOutProcServer) {
             settings.remove(QLatin1String("/AppID/") + appId + QLatin1String("/."));
             settings.remove(QLatin1String("/AppID/") + module + QLatin1String(".EXE"));
         }
         QStringList keys = qAxFactory()->featureList();
         for (QStringList::Iterator key = keys.begin(); key != keys.end(); ++key) {
             QString className = *key;
             const QMetaObject *mo = qAxFactory()->metaObject(className);
             const QString classId = qAxFactory()->classID(className).toString().toUpper();
             className = qax_clean_type(className, mo);
             QString classVersion = mo ? QString::fromLatin1(mo->classInfo(mo->indexOfClassInfo("Version")).value()) : QString();
             if (classVersion.isNull())
                 classVersion = QLatin1String("1.0");
             const QString classMajorVersion = classVersion.left(classVersion.indexOf(QLatin1Char('.')));
             qAxFactory()->unregisterClass(*key, &settings);
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion + QLatin1String("/CLSID/."));
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion + QLatin1String("/Insertable/."));
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion + QLatin1String("/."));
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion);
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1String("/CLSID/."));
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1String("/CurVer/."));
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1String("/."));
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className);
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/AppID"));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/Control/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/Insertable/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/InProcServer32/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/LocalServer32/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/MiscStatus/1/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/MiscStatus/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/Programmable/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/ToolboxBitmap32/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/TypeLib/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/Version/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/VersionIndependentProgID/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/ProgID/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/."));
             settings.remove(QLatin1String("/CLSID/") + classId);
             QString mime = QLatin1String(mo->classInfo(mo->indexOfClassInfo("MIME")).value());
             if (!mime.isEmpty()) {
                 QStringList mimeTypes = mime.split(QLatin1Char(';'));
                 for (int m = 0; m < mimeTypes.count(); ++m) {
                     mime = mimeTypes.at(m);
                     if (mime.isEmpty())
                         continue;
                     QString extension;
                     while (mime.contains(QLatin1Char(':'))) {
                         extension = mime.mid(mime.lastIndexOf(QLatin1Char(':')) + 1);
                         mime = mime.left(mime.length() - extension.length() - 1);
                         // Prepend '.' before extension, if required.
                         extension = extension.trimmed();
                         if (extension[0] != QLatin1Char('.'))
                             extension.prepend(QLatin1Char('.'));
                     }
                     if (!extension.isEmpty()) {
                         settings.remove(QLatin1Char('/') + extension + QLatin1String("/Content Type"));
                         settings.remove(QLatin1Char('/') + extension + QLatin1String("/."));
                         settings.remove(QLatin1Char('/') + extension);
                         mime.replace(QLatin1Char('/'), QLatin1Char('\\'));
                         settings.remove(QLatin1String("/MIME/Database/Content Type/") + mime + QLatin1String("/Extension"));
                         settings.remove(QLatin1String("/MIME/Database/Content Type/") + mime + QLatin1String("/CLSID"));
                         settings.remove(QLatin1String("/MIME/Database/Content Type/") + mime + QLatin1String("/."));
                         settings.remove(QLatin1String("/MIME/Database/Content Type/") + mime);
                     }
                 }
             }
         }
     }
     if (delete_qApp)
         delete qApp;
     qAxCleanup();
     if (settings.status() == QSettings::NoError)
         return S_OK;
     return SELFREG_E_CLASS;
 }
Variable Documentation
CLSID_QPoint
CLSID CLSID_QPoint
Referenced by DumpIDL(), QVariantToVARIANT(), and VARIANTToQVariant().
CLSID_QRect
CLSID CLSID_QRect
Referenced by DumpIDL(), QVariantToVARIANT(), and VARIANTToQVariant().
CLSID_QSize
CLSID CLSID_QSize
Referenced by DumpIDL(), QVariantToVARIANT(), and VARIANTToQVariant().
enums
QList<QByteArray> enums static
Definition at line 443 of file qaxserver.cpp.
Referenced by QPatternist::yyparse().
enumValues
QList<QByteArray> enumValues static
Definition at line 444 of file qaxserver.cpp.
ignore_props
const char* const ignore_props[] static
Definition at line 596 of file qaxserver.cpp.
Referenced by ignoreProps().
ignore_slots
const char* const ignore_slots[] static
Initial value:
=
{
    "deleteLater",
    "setMouseTracking",
    "update",
    "repaint",
    "iconify",
    "showMinimized",
    "showMaximized",
    "showFullScreen",
    "showNormal",
    "polish",
    "constPolish",
    "stackUnder",
    "setShown",
    "setHidden",
    "move_1",
    "resize_1",
    "setGeometry_1",
    0
}
Definition at line 638 of file qaxserver.cpp.
Referenced by ignoreSlots().
initCount
int initCount = 0 static
Definition at line 109 of file qaxserver.cpp.
Referenced by qAxCleanup(), qAxInit(), and qAxUnlock().
keyword_map
const char* const keyword_map[][2] static
Definition at line 529 of file qaxserver.cpp.
Referenced by replaceKeyword().
mapping
QMap<QByteArray, int> mapping static
Definition at line 577 of file qaxserver.cpp.
Referenced by fontFile(), QFSFileEnginePrivate::map(), mapToLowerCase(), qt_mac_to_pascal_string(), and QFSFileEnginePrivate::unmap().
qax_disable_inplaceframe
bool qax_disable_inplaceframe
Definition at line 3814 of file qaxserverbase.cpp.
Referenced by QAxServerBase::internalActivate(), and qAxLockCount().
qax_factory
QAxFactory* qax_factory = 0 static
Definition at line 71 of file qaxserver.cpp.
Referenced by qAxCleanup(), and qAxFactory().
qax_ownQApp
bool qax_ownQApp
Definition at line 50 of file qaxserverdll.cpp.
Referenced by qAxFactory().
qAxInstance
HANDLE qAxInstance = 0
Definition at line 65 of file qaxserver.cpp.
Referenced by QAxServerBase::create(), DllMain(), and WinMain().
qAxIsServer
bool qAxIsServer = false
Definition at line 64 of file qaxserver.cpp.
Referenced by DllMain(), DumpIDL(), QAxFactory::hasStockEvents(), QAxFactory::isServer(), qax_startServer(), qax_stopServer(), and UpdateRegistry().
qAxModuleFilename
wchar_t qAxModuleFilename[MAX_PATH]
Definition at line 67 of file qaxserver.cpp.
Referenced by DllMain(), DumpIDL(), qAxInit(), QAxFactory::registerActiveObject(), QAxFactory::serverDirPath(), QAxFactory::serverFilePath(), UpdateRegistry(), QAxFactory::validateLicenseKey(), and WinMain().
qAxModuleRef
unsigned long qAxModuleRef = 0 static
Definition at line 101 of file qaxserver.cpp.
Referenced by qAxLock(), qAxLockCount(), and qAxUnlock().
qAxModuleSection
CRITICAL_SECTION qAxModuleSection static
Definition at line 102 of file qaxserver.cpp.
Referenced by qAxCleanup(), qAxInit(), qAxLock(), and qAxUnlock().
qAxOutProcServer
bool qAxOutProcServer = false
Definition at line 68 of file qaxserver.cpp.
Referenced by QClassFactory::CreateInstanceHelper(), QAxServerBase::registerActiveObject(), QAxServerBase::TranslateAcceleratorW(), and WinMain().
qAxTypeLibrary
ITypeLib* qAxTypeLibrary = 0
Definition at line 66 of file qaxserver.cpp.
Referenced by QAxServerBase::ensureMetaData(), QAxServerBase::GetClassInfo(), QAxServerBase::GetIDsOfNames(), QAxServerBase::GetTypeInfo(), QAxServerBase::GetTypeInfoCount(), qAxCleanup(), qAxInit(), QAxServerBase::qt_metacall(), QVariantToVARIANT(), and UpdateRegistry().
subtypes
QList<QByteArray> subtypes static
Definition at line 445 of file qaxserver.cpp.
type_map
const char* const type_map[][2] static
Definition at line 447 of file qaxserver.cpp.
Referenced by convertTypes().