Qt 4.8: /src/activeqt/control/qaxserverbase.cpp File Reference
qaxserverbase.cpp File Reference
#include <qabstracteventdispatcher.h>
#include <qapplication.h>
#include <qbuffer.h>
#include <qdatastream.h>
#include <qdebug.h>
#include <qevent.h>
#include <qeventloop.h>
#include <qfile.h>
#include <qpointer.h>
#include <qhash.h>
#include <qmap.h>
#include <qmenubar.h>
#include <qmenu.h>
#include <qmetaobject.h>
#include <qpixmap.h>
#include <qstatusbar.h>
#include <qwhatsthis.h>
#include <ocidl.h>
#include <olectl.h>
#include <private/qcoreapplication_p.h>
#include "qaxfactory.h"
#include "qaxbindable.h"
#include "qaxaggregated.h"
#include "../shared/qaxtypes.h"
Classes
class HackWidget
class QAxConnection
struct QAxExceptInfo
class QAxServerAggregate
class QAxServerBase
class QAxSignalVec
class QClassFactory
Macros
#define QT_NO_CAST_TO_ASCII
#define ULONG_PTR DWORD
Functions
LRESULT QT_WIN_CALLBACK axs_FilterProc (int nCode, WPARAM wParam, LPARAM lParam)
static bool checkHRESULT (HRESULT hres)
HRESULT GetClassObject (REFIID clsid, REFIID iid, void **ppUnk)
bool ignoreProps (const char *test)
bool ignoreSlots (const char *test)
static int mapModifiers (int state)
static QByteArray paramType (const QByteArray &ptype, bool *out)
bool qax_winEventFilter (void *message)
QAxFactory * qAxFactory ()
unsigned long qAxLock ()
unsigned long qAxUnlock ()
static LPOLESTR QStringToOLESTR (const QString &qstring)
bool qt_sendSpontaneousEvent (QObject *, QEvent *)
Q_GUI_EXPORT int qt_translateKeyCode (int)
void qWinMsgHandler (QtMsgType t, const char *str)
Variables
static int invokeCount = 0
bool qax_disable_inplaceframe = true
HHOOK qax_hhook
bool qax_ownQApp
HANDLE qAxInstance
bool qAxOutProcServer
unsigned long qaxserverbase_instance_count = 0
ITypeLib * qAxTypeLibrary
Macro Definition Documentation
QT_NO_CAST_TO_ASCII
#define QT_NO_CAST_TO_ASCII
disables automatic conversion from QString to 8-bit strings (char *)
See also
QT_NO_CAST_FROM_ASCII, QT_NO_CAST_FROM_BYTEARRAY
ULONG_PTR
#define ULONG_PTR DWORD
Definition at line 77 of file qaxserverbase.cpp.
Referenced by qt_adopted_thread_watcher_function(), and QAxServerBase::reportError().
Function Documentation
axs_FilterProc()
LRESULT QT_WIN_CALLBACK axs_FilterProc (int nCode, WPARAM wParam, LPARAM lParam)
Definition at line 799 of file qaxserverbase.cpp.
Referenced by QClassFactory::CreateInstanceHelper().
 {
     if (qApp && !invokeCount)
         qApp->sendPostedEvents();
     return CallNextHookEx(qax_hhook, nCode, wParam, lParam);
 }
checkHRESULT()
static bool checkHRESULT (HRESULT hres) static
Definition at line 1878 of file qaxserverbase.cpp.
 {
     const char *name = 0;
     switch(hres) {
     case S_OK:
     return true;
     case DISP_E_BADPARAMCOUNT:
 #if defined(QT_CHECK_STATE)
     qWarning("QAxBase: Error calling IDispatch member %s: Bad parameter count", name);
 #endif
     return false;
     case DISP_E_BADVARTYPE:
 #if defined(QT_CHECK_STATE)
     qWarning("QAxBase: Error calling IDispatch member %s: Bad variant type", name);
 #endif
     return false;
     case DISP_E_EXCEPTION:
 #if defined(QT_CHECK_STATE)
         qWarning("QAxBase: Error calling IDispatch member %s: Exception thrown by server", name);
 #endif
     return false;
     case DISP_E_MEMBERNOTFOUND:
 #if defined(QT_CHECK_STATE)
     qWarning("QAxBase: Error calling IDispatch member %s: Member not found", name);
 #endif
     return false;
     case DISP_E_NONAMEDARGS:
 #if defined(QT_CHECK_STATE)
     qWarning("QAxBase: Error calling IDispatch member %s: No named arguments", name);
 #endif
     return false;
     case DISP_E_OVERFLOW:
 #if defined(QT_CHECK_STATE)
     qWarning("QAxBase: Error calling IDispatch member %s: Overflow", name);
 #endif
     return false;
     case DISP_E_PARAMNOTFOUND:
 #if defined(QT_CHECK_STATE)
     qWarning("QAxBase: Error calling IDispatch member %s: Parameter not found", name);
 #endif
     return false;
     case DISP_E_TYPEMISMATCH:
 #if defined(QT_CHECK_STATE)
     qWarning("QAxBase: Error calling IDispatch member %s: Type mismatch", name);
 #endif
     return false;
     case DISP_E_UNKNOWNINTERFACE:
 #if defined(QT_CHECK_STATE)
     qWarning("QAxBase: Error calling IDispatch member %s: Unknown interface", name);
 #endif
     return false;
     case DISP_E_UNKNOWNLCID:
 #if defined(QT_CHECK_STATE)
     qWarning("QAxBase: Error calling IDispatch member %s: Unknown locale ID", name);
 #endif
     return false;
     case DISP_E_PARAMNOTOPTIONAL:
 #if defined(QT_CHECK_STATE)
     qWarning("QAxBase: Error calling IDispatch member %s: Non-optional parameter missing", name);
 #endif
     return false;
     default:
 #if defined(QT_CHECK_STATE)
     qWarning("QAxBase: Error calling IDispatch member %s: Unknown error", name);
 #endif
     return false;
     }
 }
GetClassObject()
HRESULT GetClassObject (REFIID clsid, REFIID iid, void ** ppUnk)
Definition at line 1023 of file qaxserverbase.cpp.
 {
     QClassFactory *factory = new QClassFactory(clsid);
     if (!factory)
     return E_OUTOFMEMORY;
     if (factory->className.isEmpty()) {
     delete factory;
     return E_NOINTERFACE;
     }
     HRESULT res = factory->QueryInterface(iid, ppUnk);
     if (res != S_OK)
     delete factory;
     return res;
 }
ignoreProps()
bool ignoreProps (const char * test)
Definition at line 678 of file qaxserver.cpp.
Referenced by classIDL(), QAxServerBase::isPropertyExposed(), and QAxServerBase::removeMenu().
 {
     return ignore(test, ignore_props);
 }
ignoreSlots()
bool ignoreSlots (const char * test)
Definition at line 673 of file qaxserver.cpp.
Referenced by classIDL(), and QAxServerBase::removeMenu().
 {
     return ignore(test, ignore_slots);
 }
mapModifiers()
static int mapModifiers (int state) static
Definition at line 4304 of file qaxserverbase.cpp.
Referenced by QAxServerBase::eventFilter().
 {
     int ole = 0;
     if (state & Qt::ShiftModifier)
     ole |= 1;
     if (state & Qt::ControlModifier)
     ole |= 2;
     if (state & Qt::AltModifier)
     ole |= 4;
     return ole;
 }
paramType()
static QByteArray paramType (const QByteArray & ptype, bool * out) inline static
Definition at line 1947 of file qaxserverbase.cpp.
Referenced by QAxBase::dynamicCallHelper(), QAxServerBase::Invoke(), and QAxServerBase::qt_metacall().
 {
     *out = ptype.endsWith('&') || ptype.endsWith("**");
     if (*out) {
         QByteArray res(ptype);
     res.truncate(res.length() - 1);
         return res;
     }
     return ptype;
 }
qax_winEventFilter()
bool qax_winEventFilter (void * message)
Definition at line 809 of file qaxserverbase.cpp.
Referenced by QClassFactory::CreateInstanceHelper().
 {
     MSG *pMsg = (MSG*)message;
     if (pMsg->message < WM_KEYFIRST || pMsg->message > WM_KEYLAST)
     return false;
     bool ret = false;
     QWidget *aqt = QWidget::find(pMsg->hwnd);
     if (!aqt)
     return ret;
     HWND baseHwnd = ::GetParent(aqt->winId());
     QAxServerBase *axbase = 0;
     while (!axbase && baseHwnd) {
 #ifdef GWLP_USERDATA
         axbase = (QAxServerBase*)GetWindowLongPtr(baseHwnd, GWLP_USERDATA);
 #else
         axbase = (QAxServerBase*)GetWindowLong(baseHwnd, GWL_USERDATA);
 #endif
     baseHwnd = ::GetParent(baseHwnd);
     }
     if (!axbase)
     return ret;
     HRESULT hres = axbase->TranslateAcceleratorW(pMsg);
     return hres == S_OK;
 }
qAxFactory()
QAxFactory* qAxFactory ()
Definition at line 81 of file qaxserver.cpp.
Referenced by classIDL(), convertTypes(), QClassFactory::CreateInstance(), QClassFactory::CreateInstanceHelper(), QClassFactory::CreateInstanceLic(), DumpIDL(), QAxServerBase::ensureMetaData(), QAxServerBase::EnumVerbs(), QAxServerBase::GetClassID(), QAxServerBase::GetClassInfo(), QAxServerBase::GetGUID(), QClassFactory::GetLicInfo(), QAxServerBase::GetMiscStatus(), QAxServerBase::GetUserClassID(), QAxServerBase::internalConnect(), QAxServerBase::internalCreate(), QAxServerBase::InternalQueryInterface(), QClassFactory::QClassFactory(), QAxServerBase::qt_metacall(), QAxServerBase::registerActiveObject(), QClassFactory::RequestLicKey(), and UpdateRegistry().
 {
     if (!qax_factory) {
         bool hadQApp = qApp != 0;
         qax_factory = qax_instantiate();
         // QAxFactory created a QApplication
         if (!hadQApp && qApp)
             qax_ownQApp = true;
         // register all types with metatype system as pointers
         QStringList keys(qax_factory->featureList());
         for (int i = 0; i < keys.count(); ++i) {
             QString key(keys.at(i));
             qRegisterMetaType((key + QLatin1Char('*')).toLatin1(), (void**)(quintptr)-1);
         }
     }
     return qax_factory;
 }
qAxLock()
unsigned long qAxLock ()
Definition at line 158 of file qaxserver.cpp.
Referenced by QAxServerBase::init(), and QClassFactory::LockServer().
 {
     EnterCriticalSection(&qAxModuleSection);
     unsigned long ref = ++qAxModuleRef;
     LeaveCriticalSection(&qAxModuleSection);
     return ref;
 }
qAxUnlock()
unsigned long qAxUnlock ()
Definition at line 166 of file qaxserver.cpp.
Referenced by QClassFactory::LockServer(), and QAxServerBase::~QAxServerBase().
 {
     if (!initCount) // cleaned up already
         return 0;
     EnterCriticalSection(&qAxModuleSection);
     unsigned long ref = --qAxModuleRef;
     LeaveCriticalSection(&qAxModuleSection);
     if (!ref)
         qax_shutDown();
     return ref;
 }
QStringToOLESTR()
static LPOLESTR QStringToOLESTR (const QString & qstring) inline static
Definition at line 3726 of file qaxserverbase.cpp.
Referenced by QAxServerBase::GetUserType().
 {
     LPOLESTR olestr = (wchar_t*)CoTaskMemAlloc(qstring.length()*2+2);
     memcpy(olestr, (ushort*)qstring.unicode(), qstring.length()*2);
     olestr[qstring.length()] = 0;
     return olestr;
 }
qt_sendSpontaneousEvent()
bool qt_sendSpontaneousEvent (QObject * , QEvent *)
Definition at line 5779 of file qapplication.cpp.
Referenced by QAxServerBase::resize(), QAxServerBase::SetColorScheme(), and QWSInputContext::translateIMEvent().
 {
     return QCoreApplication::sendSpontaneousEvent(receiver, event);
 }
qt_translateKeyCode()
Q_GUI_EXPORT int qt_translateKeyCode (int)
Definition at line 517 of file qkeymapper_win.cpp.
Referenced by QAxServerBase::ReactivateAndUndo(), and QAxServerBase::TranslateAcceleratorW().
 {
     int code = winceKeyBend((vk < 0 || vk > 255) ? 0 : vk);
     return code == Qt::Key_unknown ? 0 : code;
 }
qWinMsgHandler()
void qWinMsgHandler (QtMsgType t, const char * str)
Definition at line 143 of file qcoreapplication_win.cpp.
Referenced by QClassFactory::CreateInstanceHelper(), qax_winEventFilter(), qInstallMsgHandler(), qt_error_string(), and qWinMain().
 {
     Q_UNUSED(t);
     // OutputDebugString is not threadsafe.
     // cannot use QMutex here, because qWarning()s in the QMutex
     // implementation may cause this function to recurse
     static QWinMsgHandlerCriticalSection staticCriticalSection;
     if (!str)
         str = "(null)";
     staticCriticalSection.lock();
     QString s(QString::fromLocal8Bit(str));
     s += QLatin1Char('\n');
     OutputDebugString((wchar_t*)s.utf16());
     staticCriticalSection.unlock();
 }
Variable Documentation
invokeCount
int invokeCount = 0 static
Definition at line 92 of file qaxserverbase.cpp.
Referenced by axs_FilterProc(), and QAxServerBase::Invoke().
qax_disable_inplaceframe
bool qax_disable_inplaceframe = true
Definition at line 3814 of file qaxserverbase.cpp.
Referenced by QAxServerBase::internalActivate(), and qAxLockCount().
qax_hhook
HHOOK qax_hhook
Definition at line 51 of file qaxserverdll.cpp.
Referenced by axs_FilterProc(), QClassFactory::CreateInstanceHelper(), and DllCanUnloadNow().
qax_ownQApp
bool qax_ownQApp
Definition at line 50 of file qaxserverdll.cpp.
Referenced by QClassFactory::CreateInstanceHelper(), and DllCanUnloadNow().
qAxInstance
HANDLE qAxInstance
Definition at line 65 of file qaxserver.cpp.
Referenced by QAxServerBase::create().
qAxOutProcServer
bool qAxOutProcServer
Definition at line 68 of file qaxserver.cpp.
Referenced by QClassFactory::CreateInstanceHelper(), QAxServerBase::registerActiveObject(), and QAxServerBase::TranslateAcceleratorW().
qaxserverbase_instance_count
unsigned long qaxserverbase_instance_count = 0
Definition at line 95 of file qaxserverbase.cpp.
Referenced by QAxServerBase::init(), and QAxServerBase::~QAxServerBase().
qAxTypeLibrary
ITypeLib* qAxTypeLibrary
Definition at line 66 of file qaxserver.cpp.
Referenced by QAxServerBase::ensureMetaData(), QAxServerBase::GetClassInfo(), QAxServerBase::GetIDsOfNames(), QAxServerBase::GetTypeInfo(), QAxServerBase::GetTypeInfoCount(), and QAxServerBase::qt_metacall().