Qt 4.8: /src/activeqt/control/qaxservermain.cpp File Reference
qaxservermain.cpp File Reference
#include <qstringlist.h>
#include <qvector.h>
#include "qaxfactory.h"
#include <qt_windows.h>
Functions
STDAPI DumpIDL (const QString &outfile, const QString &ver)
HRESULT GetClassObject (const GUID &clsid, const GUID &iid, void **ppUnk)
int __cdecl main (int, char **)
static DWORD WINAPI MonitorProc (void *pv)
void qax_shutDown ()
bool qax_startServer (QAxFactory::ServerType type)
bool qax_stopServer ()
bool qax_winEventFilter (void *message)
void qAxCleanup ()
QString qAxInit ()
ulong qAxLockCount ()
void __cdecl qWinMain (HINSTANCE, HINSTANCE, LPSTR, int, int &, QVector< char *> &)
static bool StartMonitor ()
HRESULT UpdateRegistry (BOOL bRegister)
EXTERN_C int WINAPI WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR, int nShowCmd)
Variables
static DWORD * classRegistration = 0
QT_STATIC_CONST DWORD dwPause = 500
static DWORD dwThreadID
QT_STATIC_CONST DWORD dwTimeOut = 1000
static HANDLE hEventShutdown
static bool qAxActivity = false
HANDLE qAxInstance
bool qAxIsServer
wchar_t qAxModuleFilename [MAX_PATH]
bool qAxOutProcServer
Function Documentation
DumpIDL()
STDAPI DumpIDL (const QString & outfile, const QString & ver)
Definition at line 1062 of file qaxserver.cpp.
Referenced by classIDL(), and WinMain().
 {
     qAxIsServer = false;
     QTextStream out;
     if (outfile.contains(QLatin1String("\\"))) {
         QString outpath = outfile.left(outfile.lastIndexOf(QLatin1String("\\")));
         QDir dir;
         dir.mkpath(outpath);
     }
     QFile file(outfile);
     file.remove();
     QString filebase = QString::fromWCharArray(qAxModuleFilename);
     filebase = filebase.left(filebase.lastIndexOf(QLatin1Char('.')));
     QString appID = qAxFactory()->appID().toString().toUpper();
     if (QUuid(appID).isNull())
         return 1;
     STRIPCB(appID);
     QString typeLibID = qAxFactory()->typeLibID().toString().toUpper();
     if (QUuid(typeLibID).isNull())
         return 2;
     STRIPCB(typeLibID);
     QString typelib = filebase.right(filebase.length() - filebase.lastIndexOf(QLatin1String("\\"))-1);
     if (!file.open(QIODevice::WriteOnly))
         return -1;
     out.setDevice(&file);
     QString version(ver.unicode(), ver.length());
     while (version.count(QLatin1Char('.')) > 1) {
         int lastdot = version.lastIndexOf(QLatin1Char('.'));
         version = version.left(lastdot) + version.right(version.length() - lastdot - 1);
     }
     if (version.isEmpty())
         version = QLatin1String("1.0");
     QString idQRect(QUuid(CLSID_QRect).toString());
     STRIPCB(idQRect);
     QString idQSize(QUuid(CLSID_QSize).toString());
     STRIPCB(idQSize);
     QString idQPoint(QUuid(CLSID_QPoint).toString());
     STRIPCB(idQPoint);
     out << "/****************************************************************************" << endl;
     out << "** Interface definition generated for ActiveQt project" << endl;
     out << "**" << endl;
     out << "**     '" << QString::fromWCharArray(qAxModuleFilename) << '\'' << endl;
     out << "**" << endl;
     out << "** Created:  " << QDateTime::currentDateTime().toString() << endl;
     out << "**" << endl;
     out << "** WARNING! All changes made in this file will be lost!" << endl;
     out << "****************************************************************************/" << endl << endl;
     out << "import \"ocidl.idl\";" << endl;
     out << "#include <olectl.h>" << endl << endl;
     // dummy application to create widgets
     bool delete_qApp = false;
     if (!qApp) {
         int argc;
         (void)new QApplication(argc, 0);
         delete_qApp = true;
     }
     out << '[' << endl;
     out << "\tuuid(" << typeLibID << ")," << endl;
     out << "\tversion(" << version << ")," << endl;
     out << "\thelpstring(\"" << typelib << ' ' << version << " Type Library\")" << endl;
     out << ']' << endl;
     out << "library " << typelib << "Lib" << endl;
     out << '{' << endl;
     out << "\timportlib(\"stdole32.tlb\");" << endl;
     out << "\timportlib(\"stdole2.tlb\");" << endl << endl;
     QStringList keys = qAxFactory()->featureList();
     QStringList::ConstIterator key;
     out << "\t/************************************************************************" << endl;
     out << "\t** If this causes a compile error in MIDL you need to upgrade the" << endl;
     out << "\t** Platform SDK you are using. Download the SDK from msdn.microsoft.com" << endl;
     out << "\t** and make sure that both the system and the Visual Studio environment" << endl;
     out << "\t** use the correct files." << endl;
     out << "\t**" << endl;
 #ifndef Q_CC_BOR
 #if __REQUIRED_RPCNDR_H_VERSION__ < Q_REQUIRED_RPCNDR_H_VERSION
     out << "\t** Required version of MIDL could not be verified. QRect, QSize and QPoint" << endl;
     out << "\t** support needs an updated Platform SDK to be installed." << endl;
     out << "\t*************************************************************************" << endl;
 #else
     out << "\t************************************************************************/" << endl;
 #endif
     out << endl;
     out << "\t[uuid(" << idQRect << ")]" << endl;
     out << "\tstruct QRect {" << endl;
     out << "\t\tint left;" << endl;
     out << "\t\tint top;" << endl;
     out << "\t\tint right;" << endl;
     out << "\t\tint bottom;" << endl;
     out << "\t};" << endl << endl;
     out << "\t[uuid(" << idQSize << ")]" << endl;
     out << "\tstruct QSize {" << endl;
     out << "\t\tint width;" << endl;
     out << "\t\tint height;" << endl;
     out << "\t};" << endl << endl;
     out << "\t[uuid(" << idQPoint << ")]" << endl;
     out << "\tstruct QPoint {" << endl;
     out << "\t\tint x;" << endl;
     out << "\t\tint y;" << endl;
     out << "\t};" << endl;
 #if __REQUIRED_RPCNDR_H_VERSION__ < Q_REQUIRED_RPCNDR_H_VERSION
     out << "\t*/" << endl;
 #endif
 #else
     out << "\t** Custom data types not supported with Borland." << endl;
     out << "\t*************************************************************************" << endl;
 #endif
     out << endl;
     out << "\t/* Forward declaration of classes that might be used as parameters */" << endl << endl;
     int res = S_OK;
     for (key = keys.begin(); key != keys.end(); ++key) {
         QByteArray className = (*key).toLatin1();
         const QMetaObject *mo = qAxFactory()->metaObject(QString::fromLatin1(className.constData()));
         // We have meta object information for this type. Forward declare it.
         if (mo) {
             QByteArray cleanType = qax_clean_type(*key, mo).toLatin1();
             out << "\tcoclass " << cleanType << ';' << endl;
             subtypes.append(cleanType);
             qRegisterMetaType(cleanType, (void**)0);
             cleanType += '*';
             subtypes.append(cleanType);
             qRegisterMetaType(cleanType, (void**)0);
         }
     }
     out << endl;
     for (key = keys.begin(); key != keys.end(); ++key) {
         QByteArray className = (*key).toLatin1();
         const QMetaObject *mo = qAxFactory()->metaObject(QString::fromLatin1(className.constData()));
         // We have meta object information for this type. Define it.
         if (mo) {
             QObject *o = qAxFactory()->createObject(QString::fromLatin1(className.constData()));
             // It's not a control class, so it is actually a subtype. Define it.
             if (!o)
                 res = classIDL(0, mo, QString::fromLatin1(className), false, out);
             delete o;
         }
     }
     out << endl;
     if (res != S_OK)
         goto ErrorInClass;
     for (key = keys.begin(); key != keys.end(); ++key) {
         QByteArray className = (*key).toLatin1();
         QObject *o = qAxFactory()->createObject(QString::fromLatin1(className.constData()));
         if (!o)
             continue;
         const QMetaObject *mo = o->metaObject();
         QAxBindable *bind = (QAxBindable*)o->qt_metacast("QAxBindable");
         bool isBindable =  bind != 0;
         QByteArray cleanType = qax_clean_type(*key, mo).toLatin1();
         subtypes.append(cleanType);
         subtypes.append(cleanType + '*');
         res = classIDL(o, mo, QString::fromLatin1(className.constData()), isBindable, out);
         delete o;
         if (res != S_OK)
             break;
     }
     out << "};" << endl;
     out.flush();
 ErrorInClass:
     if (delete_qApp)
         delete qApp;
     if (res != S_OK) {
         file.close();
         file.remove();
     }
     return res;
 }
GetClassObject()
HRESULT GetClassObject (const GUID & clsid, const GUID & iid, void ** ppUnk)
Referenced by qax_startServer().
main()
int __cdecl main (int , char **)
Definition at line 46 of file qaxmain.cpp.
Referenced by qax_stopServer(), and WinMain().
 {
     QT_USE_NAMESPACE
     QAxFactory::startServer();
     QApplication app(argc, argv);
     app.setQuitOnLastWindowClosed(false);
     return app.exec();
 }
MonitorProc()
static DWORD WINAPI MonitorProc (void * pv) static
Definition at line 85 of file qaxservermain.cpp.
Referenced by StartMonitor().
 {
     while (1) {
         WaitForSingleObject(hEventShutdown, INFINITE);
         DWORD dwWait=0;
         do {
             qAxActivity = false;
             dwWait = WaitForSingleObject(hEventShutdown, dwTimeOut);
         } while (dwWait == WAIT_OBJECT_0);
         // timed out
         if (!qAxActivity && !qAxLockCount()) // if no activity let's really bail
             break;
     }
     CloseHandle(hEventShutdown);
     PostThreadMessage(dwThreadID, WM_QUIT, 0, 0);
     PostQuitMessage(0);
     return 0;
 }
qax_shutDown()
void qax_shutDown ()
Definition at line 117 of file qaxservermain.cpp.
Referenced by qAxUnlock().
 {
     qAxActivity = true;
     if (hEventShutdown)
         SetEvent(hEventShutdown); // tell monitor that we transitioned to zero
 }
qax_startServer()
bool qax_startServer (QAxFactory::ServerType type)
Definition at line 127 of file qaxservermain.cpp.
Referenced by QAxFactory::startServer().
 {
     if (qAxIsServer)
         return true;
     const QStringList keys = qAxFactory()->featureList();
     if (!keys.count())
         return false;
     if (!qAxFactory()->isService())
         StartMonitor();
     classRegistration = new DWORD[keys.count()];
     int object = 0;
     for (QStringList::ConstIterator key = keys.begin(); key != keys.end(); ++key, ++object) {
         IUnknown* p = 0;
         CLSID clsid = qAxFactory()->classID(*key);
         // Create a QClassFactory (implemented in qaxserverbase.cpp)
         HRESULT hRes = GetClassObject(clsid, IID_IClassFactory, (void**)&p);
         if (SUCCEEDED(hRes))
             hRes = CoRegisterClassObject(clsid, p, CLSCTX_LOCAL_SERVER,
                 type == QAxFactory::MultipleInstances ? REGCLS_MULTIPLEUSE : REGCLS_SINGLEUSE,
                 classRegistration+object);
         if (p)
             p->Release();
     }
     qAxIsServer = true;
     return true;
 }
qax_stopServer()
bool qax_stopServer ()
Definition at line 162 of file qaxservermain.cpp.
Referenced by QAxFactory::startServer(), and QAxFactory::stopServer().
 {
     if (!qAxIsServer || !classRegistration)
         return true;
     qAxIsServer = false;
     const QStringList keys = qAxFactory()->featureList();
     int object = 0;
     for (QStringList::ConstIterator key = keys.begin(); key != keys.end(); ++key, ++object)
         CoRevokeClassObject(classRegistration[object]);
     delete []classRegistration;
     classRegistration = 0;
     Sleep(dwPause); //wait for any threads to finish
     return true;
 }
qax_winEventFilter()
bool qax_winEventFilter (void * message)
Definition at line 809 of file qaxserverbase.cpp.
Referenced by QClassFactory::CreateInstanceHelper().
 {
     MSG *pMsg = (MSG*)message;
     if (pMsg->message < WM_KEYFIRST || pMsg->message > WM_KEYLAST)
     return false;
     bool ret = false;
     QWidget *aqt = QWidget::find(pMsg->hwnd);
     if (!aqt)
     return ret;
     HWND baseHwnd = ::GetParent(aqt->winId());
     QAxServerBase *axbase = 0;
     while (!axbase && baseHwnd) {
 #ifdef GWLP_USERDATA
         axbase = (QAxServerBase*)GetWindowLongPtr(baseHwnd, GWLP_USERDATA);
 #else
         axbase = (QAxServerBase*)GetWindowLong(baseHwnd, GWL_USERDATA);
 #endif
     baseHwnd = ::GetParent(baseHwnd);
     }
     if (!axbase)
     return ret;
     HRESULT hres = axbase->TranslateAcceleratorW(pMsg);
     return hres == S_OK;
 }
qAxCleanup()
void qAxCleanup ()
Definition at line 139 of file qaxserver.cpp.
Referenced by WinMain().
 {
     if (!initCount)
         qWarning("qAxInit/qAxCleanup mismatch");
     if (--initCount)
         return;
     delete qax_factory;
     qax_factory = 0;
     if (qAxTypeLibrary) {
         qAxTypeLibrary->Release();
         qAxTypeLibrary = 0;
     }
     DeleteCriticalSection(&qAxModuleSection);
 }
qAxInit()
QString qAxInit ()
Definition at line 111 of file qaxserver.cpp.
Referenced by UpdateRegistry(), and WinMain().
 {
     static QString libFile;
     if (initCount++)
         return libFile;
     InitializeCriticalSection(&qAxModuleSection);
     libFile = QString::fromWCharArray(qAxModuleFilename);
     libFile = libFile.toLower();
     if (LoadTypeLibEx((wchar_t*)libFile.utf16(), REGKIND_NONE, &qAxTypeLibrary) == S_OK)
         return libFile;
     int lastDot = libFile.lastIndexOf(QLatin1Char('.'));
     libFile = libFile.left(lastDot) + QLatin1String(".tlb");
     if (LoadTypeLibEx((wchar_t*)libFile.utf16(), REGKIND_NONE, &qAxTypeLibrary) == S_OK)
         return libFile;
     lastDot = libFile.lastIndexOf(QLatin1Char('.'));
     libFile = libFile.left(lastDot) + QLatin1String(".olb");
     if (LoadTypeLibEx((wchar_t*)libFile.utf16(), REGKIND_NONE, &qAxTypeLibrary) == S_OK)
         return libFile;
     libFile = QString();
     return libFile;
 }
qAxLockCount()
ulong qAxLockCount ()
Definition at line 180 of file qaxserver.cpp.
Referenced by MonitorProc().
 {
     return qAxModuleRef;
 }
qWinMain()
void __cdecl qWinMain (HINSTANCE , HINSTANCE , LPSTR , int , int & , QVector< char *> &)
Definition at line 170 of file qcoreapplication_win.cpp.
Referenced by qax_stopServer(), and WinMain().
 {
     static bool already_called = false;
     if (already_called) {
         qWarning("Qt: Internal error: qWinMain should be called only once");
         return;
     }
     already_called = true;
     usingWinMain = true;
     // Install default debug handler
     qInstallMsgHandler(qWinMsgHandler);
     // Create command line
     argv = qWinCmdLine<char>(cmdParam, int(strlen(cmdParam)), argc);
     appCmdShow = cmdShow;
     // Ignore Windows parameters
     Q_UNUSED(instance);
     Q_UNUSED(prevInstance);
 }
StartMonitor()
static bool StartMonitor () static
Definition at line 106 of file qaxservermain.cpp.
Referenced by qax_startServer().
 {
     dwThreadID = GetCurrentThreadId();
     hEventShutdown = CreateEvent(0, false, false, 0);
     if (hEventShutdown == 0)
         return false;
     DWORD dwThreadID;
     HANDLE h = CreateThread(0, 0, MonitorProc, 0, 0, &dwThreadID);
     return (h != NULL);
 }
UpdateRegistry()
HRESULT UpdateRegistry (BOOL bRegister)
Definition at line 208 of file qaxserver.cpp.
Referenced by WinMain().
 {
     qAxIsServer = false;
     QString file = QString::fromWCharArray(qAxModuleFilename);
     QString path = file.left(file.lastIndexOf(QLatin1Char('\\'))+1);
     QString module = file.right(file.length() - path.length());
     module = module.left(module.lastIndexOf(QLatin1Char('.')));
     const QString appId = qAxFactory()->appID().toString().toUpper();
     const QString libId = qAxFactory()->typeLibID().toString().toUpper();
     QString libFile = qAxInit();
     QString typeLibVersion;
     TLIBATTR *libAttr = 0;
     if (qAxTypeLibrary)
         qAxTypeLibrary->GetLibAttr(&libAttr);
     if (!libAttr)
         return SELFREG_E_TYPELIB;
     DWORD major = libAttr->wMajorVerNum;
     DWORD minor = libAttr->wMinorVerNum;
     typeLibVersion = QString::number((uint)major) + QLatin1Char('.') + QString::number((uint)minor);
     if (bRegister)
         RegisterTypeLib(qAxTypeLibrary, (wchar_t*)libFile.utf16(), 0);
     else
         UnRegisterTypeLib(libAttr->guid, libAttr->wMajorVerNum, libAttr->wMinorVerNum, libAttr->lcid, libAttr->syskind);
     qAxTypeLibrary->ReleaseTLibAttr(libAttr);
     if (typeLibVersion.isEmpty())
         typeLibVersion = QLatin1String("1.0");
     // check whether the user has permission to write to HKLM\Software\Classes
     // if not, use HKCU\Software\Classes
     QString keyPath(QLatin1String("HKEY_LOCAL_MACHINE\\Software\\Classes"));
     QSettings test(keyPath, QSettings::NativeFormat);
     if (!test.isWritable())
         keyPath = QLatin1String("HKEY_CURRENT_USER\\Software\\Classes");
     QSettings settings(keyPath, QSettings::NativeFormat);
     // we try to create the ActiveX widgets later on...
     bool delete_qApp = false;
     if (!qApp) {
         int argc = 0;
         (void)new QApplication(argc, 0);
         delete_qApp = true;
     }
     if (bRegister) {
         if (qAxOutProcServer) {
             settings.setValue(QLatin1String("/AppID/") + appId + QLatin1String("/."), module);
             settings.setValue(QLatin1String("/AppID/") + module + QLatin1String(".EXE/AppID"), appId);
         }
         QStringList keys = qAxFactory()->featureList();
         for (QStringList::Iterator key = keys.begin(); key != keys.end(); ++key) {
             QString className = *key;
             QObject *object = qAxFactory()->createObject(className);
             const QMetaObject *mo = qAxFactory()->metaObject(className);
             const QString classId = qAxFactory()->classID(className).toString().toUpper();
             className = qax_clean_type(className, mo);
             if (object) { // don't register subobject classes
                 QString classVersion = mo ? QString::fromLatin1(mo->classInfo(mo->indexOfClassInfo("Version")).value()) : QString();
                 if (classVersion.isNull())
                     classVersion = QLatin1String("1.0");
                 bool insertable = mo && !qstricmp(mo->classInfo(mo->indexOfClassInfo("Insertable")).value(), "yes");
                 bool control = object->isWidgetType();
                 const QString classMajorVersion = classVersion.left(classVersion.indexOf(QLatin1Char('.')));
                 uint olemisc = OLEMISC_SETCLIENTSITEFIRST
                     |OLEMISC_ACTIVATEWHENVISIBLE
                     |OLEMISC_INSIDEOUT
                     |OLEMISC_CANTLINKINSIDE
                     |OLEMISC_RECOMPOSEONRESIZE;
                 if (!control)
                     olemisc |= OLEMISC_INVISIBLEATRUNTIME;
                 else if (object->findChild<QMenuBar*>() && !qax_disable_inplaceframe)
                     olemisc |= OLEMISC_WANTSTOMENUMERGE;
                 settings.setValue(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion + QLatin1String("/."), className + QLatin1String(" Class"));
                 settings.setValue(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion + QLatin1String("/CLSID/."), classId);
                 if (insertable)
                     settings.setValue(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion + QLatin1String("/Insertable/."), QVariant(QLatin1String("")));
                 settings.setValue(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1String("/."), className + QLatin1String(" Class"));
                 settings.setValue(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1String("/CLSID/."), classId);
                 settings.setValue(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1String("/CurVer/."), module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion);
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/."), className + QLatin1String(" Class"));
                 if (file.endsWith(QLatin1String("exe"), Qt::CaseInsensitive))
                     settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/AppID"), appId);
                 if (control)
                     settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/Control/."), QVariant(QLatin1String("")));
                 if (insertable)
                     settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/Insertable/."), QVariant(QLatin1String("")));
                 if (file.right(3).toLower() == QLatin1String("dll"))
                     settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/InProcServer32/."), file);
                 else
                     settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/LocalServer32/."),
                                       QLatin1Char('\"') + file + QLatin1String("\" -activex"));
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/MiscStatus/."), control ? QLatin1String("1") : QLatin1String("0"));
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/MiscStatus/1/."), QString::number(olemisc));
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/Programmable/."), QVariant(QLatin1String("")));
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/ToolboxBitmap32/."), QLatin1Char('\"') +
                                   file + QLatin1String("\", 101"));
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/TypeLib/."), libId); settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/Version/."), classVersion);
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/VersionIndependentProgID/."), module + QLatin1Char('.') + className);
                 settings.setValue(QLatin1String("/CLSID/") + classId + QLatin1String("/ProgID/."), module + QLatin1Char('.') + className + QLatin1Char('.') + classVersion.left(classVersion.indexOf(QLatin1Char('.'))));
                 QString mime = QLatin1String(mo->classInfo(mo->indexOfClassInfo("MIME")).value());
                 if (!mime.isEmpty()) {
                     QStringList mimeTypes = mime.split(QLatin1Char(';'));
                     for (int m = 0; m < mimeTypes.count(); ++m) {
                         mime = mimeTypes.at(m);
                         if (mime.isEmpty())
                             continue;
                         QString extension;
                         while (mime.contains(QLatin1Char(':'))) {
                             extension = mime.mid(mime.lastIndexOf(QLatin1Char(':')) + 1);
                             mime = mime.left(mime.length() - extension.length() - 1);
                             // Prepend '.' before extension, if required.
                             extension = extension.trimmed();
                             if (extension[0] != QLatin1Char('.'))
                                 extension = QLatin1Char('.') + extension;
                         }
                         if (!extension.isEmpty()) {
                             settings.setValue(QLatin1Char('/') + extension + QLatin1String("/."), module + QLatin1Char('.') + className);
                             settings.setValue(QLatin1Char('/') + extension + QLatin1String("/Content Type"), mime);
                             mime = mime.replace(QLatin1Char('/'), QLatin1Char('\\'));
                             settings.setValue(QLatin1String("/MIME/Database/Content Type/") + mime + QLatin1String("/CLSID"), classId);
                             settings.setValue(QLatin1String("/MIME/Database/Content Type/") + mime + QLatin1String("/Extension"), extension);
                         }
                     }
                 }
                 delete object;
             }
             qAxFactory()->registerClass(*key, &settings);
         }
     } else {
         if (qAxOutProcServer) {
             settings.remove(QLatin1String("/AppID/") + appId + QLatin1String("/."));
             settings.remove(QLatin1String("/AppID/") + module + QLatin1String(".EXE"));
         }
         QStringList keys = qAxFactory()->featureList();
         for (QStringList::Iterator key = keys.begin(); key != keys.end(); ++key) {
             QString className = *key;
             const QMetaObject *mo = qAxFactory()->metaObject(className);
             const QString classId = qAxFactory()->classID(className).toString().toUpper();
             className = qax_clean_type(className, mo);
             QString classVersion = mo ? QString::fromLatin1(mo->classInfo(mo->indexOfClassInfo("Version")).value()) : QString();
             if (classVersion.isNull())
                 classVersion = QLatin1String("1.0");
             const QString classMajorVersion = classVersion.left(classVersion.indexOf(QLatin1Char('.')));
             qAxFactory()->unregisterClass(*key, &settings);
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion + QLatin1String("/CLSID/."));
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion + QLatin1String("/Insertable/."));
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion + QLatin1String("/."));
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1Char('.') + classMajorVersion);
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1String("/CLSID/."));
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1String("/CurVer/."));
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className + QLatin1String("/."));
             settings.remove(QLatin1Char('/') + module + QLatin1Char('.') + className);
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/AppID"));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/Control/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/Insertable/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/InProcServer32/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/LocalServer32/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/MiscStatus/1/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/MiscStatus/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/Programmable/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/ToolboxBitmap32/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/TypeLib/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/Version/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/VersionIndependentProgID/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/ProgID/."));
             settings.remove(QLatin1String("/CLSID/") + classId + QLatin1String("/."));
             settings.remove(QLatin1String("/CLSID/") + classId);
             QString mime = QLatin1String(mo->classInfo(mo->indexOfClassInfo("MIME")).value());
             if (!mime.isEmpty()) {
                 QStringList mimeTypes = mime.split(QLatin1Char(';'));
                 for (int m = 0; m < mimeTypes.count(); ++m) {
                     mime = mimeTypes.at(m);
                     if (mime.isEmpty())
                         continue;
                     QString extension;
                     while (mime.contains(QLatin1Char(':'))) {
                         extension = mime.mid(mime.lastIndexOf(QLatin1Char(':')) + 1);
                         mime = mime.left(mime.length() - extension.length() - 1);
                         // Prepend '.' before extension, if required.
                         extension = extension.trimmed();
                         if (extension[0] != QLatin1Char('.'))
                             extension.prepend(QLatin1Char('.'));
                     }
                     if (!extension.isEmpty()) {
                         settings.remove(QLatin1Char('/') + extension + QLatin1String("/Content Type"));
                         settings.remove(QLatin1Char('/') + extension + QLatin1String("/."));
                         settings.remove(QLatin1Char('/') + extension);
                         mime.replace(QLatin1Char('/'), QLatin1Char('\\'));
                         settings.remove(QLatin1String("/MIME/Database/Content Type/") + mime + QLatin1String("/Extension"));
                         settings.remove(QLatin1String("/MIME/Database/Content Type/") + mime + QLatin1String("/CLSID"));
                         settings.remove(QLatin1String("/MIME/Database/Content Type/") + mime + QLatin1String("/."));
                         settings.remove(QLatin1String("/MIME/Database/Content Type/") + mime);
                     }
                 }
             }
         }
     }
     if (delete_qApp)
         delete qApp;
     qAxCleanup();
     if (settings.status() == QSettings::NoError)
         return S_OK;
     return SELFREG_E_CLASS;
 }
WinMain()
EXTERN_C int WINAPI WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR , int nShowCmd)
Definition at line 202 of file qaxservermain.cpp.
 {
     QT_USE_NAMESPACE
     qAxOutProcServer = true;
     GetModuleFileName(0, qAxModuleFilename, MAX_PATH);
     qAxInstance = hInstance;
     QByteArray cmdParam = QString::fromWCharArray(GetCommandLine()).toLocal8Bit();
     QList<QByteArray> cmds = cmdParam.split(' ');
     QByteArray unprocessed;
     int nRet = 0;
     bool run = true;
     bool runServer = false;
     for (int i = 0; i < cmds.count(); ++i) {
         QByteArray cmd = cmds.at(i).toLower();
         if (cmd == "-activex" || cmd == "/activex" || cmd == "-embedding" || cmd == "/embedding") {
             runServer = true;
         } else if (cmd == "-unregserver" || cmd == "/unregserver") {
             nRet = UpdateRegistry(false);
             run = false;
             break;
         } else if (cmd == "-regserver" || cmd == "/regserver") {
             nRet = UpdateRegistry(true);
             run = false;
             break;
         } else if (cmd == "-dumpidl" || cmd == "/dumpidl") {
             ++i;
             if (i < cmds.count()) {
                 QByteArray outfile = cmds.at(i);
                 ++i;
                 QByteArray version;
                 if (i < cmds.count() && (cmds.at(i) == "-version" || cmds.at(i) == "/version")) {
                     ++i;
                     if (i < cmds.count())
                         version = cmds.at(i);
                     else
                         version = "1.0";
                 }
                 nRet = DumpIDL(QString::fromLatin1(outfile.constData()), QString::fromLatin1(version.constData()));
             } else {
                 qWarning("Wrong commandline syntax: <app> -dumpidl <idl file> [-version <x.y.z>]");
             }
             run = false;
             break;
         } else {
             unprocessed += cmds.at(i) + ' ';
         }
     }
     if (run) {
         HRESULT hRes = CoInitialize(0);
         int argc;
         QVector<char*> argv(8);
         qWinMain(hInstance, hPrevInstance, unprocessed.data(), nShowCmd, argc, argv);
         qAxInit();
         if (runServer)
             QAxFactory::startServer();
         nRet = ::main(argc, argv.data());
         QAxFactory::stopServer();
         qAxCleanup();
         CoUninitialize();
     }
     return nRet;
 }
Variable Documentation
classRegistration
DWORD* classRegistration = 0 static
Definition at line 52 of file qaxservermain.cpp.
Referenced by qax_startServer(), and qax_stopServer().
dwPause
QT_STATIC_CONST DWORD dwPause = 500
Definition at line 59 of file qaxservermain.cpp.
Referenced by qax_stopServer().
dwThreadID
DWORD dwThreadID static
Definition at line 53 of file qaxservermain.cpp.
Referenced by MonitorProc(), qt_adopted_thread_watcher_function(), and StartMonitor().
dwTimeOut
QT_STATIC_CONST DWORD dwTimeOut = 1000
Definition at line 58 of file qaxservermain.cpp.
Referenced by MonitorProc().
hEventShutdown
HANDLE hEventShutdown static
Definition at line 55 of file qaxservermain.cpp.
Referenced by MonitorProc(), qax_shutDown(), and StartMonitor().
qAxActivity
bool qAxActivity = false static
Definition at line 54 of file qaxservermain.cpp.
Referenced by MonitorProc(), and qax_shutDown().
qAxInstance
HANDLE qAxInstance
Definition at line 65 of file qaxserver.cpp.
Referenced by WinMain().
qAxIsServer
bool qAxIsServer
Definition at line 64 of file qaxserver.cpp.
Referenced by DumpIDL(), qax_startServer(), qax_stopServer(), and UpdateRegistry().
qAxModuleFilename
wchar_t qAxModuleFilename[MAX_PATH]
Definition at line 67 of file qaxserver.cpp.
Referenced by DumpIDL(), qAxInit(), UpdateRegistry(), and WinMain().
qAxOutProcServer
bool qAxOutProcServer
Definition at line 68 of file qaxserver.cpp.
Referenced by WinMain().