Qt 4.8: /src/gui/painting/qbackingstore.cpp File Reference
qbackingstore.cpp File Reference
#include "qplatformdefs.h"
#include "qbackingstore_p.h"
#include <QtCore/qglobal.h>
#include <QtCore/qdebug.h>
#include <QtCore/qvarlengtharray.h>
#include <QtGui/qevent.h>
#include <QtGui/qapplication.h>
#include <QtGui/qpaintengine.h>
#include <QtGui/qgraphicsproxywidget.h>
#include <private/qwidget_p.h>
#include <private/qwindowsurface_raster_p.h>
#include <private/qapplication_p.h>
#include <private/qpaintengine_raster_p.h>
#include <private/qgraphicseffect_p.h>
#include "qgraphicssystem_p.h"
#include <QtGui/qwsmanager_qws.h>
#include <private/qwsmanager_p.h>
Functions
static bool discardInvalidateBufferRequest (QWidget *widget, QTLWExtra *tlwExtra)
static bool discardSyncRequest (QWidget *tlw, QTLWExtra *tlwExtra)
static bool qRectIntersects (const QRect &r1, const QRect &r2)
QRegion qt_dirtyRegion (QWidget *)
static void qt_flush (QWidget *widget, const QRegion &region, QWindowSurface *windowSurface, QWidget *tlw, const QPoint &tlwOffset)
static void sendUpdateRequest (QWidget *widget, bool updateImmediately)
static void showYellowThing_win (QWidget *widget, const QRegion &region, int msec)
Function Documentation
discardInvalidateBufferRequest()
static bool discardInvalidateBufferRequest (QWidget * widget, QTLWExtra * tlwExtra) inline static
Definition at line 1451 of file qbackingstore.cpp.
Referenced by QWidgetPrivate::invalidateBuffer().
 {
     Q_ASSERT(widget);
     if (QApplication::closingDown())
         return true;
     if (!tlwExtra || tlwExtra->inTopLevelResize || !tlwExtra->backingStore)
         return true;
     if (!widget->isVisible() || !widget->updatesEnabled())
         return true;
     return false;
 }
discardSyncRequest()
static bool discardSyncRequest (QWidget * tlw, QTLWExtra * tlwExtra) inline static
Definition at line 1098 of file qbackingstore.cpp.
Referenced by QWidgetBackingStore::sync().
 {
     if (!tlw || !tlwExtra)
         return true;
 #ifdef Q_WS_X11
     // Delay the sync until we get an Expose event from X11 (initial show).
     // Qt::WA_Mapped is set to true, but the actual mapping has not yet occurred.
     // However, we must repaint immediately regardless of the state if someone calls repaint().
     if (tlwExtra->waitingForMapNotify && !tlwExtra->inRepaint)
         return true;
 #endif
     if (!tlw->testAttribute(Qt::WA_Mapped))
         return true;
     if (!tlw->isVisible()
 #ifndef Q_WS_X11
         // If we're minimized on X11, WA_Mapped will be false and we
         // will return in the case above. Some window managers on X11
         // sends us the PropertyNotify to change the minimized state
         // *AFTER* we've received the expose event, which is baaad.
         || tlw->isMinimized()
 #endif
         )
         return true;
     return false;
 }
qRectIntersects()
static bool qRectIntersects (const QRect & r1, const QRect & r2) inline static
Definition at line 75 of file qbackingstore.cpp.
Referenced by QWidgetBackingStore::sync().
 {
     return (qMax(r1.left(), r2.left()) <= qMin(r1.right(), r2.right())
             && qMax(r1.top(), r2.top()) <= qMin(r1.bottom(), r2.bottom()));
 }
qt_dirtyRegion()
QRegion qt_dirtyRegion (QWidget *)
Definition at line 1111 of file qwidget.cpp.
 {
     if (!widget)
         return QRegion();
     QWidgetBackingStore *bs = qt_widget_private(widget)->maybeBackingStore();
     if (!bs)
         return QRegion();
     return bs->dirtyRegion(widget);
 }
qt_flush()
static void qt_flush (QWidget * widget, const QRegion & region, QWindowSurface * windowSurface, QWidget * tlw, const QPoint & tlwOffset) inline static
Flushes the contents of the windowSurface into the screen area of widget. tlwOffset is the position of the top level widget relative to the window surface. region is the region to be updated in widget coordinates.
Definition at line 86 of file qbackingstore.cpp.
Referenced by QWidgetBackingStore::flush(), QWidgetBackingStore::sync(), and QWidgetBackingStore::unflushPaint().
 {
     Q_ASSERT(widget);
     Q_ASSERT(!region.isEmpty());
     Q_ASSERT(windowSurface);
     Q_ASSERT(tlw);
 #if !defined(QT_NO_PAINT_DEBUG) && !defined(Q_WS_QWS)
     // QWS does flush update in QWindowSurface::flush (because it needs to lock the surface etc).
     static int flushUpdate = qgetenv("QT_FLUSH_UPDATE").toInt();
     if (flushUpdate > 0)
         QWidgetBackingStore::showYellowThing(widget, region, flushUpdate * 10, false);
 #endif
     //The performance hit by doing this should be negligible. However, be aware that
     //using this FPS when you have > 1 windowsurface can give you inaccurate FPS
     static bool fpsDebug = qgetenv("QT_DEBUG_FPS").toInt();
     if (fpsDebug) {
         static QTime time = QTime::currentTime();
         static int frames = 0;
         frames++;
         if(time.elapsed() > 5000) {
             double fps = double(frames * 1000) /time.restart();
             fprintf(stderr,"FPS: %.1f\n",fps);
             frames = 0;
         }
     }
     if (widget != tlw)
         windowSurface->flush(widget, region, tlwOffset + widget->mapTo(tlw, QPoint()));
     else
         windowSurface->flush(widget, region, tlwOffset);
 }
sendUpdateRequest()
static void sendUpdateRequest (QWidget * widget, bool updateImmediately) inline static
Definition at line 527 of file qbackingstore.cpp.
Referenced by QWidgetBackingStore::markDirty().
 {
     if (!widget)
         return;
     if (updateImmediately) {
         QEvent event(QEvent::UpdateRequest);
         QApplication::sendEvent(widget, &event);
     } else {
         QApplication::postEvent(widget, new QEvent(QEvent::UpdateRequest), Qt::LowEventPriority);
     }
 }
showYellowThing_win()
static void showYellowThing_win (QWidget * widget, const QRegion & region, int msec) static
Definition at line 124 of file qbackingstore.cpp.
Referenced by QWidgetBackingStore::showYellowThing().
 {
     HBRUSH brush;
     static int i = 0;
     switch (i) {
     case 0:
         brush = CreateSolidBrush(RGB(255, 255, 0));
         break;
     case 1:
         brush = CreateSolidBrush(RGB(255, 200, 55));
         break;
     case 2:
         brush = CreateSolidBrush(RGB(200, 255, 55));
         break;
     case 3:
         brush = CreateSolidBrush(RGB(200, 200, 0));
         break;
     }
     i = (i + 1) & 3;
     HDC hdc = widget->getDC();
     const QVector<QRect> &rects = region.rects();
     foreach (QRect rect, rects) {
         RECT winRect;
         SetRect(&winRect, rect.left(), rect.top(), rect.right(), rect.bottom());
         FillRect(hdc, &winRect, brush);
     }
     widget->releaseDC(hdc);
     ::Sleep(msec);
 }