Qt 4.8: /src/plugins/bearer/blackberry/qbbengine.cpp File Reference
qbbengine.cpp File Reference
#include "qbbengine.h"
#include "../qnetworksession_impl.h"
#include <QDebug>
#include <QThreadStorage>
#include <QStringList>
#include <QTimer>
#include <bps/netstatus.h>
Classes
struct EngineInstanceHolder
struct NetstatusInterfaceCleanupHelper
struct NetstatusInterfaceListCleanupHelper
Macros
#define qBearerDebug QT_NO_QDEBUG_MACRO
Functions
static QString idForName (const QString &name)
static QNetworkConfiguration::BearerType interfaceType (netstatus_interface_type_t type)
Q_GLOBAL_STATIC (QThreadStorage< EngineInstanceHolder *>, instanceStorage)
Macro Definition Documentation
qBearerDebug
#define qBearerDebug QT_NO_QDEBUG_MACRO
Definition at line 57 of file qbbengine.cpp.
Referenced by QBBEngine::defaultConfiguration(), QBBEngine::doRequestUpdate(), QBBEngine::filterEvent(), and QBBEngine::updateConfiguration().
Function Documentation
idForName()
static QString idForName (const QString & name) static
Definition at line 116 of file qbbengine.cpp.
Referenced by QBBEngine::defaultConfiguration(), QBBEngine::doRequestUpdate(), and QBBEngine::updateConfiguration().
 {
     return QLatin1String("bps:") + name;
 }
interfaceType()
static QNetworkConfiguration::BearerType interfaceType (netstatus_interface_type_t type) static
Definition at line 87 of file qbbengine.cpp.
Referenced by QBBEngine::updateConfiguration().
 {
     switch (type) {
     case NETSTATUS_INTERFACE_TYPE_USB:
     case NETSTATUS_INTERFACE_TYPE_WIRED:
         return QNetworkConfiguration::BearerEthernet;
     case NETSTATUS_INTERFACE_TYPE_WIFI:
         return QNetworkConfiguration::BearerWLAN;
     case NETSTATUS_INTERFACE_TYPE_BLUETOOTH_DUN:
         return QNetworkConfiguration::BearerBluetooth;
     case NETSTATUS_INTERFACE_TYPE_CELLULAR:
         //### TODO  not sure which BearerType would be the best
         //to return here. We need to be able to get more
         //information on the bearer type in order to return
         //the exact match.
         return QNetworkConfiguration::Bearer2G;
     case NETSTATUS_INTERFACE_TYPE_VPN:
     case NETSTATUS_INTERFACE_TYPE_BB:
     case NETSTATUS_INTERFACE_TYPE_UNKNOWN:
         break;
     }
     return QNetworkConfiguration::BearerUnknown;
 }
Q_GLOBAL_STATIC()
Q_GLOBAL_STATIC (QThreadStorage< EngineInstanceHolder *> , instanceStorage)