Qt 4.8: /src/plugins/platforms/blackberry/qbbscreen.cpp File Reference
qbbscreen.cpp File Reference
#include "qbbscreen.h"
#include "qbbrootwindow.h"
#include "qbbwindow.h"
#include "qbbcursor.h"
#include <QDebug>
#include <QtCore/QThread>
#include <QtGui/QWindowSystemInterface>
#include <errno.h>
#include <unistd.h>
Functions
static int defaultDepth ()
static QSize determineScreenSize (screen_display_t display, bool primaryScreen)
static bool isOrthogonal (int angle1, int angle2)
Check if the supplied angles are perpendicular to each other.
Function Documentation
defaultDepth()
static int defaultDepth () static
Definition at line 164 of file qbbscreen.cpp.
Referenced by QBBScreen::depth(), and QPixmap::swap().
 {
     static int defaultDepth = 0;
     if (defaultDepth == 0) {
         // check if display depth was specified in environment variable;
         // use default value if no valid value found
         defaultDepth = qgetenv("QBB_DISPLAY_DEPTH").toInt();
         if (defaultDepth != 16 && defaultDepth != 32) {
             defaultDepth = 32;
         }
     }
     return defaultDepth;
 }
determineScreenSize()
static QSize determineScreenSize (screen_display_t display, bool primaryScreen) static
Definition at line 67 of file qbbscreen.cpp.
Referenced by QBBScreen::QBBScreen().
 {
     int val[2];
     errno = 0;
     const int result = screen_get_display_property_iv(display, SCREEN_PROPERTY_PHYSICAL_SIZE, val);
     if (result != 0) {
         qFatal("QBBScreen: failed to query display physical size, errno=%d", errno);
         return QSize(150, 90);
     }
     if (val[0] > 0 && val[1] > 0)
         return QSize(val[0], val[1]);
     qWarning("QBBScreen: screen_get_display_property_iv() reported an invalid physical screen size (%dx%d). Falling back to QBB_PHYSICAL_SCREEN_SIZE environment variable.", val[0], val[1]);
     const QString envPhySizeStr = qgetenv("QBB_PHYSICAL_SCREEN_SIZE");
     if (!envPhySizeStr.isEmpty()) {
         const QStringList envPhySizeStrList = envPhySizeStr.split(QLatin1Char(','));
         const int envWidth = envPhySizeStrList.size() == 2 ? envPhySizeStrList[0].toInt() : -1;
         const int envHeight = envPhySizeStrList.size() == 2 ? envPhySizeStrList[1].toInt() : -1;
         if (envWidth <= 0 || envHeight <= 0) {
             qFatal("QBBScreen: The value of QBB_PHYSICAL_SCREEN_SIZE must be in the format \"width,height\" in mm, with width, height > 0. Example: QBB_PHYSICAL_SCREEN_SIZE=150,90");
             return QSize(150, 90);
         }
         return QSize(envWidth, envHeight);
     }
 #if defined(QBB_PHYSICAL_SCREEN_SIZE_DEFINED)
     const QSize defSize(QBB_PHYSICAL_SCREEN_WIDTH, QBB_PHYSICAL_SCREEN_HEIGHT);
     qWarning("QBBScreen: QBB_PHYSICAL_SCREEN_SIZE variable not set. Falling back to defines QBB_PHYSICAL_SCREEN_WIDTH/QBB_PHYSICAL_SCREEN_HEIGHT (%dx%d)", defSize.width(), defSize.height());
     return defSize;
 #else
     if (primaryScreen)
         qFatal("QBBScreen: QBB_PHYSICAL_SCREEN_SIZE variable not set. Could not determine physical screen size.");
     return QSize(150, 90);
 #endif
 }
isOrthogonal()
static bool isOrthogonal (int angle1, int angle2) static
Check if the supplied angles are perpendicular to each other.
Definition at line 224 of file qbbscreen.cpp.
Referenced by QBBScreen::setRotation().
 {
     return ((angle1 - angle2) % 180) != 0;
 }