Qt 4.8: /src/gui/painting/qbezier.cpp File Reference
qbezier.cpp File Reference
#include "qbezier_p.h"
#include <qdebug.h>
#include <qline.h>
#include <qpolygon.h>
#include <qvector.h>
#include <qlist.h>
#include <qmath.h>
#include <private/qnumeric_p.h>
#include <private/qmath_p.h>
Macros
#define INV_EPS (1L<<14)
#define KAPPA qreal(0.5522847498)
#define M_SQRT2 1.41421356237309504880
Enumerations
enum ShiftResult { Ok, Discard, Split, Circle }
Functions
static bool addCircle (const QBezier *b, qreal offset, QBezier *o)
static bool findInflections (qreal a, qreal b, qreal c, qreal *t1, qreal *t2, qreal *tCups)
static ShiftResult good_offset (const QBezier *b1, const QBezier *b2, qreal offset, qreal threshold)
static int quadraticRoots (qreal a, qreal b, qreal c, qreal *x1, qreal *x2)
static ShiftResult shift (const QBezier *orig, QBezier *shifted, qreal offset, qreal threshold)
static void splitBezierAt (const QBezier &bez, qreal t, QBezier *left, QBezier *right)
Macro Definition Documentation
INV_EPS
#define INV_EPS (1L<<14)
Definition at line 61 of file qbezier.cpp.
KAPPA
#define KAPPA qreal(0.5522847498)
Definition at line 370 of file qbezier.cpp.
Referenced by addCircle(), QPaintEngineEx::drawRoundedRect(), and QVGPaintEnginePrivate::roundedRectPath().
M_SQRT2
#define M_SQRT2 1.41421356237309504880
Definition at line 65 of file qbezier.cpp.
Enumeration Type Documentation
ShiftResult
enum ShiftResult
Enumerator
Ok
Discard
Split
Circle
Definition at line 258 of file qbezier.cpp.
                  {
     Ok,
     Discard,
     Split,
     Circle
 };
Function Documentation
addCircle()
static bool addCircle (const QBezier * b, qreal offset, QBezier * o) static
Definition at line 373 of file qbezier.cpp.
Referenced by QBezier::shifted().
 {
     QPointF normals[3];
     normals[0] = QPointF(b->y2 - b->y1, b->x1 - b->x2);
     qreal dist = qSqrt(normals[0].x()*normals[0].x() + normals[0].y()*normals[0].y());
     if (qFuzzyIsNull(dist))
         return false;
     normals[0] /= dist;
     normals[2] = QPointF(b->y4 - b->y3, b->x3 - b->x4);
     dist = qSqrt(normals[2].x()*normals[2].x() + normals[2].y()*normals[2].y());
     if (qFuzzyIsNull(dist))
         return false;
     normals[2] /= dist;
     normals[1] = QPointF(b->x1 - b->x2 - b->x3 + b->x4, b->y1 - b->y2 - b->y3 + b->y4);
     normals[1] /= -1*qSqrt(normals[1].x()*normals[1].x() + normals[1].y()*normals[1].y());
     qreal angles[2];
     qreal sign = 1.;
     for (int i = 0; i < 2; ++i) {
         qreal cos_a = normals[i].x()*normals[i+1].x() + normals[i].y()*normals[i+1].y();
         if (cos_a > 1.)
             cos_a = 1.;
         if (cos_a < -1.)
             cos_a = -1;
         angles[i] = qAcos(cos_a)/Q_PI;
     }
     if (angles[0] + angles[1] > 1.) {
         // more than 180 degrees
         normals[1] = -normals[1];
         angles[0] = 1. - angles[0];
         angles[1] = 1. - angles[1];
         sign = -1.;
     }
     QPointF circle[3];
     circle[0] = QPointF(b->x1, b->y1) + normals[0]*offset;
     circle[1] = QPointF(qreal(0.5)*(b->x1 + b->x4), qreal(0.5)*(b->y1 + b->y4)) + normals[1]*offset;
     circle[2] = QPointF(b->x4, b->y4) + normals[2]*offset;
     for (int i = 0; i < 2; ++i) {
         qreal kappa = qreal(2.0) * KAPPA * sign * offset * angles[i];
         o->x1 = circle[i].x();
         o->y1 = circle[i].y();
         o->x2 = circle[i].x() - normals[i].y()*kappa;
         o->y2 = circle[i].y() + normals[i].x()*kappa;
         o->x3 = circle[i+1].x() + normals[i+1].y()*kappa;
         o->y3 = circle[i+1].y() - normals[i+1].x()*kappa;
         o->x4 = circle[i+1].x();
         o->y4 = circle[i+1].y();
         ++o;
     }
     return true;
 }
findInflections()
static bool findInflections (qreal a, qreal b, qreal c, qreal * t1, qreal * t2, qreal * tCups) inline static
Definition at line 164 of file qbezier.cpp.
 {
     qreal r1 = 0, r2 = 0;
     short rootsCount = quadraticRoots(a, b, c, &r1, &r2);
     if (rootsCount >= 1) {
         if (r1 < r2) {
             *t1 = r1;
             *t2 = r2;
         } else {
             *t1 = r2;
             *t2 = r1;
         }
         if (!qFuzzyIsNull(a))
             *tCups = qreal(0.5) * (-b / a);
         else
             *tCups = 2;
         return true;
     }
     return false;
 }
good_offset()
static ShiftResult good_offset (const QBezier * b1, const QBezier * b2, qreal offset, qreal threshold) static
Definition at line 265 of file qbezier.cpp.
Referenced by shift().
 {
     const qreal o2 = offset*offset;
     const qreal max_dist_line = threshold*offset*offset;
     const qreal max_dist_normal = threshold*offset;
     const qreal spacing = qreal(0.25);
     for (qreal i = spacing; i < qreal(0.99); i += spacing) {
         QPointF p1 = b1->pointAt(i);
         QPointF p2 = b2->pointAt(i);
         qreal d = (p1.x() - p2.x())*(p1.x() - p2.x()) + (p1.y() - p2.y())*(p1.y() - p2.y());
         if (qAbs(d - o2) > max_dist_line)
             return Split;
         QPointF normalPoint = b1->normalVector(i);
         qreal l = qAbs(normalPoint.x()) + qAbs(normalPoint.y());
         if (l != qreal(0.0)) {
             d = qAbs( normalPoint.x()*(p1.y() - p2.y()) - normalPoint.y()*(p1.x() - p2.x()) ) / l;
             if (d > max_dist_normal)
                 return Split;
         }
     }
     return Ok;
 }
quadraticRoots()
static int quadraticRoots (qreal a, qreal b, qreal c, qreal * x1, qreal * x2) inline static
Definition at line 133 of file qbezier.cpp.
Referenced by findInflections().
 {
     if (qFuzzyIsNull(a)) {
         if (qFuzzyIsNull(b))
             return 0;
         *x1 = *x2 = (-c / b);
         return 1;
     } else {
         const qreal det = b * b - 4 * a * c;
         if (qFuzzyIsNull(det)) {
             *x1 = *x2 = -b / (2 * a);
             return 1;
         }
         if (det > 0) {
             if (qFuzzyIsNull(b)) {
                 *x2 = qSqrt(-c / a);
                 *x1 = -(*x2);
                 return 2;
             }
             const qreal stableA = b / (2 * a);
             const qreal stableB = c / (a * stableA * stableA);
             const qreal stableC = -1 - qSqrt(1 - stableB);
             *x2 = stableA * stableC;
             *x1 = (stableA * stableB) / stableC;
             return 2;
         } else
             return 0;
     }
 }
shift()
static ShiftResult shift (const QBezier * orig, QBezier * shifted, qreal offset, qreal threshold) static
Definition at line 289 of file qbezier.cpp.
Referenced by qrgb444::byte_mul(), QWSCalibratedMouseHandler::calibrate(), checksum(), QImage::mirrored(), qt_memrotate270_tiled(), qt_memrotate90_tiled(), qt_static_shift(), QBezier::shifted(), and QAxServerBase::TranslateAcceleratorW().
 {
     int map[4];
     bool p1_p2_equal = (orig->x1 == orig->x2 && orig->y1 == orig->y2);
     bool p2_p3_equal = (orig->x2 == orig->x3 && orig->y2 == orig->y3);
     bool p3_p4_equal = (orig->x3 == orig->x4 && orig->y3 == orig->y4);
     QPointF points[4];
     int np = 0;
     points[np] = QPointF(orig->x1, orig->y1);
     map[0] = 0;
     ++np;
     if (!p1_p2_equal) {
         points[np] = QPointF(orig->x2, orig->y2);
         ++np;
     }
     map[1] = np - 1;
     if (!p2_p3_equal) {
         points[np] = QPointF(orig->x3, orig->y3);
         ++np;
     }
     map[2] = np - 1;
     if (!p3_p4_equal) {
         points[np] = QPointF(orig->x4, orig->y4);
         ++np;
     }
     map[3] = np - 1;
     if (np == 1)
         return Discard;
     QRectF b = orig->bounds();
     if (np == 4 && b.width() < .1*offset && b.height() < .1*offset) {
         qreal l = (orig->x1 - orig->x2)*(orig->x1 - orig->x2) +
                   (orig->y1 - orig->y2)*(orig->y1 - orig->y1) *
                   (orig->x3 - orig->x4)*(orig->x3 - orig->x4) +
                   (orig->y3 - orig->y4)*(orig->y3 - orig->y4);
         qreal dot = (orig->x1 - orig->x2)*(orig->x3 - orig->x4) +
                     (orig->y1 - orig->y2)*(orig->y3 - orig->y4);
         if (dot < 0 && dot*dot < 0.8*l)
             // the points are close and reverse dirction. Approximate the whole
             // thing by a semi circle
             return Circle;
     }
     QPointF points_shifted[4];
     QLineF prev = QLineF(QPointF(), points[1] - points[0]);
     QPointF prev_normal = prev.normalVector().unitVector().p2();
     points_shifted[0] = points[0] + offset * prev_normal;
     for (int i = 1; i < np - 1; ++i) {
         QLineF next = QLineF(QPointF(), points[i + 1] - points[i]);
         QPointF next_normal = next.normalVector().unitVector().p2();
         QPointF normal_sum = prev_normal + next_normal;
         qreal r = qreal(1.0) + prev_normal.x() * next_normal.x()
                   + prev_normal.y() * next_normal.y();
         if (qFuzzyIsNull(r)) {
             points_shifted[i] = points[i] + offset * prev_normal;
         } else {
             qreal k = offset / r;
             points_shifted[i] = points[i] + k * normal_sum;
         }
         prev_normal = next_normal;
     }
     points_shifted[np - 1] = points[np - 1] + offset * prev_normal;
     *shifted = QBezier::fromPoints(points_shifted[map[0]], points_shifted[map[1]],
                                    points_shifted[map[2]], points_shifted[map[3]]);
     return good_offset(orig, shifted, offset, threshold);
 }
splitBezierAt()
static void splitBezierAt (const QBezier & bez, qreal t, QBezier * left, QBezier * right) inline static
Definition at line 501 of file qbezier.cpp.
 {
     left->x1 = bez.x1;
     left->y1 = bez.y1;
     left->x2 = bez.x1 + t * ( bez.x2 - bez.x1 );
     left->y2 = bez.y1 + t * ( bez.y2 - bez.y1 );
     left->x3 = bez.x2 + t * ( bez.x3 - bez.x2 ); // temporary holding spot
     left->y3 = bez.y2 + t * ( bez.y3 - bez.y2 ); // temporary holding spot
     right->x3 = bez.x3 + t * ( bez.x4 - bez.x3 );
     right->y3 = bez.y3 + t * ( bez.y4 - bez.y3 );
     right->x2 = left->x3 + t * ( right->x3 - left->x3);
     right->y2 = left->y3 + t * ( right->y3 - left->y3);
     left->x3 = left->x2 + t * ( left->x3 - left->x2 );
     left->y3 = left->y2 + t * ( left->y3 - left->y2 );
     left->x4 = right->x1 = left->x3 + t * (right->x2 - left->x3);
     left->y4 = right->y1 = left->y3 + t * (right->y2 - left->y3);
     right->x4 = bez.x4;
     right->y4 = bez.y4;
 }