Qt 4.8: /src/corelib/tools/qbitarray.h File Reference
qbitarray.h File Reference
#include <QtCore/qbytearray.h>
Classes
class QBitArray
The QBitArray class provides an array of bits.
class QBitRef
The QBitRef class is an internal class, used with QBitArray.
Functions
Q_CORE_EXPORT QBitArray operator & (const QBitArray &, const QBitArray &)
Q_CORE_EXPORT QDataStream & operator<< (QDataStream &, const QBitArray &)
Q_CORE_EXPORT QDataStream & operator>> (QDataStream &, QBitArray &)
Q_CORE_EXPORT QBitArray operator^ (const QBitArray &, const QBitArray &)
Q_CORE_EXPORT QBitArray operator| (const QBitArray &, const QBitArray &)
Q_DECLARE_TYPEINFO (QBitArray, Q_MOVABLE_TYPE)
Function Documentation
operator &()
Q_CORE_EXPORT QBitArray operator& (const QBitArray & , const QBitArray &) related
Referenced by QBitArray::fill(), QRect::QRect(), QPainterPath::swap(), and QRegion::xored().
operator<<()
Q_CORE_EXPORT QDataStream& operator<< (QDataStream & , const QBitArray &)
Referenced by QBitArray::operator[]().
operator>>()
Q_CORE_EXPORT QDataStream& operator>> (QDataStream & , QBitArray &)
Referenced by QBitArray::operator[]().
operator^()
Q_CORE_EXPORT QBitArray operator^ (const QBitArray & , const QBitArray &) related
Referenced by QBitArray::fill(), and QRegion::xored().
operator|()
Q_CORE_EXPORT QBitArray operator| (const QBitArray & , const QBitArray &) related
Referenced by QBitArray::fill(), QPainterPath::swap(), and QRegion::xored().
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QBitArray , Q_MOVABLE_TYPE)
Referenced by QBitArray::operator[]().