Qt 4.8: /src/gui/painting/qblendfunctions.cpp File Reference
qblendfunctions.cpp File Reference
#include <qmath.h>
#include "qblendfunctions_p.h"
Classes
struct Blend_ARGB24_on_RGB16_SourceAlpha
struct Blend_ARGB24_on_RGB16_SourceAndConstAlpha
struct Blend_ARGB32_on_ARGB32_SourceAlpha
struct Blend_ARGB32_on_ARGB32_SourceAndConstAlpha
struct Blend_ARGB32_on_RGB16_SourceAlpha
struct Blend_ARGB32_on_RGB16_SourceAndConstAlpha
struct Blend_RGB16_on_RGB16_ConstAlpha
struct Blend_RGB16_on_RGB16_NoAlpha
struct Blend_RGB32_on_RGB32_ConstAlpha
struct Blend_RGB32_on_RGB32_NoAlpha
struct SourceAndConstAlpha
struct SourceOnlyAlpha
Functions
static quint16 convert_argb32_to_rgb16 (quint32 spix)
template<typename T >
void qt_blend_argb24_on_rgb16 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, int w, int h, const T &alphaFunc)
static void qt_blend_argb24_on_rgb16 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, int w, int h, int const_alpha)
static void qt_blend_argb32_on_argb32 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, int w, int h, int const_alpha)
static void qt_blend_argb32_on_rgb16 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, int w, int h, int const_alpha)
void qt_blend_argb32_on_rgb16_const_alpha (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, int w, int h, int const_alpha)
void qt_blend_rgb16_on_rgb16 (uchar *dst, int dbpl, const uchar *src, int sbpl, int w, int h, int const_alpha)
static void qt_blend_rgb32_on_rgb16 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, int w, int h, int const_alpha)
void qt_blend_rgb32_on_rgb32 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, int w, int h, int const_alpha)
void qt_scale_image_argb24_on_rgb16 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, int sh, const QRectF &targetRect, const QRectF &sourceRect, const QRect &clip, int const_alpha)
void qt_scale_image_argb32_on_argb32 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, int sh, const QRectF &targetRect, const QRectF &sourceRect, const QRect &clip, int const_alpha)
void qt_scale_image_argb32_on_rgb16 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, int sh, const QRectF &targetRect, const QRectF &sourceRect, const QRect &clip, int const_alpha)
void qt_scale_image_rgb16_on_rgb16 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, int sh, const QRectF &targetRect, const QRectF &sourceRect, const QRect &clip, int const_alpha)
void qt_scale_image_rgb32_on_rgb32 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, int sh, const QRectF &targetRect, const QRectF &sourceRect, const QRect &clip, int const_alpha)
void qt_transform_image_argb24_on_rgb16 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, const QRectF &targetRect, const QRectF &sourceRect, const QRect &clip, const QTransform &targetRectTransform, int const_alpha)
void qt_transform_image_argb32_on_argb32 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, const QRectF &targetRect, const QRectF &sourceRect, const QRect &clip, const QTransform &targetRectTransform, int const_alpha)
void qt_transform_image_argb32_on_rgb16 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, const QRectF &targetRect, const QRectF &sourceRect, const QRect &clip, const QTransform &targetRectTransform, int const_alpha)
void qt_transform_image_rgb16_on_rgb16 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, const QRectF &targetRect, const QRectF &sourceRect, const QRect &clip, const QTransform &targetRectTransform, int const_alpha)
void qt_transform_image_rgb32_on_rgb32 (uchar *destPixels, int dbpl, const uchar *srcPixels, int sbpl, const QRectF &targetRect, const QRectF &sourceRect, const QRect &clip, const QTransform &targetRectTransform, int const_alpha)
Variables
SrcOverBlendFunc qBlendFunctions [QImage::NImageFormats][QImage::NImageFormats]
SrcOverScaleFunc qScaleFunctions [QImage::NImageFormats][QImage::NImageFormats]
SrcOverTransformFunc qTransformFunctions [QImage::NImageFormats][QImage::NImageFormats]
Function Documentation
convert_argb32_to_rgb16()
static quint16 convert_argb32_to_rgb16 (quint32 spix) inline static
Definition at line 74 of file qblendfunctions.cpp.
Referenced by qt_blend_argb32_on_rgb16(), qt_blend_argb32_on_rgb16_const_alpha(), qt_blend_rgb32_on_rgb16(), Blend_ARGB32_on_RGB16_SourceAlpha::write(), and Blend_ARGB32_on_RGB16_SourceAndConstAlpha::write().
 {
     quint32 b = spix;
     quint32 g = spix;
     b >>= 8;
     g >>= 5;
     b &= 0x0000f800;
     g &= 0x000007e0;
     spix >>= 3;
     b |= g;
     spix &= 0x0000001f;
     b |= spix;
     return b;
 }
qt_blend_argb24_on_rgb16() [1/2]
template<typename T > void qt_blend_argb24_on_rgb16 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, int w, int h, const T & alphaFunc)
Definition at line 299 of file qblendfunctions.cpp.
Referenced by qt_blend_argb24_on_rgb16().
 {
     int srcOffset = w*3;
     int dstJPL = dbpl / 2;
     quint16 *dst = (quint16 *) destPixels;
     int dstExtraStride = dstJPL - w;
     for (int y=0; y<h; ++y) {
         const uchar *src = srcPixels + y * sbpl;
         const uchar *srcEnd = src + srcOffset;
         while (src < srcEnd) {
 #if defined(QT_ARCH_ARMV5) || defined(QT_ARCH_POWERPC) || defined(QT_ARCH_SH) || defined(QT_ARCH_AVR32) || (defined(QT_ARCH_WINDOWSCE) && !defined(_X86_)) || (defined(QT_ARCH_SPARC) && defined(Q_CC_GNU)) || (defined(QT_ARCH_INTEGRITY) && !defined(_X86_))
             // non-16-bit aligned memory access is not possible on PowerPC,
             // ARM <v6 (QT_ARCH_ARMV5) & SH & AVR32 & SPARC w/GCC
             quint16 spix = (quint16(src[2])<<8) + src[1];
 #else
             quint16 spix = *(quint16 *) (src + 1);
 #endif
             uchar alpha = alphaFunc.alpha(*src);
             if (alpha == 255) {
                 *dst = spix;
             } else if (alpha != 0) {
                 quint16 dpix = *dst;
                 quint32 sia = 255 - alpha;
                 quint16 dr = (dpix & 0x0000f800);
                 quint16 dg = (dpix & 0x000007e0);
                 quint16 db = (dpix & 0x0000001f);
                 quint32 siar = dr * sia;
                 quint32 siag = dg * sia;
                 quint32 siab = db * sia;
                 quint32 rr = ((siar + (siar>>8) + (0x80 <<  8)) >> 8) & 0xf800;
                 quint32 rg = ((siag + (siag>>8) + (0x80 <<  3)) >> 8) & 0x07e0;
                 quint32 rb = ((siab + (siab>>8) + (0x80 >>  3)) >> 8) & 0x001f;
                 *dst = alphaFunc.bytemul(spix) + rr + rg + rb;
             }
             ++dst;
             src += 3;
         }
         dst += dstExtraStride;
     }
 }
qt_blend_argb24_on_rgb16() [2/2]
static void qt_blend_argb24_on_rgb16 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, int w, int h, int const_alpha) static
Definition at line 350 of file qblendfunctions.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     printf("qt_blend_argb24_on_rgb16: dst=(%p, %d), src=(%p, %d), dim=(%d, %d) alpha=%d\n",
            destPixels, dbpl, srcPixels, sbpl, w, h, const_alpha);
 #endif
     if (const_alpha != 256) {
         SourceAndConstAlpha alphaFunc(const_alpha);
         qt_blend_argb24_on_rgb16(destPixels, dbpl, srcPixels, sbpl, w, h, alphaFunc);
     } else {
         SourceOnlyAlpha alphaFunc;
         qt_blend_argb24_on_rgb16(destPixels, dbpl, srcPixels, sbpl, w, h, alphaFunc);
     }
 }
qt_blend_argb32_on_argb32()
static void qt_blend_argb32_on_argb32 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, int w, int h, int const_alpha) static
Definition at line 491 of file qblendfunctions.cpp.
Referenced by qt_blend_rgb32_on_rgb32().
 {
 #ifdef QT_DEBUG_DRAW
     fprintf(stdout, "qt_blend_argb32_on_argb32: dst=(%p, %d), src=(%p, %d), dim=(%d, %d) alpha=%d\n",
             destPixels, dbpl, srcPixels, sbpl, w, h, const_alpha);
     fflush(stdout);
 #endif
     const uint *src = (const uint *) srcPixels;
     uint *dst = (uint *) destPixels;
     if (const_alpha == 256) {
         for (int y=0; y<h; ++y) {
             for (int x=0; x<w; ++x) {
                 uint s = src[x];
                 if (s >= 0xff000000)
                     dst[x] = s;
                 else if (s != 0)
                     dst[x] = s + BYTE_MUL(dst[x], qAlpha(~s));
             }
             dst = (quint32 *)(((uchar *) dst) + dbpl);
             src = (const quint32 *)(((const uchar *) src) + sbpl);
         }
     } else if (const_alpha != 0) {
         const_alpha = (const_alpha * 255) >> 8;
         for (int y=0; y<h; ++y) {
             for (int x=0; x<w; ++x) {
                 uint s = BYTE_MUL(src[x], const_alpha);
                 dst[x] = s + BYTE_MUL(dst[x], qAlpha(~s));
             }
             dst = (quint32 *)(((uchar *) dst) + dbpl);
             src = (const quint32 *)(((const uchar *) src) + sbpl);
         }
     }
 }
qt_blend_argb32_on_rgb16()
static void qt_blend_argb32_on_rgb16 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, int w, int h, int const_alpha) static
Definition at line 395 of file qblendfunctions.cpp.
Referenced by qt_blend_rgb32_on_rgb16().
 {
     if (const_alpha != 256) {
         qt_blend_argb32_on_rgb16_const_alpha(destPixels, dbpl, srcPixels, sbpl, w, h, const_alpha);
         return;
     }
     quint16 *dst = (quint16 *) destPixels;
     quint32 *src = (quint32 *) srcPixels;
     for (int y=0; y<h; ++y) {
         for (int x=0; x<w; ++x) {
             quint32 spix = src[x];
             quint32 alpha = spix >> 24;
             if (alpha == 255) {
                 dst[x] = convert_argb32_to_rgb16(spix);
             } else if (alpha != 0) {
                 quint32 dpix = dst[x];
                 quint32 sia = 255 - alpha;
                 quint32 sr = (spix >> 8) & 0xf800;
                 quint32 sg = (spix >> 5) & 0x07e0;
                 quint32 sb = (spix >> 3) & 0x001f;
                 quint32 dr = (dpix & 0x0000f800);
                 quint32 dg = (dpix & 0x000007e0);
                 quint32 db = (dpix & 0x0000001f);
                 quint32 siar = dr * sia;
                 quint32 siag = dg * sia;
                 quint32 siab = db * sia;
                 quint32 rr = sr + ((siar + (siar>>8) + (0x80 << 8)) >> 8);
                 quint32 rg = sg + ((siag + (siag>>8) + (0x80 << 3)) >> 8);
                 quint32 rb = sb + ((siab + (siab>>8) + (0x80 >> 3)) >> 8);
                 dst[x] = (rr & 0xf800)
                          | (rg & 0x07e0)
                          | (rb);
             }
         }
         dst = (quint16 *) (((uchar *) dst) + dbpl);
         src = (quint32 *) (((uchar *) src) + sbpl);
     }
 }
qt_blend_argb32_on_rgb16_const_alpha()
void qt_blend_argb32_on_rgb16_const_alpha (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, int w, int h, int const_alpha)
Definition at line 372 of file qblendfunctions.cpp.
Referenced by qt_blend_argb32_on_rgb16().
 {
     quint16 *dst = (quint16 *) destPixels;
     const quint32 *src = (const quint32 *) srcPixels;
     const_alpha = (const_alpha * 255) >> 8;
     for (int y=0; y<h; ++y) {
         for (int i = 0; i < w; ++i) {
             uint s = src[i];
             s = BYTE_MUL(s, const_alpha);
             int alpha = qAlpha(s);
             s = convert_argb32_to_rgb16(s);
             s += BYTE_MUL_RGB16(dst[i], 255 - alpha);
             dst[i] = s;
         }
         dst = (quint16 *)(((uchar *) dst) + dbpl);
         src = (const quint32 *)(((const uchar *) src) + sbpl);
     }
 }
qt_blend_rgb16_on_rgb16()
void qt_blend_rgb16_on_rgb16 (uchar * dst, int dbpl, const uchar * src, int sbpl, int w, int h, int const_alpha)
Definition at line 257 of file qblendfunctions.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     printf("qt_blend_rgb16_on_rgb16: dst=(%p, %d), src=(%p, %d), dim=(%d, %d) alpha=%d\n",
            dst, dbpl, src, sbpl, w, h, const_alpha);
 #endif
     if (const_alpha == 256) {
         if (w <= 64) {
             while (h--) {
                 QT_MEMCPY_USHORT(dst, src, w);
                 dst += dbpl;
                 src += sbpl;
             }
         } else {
             int length = w << 1;
             while (h--) {
                 memcpy(dst, src, length);
                 dst += dbpl;
                 src += sbpl;
             }
         }
     } else if (const_alpha != 0) {
         SourceAndConstAlpha alpha(const_alpha); // expects the 0-256 range
         quint16 *d = (quint16 *) dst;
         const quint16 *s = (const quint16 *) src;
         quint8 a = (255 * const_alpha) >> 8;
         quint8 ia = 255 - a;
         while (h--) {
             for (int x=0; x<w; ++x) {
                 d[x] = BYTE_MUL_RGB16(s[x], a) + BYTE_MUL_RGB16(d[x], ia);
             }
             d = (quint16 *)(((uchar *) d) + dbpl);
             s = (const quint16 *)(((const uchar *) s) + sbpl);
         }
     }
 }
qt_blend_rgb32_on_rgb16()
static void qt_blend_rgb32_on_rgb16 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, int w, int h, int const_alpha) static
Definition at line 448 of file qblendfunctions.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     printf("qt_blend_rgb32_on_rgb16: dst=(%p, %d), src=(%p, %d), dim=(%d, %d) alpha=%d\n",
            destPixels, dbpl, srcPixels, sbpl, w, h, const_alpha);
 #endif
     if (const_alpha != 256) {
         qt_blend_argb32_on_rgb16(destPixels, dbpl, srcPixels, sbpl, w, h, const_alpha);
         return;
     }
     const quint32 *src = (const quint32 *) srcPixels;
     int srcExtraStride = (sbpl >> 2) - w;
     int dstJPL = dbpl / 2;
     quint16 *dst = (quint16 *) destPixels;
     quint16 *dstEnd = dst + dstJPL * h;
     int dstExtraStride = dstJPL - w;
     while (dst < dstEnd) {
         const quint32 *srcEnd = src + w;
         while (src < srcEnd) {
             *dst = convert_argb32_to_rgb16(*src);
             ++dst;
             ++src;
         }
         dst += dstExtraStride;
         src += srcExtraStride;
     }
 }
qt_blend_rgb32_on_rgb32()
void qt_blend_rgb32_on_rgb32 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, int w, int h, int const_alpha)
Definition at line 530 of file qblendfunctions.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     fprintf(stdout, "qt_blend_rgb32_on_rgb32: dst=(%p, %d), src=(%p, %d), dim=(%d, %d) alpha=%d\n",
             destPixels, dbpl, srcPixels, sbpl, w, h, const_alpha);
     fflush(stdout);
 #endif
     if (const_alpha != 256) {
         qt_blend_argb32_on_argb32(destPixels, dbpl, srcPixels, sbpl, w, h, const_alpha);
         return;
     }
     const uint *src = (const uint *) srcPixels;
     uint *dst = (uint *) destPixels;
     if (w <= 64) {
         for (int y=0; y<h; ++y) {
             qt_memconvert(dst, src, w);
             dst = (quint32 *)(((uchar *) dst) + dbpl);
             src = (const quint32 *)(((const uchar *) src) + sbpl);
         }
     } else {
         int len = w * 4;
         for (int y=0; y<h; ++y) {
             memcpy(dst, src, len);
             dst = (quint32 *)(((uchar *) dst) + dbpl);
             src = (const quint32 *)(((const uchar *) src) + sbpl);
         }
     }
 }
qt_scale_image_argb24_on_rgb16()
void qt_scale_image_argb24_on_rgb16 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, int sh, const QRectF & targetRect, const QRectF & sourceRect, const QRect & clip, int const_alpha)
Definition at line 206 of file qblendfunctions.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     printf("qt_scale_argb24_on_rgb16: dst=(%p, %d), src=(%p, %d), target=(%d, %d), [%d x %d], src=(%d, %d) [%d x %d] alpha=%d\n",
            destPixels, dbpl, srcPixels, sbpl,
            targetRect.x(), targetRect.y(), targetRect.width(), targetRect.height(),
            sourceRect.x(), sourceRect.y(), sourceRect.width(), sourceRect.height(),
            const_alpha);
 #endif
     if (const_alpha == 256) {
         Blend_ARGB24_on_RGB16_SourceAlpha noAlpha;
         qt_scale_image_16bit<qargb8565>(destPixels, dbpl, srcPixels, sbpl, sh,
                                         targetRect, sourceRect, clip, noAlpha);
     } else {
         Blend_ARGB24_on_RGB16_SourceAndConstAlpha constAlpha(const_alpha);
         qt_scale_image_16bit<qargb8565>(destPixels, dbpl, srcPixels, sbpl, sh,
                                         targetRect, sourceRect, clip, constAlpha);
     }
 }
qt_scale_image_argb32_on_argb32()
void qt_scale_image_argb32_on_argb32 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, int sh, const QRectF & targetRect, const QRectF & sourceRect, const QRect & clip, int const_alpha)
Definition at line 638 of file qblendfunctions.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     printf("qt_scale_argb32_on_argb32: dst=(%p, %d), src=(%p, %d), target=(%d, %d), [%d x %d], src=(%d, %d) [%d x %d] alpha=%d\n",
            destPixels, dbpl, srcPixels, sbpl,
            targetRect.x(), targetRect.y(), targetRect.width(), targetRect.height(),
            sourceRect.x(), sourceRect.y(), sourceRect.width(), sourceRect.height(),
            const_alpha);
 #endif
     if (const_alpha == 256) {
         Blend_ARGB32_on_ARGB32_SourceAlpha sourceAlpha;
         qt_scale_image_32bit(destPixels, dbpl, srcPixels, sbpl, sh,
                              targetRect, sourceRect, clip, sourceAlpha);
     } else {
         Blend_ARGB32_on_ARGB32_SourceAndConstAlpha constAlpha(const_alpha);
         qt_scale_image_32bit(destPixels, dbpl, srcPixels, sbpl, sh,
                              targetRect, sourceRect, clip, constAlpha);
     }
 }
qt_scale_image_argb32_on_rgb16()
void qt_scale_image_argb32_on_rgb16 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, int sh, const QRectF & targetRect, const QRectF & sourceRect, const QRect & clip, int const_alpha)
Definition at line 232 of file qblendfunctions.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     printf("qt_scale_argb32_on_rgb16: dst=(%p, %d), src=(%p, %d), target=(%d, %d), [%d x %d], src=(%d, %d) [%d x %d] alpha=%d\n",
            destPixels, dbpl, srcPixels, sbpl,
            targetRect.x(), targetRect.y(), targetRect.width(), targetRect.height(),
            sourceRect.x(), sourceRect.y(), sourceRect.width(), sourceRect.height(),
            const_alpha);
 #endif
     if (const_alpha == 256) {
         Blend_ARGB32_on_RGB16_SourceAlpha noAlpha;
         qt_scale_image_16bit<quint32>(destPixels, dbpl, srcPixels, sbpl, sh,
                                       targetRect, sourceRect, clip, noAlpha);
     } else {
         Blend_ARGB32_on_RGB16_SourceAndConstAlpha constAlpha(const_alpha);
         qt_scale_image_16bit<quint32>(destPixels, dbpl, srcPixels, sbpl, sh,
                                      targetRect, sourceRect, clip, constAlpha);
     }
 }
qt_scale_image_rgb16_on_rgb16()
void qt_scale_image_rgb16_on_rgb16 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, int sh, const QRectF & targetRect, const QRectF & sourceRect, const QRect & clip, int const_alpha)
Definition at line 181 of file qblendfunctions.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     printf("qt_scale_rgb16_on_rgb16: dst=(%p, %d), src=(%p, %d), target=(%d, %d), [%d x %d], src=(%d, %d) [%d x %d] alpha=%d\n",
            destPixels, dbpl, srcPixels, sbpl,
            targetRect.x(), targetRect.y(), targetRect.width(), targetRect.height(),
            sourceRect.x(), sourceRect.y(), sourceRect.width(), sourceRect.height(),
            const_alpha);
 #endif
     if (const_alpha == 256) {
         Blend_RGB16_on_RGB16_NoAlpha noAlpha;
         qt_scale_image_16bit<quint16>(destPixels, dbpl, srcPixels, sbpl, sh,
                                       targetRect, sourceRect, clip, noAlpha);
     } else {
         Blend_RGB16_on_RGB16_ConstAlpha constAlpha(const_alpha);
         qt_scale_image_16bit<quint16>(destPixels, dbpl, srcPixels, sbpl, sh,
                                      targetRect, sourceRect, clip, constAlpha);
     }
 }
qt_scale_image_rgb32_on_rgb32()
void qt_scale_image_rgb32_on_rgb32 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, int sh, const QRectF & targetRect, const QRectF & sourceRect, const QRect & clip, int const_alpha)
Definition at line 613 of file qblendfunctions.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     printf("qt_scale_rgb32_on_rgb32: dst=(%p, %d), src=(%p, %d), target=(%d, %d), [%d x %d], src=(%d, %d) [%d x %d] alpha=%d\n",
            destPixels, dbpl, srcPixels, sbpl,
            targetRect.x(), targetRect.y(), targetRect.width(), targetRect.height(),
            sourceRect.x(), sourceRect.y(), sourceRect.width(), sourceRect.height(),
            const_alpha);
 #endif
     if (const_alpha == 256) {
         Blend_RGB32_on_RGB32_NoAlpha noAlpha;
         qt_scale_image_32bit(destPixels, dbpl, srcPixels, sbpl, sh,
                              targetRect, sourceRect, clip, noAlpha);
     } else {
         Blend_RGB32_on_RGB32_ConstAlpha constAlpha(const_alpha);
         qt_scale_image_32bit(destPixels, dbpl, srcPixels, sbpl, sh,
                              targetRect, sourceRect, clip, constAlpha);
     }
 }
qt_transform_image_argb24_on_rgb16()
void qt_transform_image_argb24_on_rgb16 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, const QRectF & targetRect, const QRectF & sourceRect, const QRect & clip, const QTransform & targetRectTransform, int const_alpha)
Definition at line 684 of file qblendfunctions.cpp.
 {
     if (const_alpha == 256) {
         Blend_ARGB24_on_RGB16_SourceAlpha noAlpha;
         qt_transform_image(reinterpret_cast<quint16 *>(destPixels), dbpl,
                            reinterpret_cast<const qargb8565 *>(srcPixels), sbpl,
                            targetRect, sourceRect, clip, targetRectTransform, noAlpha);
     } else {
         Blend_ARGB24_on_RGB16_SourceAndConstAlpha constAlpha(const_alpha);
         qt_transform_image(reinterpret_cast<quint16 *>(destPixels), dbpl,
                            reinterpret_cast<const qargb8565 *>(srcPixels), sbpl,
                            targetRect, sourceRect, clip, targetRectTransform, constAlpha);
     }
 }
qt_transform_image_argb32_on_argb32()
void qt_transform_image_argb32_on_argb32 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, const QRectF & targetRect, const QRectF & sourceRect, const QRect & clip, const QTransform & targetRectTransform, int const_alpha)
Definition at line 749 of file qblendfunctions.cpp.
 {
     if (const_alpha == 256) {
         Blend_ARGB32_on_ARGB32_SourceAlpha sourceAlpha;
         qt_transform_image(reinterpret_cast<quint32 *>(destPixels), dbpl,
                            reinterpret_cast<const quint32 *>(srcPixels), sbpl,
                            targetRect, sourceRect, clip, targetRectTransform, sourceAlpha);
     } else {
         Blend_ARGB32_on_ARGB32_SourceAndConstAlpha constAlpha(const_alpha);
         qt_transform_image(reinterpret_cast<quint32 *>(destPixels), dbpl,
                            reinterpret_cast<const quint32 *>(srcPixels), sbpl,
                            targetRect, sourceRect, clip, targetRectTransform, constAlpha);
     }
 }
qt_transform_image_argb32_on_rgb16()
void qt_transform_image_argb32_on_rgb16 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, const QRectF & targetRect, const QRectF & sourceRect, const QRect & clip, const QTransform & targetRectTransform, int const_alpha)
Definition at line 706 of file qblendfunctions.cpp.
 {
     if (const_alpha == 256) {
         Blend_ARGB32_on_RGB16_SourceAlpha noAlpha;
         qt_transform_image(reinterpret_cast<quint16 *>(destPixels), dbpl,
                            reinterpret_cast<const quint32 *>(srcPixels), sbpl,
                            targetRect, sourceRect, clip, targetRectTransform, noAlpha);
     } else {
         Blend_ARGB32_on_RGB16_SourceAndConstAlpha constAlpha(const_alpha);
         qt_transform_image(reinterpret_cast<quint16 *>(destPixels), dbpl,
                            reinterpret_cast<const quint32 *>(srcPixels), sbpl,
                            targetRect, sourceRect, clip, targetRectTransform, constAlpha);
     }
 }
qt_transform_image_rgb16_on_rgb16()
void qt_transform_image_rgb16_on_rgb16 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, const QRectF & targetRect, const QRectF & sourceRect, const QRect & clip, const QTransform & targetRectTransform, int const_alpha)
Definition at line 663 of file qblendfunctions.cpp.
 {
     if (const_alpha == 256) {
         Blend_RGB16_on_RGB16_NoAlpha noAlpha;
         qt_transform_image(reinterpret_cast<quint16 *>(destPixels), dbpl,
                            reinterpret_cast<const quint16 *>(srcPixels), sbpl,
                            targetRect, sourceRect, clip, targetRectTransform, noAlpha);
     } else {
         Blend_RGB16_on_RGB16_ConstAlpha constAlpha(const_alpha);
         qt_transform_image(reinterpret_cast<quint16 *>(destPixels), dbpl,
                            reinterpret_cast<const quint16 *>(srcPixels), sbpl,
                            targetRect, sourceRect, clip, targetRectTransform, constAlpha);
     }
 }
qt_transform_image_rgb32_on_rgb32()
void qt_transform_image_rgb32_on_rgb32 (uchar * destPixels, int dbpl, const uchar * srcPixels, int sbpl, const QRectF & targetRect, const QRectF & sourceRect, const QRect & clip, const QTransform & targetRectTransform, int const_alpha)
Definition at line 728 of file qblendfunctions.cpp.
 {
     if (const_alpha == 256) {
         Blend_RGB32_on_RGB32_NoAlpha noAlpha;
         qt_transform_image(reinterpret_cast<quint32 *>(destPixels), dbpl,
                            reinterpret_cast<const quint32 *>(srcPixels), sbpl,
                            targetRect, sourceRect, clip, targetRectTransform, noAlpha);
     } else {
         Blend_RGB32_on_RGB32_ConstAlpha constAlpha(const_alpha);
         qt_transform_image(reinterpret_cast<quint32 *>(destPixels), dbpl,
                            reinterpret_cast<const quint32 *>(srcPixels), sbpl,
                            targetRect, sourceRect, clip, targetRectTransform, constAlpha);
     }
 }
Variable Documentation
qBlendFunctions
SrcOverBlendFunc qBlendFunctions[QImage::NImageFormats][QImage::NImageFormats]
Definition at line 1062 of file qblendfunctions.cpp.
Referenced by QRasterPaintEngine::drawImage(), and qInitDrawhelperAsm().
qScaleFunctions
SrcOverScaleFunc qScaleFunctions[QImage::NImageFormats][QImage::NImageFormats]
Definition at line 770 of file qblendfunctions.cpp.
Referenced by QRasterPaintEngine::drawImage(), and qInitDrawhelperAsm().
qTransformFunctions
SrcOverTransformFunc qTransformFunctions[QImage::NImageFormats][QImage::NImageFormats]
Definition at line 1353 of file qblendfunctions.cpp.
Referenced by QRasterPaintEngine::drawImage(), and qInitDrawhelperAsm().