Qt 4.8: /src/gui/kernel/qboxlayout.cpp File Reference
qboxlayout.cpp File Reference
#include "qboxlayout.h"
#include "qapplication.h"
#include "qwidget.h"
#include "qlist.h"
#include "qsizepolicy.h"
#include "qvector.h"
#include "qlayoutengine_p.h"
#include "qlayout_p.h"
Classes
struct QBoxLayoutItem
class QBoxLayoutPrivate
Functions
static bool checkWidget (QLayout *layout, QWidget *widget)
static bool horz (QBoxLayout::Direction dir)
Function Documentation
checkWidget()
static bool checkWidget (QLayout * layout, QWidget * widget) static
Definition at line 58 of file qboxlayout.cpp.
Referenced by QBoxLayout::insertWidget().
 {
     if (!widget) {
         qWarning("QLayout: Cannot add null widget to %s/%s", layout->metaObject()->className(),
                   layout->objectName().toLocal8Bit().data());
         return false;
     }
     return true;
 }
horz()
static bool horz (QBoxLayout::Direction dir) inline static
Definition at line 149 of file qboxlayout.cpp.
Referenced by QBoxLayout::addStrut(), QBoxLayoutPrivate::calcHfw(), QBoxLayoutPrivate::effectiveMargins(), QBoxLayout::insertSpacing(), QBoxLayout::insertStretch(), QBoxLayout::setDirection(), QBoxLayout::setGeometry(), and QBoxLayoutPrivate::setupGeom().
 {
     return dir == QBoxLayout::RightToLeft || dir == QBoxLayout::LeftToRight;
 }