Qt 4.8: /src/gui/painting/qbrush.cpp File Reference
qbrush.cpp File Reference
#include "qbrush.h"
#include "qpixmap.h"
#include "qbitmap.h"
#include "qpixmapcache.h"
#include "qdatastream.h"
#include "qvariant.h"
#include "qline.h"
#include "qdebug.h"
#include <QtCore/qcoreapplication.h>
#include "private/qstylehelper_p.h"
#include <QtCore/qnumeric.h>
Classes
struct QBrushDataPointerDeleter
class QBrushPatternImageCache
class QGlobalStaticDeleter< QBrushData >
struct QGradientBrushData
struct QTexturedBrushData
Macros
#define Q_DUMMY_ACCESSOR union {void *p; uint i;}; p = dummy;
Functions
QDebug operator<< (QDebug dbg, const QBrush &b)
QDataStream & operator<< (QDataStream &s, const QBrush &b)
QDataStream & operator>> (QDataStream &s, QBrush &b)
Q_GLOBAL_STATIC_WITH_INITIALIZER (QBrushPatternImageCache, qt_brushPatternImageCache, { qAddPostRoutine(qt_cleanup_brush_pattern_image_cache);}) static void qt_cleanup_brush_pattern_image_cache()
Q_GLOBAL_STATIC_WITH_INITIALIZER (QBrushData, nullBrushInstance, { x->ref=1;x->style=Qt::BrushStyle(0);x->color=Qt::black;}) static bool qbrush_check_type(Qt
bool Q_GUI_EXPORT qHasPixmapTexture (const QBrush &brush)
static void qt_cleanup_brush_pattern_image_cache ()
Q_GUI_EXPORT QImage qt_imageForBrush (int brushStyle, bool invert)
Q_GUI_EXPORT bool qt_isExtendedRadialGradient (const QBrush &brush)
const uchar * qt_patternForBrush (int brushStyle, bool invert)
QPixmap qt_pixmapForBrush (int brushStyle, bool invert)
static QPointF qt_radial_gradient_adapt_focal_point (const QPointF &center, qreal radius, const QPointF &focalPoint)
Macro Definition Documentation
Q_DUMMY_ACCESSOR
#define Q_DUMMY_ACCESSOR union {void *p; uint i;}; p = dummy;
Definition at line 1530 of file qbrush.cpp.
Referenced by QGradient::coordinateMode(), QRadialGradient::focalRadius(), QGradient::interpolationMode(), QGradient::setCoordinateMode(), QRadialGradient::setFocalRadius(), and QGradient::setInterpolationMode().
Function Documentation
operator<<() [1/2]
QDebug operator<< (QDebug dbg, const QBrush & b)
Warning
This function is not part of the public interface.
Definition at line 1058 of file qbrush.cpp.
 {
 #ifndef Q_BROKEN_DEBUG_STREAM
     static const char *BRUSH_STYLES[] = {
      "NoBrush",
      "SolidPattern",
      "Dense1Pattern",
      "Dense2Pattern",
      "Dense3Pattern",
      "Dense4Pattern",
      "Dense5Pattern",
      "Dense6Pattern",
      "Dense7Pattern",
      "HorPattern",
      "VerPattern",
      "CrossPattern",
      "BDiagPattern",
      "FDiagPattern",
      "DiagCrossPattern",
      "LinearGradientPattern",
      "RadialGradientPattern",
      "ConicalGradientPattern",
      0, 0, 0, 0, 0, 0,
      "TexturePattern" // 24
     };
     dbg.nospace() << "QBrush(" << b.color() << ',' << BRUSH_STYLES[b.style()] << ')';
     return dbg.space();
 #else
     qWarning("This compiler doesn't support streaming QBrush to QDebug");
     return dbg;
     Q_UNUSED(b);
 #endif
 }
operator<<() [2/2]
QDataStream& operator<< (QDataStream & s, const QBrush & b) related
Definition at line 1111 of file qbrush.cpp.
Referenced by QBrush::setColor().
 {
     quint8 style = (quint8) b.style();
     bool gradient_style = false;
     if (style == Qt::LinearGradientPattern || style == Qt::RadialGradientPattern
         || style == Qt::ConicalGradientPattern)
         gradient_style = true;
     if (s.version() < QDataStream::Qt_4_0 && gradient_style)
         style = Qt::NoBrush;
     s << style << b.color();
     if (b.style() == Qt::TexturePattern) {
         s << b.texture();
     } else if (s.version() >= QDataStream::Qt_4_0 && gradient_style) {
         const QGradient *gradient = b.gradient();
         int type_as_int = int(gradient->type());
         s << type_as_int;
         if (s.version() >= QDataStream::Qt_4_3) {
             s << int(gradient->spread());
             s << int(gradient->coordinateMode());
         }
         if (s.version() >= QDataStream::Qt_4_5)
             s << int(gradient->interpolationMode());
         if (sizeof(qreal) == sizeof(double)) {
             s << gradient->stops();
         } else {
             // ensure that we write doubles here instead of streaming the stops
             // directly; otherwise, platforms that redefine qreal might generate
             // data that cannot be read on other platforms.
             QVector<QGradientStop> stops = gradient->stops();
             s << quint32(stops.size());
             for (int i = 0; i < stops.size(); ++i) {
                 const QGradientStop &stop = stops.at(i);
                 s << QPair<double, QColor>(double(stop.first), stop.second);
             }
         }
         if (gradient->type() == QGradient::LinearGradient) {
             s << static_cast<const QLinearGradient *>(gradient)->start();
             s << static_cast<const QLinearGradient *>(gradient)->finalStop();
         } else if (gradient->type() == QGradient::RadialGradient) {
             s << static_cast<const QRadialGradient *>(gradient)->center();
             s << static_cast<const QRadialGradient *>(gradient)->focalPoint();
             s << (double) static_cast<const QRadialGradient *>(gradient)->radius();
         } else { // type == Conical
             s << static_cast<const QConicalGradient *>(gradient)->center();
             s << (double) static_cast<const QConicalGradient *>(gradient)->angle();
         }
     }
     if (s.version() >= QDataStream::Qt_4_3)
         s << b.transform();
     return s;
 }
operator>>()
QDataStream& operator>> (QDataStream & s, QBrush & b) related
Definition at line 1182 of file qbrush.cpp.
Referenced by QBrush::setColor().
 {
     quint8 style;
     QColor color;
     s >> style;
     s >> color;
     if (style == Qt::TexturePattern) {
         QPixmap pm;
         s >> pm;
         b = QBrush(color, pm);
     } else if (style == Qt::LinearGradientPattern
                || style == Qt::RadialGradientPattern
                || style == Qt::ConicalGradientPattern) {
         int type_as_int;
         QGradient::Type type;
         QGradientStops stops;
         QGradient::CoordinateMode cmode = QGradient::LogicalMode;
         QGradient::Spread spread = QGradient::PadSpread;
         QGradient::InterpolationMode imode = QGradient::ColorInterpolation;
         s >> type_as_int;
         type = QGradient::Type(type_as_int);
         if (s.version() >= QDataStream::Qt_4_3) {
             s >> type_as_int;
             spread = QGradient::Spread(type_as_int);
             s >> type_as_int;
             cmode = QGradient::CoordinateMode(type_as_int);
         }
         if (s.version() >= QDataStream::Qt_4_5) {
             s >> type_as_int;
             imode = QGradient::InterpolationMode(type_as_int);
         }
         if (sizeof(qreal) == sizeof(double)) {
             s >> stops;
         } else {
             quint32 numStops;
             double n;
             QColor c;
             s >> numStops;
             for (quint32 i = 0; i < numStops; ++i) {
                 s >> n >> c;
                 stops << QPair<qreal, QColor>(n, c);
             }
         }
         if (type == QGradient::LinearGradient) {
             QPointF p1, p2;
             s >> p1;
             s >> p2;
             QLinearGradient lg(p1, p2);
             lg.setStops(stops);
             lg.setSpread(spread);
             lg.setCoordinateMode(cmode);
             lg.setInterpolationMode(imode);
             b = QBrush(lg);
         } else if (type == QGradient::RadialGradient) {
             QPointF center, focal;
             double radius;
             s >> center;
             s >> focal;
             s >> radius;
             QRadialGradient rg(center, radius, focal);
             rg.setStops(stops);
             rg.setSpread(spread);
             rg.setCoordinateMode(cmode);
             rg.setInterpolationMode(imode);
             b = QBrush(rg);
         } else { // type == QGradient::ConicalGradient
             QPointF center;
             double angle;
             s >> center;
             s >> angle;
             QConicalGradient cg(center, angle);
             cg.setStops(stops);
             cg.setSpread(spread);
             cg.setCoordinateMode(cmode);
             cg.setInterpolationMode(imode);
             b = QBrush(cg);
         }
     } else {
         b = QBrush(color, (Qt::BrushStyle)style);
     }
     if (s.version() >= QDataStream::Qt_4_3) {
         QTransform transform;
         s >> transform;
         b.setTransform(transform);
     }
     return s;
 }
Q_GLOBAL_STATIC_WITH_INITIALIZER() [1/2]
Q_GLOBAL_STATIC_WITH_INITIALIZER (QBrushPatternImageCache , qt_brushPatternImageCache , { qAddPostRoutine(qt_cleanup_brush_pattern_image_cache);})
Definition at line 157 of file qbrush.cpp.
{
                                      qAddPostRoutine(qt_cleanup_brush_pattern_image_cache);
                                  })
 static void qt_cleanup_brush_pattern_image_cache()
 {
     qt_brushPatternImageCache()->cleanup();
 }
Q_GLOBAL_STATIC_WITH_INITIALIZER() [2/2]
Q_GLOBAL_STATIC_WITH_INITIALIZER (QBrushData , nullBrushInstance , { x->ref=1;x->style=Qt::BrushStyle(0);x->color=Qt::black;})
Definition at line 365 of file qbrush.cpp.
{
                                      x->ref = 1;
                                      x->style = Qt::BrushStyle(0);
                                      x->color = Qt::black;
                                  })
 static bool qbrush_check_type(Qt::BrushStyle style) {
     switch (style) {
     case Qt::TexturePattern:
          qWarning("QBrush: Incorrect use of TexturePattern");
          break;
     case Qt::LinearGradientPattern:
     case Qt::RadialGradientPattern:
     case Qt::ConicalGradientPattern:
         qWarning("QBrush: Wrong use of a gradient pattern");
         break;
     default:
         return true;
     }
     return false;
 }
qHasPixmapTexture()
bool Q_GUI_EXPORT qHasPixmapTexture (const QBrush & brush)
Definition at line 223 of file qbrush.cpp.
Referenced by check_gradient(), QTextHtmlExporter::emitBackgroundAttribute(), QTextHtmlExporter::emitBlock(), is_brush_transparent(), QGL2PaintEngineExPrivate::setBrush(), QSpanData::setup(), QGL2PaintEngineExPrivate::updateBrushUniforms(), and QPainterPrivate::updateEmulationSpecifier().
 {
     if (brush.style() != Qt::TexturePattern)
         return false;
     QTexturedBrushData *tx_data = static_cast<QTexturedBrushData *>(brush.d.data());
     return tx_data->m_has_pixmap_texture;
 }
qt_cleanup_brush_pattern_image_cache()
static void qt_cleanup_brush_pattern_image_cache () static
Referenced by Q_GLOBAL_STATIC_WITH_INITIALIZER().
qt_imageForBrush()
Q_GUI_EXPORT QImage qt_imageForBrush (int brushStyle, bool invert)
Definition at line 167 of file qbrush.cpp.
Referenced by QOpenGLPaintEnginePrivate::composite(), QVGPaintEnginePrivate::roundedRectPath(), QVGPaintEnginePrivate::setBrush(), QSpanData::setup(), and QGL2PaintEngineExPrivate::updateBrushTexture().
 {
     return qt_brushPatternImageCache()->getImage(brushStyle, invert);
 }
qt_isExtendedRadialGradient()
Q_GUI_EXPORT bool qt_isExtendedRadialGradient (const QBrush & brush)
Definition at line 881 of file qbrush.cpp.
Referenced by QOpenGLPaintEngine::fill(), QOpenGLPaintEnginePrivate::fillPath(), QBrush::isOpaque(), QVGPaintEnginePrivate::needsEmulation(), QPainterPrivate::updateEmulationSpecifier(), QPainterPrivate::updateInvMatrix(), and QOpenGLPaintEnginePrivate::updateUseEmulation().
 {
     if (brush.style() == Qt::RadialGradientPattern) {
         const QGradient *g = brush.gradient();
         const QRadialGradient *rg = static_cast<const QRadialGradient *>(g);
         if (!qFuzzyIsNull(rg->focalRadius()))
             return true;
         QPointF delta = rg->focalPoint() - rg->center();
         if (delta.x() * delta.x() + delta.y() * delta.y() > rg->radius() * rg->radius())
             return true;
     }
     return false;
 }
qt_patternForBrush()
const uchar* qt_patternForBrush (int brushStyle, bool invert)
Definition at line 56 of file qbrush.cpp.
Referenced by QBrushPatternImageCache::init(), and qt_pixmapForBrush().
 {
     Q_ASSERT(brushStyle > Qt::SolidPattern && brushStyle < Qt::LinearGradientPattern);
     if(invert) {
         static const uchar dense1_pat[] = { 0xff, 0xbb, 0xff, 0xff, 0xff, 0xbb, 0xff, 0xff };
         static const uchar dense2_pat[] = { 0x77, 0xff, 0xdd, 0xff, 0x77, 0xff, 0xdd, 0xff };
         static const uchar dense3_pat[] = { 0x55, 0xbb, 0x55, 0xee, 0x55, 0xbb, 0x55, 0xee };
         static const uchar dense4_pat[] = { 0xaa, 0x55, 0xaa, 0x55, 0xaa, 0x55, 0xaa, 0x55 };
         static const uchar dense5_pat[] = { 0xaa, 0x44, 0xaa, 0x11, 0xaa, 0x44, 0xaa, 0x11 };
         static const uchar dense6_pat[] = { 0x88, 0x00, 0x22, 0x00, 0x88, 0x00, 0x22, 0x00 };
         static const uchar dense7_pat[] = { 0x00, 0x44, 0x00, 0x00, 0x00, 0x44, 0x00, 0x00 };
         static const uchar hor_pat[]    = { 0x00, 0x00, 0x00, 0xff, 0x00, 0x00, 0x00, 0x00 };
         static const uchar ver_pat[]    = { 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10 };
         static const uchar cross_pat[]  = { 0x10, 0x10, 0x10, 0xff, 0x10, 0x10, 0x10, 0x10 };
         static const uchar bdiag_pat[]  = { 0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01 };
         static const uchar fdiag_pat[]  = { 0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80 };
         static const uchar dcross_pat[] = { 0x81, 0x42, 0x24, 0x18, 0x18, 0x24, 0x42, 0x81 };
         static const uchar *const pat_tbl[] = {
             dense1_pat, dense2_pat, dense3_pat, dense4_pat, dense5_pat,
             dense6_pat, dense7_pat,
             hor_pat, ver_pat, cross_pat, bdiag_pat, fdiag_pat, dcross_pat };
         return pat_tbl[brushStyle - Qt::Dense1Pattern];
     }
     static const uchar dense1_pat[] = { 0x00, 0x44, 0x00, 0x00, 0x00, 0x44, 0x00, 0x00 };
     static const uchar dense2_pat[] = { 0x88, 0x00, 0x22, 0x00, 0x88, 0x00, 0x22, 0x00 };
     static const uchar dense3_pat[] = { 0xaa, 0x44, 0xaa, 0x11, 0xaa, 0x44, 0xaa, 0x11 };
     static const uchar dense4_pat[] = { 0x55, 0xaa, 0x55, 0xaa, 0x55, 0xaa, 0x55, 0xaa };
     static const uchar dense5_pat[] = { 0x55, 0xbb, 0x55, 0xee, 0x55, 0xbb, 0x55, 0xee };
     static const uchar dense6_pat[] = { 0x77, 0xff, 0xdd, 0xff, 0x77, 0xff, 0xdd, 0xff };
     static const uchar dense7_pat[] = { 0xff, 0xbb, 0xff, 0xff, 0xff, 0xbb, 0xff, 0xff };
     static const uchar hor_pat[]    = { 0xff, 0xff, 0xff, 0x00, 0xff, 0xff, 0xff, 0xff };
     static const uchar ver_pat[]    = { 0xef, 0xef, 0xef, 0xef, 0xef, 0xef, 0xef, 0xef };
     static const uchar cross_pat[]  = { 0xef, 0xef, 0xef, 0x00, 0xef, 0xef, 0xef, 0xef };
     static const uchar bdiag_pat[]  = { 0x7f, 0xbf, 0xdf, 0xef, 0xf7, 0xfb, 0xfd, 0xfe };
     static const uchar fdiag_pat[]  = { 0xfe, 0xfd, 0xfb, 0xf7, 0xef, 0xdf, 0xbf, 0x7f };
     static const uchar dcross_pat[] = { 0x7e, 0xbd, 0xdb, 0xe7, 0xe7, 0xdb, 0xbd, 0x7e };
     static const uchar *const pat_tbl[] = {
         dense1_pat, dense2_pat, dense3_pat, dense4_pat, dense5_pat,
         dense6_pat, dense7_pat,
         hor_pat, ver_pat, cross_pat, bdiag_pat, fdiag_pat, dcross_pat };
     return pat_tbl[brushStyle - Qt::Dense1Pattern];
 }
qt_pixmapForBrush()
QPixmap qt_pixmapForBrush (int brushStyle, bool invert)
Definition at line 99 of file qbrush.cpp.
Referenced by getPatternFill(), and QX11PaintEngine::updateBrush().
 {
     QPixmap pm;
     QString key = QLatin1Literal("$qt-brush$")
                   % HexString<uint>(brushStyle)
                   % QLatin1Char(invert ? '1' : '0');
     if (!QPixmapCache::find(key, pm)) {
         pm = QBitmap::fromData(QSize(8, 8), qt_patternForBrush(brushStyle, invert),
                                QImage::Format_MonoLSB);
         QPixmapCache::insert(key, pm);
     }
     return pm;
 }
qt_radial_gradient_adapt_focal_point()
static QPointF qt_radial_gradient_adapt_focal_point (const QPointF & center, qreal radius, const QPointF & focalPoint) static
Definition at line 1933 of file qbrush.cpp.
Referenced by QRadialGradient::QRadialGradient().
 {
     // We have a one pixel buffer zone to avoid numerical instability on the
     // circle border
     //### this is hacky because technically we should adjust based on current matrix
     const qreal compensated_radius = radius - radius * qreal(0.001);
     QLineF line(center, focalPoint);
     if (line.length() > (compensated_radius))
         line.setLength(compensated_radius);
     return line.p2();
 }