Qt 4.8: /src/corelib/tools/qbytearray.cpp File Reference
qbytearray.cpp File Reference
#include "qbytearray.h"
#include "qbytearraymatcher.h"
#include "qtools_p.h"
#include "qstring.h"
#include "qlist.h"
#include "qlocale.h"
#include "qlocale_p.h"
#include "qscopedpointer.h"
#include <qdatastream.h>
#include <zlib.h>
#include <ctype.h>
#include <limits.h>
#include <string.h>
#include <stdlib.h>
Macros
#define IS_RAW_DATA(d) ((d)->data != (d)->array)
#define REHASH(a)
Functions
static int lastIndexOfHelper (const char *haystack, int l, const char *needle, int ol, int from)
static void q_fromPercentEncoding (QByteArray *ba, char percent)
void q_fromPercentEncoding (QByteArray *ba)
void q_normalizePercentEncoding (QByteArray *ba, const char *exclude)
static bool q_strchr (const char str[], char chr)
static void q_toPercentEncoding (QByteArray *ba, const char *dontEncode, const char *alsoEncode, char percent)
void q_toPercentEncoding (QByteArray *ba, const char *exclude, const char *include)
int qAllocMore (int alloc, int extra)
static QByteArray & qbytearray_insert (QByteArray *ba, int pos, const char *arr, int len)
Inserts len bytes from the array arr at position pos and returns a reference the modified byte array.
int qFindByteArray (const char *haystack0, int haystackLen, int from, const char *needle0, int needleLen)
static bool qIsUpper (char c)
int qstrcmp (const QByteArray &str1, const char *str2)
int qstrcmp (const QByteArray &str1, const QByteArray &str2)
static char qToLower (char c)
static char toHexHelper (char c)
Variables
static const quint16 crc_tbl [16]
Macro Definition Documentation
IS_RAW_DATA
#define IS_RAW_DATA (d) ((d)->data != (d)->array)
Definition at line 60 of file qbytearray.cpp.
Referenced by QByteArray::append(), and QByteArray::prepend().
REHASH
#define REHASH (a)
Value:
if (ol_minus_1 < sizeof(uint) * CHAR_BIT) \
        hashHaystack -= (a) << ol_minus_1; \
    hashHaystack <<= 1
Definition at line 2372 of file qbytearray.cpp.
Referenced by lastIndexOfHelper().
Function Documentation
lastIndexOfHelper()
static int lastIndexOfHelper (const char * haystack, int l, const char * needle, int ol, int from) static
Definition at line 2476 of file qbytearray.cpp.
Referenced by QByteArray::lastIndexOf().
 {
     int delta = l - ol;
     if (from < 0)
         from = delta;
     if (from < 0 || from > l)
         return -1;
     if (from > delta)
         from = delta;
     const char *end = haystack;
     haystack += from;
     const uint ol_minus_1 = ol - 1;
     const char *n = needle + ol_minus_1;
     const char *h = haystack + ol_minus_1;
     uint hashNeedle = 0, hashHaystack = 0;
     int idx;
     for (idx = 0; idx < ol; ++idx) {
         hashNeedle = ((hashNeedle<<1) + *(n-idx));
         hashHaystack = ((hashHaystack<<1) + *(h-idx));
     }
     hashHaystack -= *haystack;
     while (haystack >= end) {
         hashHaystack += *haystack;
         if (hashHaystack == hashNeedle && memcmp(needle, haystack, ol) == 0)
             return haystack - end;
         --haystack;
         REHASH(*(haystack + ol));
     }
     return -1;
 }
q_fromPercentEncoding() [1/2]
static void q_fromPercentEncoding (QByteArray * ba, char percent) static
Definition at line 4291 of file qbytearray.cpp.
Referenced by QByteArray::fromPercentEncoding(), q_fromPercentEncoding(), and q_normalizePercentEncoding().
 {
     if (ba->isEmpty())
         return;
     char *data = ba->data();
     const char *inputPtr = data;
     int i = 0;
     int len = ba->count();
     int outlen = 0;
     int a, b;
     char c;
     while (i < len) {
         c = inputPtr[i];
         if (c == percent && i + 2 < len) {
             a = inputPtr[++i];
             b = inputPtr[++i];
             if (a >= '0' && a <= '9') a -= '0';
             else if (a >= 'a' && a <= 'f') a = a - 'a' + 10;
             else if (a >= 'A' && a <= 'F') a = a - 'A' + 10;
             if (b >= '0' && b <= '9') b -= '0';
             else if (b >= 'a' && b <= 'f') b  = b - 'a' + 10;
             else if (b >= 'A' && b <= 'F') b  = b - 'A' + 10;
             *data++ = (char)((a << 4) | b);
         } else {
             *data++ = c;
         }
         ++i;
         ++outlen;
     }
     if (outlen != len)
         ba->truncate(outlen);
 }
q_fromPercentEncoding() [2/2]
void q_fromPercentEncoding (QByteArray * ba)
Definition at line 4331 of file qbytearray.cpp.
Referenced by fromPercentEncodingHelper(), and fromPercentEncodingMutable().
 {
     q_fromPercentEncoding(ba, '%');
 }
q_normalizePercentEncoding()
void q_normalizePercentEncoding (QByteArray * ba, const char * exclude)
Definition at line 4429 of file qbytearray.cpp.
Referenced by QUrlPrivate::normalized().
 {
     q_fromPercentEncoding(ba, '%');
     q_toPercentEncoding(ba, exclude, 0, '%');
 }
q_strchr()
static bool q_strchr (const char str[], char chr) inline static
Definition at line 4366 of file qbytearray.cpp.
Referenced by q_toPercentEncoding().
 {
     if (!str) return false;
     const char *ptr = str;
     char c;
     while ((c = *ptr++))
         if (c == chr)
             return true;
     return false;
 }
q_toPercentEncoding() [1/2]
static void q_toPercentEncoding (QByteArray * ba, const char * dontEncode, const char * alsoEncode, char percent) static
Definition at line 4384 of file qbytearray.cpp.
Referenced by q_normalizePercentEncoding(), q_toPercentEncoding(), and QByteArray::toPercentEncoding().
 {
     if (ba->isEmpty())
         return;
     QByteArray input = *ba;
     int len = input.count();
     const char *inputData = input.constData();
     char *output = 0;
     int length = 0;
     for (int i = 0; i < len; ++i) {
         unsigned char c = *inputData++;
         if (((c >= 0x61 && c <= 0x7A) // ALPHA
              || (c >= 0x41 && c <= 0x5A) // ALPHA
              || (c >= 0x30 && c <= 0x39) // DIGIT
              || c == 0x2D // -
              || c == 0x2E // .
              || c == 0x5F // _
              || c == 0x7E // ~
              || q_strchr(dontEncode, c))
             && !q_strchr(alsoEncode, c)) {
             if (output)
                 output[length] = c;
             ++length;
         } else {
             if (!output) {
                 // detach now
                 ba->resize(len*3); // worst case
                 output = ba->data();
             }
             output[length++] = percent;
             output[length++] = toHexHelper((c & 0xf0) >> 4);
             output[length++] = toHexHelper(c & 0xf);
         }
     }
     if (output)
         ba->truncate(length);
 }
q_toPercentEncoding() [2/2]
void q_toPercentEncoding (QByteArray * ba, const char * exclude, const char * include)
Definition at line 4424 of file qbytearray.cpp.
Referenced by toPercentEncodingHelper().
 {
     q_toPercentEncoding(ba, exclude, include, '%');
 }
qAllocMore()
int qAllocMore (int alloc, int extra)
Definition at line 70 of file qbytearray.cpp.
Referenced by QByteArray::append(), QFragmentMapData< QTextBlockData >::createFragment(), grow(), QVectorData::grow(), QString::grow(), and QByteArray::prepend().
 {
     Q_ASSERT(alloc >= 0 && extra >= 0);
     Q_ASSERT_X(alloc < (1 << 30) - extra, "qAllocMore", "Requested size is too large!");
     if (alloc == 0 && extra == 0)
         return 0;
     const int page = 1 << 12;
     int nalloc;
     alloc += extra;
     if (alloc < 1<<6) {
         nalloc = (1<<3) + ((alloc >>3) << 3);
     } else  {
         // don't do anything if the loop will overflow signed int.
         if (alloc >= INT_MAX/2)
             return INT_MAX;
         nalloc = (alloc < page) ? 1 << 3 : page;
         while (nalloc < alloc) {
             if (nalloc <= 0)
                 return INT_MAX;
             nalloc *= 2;
         }
     }
     return nalloc - extra;
 }
qbytearray_insert()
static QByteArray& qbytearray_insert (QByteArray * ba, int pos, const char * arr, int len) inline static
Inserts len bytes from the array arr at position pos and returns a reference the modified byte array.
Warning
This function is not part of the public interface.
Definition at line 1834 of file qbytearray.cpp.
Referenced by QByteArray::insert(), and QByteArray::replace().
 {
     Q_ASSERT(pos >= 0);
     if (pos < 0 || len <= 0 || arr == 0)
         return *ba;
     int oldsize = ba->size();
     ba->resize(qMax(pos, oldsize) + len);
     char *dst = ba->data();
     if (pos > oldsize)
         ::memset(dst + oldsize, 0x20, pos - oldsize);
     else
         ::memmove(dst + pos + len, dst + pos, oldsize - pos);
     memcpy(dst + pos, arr, len);
     return *ba;
 }
qFindByteArray()
int qFindByteArray (const char * haystack0, int haystackLen, int from, const char * needle, int needleLen)
Warning
This function is not part of the public interface.
Definition at line 275 of file qbytearraymatcher.cpp.
Referenced by QByteArray::indexOf().
 {
     const int l = haystackLen;
     const int sl = needleLen;
     if (from < 0)
         from += l;
     if (uint(sl + from) > (uint)l)
         return -1;
     if (!sl)
         return from;
     if (!l)
         return -1;
     if (sl == 1)
         return findChar(haystack0, haystackLen, needle[0], from);
     /*
       We use the Boyer-Moore algorithm in cases where the overhead
       for the skip table should pay off, otherwise we use a simple
       hash function.
     */
     if (l > 500 && sl > 5)
         return qFindByteArrayBoyerMoore(haystack0, haystackLen, from,
                                         needle, needleLen);
     /*
       We use some hashing for efficiency's sake. Instead of
       comparing strings, we compare the hash value of str with that
       of a part of this QString. Only if that matches, we call memcmp().
     */
     const char *haystack = haystack0 + from;
     const char *end = haystack0 + (l - sl);
     const uint sl_minus_1 = sl - 1;
     uint hashNeedle = 0, hashHaystack = 0;
     int idx;
     for (idx = 0; idx < sl; ++idx) {
         hashNeedle = ((hashNeedle<<1) + needle[idx]);
         hashHaystack = ((hashHaystack<<1) + haystack[idx]);
     }
     hashHaystack -= *(haystack + sl_minus_1);
     while (haystack <= end) {
         hashHaystack += *(haystack + sl_minus_1);
         if (hashHaystack == hashNeedle && *needle == *haystack
              && memcmp(needle, haystack, sl) == 0)
             return haystack - haystack0;
         REHASH(*haystack);
         ++haystack;
     }
     return -1;
 }
qIsUpper()
static bool qIsUpper (char c) inline static
Definition at line 637 of file qbytearray.cpp.
Referenced by QByteArray::setNum().
 {
     return c >= 'A' && c <= 'Z';
 }
qstrcmp() [1/2]
int qstrcmp (const QByteArray & str1, const char * str2)
Warning
This function is not part of the public interface.
Definition at line 336 of file qbytearray.cpp.
Referenced by QAccessibleObjectPrivate::actionList(), QDBusAdaptorConnector::addAdaptor(), QPrintPropertiesDialog::addItemToOptions(), QAudioDeviceInfoInternal::availableDevices(), QLocalePrivate::bytearrayToDouble(), QMetaObject::checkConnectArgs(), QCUPSSupport::collectMarkedOptionsHelper(), QPSQLDriver::commitTransaction(), QTest::compare_string_helper(), QFutureWatcherBase::connectNotify(), QNetworkSession::connectNotify(), QDBusAbstractInterface::connectNotify(), QAxClass< T >::createObject(), QDeclarativeVisualDataModelDataMetaObject::createProperty(), QScript::QMetaObjectWrapperObject::deleteProperty(), QFutureWatcherBase::disconnectNotify(), QNetworkSession::disconnectNotify(), QProxyStylePrivate::ensureBaseStyle(), QScript::QMetaObjectWrapperObject::getOwnPropertyDescriptor(), QScript::QMetaObjectWrapperObject::getOwnPropertySlot(), getStyle(), QObject::inherits(), QDeclarativeJS::integerFromString(), QScript::integerFromString(), QMetaMethod::invoke(), isProcessBeingDebugged(), QObject::killTimer(), QStyleSheetStyle::nativeFrameWidth(), QStyleSheetStyleSelector::nodeNameEquals(), QStyleSheetStyleSelector::nodeNames(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), QCUPSSupport::pageRect(), QCUPSSupport::paperRect(), parentWidget(), QPPDOptionsModel::parseChoices(), QCUPSSupport::ppdOption(), QApplicationPrivate::process_cmdline(), QVideoSurfaceFormat::property(), QScript::QMetaObjectWrapperObject::put(), QTest::qExec(), QTest::qInvokeTestMethod(), QRenderRule::QRenderRule(), QSQLite2DriverPrivate::QSQLite2DriverPrivate(), qt_check_if_internal_widget(), qt_init(), QAxObject::qt_metacast(), QAxWidget::qt_metacast(), QAxHostWidget::qt_metacast(), qt_parseEtcLpPrinters(), QBBSystemLocaleData::readHourFormat(), QBBSystemLocaleData::readMeasurementSystem(), QCUPSSupport::saveOptions(), QWizard::setDefaultProperty(), QFontDialogPrivate::setFont(), QObject::setObjectName(), QVideoSurfaceFormat::setProperty(), QDBusConnectionInterface::unregisterService(), and QAccessible::updateAccessibility().
 {
     if (!str2)
         return str1.isEmpty() ? 0 : +1;
     const char *str1data = str1.constData();
     const char *str1end = str1data + str1.length();
     for ( ; str1data < str1end && *str2; ++str1data, ++str2) {
         register int diff = int(uchar(*str1data)) - uchar(*str2);
         if (diff)
             // found a difference
             return diff;
     }
     // Why did we stop?
     if (*str2 != '\0')
         // not the null, so we stopped because str1 is shorter
         return -1;
     if (str1data < str1end)
         // we haven't reached the end, so str1 must be longer
         return +1;
     return 0;
 }
qstrcmp() [2/2]
int qstrcmp (const QByteArray & str1, const QByteArray & str2)
Warning
This function is not part of the public interface.
Definition at line 363 of file qbytearray.cpp.
 {
     int l1 = str1.length();
     int l2 = str2.length();
     int ret = memcmp(str1, str2, qMin(l1, l2));
     if (ret != 0)
         return ret;
     // they matched qMin(l1, l2) bytes
     // so the longer one is lexically after the shorter one
     return l1 - l2;
 }
qToLower()
static char qToLower (char c) inline static
Definition at line 642 of file qbytearray.cpp.
Referenced by QByteArray::setNum().
 {
     if (c >= 'A' && c <= 'Z')
         return c - 'A' + 'a';
     else
         return c;
 }
toHexHelper()
static char toHexHelper (char c) inline static
Definition at line 4378 of file qbytearray.cpp.
Referenced by q_toPercentEncoding().
 {
     static const char hexnumbers[] = "0123456789ABCDEF";
     return hexnumbers[c & 0xf];
 }
Variable Documentation
crc_tbl
const quint16 crc_tbl[16] static
Initial value:
= {
    0x0000, 0x1081, 0x2102, 0x3183,
    0x4204, 0x5285, 0x6306, 0x7387,
    0x8408, 0x9489, 0xa50a, 0xb58b,
    0xc60c, 0xd68d, 0xe70e, 0xf78f
}
Definition at line 413 of file qbytearray.cpp.
Referenced by QByteArray::qChecksum(), and qstrcmp().