Qt 4.8: /src/corelib/tools/qbytearray.h File Reference
qbytearray.h File Reference
#include <QtCore/qatomic.h>
#include <QtCore/qnamespace.h>
#include <string.h>
#include <stdarg.h>
Classes
class QByteArray
The QByteArray class provides an array of bytes.
struct QByteArray::Data
class QByteRef
class QList< T >
The QList class is a template class that provides lists.
Functions
bool operator!= (const QByteArray &a1, const QByteArray &a2)
bool operator!= (const QByteArray &a1, const char *a2)
bool operator!= (const char *a1, const QByteArray &a2)
const QByteArray operator+ (const QByteArray &a1, const QByteArray &a2)
const QByteArray operator+ (const QByteArray &a1, const char *a2)
const QByteArray operator+ (const QByteArray &a1, char a2)
const QByteArray operator+ (const char *a1, const QByteArray &a2)
const QByteArray operator+ (char a1, const QByteArray &a2)
bool operator< (const QByteArray &a1, const QByteArray &a2)
bool operator< (const QByteArray &a1, const char *a2)
bool operator< (const char *a1, const QByteArray &a2)
Q_CORE_EXPORT QDataStream & operator<< (QDataStream &, const QByteArray &)
bool operator<= (const QByteArray &a1, const QByteArray &a2)
bool operator<= (const QByteArray &a1, const char *a2)
bool operator<= (const char *a1, const QByteArray &a2)
bool operator== (const QByteArray &a1, const QByteArray &a2)
bool operator== (const QByteArray &a1, const char *a2)
bool operator== (const char *a1, const QByteArray &a2)
bool operator> (const QByteArray &a1, const QByteArray &a2)
bool operator> (const QByteArray &a1, const char *a2)
bool operator> (const char *a1, const QByteArray &a2)
bool operator>= (const QByteArray &a1, const QByteArray &a2)
bool operator>= (const QByteArray &a1, const char *a2)
bool operator>= (const char *a1, const QByteArray &a2)
Q_CORE_EXPORT QDataStream & operator>> (QDataStream &, QByteArray &)
Q_DECLARE_TYPEINFO (QByteArray, Q_MOVABLE_TYPE)
Q_CORE_EXPORT quint16 qChecksum (const char *s, uint len)
Q_CORE_EXPORT QByteArray qCompress (const uchar *data, int nbytes, int compressionLevel=-1)
QByteArray qCompress (const QByteArray &data, int compressionLevel=-1)
Q_CORE_EXPORT int qsnprintf (char *str, size_t n, const char *fmt,...)
Q_CORE_EXPORT int qstrcmp (const char *str1, const char *str2)
Q_CORE_EXPORT int qstrcmp (const QByteArray &str1, const QByteArray &str2)
Q_CORE_EXPORT int qstrcmp (const QByteArray &str1, const char *str2)
static int qstrcmp (const char *str1, const QByteArray &str2)
Q_CORE_EXPORT char * qstrcpy (char *dst, const char *src)
Q_CORE_EXPORT char * qstrdup (const char *)
Q_CORE_EXPORT int qstricmp (const char *, const char *)
uint qstrlen (const char *str)
int qstrncmp (const char *str1, const char *str2, uint len)
Q_CORE_EXPORT char * qstrncpy (char *dst, const char *src, uint len)
Q_CORE_EXPORT int qstrnicmp (const char *, const char *, uint len)
uint qstrnlen (const char *str, uint maxlen)
Q_CORE_EXPORT QByteArray qUncompress (const uchar *data, int nbytes)
QByteArray qUncompress (const QByteArray &data)
Q_CORE_EXPORT int qvsnprintf (char *str, size_t n, const char *fmt, va_list ap)
Function Documentation
operator!=() [1/3]
bool operator!= (const QByteArray & a1, const QByteArray & a2) related
Definition at line 533 of file qbytearray.h.
Referenced by QByteArray::isSharedWith().
 { return !(a1==a2); }
operator!=() [2/3]
bool operator!= (const QByteArray & a1, const char * a2) related
Definition at line 535 of file qbytearray.h.
 { return a2 ? qstrcmp(a1,a2) != 0 : !a1.isEmpty(); }
operator!=() [3/3]
bool operator!= (const char * a1, const QByteArray & a2) related
Definition at line 537 of file qbytearray.h.
 { return a1 ? qstrcmp(a1,a2) != 0 : !a2.isEmpty(); }
operator+() [1/5]
const QByteArray operator+ (const QByteArray & a1, const QByteArray & a2) related
Definition at line 564 of file qbytearray.h.
 { return QByteArray(a1) += a2; }
operator+() [2/5]
const QByteArray operator+ (const QByteArray & a1, const char * a2) related
Definition at line 566 of file qbytearray.h.
 { return QByteArray(a1) += a2; }
operator+() [3/5]
const QByteArray operator+ (const QByteArray & a1, char a2) related
Definition at line 568 of file qbytearray.h.
 { return QByteArray(a1) += a2; }
operator+() [4/5]
const QByteArray operator+ (const char * a1, const QByteArray & a2) related
Definition at line 570 of file qbytearray.h.
 { return QByteArray(a1) += a2; }
operator+() [5/5]
const QByteArray operator+ (char a1, const QByteArray & a2) related
Definition at line 572 of file qbytearray.h.
 { return QByteArray(&a1, 1) += a2; }
operator<() [1/3]
bool operator< (const QByteArray & a1, const QByteArray & a2) related
Definition at line 539 of file qbytearray.h.
Referenced by QByteArray::isSharedWith().
 { return qstrcmp(a1, a2) < 0; }
operator<() [2/3]
bool operator< (const QByteArray & a1, const char * a2) related
Definition at line 541 of file qbytearray.h.
 { return qstrcmp(a1, a2) < 0; }
operator<() [3/3]
bool operator< (const char * a1, const QByteArray & a2) related
Definition at line 543 of file qbytearray.h.
 { return qstrcmp(a1, a2) < 0; }
operator<<()
Q_CORE_EXPORT QDataStream& operator<< (QDataStream & , const QByteArray &) related
operator<=() [1/3]
bool operator<= (const QByteArray & a1, const QByteArray & a2) related
Definition at line 545 of file qbytearray.h.
Referenced by QVector< QPoint >::constData(), and QByteArray::isSharedWith().
 { return qstrcmp(a1, a2) <= 0; }
operator<=() [2/3]
bool operator<= (const QByteArray & a1, const char * a2) related
Definition at line 547 of file qbytearray.h.
 { return qstrcmp(a1, a2) <= 0; }
operator<=() [3/3]
bool operator<= (const char * a1, const QByteArray & a2) related
Definition at line 549 of file qbytearray.h.
 { return qstrcmp(a1, a2) <= 0; }
operator==() [1/3]
bool operator== (const QByteArray & a1, const QByteArray & a2) related
Definition at line 527 of file qbytearray.h.
Referenced by QByteArray::isSharedWith().
 { return (a1.size() == a2.size()) && (memcmp(a1.constData(), a2.constData(), a1.size())==0); }
operator==() [2/3]
bool operator== (const QByteArray & a1, const char * a2) related
Definition at line 529 of file qbytearray.h.
 { return a2 ? qstrcmp(a1,a2) == 0 : a1.isEmpty(); }
operator==() [3/3]
bool operator== (const char * a1, const QByteArray & a2) related
Definition at line 531 of file qbytearray.h.
 { return a1 ? qstrcmp(a1,a2) == 0 : a2.isEmpty(); }
operator>() [1/3]
bool operator> (const QByteArray & a1, const QByteArray & a2) related
Definition at line 551 of file qbytearray.h.
Referenced by QVector< QPoint >::constData(), QByteArray::isSharedWith(), and QUuid::operator!=().
 { return qstrcmp(a1, a2) > 0; }
operator>() [2/3]
bool operator> (const QByteArray & a1, const char * a2) related
Definition at line 553 of file qbytearray.h.
 { return qstrcmp(a1, a2) > 0; }
operator>() [3/3]
bool operator> (const char * a1, const QByteArray & a2) related
Definition at line 555 of file qbytearray.h.
 { return qstrcmp(a1, a2) > 0; }
operator>=() [1/3]
bool operator>= (const QByteArray & a1, const QByteArray & a2) related
Definition at line 557 of file qbytearray.h.
Referenced by QVector< QPoint >::constData(), and QByteArray::isSharedWith().
 { return qstrcmp(a1, a2) >= 0; }
operator>=() [2/3]
bool operator>= (const QByteArray & a1, const char * a2) related
Definition at line 559 of file qbytearray.h.
 { return qstrcmp(a1, a2) >= 0; }
operator>=() [3/3]
bool operator>= (const char * a1, const QByteArray & a2) related
Definition at line 561 of file qbytearray.h.
 { return qstrcmp(a1, a2) >= 0; }
operator>>()
Q_CORE_EXPORT QDataStream& operator>> (QDataStream & , QByteArray &) related
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QByteArray , Q_MOVABLE_TYPE)
Referenced by qUncompress().
qChecksum()
Q_CORE_EXPORT quint16 qChecksum (const char * s, uint len) related
Referenced by QPicturePrivate::checkFormat(), and QPicturePaintEngine::end().
qCompress() [1/2]
Q_CORE_EXPORT QByteArray qCompress (const uchar * data, int nbytes, int compressionLevel = -1) related
Referenced by QSvgIconEngine::read(), QSvgIconEngine::write(), and QCacheItem::writeCompressedData().
qCompress() [2/2]
QByteArray qCompress (const QByteArray & data, int compressionLevel = -1) related
Definition at line 604 of file qbytearray.h.
 { return qCompress(reinterpret_cast<const uchar *>(data.constData()), data.size(), compressionLevel); }
qsnprintf()
Q_CORE_EXPORT int qsnprintf (char * str, size_t n, const char * fmt, ...) related
qstrcmp() [1/4]
Q_CORE_EXPORT int qstrcmp (const char * str1, const char * str2) related
qstrcmp() [2/4]
Q_CORE_EXPORT int qstrcmp (const QByteArray & str1, const QByteArray & str2)
Warning
This function is not part of the public interface.
Definition at line 363 of file qbytearray.cpp.
 {
     int l1 = str1.length();
     int l2 = str2.length();
     int ret = memcmp(str1, str2, qMin(l1, l2));
     if (ret != 0)
         return ret;
     // they matched qMin(l1, l2) bytes
     // so the longer one is lexically after the shorter one
     return l1 - l2;
 }
qstrcmp() [3/4]
Q_CORE_EXPORT int qstrcmp (const QByteArray & str1, const char * str2)
Warning
This function is not part of the public interface.
Definition at line 336 of file qbytearray.cpp.
Referenced by QAccessibleObjectPrivate::actionList(), QDBusAdaptorConnector::addAdaptor(), QPrintPropertiesDialog::addItemToOptions(), QAudioDeviceInfoInternal::availableDevices(), QLocalePrivate::bytearrayToDouble(), QMetaObject::checkConnectArgs(), QCUPSSupport::collectMarkedOptionsHelper(), QPSQLDriver::commitTransaction(), QTest::compare_string_helper(), QFutureWatcherBase::connectNotify(), QNetworkSession::connectNotify(), QDBusAbstractInterface::connectNotify(), QAxClass< T >::createObject(), QDeclarativeVisualDataModelDataMetaObject::createProperty(), QScript::QMetaObjectWrapperObject::deleteProperty(), QFutureWatcherBase::disconnectNotify(), QNetworkSession::disconnectNotify(), QProxyStylePrivate::ensureBaseStyle(), QScript::QMetaObjectWrapperObject::getOwnPropertyDescriptor(), QScript::QMetaObjectWrapperObject::getOwnPropertySlot(), getStyle(), QObject::inherits(), QDeclarativeJS::integerFromString(), QScript::integerFromString(), QMetaMethod::invoke(), isProcessBeingDebugged(), QObject::killTimer(), QStyleSheetStyle::nativeFrameWidth(), QStyleSheetStyleSelector::nodeNameEquals(), QStyleSheetStyleSelector::nodeNames(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), QCUPSSupport::pageRect(), QCUPSSupport::paperRect(), parentWidget(), QPPDOptionsModel::parseChoices(), QCUPSSupport::ppdOption(), QApplicationPrivate::process_cmdline(), QVideoSurfaceFormat::property(), QScript::QMetaObjectWrapperObject::put(), QTest::qExec(), QTest::qInvokeTestMethod(), QRenderRule::QRenderRule(), QSQLite2DriverPrivate::QSQLite2DriverPrivate(), qt_check_if_internal_widget(), qt_init(), QAxObject::qt_metacast(), QAxWidget::qt_metacast(), QAxHostWidget::qt_metacast(), qt_parseEtcLpPrinters(), QBBSystemLocaleData::readHourFormat(), QBBSystemLocaleData::readMeasurementSystem(), QCUPSSupport::saveOptions(), QWizard::setDefaultProperty(), QFontDialogPrivate::setFont(), QObject::setObjectName(), QVideoSurfaceFormat::setProperty(), QDBusConnectionInterface::unregisterService(), and QAccessible::updateAccessibility().
 {
     if (!str2)
         return str1.isEmpty() ? 0 : +1;
     const char *str1data = str1.constData();
     const char *str1end = str1data + str1.length();
     for ( ; str1data < str1end && *str2; ++str1data, ++str2) {
         register int diff = int(uchar(*str1data)) - uchar(*str2);
         if (diff)
             // found a difference
             return diff;
     }
     // Why did we stop?
     if (*str2 != '\0')
         // not the null, so we stopped because str1 is shorter
         return -1;
     if (str1data < str1end)
         // we haven't reached the end, so str1 must be longer
         return +1;
     return 0;
 }
qstrcmp() [4/4]
static int qstrcmp (const char * str1, const QByteArray & str2) inline static
Definition at line 98 of file qbytearray.h.
 { return -qstrcmp(str2, str1); }
qstrcpy()
Q_CORE_EXPORT char* qstrcpy (char * dst, const char * src) related
Referenced by QScreen::subScreenIndexAt(), and QTest::toString().
qstrdup()
Q_CORE_EXPORT char* qstrdup (const char *) related
Referenced by QDirectFBScreen::connect(), QIconvCodec::createIconv_t(), QTest::IgnoreResultList::IgnoreResultList(), QDirectFbIntegration::initializeDirectFB(), loadXlfds(), qErrnoWarning(), QTest::qExpectFail(), QTest::qInvokeTestMethod(), QTest::qPrintDataTags(), qt_init(), qt_parsePrintersConf(), QTest::qtest_qParseArgs(), QTestData::QTestData(), set_text(), QTestElementAttribute::setPair(), QPictureIO::setParameters(), QTest::toHexRepresentation(), and QTest::toString().
qstricmp()
Q_CORE_EXPORT int qstricmp (const char * , const char *) related
Referenced by QHttpNetworkHeaderPrivate::contentLength(), QClassFactory::CreateInstanceHelper(), QNetworkHeadersPrivate::findRawHeader(), QTextStreamPrivate::getReal(), QHttpNetworkHeaderPrivate::headerFieldValues(), QHttpNetworkReplyPrivate::isGzipped(), QX11Data::motifdndObtainData(), QJpUnicodeConv::newConverter(), parseHeaderName(), QMimeSource::provides(), qt_set_input_encoding(), QConfFileSettingsPrivate::readIniFile(), QAxFactory::registerActiveObject(), QAxServerBase::registerActiveObject(), QHttpNetworkReplyPrivate::removeAutoDecompressHeader(), QNetworkAccessHttpBackend::replyDownloadMetaData(), QHttpNetworkHeaderPrivate::setHeaderField(), QNetworkHeadersPrivate::setRawHeaderInternal(), sm_performSaveYourself(), and QConfFileSettingsPrivate::writeIniFile().
qstrlen()
uint qstrlen (const char * str) related
Definition at line 79 of file qbytearray.h.
Referenced by _qdtoa(), QPatternist::XQueryTokenizer::aheadEquals(), QString::append(), QMetaObject::checkConnectArgs(), QGLShader::compileSourceCode(), QObject::connect(), QMetaObject::connectSlotsByName(), QWindowsMimeText::convertToMime(), QObject::disconnect(), QTextHtmlExporter::emitCharFormatStyle(), QTextHtmlExporter::emitFragment(), QTextHtmlExporter::emitFrameStyle(), extract_location(), QString::fromAscii_helper(), QHashableLatin1Literal::fromData(), QString::fromLatin1_helper(), QString::fromLocal8Bit(), QString::fromUtf8(), QString::insert(), intValueHelper(), QMetaMethod::invoke(), QMetaObject::invokeMethod(), QTest::isValidSlot(), QMetaEnum::keysToValue(), QMetaEnum::keyToValue(), QString::lastIndexOf(), QStringRef::lastIndexOf(), QDBusMessagePrivate::makeLocal(), QGLExtensionMatcher::match(), QMetaObject::newInstance(), QMetaObject::normalizedType(), QDataStream::operator<<(), qt_ends_with(), qt_fillFontDef(), qt_find_latin1_string(), qt_mac_execute_apple_script(), qt_parse_pattern(), qt_starts_with(), QXIMInputContext::QXIMInputContext(), QFSFileEnginePrivate::readLineFdFh(), QCss::Declaration::realValue(), QString::replace(), MetaObjectGenerator::replacePrototype(), QObjectPrivate::signalSignature(), QConcatenable< QLatin1String >::size(), QConcatenable< const char * >::size(), QTextCodec::toUnicode(), QMetaType::type(), and QIODevice::write().
 { return str ? uint(strlen(str)) : 0; }
qstrncmp()
int qstrncmp (const char * str1, const char * str2, uint len) related
Definition at line 101 of file qbytearray.h.
Referenced by QGifHandler::canRead(), QXpmHandler::canRead(), QBmpHandler::canRead(), QGLShader::compileSourceCode(), QMetaObject::connectSlotsByName(), QGIFFormat::decode(), QGLExtensionMatcher::match(), QScript::methodNameEquals(), QAudioInputPrivate::open(), QAudioOutputPrivate::open(), qt_parse_pattern(), qt_parseNsswitchConf(), QTgaFile::QTgaFile(), QWSSoundServerBucket::readySamples(), and QGIFFormat::scan().
 {
     return (str1 && str2) ? strncmp(str1, str2, len)
         : (str1 ? 1 : (str2 ? -1 : 0));
 }
qstrncpy()
Q_CORE_EXPORT char* qstrncpy (char * dst, const char * src, uint len) related
Referenced by _qdtoa(), QFileSystemEngine::currentPath(), QTest::formatResult(), QNtlmPhase1Block::QNtlmPhase1Block(), QNtlmPhase3Block::QNtlmPhase3Block(), and qStringFromUcs2Le().
qstrnicmp()
Q_CORE_EXPORT int qstrnicmp (const char * , const char * , uint len) related
qstrnlen()
uint qstrnlen (const char * str, uint maxlen) related
Definition at line 82 of file qbytearray.h.
Referenced by QString::append(), operator+(), QString::operator+=(), QString::operator=(), and QString::prepend().
 {
     uint length = 0;
     if (str) {
         while (length < maxlen && *str++)
             length++;
     }
     return length;
 }
qUncompress() [1/2]
Q_CORE_EXPORT QByteArray qUncompress (const uchar * data, int nbytes)
Referenced by QSvgIconEnginePrivate::loadDataForModeAndState(), QResourceFileEngine::QResourceFileEngine(), QSvgIconEngine::read(), and QCacheItem::read().
qUncompress() [2/2]
QByteArray qUncompress (const QByteArray & data) related
Definition at line 606 of file qbytearray.h.
 { return qUncompress(reinterpret_cast<const uchar*>(data.constData()), data.size()); }
qvsnprintf()
Q_CORE_EXPORT int qvsnprintf (char * str, size_t n, const char * fmt, va_list ap) related
Referenced by qEmergencyOut(), QTest::qt_asprintf(), QTest::qt_snprintf(), and QPdfEnginePrivate::xprintf().