Qt 4.8: /src/gui/kernel/qclipboard_win.cpp File Reference
qclipboard_win.cpp File Reference
#include "qclipboard.h"
#include "qapplication.h"
#include "qapplication_p.h"
#include "qeventloop.h"
#include "qwidget.h"
#include "qevent.h"
#include "qmime.h"
#include "qt_windows.h"
#include "qdnd_p.h"
#include <private/qwidget_p.h>
#include <private/qsystemlibrary_p.h>
#include "qguifunctions_wince.h"
Classes
class QClipboardData
class QClipboardWatcher
Macros
#define OleFlushClipboard QtCeFlushClipboard
#define OleGetClipboard QtCeGetClipboard
#define OleSetClipboard QtCeSetClipboard
Typedefs
typedef BOOL(WINAPI * PtrIsHungAppWindow) (HWND)
Functions
static void cleanupClipboardData ()
static QClipboardData * clipboardData ()
static bool isProcessBeingDebugged (HWND)
void QtCeFlushClipboard ()
HRESULT QtCeGetClipboard (IDataObject **obj)
HRESULT QtCeSetClipboard (IDataObject *obj)
Variables
static QClipboardData * ptrClipboardData = 0
static PtrIsHungAppWindow ptrIsHungAppWindow = 0
Macro Definition Documentation
OleFlushClipboard
#define OleFlushClipboard QtCeFlushClipboard
Definition at line 70 of file qclipboard_win.cpp.
Referenced by isProcessBeingDebugged().
OleGetClipboard
#define OleGetClipboard QtCeGetClipboard
Definition at line 68 of file qclipboard_win.cpp.
Referenced by QClipboardWatcher::formats_sys(), QClipboardWatcher::hasFormat_sys(), and QClipboardWatcher::retrieveData_sys().
OleSetClipboard
#define OleSetClipboard QtCeSetClipboard
Definition at line 69 of file qclipboard_win.cpp.
Referenced by QClipboard::~QClipboard().
Typedef Documentation
PtrIsHungAppWindow
typedef BOOL(WINAPI * PtrIsHungAppWindow) (HWND)
Definition at line 74 of file qclipboard_win.cpp.
Function Documentation
cleanupClipboardData()
static void cleanupClipboardData () static
Definition at line 190 of file qclipboard_win.cpp.
Referenced by QClipboard::~QClipboard().
 {
     delete ptrClipboardData;
     ptrClipboardData = 0;
 }
clipboardData()
static QClipboardData* clipboardData () static
Definition at line 179 of file qclipboard_win.cpp.
Referenced by isProcessBeingDebugged(), and QClipboard::~QClipboard().
 {
     if (ptrClipboardData == 0) {
         ptrClipboardData = new QClipboardData;
         // this needs to be done here to avoid recursion
         Q_ASSERT(ptrClipboardData->clipBoardViewer->testAttribute(Qt::WA_WState_Created));
         ptrClipboardData->nextClipboardViewer = SetClipboardViewer(ptrClipboardData->clipBoardViewer->internalWinId());
     }
     return ptrClipboardData;
 }
isProcessBeingDebugged()
static bool isProcessBeingDebugged (HWND) static
Definition at line 318 of file qclipboard_win.cpp.
Referenced by QClipboard::~QClipboard().
 { return false; }
QtCeFlushClipboard()
void QtCeFlushClipboard ()
Definition at line 249 of file qclipboard_win.cpp.
 { }
QtCeGetClipboard()
HRESULT QtCeGetClipboard (IDataObject ** obj)
Definition at line 197 of file qclipboard_win.cpp.
 {
     HWND owner = ptrClipboardData->clipBoardViewer->internalWinId();
     if (!OpenClipboard(owner))
         return !S_OK;
     if (!IsClipboardFormatAvailable(CF_TEXT) && !IsClipboardFormatAvailable(CF_UNICODETEXT))
         return !S_OK;
     HANDLE clipData = GetClipboardData(CF_TEXT);
     QString clipText;
     if (clipData == 0) {
         clipData = GetClipboardData(CF_UNICODETEXT);
         if (clipData != 0)
             clipText = QString::fromWCharArray((wchar_t *)clipData);
     } else {
         clipText = QString::fromLatin1((const char*)clipData);
     }
     QMimeData *mimeData = new QMimeData();
     mimeData->setText(clipText);
     QOleDataObject* data = new QOleDataObject(mimeData);
     *obj = data;
     CloseClipboard();
     return S_OK;
 }
QtCeSetClipboard()
HRESULT QtCeSetClipboard (IDataObject * obj)
Definition at line 224 of file qclipboard_win.cpp.
 {
     HWND owner = ptrClipboardData->clipBoardViewer->internalWinId();
     if (!OpenClipboard(owner))
         return !S_OK;
     bool result = false;
     if (obj == 0) {
         result = true;
         EmptyClipboard();
         CloseClipboard();
     } else {
         QOleDataObject* qobj = static_cast<QOleDataObject*>(obj);
         const QMimeData* data = qobj->mimeData();
         if (data->hasText()) {
             EmptyClipboard();
             result = SetClipboardData(CF_UNICODETEXT, wcsdup(reinterpret_cast<const wchar_t *> (data->text().utf16()))) != NULL;
             CloseClipboard();
             result = true;
         }
     }
     return result ? S_OK : !S_OK;
 }
Variable Documentation
ptrClipboardData
QClipboardData* ptrClipboardData = 0 static
Definition at line 177 of file qclipboard_win.cpp.
Referenced by cleanupClipboardData(), and clipboardData().
ptrIsHungAppWindow
PtrIsHungAppWindow ptrIsHungAppWindow = 0 static
Definition at line 76 of file qclipboard_win.cpp.
Referenced by isProcessBeingDebugged().