Qt 4.8: /src/gui/kernel/qclipboard_mac.cpp File Reference
qclipboard_mac.cpp File Reference
#include "qclipboard.h"
#include "qapplication.h"
#include "qbitmap.h"
#include "qdatetime.h"
#include "qdebug.h"
#include "qapplication_p.h"
#include <private/qt_mac_p.h>
#include "qevent.h"
#include "qurl.h"
#include <stdlib.h>
#include <string.h>
#include "qt_cocoa_helpers_mac_p.h"
Classes
class QMacMimeData
class QMacPasteboardMimeSource
Functions
static void qt_mac_cleanupPasteboard ()
static QMacPasteboard * qt_mac_pasteboard (QClipboard::Mode mode)
static bool qt_mac_updateScrap (QClipboard::Mode mode)
Variables
static QMacPasteboard * qt_mac_pasteboards [2] = {0, 0}
Function Documentation
qt_mac_cleanupPasteboard()
static void qt_mac_cleanupPasteboard () static
Definition at line 81 of file qclipboard_mac.cpp.
Referenced by qt_mac_updateScrap().
{
     delete qt_mac_pasteboards[0];
     delete qt_mac_pasteboards[1];
     qt_mac_pasteboards[0] = 0;
     qt_mac_pasteboards[1] = 0;
 }
qt_mac_pasteboard()
static QMacPasteboard* qt_mac_pasteboard (QClipboard::Mode mode) inline static
Definition at line 72 of file qclipboard_mac.cpp.
Referenced by QClipboard::clear(), QClipboard::mimeData(), qt_mac_updateScrap(), and QClipboard::setMimeData().
 {
     Q_ASSERT(mode == QClipboard::Clipboard || mode == QClipboard::FindBuffer);
     if (mode == QClipboard::Clipboard)
         return qt_mac_pasteboards[0];
     else
         return qt_mac_pasteboards[1];
 }
qt_mac_updateScrap()
static bool qt_mac_updateScrap (QClipboard::Mode mode) static
Definition at line 88 of file qclipboard_mac.cpp.
Referenced by QClipboard::clear(), QClipboard::event(), QClipboard::mimeData(), and QClipboard::setMimeData().
 {
     if(!qt_mac_pasteboards[0]) {
         qt_mac_pasteboards[0] = new QMacPasteboard(kPasteboardClipboard, QMacPasteboardMime::MIME_CLIP);
         qt_mac_pasteboards[1] = new QMacPasteboard(kPasteboardFind, QMacPasteboardMime::MIME_CLIP);
         qAddPostRoutine(qt_mac_cleanupPasteboard);
         return true;
     }
     return qt_mac_pasteboard(mode)->sync();
 }
Variable Documentation
qt_mac_pasteboards
QMacPasteboard* qt_mac_pasteboards[2] = {0, 0} static
Definition at line 70 of file qclipboard_mac.cpp.