Qt 4.8: /src/gui/kernel/qcocoaintrospection_p.h File Reference
qcocoaintrospection_p.h File Reference
#include <qglobal.h>
#import <objc/objc-class.h>
Functions
void qt_cocoa_change_back_implementation (Class baseClass, SEL originalSel, SEL backupSel)
void qt_cocoa_change_implementation (Class baseClass, SEL originalSel, Class proxyClass, SEL replacementSel=0, SEL backupSel=0)
Function Documentation
qt_cocoa_change_back_implementation()
void qt_cocoa_change_back_implementation (Class baseClass, SEL originalSel, SEL backupSel)
Definition at line 111 of file qcocoaintrospection_mac.mm.
Referenced by macStopInterceptNSPanelCtor(), and macStopInterceptWindowTitle().
 {
 #ifndef QT_MAC_USE_COCOA
     if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_5)
 #endif
     {
 #if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5
         Method originalMethod = class_getInstanceMethod(baseClass, originalSel);
         Method backupMethodInBaseClass = class_getInstanceMethod(baseClass, backupSel);
         method_setImplementation(originalMethod, method_getImplementation(backupMethodInBaseClass));
 #endif
     }
 }
qt_cocoa_change_implementation()
void qt_cocoa_change_implementation (Class baseClass, SEL originalSel, Class proxyClass, SEL replacementSel = 0, SEL backupSel = 0)
Definition at line 80 of file qcocoaintrospection_mac.mm.
Referenced by macStartInterceptNSPanelCtor(), and macStartInterceptWindowTitle().
 {
 #ifndef QT_MAC_USE_COCOA
     if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_5)
 #endif
     {
 #if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5
         // The following code replaces the _implementation_ for the selector we want to hack
         // (originalSel) with the implementation found in proxyClass. Then it creates
         // a new 'backup' method inside baseClass containing the old, original,
         // implementation (fakeSel). You can let the proxy implementation of originalSel
         // call fakeSel if needed (similar approach to calling a super class implementation).
         // fakeSel must also be implemented in proxyClass, as the signature is used
         // as template for the method one we add into baseClass.
         // NB: You will typically never create any instances of proxyClass; we use it
         // only for stealing its contents and put it into baseClass.
         if (!replacementSel)
             replacementSel = originalSel;
         Method originalMethod = class_getInstanceMethod(baseClass, originalSel);
         Method replacementMethod = class_getInstanceMethod(proxyClass, replacementSel);
         IMP originalImp = method_setImplementation(originalMethod, method_getImplementation(replacementMethod));
         if (backupSel) {
             Method backupMethod = class_getInstanceMethod(proxyClass, backupSel);
             class_addMethod(baseClass, backupSel, originalImp, method_getTypeEncoding(backupMethod));
         }
 #endif
     }
 }