Qt 4.8: /src/gui/painting/qcolor_p.h File Reference
qcolor_p.h File Reference
#include "QtCore/qglobal.h"
#include "QtGui/qrgb.h"
#include "QtCore/qstringlist.h"
Functions
QStringList qt_get_colornames ()
bool qt_get_hex_rgb (const char *, QRgb *)
bool qt_get_hex_rgb (const QChar *, int len, QRgb *)
bool qt_get_named_rgb (const char *, QRgb *)
bool qt_get_named_rgb (const QChar *, int len, QRgb *)
uint qt_get_rgb_val (const char *name)
Function Documentation
qt_get_colornames()
QStringList qt_get_colornames ()
Definition at line 344 of file qcolor_p.cpp.
Referenced by QColor::colorNames(), and qt_get_colornames().
 {
     int i = 0;
     QStringList lst;
     for (i = 0; i < rgbTblSize; i++)
         lst << QLatin1String(rgbTbl[i].name);
     return lst;
 }
qt_get_hex_rgb() [1/2]
bool qt_get_hex_rgb (const char * , QRgb *)
Definition at line 76 of file qcolor_p.cpp.
Referenced by qt_get_hex_rgb(), read_xpm_body(), and QColor::setColorFromString().
 {
     if(name[0] != '#')
         return false;
     name++;
     int len = qstrlen(name);
     int r, g, b;
     if (len == 12) {
         r = hex2int(name);
         g = hex2int(name + 4);
         b = hex2int(name + 8);
     } else if (len == 9) {
         r = hex2int(name);
         g = hex2int(name + 3);
         b = hex2int(name + 6);
     } else if (len == 6) {
         r = hex2int(name);
         g = hex2int(name + 2);
         b = hex2int(name + 4);
     } else if (len == 3) {
         r = hex2int(name[0]);
         g = hex2int(name[1]);
         b = hex2int(name[2]);
     } else {
         r = g = b = -1;
     }
     if ((uint)r > 255 || (uint)g > 255 || (uint)b > 255) {
         *rgb = 0;
         return false;
     }
     *rgb = qRgb(r, g ,b);
     return true;
 }
qt_get_hex_rgb() [2/2]
bool qt_get_hex_rgb (const QChar * , int len, QRgb *)
Definition at line 110 of file qcolor_p.cpp.
 {
     if (len > 13)
         return false;
     char tmp[16];
     for(int i = 0; i < len; ++i)
         tmp[i] = str[i].toLatin1();
     tmp[len] = 0;
     return qt_get_hex_rgb(tmp, rgb);
 }
qt_get_named_rgb() [1/2]
bool qt_get_named_rgb (const char * , QRgb *)
Definition at line 306 of file qcolor_p.cpp.
Referenced by qt_get_colornames(), qt_get_rgb_val(), and QColor::setColorFromString().
 {
     int len = int(strlen(name));
     if(len > 255)
         return false;
     char name_no_space[256];
     int pos = 0;
     for(int i = 0; i < len; i++) {
         if(name[i] != '\t' && name[i] != ' ')
             name_no_space[pos++] = name[i];
     }
     name_no_space[pos] = 0;
     return get_named_rgb(name_no_space, rgb);
 }
qt_get_named_rgb() [2/2]
bool qt_get_named_rgb (const QChar * , int len, QRgb *)
Definition at line 322 of file qcolor_p.cpp.
 {
     if(len > 255)
         return false;
     char name_no_space[256];
     int pos = 0;
     for(int i = 0; i < len; i++) {
         if(name[i] != QLatin1Char('\t') && name[i] != QLatin1Char(' '))
             name_no_space[pos++] = name[i].toLatin1();
     }
     name_no_space[pos] = 0;
     return get_named_rgb(name_no_space, rgb);
 }
qt_get_rgb_val()
uint qt_get_rgb_val (const char * name)
Definition at line 337 of file qcolor_p.cpp.
Referenced by qt_get_colornames().
 {
     QRgb r = 0;
     qt_get_named_rgb(name,&r);
     return r;
 }