Qt 4.8: /src/gui/dialogs/qcolordialog_mac.mm File Reference
qcolordialog_mac.mm File Reference
#include "qcolordialog_p.h"
#include <qapplication.h>
#include <qtimer.h>
#include <qdialogbuttonbox.h>
#include <qabstracteventdispatcher.h>
#include <private/qapplication_p.h>
#include <private/qt_mac_p.h>
#include <qdebug.h>
#import <AppKit/AppKit.h>
#import <Foundation/Foundation.h>
Classes
protocol <NSWindowDelegate >
class QCocoaColorPanelDelegate
Typedefs
typedef float CGFloat
Functions
NSButton * macCreateButton (const char *text, NSView *superview)
void macStartInterceptNSPanelCtor ()
void macStopInterceptNSPanelCtor ()
Typedef Documentation
CGFloat
typedef float CGFloat
Definition at line 55 of file qcolordialog_mac.mm.
Function Documentation
macCreateButton()
NSButton* macCreateButton (const char * text, NSView * superview)
Definition at line 211 of file qnspanelproxy_mac.mm.
Referenced by QColorDialogPrivate::openCocoaColorPanel().
 {
     static const NSRect buttonFrameRect = { { 0.0, 0.0 }, { 0.0, 0.0 } };
     NSButton *button = [[NSButton alloc] initWithFrame:buttonFrameRect];
     [button setButtonType:NSMomentaryLightButton];
     [button setBezelStyle:NSRoundedBezelStyle];
     [button setTitle:(NSString*)(CFStringRef)QCFString(QDialogButtonBox::tr(text)
                                                        .remove(QLatin1Char('&')))];
     [[button cell] setFont:[NSFont systemFontOfSize:
             [NSFont systemFontSizeForControlSize:NSRegularControlSize]]];
     [superview addSubview:button];
     return button;
 }
macStartInterceptNSPanelCtor()
void macStartInterceptNSPanelCtor ()
Definition at line 150 of file qnspanelproxy_mac.mm.
Referenced by QColorDialogPrivate::openCocoaColorPanel().
 {
     qt_cocoa_change_implementation(
             [NSPanel class],
             @selector(initWithContentRect:styleMask:backing:defer:),
             [QT_MANGLE_NAMESPACE(QNSPanelProxy) class],
             @selector(initWithContentRect:styleMask:backing:defer:),
             @selector(qt_fakeInitWithContentRect:styleMask:backing:defer:));
     qt_cocoa_change_implementation(
             [NSPanel class],
             @selector(initWithContentRect:styleMask:backing:defer:screen:),
             [QT_MANGLE_NAMESPACE(QNSPanelProxy) class],
             @selector(initWithContentRect:styleMask:backing:defer:screen:),
             @selector(qt_fakeInitWithContentRect:styleMask:backing:defer:screen:));
 }
macStopInterceptNSPanelCtor()
void macStopInterceptNSPanelCtor ()
Definition at line 169 of file qnspanelproxy_mac.mm.
Referenced by QColorDialogPrivate::openCocoaColorPanel().
 {
     qt_cocoa_change_back_implementation(
             [NSPanel class],
             @selector(initWithContentRect:styleMask:backing:defer:screen:),
             @selector(qt_fakeInitWithContentRect:styleMask:backing:defer:screen:));
     qt_cocoa_change_back_implementation(
             [NSPanel class],
             @selector(initWithContentRect:styleMask:backing:defer:),
             @selector(qt_fakeInitWithContentRect:styleMask:backing:defer:));
 }