Qt 4.8: /src/gui/styles/qcommonstyle.cpp File Reference
qcommonstyle.cpp File Reference
#include "qcommonstyle.h"
#include "qcommonstyle_p.h"
#include <qfile.h>
#include <qapplication.h>
#include <qbitmap.h>
#include <qcache.h>
#include <qdockwidget.h>
#include <qdrawutil.h>
#include <qdialogbuttonbox.h>
#include <qformlayout.h>
#include <qgroupbox.h>
#include <qmath.h>
#include <qmenu.h>
#include <qpainter.h>
#include <qpaintengine.h>
#include <qpainterpath.h>
#include <qslider.h>
#include <qstyleoption.h>
#include <qtabbar.h>
#include <qtabwidget.h>
#include <qtoolbar.h>
#include <qtoolbutton.h>
#include <qrubberband.h>
#include <private/qcommonstylepixmaps_p.h>
#include <private/qmath_p.h>
#include <qdebug.h>
#include <qtextformat.h>
#include <qwizard.h>
#include <qfileinfo.h>
#include <qdir.h>
#include <qsettings.h>
#include <qpixmapcache.h>
#include <private/qguiplatformplugin_p.h>
#include <limits.h>
#include "private/qtextengine_p.h"
#include <private/qt_x11_p.h>
#include <private/qstylehelper_p.h>
Functions
static QPolygonF calcArrow (const QStyleOptionSlider *dial, qreal &a)
static void drawArrow (const QStyle *style, const QStyleOptionToolButton *toolbutton, const QRect &rect, QPainter *painter, const QWidget *widget=0)
static uint qt_intensity (uint r, uint g, uint b)
static QSizeF viewItemTextLayout (QTextLayout &textLayout, int lineWidth)
Function Documentation
calcArrow()
static QPolygonF calcArrow (const QStyleOptionSlider * dial, qreal & a) static
Definition at line 3068 of file qcommonstyle.cpp.
Referenced by QCommonStyle::drawComplexControl().
 {
     int width = dial->rect.width();
     int height = dial->rect.height();
     int r = qMin(width, height) / 2;
     int currentSliderPosition = dial->upsideDown ? dial->sliderPosition : (dial->maximum - dial->sliderPosition);
     if (dial->maximum == dial->minimum)
         a = Q_PI / 2;
     else if (dial->dialWrapping)
         a = Q_PI * 3 / 2 - (currentSliderPosition - dial->minimum) * 2 * Q_PI
             / (dial->maximum - dial->minimum);
     else
         a = (Q_PI * 8 - (currentSliderPosition - dial->minimum) * 10 * Q_PI
             / (dial->maximum - dial->minimum)) / 6;
     int xc = width / 2;
     int yc = height / 2;
     int len = r - QStyleHelper::calcBigLineSize(r) - 5;
     if (len < 5)
         len = 5;
     int back = len / 2;
     QPolygonF arrow(3);
     arrow[0] = QPointF(0.5 + xc + len * qCos(a),
                        0.5 + yc - len * qSin(a));
     arrow[1] = QPointF(0.5 + xc + back * qCos(a + Q_PI * 5 / 6),
                        0.5 + yc - back * qSin(a + Q_PI * 5 / 6));
     arrow[2] = QPointF(0.5 + xc + back * qCos(a - Q_PI * 5 / 6),
                        0.5 + yc - back * qSin(a - Q_PI * 5 / 6));
     return arrow;
 }
drawArrow()
static void drawArrow (const QStyle * style, const QStyleOptionToolButton * toolbutton, const QRect & rect, QPainter * painter, const QWidget * widget = 0) static
Definition at line 811 of file qcommonstyle.cpp.
Referenced by QCommonStyle::drawControl().
 {
     QStyle::PrimitiveElement pe;
     switch (toolbutton->arrowType) {
     case Qt::LeftArrow:
         pe = QStyle::PE_IndicatorArrowLeft;
         break;
     case Qt::RightArrow:
         pe = QStyle::PE_IndicatorArrowRight;
         break;
     case Qt::UpArrow:
         pe = QStyle::PE_IndicatorArrowUp;
         break;
     case Qt::DownArrow:
         pe = QStyle::PE_IndicatorArrowDown;
         break;
     default:
         return;
     }
     QStyleOption arrowOpt;
     arrowOpt.rect = rect;
     arrowOpt.palette = toolbutton->palette;
     arrowOpt.state = toolbutton->state;
     style->drawPrimitive(pe, &arrowOpt, painter, widget);
 }
qt_intensity()
static uint qt_intensity (uint r, uint g, uint b) inline static
Definition at line 5974 of file qcommonstyle.cpp.
Referenced by QCommonStyle::generatedIconPixmap().
 {
     // 30% red, 59% green, 11% blue
     return (77 * r + 150 * g + 28 * b) / 255;
 }
viewItemTextLayout()
static QSizeF viewItemTextLayout (QTextLayout & textLayout, int lineWidth) static
Definition at line 905 of file qcommonstyle.cpp.
Referenced by QCommonStylePrivate::viewItemDrawText().
 {
     qreal height = 0;
     qreal widthUsed = 0;
     textLayout.beginLayout();
     while (true) {
         QTextLine line = textLayout.createLine();
         if (!line.isValid())
             break;
         line.setLineWidth(lineWidth);
         line.setPosition(QPointF(0, height));
         height += line.height();
         widthUsed = qMax(widthUsed, line.naturalTextWidth());
     }
     textLayout.endLayout();
     return QSizeF(widthUsed, height);
 }