Qt 4.8: /src/corelib/kernel/qcore_mac.cpp File Reference
qcore_mac.cpp File Reference
#include <private/qcore_mac_p.h>
#include <new>
Functions
OSErr qt_mac_create_fsref (const QString &file, FSRef *fsref)
OSErr qt_mac_create_fsspec (const QString &file, FSSpec *spec)
QString qt_mac_from_pascal_string (const Str255 pstr)
void qt_mac_to_pascal_string (const QString &s, Str255 str, TextEncoding encoding, int len)
Function Documentation
qt_mac_create_fsref()
OSErr qt_mac_create_fsref (const QString & file, FSRef * fsref)
Definition at line 125 of file qcore_mac.cpp.
Referenced by QFileDialogPrivate::createNavServicesDialog(), qt_mac_create_fsspec(), registerFont(), QFileDialogPrivate::selectFile_sys(), and QFileDialogPrivate::setDirectory_sys().
 {
     return FSPathMakeRef(reinterpret_cast<const UInt8 *>(file.toUtf8().constData()), fsref, 0);
 }
qt_mac_create_fsspec()
OSErr qt_mac_create_fsspec (const QString & file, FSSpec * spec)
Definition at line 131 of file qcore_mac.cpp.
Referenced by registerFont().
 {
     FSRef fsref;
     OSErr ret = qt_mac_create_fsref(file, &fsref);
     if (ret == noErr)
         ret = FSGetCatalogInfo(&fsref, kFSCatInfoNone, 0, 0, spec, 0);
     return ret;
 }
qt_mac_from_pascal_string()
QString qt_mac_from_pascal_string (const Str255 pstr)
Definition at line 120 of file qcore_mac.cpp.
Referenced by qfontForThemeFont().
 {
     return QCFString(CFStringCreateWithPascalString(0, pstr, CFStringGetSystemEncoding()));
 }
qt_mac_to_pascal_string()
void qt_mac_to_pascal_string (const QString & s, Str255 str, TextEncoding encoding, int len)
Definition at line 91 of file qcore_mac.cpp.
Referenced by QFileDialogPrivate::selectFile_sys().
 {
     if(len == -1)
         len = s.length();
 #if 0
     UnicodeMapping mapping;
     mapping.unicodeEncoding = CreateTextEncoding(kTextEncodingUnicodeDefault,
                                                  kTextEncodingDefaultVariant,
                                                  kUnicode16BitFormat);
     mapping.otherEncoding = (encoding ? encoding : );
     mapping.mappingVersion = kUnicodeUseLatestMapping;
     UnicodeToTextInfo info;
     OSStatus err = CreateUnicodeToTextInfo(&mapping, &info);
     if(err != noErr) {
         qDebug("Qt: internal: Unable to create pascal string '%s'::%d [%ld]",
                s.left(len).latin1(), (int)encoding, err);
         return;
     }
     const int unilen = len * 2;
     const UniChar *unibuf = (UniChar *)s.unicode();
     ConvertFromUnicodeToPString(info, unilen, unibuf, str);
     DisposeUnicodeToTextInfo(&info);
 #else
     Q_UNUSED(encoding);
     CFStringGetPascalString(QCFString(s), str, 256, CFStringGetSystemEncoding());
 #endif
 }