Qt 4.8: /src/corelib/kernel/qcore_unix_p.h File Reference
qcore_unix_p.h File Reference
#include "qplatformdefs.h"
#include "qatomic.h"
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <sys/wait.h>
#include <errno.h>
#include <fcntl.h>
Classes
union qt_semun
Macros
#define _POSIX_MONOTONIC_CLOCK -1
#define EINTR_LOOP(var, cmd)
#define QT_CLOSE qt_safe_close
#define QT_OPEN qt_safe_open
#define QT_READ qt_safe_read
#define QT_UNIX_SUPPORTS_THREADSAFE_CLOEXEC 0
#define QT_WRITE qt_safe_write
Functions
timeval & normalizedTimeval (timeval &t)
timeval operator* (const timeval &t1, int mul)
timeval operator+ (const timeval &t1, const timeval &t2)
timeval & operator+= (timeval &t1, const timeval &t2)
timeval operator- (const timeval &t1, const timeval &t2)
bool operator< (const timeval &t1, const timeval &t2)
bool operator== (const timeval &t1, const timeval &t2)
timeval qt_gettime ()
void qt_ignore_sigpipe ()
static int qt_safe_close (int fd)
static int qt_safe_dup (int oldfd, int atleast=0, int flags=FD_CLOEXEC)
static int qt_safe_dup2 (int oldfd, int newfd, int flags=FD_CLOEXEC)
static int qt_safe_execv (const char *path, char *const argv[])
static int qt_safe_execve (const char *filename, char *const argv[], char *const envp[])
static int qt_safe_execvp (const char *file, char *const argv[])
static int qt_safe_open (const char *pathname, int flags, mode_t mode=0777)
static int qt_safe_pipe (int pipefd[2], int flags=0)
static qint64 qt_safe_read (int fd, void *data, qint64 maxlen)
Q_CORE_EXPORT int qt_safe_select (int nfds, fd_set *fdread, fd_set *fdwrite, fd_set *fdexcept, const struct timeval *tv)
static pid_t qt_safe_waitpid (pid_t pid, int *status, int options)
static qint64 qt_safe_write (int fd, const void *data, qint64 len)
static qint64 qt_safe_write_nosignal (int fd, const void *data, qint64 len)
Macro Definition Documentation
_POSIX_MONOTONIC_CLOCK
#define _POSIX_MONOTONIC_CLOCK -1
Definition at line 343 of file qcore_unix_p.h.
EINTR_LOOP
#define EINTR_LOOP (var, cmd)
Value:
do {                                        \
        var = cmd;                              \
    } while (var == -1 && errno == EINTR)
Definition at line 96 of file qcore_unix_p.h.
Referenced by QWSSharedMemory::attach(), QSharedMemoryPrivate::attach(), QWSSharedMemory::create(), QSharedMemoryPrivate::create(), QWSLock::down(), QLock::lock(), QSystemSemaphorePrivate::modifySemaphore(), QProcessPrivate::processStarted(), qt_safe_close(), qt_safe_connect(), qt_safe_dup2(), qt_safe_execv(), qt_safe_execve(), qt_safe_execvp(), qt_safe_open(), qt_safe_read(), qt_safe_select(), qt_safe_sendto(), qt_safe_waitpid(), qt_safe_write(), QKqueueFileSystemWatcherEngine::run(), QLock::unlock(), and QWSLock::up().
QT_CLOSE
#define QT_CLOSE qt_safe_close
Definition at line 304 of file qcore_unix_p.h.
Referenced by QFontDatabasePrivate::addQPF2File(), QTransportAuth::authorizeRequest(), QFontEngineQPF::cleanUpAfterClientCrash(), closeAllOpenFds(), QFSFileEnginePrivate::closeFdFh(), QWSPcMouseSubHandler::closeIfNot(), QLinuxFbIntegrationPrivate::closeTty(), QLinuxFbScreenPrivate::closeTty(), QUnixSocket::connect(), QUnixSocketPrivate::flushAncillary(), QFSFileEnginePrivate::nativeOpen(), QFontEngineQPF1::QFontEngineQPF1(), qt_safe_close(), QFSFileEngine::~QFSFileEngine(), QLinuxInputKeyboardHandler::~QLinuxInputKeyboardHandler(), QLinuxInputMouseHandler::~QLinuxInputMouseHandler(), QLock::~QLock(), QQnxMouseHandler::~QQnxMouseHandler(), QUnixSocketRightsPrivate::~QUnixSocketRightsPrivate(), QVFbKeyboardHandler::~QVFbKeyboardHandler(), QVFbMouseHandler::~QVFbMouseHandler(), QVFbScreenKeyboardHandler::~QVFbScreenKeyboardHandler(), QVFbScreenMouseHandler::~QVFbScreenMouseHandler(), QWSLinuxInputKbPrivate::~QWSLinuxInputKbPrivate(), QWSLinuxInputMousePrivate::~QWSLinuxInputMousePrivate(), QWSLinuxTPMouseHandlerPrivate::~QWSLinuxTPMouseHandlerPrivate(), QWSQnxKeyboardHandler::~QWSQnxKeyboardHandler(), QWSTtyKbPrivate::~QWSTtyKbPrivate(), and QWSUmKeyboardHandlerPrivate::~QWSUmKeyboardHandlerPrivate().
QT_OPEN
#define QT_OPEN qt_safe_open
Definition at line 186 of file qcore_unix_p.h.
Referenced by QFontDatabasePrivate::addQPF2File(), QTransportAuth::authorizeRequest(), QFontEngineQPF::cleanUpAfterClientCrash(), QLinuxFbScreen::connect(), QLinuxFbIntegration::connect(), createFileFromTemplate(), QTranslatorPrivate::do_load(), QLinuxFbScreen::initDevice(), QLinuxFbIntegration::initDevice(), QFSFileEnginePrivate::nativeOpen(), QWSSoundServerPrivate::openDevice(), QWSPcMouseHandlerPrivate::openDevices(), QWSSoundServerPrivate::openFile(), QLinuxFbIntegrationPrivate::openTty(), QLinuxFbScreenPrivate::openTty(), QFontEngineQPF::QFontEngineQPF(), QFontEngineQPF1::QFontEngineQPF1(), QLinuxInputKeyboardHandler::QLinuxInputKeyboardHandler(), QLinuxInputMouseHandler::QLinuxInputMouseHandler(), QLock::QLock(), QQnxMouseHandler::QQnxMouseHandler(), qt_safe_open(), QVFbKeyboardHandler::QVFbKeyboardHandler(), QVFbMouseHandler::QVFbMouseHandler(), QVFbScreenKeyboardHandler::QVFbScreenKeyboardHandler(), QVFbScreenMouseHandler::QVFbScreenMouseHandler(), QWSLinuxInputKbPrivate::QWSLinuxInputKbPrivate(), QWSLinuxInputMousePrivate::QWSLinuxInputMousePrivate(), QWSLinuxTPMouseHandlerPrivate::QWSLinuxTPMouseHandlerPrivate(), QWSQnxKeyboardHandler::QWSQnxKeyboardHandler(), QWSTtyKbPrivate::QWSTtyKbPrivate(), QWSUmKeyboardHandlerPrivate::QWSUmKeyboardHandlerPrivate(), and QDynamicFileResourceRoot::registerSelf().
QT_READ
#define QT_READ qt_safe_read
Definition at line 280 of file qcore_unix_p.h.
Referenced by QTransportAuth::authorizeRequest(), QWSPcMouseSubHandler_intellimouse::init(), QWSPcMouseSubHandler_mouseman::init(), QFontEngineQPF1::QFontEngineQPF1(), qt_safe_read(), QVFbKeyboardHandler::QVFbKeyboardHandler(), QVFbMouseHandler::QVFbMouseHandler(), QVFbScreenKeyboardHandler::QVFbScreenKeyboardHandler(), QVFbScreenMouseHandler::QVFbScreenMouseHandler(), QWSUmKeyboardHandlerPrivate::QWSUmKeyboardHandlerPrivate(), QFSFileEnginePrivate::readFdFh(), QVFbKeyboardHandler::readKeyboardData(), QWSUmKeyboardHandlerPrivate::readKeyboardData(), QVFbScreenKeyboardHandler::readKeyboardData(), QWSLinuxInputKbPrivate::readKeycode(), QWSTtyKbPrivate::readKeycode(), QLinuxInputKeyboardHandler::readKeycode(), QLinuxInputMouseHandler::readMouseData(), QWSLinuxInputMousePrivate::readMouseData(), QVFbMouseHandler::readMouseData(), QWSLinuxTPMouseHandlerPrivate::readMouseData(), QVFbScreenMouseHandler::readMouseData(), QWSQnxKeyboardHandler::socketActivated(), and QQnxMouseHandler::socketActivated().
QT_UNIX_SUPPORTS_THREADSAFE_CLOEXEC
#define QT_UNIX_SUPPORTS_THREADSAFE_CLOEXEC 0
Definition at line 93 of file qcore_unix_p.h.
QT_WRITE
#define QT_WRITE qt_safe_write
Definition at line 289 of file qcore_unix_p.h.
Referenced by QLinuxFbIntegrationPrivate::closeTty(), QLinuxFbScreenPrivate::closeTty(), QWSPcMouseSubHandler_intellimouse::init(), QWSPcMouseSubHandler_mouseman::init(), QWSPcMouseSubHandler_mousesystems::init(), QWSPcMouseSubHandler_ms::init(), QWSPcMouseSubHandler_serial::initSerial(), QFontEngineQPF::loadGlyph(), QLinuxFbIntegrationPrivate::openTty(), QLinuxFbScreenPrivate::openTty(), QFontEngineQPF::QFontEngineQPF(), qt_safe_write(), QWSLinuxInputKbPrivate::switchLed(), QLinuxInputKeyboardHandler::switchLed(), and QFSFileEnginePrivate::writeFdFh().
Function Documentation
normalizedTimeval()
timeval& normalizedTimeval (timeval & t) inline
Definition at line 104 of file qcore_unix_p.h.
Referenced by operator*(), operator+(), operator+=(), operator-(), and QTimerInfoList::updateCurrentTime().
 {
     while (t.tv_usec > 1000000l) {
         ++t.tv_sec;
         t.tv_usec -= 1000000l;
     }
     while (t.tv_usec < 0l) {
         --t.tv_sec;
         t.tv_usec += 1000000l;
     }
     return t;
 }
operator*()
timeval operator* (const timeval & t1, int mul) inline
Definition at line 140 of file qcore_unix_p.h.
Referenced by QVector< QPoint >::constData().
 {
     timeval tmp;
     tmp.tv_sec = t1.tv_sec * mul;
     tmp.tv_usec = t1.tv_usec * mul;
     return normalizedTimeval(tmp);
 }
operator+()
timeval operator+ (const timeval & t1, const timeval & t2) inline
Definition at line 126 of file qcore_unix_p.h.
Referenced by QVector< QPoint >::constData(), qargb8565::ialpha(), qargb8555::ialpha(), qargb6666::ialpha(), qrgb666::ialpha(), qrgb888::ialpha(), qrgb555::operator quint16(), operator%(), QLinkedList< T >::iterator::operator-(), QLinkedList< T >::const_iterator::operator-(), QMap< Key, T >::iterator::operator-(), QMap< Key, T >::const_iterator::operator-(), QHash< Key, T >::iterator::operator-(), QHash< Key, T >::const_iterator::operator-(), qargb4444::qargb4444(), qrgb444::qrgb444(), qrgb565::qrgb565(), QPainterPath::swap(), QLinkedList< JSC::Identifier >::toStdList(), and QRegion::xored().
 {
     timeval tmp;
     tmp.tv_sec = t1.tv_sec + t2.tv_sec;
     tmp.tv_usec = t1.tv_usec + t2.tv_usec;
     return normalizedTimeval(tmp);
 }
operator+=()
timeval& operator+= (timeval & t1, const timeval & t2) inline
Definition at line 120 of file qcore_unix_p.h.
Referenced by QVector< QPoint >::back(), QScriptLine::base(), QVector< QPoint >::constData(), QByteArray::isSharedWith(), QString::isSimpleText(), QItemSelection::merge(), QMatrix4x4::QMatrix4x4(), QTransform::QTransform(), QPainterPath::swap(), QLinkedList< JSC::Identifier >::toStdList(), and QRegion::xored().
 {
     t1.tv_sec += t2.tv_sec;
     t1.tv_usec += t2.tv_usec;
     return normalizedTimeval(t1);
 }
operator-()
timeval operator- (const timeval & t1, const timeval & t2) inline
Definition at line 133 of file qcore_unix_p.h.
Referenced by QVector< QPoint >::constData(), QPainterPath::swap(), and QRegion::xored().
 {
     timeval tmp;
     tmp.tv_sec = t1.tv_sec - (t2.tv_sec - 1);
     tmp.tv_usec = t1.tv_usec - (t2.tv_usec + 1000000);
     return normalizedTimeval(tmp);
 }
operator<()
bool operator< (const timeval & t1, const timeval & t2) inline
Definition at line 116 of file qcore_unix_p.h.
 { return t1.tv_sec < t2.tv_sec || (t1.tv_sec == t2.tv_sec && t1.tv_usec < t2.tv_usec); }
operator==()
bool operator== (const timeval & t1, const timeval & t2) inline
Definition at line 118 of file qcore_unix_p.h.
 { return t1.tv_sec == t2.tv_sec && t1.tv_usec == t2.tv_usec; }
qt_gettime()
timeval qt_gettime ()
Definition at line 74 of file qelapsedtimer_mac.cpp.
Referenced by qt_safe_select(), QTimerInfoList::QTimerInfoList(), QEventDispatcherBlackberry::select(), time_update(), and QTimerInfoList::updateCurrentTime().
 {
     timeval tv;
     uint64_t cpu_time = mach_absolute_time();
     uint64_t nsecs = absoluteToNSecs(cpu_time);
     tv.tv_sec = nsecs / 1000000000ull;
     tv.tv_usec = (nsecs / 1000) - (tv.tv_sec * 1000000);
     return tv;
 }
qt_ignore_sigpipe()
void qt_ignore_sigpipe () inline
Definition at line 148 of file qcore_unix_p.h.
Referenced by qt_safe_sendto(), and qt_safe_write_nosignal().
 {
 #ifndef Q_NO_POSIX_SIGNALS
     // Set to ignore SIGPIPE once only.
     static QBasicAtomicInt atom = Q_BASIC_ATOMIC_INITIALIZER(0);
     if (!atom) {
         // More than one thread could turn off SIGPIPE at the same time
         // But that's acceptable because they all would be doing the same
         // action
         struct sigaction noaction;
         memset(&noaction, 0, sizeof(noaction));
         noaction.sa_handler = SIG_IGN;
         ::sigaction(SIGPIPE, &noaction, 0);
         atom = 1;
     }
 #else
     // Posix signals are not supported by the underlying platform
     // so we don't need to ignore sigpipe signal explicitly
 #endif
 }
qt_safe_close()
static int qt_safe_close (int fd) inline static
Definition at line 297 of file qcore_unix_p.h.
Referenced by QSharedMemoryPrivate::cleanHandle(), QBBButtonEventNotifier::close(), QSharedMemoryPrivate::create(), QSharedMemoryPrivate::createUnixKeyFile(), QProcessPrivate::destroyPipe(), QWSSharedMemory::detach(), detectProcessorFeatures(), QProcessPrivate::execChild(), QDBusUnixFileDescriptor::giveFileDescriptor(), QNativeSocketEnginePrivate::nativeClose(), QProcessPrivate::processStarted(), qt_create_pipe(), QDnotifyFileSystemWatcherEngine::refresh(), QDnotifyFileSystemWatcherEngine::removePaths(), QProcessPrivate::startDetached(), QProcessPrivate::startProcess(), QBBNavigatorEventNotifier::~QBBNavigatorEventNotifier(), QBBSystemLocaleData::~QBBSystemLocaleData(), QDBusUnixFileDescriptorPrivate::~QDBusUnixFileDescriptorPrivate(), QDnotifyFileSystemWatcherEngine::~QDnotifyFileSystemWatcherEngine(), and QProcessManager::~QProcessManager().
 {
     register int ret;
     EINTR_LOOP(ret, QT_CLOSE(fd));
     return ret;
 }
qt_safe_dup()
static int qt_safe_dup (int oldfd, int atleast = 0, int flags = FD_CLOEXEC) inline static
Definition at line 227 of file qcore_unix_p.h.
Referenced by QDnotifyFileSystemWatcherEngine::addPaths(), QUnixSocketRights::dupFd(), QUnixSocketRights::QUnixSocketRights(), and QDBusUnixFileDescriptor::setFileDescriptor().
 {
     Q_ASSERT(flags == FD_CLOEXEC || flags == 0);
     register int ret;
 #ifdef F_DUPFD_CLOEXEC
     // use this fcntl
     if (flags & FD_CLOEXEC) {
         ret = ::fcntl(oldfd, F_DUPFD_CLOEXEC, atleast);
         if (ret != -1 || errno != EINVAL)
             return ret;
     }
 #endif
     // use F_DUPFD
     ret = ::fcntl(oldfd, F_DUPFD, atleast);
     if (flags && ret != -1)
         ::fcntl(ret, F_SETFD, flags);
     return ret;
 }
qt_safe_dup2()
static int qt_safe_dup2 (int oldfd, int newfd, int flags = FD_CLOEXEC) inline static
Definition at line 251 of file qcore_unix_p.h.
Referenced by QProcessPrivate::execChild().
 {
     Q_ASSERT(flags == FD_CLOEXEC || flags == 0);
     register int ret;
 #if QT_UNIX_SUPPORTS_THREADSAFE_CLOEXEC && defined(O_CLOEXEC)
     // use dup3
     if (flags & FD_CLOEXEC) {
         EINTR_LOOP(ret, ::dup3(oldfd, newfd, O_CLOEXEC));
         if (ret == 0 || errno != ENOSYS)
             return ret;
     }
 #endif
     EINTR_LOOP(ret, ::dup2(oldfd, newfd));
     if (ret == -1)
         return -1;
     if (flags)
         ::fcntl(newfd, F_SETFD, flags);
     return 0;
 }
qt_safe_execv()
static int qt_safe_execv (const char * path, char *const argv[]) inline static
Definition at line 317 of file qcore_unix_p.h.
Referenced by QProcessPrivate::startDetached().
 {
     register int ret;
     EINTR_LOOP(ret, ::execv(path, argv));
     return ret;
 }
qt_safe_execve()
static int qt_safe_execve (const char * filename, char *const argv[], char *const envp[]) inline static
Definition at line 309 of file qcore_unix_p.h.
Referenced by QProcessPrivate::execChild().
 {
     register int ret;
     EINTR_LOOP(ret, ::execve(filename, argv, envp));
     return ret;
 }
qt_safe_execvp()
static int qt_safe_execvp (const char * file, char *const argv[]) inline static
Definition at line 324 of file qcore_unix_p.h.
Referenced by QProcessPrivate::execChild().
 {
     register int ret;
     EINTR_LOOP(ret, ::execvp(file, argv));
     return ret;
 }
qt_safe_open()
static int qt_safe_open (const char * pathname, int flags, mode_t mode = 0777) inline static
Definition at line 171 of file qcore_unix_p.h.
Referenced by QKqueueFileSystemWatcherEngine::addPaths(), QProcessPrivate::createChannel(), QSharedMemoryPrivate::createUnixKeyFile(), detectProcessorFeatures(), QBBSystemLocaleData::QBBSystemLocaleData(), QBBNavigatorEventNotifier::start(), and QBBButtonEventNotifier::start().
 {
 #ifdef O_CLOEXEC
     flags |= O_CLOEXEC;
 #endif
     register int fd;
     EINTR_LOOP(fd, QT_OPEN(pathname, flags, mode));
     // unknown flags are ignored, so we have no way of verifying if
     // O_CLOEXEC was accepted
     if (fd != -1)
         ::fcntl(fd, F_SETFD, FD_CLOEXEC);
     return fd;
 }
qt_safe_pipe()
static int qt_safe_pipe (int pipefd[2], int flags = 0) inline static
Definition at line 191 of file qcore_unix_p.h.
Referenced by QPdfBaseEnginePrivate::openPrintDevice(), QDnotifySignalThread::QDnotifySignalThread(), QEventDispatcherUNIXPrivate::QEventDispatcherUNIXPrivate(), QProcessManager::QProcessManager(), qt_create_pipe(), and QProcessPrivate::startDetached().
 {
 #ifdef O_CLOEXEC
     Q_ASSERT((flags & ~(O_CLOEXEC | O_NONBLOCK)) == 0);
 #else
     Q_ASSERT((flags & ~O_NONBLOCK) == 0);
 #endif
     register int ret;
 #if QT_UNIX_SUPPORTS_THREADSAFE_CLOEXEC && defined(O_CLOEXEC)
     // use pipe2
     flags |= O_CLOEXEC;
     ret = ::pipe2(pipefd, flags); // pipe2 is Linux-specific and is documented not to return EINTR
     if (ret == 0 || errno != ENOSYS)
         return ret;
 #endif
     ret = ::pipe(pipefd);
     if (ret == -1)
         return -1;
     ::fcntl(pipefd[0], F_SETFD, FD_CLOEXEC);
     ::fcntl(pipefd[1], F_SETFD, FD_CLOEXEC);
     // set non-block too?
     if (flags & O_NONBLOCK) {
         ::fcntl(pipefd[0], F_SETFL, ::fcntl(pipefd[0], F_GETFL) | O_NONBLOCK);
         ::fcntl(pipefd[1], F_SETFL, ::fcntl(pipefd[1], F_GETFL) | O_NONBLOCK);
     }
     return 0;
 }
qt_safe_read()
static qint64 qt_safe_read (int fd, void * data, qint64 maxlen) inline static
Definition at line 273 of file qcore_unix_p.h.
Referenced by detectProcessorFeatures(), QNativeSocketEnginePrivate::nativeRead(), QBBVirtualKeyboardPps::ppsDataReady(), QProcessPrivate::processStarted(), QBBNavigatorEventNotifier::readData(), QDnotifySignalThread::readFromDnotify(), QProcessPrivate::readFromStderr(), QProcessPrivate::readFromStdout(), QBBSystemLocaleData::readPpsValue(), QProcessManager::run(), QProcessPrivate::startDetached(), QBBButtonEventNotifier::updateButtonStates(), and QProcessPrivate::waitForDeadChild().
 {
     qint64 ret = 0;
     EINTR_LOOP(ret, QT_READ(fd, data, maxlen));
     return ret;
 }
qt_safe_select()
Q_CORE_EXPORT int qt_safe_select (int nfds, fd_set * fdread, fd_set * fdwrite, fd_set * fdexcept, const struct timeval * tv)
Definition at line 73 of file qcore_unix.cpp.
Referenced by QNativeSocketEnginePrivate::nativeSelect(), SelectWorker::run(), QEventDispatcherUNIX::select(), and select_msecs().
 {
     if (!orig_timeout) {
         // no timeout -> block forever
         register int ret;
         EINTR_LOOP(ret, select(nfds, fdread, fdwrite, fdexcept, 0));
         return ret;
     }
     timeval start = qt_gettime();
     timeval timeout = *orig_timeout;
     // loop and recalculate the timeout as needed
     int ret;
     forever {
         ret = ::select(nfds, fdread, fdwrite, fdexcept, &timeout);
         if (ret != -1 || errno != EINTR)
             return ret;
         // recalculate the timeout
         if (!time_update(&timeout, start, *orig_timeout)) {
             // timeout during update
             // or clock reset, fake timeout error
             return 0;
         }
     }
 }
qt_safe_waitpid()
static pid_t qt_safe_waitpid (pid_t pid, int * status, int options) inline static
Definition at line 333 of file qcore_unix_p.h.
Referenced by QProcessPrivate::startDetached(), and QProcessPrivate::waitForDeadChild().
 {
     register int ret;
     EINTR_LOOP(ret, ::waitpid(pid, status, options));
     return ret;
 }
qt_safe_write()
static qint64 qt_safe_write (int fd, const void * data, qint64 len) inline static
Definition at line 282 of file qcore_unix_p.h.
Referenced by QProcessManager::catchDeadChildren(), QProcessPrivate::execChild(), QProcessPrivate::processStarted(), qfswd_sigio_monitor(), qt_sa_sigchld_sigaction(), qt_safe_write_nosignal(), QProcessPrivate::startDetached(), QEventDispatcherUNIX::wakeUp(), and QProcessManager::~QProcessManager().
 {
     qint64 ret = 0;
     EINTR_LOOP(ret, QT_WRITE(fd, data, len));
     return ret;
 }
qt_safe_write_nosignal()
static qint64 qt_safe_write_nosignal (int fd, const void * data, qint64 len) inline static
Definition at line 291 of file qcore_unix_p.h.
Referenced by QNativeSocketEnginePrivate::nativeWrite(), and QProcessPrivate::writeToStdin().
 {
     qt_ignore_sigpipe();
     return qt_safe_write(fd, data, len);
 }