Qt 4.8: /src/plugins/platforms/fontdatabases/coretext/qcoretextfontdatabase.mm File Reference
qcoretextfontdatabase.mm File Reference
#include "qcoretextfontdatabase.h"
#include <CoreText/CoreText.h>
#include <Foundation/Foundation.h>
#include <private/qcore_mac_p.h>
#include <private/qfontengine_coretext_p.h>
Functions
static QString familyNameFromPostScriptName (QHash< QString, QString > *psNameToFamily, NSString *psName)
static NSInteger languageMapSort (id obj1, id obj2, void *context)
static QFont::StyleHint styleHintFromNSString (NSString *style)
Function Documentation
familyNameFromPostScriptName()
static QString familyNameFromPostScriptName (QHash< QString, QString > * psNameToFamily, NSString * psName) static
Definition at line 94 of file qcoretextfontdatabase.mm.
Referenced by QCoreTextFontDatabase::populateFontDatabase().
 {
     QString name = QCFString::toQString((CFStringRef) psName);
     if (psNameToFamily->contains(name)) {
         return psNameToFamily->value(name);
     } else {
         QCFType<CTFontRef> font = CTFontCreateWithName((CFStringRef) psName, 12.0, NULL);
         if (font) {
             QCFString family = CTFontCopyFamilyName(font);
             (*psNameToFamily)[name] = family;
             return family;
         }
     }
     return name;
 }
languageMapSort()
static NSInteger languageMapSort (id obj1, id obj2, void * context) static
Definition at line 82 of file qcoretextfontdatabase.mm.
Referenced by QCoreTextFontDatabase::populateFontDatabase().
 {
     NSArray *map1 = (NSArray *) obj1;
     NSArray *map2 = (NSArray *) obj2;
     NSArray *languages = (NSArray *) context;
     NSString *lang1 = [map1 objectAtIndex: 0];
     NSString *lang2 = [map2 objectAtIndex: 0];
     return [languages indexOfObject: lang1] - [languages indexOfObject: lang2];
 }
styleHintFromNSString()
static QFont::StyleHint styleHintFromNSString (NSString * style) static
Definition at line 66 of file qcoretextfontdatabase.mm.
Referenced by QCoreTextFontDatabase::populateFontDatabase().
 {
     if ([style isEqual: @"sans-serif"])
         return QFont::SansSerif;
     else if ([style isEqual: @"monospace"])
         return QFont::Monospace;
     else if ([style isEqual: @"cursive"])
         return QFont::Cursive;
     else if ([style isEqual: @"serif"])
         return QFont::Serif;
     else if ([style isEqual: @"fantasy"])
         return QFont::Fantasy;
     else
         return QFont::AnyStyle;
 }