Qt 4.8: /src/corelib/kernel/qcoreapplication.cpp File Reference
qcoreapplication.cpp File Reference
#include "qcoreapplication.h"
#include "qcoreapplication_p.h"
#include "qabstracteventdispatcher.h"
#include "qcoreevent.h"
#include "qeventloop.h"
#include "qcorecmdlineargs_p.h"
#include <qdatastream.h>
#include <qdebug.h>
#include <qdir.h>
#include <qfile.h>
#include <qfileinfo.h>
#include <qhash.h>
#include <private/qprocess_p.h>
#include <qtextcodec.h>
#include <qthread.h>
#include <qthreadpool.h>
#include <qthreadstorage.h>
#include <private/qthread_p.h>
#include <qelapsedtimer.h>
#include <qlibraryinfo.h>
#include <qvarlengtharray.h>
#include <private/qfactoryloader_p.h>
#include <private/qfunctions_p.h>
#include <private/qlocale_p.h>
#include <private/qmutexpool_p.h>
#include "qeventdispatcher_glib_p.h"
#include "qeventdispatcher_unix_p.h"
#include "qeventdispatcher_win_p.h"
#include "qcore_mac_p.h"
#include <stdlib.h>
#include <locale.h>
Classes
struct QCoreApplicationData
class QMutexUnlocker
Typedefs
typedef QList< QtCleanUpFunction > QVFuncList
Functions
Q_GLOBAL_STATIC (QString, qmljs_debug_arguments)
Q_GLOBAL_STATIC_WITH_ARGS (QSettings, staticTrolltechConf,(QSettings::UserScope, QLatin1String("Trolltech"))) QSettings *QCoreApplicationPrivate
void qAddPostRoutine (QtCleanUpFunction p)
QString qAppFileName ()
QString qAppName ()
Q_CORE_EXPORT uint qGlobalPostedEventsCount ()
void qRemovePostRoutine (QtCleanUpFunction p)
void Q_CORE_EXPORT qt_call_post_routines ()
void qt_register_signal_spy_callbacks (const QSignalSpyCallbackSet &callback_set)
void qt_set_current_thread_to_main_thread ()
void Q_CORE_EXPORT qt_startup_hook ()
QString qtTrId (const char *id, int n)
static void replacePercentN (QString *result, int n)
Variables
Qt::HANDLE qt_application_thread_id = 0
Q_CORE_EXPORT bool qt_locale_initialized = false
QSignalSpyCallbackSet Q_CORE_EXPORT qt_signal_spy_callback_set = { 0, 0, 0, 0 }
Typedef Documentation
QVFuncList
typedef QList<QtCleanUpFunction> QVFuncList
Definition at line 270 of file qcoreapplication.cpp.
Function Documentation
Q_GLOBAL_STATIC()
Q_GLOBAL_STATIC (QString , qmljs_debug_arguments)
Referenced by QCoreApplicationPrivate::checkInstance().
Q_GLOBAL_STATIC_WITH_ARGS()
Q_GLOBAL_STATIC_WITH_ARGS (QSettings , staticTrolltechConf , (QSettings::UserScope, QLatin1String("Trolltech")))
Definition at line 341 of file qcoreapplication.cpp.
Referenced by QCoreApplication::setApplicationVersion().
 {
     return staticTrolltechConf();
 }
qAddPostRoutine()
void qAddPostRoutine (QtCleanUpFunction p) related
Definition at line 273 of file qcoreapplication.cpp.
Referenced by QNetworkConfigurationManagerPrivate::addPostRoutine(), QX11PixmapData::bitmap_to_mask(), build_scale_table(), clipboardData(), QWSCursor::createSystemCursor(), QSqlDatabasePrivate::driverDict(), QGtkStylePrivate::gtkWidgetMap(), QTestAccessibility::initialize(), QMacPasteboardMime::initialize(), QAccessible::installFactory(), QCoreGraphicsPaintEngine::macDisplayColorSpace(), QCoreGraphicsPaintEngine::macGenericColorSpace(), make_widget_eventUPP(), make_win_eventUPP(), Q_GLOBAL_STATIC_WITH_INITIALIZER(), QLibrarySettings::QLibrarySettings(), qt_gl_choose_cmap(), qt_init_picture_handlers(), qt_mac_unregister_widget(), QErrorMessage::qtHandler(), selectionData(), and QX11Data::xdndSetup().
 {
     QVFuncList *list = postRList();
     if (!list)
         return;
     list->prepend(p);
 }
qAppFileName()
QString qAppFileName ()
Definition at line 51 of file qcoreapplication_mac.cpp.
Referenced by QCoreApplication::applicationFilePath(), QCoreApplicationPrivate::appName(), and QSystemLibrary::load().
 {
     static QString appFileName;
     if (appFileName.isEmpty()) {
         QCFType<CFURLRef> bundleURL(CFBundleCopyExecutableURL(CFBundleGetMainBundle()));
         if(bundleURL) {
             QCFString cfPath(CFURLCopyFileSystemPath(bundleURL, kCFURLPOSIXPathStyle));
             if(cfPath)
                 appFileName = cfPath;
         }
     }
     return appFileName;
 }
qAppName()
QString qAppName ()
Definition at line 575 of file qcoreapplication.cpp.
Referenced by getNetWmState(), qt_mac_menu_merge_text(), qt_tablet_cleanup_wce(), and sm_performSaveYourself().
 {
     if (!QCoreApplicationPrivate::checkInstance("qAppName"))
         return QString();
     return QCoreApplication::instance()->d_func()->appName();
 }
qGlobalPostedEventsCount()
Q_CORE_EXPORT uint qGlobalPostedEventsCount ()
Definition at line 348 of file qcoreapplication.cpp.
Referenced by alert_widget(), QEventDispatcherX11::hasPendingEvents(), QEventDispatcherQWS::hasPendingEvents(), QEventDispatcherQPA::hasPendingEvents(), QEventDispatcherWin32::hasPendingEvents(), QEventDispatcherMac::hasPendingEvents(), QEventDispatcherUNIX::hasPendingEvents(), and qt_mac_mouse_inside_answer_rect().
 {
     QThreadData *currentThreadData = QThreadData::current();
     return currentThreadData->postEventList.size() - currentThreadData->postEventList.startOffset;
 }
qRemovePostRoutine()
void qRemovePostRoutine (QtCleanUpFunction p)
Definition at line 281 of file qcoreapplication.cpp.
 {
     QVFuncList *list = postRList();
     if (!list)
         return;
     list->removeAll(p);
 }
qt_call_post_routines()
void Q_CORE_EXPORT qt_call_post_routines ()
Definition at line 289 of file qcoreapplication.cpp.
Referenced by initResources(), QApplication::~QApplication(), and QCoreApplication::~QCoreApplication().
 {
     QVFuncList *list = 0;
     QT_TRY {
         list = postRList();
     } QT_CATCH(const std::bad_alloc &) {
         // ignore - if we can't allocate a post routine list,
         // there's a high probability that there's no post
         // routine to be executed :)
     }
     if (!list)
         return;
     while (!list->isEmpty())
         (list->takeFirst())();
 }
qt_register_signal_spy_callbacks()
void qt_register_signal_spy_callbacks (const QSignalSpyCallbackSet & callback_set)
Definition at line 261 of file qcoreapplication.cpp.
Referenced by QSignalDumper::endDump(), and QSignalDumper::startDump().
 {
     qt_signal_spy_callback_set = callback_set;
 }
qt_set_current_thread_to_main_thread()
void qt_set_current_thread_to_main_thread ()
Definition at line 355 of file qcoreapplication.cpp.
Referenced by QInternal::activateCallbacks(), and QInternal::callFunction().
 {
     QCoreApplicationPrivate::theMainThread = QThread::currentThread();
 }
qt_startup_hook()
void Q_CORE_EXPORT qt_startup_hook ()
Definition at line 266 of file qcoreapplication.cpp.
Referenced by QCoreApplication::init().
 {
 }
qtTrId()
QString qtTrId (const char * id, int n)
Definition at line 2023 of file qcoreapplication.cpp.
Referenced by QScript::functionQsTrId().
 {
     return QCoreApplication::translate(0, id, 0, QCoreApplication::UnicodeUTF8, n);
 }
replacePercentN()
static void replacePercentN (QString * result, int n) static
Definition at line 1914 of file qcoreapplication.cpp.
Referenced by QCoreApplication::translate().
 {
     if (n >= 0) {
         int percentPos = 0;
         int len = 0;
         while ((percentPos = result->indexOf(QLatin1Char('%'), percentPos + len)) != -1) {
             len = 1;
             QString fmt;
             if (result->at(percentPos + len) == QLatin1Char('L')) {
                 ++len;
                 fmt = QLatin1String("%L1");
             } else {
                 fmt = QLatin1String("%1");
             }
             if (result->at(percentPos + len) == QLatin1Char('n')) {
                 fmt = fmt.arg(n);
                 ++len;
                 result->replace(percentPos, len, fmt);
                 len = fmt.length();
             }
         }
     }
 }
Variable Documentation
qt_application_thread_id
Qt::HANDLE qt_application_thread_id = 0
Definition at line 367 of file qcoreapplication.cpp.
Referenced by QEventDispatcherUNIXPrivate::QEventDispatcherUNIXPrivate().
qt_locale_initialized
Q_CORE_EXPORT bool qt_locale_initialized = false
Definition at line 311 of file qcoreapplication.cpp.
Referenced by QIconvCodec::convertFromUnicode(), and QIconvCodec::convertToUnicode().
qt_signal_spy_callback_set
QSignalSpyCallbackSet Q_CORE_EXPORT qt_signal_spy_callback_set = { 0, 0, 0, 0 }
Definition at line 259 of file qcoreapplication.cpp.
Referenced by QMetaObject::activate(), and QObjectPrivate::isSignalConnected().