Qt 4.8: /src/corelib/kernel/qcoreapplication_win.cpp File Reference
qcoreapplication_win.cpp File Reference
#include "qcoreapplication.h"
#include "qcoreapplication_p.h"
#include "qstringlist.h"
#include "qt_windows.h"
#include "qvector.h"
#include "qmutex.h"
#include "qfileinfo.h"
#include "qcorecmdlineargs_p.h"
#include <private/qthread_p.h>
#include <ctype.h>
#include <windowsx.h>
#include "qdebug.h"
Classes
struct FLAG_STRING_STRUCT
struct KnownWM
class QWinMsgHandlerCriticalSection
Macros
#define FLGSTR(x) FLAG_STRING(x, #x)
#define GET_X_LPARAM(lp) ((int)(short)LOWORD(lp))
#define GET_Y_LPARAM(lp) ((int)(short)HIWORD(lp))
Functions
QString decodeMSG (const MSG &msg)
static const char * findWMstr (uint msg)
FLAG_STRING_STRUCT FLAG_STRING (uint value=0, const char *c=0)
QString flagCheck (uint actual,...)
QDebug operator<< (QDebug dbg, const MSG &msg)
Q_CORE_EXPORT QString qAppFileName ()
Q_CORE_EXPORT int qWinAppCmdShow ()
Q_CORE_EXPORT HINSTANCE qWinAppInst ()
Q_CORE_EXPORT HINSTANCE qWinAppPrevInst ()
Q_CORE_EXPORT void __cdecl qWinMain (HINSTANCE instance, HINSTANCE prevInstance, LPSTR cmdParam, int cmdShow, int &argc, QVector< char *> &argv)
Q_CORE_EXPORT void qWinMsgHandler (QtMsgType t, const char *str)
QString valueCheck (uint actual,...)
Variables
int appCmdShow = 0
struct KnownWM knownWM []
bool usingWinMain = false
Macro Definition Documentation
FLGSTR
#define FLGSTR (x) FLAG_STRING(x, #x)
Definition at line 592 of file qcoreapplication_win.cpp.
Referenced by decodeMSG().
GET_X_LPARAM
#define GET_X_LPARAM (lp) ((int)(short)LOWORD(lp))
Definition at line 254 of file qcoreapplication_win.cpp.
Referenced by axc_FilterProc(), decodeMSG(), QtWndProc(), QETWidget::translateMouseEvent(), and QSystemTrayIconSys::winEvent().
GET_Y_LPARAM
#define GET_Y_LPARAM (lp) ((int)(short)HIWORD(lp))
Definition at line 255 of file qcoreapplication_win.cpp.
Referenced by axc_FilterProc(), decodeMSG(), QtWndProc(), QETWidget::translateMouseEvent(), and QSystemTrayIconSys::winEvent().
Function Documentation
decodeMSG()
QString decodeMSG (const MSG & msg)
Definition at line 645 of file qcoreapplication_win.cpp.
Referenced by operator<<(), and valueCheck().
 {
     const WPARAM wParam = msg.wParam;
     const LPARAM lParam = msg.lParam;
     QString wmmsg = QString::fromLatin1(findWMstr(msg.message));
     // Unknown WM_, so use number
     if (wmmsg.isEmpty())
         wmmsg = QString::fromLatin1("WM_(%1)").arg(msg.message);
     QString rawParameters;
     rawParameters.sprintf("hwnd(0x%p) ", (void *)msg.hwnd);
     // Custom WM_'s
     if (msg.message > WM_APP)
         wmmsg = QString::fromLatin1("WM_APP + %1").arg(msg.message - WM_APP);
     else if (msg.message > WM_USER)
         wmmsg = QString::fromLatin1("WM_USER + %1").arg(msg.message - WM_USER);
     QString parameters;
     switch (msg.message) {
 #ifdef WM_ACTIVATE
         case WM_ACTIVATE:
             {
                 QString activation = valueCheck(wParam,
                                                 FLAG_STRING(WA_ACTIVE,      "Activate"),
                                                 FLAG_STRING(WA_INACTIVE,    "Deactivate"),
                                                 FLAG_STRING(WA_CLICKACTIVE, "Activate by mouseclick"),
                                                 FLAG_STRING());
                 parameters.sprintf("%s Hwnd (0x%p)", activation.toLatin1().data(), (void *)msg.hwnd);
             }
             break;
 #endif
 #ifdef WM_CAPTURECHANGED
         case WM_CAPTURECHANGED:
             parameters.sprintf("Hwnd gaining capture (0x%p)", (void *)lParam);
             break;
 #endif
 #ifdef WM_CREATE
         case WM_CREATE:
             {
                 LPCREATESTRUCT lpcs = (LPCREATESTRUCT)lParam;
                 QString styles = flagCheck(lpcs->style,
                                            FLGSTR(WS_BORDER),
                                            FLGSTR(WS_CAPTION),
                                            FLGSTR(WS_CHILD),
                                            FLGSTR(WS_CLIPCHILDREN),
                                            FLGSTR(WS_CLIPSIBLINGS),
                                            FLGSTR(WS_DISABLED),
                                            FLGSTR(WS_DLGFRAME),
                                            FLGSTR(WS_GROUP),
                                            FLGSTR(WS_HSCROLL),
                                            FLGSTR(WS_OVERLAPPED),
 #if defined(WS_OVERLAPPEDWINDOW) && (WS_OVERLAPPEDWINDOW != 0)
                                            FLGSTR(WS_OVERLAPPEDWINDOW),
 #endif
 #ifdef WS_ICONIC
                                            FLGSTR(WS_ICONIC),
 #endif
                                            FLGSTR(WS_MAXIMIZE),
                                            FLGSTR(WS_MAXIMIZEBOX),
                                            FLGSTR(WS_MINIMIZE),
                                            FLGSTR(WS_MINIMIZEBOX),
                                            FLGSTR(WS_OVERLAPPEDWINDOW),
                                            FLGSTR(WS_POPUP),
 #ifdef WS_POPUPWINDOW
                                            FLGSTR(WS_POPUPWINDOW),
 #endif
                                            FLGSTR(WS_SIZEBOX),
                                            FLGSTR(WS_SYSMENU),
                                            FLGSTR(WS_TABSTOP),
                                            FLGSTR(WS_THICKFRAME),
 #ifdef WS_TILED
                                            FLGSTR(WS_TILED),
 #endif
 #ifdef WS_TILEDWINDOW
                                            FLGSTR(WS_TILEDWINDOW),
 #endif
                                            FLGSTR(WS_VISIBLE),
                                            FLGSTR(WS_VSCROLL),
                                            FLAG_STRING());
                 QString exStyles = flagCheck(lpcs->dwExStyle,
 #ifdef WS_EX_ACCEPTFILES
                                            FLGSTR(WS_EX_ACCEPTFILES),
 #endif
 #ifdef WS_EX_APPWINDOW
                                            FLGSTR(WS_EX_APPWINDOW),
 #endif
                                            FLGSTR(WS_EX_CLIENTEDGE),
                                            FLGSTR(WS_EX_DLGMODALFRAME),
 #ifdef WS_EX_LEFT
                                            FLGSTR(WS_EX_LEFT),
 #endif
                                            FLGSTR(WS_EX_LEFTSCROLLBAR),
 #ifdef WS_EX_LTRREADING
                                            FLGSTR(WS_EX_LTRREADING),
 #endif
 #ifdef WS_EX_MDICHILD
                                            FLGSTR(WS_EX_MDICHILD),
 #endif
 #ifdef WS_EX_NOACTIVATE
                                            FLGSTR(WS_EX_NOACTIVATE),
 #endif
 #ifdef WS_EX_NOANIMATION
                                            FLGSTR(WS_EX_NOANIMATION),
 #endif
                                            FLGSTR(WS_EX_NOPARENTNOTIFY),
                                            FLGSTR(WS_EX_OVERLAPPEDWINDOW),
 #ifdef WS_EX_PALETTEWINDOW
                                            FLGSTR(WS_EX_PALETTEWINDOW),
 #endif
 #ifdef WS_EX_RIGHT
                                            FLGSTR(WS_EX_RIGHT),
 #endif
 #ifdef WS_EX_RIGHTSCROLLBAR
                                            FLGSTR(WS_EX_RIGHTSCROLLBAR),
 #endif
 #ifdef WS_EX_RTLREADING
                                            FLGSTR(WS_EX_RTLREADING),
 #endif
                                            FLGSTR(WS_EX_STATICEDGE),
                                            FLGSTR(WS_EX_TOOLWINDOW),
                                            FLGSTR(WS_EX_TOPMOST),
 #ifdef WS_EX_TRANSPARENT
                                            FLGSTR(WS_EX_TRANSPARENT),
 #endif
                                            FLGSTR(WS_EX_WINDOWEDGE),
 #ifdef WS_EX_CAPTIONOKBTN
                                            FLGSTR(WS_EX_CAPTIONOKBTN),
 #endif
                                            FLAG_STRING());
                 QString className;
                 if (lpcs->lpszClass != 0) {
                     if (HIWORD(lpcs->lpszClass) == 0) // Atom
                         className = QString::number(LOWORD(lpcs->lpszClass), 16);
                     else                              // String
                         className = QString((QChar*)lpcs->lpszClass,
                                             (int)wcslen(reinterpret_cast<const wchar_t *>(lpcs->lpszClass)));
                 }
                 QString windowName;
                 if (lpcs->lpszName != 0)
                     windowName = QString((QChar*)lpcs->lpszName,
                                          (int)wcslen(reinterpret_cast<const wchar_t *>(lpcs->lpszName)));
                 parameters.sprintf("x,y(%4d,%4d) w,h(%4d,%4d) className(%s) windowName(%s) parent(0x%p) style(%s) exStyle(%s)",
                                    lpcs->x, lpcs->y, lpcs->cx, lpcs->cy, className.toLatin1().data(),
                                    windowName.toLatin1().data(), (void *)lpcs->hwndParent,
                                    styles.toLatin1().data(), exStyles.toLatin1().data());
             }
             break;
 #endif
 #ifdef WM_DESTROY
         case WM_DESTROY:
             parameters.sprintf("Destroy hwnd (0x%p)", (void *)msg.hwnd);
             break;
 #endif
 #ifdef WM_IME_NOTIFY
         case WM_IME_NOTIFY:
             {
                 QString imnCommand = valueCheck(wParam,
                                             FLGSTR(IMN_CHANGECANDIDATE),
                                             FLGSTR(IMN_CLOSECANDIDATE),
                                             FLGSTR(IMN_CLOSESTATUSWINDOW),
                                             FLGSTR(IMN_GUIDELINE),
                                             FLGSTR(IMN_OPENCANDIDATE),
                                             FLGSTR(IMN_OPENSTATUSWINDOW),
                                             FLGSTR(IMN_SETCANDIDATEPOS),
                                             FLGSTR(IMN_SETCOMPOSITIONFONT),
                                             FLGSTR(IMN_SETCOMPOSITIONWINDOW),
                                             FLGSTR(IMN_SETCONVERSIONMODE),
                                             FLGSTR(IMN_SETOPENSTATUS),
                                             FLGSTR(IMN_SETSENTENCEMODE),
                                             FLGSTR(IMN_SETSTATUSWINDOWPOS),
                                             FLAG_STRING());
                 parameters.sprintf("Command(%s : 0x%p)", imnCommand.toLatin1().data(), (void *)lParam);
             }
             break;
 #endif
 #ifdef WM_IME_SETCONTEXT
         case WM_IME_SETCONTEXT:
             {
                 bool fSet = (BOOL)wParam;
                 DWORD fShow = (DWORD)lParam;
                 QString showFlgs = flagCheck(fShow,
 #ifdef ISC_SHOWUICOMPOSITIONWINDOW
                                              FLGSTR(ISC_SHOWUICOMPOSITIONWINDOW),
 #endif
 #ifdef ISC_SHOWUIGUIDWINDOW
                                              FLGSTR(ISC_SHOWUIGUIDWINDOW),
 #endif
 #ifdef ISC_SHOWUISOFTKBD
                                              FLGSTR(ISC_SHOWUISOFTKBD),
 #endif
                                              FLGSTR(ISC_SHOWUICANDIDATEWINDOW),
                                              FLGSTR(ISC_SHOWUICANDIDATEWINDOW << 1),
                                              FLGSTR(ISC_SHOWUICANDIDATEWINDOW << 2),
                                              FLGSTR(ISC_SHOWUICANDIDATEWINDOW << 3),
                                              FLAG_STRING());
                 parameters.sprintf("Input context(%s) Show flags(%s)", (fSet? "Active" : "Inactive"), showFlgs.toLatin1().data());
             }
             break;
 #endif
 #ifdef WM_KILLFOCUS
         case WM_KILLFOCUS:
             parameters.sprintf("Hwnd gaining keyboard focus (0x%p)", (void *)wParam);
             break;
 #endif
 #ifdef WM_CHAR
         case WM_CHAR:
 #endif
 #ifdef WM_IME_CHAR
         case WM_IME_CHAR:
 #endif
 #ifdef WM_KEYDOWN
         case WM_KEYDOWN:
 #endif
 #ifdef WM_KEYUP
         case WM_KEYUP:
             {
                 int nVirtKey     = (int)wParam;
                 long lKeyData    = (long)lParam;
                 int repCount     = (lKeyData & 0xffff);        // Bit 0-15
                 int scanCode     = (lKeyData & 0xf0000) >> 16; // Bit 16-23
                 bool contextCode = (lKeyData && 0x20000000);   // Bit 29
                 bool prevState   = (lKeyData && 0x40000000);   // Bit 30
                 bool transState  = (lKeyData && 0x80000000);   // Bit 31
                 parameters.sprintf("Virual-key(0x%x) Scancode(%d) Rep(%d) Contextcode(%d), Prev state(%d), Trans state(%d)",
                                    nVirtKey, scanCode, repCount, contextCode, prevState, transState);
             }
             break;
 #endif
 #ifdef WM_INPUTLANGCHANGE
         case WM_INPUTLANGCHANGE:
             parameters = QLatin1String("Keyboard layout changed");
             break;
 #endif // WM_INPUTLANGCHANGE
 #ifdef WM_NCACTIVATE
         case WM_NCACTIVATE:
             {
             parameters = (msg.wParam? QLatin1String("Active Titlebar") : QLatin1String("Inactive Titlebar"));
             }
             break;
 #endif
 #ifdef WM_MOUSEACTIVATE
         case WM_MOUSEACTIVATE:
             {
                 QString mouseMsg = QString::fromLatin1(findWMstr(HIWORD(lParam)));
                 parameters.sprintf("TLW(0x%p) HittestCode(0x%x) MouseMsg(%s)", (void *)wParam, LOWORD(lParam), mouseMsg.toLatin1().data());
             }
             break;
 #endif
 #ifdef WM_MOUSELEAVE
         case WM_MOUSELEAVE:
             break; // wParam & lParam not used
 #endif
 #ifdef WM_MOUSEHOVER
         case WM_MOUSEHOVER:
 #endif
 #ifdef WM_MOUSEWHEEL
         case WM_MOUSEWHEEL:
 #endif
 #ifdef WM_MOUSEHWHEEL
         case WM_MOUSEHWHEEL:
 #endif
 #ifdef WM_LBUTTONDBLCLK
         case WM_LBUTTONDBLCLK:
 #endif
 #ifdef WM_LBUTTONDOWN
         case WM_LBUTTONDOWN:
 #endif
 #ifdef WM_LBUTTONUP
         case WM_LBUTTONUP:
 #endif
 #ifdef WM_MBUTTONDBLCLK
         case WM_MBUTTONDBLCLK:
 #endif
 #ifdef WM_MBUTTONDOWN
         case WM_MBUTTONDOWN:
 #endif
 #ifdef WM_MBUTTONUP
         case WM_MBUTTONUP:
 #endif
 #ifdef WM_RBUTTONDBLCLK
         case WM_RBUTTONDBLCLK:
 #endif
 #ifdef WM_RBUTTONDOWN
         case WM_RBUTTONDOWN:
 #endif
 #ifdef WM_RBUTTONUP
         case WM_RBUTTONUP:
 #endif
 #ifdef WM_MOUSEMOVE
         case WM_MOUSEMOVE:
             {
                 QString vrtKeys = flagCheck(wParam,
                                             FLGSTR(MK_CONTROL),
                                             FLGSTR(MK_LBUTTON),
                                             FLGSTR(MK_MBUTTON),
                                             FLGSTR(MK_RBUTTON),
                                             FLGSTR(MK_SHIFT),
 #ifdef MK_XBUTTON1
                                             FLGSTR(MK_XBUTTON1),
 #endif
 #ifdef MK_XBUTTON2
                                             FLGSTR(MK_XBUTTON2),
 #endif
                                             FLAG_STRING());
                 parameters.sprintf("x,y(%4d,%4d) Virtual Keys(%s)", GET_X_LPARAM(lParam), GET_Y_LPARAM(lParam), vrtKeys.toLatin1().data());
             }
             break;
 #endif
 #ifdef WM_MOVE
         case WM_MOVE:
             parameters.sprintf("x,y(%4d,%4d)", LOWORD(lParam), HIWORD(lParam));
             break;
 #endif
 #if defined(WM_PAINT) && defined(WM_ERASEBKGND)
         case WM_ERASEBKGND:
         case WM_PAINT:
             parameters.sprintf("hdc(0x%p)", (void *)wParam);
             break;
 #endif
 #ifdef WM_QUERYNEWPALETTE
         case WM_QUERYNEWPALETTE:
             break; // lParam & wParam are unused
 #endif
 #ifdef WM_SETCURSOR
         case WM_SETCURSOR:
             {
                 QString mouseMsg = QString::fromLatin1(findWMstr(HIWORD(lParam)));
                 parameters.sprintf("HitTestCode(0x%x) MouseMsg(%s)", LOWORD(lParam), mouseMsg.toLatin1().data());
             }
             break;
 #endif
 #ifdef WM_SETFOCUS
         case WM_SETFOCUS:
             parameters.sprintf("Lost Focus (0x%p)", (void *)wParam);
             break;
 #endif
 #ifdef WM_SETTEXT
         case WM_SETTEXT:
             parameters.sprintf("Set Text (%s)", QString((QChar*)lParam, (int)wcslen(reinterpret_cast<const wchar_t *>(lParam))).toLatin1().data()); //Unicode string
             break;
 #endif
 #ifdef WM_SIZE
         case WM_SIZE:
             {
                 QString showMode = valueCheck(wParam,
                                               FLGSTR(SIZE_MAXHIDE),
                                               FLGSTR(SIZE_MAXIMIZED),
                                               FLGSTR(SIZE_MAXSHOW),
                                               FLGSTR(SIZE_MINIMIZED),
                                               FLGSTR(SIZE_RESTORED),
                                               FLAG_STRING());
                 parameters.sprintf("w,h(%4d,%4d) showmode(%s)", LOWORD(lParam), HIWORD(lParam), showMode.toLatin1().data());
             }
             break;
 #endif
 #ifdef WM_WINDOWPOSCHANGED
         case WM_WINDOWPOSCHANGED:
             {
                 LPWINDOWPOS winPos = (LPWINDOWPOS)lParam;
                 if (!winPos)
                     break;
                 QString hwndAfter = valueCheck(quint64(winPos->hwndInsertAfter),
                                           FLAG_STRING((qptrdiff)HWND_BOTTOM,    "HWND_BOTTOM"),
                                           FLAG_STRING((qptrdiff)HWND_NOTOPMOST, "HWND_NOTOPMOST"),
                                           FLAG_STRING((qptrdiff)HWND_TOP,       "HWND_TOP"),
                                           FLAG_STRING((qptrdiff)HWND_TOPMOST,   "HWND_TOPMOST"),
                                           FLAG_STRING());
                 if (hwndAfter.isEmpty())
                     hwndAfter = QString::number((quintptr)winPos->hwndInsertAfter, 16);
                 QString flags = flagCheck(winPos->flags,
                                           FLGSTR(SWP_DRAWFRAME),
                                           FLGSTR(SWP_FRAMECHANGED),
                                           FLGSTR(SWP_HIDEWINDOW),
                                           FLGSTR(SWP_NOACTIVATE),
 #ifdef SWP_NOCOPYBITS
                                           FLGSTR(SWP_NOCOPYBITS),
 #endif
                                           FLGSTR(SWP_NOMOVE),
                                           FLGSTR(SWP_NOOWNERZORDER),
                                           FLGSTR(SWP_NOREDRAW),
                                           FLGSTR(SWP_NOREPOSITION),
 #ifdef SWP_NOSENDCHANGING
                                           FLGSTR(SWP_NOSENDCHANGING),
 #endif
                                           FLGSTR(SWP_NOSIZE),
                                           FLGSTR(SWP_NOZORDER),
                                           FLGSTR(SWP_SHOWWINDOW),
                                           FLAG_STRING());
                 parameters.sprintf("x,y(%4d,%4d) w,h(%4d,%4d) flags(%s) hwndAfter(%s)", winPos->x, winPos->y, winPos->cx, winPos->cy, flags.toLatin1().data(), hwndAfter.toLatin1().data());
             }
             break;
 #endif
         default:
             parameters.sprintf("wParam(0x%p) lParam(0x%p)", (void *)wParam, (void *)lParam);
             break;
     }
     // Yes, we want to give the WM_ names 20 chars of space before showing the
     // decoded message, since some of the common messages are quite long, and
     // we don't want the decoded information to vary in output position
     QString message = QString::fromLatin1("%1: ").arg(wmmsg, 20);
     message += rawParameters;
     message += parameters;
     return message;
 }
findWMstr()
static const char* findWMstr (uint msg) static
Definition at line 568 of file qcoreapplication_win.cpp.
Referenced by decodeMSG().
 {
     uint i = 0;
     const char* result = 0;
     // Known WM_'s
     while (knownWM[i].str && (knownWM[i].WM != msg))
         ++i;
     result = knownWM[i].str;
     return result;
 };
FLAG_STRING()
FLAG_STRING_STRUCT FLAG_STRING (uint value = 0, const char * c = 0)
Definition at line 586 of file qcoreapplication_win.cpp.
Referenced by decodeMSG().
 {
     FLAG_STRING_STRUCT s = {value, c};
     return s;
 }
flagCheck()
QString flagCheck (uint actual, ...)
Definition at line 597 of file qcoreapplication_win.cpp.
Referenced by decodeMSG().
 {
     va_list ap;
     va_start(ap, actual);
     QString result;
     int count = 0;
     FLAG_STRING_STRUCT v;
     while((v=va_arg(ap,FLAG_STRING_STRUCT)).str) {
         if ((actual & v.value) == v.value) {
             if (count++)
                 result += QLatin1String(" | ");
             result += QString::fromLatin1(v.str);
         }
     }
     va_end(ap);
     return result;
 };
operator<<()
QDebug operator<< (QDebug dbg, const MSG & msg)
Definition at line 1058 of file qcoreapplication_win.cpp.
 {
     dbg << decodeMSG(msg);
     return dbg.nospace();
 }
qAppFileName()
Q_CORE_EXPORT QString qAppFileName ()
Definition at line 82 of file qcoreapplication_win.cpp.
Referenced by QCoreApplication::applicationFilePath(), QCoreApplicationPrivate::appName(), and QSystemLibrary::load().
 {
     // We do MAX_PATH + 2 here, and request with MAX_PATH + 1, so we can handle all paths
     // up to, and including MAX_PATH size perfectly fine with string termination, as well
     // as easily detect if the file path is indeed larger than MAX_PATH, in which case we
     // need to use the heap instead. This is a work-around, since contrary to what the
     // MSDN documentation states, GetModuleFileName sometimes doesn't set the
     // ERROR_INSUFFICIENT_BUFFER error number, and we thus cannot rely on this value if
     // GetModuleFileName(0, buffer, MAX_PATH) == MAX_PATH.
     // GetModuleFileName(0, buffer, MAX_PATH + 1) == MAX_PATH just means we hit the normal
     // file path limit, and we handle it normally, if the result is MAX_PATH + 1, we use
     // heap (even if the result _might_ be exactly MAX_PATH + 1, but that's ok).
     wchar_t buffer[MAX_PATH + 2];
     DWORD v = GetModuleFileName(0, buffer, MAX_PATH + 1);
     buffer[MAX_PATH + 1] = 0;
     if (v == 0)
         return QString();
     else if (v <= MAX_PATH)
         return QString::fromWCharArray(buffer);
     // MAX_PATH sized buffer wasn't large enough to contain the full path, use heap
     wchar_t *b = 0;
     int i = 1;
     size_t size;
     do {
         ++i;
         size = MAX_PATH * i;
         b = reinterpret_cast<wchar_t *>(realloc(b, (size + 1) * sizeof(wchar_t)));
         if (b)
             v = GetModuleFileName(NULL, b, size);
     } while (b && v == size);
     if (b)
         *(b + size) = 0;
     QString res = QString::fromWCharArray(b);
     free(b);
     return res;
 }
qWinAppCmdShow()
Q_CORE_EXPORT int qWinAppCmdShow ()
Definition at line 68 of file qcoreapplication_win.cpp.
 {
 #if defined(Q_OS_WINCE)
     return appCmdShow;
 #else
     STARTUPINFO startupInfo;
     GetStartupInfo(&startupInfo);
     return (startupInfo.dwFlags & STARTF_USESHOWWINDOW)
         ? startupInfo.wShowWindow
         : SW_SHOWDEFAULT;
 #endif
 }
qWinAppInst()
Q_CORE_EXPORT HINSTANCE qWinAppInst ()
Definition at line 58 of file qcoreapplication_win.cpp.
Referenced by create32BitCursor(), qt_create_internal_window(), qt_reg_winclass(), qt_tablet_cleanup_wce(), qt_wce_get_module_handle(), unregWinClasses(), QMenuBarPrivate::wceCreateMenuBar(), and QEventDispatcherWin32Private::~QEventDispatcherWin32Private().
 {
     return GetModuleHandle(0);
 }
qWinAppPrevInst()
Q_CORE_EXPORT HINSTANCE qWinAppPrevInst ()
Definition at line 63 of file qcoreapplication_win.cpp.
 {
     return 0;
 }
qWinMain()
Q_CORE_EXPORT void __cdecl qWinMain (HINSTANCE instance, HINSTANCE prevInstance, LPSTR cmdParam, int cmdShow, int & argc, QVector< char *> & argv)
Definition at line 170 of file qcoreapplication_win.cpp.
Referenced by qax_stopServer(), and WinMain().
 {
     static bool already_called = false;
     if (already_called) {
         qWarning("Qt: Internal error: qWinMain should be called only once");
         return;
     }
     already_called = true;
     usingWinMain = true;
     // Install default debug handler
     qInstallMsgHandler(qWinMsgHandler);
     // Create command line
     argv = qWinCmdLine<char>(cmdParam, int(strlen(cmdParam)), argc);
     appCmdShow = cmdShow;
     // Ignore Windows parameters
     Q_UNUSED(instance);
     Q_UNUSED(prevInstance);
 }
qWinMsgHandler()
Q_CORE_EXPORT void qWinMsgHandler (QtMsgType t, const char * str)
Definition at line 143 of file qcoreapplication_win.cpp.
Referenced by QClassFactory::CreateInstanceHelper(), qax_winEventFilter(), qInstallMsgHandler(), qt_error_string(), and qWinMain().
 {
     Q_UNUSED(t);
     // OutputDebugString is not threadsafe.
     // cannot use QMutex here, because qWarning()s in the QMutex
     // implementation may cause this function to recurse
     static QWinMsgHandlerCriticalSection staticCriticalSection;
     if (!str)
         str = "(null)";
     staticCriticalSection.lock();
     QString s(QString::fromLocal8Bit(str));
     s += QLatin1Char('\n');
     OutputDebugString((wchar_t*)s.utf16());
     staticCriticalSection.unlock();
 }
valueCheck()
QString valueCheck (uint actual, ...)
Definition at line 619 of file qcoreapplication_win.cpp.
Referenced by decodeMSG().
 {
     va_list ap;
     va_start(ap, actual);
     QString result;
     FLAG_STRING_STRUCT v;
     while((v=va_arg(ap,FLAG_STRING_STRUCT)).str && (actual != v.value))
         ;
     result = QString::fromLatin1(v.str);
     va_end(ap);
     return result;
 };
Variable Documentation
appCmdShow
int appCmdShow = 0
Definition at line 56 of file qcoreapplication_win.cpp.
Referenced by qWinAppCmdShow(), and qWinMain().
knownWM
struct KnownWM knownWM[]
Referenced by findWMstr().
usingWinMain
bool usingWinMain = false
Definition at line 55 of file qcoreapplication_win.cpp.
Referenced by qInstallMsgHandler(), qt_error_string(), and qWinMain().