Qt 4.8: /src/corelib/kernel/qcore_unix.cpp File Reference
qcore_unix.cpp File Reference
#include "qcore_unix_p.h"
#include "qelapsedtimer.h"
#include <sys/select.h>
#include <sys/time.h>
#include <stdlib.h>
#include <mach/mach_time.h>
Functions
int qt_safe_select (int nfds, fd_set *fdread, fd_set *fdwrite, fd_set *fdexcept, const struct timeval *orig_timeout)
static bool time_update (struct timeval *tv, const struct timeval &start, const struct timeval &timeout)
Function Documentation
qt_safe_select()
int qt_safe_select (int nfds, fd_set * fdread, fd_set * fdwrite, fd_set * fdexcept, const struct timeval * orig_timeout)
Definition at line 73 of file qcore_unix.cpp.
Referenced by QNativeSocketEnginePrivate::nativeSelect(), SelectWorker::run(), QEventDispatcherUNIX::select(), and select_msecs().
 {
     if (!orig_timeout) {
         // no timeout -> block forever
         register int ret;
         EINTR_LOOP(ret, select(nfds, fdread, fdwrite, fdexcept, 0));
         return ret;
     }
     timeval start = qt_gettime();
     timeval timeout = *orig_timeout;
     // loop and recalculate the timeout as needed
     int ret;
     forever {
         ret = ::select(nfds, fdread, fdwrite, fdexcept, &timeout);
         if (ret != -1 || errno != EINTR)
             return ret;
         // recalculate the timeout
         if (!time_update(&timeout, start, *orig_timeout)) {
             // timeout during update
             // or clock reset, fake timeout error
             return 0;
         }
     }
 }
time_update()
static bool time_update (struct timeval * tv, const struct timeval & start, const struct timeval & timeout) inline static
Definition at line 63 of file qcore_unix.cpp.
Referenced by qt_safe_select().
 {
     // clock source is (hopefully) monotonic, so we can recalculate how much timeout is left;
     // if it isn't monotonic, we'll simply hope that it hasn't jumped, because we have no alternative
     struct timeval now = qt_gettime();
     *tv = timeout + start - now;
     return tv->tv_sec >= 0;
 }