Qt 4.8: /src/gui/painting/qcosmeticstroker.cpp File Reference
qcosmeticstroker.cpp File Reference
#include "qcosmeticstroker_p.h"
#include "private/qpainterpath_p.h"
#include <qdebug.h>
#include <math.h>
Macros
#define toF26Dot6(x) ((int)((x)*64.))
Typedefs
typedef void(* DrawPixel) (QCosmeticStroker *stroker, int x, int y, int coverage)
Enumerations
enum StrokeSelection {
Aliased = 0, AntiAliased = 1, Solid = 0, Dashed = 2,
RegularDraw = 0, FastDraw = 4
}
Functions
static void capAdjust (int caps, int &x1, int &x2, int &y, int yinc)
template<DrawPixel drawPixel, class Dasher >
static bool drawLine (QCosmeticStroker *stroker, qreal x1, qreal y1, qreal x2, qreal y2, int caps)
template<DrawPixel drawPixel, class Dasher >
static bool drawLineAA (QCosmeticStroker *stroker, qreal x1, qreal y1, qreal x2, qreal y2, int caps)
void drawPixel (QCosmeticStroker *stroker, int x, int y, int coverage)
void drawPixelARGB32 (QCosmeticStroker *stroker, int x, int y, int coverage)
void drawPixelARGB32Opaque (QCosmeticStroker *stroker, int x, int y, int)
static int F16Dot16FixedDiv (int x, int y)
static uint sourceOver (uint d, uint color)
static void splitCubic (QCosmeticStroker::PointF *points)
static StrokeLine strokeLine (int strokeSelection)
static const QPainterPath::ElementType * subPath (const QPainterPath::ElementType *t, const QPainterPath::ElementType *end, const qreal *points, bool *closed)
static int swapCaps (int caps)
Macro Definition Documentation
toF26Dot6
#define toF26Dot6 (x) ((int)((x)*64.))
Definition at line 63 of file qcosmeticstroker.cpp.
Referenced by QCosmeticStroker::calculateLastPoint(), drawLine(), and drawLineAA().
Typedef Documentation
DrawPixel
typedef void(* DrawPixel) (QCosmeticStroker *stroker, int x, int y, int coverage)
Definition at line 77 of file qcosmeticstroker.cpp.
Enumeration Type Documentation
StrokeSelection
enum StrokeSelection
Enumerator
Aliased
AntiAliased
Solid
Dashed
RegularDraw
FastDraw
Definition at line 188 of file qcosmeticstroker.cpp.
                      {
     Aliased = 0,
     AntiAliased = 1,
     Solid = 0,
     Dashed = 2,
     RegularDraw = 0,
     FastDraw = 4
 };
Function Documentation
capAdjust()
static void capAdjust (int caps, int & x1, int & x2, int & y, int yinc) inline static
Definition at line 718 of file qcosmeticstroker.cpp.
Referenced by drawLine(), and drawLineAA().
 {
     if (caps & QCosmeticStroker::CapBegin) {
         x1 -= 32;
         y -= yinc >> 1;
     }
     if (caps & QCosmeticStroker::CapEnd) {
         x2 += 32;
     }
 }
drawLine()
template<DrawPixel drawPixel, class Dasher > static bool drawLine (QCosmeticStroker * stroker, qreal x1, qreal y1, qreal x2, qreal y2, int caps) static
Definition at line 734 of file qcosmeticstroker.cpp.
Referenced by QPainter::drawLine().
 {
     if (stroker->clipLine(rx1, ry1, rx2, ry2))
         return false;
     static const int half = 31;
     int x1 = toF26Dot6(rx1) + half;
     int y1 = toF26Dot6(ry1) + half;
     int x2 = toF26Dot6(rx2) + half;
     int y2 = toF26Dot6(ry2) + half;
     int dx = qAbs(x2 - x1);
     int dy = qAbs(y2 - y1);
     QCosmeticStroker::Point last = stroker->lastPixel;
 //    qDebug() << "stroke" << x1/64. << y1/64. << x2/64. << y2/64.;
     if (dx < dy) {
         // vertical
         QCosmeticStroker::Direction dir = QCosmeticStroker::TopToBottom;
         bool swapped = false;
         if (y1 > y2) {
             swapped = true;
             qSwap(y1, y2);
             qSwap(x1, x2);
             caps = swapCaps(caps);
             dir = QCosmeticStroker::BottomToTop;
         }
         int xinc = F16Dot16FixedDiv(x2 - x1, y2 - y1);
         int x = x1 << 10;
         if ((stroker->lastDir ^ QCosmeticStroker::VerticalMask) == dir)
             caps |= swapped ? QCosmeticStroker::CapEnd : QCosmeticStroker::CapBegin;
         capAdjust(caps, y1, y2, x, xinc);
         int y = (y1 + 32) >> 6;
         int ys = (y2 + 32) >> 6;
         if (y != ys) {
             x += ( ((((y << 6) + 32 - y1)))  * xinc ) >> 6;
             // calculate first and last pixel and perform dropout control
             QCosmeticStroker::Point first;
             first.x = x >> 16;
             first.y = y;
             last.x = (x + (ys - y - 1)*xinc) >> 16;
             last.y = ys - 1;
             if (swapped)
                 qSwap(first, last);
             bool axisAligned = qAbs(xinc) < (1 << 14);
             if (stroker->lastPixel.x >= 0) {
                 if (first.x == stroker->lastPixel.x &&
                     first.y == stroker->lastPixel.y) {
                     // remove duplicated pixel
                     if (swapped) {
                         --ys;
                     } else {
                         ++y;
                         x += xinc;
                     }
                 } else if (stroker->lastDir != dir &&
                            (((axisAligned && stroker->lastAxisAligned) &&
                              stroker->lastPixel.x != first.x && stroker->lastPixel.y != first.y) ||
                             (qAbs(stroker->lastPixel.x - first.x) > 1 ||
                              qAbs(stroker->lastPixel.y - first.y) > 1))) {
                     // have a missing pixel, insert it
                     if (swapped) {
                         ++ys;
                     } else {
                         --y;
                         x -= xinc;
                     }
                 }
             }
             stroker->lastDir = dir;
             stroker->lastAxisAligned = axisAligned;
             Dasher dasher(stroker, swapped, y << 6, ys << 6);
             do {
                 if (dasher.on())
                     drawPixel(stroker, x >> 16, y, 255);
                 dasher.adjust();
                 x += xinc;
             } while (++y < ys);
         }
     } else {
         // horizontal
         if (!dx)
             return true;
         QCosmeticStroker::Direction dir = QCosmeticStroker::LeftToRight;
         bool swapped = false;
         if (x1 > x2) {
             swapped = true;
             qSwap(x1, x2);
             qSwap(y1, y2);
             caps = swapCaps(caps);
             dir = QCosmeticStroker::RightToLeft;
         }
         int yinc = F16Dot16FixedDiv(y2 - y1, x2 - x1);
         int y = y1 << 10;
         if ((stroker->lastDir ^ QCosmeticStroker::HorizontalMask) == dir)
             caps |= swapped ? QCosmeticStroker::CapEnd : QCosmeticStroker::CapBegin;
         capAdjust(caps, x1, x2, y, yinc);
         int x = (x1 + 32) >> 6;
         int xs = (x2 + 32) >> 6;
         if (x != xs) {
             y += ( ((((x << 6) + 32 - x1)))  * yinc ) >> 6;
             // calculate first and last pixel to perform dropout control
             QCosmeticStroker::Point first;
             first.x = x;
             first.y = y >> 16;
             last.x = xs - 1;
             last.y = (y + (xs - x - 1)*yinc) >> 16;
             if (swapped)
                 qSwap(first, last);
             bool axisAligned = qAbs(yinc) < (1 << 14);
             if (stroker->lastPixel.x >= 0) {
                 if (first.x == stroker->lastPixel.x && first.y == stroker->lastPixel.y) {
                     // remove duplicated pixel
                     if (swapped) {
                         --xs;
                     } else {
                         ++x;
                         y += yinc;
                     }
                 } else if (stroker->lastDir != dir &&
                            (((axisAligned && stroker->lastAxisAligned) &&
                              stroker->lastPixel.x != first.x && stroker->lastPixel.y != first.y) ||
                             (qAbs(stroker->lastPixel.x - first.x) > 1 ||
                              qAbs(stroker->lastPixel.y - first.y) > 1))) {
                     // have a missing pixel, insert it
                     if (swapped) {
                         ++xs;
                     } else {
                         --x;
                         y -= yinc;
                     }
                 }
             }
             stroker->lastDir = dir;
             stroker->lastAxisAligned = axisAligned;
             Dasher dasher(stroker, swapped, x << 6, xs << 6);
             do {
                 if (dasher.on())
                     drawPixel(stroker, x, y >> 16, 255);
                 dasher.adjust();
                 y += yinc;
             } while (++x < xs);
         }
     }
     stroker->lastPixel = last;
     return true;
 }
drawLineAA()
template<DrawPixel drawPixel, class Dasher > static bool drawLineAA (QCosmeticStroker * stroker, qreal x1, qreal y1, qreal x2, qreal y2, int caps) static
Definition at line 905 of file qcosmeticstroker.cpp.
 {
     if (stroker->clipLine(rx1, ry1, rx2, ry2))
         return false;
     int x1 = toF26Dot6(rx1);
     int y1 = toF26Dot6(ry1);
     int x2 = toF26Dot6(rx2);
     int y2 = toF26Dot6(ry2);
     int dx = x2 - x1;
     int dy = y2 - y1;
     if (qAbs(dx) < qAbs(dy)) {
         // vertical
         int xinc = F16Dot16FixedDiv(dx, dy);
         bool swapped = false;
         if (y1 > y2) {
             qSwap(y1, y2);
             qSwap(x1, x2);
             swapped = true;
             caps = swapCaps(caps);
         }
         int x = (x1 - 32) << 10;
         x -= ( ((y1 & 63) - 32)  * xinc ) >> 6;
         capAdjust(caps, y1, y2, x, xinc);
         Dasher dasher(stroker, swapped, y1, y2);
         int y = y1 >> 6;
         int ys = y2 >> 6;
         int alphaStart, alphaEnd;
         if (y == ys) {
             alphaStart = y2 - y1;
             Q_ASSERT(alphaStart >= 0 && alphaStart < 64);
             alphaEnd = 0;
         } else {
             alphaStart = 64 - (y1 & 63);
             alphaEnd = (y2 & 63);
         }
 //        qDebug() << "vertical" << x1/64. << y1/64. << x2/64. << y2/64.;
 //        qDebug() << "          x=" << x << "dx=" << dx << "xi=" << (x>>16) << "xsi=" << ((x+(ys-y)*dx)>>16) << "y=" << y << "ys=" << ys;
         // draw first pixel
         if (dasher.on()) {
             uint alpha = (quint8)(x >> 8);
             drawPixel(stroker, x>>16, y, (255-alpha) * alphaStart >> 6);
             drawPixel(stroker, (x>>16) + 1, y, alpha * alphaStart >> 6);
         }
         dasher.adjust();
         x += xinc;
         ++y;
         if (y < ys) {
             do {
                 if (dasher.on()) {
                     uint alpha = (quint8)(x >> 8);
                     drawPixel(stroker, x>>16, y, (255-alpha));
                     drawPixel(stroker, (x>>16) + 1, y, alpha);
                 }
                 dasher.adjust();
                 x += xinc;
             } while (++y < ys);
         }
         // draw last pixel
         if (alphaEnd && dasher.on()) {
             uint alpha = (quint8)(x >> 8);
             drawPixel(stroker, x>>16, y, (255-alpha) * alphaEnd >> 6);
             drawPixel(stroker, (x>>16) + 1, y, alpha * alphaEnd >> 6);
         }
     } else {
         // horizontal
         if (!dx)
             return true;
         int yinc = F16Dot16FixedDiv(dy, dx);
         bool swapped = false;
         if (x1 > x2) {
             qSwap(x1, x2);
             qSwap(y1, y2);
             swapped = true;
             caps = swapCaps(caps);
         }
         int y = (y1 - 32) << 10;
         y -= ( ((x1 & 63) - 32)  * yinc ) >> 6;
         capAdjust(caps, x1, x2, y, yinc);
         Dasher dasher(stroker, swapped, x1, x2);
         int x = x1 >> 6;
         int xs = x2 >> 6;
 //        qDebug() << "horizontal" << x1/64. << y1/64. << x2/64. << y2/64.;
 //        qDebug() << "          y=" << y << "dy=" << dy << "x=" << x << "xs=" << xs << "yi=" << (y>>16) << "ysi=" << ((y+(xs-x)*dy)>>16);
         int alphaStart, alphaEnd;
         if (x == xs) {
             alphaStart = x2 - x1;
             Q_ASSERT(alphaStart >= 0 && alphaStart < 64);
             alphaEnd = 0;
         } else {
             alphaStart = 64 - (x1 & 63);
             alphaEnd = (x2 & 63);
         }
         // draw first pixel
         if (dasher.on()) {
             uint alpha = (quint8)(y >> 8);
             drawPixel(stroker, x, y>>16, (255-alpha) * alphaStart >> 6);
             drawPixel(stroker, x, (y>>16) + 1, alpha * alphaStart >> 6);
         }
         dasher.adjust();
         y += yinc;
         ++x;
         // draw line
         if (x < xs) {
             do {
                 if (dasher.on()) {
                     uint alpha = (quint8)(y >> 8);
                     drawPixel(stroker, x, y>>16, (255-alpha));
                     drawPixel(stroker, x, (y>>16) + 1, alpha);
                 }
                 dasher.adjust();
                 y += yinc;
             } while (++x < xs);
         }
         // draw last pixel
         if (alphaEnd && dasher.on()) {
             uint alpha = (quint8)(y >> 8);
             drawPixel(stroker, x, y>>16, (255-alpha) * alphaEnd >> 6);
             drawPixel(stroker, x, (y>>16) + 1, alpha * alphaEnd >> 6);
         }
     }
     return true;
 }
drawPixel()
void drawPixel (QCosmeticStroker * stroker, int x, int y, int coverage) inline
Definition at line 146 of file qcosmeticstroker.cpp.
Referenced by drawLine(), drawLineAA(), QCosmeticStroker::drawPoints(), and strokeLine().
 {
     const QRect &cl = stroker->clip;
     if (x < cl.x() || x > cl.right() || y < cl.y() || y > cl.bottom())
         return;
     int lastx = stroker->spans[stroker->current_span-1].x + stroker->spans[stroker->current_span-1].len ;
     int lasty = stroker->spans[stroker->current_span-1].y;
     if (stroker->current_span == QCosmeticStroker::NSPANS || y < lasty || (y == lasty && x < lastx)) {
         stroker->blend(stroker->current_span, stroker->spans, &stroker->state->penData);
         stroker->current_span = 0;
     }
     stroker->spans[stroker->current_span].x = ushort(x);
     stroker->spans[stroker->current_span].len = 1;
     stroker->spans[stroker->current_span].y = y;
     stroker->spans[stroker->current_span].coverage = coverage*stroker->opacity >> 8;
     ++stroker->current_span;
 }
drawPixelARGB32()
void drawPixelARGB32 (QCosmeticStroker * stroker, int x, int y, int coverage) inline
Definition at line 167 of file qcosmeticstroker.cpp.
Referenced by strokeLine().
 {
     const QRect &cl = stroker->clip;
     if (x < cl.x() || x > cl.right() || y < cl.y() || y > cl.bottom())
         return;
     int offset = x + stroker->ppl*y;
     uint c = BYTE_MUL(stroker->color, coverage);
     stroker->pixels[offset] = sourceOver(stroker->pixels[offset], c);
 }
drawPixelARGB32Opaque()
void drawPixelARGB32Opaque (QCosmeticStroker * stroker, int x, int y, int) inline
Definition at line 178 of file qcosmeticstroker.cpp.
Referenced by strokeLine().
 {
     const QRect &cl = stroker->clip;
     if (x < cl.x() || x > cl.right() || y < cl.y() || y > cl.bottom())
         return;
     int offset = x + stroker->ppl*y;
     stroker->pixels[offset] = sourceOver(stroker->pixels[offset], stroker->color);
 }
F16Dot16FixedDiv()
static int F16Dot16FixedDiv (int x, int y) inline static
Definition at line 70 of file qcosmeticstroker.cpp.
Referenced by QCosmeticStroker::calculateLastPoint(), drawLine(), and drawLineAA().
 {
     if (qAbs(x) > 0x7fff)
         return (((qlonglong)x) << 16) / y;
     return (x << 16) / y;
 }
sourceOver()
static uint sourceOver (uint d, uint color) inline static
Definition at line 65 of file qcosmeticstroker.cpp.
Referenced by drawPixelARGB32(), and drawPixelARGB32Opaque().
 {
     return color + BYTE_MUL(d, qAlpha(~color));
 }
splitCubic()
static void splitCubic (QCosmeticStroker::PointF * points) static
Definition at line 664 of file qcosmeticstroker.cpp.
Referenced by QCosmeticStroker::renderCubicSubdivision().
 {
     const qreal half = .5;
     qreal  a, b, c, d;
     points[6].x = points[3].x;
     c = points[1].x;
     d = points[2].x;
     points[1].x = a = ( points[0].x + c ) * half;
     points[5].x = b = ( points[3].x + d ) * half;
     c = ( c + d ) * half;
     points[2].x = a = ( a + c ) * half;
     points[4].x = b = ( b + c ) * half;
     points[3].x = ( a + b ) * half;
     points[6].y = points[3].y;
     c = points[1].y;
     d = points[2].y;
     points[1].y = a = ( points[0].y + c ) * half;
     points[5].y = b = ( points[3].y + d ) * half;
     c = ( c + d ) * half;
     points[2].y = a = ( a + c ) * half;
     points[4].y = b = ( b + c ) * half;
     points[3].y = ( a + b ) * half;
 }
strokeLine()
static StrokeLine strokeLine (int strokeSelection) static
Definition at line 197 of file qcosmeticstroker.cpp.
Referenced by QCosmeticStroker::setup().
 {
     StrokeLine stroke;
     switch (strokeSelection) {
     case Aliased|Solid|RegularDraw:
         stroke = &QT_PREPEND_NAMESPACE(drawLine)<drawPixel, NoDasher>;
         break;
     case Aliased|Solid|FastDraw:
         stroke = &QT_PREPEND_NAMESPACE(drawLine)<drawPixelARGB32Opaque, NoDasher>;
         break;
     case Aliased|Dashed|RegularDraw:
         stroke = &QT_PREPEND_NAMESPACE(drawLine)<drawPixel, Dasher>;
         break;
     case Aliased|Dashed|FastDraw:
         stroke = &QT_PREPEND_NAMESPACE(drawLine)<drawPixelARGB32Opaque, Dasher>;
         break;
     case AntiAliased|Solid|RegularDraw:
         stroke = &QT_PREPEND_NAMESPACE(drawLineAA)<drawPixel, NoDasher>;
         break;
     case AntiAliased|Solid|FastDraw:
         stroke = &QT_PREPEND_NAMESPACE(drawLineAA)<drawPixelARGB32, NoDasher>;
         break;
     case AntiAliased|Dashed|RegularDraw:
         stroke = &QT_PREPEND_NAMESPACE(drawLineAA)<drawPixel, Dasher>;
         break;
     case AntiAliased|Dashed|FastDraw:
         stroke = &QT_PREPEND_NAMESPACE(drawLineAA)<drawPixelARGB32, Dasher>;
         break;
     default:
         Q_ASSERT(false);
         stroke = 0;
     }
     return stroke;
 }
subPath()
static const QPainterPath::ElementType* subPath (const QPainterPath::ElementType * t, const QPainterPath::ElementType * end, const qreal * points, bool * closed) inline static
Definition at line 498 of file qcosmeticstroker.cpp.
Referenced by QCosmeticStroker::drawPath().
 {
     const QPainterPath::ElementType *start = t;
     ++t;
     // find out if the subpath is closed
     while (t < end) {
         if (*t == QPainterPath::MoveToElement)
             break;
         ++t;
     }
     int offset = t - start - 1;
 //    qDebug() << "subpath" << offset << points[0] << points[1] << points[2*offset] << points[2*offset+1];
     *closed = (points[0] == points[2*offset] && points[1] == points[2*offset + 1]);
     return t;
 }
swapCaps()
static int swapCaps (int caps) inline static
Definition at line 711 of file qcosmeticstroker.cpp.
Referenced by drawLine(), and drawLineAA().
 {
     return ((caps & QCosmeticStroker::CapBegin) << 1) |
            ((caps & QCosmeticStroker::CapEnd) >> 1);
 }