Qt 4.8: /src/corelib/kernel/qcrashhandler.cpp File Reference
qcrashhandler.cpp File Reference
#include "qplatformdefs.h"
#include "private/qcrashhandler_p.h"
#include "qbytearray.h"
#include <stdio.h>
#include <signal.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/wait.h>
Functions
static bool backtrace_command (FILE *outb, const char *format,...)
static void init_backtrace (char **argv, int argc)
static void print_backtrace (FILE *outb)
void qt_signal_handler (int sig)
Variables
static char * globalProgName = NULL
Function Documentation
backtrace_command()
static bool backtrace_command (FILE * outb, const char * format, ...) static
Definition at line 114 of file qcrashhandler.cpp.
Referenced by print_backtrace().
 {
     bool ret = false;
     char buffer[50];
     /*
      * Please note that vsnprintf() is not ASync safe (ie. cannot safely
      * be used from a signal handler.) If this proves to be a problem
      * then the cmd string can be built by more basic functions such as
      * strcpy, strcat, and a home-made integer-to-ascii function.
      */
     va_list args;
     char cmd[512];
     va_start(args, format);
     qvsnprintf(cmd, 512, format, args);
     va_end(args);
     char *foo = cmd;
 #if 0
     foo = "echo hi";
 #endif
     if(FILE *inb = popen(foo, "r")) {
         while(!feof(inb)) {
             int len = fread(buffer, 1, sizeof(buffer), inb);
             if(!len)
                 break;
             if(!ret) {
                 fwrite("Output from ", 1, strlen("Output from "), outb);
                 strtok(cmd, " ");
                 fwrite(cmd, 1, strlen(cmd), outb);
                 fwrite("\n", 1, 1, outb);
                 ret = true;
             }
             fwrite(buffer, 1, len, outb);
         }
         fclose(inb);
     }
     return ret;
 }
init_backtrace()
static void init_backtrace (char ** argv, int argc) static
Definition at line 155 of file qcrashhandler.cpp.
Referenced by QSegfaultHandler::initialize().
 {
     if(argc >= 1)
         globalProgName = argv[0];
 }
print_backtrace()
static void print_backtrace (FILE * outb) static
Definition at line 161 of file qcrashhandler.cpp.
Referenced by qt_signal_handler().
 {
     /*
      * In general dbx seems to do a better job than gdb.
      *
      * Different dbx implementations require different flags/commands.
      */
 #if defined(Q_OS_AIX)
     if(backtrace_command(outb, "dbx -a %d 2>/dev/null <<EOF\n"
                          "where\n"
                          "detach\n"
                          "EOF\n",
                          (int)getpid()))
         return;
     if(backtrace_command(outb, "gdb -q %s %d 2>/dev/null <<EOF\n"
                          "set prompt\n"
                          "where\n"
                          "detach\n"
                          "quit\n"
                          "EOF\n",
                          globalProgName, (int)getpid()))
         return;
 #elif defined(Q_OS_FREEBSD)
     /*
      * FreeBSD insists on sending a SIGSTOP to the process we
      * attach to, so we let the debugger send a SIGCONT to that
      * process after we have detached.
      */
     if(backtrace_command(outb, "gdb -q %s %d 2>/dev/null <<EOF\n"
                          "set prompt\n"
                          "where\n"
                          "detach\n"
                          "shell kill -CONT %d\n"
                          "quit\n"
                          "EOF\n",
                          globalProgName, (int)getpid(), (int)getpid()))
         return;
 #elif defined(Q_OS_HPUX)
     /*
      * HP decided to call their debugger xdb.
      *
      * This does not seem to work properly yet. The debugger says
      * "Note: Stack traces may not be possible until you are
      *  stopped in user code." on HP-UX 09.01
      *
      * -L = line-oriented interface.
      * "T [depth]" gives a stacktrace with local variables.
      * The final "y" is confirmation to the quit command.
      */
     if(backtrace_command(outb, "xdb -P %d -L %s 2>&1 <<EOF\n"
                          "T 50\n"
                          "q\ny\n"
                          "EOF\n",
                          (int)getpid(), globalProgName))
         return;
     if(backtrace_command(outb, "gdb -q %s %d 2>/dev/null <<EOF\n"
                          "set prompt\n"
                          "where\n"
                          "detach\n"
                          "quit\n"
                          "EOF\n",
                          globalProgName, (int)getpid()))
         return;
 #elif defined(Q_OS_IRIX)
     /*
      * "set $page=0" drops hold mode
      * "dump ." displays the contents of the variables
      */
     if(backtrace_command(outb, "dbx -p %d 2>/dev/null <<EOF\n"
                          "set \\$page=0\n"
                          "where\n"
 # if !defined(__GNUC__)
                          /* gcc does not generate this information */
                          "dump .\n"
 # endif
                          "detach\n"
                          "EOF\n",
                          (int)getpid()))
         return;
 # if defined(USE_LIBEXC)
     if(trace_back_stack_and_print())
         return;
 # endif
     if(backtrace_command(outb, "gdb -q %s %d 2>/dev/null <<EOF\n"
                          "set prompt\n"
                          "where\n"
                          "echo ---\\n\n"
                          "frame 5\n"      /* Skip signal handler frames */
                          "set \\$x = 50\n"
                          "while (\\$x)\n" /* Print local variables for each frame */
                          "info locals\n"
                          "up\n"
                          "set \\$x--\n"
                          "end\n"
                          "echo ---\\n\n"
                          "detach\n"
                          "quit\n"
                          "EOF\n",
                          globalProgName, (int)getpid()))
         return;
 #elif defined(Q_OS_OSF)
     if(backtrace_command(outb, "dbx -pid %d %s 2>/dev/null <<EOF\n"
                          "where\n"
                          "detach\n"
                          "quit\n"
                          "EOF\n",
                          (int)getpid(), globalProgName))
         return;
     if(backtrace_command(outb, "gdb -q %s %d 2>/dev/null <<EOF\n"
                          "set prompt\n"
                          "where\n"
                          "detach\n"
                          "quit\n"
                          "EOF\n",
                          globalProgName, (int)getpid()))
         return;
 #elif defined(Q_OS_SCO)
     /*
      * SCO OpenServer dbx is like a catch-22. The 'detach' command
      * depends on whether ptrace(S) support detaching or not. If it
      * is supported then 'detach' must be used, otherwise the process
      * will be killed upon dbx exit. If it isn't supported then 'detach'
      * will cause the process to be killed. We do not want it to be
      * killed.
      *
      * Out of two evils, the omission of 'detach' was chosen because
      * it worked on our system.
      */
     if(backtrace_command(outb, "dbx %s %d 2>/dev/null <<EOF\n"
                          "where\n"
                          "quit\nEOF\n",
                          globalProgName, (int)getpid()))
         return;
     if(backtrace_command(outb, "gdb -q %s %d 2>/dev/null <<EOF\n"
                          "set prompt\n"
                          "where\n"
                          "detach\n"
                          "quit\n"
                          "EOF\n",
                          globalProgName, (int)getpid()))
         return;
 #elif defined(Q_OS_SOLARIS)
     if(backtrace_command(outb, "dbx %s %d 2>/dev/null <<EOF\n"
                          "where\n"
                          "detach\n"
                          "EOF\n",
                          globalProgName, (int)getpid()))
         return;
     if(backtrace_command(outb, "gdb -q %s %d 2>/dev/null <<EOF\n"
                          "set prompt\n"
                          "where\n"
                          "echo ---\\n\n"
                          "frame 5\n"      /* Skip signal handler frames */
                          "set \\$x = 50\n"
                          "while (\\$x)\n" /* Print local variables for each frame */
                          "info locals\n"
                          "up\n"
                          "set \\$x--\n"
                          "end\n"
                          "echo ---\\n\n"
                          "detach\n"
                          "quit\n"
                          "EOF\n",
                          globalProgName, (int)getpid()))
         return;
     if(backtrace_command(outb, "/usr/proc/bin/pstack %d",
                          (int)getpid()))
         return;
     /*
      * Other Unices (AIX, HPUX, SCO) also have adb, but
      * they seem unable to attach to a running process.)
      */
     if(backtrace_command(outb, "adb %s 2>&1 <<EOF\n"
                          "0t%d:A\n" /* Attach to pid */
                          "\\$c\n"   /* print stacktrace */
                          ":R\n"     /* Detach */
                          "\\$q\n"   /* Quit */
                          "EOF\n",
                          globalProgName, (int)getpid()))
         return;
 #elif defined(Q_OS_INTEGRITY)
     /* abort */
     CheckSuccess(Failure);
 #else /* All other platforms */
     /*
      * TODO: SCO/UnixWare 7 must be something like (not tested)
      *  debug -i c <pid> <<EOF\nstack -f 4\nquit\nEOF\n
      */
 # if !defined(__GNUC__)
     if(backtrace_command(outb, "dbx %s %d 2>/dev/null <<EOF\n"
                          "where\n"
                          "detach\n"
                          "EOF\n",
                          globalProgName, (int)getpid()))
         return;
 # endif
     if(backtrace_command(outb, "gdb -q %s %d 2>/dev/null <<EOF\n"
                          "set prompt\n"
                          "where\n"
 #if 0
                          "echo ---\\n\n"
                          "frame 4\n"
                          "set \\$x = 50\n"
                          "while (\\$x)\n"
                          "info locals\n"
                          "up\n"
                          "set \\$x--\n"
                          "end\n"
                          "echo ---\\n\n"
 #endif
                          "detach\n"
                          "quit\n"
                          "EOF\n",
                          globalProgName, (int)getpid()))
         return;
 #endif
     const char debug_err[] = "No debugger found\n";
     fwrite(debug_err, strlen(debug_err), 1, outb);
 }
qt_signal_handler()
void qt_signal_handler (int sig)
Definition at line 385 of file qcrashhandler.cpp.
 {
     signal(sig, SIG_DFL);
     if(QSegfaultHandler::callback) {
         (*QSegfaultHandler::callback)();
         _exit(1);
     }
     FILE *outb = stderr;
     if(char *crash_loc = ::getenv("QT_CRASH_OUTPUT")) {
         if(FILE *new_outb = fopen(crash_loc, "w")) {
             fprintf(stderr, "Crash (backtrace written to %s)!!!\n", crash_loc);
             outb = new_outb;
         }
     } else {
         fprintf(outb, "Crash!!!\n");
     }
     print_backtrace(outb);
     if(outb != stderr)
         fclose(outb);
     _exit(1);
 }
Variable Documentation
globalProgName
char* globalProgName = NULL static
Definition at line 113 of file qcrashhandler.cpp.