Qt 4.8: /src/gui/kernel/qcursor_mac.mm File Reference
qcursor_mac.mm File Reference
#include <private/qcursor_p.h>
#include <private/qpixmap_mac_p.h>
#include <qapplication.h>
#include <qbitmap.h>
#include <qcursor.h>
#include <qevent.h>
#include <string.h>
#include <unistd.h>
#include <AppKit/NSCursor.h>
#include <qpainter.h>
#include <private/qt_cocoa_helpers_mac_p.h>
#include <private/qapplication_p.h>
Classes
class QMacAnimateCursor
Macros
#define QT_USE_APPROXIMATE_CURSORS
#define QT_USE_APPROXIMATE_CURSORS
Functions
void * qt_mac_nsCursorForQCursor (const QCursor &c)
GrafPtr qt_mac_qd_context (const QPaintDevice *)
Returns the QuickDraw CGrafPtr of the paint device.
void qt_mac_set_cursor (const QCursor *c)
void qt_mac_setMouseGrabCursor (bool set, QCursor *const cursor=0)
void qt_mac_update_cursor ()
void qt_mac_update_cursor_at_global_pos (const QPoint &globalPos)
void qt_mac_updateCursorWithWidgetUnderMouse (QWidget *widgetUnderMouse)
OSWindowRef qt_mac_window_for (const QWidget *)
bool qt_sendSpontaneousEvent (QObject *, QEvent *)
Variables
static QCursorData * currentCursor = 0
static QCursor * grabCursor = 0
static QPointer< QWidget > lastMouseCursorWidget = 0
static QPointer< QWidget > lastWidgetUnderMouse = 0
static int nextCursorId = Qt::BitmapCursor
QPointer< QWidget > qt_button_down
static bool qt_button_down_on_prev_call = false
QCursorData * qt_cursorTable [Qt::LastCursor+1]
Macro Definition Documentation
QT_USE_APPROXIMATE_CURSORS [1/2]
#define QT_USE_APPROXIMATE_CURSORS
QT_USE_APPROXIMATE_CURSORS [2/2]
#define QT_USE_APPROXIMATE_CURSORS
Function Documentation
qt_mac_nsCursorForQCursor()
void* qt_mac_nsCursorForQCursor (const QCursor & c) inline
Definition at line 100 of file qcursor_mac.mm.
Referenced by qt_mac_set_cursor().
 {
     c.d->update();
     return [[static_cast<NSCursor *>(c.d->curs.cp.nscursor) retain] autorelease];
 }
qt_mac_qd_context()
GrafPtr qt_mac_qd_context (const QPaintDevice * device)
Returns the QuickDraw CGrafPtr of the paint device.
Warning
This function is not part of the public interface.
0 is returned if it can't be obtained. Do not hold the pointer around for long as it can be relocated.
Warning
This function is only available on Mac OS X.
Definition at line 91 of file qpaintdevice_mac.cpp.
 {
     if (device->devType() == QInternal::Pixmap) {
         return static_cast<GrafPtr>(static_cast<const QPixmap *>(device)->macQDHandle());
     } else if(device->devType() == QInternal::Widget) {
         return static_cast<GrafPtr>(static_cast<const QWidget *>(device)->macQDHandle());
     } else if(device->devType() == QInternal::Printer) {
         QPaintEngine *engine = static_cast<const QPrinter *>(device)->paintEngine();
         return static_cast<GrafPtr>(static_cast<const QMacPrintEngine *>(engine)->handle());
     }
     return 0;
 }
qt_mac_set_cursor()
void qt_mac_set_cursor (const QCursor * c)
Definition at line 108 of file qcursor_mac.mm.
Referenced by QApplicationPrivate::globalEventProcessor(), qt_mac_mouse_inside_answer_rect(), qt_mac_updateCursorWithWidgetUnderMouse(), QApplication::restoreOverrideCursor(), and QApplication::setOverrideCursor().
 {
 #ifdef QT_MAC_USE_COCOA
     QMacCocoaAutoReleasePool pool;
     [static_cast<NSCursor *>(qt_mac_nsCursorForQCursor(*c)) set];
 #else
     if (!c) {
         currentCursor = 0;
         return;
     }
     c->handle(); //force the cursor to get loaded, if it's not
     if(currentCursor && currentCursor->type == QCursorData::TYPE_ThemeCursor
             && currentCursor->curs.tc.anim)
         currentCursor->curs.tc.anim->stop();
     if(c->d->type == QCursorData::TYPE_ImageCursor) {
         [static_cast<NSCursor *>(c->d->curs.cp.nscursor) set];
     } else if(c->d->type == QCursorData::TYPE_ThemeCursor) {
         if(SetAnimatedThemeCursor(c->d->curs.tc.curs, 0) == themeBadCursorIndexErr) {
             SetThemeCursor(c->d->curs.tc.curs);
         } else {
             if(!c->d->curs.tc.anim)
                 c->d->curs.tc.anim = new QMacAnimateCursor;
             c->d->curs.tc.anim->start(c->d->curs.tc.curs);
         }
     }
     currentCursor = c->d;
 #endif
 }
qt_mac_setMouseGrabCursor()
void qt_mac_setMouseGrabCursor (bool set, QCursor *const cursor = 0)
Definition at line 227 of file qcursor_mac.mm.
Referenced by QWidget::grabMouse(), and QWidget::releaseMouse().
 {
     if (grabCursor) {
         delete grabCursor;
         grabCursor = 0;
     }
     if (set) {
         if (cursor)
             grabCursor = new QCursor(*cursor);
         else if (lastMouseCursorWidget)
             grabCursor = new QCursor(lastMouseCursorWidget->cursor());
         else
             grabCursor = new QCursor(Qt::ArrowCursor);
     }
     qt_mac_update_cursor();
 }
qt_mac_update_cursor()
void qt_mac_update_cursor ()
Definition at line 201 of file qcursor_mac.mm.
Referenced by QApplicationPrivate::globalEventProcessor(), QWidgetPrivate::hide_sys(), onApplicationChangedActivation(), onApplicationWindowChangedActivation(), qt_mac_setMouseGrabCursor(), QApplication::restoreOverrideCursor(), QWidgetPrivate::setCursor_sys(), QApplication::setOverrideCursor(), QWidgetPrivate::show_sys(), and QWidgetPrivate::unsetCursor_sys().
 {
     // This function is similar to qt_mac_updateCursorWithWidgetUnderMouse
     // except that is clears the optimization cache, and finds the widget
     // under mouse itself. Clearing the cache is useful in cases where the
     // application has been deactivated/activated etc.
     // NB: since we dont have any true native widget, the call to
     // qt_mac_getTargetForMouseEvent will fail when the mouse is over QMacNativeWidgets.
 #ifdef QT_MAC_USE_COCOA
     lastWidgetUnderMouse = 0;
     lastMouseCursorWidget = 0;
     QWidget *widgetUnderMouse = 0;
     if (qt_button_down) {
         widgetUnderMouse = qt_button_down;
     } else {
         QPoint localPoint;
         QPoint globalPoint;
         qt_mac_getTargetForMouseEvent(0, QEvent::None, localPoint, globalPoint, 0, &widgetUnderMouse);
     }
     qt_mac_updateCursorWithWidgetUnderMouse(widgetUnderMouse);
 #else
     qt_mac_updateCursorWithWidgetUnderMouse(QApplication::widgetAt(QCursor::pos()));
 #endif
 }
qt_mac_update_cursor_at_global_pos()
void qt_mac_update_cursor_at_global_pos (const QPoint & globalPos)
Definition at line 245 of file qcursor_mac.mm.
 {
     qt_mac_updateCursorWithWidgetUnderMouse(QApplication::widgetAt(globalPos));
 }
qt_mac_updateCursorWithWidgetUnderMouse()
void qt_mac_updateCursorWithWidgetUnderMouse (QWidget * widgetUnderMouse)
Definition at line 144 of file qcursor_mac.mm.
Referenced by flipPoint(), QMacWindowFader::performFade(), qt_mac_update_cursor(), and qt_mac_update_cursor_at_global_pos().
 {
     QCursor cursor(Qt::ArrowCursor);
     if (qt_button_down) {
         // The widget that is currently pressed
         // grabs the mouse cursor:
         widgetUnderMouse = qt_button_down;
         qt_button_down_on_prev_call = true;
     } else if (qt_button_down_on_prev_call) {
         // Grab has been released, so do
         // a full check:
         qt_button_down_on_prev_call = false;
         lastWidgetUnderMouse = 0;
         lastMouseCursorWidget = 0;
     }
     if (QApplication::overrideCursor()) {
         cursor = *QApplication::overrideCursor();
     } else if (grabCursor) {
         cursor = *grabCursor;
     } else if (widgetUnderMouse) {
         if (widgetUnderMouse == lastWidgetUnderMouse) {
             // Optimization that should hit when the widget under
             // the mouse does not change as the mouse moves:
             if (lastMouseCursorWidget)
                 cursor = lastMouseCursorWidget->cursor();
         } else {
             QWidget *w = widgetUnderMouse;
             for (; w; w = w->parentWidget()) {
                 if (w->testAttribute(Qt::WA_SetCursor)) {
                     cursor = w->cursor();
                     break;
                 }
                 if (w->isWindow())
                     break;
             }
             // One final check in case we ran out of parents in the loop:
             if (w && !w->testAttribute(Qt::WA_SetCursor))
                 w = 0;
             lastWidgetUnderMouse = widgetUnderMouse;
             lastMouseCursorWidget = w;
         }
     }
 #ifdef QT_MAC_USE_COCOA
     cursor.d->update();
     NSCursor *nsCursor = static_cast<NSCursor *>(cursor.d->curs.cp.nscursor);
     if ([NSCursor currentCursor] != nsCursor) {
         QMacCocoaAutoReleasePool pool;
         [nsCursor set];
     }
 #else
     qt_mac_set_cursor(&cursor);
 #endif
 }
qt_mac_window_for()
OSWindowRef qt_mac_window_for (const QWidget *)
Definition at line 484 of file qwidget_mac.mm.
 {
     if (OSViewRef hiview = qt_mac_effectiveview_for(w)) {
         OSWindowRef window = qt_mac_window_for(hiview);
         if (window)
             return window;
         if (qt_isGenuineQWidget(hiview)) {
             // This is a workaround for NSToolbar. When a widget is hidden
             // by clicking the toolbar button, Cocoa reparents the widgets
             // to another window (but Qt doesn't know about it).
             // When we start showing them, it reparents back,
             // but at this point it's window is nil, but the window it's being brought
             // into (the Qt one) is for sure created.
             // This stops the hierarchy moving under our feet.
             QWidget *toplevel = w->window();
             if (toplevel != w) {
                 hiview = qt_mac_nativeview_for(toplevel);
                 if (OSWindowRef w = qt_mac_window_for(hiview))
                     return w;
             }
             toplevel->d_func()->createWindow_sys();
             // Reget the hiview since "create window" could potentially move the view (I guess).
             hiview = qt_mac_nativeview_for(toplevel);
             return qt_mac_window_for(hiview);
         }
     }
     return 0;
 }
qt_sendSpontaneousEvent()
bool qt_sendSpontaneousEvent (QObject * , QEvent *)
Definition at line 5779 of file qapplication.cpp.
Referenced by QCursor::setPos().
 {
     return QCoreApplication::sendSpontaneousEvent(receiver, event);
 }
Variable Documentation
currentCursor
QCursorData* currentCursor = 0 static
Definition at line 106 of file qcursor_mac.mm.
Referenced by QtWndProc().
grabCursor
QCursor* grabCursor = 0 static
Definition at line 142 of file qcursor_mac.mm.
Referenced by qt_mac_setMouseGrabCursor(), and qt_mac_updateCursorWithWidgetUnderMouse().
lastMouseCursorWidget
QPointer<QWidget> lastMouseCursorWidget = 0 static
Definition at line 140 of file qcursor_mac.mm.
lastWidgetUnderMouse
QPointer<QWidget> lastWidgetUnderMouse = 0 static
Definition at line 139 of file qcursor_mac.mm.
nextCursorId
int nextCursorId = Qt::BitmapCursor static
Definition at line 251 of file qcursor_mac.mm.
Referenced by QCursorData::setBitmap().
qt_button_down
QPointer<QWidget> qt_button_down
Definition at line 188 of file qapplication_mac.mm.
Referenced by qt_mac_update_cursor(), and qt_mac_updateCursorWithWidgetUnderMouse().
qt_button_down_on_prev_call
bool qt_button_down_on_prev_call = false static
Definition at line 141 of file qcursor_mac.mm.
Referenced by qt_mac_updateCursorWithWidgetUnderMouse().
qt_cursorTable
QCursorData* qt_cursorTable[Qt::LastCursor+1]
Definition at line 398 of file qcursor.cpp.
Referenced by QCursorData::setBitmap().