Qt 4.8: /src/gui/widgets/qdatetimeedit.cpp File Reference
qdatetimeedit.cpp File Reference
#include <math.h>
#include <private/qdatetimeedit_p.h>
#include <qabstractspinbox.h>
#include <qapplication.h>
#include <qdatetimeedit.h>
#include <qdesktopwidget.h>
#include <qdebug.h>
#include <qevent.h>
#include <qlineedit.h>
#include <private/qlineedit_p.h>
#include <qlocale.h>
#include <qpainter.h>
#include <qlayout.h>
#include <qset.h>
#include <qstyle.h>
#include "moc_qdatetimeedit.cpp"
Macros
#define QDTEDEBUG if (false) qDebug()
#define QDTEDEBUGN if (false) qDebug
Functions
template<typename C >
static C reverse (const C &l)
Macro Definition Documentation
QDTEDEBUG
#define QDTEDEBUG if (false) qDebug()
Definition at line 65 of file qdatetimeedit.cpp.
Referenced by QDateTimeEditPrivate::_q_editorCursorPositionChanged(), QDateTimeEditPrivate::clearSection(), QDateTimeEdit::focusNextPrevChild(), QDateTimeEdit::keyPressEvent(), QDateTimeEdit::setCurrentSection(), and QDateTimeEditPrivate::updateEdit().
QDTEDEBUGN
#define QDTEDEBUGN if (false) qDebug
Definition at line 66 of file qdatetimeedit.cpp.
Function Documentation
reverse()
template<typename C > static C reverse (const C & l) inline static
Definition at line 928 of file qdatetimeedit.cpp.
Referenced by QTextLine::cursorToX(), QGridLayoutPrivate::distribute(), QTreeView::drawBranches(), QWindowsCEStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), QCommonStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QStyleSheetStyle::drawControl(), QPlastiqueStylePrivate::drawPartialFrame(), QCommonStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QStyleSheetStyle::drawPrimitive(), QTreeView::drawRow(), QToolBarAreaLayoutInfo::fitLayout(), QAudioOutputPrivate::freeBlocks(), QDialogButtonBoxPrivate::layoutButtons(), QColumnViewDelegate::paint(), QPatternist::XPath20CoreFunctions::retrieveExpression(), QHeaderViewPrivate::sectionHandleAt(), QDateTimeEdit::setDisplayFormat(), QBoxLayout::setGeometry(), QDeclarativeAnimationPropertyUpdater::setValue(), QDeclarativeParentAnimation::transition(), and QTableView::updateGeometries().
 {
     C ret;
     for (int i=l.size() - 1; i>=0; --i)
         ret.append(l.at(i));
     return ret;
 }