Qt 4.8: /src/corelib/tools/qdatetime.cpp File Reference
qdatetime.cpp File Reference
#include "qplatformdefs.h"
#include "private/qdatetime_p.h"
#include "qdatastream.h"
#include "qset.h"
#include "qlocale.h"
#include "qdatetime.h"
#include "qregexp.h"
#include "qdebug.h"
#include <qt_windows.h>
#include <time.h>
#include "qfunctions_wince.h"
#include <private/qcore_mac_p.h>
Macros
#define QDTPDEBUG if (false) qDebug()
#define QDTPDEBUGN if (false) qDebug
Enumerations
enum {
FIRST_YEAR = -4713, FIRST_MONTH = 1, FIRST_DAY = 2, SECS_PER_DAY = 86400,
MSECS_PER_DAY = 86400000, SECS_PER_HOUR = 3600, MSECS_PER_HOUR = 3600000, SECS_PER_MIN = 60,
MSECS_PER_MIN = 60000, JULIAN_DAY_FOR_EPOCH = 2440588
}
Functions
static QDate adjustDate (QDate date)
static void appendSeparator (QStringList *list, const QString &string, int from, int size, int lastQuote)
static int countRepeat (const QString &str, int index, int maxCount)
Parses the format newFormat.
static QDate fixedDate (int y, int m, int d)
static QString fmtDateTime (const QString &f, const QTime *dt=0, const QDate *dd=0)
static int fromShortMonthName (const QString &monthName)
static void getDateFromJulianDay (uint julianDay, int *year, int *month, int *day)
static QString getFmtString (const QString &f, const QTime *dt=0, const QDate *dd=0, bool am_pm=false)
static bool hasUnquotedAP (const QString &f)
static uint julianDayFromDate (int year, int month, int day)
static uint julianDayFromGregorianDate (int year, int month, int day)
static void localToUtc (QDate &date, QTime &time, int isdst)
static uint msecsFromDecomposed (int hour, int minute, int sec, int msec=0)
QDebug operator<< (QDebug dbg, const QDate &date)
QDebug operator<< (QDebug dbg, const QTime &time)
QDebug operator<< (QDebug dbg, const QDateTime &date)
bool operator== (const QDateTimeParser::SectionNode &s1, const QDateTimeParser::SectionNode &s2)
qint64 toMSecsSinceEpoch_helper (qint64 jd, int msecs)
static QString unquote (const QString &str)
static QDateTimePrivate::Spec utcToLocal (QDate &date, QTime &time)
Variables
static const int LowerYear = 1980
static const char monthDays [] = { 0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 }
static const char *const qt_shortMonthNames []
static const int UpperYear = 2037
Macro Definition Documentation
QDTPDEBUG
#define QDTPDEBUG if (false) qDebug()
Definition at line 68 of file qdatetime.cpp.
Referenced by QDateTimeParser::findAmPm(), QDateTimeParser::findMonth(), QDateTimeParser::parse(), QDateTimeParser::parseFormat(), and QDateTimeParser::parseSection().
QDTPDEBUGN
#define QDTPDEBUGN if (false) qDebug
Definition at line 69 of file qdatetime.cpp.
Referenced by QDateTimeParser::parse(), QDateTimeParser::parseFormat(), and QDateTimeParser::parseSection().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FIRST_YEAR
FIRST_MONTH
FIRST_DAY
SECS_PER_DAY
MSECS_PER_DAY
SECS_PER_HOUR
MSECS_PER_HOUR
SECS_PER_MIN
MSECS_PER_MIN
JULIAN_DAY_FOR_EPOCH
Definition at line 83 of file qdatetime.cpp.
      {
     FIRST_YEAR = -4713,
     FIRST_MONTH = 1,
     FIRST_DAY = 2,  // ### Qt 5: make FIRST_DAY = 1, by support jd == 0 as valid
     SECS_PER_DAY = 86400,
     MSECS_PER_DAY = 86400000,
     SECS_PER_HOUR = 3600,
     MSECS_PER_HOUR = 3600000,
     SECS_PER_MIN = 60,
     MSECS_PER_MIN = 60000,
     JULIAN_DAY_FOR_EPOCH = 2440588 // result of julianDayFromGregorianDate(1970, 1, 1)
 };
Function Documentation
adjustDate()
static QDate adjustDate (QDate date) static
Definition at line 4205 of file qdatetime.cpp.
Referenced by localToUtc(), and utcToLocal().
 {
     QDate lowerLimit(LowerYear, 1, 2);
     QDate upperLimit(UpperYear, 12, 30);
     if (date > lowerLimit && date < upperLimit)
         return date;
     int month = date.month();
     int day = date.day();
     // neither 1970 nor 2037 are leap years, so make sure date isn't Feb 29
     if (month == 2 && day == 29)
         --day;
     if (date < lowerLimit)
         date.setDate(LowerYear, month, day);
     else
         date.setDate(UpperYear, month, day);
     return date;
 }
appendSeparator()
static void appendSeparator (QStringList * list, const QString & string, int from, int size, int lastQuote) inline static
Definition at line 4760 of file qdatetime.cpp.
Referenced by QDateTimeParser::parseFormat().
 {
     QString str(string.mid(from, size));
     if (lastQuote >= from)
         str = unquote(str);
     list->append(str);
 }
countRepeat()
static int countRepeat (const QString & str, int index, int maxCount) inline static
Parses the format newFormat.
Warning
This function is not part of the public interface.
If successful, returns true and sets up the format. Else keeps the old format and returns false.
Definition at line 4749 of file qdatetime.cpp.
Referenced by QDateTimeParser::parseFormat().
 {
     int count = 1;
     const QChar ch(str.at(index));
     const int max = qMin(index + maxCount, str.size());
     while (index + count < max && str.at(index + count) == ch) {
         ++count;
     }
     return count;
 }
fixedDate()
static QDate fixedDate (int y, int m, int d) inline static
Definition at line 96 of file qdatetime.cpp.
Referenced by QDate::addMonths(), and QDate::addYears().
 {
     QDate result(y, m, 1);
     result.setDate(y, m, qMin(d, result.daysInMonth()));
     return result;
 }
fmtDateTime()
static QString fmtDateTime (const QString & f, const QTime * dt = 0, const QDate * dd = 0) static
Definition at line 4133 of file qdatetime.cpp.
Referenced by QDate::toString(), QTime::toString(), and QDateTime::toString().
 {
     const QLatin1Char quote('\'');
     if (f.isEmpty())
         return QString();
     if (dt && !dt->isValid())
         return QString();
     if (dd && !dd->isValid())
         return QString();
     const bool ap = hasUnquotedAP(f);
     QString buf;
     QString frm;
     QChar status(QLatin1Char('0'));
     for (int i = 0; i < (int)f.length(); ++i) {
         if (f.at(i) == quote) {
             if (status == quote) {
                 if (i > 0 && f.at(i - 1) == quote)
                     buf += QLatin1Char('\'');
                 status = QLatin1Char('0');
             } else {
                 if (!frm.isEmpty()) {
                     buf += getFmtString(frm, dt, dd, ap);
                     frm.clear();
                 }
                 status = quote;
             }
         } else if (status == quote) {
             buf += f.at(i);
         } else if (f.at(i) == status) {
             if ((ap) && ((f.at(i) == QLatin1Char('P')) || (f.at(i) == QLatin1Char('p'))))
                 status = QLatin1Char('0');
             frm += f.at(i);
         } else {
             buf += getFmtString(frm, dt, dd, ap);
             frm.clear();
             if ((f.at(i) == QLatin1Char('h')) || (f.at(i) == QLatin1Char('m'))
                 || (f.at(i) == QLatin1Char('H'))
                 || (f.at(i) == QLatin1Char('s')) || (f.at(i) == QLatin1Char('z'))) {
                 status = f.at(i);
                 frm += f.at(i);
             } else if ((f.at(i) == QLatin1Char('d')) || (f.at(i) == QLatin1Char('M')) || (f.at(i) == QLatin1Char('y'))) {
                 status = f.at(i);
                 frm += f.at(i);
             } else if ((ap) && (f.at(i) == QLatin1Char('A'))) {
                 status = QLatin1Char('P');
                 frm += f.at(i);
             } else  if((ap) && (f.at(i) == QLatin1Char('a'))) {
                 status = QLatin1Char('p');
                 frm += f.at(i);
             } else {
                 buf += f.at(i);
                 status = QLatin1Char('0');
             }
         }
     }
     buf += getFmtString(frm, dt, dd, ap);
     return buf;
 }
fromShortMonthName()
static int fromShortMonthName (const QString & monthName) static
Definition at line 3459 of file qdatetime.cpp.
Referenced by QDateTime::fromString().
 {
     // Assume that English monthnames are the default
     for (int i = 0; i < 12; ++i) {
         if (monthName == QLatin1String(qt_shortMonthNames[i]))
             return i + 1;
     }
     // If English names can't be found, search the localized ones
     for (int i = 1; i <= 12; ++i) {
         if (monthName == QDate::shortMonthName(i))
             return i;
     }
     return -1;
 }
getDateFromJulianDay()
static void getDateFromJulianDay (uint julianDay, int * year, int * month, int * day) static
Definition at line 133 of file qdatetime.cpp.
Referenced by QDate::addMonths(), QDate::addYears(), QDate::day(), QDate::daysInMonth(), QDate::daysInYear(), QDate::getDate(), QDate::julianToGregorian(), QDate::month(), QDateTimeParser::parse(), QDate::toString(), and QDate::year().
 {
     int y, m, d;
     if (julianDay >= 2299161) {
         // Gregorian calendar starting from October 15, 1582
         // This algorithm is from Henry F. Fliegel and Thomas C. Van Flandern
         qulonglong ell, n, i, j;
         ell = qulonglong(julianDay) + 68569;
         n = (4 * ell) / 146097;
         ell = ell - (146097 * n + 3) / 4;
         i = (4000 * (ell + 1)) / 1461001;
         ell = ell - (1461 * i) / 4 + 31;
         j = (80 * ell) / 2447;
         d = ell - (2447 * j) / 80;
         ell = j / 11;
         m = j + 2 - (12 * ell);
         y = 100 * (n - 49) + i + ell;
     } else {
         // Julian calendar until October 4, 1582
         // Algorithm from Frequently Asked Questions about Calendars by Claus Toendering
         julianDay += 32082;
         int dd = (4 * julianDay + 3) / 1461;
         int ee = julianDay - (1461 * dd) / 4;
         int mm = ((5 * ee) + 2) / 153;
         d = ee - (153 * mm + 2) / 5 + 1;
         m = mm + 3 - 12 * (mm / 10);
         y = dd - 4800 + (mm / 10);
         if (y <= 0)
             --y;
     }
     if (year)
         *year = y;
     if (month)
         *month = m;
     if (day)
         *day = d;
 }
getFmtString()
static QString getFmtString (const QString & f, const QTime * dt = 0, const QDate * dd = 0, bool am_pm = false) static
Definition at line 4026 of file qdatetime.cpp.
Referenced by fmtDateTime().
 {
     if (f.isEmpty())
         return QString();
     QString buf = f;
     int removed = 0;
     if (dt) {
         if (f.startsWith(QLatin1String("hh")) || f.startsWith(QLatin1String("HH"))) {
             const bool hour12 = f.at(0) == QLatin1Char('h') && am_pm;
             if (hour12 && dt->hour() > 12)
                 buf = QString::number(dt->hour() - 12).rightJustified(2, QLatin1Char('0'), true);
             else if (hour12 && dt->hour() == 0)
                 buf = QLatin1String("12");
             else
                 buf = QString::number(dt->hour()).rightJustified(2, QLatin1Char('0'), true);
             removed = 2;
         } else if (f.at(0) == QLatin1Char('h') || f.at(0) == QLatin1Char('H')) {
             const bool hour12 = f.at(0) == QLatin1Char('h') && am_pm;
             if (hour12 && dt->hour() > 12)
                 buf = QString::number(dt->hour() - 12);
             else if (hour12 && dt->hour() == 0)
                 buf = QLatin1String("12");
             else
                 buf = QString::number(dt->hour());
             removed = 1;
         } else if (f.startsWith(QLatin1String("mm"))) {
             buf = QString::number(dt->minute()).rightJustified(2, QLatin1Char('0'), true);
             removed = 2;
         } else if (f.at(0) == (QLatin1Char('m'))) {
             buf = QString::number(dt->minute());
             removed = 1;
         } else if (f.startsWith(QLatin1String("ss"))) {
             buf = QString::number(dt->second()).rightJustified(2, QLatin1Char('0'), true);
             removed = 2;
         } else if (f.at(0) == QLatin1Char('s')) {
             buf = QString::number(dt->second());
         } else if (f.startsWith(QLatin1String("zzz"))) {
             buf = QString::number(dt->msec()).rightJustified(3, QLatin1Char('0'), true);
             removed = 3;
         } else if (f.at(0) == QLatin1Char('z')) {
             buf = QString::number(dt->msec());
             removed = 1;
         } else if (f.at(0).toUpper() == QLatin1Char('A')) {
             const bool upper = f.at(0) == QLatin1Char('A');
             buf = dt->hour() < 12 ? QLatin1String("am") : QLatin1String("pm");
             if (upper)
                 buf = buf.toUpper();
             if (f.size() > 1 && f.at(1).toUpper() == QLatin1Char('P') &&
                 f.at(0).isUpper() == f.at(1).isUpper()) {
                 removed = 2;
             } else {
                 removed = 1;
             }
         }
     }
     if (dd) {
         if (f.startsWith(QLatin1String("dddd"))) {
             buf = dd->longDayName(dd->dayOfWeek());
             removed = 4;
         } else if (f.startsWith(QLatin1String("ddd"))) {
             buf = dd->shortDayName(dd->dayOfWeek());
             removed = 3;
         } else if (f.startsWith(QLatin1String("dd"))) {
             buf = QString::number(dd->day()).rightJustified(2, QLatin1Char('0'), true);
             removed = 2;
         } else if (f.at(0) == QLatin1Char('d')) {
             buf = QString::number(dd->day());
             removed = 1;
         } else if (f.startsWith(QLatin1String("MMMM"))) {
             buf = dd->longMonthName(dd->month());
             removed = 4;
         } else if (f.startsWith(QLatin1String("MMM"))) {
             buf = dd->shortMonthName(dd->month());
             removed = 3;
         } else if (f.startsWith(QLatin1String("MM"))) {
             buf = QString::number(dd->month()).rightJustified(2, QLatin1Char('0'), true);
             removed = 2;
         } else if (f.at(0) == QLatin1Char('M')) {
             buf = QString::number(dd->month());
             removed = 1;
         } else if (f.startsWith(QLatin1String("yyyy"))) {
             const int year = dd->year();
             buf = QString::number(qAbs(year)).rightJustified(4, QLatin1Char('0'));
             if(year > 0)
                 removed = 4;
             else
             {
                 buf.prepend(QLatin1Char('-'));
                 removed = 5;
             }
         } else if (f.startsWith(QLatin1String("yy"))) {
             buf = QString::number(dd->year()).right(2).rightJustified(2, QLatin1Char('0'));
             removed = 2;
         }
     }
     if (removed == 0 || removed >= f.size()) {
         return buf;
     }
     return buf + getFmtString(f.mid(removed), dt, dd, am_pm);
 }
hasUnquotedAP()
static bool hasUnquotedAP (const QString & f) static
Definition at line 4005 of file qdatetime.cpp.
Referenced by fmtDateTime().
 {
     const QLatin1Char quote('\'');
     bool inquote = false;
     const int max = f.size();
     for (int i=0; i<max; ++i) {
         if (f.at(i) == quote) {
             inquote = !inquote;
         } else if (!inquote && f.at(i).toUpper() == QLatin1Char('A')) {
             return true;
         }
     }
     return false;
 }
julianDayFromDate()
static uint julianDayFromDate (int year, int month, int day) static
Definition at line 113 of file qdatetime.cpp.
Referenced by QDate::currentDate(), QDateTime::currentDateTime(), QDateTime::currentDateTimeUtc(), QDateTime::currentMSecsSinceEpoch(), QDate::dayOfYear(), QDate::gregorianToJulian(), and QDate::setDate().
 {
     if (year < 0)
         ++year;
     if (year > 1582 || (year == 1582 && (month > 10 || (month == 10 && day >= 15)))) {
         return julianDayFromGregorianDate(year, month, day);
     } else if (year < 1582 || (year == 1582 && (month < 10 || (month == 10 && day <= 4)))) {
         // Julian calendar until October 4, 1582
         // Algorithm from Frequently Asked Questions about Calendars by Claus Toendering
         int a = (14 - month) / 12;
         return (153 * (month + (12 * a) - 3) + 2) / 5
                + (1461 * (year + 4800 - a)) / 4
                + day - 32083;
     } else {
         // the day following October 4, 1582 is October 15, 1582
         return 0;
     }
 }
julianDayFromGregorianDate()
static uint julianDayFromGregorianDate (int year, int month, int day) inline static
Definition at line 103 of file qdatetime.cpp.
Referenced by QDateTime::currentMSecsSinceEpoch(), and julianDayFromDate().
 {
     // Gregorian calendar starting from October 15, 1582
     // Algorithm from Henry F. Fliegel and Thomas C. Van Flandern
     return (1461 * (year + 4800 + (month - 14) / 12)) / 4
            + (367 * (month - 2 - 12 * ((month - 14) / 12))) / 12
            - (3 * ((year + 4900 + (month - 14) / 12) / 100)) / 4
            + day - 32075;
 }
localToUtc()
static void localToUtc (QDate & date, QTime & time, int isdst) static
Definition at line 4316 of file qdatetime.cpp.
Referenced by QDateTimePrivate::getUTC().
 {
     if (!date.isValid())
         return;
     QDate fakeDate = adjustDate(date);
     tm localTM;
     localTM.tm_sec = time.second();
     localTM.tm_min = time.minute();
     localTM.tm_hour = time.hour();
     localTM.tm_mday = fakeDate.day();
     localTM.tm_mon = fakeDate.month() - 1;
     localTM.tm_year = fakeDate.year() - 1900;
     localTM.tm_isdst = (int)isdst;
 #if defined(Q_OS_WINCE) || defined(Q_OS_SYMBIAN)
     time_t secsSince1Jan1970UTC = (toMSecsSinceEpoch_helper(fakeDate.toJulianDay(), QTime().msecsTo(time)) / 1000);
 #else
 #if defined(Q_OS_WIN)
     _tzset();
 #endif
     time_t secsSince1Jan1970UTC = mktime(&localTM);
 #ifdef Q_OS_QNX
     //mktime sometimes fails on QNX. Following workaround converts the date and time then manually
     if (secsSince1Jan1970UTC == (time_t)-1) {
         QDateTime tempTime = QDateTime(date, time, Qt::UTC);;
         tempTime = tempTime.addMSecs(timezone * 1000);
         date = tempTime.date();
         time = tempTime.time();
         return;
     }
 #endif
 #endif
     tm *brokenDown = 0;
 #if defined(Q_OS_WINCE)
     tm res;
     FILETIME localTime = time_tToFt(secsSince1Jan1970UTC);
     SYSTEMTIME sysTime;
     FileTimeToSystemTime(&localTime, &sysTime);
     FILETIME resultTime;
     LocalFileTimeToFileTime(&localTime , &resultTime);
     FileTimeToSystemTime(&resultTime , &sysTime);
     res.tm_sec = sysTime.wSecond;
     res.tm_min = sysTime.wMinute;
     res.tm_hour = sysTime.wHour;
     res.tm_mday = sysTime.wDay;
     res.tm_mon = sysTime.wMonth - 1;
     res.tm_year = sysTime.wYear - 1900;
     res.tm_isdst = (int)isdst;
     brokenDown = &res;
 #elif defined(Q_OS_SYMBIAN)
     // months and days are zero index based
     _LIT(KUnixEpoch, "19700000:000000.000000");
     TTimeIntervalSeconds tTimeIntervalSecsSince1Jan1970UTC(secsSince1Jan1970UTC);
     TTime epochTTime;
     TInt err = epochTTime.Set(KUnixEpoch);
     tm res;
     if(err == KErrNone) {
         TTime localTTime = epochTTime + tTimeIntervalSecsSince1Jan1970UTC;
         RTz tz;
         if (KErrNone == tz.Connect()) {
             if (KErrNone == tz.ConvertToUniversalTime(localTTime)) {
                 TDateTime utcDateTime = localTTime.DateTime();
                 res.tm_sec = utcDateTime.Second();
                 res.tm_min = utcDateTime.Minute();
                 res.tm_hour = utcDateTime.Hour();
                 res.tm_mday = utcDateTime.Day() + 1; // non-zero based index for tm struct
                 res.tm_mon = utcDateTime.Month();
                 res.tm_year = utcDateTime.Year() - 1900;
                 res.tm_isdst = (int)isdst;
                 brokenDown = &res;
             }
         tz.Close();
         }
     }
 #elif !defined(QT_NO_THREAD) && defined(_POSIX_THREAD_SAFE_FUNCTIONS)
     // use the reentrant version of gmtime() where available
     tm res;
     brokenDown = gmtime_r(&secsSince1Jan1970UTC, &res);
 #elif defined(_MSC_VER) && _MSC_VER >= 1400
     tm res;
     if (!_gmtime64_s(&res, &secsSince1Jan1970UTC))
         brokenDown = &res;
 #else
     brokenDown = gmtime(&secsSince1Jan1970UTC);
 #endif // !QT_NO_THREAD && _POSIX_THREAD_SAFE_FUNCTIONS
     if (!brokenDown) {
         date = QDate(1970, 1, 1);
         time = QTime();
     } else {
         int deltaDays = fakeDate.daysTo(date);
         date = QDate(brokenDown->tm_year + 1900, brokenDown->tm_mon + 1, brokenDown->tm_mday);
         time = QTime(brokenDown->tm_hour, brokenDown->tm_min, brokenDown->tm_sec, time.msec());
         date = date.addDays(deltaDays);
     }
 }
msecsFromDecomposed()
static uint msecsFromDecomposed (int hour, int minute, int sec, int msec = 0) inline static
Definition at line 3109 of file qdatetime.cpp.
Referenced by QDateTime::currentDateTime(), QDateTime::currentDateTimeUtc(), QDateTime::currentMSecsSinceEpoch(), and QTime::currentTime().
 {
     return MSECS_PER_HOUR * hour + MSECS_PER_MIN * minute + 1000 * sec + msec;
 }
operator<<() [1/3]
QDebug operator<< (QDebug dbg, const QDate & date)
Definition at line 4436 of file qdatetime.cpp.
 {
     dbg.nospace() << "QDate(" << date.toString() << ')';
     return dbg.space();
 }
operator<<() [2/3]
QDebug operator<< (QDebug dbg, const QTime & time)
Definition at line 4442 of file qdatetime.cpp.
 {
     dbg.nospace() << "QTime(" << time.toString() << ')';
     return dbg.space();
 }
operator<<() [3/3]
QDebug operator<< (QDebug dbg, const QDateTime & date)
Definition at line 4448 of file qdatetime.cpp.
 {
     dbg.nospace() << "QDateTime(" << date.toString() << ')';
     return dbg.space();
 }
operator==()
bool operator== (const QDateTimeParser::SectionNode & s1, const QDateTimeParser::SectionNode & s2)
Definition at line 6137 of file qdatetime.cpp.
 {
     return (s1.type == s2.type) && (s1.pos == s2.pos) && (s1.count == s2.count);
 }
toMSecsSinceEpoch_helper()
qint64 toMSecsSinceEpoch_helper (qint64 jd, int msecs)
Definition at line 2449 of file qdatetime.cpp.
Referenced by localToUtc(), QDateTime::toMSecsSinceEpoch(), and utcToLocal().
 {
     qint64 days = jd - JULIAN_DAY_FOR_EPOCH;
     qint64 retval = (days * MSECS_PER_DAY) + msecs;
     return retval;
 }
unquote()
static QString unquote (const QString & str) static
Warning
This function is not part of the public interface. helper function for parseFormat. removes quotes that are not escaped and removes the escaping on those that are escaped
Definition at line 4715 of file qdatetime.cpp.
Referenced by appendSeparator(), and QDateTimeParser::parseFormat().
 {
     const QChar quote(QLatin1Char('\''));
     const QChar slash(QLatin1Char('\\'));
     const QChar zero(QLatin1Char('0'));
     QString ret;
     QChar status(zero);
     const int max = str.size();
     for (int i=0; i<max; ++i) {
         if (str.at(i) == quote) {
             if (status != quote) {
                 status = quote;
             } else if (!ret.isEmpty() && str.at(i - 1) == slash) {
                 ret[ret.size() - 1] = quote;
             } else {
                 status = zero;
             }
         } else {
             ret += str.at(i);
         }
     }
     return ret;
 }
utcToLocal()
static QDateTimePrivate::Spec utcToLocal (QDate & date, QTime & time) static
Definition at line 4228 of file qdatetime.cpp.
Referenced by QDateTimePrivate::getLocal().
 {
     QDate fakeDate = adjustDate(date);
     // won't overflow because of fakeDate
     time_t secsSince1Jan1970UTC = toMSecsSinceEpoch_helper(fakeDate.toJulianDay(), QTime().msecsTo(time)) / 1000;
     tm *brokenDown = 0;
 #if defined(Q_OS_WINCE)
     tm res;
     FILETIME utcTime = time_tToFt(secsSince1Jan1970UTC);
     FILETIME resultTime;
     FileTimeToLocalFileTime(&utcTime , &resultTime);
     SYSTEMTIME sysTime;
     FileTimeToSystemTime(&resultTime , &sysTime);
     res.tm_sec = sysTime.wSecond;
     res.tm_min = sysTime.wMinute;
     res.tm_hour = sysTime.wHour;
     res.tm_mday = sysTime.wDay;
     res.tm_mon = sysTime.wMonth - 1;
     res.tm_year = sysTime.wYear - 1900;
     brokenDown = &res;
 #elif defined(Q_OS_SYMBIAN)
     // months and days are zero index based
     _LIT(KUnixEpoch, "19700000:000000.000000");
     TTimeIntervalSeconds tTimeIntervalSecsSince1Jan1970UTC(secsSince1Jan1970UTC);
     TTime epochTTime;
     TInt err = epochTTime.Set(KUnixEpoch);
     tm res;
     if(err == KErrNone) {
         TTime utcTTime = epochTTime + tTimeIntervalSecsSince1Jan1970UTC;
         CTrapCleanup *cleanup = CTrapCleanup::New();    // needed to avoid crashes in apps that previously were able to use this function in static data initialization
         TRAP(err,
             RTz tz;
             User::LeaveIfError(tz.Connect());
             CleanupClosePushL(tz);
             CTzId *tzId = tz.GetTimeZoneIdL();
             CleanupStack::PushL(tzId);
             res.tm_isdst = tz.IsDaylightSavingOnL(*tzId,utcTTime);
             User::LeaveIfError(tz.ConvertToLocalTime(utcTTime));
             CleanupStack::PopAndDestroy(tzId);
             CleanupStack::PopAndDestroy(&tz));
         delete cleanup;
         if (KErrNone == err) {
             TDateTime localDateTime = utcTTime.DateTime();
             res.tm_sec = localDateTime.Second();
             res.tm_min = localDateTime.Minute();
             res.tm_hour = localDateTime.Hour();
             res.tm_mday = localDateTime.Day() + 1; // non-zero based index for tm struct
             res.tm_mon = localDateTime.Month();
             res.tm_year = localDateTime.Year() - 1900;
             // Symbian's timezone server doesn't know how to handle DST before year 1997
             if (res.tm_year < 97)
                 res.tm_isdst = -1;
             brokenDown = &res;
         }
     }
 #elif !defined(QT_NO_THREAD) && defined(_POSIX_THREAD_SAFE_FUNCTIONS)
     // use the reentrant version of localtime() where available
     tzset();
     tm res;
     brokenDown = localtime_r(&secsSince1Jan1970UTC, &res);
 #elif defined(_MSC_VER) && _MSC_VER >= 1400
     tm res;
     if (!_localtime64_s(&res, &secsSince1Jan1970UTC))
         brokenDown = &res;
 #else
     brokenDown = localtime(&secsSince1Jan1970UTC);
 #endif
     if (!brokenDown) {
         date = QDate(1970, 1, 1);
         time = QTime();
         return QDateTimePrivate::LocalUnknown;
     } else {
         int deltaDays = fakeDate.daysTo(date);
         date = QDate(brokenDown->tm_year + 1900, brokenDown->tm_mon + 1, brokenDown->tm_mday);
         time = QTime(brokenDown->tm_hour, brokenDown->tm_min, brokenDown->tm_sec, time.msec());
         date = date.addDays(deltaDays);
         if (brokenDown->tm_isdst > 0)
             return QDateTimePrivate::LocalDST;
         else if (brokenDown->tm_isdst < 0)
             return QDateTimePrivate::LocalUnknown;
         else
             return QDateTimePrivate::LocalStandard;
     }
 }
Variable Documentation
LowerYear
const int LowerYear = 1980 static
Definition at line 4199 of file qdatetime.cpp.
Referenced by adjustDate().
monthDays
const char monthDays[] = { 0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 } static
Definition at line 173 of file qdatetime.cpp.
Referenced by QDate::daysInMonth(), and QDate::isValid().
qt_shortMonthNames
const char* const qt_shortMonthNames[] static
Initial value:
= {
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }
Definition at line 176 of file qdatetime.cpp.
Referenced by fromShortMonthName(), and QDate::fromString().
UpperYear
const int UpperYear = 2037 static
Definition at line 4203 of file qdatetime.cpp.
Referenced by adjustDate().