Qt 4.8: /src/dbus/qdbusconnection_p.h File Reference
qdbusconnection_p.h File Reference
#include <qdbuserror.h>
#include <qdbusconnection.h>
#include <QtCore/qatomic.h>
#include <QtCore/qhash.h>
#include <QtCore/qmutex.h>
#include <QtCore/qobject.h>
#include <QtCore/qpointer.h>
#include <QtCore/qreadwritelock.h>
#include <QtCore/qstringlist.h>
#include <QtCore/qvarlengtharray.h>
#include <QtCore/qvector.h>
#include "qdbus_symbols_p.h"
#include <qdbusmessage.h>
Classes
class QDBusConnectionPrivate
struct QDBusConnectionPrivate::ObjectTreeNode
struct QDBusConnectionPrivate::SignalHook
struct QDBusConnectionPrivate::WatchedServiceData
struct QDBusConnectionPrivate::Watcher
class QDBusErrorInternal
Functions
bool qDBusCheckAsyncTag (const char *tag)
QString qDBusInterfaceFromMetaObject (const QMetaObject *mo)
bool qDBusInterfaceInObject (QObject *obj, const QString &interface_name)
QString qDBusIntrospectObject (const QDBusConnectionPrivate::ObjectTreeNode &node, const QString &path)
int qDBusNameToTypeId (const char *name)
int qDBusParametersForMethod (const QMetaMethod &mm, QList< int > &metaTypes)
QDBusMessage qDBusPropertyGet (const QDBusConnectionPrivate::ObjectTreeNode &node, const QDBusMessage &msg)
QDBusMessage qDBusPropertyGetAll (const QDBusConnectionPrivate::ObjectTreeNode &node, const QDBusMessage &msg)
QDBusMessage qDBusPropertySet (const QDBusConnectionPrivate::ObjectTreeNode &node, const QDBusMessage &msg)
Function Documentation
qDBusCheckAsyncTag()
bool qDBusCheckAsyncTag (const char * tag)
Definition at line 57 of file qdbusmisc.cpp.
Referenced by findSlot(), and generateInterfaceXml().
 {
     static const char noReplyTag[] = "Q_NOREPLY";
     if (!tag || !*tag)
         return false;
     const char *p = strstr(tag, noReplyTag);
     if (p != NULL &&
         (p == tag || *(p-1) == ' ') &&
         (p[sizeof noReplyTag - 1] == '\0' || p[sizeof noReplyTag - 1] == ' '))
         return true;
     return false;
 }
qDBusInterfaceFromMetaObject()
QString qDBusInterfaceFromMetaObject (const QMetaObject * mo)
Definition at line 80 of file qdbusmisc.cpp.
Referenced by qDBusGenerateMetaObjectXml(), and qDBusInterfaceInObject().
 {
     QString interface;
     int idx = mo->indexOfClassInfo(QCLASSINFO_DBUS_INTERFACE);
     if (idx >= mo->classInfoOffset()) {
         interface = QLatin1String(mo->classInfo(idx).value());
     } else {
         interface = QLatin1String(mo->className());
         interface.replace(QLatin1String("::"), QLatin1String("."));
         if (interface.startsWith(QLatin1String("QDBus"))) {
             interface.prepend(QLatin1String("org.qtproject.QtDBus."));
         } else if (interface.startsWith(QLatin1Char('Q')) &&
                    interface.length() >= 2 && interface.at(1).isUpper()) {
             // assume it's Qt
             interface.prepend(QLatin1String("org.qtproject.Qt."));
         } else if (!QCoreApplication::instance()||
                    QCoreApplication::instance()->applicationName().isEmpty()) {
             interface.prepend(QLatin1String("local."));
          } else {
             interface.prepend(QLatin1Char('.')).prepend(QCoreApplication::instance()->applicationName());
             QStringList domainName =
                 QCoreApplication::instance()->organizationDomain().split(QLatin1Char('.'),
                                                                          QString::SkipEmptyParts);
             if (domainName.isEmpty())
                  interface.prepend(QLatin1String("local."));
             else
                 for (int i = 0; i < domainName.count(); ++i)
                     interface.prepend(QLatin1Char('.')).prepend(domainName.at(i));
          }
      }
     return interface;
 }
qDBusInterfaceInObject()
bool qDBusInterfaceInObject (QObject * obj, const QString & interface_name)
Definition at line 116 of file qdbusmisc.cpp.
Referenced by QDBusConnectionPrivate::activateObject(), qDBusPropertyGet(), and qDBusPropertySet().
 {
     const QMetaObject *mo = obj->metaObject();
     for ( ; mo != &QObject::staticMetaObject; mo = mo->superClass())
         if (interface_name == qDBusInterfaceFromMetaObject(mo))
             return true;
     return false;
 }
qDBusIntrospectObject()
QString qDBusIntrospectObject (const QDBusConnectionPrivate::ObjectTreeNode & node, const QString & path)
Definition at line 120 of file qdbusinternalfilters.cpp.
Referenced by QDBusConnectionPrivate::activateInternalFilters().
 {
     // object may be null
     QString xml_data(QLatin1String(DBUS_INTROSPECT_1_0_XML_DOCTYPE_DECL_NODE));
     xml_data += QLatin1String("<node>\n");
     if (node.obj) {
         Q_ASSERT_X(QThread::currentThread() == node.obj->thread(),
                    "QDBusConnection: internal threading error",
                    "function called for an object that is in another thread!!");
         if (node.flags & (QDBusConnection::ExportScriptableContents
                            | QDBusConnection::ExportNonScriptableContents)) {
             // create XML for the object itself
             const QMetaObject *mo = node.obj->metaObject();
             for ( ; mo != &QObject::staticMetaObject; mo = mo->superClass())
                 xml_data += qDBusGenerateMetaObjectXml(QString(), mo, mo->superClass(),
                                                        node.flags);
         }
         // does this object have adaptors?
         QDBusAdaptorConnector *connector;
         if (node.flags & QDBusConnection::ExportAdaptors &&
             (connector = qDBusFindAdaptorConnector(node.obj))) {
             // trasverse every adaptor in this object
             QDBusAdaptorConnector::AdaptorMap::ConstIterator it = connector->adaptors.constBegin();
             QDBusAdaptorConnector::AdaptorMap::ConstIterator end = connector->adaptors.constEnd();
             for ( ; it != end; ++it) {
                 // add the interface:
                 QString ifaceXml = QDBusAbstractAdaptorPrivate::retrieveIntrospectionXml(it->adaptor);
                 if (ifaceXml.isEmpty()) {
                     // add the interface's contents:
                     ifaceXml += qDBusGenerateMetaObjectXml(QString::fromLatin1(it->interface),
                                                            it->adaptor->metaObject(),
                                                            &QDBusAbstractAdaptor::staticMetaObject,
                                                            QDBusConnection::ExportScriptableContents
                                                            | QDBusConnection::ExportNonScriptableContents);
                     QDBusAbstractAdaptorPrivate::saveIntrospectionXml(it->adaptor, ifaceXml);
                 }
                 xml_data += ifaceXml;
             }
         }
         // is it a virtual node that handles introspection itself?
         if (node.flags & QDBusConnectionPrivate::VirtualObject) {
             xml_data += node.treeNode->introspect(path);
         }
         xml_data += QLatin1String( propertiesInterfaceXml );
     }
     xml_data += QLatin1String( introspectableInterfaceXml );
     xml_data += QLatin1String( peerInterfaceXml );
     if (node.flags & QDBusConnection::ExportChildObjects) {
         xml_data += generateSubObjectXml(node.obj);
     } else {
         // generate from the object tree
         QDBusConnectionPrivate::ObjectTreeNode::DataList::ConstIterator it =
             node.children.constBegin();
         QDBusConnectionPrivate::ObjectTreeNode::DataList::ConstIterator end =
             node.children.constEnd();
         for ( ; it != end; ++it)
             if (it->obj || !it->children.isEmpty())
                 xml_data += QString::fromLatin1("  <node name=\"%1\"/>\n")
                             .arg(it->name);
     }
     xml_data += QLatin1String("</node>\n");
     return xml_data;
 }
qDBusNameToTypeId()
int qDBusNameToTypeId (const char * name)
Definition at line 72 of file qdbusmisc.cpp.
Referenced by findSlot(), generateInterfaceXml(), qDBusParametersForMethod(), readAllProperties(), and writeProperty().
 {
     int id = static_cast<int>( QVariant::nameToType(name) );
     if (id == QVariant::UserType)
         id = QMetaType::type(name);
     return id;
 }
qDBusParametersForMethod()
int qDBusParametersForMethod (const QMetaMethod & mm, QList< int > & metaTypes)
Definition at line 137 of file qdbusmisc.cpp.
Referenced by QDBusConnectionPrivate::findSlot(), findSlot(), generateInterfaceXml(), and QDBusAdaptorConnector::relay().
 {
     QDBusMetaTypeId::init();
     QList<QByteArray> parameterTypes = mm.parameterTypes();
     metaTypes.clear();
     metaTypes.append(0);        // return type
     int inputCount = 0;
     bool seenMessage = false;
     QList<QByteArray>::ConstIterator it = parameterTypes.constBegin();
     QList<QByteArray>::ConstIterator end = parameterTypes.constEnd();
     for ( ; it != end; ++it) {
         const QByteArray &type = *it;
         if (type.endsWith('*')) {
             //qWarning("Could not parse the method '%s'", mm.signature());
             // pointer?
             return -1;
         }
         if (type.endsWith('&')) {
             QByteArray basictype = type;
             basictype.truncate(type.length() - 1);
             int id = qDBusNameToTypeId(basictype);
             if (id == 0) {
                 //qWarning("Could not parse the method '%s'", mm.signature());
                 // invalid type in method parameter list
                 return -1;
             } else if (QDBusMetaType::typeToSignature(id) == 0)
                 return -1;
             metaTypes.append( id );
             seenMessage = true; // it cannot appear anymore anyways
             continue;
         }
         if (seenMessage) {      // && !type.endsWith('&')
             //qWarning("Could not parse the method '%s'", mm.signature());
             // non-output parameters after message or after output params
             return -1;          // not allowed
         }
         int id = qDBusNameToTypeId(type);
         if (id == 0) {
             //qWarning("Could not parse the method '%s'", mm.signature());
             // invalid type in method parameter list
             return -1;
         }
         if (id == QDBusMetaTypeId::message)
             seenMessage = true;
         else if (QDBusMetaType::typeToSignature(id) == 0)
             return -1;
         metaTypes.append(id);
         ++inputCount;
     }
     return inputCount;
 }
qDBusPropertyGet()
QDBusMessage qDBusPropertyGet (const QDBusConnectionPrivate::ObjectTreeNode & node, const QDBusMessage & msg)
Definition at line 217 of file qdbusinternalfilters.cpp.
Referenced by QDBusConnectionPrivate::activateInternalFilters().
 {
     Q_ASSERT(msg.arguments().count() == 2);
     Q_ASSERT_X(!node.obj || QThread::currentThread() == node.obj->thread(),
                "QDBusConnection: internal threading error",
                "function called for an object that is in another thread!!");
     QString interface_name = msg.arguments().at(0).toString();
     QByteArray property_name = msg.arguments().at(1).toString().toUtf8();
     QDBusAdaptorConnector *connector;
     QVariant value;
     bool interfaceFound = false;
     if (node.flags & QDBusConnection::ExportAdaptors &&
         (connector = qDBusFindAdaptorConnector(node.obj))) {
         // find the class that implements interface_name or try until we've found the property
         // in case of an empty interface
         if (interface_name.isEmpty()) {
             for (QDBusAdaptorConnector::AdaptorMap::ConstIterator it = connector->adaptors.constBegin(),
                  end = connector->adaptors.constEnd(); it != end; ++it) {
                 const QMetaObject *mo = it->adaptor->metaObject();
                 int pidx = mo->indexOfProperty(property_name);
                 if (pidx != -1) {
                     value = mo->property(pidx).read(it->adaptor);
                     break;
                 }
             }
         } else {
             QDBusAdaptorConnector::AdaptorMap::ConstIterator it;
             it = qLowerBound(connector->adaptors.constBegin(), connector->adaptors.constEnd(),
                              interface_name);
             if (it != connector->adaptors.constEnd() && interface_name == QLatin1String(it->interface)) {
                 interfaceFound = true;
                 value = it->adaptor->property(property_name);
             }
         }
     }
     if (!interfaceFound && !value.isValid()
         && node.flags & (QDBusConnection::ExportAllProperties |
                          QDBusConnection::ExportNonScriptableProperties)) {
         // try the object itself
         if (!interface_name.isEmpty())
             interfaceFound = qDBusInterfaceInObject(node.obj, interface_name);
         if (interfaceFound) {
             int pidx = node.obj->metaObject()->indexOfProperty(property_name);
             if (pidx != -1) {
                 QMetaProperty mp = node.obj->metaObject()->property(pidx);
                 if ((mp.isScriptable() && (node.flags & QDBusConnection::ExportScriptableProperties)) ||
                     (!mp.isScriptable() && (node.flags & QDBusConnection::ExportNonScriptableProperties)))
                     value = mp.read(node.obj);
             }
         }
     }
     if (!value.isValid()) {
         // the property was not found
         if (!interfaceFound)
             return interfaceNotFoundError(msg, interface_name);
         return propertyNotFoundError(msg, interface_name, property_name);
     }
     return msg.createReply(QVariant::fromValue(QDBusVariant(value)));
 }
qDBusPropertyGetAll()
QDBusMessage qDBusPropertyGetAll (const QDBusConnectionPrivate::ObjectTreeNode & node, const QDBusMessage & msg)
Definition at line 466 of file qdbusinternalfilters.cpp.
Referenced by QDBusConnectionPrivate::activateInternalFilters().
 {
     Q_ASSERT(msg.arguments().count() == 1);
     Q_ASSERT_X(!node.obj || QThread::currentThread() == node.obj->thread(),
                "QDBusConnection: internal threading error",
                "function called for an object that is in another thread!!");
     QString interface_name = msg.arguments().at(0).toString();
     bool interfaceFound = false;
     QVariantMap result;
     QDBusAdaptorConnector *connector;
     if (node.flags & QDBusConnection::ExportAdaptors &&
         (connector = qDBusFindAdaptorConnector(node.obj))) {
         if (interface_name.isEmpty()) {
             // iterate over all interfaces
             for (QDBusAdaptorConnector::AdaptorMap::ConstIterator it = connector->adaptors.constBegin(),
                  end = connector->adaptors.constEnd(); it != end; ++it) {
                 result += readAllProperties(it->adaptor, QDBusConnection::ExportAllProperties);
             }
         } else {
             // find the class that implements interface_name
             QDBusAdaptorConnector::AdaptorMap::ConstIterator it;
             it = qLowerBound(connector->adaptors.constBegin(), connector->adaptors.constEnd(),
                              interface_name);
             if (it != connector->adaptors.constEnd() && interface_name == QLatin1String(it->interface)) {
                 interfaceFound = true;
                 result = readAllProperties(it->adaptor, QDBusConnection::ExportAllProperties);
             }
         }
     }
     if (node.flags & QDBusConnection::ExportAllProperties &&
         (!interfaceFound || interface_name.isEmpty())) {
         // try the object itself
         result += readAllProperties(node.obj, node.flags);
         interfaceFound = true;
     }
     if (!interfaceFound && !interface_name.isEmpty()) {
         // the interface was not found
         return interfaceNotFoundError(msg, interface_name);
     }
     return msg.createReply(QVariant::fromValue(result));
 }
qDBusPropertySet()
QDBusMessage qDBusPropertySet (const QDBusConnectionPrivate::ObjectTreeNode & node, const QDBusMessage & msg)
Definition at line 366 of file qdbusinternalfilters.cpp.
Referenced by QDBusConnectionPrivate::activateInternalFilters().
 {
     Q_ASSERT(msg.arguments().count() == 3);
     Q_ASSERT_X(!node.obj || QThread::currentThread() == node.obj->thread(),
                "QDBusConnection: internal threading error",
                "function called for an object that is in another thread!!");
     QString interface_name = msg.arguments().at(0).toString();
     QByteArray property_name = msg.arguments().at(1).toString().toUtf8();
     QVariant value = qvariant_cast<QDBusVariant>(msg.arguments().at(2)).variant();
     QDBusAdaptorConnector *connector;
     if (node.flags & QDBusConnection::ExportAdaptors &&
         (connector = qDBusFindAdaptorConnector(node.obj))) {
         // find the class that implements interface_name or try until we've found the property
         // in case of an empty interface
         if (interface_name.isEmpty()) {
             for (QDBusAdaptorConnector::AdaptorMap::ConstIterator it = connector->adaptors.constBegin(),
                  end = connector->adaptors.constEnd(); it != end; ++it) {
                 int status = writeProperty(it->adaptor, property_name, value);
                 if (status == PropertyNotFound)
                     continue;
                 return propertyWriteReply(msg, interface_name, property_name, status);
             }
         } else {
             QDBusAdaptorConnector::AdaptorMap::ConstIterator it;
             it = qLowerBound(connector->adaptors.constBegin(), connector->adaptors.constEnd(),
                              interface_name);
             if (it != connector->adaptors.end() && interface_name == QLatin1String(it->interface)) {
                 return propertyWriteReply(msg, interface_name, property_name,
                                           writeProperty(it->adaptor, property_name, value));
             }
         }
     }
     if (node.flags & (QDBusConnection::ExportScriptableProperties |
                       QDBusConnection::ExportNonScriptableProperties)) {
         // try the object itself
         bool interfaceFound = true;
         if (!interface_name.isEmpty())
             interfaceFound = qDBusInterfaceInObject(node.obj, interface_name);
         if (interfaceFound) {
             return propertyWriteReply(msg, interface_name, property_name,
                                       writeProperty(node.obj, property_name, value, node.flags));
         }
     }
     // the property was not found
     if (!interface_name.isEmpty())
         return interfaceNotFoundError(msg, interface_name);
     return propertyWriteReply(msg, interface_name, property_name, PropertyNotFound);
 }