Qt 4.8: /src/dbus/qdbusmetaobject.cpp File Reference
qdbusmetaobject.cpp File Reference
#include "qdbusmetaobject_p.h"
#include <QtCore/qbytearray.h>
#include <QtCore/qhash.h>
#include <QtCore/qstring.h>
#include <QtCore/qvarlengtharray.h>
#include "qdbusutil_p.h"
#include "qdbuserror.h"
#include "qdbusmetatype.h"
#include "qdbusargument.h"
#include "qdbusintrospection_p.h"
#include "qdbusabstractinterface_p.h"
Classes
class QDBusMetaObjectGenerator
struct QDBusMetaObjectGenerator::Method
struct QDBusMetaObjectGenerator::Property
struct QDBusMetaObjectGenerator::Type
struct QDBusMetaObjectPrivate
Functions
static const QDBusMetaObjectPrivate * priv (const uint *data)
Variables
static const int intsPerMethod = 5
static const int intsPerProperty = 2
Q_DBUS_EXPORT bool qt_dbus_metaobject_skip_annotations = false
Function Documentation
priv()
static const QDBusMetaObjectPrivate* priv (const uint * data) inline static
Definition at line 646 of file qdbusmetaobject.cpp.
Referenced by QDBusMetaObject::dbusNameForMethod(), QDBusMetaObject::inputSignatureForMethod(), QDBusMetaObject::inputTypesForMethod(), QDBusMetaObject::outputSignatureForMethod(), QDBusMetaObject::outputTypesForMethod(), and QDBusMetaObject::propertyMetaType().
 {
     return reinterpret_cast<const QDBusMetaObjectPrivate *>(data);
 }
Variable Documentation
intsPerMethod
const int intsPerMethod = 5 static
Definition at line 144 of file qdbusmetaobject.cpp.
Referenced by QDBusMetaObject::dbusNameForMethod(), QDBusMetaObject::inputSignatureForMethod(), QDBusMetaObject::inputTypesForMethod(), QDBusMetaObject::outputSignatureForMethod(), QDBusMetaObject::outputTypesForMethod(), and QDBusMetaObjectGenerator::write().
intsPerProperty
const int intsPerProperty = 2 static
Definition at line 143 of file qdbusmetaobject.cpp.
Referenced by QDBusMetaObject::propertyMetaType(), and QDBusMetaObjectGenerator::write().
qt_dbus_metaobject_skip_annotations
Q_DBUS_EXPORT bool qt_dbus_metaobject_skip_annotations = false
Definition at line 172 of file qdbusmetaobject.cpp.
Referenced by QDBusMetaObjectGenerator::findType().