Qt 4.8: /src/dbus/qdbusargument.h File Reference
qdbusargument.h File Reference
#include <QtCore/qbytearray.h>
#include <QtCore/qhash.h>
#include <QtCore/qglobal.h>
#include <QtCore/qlist.h>
#include <QtCore/qmap.h>
#include <QtCore/qstring.h>
#include <QtCore/qstringlist.h>
#include <QtCore/qvariant.h>
#include <QtDBus/qdbusextratypes.h>
#include <QtDBus/qdbusmacros.h>
Classes
class QDBusArgument
The QDBusArgument class is used to marshall and demarshall D-Bus arguments.
Functions
Q_DBUS_EXPORT QDBusArgument & operator<< (QDBusArgument &a, const QDate &date)
Q_DBUS_EXPORT QDBusArgument & operator<< (QDBusArgument &a, const QTime &time)
Q_DBUS_EXPORT QDBusArgument & operator<< (QDBusArgument &a, const QDateTime &dt)
Q_DBUS_EXPORT QDBusArgument & operator<< (QDBusArgument &a, const QRect &rect)
Q_DBUS_EXPORT QDBusArgument & operator<< (QDBusArgument &a, const QRectF &rect)
Q_DBUS_EXPORT QDBusArgument & operator<< (QDBusArgument &a, const QSize &size)
Q_DBUS_EXPORT QDBusArgument & operator<< (QDBusArgument &a, const QSizeF &size)
Q_DBUS_EXPORT QDBusArgument & operator<< (QDBusArgument &a, const QPoint &pt)
Q_DBUS_EXPORT QDBusArgument & operator<< (QDBusArgument &a, const QPointF &pt)
Q_DBUS_EXPORT QDBusArgument & operator<< (QDBusArgument &a, const QLine &line)
Q_DBUS_EXPORT QDBusArgument & operator<< (QDBusArgument &a, const QLineF &line)
template<template< typename > class Container, typename T >
QDBusArgument & operator<< (QDBusArgument &arg, const Container< T > &list)
template<typename T >
QDBusArgument & operator<< (QDBusArgument &arg, const QList< T > &list)
QDBusArgument & operator<< (QDBusArgument &arg, const QVariantList &list)
template<typename Key , typename T >
QDBusArgument & operator<< (QDBusArgument &arg, const QMap< Key, T > &map)
QDBusArgument & operator<< (QDBusArgument &arg, const QVariantMap &map)
template<typename Key , typename T >
QDBusArgument & operator<< (QDBusArgument &arg, const QHash< Key, T > &map)
QDBusArgument & operator<< (QDBusArgument &arg, const QVariantHash &map)
Q_DBUS_EXPORT const QDBusArgument & operator>> (const QDBusArgument &a, QVariant &v)
Q_DBUS_EXPORT const QDBusArgument & operator>> (const QDBusArgument &a, QDate &date)
Q_DBUS_EXPORT const QDBusArgument & operator>> (const QDBusArgument &a, QTime &time)
Q_DBUS_EXPORT const QDBusArgument & operator>> (const QDBusArgument &a, QDateTime &dt)
Q_DBUS_EXPORT const QDBusArgument & operator>> (const QDBusArgument &a, QRect &rect)
Q_DBUS_EXPORT const QDBusArgument & operator>> (const QDBusArgument &a, QRectF &rect)
Q_DBUS_EXPORT const QDBusArgument & operator>> (const QDBusArgument &a, QSize &size)
Q_DBUS_EXPORT const QDBusArgument & operator>> (const QDBusArgument &a, QSizeF &size)
Q_DBUS_EXPORT const QDBusArgument & operator>> (const QDBusArgument &a, QPoint &pt)
Q_DBUS_EXPORT const QDBusArgument & operator>> (const QDBusArgument &a, QPointF &pt)
Q_DBUS_EXPORT const QDBusArgument & operator>> (const QDBusArgument &a, QLine &line)
Q_DBUS_EXPORT const QDBusArgument & operator>> (const QDBusArgument &a, QLineF &line)
template<template< typename > class Container, typename T >
const QDBusArgument & operator>> (const QDBusArgument &arg, Container< T > &list)
template<typename T >
const QDBusArgument & operator>> (const QDBusArgument &arg, QList< T > &list)
template<typename Key , typename T >
const QDBusArgument & operator>> (const QDBusArgument &arg, QMap< Key, T > &map)
template<typename Key , typename T >
const QDBusArgument & operator>> (const QDBusArgument &arg, QHash< Key, T > &map)
template<typename T >
T qdbus_cast (const QDBusArgument &arg)
template<typename T >
T qdbus_cast (const QVariant &v)
template<>
QVariant qdbus_cast< QVariant > (const QDBusArgument &arg, QVariant *)
template<>
QVariant qdbus_cast< QVariant > (const QVariant &v, QVariant *)
Function Documentation
operator<<() [1/18]
Q_DBUS_EXPORT QDBusArgument& operator<< (QDBusArgument & a, const QDate & date)
Definition at line 1253 of file qdbusargument.cpp.
Referenced by qdbus_cast< QVariant >().
 {
     a.beginStructure();
     if (date.isValid())
         a << date.year() << date.month() << date.day();
     else
         a << 0 << 0 << 0;
     a.endStructure();
     return a;
 }
operator<<() [2/18]
Q_DBUS_EXPORT QDBusArgument& operator<< (QDBusArgument & a, const QTime & time)
Definition at line 1278 of file qdbusargument.cpp.
 {
     a.beginStructure();
     if (time.isValid())
         a << time.hour() << time.minute() << time.second() << time.msec();
     else
         a << -1 << -1 << -1 << -1;
     a.endStructure();
     return a;
 }
operator<<() [3/18]
Q_DBUS_EXPORT QDBusArgument& operator<< (QDBusArgument & a, const QDateTime & dt)
Definition at line 1303 of file qdbusargument.cpp.
 {
     a.beginStructure();
     a << dt.date() << dt.time() << int(dt.timeSpec());
     a.endStructure();
     return a;
 }
operator<<() [4/18]
Q_DBUS_EXPORT QDBusArgument& operator<< (QDBusArgument & a, const QRect & rect)
Definition at line 1322 of file qdbusargument.cpp.
 {
     a.beginStructure();
     a << rect.x() << rect.y() << rect.width() << rect.height();
     a.endStructure();
     return a;
 }
operator<<() [5/18]
Q_DBUS_EXPORT QDBusArgument& operator<< (QDBusArgument & a, const QRectF & rect)
Definition at line 1342 of file qdbusargument.cpp.
 {
     a.beginStructure();
     a << double(rect.x()) << double(rect.y()) << double(rect.width()) << double(rect.height());
     a.endStructure();
     return a;
 }
operator<<() [6/18]
Q_DBUS_EXPORT QDBusArgument& operator<< (QDBusArgument & a, const QSize & size)
Definition at line 1360 of file qdbusargument.cpp.
 {
     a.beginStructure();
     a << size.width() << size.height();
     a.endStructure();
     return a;
 }
operator<<() [7/18]
Q_DBUS_EXPORT QDBusArgument& operator<< (QDBusArgument & a, const QSizeF & size)
Definition at line 1381 of file qdbusargument.cpp.
 {
     a.beginStructure();
     a << double(size.width()) << double(size.height());
     a.endStructure();
     return a;
 }
operator<<() [8/18]
Q_DBUS_EXPORT QDBusArgument& operator<< (QDBusArgument & a, const QPoint & pt)
Definition at line 1399 of file qdbusargument.cpp.
 {
     a.beginStructure();
     a << pt.x() << pt.y();
     a.endStructure();
     return a;
 }
operator<<() [9/18]
Q_DBUS_EXPORT QDBusArgument& operator<< (QDBusArgument & a, const QPointF & pt)
Definition at line 1420 of file qdbusargument.cpp.
 {
     a.beginStructure();
     a << double(pt.x()) << double(pt.y());
     a.endStructure();
     return a;
 }
operator<<() [10/18]
Q_DBUS_EXPORT QDBusArgument& operator<< (QDBusArgument & a, const QLine & line)
Definition at line 1440 of file qdbusargument.cpp.
 {
     a.beginStructure();
     a << line.p1() << line.p2();
     a.endStructure();
     return a;
 }
operator<<() [11/18]
Q_DBUS_EXPORT QDBusArgument& operator<< (QDBusArgument & a, const QLineF & line)
Definition at line 1460 of file qdbusargument.cpp.
 {
     a.beginStructure();
     a << line.p1() << line.p2();
     a.endStructure();
     return a;
 }
operator<<() [12/18]
template<template< typename > class Container, typename T > QDBusArgument& operator<< (QDBusArgument & arg, const Container< T > & list) inline
Definition at line 231 of file qdbusargument.h.
 {
     int id = qMetaTypeId<T>();
     arg.beginArray(id);
     typename Container<T>::const_iterator it = list.begin();
     typename Container<T>::const_iterator end = list.end();
     for ( ; it != end; ++it)
         arg << *it;
     arg.endArray();
     return arg;
 }
operator<<() [13/18]
template<typename T > QDBusArgument& operator<< (QDBusArgument & arg, const QList< T > & list) inline
Definition at line 260 of file qdbusargument.h.
 {
     int id = qMetaTypeId<T>();
     arg.beginArray(id);
     typename QList<T>::ConstIterator it = list.constBegin();
     typename QList<T>::ConstIterator end = list.constEnd();
     for ( ; it != end; ++it)
         arg << *it;
     arg.endArray();
     return arg;
 }
operator<<() [14/18]
QDBusArgument& operator<< (QDBusArgument & arg, const QVariantList & list) inline
Definition at line 287 of file qdbusargument.h.
 {
     int id = qMetaTypeId<QDBusVariant>();
     arg.beginArray(id);
     QVariantList::ConstIterator it = list.constBegin();
     QVariantList::ConstIterator end = list.constEnd();
     for ( ; it != end; ++it)
         arg << QDBusVariant(*it);
     arg.endArray();
     return arg;
 }
operator<<() [15/18]
template<typename Key , typename T > QDBusArgument& operator<< (QDBusArgument & arg, const QMap< Key, T > & map) inline
Definition at line 301 of file qdbusargument.h.
 {
     int kid = qMetaTypeId<Key>();
     int vid = qMetaTypeId<T>();
     arg.beginMap(kid, vid);
     typename QMap<Key, T>::ConstIterator it = map.constBegin();
     typename QMap<Key, T>::ConstIterator end = map.constEnd();
     for ( ; it != end; ++it) {
         arg.beginMapEntry();
         arg << it.key() << it.value();
         arg.endMapEntry();
     }
     arg.endMap();
     return arg;
 }
operator<<() [16/18]
QDBusArgument& operator<< (QDBusArgument & arg, const QVariantMap & map) inline
Definition at line 334 of file qdbusargument.h.
 {
     arg.beginMap(QVariant::String, qMetaTypeId<QDBusVariant>());
     QVariantMap::ConstIterator it = map.constBegin();
     QVariantMap::ConstIterator end = map.constEnd();
     for ( ; it != end; ++it) {
         arg.beginMapEntry();
         arg << it.key() << QDBusVariant(it.value());
         arg.endMapEntry();
     }
     arg.endMap();
     return arg;
 }
operator<<() [17/18]
template<typename Key , typename T > QDBusArgument& operator<< (QDBusArgument & arg, const QHash< Key, T > & map) inline
Definition at line 350 of file qdbusargument.h.
 {
     int kid = qMetaTypeId<Key>();
     int vid = qMetaTypeId<T>();
     arg.beginMap(kid, vid);
     typename QHash<Key, T>::ConstIterator it = map.constBegin();
     typename QHash<Key, T>::ConstIterator end = map.constEnd();
     for ( ; it != end; ++it) {
         arg.beginMapEntry();
         arg << it.key() << it.value();
         arg.endMapEntry();
     }
     arg.endMap();
     return arg;
 }
operator<<() [18/18]
QDBusArgument& operator<< (QDBusArgument & arg, const QVariantHash & map) inline
Definition at line 383 of file qdbusargument.h.
 {
     arg.beginMap(QVariant::String, qMetaTypeId<QDBusVariant>());
     QVariantHash::ConstIterator it = map.constBegin();
     QVariantHash::ConstIterator end = map.constEnd();
     for ( ; it != end; ++it) {
         arg.beginMapEntry();
         arg << it.key() << QDBusVariant(it.value());
         arg.endMapEntry();
     }
     arg.endMap();
     return arg;
 }
operator>>() [1/16]
Q_DBUS_EXPORT const QDBusArgument& operator>> (const QDBusArgument & a, QVariant & v)
Definition at line 1229 of file qdbusargument.cpp.
Referenced by qdbus_cast< QVariant >().
 {
     QDBusVariant dbv;
     a >> dbv;
     v = dbv.variant();
     return a;
 }
operator>>() [2/16]
Q_DBUS_EXPORT const QDBusArgument& operator>> (const QDBusArgument & a, QDate & date)
Definition at line 1239 of file qdbusargument.cpp.
 {
     int y, m, d;
     a.beginStructure();
     a >> y >> m >> d;
     a.endStructure();
     if (y != 0 && m != 0 && d != 0)
         date.setYMD(y, m, d);
     else
         date = QDate();
     return a;
 }
operator>>() [3/16]
Q_DBUS_EXPORT const QDBusArgument& operator>> (const QDBusArgument & a, QTime & time)
Definition at line 1264 of file qdbusargument.cpp.
 {
     int h, m, s, ms;
     a.beginStructure();
     a >> h >> m >> s >> ms;
     a.endStructure();
     if (h < 0)
         time = QTime();
     else
         time.setHMS(h, m, s, ms);
     return a;
 }
operator>>() [4/16]
Q_DBUS_EXPORT const QDBusArgument& operator>> (const QDBusArgument & a, QDateTime & dt)
Definition at line 1289 of file qdbusargument.cpp.
 {
     QDate date;
     QTime time;
     int timespec;
     a.beginStructure();
     a >> date >> time >> timespec;
     a.endStructure();
     dt = QDateTime(date, time, Qt::TimeSpec(timespec));
     return a;
 }
operator>>() [5/16]
Q_DBUS_EXPORT const QDBusArgument& operator>> (const QDBusArgument & a, QRect & rect)
Definition at line 1311 of file qdbusargument.cpp.
 {
     int x, y, width, height;
     a.beginStructure();
     a >> x >> y >> width >> height;
     a.endStructure();
     rect.setRect(x, y, width, height);
     return a;
 }
operator>>() [6/16]
Q_DBUS_EXPORT const QDBusArgument& operator>> (const QDBusArgument & a, QRectF & rect)
Definition at line 1331 of file qdbusargument.cpp.
 {
     double x, y, width, height;
     a.beginStructure();
     a >> x >> y >> width >> height;
     a.endStructure();
     rect.setRect(qreal(x), qreal(y), qreal(width), qreal(height));
     return a;
 }
operator>>() [7/16]
Q_DBUS_EXPORT const QDBusArgument& operator>> (const QDBusArgument & a, QSize & size)
Definition at line 1351 of file qdbusargument.cpp.
 {
     a.beginStructure();
     a >> size.rwidth() >> size.rheight();
     a.endStructure();
     return a;
 }
operator>>() [8/16]
Q_DBUS_EXPORT const QDBusArgument& operator>> (const QDBusArgument & a, QSizeF & size)
Definition at line 1369 of file qdbusargument.cpp.
 {
     double width, height;
     a.beginStructure();
     a >> width >> height;
     a.endStructure();
     size.setWidth(qreal(width));
     size.setHeight(qreal(height));
     return a;
 }
operator>>() [9/16]
Q_DBUS_EXPORT const QDBusArgument& operator>> (const QDBusArgument & a, QPoint & pt)
Definition at line 1390 of file qdbusargument.cpp.
 {
     a.beginStructure();
     a >> pt.rx() >> pt.ry();
     a.endStructure();
     return a;
 }
operator>>() [10/16]
Q_DBUS_EXPORT const QDBusArgument& operator>> (const QDBusArgument & a, QPointF & pt)
Definition at line 1408 of file qdbusargument.cpp.
 {
     double x, y;
     a.beginStructure();
     a >> x >> y;
     a.endStructure();
     pt.setX(qreal(x));
     pt.setY(qreal(y));
     return a;
 }
operator>>() [11/16]
Q_DBUS_EXPORT const QDBusArgument& operator>> (const QDBusArgument & a, QLine & line)
Definition at line 1429 of file qdbusargument.cpp.
 {
     QPoint p1, p2;
     a.beginStructure();
     a >> p1 >> p2;
     a.endStructure();
     line = QLine(p1, p2);
     return a;
 }
operator>>() [12/16]
Q_DBUS_EXPORT const QDBusArgument& operator>> (const QDBusArgument & a, QLineF & line)
Definition at line 1449 of file qdbusargument.cpp.
 {
     QPointF p1, p2;
     a.beginStructure();
     a >> p1 >> p2;
     a.endStructure();
     line = QLineF(p1, p2);
     return a;
 }
operator>>() [13/16]
template<template< typename > class Container, typename T > const QDBusArgument& operator>> (const QDBusArgument & arg, Container< T > & list) inline
Definition at line 244 of file qdbusargument.h.
 {
     arg.beginArray();
     list.clear();
     while (!arg.atEnd()) {
         T item;
         arg >> item;
         list.push_back(item);
     }
     arg.endArray();
     return arg;
 }
operator>>() [14/16]
template<typename T > const QDBusArgument& operator>> (const QDBusArgument & arg, QList< T > & list) inline
Definition at line 273 of file qdbusargument.h.
 {
     arg.beginArray();
     list.clear();
     while (!arg.atEnd()) {
         T item;
         arg >> item;
         list.push_back(item);
     }
     arg.endArray();
     return arg;
 }
operator>>() [15/16]
template<typename Key , typename T > const QDBusArgument& operator>> (const QDBusArgument & arg, QMap< Key, T > & map) inline
Definition at line 318 of file qdbusargument.h.
 {
     arg.beginMap();
     map.clear();
     while (!arg.atEnd()) {
         Key key;
         T value;
         arg.beginMapEntry();
         arg >> key >> value;
         map.insertMulti(key, value);
         arg.endMapEntry();
     }
     arg.endMap();
     return arg;
 }
operator>>() [16/16]
template<typename Key , typename T > const QDBusArgument& operator>> (const QDBusArgument & arg, QHash< Key, T > & map) inline
Definition at line 367 of file qdbusargument.h.
 {
     arg.beginMap();
     map.clear();
     while (!arg.atEnd()) {
         Key key;
         T value;
         arg.beginMapEntry();
         arg >> key >> value;
         map.insertMulti(key, value);
         arg.endMapEntry();
     }
     arg.endMap();
     return arg;
 }
qdbus_cast() [1/2]
template<typename T > T qdbus_cast (const QDBusArgument & arg) related
Definition at line 155 of file qdbusargument.h.
Referenced by QDBusPendingReply< T1, T2, T3, T4, T5, T6, T7, T8 >::argumentAt(), QOfonoSimInterface::cardIdentifier(), QConnmanManagerInterface::getActiveProfile(), QOfonoPrimaryDataContextInterface::getAddress(), QConnmanServiceInterface::getAPN(), QOfonoPrimaryDataContextInterface::getApName(), QConnmanManagerInterface::getAvailableTechnologies(), QOfonoNetworkRegistrationInterface::getBaseStation(), QConnmanManagerInterface::getConnectedTechnologies(), QConnmanManagerInterface::getDefaultTechnology(), QConnmanServiceInterface::getDomains(), QConnmanManagerInterface::getEnabledTechnologies(), QConnmanServiceInterface::getError(), QConnmanServiceInterface::getEthernet(), QOfonoModemInterface::getFeatures(), QOfonoSimInterface::getHomeMcc(), QOfonoSimInterface::getHomeMnc(), QOfonoPrimaryDataContextInterface::getInterface(), QOfonoModemInterface::getInterfaces(), QConnmanServiceInterface::getIPv4(), QConnmanServiceInterface::getIPv4Configuration(), QOfonoModemInterface::getManufacturer(), QOfonoNetworkOperatorInterface::getMcc(), QConnmanServiceInterface::getMCC(), QOfonoNetworkOperatorInterface::getMnc(), QConnmanServiceInterface::getMNC(), QConnmanServiceInterface::getMode(), QOfonoModemInterface::getModel(), QOfonoModemInterface::getName(), QConnmanProfileInterface::getName(), QConnmanServiceInterface::getName(), QOfonoNetworkOperatorInterface::getName(), QConnmanTechnologyInterface::getName(), QOfonoPrimaryDataContextInterface::getName(), QConnmanServiceInterface::getNameservers(), QConnmanManagerInterface::getOfflineMode(), QOfonoNetworkRegistrationInterface::getOperatorName(), QConnmanServiceInterface::getPassphrase(), QConnmanManagerInterface::getProfiles(), QConnmanServiceInterface::getProxy(), QOfonoModemInterface::getRevision(), QConnmanServiceInterface::getSecurity(), QOfonoModemInterface::getSerial(), QConnmanManagerInterface::getServices(), QConnmanProfileInterface::getServices(), QConnmanServiceInterface::getServices(), QOfonoPrimaryDataContextInterface::getSettings(), QOfonoNetworkRegistrationInterface::getSignalStrength(), QConnmanServiceInterface::getSignalStrength(), QConnmanServiceInterface::getState(), QConnmanTechnologyInterface::getState(), QOfonoNetworkRegistrationInterface::getStatus(), QOfonoNetworkOperatorInterface::getStatus(), QConnmanManagerInterface::getTechnologies(), QOfonoNetworkOperatorInterface::getTechnologies(), QOfonoNetworkRegistrationInterface::getTechnology(), QConnmanServiceInterface::getType(), QConnmanTechnologyInterface::getType(), QOfonoPrimaryDataContextInterface::getType(), QNetworkManagerEngine::interfacePropertiesChanged(), QOfonoPrimaryDataContextInterface::isActive(), QOfonoDataConnectionManagerInterface::isAttached(), QConnmanServiceInterface::isAutoConnect(), QConnmanServiceInterface::isFavorite(), QConnmanServiceInterface::isImmutable(), QConnmanProfileInterface::isOfflineMode(), QConnmanServiceInterface::isOfflineMode(), QOfonoModemInterface::isOnline(), QConnmanServiceInterface::isPassphraseRequired(), QOfonoModemInterface::isPowered(), QOfonoDataConnectionManagerInterface::isPowered(), QOfonoSimInterface::isPresent(), QConnmanServiceInterface::isRoaming(), QOfonoDataConnectionManagerInterface::isRoamingAllowed(), QConnmanServiceInterface::isSetupRequired(), QOfonoSimInterface::lockedPins(), QOfonoSimInterface::pinRequired(), QConnmanEngine::propertyChangedContext(), qdbus_cast(), and qdbus_cast< QVariant >().
 {
     T item;
     arg >> item;
     return item;
 }
qdbus_cast() [2/2]
template<typename T > T qdbus_cast (const QVariant & v) inline
Definition at line 166 of file qdbusargument.h.
 {
     int id = v.userType();
     if (id == qMetaTypeId<QDBusArgument>())
         return qdbus_cast<T>(qvariant_cast<QDBusArgument>(v));
     else
         return qvariant_cast<T>(v);
 }
qdbus_cast< QVariant >() [1/2]
template<> QVariant qdbus_cast< QVariant > (const QDBusArgument & arg, QVariant *) inline
Definition at line 180 of file qdbusargument.h.
 {
     QDBusVariant item;
     arg >> item;
     return item.variant();
 }
qdbus_cast< QVariant >() [2/2]
template<> QVariant qdbus_cast< QVariant > (const QVariant & v, QVariant *) inline
Definition at line 186 of file qdbusargument.h.
 {
     return qdbus_cast<QDBusVariant>(v).variant();
 }