Qt 4.8: /src/dbus/qdbusmessage.cpp File Reference
qdbusmessage.cpp File Reference
#include "qdbusmessage.h"
#include <qdebug.h>
#include <qstringlist.h>
#include "qdbus_symbols_p.h"
#include "qdbusargument_p.h"
#include "qdbuserror.h"
#include "qdbusmessage_p.h"
#include "qdbusmetatype.h"
#include "qdbusconnection_p.h"
#include "qdbusutil_p.h"
Functions
static const char * data (const QByteArray &arr)
static void debugVariantList (QDebug dbg, const QVariantList &list)
static QDebug operator<< (QDebug dbg, QDBusMessage::MessageType t)
Sends the message without waiting for a reply.
QDebug operator<< (QDebug dbg, const QDBusMessage &msg)
Function Documentation
data()
static const char* data (const QByteArray & arr) inline static
Definition at line 60 of file qdbusmessage.cpp.
Referenced by QSocks5SocketEnginePrivate::_q_controlSocketBytesWritten(), QSocks5SocketEnginePrivate::_q_controlSocketConnected(), QSocks5SocketEnginePrivate::_q_controlSocketError(), QSocks5SocketEnginePrivate::_q_controlSocketReadNotification(), QDeclarativeVisualDataModel::_q_itemsChanged(), QDeclarativeVisualDataModel::_q_itemsInserted(), QDeclarativeVisualDataModel::_q_itemsMoved(), QDeclarativeVisualDataModel::_q_itemsRemoved(), _q_mapFromX509Name(), QScriptEnginePrivate::_q_objectDestroyed(), QScriptDebuggerPrivate::_q_toggleBreakpoint(), QSocks5SocketEnginePrivate::_q_udpSocketReadNotification(), QStandardItem::accessibleDescription(), QStandardItem::accessibleText(), QGraphicsAnchorLayoutPrivate::acquireGraphicsAnchor(), QLayout::activate(), QDeclarativeFastProperties::add(), QWSSoundServerProvider::add(), QGraphicsAnchorLayoutPrivate::addAnchor(), QFontDatabase::addApplicationFont(), QVectorPath::addCacheData(), QScriptDebuggerConsoleCommandManager::addCommandGroup(), QGridLayoutPrivate::addData(), QPaintBufferPrivate::addData(), QXmlStreamReader::addData(), QZipWriterPrivate::addEntry(), QDeclarativeGuardImpl::addGuard(), QPdfEnginePrivate::addImage(), QListWidget::addItems(), QDeclarativeContextData::addObject(), QFontDatabasePrivate::addQPF2File(), QDeclarativeAbstractBinding::addToObject(), QFSFileEngineIterator::advance(), QAxServerBase::Advise(), QTtfStream::align4(), qargb8565::alpha(), qargb8555::alpha(), qargb6666::alpha(), qargb4444::alpha(), QGLPixmapGLPaintDevice::alphaRequested(), QCopChannel::answer(), QTestTablePrivate::append(), QDBusMarshaller::append(), QDeclarativePropertyCache::append(), QDBusMarshaller::appendCrossMarshalling(), QNetworkReplyImplPrivate::appendDownstreamData(), Maemo::appendVariantToDBusMessage(), QDeclarativeEnginePrivate::atob(), QDeclarativeMetaType::attachedPropertiesFuncById(), QDeclarativeMetaType::attachedPropertiesFuncId(), QStandardItem::background(), QListWidgetItem::background(), QTableWidgetItem::background(), QTreeWidgetItem::background(), QListWidgetItem::backgroundColor(), QTableWidgetItem::backgroundColor(), QTreeWidgetItem::backgroundColor(), QScreen::base(), QPatternist::Base64Binary::base64Decode(), QDeclarativeContext::baseUrl(), QDirectFBPaintEngine::begin(), QX11PaintEngine::begin(), QFragmentMap< QTextBlockData >::begin(), QGLPixmapGLPaintDevice::beginPaint(), QDeclarativePropertyPrivate::binding(), QOCIResultPrivate::bindValue(), QFontEngineXLFD::bitmapForGlyphs(), blit_template(), QCss::ValueExtractor::borderValue(), bpsIOHandler(), QRasterPaintEnginePrivate::brushMatrix(), QCss::Declaration::brushValue(), QCss::Declaration::brushValues(), QDeclarativeEnginePrivate::btoa(), QDeclarativeCompiler::buildDynamicMeta(), buildMetaObject(), QDeclarativeBindingCompilerPrivate::buildSignalTable(), buttonChange(), qargb8565::byte_mul(), qrgb565::byte_mul(), qargb8555::byte_mul(), qrgb555::byte_mul(), qargb6666::byte_mul(), qrgb666::byte_mul(), qargb4444::byte_mul(), qrgb444::byte_mul(), QHttpMultiPartIODevice::bytesToWrite(), QWaylandSelection::cancelled(), QVariant::canConvert(), QSslCertificatePrivate::certificatesFromDer(), QSslCertificatePrivate::certificatesFromPem(), QTextFragment::charFormat(), QTextFragment::charFormatIndex(), QXmlStreamReaderPrivate::checkPublicLiteral(), QStandardItem::checkState(), QListWidgetItem::checkState(), QTableWidgetItem::checkState(), QTreeWidgetItem::checkState(), QDeclarativeListViewPrivate::checkVisible(), childKeysOrGroups(), QConfFileSettingsPrivate::children(), QODBCDriver::cleanup(), QDeclarativePropertyCache::clear(), QFontCache::clear(), QResourcePrivate::clear(), QFragmentMap< QTextBlockData >::clear(), QFileSystemEngine::clearWinStatData(), clipboardData(), QXlibClipboard::clipboardReadProperty(), QX11Data::clipboardReadProperty(), QFontEngine::cloneWithSize(), QXIMInputContext::close_xim(), QMacFontPath::closePath(), QImage::colorCount(), QCalendarModel::columnCount(), QScript::UStringSourceProviderWithFeedback::columnNumberFromOffset(), QDeclarativeBindingCompilerPrivate::commitCompile(), QDeclarativePropertyChangesParser::compile(), QDeclarativeObjectMethodScriptClass::connect(), QVFbScreenPrivate::connect(), QDBusConnectionPrivate::connectSignal(), QTransportAuth::connectTransport(), QDeclarativeExpression::context(), QGLPixmapGLPaintDevice::context(), QDeclarativeEngine::contextForObject(), QDeclarativeContextScriptClass::contextFromValue(), QDeclarativeContext::contextProperty(), QSizePolicy::controlType(), QWindowsMimeText::convertFromMime(), QMacPasteboardMimeHTMLText::convertFromMime(), QWindowsMimeHtml::convertFromMime(), QBuiltInMimes::convertFromMime(), QUtf16::convertFromUnicode(), QUtf32::convertFromUnicode(), QWindowsLocalCodec::convertFromUnicode(), QX11PixmapData::convertToARGB32(), QWindowsMimeText::convertToMime(), QWindowsMimeURI::convertToMime(), QWindowsMimeImage::convertToMime(), QBuiltInMimes::convertToMime(), QLastResortMimes::convertToMime(), QVectorPath::convertToPainterPath(), QMacPixmapData::copy(), QDeclarativeMetaType::copy(), QDirectFBPixmapData::copy(), QX11PixmapData::copy(), QVGPixmapData::copy(), QGLPixmapData::copy(), QTextControl::copy(), QImageData::create(), QPixmapData::create(), NamedNodeMap::create(), NodeList::create(), QGraphicsAnchorLayoutPrivate::createCenterAnchors(), QXIMInputContext::createICData(), QGraphicsAnchorLayoutPrivate::createItemEdges(), QGraphicsAnchorLayoutPrivate::createLayoutEdges(), QRuntimeGraphicsSystem::createPixmapData(), QDeclarativeVisualDataModelDataMetaObject::createProperty(), QLayoutPrivate::createSpacerItem(), QGLTextureGlyphCache::createTextureData(), QMainWindowLayout::CreateToolbarItemForIdentifier(), QUuid::createUuid(), QMacFontPath::cubicTo(), QThreadData::current(), QDeclarativeMetaType::customStringConverter(), QAxServerBase::DAdvise(), QDashStroker::dashOffset(), QPixmap::data_ptr(), QETWidget::dataPtr(), QDeclarativeTypeData::dataReceived(), QTextCodecUnalignedPointer::decode(), QDeclarativeEngineDebugPrivate::decode(), QDeclarativePropertyChangesPrivate::decode(), decodeMSG(), QSGGeometry::defaultAttributes_ColoredPoint2D(), QSGGeometry::defaultAttributes_Point2D(), QSGGeometry::defaultAttributes_TexturedPoint2D(), QSvgHandler::defaultPen(), QWSDisplay::defineCursor(), destFetchARGB32(), destFetchMono(), destFetchMonoLsb(), destFetchRGB16(), QPersistentModelIndexData::destroy(), QMetaType::destroy(), QDeclarativeObjectScriptClass::destroy(), destroy_current_thread_data(), QLocalSocketPrivate::destroyPipeHandles(), destStoreARGB32(), destStoreMono(), destStoreMonoLsb(), destStoreRGB16(), QBrush::detach(), QPainterPath::detach_helper(), QLocalePrivate::digitToCLocale(), QDeclarativeObjectMethodScriptClass::disconnect(), QObject::disconnect(), QWaylandDisplay::displayHandleGlobal(), distributeMultiBox(), QTranslatorPrivate::do_load(), do_size_hints(), QDeclarativeXmlQueryEngine::doQuery(), QDragManager::drag(), QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), QX11PaintEngine::drawFreetype(), QSvgPaintEngine::drawImage(), QDirectFBPaintEngine::drawPixmap(), QGL2PaintEngineExPrivate::drawPixmapFragments(), QDirectFBPaintEngine::drawTiledPixmap(), QDirectFBPaintEnginePrivate::drawTiledPixmap(), QOleDropTarget::Drop(), QObject::dumpObjectInfo(), QImagePixmapCleanupHooks::enableCleanupHooks(), QTextCodecUnalignedPointer::encode(), QMimeDataWrapper::encodedData(), QtopiaPrintEngine::end(), QPatternist::AccelTreeBuilder< true >::endElement(), QGLPixmapGLPaintDevice::endPaint(), QPainterPath::ensureData_helper(), QFragmentMap< QTextBlockData >::erase_single(), errorCodeToString(), escapedKey(), QOCICols::execBatch(), QScriptDebuggerCommandExecutor::execute(), QJSDebuggerAgent::executeExpression(), QCoreApplication::exit(), expandObject(), QCss::ValueExtractor::extractBackground(), QFontEngineQPA::extractHeaderField(), QFontEngineQPF::extractHeaderField(), QAudioInputPrivate::feedback(), QGL2PaintEngineExPrivate::fill(), QWSDisplay::Data::fillQueue(), QTextStreamPrivate::fillReadBuffer(), QFragmentMap< QTextBlockData >::find(), QDeclarativePropertyPrivate::findAliasTarget(), QX11Data::findClientWindow(), QFragmentMap< QTextBlockData >::findNode(), QComboBox::findText(), findXdndAwareParent(), QThreadPrivate::finish(), QDeclarativeInclude::finished(), QBspTree::firstChildIndex(), QFragmentMap< QTextBlockData >::firstNode(), fixedCDataSection(), fixedCharData(), fixedComment(), fixedPIData(), fixedPubidLiteral(), fixedSystemLiteral(), QPaintEngineEx::flags(), QMacMime::flavorToMime(), QRasterWindowSurface::flush(), flush_vme_signal(), QTextStreamPrivate::flushWriteBuffer(), QListWidgetItem::font(), QStandardItem::font(), QTableWidgetItem::font(), QTreeWidgetItem::font(), QWidget::fontInfo(), QWidget::fontMetrics(), QStandardItem::foreground(), QListWidgetItem::foreground(), QTableWidgetItem::foreground(), QTreeWidgetItem::foreground(), QMimeDataWrapper::format(), QPSQLDriver::formatValue(), QFragmentMap< QTextBlockData >::fragment(), QWaylandWindow::frameCallback(), QTextFrame::frameFormat(), QAudioOutputPrivate::freeBlocks(), QAudioInputPrivate::freeBlocks(), QDirectFBPixmapData::fromFile(), QGLPixmapData::fromFile(), QDir::fromNativeSeparators(), QXmlInputSource::fromRawData(), QUuid::fromRfc4122(), fromScriptValue(), QNetworkAccessFtpBackend::ftpReadyRead(), QDeclarativeCompiler::genLiteralAssignment(), QDeclarativeCompiler::genValueTypeData(), QThreadStorageData::get(), QConfFileSettingsPrivate::get(), get_network_interface(), QGraphicsAnchorLayoutPrivate::getAnchor(), QDeclarativeOpenMetaObjectPrivate::getData(), getData(), getFamiliesAndSignatures(), QGtkPainter::getIcon(), getImage(), getLocaleListData(), QXlibWindow::getMWMHints(), GetMWMHints(), getNetWmState(), getPixmap(), QWaylandGLContext::getProcAddress(), QWSSoundServerProvider::getSample(), QMacInputContext::globalEventProcessor(), QFontEngineQPA::glyphCount(), QFontEngineQPF::glyphCount(), QPixmap::grabWindow(), grayscale(), QWindowSystemInterface::handleEnterEvent(), QWindowSystemInterface::handleExtendedKeyEvent(), QWindowSystemInterface::handleGeometryChange(), QWindowSystemInterface::handleKeyEvent(), QWindowSystemInterface::handleLeaveEvent(), QWindowSystemInterface::handleMouseEvent(), QWidgetPrivate::handleSoftwareInputPanel(), QWaylandDisplay::handleVisual(), QWindowSystemInterface::handleWheelEvent(), QX11PixmapData::hasAlphaChannel(), QDeclarativeOpenMetaObjectPrivate::hasData(), QSizePolicy::hasHeightForWidth(), QCoreApplication::hasPendingEvents(), QSizePolicy::hasWidthForHeight(), QMacPattern::height(), QSizePolicy::horizontalPolicy(), QSizePolicy::horizontalStretch(), QPlatformCursorImage::hotspot(), QStandardItem::icon(), QListWidgetItem::icon(), QTableWidgetItem::icon(), QTreeWidgetItem::icon(), QWSClient::identity(), PvrEglWindowSurface::image(), QClipboard::image(), QDomDocumentPrivate::implementation(), QDeclarativeInclude::include(), QDeclarativeCompiledData::indexForByteArray(), QDeclarativeCompiledData::indexForString(), QDeclarativeCompiledData::indexForUrl(), QBspTree::init(), QDeclarativeBoundSignal::init(), QSqlDatabasePrivate::init(), QDeclarativeTypePrivate::init(), initEmptyMultiBox(), QRasterizer::initialize(), initializeDb(), QTestLiteStaticInfoPrivate::initializeSupportedAtoms(), QDeclarativeVisualDataModelDataMetaObject::initialValue(), QDeclarativePropertyPrivate::initProperty(), QFragmentMap< QTextBlockData >::insert_single(), QFontCache::insertEngine(), QXmlSimpleReaderPrivate::insertXmlRef(), QAbstractEventDispatcher::instance(), QWSDisplay::instance(), QDeclarativeMetaType::interfaceIId(), QModelIndex::internalId(), QtSharedPointer::internalSafetyCheckRemove(), QWidget::internalWinId(), QWidgetPrivate::invalidateBuffer_resizeHelper(), QMeeGoLivePixmapData::invalidateSurfaces(), QWSServerPrivate::invokeGetProperty(), QWidgetPrivate::isBackgroundInherited(), QXIMInputContext::isComposing(), QResourceRoot::isCompressed(), QFragmentMap< QTextBlockData >::isEmpty(), QPaintEngine::isExtended(), QHostAddress::isInSubnet(), QDeclarativeMetaType::isInterface(), QDeclarativeMetaType::isList(), QDeclarativeItemPrivate::isMirrored(), QWidget::isModal(), QDeclarativeMetaType::isModule(), QDeclarativeMetaType::isQObject(), QCopChannel::isRegistered(), QIODevicePrivate::isSequential(), QLock::isValid(), QFragmentMap< QTextBlockData >::isValid(), QDBusUtil::isValidSignature(), QDBusUtil::isValidSingleSignature(), QDeclarativeVisualDataModel::item(), QDeclarativeGridViewPrivate::itemGeometryChanged(), QWSLocalMemSurface::key(), QWSSharedMemSurface::key(), QWSOnScreenSurface::key(), QWSYellowSurface::key(), QFragmentMap< QTextBlockData >::last(), QFragmentMap< QTextBlockData >::length(), QCss::ValueExtractor::lengthValue(), libraryMap(), ligatureHelper(), QMacFontPath::lineTo(), QDeclarativeMetaType::listType(), QMetaType::load(), QDeclarativeDataLoader::load(), QAxScriptManager::load(), QResourcePrivate::load(), QImage::loadFromData(), QFontEngine::loadKerningPairs(), QDeclarativeComponent::loadUrl(), QMeeGoLivePixmapData::lock(), QLock::lock(), QLock::locked(), QFSFileEnginePrivate::longFileName(), main(), QWidgetPrivate::mapFromGlobal(), QETWidget::markFrameStrutDirty(), QFileDialogPrivate::maxNameLength(), QDeclarativeEnginePrivate::md5(), QJSDebugService::messageReceived(), QDropEvent::mimeData(), QXIMInputContext::mouseHandler(), QWidgetPrivate::moveRect(), QMacFontPath::moveTo(), QVGImagePool::moveToHeadOfLRU(), multicastMembershipHelper(), QLocale::name(), QNativeSocketEnginePrivate::nativeRead(), QNativeSocketEnginePrivate::nativeReceiveDatagram(), QNativeSocketEnginePrivate::nativeSendDatagram(), QNativeSocketEnginePrivate::nativeWrite(), QDeclarativeDataLoader::networkReplyFinished(), QDeclarativeListScriptClass::newList(), QScriptEnginePrivate::newQObject(), QFragmentMap< QTextBlockData >::next(), QUrlPrivate::normalized(), QFragmentMap< QTextBlockData >::numNodes(), QTtfStream::offset(), QODBCDriver::open(), quint32p::operator quint16(), qargb8565::operator quint16(), qrgb565::operator quint16(), qrgb555::operator quint16(), quint32p::operator quint32(), qargb8565::operator quint32(), qrgb565::operator quint32(), qargb8555::operator quint32(), qrgb555::operator quint32(), qargb6666::operator quint32(), qrgb666::operator quint32(), qrgb888::operator quint32(), quint24::operator quint32(), quint18::operator quint32(), qargb4444::operator quint32(), qrgb444::operator quint32(), QSslCertificate::operator!=(), QPatternist::NodeIndexStorage::operator!=(), QPersistentModelIndex::operator!=(), QSizePolicy::operator!=(), qrgb555::operator!=(), qrgb444::operator!=(), qargb8565::operator+(), qrgb565::operator+(), qargb8555::operator+(), qrgb555::operator+(), qargb6666::operator+(), qrgb666::operator+(), qargb4444::operator+(), qrgb444::operator+(), QTextBlock::operator<(), operator<<(), QTtfStream::operator<<(), QUuid::operator<<(), QDBusReply< QStringList >::operator=(), QPaintBuffer::operator=(), QPainterPath::operator=(), QSizePolicy::operator==(), qabgr8888::operator==(), qargb8565::operator==(), qrgb565::operator==(), qbgr565::operator==(), qargb8555::operator==(), qrgb555::operator==(), qbgr555::operator==(), qargb6666::operator==(), qrgb666::operator==(), qrgb888::operator==(), quint24::operator==(), qargb4444::operator==(), qrgb444::operator==(), QUuid::operator>>(), QVector< QPoint >::operator[](), QWaylandDisplay::outputHandleGeometry(), QX11PixmapData::paintEngine(), QGLPixmapGLPaintDevice::paintEngine(), QCompletionModel::parent(), QDeclarativeMetaType::parentFunctions(), QPdf::patternForBrush(), QProcessPrivate::pipeWriterBytesToWrite(), QClipboard::pixmap(), QTextDocumentPrivate::plainText(), QFragmentMap< QTextBlockData >::position(), QScriptDebuggerAgent::positionChange(), QCoreApplication::postEvent(), postEventSourcePrepare(), QWSSoundServerProvider::prepareBuffer(), QFragmentMap< QTextBlockData >::previous(), QThread::priority(), priv(), QCoreApplication::processEvents(), QDeclarativeWorkerScriptEnginePrivate::processLoad(), QXmlNamespaceSupport::processName(), QPatternist::NamespaceSupport::processName(), QDeclarativeBindingCompiler::program(), QMacPasteboard::promiseKeeper(), QDeclarativeListScriptClass::property(), QWin32PrintEngine::property(), QTextStreamPrivate::putString(), qabgr8888::qabgr8888(), QAbstractItemModelPrivate::QAbstractItemModelPrivate(), qargb4444::qargb4444(), qargb6666::qargb6666(), qargb8555::qargb8555(), qargb8565::qargb8565(), qbgr555::qbgr555(), qbgr565::qbgr565(), QSslCertificatePrivate::QByteArray_from_X509(), QByteArray::qChecksum(), QColorToOLEColor(), qDBusAddTimeout(), qDBusAddWatch(), qDBusNewConnection(), qDBusRemoveTimeout(), qDBusRemoveWatch(), qDBusSignalFilter(), qDBusToggleWatch(), qDBusUpdateDispatchStatus(), QDeclarativeContext::QDeclarativeContext(), QDeclarativeListReference::QDeclarativeListReference(), qDecodeDataUrl(), QDomCharacterDataPrivate::QDomCharacterDataPrivate(), qDrawBorderPixmap(), QFontEngineMac::QFontEngineMac(), QFontEngineQPF::QFontEngineQPF(), QFontEngineQPF1::QFontEngineQPF1(), qGeomCalc(), qGetODBCVersion(), QGL2PaintEngineExPrivate::QGL2PaintEngineExPrivate(), QHttpNormalRequest::QHttpNormalRequest(), QImage::QImage(), qInitImageConversions(), QLock::QLock(), QMacPasteboardMimeHTMLText::QMacPasteboardMimeHTMLText(), QMacPasteboardMimePlainText::QMacPasteboardMimePlainText(), QMacPasteboardMimeUnicodeText::QMacPasteboardMimeUnicodeText(), QMacPattern::QMacPattern(), QMatrix4x4::QMatrix4x4(), qmlAttachedPropertiesObjectById(), QDeclarativeMetaType::qmlComponents(), qmlExecuteDeferred(), QDeclarativeMetaType::qmlType(), QDeclarativeMetaType::qmlTypeNames(), QDeclarativeMetaType::qmlTypes(), qmlxmlhttprequest_send(), QScriptEnginePrivate::qobjectData(), QPAGenerator::QPAGenerator(), QPFGenerator::QPFGenerator(), QPFGlyph::QPFGlyph(), QPlatformCursorImage::QPlatformCursorImage(), QRfbDualColorHextile< SRC >::QRfbDualColorHextile(), QRfbMultiColorHextile< SRC >::QRfbMultiColorHextile(), QRfbSingleColorHextile< SRC >::QRfbSingleColorHextile(), qrgb444::qrgb444(), qrgb555::qrgb555(), qrgb565::qrgb565(), qrgb666::qrgb666(), qrgb888::qrgb888(), qstring_to_xtp(), qsvg_get_hex_rgb(), qt_adopted_thread_watcher_function(), qt_blend_color_argb_x86(), qt_create_commandline(), qt_directfb_surface_for_pixmap(), qt_fetch_radial_gradient_plain(), qt_get_net_supported(), qt_get_net_virtual_roots(), qt_keypress_scanner(), qt_keyrelease_scanner(), QFileDialogPrivate::qt_mac_filedialog_event_proc(), QFileDialogPrivate::qt_mac_filedialog_filter_proc(), qt_mac_flipPixmap(), qt_matchLibraryName(), qt_mouseMotion_scanner(), qt_nameprep(), qt_parse_pattern(), qt_read_dibv5(), qt_save_rootinfo(), qt_set_input_encoding(), qt_set_x11_resources(), qt_socks5_set_host_address_and_port(), qt_socks5_set_host_name_and_port(), qt_sync_request_scanner(), qt_tabletMotion_scanner(), qt_toRasterPixmap(), qt_toX11Pixmap(), qt_wstate_iconified(), qt_x11_drawImage(), qt_xfixes_scanner(), QThreadStorageData::QThreadStorageData(), QMainWindowLayout::qtmacToolbarDelegate(), QMainWindowLayout::qtoolbarInHIToolbarHandler(), QTtfStream::QTtfStream(), QDeclarativeTypeNameScriptClass::queryProperty(), QDeclarativeContextScriptClass::queryProperty(), QDeclarativeObjectScriptClass::queryProperty(), QAxBase::querySubObject(), quint18::quint18(), quint24::quint24(), QUnixSocketMessage::QUnixSocketMessage(), QUuid::QUuid(), QVariantToVARIANT(), QVideoFrame::QVideoFrame(), QWaylandShmBuffer::QWaylandShmBuffer(), qwsClipboardText(), QWSCursor::QWSCursor(), QWSSetPropertyCommand::QWSSetPropertyCommand(), QWSSoundServerProvider::QWSSoundServerProvider(), QXIMInputContext::QXIMInputContext(), QXmlStreamReader::QXmlStreamReader(), QRasterPaintEnginePrivate::rasterize(), qargb8565::rawValue(), qrgb565::rawValue(), qargb8555::rawValue(), qrgb555::rawValue(), qargb6666::rawValue(), qrgb666::rawValue(), qrgb888::rawValue(), qargb4444::rawValue(), qrgb444::rawValue(), qargb8565::rawValue16(), QSvgIconEngine::read(), QIODevice::read(), QUnixSocket::read(), QRfbSingleColorHextile< SRC >::read(), QRfbDualColorHextile< SRC >::read(), QRfbMultiColorHextile< SRC >::read(), read8(), read_dib_body(), QProcess::readAllStandardError(), QProcess::readAllStandardOutput(), QAbstractSocket::readData(), QPFGlyphTree::readData(), QWinSettingsPrivate::readKey(), QNetworkAccessFileBackend::readMoreFromFile(), QLinuxInputMouseHandler::readMouseData(), QWSLinuxInputMousePrivate::readMouseData(), QWSLinuxTPMouseHandlerPrivate::readMouseData(), QPngHandlerPrivate::readPngImage(), readValue(), QDeclarativePropertyPrivate::readValueProperty(), QPatternist::XsdSchemaParser::readXPathAttribute(), QJSDebuggerAgentPrivate::recordKnownObjects(), QGraphicsAnchorLayoutPrivate::refreshAllSizeHints(), registerAutoParentFunction(), QDeclarativeMetaType::registerCustomStringConverter(), registerFont(), registerInterface(), QDeclarativeBindingCompilerPrivate::registerLiteralString(), QPlatformFontDatabase::registerQPF2Font(), QDeclarativeBindingCompilerPrivate::registerString(), registerType(), QMdi::ControlContainer::removeButtonsFromMenuBar(), QGraphicsAnchorLayoutPrivate::removeCenterAnchors(), Graph< AnchorVertex, AnchorData >::removeEdge(), QDeclarativeAbstractBinding::removeFromObject(), removeGroupSeparators(), QCoreApplicationPrivate::removePostedEvent(), QCoreApplication::removePostedEvents(), QCoreApplicationPrivate::removePostedTimerEvent(), QWidgetPrivate::repaint_sys(), QVector< QPoint >::replace(), QXIMInputContext::reset(), QDeclarativeBindingCompilerPrivate::resetInstanceState(), QVarLengthGlyphLayoutArray::resize(), QDeclarativePropertyPrivate::restore(), QGraphicsAnchorLayoutPrivate::restoreSimplifiedAnchor(), QWaylandXCompositeGLXIntegration::rootInformation(), QWaylandXCompositeEGLIntegration::rootInformation(), QDeclarativeCompiledBindingsPrivate::run(), QOstDevicePrivate::RunL(), runlengthEncode(), QMetaType::save(), QAxServerBase::Save(), QDomDocumentPrivate::saveDocument(), QWaylandDisplay::screens(), QScriptEnginePrivate::scriptConnect(), QScriptEnginePrivate::scriptDisconnect(), QScriptDebuggerAgent::scriptLoad(), QScriptDebuggerAgent::scriptUnload(), QWidgetPrivate::scrollRect(), QCopChannel::send(), QWaylandSelection::send(), QDeclarativeXMLHttpRequest::send(), send_selection(), QJSDebugService::sendMessages(), QDeclarativeDebugTrace::sendMessages(), QCoreApplicationPrivate::sendPostedEvents(), QCoreApplication::sendPostedEvents(), QWSServerPrivate::sendQCopEvent(), QXlibClipboard::sendSelection(), Graph< AnchorVertex, AnchorData >::serializeToDot(), QThreadStorageData::set(), set_thread_data(), QWidget::setBaseSize(), QDeclarativePropertyPrivate::setBinding(), QDeclarativePropertyPrivate::setBindingNoEnable(), QHttpPartPrivate::setBody(), QScriptDebuggerAgent::setBreakpoint(), QScriptDebuggerAgent::setBreakpointData(), QTextControlPrivate::setClipboardSelection(), QBrush::setColor(), QDeclarativeEngine::setContextForObject(), QDeclarativeContext::setContextObject(), QDeclarativeContext::setContextProperty(), QSizePolicy::setControlType(), QStrokerOps::setCubicToHook(), QTestResult::setCurrentGlobalTestData(), QTestResult::setCurrentTestData(), QDeclarativeConnectionsParser::setCustomData(), QDeclarativePropertyChangesParser::setCustomData(), QWSProtocolItem::setData(), QWSRegionCommand::setData(), QWSPropertyReplyEvent::setData(), QWSQCopMessageEvent::setData(), QWSSetPropertyCommand::setData(), QWSDefineCursorCommand::setData(), QWSQCopSendCommand::setData(), QXIMInputContext::setFocusWidget(), QWidgetPrivate::setFont_helper(), QX11WindowSurface::setGeometry(), QWidget::setGeometry(), QFontEngine::setGlyphCache(), QSizePolicy::setHeightForWidth(), QSizePolicy::setHorizontalPolicy(), QSizePolicy::setHorizontalStretch(), QDeclarativeContextData::setIdPropertyData(), QClipboard::setImage(), QTextFrame::setLayoutData(), QDeclarativeListAccessor::setList(), QWSQCopSendCommand::setMessage(), QXlibClipboard::setMimeData(), QBBClipboard::setMimeData(), QDrag::setMimeData(), QGraphicsSceneDragDropEvent::setMimeData(), QTtfStream::setOffset(), QDeclarativeContextScriptClass::setOverrideObject(), QImage::setPixel(), QClipboard::setPixmap(), QGLPixmapGLPaintDevice::setPixmapData(), QFragmentMap< QTextBlockData >::setSize(), QListWidgetItem::setSizeHint(), QTableWidgetItem::setSizeHint(), QTreeWidgetItem::setSizeHint(), QClipboard::setText(), QBrush::setTexture(), QBrush::setTextureImage(), QGraphicsItem::setTransformOriginPoint(), QNetworkReplyImplPrivate::setup(), QTextBlock::setUserData(), QObject::setUserData(), QSizePolicy::setVerticalPolicy(), QSizePolicy::setVerticalStretch(), QSizePolicy::setWidthForHeight(), QDeclarativePixmapStore::shrinkCache(), QWSWindow::shuttingDown(), QAbstractItemModel::sibling(), QGraphicsAnchorLayoutPrivate::simplifyGraphIteration(), QGraphicsAnchorLayoutPrivate::simplifyVertices(), QGLPixmapGLPaintDevice::size(), QFragmentMap< QTextBlockData >::size(), QStandardItem::sizeHint(), QListWidgetItem::sizeHint(), QTableWidgetItem::sizeHint(), QTreeWidgetItem::sizeHint(), QHttpSocketEngine::slotSocketConnected(), QAuBucketQWS::sound(), QHttpNormalRequest::sourceDevice(), QWaylandDisplay::sourceUpdate(), QString::squeeze(), QThreadPrivate::start(), QHttpNormalRequest::start(), QTextControlPrivate::startDrag(), QPatternist::AccelTreeBuilder< true >::startElement(), QStandardItem::statusTip(), QListWidgetItem::statusTip(), QTableWidgetItem::statusTip(), QTreeWidgetItem::statusTip(), QSortFilterProxyModelPrivate::store_persistent_indexes(), QFontEngineXLFD::stringToCMap(), QDeclarativeVisualDataModel::stringValue(), QSystemLocalePrivate::substituteDigits(), QRawFont::supportedWritingSystems(), QVGPaintEngine::supportsTransformations(), QByteArray::swap(), QVariant::swap(), QWaylandXCompositeEGLContext::sync_function(), QWaylandXCompositeGLXContext::sync_function(), QWaylandClipboard::syncCallback(), QConfFileSettingsPrivate::syncConfFile(), QFontEngineWin::synthesized(), QSslSocketPrivate::systemCaCertificates(), QODBCDriver::tables(), Graph< AnchorVertex, AnchorData >::takeEdge(), QWidget::testAttribute(), QStandardItem::text(), QClipboard::text(), QListWidgetItem::text(), QTableWidgetItem::text(), QTreeWidgetItem::text(), QListWidgetItem::textAlignment(), QStandardItem::textAlignment(), QTableWidgetItem::textAlignment(), QTreeWidgetItem::textAlignment(), QListWidgetItem::textColor(), QTableWidgetItem::textColor(), QTreeWidgetItem::textColor(), QDeclarativeDebugData::toByteArray(), JSAgentCoverageData::toByteArray(), QUuid::toByteArray(), QDBusDemarshaller::toByteArrayUnchecked(), QDBusMessagePrivate::toDBusMessage(), QRasterPixmapData::toImage(), QGLPixmapData::toImage(), QProcessEnvironmentPrivate::toList(), QDir::toNativeSeparators(), QStandardItem::toolTip(), QListWidgetItem::toolTip(), QTableWidgetItem::toolTip(), QTreeWidgetItem::toolTip(), QSslKey::toPem(), QDeclarativeObjectScriptClass::toQObject(), QMetaObjectBuilder::toRelocatableData(), QUuid::toRfc4122(), QUuid::toString(), XsdSchemaToken::toString(), QPatternist::XSLTTokenLookup::toString(), QFontEngineXLFD::toUnicode(), QTextDecoder::toUnicode(), QDeclarativeListScriptClass::toVariant(), QScriptDebuggerBackendPrivate::trace(), QPaintBufferEngine::transformChanged(), QDirectFBPixmapData::transformed(), QX11PixmapData::transformed(), QDeclarativePropertyAction::transition(), QDeclarativePropertyAnimation::transition(), QDeclarativeParentAnimation::transition(), QDeclarativeAnchorAnimation::transition(), QETWidget::translateConfigEvent(), QWSInputContext::translateIMEvent(), translateKeyEventInternal(), QETWidget::translatePaintEvent(), QETWidget::translatePropertyEvent(), QSslSocketBackendPrivate::transmit(), qargb8565::truncedAlpha(), qargb8555::truncedAlpha(), QDeclarativeMetaType::typeCategory(), QLock::unlock(), QDeclarativePixmapStore::unreferencePixmap(), QDeclarativeBoundSignal::unregisterScopeObject(), QXIMInputContext::update(), QAccessible::updateAccessibility(), QX11PaintEngine::updateBrush(), QWSSoundServerProvider::updateBuffer(), QDeclarativeContextScriptClass::urlFromValue(), QMap< Key, T >::iterator::value(), QMap< Key, T >::const_iterator::value(), VARIANTToQVariant(), QFontEngineQPA::verifyHeader(), QFontEngineQPF::verifyHeader(), QSizePolicy::verticalPolicy(), QSizePolicy::verticalStretch(), QIconEngineV2::virtual_hook(), QPixmapIconEngine::virtual_hook(), QIconLoaderEngine::virtual_hook(), QSocks5SocketEnginePrivate::waitForConnected(), QNetworkAccessHttpBackend::wantUploadDataSlot(), QStandardItem::whatsThis(), QListWidgetItem::whatsThis(), QTableWidgetItem::whatsThis(), QTreeWidgetItem::whatsThis(), QXIMInputContext::widgetDestroyed(), QMacPattern::width(), QWidget::windowFlags(), QWidget::windowType(), QWaylandXCompositeGLXIntegration::wlDisplayHandleGlobal(), QWaylandXCompositeEGLIntegration::wlDisplayHandleGlobal(), QWaylandWindowManagerIntegration::wlHandleListenerGlobal(), QDeclarativeInclude::worker_include(), QIODevice::write(), QTextStreamPrivate::write(), write_jpeg_image(), QDeclarativeOpenMetaObjectPrivate::writeData(), QAbstractSocket::writeData(), QFile::writeData(), QPAGenerator::writeHeader(), QPFGenerator::writeHeader(), QPNGImageWriter::writeImage(), QTextOdfWriter::writeInlineCharacter(), QDeclarativePropertyPrivate::writeValueProperty(), QXIMInputContext::x11FilterEvent(), QWidgetPrivate::x11UpdateIsOpaque(), xic_draw_callback(), xic_start_callback(), QFontEngineFT::Glyph::~Glyph(), QOCICols::OraFieldInf::~OraFieldInf(), QChildEvent::~QChildEvent(), QConfFileSettingsPrivate::~QConfFileSettingsPrivate(), QCopChannel::~QCopChannel(), QCoreApplicationData::~QCoreApplicationData(), QCoreApplicationPrivate::~QCoreApplicationPrivate(), QFragmentMap< QTextBlockData >::~QFragmentMap(), QGLFontTexture::~QGLFontTexture(), QHttpNetworkHeader::~QHttpNetworkHeader(), QHttpNormalRequest::~QHttpNormalRequest(), QKeyMapperPrivate::~QKeyMapperPrivate(), QListModelInterface::~QListModelInterface(), QLock::~QLock(), QMacPasteboardMimeAny::~QMacPasteboardMimeAny(), QMacPasteboardMimeTypeName::~QMacPasteboardMimeTypeName(), QScriptMessageHandlerInterface::~QScriptMessageHandlerInterface(), QXmlContentHandler::~QXmlContentHandler(), and QXmlDefaultHandler::~QXmlDefaultHandler().
 {
     return arr.isEmpty() ? 0 : arr.constData();
 }
debugVariantList()
static void debugVariantList (QDebug dbg, const QVariantList & list) static
Definition at line 800 of file qdbusmessage.cpp.
Referenced by operator<<().
 {
     bool first = true;
     QVariantList::ConstIterator it = list.constBegin();
     QVariantList::ConstIterator end = list.constEnd();
     for ( ; it != end; ++it) {
         if (!first)
             dbg.nospace() << ", ";
         dbg.nospace() << qPrintable(QDBusUtil::argumentToString(*it));
         first = false;
     }
 }
operator<<() [1/2]
static QDebug operator<< (QDebug dbg, QDBusMessage::MessageType t) static
Sends the message without waiting for a reply.
This is suitable for errors, signals, and return values as well as calls whose return values are not necessary.
Returns true if the message was queued successfully; otherwise returns false.
See also
QDBusConnection::send()
Definition at line 783 of file qdbusmessage.cpp.
 {
     switch (t)
     {
     case QDBusMessage::MethodCallMessage:
         return dbg << "MethodCall";
     case QDBusMessage::ReplyMessage:
         return dbg << "MethodReturn";
     case QDBusMessage::SignalMessage:
         return dbg << "Signal";
     case QDBusMessage::ErrorMessage:
         return dbg << "Error";
     default:
         return dbg << "Invalid";
     }
 }
operator<<() [2/2]
QDebug operator<< (QDebug dbg, const QDBusMessage & msg)
Definition at line 813 of file qdbusmessage.cpp.
Referenced by QDBusMessage::createErrorReply().
 {
     dbg.nospace() << "QDBusMessage(type=" << msg.type()
                   << ", service=" << msg.service();
     if (msg.type() == QDBusMessage::MethodCallMessage ||
         msg.type() == QDBusMessage::SignalMessage)
         dbg.nospace() << ", path=" << msg.path()
                       << ", interface=" << msg.interface()
                       << ", member=" << msg.member();
     if (msg.type() == QDBusMessage::ErrorMessage)
         dbg.nospace() << ", error name=" << msg.errorName()
                       << ", error message=" << msg.errorMessage();
     dbg.nospace() << ", signature=" << msg.signature()
                   << ", contents=(";
     debugVariantList(dbg, msg.arguments());
     dbg.nospace() << ") )";
     return dbg.space();
 }