Qt 4.8: /src/dbus/qdbusabstractadaptor.cpp File Reference
qdbusabstractadaptor.cpp File Reference
#include "qdbusabstractadaptor.h"
#include <QtCore/qcoreapplication.h>
#include <QtCore/qmetaobject.h>
#include <QtCore/qset.h>
#include <QtCore/qtimer.h>
#include <QtCore/qthread.h>
#include "qdbusconnection.h"
#include "qdbusconnection_p.h"
#include "qdbusabstractadaptor_p.h"
#include "qdbusmetatype_p.h"
Functions
QDBusAdaptorConnector * qDBusCreateAdaptorConnector (QObject *obj)
QDBusAdaptorConnector * qDBusFindAdaptorConnector (QObject *obj)
QDBusAdaptorConnector * qDBusFindAdaptorConnector (QDBusAbstractAdaptor *adaptor)
Variables
static const uint qt_meta_data_QDBusAdaptorConnector []
static const char qt_meta_stringdata_QDBusAdaptorConnector []
Function Documentation
qDBusCreateAdaptorConnector()
QDBusAdaptorConnector* qDBusCreateAdaptorConnector (QObject * obj)
Definition at line 82 of file qdbusabstractadaptor.cpp.
Referenced by QDBusAbstractAdaptor::QDBusAbstractAdaptor(), and QDBusConnectionPrivate::registerObject().
 {
     QDBusAdaptorConnector *connector = qDBusFindAdaptorConnector(obj);
     if (connector)
         return connector;
     return new QDBusAdaptorConnector(obj);
 }
qDBusFindAdaptorConnector() [1/2]
QDBusAdaptorConnector* qDBusFindAdaptorConnector (QObject * obj)
Definition at line 60 of file qdbusabstractadaptor.cpp.
Referenced by QDBusConnectionPrivate::activateObject(), qDBusCreateAdaptorConnector(), qDBusFindAdaptorConnector(), qDBusIntrospectObject(), qDBusPropertyGet(), qDBusPropertyGetAll(), and qDBusPropertySet().
 {
     if (!obj)
         return 0;
     const QObjectList &children = obj->children();
     QObjectList::ConstIterator it = children.constBegin();
     QObjectList::ConstIterator end = children.constEnd();
     for ( ; it != end; ++it) {
         QDBusAdaptorConnector *connector = qobject_cast<QDBusAdaptorConnector *>(*it);
         if (connector) {
             connector->polish();
             return connector;
         }
     }
     return 0;
 }
qDBusFindAdaptorConnector() [2/2]
QDBusAdaptorConnector* qDBusFindAdaptorConnector (QDBusAbstractAdaptor * adaptor)
Definition at line 77 of file qdbusabstractadaptor.cpp.
 {
     return qDBusFindAdaptorConnector(adaptor->parent());
 }
Variable Documentation
qt_meta_data_QDBusAdaptorConnector
const uint qt_meta_data_QDBusAdaptorConnector[] static
Initial value:
= {
       1,
       0,
       0,    0,
       3,   10,
       0,    0,
       0,    0,
     106,   22,   22,   22, 0x0a,
     118,   22,   22,   22, 0x0a,
      47,   23,   22,   22, 0x05,
       0
}
Definition at line 327 of file qdbusabstractadaptor.cpp.
qt_meta_stringdata_QDBusAdaptorConnector
const char qt_meta_stringdata_QDBusAdaptorConnector[] static
Initial value:
= {
    "QDBusAdaptorConnector\0\0obj,metaobject,sid,args\0"
    "relaySignal(QObject*,const QMetaObject*,int,QVariantList)\0\0relaySlot()\0"
    "polish()\0"
}
Definition at line 346 of file qdbusabstractadaptor.cpp.