Qt 4.8: /src/dbus/qdbusinternalfilters.cpp File Reference
qdbusinternalfilters.cpp File Reference
#include "qdbusconnection_p.h"
#include "qdbus_symbols_p.h"
#include <QtCore/qcoreapplication.h>
#include <QtCore/qmetaobject.h>
#include <QtCore/qstringlist.h>
#include <QtCore/qthread.h>
#include "qdbusabstractadaptor.h"
#include "qdbusabstractadaptor_p.h"
#include "qdbusconnection.h"
#include "qdbusextratypes.h"
#include "qdbusmessage.h"
#include "qdbusmetatype.h"
#include "qdbusmetatype_p.h"
#include "qdbusmessage_p.h"
#include "qdbusutil_p.h"
#include "qdbusvirtualobject.h"
Enumerations
enum PropertyWriteResult { PropertyWriteSuccess = 0, PropertyNotFound, PropertyTypeMismatch, PropertyWriteFailed }
Functions
static QString generateSubObjectXml (QObject *object)
static QDBusMessage interfaceNotFoundError (const QDBusMessage &msg, const QString &interface_name)
static QVariantMap & operator+= (QVariantMap &lhs, const QVariantMap &rhs)
static QDBusMessage propertyNotFoundError (const QDBusMessage &msg, const QString &interface_name, const QByteArray &property_name)
static QDBusMessage propertyWriteReply (const QDBusMessage &msg, const QString &interface_name, const QByteArray &property_name, int status)
QString qDBusGenerateMetaObjectXml (QString interface, const QMetaObject *mo, const QMetaObject *base, int flags)
QString qDBusIntrospectObject (const QDBusConnectionPrivate::ObjectTreeNode &node, const QString &path)
QDBusMessage qDBusPropertyGet (const QDBusConnectionPrivate::ObjectTreeNode &node, const QDBusMessage &msg)
QDBusMessage qDBusPropertyGetAll (const QDBusConnectionPrivate::ObjectTreeNode &node, const QDBusMessage &msg)
QDBusMessage qDBusPropertySet (const QDBusConnectionPrivate::ObjectTreeNode &node, const QDBusMessage &msg)
static QVariantMap readAllProperties (QObject *object, int flags)
static int writeProperty (QObject *obj, const QByteArray &property_name, QVariant value, int propFlags=QDBusConnection::ExportAllProperties)
Variables
static const char introspectableInterfaceXml []
static const char peerInterfaceXml []
static const char propertiesInterfaceXml []
Enumeration Type Documentation
PropertyWriteResult
enum PropertyWriteResult
Enumerator
PropertyWriteSuccess
PropertyNotFound
PropertyTypeMismatch
PropertyWriteFailed
Definition at line 285 of file qdbusinternalfilters.cpp.
{
     PropertyWriteSuccess = 0,
     PropertyNotFound,
     PropertyTypeMismatch,
     PropertyWriteFailed
 };
Function Documentation
generateSubObjectXml()
static QString generateSubObjectXml (QObject * object) static
Definition at line 103 of file qdbusinternalfilters.cpp.
Referenced by qDBusIntrospectObject().
 {
     QString retval;
     const QObjectList &objs = object->children();
     QObjectList::ConstIterator it = objs.constBegin();
     QObjectList::ConstIterator end = objs.constEnd();
     for ( ; it != end; ++it) {
         QString name = (*it)->objectName();
         if (!name.isEmpty() && QDBusUtil::isValidPartOfObjectPath(name))
             retval += QString::fromLatin1("  <node name=\"%1\"/>\n")
                       .arg(name);
     }
     return retval;
 }
interfaceNotFoundError()
static QDBusMessage interfaceNotFoundError (const QDBusMessage & msg, const QString & interface_name) inline static
Definition at line 198 of file qdbusinternalfilters.cpp.
Referenced by qDBusPropertyGet(), qDBusPropertyGetAll(), and qDBusPropertySet().
 {
     return msg.createErrorReply(QDBusError::UnknownInterface,
                                 QString::fromLatin1("Interface %1 was not found in object %2")
                                 .arg(interface_name)
                                 .arg(msg.path()));
 }
operator+=()
static QVariantMap& operator+= (QVariantMap & lhs, const QVariantMap & rhs) static
Definition at line 423 of file qdbusinternalfilters.cpp.
 {
     QVariantMap::ConstIterator it = rhs.constBegin(),
                               end = rhs.constEnd();
     for ( ; it != end; ++it)
         lhs.insert(it.key(), it.value());
     return lhs;
 }
propertyNotFoundError()
static QDBusMessage propertyNotFoundError (const QDBusMessage & msg, const QString & interface_name, const QByteArray & property_name) inline static
Definition at line 207 of file qdbusinternalfilters.cpp.
Referenced by propertyWriteReply(), and qDBusPropertyGet().
 {
     return msg.createErrorReply(QDBusError::InvalidArgs,
                                 QString::fromLatin1("Property %1%2%3 was not found in object %4")
                                 .arg(interface_name,
                                      QString::fromLatin1(interface_name.isEmpty() ? "" : "."),
                                      QString::fromLatin1(property_name),
                                      msg.path()));
 }
propertyWriteReply()
static QDBusMessage propertyWriteReply (const QDBusMessage & msg, const QString & interface_name, const QByteArray & property_name, int status) static
Definition at line 292 of file qdbusinternalfilters.cpp.
Referenced by qDBusPropertySet().
 {
     switch (status) {
     case PropertyNotFound:
         return propertyNotFoundError(msg, interface_name, property_name);
     case PropertyTypeMismatch:
         return msg.createErrorReply(QDBusError::InvalidArgs,
                                     QString::fromLatin1("Invalid arguments for writing to property %1%2%3")
                                     .arg(interface_name,
                                          QString::fromLatin1(interface_name.isEmpty() ? "" : "."),
                                          QString::fromLatin1(property_name)));
     case PropertyWriteFailed:
         return msg.createErrorReply(QDBusError::InternalError,
                                     QString::fromLatin1("Internal error"));
     case PropertyWriteSuccess:
         return msg.createReply();
     }
     Q_ASSERT_X(false, "", "Should not be reached");
     return QDBusMessage();
 }
qDBusGenerateMetaObjectXml()
QString qDBusGenerateMetaObjectXml (QString interface, const QMetaObject * mo, const QMetaObject * base, int flags)
Definition at line 236 of file qdbusxmlgenerator.cpp.
Referenced by qDBusIntrospectObject().
 {
     if (interface.isEmpty())
         // generate the interface name from the meta object
         interface = qDBusInterfaceFromMetaObject(mo);
     QString xml;
     int idx = mo->indexOfClassInfo(QCLASSINFO_DBUS_INTROSPECTION);
     if (idx >= mo->classInfoOffset())
         return QString::fromUtf8(mo->classInfo(idx).value());
     else
         xml = generateInterfaceXml(mo, flags, base->methodCount(), base->propertyCount());
     if (xml.isEmpty())
         return QString();       // don't add an empty interface
     return QString::fromLatin1("  <interface name=\"%1\">\n%2  </interface>\n")
         .arg(interface, xml);
 }
qDBusIntrospectObject()
QString qDBusIntrospectObject (const QDBusConnectionPrivate::ObjectTreeNode & node, const QString & path)
Definition at line 120 of file qdbusinternalfilters.cpp.
Referenced by QDBusConnectionPrivate::activateInternalFilters().
 {
     // object may be null
     QString xml_data(QLatin1String(DBUS_INTROSPECT_1_0_XML_DOCTYPE_DECL_NODE));
     xml_data += QLatin1String("<node>\n");
     if (node.obj) {
         Q_ASSERT_X(QThread::currentThread() == node.obj->thread(),
                    "QDBusConnection: internal threading error",
                    "function called for an object that is in another thread!!");
         if (node.flags & (QDBusConnection::ExportScriptableContents
                            | QDBusConnection::ExportNonScriptableContents)) {
             // create XML for the object itself
             const QMetaObject *mo = node.obj->metaObject();
             for ( ; mo != &QObject::staticMetaObject; mo = mo->superClass())
                 xml_data += qDBusGenerateMetaObjectXml(QString(), mo, mo->superClass(),
                                                        node.flags);
         }
         // does this object have adaptors?
         QDBusAdaptorConnector *connector;
         if (node.flags & QDBusConnection::ExportAdaptors &&
             (connector = qDBusFindAdaptorConnector(node.obj))) {
             // trasverse every adaptor in this object
             QDBusAdaptorConnector::AdaptorMap::ConstIterator it = connector->adaptors.constBegin();
             QDBusAdaptorConnector::AdaptorMap::ConstIterator end = connector->adaptors.constEnd();
             for ( ; it != end; ++it) {
                 // add the interface:
                 QString ifaceXml = QDBusAbstractAdaptorPrivate::retrieveIntrospectionXml(it->adaptor);
                 if (ifaceXml.isEmpty()) {
                     // add the interface's contents:
                     ifaceXml += qDBusGenerateMetaObjectXml(QString::fromLatin1(it->interface),
                                                            it->adaptor->metaObject(),
                                                            &QDBusAbstractAdaptor::staticMetaObject,
                                                            QDBusConnection::ExportScriptableContents
                                                            | QDBusConnection::ExportNonScriptableContents);
                     QDBusAbstractAdaptorPrivate::saveIntrospectionXml(it->adaptor, ifaceXml);
                 }
                 xml_data += ifaceXml;
             }
         }
         // is it a virtual node that handles introspection itself?
         if (node.flags & QDBusConnectionPrivate::VirtualObject) {
             xml_data += node.treeNode->introspect(path);
         }
         xml_data += QLatin1String( propertiesInterfaceXml );
     }
     xml_data += QLatin1String( introspectableInterfaceXml );
     xml_data += QLatin1String( peerInterfaceXml );
     if (node.flags & QDBusConnection::ExportChildObjects) {
         xml_data += generateSubObjectXml(node.obj);
     } else {
         // generate from the object tree
         QDBusConnectionPrivate::ObjectTreeNode::DataList::ConstIterator it =
             node.children.constBegin();
         QDBusConnectionPrivate::ObjectTreeNode::DataList::ConstIterator end =
             node.children.constEnd();
         for ( ; it != end; ++it)
             if (it->obj || !it->children.isEmpty())
                 xml_data += QString::fromLatin1("  <node name=\"%1\"/>\n")
                             .arg(it->name);
     }
     xml_data += QLatin1String("</node>\n");
     return xml_data;
 }
qDBusPropertyGet()
QDBusMessage qDBusPropertyGet (const QDBusConnectionPrivate::ObjectTreeNode & node, const QDBusMessage & msg)
Definition at line 217 of file qdbusinternalfilters.cpp.
Referenced by QDBusConnectionPrivate::activateInternalFilters().
 {
     Q_ASSERT(msg.arguments().count() == 2);
     Q_ASSERT_X(!node.obj || QThread::currentThread() == node.obj->thread(),
                "QDBusConnection: internal threading error",
                "function called for an object that is in another thread!!");
     QString interface_name = msg.arguments().at(0).toString();
     QByteArray property_name = msg.arguments().at(1).toString().toUtf8();
     QDBusAdaptorConnector *connector;
     QVariant value;
     bool interfaceFound = false;
     if (node.flags & QDBusConnection::ExportAdaptors &&
         (connector = qDBusFindAdaptorConnector(node.obj))) {
         // find the class that implements interface_name or try until we've found the property
         // in case of an empty interface
         if (interface_name.isEmpty()) {
             for (QDBusAdaptorConnector::AdaptorMap::ConstIterator it = connector->adaptors.constBegin(),
                  end = connector->adaptors.constEnd(); it != end; ++it) {
                 const QMetaObject *mo = it->adaptor->metaObject();
                 int pidx = mo->indexOfProperty(property_name);
                 if (pidx != -1) {
                     value = mo->property(pidx).read(it->adaptor);
                     break;
                 }
             }
         } else {
             QDBusAdaptorConnector::AdaptorMap::ConstIterator it;
             it = qLowerBound(connector->adaptors.constBegin(), connector->adaptors.constEnd(),
                              interface_name);
             if (it != connector->adaptors.constEnd() && interface_name == QLatin1String(it->interface)) {
                 interfaceFound = true;
                 value = it->adaptor->property(property_name);
             }
         }
     }
     if (!interfaceFound && !value.isValid()
         && node.flags & (QDBusConnection::ExportAllProperties |
                          QDBusConnection::ExportNonScriptableProperties)) {
         // try the object itself
         if (!interface_name.isEmpty())
             interfaceFound = qDBusInterfaceInObject(node.obj, interface_name);
         if (interfaceFound) {
             int pidx = node.obj->metaObject()->indexOfProperty(property_name);
             if (pidx != -1) {
                 QMetaProperty mp = node.obj->metaObject()->property(pidx);
                 if ((mp.isScriptable() && (node.flags & QDBusConnection::ExportScriptableProperties)) ||
                     (!mp.isScriptable() && (node.flags & QDBusConnection::ExportNonScriptableProperties)))
                     value = mp.read(node.obj);
             }
         }
     }
     if (!value.isValid()) {
         // the property was not found
         if (!interfaceFound)
             return interfaceNotFoundError(msg, interface_name);
         return propertyNotFoundError(msg, interface_name, property_name);
     }
     return msg.createReply(QVariant::fromValue(QDBusVariant(value)));
 }
qDBusPropertyGetAll()
QDBusMessage qDBusPropertyGetAll (const QDBusConnectionPrivate::ObjectTreeNode & node, const QDBusMessage & msg)
Definition at line 466 of file qdbusinternalfilters.cpp.
Referenced by QDBusConnectionPrivate::activateInternalFilters().
 {
     Q_ASSERT(msg.arguments().count() == 1);
     Q_ASSERT_X(!node.obj || QThread::currentThread() == node.obj->thread(),
                "QDBusConnection: internal threading error",
                "function called for an object that is in another thread!!");
     QString interface_name = msg.arguments().at(0).toString();
     bool interfaceFound = false;
     QVariantMap result;
     QDBusAdaptorConnector *connector;
     if (node.flags & QDBusConnection::ExportAdaptors &&
         (connector = qDBusFindAdaptorConnector(node.obj))) {
         if (interface_name.isEmpty()) {
             // iterate over all interfaces
             for (QDBusAdaptorConnector::AdaptorMap::ConstIterator it = connector->adaptors.constBegin(),
                  end = connector->adaptors.constEnd(); it != end; ++it) {
                 result += readAllProperties(it->adaptor, QDBusConnection::ExportAllProperties);
             }
         } else {
             // find the class that implements interface_name
             QDBusAdaptorConnector::AdaptorMap::ConstIterator it;
             it = qLowerBound(connector->adaptors.constBegin(), connector->adaptors.constEnd(),
                              interface_name);
             if (it != connector->adaptors.constEnd() && interface_name == QLatin1String(it->interface)) {
                 interfaceFound = true;
                 result = readAllProperties(it->adaptor, QDBusConnection::ExportAllProperties);
             }
         }
     }
     if (node.flags & QDBusConnection::ExportAllProperties &&
         (!interfaceFound || interface_name.isEmpty())) {
         // try the object itself
         result += readAllProperties(node.obj, node.flags);
         interfaceFound = true;
     }
     if (!interfaceFound && !interface_name.isEmpty()) {
         // the interface was not found
         return interfaceNotFoundError(msg, interface_name);
     }
     return msg.createReply(QVariant::fromValue(result));
 }
qDBusPropertySet()
QDBusMessage qDBusPropertySet (const QDBusConnectionPrivate::ObjectTreeNode & node, const QDBusMessage & msg)
Definition at line 366 of file qdbusinternalfilters.cpp.
Referenced by QDBusConnectionPrivate::activateInternalFilters().
 {
     Q_ASSERT(msg.arguments().count() == 3);
     Q_ASSERT_X(!node.obj || QThread::currentThread() == node.obj->thread(),
                "QDBusConnection: internal threading error",
                "function called for an object that is in another thread!!");
     QString interface_name = msg.arguments().at(0).toString();
     QByteArray property_name = msg.arguments().at(1).toString().toUtf8();
     QVariant value = qvariant_cast<QDBusVariant>(msg.arguments().at(2)).variant();
     QDBusAdaptorConnector *connector;
     if (node.flags & QDBusConnection::ExportAdaptors &&
         (connector = qDBusFindAdaptorConnector(node.obj))) {
         // find the class that implements interface_name or try until we've found the property
         // in case of an empty interface
         if (interface_name.isEmpty()) {
             for (QDBusAdaptorConnector::AdaptorMap::ConstIterator it = connector->adaptors.constBegin(),
                  end = connector->adaptors.constEnd(); it != end; ++it) {
                 int status = writeProperty(it->adaptor, property_name, value);
                 if (status == PropertyNotFound)
                     continue;
                 return propertyWriteReply(msg, interface_name, property_name, status);
             }
         } else {
             QDBusAdaptorConnector::AdaptorMap::ConstIterator it;
             it = qLowerBound(connector->adaptors.constBegin(), connector->adaptors.constEnd(),
                              interface_name);
             if (it != connector->adaptors.end() && interface_name == QLatin1String(it->interface)) {
                 return propertyWriteReply(msg, interface_name, property_name,
                                           writeProperty(it->adaptor, property_name, value));
             }
         }
     }
     if (node.flags & (QDBusConnection::ExportScriptableProperties |
                       QDBusConnection::ExportNonScriptableProperties)) {
         // try the object itself
         bool interfaceFound = true;
         if (!interface_name.isEmpty())
             interfaceFound = qDBusInterfaceInObject(node.obj, interface_name);
         if (interfaceFound) {
             return propertyWriteReply(msg, interface_name, property_name,
                                       writeProperty(node.obj, property_name, value, node.flags));
         }
     }
     // the property was not found
     if (!interface_name.isEmpty())
         return interfaceNotFoundError(msg, interface_name);
     return propertyWriteReply(msg, interface_name, property_name, PropertyNotFound);
 }
readAllProperties()
static QVariantMap readAllProperties (QObject * object, int flags) static
Definition at line 432 of file qdbusinternalfilters.cpp.
Referenced by qDBusPropertyGetAll().
 {
     QVariantMap result;
     const QMetaObject *mo = object->metaObject();
     // QObject has properties, so don't start from 0
     for (int i = QObject::staticMetaObject.propertyCount(); i < mo->propertyCount(); ++i) {
         QMetaProperty mp = mo->property(i);
         // is it readable?
         if (!mp.isReadable())
             continue;
         // is it a registered property?
         int typeId = qDBusNameToTypeId(mp.typeName());
         if (!typeId)
             continue;
         const char *signature = QDBusMetaType::typeToSignature(typeId);
         if (!signature)
             continue;
         // is this property visible from the outside?
         if ((mp.isScriptable() && flags & QDBusConnection::ExportScriptableProperties) ||
             (!mp.isScriptable() && flags & QDBusConnection::ExportNonScriptableProperties)) {
             // yes, it's visible
             QVariant value = mp.read(object);
             if (value.isValid())
                 result.insert(QString::fromLatin1(mp.name()), value);
         }
     }
     return result;
 }
writeProperty()
static int writeProperty (QObject * obj, const QByteArray & property_name, QVariant value, int propFlags = QDBusConnection::ExportAllProperties) static
Definition at line 315 of file qdbusinternalfilters.cpp.
Referenced by qDBusPropertySet().
 {
     const QMetaObject *mo = obj->metaObject();
     int pidx = mo->indexOfProperty(property_name);
     if (pidx == -1) {
         // this object has no property by that name
         return PropertyNotFound;
     }
     QMetaProperty mp = mo->property(pidx);
     // check if this property is exported
     bool isScriptable = mp.isScriptable();
     if (!(propFlags & QDBusConnection::ExportScriptableProperties) && isScriptable)
         return PropertyNotFound;
     if (!(propFlags & QDBusConnection::ExportNonScriptableProperties) && !isScriptable)
         return PropertyNotFound;
     // we found our property
     // do we have the right type?
     int id = mp.type();
     if (id == QVariant::UserType) {
         // dynamic type
         id = qDBusNameToTypeId(mp.typeName());
         if (id == -1) {
             // type not registered?
             qWarning("QDBusConnection: Unable to handle unregistered datatype '%s' for property '%s::%s'",
                      mp.typeName(), mo->className(), property_name.constData());
             return PropertyWriteFailed;
         }
     }
     if (id != 0xff && value.userType() == QDBusMetaTypeId::argument) {
         // we have to demarshall before writing
         void *null = 0;
         QVariant other(id, null);
         if (!QDBusMetaType::demarshall(qvariant_cast<QDBusArgument>(value), id, other.data())) {
             qWarning("QDBusConnection: type `%s' (%d) is not registered with QtDBus. "
                      "Use qDBusRegisterMetaType to register it",
                      mp.typeName(), id);
             return PropertyWriteFailed;
         }
         value = other;
     }
     // the property type here should match
     return mp.write(obj, value) ? PropertyWriteSuccess : PropertyWriteFailed;
 }
Variable Documentation
introspectableInterfaceXml
const char introspectableInterfaceXml[] static
Initial value:
=
    "  <interface name=\"org.freedesktop.DBus.Introspectable\">\n"
    "    <method name=\"Introspect\">\n"
    "      <arg name=\"xml_data\" type=\"s\" direction=\"out\"/>\n"
    "    </method>\n"
    "  </interface>\n"
Definition at line 69 of file qdbusinternalfilters.cpp.
Referenced by qDBusIntrospectObject().
peerInterfaceXml
const char peerInterfaceXml[] static
Initial value:
=
    "  <interface name=\"org.freedesktop.DBus.Peer\">\n"
    "    <method name=\"Ping\"/>\n"
    "    <method name=\"GetMachineId\">\n"
    "      <arg name=\"machine_uuid\" type=\"s\" direction=\"out\"/>\n"
    "    </method>\n"
    "  </interface>\n"
Definition at line 95 of file qdbusinternalfilters.cpp.
Referenced by qDBusIntrospectObject().
propertiesInterfaceXml
const char propertiesInterfaceXml[] static
Initial value:
=
    "  <interface name=\"org.freedesktop.DBus.Properties\">\n"
    "    <method name=\"Get\">\n"
    "      <arg name=\"interface_name\" type=\"s\" direction=\"in\"/>\n"
    "      <arg name=\"property_name\" type=\"s\" direction=\"in\"/>\n"
    "      <arg name=\"value\" type=\"v\" direction=\"out\"/>\n"
    "    </method>\n"
    "    <method name=\"Set\">\n"
    "      <arg name=\"interface_name\" type=\"s\" direction=\"in\"/>\n"
    "      <arg name=\"property_name\" type=\"s\" direction=\"in\"/>\n"
    "      <arg name=\"value\" type=\"v\" direction=\"in\"/>\n"
    "    </method>\n"
    "    <method name=\"GetAll\">\n"
    "      <arg name=\"interface_name\" type=\"s\" direction=\"in\"/>\n"
    "      <arg name=\"values\" type=\"a{sv}\" direction=\"out\"/>\n"
    "      <annotation name=\"org.qtproject.QtDBus.QtTypeName.Out0\" value=\"QVariantMap\"/>\n"
    "    </method>\n"
    "  </interface>\n"
Definition at line 76 of file qdbusinternalfilters.cpp.
Referenced by qDBusIntrospectObject().