Qt 4.8: /src/dbus/qdbusabstractadaptor_p.h File Reference
qdbusabstractadaptor_p.h File Reference
#include <qdbusabstractadaptor.h>
#include <QtCore/qobject.h>
#include <QtCore/qmap.h>
#include <QtCore/qhash.h>
#include <QtCore/qreadwritelock.h>
#include <QtCore/qvariant.h>
#include <QtCore/qvector.h>
#include "private/qobject_p.h"
Classes
class QDBusAbstractAdaptorPrivate
class QDBusAdaptorConnector
struct QDBusAdaptorConnector::AdaptorData
Macros
#define QCLASSINFO_DBUS_INTERFACE "D-Bus Interface"
#define QCLASSINFO_DBUS_INTROSPECTION "D-Bus Introspection"
Functions
QDBusAdaptorConnector * qDBusCreateAdaptorConnector (QObject *object)
QDBusAdaptorConnector * qDBusFindAdaptorConnector (QObject *object)
Macro Definition Documentation
QCLASSINFO_DBUS_INTERFACE
#define QCLASSINFO_DBUS_INTERFACE "D-Bus Interface"
Definition at line 67 of file qdbusabstractadaptor_p.h.
Referenced by QDBusAdaptorConnector::addAdaptor(), qDBusGenerateMetaObjectXml(), and qDBusInterfaceFromMetaObject().
QCLASSINFO_DBUS_INTROSPECTION
#define QCLASSINFO_DBUS_INTROSPECTION "D-Bus Introspection"
Definition at line 68 of file qdbusabstractadaptor_p.h.
Referenced by qDBusGenerateMetaObjectXml().
Function Documentation
qDBusCreateAdaptorConnector()
QDBusAdaptorConnector* qDBusCreateAdaptorConnector (QObject * object)
Definition at line 82 of file qdbusabstractadaptor.cpp.
Referenced by QDBusAbstractAdaptor::QDBusAbstractAdaptor(), and QDBusConnectionPrivate::registerObject().
 {
     QDBusAdaptorConnector *connector = qDBusFindAdaptorConnector(obj);
     if (connector)
         return connector;
     return new QDBusAdaptorConnector(obj);
 }
qDBusFindAdaptorConnector()
QDBusAdaptorConnector* qDBusFindAdaptorConnector (QObject * object)
Definition at line 60 of file qdbusabstractadaptor.cpp.
Referenced by QDBusConnectionPrivate::activateObject(), qDBusCreateAdaptorConnector(), qDBusFindAdaptorConnector(), qDBusIntrospectObject(), qDBusPropertyGet(), qDBusPropertyGetAll(), and qDBusPropertySet().
 {
     if (!obj)
         return 0;
     const QObjectList &children = obj->children();
     QObjectList::ConstIterator it = children.constBegin();
     QObjectList::ConstIterator end = children.constEnd();
     for ( ; it != end; ++it) {
         QDBusAdaptorConnector *connector = qobject_cast<QDBusAdaptorConnector *>(*it);
         if (connector) {
             connector->polish();
             return connector;
         }
     }
     return 0;
 }