Qt 4.8: /src/dbus/qdbus_symbols.cpp File Reference
qdbus_symbols.cpp File Reference
#include <QtCore/qglobal.h>
#include <QtCore/qlibrary.h>
#include <QtCore/qmutex.h>
#include <private/qmutexpool_p.h>
Functions
bool qdbus_loadLibDBus ()
void * qdbus_resolve_conditionally (const char *name)
void * qdbus_resolve_me (const char *name)
void qdbus_unloadLibDBus ()
Variables
static QLibrary * qdbus_libdbus = 0
Function Documentation
qdbus_loadLibDBus()
bool qdbus_loadLibDBus ()
Definition at line 63 of file qdbus_symbols.cpp.
Referenced by QDBusConnection::connectToBus(), QDBusConnection::connectToPeer(), QDBusArgumentPrivate::createSignature(), qdbus_resolve_conditionally(), qdbus_resolve_me(), QDBusArgument::QDBusArgument(), QDBusServer::QDBusServer(), and QDBusMessagePrivate::toDBusMessage().
 {
     static volatile bool triedToLoadLibrary = false;
 #ifndef QT_NO_THREAD
     QMutexLocker locker(QMutexPool::globalInstanceGet((void *)&qdbus_resolve_me));
 #endif
     QLibrary *&lib = qdbus_libdbus;
     if (triedToLoadLibrary)
         return lib && lib->isLoaded();
     lib = new QLibrary;
     triedToLoadLibrary = true;
     static int majorversions[] = { 3, 2, -1 };
     lib->unload();
     lib->setFileName(QLatin1String("dbus-1"));
     lib->setLoadHints(QLibrary::ImprovedSearchHeuristics);
     for (uint i = 0; i < sizeof(majorversions) / sizeof(majorversions[0]); ++i) {
         lib->setFileNameAndVersion(lib->fileName(), majorversions[i]);
         if (lib->load() && lib->resolve("dbus_connection_open_private"))
             return true;
         lib->unload();
     }
     delete lib;
     lib = 0;
     return false;
 }
qdbus_resolve_conditionally()
void* qdbus_resolve_conditionally (const char * name)
Definition at line 93 of file qdbus_symbols.cpp.
Referenced by connectionCapabilies().
 {
     if (qdbus_loadLibDBus())
         return qdbus_libdbus->resolve(name);
     return 0;
 }
qdbus_resolve_me()
void * qdbus_resolve_me (const char * name)
Definition at line 100 of file qdbus_symbols.cpp.
Referenced by qdbus_loadLibDBus().
 {
     void *ptr = 0;
     if (!qdbus_loadLibDBus())
         qFatal("Cannot find libdbus-1 in your system to resolve symbol '%s'.", name);
     ptr = qdbus_libdbus->resolve(name);
     if (!ptr)
         qFatal("Cannot resolve '%s' in your libdbus-1.", name);
     return ptr;
 }
qdbus_unloadLibDBus()
void qdbus_unloadLibDBus ()
Definition at line 57 of file qdbus_symbols.cpp.
Referenced by qdbus_resolve_me().
 {
     delete qdbus_libdbus;
     qdbus_libdbus = 0;
 }
Variable Documentation
qdbus_libdbus
QLibrary* qdbus_libdbus = 0 static
Definition at line 55 of file qdbus_symbols.cpp.
Referenced by qdbus_loadLibDBus(), and qdbus_unloadLibDBus().