Qt 4.8: /src/dbus/qdbus_symbols_p.h File Reference
qdbus_symbols_p.h File Reference
#include <QtCore/qglobal.h>
#include <dbus/dbus.h>
Macros
#define DEFINEFUNC(ret, func, args, argcall, funcret)
Functions
void dbus_bus_add_match (DBusConnection *connection, const char *rule, DBusError *error)
DBusConnection * dbus_bus_get_private (DBusBusType type, DBusError *error)
const char * dbus_bus_get_unique_name (DBusConnection *connection)
dbus_bool_t dbus_bus_register (DBusConnection *connection, DBusError *error)
void dbus_bus_remove_match (DBusConnection *connection, const char *rule, DBusError *error)
dbus_bool_t dbus_connection_add_filter (DBusConnection *connection, DBusHandleMessageFunction function, void *user_data, DBusFreeFunction free_data_function)
void dbus_connection_close (DBusConnection *connection)
DBusDispatchStatus dbus_connection_dispatch (DBusConnection *connection)
DBusDispatchStatus dbus_connection_get_dispatch_status (DBusConnection *connection)
dbus_bool_t dbus_connection_get_is_connected (DBusConnection *connection)
DBusConnection * dbus_connection_open_private (const char *address, DBusError *error)
DBusConnection * dbus_connection_ref (DBusConnection *connection)
dbus_bool_t dbus_connection_send (DBusConnection *connection, DBusMessage *message, dbus_uint32_t *client_serial)
dbus_bool_t dbus_connection_send_with_reply (DBusConnection *connection, DBusMessage *message, DBusPendingCall **pending_return, int timeout_milliseconds)
DBusMessage * dbus_connection_send_with_reply_and_block (DBusConnection *connection, DBusMessage *message, int timeout_milliseconds, DBusError *error)
void dbus_connection_set_dispatch_status_function (DBusConnection *connection, DBusDispatchStatusFunction function, void *data, DBusFreeFunction free_data_function)
void dbus_connection_set_exit_on_disconnect (DBusConnection *connection, dbus_bool_t exit_on_disconnect)
dbus_bool_t dbus_connection_set_timeout_functions (DBusConnection *connection, DBusAddTimeoutFunction add_function, DBusRemoveTimeoutFunction remove_function, DBusTimeoutToggledFunction toggled_function, void *data, DBusFreeFunction free_data_function)
void dbus_connection_set_wakeup_main_function (DBusConnection *connection, DBusWakeupMainFunction wakeup_main_function, void *data, DBusFreeFunction free_data_function)
dbus_bool_t dbus_connection_set_watch_functions (DBusConnection *connection, DBusAddWatchFunction add_function, DBusRemoveWatchFunction remove_function, DBusWatchToggledFunction toggled_function, void *data, DBusFreeFunction free_data_function)
void dbus_connection_unref (DBusConnection *connection)
void dbus_error_free (DBusError *error)
void dbus_error_init (DBusError *error)
dbus_bool_t dbus_error_is_set (const DBusError *error)
void dbus_free (void *memory)
char * dbus_get_local_machine_id (void)
DBusMessage * dbus_message_copy (const DBusMessage *message)
dbus_bool_t dbus_message_get_auto_start (DBusMessage *message)
const char * dbus_message_get_error_name (DBusMessage *message)
const char * dbus_message_get_interface (DBusMessage *message)
const char * dbus_message_get_member (DBusMessage *message)
dbus_bool_t dbus_message_get_no_reply (DBusMessage *message)
const char * dbus_message_get_path (DBusMessage *message)
const char * dbus_message_get_sender (DBusMessage *message)
dbus_uint32_t dbus_message_get_serial (DBusMessage *message)
const char * dbus_message_get_signature (DBusMessage *message)
int dbus_message_get_type (DBusMessage *message)
dbus_bool_t dbus_message_iter_append_basic (DBusMessageIter *iter, int type, const void *value)
dbus_bool_t dbus_message_iter_append_fixed_array (DBusMessageIter *iter, int element_type, const void *value, int n_elements)
dbus_bool_t dbus_message_iter_close_container (DBusMessageIter *iter, DBusMessageIter *sub)
int dbus_message_iter_get_arg_type (DBusMessageIter *iter)
void dbus_message_iter_get_basic (DBusMessageIter *iter, void *value)
int dbus_message_iter_get_element_type (DBusMessageIter *iter)
void dbus_message_iter_get_fixed_array (DBusMessageIter *iter, void *value, int *n_elements)
char * dbus_message_iter_get_signature (DBusMessageIter *iter)
dbus_bool_t dbus_message_iter_init (DBusMessage *message, DBusMessageIter *iter)
void dbus_message_iter_init_append (DBusMessage *message, DBusMessageIter *iter)
dbus_bool_t dbus_message_iter_next (DBusMessageIter *iter)
dbus_bool_t dbus_message_iter_open_container (DBusMessageIter *iter, int type, const char *contained_signature, DBusMessageIter *sub)
void dbus_message_iter_recurse (DBusMessageIter *iter, DBusMessageIter *sub)
DBusMessage * dbus_message_new (int message_type)
DBusMessage * dbus_message_new_method_call (const char *bus_name, const char *path, const char *interface, const char *method)
DBusMessage * dbus_message_new_signal (const char *path, const char *interface, const char *name)
DBusMessage * dbus_message_ref (DBusMessage *message)
void dbus_message_set_auto_start (DBusMessage *message, dbus_bool_t auto_start)
dbus_bool_t dbus_message_set_destination (DBusMessage *message, const char *destination)
dbus_bool_t dbus_message_set_error_name (DBusMessage *message, const char *name)
void dbus_message_set_no_reply (DBusMessage *message, dbus_bool_t no_reply)
dbus_bool_t dbus_message_set_path (DBusMessage *message, const char *object_path)
dbus_bool_t dbus_message_set_reply_serial (DBusMessage *message, dbus_uint32_t reply_serial)
dbus_bool_t dbus_message_set_sender (DBusMessage *message, const char *sender)
void dbus_message_unref (DBusMessage *message)
void dbus_pending_call_block (DBusPendingCall *pending)
void dbus_pending_call_cancel (DBusPendingCall *pending)
dbus_bool_t dbus_pending_call_get_completed (DBusPendingCall *pending)
dbus_bool_t dbus_pending_call_set_notify (DBusPendingCall *pending, DBusPendingCallNotifyFunction function, void *user_data, DBusFreeFunction free_user_data)
DBusMessage * dbus_pending_call_steal_reply (DBusPendingCall *pending)
void dbus_pending_call_unref (DBusPendingCall *pending)
dbus_bool_t dbus_server_allocate_data_slot (dbus_int32_t *slot_p)
void dbus_server_disconnect (DBusServer *server)
char * dbus_server_get_address (DBusServer *server)
dbus_bool_t dbus_server_get_is_connected (DBusServer *server)
DBusServer * dbus_server_listen (const char *address, DBusError *error)
dbus_bool_t dbus_server_set_data (DBusServer *server, int slot, void *data, DBusFreeFunction free_data_func)
void dbus_server_set_new_connection_function (DBusServer *server, DBusNewConnectionFunction function, void *data, DBusFreeFunction free_data_function)
dbus_bool_t dbus_server_set_timeout_functions (DBusServer *server, DBusAddTimeoutFunction add_function, DBusRemoveTimeoutFunction remove_function, DBusTimeoutToggledFunction toggled_function, void *data, DBusFreeFunction free_data_function)
dbus_bool_t dbus_server_set_watch_functions (DBusServer *server, DBusAddWatchFunction add_function, DBusRemoveWatchFunction remove_function, DBusWatchToggledFunction toggled_function, void *data, DBusFreeFunction free_data_function)
void dbus_server_unref (DBusServer *server)
dbus_bool_t dbus_threads_init_default ()
dbus_bool_t dbus_timeout_get_enabled (DBusTimeout *timeout)
int dbus_timeout_get_interval (DBusTimeout *timeout)
dbus_bool_t dbus_timeout_handle (DBusTimeout *timeout)
dbus_bool_t dbus_watch_get_enabled (DBusWatch *watch)
int dbus_watch_get_fd (DBusWatch *watch)
unsigned int dbus_watch_get_flags (DBusWatch *watch)
dbus_bool_t dbus_watch_handle (DBusWatch *watch, unsigned int flags)
bool qdbus_loadLibDBus ()
void * qdbus_resolve_conditionally (const char *name)
void * qdbus_resolve_me (const char *name)
Macro Definition Documentation
DEFINEFUNC
#define DEFINEFUNC (ret, func, args, argcall, funcret)
Value:
typedef ret (* _q_PTR_##func) args;                         \
    static inline ret q_##func args                             \
    {                                                           \
        static _q_PTR_##func ptr;                               \
        if (!ptr)                                               \
            ptr = (_q_PTR_##func) qdbus_resolve_me(#func);      \
        funcret ptr argcall;                                    \
    }
Definition at line 70 of file qdbus_symbols_p.h.
Function Documentation
dbus_bus_add_match()
void dbus_bus_add_match (DBusConnection * connection, const char * rule, DBusError * error)
dbus_bus_get_private()
DBusConnection* dbus_bus_get_private (DBusBusType type, DBusError * error)
Referenced by Maemo::DBusDispatcher::setupDBus().
dbus_bus_get_unique_name()
const char* dbus_bus_get_unique_name (DBusConnection * connection)
dbus_bus_register()
dbus_bool_t dbus_bus_register (DBusConnection * connection, DBusError * error)
dbus_bus_remove_match()
void dbus_bus_remove_match (DBusConnection * connection, const char * rule, DBusError * error)
dbus_connection_add_filter()
dbus_bool_t dbus_connection_add_filter (DBusConnection * connection, DBusHandleMessageFunction function, void * user_data, DBusFreeFunction free_data_function)
dbus_connection_close()
void dbus_connection_close (DBusConnection * connection)
Referenced by Maemo::DBusDispatcher::~DBusDispatcher().
dbus_connection_dispatch()
DBusDispatchStatus dbus_connection_dispatch (DBusConnection * connection)
dbus_connection_get_dispatch_status()
DBusDispatchStatus dbus_connection_get_dispatch_status (DBusConnection * connection)
dbus_connection_get_is_connected()
dbus_bool_t dbus_connection_get_is_connected (DBusConnection * connection)
dbus_connection_open_private()
DBusConnection* dbus_connection_open_private (const char * address, DBusError * error)
dbus_connection_ref()
DBusConnection* dbus_connection_ref (DBusConnection * connection)
dbus_connection_send()
dbus_bool_t dbus_connection_send (DBusConnection * connection, DBusMessage * message, dbus_uint32_t * client_serial)
dbus_connection_send_with_reply()
dbus_bool_t dbus_connection_send_with_reply (DBusConnection * connection, DBusMessage * message, DBusPendingCall ** pending_return, int timeout_milliseconds)
Referenced by Maemo::DBusDispatcher::callAsynchronous().
dbus_connection_send_with_reply_and_block()
DBusMessage* dbus_connection_send_with_reply_and_block (DBusConnection * connection, DBusMessage * message, int timeout_milliseconds, DBusError * error)
Referenced by Maemo::DBusDispatcher::call().
dbus_connection_set_dispatch_status_function()
void dbus_connection_set_dispatch_status_function (DBusConnection * connection, DBusDispatchStatusFunction function, void * data, DBusFreeFunction free_data_function)
dbus_connection_set_exit_on_disconnect()
void dbus_connection_set_exit_on_disconnect (DBusConnection * connection, dbus_bool_t exit_on_disconnect)
Referenced by Maemo::DBusDispatcher::setupDBus().
dbus_connection_set_timeout_functions()
dbus_bool_t dbus_connection_set_timeout_functions (DBusConnection * connection, DBusAddTimeoutFunction add_function, DBusRemoveTimeoutFunction remove_function, DBusTimeoutToggledFunction toggled_function, void * data, DBusFreeFunction free_data_function)
dbus_connection_set_wakeup_main_function()
void dbus_connection_set_wakeup_main_function (DBusConnection * connection, DBusWakeupMainFunction wakeup_main_function, void * data, DBusFreeFunction free_data_function)
dbus_connection_set_watch_functions()
dbus_bool_t dbus_connection_set_watch_functions (DBusConnection * connection, DBusAddWatchFunction add_function, DBusRemoveWatchFunction remove_function, DBusWatchToggledFunction toggled_function, void * data, DBusFreeFunction free_data_function)
dbus_connection_unref()
void dbus_connection_unref (DBusConnection * connection)
Referenced by Maemo::DBusDispatcher::~DBusDispatcher().
dbus_error_free()
void dbus_error_free (DBusError * error)
dbus_error_init()
void dbus_error_init (DBusError * error)
dbus_error_is_set()
dbus_bool_t dbus_error_is_set (const DBusError * error)
dbus_free()
void dbus_free (void * memory)
dbus_get_local_machine_id()
char* dbus_get_local_machine_id (void)
dbus_message_copy()
DBusMessage* dbus_message_copy (const DBusMessage * message)
dbus_message_get_auto_start()
dbus_bool_t dbus_message_get_auto_start (DBusMessage * message)
dbus_message_get_error_name()
const char* dbus_message_get_error_name (DBusMessage * message)
Referenced by Maemo::pendingCallFunction().
dbus_message_get_interface()
const char* dbus_message_get_interface (DBusMessage * message)
dbus_message_get_member()
const char* dbus_message_get_member (DBusMessage * message)
dbus_message_get_no_reply()
dbus_bool_t dbus_message_get_no_reply (DBusMessage * message)
dbus_message_get_path()
const char* dbus_message_get_path (DBusMessage * message)
dbus_message_get_sender()
const char* dbus_message_get_sender (DBusMessage * message)
dbus_message_get_serial()
dbus_uint32_t dbus_message_get_serial (DBusMessage * message)
dbus_message_get_signature()
const char* dbus_message_get_signature (DBusMessage * message)
dbus_message_get_type()
int dbus_message_get_type (DBusMessage * message)
Referenced by Maemo::pendingCallFunction().
dbus_message_iter_append_basic()
dbus_bool_t dbus_message_iter_append_basic (DBusMessageIter * iter, int type, const void * value)
Referenced by Maemo::appendVariantToDBusMessage().
dbus_message_iter_append_fixed_array()
dbus_bool_t dbus_message_iter_append_fixed_array (DBusMessageIter * iter, int element_type, const void * value, int n_elements)
Referenced by Maemo::appendVariantToDBusMessage().
dbus_message_iter_close_container()
dbus_bool_t dbus_message_iter_close_container (DBusMessageIter * iter, DBusMessageIter * sub)
Referenced by Maemo::appendVariantToDBusMessage().
dbus_message_iter_get_arg_type()
int dbus_message_iter_get_arg_type (DBusMessageIter * iter)
Referenced by Maemo::DBusDispatcher::call(), Maemo::getVariantFromDBusMessage(), and Maemo::pendingCallFunction().
dbus_message_iter_get_basic()
void dbus_message_iter_get_basic (DBusMessageIter * iter, void * value)
Referenced by Maemo::getVariantFromDBusMessage().
dbus_message_iter_get_element_type()
int dbus_message_iter_get_element_type (DBusMessageIter * iter)
Referenced by Maemo::getVariantFromDBusMessage().
dbus_message_iter_get_fixed_array()
void dbus_message_iter_get_fixed_array (DBusMessageIter * iter, void * value, int * n_elements)
dbus_message_iter_get_signature()
char* dbus_message_iter_get_signature (DBusMessageIter * iter)
dbus_message_iter_init()
dbus_bool_t dbus_message_iter_init (DBusMessage * message, DBusMessageIter * iter)
Referenced by Maemo::DBusDispatcher::call(), and Maemo::pendingCallFunction().
dbus_message_iter_init_append()
void dbus_message_iter_init_append (DBusMessage * message, DBusMessageIter * iter)
Referenced by Maemo::prepareDBusCall().
dbus_message_iter_next()
dbus_bool_t dbus_message_iter_next (DBusMessageIter * iter)
Referenced by Maemo::DBusDispatcher::call(), Maemo::getVariantFromDBusMessage(), and Maemo::pendingCallFunction().
dbus_message_iter_open_container()
dbus_bool_t dbus_message_iter_open_container (DBusMessageIter * iter, int type, const char * contained_signature, DBusMessageIter * sub)
Referenced by Maemo::appendVariantToDBusMessage().
dbus_message_iter_recurse()
void dbus_message_iter_recurse (DBusMessageIter * iter, DBusMessageIter * sub)
Referenced by Maemo::getVariantFromDBusMessage().
dbus_message_new()
DBusMessage* dbus_message_new (int message_type)
dbus_message_new_method_call()
DBusMessage* dbus_message_new_method_call (const char * bus_name, const char * path, const char * interface, const char * method)
Referenced by Maemo::prepareDBusCall().
dbus_message_new_signal()
DBusMessage* dbus_message_new_signal (const char * path, const char * interface, const char * name)
dbus_message_ref()
DBusMessage* dbus_message_ref (DBusMessage * message)
dbus_message_set_auto_start()
void dbus_message_set_auto_start (DBusMessage * message, dbus_bool_t auto_start)
dbus_message_set_destination()
dbus_bool_t dbus_message_set_destination (DBusMessage * message, const char * destination)
dbus_message_set_error_name()
dbus_bool_t dbus_message_set_error_name (DBusMessage * message, const char * name)
dbus_message_set_no_reply()
void dbus_message_set_no_reply (DBusMessage * message, dbus_bool_t no_reply)
dbus_message_set_path()
dbus_bool_t dbus_message_set_path (DBusMessage * message, const char * object_path)
dbus_message_set_reply_serial()
dbus_bool_t dbus_message_set_reply_serial (DBusMessage * message, dbus_uint32_t reply_serial)
dbus_message_set_sender()
dbus_bool_t dbus_message_set_sender (DBusMessage * message, const char * sender)
dbus_message_unref()
void dbus_message_unref (DBusMessage * message)
Referenced by Maemo::DBusDispatcher::call(), and Maemo::pendingCallFunction().
dbus_pending_call_block()
void dbus_pending_call_block (DBusPendingCall * pending)
dbus_pending_call_cancel()
void dbus_pending_call_cancel (DBusPendingCall * pending)
Referenced by Maemo::DBusDispatcherPrivate::~DBusDispatcherPrivate().
dbus_pending_call_get_completed()
dbus_bool_t dbus_pending_call_get_completed (DBusPendingCall * pending)
dbus_pending_call_set_notify()
dbus_bool_t dbus_pending_call_set_notify (DBusPendingCall * pending, DBusPendingCallNotifyFunction function, void * user_data, DBusFreeFunction free_user_data)
Referenced by Maemo::DBusDispatcher::callAsynchronous().
dbus_pending_call_steal_reply()
DBusMessage* dbus_pending_call_steal_reply (DBusPendingCall * pending)
Referenced by Maemo::pendingCallFunction().
dbus_pending_call_unref()
void dbus_pending_call_unref (DBusPendingCall * pending)
Referenced by Maemo::pendingCallFunction(), and Maemo::DBusDispatcherPrivate::~DBusDispatcherPrivate().
dbus_server_allocate_data_slot()
dbus_bool_t dbus_server_allocate_data_slot (dbus_int32_t * slot_p)
dbus_server_disconnect()
void dbus_server_disconnect (DBusServer * server)
dbus_server_get_address()
char* dbus_server_get_address (DBusServer * server)
dbus_server_get_is_connected()
dbus_bool_t dbus_server_get_is_connected (DBusServer * server)
dbus_server_listen()
DBusServer* dbus_server_listen (const char * address, DBusError * error)
dbus_server_set_data()
dbus_bool_t dbus_server_set_data (DBusServer * server, int slot, void * data, DBusFreeFunction free_data_func)
dbus_server_set_new_connection_function()
void dbus_server_set_new_connection_function (DBusServer * server, DBusNewConnectionFunction function, void * data, DBusFreeFunction free_data_function)
dbus_server_set_timeout_functions()
dbus_bool_t dbus_server_set_timeout_functions (DBusServer * server, DBusAddTimeoutFunction add_function, DBusRemoveTimeoutFunction remove_function, DBusTimeoutToggledFunction toggled_function, void * data, DBusFreeFunction free_data_function)
dbus_server_set_watch_functions()
dbus_bool_t dbus_server_set_watch_functions (DBusServer * server, DBusAddWatchFunction add_function, DBusRemoveWatchFunction remove_function, DBusWatchToggledFunction toggled_function, void * data, DBusFreeFunction free_data_function)
dbus_server_unref()
void dbus_server_unref (DBusServer * server)
dbus_threads_init_default()
dbus_bool_t dbus_threads_init_default ()
dbus_timeout_get_enabled()
dbus_bool_t dbus_timeout_get_enabled (DBusTimeout * timeout)
dbus_timeout_get_interval()
int dbus_timeout_get_interval (DBusTimeout * timeout)
dbus_timeout_handle()
dbus_bool_t dbus_timeout_handle (DBusTimeout * timeout)
dbus_watch_get_enabled()
dbus_bool_t dbus_watch_get_enabled (DBusWatch * watch)
dbus_watch_get_fd()
int dbus_watch_get_fd (DBusWatch * watch)
dbus_watch_get_flags()
unsigned int dbus_watch_get_flags (DBusWatch * watch)
dbus_watch_handle()
dbus_bool_t dbus_watch_handle (DBusWatch * watch, unsigned int flags)
qdbus_loadLibDBus()
bool qdbus_loadLibDBus ()
Definition at line 63 of file qdbus_symbols.cpp.
Referenced by QDBusConnection::connectToBus(), QDBusConnection::connectToPeer(), QDBusArgumentPrivate::createSignature(), qdbus_resolve_conditionally(), qdbus_resolve_me(), QDBusArgument::QDBusArgument(), QDBusServer::QDBusServer(), and QDBusMessagePrivate::toDBusMessage().
 {
     static volatile bool triedToLoadLibrary = false;
 #ifndef QT_NO_THREAD
     QMutexLocker locker(QMutexPool::globalInstanceGet((void *)&qdbus_resolve_me));
 #endif
     QLibrary *&lib = qdbus_libdbus;
     if (triedToLoadLibrary)
         return lib && lib->isLoaded();
     lib = new QLibrary;
     triedToLoadLibrary = true;
     static int majorversions[] = { 3, 2, -1 };
     lib->unload();
     lib->setFileName(QLatin1String("dbus-1"));
     lib->setLoadHints(QLibrary::ImprovedSearchHeuristics);
     for (uint i = 0; i < sizeof(majorversions) / sizeof(majorversions[0]); ++i) {
         lib->setFileNameAndVersion(lib->fileName(), majorversions[i]);
         if (lib->load() && lib->resolve("dbus_connection_open_private"))
             return true;
         lib->unload();
     }
     delete lib;
     lib = 0;
     return false;
 }
qdbus_resolve_conditionally()
void* qdbus_resolve_conditionally (const char * name)
Definition at line 93 of file qdbus_symbols.cpp.
Referenced by connectionCapabilies().
 {
     if (qdbus_loadLibDBus())
         return qdbus_libdbus->resolve(name);
     return 0;
 }
qdbus_resolve_me()
void* qdbus_resolve_me (const char * name)
Definition at line 100 of file qdbus_symbols.cpp.
Referenced by qdbus_loadLibDBus().
 {
     void *ptr = 0;
     if (!qdbus_loadLibDBus())
         qFatal("Cannot find libdbus-1 in your system to resolve symbol '%s'.", name);
     ptr = qdbus_libdbus->resolve(name);
     if (!ptr)
         qFatal("Cannot resolve '%s' in your libdbus-1.", name);
     return ptr;
 }