Qt 4.8: /src/declarative/qml/qdeclarativeproperty.cpp File Reference
qdeclarativeproperty.cpp File Reference
#include "qdeclarativeproperty.h"
#include "private/qdeclarativeproperty_p.h"
#include "qdeclarative.h"
#include "private/qdeclarativebinding_p.h"
#include "qdeclarativecontext.h"
#include "private/qdeclarativecontext_p.h"
#include "private/qdeclarativeboundsignal_p.h"
#include "qdeclarativeengine.h"
#include "private/qdeclarativeengine_p.h"
#include "private/qdeclarativedata_p.h"
#include "private/qdeclarativestringconverters_p.h"
#include "private/qdeclarativelist_p.h"
#include "private/qdeclarativecompiler_p.h"
#include "private/qdeclarativevmemetaobject_p.h"
#include <QStringList>
#include <QtCore/qdebug.h>
#include <math.h>
Classes
struct SerializedData
struct ValueTypeSerializedData
Functions
static void flush_vme_signal (const QObject *object, int index)
Q_GLOBAL_STATIC (QDeclarativeValueTypeFactory, qmlValueTypes)
static int QMetaObject_methods (const QMetaObject *metaObject)
static int QMetaObject_properties (const QMetaObject *metaObject)
Function Documentation
flush_vme_signal()
static void flush_vme_signal (const QObject * object, int index) inline static
Definition at line 1607 of file qdeclarativeproperty.cpp.
Referenced by QDeclarativePropertyPrivate::connect().
 {
     QDeclarativeData *data = static_cast<QDeclarativeData *>(QObjectPrivate::get(const_cast<QObject *>(object))->declarativeData);
     if (data && data->propertyCache) {
         QDeclarativePropertyCache::Data *property = data->propertyCache->method(index);
         if (property && property->flags & QDeclarativePropertyCache::Data::IsVMESignal) {
             const QMetaObject *metaObject = object->metaObject();
             int methodOffset = metaObject->methodOffset();
             while (methodOffset > index) {
                 metaObject = metaObject->d.superdata;
                 methodOffset -= QMetaObject_methods(metaObject);
             }
             QDeclarativeVMEMetaObject *vme =
                 static_cast<QDeclarativeVMEMetaObject *>(const_cast<QMetaObject *>(metaObject));
             vme->connectAliasSignal(index);
         }
     }
 }
Q_GLOBAL_STATIC()
Q_GLOBAL_STATIC (QDeclarativeValueTypeFactory , qmlValueTypes)
Referenced by QDeclarativeProperty::QDeclarativeProperty().
QMetaObject_methods()
static int QMetaObject_methods (const QMetaObject * metaObject) inline static
Definition at line 1579 of file qdeclarativeproperty.cpp.
Referenced by flush_vme_signal().
 {
     struct Private
     {
         int revision;
         int className;
         int classInfoCount, classInfoData;
         int methodCount, methodData;
         int propertyCount, propertyData;
     };
     return reinterpret_cast<const Private *>(metaObject->d.data)->methodCount;
 }
QMetaObject_properties()
static int QMetaObject_properties (const QMetaObject * metaObject) inline static
Definition at line 1593 of file qdeclarativeproperty.cpp.
Referenced by QDeclarativePropertyPrivate::metaObjectForProperty().
 {
     struct Private
     {
         int revision;
         int className;
         int classInfoCount, classInfoData;
         int methodCount, methodData;
         int propertyCount, propertyData;
     };
     return reinterpret_cast<const Private *>(metaObject->d.data)->propertyCount;
 }