Qt 4.8: /src/declarative/qml/qdeclarativesqldatabase.cpp File Reference
qdeclarativesqldatabase.cpp File Reference
#include "private/qdeclarativesqldatabase_p.h"
#include "qdeclarativeengine.h"
#include "private/qdeclarativeengine_p.h"
#include "private/qdeclarativerefcount_p.h"
#include <QtCore/qobject.h>
#include <QtScript/qscriptvalue.h>
#include <QtScript/qscriptvalueiterator.h>
#include <QtScript/qscriptcontext.h>
#include <QtScript/qscriptengine.h>
#include <QtScript/qscriptclasspropertyiterator.h>
#include <QtSql/qsqldatabase.h>
#include <QtSql/qsqlquery.h>
#include <QtSql/qsqlerror.h>
#include <QtSql/qsqlrecord.h>
#include <QtCore/qstack.h>
#include <QtCore/qcryptographichash.h>
#include <QtCore/qsettings.h>
#include <QtCore/qdir.h>
#include <QtCore/qdebug.h>
Classes
class QDeclarativeSqlQueryScriptClass
Macros
#define THROW_SQL(error, desc)
Enumerations
enum SqlException {
UNKNOWN_ERR, DATABASE_ERR, VERSION_ERR, TOO_LARGE_ERR,
QUOTA_ERR, SYNTAX_ERR, CONSTRAINT_ERR, TIMEOUT_ERR
}
Functions
static QScriptValue qmlsqldatabase_change_version (QScriptContext *context, QScriptEngine *engine)
static QString qmlsqldatabase_databaseFile (const QString &connectionName, QScriptEngine *engine)
static QString qmlsqldatabase_databasesPath (QScriptEngine *engine)
static QScriptValue qmlsqldatabase_executeSql (QScriptContext *context, QScriptEngine *engine)
static QScriptValue qmlsqldatabase_executeSql_outsidetransaction (QScriptContext *context, QScriptEngine *)
static QScriptValue qmlsqldatabase_executeSql_readonly (QScriptContext *context, QScriptEngine *engine)
static void qmlsqldatabase_initDatabasesPath (QScriptEngine *engine)
static QScriptValue qmlsqldatabase_item (QScriptContext *context, QScriptEngine *engine)
static QScriptValue qmlsqldatabase_open_sync (QScriptContext *context, QScriptEngine *engine)
static QScriptValue qmlsqldatabase_read_transaction (QScriptContext *context, QScriptEngine *engine)
static QScriptValue qmlsqldatabase_transaction (QScriptContext *context, QScriptEngine *engine)
static QScriptValue qmlsqldatabase_transaction_shared (QScriptContext *context, QScriptEngine *engine, bool readOnly)
void qt_add_qmlsqldatabase (QScriptEngine *engine)
Variables
static const char * sqlerror []
Macro Definition Documentation
THROW_SQL
#define THROW_SQL (error, desc)
Value:
{ \
    QScriptValue errorValue = context->throwError(desc); \
    errorValue.setProperty(QLatin1String("code"), error); \
    return errorValue; \
}
Definition at line 168 of file qdeclarativesqldatabase.cpp.
Referenced by qmlsqldatabase_change_version(), qmlsqldatabase_executeSql(), qmlsqldatabase_executeSql_outsidetransaction(), qmlsqldatabase_executeSql_readonly(), qmlsqldatabase_open_sync(), and qmlsqldatabase_transaction_shared().
Enumeration Type Documentation
SqlException
enum SqlException
Enumerator
UNKNOWN_ERR
DATABASE_ERR
VERSION_ERR
TOO_LARGE_ERR
QUOTA_ERR
SYNTAX_ERR
CONSTRAINT_ERR
TIMEOUT_ERR
Definition at line 145 of file qdeclarativesqldatabase.cpp.
                   {
     UNKNOWN_ERR,
     DATABASE_ERR,
     VERSION_ERR,
     TOO_LARGE_ERR,
     QUOTA_ERR,
     SYNTAX_ERR,
     CONSTRAINT_ERR,
     TIMEOUT_ERR
 };
Function Documentation
qmlsqldatabase_change_version()
static QScriptValue qmlsqldatabase_change_version (QScriptContext * context, QScriptEngine * engine) static
Definition at line 273 of file qdeclarativesqldatabase.cpp.
Referenced by qmlsqldatabase_open_sync().
 {
     if (context->argumentCount() < 2)
         return engine->undefinedValue();
     QSqlDatabase db = qscriptvalue_cast<QSqlDatabase>(context->thisObject());
     QString from_version = context->argument(0).toString();
     QString to_version = context->argument(1).toString();
     QScriptValue callback = context->argument(2);
     QScriptValue instance = engine->newObject();
     instance.setProperty(QLatin1String("executeSql"), engine->newFunction(qmlsqldatabase_executeSql,1));
     QScriptValue tx = engine->newVariant(instance,QVariant::fromValue(db));
     QString foundvers = context->thisObject().property(QLatin1String("version")).toString();
     if (from_version!=foundvers) {
         THROW_SQL(VERSION_ERR,QDeclarativeEngine::tr("Version mismatch: expected %1, found %2").arg(from_version).arg(foundvers));
         return engine->undefinedValue();
     }
     bool ok = true;
     if (callback.isFunction()) {
         ok = false;
         db.transaction();
         callback.call(QScriptValue(), QScriptValueList() << tx);
         if (engine->hasUncaughtException()) {
             db.rollback();
         } else {
             if (!db.commit()) {
                 db.rollback();
                 THROW_SQL(UNKNOWN_ERR,QDeclarativeEngine::tr("SQL transaction failed"));
             } else {
                 ok = true;
             }
         }
     }
     if (ok) {
         context->thisObject().setProperty(QLatin1String("version"), to_version, QScriptValue::ReadOnly);
 #ifndef QT_NO_SETTINGS
         QSettings ini(qmlsqldatabase_databaseFile(db.connectionName(),engine) + QLatin1String(".ini"), QSettings::IniFormat);
         ini.setValue(QLatin1String("Version"), to_version);
 #endif
     }
     return engine->undefinedValue();
 }
qmlsqldatabase_databaseFile()
static QString qmlsqldatabase_databaseFile (const QString & connectionName, QScriptEngine * engine) static
Definition at line 187 of file qdeclarativesqldatabase.cpp.
Referenced by qmlsqldatabase_change_version(), and qmlsqldatabase_open_sync().
 {
     return qmlsqldatabase_databasesPath(engine) + QDir::separator()
             + connectionName;
 }
qmlsqldatabase_databasesPath()
static QString qmlsqldatabase_databasesPath (QScriptEngine * engine) static
Definition at line 175 of file qdeclarativesqldatabase.cpp.
Referenced by qmlsqldatabase_databaseFile(), and qmlsqldatabase_initDatabasesPath().
 {
     QDeclarativeScriptEngine *qmlengine = static_cast<QDeclarativeScriptEngine*>(engine);
     return QDir::toNativeSeparators(qmlengine->offlineStoragePath)
             + QDir::separator() + QLatin1String("Databases");
 }
qmlsqldatabase_executeSql()
static QScriptValue qmlsqldatabase_executeSql (QScriptContext * context, QScriptEngine * engine) static
Definition at line 214 of file qdeclarativesqldatabase.cpp.
Referenced by qmlsqldatabase_change_version(), qmlsqldatabase_executeSql_readonly(), and qmlsqldatabase_transaction_shared().
 {
     QSqlDatabase db = qscriptvalue_cast<QSqlDatabase>(context->thisObject());
     QString sql = context->argument(0).toString();
     QSqlQuery query(db);
     bool err = false;
     QScriptValue result;
     if (query.prepare(sql)) {
         if (context->argumentCount() > 1) {
             QScriptValue values = context->argument(1);
             if (values.isObject()) {
                 if (values.isArray()) {
                     int size = values.property(QLatin1String("length")).toInt32();
                     for (int i = 0; i < size; ++i)
                         query.bindValue(i, values.property(i).toVariant());
                 } else {
                     for (QScriptValueIterator it(values); it.hasNext();) {
                         it.next();
                         query.bindValue(it.name(),it.value().toVariant());
                     }
                 }
             } else {
                 query.bindValue(0,values.toVariant());
             }
         }
         if (query.exec()) {
             result = engine->newObject();
             QDeclarativeScriptEngine *qmlengine = static_cast<QDeclarativeScriptEngine*>(engine);
             if (!qmlengine->sqlQueryClass)
                 qmlengine->sqlQueryClass = new QDeclarativeSqlQueryScriptClass(engine);
             QScriptValue rows = engine->newObject(qmlengine->sqlQueryClass);
             rows.setData(engine->newVariant(QVariant::fromValue(query)));
             rows.setProperty(QLatin1String("item"), engine->newFunction(qmlsqldatabase_item,1), QScriptValue::SkipInEnumeration);
             result.setProperty(QLatin1String("rows"),rows);
             result.setProperty(QLatin1String("rowsAffected"),query.numRowsAffected());
             result.setProperty(QLatin1String("insertId"),query.lastInsertId().toString());
         } else {
             err = true;
         }
     } else {
         err = true;
     }
     if (err)
         THROW_SQL(DATABASE_ERR,query.lastError().text());
     return result;
 }
qmlsqldatabase_executeSql_outsidetransaction()
static QScriptValue qmlsqldatabase_executeSql_outsidetransaction (QScriptContext * context, QScriptEngine *) static
Definition at line 209 of file qdeclarativesqldatabase.cpp.
Referenced by qmlsqldatabase_transaction_shared().
 {
     THROW_SQL(DATABASE_ERR,QDeclarativeEngine::tr("executeSql called outside transaction()"));
 }
qmlsqldatabase_executeSql_readonly()
static QScriptValue qmlsqldatabase_executeSql_readonly (QScriptContext * context, QScriptEngine * engine) static
Definition at line 263 of file qdeclarativesqldatabase.cpp.
Referenced by qmlsqldatabase_transaction_shared().
 {
     QString sql = context->argument(0).toString();
     if (sql.startsWith(QLatin1String("SELECT"),Qt::CaseInsensitive)) {
         return qmlsqldatabase_executeSql(context,engine);
     } else {
         THROW_SQL(SYNTAX_ERR,QDeclarativeEngine::tr("Read-only Transaction"))
     }
 }
qmlsqldatabase_initDatabasesPath()
static void qmlsqldatabase_initDatabasesPath (QScriptEngine * engine) static
Definition at line 182 of file qdeclarativesqldatabase.cpp.
Referenced by qmlsqldatabase_open_sync().
 {
     QDir().mkpath(qmlsqldatabase_databasesPath(engine));
 }
qmlsqldatabase_item()
static QScriptValue qmlsqldatabase_item (QScriptContext * context, QScriptEngine * engine) static
Definition at line 194 of file qdeclarativesqldatabase.cpp.
Referenced by qmlsqldatabase_executeSql().
 {
     QSqlQuery query = qscriptvalue_cast<QSqlQuery>(context->thisObject().data());
     int i = context->argument(0).toNumber();
     if (query.at() == i || query.seek(i)) { // Qt 4.6 doesn't optimize seek(at())
         QSqlRecord r = query.record();
         QScriptValue row = engine->newObject();
         for (int j=0; j<r.count(); ++j) {
             row.setProperty(r.fieldName(j), QScriptValue(engine,r.value(j).toString()));
         }
         return row;
     }
     return engine->undefinedValue();
 }
qmlsqldatabase_open_sync()
static QScriptValue qmlsqldatabase_open_sync (QScriptContext * context, QScriptEngine * engine) static
Definition at line 358 of file qdeclarativesqldatabase.cpp.
Referenced by qt_add_qmlsqldatabase().
 {
 #ifndef QT_NO_SETTINGS
     qmlsqldatabase_initDatabasesPath(engine);
     QSqlDatabase database;
     QString dbname = context->argument(0).toString();
     QString dbversion = context->argument(1).toString();
     QString dbdescription = context->argument(2).toString();
     int dbestimatedsize = context->argument(3).toNumber();
     QScriptValue dbcreationCallback = context->argument(4);
     QCryptographicHash md5(QCryptographicHash::Md5);
     md5.addData(dbname.toUtf8());
     QString dbid(QLatin1String(md5.result().toHex()));
     QString basename = qmlsqldatabase_databaseFile(dbid, engine);
     bool created = false;
     QString version = dbversion;
     {
         QSettings ini(basename+QLatin1String(".ini"),QSettings::IniFormat);
         if (QSqlDatabase::connectionNames().contains(dbid)) {
             database = QSqlDatabase::database(dbid);
             version = ini.value(QLatin1String("Version")).toString();
             if (version != dbversion && !dbversion.isEmpty() && !version.isEmpty())
                 THROW_SQL(VERSION_ERR,QDeclarativeEngine::tr("SQL: database version mismatch"));
         } else {
             created = !QFile::exists(basename+QLatin1String(".sqlite"));
             database = QSqlDatabase::addDatabase(QLatin1String("QSQLITE"), dbid);
             if (created) {
                 ini.setValue(QLatin1String("Name"), dbname);
                 if (dbcreationCallback.isFunction())
                     version = QString();
                 ini.setValue(QLatin1String("Version"), version);
                 ini.setValue(QLatin1String("Description"), dbdescription);
                 ini.setValue(QLatin1String("EstimatedSize"), dbestimatedsize);
                 ini.setValue(QLatin1String("Driver"), QLatin1String("QSQLITE"));
             } else {
                 if (!dbversion.isEmpty() && ini.value(QLatin1String("Version")) != dbversion) {
                     // Incompatible
                     THROW_SQL(VERSION_ERR,QDeclarativeEngine::tr("SQL: database version mismatch"));
                 }
                 version = ini.value(QLatin1String("Version")).toString();
             }
             database.setDatabaseName(basename+QLatin1String(".sqlite"));
         }
         if (!database.isOpen())
             database.open();
     }
     QScriptValue instance = engine->newObject();
     instance.setProperty(QLatin1String("transaction"), engine->newFunction(qmlsqldatabase_transaction,1));
     instance.setProperty(QLatin1String("readTransaction"), engine->newFunction(qmlsqldatabase_read_transaction,1));
     instance.setProperty(QLatin1String("version"), version, QScriptValue::ReadOnly);
     instance.setProperty(QLatin1String("changeVersion"), engine->newFunction(qmlsqldatabase_change_version,3));
     QScriptValue result = engine->newVariant(instance,QVariant::fromValue(database));
     if (created && dbcreationCallback.isFunction()) {
         dbcreationCallback.call(QScriptValue(), QScriptValueList() << result);
     }
     return result;
 #else
     return engine->undefinedValue();
 #endif // QT_NO_SETTINGS
 }
qmlsqldatabase_read_transaction()
static QScriptValue qmlsqldatabase_read_transaction (QScriptContext * context, QScriptEngine * engine) static
Definition at line 350 of file qdeclarativesqldatabase.cpp.
Referenced by qmlsqldatabase_open_sync().
 {
     return qmlsqldatabase_transaction_shared(context,engine,true);
 }
qmlsqldatabase_transaction()
static QScriptValue qmlsqldatabase_transaction (QScriptContext * context, QScriptEngine * engine) static
Definition at line 346 of file qdeclarativesqldatabase.cpp.
Referenced by qmlsqldatabase_open_sync().
 {
     return qmlsqldatabase_transaction_shared(context,engine,false);
 }
qmlsqldatabase_transaction_shared()
static QScriptValue qmlsqldatabase_transaction_shared (QScriptContext * context, QScriptEngine * engine, bool readOnly) static
Definition at line 321 of file qdeclarativesqldatabase.cpp.
Referenced by qmlsqldatabase_read_transaction(), and qmlsqldatabase_transaction().
 {
     QSqlDatabase db = qscriptvalue_cast<QSqlDatabase>(context->thisObject());
     QScriptValue callback = context->argument(0);
     if (!callback.isFunction())
         THROW_SQL(UNKNOWN_ERR,QDeclarativeEngine::tr("transaction: missing callback"));
     QScriptValue instance = engine->newObject();
     instance.setProperty(QLatin1String("executeSql"),
         engine->newFunction(readOnly ? qmlsqldatabase_executeSql_readonly : qmlsqldatabase_executeSql,1));
     QScriptValue tx = engine->newVariant(instance,QVariant::fromValue(db));
     db.transaction();
     callback.call(QScriptValue(), QScriptValueList() << tx);
     instance.setProperty(QLatin1String("executeSql"),
         engine->newFunction(qmlsqldatabase_executeSql_outsidetransaction));
     if (engine->hasUncaughtException()) {
         db.rollback();
     } else {
         if (!db.commit())
             db.rollback();
     }
     return engine->undefinedValue();
 }
qt_add_qmlsqldatabase()
void qt_add_qmlsqldatabase (QScriptEngine * engine)
Definition at line 429 of file qdeclarativesqldatabase.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     QScriptValue openDatabase = engine->newFunction(qmlsqldatabase_open_sync, 4);
     engine->globalObject().setProperty(QLatin1String("openDatabaseSync"), openDatabase);
     QScriptValue sqlExceptionPrototype = engine->newObject();
     for (int i=0; sqlerror[i]; ++i)
         sqlExceptionPrototype.setProperty(QLatin1String(sqlerror[i]),
             i,QScriptValue::ReadOnly | QScriptValue::Undeletable | QScriptValue::SkipInEnumeration);
     engine->globalObject().setProperty(QLatin1String("SQLException"), sqlExceptionPrototype);
 }
Variable Documentation
sqlerror
const char* sqlerror[] static
Initial value:
= {
    "UNKNOWN_ERR",
    "DATABASE_ERR",
    "VERSION_ERR",
    "TOO_LARGE_ERR",
    "QUOTA_ERR",
    "SYNTAX_ERR",
    "CONSTRAINT_ERR",
    "TIMEOUT_ERR",
    0
}
Definition at line 156 of file qdeclarativesqldatabase.cpp.
Referenced by qt_add_qmlsqldatabase().