Qt 4.8: /src/declarative/graphicsitems/qdeclarativeanchors.cpp File Reference
qdeclarativeanchors.cpp File Reference
#include "private/qdeclarativeanchors_p_p.h"
#include "qdeclarativeitem.h"
#include "private/qdeclarativeitem_p.h"
#include <qdeclarativeinfo.h>
#include <QDebug>
#include <moc_qdeclarativeanchors_p.cpp>
Functions
static qreal adjustedPosition (QGraphicsObject *item, QDeclarativeAnchorLine::AnchorLine anchorLine)
static qreal hcenter (QGraphicsItem *i)
static qreal position (QGraphicsObject *item, QDeclarativeAnchorLine::AnchorLine anchorLine)
QDeclarativeAnchorLine::AnchorLine reverseAnchorLine (QDeclarativeAnchorLine::AnchorLine anchorLine)
static qreal vcenter (QGraphicsItem *i)
Function Documentation
adjustedPosition()
static qreal adjustedPosition (QGraphicsObject * item, QDeclarativeAnchorLine::AnchorLine anchorLine) static
Definition at line 117 of file qdeclarativeanchors.cpp.
Referenced by QDeclarativeAnchorsPrivate::updateHorizontalAnchors(), and QDeclarativeAnchorsPrivate::updateVerticalAnchors().
 {
     qreal ret = 0.0;
     QGraphicsItemPrivate *d = QGraphicsItemPrivate::get(item);
     switch(anchorLine) {
     case QDeclarativeAnchorLine::Left:
         ret = 0.0;
         break;
     case QDeclarativeAnchorLine::Right:
         ret = d->width();
         break;
     case QDeclarativeAnchorLine::Top:
         ret = 0.0;
         break;
     case QDeclarativeAnchorLine::Bottom:
         ret = d->height();
         break;
     case QDeclarativeAnchorLine::HCenter:
         ret = hcenter(item);
         break;
     case QDeclarativeAnchorLine::VCenter:
         ret = vcenter(item);
         break;
     case QDeclarativeAnchorLine::Baseline:
         if (d->isDeclarativeItem)
             ret = static_cast<QDeclarativeItem*>(item)->baselineOffset();
         break;
     default:
         break;
     }
     return ret;
 }
hcenter()
static qreal hcenter (QGraphicsItem * i) static
Definition at line 56 of file qdeclarativeanchors.cpp.
Referenced by adjustedPosition(), QDeclarativeAnchorsPrivate::centerInChanged(), position(), and QDeclarativeAnchorsPrivate::updateHorizontalAnchors().
 {
     QGraphicsItemPrivate *item = QGraphicsItemPrivate::get(i);
     qreal width = item->width();
     int iw = width;
     if (iw % 2)
         return (width + 1) / 2;
     else
         return width / 2;
 }
position()
static qreal position (QGraphicsObject * item, QDeclarativeAnchorLine::AnchorLine anchorLine) static
Definition at line 82 of file qdeclarativeanchors.cpp.
Referenced by QAbstractScrollArea::addScrollBarWidget(), QTextBlock::begin(), QTextDocumentPrivate::block(), QDeclarativeAnchorsPrivate::calcStretch(), QPlainTextEdit::centerCursor(), QAccessibleStackedWidget::childAt(), QTextFragment::contains(), QOCICols::create(), QUrlPrivate::createErrorString(), QOCICols::createLobLocator(), QTextLine::cursorToX(), QTextLayout::draw(), QTextLayout::drawCursor(), QTreeView::drawRow(), QAbstractItemViewPrivate::dropOn(), QtMultimediaInternal::QAudioPacketFeeder::empty(), QTextBlock::end(), QDeclarativeListViewPrivate::endPositionAt(), QPatternist::InsertBeforeFN::evaluateSequence(), QtMultimediaInternal::QAudioPacketFeeder::feed(), QWingedEdge::findInsertStatus(), firstFramePosLessThanCursorPos(), QDeclarativeListViewPrivate::firstVisibleItem(), QDeclarativeGridViewPrivate::firstVisibleItem(), QDeclarativeGridViewPrivate::fixup(), QDeclarativeListViewPrivate::fixup(), flowPosition(), QTextTablePrivate::fragmentAdded(), QTextDocumentLayoutPrivate::frameIteratorForYPosition(), QTextFragment::glyphRuns(), QTextDocumentLayout::hitTest(), QTextDocumentLayoutPrivate::hitTest(), QTextTable::insertColumns(), QGlyphLayout::instance(), QTreeViewPrivate::itemDecorationRect(), QDeclarativeListView::itemsInserted(), QGlyphLayout::mid(), QString::mid(), QString::midRef(), QTextLineItemIterator::next(), QTextDocumentPrivate::nextCursorPosition(), QSqlRecord::operator!=(), QTextBlock::operator<(), QTextFragment::operator<(), QTextOption::Tab::operator==(), QSettingsKey::originalKeyPosition(), QDeclarativeListViewPrivate::originPosition(), CloseButton::paintEvent(), QNetworkCookiePrivate::parseSetCookieHeaderLine(), QRawFont::pathForGlyph(), QDeclarativeListViewPrivate::positionAt(), QDeclarativeGridViewPrivate::positionViewAtIndex(), QDeclarativeListViewPrivate::positionViewAtIndex(), QTextDocumentPrivate::previousCursorPosition(), QtMultimediaInternal::QAudioPacketFeeder::QAudioPacketFeeder(), QScript::qobjectProtoFuncFindChildren(), QStringRef::QStringRef(), QConfFileSettingsPrivate::readIniFile(), QConfFileSettingsPrivate::readIniSection(), QDeclarativeListViewPrivate::refill(), QTextControlPrivate::repaintSelection(), QExpandingLineEdit::resizeToContents(), QPatternist::XPath10CoreFunctions::retrieveExpression(), QDeclarativeRewrite::RewriteBinding::rewrite(), QAbstractSliderPrivate::scrollByDelta(), QHeaderView::sectionViewportPosition(), QListViewPrivate::selectionAllowed(), QAbstractItemViewPrivate::selectionBehaviorFlags(), QTextControl::selectionRect(), QWSCalibratedMouseHandler::sendFiltered(), QGlyphLayout::setInstance(), QDeclarativeRewrite::RewriteBinding::setName(), QHeaderView::setOffsetToLastSection(), QHeaderView::setOffsetToSectionPosition(), setPenAndDrawBackground(), QDeclarativeGradientStop::setPosition(), QTextLayout::setPreeditArea(), QListModeViewBase::setRowCount(), QAbstractSlider::setSliderPosition(), QMdiArea::setTabPosition(), QSlider::setTickPosition(), QPatternist::AccelTree::sourceLocation(), QTextBlock::text(), QTextBlock::textDirection(), QTextEdit::toHtml(), QFileDialogPrivate::toInternal(), QTextBoundaryFinder::type(), QDeclarativeListViewPrivate::updateCurrentSection(), QDeclarativeGridViewPrivate::updateFooter(), QDeclarativeListViewPrivate::updateFooter(), QDeclarativeGridViewPrivate::updateHeader(), QDeclarativeListViewPrivate::updateHeader(), QDeclarativeAnchorsPrivate::updateHorizontalAnchors(), QDeclarativeListViewPrivate::updateUnrequestedPositions(), QDeclarativeAnchorsPrivate::updateVerticalAnchors(), QSidebar::urls(), QCommonStylePrivate::viewItemDrawText(), QHeaderView::visualIndexAt(), QAccessibleTextInterface::~QAccessibleTextInterface(), and QTestEvent::~QTestEvent().
 {
     qreal ret = 0.0;
     QGraphicsItemPrivate *d = QGraphicsItemPrivate::get(item);
     switch(anchorLine) {
     case QDeclarativeAnchorLine::Left:
         ret = item->x();
         break;
     case QDeclarativeAnchorLine::Right:
         ret = item->x() + d->width();
         break;
     case QDeclarativeAnchorLine::Top:
         ret = item->y();
         break;
     case QDeclarativeAnchorLine::Bottom:
         ret = item->y() + d->height();
         break;
     case QDeclarativeAnchorLine::HCenter:
         ret = item->x() + hcenter(item);
         break;
     case QDeclarativeAnchorLine::VCenter:
         ret = item->y() + vcenter(item);
         break;
     case QDeclarativeAnchorLine::Baseline:
         if (d->isDeclarativeItem)
             ret = item->y() + static_cast<QDeclarativeItem*>(item)->baselineOffset();
         break;
     default:
         break;
     }
     return ret;
 }
reverseAnchorLine()
QDeclarativeAnchorLine::AnchorLine reverseAnchorLine (QDeclarativeAnchorLine::AnchorLine anchorLine) inline
Definition at line 586 of file qdeclarativeanchors.cpp.
Referenced by QDeclarativeAnchorsPrivate::updateHorizontalAnchors().
{
     if (anchorLine == QDeclarativeAnchorLine::Left) {
         return QDeclarativeAnchorLine::Right;
     } else if (anchorLine == QDeclarativeAnchorLine::Right) {
         return QDeclarativeAnchorLine::Left;
     } else {
         return anchorLine;
     }
 }
vcenter()
static qreal vcenter (QGraphicsItem * i) static
Definition at line 68 of file qdeclarativeanchors.cpp.
Referenced by adjustedPosition(), QDeclarativeAnchorsPrivate::centerInChanged(), position(), and QDeclarativeAnchorsPrivate::updateVerticalAnchors().
 {
     QGraphicsItemPrivate *item = QGraphicsItemPrivate::get(i);
     qreal height = item->height();
     int ih = height;
     if (ih % 2)
         return (height + 1) / 2;
     else
         return height / 2;
 }