Qt 4.8: /src/declarative/qml/qdeclarativeimport.cpp File Reference
qdeclarativeimport.cpp File Reference
#include "qdeclarativeimport_p.h"
#include <QtCore/qdebug.h>
#include <QtCore/qdir.h>
#include <QtCore/qfileinfo.h>
#include <QtCore/qpluginloader.h>
#include <QtCore/qlibraryinfo.h>
#include <QtCore/qalgorithms.h>
#include <QtDeclarative/qdeclarativeextensioninterface.h>
#include <private/qdeclarativeglobal_p.h>
#include <private/qdeclarativetypenamecache_p.h>
#include <private/qdeclarativeengine_p.h>
Classes
class QDeclarativeImportedNamespace
class QDeclarativeImportsPrivate
Typedefs
typedef QMap< QString, QString > StringStringMap
Functions
static QDeclarativeTypeNameCache * cacheForNamespace (QDeclarativeEngine *engine, const QDeclarativeImportedNamespace &set, QDeclarativeTypeNameCache *cache)
static bool greaterThan (const QString &s1, const QString &s2)
Q_GLOBAL_STATIC (StringStringMap, qmlEnginePluginsWithRegisteredTypes)
Typedef Documentation
StringStringMap
typedef QMap<QString, QString> StringStringMap
Definition at line 69 of file qdeclarativeimport.cpp.
Function Documentation
cacheForNamespace()
static QDeclarativeTypeNameCache* cacheForNamespace (QDeclarativeEngine * engine, const QDeclarativeImportedNamespace & set, QDeclarativeTypeNameCache * cache) static
Definition at line 173 of file qdeclarativeimport.cpp.
Referenced by QDeclarativeImports::populateCache().
 {
     if (!cache)
         cache = new QDeclarativeTypeNameCache(engine);
     QList<QDeclarativeType *> types = QDeclarativeMetaType::qmlTypes();
     for (int ii = 0; ii < set.uris.count(); ++ii) {
         QByteArray base = set.uris.at(ii).toUtf8() + '/';
         int major = set.majversions.at(ii);
         int minor = set.minversions.at(ii);
         foreach (QDeclarativeType *type, types) {
             if (type->qmlTypeName().startsWith(base) &&
                 type->qmlTypeName().lastIndexOf('/') == (base.length() - 1) &&
                 type->availableInVersion(major,minor))
             {
                 QString name = QString::fromUtf8(type->qmlTypeName().mid(base.length()));
                 cache->add(name, type);
             }
         }
     }
     return cache;
 }
greaterThan()
static bool greaterThan (const QString & s1, const QString & s2) static
Definition at line 64 of file qdeclarativeimport.cpp.
Referenced by QUrlInfo::lessThan(), QDeclarativeStyledTextPrivate::parseAttribute(), QDeclarativeStyledTextPrivate::parseCloseTag(), QDeclarativeStyledTextPrivate::parseTag(), and QDeclarativeImportsPrivate::resolvedUri().
 {
     return s1 > s2;
 }
Q_GLOBAL_STATIC()
Q_GLOBAL_STATIC (StringStringMap , qmlEnginePluginsWithRegisteredTypes)