Qt 4.8: /src/declarative/qml/parser/qdeclarativejsparser.cpp File Reference
qdeclarativejsparser.cpp File Reference
#include <QtCore/QtDebug>
#include <QtGui/QApplication>
#include <string.h>
#include "private/qdeclarativejsengine_p.h"
#include "private/qdeclarativejslexer_p.h"
#include "private/qdeclarativejsast_p.h"
#include "private/qdeclarativejsnodepool_p.h"
#include "private/qdeclarativejsparser_p.h"
#include <QVarLengthArray>
Functions
static bool automatic (Engine *driver, int token)
static AST::SourceLocation location (Lexer *lexer)
Function Documentation
automatic()
static bool automatic (Engine * driver, int token) inline static
Definition at line 78 of file qdeclarativejsparser.cpp.
Referenced by QDeclarativeJS::Parser::parse(), and QDeclarativeOpenMetaObject::QDeclarativeOpenMetaObject().
 {
     return token == QDeclarativeJSGrammar::T_RBRACE
         || token == 0
         || driver->lexer()->prevTerminator();
 }
location()
static AST::SourceLocation location (Lexer * lexer) inline static
Definition at line 107 of file qdeclarativejsparser.cpp.
Referenced by QDeclarativeJS::Parser::parse().
 {
     AST::SourceLocation loc;
     loc.offset = lexer->tokenOffset();
     loc.length = lexer->tokenLength();
     loc.startLine = lexer->startLineNo();
     loc.startColumn = lexer->startColumnNo();
     return loc;
 }