Qt 4.8: /src/declarative/qml/qdeclarativeglobal_p.h File Reference
qdeclarativeglobal_p.h File Reference
#include <QtCore/qglobal.h>
#include <QtCore/QObject>
Classes
struct QDeclarativeGraphics_DerivedObject
Macros
#define DEFINE_BOOL_CONFIG_OPTION(name, var)
#define Q_DECLARATIVE_PRIVATE_EXPORT Q_DECLARATIVE_EXPORT
Functions
bool QDeclarative_isFileCaseCorrect (const QString &fileName)
Returns true if the case of fileName is equivalent to the file case of fileName on disk, and false otherwise.
void QDeclarative_setParent_noEvent (QObject *object, QObject *parent)
Makes the object a child of parent.
Macro Definition Documentation
DEFINE_BOOL_CONFIG_OPTION
#define DEFINE_BOOL_CONFIG_OPTION (name, var)
Value:
static bool name() \
    { \
        static enum { Yes, No, Unknown } status = Unknown; \
        if (status == Unknown) { \
            QByteArray v = qgetenv(#var); \
            bool value = !v.isEmpty() && v != "0" && v != "false"; \
            if (value) status = Yes; \
            else status = No; \
        } \
        return status == Yes; \
    }
Definition at line 54 of file qdeclarativeglobal_p.h.
Q_DECLARATIVE_PRIVATE_EXPORT
#define Q_DECLARATIVE_PRIVATE_EXPORT Q_DECLARATIVE_EXPORT
Definition at line 70 of file qdeclarativeglobal_p.h.
Function Documentation
QDeclarative_isFileCaseCorrect()
bool QDeclarative_isFileCaseCorrect (const QString & fileName)
Returns true if the case of fileName is equivalent to the file case of fileName on disk, and false otherwise.
This is used to ensure that the behavior of QML on a case-insensitive file system is the same as on a case-sensitive file system. This function performs a "best effort" attempt to determine the real case of the file. It may have false positives (say the case is correct when it isn't), but it should never have a false negative (say the case is incorrect when it is correct).
Definition at line 2550 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeImportDatabase::importPlugin(), QDeclarativeDataLoader::load(), QDeclarativeDirParser::parse(), and QDeclarativeGraphics_DerivedObject::setParent_noEvent().
 {
 #if defined(Q_OS_MAC) || defined(Q_OS_WIN32)
     QFileInfo info(fileName);
     QString absolute = info.absoluteFilePath();
 #if defined(Q_OS_MAC)
     QString canonical = info.canonicalFilePath();
 #elif defined(Q_OS_WIN32)
     wchar_t buffer[1024];
     DWORD rv = ::GetShortPathName((wchar_t*)absolute.utf16(), buffer, 1024);
     if (rv == 0 || rv >= 1024) return true;
     rv = ::GetLongPathName(buffer, buffer, 1024);
     if (rv == 0 || rv >= 1024) return true;
     QString canonical((QChar *)buffer);
 #endif
     int absoluteLength = absolute.length();
     int canonicalLength = canonical.length();
     int length = qMin(absoluteLength, canonicalLength);
     for (int ii = 0; ii < length; ++ii) {
         const QChar &a = absolute.at(absoluteLength - 1 - ii);
         const QChar &c = canonical.at(canonicalLength - 1 - ii);
         if (a.toLower() != c.toLower())
             return true;
         if (a != c)
             return false;
     }
 #else
     Q_UNUSED(fileName)
 #endif
     return true;
 }
QDeclarative_setParent_noEvent()
void QDeclarative_setParent_noEvent (QObject * object, QObject * parent) inline
Makes the object a child of parent.
Note that when using this method, neither parent nor the object's previous parent (if it had one) will receive ChildRemoved or ChildAdded events.
Definition at line 101 of file qdeclarativeglobal_p.h.
Referenced by QDeclarativeLoaderPrivate::_q_sourceLoaded(), QDeclarativeAnimationGroupPrivate::append_animation(), QDeclarativeVisualItemModelPrivate::children_append(), QDeclarativeAnimationGroupPrivate::clear_animation(), QDeclarativeGridViewPrivate::createComponentItem(), QDeclarativeListViewPrivate::createComponentItem(), QDeclarativeTextInput::createCursor(), QDeclarativePathViewPrivate::createHighlight(), QDeclarativeGridViewPrivate::createHighlight(), QDeclarativeListViewPrivate::createHighlight(), QDeclarativeListViewPrivate::createSection(), QDeclarativeFlickablePrivate::init(), QDeclarativeBoundSignal::init(), QDeclarativeItemPrivate::init(), QDeclarativePauseAnimationPrivate::init(), QDeclarativeScriptActionPrivate::init(), QDeclarativePropertyActionPrivate::init(), QDeclarativePropertyAnimationPrivate::init(), QDeclarativeVisualDataModel::item(), QDeclarativeRepeater::itemsInserted(), QDeclarativeTextEdit::loadCursorDelegate(), QDeclarativeAnchorAnimation::QDeclarativeAnchorAnimation(), QDeclarativeParallelAnimation::QDeclarativeParallelAnimation(), QDeclarativeParentAnimation::QDeclarativeParentAnimation(), QDeclarativeSequentialAnimation::QDeclarativeSequentialAnimation(), QDeclarativeSmoothedAnimationPrivate::QDeclarativeSmoothedAnimationPrivate(), QDeclarativeRepeater::regenerate(), QDeclarativeVisualItemModel::release(), QDeclarativeVME::run(), QDeclarativeStateGroupPrivate::setCurrentStateInternal(), QDeclarativeGridViewPrivate::updateFooter(), QDeclarativeListViewPrivate::updateFooter(), QDeclarativeGridViewPrivate::updateHeader(), and QDeclarativeListViewPrivate::updateHeader().
 {
     static_cast<QDeclarativeGraphics_DerivedObject *>(object)->setParent_noEvent(parent);
 }