Qt 4.8: /src/declarative/qml/qdeclarativecompiledbindings.cpp File Reference
qdeclarativecompiledbindings.cpp File Reference
#include "private/qdeclarativecompiledbindings_p.h"
#include <QtDeclarative/qdeclarativeinfo.h>
#include <private/qdeclarativecontext_p.h>
#include <private/qdeclarativejsast_p.h>
#include <private/qdeclarativejsengine_p.h>
#include <private/qdeclarativeexpression_p.h>
#include <QtCore/qcoreapplication.h>
#include <QtCore/qdebug.h>
#include <QtCore/qnumeric.h>
#include <private/qdeclarativeanchors_p_p.h>
#include <private/qdeclarativeglobal_p.h>
#include <private/qdeclarativefastproperties_p.h>
#include <private/qdeclarativedebugtrace_p.h>
Classes
struct QDeclarativeBindingCompilerPrivate
struct QDeclarativeBindingCompilerPrivate::Result
class QDeclarativeCompiledBindingsPrivate
struct QDeclarativeCompiledBindingsPrivate::Binding
Macros
#define FOR_EACH_QML_INSTR(F)
#define QML_BEGIN_INSTR(I) case Instr::I:
#define QML_END_INSTR(I) break;
#define QML_INSTR_ADDR(I) &&op_##I,
#define QML_INSTR_ENUM(I) I,
#define QML_INSTR_HEADER
Functions
DEFINE_BOOL_CONFIG_OPTION (qmlExperimental, QML_EXPERIMENTAL)
DEFINE_BOOL_CONFIG_OPTION (qmlDisableOptimizer, QML_DISABLE_OPTIMIZER)
DEFINE_BOOL_CONFIG_OPTION (qmlDisableFastProperties, QML_DISABLE_FAST_PROPERTIES)
DEFINE_BOOL_CONFIG_OPTION (bindingsDump, QML_BINDINGS_DUMP)
static void dumpInstruction (const Instr *instr)
Q_GLOBAL_STATIC (QDeclarativeFastProperties, fastProperties)
static void throwException (int id, QDeclarativeDelayedError *error, Program *program, QDeclarativeContextData *context, const QString &description=QString())
static bool toBool (Register *reg, int type, bool *ok=0)
static qreal toReal (Register *reg, int type, bool *ok=0)
static QString toString (Register *reg, int type, bool *ok=0)
static QUrl toUrl (Register *reg, int type, QDeclarativeContextData *context, bool *ok=0)
static QObject * variantToQObject (const QVariant &value, bool *ok)
Macro Definition Documentation
FOR_EACH_QML_INSTR
#define FOR_EACH_QML_INSTR (F)
Definition at line 73 of file qdeclarativecompiledbindings.cpp.
Referenced by QDeclarativeCompiledBindingsPrivate::run().
QML_BEGIN_INSTR
#define QML_BEGIN_INSTR (I) case Instr::I:
Definition at line 130 of file qdeclarativecompiledbindings.cpp.
Referenced by QDeclarativeCompiledBindingsPrivate::run().
QML_END_INSTR
#define QML_END_INSTR (I) break;
Definition at line 131 of file qdeclarativecompiledbindings.cpp.
Referenced by QDeclarativeCompiledBindingsPrivate::run().
QML_INSTR_ADDR
#define QML_INSTR_ADDR (I) &&op_##I,
Definition at line 123 of file qdeclarativecompiledbindings.cpp.
Referenced by QDeclarativeCompiledBindingsPrivate::run().
QML_INSTR_ENUM
#define QML_INSTR_ENUM (I) I,
Definition at line 122 of file qdeclarativecompiledbindings.cpp.
Referenced by QDeclarativeCompiledBindingsPrivate::run().
QML_INSTR_HEADER
#define QML_INSTR_HEADER
Definition at line 132 of file qdeclarativecompiledbindings.cpp.
Referenced by QDeclarativeCompiledBindingsPrivate::run().
Function Documentation
DEFINE_BOOL_CONFIG_OPTION() [1/4]
DEFINE_BOOL_CONFIG_OPTION (qmlExperimental , QML_EXPERIMENTAL)
DEFINE_BOOL_CONFIG_OPTION() [2/4]
DEFINE_BOOL_CONFIG_OPTION (qmlDisableOptimizer , QML_DISABLE_OPTIMIZER)
DEFINE_BOOL_CONFIG_OPTION() [3/4]
DEFINE_BOOL_CONFIG_OPTION (qmlDisableFastProperties , QML_DISABLE_FAST_PROPERTIES)
DEFINE_BOOL_CONFIG_OPTION() [4/4]
DEFINE_BOOL_CONFIG_OPTION (bindingsDump , QML_BINDINGS_DUMP)
dumpInstruction()
static void dumpInstruction (const Instr * instr) static
Definition at line 1033 of file qdeclarativecompiledbindings.cpp.
Referenced by QDeclarativeBindingCompiler::dump(), and QDeclarativeCompiledBindingsPrivate::run().
 {
     switch (instr->common.type) {
     case Instr::Noop:
         qWarning().nospace() << "\t" << "Noop";
         break;
     case Instr::BindingId:
         qWarning().nospace() << instr->id.line << ":" << instr->id.column << ":";
         break;
     case Instr::Subscribe:
         qWarning().nospace() << "\t" << "Subscribe" << "\t\t" << instr->subscribe.offset << "\t" << instr->subscribe.reg << "\t" << instr->subscribe.index;
         break;
     case Instr::SubscribeId:
         qWarning().nospace() << "\t" << "SubscribeId" << "\t\t" << instr->subscribe.offset << "\t" << instr->subscribe.reg << "\t" << instr->subscribe.index;
         break;
     case Instr::FetchAndSubscribe:
         qWarning().nospace() << "\t" << "FetchAndSubscribe" << "\t" << instr->fetchAndSubscribe.output << "\t" << instr->fetchAndSubscribe.objectReg << "\t" << instr->fetchAndSubscribe.subscription;
         break;
     case Instr::LoadId:
         qWarning().nospace() << "\t" << "LoadId" << "\t\t\t" << instr->load.index << "\t" << instr->load.reg;
         break;
     case Instr::LoadScope:
         qWarning().nospace() << "\t" << "LoadScope" << "\t\t" << instr->load.index << "\t" << instr->load.reg;
         break;
     case Instr::LoadRoot:
         qWarning().nospace() << "\t" << "LoadRoot" << "\t\t" << instr->load.index << "\t" << instr->load.reg;
         break;
     case Instr::LoadAttached:
         qWarning().nospace() << "\t" << "LoadAttached" << "\t\t" << instr->attached.output << "\t" << instr->attached.reg << "\t" << instr->attached.id;
         break;
     case Instr::ConvertIntToReal:
         qWarning().nospace() << "\t" << "ConvertIntToReal" << "\t" << instr->unaryop.output << "\t" << instr->unaryop.src;
         break;
     case Instr::ConvertRealToInt:
         qWarning().nospace() << "\t" << "ConvertRealToInt" << "\t" << instr->unaryop.output << "\t" << instr->unaryop.src;
         break;
     case Instr::Real:
         qWarning().nospace() << "\t" << "Real" << "\t\t\t" << instr->real_value.reg << "\t" << instr->real_value.value;
         break;
     case Instr::Int:
         qWarning().nospace() << "\t" << "Int" << "\t\t\t" << instr->int_value.reg << "\t" << instr->int_value.value;
         break;
     case Instr::Bool:
         qWarning().nospace() << "\t" << "Bool" << "\t\t\t" << instr->bool_value.reg << "\t" << instr->bool_value.value;
         break;
     case Instr::String:
         qWarning().nospace() << "\t" << "String" << "\t\t\t" << instr->string_value.reg << "\t" << instr->string_value.offset << "\t" << instr->string_value.length;
         break;
     case Instr::AddReal:
         qWarning().nospace() << "\t" << "AddReal" << "\t\t\t" << instr->binaryop.output << "\t" << instr->binaryop.src1 << "\t" << instr->binaryop.src2;
         break;
     case Instr::AddInt:
         qWarning().nospace() << "\t" << "AddInt" << "\t\t\t" << instr->binaryop.output << "\t" << instr->binaryop.src1 << "\t" << instr->binaryop.src2;
         break;
     case Instr::AddString:
         qWarning().nospace() << "\t" << "AddString" << "\t\t" << instr->binaryop.output << "\t" << instr->binaryop.src1 << "\t" << instr->binaryop.src2;
         break;
     case Instr::MinusReal:
         qWarning().nospace() << "\t" << "MinusReal" << "\t\t" << instr->binaryop.output << "\t" << instr->binaryop.src1 << "\t" << instr->binaryop.src2;
         break;
     case Instr::MinusInt:
         qWarning().nospace() << "\t" << "MinusInt" << "\t\t" << instr->binaryop.output << "\t" << instr->binaryop.src1 << "\t" << instr->binaryop.src2;
         break;
     case Instr::CompareReal:
         qWarning().nospace() << "\t" << "CompareReal" << "\t\t" << instr->binaryop.output << "\t" << instr->binaryop.src1 << "\t" << instr->binaryop.src2;
         break;
     case Instr::CompareString:
         qWarning().nospace() << "\t" << "CompareString" << "\t\t" << instr->binaryop.output << "\t" << instr->binaryop.src1 << "\t" << instr->binaryop.src2;
         break;
     case Instr::NotCompareReal:
         qWarning().nospace() << "\t" << "NotCompareReal" << "\t\t" << instr->binaryop.output << "\t" << instr->binaryop.src1 << "\t" << instr->binaryop.src2;
         break;
     case Instr::NotCompareString:
         qWarning().nospace() << "\t" << "NotCompareString" << "\t\t" << instr->binaryop.output << "\t" << instr->binaryop.src1 << "\t" << instr->binaryop.src2;
         break;
     case Instr::GreaterThanReal:
         qWarning().nospace() << "\t" << "GreaterThanReal" << "\t\t" << instr->binaryop.output << "\t" << instr->binaryop.src1 << "\t" << instr->binaryop.src2;
         break;
     case Instr::MaxReal:
         qWarning().nospace() << "\t" << "MaxReal" << "\t\t\t" << instr->binaryop.output << "\t" << instr->binaryop.src1 << "\t" << instr->binaryop.src2;
         break;
     case Instr::MinReal:
         qWarning().nospace() << "\t" << "MinReal" << "\t\t\t" << instr->binaryop.output << "\t" << instr->binaryop.src1 << "\t" << instr->binaryop.src2;
         break;
     case Instr::NewString:
         qWarning().nospace() << "\t" << "NewString" << "\t\t" << instr->construct.reg;
         break;
     case Instr::NewUrl:
         qWarning().nospace() << "\t" << "NewUrl" << "\t\t\t" << instr->construct.reg;
         break;
     case Instr::CleanupString:
         qWarning().nospace() << "\t" << "CleanupString" << "\t\t" << instr->cleanup.reg;
         break;
     case Instr::CleanupUrl:
         qWarning().nospace() << "\t" << "CleanupUrl" << "\t\t" << instr->cleanup.reg;
         break;
     case Instr::Fetch:
         qWarning().nospace() << "\t" << "Fetch" << "\t\t\t" << instr->fetch.output << "\t" << instr->fetch.index << "\t" << instr->fetch.objectReg;
         break;
     case Instr::Store:
         qWarning().nospace() << "\t" << "Store" << "\t\t\t" << instr->store.output << "\t" << instr->store.index << "\t" << instr->store.reg;
         break;
     case Instr::Copy:
         qWarning().nospace() << "\t" << "Copy" << "\t\t\t" << instr->copy.reg << "\t" << instr->copy.src;
         break;
     case Instr::Skip:
         qWarning().nospace() << "\t" << "Skip" << "\t\t\t" << instr->skip.reg << "\t" << instr->skip.count;
         break;
     case Instr::Done:
         qWarning().nospace() << "\t" << "Done";
         break;
     case Instr::InitString:
         qWarning().nospace() << "\t" << "InitString" << "\t\t" << instr->initstring.offset << "\t" << instr->initstring.dataIdx;
         break;
     case Instr::FindGeneric:
         qWarning().nospace() << "\t" << "FindGeneric" << "\t\t" << instr->find.reg << "\t" << instr->find.name;
         break;
     case Instr::FindGenericTerminal:
         qWarning().nospace() << "\t" << "FindGenericTerminal" << "\t" << instr->find.reg << "\t" <<  instr->find.name;
         break;
     case Instr::FindProperty:
         qWarning().nospace() << "\t" << "FindProperty" << "\t\t" << instr->find.reg << "\t" << instr->find.src << "\t" << instr->find.name;
         break;
     case Instr::FindPropertyTerminal:
         qWarning().nospace() << "\t" << "FindPropertyTerminal" << "\t" << instr->find.reg << "\t" << instr->find.src << "\t" << instr->find.name;
         break;
     case Instr::CleanupGeneric:
         qWarning().nospace() << "\t" << "CleanupGeneric" << "\t\t" << instr->cleanup.reg;
         break;
     case Instr::ConvertGenericToReal:
         qWarning().nospace() << "\t" << "ConvertGenericToReal" << "\t" << instr->unaryop.output << "\t" << instr->unaryop.src;
         break;
     case Instr::ConvertGenericToBool:
         qWarning().nospace() << "\t" << "ConvertGenericToBool" << "\t" << instr->unaryop.output << "\t" << instr->unaryop.src;
         break;
     case Instr::ConvertGenericToString:
         qWarning().nospace() << "\t" << "ConvertGenericToString" << "\t" << instr->unaryop.output << "\t" << instr->unaryop.src;
         break;
     case Instr::ConvertGenericToUrl:
         qWarning().nospace() << "\t" << "ConvertGenericToUrl" << "\t" << instr->unaryop.output << "\t" << instr->unaryop.src;
         break;
     default:
         qWarning().nospace() << "\t" << "Unknown";
         break;
     }
 }
Q_GLOBAL_STATIC()
Q_GLOBAL_STATIC (QDeclarativeFastProperties , fastProperties)
throwException()
static void throwException (int id, QDeclarativeDelayedError * error, Program * program, QDeclarativeContextData * context, const QString & description = QString()) static
Definition at line 1012 of file qdeclarativecompiledbindings.cpp.
Referenced by QDeclarativeCompiledBindingsPrivate::run().
 {
     error->error.setUrl(context->url);
     if (description.isEmpty())
         error->error.setDescription(QLatin1String("TypeError: Result of expression is not an object"));
     else
         error->error.setDescription(description);
     if (id != 0xFF) {
         quint64 e = *((quint64 *)(program->data() + program->exceptionDataOffset) + id);
         error->error.setLine((e >> 32) & 0xFFFFFFFF);
         error->error.setColumn(e & 0xFFFFFFFF);
     } else {
         error->error.setLine(-1);
         error->error.setColumn(-1);
     }
     if (!context->engine || !error->addError(QDeclarativeEnginePrivate::get(context->engine)))
         QDeclarativeEnginePrivate::warning(context->engine, error->error);
 }
toBool()
static bool toBool (Register * reg, int type, bool * ok = 0) inline static
Definition at line 811 of file qdeclarativecompiledbindings.cpp.
Referenced by QX11Data::clipboardWaitForEvent(), QScriptEnginePrivate::convertValue(), QScriptEnginePrivate::get(), QMacPrintEngine::metric(), QNetworkAccessHttpBackend::postRequest(), QDBusDemarshaller::QDBusDemarshaller(), QDeclarativeCompiledBindingsPrivate::run(), and QVariant::swap().
 {
     if (ok) *ok = true;
     if (type == QMetaType::Bool) {
         return reg->getbool();
     } else if (type == qMetaTypeId<QVariant>()) {
         return reg->getvariantptr()->toBool();
     } else {
         if (ok) *ok = false;
         return false;
     }
 }
toReal()
static qreal toReal (Register * reg, int type, bool * ok = 0) inline static
Definition at line 779 of file qdeclarativecompiledbindings.cpp.
Referenced by QFontEngine::addBitmapFontToPath(), QFontEngineBox::boundingBox(), QTextLayout::boundingRect(), QTextTableData::cellRect(), QFontEngineMac::draw(), QTextLine::draw(), QTextLayout::drawCursor(), QTextDocumentLayoutPrivate::drawFrame(), QTextDocumentLayoutPrivate::drawFrameDecoration(), QOpenGLPaintEngine::drawStaticTextItem(), QTextDocumentLayoutPrivate::drawTableCell(), QEmulationPaintEngine::drawTextItem(), QPainter::drawTextItem(), QFontEngineQPA::extractHeaderField(), QFontEngineQPF::extractHeaderField(), QFontEngine::getGlyphBearings(), QFontMetricsF::height(), QFontEngineMac::imageForGlyph(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutFlow(), QFontMetricsF::lineSpacing(), QProxyFontEngine::maxCharWidth(), QProxyFontEngine::minLeftBearing(), QProxyFontEngine::minRightBearing(), QFreetypeFace::properties(), QFontEngine::properties(), qt_format_text(), QDeclarativeCompiledBindingsPrivate::run(), and QVariant::swap().
 {
     if (ok) *ok = true;
     if (type == QMetaType::QReal) {
         return reg->getqreal();
     } else if (type == qMetaTypeId<QVariant>()) {
         return reg->getvariantptr()->toReal();
     } else {
         if (ok) *ok = false;
         return 0;
     }
 }
toString()
static QString toString (Register * reg, int type, bool * ok = 0) inline static
Definition at line 793 of file qdeclarativecompiledbindings.cpp.
Referenced by QDeclarativeImports::addImport(), QIcdEngine::asyncUpdateConfigurationsSlot(), QStringRef::clear(), QAxBase::connectNotify(), convert(), QScriptEnginePrivate::convertValue(), DumpIDL(), QScreen::exposeRegion(), QPatternist::AnyURI::fromLexical(), QNetworkAccessFtpBackend::ftpDone(), QScriptEnginePrivate::get(), QMainWindowLayout::insertIntoMacToolbar(), QSqlRecord::isGenerated(), QDate::isNull(), QTime::isNull(), QNetworkAccessFileBackend::loadFileInfo(), QFSFileEnginePrivate::map(), QScriptErrorLogWidget::message(), messageToScriptValue(), QSqlIndex::name(), QSettingsGroup::name(), QFSFileEnginePrivate::nativeRead(), QFSFileEnginePrivate::nativeWrite(), QDomDocument::nodeType(), QNetworkAccessCacheBackend::open(), QNetworkAccessFileBackend::open(), QUuid::operator QString(), QSqlRecord::operator!=(), QXmlStreamReaderPrivate::parse(), QEglProperties::properties(), QDBusDemarshaller::QDBusDemarshaller(), QFontEngineQPA::QFontEngineQPA(), QFontEngineQPF::QFontEngineQPF(), QNetworkSessionPrivateImpl::QNetworkSessionPrivateImpl(), QUuid::QUuid(), MetaObjectGenerator::readClassInfo(), QNetworkAccessFileBackend::readMoreFromFile(), QDeclarativeImports::resolveType(), QDeclarativeCompiledBindingsPrivate::run(), setCloseOnExec(), QSqlIndex::setDescending(), QMacPrintEnginePrivate::setPaperSize(), QDirModelPrivate::size(), QFileSystemModelPrivate::size(), QSortedModelEngine::sortOrder(), QDeclarativeVisualDataModel::stringValue(), QUrl::swap(), QVariant::swap(), QAccessibleItemRow::text(), QLocale::toString(), QFSFileEnginePrivate::unmap(), QNetworkAccessFileBackend::uploadReadyReadSlot(), QPatternist::MaintainingReader< XSLTTokenLookup >::validateElement(), and QListModelInterface::~QListModelInterface().
 {
     if (ok) *ok = true;
     if (type == QMetaType::QReal) {
         return QString::number(reg->getqreal());
     } else if (type == QMetaType::Int) {
         return QString::number(reg->getint());
     } else if (type == qMetaTypeId<QVariant>()) {
         return reg->getvariantptr()->toString();
     } else if (type == QMetaType::QString) {
         return *reg->getstringptr();
     } else {
         if (ok) *ok = false;
         return QString();
     }
 }
toUrl()
static QUrl toUrl (Register * reg, int type, QDeclarativeContextData * context, bool * ok = 0) inline static
Definition at line 825 of file qdeclarativecompiledbindings.cpp.
Referenced by QUrlModel::addUrls(), QDragManager::drag(), QDeclarativeCompiledBindingsPrivate::run(), QSidebar::showContextMenu(), QVariant::swap(), and QUrlModel::urls().
 {
     if (ok) *ok = true;
     QUrl base;
     if (type == qMetaTypeId<QVariant>()) {
         QVariant *var = reg->getvariantptr();
         int vt = var->type();
         if (vt == QVariant::Url) {
             base = var->toUrl();
         } else if (vt == QVariant::ByteArray) {
             base = QUrl(QString::fromUtf8(var->toByteArray()));
         } else if (vt == QVariant::String) {
             base = QUrl(var->toString());
         } else {
             if (ok) *ok = false;
             return QUrl();
         }
     } else if (type == QMetaType::QString) {
         base = QUrl(*reg->getstringptr());
     } else {
         if (ok) *ok = false;
         return QUrl();
     }
     if (!base.isEmpty() && base.isRelative())
         return context->url.resolved(base);
     else
         return base;
 }
variantToQObject()
static QObject* variantToQObject (const QVariant & value, bool * ok) static
Definition at line 856 of file qdeclarativecompiledbindings.cpp.
Referenced by QDeclarativeCompiledBindingsPrivate::findgeneric(), and QDeclarativeCompiledBindingsPrivate::findproperty().
 {
     if (ok) *ok = true;
     if (value.userType() == QMetaType::QObjectStar) {
         return qvariant_cast<QObject*>(value);
     } else {
         if (ok) *ok = false;
         return 0;
     }
 }