Qt 4.8: /src/xmlpatterns/data/qdecimal_p.h File Reference
qdecimal_p.h File Reference
#include "qschemanumeric_p.h"
Classes
class QPatternist::Decimal
Implements the value instance of the xs:decimal type.
Namespaces
QPatternist
The namespace for the internal API of QtXmlPatterns.
Functions
Q_CORE_EXPORT char * qdtoa (double d, int mode, int ndigits, int *decpt, int *sign, char **rve, char **resultp)
Function Documentation
qdtoa()
Q_CORE_EXPORT char* qdtoa (double d, int mode, int ndigits, int * decpt, int * sign, char ** rve, char ** resultp)
Defined in QtCore's qlocale.cpp.
Definition at line 2271 of file qlocale_tools.cpp.
Referenced by _qdtoa(), QLocalePrivate::doubleToString(), QPatternist::AbstractFloat< isDouble >::stringValue(), and QPatternist::Decimal::toString().
 {
     // Some values of the floating-point control word can cause _qdtoa to crash with an underflow.
     // We set a safe value here.
 #ifdef Q_OS_WIN
     _clear87();
     unsigned int oldbits = _control87(0, 0);
 #ifndef MCW_EM
 #    ifdef _MCW_EM
 #        define MCW_EM _MCW_EM
 #    else
 #        define MCW_EM 0x0008001F
 #    endif
 #endif
     _control87(MCW_EM, MCW_EM);
 #endif
 #if defined(Q_OS_LINUX) && !defined(__UCLIBC__)
     fenv_t envp;
     feholdexcept(&envp);
 #endif
     char *s = _qdtoa(d, mode, ndigits, decpt, sign, rve, resultp);
 #ifdef Q_OS_WIN
     _clear87();
 #ifndef _M_X64
     _control87(oldbits, 0xFFFFF);
 #else
     _control87(oldbits, _MCW_EM|_MCW_DN|_MCW_RC);
 #endif //_M_X64
 #endif //Q_OS_WIN
 #if defined(Q_OS_LINUX) && !defined(__UCLIBC__)
     fesetenv(&envp);
 #endif
     return s;
 }