Qt 4.8: /src/declarative/graphicsitems/qdeclarativepathview.cpp File Reference
qdeclarativepathview.cpp File Reference
#include "private/qdeclarativepathview_p.h"
#include "private/qdeclarativepathview_p_p.h"
#include <qdeclarativestate_p.h>
#include <qdeclarativeopenmetaobject_p.h>
#include <QDebug>
#include <QEvent>
#include <qlistmodelinterface_p.h>
#include <QGraphicsSceneEvent>
#include <qmath.h>
#include <math.h>
Functions
qreal qmlMod (qreal x, qreal y)
Variables
static QDeclarativeOpenMetaObjectType * qPathViewAttachedType = 0
Function Documentation
qmlMod()
qreal qmlMod (qreal x, qreal y) inline
Definition at line 57 of file qdeclarativepathview.cpp.
Referenced by QDeclarativePathViewPrivate::calcCurrentIndex(), QDeclarativePathView::componentComplete(), QDeclarativePathViewPrivate::positionOfIndex(), QDeclarativePathViewPrivate::setHighlightPosition(), QDeclarativePathViewPrivate::setOffset(), and QDeclarativePathViewPrivate::snapToCurrent().
 {
 #ifdef QT_USE_MATH_H_FLOATS
     if(sizeof(qreal) == sizeof(float))
         return fmodf(float(x), float(y));
     else
 #endif
         return fmod(x, y);
 }
Variable Documentation
qPathViewAttachedType
QDeclarativeOpenMetaObjectType* qPathViewAttachedType = 0 static
Definition at line 67 of file qdeclarativepathview.cpp.