Qt 4.8: /src/declarative/qml/qdeclarativescriptparser.cpp File Reference
qdeclarativescriptparser.cpp File Reference
#include "private/qdeclarativescriptparser_p.h"
#include "private/qdeclarativeparser_p.h"
#include "parser/qdeclarativejsengine_p.h"
#include "parser/qdeclarativejsparser_p.h"
#include "parser/qdeclarativejslexer_p.h"
#include "parser/qdeclarativejsnodepool_p.h"
#include "parser/qdeclarativejsastvisitor_p.h"
#include "parser/qdeclarativejsast_p.h"
#include "private/qdeclarativerewrite_p.h"
#include <QStack>
#include <QCoreApplication>
#include <QtDebug>
Classes
class QDeclarativeScriptParserJsASTData
Macros
#define CHECK_LINE if(l.currentLineNo() != startLine) return rv;
#define CHECK_TOKEN(t) if (token != QDeclarativeJSGrammar:: t) return rv;
Functions
static bool isUriToken (int token)
static void replaceWithSpace (QString &str, int idx, int n)
Variables
static const int uriTokens []
Macro Definition Documentation
CHECK_LINE
#define CHECK_LINE if(l.currentLineNo() != startLine) return rv;
Definition at line 953 of file qdeclarativescriptparser.cpp.
Referenced by QDeclarativeScriptParser::extractMetaData().
CHECK_TOKEN
#define CHECK_TOKEN (t) if (token != QDeclarativeJSGrammar:: t) return rv;
Definition at line 954 of file qdeclarativescriptparser.cpp.
Referenced by QDeclarativeScriptParser::extractMetaData().
Function Documentation
isUriToken()
static bool isUriToken (int token) inline static
Definition at line 996 of file qdeclarativescriptparser.cpp.
Referenced by QDeclarativeScriptParser::extractMetaData().
 {
     const int *current = uriTokens;
     while (*current != QDeclarativeJSGrammar::EOF_SYMBOL) {
         if (*current == token)
             return true;
         ++current;
     }
     return false;
 }
replaceWithSpace()
static void replaceWithSpace (QString & str, int idx, int n) static
Definition at line 891 of file qdeclarativescriptparser.cpp.
Referenced by QDeclarativeScriptParser::extractMetaData(), and QDeclarativeScriptParser::extractPragmas().
 {
     QChar *data = str.data() + idx;
     const QChar space(QLatin1Char(' '));
     for (int ii = 0; ii < n; ++ii)
         *data++ = space;
 }
Variable Documentation
uriTokens
const int uriTokens[] static
Definition at line 956 of file qdeclarativescriptparser.cpp.
Referenced by isUriToken().