Qt 4.8: /src/declarative/qml/qdeclarative.h File Reference
qdeclarative.h File Reference
#include <QtDeclarative/qdeclarativeprivate.h>
#include <QtDeclarative/qdeclarativeparserstatus.h>
#include <QtDeclarative/qdeclarativepropertyvaluesource.h>
#include <QtDeclarative/qdeclarativepropertyvalueinterceptor.h>
#include <QtDeclarative/qdeclarativelist.h>
#include <QtCore/qbytearray.h>
#include <QtCore/qmetaobject.h>
Macros
#define QML_DECLARE_INTERFACE(INTERFACE) QML_DECLARE_TYPE(INTERFACE)
#define QML_DECLARE_INTERFACE_HASMETATYPE(INTERFACE) QML_DECLARE_TYPE_HASMETATYPE(INTERFACE)
#define QML_DECLARE_TYPE(TYPE)
#define QML_DECLARE_TYPE_HASMETATYPE(TYPE) Q_DECLARE_METATYPE(QDeclarativeListProperty<TYPE>)
#define QML_DECLARE_TYPEINFO(TYPE, FLAGS)
Enumerations
enum { QML_HAS_ATTACHED_PROPERTIES = 0x01 }
Functions
Q_DECLARATIVE_EXPORT QObject * qmlAttachedPropertiesObject (int *, const QObject *, const QMetaObject *, bool create)
template<typename T >
QObject * qmlAttachedPropertiesObject (const QObject *obj, bool create=true)
Q_DECLARATIVE_EXPORT QObject * qmlAttachedPropertiesObjectById (int, const QObject *, bool create=true)
Q_DECLARATIVE_EXPORT QDeclarativeContext * qmlContext (const QObject *)
Q_DECLARATIVE_EXPORT QDeclarativeEngine * qmlEngine (const QObject *)
Q_DECLARATIVE_EXPORT void qmlExecuteDeferred (QObject *)
template<typename T >
int qmlRegisterCustomType (const char *uri, int versionMajor, int versionMinor, const char *qmlName, QDeclarativeCustomParser *parser)
template<typename T , typename E >
int qmlRegisterExtendedType ()
template<typename T , typename E >
int qmlRegisterExtendedType (const char *uri, int versionMajor, int versionMinor, const char *qmlName)
template<typename T >
int qmlRegisterInterface (const char *typeName)
template<typename T , int metaObjectRevision>
int qmlRegisterRevision (const char *uri, int versionMajor, int versionMinor)
template<typename T >
int qmlRegisterType ()
template<typename T >
int qmlRegisterType (const char *uri, int versionMajor, int versionMinor, const char *qmlName)
template<typename T , int metaObjectRevision>
int qmlRegisterType (const char *uri, int versionMajor, int versionMinor, const char *qmlName)
int Q_AUTOTEST_EXPORT qmlRegisterTypeNotAvailable (const char *uri, int versionMajor, int versionMinor, const char *qmlName, const QString &message)
template<typename T >
int qmlRegisterUncreatableType (const char *uri, int versionMajor, int versionMinor, const char *qmlName, const QString &reason)
Macro Definition Documentation
QML_DECLARE_INTERFACE
#define QML_DECLARE_INTERFACE (INTERFACE) QML_DECLARE_TYPE(INTERFACE)
Definition at line 63 of file qdeclarative.h.
QML_DECLARE_INTERFACE_HASMETATYPE
#define QML_DECLARE_INTERFACE_HASMETATYPE (INTERFACE) QML_DECLARE_TYPE_HASMETATYPE(INTERFACE)
Definition at line 66 of file qdeclarative.h.
QML_DECLARE_TYPE
#define QML_DECLARE_TYPE (TYPE)
Value:
Q_DECLARE_METATYPE(TYPE *) \
    Q_DECLARE_METATYPE(QDeclarativeListProperty<TYPE>)
Definition at line 56 of file qdeclarative.h.
Referenced by QDeclarativeVisualDataModel::_q_destroyingPackage(), QDeclarativeAnchorChanges::needsCopy(), QDeclarativePropertyChangesParser::QDeclarativePropertyChangesParser(), qmlAttachedPropertiesObject(), and qobject_cast().
QML_DECLARE_TYPE_HASMETATYPE
#define QML_DECLARE_TYPE_HASMETATYPE (TYPE) Q_DECLARE_METATYPE(QDeclarativeListProperty<TYPE>)
Definition at line 60 of file qdeclarative.h.
QML_DECLARE_TYPEINFO
#define QML_DECLARE_TYPEINFO (TYPE, FLAGS)
Value:
QT_BEGIN_NAMESPACE \
template <> \
class QDeclarativeTypeInfo<TYPE > \
{ \
public: \
    enum { \
        hasAttachedProperties = (((FLAGS) & QML_HAS_ATTACHED_PROPERTIES) == QML_HAS_ATTACHED_PROPERTIES) \
    }; \
}; \
QT_END_NAMESPACE
Definition at line 73 of file qdeclarative.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
QML_HAS_ATTACHED_PROPERTIES
Definition at line 69 of file qdeclarative.h.
      { /* TYPEINFO flags */
     QML_HAS_ATTACHED_PROPERTIES = 0x01
 };
Function Documentation
qmlAttachedPropertiesObject() [1/2]
Q_DECLARATIVE_EXPORT QObject* qmlAttachedPropertiesObject (int * , const QObject * , const QMetaObject * , bool create)
Definition at line 1106 of file qdeclarativeengine.cpp.
Referenced by qmlAttachedPropertiesObject(), and qmlRegisterCustomType().
 {
     if (*idCache == -1)
         *idCache = QDeclarativeMetaType::attachedPropertiesFuncId(attachedMetaObject);
     if (*idCache == -1 || !object)
         return 0;
     return qmlAttachedPropertiesObjectById(*idCache, object, create);
 }
qmlAttachedPropertiesObject() [2/2]
template<typename T > QObject* qmlAttachedPropertiesObject (const QObject * obj, bool create = true)
Definition at line 402 of file qdeclarative.h.
 {
     static int idx = -1;
     return qmlAttachedPropertiesObject(&idx, obj, &T::staticMetaObject, create);
 }
qmlAttachedPropertiesObjectById()
Q_DECLARATIVE_EXPORT QObject* qmlAttachedPropertiesObjectById (int , const QObject * , bool create = true)
Definition at line 1084 of file qdeclarativeengine.cpp.
Referenced by QDeclarativePropertyPrivate::initProperty(), qmlAttachedPropertiesObject(), qmlRegisterCustomType(), QDeclarativeTypeNameScriptClass::queryProperty(), and QDeclarativeCompiledBindingsPrivate::run().
 {
     QDeclarativeData *data = QDeclarativeData::get(object);
     if (!data)
         return 0; // Attached properties are only on objects created by QML
     QObject *rv = data->hasExtendedData()?data->attachedProperties()->value(id):0;
     if (rv || !create)
         return rv;
     QDeclarativeAttachedPropertiesFunc pf = QDeclarativeMetaType::attachedPropertiesFuncById(id);
     if (!pf)
         return 0;
     rv = pf(const_cast<QObject *>(object));
     if (rv)
         data->attachedProperties()->insert(id, rv);
     return rv;
 }
qmlContext()
Q_DECLARATIVE_EXPORT QDeclarativeContext* qmlContext (const QObject *)
Definition at line 1073 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeLoaderPrivate::_q_sourceLoaded(), QDeclarativePropertyChanges::actions(), QDeclarativeParentChange::actions(), QDeclarativeAnchorChanges::actions(), QDeclarativeAnchorChanges::additionalActions(), QDeclarativeWatcher::addWatch(), QDeclarativePropertyChanges::changeExpression(), QDeclarativeGestureArea::connectSignals(), QDeclarativeConnections::connectSignals(), QDeclarativeGridViewPrivate::createComponentItem(), QDeclarativeListViewPrivate::createComponentItem(), QDeclarativePathViewPrivate::createHighlight(), QDeclarativeAbstractAnimationPrivate::createProperty(), QDeclarativeListViewPrivate::createSection(), QDeclarativeComponent::creationContext(), QDeclarativePropertyChangesPrivate::decode(), QDeclarativeXmlListModel::get(), QDeclarativeVisualDataModel::item(), QDeclarativeTextEdit::loadCursorDelegate(), QTextDocumentWithImageResources::loadResource(), QDeclarativeEngineDebugService::messageReceived(), QDeclarativeEngineDebugService::objectData(), QDeclarativePropertyChangesPrivate::property(), qmlRegisterCustomType(), QDeclarativeXmlListModel::reload(), QDeclarativeEngineDebugService::resetBinding(), QDeclarativeEngineDebugService::setBinding(), QDeclarativeRepeater::setDelegate(), QDeclarativeGridView::setDelegate(), QDeclarativePathView::setDelegate(), QDeclarativeListView::setDelegate(), QDeclarativeEngineDebugService::setMethodBody(), QDeclarativeRepeater::setModel(), QDeclarativePathView::setModel(), QDeclarativeGridView::setModel(), QDeclarativeListView::setModel(), and QDeclarativeFontLoader::setSource().
 {
     return QDeclarativeEngine::contextForObject(obj);
 }
qmlEngine()
Q_DECLARATIVE_EXPORT QDeclarativeEngine* qmlEngine (const QObject *)
Definition at line 1078 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeLoaderPrivate::_q_sourceLoaded(), QDeclarativeXmlListModel::classBegin(), QDeclarativePathView::createdItem(), QDeclarativeWorkerScript::engine(), QDeclarativeWorkerScript::event(), FlatListModel::get(), NestedListModel::get(), QDeclarativePathViewPrivate::getItem(), QDeclarativeBorderImage::load(), QDeclarativeImageBase::load(), QDeclarativeAnimatedImage::load(), QDeclarativeItem::mapFromItem(), QDeclarativeItem::mapToItem(), ModelNode::object(), QDeclarativeComponent::qmlAttachedProperties(), qmlRegisterCustomType(), QDeclarativeXmlListModel::reload(), QDeclarativeXmlListModel::requestFinished(), QDeclarativeBorderImage::setGridScaledImage(), QDeclarativeVisualDataModel::setModel(), QDeclarativeAbstractAnimation::setRunning(), QDeclarativeLoader::setSource(), QDeclarativeFontLoader::setSource(), QDeclarativeParticles::setSource(), QDeclarativeBehavior::setTarget(), and QDeclarativeInfo::~QDeclarativeInfo().
 {
     QDeclarativeContext *context = QDeclarativeEngine::contextForObject(obj);
     return context?context->engine():0;
 }
qmlExecuteDeferred()
Q_DECLARATIVE_EXPORT void qmlExecuteDeferred (QObject *)
Definition at line 1047 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeState::apply(), QDeclarativeStatePrivate::generateActionList(), QDeclarativeTransition::prepare(), QDeclarativeEngineDebugService::prepareDeferredObjects(), qmlRegisterCustomType(), and QDeclarativeBehavior::write().
 {
     QDeclarativeData *data = QDeclarativeData::get(object);
     if (data && data->deferredComponent) {
         if (QDeclarativeDebugService::isDebuggingEnabled()) {
             QDeclarativeDebugTrace::startRange(QDeclarativeDebugTrace::Creating);
             QDeclarativeType *type = QDeclarativeMetaType::qmlType(object->metaObject());
             QString typeName = type ? QLatin1String(type->qmlTypeName()) : QString::fromLatin1(object->metaObject()->className());
             QDeclarativeDebugTrace::rangeData(QDeclarativeDebugTrace::Creating, typeName);
             if (data->outerContext)
                 QDeclarativeDebugTrace::rangeLocation(QDeclarativeDebugTrace::Creating, data->outerContext->url, data->lineNumber);
         }
         QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(data->context->engine);
         QDeclarativeComponentPrivate::ConstructionState state;
         QDeclarativeComponentPrivate::beginDeferred(ep, object, &state);
         data->deferredComponent->release();
         data->deferredComponent = 0;
         QDeclarativeComponentPrivate::complete(ep, &state);
         QDeclarativeDebugTrace::endRange(QDeclarativeDebugTrace::Creating);
     }
 }
qmlRegisterCustomType()
template<typename T > int qmlRegisterCustomType (const char * uri, int versionMajor, int versionMinor, const char * qmlName, QDeclarativeCustomParser * parser)
Definition at line 359 of file qdeclarative.h.
 {
     QByteArray name(T::staticMetaObject.className());
     QByteArray pointerName(name + '*');
     QByteArray listName("QDeclarativeListProperty<" + name + ">");
     QDeclarativePrivate::RegisterType type = {
         0,
         qRegisterMetaType<T *>(pointerName.constData()),
         qRegisterMetaType<QDeclarativeListProperty<T> >(listName.constData()),
         sizeof(T), QDeclarativePrivate::createInto<T>,
         QString(),
         uri, versionMajor, versionMinor, qmlName, &T::staticMetaObject,
         QDeclarativePrivate::attachedPropertiesFunc<T>(),
         QDeclarativePrivate::attachedPropertiesMetaObject<T>(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativeParserStatus>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueSource>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueInterceptor>::cast(),
         0, 0,
         parser,
         0
     };
     return QDeclarativePrivate::qmlregister(QDeclarativePrivate::TypeRegistration, &type);
 }
qmlRegisterExtendedType() [1/2]
template<typename T , typename E > int qmlRegisterExtendedType ()
Definition at line 263 of file qdeclarative.h.
 {
     QByteArray name(T::staticMetaObject.className());
     QByteArray pointerName(name + '*');
     QByteArray listName("QDeclarativeListProperty<" + name + ">");
     QDeclarativePrivate::RegisterType type = {
         0,
         qRegisterMetaType<T *>(pointerName.constData()),
         qRegisterMetaType<QDeclarativeListProperty<T> >(listName.constData()),
         0, 0,
         QString(),
         0, 0, 0, 0, &T::staticMetaObject,
         QDeclarativePrivate::attachedPropertiesFunc<T>(),
         QDeclarativePrivate::attachedPropertiesMetaObject<T>(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativeParserStatus>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueSource>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueInterceptor>::cast(),
         QDeclarativePrivate::createParent<E>, &E::staticMetaObject,
         0,
         0
     };
     return QDeclarativePrivate::qmlregister(QDeclarativePrivate::TypeRegistration, &type);
 }
qmlRegisterExtendedType() [2/2]
template<typename T , typename E > int qmlRegisterExtendedType (const char * uri, int versionMajor, int versionMinor, const char * qmlName)
Definition at line 297 of file qdeclarative.h.
 {
     QByteArray name(T::staticMetaObject.className());
     QByteArray pointerName(name + '*');
     QByteArray listName("QDeclarativeListProperty<" + name + ">");
     QDeclarativeAttachedPropertiesFunc attached = QDeclarativePrivate::attachedPropertiesFunc<E>();
     const QMetaObject * attachedMetaObject = QDeclarativePrivate::attachedPropertiesMetaObject<E>();
     if (!attached) {
         attached = QDeclarativePrivate::attachedPropertiesFunc<T>();
         attachedMetaObject = QDeclarativePrivate::attachedPropertiesMetaObject<T>();
     }
     QDeclarativePrivate::RegisterType type = {
         0,
         qRegisterMetaType<T *>(pointerName.constData()),
         qRegisterMetaType<QDeclarativeListProperty<T> >(listName.constData()),
         sizeof(T), QDeclarativePrivate::createInto<T>,
         QString(),
         uri, versionMajor, versionMinor, qmlName, &T::staticMetaObject,
         attached,
         attachedMetaObject,
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativeParserStatus>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueSource>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueInterceptor>::cast(),
         QDeclarativePrivate::createParent<E>, &E::staticMetaObject,
         0,
         0
     };
     return QDeclarativePrivate::qmlregister(QDeclarativePrivate::TypeRegistration, &type);
 }
qmlRegisterInterface()
template<typename T > int qmlRegisterInterface (const char * typeName)
Definition at line 339 of file qdeclarative.h.
 {
     QByteArray name(typeName);
     QByteArray pointerName(name + '*');
     QByteArray listName("QDeclarativeListProperty<" + name + ">");
     QDeclarativePrivate::RegisterInterface qmlInterface = {
         0,
         qRegisterMetaType<T *>(pointerName.constData()),
         qRegisterMetaType<QDeclarativeListProperty<T> >(listName.constData()),
         qobject_interface_iid<T *>()
     };
     return QDeclarativePrivate::qmlregister(QDeclarativePrivate::InterfaceRegistration, &qmlInterface);
 }
qmlRegisterRevision()
template<typename T , int metaObjectRevision> int qmlRegisterRevision (const char * uri, int versionMajor, int versionMinor)
Definition at line 228 of file qdeclarative.h.
 {
     QByteArray name(T::staticMetaObject.className());
     QByteArray pointerName(name + '*');
     QByteArray listName("QDeclarativeListProperty<" + name + ">");
     QDeclarativePrivate::RegisterType type = {
         1,
         qRegisterMetaType<T *>(pointerName.constData()),
         qRegisterMetaType<QDeclarativeListProperty<T> >(listName.constData()),
         sizeof(T), QDeclarativePrivate::createInto<T>,
         QString(),
         uri, versionMajor, versionMinor, 0, &T::staticMetaObject,
         QDeclarativePrivate::attachedPropertiesFunc<T>(),
         QDeclarativePrivate::attachedPropertiesMetaObject<T>(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativeParserStatus>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueSource>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueInterceptor>::cast(),
         0, 0,
         0,
         metaObjectRevision
     };
     return QDeclarativePrivate::qmlregister(QDeclarativePrivate::TypeRegistration, &type);
 }
qmlRegisterType() [1/3]
template<typename T > int qmlRegisterType ()
Definition at line 90 of file qdeclarative.h.
 {
     QByteArray name(T::staticMetaObject.className());
     QByteArray pointerName(name + '*');
     QByteArray listName("QDeclarativeListProperty<" + name + ">");
     QDeclarativePrivate::RegisterType type = {
         0,
         qRegisterMetaType<T *>(pointerName.constData()),
         qRegisterMetaType<QDeclarativeListProperty<T> >(listName.constData()),
         0, 0,
         QString(),
         0, 0, 0, 0, &T::staticMetaObject,
         QDeclarativePrivate::attachedPropertiesFunc<T>(),
         QDeclarativePrivate::attachedPropertiesMetaObject<T>(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativeParserStatus>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueSource>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueInterceptor>::cast(),
         0, 0,
         0,
         0
     };
     return QDeclarativePrivate::qmlregister(QDeclarativePrivate::TypeRegistration, &type);
 }
qmlRegisterType() [2/3]
template<typename T > int qmlRegisterType (const char * uri, int versionMajor, int versionMinor, const char * qmlName)
Definition at line 160 of file qdeclarative.h.
 {
     QByteArray name(T::staticMetaObject.className());
     QByteArray pointerName(name + '*');
     QByteArray listName("QDeclarativeListProperty<" + name + ">");
     QDeclarativePrivate::RegisterType type = {
         0,
         qRegisterMetaType<T *>(pointerName.constData()),
         qRegisterMetaType<QDeclarativeListProperty<T> >(listName.constData()),
         sizeof(T), QDeclarativePrivate::createInto<T>,
         QString(),
         uri, versionMajor, versionMinor, qmlName, &T::staticMetaObject,
         QDeclarativePrivate::attachedPropertiesFunc<T>(),
         QDeclarativePrivate::attachedPropertiesMetaObject<T>(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativeParserStatus>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueSource>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueInterceptor>::cast(),
         0, 0,
         0,
         0
     };
     return QDeclarativePrivate::qmlregister(QDeclarativePrivate::TypeRegistration, &type);
 }
qmlRegisterType() [3/3]
template<typename T , int metaObjectRevision> int qmlRegisterType (const char * uri, int versionMajor, int versionMinor, const char * qmlName)
Definition at line 194 of file qdeclarative.h.
 {
     QByteArray name(T::staticMetaObject.className());
     QByteArray pointerName(name + '*');
     QByteArray listName("QDeclarativeListProperty<" + name + ">");
     QDeclarativePrivate::RegisterType type = {
         1,
         qRegisterMetaType<T *>(pointerName.constData()),
         qRegisterMetaType<QDeclarativeListProperty<T> >(listName.constData()),
         sizeof(T), QDeclarativePrivate::createInto<T>,
         QString(),
         uri, versionMajor, versionMinor, qmlName, &T::staticMetaObject,
         QDeclarativePrivate::attachedPropertiesFunc<T>(),
         QDeclarativePrivate::attachedPropertiesMetaObject<T>(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativeParserStatus>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueSource>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueInterceptor>::cast(),
         0, 0,
         0,
         metaObjectRevision
     };
     return QDeclarativePrivate::qmlregister(QDeclarativePrivate::TypeRegistration, &type);
 }
qmlRegisterTypeNotAvailable()
int Q_AUTOTEST_EXPORT qmlRegisterTypeNotAvailable (const char * uri, int versionMajor, int versionMinor, const char * qmlName, const QString & message)
Definition at line 46 of file qdeclarativetypenotavailable.cpp.
Referenced by QDeclarativeItemModule::defineModule(), QDeclarativeUtilModule::defineModule(), QDeclarativeItemModule::defineModuleCompat(), QDeclarativeUtilModule::defineModuleCompat(), and qmlRegisterType().
 {
     return qmlRegisterUncreatableType<QDeclarativeTypeNotAvailable>(uri,versionMajor,versionMinor,qmlName,message);
 }
qmlRegisterUncreatableType()
template<typename T > int qmlRegisterUncreatableType (const char * uri, int versionMajor, int versionMinor, const char * qmlName, const QString & reason)
Definition at line 126 of file qdeclarative.h.
 {
     QByteArray name(T::staticMetaObject.className());
     QByteArray pointerName(name + '*');
     QByteArray listName("QDeclarativeListProperty<" + name + ">");
     QDeclarativePrivate::RegisterType type = {
         0,
         qRegisterMetaType<T *>(pointerName.constData()),
         qRegisterMetaType<QDeclarativeListProperty<T> >(listName.constData()),
         0, 0,
         reason,
         uri, versionMajor, versionMinor, qmlName, &T::staticMetaObject,
         QDeclarativePrivate::attachedPropertiesFunc<T>(),
         QDeclarativePrivate::attachedPropertiesMetaObject<T>(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativeParserStatus>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueSource>::cast(),
         QDeclarativePrivate::StaticCastSelector<T,QDeclarativePropertyValueInterceptor>::cast(),
         0, 0,
         0,
         0
     };
     return QDeclarativePrivate::qmlregister(QDeclarativePrivate::TypeRegistration, &type);
 }