Qt 4.8: /src/declarative/graphicsitems/qdeclarativetextlayout.cpp File Reference
qdeclarativetextlayout.cpp File Reference
#include "qdeclarativetextlayout_p.h"
#include <private/qstatictext_p.h>
#include <private/qfontengine_p.h>
#include <private/qtextengine_p.h>
#include <private/qpainter_p.h>
#include <private/qpaintengineex_p.h>
Classes
class QDeclarativeTextLayoutPrivate
Functions
Q_GLOBAL_STATIC (InertTextPainter, inertTextPainter)
Q_GUI_EXPORT void qt_draw_decoration_for_glyphs (QPainter *painter, const glyph_t *glyphArray, const QFixedPoint *positions, int glyphCount, QFontEngine *fontEngine, const QFont &font, const QTextCharFormat &charFormat)
Function Documentation
Q_GLOBAL_STATIC()
Q_GLOBAL_STATIC (InertTextPainter , inertTextPainter)
qt_draw_decoration_for_glyphs()
Q_GUI_EXPORT void qt_draw_decoration_for_glyphs (QPainter * painter, const glyph_t * glyphArray, const QFixedPoint * positions, int glyphCount, QFontEngine * fontEngine, const QFont & font, const QTextCharFormat & charFormat)
Definition at line 6820 of file qpainter.cpp.
Referenced by QDeclarativeTextLayout::draw(), QPainter::drawStaticText(), and QDeclarativeTextLayout::prepare().
 {
     if (!(font.underline() || font.strikeOut() || font.overline()))
         return;
     QFixed leftMost;
     QFixed rightMost;
     QFixed baseLine;
     for (int i=0; i<glyphCount; ++i) {
         glyph_metrics_t gm = fontEngine->boundingBox(glyphArray[i]);
         if (i == 0 || leftMost > positions[i].x)
             leftMost = positions[i].x;
         // We don't support glyphs that do not share a common baseline. If this turns out to
         // be a relevant use case, then we need to find clusters of glyphs that share a baseline
         // and do a drawTextItemDecorations call per cluster.
         if (i == 0 || baseLine < positions[i].y)
             baseLine = positions[i].y;
         // We use the advance rather than the actual bounds to match the algorithm in drawText()
         if (i == 0 || rightMost < positions[i].x + gm.xoff)
             rightMost = positions[i].x + gm.xoff;
     }
     QFixed width = rightMost - leftMost;
     QTextItem::RenderFlags flags = 0;
     if (font.underline())
         flags |= QTextItem::Underline;
     if (font.overline())
         flags |= QTextItem::Overline;
     if (font.strikeOut())
         flags |= QTextItem::StrikeOut;
     drawTextItemDecoration(painter, QPointF(leftMost.toReal(), baseLine.toReal()),
                            fontEngine,
                            font.underline() ? QTextCharFormat::SingleUnderline
                                             : QTextCharFormat::NoUnderline, flags,
                            width.toReal(), charFormat);
 }