Qt 4.8: /src/declarative/util/qdeclarativeanimation.cpp File Reference
qdeclarativeanimation.cpp File Reference
#include "private/qdeclarativeanimation_p.h"
#include "private/qdeclarativeanimation_p_p.h"
#include "private/qdeclarativebehavior_p.h"
#include "private/qdeclarativestateoperations_p.h"
#include "private/qdeclarativecontext_p.h"
#include <qdeclarativepropertyvaluesource.h>
#include <qdeclarative.h>
#include <qdeclarativeinfo.h>
#include <qdeclarativeexpression.h>
#include <qdeclarativestringconverters_p.h>
#include <qdeclarativeglobal_p.h>
#include <qdeclarativemetatype_p.h>
#include <qdeclarativevaluetype_p.h>
#include <qdeclarativeproperty_p.h>
#include <qdeclarativeengine_p.h>
#include <qvariant.h>
#include <qcolor.h>
#include <qfile.h>
#include <QParallelAnimationGroup>
#include <QSequentialAnimationGroup>
#include <QtCore/qset.h>
#include <QtCore/qrect.h>
#include <QtCore/qpoint.h>
#include <QtCore/qsize.h>
#include <QtCore/qmath.h>
#include <private/qvariantanimation_p.h>
Functions
QVariant _q_interpolateClockwiseRotation (qreal &f, qreal &t, qreal progress)
QVariant _q_interpolateCounterclockwiseRotation (qreal &f, qreal &t, qreal progress)
QVariant _q_interpolateShortestRotation (qreal &f, qreal &t, qreal progress)
Function Documentation
_q_interpolateClockwiseRotation()
QVariant _q_interpolateClockwiseRotation (qreal & f, qreal & t, qreal progress)
Definition at line 1458 of file qdeclarativeanimation.cpp.
Referenced by QDeclarativeRotationAnimation::setDirection().
 {
     qreal newt = t;
     qreal diff = t-f;
     while(diff < 0.0){
         newt += 360.0;
         diff += 360.0;
     }
     return QVariant(f + (newt - f) * progress);
 }
_q_interpolateCounterclockwiseRotation()
QVariant _q_interpolateCounterclockwiseRotation (qreal & f, qreal & t, qreal progress)
Definition at line 1469 of file qdeclarativeanimation.cpp.
Referenced by QDeclarativeRotationAnimation::setDirection().
 {
     qreal newt = t;
     qreal diff = t-f;
     while(diff > 0.0){
         newt -= 360.0;
         diff -= 360.0;
     }
     return QVariant(f + (newt - f) * progress);
 }
_q_interpolateShortestRotation()
QVariant _q_interpolateShortestRotation (qreal & f, qreal & t, qreal progress)
Definition at line 1443 of file qdeclarativeanimation.cpp.
Referenced by QDeclarativeRotationAnimation::setDirection().
 {
     qreal newt = t;
     qreal diff = t-f;
     while(diff > 180.0){
         newt -= 360.0;
         diff -= 360.0;
     }
     while(diff < -180.0){
         newt += 360.0;
         diff += 360.0;
     }
     return QVariant(f + (newt - f) * progress);
 }