Qt 4.8: /src/declarative/graphicsitems/qdeclarativeitem.cpp File Reference
qdeclarativeitem.cpp File Reference
#include "qdeclarativeitem.h"
#include "private/qdeclarativeevents_p_p.h"
#include <private/qdeclarativeengine_p.h>
#include <private/qgraphicsitem_p.h>
#include <QtDeclarative/private/qdeclarativeitem_p.h>
#include <qdeclarativeengine.h>
#include <qdeclarativeopenmetaobject_p.h>
#include <qdeclarativestate_p.h>
#include <qdeclarativeview.h>
#include <qdeclarativestategroup_p.h>
#include <qdeclarativecomponent.h>
#include <qdeclarativeinfo.h>
#include <QDebug>
#include <QPen>
#include <QEvent>
#include <QGraphicsSceneMouseEvent>
#include <QtCore/qnumeric.h>
#include <QtScript/qscriptengine.h>
#include <QtGui/qgraphicstransform.h>
#include <qlistmodelinterface_p.h>
#include <float.h>
#include <moc_qdeclarativeitem.cpp>
Classes
class QDeclarativeItemAccessor
class QElapsedTimerConsistentTimeHack
struct RegisterAnchorLineAtStartup
Functions
static QObject * children_at_helper (QDeclarativeListProperty< QObject > *prop, int index)
static void children_clear_helper (QDeclarativeListProperty< QObject > *prop)
static int children_count_helper (QDeclarativeListProperty< QObject > *prop)
QDebug operator<< (QDebug debug, QDeclarativeItem *item)
Variables
static RegisterAnchorLineAtStartup registerAnchorLineAtStartup
Function Documentation
children_at_helper()
static QObject* children_at_helper (QDeclarativeListProperty< QObject > * prop, int index) inline static
Definition at line 2020 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeItemPrivate::data_at().
 {
     QGraphicsItemPrivate *d = QGraphicsItemPrivate::get(static_cast<QGraphicsObject *>(prop->object));
     if (index >= 0 && index < d->children.count())
         return d->children.at(index)->toGraphicsObject();
     else
         return 0;
 }
children_clear_helper()
static void children_clear_helper (QDeclarativeListProperty< QObject > * prop) inline static
Definition at line 2029 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeItemPrivate::data_clear().
 {
     QDeclarativeItemPrivate *d = static_cast<QDeclarativeItemPrivate*>(QGraphicsItemPrivate::get(static_cast<QGraphicsObject *>(prop->object)));
     int childCount = d->children.count();
     if (d->componentComplete) {
         for (int index = 0 ;index < childCount; index++)
             d->children.at(0)->setParentItem(0);
     } else {
         for (int index = 0 ;index < childCount; index++)
             QGraphicsItemPrivate::get(d->children.at(0))->setParentItemHelper(0, /*newParentVariant=*/0, /*thisPointerVariant=*/0);
     }
 }
children_count_helper()
static int children_count_helper (QDeclarativeListProperty< QObject > * prop) inline static
Definition at line 2014 of file qdeclarativeitem.cpp.
Referenced by QDeclarativeItemPrivate::data_at(), and QDeclarativeItemPrivate::data_count().
 {
     QGraphicsItemPrivate *d = QGraphicsItemPrivate::get(static_cast<QGraphicsObject *>(prop->object));
     return d->children.count();
 }
operator<<()
QDebug operator<< (QDebug debug, QDeclarativeItem * item)
Definition at line 4004 of file qdeclarativeitem.cpp.
Referenced by qobject_cast().
 {
     if (!item) {
         debug << "QDeclarativeItem(0)";
         return debug;
     }
     debug << item->metaObject()->className() << "(this =" << ((void*)item)
           << ", parent =" << ((void*)item->parentItem())
           << ", geometry =" << QRectF(item->pos(), QSizeF(item->width(), item->height()))
           << ", z =" << item->zValue() << ')';
     return debug;
 }
Variable Documentation
registerAnchorLineAtStartup
RegisterAnchorLineAtStartup registerAnchorLineAtStartup static
Definition at line 1822 of file qdeclarativeitem.cpp.