Qt 4.8: /src/declarative/util/qdeclarativestateoperations.cpp File Reference
qdeclarativestateoperations.cpp File Reference
#include "private/qdeclarativestateoperations_p.h"
#include <qdeclarative.h>
#include <qdeclarativecontext.h>
#include <qdeclarativeexpression.h>
#include <qdeclarativeinfo.h>
#include <qdeclarativeanchors_p_p.h>
#include <qdeclarativeitem_p.h>
#include <qdeclarativeguard_p.h>
#include <qdeclarativenullablevalue_p_p.h>
#include "private/qdeclarativecontext_p.h"
#include "private/qdeclarativeproperty_p.h"
#include "private/qdeclarativebinding_p.h"
#include "private/qdeclarativestate_p_p.h"
#include <QtCore/qdebug.h>
#include <QtGui/qgraphicsitem.h>
#include <QtCore/qmath.h>
#include <private/qobject_p.h>
#include <qdeclarativestateoperations.moc>
#include <moc_qdeclarativestateoperations_p.cpp>
Classes
class AccessibleFxItem
class QDeclarativeAnchorChangesPrivate
class QDeclarativeAnchorSetPrivate
class QDeclarativeParentChangePrivate
class QDeclarativeStateChangeScriptPrivate
Functions
void tryReal (QDeclarativeNullableValue< qreal > &value, const QString &string)
Function Documentation
tryReal()
void tryReal (QDeclarativeNullableValue< qreal > & value, const QString & string)
Definition at line 236 of file qdeclarativestateoperations.cpp.
Referenced by QDeclarativeParentChange::setHeight(), QDeclarativeParentChange::setRotation(), QDeclarativeParentChange::setScale(), QDeclarativeParentChange::setWidth(), QDeclarativeParentChange::setX(), and QDeclarativeParentChange::setY().
 {
     bool ok = false;
     qreal realValue = string.toFloat(&ok);
     if (ok)
         value = realValue;
     else
         value.invalidate();
 }