Qt 4.8: /src/declarative/qml/qdeclarativeengine.cpp File Reference
qdeclarativeengine.cpp File Reference
#include "private/qdeclarativeengine_p.h"
#include "qdeclarativeengine.h"
#include "private/qdeclarativeboundsignal_p.h"
#include "private/qdeclarativecontext_p.h"
#include "private/qdeclarativecompiler_p.h"
#include "private/qdeclarativeglobalscriptclass_p.h"
#include "qdeclarative.h"
#include "qdeclarativecontext.h"
#include "qdeclarativeexpression.h"
#include "qdeclarativecomponent.h"
#include "private/qdeclarativebinding_p_p.h"
#include "private/qdeclarativevme_p.h"
#include "private/qdeclarativeenginedebugservice_p.h"
#include "private/qdeclarativestringconverters_p.h"
#include "private/qdeclarativexmlhttprequest_p.h"
#include "private/qdeclarativesqldatabase_p.h"
#include "private/qdeclarativetypenamescriptclass_p.h"
#include "private/qdeclarativelistscriptclass_p.h"
#include "qdeclarativescriptstring.h"
#include "private/qdeclarativeglobal_p.h"
#include "private/qdeclarativeworkerscript_p.h"
#include "private/qdeclarativecomponent_p.h"
#include "qdeclarativenetworkaccessmanagerfactory.h"
#include "qdeclarativeimageprovider.h"
#include "private/qdeclarativedirparser_p.h"
#include "qdeclarativeextensioninterface.h"
#include "private/qdeclarativelist_p.h"
#include "private/qdeclarativetypenamecache_p.h"
#include "private/qdeclarativeinclude_p.h"
#include "private/qdeclarativenotifier_p.h"
#include "private/qdeclarativedebugtrace_p.h"
#include "private/qdeclarativeapplication_p.h"
#include "private/qjsdebugservice_p.h"
#include <QtCore/qmetaobject.h>
#include <QScriptClass>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QNetworkAccessManager>
#include <QDesktopServices>
#include <QTimer>
#include <QList>
#include <QPair>
#include <QDebug>
#include <QMetaObject>
#include <QStack>
#include <QMap>
#include <QPluginLoader>
#include <QtGui/qapplication.h>
#include <QtGui/qfontdatabase.h>
#include <QtCore/qlibraryinfo.h>
#include <QtCore/qthreadstorage.h>
#include <QtCore/qthread.h>
#include <QtCore/qcoreapplication.h>
#include <QtCore/qdir.h>
#include <QtCore/qmutex.h>
#include <QtGui/qcolor.h>
#include <QtGui/qvector3d.h>
#include <QtGui/qsound.h>
#include <QtCore/qcryptographichash.h>
#include <private/qobject_p.h>
#include <private/qscriptdeclarativeclass_p.h>
#include <private/qdeclarativeitemsmodule_p.h>
#include <private/qdeclarativeutilmodule_p.h>
#include <qt_windows.h>
#include <qlibrary.h>
#include <windows.h>
Classes
class QDeclarativeDataExtended
struct StaticQtMetaObject
Macros
#define CSIDL_APPDATA 0x001a
Functions
static void dumpwarning (const QDeclarativeError &error)
static void dumpwarning (const QList< QDeclarativeError > &errors)
bool QDeclarative_isFileCaseCorrect (const QString &fileName)
Returns true if the case of fileName is equivalent to the file case of fileName on disk, and false otherwise.
QObject * qmlAttachedPropertiesObject (int *idCache, const QObject *object, const QMetaObject *attachedMetaObject, bool create)
QObject * qmlAttachedPropertiesObjectById (int id, const QObject *object, bool create)
QDeclarativeContext * qmlContext (const QObject *obj)
QDeclarativeEngine * qmlEngine (const QObject *obj)
Q_AUTOTEST_EXPORT void qmlExecuteDeferred (QObject *object)
static void * voidptr_constructor (const void *v)
static void voidptr_destructor (void *v)
Variables
static bool qt_QmlQtModule_registered = false
Macro Definition Documentation
CSIDL_APPDATA
#define CSIDL_APPDATA 0x001a
Definition at line 115 of file qdeclarativeengine.cpp.
Function Documentation
dumpwarning() [1/2]
static void dumpwarning (const QDeclarativeError & error) static
Definition at line 1980 of file qdeclarativeengine.cpp.
Referenced by dumpwarning(), and QDeclarativeEnginePrivate::warning().
 {
     qWarning().nospace() << qPrintable(error.toString());
 }
dumpwarning() [2/2]
static void dumpwarning (const QList< QDeclarativeError > & errors) static
Definition at line 1985 of file qdeclarativeengine.cpp.
 {
     for (int ii = 0; ii < errors.count(); ++ii)
         dumpwarning(errors.at(ii));
 }
QDeclarative_isFileCaseCorrect()
bool QDeclarative_isFileCaseCorrect (const QString & fileName)
Returns true if the case of fileName is equivalent to the file case of fileName on disk, and false otherwise.
This is used to ensure that the behavior of QML on a case-insensitive file system is the same as on a case-sensitive file system. This function performs a "best effort" attempt to determine the real case of the file. It may have false positives (say the case is correct when it isn't), but it should never have a false negative (say the case is incorrect when it is correct).
Definition at line 2550 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeImportDatabase::importPlugin(), QDeclarativeDataLoader::load(), QDeclarativeDirParser::parse(), and QDeclarativeGraphics_DerivedObject::setParent_noEvent().
 {
 #if defined(Q_OS_MAC) || defined(Q_OS_WIN32)
     QFileInfo info(fileName);
     QString absolute = info.absoluteFilePath();
 #if defined(Q_OS_MAC)
     QString canonical = info.canonicalFilePath();
 #elif defined(Q_OS_WIN32)
     wchar_t buffer[1024];
     DWORD rv = ::GetShortPathName((wchar_t*)absolute.utf16(), buffer, 1024);
     if (rv == 0 || rv >= 1024) return true;
     rv = ::GetLongPathName(buffer, buffer, 1024);
     if (rv == 0 || rv >= 1024) return true;
     QString canonical((QChar *)buffer);
 #endif
     int absoluteLength = absolute.length();
     int canonicalLength = canonical.length();
     int length = qMin(absoluteLength, canonicalLength);
     for (int ii = 0; ii < length; ++ii) {
         const QChar &a = absolute.at(absoluteLength - 1 - ii);
         const QChar &c = canonical.at(canonicalLength - 1 - ii);
         if (a.toLower() != c.toLower())
             return true;
         if (a != c)
             return false;
     }
 #else
     Q_UNUSED(fileName)
 #endif
     return true;
 }
qmlAttachedPropertiesObject()
QObject* qmlAttachedPropertiesObject (int * idCache, const QObject * object, const QMetaObject * attachedMetaObject, bool create)
Definition at line 1106 of file qdeclarativeengine.cpp.
Referenced by qmlAttachedPropertiesObject(), and qmlRegisterCustomType().
 {
     if (*idCache == -1)
         *idCache = QDeclarativeMetaType::attachedPropertiesFuncId(attachedMetaObject);
     if (*idCache == -1 || !object)
         return 0;
     return qmlAttachedPropertiesObjectById(*idCache, object, create);
 }
qmlAttachedPropertiesObjectById()
QObject* qmlAttachedPropertiesObjectById (int id, const QObject * object, bool create)
Definition at line 1084 of file qdeclarativeengine.cpp.
Referenced by QDeclarativePropertyPrivate::initProperty(), qmlAttachedPropertiesObject(), qmlRegisterCustomType(), QDeclarativeTypeNameScriptClass::queryProperty(), and QDeclarativeCompiledBindingsPrivate::run().
 {
     QDeclarativeData *data = QDeclarativeData::get(object);
     if (!data)
         return 0; // Attached properties are only on objects created by QML
     QObject *rv = data->hasExtendedData()?data->attachedProperties()->value(id):0;
     if (rv || !create)
         return rv;
     QDeclarativeAttachedPropertiesFunc pf = QDeclarativeMetaType::attachedPropertiesFuncById(id);
     if (!pf)
         return 0;
     rv = pf(const_cast<QObject *>(object));
     if (rv)
         data->attachedProperties()->insert(id, rv);
     return rv;
 }
qmlContext()
QDeclarativeContext* qmlContext (const QObject * obj)
Definition at line 1073 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeLoaderPrivate::_q_sourceLoaded(), QDeclarativePropertyChanges::actions(), QDeclarativeParentChange::actions(), QDeclarativeAnchorChanges::actions(), QDeclarativeAnchorChanges::additionalActions(), QDeclarativeWatcher::addWatch(), QDeclarativePropertyChanges::changeExpression(), QDeclarativeGestureArea::connectSignals(), QDeclarativeConnections::connectSignals(), QDeclarativeGridViewPrivate::createComponentItem(), QDeclarativeListViewPrivate::createComponentItem(), QDeclarativePathViewPrivate::createHighlight(), QDeclarativeAbstractAnimationPrivate::createProperty(), QDeclarativeListViewPrivate::createSection(), QDeclarativeComponent::creationContext(), QDeclarativePropertyChangesPrivate::decode(), QDeclarativeXmlListModel::get(), QDeclarativeVisualDataModel::item(), QDeclarativeTextEdit::loadCursorDelegate(), QTextDocumentWithImageResources::loadResource(), QDeclarativeEngineDebugService::messageReceived(), QDeclarativeEngineDebugService::objectData(), QDeclarativePropertyChangesPrivate::property(), qmlRegisterCustomType(), QDeclarativeXmlListModel::reload(), QDeclarativeEngineDebugService::resetBinding(), QDeclarativeEngineDebugService::setBinding(), QDeclarativeRepeater::setDelegate(), QDeclarativeGridView::setDelegate(), QDeclarativePathView::setDelegate(), QDeclarativeListView::setDelegate(), QDeclarativeEngineDebugService::setMethodBody(), QDeclarativeRepeater::setModel(), QDeclarativePathView::setModel(), QDeclarativeGridView::setModel(), QDeclarativeListView::setModel(), and QDeclarativeFontLoader::setSource().
 {
     return QDeclarativeEngine::contextForObject(obj);
 }
qmlEngine()
QDeclarativeEngine* qmlEngine (const QObject * obj)
Definition at line 1078 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeLoaderPrivate::_q_sourceLoaded(), QDeclarativeXmlListModel::classBegin(), QDeclarativePathView::createdItem(), QDeclarativeWorkerScript::engine(), QDeclarativeWorkerScript::event(), FlatListModel::get(), NestedListModel::get(), QDeclarativePathViewPrivate::getItem(), QDeclarativeBorderImage::load(), QDeclarativeImageBase::load(), QDeclarativeAnimatedImage::load(), QDeclarativeItem::mapFromItem(), QDeclarativeItem::mapToItem(), ModelNode::object(), QDeclarativeComponent::qmlAttachedProperties(), qmlRegisterCustomType(), QDeclarativeXmlListModel::reload(), QDeclarativeXmlListModel::requestFinished(), QDeclarativeBorderImage::setGridScaledImage(), QDeclarativeVisualDataModel::setModel(), QDeclarativeAbstractAnimation::setRunning(), QDeclarativeLoader::setSource(), QDeclarativeFontLoader::setSource(), QDeclarativeParticles::setSource(), QDeclarativeBehavior::setTarget(), and QDeclarativeInfo::~QDeclarativeInfo().
 {
     QDeclarativeContext *context = QDeclarativeEngine::contextForObject(obj);
     return context?context->engine():0;
 }
qmlExecuteDeferred()
Q_AUTOTEST_EXPORT void qmlExecuteDeferred (QObject * object)
Definition at line 1047 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeState::apply(), QDeclarativeStatePrivate::generateActionList(), QDeclarativeTransition::prepare(), QDeclarativeEngineDebugService::prepareDeferredObjects(), qmlRegisterCustomType(), and QDeclarativeBehavior::write().
 {
     QDeclarativeData *data = QDeclarativeData::get(object);
     if (data && data->deferredComponent) {
         if (QDeclarativeDebugService::isDebuggingEnabled()) {
             QDeclarativeDebugTrace::startRange(QDeclarativeDebugTrace::Creating);
             QDeclarativeType *type = QDeclarativeMetaType::qmlType(object->metaObject());
             QString typeName = type ? QLatin1String(type->qmlTypeName()) : QString::fromLatin1(object->metaObject()->className());
             QDeclarativeDebugTrace::rangeData(QDeclarativeDebugTrace::Creating, typeName);
             if (data->outerContext)
                 QDeclarativeDebugTrace::rangeLocation(QDeclarativeDebugTrace::Creating, data->outerContext->url, data->lineNumber);
         }
         QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(data->context->engine);
         QDeclarativeComponentPrivate::ConstructionState state;
         QDeclarativeComponentPrivate::beginDeferred(ep, object, &state);
         data->deferredComponent->release();
         data->deferredComponent = 0;
         QDeclarativeComponentPrivate::complete(ep, &state);
         QDeclarativeDebugTrace::endRange(QDeclarativeDebugTrace::Creating);
     }
 }
voidptr_constructor()
static void* voidptr_constructor (const void * v) static
Definition at line 2343 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeEnginePrivate::registerCompositeType().
 {
     if (!v) {
         return new void*;
     } else {
         return new void*(*(void **)v);
     }
 }
voidptr_destructor()
static void voidptr_destructor (void * v) static
Definition at line 2337 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeEnginePrivate::registerCompositeType().
 {
     void **ptr = (void **)v;
     delete ptr;
 }
Variable Documentation
qt_QmlQtModule_registered
bool qt_QmlQtModule_registered = false static
Definition at line 186 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeEnginePrivate::QDeclarativeEnginePrivate().