Qt 4.8: /src/declarative/qml/qdeclarativetypenotavailable.cpp File Reference
qdeclarativetypenotavailable.cpp File Reference
#include "qdeclarativetypenotavailable_p.h"
Functions
int qmlRegisterTypeNotAvailable (const char *uri, int versionMajor, int versionMinor, const char *qmlName, const QString &message)
Function Documentation
qmlRegisterTypeNotAvailable()
int qmlRegisterTypeNotAvailable (const char * uri, int versionMajor, int versionMinor, const char * qmlName, const QString & message)
Definition at line 46 of file qdeclarativetypenotavailable.cpp.
Referenced by QDeclarativeItemModule::defineModule(), QDeclarativeUtilModule::defineModule(), QDeclarativeItemModule::defineModuleCompat(), QDeclarativeUtilModule::defineModuleCompat(), and qmlRegisterType().
 {
     return qmlRegisterUncreatableType<QDeclarativeTypeNotAvailable>(uri,versionMajor,versionMinor,qmlName,message);
 }