Qt 4.8: /src/declarative/util/qdeclarativepixmapcache.cpp File Reference
qdeclarativepixmapcache.cpp File Reference
#include "private/qdeclarativepixmapcache_p.h"
#include "qdeclarativenetworkaccessmanagerfactory.h"
#include "qdeclarativeimageprovider.h"
#include <qdeclarativeengine.h>
#include <private/qdeclarativeglobal_p.h>
#include <private/qdeclarativeengine_p.h>
#include <QCoreApplication>
#include <QImageReader>
#include <QHash>
#include <QNetworkReply>
#include <QPixmapCache>
#include <QFile>
#include <QThread>
#include <QMutex>
#include <QMutexLocker>
#include <QWaitCondition>
#include <QBuffer>
#include <QtCore/qdebug.h>
#include <private/qobject_p.h>
#include <QSslError>
#include <qdeclarativepixmapcache.moc>
Classes
class QDeclarativePixmapData
class QDeclarativePixmapKey
struct QDeclarativePixmapNull
class QDeclarativePixmapReader
class QDeclarativePixmapReaderThreadObject
class QDeclarativePixmapReply
class QDeclarativePixmapReply::Event
class QDeclarativePixmapStore
Macros
#define CACHE_EXPIRE_TIME 30
#define CACHE_REMOVAL_FRACTION 4
#define IMAGEREQUEST_MAX_REDIRECT_RECURSION 16
#define IMAGEREQUEST_MAX_REQUEST_COUNT 8
Functions
static QDeclarativePixmapData * createPixmapDataSync (QDeclarativeEngine *engine, const QUrl &url, const QSize &requestSize, bool *ok)
bool operator== (const QDeclarativePixmapKey &lhs, const QDeclarativePixmapKey &rhs)
Q_GLOBAL_STATIC (QDeclarativePixmapStore, pixmapStore)
Q_GLOBAL_STATIC (QDeclarativePixmapNull, nullPixmap)
uint qHash (const QDeclarativePixmapKey &key)
static bool readImage (const QUrl &url, QIODevice *dev, QImage *image, QString *errorString, QSize *impsize, const QSize &requestSize)
Variables
static int cache_limit = 2048 * 1024
Macro Definition Documentation
CACHE_EXPIRE_TIME
#define CACHE_EXPIRE_TIME 30
Definition at line 68 of file qdeclarativepixmapcache.cpp.
Referenced by QDeclarativePixmapStore::unreferencePixmap().
CACHE_REMOVAL_FRACTION
#define CACHE_REMOVAL_FRACTION 4
Definition at line 69 of file qdeclarativepixmapcache.cpp.
Referenced by QDeclarativePixmapStore::timerEvent().
IMAGEREQUEST_MAX_REDIRECT_RECURSION
#define IMAGEREQUEST_MAX_REDIRECT_RECURSION 16
Definition at line 67 of file qdeclarativepixmapcache.cpp.
Referenced by QDeclarativePixmapReader::networkRequestDone().
IMAGEREQUEST_MAX_REQUEST_COUNT
#define IMAGEREQUEST_MAX_REQUEST_COUNT 8
Definition at line 66 of file qdeclarativepixmapcache.cpp.
Referenced by QDeclarativePixmapReader::processJobs().
Function Documentation
createPixmapDataSync()
static QDeclarativePixmapData* createPixmapDataSync (QDeclarativeEngine * engine, const QUrl & url, const QSize & requestSize, bool * ok) static
Definition at line 810 of file qdeclarativepixmapcache.cpp.
Referenced by QDeclarativePixmap::load().
 {
     if (url.scheme() == QLatin1String("image")) {
         QSize readSize;
         QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
         QDeclarativeImageProvider::ImageType imageType = ep->getImageProviderType(url);
         switch (imageType) {
             case QDeclarativeImageProvider::Image:
             {
                 QImage image = ep->getImageFromProvider(url, &readSize, requestSize);
                 if (!image.isNull()) {
                     *ok = true;
                     return new QDeclarativePixmapData(url, QPixmap::fromImage(image), readSize, requestSize);
                 }
             }
             case QDeclarativeImageProvider::Pixmap:
             {
                 QPixmap pixmap = ep->getPixmapFromProvider(url, &readSize, requestSize);
                 if (!pixmap.isNull()) {
                     *ok = true;
                     return new QDeclarativePixmapData(url, pixmap, readSize, requestSize);
                 }
             }
         }
         // no matching provider, or provider has bad image type, or provider returned null image
         return new QDeclarativePixmapData(url, requestSize,
             QDeclarativePixmap::tr("Failed to get image from provider: %1").arg(url.toString()));
     }
     QString localFile = QDeclarativeEnginePrivate::urlToLocalFileOrQrc(url);
     if (localFile.isEmpty())
         return 0;
     QFile f(localFile);
     QSize readSize;
     QString errorString;
     if (f.open(QIODevice::ReadOnly)) {
         QImage image;
         if (readImage(url, &f, &image, &errorString, &readSize, requestSize)) {
             *ok = true;
             return new QDeclarativePixmapData(url, QPixmap::fromImage(image), readSize, requestSize);
         }
     } else {
         errorString = QDeclarativePixmap::tr("Cannot open: %1").arg(url.toString());
     }
     return new QDeclarativePixmapData(url, requestSize, errorString);
 }
operator==()
bool operator== (const QDeclarativePixmapKey & lhs, const QDeclarativePixmapKey & rhs) inline
Definition at line 589 of file qdeclarativepixmapcache.cpp.
 {
     return *lhs.size == *rhs.size && *lhs.url == *rhs.url;
 }
Q_GLOBAL_STATIC() [1/2]
Q_GLOBAL_STATIC (QDeclarativePixmapStore , pixmapStore)
Q_GLOBAL_STATIC() [2/2]
Q_GLOBAL_STATIC (QDeclarativePixmapNull , nullPixmap)
qHash()
uint qHash (const QDeclarativePixmapKey & key) inline
Definition at line 594 of file qdeclarativepixmapcache.cpp.
 {
     return qHash(*key.url) ^ key.size->width() ^ key.size->height();
 }
readImage()
static bool readImage (const QUrl & url, QIODevice * dev, QImage * image, QString * errorString, QSize * impsize, const QSize & requestSize) static
Definition at line 275 of file qdeclarativepixmapcache.cpp.
Referenced by createPixmapDataSync(), QDeclarativePixmapReader::networkRequestDone(), and QDeclarativePixmapReader::processJob().
 {
     QImageReader imgio(dev);
     bool force_scale = false;
     if (url.path().endsWith(QLatin1String(".svg"),Qt::CaseInsensitive)) {
         imgio.setFormat("svg"); // QSvgPlugin::capabilities bug QTBUG-9053
         force_scale = true;
     }
     bool scaled = false;
     if (requestSize.width() > 0 || requestSize.height() > 0) {
         QSize s = imgio.size();
         if (requestSize.width() && (force_scale || requestSize.width() < s.width())) {
             if (requestSize.height() <= 0)
                 s.setHeight(s.height()*requestSize.width()/s.width());
             s.setWidth(requestSize.width()); scaled = true;
         }
         if (requestSize.height() && (force_scale || requestSize.height() < s.height())) {
             if (requestSize.width() <= 0)
                 s.setWidth(s.width()*requestSize.height()/s.height());
             s.setHeight(requestSize.height()); scaled = true;
         }
         if (scaled) { imgio.setScaledSize(s); }
     }
     if (impsize)
         *impsize = imgio.size();
     if (imgio.read(image)) {
         if (impsize && impsize->width() < 0)
             *impsize = image->size();
         return true;
     } else {
         if (errorString)
             *errorString = QDeclarativePixmap::tr("Error decoding: %1: %2").arg(url.toString())
                                 .arg(imgio.errorString());
         return false;
     }
 }
Variable Documentation
cache_limit
int cache_limit = 2048 * 1024 static
Definition at line 76 of file qdeclarativepixmapcache.cpp.
Referenced by QDeclarativePixmapStore::shrinkCache().