Qt 4.8: /src/declarative/qml/qdeclarativestringconverters.cpp File Reference
qdeclarativestringconverters.cpp File Reference
#include "private/qdeclarativestringconverters_p.h"
#include <QtGui/qcolor.h>
#include <QtGui/qvector3d.h>
#include <QtCore/qpoint.h>
#include <QtCore/qrect.h>
#include <QtCore/qsize.h>
#include <QtCore/qvariant.h>
#include <QtCore/qdatetime.h>
Functions
static uchar fromHex (const uchar c, const uchar c2)
static uchar fromHex (const QString &s, int idx)
Function Documentation
fromHex() [1/2]
static uchar fromHex (const uchar c, const uchar c2) static
Definition at line 54 of file qdeclarativestringconverters.cpp.
Referenced by QDeclarativeStringConverters::colorFromString(), fromHex(), and QByteArray::isSharedWith().
 {
     uchar rv = 0;
     if (c >= '0' && c <= '9')
         rv += (c - '0') * 16;
     else if (c >= 'A' && c <= 'F')
         rv += (c - 'A' + 10) * 16;
     else if (c >= 'a' && c <= 'f')
         rv += (c - 'a' + 10) * 16;
     if (c2 >= '0' && c2 <= '9')
         rv += (c2 - '0');
     else if (c2 >= 'A' && c2 <= 'F')
         rv += (c2 - 'A' + 10);
     else if (c2 >= 'a' && c2 <= 'f')
         rv += (c2 - 'a' + 10);
     return rv;
 }
fromHex() [2/2]
static uchar fromHex (const QString & s, int idx) static
Definition at line 74 of file qdeclarativestringconverters.cpp.
 {
     uchar c = s.at(idx).toAscii();
     uchar c2 = s.at(idx + 1).toAscii();
     return fromHex(c, c2);
 }