Qt 4.8: /src/declarative/debugger/qdeclarativeenginedebugservice.cpp File Reference
qdeclarativeenginedebugservice.cpp File Reference
#include "private/qdeclarativeenginedebugservice_p.h"
#include "private/qdeclarativeboundsignal_p.h"
#include "qdeclarativeengine.h"
#include "private/qdeclarativemetatype_p.h"
#include "qdeclarativeproperty.h"
#include "private/qdeclarativeproperty_p.h"
#include "private/qdeclarativebinding_p.h"
#include "private/qdeclarativecontext_p.h"
#include "private/qdeclarativewatcher_p.h"
#include "private/qdeclarativevaluetype_p.h"
#include "private/qdeclarativevmemetaobject_p.h"
#include "private/qdeclarativeexpression_p.h"
#include "private/qdeclarativepropertychanges_p.h"
#include <QtCore/qdebug.h>
#include <QtCore/qmetaobject.h>
Functions
static bool hasValidSignal (QObject *object, const QString &propertyName)
static bool isSignalPropertyName (const QString &signalName)
QDataStream & operator<< (QDataStream &ds, const QDeclarativeEngineDebugService::QDeclarativeObjectData &data)
QDataStream & operator<< (QDataStream &ds, const QDeclarativeEngineDebugService::QDeclarativeObjectProperty &data)
QDataStream & operator>> (QDataStream &ds, QDeclarativeEngineDebugService::QDeclarativeObjectData &data)
QDataStream & operator>> (QDataStream &ds, QDeclarativeEngineDebugService::QDeclarativeObjectProperty &data)
Q_GLOBAL_STATIC (QDeclarativeEngineDebugService, qmlEngineDebugService)
Function Documentation
hasValidSignal()
static bool hasValidSignal (QObject * object, const QString & propertyName) static
Definition at line 120 of file qdeclarativeenginedebugservice.cpp.
Referenced by QDeclarativeEngineDebugService::resetBinding(), and QDeclarativeEngineDebugService::setBinding().
 {
     if (!isSignalPropertyName(propertyName))
         return false;
     QString signalName = propertyName.mid(2);
     signalName[0] = signalName.at(0).toLower();
     int sigIdx = QDeclarativePropertyPrivate::findSignalByName(object->metaObject(), signalName.toLatin1()).methodIndex();
     if (sigIdx == -1)
         return false;
     return true;
 }
isSignalPropertyName()
static bool isSignalPropertyName (const QString & signalName) inline static
Definition at line 113 of file qdeclarativeenginedebugservice.cpp.
Referenced by hasValidSignal().
 {
     // see QmlCompiler::isSignalPropertyName
     return signalName.length() >= 3 && signalName.startsWith(QLatin1String("on")) &&
            signalName.at(2).isLetter() && signalName.at(2).isUpper();
 }
operator<<() [1/2]
QDataStream& operator<< (QDataStream & ds, const QDeclarativeEngineDebugService::QDeclarativeObjectData & data)
Definition at line 77 of file qdeclarativeenginedebugservice.cpp.
 {
     ds << data.url << data.lineNumber << data.columnNumber << data.idString
        << data.objectName << data.objectType << data.objectId << data.contextId
        << data.parentId;
     return ds;
 }
operator<<() [2/2]
QDataStream& operator<< (QDataStream & ds, const QDeclarativeEngineDebugService::QDeclarativeObjectProperty & data)
Definition at line 95 of file qdeclarativeenginedebugservice.cpp.
 {
     ds << (int)data.type << data.name << data.value << data.valueTypeName
        << data.binding << data.hasNotifySignal;
     return ds;
 }
operator>>() [1/2]
QDataStream& operator>> (QDataStream & ds, QDeclarativeEngineDebugService::QDeclarativeObjectData & data)
Definition at line 86 of file qdeclarativeenginedebugservice.cpp.
 {
     ds >> data.url >> data.lineNumber >> data.columnNumber >> data.idString
        >> data.objectName >> data.objectType >> data.objectId >> data.contextId
        >> data.parentId;
     return ds;
 }
operator>>() [2/2]
QDataStream& operator>> (QDataStream & ds, QDeclarativeEngineDebugService::QDeclarativeObjectProperty & data)
Definition at line 103 of file qdeclarativeenginedebugservice.cpp.
 {
     int type;
     ds >> type >> data.name >> data.value >> data.valueTypeName
        >> data.binding >> data.hasNotifySignal;
     data.type = (QDeclarativeEngineDebugService::QDeclarativeObjectProperty::Type)type;
     return ds;
 }
Q_GLOBAL_STATIC()
Q_GLOBAL_STATIC (QDeclarativeEngineDebugService , qmlEngineDebugService)