Qt 4.8: /src/declarative/qml/qdeclarativeinfo.cpp File Reference
qdeclarativeinfo.cpp File Reference
#include "qdeclarativeinfo.h"
#include "private/qdeclarativedata_p.h"
#include "qdeclarativecontext.h"
#include "private/qdeclarativecontext_p.h"
#include "private/qdeclarativemetatype_p.h"
#include "private/qdeclarativeengine_p.h"
#include <QCoreApplication>
Classes
class QDeclarativeInfoPrivate
Functions
QDeclarativeInfo qmlInfo (const QObject *me)
QDeclarativeInfo qmlInfo (const QObject *me, const QDeclarativeError &error)
QDeclarativeInfo qmlInfo (const QObject *me, const QList< QDeclarativeError > &errors)
Function Documentation
qmlInfo() [1/3]
QDeclarativeInfo qmlInfo (const QObject * me) related
Definition at line 155 of file qdeclarativeinfo.cpp.
Referenced by QDeclarativeVisualDataModel::_q_itemsChanged(), QDeclarativeLoaderPrivate::_q_sourceLoaded(), FlatListModel::addValue(), QDeclarativeListModel::agent(), QDeclarativeListModel::append(), QDeclarativeXmlListModelPrivate::append_role(), QDeclarativeAnchorsPrivate::centerInChanged(), QDeclarativeAnchorsPrivate::checkHAnchorValid(), QDeclarativeAnchorsPrivate::checkHValid(), QDeclarativeAnchorsPrivate::checkVAnchorValid(), QDeclarativeAnchorsPrivate::checkVValid(), QDeclarativeConnections::connectSignals(), QDeclarativeTextInput::createCursor(), QDeclarativeComponent::createObject(), QDeclarativeAbstractAnimationPrivate::createProperty(), QDeclarativeParentChangePrivate::doChange(), QDeclarativeStateChangeScript::execute(), QDeclarativeScriptActionPrivate::execute(), QDeclarativeAnchorsPrivate::fillChanged(), QDeclarativeGestureAreaPrivate::gestureEvent(), QDeclarativeParticles::imageLoaded(), QDeclarativeListModel::insert(), QDeclarativeTextEdit::isRightToLeft(), QDeclarativeTextInput::isRightToLeft(), QDeclarativeVisualDataModel::item(), QDeclarativeBorderImage::load(), QDeclarativeAnimatedImage::load(), QDeclarativeTextEdit::loadCursorDelegate(), QTextDocumentWithImageResources::loadResource(), QDeclarativeItem::mapFromItem(), QDeclarativeItem::mapToItem(), QDeclarativeListModel::move(), QDeclarativeAnimatedImage::movieRequestFinished(), QDeclarativeInfo::operator<<(), QDeclarativePropertyChangesPrivate::property(), QDeclarativeLayoutMirroringAttached::QDeclarativeLayoutMirroringAttached(), QDeclarativeXmlListModel::queryError(), QDeclarativeListModel::remove(), QDeclarativeColumn::reportConflictingAnchors(), QDeclarativeRow::reportConflictingAnchors(), QDeclarativeGrid::reportConflictingAnchors(), QDeclarativeFlow::reportConflictingAnchors(), QDeclarativeBorderImage::requestFinished(), QDeclarativeImageBase::requestFinished(), QDeclarativeCompiledBindingsPrivate::run(), QDeclarativeListModel::set(), QDeclarativeBehavior::setAnimation(), QDeclarativeFlipable::setBack(), QDeclarativeAnchors::setCenterIn(), QDeclarativeStateGroupPrivate::setCurrentStateInternal(), QDeclarativePauseAnimation::setDuration(), QDeclarativePropertyAnimation::setDuration(), QDeclarativeAnchorAnimation::setDuration(), QDeclarativeAnchors::setFill(), QDeclarativeFlipable::setFront(), QDeclarativeBorderImage::setGridScaledImage(), QDeclarativeAbstractAnimation::setPaused(), QDeclarativeListModel::setProperty(), FlatListScriptClass::setProperty(), QDeclarativeXmlListModel::setQuery(), QDeclarativeXmlListModelRole::setQuery(), QDeclarativeAbstractAnimation::setRunning(), QDeclarativeParticles::setSource(), QDeclarativeBorderImage::setSourceSize(), QDeclarativeTextInputPrivate::startCreatingCursor(), QDeclarativeListModel::sync(), QDeclarativeParentAnimation::transition(), QDeclarativeBinding::update(), QDeclarativeFontLoader::updateFontInfo(), QDeclarativeAnchorsPrivate::updateHorizontalAnchors(), and QDeclarativeAnchorsPrivate::updateVerticalAnchors().
 {
     QDeclarativeInfoPrivate *d = new QDeclarativeInfoPrivate;
     d->object = me;
     return QDeclarativeInfo(d);
 }
qmlInfo() [2/3]
QDeclarativeInfo qmlInfo (const QObject * me, const QDeclarativeError & error)
Definition at line 162 of file qdeclarativeinfo.cpp.
 {
     QDeclarativeInfoPrivate *d = new QDeclarativeInfoPrivate;
     d->object = me;
     d->errors << error;
     return QDeclarativeInfo(d);
 }
qmlInfo() [3/3]
QDeclarativeInfo qmlInfo (const QObject * me, const QList< QDeclarativeError > & errors)
Definition at line 170 of file qdeclarativeinfo.cpp.
 {
     QDeclarativeInfoPrivate *d = new QDeclarativeInfoPrivate;
     d->object = me;
     d->errors = errors;
     return QDeclarativeInfo(d);
 }