Qt 4.8: /src/gui/util/qdesktopservices_x11.cpp File Reference
qdesktopservices_x11.cpp File Reference
#include "qdesktopservices.h"
#include <qprocess.h>
#include <qurl.h>
#include <qdir.h>
#include <qfile.h>
#include <qtextstream.h>
#include <private/qt_x11_p.h>
#include <qcoreapplication.h>
#include <stdlib.h>
Functions
static bool launch (const QUrl &url, const QString &client)
static bool launchWebBrowser (const QUrl &url)
static bool openDocument (const QUrl &url)
Function Documentation
launch()
static bool launch (const QUrl & url, const QString & client) inline static
Definition at line 57 of file qdesktopservices_x11.cpp.
Referenced by launchWebBrowser(), and openDocument().
 {
 #if !defined(QT_NO_PROCESS)
     return (QProcess::startDetached(client + QLatin1Char(' ') + QString::fromLatin1(url.toEncoded().constData())));
 #else
     return (::system((client + QLatin1Char(' ') + QString::fromLatin1(url.toEncoded().constData())).toLocal8Bit().constData()) != -1);
 #endif
 }
launchWebBrowser()
static bool launchWebBrowser (const QUrl & url) static
Definition at line 95 of file qdesktopservices_x11.cpp.
 {
     if (!url.isValid())
         return false;
     if (url.scheme() == QLatin1String("mailto"))
         return openDocument(url);
     if (launch(url, QLatin1String("xdg-open")))
         return true;
     if (launch(url, QString::fromLocal8Bit(getenv("DEFAULT_BROWSER"))))
         return true;
     if (launch(url, QString::fromLocal8Bit(getenv("BROWSER"))))
         return true;
     // Use the X11->desktopEnvironment value if X11 is non-NULL,
     //  otherwise just attempt to launch command regardless of the desktop environment
     if ((!X11 || (X11 && X11->desktopEnvironment == DE_GNOME)) && launch(url, QLatin1String("gnome-open"))) {
         return true;
     } else {
         if ((!X11 || (X11 && X11->desktopEnvironment == DE_KDE)) && launch(url, QLatin1String("kfmclient openURL")))
             return true;
     }
     if (launch(url, QLatin1String("firefox")))
         return true;
     if (launch(url, QLatin1String("mozilla")))
         return true;
     if (launch(url, QLatin1String("netscape")))
         return true;
     if (launch(url, QLatin1String("opera")))
         return true;
     return false;
 }
openDocument()
static bool openDocument (const QUrl & url) static
Definition at line 66 of file qdesktopservices_x11.cpp.
Referenced by launchWebBrowser().
 {
     if (!url.isValid())
         return false;
     if (launch(url, QLatin1String("xdg-open")))
         return true;
     // Use the X11->desktopEnvironment value if X11 is non-NULL,
     //  otherwise just attempt to launch command regardless of the desktop environment
     if ((!X11 || (X11 && X11->desktopEnvironment == DE_GNOME)) && launch(url, QLatin1String("gnome-open"))) {
         return true;
     } else {
         if ((!X11 || (X11 && X11->desktopEnvironment == DE_KDE)) && launch(url, QLatin1String("kfmclient exec")))
             return true;
     }
     if (launch(url, QLatin1String("firefox")))
         return true;
     if (launch(url, QLatin1String("mozilla")))
         return true;
     if (launch(url, QLatin1String("netscape")))
         return true;
     if (launch(url, QLatin1String("opera")))
         return true;
     return false;
 }