Qt 4.8: /src/gui/util/qdesktopservices_blackberry.cpp File Reference
qdesktopservices_blackberry.cpp File Reference
#include <qurl.h>
#include <bps/navigator.h>
#include <qdir.h>
Functions
static bool launchWebBrowser (const QUrl &url)
static bool navigatorInvoke (const QUrl &url)
static bool openDocument (const QUrl &file)
Function Documentation
launchWebBrowser()
static bool launchWebBrowser (const QUrl & url) static
Definition at line 60 of file qdesktopservices_blackberry.cpp.
Referenced by QDesktopServices::openUrl().
 {
     return navigatorInvoke(url);
 }
navigatorInvoke()
static bool navigatorInvoke (const QUrl & url) static
Definition at line 50 of file qdesktopservices_blackberry.cpp.
Referenced by launchWebBrowser(), and openDocument().
 {
     if (!url.isValid() || url.isRelative())
         return false;
     int ret = navigator_invoke(url.toString().toUtf8(), 0);
     return (ret == BPS_SUCCESS);
 }
openDocument()
static bool openDocument (const QUrl & file) static
Definition at line 65 of file qdesktopservices_blackberry.cpp.
Referenced by QDesktopServices::openUrl(), and QPatternist::ResourceLoader::ResourceLoader().
 {
     return navigatorInvoke(file);
 }