Qt 4.8: /src/gui/dialogs/qdialog.cpp File Reference
qdialog.cpp File Reference
#include "qdialog.h"
#include "qevent.h"
#include "qdesktopwidget.h"
#include "qpushbutton.h"
#include "qapplication.h"
#include "qlayout.h"
#include "qsizegrip.h"
#include "qwhatsthis.h"
#include "qmenu.h"
#include "qcursor.h"
#include "private/qdialog_p.h"
#include "qaccessible.h"
#include "qt_windows.h"
#include "qmenubar.h"
#include "qpointer.h"
#include "qguifunctions_wince.h"
#include "moc_qdialog.cpp"
Macros
#define SPI_GETSNAPTODEFBUTTON 95
Functions
bool qt_wince_is_mobile ()
bool qt_wince_is_smartphone ()
Macro Definition Documentation
SPI_GETSNAPTODEFBUTTON
#define SPI_GETSNAPTODEFBUTTON 95
Definition at line 81 of file qdialog.cpp.
Referenced by QDialog::setVisible().
Function Documentation
qt_wince_is_mobile()
bool qt_wince_is_mobile ()
Definition at line 296 of file qguifunctions_wince.cpp.
Referenced by QDialog::QDialog(), and qt_tablet_cleanup_wce().
{
      return (qt_wince_is_smartphone() || qt_wince_is_pocket_pc());
 }
qt_wince_is_smartphone()
bool qt_wince_is_smartphone ()
Definition at line 293 of file qguifunctions_wince.cpp.
Referenced by QDialog::exec(), and QDialog::QDialog().
{
        return qt_wince_is_platform(QString::fromLatin1("Smartphone"));
 }