Qt 4.8: /src/plugins/platforms/directfb/qdirectfbconvenience.h File Reference
qdirectfbconvenience.h File Reference
#include <QtGui/qimage.h>
#include <QtCore/QHash>
#include <QtCore/QEvent>
#include <QtGui/QPixmap>
#include <directfb.h>
Classes
class QDirectFbConvenience
struct QDirectFBInterfaceCleanupHandler< T >
class QDirectFbKeyMap
class QDirectFBPointer< T >
Macros
#define QDFB_PRETTY (__FILE__ ":" QDFB_TOSTRING(__LINE__))
#define QDFB_STRINGIFY(x) #x
#define QDFB_TOSTRING(x) QDFB_STRINGIFY(x)
Functions
IDirectFBDisplayLayer * toDfbLayer (QPlatformScreen *screen)
QDirectFbScreen * toDfbScreen (QWidget *window)
Macro Definition Documentation
QDFB_PRETTY
#define QDFB_PRETTY (__FILE__ ":" QDFB_TOSTRING(__LINE__))
Definition at line 120 of file qdirectfbconvenience.h.
Referenced by QDirectFbWindow::dfbSurface(), and QDirectFbBlitterPlatformPixmap::fromDataBufferDescription().
QDFB_STRINGIFY
#define QDFB_STRINGIFY (x) #x
Definition at line 118 of file qdirectfbconvenience.h.
QDFB_TOSTRING
#define QDFB_TOSTRING (x) QDFB_STRINGIFY(x)
Definition at line 119 of file qdirectfbconvenience.h.
Function Documentation
toDfbLayer()
IDirectFBDisplayLayer* toDfbLayer (QPlatformScreen * screen)
Definition at line 392 of file qdirectfbconvenience.cpp.
Referenced by QDirectFBCursor::changeCursor(), and QDirectFBPointer< IDirectFBSurface >::outPtr().
 {
     return static_cast<QDirectFbScreen*>(screen)->dfbLayer();
 }
toDfbScreen()
QDirectFbScreen* toDfbScreen (QWidget * window)
Definition at line 387 of file qdirectfbconvenience.cpp.
Referenced by QDirectFBPointer< IDirectFBSurface >::outPtr(), and QDirectFbWindow::QDirectFbWindow().
 {
     return static_cast<QDirectFbScreen*>(QPlatformScreen::platformScreenForWidget(window));
 }