Qt 4.8: /src/plugins/gfxdrivers/directfb/qdirectfbpaintengine.cpp File Reference
qdirectfbpaintengine.cpp File Reference
#include "qdirectfbpaintengine.h"
#include "qdirectfbwindowsurface.h"
#include "qdirectfbscreen.h"
#include "qdirectfbpixmap.h"
#include <directfb.h>
#include <qtransform.h>
#include <qvarlengtharray.h>
#include <qcache.h>
#include <qmath.h>
#include <private/qpixmapdata_p.h>
#include <private/qpixmap_raster_p.h>
#include <private/qimagepixmapcleanuphooks_p.h>
Classes
class QDirectFBPaintEnginePrivate
class SurfaceCache
Macros
#define CLIPPED_PAINT(operation)
#define RASTERFALLBACK(op, one, two, three)
#define VOID_ARG() static_cast<bool>(false)
Enumerations
enum { RasterWarn = 1, RasterDisable = 2 }
enum PaintOperation {
DRAW_RECTS = 0x0001, DRAW_LINES = 0x0002, DRAW_IMAGE = 0x0004, DRAW_PIXMAP = 0x0008,
DRAW_TILED_PIXMAP = 0x0010, STROKE_PATH = 0x0020, DRAW_PATH = 0x0040, DRAW_POINTS = 0x0080,
DRAW_ELLIPSE = 0x0100, DRAW_POLYGON = 0x0200, DRAW_TEXT = 0x0400, FILL_PATH = 0x0800,
FILL_RECT = 0x1000, DRAW_COLORSPANS = 0x2000, DRAW_ROUNDED_RECT = 0x4000, DRAW_STATICTEXT = 0x8000,
ALL = 0xffff
}
Functions
static uint ALPHA_MUL (uint x, uint a)
template<class T >
static void drawLines (const T *lines, int n, const QTransform &transform, IDirectFBSurface *surface)
template<class T >
static void drawPoints (const T *points, int n, const QTransform &transform, IDirectFBSurface *surface)
template<class T >
static void drawRects (const T *rects, int n, const QTransform &transform, IDirectFBSurface *surface)
template<class T >
static void fillRects (const T *rects, int n, const QTransform &transform, IDirectFBSurface *surface)
static qreal fixCoord (qreal rect_pos, qreal pixmapSize, qreal offset)
static QRect map (const QTransform &transform, const QRect &rect)
static QRect map (const QTransform &transform, const QRectF &rect)
static QLine map (const QTransform &transform, const QLine &line)
static QLine map (const QTransform &transform, const QLineF &line)
static QPoint map (const QTransform &transform, const QPoint &point)
static QPoint map (const QTransform &transform, const QPointF &point)
template<typename T >
const T * ptr (const T &t)
template<>
const bool * ptr< bool > (const bool &)
static uint rasterFallbacksMask (PaintOperation op)
template<typename device , typename T1 , typename T2 , typename T3 >
static void rasterFallbackWarn (const char *msg, const char *func, const device *dev, QDirectFBPaintEnginePrivate *priv, const char *nameOne, const T1 &one, const char *nameTwo, const T2 &two, const char *nameThree, const T3 &three)
Macro Definition Documentation
CLIPPED_PAINT
#define CLIPPED_PAINT (operation)
Value:
{                                      \
        d->unlock();                                                    \
        DFBRegion clipRegion;                                           \
        switch (d->clipType) {                                          \
        case QDirectFBPaintEnginePrivate::NoClip:                       \
        case QDirectFBPaintEnginePrivate::RectClip:                     \
            operation;                                                  \
            break;                                                      \
        case QDirectFBPaintEnginePrivate::RegionClip: {                 \
            Q_ASSERT(d->clip());                                        \
            const QVector<QRect> cr = d->clip()->clipRegion.rects();    \
            const int size = cr.size();                                 \
            for (int i=0; i<size; ++i) {                                \
                d->currentClip = cr.at(i);                              \
                clipRegion.x1 = d->currentClip.x();                     \
                clipRegion.y1 = d->currentClip.y();                     \
                clipRegion.x2 = d->currentClip.right();                 \
                clipRegion.y2 = d->currentClip.bottom();                \
                d->surface->SetClip(d->surface, &clipRegion);           \
                operation;                                              \
            }                                                           \
            d->updateClip();                                            \
            break; }                                                    \
        case QDirectFBPaintEnginePrivate::ComplexClip:                  \
        case QDirectFBPaintEnginePrivate::ClipUnset:                    \
            qFatal("CLIPPED_PAINT internal error %d", d->clipType);     \
            break;                                                      \
        }                                                               \
    }
Definition at line 320 of file qdirectfbpaintengine.cpp.
Referenced by QDirectFBPaintEngine::drawImage(), QDirectFBPaintEngine::drawLines(), QDirectFBPaintEngine::drawPixmap(), QDirectFBPaintEngine::drawPoints(), QDirectFBPaintEngine::drawRects(), QDirectFBPaintEngine::drawTiledPixmap(), and QDirectFBPaintEngine::fillRect().
RASTERFALLBACK
#define RASTERFALLBACK (op, one, two, three)
Value:
{                                                                   \
        static const uint rasterFallbacks = rasterFallbacksMask(op);    \
        switch (rasterFallbacks) {                                      \
        case 0: break;                                                  \
        case RasterWarn:                                                \
            rasterFallbackWarn("Falling back to raster engine for",     \
                               __FUNCTION__,                            \
                               state()->painter->device(),              \
                               d_func(),                                \
                               #one, one, #two, two, #three, three);    \
            break;                                                      \
        case RasterDisable|RasterWarn:                                  \
            rasterFallbackWarn("Disabled raster engine operation",      \
                               __FUNCTION__,                            \
                               state()->painter->device(),              \
                               d_func(),                                \
                               #one, one, #two, two, #three, three);    \
        case RasterDisable:                                             \
            return;                                                     \
        }                                                               \
    }
Definition at line 288 of file qdirectfbpaintengine.cpp.
Referenced by QDirectFBPaintEngine::drawEllipse(), QDirectFBPaintEngine::drawImage(), QDirectFBPaintEngine::drawLines(), QDirectFBPaintEngine::drawPath(), QDirectFBPaintEngine::drawPixmap(), QDirectFBPaintEngine::drawPoints(), QDirectFBPaintEngine::drawPolygon(), QDirectFBPaintEngine::drawRects(), QDirectFBPaintEngine::drawRoundedRect(), QDirectFBPaintEngine::drawStaticTextItem(), QDirectFBPaintEngine::drawTextItem(), QDirectFBPaintEngine::drawTiledPixmap(), QDirectFBPaintEngine::fill(), QDirectFBPaintEngine::fillRect(), and QDirectFBPaintEngine::stroke().
VOID_ARG
#define VOID_ARG () static_cast<bool>(false)
Definition at line 183 of file qdirectfbpaintengine.cpp.
Referenced by QDirectFBPaintEngine::drawEllipse(), QDirectFBPaintEngine::drawLines(), QDirectFBPaintEngine::drawPath(), QDirectFBPaintEngine::drawPoints(), QDirectFBPaintEngine::drawPolygon(), QDirectFBPaintEngine::drawRects(), QDirectFBPaintEngine::drawStaticTextItem(), QDirectFBPaintEngine::drawTextItem(), QDirectFBPaintEngine::fill(), QDirectFBPaintEngine::fillRect(), and QDirectFBPaintEngine::stroke().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RasterWarn
RasterDisable
Definition at line 206 of file qdirectfbpaintengine.cpp.
 { RasterWarn = 1, RasterDisable = 2 };
PaintOperation
enum PaintOperation
Enumerator
DRAW_RECTS
DRAW_LINES
DRAW_IMAGE
DRAW_PIXMAP
DRAW_TILED_PIXMAP
STROKE_PATH
DRAW_PATH
DRAW_POINTS
DRAW_ELLIPSE
DRAW_POLYGON
DRAW_TEXT
FILL_PATH
FILL_RECT
DRAW_COLORSPANS
DRAW_ROUNDED_RECT
DRAW_STATICTEXT
ALL
Definition at line 184 of file qdirectfbpaintengine.cpp.
                     {
     DRAW_RECTS          = 0x0001,
     DRAW_LINES          = 0x0002,
     DRAW_IMAGE          = 0x0004,
     DRAW_PIXMAP         = 0x0008,
     DRAW_TILED_PIXMAP   = 0x0010,
     STROKE_PATH         = 0x0020,
     DRAW_PATH           = 0x0040,
     DRAW_POINTS         = 0x0080,
     DRAW_ELLIPSE        = 0x0100,
     DRAW_POLYGON        = 0x0200,
     DRAW_TEXT           = 0x0400,
     FILL_PATH           = 0x0800,
     FILL_RECT           = 0x1000,
     DRAW_COLORSPANS     = 0x2000,
     DRAW_ROUNDED_RECT   = 0x4000,
     DRAW_STATICTEXT     = 0x8000,
     ALL                 = 0xffff
 };
Function Documentation
ALPHA_MUL()
static uint ALPHA_MUL (uint x, uint a) inline static
Definition at line 1138 of file qdirectfbpaintengine.cpp.
Referenced by QDirectFBPaintEnginePrivate::prepareForDraw().
 {
     uint t = x * a;
     t = ((t + (t >> 8) + 0x80) >> 8) & 0xff;
     return t;
 }
drawLines()
template<class T > static void drawLines (const T * lines, int n, const QTransform & transform, IDirectFBSurface * surface) inline static
Definition at line 1452 of file qdirectfbpaintengine.cpp.
Referenced by QPainter::drawLine(), QOpenGLPaintEngine::drawLines(), QPainter::drawLines(), QPaintEngine::setActive(), QOpenGLPaintEngine::state(), QRasterPaintEngine::state(), QPaintBufferEngine::type(), and QPdfBaseEngine::~QPdfBaseEngine().
 {
     if (n == 1) {
         const QLine l = map(transform, lines[0]);
         surface->DrawLine(surface, l.x1(), l.y1(), l.x2(), l.y2());
     } else {
         QVarLengthArray<DFBRegion, 32> lineArray(n);
         for (int i=0; i<n; ++i) {
             const QLine l = map(transform, lines[i]);
             lineArray[i].x1 = l.x1();
             lineArray[i].y1 = l.y1();
             lineArray[i].x2 = l.x2();
             lineArray[i].y2 = l.y2();
         }
         surface->DrawLines(surface, lineArray.constData(), n);
     }
 }
drawPoints()
template<class T > static void drawPoints (const T * points, int n, const QTransform & transform, IDirectFBSurface * surface) inline static
Definition at line 1433 of file qdirectfbpaintengine.cpp.
Referenced by QCosmeticStroker::drawLine(), QOpenGLPaintEngine::drawLines(), QPainter::drawPoint(), QOpenGLPaintEngine::drawPoints(), QPaintEngine::drawPoints(), QPainter::drawPoints(), QPaintEngine::setActive(), QOpenGLPaintEngine::state(), QRasterPaintEngine::state(), QPainter::testRenderHint(), QPaintBufferEngine::type(), and QPdfBaseEngine::~QPdfBaseEngine().
 {
     if (n == 1) {
         const QPoint p = map(transform, points[0]);
         surface->FillRectangle(surface, p.x(), p.y(), 1, 1);
     } else {
         QVarLengthArray<DFBRectangle, 32> rectArray(n);
         for (int i=0; i<n; ++i) {
             const QPoint p = map(transform, points[i]);
             rectArray[i].x = p.x();
             rectArray[i].y = p.y();
             rectArray[i].w = 1;
             rectArray[i].h = 1;
         }
         surface->FillRectangles(surface, rectArray.constData(), n);
     }
 }
drawRects()
template<class T > static void drawRects (const T * rects, int n, const QTransform & transform, IDirectFBSurface * surface) inline static
Definition at line 1490 of file qdirectfbpaintengine.cpp.
Referenced by QRasterPaintEngine::drawPolygon(), QPainter::drawRect(), QOpenGLPaintEngine::drawRects(), QPainter::drawRects(), QOpenGLPaintEngine::fill(), QPaintEngine::setActive(), QOpenGLPaintEngine::state(), QRasterPaintEngine::state(), QPaintBufferEngine::type(), and QPdfBaseEngine::~QPdfBaseEngine().
 {
     for (int i=0; i<n; ++i) {
         const QRect r = map(transform, rects[i]);
         surface->DrawRectangle(surface, r.x(), r.y(), r.width(), r.height());
     }
 }
fillRects()
template<class T > static void fillRects (const T * rects, int n, const QTransform & transform, IDirectFBSurface * surface) inline static
Definition at line 1471 of file qdirectfbpaintengine.cpp.
 {
     if (n == 1) {
         const QRect r = map(transform, rects[0]);
         surface->FillRectangle(surface, r.x(), r.y(), r.width(), r.height());
     } else {
         QVarLengthArray<DFBRectangle, 32> rectArray(n);
         for (int i=0; i<n; ++i) {
             const QRect r = map(transform, rects[i]);
             rectArray[i].x = r.x();
             rectArray[i].y = r.y();
             rectArray[i].w = r.width();
             rectArray[i].h = r.height();
         }
         surface->FillRectangles(surface, rectArray.constData(), n);
     }
 }
fixCoord()
static qreal fixCoord (qreal rect_pos, qreal pixmapSize, qreal offset) inline static
Definition at line 1240 of file qdirectfbpaintengine.cpp.
Referenced by QDirectFBPaintEnginePrivate::drawTiledPixmap().
 {
     qreal pos = rect_pos - offset;
     while (pos > rect_pos)
         pos -= pixmapSize;
     while (pos + pixmapSize < rect_pos)
         pos += pixmapSize;
     return pos;
 }
map() [1/6]
static QRect map (const QTransform & transform, const QRect & rect) inline static
Definition at line 1425 of file qdirectfbpaintengine.cpp.
Referenced by drawLines(), drawPoints(), drawRects(), and fillRects().
 { return transform.mapRect(rect); }
map() [2/6]
static QRect map (const QTransform & transform, const QRectF & rect) inline static
Definition at line 1426 of file qdirectfbpaintengine.cpp.
 { return transform.mapRect(rect).toRect(); }
map() [3/6]
static QLine map (const QTransform & transform, const QLine & line) inline static
Definition at line 1427 of file qdirectfbpaintengine.cpp.
 { return transform.map(line); }
map() [4/6]
static QLine map (const QTransform & transform, const QLineF & line) inline static
Definition at line 1428 of file qdirectfbpaintengine.cpp.
 { return transform.map(line).toLine(); }
map() [5/6]
static QPoint map (const QTransform & transform, const QPoint & point) inline static
Definition at line 1429 of file qdirectfbpaintengine.cpp.
 { return transform.map(point); }
map() [6/6]
static QPoint map (const QTransform & transform, const QPointF & point) inline static
Definition at line 1430 of file qdirectfbpaintengine.cpp.
 { return transform.map(point).toPoint(); }
ptr()
template<typename T > const T* ptr (const T & t) inline
Definition at line 1498 of file qdirectfbpaintengine.cpp.
Referenced by _decOctet(), _fragment(), _getWord0(), _getWord1(), _HEXDIG(), _hierPart(), _host(), _IPLiteral(), _IPv4Address(), _IPv6Address(), _IPvFuture(), _ls32(), _pctEncoded(), _port(), QProcessPrivate::_q_canReadStandardError(), QProcessPrivate::_q_canReadStandardOutput(), _q_ia64_fetchadd_immediate(), QHttpPrivate::_q_slotReadyRead(), _query(), _scheme(), _setWord0(), _setWord1(), _subDelims(), _unreserved(), _userInfo(), QNetworkManagerEngine::activationFinished(), QNetworkManagerEngine::activeConnectionPropertiesChanged(), QIcdEngine::addConfiguration(), QConnmanEngine::addServiceConfiguration(), QNetworkConfigurationManagerPrivate::allConfigurations(), QNetworkInterfaceManager::allInterfaces(), QHashData::allocateNode(), QPMCache::allPixmaps(), buttonChange(), QNetworkManagerEngine::bytesReceived(), QNetworkManagerEngine::bytesWritten(), QVariant::canConvert(), QUrlPrivate::canonicalHost(), QMetaObject::changeGuard(), QNetworkConfigurationManagerPrivate::configurationAdded(), QConnmanEngine::configurationChange(), QNetworkConfigurationManagerPrivate::configurationChanged(), QNetworkConfigurationManagerPrivate::configurationRemoved(), QIcdEngine::connectionStateSignalsSlot(), QCoreWlanEngine::connectToId(), connManager(), construct(), QScriptEngine::convert(), convertFlags(), QCP949Codec::convertFromUnicode(), QScriptEnginePrivate::convertNumber(), QScriptEnginePrivate::convertString(), QScriptEnginePrivate::convertValue(), QScriptEnginePrivate::create(), createInterfaces(), QNetworkConfigurationManagerPrivate::defaultConfiguration(), QIcdEngine::deleteConfiguration(), QDBusConnectionPrivate::deliverCall(), QLocalSocketPrivate::destroyPipeHandles(), QAxBasePrivate::dispatch(), QTranslatorPrivate::do_load(), QGenericEngine::doRequestUpdate(), QIcdEngine::doRequestUpdate(), downloadBufferDeleter(), QGraphicsScenePrivate::draw(), QPaintEngineEx::drawEllipse(), QIcdEngine::ensureDBusConnection(), QPixmapCache::find(), QAbstractSocketPrivate::flush(), QScanThread::foundNetwork(), QScriptEngine::fromScriptValue(), QScriptEnginePrivate::get(), QIcdEngine::getIcdInitialState(), QIcdEngine::icdServiceOwnerChanged(), QRingBuffer< T >::indexOf(), QXcbConnection::initializeAllAtoms(), QTestLiteStaticInfoPrivate::initializeAllAtoms(), interfaceListing(), interfaceListingWin2k(), interfaceListingWinXP(), QNetworkManagerEngine::interfacePropertiesChanged(), QtSharedPointer::internalSafetyCheckRemove(), ipv4Netmasks(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), QOCIResult::lastInsertId(), QFSFileEnginePrivate::longFileName(), QFSFileEnginePrivate::map(), myalloc(), QFSFileEnginePrivate::nativeRead(), QFSFileEnginePrivate::nativeWrite(), QCoreWlanEngine::networksChanged(), QNlaEngine::networksChanged(), QNetworkManagerEngine::newAccessPoint(), QNetworkManagerEngine::newConnection(), QPMCache::object(), QScriptValuePrivate::operator delete(), QExplicitlySharedDataPointer< QSslConfigurationPrivate >::operator!=(), QModelIndex::operator<(), QExplicitlySharedDataPointer< QSslConfigurationPrivate >::operator==(), QTextStream::operator>>(), QTest::outputMessage(), QUrlPrivate::parse(), QNetworkManagerEngine::parseConnection(), QDirectFBWindowSurface::permanentState(), QWSLocalMemSurface::permanentState(), QWSSharedMemSurface::permanentState(), QWSOnScreenSurface::permanentState(), QWSYellowSurface::permanentState(), QRingBuffer< T >::putChar(), q_strchr(), QAxBasePrivate::QAxBasePrivate(), qdbus_resolve_me(), qFieldSerial(), qFreeAligned(), qGetPtrHelper(), qIterGet(), qPixmapSerial(), qt_atomic_tasb(), qt_load_library_runtime(), qt_message_output(), qt_socks5_set_host_address_and_port(), qt_socks5_set_host_name_and_port(), qt_x11_create_intern_atoms(), rasterFallbackWarn(), QRfbDualColorHextile< SRC >::read(), QRingBuffer< T >::read(), QRfbMultiColorHextile< SRC >::read(), QAbstractSocket::readData(), QProcess::readData(), QAbstractSocketPrivate::readFromSocket(), QRfbMultiColorHextile< SRC >::rectx(), QRfbMultiColorHextile< SRC >::recty(), QFactoryLoader::refreshAll(), QDeclarativeEnginePrivate::registerCompositeType(), QDynamicFileResourceRoot::registerSelf(), QNetworkManagerEngine::removeAccessPoint(), QBBEngine::removeConfiguration(), QConnmanEngine::removeConfiguration(), QNetworkManagerEngine::removeConnection(), QMetaObject::removeGuard(), QNativeWifiEngine::scanComplete(), QScript::scriptableFromQObject(), QTest::sendKeyEvent(), QGenericEngine::sessionStateForId(), QBBEngine::sessionStateForId(), QCoreWlanEngine::sessionStateForId(), QNativeWifiEngine::sessionStateForId(), QNetworkManagerEngine::sessionStateForId(), QConnmanEngine::sessionStateForId(), QNlaEngine::sessionStateForId(), QDBusContextPrivate::set(), QNetmaskAddress::setAddress(), QWSRegionCommand::setData(), QPluginLoader::setFileName(), QRfbMultiColorHextile< SRC >::setHeight(), QDirectFBWindowSurface::setPermanentState(), QWSLocalMemSurface::setPermanentState(), QWSSharedMemSurface::setPermanentState(), QWSOnScreenSurface::setPermanentState(), QWSYellowSurface::setPermanentState(), QNetworkSessionPrivate::setPrivateConfiguration(), QRfbMultiColorHextile< SRC >::setWidth(), QRfbMultiColorHextile< SRC >::setX(), QRfbMultiColorHextile< SRC >::setY(), QLocalSocketPrivate::startAsyncRead(), QNetworkSessionPrivateImpl::syncStateWithInterface(), QDBusDemarshaller::toVariantInternal(), QSslSocketBackendPrivate::transmit(), QFSFileEnginePrivate::unmap(), QNetworkManagerEngine::updateAccessPoint(), QBBEngine::updateConfiguration(), QNetworkManagerEngine::updateConnection(), voidptr_destructor(), QOstDevice::writeData(), QAbstractSocket::writeData(), and QAxBasePrivate::~QAxBasePrivate().
 { return &t; }
ptr< bool >()
template<> const bool* ptr< bool > (const bool &) inline
Definition at line 1499 of file qdirectfbpaintengine.cpp.
 { return 0; }
rasterFallbacksMask()
static uint rasterFallbacksMask (PaintOperation op) inline static
Definition at line 207 of file qdirectfbpaintengine.cpp.
 {
     uint ret = 0;
 #ifdef QT_DIRECTFB_WARN_ON_RASTERFALLBACKS
     if (op & QT_DIRECTFB_WARN_ON_RASTERFALLBACKS)
         ret |= RasterWarn;
 #endif
 #ifdef QT_DIRECTFB_DISABLE_RASTERFALLBACKS
     if (op & QT_DIRECTFB_DISABLE_RASTERFALLBACKS)
         ret |= RasterDisable;
 #endif
     static int warningMask = -1;
     static int disableMask = -1;
     if (warningMask < 0) {
         struct {
             const char *name;
             PaintOperation operation;
         } const operations[] = {
             { "DRAW_RECTS", DRAW_RECTS },
             { "DRAW_LINES", DRAW_LINES },
             { "DRAW_IMAGE", DRAW_IMAGE },
             { "DRAW_PIXMAP", DRAW_PIXMAP },
             { "DRAW_TILED_PIXMAP", DRAW_TILED_PIXMAP },
             { "STROKE_PATH", STROKE_PATH },
             { "DRAW_PATH", DRAW_PATH },
             { "DRAW_POINTS", DRAW_POINTS },
             { "DRAW_ELLIPSE", DRAW_ELLIPSE },
             { "DRAW_POLYGON", DRAW_POLYGON },
             { "DRAW_TEXT", DRAW_TEXT },
             { "FILL_PATH", FILL_PATH },
             { "FILL_RECT", FILL_RECT },
             { "DRAW_COLORSPANS", DRAW_COLORSPANS },
             { "DRAW_ROUNDED_RECT", DRAW_ROUNDED_RECT },
             { "ALL", ALL },
             { 0, ALL }
         };
         QStringList warning = QString::fromLatin1(qgetenv("QT_DIRECTFB_WARN_ON_RASTERFALLBACKS")).toUpper().split(QLatin1Char('|'),
                                                                                                                   QString::SkipEmptyParts);
         QStringList disable = QString::fromLatin1(qgetenv("QT_DIRECTFB_DISABLE_RASTERFALLBACKS")).toUpper().split(QLatin1Char('|'),
                                                                                                                   QString::SkipEmptyParts);
         warningMask = 0;
         disableMask = 0;
         if (!warning.isEmpty() || !disable.isEmpty()) {
             for (int i=0; operations[i].name; ++i) {
                 const QString name = QString::fromLatin1(operations[i].name);
                 int idx = warning.indexOf(name);
                 if (idx != -1) {
                     warningMask |= operations[i].operation;
                     warning.erase(warning.begin() + idx);
                 }
                 idx = disable.indexOf(name);
                 if (idx != -1) {
                     disableMask |= operations[i].operation;
                     disable.erase(disable.begin() + idx);
                 }
             }
         }
         if (!warning.isEmpty()) {
             qWarning("QDirectFBPaintEngine QT_DIRECTFB_WARN_ON_RASTERFALLBACKS Unknown operation(s): %s",
                      qPrintable(warning.join(QLatin1String("|"))));
         }
         if (!disable.isEmpty()) {
             qWarning("QDirectFBPaintEngine QT_DIRECTFB_DISABLE_RASTERFALLBACKS Unknown operation(s): %s",
                      qPrintable(disable.join(QLatin1String("|"))));
         }
     }
     if (op & warningMask)
         ret |= RasterWarn;
     if (op & disableMask)
         ret |= RasterDisable;
     return ret;
 }
rasterFallbackWarn()
template<typename device , typename T1 , typename T2 , typename T3 > static void rasterFallbackWarn (const char * msg, const char * func, const device * dev, QDirectFBPaintEnginePrivate * priv, const char * nameOne, const T1 & one, const char * nameTwo, const T2 & two, const char * nameThree, const T3 & three) static
Definition at line 1501 of file qdirectfbpaintengine.cpp.
Referenced by rasterFallbacksMask().
 {
     QString out;
     QDebug dbg(&out);
     dbg << "***";
     dbg << msg << (QByteArray(func) + "()")  << "painting on";
     if (dev->devType() == QInternal::Widget) {
         dbg << static_cast<const QWidget*>(dev);
     } else {
         dbg << dev << "of type" << dev->devType();
     }
     dbg << "\n\t";
     dbg << ((priv->transformationType & QDirectFBPaintEnginePrivate::Matrix_BlitsUnsupported) ? "*" : "") << QString::fromLatin1("transformationType 0x%1").arg(priv->transformationType, 3, 16, QLatin1Char('0'));
     dbg << priv->engine->state()->matrix;
     dbg << "\n\t";
     dbg << (priv->supportedBrush ? "" : "*") << "supportedBrush" << priv->supportedBrush;
     dbg << priv->engine->state()->brush;
     dbg << "\n\t";
     const QGradient *gradient = priv->engine->state()->brush.gradient();
     if (gradient) {
         const QGradientStops &stops = gradient->stops();
         dbg << "gradient: " << *gradient;
         dbg << "stops: " << stops.count();
         dbg << "\n\t";
         for (int i=0; i<stops.count(); i++) {
             dbg << stops[i].first << stops[i].second;
         }
         dbg << "\n\t";
     }
     dbg << (priv->supportedPen ? "" : "*") << "supportedPen" << priv->supportedPen;
     dbg << priv->engine->state()->pen;
     dbg << "\n\t";
     dbg << (priv->clipType == QDirectFBPaintEnginePrivate::ComplexClip ? "*" : "") << "clipType" << priv->clipType;
     dbg << "\n\t";
     dbg << (priv->supportedComposition ? "" : "*") << "supportedComposition" << priv->supportedComposition;
     dbg << "\n\t";
     const T1 *t1 = ptr(one);
     const T2 *t2 = ptr(two);
     const T3 *t3 = ptr(three);
     if (t1) {
         dbg << nameOne << *t1;
         if (t2) {
             dbg << nameTwo << *t2;
             if (t3) {
                 dbg << nameThree << *t3;
             }
         }
     }
     qWarning("%s", qPrintable(out));
 }