Qt 4.8: /src/gui/embedded/qdirectpainter_qws.cpp File Reference
qdirectpainter_qws.cpp File Reference
#include "qdirectpainter_qws.h"
#include "qscreen_qws.h"
#include "private/qobject_p.h"
#include "private/qapplication_p.h"
#include "qwsdisplay_qws.h"
#include "qwidget.h"
#include "qimage.h"
#include <qwsevent_qws.h>
#include <private/qwindowsurface_qws_p.h>
#include <private/qwsdisplay_qws_p.h>
Classes
class QDirectPainterPrivate
Functions
static QSize devS ()
static QScreen * getPrimaryScreen ()
void qt_directpainter_embedevent (QDirectPainter *dp, const QWSEmbedEvent *event)
void qt_directpainter_region (QDirectPainter *dp, const QRegion &alloc, int type)
static QSize screenS ()
Function Documentation
devS()
static QSize devS () inline static
Definition at line 190 of file qdirectpainter_qws.cpp.
 {
     QScreen *screen = getPrimaryScreen();
     if (!screen)
         return QSize();
     return QSize(screen->deviceWidth(), screen->deviceHeight());
 }
getPrimaryScreen()
static QScreen* getPrimaryScreen () inline static
Definition at line 170 of file qdirectpainter_qws.cpp.
Referenced by devS(), QDirectPainter::frameBuffer(), QDirectPainter::linestep(), QDirectPainter::screenDepth(), QDirectPainter::screenHeight(), screenS(), and QDirectPainter::screenWidth().
 {
     QScreen *screen = QScreen::instance();
     if (!screen->base()) {
         QList<QScreen*> subScreens = screen->subScreens();
         if (subScreens.size() < 1)
             return 0;
         screen = subScreens.at(0);
     }
     return screen;
 }
qt_directpainter_embedevent()
void qt_directpainter_embedevent (QDirectPainter * dp, const QWSEmbedEvent * event)
Definition at line 244 of file qdirectpainter_qws.cpp.
Referenced by QApplication::qwsProcessEvent(), and QDirectPainter::region().
 {
     if (event->type | QWSEmbedEvent::Region) {
         QScreen *screen = dp->d_func()->surface->screen();
         QRegion r = event->region;
         if (screen->isTransformed()) {
             const QSize screenSize(screen->width(), screen->height());
             r = screen->mapToDevice(r, screenSize);
         }
         dp->setRegion(r);
     }
 }
qt_directpainter_region()
void qt_directpainter_region (QDirectPainter * dp, const QRegion & alloc, int type)
Definition at line 223 of file qdirectpainter_qws.cpp.
Referenced by QApplication::qwsProcessEvent(), and QDirectPainter::region().
 {
     QDirectPainterPrivate *d = dp->d_func();
     QRegion r = alloc;
     QScreen *screen = d->surface->screen();
     if (screen->isTransformed()) {
         const QSize screenSize(screen->width(), screen->height());
         r = screen->mapToDevice(r, screenSize);
     }
     if (type == QWSRegionEvent::Allocation) {
         d->surface->setClipRegion(alloc);
         d->seenRegion = true;
         if (dp != QDirectPainterPrivate::staticPainter) {
             if (!d->surface->flushingRegionEvents) // recursion guard
                 dp->regionChanged(r);
         }
     }
 }
screenS()
static QSize screenS () inline static
Definition at line 182 of file qdirectpainter_qws.cpp.
 {
     QScreen *screen = getPrimaryScreen();
     if (!screen)
         return QSize();
     return QSize(screen->width(), screen->height());
 }