Qt 4.8: /src/plugins/platforms/directfb/qdirectfbconvenience.cpp File Reference
qdirectfbconvenience.cpp File Reference
#include "qdirectfbconvenience.h"
#include "qdirectfbblitter.h"
#include "qdirectfbscreen.h"
#include <private/qpixmap_blitter_p.h>
#include <QtGui/QWidget>
#include <QtGui/QScreen>
Functions
IDirectFBDisplayLayer * toDfbLayer (QPlatformScreen *screen)
QDirectFbScreen * toDfbScreen (QWidget *window)
Function Documentation
toDfbLayer()
IDirectFBDisplayLayer* toDfbLayer (QPlatformScreen * screen)
Definition at line 392 of file qdirectfbconvenience.cpp.
Referenced by QDirectFBCursor::changeCursor(), and QDirectFBPointer< IDirectFBSurface >::outPtr().
 {
     return static_cast<QDirectFbScreen*>(screen)->dfbLayer();
 }
toDfbScreen()
QDirectFbScreen* toDfbScreen (QWidget * window)
Definition at line 387 of file qdirectfbconvenience.cpp.
Referenced by QDirectFBPointer< IDirectFBSurface >::outPtr(), and QDirectFbWindow::QDirectFbWindow().
 {
     return static_cast<QDirectFbScreen*>(QPlatformScreen::platformScreenForWidget(window));
 }