Qt 4.8: /src/gui/kernel/qdnd.cpp File Reference
qdnd.cpp File Reference
#include "qplatformdefs.h"
#include "qbitmap.h"
#include "qdrag.h"
#include "qpixmap.h"
#include "qevent.h"
#include "qfile.h"
#include "qtextcodec.h"
#include "qapplication.h"
#include "qpoint.h"
#include "qwidget.h"
#include "qbuffer.h"
#include "qimage.h"
#include "qregexp.h"
#include "qdir.h"
#include "qdnd_p.h"
#include "qimagereader.h"
#include "qimagewriter.h"
#include "qdebug.h"
#include <ctype.h>
#include <private/qapplication_p.h>
Functions
static QStringList imageReadMimeFormats ()
static QStringList imageWriteMimeFormats ()
Function Documentation
imageReadMimeFormats()
static QStringList imageReadMimeFormats () static
Definition at line 292 of file qdnd.cpp.
Referenced by QInternalMimeData::canReadData(), QInternalMimeData::formats(), QInternalMimeData::hasFormat(), and QInternalMimeData::retrieveData().
 {
     QStringList formats;
     QList<QByteArray> imageFormats = QImageReader::supportedImageFormats();
     for (int i = 0; i < imageFormats.size(); ++i) {
         QString format = QLatin1String("image/");
         format += QString::fromLatin1(imageFormats.at(i).toLower());
         formats.append(format);
     }
     //put png at the front because it is best
     int pngIndex = formats.indexOf(QLatin1String("image/png"));
     if (pngIndex != -1 && pngIndex != 0)
         formats.move(pngIndex, 0);
     return formats;
 }
imageWriteMimeFormats()
static QStringList imageWriteMimeFormats () static
Definition at line 311 of file qdnd.cpp.
Referenced by QInternalMimeData::formatsHelper(), and QInternalMimeData::hasFormatHelper().
 {
     QStringList formats;
     QList<QByteArray> imageFormats = QImageWriter::supportedImageFormats();
     for (int i = 0; i < imageFormats.size(); ++i) {
         QString format = QLatin1String("image/");
         format += QString::fromLatin1(imageFormats.at(i).toLower());
         formats.append(format);
     }
     //put png at the front because it is best
     int pngIndex = formats.indexOf(QLatin1String("image/png"));
     if (pngIndex != -1 && pngIndex != 0)
         formats.move(pngIndex, 0);
     return formats;
 }