Qt 4.8: /src/gui/kernel/qdnd_win.cpp File Reference
qdnd_win.cpp File Reference
#include "qapplication.h"
#include "qapplication_p.h"
#include "qevent.h"
#include "qpainter.h"
#include "qwidget.h"
#include "qbuffer.h"
#include "qdatastream.h"
#include "qcursor.h"
#include "qt_windows.h"
#include <shlobj.h>
#include "qaccessible.h"
#include "qdnd_p.h"
#include "qdebug.h"
#include "qguifunctions_wince.h"
Classes
class QOleDropSource
Macros
#define KEY_STATE_BUTTON_MASK (MK_LBUTTON | MK_MBUTTON | MK_RBUTTON)
#define MK_XBUTTON1 0x0020
#define MK_XBUTTON2 0x0040
Functions
static bool acceptsDrop (const QWidget *w)
static Qt::MouseButtons keystate_to_mousebutton (DWORD grfKeyState)
Qt::KeyboardModifiers toQtKeyboardModifiers (DWORD keyState)
Qt::MouseButtons toQtMouseButtons (DWORD keyState)
Qt::DropAction translateToQDragDropAction (DWORD pdwEffect)
Qt::DropActions translateToQDragDropActions (DWORD pdwEffects)
DWORD translateToWinDragEffects (Qt::DropActions action)
Macro Definition Documentation
KEY_STATE_BUTTON_MASK
#define KEY_STATE_BUTTON_MASK (MK_LBUTTON | MK_MBUTTON | MK_RBUTTON)
Definition at line 802 of file qdnd_win.cpp.
Referenced by QOleDropTarget::Drop().
MK_XBUTTON1
#define MK_XBUTTON1 0x0020
Definition at line 65 of file qdnd_win.cpp.
Referenced by keystate_to_mousebutton().
MK_XBUTTON2
#define MK_XBUTTON2 0x0040
Definition at line 66 of file qdnd_win.cpp.
Referenced by keystate_to_mousebutton().
Function Documentation
acceptsDrop()
static bool acceptsDrop (const QWidget * w) inline static
Definition at line 693 of file qdnd_win.cpp.
Referenced by QOleDropTarget::DragOver().
 {
     return w->testAttribute(Qt::WA_DropSiteRegistered) && w->acceptDrops();
 }
keystate_to_mousebutton()
static Qt::MouseButtons keystate_to_mousebutton (DWORD grfKeyState) inline static
Definition at line 499 of file qdnd_win.cpp.
Referenced by QOleDropSource::QueryContinueDrag().
 {
     Qt::MouseButtons result;
     if (grfKeyState & MK_LBUTTON)
         result |= Qt::LeftButton;
     if (grfKeyState & MK_MBUTTON)
         result |= Qt::MidButton;
     if (grfKeyState & MK_RBUTTON)
         result |= Qt::RightButton;
     if (grfKeyState & MK_XBUTTON1)
         result |= Qt::XButton1;
     if (grfKeyState & MK_XBUTTON2)
         result |= Qt::XButton2;
     return result;
 }
toQtKeyboardModifiers()
Qt::KeyboardModifiers toQtKeyboardModifiers (DWORD keyState)
Definition at line 318 of file qdnd_win.cpp.
Referenced by QOleDropTarget::DragOver(), QOleDropTarget::Drop(), and QOleDropTarget::sendDragEnterEvent().
 {
     Qt::KeyboardModifiers modifiers = Qt::NoModifier;
     if (keyState & MK_SHIFT)
         modifiers |= Qt::ShiftModifier;
     if (keyState & MK_CONTROL)
         modifiers |= Qt::ControlModifier;
     if (keyState & MK_ALT)
         modifiers |= Qt::AltModifier;
     return modifiers;
 }
toQtMouseButtons()
Qt::MouseButtons toQtMouseButtons (DWORD keyState)
Definition at line 332 of file qdnd_win.cpp.
Referenced by QOleDropTarget::DragOver(), QOleDropTarget::Drop(), and QOleDropTarget::sendDragEnterEvent().
 {
     Qt::MouseButtons buttons = Qt::NoButton;
     if (keyState & MK_LBUTTON)
         buttons |= Qt::LeftButton;
     if (keyState & MK_RBUTTON)
         buttons |= Qt::RightButton;
     if (keyState & MK_MBUTTON)
         buttons |= Qt::MidButton;
     return buttons;
 }
translateToQDragDropAction()
Qt::DropAction translateToQDragDropAction (DWORD pdwEffect)
Definition at line 295 of file qdnd_win.cpp.
Referenced by QOleDropTarget::DragOver(), QOleDropTarget::Drop(), and QOleDropSource::GiveFeedback().
 {
     if (pdwEffect & DROPEFFECT_LINK)
         return Qt::LinkAction;
     if (pdwEffect & DROPEFFECT_COPY)
         return Qt::CopyAction;
     if (pdwEffect & DROPEFFECT_MOVE)
         return Qt::MoveAction;
     return Qt::IgnoreAction;
 }
translateToQDragDropActions()
Qt::DropActions translateToQDragDropActions (DWORD pdwEffects)
Definition at line 283 of file qdnd_win.cpp.
Referenced by QOleDropTarget::DragOver(), QOleDropTarget::Drop(), and QOleDropTarget::sendDragEnterEvent().
 {
     Qt::DropActions actions = Qt::IgnoreAction;
     if (pdwEffects & DROPEFFECT_LINK)
         actions |= Qt::LinkAction;
     if (pdwEffects & DROPEFFECT_COPY)
         actions |= Qt::CopyAction;
     if (pdwEffects & DROPEFFECT_MOVE)
         actions |= Qt::MoveAction;
     return actions;
 }
translateToWinDragEffects()
DWORD translateToWinDragEffects (Qt::DropActions action)
Definition at line 306 of file qdnd_win.cpp.
Referenced by QOleDropTarget::DragOver(), QOleDropTarget::Drop(), and QOleDropTarget::sendDragEnterEvent().
 {
     DWORD effect = DROPEFFECT_NONE;
     if (action & Qt::LinkAction)
         effect |= DROPEFFECT_LINK;
     if (action & Qt::CopyAction)
         effect |= DROPEFFECT_COPY;
     if (action & Qt::MoveAction)
         effect |= DROPEFFECT_MOVE;
     return effect;
 }