Qt 4.8: /src/gui/widgets/qdockwidget.cpp File Reference
qdockwidget.cpp File Reference
#include "qdockwidget.h"
#include <qaction.h>
#include <qapplication.h>
#include <qdesktopwidget.h>
#include <qdrawutil.h>
#include <qevent.h>
#include <qfontmetrics.h>
#include <qmainwindow.h>
#include <qrubberband.h>
#include <qstylepainter.h>
#include <qtoolbutton.h>
#include <qdebug.h>
#include <private/qwidgetresizehandler_p.h>
#include "qdockwidget_p.h"
#include "qmainwindowlayout_p.h"
#include <private/qapplication_p.h>
#include <private/qt_mac_p.h>
#include <qmacstyle_mac.h>
#include "qdockwidget.moc"
#include "moc_qdockwidget.cpp"
Classes
class QDockWidgetTitleButton
Functions
static bool hasFeature (const QDockWidgetPrivate *priv, QDockWidget::DockWidgetFeature feature)
static bool hasFeature (const QDockWidget *dockwidget, QDockWidget::DockWidgetFeature feature)
static int perp (bool vertical, const QSize &size)
static int pick (bool vertical, const QSize &size)
QMainWindowLayout * qt_mainwindow_layout (const QMainWindow *window)
QString qt_setWindowTitle_helperHelper (const QString &, const QWidget *)
Returns a modified window title with the [*] place holder replaced according to the rules described in QWidget::setWindowTitle.
Function Documentation
hasFeature() [1/2]
static bool hasFeature (const QDockWidgetPrivate * priv, QDockWidget::DockWidgetFeature feature) inline static
Definition at line 74 of file qdockwidget.cpp.
Referenced by QSqlResult::detachFromResultSet(), QPaintEngine::drawEllipse(), QDockWidgetPrivate::endDrag(), QSqlResult::execBatch(), QDockWidget::initStyleOption(), QDockWidgetLayout::minimumTitleWidth(), QDockWidgetPrivate::mouseDoubleClickEvent(), QDockWidgetPrivate::mousePressEvent(), QSqlResult::nextResult(), QSqlResult::savePrepare(), QDockWidgetPrivate::setWindowState(), QDockWidgetPrivate::updateButtons(), and QXmlReader::~QXmlReader().
 { return (priv->features & feature) == feature; }
hasFeature() [2/2]
static bool hasFeature (const QDockWidget * dockwidget, QDockWidget::DockWidgetFeature feature) inline static
Definition at line 77 of file qdockwidget.cpp.
 { return (dockwidget->features() & feature) == feature; }
perp()
static int perp (bool vertical, const QSize & size) inline static
Definition at line 400 of file qdockwidget.cpp.
Referenced by QToolBarLayout::checkUsePopupMenu(), QToolBarLayout::expandedSize(), QDockAreaLayout::gapRect(), QDockAreaLayoutItem::hasFixedSize(), QDockAreaLayoutInfo::hasFixedSize(), QDockAreaLayoutInfo::itemRect(), QToolBarLayout::layoutActions(), QDockAreaLayoutInfo::maximumSize(), QDockAreaLayoutInfo::minimumSize(), QToolBarAreaLayoutLine::minimumSize(), QToolBarAreaLayoutInfo::minimumSize(), QDockAreaLayoutInfo::plug(), QRasterizer::rasterizeLine(), QToolBarLayout::setGeometry(), QDockAreaLayoutInfo::sizeHint(), QToolBarAreaLayoutLine::sizeHint(), QToolBarAreaLayoutInfo::sizeHint(), QTessellator::tessellateRect(), QDockWidgetLayout::titleHeight(), and QToolBarLayout::updateGeomArray().
 {
     return vertical ? size.width() : size.height();
 }
pick()
static int pick (bool vertical, const QSize & size) inline static
Definition at line 395 of file qdockwidget.cpp.
Referenced by QSplitterPrivate::addContribution(), QSplitterPrivate::doMove(), QSplitterPrivate::doResize(), QToolBarLayout::expandedSize(), QDockAreaLayoutInfo::findSeparator(), QSplitterPrivate::findWidgetJustBeforeOrJustAfter(), QDockAreaLayoutInfo::fitItems(), QToolBarAreaLayoutLine::fitLayout(), QDockAreaLayoutInfo::gapIndex(), QToolBarAreaLayoutInfo::gapIndex(), QSplitterLayoutStruct::getHandleSize(), getInt(), QSplitterPrivate::getRange(), QSplitterLayoutStruct::getWidgetSize(), QDockAreaLayoutInfo::insertGap(), QToolBarAreaLayoutInfo::insertGap(), QToolBarLayout::layoutActions(), QDockAreaLayoutInfo::maximumSize(), QDockAreaLayoutInfo::minimumSize(), QToolBarAreaLayoutLine::minimumSize(), QToolBarAreaLayoutInfo::minimumSize(), QDockWidgetLayout::minimumTitleWidth(), QToolBarAreaLayoutInfo::moveToolBar(), realMaxSize(), realMinSize(), QSplitterPrivate::recalc(), QDockAreaLayoutInfo::saveState(), QDockAreaLayoutInfo::separatorMove(), QDockAreaLayout::separatorMove(), QSplitterPrivate::setGeo(), QToolBarLayout::setGeometry(), QSplitterPrivate::setSizes_helper(), QDockAreaLayoutInfo::sizeHint(), QToolBarAreaLayoutLine::sizeHint(), QToolBarAreaLayoutInfo::sizeHint(), QSplitterPrivate::storeSizes(), QToolBarAreaLayout::unplug(), and QToolBarLayout::updateGeomArray().
 {
     return vertical ? size.height() : size.width();
 }
qt_mainwindow_layout()
QMainWindowLayout* qt_mainwindow_layout (const QMainWindow * window)
Definition at line 111 of file qmainwindow.cpp.
Referenced by QDockWidget::changeEvent(), QDockWidgetPrivate::endDrag(), QDockWidget::event(), QDockWidgetPrivate::initDrag(), QDockWidgetPrivate::isAnimating(), QDockWidgetPrivate::mouseMoveEvent(), QDockWidgetPrivate::moveEvent(), QDockWidgetPrivate::nonClientAreaMouseEvent(), QDockWidgetPrivate::setWindowState(), and QDockWidgetPrivate::startDrag().
 {
     return QMainWindowPrivate::mainWindowLayout(mainWindow);
 }
qt_setWindowTitle_helperHelper()
QString qt_setWindowTitle_helperHelper (const QString & title, const QWidget * widget)
Returns a modified window title with the [*] place holder replaced according to the rules described in QWidget::setWindowTitle.
This function assumes that "[*]" can be quoted by another "[*]", so it will replace two place holders by one and a single last one by either "*" or nothing depending on the modified flag.
Warning
This function is not part of the public interface.
Definition at line 6240 of file qwidget.cpp.
Referenced by QDockWidget::changeEvent(), and QDockWidgetPrivate::init().
 {
     Q_ASSERT(widget);
 #ifdef QT_EVAL
     extern QString qt_eval_adapt_window_title(const QString &title);
     QString cap = qt_eval_adapt_window_title(title);
 #else
     QString cap = title;
 #endif
     if (cap.isEmpty())
         return cap;
     QLatin1String placeHolder("[*]");
     int placeHolderLength = 3; // QLatin1String doesn't have length()
     int index = cap.indexOf(placeHolder);
     // here the magic begins
     while (index != -1) {
         index += placeHolderLength;
         int count = 1;
         while (cap.indexOf(placeHolder, index) == index) {
             ++count;
             index += placeHolderLength;
         }
         if (count%2) { // odd number of [*] -> replace last one
             int lastIndex = cap.lastIndexOf(placeHolder, index - 1);
             if (widget->isWindowModified()
              && widget->style()->styleHint(QStyle::SH_TitleBar_ModifyNotification, 0, widget))
                 cap.replace(lastIndex, 3, QWidget::tr("*"));
             else
                 cap.remove(lastIndex, 3);
         }
         index = cap.indexOf(placeHolder, index);
     }
     cap.replace(QLatin1String("[*][*]"), placeHolder);
     return cap;
 }