Qt 4.8: /src/gui/widgets/qdockarealayout.cpp File Reference
qdockarealayout.cpp File Reference
#include "QtGui/qapplication.h"
#include "QtGui/qwidget.h"
#include "QtGui/qtabbar.h"
#include "QtGui/qstyle.h"
#include "QtGui/qdesktopwidget.h"
#include "QtCore/qvariant.h"
#include "qdockarealayout_p.h"
#include "qdockwidget.h"
#include "qmainwindow.h"
#include "qwidgetanimator_p.h"
#include "qmainwindowlayout_p.h"
#include "qdockwidget_p.h"
#include <private/qlayoutengine_p.h>
#include <qpainter.h>
#include <qstyleoption.h>
Enumerations
enum { StateFlagVisible = 1, StateFlagFloating = 2 }
Functions
static QRect constrainedRect (QRect rect, const QRect &desktop)
static QRect dockedGeometry (QWidget *widget)
static QInternal::DockPosition dockPosHelper (const QRect &rect, const QPoint &_pos, Qt::Orientation o, bool nestingEnabled, QDockAreaLayoutInfo::TabMode tabMode)
static int grow (QLayoutStruct &ls, int delta)
static void paintSep (QPainter *p, QWidget *w, const QRect &r, Qt::Orientation o, bool mouse_over)
static int qMax (int i1, int i2, int i3)
static int qMin (int i1, int i2, int i3)
QMainWindowLayout * qt_mainwindow_layout (const QMainWindow *window)
static int realMaxSize (const QDockAreaLayoutInfo &info)
static int realMinSize (const QDockAreaLayoutInfo &info)
static int separatorMoveHelper (QVector< QLayoutStruct > &list, int index, int delta, int sep)
static int shrink (QLayoutStruct &ls, int delta)
static quintptr tabId (const QDockAreaLayoutItem &item)
static Qt::DockWidgetArea toDockWidgetArea (QInternal::DockPosition pos)
Variables
static const int zero = 0
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
StateFlagVisible
StateFlagFloating
Definition at line 66 of file qdockarealayout.cpp.
 { StateFlagVisible = 1, StateFlagFloating = 2 };
Function Documentation
constrainedRect()
static QRect constrainedRect (QRect rect, const QRect & desktop) static
Definition at line 1864 of file qdockarealayout.cpp.
Referenced by QDockAreaLayout::restoreDockWidget(), and QDockAreaLayoutInfo::restoreState().
 {
     if (desktop.isValid()) {
         rect.setWidth(qMin(rect.width(), desktop.width()));
         rect.setHeight(qMin(rect.height(), desktop.height()));
         rect.moveLeft(qMax(rect.left(), desktop.left()));
         rect.moveTop(qMax(rect.top(), desktop.top()));
         rect.moveRight(qMin(rect.right(), desktop.right()));
         rect.moveBottom(qMin(rect.bottom(), desktop.bottom()));
     }
     return rect;
 }
dockedGeometry()
static QRect dockedGeometry (QWidget * widget) static
Definition at line 1135 of file qdockarealayout.cpp.
Referenced by QDockAreaLayoutInfo::insertGap().
 {
     int titleHeight = 0;
     QDockWidgetLayout *layout
         = qobject_cast<QDockWidgetLayout*>(widget->layout());
     if(layout != 0 && layout->nativeWindowDeco())
         titleHeight = layout->titleHeight();
     QRect result = widget->geometry();
     result.adjust(0, -titleHeight, 0, 0);
     return result;
 }
dockPosHelper()
static QInternal::DockPosition dockPosHelper (const QRect & rect, const QPoint & _pos, Qt::Orientation o, bool nestingEnabled, QDockAreaLayoutInfo::TabMode tabMode) static
Definition at line 643 of file qdockarealayout.cpp.
Referenced by QDockAreaLayoutInfo::gapIndex().
 {
     if (tabMode == QDockAreaLayoutInfo::ForceTabs)
         return QInternal::DockCount;
     QPoint pos = _pos - rect.topLeft();
     int x = pos.x();
     int y = pos.y();
     int w = rect.width();
     int h = rect.height();
     if (tabMode != QDockAreaLayoutInfo::NoTabs) {
         // is it in the center?
         if (nestingEnabled) {
         /*             2/3
                 +--------------+
                 |              |
                 |   CCCCCCCC   |
            2/3  |   CCCCCCCC   |
                 |   CCCCCCCC   |
                 |              |
                 +--------------+     */
             QRect center(w/6, h/6, 2*w/3, 2*h/3);
             if (center.contains(pos))
                 return QInternal::DockCount;
         } else if (o == Qt::Horizontal) {
         /*             2/3
                 +--------------+
                 |   CCCCCCCC   |
                 |   CCCCCCCC   |
                 |   CCCCCCCC   |
                 |   CCCCCCCC   |
                 |   CCCCCCCC   |
                 +--------------+     */
             if (x > w/6 && x < w*5/6)
                 return QInternal::DockCount;
         } else {
         /*
                 +--------------+
                 |              |
            2/3  |CCCCCCCCCCCCCC|
                 |CCCCCCCCCCCCCC|
                 |              |
                 +--------------+     */
             if (y > h/6 && y < 5*h/6)
                 return QInternal::DockCount;
         }
     }
     // not in the center. which edge?
     if (nestingEnabled) {
         if (o == Qt::Horizontal) {
     /*       1/3  1/3 1/3
             +------------+     (we've already ruled out the center)
             |LLLLTTTTRRRR|
             |LLLLTTTTRRRR|
             |LLLLBBBBRRRR|
             |LLLLBBBBRRRR|
             +------------+    */
             if (x < w/3)
                 return QInternal::LeftDock;
             if (x > 2*w/3)
                 return QInternal::RightDock;
             if (y < h/2)
                 return QInternal::TopDock;
             return QInternal::BottomDock;
         } else {
     /*      +------------+     (we've already ruled out the center)
         1/3 |TTTTTTTTTTTT|
             |LLLLLLRRRRRR|
         1/3 |LLLLLLRRRRRR|
         1/3 |BBBBBBBBBBBB|
             +------------+    */
             if (y < h/3)
                 return QInternal::TopDock;
             if (y > 2*h/3)
                 return QInternal::BottomDock;
             if (x < w/2)
                 return QInternal::LeftDock;
             return QInternal::RightDock;
         }
     } else {
         if (o == Qt::Horizontal) {
             return x < w/2
                     ? QInternal::LeftDock
                     : QInternal::RightDock;
         } else {
             return y < h/2
                     ? QInternal::TopDock
                     : QInternal::BottomDock;
         }
     }
 }
grow()
static int grow (QLayoutStruct & ls, int delta) inline static
Definition at line 845 of file qdockarealayout.cpp.
Referenced by separatorMoveHelper().
 {
     if (ls.empty)
         return 0;
     int old_size = ls.size;
     ls.size = qMin(ls.size + delta, ls.maximumSize);
     return ls.size - old_size;
 }
paintSep()
static void paintSep (QPainter * p, QWidget * w, const QRect & r, Qt::Orientation o, bool mouse_over) static
Definition at line 1573 of file qdockarealayout.cpp.
Referenced by QDockAreaLayoutInfo::paintSeparators(), and QDockAreaLayout::paintSeparators().
 {
     QStyleOption opt(0);
     opt.state = QStyle::State_None;
     if (w->isEnabled())
         opt.state |= QStyle::State_Enabled;
     if (o != Qt::Horizontal)
         opt.state |= QStyle::State_Horizontal;
     if (mouse_over)
         opt.state |= QStyle::State_MouseOver;
     opt.rect = r;
     opt.palette = w->palette();
     w->style()->drawPrimitive(QStyle::PE_IndicatorDockWidgetResizeHandle, &opt, p, w);
 }
qMax()
static int qMax (int i1, int i2, int i3) inline static
Definition at line 2581 of file qdockarealayout.cpp.
Referenced by constrainedRect(), QDockAreaLayoutInfo::fitItems(), QDockAreaLayout::getGrid(), QDockAreaLayoutInfo::maximumSize(), QDockAreaLayoutInfo::minimumSize(), QDockAreaLayout::minimumSize(), shrink(), QDockAreaLayoutInfo::sizeHint(), and QDockAreaLayout::sizeHint().
 { return qMax(i1, qMax(i2, i3)); }
qMin()
static int qMin (int i1, int i2, int i3) inline static
Definition at line 2580 of file qdockarealayout.cpp.
Referenced by constrainedRect(), grow(), QDockAreaLayoutInfo::maximumSize(), and QDockAreaLayoutInfo::sizeHint().
 { return qMin(i1, qMin(i2, i3)); }
qt_mainwindow_layout()
QMainWindowLayout* qt_mainwindow_layout (const QMainWindow * window)
Definition at line 111 of file qmainwindow.cpp.
Referenced by QDockAreaLayout::apply(), QDockAreaLayoutInfo::mainWindowLayout(), and QDockAreaLayout::updateSeparatorWidgets().
 {
     return QMainWindowPrivate::mainWindowLayout(mainWindow);
 }
realMaxSize()
static int realMaxSize (const QDockAreaLayoutInfo & info) static
Definition at line 508 of file qdockarealayout.cpp.
Referenced by QDockAreaLayoutInfo::fitItems().
 {
     int result = 0;
     bool first = true;
     for (int i = 0; i < info.item_list.size(); ++i) {
         const QDockAreaLayoutItem &item = info.item_list.at(i);
         if (item.skip())
             continue;
         int max = 0;
         if ((item.flags & QDockAreaLayoutItem::KeepSize) && item.size != -1)
             max = item.size;
         else
             max = pick(info.o, item.maximumSize());
         if (!first)
             result += *info.sep;
         result += max;
         if (result >= QWIDGETSIZE_MAX)
             return QWIDGETSIZE_MAX;
         first = false;
     }
     return result;
 }
realMinSize()
static int realMinSize (const QDockAreaLayoutInfo & info) static
Definition at line 483 of file qdockarealayout.cpp.
Referenced by QDockAreaLayoutInfo::fitItems().
 {
     int result = 0;
     bool first = true;
     for (int i = 0; i < info.item_list.size(); ++i) {
         const QDockAreaLayoutItem &item = info.item_list.at(i);
         if (item.skip())
             continue;
         int min = 0;
         if ((item.flags & QDockAreaLayoutItem::KeepSize) && item.size != -1)
             min = item.size;
         else
             min = pick(info.o, item.minimumSize());
         if (!first)
             result += *info.sep;
         result += min;
         first = false;
     }
     return result;
 }
separatorMoveHelper()
static int separatorMoveHelper (QVector< QLayoutStruct > & list, int index, int delta, int sep) static
Definition at line 854 of file qdockarealayout.cpp.
Referenced by QDockAreaLayoutInfo::separatorMove(), and QDockAreaLayout::separatorMove().
 {
     // adjust sizes
     int pos = -1;
     for (int i = 0; i < list.size(); ++i) {
         const QLayoutStruct &ls = list.at(i);
         if (!ls.empty) {
             pos = ls.pos;
             break;
         }
     }
     if (pos == -1)
         return 0;
     if (delta > 0) {
         int growlimit = 0;
         for (int i = 0; i<=index; ++i) {
             const QLayoutStruct &ls = list.at(i);
             if (ls.empty)
                 continue;
             if (ls.maximumSize == QLAYOUTSIZE_MAX) {
                 growlimit = QLAYOUTSIZE_MAX;
                 break;
             }
             growlimit += ls.maximumSize - ls.size;
         }
         if (delta > growlimit)
             delta = growlimit;
         int d = 0;
         for (int i = index + 1; d < delta && i < list.count(); ++i)
             d += shrink(list[i], delta - d);
         delta = d;
         d = 0;
         for (int i = index; d < delta && i >= 0; --i)
             d += grow(list[i], delta - d);
     } else if (delta < 0) {
         int growlimit = 0;
         for (int i = index + 1; i < list.count(); ++i) {
             const QLayoutStruct &ls = list.at(i);
             if (ls.empty)
                 continue;
             if (ls.maximumSize == QLAYOUTSIZE_MAX) {
                 growlimit = QLAYOUTSIZE_MAX;
                 break;
             }
             growlimit += ls.maximumSize - ls.size;
         }
         if (-delta > growlimit)
             delta = -growlimit;
         int d = 0;
         for (int i = index; d < -delta && i >= 0; --i)
             d += shrink(list[i], -delta - d);
         delta = -d;
         d = 0;
         for (int i = index + 1; d < -delta && i < list.count(); ++i)
             d += grow(list[i], -delta - d);
     }
     // adjust positions
     bool first = true;
     for (int i = 0; i < list.size(); ++i) {
         QLayoutStruct &ls = list[i];
         if (ls.empty) {
             ls.pos = pos + (first ? 0 : sep);
             continue;
         }
         if (!first)
             pos += sep;
         ls.pos = pos;
         pos += ls.size;
         first = false;
     }
     return delta;
 }
shrink()
static int shrink (QLayoutStruct & ls, int delta) inline static
Definition at line 836 of file qdockarealayout.cpp.
Referenced by separatorMoveHelper().
 {
     if (ls.empty)
         return 0;
     int old_size = ls.size;
     ls.size = qMax(ls.size - delta, ls.minimumSize);
     return old_size - ls.size;
 }
tabId()
static quintptr tabId (const QDockAreaLayoutItem & item) static
Definition at line 218 of file qdockarealayout.cpp.
Referenced by QDockAreaLayout::addDockWidget(), QDockAreaLayoutInfo::itemRect(), QDockAreaLayoutInfo::restoreState(), QDockAreaLayoutInfo::saveState(), and QDockAreaLayoutInfo::updateTabBar().
 {
     if (item.widgetItem == 0)
         return 0;
     return reinterpret_cast<quintptr>(item.widgetItem->widget());
 }
toDockWidgetArea()
static Qt::DockWidgetArea toDockWidgetArea (QInternal::DockPosition pos) static
Definition at line 1852 of file qdockarealayout.cpp.
Referenced by QDockAreaLayoutInfo::restoreState().
 {
     switch (pos) {
         case QInternal::LeftDock:   return Qt::LeftDockWidgetArea;
         case QInternal::RightDock:  return Qt::RightDockWidgetArea;
         case QInternal::TopDock:    return Qt::TopDockWidgetArea;
         case QInternal::BottomDock: return Qt::BottomDockWidgetArea;
         default: break;
     }
     return Qt::NoDockWidgetArea;
 }
Variable Documentation
zero
const int zero = 0 static
Definition at line 226 of file qdockarealayout.cpp.
Referenced by QLocalePrivate::digitToCLocale(), QLocalePrivate::doubleToString(), QTabWidget::heightForWidth(), QCss::ValueExtractor::lengthValues(), QLocalePrivate::longLongToString(), QDateTimeParser::parseFormat(), qt_bitmapToRegion(), QAccessibleHeader::rect(), QAccessibleTable2HeaderCell::rect(), unquote(), and QLocalePrivate::unsLongLongToString().