Qt 4.8: /src/xml/dom/qdom.cpp File Reference
qdom.cpp File Reference
#include <qplatformdefs.h>
#include <qdom.h>
#include "private/qxmlutils_p.h"
#include <qatomic.h>
#include <qbuffer.h>
#include <qhash.h>
#include <qiodevice.h>
#include <qlist.h>
#include <qregexp.h>
#include <qtextcodec.h>
#include <qtextstream.h>
#include <qxml.h>
#include <qvariant.h>
#include <qmap.h>
#include <qshareddata.h>
#include <qdebug.h>
#include <stdio.h>
Classes
class QDomAttrPrivate
class QDomCDATASectionPrivate
class QDomCharacterDataPrivate
class QDomCommentPrivate
class QDomDocumentFragmentPrivate
class QDomDocumentPrivate
class QDomDocumentTypePrivate
class QDomElementPrivate
class QDomEntityPrivate
class QDomEntityReferencePrivate
class QDomHandler
class QDomImplementationPrivate
class QDomNamedNodeMapPrivate
class QDomNodeListPrivate
class QDomNodePrivate
class QDomNotationPrivate
class QDomProcessingInstructionPrivate
class QDomTextPrivate
Macros
#define IMPL ((QDomNodePrivate*)impl)
#define IMPL ((QDomNamedNodeMapPrivate*)impl)
#define IMPL ((QDomDocumentTypePrivate*)impl)
#define IMPL ((QDomCharacterDataPrivate*)impl)
#define IMPL ((QDomAttrPrivate*)impl)
#define IMPL ((QDomElementPrivate*)impl)
#define IMPL ((QDomTextPrivate*)impl)
#define IMPL ((QDomNotationPrivate*)impl)
#define IMPL ((QDomEntityPrivate*)impl)
#define IMPL ((QDomDocumentPrivate*)impl)
Functions
static QByteArray encodeEntity (const QByteArray &str)
static QString encodeText (const QString &str, QTextStream &s, const bool encodeQuotes=true, const bool performAVN=false, const bool encodeEOLs=false)
static QString fixedCDataSection (const QString &data, bool *ok)
static QString fixedCharData (const QString &data, bool *ok)
static QString fixedComment (const QString &data, bool *ok)
static QString fixedPIData (const QString &data, bool *ok)
static QString fixedPubidLiteral (const QString &data, bool *ok)
static QString fixedSystemLiteral (const QString &data, bool *ok)
static QString fixedXmlName (const QString &_name, bool *ok, bool namespaces=false)
static void initializeReader (QXmlSimpleReader &reader, bool namespaceProcessing)
static void qNormalizeNode (QDomNodePrivate *n)
static void qt_split_namespace (QString &prefix, QString &name, const QString &qName, bool hasURI)
static QString quotedValue (const QString &data)
Variables
bool qt_xml_skipped_entity_in_content
Macro Definition Documentation
IMPL [1/10]
#define IMPL ((QDomNodePrivate*)impl)
Definition at line 6666 of file qdom.cpp.
Referenced by QDomNode::appendChild(), QDomCharacterData::appendData(), QDomNode::cloneNode(), QDomNamedNodeMap::contains(), QDomDocument::createAttribute(), QDomDocument::createAttributeNS(), QDomDocument::createCDATASection(), QDomDocument::createComment(), QDomDocument::createDocumentFragment(), QDomDocument::createElement(), QDomDocument::createElementNS(), QDomDocument::createEntityReference(), QDomDocument::createProcessingInstruction(), QDomDocument::createTextNode(), QDomCharacterData::deleteData(), QDomDocument::doctype(), QDomDocument::documentElement(), QDomNode::firstChild(), QDomNode::hasChildNodes(), QDomDocument::implementation(), QDomDocument::importNode(), QDomNode::insertAfter(), QDomNode::insertBefore(), QDomCharacterData::insertData(), QDomNamedNodeMap::item(), QDomNode::lastChild(), QDomNamedNodeMap::length(), QDomCharacterData::length(), QDomNode::localName(), QDomNamedNodeMap::namedItem(), QDomNamedNodeMap::namedItemNS(), QDomNode::namespaceURI(), QDomNode::nextSibling(), QDomNode::nodeName(), QDomNode::nodeType(), QDomNode::nodeValue(), QDomNode::normalize(), QDomNode::ownerDocument(), QDomNode::parentNode(), QDomNode::prefix(), QDomNode::previousSibling(), QDomNode::removeChild(), QDomNamedNodeMap::removeNamedItem(), QDomNamedNodeMap::removeNamedItemNS(), QDomNode::replaceChild(), QDomCharacterData::replaceData(), QDomNode::save(), QDomDocument::setContent(), QDomNamedNodeMap::setNamedItem(), QDomNamedNodeMap::setNamedItemNS(), QDomNode::setNodeValue(), QDomNode::setPrefix(), QDomAttr::setValue(), QDomAttr::specified(), and QDomCharacterData::substringData().
IMPL [2/10]
#define IMPL ((QDomNamedNodeMapPrivate*)impl)
Definition at line 6666 of file qdom.cpp.
IMPL [3/10]
#define IMPL ((QDomDocumentTypePrivate*)impl)
Definition at line 6666 of file qdom.cpp.
IMPL [4/10]
#define IMPL ((QDomCharacterDataPrivate*)impl)
Definition at line 6666 of file qdom.cpp.
IMPL [5/10]
#define IMPL ((QDomAttrPrivate*)impl)
Definition at line 6666 of file qdom.cpp.
IMPL [6/10]
#define IMPL ((QDomElementPrivate*)impl)
Definition at line 6666 of file qdom.cpp.
IMPL [7/10]
#define IMPL ((QDomTextPrivate*)impl)
Definition at line 6666 of file qdom.cpp.
IMPL [8/10]
#define IMPL ((QDomNotationPrivate*)impl)
Definition at line 6666 of file qdom.cpp.
IMPL [9/10]
#define IMPL ((QDomEntityPrivate*)impl)
Definition at line 6666 of file qdom.cpp.
IMPL [10/10]
#define IMPL ((QDomDocumentPrivate*)impl)
Definition at line 6666 of file qdom.cpp.
Function Documentation
encodeEntity()
static QByteArray encodeEntity (const QByteArray & str) static
Definition at line 5834 of file qdom.cpp.
 {
     QByteArray tmp(str);
     uint len = tmp.size();
     uint i = 0;
     const char* d = tmp.data();
     while (i < len) {
         if (d[i] == '%'){
             tmp.replace(i, 1, "&#60;");
             d = tmp;
             len += 4;
             i += 5;
         }
         else if (d[i] == '"') {
             tmp.replace(i, 1, "&#34;");
             d = tmp;
             len += 4;
             i += 5;
         } else if (d[i] == '&' && i + 1 < len && d[i+1] == '#') {
             // Don't encode &lt; or &quot; or &custom;.
             // Only encode character references
             tmp.replace(i, 1, "&#38;");
             d = tmp;
             len += 4;
             i += 5;
         } else {
             ++i;
         }
     }
     return tmp;
 }
encodeText()
static QString encodeText (const QString & str, QTextStream & s, const bool encodeQuotes = true, const bool performAVN = false, const bool encodeEOLs = false) static
Definition at line 4245 of file qdom.cpp.
Referenced by QDomAttrPrivate::save(), and QDomElementPrivate::save().
 {
 #ifdef QT_NO_TEXTCODEC
     Q_UNUSED(s);
 #else
     const QTextCodec *const codec = s.codec();
     Q_ASSERT(codec);
 #endif
     QString retval(str);
     int len = retval.length();
     int i = 0;
     while (i < len) {
         const QChar ati(retval.at(i));
         if (ati == QLatin1Char('<')) {
             retval.replace(i, 1, QLatin1String("&lt;"));
             len += 3;
             i += 4;
         } else if (encodeQuotes && (ati == QLatin1Char('"'))) {
             retval.replace(i, 1, QLatin1String("&quot;"));
             len += 5;
             i += 6;
         } else if (ati == QLatin1Char('&')) {
             retval.replace(i, 1, QLatin1String("&amp;"));
             len += 4;
             i += 5;
         } else if (ati == QLatin1Char('>') && i >= 2 && retval[i - 1] == QLatin1Char(']') && retval[i - 2] == QLatin1Char(']')) {
             retval.replace(i, 1, QLatin1String("&gt;"));
             len += 3;
             i += 4;
         } else if (performAVN &&
                    (ati == QChar(0xA) ||
                     ati == QChar(0xD) ||
                     ati == QChar(0x9))) {
             const QString replacement(QLatin1String("&#x") + QString::number(ati.unicode(), 16) + QLatin1Char(';'));
             retval.replace(i, 1, replacement);
             i += replacement.length();
             len += replacement.length() - 1;
         } else if (encodeEOLs && ati == QChar(0xD)) {
             retval.replace(i, 1, QLatin1String("&#xd;")); // Replace a single 0xD with a ref for 0xD
             len += 4;
             i += 5;
         } else {
 #ifndef QT_NO_TEXTCODEC
             if(codec->canEncode(ati))
                 ++i;
             else
 #endif
             {
                 // We have to use a character reference to get it through.
                 const ushort codepoint(ati.unicode());
                 const QString replacement(QLatin1String("&#x") + QString::number(codepoint, 16) + QLatin1Char(';'));
                 retval.replace(i, 1, replacement);
                 i += replacement.length();
                 len += replacement.length() - 1;
             }
         }
     }
     return retval;
 }
fixedCDataSection()
static QString fixedCDataSection (const QString & data, bool * ok) static
Definition at line 753 of file qdom.cpp.
Referenced by QDomDocumentPrivate::createCDATASection().
 {
     if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::AcceptInvalidChars) {
         *ok = true;
         return data;
     }
     QString fixedData = fixedCharData(data, ok);
     if (!*ok)
         return QString();
     for (;;) {
         int idx = fixedData.indexOf(QLatin1String("]]>"));
         if (idx == -1)
             break;
         if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::ReturnNullNode) {
             *ok = false;
             return QString();
         }
         fixedData.remove(idx, 3);
     }
     *ok = true;
     return fixedData;
 }
fixedCharData()
static QString fixedCharData (const QString & data, bool * ok) static
Definition at line 699 of file qdom.cpp.
Referenced by QDomDocumentPrivate::createTextNode(), fixedCDataSection(), fixedComment(), and fixedPIData().
 {
     if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::AcceptInvalidChars) {
         *ok = true;
         return data;
     }
     QString result;
     for (int i = 0; i < data.size(); ++i) {
         QChar c = data.at(i);
         if (QXmlUtils::isChar(c)) {
             result.append(c);
         } else if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::ReturnNullNode) {
             *ok = false;
             return QString();
         }
     }
     *ok = true;
     return result;
 }
fixedComment()
static QString fixedComment (const QString & data, bool * ok) static
Definition at line 724 of file qdom.cpp.
Referenced by QDomDocumentPrivate::createComment().
 {
     if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::AcceptInvalidChars) {
         *ok = true;
         return data;
     }
     QString fixedData = fixedCharData(data, ok);
     if (!*ok)
         return QString();
     for (;;) {
         int idx = fixedData.indexOf(QLatin1String("--"));
         if (idx == -1)
             break;
         if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::ReturnNullNode) {
             *ok = false;
             return QString();
         }
         fixedData.remove(idx, 2);
     }
     *ok = true;
     return fixedData;
 }
fixedPIData()
static QString fixedPIData (const QString & data, bool * ok) static
Definition at line 781 of file qdom.cpp.
Referenced by QDomDocumentPrivate::createProcessingInstruction().
 {
     if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::AcceptInvalidChars) {
         *ok = true;
         return data;
     }
     QString fixedData = fixedCharData(data, ok);
     if (!*ok)
         return QString();
     for (;;) {
         int idx = fixedData.indexOf(QLatin1String("?>"));
         if (idx == -1)
             break;
         if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::ReturnNullNode) {
             *ok = false;
             return QString();
         }
         fixedData.remove(idx, 2);
     }
     *ok = true;
     return fixedData;
 }
fixedPubidLiteral()
static QString fixedPubidLiteral (const QString & data, bool * ok) static
Definition at line 810 of file qdom.cpp.
Referenced by QDomImplementation::createDocumentType().
 {
     if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::AcceptInvalidChars) {
         *ok = true;
         return data;
     }
     QString result;
     if(QXmlUtils::isPublicID(data))
         result = data;
     else if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::ReturnNullNode) {
         *ok = false;
         return QString();
     }
     if (result.indexOf(QLatin1Char('\'')) != -1
         && result.indexOf(QLatin1Char('"')) != -1) {
         if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::ReturnNullNode) {
             *ok = false;
             return QString();
         } else {
             result.remove(QLatin1Char('\''));
         }
     }
     *ok = true;
     return result;
 }
fixedSystemLiteral()
static QString fixedSystemLiteral (const QString & data, bool * ok) static
Definition at line 843 of file qdom.cpp.
Referenced by QDomImplementation::createDocumentType().
 {
     if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::AcceptInvalidChars) {
         *ok = true;
         return data;
     }
     QString result = data;
     if (result.indexOf(QLatin1Char('\'')) != -1
         && result.indexOf(QLatin1Char('"')) != -1) {
         if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::ReturnNullNode) {
             *ok = false;
             return QString();
         } else {
             result.remove(QLatin1Char('\''));
         }
     }
     *ok = true;
     return result;
 }
fixedXmlName()
static QString fixedXmlName (const QString & _name, bool * ok, bool namespaces = false) static
Definition at line 645 of file qdom.cpp.
Referenced by QDomDocumentPrivate::createAttribute(), QDomDocumentPrivate::createAttributeNS(), QDomImplementation::createDocumentType(), QDomDocumentPrivate::createElement(), QDomDocumentPrivate::createElementNS(), QDomDocumentPrivate::createEntityReference(), and QDomDocumentPrivate::createProcessingInstruction().
 {
     QString name, prefix;
     if (namespaces)
         qt_split_namespace(prefix, name, _name, true);
     else
         name = _name;
     if (name.isEmpty()) {
         *ok = false;
         return QString();
     }
     if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::AcceptInvalidChars) {
         *ok = true;
         return _name;
     }
     QString result;
     bool firstChar = true;
     for (int i = 0; i < name.size(); ++i) {
         QChar c = name.at(i);
         if (firstChar) {
             if (QXmlUtils::isLetter(c) || c.unicode() == '_' || c.unicode() == ':') {
                 result.append(c);
                 firstChar = false;
             } else if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::ReturnNullNode) {
                 *ok = false;
                 return QString();
             }
         } else {
             if (QXmlUtils::isNameChar(c))
                 result.append(c);
             else if (QDomImplementationPrivate::invalidDataPolicy == QDomImplementation::ReturnNullNode) {
                 *ok = false;
                 return QString();
             }
         }
     }
     if (result.isEmpty()) {
         *ok = false;
         return QString();
     }
     *ok = true;
     if (namespaces && !prefix.isEmpty())
         return prefix + QLatin1Char(':') + result;
     return result;
 }
initializeReader()
static void initializeReader (QXmlSimpleReader & reader, bool namespaceProcessing) static
Definition at line 6360 of file qdom.cpp.
Referenced by QDomDocument::setContent(), and QDomDocumentPrivate::setContent().
 {
     reader.setFeature(QLatin1String("http://xml.org/sax/features/namespaces"), namespaceProcessing);
     reader.setFeature(QLatin1String("http://xml.org/sax/features/namespace-prefixes"), !namespaceProcessing);
     reader.setFeature(QLatin1String("http://trolltech.com/xml/features/report-whitespace-only-CharData"), false); // Shouldn't change in Qt 4
 }
qNormalizeNode()
static void qNormalizeNode (QDomNodePrivate * n) static
Definition at line 1913 of file qdom.cpp.
Referenced by QDomNodePrivate::normalize().
 {
     QDomNodePrivate* p = n->first;
     QDomTextPrivate* t = 0;
     while (p) {
         if (p->isText()) {
             if (t) {
                 QDomNodePrivate* tmp = p->next;
                 t->appendData(p->nodeValue());
                 n->removeChild(p);
                 p = tmp;
             } else {
                 t = (QDomTextPrivate*)p;
                 p = p->next;
             }
         } else {
             p = p->next;
             t = 0;
         }
     }
 }
qt_split_namespace()
static void qt_split_namespace (QString & prefix, QString & name, const QString & qName, bool hasURI) static
Definition at line 104 of file qdom.cpp.
Referenced by fixedXmlName(), QDomAttrPrivate::QDomAttrPrivate(), QDomElementPrivate::QDomElementPrivate(), and QDomElementPrivate::setAttributeNS().
 {
     int i = qName.indexOf(QLatin1Char(':'));
     if (i == -1) {
         if (hasURI)
             prefix = QLatin1String("");
         else
             prefix.clear();
         name = qName;
     } else {
         prefix = qName.left(i);
         name = qName.mid(i + 1);
     }
 }
quotedValue()
static QString quotedValue (const QString & data) static
Definition at line 3656 of file qdom.cpp.
Referenced by QTestXunitStreamer::formatAttributes(), QDomDocumentTypePrivate::save(), QDomNotationPrivate::save(), and QDomEntityPrivate::save().
 {
     QChar quote = data.indexOf(QLatin1Char('\'')) == -1
                     ? QLatin1Char('\'')
                     : QLatin1Char('"');
     return quote + data + quote;
 }
Variable Documentation
qt_xml_skipped_entity_in_content
bool qt_xml_skipped_entity_in_content
Definition at line 104 of file qxml.cpp.
Referenced by QXmlSimpleReader::parse(), QDomHandler::processingInstruction(), and QXmlSimpleReaderPrivate::processReference().