Qt 4.8: /src/gui/painting/qdrawhelper_p.h File Reference
qdrawhelper_p.h File Reference
#include "QtCore/qglobal.h"
#include "QtGui/qcolor.h"
#include "QtGui/qpainter.h"
#include "QtGui/qimage.h"
#include "private/qrasterdefs_p.h"
#include <private/qsimd_p.h>
#include <private/qmath_p.h>
#include "QtGui/qscreen_qws.h"
Classes
struct DrawHelper
struct LinearGradientValues
struct Operator
class qabgr8888
class qargb4444
class qargb6666
class qargb8555
class qargb8565
class qbgr555
class qbgr565
struct QConicalGradientData
struct QGradientData
struct QLinearGradientData
class QRadialFetchSimd< Simd >
struct QRadialGradientData
class qrgb444
class qrgb555
class qrgb565
class qrgb666
class qrgb888
struct QSolidData
struct QSpanData
struct QTextureData
class quint18
class quint24
class quint32p
struct RadialGradientValues
Macros
#define AMIX(mask) quint32(qMin(((qint64(s)&mask) + (qint64(d)&mask)), qint64(mask)))
#define ARGB_COMBINE_ALPHA(argb, alpha) ((((argb >> 24) * alpha) >> 8) << 24) | (argb & 0x00ffffff)
#define FETCH_RADIAL_LOOP(FETCH_RADIAL_LOOP_CLAMP)
#define FETCH_RADIAL_LOOP_CLAMP_PAD index_vec.v = Simd::v_toInt(Simd::v_min(v_max, Simd::v_max(v_min, v_index)));
#define FETCH_RADIAL_LOOP_CLAMP_REFLECT
#define FETCH_RADIAL_LOOP_CLAMP_REPEAT index_vec.v = Simd::v_and(v_repeat_mask, Simd::v_toInt(v_index));
#define FETCH_RADIAL_LOOP_EPILOGUE
#define FETCH_RADIAL_LOOP_PROLOGUE
#define GRADIENT_STOPTABLE_SIZE 256
#define GRADIENT_STOPTABLE_SIZE_SHIFT 8
#define INV_PREMUL(p)
#define MIX(mask) (qMin(((quint32(s)&mask) + (quint32(d)&mask)), quint32(mask)))
#define Q_STATIC_INLINE_FUNCTION static inline
#define Q_STATIC_TEMPLATE_FUNCTION static
#define Q_STATIC_TEMPLATE_SPECIALIZATION
#define QT_FT_BEGIN_HEADER
#define QT_FT_END_HEADER
#define QT_MEMCPY_REV_UINT(dest, src, length)
#define QT_MEMCPY_USHORT(dest, src, length)
#define QT_MEMFILL_UINT(dest, length, color) qt_memfill<quint32>(dest, color, length);
#define QT_MEMFILL_USHORT(dest, length, color) qt_memfill<quint16>(dest, color, length);
#define QT_RECTCONVERT_TRIVIAL_IMPL(T)
#define QT_TRIVIAL_MEMCONVERT_IMPL(T)
Typedefs
typedef void(* AlphamapBlitFunc) (QRasterBuffer *rasterBuffer, int x, int y, quint32 color, const uchar *bitmap, int mapWidth, int mapHeight, int mapStride, const QClipData *clip)
typedef void(* AlphaRGBBlitFunc) (QRasterBuffer *rasterBuffer, int x, int y, quint32 color, const uint *rgbmask, int mapWidth, int mapHeight, int mapStride, const QClipData *clip)
typedef void(* BitmapBlitFunc) (QRasterBuffer *rasterBuffer, int x, int y, quint32 color, const uchar *bitmap, int mapWidth, int mapHeight, int mapStride)
typedef void(QT_FASTCALL * CompositionFunction) (uint *dest, const uint *src, int length, uint const_alpha)
typedef void(QT_FASTCALL * CompositionFunctionSolid) (uint *dest, int length, uint color, uint const_alpha)
typedef uint *QT_FASTCALL * DestFetchProc(uint *buffer, QRasterBuffer *rasterBuffer, int x, int y, int length)
typedef void(QT_FASTCALL * DestStoreProc) (QRasterBuffer *rasterBuffer, int x, int y, const uint *buffer, int length)
typedef void(* MemRotateFunc) (const uchar *srcPixels, int w, int h, int sbpl, uchar *destPixels, int dbpl)
typedef QT_FT_SpanFunc ProcessSpans
typedef QT_FT_Span QSpan
typedef void(* RectFillFunc) (QRasterBuffer *rasterBuffer, int x, int y, int width, int height, quint32 color)
typedef const uint *(QT_FASTCALL * SourceFetchProc) (uint *buffer, const Operator *o, const QSpanData *data, int y, int x, int length)
typedef void(* SrcOverBlendFunc) (uchar *destPixels, int dbpl, const uchar *src, int spbl, int w, int h, int const_alpha)
typedef void(* SrcOverScaleFunc) (uchar *destPixels, int dbpl, const uchar *src, int spbl, int srch, const QRectF &targetRect, const QRectF &sourceRect, const QRect &clipRect, int const_alpha)
typedef void(* SrcOverTransformFunc) (uchar *destPixels, int dbpl, const uchar *src, int spbl, const QRectF &targetRect, const QRectF &sourceRect, const QRect &clipRect, const QTransform &targetRectTransform, int const_alpha)
Functions
Q_STATIC_INLINE_FUNCTION uint BYTE_MUL (uint x, uint a)
Q_STATIC_INLINE_FUNCTION uint BYTE_MUL_RGB16 (uint x, uint a)
Q_STATIC_INLINE_FUNCTION uint BYTE_MUL_RGB16_32 (uint x, uint a)
void QT_FASTCALL comp_func_Clear (uint *dest, const uint *, int length, uint const_alpha)
void QT_FASTCALL comp_func_ColorBurn (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_ColorDodge (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_Darken (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_Destination (uint *, const uint *, int, uint)
void QT_FASTCALL comp_func_DestinationAtop (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_DestinationIn (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_DestinationOut (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_DestinationOver (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_Difference (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_Exclusion (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_HardLight (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_Lighten (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_Multiply (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_Overlay (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_Plus (uint *dest, const uint *src, int length, uint const_alpha)
int comp_func_Plus_one_pixel (uint d, const uint s)
int comp_func_Plus_one_pixel_const_alpha (uint d, const uint s, const uint const_alpha, const uint one_minus_const_alpha)
void QT_FASTCALL comp_func_Screen (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_SoftLight (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_solid_Clear (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_ColorBurn (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_ColorDodge (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_Darken (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_Destination (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_DestinationAtop (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_DestinationIn (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_DestinationOut (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_DestinationOver (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_Difference (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_Exclusion (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_HardLight (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_Lighten (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_Multiply (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_Overlay (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_Plus (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_Screen (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_SoftLight (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_Source (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_SourceAtop (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_SourceIn (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_SourceOut (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_SourceOver (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_solid_XOR (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL comp_func_Source (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_SourceAtop (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_SourceIn (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_SourceOut (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_SourceOver (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL comp_func_XOR (uint *dest, const uint *src, int length, uint const_alpha)
Q_STATIC_INLINE_FUNCTION uint INTERPOLATE_PIXEL_255 (uint x, uint a, uint y, uint b)
Q_STATIC_INLINE_FUNCTION uint INTERPOLATE_PIXEL_256 (uint x, uint a, uint y, uint b)
Q_STATIC_INLINE_FUNCTION uint PREMUL (uint x)
void qBlendTexture (int count, const QSpan *spans, void *userData)
void qBlendTextureCallback (int count, const QSpan *spans, void *userData)
int qBlue565 (quint16 rgb)
QRgb qConvertRgb16To32 (uint c)
ushort qConvertRgb32To16 (uint c)
quint32 qConvertRgb32To16x2 (quint64 c)
int qGreen565 (quint16 rgb)
void qInitDrawhelperAsm ()
static qreal qRadialDeterminant (qreal a, qreal b, qreal c)
int qRed565 (quint16 rgb)
template<class DST , class SRC >
DST qt_colorConvert (SRC color, DST dummy)
template<>
quint32 qt_colorConvert (quint16 color, quint32 dummy)
template<>
quint16 qt_colorConvert (quint32 color, quint16 dummy)
template<>
qrgb888 qt_colorConvert (quint32 color, qrgb888 dummy)
template<>
quint32 qt_colorConvert (qrgb888 color, quint32 dummy)
template<>
quint24 qt_colorConvert (quint32 color, quint24 dummy)
template<>
quint18 qt_colorConvert (quint32 color, quint18 dummy)
Q_STATIC_INLINE_FUNCTION int qt_div_255 (int x)
template<class RadialFetchFunc >
const uint *QT_FASTCALL qt_fetch_radial_gradient_template (uint *buffer, const Operator *op, const QSpanData *data, int y, int x, int length)
static uint qt_gradient_clamp (const QGradientData *data, int ipos)
static uint qt_gradient_pixel (const QGradientData *data, qreal pos)
template<class DST , class SRC >
void qt_memconvert (DST *dest, const SRC *src, int count)
template<>
void qt_memconvert (qrgb666 *dest, const quint32 *src, int count)
template<class T >
void qt_memfill (T *dest, T value, int count)
template<>
void qt_memfill (quint32 *dest, quint32 color, int count)
template<>
void qt_memfill (quint16 *dest, quint16 color, int count)
template<>
void qt_memfill (quint8 *dest, quint8 color, int count)
template<class DST , class SRC >
void qt_rectconvert (DST *dest, const SRC *src, int x, int y, int width, int height, int dstStride, int srcStride)
template<class T >
void qt_rectcopy (T *dest, const T *src, int x, int y, int width, int height, int dstStride, int srcStride)
template<class T >
void qt_rectfill (T *dest, T value, int x, int y, int width, int height, int stride)
void QT_FASTCALL rasterop_NotSource (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL rasterop_NotSourceAndDestination (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL rasterop_NotSourceAndNotDestination (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL rasterop_NotSourceOrNotDestination (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL rasterop_NotSourceXorDestination (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL rasterop_solid_NotSource (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL rasterop_solid_NotSourceAndDestination (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL rasterop_solid_NotSourceAndNotDestination (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL rasterop_solid_NotSourceOrNotDestination (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL rasterop_solid_NotSourceXorDestination (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL rasterop_solid_SourceAndDestination (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL rasterop_solid_SourceAndNotDestination (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL rasterop_solid_SourceOrDestination (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL rasterop_solid_SourceXorDestination (uint *dest, int length, uint color, uint const_alpha)
void QT_FASTCALL rasterop_SourceAndDestination (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL rasterop_SourceAndNotDestination (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL rasterop_SourceOrDestination (uint *dest, const uint *src, int length, uint const_alpha)
void QT_FASTCALL rasterop_SourceXorDestination (uint *dest, const uint *src, int length, uint const_alpha)
Variables
static const uint AMASK = 0xff000000
static const uint BMASK = 0x000000ff
static const uint GMASK = 0x0000ff00
class quint32p Q_PACKED
SrcOverBlendFunc qBlendFunctions [QImage::NImageFormats][QImage::NImageFormats]
DrawHelper qDrawHelper [QImage::NImageFormats]
DrawHelper qDrawHelperCallback [QImage::NImageFormats]
MemRotateFunc qMemRotateFunctions [QImage::NImageFormats][3]
SrcOverScaleFunc qScaleFunctions [QImage::NImageFormats][QImage::NImageFormats]
const uint qt_bayer_matrix [16][16]
SrcOverTransformFunc qTransformFunctions [QImage::NImageFormats][QImage::NImageFormats]
static const uint RMASK = 0x00ff0000
Macro Definition Documentation
AMIX
#define AMIX (mask) quint32(qMin(((qint64(s)&mask) + (qint64(d)&mask)), qint64(mask)))
Definition at line 2196 of file qdrawhelper_p.h.
Referenced by comp_func_Plus_one_pixel(), and comp_func_Plus_one_pixel_const_alpha().
ARGB_COMBINE_ALPHA
#define ARGB_COMBINE_ALPHA (argb, alpha) ((((argb >> 24) * alpha) >> 8) << 24) | (argb & 0x00ffffff)
Definition at line 2187 of file qdrawhelper_p.h.
Referenced by QRasterPaintEngine::drawImage(), QRasterPaintEngine::fillRect(), QGL2GradientCache::generateGradientColorTable(), QGLGradientCache::generateGradientColorTable(), QGradientCache::generateGradientColorTable(), and QSpanData::setup().
FETCH_RADIAL_LOOP
#define FETCH_RADIAL_LOOP (FETCH_RADIAL_LOOP_CLAMP)
Value:
FETCH_RADIAL_LOOP_PROLOGUE \
        FETCH_RADIAL_LOOP_CLAMP \
        FETCH_RADIAL_LOOP_EPILOGUE
Referenced by QRadialFetchSimd< Simd >::fetch().
FETCH_RADIAL_LOOP_CLAMP_PAD
#define FETCH_RADIAL_LOOP_CLAMP_PAD index_vec.v = Simd::v_toInt(Simd::v_min(v_max, Simd::v_max(v_min, v_index)));
Referenced by QRadialFetchSimd< Simd >::fetch().
FETCH_RADIAL_LOOP_CLAMP_REFLECT
#define FETCH_RADIAL_LOOP_CLAMP_REFLECT
Value:
const typename Simd::Int32x4 v_index_i = Simd::v_and(v_reflect_mask, Simd::v_toInt(v_index)); \
            const typename Simd::Int32x4 v_index_i_inv = Simd::v_sub(v_reflect_limit, v_index_i); \
            index_vec.v = Simd::v_min_16(v_index_i, v_index_i_inv);
Referenced by QRadialFetchSimd< Simd >::fetch().
FETCH_RADIAL_LOOP_CLAMP_REPEAT
#define FETCH_RADIAL_LOOP_CLAMP_REPEAT index_vec.v = Simd::v_and(v_repeat_mask, Simd::v_toInt(v_index));
Referenced by QRadialFetchSimd< Simd >::fetch().
FETCH_RADIAL_LOOP_EPILOGUE
#define FETCH_RADIAL_LOOP_EPILOGUE
Value:
det_vec.v = Simd::v_add(Simd::v_add(det_vec.v, delta_det4_vec.v), v_delta_delta_det6); \
            delta_det4_vec.v = Simd::v_add(delta_det4_vec.v, v_delta_delta_det16); \
            b_vec.v = Simd::v_add(b_vec.v, v_delta_b4); \
            for (int i = 0; i < 4; ++i) \
                *buffer++ = (extended_mask | v_buffer_mask.i[i]) & data->gradient.colorTable[index_vec.i[i]]; \
        }
FETCH_RADIAL_LOOP_PROLOGUE
#define FETCH_RADIAL_LOOP_PROLOGUE
Value:
while (buffer < end) { \
            typename Simd::Vect_buffer_i v_buffer_mask; \
            v_buffer_mask.v = Simd::v_greaterOrEqual(det_vec.v, v_min); \
            const typename Simd::Float32x4 v_index_local = Simd::v_sub(Simd::v_sqrt(Simd::v_max(v_min, det_vec.v)), b_vec.v); \
            const typename Simd::Float32x4 v_index = Simd::v_add(Simd::v_mul(v_index_local, v_max), v_half); \
            v_buffer_mask.v = Simd::v_and(v_buffer_mask.v, Simd::v_greaterOrEqual(Simd::v_add(v_r0, Simd::v_mul(v_dr, v_index_local)), v_min)); \
            typename Simd::Vect_buffer_i index_vec;
GRADIENT_STOPTABLE_SIZE
#define GRADIENT_STOPTABLE_SIZE 256
Definition at line 275 of file qdrawhelper_p.h.
Referenced by QRadialFetchSimd< Simd >::fetch(), QGradientCache::generateGradientColorTable(), QGradientCache::paletteSize(), qt_fetch_linear_gradient(), qt_gradient_clamp(), qt_gradient_pixel(), qt_gradient_quint16(), and qt_gradient_quint32().
GRADIENT_STOPTABLE_SIZE_SHIFT
#define GRADIENT_STOPTABLE_SIZE_SHIFT 8
Definition at line 276 of file qdrawhelper_p.h.
Referenced by QRadialFetchSimd< Simd >::fetch().
INV_PREMUL
#define INV_PREMUL (p)
Value:
(qAlpha(p) == 0 ? 0 :                               \
    ((qAlpha(p) << 24)                                  \
     | (((255*qRed(p))/ qAlpha(p)) << 16)               \
     | (((255*qGreen(p)) / qAlpha(p))  << 8)            \
     | ((255*qBlue(p)) / qAlpha(p))))
Definition at line 669 of file qdrawhelper_p.h.
Referenced by convert_ARGB_PM_to_ARGB(), convert_ARGB_PM_to_RGB(), qt_rectfill_nonpremul_quint32(), and QSvgPaintEngine::saveGradientStops().
MIX
#define MIX (mask) (qMin(((quint32(s)&mask) + (quint32(d)&mask)), quint32(mask)))
Definition at line 2197 of file qdrawhelper_p.h.
Referenced by comp_func_Plus_one_pixel(), and comp_func_Plus_one_pixel_const_alpha().
Q_STATIC_INLINE_FUNCTION
#define Q_STATIC_INLINE_FUNCTION static inline
Definition at line 86 of file qdrawhelper_p.h.
Referenced by INTERPOLATE_PIXEL_255().
Q_STATIC_TEMPLATE_FUNCTION
#define Q_STATIC_TEMPLATE_FUNCTION static
Definition at line 85 of file qdrawhelper_p.h.
Referenced by blit_template(), qrgb444::byte_mul(), fetchTransformedBilinear_pixelBounds(), qt_fetchUntransformed< QImage::Format_ARGB32_Premultiplied >(), and qt_memfill16_setup().
Q_STATIC_TEMPLATE_SPECIALIZATION
#define Q_STATIC_TEMPLATE_SPECIALIZATION
Definition at line 77 of file qdrawhelper_p.h.
Referenced by alpha_2(), alpha_4(), blend_sourceOver_rgb16_rgb16(), blendUntransformed_dest24(), eff_alpha_2(), eff_alpha_4(), eff_ialpha_2(), eff_ialpha_4(), madd_2(), madd_4(), qt_fetchPixel< QImage::Format_ARGB32 >(), qt_fetchPixel< QImage::Format_ARGB32_Premultiplied >(), qt_fetchPixel< QImage::Format_ARGB4444_Premultiplied >(), qt_fetchPixel< QImage::Format_ARGB6666_Premultiplied >(), qt_fetchPixel< QImage::Format_ARGB8555_Premultiplied >(), qt_fetchPixel< QImage::Format_ARGB8565_Premultiplied >(), qt_fetchPixel< QImage::Format_Indexed8 >(), qt_fetchPixel< QImage::Format_Mono >(), qt_fetchPixel< QImage::Format_MonoLSB >(), qt_fetchPixel< QImage::Format_RGB16 >(), qt_fetchPixel< QImage::Format_RGB444 >(), qt_fetchPixel< QImage::Format_RGB555 >(), qt_fetchPixel< QImage::Format_RGB666 >(), qt_fetchPixel< QImage::Format_RGB888 >(), qt_fetchUntransformed(), qt_memrotate270_template(), qt_memrotate90_template< quint24, quint24 >(), and qt_memrotate90_template< quint24, quint32 >().
QT_FT_BEGIN_HEADER
#define QT_FT_BEGIN_HEADER
Definition at line 61 of file qdrawhelper_p.h.
QT_FT_END_HEADER
#define QT_FT_END_HEADER
Definition at line 62 of file qdrawhelper_p.h.
QT_MEMCPY_REV_UINT
#define QT_MEMCPY_REV_UINT (dest, src, length)
Value:
do {                                          \
    /* Duff's device */                       \
    uint *_d = (uint*)(dest) + length;         \
    const uint *_s = (uint*)(src) + length;    \
    register int n = ((length) + 7) / 8;      \
    switch ((length) & 0x07)                  \
    {                                         \
    case 0: do { *--_d = *--_s;                 \
    case 7:      *--_d = *--_s;                 \
    case 6:      *--_d = *--_s;                 \
    case 5:      *--_d = *--_s;                 \
    case 4:      *--_d = *--_s;                 \
    case 3:      *--_d = *--_s;                 \
    case 2:      *--_d = *--_s;                 \
    case 1:      *--_d = *--_s;                 \
    } while (--n > 0);                        \
    }                                         \
} while (0)
Definition at line 2063 of file qdrawhelper_p.h.
QT_MEMCPY_USHORT
#define QT_MEMCPY_USHORT (dest, src, length)
Value:
do {                                          \
    /* Duff's device */                       \
    ushort *_d = (ushort*)(dest);         \
    const ushort *_s = (ushort*)(src);    \
    register int n = ((length) + 7) / 8;      \
    switch ((length) & 0x07)                  \
    {                                         \
    case 0: do { *_d++ = *_s++;                 \
    case 7:      *_d++ = *_s++;                 \
    case 6:      *_d++ = *_s++;                 \
    case 5:      *_d++ = *_s++;                 \
    case 4:      *_d++ = *_s++;                 \
    case 3:      *_d++ = *_s++;                 \
    case 2:      *_d++ = *_s++;                 \
    case 1:      *_d++ = *_s++;                 \
    } while (--n > 0);                        \
    }                                         \
} while (0)
Definition at line 2083 of file qdrawhelper_p.h.
Referenced by qt_blend_rgb16_on_rgb16().
QT_MEMFILL_UINT
#define QT_MEMFILL_UINT (dest, length, color) qt_memfill<quint32>(dest, color, length);
Definition at line 2057 of file qdrawhelper_p.h.
Referenced by blend_color_argb(), comp_func_solid_Source(), comp_func_solid_SourceOver(), and qt_fetch_linear_gradient().
QT_MEMFILL_USHORT
#define QT_MEMFILL_USHORT (dest, length, color) qt_memfill<quint16>(dest, color, length);
Definition at line 2060 of file qdrawhelper_p.h.
Referenced by blend_color_rgb16().
QT_RECTCONVERT_TRIVIAL_IMPL
#define QT_RECTCONVERT_TRIVIAL_IMPL (T)
Value:
template <>                                                         \
    inline void qt_rectconvert(T *dest, const T *src,                   \
                               int x, int y, int width, int height,     \
                               int dstStride, int srcStride)            \
    {                                                                   \
        qt_rectcopy(dest, src, x, y, width, height, dstStride, srcStride); \
    }
Definition at line 2026 of file qdrawhelper_p.h.
QT_TRIVIAL_MEMCONVERT_IMPL
#define QT_TRIVIAL_MEMCONVERT_IMPL (T)
Value:
template <> \
    inline void qt_memconvert(T *dest, const T *src, int count) \
    { \
        memcpy(dest, src, count * sizeof(T)); \
    }
Definition at line 1930 of file qdrawhelper_p.h.
Typedef Documentation
AlphamapBlitFunc
typedef void(* AlphamapBlitFunc) (QRasterBuffer *rasterBuffer, int x, int y, quint32 color, const uchar *bitmap, int mapWidth, int mapHeight, int mapStride, const QClipData *clip)
Definition at line 119 of file qdrawhelper_p.h.
AlphaRGBBlitFunc
typedef void(* AlphaRGBBlitFunc) (QRasterBuffer *rasterBuffer, int x, int y, quint32 color, const uint *rgbmask, int mapWidth, int mapHeight, int mapStride, const QClipData *clip)
Definition at line 125 of file qdrawhelper_p.h.
BitmapBlitFunc
typedef void(* BitmapBlitFunc) (QRasterBuffer *rasterBuffer, int x, int y, quint32 color, const uchar *bitmap, int mapWidth, int mapHeight, int mapStride)
Definition at line 114 of file qdrawhelper_p.h.
CompositionFunction
typedef void(QT_FASTCALL * CompositionFunction) (uint *dest, const uint *src, int length, uint const_alpha)
Definition at line 179 of file qdrawhelper_p.h.
CompositionFunctionSolid
typedef void(QT_FASTCALL * CompositionFunctionSolid) (uint *dest, int length, uint color, uint const_alpha)
Definition at line 180 of file qdrawhelper_p.h.
DestFetchProc
typedef uint* QT_FASTCALL* DestFetchProc(uint *buffer, QRasterBuffer *rasterBuffer, int x, int y, int length)
Definition at line 202 of file qdrawhelper_p.h.
DestStoreProc
typedef void(QT_FASTCALL * DestStoreProc) (QRasterBuffer *rasterBuffer, int x, int y, const uint *buffer, int length)
Definition at line 203 of file qdrawhelper_p.h.
MemRotateFunc
typedef void(* MemRotateFunc) (const uchar *srcPixels, int w, int h, int sbpl, uchar *destPixels, int dbpl)
Definition at line 155 of file qdrawhelper_p.h.
ProcessSpans
typedef QT_FT_SpanFunc ProcessSpans
Definition at line 111 of file qdrawhelper_p.h.
QSpan
typedef QT_FT_Span QSpan related
Definition at line 99 of file qdrawhelper_p.h.
RectFillFunc
typedef void(* RectFillFunc) (QRasterBuffer *rasterBuffer, int x, int y, int width, int height, quint32 color)
Definition at line 131 of file qdrawhelper_p.h.
SourceFetchProc
typedef const uint*(QT_FASTCALL * SourceFetchProc) (uint *buffer, const Operator *o, const QSpanData *data, int y, int x, int length)
Definition at line 204 of file qdrawhelper_p.h.
SrcOverBlendFunc
typedef void(* SrcOverBlendFunc) (uchar *destPixels, int dbpl, const uchar *src, int spbl, int w, int h, int const_alpha)
Definition at line 135 of file qdrawhelper_p.h.
SrcOverScaleFunc
typedef void(* SrcOverScaleFunc) (uchar *destPixels, int dbpl, const uchar *src, int spbl, int srch, const QRectF &targetRect, const QRectF &sourceRect, const QRect &clipRect, int const_alpha)
Definition at line 140 of file qdrawhelper_p.h.
SrcOverTransformFunc
typedef void(* SrcOverTransformFunc) (uchar *destPixels, int dbpl, const uchar *src, int spbl, const QRectF &targetRect, const QRectF &sourceRect, const QRect &clipRect, const QTransform &targetRectTransform, int const_alpha)
Definition at line 147 of file qdrawhelper_p.h.
Function Documentation
BYTE_MUL()
Q_STATIC_INLINE_FUNCTION uint BYTE_MUL (uint x, uint a)
Definition at line 626 of file qdrawhelper_p.h.
Referenced by blend_color_argb(), blend_color_rgb16(), blendColor(), blendUntransformed_dest16(), blendUntransformed_dest24(), comp_func_DestinationAtop(), comp_func_DestinationIn(), comp_func_DestinationOut(), comp_func_DestinationOver(), comp_func_solid_DestinationAtop(), comp_func_solid_DestinationIn(), comp_func_solid_DestinationOut(), comp_func_solid_DestinationOver(), comp_func_solid_Source(), comp_func_solid_SourceAtop(), comp_func_solid_SourceIn(), comp_func_solid_SourceOut(), comp_func_solid_SourceOver(), comp_func_solid_XOR(), comp_func_SourceAtop(), comp_func_SourceIn(), comp_func_SourceOut(), comp_func_SourceOver(), comp_func_XOR(), drawPixelARGB32(), INTERPOLATE_PIXEL_255(), qt_blend_argb32_on_argb32(), qt_blend_argb32_on_rgb16_const_alpha(), sourceOver(), Blend_ARGB32_on_RGB16_SourceAndConstAlpha::write(), Blend_RGB32_on_RGB32_ConstAlpha::write(), Blend_ARGB32_on_ARGB32_SourceAlpha::write(), and Blend_ARGB32_on_ARGB32_SourceAndConstAlpha::write().
{
     uint t = (x & 0xff00ff) * a;
     t = (t + ((t >> 8) & 0xff00ff) + 0x800080) >> 8;
     t &= 0xff00ff;
     x = ((x >> 8) & 0xff00ff) * a;
     x = (x + ((x >> 8) & 0xff00ff) + 0x800080);
     x &= 0xff00ff00;
     x |= t;
     return x;
 }
BYTE_MUL_RGB16()
Q_STATIC_INLINE_FUNCTION uint BYTE_MUL_RGB16 (uint x, uint a)
Definition at line 656 of file qdrawhelper_p.h.
Referenced by blend_color_rgb16(), qt_alphamapblit_quint16(), qt_blend_argb32_on_rgb16_const_alpha(), qt_blend_rgb16_on_rgb16(), Blend_RGB16_on_RGB16_ConstAlpha::write(), Blend_ARGB24_on_RGB16_SourceAlpha::write(), Blend_ARGB24_on_RGB16_SourceAndConstAlpha::write(), Blend_ARGB32_on_RGB16_SourceAlpha::write(), and Blend_ARGB32_on_RGB16_SourceAndConstAlpha::write().
{
     a += 1;
     uint t = (((x & 0x07e0)*a) >> 8) & 0x07e0;
     t |= (((x & 0xf81f)*(a>>2)) >> 6) & 0xf81f;
     return t;
 }
BYTE_MUL_RGB16_32()
Q_STATIC_INLINE_FUNCTION uint BYTE_MUL_RGB16_32 (uint x, uint a)
Definition at line 663 of file qdrawhelper_p.h.
Referenced by blend_color_rgb16().
{
     uint t = (((x & 0xf81f07e0) >> 5)*a) & 0xf81f07e0;
     t |= (((x & 0x07e0f81f)*a) >> 5) & 0x07e0f81f;
     return t;
 }
comp_func_Clear()
void QT_FASTCALL comp_func_Clear (uint * dest, const uint * , int length, uint const_alpha)
Definition at line 1580 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     comp_func_Clear_impl(dest, length, const_alpha);
 }
comp_func_ColorBurn()
void QT_FASTCALL comp_func_ColorBurn (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2582 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_ColorBurn_impl(dest, src, length, QFullCoverage());
     else
         comp_func_ColorBurn_impl(dest, src, length, QPartialCoverage(const_alpha));
 }
comp_func_ColorDodge()
void QT_FASTCALL comp_func_ColorDodge (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2499 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_ColorDodge_impl(dest, src, length, QFullCoverage());
     else
         comp_func_ColorDodge_impl(dest, src, length, QPartialCoverage(const_alpha));
 }
comp_func_Darken()
void QT_FASTCALL comp_func_Darken (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2343 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_Darken_impl(dest, src, length, QFullCoverage());
     else
         comp_func_Darken_impl(dest, src, length, QPartialCoverage(const_alpha));
 }
comp_func_Destination()
void QT_FASTCALL comp_func_Destination (uint * , const uint * , int , uint)
Definition at line 1622 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
 }
comp_func_DestinationAtop()
void QT_FASTCALL comp_func_DestinationAtop (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 1919 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     PRELOAD_INIT2(dest, src)
     if (const_alpha == 255) {
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             uint s = src[i];
             uint d = dest[i];
             dest[i] = INTERPOLATE_PIXEL_255(d, qAlpha(s), s, qAlpha(~d));
         }
     } else {
         int cia = 255 - const_alpha;
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             uint s = BYTE_MUL(src[i], const_alpha);
             uint d = dest[i];
             uint a = qAlpha(s) + cia;
             dest[i] = INTERPOLATE_PIXEL_255(d, a, s, qAlpha(~d));
         }
     }
 }
comp_func_DestinationIn()
void QT_FASTCALL comp_func_DestinationIn (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 1764 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     PRELOAD_INIT2(dest, src)
     if (const_alpha == 255) {
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             dest[i] = BYTE_MUL(dest[i], qAlpha(src[i]));
         }
     } else {
         int cia = 255 - const_alpha;
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             uint a = BYTE_MUL(qAlpha(src[i]), const_alpha) + cia;
             dest[i] = BYTE_MUL(dest[i], a);
         }
     }
 }
comp_func_DestinationOut()
void QT_FASTCALL comp_func_DestinationOut (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 1842 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     PRELOAD_INIT2(dest, src)
     if (const_alpha == 255) {
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             dest[i] = BYTE_MUL(dest[i], qAlpha(~src[i]));
         }
     } else {
         int cia = 255 - const_alpha;
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             uint sia = BYTE_MUL(qAlpha(~src[i]), const_alpha) + cia;
             dest[i] = BYTE_MUL(dest[i], sia);
         }
     }
 }
comp_func_DestinationOver()
void QT_FASTCALL comp_func_DestinationOver (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 1685 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     PRELOAD_INIT2(dest, src)
     if (const_alpha == 255) {
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             uint d = dest[i];
             dest[i] = d + BYTE_MUL(src[i], qAlpha(~d));
         }
     } else {
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             uint d = dest[i];
             uint s = BYTE_MUL(src[i], const_alpha);
             dest[i] = d + BYTE_MUL(s, qAlpha(~d));
         }
     }
 }
comp_func_Difference()
void QT_FASTCALL comp_func_Difference (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2826 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_Difference_impl(dest, src, length, QFullCoverage());
     else
         comp_func_Difference_impl(dest, src, length, QPartialCoverage(const_alpha));
 }
comp_func_Exclusion()
void QT_FASTCALL comp_func_Exclusion (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2893 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_Exclusion_impl(dest, src, length, QFullCoverage());
     else
         comp_func_Exclusion_impl(dest, src, length, QPartialCoverage(const_alpha));
 }
comp_func_HardLight()
void QT_FASTCALL comp_func_HardLight (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2662 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_HardLight_impl(dest, src, length, QFullCoverage());
     else
         comp_func_HardLight_impl(dest, src, length, QPartialCoverage(const_alpha));
 }
comp_func_Lighten()
void QT_FASTCALL comp_func_Lighten (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2416 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_Lighten_impl(dest, src, length, QFullCoverage());
     else
         comp_func_Lighten_impl(dest, src, length, QPartialCoverage(const_alpha));
 }
comp_func_Multiply()
void QT_FASTCALL comp_func_Multiply (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2123 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_Multiply_impl(dest, src, length, QFullCoverage());
     else
         comp_func_Multiply_impl(dest, src, length, QPartialCoverage(const_alpha));
 }
comp_func_Overlay()
void QT_FASTCALL comp_func_Overlay (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2270 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_Overlay_impl(dest, src, length, QFullCoverage());
     else
         comp_func_Overlay_impl(dest, src, length, QPartialCoverage(const_alpha));
 }
comp_func_Plus()
void QT_FASTCALL comp_func_Plus (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2051 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_Plus_impl(dest, src, length, QFullCoverage());
     else
         comp_func_Plus_impl(dest, src, length, QPartialCoverage(const_alpha));
 }
comp_func_Plus_one_pixel()
int comp_func_Plus_one_pixel (uint d, const uint s) inline
Definition at line 2206 of file qdrawhelper_p.h.
Referenced by comp_func_Plus_impl(), and comp_func_solid_Plus_impl().
 {
     const int result = (AMIX(AMASK) | MIX(RMASK) | MIX(GMASK) | MIX(BMASK));
     return result;
 }
comp_func_Plus_one_pixel_const_alpha()
int comp_func_Plus_one_pixel_const_alpha (uint d, const uint s, const uint const_alpha, const uint one_minus_const_alpha) inline
Definition at line 2200 of file qdrawhelper_p.h.
 {
     const int result = (AMIX(AMASK) | MIX(RMASK) | MIX(GMASK) | MIX(BMASK));
     return INTERPOLATE_PIXEL_255(result, const_alpha, d, one_minus_const_alpha);
 }
comp_func_Screen()
void QT_FASTCALL comp_func_Screen (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2191 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_Screen_impl(dest, src, length, QFullCoverage());
     else
         comp_func_Screen_impl(dest, src, length, QPartialCoverage(const_alpha));
 }
comp_func_SoftLight()
void QT_FASTCALL comp_func_SoftLight (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2753 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_SoftLight_impl(dest, src, length, QFullCoverage());
     else
         comp_func_SoftLight_impl(dest, src, length, QPartialCoverage(const_alpha));
 }
comp_func_solid_Clear()
void QT_FASTCALL comp_func_solid_Clear (uint * dest, int length, uint color, uint const_alpha)
Definition at line 1575 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     comp_func_Clear_impl(dest, length, const_alpha);
 }
comp_func_solid_ColorBurn()
void QT_FASTCALL comp_func_solid_ColorBurn (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2551 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_solid_ColorBurn_impl(dest, length, color, QFullCoverage());
     else
         comp_func_solid_ColorBurn_impl(dest, length, color, QPartialCoverage(const_alpha));
 }
comp_func_solid_ColorDodge()
void QT_FASTCALL comp_func_solid_ColorDodge (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2468 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_solid_ColorDodge_impl(dest, length, color, QFullCoverage());
     else
         comp_func_solid_ColorDodge_impl(dest, length, color, QPartialCoverage(const_alpha));
 }
comp_func_solid_Darken()
void QT_FASTCALL comp_func_solid_Darken (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2312 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_solid_Darken_impl(dest, length, color, QFullCoverage());
     else
         comp_func_solid_Darken_impl(dest, length, color, QPartialCoverage(const_alpha));
 }
comp_func_solid_Destination()
void QT_FASTCALL comp_func_solid_Destination (uint * dest, int length, uint color, uint const_alpha)
Definition at line 1618 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
 }
comp_func_solid_DestinationAtop()
void QT_FASTCALL comp_func_solid_DestinationAtop (uint * dest, int length, uint color, uint const_alpha)
Definition at line 1904 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     uint a = qAlpha(color);
     if (const_alpha != 255) {
         color = BYTE_MUL(color, const_alpha);
         a = qAlpha(color) + 255 - const_alpha;
     }
     PRELOAD_INIT(dest)
     for (int i = 0; i < length; ++i) {
         PRELOAD_COND(dest)
         uint d = dest[i];
         dest[i] = INTERPOLATE_PIXEL_255(d, a, color, qAlpha(~d));
     }
 }
comp_func_solid_DestinationIn()
void QT_FASTCALL comp_func_solid_DestinationIn (uint * dest, int length, uint color, uint const_alpha)
Definition at line 1751 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     uint a = qAlpha(color);
     if (const_alpha != 255) {
         a = BYTE_MUL(a, const_alpha) + 255 - const_alpha;
     }
     PRELOAD_INIT(dest)
     for (int i = 0; i < length; ++i) {
         PRELOAD_COND(dest)
         dest[i] = BYTE_MUL(dest[i], a);
     }
 }
comp_func_solid_DestinationOut()
void QT_FASTCALL comp_func_solid_DestinationOut (uint * dest, int length, uint color, uint const_alpha)
Definition at line 1830 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     uint a = qAlpha(~color);
     if (const_alpha != 255)
         a = BYTE_MUL(a, const_alpha) + 255 - const_alpha;
     PRELOAD_INIT(dest)
     for (int i = 0; i < length; ++i) {
         PRELOAD_COND(dest)
         dest[i] = BYTE_MUL(dest[i], a);
     }
 }
comp_func_solid_DestinationOver()
void QT_FASTCALL comp_func_solid_DestinationOver (uint * dest, int length, uint color, uint const_alpha)
Definition at line 1673 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha != 255)
         color = BYTE_MUL(color, const_alpha);
     PRELOAD_INIT(dest)
     for (int i = 0; i < length; ++i) {
         PRELOAD_COND(dest)
         uint d = dest[i];
         dest[i] = d + BYTE_MUL(color, qAlpha(~d));
     }
 }
comp_func_solid_Difference()
void QT_FASTCALL comp_func_solid_Difference (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2795 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_solid_Difference_impl(dest, length, color, QFullCoverage());
     else
         comp_func_solid_Difference_impl(dest, length, color, QPartialCoverage(const_alpha));
 }
comp_func_solid_Exclusion()
void QT_FASTCALL comp_func_solid_Exclusion (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2862 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_solid_Exclusion_impl(dest, length, color, QFullCoverage());
     else
         comp_func_solid_Exclusion_impl(dest, length, color, QPartialCoverage(const_alpha));
 }
comp_func_solid_HardLight()
void QT_FASTCALL comp_func_solid_HardLight (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2631 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_solid_HardLight_impl(dest, length, color, QFullCoverage());
     else
         comp_func_solid_HardLight_impl(dest, length, color, QPartialCoverage(const_alpha));
 }
comp_func_solid_Lighten()
void QT_FASTCALL comp_func_solid_Lighten (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2385 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_solid_Lighten_impl(dest, length, color, QFullCoverage());
     else
         comp_func_solid_Lighten_impl(dest, length, color, QPartialCoverage(const_alpha));
 }
comp_func_solid_Multiply()
void QT_FASTCALL comp_func_solid_Multiply (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2092 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_solid_Multiply_impl(dest, length, color, QFullCoverage());
     else
         comp_func_solid_Multiply_impl(dest, length, color, QPartialCoverage(const_alpha));
 }
comp_func_solid_Overlay()
void QT_FASTCALL comp_func_solid_Overlay (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2239 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_solid_Overlay_impl(dest, length, color, QFullCoverage());
     else
         comp_func_solid_Overlay_impl(dest, length, color, QPartialCoverage(const_alpha));
 }
comp_func_solid_Plus()
void QT_FASTCALL comp_func_solid_Plus (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2028 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_solid_Plus_impl(dest, length, color, QFullCoverage());
     else
         comp_func_solid_Plus_impl(dest, length, color, QPartialCoverage(const_alpha));
 }
comp_func_solid_Screen()
void QT_FASTCALL comp_func_solid_Screen (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2160 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_solid_Screen_impl(dest, length, color, QFullCoverage());
     else
         comp_func_solid_Screen_impl(dest, length, color, QPartialCoverage(const_alpha));
 }
comp_func_solid_SoftLight()
void QT_FASTCALL comp_func_solid_SoftLight (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2722 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255)
         comp_func_solid_SoftLight_impl(dest, length, color, QFullCoverage());
     else
         comp_func_solid_SoftLight_impl(dest, length, color, QPartialCoverage(const_alpha));
 }
comp_func_solid_Source()
void QT_FASTCALL comp_func_solid_Source (uint * dest, int length, uint color, uint const_alpha)
Definition at line 1589 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255) {
         QT_MEMFILL_UINT(dest, length, color);
     } else {
         int ialpha = 255 - const_alpha;
         color = BYTE_MUL(color, const_alpha);
         PRELOAD_INIT(dest)
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND(dest)
             dest[i] = color + BYTE_MUL(dest[i], ialpha);
         }
     }
 }
comp_func_solid_SourceAtop()
void QT_FASTCALL comp_func_solid_SourceAtop (uint * dest, int length, uint color, uint const_alpha)
Definition at line 1866 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha != 255) {
         color = BYTE_MUL(color, const_alpha);
     }
     uint sia = qAlpha(~color);
     PRELOAD_INIT(dest)
     for (int i = 0; i < length; ++i) {
         PRELOAD_COND(dest)
         dest[i] = INTERPOLATE_PIXEL_255(color, qAlpha(dest[i]), dest[i], sia);
     }
 }
comp_func_solid_SourceIn()
void QT_FASTCALL comp_func_solid_SourceIn (uint * dest, int length, uint color, uint const_alpha)
Definition at line 1708 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     PRELOAD_INIT(dest)
     if (const_alpha == 255) {
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND(dest)
             dest[i] = BYTE_MUL(color, qAlpha(dest[i]));
         }
     } else {
         color = BYTE_MUL(color, const_alpha);
         uint cia = 255 - const_alpha;
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND(dest)
             uint d = dest[i];
             dest[i] = INTERPOLATE_PIXEL_255(color, qAlpha(d), d, cia);
         }
     }
 }
comp_func_solid_SourceOut()
void QT_FASTCALL comp_func_solid_SourceOut (uint * dest, int length, uint color, uint const_alpha)
Definition at line 1787 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     PRELOAD_INIT(dest)
     if (const_alpha == 255) {
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND(dest)
             dest[i] = BYTE_MUL(color, qAlpha(~dest[i]));
         }
     } else {
         color = BYTE_MUL(color, const_alpha);
         int cia = 255 - const_alpha;
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND(dest)
             uint d = dest[i];
             dest[i] = INTERPOLATE_PIXEL_255(color, qAlpha(~d), d, cia);
         }
     }
 }
comp_func_solid_SourceOver()
void QT_FASTCALL comp_func_solid_SourceOver (uint * dest, int length, uint color, uint const_alpha)
Definition at line 1632 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if ((const_alpha & qAlpha(color)) == 255) {
         QT_MEMFILL_UINT(dest, length, color);
     } else {
         if (const_alpha != 255)
             color = BYTE_MUL(color, const_alpha);
         PRELOAD_INIT(dest)
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND(dest)
             dest[i] = color + BYTE_MUL(dest[i], qAlpha(~color));
         }
     }
 }
comp_func_solid_XOR()
void QT_FASTCALL comp_func_solid_XOR (uint * dest, int length, uint color, uint const_alpha)
Definition at line 1947 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha != 255)
         color = BYTE_MUL(color, const_alpha);
     uint sia = qAlpha(~color);
     PRELOAD_INIT(dest)
     for (int i = 0; i < length; ++i) {
         PRELOAD_COND(dest)
         uint d = dest[i];
         dest[i] = INTERPOLATE_PIXEL_255(color, qAlpha(~d), d, sia);
     }
 }
comp_func_Source()
void QT_FASTCALL comp_func_Source (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 1604 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     if (const_alpha == 255) {
         ::memcpy(dest, src, length * sizeof(uint));
     } else {
         int ialpha = 255 - const_alpha;
         PRELOAD_INIT2(dest, src)
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             dest[i] = INTERPOLATE_PIXEL_255(src[i], const_alpha, dest[i], ialpha);
         }
     }
 }
comp_func_SourceAtop()
void QT_FASTCALL comp_func_SourceAtop (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 1879 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     PRELOAD_INIT2(dest, src)
     if (const_alpha == 255) {
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             uint s = src[i];
             uint d = dest[i];
             dest[i] = INTERPOLATE_PIXEL_255(s, qAlpha(d), d, qAlpha(~s));
         }
     } else {
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             uint s = BYTE_MUL(src[i], const_alpha);
             uint d = dest[i];
             dest[i] = INTERPOLATE_PIXEL_255(s, qAlpha(d), d, qAlpha(~s));
         }
     }
 }
comp_func_SourceIn()
void QT_FASTCALL comp_func_SourceIn (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 1727 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     PRELOAD_INIT2(dest, src)
     if (const_alpha == 255) {
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             dest[i] = BYTE_MUL(src[i], qAlpha(dest[i]));
         }
     } else {
         uint cia = 255 - const_alpha;
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             uint d = dest[i];
             uint s = BYTE_MUL(src[i], const_alpha);
             dest[i] = INTERPOLATE_PIXEL_255(s, qAlpha(d), d, cia);
         }
     }
 }
comp_func_SourceOut()
void QT_FASTCALL comp_func_SourceOut (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 1806 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     PRELOAD_INIT2(dest, src)
     if (const_alpha == 255) {
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             dest[i] = BYTE_MUL(src[i], qAlpha(~dest[i]));
         }
     } else {
         int cia = 255 - const_alpha;
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             uint s = BYTE_MUL(src[i], const_alpha);
             uint d = dest[i];
             dest[i] = INTERPOLATE_PIXEL_255(s, qAlpha(~d), d, cia);
         }
     }
 }
comp_func_SourceOver()
void QT_FASTCALL comp_func_SourceOver (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 1647 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     PRELOAD_INIT2(dest, src)
     if (const_alpha == 255) {
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             uint s = src[i];
             if (s >= 0xff000000)
                 dest[i] = s;
             else if (s != 0)
                 dest[i] = s + BYTE_MUL(dest[i], qAlpha(~s));
         }
     } else {
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             uint s = BYTE_MUL(src[i], const_alpha);
             dest[i] = s + BYTE_MUL(dest[i], qAlpha(~s));
         }
     }
 }
comp_func_XOR()
void QT_FASTCALL comp_func_XOR (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 1961 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     PRELOAD_INIT2(dest, src)
     if (const_alpha == 255) {
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             uint d = dest[i];
             uint s = src[i];
             dest[i] = INTERPOLATE_PIXEL_255(s, qAlpha(~d), d, qAlpha(~s));
         }
     } else {
         for (int i = 0; i < length; ++i) {
             PRELOAD_COND2(dest, src)
             uint d = dest[i];
             uint s = BYTE_MUL(src[i], const_alpha);
             dest[i] = INTERPOLATE_PIXEL_255(s, qAlpha(~d), d, qAlpha(~s));
         }
     }
 }
INTERPOLATE_PIXEL_255()
Q_STATIC_INLINE_FUNCTION uint INTERPOLATE_PIXEL_255 (uint x, uint a, uint y, uint b)
Definition at line 569 of file qdrawhelper_p.h.
Referenced by comp_func_DestinationAtop(), comp_func_Plus_one_pixel_const_alpha(), comp_func_solid_DestinationAtop(), comp_func_solid_SourceAtop(), comp_func_solid_SourceIn(), comp_func_solid_SourceOut(), comp_func_solid_XOR(), comp_func_Source(), comp_func_SourceAtop(), comp_func_SourceIn(), comp_func_SourceOut(), comp_func_XOR(), qt_alphamapblit_quint32(), and QPartialCoverage::store().
{
     uint t = (x & 0xff00ff) * a + (y & 0xff00ff) * b;
     t = (t + ((t >> 8) & 0xff00ff) + 0x800080) >> 8;
     t &= 0xff00ff;
     x = ((x >> 8) & 0xff00ff) * a + ((y >> 8) & 0xff00ff) * b;
     x = (x + ((x >> 8) & 0xff00ff) + 0x800080);
     x &= 0xff00ff00;
     x |= t;
     return x;
 }
INTERPOLATE_PIXEL_256()
Q_STATIC_INLINE_FUNCTION uint INTERPOLATE_PIXEL_256 (uint x, uint a, uint y, uint b)
Definition at line 611 of file qdrawhelper_p.h.
Referenced by cgColorForQColor(), fetchTransformedBilinear(), QGL2GradientCache::generateGradientColorTable(), QGLGradientCache::generateGradientColorTable(), QGradientCache::generateGradientColorTable(), INTERPOLATE_PIXEL_255(), QSvgPaintEngine::saveGradientStops(), and QCosmeticStroker::setup().
{
     uint t = (x & 0xff00ff) * a + (y & 0xff00ff) * b;
     t >>= 8;
     t &= 0xff00ff;
     x = ((x >> 8) & 0xff00ff) * a + ((y >> 8) & 0xff00ff) * b;
     x &= 0xff00ff00;
     x |= t;
     return x;
 }
PREMUL()
Q_STATIC_INLINE_FUNCTION uint PREMUL (uint x)
Definition at line 641 of file qdrawhelper_p.h.
Referenced by QGLPixmapData::bind(), QRasterBuffer::colorizeBitmap(), colorizeBitmap(), convert_ARGB_to_ARGB_PM(), convert_ARGB_to_ARGB_PM_inplace(), convert_indexed8_to_ARGB_PM_inplace(), destFetchARGB32(), QRasterPaintEngine::drawImage(), QBlittablePixmapData::fill(), QMacPixmapData::fill(), QRasterPixmapData::fill(), QX11PixmapData::fill(), QVGPixmapData::fill(), QGLPixmapData::fill(), QImage::fill(), QGLPixmapData::fillImage(), QRasterPaintEngine::fillRect(), findNearestColor(), fix_color_table(), QMacPixmapData::fromImage(), QGL2GradientCache::generateGradientColorTable(), QGLGradientCache::generateGradientColorTable(), QGradientCache::generateGradientColorTable(), INTERPOLATE_PIXEL_255(), QMacPixmapData::macSetAlphaChannel(), QGLPixmapData::paintEngine(), QRasterBuffer::prepare(), qt_fetchPixel< QImage::Format_ARGB32 >(), qt_fetchPixel< QImage::Format_Indexed8 >(), qt_fetchPixel< QImage::Format_Mono >(), qt_fetchPixel< QImage::Format_MonoLSB >(), QSvgPaintEngine::saveGradientStops(), and QSpanData::setup().
{
     uint a = x >> 24;
     uint t = (x & 0xff00ff) * a;
     t = (t + ((t >> 8) & 0xff00ff) + 0x800080) >> 8;
     t &= 0xff00ff;
     x = ((x >> 8) & 0xff) * a;
     x = (x + ((x >> 8) & 0xff) + 0x80);
     x &= 0xff00;
     x |= t | (a << 24);
     return x;
 }
qBlendTexture()
void qBlendTexture (int count, const QSpan * spans, void * userData)
Definition at line 6828 of file qdrawhelper.cpp.
Referenced by QSpanData::adjustSpanMethods().
 {
     QSpanData *data = reinterpret_cast<QSpanData *>(userData);
     ProcessSpans proc = processTextureSpans[getBlendType(data)][data->rasterBuffer->format];
     proc(count, spans, userData);
 }
qBlendTextureCallback()
void qBlendTextureCallback (int count, const QSpan * spans, void * userData)
Definition at line 6836 of file qdrawhelper.cpp.
Referenced by QSpanData::adjustSpanMethods().
 {
     QSpanData *data = reinterpret_cast<QSpanData *>(userData);
     ProcessSpans proc = processTextureSpansCallback[getBlendType(data)][data->rasterBuffer->format];
     proc(count, spans, userData);
 }
qBlue565()
int qBlue565 (quint16 rgb) inline
Definition at line 2147 of file qdrawhelper_p.h.
{
     const int b = (rgb & 0x001f);
     return (b << 3) | (b >> 2);
 }
qConvertRgb16To32()
QRgb qConvertRgb16To32 (uint c) inline
Definition at line 2129 of file qdrawhelper_p.h.
Referenced by destFetchRGB16(), and qt_fetchPixel< QImage::Format_RGB16 >().
 {
     return 0xff000000
         | ((((c) << 3) & 0xf8) | (((c) >> 2) & 0x7))
         | ((((c) << 5) & 0xfc00) | (((c) >> 1) & 0x300))
         | ((((c) << 8) & 0xf80000) | (((c) << 3) & 0x70000));
 }
qConvertRgb32To16()
ushort qConvertRgb32To16 (uint c) inline
Definition at line 2112 of file qdrawhelper_p.h.
Referenced by blend_color_rgb16().
 {
    return (((c) >> 3) & 0x001f)
        | (((c) >> 5) & 0x07e0)
        | (((c) >> 8) & 0xf800);
 }
qConvertRgb32To16x2()
quint32 qConvertRgb32To16x2 (quint64 c) inline
Definition at line 2120 of file qdrawhelper_p.h.
 {
     c = (((c) >> 3) & Q_UINT64_C(0x001f0000001f))
         | (((c) >> 5) & Q_UINT64_C(0x07e0000007e0))
         | (((c) >> 8) & Q_UINT64_C(0xf8000000f800));
     return c | (c >> 16);
 }
qGreen565()
int qGreen565 (quint16 rgb) inline
Definition at line 2142 of file qdrawhelper_p.h.
{
     const int g = (rgb & 0x07e0);
     return (g >> 3) | (g >> 9);
 }
qInitDrawhelperAsm()
void qInitDrawhelperAsm ()
Definition at line 7659 of file qdrawhelper.cpp.
Referenced by qt_memfill16_setup(), and qt_memfill32_setup().
 {
     qt_memfill32 = qt_memfill_template<quint32, quint32>;
     qt_memfill16 = qt_memfill_quint16; //qt_memfill_template<quint16, quint16>;
     CompositionFunction *functionForModeAsm = 0;
     CompositionFunctionSolid *functionForModeSolidAsm = 0;
     const uint features = qDetectCPUFeatures();
     if (false) {
 #ifdef QT_HAVE_SSE2
     } else if (features & SSE2) {
         qt_memfill32 = qt_memfill32_sse2;
         qt_memfill16 = qt_memfill16_sse2;
         qDrawHelper[QImage::Format_RGB32].bitmapBlit = qt_bitmapblit32_sse2;
         qDrawHelper[QImage::Format_ARGB32].bitmapBlit = qt_bitmapblit32_sse2;
         qDrawHelper[QImage::Format_ARGB32_Premultiplied].bitmapBlit = qt_bitmapblit32_sse2;
         qDrawHelper[QImage::Format_RGB16].bitmapBlit = qt_bitmapblit16_sse2;
 #endif
 #ifdef QT_HAVE_SSE
     } else if (features & SSE) {
 //        qt_memfill32 = qt_memfill32_sse;
         qDrawHelper[QImage::Format_RGB16].bitmapBlit = qt_bitmapblit16_sse;
 #ifdef QT_HAVE_3DNOW
         if (features & MMX3DNOW) {
             qt_memfill32 = qt_memfill32_sse3dnow;
             qDrawHelper[QImage::Format_RGB16].bitmapBlit = qt_bitmapblit16_sse3dnow;
         }
 #endif
 #endif // SSE
     }
 #ifdef QT_HAVE_MMX
     if (features & MMX) {
         functionForModeAsm = qt_functionForMode_MMX;
         functionForModeSolidAsm = qt_functionForModeSolid_MMX;
         qDrawHelper[QImage::Format_ARGB32_Premultiplied].blendColor = qt_blend_color_argb_mmx;
 #ifdef QT_HAVE_3DNOW
         if (features & MMX3DNOW) {
             functionForModeAsm = qt_functionForMode_MMX3DNOW;
             functionForModeSolidAsm = qt_functionForModeSolid_MMX3DNOW;
             qDrawHelper[QImage::Format_ARGB32_Premultiplied].blendColor = qt_blend_color_argb_mmx3dnow;
         }
 #endif // 3DNOW
         extern void qt_blend_rgb32_on_rgb32_mmx(uchar *destPixels, int dbpl,
                                                 const uchar *srcPixels, int sbpl,
                                                 int w, int h,
                                                 int const_alpha);
         extern void qt_blend_argb32_on_argb32_mmx(uchar *destPixels, int dbpl,
                                                   const uchar *srcPixels, int sbpl,
                                                   int w, int h,
                                                   int const_alpha);
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_mmx;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_mmx;
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_mmx;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_mmx;
     }
 #endif // MMX
 #ifdef QT_HAVE_SSE
     if (features & SSE) {
         extern void qt_blend_rgb32_on_rgb32_sse(uchar *destPixels, int dbpl,
                                                 const uchar *srcPixels, int sbpl,
                                                 int w, int h,
                                                 int const_alpha);
         extern void qt_blend_argb32_on_argb32_sse(uchar *destPixels, int dbpl,
                                                   const uchar *srcPixels, int sbpl,
                                                   int w, int h,
                                                   int const_alpha);
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_sse;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_sse;
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_sse;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_sse;
     }
 #endif // SSE
 #ifdef QT_HAVE_SSE2
     if (features & SSE2) {
         extern void qt_blend_rgb32_on_rgb32_sse2(uchar *destPixels, int dbpl,
                                                  const uchar *srcPixels, int sbpl,
                                                  int w, int h,
                                                  int const_alpha);
         extern void qt_blend_argb32_on_argb32_sse2(uchar *destPixels, int dbpl,
                                                    const uchar *srcPixels, int sbpl,
                                                    int w, int h,
                                                    int const_alpha);
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_sse2;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_sse2;
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_sse2;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_sse2;
         extern const uint * QT_FASTCALL qt_fetch_radial_gradient_sse2(uint *buffer, const Operator *op, const QSpanData *data,
                                                                       int y, int x, int length);
         qt_fetch_radial_gradient = qt_fetch_radial_gradient_sse2;
     }
 #ifdef QT_HAVE_SSSE3
     if (features & SSSE3) {
         extern void qt_blend_argb32_on_argb32_ssse3(uchar *destPixels, int dbpl,
                                                     const uchar *srcPixels, int sbpl,
                                                     int w, int h,
                                                     int const_alpha);
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_ssse3;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_ssse3;
     }
 #endif // SSSE3
 #endif // SSE2
 #ifdef QT_HAVE_SSE
     if (features & SSE) {
         functionForModeAsm = qt_functionForMode_SSE;
         functionForModeSolidAsm = qt_functionForModeSolid_SSE;
         qDrawHelper[QImage::Format_ARGB32_Premultiplied].blendColor = qt_blend_color_argb_sse;
 #ifdef QT_HAVE_3DNOW
         if (features & MMX3DNOW) {
             functionForModeAsm = qt_functionForMode_SSE3DNOW;
             functionForModeSolidAsm = qt_functionForModeSolid_SSE3DNOW;
             qDrawHelper[QImage::Format_ARGB32_Premultiplied].blendColor = qt_blend_color_argb_sse3dnow;
         }
 #endif // 3DNOW
 #ifdef QT_HAVE_SSE2
         if (features & SSE2) {
             extern void QT_FASTCALL comp_func_SourceOver_sse2(uint *destPixels,
                                                               const uint *srcPixels,
                                                               int length,
                                                               uint const_alpha);
             extern void QT_FASTCALL comp_func_solid_SourceOver_sse2(uint *destPixels, int length, uint color, uint const_alpha);
             extern void QT_FASTCALL comp_func_Plus_sse2(uint *dst, const uint *src, int length, uint const_alpha);
             extern void QT_FASTCALL comp_func_Source_sse2(uint *dst, const uint *src, int length, uint const_alpha);
             functionForModeAsm[0] = comp_func_SourceOver_sse2;
             functionForModeAsm[QPainter::CompositionMode_Source] = comp_func_Source_sse2;
             functionForModeAsm[QPainter::CompositionMode_Plus] = comp_func_Plus_sse2;
             functionForModeSolidAsm[0] = comp_func_solid_SourceOver_sse2;
         }
 #endif
     }
 #elif defined(QT_HAVE_SSE2)
     // this is the special case when SSE2 is usable but MMX/SSE is not usable (e.g.: Windows x64 + visual studio)
     if (features & SSE2) {
         functionForModeAsm = qt_functionForMode_onlySSE2;
         functionForModeSolidAsm = qt_functionForModeSolid_onlySSE2;
     }
 #endif
 #ifdef QT_HAVE_IWMMXT
     if (features & IWMMXT) {
         functionForModeAsm = qt_functionForMode_IWMMXT;
         functionForModeSolidAsm = qt_functionForModeSolid_IWMMXT;
         qDrawHelper[QImage::Format_ARGB32_Premultiplied].blendColor = qt_blend_color_argb_iwmmxt;
     }
 #endif // IWMMXT
 #if defined(QT_HAVE_ARM_SIMD)
     qBlendFunctions[QImage::Format_RGB32][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_arm_simd;
     qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_arm_simd;
     qBlendFunctions[QImage::Format_RGB32][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_arm_simd;
     qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_arm_simd;
 #elif defined(QT_HAVE_NEON)
     if (features & NEON) {
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_neon;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_RGB32] = qt_blend_rgb32_on_rgb32_neon;
         qBlendFunctions[QImage::Format_RGB32][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_neon;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_argb32_neon;
         qBlendFunctions[QImage::Format_RGB16][QImage::Format_ARGB32_Premultiplied] = qt_blend_argb32_on_rgb16_neon;
         qBlendFunctions[QImage::Format_ARGB32_Premultiplied][QImage::Format_RGB16] = qt_blend_rgb16_on_argb32_neon;
         qBlendFunctions[QImage::Format_RGB16][QImage::Format_RGB16] = qt_blend_rgb16_on_rgb16_neon;
         qScaleFunctions[QImage::Format_RGB16][QImage::Format_ARGB32_Premultiplied] = qt_scale_image_argb32_on_rgb16_neon;
         qScaleFunctions[QImage::Format_RGB16][QImage::Format_RGB16] = qt_scale_image_rgb16_on_rgb16_neon;
         qTransformFunctions[QImage::Format_RGB16][QImage::Format_ARGB32_Premultiplied] = qt_transform_image_argb32_on_rgb16_neon;
         qTransformFunctions[QImage::Format_RGB16][QImage::Format_RGB16] = qt_transform_image_rgb16_on_rgb16_neon;
         qDrawHelper[QImage::Format_RGB16].alphamapBlit = qt_alphamapblit_quint16_neon;
         functionForMode_C[QPainter::CompositionMode_SourceOver] = qt_blend_argb32_on_argb32_scanline_neon;
         functionForModeSolid_C[QPainter::CompositionMode_SourceOver] = comp_func_solid_SourceOver_neon;
         functionForMode_C[QPainter::CompositionMode_Plus] = comp_func_Plus_neon;
         destFetchProc[QImage::Format_RGB16] = qt_destFetchRGB16_neon;
         destStoreProc[QImage::Format_RGB16] = qt_destStoreRGB16_neon;
         qMemRotateFunctions[QImage::Format_RGB16][0] = qt_memrotate90_16_neon;
         qMemRotateFunctions[QImage::Format_RGB16][2] = qt_memrotate270_16_neon;
         qt_memfill32 = qt_memfill32_neon;
         extern const uint * QT_FASTCALL qt_fetch_radial_gradient_neon(uint *buffer, const Operator *op, const QSpanData *data,
                                                                       int y, int x, int length);
         qt_fetch_radial_gradient = qt_fetch_radial_gradient_neon;
     }
 #endif
     if (functionForModeSolidAsm) {
         const int destinationMode = QPainter::CompositionMode_Destination;
         functionForModeSolidAsm[destinationMode] = functionForModeSolid_C[destinationMode];
         // use the default qdrawhelper implementation for the
         // extended composition modes
         for (int mode = 12; mode < 24; ++mode)
             functionForModeSolidAsm[mode] = functionForModeSolid_C[mode];
         functionForModeSolid = functionForModeSolidAsm;
     }
     if (functionForModeAsm)
         functionForMode = functionForModeAsm;
     qt_build_pow_tables();
 }
qRadialDeterminant()
static qreal qRadialDeterminant (qreal a, qreal b, qreal c) inline static
Definition at line 384 of file qdrawhelper_p.h.
 {
     return (b * b) - (4 * a * c);
 }
qRed565()
int qRed565 (quint16 rgb) inline
Definition at line 2137 of file qdrawhelper_p.h.
{
     const int r = (rgb & 0xf800);
     return (r >> 8) | (r >> 13);
 }
qt_colorConvert() [1/7]
template<class DST , class SRC > DST qt_colorConvert (SRC color, DST dummy) inline
Definition at line 677 of file qdrawhelper_p.h.
Referenced by qrgb444::byte_mul(), and qt_colorConvert().
 {
     Q_UNUSED(dummy);
     return DST(color);
 }
qt_colorConvert() [2/7]
template<> quint32 qt_colorConvert (quint16 color, quint32 dummy) inline
Definition at line 685 of file qdrawhelper_p.h.
 {
     Q_UNUSED(dummy);
     const int r = (color & 0xf800);
     const int g = (color & 0x07e0);
     const int b = (color & 0x001f);
     const int tr = (r >> 8) | (r >> 13);
     const int tg = (g >> 3) | (g >> 9);
     const int tb = (b << 3) | (b >> 2);
     return qRgb(tr, tg, tb);
 }
qt_colorConvert() [3/7]
template<> quint16 qt_colorConvert (quint32 color, quint16 dummy) inline
Definition at line 699 of file qdrawhelper_p.h.
 {
     Q_UNUSED(dummy);
     const int r = qRed(color) << 8;
     const int g = qGreen(color) << 3;
     const int b = qBlue(color) >> 3;
     return (r & 0xf800) | (g & 0x07e0)| (b & 0x001f);
 }
qt_colorConvert() [4/7]
template<> qrgb888 qt_colorConvert (quint32 color, qrgb888 dummy) inline
Definition at line 1482 of file qdrawhelper_p.h.
 {
     Q_UNUSED(dummy);
     return qrgb888(color);
 }
qt_colorConvert() [5/7]
template<> quint32 qt_colorConvert (qrgb888 color, quint32 dummy) inline
Definition at line 1489 of file qdrawhelper_p.h.
 {
     Q_UNUSED(dummy);
     return quint32(color);
 }
qt_colorConvert() [6/7]
template<> quint24 qt_colorConvert (quint32 color, quint24 dummy) inline
Definition at line 1554 of file qdrawhelper_p.h.
 {
     Q_UNUSED(dummy);
     return quint24(color);
 }
qt_colorConvert() [7/7]
template<> quint18 qt_colorConvert (quint32 color, quint18 dummy) inline
Definition at line 1588 of file qdrawhelper_p.h.
 {
     Q_UNUSED(dummy);
     return quint18(color);
 }
qt_div_255()
Q_STATIC_INLINE_FUNCTION int qt_div_255 (int x)
Definition at line 2107 of file qdrawhelper_p.h.
Referenced by blendUntransformed_dest16(), blendUntransformed_dest24(), blendUntransformed_unaligned(), color_burn_op(), color_dodge_op(), darken_op(), difference_op(), QX11PixmapData::fromImage(), hardlight_op(), lighten_op(), QMacPixmapData::macSetAlphaChannel(), multiply_op(), overlay_op(), qt_intersect_spans(), rgbBlendPixel(), QImage::setAlphaChannel(), QOpenGLPaintEnginePrivate::setGLBrush(), and QOpenGLPaintEnginePrivate::setGLPen().
 { return (x + (x>>8) + 0x80) >> 8; }
qt_fetch_radial_gradient_template()
template<class RadialFetchFunc > const uint* QT_FASTCALL qt_fetch_radial_gradient_template (uint * buffer, const Operator * op, const QSpanData * data, int y, int x, int length)
Definition at line 390 of file qdrawhelper_p.h.
 {
     // avoid division by zero
     if (qFuzzyIsNull(op->radial.a)) {
         extern void (*qt_memfill32)(quint32 *dest, quint32 value, int count);
         qt_memfill32(buffer, 0, length);
         return buffer;
     }
     const uint *b = buffer;
     qreal rx = data->m21 * (y + qreal(0.5))
                + data->dx + data->m11 * (x + qreal(0.5));
     qreal ry = data->m22 * (y + qreal(0.5))
                + data->dy + data->m12 * (x + qreal(0.5));
     bool affine = !data->m13 && !data->m23;
     uint *end = buffer + length;
     if (affine) {
         rx -= data->gradient.radial.focal.x;
         ry -= data->gradient.radial.focal.y;
         qreal inv_a = 1 / qreal(2 * op->radial.a);
         const qreal delta_rx = data->m11;
         const qreal delta_ry = data->m12;
         qreal b = 2*(op->radial.dr*data->gradient.radial.focal.radius + rx * op->radial.dx + ry * op->radial.dy);
         qreal delta_b = 2*(delta_rx * op->radial.dx + delta_ry * op->radial.dy);
         const qreal b_delta_b = 2 * b * delta_b;
         const qreal delta_b_delta_b = 2 * delta_b * delta_b;
         const qreal bb = b * b;
         const qreal delta_bb = delta_b * delta_b;
         b *= inv_a;
         delta_b *= inv_a;
         const qreal rxrxryry = rx * rx + ry * ry;
         const qreal delta_rxrxryry = delta_rx * delta_rx + delta_ry * delta_ry;
         const qreal rx_plus_ry = 2*(rx * delta_rx + ry * delta_ry);
         const qreal delta_rx_plus_ry = 2 * delta_rxrxryry;
         inv_a *= inv_a;
         qreal det = (bb - 4 * op->radial.a * (op->radial.sqrfr - rxrxryry)) * inv_a;
         qreal delta_det = (b_delta_b + delta_bb + 4 * op->radial.a * (rx_plus_ry + delta_rxrxryry)) * inv_a;
         const qreal delta_delta_det = (delta_b_delta_b + 4 * op->radial.a * delta_rx_plus_ry) * inv_a;
         RadialFetchFunc::fetch(buffer, end, op, data, det, delta_det, delta_delta_det, b, delta_b);
     } else {
         qreal rw = data->m23 * (y + qreal(0.5))
                    + data->m33 + data->m13 * (x + qreal(0.5));
         while (buffer < end) {
             if (rw == 0) {
                 *buffer = 0;
             } else {
                 qreal invRw = 1 / rw;
                 qreal gx = rx * invRw - data->gradient.radial.focal.x;
                 qreal gy = ry * invRw - data->gradient.radial.focal.y;
                 qreal b  = 2*(op->radial.dr*data->gradient.radial.focal.radius + gx*op->radial.dx + gy*op->radial.dy);
                 qreal det = qRadialDeterminant(op->radial.a, b, op->radial.sqrfr - (gx*gx + gy*gy));
                 quint32 result = 0;
                 if (det >= 0) {
                     qreal detSqrt = qSqrt(det);
                     qreal s0 = (-b - detSqrt) * op->radial.inv2a;
                     qreal s1 = (-b + detSqrt) * op->radial.inv2a;
                     qreal s = qMax(s0, s1);
                     if (data->gradient.radial.focal.radius + op->radial.dr * s >= 0)
                         result = qt_gradient_pixel(&data->gradient, s);
                 }
                 *buffer = result;
             }
             rx += data->m11;
             ry += data->m12;
             rw += data->m13;
             ++buffer;
         }
     }
     return b;
 }
qt_gradient_clamp()
static uint qt_gradient_clamp (const QGradientData * data, int ipos) inline static
Definition at line 353 of file qdrawhelper_p.h.
Referenced by qt_gradient_pixel(), and qt_gradient_pixel_fixed().
 {
     if (ipos < 0 || ipos >= GRADIENT_STOPTABLE_SIZE) {
         if (data->spread == QGradient::RepeatSpread) {
             ipos = ipos % GRADIENT_STOPTABLE_SIZE;
             ipos = ipos < 0 ? GRADIENT_STOPTABLE_SIZE + ipos : ipos;
         } else if (data->spread == QGradient::ReflectSpread) {
             const int limit = GRADIENT_STOPTABLE_SIZE * 2;
             ipos = ipos % limit;
             ipos = ipos < 0 ? limit + ipos : ipos;
             ipos = ipos >= GRADIENT_STOPTABLE_SIZE ? limit - 1 - ipos : ipos;
         } else {
             if (ipos < 0)
                 ipos = 0;
             else if (ipos >= GRADIENT_STOPTABLE_SIZE)
                 ipos = GRADIENT_STOPTABLE_SIZE-1;
         }
     }
     Q_ASSERT(ipos >= 0);
     Q_ASSERT(ipos < GRADIENT_STOPTABLE_SIZE);
     return ipos;
 }
qt_gradient_pixel()
static uint qt_gradient_pixel (const QGradientData * data, qreal pos) inline static
Definition at line 378 of file qdrawhelper_p.h.
Referenced by RadialFetchPlain::fetch(), qt_fetch_conical_gradient(), and qt_fetch_linear_gradient().
 {
     int ipos = int(pos * (GRADIENT_STOPTABLE_SIZE - 1) + qreal(0.5));
     return data->colorTable[qt_gradient_clamp(data, ipos)];
 }
qt_memconvert() [1/2]
template<class DST , class SRC > void qt_memconvert (DST * dest, const SRC * src, int count) inline
Definition at line 1898 of file qdrawhelper_p.h.
Referenced by blend_sourceOver_4(), blendTiled(), blendTransformed(), blendTransformedBilinear(), blendTransformedTiled(), blendUntransformed_dest16(), convert_RGB_to_RGB16_inplace(), and qt_blend_rgb32_on_rgb32().
 {
     if (sizeof(DST) == 1) {
         while (count) {
             int n = 1;
             const SRC color = *src++;
             const DST dstColor = qt_colorConvert<DST, SRC>(color, 0);
             while (--count && (*src == color || dstColor == qt_colorConvert<DST, SRC>(*src, 0))) {
                 ++n;
                 ++src;
             }
             qt_memfill(dest, dstColor, n);
             dest += n;
         }
     } else {
         /* Duff's device */
         int n = (count + 7) / 8;
         switch (count & 0x07)
         {
         case 0: do { *dest++ = qt_colorConvert<DST, SRC>(*src++, 0);
             case 7:      *dest++ = qt_colorConvert<DST, SRC>(*src++, 0);
             case 6:      *dest++ = qt_colorConvert<DST, SRC>(*src++, 0);
             case 5:      *dest++ = qt_colorConvert<DST, SRC>(*src++, 0);
             case 4:      *dest++ = qt_colorConvert<DST, SRC>(*src++, 0);
             case 3:      *dest++ = qt_colorConvert<DST, SRC>(*src++, 0);
             case 2:      *dest++ = qt_colorConvert<DST, SRC>(*src++, 0);
             case 1:      *dest++ = qt_colorConvert<DST, SRC>(*src++, 0);
             } while (--n > 0);
         }
     }
 }
qt_memconvert() [2/2]
template<> void qt_memconvert (qrgb666 * dest, const quint32 * src, int count) inline
Definition at line 1951 of file qdrawhelper_p.h.
 {
     if (count < 3) {
         switch (count) {
         case 2: *dest++ = qrgb666(*src++);
         case 1: *dest = qrgb666(*src);
         }
         return;
     }
     const int align = (quintptr(dest) & 3);
     switch (align) {
     case 1: *dest++ = qrgb666(*src++); --count;
     case 2: *dest++ = qrgb666(*src++); --count;
     case 3: *dest++ = qrgb666(*src++); --count;
     }
     quint32 *dest32 = reinterpret_cast<quint32*>(dest);
     int sourceCount = count >> 2;
     while (sourceCount--) {
         dest32[0] = ((src[1] & 0x00000c00) << 20)
                     | ((src[1] & 0x000000fc) << 22)
                     | ((src[0] & 0x00fc0000) >> 6)
                     | ((src[0] & 0x0000fc00) >> 4)
                     |  ((src[0] & 0x000000fc) >> 2);
         dest32[1] = ((src[2] & 0x003c0000) << 10)
                     | ((src[2] & 0x0000fc00) << 12)
                     | ((src[2] & 0x000000fc) << 14)
                     | ((src[1] & 0x00fc0000) >> 14)
                     | ((src[1] & 0x0000f000) >> 12);
         dest32[2] = ((src[3] & 0x00fc0000) << 2)
                     | ((src[3] & 0x0000fc00) << 4)
                     | ((src[3] & 0x000000fc) << 6)
                     | ((src[2] & 0x00c00000) >> 22);
         dest32 += 3;
         src += 4;
     }
     dest = reinterpret_cast<qrgb666*>(dest32);
     switch (count & 3) {
     case 3: *dest++ = qrgb666(*src++);
     case 2: *dest++ = qrgb666(*src++);
     case 1: *dest = qrgb666(*src);
     }
 }
qt_memfill() [1/4]
template<class T > void qt_memfill (T * dest, T value, int count) inline
Definition at line 1861 of file qdrawhelper_p.h.
Referenced by blendColor(), qrgb444::byte_mul(), comp_func_solid_Source(), comp_func_solid_SourceOver(), qt_bitmapblit_template(), qt_blend_color_argb_x86(), qt_memconvert(), qt_memfill_template(), qt_rectfill(), and rasterop_solid_NotSource().
 {
     if (!count)
         return;
     int n = (count + 7) / 8;
     switch (count & 0x07)
     {
     case 0: do { *dest++ = value;
     case 7:      *dest++ = value;
     case 6:      *dest++ = value;
     case 5:      *dest++ = value;
     case 4:      *dest++ = value;
     case 3:      *dest++ = value;
     case 2:      *dest++ = value;
     case 1:      *dest++ = value;
     } while (--n > 0);
     }
 }
qt_memfill() [2/4]
template<> void qt_memfill (quint32 * dest, quint32 color, int count) inline
Definition at line 1843 of file qdrawhelper_p.h.
 {
     extern void (*qt_memfill32)(quint32 *dest, quint32 value, int count);
     qt_memfill32(dest, color, count);
 }
qt_memfill() [3/4]
template<> void qt_memfill (quint16 * dest, quint16 color, int count) inline
Definition at line 1849 of file qdrawhelper_p.h.
 {
     extern void (*qt_memfill16)(quint16 *dest, quint16 value, int count);
     qt_memfill16(dest, color, count);
 }
qt_memfill() [4/4]
template<> void qt_memfill (quint8 * dest, quint8 color, int count) inline
Definition at line 1855 of file qdrawhelper_p.h.
 {
     memset(dest, color, count);
 }
qt_rectconvert()
template<class DST , class SRC > void qt_rectconvert (DST * dest, const SRC * src, int x, int y, int width, int height, int dstStride, int srcStride) inline
Definition at line 2013 of file qdrawhelper_p.h.
Referenced by blit_template(), and qt_memfill16_setup().
 {
     char *d = (char*)(dest + x) + y * dstStride;
     const char *s = (char*)(src);
     for (int i = 0; i < height; ++i) {
         qt_memconvert<DST,SRC>((DST*)d, (const SRC*)s, width);
         d += dstStride;
         s += srcStride;
     }
 }
qt_rectcopy()
template<class T > void qt_rectcopy (T * dest, const T * src, int x, int y, int width, int height, int dstStride, int srcStride) inline
Definition at line 1999 of file qdrawhelper_p.h.
Referenced by QGLPixmapBlurFilter::processGL(), and QGLPixmapDropShadowFilter::processGL().
 {
     char *d = (char*)(dest + x) + y * dstStride;
     const char *s = (char*)(src);
     for (int i = 0; i < height; ++i) {
         ::memcpy(d, s, width * sizeof(T));
         d += dstStride;
         s += srcStride;
     }
 }
qt_rectfill()
template<class T > void qt_rectfill (T * dest, T value, int x, int y, int width, int height, int stride) inline
Definition at line 1882 of file qdrawhelper_p.h.
Referenced by solidFill_template().
 {
     char *d = reinterpret_cast<char*>(dest + x) + y * stride;
     if (uint(stride) == (width * sizeof(T))) {
         qt_memfill(reinterpret_cast<T*>(d), value, width * height);
     } else {
         for (int j = 0; j < height; ++j) {
             dest = reinterpret_cast<T*>(d);
             qt_memfill(dest, value, width);
             d += stride;
         }
     }
 }
rasterop_NotSource()
void QT_FASTCALL rasterop_NotSource (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 3054 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     while (length--)
         *dest++ = ~(*src++) | 0xff000000;
 }
rasterop_NotSourceAndDestination()
void QT_FASTCALL rasterop_NotSourceAndDestination (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 3075 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     while (length--) {
         *dest = (~(*src) & *dest) | 0xff000000;
         ++dest; ++src;
     }
 }
rasterop_NotSourceAndNotDestination()
void QT_FASTCALL rasterop_NotSourceAndNotDestination (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2985 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     while (length--) {
         *dest = (~(*src) & ~(*dest)) | 0xff000000;
         ++dest; ++src;
     }
 }
rasterop_NotSourceOrNotDestination()
void QT_FASTCALL rasterop_NotSourceOrNotDestination (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 3010 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     while (length--) {
         *dest = ~(*src) | ~(*dest) | 0xff000000;
         ++dest; ++src;
     }
 }
rasterop_NotSourceXorDestination()
void QT_FASTCALL rasterop_NotSourceXorDestination (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 3035 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     while (length--) {
         *dest = ((~(*src)) ^ (*dest)) | 0xff000000;
         ++dest; ++src;
     }
 }
rasterop_solid_NotSource()
void QT_FASTCALL rasterop_solid_NotSource (uint * dest, int length, uint color, uint const_alpha)
Definition at line 3047 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     qt_memfill(dest, ~color | 0xff000000, length);
 }
rasterop_solid_NotSourceAndDestination()
void QT_FASTCALL rasterop_solid_NotSourceAndDestination (uint * dest, int length, uint color, uint const_alpha)
Definition at line 3062 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     color = ~color | 0xff000000;
     while (length--) {
         *dest = color & *dest;
         ++dest;
     }
 }
rasterop_solid_NotSourceAndNotDestination()
void QT_FASTCALL rasterop_solid_NotSourceAndNotDestination (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2972 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     color = ~color;
     while (length--) {
         *dest = (color & ~(*dest)) | 0xff000000;
         ++dest;
     }
 }
rasterop_solid_NotSourceOrNotDestination()
void QT_FASTCALL rasterop_solid_NotSourceOrNotDestination (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2997 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     color = ~color | 0xff000000;
     while (length--) {
         *dest = color | ~(*dest);
         ++dest;
     }
 }
rasterop_solid_NotSourceXorDestination()
void QT_FASTCALL rasterop_solid_NotSourceXorDestination (uint * dest, int length, uint color, uint const_alpha)
Definition at line 3022 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     color = ~color & 0x00ffffff;
     while (length--) {
         *dest = color ^ (*dest);
         ++dest;
     }
 }
rasterop_solid_SourceAndDestination()
void QT_FASTCALL rasterop_solid_SourceAndDestination (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2926 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     color |= 0xff000000;
     while (length--)
         *dest++ &= color;
 }
rasterop_solid_SourceAndNotDestination()
void QT_FASTCALL rasterop_solid_SourceAndNotDestination (uint * dest, int length, uint color, uint const_alpha)
Definition at line 3087 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     while (length--) {
         *dest = (color & ~(*dest)) | 0xff000000;
         ++dest;
     }
 }
rasterop_solid_SourceOrDestination()
void QT_FASTCALL rasterop_solid_SourceOrDestination (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2906 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     while (length--)
         *dest++ |= color;
 }
rasterop_solid_SourceXorDestination()
void QT_FASTCALL rasterop_solid_SourceXorDestination (uint * dest, int length, uint color, uint const_alpha)
Definition at line 2949 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     color &= 0x00ffffff;
     while (length--)
         *dest++ ^= color;
 }
rasterop_SourceAndDestination()
void QT_FASTCALL rasterop_SourceAndDestination (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2937 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     while (length--) {
         *dest = (*src & *dest) | 0xff000000;
         ++dest; ++src;
     }
 }
rasterop_SourceAndNotDestination()
void QT_FASTCALL rasterop_SourceAndNotDestination (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 3099 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     while (length--) {
         *dest = (*src & ~(*dest)) | 0xff000000;
         ++dest; ++src;
     }
 }
rasterop_SourceOrDestination()
void QT_FASTCALL rasterop_SourceOrDestination (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2916 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     while (length--)
         *dest++ |= *src++;
 }
rasterop_SourceXorDestination()
void QT_FASTCALL rasterop_SourceXorDestination (uint * dest, const uint * src, int length, uint const_alpha)
Definition at line 2960 of file qdrawhelper.cpp.
Referenced by comp_func_Plus_one_pixel().
 {
     Q_UNUSED(const_alpha);
     while (length--) {
         *dest = (*src ^ *dest) | 0xff000000;
         ++dest; ++src;
     }
 }
Variable Documentation
AMASK
const uint AMASK = 0xff000000 static
Definition at line 89 of file qdrawhelper_p.h.
Referenced by comp_func_Plus_one_pixel(), and comp_func_Plus_one_pixel_const_alpha().
BMASK
const uint BMASK = 0x000000ff static
Definition at line 92 of file qdrawhelper_p.h.
Referenced by comp_func_Plus_one_pixel(), and comp_func_Plus_one_pixel_const_alpha().
GMASK
const uint GMASK = 0x0000ff00 static
Definition at line 91 of file qdrawhelper_p.h.
Referenced by comp_func_Plus_one_pixel(), and comp_func_Plus_one_pixel_const_alpha().
Q_PACKED
class qrgb444 Q_PACKED
Referenced by qrgb444::byte_mul().
qBlendFunctions
SrcOverBlendFunc qBlendFunctions[QImage::NImageFormats][QImage::NImageFormats]
Definition at line 1062 of file qblendfunctions.cpp.
Referenced by QRasterPaintEngine::drawImage(), and qInitDrawhelperAsm().
qDrawHelper
DrawHelper qDrawHelper[QImage::NImageFormats]
Definition at line 7377 of file qdrawhelper.cpp.
Referenced by QRasterBuffer::prepare().
qDrawHelperCallback
DrawHelper qDrawHelperCallback[QImage::NImageFormats]
Definition at line 7494 of file qdrawhelper.cpp.
Referenced by QRasterBuffer::prepare().
qMemRotateFunctions
MemRotateFunc qMemRotateFunctions[QImage::NImageFormats][3]
Definition at line 627 of file qmemrotate.cpp.
Referenced by QRasterPaintEngine::drawImage(), and qInitDrawhelperAsm().
qScaleFunctions
SrcOverScaleFunc qScaleFunctions[QImage::NImageFormats][QImage::NImageFormats]
Definition at line 770 of file qblendfunctions.cpp.
Referenced by QRasterPaintEngine::drawImage(), and qInitDrawhelperAsm().
qt_bayer_matrix
const uint qt_bayer_matrix[16][16]
Definition at line 2152 of file qdrawhelper_p.h.
Referenced by convert_RGB_to_Indexed8(), destStoreMono(), destStoreMonoLsb(), and dither_to_Mono().
qTransformFunctions
SrcOverTransformFunc qTransformFunctions[QImage::NImageFormats][QImage::NImageFormats]
Definition at line 1353 of file qblendfunctions.cpp.
Referenced by QRasterPaintEngine::drawImage(), and qInitDrawhelperAsm().
RMASK
const uint RMASK = 0x00ff0000 static
Definition at line 90 of file qdrawhelper_p.h.
Referenced by comp_func_Plus_one_pixel(), and comp_func_Plus_one_pixel_const_alpha().