Qt 4.8: /src/gui/painting/qdrawutil.cpp File Reference
qdrawutil.cpp File Reference
#include "qdrawutil.h"
#include "qbitmap.h"
#include "qpixmapcache.h"
#include "qapplication.h"
#include "qpainter.h"
#include "qpalette.h"
#include <private/qpaintengineex_p.h>
#include <qvarlengtharray.h>
#include <qmath.h>
#include <private/qstylehelper_p.h>
Typedefs
typedef QVarLengthArray< QRectF, 16 > QRectFArray
Functions
void qDrawBorderPixmap (QPainter *painter, const QRect &targetRect, const QMargins &targetMargins, const QPixmap &pixmap, const QRect &sourceRect, const QMargins &sourceMargins, const QTileRules &rules, QDrawBorderPixmap::DrawingHints hints)
Draws the indicated sourceRect rectangle from the given pixmap into the given targetRect rectangle, using the given painter.
void qDrawPlainRect (QPainter *p, int x, int y, int w, int h, const QColor &c, int lineWidth, const QBrush *fill)
void qDrawPlainRect (QPainter *p, const QRect &r, const QColor &c, int lineWidth, const QBrush *fill)
void qDrawShadeLine (QPainter *p, int x1, int y1, int x2, int y2, const QPalette &pal, bool sunken, int lineWidth, int midLineWidth)
void qDrawShadeLine (QPainter *p, const QPoint &p1, const QPoint &p2, const QPalette &pal, bool sunken, int lineWidth, int midLineWidth)
void qDrawShadePanel (QPainter *p, int x, int y, int w, int h, const QPalette &pal, bool sunken, int lineWidth, const QBrush *fill)
void qDrawShadePanel (QPainter *p, const QRect &r, const QPalette &pal, bool sunken, int lineWidth, const QBrush *fill)
void qDrawShadeRect (QPainter *p, int x, int y, int w, int h, const QPalette &pal, bool sunken, int lineWidth, int midLineWidth, const QBrush *fill)
void qDrawShadeRect (QPainter *p, const QRect &r, const QPalette &pal, bool sunken, int lineWidth, int midLineWidth, const QBrush *fill)
void qDrawWinButton (QPainter *p, int x, int y, int w, int h, const QPalette &pal, bool sunken, const QBrush *fill)
void qDrawWinButton (QPainter *p, const QRect &r, const QPalette &pal, bool sunken, const QBrush *fill)
void qDrawWinPanel (QPainter *p, int x, int y, int w, int h, const QPalette &pal, bool sunken, const QBrush *fill)
void qDrawWinPanel (QPainter *p, const QRect &r, const QPalette &pal, bool sunken, const QBrush *fill)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the Windows-style panel at the rectangle specified by rect using the given painter with a line width of 2 pixels.
static void qDrawWinShades (QPainter *p, int x, int y, int w, int h, const QColor &c1, const QColor &c2, const QColor &c3, const QColor &c4, const QBrush *fill)
This function draws a rectangle with two pixel line width.
Typedef Documentation
QRectFArray
typedef QVarLengthArray<QRectF, 16> QRectFArray
Definition at line 1086 of file qdrawutil.cpp.
Function Documentation
qDrawBorderPixmap()
void qDrawBorderPixmap (QPainter * painter, const QRect & targetRect, const QMargins & targetMargins, const QPixmap & pixmap, const QRect & sourceRect, const QMargins & sourceMargins, const QTileRules & rules, QDrawBorderPixmap::DrawingHints hints)
Draws the indicated sourceRect rectangle from the given pixmap into the given targetRect rectangle, using the given painter.
Since
4.6
The pixmap will be split into nine segments according to the given targetMargins and sourceMargins structures. Finally, the pixmap will be drawn according to the given rules.
This function is used to draw a scaled pixmap, similar to CSS3 border-images
See also
Qt::TileRule, QTileRules, QMargins
Definition at line 1106 of file qdrawutil.cpp.
Referenced by QRenderRule::drawBorderImage(), QDeclarativeRectangle::drawRect(), and QDeclarativeBorderImage::paint().
 {
     if (!painter->isActive()) {
         qWarning("qDrawBorderPixmap: Painter not active");
         return;
     }
     QRectFArray sourceData[2];
     QRectFArray targetData[2];
     // source center
     const int sourceCenterTop = sourceRect.top() + sourceMargins.top();
     const int sourceCenterLeft = sourceRect.left() + sourceMargins.left();
     const int sourceCenterBottom = sourceRect.bottom() - sourceMargins.bottom() + 1;
     const int sourceCenterRight = sourceRect.right() - sourceMargins.right() + 1;
     const int sourceCenterWidth = sourceCenterRight - sourceCenterLeft;
     const int sourceCenterHeight = sourceCenterBottom - sourceCenterTop;
     // target center
     const int targetCenterTop = targetRect.top() + targetMargins.top();
     const int targetCenterLeft = targetRect.left() + targetMargins.left();
     const int targetCenterBottom = targetRect.bottom() - targetMargins.bottom() + 1;
     const int targetCenterRight = targetRect.right() - targetMargins.right() + 1;
     const int targetCenterWidth = targetCenterRight - targetCenterLeft;
     const int targetCenterHeight = targetCenterBottom - targetCenterTop;
     QVarLengthArray<qreal, 16> xTarget; // x-coordinates of target rectangles
     QVarLengthArray<qreal, 16> yTarget; // y-coordinates of target rectangles
     int columns = 3;
     int rows = 3;
     if (rules.horizontal != Qt::StretchTile && sourceCenterWidth != 0)
         columns = qMax(3, 2 + qCeil(targetCenterWidth / qreal(sourceCenterWidth)));
     if (rules.vertical != Qt::StretchTile && sourceCenterHeight != 0)
         rows = qMax(3, 2 + qCeil(targetCenterHeight / qreal(sourceCenterHeight)));
     xTarget.resize(columns + 1);
     yTarget.resize(rows + 1);
     bool oldAA = painter->testRenderHint(QPainter::Antialiasing);
     if (painter->paintEngine()->type() != QPaintEngine::OpenGL
         && painter->paintEngine()->type() != QPaintEngine::OpenGL2
         && oldAA && painter->combinedTransform().type() != QTransform::TxNone) {
         painter->setRenderHint(QPainter::Antialiasing, false);
     }
     xTarget[0] = targetRect.left();
     xTarget[1] = targetCenterLeft;
     xTarget[columns - 1] = targetCenterRight;
     xTarget[columns] = targetRect.left() + targetRect.width();
     yTarget[0] = targetRect.top();
     yTarget[1] = targetCenterTop;
     yTarget[rows - 1] = targetCenterBottom;
     yTarget[rows] = targetRect.top() + targetRect.height();
     qreal dx = targetCenterWidth;
     qreal dy = targetCenterHeight;
     switch (rules.horizontal) {
     case Qt::StretchTile:
         dx = targetCenterWidth;
         break;
     case Qt::RepeatTile:
         dx = sourceCenterWidth;
         break;
     case Qt::RoundTile:
         dx = targetCenterWidth / qreal(columns - 2);
         break;
     }
     for (int i = 2; i < columns - 1; ++i)
         xTarget[i] = xTarget[i - 1] + dx;
     switch (rules.vertical) {
     case Qt::StretchTile:
         dy = targetCenterHeight;
         break;
     case Qt::RepeatTile:
         dy = sourceCenterHeight;
         break;
     case Qt::RoundTile:
         dy = targetCenterHeight / qreal(rows - 2);
         break;
     }
     for (int i = 2; i < rows - 1; ++i)
         yTarget[i] = yTarget[i - 1] + dy;
     // corners
     if (targetMargins.top() > 0 && targetMargins.left() > 0 && sourceMargins.top() > 0 && sourceMargins.left() > 0) { // top left
         int index = bool(hints & QDrawBorderPixmap::OpaqueTopLeft);
         sourceData[index].append(QRectF(sourceRect.topLeft(), QSizeF(sourceMargins.left(), sourceMargins.top())));
         targetData[index].append(QRectF(QPointF(xTarget[0], yTarget[0]), QPointF(xTarget[1], yTarget[1])));
     }
     if (targetMargins.top() > 0 && targetMargins.right() > 0 && sourceMargins.top() > 0 && sourceMargins.right() > 0) { // top right
         int index = bool(hints & QDrawBorderPixmap::OpaqueTopRight);
         sourceData[index].append(QRectF(QPointF(sourceCenterRight, sourceRect.top()), QSizeF(sourceMargins.right(), sourceMargins.top())));
         targetData[index].append(QRectF(QPointF(xTarget[columns-1], yTarget[0]), QPointF(xTarget[columns], yTarget[1])));
     }
     if (targetMargins.bottom() > 0 && targetMargins.left() > 0 && sourceMargins.bottom() > 0 && sourceMargins.left() > 0) { // bottom left
         int index = bool(hints & QDrawBorderPixmap::OpaqueBottomLeft);
         sourceData[index].append(QRectF(QPointF(sourceRect.left(), sourceCenterBottom), QSizeF(sourceMargins.left(), sourceMargins.bottom())));
         targetData[index].append(QRectF(QPointF(xTarget[0], yTarget[rows - 1]), QPointF(xTarget[1], yTarget[rows])));
     }
     if (targetMargins.bottom() > 0 && targetMargins.right() > 0 && sourceMargins.bottom() > 0 && sourceMargins.right() > 0) { // bottom right
         int index = bool(hints & QDrawBorderPixmap::OpaqueBottomRight);
         sourceData[index].append(QRectF(QPointF(sourceCenterRight, sourceCenterBottom), QSizeF(sourceMargins.right(), sourceMargins.bottom())));
         targetData[index].append(QRectF(QPointF(xTarget[columns - 1], yTarget[rows - 1]), QPointF(xTarget[columns], yTarget[rows])));
     }
     // horizontal edges
     if (targetCenterWidth > 0 && sourceCenterWidth > 0) {
         if (targetMargins.top() > 0 && sourceMargins.top() > 0) { // top
             int index = bool(hints & QDrawBorderPixmap::OpaqueTop);
             for (int i = 1; i < columns - 1; ++i) {
                 if (rules.horizontal == Qt::RepeatTile && i == columns - 2) {
                     sourceData[index].append(QRectF(QPointF(sourceCenterLeft, sourceRect.top()), QSizeF(xTarget[i + 1] - xTarget[i], sourceMargins.top())));
                 } else {
                     sourceData[index].append(QRectF(QPointF(sourceCenterLeft, sourceRect.top()), QSizeF(sourceCenterWidth, sourceMargins.top())));
                 }
                 targetData[index].append(QRectF(QPointF(xTarget[i], yTarget[0]), QPointF(xTarget[i + 1], yTarget[1])));
             }
         }
         if (targetMargins.bottom() > 0 && sourceMargins.bottom() > 0) { // bottom
             int index = bool(hints & QDrawBorderPixmap::OpaqueBottom);
             for (int i = 1; i < columns - 1; ++i) {
                 if (rules.horizontal == Qt::RepeatTile && i == columns - 2) {
                     sourceData[index].append(QRectF(QPointF(sourceCenterLeft, sourceCenterBottom), QSizeF(xTarget[i + 1] - xTarget[i], sourceMargins.bottom())));
                 } else {
                     sourceData[index].append(QRectF(QPointF(sourceCenterLeft, sourceCenterBottom), QSizeF(sourceCenterWidth, sourceMargins.bottom())));
                 }
                 targetData[index].append(QRectF(QPointF(xTarget[i], yTarget[rows - 1]), QPointF(xTarget[i + 1], yTarget[rows])));
             }
         }
     }
     // vertical edges
     if (targetCenterHeight > 0 && sourceCenterHeight > 0) {
         if (targetMargins.left() > 0 && sourceMargins.left() > 0) { // left
             int index = bool(hints & QDrawBorderPixmap::OpaqueLeft);
             for (int i = 1; i < rows - 1; ++i) {
                 if (rules.vertical == Qt::RepeatTile && i == rows - 2) {
                     sourceData[index].append(QRectF(QPointF(sourceRect.left(), sourceCenterTop), QSizeF(sourceMargins.left(), yTarget[i + 1] - yTarget[i])));
                 } else {
                     sourceData[index].append(QRectF(QPointF(sourceRect.left(), sourceCenterTop), QSizeF(sourceMargins.left(), sourceCenterHeight)));
                 }
                 targetData[index].append(QRectF(QPointF(xTarget[0], yTarget[i]), QPointF(xTarget[1], yTarget[i + 1])));
             }
         }
         if (targetMargins.right() > 0 && sourceMargins.right() > 0) { // right
             int index = bool(hints & QDrawBorderPixmap::OpaqueRight);
             for (int i = 1; i < rows - 1; ++i) {
                 if (rules.vertical == Qt::RepeatTile && i == rows - 2) {
                     sourceData[index].append(QRectF(QPointF(sourceCenterRight, sourceCenterTop), QSizeF(sourceMargins.right(), yTarget[i + 1] - yTarget[i])));
                 } else {
                     sourceData[index].append(QRectF(QPointF(sourceCenterRight, sourceCenterTop), QSizeF(sourceMargins.right(), sourceCenterHeight)));
                 }
                 targetData[index].append(QRectF(QPointF(xTarget[columns - 1], yTarget[i]), QPointF(xTarget[columns], yTarget[i + 1])));
             }
         }
     }
     // center
     if (targetCenterWidth > 0 && targetCenterHeight > 0 && sourceCenterWidth > 0 && sourceCenterHeight > 0) {
         int index = bool(hints & QDrawBorderPixmap::OpaqueCenter);
         for (int j = 1; j < rows - 1; ++j) {
             qreal sourceHeight = (rules.vertical == Qt::RepeatTile && j == rows - 2) ? yTarget[j + 1] - yTarget[j] : sourceCenterHeight;
             for (int i = 1; i < columns - 1; ++i) {
                 qreal sourceWidth = (rules.horizontal == Qt::RepeatTile && i == columns - 2) ? xTarget[i + 1] - xTarget[i] : sourceCenterWidth;
                 sourceData[index].append(QRectF(QPointF(sourceCenterLeft, sourceCenterTop), QSizeF(sourceWidth, sourceHeight)));
                 targetData[index].append(QRectF(QPointF(xTarget[i], yTarget[j]), QPointF(xTarget[i + 1], yTarget[j + 1])));
             }
         }
     }
     for (int i = 0; i < 2; ++i) {
         if (sourceData[i].size())
             painter->drawPixmapFragments(targetData[i].data(), sourceData[i].data(), sourceData[i].size(), pixmap, i == 1 ? QPainter::OpaqueHint : QPainter::PixmapFragmentHint(0));
     }
     if (oldAA)
         painter->setRenderHint(QPainter::Antialiasing, true);
 }
qDrawPlainRect() [1/2]
void qDrawPlainRect (QPainter * p, int x, int y, int w, int h, const QColor & c, int lineWidth, const QBrush * fill)
Definition at line 511 of file qdrawutil.cpp.
Referenced by QWindowsMobileStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsCEStyle::drawControl(), QWindowsMobileStyle::drawControl(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), and qDrawPlainRect().
 {
     if (w == 0 || h == 0)
         return;
     if (!(w > 0 && h > 0 && lineWidth >= 0)) {
         qWarning("qDrawPlainRect: Invalid parameters");
     }
     QPen   oldPen   = p->pen();
     QBrush oldBrush = p->brush();
     p->setPen(c);
     p->setBrush(Qt::NoBrush);
     for (int i=0; i<lineWidth; i++)
         p->drawRect(x+i, y+i, w-i*2 - 1, h-i*2 - 1);
     if (fill) {                                // fill with fill color
         p->setPen(Qt::NoPen);
         p->setBrush(*fill);
         p->drawRect(x+lineWidth, y+lineWidth, w-lineWidth*2, h-lineWidth*2);
     }
     p->setPen(oldPen);
     p->setBrush(oldBrush);
 }
qDrawPlainRect() [2/2]
void qDrawPlainRect (QPainter * p, const QRect & r, const QColor & c, int lineWidth, const QBrush * fill)
Definition at line 726 of file qdrawutil.cpp.
 {
     qDrawPlainRect(p, r.x(), r.y(), r.width(), r.height(), c,
                     lineWidth, fill);
 }
qDrawShadeLine() [1/2]
void qDrawShadeLine (QPainter * p, int x1, int y1, int x2, int y2, const QPalette & pal, bool sunken, int lineWidth, int midLineWidth)
Definition at line 93 of file qdrawutil.cpp.
Referenced by QMotifStyle::drawComplexControl(), QCommonStyle::drawControl(), QCommonStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), and qDrawShadeLine().
 {
     if (!(p && lineWidth >= 0 && midLineWidth >= 0))        {
         qWarning("qDrawShadeLine: Invalid parameters");
         return;
     }
     int tlw = lineWidth*2 + midLineWidth;        // total line width
     QPen oldPen = p->pen();                        // save pen
     if (sunken)
         p->setPen(pal.color(QPalette::Dark));
     else
         p->setPen(pal.light().color());
     QPolygon a;
     int i;
     if (y1 == y2) {                                // horizontal line
         int y = y1 - tlw/2;
         if (x1 > x2) {                        // swap x1 and x2
             int t = x1;
             x1 = x2;
             x2 = t;
         }
         x2--;
         for (i=0; i<lineWidth; i++) {                // draw top shadow
             a.setPoints(3, x1+i, y+tlw-1-i,
                          x1+i, y+i,
                          x2-i, y+i);
             p->drawPolyline(a);
         }
         if (midLineWidth > 0) {
             p->setPen(pal.mid().color());
             for (i=0; i<midLineWidth; i++)        // draw lines in the middle
                 p->drawLine(x1+lineWidth, y+lineWidth+i,
                              x2-lineWidth, y+lineWidth+i);
         }
         if (sunken)
             p->setPen(pal.light().color());
         else
             p->setPen(pal.dark().color());
         for (i=0; i<lineWidth; i++) {                // draw bottom shadow
             a.setPoints(3, x1+i, y+tlw-i-1,
                          x2-i, y+tlw-i-1,
                          x2-i, y+i+1);
             p->drawPolyline(a);
         }
     }
     else if (x1 == x2) {                        // vertical line
         int x = x1 - tlw/2;
         if (y1 > y2) {                        // swap y1 and y2
             int t = y1;
             y1 = y2;
             y2 = t;
         }
         y2--;
         for (i=0; i<lineWidth; i++) {                // draw left shadow
             a.setPoints(3, x+i, y2,
                          x+i, y1+i,
                          x+tlw-1, y1+i);
             p->drawPolyline(a);
         }
         if (midLineWidth > 0) {
             p->setPen(pal.mid().color());
             for (i=0; i<midLineWidth; i++)        // draw lines in the middle
                 p->drawLine(x+lineWidth+i, y1+lineWidth, x+lineWidth+i, y2);
         }
         if (sunken)
             p->setPen(pal.light().color());
         else
             p->setPen(pal.dark().color());
         for (i=0; i<lineWidth; i++) {                // draw right shadow
             a.setPoints(3, x+lineWidth, y2-i,
                          x+tlw-i-1, y2-i,
                          x+tlw-i-1, y1+lineWidth);
             p->drawPolyline(a);
         }
     }
     p->setPen(oldPen);
 }
qDrawShadeLine() [2/2]
void qDrawShadeLine (QPainter * p, const QPoint & p1, const QPoint & p2, const QPalette & pal, bool sunken, int lineWidth, int midLineWidth)
Definition at line 568 of file qdrawutil.cpp.
 {
     qDrawShadeLine(p, p1.x(), p1.y(), p2.x(), p2.y(), pal, sunken,
                     lineWidth, midLineWidth);
 }
qDrawShadePanel() [1/2]
void qDrawShadePanel (QPainter * p, int x, int y, int w, int h, const QPalette & pal, bool sunken, int lineWidth, const QBrush * fill)
Definition at line 303 of file qdrawutil.cpp.
Referenced by QMotifStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsCEStyle::drawControl(), QCDEStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QStyleSheetStyle::drawControl(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QDecorationDefault::paint(), QColorLuminancePicker::paintEvent(), and qDrawShadePanel().
 {
     if (w == 0 || h == 0)
         return;
     if (!(w > 0 && h > 0 && lineWidth >= 0)) {
         qWarning("qDrawShadePanel: Invalid parameters");
     }
     QColor shade = pal.dark().color();
     QColor light = pal.light().color();
     if (fill) {
         if (fill->color() == shade)
             shade = pal.shadow().color();
         if (fill->color() == light)
             light = pal.midlight().color();
     }
     QPen oldPen = p->pen();                        // save pen
     QVector<QLineF> lines;
     lines.reserve(2*lineWidth);
     if (sunken)
         p->setPen(shade);
     else
         p->setPen(light);
     int x1, y1, x2, y2;
     int i;
     x1 = x;
     y1 = y2 = y;
     x2 = x+w-2;
     for (i=0; i<lineWidth; i++) {                // top shadow
         lines << QLineF(x1, y1++, x2--, y2++);
     }
     x2 = x1;
     y1 = y+h-2;
     for (i=0; i<lineWidth; i++) {                // left shado
         lines << QLineF(x1++, y1, x2++, y2--);
     }
     p->drawLines(lines);
     lines.clear();
     if (sunken)
         p->setPen(light);
     else
         p->setPen(shade);
     x1 = x;
     y1 = y2 = y+h-1;
     x2 = x+w-1;
     for (i=0; i<lineWidth; i++) {                // bottom shadow
         lines << QLineF(x1++, y1--, x2, y2--);
     }
     x1 = x2;
     y1 = y;
     y2 = y+h-lineWidth-1;
     for (i=0; i<lineWidth; i++) {                // right shadow
         lines << QLineF(x1--, y1++, x2--, y2);
     }
     p->drawLines(lines);
     if (fill)                                // fill with fill color
         p->fillRect(x+lineWidth, y+lineWidth, w-lineWidth*2, h-lineWidth*2, *fill);
     p->setPen(oldPen);                        // restore pen
 }
qDrawShadePanel() [2/2]
void qDrawShadePanel (QPainter * p, const QRect & r, const QPalette & pal, bool sunken, int lineWidth, const QBrush * fill)
Definition at line 640 of file qdrawutil.cpp.
 {
     qDrawShadePanel(p, r.x(), r.y(), r.width(), r.height(), pal, sunken,
                      lineWidth, fill);
 }
qDrawShadeRect() [1/2]
void qDrawShadeRect (QPainter * p, int x, int y, int w, int h, const QPalette & pal, bool sunken, int lineWidth, int midLineWidth, const QBrush * fill)
Definition at line 204 of file qdrawutil.cpp.
Referenced by QCommonStyle::drawControl(), QWindowsStyle::drawControl(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), and qDrawShadeRect().
 {
     if (w == 0 || h == 0)
         return;
     if (! (w > 0 && h > 0 && lineWidth >= 0 && midLineWidth >= 0)) {
         qWarning("qDrawShadeRect: Invalid parameters");
         return;
     }
     QPen oldPen = p->pen();
     if (sunken)
         p->setPen(pal.dark().color());
     else
         p->setPen(pal.light().color());
     int x1=x, y1=y, x2=x+w-1, y2=y+h-1;
     if (lineWidth == 1 && midLineWidth == 0) {// standard shade rectangle
         p->drawRect(x1, y1, w-2, h-2);
         if (sunken)
             p->setPen(pal.light().color());
         else
             p->setPen(pal.dark().color());
         QLineF lines[4] = { QLineF(x1+1, y1+1, x2-2, y1+1),
                             QLineF(x1+1, y1+2, x1+1, y2-2),
                             QLineF(x1, y2, x2, y2),
                             QLineF(x2,y1, x2,y2-1) };
         p->drawLines(lines, 4);              // draw bottom/right lines
     } else {                                        // more complicated
         int m = lineWidth+midLineWidth;
         int i, j=0, k=m;
         for (i=0; i<lineWidth; i++) {                // draw top shadow
             QLineF lines[4] = { QLineF(x1+i, y2-i, x1+i, y1+i),
                                 QLineF(x1+i, y1+i, x2-i, y1+i),
                                 QLineF(x1+k, y2-k, x2-k, y2-k),
                                 QLineF(x2-k, y2-k, x2-k, y1+k) };
             p->drawLines(lines, 4);
             k++;
         }
         p->setPen(pal.mid().color());
         j = lineWidth*2;
         for (i=0; i<midLineWidth; i++) {        // draw lines in the middle
             p->drawRect(x1+lineWidth+i, y1+lineWidth+i, w-j-1, h-j-1);
             j += 2;
         }
         if (sunken)
             p->setPen(pal.light().color());
         else
             p->setPen(pal.dark().color());
         k = m;
         for (i=0; i<lineWidth; i++) {                // draw bottom shadow
             QLineF lines[4] = { QLineF(x1+1+i, y2-i, x2-i, y2-i),
                                 QLineF(x2-i, y2-i, x2-i, y1+i+1),
                                 QLineF(x1+k, y2-k, x1+k, y1+k),
                                 QLineF(x1+k, y1+k, x2-k, y1+k) };
             p->drawLines(lines, 4);
             k++;
         }
     }
     if (fill) {
         QBrush oldBrush = p->brush();
         int tlw = lineWidth + midLineWidth;
         p->setPen(Qt::NoPen);
         p->setBrush(*fill);
         p->drawRect(x+tlw, y+tlw, w-2*tlw, h-2*tlw);
         p->setBrush(oldBrush);
     }
     p->setPen(oldPen);                        // restore pen
 }
qDrawShadeRect() [2/2]
void qDrawShadeRect (QPainter * p, const QRect & r, const QPalette & pal, bool sunken, int lineWidth, int midLineWidth, const QBrush * fill)
Definition at line 605 of file qdrawutil.cpp.
 {
     qDrawShadeRect(p, r.x(), r.y(), r.width(), r.height(), pal, sunken,
                     lineWidth, midLineWidth, fill);
 }
qDrawWinButton() [1/2]
void qDrawWinButton (QPainter * p, int x, int y, int w, int h, const QPalette & pal, bool sunken, const QBrush * fill)
Definition at line 435 of file qdrawutil.cpp.
Referenced by QWindowsStyle::drawComplexControl(), QWindowsStyle::drawControl(), QWindowsMobileStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), and qDrawWinButton().
 {
     if (sunken)
         qDrawWinShades(p, x, y, w, h,
                        pal.shadow().color(), pal.light().color(), pal.dark().color(),
                        pal.button().color(), fill);
     else
         qDrawWinShades(p, x, y, w, h,
                        pal.light().color(), pal.shadow().color(), pal.button().color(),
                        pal.dark().color(), fill);
 }
qDrawWinButton() [2/2]
void qDrawWinButton (QPainter * p, const QRect & r, const QPalette & pal, bool sunken, const QBrush * fill)
Definition at line 669 of file qdrawutil.cpp.
 {
     qDrawWinButton(p, r.x(), r.y(), r.width(), r.height(), pal, sunken, fill);
 }
qDrawWinPanel() [1/2]
void qDrawWinPanel (QPainter * p, int x, int y, int w, int h, const QPalette & pal, bool sunken, const QBrush * fill)
Definition at line 475 of file qdrawutil.cpp.
Referenced by QCommonStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QCommonStyle::drawControl(), QCommonStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QDecorationDefault::paint(), QDecorationWindows::paintButton(), QDecorationDefault::paintButton(), and qDrawWinPanel().
 {
     if (sunken)
         qDrawWinShades(p, x, y, w, h,
                         pal.dark().color(), pal.light().color(), pal.shadow().color(),
                        pal.midlight().color(), fill);
     else
         qDrawWinShades(p, x, y, w, h,
                        pal.light().color(), pal.shadow().color(), pal.midlight().color(),
                        pal.dark().color(), fill);
 }
qDrawWinPanel() [2/2]
void qDrawWinPanel (QPainter * painter, const QRect & rect, const QPalette & palette, bool sunken, const QBrush * fill)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the Windows-style panel at the rectangle specified by rect using the given painter with a line width of 2 pixels.
The button's interior is filled with the fill brush unless fill is 0.
The given palette specifies the shading colors. The panel appears sunken if sunken is true, otherwise raised.
Warning
This function does not look at QWidget::style() or QApplication::style(). Use the drawing functions in QStyle to make widgets that follow the current GUI style.
Alternatively you can use a QFrame widget and apply the QFrame::setFrameStyle() function to display a shaded panel:
QFrame frame:
frame.setFrameStyle(QFrame::WinPanel | QFrame::Raised);
See also
qDrawShadePanel(), qDrawWinButton(), QStyle
Definition at line 699 of file qdrawutil.cpp.
 {
     qDrawWinPanel(p, r.x(), r.y(), r.width(), r.height(), pal, sunken, fill);
 }
qDrawWinShades()
static void qDrawWinShades (QPainter * p, int x, int y, int w, int h, const QColor & c1, const QColor & c2, const QColor & c3, const QColor & c4, const QBrush * fill) static
This function draws a rectangle with two pixel line width.
Warning
This function is not part of the public interface.
It is called from qDrawWinButton() and qDrawWinPanel().
c1..c4 and fill are used:
1 1 1 1 1 2 1 3 3 3 4 2 1 3 F F 4 2 1 3 F F 4 2 1 4 4 4 4 2 2 2 2 2 2 2
Definition at line 384 of file qdrawutil.cpp.
Referenced by qDrawWinButton(), and qDrawWinPanel().
 {
     if (w < 2 || h < 2)                        // can't do anything with that
         return;
     QPen oldPen = p->pen();
     QPoint a[3] = { QPoint(x, y+h-2), QPoint(x, y), QPoint(x+w-2, y) };
     p->setPen(c1);
     p->drawPolyline(a, 3);
     QPoint b[3] = { QPoint(x, y+h-1), QPoint(x+w-1, y+h-1), QPoint(x+w-1, y) };
     p->setPen(c2);
     p->drawPolyline(b, 3);
     if (w > 4 && h > 4) {
         QPoint c[3] = { QPoint(x+1, y+h-3), QPoint(x+1, y+1), QPoint(x+w-3, y+1) };
         p->setPen(c3);
         p->drawPolyline(c, 3);
         QPoint d[3] = { QPoint(x+1, y+h-2), QPoint(x+w-2, y+h-2), QPoint(x+w-2, y+1) };
         p->setPen(c4);
         p->drawPolyline(d, 3);
         if (fill)
             p->fillRect(QRect(x+2, y+2, w-4, h-4), *fill);
     }
     p->setPen(oldPen);
 }