Qt 4.8: /src/corelib/tools/qeasingcurve.cpp File Reference
qeasingcurve.cpp File Reference
#include "qeasingcurve.h"
#include <QtCore/qdebug.h>
#include <QtCore/qstring.h>
#include <QtCore/qdatastream.h>
#include "../../3rdparty/easing/easing.cpp"
Classes
struct BackEase
struct BounceEase
struct ElasticEase
class QEasingCurveFunction
class QEasingCurvePrivate
Functions
static QEasingCurve::EasingFunction curveToFunc (QEasingCurve::Type curve)
static QEasingCurveFunction * curveToFunctionObject (QEasingCurve::Type type)
static bool isConfigFunction (QEasingCurve::Type type)
QDebug operator<< (QDebug debug, const QEasingCurve &item)
QDataStream & operator<< (QDataStream &stream, const QEasingCurve &easing)
QDataStream & operator>> (QDataStream &stream, QEasingCurve &easing)
Function Documentation
curveToFunc()
static QEasingCurve::EasingFunction curveToFunc (QEasingCurve::Type curve) static
Definition at line 490 of file qeasingcurve.cpp.
Referenced by QEasingCurvePrivate::setType_helper().
 {
     switch(curve) {
     case QEasingCurve::Linear:
         return &easeNone;
     case QEasingCurve::InQuad:
         return &easeInQuad;
     case QEasingCurve::OutQuad:
         return &easeOutQuad;
     case QEasingCurve::InOutQuad:
         return &easeInOutQuad;
     case QEasingCurve::OutInQuad:
         return &easeOutInQuad;
     case QEasingCurve::InCubic:
         return &easeInCubic;
     case QEasingCurve::OutCubic:
         return &easeOutCubic;
     case QEasingCurve::InOutCubic:
         return &easeInOutCubic;
     case QEasingCurve::OutInCubic:
         return &easeOutInCubic;
     case QEasingCurve::InQuart:
         return &easeInQuart;
     case QEasingCurve::OutQuart:
         return &easeOutQuart;
     case QEasingCurve::InOutQuart:
         return &easeInOutQuart;
     case QEasingCurve::OutInQuart:
         return &easeOutInQuart;
     case QEasingCurve::InQuint:
         return &easeInQuint;
     case QEasingCurve::OutQuint:
         return &easeOutQuint;
     case QEasingCurve::InOutQuint:
         return &easeInOutQuint;
     case QEasingCurve::OutInQuint:
         return &easeOutInQuint;
     case QEasingCurve::InSine:
         return &easeInSine;
     case QEasingCurve::OutSine:
         return &easeOutSine;
     case QEasingCurve::InOutSine:
         return &easeInOutSine;
     case QEasingCurve::OutInSine:
         return &easeOutInSine;
     case QEasingCurve::InExpo:
         return &easeInExpo;
     case QEasingCurve::OutExpo:
         return &easeOutExpo;
     case QEasingCurve::InOutExpo:
         return &easeInOutExpo;
     case QEasingCurve::OutInExpo:
         return &easeOutInExpo;
     case QEasingCurve::InCirc:
         return &easeInCirc;
     case QEasingCurve::OutCirc:
         return &easeOutCirc;
     case QEasingCurve::InOutCirc:
         return &easeInOutCirc;
     case QEasingCurve::OutInCirc:
         return &easeOutInCirc;
     // Internal for, compatibility with QTimeLine only ??
     case QEasingCurve::InCurve:
         return &easeInCurve;
     case QEasingCurve::OutCurve:
         return &easeOutCurve;
     case QEasingCurve::SineCurve:
         return &easeSineCurve;
     case QEasingCurve::CosineCurve:
         return &easeCosineCurve;
     default:
         return 0;
     };
 }
curveToFunctionObject()
static QEasingCurveFunction* curveToFunctionObject (QEasingCurve::Type type) static
Definition at line 565 of file qeasingcurve.cpp.
Referenced by operator>>(), QEasingCurve::setAmplitude(), QEasingCurve::setOvershoot(), QEasingCurve::setPeriod(), and QEasingCurvePrivate::setType_helper().
 {
     QEasingCurveFunction *curveFunc = 0;
     switch(type) {
     case QEasingCurve::InElastic:
         curveFunc = new ElasticEase(ElasticEase::In);
         break;
     case QEasingCurve::OutElastic:
         curveFunc = new ElasticEase(ElasticEase::Out);
         break;
     case QEasingCurve::InOutElastic:
         curveFunc = new ElasticEase(ElasticEase::InOut);
         break;
     case QEasingCurve::OutInElastic:
         curveFunc = new ElasticEase(ElasticEase::OutIn);
         break;
     case QEasingCurve::OutBounce:
         curveFunc = new BounceEase(BounceEase::Out);
         break;
     case QEasingCurve::InBounce:
         curveFunc = new BounceEase(BounceEase::In);
         break;
     case QEasingCurve::OutInBounce:
         curveFunc = new BounceEase(BounceEase::OutIn);
         break;
     case QEasingCurve::InOutBounce:
         curveFunc = new BounceEase(BounceEase::InOut);
         break;
     case QEasingCurve::InBack:
         curveFunc = new BackEase(BackEase::In);
         break;
     case QEasingCurve::OutBack:
         curveFunc = new BackEase(BackEase::Out);
         break;
     case QEasingCurve::InOutBack:
         curveFunc = new BackEase(BackEase::InOut);
         break;
     case QEasingCurve::OutInBack:
         curveFunc = new BackEase(BackEase::OutIn);
         break;
     default:
         curveFunc = new QEasingCurveFunction(QEasingCurveFunction::In, qreal(0.3), qreal(1.0), qreal(1.70158));
     }
     return curveFunc;
 }
isConfigFunction()
static bool isConfigFunction (QEasingCurve::Type type) static
Definition at line 331 of file qeasingcurve.cpp.
Referenced by QEasingCurvePrivate::setType_helper().
 {
     return type >= QEasingCurve::InElastic
             && type <= QEasingCurve::OutInBounce;
 }
operator<<() [1/2]
QDebug operator<< (QDebug debug, const QEasingCurve & item)
Definition at line 870 of file qeasingcurve.cpp.
 {
     debug << "type:" << item.d_ptr->type
           << "func:" << item.d_ptr->func;
     if (item.d_ptr->config) {
         debug << QString::fromAscii("period:%1").arg(item.d_ptr->config->_p, 0, 'f', 20)
               << QString::fromAscii("amp:%1").arg(item.d_ptr->config->_a, 0, 'f', 20)
               << QString::fromAscii("overshoot:%1").arg(item.d_ptr->config->_o, 0, 'f', 20);
     }
     return debug;
 }
operator<<() [2/2]
QDataStream& operator<< (QDataStream & stream, const QEasingCurve & easing)
Definition at line 897 of file qeasingcurve.cpp.
 {
     stream << quint8(easing.d_ptr->type);
     stream << quint64(quintptr(easing.d_ptr->func));
     bool hasConfig = easing.d_ptr->config;
     stream << hasConfig;
     if (hasConfig) {
         stream << easing.d_ptr->config->_p;
         stream << easing.d_ptr->config->_a;
         stream << easing.d_ptr->config->_o;
     }
     return stream;
 }
operator>>()
QDataStream& operator>> (QDataStream & stream, QEasingCurve & easing) related
Definition at line 925 of file qeasingcurve.cpp.
 {
     QEasingCurve::Type type;
     quint8 int_type;
     stream >> int_type;
     type = static_cast<QEasingCurve::Type>(int_type);
     easing.setType(type);
     quint64 ptr_func;
     stream >> ptr_func;
     easing.d_ptr->func = QEasingCurve::EasingFunction(quintptr(ptr_func));
     bool hasConfig;
     stream >> hasConfig;
     if (hasConfig) {
         QEasingCurveFunction *config = curveToFunctionObject(type);
         stream >> config->_p;
         stream >> config->_a;
         stream >> config->_o;
         easing.d_ptr->config = config;
     }
     return stream;
 }