Qt 4.8: /src/gui/widgets/qeffects_p.h File Reference
qeffects_p.h File Reference
#include "QtCore/qnamespace.h"
Classes
struct QEffects
Functions
void Q_GUI_EXPORT qFadeEffect (QWidget *, int time=-1)
Fade in widget w in time ms.
void Q_GUI_EXPORT qScrollEffect (QWidget *, QEffects::DirFlags dir=QEffects::DownScroll, int time=-1)
Scroll widget w in time ms.
Function Documentation
qFadeEffect()
void Q_GUI_EXPORT qFadeEffect (QWidget * , int time = -1)
Fade in widget w in time ms.
Definition at line 584 of file qeffects.cpp.
Referenced by QMenu::popup(), QMenuPrivate::setCurrentAction(), and QToolTip::showText().
 {
     if (q_blend) {
         q_blend->deleteLater();
         q_blend = 0;
     }
     if (!w)
         return;
     QApplication::sendPostedEvents(w, QEvent::Move);
     QApplication::sendPostedEvents(w, QEvent::Resize);
     Qt::WindowFlags flags = Qt::ToolTip;
     // those can be popups - they would steal the focus, but are disabled
     q_blend = new QAlphaWidget(w, flags);
     q_blend->run(time);
 }
qScrollEffect()
void Q_GUI_EXPORT qScrollEffect (QWidget * w, QEffects::DirFlags orient, int time)
Scroll widget w in time ms.
orient may be 1 (vertical), 2 (horizontal) or 3 (diagonal).
Definition at line 562 of file qeffects.cpp.
Referenced by QMenu::popup(), QMenuPrivate::setCurrentAction(), QComboBox::showPopup(), and QToolTip::showText().
 {
     if (q_roll) {
         q_roll->deleteLater();
         q_roll = 0;
     }
     if (!w)
         return;
     QApplication::sendPostedEvents(w, QEvent::Move);
     QApplication::sendPostedEvents(w, QEvent::Resize);
     Qt::WindowFlags flags = Qt::ToolTip;
     // those can be popups - they would steal the focus, but are disabled
     q_roll = new QRollEffect(w, flags, orient);
     q_roll->run(time);
 }