Qt 4.8: /src/gui/widgets/qeffects.cpp File Reference
qeffects.cpp File Reference
#include "qapplication.h"
#include "qdesktopwidget.h"
#include "qeffects_p.h"
#include "qevent.h"
#include "qimage.h"
#include "qpainter.h"
#include "qpixmap.h"
#include "qpointer.h"
#include "qtimer.h"
#include "qelapsedtimer.h"
#include "qdebug.h"
#include "qeffects.moc"
Classes
class QAlphaWidget
class QRollEffect
Functions
void qFadeEffect (QWidget *w, int time)
Fade in widget w in time ms.
void qScrollEffect (QWidget *w, QEffects::DirFlags orient, int time)
Scroll widget w in time ms.
Variables
static QAlphaWidget * q_blend = 0
static QRollEffect * q_roll = 0
Function Documentation
qFadeEffect()
void qFadeEffect (QWidget * w, int time)
Fade in widget w in time ms.
Definition at line 584 of file qeffects.cpp.
Referenced by QMenu::popup(), QMenuPrivate::setCurrentAction(), and QToolTip::showText().
 {
     if (q_blend) {
         q_blend->deleteLater();
         q_blend = 0;
     }
     if (!w)
         return;
     QApplication::sendPostedEvents(w, QEvent::Move);
     QApplication::sendPostedEvents(w, QEvent::Resize);
     Qt::WindowFlags flags = Qt::ToolTip;
     // those can be popups - they would steal the focus, but are disabled
     q_blend = new QAlphaWidget(w, flags);
     q_blend->run(time);
 }
qScrollEffect()
void qScrollEffect (QWidget * w, QEffects::DirFlags orient, int time)
Scroll widget w in time ms.
orient may be 1 (vertical), 2 (horizontal) or 3 (diagonal).
Definition at line 562 of file qeffects.cpp.
Referenced by QMenu::popup(), QMenuPrivate::setCurrentAction(), QComboBox::showPopup(), and QToolTip::showText().
 {
     if (q_roll) {
         q_roll->deleteLater();
         q_roll = 0;
     }
     if (!w)
         return;
     QApplication::sendPostedEvents(w, QEvent::Move);
     QApplication::sendPostedEvents(w, QEvent::Resize);
     Qt::WindowFlags flags = Qt::ToolTip;
     // those can be popups - they would steal the focus, but are disabled
     q_roll = new QRollEffect(w, flags, orient);
     q_roll->run(time);
 }
Variable Documentation
q_blend
QAlphaWidget* q_blend = 0 static
Definition at line 96 of file qeffects.cpp.
q_roll
QRollEffect* q_roll = 0 static
Definition at line 377 of file qeffects.cpp.