Qt 4.8: /src/gui/egl/qegl_x11.cpp File Reference
qegl_x11.cpp File Reference
#include <QtCore/qdebug.h>
#include <QtGui/private/qt_x11_p.h>
#include <QtGui/qx11info_x11.h>
#include <QtGui/private/qpixmapdata_p.h>
#include <QtGui/private/qpixmap_x11_p.h>
#include <QtGui/private/qimagepixmapcleanuphooks_p.h>
#include <QtGui/qpaintdevice.h>
#include <QtGui/qpixmap.h>
#include <QtGui/qwidget.h>
#include <QtGui/qcolormap.h>
#include "QtGui/private/qegl_p.h"
#include "QtGui/private/qeglcontext_p.h"
Functions
static int countBits (unsigned long mask)
void qt_set_winid_on_widget (QWidget *w, Qt::HANDLE id)
const QX11Info * qt_x11Info (const QPaintDevice *pd)
Function Documentation
countBits()
static int countBits (unsigned long mask) static
Definition at line 81 of file qegl_x11.cpp.
Referenced by QEgl::getCompatibleVisualId(), and QEglProperties::setVisualFormat().
 {
     int count = 0;
     while (mask != 0) {
         if (mask & 1)
             ++count;
         mask >>= 1;
     }
     return count;
 }
qt_set_winid_on_widget()
void qt_set_winid_on_widget (QWidget * w, Qt::HANDLE id)
Definition at line 325 of file qegl_x11.cpp.
Referenced by QEgl::createSurface().
 {
     w->create(id);
 }
qt_x11Info()
const QX11Info* qt_x11Info (const QPaintDevice * pd) related
Referenced by QEglProperties::setVisualFormat().