Qt 4.8: /src/corelib/tools/qelapsedtimer_unix.cpp File Reference
qelapsedtimer_unix.cpp File Reference
#include "qelapsedtimer.h"
#include <sys/time.h>
#include <time.h>
#include <unistd.h>
Macros
#define is_likely(x) (x)
#define load_acquire(x) ((volatile const int&)(x))
#define store_release(x, v) ((volatile int&)(x) = (v))
Functions
static void do_gettime (qint64 *sec, qint64 *frac)
static qint64 elapsedAndRestart (qint64 sec, qint64 frac, qint64 *nowsec, qint64 *nowfrac)
static qint64 fractionAdjustment ()
bool operator< (const QElapsedTimer &v1, const QElapsedTimer &v2)
timeval qt_gettime ()
static void unixCheckClockType ()
Variables
static int monotonicClockAvailable = false
static int monotonicClockChecked = false
Macro Definition Documentation
is_likely
#define is_likely (x) (x)
Definition at line 72 of file qelapsedtimer_unix.cpp.
Referenced by do_gettime(), and unixCheckClockType().
load_acquire
#define load_acquire (x) ((volatile const int&)(x))
Definition at line 74 of file qelapsedtimer_unix.cpp.
Referenced by unixCheckClockType().
store_release
#define store_release (x, v) ((volatile int&)(x) = (v))
Definition at line 75 of file qelapsedtimer_unix.cpp.
Referenced by unixCheckClockType().
Function Documentation
do_gettime()
static void do_gettime (qint64 * sec, qint64 * frac) inline static
Definition at line 121 of file qelapsedtimer_unix.cpp.
Referenced by elapsedAndRestart(), and qt_gettime().
 {
 #if (_POSIX_MONOTONIC_CLOCK-0 >= 0)
     unixCheckClockType();
     if (is_likely(monotonicClockAvailable)) {
         timespec ts;
         clock_gettime(CLOCK_MONOTONIC, &ts);
         *sec = ts.tv_sec;
         *frac = ts.tv_nsec;
         return;
     }
 #endif
     // use gettimeofday
     struct timeval tv;
     ::gettimeofday(&tv, 0);
     *sec = tv.tv_sec;
     *frac = tv.tv_usec;
 }
elapsedAndRestart()
static qint64 elapsedAndRestart (qint64 sec, qint64 frac, qint64 * nowsec, qint64 * nowfrac) static
Definition at line 155 of file qelapsedtimer_unix.cpp.
 {
     do_gettime(nowsec, nowfrac);
     sec = *nowsec - sec;
     frac = *nowfrac - frac;
     return sec * Q_INT64_C(1000) + frac / fractionAdjustment();
 }
fractionAdjustment()
static qint64 fractionAdjustment () inline static
Definition at line 93 of file qelapsedtimer_unix.cpp.
Referenced by elapsedAndRestart().
 {
     // disabled, but otherwise indicates bad usage of QElapsedTimer
     //Q_ASSERT(monotonicClockChecked);
     if (monotonicClockAvailable) {
         // the monotonic timer is measured in nanoseconds
         // 1 ms = 1000000 ns
         return 1000*1000ull;
     } else {
         // gettimeofday is measured in microseconds
         // 1 ms = 1000 us
         return 1000;
     }
 }
operator<()
bool operator< (const QElapsedTimer & v1, const QElapsedTimer & v2)
Definition at line 208 of file qelapsedtimer_unix.cpp.
 {
     return v1.t1 < v2.t1 || (v1.t1 == v2.t1 && v1.t2 < v2.t2);
 }
qt_gettime()
timeval qt_gettime ()
Definition at line 141 of file qelapsedtimer_unix.cpp.
Referenced by qt_safe_select(), QTimerInfoList::QTimerInfoList(), QEventDispatcherBlackberry::select(), time_update(), and QTimerInfoList::updateCurrentTime().
 {
     qint64 sec, frac;
     do_gettime(&sec, &frac);
     timeval tv;
     tv.tv_sec = sec;
     tv.tv_usec = frac;
     if (monotonicClockAvailable)
         tv.tv_usec /= 1000;
     return tv;
 }
unixCheckClockType()
static void unixCheckClockType () static
Definition at line 77 of file qelapsedtimer_unix.cpp.
Referenced by do_gettime(), and fractionAdjustment().
 {
 #if (_POSIX_MONOTONIC_CLOCK-0 == 0)
     if (is_likely(load_acquire(monotonicClockChecked)))
         return;
 # if defined(_SC_MONOTONIC_CLOCK)
     // detect if the system support monotonic timers
     long x = sysconf(_SC_MONOTONIC_CLOCK);
     store_release(monotonicClockAvailable, x >= 200112L);
 # endif
     store_release(monotonicClockChecked, true);
 #endif
 }
Variable Documentation
monotonicClockAvailable
int monotonicClockAvailable = false static
Definition at line 66 of file qelapsedtimer_unix.cpp.
Referenced by do_gettime(), elapsedAndRestart(), fractionAdjustment(), qt_gettime(), and unixCheckClockType().
monotonicClockChecked
int monotonicClockChecked = false static
Definition at line 65 of file qelapsedtimer_unix.cpp.
Referenced by unixCheckClockType().