Qt 4.8: /src/corelib/tools/qelapsedtimer_win.cpp File Reference
qelapsedtimer_win.cpp File Reference
#include "qelapsedtimer.h"
#include <windows.h>
#include <private/qsystemlibrary_p.h>
Typedefs
typedef ULONGLONG(WINAPI * PtrGetTickCount64) (void)
Functions
static quint64 getTickCount ()
bool operator< (const QElapsedTimer &v1, const QElapsedTimer &v2)
static void resolveLibs ()
static qint64 ticksToNanoseconds (qint64 ticks)
Variables
static quint64 counterFrequency = 0
static PtrGetTickCount64 ptrGetTickCount64 = 0
Typedef Documentation
PtrGetTickCount64
typedef ULONGLONG(WINAPI * PtrGetTickCount64) (void)
Definition at line 47 of file qelapsedtimer_win.cpp.
Function Documentation
getTickCount()
static quint64 getTickCount () static
Definition at line 93 of file qelapsedtimer_win.cpp.
 {
     resolveLibs();
     // This avoids a division by zero and disables the high performance counter if it's not available
     if (counterFrequency > 0) {
         LARGE_INTEGER counter;
         if (QueryPerformanceCounter(&counter)) {
             return counter.QuadPart;
         } else {
             qWarning("QueryPerformanceCounter failed, although QueryPerformanceFrequency succeeded.");
             return 0;
         }
     }
     if (ptrGetTickCount64)
         return ptrGetTickCount64();
     static quint32 highdword = 0;
     static quint32 lastval = 0;
     quint32 val = GetTickCount();
     if (val < lastval)
         ++highdword;
     lastval = val;
     return val | (quint64(highdword) << 32);
 }
operator<()
bool operator< (const QElapsedTimer & v1, const QElapsedTimer & v2)
Definition at line 178 of file qelapsedtimer_win.cpp.
 {
     return (v1.t1 - v2.t1) < 0;
 }
resolveLibs()
static void resolveLibs () static
Definition at line 55 of file qelapsedtimer_win.cpp.
Referenced by QFileSystemEngine::fillPermissions(), getTickCount(), isDirPath(), QFileSystemEngine::owner(), and readSymLink().
 {
     static volatile bool done = false;
     if (done)
         return;
     // try to get GetTickCount64 from the system
     QSystemLibrary kernel32(QLatin1String("kernel32"));
     if (!kernel32.load())
         return;
     // does this function exist on WinCE, or will ever exist?
     ptrGetTickCount64 = (PtrGetTickCount64)kernel32.resolve("GetTickCount64");
     // Retrieve the number of high-resolution performance counter ticks per second
     LARGE_INTEGER frequency;
     if (!QueryPerformanceFrequency(&frequency)) {
         counterFrequency = 0;
     } else {
         counterFrequency = frequency.QuadPart;
     }
     done = true;
 }
ticksToNanoseconds()
static qint64 ticksToNanoseconds (qint64 ticks) inline static
Definition at line 80 of file qelapsedtimer_win.cpp.
Referenced by getTickCount().
 {
     if (counterFrequency > 0) {
         // QueryPerformanceCounter uses an arbitrary frequency
         qint64 seconds = ticks / counterFrequency;
         qint64 nanoSeconds = (ticks - seconds * counterFrequency) * 1000000000 / counterFrequency;
         return seconds * 1000000000 + nanoSeconds;
     } else {
         // GetTickCount(64) return milliseconds
         return ticks * 1000000;
     }
 }
Variable Documentation
counterFrequency
quint64 counterFrequency = 0 static
Definition at line 53 of file qelapsedtimer_win.cpp.
Referenced by getTickCount(), resolveLibs(), and ticksToNanoseconds().
ptrGetTickCount64
PtrGetTickCount64 ptrGetTickCount64 = 0 static
Definition at line 48 of file qelapsedtimer_win.cpp.
Referenced by getTickCount(), and resolveLibs().