Qt 4.8: /src/corelib/global/qendian.h File Reference
qendian.h File Reference
#include <QtCore/qglobal.h>
#include <stdlib.h>
Functions
template<typename T >
void qbswap (const T src, uchar *dest)
template<typename T >
T qbswap (T source)
template<>
qint16 qbswap< qint16 > (qint16 source)
template<>
qint32 qbswap< qint32 > (qint32 source)
template<>
qint64 qbswap< qint64 > (qint64 source)
template<>
quint16 qbswap< quint16 > (quint16 source)
template<>
quint32 qbswap< quint32 > (quint32 source)
template<>
quint64 qbswap< quint64 > (quint64 source)
template<>
quint8 qbswap< quint8 > (quint8 source)
void qbswap_helper (const uchar *src, uchar *dest, int size)
template<class T >
T qFromBigEndian (const uchar *src)
template<typename T >
T qFromBigEndian (T source)
template<>
qint16 qFromBigEndian< qint16 > (const uchar *src)
template<>
qint32 qFromBigEndian< qint32 > (const uchar *src)
template<>
qint64 qFromBigEndian< qint64 > (const uchar *src)
template<>
quint16 qFromBigEndian< quint16 > (const uchar *src)
template<>
quint32 qFromBigEndian< quint32 > (const uchar *src)
template<>
quint64 qFromBigEndian< quint64 > (const uchar *src)
template<typename T >
T qFromLittleEndian (const uchar *src)
template<typename T >
T qFromLittleEndian (T source)
template<>
qint16 qFromLittleEndian< qint16 > (const uchar *src)
template<>
qint32 qFromLittleEndian< qint32 > (const uchar *src)
template<>
qint64 qFromLittleEndian< qint64 > (const uchar *src)
template<>
quint16 qFromLittleEndian< quint16 > (const uchar *src)
template<>
quint32 qFromLittleEndian< quint32 > (const uchar *src)
template<>
quint64 qFromLittleEndian< quint64 > (const uchar *src)
template<typename T >
T qToBigEndian (T source)
template<typename T >
void qToBigEndian (T src, uchar *dest)
template<typename T >
T qToLittleEndian (T source)
template<typename T >
void qToLittleEndian (T src, uchar *dest)
template<typename T >
void qToUnaligned (const T src, uchar *dest)
Function Documentation
qbswap() [1/2]
template<typename T > void qbswap (const T src, uchar * dest) inline
Definition at line 74 of file qendian.h.
Referenced by QDataStream::operator<<(), operator<<(), QDataStream::operator>>(), operator>>(), and qFromBigEndian< qint16 >().
 {
     qbswap_helper(reinterpret_cast<const uchar *>(&src), dest, sizeof(T));
 }
qbswap() [2/2]
template<typename T > T qbswap (T source)
qbswap< qint16 >()
template<> qint16 qbswap< qint16 > (qint16 source) inline
Definition at line 330 of file qendian.h.
 {
     return qbswap<quint16>(quint16(source));
 }
qbswap< qint32 >()
template<> qint32 qbswap< qint32 > (qint32 source) inline
Definition at line 325 of file qendian.h.
 {
     return qbswap<quint32>(quint32(source));
 }
qbswap< qint64 >()
template<> qint64 qbswap< qint64 > (qint64 source) inline
Definition at line 320 of file qendian.h.
 {
     return qbswap<quint64>(quint64(source));
 }
qbswap< quint16 >()
template<> quint16 qbswap< quint16 > (quint16 source) inline
Definition at line 311 of file qendian.h.
Referenced by qbswap< qint16 >(), and qFromBigEndian< qint16 >().
 {
     return quint16( 0
                     | ((source & 0x00ff) << 8)
                     | ((source & 0xff00) >> 8) );
 }
qbswap< quint32 >()
template<> quint32 qbswap< quint32 > (quint32 source) inline
Definition at line 302 of file qendian.h.
Referenced by QFontEngineWin::getCMap(), QFontEngineWin::getSfntTableData(), QFontEngineDirectWrite::getSfntTableData(), qbswap< qint32 >(), and qFromBigEndian< qint16 >().
 {
     return 0
         | ((source & 0x000000ff) << 24)
         | ((source & 0x0000ff00) << 8)
         | ((source & 0x00ff0000) >> 8)
         | ((source & 0xff000000) >> 24);
 }
qbswap< quint64 >()
template<> quint64 qbswap< quint64 > (quint64 source) inline
Definition at line 289 of file qendian.h.
Referenced by qbswap< qint64 >(), and qFromBigEndian< qint16 >().
 {
     return 0
         | ((source & Q_UINT64_C(0x00000000000000ff)) << 56)
         | ((source & Q_UINT64_C(0x000000000000ff00)) << 40)
         | ((source & Q_UINT64_C(0x0000000000ff0000)) << 24)
         | ((source & Q_UINT64_C(0x00000000ff000000)) << 8)
         | ((source & Q_UINT64_C(0x000000ff00000000)) >> 8)
         | ((source & Q_UINT64_C(0x0000ff0000000000)) >> 24)
         | ((source & Q_UINT64_C(0x00ff000000000000)) >> 40)
         | ((source & Q_UINT64_C(0xff00000000000000)) >> 56);
 }
qbswap< quint8 >()
template<> quint8 qbswap< quint8 > (quint8 source) inline
Definition at line 366 of file qendian.h.
 {
     return source;
 }
qbswap_helper()
void qbswap_helper (const uchar * src, uchar * dest, int size) inline
Definition at line 63 of file qendian.h.
Referenced by qbswap().
 {
     for (int i = 0; i < size ; ++i) dest[i] = src[size - 1 - i];
 }
qFromBigEndian() [1/2]
template<class T > T qFromBigEndian (const uchar * src) inline
Referenced by QAudioOutputPrivate::freeBlocks(), qFromLittleEndian< qint16 >(), qToLittleEndian(), and QRawFont::supportedWritingSystems().
qFromBigEndian() [2/2]
template<typename T > T qFromBigEndian (T source) inline
Definition at line 339 of file qendian.h.
 { return source; }
qFromBigEndian< qint16 >()
template<> qint16 qFromBigEndian< qint16 > (const uchar * src) inline
Definition at line 264 of file qendian.h.
 { return static_cast<qint16>(qFromBigEndian<quint16>(src)); }
qFromBigEndian< qint32 >()
template<> qint32 qFromBigEndian< qint32 > (const uchar * src) inline
Definition at line 261 of file qendian.h.
 { return static_cast<qint32>(qFromBigEndian<quint32>(src)); }
qFromBigEndian< qint64 >()
template<> qint64 qFromBigEndian< qint64 > (const uchar * src) inline
Definition at line 258 of file qendian.h.
 { return static_cast<qint64>(qFromBigEndian<quint64>(src)); }
qFromBigEndian< quint16 >()
template<> quint16 qFromBigEndian< quint16 > (const uchar * src) inline
Definition at line 249 of file qendian.h.
Referenced by QFontEngineQPA::extractHeaderField(), QFontEngineQPF::extractHeaderField(), QUuid::fromRfc4122(), QFontEngine::getCMap(), getFontTable(), QFontEngine::getTrueTypeGlyphIndex(), QFontEngine::glyphCount(), initializeDb(), QFontEngine::loadKerningPairs(), QFontEngineMac::properties(), QFontEngineMac::QFontEngineMac(), QFontEngineQPA::QFontEngineQPA(), QFontEngineQPF::QFontEngineQPF(), qFromBigEndian< qint16 >(), qt_socks5_get_host_address_and_port(), QFontEngineQPA::verifyHeader(), and QFontEngineQPF::verifyHeader().
 {
     return quint16( 0
                     | src[1]
                     | src[0] * quint16(0x0100));
 }
qFromBigEndian< quint32 >()
template<> quint32 qFromBigEndian< quint32 > (const uchar * src) inline
Definition at line 239 of file qendian.h.
Referenced by checksum(), QUtf32::convertToUnicode(), QFontEngineQPA::findGlyph(), QFontEngineQPF::findGlyph(), QUuid::fromRfc4122(), QFontEngine::getCMap(), getFamiliesAndSignatures(), getFontTable(), getTrueTypeFontOffsets(), QFontEngine::getTrueTypeGlyphIndex(), initWritingSystems(), QFontEngineQPA::QFontEngineQPA(), QFontEngineQPF::QFontEngineQPF(), qFromBigEndian< qint32 >(), qt_socks5_get_host_address_and_port(), QPAGenerator::writeHeader(), and QPFGenerator::writeHeader().
 {
     return 0
         | src[3]
         | src[2] * quint32(0x00000100)
         | src[1] * quint32(0x00010000)
         | src[0] * quint32(0x01000000);
 }
qFromBigEndian< quint64 >()
template<> quint64 qFromBigEndian< quint64 > (const uchar * src) inline
Definition at line 225 of file qendian.h.
Referenced by qFromBigEndian< qint64 >().
 {
     return 0
         | src[7]
         | src[6] * Q_UINT64_C(0x0000000000000100)
         | src[5] * Q_UINT64_C(0x0000000000010000)
         | src[4] * Q_UINT64_C(0x0000000001000000)
         | src[3] * Q_UINT64_C(0x0000000100000000)
         | src[2] * Q_UINT64_C(0x0000010000000000)
         | src[1] * Q_UINT64_C(0x0001000000000000)
         | src[0] * Q_UINT64_C(0x0100000000000000);
 }
qFromLittleEndian() [1/2]
template<typename T > T qFromLittleEndian (const uchar * src) inline
Referenced by qStringFromUcs2Le(), qToLittleEndian(), and qToUnaligned().
qFromLittleEndian() [2/2]
template<typename T > T qFromLittleEndian (T source) inline
Definition at line 343 of file qendian.h.
 { return qbswap<T>(source); }
qFromLittleEndian< qint16 >()
template<> qint16 qFromLittleEndian< qint16 > (const uchar * src) inline
Definition at line 171 of file qendian.h.
 { return static_cast<qint16>(qFromLittleEndian<quint16>(src)); }
qFromLittleEndian< qint32 >()
template<> qint32 qFromLittleEndian< qint32 > (const uchar * src) inline
Definition at line 168 of file qendian.h.
 { return static_cast<qint32>(qFromLittleEndian<quint32>(src)); }
qFromLittleEndian< qint64 >()
template<> qint64 qFromLittleEndian< qint64 > (const uchar * src) inline
Definition at line 165 of file qendian.h.
 { return static_cast<qint64>(qFromLittleEndian<quint64>(src)); }
qFromLittleEndian< quint16 >()
template<> quint16 qFromLittleEndian< quint16 > (const uchar * src) inline
Definition at line 157 of file qendian.h.
Referenced by QUuid::operator>>(), qFromLittleEndian< qint16 >(), readBMPInfoHeader(), readIconDir(), and readIconDirEntry().
 {
     return quint16(0
                    | src[0]
                    | src[1] * 0x0100);
 }
qFromLittleEndian< quint32 >()
template<> quint32 qFromLittleEndian< quint32 > (const uchar * src) inline
Definition at line 148 of file qendian.h.
Referenced by QUtf32::convertToUnicode(), QZipPrivate::fillFileInfo(), QUuid::operator>>(), qFromLittleEndian< qint32 >(), readBMPInfoHeader(), and readIconDirEntry().
 {
     return 0
         | src[0]
         | src[1] * quint32(0x00000100)
         | src[2] * quint32(0x00010000)
         | src[3] * quint32(0x01000000);
 }
qFromLittleEndian< quint64 >()
template<> quint64 qFromLittleEndian< quint64 > (const uchar * src) inline
Definition at line 135 of file qendian.h.
Referenced by qFromLittleEndian< qint64 >().
 {
     return 0
         | src[0]
         | src[1] * Q_UINT64_C(0x0000000000000100)
         | src[2] * Q_UINT64_C(0x0000000000010000)
         | src[3] * Q_UINT64_C(0x0000000001000000)
         | src[4] * Q_UINT64_C(0x0000000100000000)
         | src[5] * Q_UINT64_C(0x0000010000000000)
         | src[6] * Q_UINT64_C(0x0001000000000000)
         | src[7] * Q_UINT64_C(0x0100000000000000);
 }
qToBigEndian() [1/2]
template<typename T > T qToBigEndian (T source) inline
Definition at line 337 of file qendian.h.
Referenced by _q_toHex(), bindFont(), QRawFont::fontTable(), QHostAddress::isInSubnet(), QFontEngineQPF::loadGlyph(), QTtfStream::operator<<(), qToLittleEndian(), QNetmaskAddress::setAddress(), QUuid::toRfc4122(), QPAGenerator::writeUInt16(), QPFGenerator::writeUInt16(), QPAGenerator::writeUInt32(), and QPFGenerator::writeUInt32().
 { return source; }
qToBigEndian() [2/2]
template<typename T > void qToBigEndian (T src, uchar * dest) inline
Definition at line 345 of file qendian.h.
 { qToUnaligned<T>(src, dest); }
qToLittleEndian() [1/2]
template<typename T > T qToLittleEndian (T source) inline
Definition at line 341 of file qendian.h.
Referenced by QWSSoundServerProvider::getSample(), QUuid::operator<<(), qStringAsUcs2Le(), qToLittleEndian(), QWSSoundServerBucket::readySamples(), and writeIconDir().
 { return qbswap<T>(source); }
qToLittleEndian() [2/2]
template<typename T > void qToLittleEndian (T src, uchar * dest) inline
Definition at line 347 of file qendian.h.
 { qbswap<T>(src, dest); }
qToUnaligned()
template<typename T > void qToUnaligned (const T src, uchar * dest) inline
Definition at line 81 of file qendian.h.
 {
     qMemCopy(dest, &src, sizeof(T));
 }