Qt 4.8: /src/gui/dialogs/qerrormessage.cpp File Reference
qerrormessage.cpp File Reference
#include "qerrormessage.h"
#include "qapplication.h"
#include "qcheckbox.h"
#include "qlabel.h"
#include "qlayout.h"
#include "qmessagebox.h"
#include "qpushbutton.h"
#include "qstringlist.h"
#include "qtextedit.h"
#include "qdialog_p.h"
#include "qpixmap.h"
#include "qmetaobject.h"
#include "qthread.h"
#include "qqueue.h"
#include "qset.h"
#include <stdio.h>
#include <stdlib.h>
#include "qguifunctions_wince.h"
Classes
class QErrorMessagePrivate
class QErrorMessageTextView
Functions
static void deleteStaticcQErrorMessage ()
static void jump (QtMsgType t, const char *m)
bool qt_wince_is_high_dpi ()
bool qt_wince_is_mobile ()
Variables
static bool metFatal = false
static QErrorMessage * qtMessageHandler = 0
Function Documentation
deleteStaticcQErrorMessage()
static void deleteStaticcQErrorMessage () static
Definition at line 191 of file qerrormessage.cpp.
Referenced by QErrorMessage::qtHandler().
 {
     if (qtMessageHandler) {
         delete qtMessageHandler;
         qtMessageHandler = 0;
     }
 }
jump()
static void jump (QtMsgType t, const char * m) static
Definition at line 201 of file qerrormessage.cpp.
Referenced by do_size_hints(), qt_grab_cursor(), qt_mac_update_widget_position(), QErrorMessage::qtHandler(), and QErrorMessage::~QErrorMessage().
 {
     if (!qtMessageHandler)
         return;
     QString rich;
     switch (t) {
     case QtDebugMsg:
     default:
         rich = QErrorMessage::tr("Debug Message:");
         break;
     case QtWarningMsg:
         rich = QErrorMessage::tr("Warning:");
         break;
     case QtFatalMsg:
         rich = QErrorMessage::tr("Fatal Error:");
     }
     rich = QString::fromLatin1("<p><b>%1</b></p>").arg(rich);
     rich += Qt::convertFromPlainText(QLatin1String(m), Qt::WhiteSpaceNormal);
     // ### work around text engine quirk
     if (rich.endsWith(QLatin1String("</p>")))
         rich.chop(4);
     if (!metFatal) {
         if (QThread::currentThread() == qApp->thread()) {
             qtMessageHandler->showMessage(rich);
         } else {
             QMetaObject::invokeMethod(qtMessageHandler,
                                       "showMessage",
                                       Qt::QueuedConnection,
                                       Q_ARG(QString, rich));
         }
         metFatal = (t == QtFatalMsg);
     }
 }
qt_wince_is_high_dpi()
bool qt_wince_is_high_dpi ()
Definition at line 300 of file qguifunctions_wince.cpp.
Referenced by QErrorMessageTextView::minimumSizeHint(), and QErrorMessageTextView::sizeHint().
{
     if (!qt_wince_is_pocket_pc())
         return false;
     HDC deviceContext = GetDC(0);
     int dpi = GetDeviceCaps(deviceContext, LOGPIXELSX);
     ReleaseDC(0, deviceContext);
     if ((dpi < 1000) && (dpi > 0))
         return dpi > 96;
     else
         return false;
 }
qt_wince_is_mobile()
bool qt_wince_is_mobile ()
Definition at line 296 of file qguifunctions_wince.cpp.
Referenced by QErrorMessageTextView::minimumSizeHint(), and QErrorMessageTextView::sizeHint().
{
      return (qt_wince_is_smartphone() || qt_wince_is_pocket_pc());
 }
Variable Documentation
metFatal
bool metFatal = false static
Definition at line 199 of file qerrormessage.cpp.
Referenced by QErrorMessage::done(), and jump().
qtMessageHandler
QErrorMessage* qtMessageHandler = 0 static
Definition at line 189 of file qerrormessage.cpp.
Referenced by deleteStaticcQErrorMessage(), and QErrorMessage::qtHandler().