Qt 4.8: /src/plugins/codecs/kr/qeuckrcodec.cpp File Reference
qeuckrcodec.cpp File Reference
#include "qeuckrcodec.h"
#include "cp949codetbl.h"
Classes
struct map
Macros
#define IsCP949Char(c) (((c) >= 0x81) && ((c) <= 0xa0))
#define IsEucChar(c) (((c) >= 0xa1) && ((c) <= 0xfe))
#define QValidChar(u) ((u) ? QChar((ushort)(u)) : QChar(QChar::ReplacementCharacter))
Functions
static unsigned short ksc2unicode (unsigned short code)
unsigned int qt_Ksc5601ToUnicode (unsigned int code)
unsigned int qt_UnicodeToKsc5601 (unsigned int unicode)
static unsigned short unicode2ksc (unsigned short code)
Variables
static const unsigned short ksc5601_hangul_to_unicode [2350]
static const unsigned short ksc5601_hanja_to_unicode [4888]
static const unsigned short ksc5601_symbol_to_unicode [1115]
static const struct map unicode_to_ksc5601_hanja [4888]
static const struct map unicode_to_ksc5601_symbol [986]
Macro Definition Documentation
IsCP949Char
#define IsCP949Char (c) (((c) >= 0x81) && ((c) <= 0xa0))
Definition at line 82 of file qeuckrcodec.cpp.
Referenced by QCP949Codec::convertToUnicode().
IsEucChar
#define IsEucChar (c) (((c) >= 0xa1) && ((c) <= 0xfe))
Definition at line 81 of file qeuckrcodec.cpp.
Referenced by QEucKrCodec::convertToUnicode(), and QCP949Codec::convertToUnicode().
QValidChar
#define QValidChar (u) ((u) ? QChar((ushort)(u)) : QChar(QChar::ReplacementCharacter))
Definition at line 83 of file qeuckrcodec.cpp.
Referenced by QEucKrCodec::convertToUnicode(), and QCP949Codec::convertToUnicode().
Function Documentation
ksc2unicode()
static unsigned short ksc2unicode (unsigned short code) static
Definition at line 3303 of file qeuckrcodec.cpp.
Referenced by QFontKsc5601Codec::convertFromUnicode(), and qt_Ksc5601ToUnicode().
 {
     int ch1 = code >> 8;
     int ch2 = code & 0x00ff;
     int idx;
     if (ch1 < 0x80 || (ch1 - 0x80) <= 0x20 || (ch1 - 0x80) >= 0x7e
       || (ch1 - 0x80) == 0x49)
         return 0;
     if (ch2 < 0x80 || (ch2 - 0x80) <= 0x20 || (ch2 - 0x80) >= 0x7f)
         return 0;
     idx = (ch1 - 0x80 - 0x21) * 94 + (ch2 - 0x80 - 0x21);
                 /* Hangul : row 16 - row 40 : 1410 = 15 * 94 ,
                                         3760 = 40 * 94 */
     if (idx >= 1410 && idx < 1410 + 2350)
         return ksc5601_hangul_to_unicode[idx - 1410];
     else if (idx >= 3854)
         /* Hanja : row 42 - row 93 : 3854 = 94 * (42-1) */
         return ksc5601_hanja_to_unicode[idx - 3854];
     else if(idx <= 1114)
         return ksc5601_symbol_to_unicode[idx];
     return 0;
 }
qt_Ksc5601ToUnicode()
unsigned int qt_Ksc5601ToUnicode (unsigned int code)
Definition at line 249 of file qeuckrcodec.cpp.
Referenced by QEucKrCodec::convertToUnicode(), and QCP949Codec::convertToUnicode().
 {
 #if 0
   printf("qt_Ksc5601ToUnicode : code = %x, unicode = %x\n",
       code, ksc2unicode((unsigned short)code));
 #endif
   return ksc2unicode((unsigned short)code);
 }
qt_UnicodeToKsc5601()
unsigned int qt_UnicodeToKsc5601 (unsigned int unicode)
Definition at line 258 of file qeuckrcodec.cpp.
Referenced by QEucKrCodec::convertFromUnicode(), QCP949Codec::convertFromUnicode(), and QFontKsc5601Codec::convertFromUnicode().
 {
 #if 0
   printf("qt_UnicodeToKsc5601 : unicode = %x, %x\n",
       unicode, unicode2ksc((unsigned short)unicode));
 #endif
   return unicode2ksc((unsigned short)unicode);
 }
unicode2ksc()
static unsigned short unicode2ksc (unsigned short code) static
Definition at line 3333 of file qeuckrcodec.cpp.
Referenced by QFontKsc5601Codec::convertFromUnicode(), and qt_UnicodeToKsc5601().
 {
     int lo, hi, mid, c2;
     unsigned char s[2];
     lo = mid = c2 = 0;
     if (unicode >= 0xac00 && unicode <= 0xd7a3) {
     // Hangul
         hi = 2349;
         while (lo <= hi) { // binary search
             mid = (lo + hi) / 2;
             c2 = ksc5601_hangul_to_unicode[mid];
             if(unicode < c2)
                 hi = mid - 1;
             else if(unicode > c2)
                 lo = mid + 1;
             else { // unicode == c2
                 s[0] = (mid / 94) + 0x30;
                 s[1] = (mid % 94) + 0x21;
                 return ((s[0] << 8) | s[1]);
             }
         }
     } else if ((unicode >= 0x4e00 && unicode <= 0x9fff)
             || (unicode >= 0xf900 && unicode <= 0xfa0b)) {
     // Hanja
         hi = 4887;
         while (lo <= hi) { // binary search
             mid = (lo + hi) / 2;
             c2 = unicode_to_ksc5601_hanja[mid].unicode;
             if(unicode < c2)
                 hi = mid - 1;
             else if(unicode > c2)
                 lo = mid + 1;
             else { // unicode == c2
                 return unicode_to_ksc5601_hanja[mid].kscode;
             }
         }
     } else {
     // Symbol
         hi = 985;
         while (lo <= hi) { // binary search
             mid = (lo + hi) / 2;
             c2 = unicode_to_ksc5601_symbol[mid].unicode;
             if(unicode < c2)
                 hi = mid - 1;
             else if(unicode > c2)
                 lo = mid + 1;
             else { // unicode == c2
                 return unicode_to_ksc5601_symbol[mid].kscode;
             }
         }
     }
     return 0;
 }
Variable Documentation
ksc5601_hangul_to_unicode
const unsigned short ksc5601_hangul_to_unicode[2350] static
Definition at line 268 of file qeuckrcodec.cpp.
Referenced by ksc2unicode(), and unicode2ksc().
ksc5601_hanja_to_unicode
const unsigned short ksc5601_hanja_to_unicode[4888] static
Definition at line 1052 of file qeuckrcodec.cpp.
Referenced by ksc2unicode().
ksc5601_symbol_to_unicode
const unsigned short ksc5601_symbol_to_unicode[1115] static
Definition at line 567 of file qeuckrcodec.cpp.
Referenced by ksc2unicode().
unicode_to_ksc5601_hanja
const struct map unicode_to_ksc5601_hanja[4888] static
Definition at line 1668 of file qeuckrcodec.cpp.
unicode_to_ksc5601_symbol
const struct map unicode_to_ksc5601_symbol[986] static
Definition at line 718 of file qeuckrcodec.cpp.