Qt 4.8: /src/corelib/kernel/qeventdispatcher_blackberry.cpp File Reference
qeventdispatcher_blackberry.cpp File Reference
#include "qeventdispatcher_blackberry_p.h"
#include "qsocketnotifier.h"
#include "qdebug.h"
#include "qelapsedtimer.h"
#include "private/qthread_p.h"
#include <bps/bps.h>
#include <bps/event.h>
Classes
class BBScopedLoopLevelCounter
class BpsChannelScopeSwitcher
struct bpsIOHandlerData
Macros
#define qEventDispatcherDebug QT_NO_QDEBUG_MACRO()
Functions
static int bpsIOHandler (int fd, int io_events, void *data)
static void destroyHeldBpsEvent (int holding_channel)
static int timevalToMillisecs (const timeval &tv)
Variables
static int bpsUnblockDomain = -1
Macro Definition Documentation
qEventDispatcherDebug
#define qEventDispatcherDebug QT_NO_QDEBUG_MACRO()
Definition at line 56 of file qeventdispatcher_blackberry.cpp.
Referenced by bpsIOHandler(), QEventDispatcherBlackberry::registerSocketNotifier(), and QEventDispatcherBlackberry::unregisterSocketNotifier().
Function Documentation
bpsIOHandler()
static int bpsIOHandler (int fd, int io_events, void * data) static
Definition at line 108 of file qeventdispatcher_blackberry.cpp.
Referenced by QEventDispatcherBlackberry::registerSocketNotifier(), and QEventDispatcherBlackberry::unregisterSocketNotifier().
 {
     qEventDispatcherDebug << Q_FUNC_INFO;
     // decode callback payload
     bpsIOHandlerData *ioData = static_cast<bpsIOHandlerData*>(data);
     // check if first file is ready
     bool firstReady = (ioData->count == 0);
     // update ready state of file
     if (io_events & BPS_IO_INPUT) {
         qEventDispatcherDebug << fd << "ready for Read";
         FD_SET(fd, ioData->readfds);
         ioData->count++;
     }
     if (io_events & BPS_IO_OUTPUT) {
         qEventDispatcherDebug << fd << "ready for Write";
         FD_SET(fd, ioData->writefds);
         ioData->count++;
     }
     if (io_events & BPS_IO_EXCEPT) {
         qEventDispatcherDebug << fd << "ready for Exception";
         FD_SET(fd, ioData->exceptfds);
         ioData->count++;
     }
     // force bps_get_event() to return immediately by posting an event to ourselves;
     // but this only needs to happen once if multiple files become ready at the same time
     if (firstReady) {
         qEventDispatcherDebug << "Sending bpsIOReadyDomain event";
         // create unblock event
         bps_event_t *event;
         int result = bps_event_create(&event, bpsUnblockDomain, 0, NULL, NULL);
         if (Q_UNLIKELY(result != BPS_SUCCESS)) {
             qWarning("QEventDispatcherBlackberry: bps_event_create failed");
             return BPS_FAILURE;
         }
         // post unblock event to our thread; in this callback the bps channel is
         // guaranteed to be the same that was active when bps_add_fd was called
         result = bps_push_event(event);
         if (Q_UNLIKELY(result != BPS_SUCCESS)) {
             qWarning("QEventDispatcherBlackberry: bps_push_event failed");
             bps_event_destroy(event);
             return BPS_FAILURE;
         }
     }
     return BPS_SUCCESS;
 }
destroyHeldBpsEvent()
static void destroyHeldBpsEvent (int holding_channel) inline static
Definition at line 305 of file qeventdispatcher_blackberry.cpp.
Referenced by QEventDispatcherBlackberry::select().
 {
     // Switch to the holding channel and use bps_get_event() to trigger its destruction.  We
     // don't care about the return value from this call to bps_get_event().
     BpsChannelScopeSwitcher holdingChannelSwitcher(holding_channel);
     bps_event_t *held_event = 0;
     (void)bps_get_event(&held_event, 0);
  }
timevalToMillisecs()
static int timevalToMillisecs (const timeval & tv) inline static
Definition at line 300 of file qeventdispatcher_blackberry.cpp.
Referenced by QEventDispatcherBlackberry::select().
 {
     return (tv.tv_sec * 1000) + (tv.tv_usec / 1000);
 }
Variable Documentation
bpsUnblockDomain
int bpsUnblockDomain = -1 static
Definition at line 106 of file qeventdispatcher_blackberry.cpp.
Referenced by bpsIOHandler(), QEventDispatcherBlackberryPrivate::QEventDispatcherBlackberryPrivate(), QEventDispatcherBlackberry::select(), and QEventDispatcherBlackberry::wakeUp().