Qt 4.8: /src/gui/kernel/qeventdispatcher_mac.mm File Reference
qeventdispatcher_mac.mm File Reference
#include "qplatformdefs.h"
#include "private/qt_mac_p.h"
#include "qeventdispatcher_mac_p.h"
#include "qapplication.h"
#include "qevent.h"
#include "qdialog.h"
#include "qhash.h"
#include "qsocketnotifier.h"
#include "private/qwidget_p.h"
#include "private/qthread_p.h"
#include "private/qapplication_p.h"
#include <private/qcocoaapplication_mac_p.h>
#include "private/qt_cocoa_helpers_mac_p.h"
#include "qmutex.h"
Functions
static CFRunLoopRef mainRunLoop ()
static void processPostedEvents (QEventDispatcherMacPrivate *const d, const bool blockSendPostedEvents)
MacTimerInfo * qt_event_get_timer (EventRef)
void qt_event_request_select (QEventDispatcherMac *)
void qt_event_request_timer (MacTimerInfo *)
void qt_event_request_updates ()
CFRunLoopSourceRef qt_mac_add_socket_to_runloop (const CFSocketRef socket)
bool qt_mac_is_macsheet (const QWidget *)
void qt_mac_remove_socket_from_runloop (const CFSocketRef socket, CFRunLoopSourceRef runloop)
static bool qt_mac_send_event (QEventLoop::ProcessEventsFlags, OSEventRef event, OSWindowRef pt)
void qt_mac_socket_callback (CFSocketRef s, CFSocketCallBackType callbackType, CFDataRef, const void *, void *info)
static void qt_mac_waitForMoreEvents ()
OSWindowRef qt_mac_window_for (const QWidget *)
bool qt_sendSpontaneousEvent (QObject *, QEvent *)
Variables
bool qt_is_gui_used
Function Documentation
mainRunLoop()
static CFRunLoopRef mainRunLoop () inline static
Definition at line 111 of file qeventdispatcher_mac.mm.
Referenced by QEventDispatcherMac::interrupt(), QEventDispatcherMac::QEventDispatcherMac(), qt_mac_add_socket_to_runloop(), qt_mac_remove_socket_from_runloop(), QEventDispatcherMac::registerTimer(), QEventDispatcherMac::wakeUp(), and QEventDispatcherMac::~QEventDispatcherMac().
 {
 #ifndef QT_MAC_USE_COCOA
     return reinterpret_cast<CFRunLoopRef>(const_cast<void *>(GetCFRunLoopFromEventLoop(GetMainEventLoop())));
 #else
     return CFRunLoopGetMain();
 #endif
 }
processPostedEvents()
static void processPostedEvents (QEventDispatcherMacPrivate *const d, const bool blockSendPostedEvents) inline static
Definition at line 1035 of file qeventdispatcher_mac.mm.
Referenced by QEventDispatcherMacPrivate::firstLoopEntry(), and QEventDispatcherMacPrivate::postedEventsSourcePerformCallback().
 {
     if (blockSendPostedEvents) {
         // We're told to not send posted events (because the event dispatcher
         // is currently working on setting up the correct session to run). But
         // we still need to make sure that we don't fall asleep until pending events
         // are sendt, so we just signal this need, and return:
         CFRunLoopSourceSignal(d->postedEventsSource);
         return;
     }
 #ifdef QT_MAC_USE_COCOA
     if (d->cleanupModalSessionsNeeded)
         d->cleanupModalSessions();
 #endif
     if (d->interrupt) {
 #ifdef QT_MAC_USE_COCOA
         if (d->currentExecIsNSAppRun) {
             // The event dispatcher has been interrupted. But since
             // [NSApplication run] is running the event loop, we
             // delayed stopping it until now (to let cocoa process
             // pending cocoa events first).
             if (d->currentModalSessionCached)
                 d->temporarilyStopAllModalSessions();
             [NSApp stop:NSApp];
             d->cancelWaitForMoreEvents();
         }
 #endif
         return;
     }
     if (!d->threadData->canWait || (d->serialNumber != d->lastSerial)) {
         d->lastSerial = d->serialNumber;
         QApplicationPrivate::sendPostedEvents(0, 0, d->threadData);
     }
 }
qt_event_get_timer()
MacTimerInfo* qt_event_get_timer (EventRef)
qt_event_request_select()
void qt_event_request_select (QEventDispatcherMac *)
qt_event_request_timer()
void qt_event_request_timer (MacTimerInfo *)
qt_event_request_updates()
void qt_event_request_updates ()
qt_mac_add_socket_to_runloop()
CFRunLoopSourceRef qt_mac_add_socket_to_runloop (const CFSocketRef socket)
Definition at line 290 of file qeventdispatcher_mac.mm.
Referenced by QEventDispatcherMac::registerSocketNotifier().
 {
     CFRunLoopSourceRef loopSource = CFSocketCreateRunLoopSource(kCFAllocatorDefault, socket, 0);
     if (!loopSource)
         return 0;
     CFRunLoopAddSource(mainRunLoop(), loopSource, kCFRunLoopCommonModes);
     return loopSource;
 }
qt_mac_is_macsheet()
bool qt_mac_is_macsheet (const QWidget *)
Definition at line 295 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::hide_sys(), make_win_eventUPP(), qt_mac_unregister_widget(), and QWidgetPrivate::show_sys().
 {
     if (!w)
         return false;
     Qt::WindowModality modality = w->windowModality();
     if (modality == Qt::ApplicationModal)
         return false;
     return w->parentWidget() && (modality == Qt::WindowModal || w->windowType() == Qt::Sheet);
 }
qt_mac_remove_socket_from_runloop()
void qt_mac_remove_socket_from_runloop (const CFSocketRef socket, CFRunLoopSourceRef runloop)
Definition at line 303 of file qeventdispatcher_mac.mm.
Referenced by QEventDispatcherMac::unregisterSocketNotifier(), and QEventDispatcherMac::~QEventDispatcherMac().
 {
     Q_ASSERT(runloop);
     CFRunLoopRemoveSource(mainRunLoop(), runloop, kCFRunLoopCommonModes);
     CFSocketDisableCallBacks(socket, kCFSocketReadCallBack);
     CFSocketDisableCallBacks(socket, kCFSocketWriteCallBack);
     CFRunLoopSourceInvalidate(runloop);
 }
qt_mac_send_event()
static bool qt_mac_send_event (QEventLoop::ProcessEventsFlags , OSEventRef event, OSWindowRef pt) static
Definition at line 454 of file qeventdispatcher_mac.mm.
Referenced by QEventDispatcherMac::processEvents().
 {
 #ifndef QT_MAC_USE_COCOA
     if(pt && SendEventToWindow(event, pt) != eventNotHandledErr)
         return true;
     return !SendEventToEventTarget(event, GetEventDispatcherTarget());
 #else // QT_MAC_USE_COCOA
     if (pt)
         [pt sendEvent:event];
     else
         [NSApp sendEvent:event];
     return true;
 #endif
 }
qt_mac_socket_callback()
void qt_mac_socket_callback (CFSocketRef s, CFSocketCallBackType callbackType, CFDataRef , const void * , void * info)
Definition at line 265 of file qeventdispatcher_mac.mm.
Referenced by QEventDispatcherMac::registerSocketNotifier().
{
     QEventDispatcherMacPrivate *const eventDispatcher
                                     = static_cast<QEventDispatcherMacPrivate *>(info);
     int nativeSocket = CFSocketGetNative(s);
     MacSocketInfo *socketInfo = eventDispatcher->macSockets.value(nativeSocket);
     QEvent notifierEvent(QEvent::SockAct);
     // There is a race condition that happen where we disable the notifier and
     // the kernel still has a notification to pass on. We then get this
     // notification after we've successfully disabled the CFSocket, but our Qt
     // notifier is now gone. The upshot is we have to check the notifier
     // everytime.
     if (callbackType == kCFSocketReadCallBack) {
         if (socketInfo->readNotifier)
             QApplication::sendEvent(socketInfo->readNotifier, &notifierEvent);
     } else if (callbackType == kCFSocketWriteCallBack) {
         if (socketInfo->writeNotifier)
             QApplication::sendEvent(socketInfo->writeNotifier, &notifierEvent);
     }
 }
qt_mac_waitForMoreEvents()
static void qt_mac_waitForMoreEvents () inline static
Definition at line 515 of file qeventdispatcher_mac.mm.
Referenced by QEventDispatcherMac::processEvents().
 {
 #ifndef QT_MAC_USE_COCOA
     while (CFRunLoopRunInMode(kCFRunLoopDefaultMode, 1.0e20, true) == kCFRunLoopRunTimedOut) ;
 #else
     // If no event exist in the cocoa event que, wait
     // (and free up cpu time) until at least one event occur.
     // This implementation is a bit on the edge, but seems to
     // work fine:
     NSEvent* event = [NSApp nextEventMatchingMask:NSAnyEventMask
         untilDate:[NSDate distantFuture]
         inMode:NSDefaultRunLoopMode
         dequeue:YES];
     if (event)
         [NSApp postEvent:event atStart:YES];
 #endif
 }
qt_mac_window_for()
OSWindowRef qt_mac_window_for (const QWidget *)
Definition at line 484 of file qwidget_mac.mm.
Referenced by QEventDispatcherMac::flush().
 {
     if (OSViewRef hiview = qt_mac_effectiveview_for(w)) {
         OSWindowRef window = qt_mac_window_for(hiview);
         if (window)
             return window;
         if (qt_isGenuineQWidget(hiview)) {
             // This is a workaround for NSToolbar. When a widget is hidden
             // by clicking the toolbar button, Cocoa reparents the widgets
             // to another window (but Qt doesn't know about it).
             // When we start showing them, it reparents back,
             // but at this point it's window is nil, but the window it's being brought
             // into (the Qt one) is for sure created.
             // This stops the hierarchy moving under our feet.
             QWidget *toplevel = w->window();
             if (toplevel != w) {
                 hiview = qt_mac_nativeview_for(toplevel);
                 if (OSWindowRef w = qt_mac_window_for(hiview))
                     return w;
             }
             toplevel->d_func()->createWindow_sys();
             // Reget the hiview since "create window" could potentially move the view (I guess).
             hiview = qt_mac_nativeview_for(toplevel);
             return qt_mac_window_for(hiview);
         }
     }
     return 0;
 }
qt_sendSpontaneousEvent()
bool qt_sendSpontaneousEvent (QObject * , QEvent *)
Definition at line 5779 of file qapplication.cpp.
Referenced by QEventDispatcherMacPrivate::activateTimer().
 {
     return QCoreApplication::sendSpontaneousEvent(receiver, event);
 }
Variable Documentation
qt_is_gui_used
bool qt_is_gui_used
Definition at line 492 of file qapplication.cpp.
Referenced by QEventDispatcherMac::hasPendingEvents().