Qt 4.8: /src/corelib/kernel/qeventdispatcher_glib.cpp File Reference
qeventdispatcher_glib.cpp File Reference
#include "qeventdispatcher_glib_p.h"
#include "qeventdispatcher_unix_p.h"
#include <private/qmutexpool_p.h>
#include <private/qthread_p.h>
#include "qcoreapplication.h"
#include "qsocketnotifier.h"
#include <QtCore/qhash.h>
#include <QtCore/qlist.h>
#include <QtCore/qpair.h>
#include <glib.h>
Classes
struct GIdleTimerSource
struct GPollFDWithQSocketNotifier
struct GPostEventSource
struct GSocketNotifierSource
struct GTimerSource
Functions
static gboolean idleTimerSourceCheck (GSource *source)
static gboolean idleTimerSourceDispatch (GSource *source, GSourceFunc, gpointer)
static gboolean idleTimerSourcePrepare (GSource *source, gint *timeout)
static gboolean postEventSourceCheck (GSource *source)
static gboolean postEventSourceDispatch (GSource *s, GSourceFunc, gpointer)
static gboolean postEventSourcePrepare (GSource *s, gint *timeout)
static gboolean socketNotifierSourceCheck (GSource *source)
static gboolean socketNotifierSourceDispatch (GSource *source, GSourceFunc, gpointer)
static gboolean socketNotifierSourcePrepare (GSource *, gint *timeout)
static gboolean timerSourceCheck (GSource *source)
static gboolean timerSourceCheckHelper (GTimerSource *src)
static gboolean timerSourceDispatch (GSource *source, GSourceFunc, gpointer)
static gboolean timerSourcePrepare (GSource *source, gint *timeout)
static gboolean timerSourcePrepareHelper (GTimerSource *src, gint *timeout)
Variables
static GSourceFuncs idleTimerSourceFuncs
static GSourceFuncs postEventSourceFuncs
static GSourceFuncs socketNotifierSourceFuncs
static GSourceFuncs timerSourceFuncs
Function Documentation
idleTimerSourceCheck()
static gboolean idleTimerSourceCheck (GSource * source) static
Definition at line 219 of file qeventdispatcher_glib.cpp.
 {
     GIdleTimerSource *idleTimerSource = reinterpret_cast<GIdleTimerSource *>(source);
     GTimerSource *timerSource = idleTimerSource->timerSource;
     if (!timerSource->runWithIdlePriority) {
         // Yield to the normal priority timer source
         return false;
     }
     return timerSourceCheckHelper(timerSource);
 }
idleTimerSourceDispatch()
static gboolean idleTimerSourceDispatch (GSource * source, GSourceFunc , gpointer) static
Definition at line 230 of file qeventdispatcher_glib.cpp.
 {
     GTimerSource *timerSource = reinterpret_cast<GIdleTimerSource *>(source)->timerSource;
     (void) timerSourceDispatch(&timerSource->source, 0, 0);
     return true;
 }
idleTimerSourcePrepare()
static gboolean idleTimerSourcePrepare (GSource * source, gint * timeout) static
Definition at line 205 of file qeventdispatcher_glib.cpp.
 {
     GIdleTimerSource *idleTimerSource = reinterpret_cast<GIdleTimerSource *>(source);
     GTimerSource *timerSource = idleTimerSource->timerSource;
     if (!timerSource->runWithIdlePriority) {
         // Yield to the normal priority timer source
         if (timeout)
             *timeout = -1;
         return false;
     }
     return timerSourcePrepareHelper(timerSource, timeout);
 }
postEventSourceCheck()
static gboolean postEventSourceCheck (GSource * source) static
Definition at line 271 of file qeventdispatcher_glib.cpp.
 {
     return postEventSourcePrepare(source, 0);
 }
postEventSourceDispatch()
static gboolean postEventSourceDispatch (GSource * s, GSourceFunc , gpointer) static
Definition at line 276 of file qeventdispatcher_glib.cpp.
 {
     GPostEventSource *source = reinterpret_cast<GPostEventSource *>(s);
     source->lastSerialNumber = source->serialNumber;
     QCoreApplication::sendPostedEvents();
     source->d->runTimersOnceWithNormalPriority();
     return true; // i dunno, george...
 }
postEventSourcePrepare()
static gboolean postEventSourcePrepare (GSource * s, gint * timeout) static
Definition at line 254 of file qeventdispatcher_glib.cpp.
Referenced by postEventSourceCheck().
 {
     QThreadData *data = QThreadData::current();
     if (!data)
         return false;
     gint dummy;
     if (!timeout)
         timeout = &dummy;
     const bool canWait = data->canWaitLocked();
     *timeout = canWait ? -1 : 0;
     GPostEventSource *source = reinterpret_cast<GPostEventSource *>(s);
     return (!canWait
             || (source->serialNumber != source->lastSerialNumber));
 }
socketNotifierSourceCheck()
static gboolean socketNotifierSourceCheck (GSource * source) static
Definition at line 78 of file qeventdispatcher_glib.cpp.
 {
     GSocketNotifierSource *src = reinterpret_cast<GSocketNotifierSource *>(source);
     bool pending = false;
     for (int i = 0; !pending && i < src->pollfds.count(); ++i) {
         GPollFDWithQSocketNotifier *p = src->pollfds.at(i);
         if (p->pollfd.revents & G_IO_NVAL) {
             // disable the invalid socket notifier
             static const char *t[] = { "Read", "Write", "Exception" };
             qWarning("QSocketNotifier: Invalid socket %d and type '%s', disabling...",
                      p->pollfd.fd, t[int(p->socketNotifier->type())]);
             // ### note, modifies src->pollfds!
             p->socketNotifier->setEnabled(false);
         }
         pending = ((p->pollfd.revents & p->pollfd.events) != 0);
     }
     return pending;
 }
socketNotifierSourceDispatch()
static gboolean socketNotifierSourceDispatch (GSource * source, GSourceFunc , gpointer) static
Definition at line 101 of file qeventdispatcher_glib.cpp.
 {
     QEvent event(QEvent::SockAct);
     GSocketNotifierSource *src = reinterpret_cast<GSocketNotifierSource *>(source);
     for (int i = 0; i < src->pollfds.count(); ++i) {
         GPollFDWithQSocketNotifier *p = src->pollfds.at(i);
         if ((p->pollfd.revents & p->pollfd.events) != 0)
             QCoreApplication::sendEvent(p->socketNotifier, &event);
     }
     return true; // ??? don't remove, right?
 }
socketNotifierSourcePrepare()
static gboolean socketNotifierSourcePrepare (GSource * , gint * timeout) static
Definition at line 71 of file qeventdispatcher_glib.cpp.
 {
     if (timeout)
         *timeout = -1;
     return false;
 }
timerSourceCheck()
static gboolean timerSourceCheck (GSource * source) static
Definition at line 172 of file qeventdispatcher_glib.cpp.
 {
     GTimerSource *src = reinterpret_cast<GTimerSource *>(source);
     if (src->runWithIdlePriority)
         return false;
     return timerSourceCheckHelper(src);
 }
timerSourceCheckHelper()
static gboolean timerSourceCheckHelper (GTimerSource * src) static
Definition at line 144 of file qeventdispatcher_glib.cpp.
Referenced by idleTimerSourceCheck(), and timerSourceCheck().
 {
     if (src->timerList.isEmpty()
         || (src->processEventsFlags & QEventLoop::X11ExcludeTimers))
         return false;
     if (src->timerList.updateCurrentTime() < src->timerList.first()->timeout)
         return false;
     return true;
 }
timerSourceDispatch()
static gboolean timerSourceDispatch (GSource * source, GSourceFunc , gpointer) static
Definition at line 180 of file qeventdispatcher_glib.cpp.
 {
     GTimerSource *timerSource = reinterpret_cast<GTimerSource *>(source);
     if (timerSource->processEventsFlags & QEventLoop::X11ExcludeTimers)
         return true;
     timerSource->runWithIdlePriority = true;
     (void) timerSource->timerList.activateTimers();
     return true; // ??? don't remove, right again?
 }
timerSourcePrepare()
static gboolean timerSourcePrepare (GSource * source, gint * timeout) static
Definition at line 156 of file qeventdispatcher_glib.cpp.
 {
     gint dummy;
     if (!timeout)
         timeout = &dummy;
     GTimerSource *src = reinterpret_cast<GTimerSource *>(source);
     if (src->runWithIdlePriority) {
         if (timeout)
             *timeout = -1;
         return false;
     }
     return timerSourcePrepareHelper(src, timeout);
 }
timerSourcePrepareHelper()
static gboolean timerSourcePrepareHelper (GTimerSource * src, gint * timeout) static
Definition at line 133 of file qeventdispatcher_glib.cpp.
Referenced by idleTimerSourcePrepare(), and timerSourcePrepare().
 {
     timeval tv = { 0l, 0l };
     if (!(src->processEventsFlags & QEventLoop::X11ExcludeTimers) && src->timerList.timerWait(tv))
         *timeout = (tv.tv_sec * 1000) + (tv.tv_usec / 1000);
     else
         *timeout = -1;
     return (*timeout == 0);
 }
Variable Documentation
idleTimerSourceFuncs
GSourceFuncs idleTimerSourceFuncs static
Initial value:
= {
    idleTimerSourcePrepare,
    idleTimerSourceCheck,
    idleTimerSourceDispatch,
    NULL,
    NULL,
    NULL
}
Definition at line 237 of file qeventdispatcher_glib.cpp.
postEventSourceFuncs
GSourceFuncs postEventSourceFuncs static
Initial value:
= {
    postEventSourcePrepare,
    postEventSourceCheck,
    postEventSourceDispatch,
    NULL,
    NULL,
    NULL
}
Definition at line 285 of file qeventdispatcher_glib.cpp.
Referenced by QEventDispatcherGlibPrivate::QEventDispatcherGlibPrivate().
socketNotifierSourceFuncs
GSourceFuncs socketNotifierSourceFuncs static
Initial value:
= {
    socketNotifierSourcePrepare,
    socketNotifierSourceCheck,
    socketNotifierSourceDispatch,
    NULL,
    NULL,
    NULL
}
Definition at line 116 of file qeventdispatcher_glib.cpp.
Referenced by QEventDispatcherGlibPrivate::QEventDispatcherGlibPrivate().
timerSourceFuncs
GSourceFuncs timerSourceFuncs static
Initial value:
= {
    timerSourcePrepare,
    timerSourceCheck,
    timerSourceDispatch,
    NULL,
    NULL,
    NULL
}
Definition at line 190 of file qeventdispatcher_glib.cpp.