Qt 4.8: /src/corelib/kernel/qeventdispatcher_win.cpp File Reference
qeventdispatcher_win.cpp File Reference
#include "qeventdispatcher_win_p.h"
#include "qcoreapplication.h"
#include "qhash.h"
#include <private/qsystemlibrary_p.h>
#include "qpair.h"
#include "qset.h"
#include "qsocketnotifier.h"
#include "qvarlengtharray.h"
#include "qwineventnotifier_p.h"
#include "qabstracteventdispatcher_p.h"
#include "qcoreapplication_p.h"
#include <private/qthread_p.h>
#include <winsock.h>
#include <qthread.h>
#include <qmap.h>
#include <qmutex.h>
Classes
class QEventDispatcherWin32Private
struct QSockNot
class QZeroTimerEvent
struct WinTimerInfo
Macros
#define DWORD_PTR DWORD
#define QS_RAWINPUT 0x0000
#define TIME_KILL_SYNCHRONOUS 0x0100
#define WM_GESTURE 0x0119
#define WM_GESTURENOTIFY 0x011A
#define WM_TOUCH 0x0240
Typedefs
typedef MMRESULT(WINAPI * ptimeKillEvent) (UINT)
typedef MMRESULT(WINAPI * ptimeSetEvent) (UINT, UINT, LPTIMECALLBACK, DWORD_PTR, UINT)
typedef QHash< int, QSockNot * > QSNDict
typedef QHash< int, WinTimerInfo * > WinTimerDict
typedef QList< WinTimerInfo * > WinTimerVec
Enumerations
enum { WM_QT_SOCKETNOTIFIER = WM_USER, WM_QT_SENDPOSTEDEVENTS = WM_USER + 1, SendPostedEventsWindowsTimerId = ~1u }
Functions
static UINT inputTimerMask ()
uint qGlobalPostedEventsCount ()
static HWND qt_create_internal_window (const QEventDispatcherWin32 *eventDispatcher)
void WINAPI QT_WIN_CALLBACK qt_fast_timer_proc (uint timerId, uint, DWORD_PTR user, DWORD_PTR, DWORD_PTR)
LRESULT QT_WIN_CALLBACK qt_GetMessageHook (int code, WPARAM wp, LPARAM lp)
LRESULT QT_WIN_CALLBACK qt_internal_proc (HWND hwnd, UINT message, WPARAM wp, LPARAM lp)
HINSTANCE qWinAppInst ()
static void resolveTimerAPI ()
Q_CORE_EXPORT bool winGetMessage (MSG *msg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax)
Q_CORE_EXPORT bool winPeekMessage (MSG *msg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax, UINT wRemoveMsg)
Q_CORE_EXPORT bool winPostMessage (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
int WSAAsyncSelect (SOCKET sock, HWND handle, unsigned int msg, long ev)
Variables
static ptimeKillEvent qtimeKillEvent = 0
static ptimeSetEvent qtimeSetEvent = 0
Macro Definition Documentation
DWORD_PTR
#define DWORD_PTR DWORD
Definition at line 309 of file qeventdispatcher_win.cpp.
Referenced by QAudioOutputPrivate::freeBlocks(), QAudioInputPrivate::freeBlocks(), and QEventDispatcherWin32Private::registerTimer().
QS_RAWINPUT
#define QS_RAWINPUT 0x0000
Definition at line 68 of file qeventdispatcher_win.cpp.
Referenced by inputTimerMask().
TIME_KILL_SYNCHRONOUS
#define TIME_KILL_SYNCHRONOUS 0x0100
Definition at line 63 of file qeventdispatcher_win.cpp.
Referenced by QEventDispatcherWin32Private::registerTimer().
WM_GESTURE
#define WM_GESTURE 0x0119
Definition at line 79 of file qeventdispatcher_win.cpp.
Referenced by QEventDispatcherWin32::processEvents(), and QtWndProc().
WM_GESTURENOTIFY
#define WM_GESTURENOTIFY 0x011A
Definition at line 82 of file qeventdispatcher_win.cpp.
Referenced by QEventDispatcherWin32::processEvents().
WM_TOUCH
#define WM_TOUCH 0x0240
Definition at line 75 of file qeventdispatcher_win.cpp.
Referenced by QEventDispatcherWin32::processEvents().
Typedef Documentation
ptimeKillEvent
typedef MMRESULT(WINAPI * ptimeKillEvent) (UINT)
Definition at line 313 of file qeventdispatcher_win.cpp.
ptimeSetEvent
typedef MMRESULT(WINAPI * ptimeSetEvent) (UINT, UINT, LPTIMECALLBACK, DWORD_PTR, UINT)
Definition at line 312 of file qeventdispatcher_win.cpp.
QSNDict
typedef QHash<int, QSockNot *> QSNDict
Definition at line 286 of file qeventdispatcher_win.cpp.
WinTimerDict
typedef QHash<int, WinTimerInfo*> WinTimerDict
Definition at line 306 of file qeventdispatcher_win.cpp.
WinTimerVec
typedef QList<WinTimerInfo*> WinTimerVec
Definition at line 305 of file qeventdispatcher_win.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
WM_QT_SOCKETNOTIFIER
WM_QT_SENDPOSTEDEVENTS
SendPostedEventsWindowsTimerId
Definition at line 86 of file qeventdispatcher_win.cpp.
      {
     WM_QT_SOCKETNOTIFIER = WM_USER,
     WM_QT_SENDPOSTEDEVENTS = WM_USER + 1,
     SendPostedEventsWindowsTimerId = ~1u
 };
Function Documentation
inputTimerMask()
static UINT inputTimerMask () inline static
Definition at line 508 of file qeventdispatcher_win.cpp.
Referenced by qt_GetMessageHook().
 {
     UINT result = QS_TIMER | QS_INPUT | QS_RAWINPUT;
     // QTBUG 28513, QTBUG-29097, QTBUG-29435: QS_TOUCH, QS_POINTER became part of
     // QS_INPUT in Windows Kit 8. They should not be used when running on pre-Windows 8.
 #if defined(_MSC_VER) && _MSC_VER >= 1700
     if (QSysInfo::WindowsVersion < QSysInfo::WV_WINDOWS8)
         result &= ~(QS_TOUCH | QS_POINTER);
 #endif //  _MSC_VER >= 1700
     return result;
 }
qGlobalPostedEventsCount()
uint qGlobalPostedEventsCount ()
Definition at line 348 of file qcoreapplication.cpp.
Referenced by QEventDispatcherWin32::hasPendingEvents().
 {
     QThreadData *currentThreadData = QThreadData::current();
     return currentThreadData->postEventList.size() - currentThreadData->postEventList.startOffset;
 }
qt_create_internal_window()
static HWND qt_create_internal_window (const QEventDispatcherWin32 * eventDispatcher) static
Definition at line 565 of file qeventdispatcher_win.cpp.
Referenced by QEventDispatcherWin32::createInternalHwnd().
 {
     // make sure that multiple Qt's can coexist in the same process
     QString className = QLatin1String("QEventDispatcherWin32_Internal_Widget") + QString::number(quintptr(qt_internal_proc));
     WNDCLASS wc;
     wc.style = 0;
     wc.lpfnWndProc = qt_internal_proc;
     wc.cbClsExtra = 0;
     wc.cbWndExtra = 0;
     wc.hInstance = qWinAppInst();
     wc.hIcon = 0;
     wc.hCursor = 0;
     wc.hbrBackground = 0;
     wc.lpszMenuName = NULL;
     wc.lpszClassName = reinterpret_cast<const wchar_t *> (className.utf16());
     RegisterClass(&wc);
     HWND wnd = CreateWindow(wc.lpszClassName,  // classname
                             wc.lpszClassName,  // window name
                             0,                 // style
                             0, 0, 0, 0,        // geometry
                             0,                 // parent
                             0,                 // menu handle
                             qWinAppInst(),     // application
                             0);                // windows creation data.
     if (!wnd) {
         qWarning("QEventDispatcher: Failed to create QEventDispatcherWin32 internal window: %d\n", (int)GetLastError());
     }
 #ifdef GWLP_USERDATA
     SetWindowLongPtr(wnd, GWLP_USERDATA, (LONG_PTR)eventDispatcher);
 #else
     SetWindowLong(wnd, GWL_USERDATA, (LONG)eventDispatcher);
 #endif
     return wnd;
 }
qt_fast_timer_proc()
void WINAPI QT_WIN_CALLBACK qt_fast_timer_proc (uint timerId, uint , DWORD_PTR user, DWORD_PTR , DWORD_PTR)
Definition at line 421 of file qeventdispatcher_win.cpp.
Referenced by QEventDispatcherWin32Private::registerTimer().
 {
     if (!timerId) // sanity check
         return;
     WinTimerInfo *t = (WinTimerInfo*)user;
     Q_ASSERT(t);
     QCoreApplication::postEvent(t->dispatcher, new QTimerEvent(t->timerId));
 }
qt_GetMessageHook()
LRESULT QT_WIN_CALLBACK qt_GetMessageHook (int code, WPARAM wp, LPARAM lp)
Definition at line 520 of file qeventdispatcher_win.cpp.
Referenced by QEventDispatcherWin32::createInternalHwnd().
 {
     if (wp == PM_REMOVE) {
         QEventDispatcherWin32 *q = qobject_cast<QEventDispatcherWin32 *>(QAbstractEventDispatcher::instance());
         Q_ASSERT(q != 0);
         if (q) {
             MSG *msg = (MSG *) lp;
             QEventDispatcherWin32Private *d = q->d_func();
             int localSerialNumber = d->serialNumber;
             static const UINT mask = inputTimerMask();
             if (HIWORD(GetQueueStatus(mask)) == 0) {
                 // no more input or timer events in the message queue, we can allow posted events to be sent normally now
                 if (d->sendPostedEventsWindowsTimerId != 0) {
                     // stop the timer to send posted events, since we now allow the WM_QT_SENDPOSTEDEVENTS message
                     KillTimer(d->internalHwnd, d->sendPostedEventsWindowsTimerId);
                     d->sendPostedEventsWindowsTimerId = 0;
                 }
                 (void) d->wakeUps.fetchAndStoreRelease(0);
                 if (localSerialNumber != d->lastSerialNumber
                     // if this message IS the one that triggers sendPostedEvents(), no need to post it again
                     && (msg->hwnd != d->internalHwnd
                         || msg->message != WM_QT_SENDPOSTEDEVENTS)) {
                     PostMessage(d->internalHwnd, WM_QT_SENDPOSTEDEVENTS, 0, 0);
                 }
             } else if (d->sendPostedEventsWindowsTimerId == 0
                        && localSerialNumber != d->lastSerialNumber) {
                 // start a special timer to continue delivering posted events while
                 // there are still input and timer messages in the message queue
                 d->sendPostedEventsWindowsTimerId = SetTimer(d->internalHwnd,
                                                              SendPostedEventsWindowsTimerId,
                                                              0, // we specify zero, but Windows uses USER_TIMER_MINIMUM
                                                              NULL);
                 // we don't check the return value of SetTimer()... if creating the timer failed, there's little
                 // we can do. we just have to accept that posted events will be starved
             }
         }
     }
 #ifdef Q_OS_WINCE
     Q_UNUSED(code);
     return 0;
 #else
     return CallNextHookEx(0, code, wp, lp);
 #endif
 }
qt_internal_proc()
LRESULT QT_WIN_CALLBACK qt_internal_proc (HWND hwnd, UINT message, WPARAM wp, LPARAM lp)
Definition at line 430 of file qeventdispatcher_win.cpp.
Referenced by qt_create_internal_window(), and QEventDispatcherWin32Private::~QEventDispatcherWin32Private().
 {
     if (message == WM_NCCREATE)
         return true;
     MSG msg;
     msg.hwnd = hwnd;
     msg.message = message;
     msg.wParam = wp;
     msg.lParam = lp;
     QCoreApplication *app = QCoreApplication::instance();
     long result;
     if (!app) {
         if (message == WM_TIMER)
             KillTimer(hwnd, wp);
         return 0;
     } else if (app->filterEvent(&msg, &result)) {
         return result;
     }
 #ifdef GWLP_USERDATA
     QEventDispatcherWin32 *q = (QEventDispatcherWin32 *) GetWindowLongPtr(hwnd, GWLP_USERDATA);
 #else
     QEventDispatcherWin32 *q = (QEventDispatcherWin32 *) GetWindowLong(hwnd, GWL_USERDATA);
 #endif
     QEventDispatcherWin32Private *d = 0;
     if (q != 0)
         d = q->d_func();
     if (message == WM_QT_SOCKETNOTIFIER) {
         // socket notifier message
         int type = -1;
         switch (WSAGETSELECTEVENT(lp)) {
         case FD_READ:
         case FD_CLOSE:
         case FD_ACCEPT:
             type = 0;
             break;
         case FD_WRITE:
         case FD_CONNECT:
             type = 1;
             break;
         case FD_OOB:
             type = 2;
             break;
         }
         if (type >= 0) {
             Q_ASSERT(d != 0);
             QSNDict *sn_vec[3] = { &d->sn_read, &d->sn_write, &d->sn_except };
             QSNDict *dict = sn_vec[type];
             QSockNot *sn = dict ? dict->value(wp) : 0;
             if (sn) {
                 QEvent event(QEvent::SockAct);
                 QCoreApplication::sendEvent(sn->obj, &event);
             }
         }
         return 0;
     } else if (message == WM_QT_SENDPOSTEDEVENTS
                // we also use a Windows timer to send posted events when the message queue is full
                || (message == WM_TIMER
                    && d->sendPostedEventsWindowsTimerId != 0
                    && wp == (uint)d->sendPostedEventsWindowsTimerId)) {
         int localSerialNumber = d->serialNumber;
         if (localSerialNumber != d->lastSerialNumber) {
             d->lastSerialNumber = localSerialNumber;
             QCoreApplicationPrivate::sendPostedEvents(0, 0, d->threadData);
         }
         return 0;
     } else if (message == WM_TIMER) {
         Q_ASSERT(d != 0);
         d->sendTimerEvent(wp);
         return 0;
     }
     return DefWindowProc(hwnd, message, wp, lp);
 }
qWinAppInst()
HINSTANCE qWinAppInst ()
Definition at line 58 of file qcoreapplication_win.cpp.
Referenced by qt_create_internal_window(), and QEventDispatcherWin32Private::~QEventDispatcherWin32Private().
 {
     return GetModuleHandle(0);
 }
resolveTimerAPI()
static void resolveTimerAPI () static
Definition at line 320 of file qeventdispatcher_win.cpp.
Referenced by QEventDispatcherWin32Private::QEventDispatcherWin32Private().
 {
     static bool triedResolve = false;
     if (!triedResolve) {
 #ifdef Q_OS_WINCE
         QSystemLibrary library(QLatin1String("Mmtimer"));
 #else
         QSystemLibrary library(QLatin1String("winmm"));
 #endif
         if (library.load()) {
             qtimeSetEvent = (ptimeSetEvent)library.resolve("timeSetEvent");
             qtimeKillEvent = (ptimeKillEvent)library.resolve("timeKillEvent");
         }
         triedResolve = true;
     }
 }
winGetMessage()
Q_CORE_EXPORT bool winGetMessage (MSG * msg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax)
Definition at line 414 of file qeventdispatcher_win.cpp.
 {
     return GetMessage(msg, hWnd, wMsgFilterMin, wMsgFilterMax);
 }
winPeekMessage()
Q_CORE_EXPORT bool winPeekMessage (MSG * msg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax, UINT wRemoveMsg)
Definition at line 401 of file qeventdispatcher_win.cpp.
 {
     return PeekMessage(msg, hWnd, wMsgFilterMin, wMsgFilterMax, wRemoveMsg);
 }
winPostMessage()
Q_CORE_EXPORT bool winPostMessage (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
Definition at line 408 of file qeventdispatcher_win.cpp.
 {
     return PostMessage(hWnd, msg, wParam, lParam);
 }
WSAAsyncSelect()
int WSAAsyncSelect (SOCKET sock, HWND handle, unsigned int msg, long ev)
Definition at line 256 of file qeventdispatcher_win.cpp.
Referenced by QEventDispatcherWin32Private::doWsaAsyncSelect().
 {
     if (sock == 0 || handle == 0 || handle == INVALID_HANDLE_VALUE) {
         WSASetLastError(WSAEINVAL);
         return SOCKET_ERROR;
     }
     if (msg == 0 && ev == 0)
         qt_async_handler()->safeRemove(sock);
     else
         qt_async_handler()->select(sock, handle, msg, ev);
     qt_async_handler()->start(QThread::LowPriority);
     WSASetLastError(0);
     return 0;
 }
Variable Documentation
qtimeKillEvent
ptimeKillEvent qtimeKillEvent = 0 static
Definition at line 316 of file qeventdispatcher_win.cpp.
Referenced by resolveTimerAPI(), and QEventDispatcherWin32Private::unregisterTimer().
qtimeSetEvent
ptimeSetEvent qtimeSetEvent = 0 static
Definition at line 315 of file qeventdispatcher_win.cpp.
Referenced by QEventDispatcherWin32Private::registerTimer(), and resolveTimerAPI().