Qt 4.8: /src/gui/dialogs/qfiledialog_mac.mm File Reference
qfiledialog_mac.mm File Reference
#include "qfiledialog.h"
#include <qapplication.h>
#include <private/qapplication_p.h>
#include <private/qfiledialog_p.h>
#include <private/qt_mac_p.h>
#include <private/qt_cocoa_helpers_mac_p.h>
#include <qregexp.h>
#include <qbuffer.h>
#include <qdebug.h>
#include <qstringlist.h>
#include <qaction.h>
#include <qtextcodec.h>
#include <qvarlengtharray.h>
#include <qdesktopwidget.h>
#include <stdlib.h>
#include <qabstracteventdispatcher.h>
#import <AppKit/NSSavePanel.h>
#include "ui_qfiledialog.h"
Classes
class QNSOpenSavePanelDelegate
Functions
QStringList qt_clean_filter_list (const QString &filter)
static QFileDialogPrivate::QtMacFilterName qt_mac_extract_filter (const QString &rawFilter, bool showDetails)
bool qt_mac_is_macsheet (const QWidget *w)
static QList< QFileDialogPrivate::QtMacFilterName > qt_mac_make_filters_list (const QString &filter, bool showDetails)
QStringList qt_make_filter_list (const QString &filter)
Variables
const char * qt_file_dialog_filter_reg_exp
Function Documentation
qt_clean_filter_list()
QStringList qt_clean_filter_list (const QString & filter)
Definition at line 3189 of file qfiledialog.cpp.
Referenced by QFileDialogPrivate::_q_useNameFilter(), and QNSOpenSavePanelDelegate::findStrippedFilterWithVisualFilterName:.
 {
     QRegExp regexp(QString::fromLatin1(qt_file_dialog_filter_reg_exp));
     QString f = filter;
     int i = regexp.indexIn(f);
     if (i >= 0)
         f = regexp.cap(2);
     return f.split(QLatin1Char(' '), QString::SkipEmptyParts);
 }
qt_mac_extract_filter()
static QFileDialogPrivate::QtMacFilterName qt_mac_extract_filter (const QString & rawFilter, bool showDetails) static
Definition at line 952 of file qfiledialog_mac.mm.
Referenced by qt_mac_make_filters_list().
 {
     QFileDialogPrivate::QtMacFilterName ret;
     ret.filter = rawFilter;
     QString result = rawFilter;
     QRegExp r(QString::fromLatin1(qt_file_dialog_filter_reg_exp));
     int index = r.indexIn(result);
     if (index >= 0)
         result = r.cap(2);
     if (showDetails) {
         ret.description = rawFilter;
     } else {
         if (index >= 0)
             ret.description = r.cap(1).trimmed();
         if (ret.description.isEmpty())
             ret.description = result;
     }
     ret.regexp = result.replace(QLatin1Char(' '), QLatin1Char(';'));
     return ret;
 }
qt_mac_is_macsheet()
bool qt_mac_is_macsheet (const QWidget * w)
Definition at line 295 of file qwidget_mac.mm.
Referenced by QFileDialogPrivate::createNavServicesDialog(), and QFileDialogPrivate::hideCarbonNavServicesDialog().
 {
     if (!w)
         return false;
     Qt::WindowModality modality = w->windowModality();
     if (modality == Qt::ApplicationModal)
         return false;
     return w->parentWidget() && (modality == Qt::WindowModal || w->windowType() == Qt::Sheet);
 }
qt_mac_make_filters_list()
static QList<QFileDialogPrivate::QtMacFilterName> qt_mac_make_filters_list (const QString & filter, bool showDetails) static
Definition at line 974 of file qfiledialog_mac.mm.
Referenced by QFileDialogPrivate::createNavServicesDialog().
 {
 #ifdef DEBUG_FILEDIALOG_FILTERS
     qDebug("QFileDialog:%d - Got filter (%s)", __LINE__, filter.latin1());
 #endif
     QList<QFileDialogPrivate::QtMacFilterName> ret;
     QString f(filter);
     if (f.isEmpty())
         f = QFileDialog::tr("All Files (*)");
     if (f.isEmpty())
         return ret;
     QStringList filts = qt_make_filter_list(f);
     for (QStringList::const_iterator it = filts.constBegin(); it != filts.constEnd(); ++it) {
         QFileDialogPrivate::QtMacFilterName filter = qt_mac_extract_filter(*it, showDetails);
 #ifdef DEBUG_FILEDIALOG_FILTERS
         qDebug("QFileDialog:%d Split out filter (%d) '%s' '%s' [%s]", __LINE__, ret.count(),
                 filter->regxp.latin1(), filter->description.latin1(), (*it).latin1());
 #endif
         ret.append(filter);
     }
     return ret;
 }
qt_make_filter_list()
QStringList qt_make_filter_list (const QString & filter)
Definition at line 1075 of file qfiledialog.cpp.
Referenced by qt_mac_make_filters_list().
 {
     QString f(filter);
     if (f.isEmpty())
         return QStringList();
     QString sep(QLatin1String(";;"));
     int i = f.indexOf(sep, 0);
     if (i == -1) {
         if (f.indexOf(QLatin1Char('\n'), 0) != -1) {
             sep = QLatin1Char('\n');
             i = f.indexOf(sep, 0);
         }
     }
     return f.split(sep);
 }
Variable Documentation
qt_file_dialog_filter_reg_exp
const char* qt_file_dialog_filter_reg_exp
Definition at line 438 of file qfiledialog.cpp.
Referenced by qt_mac_extract_filter(), and QNSOpenSavePanelDelegate::removeExtensions:.