Qt 4.8: /src/corelib/io/qfile.cpp File Reference
qfile.cpp File Reference
#include "qplatformdefs.h"
#include "qdebug.h"
#include "qfile.h"
#include "qfsfileengine.h"
#include "qtemporaryfile.h"
#include "qlist.h"
#include "qfileinfo.h"
#include "private/qiodevice_p.h"
#include "private/qfile_p.h"
#include "private/qsystemerror_p.h"
Functions
static qint64 _qfile_writeData (QAbstractFileEngine *engine, QRingBuffer *buffer)
static QString locale_decode (const QByteArray &f)
static QByteArray locale_encode (const QString &f)
Variables
static const int QFILE_WRITEBUFFER_SIZE = 16384
Function Documentation
_qfile_writeData()
static qint64 _qfile_writeData (QAbstractFileEngine * engine, QRingBuffer * buffer) inline static
Definition at line 1631 of file qfile.cpp.
Referenced by QFile::flush().
 {
     qint64 ret = engine->write(buffer->readPointer(), buffer->nextDataBlockSize());
     if (ret > 0)
         buffer->free(ret);
     return ret;
 }
locale_decode()
static QString locale_decode (const QByteArray & f) static
Definition at line 76 of file qfile.cpp.
Referenced by QFile::setDecodingFunction().
 {
 #if defined(Q_OS_DARWIN)
     // Mac always gives us UTF-8 and decomposed, we want that composed...
     return QString::fromUtf8(f).normalized(QString::NormalizationForm_C);
 #elif defined(Q_OS_SYMBIAN)
     return QString::fromUtf8(f);
 #else
     return QString::fromLocal8Bit(f);
 #endif
 }
locale_encode()
static QByteArray locale_encode (const QString & f) static
Definition at line 64 of file qfile.cpp.
Referenced by locale_decode(), and QFile::setEncodingFunction().
 {
 #if defined(Q_OS_DARWIN)
     // Mac always expects UTF-8... and decomposed...
     return f.normalized(QString::NormalizationForm_D).toUtf8();
 #elif defined(Q_OS_SYMBIAN)
     return f.toUtf8();
 #else
     return f.toLocal8Bit();
 #endif
 }
Variable Documentation
QFILE_WRITEBUFFER_SIZE
const int QFILE_WRITEBUFFER_SIZE = 16384 static
Definition at line 62 of file qfile.cpp.
Referenced by QFilePrivate::putCharHelper(), and QFile::writeData().