Qt 4.8: /src/gui/dialogs/qfiledialog.cpp File Reference
qfiledialog.cpp File Reference
#include <qvariant.h>
#include <private/qwidgetitemdata_p.h>
#include "qfiledialog.h"
#include "qfiledialog_p.h"
#include <qfontmetrics.h>
#include <qaction.h>
#include <qheaderview.h>
#include <qshortcut.h>
#include <qgridlayout.h>
#include <qmenu.h>
#include <qmessagebox.h>
#include <qinputdialog.h>
#include <stdlib.h>
#include <qsettings.h>
#include <qdebug.h>
#include <qapplication.h>
#include <qstylepainter.h>
#include <itemviews/qfileiconprovider_p.h>
#include "ui_qfiledialog_embedded.h"
#include <pwd.h>
#include <qwindowsstyle.h>
#include <qmacstyle_mac.h>
#include "moc_qfiledialog.cpp"
Macros
#define Q_EMBEDDED_SMALLSCREEN
Typedefs
typedef QString(* _qt_filedialog_existing_directory_hook) (QWidget *parent, const QString &caption, const QString &dir, QFileDialog::Options options)
typedef QString(* _qt_filedialog_open_filename_hook) (QWidget *parent, const QString &caption, const QString &dir, const QString &filter, QString *selectedFilter, QFileDialog::Options options)
typedef QStringList(* _qt_filedialog_open_filenames_hook) (QWidget *parent, const QString &caption, const QString &dir, const QString &filter, QString *selectedFilter, QFileDialog::Options options)
typedef QString(* _qt_filedialog_save_filename_hook) (QWidget *parent, const QString &caption, const QString &dir, const QString &filter, QString *selectedFilter, QFileDialog::Options options)
Functions
static QString _qt_get_directory (const QString &path)
QStringList qt_clean_filter_list (const QString &filter)
QStringList qt_make_filter_list (const QString &filter)
QStringList qt_strip_filters (const QStringList &filters)
Q_AUTOTEST_EXPORT QString qt_tildeExpansion (const QString &path, bool *expanded=0)
QString qt_win_get_existing_directory (const QFileDialogArgs &args)
QString qt_win_get_open_file_name (const QFileDialogArgs &args, QString *initialDirectory, QString *selectedFilter)
QStringList qt_win_get_open_file_names (const QFileDialogArgs &args, QString *initialDirectory, QString *selectedFilter)
QString qt_win_get_save_file_name (const QFileDialogArgs &args, QString *initialDirectory, QString *selectedFilter)
Variables
static const qint32 QFileDialogMagic = 0xbe
const char * qt_file_dialog_filter_reg_exp
Q_GUI_EXPORT _qt_filedialog_existing_directory_hook qt_filedialog_existing_directory_hook = 0
Q_GUI_EXPORT _qt_filedialog_open_filename_hook qt_filedialog_open_filename_hook = 0
Q_GUI_EXPORT _qt_filedialog_open_filenames_hook qt_filedialog_open_filenames_hook = 0
Q_GUI_EXPORT _qt_filedialog_save_filename_hook qt_filedialog_save_filename_hook = 0
bool qt_priv_ptr_valid
bool Q_GUI_EXPORT qt_use_native_dialogs = true
Macro Definition Documentation
Q_EMBEDDED_SMALLSCREEN
#define Q_EMBEDDED_SMALLSCREEN
Definition at line 65 of file qfiledialog.cpp.
Typedef Documentation
_qt_filedialog_existing_directory_hook
typedef QString(* _qt_filedialog_existing_directory_hook) (QWidget *parent, const QString &caption, const QString &dir, QFileDialog::Options options)
Definition at line 84 of file qfiledialog.cpp.
_qt_filedialog_open_filename_hook
typedef QString(* _qt_filedialog_open_filename_hook) (QWidget *parent, const QString &caption, const QString &dir, const QString &filter, QString *selectedFilter, QFileDialog::Options options)
Definition at line 87 of file qfiledialog.cpp.
_qt_filedialog_open_filenames_hook
typedef QStringList(* _qt_filedialog_open_filenames_hook) (QWidget *parent, const QString &caption, const QString &dir, const QString &filter, QString *selectedFilter, QFileDialog::Options options)
Definition at line 90 of file qfiledialog.cpp.
_qt_filedialog_save_filename_hook
typedef QString(* _qt_filedialog_save_filename_hook) (QWidget *parent, const QString &caption, const QString &dir, const QString &filter, QString *selectedFilter, QFileDialog::Options options)
Definition at line 93 of file qfiledialog.cpp.
Function Documentation
_qt_get_directory()
static QString _qt_get_directory (const QString & path) inline static
Definition at line 2190 of file qfiledialog.cpp.
Referenced by QFileDialogPrivate::workingDirectory().
 {
     QFileInfo info = QFileInfo(QDir::current(), path);
     if (info.exists() && info.isDir())
         return QDir::cleanPath(info.absoluteFilePath());
     info.setFile(info.absolutePath());
     if (info.exists() && info.isDir())
         return info.absoluteFilePath();
     return QString();
 }
qt_clean_filter_list()
QStringList qt_clean_filter_list (const QString & filter)
Definition at line 3189 of file qfiledialog.cpp.
Referenced by QFileDialogPrivate::_q_useNameFilter(), and QNSOpenSavePanelDelegate::findStrippedFilterWithVisualFilterName:.
 {
     QRegExp regexp(QString::fromLatin1(qt_file_dialog_filter_reg_exp));
     QString f = filter;
     int i = regexp.indexIn(f);
     if (i >= 0)
         f = regexp.cap(2);
     return f.split(QLatin1Char(' '), QString::SkipEmptyParts);
 }
qt_make_filter_list()
QStringList qt_make_filter_list (const QString & filter)
Definition at line 1075 of file qfiledialog.cpp.
Referenced by QGtkStylePrivate::extract_filter(), qt_mac_make_filters_list(), qt_win_make_filters_list(), qt_win_resolve_libs(), QFileDialog::selectNameFilter(), QFileDialog::setNameFilter(), and QGtkStylePrivate::setupGtkFileChooser().
 {
     QString f(filter);
     if (f.isEmpty())
         return QStringList();
     QString sep(QLatin1String(";;"));
     int i = f.indexOf(sep, 0);
     if (i == -1) {
         if (f.indexOf(QLatin1Char('\n'), 0) != -1) {
             sep = QLatin1Char('\n');
             i = f.indexOf(sep, 0);
         }
     }
     return f.split(sep);
 }
qt_strip_filters()
QStringList qt_strip_filters (const QStringList & filters)
Definition at line 1155 of file qfiledialog.cpp.
Referenced by QFileDialog::selectNameFilter(), and QFileDialog::setNameFilters().
 {
     QStringList strippedFilters;
     QRegExp r(QString::fromLatin1(qt_file_dialog_filter_reg_exp));
     for (int i = 0; i < filters.count(); ++i) {
         QString filterName;
         int index = r.indexIn(filters[i]);
         if (index >= 0)
             filterName = r.cap(1);
         strippedFilters.append(filterName.simplified());
     }
     return strippedFilters;
 }
qt_tildeExpansion()
Q_AUTOTEST_EXPORT QString qt_tildeExpansion (const QString & path, bool * expanded = 0)
Definition at line 932 of file qfiledialog.cpp.
Referenced by QFSCompleter::splitPath(), and QFileDialogPrivate::typedFiles().
 {
     if (expanded != 0)
         *expanded = false;
     if (!path.startsWith(QLatin1Char('~')))
         return path;
     QString ret = path;
 #if !defined(Q_OS_INTEGRITY)
     QStringList tokens = ret.split(QDir::separator());
     if (tokens.first() == QLatin1String("~")) {
         ret.replace(0, 1, QDir::homePath());
     } else {
         QString userName = tokens.first();
         userName.remove(0, 1);
 #if defined(Q_OS_VXWORKS)
         const QString homePath = QDir::homePath();
 #elif defined(_POSIX_THREAD_SAFE_FUNCTIONS) && !defined(Q_OS_OPENBSD)
         passwd pw;
         passwd *tmpPw;
         char buf[200];
         const int bufSize = sizeof(buf);
         int err = 0;
 #if defined(Q_OS_SOLARIS) && defined(_POSIX_C_SOURCE) && (_POSIX_C_SOURCE - 0 < 199506L)
         tmpPw = getpwnam_r(userName.toLocal8Bit().constData(), &pw, buf, bufSize);
 #else
         err = getpwnam_r(userName.toLocal8Bit().constData(), &pw, buf, bufSize, &tmpPw);
 #endif
         if (err || !tmpPw)
             return ret;
         const QString homePath = QString::fromLocal8Bit(pw.pw_dir);
 #else
         passwd *pw = getpwnam(userName.toLocal8Bit().constData());
         if (!pw)
             return ret;
         const QString homePath = QString::fromLocal8Bit(pw->pw_dir);
 #endif
         ret.replace(0, tokens.first().length(), homePath);
     }
     if (expanded != 0)
         *expanded = true;
 #endif
     return ret;
 }
qt_win_get_existing_directory()
QString qt_win_get_existing_directory (const QFileDialogArgs & args)
Definition at line 741 of file qfiledialog_win.cpp.
Referenced by QFileDialog::getExistingDirectory(), and QFileDialog::labelText().
 {
 #ifndef Q_WS_WINCE
     if (QSysInfo::WindowsVersion >= QSysInfo::WV_VISTA && (QSysInfo::WindowsVersion & QSysInfo::WV_NT_based))
         return qt_win_CID_get_existing_directory(args);
 #endif
     QString currentDir = QDir::currentPath();
     QString result;
     QWidget *parent = args.parent;
     if (parent)
         parent = parent->window();
     else
         parent = QApplication::activeWindow();
     if (parent)
         parent->createWinId();
     QDialog modal_widget;
     modal_widget.setAttribute(Qt::WA_NoChildEventsForParent, true);
     modal_widget.setParent(parent, Qt::Window);
     QApplicationPrivate::enterModal(&modal_widget);
     QString initDir = QDir::toNativeSeparators(args.directory);
     wchar_t path[MAX_PATH];
     wchar_t initPath[MAX_PATH];
     initPath[0] = 0;
     path[0] = 0;
     tTitle = args.caption;
     qt_BROWSEINFO bi;
     Q_ASSERT(!parent ||parent->testAttribute(Qt::WA_WState_Created));
     bi.hwndOwner = (parent ? parent->winId() : 0);
     bi.pidlRoot = NULL;
     //### This does not seem to be respected? - the dialog always displays "Browse for folder"
     bi.lpszTitle = (wchar_t*)tTitle.utf16();
     bi.pszDisplayName = initPath;
     bi.ulFlags = BIF_RETURNONLYFSDIRS | BIF_STATUSTEXT | BIF_NEWDIALOGSTYLE;
     bi.lpfn = winGetExistDirCallbackProc;
     bi.lParam = LPARAM(&initDir);
     qt_win_resolve_libs();
     if (ptrSHBrowseForFolder) {
         qt_LPITEMIDLIST pItemIDList = ptrSHBrowseForFolder(&bi);
         if (pItemIDList) {
             ptrSHGetPathFromIDList(pItemIDList, path);
             IMalloc *pMalloc;
             if (ptrSHGetMalloc(&pMalloc) == NOERROR) {
                 pMalloc->Free(pItemIDList);
                 pMalloc->Release();
                 result = QString::fromWCharArray(path);
             }
         }
     }
     tTitle = QString();
     QApplicationPrivate::leaveModal(&modal_widget);
     qt_win_eatMouseMove();
     if (!result.isEmpty())
         result.replace(QLatin1Char('\\'), QLatin1Char('/'));
     return result;
 }
qt_win_get_open_file_name()
QString qt_win_get_open_file_name (const QFileDialogArgs & args, QString * initialDirectory, QString * selectedFilter)
Definition at line 231 of file qfiledialog_win.cpp.
Referenced by QFileDialog::getOpenFileName(), and QFileDialog::labelText().
 {
     QString result;
     QString isel = args.selection;
     if (initialDirectory && initialDirectory->left(5) == QLatin1String("file:"))
         initialDirectory->remove(0, 5);
     QFileInfo fi(*initialDirectory);
     if (initialDirectory && !fi.isDir()) {
         *initialDirectory = fi.absolutePath();
         if (isel.isEmpty())
             isel = fi.fileName();
     }
     if (!fi.exists())
         *initialDirectory = QDir::homePath();
     DWORD selFilIdx = 0;
     int idx = 0;
     if (selectedFilter) {
         QStringList filterLst = qt_win_make_filters_list(args.filter);
         idx = filterLst.indexOf(*selectedFilter);
     }
     QDialog modal_widget;
     modal_widget.setAttribute(Qt::WA_NoChildEventsForParent, true);
     modal_widget.setParent(args.parent, Qt::Window);
     QApplicationPrivate::enterModal(&modal_widget);
     bool hideFiltersDetails = args.options & QFileDialog::HideNameFilterDetails;
     OPENFILENAME* ofn = qt_win_make_OFN(args.parent, args.selection,
                                         args.directory, args.caption,
                                         qt_win_filter(args.filter, hideFiltersDetails),
                                         QFileDialog::ExistingFile,
                                         args.options);
     if (idx)
         ofn->nFilterIndex = idx + 1;
     if (GetOpenFileName(ofn)) {
         result = QString::fromWCharArray(ofn->lpstrFile);
         selFilIdx = ofn->nFilterIndex;
     }
     qt_win_clean_up_OFN(&ofn);
     QApplicationPrivate::leaveModal(&modal_widget);
     qt_win_eatMouseMove();
     if (result.isEmpty())
         return result;
     fi = result;
     *initialDirectory = fi.path();
     if (selectedFilter)
         *selectedFilter = qt_win_selected_filter(args.filter, selFilIdx);
     return fi.absoluteFilePath();
 }
qt_win_get_open_file_names()
QStringList qt_win_get_open_file_names (const QFileDialogArgs & args, QString * initialDirectory, QString * selectedFilter)
Definition at line 627 of file qfiledialog_win.cpp.
Referenced by QFileDialog::getOpenFileNames(), and QFileDialog::labelText().
 {
     QFileInfo fi;
     QDir dir;
     if (initialDirectory && initialDirectory->left(5) == QLatin1String("file:"))
         initialDirectory->remove(0, 5);
     fi = QFileInfo(*initialDirectory);
     if (initialDirectory && !fi.isDir()) {
         *initialDirectory = fi.absolutePath();
     }
     if (!fi.exists())
         *initialDirectory = QDir::homePath();
     DWORD selFilIdx = 0;
     QStringList filterLst = qt_win_make_filters_list(args.filter);
     int idx = 0;
     if (selectedFilter) {
         idx = filterLst.indexOf(*selectedFilter);
     }
     // Windows Vista (& above) allows users to search from file dialogs. If user selects
     // multiple files belonging to different folders from these search results, the
     // GetOpenFileName() will return only one folder name for all the files. To retrieve
     // the correct path for all selected files, we have to use Common Item Dialog interfaces.
 #ifndef Q_WS_WINCE
     if (QSysInfo::WindowsVersion >= QSysInfo::WV_VISTA && (QSysInfo::WindowsVersion & QSysInfo::WV_NT_based))
         return qt_win_CID_get_open_file_names(args, initialDirectory, filterLst, selectedFilter, idx);
 #endif
     QStringList result;
     QDialog modal_widget;
     modal_widget.setAttribute(Qt::WA_NoChildEventsForParent, true);
     modal_widget.setParent(args.parent, Qt::Window);
     QApplicationPrivate::enterModal(&modal_widget);
     bool hideFiltersDetails = args.options & QFileDialog::HideNameFilterDetails;
     OPENFILENAME* ofn = qt_win_make_OFN(args.parent, args.selection,
                                         args.directory, args.caption,
                                         qt_win_filter(args.filter, hideFiltersDetails),
                                         QFileDialog::ExistingFiles,
                                         args.options);
     if (idx)
         ofn->nFilterIndex = idx + 1;
     if (GetOpenFileName(ofn)) {
         QString fileOrDir = QString::fromWCharArray(ofn->lpstrFile);
         selFilIdx = ofn->nFilterIndex;
         int offset = fileOrDir.length() + 1;
         if (ofn->lpstrFile[offset] == 0) {
             // Only one file selected; has full path
             fi.setFile(fileOrDir);
             QString res = fi.absoluteFilePath();
             if (!res.isEmpty())
                 result.append(res);
         }
         else {
             // Several files selected; first string is path
             dir.setPath(fileOrDir);
             QString f;
             while(!(f = QString::fromWCharArray(ofn->lpstrFile + offset)).isEmpty()) {
                 fi.setFile(dir, f);
                 QString res = fi.absoluteFilePath();
                 if (!res.isEmpty())
                     result.append(res);
                 offset += f.length() + 1;
             }
         }
     }
     qt_win_clean_up_OFN(&ofn);
     QApplicationPrivate::leaveModal(&modal_widget);
     qt_win_eatMouseMove();
     if (!result.isEmpty()) {
         *initialDirectory = fi.path();    // only save the path if there is a result
         if (selectedFilter)
             *selectedFilter = qt_win_selected_filter(args.filter, selFilIdx);
     }
     return result;
 }
qt_win_get_save_file_name()
QString qt_win_get_save_file_name (const QFileDialogArgs & args, QString * initialDirectory, QString * selectedFilter)
Definition at line 293 of file qfiledialog_win.cpp.
Referenced by QFileDialog::getSaveFileName(), and QFileDialog::labelText().
 {
     QString result;
     QString isel = args.selection;
     if (initialDirectory && initialDirectory->left(5) == QLatin1String("file:"))
         initialDirectory->remove(0, 5);
     QFileInfo fi(*initialDirectory);
     if (initialDirectory && !fi.isDir()) {
         *initialDirectory = fi.absolutePath();
         if (isel.isEmpty())
             isel = fi.fileName();
     }
     if (!fi.exists())
         *initialDirectory = QDir::homePath();
     DWORD selFilIdx = 0;
     int idx = 0;
     if (selectedFilter) {
         QStringList filterLst = qt_win_make_filters_list(args.filter);
         idx = filterLst.indexOf(*selectedFilter);
     }
     QDialog modal_widget;
     modal_widget.setAttribute(Qt::WA_NoChildEventsForParent, true);
     modal_widget.setParent(args.parent, Qt::Window);
     QApplicationPrivate::enterModal(&modal_widget);
     bool hideFiltersDetails = args.options & QFileDialog::HideNameFilterDetails;
     // This block is used below for the lpstrDefExt member.
     // Note that the current MSDN docs document this member wrong.
     // It should rather be documented as "the default extension if no extension was given and if the
     // current filter does not have a extension (e.g (*)). If the current filter have an extension, use
     // the extension of the current filter"
     QString defaultSaveExt;
     if (selectedFilter && !selectedFilter->isEmpty()) {
         defaultSaveExt = qt_win_extract_filter(*selectedFilter);
         // make sure we only have the extension
         int firstDot = defaultSaveExt.indexOf(QLatin1Char('.'));
         if (firstDot != -1) {
             defaultSaveExt.remove(0, firstDot + 1);
         } else {
             defaultSaveExt.clear();
         }
     }
     OPENFILENAME *ofn = qt_win_make_OFN(args.parent, args.selection,
                                         args.directory, args.caption,
                                         qt_win_filter(args.filter, hideFiltersDetails),
                                         QFileDialog::AnyFile,
                                         args.options);
     ofn->lpstrDefExt = (wchar_t*)defaultSaveExt.utf16();
     if (idx)
         ofn->nFilterIndex = idx + 1;
     if (GetSaveFileName(ofn)) {
         result = QString::fromWCharArray(ofn->lpstrFile);
         selFilIdx = ofn->nFilterIndex;
     }
     qt_win_clean_up_OFN(&ofn);
 #if defined(Q_WS_WINCE)
     int semIndex = result.indexOf(QLatin1Char(';'));
     if (semIndex >= 0)
         result = result.left(semIndex);
 #endif
     QApplicationPrivate::leaveModal(&modal_widget);
     qt_win_eatMouseMove();
     if (result.isEmpty())
         return result;
     fi = result;
     *initialDirectory = fi.path();
     if (selectedFilter)
         *selectedFilter = qt_win_selected_filter(args.filter, selFilIdx);
     return fi.absoluteFilePath();
 }
Variable Documentation
QFileDialogMagic
const qint32 QFileDialogMagic = 0xbe static
Definition at line 436 of file qfiledialog.cpp.
qt_file_dialog_filter_reg_exp
const char* qt_file_dialog_filter_reg_exp
Initial value:
=
"^(.*)\\(([a-zA-Z0-9_.*? +;#\\-\\[\\]@\\{\\}/!<>\\$%&=^~:\\|]*)\\)$"
Definition at line 438 of file qfiledialog.cpp.
Referenced by qt_mac_extract_filter(), qt_win_extract_filter(), qt_win_filter(), qt_win_resolve_libs(), and QNSOpenSavePanelDelegate::removeExtensions:.
qt_filedialog_existing_directory_hook
Q_GUI_EXPORT _qt_filedialog_existing_directory_hook qt_filedialog_existing_directory_hook = 0
Definition at line 85 of file qfiledialog.cpp.
Referenced by QFileDialog::getExistingDirectory(), QGtkStyle::polish(), and QGtkStyle::unpolish().
qt_filedialog_open_filename_hook
Q_GUI_EXPORT _qt_filedialog_open_filename_hook qt_filedialog_open_filename_hook = 0
Definition at line 88 of file qfiledialog.cpp.
Referenced by QFileDialog::getOpenFileName(), QGtkStyle::polish(), and QGtkStyle::unpolish().
qt_filedialog_open_filenames_hook
Q_GUI_EXPORT _qt_filedialog_open_filenames_hook qt_filedialog_open_filenames_hook = 0
Definition at line 91 of file qfiledialog.cpp.
Referenced by QFileDialog::getOpenFileNames(), QGtkStyle::polish(), and QGtkStyle::unpolish().
qt_filedialog_save_filename_hook
Q_GUI_EXPORT _qt_filedialog_save_filename_hook qt_filedialog_save_filename_hook = 0
Definition at line 94 of file qfiledialog.cpp.
Referenced by QFileDialog::getSaveFileName(), QGtkStyle::polish(), and QGtkStyle::unpolish().
qt_priv_ptr_valid
bool qt_priv_ptr_valid
Definition at line 60 of file qfiledialog_win.cpp.
Referenced by QFileDialog::getExistingDirectory(), and qt_win_resolve_libs().
qt_use_native_dialogs
bool Q_GUI_EXPORT qt_use_native_dialogs = true
Definition at line 331 of file qfiledialog.cpp.