Qt 4.8: /src/corelib/io/qfilesystemengine_win.cpp File Reference
qfilesystemengine_win.cpp File Reference
#include "qfilesystemengine_p.h"
#include "qplatformdefs.h"
#include "qabstractfileengine.h"
#include "private/qfsfileengine_p.h"
#include <private/qsystemlibrary_p.h>
#include <qdebug.h>
#include "qfile.h"
#include "qdir.h"
#include "private/qmutexpool_p.h"
#include "qvarlengtharray.h"
#include "qdatetime.h"
#include "qt_windows.h"
#include <types.h>
#include <objbase.h>
#include <shlobj.h>
#include <initguid.h>
#include <accctrl.h>
#include <ctype.h>
#include <limits.h>
#include <security.h>
Classes
struct _SHARE_INFO_1
Macros
#define _INTPTR_T_DEFINED
#define _POSIX_
#define INVALID_FILE_ATTRIBUTES (DWORD (-1))
#define PATH_MAX FILENAME_MAX
#define QT_NO_LIBRARY 1
#define SECURITY_WIN32
#define SPI_GETPLATFORMTYPE 257
Typedefs
typedef INT_PTR intptr_t
typedef DWORD(WINAPI * PtrNetApiBufferFree) (LPVOID)
typedef DWORD(WINAPI * PtrNetShareEnum) (LPWSTR, DWORD, LPBYTE *, DWORD, LPDWORD, LPDWORD, LPDWORD)
typedef struct _SHARE_INFO_1 SHARE_INFO_1
Functions
static QDateTime fileTimeToQDateTime (const FILETIME *time)
static bool getFindData (QString path, WIN32_FIND_DATA &findData)
static bool isDirPath (const QString &dirPath, bool *existed)
static bool mkDir (const QString &path)
static QString readLink (const QFileSystemEntry &link)
static QString readSymLink (const QFileSystemEntry &link)
static bool resolveUNCLibs ()
static bool rmDir (const QString &path)
static bool tryDriveUNCFallback (const QFileSystemEntry &fname, QFileSystemMetaData &data)
static bool tryFindFallback (const QFileSystemEntry &fname, QFileSystemMetaData &data)
static bool uncShareExists (const QString &server)
Variables
static PtrNetApiBufferFree ptrNetApiBufferFree = 0
static PtrNetShareEnum ptrNetShareEnum = 0
static QString qfsPrivateCurrentDir = QLatin1String("")
Q_CORE_EXPORT int qt_ntfs_permission_lookup = 0
Macro Definition Documentation
_INTPTR_T_DEFINED
#define _INTPTR_T_DEFINED
Definition at line 92 of file qfilesystemengine_win.cpp.
_POSIX_
#define _POSIX_
Definition at line 44 of file qfilesystemengine_win.cpp.
INVALID_FILE_ATTRIBUTES
#define INVALID_FILE_ATTRIBUTES (DWORD (-1))
Definition at line 96 of file qfilesystemengine_win.cpp.
Referenced by isDirPath(), and tryFindFallback().
PATH_MAX
#define PATH_MAX FILENAME_MAX
Definition at line 79 of file qfilesystemengine_win.cpp.
Referenced by QFileSystemEngine::canonicalName(), QFileSystemEngine::currentPath(), QFileSystemEngine::getLinkTarget(), isDirPath(), and QProcessPrivate::processStarted().
QT_NO_LIBRARY
#define QT_NO_LIBRARY 1
Definition at line 148 of file qfilesystemengine_win.cpp.
SECURITY_WIN32
#define SECURITY_WIN32
Definition at line 71 of file qfilesystemengine_win.cpp.
SPI_GETPLATFORMTYPE
#define SPI_GETPLATFORMTYPE 257
Definition at line 75 of file qfilesystemengine_win.cpp.
Referenced by mkDir().
Typedef Documentation
intptr_t
typedef INT_PTR intptr_t
Definition at line 89 of file qfilesystemengine_win.cpp.
PtrNetApiBufferFree
typedef DWORD(WINAPI * PtrNetApiBufferFree) (LPVOID)
Definition at line 272 of file qfilesystemengine_win.cpp.
PtrNetShareEnum
typedef DWORD(WINAPI * PtrNetShareEnum) (LPWSTR, DWORD, LPBYTE *, DWORD, LPDWORD, LPDWORD, LPDWORD)
Definition at line 270 of file qfilesystemengine_win.cpp.
SHARE_INFO_1
typedef struct _SHARE_INFO_1 SHARE_INFO_1
Function Documentation
fileTimeToQDateTime()
static QDateTime fileTimeToQDateTime (const FILETIME * time) inline static
Definition at line 1208 of file qfilesystemengine_win.cpp.
Referenced by QFileSystemMetaData::accessTime(), QFileSystemMetaData::creationTime(), and QFileSystemMetaData::modificationTime().
 {
     QDateTime ret;
 #if defined(Q_OS_WINCE)
     SYSTEMTIME systime;
     FILETIME ftime;
     systime.wYear = 1970;
     systime.wMonth = 1;
     systime.wDay = 1;
     systime.wHour = 0;
     systime.wMinute = 0;
     systime.wSecond = 0;
     systime.wMilliseconds = 0;
     systime.wDayOfWeek = 4;
     SystemTimeToFileTime(&systime, &ftime);
     unsigned __int64 acttime = (unsigned __int64)time->dwHighDateTime << 32 | time->dwLowDateTime;
     FileTimeToSystemTime(time, &systime);
     unsigned __int64 time1970 = (unsigned __int64)ftime.dwHighDateTime << 32 | ftime.dwLowDateTime;
     unsigned __int64 difftime = acttime - time1970;
     difftime /= 10000000;
     ret.setTime_t((unsigned int)difftime);
 #else
     SYSTEMTIME sTime, lTime;
     FileTimeToSystemTime(time, &sTime);
     SystemTimeToTzSpecificLocalTime(0, &sTime, &lTime);
     ret.setDate(QDate(lTime.wYear, lTime.wMonth, lTime.wDay));
     ret.setTime(QTime(lTime.wHour, lTime.wMinute, lTime.wSecond, lTime.wMilliseconds));
 #endif
     return ret;
 }
getFindData()
static bool getFindData (QString path, WIN32_FIND_DATA & findData) inline static
Definition at line 427 of file qfilesystemengine_win.cpp.
Referenced by QFileSystemEngine::fillMetaData(), isDirPath(), and tryFindFallback().
 {
     // path should not end with a trailing slash
     while (path.endsWith(QLatin1Char('\\')))
         path.chop(1);
     // can't handle drives
     if (!path.endsWith(QLatin1Char(':'))) {
         HANDLE hFind = ::FindFirstFile((wchar_t*)path.utf16(), &findData);
         if (hFind != INVALID_HANDLE_VALUE) {
             ::FindClose(hFind);
             return true;
         }
     }
     return false;
 }
isDirPath()
static bool isDirPath (const QString & dirPath, bool * existed) static
Definition at line 921 of file qfilesystemengine_win.cpp.
Referenced by QFileSystemEngine::fillMetaData().
 {
     QString path = dirPath;
     if (path.length() == 2 && path.at(1) == QLatin1Char(':'))
         path += QLatin1Char('\\');
     DWORD fileAttrib = ::GetFileAttributes((wchar_t*)QFSFileEnginePrivate::longFileName(path).utf16());
     if (fileAttrib == INVALID_FILE_ATTRIBUTES) {
         int errorCode = GetLastError();
         if (errorCode == ERROR_ACCESS_DENIED || errorCode == ERROR_SHARING_VIOLATION) {
             WIN32_FIND_DATA findData;
             if (getFindData(QFSFileEnginePrivate::longFileName(path), findData))
                 fileAttrib = findData.dwFileAttributes;
         }
     }
     if (existed)
         *existed = fileAttrib != INVALID_FILE_ATTRIBUTES;
     if (fileAttrib == INVALID_FILE_ATTRIBUTES)
         return false;
     return fileAttrib & FILE_ATTRIBUTE_DIRECTORY;
 }
mkDir()
static bool mkDir (const QString & path) inline static
Definition at line 892 of file qfilesystemengine_win.cpp.
Referenced by isDirPath().
 {
 #if defined(Q_OS_WINCE)
     // Unfortunately CreateDirectory returns true for paths longer than
     // 256, but does not create a directory. It starts to fail, when
     // path length > MAX_PATH, which is 260 usually on CE.
     // This only happens on a Windows Mobile device. Windows CE seems
     // not to be affected by this.
     static int platformId = 0;
     if (platformId == 0) {
         wchar_t platformString[64];
         if (SystemParametersInfo(SPI_GETPLATFORMTYPE, sizeof(platformString)/sizeof(*platformString),platformString,0)) {
             if (0 == wcscmp(platformString, L"PocketPC") || 0 == wcscmp(platformString, L"Smartphone"))
                 platformId = 1;
             else
                 platformId = 2;
         }
     }
     if (platformId == 1 && QFSFileEnginePrivate::longFileName(path).size() > 256)
         return false;
 #endif
     return ::CreateDirectory((wchar_t*)QFSFileEnginePrivate::longFileName(path).utf16(), 0);
 }
readLink()
static QString readLink (const QFileSystemEntry & link) static
Definition at line 358 of file qfilesystemengine_win.cpp.
Referenced by QFileSystemEngine::clearWinStatData(), QFile::decodeName(), QFileSystemEngine::fillMetaData(), QFileInfo::isAbsolute(), QFileInfo::symLinkTarget(), and QFile::symLinkTarget().
 {
 #if !defined(Q_OS_WINCE)
 #if !defined(QT_NO_LIBRARY) && !defined(Q_CC_MWERKS)
     QString ret;
     bool neededCoInit = false;
     IShellLink *psl;                            // pointer to IShellLink i/f
     WIN32_FIND_DATA wfd;
     wchar_t szGotPath[MAX_PATH];
     // Get pointer to the IShellLink interface.
     HRESULT hres = CoCreateInstance(CLSID_ShellLink, NULL, CLSCTX_INPROC_SERVER, IID_IShellLink, (LPVOID *)&psl);
     if (hres == CO_E_NOTINITIALIZED) { // COM was not initialized
         neededCoInit = true;
         CoInitialize(NULL);
         hres = CoCreateInstance(CLSID_ShellLink, NULL, CLSCTX_INPROC_SERVER,
                                     IID_IShellLink, (LPVOID *)&psl);
     }
     if (SUCCEEDED(hres)) {    // Get pointer to the IPersistFile interface.
         IPersistFile *ppf;
         hres = psl->QueryInterface(IID_IPersistFile, (LPVOID *)&ppf);
         if (SUCCEEDED(hres))  {
             hres = ppf->Load((LPOLESTR)link.nativeFilePath().utf16(), STGM_READ);
             //The original path of the link is retrieved. If the file/folder
             //was moved, the return value still have the old path.
             if (SUCCEEDED(hres)) {
                 if (psl->GetPath(szGotPath, MAX_PATH, &wfd, SLGP_UNCPRIORITY) == NOERROR)
                     ret = QString::fromWCharArray(szGotPath);
             }
             ppf->Release();
         }
         psl->Release();
     }
     if (neededCoInit)
         CoUninitialize();
     return ret;
 #else
     Q_UNUSED(link);
     return QString();
 #endif // QT_NO_LIBRARY
 #else
     wchar_t target[MAX_PATH];
     QString result;
     if (SHGetShortcutTarget((wchar_t*)QFileInfo(link.filePath()).absoluteFilePath().replace(QLatin1Char('/'),QLatin1Char('\\')).utf16(), target, MAX_PATH)) {
         result = QString::fromWCharArray(target);
         if (result.startsWith(QLatin1Char('"')))
             result.remove(0,1);
         if (result.endsWith(QLatin1Char('"')))
             result.remove(result.size()-1,1);
     }
     return result;
 #endif // Q_OS_WINCE
 }
readSymLink()
static QString readSymLink (const QFileSystemEntry & link) static
Definition at line 304 of file qfilesystemengine_win.cpp.
Referenced by QFileSystemEngine::clearWinStatData().
 {
     QString result;
 #if !defined(Q_OS_WINCE)
     HANDLE handle = CreateFile((wchar_t*)link.nativeFilePath().utf16(),
                                FILE_READ_EA,
                                FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE,
                                0,
                                OPEN_EXISTING,
                                FILE_FLAG_BACKUP_SEMANTICS | FILE_FLAG_OPEN_REPARSE_POINT,
                                0);
     if (handle != INVALID_HANDLE_VALUE) {
         DWORD bufsize = MAXIMUM_REPARSE_DATA_BUFFER_SIZE;
         REPARSE_DATA_BUFFER *rdb = (REPARSE_DATA_BUFFER*)qMalloc(bufsize);
         DWORD retsize = 0;
         if (::DeviceIoControl(handle, FSCTL_GET_REPARSE_POINT, 0, 0, rdb, bufsize, &retsize, 0)) {
             if (rdb->ReparseTag == IO_REPARSE_TAG_MOUNT_POINT) {
                 int length = rdb->MountPointReparseBuffer.SubstituteNameLength / sizeof(wchar_t);
                 int offset = rdb->MountPointReparseBuffer.SubstituteNameOffset / sizeof(wchar_t);
                 const wchar_t* PathBuffer = &rdb->MountPointReparseBuffer.PathBuffer[offset];
                 result = QString::fromWCharArray(PathBuffer, length);
             } else if (rdb->ReparseTag == IO_REPARSE_TAG_SYMLINK) {
                 int length = rdb->SymbolicLinkReparseBuffer.SubstituteNameLength / sizeof(wchar_t);
                 int offset = rdb->SymbolicLinkReparseBuffer.SubstituteNameOffset / sizeof(wchar_t);
                 const wchar_t* PathBuffer = &rdb->SymbolicLinkReparseBuffer.PathBuffer[offset];
                 result = QString::fromWCharArray(PathBuffer, length);
             }
             // cut-off "//?/" and "/??/"
             if (result.size() > 4 && result.at(0) == QLatin1Char('\\') && result.at(2) == QLatin1Char('?') && result.at(3) == QLatin1Char('\\'))
                 result = result.mid(4);
         }
         qFree(rdb);
         CloseHandle(handle);
 #if !defined(QT_NO_LIBRARY)
         resolveLibs();
         if (ptrGetVolumePathNamesForVolumeNameW) {
             QRegExp matchVolName(QLatin1String("^Volume\\{([a-z]|[0-9]|-)+\\}\\\\"), Qt::CaseInsensitive);
             if(matchVolName.indexIn(result) == 0) {
                 DWORD len;
                 wchar_t buffer[MAX_PATH];
                 QString volumeName = result.mid(0, matchVolName.matchedLength()).prepend(QLatin1String("\\\\?\\"));
                 if(ptrGetVolumePathNamesForVolumeNameW((wchar_t*)volumeName.utf16(), buffer, MAX_PATH, &len) != 0)
                     result.replace(0,matchVolName.matchedLength(), QString::fromWCharArray(buffer));
             }
         }
 #endif
     }
 #else
     Q_UNUSED(link);
 #endif // Q_OS_WINCE
     return result;
 }
resolveUNCLibs()
static bool resolveUNCLibs () static
Definition at line 281 of file qfilesystemengine_win.cpp.
Referenced by QFileSystemEngine::uncListSharesOnServer().
 {
     static bool triedResolve = false;
     if (!triedResolve) {
 #ifndef QT_NO_THREAD
         QMutexLocker locker(QMutexPool::globalInstanceGet(&triedResolve));
         if (triedResolve) {
             return ptrNetShareEnum && ptrNetApiBufferFree;
         }
 #endif
 #if !defined(Q_OS_WINCE)
         QSystemLibrary netapi32(QLatin1String("Netapi32"));
         if (netapi32.load()) {
             ptrNetShareEnum = (PtrNetShareEnum)netapi32.resolve("NetShareEnum");
             ptrNetApiBufferFree = (PtrNetApiBufferFree)netapi32.resolve("NetApiBufferFree");
         }
 #endif
         triedResolve = true;
     }
     return ptrNetShareEnum && ptrNetApiBufferFree;
 }
rmDir()
static bool rmDir (const QString & path) inline static
Definition at line 916 of file qfilesystemengine_win.cpp.
Referenced by isDirPath().
 {
     return ::RemoveDirectory((wchar_t*)QFSFileEnginePrivate::longFileName(path).utf16());
 }
tryDriveUNCFallback()
static bool tryDriveUNCFallback (const QFileSystemEntry & fname, QFileSystemMetaData & data) static
Definition at line 736 of file qfilesystemengine_win.cpp.
Referenced by QFileSystemEngine::fillMetaData().
 {
     bool entryExists = false;
     DWORD fileAttrib = 0;
 #if !defined(Q_OS_WINCE)
     if (fname.isDriveRoot()) {
         // a valid drive ??
         DWORD drivesBitmask = ::GetLogicalDrives();
         int drivebit = 1 << (fname.filePath().at(0).toUpper().unicode() - QLatin1Char('A').unicode());
         if (drivesBitmask & drivebit) {
             fileAttrib = FILE_ATTRIBUTE_DIRECTORY | FILE_ATTRIBUTE_SYSTEM;
             entryExists = true;
         }
     } else {
 #endif
         const QString &path = fname.nativeFilePath();
         bool is_dir = false;
         if (path.startsWith(QLatin1String("\\\\?\\UNC"))) {
             // UNC - stat doesn't work for all cases (Windows bug)
             int s = path.indexOf(path.at(0),7);
             if (s > 0) {
                 // "\\?\UNC\server\..."
                 s = path.indexOf(path.at(0),s+1);
                 if (s > 0) {
                     // "\\?\UNC\server\share\..."
                     if (s == path.size() - 1) {
                         // "\\?\UNC\server\share\"
                         is_dir = true;
                     } else {
                         // "\\?\UNC\server\share\notfound"
                     }
                 } else {
                     // "\\?\UNC\server\share"
                     is_dir = true;
                 }
             } else {
                 // "\\?\UNC\server"
                 is_dir = true;
             }
         }
         if (is_dir && uncShareExists(path)) {
             // looks like a UNC dir, is a dir.
             fileAttrib = FILE_ATTRIBUTE_DIRECTORY;
             entryExists = true;
         }
 #if !defined(Q_OS_WINCE)
     }
 #endif
     if (entryExists)
         data.fillFromFileAttribute(fileAttrib);
     return entryExists;
 }
tryFindFallback()
static bool tryFindFallback (const QFileSystemEntry & fname, QFileSystemMetaData & data) static
Definition at line 789 of file qfilesystemengine_win.cpp.
Referenced by QFileSystemEngine::fillMetaData().
 {
     bool filledData = false;
     // This assumes the last call to a Windows API failed.
     int errorCode = GetLastError();
     if (errorCode == ERROR_ACCESS_DENIED || errorCode == ERROR_SHARING_VIOLATION) {
         WIN32_FIND_DATA findData;
         if (getFindData(fname.nativeFilePath(), findData)
             && findData.dwFileAttributes != INVALID_FILE_ATTRIBUTES) {
             data.fillFromFindData(findData, true, fname.isDriveRoot());
             filledData = true;
         }
     }
     return filledData;
 }
uncShareExists()
static bool uncShareExists (const QString & server) static
Definition at line 415 of file qfilesystemengine_win.cpp.
Referenced by tryDriveUNCFallback().
 {
     // This code assumes the UNC path is always like \\?\UNC\server...
     QStringList parts = server.split(QLatin1Char('\\'), QString::SkipEmptyParts);
     if (parts.count() >= 3) {
         QStringList shares;
         if (QFileSystemEngine::uncListSharesOnServer(QLatin1String("\\\\") + parts.at(2), &shares))
             return parts.count() >= 4 ? shares.contains(parts.at(3), Qt::CaseInsensitive) : true;
     }
     return false;
 }
Variable Documentation
ptrNetApiBufferFree
PtrNetApiBufferFree ptrNetApiBufferFree = 0 static
Definition at line 273 of file qfilesystemengine_win.cpp.
Referenced by resolveUNCLibs(), and QFileSystemEngine::uncListSharesOnServer().
ptrNetShareEnum
PtrNetShareEnum ptrNetShareEnum = 0 static
Definition at line 271 of file qfilesystemengine_win.cpp.
Referenced by resolveUNCLibs(), and QFileSystemEngine::uncListSharesOnServer().
qfsPrivateCurrentDir
QString qfsPrivateCurrentDir = QLatin1String("") static
Definition at line 145 of file qfilesystemengine_win.cpp.
Referenced by isDirPath().
qt_ntfs_permission_lookup
Q_CORE_EXPORT int qt_ntfs_permission_lookup = 0
Definition at line 142 of file qfilesystemengine_win.cpp.
Referenced by QFileSystemEngine::fillPermissions(), and QFileSystemEngine::owner().