Qt 4.8: /src/gui/dialogs/qfiledialog_win.cpp File Reference
qfiledialog_win.cpp File Reference
#include "qfiledialog.h"
#include <private/qfiledialog_p.h>
#include <qapplication.h>
#include <private/qapplication_p.h>
#include <qt_windows.h>
#include <qglobal.h>
#include <qregexp.h>
#include <qbuffer.h>
#include <qdir.h>
#include <qstringlist.h>
#include <private/qsystemlibrary_p.h>
#include "qfiledialog_win_p.h"
#include <commdlg.h>
Typedefs
typedef qt_LPITEMIDLIST(WINAPI * PtrSHBrowseForFolder) (qt_BROWSEINFO *)
typedef HRESULT(WINAPI * PtrSHGetMalloc) (LPMALLOC *)
typedef BOOL(WINAPI * PtrSHGetPathFromIDList) (qt_LPITEMIDLIST, LPWSTR)
Functions
QStringList qt_make_filter_list (const QString &filter)
static void qt_win_clean_up_OFN (OPENFILENAME **ofn)
void qt_win_eatMouseMove ()
static QString qt_win_extract_filter (const QString &rawFilter)
static QString qt_win_filter (const QString &filter, bool hideFiltersDetails)
QString qt_win_get_existing_directory (const QFileDialogArgs &args)
QString qt_win_get_open_file_name (const QFileDialogArgs &args, QString *initialDirectory, QString *selectedFilter)
QStringList qt_win_get_open_file_names (const QFileDialogArgs &args, QString *initialDirectory, QString *selectedFilter)
QString qt_win_get_save_file_name (const QFileDialogArgs &args, QString *initialDirectory, QString *selectedFilter)
static QStringList qt_win_make_filters_list (const QString &filter)
static OPENFILENAME * qt_win_make_OFN (QWidget *parent, const QString &initialSelection, const QString &initialDirectory, const QString &title, const QString &filters, QFileDialog::FileMode mode, QFileDialog::Options options)
static void qt_win_resolve_libs ()
static QString qt_win_selected_filter (const QString &filter, DWORD idx)
static int __stdcall winGetExistDirCallbackProc (HWND hwnd, UINT uMsg, LPARAM lParam, LPARAM lpData)
Variables
const int maxMultiLen = 65535
const int maxNameLen = 1023
static PtrSHBrowseForFolder ptrSHBrowseForFolder = 0
static PtrSHGetMalloc ptrSHGetMalloc = 0
static PtrSHGetPathFromIDList ptrSHGetPathFromIDList = 0
const char * qt_file_dialog_filter_reg_exp
bool qt_priv_ptr_valid = false
static QString tFilters
static QString tInitDir
static QString tTitle
Typedef Documentation
PtrSHBrowseForFolder
typedef qt_LPITEMIDLIST(WINAPI * PtrSHBrowseForFolder) (qt_BROWSEINFO *)
Definition at line 69 of file qfiledialog_win.cpp.
PtrSHGetMalloc
typedef HRESULT(WINAPI * PtrSHGetMalloc) (LPMALLOC *)
Definition at line 73 of file qfiledialog_win.cpp.
PtrSHGetPathFromIDList
typedef BOOL(WINAPI * PtrSHGetPathFromIDList) (qt_LPITEMIDLIST, LPWSTR)
Definition at line 71 of file qfiledialog_win.cpp.
Function Documentation
qt_make_filter_list()
QStringList qt_make_filter_list (const QString & filter)
Definition at line 1075 of file qfiledialog.cpp.
Referenced by qt_win_make_filters_list(), and qt_win_resolve_libs().
 {
     QString f(filter);
     if (f.isEmpty())
         return QStringList();
     QString sep(QLatin1String(";;"));
     int i = f.indexOf(sep, 0);
     if (i == -1) {
         if (f.indexOf(QLatin1Char('\n'), 0) != -1) {
             sep = QLatin1Char('\n');
             i = f.indexOf(sep, 0);
         }
     }
     return f.split(sep);
 }
qt_win_clean_up_OFN()
static void qt_win_clean_up_OFN (OPENFILENAME ** ofn) static
Definition at line 222 of file qfiledialog_win.cpp.
Referenced by qt_win_get_open_file_name(), qt_win_get_open_file_names(), and qt_win_get_save_file_name().
 {
     delete [] (*ofn)->lpstrFile;
     delete *ofn;
     *ofn = 0;
 }
qt_win_eatMouseMove()
void qt_win_eatMouseMove ()
Definition at line 3016 of file qapplication_win.cpp.
Referenced by qt_win_clean_up_OFN(), qt_win_get_existing_directory(), qt_win_get_open_file_name(), qt_win_get_open_file_names(), and qt_win_get_save_file_name().
 {
     // after closing a windows dialog with a double click (i.e. open a file)
     // the message queue still contains a dubious WM_MOUSEMOVE message where
     // the left button is reported to be down (wParam != 0).
     // remove all those messages (usually 1) and post the last one with a
     // reset button state
     MSG msg = {0, 0, 0, 0, 0, {0, 0} };
     while (PeekMessage(&msg, 0, WM_MOUSEMOVE, WM_MOUSEMOVE, PM_REMOVE))
         ;
     if (msg.message == WM_MOUSEMOVE)
         PostMessage(msg.hwnd, msg.message, 0, msg.lParam);
 }
qt_win_extract_filter()
static QString qt_win_extract_filter (const QString & rawFilter) static
Definition at line 109 of file qfiledialog_win.cpp.
Referenced by qt_win_filter(), and qt_win_get_save_file_name().
 {
     QString result = rawFilter;
     QRegExp r(QString::fromLatin1(qt_file_dialog_filter_reg_exp));
     int index = r.indexIn(result);
     if (index >= 0)
         result = r.cap(2);
     QStringList list = result.split(QLatin1Char(' '));
     for(QStringList::iterator it = list.begin(); it < list.end(); ++it) {
         if (*it == QLatin1String("*")) {
             *it = QLatin1String("*.*");
             break;
         }
     }
     return list.join(QLatin1String(";"));
 }
qt_win_filter()
static QString qt_win_filter (const QString & filter, bool hideFiltersDetails) static
Definition at line 137 of file qfiledialog_win.cpp.
Referenced by qt_win_get_open_file_name(), qt_win_get_open_file_names(), and qt_win_get_save_file_name().
 {
     QStringList filterLst = qt_win_make_filters_list(filter);
     QStringList::Iterator it = filterLst.begin();
     QString winfilters;
     QRegExp r(QString::fromLatin1(qt_file_dialog_filter_reg_exp));
     for (; it != filterLst.end(); ++it) {
         QString subfilter = *it;
         if (!subfilter.isEmpty()) {
             if (hideFiltersDetails) {
                 int index = r.indexIn(subfilter);
                 if (index >= 0)
                     winfilters += r.cap(1);
             } else {
                 winfilters += subfilter;
             }
             winfilters += QChar();
             winfilters += qt_win_extract_filter(subfilter);
             winfilters += QChar();
         }
     }
     winfilters += QChar();
     return winfilters;
 }
qt_win_get_existing_directory()
QString qt_win_get_existing_directory (const QFileDialogArgs & args)
Definition at line 741 of file qfiledialog_win.cpp.
Referenced by QFileDialog::getExistingDirectory(), and QFileDialog::labelText().
 {
 #ifndef Q_WS_WINCE
     if (QSysInfo::WindowsVersion >= QSysInfo::WV_VISTA && (QSysInfo::WindowsVersion & QSysInfo::WV_NT_based))
         return qt_win_CID_get_existing_directory(args);
 #endif
     QString currentDir = QDir::currentPath();
     QString result;
     QWidget *parent = args.parent;
     if (parent)
         parent = parent->window();
     else
         parent = QApplication::activeWindow();
     if (parent)
         parent->createWinId();
     QDialog modal_widget;
     modal_widget.setAttribute(Qt::WA_NoChildEventsForParent, true);
     modal_widget.setParent(parent, Qt::Window);
     QApplicationPrivate::enterModal(&modal_widget);
     QString initDir = QDir::toNativeSeparators(args.directory);
     wchar_t path[MAX_PATH];
     wchar_t initPath[MAX_PATH];
     initPath[0] = 0;
     path[0] = 0;
     tTitle = args.caption;
     qt_BROWSEINFO bi;
     Q_ASSERT(!parent ||parent->testAttribute(Qt::WA_WState_Created));
     bi.hwndOwner = (parent ? parent->winId() : 0);
     bi.pidlRoot = NULL;
     //### This does not seem to be respected? - the dialog always displays "Browse for folder"
     bi.lpszTitle = (wchar_t*)tTitle.utf16();
     bi.pszDisplayName = initPath;
     bi.ulFlags = BIF_RETURNONLYFSDIRS | BIF_STATUSTEXT | BIF_NEWDIALOGSTYLE;
     bi.lpfn = winGetExistDirCallbackProc;
     bi.lParam = LPARAM(&initDir);
     qt_win_resolve_libs();
     if (ptrSHBrowseForFolder) {
         qt_LPITEMIDLIST pItemIDList = ptrSHBrowseForFolder(&bi);
         if (pItemIDList) {
             ptrSHGetPathFromIDList(pItemIDList, path);
             IMalloc *pMalloc;
             if (ptrSHGetMalloc(&pMalloc) == NOERROR) {
                 pMalloc->Free(pItemIDList);
                 pMalloc->Release();
                 result = QString::fromWCharArray(path);
             }
         }
     }
     tTitle = QString();
     QApplicationPrivate::leaveModal(&modal_widget);
     qt_win_eatMouseMove();
     if (!result.isEmpty())
         result.replace(QLatin1Char('\\'), QLatin1Char('/'));
     return result;
 }
qt_win_get_open_file_name()
QString qt_win_get_open_file_name (const QFileDialogArgs & args, QString * initialDirectory, QString * selectedFilter)
Definition at line 231 of file qfiledialog_win.cpp.
Referenced by QFileDialog::getOpenFileName(), and QFileDialog::labelText().
 {
     QString result;
     QString isel = args.selection;
     if (initialDirectory && initialDirectory->left(5) == QLatin1String("file:"))
         initialDirectory->remove(0, 5);
     QFileInfo fi(*initialDirectory);
     if (initialDirectory && !fi.isDir()) {
         *initialDirectory = fi.absolutePath();
         if (isel.isEmpty())
             isel = fi.fileName();
     }
     if (!fi.exists())
         *initialDirectory = QDir::homePath();
     DWORD selFilIdx = 0;
     int idx = 0;
     if (selectedFilter) {
         QStringList filterLst = qt_win_make_filters_list(args.filter);
         idx = filterLst.indexOf(*selectedFilter);
     }
     QDialog modal_widget;
     modal_widget.setAttribute(Qt::WA_NoChildEventsForParent, true);
     modal_widget.setParent(args.parent, Qt::Window);
     QApplicationPrivate::enterModal(&modal_widget);
     bool hideFiltersDetails = args.options & QFileDialog::HideNameFilterDetails;
     OPENFILENAME* ofn = qt_win_make_OFN(args.parent, args.selection,
                                         args.directory, args.caption,
                                         qt_win_filter(args.filter, hideFiltersDetails),
                                         QFileDialog::ExistingFile,
                                         args.options);
     if (idx)
         ofn->nFilterIndex = idx + 1;
     if (GetOpenFileName(ofn)) {
         result = QString::fromWCharArray(ofn->lpstrFile);
         selFilIdx = ofn->nFilterIndex;
     }
     qt_win_clean_up_OFN(&ofn);
     QApplicationPrivate::leaveModal(&modal_widget);
     qt_win_eatMouseMove();
     if (result.isEmpty())
         return result;
     fi = result;
     *initialDirectory = fi.path();
     if (selectedFilter)
         *selectedFilter = qt_win_selected_filter(args.filter, selFilIdx);
     return fi.absoluteFilePath();
 }
qt_win_get_open_file_names()
QStringList qt_win_get_open_file_names (const QFileDialogArgs & args, QString * initialDirectory, QString * selectedFilter)
Definition at line 627 of file qfiledialog_win.cpp.
Referenced by QFileDialog::getOpenFileNames(), and QFileDialog::labelText().
 {
     QFileInfo fi;
     QDir dir;
     if (initialDirectory && initialDirectory->left(5) == QLatin1String("file:"))
         initialDirectory->remove(0, 5);
     fi = QFileInfo(*initialDirectory);
     if (initialDirectory && !fi.isDir()) {
         *initialDirectory = fi.absolutePath();
     }
     if (!fi.exists())
         *initialDirectory = QDir::homePath();
     DWORD selFilIdx = 0;
     QStringList filterLst = qt_win_make_filters_list(args.filter);
     int idx = 0;
     if (selectedFilter) {
         idx = filterLst.indexOf(*selectedFilter);
     }
     // Windows Vista (& above) allows users to search from file dialogs. If user selects
     // multiple files belonging to different folders from these search results, the
     // GetOpenFileName() will return only one folder name for all the files. To retrieve
     // the correct path for all selected files, we have to use Common Item Dialog interfaces.
 #ifndef Q_WS_WINCE
     if (QSysInfo::WindowsVersion >= QSysInfo::WV_VISTA && (QSysInfo::WindowsVersion & QSysInfo::WV_NT_based))
         return qt_win_CID_get_open_file_names(args, initialDirectory, filterLst, selectedFilter, idx);
 #endif
     QStringList result;
     QDialog modal_widget;
     modal_widget.setAttribute(Qt::WA_NoChildEventsForParent, true);
     modal_widget.setParent(args.parent, Qt::Window);
     QApplicationPrivate::enterModal(&modal_widget);
     bool hideFiltersDetails = args.options & QFileDialog::HideNameFilterDetails;
     OPENFILENAME* ofn = qt_win_make_OFN(args.parent, args.selection,
                                         args.directory, args.caption,
                                         qt_win_filter(args.filter, hideFiltersDetails),
                                         QFileDialog::ExistingFiles,
                                         args.options);
     if (idx)
         ofn->nFilterIndex = idx + 1;
     if (GetOpenFileName(ofn)) {
         QString fileOrDir = QString::fromWCharArray(ofn->lpstrFile);
         selFilIdx = ofn->nFilterIndex;
         int offset = fileOrDir.length() + 1;
         if (ofn->lpstrFile[offset] == 0) {
             // Only one file selected; has full path
             fi.setFile(fileOrDir);
             QString res = fi.absoluteFilePath();
             if (!res.isEmpty())
                 result.append(res);
         }
         else {
             // Several files selected; first string is path
             dir.setPath(fileOrDir);
             QString f;
             while(!(f = QString::fromWCharArray(ofn->lpstrFile + offset)).isEmpty()) {
                 fi.setFile(dir, f);
                 QString res = fi.absoluteFilePath();
                 if (!res.isEmpty())
                     result.append(res);
                 offset += f.length() + 1;
             }
         }
     }
     qt_win_clean_up_OFN(&ofn);
     QApplicationPrivate::leaveModal(&modal_widget);
     qt_win_eatMouseMove();
     if (!result.isEmpty()) {
         *initialDirectory = fi.path();    // only save the path if there is a result
         if (selectedFilter)
             *selectedFilter = qt_win_selected_filter(args.filter, selFilIdx);
     }
     return result;
 }
qt_win_get_save_file_name()
QString qt_win_get_save_file_name (const QFileDialogArgs & args, QString * initialDirectory, QString * selectedFilter)
Definition at line 293 of file qfiledialog_win.cpp.
Referenced by QFileDialog::getSaveFileName(), and QFileDialog::labelText().
 {
     QString result;
     QString isel = args.selection;
     if (initialDirectory && initialDirectory->left(5) == QLatin1String("file:"))
         initialDirectory->remove(0, 5);
     QFileInfo fi(*initialDirectory);
     if (initialDirectory && !fi.isDir()) {
         *initialDirectory = fi.absolutePath();
         if (isel.isEmpty())
             isel = fi.fileName();
     }
     if (!fi.exists())
         *initialDirectory = QDir::homePath();
     DWORD selFilIdx = 0;
     int idx = 0;
     if (selectedFilter) {
         QStringList filterLst = qt_win_make_filters_list(args.filter);
         idx = filterLst.indexOf(*selectedFilter);
     }
     QDialog modal_widget;
     modal_widget.setAttribute(Qt::WA_NoChildEventsForParent, true);
     modal_widget.setParent(args.parent, Qt::Window);
     QApplicationPrivate::enterModal(&modal_widget);
     bool hideFiltersDetails = args.options & QFileDialog::HideNameFilterDetails;
     // This block is used below for the lpstrDefExt member.
     // Note that the current MSDN docs document this member wrong.
     // It should rather be documented as "the default extension if no extension was given and if the
     // current filter does not have a extension (e.g (*)). If the current filter have an extension, use
     // the extension of the current filter"
     QString defaultSaveExt;
     if (selectedFilter && !selectedFilter->isEmpty()) {
         defaultSaveExt = qt_win_extract_filter(*selectedFilter);
         // make sure we only have the extension
         int firstDot = defaultSaveExt.indexOf(QLatin1Char('.'));
         if (firstDot != -1) {
             defaultSaveExt.remove(0, firstDot + 1);
         } else {
             defaultSaveExt.clear();
         }
     }
     OPENFILENAME *ofn = qt_win_make_OFN(args.parent, args.selection,
                                         args.directory, args.caption,
                                         qt_win_filter(args.filter, hideFiltersDetails),
                                         QFileDialog::AnyFile,
                                         args.options);
     ofn->lpstrDefExt = (wchar_t*)defaultSaveExt.utf16();
     if (idx)
         ofn->nFilterIndex = idx + 1;
     if (GetSaveFileName(ofn)) {
         result = QString::fromWCharArray(ofn->lpstrFile);
         selFilIdx = ofn->nFilterIndex;
     }
     qt_win_clean_up_OFN(&ofn);
 #if defined(Q_WS_WINCE)
     int semIndex = result.indexOf(QLatin1Char(';'));
     if (semIndex >= 0)
         result = result.left(semIndex);
 #endif
     QApplicationPrivate::leaveModal(&modal_widget);
     qt_win_eatMouseMove();
     if (result.isEmpty())
         return result;
     fi = result;
     *initialDirectory = fi.path();
     if (selectedFilter)
         *selectedFilter = qt_win_selected_filter(args.filter, selFilIdx);
     return fi.absoluteFilePath();
 }
qt_win_make_filters_list()
static QStringList qt_win_make_filters_list (const QString & filter) static
Definition at line 126 of file qfiledialog_win.cpp.
Referenced by qt_win_filter(), qt_win_get_open_file_name(), qt_win_get_open_file_names(), qt_win_get_save_file_name(), and qt_win_selected_filter().
 {
     QString f(filter);
     if (f.isEmpty())
         f = QFileDialog::tr("All Files (*.*)");
     return qt_make_filter_list(f);
 }
qt_win_make_OFN()
static OPENFILENAME* qt_win_make_OFN (QWidget * parent, const QString & initialSelection, const QString & initialDirectory, const QString & title, const QString & filters, QFileDialog::FileMode mode, QFileDialog::Options options) static
Definition at line 169 of file qfiledialog_win.cpp.
Referenced by qt_win_get_open_file_name(), qt_win_get_open_file_names(), and qt_win_get_save_file_name().
 {
     if (parent)
         parent = parent->window();
     else
         parent = QApplication::activeWindow();
     tInitDir = QDir::toNativeSeparators(initialDirectory);
     tFilters = filters;
     tTitle = title;
     QString initSel = QDir::toNativeSeparators(initialSelection);
     if (!initSel.isEmpty()) {
         initSel.remove(QLatin1Char('<'));
         initSel.remove(QLatin1Char('>'));
         initSel.remove(QLatin1Char('\"'));
         initSel.remove(QLatin1Char('|'));
     }
     int maxLen = mode == QFileDialog::ExistingFiles ? maxMultiLen : maxNameLen;
     wchar_t *tInitSel = new wchar_t[maxLen + 1];
     if (initSel.length() > 0 && initSel.length() <= maxLen)
         memcpy(tInitSel, initSel.utf16(), (initSel.length()+1)*sizeof(QChar));
     else
         tInitSel[0] = 0;
     OPENFILENAME* ofn = new OPENFILENAME;
     memset(ofn, 0, sizeof(OPENFILENAME));
     ofn->lStructSize = sizeof(OPENFILENAME);
     ofn->hwndOwner = parent ? parent->winId() : 0;
     ofn->lpstrFilter = (wchar_t*)tFilters.utf16();
     ofn->lpstrFile = tInitSel;
     ofn->nMaxFile = maxLen;
     ofn->lpstrInitialDir = (wchar_t*)tInitDir.utf16();
     ofn->lpstrTitle = (wchar_t*)tTitle.utf16();
     ofn->Flags = (OFN_NOCHANGEDIR | OFN_HIDEREADONLY | OFN_EXPLORER | OFN_PATHMUSTEXIST);
     if (mode == QFileDialog::ExistingFile ||
          mode == QFileDialog::ExistingFiles)
         ofn->Flags |= (OFN_FILEMUSTEXIST);
     if (mode == QFileDialog::ExistingFiles)
         ofn->Flags |= (OFN_ALLOWMULTISELECT);
     if (!(options & QFileDialog::DontConfirmOverwrite))
         ofn->Flags |= OFN_OVERWRITEPROMPT;
     return ofn;
 }
qt_win_resolve_libs()
static void qt_win_resolve_libs () static
Definition at line 79 of file qfiledialog_win.cpp.
Referenced by qt_win_get_existing_directory(), and winGetExistDirCallbackProc().
 {
     static bool triedResolve = false;
     if (!triedResolve) {
 #if !defined(Q_WS_WINCE)
         QSystemLibrary lib(QLatin1String("shell32"));
         ptrSHBrowseForFolder = (PtrSHBrowseForFolder)lib.resolve("SHBrowseForFolderW");
         ptrSHGetPathFromIDList = (PtrSHGetPathFromIDList)lib.resolve("SHGetPathFromIDListW");
         ptrSHGetMalloc = (PtrSHGetMalloc)lib.resolve("SHGetMalloc");
 #else
         // CE stores them in a different lib and does not use unicode version
         QSystemLibrary lib(QLatin1String("Ceshell"));
         ptrSHBrowseForFolder = (PtrSHBrowseForFolder)lib.resolve("SHBrowseForFolder");
         ptrSHGetPathFromIDList = (PtrSHGetPathFromIDList)lib.resolve("SHGetPathFromIDList");
         ptrSHGetMalloc = (PtrSHGetMalloc)lib.resolve("SHGetMalloc");
         if (ptrSHBrowseForFolder && ptrSHGetPathFromIDList && ptrSHGetMalloc)
             qt_priv_ptr_valid = true;
 #endif
         triedResolve = true;
     }
 }
qt_win_selected_filter()
static QString qt_win_selected_filter (const QString & filter, DWORD idx) static
Definition at line 162 of file qfiledialog_win.cpp.
Referenced by qt_win_get_open_file_name(), qt_win_get_open_file_names(), and qt_win_get_save_file_name().
 {
     return qt_win_make_filters_list(filter).at((int)idx - 1);
 }
winGetExistDirCallbackProc()
static int __stdcall winGetExistDirCallbackProc (HWND hwnd, UINT uMsg, LPARAM lParam, LPARAM lpData) static
Definition at line 715 of file qfiledialog_win.cpp.
Referenced by qt_win_get_existing_directory().
 {
     if (uMsg == BFFM_INITIALIZED && lpData != 0) {
         QString *initDir = (QString *)(lpData);
         if (!initDir->isEmpty()) {
             SendMessage(hwnd, BFFM_SETSELECTION, TRUE, LPARAM(initDir->utf16()));
         }
     } else if (uMsg == BFFM_SELCHANGED) {
         qt_win_resolve_libs();
         if (ptrSHGetPathFromIDList) {
             wchar_t path[MAX_PATH];
             ptrSHGetPathFromIDList(qt_LPITEMIDLIST(lParam), path);
             QString tmpStr = QString::fromWCharArray(path);
             if (!tmpStr.isEmpty())
                 SendMessage(hwnd, BFFM_ENABLEOK, 1, 1);
             else
                 SendMessage(hwnd, BFFM_ENABLEOK, 0, 0);
             SendMessage(hwnd, BFFM_SETSTATUSTEXT, 1, LPARAM(path));
         }
     }
     return 0;
 }
Variable Documentation
maxMultiLen
const int maxMultiLen = 65535
Definition at line 106 of file qfiledialog_win.cpp.
Referenced by qt_win_make_OFN().
maxNameLen
const int maxNameLen = 1023
Definition at line 105 of file qfiledialog_win.cpp.
Referenced by qt_win_make_OFN().
ptrSHBrowseForFolder
PtrSHBrowseForFolder ptrSHBrowseForFolder = 0 static
Definition at line 70 of file qfiledialog_win.cpp.
Referenced by qt_win_get_existing_directory(), and qt_win_resolve_libs().
ptrSHGetMalloc
PtrSHGetMalloc ptrSHGetMalloc = 0 static
Definition at line 74 of file qfiledialog_win.cpp.
Referenced by qt_win_get_existing_directory(), and qt_win_resolve_libs().
ptrSHGetPathFromIDList
PtrSHGetPathFromIDList ptrSHGetPathFromIDList = 0 static
Definition at line 72 of file qfiledialog_win.cpp.
Referenced by qt_win_get_existing_directory(), qt_win_resolve_libs(), and winGetExistDirCallbackProc().
qt_file_dialog_filter_reg_exp
const char* qt_file_dialog_filter_reg_exp
Definition at line 438 of file qfiledialog.cpp.
Referenced by qt_win_extract_filter(), qt_win_filter(), and qt_win_resolve_libs().
qt_priv_ptr_valid
bool qt_priv_ptr_valid = false
Definition at line 60 of file qfiledialog_win.cpp.
Referenced by QFileDialog::getExistingDirectory(), and qt_win_resolve_libs().
tFilters
QString tFilters static
Definition at line 167 of file qfiledialog_win.cpp.
tInitDir
QString tInitDir static
Definition at line 167 of file qfiledialog_win.cpp.
tTitle
QString tTitle static
Definition at line 167 of file qfiledialog_win.cpp.