Qt 4.8: /src/corelib/io/qfilesystemwatcher_dnotify.cpp File Reference
qfilesystemwatcher_dnotify.cpp File Reference
#include "qplatformdefs.h"
#include "qfilesystemwatcher.h"
#include "qfilesystemwatcher_dnotify_p.h"
#include <qsocketnotifier.h>
#include <qcoreapplication.h>
#include <qfileinfo.h>
#include <qtimer.h>
#include <qwaitcondition.h>
#include <qmutex.h>
#include <dirent.h>
#include <qdir.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <signal.h>
#include <unistd.h>
#include <fcntl.h>
#include <time.h>
#include "private/qcore_unix_p.h"
#include "qfilesystemwatcher_dnotify.moc"
Classes
class QDnotifySignalThread
Functions
static void qfswd_sigio_monitor (int signum, siginfo_t *i, void *v)
Variables
static int qfswd_fileChanged_pipe [2]
static void(* qfswd_old_sigio_action)(int, siginfo_t *, void *)=0
static void(* qfswd_old_sigio_handler)(int)=0
Function Documentation
qfswd_sigio_monitor()
static void qfswd_sigio_monitor (int signum, siginfo_t * i, void * v) static
Definition at line 84 of file qfilesystemwatcher_dnotify.cpp.
Referenced by QDnotifySignalThread::QDnotifySignalThread().
 {
     qt_safe_write(qfswd_fileChanged_pipe[1], reinterpret_cast<char*>(&i->si_fd), sizeof(int));
     if (qfswd_old_sigio_handler && qfswd_old_sigio_handler != SIG_IGN)
         qfswd_old_sigio_handler(signum);
     if (qfswd_old_sigio_action)
         qfswd_old_sigio_action(signum, i, v);
 }
Variable Documentation
qfswd_fileChanged_pipe
int qfswd_fileChanged_pipe[2] static
Definition at line 81 of file qfilesystemwatcher_dnotify.cpp.
Referenced by QDnotifySignalThread::QDnotifySignalThread(), qfswd_sigio_monitor(), QDnotifySignalThread::readFromDnotify(), and QDnotifySignalThread::run().
qfswd_old_sigio_action
void(* qfswd_old_sigio_action) (int, siginfo_t *, void *)=0 static
Definition at line 83 of file qfilesystemwatcher_dnotify.cpp.
Referenced by QDnotifySignalThread::QDnotifySignalThread(), and qfswd_sigio_monitor().
qfswd_old_sigio_handler
void(* qfswd_old_sigio_handler) (int)=0 static
Definition at line 82 of file qfilesystemwatcher_dnotify.cpp.
Referenced by QDnotifySignalThread::QDnotifySignalThread(), and qfswd_sigio_monitor().