Qt 4.8: /src/gui/text/qfontengine_qpa.cpp File Reference
qfontengine_qpa.cpp File Reference
#include "qfontengine_qpa_p.h"
#include <QtCore/QFile>
#include <QtCore/QFileInfo>
#include <QtCore/QDir>
#include <QtCore/QBuffer>
#include <QtGui/private/qapplication_p.h>
#include <QtGui/QPlatformFontDatabase>
#include <QtGui/private/qpaintengine_raster_p.h>
Macros
#define DEBUG_VERIFY if (0) qDebug
#define READ_VERIFY(type, variable)
#define VERIFY(condition)
#define VERIFY_TAG(condition)
Functions
static unsigned int getChar (const QChar *str, int &i, const int len)
template<typename T >
T readValue (const uchar *&data)
static const uchar * verifyTag (const uchar *tagPtr, const uchar *endPtr)
Variables
static QFontEngineQPA::TagType tagTypes [QFontEngineQPA::NumTags]
Macro Definition Documentation
DEBUG_VERIFY
#define DEBUG_VERIFY if (0) qDebug
Definition at line 86 of file qfontengine_qpa.cpp.
READ_VERIFY
#define READ_VERIFY (type, variable)
Value:
if (tagPtr + sizeof(type) > endPtr) { \
        DEBUG_VERIFY() << "read verify failed in line" << __LINE__; \
        return 0; \
    } \
    variable = qFromBigEndian<type>(tagPtr); \
    DEBUG_VERIFY() << "read value" << variable << "of type " #type; \
    tagPtr += sizeof(type)
Definition at line 89 of file qfontengine_qpa.cpp.
Referenced by verifyTag().
VERIFY
#define VERIFY (condition)
Value:
if (!(condition)) { \
        DEBUG_VERIFY() << "condition " #condition " failed in line" << __LINE__; \
        return 0; \
    }
Definition at line 106 of file qfontengine_qpa.cpp.
Referenced by QFontEngineQPA::verifyHeader().
VERIFY_TAG
#define VERIFY_TAG (condition)
Value:
if (!(condition)) { \
        DEBUG_VERIFY() << "verifying tag condition " #condition " failed in line" << __LINE__ << "with tag" << tag; \
        return 0; \
    }
Definition at line 112 of file qfontengine_qpa.cpp.
Referenced by verifyTag().
Function Documentation
getChar()
static unsigned int getChar (const QChar * str, int & i, const int len) inline static
Definition at line 227 of file qfontengine_qpa.cpp.
Referenced by QFontEngineQPA::canRender(), and QFontEngineQPA::stringToCMap().
 {
     uint ucs4 = str[i].unicode();
     if (str[i].isHighSurrogate() && i < len-1 && str[i+1].isLowSurrogate()) {
         ++i;
         ucs4 = QChar::surrogateToUcs4(ucs4, str[i].unicode());
     }
     return ucs4;
 }
readValue()
template<typename T > T readValue (const uchar *& data)
Definition at line 99 of file qfontengine_qpa.cpp.
 {
     T value = qFromBigEndian<T>(data);
     data += sizeof(T);
     return value;
 }
verifyTag()
static const uchar* verifyTag (const uchar * tagPtr, const uchar * endPtr) inline static
Definition at line 118 of file qfontengine_qpa.cpp.
Referenced by QFontEngineQPA::verifyHeader().
 {
     quint16 tag, length;
     READ_VERIFY(quint16, tag);
     READ_VERIFY(quint16, length);
     if (tag == QFontEngineQPA::Tag_EndOfHeader)
         return endPtr;
     if (tag < QFontEngineQPA::NumTags) {
         switch (tagTypes[tag]) {
             case QFontEngineQPA::BitFieldType:
             case QFontEngineQPA::StringType:
                 // can't do anything...
                 break;
             case QFontEngineQPA::UInt32Type:
                 VERIFY_TAG(length == sizeof(quint32));
                 break;
             case QFontEngineQPA::FixedType:
                 VERIFY_TAG(length == sizeof(quint32));
                 break;
             case QFontEngineQPA::UInt8Type:
                 VERIFY_TAG(length == sizeof(quint8));
                 break;
         }
 #if defined(DEBUG_HEADER)
         if (length == 1)
             qDebug() << "tag data" << hex << *tagPtr;
         else if (length == 4)
             qDebug() << "tag data" << hex << tagPtr[0] << tagPtr[1] << tagPtr[2] << tagPtr[3];
 #endif
     }
     return tagPtr + length;
 }
Variable Documentation
tagTypes
QFontEngineQPA::TagType tagTypes[QFontEngineQPA::NumTags] static
Initial value:
= {
    QFontEngineQPA::StringType,
    QFontEngineQPA::StringType,
    QFontEngineQPA::UInt32Type,
    QFontEngineQPA::UInt32Type,
    QFontEngineQPA::StringType,
    QFontEngineQPA::FixedType,
    QFontEngineQPA::FixedType,
    QFontEngineQPA::FixedType,
    QFontEngineQPA::FixedType,
    QFontEngineQPA::FixedType,
    QFontEngineQPA::FixedType,
    QFontEngineQPA::FixedType,
    QFontEngineQPA::FixedType,
    QFontEngineQPA::FixedType,
    QFontEngineQPA::FixedType,
    QFontEngineQPA::UInt8Type,
    QFontEngineQPA::UInt8Type,
    QFontEngineQPA::UInt8Type,
    QFontEngineQPA::UInt8Type,
    QFontEngineQPA::StringType,
    QFontEngineQPA::BitFieldType
}
Definition at line 58 of file qfontengine_qpa.cpp.
Referenced by QFontEngineQPA::extractHeaderField(), QFontEngineQPF::extractHeaderField(), and verifyTag().