Qt 4.8: /src/gui/text/qfontengine_x11.cpp File Reference
qfontengine_x11.cpp File Reference
#include "qbitmap.h"
#include <qapplication.h>
#include <qbytearray.h>
#include <qdebug.h>
#include <qtextcodec.h>
#include <qthread.h>
#include "qfontdatabase.h"
#include "qpaintdevice.h"
#include "qpainter.h"
#include "qvarlengtharray.h"
#include "qwidget.h"
#include "qsettings.h"
#include "qfile.h"
#include <private/qpaintengine_x11_p.h>
#include "qfont.h"
#include "qfont_p.h"
#include "qfontengine_p.h"
#include <qhash.h>
#include <private/qpainter_p.h>
#include <private/qunicodetables_p.h>
#include <private/qt_x11_p.h>
#include <private/qpixmap_x11_p.h>
#include "qx11info_x11.h"
#include "qfontengine_x11_p.h"
#include <limits.h>
#include <ft2build.h>
Functions
static XCharStruct * charStruct (XFontStruct *xfs, uint ch)
static QFontEngine * engineForPattern (FcPattern *match, const QFontDef &request, int screen)
static QFontEngine::FaceId fontFile (const QByteArray &_xname, QFreetypeFace **freetype, int *synth)
static QStringList fontPath ()
static int maxIndex (XFontStruct *f)
int qt_mib_for_xlfd_encoding (const char *encoding)
Q_GUI_EXPORT void qt_x11ft_convert_pattern (FcPattern *pattern, QByteArray *file_name, int *index, bool *antialias)
int qt_xlfd_encoding_id (const char *encoding)
Variables
static QStringList * qt_fontpath = 0
Function Documentation
charStruct()
static XCharStruct* charStruct (XFontStruct * xfs, uint ch) inline static
Definition at line 303 of file qfontengine_x11.cpp.
Referenced by QFontEngineXLFD::boundingBox(), QFontEngineXLFD::canRender(), and QFontEngineXLFD::recalcAdvances().
 {
     XCharStruct *xcs = 0;
     unsigned char r = ch>>8;
     unsigned char c = ch&0xff;
     if (xfs->per_char &&
          r >= xfs->min_byte1 &&
          r <= xfs->max_byte1 &&
          c >= xfs->min_char_or_byte2 &&
          c <= xfs->max_char_or_byte2) {
         xcs = xfs->per_char + ((r - xfs->min_byte1) *
                                (xfs->max_char_or_byte2 -
                                 xfs->min_char_or_byte2 + 1)) +
               (c - xfs->min_char_or_byte2);
         if (xcs->width == 0 && xcs->ascent == 0 &&  xcs->descent == 0)
             xcs = 0;
     }
     return xcs;
 }
engineForPattern()
static QFontEngine* engineForPattern (FcPattern * match, const QFontDef & request, int screen) static
Definition at line 864 of file qfontengine_x11.cpp.
Referenced by QFontEngineMultiFT::loadEngine().
 {
     QFontEngineX11FT *engine = new QFontEngineX11FT(match, request, screen);
     if (!engine->invalid())
         return engine;
     delete engine;
     QFontEngine *fe = new QFontEngineBox(request.pixelSize);
     fe->fontDef = request;
     return fe;
 }
fontFile()
static QFontEngine::FaceId fontFile (const QByteArray & _xname, QFreetypeFace ** freetype, int * synth) static
Definition at line 207 of file qfontengine_x11.cpp.
Referenced by QBasicUnixFontDatabase::addTTFile(), QFontEngineXLFD::faceId(), QFontconfigDatabase::populateFontDatabase(), and resolveGdi32().
 {
     *freetype = 0;
     *synth = 0;
     QByteArray xname = _xname.toLower();
     int pos = 0;
     int minus = 0;
     while (minus < 5 && (pos = xname.indexOf('-', pos + 1)))
         ++minus;
     QByteArray searchname = xname.left(pos);
     while (minus < 12 && (pos = xname.indexOf('-', pos + 1)))
         ++minus;
     QByteArray encoding = xname.mid(pos + 1);
     //qDebug("xname='%s', searchname='%s', encoding='%s'", xname.data(), searchname.data(), encoding.data());
     QStringList fontpath = fontPath();
     QFontEngine::FaceId face_id;
     face_id.index = 0;
     QByteArray best_mapping;
     for (QStringList::ConstIterator it = fontpath.constBegin(); it != fontpath.constEnd(); ++it) {
         if (!(*it).startsWith(QLatin1Char('/')))
             continue; // not a path name, a font server
         QString fontmapname;
         int num = 0;
         // search font.dir and font.scale for the right file
         while (num < 2) {
             if (num == 0)
                 fontmapname = (*it) + QLatin1String("/fonts.scale");
             else
                 fontmapname = (*it) + QLatin1String("/fonts.dir");
             ++num;
             //qWarning(fontmapname);
             QFile fontmap(fontmapname);
             if (!fontmap.open(QIODevice::ReadOnly))
                 continue;
             while (!fontmap.atEnd()) {
                 QByteArray mapping = fontmap.readLine();
                 QByteArray lmapping = mapping.toLower();
                 //qWarning(xfontname);
                 //qWarning(mapping);
                 if (!lmapping.contains(searchname))
                     continue;
                 int index = mapping.indexOf(' ');
                 QByteArray ffn = mapping.mid(0,index);
                 // remove bitmap formats freetype can't handle
                 if (ffn.contains(".spd") || ffn.contains(".phont"))
                     continue;
                 bool best_match = false;
                 if (!best_mapping.isEmpty()) {
                     if (lmapping.contains("-0-0-0-0-")) { // scalable font
                         best_match = true;
                         goto found;
                     }
                     if (lmapping.contains(encoding) && !best_mapping.toLower().contains(encoding))
                         goto found;
                     continue;
                 }
             found:
                 int colon = ffn.lastIndexOf(':');
                 if (colon != -1) {
                     QByteArray s = ffn.left(colon);
                     ffn = ffn.mid(colon + 1);
                     if (s.contains("ds="))
                         *synth |= QFontEngine::SynthesizedBold;
                     if (s.contains("ai="))
                         *synth |= QFontEngine::SynthesizedItalic;
                 }
                 face_id.filename = (*it).toLocal8Bit() + '/' + ffn;
                 best_mapping = mapping;
                 if (best_match)
                     goto end;
             }
         }
     }
 end:
 //     qDebug("fontfile for %s is from '%s'\n    got %s synth=%d", xname.data(),
 //            best_mapping.data(), face_id.filename.data(), *synth);
     *freetype = QFreetypeFace::getFace(face_id);
     if (!*freetype) {
         face_id.index = 0;
         face_id.filename = QByteArray();
     }
     return face_id;
 }
fontPath()
static QStringList fontPath () static
Definition at line 137 of file qfontengine_x11.cpp.
Referenced by fontFile().
 {
     if (qt_fontpath)
         return *qt_fontpath;
     // append qsettings fontpath
     QSettings settings(QSettings::UserScope, QLatin1String("Trolltech"));
     settings.beginGroup(QLatin1String("Qt"));
     QStringList fontpath;
     int npaths;
     char** font_path;
     font_path = XGetFontPath(X11->display, &npaths);
     bool xfsconfig_read = false;
     for (int i=0; i<npaths; i++) {
         // If we're using xfs, append font paths from /etc/X11/fs/config
         // can't hurt, and chances are we'll get all fonts that way.
         if (((font_path[i])[0] != '/') && !xfsconfig_read) {
             // We're using xfs -> read its config
             bool finished = false;
             QFile f(QLatin1String("/etc/X11/fs/config"));
             if (!f.exists())
                 f.setFileName(QLatin1String("/usr/X11R6/lib/X11/fs/config"));
             if (!f.exists())
                 f.setFileName(QLatin1String("/usr/X11/lib/X11/fs/config"));
             if (f.exists()) {
                 f.open(QIODevice::ReadOnly);
                 while (f.error()==QFile::NoError && !finished) {
                     QString fs = QString::fromLocal8Bit(f.readLine(1024));
                     fs=fs.trimmed();
                     if (fs.left(9)==QLatin1String("catalogue") && fs.contains(QLatin1Char('='))) {
                         fs = fs.mid(fs.indexOf(QLatin1Char('=')) + 1).trimmed();
                         bool end = false;
                         while (f.error()==QFile::NoError && !end) {
                             if (fs[int(fs.length())-1] == QLatin1Char(','))
                                 fs = fs.left(fs.length()-1);
                             else
                                 end = true;
                             fs = fs.left(fs.indexOf(QLatin1String(":unscaled")));
                             if (fs[0] != QLatin1Char('#'))
                                 fontpath += fs;
                             fs = QLatin1String(f.readLine(1024));
                             fs = fs.trimmed();
                             if (fs.isEmpty())
                                 end = true;
                         }
                         finished = true;
                     }
                 }
                 f.close();
             }
             xfsconfig_read = true;
         } else {
             QString fs = QString::fromLocal8Bit(font_path[i]);
             fontpath += fs.left(fs.indexOf(QLatin1String(":unscaled")));
         }
     }
     XFreeFontPath(font_path);
     // append qsettings fontpath
     QStringList fp = settings.value(QLatin1String("fontPath")).toStringList();
     if (!fp.isEmpty())
         fontpath += fp;
     qt_fontpath = new QStringList(fontpath);
     return fontpath;
 }
maxIndex()
static int maxIndex (XFontStruct * f) inline static
Definition at line 548 of file qfontengine_x11.cpp.
Referenced by QFontEngineXLFD::minLeftBearing(), and QFontEngineXLFD::minRightBearing().
{
     return (((f->max_byte1 - f->min_byte1) *
              (f->max_char_or_byte2 - f->min_char_or_byte2 + 1)) +
             f->max_char_or_byte2 - f->min_char_or_byte2);
 }
qt_mib_for_xlfd_encoding()
int qt_mib_for_xlfd_encoding (const char * encoding)
Definition at line 394 of file qfontdatabase_x11.cpp.
Referenced by fontFile().
 {
     int id = qt_xlfd_encoding_id(encoding);
     if (id != -1) return xlfd_encoding[id].mib;
     return 0;
 }
qt_x11ft_convert_pattern()
Q_GUI_EXPORT void qt_x11ft_convert_pattern (FcPattern * pattern, QByteArray * file_name, int * index, bool * antialias)
Definition at line 958 of file qfontengine_x11.cpp.
Referenced by QFontEngineX11FT::QFontEngineX11FT().
 {
     FcChar8 *fileName;
     FcPatternGetString(pattern, FC_FILE, 0, &fileName);
     *file_name = (const char *)fileName;
     if (!FcPatternGetInteger(pattern, FC_INDEX, 0, index))
         index = 0;
     FcBool b;
     if (FcPatternGetBool(pattern, FC_ANTIALIAS, 0, &b) == FcResultMatch)
         *antialias = b;
 }
qt_xlfd_encoding_id()
int qt_xlfd_encoding_id (const char * encoding)
Definition at line 350 of file qfontdatabase_x11.cpp.
Referenced by fontFile(), loadXlfds(), and qt_mib_for_xlfd_encoding().
 {
     // qDebug("looking for encoding id for '%s'", encoding);
     int len = strlen(encoding);
     if (len < 4)
         return -1;
     unsigned int hash1 = make_tag(encoding[0], encoding[1], encoding[2], encoding[3]);
     const char *ch = encoding + len - 4;
     unsigned int hash2 = make_tag(ch[0], ch[1], ch[2], ch[3]);
     const XlfdEncoding *enc = xlfd_encoding;
     for (; enc->name; ++enc) {
         if ((enc->hash1 && enc->hash1 != hash1) ||
             (enc->hash2 && enc->hash2 != hash2))
             continue;
         // hashes match, do a compare if strings match
         // the enc->name can contain '*'s we have to interpret correctly
         const char *n = enc->name;
         const char *e = encoding;
         while (1) {
             // qDebug("bol: *e='%c', *n='%c'", *e, *n);
             if (*e == '\0') {
                 if (*n)
                     break;
                 // qDebug("found encoding id %d", enc->id);
                 return enc->id;
             }
             if (*e == *n) {
                 ++e;
                 ++n;
                 continue;
             }
             if (*n != '*')
                 break;
             ++n;
             // qDebug("skip: *e='%c', *n='%c'", *e, *n);
             while (*e && *e != *n)
                 ++e;
         }
     }
     // qDebug("couldn't find encoding %s", encoding);
     return -1;
 }
Variable Documentation
qt_fontpath
QStringList* qt_fontpath = 0 static
Definition at line 135 of file qfontengine_x11.cpp.
Referenced by fontPath().