Qt 4.8: /src/gui/text/qfontengine.cpp File Reference
qfontengine.cpp File Reference
#include <qdebug.h>
#include <private/qfontengine_p.h>
#include "qbitmap.h"
#include "qpainter.h"
#include "qpainterpath.h"
#include "qvarlengtharray.h"
#include <qmath.h>
#include <qendian.h>
#include <private/qharfbuzz_p.h>
Macros
#define GRID(x, y) grid[(y)*(w+1) + (x)]
#define SET(x, y) (*(image_data + (y)*bpl + ((x) >> 3)) & (0x80 >> ((x) & 7)))
Enumerations
enum { EdgeRight = 0x1, EdgeDown = 0x2, EdgeLeft = 0x4, EdgeUp = 0x8 }
Functions
static void collectSingleContour (qreal x0, qreal y0, uint *grid, int x, int y, int w, int h, QPainterPath *path)
static HB_Bool hb_canRender (HB_Font font, const HB_UChar16 *string, hb_uint32 length)
static void hb_getAdvances (HB_Font font, const HB_Glyph *glyphs, hb_uint32 numGlyphs, HB_Fixed *advances, int flags)
static HB_Fixed hb_getFontMetric (HB_Font font, HB_FontMetric metric)
static void hb_getGlyphMetrics (HB_Font font, HB_Glyph glyph, HB_GlyphMetrics *metrics)
static HB_Error hb_getPointInOutline (HB_Font font, HB_Glyph glyph, int flags, hb_uint32 point, HB_Fixed *xpos, HB_Fixed *ypos, hb_uint32 *nPoints)
static HB_Error hb_getSFntTable (void *font, HB_Tag tableTag, HB_Byte *buffer, HB_UInt *length)
static HB_Bool hb_stringToGlyphs (HB_Font font, const HB_UChar16 *string, hb_uint32 length, HB_Glyph *glyphs, hb_uint32 *numGlyphs, HB_Bool rightToLeft)
static uchar highByte (glyph_t glyph)
static QFixed kerning (int left, int right, const QFontEngine::KernPair *pairs, int numPairs)
Q_GLOBAL_STATIC_WITH_INITIALIZER (QVector< QRgb >, qt_grayPalette, { x->resize(256);QRgb *it=x->data();for(int i=0;i< x->size();++i,++it) *it=0xff000000|i|(i<< 8)|(i<< 16);}) const QVector< QRgb > &QFontEngine
Q_GUI_EXPORT void qt_addBitmapToPath (qreal x0, qreal y0, const uchar *image_data, int bpl, int w, int h, QPainterPath *path)
static bool qtransform_equals_no_translate (const QTransform &a, const QTransform &b)
static glyph_t stripped (glyph_t glyph)
Variables
static const HB_FontClass hb_fontClass
Macro Definition Documentation
GRID
#define GRID (x, y) grid[(y)*(w+1) + (x)]
Definition at line 432 of file qfontengine.cpp.
Referenced by collectSingleContour(), and qt_addBitmapToPath().
SET
#define SET (x, y) (*(image_data + (y)*bpl + ((x) >> 3)) & (0x80 >> ((x) & 7)))
Definition at line 433 of file qfontengine.cpp.
Referenced by qt_addBitmapToPath().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EdgeRight
EdgeDown
EdgeLeft
EdgeUp
Definition at line 435 of file qfontengine.cpp.
      { EdgeRight = 0x1,
        EdgeDown = 0x2,
        EdgeLeft = 0x4,
        EdgeUp = 0x8
 };
Function Documentation
collectSingleContour()
static void collectSingleContour (qreal x0, qreal y0, uint * grid, int x, int y, int w, int h, QPainterPath * path) static
Definition at line 441 of file qfontengine.cpp.
Referenced by qt_addBitmapToPath().
 {
     Q_UNUSED(h);
     path->moveTo(x + x0, y + y0);
     while (GRID(x, y)) {
         if (GRID(x, y) & EdgeRight) {
             while (GRID(x, y) & EdgeRight) {
                 GRID(x, y) &= ~EdgeRight;
                 ++x;
             }
             Q_ASSERT(x <= w);
             path->lineTo(x + x0, y + y0);
             continue;
         }
         if (GRID(x, y) & EdgeDown) {
             while (GRID(x, y) & EdgeDown) {
                 GRID(x, y) &= ~EdgeDown;
                 ++y;
             }
             Q_ASSERT(y <= h);
             path->lineTo(x + x0, y + y0);
             continue;
         }
         if (GRID(x, y) & EdgeLeft) {
             while (GRID(x, y) & EdgeLeft) {
                 GRID(x, y) &= ~EdgeLeft;
                 --x;
             }
             Q_ASSERT(x >= 0);
             path->lineTo(x + x0, y + y0);
             continue;
         }
         if (GRID(x, y) & EdgeUp) {
             while (GRID(x, y) & EdgeUp) {
                 GRID(x, y) &= ~EdgeUp;
                 --y;
             }
             Q_ASSERT(y >= 0);
             path->lineTo(x + x0, y + y0);
             continue;
         }
     }
     path->closeSubpath();
 }
hb_canRender()
static HB_Bool hb_canRender (HB_Font font, const HB_UChar16 * string, hb_uint32 length) static
Definition at line 111 of file qfontengine.cpp.
 {
     QFontEngine *fe = (QFontEngine *)font->userData;
     return fe->canRender(reinterpret_cast<const QChar *>(string), length);
 }
hb_getAdvances()
static void hb_getAdvances (HB_Font font, const HB_Glyph * glyphs, hb_uint32 numGlyphs, HB_Fixed * advances, int flags) static
Definition at line 96 of file qfontengine.cpp.
 {
     QFontEngine *fe = (QFontEngine *)font->userData;
     QVarLengthGlyphLayoutArray qglyphs(numGlyphs);
     for (hb_uint32 i = 0; i < numGlyphs; ++i)
         qglyphs.glyphs[i] = glyphs[i];
     fe->recalcAdvances(&qglyphs, flags & HB_ShaperFlag_UseDesignMetrics ? QFlags<QTextEngine::ShaperFlag>(QTextEngine::DesignMetrics) : QFlags<QTextEngine::ShaperFlag>(0));
     for (hb_uint32 i = 0; i < numGlyphs; ++i)
         advances[i] = qglyphs.advances_x[i].value();
 }
hb_getFontMetric()
static HB_Fixed hb_getFontMetric (HB_Font font, HB_FontMetric metric) static
Definition at line 129 of file qfontengine.cpp.
 {
     QFontEngine *fe = (QFontEngine *)font->userData;
     switch (metric) {
     case HB_FontAscent:
         return fe->ascent().value();
         break;
     case HB_FontDescent:
         return fe->descent().value();
         break;
     default:
         return 0;
     }
 }
hb_getGlyphMetrics()
static void hb_getGlyphMetrics (HB_Font font, HB_Glyph glyph, HB_GlyphMetrics * metrics) static
Definition at line 117 of file qfontengine.cpp.
 {
     QFontEngine *fe = (QFontEngine *)font->userData;
     glyph_metrics_t m = fe->boundingBox(glyph);
     metrics->x = m.x.value();
     metrics->y = m.y.value();
     metrics->width = m.width.value();
     metrics->height = m.height.value();
     metrics->xOffset = m.xoff.value();
     metrics->yOffset = m.yoff.value();
 }
hb_getPointInOutline()
static HB_Error hb_getPointInOutline (HB_Font font, HB_Glyph glyph, int flags, hb_uint32 point, HB_Fixed * xpos, HB_Fixed * ypos, hb_uint32 * nPoints) static
Definition at line 155 of file qfontengine.cpp.
 {
     QFontEngine *fe = (QFontEngine *)font->userData;
     return fe->getPointInOutline(glyph, flags, point, xpos, ypos, nPoints);
 }
hb_getSFntTable()
static HB_Error hb_getSFntTable (void * font, HB_Tag tableTag, HB_Byte * buffer, HB_UInt * length) static
Definition at line 166 of file qfontengine.cpp.
Referenced by QFontEngine::harfbuzzFace().
 {
     QFontEngine *fe = (QFontEngine *)font;
     if (!fe->getSfntTableData(tableTag, buffer, length))
         return HB_Err_Invalid_Argument;
     return HB_Err_Ok;
 }
hb_stringToGlyphs()
static HB_Bool hb_stringToGlyphs (HB_Font font, const HB_UChar16 * string, hb_uint32 length, HB_Glyph * glyphs, hb_uint32 * numGlyphs, HB_Bool rightToLeft) static
Definition at line 74 of file qfontengine.cpp.
 {
     QFontEngine *fe = (QFontEngine *)font->userData;
     QVarLengthGlyphLayoutArray qglyphs(*numGlyphs);
     QTextEngine::ShaperFlags shaperFlags(QTextEngine::GlyphIndicesOnly);
     if (rightToLeft)
         shaperFlags |= QTextEngine::RightToLeft;
     int nGlyphs = *numGlyphs;
     bool result = fe->stringToCMap(reinterpret_cast<const QChar *>(string), length, &qglyphs, &nGlyphs, shaperFlags);
     *numGlyphs = nGlyphs;
     if (!result)
         return false;
     for (hb_uint32 i = 0; i < *numGlyphs; ++i)
         glyphs[i] = qglyphs.glyphs[i];
     return true;
 }
highByte()
static uchar highByte (glyph_t glyph) inline static
Definition at line 1311 of file qfontengine.cpp.
Referenced by QFontEngineMulti::addOutlineToPath(), QFontEngineMulti::boundingBox(), QFontEngineMulti::doKerning(), QFontEngineMulti::getGlyphBearings(), and QFontEngineMulti::recalcAdvances().
 { return glyph >> 24; }
kerning()
static QFixed kerning (int left, int right, const QFontEngine::KernPair * pairs, int numPairs) inline static
Definition at line 766 of file qfontengine.cpp.
Referenced by QFontEngine::doKerning().
 {
     uint left_right = (left << 16) + right;
     left = 0, right = numPairs - 1;
     while (left <= right) {
         int middle = left + ( ( right - left ) >> 1 );
         if(pairs[middle].left_right == left_right)
             return pairs[middle].adjust;
         if (pairs[middle].left_right < left_right)
             left = middle + 1;
         else
             right = middle - 1;
     }
     return 0;
 }
Q_GLOBAL_STATIC_WITH_INITIALIZER()
Q_GLOBAL_STATIC_WITH_INITIALIZER (QVector< QRgb > , qt_grayPalette , { x->resize(256);QRgb *it=x->data();for(int i=0;i< x->size();++i,++it) *it=0xff000000|i|(i<< 8)|(i<< 16);}) const &
Definition at line 1121 of file qfontengine.cpp.
{
     x->resize(256);
     QRgb *it = x->data();
     for (int i = 0; i < x->size(); ++i, ++it)
         *it = 0xff000000 | i | (i<<8) | (i<<16);
 })
 const QVector<QRgb> &QFontEngine::grayPalette()
 {
     return *qt_grayPalette();
 }
qt_addBitmapToPath()
Q_GUI_EXPORT void qt_addBitmapToPath (qreal x0, qreal y0, const uchar * image_data, int bpl, int w, int h, QPainterPath * path)
Definition at line 487 of file qfontengine.cpp.
Referenced by QFontEngine::addBitmapFontToPath(), QFreetypeFace::addBitmapToPath(), QFreetypeFace::addGlyphToPath(), and QFontEngineXLFD::addOutlineToPath().
 {
     uint *grid = new uint[(w+1)*(h+1)];
     // set up edges
     for (int y = 0; y <= h; ++y) {
         for (int x = 0; x <= w; ++x) {
             bool topLeft = (x == 0)|(y == 0) ? false : SET(x - 1, y - 1);
             bool topRight = (x == w)|(y == 0) ? false : SET(x, y - 1);
             bool bottomLeft = (x == 0)|(y == h) ? false : SET(x - 1, y);
             bool bottomRight = (x == w)|(y == h) ? false : SET(x, y);
             GRID(x, y) = 0;
             if ((!topRight) & bottomRight)
                 GRID(x, y) |= EdgeRight;
             if ((!bottomRight) & bottomLeft)
                 GRID(x, y) |= EdgeDown;
             if ((!bottomLeft) & topLeft)
                 GRID(x, y) |= EdgeLeft;
             if ((!topLeft) & topRight)
                 GRID(x, y) |= EdgeUp;
         }
     }
     // collect edges
     for (int y = 0; y < h; ++y) {
         for (int x = 0; x < w; ++x) {
             if (!GRID(x, y))
                 continue;
             // found start of a contour, follow it
             collectSingleContour(x0, y0, grid, x, y, w, h, path);
         }
     }
     delete [] grid;
 }
qtransform_equals_no_translate()
static bool qtransform_equals_no_translate (const QTransform & a, const QTransform & b) inline static
Definition at line 55 of file qfontengine.cpp.
Referenced by QFontEngine::glyphCache().
 {
     if (a.type() <= QTransform::TxTranslate && b.type() <= QTransform::TxTranslate) {
         return true;
     } else {
         // We always use paths for perspective text anyway, so no
         // point in checking the full matrix...
         Q_ASSERT(a.type() < QTransform::TxProject);
         Q_ASSERT(b.type() < QTransform::TxProject);
         return a.m11() == b.m11()
             && a.m12() == b.m12()
             && a.m21() == b.m21()
             && a.m22() == b.m22();
     }
 }
stripped()
static glyph_t stripped (glyph_t glyph) inline static
Definition at line 1315 of file qfontengine.cpp.
Referenced by QFontEngineMulti::addOutlineToPath(), QCoreApplication::arguments(), QFontEngineMulti::boundingBox(), QFontEngineMulti::doKerning(), QFontEngineMulti::getGlyphBearings(), QFontEngineMulti::recalcAdvances(), QSpinBoxPrivate::validateAndInterpret(), and QDoubleSpinBoxPrivate::validateAndInterpret().
 { return glyph & 0x00ffffff; }
Variable Documentation
hb_fontClass
const HB_FontClass hb_fontClass static
Initial value:
= {
    hb_stringToGlyphs, hb_getAdvances, hb_canRender, hb_getPointInOutline,
    hb_getGlyphMetrics, hb_getFontMetric
}
Definition at line 161 of file qfontengine.cpp.
Referenced by QFontEngine::QFontEngine().