Qt 4.8: /src/gui/text/qfont_p.h File Reference
qfont_p.h File Reference
#include "QtGui/qfont.h"
#include "QtCore/qmap.h"
#include "QtCore/qobject.h"
#include <private/qunicodetables_p.h>
#include <QtGui/qfontdatabase.h>
#include "private/qfixed_p.h"
Classes
class QFontCache
struct QFontCache::Engine
struct QFontCache::Key
struct QFontDef
class QFontEngineData
class QFontPrivate
Functions
Q_GUI_EXPORT int qt_defaultDpi ()
Q_GUI_EXPORT int qt_defaultDpiX ()
Q_GUI_EXPORT int qt_defaultDpiY ()
Function Documentation
qt_defaultDpi()
Q_GUI_EXPORT int qt_defaultDpi ()
Definition at line 240 of file qfont.cpp.
 {
     return qt_defaultDpiY();
 }
qt_defaultDpiX()
Q_GUI_EXPORT int qt_defaultDpiX ()
Definition at line 162 of file qfont.cpp.
Referenced by QPicture::exec(), QAlphaPaintEngine::flushAndInit(), QStaticTextPrivate::get(), QBlittablePixmapData::metric(), QRasterPixmapData::metric(), QPaintBuffer::metric(), QGLPixelBuffer::metric(), QPicture::metric(), QGLFramebufferObject::metric(), QGLPixmapData::metric(), QVGPixmapData::metric(), QMacQuartzPaintDevice::metric(), QPainterReplayer::process(), QFakeDevice::QFakeDevice(), and QPainterReplayer::setupTransform().
 {
     if (!qt_is_gui_used)
         return 75;
     int dpi;
 #ifdef Q_WS_X11
     dpi = QX11Info::appDpiX();
 #elif defined(Q_WS_WIN)
     dpi = GetDeviceCaps(shared_dc(),LOGPIXELSX);
 #elif defined(Q_WS_MAC)
     extern float qt_mac_defaultDpi_x(); //qpaintdevice_mac.cpp
     dpi = qt_mac_defaultDpi_x();
 #elif defined(Q_WS_QWS)
     if (!qt_screen)
         return 72;
     QScreen *screen = qt_screen;
     const QList<QScreen*> subScreens = qt_screen->subScreens();
     if (!subScreens.isEmpty())
         screen = subScreens.at(0);
     dpi = qRound(screen->width() / (screen->physicalWidth() / qreal(25.4)));
 #elif defined(Q_WS_QPA)
     QPlatformIntegration *pi = QApplicationPrivate::platformIntegration();
     if (pi) {
         QPlatformScreen *screen = QApplicationPrivate::platformIntegration()->screens().at(0);
         const QSize screenSize = screen->geometry().size();
         const QSize physicalSize = screen->physicalSize();
         dpi = qRound(screenSize.width() / (physicalSize.width() / qreal(25.4)));
     } else {
         //PI has not been initialised, or it is being initialised. Give a default dpi
         dpi = 100;
     }
 #elif defined(Q_OS_SYMBIAN)
     dpi = S60->defaultDpiX;
 #endif // Q_WS_X11
     return dpi;
 }
qt_defaultDpiY()
Q_GUI_EXPORT int qt_defaultDpiY ()
Definition at line 201 of file qfont.cpp.
Referenced by QTextEngine::calculateTabWidth(), QPaintBufferEngine::drawTextItem(), QPicture::exec(), QAlphaPaintEngine::flushAndInit(), QStaticTextPrivate::get(), QBlittablePixmapData::metric(), QRasterPixmapData::metric(), QPaintBuffer::metric(), QGLPixelBuffer::metric(), QPicture::metric(), QGLFramebufferObject::metric(), QGLPixmapData::metric(), QVGPixmapData::metric(), QMacQuartzPaintDevice::metric(), QFontDatabase::pointSizes(), QPainterReplayer::process(), QFakeDevice::QFakeDevice(), qt_defaultDpi(), qt_FcPatternToQFontDef(), QPainterReplayer::setupTransform(), QTextEngine::shapeText(), and QFontDatabase::smoothSizes().
 {
     if (!qt_is_gui_used)
         return 75;
     int dpi;
 #ifdef Q_WS_X11
     dpi = QX11Info::appDpiY();
 #elif defined(Q_WS_WIN)
     dpi = GetDeviceCaps(shared_dc(),LOGPIXELSY);
 #elif defined(Q_WS_MAC)
     extern float qt_mac_defaultDpi_y(); //qpaintdevice_mac.cpp
     dpi = qt_mac_defaultDpi_y();
 #elif defined(Q_WS_QWS)
     if (!qt_screen)
         return 72;
     QScreen *screen = qt_screen;
     const QList<QScreen*> subScreens = qt_screen->subScreens();
     if (!subScreens.isEmpty())
         screen = subScreens.at(0);
     dpi = qRound(screen->height() / (screen->physicalHeight() / qreal(25.4)));
 #elif defined(Q_WS_QPA)
     QPlatformIntegration *pi = QApplicationPrivate::platformIntegration();
     if (pi) {
         QPlatformScreen *screen = QApplicationPrivate::platformIntegration()->screens().at(0);
         const QSize screenSize = screen->geometry().size();
         const QSize physicalSize = screen->physicalSize();
         dpi = qRound(screenSize.height() / (physicalSize.height() / qreal(25.4)));
     } else {
         //PI has not been initialised, or it is being initialised. Give a default dpi
         dpi = 100;
     }
 #elif defined(Q_OS_SYMBIAN)
     dpi = S60->defaultDpiY;
 #endif // Q_WS_X11
     return dpi;
 }