Qt 4.8: /src/gui/text/qfontengine_ft.cpp File Reference
qfontengine_ft.cpp File Reference
#include "qdir.h"
#include "qmetatype.h"
#include "qtextstream.h"
#include "qvariant.h"
#include "qfontengine_ft_p.h"
#include "qfile.h"
#include "qabstractfileengine.h"
#include "qthreadstorage.h"
#include <qmath.h>
#include <private/qharfbuzz_p.h>
#include <ft2build.h>
#include <FT_FREETYPE_H>
#include <FT_OUTLINE_H>
#include <FT_SYNTHESIS_H>
#include <FT_TRUETYPE_TABLES_H>
#include <FT_TYPE1_TABLES_H>
#include <FT_GLYPH_H>
Classes
class QtFreetypeData
Macros
#define CEIL(x) (((x)+63) & -64)
#define FLOOR(x) ((x) & -64)
#define Q_FT_GLYPHSLOT_EMBOLDEN(slot)
#define QT_MAX_CACHED_GLYPH_SIZE 64
#define ROUND(x) (((x)+32) & -64)
#define TRUNC(x) ((x) >> 6)
#define X_SIZE(face, i) ((face)->available_sizes[i].width << 6)
#define Y_SIZE(face, i) ((face)->available_sizes[i].height << 6)
Functions
static void convertRGBToARGB (const uchar *src, uint *dst, int width, int height, int src_pitch, bool bgr, bool legacyFilter)
static void convertRGBToARGB_V (const uchar *src, uint *dst, int width, int height, int src_pitch, bool bgr, bool legacyFilter)
static void convoluteBitmap (const uchar *src, uchar *dst, int width, int height, int pitch)
static uint filterPixel (uint red, uint green, uint blue, bool legacyFilter)
static unsigned int getChar (const QChar *str, int &i, const int len)
static HB_Error hb_getSFntTable (void *font, HB_Tag tableTag, HB_Byte *buffer, HB_UInt *length)
void qt_addBitmapToPath (qreal x0, qreal y0, const uchar *image_data, int bpl, int w, int h, QPainterPath *path)
FT_Library qt_getFreetype ()
QtFreetypeData * qt_getFreetypeData ()
static void scaleOutline (FT_Face face, FT_GlyphSlot g, FT_Fixed x_scale, FT_Fixed y_scale)
Variables
static const ushort char_table []
static const int char_table_entries = sizeof(char_table)/sizeof(ushort)
static const uint subpixel_filter [3][3]
Macro Definition Documentation
CEIL
#define CEIL (x) (((x)+63) & -64)
Definition at line 108 of file qfontengine_ft.cpp.
Referenced by QFontEngineFT::alphaMapBoundingBox(), QFontEngineFT::boundingBox(), and QFontEngineFT::loadGlyph().
FLOOR
#define FLOOR (x) ((x) & -64)
Definition at line 107 of file qfontengine_ft.cpp.
Referenced by QFontEngineFT::alphaMapBoundingBox(), QFontEngineFT::boundingBox(), and QFontEngineFT::loadGlyph().
Q_FT_GLYPHSLOT_EMBOLDEN
#define Q_FT_GLYPHSLOT_EMBOLDEN (slot)
Definition at line 104 of file qfontengine_ft.cpp.
Referenced by QFontEngineFT::loadGlyph().
QT_MAX_CACHED_GLYPH_SIZE
#define QT_MAX_CACHED_GLYPH_SIZE 64
Definition at line 82 of file qfontengine_ft.cpp.
Referenced by QFreetypeFace::computeSize(), and QFontEngineFT::loadTransformedGlyphSet().
ROUND
#define ROUND (x) (((x)+32) & -64)
Definition at line 110 of file qfontengine_ft.cpp.
Referenced by QFontEngineFT::alphaMapBoundingBox(), QFontEngineFT::boundingBox(), and QFontEngineFT::loadGlyph().
TRUNC
#define TRUNC (x) ((x) >> 6)
Definition at line 109 of file qfontengine_ft.cpp.
Referenced by QFreetypeFace::addBitmapToPath(), QFontEngineFT::alphaMapBoundingBox(), QFontEngineFT::boundingBox(), and QFontEngineFT::loadGlyph().
X_SIZE
#define X_SIZE (face, i) ((face)->available_sizes[i].width << 6)
Definition at line 96 of file qfontengine_ft.cpp.
Referenced by QFreetypeFace::computeSize(), QFreetypeFace::getFace(), and QFontEngineFT::init().
Y_SIZE
#define Y_SIZE (face, i) ((face)->available_sizes[i].height << 6)
Definition at line 97 of file qfontengine_ft.cpp.
Referenced by QFreetypeFace::computeSize(), QFreetypeFace::getFace(), and QFontEngineFT::init().
Function Documentation
convertRGBToARGB()
static void convertRGBToARGB (const uchar * src, uint * dst, int width, int height, int src_pitch, bool bgr, bool legacyFilter) static
Definition at line 569 of file qfontengine_ft.cpp.
Referenced by QFontEngineFT::loadGlyph().
 {
     int h = height;
     const int offs = bgr ? -1 : 1;
     const int w = width * 3;
     while (h--) {
         uint *dd = dst;
         for (int x = 0; x < w; x += 3) {
             uint red = src[x+1-offs];
             uint green = src[x+1];
             uint blue = src[x+1+offs];
             *dd = filterPixel(red, green, blue, legacyFilter);
             ++dd;
         }
         dst += width;
         src += src_pitch;
     }
 }
convertRGBToARGB_V()
static void convertRGBToARGB_V (const uchar * src, uint * dst, int width, int height, int src_pitch, bool bgr, bool legacyFilter) static
Definition at line 588 of file qfontengine_ft.cpp.
Referenced by QFontEngineFT::loadGlyph().
 {
     int h = height;
     const int offs = bgr ? -src_pitch : src_pitch;
     while (h--) {
         for (int x = 0; x < width; x++) {
             uint red = src[x+src_pitch-offs];
             uint green = src[x+src_pitch];
             uint blue = src[x+src_pitch+offs];
             dst[x] = filterPixel(red, green, blue, legacyFilter);
         }
         dst += width;
         src += 3*src_pitch;
     }
 }
convoluteBitmap()
static void convoluteBitmap (const uchar * src, uchar * dst, int width, int height, int pitch) static
Definition at line 604 of file qfontengine_ft.cpp.
Referenced by QFontEngineFT::loadGlyph().
 {
     // convolute the bitmap with a triangle filter to get rid of color fringes
     // If we take account for a gamma value of 2, we end up with
     // weights of 1, 4, 9, 4, 1. We use an approximation of 1, 3, 8, 3, 1 here,
     // as this nicely sums up to 16 :)
     int h = height;
     while (h--) {
         dst[0] = dst[1] = 0;
         //
         for (int x = 2; x < width - 2; ++x) {
             uint sum = src[x-2] + 3*src[x-1] + 8*src[x] + 3*src[x+1] + src[x+2];
             dst[x] = (uchar) (sum >> 4);
         }
         dst[width - 2] = dst[width - 1] = 0;
         src += pitch;
         dst += pitch;
     }
 }
filterPixel()
static uint filterPixel (uint red, uint green, uint blue, bool legacyFilter) inline static
Definition at line 554 of file qfontengine_ft.cpp.
Referenced by convertRGBToARGB(), and convertRGBToARGB_V().
 {
     uint res;
     if (legacyFilter) {
         uint high = (red*subpixel_filter[0][0] + green*subpixel_filter[0][1] + blue*subpixel_filter[0][2]) >> 8;
         uint mid = (red*subpixel_filter[1][0] + green*subpixel_filter[1][1] + blue*subpixel_filter[1][2]) >> 8;
         uint low = (red*subpixel_filter[2][0] + green*subpixel_filter[2][1] + blue*subpixel_filter[2][2]) >> 8;
         res = (mid << 24) + (high << 16) + (mid << 8) + low;
     } else {
         uint alpha = green;
         res = (alpha << 24) + (red << 16) + (green << 8) + blue;
     }
     return res;
 }
getChar()
static unsigned int getChar (const QChar * str, int & i, const int len) inline static
Definition at line 1423 of file qfontengine_ft.cpp.
Referenced by QFontEngineFT::canRender(), QTextStreamPrivate::getNumber(), QTextStreamPrivate::getReal(), QXmlStreamReaderPrivate::parse(), QFontEngineFT::stringToCMap(), and QIODevice::write().
 {
     uint ucs4 = str[i].unicode();
     if (str[i].isHighSurrogate() && i < len-1 && str[i+1].isLowSurrogate()) {
         ++i;
         ucs4 = QChar::surrogateToUcs4(ucs4, str[i].unicode());
     }
     return ucs4;
 }
hb_getSFntTable()
static HB_Error hb_getSFntTable (void * font, HB_Tag tableTag, HB_Byte * buffer, HB_UInt * length) static
Definition at line 112 of file qfontengine_ft.cpp.
Referenced by QFreetypeFace::getFace().
 {
 #if (FREETYPE_MAJOR*10000 + FREETYPE_MINOR*100 + FREETYPE_PATCH) > 20103
     FT_Face face = (FT_Face)font;
     FT_ULong ftlen = *length;
     FT_Error error = 0;
     if ( !FT_IS_SFNT(face) )
         return HB_Err_Invalid_Argument;
     error = FT_Load_Sfnt_Table(face, tableTag, 0, buffer, &ftlen);
     *length = ftlen;
     return (HB_Error)error;
 #else
     return HB_Err_Invalid_Argument;
 #endif
 }
qt_addBitmapToPath()
void qt_addBitmapToPath (qreal x0, qreal y0, const uchar * image_data, int bpl, int w, int h, QPainterPath * path)
Definition at line 487 of file qfontengine.cpp.
Referenced by QFontEngine::addBitmapFontToPath(), QFreetypeFace::addBitmapToPath(), QFreetypeFace::addGlyphToPath(), and QFontEngineXLFD::addOutlineToPath().
 {
     uint *grid = new uint[(w+1)*(h+1)];
     // set up edges
     for (int y = 0; y <= h; ++y) {
         for (int x = 0; x <= w; ++x) {
             bool topLeft = (x == 0)|(y == 0) ? false : SET(x - 1, y - 1);
             bool topRight = (x == w)|(y == 0) ? false : SET(x, y - 1);
             bool bottomLeft = (x == 0)|(y == h) ? false : SET(x - 1, y);
             bool bottomRight = (x == w)|(y == h) ? false : SET(x, y);
             GRID(x, y) = 0;
             if ((!topRight) & bottomRight)
                 GRID(x, y) |= EdgeRight;
             if ((!bottomRight) & bottomLeft)
                 GRID(x, y) |= EdgeDown;
             if ((!bottomLeft) & topLeft)
                 GRID(x, y) |= EdgeLeft;
             if ((!topLeft) & topRight)
                 GRID(x, y) |= EdgeUp;
         }
     }
     // collect edges
     for (int y = 0; y < h; ++y) {
         for (int x = 0; x < w; ++x) {
             if (!GRID(x, y))
                 continue;
             // found start of a contour, follow it
             collectSingleContour(x0, y0, grid, x, y, w, h, path);
         }
     }
     delete [] grid;
 }
qt_getFreetype()
FT_Library qt_getFreetype ()
Definition at line 162 of file qfontengine_ft.cpp.
Referenced by QBasicUnixFontDatabase::addTTFile(), QFontDatabasePrivate::addTTFile(), QFontEngineFT::loadGlyph(), and queryFont().
 {
     QtFreetypeData *freetypeData = qt_getFreetypeData();
     if (!freetypeData->library)
         FT_Init_FreeType(&freetypeData->library);
     return freetypeData->library;
 }
qt_getFreetypeData()
QtFreetypeData* qt_getFreetypeData ()
Definition at line 153 of file qfontengine_ft.cpp.
Referenced by QFreetypeFace::getFace(), qt_getFreetype(), and QFreetypeFace::release().
 {
     QtFreetypeData *&freetypeData = theFreetypeData()->localData();
     if (!freetypeData)
         freetypeData = new QtFreetypeData;
     return freetypeData;
 }
scaleOutline()
static void scaleOutline (FT_Face face, FT_GlyphSlot g, FT_Fixed x_scale, FT_Fixed y_scale) static
Definition at line 436 of file qfontengine_ft.cpp.
Referenced by QFreetypeFace::addGlyphToPath().
 {
     x_scale = FT_MulDiv(x_scale, 1 << 10, face->units_per_EM);
     y_scale = FT_MulDiv(y_scale, 1 << 10, face->units_per_EM);
     FT_Vector *p = g->outline.points;
     const FT_Vector *e = p + g->outline.n_points;
     while (p < e) {
         p->x = FT_MulFix(p->x, x_scale);
         p->y = FT_MulFix(p->y, y_scale);
         ++p;
     }
 }
Variable Documentation
char_table
const ushort char_table[] static
Initial value:
= {
        40,
        67,
        70,
        75,
        86,
        88,
        89,
        91,
        102,
        114,
        124,
        127,
        205,
        645,
        884,
        922,
        1070,
        12386
}
Definition at line 1215 of file qfontengine_ft.cpp.
Referenced by QFontEngineFT::minRightBearing().
char_table_entries
const int char_table_entries = sizeof(char_table)/sizeof(ushort) static
Definition at line 1236 of file qfontengine_ft.cpp.
Referenced by QFontEngineFT::minRightBearing().
subpixel_filter
const uint subpixel_filter[3][3] static
Initial value:
= {
    { 180, 60, 16 },
    { 38, 180, 38 },
    { 16, 60, 180 }
}
Definition at line 548 of file qfontengine_ft.cpp.
Referenced by filterPixel().