Qt 4.8: /src/gui/text/qfont_win.cpp File Reference
qfont_win.cpp File Reference
#include "qfont.h"
#include "qfont_p.h"
#include "qfontengine_p.h"
#include "qtextengine_p.h"
#include "qfontmetrics.h"
#include "qfontinfo.h"
#include "qwidget.h"
#include "qpainter.h"
#include <limits.h>
#include "qt_windows.h"
#include <private/qapplication_p.h>
#include "qapplication.h"
#include <private/qunicodetables_p.h>
#include <qfontdatabase.h>
Functions
static float pixelSize (const QFontDef &request, int dpi)
static float pointSize (const QFontDef &fd, int dpi)
QFont qt_LOGFONTtoQFont (LOGFONT &lf, bool)
HDC shared_dc ()
QFont::Weight weightFromInteger (int weight)
Function Documentation
pixelSize()
static float pixelSize (const QFontDef & request, int dpi) inline static
Definition at line 80 of file qfont_win.cpp.
Referenced by QFontDatabasePrivate::addQPF2File(), QFontEngineWin::alphaMapForGlyph(), QFontEngineDirectWrite::cloneWithSize(), QFontEngineX11FT::cloneWithSize(), QFontEngineFT::cloneWithSize(), QCoreGraphicsPaintEnginePrivate::drawPath(), QGL2PaintEngineEx::drawStaticTextItem(), QGL2PaintEngineEx::drawTextItem(), QPaintEngineEx::flags(), QVGFontEngineCleaner::fontEngineDestroyed(), initializeDb(), QRawFontPrivate::isValid(), QFontDatabasePrivate::loadFromCache(), loadSingleEngine(), loadXlfds(), QRawFont::operator!=(), QRawFontPrivate::platformLoadFromData(), QCoreTextFontDatabase::populateFontDatabase(), QFontEngineDirectWrite::QFontEngineDirectWrite(), QFontEngineX11FT::QFontEngineX11FT(), QPlatformFontDatabase::registerQPF2Font(), releaseFontData(), QTextFormatPrivate::resolveFont(), resolveGdi32(), QTextCharFormat::setFont(), QCoreTextFontEngine::type(), and QRasterPaintEngine::type().
 {
     float pSize;
     if (request.pointSize != -1)
         pSize = request.pointSize * dpi/ 72.;
     else
         pSize = request.pixelSize;
     return pSize;
 }
pointSize()
static float pointSize (const QFontDef & fd, int dpi) inline static
Definition at line 90 of file qfont_win.cpp.
Referenced by QPlastiqueStyle::drawControl(), QFontFamilyDelegate::paint(), QFontDatabase::pointSizes(), qfontForCocoaFont(), qt_set_x11_resources(), QTextFormatPrivate::resolveFont(), QTextCharFormat::setFont(), QFontFamilyDelegate::sizeHint(), QFontPrivate::smallCapsFontPrivate(), and QFontDatabase::smoothSizes().
 {
     float pSize;
     if (fd.pointSize < 0)
         pSize = fd.pixelSize * 72. / ((float)dpi);
     else
         pSize = fd.pointSize;
     return pSize;
 }
qt_LOGFONTtoQFont()
QFont qt_LOGFONTtoQFont (LOGFONT & lf, bool)
Definition at line 64 of file qfont_win.cpp.
Referenced by QETWidget::forceUpdate(), qt_init(), and qt_set_windows_font_resources().
 {
     QString family = QString::fromWCharArray(lf.lfFaceName);
     QFont qf(family);
     qf.setItalic(lf.lfItalic);
     if (lf.lfWeight != FW_DONTCARE)
         qf.setWeight(weightFromInteger(lf.lfWeight));
     int lfh = qAbs(lf.lfHeight);
     qf.setPointSizeF(lfh * 72.0 / GetDeviceCaps(shared_dc(),LOGPIXELSY));
     qf.setUnderline(false);
     qf.setOverline(false);
     qf.setStrikeOut(false);
     return qf;
 }
shared_dc()
HDC shared_dc ()
Definition at line 118 of file qfontengine_win.cpp.
Referenced by qt_LOGFONTtoQFont().
 {
     QtHDC *&hdc = local_shared_dc()->localData();
     if (!hdc)
         hdc = new QtHDC;
     return hdc->hdc();
 }
weightFromInteger()
QFont::Weight weightFromInteger (int weight)
Definition at line 142 of file qfontdatabase.cpp.
Referenced by qt_LOGFONTtoQFont().
 {
     if (weight < 400)
         return QFont::Light;
     else if (weight < 600)
         return QFont::Normal;
     else if (weight < 700)
         return QFont::DemiBold;
     else if (weight < 800)
         return QFont::Bold;
     else
         return QFont::Black;
 }