Qt 4.8: /src/gui/text/qfontengine_qpf.cpp File Reference
qfontengine_qpf.cpp File Reference
#include "qfontengine_qpf_p.h"
#include "private/qpaintengine_raster_p.h"
#include <QtCore/qlibraryinfo.h>
#include <QtCore/qfileinfo.h>
#include <QtCore/qfile.h>
#include <QtCore/qdir.h>
#include <QtCore/qbuffer.h>
#include "private/qfontengine_ft_p.h"
#include "private/qcore_unix_p.h"
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <errno.h>
#include "qpfutil.cpp"
#include "private/qwscommand_qws_p.h"
#include "qwsdisplay_qws.h"
#include "qabstractfontengine_p.h"
#include "qplatformdefs.h"
Macros
#define DEBUG_VERIFY if (0) qDebug
#define READ_VERIFY(type, variable)
#define VERIFY(condition)
#define VERIFY_TAG(condition)
Functions
static unsigned int getChar (const QChar *str, int &i, const int len)
QString qws_fontCacheDir ()
template<typename T >
T readValue (const uchar *&data)
static const uchar * verifyTag (const uchar *tagPtr, const uchar *endPtr)
Macro Definition Documentation
DEBUG_VERIFY
#define DEBUG_VERIFY if (0) qDebug
Definition at line 87 of file qfontengine_qpf.cpp.
READ_VERIFY
#define READ_VERIFY (type, variable)
Value:
if (tagPtr + sizeof(type) > endPtr) { \
        DEBUG_VERIFY() << "read verify failed in line" << __LINE__; \
        return 0; \
    } \
    variable = qFromBigEndian<type>(tagPtr); \
    DEBUG_VERIFY() << "read value" << variable << "of type " #type; \
    tagPtr += sizeof(type)
Definition at line 90 of file qfontengine_qpf.cpp.
Referenced by verifyTag().
VERIFY
#define VERIFY (condition)
Value:
if (!(condition)) { \
        DEBUG_VERIFY() << "condition " #condition " failed in line" << __LINE__; \
        return 0; \
    }
Definition at line 107 of file qfontengine_qpf.cpp.
Referenced by QFontEngineQPF::verifyHeader().
VERIFY_TAG
#define VERIFY_TAG (condition)
Value:
if (!(condition)) { \
        DEBUG_VERIFY() << "verifying tag condition " #condition " failed in line" << __LINE__ << "with tag" << tag; \
        return 0; \
    }
Definition at line 113 of file qfontengine_qpf.cpp.
Referenced by verifyTag().
Function Documentation
getChar()
static unsigned int getChar (const QChar * str, int & i, const int len) inline static
Definition at line 279 of file qfontengine_qpf.cpp.
Referenced by QFontEngineQPF::canRender(), and QFontEngineQPF::stringToCMap().
 {
     uint ucs4 = str[i].unicode();
     if (str[i].isHighSurrogate() && i < len-1 && str[i+1].isLowSurrogate()) {
         ++i;
         ucs4 = QChar::surrogateToUcs4(ucs4, str[i].unicode());
     }
     return ucs4;
 }
qws_fontCacheDir()
QString qws_fontCacheDir ()
Definition at line 231 of file qfontengine_qpf.cpp.
Referenced by QFontDatabasePrivate::addQPF2File(), QFontEngineQPF::cleanUpAfterClientCrash(), cleanupFontsDir(), initializeDb(), QFontDatabasePrivate::loadFromCache(), and QFontEngineQPF::QFontEngineQPF().
 {
     QString dir;
 #if defined(Q_WS_QWS)
     extern QString qws_dataDir();
     dir = qws_dataDir();
 #else
     dir = QDir::tempPath();
 #endif
     dir.append(QLatin1String("/fonts/"));
     QDir qd(dir);
     if (!qd.exists() && !qd.mkpath(dir))
         dir = QDir::tempPath();
     return dir;
 }
readValue()
template<typename T > T readValue (const uchar *& data)
Definition at line 100 of file qfontengine_qpf.cpp.
 {
     T value = qFromBigEndian<T>(data);
     data += sizeof(T);
     return value;
 }
verifyTag()
static const uchar* verifyTag (const uchar * tagPtr, const uchar * endPtr) inline static
Definition at line 119 of file qfontengine_qpf.cpp.
Referenced by QFontEngineQPF::verifyHeader().
 {
     quint16 tag, length;
     READ_VERIFY(quint16, tag);
     READ_VERIFY(quint16, length);
     if (tag == QFontEngineQPF::Tag_EndOfHeader)
         return endPtr;
     if (tag < QFontEngineQPF::NumTags) {
         switch (tagTypes[tag]) {
             case QFontEngineQPF::BitFieldType:
             case QFontEngineQPF::StringType:
                 // can't do anything...
                 break;
             case QFontEngineQPF::UInt32Type:
                 VERIFY_TAG(length == sizeof(quint32));
                 break;
             case QFontEngineQPF::FixedType:
                 VERIFY_TAG(length == sizeof(quint32));
                 break;
             case QFontEngineQPF::UInt8Type:
                 VERIFY_TAG(length == sizeof(quint8));
                 break;
         }
 #if defined(DEBUG_HEADER)
         if (length == 1)
             qDebug() << "tag data" << hex << *tagPtr;
         else if (length == 4)
             qDebug() << "tag data" << hex << tagPtr[0] << tagPtr[1] << tagPtr[2] << tagPtr[3];
 #endif
     }
     return tagPtr + length;
 }