Qt 4.8: /src/gui/text/qfontengine_win.cpp File Reference
qfontengine_win.cpp File Reference
#include "qfontengine_p.h"
#include "qtextengine_p.h"
#include <qglobal.h>
#include "qt_windows.h"
#include <private/qapplication_p.h>
#include <private/qsystemlibrary_p.h>
#include <qpaintdevice.h>
#include <qpainter.h>
#include <limits.h>
#include <qendian.h>
#include <qmath.h>
#include <qthreadstorage.h>
#include <private/qunicodetables_p.h>
#include <qbitmap.h>
#include <private/qpainter_p.h>
#include "qpaintengine.h"
#include "qvarlengtharray.h"
#include <private/qpaintengine_raster_p.h>
#include <private/qnativeimage_p.h>
#include "qguifunctions_wince.h"
#include <qdebug.h>
Classes
class QtHDC
Macros
#define _WIN32_WINNT 0x0500
#define GGO_UNHINTED 0x0100
#define MAKE_TAG(ch1, ch2, ch3, ch4)
#define SPI_GETFONTSMOOTHINGCONTRAST 0x200C
#define SPI_SETFONTSMOOTHINGCONTRAST 0x200D
#define TT_PRIM_CSPLINE 3
Typedefs
typedef HRESULT(WINAPI * fScriptFreeCache) (SCRIPT_CACHE *)
typedef void * SCRIPT_CACHE
Enumerations
enum { max_font_count = 256 }
Functions
static bool addGlyphToPath (glyph_t glyph, const QFixedPoint &position, HDC hdc, QPainterPath *path, bool ttf, glyph_metrics_t *metric=0, qreal scale=1)
void calculateTTFGlyphWidth (HDC hdc, UINT glyph, int &width)
unsigned int getChar (const QChar *str, int &i, const int len)
static OUTLINETEXTMETRIC * getOutlineTextMetric (HDC hdc)
static quint32 getUInt (unsigned char *p)
static quint16 getUShort (unsigned char *p)
static double qt_fixed_to_double (const FIXED &p)
QFontEngine * qt_load_font_engine_win (const QFontDef &request)
static QPointF qt_to_qpointf (const POINTFX &pt, qreal scale)
HDC shared_dc ()
Variables
static const ushort char_table []
static const int char_table_entries = sizeof(char_table)/sizeof(ushort)
bool qt_cleartype_enabled
uint qt_pow_gamma [256]
fScriptFreeCache ScriptFreeCache
Macro Definition Documentation
_WIN32_WINNT
#define _WIN32_WINNT 0x0500
Definition at line 44 of file qfontengine_win.cpp.
GGO_UNHINTED
#define GGO_UNHINTED 0x0100
Definition at line 834 of file qfontengine_win.cpp.
MAKE_TAG
#define MAKE_TAG (ch1, ch2, ch3, ch4)
Value:
(\
    (((quint32)(ch4)) << 24) | \
    (((quint32)(ch3)) << 16) | \
    (((quint32)(ch2)) << 8) | \
    ((quint32)(ch1)) \
   )
Definition at line 84 of file qfontengine_win.cpp.
Referenced by QFontEngineWin::getCMap(), and QFontEngineWin::synthesized().
SPI_GETFONTSMOOTHINGCONTRAST
#define SPI_GETFONTSMOOTHINGCONTRAST 0x200C
Definition at line 1251 of file qfontengine_win.cpp.
Referenced by QFontEngineWin::alphaRGBMapForGlyph().
SPI_SETFONTSMOOTHINGCONTRAST
#define SPI_SETFONTSMOOTHINGCONTRAST 0x200D
Definition at line 1252 of file qfontengine_win.cpp.
Referenced by QFontEngineWin::alphaRGBMapForGlyph().
TT_PRIM_CSPLINE
#define TT_PRIM_CSPLINE 3
Definition at line 77 of file qfontengine_win.cpp.
Referenced by addGlyphToPath().
Typedef Documentation
fScriptFreeCache
typedef HRESULT(WINAPI * fScriptFreeCache) (SCRIPT_CACHE *)
Definition at line 151 of file qfontengine_win.cpp.
SCRIPT_CACHE
typedef void* SCRIPT_CACHE
Definition at line 150 of file qfontengine_win.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
max_font_count
Definition at line 631 of file qfontengine_win.cpp.
 { max_font_count = 256 };
Function Documentation
addGlyphToPath()
static bool addGlyphToPath (glyph_t glyph, const QFixedPoint & position, HDC hdc, QPainterPath * path, bool ttf, glyph_metrics_t * metric = 0, qreal scale = 1) static
Definition at line 837 of file qfontengine_win.cpp.
Referenced by QFontEngineWin::addGlyphsToPath(), and QFontEngineWin::getUnscaledGlyph().
 {
 #if defined(Q_WS_WINCE)
     Q_UNUSED(glyph);
     Q_UNUSED(hdc);
 #endif
     MAT2 mat;
     mat.eM11.value = mat.eM22.value = 1;
     mat.eM11.fract = mat.eM22.fract = 0;
     mat.eM21.value = mat.eM12.value = 0;
     mat.eM21.fract = mat.eM12.fract = 0;
     uint glyphFormat = GGO_NATIVE;
     if (ttf)
         glyphFormat |= GGO_GLYPH_INDEX;
     GLYPHMETRICS gMetric;
     memset(&gMetric, 0, sizeof(GLYPHMETRICS));
     int bufferSize = GDI_ERROR;
 #if !defined(Q_WS_WINCE)
     bufferSize = GetGlyphOutline(hdc, glyph, glyphFormat, &gMetric, 0, 0, &mat);
 #endif
     if ((DWORD)bufferSize == GDI_ERROR) {
         return false;
     }
     void *dataBuffer = new char[bufferSize];
     DWORD ret = GDI_ERROR;
 #if !defined(Q_WS_WINCE)
     ret = GetGlyphOutline(hdc, glyph, glyphFormat, &gMetric, bufferSize, dataBuffer, &mat);
 #endif
     if (ret == GDI_ERROR) {
         delete [](char *)dataBuffer;
         return false;
     }
     if(metric) {
         // #### obey scale
         *metric = glyph_metrics_t(gMetric.gmptGlyphOrigin.x, -gMetric.gmptGlyphOrigin.y,
                                   (int)gMetric.gmBlackBoxX, (int)gMetric.gmBlackBoxY,
                                   gMetric.gmCellIncX, gMetric.gmCellIncY);
     }
     int offset = 0;
     int headerOffset = 0;
     TTPOLYGONHEADER *ttph = 0;
     QPointF oset = position.toPointF();
     while (headerOffset < bufferSize) {
         ttph = (TTPOLYGONHEADER*)((char *)dataBuffer + headerOffset);
         QPointF lastPoint(qt_to_qpointf(ttph->pfxStart, scale));
         path->moveTo(lastPoint + oset);
         offset += sizeof(TTPOLYGONHEADER);
         TTPOLYCURVE *curve;
         while (offset<int(headerOffset + ttph->cb)) {
             curve = (TTPOLYCURVE*)((char*)(dataBuffer) + offset);
             switch (curve->wType) {
             case TT_PRIM_LINE: {
                 for (int i=0; i<curve->cpfx; ++i) {
                     QPointF p = qt_to_qpointf(curve->apfx[i], scale) + oset;
                     path->lineTo(p);
                 }
                 break;
             }
             case TT_PRIM_QSPLINE: {
                 const QPainterPath::Element &elm = path->elementAt(path->elementCount()-1);
                 QPointF prev(elm.x, elm.y);
                 QPointF endPoint;
                 for (int i=0; i<curve->cpfx - 1; ++i) {
                     QPointF p1 = qt_to_qpointf(curve->apfx[i], scale) + oset;
                     QPointF p2 = qt_to_qpointf(curve->apfx[i+1], scale) + oset;
                     if (i < curve->cpfx - 2) {
                         endPoint = QPointF((p1.x() + p2.x()) / 2, (p1.y() + p2.y()) / 2);
                     } else {
                         endPoint = p2;
                     }
                     path->quadTo(p1, endPoint);
                     prev = endPoint;
                 }
                 break;
             }
             case TT_PRIM_CSPLINE: {
                 for (int i=0; i<curve->cpfx; ) {
                     QPointF p2 = qt_to_qpointf(curve->apfx[i++], scale) + oset;
                     QPointF p3 = qt_to_qpointf(curve->apfx[i++], scale) + oset;
                     QPointF p4 = qt_to_qpointf(curve->apfx[i++], scale) + oset;
                     path->cubicTo(p2, p3, p4);
                 }
                 break;
             }
             default:
                 qWarning("QFontEngineWin::addOutlineToPath, unhandled switch case");
             }
             offset += sizeof(TTPOLYCURVE) + (curve->cpfx-1) * sizeof(POINTFX);
         }
         path->closeSubpath();
         headerOffset += ttph->cb;
     }
     delete [] (char*)dataBuffer;
     return true;
 }
calculateTTFGlyphWidth()
void calculateTTFGlyphWidth (HDC hdc, UINT glyph, int & width) inline
Definition at line 396 of file qfontengine_win.cpp.
Referenced by QFontEngineWin::recalcAdvances().
 {
 #if defined(Q_WS_WINCE)
     GetCharWidth32(hdc, glyph, glyph, &width);
 #else
     if (ptrGetCharWidthI)
         ptrGetCharWidthI(hdc, glyph, 1, 0, &width);
 #endif
 }
getChar()
unsigned int getChar (const QChar * str, int & i, const int len) inline
Definition at line 228 of file qfontengine_win.cpp.
Referenced by QFontEngineWin::canRender(), and QFontEngineWin::getGlyphIndexes().
 {
     uint ucs4 = str[i].unicode();
     if (str[i].isHighSurrogate() && i < len-1 && str[i+1].isLowSurrogate()) {
         ++i;
         ucs4 = QChar::surrogateToUcs4(ucs4, str[i].unicode());
     }
     return ucs4;
 }
getOutlineTextMetric()
static OUTLINETEXTMETRIC* getOutlineTextMetric (HDC hdc) static
Definition at line 184 of file qfontengine_win.cpp.
Referenced by QFontEngineWin::getCMap(), and QFontEngineWin::properties().
 {
     int size;
     size = GetOutlineTextMetrics(hdc, 0, 0);
     OUTLINETEXTMETRIC *otm = (OUTLINETEXTMETRIC *)malloc(size);
     GetOutlineTextMetrics(hdc, size, otm);
     return otm;
 }
getUInt()
static quint32 getUInt (unsigned char * p) inline static
Definition at line 154 of file qfontengine_win.cpp.
 {
     quint32 val;
     val = *p++ << 24;
     val |= *p++ << 16;
     val |= *p++ << 8;
     val |= *p;
     return val;
 }
getUShort()
static quint16 getUShort (unsigned char * p) inline static
Definition at line 165 of file qfontengine_win.cpp.
Referenced by QFontEngineWin::synthesized().
 {
     quint16 val;
     val = *p++ << 8;
     val |= *p;
     return val;
 }
qt_fixed_to_double()
static double qt_fixed_to_double (const FIXED & p) inline static
Definition at line 825 of file qfontengine_win.cpp.
Referenced by qt_to_qpointf().
{
     return ((p.value << 16) + p.fract) / 65536.0;
 }
qt_load_font_engine_win()
QFontEngine* qt_load_font_engine_win (const QFontDef & request)
Definition at line 998 of file qfontdatabase_win.cpp.
Referenced by QFontEngineWin::alphaRGBMapForGlyph().
 {
     // From qfont.cpp
     extern int qt_defaultDpi();
     QFontCache::Key key(request, QUnicodeTables::Common);
     QFontEngine *fe = QFontCache::instance()->findEngine(key);
     if (fe != 0)
         return fe;
     else
         return loadEngine(QUnicodeTables::Common, request, 0, qt_defaultDpi(), false, 0,
                           QStringList());
 }
qt_to_qpointf()
static QPointF qt_to_qpointf (const POINTFX & pt, qreal scale) inline static
Definition at line 829 of file qfontengine_win.cpp.
Referenced by addGlyphToPath().
{
     return QPointF(qt_fixed_to_double(pt.x) * scale, -qt_fixed_to_double(pt.y) * scale);
 }
shared_dc()
HDC shared_dc ()
Definition at line 118 of file qfontengine_win.cpp.
Referenced by QFontEngineWin::addGlyphsToPath(), QFontEngineWin::boundingBox(), QFontEngineWin::getCMap(), QFontEngineWin::getGlyphBearings(), QFontEngineWin::getSfntTableData(), QFontEngineWin::getUnscaledGlyph(), initFontInfo(), loadEngine(), QFontEngineWin::minRightBearing(), QFontEngineWin::properties(), QFontEngineWin::QFontEngineWin(), qt_defaultDpiX(), qt_defaultDpiY(), qt_LOGFONTtoQFont(), QFontEngineWin::recalcAdvances(), QFontEngineWin::selectDesignFont(), QFontEngineWin::synthesized(), and QFontEngineWin::~QFontEngineWin().
 {
     QtHDC *&hdc = local_shared_dc()->localData();
     if (!hdc)
         hdc = new QtHDC;
     return hdc->hdc();
 }
Variable Documentation
char_table
const ushort char_table[] static
Initial value:
= {
        40,
        67,
        70,
        75,
        86,
        88,
        89,
        91,
        102,
        114,
        124,
        127,
        205,
        645,
        884,
        922,
        1070,
        12386,
        0
}
Definition at line 632 of file qfontengine_win.cpp.
char_table_entries
const int char_table_entries = sizeof(char_table)/sizeof(ushort) static
Definition at line 654 of file qfontengine_win.cpp.
Referenced by QFontEngineWin::minRightBearing().
qt_cleartype_enabled
bool qt_cleartype_enabled
Definition at line 241 of file qapplication_win.cpp.
Referenced by QFontEngineWin::getSfntTableData().
qt_pow_gamma
uint qt_pow_gamma[256]
Definition at line 7029 of file qdrawhelper.cpp.
Referenced by QFontEngineWin::drawGDIGlyph().
ScriptFreeCache
fScriptFreeCache ScriptFreeCache