Qt 4.8: /src/gui/text/qfontengine_mac.mm File Reference
qfontengine_mac.mm File Reference
#include "qfontengine_mac_p.h"
#include <private/qapplication_p.h>
#include <private/qfontengine_p.h>
#include <private/qpainter_p.h>
#include <private/qtextengine_p.h>
#include <qbitmap.h>
#include <private/qpaintengine_mac_p.h>
#include <private/qprintengine_mac_p.h>
#include <qglobal.h>
#include <qpixmap.h>
#include <qpixmapcache.h>
#include <qvarlengtharray.h>
#include <qdebug.h>
#include <qendian.h>
#include <qmath.h>
#include <private/qimage_p.h>
#include <ApplicationServices/ApplicationServices.h>
#include <AppKit/AppKit.h>
Classes
struct QGlyphLayoutInfo
class QMacFontPath
Macros
#define FixedToQFixed(a) QFixed::fromFixed((a) >> 10)
#define QFixedToFixed(x) ((x).value() << 10)
Functions
static void addGlyphsToPathHelper (ATSUStyle style, glyph_t *glyphs, QFixedPoint *positions, int numGlyphs, QPainterPath *path)
static OSStatus atsuPostLayoutCallback (ATSULayoutOperationSelector selector, ATSULineRef lineRef, URefCon refCon, void *operationExtraParameter, ATSULayoutOperationCallbackStatus *callbackStatus)
static unsigned int getChar (const QChar *str, int &i, const int len)
Variables
int qt_antialiasing_threshold
Macro Definition Documentation
FixedToQFixed
#define FixedToQFixed (a) QFixed::fromFixed((a) >> 10)
Definition at line 73 of file qfontengine_mac.mm.
Referenced by atsuPostLayoutCallback().
QFixedToFixed
#define QFixedToFixed (x) ((x).value() << 10)
Definition at line 74 of file qfontengine_mac.mm.
Function Documentation
addGlyphsToPathHelper()
static void addGlyphsToPathHelper (ATSUStyle style, glyph_t * glyphs, QFixedPoint * positions, int numGlyphs, QPainterPath * path) static
Definition at line 890 of file qfontengine_mac.mm.
Referenced by QFontEngineMac::addGlyphsToPath(), and QFontEngineMac::getUnscaledGlyph().
 {
     if (!numGlyphs)
         return;
     OSStatus e;
     QMacFontPath fontpath(0, 0, path);
     ATSCubicMoveToUPP moveTo = NewATSCubicMoveToUPP(QMacFontPath::moveTo);
     ATSCubicLineToUPP lineTo = NewATSCubicLineToUPP(QMacFontPath::lineTo);
     ATSCubicCurveToUPP cubicTo = NewATSCubicCurveToUPP(QMacFontPath::cubicTo);
     ATSCubicClosePathUPP closePath = NewATSCubicClosePathUPP(QMacFontPath::closePath);
     // CTFontCreatePathForGlyph
     for (int i = 0; i < numGlyphs; ++i) {
         GlyphID glyph = glyphs[i];
         fontpath.setPosition(positions[i].x.toReal(), positions[i].y.toReal());
         ATSUGlyphGetCubicPaths(style, glyph, moveTo, lineTo,
                                cubicTo, closePath, &fontpath, &e);
     }
     DisposeATSCubicMoveToUPP(moveTo);
     DisposeATSCubicLineToUPP(lineTo);
     DisposeATSCubicCurveToUPP(cubicTo);
     DisposeATSCubicClosePathUPP(closePath);
 }
atsuPostLayoutCallback()
static OSStatus atsuPostLayoutCallback (ATSULayoutOperationSelector selector, ATSULineRef lineRef, URefCon refCon, void * operationExtraParameter, ATSULayoutOperationCallbackStatus * callbackStatus) static
Definition at line 221 of file qfontengine_mac.mm.
Referenced by QFontEngineMacMulti::stringToCMapInternal().
 {
     Q_UNUSED(selector);
     Q_UNUSED(operationExtraParameter);
     QGlyphLayoutInfo *nfo = reinterpret_cast<QGlyphLayoutInfo *>(refCon);
     nfo->callbackCalled = true;
     ATSLayoutRecord *layoutData = 0;
     ItemCount itemCount = 0;
     OSStatus e = noErr;
     e = ATSUDirectGetLayoutDataArrayPtrFromLineRef(lineRef, kATSUDirectDataLayoutRecordATSLayoutRecordCurrent,
                                                    /*iCreate =*/ false,
                                                    (void **) &layoutData,
                                                    &itemCount);
     if (e != noErr)
         return e;
     *nfo->numGlyphs = itemCount - 1;
     Fixed *baselineDeltas = 0;
     e = ATSUDirectGetLayoutDataArrayPtrFromLineRef(lineRef, kATSUDirectDataBaselineDeltaFixedArray,
                                                    /*iCreate =*/ true,
                                                    (void **) &baselineDeltas,
                                                    &itemCount);
     if (e != noErr)
         return e;
     int nextCharStop = -1;
     int currentClusterGlyph = -1; // first glyph in log cluster
     QFontEngineMacMulti::ShaperItem *item = nfo->shaperItem;
     if (item->charAttributes) {
         item = nfo->shaperItem;
 #if !defined(QT_NO_DEBUG)
         int surrogates = 0;
         const QChar *str = item->string;
         for (int i = item->from; i < item->from + item->length - 1; ++i)
             surrogates += (str[i].isHighSurrogate() && str[i+1].isLowSurrogate());
 #endif
         for (nextCharStop = item->from; nextCharStop < item->from + item->length; ++nextCharStop)
             if (item->charAttributes[nextCharStop].charStop)
                 break;
         nextCharStop -= item->from;
     }
     nfo->glyphs->attributes[0].clusterStart = true;
     int glyphIdx = 0;
     int glyphIncrement = 1;
     if (nfo->flags & QTextEngine::RightToLeft) {
         glyphIdx  = itemCount - 2;
         glyphIncrement = -1;
     }
     for (int i = 0; i < *nfo->numGlyphs; ++i, glyphIdx += glyphIncrement) {
         int charOffset = layoutData[glyphIdx].originalOffset / sizeof(UniChar);
         const int fontIdx = nfo->mappedFonts[charOffset];
         ATSGlyphRef glyphId = layoutData[glyphIdx].glyphID;
         QFixed yAdvance = FixedToQFixed(baselineDeltas[glyphIdx]);
         QFixed xAdvance = FixedToQFixed(layoutData[glyphIdx + 1].realPos - layoutData[glyphIdx].realPos);
         if (nfo->styleStrategy & QFont::ForceIntegerMetrics) {
             yAdvance = yAdvance.round();
             xAdvance = xAdvance.round();
         }
         if (glyphId != 0xffff || i == 0) {
             if (i < nfo->glyphs->numGlyphs)
             {
                 nfo->glyphs->glyphs[i] = (glyphId & 0x00ffffff) | (fontIdx << 24);
                 nfo->glyphs->advances_y[i] = yAdvance;
                 nfo->glyphs->advances_x[i] = xAdvance;
             }
         } else {
             // ATSUI gives us 0xffff as glyph id at the index in the glyph array for
             // a character position that maps to a ligtature. Such a glyph id does not
             // result in any visual glyph, but it may have an advance, which is why we
             // sum up the glyph advances.
             --i;
             nfo->glyphs->advances_y[i] += yAdvance;
             nfo->glyphs->advances_x[i] += xAdvance;
             *nfo->numGlyphs -= 1;
         }
         if (item->log_clusters) {
             if (charOffset >= nextCharStop) {
                 nfo->glyphs->attributes[i].clusterStart = true;
                 currentClusterGlyph = i;
                 ++nextCharStop;
                 for (; nextCharStop < item->length; ++nextCharStop)
                     if (item->charAttributes[item->from + nextCharStop].charStop)
                         break;
             } else {
                 if (currentClusterGlyph == -1)
                     currentClusterGlyph = i;
             }
             item->log_clusters[charOffset] = currentClusterGlyph;
             // surrogate handling
             if (charOffset < item->length - 1) {
                 QChar current = item->string[item->from + charOffset];
                 QChar next = item->string[item->from + charOffset + 1];
                 if (current.isHighSurrogate() && next.isLowSurrogate())
                     item->log_clusters[charOffset + 1] = currentClusterGlyph;
             }
         }
     }
     /*
     if (item) {
         qDebug() << "resulting logclusters:";
         for (int i = 0; i < item->length; ++i)
             qDebug() << "logClusters[" << i << "] =" << item->log_clusters[i];
         qDebug() << "clusterstarts:";
         for (int i = 0; i < *nfo->numGlyphs; ++i)
             qDebug() << "clusterStart[" << i << "] =" << nfo->glyphs[i].attributes.clusterStart;
     }
     */
     ATSUDirectReleaseLayoutDataArrayPtr(lineRef, kATSUDirectDataBaselineDeltaFixedArray,
                                         (void **) &baselineDeltas);
     ATSUDirectReleaseLayoutDataArrayPtr(lineRef, kATSUDirectDataLayoutRecordATSLayoutRecordCurrent,
                                         (void **) &layoutData);
     *callbackStatus = kATSULayoutOperationCallbackStatusHandled;
     return noErr;
 }
getChar()
static unsigned int getChar (const QChar * str, int & i, const int len) inline static
Definition at line 735 of file qfontengine_mac.mm.
Referenced by QFontEngineMac::stringToCMap().
 {
     uint ucs4 = str[i].unicode();
     if (str[i].isHighSurrogate() && i < len-1 && str[i+1].isLowSurrogate()) {
         ++i;
         ucs4 = QChar::surrogateToUcs4(ucs4, str[i].unicode());
     }
     return ucs4;
 }
Variable Documentation
qt_antialiasing_threshold
int qt_antialiasing_threshold
Definition at line 495 of file qapplication.cpp.
Referenced by QFontEngineMac::imageForGlyph().