Qt 4.8: /src/gui/text/qfont_mac.cpp File Reference
qfont_mac.cpp File Reference
#include "qfont.h"
#include "qfont_p.h"
#include "qfontengine_p.h"
#include "qfontengine_mac_p.h"
#include "qfontengine_coretext_p.h"
#include "qfontinfo.h"
#include "qfontmetrics.h"
#include "qpaintdevice.h"
#include "qstring.h"
#include <private/qt_mac_p.h>
#include <private/qtextengine_p.h>
#include <private/qunicodetables_p.h>
#include <qapplication.h>
#include "qfontdatabase.h"
#include <qpainter.h>
#include "qtextengine_p.h"
#include <stdlib.h>
Functions
float qt_mac_defaultDpi_x ()
int qt_mac_pixelsize (const QFontDef &def, int dpi)
int qt_mac_pointsize (const QFontDef &def, int dpi)
Function Documentation
qt_mac_defaultDpi_x()
float qt_mac_defaultDpi_x ()
Warning
This function is not part of the public interface.
Definition at line 61 of file qpaintdevice_mac.cpp.
Referenced by QMacPixmapData::metric(), QWidget::metric(), qt_defaultDpiX(), qt_mac_pixelsize(), and qt_mac_pointsize().
 {
     // Mac OS X currently assumes things to be 72 dpi.
     // (see http://developer.apple.com/releasenotes/GraphicsImaging/RN-ResolutionIndependentUI/)
     // This may need to be re-worked as we go further in the resolution-independence stuff.
     return 72;
 }
qt_mac_pixelsize()
int qt_mac_pixelsize (const QFontDef & def, int dpi)
Definition at line 64 of file qfont_mac.cpp.
Referenced by QFontDatabase::load().
 {
     float ret;
     if(def.pixelSize == -1)
         ret = def.pointSize *  dpi / qt_mac_defaultDpi_x();
     else
         ret = def.pixelSize;
     return qRound(ret);
 }
qt_mac_pointsize()
int qt_mac_pointsize (const QFontDef & def, int dpi)
Definition at line 73 of file qfont_mac.cpp.
Referenced by QFontDatabase::load().
 {
     float ret;
     if(def.pointSize < 0)
         ret = def.pixelSize * qt_mac_defaultDpi_x() / float(dpi);
     else
         ret = def.pointSize;
     return qRound(ret);
 }