Qt 4.8: /src/gui/text/qfontdatabase_qws.cpp File Reference
qfontdatabase_qws.cpp File Reference
#include "qdir.h"
#include "qscreen_qws.h"
#include "qwindowsystem_qws.h"
#include "qlibraryinfo.h"
#include "qabstractfileengine.h"
#include <QtCore/qsettings.h>
#include "qfontengine_ft_p.h"
#include <ft2build.h>
#include <FT_FREETYPE_H>
#include "qfontengine_qpf_p.h"
#include "private/qfactoryloader_p.h"
#include "private/qcore_unix_p.h"
#include "qabstractfontengine_qws.h"
#include "qabstractfontengine_p.h"
#include <qdatetime.h>
#include "qplatformdefs.h"
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <errno.h>
Macros
#define X_SIZE(face, i) ((face)->available_sizes[i].width << 6)
#define Y_SIZE(face, i) ((face)->available_sizes[i].height << 6)
Functions
static void initializeDb ()
static void load (const QString &=QString(), int=-1)
static QFontEngine * loadEngine (int script, const QFontPrivate *fp, const QFontDef &request, QtFontFamily *family, QtFontFoundry *foundry, QtFontStyle *style, QtFontSize *size)
static QFontEngine * loadSingleEngine (int script, const QFontPrivate *fp, const QFontDef &request, QtFontFamily *family, QtFontFoundry *foundry, QtFontStyle *style, QtFontSize *size)
Q_GLOBAL_STATIC_WITH_ARGS (QFactoryLoader, loader,(QFontEngineFactoryInterface_iid, QLatin1String("/fontengines"), Qt::CaseInsensitive)) const quint8 DatabaseVersion
void qt_applyFontDatabaseSettings (const QSettings &settings)
void qt_qws_init_fontdb ()
QString qws_fontCacheDir ()
static QString qwsFontPath ()
static void registerFont (QFontDatabasePrivate::ApplicationFont *fnt)
Macro Definition Documentation
X_SIZE
#define X_SIZE (face, i) ((face)->available_sizes[i].width << 6)
Definition at line 550 of file qfontdatabase_qws.cpp.
Y_SIZE
#define Y_SIZE (face, i) ((face)->available_sizes[i].height << 6)
Definition at line 551 of file qfontdatabase_qws.cpp.
Function Documentation
initializeDb()
static void initializeDb () static
Warning
This function is not part of the public interface.
Definition at line 283 of file qfontdatabase_qws.cpp.
Referenced by load(), qt_applyFontDatabaseSettings(), qt_qws_init_fontdb(), and registerFont().
 {
     QFontDatabasePrivate *db = privateDb();
     if (!db || db->count)
         return;
     QString fontpath = qwsFontPath();
 #ifndef QT_FONTS_ARE_RESOURCES
     QString fontDirFile = fontpath + QLatin1String("/fontdir");
     if(!QFile::exists(fontpath)) {
         qFatal("QFontDatabase: Cannot find font directory %s - is Qt installed correctly?",
                fontpath.toLocal8Bit().constData());
     }
     const bool loaded = db->loadFromCache(fontpath);
     if (db->reregisterAppFonts) {
         db->reregisterAppFonts = false;
         for (int i = 0; i < db->applicationFonts.count(); ++i)
             if (!db->applicationFonts.at(i).families.isEmpty()) {
                 registerFont(&db->applicationFonts[i]);
             }
     }
     if (loaded)
         return;
     QString dbFileName = qws_fontCacheDir() + QLatin1String("/fontdb");
     QFile binaryDb(dbFileName + QLatin1String(".tmp"));
     binaryDb.open(QIODevice::WriteOnly | QIODevice::Truncate);
     db->stream = new QDataStream(&binaryDb);
     *db->stream << DatabaseVersion << quint8(db->stream->version()) << fontpath;
 //    qDebug() << "creating binary database at" << binaryDb.fileName();
     // Load in font definition file
     FILE* fontdef=fopen(fontDirFile.toLocal8Bit().constData(),"r");
     if (fontdef) {
         char buf[200]="";
         char name[200]="";
         char render[200]="";
         char file[200]="";
         char isitalic[10]="";
         char flags[10]="";
         do {
             fgets(buf,200,fontdef);
             if (buf[0] != '#') {
                 int weight=50;
                 int size=0;
                 sscanf(buf,"%s %s %s %s %d %d %s",name,file,render,isitalic,&weight,&size,flags);
                 QString filename;
                 if (file[0] != '/')
                     filename.append(fontpath).append(QLatin1Char('/'));
                 filename += QLatin1String(file);
                 bool italic = isitalic[0] == 'y';
                 bool smooth = QByteArray(flags).contains('s');
                 if (file[0] && QFile::exists(filename))
                     db->addFont(QString::fromUtf8(name), /*foundry*/"", weight, italic, size/10, QFile::encodeName(filename), /*fileIndex*/ 0, smooth);
             }
         } while (!feof(fontdef));
         fclose(fontdef);
     }
     QDir dir(fontpath, QLatin1String("*.qpf"));
     for (int i=0; i<int(dir.count()); i++) {
         int u0 = dir[i].indexOf(QLatin1Char('_'));
         int u1 = dir[i].indexOf(QLatin1Char('_'), u0+1);
         int u2 = dir[i].indexOf(QLatin1Char('_'), u1+1);
         int u3 = dir[i].indexOf(QLatin1Char('.'), u1+1);
         if (u2 < 0) u2 = u3;
         QString familyname = dir[i].left(u0);
         int pixelSize = dir[i].mid(u0+1,u1-u0-1).toInt()/10;
         bool italic = dir[i].mid(u2-1,1) == QLatin1String("i");
         int weight = dir[i].mid(u1+1,u2-u1-1-(italic?1:0)).toInt();
         db->addFont(familyname, /*foundry*/ "qt", weight, italic, pixelSize, QFile::encodeName(dir.absoluteFilePath(dir[i])),
                     /*fileIndex*/ 0, /*antialiased*/ true);
     }
 #ifndef QT_NO_FREETYPE
     dir.setNameFilters(QStringList() << QLatin1String("*.ttf")
                        << QLatin1String("*.ttc") << QLatin1String("*.pfa")
                        << QLatin1String("*.pfb"));
     dir.refresh();
     for (int i = 0; i < int(dir.count()); ++i) {
         const QByteArray file = QFile::encodeName(dir.absoluteFilePath(dir[i]));
 //        qDebug() << "looking at" << file;
         db->addTTFile(file);
     }
 #endif
 #ifndef QT_NO_QWS_QPF2
     dir.setNameFilters(QStringList() << QLatin1String("*.qpf2"));
     dir.refresh();
     for (int i = 0; i < int(dir.count()); ++i) {
         const QByteArray file = QFile::encodeName(dir.absoluteFilePath(dir[i]));
 //        qDebug() << "looking at" << file;
         db->addQPF2File(file);
     }
 #endif
 #else //QT_FONTS_ARE_RESOURCES
 #ifdef QFONTDATABASE_DEBUG
     {
         QResource fontdir(fontpath);
         FriendlyResource *fr = static_cast<FriendlyResource*>(&fontdir);
         qDebug() << "fontdir" << fr->isValid() << fr->isDir() << fr->children();
     }
 #endif
 #ifndef QT_NO_QWS_QPF2
     QDir dir(fontpath, QLatin1String("*.qpf2"));
     for (int i = 0; i < int(dir.count()); ++i) {
         const QByteArray file = QFile::encodeName(dir.absoluteFilePath(dir[i]));
         //qDebug() << "looking at" << file;
         db->addQPF2File(file);
     }
 #endif
 #endif //QT_FONTS_ARE_RESOURCES
 #ifdef QFONTDATABASE_DEBUG
     // print the database
     for (int f = 0; f < db->count; f++) {
         QtFontFamily *family = db->families[f];
         FD_DEBUG("'%s' %s", qPrintable(family->name), (family->fixedPitch ? "fixed" : ""));
 #if 0
         for (int i = 0; i < QFont::LastPrivateScript; ++i) {
             FD_DEBUG("\t%s: %s", qPrintable(QFontDatabase::scriptName((QFont::Script) i)),
                      ((family->scripts[i] & QtFontFamily::Supported) ? "Supported" :
                       (family->scripts[i] & QtFontFamily::UnSupported) == QtFontFamily::UnSupported ?
                       "UnSupported" : "Unknown"));
         }
 #endif
         for (int fd = 0; fd < family->count; fd++) {
             QtFontFoundry *foundry = family->foundries[fd];
             FD_DEBUG("\t\t'%s'", qPrintable(foundry->name));
             for (int s = 0; s < foundry->count; s++) {
                 QtFontStyle *style = foundry->styles[s];
                 FD_DEBUG("\t\t\tstyle: style=%d weight=%d\n"
                          "\t\t\tstretch=%d",
                          style->key.style, style->key.weight,
                          style->key.stretch);
                 if (style->smoothScalable)
                     FD_DEBUG("\t\t\t\tsmooth scalable");
                 else if (style->bitmapScalable)
                     FD_DEBUG("\t\t\t\tbitmap scalable");
                 if (style->pixelSizes) {
                     FD_DEBUG("\t\t\t\t%d pixel sizes",  style->count);
                     for (int z = 0; z < style->count; ++z) {
                         QtFontSize *size = style->pixelSizes + z;
                         FD_DEBUG("\t\t\t\t  size %5d",
                                   size->pixelSize);
                     }
                 }
             }
         }
     }
 #endif // QFONTDATABASE_DEBUG
 #ifndef QT_NO_LIBRARY
     QStringList pluginFoundries = loader()->keys();
 //    qDebug() << "plugin foundries:" << pluginFoundries;
     for (int i = 0; i < pluginFoundries.count(); ++i) {
         const QString foundry(pluginFoundries.at(i));
         QFontEngineFactoryInterface *factory = qobject_cast<QFontEngineFactoryInterface *>(loader()->instance(foundry));
         if (!factory) {
             qDebug() << "Could not load plugin for foundry" << foundry;
             continue;
         }
         QList<QFontEngineInfo> fonts = factory->availableFontEngines();
         for (int i = 0; i < fonts.count(); ++i) {
             QFontEngineInfo info = fonts.at(i);
             int weight = info.weight();
             if (weight <= 0)
                 weight = QFont::Normal;
             db->addFont(info.family(), foundry.toLatin1().constData(),
                         weight, info.style() != QFont::StyleNormal,
                         qRound(info.pixelSize()), /*file*/QByteArray(),
                         /*fileIndex*/0, /*antiAliased*/true,
                         info.writingSystems());
         }
     }
 #endif
 #ifndef QT_FONTS_ARE_RESOURCES
     // the empty string/familyname signifies the end of the font list.
     *db->stream << QString();
 #endif
     {
         bool coveredWritingSystems[QFontDatabase::WritingSystemsCount] = { 0 };
         db->fallbackFamilies.clear();
         for (int i = 0; i < db->count; ++i) {
             QtFontFamily *family = db->families[i];
             bool add = false;
             if (family->count == 0)
                 continue;
             if (family->bogusWritingSystems)
                 continue;
             for (int ws = 1; ws < QFontDatabase::WritingSystemsCount; ++ws) {
                 if (coveredWritingSystems[ws])
                     continue;
                 if (family->writingSystems[ws] & QtFontFamily::Supported) {
                     coveredWritingSystems[ws] = true;
                     add = true;
                 }
             }
             if (add)
                 db->fallbackFamilies << family->name;
         }
         //qDebug() << "fallbacks on the server:" << db->fallbackFamilies;
 #ifndef QT_FONTS_ARE_RESOURCES
         *db->stream << db->fallbackFamilies;
 #endif
     }
 #ifndef QT_FONTS_ARE_RESOURCES
     delete db->stream;
     db->stream = 0;
     QFile::remove(dbFileName);
     binaryDb.rename(dbFileName);
 #endif
 }
load()
static void load (const QString & = QString(), int = -1) inline static
Definition at line 539 of file qfontdatabase_qws.cpp.
 {
     initializeDb();
 }
loadEngine()
static QFontEngine* loadEngine (int script, const QFontPrivate * fp, const QFontDef & request, QtFontFamily * family, QtFontFoundry * foundry, QtFontStyle * style, QtFontSize * size) static
Definition at line 697 of file qfontdatabase_qws.cpp.
Referenced by registerFont().
 {
     QScopedPointer<QFontEngine> engine(loadSingleEngine(script, fp, request, family, foundry,
                                        style, size));
 #ifndef QT_NO_QWS_QPF
     if (!engine.isNull()
         && script == QUnicodeTables::Common
         && !(request.styleStrategy & QFont::NoFontMerging) && !engine->symbol) {
         QStringList fallbacks = privateDb()->fallbackFamilies;
         if (family && !family->fallbackFamilies.isEmpty())
             fallbacks = family->fallbackFamilies;
         QFontEngine *fe = new QFontEngineMultiQWS(engine.data(), script, fallbacks);
         engine.take();
         engine.reset(fe);
     }
 #endif
     return engine.take();
 }
loadSingleEngine()
static QFontEngine* loadSingleEngine (int script, const QFontPrivate * fp, const QFontDef & request, QtFontFamily * family, QtFontFoundry * foundry, QtFontStyle * style, QtFontSize * size) static
is this the best way????
Definition at line 557 of file qfontdatabase_qws.cpp.
Referenced by loadEngine().
 {
     Q_UNUSED(script);
     Q_UNUSED(fp);
 #ifdef QT_NO_FREETYPE
     Q_UNUSED(foundry);
 #endif
 #ifdef QT_NO_QWS_QPF
     Q_UNUSED(family);
 #endif
     Q_ASSERT(size);
     int pixelSize = size->pixelSize;
     if (!pixelSize || (style->smoothScalable && pixelSize == SMOOTH_SCALABLE))
         pixelSize = request.pixelSize;
 #ifndef QT_NO_QWS_QPF2
     if (foundry->name == QLatin1String("prerendered")) {
 #ifdef QT_FONTS_ARE_RESOURCES
         QResource res(QLatin1String(size->fileName.constData()));
         if (res.isValid()) {
             QFontEngineQPF *fe = new QFontEngineQPF(request, res.data(), res.size());
             if (fe->isValid())
                 return fe;
             delete fe;
             qDebug() << "fontengine is not valid! " << size->fileName;
         } else {
             qDebug() << "Resource not valid" << size->fileName;
         }
 #else
         int f = ::open(size->fileName, O_RDONLY, 0);
         if (f >= 0) {
             QFontEngineQPF *fe = new QFontEngineQPF(request, f);
             if (fe->isValid())
                 return fe;
             delete fe; // will close f
             qDebug() << "fontengine is not valid!";
         }
 #endif
     } else
 #endif
     if ( foundry->name != QLatin1String("qt") ) {
         QString file = QFile::decodeName(size->fileName);
         QFontDef def = request;
         def.pixelSize = pixelSize;
 #ifdef QT_NO_QWS_SHARE_FONTS
         bool shareFonts = false;
 #else
         static bool dontShareFonts = !qgetenv("QWS_NO_SHARE_FONTS").isEmpty();
         bool shareFonts = !dontShareFonts;
 #endif
         QScopedPointer<QFontEngine> engine;
 #ifndef QT_NO_LIBRARY
         QFontEngineFactoryInterface *factory = qobject_cast<QFontEngineFactoryInterface *>(loader()->instance(foundry->name));
         if (factory) {
             QFontEngineInfo info;
             info.setFamily(request.family);
             info.setPixelSize(request.pixelSize);
             info.setStyle(QFont::Style(request.style));
             info.setWeight(request.weight);
             // #### antialiased
             QAbstractFontEngine *customEngine = factory->create(info);
             if (customEngine) {
                 engine.reset(new QProxyFontEngine(customEngine, def));
                 if (shareFonts) {
                     QVariant hint = customEngine->fontProperty(QAbstractFontEngine::CacheGlyphsHint);
                     if (hint.isValid())
                         shareFonts = hint.toBool();
                     else
                         shareFonts = (pixelSize < 64);
                 }
             }
         }
 #endif // QT_NO_LIBRARY
         if ((engine.isNull() && !file.isEmpty() && QFile::exists(file)) || privateDb()->isApplicationFont(file)) {
             QFontEngine::FaceId faceId;
             faceId.filename = file.toLocal8Bit();
             faceId.index = size->fileIndex;
 #ifndef QT_NO_FREETYPE
             QScopedPointer<QFontEngineFT> fte(new QFontEngineFT(def));
             bool antialias = style->antialiased && !(request.styleStrategy & QFont::NoAntialias);
             if (fte->init(faceId, antialias,
                           antialias ? QFontEngineFT::Format_A8 : QFontEngineFT::Format_Mono)) {
 #ifdef QT_NO_QWS_QPF2
                 return fte.take();
 #else
                 // try to distinguish between bdf and ttf fonts we can pre-render
                 // and don't try to share outline fonts
                 shareFonts = shareFonts
                              && !fte->defaultGlyphs()->outline_drawing
                              && !fte->getSfntTable(MAKE_TAG('h', 'e', 'a', 'd')).isEmpty();
                 engine.reset(fte.take());
 #endif
             }
 #endif // QT_NO_FREETYPE
         }
         if (!engine.isNull()) {
 #if !defined(QT_NO_QWS_QPF2) && !defined(QT_FONTS_ARE_RESOURCES)
             if (shareFonts) {
                 QScopedPointer<QFontEngineQPF> fe(new QFontEngineQPF(def, -1, engine.data()));
                 engine.take();
                 if (fe->isValid())
                     return fe.take();
                 qWarning("Initializing QFontEngineQPF failed for %s", qPrintable(file));
                 engine.reset(fe->takeRenderingEngine());
             }
 #endif
             return engine.take();
         }
     } else
     {
 #ifndef QT_NO_QWS_QPF
         QString fn = qwsFontPath();
         fn += QLatin1Char('/');
         fn += family->name.toLower()
               + QLatin1Char('_') + QString::number(pixelSize*10)
               + QLatin1Char('_') + QString::number(style->key.weight)
               + (style->key.style == QFont::StyleItalic ?
                  QLatin1String("i.qpf") : QLatin1String(".qpf"));
         //###rotation ###
         QFontEngine *fe = new QFontEngineQPF1(request, fn);
         return fe;
 #endif // QT_NO_QWS_QPF
     }
     return new QFontEngineBox(pixelSize);
 }
Q_GLOBAL_STATIC_WITH_ARGS()
Q_GLOBAL_STATIC_WITH_ARGS (QFactoryLoader , loader , (QFontEngineFactoryInterface_iid, QLatin1String("/fontengines"), Qt::CaseInsensitive)) const
qt_applyFontDatabaseSettings()
void qt_applyFontDatabaseSettings (const QSettings & settings)
Definition at line 524 of file qfontdatabase_qws.cpp.
 {
     initializeDb();
     QFontDatabasePrivate *db = privateDb();
     for (int i = 0; i < db->count; ++i) {
         QtFontFamily *family = db->families[i];
         if (settings.contains(family->name))
             family->fallbackFamilies = settings.value(family->name).toStringList();
     }
     if (settings.contains(QLatin1String("Global Fallbacks")))
         db->fallbackFamilies = settings.value(QLatin1String("Global Fallbacks")).toStringList();
 }
qt_qws_init_fontdb()
void qt_qws_init_fontdb ()
Definition at line 517 of file qfontdatabase_qws.cpp.
Referenced by QWSServerPrivate::initServer().
 {
     initializeDb();
 }
qws_fontCacheDir()
QString qws_fontCacheDir ()
Definition at line 231 of file qfontengine_qpf.cpp.
Referenced by QFontDatabasePrivate::addQPF2File(), QFontEngineQPF::cleanUpAfterClientCrash(), cleanupFontsDir(), initializeDb(), QFontDatabasePrivate::loadFromCache(), and QFontEngineQPF::QFontEngineQPF().
 {
     QString dir;
 #if defined(Q_WS_QWS)
     extern QString qws_dataDir();
     dir = qws_dataDir();
 #else
     dir = QDir::tempPath();
 #endif
     dir.append(QLatin1String("/fonts/"));
     QDir qd(dir);
     if (!qd.exists() && !qd.mkpath(dir))
         dir = QDir::tempPath();
     return dir;
 }
qwsFontPath()
static QString qwsFontPath () static
Warning
This function is not part of the public interface.
Definition at line 252 of file qfontdatabase_qws.cpp.
Referenced by initializeDb(), and loadSingleEngine().
 {
     QString fontpath = QString::fromLocal8Bit(qgetenv("QT_QWS_FONTDIR"));
     if (fontpath.isEmpty()) {
 #ifdef QT_FONTS_ARE_RESOURCES
         fontpath = QLatin1String(":/qt/fonts");
 #else
 #ifndef QT_NO_SETTINGS
         fontpath = QLibraryInfo::location(QLibraryInfo::LibrariesPath);
         fontpath += QLatin1String("/fonts");
 #else
         fontpath = QLatin1String("/lib/fonts");
 #endif
 #endif //QT_FONTS_ARE_RESOURCES
     }
     return fontpath;
 }
registerFont()
static void registerFont (QFontDatabasePrivate::ApplicationFont * fnt) static
Definition at line 722 of file qfontdatabase_qws.cpp.
Referenced by QFontDatabasePrivate::addQPF2File(), and initializeDb().
 {
     QFontDatabasePrivate *db = privateDb();
 #ifdef QT_NO_FREETYPE
     Q_UNUSED(fnt);
 #else
     fnt->families = db->addTTFile(QFile::encodeName(fnt->fileName), fnt->data);
     db->fallbackFamilies += fnt->families;
 #endif
     db->reregisterAppFonts = true;
 }