Qt 4.8: /src/plugins/platforms/fontdatabases/fontconfig/qfontconfigdatabase.cpp File Reference
qfontconfigdatabase.cpp File Reference
#include "qfontconfigdatabase.h"
#include <QtCore/QList>
#include <QtGui/private/qfont_p.h>
#include <QtCore/QElapsedTimer>
#include <QtGui/private/qapplication_p.h>
#include <QtGui/QPlatformScreen>
#include <QtGui/private/qfontengine_ft_p.h>
#include <QtGui/private/qfontengine_p.h>
#include <ft2build.h>
#include <FT_TRUETYPE_TABLES_H>
#include <fontconfig/fontconfig.h>
Macros
#define JapaneseCsbBit 17
#define KoreanCsbBit 21
#define SimplifiedChineseCsbBit 18
#define TraditionalChineseCsbBit 20
Enumerations
enum { SpecialLanguageCount = sizeof(specialLanguages) / sizeof(const char *) }
enum { SpecialCharCount = sizeof(specialChars) / sizeof(ushort) }
enum { LanguageCount = sizeof(languageForWritingSystem) / sizeof(const char *) }
enum { SampleCharCount = sizeof(sampleCharForWritingSystem) / sizeof(ushort) }
Functions
static const char * getFcFamilyForStyleHint (const QFont::StyleHint style)
static int getFCWeight (int fc_weight)
static bool requiresOpenType (int writingSystem)
static bool scriptRequiresOpenType (int script)
Variables
static const char * languageForWritingSystem []
static const char * openType []
static const ushort sampleCharForWritingSystem []
static const ushort specialChars []
static const char * specialLanguages []
Macro Definition Documentation
JapaneseCsbBit
#define JapaneseCsbBit 17
Definition at line 64 of file qfontconfigdatabase.cpp.
KoreanCsbBit
#define KoreanCsbBit 21
Definition at line 65 of file qfontconfigdatabase.cpp.
SimplifiedChineseCsbBit
#define SimplifiedChineseCsbBit 18
Definition at line 62 of file qfontconfigdatabase.cpp.
TraditionalChineseCsbBit
#define TraditionalChineseCsbBit 20
Definition at line 63 of file qfontconfigdatabase.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SpecialLanguageCount
Definition at line 123 of file qfontconfigdatabase.cpp.
 { SpecialLanguageCount = sizeof(specialLanguages) / sizeof(const char *) };
anonymous enum
anonymous enum
Enumerator
SpecialCharCount
Definition at line 155 of file qfontconfigdatabase.cpp.
 { SpecialCharCount = sizeof(specialChars) / sizeof(ushort) };
anonymous enum
anonymous enum
Enumerator
LanguageCount
Definition at line 195 of file qfontconfigdatabase.cpp.
 { LanguageCount = sizeof(languageForWritingSystem) / sizeof(const char *) };
anonymous enum
anonymous enum
Enumerator
SampleCharCount
Definition at line 235 of file qfontconfigdatabase.cpp.
 { SampleCharCount = sizeof(sampleCharForWritingSystem) / sizeof(ushort) };
Function Documentation
getFcFamilyForStyleHint()
static const char* getFcFamilyForStyleHint (const QFont::StyleHint style) static
Definition at line 277 of file qfontconfigdatabase.cpp.
Referenced by QFontconfigDatabase::fallbacksForFamily().
 {
     const char *stylehint = 0;
     switch (style) {
     case QFont::SansSerif:
         stylehint = "sans-serif";
         break;
     case QFont::Serif:
         stylehint = "serif";
         break;
     case QFont::TypeWriter:
         stylehint = "monospace";
         break;
     default:
         break;
     }
     return stylehint;
 }
getFCWeight()
static int getFCWeight (int fc_weight) static
Definition at line 78 of file qfontconfigdatabase.cpp.
Referenced by QFontconfigDatabase::populateFontDatabase().
 {
     int qtweight = QFont::Black;
     if (fc_weight <= (FC_WEIGHT_LIGHT + FC_WEIGHT_MEDIUM) / 2)
         qtweight = QFont::Light;
     else if (fc_weight <= (FC_WEIGHT_MEDIUM + FC_WEIGHT_DEMIBOLD) / 2)
         qtweight = QFont::Normal;
     else if (fc_weight <= (FC_WEIGHT_DEMIBOLD + FC_WEIGHT_BOLD) / 2)
         qtweight = QFont::DemiBold;
     else if (fc_weight <= (FC_WEIGHT_BOLD + FC_WEIGHT_BLACK) / 2)
         qtweight = QFont::Bold;
     return qtweight;
 }
requiresOpenType()
static bool requiresOpenType (int writingSystem) inline static
Definition at line 67 of file qfontconfigdatabase.cpp.
Referenced by QFontconfigDatabase::populateFontDatabase().
 {
     return ((writingSystem >= QFontDatabase::Syriac && writingSystem <= QFontDatabase::Sinhala)
             || writingSystem == QFontDatabase::Khmer || writingSystem == QFontDatabase::Nko);
 }
scriptRequiresOpenType()
static bool scriptRequiresOpenType (int script) inline static
Definition at line 72 of file qfontconfigdatabase.cpp.
Referenced by QFontconfigDatabase::fontEngine().
 {
     return ((script >= QUnicodeTables::Syriac && script <= QUnicodeTables::Sinhala)
             || script == QUnicodeTables::Khmer || script == QUnicodeTables::Nko);
 }
Variable Documentation
languageForWritingSystem
const char* languageForWritingSystem[] static
Definition at line 159 of file qfontconfigdatabase.cpp.
Referenced by QFontconfigDatabase::populateFontDatabase().
openType
const char* openType[] static
Definition at line 240 of file qfontconfigdatabase.cpp.
Referenced by QFontconfigDatabase::populateFontDatabase().
sampleCharForWritingSystem
const ushort sampleCharForWritingSystem[] static
Definition at line 199 of file qfontconfigdatabase.cpp.
Referenced by QFontconfigDatabase::populateFontDatabase().
specialChars
const ushort specialChars[] static
Initial value:
= {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0xc15,
    0xc95,
    0xd15,
    0xd9a,
    0,
    0,
    0,
    0x1000,
    0,
    0,
    0x1681,
    0x16a0,
    0,
    0x7ca
}
Definition at line 125 of file qfontconfigdatabase.cpp.
specialLanguages
const char* specialLanguages[] static
Initial value:
= {
    "en",
    "el",
    "ru",
    "hy",
    "he",
    "ar",
    "syr",
    "div",
    "hi",
    "bn",
    "pa",
    "gu",
    "or",
    "ta",
    "te",
    "kn",
    "ml",
    "si",
    "th",
    "lo",
    "bo",
    "my",
    "ka",
    "ko",
    "",
    "",
    "km",
    ""
}
Definition at line 93 of file qfontconfigdatabase.cpp.
Referenced by QFontconfigDatabase::fallbacksForFamily().