Qt 4.8: /src/gui/text/qfontmetrics.cpp File Reference
qfontmetrics.cpp File Reference
#include "qfont.h"
#include "qpaintdevice.h"
#include "qfontmetrics.h"
#include "qfont_p.h"
#include "qfontengine_p.h"
#include <private/qunicodetables_p.h>
#include <math.h>
#include "qx11info_x11.h"
Functions
void qt_format_text (const QFont &font, const QRectF &_r, int tf, const QString &text, QRectF *brect, int tabStops, int *tabArray, int tabArrayLen, QPainter *painter)
const QX11Info * qt_x11Info (const QPaintDevice *pd)
Function Documentation
qt_format_text()
void qt_format_text (const QFont & font, const QRectF & _r, int tf, const QString & text, QRectF * brect, int tabStops, int * tabArray, int tabArrayLen, QPainter * painter)
Definition at line 8448 of file qpainter.cpp.
Referenced by QFontMetrics::boundingRect(), and QFontMetricsF::boundingRect().
 {
     qt_format_text(fnt, _r,
                     tf, 0, str, brect,
                     tabstops, ta, tabarraylen,
                     painter);
 }
qt_x11Info()
const QX11Info* qt_x11Info (const QPaintDevice * pd) related
Referenced by QFontMetrics::QFontMetrics(), and QFontMetricsF::QFontMetricsF().