Qt 4.8: /src/gui/text/qfont_x11.cpp File Reference
qfont_x11.cpp File Reference
#include "qplatformdefs.h"
#include "qfont.h"
#include "qapplication.h"
#include "qfontinfo.h"
#include "qfontdatabase.h"
#include "qfontmetrics.h"
#include "qpaintdevice.h"
#include "qtextcodec.h"
#include "qiodevice.h"
#include "qhash.h"
#include <private/qunicodetables_p.h>
#include "qfont_p.h"
#include "qfontengine_p.h"
#include "qfontengine_x11_p.h"
#include "qtextengine_p.h"
#include <private/qt_x11_p.h>
#include "qx11info_x11.h"
#include <time.h>
#include <stdlib.h>
#include <ctype.h>
Macros
#define QFONTLOADER_DEBUG
#define QFONTLOADER_DEBUG_VERBOSE
#define QT_FATAL_ASSERT
Typedefs
typedef QHash< int, QString > FallBackHash
Functions
static bool fontExists (const QString &fontName)
QString qt_fallback_font_family (int script)
static QByteArray qt_fixXLFD (const QByteArray &xlfd)
double qt_pixelSize (double pointSize, int dpi)
double qt_pointSize (double pixelSize, int dpi)
Q_GUI_EXPORT void qt_x11_set_fallback_font_family (int script, const QString &family)
Variables
static const char *const tryFonts []
Macro Definition Documentation
QFONTLOADER_DEBUG
#define QFONTLOADER_DEBUG
Definition at line 69 of file qfont_x11.cpp.
QFONTLOADER_DEBUG_VERBOSE
#define QFONTLOADER_DEBUG_VERBOSE
Definition at line 70 of file qfont_x11.cpp.
QT_FATAL_ASSERT
#define QT_FATAL_ASSERT
Definition at line 42 of file qfont_x11.cpp.
Typedef Documentation
FallBackHash
typedef QHash<int, QString> FallBackHash
Definition at line 110 of file qfont_x11.cpp.
Function Documentation
fontExists()
static bool fontExists (const QString & fontName) static
Definition at line 339 of file qfont_x11.cpp.
 {
     int count;
     char **fontNames = XListFonts(QX11Info::display(), (char*)fontName.toLatin1().constData(), 32768, &count);
     if (fontNames) XFreeFontNames(fontNames);
     return count != 0;
 }
qt_fallback_font_family()
QString qt_fallback_font_family (int script)
Definition at line 114 of file qfont_x11.cpp.
Referenced by getFcPattern().
 {
     FallBackHash *hash = fallBackHash();
     return hash->value(script);
 }
qt_fixXLFD()
static QByteArray qt_fixXLFD (const QByteArray & xlfd) static
Definition at line 98 of file qfont_x11.cpp.
Referenced by qt_x11_set_fallback_font_family().
 {
     QByteArray ret = xlfd;
     int count = 0;
     char **fontNames =
         XListFonts(QX11Info::display(), xlfd, 32768, &count);
     if (count > 0)
         ret = fontNames[0];
     XFreeFontNames(fontNames);
     return ret ;
 }
qt_pixelSize()
double qt_pixelSize (double pointSize, int dpi)
Definition at line 74 of file qfont_x11.cpp.
Referenced by QFontDatabase::loadXlfd(), and qt_fillFontDef().
 {
     if (pointSize < 0)
         return -1.;
     if (dpi == 75) // the stupid 75 dpi setting on X11
         dpi = 72;
     return (pointSize * dpi) /72.;
 }
qt_pointSize()
double qt_pointSize (double pixelSize, int dpi)
Definition at line 83 of file qfont_x11.cpp.
Referenced by QFontDatabase::loadXlfd(), qt_FcPatternToQFontDef(), and qt_fillFontDef().
 {
     if (pixelSize < 0)
         return -1.;
     if (dpi == 75) // the stupid 75 dpi setting on X11
         dpi = 72;
     return pixelSize * 72. / ((double) dpi);
 }
qt_x11_set_fallback_font_family()
Q_GUI_EXPORT void qt_x11_set_fallback_font_family (int script, const QString & family)
Definition at line 121 of file qfont_x11.cpp.
 {
     FallBackHash *hash = fallBackHash();
     if (!family.isEmpty())
         hash->insert(script, family);
     else
         hash->remove(script);
 }
Variable Documentation
tryFonts
const char* const tryFonts[] static
Initial value:
= {
    "-*-helvetica-medium-r-*-*-*-120-*-*-*-*-*-*",
    "-*-courier-medium-r-*-*-*-120-*-*-*-*-*-*",
    "-*-times-medium-r-*-*-*-120-*-*-*-*-*-*",
    "-*-lucida-medium-r-*-*-*-120-*-*-*-*-*-*",
    "-*-helvetica-*-*-*-*-*-120-*-*-*-*-*-*",
    "-*-courier-*-*-*-*-*-120-*-*-*-*-*-*",
    "-*-times-*-*-*-*-*-120-*-*-*-*-*-*",
    "-*-lucida-*-*-*-*-*-120-*-*-*-*-*-*",
    "-*-helvetica-*-*-*-*-*-*-*-*-*-*-*-*",
    "-*-courier-*-*-*-*-*-*-*-*-*-*-*-*",
    "-*-times-*-*-*-*-*-*-*-*-*-*-*-*",
    "-*-lucida-*-*-*-*-*-*-*-*-*-*-*-*",
    "-*-fixed-*-*-*-*-*-*-*-*-*-*-*-*",
    "6x13",
    "7x13",
    "8x13",
    "9x15",
    "fixed",
    0
}
Definition at line 316 of file qfont_x11.cpp.
Referenced by fontExists().