Qt 4.8: /src/gui/text/qfontdatabase_qpa.cpp File Reference
qfontdatabase_qpa.cpp File Reference
#include "qlibraryinfo.h"
#include <QtCore/qsettings.h>
#include "qfontengine_qpa_p.h"
#include "qplatformdefs.h"
#include <QtGui/private/qapplication_p.h>
#include <QtGui/qplatformfontdatabase_qpa.h>
#include <QtCore/qmath.h>
Functions
static QStringList fallbackFamilies (const QString &family, const QFont::Style &style, const QFont::StyleHint &styleHint, const QUnicodeTables::Script &script)
static void initializeDb ()
static void load (const QString &=QString(), int=-1)
static QFontEngine * loadEngine (int script, const QFontDef &request, QtFontFamily *family, QtFontFoundry *foundry, QtFontStyle *style, QtFontSize *size)
static QFontEngine * loadSingleEngine (int script, const QFontDef &request, QtFontFoundry *foundry, QtFontStyle *style, QtFontSize *size)
void qt_applyFontDatabaseSettings (const QSettings &settings)
Q_GUI_EXPORT void qt_registerFont (const QString &familyName, const QString &foundryname, int weight, QFont::Style style, int stretch, bool antialiased, bool scalable, int pixelSize, const QSupportedWritingSystems &writingSystems, void *handle)
static void registerFont (QFontDatabasePrivate::ApplicationFont *fnt)
Function Documentation
fallbackFamilies()
static QStringList fallbackFamilies (const QString & family, const QFont::Style & style, const QFont::StyleHint & styleHint, const QUnicodeTables::Script & script) static
Definition at line 83 of file qfontdatabase_qpa.cpp.
Referenced by QFontconfigDatabase::fallbacksForFamily(), QFontDatabase::findFont(), and loadEngine().
 {
     QStringList retList = QApplicationPrivate::platformIntegration()->fontDatabase()->fallbacksForFamily(family,style,styleHint,script);
     QFontDatabasePrivate *db = privateDb();
     QStringList::iterator i;
     for (i = retList.begin(); i != retList.end(); ++i) {
         bool contains = false;
         for (int j = 0; j < db->count; j++) {
             QtFontFamily *qtFamily = db->families[j];
             if (!(i->compare(qtFamily->name,Qt::CaseInsensitive))) {
                 contains = true;
                 break;
             }
         }
         if (!contains) {
             i = retList.erase(i);
             i--;
         }
     }
     return retList;
 }
initializeDb()
static void initializeDb () static
Definition at line 108 of file qfontdatabase_qpa.cpp.
Referenced by QFontDatabase::findFont(), load(), and qt_applyFontDatabaseSettings().
 {
     QFontDatabasePrivate *db = privateDb();
     // init by asking for the platformfontdb for the first time or after invalidation
     if (!db->count)
         QApplicationPrivate::platformIntegration()->fontDatabase()->populateFontDatabase();
     if (db->reregisterAppFonts) {
         for (int i = 0; i < db->applicationFonts.count(); i++) {
             if (!db->applicationFonts.at(i).families.isEmpty())
                 registerFont(&db->applicationFonts[i]);
         }
         db->reregisterAppFonts = false;
     }
 }
load()
static void load (const QString & = QString(), int = -1) inline static
Definition at line 142 of file qfontdatabase_qpa.cpp.
 {
     // Only initialize the database if it has been cleared or not initialized yet
     if (!privateDb()->count)
         initializeDb();
 }
loadEngine()
static QFontEngine* loadEngine (int script, const QFontDef & request, QtFontFamily * family, QtFontFoundry * foundry, QtFontStyle * style, QtFontSize * size) static
Definition at line 179 of file qfontdatabase_qpa.cpp.
Referenced by QFontDatabase::findFont(), QCoreTextFontEngineMulti::macFontID(), QFontEngineMacMulti::macFontID(), and QFontEngineMulti::stringToCMap().
 {
     QFontEngine *engine = loadSingleEngine(script, request, foundry, style, size);
     //make sure that the db has all fallback families
     if (engine
         && !(request.styleStrategy & QFont::NoFontMerging) && !engine->symbol ) {
         if (family && !family->askedForFallback) {
             QFont::Style fontStyle = QFont::Style(style->key.style);
             QFont::StyleHint styleHint = QFont::StyleHint(request.styleHint);
             if (styleHint == QFont::AnyStyle && request.fixedPitch)
                 styleHint = QFont::TypeWriter;
             family->fallbackFamilies = fallbackFamilies(family->name,fontStyle,styleHint,QUnicodeTables::Script(script));
             family->askedForFallback = true;
         }
         QStringList fallbacks = privateDb()->fallbackFamilies;
         if (family && !family->fallbackFamilies.isEmpty())
             fallbacks = family->fallbackFamilies;
         engine = new QFontEngineMultiQPA(engine, script, fallbacks);
     }
     return engine;
 }
loadSingleEngine()
static QFontEngine* loadSingleEngine (int script, const QFontDef & request, QtFontFoundry * foundry, QtFontStyle * style, QtFontSize * size) static
Definition at line 150 of file qfontdatabase_qpa.cpp.
Referenced by loadEngine().
 {
     Q_UNUSED(foundry);
     Q_ASSERT(size);
     int pixelSize = size->pixelSize;
     if (!pixelSize || (style->smoothScalable && pixelSize == SMOOTH_SCALABLE))
         pixelSize = request.pixelSize;
     QFontDef def = request;
     def.pixelSize = pixelSize;
     QFontCache::Key key(def,script);
     QFontEngine *engine = QFontCache::instance()->findEngine(key);
     if (!engine) {
         QPlatformFontDatabase *pfdb = QApplicationPrivate::platformIntegration()->fontDatabase();
         engine = pfdb->fontEngine(def,QUnicodeTables::Script(script),size->handle);
         if (engine) {
             QFontCache::Key key(def,script);
             QFontCache::instance()->instance()->insertEngine(key,engine);
         }
     }
     return engine;
 }
qt_applyFontDatabaseSettings()
void qt_applyFontDatabaseSettings (const QSettings & settings)
Definition at line 127 of file qfontdatabase_qpa.cpp.
 {
     initializeDb();
     QFontDatabasePrivate *db = privateDb();
     for (int i = 0; i < db->count; ++i) {
         QtFontFamily *family = db->families[i];
         if (settings.contains(family->name))
             family->fallbackFamilies = settings.value(family->name).toStringList();
     }
     if (settings.contains(QLatin1String("Global Fallbacks")))
         db->fallbackFamilies = settings.value(QLatin1String("Global Fallbacks")).toStringList();
 }
qt_registerFont()
Q_GUI_EXPORT void qt_registerFont (const QString & familyName, const QString & foundryname, int weight, QFont::Style style, int stretch, bool antialiased, bool scalable, int pixelSize, const QSupportedWritingSystems & writingSystems, void * handle)
Definition at line 55 of file qfontdatabase_qpa.cpp.
Referenced by QPlatformFontDatabase::registerFont().
 {
     QFontDatabasePrivate *d = privateDb();
     //    qDebug() << "Adding font" << familyname << weight << italic << pixelSize << file << fileIndex << antialiased;
         QtFontStyle::Key styleKey;
         styleKey.style = style;
         styleKey.weight = weight;
         styleKey.stretch = stretch;
         QtFontFamily *f = d->family(familyName, true);
         for (int i = 0; i < QFontDatabase::WritingSystemsCount; ++i) {
             if (writingSystems.supported(QFontDatabase::WritingSystem(i))) {
                 f->writingSystems[i] = QtFontFamily::Supported;
             } else {
                 f->writingSystems[i] = QtFontFamily::Unsupported;
             }
         }
         QtFontFoundry *foundry = f->foundry(foundryname, true);
         QtFontStyle *fontStyle = foundry->style(styleKey, QString(), true);
         fontStyle->smoothScalable = scalable;
         fontStyle->antialiased = antialiased;
         QtFontSize *size = fontStyle->pixelSize(pixelSize?pixelSize:SMOOTH_SCALABLE, true);
         size->handle = handle;
 }
registerFont()
static void registerFont (QFontDatabasePrivate::ApplicationFont * fnt) static
Definition at line 209 of file qfontdatabase_qpa.cpp.
Referenced by fallbackFamilies(), and initializeDb().
 {
     QFontDatabasePrivate *db = privateDb();
     fnt->families = QApplicationPrivate::platformIntegration()->fontDatabase()->addApplicationFont(fnt->data,fnt->fileName);
     db->reregisterAppFonts = true;
 }