Qt 4.8: /src/gui/text/qfontdatabase_mac.cpp File Reference
qfontdatabase_mac.cpp File Reference
#include <private/qt_mac_p.h>
#include "qfontengine_p.h"
#include <qfile.h>
#include <qabstractfileengine.h>
#include <stdlib.h>
#include <qendian.h>
#include <private/qfontengine_coretext_p.h>
#include <private/qfontengine_mac_p.h>
Functions
static void initializeDb ()
static void initWritingSystems (QtFontFamily *family, ATSFontRef atsFont)
static void load (const QString &=QString(), int=-1)
static QFontEngine * loadFromDatabase (QFontDef &req, const QFontPrivate *d)
int qt_mac_pixelsize (const QFontDef &def, int dpi)
int qt_mac_pointsize (const QFontDef &def, int dpi)
static void registerFont (QFontDatabasePrivate::ApplicationFont *fnt)
static const char * styleHint (const QFontDef &request)
static float weightToFloat (unsigned int weight)
Function Documentation
initializeDb()
static void initializeDb () static
Definition at line 129 of file qfontdatabase_mac.cpp.
Referenced by QFontDatabase::createDatabase(), load(), and loadFromDatabase().
 {
     QFontDatabasePrivate *db = privateDb();
     if(!db || db->count)
         return;
 #if defined(QT_MAC_USE_COCOA) && MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5
 if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_5) {
     QCFType<CTFontCollectionRef> collection = CTFontCollectionCreateFromAvailableFonts(0);
     if(!collection)
         return;
     QCFType<CFArrayRef> fonts = CTFontCollectionCreateMatchingFontDescriptors(collection);
     if(!fonts)
         return;
     QString foundry_name = "CoreText";
     const int numFonts = CFArrayGetCount(fonts);
     for(int i = 0; i < numFonts; ++i) {
         CTFontDescriptorRef font = (CTFontDescriptorRef)CFArrayGetValueAtIndex(fonts, i);
         QCFString family_name = (CFStringRef)CTFontDescriptorCopyLocalizedAttribute(font, kCTFontFamilyNameAttribute, NULL);
         QCFString style_name = (CFStringRef)CTFontDescriptorCopyLocalizedAttribute(font, kCTFontStyleNameAttribute, NULL);
         QtFontFamily *family = db->family(family_name, true);
         if (QCFType<CFArrayRef> languages = (CFArrayRef) CTFontDescriptorCopyAttribute(font, kCTFontLanguagesAttribute)) {
             CFIndex length = CFArrayGetCount(languages);
             for (int i = 1; i < LanguageCount; ++i) {
                 if (!languageForWritingSystem[i])
                     continue;
                 QCFString lang = CFStringCreateWithCString(NULL, languageForWritingSystem[i], kCFStringEncodingASCII);
                 if (CFArrayContainsValue(languages, CFRangeMake(0, length), lang))
                     family->writingSystems[i] = QtFontFamily::Supported;
             }
         }
         QtFontFoundry *foundry = family->foundry(foundry_name, true);
         QtFontStyle::Key styleKey;
         QString styleName = style_name;
         if(QCFType<CFDictionaryRef> styles = (CFDictionaryRef)CTFontDescriptorCopyAttribute(font, kCTFontTraitsAttribute)) {
             if(CFNumberRef weight = (CFNumberRef)CFDictionaryGetValue(styles, kCTFontWeightTrait)) {
                 Q_ASSERT(CFNumberIsFloatType(weight));
                 double d;
                 if(CFNumberGetValue(weight, kCFNumberDoubleType, &d)) {
                     //qDebug() << "BOLD" << (QString)family_name << d;
                     styleKey.weight = (d > 0.0) ? QFont::Bold : QFont::Normal;
                 }
             }
             if(CFNumberRef italic = (CFNumberRef)CFDictionaryGetValue(styles, kCTFontSlantTrait)) {
                 Q_ASSERT(CFNumberIsFloatType(italic));
                 double d;
                 if(CFNumberGetValue(italic, kCFNumberDoubleType, &d)) {
                     //qDebug() << "ITALIC" << (QString)family_name << d;
                     if (d > 0.0)
                         styleKey.style = QFont::StyleItalic;
                 }
             }
         }
         QtFontStyle *style = foundry->style(styleKey, styleName, true);
         style->smoothScalable = true;
         if(QCFType<CFNumberRef> size = (CFNumberRef)CTFontDescriptorCopyAttribute(font, kCTFontSizeAttribute)) {
             //qDebug() << "WHEE";
             int pixel_size=0;
             if(CFNumberIsFloatType(size)) {
                 double d;
                 CFNumberGetValue(size, kCFNumberDoubleType, &d);
                 pixel_size = d;
             } else {
                 CFNumberGetValue(size, kCFNumberIntType, &pixel_size);
             }
             //qDebug() << "SIZE" << (QString)family_name << pixel_size;
             if(pixel_size)
                 style->pixelSize(pixel_size, true);
         } else {
             //qDebug() << "WTF?";
         }
     }
 } else
 #endif
     {
 #ifndef QT_MAC_USE_COCOA
         FMFontIterator it;
         if (!FMCreateFontIterator(0, 0, kFMUseGlobalScopeOption, &it)) {
             while (true) {
                 FMFont fmFont;
                 if (FMGetNextFont(&it, &fmFont) != noErr)
                     break;
                 FMFontFamily fmFamily;
                 FMFontStyle fmStyle;
                 QString familyName;
                 QtFontStyle::Key styleKey;
                 ATSFontRef atsFont = FMGetATSFontRefFromFont(fmFont);
                 if (!FMGetFontFamilyInstanceFromFont(fmFont, &fmFamily, &fmStyle)) {
                     { //sanity check the font, and see if we can use it at all! --Sam
                         ATSUFontID fontID;
                         if(ATSUFONDtoFontID(fmFamily, 0, &fontID) != noErr)
                             continue;
                     }
                     if (fmStyle & ::italic)
                         styleKey.style = QFont::StyleItalic;
                     if (fmStyle & ::bold)
                         styleKey.weight = QFont::Bold;
                     ATSFontFamilyRef familyRef = FMGetATSFontFamilyRefFromFontFamily(fmFamily);
                     QCFString cfFamilyName;;
                     ATSFontFamilyGetName(familyRef, kATSOptionFlagsDefault, &cfFamilyName);
                     familyName = cfFamilyName;
                 } else {
                     QCFString cfFontName;
                     ATSFontGetName(atsFont, kATSOptionFlagsDefault, &cfFontName);
                     familyName = cfFontName;
                     quint16 macStyle = 0;
                     {
                         uchar data[4];
                         ByteCount len = 4;
                         if (ATSFontGetTable(atsFont, MAKE_TAG('h', 'e', 'a', 'd'), 44, 4, &data, &len) == noErr)
                             macStyle = qFromBigEndian<quint16>(data);
                     }
                     if (macStyle & 1)
                         styleKey.weight = QFont::Bold;
                     if (macStyle & 2)
                         styleKey.style = QFont::StyleItalic;
                 }
                 QtFontFamily *family = db->family(familyName, true);
                 QtFontFoundry *foundry = family->foundry(QString(), true);
                 QtFontStyle *style = foundry->style(styleKey, QString(), true);
                 style->pixelSize(0, true);
                 style->smoothScalable = true;
                 initWritingSystems(family, atsFont);
             }
             FMDisposeFontIterator(&it);
         }
 #endif
     }
 }
initWritingSystems()
static void initWritingSystems (QtFontFamily * family, ATSFontRef atsFont) static
Definition at line 57 of file qfontdatabase_mac.cpp.
Referenced by initializeDb().
 {
     ByteCount length = 0;
     if (ATSFontGetTable(atsFont, MAKE_TAG('O', 'S', '/', '2'), 0, 0, 0, &length) != noErr)
         return;
     QVarLengthArray<uchar> os2Table(length);
     if (length < 86
         || ATSFontGetTable(atsFont, MAKE_TAG('O', 'S', '/', '2'), 0, length, os2Table.data(), &length) != noErr)
         return;
     // See also qfontdatabase_win.cpp, offsets taken from OS/2 table in the TrueType spec
     quint32 unicodeRange[4] = {
         qFromBigEndian<quint32>(os2Table.data() + 42),
         qFromBigEndian<quint32>(os2Table.data() + 46),
         qFromBigEndian<quint32>(os2Table.data() + 50),
         qFromBigEndian<quint32>(os2Table.data() + 54)
     };
     quint32 codePageRange[2] = { qFromBigEndian<quint32>(os2Table.data() + 78), qFromBigEndian<quint32>(os2Table.data() + 82) };
     QList<QFontDatabase::WritingSystem> systems = qt_determine_writing_systems_from_truetype_bits(unicodeRange, codePageRange);
 #if 0
     QCFString name;
     ATSFontGetName(atsFont, kATSOptionFlagsDefault, &name);
     qDebug() << systems.count() << "writing systems for" << QString(name);
 qDebug() << "first char" << hex << unicodeRange[0];
     for (int i = 0; i < systems.count(); ++i)
         qDebug() << QFontDatabase::writingSystemName(systems.at(i));
 #endif
     for (int i = 0; i < systems.count(); ++i)
         family->writingSystems[systems.at(i)] = QtFontFamily::Supported;
 }
load()
static void load (const QString & = QString(), int = -1) inline static
Definition at line 272 of file qfontdatabase_mac.cpp.
 {
     initializeDb();
 }
loadFromDatabase()
static QFontEngine* loadFromDatabase (QFontDef & req, const QFontPrivate * d) static
Definition at line 303 of file qfontdatabase_mac.cpp.
Referenced by QFontDatabase::load().
 {
 #if defined(QT_MAC_USE_COCOA)
     QCFString fontName = NULL;
 #else
     ATSFontFamilyRef familyRef = 0;
     ATSFontRef fontRef = 0;
 #endif
     QStringList family_list = familyList(req);
     const char *stylehint = styleHint(req);
     if (stylehint)
         family_list << QLatin1String(stylehint);
     // add QFont::defaultFamily() to the list, for compatibility with previous versions
     family_list << QApplication::font().defaultFamily();
     QMutexLocker locker(fontDatabaseMutex());
     QFontDatabasePrivate *db = privateDb();
     if (!db->count)
         initializeDb();
     for (int i = 0; i < family_list.size(); ++i) {
         for (int k = 0; k < db->count; ++k) {
             if (db->families[k]->name.compare(family_list.at(i), Qt::CaseInsensitive) == 0) {
 #if defined(QT_MAC_USE_COCOA)
                 CFStringRef familyName = QCFString::toCFStringRef(db->families[k]->name);
                 QCFType<CTFontDescriptorRef> descriptor = CTFontDescriptorCreateWithAttributes(
                                     QCFType<CFDictionaryRef>(CFDictionaryCreate(kCFAllocatorDefault,
                                         (const void**)&kCTFontFamilyNameAttribute,
                                         (const void**)&familyName, 1,
                                         &kCFTypeDictionaryKeyCallBacks, &kCFTypeDictionaryValueCallBacks)));
                 CFRelease(familyName);
                 QCFType<CTFontRef> ctFont = CTFontCreateWithFontDescriptor(descriptor, 0, NULL);
                 if (ctFont) {
                     fontName = CTFontCopyFullName(ctFont);
                     goto found;
                 }
 #else
                 familyRef = ATSFontFamilyFindFromName(QCFString(db->families[k]->name), kATSOptionFlagsDefault);
                 if (familyRef) {
                     fontRef = ATSFontFindFromName(QCFString(db->families[k]->name), kATSOptionFlagsDefault);
                     goto found;
                 }
 #endif
             }
         }
     }
 found:
 #ifdef QT_MAC_USE_COCOA
     if (fontName)
         return new QCoreTextFontEngineMulti(fontName, req, d->kerning);
 #else
     if (familyRef) {
         QCFString actualName;
         if (ATSFontFamilyGetName(familyRef, kATSOptionFlagsDefault, &actualName) == noErr)
             req.family = actualName;
         return new QFontEngineMacMulti(familyRef, fontRef, req, d->kerning);
     }
 #endif
     return NULL;
 }
qt_mac_pixelsize()
int qt_mac_pixelsize (const QFontDef & def, int dpi)
Definition at line 64 of file qfont_mac.cpp.
Referenced by QFontDatabase::load().
 {
     float ret;
     if(def.pixelSize == -1)
         ret = def.pointSize *  dpi / qt_mac_defaultDpi_x();
     else
         ret = def.pixelSize;
     return qRound(ret);
 }
qt_mac_pointsize()
int qt_mac_pointsize (const QFontDef & def, int dpi)
Definition at line 73 of file qfont_mac.cpp.
Referenced by QFontDatabase::load().
 {
     float ret;
     if(def.pointSize < 0)
         ret = def.pixelSize * qt_mac_defaultDpi_x() / float(dpi);
     else
         ret = def.pointSize;
     return qRound(ret);
 }
registerFont()
static void registerFont (QFontDatabasePrivate::ApplicationFont * fnt) static
Definition at line 440 of file qfontdatabase_mac.cpp.
Referenced by QFontDatabasePrivate::addAppFont().
 {
     ATSFontContainerRef handle;
     OSStatus e  = noErr;
     if(fnt->data.isEmpty()) {
 #if (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
         if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_5) {
                 FSRef ref;
                 if(qt_mac_create_fsref(fnt->fileName, &ref) != noErr)
                     return;
                 ATSFontActivateFromFileReference(&ref, kATSFontContextLocal, kATSFontFormatUnspecified, 0, kATSOptionFlagsDefault, &handle);
         } else
 #endif
         {
 #ifndef Q_WS_MAC64
                 FSSpec spec;
                 if(qt_mac_create_fsspec(fnt->fileName, &spec) != noErr)
                     return;
                 e = ATSFontActivateFromFileSpecification(&spec, kATSFontContextLocal, kATSFontFormatUnspecified,
                                                    0, kATSOptionFlagsDefault, &handle);
 #endif
         }
     } else {
         e = ATSFontActivateFromMemory((void *)fnt->data.constData(), fnt->data.size(), kATSFontContextLocal,
                                            kATSFontFormatUnspecified, 0, kATSOptionFlagsDefault, &handle);
         fnt->data = QByteArray();
     }
     if(e != noErr)
         return;
     ItemCount fontCount = 0;
     e = ATSFontFindFromContainer(handle, kATSOptionFlagsDefault, 0, 0, &fontCount);
     if(e != noErr)
         return;
     QVarLengthArray<ATSFontRef> containedFonts(fontCount);
     e = ATSFontFindFromContainer(handle, kATSOptionFlagsDefault, fontCount, containedFonts.data(), &fontCount);
     if(e != noErr)
         return;
     fnt->families.clear();
 #if defined(QT_MAC_USE_COCOA)
     // Make sure that the family name set on the font matches what
     // kCTFontFamilyNameAttribute returns in initializeDb().
     // So far the best solution seems find the installed font
     // using CoreText and get the family name from it.
     // (ATSFontFamilyGetName appears to be the correct API, but also
     // returns the font display name.)
     for(int i = 0; i < containedFonts.size(); ++i) {
         QCFString fontPostScriptName;
         ATSFontGetPostScriptName(containedFonts[i], kATSOptionFlagsDefault, &fontPostScriptName);
         QCFType<CTFontDescriptorRef> font = CTFontDescriptorCreateWithNameAndSize(fontPostScriptName, 14);
         QCFString familyName = (CFStringRef)CTFontDescriptorCopyAttribute(font, kCTFontFamilyNameAttribute);
         fnt->families.append(familyName);
     }
 #else
     for(int i = 0; i < containedFonts.size(); ++i) {
         QCFString family;
         ATSFontGetName(containedFonts[i], kATSOptionFlagsDefault, &family);
         fnt->families.append(family);
     }
 #endif
     fnt->handle = handle;
 }
styleHint()
static const char* styleHint (const QFontDef & request) static
Definition at line 277 of file qfontdatabase_mac.cpp.
Referenced by loadFromDatabase().
 {
     const char *stylehint = 0;
     switch (request.styleHint) {
     case QFont::SansSerif:
         stylehint = "Arial";
         break;
     case QFont::Serif:
         stylehint = "Times New Roman";
         break;
     case QFont::TypeWriter:
         stylehint = "Courier New";
         break;
     default:
         if (request.fixedPitch)
             stylehint = "Courier New";
         break;
     }
     return stylehint;
 }
weightToFloat()
static float weightToFloat (unsigned int weight) inline static
Definition at line 298 of file qfontdatabase_mac.cpp.
 {
     return (weight - 50) / 100.0;
 }