Qt 4.8: /src/gui/kernel/qformlayout.cpp File Reference
qformlayout.cpp File Reference
#include "qapplication.h"
#include "qdebug.h"
#include "qformlayout.h"
#include "qlabel.h"
#include "qlayout_p.h"
#include "qlayoutengine_p.h"
#include "qrect.h"
#include "qvector.h"
#include "qwidget.h"
Classes
struct QFormLayoutItem
class QFormLayoutPrivate
Enumerations
enum { ColumnCount = 2 }
Functions
static Qt::Alignment fixedAlignment (Qt::Alignment alignment, Qt::LayoutDirection layoutDirection)
static void initLayoutStruct (QLayoutStruct &sl, QFormLayoutItem *item)
static int spacingHelper (QWidget *parent, QStyle *style, int userVSpacing, bool recalculate, QFormLayoutItem *item1, QFormLayoutItem *item2, QFormLayoutItem *prevItem1, QFormLayoutItem *prevItem2)
static int storageIndexFromLayoutItem (const QFormLayoutPrivate::ItemMatrix &m, QFormLayoutItem *item)
static void updateFormLayoutItem (QFormLayoutItem *item, int userVSpacing, QFormLayout::FieldGrowthPolicy fieldGrowthPolicy, bool fullRow)
Variables
const uint DefaultFieldGrowthPolicy = 255
const uint DefaultRowWrapPolicy = 255
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ColumnCount
Definition at line 130 of file qformlayout.cpp.
 { ColumnCount = 2 };
Function Documentation
fixedAlignment()
static Qt::Alignment fixedAlignment (Qt::Alignment alignment, Qt::LayoutDirection layoutDirection) static
Definition at line 260 of file qformlayout.cpp.
Referenced by QFormLayoutPrivate::arrangeWidgets().
 {
     if (layoutDirection == Qt::RightToLeft && alignment & Qt::AlignAbsolute) {
         // swap left and right, and eliminate absolute flag
         return Qt::Alignment((alignment & ~(Qt::AlignLeft | Qt::AlignRight | Qt::AlignAbsolute))
                              | ((alignment & Qt::AlignRight) ? Qt::AlignLeft : 0)
                              | ((alignment & Qt::AlignLeft) ? Qt::AlignRight : 0));
     } else {
         return alignment & ~Qt::AlignAbsolute;
     }
 }
initLayoutStruct()
static void initLayoutStruct (QLayoutStruct & sl, QFormLayoutItem * item) inline static
Definition at line 646 of file qformlayout.cpp.
Referenced by QFormLayoutPrivate::setupVerticalLayoutData().
 {
     sl.init(item->vStretch(), item->minSize.height());
     sl.sizeHint = item->sizeHint.height();
     sl.maximumSize = item->maxSize.height();
     sl.expansive = (item->expandingDirections() & Qt::Vertical);
     sl.empty = false;
 }
spacingHelper()
static int spacingHelper (QWidget * parent, QStyle * style, int userVSpacing, bool recalculate, QFormLayoutItem * item1, QFormLayoutItem * item2, QFormLayoutItem * prevItem1, QFormLayoutItem * prevItem2) inline static
Definition at line 605 of file qformlayout.cpp.
Referenced by QFormLayoutPrivate::setupVerticalLayoutData().
 {
     int spacing = userVSpacing;
     if (spacing < 0) {
         if (!recalculate) {
             if (item1)
                 spacing = item1->vSpace;
             if (item2)
                 spacing = qMax(spacing, item2->vSpace);
         } else {
             if (style && prevItem1) {
                 QSizePolicy::ControlTypes itemtypes =
                     QSizePolicy::ControlTypes(item1 ? item1->controlTypes() : QSizePolicy::DefaultType);
                 int spacing2 = 0;
                 spacing = style->combinedLayoutSpacing(itemtypes, prevItem1->controlTypes(), Qt::Vertical, 0, parent);
                 // At most of one of item2 and prevItem2 will be nonnull
                 if (item2)
                     spacing2 = style->combinedLayoutSpacing(item2->controlTypes(), prevItem1->controlTypes(), Qt::Vertical, 0, parent);
                 else if (prevItem2)
                     spacing2 = style->combinedLayoutSpacing(itemtypes, prevItem2->controlTypes(), Qt::Vertical, 0, parent);
                 spacing = qMax(spacing, spacing2);
             }
         }
     } else {
         if (prevItem1) {
             QWidget *wid = prevItem1->item->widget();
             if (wid)
                 spacing = qMax(spacing, prevItem1->geometry().top() - wid->geometry().top() );
         }
         if (prevItem2) {
             QWidget *wid = prevItem2->item->widget();
             if (wid)
                 spacing = qMax(spacing, prevItem2->geometry().top() - wid->geometry().top() );
         }
     }
     return spacing;
 }
storageIndexFromLayoutItem()
static int storageIndexFromLayoutItem (const QFormLayoutPrivate::ItemMatrix & m, QFormLayoutItem * item) static
Definition at line 272 of file qformlayout.cpp.
Referenced by QFormLayout::getItemPosition(), and QFormLayout::takeAt().
 {
     if (item) {
         return m.storage().indexOf(item);
     } else {
         return -1;
     }
 }
updateFormLayoutItem()
static void updateFormLayoutItem (QFormLayoutItem * item, int userVSpacing, QFormLayout::FieldGrowthPolicy fieldGrowthPolicy, bool fullRow) static
Definition at line 282 of file qformlayout.cpp.
Referenced by QFormLayoutPrivate::updateSizes().
 {
     item->minSize = item->item->minimumSize();
     item->sizeHint = item->item->sizeHint();
     item->maxSize = item->item->maximumSize();
     if (!fullRow && (fieldGrowthPolicy == QFormLayout::FieldsStayAtSizeHint
                      || (fieldGrowthPolicy == QFormLayout::ExpandingFieldsGrow
                          && !(item->item->expandingDirections() & Qt::Horizontal))))
         item->maxSize.setWidth(item->sizeHint.width());
     item->isHfw = item->item->hasHeightForWidth();
     item->vSpace = userVSpacing;
 }
Variable Documentation
DefaultFieldGrowthPolicy
const uint DefaultFieldGrowthPolicy = 255
Definition at line 127 of file qformlayout.cpp.
Referenced by QFormLayout::resetFieldGrowthPolicy().
DefaultRowWrapPolicy
const uint DefaultRowWrapPolicy = 255
Definition at line 128 of file qformlayout.cpp.
Referenced by QFormLayout::resetRowWrapPolicy().