Qt 4.8: /src/corelib/io/qfsfileengine_unix.cpp File Reference
qfsfileengine_unix.cpp File Reference
#include "qplatformdefs.h"
#include "qabstractfileengine.h"
#include "private/qfsfileengine_p.h"
#include "private/qcore_unix_p.h"
#include "qfilesystementry_p.h"
#include "qfilesystemengine_p.h"
#include "qfile.h"
#include "qdir.h"
#include "qdatetime.h"
#include "qvarlengtharray.h"
#include <sys/mman.h>
#include <stdlib.h>
#include <limits.h>
#include <errno.h>
#include <private/qcore_mac_p.h>
Functions
static QByteArray openModeToFopenMode (QIODevice::OpenMode flags, const QFileSystemEntry &fileEntry, QFileSystemMetaData &metaData)
Returns the stdlib open string corresponding to a QIODevice::OpenMode.
static int openModeToOpenFlags (QIODevice::OpenMode mode)
Returns the stdio open flags corresponding to a QIODevice::OpenMode.
static bool setCloseOnExec (int fd)
Sets the file descriptor to close on exec.
Function Documentation
openModeToFopenMode()
static QByteArray openModeToFopenMode (QIODevice::OpenMode flags, const QFileSystemEntry & fileEntry, QFileSystemMetaData & metaData) inline static
Returns the stdlib open string corresponding to a QIODevice::OpenMode.
Warning
This function is not part of the public interface.
Definition at line 97 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::nativeOpen().
 {
     QByteArray mode;
     if ((flags & QIODevice::ReadOnly) && !(flags & QIODevice::Truncate)) {
         mode = "rb";
         if (flags & QIODevice::WriteOnly) {
             metaData.clearFlags(QFileSystemMetaData::FileType);
             if (!fileEntry.isEmpty()
                     && QFileSystemEngine::fillMetaData(fileEntry, metaData, QFileSystemMetaData::FileType)
                     && metaData.isFile()) {
                 mode += '+';
             } else {
                 mode = "wb+";
             }
         }
     } else if (flags & QIODevice::WriteOnly) {
         mode = "wb";
         if (flags & QIODevice::ReadOnly)
             mode += '+';
     }
     if (flags & QIODevice::Append) {
         mode = "ab";
         if (flags & QIODevice::ReadOnly)
             mode += '+';
     }
 #if defined(__GLIBC__) && (__GLIBC__ * 0x100 + __GLIBC_MINOR__) >= 0x0207
     // must be glibc >= 2.7
     mode += 'e';
 #endif
     return mode;
 }
openModeToOpenFlags()
static int openModeToOpenFlags (QIODevice::OpenMode mode) inline static
Returns the stdio open flags corresponding to a QIODevice::OpenMode.
Warning
This function is not part of the public interface.
Definition at line 141 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::nativeHandle(), and QFSFileEnginePrivate::nativeOpen().
 {
     int oflags = QT_OPEN_RDONLY;
 #ifdef QT_LARGEFILE_SUPPORT
     oflags |= QT_OPEN_LARGEFILE;
 #endif
     if ((mode & QFile::ReadWrite) == QFile::ReadWrite) {
         oflags = QT_OPEN_RDWR | QT_OPEN_CREAT;
     } else if (mode & QFile::WriteOnly) {
         oflags = QT_OPEN_WRONLY | QT_OPEN_CREAT;
     }
     if (mode & QFile::Append) {
         oflags |= QT_OPEN_APPEND;
     } else if (mode & QFile::WriteOnly) {
         if ((mode & QFile::Truncate) || !(mode & QFile::ReadOnly))
             oflags |= QT_OPEN_TRUNC;
     }
     return oflags;
 }
setCloseOnExec()
static bool setCloseOnExec (int fd) inline static
Sets the file descriptor to close on exec.
Warning
This function is not part of the public interface.
That is, the file descriptor is not inherited by child processes.
Definition at line 174 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::nativeOpen().
 {
     return fd != -1 && fcntl(fd, F_SETFD, FD_CLOEXEC) != -1;
 }