Qt 4.8: /src/network/access/qftp.cpp File Reference
qftp.cpp File Reference
#include "qftp.h"
#include "qabstractsocket.h"
#include "qcoreapplication.h"
#include "qtcpsocket.h"
#include "qurlinfo.h"
#include "qstringlist.h"
#include "qregexp.h"
#include "qtimer.h"
#include "qfileinfo.h"
#include "qhash.h"
#include "qtcpserver.h"
#include "qlocale.h"
#include <private/qobject_p.h>
#include "qftp.moc"
#include "moc_qftp.cpp"
Classes
class QFtpCommand
class QFtpDTP
class QFtpPI
class QFtpPrivate
Functions
static void _q_fixupDateTime (QDateTime *dateTime, bool leapYear=false)
static void _q_parseDosDir (const QStringList &tokens, const QString &userName, QUrlInfo *info)
static void _q_parseUnixDir (const QStringList &tokens, const QString &userName, QUrlInfo *info)
Function Documentation
_q_fixupDateTime()
static void _q_fixupDateTime (QDateTime * dateTime, bool leapYear = false) static
Definition at line 469 of file qftp.cpp.
Referenced by _q_parseUnixDir().
 {
     // Adjust for future tolerance.
     const int futureTolerance = 86400;
     if (dateTime->secsTo(QDateTime::currentDateTime()) < -futureTolerance) {
         QDate d = dateTime->date();
         if (leapYear) {
             int prevLeapYear = d.year() - 1;
             while (!QDate::isLeapYear(prevLeapYear))
                prevLeapYear--;
             d.setYMD(prevLeapYear, d.month(), d.day());
         } else {
             d.setYMD(d.year() - 1, d.month(), d.day());
         }
         dateTime->setDate(d);
     }
 }
_q_parseDosDir()
static void _q_parseDosDir (const QStringList & tokens, const QString & userName, QUrlInfo * info) static
Definition at line 598 of file qftp.cpp.
Referenced by QFtpDTP::parseDir().
 {
     // DOS style, 3 + 1 entries
     // 01-16-02  11:14AM       <DIR>          epsgroup
     // 06-05-03  03:19PM                 1973 readme.txt
     if (tokens.size() != 4)
         return;
     Q_UNUSED(userName);
     QString name = tokens.at(3);
     info->setName(name);
     info->setSymLink(name.toLower().endsWith(QLatin1String(".lnk")));
     if (tokens.at(2) == QLatin1String("<DIR>")) {
         info->setFile(false);
         info->setDir(true);
     } else {
         info->setFile(true);
         info->setDir(false);
         info->setSize(tokens.at(2).toLongLong());
     }
     // Note: We cannot use QFileInfo; permissions are for the server-side
     // machine, and QFileInfo's behavior depends on the local platform.
     int permissions = QUrlInfo::ReadOwner | QUrlInfo::WriteOwner
                       | QUrlInfo::ReadGroup | QUrlInfo::WriteGroup
                       | QUrlInfo::ReadOther | QUrlInfo::WriteOther;
     QString ext;
     int extIndex = name.lastIndexOf(QLatin1Char('.'));
     if (extIndex != -1)
         ext = name.mid(extIndex + 1);
     if (ext == QLatin1String("exe") || ext == QLatin1String("bat") || ext == QLatin1String("com"))
         permissions |= QUrlInfo::ExeOwner | QUrlInfo::ExeGroup | QUrlInfo::ExeOther;
     info->setPermissions(permissions);
     info->setReadable(true);
     info->setWritable(info->isFile());
     QDateTime dateTime;
 #ifndef QT_NO_DATESTRING
     dateTime = QLocale::c().toDateTime(tokens.at(1), QLatin1String("MM-dd-yy  hh:mmAP"));
     if (dateTime.date().year() < 1971) {
         dateTime.setDate(QDate(dateTime.date().year() + 100,
                                dateTime.date().month(),
                                dateTime.date().day()));
     }
 #endif
     info->setLastModified(dateTime);
 }
_q_parseUnixDir()
static void _q_parseUnixDir (const QStringList & tokens, const QString & userName, QUrlInfo * info) static
Definition at line 489 of file qftp.cpp.
Referenced by QFtpDTP::parseDir().
 {
     // Unix style, 7 + 1 entries
     // -rw-r--r--    1 ftp      ftp      17358091 Aug 10  2004 qt-x11-free-3.3.3.tar.gz
     // drwxr-xr-x    3 ftp      ftp          4096 Apr 14  2000 compiled-examples
     // lrwxrwxrwx    1 ftp      ftp             9 Oct 29  2005 qtscape -> qtmozilla
     if (tokens.size() != 8)
         return;
     char first = tokens.at(1).at(0).toLatin1();
     if (first == 'd') {
         info->setDir(true);
         info->setFile(false);
         info->setSymLink(false);
     } else if (first == '-') {
         info->setDir(false);
         info->setFile(true);
         info->setSymLink(false);
     } else if (first == 'l') {
         info->setDir(true);
         info->setFile(false);
         info->setSymLink(true);
     }
     // Resolve filename
     QString name = tokens.at(7);
     if (info->isSymLink()) {
         int linkPos = name.indexOf(QLatin1String(" ->"));
         if (linkPos != -1)
             name.resize(linkPos);
     }
     info->setName(name);
     // Resolve owner & group
     info->setOwner(tokens.at(3));
     info->setGroup(tokens.at(4));
     // Resolve size
     info->setSize(tokens.at(5).toLongLong());
     QStringList formats;
     formats << QLatin1String("MMM dd  yyyy") << QLatin1String("MMM dd hh:mm") << QLatin1String("MMM  d  yyyy")
             << QLatin1String("MMM  d hh:mm") << QLatin1String("MMM  d yyyy") << QLatin1String("MMM dd yyyy");
     QString dateString = tokens.at(6);
     dateString[0] = dateString[0].toUpper();
     // Resolve the modification date by parsing all possible formats
     QDateTime dateTime;
     int n = 0;
 #ifndef QT_NO_DATESTRING
     do {
         dateTime = QLocale::c().toDateTime(dateString, formats.at(n++));
     }  while (n < formats.size() && (!dateTime.isValid()));
 #endif
     if (n == 2 || n == 4) {
         // Guess the year.
         dateTime.setDate(QDate(QDate::currentDate().year(),
                                dateTime.date().month(),
                                dateTime.date().day()));
         _q_fixupDateTime(&dateTime);
     }
     if (dateTime.isValid())
         info->setLastModified(dateTime);
     else if (dateString.startsWith(QLatin1String("Feb 29"))) {
        // When the current year on the FTP server is a leap year and a
        // file's last modified date is Feb 29th, and the current day on
        // the FTP server is also Feb 29th, then the date can be in
        // formats n==2 or n==4. toDateTime in that case defaults to 1900
        // for the missing year. Feb 29 1900 is an invalid date and so
        // wont be parsed. This adds an exception that handles it.
        int recentLeapYear;
        QString timeString = dateString.mid(7);
        dateTime = QLocale::c().toDateTime(timeString, QLatin1String("hh:mm"));
        recentLeapYear = QDate::currentDate().year();
        while (!QDate::isLeapYear(recentLeapYear))
            recentLeapYear--;
        dateTime.setDate(QDate(recentLeapYear, 2, 29));
        _q_fixupDateTime(&dateTime, true);
        info->setLastModified(dateTime);
     }
     // Resolve permissions
     int permissions = 0;
     QString p = tokens.at(2);
     permissions |= (p[0] == QLatin1Char('r') ? QUrlInfo::ReadOwner : 0);
     permissions |= (p[1] == QLatin1Char('w') ? QUrlInfo::WriteOwner : 0);
     permissions |= (p[2] == QLatin1Char('x') ? QUrlInfo::ExeOwner : 0);
     permissions |= (p[3] == QLatin1Char('r') ? QUrlInfo::ReadGroup : 0);
     permissions |= (p[4] == QLatin1Char('w') ? QUrlInfo::WriteGroup : 0);
     permissions |= (p[5] == QLatin1Char('x') ? QUrlInfo::ExeGroup : 0);
     permissions |= (p[6] == QLatin1Char('r') ? QUrlInfo::ReadOther : 0);
     permissions |= (p[7] == QLatin1Char('w') ? QUrlInfo::WriteOther : 0);
     permissions |= (p[8] == QLatin1Char('x') ? QUrlInfo::ExeOther : 0);
     info->setPermissions(permissions);
     bool isOwner = info->owner() == userName;
     info->setReadable((permissions & QUrlInfo::ReadOther) || ((permissions & QUrlInfo::ReadOwner) && isOwner));
     info->setWritable((permissions & QUrlInfo::WriteOther) || ((permissions & QUrlInfo::WriteOwner) && isOwner));
 }