Qt 4.8: /src/corelib/kernel/qfunctions_nacl.cpp File Reference
qfunctions_nacl.cpp File Reference
#include "qfunctions_nacl.h"
#include <pthread.h>
#include <qglobal.h>
Typedefs
typedef long off64_t
Functions
int access (const char *, int)
int fcntl (int, int,...)
off64_t ftello64 (void *)
off64_t lseek64 (int, off_t, int)
int open (const char *, int,...)
int open64 (const char *, int,...)
int pthread_attr_getinheritsched (const pthread_attr_t *, int *)
int pthread_attr_setinheritsched (pthread_attr_t *, int)
int pthread_cancel (pthread_t)
void pthread_cleanup_pop (int)
void pthread_cleanup_push (void(*)(void *), void *)
int pthread_setcancelstate (int, int *)
int pthread_setcanceltype (int, int *)
void pthread_testcancel (void)
int select (int, fd_set *, fd_set *, fd_set *, struct timeval *)
int sigaction (int, const struct sigaction *, struct sigaction *)
Typedef Documentation
off64_t
typedef long off64_t
Definition at line 138 of file qfunctions_nacl.cpp.
Function Documentation
access()
int access (const char * , int)
Definition at line 133 of file qfunctions_nacl.cpp.
Referenced by QGLBuffer::allocate(), QLinuxFbScreen::connect(), QLinuxFbIntegration::connect(), generateInterfaceXml(), QDBusXmlParser::interfaces(), QFSFileEnginePrivate::longFileName(), QFSFileEnginePrivate::map(), QFontEngineQPF::QFontEngineQPF(), and QMetaMethodBuilder::QMetaMethodBuilder().
 {
     return 0;
 }
fcntl()
int fcntl (int , int , ...)
Definition at line 113 of file qfunctions_nacl.cpp.
Referenced by QKqueueFileSystemWatcherEngine::addPaths(), QDnotifyFileSystemWatcherEngine::addPaths(), QInotifyFileSystemWatcherEngine::create(), QWSSoundServerPrivate::feedDevice(), QFontEngineQPF::lockFile(), QFSFileEnginePrivate::nativeRead(), QWSSoundServerPrivate::openDevice(), PvrEglScreen::openTty(), QProcessPrivate::processStarted(), QDirectFBKeyboardHandlerPrivate::QDirectFBKeyboardHandlerPrivate(), QDirectFBMouseHandlerPrivate::QDirectFBMouseHandlerPrivate(), QInotifyFileSystemWatcherEngine::QInotifyFileSystemWatcherEngine(), QKqueueFileSystemWatcherEngine::QKqueueFileSystemWatcherEngine(), qt_safe_accept(), qt_safe_dup(), qt_safe_dup2(), qt_safe_open(), qt_safe_pipe(), qt_safe_socket(), setCloseOnExec(), QNativeSocketEnginePrivate::setOption(), signalHandler(), QProcessPrivate::startProcess(), and QFontEngineQPF::unlockFile().
 {
     return 0;
 }
ftello64()
off64_t ftello64 (void *)
Definition at line 139 of file qfunctions_nacl.cpp.
 {
     qFatal("ftello64 called");
     return 0;
 }
lseek64()
off64_t lseek64 (int , off_t , int)
Definition at line 145 of file qfunctions_nacl.cpp.
 {
     qFatal("lseek64 called");
     return 0;
 }
open()
int open (const char * , int , ...)
Definition at line 123 of file qfunctions_nacl.cpp.
Referenced by QBBVirtualKeyboardPps::connect(), QMacPasteboardMimeVCard::convertFromMime(), create32BitCursor(), QSqlDatabasePrivate::database(), QCommonStyle::drawPrimitive(), loadSingleEngine(), QtMultimediaInternal::MacInputDevice::MacInputDevice(), MacOutputDevice::MacOutputDevice(), Qt::mightBeRichText(), QIBaseDriver::open(), QSQLite2Driver::open(), QFileOpenEvent::openFile(), QPdfBaseEnginePrivate::openPrintDevice(), PvrEglScreen::openTty(), pvrQwsInitFbScreen(), QCursor::QCursor(), QDBusMarshaller::QDBusMarshaller(), QEventDispatcherUNIXPrivate::QEventDispatcherUNIXPrivate(), QTextBrowser::setOpenExternalLinks(), QLabel::setOpenExternalLinks(), QTextControl::setOpenExternalLinks(), QTextBrowser::setOpenLinks(), QXcbConnection::sync(), QTextControl::toHtml(), QNetworkSessionPrivate::~QNetworkSessionPrivate(), and QNetworkSessionPrivateImpl::~QNetworkSessionPrivateImpl().
 {
     return 0;
 }
open64()
int open64 (const char * , int , ...)
Definition at line 128 of file qfunctions_nacl.cpp.
 {
     return 0;
 }
pthread_attr_getinheritsched()
int pthread_attr_getinheritsched (const pthread_attr_t * , int *)
Definition at line 104 of file qfunctions_nacl.cpp.
 {
     return 0;
 }
pthread_attr_setinheritsched()
int pthread_attr_setinheritsched (pthread_attr_t * , int)
Definition at line 98 of file qfunctions_nacl.cpp.
Referenced by QThread::start().
 {
     return 0;
 }
pthread_cancel()
int pthread_cancel (pthread_t)
Definition at line 93 of file qfunctions_nacl.cpp.
Referenced by QThread::terminate().
 {
     return 0;
 }
pthread_cleanup_pop()
void pthread_cleanup_pop (int)
Definition at line 72 of file qfunctions_nacl.cpp.
Referenced by QThreadPrivate::start().
 {
 }
pthread_cleanup_push()
void pthread_cleanup_push (void(*)(void *) , void *)
Definition at line 67 of file qfunctions_nacl.cpp.
Referenced by QThreadPrivate::start().
 {
 }
pthread_setcancelstate()
int pthread_setcancelstate (int , int *)
Definition at line 77 of file qfunctions_nacl.cpp.
Referenced by QThread::setTerminationEnabled(), and QThreadPrivate::start().
 {
     return 0;
 }
pthread_setcanceltype()
int pthread_setcanceltype (int , int *)
Definition at line 82 of file qfunctions_nacl.cpp.
 {
     return 0;
 }
pthread_testcancel()
void pthread_testcancel (void)
Definition at line 87 of file qfunctions_nacl.cpp.
Referenced by QThread::setTerminationEnabled(), and QThreadPrivate::start().
 {
 }
select()
int select (int , fd_set * , fd_set * , fd_set * , struct timeval *)
Definition at line 153 of file qfunctions_nacl.cpp.
Referenced by QListWidget::addItems(), QX11Data::clipboardWaitForEvent(), QX11Data::dndEnable(), QEventDispatcherUNIXPrivate::doSelect(), QDateTimeEdit::keyPressEvent(), QLineEdit::keyPressEvent(), QListWidgetItem::listWidget(), multicastMembershipHelper(), QItemSelection::QItemSelection(), qt_safe_select(), QWaylandDisplay::readEvents(), QProcessManager::run(), QTreeWidget::setItemSelected(), QSqlResult::setSelect(), QTextEdit::setText(), QTableWidgetItem::tableWidget(), QTreeWidgetItem::treeWidget(), QTreeViewPrivate::AnimatedOperation::updateState(), QUnixSocket::waitForBytesWritten(), QXlibScreen::waitForClipboardEvent(), and QUnixSocket::waitForReadyRead().
 {
     return 0;
 }
sigaction()
int sigaction (int , const struct sigaction * , struct sigaction *)
Definition at line 118 of file qfunctions_nacl.cpp.
Referenced by QTest::FatalSignalHandler::FatalSignalHandler(), ignoreSigPipe(), QSegfaultHandler::initialize(), QDnotifySignalThread::QDnotifySignalThread(), QProcessManager::QProcessManager(), qt_ignore_sigpipe(), qt_sa_sigchld_sigaction(), QTest::FatalSignalHandler::signal(), QProcessPrivate::startDetached(), QCoreApplication::watchUnixSignal(), QTest::FatalSignalHandler::~FatalSignalHandler(), and QProcessManager::~QProcessManager().
 {
     return 0;
 }