Qt 4.8: /src/opengl/qgl_p.h File Reference
qgl_p.h File Reference
#include "QtOpenGL/qgl.h"
#include "QtOpenGL/qglcolormap.h"
#include "QtCore/qmap.h"
#include "QtCore/qthread.h"
#include "QtCore/qthreadstorage.h"
#include "QtCore/qhash.h"
#include "QtCore/qatomic.h"
#include "private/qwidget_p.h"
#include "qcache.h"
#include "qglpaintdevice_p.h"
#include <QtGui/private/qegl_p.h>
#include <AGL/agl.h>
#include <QtOpenGL/private/qglextensions_p.h>
Classes
class QGLContextGroup
class QGLContextGroupResource< T >
class QGLContextGroupResourceBase
class QGLContextPrivate
class QGLContextResource< T >
class QGLContextResourceBase
class QGLEngineThreadStorage< T >
class QGLExtensionMatcher
class QGLExtensions
class QGLFormatPrivate
class QGLShareContextScope
class QGLSharedResourceGuard
class QGLSignalProxy
class QGLTemporaryContext
class QGLTexture
class QGLTextureCache
struct QGLTextureCacheKey
class QGLTextureDestroyer
class QGLWidgetPrivate
Macros
#define QT_GL_VERTEX_ARRAY_TRACKED_COUNT 3
Functions
bool operator== (const QGLTextureCacheKey &a, const QGLTextureCacheKey &b)
uint qHash (const QGLTextureCacheKey &key)
bool qt_gl_preferGL2Engine ()
GLenum qt_gl_preferredTextureFormat ()
GLenum qt_gl_preferredTextureTarget ()
Q_OPENGL_EXPORT const QGLContext * qt_gl_transfer_context (const QGLContext *)
Q_OPENGL_EXPORT QPaintEngine * qt_qgl_paint_engine ()
Macro Definition Documentation
QT_GL_VERTEX_ARRAY_TRACKED_COUNT
#define QT_GL_VERTEX_ARRAY_TRACKED_COUNT 3
Definition at line 343 of file qgl_p.h.
Referenced by QGL2PaintEngineEx::beginNativePainting().
Function Documentation
operator==()
bool operator== (const QGLTextureCacheKey & a, const QGLTextureCacheKey & b) inline
Definition at line 645 of file qgl_p.h.
 {
     return a.key == b.key && a.group == b.group;
 }
qHash()
uint qHash (const QGLTextureCacheKey & key) inline
Definition at line 650 of file qgl_p.h.
 {
     return qHash(key.key) ^ qHash(key.group);
 }
qt_gl_preferGL2Engine()
bool qt_gl_preferGL2Engine ()
Definition at line 218 of file qgl.cpp.
Referenced by QGLTextureCache::getTexture(), QX11GLPixmapData::paintEngine(), QGLPixelBuffer::paintEngine(), QGLFramebufferObject::paintEngine(), qt_gl_preferredTextureTarget(), QGLWindowSurface::updateGeometry(), and QGLPixmapData::useFramebufferObjects().
 {
     return qgl_engine_selector()->preferredPaintEngine() == QPaintEngine::OpenGL2;
 }
qt_gl_preferredTextureFormat()
GLenum qt_gl_preferredTextureFormat () inline
Definition at line 709 of file qgl_p.h.
Referenced by QGLPixmapData::bind(), and QGLPixmapData::ensureCreated().
 {
     return (QGLExtensions::glExtensions() & QGLExtensions::BGRATextureFormat) && QSysInfo::ByteOrder == QSysInfo::LittleEndian
         ? GL_BGRA : GL_RGBA;
 }
qt_gl_preferredTextureTarget()
GLenum qt_gl_preferredTextureTarget () inline
Definition at line 715 of file qgl_p.h.
Referenced by QOpenGLPaintEngine::drawImage(), and QOpenGLPaintEngine::drawPixmap().
 {
 #if defined(QT_OPENGL_ES_2)
     return GL_TEXTURE_2D;
 #else
     return (QGLExtensions::glExtensions() & QGLExtensions::TextureRectangle)
            && !qt_gl_preferGL2Engine()
            ? GL_TEXTURE_RECTANGLE_NV
            : GL_TEXTURE_2D;
 #endif
 }
qt_gl_transfer_context()
Q_OPENGL_EXPORT const QGLContext* qt_gl_transfer_context (const QGLContext *)
Definition at line 1716 of file qgl.cpp.
 {
     if (!ctx)
         return 0;
     QList<const QGLContext *> shares
         (QGLContextPrivate::contextGroup(ctx)->shares());
     if (shares.size() >= 2)
         return (ctx == shares.at(0)) ? shares.at(1) : shares.at(0);
     else
         return 0;
 }
qt_qgl_paint_engine()
Q_OPENGL_EXPORT QPaintEngine* qt_qgl_paint_engine ()
Definition at line 5530 of file qgl.cpp.
Referenced by QGLTextureCache::getTexture(), QBBGLPaintDevice::paintEngine(), QEglFSPaintDevice::paintEngine(), QGLWindowSurfaceGLPaintDevice::paintEngine(), and EAGLPaintDevice::paintEngine().
 {
 #if defined(QT_OPENGL_ES_1)
     return qt_gl_engine()->engine();
 #elif defined(QT_OPENGL_ES_2)
     return qt_gl_2_engine()->engine();
 #else
     if (qt_gl_preferGL2Engine())
         return qt_gl_2_engine()->engine();
     else
         return qt_gl_engine()->engine();
 #endif
 }