Qt 4.8: /src/corelib/global/qglobal.cpp File Reference
qglobal.cpp File Reference
#include "qplatformdefs.h"
#include "qstring.h"
#include "qvector.h"
#include "qlist.h"
#include "qthreadstorage.h"
#include "qdir.h"
#include "qstringlist.h"
#include "qdatetime.h"
#include <private/qthread_p.h>
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <stdarg.h>
#include <string.h>
#include <string>
#include <exception>
#include "private/qcore_mac_p.h"
#include "qnamespace.h"
Classes
struct QInternal_CallBackTable
Typedefs
typedef QThreadStorage< SeedStorageType * > SeedStorage
typedef uint SeedStorageType
Functions
static QSysInfo::MacVersion macVersion ()
Use QSysInfo::MacintoshVersion instead.
void qBadAlloc ()
static void qEmergencyOut (QtMsgType msgType, const char *msg, va_list ap)
Uses a local buffer to output the message.
void qErrnoWarning (const char *msg,...)
void qErrnoWarning (int code, const char *msg,...)
QtMsgHandler qInstallMsgHandler (QtMsgHandler h)
void * qMemCopy (void *dest, const void *src, size_t n)
void * qMemSet (void *dest, int c, size_t n)
bool qSharedBuild ()
void qt_assert (const char *assertion, const char *file, int line)
void qt_assert_x (const char *where, const char *what, const char *file, int line)
void qt_check_pointer (const char *n, int l)
QString qt_error_string (int errorCode)
Q_CORE_EXPORT unsigned int qt_int_sqrt (unsigned int n)
static void qt_message (QtMsgType msgType, const char *msg, va_list ap)
void qt_message_output (QtMsgType msgType, const char *buf)
void qt_set_current_thread_to_main_thread ()
Variables
static QtMsgHandler handler = 0
Typedef Documentation
SeedStorage
typedef QThreadStorage<SeedStorageType *> SeedStorage
Definition at line 3096 of file qglobal.cpp.
SeedStorageType
typedef uint SeedStorageType
Definition at line 3093 of file qglobal.cpp.
Function Documentation
macVersion()
Qt::MacintoshVersion QApplication::macVersion () static
Use QSysInfo::MacintoshVersion instead.
Definition at line 2077 of file qglobal.cpp.
Referenced by QApplication::isLeftToRight().
 {
 #if !defined(Q_OS_IOS)
     SInt32 gestalt_version;
     if (Gestalt(gestaltSystemVersion, &gestalt_version) == noErr) {
         return QSysInfo::MacVersion(((gestalt_version & 0x00F0) >> 4) + 2);
     }
 #endif
     return QSysInfo::MV_Unknown;
 }
qBadAlloc()
void qBadAlloc ()
Definition at line 2451 of file qglobal.cpp.
 {
     QT_THROW(std::bad_alloc());
 }
qEmergencyOut()
static void qEmergencyOut (QtMsgType msgType, const char * msg, va_list ap) static
Uses a local buffer to output the message.
Warning
This function is not part of the public interface. Not locale safe + cuts off everything after character 255, but will work in out of memory situations.
Definition at line 2785 of file qglobal.cpp.
Referenced by qt_message().
 {
     char emergency_buf[256] = { '\0' };
     emergency_buf[255] = '\0';
     if (msg)
         qvsnprintf(emergency_buf, 255, msg, ap);
     qt_message_output(msgType, emergency_buf);
 }
qErrnoWarning() [1/2]
void qErrnoWarning (const char * msg, ...)
Definition at line 2954 of file qglobal.cpp.
Referenced by QFontEngineDirectWrite::addGlyphsToPath(), QWin32PrintEngine::begin(), QFontEngineDirectWrite::boundingBox(), QWindowsXPStylePrivate::buffer(), QFontEngineDirectWrite::canRender(), QGLContext::choosePixelFormat(), QWin32PrintEnginePrivate::composeGdiPath(), QWin32PrintEngine::drawPixmap(), QWin32PrintEngine::drawTiledPixmap(), QThreadPrivate::finish(), QPixmap::fromWinHBITMAP(), QFontEngineDirectWrite::getSfntTableData(), QFontEngineDirectWrite::imageForGlyph(), initFontInfo(), QAxBase::initialize(), QWin32PrintEnginePrivate::initialize(), QAxBase::initializeLicensedHelper(), QAxBase::initializeRemote(), loadEngine(), QOpenKODEWindow::lower(), QWin32PrintEngine::newPage(), QFontEngineQPF::QFontEngineQPF(), QFontEngineWin::QFontEngineWin(), QOpenKODEIntegration::QOpenKODEIntegration(), QOpenKODEScreen::QOpenKODEScreen(), QOpenKODEWindow::QOpenKODEWindow(), QQnxMouseHandler::QQnxMouseHandler(), qt_reg_winclass(), qt_tablet_cleanup_wce(), QWin32PrintEnginePrivate::queryResolutions(), QWaylandDisplay::QWaylandDisplay(), QWSQnxKeyboardHandler::QWSQnxKeyboardHandler(), QOpenKODEWindow::raise(), QFontEngineDirectWrite::recalcAdvances(), QWindowsMime::registerMimeType(), QEventDispatcherWin32Private::registerTimer(), QWidget::releaseDC(), QFontEngineQPF::remapFontData(), resolveGdi32(), QWindowsFileSystemWatcherEngineThread::run(), QOpenKODEWindow::setGeometry(), QOpenKODEWindow::setVisible(), QWSQnxKeyboardHandler::socketActivated(), QQnxMouseHandler::socketActivated(), QFontEngineDirectWrite::stringToCMap(), QPixmap::toWinHBITMAP(), QClipboard::~QClipboard(), QFontEngineQPF::~QFontEngineQPF(), and QFontEngineWin::~QFontEngineWin().
 {
     // qt_error_string() will allocate anyway, so we don't have
     // to be careful here (like we do in plain qWarning())
     QString buf;
     va_list ap;
     va_start(ap, msg);
     if (msg)
         buf.vsprintf(msg, ap);
     va_end(ap);
     qCritical("%s (%s)", buf.toLocal8Bit().constData(), qt_error_string(-1).toLocal8Bit().constData());
 }
qErrnoWarning() [2/2]
void qErrnoWarning (int code, const char * msg, ...)
Definition at line 2968 of file qglobal.cpp.
 {
     // qt_error_string() will allocate anyway, so we don't have
     // to be careful here (like we do in plain qWarning())
     QString buf;
     va_list ap;
     va_start(ap, msg);
     if (msg)
         buf.vsprintf(msg, ap);
     va_end(ap);
     qCritical("%s (%s)", buf.toLocal8Bit().constData(), qt_error_string(code).toLocal8Bit().constData());
 }
qInstallMsgHandler()
QtMsgHandler qInstallMsgHandler (QtMsgHandler h)
Definition at line 2698 of file qglobal.cpp.
Referenced by QClassFactory::CreateInstanceHelper(), QTest::messageHandler(), QErrorMessage::qtHandler(), qWinMain(), QTestLog::startLogging(), QTestLog::stopLogging(), and QErrorMessage::~QErrorMessage().
 {
     QtMsgHandler old = handler;
     handler = h;
 #if defined(Q_OS_WIN) && defined(QT_BUILD_CORE_LIB)
     if (!handler && usingWinMain)
         handler = qWinMsgHandler;
 #endif
     return old;
 }
qMemCopy()
void* qMemCopy (void * dest, const void * src, size_t n)
Definition at line 2508 of file qglobal.cpp.
Referenced by QRawFont::advancesForGlyphIndexes(), QVarLengthArray< QVariant, 9 >::append(), QVolatileImage::copyFrom(), QFontEngineDirectWrite::getSfntTableData(), QGlyphRun::glyphIndexes(), iod_read_fn(), QGlyphRun::positions(), qt_qnan(), qToUnaligned(), QNetworkReplyImpl::readData(), and QVarLengthArray< QVariant, 9 >::realloc().
 { return memcpy(dest, src, n); }
qMemSet()
void* qMemSet (void * dest, int c, size_t n)
Definition at line 2509 of file qglobal.cpp.
Referenced by QPainterPrivate::drawGlyphs(), QFontEngineDirectWrite::imageForGlyph(), QByteArrayMatcher::QByteArrayMatcher(), QStringMatcher::QStringMatcher(), QVector< QPoint >::QVector(), QVector< QPoint >::realloc(), set_text(), QGridLayoutPrivate::setupLayoutData(), QTextEngine::shapeTextWithHarfbuzz(), QPAGenerator::writeGMap(), and QPFGenerator::writeGMap().
 { return memset(dest, c, n); }
qSharedBuild()
bool qSharedBuild ()
Definition at line 1228 of file qglobal.cpp.
 {
 #ifdef QT_SHARED
     return true;
 #else
     return false;
 #endif
 }
qt_assert()
void qt_assert (const char * assertion, const char * file, int line)
Definition at line 2459 of file qglobal.cpp.
 {
     qFatal("ASSERT: \"%s\" in file %s, line %d", assertion, file, line);
 }
qt_assert_x()
void qt_assert_x (const char * where, const char * what, const char * file, int line)
Definition at line 2467 of file qglobal.cpp.
 {
     qFatal("ASSERT failure in %s: \"%s\", file %s, line %d", where, what, file, line);
 }
qt_check_pointer()
void qt_check_pointer (const char * n, int l)
Definition at line 2442 of file qglobal.cpp.
 {
     qFatal("In file %s, line %d: Out of memory", n, l);
 }
qt_error_string()
QString qt_error_string (int errorCode)
Definition at line 2600 of file qglobal.cpp.
Referenced by QLocalServerPrivate::addListener(), QFSFileEnginePrivate::closeFdFh(), QProcessPrivate::execChild(), QFSFileEnginePrivate::flushFh(), QFSFileEnginePrivate::longFileName(), QFSFileEnginePrivate::map(), QFSFileEnginePrivate::nativeOpen(), QFSFileEnginePrivate::nativeRead(), QFSFileEnginePrivate::openFd(), QFSFileEnginePrivate::openFh(), QProcessPrivate::processStarted(), qErrnoWarning(), qt_create_commandline(), qt_create_pipe(), qt_message(), qt_parse_pattern(), QNativeSocketEngine::read(), QFSFileEnginePrivate::readFdFh(), QFSFileEnginePrivate::readLineFdFh(), report_error(), QFSFileEnginePrivate::seekFdFh(), QFilePrivate::setError(), QFSFileEngine::setSize(), QThread::start(), QProcessPrivate::startProcess(), QThread::terminate(), QFSFileEnginePrivate::unmap(), QFSFileEnginePrivate::writeFdFh(), and QProcessPrivate::writeToStdin().
 {
     const char *s = 0;
     QString ret;
     if (errorCode == -1) {
 #if defined(Q_OS_WIN)
         errorCode = GetLastError();
 #else
         errorCode = errno;
 #endif
     }
     switch (errorCode) {
     case 0:
         break;
     case EACCES:
         s = QT_TRANSLATE_NOOP("QIODevice", "Permission denied");
         break;
     case EMFILE:
         s = QT_TRANSLATE_NOOP("QIODevice", "Too many open files");
         break;
     case ENOENT:
         s = QT_TRANSLATE_NOOP("QIODevice", "No such file or directory");
         break;
     case ENOSPC:
         s = QT_TRANSLATE_NOOP("QIODevice", "No space left on device");
         break;
     default: {
 #ifdef Q_OS_WIN
         wchar_t *string = 0;
         FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER|FORMAT_MESSAGE_FROM_SYSTEM,
                       NULL,
                       errorCode,
                       MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
                       (LPWSTR)&string,
                       0,
                       NULL);
         ret = QString::fromWCharArray(string);
         LocalFree((HLOCAL)string);
         if (ret.isEmpty() && errorCode == ERROR_MOD_NOT_FOUND)
             ret = QString::fromLatin1("The specified module could not be found.");
 #elif !defined(QT_NO_THREAD) && defined(_POSIX_THREAD_SAFE_FUNCTIONS) && _POSIX_VERSION >= 200112L && !defined(Q_OS_INTEGRITY) && !defined(Q_OS_QNX)
         QByteArray buf(1024, '\0');
         ret = fromstrerror_helper(strerror_r(errorCode, buf.data(), buf.size()), buf);
 #else
         ret = QString::fromLocal8Bit(strerror(errorCode));
 #endif
     break; }
     }
     if (s)
         // ######## this breaks moc build currently
 //         ret = QCoreApplication::translate("QIODevice", s);
         ret = QString::fromLatin1(s);
     return ret.trimmed();
 }
qt_int_sqrt()
Q_CORE_EXPORT unsigned int qt_int_sqrt (unsigned int n)
Definition at line 2478 of file qglobal.cpp.
Referenced by QTextDocument::adjustSize(), and qt_int_sqrt().
 {
     // n must be in the range 0...UINT_MAX/2-1
     if (n >= (UINT_MAX>>2)) {
         unsigned int r = 2 * qt_int_sqrt(n / 4);
         unsigned int r2 = r + 1;
         return (n >= r2 * r2) ? r2 : r;
     }
     uint h, p= 0, q= 1, r= n;
     while (q <= n)
         q <<= 2;
     while (q != 1) {
         q >>= 2;
         h= p + q;
         p >>= 1;
         if (r >= h) {
             p += q;
             r -= h;
         }
     }
     return p;
 }
qt_message()
static void qt_message (QtMsgType msgType, const char * msg, va_list ap) static
Warning
This function is not part of the public interface.
Definition at line 2798 of file qglobal.cpp.
Referenced by qErrnoWarning().
 {
 #if !defined(QT_NO_EXCEPTIONS)
     if (std::uncaught_exception()) {
         qEmergencyOut(msgType, msg, ap);
         return;
     }
 #endif
     QByteArray buf;
     if (msg) {
         QT_TRY {
             buf = QString().vsprintf(msg, ap).toLocal8Bit();
         } QT_CATCH(const std::bad_alloc &) {
 #if !defined(QT_NO_EXCEPTIONS)
             qEmergencyOut(msgType, msg, ap);
             // don't rethrow - we use qWarning and friends in destructors.
             return;
 #endif
         }
     }
     qt_message_output(msgType, buf.constData());
 }
qt_message_output()
void qt_message_output (QtMsgType msgType, const char * buf)
Warning
This function is not part of the public interface.
Definition at line 2712 of file qglobal.cpp.
Referenced by qEmergencyOut(), qt_message(), and QDebug::~QDebug().
 {
     if (handler) {
         (*handler)(msgType, buf);
     } else {
 #if defined(Q_CC_MWERKS) && defined(Q_OS_MACX)
         mac_default_handler(buf);
 #elif defined(QT_USE_SLOG2)
         slog2_default_handler(msgType, buf);
 #elif defined(Q_OS_WINCE)
         QString fstr = QString::fromLatin1(buf);
         fstr += QLatin1Char('\n');
         OutputDebugString(reinterpret_cast<const wchar_t *> (fstr.utf16()));
 #elif defined(Q_OS_SYMBIAN)
         // RDebug::Print has a cap of 256 characters so break it up
         char format[] = "[Qt Message] %S";
         const int maxBlockSize = 256 - sizeof(format);
         const TPtrC8 ptr(reinterpret_cast<const TUint8*>(buf));
         for (int i = 0; i < ptr.Length(); i += maxBlockSize) {
             TPtrC8 part(ptr.Mid(i, qMin(maxBlockSize, ptr.Length()-i)));
             RDebug::Printf(format, &part);
         }
 #else
         fprintf(stderr, "%s\n", buf);
         fflush(stderr);
 #endif
     }
     if (msgType == QtFatalMsg
         || (msgType == QtWarningMsg
             && (!qgetenv("QT_FATAL_WARNINGS").isNull())) ) {
 #if defined(Q_CC_MSVC) && defined(QT_DEBUG) && defined(_DEBUG) && defined(_CRT_ERROR)
         // get the current report mode
         int reportMode = _CrtSetReportMode(_CRT_ERROR, _CRTDBG_MODE_WNDW);
         _CrtSetReportMode(_CRT_ERROR, reportMode);
 #if !defined(Q_OS_WINCE)
         int ret = _CrtDbgReport(_CRT_ERROR, __FILE__, __LINE__, QT_VERSION_STR, buf);
 #else
         int ret = _CrtDbgReportW(_CRT_ERROR, _CRT_WIDE(__FILE__),
             __LINE__, _CRT_WIDE(QT_VERSION_STR), reinterpret_cast<const wchar_t *> (QString::fromLatin1(buf).utf16()));
 #endif
         if (ret == 0  && reportMode & _CRTDBG_MODE_WNDW)
             return; // ignore
         else if (ret == 1)
             _CrtDbgBreak();
 #endif
 #if defined(Q_OS_SYMBIAN)
         __DEBUGGER(); // on the emulator, get the debugger to kick in if there's one around
         TBuf<256> tmp;
         TPtrC8 ptr(reinterpret_cast<const TUint8*>(buf));
         TInt len = Min(tmp.MaxLength(), ptr.Length());
         tmp.Copy(ptr.Left(len));
         // Panic the current thread. We don't use real panic codes, so 0 has no special meaning.
         User::Panic(tmp, 0);
 #elif (defined(Q_OS_UNIX) || defined(Q_CC_MINGW))
         abort(); // trap; generates core dump
 #else
         exit(1); // goodbye cruel world
 #endif
     }
 }
qt_set_current_thread_to_main_thread()
void qt_set_current_thread_to_main_thread ()
Definition at line 355 of file qcoreapplication.cpp.
Referenced by QInternal::activateCallbacks(), and QInternal::callFunction().
 {
     QCoreApplicationPrivate::theMainThread = QThread::currentThread();
 }
Variable Documentation
handler
QtMsgHandler handler = 0 static
Definition at line 2511 of file qglobal.cpp.
Referenced by qInstallMsgHandler(), and qt_message_output().