Qt 4.8: /src/opengl/qglpixmapfilter.cpp File Reference
qglpixmapfilter.cpp File Reference
#include "private/qpixmapfilter_p.h"
#include "private/qpixmapdata_gl_p.h"
#include "private/qpaintengineex_opengl2_p.h"
#include "private/qglengineshadermanager_p.h"
#include "private/qpixmapdata_p.h"
#include "private/qimagepixmapcleanuphooks_p.h"
#include "qglpixmapfilter_p.h"
#include "qgraphicssystem_gl_p.h"
#include "qpaintengine_opengl_p.h"
#include "qcache.h"
#include "qglframebufferobject.h"
#include "qglshaderprogram.h"
#include "qgl_p.h"
#include "private/qapplication_p.h"
#include "private/qdrawhelper_p.h"
#include "private/qmemrotate_p.h"
#include "private/qmath_p.h"
#include "qmath.h"
Classes
class QGLBlurTextureCache
class QGLBlurTextureInfo
class QGLPixmapBlurFilter
class QGLPixmapColorizeFilter
class QGLPixmapConvolutionFilter
class QGLPixmapDropShadowFilter
Functions
static GLuint generateBlurTexture (const QSize &size, GLenum format=GL_RGBA)
static uint nextMultiple (uint x, uint multiplier)
Q_GUI_EXPORT void qt_blurImage (QImage &blurImage, qreal radius, bool quality, int transposed=0)
const QGLContext * qt_gl_share_context ()
Q_GUI_EXPORT QImage qt_halfScaled (const QImage &source)
Q_GUI_EXPORT void qt_memrotate90_gl (const quint32 *src, int srcWidth, int srcHeight, int srcStride, quint32 *dest, int dstStride)
Variables
static const int qAnimatedBlurLevelIncrement = 16
static const int qMaxBlurHalfScaleLevel = 1
static const char * qt_gl_colorize_filter
static const char * qt_gl_drop_shadow_filter
Function Documentation
generateBlurTexture()
static GLuint generateBlurTexture (const QSize & size, GLenum format = GL_RGBA) static
Definition at line 410 of file qglpixmapfilter.cpp.
Referenced by QGLPixmapBlurFilter::processGL().
 {
     GLuint texture;
     glGenTextures(1, &texture);
     glBindTexture(GL_TEXTURE_2D, texture);
     glTexImage2D(GL_TEXTURE_2D, 0, format, size.width(), size.height(), 0, format,
                  GL_UNSIGNED_BYTE, 0);
     return texture;
 }
nextMultiple()
static uint nextMultiple (uint x, uint multiplier) inline static
Definition at line 420 of file qglpixmapfilter.cpp.
Referenced by QGLPixmapBlurFilter::processGL().
 {
     uint mod = x % multiplier;
     if (mod == 0)
         return x;
     return x + multiplier - mod;
 }
qt_blurImage()
Q_GUI_EXPORT void qt_blurImage (QImage & blurImage, qreal radius, bool quality, int transposed = 0)
Definition at line 912 of file qpixmapfilter.cpp.
Referenced by QGLPixmapBlurFilter::processGL(), and QGLPixmapDropShadowFilter::processGL().
 {
     if (blurImage.format() == QImage::Format_Indexed8)
         expblur<12, 10, true>(blurImage, radius, quality, transposed);
     else
         expblur<12, 10, false>(blurImage, radius, quality, transposed);
 }
qt_gl_share_context()
const QGLContext* qt_gl_share_context ()
Definition at line 284 of file qwindowsurface_gl.cpp.
 {
     QGLWidget *widget = qt_gl_share_widget();
     if (widget)
         return widget->context();
     return 0;
 }
qt_halfScaled()
Q_GUI_EXPORT QImage qt_halfScaled (const QImage & source)
Definition at line 797 of file qpixmapfilter.cpp.
Referenced by QGLBlurTextureInfo::paddedImage(), QGLPixmapBlurFilter::processGL(), QGLPixmapDropShadowFilter::processGL(), and qt_blurImage().
 {
     if (source.width() < 2 || source.height() < 2)
         return QImage();
     QImage srcImage = source;
     if (source.format() == QImage::Format_Indexed8) {
         // assumes grayscale
         QImage dest(source.width() / 2, source.height() / 2, srcImage.format());
         const uchar *src = reinterpret_cast<const uchar*>(const_cast<const QImage &>(srcImage).bits());
         int sx = srcImage.bytesPerLine();
         int sx2 = sx << 1;
         uchar *dst = reinterpret_cast<uchar*>(dest.bits());
         int dx = dest.bytesPerLine();
         int ww = dest.width();
         int hh = dest.height();
         for (int y = hh; y; --y, dst += dx, src += sx2) {
             const uchar *p1 = src;
             const uchar *p2 = src + sx;
             uchar *q = dst;
             for (int x = ww; x; --x, ++q, p1 += 2, p2 += 2)
                 *q = ((int(p1[0]) + int(p1[1]) + int(p2[0]) + int(p2[1])) + 2) >> 2;
         }
         return dest;
     } else if (source.format() == QImage::Format_ARGB8565_Premultiplied) {
         QImage dest(source.width() / 2, source.height() / 2, srcImage.format());
         const uchar *src = reinterpret_cast<const uchar*>(const_cast<const QImage &>(srcImage).bits());
         int sx = srcImage.bytesPerLine();
         int sx2 = sx << 1;
         uchar *dst = reinterpret_cast<uchar*>(dest.bits());
         int dx = dest.bytesPerLine();
         int ww = dest.width();
         int hh = dest.height();
         for (int y = hh; y; --y, dst += dx, src += sx2) {
             const uchar *p1 = src;
             const uchar *p2 = src + sx;
             uchar *q = dst;
             for (int x = ww; x; --x, q += 3, p1 += 6, p2 += 6) {
                 // alpha
                 q[0] = AVG(AVG(p1[0], p1[3]), AVG(p2[0], p2[3]));
                 // rgb
                 const quint16 p16_1 = (p1[2] << 8) | p1[1];
                 const quint16 p16_2 = (p1[5] << 8) | p1[4];
                 const quint16 p16_3 = (p2[2] << 8) | p2[1];
                 const quint16 p16_4 = (p2[5] << 8) | p2[4];
                 const quint16 result = AVG16(AVG16(p16_1, p16_2), AVG16(p16_3, p16_4));
                 q[1] = result & 0xff;
                 q[2] = result >> 8;
             }
         }
         return dest;
     } else if (source.format() != QImage::Format_ARGB32_Premultiplied
                && source.format() != QImage::Format_RGB32)
     {
         srcImage = source.convertToFormat(QImage::Format_ARGB32_Premultiplied);
     }
     QImage dest(source.width() / 2, source.height() / 2, srcImage.format());
     const quint32 *src = reinterpret_cast<const quint32*>(const_cast<const QImage &>(srcImage).bits());
     int sx = srcImage.bytesPerLine() >> 2;
     int sx2 = sx << 1;
     quint32 *dst = reinterpret_cast<quint32*>(dest.bits());
     int dx = dest.bytesPerLine() >> 2;
     int ww = dest.width();
     int hh = dest.height();
     for (int y = hh; y; --y, dst += dx, src += sx2) {
         const quint32 *p1 = src;
         const quint32 *p2 = src + sx;
         quint32 *q = dst;
         for (int x = ww; x; --x, q++, p1 += 2, p2 += 2)
             *q = AVG(AVG(p1[0], p1[1]), AVG(p2[0], p2[1]));
     }
     return dest;
 }
qt_memrotate90_gl()
Q_GUI_EXPORT void qt_memrotate90_gl (const quint32 * src, int srcWidth, int srcHeight, int srcStride, quint32 * dest, int dstStride)
Definition at line 591 of file qmemrotate.cpp.
Referenced by nextMultiple(), and QGLPixmapBlurFilter::processGL().
 {
     qt_memrotate90_template(src, srcWidth, srcHeight, srcStride, reinterpret_cast<qrgb_gl_rgba *>(dest), dstStride);
 }
Variable Documentation
qAnimatedBlurLevelIncrement
const int qAnimatedBlurLevelIncrement = 16 static
Definition at line 407 of file qglpixmapfilter.cpp.
Referenced by QGLPixmapBlurFilter::processGL().
qMaxBlurHalfScaleLevel
const int qMaxBlurHalfScaleLevel = 1 static
Definition at line 408 of file qglpixmapfilter.cpp.
Referenced by QGLPixmapBlurFilter::processGL().
qt_gl_colorize_filter
const char* qt_gl_colorize_filter static
Initial value:
=
        "uniform lowp vec4 colorizeColor;"
        "uniform lowp float colorizeStrength;"
        "lowp vec4 customShader(lowp sampler2D src, highp vec2 srcCoords)"
        "{"
        "        lowp vec4 srcPixel = texture2D(src, srcCoords);"
        "        lowp float gray = dot(srcPixel.rgb, vec3(0.212671, 0.715160, 0.072169));"
        "        lowp vec3 colorized = 1.0-((1.0-gray)*(1.0-colorizeColor.rgb));"
        "        return vec4(mix(srcPixel.rgb, colorized * srcPixel.a, colorizeStrength), srcPixel.a);"
        "}"
Definition at line 161 of file qglpixmapfilter.cpp.
Referenced by QGLPixmapColorizeFilter::QGLPixmapColorizeFilter().
qt_gl_drop_shadow_filter
const char* qt_gl_drop_shadow_filter static
Initial value:
=
        "uniform lowp vec4 shadowColor;"
        "lowp vec4 customShader(lowp sampler2D src, highp vec2 srcCoords)"
        "{"
        "    return shadowColor * texture2D(src, srcCoords.yx).a;"
        "}"
Definition at line 537 of file qglpixmapfilter.cpp.
Referenced by QGLPixmapDropShadowFilter::QGLPixmapDropShadowFilter().