Qt 4.8: /src/opengl/qgltexturepool.cpp File Reference
qgltexturepool.cpp File Reference
#include "qgltexturepool_p.h"
#include "qpixmapdata_gl_p.h"
#include "qgl_p.h"
Classes
class QGLTexturePoolPrivate
Functions
Q_OPENGL_EXPORT QGLWidget * qt_gl_share_widget ()
Variables
static QGLTexturePool * qt_gl_texture_pool = 0
Function Documentation
qt_gl_share_widget()
Q_OPENGL_EXPORT QGLWidget* qt_gl_share_widget ()
Definition at line 264 of file qwindowsurface_gl.cpp.
Referenced by QMeeGoGraphicsSystemSwitchHandler::addWidget(), QMeeGoGraphicsSystem::createFenceSync(), QMeeGoGraphicsSystem::createWindowSurface(), QMeeGoPixmapData::destroyEGLSharedImage(), QMeeGoGraphicsSystem::destroyFenceSync(), QMeeGoPixmapData::fromEGLSharedImage(), QMeeGoPixmapData::imageToEGLSharedImage(), QMeeGoLivePixmapData::initializeThroughEGLImage(), QMeeGoLivePixmapData::lock(), QGLPixmapData::paintEngine(), and QMeeGoLivePixmapData::release().
 {
     if (QGLGlobalShareWidget::cleanedUp)
         return 0;
     return _qt_gl_share_widget()->shareWidget();
 }
Variable Documentation
qt_gl_texture_pool
QGLTexturePool* qt_gl_texture_pool = 0 static
Definition at line 50 of file qgltexturepool.cpp.
Referenced by QGLTexturePool::instance().