Qt 4.8: /src/gui/graphicsview/qgraphicsanchorlayout_p.cpp File Reference
qgraphicsanchorlayout_p.cpp File Reference
#include <QtGui/qwidget.h>
#include <QtGui/qapplication.h>
#include <QtCore/qlinkedlist.h>
#include <QtCore/qstack.h>
#include <QtCore/qfile.h>
#include "qgraphicsanchorlayout_p.h"
Enumerations
enum slackType { Grower = -1, Shrinker = 1 }
Functions
static void applySizePolicy (QSizePolicy::Policy policy, qreal minSizeHint, qreal prefSizeHint, qreal maxSizeHint, qreal *minSize, qreal *prefSize, qreal *maxSize)
static qreal checkAdd (qreal a, qreal b)
static AnchorData * createSequence (Graph< AnchorVertex, AnchorData > *graph, AnchorVertex *before, const QVector< AnchorVertex *> &vertices, AnchorVertex *after)
Takes the sequence of vertices described by (before, vertices, after) and removes all anchors connected to the vertices in vertices, returning one simplified anchor between before and after.
static QPair< QSimplexVariable *, QSimplexConstraint * > createSlack (QSimplexConstraint *sizeConstraint, qreal interval, slackType type)
static QPair< QGraphicsAnchorLayoutPrivate::Interval, qreal > getFactor (qreal value, qreal min, qreal minPref, qreal pref, qreal maxPref, qreal max)
QList< AnchorData * > getVariables (QList< QSimplexConstraint *> constraints)
static qreal interpolate (const QPair< QGraphicsAnchorLayoutPrivate::Interval, qreal > &factor, qreal min, qreal minPref, qreal pref, qreal maxPref, qreal max)
static AnchorVertex * replaceVertex_helper (AnchorData *data, AnchorVertex *oldV, AnchorVertex *newV)
static void shiftConstraints (const QList< QSimplexConstraint *> &constraints, qreal amount)
Shift all the constraints by a certain amount.
Variables
const qreal g_offset = (sizeof(qreal) == sizeof(double)) ? QWIDGETSIZE_MAX : QWIDGETSIZE_MAX / 32
Enumeration Type Documentation
slackType
enum slackType
Enumerator
Grower
Shrinker
Definition at line 2916 of file qgraphicsanchorlayout_p.cpp.
 { Grower = -1, Shrinker = 1 };
Function Documentation
applySizePolicy()
static void applySizePolicy (QSizePolicy::Policy policy, qreal minSizeHint, qreal prefSizeHint, qreal maxSizeHint, qreal * minSize, qreal * prefSize, qreal * maxSize) static
Definition at line 131 of file qgraphicsanchorlayout_p.cpp.
Referenced by AnchorData::refreshSizeHints().
 {
     // minSize, prefSize and maxSize are initialized
     // with item's preferred Size: this is QSizePolicy::Fixed.
     //
     // Then we check each flag to find the resultant QSizePolicy,
     // according to the following table:
     //
     //      constant               value
     // QSizePolicy::Fixed            0
     // QSizePolicy::Minimum       GrowFlag
     // QSizePolicy::Maximum       ShrinkFlag
     // QSizePolicy::Preferred     GrowFlag | ShrinkFlag
     // QSizePolicy::Ignored       GrowFlag | ShrinkFlag | IgnoreFlag
     if (policy & QSizePolicy::ShrinkFlag)
         *minSize = minSizeHint;
     else
         *minSize = prefSizeHint;
     if (policy & QSizePolicy::GrowFlag)
         *maxSize = maxSizeHint;
     else
         *maxSize = prefSizeHint;
     // Note that these two initializations are affected by the previous flags
     if (policy & QSizePolicy::IgnoreFlag)
         *prefSize = *minSize;
     else
         *prefSize = prefSizeHint;
 }
checkAdd()
static qreal checkAdd (qreal a, qreal b) inline static
Warning
This function is not part of the public interface.
helper function in order to avoid overflowing anchor sizes the returned size will never be larger than FLT_MAX
Definition at line 670 of file qgraphicsanchorlayout_p.cpp.
 {
     if (FLT_MAX - b  < a)
         return FLT_MAX;
     return a + b;
 }
createSequence()
static AnchorData* createSequence (Graph< AnchorVertex, AnchorData > * graph, AnchorVertex * before, const QVector< AnchorVertex *> & vertices, AnchorVertex * after) static
Takes the sequence of vertices described by (before, vertices, after) and removes all anchors connected to the vertices in vertices, returning one simplified anchor between before and after.
Warning
This function is not part of the public interface.
Note that this function doesn't add the created anchor to the graph. This should be done by the caller.
Definition at line 766 of file qgraphicsanchorlayout_p.cpp.
Referenced by QGraphicsAnchorLayoutPrivate::simplifyGraphIteration().
 {
 #if defined(QT_DEBUG) && 0
     QString strVertices;
     for (int i = 0; i < vertices.count(); ++i) {
         strVertices += QString::fromAscii("%1 - ").arg(vertices.at(i)->toString());
     }
     QString strPath = QString::fromAscii("%1 - %2%3").arg(before->toString(), strVertices, after->toString());
     qDebug("simplifying [%s] to [%s - %s]", qPrintable(strPath), qPrintable(before->toString()), qPrintable(after->toString()));
 #endif
     AnchorVertex *prev = before;
     QVector<AnchorData *> edges;
     // Take from the graph, the edges that will be simplificated
     for (int i = 0; i < vertices.count(); ++i) {
         AnchorVertex *next = vertices.at(i);
         AnchorData *ad = graph->takeEdge(prev, next);
         Q_ASSERT(ad);
         edges.append(ad);
         prev = next;
     }
     // Take the last edge (not covered in the loop above)
     AnchorData *ad = graph->takeEdge(vertices.last(), after);
     Q_ASSERT(ad);
     edges.append(ad);
     // Create sequence
     SequentialAnchorData *sequence = new SequentialAnchorData(vertices, edges);
     sequence->from = before;
     sequence->to = after;
     sequence->calculateSizeHints();
     return sequence;
 }
createSlack()
static QPair<QSimplexVariable *, QSimplexConstraint *> createSlack (QSimplexConstraint * sizeConstraint, qreal interval, slackType type) static
Definition at line 2917 of file qgraphicsanchorlayout_p.cpp.
Referenced by QGraphicsAnchorLayoutPrivate::solvePreferred().
 {
     QSimplexVariable *slack = new QSimplexVariable;
     sizeConstraint->variables.insert(slack, type);
     QSimplexConstraint *limit = new QSimplexConstraint;
     limit->variables.insert(slack, 1.0);
     limit->ratio = QSimplexConstraint::LessOrEqual;
     limit->constant = interval;
     return qMakePair(slack, limit);
 }
getFactor()
static QPair<QGraphicsAnchorLayoutPrivate::Interval, qreal> getFactor (qreal value, qreal min, qreal minPref, qreal pref, qreal maxPref, qreal max) static
Warning
This function is not part of the public interface. returns the factor in the interval [-1, 1]. -1 is at Minimum 0 is at Preferred 1 is at Maximum
Definition at line 415 of file qgraphicsanchorlayout_p.cpp.
Referenced by QGraphicsAnchorLayoutPrivate::setupEdgesInterpolation(), and SequentialAnchorData::updateChildrenSizes().
 {
     QGraphicsAnchorLayoutPrivate::Interval interval;
     qreal lower;
     qreal upper;
     if (value < minPref) {
         interval = QGraphicsAnchorLayoutPrivate::MinimumToMinPreferred;
         lower = min;
         upper = minPref;
     } else if (value < pref) {
         interval = QGraphicsAnchorLayoutPrivate::MinPreferredToPreferred;
         lower = minPref;
         upper = pref;
     } else if (value < maxPref) {
         interval = QGraphicsAnchorLayoutPrivate::PreferredToMaxPreferred;
         lower = pref;
         upper = maxPref;
     } else {
         interval = QGraphicsAnchorLayoutPrivate::MaxPreferredToMaximum;
         lower = maxPref;
         upper = max;
     }
     qreal progress;
     if (upper == lower) {
         progress = 0;
     } else {
         progress = (value - lower) / (upper - lower);
     }
     return qMakePair(interval, progress);
 }
getVariables()
QList<AnchorData *> getVariables (QList< QSimplexConstraint *> constraints)
Definition at line 2098 of file qgraphicsanchorlayout_p.cpp.
Referenced by QGraphicsAnchorLayoutPrivate::calculateGraphs(), and QGraphicsAnchorLayoutPrivate::solveMinMax().
 {
     QSet<AnchorData *> variableSet;
     for (int i = 0; i < constraints.count(); ++i) {
         const QSimplexConstraint *c = constraints.at(i);
         foreach (QSimplexVariable *var, c->variables.keys()) {
             variableSet += static_cast<AnchorData *>(var);
         }
     }
     return variableSet.toList();
 }
interpolate()
static qreal interpolate (const QPair< QGraphicsAnchorLayoutPrivate::Interval, qreal > & factor, qreal min, qreal minPref, qreal pref, qreal maxPref, qreal max) static
Definition at line 451 of file qgraphicsanchorlayout_p.cpp.
Referenced by QGraphicsAnchorLayoutPrivate::interpolateEdge(), and SequentialAnchorData::updateChildrenSizes().
 {
     qreal lower = 0;
     qreal upper = 0;
     switch (factor.first) {
     case QGraphicsAnchorLayoutPrivate::MinimumToMinPreferred:
         lower = min;
         upper = minPref;
         break;
     case QGraphicsAnchorLayoutPrivate::MinPreferredToPreferred:
         lower = minPref;
         upper = pref;
         break;
     case QGraphicsAnchorLayoutPrivate::PreferredToMaxPreferred:
         lower = pref;
         upper = maxPref;
         break;
     case QGraphicsAnchorLayoutPrivate::MaxPreferredToMaximum:
         lower = maxPref;
         upper = max;
         break;
     }
     return lower + factor.second * (upper - lower);
 }
replaceVertex_helper()
static AnchorVertex* replaceVertex_helper (AnchorData * data, AnchorVertex * oldV, AnchorVertex * newV) static
Definition at line 891 of file qgraphicsanchorlayout_p.cpp.
Referenced by QGraphicsAnchorLayoutPrivate::replaceVertex(), and QGraphicsAnchorLayoutPrivate::restoreVertices().
 {
     AnchorVertex *other;
     if (data->from == oldV) {
         data->from = newV;
         other = data->to;
     } else {
         data->to = newV;
         other = data->from;
     }
     return other;
 }
shiftConstraints()
static void shiftConstraints (const QList< QSimplexConstraint *> & constraints, qreal amount) static
Shift all the constraints by a certain amount.
Warning
This function is not part of the public interface.
This allows us to deal with negative values in the linear program if they are bounded by a certain limit. Functions should be careful to call it again with a negative amount, to shift the constraints back.
Definition at line 2228 of file qgraphicsanchorlayout_p.cpp.
Referenced by QGraphicsAnchorLayoutPrivate::calculateNonTrunk(), and QGraphicsAnchorLayoutPrivate::calculateTrunk().
 {
     for (int i = 0; i < constraints.count(); ++i) {
         QSimplexConstraint *c = constraints.at(i);
         qreal multiplier = 0;
         foreach (qreal v, c->variables.values()) {
             multiplier += v;
         }
         c->constant += multiplier * amount;
     }
 }
Variable Documentation
g_offset
const qreal g_offset = (sizeof(qreal) == sizeof(double)) ? QWIDGETSIZE_MAX : QWIDGETSIZE_MAX / 32
Definition at line 62 of file qgraphicsanchorlayout_p.cpp.
Referenced by QGraphicsAnchorLayoutPrivate::calculateNonTrunk(), QGraphicsAnchorLayoutPrivate::calculateTrunk(), QGraphicsAnchorLayoutPrivate::constraintsFromSizeHints(), QGraphicsAnchorLayoutPrivate::solveMinMax(), and QGraphicsAnchorLayoutPrivate::solvePreferred().