Qt 4.8: /src/gui/graphicsview/qgraphicslayoutitem.cpp File Reference
qgraphicslayoutitem.cpp File Reference
#include "qglobal.h"
#include "qgraphicslayout.h"
#include "qgraphicsscene.h"
#include "qgraphicslayoutitem.h"
#include "qgraphicslayoutitem_p.h"
#include "qwidget.h"
#include "qgraphicswidget.h"
#include <QtDebug>
Macros
#define COMBINE_SIZE(result, size)
Functions
static void boundSize (QSizeF &result, const QSizeF &size)
static void combineSize (QSizeF &result, const QSizeF &size)
static void expandSize (QSizeF &result, const QSizeF &size)
static void normalizeHints (qreal &minimum, qreal &preferred, qreal &maximum, qreal &descent)
Macro Definition Documentation
COMBINE_SIZE
#define COMBINE_SIZE (result, size)
Value:
do { \
        if ((result).width() < 0 || (result).height() < 0) \
            combineSize((result), (size)); \
    } while (false)
Definition at line 61 of file qgraphicslayoutitem.cpp.
Referenced by QGraphicsLayoutItemPrivate::effectiveSizeHints().
Function Documentation
boundSize()
static void boundSize (QSizeF & result, const QSizeF & size) static
Definition at line 75 of file qgraphicslayoutitem.cpp.
Referenced by QGraphicsLayoutItemPrivate::effectiveSizeHints().
 {
     if (size.width() >= 0 && size.width() < result.width())
         result.setWidth(size.width());
     if (size.height() >= 0 && size.height() < result.height())
         result.setHeight(size.height());
 }
combineSize()
static void combineSize (QSizeF & result, const QSizeF & size) static
Definition at line 67 of file qgraphicslayoutitem.cpp.
Referenced by QGraphicsLayoutItemPrivate::effectiveSizeHints().
 {
     if (result.width() < 0)
         result.setWidth(size.width());
     if (result.height() < 0)
         result.setHeight(size.height());
 }
expandSize()
static void expandSize (QSizeF & result, const QSizeF & size) static
Definition at line 83 of file qgraphicslayoutitem.cpp.
Referenced by QGraphicsLayoutItemPrivate::effectiveSizeHints().
 {
     if (size.width() >= 0 && size.width() > result.width())
         result.setWidth(size.width());
     if (size.height() >= 0 && size.height() > result.height())
         result.setHeight(size.height());
 }
normalizeHints()
static void normalizeHints (qreal & minimum, qreal & preferred, qreal & maximum, qreal & descent) static
Definition at line 91 of file qgraphicslayoutitem.cpp.
Referenced by QGraphicsLayoutItemPrivate::effectiveSizeHints().
 {
     if (minimum >= 0 && maximum >= 0 && minimum > maximum)
         minimum = maximum;
     if (preferred >= 0) {
         if (minimum >= 0 && preferred < minimum) {
             preferred = minimum;
         } else if (maximum >= 0 && preferred > maximum) {
             preferred = maximum;
         }
     }
     if (minimum >= 0 && descent > minimum)
         descent = minimum;
 }