Qt 4.8: /src/gui/graphicsview/qgraphicsitem_p.h File Reference
qgraphicsitem_p.h File Reference
#include "qgraphicsitem.h"
#include "qset.h"
#include "qpixmapcache.h"
#include <private/qgraphicsview_p.h>
#include "qgraphicstransform.h"
#include <private/qgraphicstransform_p.h>
#include <private/qgraphicseffect_p.h>
#include <qgraphicseffect.h>
#include <QtCore/qpoint.h>
Classes
class QDeclarativeListProperty< T >
The QDeclarativeListProperty class allows applications to expose list-like properties to QML.
class QGraphicsItemCache
struct QGraphicsItemCache::DeviceData
class QGraphicsItemEffectSourcePrivate
struct QGraphicsItemPaintInfo
class QGraphicsItemPrivate
struct QGraphicsItemPrivate::ExtraStruct
struct QGraphicsItemPrivate::TransformData
Macros
#define QDECLARATIVELISTPROPERTY
Functions
bool qt_closestItemFirst (const QGraphicsItem *item1, const QGraphicsItem *item2)
Returns true if item1 is on top of item2.
bool qt_closestItemLast (const QGraphicsItem *item1, const QGraphicsItem *item2)
Returns true if item2 is on top of item1.
bool qt_closestLeaf (const QGraphicsItem *item1, const QGraphicsItem *item2)
bool qt_notclosestLeaf (const QGraphicsItem *item1, const QGraphicsItem *item2)
Macro Definition Documentation
QDECLARATIVELISTPROPERTY
#define QDECLARATIVELISTPROPERTY
Definition at line 75 of file qgraphicsitem_p.h.
Function Documentation
qt_closestItemFirst()
bool qt_closestItemFirst (const QGraphicsItem * item1, const QGraphicsItem * item2) inline
Returns true if item1 is on top of item2.
The items don't need to be siblings.
Warning
This function is not part of the public interface.
Definition at line 729 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::gestureEventHandler(), qt_closestItemLast(), and QGraphicsSceneBspTreeIndexPrivate::sortItems().
 {
     // Siblings? Just check their z-values.
     const QGraphicsItemPrivate *d1 = item1->d_ptr.data();
     const QGraphicsItemPrivate *d2 = item2->d_ptr.data();
     if (d1->parent == d2->parent)
         return qt_closestLeaf(item1, item2);
     // Find common ancestor, and each item's ancestor closest to the common
     // ancestor.
     int item1Depth = d1->depth();
     int item2Depth = d2->depth();
     const QGraphicsItem *p = item1;
     const QGraphicsItem *t1 = item1;
     while (item1Depth > item2Depth && (p = p->d_ptr->parent)) {
         if (p == item2) {
             // item2 is one of item1's ancestors; item1 is on top
             return !(t1->d_ptr->flags & QGraphicsItem::ItemStacksBehindParent);
         }
         t1 = p;
         --item1Depth;
     }
     p = item2;
     const QGraphicsItem *t2 = item2;
     while (item2Depth > item1Depth && (p = p->d_ptr->parent)) {
         if (p == item1) {
             // item1 is one of item2's ancestors; item1 is not on top
             return (t2->d_ptr->flags & QGraphicsItem::ItemStacksBehindParent);
         }
         t2 = p;
         --item2Depth;
     }
     // item1Ancestor is now at the same level as item2Ancestor, but not the same.
     const QGraphicsItem *p1 = t1;
     const QGraphicsItem *p2 = t2;
     while (t1 && t1 != t2) {
         p1 = t1;
         p2 = t2;
         t1 = t1->d_ptr->parent;
         t2 = t2->d_ptr->parent;
     }
     // in case we have a common ancestor, we compare the immediate children in the ancestor's path.
     // otherwise we compare the respective items' topLevelItems directly.
     return qt_closestLeaf(p1, p2);
 }
qt_closestItemLast()
bool qt_closestItemLast (const QGraphicsItem * item1, const QGraphicsItem * item2) inline
Returns true if item2 is on top of item1.
The items don't need to be siblings.
Warning
This function is not part of the public interface.
Definition at line 783 of file qgraphicsitem_p.h.
Referenced by QGraphicsSceneBspTreeIndexPrivate::sortItems().
 {
     return qt_closestItemFirst(item2, item1);
 }
qt_closestLeaf()
bool qt_closestLeaf (const QGraphicsItem * item1, const QGraphicsItem * item2) inline
Warning
This function is not part of the public interface.
Definition at line 791 of file qgraphicsitem_p.h.
Referenced by QGraphicsSceneBspTreeIndexPrivate::_q_updateSortCache(), QGraphicsSceneBspTreeIndexPrivate::climbTree(), qt_closestItemFirst(), qt_notclosestLeaf(), and QGraphicsSceneBspTreeIndexPrivate::sortItems().
 {
     // Return true if sibling item1 is on top of item2.
     const QGraphicsItemPrivate *d1 = item1->d_ptr.data();
     const QGraphicsItemPrivate *d2 = item2->d_ptr.data();
     bool f1 = d1->flags & QGraphicsItem::ItemStacksBehindParent;
     bool f2 = d2->flags & QGraphicsItem::ItemStacksBehindParent;
     if (f1 != f2)
         return f2;
     if (d1->z != d2->z)
         return d1->z > d2->z;
     return d1->siblingIndex > d2->siblingIndex;
 }
qt_notclosestLeaf()
bool qt_notclosestLeaf (const QGraphicsItem * item1, const QGraphicsItem * item2) inline
Warning
This function is not part of the public interface.
Definition at line 808 of file qgraphicsitem_p.h.
Referenced by QGraphicsItemPrivate::ensureSortedChildren(), QGraphicsScenePrivate::ensureSortedTopLevelItems(), and QGraphicsSceneBspTreeIndexPrivate::sortItems().
 { return qt_closestLeaf(item2, item1); }