Qt 4.8: /src/gui/graphicsview/qgraphicsscene_p.h File Reference
qgraphicsscene_p.h File Reference
#include "qgraphicsscene.h"
#include "qgraphicssceneevent.h"
#include "qgraphicsview.h"
#include "qgraphicsview_p.h"
#include "qgraphicsitem_p.h"
#include <private/qobject_p.h>
#include <QtCore/qbitarray.h>
#include <QtCore/qlist.h>
#include <QtCore/qmap.h>
#include <QtCore/qset.h>
#include <QtGui/qfont.h>
#include <QtGui/qpalette.h>
#include <QtGui/qstyle.h>
#include <QtGui/qstyleoption.h>
Classes
class QGraphicsScenePrivate
Functions
static void _q_adjustRect (QRectF *rect)
static QRectF adjustedItemBoundingRect (const QGraphicsItem *item)
static QRectF adjustedItemEffectiveBoundingRect (const QGraphicsItem *item)
Function Documentation
_q_adjustRect()
static void _q_adjustRect (QRectF * rect) inline static
Definition at line 330 of file qgraphicsscene_p.h.
Referenced by adjustedItemBoundingRect(), and adjustedItemEffectiveBoundingRect().
 {
     Q_ASSERT(rect);
     if (!rect->width())
         rect->adjust(qreal(-0.00001), 0, qreal(0.00001), 0);
     if (!rect->height())
         rect->adjust(0, qreal(-0.00001), 0, qreal(0.00001));
 }
adjustedItemBoundingRect()
static QRectF adjustedItemBoundingRect (const QGraphicsItem * item) inline static
Definition at line 339 of file qgraphicsscene_p.h.
Referenced by QGraphicsScenePrivate::draw().
 {
     Q_ASSERT(item);
     QRectF boundingRect(item->boundingRect());
     _q_adjustRect(&boundingRect);
     return boundingRect;
 }
adjustedItemEffectiveBoundingRect()
static QRectF adjustedItemEffectiveBoundingRect (const QGraphicsItem * item) inline static
Definition at line 347 of file qgraphicsscene_p.h.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive(), QGraphicsView::paintEvent(), and QGraphicsScenePrivate::processDirtyItemsRecursive().
 {
     Q_ASSERT(item);
     QRectF boundingRect(QGraphicsItemPrivate::get(item)->effectiveBoundingRect());
     _q_adjustRect(&boundingRect);
     return boundingRect;
 }