Qt 4.8: /src/gui/graphicsview/qgraphicslayout_p.h File Reference
qgraphicslayout_p.h File Reference
#include <QtCore/qglobal.h>
#include "qgraphicslayout.h"
#include "qgraphicslayoutitem_p.h"
#include <QtGui/qstyle.h>
#include <QtGui/qwidget.h>
#include <QtGui/qstyleoption.h>
Classes
class QGraphicsLayoutPrivate
class QLayoutStyleInfo
Functions
bool qt_graphicsLayoutDebug ()
Function Documentation
qt_graphicsLayoutDebug()
bool qt_graphicsLayoutDebug () inline
Definition at line 72 of file qgraphicslayout_p.h.
Referenced by QGraphicsLinearLayout::dump(), QGraphicsGridLayoutPrivate::dump(), QGraphicsLayoutPrivate::reparentChildItems(), QGraphicsLinearLayout::setGeometry(), and QGraphicsGridLayout::setGeometry().
 {
     static int checked_env = -1;
     if(checked_env == -1)
         checked_env = !!qgetenv("QT_GRAPHICSLAYOUT_DEBUG").toInt();
     return checked_env;
 }