Qt 4.8: /src/gui/graphicsview/qgraphicsview.cpp File Reference
qgraphicsview.cpp File Reference
#include "qgraphicsview.h"
#include "qgraphicsview_p.h"
#include "qgraphicsitem.h"
#include "qgraphicsitem_p.h"
#include "qgraphicsscene.h"
#include "qgraphicsscene_p.h"
#include "qgraphicssceneevent.h"
#include "qgraphicswidget.h"
#include <QtCore/qdatetime.h>
#include <QtCore/qdebug.h>
#include <QtCore/qmath.h>
#include <QtGui/qapplication.h>
#include <QtGui/qdesktopwidget.h>
#include <QtGui/qevent.h>
#include <QtGui/qlayout.h>
#include <QtGui/qtransform.h>
#include <QtGui/qmatrix.h>
#include <QtGui/qpainter.h>
#include <QtGui/qscrollbar.h>
#include <QtGui/qstyleoption.h>
#include <QtGui/qinputcontext.h>
#include <QtGui/qpaintengine.h>
#include <private/qt_x11_p.h>
#include <private/qevent_p.h>
#include "moc_qgraphicsview.cpp"
Functions
static bool containsViewport (const QRect &r, int width, int height)
static bool intersectsViewport (const QRect &r, int width, int height)
int q_round_bound (qreal d)
static void QRect_unite (QRect *rect, const QRect &other)
Q_AUTOTEST_EXPORT QPainterPath qt_regionToPath (const QRegion &region)
bool qt_sendSpontaneousEvent (QObject *receiver, QEvent *event)
Variables
static const int QGRAPHICSVIEW_PREALLOC_STYLE_OPTIONS = 503
static const int QGRAPHICSVIEW_REGION_RECT_THRESHOLD = 50
Function Documentation
containsViewport()
static bool containsViewport (const QRect & r, int width, int height) inline static
Definition at line 894 of file qgraphicsview.cpp.
Referenced by QGraphicsViewPrivate::updateRect().
 { return r.left() <= 0 && r.top() <= 0 && r.right() >= width - 1 && r.bottom() >= height - 1; }
intersectsViewport()
static bool intersectsViewport (const QRect & r, int width, int height) inline static
Definition at line 891 of file qgraphicsview.cpp.
Referenced by QGraphicsViewPrivate::updateRect(), and QGraphicsViewPrivate::updateRegion().
 { return !(r.left() > width) && !(r.right() < 0) && !(r.top() >= height) && !(r.bottom() < 0); }
q_round_bound()
int q_round_bound (qreal d) inline
Definition at line 313 of file qgraphicsview.cpp.
Referenced by QGraphicsViewPrivate::recalculateContentSize().
 {
     if (d <= (qreal) INT_MIN)
         return INT_MIN;
     else if (d >= (qreal) INT_MAX)
         return INT_MAX;
     return d >= 0.0 ? int(d + qreal(0.5)) : int(d - int(d-1) + qreal(0.5)) + int(d-1);
 }
QRect_unite()
static void QRect_unite (QRect * rect, const QRect & other) inline static
Definition at line 897 of file qgraphicsview.cpp.
Referenced by QGraphicsViewPrivate::updateRect().
 {
     if (rect->isEmpty()) {
         *rect = other;
     } else {
         rect->setCoords(qMin(rect->left(), other.left()), qMin(rect->top(), other.top()),
                         qMax(rect->right(), other.right()), qMax(rect->bottom(), other.bottom()));
     }
 }
qt_regionToPath()
Q_AUTOTEST_EXPORT QPainterPath qt_regionToPath (const QRegion & region)
Definition at line 1160 of file qregion.cpp.
Referenced by QGraphicsViewPrivate::findItems(), and QGraphicsViewPrivate::freeStyleOptionsArray().
 {
     QPainterPath result;
     if (region.rectCount() == 1) {
         result.addRect(region.boundingRect());
         return result;
     }
     const QVector<QRect> rects = region.rects();
     QVarLengthArray<Segment> segments;
     segments.resize(4 * rects.size());
     const QRect *rect = rects.constData();
     const QRect *end = rect + rects.size();
     int lastRowSegmentCount = 0;
     Segment *lastRowSegments = 0;
     int lastSegment = 0;
     int lastY = 0;
     while (rect != end) {
         const int y = rect[0].y();
         int count = 0;
         while (&rect[count] != end && rect[count].y() == y)
             ++count;
         for (int i = 0; i < count; ++i) {
             int offset = lastSegment + i;
             segments[offset] = Segment(rect[i].topLeft());
             segments[offset += count] = Segment(rect[i].topRight() + QPoint(1, 0));
             segments[offset += count] = Segment(rect[i].bottomRight() + QPoint(1, 1));
             segments[offset += count] = Segment(rect[i].bottomLeft() + QPoint(0, 1));
             offset = lastSegment + i;
             for (int j = 0; j < 4; ++j)
                 segments[offset + j * count].connect(segments[offset + ((j + 1) % 4) * count]);
         }
         if (lastRowSegments && lastY == y)
             mergeSegments(lastRowSegments, lastRowSegmentCount, &segments[lastSegment], count);
         lastRowSegments = &segments[lastSegment + 2 * count];
         lastRowSegmentCount = count;
         lastSegment += 4 * count;
         lastY = y + rect[0].height();
         rect += count;
     }
     for (int i = 0; i < lastSegment; ++i) {
         Segment *segment = &segments[i];
         if (!segment->added)
             addSegmentsToPath(segment, result);
     }
     return result;
 }
qt_sendSpontaneousEvent()
bool qt_sendSpontaneousEvent (QObject * receiver, QEvent * event)
Definition at line 5779 of file qapplication.cpp.
Referenced by QGraphicsView::mouseDoubleClickEvent(), QGraphicsViewPrivate::mouseMoveEventHandler(), QGraphicsView::mousePressEvent(), and QGraphicsView::mouseReleaseEvent().
 {
     return QCoreApplication::sendSpontaneousEvent(receiver, event);
 }
Variable Documentation
QGRAPHICSVIEW_PREALLOC_STYLE_OPTIONS
const int QGRAPHICSVIEW_PREALLOC_STYLE_OPTIONS = 503 static
Definition at line 44 of file qgraphicsview.cpp.
Referenced by QGraphicsViewPrivate::QGraphicsViewPrivate().
QGRAPHICSVIEW_REGION_RECT_THRESHOLD
const int QGRAPHICSVIEW_REGION_RECT_THRESHOLD = 50 static
Definition at line 42 of file qgraphicsview.cpp.
Referenced by QGraphicsView::updateScene().