Qt 4.8: /src/gui/graphicsview/qgridlayoutengine.cpp File Reference
qgridlayoutengine.cpp File Reference
#include "qglobal.h"
#include <math.h>
#include "qgraphicslayoutitem.h"
#include "qgridlayoutengine_p.h"
#include "qstyleoption.h"
#include "qvarlengtharray.h"
#include <QtDebug>
#include <QtCore/qmath.h>
Functions
static qreal compare (const QGridLayoutBox &box1, const QGridLayoutBox &box2, int which)
static qreal fixedDescent (qreal descent, qreal ascent, qreal targetSize)
static qreal growthFactorBelowPreferredSize (qreal desired, qreal sumAvailable, qreal sumDesired)
template<typename T >
static void insertOrRemoveItems (QVector< T > &items, int index, int delta)
bool operator== (const QGridLayoutBox &box1, const QGridLayoutBox &box2)
static void visualRect (QRectF *geom, Qt::LayoutDirection dir, const QRectF &contentsRect)
Function Documentation
compare()
static qreal compare (const QGridLayoutBox & box1, const QGridLayoutBox & box2, int which) static
Definition at line 90 of file qgridlayoutengine.cpp.
Referenced by QGridLayoutRowData::distributeMultiCells().
 {
     qreal size1 = box1.q_sizes(which);
     qreal size2 = box2.q_sizes(which);
     if (which == MaximumSize) {
         return size2 - size1;
     } else {
         return size1 - size2;
     }
 }
fixedDescent()
static qreal fixedDescent (qreal descent, qreal ascent, qreal targetSize) static
Definition at line 77 of file qgridlayoutengine.cpp.
Referenced by QGridLayoutRowData::calculateGeometries(), and QGridLayoutEngine::fillRowData().
 {
     if (descent < 0.0)
         return -1.0;
     Q_ASSERT(descent >= 0.0);
     Q_ASSERT(ascent >= 0.0);
     Q_ASSERT(targetSize >= ascent + descent);
     qreal extra = targetSize - (ascent + descent);
     return descent + (extra / qreal(2.0));
 }
growthFactorBelowPreferredSize()
static qreal growthFactorBelowPreferredSize (qreal desired, qreal sumAvailable, qreal sumDesired) static
Definition at line 71 of file qgridlayoutengine.cpp.
Referenced by QGridLayoutRowData::calculateGeometries().
 {
     Q_ASSERT(sumDesired != 0.0);
     return desired * qPow(sumAvailable / sumDesired, desired / sumDesired);
 }
insertOrRemoveItems()
template<typename T > static void insertOrRemoveItems (QVector< T > & items, int index, int delta) static
Definition at line 59 of file qgridlayoutengine.cpp.
Referenced by QGridLayoutRowInfo::insertOrRemoveRows().
 {
     int count = items.count();
     if (index < count) {
         if (delta > 0) {
             items.insert(index, delta, T());
         } else if (delta < 0) {
             items.remove(index, qMin(-delta, count - index));
         }
     }
 }
operator==()
bool operator== (const QGridLayoutBox & box1, const QGridLayoutBox & box2)
Definition at line 149 of file qgridlayoutengine.cpp.
Referenced by operator!=(), and QGridLayoutBox::q_sizes().
 {
     for (int i = 0; i < NSizes; ++i) {
         if (box1.q_sizes(i) != box2.q_sizes(i))
             return false;
     }
     return box1.q_minimumDescent == box2.q_minimumDescent
            && box1.q_minimumAscent == box2.q_minimumAscent;
 }
visualRect()
static void visualRect (QRectF * geom, Qt::LayoutDirection dir, const QRectF & contentsRect) static
Definition at line 1080 of file qgridlayoutengine.cpp.
Referenced by QGridLayoutEngine::setGeometries(), QWindowsMobileStyle::sizeFromContents(), and QWindowsMobileStyle::subControlRect().
 {
     if (dir == Qt::RightToLeft)
         geom->moveRight(contentsRect.right() - (geom->left() - contentsRect.left()));
 }