Qt 4.8: /src/gui/kernel/qgridlayout.cpp File Reference
qgridlayout.cpp File Reference
#include "qgridlayout.h"
#include "qapplication.h"
#include "qwidget.h"
#include "qlist.h"
#include "qsizepolicy.h"
#include "qvector.h"
#include "qvarlengtharray.h"
#include "qlayoutengine_p.h"
#include "qlayout_p.h"
Classes
class QGridBox
class QGridLayoutPrivate
struct QGridLayoutSizeTriple
Functions
static bool checkWidget (QLayout *l, QWidget *w)
static void distributeMultiBox (QVector< QLayoutStruct > &chain, int start, int end, int minSize, int sizeHint, QVector< int > &stretchArray, int stretch)
static QGridBox *& gridAt (QGridBox *grid[], int r, int c, int cc, Qt::Orientation orientation=Qt::Vertical)
static void initEmptyMultiBox (QVector< QLayoutStruct > &chain, int start, int end)
Function Documentation
checkWidget()
static bool checkWidget (QLayout * l, QWidget * w) static
Definition at line 1552 of file qgridlayout.cpp.
Referenced by QGridLayout::addWidget().
 {
     if (!w) {
         qWarning("QLayout: Cannot add null widget to %s/%s", l->metaObject()->className(),
                   l->objectName().toLocal8Bit().data());
         return false;
     }
     return true;
 }
distributeMultiBox()
static void distributeMultiBox (QVector< QLayoutStruct > & chain, int start, int end, int minSize, int sizeHint, QVector< int > & stretchArray, int stretch) static
Definition at line 617 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::setupHfwLayoutData(), and QGridLayoutPrivate::setupLayoutData().
 {
     int i;
     int w = 0;
     int wh = 0;
     int max = 0;
     for (i = start; i <= end; i++) {
         QLayoutStruct *data = &chain[i];
         w += data->minimumSize;
         wh += data->sizeHint;
         max += data->maximumSize;
         if (stretchArray.at(i) == 0)
             data->stretch = qMax(data->stretch, stretch);
         if (i != end) {
             int spacing = data->spacing;
             w += spacing;
             wh += spacing;
             max += spacing;
         }
     }
     if (max < minSize) { // implies w < minSize
         /*
           We must increase the maximum size of at least one of the
           items. qGeomCalc() will put the extra space in between the
           items. We must recover that extra space and put it
           somewhere. It does not really matter where, since the user
           can always specify stretch factors and avoid this code.
         */
         qGeomCalc(chain, start, end - start + 1, 0, minSize);
         int pos = 0;
         for (i = start; i <= end; i++) {
             QLayoutStruct *data = &chain[i];
             int nextPos = (i == end) ? minSize : chain.at(i + 1).pos;
             int realSize = nextPos - pos;
             if (i != end)
                 realSize -= data->spacing;
             if (data->minimumSize < realSize)
                 data->minimumSize = realSize;
             if (data->maximumSize < data->minimumSize)
                 data->maximumSize = data->minimumSize;
             pos = nextPos;
         }
     } else if (w < minSize) {
         qGeomCalc(chain, start, end - start + 1, 0, minSize);
         for (i = start; i <= end; i++) {
             QLayoutStruct *data = &chain[i];
             if (data->minimumSize < data->size)
                 data->minimumSize = data->size;
         }
     }
     if (wh < sizeHint) {
         qGeomCalc(chain, start, end - start + 1, 0, sizeHint);
         for (i = start; i <= end; i++) {
             QLayoutStruct *data = &chain[i];
             if (data->sizeHint < data->size)
                 data->sizeHint = data->size;
         }
     }
 }
gridAt()
static QGridBox*& gridAt (QGridBox * grid[], int r, int c, int cc, Qt::Orientation orientation = Qt::Vertical) static
Definition at line 682 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::setupLayoutData(), and QGridLayoutPrivate::setupSpacings().
 {
     if (orientation == Qt::Horizontal)
         qSwap(r, c);
     return grid[(r * cc) + c];
 }
initEmptyMultiBox()
static void initEmptyMultiBox (QVector< QLayoutStruct > & chain, int start, int end) static
Definition at line 607 of file qgridlayout.cpp.
Referenced by QGridLayoutPrivate::setupHfwLayoutData(), and QGridLayoutPrivate::setupLayoutData().
 {
     for (int i = start; i <= end; i++) {
         QLayoutStruct *data = &chain[i];
         if (data->empty && data->maximumSize == 0) // truly empty box
             data->maximumSize = QWIDGETSIZE_MAX;
         data->empty = false;
     }
 }