Qt 4.8: /src/gui/styles/qgtkpainter.cpp File Reference
qgtkpainter.cpp File Reference
#include "qgtkpainter_p.h"
#include <QtCore/qglobal.h>
#include <private/qstylehelper_p.h>
#include <QtGui/QWidget>
#include <QtGui/QStyleOption>
#include <QtGui/QPixmapCache>
Macros
#define DRAW_TO_CACHE(draw_func)
#define GTK_ALPHA 3
#define GTK_BLUE 0
#define GTK_GREEN 1
#define GTK_OBJECT_FLAGS(obj) (((GtkObject*)(obj))->flags)
#define GTK_RED 2
#define QT_ALPHA 0
#define QT_BLUE 1
#define QT_GREEN 2
#define QT_RED 3
Functions
static QString uniqueName (const QString &key, GtkStateType state, GtkShadowType shadow, const QSize &size, GtkWidget *widget=0)
Macro Definition Documentation
DRAW_TO_CACHE
#define DRAW_TO_CACHE (draw_func)
Definition at line 107 of file qgtkpainter.cpp.
Referenced by QGtkPainter::paintArrow(), QGtkPainter::paintBox(), QGtkPainter::paintBoxGap(), QGtkPainter::paintCheckbox(), QGtkPainter::paintExpander(), QGtkPainter::paintExtention(), QGtkPainter::paintFlatBox(), QGtkPainter::paintFocus(), QGtkPainter::paintHandle(), QGtkPainter::paintHline(), QGtkPainter::paintOption(), QGtkPainter::paintResizeGrip(), QGtkPainter::paintShadow(), QGtkPainter::paintSlider(), and QGtkPainter::paintVline().
GTK_ALPHA
#define GTK_ALPHA 3
Definition at line 74 of file qgtkpainter.cpp.
Referenced by QGtkPainter::getIcon().
GTK_BLUE
#define GTK_BLUE 0
Definition at line 73 of file qgtkpainter.cpp.
Referenced by QGtkPainter::getIcon(), and QGtkPainter::renderTheme().
GTK_GREEN
#define GTK_GREEN 1
Definition at line 72 of file qgtkpainter.cpp.
Referenced by QGtkPainter::getIcon(), and QGtkPainter::renderTheme().
GTK_OBJECT_FLAGS
#define GTK_OBJECT_FLAGS (obj) (((GtkObject*)(obj))->flags)
Definition at line 58 of file qgtkpainter.cpp.
GTK_RED
#define GTK_RED 2
Definition at line 71 of file qgtkpainter.cpp.
Referenced by QGtkPainter::getIcon(), and QGtkPainter::renderTheme().
QT_ALPHA
#define QT_ALPHA 0
Definition at line 64 of file qgtkpainter.cpp.
Referenced by QGtkPainter::getIcon(), and QGtkPainter::renderTheme().
QT_BLUE
#define QT_BLUE 1
Definition at line 63 of file qgtkpainter.cpp.
Referenced by QGtkPainter::getIcon(), and QGtkPainter::renderTheme().
QT_GREEN
#define QT_GREEN 2
Definition at line 62 of file qgtkpainter.cpp.
Referenced by QGtkPainter::getIcon(), and QGtkPainter::renderTheme().
QT_RED
#define QT_RED 3
Definition at line 61 of file qgtkpainter.cpp.
Referenced by QGtkPainter::getIcon(), and QGtkPainter::renderTheme().
Function Documentation
uniqueName()
static QString uniqueName (const QString & key, GtkStateType state, GtkShadowType shadow, const QSize & size, GtkWidget * widget = 0) static
Definition at line 155 of file qgtkpainter.cpp.
Referenced by QGtkPainter::paintArrow(), QGtkPainter::paintBox(), QGtkPainter::paintBoxGap(), QGtkPainter::paintCheckbox(), QGtkPainter::paintExpander(), QGtkPainter::paintExtention(), QGtkPainter::paintFlatBox(), QGtkPainter::paintFocus(), QGtkPainter::paintHandle(), QGtkPainter::paintHline(), QGtkPainter::paintOption(), QGtkPainter::paintResizeGrip(), QGtkPainter::paintShadow(), QGtkPainter::paintSlider(), and QGtkPainter::paintVline().
 {
     // Note the widget arg should ideally use the widget path, though would compromise performance
     QString tmp = key
                   % HexString<uint>(state)
                   % HexString<uint>(shadow)
                   % HexString<uint>(size.width())
                   % HexString<uint>(size.height())
                   % HexString<quint64>(quint64(widget));
     return tmp;
 }