Qt 4.8: /src/gui/styles/qgtkstyle_p.cpp File Reference
qgtkstyle_p.cpp File Reference
#include "qgtkstyle_p.h"
#include <QtCore/qglobal.h>
#include <QtCore/QEvent>
#include <QtCore/QFile>
#include <QtCore/QStringList>
#include <QtCore/QTextStream>
#include <QtCore/QHash>
#include <QtCore/QUrl>
#include <QtCore/QLibrary>
#include <QtCore/QDebug>
#include <private/qapplication_p.h>
#include <private/qiconloader_p.h>
#include <QtGui/QMenu>
#include <QtGui/QStyle>
#include <QtGui/QApplication>
#include <QtGui/QPixmapCache>
#include <QtGui/QStatusBar>
#include <QtGui/QMenuBar>
#include <QtGui/QToolBar>
#include <QtGui/QToolButton>
#include <QtGui/QX11Info>
#include <private/qt_x11_p.h>
Typedefs
typedef int(* x11ErrorHandler) (Display *, XErrorEvent *)
Functions
static QHashableLatin1Literal classPath (GtkWidget *widget)
static void gtkStyleSetCallback (GtkWidget *)
bool operator== (const QHashableLatin1Literal &l1, const QHashableLatin1Literal &l2)
Q_DECLARE_METATYPE (QGtkStylePrivate *)
uint qHash (const QHashableLatin1Literal &key)
QStringList qt_make_filter_list (const QString &filter)
static bool resolveGConf ()
static void update_toolbar_style (GtkWidget *gtkToolBar, GParamSpec *, gpointer)
Variables
static bool displayDepth = -1
Typedef Documentation
x11ErrorHandler
typedef int(* x11ErrorHandler) (Display *, XErrorEvent *)
Definition at line 207 of file qgtkstyle_p.cpp.
Function Documentation
classPath()
static QHashableLatin1Literal classPath (GtkWidget * widget) static
Definition at line 239 of file qgtkstyle_p.cpp.
Referenced by QGtkStylePrivate::addWidgetToMap().
 {
     char *class_path;
     QGtkStylePrivate::gtk_widget_path (widget, NULL, &class_path, NULL);
     char *copy = class_path;
     if (strncmp(copy, "GtkWindow.", 10) == 0)
         copy += 10;
     if (strncmp(copy, "GtkFixed.", 9) == 0)
         copy += 9;
     copy = strdup(copy);
     g_free(class_path);
     return QHashableLatin1Literal::fromData(copy);
 }
gtkStyleSetCallback()
static void gtkStyleSetCallback (GtkWidget *) static
Definition at line 215 of file qgtkstyle_p.cpp.
Referenced by QGtkStylePrivate::initGtkWidgets().
 {
     qRegisterMetaType<QGtkStylePrivate *>();
     // We have to let this function return and complete the event
     // loop to ensure that all gtk widgets have been styled before
     // updating
     QMetaObject::invokeMethod(styleScheduler(), "updateTheme", Qt::QueuedConnection);
 }
operator==()
bool operator== (const QHashableLatin1Literal & l1, const QHashableLatin1Literal & l2)
Definition at line 1142 of file qgtkstyle_p.cpp.
Referenced by operator!=().
 {
     return l1.size() == l2.size() || qstrcmp(l1.data(), l2.data()) == 0;
 }
Q_DECLARE_METATYPE()
Q_DECLARE_METATYPE (QGtkStylePrivate *)
qHash()
uint qHash (const QHashableLatin1Literal & key)
Definition at line 1148 of file qgtkstyle_p.cpp.
Referenced by operator!=().
 {
     int n = key.size();
     const uchar *p = reinterpret_cast<const uchar *>(key.data());
     uint h = 0;
     uint g;
     while (n--) {
         h = (h << 4) + *p++;
         if ((g = (h & 0xf0000000)) != 0)
             h ^= g >> 23;
         h &= ~g;
     }
     return h;
 }
qt_make_filter_list()
QStringList qt_make_filter_list (const QString & filter)
Definition at line 1075 of file qfiledialog.cpp.
Referenced by QGtkStylePrivate::extract_filter(), QFileDialog::selectNameFilter(), QFileDialog::setNameFilter(), and QGtkStylePrivate::setupGtkFileChooser().
 {
     QString f(filter);
     if (f.isEmpty())
         return QStringList();
     QString sep(QLatin1String(";;"));
     int i = f.indexOf(sep, 0);
     if (i == -1) {
         if (f.indexOf(QLatin1Char('\n'), 0) != -1) {
             sep = QLatin1Char('\n');
             i = f.indexOf(sep, 0);
         }
     }
     return f.split(sep);
 }
resolveGConf()
static bool resolveGConf () static
Definition at line 605 of file qgtkstyle_p.cpp.
Referenced by QGtkStylePrivate::getGConfBool(), QGtkStylePrivate::getGConfString(), and QGtkStylePrivate::getThemeName().
 {
     if (!QGtkStylePrivate::gconf_client_get_default) {
         QGtkStylePrivate::gconf_client_get_default = (Ptr_gconf_client_get_default)QLibrary::resolve(QLS("gconf-2"), 4, "gconf_client_get_default");
         QGtkStylePrivate::gconf_client_get_string =  (Ptr_gconf_client_get_string)QLibrary::resolve(QLS("gconf-2"), 4, "gconf_client_get_string");
         QGtkStylePrivate::gconf_client_get_bool =  (Ptr_gconf_client_get_bool)QLibrary::resolve(QLS("gconf-2"), 4, "gconf_client_get_bool");
     }
     return (QGtkStylePrivate::gconf_client_get_default !=0);
 }
update_toolbar_style()
static void update_toolbar_style (GtkWidget * gtkToolBar, GParamSpec * , gpointer) static
Definition at line 225 of file qgtkstyle_p.cpp.
Referenced by QGtkStylePrivate::initGtkWidgets().
 {
     GtkToolbarStyle toolbar_style = GTK_TOOLBAR_ICONS;
     g_object_get(gtkToolBar, "toolbar-style", &toolbar_style, NULL);
     QWidgetList widgets = QApplication::allWidgets();
     for (int i = 0; i < widgets.size(); ++i) {
         QWidget *widget = widgets.at(i);
         if (qobject_cast<QToolButton*>(widget)) {
             QEvent event(QEvent::StyleChange);
             QApplication::sendEvent(widget, &event);
         }
     }
 }
Variable Documentation
displayDepth
bool displayDepth = -1 static
Definition at line 82 of file qgtkstyle_p.cpp.
Referenced by QGtkStylePrivate::initGtkWidgets().