Qt 4.8: /src/gui/kernel/qguiplatformplugin.cpp File Reference
qguiplatformplugin.cpp File Reference
#include "qguiplatformplugin_p.h"
#include <qdebug.h>
#include <qfile.h>
#include <qdir.h>
#include <qsettings.h>
#include "private/qfactoryloader_p.h"
#include "qstylefactory.h"
#include "qapplication.h"
#include "qplatformdefs.h"
#include "qicon.h"
#include "qguifunctions_wince.h"
#include <private/qkde_p.h>
#include <private/qgtkstyle_p.h>
#include <private/qt_x11_p.h>
Functions
QGuiPlatformPlugin * qt_guiPlatformPlugin ()
Return (an construct if necesseray) the Gui Platform plugin.
bool qt_wince_is_mobile ()
bool qt_wince_is_pocket_pc ()
bool qt_wince_is_smartphone ()
Function Documentation
qt_guiPlatformPlugin()
QGuiPlatformPlugin* qt_guiPlatformPlugin ()
Return (an construct if necesseray) the Gui Platform plugin.
Warning
This function is not part of the public interface.
The plugin key to be loaded is inside the QT_PLATFORM_PLUGIN environment variable. If it is not set, it will be the DESKTOP_SESSION on X11.
If no plugin can be loaded, the default one is returned.
Definition at line 82 of file qguiplatformplugin.cpp.
Referenced by QGuiPlatformPlugin::colorDialogSetCurrentColor(), QApplicationPrivate::desktopStyleKey(), QIconLoader::ensureInitialized(), QFileIconProvider::icon(), QCommonStyle::pixelMetric(), QFileDialogPrivate::rootPath(), QColorDialog::setCurrentColor(), QColorDialog::setVisible(), QCommonStyle::styleHint(), QIconLoader::themeSearchPaths(), QIconLoader::updateSystemTheme(), QApplicationPrivate::x11_apply_settings(), and QColorDialog::~QColorDialog().
 {
     static QGuiPlatformPlugin *plugin;
     if (!plugin)
     {
 #ifndef QT_NO_LIBRARY
         QString key = QString::fromLocal8Bit(qgetenv("QT_PLATFORM_PLUGIN"));
 #ifdef Q_WS_X11
         if (key.isEmpty()) {
             switch(X11->desktopEnvironment) {
             case DE_KDE:
                 key = QString::fromLatin1("kde");
                 break;
             default:
                 key = QString::fromLocal8Bit(qgetenv("DESKTOP_SESSION"));
                 break;
             }
         }
 #endif
         if (!key.isEmpty() && QApplication::desktopSettingsAware()) {
             QFactoryLoader loader(QGuiPlatformPluginInterface_iid, QLatin1String("/gui_platform"));
             plugin = qobject_cast<QGuiPlatformPlugin *>(loader.instance(key));
         }
 #endif // QT_NO_LIBRARY
         if(!plugin) {
             static QGuiPlatformPlugin def;
             plugin = &def;
         }
     }
     return plugin;
 }
qt_wince_is_mobile()
bool qt_wince_is_mobile ()
Definition at line 296 of file qguifunctions_wince.cpp.
{
      return (qt_wince_is_smartphone() || qt_wince_is_pocket_pc());
 }
qt_wince_is_pocket_pc()
bool qt_wince_is_pocket_pc ()
Definition at line 289 of file qguifunctions_wince.cpp.
Referenced by QGuiPlatformPlugin::styleName().
{
     return qt_wince_is_platform(QString::fromLatin1("PocketPC"));
 }
qt_wince_is_smartphone()
bool qt_wince_is_smartphone ()
Definition at line 293 of file qguifunctions_wince.cpp.
Referenced by QGuiPlatformPlugin::styleName().
{
        return qt_wince_is_platform(QString::fromLatin1("Smartphone"));
 }