Qt 4.8: /src/gui/kernel/qguifunctions_wince.cpp File Reference
qguifunctions_wince.cpp File Reference
#include "qguifunctions_wince.h"
#include <shellapi.h>
#include <QtCore/qlibrary.h>
Classes
struct AygSHINITDLGINFO
struct AygSIPINFO
Macros
#define SHDB_HIDE 0x0002
#define SHFS_HIDESIPBUTTON 0x0008
#define SHFS_HIDESTARTICON 0x0020
#define SHFS_HIDETASKBAR 0x0002
#define SHFS_SHOWSIPBUTTON 0x0004
#define SHFS_SHOWSTARTICON 0x0010
#define SHFS_SHOWTASKBAR 0x0001
#define SHIDIF_CANCELBUTTON 0x0080
#define SHIDIF_DONEBUTTON 0x0001
#define SHIDIF_SIZEDLGFULLSCREEN 0x0004
#define SHIDIM_FLAGS 0x0001
#define SIPF_OFF 0x00000000
#define SIPF_ON 0x00000001
#define SPI_GETPLATFORMTYPE 257
#define SPI_GETSIPINFO 225
#define SPI_SETSIPINFO 224
Typedefs
typedef BOOL(* AygFullScreen) (HWND, DWORD)
typedef BOOL(* AygInitDialog) (AygSHINITDLGINFO *)
typedef BOOL(* AygSHDoneButton) (HWND, DWORD)
typedef BOOL(* AygSHSipInfo) (UINT, UINT, PVOID, UINT)
Functions
BOOL qt_wince_ChangeClipboardChain (HWND, HWND)
void qt_wince_full_screen (HWND hwnd, bool fullScreen, UINT swpf)
int qt_wince_get_build ()
int qt_wince_get_version ()
int qt_wince_GetDIBits (HDC, HBITMAP hSourceBitmap, uint, uint, LPVOID lpvBits, LPBITMAPINFO, uint)
void qt_wince_hide_taskbar (HWND hwnd)
bool qt_wince_is_high_dpi ()
bool qt_wince_is_mobile ()
bool qt_wince_is_platform (const QString &platformString)
bool qt_wince_is_pocket_pc ()
bool qt_wince_is_smartphone ()
bool qt_wince_is_windows_mobile_65 ()
void qt_wince_maximize (QWidget *widget)
void qt_wince_minimize (HWND hwnd)
COLORREF qt_wince_PALETTEINDEX (WORD)
HWND qt_wince_SetClipboardViewer (HWND)
HINSTANCE qt_wince_ShellExecute (HWND hwnd, LPCWSTR, LPCWSTR file, LPCWSTR params, LPCWSTR dir, int showCmd)
void qt_wince_show_SIP (bool show)
void qt_wince_unmaximize (QWidget *widget)
static void resolveAygLibs ()
Variables
static AygFullScreen ptrAygFullScreen = 0
static AygInitDialog ptrAygInitDialog = 0
static AygSHDoneButton ptrAygSHDoneButton = 0
static AygSHSipInfo ptrAygSHSipInfo = 0
Macro Definition Documentation
SHDB_HIDE
#define SHDB_HIDE 0x0002
Definition at line 80 of file qguifunctions_wince.cpp.
Referenced by qt_wince_unmaximize().
SHFS_HIDESIPBUTTON
#define SHFS_HIDESIPBUTTON 0x0008
Definition at line 93 of file qguifunctions_wince.cpp.
Referenced by qt_wince_full_screen(), and qt_wince_hide_taskbar().
SHFS_HIDESTARTICON
#define SHFS_HIDESTARTICON 0x0020
Definition at line 99 of file qguifunctions_wince.cpp.
Referenced by qt_wince_full_screen(), and qt_wince_hide_taskbar().
SHFS_HIDETASKBAR
#define SHFS_HIDETASKBAR 0x0002
Definition at line 87 of file qguifunctions_wince.cpp.
Referenced by qt_wince_full_screen(), and qt_wince_hide_taskbar().
SHFS_SHOWSIPBUTTON
#define SHFS_SHOWSIPBUTTON 0x0004
Definition at line 90 of file qguifunctions_wince.cpp.
Referenced by qt_wince_full_screen().
SHFS_SHOWSTARTICON
#define SHFS_SHOWSTARTICON 0x0010
Definition at line 96 of file qguifunctions_wince.cpp.
Referenced by qt_wince_full_screen().
SHFS_SHOWTASKBAR
#define SHFS_SHOWTASKBAR 0x0001
Definition at line 84 of file qguifunctions_wince.cpp.
Referenced by qt_wince_full_screen().
SHIDIF_CANCELBUTTON
#define SHIDIF_CANCELBUTTON 0x0080
Definition at line 65 of file qguifunctions_wince.cpp.
Referenced by qt_wince_maximize().
SHIDIF_DONEBUTTON
#define SHIDIF_DONEBUTTON 0x0001
Definition at line 73 of file qguifunctions_wince.cpp.
Referenced by qt_wince_maximize().
SHIDIF_SIZEDLGFULLSCREEN
#define SHIDIF_SIZEDLGFULLSCREEN 0x0004
Definition at line 76 of file qguifunctions_wince.cpp.
Referenced by qt_wince_maximize().
SHIDIM_FLAGS
#define SHIDIM_FLAGS 0x0001
Definition at line 69 of file qguifunctions_wince.cpp.
Referenced by qt_wince_maximize().
SIPF_OFF
#define SIPF_OFF 0x00000000
Definition at line 103 of file qguifunctions_wince.cpp.
Referenced by qt_wince_show_SIP().
SIPF_ON
#define SIPF_ON 0x00000001
Definition at line 106 of file qguifunctions_wince.cpp.
Referenced by qt_wince_show_SIP().
SPI_GETPLATFORMTYPE
#define SPI_GETPLATFORMTYPE 257
Definition at line 116 of file qguifunctions_wince.cpp.
Referenced by qt_wince_is_platform().
SPI_GETSIPINFO
#define SPI_GETSIPINFO 225
Definition at line 113 of file qguifunctions_wince.cpp.
Referenced by qt_wince_show_SIP().
SPI_SETSIPINFO
#define SPI_SETSIPINFO 224
Definition at line 110 of file qguifunctions_wince.cpp.
Referenced by qt_wince_show_SIP().
Typedef Documentation
AygFullScreen
typedef BOOL(* AygFullScreen) (HWND, DWORD)
Definition at line 120 of file qguifunctions_wince.cpp.
AygInitDialog
typedef BOOL(* AygInitDialog) (AygSHINITDLGINFO *)
Definition at line 119 of file qguifunctions_wince.cpp.
AygSHDoneButton
typedef BOOL(* AygSHDoneButton) (HWND, DWORD)
Definition at line 122 of file qguifunctions_wince.cpp.
AygSHSipInfo
typedef BOOL(* AygSHSipInfo) (UINT, UINT, PVOID, UINT)
Definition at line 121 of file qguifunctions_wince.cpp.
Function Documentation
qt_wince_ChangeClipboardChain()
BOOL qt_wince_ChangeClipboardChain (HWND , HWND)
Definition at line 231 of file qguifunctions_wince.cpp.
 {
     return FALSE;
 }
qt_wince_full_screen()
void qt_wince_full_screen (HWND hwnd, bool fullScreen, UINT swpf)
Definition at line 366 of file qguifunctions_wince.cpp.
Referenced by qt_tablet_cleanup_wce().
{
     resolveAygLibs();
     if (fullScreen) {
         QRect r = qApp->desktop()->screenGeometry(QWidget::find(hwnd));
         SetWindowPos(hwnd, HWND_TOP, r.left(), r.top(), r.width(), r.height(), swpf);
         if (ptrAygFullScreen)
             ptrAygFullScreen(hwnd, SHFS_HIDETASKBAR | SHFS_HIDESIPBUTTON | SHFS_HIDESTARTICON);
         if (!qt_wince_is_mobile()) {
             HWND handle = FindWindow(L"HHTaskBar", L"");
             if (handle) {
                 ShowWindow(handle, 0);
                 EnableWindow(handle, false);
             }
         }
     } else {
         if (ptrAygFullScreen)
             ptrAygFullScreen(hwnd, SHFS_SHOWTASKBAR | SHFS_SHOWSIPBUTTON | SHFS_SHOWSTARTICON);
         SetWindowPos(hwnd, 0, 0, 0, 0, 0, swpf);
         if (!qt_wince_is_mobile()) {
             HWND handle = FindWindow(L"HHTaskBar", L"");
             if (handle) {
                 ShowWindow(handle, 1);
                 EnableWindow(handle, true);
             }
         }
     }
 }
qt_wince_get_build()
int qt_wince_get_build ()
Definition at line 257 of file qguifunctions_wince.cpp.
 {
     OSVERSIONINFO osvi;
     osvi.dwOSVersionInfoSize = sizeof(osvi);
     if (GetVersionEx(&osvi)) {
         return osvi.dwBuildNumber;
     }
     return 0;
 }
qt_wince_get_version()
int qt_wince_get_version ()
Definition at line 267 of file qguifunctions_wince.cpp.
 {
     OSVERSIONINFO osvi;
     osvi.dwOSVersionInfoSize = sizeof(osvi);
     if (GetVersionEx(&osvi)) {
         return (osvi.dwMajorVersion * 10 + osvi.dwMinorVersion);
     }
     return 0;
 }
qt_wince_GetDIBits()
int qt_wince_GetDIBits (HDC , HBITMAP hSourceBitmap, uint , uint , LPVOID lpvBits, LPBITMAPINFO , uint)
Definition at line 141 of file qguifunctions_wince.cpp.
 {
     if (!lpvBits) {
         qWarning("::GetDIBits(), lpvBits NULL");
         return 0;
     }
     BITMAP bm;
     GetObject(hSourceBitmap, sizeof(BITMAP), &bm);
     bm.bmHeight = qAbs(bm.bmHeight);
     HBITMAP hTargetBitmap;
     void *pixels;
     BITMAPINFO dibInfo;
     memset(&dibInfo, 0, sizeof(dibInfo));
     dibInfo.bmiHeader.biBitCount = 32;
     dibInfo.bmiHeader.biClrImportant = 0;
     dibInfo.bmiHeader.biClrUsed = 0;
     dibInfo.bmiHeader.biCompression = BI_RGB;;
     dibInfo.bmiHeader.biHeight = -bm.bmHeight;
     dibInfo.bmiHeader.biWidth = bm.bmWidth;
     dibInfo.bmiHeader.biPlanes = 1;
     dibInfo.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
     dibInfo.bmiHeader.biSizeImage = bm.bmWidth * bm.bmHeight * 4;
     HDC displayDC = GetDC(NULL);
     if (!displayDC) {
         qWarning("::GetDIBits(), failed to GetDC");
         return 0;
     }
     int ret = bm.bmHeight;
     hTargetBitmap = CreateDIBSection(displayDC, (const BITMAPINFO*) &dibInfo, DIB_RGB_COLORS,
                                     (void**)&pixels, NULL, 0);
     if (!hTargetBitmap) {
         qWarning("::GetDIBits(), failed to CreateDIBSection");
         return 0;
     }
     HDC hdcSrc = CreateCompatibleDC(displayDC);
     HDC hdcDst = CreateCompatibleDC(displayDC);
     if (!(hdcDst && hdcSrc)) {
         qWarning("::GetDIBits(), failed to CreateCompatibleDC");
         ret = 0;
     }
     HBITMAP hOldBitmap1 = (HBITMAP) SelectObject(hdcSrc, hSourceBitmap);
     HBITMAP hOldBitmap2 = (HBITMAP) SelectObject(hdcDst, hTargetBitmap);
     if (!(hOldBitmap1 && hOldBitmap2)) {
         qWarning("::GetDIBits(), failed to SelectObject for bitmaps");
         ret = 0;
     }
     if (!BitBlt(hdcDst, 0, 0, bm.bmWidth, bm.bmHeight, hdcSrc, 0, 0, SRCCOPY)) {
         qWarning("::GetDIBits(), BitBlt failed");
         ret = 0;
     }
     SelectObject(hdcSrc, hOldBitmap1);
     SelectObject(hdcDst, hOldBitmap2);
     DeleteDC(hdcSrc);
     DeleteDC(hdcDst);
     ReleaseDC(NULL, displayDC);
     memcpy(lpvBits, pixels, dibInfo.bmiHeader.biSizeImage);
     DeleteObject(hTargetBitmap);
     return ret;
 }
qt_wince_hide_taskbar()
void qt_wince_hide_taskbar (HWND hwnd)
Definition at line 361 of file qguifunctions_wince.cpp.
Referenced by QtWndProc(), and QETWidget::translateConfigEvent().
{
     if (ptrAygFullScreen)
         ptrAygFullScreen(hwnd, SHFS_HIDETASKBAR | SHFS_HIDESIPBUTTON | SHFS_HIDESTARTICON);
 }
qt_wince_is_high_dpi()
bool qt_wince_is_high_dpi ()
Definition at line 300 of file qguifunctions_wince.cpp.
Referenced by QErrorMessageTextView::minimumSizeHint(), QWindowsMobileStylePrivate::QWindowsMobileStylePrivate(), and QErrorMessageTextView::sizeHint().
{
     if (!qt_wince_is_pocket_pc())
         return false;
     HDC deviceContext = GetDC(0);
     int dpi = GetDeviceCaps(deviceContext, LOGPIXELSX);
     ReleaseDC(0, deviceContext);
     if ((dpi < 1000) && (dpi > 0))
         return dpi > 96;
     else
         return false;
 }
qt_wince_is_mobile()
bool qt_wince_is_mobile ()
Definition at line 296 of file qguifunctions_wince.cpp.
Referenced by QMenuBarPrivate::handleReparent(), QMenuBarPrivate::init(), QErrorMessageTextView::minimumSizeHint(), QDialog::QDialog(), qt_grab_cursor(), qt_set_windows_font_resources(), qt_tablet_cleanup_wce(), qt_wince_full_screen(), qt_wince_maximize(), qt_wince_unmaximize(), QWizard::QWizard(), QMenuBar::setDefaultAction(), QErrorMessageTextView::sizeHint(), and QMenuBar::~QMenuBar().
{
      return (qt_wince_is_smartphone() || qt_wince_is_pocket_pc());
 }
qt_wince_is_platform()
bool qt_wince_is_platform (const QString & platformString)
Definition at line 249 of file qguifunctions_wince.cpp.
Referenced by qt_wince_is_pocket_pc(), and qt_wince_is_smartphone().
{
     wchar_t tszPlatform[64];
     if (SystemParametersInfo(SPI_GETPLATFORMTYPE, sizeof(tszPlatform) / sizeof(wchar_t), tszPlatform, 0))
         if (0 == _tcsicmp(reinterpret_cast<const wchar_t *> (platformString.utf16()), tszPlatform))
             return true;
     return false;
 }
qt_wince_is_pocket_pc()
bool qt_wince_is_pocket_pc ()
Definition at line 289 of file qguifunctions_wince.cpp.
Referenced by qt_set_windows_color_resources(), qt_wince_is_high_dpi(), qt_wince_is_mobile(), QGuiPlatformPlugin::styleName(), and QMenuBarPrivate::wceCreateMenuBar().
{
     return qt_wince_is_platform(QString::fromLatin1("PocketPC"));
 }
qt_wince_is_smartphone()
bool qt_wince_is_smartphone ()
Definition at line 293 of file qguifunctions_wince.cpp.
Referenced by QDialog::exec(), QDialog::QDialog(), qt_set_windows_color_resources(), qt_wince_is_mobile(), QWindowsMobileStylePrivate::QWindowsMobileStylePrivate(), QGuiPlatformPlugin::styleName(), and QMenuBarPrivate::wceCreateMenuBar().
{
        return qt_wince_is_platform(QString::fromLatin1("Smartphone"));
 }
qt_wince_is_windows_mobile_65()
bool qt_wince_is_windows_mobile_65 ()
Definition at line 277 of file qguifunctions_wince.cpp.
Referenced by QWindowsMobileStylePrivate::setupWindowsMobileStyle65().
 {
     const DWORD dwFirstWM65BuildNumber = 21139;
     OSVERSIONINFO osvi;
     osvi.dwOSVersionInfoSize = sizeof(osvi);
     if (!GetVersionEx(&osvi))
         return false;
     return osvi.dwMajorVersion > 5
         || (osvi.dwMajorVersion == 5 && (osvi.dwMinorVersion > 2 ||
             (osvi.dwMinorVersion == 2 && osvi.dwBuildNumber >= dwFirstWM65BuildNumber)));
 }
qt_wince_maximize()
void qt_wince_maximize (QWidget * widget)
Definition at line 312 of file qguifunctions_wince.cpp.
Referenced by qt_grab_cursor(), and qt_tablet_cleanup_wce().
 {
     HWND hwnd = widget->winId();
     if (qt_wince_is_mobile()) {
         AygSHINITDLGINFO shidi;
         shidi.dwMask = SHIDIM_FLAGS;
         shidi.hDlg = hwnd;
         shidi.dwFlags = SHIDIF_SIZEDLGFULLSCREEN;
         if (widget->windowFlags() & Qt::WindowCancelButtonHint)
             shidi.dwFlags |= SHIDIF_CANCELBUTTON;
         if (widget->windowFlags() & Qt::WindowOkButtonHint)
             shidi.dwFlags |= SHIDIF_DONEBUTTON;
         if (!(widget->windowFlags() & (Qt::WindowCancelButtonHint | Qt::WindowOkButtonHint)))
             shidi.dwFlags |= SHIDIF_CANCELBUTTON;
         resolveAygLibs();
         if (ptrAygInitDialog)
             ptrAygInitDialog(&shidi);
     } else {
         RECT r;
         SystemParametersInfo(SPI_GETWORKAREA, 0, &r, 0);
         MoveWindow(hwnd, r.top, r.left, r.right - r.left, r.bottom - r.top, true);
         SetWindowLong(hwnd, GWL_EXSTYLE, GetWindowLong (hwnd, GWL_EXSTYLE) | WS_EX_NODRAG);
     }
 }
qt_wince_minimize()
void qt_wince_minimize (HWND hwnd)
Definition at line 347 of file qguifunctions_wince.cpp.
Referenced by qt_tablet_cleanup_wce().
 {
 #ifdef Q_OS_WINCE_WM
     ShowWindow(hwnd, SW_HIDE);
 #else
     if (!IsWindowVisible(hwnd)) {
         // Hack for an initial showMinimized.
         // Without it, our widget doesn't appear in the task bar.
         ShowWindow(hwnd, SW_SHOW);
     }
     ShowWindow(hwnd, SW_MINIMIZE);
 #endif
 }
qt_wince_PALETTEINDEX()
COLORREF qt_wince_PALETTEINDEX (WORD)
Definition at line 243 of file qguifunctions_wince.cpp.
 {
     return 0;
 }
qt_wince_SetClipboardViewer()
HWND qt_wince_SetClipboardViewer (HWND)
Definition at line 236 of file qguifunctions_wince.cpp.
 {
     return NULL;
 }
qt_wince_ShellExecute()
HINSTANCE qt_wince_ShellExecute (HWND hwnd, LPCWSTR , LPCWSTR file, LPCWSTR params, LPCWSTR dir, int showCmd)
Definition at line 216 of file qguifunctions_wince.cpp.
 {
     SHELLEXECUTEINFO info;
     info.hwnd = hwnd;
     info.lpVerb = L"Open";
     info.lpFile = file;
     info.lpParameters = params;
     info.lpDirectory = dir;
     info.nShow = showCmd;
     info.cbSize = sizeof(info);
     ShellExecuteEx(&info);
     return info.hInstApp;
 }
qt_wince_show_SIP()
void qt_wince_show_SIP (bool show)
Definition at line 394 of file qguifunctions_wince.cpp.
Referenced by enableIme().
 {
     resolveAygLibs();
     if (!ptrAygSHSipInfo)
         return;
     AygSIPINFO si;
     memset(&si, 0, sizeof(si));
     si.cbSize = sizeof(si);
     ptrAygSHSipInfo(SPI_GETSIPINFO, 0, &si, 0);
     si.cbSize = sizeof(si);
     si.fdwFlags = (show ? SIPF_ON : SIPF_OFF);
     ptrAygSHSipInfo(SPI_SETSIPINFO, 0, &si, 0);
 }
qt_wince_unmaximize()
void qt_wince_unmaximize (QWidget * widget)
Definition at line 337 of file qguifunctions_wince.cpp.
Referenced by qt_tablet_cleanup_wce().
 {
     if (ptrAygSHDoneButton && qt_wince_is_mobile()
         && !(widget->windowFlags() & (Qt::WindowCancelButtonHint | Qt::WindowOkButtonHint)))
     {
         // Hide the [X] button, we've added in qt_wince_maximize.
         ptrAygSHDoneButton(widget->winId(), SHDB_HIDE);
     }
 }
resolveAygLibs()
static void resolveAygLibs () static
Definition at line 128 of file qguifunctions_wince.cpp.
Referenced by qt_wince_full_screen(), qt_wince_maximize(), and qt_wince_show_SIP().
 {
     static bool aygResolved = false;
     if (!aygResolved) {
         QLibrary ayglib(QLatin1String("aygshell"));
         ptrAygInitDialog = (AygInitDialog) ayglib.resolve("SHInitDialog");
         ptrAygFullScreen = (AygFullScreen) ayglib.resolve("SHFullScreen");
         ptrAygSHSipInfo  = (AygSHSipInfo)  ayglib.resolve("SHSipInfo");
         ptrAygSHDoneButton = (AygSHDoneButton) ayglib.resolve("SHDoneButton");
         aygResolved = true;
     }
 }
Variable Documentation
ptrAygFullScreen
AygFullScreen ptrAygFullScreen = 0 static
Definition at line 125 of file qguifunctions_wince.cpp.
Referenced by qt_wince_full_screen(), qt_wince_hide_taskbar(), and resolveAygLibs().
ptrAygInitDialog
AygInitDialog ptrAygInitDialog = 0 static
Definition at line 124 of file qguifunctions_wince.cpp.
Referenced by qt_wince_maximize(), and resolveAygLibs().
ptrAygSHDoneButton
AygSHDoneButton ptrAygSHDoneButton = 0 static
Definition at line 127 of file qguifunctions_wince.cpp.
Referenced by qt_wince_unmaximize(), and resolveAygLibs().
ptrAygSHSipInfo
AygSHSipInfo ptrAygSHSipInfo = 0 static
Definition at line 126 of file qguifunctions_wince.cpp.
Referenced by qt_wince_show_SIP(), and resolveAygLibs().