Qt 4.8: /src/gui/kernel/qguiplatformplugin_p.h File Reference
qguiplatformplugin_p.h File Reference
#include <QtCore/qplugin.h>
#include <QtCore/qfactoryinterface.h>
#include <QtGui/qdialog.h>
Classes
class QGuiPlatformPlugin
struct QGuiPlatformPluginInterface
Macros
#define QGuiPlatformPluginInterface_iid "com.nokia.qt.QGuiPlatformPluginInterface"
Functions
QGuiPlatformPlugin * qt_guiPlatformPlugin ()
Return (an construct if necesseray) the Gui Platform plugin.
Macro Definition Documentation
QGuiPlatformPluginInterface_iid
#define QGuiPlatformPluginInterface_iid "com.nokia.qt.QGuiPlatformPluginInterface"
Definition at line 77 of file qguiplatformplugin_p.h.
Referenced by qt_guiPlatformPlugin().
Function Documentation
qt_guiPlatformPlugin()
QGuiPlatformPlugin* qt_guiPlatformPlugin ()
Return (an construct if necesseray) the Gui Platform plugin.
Warning
This function is not part of the public interface.
The plugin key to be loaded is inside the QT_PLATFORM_PLUGIN environment variable. If it is not set, it will be the DESKTOP_SESSION on X11.
If no plugin can be loaded, the default one is returned.
Definition at line 82 of file qguiplatformplugin.cpp.
Referenced by QGuiPlatformPlugin::colorDialogSetCurrentColor(), QApplicationPrivate::desktopStyleKey(), QIconLoader::ensureInitialized(), QFileIconProvider::icon(), QCommonStyle::pixelMetric(), QFileDialogPrivate::rootPath(), QColorDialog::setCurrentColor(), QColorDialog::setVisible(), QCommonStyle::styleHint(), QIconLoader::themeSearchPaths(), QIconLoader::updateSystemTheme(), QApplicationPrivate::x11_apply_settings(), and QColorDialog::~QColorDialog().
 {
     static QGuiPlatformPlugin *plugin;
     if (!plugin)
     {
 #ifndef QT_NO_LIBRARY
         QString key = QString::fromLocal8Bit(qgetenv("QT_PLATFORM_PLUGIN"));
 #ifdef Q_WS_X11
         if (key.isEmpty()) {
             switch(X11->desktopEnvironment) {
             case DE_KDE:
                 key = QString::fromLatin1("kde");
                 break;
             default:
                 key = QString::fromLocal8Bit(qgetenv("DESKTOP_SESSION"));
                 break;
             }
         }
 #endif
         if (!key.isEmpty() && QApplication::desktopSettingsAware()) {
             QFactoryLoader loader(QGuiPlatformPluginInterface_iid, QLatin1String("/gui_platform"));
             plugin = qobject_cast<QGuiPlatformPlugin *>(loader.instance(key));
         }
 #endif // QT_NO_LIBRARY
         if(!plugin) {
             static QGuiPlatformPlugin def;
             plugin = &def;
         }
     }
     return plugin;
 }