Qt 4.8: /src/corelib/tools/qharfbuzz_p.h File Reference
qharfbuzz_p.h File Reference
#include <QtCore/qglobal.h>
#include <harfbuzz-shaper.h>
Functions
Q_DECLARE_TYPEINFO (HB_GlyphAttributes, Q_PRIMITIVE_TYPE)
Q_DECLARE_TYPEINFO (HB_FixedPoint, Q_PRIMITIVE_TYPE)
Q_CORE_EXPORT void qGetCharAttributes (const HB_UChar16 *string, hb_uint32 stringLength, const HB_ScriptItem *items, hb_uint32 numItems, HB_CharAttributes *attributes)
Q_CORE_EXPORT void qHBFreeFace (HB_Face)
Q_CORE_EXPORT HB_Face qHBNewFace (void *font, HB_GetFontTableFunc tableFunc)
Q_CORE_EXPORT HB_Bool qShapeItem (HB_ShaperItem *item)
Function Documentation
Q_DECLARE_TYPEINFO() [1/2]
Q_DECLARE_TYPEINFO (HB_GlyphAttributes , Q_PRIMITIVE_TYPE)
Q_DECLARE_TYPEINFO() [2/2]
Q_DECLARE_TYPEINFO (HB_FixedPoint , Q_PRIMITIVE_TYPE)
qGetCharAttributes()
Q_CORE_EXPORT void qGetCharAttributes (const HB_UChar16 * string, hb_uint32 stringLength, const HB_ScriptItem * items, hb_uint32 numItems, HB_CharAttributes * attributes)
Definition at line 133 of file qharfbuzz.cpp.
Referenced by QTextEngine::attributes(), and init().
 {
     HB_GetCharAttributes(string, stringLength, items, numItems, attributes);
 }
qHBFreeFace()
Q_CORE_EXPORT void qHBFreeFace (HB_Face)
Definition at line 128 of file qharfbuzz.cpp.
Referenced by QFreetypeFace::release(), and QFontEngine::~QFontEngine().
 {
     HB_FreeFace(face);
 }
qHBNewFace()
Q_CORE_EXPORT HB_Face qHBNewFace (void * font, HB_GetFontTableFunc tableFunc)
Definition at line 123 of file qharfbuzz.cpp.
Referenced by QFreetypeFace::getFace(), and QFontEngine::harfbuzzFace().
 {
     return HB_NewFace(font, tableFunc);
 }
qShapeItem()
Q_CORE_EXPORT HB_Bool qShapeItem (HB_ShaperItem * item)
Definition at line 118 of file qharfbuzz.cpp.
Referenced by QTextEngine::shapeTextWithHarfbuzz().
 {
     return HB_ShapeItem(item);
 }