Qt 4.8: /src/corelib/tools/qharfbuzz.cpp File Reference
qharfbuzz.cpp File Reference
#include "qunicodetables_p.h"
#include "qlibrary.h"
#include "qtextcodec.h"
#include "qharfbuzz_p.h"
Functions
void HB_GetGraphemeAndLineBreakClass (HB_UChar32 ch, HB_GraphemeClass *grapheme, HB_LineBreakClass *lineBreak)
HB_GraphemeClass HB_GetGraphemeClass (HB_UChar32 ch)
HB_LineBreakClass HB_GetLineBreakClass (HB_UChar32 ch)
HB_UChar16 HB_GetMirroredChar (HB_UChar16 ch)
HB_SentenceClass HB_GetSentenceClass (HB_UChar32 ch)
HB_CharCategory HB_GetUnicodeCharCategory (HB_UChar32 ch)
int HB_GetUnicodeCharCombiningClass (HB_UChar32 ch)
void HB_GetUnicodeCharProperties (HB_UChar32 ch, HB_CharCategory *category, int *combiningClass)
HB_WordClass HB_GetWordClass (HB_UChar32 ch)
void * HB_Library_Resolve (const char *library, int version, const char *symbol)
void qGetCharAttributes (const HB_UChar16 *string, hb_uint32 stringLength, const HB_ScriptItem *items, hb_uint32 numItems, HB_CharAttributes *attributes)
void qHBFreeFace (HB_Face face)
HB_Face qHBNewFace (void *font, HB_GetFontTableFunc tableFunc)
HB_Bool qShapeItem (HB_ShaperItem *item)
Function Documentation
HB_GetGraphemeAndLineBreakClass()
void HB_GetGraphemeAndLineBreakClass (HB_UChar32 ch, HB_GraphemeClass * grapheme, HB_LineBreakClass * lineBreak)
Definition at line 76 of file qharfbuzz.cpp.
 {
     const QUnicodeTables::Properties *prop = QUnicodeTables::properties(ch);
     *grapheme = (HB_GraphemeClass) prop->graphemeBreak;
     *lineBreak = (HB_LineBreakClass) prop->line_break_class;
 }
HB_GetGraphemeClass()
HB_GraphemeClass HB_GetGraphemeClass (HB_UChar32 ch)
Definition at line 52 of file qharfbuzz.cpp.
 {
     const QUnicodeTables::Properties *prop = QUnicodeTables::properties(ch);
     return (HB_GraphemeClass) prop->graphemeBreak;
 }
HB_GetLineBreakClass()
HB_LineBreakClass HB_GetLineBreakClass (HB_UChar32 ch)
Definition at line 70 of file qharfbuzz.cpp.
 {
     return (HB_LineBreakClass)QUnicodeTables::lineBreakClass(ch);
 }
HB_GetMirroredChar()
HB_UChar16 HB_GetMirroredChar (HB_UChar16 ch)
Definition at line 100 of file qharfbuzz.cpp.
 {
     return QChar::mirroredChar(ch);
 }
HB_GetSentenceClass()
HB_SentenceClass HB_GetSentenceClass (HB_UChar32 ch)
Definition at line 64 of file qharfbuzz.cpp.
 {
     const QUnicodeTables::Properties *prop = QUnicodeTables::properties(ch);
     return (HB_SentenceClass) prop->sentenceBreak;
 }
HB_GetUnicodeCharCategory()
HB_CharCategory HB_GetUnicodeCharCategory (HB_UChar32 ch)
Definition at line 90 of file qharfbuzz.cpp.
 {
     return (HB_CharCategory)QChar::category(ch);
 }
HB_GetUnicodeCharCombiningClass()
int HB_GetUnicodeCharCombiningClass (HB_UChar32 ch)
Definition at line 95 of file qharfbuzz.cpp.
 {
     return QChar::combiningClass(ch);
 }
HB_GetUnicodeCharProperties()
void HB_GetUnicodeCharProperties (HB_UChar32 ch, HB_CharCategory * category, int * combiningClass)
Definition at line 83 of file qharfbuzz.cpp.
 {
     const QUnicodeTables::Properties *prop = QUnicodeTables::properties(ch);
     *category = (HB_CharCategory)prop->category;
     *combiningClass = prop->combiningClass;
 }
HB_GetWordClass()
HB_WordClass HB_GetWordClass (HB_UChar32 ch)
Definition at line 58 of file qharfbuzz.cpp.
 {
     const QUnicodeTables::Properties *prop = QUnicodeTables::properties(ch);
     return (HB_WordClass) prop->wordBreak;
 }
HB_Library_Resolve()
void* HB_Library_Resolve (const char * library, int version, const char * symbol)
Definition at line 105 of file qharfbuzz.cpp.
 {
 #ifdef QT_NO_LIBRARY
     return 0;
 #else
     return QLibrary::resolve(QLatin1String(library), version, symbol);
 #endif
 }
qGetCharAttributes()
void qGetCharAttributes (const HB_UChar16 * string, hb_uint32 stringLength, const HB_ScriptItem * items, hb_uint32 numItems, HB_CharAttributes * attributes)
Definition at line 133 of file qharfbuzz.cpp.
Referenced by QTextEngine::attributes(), and init().
 {
     HB_GetCharAttributes(string, stringLength, items, numItems, attributes);
 }
qHBFreeFace()
void qHBFreeFace (HB_Face face)
Definition at line 128 of file qharfbuzz.cpp.
Referenced by QFreetypeFace::release(), and QFontEngine::~QFontEngine().
 {
     HB_FreeFace(face);
 }
qHBNewFace()
HB_Face qHBNewFace (void * font, HB_GetFontTableFunc tableFunc)
Definition at line 123 of file qharfbuzz.cpp.
Referenced by QFreetypeFace::getFace(), and QFontEngine::harfbuzzFace().
 {
     return HB_NewFace(font, tableFunc);
 }
qShapeItem()
HB_Bool qShapeItem (HB_ShaperItem * item)
Definition at line 118 of file qharfbuzz.cpp.
Referenced by QTextEngine::shapeTextWithHarfbuzz().
 {
     return HB_ShapeItem(item);
 }