Qt 4.8: /src/corelib/tools/qhash.h File Reference
qhash.h File Reference
#include <QtCore/qatomic.h>
#include <QtCore/qchar.h>
#include <QtCore/qiterator.h>
#include <QtCore/qlist.h>
#include <QtCore/qpair.h>
Classes
class QHash< Key, T >
The QHash class is a template class that provides a hash-table-based dictionary.
class QHash< Key, T >::const_iterator
The QHash::const_iterator class provides an STL-style const iterator for QHash and QMultiHash.
class QHash< Key, T >::iterator
The QHash::iterator class provides an STL-style non-const iterator for QHash and QMultiHash.
struct QHashData
struct QHashData::Node
struct QHashDummyNode< Key, T >
struct QHashDummyValue
struct QHashNode< Key, T >
class QMultiHash< Key, T >
The QMultiHash class is a convenience QHash subclass that provides multi-valued hashes.
Macros
#define Q_HASH_DECLARE_INT_NODES(key_type)
Functions
bool operator== (const QHashDummyValue &, const QHashDummyValue &)
Q_DECLARE_TYPEINFO (QHashDummyValue, Q_MOVABLE_TYPE|Q_DUMMY_TYPE)
Q_HASH_DECLARE_INT_NODES (int)
Q_HASH_DECLARE_INT_NODES (uint)
uint qHash (char key)
uint qHash (uchar key)
uint qHash (signed char key)
uint qHash (ushort key)
uint qHash (short key)
uint qHash (uint key)
uint qHash (int key)
uint qHash (ulong key)
uint qHash (long key)
uint qHash (quint64 key)
uint qHash (qint64 key)
uint qHash (QChar key)
Q_CORE_EXPORT uint qHash (const QByteArray &key)
Returns the hash value for the key.
Q_CORE_EXPORT uint qHash (const QString &key)
Q_CORE_EXPORT uint qHash (const QStringRef &key)
Q_CORE_EXPORT uint qHash (const QBitArray &key)
template<class T >
uint qHash (const T *key)
template<typename T1 , typename T2 >
uint qHash (const QPair< T1, T2 > &key)
Macro Definition Documentation
Q_HASH_DECLARE_INT_NODES
#define Q_HASH_DECLARE_INT_NODES (key_type)
Value:
template <class T> \
    struct QHashDummyNode<key_type, T> { \
        QHashDummyNode *next; \
        union { uint h; key_type key; }; \
\
        inline QHashDummyNode(key_type /* key0 */) {} \
    }; \
\
    template <class T> \
    struct QHashNode<key_type, T> { \
        QHashNode *next; \
        union { uint h; key_type key; }; \
        T value; \
\
        inline QHashNode(key_type /* key0 */) {} \
        inline QHashNode(key_type /* key0 */, const T &value0) : value(value0) {} \
        inline bool same_key(uint h0, key_type) { return h0 == h; } \
    }
Definition at line 229 of file qhash.h.
Function Documentation
operator==()
bool operator== (const QHashDummyValue & , const QHashDummyValue &) inline
Definition at line 198 of file qhash.h.
Referenced by QHash< Key, T >::const_iterator::operator-=(), and QHash< QExplicitlySharedDataPointer, QHash >::swap().
 {
     return true;
 }
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QHashDummyValue , Q_MOVABLE_TYPE| Q_DUMMY_TYPE)
Referenced by operator==().
Q_HASH_DECLARE_INT_NODES() [1/2]
Q_HASH_DECLARE_INT_NODES (int)
Q_HASH_DECLARE_INT_NODES() [2/2]
Q_HASH_DECLARE_INT_NODES (uint)
qHash() [1/18]
uint qHash (char key) related
Definition at line 62 of file qhash.h.
Referenced by QHash< QExplicitlySharedDataPointer, QHash >::findNode().
 { return uint(key); }
qHash() [2/18]
uint qHash (uchar key) related
Definition at line 63 of file qhash.h.
 { return uint(key); }
qHash() [3/18]
uint qHash (signed char key) related
Definition at line 64 of file qhash.h.
 { return uint(key); }
qHash() [4/18]
uint qHash (ushort key) related
Definition at line 65 of file qhash.h.
 { return uint(key); }
qHash() [5/18]
uint qHash (short key) related
Definition at line 66 of file qhash.h.
 { return uint(key); }
qHash() [6/18]
uint qHash (uint key) related
Definition at line 67 of file qhash.h.
 { return key; }
qHash() [7/18]
uint qHash (int key) related
Definition at line 68 of file qhash.h.
 { return uint(key); }
qHash() [8/18]
uint qHash (ulong key) related
Definition at line 69 of file qhash.h.
 {
     if (sizeof(ulong) > sizeof(uint)) {
         return uint(((key >> (8 * sizeof(uint) - 1)) ^ key) & (~0U));
     } else {
         return uint(key & (~0U));
     }
 }
qHash() [9/18]
uint qHash (long key) related
Definition at line 77 of file qhash.h.
 { return qHash(ulong(key)); }
qHash() [10/18]
uint qHash (quint64 key) related
Definition at line 78 of file qhash.h.
 {
     if (sizeof(quint64) > sizeof(uint)) {
         return uint(((key >> (8 * sizeof(uint) - 1)) ^ key) & (~0U));
     } else {
         return uint(key & (~0U));
     }
 }
qHash() [11/18]
uint qHash (qint64 key) related
Definition at line 86 of file qhash.h.
 { return qHash(quint64(key)); }
qHash() [12/18]
uint qHash (QChar key) related
Definition at line 87 of file qhash.h.
 { return qHash(key.unicode()); }
qHash() [13/18]
Q_CORE_EXPORT uint qHash (const QByteArray & key)
Returns the hash value for the key.
Definition at line 92 of file qhash.cpp.
 {
     return hash(reinterpret_cast<const uchar *>(key.constData()), key.size());
 }
qHash() [14/18]
Q_CORE_EXPORT uint qHash (const QString & key) related
Definition at line 97 of file qhash.cpp.
 {
     return hash(key.unicode(), key.size());
 }
qHash() [15/18]
Q_CORE_EXPORT uint qHash (const QStringRef & key)
Definition at line 102 of file qhash.cpp.
 {
     return hash(key.unicode(), key.size());
 }
qHash() [16/18]
Q_CORE_EXPORT uint qHash (const QBitArray & key) related
Definition at line 107 of file qhash.cpp.
 {
     int m = bitArray.d.size() - 1;
     uint result = hash(reinterpret_cast<const uchar *>(bitArray.d.constData()), qMax(0, m));
     // deal with the last 0 to 7 bits manually, because we can't trust that
     // the padding is initialized to 0 in bitArray.d
     int n = bitArray.size();
     if (n & 0x7)
         result = ((result << 4) + bitArray.d.at(m)) & ((1 << n) - 1);
     return result;
 }
qHash() [17/18]
template<class T > uint qHash (const T * key) related
Definition at line 97 of file qhash.h.
 {
     return qHash(reinterpret_cast<quintptr>(key));
 }
qHash() [18/18]
template<typename T1 , typename T2 > uint qHash (const QPair< T1, T2 > & key) related
Definition at line 105 of file qhash.h.
 {
     uint h1 = qHash(key.first);
     uint h2 = qHash(key.second);
     return ((h1 << 16) | (h1 >> 16)) ^ h2;
 }