Qt 4.8: /src/corelib/tools/qhash.cpp File Reference
qhash.cpp File Reference
#include "qhash.h"
#include <qbitarray.h>
#include <qstring.h>
#include <stdlib.h>
Functions
static int countBits (int hint)
static uint hash (const uchar *p, int n)
static uint hash (const QChar *p, int n)
static int primeForNumBits (int numBits)
uint qHash (const QByteArray &key)
Returns the hash value for the key.
uint qHash (const QString &key)
uint qHash (const QStringRef &key)
uint qHash (const QBitArray &bitArray)
Variables
const int MinNumBits = 4
static const uchar prime_deltas []
Function Documentation
countBits()
static int countBits (int hint) static
Definition at line 144 of file qhash.cpp.
Referenced by QHashData::rehash().
 {
     int numBits = 0;
     int bits = hint;
     while (bits > 1) {
         bits >>= 1;
         numBits++;
     }
     if (numBits >= (int)sizeof(prime_deltas)) {
         numBits = sizeof(prime_deltas) - 1;
     } else if (primeForNumBits(numBits) < hint) {
         ++numBits;
     }
     return numBits;
 }
hash() [1/2]
static uint hash (const uchar * p, int n) static
Definition at line 68 of file qhash.cpp.
Referenced by QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::addTransition(), QMetaObject::changeGuard(), cleanup_cmaps(), QObjectPrivate::clearGuards(), convert_RGB_to_Indexed8(), digestMd5ResponseHelper(), QTranslatorPrivate::do_translate(), QResourceRoot::findNode(), QResourceRoot::findOffset(), QApplication::font(), QGLMaskTextureCache::getMask(), QPatternist::XsdParticleChecker::hasDuplicatedElements(), hasDuplicatedElementsInternal(), QDeclarativeDebugService::idForObject(), internalParticleLookupMap(), QDeclarativeDebugService::objectForId(), operator<<(), QProcessEnvironmentPrivate::OrderedMutexLocker::OrderedMutexLocker(), QApplication::palette(), QXmlStreamReaderPrivate::parse(), qEncodeHmacMd5(), qHash(), qStringFromUcs2Le(), qt_CoCreateGuid(), qt_delete_glyph_hash(), qt_fallback_font_family(), qt_gl_choose_cmap(), qt_transparent_pixel(), qt_x11_set_fallback_font_family(), QVariant::QVariant(), QMetaObject::removeGuard(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), QTextControl::setExtraSelections(), QApplication::setFont(), QApplicationPrivate::setPalette_helper(), QPatternist::XsdSchemaContext::setupBuiltinTypesFacetList(), QNetworkDiskCachePrivate::uniqueFileName(), unregWinClasses(), QPropertyAnimation::updateState(), QPatternist::TokenLookup::value(), and QDeclarativeWorkerScriptEnginePrivate::variantToScriptValue().
 {
     uint h = 0;
     while (n--) {
         h = (h << 4) + *p++;
         h ^= (h & 0xf0000000) >> 23;
         h &= 0x0fffffff;
     }
     return h;
 }
hash() [2/2]
static uint hash (const QChar * p, int n) static
Definition at line 80 of file qhash.cpp.
 {
     uint h = 0;
     while (n--) {
         h = (h << 4) + (*p++).unicode();
         h ^= (h & 0xf0000000) >> 23;
         h &= 0x0fffffff;
     }
     return h;
 }
primeForNumBits()
static int primeForNumBits (int numBits) inline static
Definition at line 135 of file qhash.cpp.
Referenced by countBits(), and QHashData::rehash().
 {
     return (1 << numBits) + prime_deltas[numBits];
 }
qHash() [1/4]
uint qHash (const QByteArray & key)
Returns the hash value for the key.
Definition at line 92 of file qhash.cpp.
 {
     return hash(reinterpret_cast<const uchar *>(key.constData()), key.size());
 }
qHash() [2/4]
uint qHash (const QString & key) related
Definition at line 97 of file qhash.cpp.
Referenced by qHash().
 {
     return hash(key.unicode(), key.size());
 }
qHash() [3/4]
uint qHash (const QStringRef & key)
Definition at line 102 of file qhash.cpp.
 {
     return hash(key.unicode(), key.size());
 }
qHash() [4/4]
uint qHash (const QBitArray & bitArray) related
Definition at line 107 of file qhash.cpp.
 {
     int m = bitArray.d.size() - 1;
     uint result = hash(reinterpret_cast<const uchar *>(bitArray.d.constData()), qMax(0, m));
     // deal with the last 0 to 7 bits manually, because we can't trust that
     // the padding is initialized to 0 in bitArray.d
     int n = bitArray.size();
     if (n & 0x7)
         result = ((result << 4) + bitArray.d.at(m)) & ((1 << n) - 1);
     return result;
 }
Variable Documentation
MinNumBits
const int MinNumBits = 4
Definition at line 166 of file qhash.cpp.
Referenced by QHashData::rehash().
prime_deltas
const uchar prime_deltas[] static
Initial value:
= {
    0,  0,  1,  3,  1,  5,  3,  3,  1,  9,  7,  5,  3,  9, 25,  3,
    1, 21,  3, 21,  7, 15,  9,  5,  3, 29, 15,  0,  0,  0,  0,  0
}
Definition at line 130 of file qhash.cpp.
Referenced by countBits(), and primeForNumBits().