Qt 4.8: /src/network/kernel/qhostaddress.h File Reference
qhostaddress.h File Reference
#include <QtCore/qpair.h>
#include <QtCore/qstring.h>
#include <QtCore/qscopedpointer.h>
#include <QtNetwork/qabstractsocket.h>
Classes
class QHostAddress
The QHostAddress class provides an IP address.
class QIPv6Address
Typedefs
typedef QIPv6Address Q_IPV6ADDR
Functions
Q_NETWORK_EXPORT QDebug operator<< (QDebug, const QHostAddress &)
Q_NETWORK_EXPORT QDataStream & operator<< (QDataStream &, const QHostAddress &)
bool operator== (QHostAddress::SpecialAddress address1, const QHostAddress &address2)
Q_NETWORK_EXPORT QDataStream & operator>> (QDataStream &, QHostAddress &)
Q_NETWORK_EXPORT uint qHash (const QHostAddress &key)
Typedef Documentation
Q_IPV6ADDR
typedef QIPv6Address Q_IPV6ADDR
Definition at line 68 of file qhostaddress.h.
Function Documentation
operator<<() [1/2]
Q_NETWORK_EXPORT QDebug operator<< (QDebug , const QHostAddress &)
Definition at line 1152 of file qhostaddress.cpp.
Referenced by operator==().
 {
     d.maybeSpace() << "QHostAddress(" << address.toString() << ')';
     return d.space();
 }
operator<<() [2/2]
Q_NETWORK_EXPORT QDataStream& operator<< (QDataStream & , const QHostAddress &) related
operator==()
bool operator== (QHostAddress::SpecialAddress address1, const QHostAddress & address2) inline
Definition at line 137 of file qhostaddress.h.
Referenced by QHostAddress::operator!=().
 { return address2 == address1; }
operator>>()
Q_NETWORK_EXPORT QDataStream& operator>> (QDataStream & , QHostAddress &) related
Referenced by operator==().
qHash()
Q_NETWORK_EXPORT uint qHash (const QHostAddress & key)
Definition at line 1159 of file qhostaddress.cpp.
Referenced by operator==(), and qHash().
 {
     return qHash(key.toString());
 }