Qt 4.8: /src/network/access/qhttpthreaddelegate.cpp File Reference
qhttpthreaddelegate.cpp File Reference
#include "qhttpthreaddelegate_p.h"
#include <QThread>
#include <QTimer>
#include <QAuthenticator>
#include <QEventLoop>
#include "private/qhttpnetworkreply_p.h"
#include "private/qnetworkaccesscache_p.h"
#include "private/qnoncontiguousbytedevice_p.h"
Classes
class QNetworkAccessCachedHttpConnection
Functions
static void downloadBufferDeleter (char *ptr)
static QByteArray makeCacheKey (QUrl &url, QNetworkProxy *proxy)
static QNetworkReply::NetworkError statusCodeFromHttp (int httpStatusCode, const QUrl &url)
Function Documentation
downloadBufferDeleter()
static void downloadBufferDeleter (char * ptr) static
Definition at line 508 of file qhttpthreaddelegate.cpp.
Referenced by QHttpThreadDelegate::headerChangedSlot().
 {
     delete[] ptr;
 }
makeCacheKey()
static QByteArray makeCacheKey (QUrl & url, QNetworkProxy * proxy) static
Definition at line 106 of file qhttpthreaddelegate.cpp.
Referenced by QHttpThreadDelegate::startRequest().
 {
     QByteArray result;
     QUrl copy = url;
     bool isEncrypted = copy.scheme().toLower() == QLatin1String("https");
     copy.setPort(copy.port(isEncrypted ? 443 : 80));
     result = copy.toEncoded(QUrl::RemoveUserInfo | QUrl::RemovePath |
                             QUrl::RemoveQuery | QUrl::RemoveFragment);
 #ifndef QT_NO_NETWORKPROXY
     if (proxy && proxy->type() != QNetworkProxy::NoProxy) {
         QUrl key;
         switch (proxy->type()) {
         case QNetworkProxy::Socks5Proxy:
             key.setScheme(QLatin1String("proxy-socks5"));
             break;
         case QNetworkProxy::HttpProxy:
         case QNetworkProxy::HttpCachingProxy:
             key.setScheme(QLatin1String("proxy-http"));
             break;
         default:
             break;
         }
         if (!key.scheme().isEmpty()) {
             key.setUserName(proxy->user());
             key.setHost(proxy->hostName());
             key.setPort(proxy->port());
             key.setEncodedQuery(result);
             result = key.toEncoded();
         }
     }
 #else
     Q_UNUSED(proxy)
 #endif
     return "http-connection:" + result;
 }
statusCodeFromHttp()
static QNetworkReply::NetworkError statusCodeFromHttp (int httpStatusCode, const QUrl & url) static
Definition at line 58 of file qhttpthreaddelegate.cpp.
Referenced by QHttpThreadDelegate::finishedSlot(), and QHttpThreadDelegate::synchronousFinishedSlot().
 {
     QNetworkReply::NetworkError code;
     // we've got an error
     switch (httpStatusCode) {
     case 401:               // Authorization required
         code = QNetworkReply::AuthenticationRequiredError;
         break;
     case 403:               // Access denied
         code = QNetworkReply::ContentOperationNotPermittedError;
         break;
     case 404:               // Not Found
         code = QNetworkReply::ContentNotFoundError;
         break;
     case 405:               // Method Not Allowed
         code = QNetworkReply::ContentOperationNotPermittedError;
         break;
     case 407:
         code = QNetworkReply::ProxyAuthenticationRequiredError;
         break;
     case 418:               // I'm a teapot
         code = QNetworkReply::ProtocolInvalidOperationError;
         break;
     default:
         if (httpStatusCode > 500) {
             // some kind of server error
             code = QNetworkReply::ProtocolUnknownError;
         } else if (httpStatusCode >= 400) {
             // content error we did not handle above
             code = QNetworkReply::UnknownContentError;
         } else {
             qWarning("QNetworkAccess: got HTTP status code %d which is not expected from url: \"%s\"",
                      httpStatusCode, qPrintable(url.toString()));
             code = QNetworkReply::ProtocolFailure;
         }
     }
     return code;
 }