Qt 4.8: /src/plugins/bearer/icd/qicdengine.cpp File Reference
qicdengine.cpp File Reference
#include "qicdengine.h"
#include "qnetworksession_impl.h"
#include <wlancond.h>
#include <wlan-utils.h>
#include <iapconf.h>
#include <iapmonitor.h>
#include "qicdengine.moc"
Classes
class _IapAddTimer
class IapAddTimer
class IapMonitor
struct SSIDInfo
Functions
static quint32 getNetworkAttrs (bool is_iap_id, const QString &iap_id, const QString &iap_type, QString security_method)
static QString network_attrs_to_security (uint network_attrs)
Function Documentation
getNetworkAttrs()
static quint32 getNetworkAttrs (bool is_iap_id, const QString & iap_id, const QString & iap_type, QString security_method) static
Definition at line 367 of file qicdengine.cpp.
Referenced by QIcdEngine::addConfiguration(), and QIcdEngine::doRequestUpdate().
 {
     guint network_attr = 0;
     dbus_uint32_t cap = 0;
     if (iap_type == "WLAN_INFRA")
     cap |= WLANCOND_INFRA;
     else if (iap_type == "WLAN_ADHOC")
     cap |= WLANCOND_ADHOC;
     if (security_method.isEmpty() && (cap & (WLANCOND_INFRA | WLANCOND_ADHOC))) {
     Maemo::IAPConf saved_ap(iap_id);
     security_method = saved_ap.value("wlan_security").toString();
     }
     if (!security_method.isEmpty()) {
     if (security_method == "WEP")
         cap |= WLANCOND_WEP;
     else if (security_method == "WPA_PSK")
         cap |= WLANCOND_WPA_PSK;
     else if (security_method == "WPA_EAP")
         cap |= WLANCOND_WPA_EAP;
     else if (security_method == "NONE")
         cap |= WLANCOND_OPEN;
     if (cap & (WLANCOND_WPA_PSK | WLANCOND_WPA_EAP)) {
         Maemo::IAPConf saved_iap(iap_id);
         bool wpa2_only = saved_iap.value("EAP_wpa2_only_mode").toBool();
         if (wpa2_only) {
         cap |= WLANCOND_WPA2;
         }
     }
     }
     cap2nwattr(cap, &network_attr);
     if (is_iap_id)
     network_attr |= ICD_NW_ATTR_IAPNAME;
     return quint32(network_attr);
 }
network_attrs_to_security()
static QString network_attrs_to_security (uint network_attrs) inline static
Definition at line 321 of file qicdengine.cpp.
Referenced by QIcdEngine::doRequestUpdate().
 {
     uint cap = 0;
     nwattr2cap(network_attrs, &cap); /* from libicd-network-wlan-dev.h */
     if (cap & WLANCOND_OPEN)
         return "NONE";
     else if (cap & WLANCOND_WEP)
         return "WEP";
     else if (cap & WLANCOND_WPA_PSK)
         return "WPA_PSK";
     else if (cap & WLANCOND_WPA_EAP)
         return "WPA_EAP";
     return "";
 }