Qt 4.8: /src/plugins/bearer/icd/qicdengine.h File Reference
qicdengine.h File Reference
#include <QtNetwork/private/qbearerengine_p.h>
#include <QtCore/qtimer.h>
#include "maemo_icd.h"
Classes
class IcdNetworkConfigurationPrivate
class QIcdEngine
Functions
QNetworkConfiguration::BearerType bearerTypeFromIapType (const QString &iapType)
IcdNetworkConfigurationPrivate * toIcdConfig (QNetworkConfigurationPrivatePointer ptr)
Function Documentation
bearerTypeFromIapType()
QNetworkConfiguration::BearerType bearerTypeFromIapType (const QString & iapType) inline
Definition at line 58 of file qicdengine.h.
Referenced by QIcdEngine::addConfiguration(), QIcdEngine::doRequestUpdate(), QNetworkSessionPrivateImpl::stateChange(), and QNetworkSessionPrivateImpl::syncStateWithInterface().
 {
     if (iapType == QLatin1String("WLAN_INFRA") ||
         iapType == QLatin1String("WLAN_ADHOC")) {
         return QNetworkConfiguration::BearerWLAN;
     } else if (iapType == QLatin1String("GPRS")) {
         return QNetworkConfiguration::BearerHSPA;
     } else {
         return QNetworkConfiguration::BearerUnknown;
     }
 }
toIcdConfig()
IcdNetworkConfigurationPrivate* toIcdConfig (QNetworkConfigurationPrivatePointer ptr) inline
Definition at line 92 of file qicdengine.h.
Referenced by QIcdEngine::addConfiguration(), QNetworkSessionPrivateImpl::clearConfiguration(), QNetworkSessionPrivateImpl::copyConfig(), QNetworkSessionPrivateImpl::do_open(), QIcdEngine::doRequestUpdate(), QNetworkSessionPrivateImpl::getStatistics(), QNetworkSessionPrivateImpl::stateChange(), QNetworkSessionPrivateImpl::syncStateWithInterface(), QNetworkSessionPrivateImpl::updateIdentifier(), and QNetworkSessionPrivateImpl::updateState().
 {
     return static_cast<IcdNetworkConfigurationPrivate *>(ptr.data());
 }