Qt 4.8: /src/gui/image/qiconloader.cpp File Reference
qiconloader.cpp File Reference
#include <private/qiconloader_p.h>
#include <private/qapplication_p.h>
#include <private/qicon_p.h>
#include <private/qguiplatformplugin_p.h>
#include <QtGui/QIconEnginePlugin>
#include <QtGui/QPixmapCache>
#include <QtGui/QIconEngine>
#include <QtGui/QStyleOption>
#include <QtCore/QList>
#include <QtCore/QHash>
#include <QtCore/QDir>
#include <QtCore/QSettings>
#include <QtGui/QPainter>
#include <private/qt_cocoa_helpers_mac_p.h>
#include <private/qt_x11_p.h>
#include <private/qstylehelper_p.h>
Functions
static bool directoryMatchesSize (const QIconDirInfo &dir, int iconsize)
static int directorySizeDistance (const QIconDirInfo &dir, int iconsize)
static QString fallbackTheme ()
Function Documentation
directoryMatchesSize()
static bool directoryMatchesSize (const QIconDirInfo & dir, int iconsize) static
Definition at line 383 of file qiconloader.cpp.
Referenced by QIconLoaderEngine::entryForSize().
 {
     if (dir.type == QIconDirInfo::Fixed) {
         return dir.size == iconsize;
     } else if (dir.type == QIconDirInfo::Scalable) {
         return dir.size <= dir.maxSize &&
                 iconsize >= dir.minSize;
     } else if (dir.type == QIconDirInfo::Threshold) {
         return iconsize >= dir.size - dir.threshold &&
                 iconsize <= dir.size + dir.threshold;
     }
     Q_ASSERT(1); // Not a valid value
     return false;
 }
directorySizeDistance()
static int directorySizeDistance (const QIconDirInfo & dir, int iconsize) static
Definition at line 405 of file qiconloader.cpp.
Referenced by QIconLoaderEngine::entryForSize().
 {
     if (dir.type == QIconDirInfo::Fixed) {
         return qAbs(dir.size - iconsize);
     } else if (dir.type == QIconDirInfo::Scalable) {
         if (iconsize < dir.minSize)
             return dir.minSize - iconsize;
         else if (iconsize > dir.maxSize)
             return iconsize - dir.maxSize;
         else
             return 0;
     } else if (dir.type == QIconDirInfo::Threshold) {
         if (iconsize < dir.size - dir.threshold)
             return dir.minSize - iconsize;
         else if (iconsize > dir.size + dir.threshold)
             return iconsize - dir.maxSize;
         else return 0;
     }
     Q_ASSERT(1); // Not a valid value
     return INT_MAX;
 }
fallbackTheme()
static QString fallbackTheme () static
Definition at line 73 of file qiconloader.cpp.
Referenced by QIconLoader::ensureInitialized(), QIconLoader::findIconHelper(), QIconTheme::QIconTheme(), and QIconLoader::updateSystemTheme().
 {
 #ifdef Q_WS_X11
     if (X11->desktopEnvironment == DE_GNOME) {
         return QLatin1String("gnome");
     } else if (X11->desktopEnvironment == DE_KDE) {
         return X11->desktopVersion >= 4
             ? QString::fromLatin1("oxygen")
             : QString::fromLatin1("crystalsvg");
     } else {
         return QLatin1String("hicolor");
     }
 #endif
     return QString();
 }