Qt 4.8: /src/gui/image/qicon.h File Reference
qicon.h File Reference
#include <QtCore/qglobal.h>
#include <QtCore/qsize.h>
#include <QtCore/qlist.h>
#include <QtGui/qpixmap.h>
Classes
class QIcon
The QIcon class provides scalable icons in different modes and states.
Functions
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &, const QIcon &)
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &, QIcon &)
Q_DECLARE_TYPEINFO (QIcon, Q_MOVABLE_TYPE)
Function Documentation
operator<<()
Q_GUI_EXPORT QDataStream& operator<< (QDataStream & , const QIcon &)
Definition at line 1096 of file qicon.cpp.
Referenced by QIcon::data_ptr().
 {
     if (s.version() >= QDataStream::Qt_4_3) {
         if (icon.isNull()) {
             s << QString();
         } else {
             if (icon.d->engine_version > 1) {
                 QIconEngineV2 *engine = static_cast<QIconEngineV2 *>(icon.d->engine);
                 s << engine->key();
                 engine->write(s);
             } else {
                 // not really supported
                 qWarning("QIcon: Cannot stream QIconEngine. Use QIconEngineV2 instead.");
             }
         }
     } else if (s.version() == QDataStream::Qt_4_2) {
         if (icon.isNull()) {
             s << 0;
         } else {
             QPixmapIconEngine *engine = static_cast<QPixmapIconEngine *>(icon.d->engine);
             int num_entries = engine->pixmaps.size();
             s << num_entries;
             for (int i=0; i < num_entries; ++i) {
                 s << engine->pixmaps.at(i).pixmap;
                 s << engine->pixmaps.at(i).fileName;
                 s << engine->pixmaps.at(i).size;
                 s << (uint) engine->pixmaps.at(i).mode;
                 s << (uint) engine->pixmaps.at(i).state;
             }
         }
     } else {
         s << QPixmap(icon.pixmap(22,22));
     }
     return s;
 }
operator>>()
Q_GUI_EXPORT QDataStream& operator>> (QDataStream & , QIcon &)
Definition at line 1144 of file qicon.cpp.
Referenced by QIcon::data_ptr().
 {
     if (s.version() >= QDataStream::Qt_4_3) {
         icon = QIcon();
         QString key;
         s >> key;
         if (key == QLatin1String("QPixmapIconEngine")) {
             icon.d = new QIconPrivate;
             QIconEngineV2 *engine = new QPixmapIconEngine;
             icon.d->engine = engine;
             engine->read(s);
         } else if (key == QLatin1String("QIconLoaderEngine")) {
             icon.d = new QIconPrivate;
             QIconEngineV2 *engine = new QIconLoaderEngine();
             icon.d->engine = engine;
             engine->read(s);
 #if !defined (QT_NO_LIBRARY) && !defined(QT_NO_SETTINGS)
         } else if (QIconEngineFactoryInterfaceV2 *factory = qobject_cast<QIconEngineFactoryInterfaceV2*>(loaderV2()->instance(key))) {
             if (QIconEngineV2 *engine= factory->create()) {
                 icon.d = new QIconPrivate;
                 icon.d->engine = engine;
                 engine->read(s);
             }
 #endif
         }
     } else if (s.version() == QDataStream::Qt_4_2) {
         icon = QIcon();
         int num_entries;
         QPixmap pm;
         QString fileName;
         QSize sz;
         uint mode;
         uint state;
         s >> num_entries;
         for (int i=0; i < num_entries; ++i) {
             s >> pm;
             s >> fileName;
             s >> sz;
             s >> mode;
             s >> state;
             if (pm.isNull())
                 icon.addFile(fileName, sz, QIcon::Mode(mode), QIcon::State(state));
             else
                 icon.addPixmap(pm, QIcon::Mode(mode), QIcon::State(state));
         }
     } else {
         QPixmap pm;
         s >> pm;
         icon.addPixmap(pm);
     }
     return s;
 }
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QIcon , Q_MOVABLE_TYPE)
Referenced by QIcon::data_ptr().