Qt 4.8: /src/plugins/imageformats/ico/qicohandler.cpp File Reference
qicohandler.cpp File Reference
#include "qicohandler.h"
#include <QtCore/qendian.h>
#include <QtGui/QImage>
#include <QtCore/QFile>
#include <QtCore/QBuffer>
#include <qvariant.h>
Classes
struct BMP_INFOHDR
struct ICONDIR
struct ICONDIRENTRY
class ICOReader
struct ICOReader::IcoAttrib
Macros
#define BMP_INFOHDR_SIZE 40
#define ICONDIR_SIZE 6
#define ICONDIRENTRY_SIZE 16
Typedefs
typedef struct BMP_INFOHDR * LPBMP_INFOHDR
typedef struct ICONDIR * LPICONDIR
typedef struct ICONDIRENTRY * LPICONDIRENTRY
Functions
static bool readBMPInfoHeader (QIODevice *iodev, BMP_INFOHDR *pHeader)
static bool readIconDir (QIODevice *iodev, ICONDIR *iconDir)
static bool readIconDirEntry (QIODevice *iodev, ICONDIRENTRY *iconDirEntry)
static bool writeBMPInfoHeader (QIODevice *iodev, const BMP_INFOHDR &header)
static bool writeIconDir (QIODevice *iodev, const ICONDIR &iconDir)
static bool writeIconDirEntry (QIODevice *iodev, const ICONDIRENTRY &iconEntry)
Macro Definition Documentation
BMP_INFOHDR_SIZE
#define BMP_INFOHDR_SIZE 40
Definition at line 100 of file qicohandler.cpp.
Referenced by readBMPInfoHeader(), ICOReader::write(), and writeBMPInfoHeader().
ICONDIR_SIZE
#define ICONDIR_SIZE 6
Definition at line 85 of file qicohandler.cpp.
Referenced by ICOReader::canRead(), QtIcoHandler::option(), readIconDir(), ICOReader::readIconEntry(), and ICOReader::write().
ICONDIRENTRY_SIZE
#define ICONDIRENTRY_SIZE 16
Definition at line 76 of file qicohandler.cpp.
Referenced by ICOReader::canRead(), QtIcoHandler::option(), readIconDirEntry(), ICOReader::readIconEntry(), ICOReader::write(), and writeIconDirEntry().
Typedef Documentation
LPBMP_INFOHDR
typedef struct BMP_INFOHDR* LPBMP_INFOHDR
LPICONDIR
typedef struct ICONDIR * LPICONDIR
LPICONDIRENTRY
typedef struct ICONDIRENTRY * LPICONDIRENTRY
Function Documentation
readBMPInfoHeader()
static bool readBMPInfoHeader (QIODevice * iodev, BMP_INFOHDR * pHeader) static
Definition at line 209 of file qicohandler.cpp.
Referenced by ICOReader::readBMPHeader().
 {
     if (iodev) {
         uchar header[BMP_INFOHDR_SIZE];
         if (iodev->read((char*)header, BMP_INFOHDR_SIZE) == BMP_INFOHDR_SIZE) {
             pHeader->biSize = qFromLittleEndian<quint32>(&header[0]);
             pHeader->biWidth = qFromLittleEndian<quint32>(&header[4]);
             pHeader->biHeight = qFromLittleEndian<quint32>(&header[8]);
             pHeader->biPlanes = qFromLittleEndian<quint16>(&header[12]);
             pHeader->biBitCount = qFromLittleEndian<quint16>(&header[14]);
             pHeader->biCompression = qFromLittleEndian<quint32>(&header[16]);
             pHeader->biSizeImage = qFromLittleEndian<quint32>(&header[20]);
             pHeader->biXPelsPerMeter = qFromLittleEndian<quint32>(&header[24]);
             pHeader->biYPelsPerMeter = qFromLittleEndian<quint32>(&header[28]);
             pHeader->biClrUsed = qFromLittleEndian<quint32>(&header[32]);
             pHeader->biClrImportant = qFromLittleEndian<quint32>(&header[36]);
             return true;
         }
     }
     return false;
 }
readIconDir()
static bool readIconDir (QIODevice * iodev, ICONDIR * iconDir) static
Definition at line 183 of file qicohandler.cpp.
Referenced by ICOReader::canRead(), and ICOReader::readHeader().
 {
     if (iodev) {
         uchar tmp[ICONDIR_SIZE];
         if (iodev->read((char*)tmp, ICONDIR_SIZE) == ICONDIR_SIZE) {
             iconDir->idReserved = qFromLittleEndian<quint16>(&tmp[0]);
             iconDir->idType = qFromLittleEndian<quint16>(&tmp[2]);
             iconDir->idCount = qFromLittleEndian<quint16>(&tmp[4]);
             return true;
         }
     }
     return false;
 }
readIconDirEntry()
static bool readIconDirEntry (QIODevice * iodev, ICONDIRENTRY * iconDirEntry) static
Definition at line 145 of file qicohandler.cpp.
Referenced by ICOReader::canRead(), QtIcoHandler::option(), and ICOReader::readIconEntry().
 {
     if (iodev) {
         uchar tmp[ICONDIRENTRY_SIZE];
         if (iodev->read((char*)tmp, ICONDIRENTRY_SIZE) == ICONDIRENTRY_SIZE) {
             iconDirEntry->bWidth = tmp[0];
             iconDirEntry->bHeight = tmp[1];
             iconDirEntry->bColorCount = tmp[2];
             iconDirEntry->bReserved = tmp[3];
             iconDirEntry->wPlanes = qFromLittleEndian<quint16>(&tmp[4]);
             iconDirEntry->wBitCount = qFromLittleEndian<quint16>(&tmp[6]);
             iconDirEntry->dwBytesInRes = qFromLittleEndian<quint32>(&tmp[8]);
             iconDirEntry->dwImageOffset = qFromLittleEndian<quint32>(&tmp[12]);
             return true;
         }
     }
     return false;
 }
writeBMPInfoHeader()
static bool writeBMPInfoHeader (QIODevice * iodev, const BMP_INFOHDR & header) static
Definition at line 231 of file qicohandler.cpp.
Referenced by ICOReader::write().
 {
     if (iodev) {
         uchar tmp[BMP_INFOHDR_SIZE];
         qToLittleEndian<quint32>(header.biSize, &tmp[0]);
         qToLittleEndian<quint32>(header.biWidth, &tmp[4]);
         qToLittleEndian<quint32>(header.biHeight, &tmp[8]);
         qToLittleEndian<quint16>(header.biPlanes, &tmp[12]);
         qToLittleEndian<quint16>(header.biBitCount, &tmp[14]);
         qToLittleEndian<quint32>(header.biCompression, &tmp[16]);
         qToLittleEndian<quint32>(header.biSizeImage, &tmp[20]);
         qToLittleEndian<quint32>(header.biXPelsPerMeter, &tmp[24]);
         qToLittleEndian<quint32>(header.biYPelsPerMeter, &tmp[28]);
         qToLittleEndian<quint32>(header.biClrUsed, &tmp[32]);
         qToLittleEndian<quint32>(header.biClrImportant, &tmp[36]);
         return (iodev->write((char*)tmp, BMP_INFOHDR_SIZE) == BMP_INFOHDR_SIZE) ? true : false;
     }
     return false;
 }
writeIconDir()
static bool writeIconDir (QIODevice * iodev, const ICONDIR & iconDir) static
Definition at line 197 of file qicohandler.cpp.
Referenced by ICOReader::write().
 {
     if (iodev) {
         uchar tmp[6];
         qToLittleEndian(iconDir.idReserved, tmp);
         qToLittleEndian(iconDir.idType, &tmp[2]);
         qToLittleEndian(iconDir.idCount, &tmp[4]);
         return (iodev->write((char*)tmp,  6) == 6) ? true : false;
     }
     return false;
 }
writeIconDirEntry()
static bool writeIconDirEntry (QIODevice * iodev, const ICONDIRENTRY & iconEntry) static
Definition at line 165 of file qicohandler.cpp.
Referenced by ICOReader::write().
 {
     if (iodev) {
         uchar tmp[ICONDIRENTRY_SIZE];
         tmp[0] = iconEntry.bWidth;
         tmp[1] = iconEntry.bHeight;
         tmp[2] = iconEntry.bColorCount;
         tmp[3] = iconEntry.bReserved;
         qToLittleEndian<quint16>(iconEntry.wPlanes, &tmp[4]);
         qToLittleEndian<quint16>(iconEntry.wBitCount, &tmp[6]);
         qToLittleEndian<quint32>(iconEntry.dwBytesInRes, &tmp[8]);
         qToLittleEndian<quint32>(iconEntry.dwImageOffset, &tmp[12]);
         return (iodev->write((char*)tmp,  ICONDIRENTRY_SIZE) == ICONDIRENTRY_SIZE) ? true : false;
     }
     return false;
 }