Qt 4.8: /src/gui/image/qicon.cpp File Reference
qicon.cpp File Reference
#include "qicon.h"
#include "qicon_p.h"
#include "qiconengine.h"
#include "qiconengineplugin.h"
#include "private/qfactoryloader_p.h"
#include "private/qiconloader_p.h"
#include "qapplication.h"
#include "qstyleoption.h"
#include "qpainter.h"
#include "qfileinfo.h"
#include "qstyle.h"
#include "qpixmapcache.h"
#include "qvariant.h"
#include "qcache.h"
#include "qdebug.h"
#include "private/qguiplatformplugin_p.h"
#include <private/qt_mac_p.h>
#include <private/qt_cocoa_helpers_mac_p.h>
#include "private/qt_x11_p.h"
#include "private/qkde_p.h"
#include "private/qstylehelper_p.h"
Typedefs
typedef QCache< QString, QIcon > IconCache
Functions
static int area (const QSize &s)
static QPixmapIconEngineEntry * bestSizeMatch (const QSize &size, QPixmapIconEngineEntry *pa, QPixmapIconEngineEntry *pb)
QDataStream & operator<< (QDataStream &s, const QIcon &icon)
QDataStream & operator>> (QDataStream &s, QIcon &icon)
Q_GLOBAL_STATIC_WITH_ARGS (QFactoryLoader, loader,(QIconEngineFactoryInterface_iid, QLatin1String("/iconengines"), Qt::CaseInsensitive)) Q_GLOBAL_STATIC_WITH_ARGS(QFactoryLoader
QLatin1String ("/iconengines")
static void qt_cleanup_icon_cache ()
Variables
loaderV2
QIconEngineFactoryInterfaceV2_iid
static QBasicAtomicInt serialNumCounter = Q_BASIC_ATOMIC_INITIALIZER(1)
Typedef Documentation
IconCache
typedef QCache<QString, QIcon> IconCache
Definition at line 116 of file qicon.cpp.
Function Documentation
area()
static int area (const QSize & s) inline static
Definition at line 155 of file qicon.cpp.
Referenced by QTableViewPrivate::accessibleTable2Index(), bestSizeMatch(), QPrintPreviewWidgetPrivate::calcCurrentPage(), QAbstractItemView::doAutoScroll(), QWindowsXPStylePrivate::drawBackgroundDirectly(), QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), QTreeView::drawTree(), QTabBar::event(), QMdiArea::eventFilter(), QBspTree::firstChildIndex(), QRasterWindowSurface::flush(), QListViewPrivate::horizontalScrollToValue(), QBspTree::init(), QToolBar::isAreaAllowed(), QDockWidget::isAreaAllowed(), QDirectFBWindowSurface::key(), QMdiSubWindow::mdiArea(), mdiAreaNavigate(), mdiAreaParent(), QDeclarativePaintedItem::paint(), QFbWindowSurface::paintDevice(), QWSMemorySurface::paintDevice(), qt_mainwindow_layout(), QtWndProc(), QWidgetBackingStore::removeDirtyWidget(), QBspTree::removeLeaf(), QBBRasterWindowSurface::scroll(), QTreeView::scrollTo(), QMainWindowLayout::setCorner(), QToolBarLayout::setGeometry(), QDeclarativePaintedItem::setPixelCacheSize(), QListModeViewBase::setRowCount(), QAbstractItemViewPrivate::shouldAutoScroll(), QDirectFBScreen::surfaceForWidget(), QVGEGLWindowSurfaceDirect::surfaceSize(), QXIMInputContext::update(), QRegionPrivate::updateInnerRect(), QListViewPrivate::verticalScrollToValue(), and QCommonListViewBase::~QCommonListViewBase().
 { return s.width() * s.height(); }
bestSizeMatch()
static QPixmapIconEngineEntry* bestSizeMatch (const QSize & size, QPixmapIconEngineEntry * pa, QPixmapIconEngineEntry * pb) static
Definition at line 158 of file qicon.cpp.
Referenced by QPixmapIconEngine::tryMatch().
 {
     int s = area(size);
     if (pa->size == QSize() && pa->pixmap.isNull()) {
         pa->pixmap = QPixmap(pa->fileName);
         pa->size = pa->pixmap.size();
     }
     int a = area(pa->size);
     if (pb->size == QSize() && pb->pixmap.isNull()) {
         pb->pixmap = QPixmap(pb->fileName);
         pb->size = pb->pixmap.size();
     }
     int b = area(pb->size);
     int res = a;
     if (qMin(a,b) >= s)
         res = qMin(a,b);
     else
         res = qMax(a,b);
     if (res == a)
         return pa;
     return pb;
 }
operator<<()
QDataStream& operator<< (QDataStream & s, const QIcon & icon)
Definition at line 1096 of file qicon.cpp.
Referenced by QIcon::data_ptr().
 {
     if (s.version() >= QDataStream::Qt_4_3) {
         if (icon.isNull()) {
             s << QString();
         } else {
             if (icon.d->engine_version > 1) {
                 QIconEngineV2 *engine = static_cast<QIconEngineV2 *>(icon.d->engine);
                 s << engine->key();
                 engine->write(s);
             } else {
                 // not really supported
                 qWarning("QIcon: Cannot stream QIconEngine. Use QIconEngineV2 instead.");
             }
         }
     } else if (s.version() == QDataStream::Qt_4_2) {
         if (icon.isNull()) {
             s << 0;
         } else {
             QPixmapIconEngine *engine = static_cast<QPixmapIconEngine *>(icon.d->engine);
             int num_entries = engine->pixmaps.size();
             s << num_entries;
             for (int i=0; i < num_entries; ++i) {
                 s << engine->pixmaps.at(i).pixmap;
                 s << engine->pixmaps.at(i).fileName;
                 s << engine->pixmaps.at(i).size;
                 s << (uint) engine->pixmaps.at(i).mode;
                 s << (uint) engine->pixmaps.at(i).state;
             }
         }
     } else {
         s << QPixmap(icon.pixmap(22,22));
     }
     return s;
 }
operator>>()
QDataStream& operator>> (QDataStream & s, QIcon & icon)
Definition at line 1144 of file qicon.cpp.
Referenced by QIcon::data_ptr().
 {
     if (s.version() >= QDataStream::Qt_4_3) {
         icon = QIcon();
         QString key;
         s >> key;
         if (key == QLatin1String("QPixmapIconEngine")) {
             icon.d = new QIconPrivate;
             QIconEngineV2 *engine = new QPixmapIconEngine;
             icon.d->engine = engine;
             engine->read(s);
         } else if (key == QLatin1String("QIconLoaderEngine")) {
             icon.d = new QIconPrivate;
             QIconEngineV2 *engine = new QIconLoaderEngine();
             icon.d->engine = engine;
             engine->read(s);
 #if !defined (QT_NO_LIBRARY) && !defined(QT_NO_SETTINGS)
         } else if (QIconEngineFactoryInterfaceV2 *factory = qobject_cast<QIconEngineFactoryInterfaceV2*>(loaderV2()->instance(key))) {
             if (QIconEngineV2 *engine= factory->create()) {
                 icon.d = new QIconPrivate;
                 icon.d->engine = engine;
                 engine->read(s);
             }
 #endif
         }
     } else if (s.version() == QDataStream::Qt_4_2) {
         icon = QIcon();
         int num_entries;
         QPixmap pm;
         QString fileName;
         QSize sz;
         uint mode;
         uint state;
         s >> num_entries;
         for (int i=0; i < num_entries; ++i) {
             s >> pm;
             s >> fileName;
             s >> sz;
             s >> mode;
             s >> state;
             if (pm.isNull())
                 icon.addFile(fileName, sz, QIcon::Mode(mode), QIcon::State(state));
             else
                 icon.addPixmap(pm, QIcon::Mode(mode), QIcon::State(state));
         }
     } else {
         QPixmap pm;
         s >> pm;
         icon.addPixmap(pm);
     }
     return s;
 }
Q_GLOBAL_STATIC_WITH_ARGS()
Q_GLOBAL_STATIC_WITH_ARGS (QFactoryLoader , loader , (QIconEngineFactoryInterface_iid, QLatin1String("/iconengines"), Qt::CaseInsensitive))
Referenced by QPixmapIconEngine::virtual_hook().
QLatin1String()
QLatin1String ("/iconengines")
Referenced by QPixmapIconEngine::key(), operator>>(), and QPixmapIconEngine::virtual_hook().
qt_cleanup_icon_cache()
static void qt_cleanup_icon_cache () static
Definition at line 119 of file qicon.cpp.
 {
     qtIconCache()->clear();
 }
Variable Documentation
loaderV2
loaderV2
Definition at line 451 of file qicon.cpp.
Referenced by QIcon::addFile(), and operator>>().
QIconEngineFactoryInterfaceV2_iid
QIconEngineFactoryInterfaceV2_iid
Definition at line 451 of file qicon.cpp.
Referenced by QIconLoader::ensureInitialized().
serialNumCounter
QBasicAtomicInt serialNumCounter = Q_BASIC_ATOMIC_INITIALIZER(1) static
Definition at line 113 of file qicon.cpp.