Qt 4.8: /src/gui/image/qimagewriter.cpp File Reference
qimagewriter.cpp File Reference
#include "qimagewriter.h"
#include <qbytearray.h>
#include <qfile.h>
#include <qfileinfo.h>
#include <qimageiohandler.h>
#include <qset.h>
#include <qvariant.h>
#include <qcoreapplication.h>
#include <private/qfactoryloader_p.h>
#include <private/qbmphandler_p.h>
#include <private/qppmhandler_p.h>
#include <private/qxbmhandler_p.h>
#include <private/qxpmhandler_p.h>
#include <private/qpnghandler_p.h>
#include <private/qjpeghandler_p.h>
#include <private/qmnghandler_p.h>
#include <private/qtiffhandler_p.h>
Classes
class QImageWriterPrivate
Functions
if (device &&format.isEmpty())
if (suffixPluginIndex !=-1)
if (!handler &&!testFormat.isEmpty())
if (!testFormat.isEmpty())
if (!handler) return 0
Q_GLOBAL_STATIC_WITH_ARGS (QFactoryLoader, loader,(QImageIOHandlerFactoryInterface_iid, QLatin1String("/imageformats"))) static QImageIOHandler *createWriteHandlerHelper(QIODevice *device
handler setDevice (device)
Variables
const QByteArray & format
QImageIOHandler * handler = 0
QStringList keys = l->keys()
QFactoryLoader * l = loader()
QByteArray suffix
int suffixPluginIndex = -1
QByteArray testFormat = !form.isEmpty() ? form : suffix
Function Documentation
if() [1/5]
if (device &&format. isEmpty())
Definition at line 157 of file qimagewriter.cpp.
{
         // if there's no format, see if \a device is a file, and if so, find
         // the file suffix and find support for that format among our plugins.
         // this allows plugins to override our built-in handlers.
         if (QFile *file = qobject_cast<QFile *>(device)) {
             if (!(suffix = QFileInfo(file->fileName()).suffix().toLower().toLatin1()).isEmpty()) {
 #ifndef QT_NO_LIBRARY
                 int index = keys.indexOf(QString::fromLatin1(suffix));
                 if (index != -1)
                     suffixPluginIndex = index;
 #endif
             }
         }
     }
if() [2/5]
if (suffixPluginIndex ! = -1)
Definition at line 175 of file qimagewriter.cpp.
{
         // when format is missing, check if we can find a plugin for the
         // suffix.
         QImageIOPlugin *plugin = qobject_cast<QImageIOPlugin *>(l->instance(QString::fromLatin1(suffix)));
         if (plugin && (plugin->capabilities(device, suffix) & QImageIOPlugin::CanWrite))
             handler = plugin->create(device, suffix);
     }
if() [3/5]
if (!handler &&!testFormat. isEmpty())
Definition at line 185 of file qimagewriter.cpp.
{
         if (false) {
 #ifndef QT_NO_IMAGEFORMAT_PNG
         } else if (testFormat == "png") {
             handler = new QPngHandler;
 #endif
 #ifndef QT_NO_IMAGEFORMAT_JPEG
         } else if (testFormat == "jpg" || testFormat == "jpeg") {
             handler = new QJpegHandler;
 #endif
 #ifndef QT_NO_IMAGEFORMAT_MNG
         } else if (testFormat == "mng") {
             handler = new QMngHandler;
 #endif
 #ifndef QT_NO_IMAGEFORMAT_TIFF
         } else if (testFormat == "tif" || testFormat == "tiff") {
             handler = new QTiffHandler;
 #endif
 #ifdef QT_BUILTIN_GIF_READER
         } else if (testFormat == "gif") {
             handler = new QGifHandler;
 #endif
 #ifndef QT_NO_IMAGEFORMAT_BMP
         } else if (testFormat == "bmp") {
             handler = new QBmpHandler;
 #endif
 #ifndef QT_NO_IMAGEFORMAT_XPM
         } else if (testFormat == "xpm") {
             handler = new QXpmHandler;
 #endif
 #ifndef QT_NO_IMAGEFORMAT_XBM
         } else if (testFormat == "xbm") {
             handler = new QXbmHandler;
             handler->setOption(QImageIOHandler::SubType, testFormat);
 #endif
 #ifndef QT_NO_IMAGEFORMAT_PPM
         } else if (testFormat == "pbm" || testFormat == "pbmraw" || testFormat == "pgm"
                  || testFormat == "pgmraw" || testFormat == "ppm" || testFormat == "ppmraw") {
             handler = new QPpmHandler;
             handler->setOption(QImageIOHandler::SubType, testFormat);
 #endif
         }
     }
if() [4/5]
if (!testFormat. isEmpty())
Definition at line 230 of file qimagewriter.cpp.
{
         for (int i = 0; i < keys.size(); ++i) {
             QImageIOPlugin *plugin = qobject_cast<QImageIOPlugin *>(l->instance(keys.at(i)));
             if (plugin && (plugin->capabilities(device, testFormat) & QImageIOPlugin::CanWrite)) {
                 delete handler;
                 handler = plugin->create(device, testFormat);
                 break;
             }
         }
     }
if() [5/5]
if (! handler)
Definition at line 585 of file qcocoasharedwindowmethods_mac_p.h.
                  {
         // There is no toolbar, we have to draw a line on top of the line drawn by Cocoa.
         macDrawRectOnTop((void *)window);
     } else {
Q_GLOBAL_STATIC_WITH_ARGS()
Q_GLOBAL_STATIC_WITH_ARGS (QFactoryLoader , loader , (QImageIOHandlerFactoryInterface_iid, QLatin1String("/imageformats")))
setDevice()
handler setDevice (device)
Referenced by QGLOffscreen::QGLOffscreen(), and QtIcoHandler::QtIcoHandler().
Variable Documentation
format
const QByteArray& format
Initial value:
{
    QByteArray form = format.toLower()
Definition at line 145 of file qimagewriter.cpp.
handler
return handler = 0
Definition at line 148 of file qimagewriter.cpp.
Referenced by QDeclarativePropertyChanges::actions(), QICOPlugin::create(), QJpegPlugin::create(), QGifPlugin::create(), createReadHandlerHelper(), createTextAreaNode(), QDeclarativePropertyChangesPrivate::decode(), QTextDocumentLayoutPrivate::drawFlow(), QAbstractTextDocumentLayout::drawInlineObject(), QAbstractTextDocumentLayout::handlerForObject(), if(), QImageReader::imageFormat(), QAccessible::installRootObjectHandler(), QAccessible::installUpdateHandler(), QSvgTinyDocument::load(), QWSServerPrivate::newMouseHandler(), QScriptDebuggerFrontend::notifyCommandFinished(), QWSServer::openKeyboard(), QWSServer::openMouse(), QDesktopServices::openUrl(), parseFont(), parsePen(), QTextDocumentLayout::positionInlineObject(), QTest::qExec(), QWSIntKbPrivate::readKeyboardData(), QTextDocumentLayout::resizeInlineObject(), QAbstractTextDocumentLayout::resizeInlineObject(), QGraphicsItem::sceneEvent(), QXmlSimpleReader::setContentHandler(), QXmlSimpleReader::setDeclHandler(), QXmlSimpleReader::setDTDHandler(), QXmlSimpleReader::setEntityResolver(), QXmlSimpleReader::setErrorHandler(), QXmlSimpleReader::setLexicalHandler(), QXmlSchemaValidator::setMessageHandler(), QXmlSchemaPrivate::setMessageHandler(), QPatternist::XsdSchemaContext::setMessageHandler(), and QXmlReader::~QXmlReader().
keys
QStringList keys = l->keys()
Definition at line 153 of file qimagewriter.cpp.
Referenced by QTextCodec::availableCodecs(), QScriptEngine::availableExtensions(), QTextCodec::availableMibs(), QWinSettingsPrivate::children(), QGLGlyphCache::cleanCache(), QGLGlyphCache::cleanupContext(), QTestEventList::clear(), QMacPasteboardMimeTiff::convertFromMime(), createForName(), createReadHandlerHelper(), QBBEngine::doRequestUpdate(), fetchWacomToolId(), QGLGlyphCache::fontEngineDestroyed(), QScanThread::getUserConfigurations(), QTextLine::glyphs(), init_platform(), QApplication::inputContext(), QHash< QExplicitlySharedDataPointer, QHash >::isSharedWith(), QMetaEnumBuilder::key(), QAccessibleMenuItem::keyBindings(), QProcessEnvironment::operator!=(), Q_GLOBAL_STATIC_WITH_ARGS(), qax_startServer(), qax_stopServer(), qAxFactory(), QClassFactory::QClassFactory(), QMetaEnum::QMetaEnum(), qt_init(), qtValue(), QWSLock::QWSLock(), QConfFileSettingsPrivate::readPlistFile(), QMacSettingsPrivate::remove(), QMetaEnumBuilder::removeKey(), QMap< int, QFrameInfo >::setInsertInOrder(), QCoreWlanEngine::startTime(), QImageReader::supportedImageFormats(), QMenuPrivate::QMacMenuPrivate::syncAction(), QImage::textLanguages(), QImage::textList(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::toDFA(), QMetaEnumBuilder::value(), QMetaEnum::valueToKeys(), QFactoryInterface::~QFactoryInterface(), QFSFileEngine::~QFSFileEngine(), QTestEvent::~QTestEvent(), and QWSLock::~QWSLock().
l
QFactoryLoader* l = loader()
Definition at line 152 of file qimagewriter.cpp.
Referenced by QDateTimeEditPrivate::_q_editorCursorPositionChanged(), QHeaderViewPrivate::_q_sectionsRemoved(), _qdtoa(), QWSSoundServerProvider::add(), QLayout::addChildWidget(), QTessellatorPrivate::addEdges(), QBezier::addToPolygon(), QSystemTrayIconSys::addToTray(), QGridLayout::addWidget(), Graph< AnchorVertex, AnchorData >::adjacentVertices(), QTextCursorPrivate::adjustCursor(), QPatternist::NamePool::allocateBinding(), QPatternist::NamePool::allocateLocalName(), QPatternist::NamePool::allocateNamespace(), QPatternist::NamePool::allocatePrefix(), QPatternist::NamePool::allocateQName(), QJpUnicodeConv::asciiToUnicode(), QTextCodec::availableCodecs(), QAudioDeviceFactory::availableDevices(), QTextCodec::availableMibs(), QVector< QPoint >::back(), blend_color_generic(), blend_tiled_argb(), blend_tiled_generic(), blend_transformed_argb(), blend_transformed_tiled_argb(), blend_untransformed_generic(), blendTiled(), blendTransformed(), blendTransformedBilinear(), blendTransformedTiled(), bm_find(), bm_init_skiptable(), QLocalePrivate::bytearrayToLongLong(), QLocalePrivate::bytearrayToUnsLongLong(), QTextCodec::canEncode(), canonicalOrderHelper(), QPicturePrivate::checkFormat(), childKeysOrGroups(), QLayout::closestAcceptableSize(), QRect::contains(), QRectF::contains(), QWindowsMimeURI::convertFromMime(), createForName(), QTextLayout::createLine(), createReadHandlerHelper(), QLineControl::cursorRect(), QTextLine::cursorToX(), QOpenGLPaintEnginePrivate::curveToStencil(), QGIFFormat::decode(), QListData::detach_grow(), QAudioOutputPrivate::deviceReady(), QPatternist::NamePool::displayName(), QGIFFormat::disposePrevious(), do_size_hints(), QEventDispatcherUNIXPrivate::doSelect(), QTextLayout::draw(), QTextDocumentLayoutPrivate::drawBlock(), QMacStyle::drawControl(), QTextLayout::drawCursor(), QPainter::drawLine(), QOpenGLPaintEngine::drawLines(), QRasterPaintEngine::drawLines(), drawLines(), QX11PaintEngine::drawRects(), QMatrix::dy(), QTessellatorPrivate::edgeInChain(), QTriangulator< T >::ComplexToSimple::edgeIsLeftOfEdge(), QTriangulator< T >::SimpleToMonotone::edgeIsLeftOfEdge(), QBoxLayoutPrivate::effectiveMargins(), QGridLayoutPrivate::effectiveMargins(), QTextLayout::endLayout(), QPlainTextEditPrivate::ensureVisible(), QTestEventLoop::enterLoop(), QDir::entryInfoList(), QDir::entryList(), equal(), QVarLengthArray< QVariant, 9 >::erase(), QVector< QPoint >::erase(), escapedKey(), QWindowsStyle::eventFilter(), QDeclarativeBindingCompilerPrivate::exceptionId(), extractEncodingDecl(), QDeclarativeScriptParser::extractMetaData(), QDeclarativeScriptParser::extractPragmas(), QWSSoundServerPrivate::feedDevice(), QDeclarativeImportedNamespace::find(), QDateTimeParser::findDay(), QDateTimeParser::findMonth(), QResourceRoot::findNode(), QToolBarAreaLayoutInfo::fitLayout(), QFontInfo::fixedPitch(), QAudioOutputPrivate::freeBlocks(), QAudioInputPrivate::freeBlocks(), QFont::fromString(), getMacDateFormat(), getMacLocaleName(), getMacTimeFormat(), QDeclarativeParser::Property::getValue(), QFontSubset::glyphName(), good_offset(), handle_xdnd_position(), handle_xdnd_status(), handleSpans(), QGraphicsLayoutItemPrivate::hasHeightForWidth(), QIntersectionFinder::hasIntersections(), QGraphicsLayoutItemPrivate::hasWidthForHeight(), QTextDocumentLayout::hitTest(), QTextDocumentLayoutPrivate::hitTest(), QDeclarativeEnginePrivate::hsla(), QDeclarativeCompiledData::indexForLocation(), QByteArray::indexOf(), QIconModeViewBase::initBspTree(), QDirPrivate::initFileLists(), QDockWidget::initStyleOption(), jisx0201ToUnicode11(), jisx0208ToSjis(), QJpUnicodeConv::jisx0212ToUnicode(), jisx0212ToUnicode11(), QSQLiteDriverPlugin::keys(), QSQLite2DriverPlugin::keys(), QIBaseDriverPlugin::keys(), QPSQLDriverPlugin::keys(), QOCIDriverPlugin::keys(), QDB2DriverPlugin::keys(), QMYSQLDriverPlugin::keys(), QODBCDriverPlugin::keys(), QSymSQLDriverPlugin::keys(), QTDSDriverPlugin::keys(), QMetaEnum::keysToValue(), QString::lastIndexOf(), QStringRef::lastIndexOf(), QTextDocumentLayoutPrivate::layoutBlock(), QFontEngineXLFD::leading(), QFontEngineBox::leading(), QSortFilterProxyModel::lessThan(), lessThan(), QMetaType::load(), QFontEngineFT::loadGlyph(), mapToLowerCase(), QScanConverter::mergeCurve(), QToolBarAreaLayoutInfo::minimumSize(), QSplitter::minimumSizeHint(), QToolBarAreaLayoutInfo::moveToolBar(), QWindowsEnumerate::Next(), normalizedTimeval(), QLocalePrivate::numberToCLocale(), QPatternist::OperandsIterator::OperandsIterator(), QLinkedList< JSC::Identifier >::operator!=(), QList< QPostEvent >::operator!=(), QLinkedList< JSC::Identifier >::operator+(), QVector< QPoint >::operator+(), QList< QPostEvent >::operator+(), QList< QPostEvent >::operator+=(), QStandardItem::operator<(), QStringList::operator<<(), QLinkedList< JSC::Identifier >::operator<<(), operator<<(), QVector< QPoint >::operator<<(), QList< QPostEvent >::operator<<(), QImage::operator==(), operator>>(), QPlainTextEdit::paintEvent(), parse_locale_tag(), QHttpResponseHeader::parseLine(), QWorkspacePrivate::place(), QFontDatabase::pointSizes(), QTextHtmlImporter::processBlockNode(), QEventDispatcherUNIX::processEvents(), QTextHtmlImporter::processSpecialNodes(), QDeclarativeGridScaledImage::QDeclarativeGridScaledImage(), qFindByteArray(), qFindString(), qGetODBCVersion(), QJpUnicodeConv_JISX0221_ASCII::QJpUnicodeConv_JISX0221_ASCII(), QJpUnicodeConv_JISX0221_JISX0201::QJpUnicodeConv_JISX0221_JISX0201(), QJpUnicodeConv_Microsoft::QJpUnicodeConv_Microsoft(), QJpUnicodeConv_Sun::QJpUnicodeConv_Sun(), QJpUnicodeConv_Unicode_ASCII::QJpUnicodeConv_Unicode_ASCII(), QLineF::QLineF(), QList< QPostEvent >::QList(), qScanConvert(), qSplitTableQualifier(), qt_format_text(), qt_is_idn_enabled(), qt_mac_execute_apple_script(), qt_mac_menu_event(), qt_mac_removeMnemonics(), qt_section_chunk::qt_section_chunk(), qt_set_x11_resources(), QTest::qToInt(), QTransform::QTransform(), QUuid::QUuid(), QVariant::QVariant(), QXmlParseException::QXmlParseException(), QRasterPaintEnginePrivate::rasterizeLine_dashed(), QAudioInputPrivate::read(), QIODevicePrivateLinearBuffer::readAll(), QWinSettingsPrivate::readKey(), QStatusBar::reformat(), removeGroupSeparators(), QGraphicsLayoutPrivate::reparentChildItems(), QLayoutPrivate::reparentChildWidgets(), QAccessibleDisplay::role(), QZipReaderPrivate::scanFiles(), QDateTimeParser::sectionMaxSize(), QWSServerPrivate::sendQCopEvent(), QWinSettingsPrivate::set(), QLayout::setAlignment(), QLineF::setAngle(), QGraphicsWidget::setContentsMargins(), QWidget::setContentsMargins(), QDeclarativeDataBlob::setError(), QWidgetPrivate::setFont_helper(), QWidget::setLayout(), QGraphicsWidgetPrivate::setLayout_helper(), QDeclarativeDebugFileReference::setLineNumber(), QApplicationPrivate::setMaxWindowRect(), QWSQCopSendCommand::setMessage(), QXlibWindow::setMWMHints(), SetMWMHints(), QWSRegionNameCommand::setName(), QTableView::setSelection(), QApplication::setStartDragDistance(), QWidget::setTabOrder(), QXcbWindow::setWindowFlags(), QDial::setWrapping(), QTextEngine::shapeTextMac(), shift(), QSplitter::sizeHint(), QGraphicsProxyWidget::sizeHint(), QToolBarAreaLayoutInfo::sizeHint(), QFontDatabase::smoothSizes(), QDirPrivate::sortFileList(), SoundPlayProc(), QColor::spec(), QSettingsPrivate::splitArgs(), QAccessibleLineEdit::state(), QPatternist::NamePool::stringForLocalName(), QPatternist::NamePool::stringForNamespace(), QPatternist::NamePool::stringForPrefix(), QSettingsPrivate::stringListToVariantList(), QOpenGLPaintEnginePrivate::strokePathFastPen(), QFontDatabase::styles(), QImageReader::supportedImageFormats(), QLinkedList< JSC::Identifier >::swap(), QBoxLayout::takeAt(), QFormLayout::takeAt(), QGridLayoutPrivate::takeAt(), QWidget::takeLayout(), QAccessibleDisplay::text(), timerSourcePrepareHelper(), QByteArray::toBase64(), QPatternist::NamePool::toClarkName(), QPatternist::NamePool::toLexical(), QApplication::topLevelAt(), QColor::toRgb(), QFontEngineXLFD::toUnicode(), QByteArray::trimmed(), QString::trimmed(), trimRef(), QTextUndoCommand::tryMerge(), QWSSoundServerClient::tryReadCommand(), ucstrcmp(), unicode11ToJisx0201(), unicode11ToJisx0208(), unicode11ToJisx0212(), QJpUnicodeConv::unicodeToAscii(), QGL2PaintEngineExPrivate::updateBrushUniforms(), QNetworkConfigurationManagerPrivate::updateConfigurations(), QLineControl::updateDisplayText(), QOpenGLPaintEnginePrivate::updateGradient(), QX11Data::xdndHandleDrop(), QX11Data::xdndHandleEnter(), QX11Data::xdndHandleFinished(), QX11Data::xdndHandleLeave(), xic_draw_callback(), QPatternist::yyparse(), and QLayout::~QLayout().
suffix
QByteArray suffix
Definition at line 147 of file qimagewriter.cpp.
Referenced by QFileDialogPrivate::_q_createDirectory(), QPrintPreviewDialogPrivate::_q_print(), QUnixPrintWidgetPrivate::_q_printerChanged(), QFileDialogPrivate::_q_useNameFilter(), QIcon::addFile(), comify(), createReadHandlerHelper(), find_translation(), QBenchmarkValgrindUtils::getNewestFileName(), if(), QLibrary::isLibrary(), QTranslator::load(), QLibraryPrivate::load_sys(), QFileInfo::operator!=(), QFactoryLoader::QFactoryLoader(), QPageSetupWidget::QPageSetupWidget(), QDeclarativeImportDatabase::resolvePlugin(), QFileDialog::setDefaultSuffix(), QFileInfo::symLinkTarget(), QPageSetupWidget::unitChanged(), and QTextDocumentWriter::write().
suffixPluginIndex
int suffixPluginIndex = -1
Definition at line 154 of file qimagewriter.cpp.
Referenced by createReadHandlerHelper().
testFormat
QByteArray testFormat = !form.isEmpty() ? form : suffix
Definition at line 172 of file qimagewriter.cpp.
Referenced by createReadHandlerHelper().