Qt 4.8: /src/gui/image/qimage.h File Reference
qimage.h File Reference
#include <QtGui/qtransform.h>
#include <QtGui/qpaintdevice.h>
#include <QtGui/qrgb.h>
#include <QtCore/qbytearray.h>
#include <QtCore/qrect.h>
#include <QtCore/qstring.h>
Classes
class QImage
The QImage class provides a hardware-independent image representation that allows direct access to the pixel data, and can be used as a paint device.
class QImageTextKeyLang
class QList< T >
The QList class is a template class that provides lists.
class QVector< T >
The QVector class is a template class that provides a dynamic array.
Functions
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &, const QImage &)
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &, QImage &)
Q_DECLARE_TYPEINFO (QImage, Q_MOVABLE_TYPE)
Function Documentation
operator<<()
Q_GUI_EXPORT QDataStream& operator<< (QDataStream & , const QImage &) related
Definition at line 5406 of file qimage.cpp.
Referenced by QImage::setPixel().
 {
     if (s.version() >= 5) {
         if (image.isNull()) {
             s << (qint32) 0; // null image marker
             return s;
         } else {
             s << (qint32) 1;
             // continue ...
         }
     }
     QImageWriter writer(s.device(), s.version() == 1 ? "bmp" : "png");
     writer.write(image);
     return s;
 }
operator>>()
Q_GUI_EXPORT QDataStream& operator>> (QDataStream & , QImage &) related
Definition at line 5435 of file qimage.cpp.
Referenced by QImage::setPixel().
 {
     if (s.version() >= 5) {
         qint32 nullMarker;
         s >> nullMarker;
         if (!nullMarker) {
             image = QImage(); // null image
             return s;
         }
     }
     image = QImageReader(s.device(), 0).read();
     return s;
 }
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QImage , Q_MOVABLE_TYPE)
Referenced by QImage::data_ptr().