Qt 4.8: /src/gui/image/qimage_p.h File Reference
qimage_p.h File Reference
#include <QtCore/qglobal.h>
#include <QVector>
#include <QMap>
Classes
struct QImageData
Functions
Q_GUI_EXPORT void qGamma_correct_back_to_linear_cs (QImage *image)
void qInitImageConversions ()
int qt_depthForFormat (QImage::Format format)
Function Documentation
qGamma_correct_back_to_linear_cs()
Q_GUI_EXPORT void qGamma_correct_back_to_linear_cs (QImage * image)
Definition at line 3938 of file qimage.cpp.
Referenced by QFontEngineMac::alphaRGBMapForGlyph().
 {
     extern uchar qt_pow_rgb_gamma[256];
     // gamma correct the pixels back to linear color space...
     int h = image->height();
     int w = image->width();
     for (int y=0; y<h; ++y) {
         uint *pixels = (uint *) image->scanLine(y);
         for (int x=0; x<w; ++x) {
             uint p = pixels[x];
             uint r = qt_pow_rgb_gamma[qRed(p)];
             uint g = qt_pow_rgb_gamma[qGreen(p)];
             uint b = qt_pow_rgb_gamma[qBlue(p)];
             pixels[x] = (r << 16) | (g << 8) | b | 0xff000000;
         }
     }
 }
qInitImageConversions()
void qInitImageConversions ()
Definition at line 3909 of file qimage.cpp.
 {
     const uint features = qDetectCPUFeatures();
     Q_UNUSED(features);
 #ifdef QT_HAVE_SSE2
     if (features & SSE2) {
         extern bool convert_ARGB_to_ARGB_PM_inplace_sse2(QImageData *data, Qt::ImageConversionFlags);
         inplace_converter_map[QImage::Format_ARGB32][QImage::Format_ARGB32_Premultiplied] = convert_ARGB_to_ARGB_PM_inplace_sse2;
     }
 #endif
 #ifdef QT_HAVE_SSSE3
     if (features & SSSE3) {
         extern void convert_RGB888_to_RGB32_ssse3(QImageData *dest, const QImageData *src, Qt::ImageConversionFlags);
         converter_map[QImage::Format_RGB888][QImage::Format_RGB32] = convert_RGB888_to_RGB32_ssse3;
         converter_map[QImage::Format_RGB888][QImage::Format_ARGB32] = convert_RGB888_to_RGB32_ssse3;
         converter_map[QImage::Format_RGB888][QImage::Format_ARGB32_Premultiplied] = convert_RGB888_to_RGB32_ssse3;
     }
 #endif
 #ifdef QT_HAVE_NEON
     if (features & NEON) {
         extern void convert_RGB888_to_RGB32_neon(QImageData *dest, const QImageData *src, Qt::ImageConversionFlags);
         converter_map[QImage::Format_RGB888][QImage::Format_RGB32] = convert_RGB888_to_RGB32_neon;
         converter_map[QImage::Format_RGB888][QImage::Format_ARGB32] = convert_RGB888_to_RGB32_neon;
         converter_map[QImage::Format_RGB888][QImage::Format_ARGB32_Premultiplied] = convert_RGB888_to_RGB32_neon;
     }
 #endif
 }
qt_depthForFormat()
int qt_depthForFormat (QImage::Format format) inline
Definition at line 116 of file qimage_p.h.
Referenced by QImage::bitPlaneCount(), QImageData::create(), and QRasterPixmapData::fill().
 {
     int depth = 0;
     switch(format) {
     case QImage::Format_Invalid:
     case QImage::NImageFormats:
         Q_ASSERT(false);
     case QImage::Format_Mono:
     case QImage::Format_MonoLSB:
         depth = 1;
         break;
     case QImage::Format_Indexed8:
         depth = 8;
         break;
     case QImage::Format_RGB32:
     case QImage::Format_ARGB32:
     case QImage::Format_ARGB32_Premultiplied:
         depth = 32;
         break;
     case QImage::Format_RGB555:
     case QImage::Format_RGB16:
     case QImage::Format_RGB444:
     case QImage::Format_ARGB4444_Premultiplied:
         depth = 16;
         break;
     case QImage::Format_RGB666:
     case QImage::Format_ARGB6666_Premultiplied:
     case QImage::Format_ARGB8565_Premultiplied:
     case QImage::Format_ARGB8555_Premultiplied:
     case QImage::Format_RGB888:
         depth = 24;
         break;
     }
     return depth;
 }