Qt 4.8: /src/gui/image/qimage.cpp File Reference
qimage.cpp File Reference
#include "qimage.h"
#include "qdatastream.h"
#include "qbuffer.h"
#include "qmap.h"
#include "qmatrix.h"
#include "qtransform.h"
#include "qimagereader.h"
#include "qimagewriter.h"
#include "qstringlist.h"
#include "qvariant.h"
#include "qimagepixmapcleanuphooks_p.h"
#include <ctype.h>
#include <stdlib.h>
#include <limits.h>
#include <math.h>
#include <private/qdrawhelper_p.h>
#include <private/qmemrotate_p.h>
#include <private/qpixmapdata_p.h>
#include <private/qimagescale_p.h>
#include <private/qsimd_p.h>
#include <qhash.h>
#include <private/qpaintengine_raster_p.h>
#include <private/qimage_p.h>
#include <private/qfont_p.h>
Classes
struct QRgbMap
Macros
#define CONVERT_DECL(DST, SRC)
#define CONVERT_PTR(DST, SRC) convert_##SRC##_to_##DST
#define DITHER(p, m) ((uchar) ((p * (m) + 127) / 255))
#define DITHER(p, d, m) ((uchar) ((((256 * (m) + (m) + 1)) * (p) + (d)) >> 16))
#define INDEXOF(r, g, b) (((r)*(MAX_G+1)+(g))*(MAX_B+1)+(b))
#define IWX_LSB(b)
#define IWX_MSB(b)
#define IWX_PIX(b)
#define MAX_B 5
#define MAX_G 5
#define MAX_R 5
#define PIX(x, y) (*((QRgb*)scanLine(y)+x) & 0x00ffffff)
#define QIMAGE_SANITYCHECK_MEMORY(image)
Typedefs
typedef void(* Image_Converter) (QImageData *dest, const QImageData *src, Qt::ImageConversionFlags)
typedef bool(* InPlace_Image_Converter) (QImageData *data, Qt::ImageConversionFlags)
Functions
static bool checkPixelSize (const QImage::Format format)
static int closestMatch (QRgb pixel, const QVector< QRgb > &clut)
static void convert_ARGB_PM_to_ARGB (QImageData *dest, const QImageData *src, Qt::ImageConversionFlags)
static void convert_ARGB_PM_to_Indexed8 (QImageData *dst, const QImageData *src, Qt::ImageConversionFlags flags)
static void convert_ARGB_PM_to_Mono (QImageData *dst, const QImageData *src, Qt::ImageConversionFlags flags)
static void convert_ARGB_PM_to_RGB (QImageData *dest, const QImageData *src, Qt::ImageConversionFlags)
static void convert_ARGB_to_ARGB_PM (QImageData *dest, const QImageData *src, Qt::ImageConversionFlags)
static bool convert_ARGB_to_ARGB_PM_inplace (QImageData *data, Qt::ImageConversionFlags)
static void convert_ARGB_to_Indexed8 (QImageData *dst, const QImageData *src, Qt::ImageConversionFlags flags)
static bool convert_indexed8_to_ARGB_PM_inplace (QImageData *data, Qt::ImageConversionFlags)
static bool convert_indexed8_to_RGB16_inplace (QImageData *data, Qt::ImageConversionFlags)
static bool convert_indexed8_to_RGB_inplace (QImageData *data, Qt::ImageConversionFlags)
static void convert_Indexed8_to_X32 (QImageData *dest, const QImageData *src, Qt::ImageConversionFlags)
static void convert_Mono_to_Indexed8 (QImageData *dest, const QImageData *src, Qt::ImageConversionFlags)
static void convert_Mono_to_X32 (QImageData *dest, const QImageData *src, Qt::ImageConversionFlags)
static void convert_RGB_to_Indexed8 (QImageData *dst, const QImageData *src, Qt::ImageConversionFlags flags)
static bool convert_RGB_to_RGB16_inplace (QImageData *data, Qt::ImageConversionFlags)
static void convert_X_to_Mono (QImageData *dst, const QImageData *src, Qt::ImageConversionFlags flags)
static QImage convertWithPalette (const QImage &src, QImage::Format format, const QVector< QRgb > &clut)
static void dither_to_Mono (QImageData *dst, const QImageData *src, Qt::ImageConversionFlags flags, bool fromalpha)
static QVector< QRgb > fix_color_table (const QVector< QRgb > &ctbl, QImage::Format format)
static void mask_alpha_converter (QImageData *dest, const QImageData *src, Qt::ImageConversionFlags)
QDataStream & operator<< (QDataStream &s, const QImage &image)
QDataStream & operator>> (QDataStream &s, QImage &image)
static int pixel_distance (QRgb p1, QRgb p2)
void qGamma_correct_back_to_linear_cs (QImage *image)
void qInitImageConversions ()
const uchar * qt_get_bitflip_array ()
const QVector< QRgb > * qt_image_colortable (const QImage &image)
Q_GUI_EXPORT qint64 qt_image_id (const QImage &image)
bool qt_read_xpm_image_or_array (QIODevice *device, const char *const *source, QImage &image)
bool qt_xForm_helper (const QTransform &trueMat, int xoffset, int type, int depth, uchar *dptr, int dbpl, int p_inc, int dHeight, const uchar *sptr, int sbpl, int sWidth, int sHeight)
static QImage rotated180 (const QImage &src)
static QImage rotated270 (const QImage &src)
static QImage rotated90 (const QImage &src)
static QImage smoothScaled (const QImage &source, int w, int h)
static void swap_bit_order (QImageData *dest, const QImageData *src, Qt::ImageConversionFlags)
Variables
static const uchar bitflip [256]
static Image_Converter converter_map [QImage::NImageFormats][QImage::NImageFormats]
static InPlace_Image_Converter inplace_converter_map [QImage::NImageFormats][QImage::NImageFormats]
QBasicAtomicInt qimage_serial_number = Q_BASIC_ATOMIC_INITIALIZER(1)
Macro Definition Documentation
CONVERT_DECL
#define CONVERT_DECL (DST, SRC)
Value:
static void convert_##SRC##_to_##DST(QImageData *dest,              \
                                         const QImageData *src,         \
                                         Qt::ImageConversionFlags)      \
    {                                                                   \
        qt_rectconvert<DST, SRC>(reinterpret_cast<DST*>(dest->data),    \
                                 reinterpret_cast<const SRC*>(src->data), \
                                 0, 0, src->width, src->height,         \
                                 dest->bytes_per_line, src->bytes_per_line); \
    }
Definition at line 3456 of file qimage.cpp.
CONVERT_PTR
#define CONVERT_PTR (DST, SRC) convert_##SRC##_to_##DST
Definition at line 3490 of file qimage.cpp.
DITHER [1/2]
#define DITHER (p, m) ((uchar) ((p * (m) + 127) / 255))
Referenced by convert_RGB_to_Indexed8().
DITHER [2/2]
#define DITHER (p, d, m) ((uchar) ((((256 * (m) + (m) + 1)) * (p) + (d)) >> 16))
INDEXOF
#define INDEXOF (r, g, b) (((r)*(MAX_G+1)+(g))*(MAX_B+1)+(b))
Referenced by convert_RGB_to_Indexed8().
IWX_LSB
#define IWX_LSB (b)
Value:
if (trigx < maxws && trigy < maxhs) {                              \
                            if (*(sptr+sbpl*(trigy>>12)+(trigx>>15)) &                      \
                                 (1 << ((trigx>>12)&7)))                              \
                                *dptr |= b;                                              \
                        }                                                              \
                        trigx += m11;                                                      \
                        trigy += m12;
Definition at line 6083 of file qimage.cpp.
Referenced by qt_xForm_helper().
IWX_MSB
#define IWX_MSB (b)
Value:
if (trigx < maxws && trigy < maxhs) {                              \
                            if (*(sptr+sbpl*(trigy>>12)+(trigx>>15)) &                      \
                                 (1 << (7-((trigx>>12)&7))))                              \
                                *dptr |= b;                                              \
                        }                                                              \
                        trigx += m11;                                                      \
                        trigy += m12;
Definition at line 6074 of file qimage.cpp.
Referenced by qt_xForm_helper().
IWX_PIX
#define IWX_PIX (b)
Value:
if (trigx < maxws && trigy < maxhs) {                              \
                            if ((*(sptr+sbpl*(trigy>>12)+(trigx>>15)) &              \
                                 (1 << (7-((trigx>>12)&7)))) == 0)                      \
                                *dptr &= ~b;                                              \
                        }                                                              \
                        trigx += m11;                                                      \
                        trigy += m12;
Definition at line 6092 of file qimage.cpp.
Referenced by qt_xForm_helper().
MAX_B
#define MAX_B 5
Referenced by convert_RGB_to_Indexed8().
MAX_G
#define MAX_G 5
Referenced by convert_RGB_to_Indexed8().
MAX_R
#define MAX_R 5
Referenced by convert_RGB_to_Indexed8().
PIX
#define PIX (x, y) (*((QRgb*)scanLine(y)+x) & 0x00ffffff)
Referenced by QImage::createHeuristicMask(), and QX11PixmapData::fromImage().
QIMAGE_SANITYCHECK_MEMORY
#define QIMAGE_SANITYCHECK_MEMORY (image)
Value:
if ((image).isNull()) { \
        qWarning("QImage: out of memory, returning null image"); \
        return QImage(); \
    }
Definition at line 105 of file qimage.cpp.
Referenced by QImage::alphaChannel(), QImage::convertToFormat(), convertWithPalette(), QImage::createHeuristicMask(), QImage::createMaskFromColor(), QImage::mirrored(), QImage::rgbSwapped(), rotated270(), rotated90(), QImage::setPixel(), and QImage::transformed().
Typedef Documentation
Image_Converter
typedef void(* Image_Converter) (QImageData *dest, const QImageData *src, Qt::ImageConversionFlags)
Definition at line 2432 of file qimage.cpp.
InPlace_Image_Converter
typedef bool(* InPlace_Image_Converter) (QImageData *data, Qt::ImageConversionFlags)
Definition at line 2434 of file qimage.cpp.
Function Documentation
checkPixelSize()
static bool checkPixelSize (const QImage::Format format) inline static
Definition at line 76 of file qimage.cpp.
Referenced by QImageData::create().
 {
     switch (format) {
     case QImage::Format_ARGB8565_Premultiplied:
         return (sizeof(qargb8565) == 3);
     case QImage::Format_RGB666:
         return (sizeof(qrgb666) == 3);
     case QImage::Format_ARGB6666_Premultiplied:
         return (sizeof(qargb6666) == 3);
     case QImage::Format_RGB555:
         return (sizeof(qrgb555) == 2);
     case QImage::Format_ARGB8555_Premultiplied:
         return (sizeof(qargb8555) == 3);
     case QImage::Format_RGB888:
         return (sizeof(qrgb888) == 3);
     case QImage::Format_RGB444:
         return (sizeof(qrgb444) == 2);
     case QImage::Format_ARGB4444_Premultiplied:
         return (sizeof(qargb4444) == 2);
     default:
         return true;
     }
 }
closestMatch()
static int closestMatch (QRgb pixel, const QVector< QRgb > & clut) inline static
Definition at line 4015 of file qimage.cpp.
Referenced by convertWithPalette(), QIconLoaderEngine::entryForSize(), and QNetworkAuthenticationCache::insert().
{
     int idx = 0;
     int current_distance = INT_MAX;
     for (int i=0; i<clut.size(); ++i) {
         int dist = pixel_distance(pixel, clut.at(i));
         if (dist < current_distance) {
             current_distance = dist;
             idx = i;
         }
     }
     return idx;
 }
convert_ARGB_PM_to_ARGB()
static void convert_ARGB_PM_to_ARGB (QImageData * dest, const QImageData * src, Qt::ImageConversionFlags) static
Definition at line 2663 of file qimage.cpp.
Referenced by convert_ARGB_PM_to_Indexed8(), and convert_ARGB_PM_to_Mono().
 {
     Q_ASSERT(src->format == QImage::Format_ARGB32_Premultiplied);
     Q_ASSERT(dest->format == QImage::Format_ARGB32);
     Q_ASSERT(src->width == dest->width);
     Q_ASSERT(src->height == dest->height);
     const int src_pad = (src->bytes_per_line >> 2) - src->width;
     const int dest_pad = (dest->bytes_per_line >> 2) - dest->width;
     const QRgb *src_data = (QRgb *) src->data;
     QRgb *dest_data = (QRgb *) dest->data;
     for (int i = 0; i < src->height; ++i) {
         const QRgb *end = src_data + src->width;
         while (src_data < end) {
             *dest_data = INV_PREMUL(*src_data);
             ++src_data;
             ++dest_data;
         }
         src_data += src_pad;
         dest_data += dest_pad;
     }
 }
convert_ARGB_PM_to_Indexed8()
static void convert_ARGB_PM_to_Indexed8 (QImageData * dst, const QImageData * src, Qt::ImageConversionFlags flags) static
Definition at line 3329 of file qimage.cpp.
 {
     QScopedPointer<QImageData> tmp(QImageData::create(QSize(src->width, src->height), QImage::Format_ARGB32));
     convert_ARGB_PM_to_ARGB(tmp.data(), src, flags);
     convert_RGB_to_Indexed8(dst, tmp.data(), flags);
 }
convert_ARGB_PM_to_Mono()
static void convert_ARGB_PM_to_Mono (QImageData * dst, const QImageData * src, Qt::ImageConversionFlags flags) static
Definition at line 3049 of file qimage.cpp.
 {
     QScopedPointer<QImageData> tmp(QImageData::create(QSize(src->width, src->height), QImage::Format_ARGB32));
     convert_ARGB_PM_to_ARGB(tmp.data(), src, flags);
     dither_to_Mono(dst, tmp.data(), flags, false);
 }
convert_ARGB_PM_to_RGB()
static void convert_ARGB_PM_to_RGB (QImageData * dest, const QImageData * src, Qt::ImageConversionFlags) static
Definition at line 2687 of file qimage.cpp.
 {
     Q_ASSERT(src->format == QImage::Format_ARGB32_Premultiplied);
     Q_ASSERT(dest->format == QImage::Format_RGB32);
     Q_ASSERT(src->width == dest->width);
     Q_ASSERT(src->height == dest->height);
     const int src_pad = (src->bytes_per_line >> 2) - src->width;
     const int dest_pad = (dest->bytes_per_line >> 2) - dest->width;
     const QRgb *src_data = (QRgb *) src->data;
     QRgb *dest_data = (QRgb *) dest->data;
     for (int i = 0; i < src->height; ++i) {
         const QRgb *end = src_data + src->width;
         while (src_data < end) {
             *dest_data = 0xff000000 | INV_PREMUL(*src_data);
             ++src_data;
             ++dest_data;
         }
         src_data += src_pad;
         dest_data += dest_pad;
     }
 }
convert_ARGB_to_ARGB_PM()
static void convert_ARGB_to_ARGB_PM (QImageData * dest, const QImageData * src, Qt::ImageConversionFlags) static
Definition at line 2436 of file qimage.cpp.
 {
     Q_ASSERT(src->format == QImage::Format_ARGB32);
     Q_ASSERT(dest->format == QImage::Format_ARGB32_Premultiplied);
     Q_ASSERT(src->width == dest->width);
     Q_ASSERT(src->height == dest->height);
     const int src_pad = (src->bytes_per_line >> 2) - src->width;
     const int dest_pad = (dest->bytes_per_line >> 2) - dest->width;
     const QRgb *src_data = (QRgb *) src->data;
     QRgb *dest_data = (QRgb *) dest->data;
     for (int i = 0; i < src->height; ++i) {
         const QRgb *end = src_data + src->width;
         while (src_data < end) {
             *dest_data = PREMUL(*src_data);
             ++src_data;
             ++dest_data;
         }
         src_data += src_pad;
         dest_data += dest_pad;
     }
 }
convert_ARGB_to_ARGB_PM_inplace()
static bool convert_ARGB_to_ARGB_PM_inplace (QImageData * data, Qt::ImageConversionFlags) static
Definition at line 2460 of file qimage.cpp.
 {
     Q_ASSERT(data->format == QImage::Format_ARGB32);
     const int pad = (data->bytes_per_line >> 2) - data->width;
     QRgb *rgb_data = (QRgb *) data->data;
     for (int i = 0; i < data->height; ++i) {
         const QRgb *end = rgb_data + data->width;
         while (rgb_data < end) {
             *rgb_data = PREMUL(*rgb_data);
             ++rgb_data;
         }
         rgb_data += pad;
     }
     data->format = QImage::Format_ARGB32_Premultiplied;
     return true;
 }
convert_ARGB_to_Indexed8()
static void convert_ARGB_to_Indexed8 (QImageData * dst, const QImageData * src, Qt::ImageConversionFlags flags) static
Definition at line 3336 of file qimage.cpp.
 {
     convert_RGB_to_Indexed8(dst, src, flags);
 }
convert_indexed8_to_ARGB_PM_inplace()
static bool convert_indexed8_to_ARGB_PM_inplace (QImageData * data, Qt::ImageConversionFlags) static
Definition at line 2479 of file qimage.cpp.
 {
     Q_ASSERT(data->format == QImage::Format_Indexed8);
     const int depth = 32;
     const int dst_bytes_per_line = ((data->width * depth + 31) >> 5) << 2;
     const int nbytes = dst_bytes_per_line * data->height;
     uchar *const newData = (uchar *)realloc(data->data, nbytes);
     if (!newData)
         return false;
     data->data = newData;
     // start converting from the end because the end image is bigger than the source
     uchar *src_data = newData + data->nbytes; // end of src
     quint32 *dest_data = (quint32 *) (newData + nbytes); // end of dest > end of src
     const int width = data->width;
     const int src_pad = data->bytes_per_line - width;
     const int dest_pad = (dst_bytes_per_line >> 2) - width;
     if (data->colortable.size() == 0) {
         data->colortable.resize(256);
         for (int i = 0; i < 256; ++i)
             data->colortable[i] = qRgb(i, i, i);
     } else {
         for (int i = 0; i < data->colortable.size(); ++i)
             data->colortable[i] = PREMUL(data->colortable.at(i));
         // Fill the rest of the table in case src_data > colortable.size()
         const int oldSize = data->colortable.size();
         const QRgb lastColor = data->colortable.at(oldSize - 1);
         data->colortable.insert(oldSize, 256 - oldSize, lastColor);
     }
     for (int i = 0; i < data->height; ++i) {
         src_data -= src_pad;
         dest_data -= dest_pad;
         for (int pixI = 0; pixI < width; ++pixI) {
             --src_data;
             --dest_data;
             *dest_data = data->colortable.at(*src_data);
         }
     }
     data->colortable = QVector<QRgb>();
     data->format = QImage::Format_ARGB32_Premultiplied;
     data->bytes_per_line = dst_bytes_per_line;
     data->depth = depth;
     data->nbytes = nbytes;
     return true;
 }
convert_indexed8_to_RGB16_inplace()
static bool convert_indexed8_to_RGB16_inplace (QImageData * data, Qt::ImageConversionFlags) static
Definition at line 2580 of file qimage.cpp.
 {
     Q_ASSERT(data->format == QImage::Format_Indexed8);
     const int depth = 16;
     const int dst_bytes_per_line = ((data->width * depth + 31) >> 5) << 2;
     const int nbytes = dst_bytes_per_line * data->height;
     uchar *const newData = (uchar *)realloc(data->data, nbytes);
     if (!newData)
         return false;
     data->data = newData;
     // start converting from the end because the end image is bigger than the source
     uchar *src_data = newData + data->nbytes;
     quint16 *dest_data = (quint16 *) (newData + nbytes);
     const int width = data->width;
     const int src_pad = data->bytes_per_line - width;
     const int dest_pad = (dst_bytes_per_line >> 1) - width;
     quint16 colorTableRGB16[256];
     if (data->colortable.isEmpty()) {
         for (int i = 0; i < 256; ++i)
             colorTableRGB16[i] = qt_colorConvert<quint16, quint32>(qRgb(i, i, i), 0);
     } else {
         // 1) convert the existing colors to RGB16
         const int tableSize = data->colortable.size();
         for (int i = 0; i < tableSize; ++i)
             colorTableRGB16[i] = qt_colorConvert<quint16, quint32>(data->colortable.at(i), 0);
         data->colortable = QVector<QRgb>();
         // 2) fill the rest of the table in case src_data > colortable.size()
         const quint16 lastColor = colorTableRGB16[tableSize - 1];
         for (int i = tableSize; i < 256; ++i)
             colorTableRGB16[i] = lastColor;
     }
     for (int i = 0; i < data->height; ++i) {
         src_data -= src_pad;
         dest_data -= dest_pad;
         for (int pixI = 0; pixI < width; ++pixI) {
             --src_data;
             --dest_data;
             *dest_data = colorTableRGB16[*src_data];
         }
     }
     data->format = QImage::Format_RGB16;
     data->bytes_per_line = dst_bytes_per_line;
     data->depth = depth;
     data->nbytes = nbytes;
     return true;
 }
convert_indexed8_to_RGB_inplace()
static bool convert_indexed8_to_RGB_inplace (QImageData * data, Qt::ImageConversionFlags) static
Definition at line 2531 of file qimage.cpp.
 {
     Q_ASSERT(data->format == QImage::Format_Indexed8);
     const int depth = 32;
     const int dst_bytes_per_line = ((data->width * depth + 31) >> 5) << 2;
     const int nbytes = dst_bytes_per_line * data->height;
     uchar *const newData = (uchar *)realloc(data->data, nbytes);
     if (!newData)
         return false;
     data->data = newData;
     // start converting from the end because the end image is bigger than the source
     uchar *src_data = newData + data->nbytes;
     quint32 *dest_data = (quint32 *) (newData + nbytes);
     const int width = data->width;
     const int src_pad = data->bytes_per_line - width;
     const int dest_pad = (dst_bytes_per_line >> 2) - width;
     if (data->colortable.size() == 0) {
         data->colortable.resize(256);
         for (int i = 0; i < 256; ++i)
             data->colortable[i] = qRgb(i, i, i);
     } else {
         // Fill the rest of the table in case src_data > colortable.size()
         const int oldSize = data->colortable.size();
         const QRgb lastColor = data->colortable.at(oldSize - 1);
         data->colortable.insert(oldSize, 256 - oldSize, lastColor);
     }
     for (int i = 0; i < data->height; ++i) {
         src_data -= src_pad;
         dest_data -= dest_pad;
         for (int pixI = 0; pixI < width; ++pixI) {
             --src_data;
             --dest_data;
             *dest_data = (quint32) data->colortable.at(*src_data);
         }
     }
     data->colortable = QVector<QRgb>();
     data->format = QImage::Format_RGB32;
     data->bytes_per_line = dst_bytes_per_line;
     data->depth = depth;
     data->nbytes = nbytes;
     return true;
 }
convert_Indexed8_to_X32()
static void convert_Indexed8_to_X32 (QImageData * dest, const QImageData * src, Qt::ImageConversionFlags) static
Definition at line 3341 of file qimage.cpp.
 {
     Q_ASSERT(src->format == QImage::Format_Indexed8);
     Q_ASSERT(dest->format == QImage::Format_RGB32
              || dest->format == QImage::Format_ARGB32
              || dest->format == QImage::Format_ARGB32_Premultiplied);
     Q_ASSERT(src->width == dest->width);
     Q_ASSERT(src->height == dest->height);
     QVector<QRgb> colorTable = fix_color_table(src->colortable, dest->format);
     if (colorTable.size() == 0) {
         colorTable.resize(256);
         for (int i=0; i<256; ++i)
             colorTable[i] = qRgb(i, i, i);
     }
     int w = src->width;
     const uchar *src_data = src->data;
     uchar *dest_data = dest->data;
     int tableSize = colorTable.size() - 1;
     for (int y = 0; y < src->height; y++) {
         uint *p = (uint *)dest_data;
         const uchar *b = src_data;
         uint *end = p + w;
         while (p < end)
             *p++ = colorTable.at(qMin<int>(tableSize, *b++));
         src_data += src->bytes_per_line;
         dest_data += dest->bytes_per_line;
     }
 }
convert_Mono_to_Indexed8()
static void convert_Mono_to_Indexed8 (QImageData * dest, const QImageData * src, Qt::ImageConversionFlags) static
Definition at line 3416 of file qimage.cpp.
 {
     Q_ASSERT(src->format == QImage::Format_Mono || src->format == QImage::Format_MonoLSB);
     Q_ASSERT(dest->format == QImage::Format_Indexed8);
     Q_ASSERT(src->width == dest->width);
     Q_ASSERT(src->height == dest->height);
     QVector<QRgb> ctbl = src->colortable;
     if (ctbl.size() > 2) {
         ctbl.resize(2);
     } else if (ctbl.size() < 2) {
         if (ctbl.size() == 0)
             ctbl << 0xff000000;
         ctbl << 0xffffffff;
     }
     dest->colortable = ctbl;
     dest->has_alpha_clut = src->has_alpha_clut;
     const uchar *src_data = src->data;
     uchar *dest_data = dest->data;
     if (src->format == QImage::Format_Mono) {
         for (int y = 0; y < dest->height; y++) {
             register uchar *p = dest_data;
             for (int x = 0; x < dest->width; x++)
                 *p++ = (src_data[x>>3] >> (7 - (x & 7))) & 1;
             src_data += src->bytes_per_line;
             dest_data += dest->bytes_per_line;
         }
     } else {
         for (int y = 0; y < dest->height; y++) {
             register uchar *p = dest_data;
             for (int x = 0; x < dest->width; x++)
                 *p++ = (src_data[x>>3] >> (x & 7)) & 1;
             src_data += src->bytes_per_line;
             dest_data += dest->bytes_per_line;
         }
     }
 }
convert_Mono_to_X32()
static void convert_Mono_to_X32 (QImageData * dest, const QImageData * src, Qt::ImageConversionFlags) static
Definition at line 3374 of file qimage.cpp.
 {
     Q_ASSERT(src->format == QImage::Format_Mono || src->format == QImage::Format_MonoLSB);
     Q_ASSERT(dest->format == QImage::Format_RGB32
              || dest->format == QImage::Format_ARGB32
              || dest->format == QImage::Format_ARGB32_Premultiplied);
     Q_ASSERT(src->width == dest->width);
     Q_ASSERT(src->height == dest->height);
     QVector<QRgb> colorTable = fix_color_table(src->colortable, dest->format);
     // Default to black / white colors
     if (colorTable.size() < 2) {
         if (colorTable.size() == 0)
             colorTable << 0xff000000;
         colorTable << 0xffffffff;
     }
     const uchar *src_data = src->data;
     uchar *dest_data = dest->data;
     if (src->format == QImage::Format_Mono) {
         for (int y = 0; y < dest->height; y++) {
             register uint *p = (uint *)dest_data;
             for (int x = 0; x < dest->width; x++)
                 *p++ = colorTable.at((src_data[x>>3] >> (7 - (x & 7))) & 1);
             src_data += src->bytes_per_line;
             dest_data += dest->bytes_per_line;
         }
     } else {
         for (int y = 0; y < dest->height; y++) {
             register uint *p = (uint *)dest_data;
             for (int x = 0; x < dest->width; x++)
                 *p++ = colorTable.at((src_data[x>>3] >> (x & 7)) & 1);
             src_data += src->bytes_per_line;
             dest_data += dest->bytes_per_line;
         }
     }
 }
convert_RGB_to_Indexed8()
static void convert_RGB_to_Indexed8 (QImageData * dst, const QImageData * src, Qt::ImageConversionFlags flags) static
Definition at line 3071 of file qimage.cpp.
Referenced by convert_ARGB_PM_to_Indexed8(), and convert_ARGB_to_Indexed8().
 {
     Q_ASSERT(src->format == QImage::Format_RGB32 || src->format == QImage::Format_ARGB32);
     Q_ASSERT(dst->format == QImage::Format_Indexed8);
     Q_ASSERT(src->width == dst->width);
     Q_ASSERT(src->height == dst->height);
     bool    do_quant = (flags & Qt::DitherMode_Mask) == Qt::PreferDither
                        || src->format == QImage::Format_ARGB32;
     uint alpha_mask = src->format == QImage::Format_RGB32 ? 0xff000000 : 0;
     const int tablesize = 997; // prime
     QRgbMap table[tablesize];
     int   pix=0;
     if (!dst->colortable.isEmpty()) {
         QVector<QRgb> ctbl = dst->colortable;
         dst->colortable.resize(256);
         // Preload palette into table.
         // Almost same code as pixel insertion below
         for (int i = 0; i < dst->colortable.size(); ++i) {
             // Find in table...
             QRgb p = ctbl.at(i) | alpha_mask;
             int hash = p % tablesize;
             for (;;) {
                 if (table[hash].used) {
                     if (table[hash].rgb == p) {
                         // Found previous insertion - use it
                         break;
                     } else {
                         // Keep searching...
                         if (++hash == tablesize) hash = 0;
                     }
                 } else {
                     // Cannot be in table
                     Q_ASSERT (pix != 256);        // too many colors
                     // Insert into table at this unused position
                     dst->colortable[pix] = p;
                     table[hash].pix = pix++;
                     table[hash].rgb = p;
                     table[hash].used = 1;
                     break;
                 }
             }
         }
     }
     if ((flags & Qt::DitherMode_Mask) != Qt::PreferDither) {
         dst->colortable.resize(256);
         const uchar *src_data = src->data;
         uchar *dest_data = dst->data;
         for (int y = 0; y < src->height; y++) {        // check if <= 256 colors
             const QRgb *s = (const QRgb *)src_data;
             uchar *b = dest_data;
             for (int x = 0; x < src->width; ++x) {
                 QRgb p = s[x] | alpha_mask;
                 int hash = p % tablesize;
                 for (;;) {
                     if (table[hash].used) {
                         if (table[hash].rgb == (p)) {
                             // Found previous insertion - use it
                             break;
                         } else {
                             // Keep searching...
                             if (++hash == tablesize) hash = 0;
                         }
                     } else {
                         // Cannot be in table
                         if (pix == 256) {        // too many colors
                             do_quant = true;
                             // Break right out
                             x = src->width;
                             y = src->height;
                         } else {
                             // Insert into table at this unused position
                             dst->colortable[pix] = p;
                             table[hash].pix = pix++;
                             table[hash].rgb = p;
                             table[hash].used = 1;
                         }
                         break;
                     }
                 }
                 *b++ = table[hash].pix;                // May occur once incorrectly
             }
             src_data += src->bytes_per_line;
             dest_data += dst->bytes_per_line;
         }
     }
     int numColors = do_quant ? 256 : pix;
     dst->colortable.resize(numColors);
     if (do_quant) {                                // quantization needed
 #define MAX_R 5
 #define MAX_G 5
 #define MAX_B 5
 #define INDEXOF(r,g,b) (((r)*(MAX_G+1)+(g))*(MAX_B+1)+(b))
         for (int rc=0; rc<=MAX_R; rc++)                // build 6x6x6 color cube
             for (int gc=0; gc<=MAX_G; gc++)
                 for (int bc=0; bc<=MAX_B; bc++)
                     dst->colortable[INDEXOF(rc,gc,bc)] = 0xff000000 | qRgb(rc*255/MAX_R, gc*255/MAX_G, bc*255/MAX_B);
         const uchar *src_data = src->data;
         uchar *dest_data = dst->data;
         if ((flags & Qt::Dither_Mask) == Qt::ThresholdDither) {
             for (int y = 0; y < src->height; y++) {
                 const QRgb *p = (const QRgb *)src_data;
                 const QRgb *end = p + src->width;
                 uchar *b = dest_data;
                 while (p < end) {
 #define DITHER(p,m) ((uchar) ((p * (m) + 127) / 255))
                     *b++ =
                         INDEXOF(
                             DITHER(qRed(*p), MAX_R),
                             DITHER(qGreen(*p), MAX_G),
                             DITHER(qBlue(*p), MAX_B)
                             );
 #undef DITHER
                     p++;
                 }
                 src_data += src->bytes_per_line;
                 dest_data += dst->bytes_per_line;
             }
         } else if ((flags & Qt::Dither_Mask) == Qt::DiffuseDither) {
             int* line1[3];
             int* line2[3];
             int* pv[3];
             QScopedArrayPointer<int> lineBuffer(new int[src->width * 9]);
             line1[0] = lineBuffer.data();
             line2[0] = lineBuffer.data() + src->width;
             line1[1] = lineBuffer.data() + src->width * 2;
             line2[1] = lineBuffer.data() + src->width * 3;
             line1[2] = lineBuffer.data() + src->width * 4;
             line2[2] = lineBuffer.data() + src->width * 5;
             pv[0] = lineBuffer.data() + src->width * 6;
             pv[1] = lineBuffer.data() + src->width * 7;
             pv[2] = lineBuffer.data() + src->width * 8;
             int endian = (QSysInfo::ByteOrder == QSysInfo::BigEndian);
             for (int y = 0; y < src->height; y++) {
                 const uchar* q = src_data;
                 const uchar* q2 = y < src->height - 1 ? q + src->bytes_per_line : src->data;
                 uchar *b = dest_data;
                 for (int chan = 0; chan < 3; chan++) {
                     int *l1 = (y&1) ? line2[chan] : line1[chan];
                     int *l2 = (y&1) ? line1[chan] : line2[chan];
                     if (y == 0) {
                         for (int i = 0; i < src->width; i++)
                             l1[i] = q[i*4+chan+endian];
                     }
                     if (y+1 < src->height) {
                         for (int i = 0; i < src->width; i++)
                             l2[i] = q2[i*4+chan+endian];
                     }
                     // Bi-directional error diffusion
                     if (y&1) {
                         for (int x = 0; x < src->width; x++) {
                             int pix = qMax(qMin(5, (l1[x] * 5 + 128)/ 255), 0);
                             int err = l1[x] - pix * 255 / 5;
                             pv[chan][x] = pix;
                             // Spread the error around...
                             if (x + 1< src->width) {
                                 l1[x+1] += (err*7)>>4;
                                 l2[x+1] += err>>4;
                             }
                             l2[x]+=(err*5)>>4;
                             if (x>1)
                                 l2[x-1]+=(err*3)>>4;
                         }
                     } else {
                         for (int x = src->width; x-- > 0;) {
                             int pix = qMax(qMin(5, (l1[x] * 5 + 128)/ 255), 0);
                             int err = l1[x] - pix * 255 / 5;
                             pv[chan][x] = pix;
                             // Spread the error around...
                             if (x > 0) {
                                 l1[x-1] += (err*7)>>4;
                                 l2[x-1] += err>>4;
                             }
                             l2[x]+=(err*5)>>4;
                             if (x + 1 < src->width)
                                 l2[x+1]+=(err*3)>>4;
                         }
                     }
                 }
                 if (endian) {
                     for (int x = 0; x < src->width; x++) {
                         *b++ = INDEXOF(pv[0][x],pv[1][x],pv[2][x]);
                     }
                 } else {
                     for (int x = 0; x < src->width; x++) {
                         *b++ = INDEXOF(pv[2][x],pv[1][x],pv[0][x]);
                     }
                 }
                 src_data += src->bytes_per_line;
                 dest_data += dst->bytes_per_line;
             }
         } else { // OrderedDither
             for (int y = 0; y < src->height; y++) {
                 const QRgb *p = (const QRgb *)src_data;
                 const QRgb *end = p + src->width;
                 uchar *b = dest_data;
                 int x = 0;
                 while (p < end) {
                     uint d = qt_bayer_matrix[y & 15][x & 15] << 8;
 #define DITHER(p, d, m) ((uchar) ((((256 * (m) + (m) + 1)) * (p) + (d)) >> 16))
                     *b++ =
                         INDEXOF(
                             DITHER(qRed(*p), d, MAX_R),
                             DITHER(qGreen(*p), d, MAX_G),
                             DITHER(qBlue(*p), d, MAX_B)
                             );
 #undef DITHER
                     p++;
                     x++;
                 }
                 src_data += src->bytes_per_line;
                 dest_data += dst->bytes_per_line;
             }
         }
         if (src->format != QImage::Format_RGB32
             && src->format != QImage::Format_RGB16) {
             const int trans = 216;
             Q_ASSERT(dst->colortable.size() > trans);
             dst->colortable[trans] = 0;
             QScopedPointer<QImageData> mask(QImageData::create(QSize(src->width, src->height), QImage::Format_Mono));
             dither_to_Mono(mask.data(), src, flags, true);
             uchar *dst_data = dst->data;
             const uchar *mask_data = mask->data;
             for (int y = 0; y < src->height; y++) {
                 for (int x = 0; x < src->width ; x++) {
                     if (!(mask_data[x>>3] & (0x80 >> (x & 7))))
                         dst_data[x] = trans;
                 }
                 mask_data += mask->bytes_per_line;
                 dst_data += dst->bytes_per_line;
             }
             dst->has_alpha_clut = true;
         }
 #undef MAX_R
 #undef MAX_G
 #undef MAX_B
 #undef INDEXOF
     }
 }
convert_RGB_to_RGB16_inplace()
static bool convert_RGB_to_RGB16_inplace (QImageData * data, Qt::ImageConversionFlags) static
Definition at line 2635 of file qimage.cpp.
 {
     Q_ASSERT(data->format == QImage::Format_RGB32);
     const int depth = 16;
     const int dst_bytes_per_line = ((data->width * depth + 31) >> 5) << 2;
     const int src_bytes_per_line = data->bytes_per_line;
     quint32 *src_data = (quint32 *) data->data;
     quint16 *dst_data = (quint16 *) data->data;
     for (int i = 0; i < data->height; ++i) {
         qt_memconvert(dst_data, src_data, data->width);
         src_data = (quint32 *) (((char*)src_data) + src_bytes_per_line);
         dst_data = (quint16 *) (((char*)dst_data) + dst_bytes_per_line);
     }
     data->format = QImage::Format_RGB16;
     data->bytes_per_line = dst_bytes_per_line;
     data->depth = depth;
     data->nbytes = dst_bytes_per_line * data->height;
     uchar *const newData = (uchar *)realloc(data->data, data->nbytes);
     if (newData) {
         data->data = newData;
         return true;
     } else {
         return false;
     }
 }
convert_X_to_Mono()
static void convert_X_to_Mono (QImageData * dst, const QImageData * src, Qt::ImageConversionFlags flags) static
Definition at line 3044 of file qimage.cpp.
 {
     dither_to_Mono(dst, src, flags, false);
 }
convertWithPalette()
static QImage convertWithPalette (const QImage & src, QImage::Format format, const QVector< QRgb > & clut) static
Definition at line 4028 of file qimage.cpp.
Referenced by QImage::convertToFormat().
{
     QImage dest(src.size(), format);
     QIMAGE_SANITYCHECK_MEMORY(dest);
     dest.setColorTable(clut);
 #if !defined(QT_NO_IMAGE_TEXT)
     QString textsKeys = src.text();
     QStringList textKeyList = textsKeys.split(QLatin1Char('\n'), QString::SkipEmptyParts);
     foreach (const QString &textKey, textKeyList) {
         QStringList textKeySplitted = textKey.split(QLatin1String(": "));
         dest.setText(textKeySplitted[0], textKeySplitted[1]);
     }
 #endif // !QT_NO_IMAGE_TEXT
     int h = src.height();
     int w = src.width();
     QHash<QRgb, int> cache;
     if (format == QImage::Format_Indexed8) {
         for (int y=0; y<h; ++y) {
             QRgb *src_pixels = (QRgb *) src.scanLine(y);
             uchar *dest_pixels = (uchar *) dest.scanLine(y);
             for (int x=0; x<w; ++x) {
                 int src_pixel = src_pixels[x];
                 int value = cache.value(src_pixel, -1);
                 if (value == -1) {
                     value = closestMatch(src_pixel, clut);
                     cache.insert(src_pixel, value);
                 }
                 dest_pixels[x] = (uchar) value;
             }
         }
     } else {
         QVector<QRgb> table = clut;
         table.resize(2);
         for (int y=0; y<h; ++y) {
             QRgb *src_pixels = (QRgb *) src.scanLine(y);
             for (int x=0; x<w; ++x) {
                 int src_pixel = src_pixels[x];
                 int value = cache.value(src_pixel, -1);
                 if (value == -1) {
                     value = closestMatch(src_pixel, table);
                     cache.insert(src_pixel, value);
                 }
                 dest.setPixel(x, y, value);
             }
         }
     }
     return dest;
 }
dither_to_Mono()
static void dither_to_Mono (QImageData * dst, const QImageData * src, Qt::ImageConversionFlags flags, bool fromalpha) static
Definition at line 2774 of file qimage.cpp.
Referenced by convert_ARGB_PM_to_Mono(), convert_RGB_to_Indexed8(), convert_X_to_Mono(), and QImage::createAlphaMask().
 {
     Q_ASSERT(src->width == dst->width);
     Q_ASSERT(src->height == dst->height);
     Q_ASSERT(dst->format == QImage::Format_Mono || dst->format == QImage::Format_MonoLSB);
     dst->colortable.clear();
     dst->colortable.append(0xffffffff);
     dst->colortable.append(0xff000000);
     enum { Threshold, Ordered, Diffuse } dithermode;
     if (fromalpha) {
         if ((flags & Qt::AlphaDither_Mask) == Qt::DiffuseAlphaDither)
             dithermode = Diffuse;
         else if ((flags & Qt::AlphaDither_Mask) == Qt::OrderedAlphaDither)
             dithermode = Ordered;
         else
             dithermode = Threshold;
     } else {
         if ((flags & Qt::Dither_Mask) == Qt::ThresholdDither)
             dithermode = Threshold;
         else if ((flags & Qt::Dither_Mask) == Qt::OrderedDither)
             dithermode = Ordered;
         else
             dithermode = Diffuse;
     }
     int          w = src->width;
     int          h = src->height;
     int          d = src->depth;
     uchar gray[256];                                // gray map for 8 bit images
     bool  use_gray = (d == 8);
     if (use_gray) {                                // make gray map
         if (fromalpha) {
             // Alpha 0x00 -> 0 pixels (white)
             // Alpha 0xFF -> 1 pixels (black)
             for (int i = 0; i < src->colortable.size(); i++)
                 gray[i] = (255 - (src->colortable.at(i) >> 24));
         } else {
             // Pixel 0x00 -> 1 pixels (black)
             // Pixel 0xFF -> 0 pixels (white)
             for (int i = 0; i < src->colortable.size(); i++)
                 gray[i] = qGray(src->colortable.at(i));
         }
     }
     uchar *dst_data = dst->data;
     int dst_bpl = dst->bytes_per_line;
     const uchar *src_data = src->data;
     int src_bpl = src->bytes_per_line;
     switch (dithermode) {
     case Diffuse: {
         QScopedArrayPointer<int> lineBuffer(new int[w * 2]);
         int *line1 = lineBuffer.data();
         int *line2 = lineBuffer.data() + w;
         int bmwidth = (w+7)/8;
         int *b1, *b2;
         int wbytes = w * (d/8);
         register const uchar *p = src->data;
         const uchar *end = p + wbytes;
         b2 = line2;
         if (use_gray) {                        // 8 bit image
             while (p < end)
                 *b2++ = gray[*p++];
         } else {                                // 32 bit image
             if (fromalpha) {
                 while (p < end) {
                     *b2++ = 255 - (*(uint*)p >> 24);
                     p += 4;
                 }
             } else {
                 while (p < end) {
                     *b2++ = qGray(*(uint*)p);
                     p += 4;
                 }
             }
         }
         for (int y=0; y<h; y++) {                        // for each scan line...
             int *tmp = line1; line1 = line2; line2 = tmp;
             bool not_last_line = y < h - 1;
             if (not_last_line) {                // calc. grayvals for next line
                 p = src->data + (y+1)*src->bytes_per_line;
                 end = p + wbytes;
                 b2 = line2;
                 if (use_gray) {                // 8 bit image
                     while (p < end)
                         *b2++ = gray[*p++];
                 } else {                        // 24 bit image
                     if (fromalpha) {
                         while (p < end) {
                             *b2++ = 255 - (*(uint*)p >> 24);
                             p += 4;
                         }
                     } else {
                         while (p < end) {
                             *b2++ = qGray(*(uint*)p);
                             p += 4;
                         }
                     }
                 }
             }
             int err;
             uchar *p = dst->data + y*dst->bytes_per_line;
             memset(p, 0, bmwidth);
             b1 = line1;
             b2 = line2;
             int bit = 7;
             for (int x=1; x<=w; x++) {
                 if (*b1 < 128) {                // black pixel
                     err = *b1++;
                     *p |= 1 << bit;
                 } else {                        // white pixel
                     err = *b1++ - 255;
                 }
                 if (bit == 0) {
                     p++;
                     bit = 7;
                 } else {
                     bit--;
                 }
                 if (x < w)
                     *b1 += (err*7)>>4;                // spread error to right pixel
                 if (not_last_line) {
                     b2[0] += (err*5)>>4;        // pixel below
                     if (x > 1)
                         b2[-1] += (err*3)>>4;        // pixel below left
                     if (x < w)
                         b2[1] += err>>4;        // pixel below right
                 }
                 b2++;
             }
         }
     } break;
     case Ordered: {
         memset(dst->data, 0, dst->nbytes);
         if (d == 32) {
             for (int i=0; i<h; i++) {
                 const uint *p = (const uint *)src_data;
                 const uint *end = p + w;
                 uchar *m = dst_data;
                 int bit = 7;
                 int j = 0;
                 if (fromalpha) {
                     while (p < end) {
                         if ((*p++ >> 24) >= qt_bayer_matrix[j++&15][i&15])
                             *m |= 1 << bit;
                         if (bit == 0) {
                             m++;
                             bit = 7;
                         } else {
                             bit--;
                         }
                     }
                 } else {
                     while (p < end) {
                         if ((uint)qGray(*p++) < qt_bayer_matrix[j++&15][i&15])
                             *m |= 1 << bit;
                         if (bit == 0) {
                             m++;
                             bit = 7;
                         } else {
                             bit--;
                         }
                     }
                 }
                 dst_data += dst_bpl;
                 src_data += src_bpl;
             }
         } else
             /* (d == 8) */ {
             for (int i=0; i<h; i++) {
                 const uchar *p = src_data;
                 const uchar *end = p + w;
                 uchar *m = dst_data;
                 int bit = 7;
                 int j = 0;
                 while (p < end) {
                     if ((uint)gray[*p++] < qt_bayer_matrix[j++&15][i&15])
                         *m |= 1 << bit;
                     if (bit == 0) {
                         m++;
                         bit = 7;
                     } else {
                         bit--;
                     }
                 }
                 dst_data += dst_bpl;
                 src_data += src_bpl;
             }
         }
     } break;
     default: { // Threshold:
         memset(dst->data, 0, dst->nbytes);
         if (d == 32) {
             for (int i=0; i<h; i++) {
                 const uint *p = (const uint *)src_data;
                 const uint *end = p + w;
                 uchar *m = dst_data;
                 int bit = 7;
                 if (fromalpha) {
                     while (p < end) {
                         if ((*p++ >> 24) >= 128)
                             *m |= 1 << bit;        // Set mask "on"
                         if (bit == 0) {
                             m++;
                             bit = 7;
                         } else {
                             bit--;
                         }
                     }
                 } else {
                     while (p < end) {
                         if (qGray(*p++) < 128)
                             *m |= 1 << bit;        // Set pixel "black"
                         if (bit == 0) {
                             m++;
                             bit = 7;
                         } else {
                             bit--;
                         }
                     }
                 }
                 dst_data += dst_bpl;
                 src_data += src_bpl;
             }
         } else
             if (d == 8) {
                 for (int i=0; i<h; i++) {
                     const uchar *p = src_data;
                     const uchar *end = p + w;
                     uchar *m = dst_data;
                     int bit = 7;
                     while (p < end) {
                         if (gray[*p++] < 128)
                             *m |= 1 << bit;                // Set mask "on"/ pixel "black"
                         if (bit == 0) {
                             m++;
                             bit = 7;
                         } else {
                             bit--;
                         }
                     }
                     dst_data += dst_bpl;
                     src_data += src_bpl;
                 }
             }
         }
     }
     if (dst->format == QImage::Format_MonoLSB) {
         // need to swap bit order
         uchar *sl = dst->data;
         int bpl = (dst->width + 7) * dst->depth / 8;
         int pad = dst->bytes_per_line - bpl;
         for (int y=0; y<dst->height; ++y) {
             for (int x=0; x<bpl; ++x) {
                 *sl = bitflip[*sl];
                 ++sl;
             }
             sl += pad;
         }
     }
 }
fix_color_table()
static QVector<QRgb> fix_color_table (const QVector< QRgb > & ctbl, QImage::Format format) static
Definition at line 2754 of file qimage.cpp.
Referenced by convert_Indexed8_to_X32(), and convert_Mono_to_X32().
 {
     QVector<QRgb> colorTable = ctbl;
     if (format == QImage::Format_RGB32) {
         // check if the color table has alpha
         for (int i = 0; i < colorTable.size(); ++i)
             if (qAlpha(colorTable.at(i) != 0xff))
                 colorTable[i] = colorTable.at(i) | 0xff000000;
     } else if (format == QImage::Format_ARGB32_Premultiplied) {
         // check if the color table has alpha
         for (int i = 0; i < colorTable.size(); ++i)
             colorTable[i] = PREMUL(colorTable.at(i));
     }
     return colorTable;
 }
mask_alpha_converter()
static void mask_alpha_converter (QImageData * dest, const QImageData * src, Qt::ImageConversionFlags) static
Definition at line 2732 of file qimage.cpp.
 {
     Q_ASSERT(src->width == dest->width);
     Q_ASSERT(src->height == dest->height);
     const int src_pad = (src->bytes_per_line >> 2) - src->width;
     const int dest_pad = (dest->bytes_per_line >> 2) - dest->width;
     const uint *src_data = (const uint *)src->data;
     uint *dest_data = (uint *)dest->data;
     for (int i = 0; i < src->height; ++i) {
         const uint *end = src_data + src->width;
         while (src_data < end) {
             *dest_data = *src_data | 0xff000000;
             ++src_data;
             ++dest_data;
         }
         src_data += src_pad;
         dest_data += dest_pad;
     }
 }
operator<<()
QDataStream& operator<< (QDataStream & s, const QImage & image) related
Definition at line 5406 of file qimage.cpp.
Referenced by QImage::setPixel().
 {
     if (s.version() >= 5) {
         if (image.isNull()) {
             s << (qint32) 0; // null image marker
             return s;
         } else {
             s << (qint32) 1;
             // continue ...
         }
     }
     QImageWriter writer(s.device(), s.version() == 1 ? "bmp" : "png");
     writer.write(image);
     return s;
 }
operator>>()
QDataStream& operator>> (QDataStream & s, QImage & image) related
Definition at line 5435 of file qimage.cpp.
Referenced by QImage::setPixel().
 {
     if (s.version() >= 5) {
         qint32 nullMarker;
         s >> nullMarker;
         if (!nullMarker) {
             image = QImage(); // null image
             return s;
         }
     }
     image = QImageReader(s.device(), 0).read();
     return s;
 }
pixel_distance()
static int pixel_distance (QRgb p1, QRgb p2) inline static
Definition at line 4001 of file qimage.cpp.
Referenced by closestMatch().
{
     int r1 = qRed(p1);
     int g1 = qGreen(p1);
     int b1 = qBlue(p1);
     int a1 = qAlpha(p1);
     int r2 = qRed(p2);
     int g2 = qGreen(p2);
     int b2 = qBlue(p2);
     int a2 = qAlpha(p2);
     return abs(r1 - r2) + abs(g1 - g2) + abs(b1 - b2) + abs(a1 - a2);
 }
qGamma_correct_back_to_linear_cs()
void qGamma_correct_back_to_linear_cs (QImage * image)
Definition at line 3938 of file qimage.cpp.
Referenced by QFontEngineMac::alphaRGBMapForGlyph().
 {
     extern uchar qt_pow_rgb_gamma[256];
     // gamma correct the pixels back to linear color space...
     int h = image->height();
     int w = image->width();
     for (int y=0; y<h; ++y) {
         uint *pixels = (uint *) image->scanLine(y);
         for (int x=0; x<w; ++x) {
             uint p = pixels[x];
             uint r = qt_pow_rgb_gamma[qRed(p)];
             uint g = qt_pow_rgb_gamma[qGreen(p)];
             uint b = qt_pow_rgb_gamma[qBlue(p)];
             pixels[x] = (r << 16) | (g << 8) | b | 0xff000000;
         }
     }
 }
qInitImageConversions()
void qInitImageConversions ()
Definition at line 3909 of file qimage.cpp.
Referenced by QApplication::QApplication().
 {
     const uint features = qDetectCPUFeatures();
     Q_UNUSED(features);
 #ifdef QT_HAVE_SSE2
     if (features & SSE2) {
         extern bool convert_ARGB_to_ARGB_PM_inplace_sse2(QImageData *data, Qt::ImageConversionFlags);
         inplace_converter_map[QImage::Format_ARGB32][QImage::Format_ARGB32_Premultiplied] = convert_ARGB_to_ARGB_PM_inplace_sse2;
     }
 #endif
 #ifdef QT_HAVE_SSSE3
     if (features & SSSE3) {
         extern void convert_RGB888_to_RGB32_ssse3(QImageData *dest, const QImageData *src, Qt::ImageConversionFlags);
         converter_map[QImage::Format_RGB888][QImage::Format_RGB32] = convert_RGB888_to_RGB32_ssse3;
         converter_map[QImage::Format_RGB888][QImage::Format_ARGB32] = convert_RGB888_to_RGB32_ssse3;
         converter_map[QImage::Format_RGB888][QImage::Format_ARGB32_Premultiplied] = convert_RGB888_to_RGB32_ssse3;
     }
 #endif
 #ifdef QT_HAVE_NEON
     if (features & NEON) {
         extern void convert_RGB888_to_RGB32_neon(QImageData *dest, const QImageData *src, Qt::ImageConversionFlags);
         converter_map[QImage::Format_RGB888][QImage::Format_RGB32] = convert_RGB888_to_RGB32_neon;
         converter_map[QImage::Format_RGB888][QImage::Format_ARGB32] = convert_RGB888_to_RGB32_neon;
         converter_map[QImage::Format_RGB888][QImage::Format_ARGB32_Premultiplied] = convert_RGB888_to_RGB32_neon;
     }
 #endif
 }
qt_get_bitflip_array()
const uchar* qt_get_bitflip_array ()
Definition at line 765 of file qimage.cpp.
Referenced by QX11PixmapData::bitmap_to_mask().
 {
     return bitflip;
 }
qt_image_colortable()
const QVector<QRgb>* qt_image_colortable (const QImage & image)
Definition at line 122 of file qimage.cpp.
Referenced by QSpanData::setupMatrix().
 {
     return &image.d->colortable;
 }
qt_image_id()
Q_GUI_EXPORT qint64 qt_image_id (const QImage & image)
Definition at line 117 of file qimage.cpp.
 {
     return image.cacheKey();
 }
qt_read_xpm_image_or_array()
bool qt_read_xpm_image_or_array (QIODevice * device, const char *const * source, QImage & image)
Definition at line 1025 of file qxpmhandler.cpp.
Referenced by QImage::QImage().
 {
     if (!source)
         return true;
     QByteArray buf(200, 0);
     QByteArray state;
     int cpp, ncols, w, h, index = 0;
     if (device) {
         // "/* XPM */"
         int readBytes;
         if ((readBytes = device->readLine(buf.data(), buf.size())) < 0)
             return false;
         if (buf.indexOf("/* XPM") != 0) {
             while (readBytes > 0) {
                 device->ungetChar(buf.at(readBytes - 1));
                 --readBytes;
             }
             return false;
         }// bad magic
     }
     if (!read_xpm_header(device, source, index, state, &cpp, &ncols, &w, &h))
         return false;
     return read_xpm_body(device, source, index, state, cpp, ncols, w, h, image);
 }
qt_xForm_helper()
bool qt_xForm_helper (const QTransform & trueMat, int xoffset, int type, int depth, uchar * dptr, int dbpl, int p_inc, int dHeight, const uchar * sptr, int sbpl, int sWidth, int sHeight)
Definition at line 6100 of file qimage.cpp.
Referenced by QMacPixmapData::macCreatePixels(), QX11PixmapData::transformed(), and QImage::transformed().
 {
     int m11 = int(trueMat.m11()*qreal(4096.0));
     int m12 = int(trueMat.m12()*qreal(4096.0));
     int m21 = int(trueMat.m21()*qreal(4096.0));
     int m22 = int(trueMat.m22()*qreal(4096.0));
     int dx  = qRound(trueMat.dx()*qreal(4096.0));
     int dy  = qRound(trueMat.dy()*qreal(4096.0));
     int m21ydx = dx + (xoffset<<16) + (m11 + m21) / 2;
     int m22ydy = dy + (m12 + m22) / 2;
     uint trigx;
     uint trigy;
     uint maxws = sWidth<<12;
     uint maxhs = sHeight<<12;
     for (int y=0; y<dHeight; y++) {                // for each target scanline
         trigx = m21ydx;
         trigy = m22ydy;
         uchar *maxp = dptr + dbpl;
         if (depth != 1) {
             switch (depth) {
                 case 8:                                // 8 bpp transform
                 while (dptr < maxp) {
                     if (trigx < maxws && trigy < maxhs)
                         *dptr = *(sptr+sbpl*(trigy>>12)+(trigx>>12));
                     trigx += m11;
                     trigy += m12;
                     dptr++;
                 }
                 break;
                 case 16:                        // 16 bpp transform
                 while (dptr < maxp) {
                     if (trigx < maxws && trigy < maxhs)
                         *((ushort*)dptr) = *((ushort *)(sptr+sbpl*(trigy>>12) +
                                                      ((trigx>>12)<<1)));
                     trigx += m11;
                     trigy += m12;
                     dptr++;
                     dptr++;
                 }
                 break;
                 case 24:                        // 24 bpp transform
                 while (dptr < maxp) {
                     if (trigx < maxws && trigy < maxhs) {
                         const uchar *p2 = sptr+sbpl*(trigy>>12) + ((trigx>>12)*3);
                         dptr[0] = p2[0];
                         dptr[1] = p2[1];
                         dptr[2] = p2[2];
                     }
                     trigx += m11;
                     trigy += m12;
                     dptr += 3;
                 }
                 break;
                 case 32:                        // 32 bpp transform
                 while (dptr < maxp) {
                     if (trigx < maxws && trigy < maxhs)
                         *((uint*)dptr) = *((uint *)(sptr+sbpl*(trigy>>12) +
                                                    ((trigx>>12)<<2)));
                     trigx += m11;
                     trigy += m12;
                     dptr += 4;
                 }
                 break;
                 default: {
                 return false;
                 }
             }
         } else  {
             switch (type) {
                 case QT_XFORM_TYPE_MSBFIRST:
                     while (dptr < maxp) {
                         IWX_MSB(128);
                         IWX_MSB(64);
                         IWX_MSB(32);
                         IWX_MSB(16);
                         IWX_MSB(8);
                         IWX_MSB(4);
                         IWX_MSB(2);
                         IWX_MSB(1);
                         dptr++;
                     }
                     break;
                 case QT_XFORM_TYPE_LSBFIRST:
                     while (dptr < maxp) {
                         IWX_LSB(1);
                         IWX_LSB(2);
                         IWX_LSB(4);
                         IWX_LSB(8);
                         IWX_LSB(16);
                         IWX_LSB(32);
                         IWX_LSB(64);
                         IWX_LSB(128);
                         dptr++;
                     }
                     break;
 #  if defined(Q_WS_WIN)
                 case QT_XFORM_TYPE_WINDOWSPIXMAP:
                     while (dptr < maxp) {
                         IWX_PIX(128);
                         IWX_PIX(64);
                         IWX_PIX(32);
                         IWX_PIX(16);
                         IWX_PIX(8);
                         IWX_PIX(4);
                         IWX_PIX(2);
                         IWX_PIX(1);
                         dptr++;
                     }
                     break;
 #  endif
             }
         }
         m21ydx += m21;
         m22ydy += m22;
         dptr += p_inc;
     }
     return true;
 }
rotated180()
static QImage rotated180 (const QImage & src) static
Definition at line 6681 of file qimage.cpp.
Referenced by QImage::transformed().
{
     return image.mirrored(true, true);
 }
rotated270()
static QImage rotated270 (const QImage & src) static
Definition at line 6686 of file qimage.cpp.
Referenced by QImage::transformed().
{
     QImage out(image.height(), image.width(), image.format());
     QIMAGE_SANITYCHECK_MEMORY(out);
     if (image.colorCount() > 0)
         out.setColorTable(image.colorTable());
     int w = image.width();
     int h = image.height();
     switch (image.format()) {
     case QImage::Format_RGB32:
     case QImage::Format_ARGB32:
     case QImage::Format_ARGB32_Premultiplied:
         qt_memrotate90(reinterpret_cast<const quint32*>(image.bits()),
                        w, h, image.bytesPerLine(),
                        reinterpret_cast<quint32*>(out.bits()),
                        out.bytesPerLine());
         break;
     case QImage::Format_RGB666:
     case QImage::Format_ARGB6666_Premultiplied:
     case QImage::Format_ARGB8565_Premultiplied:
     case QImage::Format_ARGB8555_Premultiplied:
     case QImage::Format_RGB888:
         qt_memrotate90(reinterpret_cast<const quint24*>(image.bits()),
                        w, h, image.bytesPerLine(),
                        reinterpret_cast<quint24*>(out.bits()),
                        out.bytesPerLine());
         break;
     case QImage::Format_RGB555:
     case QImage::Format_RGB16:
     case QImage::Format_ARGB4444_Premultiplied:
        qt_memrotate90(reinterpret_cast<const quint16*>(image.bits()),
                        w, h, image.bytesPerLine(),
                        reinterpret_cast<quint16*>(out.bits()),
                        out.bytesPerLine());
         break;
     case QImage::Format_Indexed8:
         qt_memrotate90(reinterpret_cast<const quint8*>(image.bits()),
                        w, h, image.bytesPerLine(),
                        reinterpret_cast<quint8*>(out.bits()),
                        out.bytesPerLine());
         break;
     default:
         for (int y=0; y<h; ++y) {
             if (image.colorCount())
                 for (int x=0; x<w; ++x)
                     out.setPixel(y, w-x-1, image.pixelIndex(x, y));
             else
                 for (int x=0; x<w; ++x)
                     out.setPixel(y, w-x-1, image.pixel(x, y));
         }
         break;
     }
     return out;
 }
rotated90()
static QImage rotated90 (const QImage & src) static
Definition at line 6626 of file qimage.cpp.
Referenced by QImage::transformed().
{
     QImage out(image.height(), image.width(), image.format());
     QIMAGE_SANITYCHECK_MEMORY(out);
     if (image.colorCount() > 0)
         out.setColorTable(image.colorTable());
     int w = image.width();
     int h = image.height();
     switch (image.format()) {
     case QImage::Format_RGB32:
     case QImage::Format_ARGB32:
     case QImage::Format_ARGB32_Premultiplied:
         qt_memrotate270(reinterpret_cast<const quint32*>(image.bits()),
                         w, h, image.bytesPerLine(),
                         reinterpret_cast<quint32*>(out.bits()),
                         out.bytesPerLine());
         break;
     case QImage::Format_RGB666:
     case QImage::Format_ARGB6666_Premultiplied:
     case QImage::Format_ARGB8565_Premultiplied:
     case QImage::Format_ARGB8555_Premultiplied:
     case QImage::Format_RGB888:
         qt_memrotate270(reinterpret_cast<const quint24*>(image.bits()),
                         w, h, image.bytesPerLine(),
                         reinterpret_cast<quint24*>(out.bits()),
                         out.bytesPerLine());
         break;
     case QImage::Format_RGB555:
     case QImage::Format_RGB16:
     case QImage::Format_ARGB4444_Premultiplied:
         qt_memrotate270(reinterpret_cast<const quint16*>(image.bits()),
                         w, h, image.bytesPerLine(),
                         reinterpret_cast<quint16*>(out.bits()),
                         out.bytesPerLine());
         break;
     case QImage::Format_Indexed8:
         qt_memrotate270(reinterpret_cast<const quint8*>(image.bits()),
                         w, h, image.bytesPerLine(),
                         reinterpret_cast<quint8*>(out.bits()),
                         out.bytesPerLine());
         break;
     default:
         for (int y=0; y<h; ++y) {
             if (image.colorCount())
                 for (int x=0; x<w; ++x)
                     out.setPixel(h-y-1, x, image.pixelIndex(x, y));
             else
                 for (int x=0; x<w; ++x)
                     out.setPixel(h-y-1, x, image.pixel(x, y));
         }
         break;
     }
     return out;
 }
smoothScaled()
static QImage smoothScaled (const QImage & source, int w, int h) static
Definition at line 6611 of file qimage.cpp.
Referenced by QImage::transformed().
{
     QImage src = source;
     if (src.format() == QImage::Format_ARGB32)
         src = src.convertToFormat(QImage::Format_ARGB32_Premultiplied);
     else if (src.depth() < 32) {
         if (src.hasAlphaChannel())
             src = src.convertToFormat(QImage::Format_ARGB32_Premultiplied);
         else
             src = src.convertToFormat(QImage::Format_RGB32);
     }
     return qSmoothScaleImage(src, w, h);
 }
swap_bit_order()
static void swap_bit_order (QImageData * dest, const QImageData * src, Qt::ImageConversionFlags) static
Definition at line 2711 of file qimage.cpp.
 {
     Q_ASSERT(src->format == QImage::Format_Mono || src->format == QImage::Format_MonoLSB);
     Q_ASSERT(dest->format == QImage::Format_Mono || dest->format == QImage::Format_MonoLSB);
     Q_ASSERT(src->width == dest->width);
     Q_ASSERT(src->height == dest->height);
     Q_ASSERT(src->nbytes == dest->nbytes);
     Q_ASSERT(src->bytes_per_line == dest->bytes_per_line);
     dest->colortable = src->colortable;
     const uchar *src_data = src->data;
     const uchar *end = src->data + src->nbytes;
     uchar *dest_data = dest->data;
     while (src_data < end) {
         *dest_data = bitflip[*src_data];
         ++src_data;
         ++dest_data;
     }
 }
Variable Documentation
bitflip
const uchar bitflip[256] static
Initial value:
= {
    0, 128, 64, 192, 32, 160, 96, 224, 16, 144, 80, 208, 48, 176, 112, 240,
    8, 136, 72, 200, 40, 168, 104, 232, 24, 152, 88, 216, 56, 184, 120, 248,
    4, 132, 68, 196, 36, 164, 100, 228, 20, 148, 84, 212, 52, 180, 116, 244,
    12, 140, 76, 204, 44, 172, 108, 236, 28, 156, 92, 220, 60, 188, 124, 252,
    2, 130, 66, 194, 34, 162, 98, 226, 18, 146, 82, 210, 50, 178, 114, 242,
    10, 138, 74, 202, 42, 170, 106, 234, 26, 154, 90, 218, 58, 186, 122, 250,
    6, 134, 70, 198, 38, 166, 102, 230, 22, 150, 86, 214, 54, 182, 118, 246,
    14, 142, 78, 206, 46, 174, 110, 238, 30, 158, 94, 222, 62, 190, 126, 254,
    1, 129, 65, 193, 33, 161, 97, 225, 17, 145, 81, 209, 49, 177, 113, 241,
    9, 137, 73, 201, 41, 169, 105, 233, 25, 153, 89, 217, 57, 185, 121, 249,
    5, 133, 69, 197, 37, 165, 101, 229, 21, 149, 85, 213, 53, 181, 117, 245,
    13, 141, 77, 205, 45, 173, 109, 237, 29, 157, 93, 221, 61, 189, 125, 253,
    3, 131, 67, 195, 35, 163, 99, 227, 19, 147, 83, 211, 51, 179, 115, 243,
    11, 139, 75, 203, 43, 171, 107, 235, 27, 155, 91, 219, 59, 187, 123, 251,
    7, 135, 71, 199, 39, 167, 103, 231, 23, 151, 87, 215, 55, 183, 119, 247,
    15, 143, 79, 207, 47, 175, 111, 239, 31, 159, 95, 223, 63, 191, 127, 255
}
Definition at line 736 of file qimage.cpp.
Referenced by dither_to_Mono(), QImage::mirrored(), qt_get_bitflip_array(), QImage::setPixel(), and swap_bit_order().
converter_map
Image_Converter converter_map[QImage::NImageFormats][QImage::NImageFormats] static
Definition at line 3513 of file qimage.cpp.
inplace_converter_map
InPlace_Image_Converter inplace_converter_map[QImage::NImageFormats][QImage::NImageFormats] static
Definition at line 3812 of file qimage.cpp.
qimage_serial_number
QBasicAtomicInt qimage_serial_number = Q_BASIC_ATOMIC_INITIALIZER(1)
Definition at line 127 of file qimage.cpp.