Qt 4.8: /src/gui/itemviews/qitemselectionmodel.cpp File Reference
qitemselectionmodel.cpp File Reference
#include "qitemselectionmodel.h"
#include <private/qitemselectionmodel_p.h>
#include <qdebug.h>
#include "moc_qitemselectionmodel.cpp"
Functions
static void indexesFromRange (const QItemSelectionRange &range, QModelIndexList &result)
static QItemSelection mergeIndexes (const QList< QPersistentModelIndex > &indexes)
Merges indexes into an item selection made up of ranges.
QDebug operator<< (QDebug dbg, const QItemSelectionRange &range)
Function Documentation
indexesFromRange()
static void indexesFromRange (const QItemSelectionRange & range, QModelIndexList & result) static
Definition at line 347 of file qitemselectionmodel.cpp.
Referenced by QItemSelectionRange::indexes(), and QItemSelection::indexes().
 {
     if (range.isValid() && range.model()) {
         for (int column = range.left(); column <= range.right(); ++column) {
             for (int row = range.top(); row <= range.bottom(); ++row) {
                 QModelIndex index = range.model()->index(row, column, range.parent());
                 Qt::ItemFlags flags = range.model()->flags(index);
                 if ((flags & Qt::ItemIsSelectable) && (flags & Qt::ItemIsEnabled))
                     result.append(index);
             }
         }
     }
 }
mergeIndexes()
static QItemSelection mergeIndexes (const QList< QPersistentModelIndex > & indexes) static
Merges indexes into an item selection made up of ranges.
Warning
This function is not part of the public interface.
Assumes that the indexes are sorted.
Definition at line 902 of file qitemselectionmodel.cpp.
Referenced by QItemSelectionModelPrivate::_q_layoutChanged().
 {
     QItemSelection colSpans;
     // merge columns
     int i = 0;
     while (i < indexes.count()) {
         QModelIndex tl = indexes.at(i);
         QModelIndex br = tl;
         while (++i < indexes.count()) {
             QModelIndex next = indexes.at(i);
             if ((next.parent() == br.parent())
                  && (next.row() == br.row())
                  && (next.column() == br.column() + 1))
                 br = next;
             else
                 break;
         }
         colSpans.append(QItemSelectionRange(tl, br));
     }
     // merge rows
     QItemSelection rowSpans;
     i = 0;
     while (i < colSpans.count()) {
         QModelIndex tl = colSpans.at(i).topLeft();
         QModelIndex br = colSpans.at(i).bottomRight();
         QModelIndex prevTl = tl;
         while (++i < colSpans.count()) {
             QModelIndex nextTl = colSpans.at(i).topLeft();
             QModelIndex nextBr = colSpans.at(i).bottomRight();
             if (nextTl.parent() != tl.parent())
                 break; // we can't merge selection ranges from different parents
             if ((nextTl.column() == prevTl.column()) && (nextBr.column() == br.column())
                 && (nextTl.row() == prevTl.row() + 1) && (nextBr.row() == br.row() + 1)) {
                 br = nextBr;
                 prevTl = nextTl;
             } else {
                 break;
             }
         }
         rowSpans.append(QItemSelectionRange(tl, br));
     }
     return rowSpans;
 }
operator<<()
QDebug operator<< (QDebug dbg, const QItemSelectionRange & range)
Definition at line 1721 of file qitemselectionmodel.cpp.
 {
 #ifndef Q_BROKEN_DEBUG_STREAM
     dbg.nospace() << "QItemSelectionRange(" << range.topLeft()
                   << ',' << range.bottomRight() << ')';
     return dbg.space();
 #else
     qWarning("This compiler doesn't support streaming QItemSelectionRange to QDebug");
     return dbg;
     Q_UNUSED(range);
 #endif
 }