Qt 4.8: /src/plugins/codecs/jp/qjpunicode.cpp File Reference
qjpunicode.cpp File Reference
#include "qjpunicode.h"
#include "qbytearray.h"
#include <stdlib.h>
Classes
class QJpUnicodeConv_JISX0221_ASCII
class QJpUnicodeConv_JISX0221_JISX0201
class QJpUnicodeConv_Microsoft
class QJpUnicodeConv_Sun
class QJpUnicodeConv_Unicode_ASCII
class QJpUnicodeConv_Unicode_JISX0201
Macros
#define IsJisChar(c) (((c) >= 0x21) && ((c) <= 0x7e))
#define IsKana(c) (((c) >= 0xa1) && ((c) <= 0xdf))
#define IsLatin(c) (/*((c) >= 0x00) &&*/ ((c) <= 0x7f))
#define IsSjisChar1(c)
#define IsSjisChar2(c) (((c) >= 0x40) && ((c) != 0x7f) && ((c) <= 0xfc))
#define IsSjisIBMVDCChar1(c) (((c) >= 0xfa) && ((c) <= 0xfc))
#define IsSjisUDC1(c) (((c) >= 0xf0) && ((c) <= 0xfc))
#define JISX0201_OVERLINE 0x007e
#define JISX0201_YEN_SIGN 0x005c
#define Q_STRICT
#define UNICODE_OVERLINE 0x203e
#define UNICODE_YEN_SIGN 0x00a5
#define USE_JISX0212
Functions
static uint jisx0201ToUnicode11 (uint h, uint l)
static uint jisx0208ToSjis (uint h, uint l)
static uint jisx0208ToSjis (uint jis)
static uint jisx0208ToUnicode11 (uint h, uint l)
static uint jisx0212ToUnicode11 (uint h, uint l)
static uint sjisToJisx0208 (uint h, uint l)
static uint unicode11ToJisx0201 (uint h, uint l)
static uint unicode11ToJisx0208 (uint h, uint l)
static uint unicode11ToJisx0212 (uint h, uint l)
Variables
static unsigned short const cp932_87_unicode []
static unsigned short const cp932_ed_ee_unicode []
static unsigned short const jisx0208_to_unicode []
static unsigned short const jisx0212_to_unicode []
static unsigned short const sjis208ibmvdc_unicode []
static unsigned short const unicode_to_jisx0208_00 []
static unsigned short const unicode_to_jisx0208_03 []
static unsigned short const unicode_to_jisx0208_04 []
static unsigned short const unicode_to_jisx0208_20 []
static unsigned short const unicode_to_jisx0208_21 []
static unsigned short const unicode_to_jisx0208_22 []
static unsigned short const unicode_to_jisx0208_23 []
static unsigned short const unicode_to_jisx0208_24 []
static unsigned short const unicode_to_jisx0208_25 []
static unsigned short const unicode_to_jisx0208_26 []
static unsigned short const unicode_to_jisx0208_30 []
static unsigned short const unicode_to_jisx0208_32 []
static unsigned short const unicode_to_jisx0208_33 []
static unsigned short const unicode_to_jisx0208_4e []
static unsigned short const unicode_to_jisx0208_4f []
static unsigned short const unicode_to_jisx0208_50 []
static unsigned short const unicode_to_jisx0208_51 []
static unsigned short const unicode_to_jisx0208_52 []
static unsigned short const unicode_to_jisx0208_53 []
static unsigned short const unicode_to_jisx0208_54 []
static unsigned short const unicode_to_jisx0208_55 []
static unsigned short const unicode_to_jisx0208_56 []
static unsigned short const unicode_to_jisx0208_57 []
static unsigned short const unicode_to_jisx0208_58 []
static unsigned short const unicode_to_jisx0208_59 []
static unsigned short const unicode_to_jisx0208_5a []
static unsigned short const unicode_to_jisx0208_5b []
static unsigned short const unicode_to_jisx0208_5c []
static unsigned short const unicode_to_jisx0208_5d []
static unsigned short const unicode_to_jisx0208_5e []
static unsigned short const unicode_to_jisx0208_5f []
static unsigned short const unicode_to_jisx0208_60 []
static unsigned short const unicode_to_jisx0208_61 []
static unsigned short const unicode_to_jisx0208_62 []
static unsigned short const unicode_to_jisx0208_63 []
static unsigned short const unicode_to_jisx0208_64 []
static unsigned short const unicode_to_jisx0208_65 []
static unsigned short const unicode_to_jisx0208_66 []
static unsigned short const unicode_to_jisx0208_67 []
static unsigned short const unicode_to_jisx0208_68 []
static unsigned short const unicode_to_jisx0208_69 []
static unsigned short const unicode_to_jisx0208_6a []
static unsigned short const unicode_to_jisx0208_6b []
static unsigned short const unicode_to_jisx0208_6c []
static unsigned short const unicode_to_jisx0208_6d []
static unsigned short const unicode_to_jisx0208_6e []
static unsigned short const unicode_to_jisx0208_6f []
static unsigned short const unicode_to_jisx0208_70 []
static unsigned short const unicode_to_jisx0208_71 []
static unsigned short const unicode_to_jisx0208_72 []
static unsigned short const unicode_to_jisx0208_73 []
static unsigned short const unicode_to_jisx0208_74 []
static unsigned short const unicode_to_jisx0208_75 []
static unsigned short const unicode_to_jisx0208_76 []
static unsigned short const unicode_to_jisx0208_77 []
static unsigned short const unicode_to_jisx0208_78 []
static unsigned short const unicode_to_jisx0208_79 []
static unsigned short const unicode_to_jisx0208_7a []
static unsigned short const unicode_to_jisx0208_7b []
static unsigned short const unicode_to_jisx0208_7c []
static unsigned short const unicode_to_jisx0208_7d []
static unsigned short const unicode_to_jisx0208_7e []
static unsigned short const unicode_to_jisx0208_7f []
static unsigned short const unicode_to_jisx0208_80 []
static unsigned short const unicode_to_jisx0208_81 []
static unsigned short const unicode_to_jisx0208_82 []
static unsigned short const unicode_to_jisx0208_83 []
static unsigned short const unicode_to_jisx0208_84 []
static unsigned short const unicode_to_jisx0208_85 []
static unsigned short const unicode_to_jisx0208_86 []
static unsigned short const unicode_to_jisx0208_87 []
static unsigned short const unicode_to_jisx0208_88 []
static unsigned short const unicode_to_jisx0208_89 []
static unsigned short const unicode_to_jisx0208_8a []
static unsigned short const unicode_to_jisx0208_8b []
static unsigned short const unicode_to_jisx0208_8c []
static unsigned short const unicode_to_jisx0208_8d []
static unsigned short const unicode_to_jisx0208_8e []
static unsigned short const unicode_to_jisx0208_8f []
static unsigned short const unicode_to_jisx0208_90 []
static unsigned short const unicode_to_jisx0208_91 []
static unsigned short const unicode_to_jisx0208_92 []
static unsigned short const unicode_to_jisx0208_93 []
static unsigned short const unicode_to_jisx0208_94 []
static unsigned short const unicode_to_jisx0208_95 []
static unsigned short const unicode_to_jisx0208_96 []
static unsigned short const unicode_to_jisx0208_97 []
static unsigned short const unicode_to_jisx0208_98 []
static unsigned short const unicode_to_jisx0208_99 []
static unsigned short const unicode_to_jisx0208_9a []
static unsigned short const unicode_to_jisx0208_9b []
static unsigned short const unicode_to_jisx0208_9c []
static unsigned short const unicode_to_jisx0208_9d []
static unsigned short const unicode_to_jisx0208_9e []
static unsigned short const unicode_to_jisx0208_9f []
static unsigned short const unicode_to_jisx0208_ff []
static unsigned short const *const unicode_to_jisx0208_map [0x100]
static unsigned short const unicode_to_jisx0212_00 []
static unsigned short const unicode_to_jisx0212_01 []
static unsigned short const unicode_to_jisx0212_02 []
static unsigned short const unicode_to_jisx0212_03 []
static unsigned short const unicode_to_jisx0212_04 []
static unsigned short const unicode_to_jisx0212_21 []
static unsigned short const unicode_to_jisx0212_32 []
static unsigned short const unicode_to_jisx0212_4e []
static unsigned short const unicode_to_jisx0212_4f []
static unsigned short const unicode_to_jisx0212_50 []
static unsigned short const unicode_to_jisx0212_51 []
static unsigned short const unicode_to_jisx0212_52 []
static unsigned short const unicode_to_jisx0212_53 []
static unsigned short const unicode_to_jisx0212_54 []
static unsigned short const unicode_to_jisx0212_55 []
static unsigned short const unicode_to_jisx0212_56 []
static unsigned short const unicode_to_jisx0212_57 []
static unsigned short const unicode_to_jisx0212_58 []
static unsigned short const unicode_to_jisx0212_59 []
static unsigned short const unicode_to_jisx0212_5a []
static unsigned short const unicode_to_jisx0212_5b []
static unsigned short const unicode_to_jisx0212_5c []
static unsigned short const unicode_to_jisx0212_5d []
static unsigned short const unicode_to_jisx0212_5e []
static unsigned short const unicode_to_jisx0212_5f []
static unsigned short const unicode_to_jisx0212_60 []
static unsigned short const unicode_to_jisx0212_61 []
static unsigned short const unicode_to_jisx0212_62 []
static unsigned short const unicode_to_jisx0212_63 []
static unsigned short const unicode_to_jisx0212_64 []
static unsigned short const unicode_to_jisx0212_65 []
static unsigned short const unicode_to_jisx0212_66 []
static unsigned short const unicode_to_jisx0212_67 []
static unsigned short const unicode_to_jisx0212_68 []
static unsigned short const unicode_to_jisx0212_69 []
static unsigned short const unicode_to_jisx0212_6a []
static unsigned short const unicode_to_jisx0212_6b []
static unsigned short const unicode_to_jisx0212_6c []
static unsigned short const unicode_to_jisx0212_6d []
static unsigned short const unicode_to_jisx0212_6e []
static unsigned short const unicode_to_jisx0212_6f []
static unsigned short const unicode_to_jisx0212_70 []
static unsigned short const unicode_to_jisx0212_71 []
static unsigned short const unicode_to_jisx0212_72 []
static unsigned short const unicode_to_jisx0212_73 []
static unsigned short const unicode_to_jisx0212_74 []
static unsigned short const unicode_to_jisx0212_75 []
static unsigned short const unicode_to_jisx0212_76 []
static unsigned short const unicode_to_jisx0212_77 []
static unsigned short const unicode_to_jisx0212_78 []
static unsigned short const unicode_to_jisx0212_79 []
static unsigned short const unicode_to_jisx0212_7a []
static unsigned short const unicode_to_jisx0212_7b []
static unsigned short const unicode_to_jisx0212_7c []
static unsigned short const unicode_to_jisx0212_7d []
static unsigned short const unicode_to_jisx0212_7e []
static unsigned short const unicode_to_jisx0212_7f []
static unsigned short const unicode_to_jisx0212_80 []
static unsigned short const unicode_to_jisx0212_81 []
static unsigned short const unicode_to_jisx0212_82 []
static unsigned short const unicode_to_jisx0212_83 []
static unsigned short const unicode_to_jisx0212_84 []
static unsigned short const unicode_to_jisx0212_85 []
static unsigned short const unicode_to_jisx0212_86 []
static unsigned short const unicode_to_jisx0212_87 []
static unsigned short const unicode_to_jisx0212_88 []
static unsigned short const unicode_to_jisx0212_89 []
static unsigned short const unicode_to_jisx0212_8a []
static unsigned short const unicode_to_jisx0212_8b []
static unsigned short const unicode_to_jisx0212_8c []
static unsigned short const unicode_to_jisx0212_8d []
static unsigned short const unicode_to_jisx0212_8e []
static unsigned short const unicode_to_jisx0212_8f []
static unsigned short const unicode_to_jisx0212_90 []
static unsigned short const unicode_to_jisx0212_91 []
static unsigned short const unicode_to_jisx0212_92 []
static unsigned short const unicode_to_jisx0212_93 []
static unsigned short const unicode_to_jisx0212_94 []
static unsigned short const unicode_to_jisx0212_95 []
static unsigned short const unicode_to_jisx0212_96 []
static unsigned short const unicode_to_jisx0212_97 []
static unsigned short const unicode_to_jisx0212_98 []
static unsigned short const unicode_to_jisx0212_99 []
static unsigned short const unicode_to_jisx0212_9a []
static unsigned short const unicode_to_jisx0212_9b []
static unsigned short const unicode_to_jisx0212_9c []
static unsigned short const unicode_to_jisx0212_9d []
static unsigned short const unicode_to_jisx0212_9e []
static unsigned short const unicode_to_jisx0212_9f []
static unsigned short const unicode_to_jisx0212_f9 []
static unsigned short const unicode_to_jisx0212_fa []
static unsigned short const unicode_to_jisx0212_ff []
static unsigned short const *const unicode_to_jisx0212_map [0x100]
Macro Definition Documentation
IsJisChar
#define IsJisChar (c) (((c) >= 0x21) && ((c) <= 0x7e))
Definition at line 60 of file qjpunicode.cpp.
Referenced by QJpUnicodeConv::jisx0208ToUnicode(), and QJpUnicodeConv::jisx0212ToUnicode().
IsKana
#define IsKana (c) (((c) >= 0xa1) && ((c) <= 0xdf))
Definition at line 59 of file qjpunicode.cpp.
Referenced by QJpUnicodeConv::jisx0201KanaToUnicode(), QJpUnicodeConv::jisx0201ToUnicode(), and QJpUnicodeConv::unicodeToJisx0201Kana().
IsLatin
#define IsLatin (c) (/*((c) >= 0x00) &&*/ ((c) <= 0x7f))
Definition at line 58 of file qjpunicode.cpp.
Referenced by QJpUnicodeConv::jisx0201LatinToUnicode(), QJpUnicodeConv::jisx0201ToUnicode(), and QJpUnicodeConv::unicodeToJisx0201Latin().
IsSjisChar1
#define IsSjisChar1 (c)
Value:
((((c) >= 0x81) && ((c) <= 0x9f)) ||        \
                         (((c) >= 0xe0) && ((c) <= 0xfc)))
Definition at line 61 of file qjpunicode.cpp.
Referenced by QJpUnicodeConv::sjisToUnicode().
IsSjisChar2
#define IsSjisChar2 (c) (((c) >= 0x40) && ((c) != 0x7f) && ((c) <= 0xfc))
Definition at line 64 of file qjpunicode.cpp.
Referenced by QJpUnicodeConv::sjisToUnicode().
IsSjisIBMVDCChar1
#define IsSjisIBMVDCChar1 (c) (((c) >= 0xfa) && ((c) <= 0xfc))
Definition at line 66 of file qjpunicode.cpp.
Referenced by QJpUnicodeConv::sjisibmvdcToUnicode().
IsSjisUDC1
#define IsSjisUDC1 (c) (((c) >= 0xf0) && ((c) <= 0xfc))
Definition at line 63 of file qjpunicode.cpp.
JISX0201_OVERLINE
#define JISX0201_OVERLINE 0x007e
Definition at line 826 of file qjpunicode.cpp.
Referenced by jisx0201ToUnicode11(), and unicode11ToJisx0201().
JISX0201_YEN_SIGN
#define JISX0201_YEN_SIGN 0x005c
Definition at line 823 of file qjpunicode.cpp.
Referenced by jisx0201ToUnicode11(), and unicode11ToJisx0201().
Q_STRICT
#define Q_STRICT
Definition at line 56 of file qjpunicode.cpp.
UNICODE_OVERLINE
#define UNICODE_OVERLINE 0x203e
Definition at line 827 of file qjpunicode.cpp.
Referenced by jisx0201ToUnicode11().
UNICODE_YEN_SIGN
#define UNICODE_YEN_SIGN 0x00a5
Definition at line 824 of file qjpunicode.cpp.
Referenced by jisx0201ToUnicode11().
USE_JISX0212
#define USE_JISX0212
Definition at line 54 of file qjpunicode.cpp.
Function Documentation
jisx0201ToUnicode11()
static uint jisx0201ToUnicode11 (uint h, uint l) static
Definition at line 829 of file qjpunicode.cpp.
Referenced by QJpUnicodeConv::jisx0201KanaToUnicode(), QJpUnicodeConv::jisx0201LatinToUnicode(), and jisx0208ToSjis().
 {
     if (h == 0x00) {
         if (l < 0x80) {
             if (l == JISX0201_YEN_SIGN) {
                 return UNICODE_YEN_SIGN;
             } else if (l == JISX0201_OVERLINE) {
                 return UNICODE_OVERLINE;
             } else {
                 return l;
             }
         } else if ((0xa1 <= l) && (l <= 0x00df)) {
             return 0xff61 + l - 0x00a1;
         }
     }
     return 0x0000;
 }
jisx0208ToSjis() [1/2]
static uint jisx0208ToSjis (uint h, uint l) static
Definition at line 794 of file qjpunicode.cpp.
Referenced by jisx0208ToSjis(), and QJpUnicodeConv::unicodeToSjis().
 {
     if ((0x0021 <= h) && (h <= 0x007e) && (0x0021 <= l) && (l <= 0x007e)) {
         return ((((h - 1) >> 1) + ((h <= 0x5e) ? 0x71 : 0xb1)) << 8) |
                (l + ((h & 1) ? ((l < 0x60) ? 0x1f : 0x20) : 0x7e));
     }
     return 0x0000;
 }
jisx0208ToSjis() [2/2]
static uint jisx0208ToSjis (uint jis) inline static
Definition at line 70 of file qjpunicode.cpp.
 {
     return jisx0208ToSjis((jis & 0xff00) >> 8, (jis & 0x00ff));
 }
jisx0208ToUnicode11()
static uint jisx0208ToUnicode11 (uint h, uint l) static
Definition at line 2100 of file qjpunicode.cpp.
Referenced by jisx0208ToSjis(), and QJpUnicodeConv::jisx0208ToUnicode().
 {
     if ((0x0021 <= h) && (h <= 0x007e) && (0x0021 <= l) && (l <= 0x007e)) {
         return jisx0208_to_unicode[(h - 0x0021) * 0x005e + (l - 0x0021)];
     }
     return 0x0000;
 }
jisx0212ToUnicode11()
static uint jisx0212ToUnicode11 (uint h, uint l) static
Definition at line 6943 of file qjpunicode.cpp.
Referenced by jisx0208ToSjis(), and QJpUnicodeConv::jisx0212ToUnicode().
 {
     if ((0x0021 <= h) && (h <= 0x007e) && (0x0021 <= l) && (l <= 0x007e)) {
         return jisx0212_to_unicode[(h - 0x0021) * 0x005e + (l - 0x0021)];
     }
     return 0x0000;
 }
sjisToJisx0208()
static uint sjisToJisx0208 (uint h, uint l) static
Definition at line 803 of file qjpunicode.cpp.
Referenced by jisx0208ToSjis(), and QJpUnicodeConv::sjisToUnicode().
 {
     if ((((0x81 <= h) && (h <= 0x9f)) || ((0xe0 <= h) && (h <= 0xef))) &&
         ((0x40 <= l) && (l != 0x7f) && (l <= 0xfc))) {
         if (l < 0x9f) {
             return (((h << 1) - ((h <= 0x9f) ? 0x00e1 : 0x0161)) << 8) |
                    (l - ((l <= 0x7f) ? 0x1f : 0x20));
         } else {
             return (((h << 1) - ((h <= 0x9f) ? 0x00e1 : 0x0161) + 1) << 8) |
                    (l - 0x7e);
         }
     }
     return 0x0000;
 }
unicode11ToJisx0201()
static uint unicode11ToJisx0201 (uint h, uint l) static
Definition at line 852 of file qjpunicode.cpp.
Referenced by jisx0208ToSjis(), QJpUnicodeConv::unicodeToJisx0201Kana(), and QJpUnicodeConv::unicodeToJisx0201Latin().
 {
     if ((h == 0x00) && (l < 0x80)) {
         if ((l == JISX0201_YEN_SIGN) ||
             (l == JISX0201_OVERLINE)) {
             return 0x0000;
         }
         return l;
     } else if ((h == 0x00) && (l == 0xa5)) {
         return JISX0201_YEN_SIGN;
     } else if ((h == 0x20) && (l == 0x3e)) {
         return JISX0201_OVERLINE;
     } else if ((h == 0xff) && (0x61 <= l) && (l <= 0x9f)) {
         return 0x00a1 + l - 0x61;
     }
     return 0x0000;
 }
unicode11ToJisx0208()
static uint unicode11ToJisx0208 (uint h, uint l) static
Definition at line 5697 of file qjpunicode.cpp.
Referenced by jisx0208ToSjis(), and QJpUnicodeConv::unicodeToJisx0208().
 {
     unsigned short const *table;
     table = unicode_to_jisx0208_map[h];
     if (table != 0) {
         return table[l];
     }
     return 0x0000;
 }
unicode11ToJisx0212()
static uint unicode11ToJisx0212 (uint h, uint l) static
Definition at line 10404 of file qjpunicode.cpp.
Referenced by jisx0208ToSjis(), and QJpUnicodeConv::unicodeToJisx0212().
 {
     unsigned short const *table;
     table = unicode_to_jisx0212_map[h];
     if (table != 0) {
         return table[l];
     }
     return 0x0000;
 }
Variable Documentation
cp932_87_unicode
unsigned short const cp932_87_unicode[] static
Initial value:
= {
        0x2460, 0x2461, 0x2462, 0x2463, 0x2464, 0x2465, 0x2466, 0x2467,
        0x2468, 0x2469, 0x246a, 0x246b, 0x246c, 0x246d, 0x246e, 0x246f,
        0x2470, 0x2471, 0x2472, 0x2473, 0x2160, 0x2161, 0x2162, 0x2163,
        0x2164, 0x2165, 0x2166, 0x2167, 0x2168, 0x2169, 0x0000, 0x3349,
        0x3314, 0x3322, 0x334d, 0x3318, 0x3327, 0x3303, 0x3336, 0x3351,
        0x3357, 0x330d, 0x3326, 0x3323, 0x332b, 0x334a, 0x333b, 0x339c,
        0x339d, 0x339e, 0x338e, 0x338f, 0x33c4, 0x33a1, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x337b, 0x0000,
        0x301d, 0x301f, 0x2116, 0x33cd, 0x2121, 0x32a4, 0x32a5, 0x32a6,
        0x32a7, 0x32a8, 0x3231, 0x3232, 0x3239, 0x337e, 0x337d, 0x337c,
        0x2252, 0x2261, 0x222b, 0x222e, 0x2211, 0x221a, 0x22a5, 0x2220,
        0x221f, 0x22bf, 0x2235, 0x2229, 0x222a
}
Definition at line 10524 of file qjpunicode.cpp.
Referenced by QJpUnicodeConv::cp932ToUnicode(), and QJpUnicodeConv::unicodeToCp932().
cp932_ed_ee_unicode
unsigned short const cp932_ed_ee_unicode[] static
Definition at line 10540 of file qjpunicode.cpp.
Referenced by QJpUnicodeConv::cp932ToUnicode(), and QJpUnicodeConv::unicodeToCp932().
jisx0208_to_unicode
unsigned short const jisx0208_to_unicode[] static
Definition at line 875 of file qjpunicode.cpp.
Referenced by jisx0208ToUnicode11().
jisx0212_to_unicode
unsigned short const jisx0212_to_unicode[] static
Definition at line 5715 of file qjpunicode.cpp.
Referenced by jisx0212ToUnicode11().
sjis208ibmvdc_unicode
unsigned short const sjis208ibmvdc_unicode[] static
Definition at line 10421 of file qjpunicode.cpp.
Referenced by QJpUnicodeConv::sjisibmvdcToUnicode(), and QJpUnicodeConv::unicodeToSjisibmvdc().
unicode_to_jisx0208_00
unsigned short const unicode_to_jisx0208_00[] static
Definition at line 2113 of file qjpunicode.cpp.
unicode_to_jisx0208_03
unsigned short const unicode_to_jisx0208_03[] static
Definition at line 2149 of file qjpunicode.cpp.
unicode_to_jisx0208_04
unsigned short const unicode_to_jisx0208_04[] static
Definition at line 2185 of file qjpunicode.cpp.
unicode_to_jisx0208_20
unsigned short const unicode_to_jisx0208_20[] static
Definition at line 2221 of file qjpunicode.cpp.
unicode_to_jisx0208_21
unsigned short const unicode_to_jisx0208_21[] static
Definition at line 2257 of file qjpunicode.cpp.
unicode_to_jisx0208_22
unsigned short const unicode_to_jisx0208_22[] static
Definition at line 2293 of file qjpunicode.cpp.
unicode_to_jisx0208_23
unsigned short const unicode_to_jisx0208_23[] static
Definition at line 2329 of file qjpunicode.cpp.
unicode_to_jisx0208_24
unsigned short const unicode_to_jisx0208_24[] static
Definition at line 2365 of file qjpunicode.cpp.
unicode_to_jisx0208_25
unsigned short const unicode_to_jisx0208_25[] static
Definition at line 2401 of file qjpunicode.cpp.
unicode_to_jisx0208_26
unsigned short const unicode_to_jisx0208_26[] static
Definition at line 2437 of file qjpunicode.cpp.
unicode_to_jisx0208_30
unsigned short const unicode_to_jisx0208_30[] static
Definition at line 2473 of file qjpunicode.cpp.
unicode_to_jisx0208_32
unsigned short const unicode_to_jisx0208_32[] static
Definition at line 2509 of file qjpunicode.cpp.
unicode_to_jisx0208_33
unsigned short const unicode_to_jisx0208_33[] static
Definition at line 2545 of file qjpunicode.cpp.
unicode_to_jisx0208_4e
unsigned short const unicode_to_jisx0208_4e[] static
Definition at line 2581 of file qjpunicode.cpp.
unicode_to_jisx0208_4f
unsigned short const unicode_to_jisx0208_4f[] static
Definition at line 2617 of file qjpunicode.cpp.
unicode_to_jisx0208_50
unsigned short const unicode_to_jisx0208_50[] static
Definition at line 2653 of file qjpunicode.cpp.
unicode_to_jisx0208_51
unsigned short const unicode_to_jisx0208_51[] static
Definition at line 2689 of file qjpunicode.cpp.
unicode_to_jisx0208_52
unsigned short const unicode_to_jisx0208_52[] static
Definition at line 2725 of file qjpunicode.cpp.
unicode_to_jisx0208_53
unsigned short const unicode_to_jisx0208_53[] static
Definition at line 2761 of file qjpunicode.cpp.
unicode_to_jisx0208_54
unsigned short const unicode_to_jisx0208_54[] static
Definition at line 2797 of file qjpunicode.cpp.
unicode_to_jisx0208_55
unsigned short const unicode_to_jisx0208_55[] static
Definition at line 2833 of file qjpunicode.cpp.
unicode_to_jisx0208_56
unsigned short const unicode_to_jisx0208_56[] static
Definition at line 2869 of file qjpunicode.cpp.
unicode_to_jisx0208_57
unsigned short const unicode_to_jisx0208_57[] static
Definition at line 2905 of file qjpunicode.cpp.
unicode_to_jisx0208_58
unsigned short const unicode_to_jisx0208_58[] static
Definition at line 2941 of file qjpunicode.cpp.
unicode_to_jisx0208_59
unsigned short const unicode_to_jisx0208_59[] static
Definition at line 2977 of file qjpunicode.cpp.
unicode_to_jisx0208_5a
unsigned short const unicode_to_jisx0208_5a[] static
Definition at line 3013 of file qjpunicode.cpp.
unicode_to_jisx0208_5b
unsigned short const unicode_to_jisx0208_5b[] static
Definition at line 3049 of file qjpunicode.cpp.
unicode_to_jisx0208_5c
unsigned short const unicode_to_jisx0208_5c[] static
Definition at line 3085 of file qjpunicode.cpp.
unicode_to_jisx0208_5d
unsigned short const unicode_to_jisx0208_5d[] static
Definition at line 3121 of file qjpunicode.cpp.
unicode_to_jisx0208_5e
unsigned short const unicode_to_jisx0208_5e[] static
Definition at line 3157 of file qjpunicode.cpp.
unicode_to_jisx0208_5f
unsigned short const unicode_to_jisx0208_5f[] static
Definition at line 3193 of file qjpunicode.cpp.
unicode_to_jisx0208_60
unsigned short const unicode_to_jisx0208_60[] static
Definition at line 3229 of file qjpunicode.cpp.
unicode_to_jisx0208_61
unsigned short const unicode_to_jisx0208_61[] static
Definition at line 3265 of file qjpunicode.cpp.
unicode_to_jisx0208_62
unsigned short const unicode_to_jisx0208_62[] static
Definition at line 3301 of file qjpunicode.cpp.
unicode_to_jisx0208_63
unsigned short const unicode_to_jisx0208_63[] static
Definition at line 3337 of file qjpunicode.cpp.
unicode_to_jisx0208_64
unsigned short const unicode_to_jisx0208_64[] static
Definition at line 3373 of file qjpunicode.cpp.
unicode_to_jisx0208_65
unsigned short const unicode_to_jisx0208_65[] static
Definition at line 3409 of file qjpunicode.cpp.
unicode_to_jisx0208_66
unsigned short const unicode_to_jisx0208_66[] static
Definition at line 3445 of file qjpunicode.cpp.
unicode_to_jisx0208_67
unsigned short const unicode_to_jisx0208_67[] static
Definition at line 3481 of file qjpunicode.cpp.
unicode_to_jisx0208_68
unsigned short const unicode_to_jisx0208_68[] static
Definition at line 3517 of file qjpunicode.cpp.
unicode_to_jisx0208_69
unsigned short const unicode_to_jisx0208_69[] static
Definition at line 3553 of file qjpunicode.cpp.
unicode_to_jisx0208_6a
unsigned short const unicode_to_jisx0208_6a[] static
Definition at line 3589 of file qjpunicode.cpp.
unicode_to_jisx0208_6b
unsigned short const unicode_to_jisx0208_6b[] static
Definition at line 3625 of file qjpunicode.cpp.
unicode_to_jisx0208_6c
unsigned short const unicode_to_jisx0208_6c[] static
Definition at line 3661 of file qjpunicode.cpp.
unicode_to_jisx0208_6d
unsigned short const unicode_to_jisx0208_6d[] static
Definition at line 3697 of file qjpunicode.cpp.
unicode_to_jisx0208_6e
unsigned short const unicode_to_jisx0208_6e[] static
Definition at line 3733 of file qjpunicode.cpp.
unicode_to_jisx0208_6f
unsigned short const unicode_to_jisx0208_6f[] static
Definition at line 3769 of file qjpunicode.cpp.
unicode_to_jisx0208_70
unsigned short const unicode_to_jisx0208_70[] static
Definition at line 3805 of file qjpunicode.cpp.
unicode_to_jisx0208_71
unsigned short const unicode_to_jisx0208_71[] static
Definition at line 3841 of file qjpunicode.cpp.
unicode_to_jisx0208_72
unsigned short const unicode_to_jisx0208_72[] static
Definition at line 3877 of file qjpunicode.cpp.
unicode_to_jisx0208_73
unsigned short const unicode_to_jisx0208_73[] static
Definition at line 3913 of file qjpunicode.cpp.
unicode_to_jisx0208_74
unsigned short const unicode_to_jisx0208_74[] static
Definition at line 3949 of file qjpunicode.cpp.
unicode_to_jisx0208_75
unsigned short const unicode_to_jisx0208_75[] static
Definition at line 3985 of file qjpunicode.cpp.
unicode_to_jisx0208_76
unsigned short const unicode_to_jisx0208_76[] static
Definition at line 4021 of file qjpunicode.cpp.
unicode_to_jisx0208_77
unsigned short const unicode_to_jisx0208_77[] static
Definition at line 4057 of file qjpunicode.cpp.
unicode_to_jisx0208_78
unsigned short const unicode_to_jisx0208_78[] static
Definition at line 4093 of file qjpunicode.cpp.
unicode_to_jisx0208_79
unsigned short const unicode_to_jisx0208_79[] static
Definition at line 4129 of file qjpunicode.cpp.
unicode_to_jisx0208_7a
unsigned short const unicode_to_jisx0208_7a[] static
Definition at line 4165 of file qjpunicode.cpp.
unicode_to_jisx0208_7b
unsigned short const unicode_to_jisx0208_7b[] static
Definition at line 4201 of file qjpunicode.cpp.
unicode_to_jisx0208_7c
unsigned short const unicode_to_jisx0208_7c[] static
Definition at line 4237 of file qjpunicode.cpp.
unicode_to_jisx0208_7d
unsigned short const unicode_to_jisx0208_7d[] static
Definition at line 4273 of file qjpunicode.cpp.
unicode_to_jisx0208_7e
unsigned short const unicode_to_jisx0208_7e[] static
Definition at line 4309 of file qjpunicode.cpp.
unicode_to_jisx0208_7f
unsigned short const unicode_to_jisx0208_7f[] static
Definition at line 4345 of file qjpunicode.cpp.
unicode_to_jisx0208_80
unsigned short const unicode_to_jisx0208_80[] static
Definition at line 4381 of file qjpunicode.cpp.
unicode_to_jisx0208_81
unsigned short const unicode_to_jisx0208_81[] static
Definition at line 4417 of file qjpunicode.cpp.
unicode_to_jisx0208_82
unsigned short const unicode_to_jisx0208_82[] static
Definition at line 4453 of file qjpunicode.cpp.
unicode_to_jisx0208_83
unsigned short const unicode_to_jisx0208_83[] static
Definition at line 4489 of file qjpunicode.cpp.
unicode_to_jisx0208_84
unsigned short const unicode_to_jisx0208_84[] static
Definition at line 4525 of file qjpunicode.cpp.
unicode_to_jisx0208_85
unsigned short const unicode_to_jisx0208_85[] static
Definition at line 4561 of file qjpunicode.cpp.
unicode_to_jisx0208_86
unsigned short const unicode_to_jisx0208_86[] static
Definition at line 4597 of file qjpunicode.cpp.
unicode_to_jisx0208_87
unsigned short const unicode_to_jisx0208_87[] static
Definition at line 4633 of file qjpunicode.cpp.
unicode_to_jisx0208_88
unsigned short const unicode_to_jisx0208_88[] static
Definition at line 4669 of file qjpunicode.cpp.
unicode_to_jisx0208_89
unsigned short const unicode_to_jisx0208_89[] static
Definition at line 4705 of file qjpunicode.cpp.
unicode_to_jisx0208_8a
unsigned short const unicode_to_jisx0208_8a[] static
Definition at line 4741 of file qjpunicode.cpp.
unicode_to_jisx0208_8b
unsigned short const unicode_to_jisx0208_8b[] static
Definition at line 4777 of file qjpunicode.cpp.
unicode_to_jisx0208_8c
unsigned short const unicode_to_jisx0208_8c[] static
Definition at line 4813 of file qjpunicode.cpp.
unicode_to_jisx0208_8d
unsigned short const unicode_to_jisx0208_8d[] static
Definition at line 4849 of file qjpunicode.cpp.
unicode_to_jisx0208_8e
unsigned short const unicode_to_jisx0208_8e[] static
Definition at line 4885 of file qjpunicode.cpp.
unicode_to_jisx0208_8f
unsigned short const unicode_to_jisx0208_8f[] static
Definition at line 4921 of file qjpunicode.cpp.
unicode_to_jisx0208_90
unsigned short const unicode_to_jisx0208_90[] static
Definition at line 4957 of file qjpunicode.cpp.
unicode_to_jisx0208_91
unsigned short const unicode_to_jisx0208_91[] static
Definition at line 4993 of file qjpunicode.cpp.
unicode_to_jisx0208_92
unsigned short const unicode_to_jisx0208_92[] static
Definition at line 5029 of file qjpunicode.cpp.
unicode_to_jisx0208_93
unsigned short const unicode_to_jisx0208_93[] static
Definition at line 5065 of file qjpunicode.cpp.
unicode_to_jisx0208_94
unsigned short const unicode_to_jisx0208_94[] static
Definition at line 5101 of file qjpunicode.cpp.
unicode_to_jisx0208_95
unsigned short const unicode_to_jisx0208_95[] static
Definition at line 5137 of file qjpunicode.cpp.
unicode_to_jisx0208_96
unsigned short const unicode_to_jisx0208_96[] static
Definition at line 5173 of file qjpunicode.cpp.
unicode_to_jisx0208_97
unsigned short const unicode_to_jisx0208_97[] static
Definition at line 5209 of file qjpunicode.cpp.
unicode_to_jisx0208_98
unsigned short const unicode_to_jisx0208_98[] static
Definition at line 5245 of file qjpunicode.cpp.
unicode_to_jisx0208_99
unsigned short const unicode_to_jisx0208_99[] static
Definition at line 5281 of file qjpunicode.cpp.
unicode_to_jisx0208_9a
unsigned short const unicode_to_jisx0208_9a[] static
Definition at line 5317 of file qjpunicode.cpp.
unicode_to_jisx0208_9b
unsigned short const unicode_to_jisx0208_9b[] static
Definition at line 5353 of file qjpunicode.cpp.
unicode_to_jisx0208_9c
unsigned short const unicode_to_jisx0208_9c[] static
Definition at line 5389 of file qjpunicode.cpp.
unicode_to_jisx0208_9d
unsigned short const unicode_to_jisx0208_9d[] static
Definition at line 5425 of file qjpunicode.cpp.
unicode_to_jisx0208_9e
unsigned short const unicode_to_jisx0208_9e[] static
Definition at line 5461 of file qjpunicode.cpp.
unicode_to_jisx0208_9f
unsigned short const unicode_to_jisx0208_9f[] static
Definition at line 5497 of file qjpunicode.cpp.
unicode_to_jisx0208_ff
unsigned short const unicode_to_jisx0208_ff[] static
Definition at line 5533 of file qjpunicode.cpp.
unicode_to_jisx0208_map
unsigned short const* const unicode_to_jisx0208_map[0x100] static
Definition at line 5569 of file qjpunicode.cpp.
Referenced by unicode11ToJisx0208().
unicode_to_jisx0212_00
unsigned short const unicode_to_jisx0212_00[] static
Definition at line 6964 of file qjpunicode.cpp.
unicode_to_jisx0212_01
unsigned short const unicode_to_jisx0212_01[] static
Definition at line 7000 of file qjpunicode.cpp.
unicode_to_jisx0212_02
unsigned short const unicode_to_jisx0212_02[] static
Definition at line 7036 of file qjpunicode.cpp.
unicode_to_jisx0212_03
unsigned short const unicode_to_jisx0212_03[] static
Definition at line 7072 of file qjpunicode.cpp.
unicode_to_jisx0212_04
unsigned short const unicode_to_jisx0212_04[] static
Definition at line 7108 of file qjpunicode.cpp.
unicode_to_jisx0212_21
unsigned short const unicode_to_jisx0212_21[] static
Definition at line 7144 of file qjpunicode.cpp.
unicode_to_jisx0212_32
unsigned short const unicode_to_jisx0212_32[] static
Definition at line 7180 of file qjpunicode.cpp.
unicode_to_jisx0212_4e
unsigned short const unicode_to_jisx0212_4e[] static
Definition at line 7216 of file qjpunicode.cpp.
unicode_to_jisx0212_4f
unsigned short const unicode_to_jisx0212_4f[] static
Definition at line 7252 of file qjpunicode.cpp.
unicode_to_jisx0212_50
unsigned short const unicode_to_jisx0212_50[] static
Definition at line 7288 of file qjpunicode.cpp.
unicode_to_jisx0212_51
unsigned short const unicode_to_jisx0212_51[] static
Definition at line 7324 of file qjpunicode.cpp.
unicode_to_jisx0212_52
unsigned short const unicode_to_jisx0212_52[] static
Definition at line 7360 of file qjpunicode.cpp.
unicode_to_jisx0212_53
unsigned short const unicode_to_jisx0212_53[] static
Definition at line 7396 of file qjpunicode.cpp.
unicode_to_jisx0212_54
unsigned short const unicode_to_jisx0212_54[] static
Definition at line 7432 of file qjpunicode.cpp.
unicode_to_jisx0212_55
unsigned short const unicode_to_jisx0212_55[] static
Definition at line 7468 of file qjpunicode.cpp.
unicode_to_jisx0212_56
unsigned short const unicode_to_jisx0212_56[] static
Definition at line 7504 of file qjpunicode.cpp.
unicode_to_jisx0212_57
unsigned short const unicode_to_jisx0212_57[] static
Definition at line 7540 of file qjpunicode.cpp.
unicode_to_jisx0212_58
unsigned short const unicode_to_jisx0212_58[] static
Definition at line 7576 of file qjpunicode.cpp.
unicode_to_jisx0212_59
unsigned short const unicode_to_jisx0212_59[] static
Definition at line 7612 of file qjpunicode.cpp.
unicode_to_jisx0212_5a
unsigned short const unicode_to_jisx0212_5a[] static
Definition at line 7648 of file qjpunicode.cpp.
unicode_to_jisx0212_5b
unsigned short const unicode_to_jisx0212_5b[] static
Definition at line 7684 of file qjpunicode.cpp.
unicode_to_jisx0212_5c
unsigned short const unicode_to_jisx0212_5c[] static
Definition at line 7720 of file qjpunicode.cpp.
unicode_to_jisx0212_5d
unsigned short const unicode_to_jisx0212_5d[] static
Definition at line 7756 of file qjpunicode.cpp.
unicode_to_jisx0212_5e
unsigned short const unicode_to_jisx0212_5e[] static
Definition at line 7792 of file qjpunicode.cpp.
unicode_to_jisx0212_5f
unsigned short const unicode_to_jisx0212_5f[] static
Definition at line 7828 of file qjpunicode.cpp.
unicode_to_jisx0212_60
unsigned short const unicode_to_jisx0212_60[] static
Definition at line 7864 of file qjpunicode.cpp.
unicode_to_jisx0212_61
unsigned short const unicode_to_jisx0212_61[] static
Definition at line 7900 of file qjpunicode.cpp.
unicode_to_jisx0212_62
unsigned short const unicode_to_jisx0212_62[] static
Definition at line 7936 of file qjpunicode.cpp.
unicode_to_jisx0212_63
unsigned short const unicode_to_jisx0212_63[] static
Definition at line 7972 of file qjpunicode.cpp.
unicode_to_jisx0212_64
unsigned short const unicode_to_jisx0212_64[] static
Definition at line 8008 of file qjpunicode.cpp.
unicode_to_jisx0212_65
unsigned short const unicode_to_jisx0212_65[] static
Definition at line 8044 of file qjpunicode.cpp.
unicode_to_jisx0212_66
unsigned short const unicode_to_jisx0212_66[] static
Definition at line 8080 of file qjpunicode.cpp.
unicode_to_jisx0212_67
unsigned short const unicode_to_jisx0212_67[] static
Definition at line 8116 of file qjpunicode.cpp.
unicode_to_jisx0212_68
unsigned short const unicode_to_jisx0212_68[] static
Definition at line 8152 of file qjpunicode.cpp.
unicode_to_jisx0212_69
unsigned short const unicode_to_jisx0212_69[] static
Definition at line 8188 of file qjpunicode.cpp.
unicode_to_jisx0212_6a
unsigned short const unicode_to_jisx0212_6a[] static
Definition at line 8224 of file qjpunicode.cpp.
unicode_to_jisx0212_6b
unsigned short const unicode_to_jisx0212_6b[] static
Definition at line 8260 of file qjpunicode.cpp.
unicode_to_jisx0212_6c
unsigned short const unicode_to_jisx0212_6c[] static
Definition at line 8296 of file qjpunicode.cpp.
unicode_to_jisx0212_6d
unsigned short const unicode_to_jisx0212_6d[] static
Definition at line 8332 of file qjpunicode.cpp.
unicode_to_jisx0212_6e
unsigned short const unicode_to_jisx0212_6e[] static
Definition at line 8368 of file qjpunicode.cpp.
unicode_to_jisx0212_6f
unsigned short const unicode_to_jisx0212_6f[] static
Definition at line 8404 of file qjpunicode.cpp.
unicode_to_jisx0212_70
unsigned short const unicode_to_jisx0212_70[] static
Definition at line 8440 of file qjpunicode.cpp.
unicode_to_jisx0212_71
unsigned short const unicode_to_jisx0212_71[] static
Definition at line 8476 of file qjpunicode.cpp.
unicode_to_jisx0212_72
unsigned short const unicode_to_jisx0212_72[] static
Definition at line 8512 of file qjpunicode.cpp.
unicode_to_jisx0212_73
unsigned short const unicode_to_jisx0212_73[] static
Definition at line 8548 of file qjpunicode.cpp.
unicode_to_jisx0212_74
unsigned short const unicode_to_jisx0212_74[] static
Definition at line 8584 of file qjpunicode.cpp.
unicode_to_jisx0212_75
unsigned short const unicode_to_jisx0212_75[] static
Definition at line 8620 of file qjpunicode.cpp.
unicode_to_jisx0212_76
unsigned short const unicode_to_jisx0212_76[] static
Definition at line 8656 of file qjpunicode.cpp.
unicode_to_jisx0212_77
unsigned short const unicode_to_jisx0212_77[] static
Definition at line 8692 of file qjpunicode.cpp.
unicode_to_jisx0212_78
unsigned short const unicode_to_jisx0212_78[] static
Definition at line 8728 of file qjpunicode.cpp.
unicode_to_jisx0212_79
unsigned short const unicode_to_jisx0212_79[] static
Definition at line 8764 of file qjpunicode.cpp.
unicode_to_jisx0212_7a
unsigned short const unicode_to_jisx0212_7a[] static
Definition at line 8800 of file qjpunicode.cpp.
unicode_to_jisx0212_7b
unsigned short const unicode_to_jisx0212_7b[] static
Definition at line 8836 of file qjpunicode.cpp.
unicode_to_jisx0212_7c
unsigned short const unicode_to_jisx0212_7c[] static
Definition at line 8872 of file qjpunicode.cpp.
unicode_to_jisx0212_7d
unsigned short const unicode_to_jisx0212_7d[] static
Definition at line 8908 of file qjpunicode.cpp.
unicode_to_jisx0212_7e
unsigned short const unicode_to_jisx0212_7e[] static
Definition at line 8944 of file qjpunicode.cpp.
unicode_to_jisx0212_7f
unsigned short const unicode_to_jisx0212_7f[] static
Definition at line 8980 of file qjpunicode.cpp.
unicode_to_jisx0212_80
unsigned short const unicode_to_jisx0212_80[] static
Definition at line 9016 of file qjpunicode.cpp.
unicode_to_jisx0212_81
unsigned short const unicode_to_jisx0212_81[] static
Definition at line 9052 of file qjpunicode.cpp.
unicode_to_jisx0212_82
unsigned short const unicode_to_jisx0212_82[] static
Definition at line 9088 of file qjpunicode.cpp.
unicode_to_jisx0212_83
unsigned short const unicode_to_jisx0212_83[] static
Definition at line 9124 of file qjpunicode.cpp.
unicode_to_jisx0212_84
unsigned short const unicode_to_jisx0212_84[] static
Definition at line 9160 of file qjpunicode.cpp.
unicode_to_jisx0212_85
unsigned short const unicode_to_jisx0212_85[] static
Definition at line 9196 of file qjpunicode.cpp.
unicode_to_jisx0212_86
unsigned short const unicode_to_jisx0212_86[] static
Definition at line 9232 of file qjpunicode.cpp.
unicode_to_jisx0212_87
unsigned short const unicode_to_jisx0212_87[] static
Definition at line 9268 of file qjpunicode.cpp.
unicode_to_jisx0212_88
unsigned short const unicode_to_jisx0212_88[] static
Definition at line 9304 of file qjpunicode.cpp.
unicode_to_jisx0212_89
unsigned short const unicode_to_jisx0212_89[] static
Definition at line 9340 of file qjpunicode.cpp.
unicode_to_jisx0212_8a
unsigned short const unicode_to_jisx0212_8a[] static
Definition at line 9376 of file qjpunicode.cpp.
unicode_to_jisx0212_8b
unsigned short const unicode_to_jisx0212_8b[] static
Definition at line 9412 of file qjpunicode.cpp.
unicode_to_jisx0212_8c
unsigned short const unicode_to_jisx0212_8c[] static
Definition at line 9448 of file qjpunicode.cpp.
unicode_to_jisx0212_8d
unsigned short const unicode_to_jisx0212_8d[] static
Definition at line 9484 of file qjpunicode.cpp.
unicode_to_jisx0212_8e
unsigned short const unicode_to_jisx0212_8e[] static
Definition at line 9520 of file qjpunicode.cpp.
unicode_to_jisx0212_8f
unsigned short const unicode_to_jisx0212_8f[] static
Definition at line 9556 of file qjpunicode.cpp.
unicode_to_jisx0212_90
unsigned short const unicode_to_jisx0212_90[] static
Definition at line 9592 of file qjpunicode.cpp.
unicode_to_jisx0212_91
unsigned short const unicode_to_jisx0212_91[] static
Definition at line 9628 of file qjpunicode.cpp.
unicode_to_jisx0212_92
unsigned short const unicode_to_jisx0212_92[] static
Definition at line 9664 of file qjpunicode.cpp.
unicode_to_jisx0212_93
unsigned short const unicode_to_jisx0212_93[] static
Definition at line 9700 of file qjpunicode.cpp.
unicode_to_jisx0212_94
unsigned short const unicode_to_jisx0212_94[] static
Definition at line 9736 of file qjpunicode.cpp.
unicode_to_jisx0212_95
unsigned short const unicode_to_jisx0212_95[] static
Definition at line 9772 of file qjpunicode.cpp.
unicode_to_jisx0212_96
unsigned short const unicode_to_jisx0212_96[] static
Definition at line 9808 of file qjpunicode.cpp.
unicode_to_jisx0212_97
unsigned short const unicode_to_jisx0212_97[] static
Definition at line 9844 of file qjpunicode.cpp.
unicode_to_jisx0212_98
unsigned short const unicode_to_jisx0212_98[] static
Definition at line 9880 of file qjpunicode.cpp.
unicode_to_jisx0212_99
unsigned short const unicode_to_jisx0212_99[] static
Definition at line 9916 of file qjpunicode.cpp.
unicode_to_jisx0212_9a
unsigned short const unicode_to_jisx0212_9a[] static
Definition at line 9952 of file qjpunicode.cpp.
unicode_to_jisx0212_9b
unsigned short const unicode_to_jisx0212_9b[] static
Definition at line 9988 of file qjpunicode.cpp.
unicode_to_jisx0212_9c
unsigned short const unicode_to_jisx0212_9c[] static
Definition at line 10024 of file qjpunicode.cpp.
unicode_to_jisx0212_9d
unsigned short const unicode_to_jisx0212_9d[] static
Definition at line 10060 of file qjpunicode.cpp.
unicode_to_jisx0212_9e
unsigned short const unicode_to_jisx0212_9e[] static
Definition at line 10096 of file qjpunicode.cpp.
unicode_to_jisx0212_9f
unsigned short const unicode_to_jisx0212_9f[] static
Definition at line 10132 of file qjpunicode.cpp.
unicode_to_jisx0212_f9
unsigned short const unicode_to_jisx0212_f9[] static
Definition at line 10168 of file qjpunicode.cpp.
unicode_to_jisx0212_fa
unsigned short const unicode_to_jisx0212_fa[] static
Definition at line 10204 of file qjpunicode.cpp.
unicode_to_jisx0212_ff
unsigned short const unicode_to_jisx0212_ff[] static
Definition at line 10240 of file qjpunicode.cpp.
unicode_to_jisx0212_map
unsigned short const* const unicode_to_jisx0212_map[0x100] static
Definition at line 10276 of file qjpunicode.cpp.
Referenced by unicode11ToJisx0212().