Qt 4.8: /src/declarative/debugger/qjsdebuggeragent.cpp File Reference
qjsdebuggeragent.cpp File Reference
#include "private/qjsdebuggeragent_p.h"
#include "private/qdeclarativedebughelper_p.h"
#include "private/qjsdebugservice_p.h"
#include <QtCore/qdatetime.h>
#include <QtCore/qcoreapplication.h>
#include <QtCore/qset.h>
#include <QtCore/qurl.h>
#include <QtScript/qscriptcontextinfo.h>
#include <QtScript/qscriptengine.h>
#include <QtScript/qscriptvalueiterator.h>
Classes
class QJSDebuggerAgentPrivate
Functions
static QList< JSAgentWatchData > expandObject (const QScriptValue &object)
static QString fileName (const QString &fileUrl)
static JSAgentWatchData fromScriptValue (const QString &expression, const QScriptValue &value)
Function Documentation
expandObject()
static QList<JSAgentWatchData> expandObject (const QScriptValue & object) static
Definition at line 172 of file qjsdebuggeragent.cpp.
Referenced by QJSDebuggerAgent::expandObjectById(), and QJSDebuggerAgentPrivate::getLocals().
 {
     QList<JSAgentWatchData> result;
     QScriptValueIterator it(object);
     while (it.hasNext()) {
         it.next();
         if (it.flags() & QScriptValue::SkipInEnumeration)
             continue;
         if (/*object.isQObject() &&*/ it.value().isFunction()) {
             // Cosmetics: skip all functions and slot, there are too many of them,
             // and it is not useful information in the debugger.
             continue;
         }
         JSAgentWatchData data = fromScriptValue(it.name(), it.value());
         result.append(data);
     }
     if (result.isEmpty()) {
         JSAgentWatchData data;
         data.name = "<no initialized data>";
         data.hasChildren = false;
         data.value = " ";
         data.objectId = 0;
         result.append(data);
     }
     return result;
 }
fileName()
static QString fileName (const QString & fileUrl) static
Definition at line 199 of file qjsdebuggeragent.cpp.
Referenced by QFileDialogPrivate::_q_deleteCurrent(), QPrintPreviewDialogPrivate::_q_print(), QFileDialogPrivate::_q_updateOkButton(), QFileDialogPrivate::_q_useNameFilter(), QDir::absoluteFilePath(), QFontDatabasePrivate::addAppFont(), QSvgIconEngine::addFile(), QPixmapIconEngine::addFile(), QDirIteratorPrivate::checkAndPushDirectory(), QGLShader::compileSourceFile(), QScriptDebuggerStackModel::data(), QScriptDebuggerScriptsModel::data(), QFile::decodeName(), QScriptDebuggerBackend::doPendingEvaluate(), QDragManager::drag(), QPdfEnginePrivate::embedFont(), QResourcePrivate::ensureInitialized(), QScriptDebuggerAgent::enterRunToLocationMode(), QScriptDebuggerBackend::evaluate(), QDeclarativeExpressionPrivate::exceptionToError(), QScriptDebuggerCommandExecutor::execute(), QNetworkDiskCache::expire(), fbname(), QNetworkDiskCache::fileMetaData(), QDir::filePath(), QFileSystemEngine::fillMetaData(), QTextBrowserPrivate::findFile(), QFontEngineQPF::fontFile(), QAxServerBase::GetClassID(), QPixmap::handle(), QScriptCompleteScriptsJob::handleResponse(), QFileSystemModelPrivate::index(), QMoviePrivate::infoForFrame(), QImageReaderPrivate::initHandler(), QFontDatabasePrivate::isApplicationFont(), QUrl::isParentOf(), QSystemLibrary::load(), QTextBrowser::loadResource(), QScriptDebuggerConsolePrivate::loadScriptedCommands(), QFSFileEnginePrivate::longFileName(), QFileSystemEngine::nativeAbsoluteFilePath(), QNetworkAccessFileBackend::open(), QFileInfo::operator!=(), QRawFont::operator!=(), QDir::operator!=(), QProcessPrivate::Channel::operator=(), operator>>(), QScriptDebuggerScriptedConsoleCommand::parse(), QDeclarativeScriptParser::parse(), QPlatformFontDatabase::populateFontDatabase(), QJSDebuggerAgentPrivate::positionChange(), QDeclarativeWorkerScriptEnginePrivate::processLoad(), qmlFilesInDirectory(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), QPictureIO::QPictureIO(), qt_win_get_save_file_name(), qt_x11ft_convert_pattern(), QUrlInfo::QUrlInfo(), QDeclarativeDebugTrace::rangeLocationImpl(), QPixmapIconEngine::read(), QTestLog::redirectOutput(), QNetworkDiskCachePrivate::removeFile(), QScriptBreakpointsModel::resolveBreakpoint(), QScriptDebuggerScriptsModel::resolveScript(), QScriptDebuggerAgent::resolveScript(), QImage::scaled(), scriptDataFromScriptValue(), QScriptDebuggerAgent::scriptUnload(), QFileDialogPrivate::selectFile_sys(), QScriptDebuggerAgent::setBreakpoint(), QJSDebuggerAgent::setBreakpoints(), QScriptNewBreakpointWidget::setCompleter(), QPictureIO::setFileName(), QDeclarativeGraphics_DerivedObject::setParent_noEvent(), QProcess::setStandardErrorFile(), QProcess::setStandardInputFile(), QProcess::setStandardOutputFile(), QUrlModel::setUrl(), QWidgetPrivate::setWindowFilePath_helper(), QNetworkDiskCachePrivate::storeItem(), QUrl::swap(), QFile::symLinkTarget(), QDir::temp(), JSAgentCoverageData::toByteArray(), QScriptContext::toString(), QFactoryLoader::updateDir(), QFileInfoGatherer::updateFile(), write_xbm_image(), QOutputStrategy::~QOutputStrategy(), and QScriptMessageHandlerInterface::~QScriptMessageHandlerInterface().
 {
     int lastDelimiterPos = fileUrl.lastIndexOf(QLatin1Char('/'));
     return fileUrl.mid(lastDelimiterPos, fileUrl.size() - lastDelimiterPos);
 }
fromScriptValue()
static JSAgentWatchData fromScriptValue (const QString & expression, const QScriptValue & value) static
Definition at line 115 of file qjsdebuggeragent.cpp.
Referenced by QDeclarativeObjectMethodScriptClass::callMethod(), QJSDebuggerAgent::executeExpression(), expandObject(), QJSDebuggerAgentPrivate::getLocals(), QDeclarativeObjectMethodScriptClass::property(), qScriptRegisterMetaType(), and QJSDebuggerAgent::watches().
 {
     static const QString arrayStr = QCoreApplication::translate
             ("Debugger::JSAgentWatchData", "[Array of length %1]");
     static const QString undefinedStr = QCoreApplication::translate
             ("Debugger::JSAgentWatchData", "<undefined>");
     JSAgentWatchData data;
     data.exp = expression.toUtf8();
     data.name = data.exp;
     data.hasChildren = false;
     data.value = value.toString().toUtf8();
     data.objectId = value.objectId();
     if (value.isArray()) {
         data.type = "Array";
         data.value = arrayStr.arg(value.property(QLatin1String("length")).toString()).toUtf8();
         data.hasChildren = true;
     } else if (value.isBool()) {
         data.type = "Bool";
         // data.value = value.toBool() ? "true" : "false";
     } else if (value.isDate()) {
         data.type = "Date";
         data.value = value.toDateTime().toString().toUtf8();
     } else if (value.isError()) {
         data.type = "Error";
     } else if (value.isFunction()) {
         data.type = "Function";
     } else if (value.isUndefined()) {
         data.type = undefinedStr.toUtf8();
     } else if (value.isNumber()) {
         data.type = "Number";
     } else if (value.isRegExp()) {
         data.type = "RegExp";
     } else if (value.isString()) {
         data.type = "String";
     } else if (value.isVariant()) {
         data.type = "Variant";
     } else if (value.isQObject()) {
         const QObject *obj = value.toQObject();
         data.type = "Object";
         data.value += '[';
         data.value += obj->metaObject()->className();
         data.value += ']';
         data.hasChildren = true;
     } else if (value.isObject()) {
         data.type = "Object";
         data.hasChildren = true;
         data.value = "[Object]";
     } else if (value.isNull()) {
         data.type = "<null>";
     } else {
         data.type = "<unknown>";
     }
     return data;
 }