Qt 4.8: /src/gui/kernel/qkeymapper_p.h File Reference
qkeymapper_p.h File Reference
#include <qobject.h>
#include <private/qobject_p.h>
#include <qkeysequence.h>
#include <qlist.h>
#include <qlocale.h>
#include <qevent.h>
#include <qhash.h>
Classes
class QKeyMapper
class QKeyMapperPrivate
Typedefs
typedef struct tagMSG MSG
typedef struct __TISInputSource * TISInputSourceRef
Enumerations
enum WindowsNativeModifiers {
ShiftLeft = 0x00000001, ControlLeft = 0x00000002, AltLeft = 0x00000004, MetaLeft = 0x00000008,
ShiftRight = 0x00000010, ControlRight = 0x00000020, AltRight = 0x00000040, MetaRight = 0x00000080,
CapsLock = 0x00000100, NumLock = 0x00000200, ScrollLock = 0x00000400, ExtendedKey = 0x01000000,
ShiftAny = 0x00000011, ControlAny = 0x00000022, AltAny = 0x00000044, MetaAny = 0x00000088,
LockAny = 0x00000700
}
Functions
QKeyMapperPrivate * qt_keymapper_private ()
Typedef Documentation
MSG
typedef struct tagMSG MSG
Definition at line 117 of file qkeymapper_p.h.
TISInputSourceRef
typedef struct __TISInputSource* TISInputSourceRef
Definition at line 143 of file qkeymapper_p.h.
Enumeration Type Documentation
WindowsNativeModifiers
enum WindowsNativeModifiers
Enumerator
ShiftLeft
ControlLeft
AltLeft
MetaLeft
ShiftRight
ControlRight
AltRight
MetaRight
CapsLock
NumLock
ScrollLock
ExtendedKey
ShiftAny
ControlAny
AltAny
MetaAny
LockAny
Definition at line 95 of file qkeymapper_p.h.
{
     ShiftLeft            = 0x00000001,
     ControlLeft          = 0x00000002,
     AltLeft              = 0x00000004,
     MetaLeft             = 0x00000008,
     ShiftRight           = 0x00000010,
     ControlRight         = 0x00000020,
     AltRight             = 0x00000040,
     MetaRight            = 0x00000080,
     CapsLock             = 0x00000100,
     NumLock              = 0x00000200,
     ScrollLock           = 0x00000400,
     ExtendedKey          = 0x01000000,
     // Convenience mappings
     ShiftAny             = 0x00000011,
     ControlAny           = 0x00000022,
     AltAny               = 0x00000044,
     MetaAny              = 0x00000088,
     LockAny              = 0x00000700
 };
Function Documentation
qt_keymapper_private()
QKeyMapperPrivate* qt_keymapper_private ()
Definition at line 113 of file qkeymapper.cpp.
Referenced by QMacInputContext::globalEventProcessor(), QApplicationPrivate::globalEventProcessor(), QApplication::keyboardInputDirection(), QApplication::keyboardInputLocale(), qt_dispatchKeyEvent(), QtWndProc(), and QApplication::x11ProcessEvent().
 {
     return QKeyMapper::instance()->d_func();
 }