Qt 4.8: /src/gui/kernel/qkeymapper.cpp File Reference
qkeymapper.cpp File Reference
#include "qapplication.h"
#include <private/qobject_p.h>
#include "qkeymapper_p.h"
#include <qwidget.h>
Functions
QKeyMapperPrivate * qt_keymapper_private ()
bool qt_sendSpontaneousEvent (QObject *receiver, QEvent *event)
Function Documentation
qt_keymapper_private()
QKeyMapperPrivate* qt_keymapper_private ()
Definition at line 113 of file qkeymapper.cpp.
Referenced by QMacInputContext::globalEventProcessor(), QApplicationPrivate::globalEventProcessor(), QApplication::keyboardInputDirection(), QApplication::keyboardInputLocale(), qt_dispatchKeyEvent(), QtWndProc(), and QApplication::x11ProcessEvent().
 {
     return QKeyMapper::instance()->d_func();
 }
qt_sendSpontaneousEvent()
bool qt_sendSpontaneousEvent (QObject * receiver, QEvent * event)
Definition at line 5779 of file qapplication.cpp.
Referenced by QKeyMapper::changeKeyboard(), and QKeyMapper::possibleKeys().
 {
     return QCoreApplication::sendSpontaneousEvent(receiver, event);
 }