Qt 4.8: /src/gui/kernel/qlayoutitem.cpp File Reference
qlayoutitem.cpp File Reference
#include "qlayout.h"
#include "qapplication.h"
#include "qlayoutengine_p.h"
#include "qmenubar.h"
#include "qtoolbar.h"
#include "qevent.h"
#include "qstyle.h"
#include "qvariant.h"
#include "qwidget_p.h"
Functions
static QRect fromLayoutItemRect (QWidgetPrivate *priv, const QRect &rect)
static QSize fromLayoutItemSize (QWidgetPrivate *priv, const QSize &size)
static QRect toLayoutItemRect (QWidgetPrivate *priv, const QRect &rect)
static QSize toLayoutItemSize (QWidgetPrivate *priv, const QSize &size)
Function Documentation
fromLayoutItemRect()
static QRect fromLayoutItemRect (QWidgetPrivate * priv, const QRect & rect) inline static
Definition at line 55 of file qlayoutitem.cpp.
Referenced by fromLayoutItemSize(), and QWidgetItem::setGeometry().
 {
     return rect.adjusted(priv->leftLayoutItemMargin, priv->topLayoutItemMargin,
                          -priv->rightLayoutItemMargin, -priv->bottomLayoutItemMargin);
 }
fromLayoutItemSize()
static QSize fromLayoutItemSize (QWidgetPrivate * priv, const QSize & size) inline static
Definition at line 61 of file qlayoutitem.cpp.
Referenced by QWidgetItem::heightForWidth().
 {
     return fromLayoutItemRect(priv, QRect(QPoint(0, 0), size)).size();
 }
toLayoutItemRect()
static QRect toLayoutItemRect (QWidgetPrivate * priv, const QRect & rect) inline static
Definition at line 66 of file qlayoutitem.cpp.
Referenced by QWidgetItem::geometry(), and toLayoutItemSize().
 {
     return rect.adjusted(-priv->leftLayoutItemMargin, -priv->topLayoutItemMargin,
                          priv->rightLayoutItemMargin, priv->bottomLayoutItemMargin);
 }
toLayoutItemSize()
static QSize toLayoutItemSize (QWidgetPrivate * priv, const QSize & size) inline static
Definition at line 72 of file qlayoutitem.cpp.
Referenced by QWidgetItem::heightForWidth(), QWidgetItem::maximumSize(), QWidgetItem::minimumSize(), QWidgetItem::sizeHint(), and QWidgetItemV2::updateCacheIfNecessary().
 {
     return toLayoutItemRect(priv, QRect(QPoint(0, 0), size)).size();
 }