Qt 4.8: /src/gui/kernel/qlayout.cpp File Reference
qlayout.cpp File Reference
#include "qlayout.h"
#include "qapplication.h"
#include "qlayoutengine_p.h"
#include "qmenubar.h"
#include "qtoolbar.h"
#include "qsizegrip.h"
#include "qevent.h"
#include "qstyle.h"
#include "qvariant.h"
#include "qwidget_p.h"
#include "qlayout_p.h"
#include "qformlayout.h"
Functions
static bool layoutDebug ()
static int menuBarHeightForWidth (QWidget *menubar, int w)
static bool removeWidgetRecursively (QLayoutItem *li, QWidget *w)
Function Documentation
layoutDebug()
static bool layoutDebug () static
Definition at line 995 of file qlayout.cpp.
Referenced by QLayout::addChildWidget(), and QLayoutPrivate::reparentChildWidgets().
 {
     static int checked_env = -1;
     if(checked_env == -1)
         checked_env = !!qgetenv("QT_LAYOUT_DEBUG").toInt();
     return checked_env;
 }
menuBarHeightForWidth()
static int menuBarHeightForWidth (QWidget * menubar, int w) static
Definition at line 58 of file qlayout.cpp.
Referenced by QLayoutPrivate::doResize(), QLayout::totalHeightForWidth(), QLayout::totalMaximumSize(), QLayout::totalMinimumSize(), and QLayout::totalSizeHint().
 {
     if (menubar && !menubar->isHidden() && !menubar->isWindow()) {
         int result = menubar->heightForWidth(qMax(w, menubar->minimumWidth()));
         if (result == -1)
             result = menubar->sizeHint().height();
         const int min = qSmartMinSize(menubar).height();
         result = qBound(min, result, menubar->maximumSize().height());
         if (result != -1)
             return result;
     }
     return 0;
 }
removeWidgetRecursively()
static bool removeWidgetRecursively (QLayoutItem * li, QWidget * w) static
Definition at line 680 of file qlayout.cpp.
Referenced by QLayout::addChildWidget(), and QLayout::widgetEvent().
 {
     QLayout *lay = li->layout();
     if (!lay)
         return false;
     int i = 0;
     QLayoutItem *child;
     while ((child = lay->itemAt(i))) {
         if (child->widget() == w) {
             delete lay->takeAt(i);
             lay->invalidate();
             return true;
         } else if (removeWidgetRecursively(child, w)) {
             return true;
         } else {
             ++i;
         }
     }
     return false;
 }