Qt 4.8: /src/gui/widgets/qlcdnumber.cpp File Reference
qlcdnumber.cpp File Reference
#include "qlcdnumber.h"
#include "qbitarray.h"
#include "qpainter.h"
#include "private/qframe_p.h"
Classes
class QLCDNumberPrivate
Macros
#define DARK
#define DARK p.setPen(darkColor)
#define LIGHT
#define LIGHT p.setPen(lightColor)
#define LINETO(X, Y) addPoint(a, QPoint(pt.x() + (X),pt.y() + (Y)))
#define LINETO(X, Y)
Functions
static void addPoint (QPolygon &a, const QPoint &p)
static QString double2string (double num, int base, int ndigits, bool *oflow)
static const char * getSegments (char ch)
static QString int2string (int num, int base, int ndigits, bool *oflow)
Macro Definition Documentation
DARK [1/2]
#define DARK
Referenced by QLCDNumberPrivate::drawSegment().
DARK [2/2]
#define DARK p.setPen(darkColor)
LIGHT [1/2]
#define LIGHT
Referenced by QLCDNumberPrivate::drawSegment().
LIGHT [2/2]
#define LIGHT p.setPen(lightColor)
LINETO [1/2]
#define LINETO (X, Y) addPoint(a, QPoint(pt.x() + (X),pt.y() + (Y)))
Referenced by QLCDNumberPrivate::drawSegment().
LINETO [2/2]
#define LINETO (X, Y)
Value:
p.drawLine(ppt.x(), ppt.y(), pt.x()+(X), pt.y()+(Y)); \
                    ppt = QPoint(pt.x()+(X), pt.y()+(Y))
Function Documentation
addPoint()
static void addPoint (QPolygon & a, const QPoint & p) static
Definition at line 989 of file qlcdnumber.cpp.
 {
     uint n = a.size();
     a.resize(n + 1);
     a.setPoint(n, p);
 }
double2string()
static QString double2string (double num, int base, int ndigits, bool * oflow) static
Definition at line 235 of file qlcdnumber.cpp.
Referenced by QLCDNumber::checkOverflow(), and QLCDNumber::display().
 {
     QString s;
     if (base != QLCDNumber::Dec) {
         bool of = num >= 2147483648.0 || num < -2147483648.0;
         if (of) {                             // oops, integer overflow
             if (oflow)
                 *oflow = true;
             return s;
         }
         s = int2string((int)num, base, ndigits, 0);
     } else {                                    // decimal base
         int nd = ndigits;
         do {
             s.sprintf("%*.*g", ndigits, nd, num);
             int i = s.indexOf(QLatin1Char('e'));
             if (i > 0 && s[i+1]==QLatin1Char('+')) {
                 s[i] = QLatin1Char(' ');
                 s[i+1] = QLatin1Char('e');
             }
         } while (nd-- && (int)s.length() > ndigits);
     }
     if (oflow)
         *oflow = (int)s.length() > ndigits;
     return s;
 }
getSegments()
static const char* getSegments (char ch) static
Definition at line 263 of file qlcdnumber.cpp.
Referenced by QLCDNumberPrivate::drawDigit().
 {
     static const char segments[30][8] =
        { { 0, 1, 2, 4, 5, 6,99, 0},             // 0    0 / O
          { 2, 5,99, 0, 0, 0, 0, 0},             // 1    1
          { 0, 2, 3, 4, 6,99, 0, 0},             // 2    2
          { 0, 2, 3, 5, 6,99, 0, 0},             // 3    3
          { 1, 2, 3, 5,99, 0, 0, 0},             // 4    4
          { 0, 1, 3, 5, 6,99, 0, 0},             // 5    5 / S
          { 0, 1, 3, 4, 5, 6,99, 0},             // 6    6
          { 0, 2, 5,99, 0, 0, 0, 0},             // 7    7
          { 0, 1, 2, 3, 4, 5, 6,99},             // 8    8
          { 0, 1, 2, 3, 5, 6,99, 0},             // 9    9 / g
          { 3,99, 0, 0, 0, 0, 0, 0},             // 10   -
          { 7,99, 0, 0, 0, 0, 0, 0},             // 11   .
          { 0, 1, 2, 3, 4, 5,99, 0},             // 12   A
          { 1, 3, 4, 5, 6,99, 0, 0},             // 13   B
          { 0, 1, 4, 6,99, 0, 0, 0},             // 14   C
          { 2, 3, 4, 5, 6,99, 0, 0},             // 15   D
          { 0, 1, 3, 4, 6,99, 0, 0},             // 16   E
          { 0, 1, 3, 4,99, 0, 0, 0},             // 17   F
          { 1, 3, 4, 5,99, 0, 0, 0},             // 18   h
          { 1, 2, 3, 4, 5,99, 0, 0},             // 19   H
          { 1, 4, 6,99, 0, 0, 0, 0},             // 20   L
          { 3, 4, 5, 6,99, 0, 0, 0},             // 21   o
          { 0, 1, 2, 3, 4,99, 0, 0},             // 22   P
          { 3, 4,99, 0, 0, 0, 0, 0},             // 23   r
          { 4, 5, 6,99, 0, 0, 0, 0},             // 24   u
          { 1, 2, 4, 5, 6,99, 0, 0},             // 25   U
          { 1, 2, 3, 5, 6,99, 0, 0},             // 26   Y
          { 8, 9,99, 0, 0, 0, 0, 0},             // 27   :
          { 0, 1, 2, 3,99, 0, 0, 0},             // 28   '
          {99, 0, 0, 0, 0, 0, 0, 0} };           // 29   empty
     if (ch >= '0' && ch <= '9')
         return segments[ch - '0'];
     if (ch >= 'A' && ch <= 'F')
         return segments[ch - 'A' + 12];
     if (ch >= 'a' && ch <= 'f')
         return segments[ch - 'a' + 12];
     int n;
     switch (ch) {
         case '-':
             n = 10;  break;
         case 'O':
             n = 0;   break;
         case 'g':
             n = 9;   break;
         case '.':
             n = 11;  break;
         case 'h':
             n = 18;  break;
         case 'H':
             n = 19;  break;
         case 'l':
         case 'L':
             n = 20;  break;
         case 'o':
             n = 21;  break;
         case 'p':
         case 'P':
             n = 22;  break;
         case 'r':
         case 'R':
             n = 23;  break;
         case 's':
         case 'S':
             n = 5;   break;
         case 'u':
             n = 24;  break;
         case 'U':
             n = 25;  break;
         case 'y':
         case 'Y':
             n = 26;  break;
         case ':':
             n = 27;  break;
         case '\'':
             n = 28;  break;
         default:
             n = 29;  break;
     }
     return segments[n];
 }
int2string()
static QString int2string (int num, int base, int ndigits, bool * oflow) static
Definition at line 178 of file qlcdnumber.cpp.
Referenced by QLCDNumber::checkOverflow(), QLCDNumber::display(), and double2string().
 {
     QString s;
     bool negative;
     if (num < 0) {
         negative = true;
         num      = -num;
     } else {
         negative = false;
     }
     switch(base) {
         case QLCDNumber::Hex:
             s.sprintf("%*x", ndigits, num);
             break;
         case QLCDNumber::Dec:
             s.sprintf("%*i", ndigits, num);
             break;
         case QLCDNumber::Oct:
             s.sprintf("%*o", ndigits, num);
             break;
         case QLCDNumber::Bin:
             {
                 char buf[42];
                 char *p = &buf[41];
                 uint n = num;
                 int len = 0;
                 *p = '\0';
                 do {
                     *--p = (char)((n&1)+'0');
                     n >>= 1;
                     len++;
                 } while (n != 0);
                 len = ndigits - len;
                 if (len > 0)
                 s.fill(QLatin1Char(' '), len);
                 s += QString::fromLatin1(p);
             }
             break;
     }
     if (negative) {
         for (int i=0; i<(int)s.length(); i++) {
             if (s[i] != QLatin1Char(' ')) {
                 if (i != 0) {
                     s[i-1] = QLatin1Char('-');
                 } else {
                     s.insert(0, QLatin1Char('-'));
                 }
                 break;
             }
         }
     }
     if (oflow)
         *oflow = (int)s.length() > ndigits;
     return s;
 }