Qt 4.8: /src/corelib/plugin/qlibrary_win.cpp File Reference
qlibrary_win.cpp File Reference
#include "qplatformdefs.h"
#include "qlibrary_p.h"
#include "qfile.h"
#include "qdir.h"
#include "qfileinfo.h"
#include <private/qfilesystementry_p.h>
#include "qt_windows.h"
Functions
QString qt_error_string (int code)
Function Documentation
qt_error_string()
QString qt_error_string (int code)
Definition at line 2600 of file qglobal.cpp.
Referenced by QLocalServerPrivate::addListener(), QFSFileEnginePrivate::closeFdFh(), QProcessPrivate::execChild(), QFSFileEnginePrivate::flushFh(), QFSFileEnginePrivate::longFileName(), QFSFileEnginePrivate::map(), QFSFileEnginePrivate::nativeOpen(), QFSFileEnginePrivate::nativeRead(), QFSFileEnginePrivate::openFd(), QFSFileEnginePrivate::openFh(), QProcessPrivate::processStarted(), qErrnoWarning(), qt_create_commandline(), qt_create_pipe(), qt_message(), qt_parse_pattern(), QNativeSocketEngine::read(), QFSFileEnginePrivate::readFdFh(), QFSFileEnginePrivate::readLineFdFh(), report_error(), QFSFileEnginePrivate::seekFdFh(), QFilePrivate::setError(), QFSFileEngine::setSize(), QThread::start(), QProcessPrivate::startProcess(), QThread::terminate(), QFSFileEnginePrivate::unmap(), QFSFileEnginePrivate::writeFdFh(), and QProcessPrivate::writeToStdin().
 {
     const char *s = 0;
     QString ret;
     if (errorCode == -1) {
 #if defined(Q_OS_WIN)
         errorCode = GetLastError();
 #else
         errorCode = errno;
 #endif
     }
     switch (errorCode) {
     case 0:
         break;
     case EACCES:
         s = QT_TRANSLATE_NOOP("QIODevice", "Permission denied");
         break;
     case EMFILE:
         s = QT_TRANSLATE_NOOP("QIODevice", "Too many open files");
         break;
     case ENOENT:
         s = QT_TRANSLATE_NOOP("QIODevice", "No such file or directory");
         break;
     case ENOSPC:
         s = QT_TRANSLATE_NOOP("QIODevice", "No space left on device");
         break;
     default: {
 #ifdef Q_OS_WIN
         wchar_t *string = 0;
         FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER|FORMAT_MESSAGE_FROM_SYSTEM,
                       NULL,
                       errorCode,
                       MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
                       (LPWSTR)&string,
                       0,
                       NULL);
         ret = QString::fromWCharArray(string);
         LocalFree((HLOCAL)string);
         if (ret.isEmpty() && errorCode == ERROR_MOD_NOT_FOUND)
             ret = QString::fromLatin1("The specified module could not be found.");
 #elif !defined(QT_NO_THREAD) && defined(_POSIX_THREAD_SAFE_FUNCTIONS) && _POSIX_VERSION >= 200112L && !defined(Q_OS_INTEGRITY) && !defined(Q_OS_QNX)
         QByteArray buf(1024, '\0');
         ret = fromstrerror_helper(strerror_r(errorCode, buf.data(), buf.size()), buf);
 #else
         ret = QString::fromLocal8Bit(strerror(errorCode));
 #endif
     break; }
     }
     if (s)
         // ######## this breaks moc build currently
 //         ret = QCoreApplication::translate("QIODevice", s);
         ret = QString::fromLatin1(s);
     return ret.trimmed();
 }