Qt 4.8: /src/corelib/plugin/qlibrary_p.h File Reference
qlibrary_p.h File Reference
#include "QtCore/qt_windows.h"
#include "QtCore/qlibrary.h"
#include "QtCore/qpointer.h"
#include "QtCore/qstringlist.h"
#include "QtCore/qplugin.h"
#include "QtCore/qsharedpointer.h"
Classes
class QLibraryPrivate
Functions
bool qt_debug_component ()
Function Documentation
qt_debug_component()
bool qt_debug_component ()
Definition at line 1319 of file qlibrary.cpp.
Referenced by QLibraryPrivate::isPlugin(), QLibraryPrivate::loadPlugin(), qt_parse_pattern(), QPluginLoader::setFileName(), QLibraryPrivate::unload(), QFactoryLoader::update(), and QFactoryLoader::updateDir().
 {
     static int debug_env = -1;
     if (debug_env == -1)
        debug_env = QT_PREPEND_NAMESPACE(qgetenv)("QT_DEBUG_PLUGINS").toInt();
     return debug_env != 0;
 }