Qt 4.8: /src/corelib/plugin/qlibrary_unix.cpp File Reference
qlibrary_unix.cpp File Reference
#include "qplatformdefs.h"
#include <qfile.h>
#include "qlibrary_p.h"
#include <qcoreapplication.h>
#include <private/qfilesystementry_p.h>
#include <private/qcore_mac_p.h>
#include <dlfcn.h>
Functions
static QString qdlerror ()
Q_CORE_EXPORT void * qt_mac_resolve_sys (void *handle, const char *symbol)
Function Documentation
qdlerror()
static QString qdlerror () static
Definition at line 71 of file qlibrary_unix.cpp.
Referenced by QLibraryPrivate::load_sys(), QLibraryPrivate::resolve_sys(), and QLibraryPrivate::unload_sys().
 {
 #if defined(QT_NO_DYNAMIC_LIBRARY)
     const char *err = "This platform does not support dynamic libraries.";
 #elif !defined(QT_HPUX_LD)
     const char *err = dlerror();
 #else
     const char *err = strerror(errno);
 #endif
     return err ? QLatin1Char('(') + QString::fromLocal8Bit(err) + QLatin1Char(')'): QString();
 }
qt_mac_resolve_sys()
Q_CORE_EXPORT void* qt_mac_resolve_sys (void * handle, const char * symbol)
Definition at line 287 of file qlibrary_unix.cpp.
 {
     return dlsym(handle, symbol);
 }