Qt 4.8: /src/corelib/plugin/qlibrary.cpp File Reference
qlibrary.cpp File Reference
#include "qplatformdefs.h"
#include "qlibrary.h"
#include "qlibrary_p.h"
#include <qstringlist.h>
#include <qfile.h>
#include <qfileinfo.h>
#include <qmutex.h>
#include <qmap.h>
#include <qsettings.h>
#include <qdatetime.h>
#include <private/qcoreapplication_p.h>
#include <private/qcore_mac_p.h>
#include <errno.h>
#include <qdebug.h>
#include <qvector.h>
#include <qdir.h>
#include "qelfparser_p.h"
Classes
struct LibraryData
struct qt_token_info
Macros
#define QLIBRARY_AS_DEBUG true
Typedefs
typedef QMap< QString, QLibraryPrivate * > LibraryMap
typedef const char *(* QtPluginQueryVerificationDataFunction) ()
Functions
static LibraryMap * libraryMap ()
bool qt_debug_component ()
bool qt_get_verificationdata (QtPluginQueryVerificationDataFunction pfn, uint *qt_version, bool *debug, QByteArray *key, bool *exceptionThrown)
static bool qt_parse_pattern (const char *s, uint *version, bool *debug, QByteArray *key)
static int qt_tokenize (const char *s, ulong s_len, ulong *advance, qt_token_info &token_info)
Macro Definition Documentation
QLIBRARY_AS_DEBUG
#define QLIBRARY_AS_DEBUG true
Definition at line 72 of file qlibrary.cpp.
Referenced by QLibraryPrivate::isPlugin().
Typedef Documentation
LibraryMap
typedef QMap<QString, QLibraryPrivate*> LibraryMap
Definition at line 418 of file qlibrary.cpp.
QtPluginQueryVerificationDataFunction
typedef const char*(* QtPluginQueryVerificationDataFunction) ()
Definition at line 645 of file qlibrary.cpp.
Function Documentation
libraryMap()
static LibraryMap* libraryMap () static
Definition at line 427 of file qlibrary.cpp.
Referenced by QLibraryPrivate::findOrCreate(), QLibraryPrivate::QLibraryPrivate(), and QLibraryPrivate::~QLibraryPrivate().
 {
     LibraryData *data = libraryData();
     return data ? &data->libraryMap : 0;
 }
qt_debug_component()
bool qt_debug_component ()
Definition at line 1319 of file qlibrary.cpp.
Referenced by QLibraryPrivate::isPlugin(), QLibraryPrivate::loadPlugin(), qt_parse_pattern(), QPluginLoader::setFileName(), QLibraryPrivate::unload(), QFactoryLoader::update(), and QFactoryLoader::updateDir().
 {
     static int debug_env = -1;
     if (debug_env == -1)
        debug_env = QT_PREPEND_NAMESPACE(qgetenv)("QT_DEBUG_PLUGINS").toInt();
     return debug_env != 0;
 }
qt_get_verificationdata()
bool qt_get_verificationdata (QtPluginQueryVerificationDataFunction pfn, uint * qt_version, bool * debug, QByteArray * key, bool * exceptionThrown)
Definition at line 648 of file qlibrary.cpp.
Referenced by QLibraryPrivate::isPlugin().
 {
     *exceptionThrown = false;
     const char *szData = 0;
     if (!pfn)
         return false;
 #ifdef QT_USE_MS_STD_EXCEPTION
     szData = qt_try_versioninfo((void *)pfn, exceptionThrown);
     if (*exceptionThrown)
         return false;
 #else
     szData = pfn();
 #endif
 #ifdef QT_NO_PLUGIN_CHECK
     return true;
 #else
     return qt_parse_pattern(szData, qt_version, debug, key);
 #endif
 }
qt_parse_pattern()
static bool qt_parse_pattern (const char * s, uint * version, bool * debug, QByteArray * key) static
Definition at line 262 of file qlibrary.cpp.
Referenced by qt_get_verificationdata().
 {
     bool ret = true;
     qt_token_info pinfo("=\n", 2);
     int parse;
     ulong at = 0, advance, parselen = qstrlen(s);
     do {
         parse = qt_tokenize(s + at, parselen, &advance, pinfo);
         if (parse == -1) {
             ret = false;
             break;
         }
         at += advance;
         parselen -= advance;
         if (qstrncmp("version", pinfo.results[0], pinfo.lengths[0]) == 0) {
             // parse version string
             qt_token_info pinfo2("..-", 3);
             if (qt_tokenize(pinfo.results[1], pinfo.lengths[1],
                               &advance, pinfo2) != -1) {
                 QByteArray m(pinfo2.results[0], pinfo2.lengths[0]);
                 QByteArray n(pinfo2.results[1], pinfo2.lengths[1]);
                 QByteArray p(pinfo2.results[2], pinfo2.lengths[2]);
                 *version  = (m.toUInt() << 16) | (n.toUInt() << 8) | p.toUInt();
             } else {
                 ret = false;
                 break;
             }
         } else if (qstrncmp("debug", pinfo.results[0], pinfo.lengths[0]) == 0) {
             *debug = qstrncmp("true", pinfo.results[1], pinfo.lengths[1]) == 0;
         } else if (qstrncmp("buildkey", pinfo.results[0],
                               pinfo.lengths[0]) == 0){
             // save buildkey
             *key = QByteArray(pinfo.results[1], pinfo.lengths[1]);
         }
     } while (parse == 1 && parselen > 0);
     return ret;
 }
qt_tokenize()
static int qt_tokenize (const char * s, ulong s_len, ulong * advance, qt_token_info & token_info) static
Definition at line 204 of file qlibrary.cpp.
Referenced by qt_parse_pattern().
 {
     if (!s)
         return -1;
     ulong pos = 0, field = 0, fieldlen = 0;
     char current;
     int ret = -1;
     *advance = 0;
     for (;;) {
         current = s[pos];
         // next char
         ++pos;
         ++fieldlen;
         ++*advance;
         if (! current || pos == s_len + 1) {
             // save result
             token_info.results[(int)field] = s;
             token_info.lengths[(int)field] = fieldlen - 1;
             // end of string
             ret = 0;
             break;
         }
         if (current == token_info.fields[field]) {
             // save result
             token_info.results[(int)field] = s;
             token_info.lengths[(int)field] = fieldlen - 1;
             // end of field
             fieldlen = 0;
             ++field;
             if (field == token_info.field_count - 1) {
                 // parse ok
                 ret = 1;
             }
             if (field == token_info.field_count) {
                 // done parsing
                 break;
             }
             // reset string and its length
             s = s + pos;
             s_len -= pos;
             pos = 0;
         }
     }
     return ret;
 }