Qt 4.8: /src/corelib/tools/qline.cpp File Reference
qline.cpp File Reference
#include "qline.h"
#include "qdebug.h"
#include "qdatastream.h"
#include "qmath.h"
#include <private/qnumeric_p.h>
Functions
QDebug operator<< (QDebug d, const QLine &p)
QDebug operator<< (QDebug d, const QLineF &p)
static qreal q_deg2rad (qreal x)
static qreal q_rad2deg (qreal x)
Function Documentation
operator<<() [1/2]
QDebug operator<< (QDebug d, const QLine & p)
Definition at line 330 of file qline.cpp.
 {
     d << "QLine(" << p.p1() << ',' << p.p2() << ')';
     return d;
 }
operator<<() [2/2]
QDebug operator<< (QDebug d, const QLineF & p)
Definition at line 1006 of file qline.cpp.
 {
     d << "QLineF(" << p.p1() << ',' << p.p2() << ')';
     return d;
 }
q_deg2rad()
static qreal q_deg2rad (qreal x) inline static
Definition at line 380 of file qline.cpp.
Referenced by QLineF::fromPolar(), and QLineF::setAngle().
 {
     return x * qreal(0.01745329251994329576923690768489);    /* pi/180 */
 }
q_rad2deg()
static qreal q_rad2deg (qreal x) inline static
Definition at line 385 of file qline.cpp.
Referenced by QLineF::angle().
 {
     return x * qreal(57.295779513082320876798154814105);    /* 180/pi */
 }