Qt 4.8: /src/gui/widgets/qlineedit.cpp File Reference
qlineedit.cpp File Reference
#include "qlineedit.h"
#include "qlineedit_p.h"
#include "qaction.h"
#include "qapplication.h"
#include "qclipboard.h"
#include "qdrag.h"
#include "qdrawutil.h"
#include "qevent.h"
#include "qfontmetrics.h"
#include "qmenu.h"
#include "qpainter.h"
#include "qpixmap.h"
#include "qpointer.h"
#include "qstringlist.h"
#include "qstyle.h"
#include "qstyleoption.h"
#include "qtimer.h"
#include "qvalidator.h"
#include "qvariant.h"
#include "qvector.h"
#include "qwhatsthis.h"
#include "qdebug.h"
#include "qtextedit.h"
#include <private/qtextedit_p.h>
#include "qaccessible.h"
#include "qinputcontext.h"
#include "qlist.h"
#include "qabstractitemview.h"
#include "private/qstylesheetstyle_p.h"
#include "private/qapplication_p.h"
#include "private/qshortcutmap_p.h"
#include "qkeysequence.h"
#include <limits.h>
#include "moc_qlineedit.cpp"
Macros
#define ACCEL_KEY(k) (!qApp->d_func()->shortcutMap.hasShortcutForKeySequence(k) ? QLatin1Char('\t') + QString(QKeySequence(k)) : QString())
Functions
void qt_mac_secure_keyboard (bool)
Variables
bool qt_use_rtl_extensions
Macro Definition Documentation
ACCEL_KEY
#define ACCEL_KEY (k) (!qApp->d_func()->shortcutMap.hasShortcutForKeySequence(k) ? QLatin1Char('\t') + QString(QKeySequence(k)) : QString())
Definition at line 82 of file qlineedit.cpp.
Referenced by QLineEdit::createStandardContextMenu().
Function Documentation
qt_mac_secure_keyboard()
void qt_mac_secure_keyboard (bool)
Definition at line 70 of file qkeymapper_mac.cpp.
Referenced by QLineEdit::focusInEvent(), QLineEdit::focusOutEvent(), and QLineEdit::setEchoMode().
 {
     static bool secure = false;
     if (b != secure){
         b ? EnableSecureEventInput() : DisableSecureEventInput();
         secure = b;
     }
 }
Variable Documentation
qt_use_rtl_extensions
bool qt_use_rtl_extensions
Definition at line 266 of file qapplication_win.cpp.
Referenced by QLineEdit::contextMenuEvent(), QLineEdit::createStandardContextMenu(), and QApplicationPrivate::x11_apply_settings().