Qt 4.8: /src/corelib/tools/qlist.cpp File Reference
qlist.cpp File Reference
#include <new>
#include "qlist.h"
#include "qtools_p.h"
#include <string.h>
Functions
static int grow (int size)
Function Documentation
grow()
static int grow (int size) static
Definition at line 62 of file qlist.cpp.
Referenced by QListData::append(), QGlyphLayout::data(), QListData::detach_grow(), QListData::insert(), QString::operator+=(), QListData::prepend(), and QGLEllipseMaskGenerator::screenRect().
 {
     // dear compiler: don't optimize me out.
     volatile int x = qAllocMore(size * sizeof(void *), QListData::DataHeaderSize) / sizeof(void *);
     return x;
 }