Qt 4.8: /src/corelib/tools/qlocale_p.h File Reference
qlocale_p.h File Reference
#include "QtCore/qstring.h"
#include "QtCore/qvarlengtharray.h"
#include "QtCore/qmetatype.h"
#include "qlocale.h"
Classes
struct QLocalePrivate
Functions
QString qt_readEscapedFormatString (const QString &format, int *idx)
int qt_repeatCount (const QString &s, int i)
bool qt_splitLocaleName (const QString &name, QString &lang, QString &script, QString &cntry)
Function Documentation
qt_readEscapedFormatString()
QString qt_readEscapedFormatString (const QString & format, int * idx)
Definition at line 387 of file qlocale.cpp.
Referenced by QLocalePrivate::dateTimeToString(), QLocalePrivate::digitToCLocale(), macToQtFormat(), timeFormatContainsAP(), and QSystemLocalePrivate::winToQtFormat().
 {
     int &i = *idx;
     Q_ASSERT(format.at(i) == QLatin1Char('\''));
     ++i;
     if (i == format.size())
         return QString();
     if (format.at(i).unicode() == '\'') { // "''" outside of a quoted stirng
         ++i;
         return QLatin1String("'");
     }
     QString result;
     while (i < format.size()) {
         if (format.at(i).unicode() == '\'') {
             if (i + 1 < format.size() && format.at(i + 1).unicode() == '\'') {
                 // "''" inside of a quoted string
                 result.append(QLatin1Char('\''));
                 i += 2;
             } else {
                 break;
             }
         } else {
             result.append(format.at(i++));
         }
     }
     if (i < format.size())
         ++i;
     return result;
 }
qt_repeatCount()
int qt_repeatCount (const QString & s, int i)
Definition at line 421 of file qlocale.cpp.
Referenced by QLocalePrivate::dateTimeToString(), QLocalePrivate::digitToCLocale(), macToQtFormat(), and QSystemLocalePrivate::winToQtFormat().
 {
     QChar c = s.at(i);
     int j = i + 1;
     while (j < s.size() && s.at(j) == c)
         ++j;
     return j - i;
 }
qt_splitLocaleName()
bool qt_splitLocaleName (const QString & name, QString & lang, QString & script, QString & cntry)
Definition at line 302 of file qlocale.cpp.
Referenced by QLocalePrivate::digitToCLocale(), QLocalePrivate::getLangAndCountry(), getMacLocaleName(), and getWinLocaleName().
 {
     const int length = name.length();
     lang = script = cntry = QString();
     const QString separators = QLatin1String("_-.@");
     enum ParserState { NoState, LangState, ScriptState, CountryState };
     ParserState state = LangState;
     for (int i = 0; i < length && state != NoState; ) {
         QString value;
         if (!parse_locale_tag(name, i, &value, separators) ||value.isEmpty())
             break;
         QChar sep = i < length ? name.at(i) : QChar();
         switch (state) {
         case LangState:
             if (!sep.isNull() && !separators.contains(sep)) {
                 state = NoState;
                 break;
             }
             lang = value;
             if (i == length) {
                 // just language was specified
                 state = NoState;
                 break;
             }
             state = ScriptState;
             break;
         case ScriptState: {
             QString scripts = QString::fromLatin1((const char *)script_code_list, sizeof(script_code_list));
             if (value.length() == 4 && scripts.indexOf(value) % 4 == 0) {
                 // script name is always 4 characters
                 script = value;
                 state = CountryState;
             } else {
                 // it wasn't a script, maybe it is a country then?
                 cntry = value;
                 state = NoState;
             }
             break;
         }
         case CountryState:
             cntry = value;
             state = NoState;
             break;
         case NoState:
             // shouldn't happen
             qWarning("QLocale: This should never happen");
             break;
         }
         ++i;
     }
     return lang.length() == 2 || lang.length() == 3;
 }