Qt 4.8: /src/corelib/tools/qlocale_mac.mm File Reference
qlocale_mac.mm File Reference
#include "qlocale_p.h"
#include "qstringlist.h"
#include "qvariant.h"
#include "qdatetime.h"
#include "private/qcore_mac_p.h"
#include <CoreFoundation/CoreFoundation.h>
Functions
static QByteArray envVarLocale ()
static QString getCFLocaleValue (CFStringRef key)
QString getMacDateFormat (CFDateFormatterStyle style)
static QByteArray getMacLocaleName ()
static QString getMacTimeFormat (CFDateFormatterStyle style)
static QString macCurrencySymbol (QLocale::CurrencySymbolFormat format)
static QString macDateToString (const QDate &date, bool short_format)
static QString macDayName (int day, bool short_format)
static quint8 macFirstDayOfWeek ()
static QString macFormatCurrency (const QSystemLocale::CurrencyToStringArgument &arg)
static QLocale::MeasurementSystem macMeasurementSystem ()
static QString macMonthName (int month, bool short_format)
static QVariant macQuoteString (QSystemLocale::QueryType type, const QStringRef &str)
static QString macTimeToString (const QTime &time, bool short_format)
static QString macToQtFormat (const QString &sys_fmt)
Function Documentation
envVarLocale()
static QByteArray envVarLocale () static
Definition at line 59 of file qlocale_mac.mm.
Referenced by getMacLocaleName().
 {
     static QByteArray lang = 0;
 #ifdef Q_OS_UNIX
     lang = qgetenv("LC_ALL");
     if (lang.isEmpty())
         lang = qgetenv("LC_NUMERIC");
     if (lang.isEmpty())
 #endif
         lang = qgetenv("LANG");
     return lang;
 }
getCFLocaleValue()
static QString getCFLocaleValue (CFStringRef key) static
Definition at line 309 of file qlocale_mac.mm.
Referenced by macQuoteString().
 {
     QCFType<CFLocaleRef> locale = CFLocaleCopyCurrent();
     CFTypeRef value = CFLocaleGetValue(locale, key);
     return QCFString::toQString(CFStringRef(static_cast<CFTypeRef>(value)));
 }
getMacDateFormat()
QString getMacDateFormat (CFDateFormatterStyle style)
Definition at line 293 of file qlocale_mac.mm.
Referenced by macQuoteString().
 {
     QCFType<CFLocaleRef> l = CFLocaleCopyCurrent();
     QCFType<CFDateFormatterRef> formatter = CFDateFormatterCreate(kCFAllocatorDefault,
                                                                   l, style, kCFDateFormatterNoStyle);
     return macToQtFormat(QCFString::toQString(CFDateFormatterGetFormat(formatter)));
 }
getMacLocaleName()
static QByteArray getMacLocaleName () static
Definition at line 72 of file qlocale_mac.mm.
Referenced by macQuoteString().
 {
     QByteArray result = envVarLocale();
     QString lang, script, cntry;
     if (result.isEmpty() || result != "C"
             && !qt_splitLocaleName(QString::fromLocal8Bit(result), lang, script, cntry)) {
         QCFType<CFLocaleRef> l = CFLocaleCopyCurrent();
         CFStringRef locale = CFLocaleGetIdentifier(l);
         result = QCFString::toQString(locale).toUtf8();
     }
     return result;
 }
getMacTimeFormat()
static QString getMacTimeFormat (CFDateFormatterStyle style) static
Definition at line 301 of file qlocale_mac.mm.
Referenced by macQuoteString().
 {
     QCFType<CFLocaleRef> l = CFLocaleCopyCurrent();
     QCFType<CFDateFormatterRef> formatter = CFDateFormatterCreate(kCFAllocatorDefault,
                                                                   l, kCFDateFormatterNoStyle, style);
     return macToQtFormat(QCFString::toQString(CFDateFormatterGetFormat(formatter)));
 }
macCurrencySymbol()
static QString macCurrencySymbol (QLocale::CurrencySymbolFormat format) static
Definition at line 337 of file qlocale_mac.mm.
Referenced by macQuoteString().
 {
     QCFType<CFLocaleRef> locale = CFLocaleCopyCurrent();
     switch (format) {
     case QLocale::CurrencyIsoCode:
         return QCFString::toQString(static_cast<CFStringRef>(CFLocaleGetValue(locale, kCFLocaleCurrencyCode)));
     case QLocale::CurrencySymbol:
         return QCFString::toQString(static_cast<CFStringRef>(CFLocaleGetValue(locale, kCFLocaleCurrencySymbol)));
     case QLocale::CurrencyDisplayName: {
         CFStringRef code = static_cast<CFStringRef>(CFLocaleGetValue(locale, kCFLocaleCurrencyCode));
         QCFType<CFStringRef> value = CFLocaleCopyDisplayNameForPropertyValue(locale, kCFLocaleCurrencyCode, code);
         return QCFString::toQString(value);
     }
     default:
         break;
     }
     return QString();
 }
macDateToString()
static QString macDateToString (const QDate & date, bool short_format) static
Definition at line 124 of file qlocale_mac.mm.
Referenced by macQuoteString().
 {
     CFGregorianDate macGDate;
     macGDate.year = date.year();
     macGDate.month = date.month();
     macGDate.day = date.day();
     macGDate.hour = 0;
     macGDate.minute = 0;
     macGDate.second = 0.0;
     QCFType<CFDateRef> myDate
         = CFDateCreate(0, CFGregorianDateGetAbsoluteTime(macGDate,
                                                          QCFType<CFTimeZoneRef>(CFTimeZoneCopyDefault())));
     QCFType<CFLocaleRef> mylocale = CFLocaleCopyCurrent();
     CFDateFormatterStyle style = short_format ? kCFDateFormatterShortStyle : kCFDateFormatterLongStyle;
     QCFType<CFDateFormatterRef> myFormatter
         = CFDateFormatterCreate(kCFAllocatorDefault,
                                 mylocale, style,
                                 kCFDateFormatterNoStyle);
     return QCFString(CFDateFormatterCreateStringWithDate(0, myFormatter, myDate));
 }
macDayName()
static QString macDayName (int day, bool short_format) static
Definition at line 106 of file qlocale_mac.mm.
Referenced by macQuoteString().
 {
     if (day < 1 || day > 7)
         return QString();
     QCFType<CFDateFormatterRef> formatter
         = CFDateFormatterCreate(0, QCFType<CFLocaleRef>(CFLocaleCopyCurrent()),
                                 kCFDateFormatterNoStyle,  kCFDateFormatterNoStyle);
     QCFType<CFArrayRef> values = static_cast<CFArrayRef>(CFDateFormatterCopyProperty(formatter,
                                             short_format ? kCFDateFormatterShortWeekdaySymbols
                                                          : kCFDateFormatterWeekdaySymbols));
     if (values != 0) {
         CFStringRef cfstring = static_cast<CFStringRef>(CFArrayGetValueAtIndex(values, day % 7));
         return QCFString::toQString(cfstring);
     }
     return QString();
 }
macFirstDayOfWeek()
static quint8 macFirstDayOfWeek () static
Definition at line 328 of file qlocale_mac.mm.
Referenced by macQuoteString().
 {
     QCFType<CFCalendarRef> calendar = CFCalendarCopyCurrent();
     quint8 day = static_cast<quint8>(CFCalendarGetFirstWeekday(calendar))-1;
     if (day == 0)
         day = 7;
     return day;
 }
macFormatCurrency()
static QString macFormatCurrency (const QSystemLocale::CurrencyToStringArgument & arg) static
Definition at line 357 of file qlocale_mac.mm.
Referenced by macQuoteString().
 {
     QCFType<CFNumberRef> value;
     switch (arg.value.type()) {
     case QVariant::Int:
     case QVariant::UInt: {
         int v = arg.value.toInt();
         value = CFNumberCreate(NULL, kCFNumberIntType, &v);
         break;
     }
     case QVariant::Double: {
         double v = arg.value.toDouble();
         value = CFNumberCreate(NULL, kCFNumberDoubleType, &v);
         break;
     }
     case QVariant::LongLong:
     case QVariant::ULongLong: {
         qint64 v = arg.value.toLongLong();
         value = CFNumberCreate(NULL, kCFNumberLongLongType, &v);
         break;
     }
     default:
         return QString();
     }
     QCFType<CFLocaleRef> locale = CFLocaleCopyCurrent();
     QCFType<CFNumberFormatterRef> currencyFormatter =
             CFNumberFormatterCreate(NULL, locale, kCFNumberFormatterCurrencyStyle);
     if (!arg.symbol.isEmpty()) {
         CFNumberFormatterSetProperty(currencyFormatter, kCFNumberFormatterCurrencySymbol,
                                      QCFString::toCFStringRef(arg.symbol));
     }
     QCFType<CFStringRef> result = CFNumberFormatterCreateStringWithNumber(NULL, currencyFormatter, value);
     return QCFString::toQString(result);
 }
macMeasurementSystem()
static QLocale::MeasurementSystem macMeasurementSystem () static
Definition at line 316 of file qlocale_mac.mm.
Referenced by macQuoteString().
 {
     QCFType<CFLocaleRef> locale = CFLocaleCopyCurrent();
     CFStringRef system = static_cast<CFStringRef>(CFLocaleGetValue(locale, kCFLocaleMeasurementSystem));
     if (QCFString::toQString(system) == QLatin1String("Metric")) {
         return QLocale::MetricSystem;
     } else {
         return QLocale::ImperialSystem;
     }
 }
macMonthName()
static QString macMonthName (int month, bool short_format) static
Definition at line 86 of file qlocale_mac.mm.
Referenced by macQuoteString().
 {
     month -= 1;
     if (month < 0 || month > 11)
         return QString();
     QCFType<CFDateFormatterRef> formatter
         = CFDateFormatterCreate(0, QCFType<CFLocaleRef>(CFLocaleCopyCurrent()),
                                 kCFDateFormatterNoStyle,  kCFDateFormatterNoStyle);
     QCFType<CFArrayRef> values
         = static_cast<CFArrayRef>(CFDateFormatterCopyProperty(formatter,
                                   short_format ? kCFDateFormatterShortMonthSymbols
                                                : kCFDateFormatterMonthSymbols));
     if (values != 0) {
         CFStringRef cfstring = static_cast<CFStringRef>(CFArrayGetValueAtIndex(values, month));
         return QCFString::toQString(cfstring);
     }
     return QString();
 }
macQuoteString()
static QVariant macQuoteString (QSystemLocale::QueryType type, const QStringRef & str) static
Definition at line 393 of file qlocale_mac.mm.
 {
 #if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_6 && !defined(Q_OS_IOS)
     if (QSysInfo::MacintoshVersion < QSysInfo::MV_10_6)
         return QVariant();
     QString begin, end;
     QCFType<CFLocaleRef> locale = CFLocaleCopyCurrent();
     switch (type) {
     case QSystemLocale::StringToStandardQuotation:
         begin = QCFString::toQString(static_cast<CFStringRef>(CFLocaleGetValue(locale, kCFLocaleQuotationBeginDelimiterKey)));
         end = QCFString::toQString(static_cast<CFStringRef>(CFLocaleGetValue(locale, kCFLocaleQuotationEndDelimiterKey)));
         return QString(begin % str % end);
     case QSystemLocale::StringToAlternateQuotation:
         begin = QCFString::toQString(static_cast<CFStringRef>(CFLocaleGetValue(locale, kCFLocaleAlternateQuotationBeginDelimiterKey)));
         end = QCFString::toQString(static_cast<CFStringRef>(CFLocaleGetValue(locale, kCFLocaleAlternateQuotationEndDelimiterKey)));
         return QString(begin % str % end);
      default:
         break;
     }
 #endif
     return QVariant();
 }
macTimeToString()
static QString macTimeToString (const QTime & time, bool short_format) static
Definition at line 145 of file qlocale_mac.mm.
Referenced by macQuoteString().
 {
     CFGregorianDate macGDate;
     // Assume this is local time and the current date
     QDate dt = QDate::currentDate();
     macGDate.year = dt.year();
     macGDate.month = dt.month();
     macGDate.day = dt.day();
     macGDate.hour = time.hour();
     macGDate.minute = time.minute();
     macGDate.second = time.second();
     QCFType<CFDateRef> myDate
         = CFDateCreate(0, CFGregorianDateGetAbsoluteTime(macGDate,
                                                          QCFType<CFTimeZoneRef>(CFTimeZoneCopyDefault())));
     QCFType<CFLocaleRef> mylocale = CFLocaleCopyCurrent();
     CFDateFormatterStyle style = short_format ? kCFDateFormatterShortStyle :  kCFDateFormatterLongStyle;
     QCFType<CFDateFormatterRef> myFormatter = CFDateFormatterCreate(kCFAllocatorDefault,
                                                                     mylocale,
                                                                     kCFDateFormatterNoStyle,
                                                                     style);
     return QCFString(CFDateFormatterCreateStringWithDate(0, myFormatter, myDate));
 }
macToQtFormat()
static QString macToQtFormat (const QString & sys_fmt) static
Definition at line 174 of file qlocale_mac.mm.
Referenced by getMacDateFormat(), and getMacTimeFormat().
 {
     QString result;
     int i = 0;
     while (i < sys_fmt.size()) {
         if (sys_fmt.at(i).unicode() == '\'') {
             QString text = qt_readEscapedFormatString(sys_fmt, &i);
             if (text == QLatin1String("'"))
                 result += QLatin1String("''");
             else
                 result += QLatin1Char('\'') + text + QLatin1Char('\'');
             continue;
         }
         QChar c = sys_fmt.at(i);
         int repeat = qt_repeatCount(sys_fmt, i);
         switch (c.unicode()) {
             // Qt does not support the following options
             case 'G': // Era (1..5): 4 = long, 1..3 = short, 5 = narrow
             case 'Y': // Year of Week (1..n): 1..n = padded number
             case 'U': // Cyclic Year Name (1..5): 4 = long, 1..3 = short, 5 = narrow
             case 'Q': // Quarter (1..4): 4 = long, 3 = short, 1..2 = padded number
             case 'q': // Standalone Quarter (1..4): 4 = long, 3 = short, 1..2 = padded number
             case 'w': // Week of Year (1..2): 1..2 = padded number
             case 'W': // Week of Month (1): 1 = number
             case 'D': // Day of Year (1..3): 1..3 = padded number
             case 'F': // Day of Week in Month (1): 1 = number
             case 'g': // Modified Julian Day (1..n): 1..n = padded number
             case 'A': // Milliseconds in Day (1..n): 1..n = padded number
                 break;
             case 'y': // Year (1..n): 2 = short year, 1 & 3..n = padded number
             case 'u': // Extended Year (1..n): 2 = short year, 1 & 3..n = padded number
                 // Qt only supports long (4) or short (2) year, use long for all others
                 if (repeat == 2)
                     result += QLatin1String("yy");
                 else
                     result += QLatin1String("yyyy");
                 break;
             case 'M': // Month (1..5): 4 = long, 3 = short, 1..2 = number, 5 = narrow
             case 'L': // Standalone Month (1..5): 4 = long, 3 = short, 1..2 = number, 5 = narrow
                 // Qt only supports long, short and number, use short for narrow
                 if (repeat == 5)
                     result += QLatin1String("MMM");
                 else
                     result += QString(repeat, QLatin1Char('M'));
                 break;
             case 'd': // Day of Month (1..2): 1..2 padded number
                 result += QString(repeat, c);
                 break;
             case 'E': // Day of Week (1..6): 4 = long, 1..3 = short, 5..6 = narrow
                 // Qt only supports long, short and padded number, use short for narrow
                 if (repeat == 4)
                     result += QLatin1String("dddd");
                 else
                     result += QLatin1String("ddd");
                 break;
             case 'e': // Local Day of Week (1..6): 4 = long, 3 = short, 5..6 = narrow, 1..2 padded number
             case 'c': // Standalone Local Day of Week (1..6): 4 = long, 3 = short, 5..6 = narrow, 1..2 padded number
                 // Qt only supports long, short and padded number, use short for narrow
                 if (repeat >= 5)
                     result += QLatin1String("ddd");
                 else
                     result += QString(repeat, QLatin1Char('d'));
                 break;
             case 'a': // AM/PM (1): 1 = short
                 // Translate to Qt uppercase AM/PM
                 result += QLatin1String("AP");
                 break;
             case 'h': // Hour [1..12] (1..2): 1..2 = padded number
             case 'K': // Hour [0..11] (1..2): 1..2 = padded number
             case 'j': // Local Hour [12 or 24] (1..2): 1..2 = padded number
                 // Qt h is local hour
                 result += QString(repeat, QLatin1Char('h'));
                 break;
             case 'H': // Hour [0..23] (1..2): 1..2 = padded number
             case 'k': // Hour [1..24] (1..2): 1..2 = padded number
                 // Qt H is 0..23 hour
                 result += QString(repeat, QLatin1Char('H'));
                 break;
             case 'm': // Minutes (1..2): 1..2 = padded number
             case 's': // Seconds (1..2): 1..2 = padded number
                 result += QString(repeat, c);
                 break;
             case 'S': // Fractional second (1..n): 1..n = truncates to decimal places
                 // Qt uses msecs either unpadded or padded to 3 places
                 if (repeat < 3)
                     result += QLatin1Char('z');
                 else
                     result += QLatin1String("zzz");
                 break;
             case 'z': // Time Zone (1..4)
             case 'Z': // Time Zone (1..5)
             case 'O': // Time Zone (1, 4)
             case 'v': // Time Zone (1, 4)
             case 'V': // Time Zone (1..4)
             case 'X': // Time Zone (1..5)
             case 'x': // Time Zone (1..5)
                 result += QLatin1Char('t');
                 break;
             default:
                 // a..z and A..Z are reserved for format codes, so any occurrence of these not
                 // already processed are not known and so unsupported formats to be ignored.
                 // All other chars are allowed as literals.
                 if (c < QLatin1Char('A') || c > QLatin1Char('z') ||
                     (c > QLatin1Char('Z') && c < QLatin1Char('a'))) {
                     result += QString(repeat, c);
                 }
                 break;
         }
         i += repeat;
     }
     return result;
 }