Qt 4.8: /src/corelib/tools/qlocale_win.cpp File Reference
qlocale_win.cpp File Reference
#include "qlocale_p.h"
#include "qlocale_tools_p.h"
#include "qstringlist.h"
#include "qvariant.h"
#include "qdatetime.h"
#include "private/qsystemlibrary_p.h"
#include "qdebug.h"
#include "qt_windows.h"
#include <time.h>
Classes
struct QSystemLocalePrivate
struct WindowsToISOListElt
Macros
#define LOCALE_SNATIVECOUNTRYNAME 0x00000008
#define LOCALE_SNATIVELANGUAGENAME 0x00000004
#define LOCALE_SSHORTESTDAYNAME1 0x0060
#define LOCALE_SSHORTESTDAYNAME2 0x0061
#define LOCALE_SSHORTESTDAYNAME3 0x0062
#define LOCALE_SSHORTESTDAYNAME4 0x0063
#define LOCALE_SSHORTESTDAYNAME5 0x0064
#define LOCALE_SSHORTESTDAYNAME6 0x0065
#define LOCALE_SSHORTESTDAYNAME7 0x0066
#define MUI_LANGUAGE_NAME 0x8
Functions
static QByteArray getWinLocaleName (LCID id=LOCALE_USER_DEFAULT)
Q_CORE_EXPORT QLocale qt_localeFromLCID (LCID id)
static QString winIso3116CtryName (LCID id=LOCALE_USER_DEFAULT)
static QString winIso639LangName (LCID id=LOCALE_USER_DEFAULT)
static const char * winLangCodeToIsoName (int code)
Variables
static const int windows_to_iso_count = sizeof(windows_to_iso_list)/sizeof(WindowsToISOListElt)
static const WindowsToISOListElt windows_to_iso_list []
Macro Definition Documentation
LOCALE_SNATIVECOUNTRYNAME
#define LOCALE_SNATIVECOUNTRYNAME 0x00000008
Definition at line 83 of file qlocale_win.cpp.
Referenced by QSystemLocalePrivate::nativeCountryName().
LOCALE_SNATIVELANGUAGENAME
#define LOCALE_SNATIVELANGUAGENAME 0x00000004
Definition at line 80 of file qlocale_win.cpp.
Referenced by QSystemLocalePrivate::nativeLanguageName().
LOCALE_SSHORTESTDAYNAME1
#define LOCALE_SSHORTESTDAYNAME1 0x0060
Definition at line 71 of file qlocale_win.cpp.
Referenced by QSystemLocalePrivate::dayName().
LOCALE_SSHORTESTDAYNAME2
#define LOCALE_SSHORTESTDAYNAME2 0x0061
Definition at line 72 of file qlocale_win.cpp.
Referenced by QSystemLocalePrivate::dayName().
LOCALE_SSHORTESTDAYNAME3
#define LOCALE_SSHORTESTDAYNAME3 0x0062
Definition at line 73 of file qlocale_win.cpp.
Referenced by QSystemLocalePrivate::dayName().
LOCALE_SSHORTESTDAYNAME4
#define LOCALE_SSHORTESTDAYNAME4 0x0063
Definition at line 74 of file qlocale_win.cpp.
Referenced by QSystemLocalePrivate::dayName().
LOCALE_SSHORTESTDAYNAME5
#define LOCALE_SSHORTESTDAYNAME5 0x0064
Definition at line 75 of file qlocale_win.cpp.
Referenced by QSystemLocalePrivate::dayName().
LOCALE_SSHORTESTDAYNAME6
#define LOCALE_SSHORTESTDAYNAME6 0x0065
Definition at line 76 of file qlocale_win.cpp.
Referenced by QSystemLocalePrivate::dayName().
LOCALE_SSHORTESTDAYNAME7
#define LOCALE_SSHORTESTDAYNAME7 0x0066
Definition at line 77 of file qlocale_win.cpp.
Referenced by QSystemLocalePrivate::dayName().
MUI_LANGUAGE_NAME
#define MUI_LANGUAGE_NAME 0x8
Definition at line 68 of file qlocale_win.cpp.
Referenced by QSystemLocalePrivate::uiLanguages().
Function Documentation
getWinLocaleName()
static QByteArray getWinLocaleName (LCID id = LOCALE_USER_DEFAULT) static
Definition at line 949 of file qlocale_win.cpp.
Referenced by qt_localeFromLCID(), and QSystemLocalePrivate::winToQtFormat().
 {
     QByteArray result;
     if (id == LOCALE_USER_DEFAULT) {
         static QByteArray langEnvVar = qgetenv("LANG");
         result = langEnvVar;
         QString lang, script, cntry;
         if ( result == "C" || (!result.isEmpty()
                 && qt_splitLocaleName(QString::fromLocal8Bit(result), lang, script, cntry)) ) {
             long id = 0;
             bool ok = false;
             id = qstrtoll(result.data(), 0, 0, &ok);
             if ( !ok || id == 0 || id < INT_MIN || id > INT_MAX )
                 return result;
             else
                 return winLangCodeToIsoName( (int)id );
         }
     }
 #if defined(Q_OS_WINCE)
     result = winLangCodeToIsoName(id != LOCALE_USER_DEFAULT ? id : GetUserDefaultLCID());
 #else
     if (id == LOCALE_USER_DEFAULT)
         id = GetUserDefaultLCID();
     QString resultuage = winIso639LangName(id);
     QString country = winIso3116CtryName(id);
     result = resultuage.toLatin1();
     if (!country.isEmpty()) {
         result += '_';
         result += country.toLatin1();
     }
 #endif
     return result;
 }
qt_localeFromLCID()
Q_CORE_EXPORT QLocale qt_localeFromLCID (LCID id)
Definition at line 985 of file qlocale_win.cpp.
 {
     return QLocale(QString::fromLatin1(getWinLocaleName(id)));
 }
winIso3116CtryName()
static QString winIso3116CtryName (LCID id = LOCALE_USER_DEFAULT) static
Definition at line 938 of file qlocale_win.cpp.
Referenced by getWinLocaleName().
 {
     QString result;
     wchar_t out[256];
     if (GetLocaleInfo(id, LOCALE_SISO3166CTRYNAME, out, 255))
         result = QString::fromWCharArray(out);
     return result;
 }
winIso639LangName()
static QString winIso639LangName (LCID id = LOCALE_USER_DEFAULT) static
Definition at line 901 of file qlocale_win.cpp.
Referenced by getWinLocaleName().
 {
     QString result;
     // Windows returns the wrong ISO639 for some languages, we need to detect them here using
     // the language code
     QString lang_code;
     wchar_t out[256];
     if (GetLocaleInfo(id, LOCALE_ILANGUAGE, out, 255)) // ### shouldn't use them according to msdn
         lang_code = QString::fromWCharArray(out);
     if (!lang_code.isEmpty()) {
         const char *endptr;
         bool ok;
         QByteArray latin1_lang_code = lang_code.toLatin1();
         int i = qstrtoull(latin1_lang_code, &endptr, 16, &ok);
         if (ok && *endptr == '\0') {
             switch (i) {
                 case 0x814:
                     result = QLatin1String("nn"); // Nynorsk
                     break;
                 default:
                     break;
             }
         }
     }
     if (!result.isEmpty())
         return result;
     // not one of the problematic languages - do the usual lookup
     if (GetLocaleInfo(id, LOCALE_SISO639LANGNAME , out, 255))
         result = QString::fromWCharArray(out);
     return result;
 }
winLangCodeToIsoName()
static const char * winLangCodeToIsoName (int code) static
Definition at line 872 of file qlocale_win.cpp.
Referenced by getWinLocaleName(), and QSystemLocalePrivate::uiLanguages().
 {
     int cmp = code - windows_to_iso_list[0].windows_code;
     if (cmp < 0)
         return 0;
     if (cmp == 0)
         return windows_to_iso_list[0].iso_name;
     int begin = 0;
     int end = windows_to_iso_count;
     while (end - begin > 1) {
         uint mid = (begin + end)/2;
         const WindowsToISOListElt *elt = windows_to_iso_list + mid;
         int cmp = code - elt->windows_code;
         if (cmp < 0)
             end = mid;
         else if (cmp > 0)
             begin = mid;
         else
             return elt->iso_name;
     }
     return 0;
 }
Variable Documentation
windows_to_iso_count
const int windows_to_iso_count = sizeof(windows_to_iso_list)/sizeof(WindowsToISOListElt) static
Definition at line 870 of file qlocale_win.cpp.
Referenced by winLangCodeToIsoName().
windows_to_iso_list
const WindowsToISOListElt windows_to_iso_list[] static
Definition at line 758 of file qlocale_win.cpp.