Qt 4.8: /src/corelib/tools/qlocale_tools_p.h File Reference
qlocale_tools_p.h File Reference
#include "qlocale_p.h"
#include "qstring.h"
Macros
#define NEEDS_VOLATILE
Enumerations
enum PrecisionMode { PMDecimalDigits = 0x01, PMSignificantDigits = 0x02, PMChopTrailingZeros = 0x03 }
Functions
QString & decimalForm (QChar zero, QChar decimal, QChar group, QString &digits, int decpt, uint precision, PrecisionMode pm, bool always_show_decpt, bool thousands_group)
QString & exponentForm (QChar zero, QChar decimal, QChar exponential, QChar group, QChar plus, QChar minus, QString &digits, int decpt, uint precision, PrecisionMode pm, bool always_show_decpt)
bool isZero (double d)
Q_CORE_EXPORT char * qdtoa (double d, int mode, int ndigits, int *decpt, int *sign, char **rve, char **digits_str)
QString qlltoa (qlonglong l, int base, const QChar zero)
Q_CORE_EXPORT double qstrtod (const char *s00, char const **se, bool *ok)
qlonglong qstrtoll (const char *nptr, const char **endptr, register int base, bool *ok)
qulonglong qstrtoull (const char *nptr, const char **endptr, register int base, bool *ok)
QString qulltoa (qulonglong l, int base, const QChar _zero)
bool removeGroupSeparators (QLocalePrivate::CharBuff *num)
Macro Definition Documentation
NEEDS_VOLATILE
#define NEEDS_VOLATILE
Definition at line 72 of file qlocale_tools_p.h.
Referenced by _getWord0(), _getWord1(), _setWord0(), and _setWord1().
Enumeration Type Documentation
PrecisionMode
enum PrecisionMode
Enumerator
PMDecimalDigits
PMSignificantDigits
PMChopTrailingZeros
Definition at line 80 of file qlocale_tools_p.h.
                    {
     PMDecimalDigits =             0x01,
     PMSignificantDigits =   0x02,
     PMChopTrailingZeros =   0x03
 };
Function Documentation
decimalForm()
QString& decimalForm (QChar zero, QChar decimal, QChar group, QString & digits, int decpt, uint precision, PrecisionMode pm, bool always_show_decpt, bool thousands_group)
Definition at line 116 of file qlocale_tools.cpp.
Referenced by QLocalePrivate::doubleToString().
 {
     if (decpt < 0) {
         for (int i = 0; i < -decpt; ++i)
             digits.prepend(zero);
         decpt = 0;
     }
     else if (decpt > digits.length()) {
         for (int i = digits.length(); i < decpt; ++i)
             digits.append(zero);
     }
     if (pm == PMDecimalDigits) {
         uint decimal_digits = digits.length() - decpt;
         for (uint i = decimal_digits; i < precision; ++i)
             digits.append(zero);
     }
     else if (pm == PMSignificantDigits) {
         for (uint i = digits.length(); i < precision; ++i)
             digits.append(zero);
     }
     else { // pm == PMChopTrailingZeros
     }
     if (always_show_decpt || decpt < digits.length())
         digits.insert(decpt, decimal);
     if (thousands_group) {
         for (int i = decpt - 3; i > 0; i -= 3)
             digits.insert(i, group);
     }
     if (decpt == 0)
         digits.prepend(zero);
     return digits;
 }
exponentForm()
QString& exponentForm (QChar zero, QChar decimal, QChar exponential, QChar group, QChar plus, QChar minus, QString & digits, int decpt, uint precision, PrecisionMode pm, bool always_show_decpt)
Definition at line 158 of file qlocale_tools.cpp.
Referenced by QLocalePrivate::doubleToString().
 {
     int exp = decpt - 1;
     if (pm == PMDecimalDigits) {
         for (uint i = digits.length(); i < precision + 1; ++i)
             digits.append(zero);
     }
     else if (pm == PMSignificantDigits) {
         for (uint i = digits.length(); i < precision; ++i)
             digits.append(zero);
     }
     else { // pm == PMChopTrailingZeros
     }
     if (always_show_decpt || digits.length() > 1)
         digits.insert(1, decimal);
     digits.append(exponential);
     digits.append(QLocalePrivate::longLongToString(zero, group, plus, minus,
                    exp, 2, 10, -1, QLocalePrivate::AlwaysShowSign));
     return digits;
 }
isZero()
bool isZero (double d) inline
Definition at line 97 of file qlocale_tools_p.h.
Referenced by QLocalePrivate::doubleToString().
 {
     uchar *ch = (uchar *)&d;
 #ifdef QT_ARMFPA
         return !(ch[3] & 0x7F || ch[2] || ch[1] || ch[0] || ch[7] || ch[6] || ch[5] || ch[4]);
 #else
     if (QSysInfo::ByteOrder == QSysInfo::BigEndian) {
         return !(ch[0] & 0x7F || ch[1] || ch[2] || ch[3] || ch[4] || ch[5] || ch[6] || ch[7]);
     } else {
         return !(ch[7] & 0x7F || ch[6] || ch[5] || ch[4] || ch[3] || ch[2] || ch[1] || ch[0]);
     }
 #endif
 }
qdtoa()
Q_CORE_EXPORT char* qdtoa (double d, int mode, int ndigits, int * decpt, int * sign, char ** rve, char ** digits_str)
Definition at line 2271 of file qlocale_tools.cpp.
Referenced by isZero().
 {
     // Some values of the floating-point control word can cause _qdtoa to crash with an underflow.
     // We set a safe value here.
 #ifdef Q_OS_WIN
     _clear87();
     unsigned int oldbits = _control87(0, 0);
 #ifndef MCW_EM
 #    ifdef _MCW_EM
 #        define MCW_EM _MCW_EM
 #    else
 #        define MCW_EM 0x0008001F
 #    endif
 #endif
     _control87(MCW_EM, MCW_EM);
 #endif
 #if defined(Q_OS_LINUX) && !defined(__UCLIBC__)
     fenv_t envp;
     feholdexcept(&envp);
 #endif
     char *s = _qdtoa(d, mode, ndigits, decpt, sign, rve, resultp);
 #ifdef Q_OS_WIN
     _clear87();
 #ifndef _M_X64
     _control87(oldbits, 0xFFFFF);
 #else
     _control87(oldbits, _MCW_EM|_MCW_DN|_MCW_RC);
 #endif //_M_X64
 #endif //Q_OS_WIN
 #if defined(Q_OS_LINUX) && !defined(__UCLIBC__)
     fesetenv(&envp);
 #endif
     return s;
 }
qlltoa()
QString qlltoa (qlonglong l, int base, const QChar zero)
Definition at line 111 of file qlocale_tools.cpp.
Referenced by QLocalePrivate::longLongToString().
 {
     return qulltoa(l < 0 ? -l : l, base, zero);
 }
qstrtod()
Q_CORE_EXPORT double qstrtod (const char * s00, char const ** se, bool * ok)
Definition at line 1570 of file qlocale_tools.cpp.
Referenced by isZero().
 {
     int bb2, bb5, bbe, bd2, bd5, bbbits, bs2, c, dsign,
         e, e1, esign, i, j, k, nd, nd0, nf, nz, nz0, sign;
     const char *s, *s0, *s1;
     double aadj, aadj1, adj, rv, rv0;
     Long L;
     ULong y, z;
     Bigint *bb1, *bd0;
     Bigint *bb = NULL, *bd = NULL, *bs = NULL, *delta = NULL;/* pacify gcc */
     /*
       #ifndef KR_headers
       const char decimal_point = localeconv()->decimal_point[0];
       #else
       const char decimal_point = '.';
       #endif */
     if (ok != 0)
         *ok = true;
     const char decimal_point = '.';
     sign = nz0 = nz = 0;
     rv = 0.;
     for(s = s00; isspace(uchar(*s)); s++)
         ;
     if (*s == '-') {
         sign = 1;
         s++;
     } else if (*s == '+') {
         s++;
     }
     if (*s == '\0') {
         s = s00;
         goto ret;
     }
     if (*s == '0') {
         nz0 = 1;
         while(*++s == '0') ;
         if (!*s)
             goto ret;
     }
     s0 = s;
     y = z = 0;
     for(nd = nf = 0; (c = *s) >= '0' && c <= '9'; nd++, s++)
         if (nd < 9)
             y = 10*y + c - '0';
         else if (nd < 16)
             z = 10*z + c - '0';
     nd0 = nd;
     if (c == decimal_point) {
         c = *++s;
         if (!nd) {
             for(; c == '0'; c = *++s)
                 nz++;
             if (c > '0' && c <= '9') {
                 s0 = s;
                 nf += nz;
                 nz = 0;
                 goto have_dig;
             }
             goto dig_done;
         }
         for(; c >= '0' && c <= '9'; c = *++s) {
         have_dig:
             nz++;
             if (c -= '0') {
                 nf += nz;
                 for(i = 1; i < nz; i++)
                     if (nd++ < 9)
                         y *= 10;
                     else if (nd <= DBL_DIG + 1)
                         z *= 10;
                 if (nd++ < 9)
                     y = 10*y + c;
                 else if (nd <= DBL_DIG + 1)
                     z = 10*z + c;
                 nz = 0;
             }
         }
     }
  dig_done:
     e = 0;
     if (c == 'e' || c == 'E') {
         if (!nd && !nz && !nz0) {
             s = s00;
             goto ret;
         }
         s00 = s;
         esign = 0;
         switch(c = *++s) {
         case '-':
             esign = 1;
         case '+':
             c = *++s;
         }
         if (c >= '0' && c <= '9') {
             while(c == '0')
                 c = *++s;
             if (c > '0' && c <= '9') {
                 L = c - '0';
                 s1 = s;
                 while((c = *++s) >= '0' && c <= '9')
                     L = 10*L + c - '0';
                 if (s - s1 > 8 || L > 19999)
                     /* Avoid confusion from exponents
                      * so large that e might overflow.
                      */
                     e = 19999; /* safe for 16 bit ints */
                 else
                     e = int(L);
                 if (esign)
                     e = -e;
             }
             else
                 e = 0;
         }
         else
             s = s00;
     }
     if (!nd) {
         if (!nz && !nz0)
             s = s00;
         goto ret;
     }
     e1 = e -= nf;
     /* Now we have nd0 digits, starting at s0, followed by a
      * decimal point, followed by nd-nd0 digits.  The number we're
      * after is the integer represented by those digits times
      * 10**e */
     if (!nd0)
         nd0 = nd;
     k = nd < DBL_DIG + 1 ? nd : DBL_DIG + 1;
     rv = y;
     if (k > 9)
 #if defined(Q_OS_IRIX) && defined(Q_CC_GNU)
     {
         // work around a bug on 64 bit IRIX gcc
         double *t = (double *) tens;
         rv = t[k - 9] * rv + z;
     }
 #else
     rv = tens[k - 9] * rv + z;
 #endif
     bd0 = 0;
     if (nd <= DBL_DIG
 #ifndef RND_PRODQUOT
         && FLT_ROUNDS == 1
 #endif
         ) {
         if (!e)
             goto ret;
         if (e > 0) {
             if (e <= Ten_pmax) {
 #ifdef VAX
                 goto vax_ovfl_check;
 #else
                 /* rv = */ rounded_product(rv, tens[e]);
                 goto ret;
 #endif
             }
             i = DBL_DIG - nd;
             if (e <= Ten_pmax + i) {
                 /* A fancier test would sometimes let us do
                  * this for larger i values.
                  */
                 e -= i;
                 rv *= tens[i];
 #ifdef VAX
                 /* VAX exponent range is so narrow we must
                  * worry about overflow here...
                  */
             vax_ovfl_check:
                 setWord0(&rv, getWord0(rv) - P*Exp_msk1);
                 /* rv = */ rounded_product(rv, tens[e]);
                 if ((getWord0(rv) & Exp_mask)
                     > Exp_msk1*(DBL_MAX_EXP+Bias-1-P))
                     goto ovfl;
                 setWord0(&rv, getWord0(rv) + P*Exp_msk1);
 #else
                 /* rv = */ rounded_product(rv, tens[e]);
 #endif
                 goto ret;
             }
         }
 #ifndef Inaccurate_Divide
         else if (e >= -Ten_pmax) {
             /* rv = */ rounded_quotient(rv, tens[-e]);
             goto ret;
         }
 #endif
     }
     e1 += nd - k;
     /* Get starting approximation = rv * 10**e1 */
     if (e1 > 0) {
         if ((i = e1 & 15) != 0)
             rv *= tens[i];
         if (e1 &= ~15) {
             if (e1 > DBL_MAX_10_EXP) {
             ovfl:
                 //                                errno = ERANGE;
                 if (ok != 0)
                     *ok = false;
 #ifdef __STDC__
                 rv = HUGE_VAL;
 #else
                 /* Can't trust HUGE_VAL */
 #ifdef IEEE_Arith
                 setWord0(&rv, Exp_mask);
                 setWord1(&rv, 0);
 #else
                 setWord0(&rv, Big0);
                 setWord1(&rv, Big1);
 #endif
 #endif
                 if (bd0)
                     goto retfree;
                 goto ret;
             }
             if (e1 >>= 4) {
                 for(j = 0; e1 > 1; j++, e1 >>= 1)
                     if (e1 & 1)
                         rv *= bigtens[j];
                 /* The last multiplication could overflow. */
                 setWord0(&rv, getWord0(rv) - P*Exp_msk1);
                 rv *= bigtens[j];
                 if ((z = getWord0(rv) & Exp_mask)
                     > Exp_msk1*(DBL_MAX_EXP+Bias-P))
                     goto ovfl;
                 if (z > Exp_msk1*(DBL_MAX_EXP+Bias-1-P)) {
                     /* set to largest number */
                     /* (Can't trust DBL_MAX) */
                     setWord0(&rv, Big0);
                     setWord1(&rv, Big1);
                 }
                 else
                     setWord0(&rv, getWord0(rv) + P*Exp_msk1);
             }
         }
     }
     else if (e1 < 0) {
         e1 = -e1;
         if ((i = e1 & 15) != 0)
             rv /= tens[i];
         if (e1 &= ~15) {
             e1 >>= 4;
             if (e1 >= 1 << n_bigtens)
                 goto undfl;
             for(j = 0; e1 > 1; j++, e1 >>= 1)
                 if (e1 & 1)
                     rv *= tinytens[j];
             /* The last multiplication could underflow. */
             rv0 = rv;
             rv *= tinytens[j];
             if (rv == g_double_zero)
                 {
                     rv = 2.*rv0;
                     rv *= tinytens[j];
                     if (rv == g_double_zero)
{
                         undfl:
                             rv = 0.;
                             //                                        errno = ERANGE;
                             if (ok != 0)
                                 *ok = false;
                             if (bd0)
                                 goto retfree;
                             goto ret;
                         }
                     setWord0(&rv, Tiny0);
                     setWord1(&rv, Tiny1);
                     /* The refinement below will clean
                      * this approximation up.
                      */
                 }
         }
     }
     /* Now the hard part -- adjusting rv to the correct value.*/
     /* Put digits into bd: true value = bd * 10^e */
     bd0 = s2b(s0, nd0, nd, y);
     for(;;) {
         bd = Balloc(bd0->k);
         Bcopy(bd, bd0);
         bb = d2b(rv, &bbe, &bbbits);        /* rv = bb * 2^bbe */
         bs = i2b(1);
         if (e >= 0) {
             bb2 = bb5 = 0;
             bd2 = bd5 = e;
         }
         else {
             bb2 = bb5 = -e;
             bd2 = bd5 = 0;
         }
         if (bbe >= 0)
             bb2 += bbe;
         else
             bd2 -= bbe;
         bs2 = bb2;
 #ifdef Sudden_Underflow
 #ifdef IBM
         j = 1 + 4*P - 3 - bbbits + ((bbe + bbbits - 1) & 3);
 #else
         j = P + 1 - bbbits;
 #endif
 #else
         i = bbe + bbbits - 1;        /* logb(rv) */
         if (i < Emin)        /* denormal */
             j = bbe + (P-Emin);
         else
             j = P + 1 - bbbits;
 #endif
         bb2 += j;
         bd2 += j;
         i = bb2 < bd2 ? bb2 : bd2;
         if (i > bs2)
             i = bs2;
         if (i > 0) {
             bb2 -= i;
             bd2 -= i;
             bs2 -= i;
         }
         if (bb5 > 0) {
             bs = pow5mult(bs, bb5);
             bb1 = mult(bs, bb);
             Bfree(bb);
             bb = bb1;
         }
         if (bb2 > 0)
             bb = lshift(bb, bb2);
         if (bd5 > 0)
             bd = pow5mult(bd, bd5);
         if (bd2 > 0)
             bd = lshift(bd, bd2);
         if (bs2 > 0)
             bs = lshift(bs, bs2);
         delta = diff(bb, bd);
         dsign = delta->sign;
         delta->sign = 0;
         i = cmp(delta, bs);
         if (i < 0) {
             /* Error is less than half an ulp -- check for
              * special case of mantissa a power of two.
              */
             if (dsign || getWord1(rv) || getWord0(rv) & Bndry_mask)
                 break;
             delta = lshift(delta,Log2P);
             if (cmp(delta, bs) > 0)
                 goto drop_down;
             break;
         }
         if (i == 0) {
             /* exactly half-way between */
             if (dsign) {
                 if ((getWord0(rv) & Bndry_mask1) == Bndry_mask1
                     &&  getWord1(rv) == 0xffffffff) {
                     /*boundary case -- increment exponent*/
                     setWord0(&rv, (getWord0(rv) & Exp_mask)
                                 + Exp_msk1
 #ifdef IBM
                                 | Exp_msk1 >> 4
 #endif
                                 );
                     setWord1(&rv, 0);
                     break;
                 }
             }
             else if (!(getWord0(rv) & Bndry_mask) && !getWord1(rv)) {
             drop_down:
                 /* boundary case -- decrement exponent */
 #ifdef Sudden_Underflow
                 L = getWord0(rv) & Exp_mask;
 #ifdef IBM
                 if (L <  Exp_msk1)
 #else
                     if (L <= Exp_msk1)
 #endif
                         goto undfl;
                 L -= Exp_msk1;
 #else
                 L = (getWord0(rv) & Exp_mask) - Exp_msk1;
 #endif
                 setWord0(&rv, L | Bndry_mask1);
                 setWord1(&rv, 0xffffffff);
 #ifdef IBM
                 goto cont;
 #else
                 break;
 #endif
             }
 #ifndef ROUND_BIASED
             if (!(getWord1(rv) & LSB))
                 break;
 #endif
             if (dsign)
                 rv += ulp(rv);
 #ifndef ROUND_BIASED
             else {
                 rv -= ulp(rv);
 #ifndef Sudden_Underflow
                 if (rv == g_double_zero)
                     goto undfl;
 #endif
             }
 #endif
             break;
         }
         if ((aadj = ratio(delta, bs)) <= 2.) {
             if (dsign)
                 aadj = aadj1 = 1.;
             else if (getWord1(rv) || getWord0(rv) & Bndry_mask) {
 #ifndef Sudden_Underflow
                 if (getWord1(rv) == Tiny1 && !getWord0(rv))
                     goto undfl;
 #endif
                 aadj = 1.;
                 aadj1 = -1.;
             }
             else {
                 /* special case -- power of FLT_RADIX to be */
                 /* rounded down... */
                 if (aadj < 2./FLT_RADIX)
                     aadj = 1./FLT_RADIX;
                 else
                     aadj *= 0.5;
                 aadj1 = -aadj;
             }
         }
         else {
             aadj *= 0.5;
             aadj1 = dsign ? aadj : -aadj;
 #ifdef Check_FLT_ROUNDS
             switch(FLT_ROUNDS) {
             case 2: /* towards +infinity */
                 aadj1 -= 0.5;
                 break;
             case 0: /* towards 0 */
             case 3: /* towards -infinity */
                 aadj1 += 0.5;
             }
 #else
             if (FLT_ROUNDS == 0)
                 aadj1 += 0.5;
 #endif
         }
         y = getWord0(rv) & Exp_mask;
         /* Check for overflow */
         if (y == Exp_msk1*(DBL_MAX_EXP+Bias-1)) {
             rv0 = rv;
             setWord0(&rv, getWord0(rv) - P*Exp_msk1);
             adj = aadj1 * ulp(rv);
             rv += adj;
             if ((getWord0(rv) & Exp_mask) >=
                 Exp_msk1*(DBL_MAX_EXP+Bias-P)) {
                 if (getWord0(rv0) == Big0 && getWord1(rv0) == Big1)
                     goto ovfl;
                 setWord0(&rv, Big0);
                 setWord1(&rv, Big1);
                 goto cont;
             }
             else
                 setWord0(&rv, getWord0(rv) + P*Exp_msk1);
         }
         else {
 #ifdef Sudden_Underflow
             if ((getWord0(rv) & Exp_mask) <= P*Exp_msk1) {
                 rv0 = rv;
                 setWord0(&rv, getWord0(rv) + P*Exp_msk1);
                 adj = aadj1 * ulp(rv);
                 rv += adj;
 #ifdef IBM
                 if ((getWord0(rv) & Exp_mask) <  P*Exp_msk1)
 #else
                     if ((getWord0(rv) & Exp_mask) <= P*Exp_msk1)
 #endif
{
                             if (getWord0(rv0) == Tiny0
                                 && getWord1(rv0) == Tiny1)
                                 goto undfl;
                             setWord0(&rv, Tiny0);
                             setWord1(&rv, Tiny1);
                             goto cont;
                         }
                     else
                         setWord0(&rv, getWord0(rv) - P*Exp_msk1);
             }
             else {
                 adj = aadj1 * ulp(rv);
                 rv += adj;
             }
 #else
             /* Compute adj so that the IEEE rounding rules will
              * correctly round rv + adj in some half-way cases.
              * If rv * ulp(rv) is denormalized (i.e.,
              * y <= (P-1)*Exp_msk1), we must adjust aadj to avoid
              * trouble from bits lost to denormalization;
              * example: 1.2e-307 .
              */
             if (y <= (P-1)*Exp_msk1 && aadj >= 1.) {
                 aadj1 = int(aadj + 0.5);
                 if (!dsign)
                     aadj1 = -aadj1;
             }
             adj = aadj1 * ulp(rv);
             rv += adj;
 #endif
         }
         z = getWord0(rv) & Exp_mask;
         if (y == z) {
             /* Can we stop now? */
             L = Long(aadj);
             aadj -= L;
             /* The tolerances below are conservative. */
             if (dsign || getWord1(rv) || getWord0(rv) & Bndry_mask) {
                 if (aadj < .4999999 || aadj > .5000001)
                     break;
             }
             else if (aadj < .4999999/FLT_RADIX)
                 break;
         }
     cont:
         Bfree(bb);
         Bfree(bd);
         Bfree(bs);
         Bfree(delta);
     }
  retfree:
     Bfree(bb);
     Bfree(bd);
     Bfree(bs);
     Bfree(bd0);
     Bfree(delta);
  ret:
     if (se)
         *se = s;
     return sign ? -rv : rv;
 }
qstrtoll()
qlonglong qstrtoll (const char * nptr, const char ** endptr, register int base, bool * ok)
Definition at line 391 of file qlocale_tools.cpp.
Referenced by QLocalePrivate::bytearrayToLongLong(), getWinLocaleName(), and isZero().
 {
     register const char *s;
     register qulonglong acc;
     register unsigned char c;
     register qulonglong qbase, cutoff;
     register int neg, any, cutlim;
     /*
      * Skip white space and pick up leading +/- sign if any.
      * If base is 0, allow 0x for hex and 0 for octal, else
      * assume decimal; if base is already 16, allow 0x.
      */
     s = nptr;
     do {
         c = *s++;
     } while (isspace(c));
     if (c == '-') {
         neg = 1;
         c = *s++;
     } else {
         neg = 0;
         if (c == '+')
             c = *s++;
     }
     if ((base == 0 || base == 16) &&
         c == '0' && (*s == 'x' || *s == 'X')) {
         c = s[1];
         s += 2;
         base = 16;
     }
     if (base == 0)
         base = c == '0' ? 8 : 10;
     /*
      * Compute the cutoff value between legal numbers and illegal
      * numbers.  That is the largest legal value, divided by the
      * base.  An input number that is greater than this value, if
      * followed by a legal input character, is too big.  One that
      * is equal to this value may be valid or not; the limit
      * between valid and invalid numbers is then based on the last
      * digit.  For instance, if the range for quads is
      * [-9223372036854775808..9223372036854775807] and the input base
      * is 10, cutoff will be set to 922337203685477580 and cutlim to
      * either 7 (neg==0) or 8 (neg==1), meaning that if we have
      * accumulated a value > 922337203685477580, or equal but the
      * next digit is > 7 (or 8), the number is too big, and we will
      * return a range error.
      *
      * Set any if any `digits' consumed; make it negative to indicate
      * overflow.
      */
     qbase = unsigned(base);
     cutoff = neg ? qulonglong(0-(LLONG_MIN + LLONG_MAX)) + LLONG_MAX : LLONG_MAX;
     cutlim = cutoff % qbase;
     cutoff /= qbase;
     for (acc = 0, any = 0;; c = *s++) {
         if (!isascii(c))
             break;
         if (isdigit(c))
             c -= '0';
         else if (isalpha(c))
             c -= isupper(c) ? 'A' - 10 : 'a' - 10;
         else
             break;
         if (c >= base)
             break;
         if (any < 0 || acc > cutoff || (acc == cutoff && c > cutlim))
             any = -1;
         else {
             any = 1;
             acc *= qbase;
             acc += c;
         }
     }
     if (any < 0) {
         acc = neg ? LLONG_MIN : LLONG_MAX;
         if (ok != 0)
             *ok = false;
     } else if (neg) {
         acc = (~acc) + 1;
     }
     if (endptr != 0)
         *endptr = (any >= 0 ? s - 1 : nptr);
     if (ok != 0)
         *ok = any > 0;
     return acc;
 }
qstrtoull()
qulonglong qstrtoull (const char * nptr, const char ** endptr, register int base, bool * ok)
Definition at line 310 of file qlocale_tools.cpp.
Referenced by QLocalePrivate::bytearrayToUnsLongLong(), isZero(), and winIso639LangName().
 {
     register const char *s = nptr;
     register qulonglong acc;
     register unsigned char c;
     register qulonglong qbase, cutoff;
     register int any, cutlim;
     if (ok != 0)
         *ok = true;
     /*
      * See strtoq for comments as to the logic used.
      */
     s = nptr;
     do {
         c = *s++;
     } while (isspace(c));
     if (c == '-') {
         if (ok != 0)
             *ok = false;
         if (endptr != 0)
             *endptr = s - 1;
         return 0;
     } else {
         if (c == '+')
             c = *s++;
     }
     if ((base == 0 || base == 16) &&
         c == '0' && (*s == 'x' || *s == 'X')) {
         c = s[1];
         s += 2;
         base = 16;
     }
     if (base == 0)
         base = c == '0' ? 8 : 10;
     qbase = unsigned(base);
     cutoff = qulonglong(ULLONG_MAX) / qbase;
     cutlim = qulonglong(ULLONG_MAX) % qbase;
     for (acc = 0, any = 0;; c = *s++) {
         if (!isascii(c))
             break;
         if (isdigit(c))
             c -= '0';
         else if (isalpha(c))
             c -= isupper(c) ? 'A' - 10 : 'a' - 10;
         else
             break;
         if (c >= base)
             break;
         if (any < 0 || acc > cutoff || (acc == cutoff && c > cutlim))
             any = -1;
         else {
             any = 1;
             acc *= qbase;
             acc += c;
         }
     }
     if (any == 0) {
         if (ok != 0)
             *ok = false;
     } else if (any < 0) {
         acc = ULLONG_MAX;
         if (ok != 0)
             *ok = false;
     }
     if (endptr != 0)
         *endptr = (any ? s - 1 : nptr);
     return acc;
 }
qulltoa()
QString qulltoa (qulonglong l, int base, const QChar _zero)
Definition at line 79 of file qlocale_tools.cpp.
Referenced by QLocalePrivate::longLongToString(), qlltoa(), and QLocalePrivate::unsLongLongToString().
 {
     ushort buff[65]; // length of MAX_ULLONG in base 2
     ushort *p = buff + 65;
     if (base != 10 || _zero.unicode() == '0') {
         while (l != 0) {
             int c = l % base;
             --p;
             if (c < 10)
                 *p = '0' + c;
             else
                 *p = c - 10 + 'a';
             l /= base;
         }
     }
     else {
         while (l != 0) {
             int c = l % base;
             *(--p) = _zero.unicode() + c;
             l /= base;
         }
     }
     return QString(reinterpret_cast<QChar *>(p), 65 - (p - buff));
 }
removeGroupSeparators()
bool removeGroupSeparators (QLocalePrivate::CharBuff * num)
Definition at line 188 of file qlocale_tools.cpp.
Referenced by isZero(), and QLocalePrivate::numberToCLocale().
 {
     int group_cnt = 0; // counts number of group chars
     int decpt_idx = -1;
     char *data = num->data();
     int l = qstrlen(data);
     // Find the decimal point and check if there are any group chars
     int i = 0;
     for (; i < l; ++i) {
         char c = data[i];
         if (c == ',') {
             if (i == 0 || data[i - 1] < '0' || data[i - 1] > '9')
                 return false;
             if (i == l - 1 || data[i + 1] < '0' || data[i + 1] > '9')
                 return false;
             ++group_cnt;
         }
         else if (c == '.') {
             // Fail if more than one decimal points
             if (decpt_idx != -1)
                 return false;
             decpt_idx = i;
         } else if (c == 'e' || c == 'E') {
             // an 'e' or 'E' - if we have not encountered a decimal
             // point, this is where it "is".
             if (decpt_idx == -1)
                 decpt_idx = i;
         }
     }
     // If no group chars, we're done
     if (group_cnt == 0)
         return true;
     // No decimal point means that it "is" at the end of the string
     if (decpt_idx == -1)
         decpt_idx = l;
     i = 0;
     while (i < l && group_cnt > 0) {
         char c = data[i];
         if (c == ',') {
             // Don't allow group chars after the decimal point
             if (i > decpt_idx)
                 return false;
             // Check that it is placed correctly relative to the decpt
             if ((decpt_idx - i) % 4 != 0)
                 return false;
             // Remove it
             memmove(data + i, data + i + 1, l - i - 1);
             data[--l] = '\0';
             --group_cnt;
             --decpt_idx;
         } else {
             // Check that we are not missing a separator
             if (i < decpt_idx
                     && (decpt_idx - i) % 4 == 0
                     && !(i == 0 && c == '-')) // check for negative sign at start of string
                 return false;
             ++i;
         }
     }
     return true;
 }