Qt 4.8: /src/corelib/tools/qlocale.cpp File Reference
qlocale.cpp File Reference
#include "qglobal.h"
#include "private/qcore_mac_p.h"
#include <CoreFoundation/CoreFoundation.h>
#include "qplatformdefs.h"
#include "qdatastream.h"
#include "qstring.h"
#include "qlocale.h"
#include "qlocale_p.h"
#include "qlocale_tools_p.h"
#include "qdatetime_p.h"
#include "qnamespace.h"
#include "qdatetime.h"
#include "qstringlist.h"
#include "qvariant.h"
#include "qstringbuilder.h"
#include "qt_windows.h"
#include <time.h>
#include "private/qnumeric_p.h"
#include "private/qsystemlibrary_p.h"
#include "qlocale_data_p.h"
Macros
#define QT_MAX_FLOAT 3.4028234663852886e+38
Returns the float represented by the localized string s, or 0.0 if the conversion failed.
Functions
static const QLocalePrivate * dataPointerHelper (quint16 index)
static const QLocalePrivate * defaultPrivate ()
static const QLocalePrivate * findLocale (const QString &name)
static QString getLocaleData (const ushort *data, int size)
static QString getLocaleListData (const ushort *data, int size, int index)
static quint16 localePrivateIndex (const QLocalePrivate *p)
QDataStream & operator<< (QDataStream &ds, const QLocale &l)
QDataStream & operator>> (QDataStream &ds, QLocale &l)
static bool parse_locale_tag (const QString &input, int &i, QString *result, const QString &separators)
static bool qIsUpper (char c)
static QSystemLocale * QSystemLocale_globalSystemLocale ()
QString qt_readEscapedFormatString (const QString &format, int *idx)
int qt_repeatCount (const QString &s, int i)
bool qt_splitLocaleName (const QString &name, QString &lang, QString &script, QString &cntry)
static char qToLower (char c)
static const QSystemLocale * systemLocale ()
static const QLocalePrivate * systemPrivate ()
static bool timeFormatContainsAP (const QString &format)
static QString timeZone ()
Variables
static QSystemLocale * _systemLocale = 0
static const QLocalePrivate * default_lp = 0
static uint default_number_options = 0
static const int locale_data_size = sizeof(locale_data)/sizeof(QLocalePrivate) - 1
static QLocalePrivate * system_lp = 0
Macro Definition Documentation
QT_MAX_FLOAT
#define QT_MAX_FLOAT 3.4028234663852886e+38
Returns the float represented by the localized string s, or 0.0 if the conversion failed.
If ok is not 0, reports failure by setting ok to false and success by setting *ok to true.
This function ignores leading and trailing whitespace.
See also
toDouble(), toInt(), toString()
Definition at line 1242 of file qlocale.cpp.
Referenced by QLocale::toFloat().
Function Documentation
dataPointerHelper()
static const QLocalePrivate* dataPointerHelper (quint16 index) static
Definition at line 598 of file qlocale.cpp.
Referenced by QLocale::d().
 {
 #ifndef QT_NO_SYSTEMLOCALE
     Q_ASSERT(index <= locale_data_size);
     if (index == locale_data_size)
         return system_lp;
 #else
     Q_ASSERT(index < locale_data_size);
 #endif
     return &locale_data[index];
 }
defaultPrivate()
static const QLocalePrivate* defaultPrivate () static
Definition at line 548 of file qlocale.cpp.
Referenced by QLocale::QLocale().
 {
     if (!default_lp)
         default_lp = systemPrivate();
     return default_lp;
 }
findLocale()
static const QLocalePrivate* findLocale (const QString & name) static
Definition at line 377 of file qlocale.cpp.
Referenced by QLocalePrivate::countryId(), and QLocale::QLocale().
 {
     QLocale::Language lang;
     QLocale::Script script;
     QLocale::Country cntry;
     QLocalePrivate::getLangAndCountry(name, lang, script, cntry);
     return QLocalePrivate::findLocale(lang, script, cntry);
 }
getLocaleData()
static QString getLocaleData (const ushort * data, int size) inline static
Definition at line 573 of file qlocale.cpp.
Referenced by QLocale::amText(), QLocale::createSeparatedList(), QLocale::currencySymbol(), QLocale::dateFormat(), QLocale::nativeCountryName(), QLocale::nativeLanguageName(), QLocale::pmText(), QLocale::timeFormat(), and QLocale::toCurrencyString().
 {
     return size ? QString::fromRawData(reinterpret_cast<const QChar*>(data), size) : QString();
 }
getLocaleListData()
static QString getLocaleListData (const ushort * data, int size, int index) static
Definition at line 555 of file qlocale.cpp.
Referenced by QLocale::currencySymbol(), QLocale::dayName(), QLocale::monthName(), QLocale::standaloneDayName(), and QLocale::standaloneMonthName().
 {
     static const ushort separator = ';';
     while (index && size > 0) {
         while (*data != separator)
             ++data, --size;
         --index;
         ++data;
         --size;
     }
     const ushort *end = data;
     while (size > 0 && *end != separator)
         ++end, --size;
     if (end-data == 0)
         return QString();
     return QString::fromRawData(reinterpret_cast<const QChar*>(data), end-data);
 }
localePrivateIndex()
static quint16 localePrivateIndex (const QLocalePrivate * p) static
Definition at line 611 of file qlocale.cpp.
Referenced by QLocale::matchingLocales(), QLocale::QLocale(), and QLocale::system().
 {
 #ifndef QT_NO_SYSTEMLOCALE
     Q_ASSERT((p >= locale_data && p - locale_data < locale_data_size)
              || (p != 0 && p == system_lp));
     quint16 index = p == system_lp ? locale_data_size : p - locale_data;
 #else
     Q_ASSERT(p >= locale_data && p - locale_data < locale_data_size);
     quint16 index = p - locale_data;
 #endif
     return index;
 }
operator<<()
QDataStream& operator<< (QDataStream & ds, const QLocale & l)
Definition at line 580 of file qlocale.cpp.
Referenced by QLocale::toCurrencyString().
 {
     ds << l.name();
     return ds;
 }
operator>>()
QDataStream& operator>> (QDataStream & ds, QLocale & l)
Definition at line 586 of file qlocale.cpp.
Referenced by QLocale::toCurrencyString().
 {
     QString s;
     ds >> s;
     l = QLocale(s);
     return ds;
 }
parse_locale_tag()
static bool parse_locale_tag (const QString & input, int & i, QString * result, const QString & separators) static
Definition at line 282 of file qlocale.cpp.
Referenced by qt_splitLocaleName().
 {
     *result = QString(8, Qt::Uninitialized); // worst case according to BCP47
     QChar *pch = result->data();
     const QChar *uc = input.data() + i;
     const int l = input.length();
     int size = 0;
     for (; i < l && size < 8; ++i, ++size) {
         if (separators.contains(*uc))
             break;
         if (! ((uc->unicode() >= 'a' && uc->unicode() <= 'z') ||
                (uc->unicode() >= 'A' && uc->unicode() <= 'Z') ||
                (uc->unicode() >= '0' && uc->unicode() <= '9')) ) // latin only
             return false;
         *pch++ = *uc++;
     }
     result->truncate(size);
     return true;
 }
qIsUpper()
static bool qIsUpper (char c) static
Definition at line 1848 of file qlocale.cpp.
Referenced by QLocale::toString().
 {
     return c >= 'A' && c <= 'Z';
 }
QSystemLocale_globalSystemLocale()
static QSystemLocale* QSystemLocale_globalSystemLocale () static
Referenced by systemLocale().
qt_readEscapedFormatString()
QString qt_readEscapedFormatString (const QString & format, int * idx)
Definition at line 387 of file qlocale.cpp.
Referenced by QLocalePrivate::dateTimeToString(), QLocalePrivate::digitToCLocale(), macToQtFormat(), timeFormatContainsAP(), and QSystemLocalePrivate::winToQtFormat().
 {
     int &i = *idx;
     Q_ASSERT(format.at(i) == QLatin1Char('\''));
     ++i;
     if (i == format.size())
         return QString();
     if (format.at(i).unicode() == '\'') { // "''" outside of a quoted stirng
         ++i;
         return QLatin1String("'");
     }
     QString result;
     while (i < format.size()) {
         if (format.at(i).unicode() == '\'') {
             if (i + 1 < format.size() && format.at(i + 1).unicode() == '\'') {
                 // "''" inside of a quoted string
                 result.append(QLatin1Char('\''));
                 i += 2;
             } else {
                 break;
             }
         } else {
             result.append(format.at(i++));
         }
     }
     if (i < format.size())
         ++i;
     return result;
 }
qt_repeatCount()
int qt_repeatCount (const QString & s, int i)
Definition at line 421 of file qlocale.cpp.
Referenced by QLocalePrivate::dateTimeToString(), QLocalePrivate::digitToCLocale(), macToQtFormat(), and QSystemLocalePrivate::winToQtFormat().
 {
     QChar c = s.at(i);
     int j = i + 1;
     while (j < s.size() && s.at(j) == c)
         ++j;
     return j - i;
 }
qt_splitLocaleName()
bool qt_splitLocaleName (const QString & name, QString & lang, QString & script, QString & cntry)
Definition at line 302 of file qlocale.cpp.
Referenced by QLocalePrivate::digitToCLocale(), QLocalePrivate::getLangAndCountry(), getMacLocaleName(), and getWinLocaleName().
 {
     const int length = name.length();
     lang = script = cntry = QString();
     const QString separators = QLatin1String("_-.@");
     enum ParserState { NoState, LangState, ScriptState, CountryState };
     ParserState state = LangState;
     for (int i = 0; i < length && state != NoState; ) {
         QString value;
         if (!parse_locale_tag(name, i, &value, separators) ||value.isEmpty())
             break;
         QChar sep = i < length ? name.at(i) : QChar();
         switch (state) {
         case LangState:
             if (!sep.isNull() && !separators.contains(sep)) {
                 state = NoState;
                 break;
             }
             lang = value;
             if (i == length) {
                 // just language was specified
                 state = NoState;
                 break;
             }
             state = ScriptState;
             break;
         case ScriptState: {
             QString scripts = QString::fromLatin1((const char *)script_code_list, sizeof(script_code_list));
             if (value.length() == 4 && scripts.indexOf(value) % 4 == 0) {
                 // script name is always 4 characters
                 script = value;
                 state = CountryState;
             } else {
                 // it wasn't a script, maybe it is a country then?
                 cntry = value;
                 state = NoState;
             }
             break;
         }
         case CountryState:
             cntry = value;
             state = NoState;
             break;
         case NoState:
             // shouldn't happen
             qWarning("QLocale: This should never happen");
             break;
         }
         ++i;
     }
     return lang.length() == 2 || lang.length() == 3;
 }
qToLower()
static char qToLower (char c) static
Definition at line 1853 of file qlocale.cpp.
Referenced by QLocale::toString().
 {
     if (c >= 'A' && c <= 'Z')
         return c - 'A' + 'a';
     else
         return c;
 }
systemLocale()
static const QSystemLocale* systemLocale () static
Definition at line 471 of file qlocale.cpp.
Referenced by QLocale::amText(), QLocale::createSeparatedList(), QLocale::currencySymbol(), QLocale::dateFormat(), QLocale::dateTimeFormat(), QLocale::dayName(), QLocale::firstDayOfWeek(), QLocale::measurementSystem(), QLocale::monthName(), QLocale::nativeCountryName(), QLocale::nativeLanguageName(), QLocale::pmText(), QHttpNetworkConnectionPrivate::prepareRequest(), QLocale::quoteString(), QLocale::standaloneDayName(), QLocale::standaloneMonthName(), QLocale::timeFormat(), QLocale::toCurrencyString(), QLocale::toString(), QLocale::uiLanguages(), QLocalePrivate::updateSystemPrivate(), and QLocale::weekdays().
 {
     if (_systemLocale)
         return _systemLocale;
     return QSystemLocale_globalSystemLocale();
 }
systemPrivate()
static const QLocalePrivate* systemPrivate () static
Definition at line 535 of file qlocale.cpp.
Referenced by QLocale::amText(), QLocale::createSeparatedList(), QLocale::currencySymbol(), QLocale::dateFormat(), QLocale::dateTimeFormat(), QLocale::dayName(), defaultPrivate(), QLocale::firstDayOfWeek(), QLocale::measurementSystem(), QLocale::monthName(), QLocale::nativeCountryName(), QLocale::nativeLanguageName(), QLocale::pmText(), QLocale::quoteString(), QLocale::standaloneDayName(), QLocale::standaloneMonthName(), QLocale::system(), QLocale::timeFormat(), QLocale::toCurrencyString(), QLocale::toString(), QLocale::uiLanguages(), and QLocale::weekdays().
 {
 #ifndef QT_NO_SYSTEMLOCALE
     // copy over the information from the fallback locale and modify
     if (!system_lp || system_lp->m_language_id == 0)
         QLocalePrivate::updateSystemPrivate();
     return system_lp;
 #else
     return locale_data;
 #endif
 }
timeFormatContainsAP()
static bool timeFormatContainsAP (const QString & format) static
Definition at line 1354 of file qlocale.cpp.
Referenced by QLocalePrivate::dateTimeToString().
 {
     int i = 0;
     while (i < format.size()) {
         if (format.at(i).unicode() == '\'') {
             qt_readEscapedFormatString(format, &i);
             continue;
         }
         if (format.at(i).toLower().unicode() == 'a')
             return true;
         ++i;
     }
     return false;
 }
timeZone()
static QString timeZone () static
Definition at line 1371 of file qlocale.cpp.
Referenced by QLocalePrivate::dateTimeToString().
 {
 #if defined(Q_OS_WINCE)
     TIME_ZONE_INFORMATION info;
     DWORD res = GetTimeZoneInformation(&info);
     if (res == TIME_ZONE_ID_UNKNOWN)
         return QString();
     return QString::fromWCharArray(info.StandardName);
 #elif defined(Q_OS_WIN)
     _tzset();
 # if defined(_MSC_VER) && _MSC_VER >= 1400
     size_t returnSize = 0;
     char timeZoneName[512];
     if (_get_tzname(&returnSize, timeZoneName, 512, 1))
         return QString();
     return QString::fromLocal8Bit(timeZoneName);
 # else
     return QString::fromLocal8Bit(_tzname[1]);
 # endif
 #elif defined(Q_OS_VXWORKS)
     return QString();
 #else
     tzset();
     return QString::fromLocal8Bit(tzname[1]);
 #endif
 }
Variable Documentation
_systemLocale
QSystemLocale* _systemLocale = 0 static
Definition at line 83 of file qlocale.cpp.
Referenced by QSystemLocale::QSystemLocale(), and systemLocale().
default_lp
const QLocalePrivate* default_lp = 0 static
Definition at line 430 of file qlocale.cpp.
Referenced by defaultPrivate().
default_number_options
uint default_number_options = 0 static
Definition at line 431 of file qlocale.cpp.
Referenced by QLocale::QLocale().
locale_data_size
const int locale_data_size = sizeof(locale_data)/sizeof(QLocalePrivate) - 1 static
Definition at line 596 of file qlocale.cpp.
Referenced by localePrivateIndex().
system_lp
QLocalePrivate* system_lp = 0 static
Definition at line 85 of file qlocale.cpp.
Referenced by dataPointerHelper(), and systemPrivate().