Qt 4.8: /src/gui/styles/qmacstyle_mac.mm File Reference
qmacstyle_mac.mm File Reference
#include "qmacstyle_mac.h"
#include <private/qapplication_p.h>
#include <private/qcombobox_p.h>
#include <private/qmacstylepixmaps_mac_p.h>
#include <private/qpaintengine_mac_p.h>
#include <private/qpainter_p.h>
#include <private/qprintengine_mac_p.h>
#include <qapplication.h>
#include <qbitmap.h>
#include <qcheckbox.h>
#include <qcombobox.h>
#include <qdialogbuttonbox.h>
#include <qdockwidget.h>
#include <qevent.h>
#include <qfocusframe.h>
#include <qformlayout.h>
#include <qgroupbox.h>
#include <qhash.h>
#include <qheaderview.h>
#include <qlayout.h>
#include <qlineedit.h>
#include <qlistview.h>
#include <qmainwindow.h>
#include <qmap.h>
#include <qmenubar.h>
#include <qpaintdevice.h>
#include <qpainter.h>
#include <qpixmapcache.h>
#include <qpointer.h>
#include <qprogressbar.h>
#include <qpushbutton.h>
#include <qradiobutton.h>
#include <qrubberband.h>
#include <qsizegrip.h>
#include <qspinbox.h>
#include <qsplitter.h>
#include <qstyleoption.h>
#include <qtextedit.h>
#include <qtextstream.h>
#include <qtoolbar.h>
#include <qtoolbutton.h>
#include <qtreeview.h>
#include <qtableview.h>
#include <qwizard.h>
#include <qdebug.h>
#include <qlibrary.h>
#include <qdatetimeedit.h>
#include <qmath.h>
#include <QtGui/qgraphicsproxywidget.h>
#include <QtGui/qgraphicsview.h>
#include <private/qt_cocoa_helpers_mac_p.h>
#include "qmacstyle_mac_p.h"
#include <private/qstylehelper_p.h>
#include "moc_qmacstyle_mac.cpp"
#include "moc_qmacstyle_mac_p.cpp"
Macros
#define QMAC_QAQUASTYLE_SIZE_CONSTRAIN
Typedefs
typedef HIRect *(* PtrHIShapeGetBounds) (HIShapeRef, HIRect *)
Enumerations
enum ScrollBarCutoffType { thumbIndicatorCutoff = 0, scrollButtonsCutoff = 1 }
Functions
static QPixmap darkenPixmap (const QPixmap &pixmap)
void drawTabBase (QPainter *p, const QStyleOptionTabBarBaseV2 *tbb, const QWidget *w)
void drawTabCloseButton (QPainter *p, bool hover, bool active, bool selected)
void drawTabShape (QPainter *p, const QStyleOptionTabV3 *tabOpt)
static void drawToolbarButtonArrow (const QRect &toolButtonRect, ThemeDrawState tds, CGContextRef cg)
static int getControlSize (const QStyleOption *option, const QWidget *widget)
static ThemeTabDirection getTabDirection (QTabBar::Shape shape)
static bool isTreeView (const QWidget *widget)
static bool isVerticalTabs (const QTabBar::Shape shape)
static QSize qt_aqua_get_known_size (QStyle::ContentsType ct, const QWidget *widg, QSize szHint, QAquaWidgetSize sz)
static QAquaWidgetSize qt_aqua_guess_size (const QWidget *widg, QSize large, QSize small, QSize mini)
static HIRect qt_hirectForQRect (const QRect &convertRect, const QRect &rect=QRect())
static int qt_mac_aqua_get_metric (ThemeMetric met)
bool qt_mac_buttonIsRenderedFlat (const QPushButton *pushButton, const QStyleOptionButton *option)
CGContextRef qt_mac_cg_context (const QPaintDevice *)
Returns the CoreGraphics CGContextRef of the paint device.
QRegion qt_mac_convert_mac_region (RgnHandle)
QRegion qt_mac_convert_mac_region (HIShapeRef)
void qt_mac_dispose_rgn (RgnHandle r)
void qt_mac_fill_background (QPainter *painter, const QRegion &rgn, const QBrush &brush)
static int qt_mac_hitheme_tab_version ()
bool qt_mac_is_metal (const QWidget *w)
QString qt_mac_removeMnemonics (const QString &original)
static const QRect qt_qrectForHIRect (const HIRect &hirect)
QRect rotateTabPainter (QPainter *p, QTabBar::Shape shape, QRect tabRect)
static int scrollButtonsCutoffSize (ScrollBarCutoffType cutoffType, QMacStyle::WidgetSizePolicy widgetSize)
static void setLayoutItemMargins (int left, int top, int right, int bottom, QRect *rect, Qt::LayoutDirection dir)
Variables
static int closeButtonSize = 12
static const int DisclosureOffset = 4
const int macItemFrame = 2
const int macItemHMargin = 3
const int macItemVMargin = 2
const int macRightBorder = 12
static const QColor mainWindowGradientBegin (240, 240, 240)
static const QColor mainWindowGradientEnd (200, 200, 200)
static PtrHIShapeGetBounds ptrHIShapeGetBounds = 0
QPixmap * qt_mac_backgroundPattern = 0
const int qt_mac_hitheme_version = 0
QPaintDevice * qt_mac_safe_pdev
const ThemeWindowType QtWinType = kThemeDocumentWindow
static const QColor titlebarGradientActiveBegin (220, 220, 220)
static const QColor titlebarGradientActiveEnd (151, 151, 151)
static const QColor titlebarGradientInactiveBegin (241, 241, 241)
static const QColor titlebarGradientInactiveEnd (207, 207, 207)
static const QColor titlebarSeparatorLineActive (111, 111, 111)
static const QColor titlebarSeparatorLineInactive (131, 131, 131)
Macro Definition Documentation
QMAC_QAQUASTYLE_SIZE_CONSTRAIN
#define QMAC_QAQUASTYLE_SIZE_CONSTRAIN
Definition at line 50 of file qmacstyle_mac.mm.
Typedef Documentation
PtrHIShapeGetBounds
typedef HIRect*(* PtrHIShapeGetBounds) (HIShapeRef, HIRect *)
Definition at line 137 of file qmacstyle_mac.mm.
Enumeration Type Documentation
ScrollBarCutoffType
enum ScrollBarCutoffType
Enumerator
thumbIndicatorCutoff
scrollButtonsCutoff
Definition at line 1344 of file qmacstyle_mac.mm.
 { thumbIndicatorCutoff = 0, scrollButtonsCutoff = 1 };
Function Documentation
darkenPixmap()
static QPixmap darkenPixmap (const QPixmap & pixmap) inline static
Definition at line 3142 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawControl().
 {
     QImage img = pixmap.toImage().convertToFormat(QImage::Format_ARGB32);
     int imgh = img.height();
     int imgw = img.width();
     int h, s, v, a;
     QRgb pixel;
     for (int y = 0; y < imgh; ++y) {
         for (int x = 0; x < imgw; ++x) {
             pixel = img.pixel(x, y);
             a = qAlpha(pixel);
             QColor hsvColor(pixel);
             hsvColor.getHsv(&h, &s, &v);
             s = qMin(100, s * 2);
             v = v / 2;
             hsvColor.setHsv(h, s, v);
             pixel = hsvColor.rgb();
             img.setPixel(x, y, qRgba(qRed(pixel), qGreen(pixel), qBlue(pixel), a));
         }
     }
     return QPixmap::fromImage(img);
 }
drawTabBase()
void drawTabBase (QPainter * p, const QStyleOptionTabBarBaseV2 * tbb, const QWidget * w)
Definition at line 312 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawPrimitive().
 {
     QRect r = tbb->rect;
     if (isVerticalTabs(tbb->shape)) {
         r.setWidth(w->width());
     } else {
         r.setHeight(w->height());
     }
     QRect tabRect = rotateTabPainter(p, tbb->shape, r);
     int width = tabRect.width();
     int height = tabRect.height();
     bool active = (tbb->state & QStyle::State_Active);
     // top border lines
     QColor borderHighlightTop;
     QColor borderTop;
     if (active) {
         borderTop = QColor(64, 64, 64);
         borderHighlightTop = QColor(174, 174, 174);
     } else {
         borderTop = QColor(135, 135, 135);
         borderHighlightTop = QColor(207, 207, 207);
     }
     p->setPen(borderHighlightTop);
     p->drawLine(tabRect.x(), 0, width, 0);
     p->setPen(borderTop);
     p->drawLine(tabRect.x(), 1, width, 1);
     // center block
     QRect centralRect(tabRect.x(), 2, width, height - 2);
     if (active) {
         QColor mainColor = QColor(120, 120, 120);
         p->fillRect(centralRect, mainColor);
     } else {
         QLinearGradient gradient(centralRect.topLeft(), centralRect.bottomLeft());
         gradient.setColorAt(0, QColor(165, 165, 165));
         gradient.setColorAt(0.5, QColor(164, 164, 164));
         gradient.setColorAt(1, QColor(158, 158, 158));
         p->fillRect(centralRect, gradient);
     }
     // bottom border lines
     QColor borderHighlightBottom;
     QColor borderBottom;
     if (active) {
         borderHighlightBottom = QColor(153, 153, 153);
         borderBottom = QColor(64, 64, 64);
     } else {
         borderHighlightBottom = QColor(177, 177, 177);
         borderBottom = QColor(127, 127, 127);
     }
     p->setPen(borderHighlightBottom);
     p->drawLine(tabRect.x(), height - 2, width, height - 2);
     p->setPen(borderBottom);
     p->drawLine(tabRect.x(), height - 1, width, height - 1);
 }
drawTabCloseButton()
void drawTabCloseButton (QPainter * p, bool hover, bool active, bool selected)
Definition at line 151 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawPrimitive().
 {
     // draw background circle
     p->setRenderHints(QPainter::Antialiasing);
     QRect rect(0, 0, closeButtonSize, closeButtonSize);
     QColor background;
     if (hover) {
         background = QColor(124, 124, 124);
     } else {
         if (active) {
             if (selected)
                 background = QColor(104, 104, 104);
             else
                 background = QColor(83, 83, 83);
         } else {
             if (selected)
                 background = QColor(144, 144, 144);
             else
                 background = QColor(114, 114, 114);
         }
     }
     p->setPen(Qt::transparent);
     p->setBrush(background);
     p->drawEllipse(rect);
     // draw cross
     int min = 3;
     int max = 9;
     QPen crossPen;
     crossPen.setColor(QColor(194, 194, 194));
     crossPen.setWidthF(1.3);
     crossPen.setCapStyle(Qt::FlatCap);
     p->setPen(crossPen);
     p->drawLine(min, min, max, max);
     p->drawLine(min, max, max, min);
 }
drawTabShape()
void drawTabShape (QPainter * p, const QStyleOptionTabV3 * tabOpt)
Definition at line 211 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawControl().
 {
     QRect r = tabOpt->rect;
     p->translate(tabOpt->rect.x(), tabOpt->rect.y());
     r.moveLeft(0);
     r.moveTop(0);
     QRect tabRect = rotateTabPainter(p, tabOpt->shape, r);
     int width = tabRect.width();
     int height = 20;
     bool active = (tabOpt->state & QStyle::State_Active);
     bool selected = (tabOpt->state & QStyle::State_Selected);
     if (selected) {
         QRect rect(1, 0, width - 2, height);
         // fill body
         if (active) {
             int d = (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_6) ? 16 : 0;
             p->fillRect(rect, QColor(151 + d, 151 + d, 151 + d));
         } else {
             int d = (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_6) ? 9 : 0;
             QLinearGradient gradient(rect.topLeft(), rect.bottomLeft());
             gradient.setColorAt(0, QColor(207 + d, 207 + d, 207 + d));
             gradient.setColorAt(0.5, QColor(206 + d, 206 + d, 206 + d));
             gradient.setColorAt(1, QColor(201 + d, 201 + d, 201 + d));
             p->fillRect(rect, gradient);
         }
         // draw border
         QColor borderSides;
         QColor borderBottom;
         if (active) {
             borderSides = QColor(88, 88, 88);
             borderBottom = QColor(88, 88, 88);
         } else {
             borderSides = QColor(121, 121, 121);
             borderBottom = QColor(116, 116, 116);
         }
         p->setPen(borderSides);
         int bottom = height;
         // left line
         p->drawLine(0, 1, 0, bottom-2);
         // right line
         p->drawLine(width-1, 1, width-1, bottom-2);
         // bottom line
         if (active) {
             p->setPen(QColor(168, 168, 168));
             p->drawLine(3, bottom-1, width-3, bottom-1);
         }
         p->setPen(borderBottom);
         p->drawLine(2, bottom, width-2, bottom);
         int w = 3;
         QRectF rectangleLeft(1, height - w, w, w);
         QRectF rectangleRight(width - 2, height - 1, w, w);
         int startAngle = 180 * 16;
         int spanAngle = 90 * 16;
         p->setRenderHint(QPainter::Antialiasing);
         p->drawArc(rectangleLeft, startAngle, spanAngle);
         p->drawArc(rectangleRight, startAngle, -spanAngle);
     } else {
         // when the mouse is over non selected tabs they get a new color
         bool hover = (tabOpt->state & QStyle::State_MouseOver);
         if (hover) {
             QRect rect(1, 2, width - 1, height - 1);
             p->fillRect(rect, QColor(110, 110, 110));
         }
         // seperator lines between tabs
         bool west = (tabOpt->shape == QTabBar::RoundedWest || tabOpt->shape == QTabBar::TriangularWest);
         bool drawOnRight = !west;
         if ((!drawOnRight && tabOpt->selectedPosition != QStyleOptionTab::NextIsSelected)
             || (drawOnRight && tabOpt->selectedPosition != QStyleOptionTab::NextIsSelected)) {
             QColor borderColor;
             QColor borderHighlightColor;
             if (active) {
                 borderColor = QColor(64, 64, 64);
                 borderHighlightColor = QColor(140, 140, 140);
             } else {
                 borderColor = QColor(135, 135, 135);
                 borderHighlightColor = QColor(178, 178, 178);
             }
             int x = drawOnRight ? width : 0;
             // tab seperator line
             p->setPen(borderColor);
             p->drawLine(x, 2, x, height + 1);
             // tab seperator highlight
             p->setPen(borderHighlightColor);
             p->drawLine(x-1, 2, x-1, height + 1);
             p->drawLine(x+1, 2, x+1, height + 1);
         }
     }
 }
drawToolbarButtonArrow()
static void drawToolbarButtonArrow (const QRect & toolButtonRect, ThemeDrawState tds, CGContextRef cg) inline static
Definition at line 4650 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawComplexControl().
 {
     QRect arrowRect = QRect(toolButtonRect.right() - 9, toolButtonRect.bottom() - 9, 7, 5);
     HIThemePopupArrowDrawInfo padi;
     padi.version = qt_mac_hitheme_version;
     padi.state = tds;
     padi.orientation = kThemeArrowDown;
     padi.size = kThemeArrow7pt;
     HIRect hirect = qt_hirectForQRect(arrowRect);
     HIThemeDrawPopupArrow(&hirect, &padi, cg, kHIThemeOrientationNormal);
 }
getControlSize()
static int getControlSize (const QStyleOption * option, const QWidget * widget) static
Definition at line 369 of file qmacstyle_mac.mm.
Referenced by QMacStyle::layoutSpacingImplementation(), QMacStyle::pixelMetric(), and QMacStyle::subElementRect().
 {
     if (option) {
         if (option->state & (QStyle::State_Small | QStyle::State_Mini))
             return (option->state & QStyle::State_Mini) ? QAquaSizeMini : QAquaSizeSmall;
     } else if (widget) {
         switch (QMacStyle::widgetSizePolicy(widget)) {
         case QMacStyle::SizeSmall:
             return QAquaSizeSmall;
         case QMacStyle::SizeMini:
             return QAquaSizeMini;
         default:
             break;
         }
     }
     return QAquaSizeLarge;
 }
getTabDirection()
static ThemeTabDirection getTabDirection (QTabBar::Shape shape) inline static
Definition at line 421 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawControl(), QMacStyle::drawPrimitive(), QMacStyle::sizeFromContents(), and QMacStyle::subElementRect().
 {
     ThemeTabDirection ttd;
     switch (shape) {
     case QTabBar::RoundedSouth:
     case QTabBar::TriangularSouth:
         ttd = kThemeTabSouth;
         break;
     default:  // Added to remove the warning, since all values are taken care of, really!
     case QTabBar::RoundedNorth:
     case QTabBar::TriangularNorth:
         ttd = kThemeTabNorth;
         break;
     case QTabBar::RoundedWest:
     case QTabBar::TriangularWest:
         ttd = kThemeTabWest;
         break;
     case QTabBar::RoundedEast:
     case QTabBar::TriangularEast:
         ttd = kThemeTabEast;
         break;
     }
     return ttd;
 }
isTreeView()
static bool isTreeView (const QWidget * widget) inline static
Definition at line 388 of file qmacstyle_mac.mm.
Referenced by qt_aqua_get_known_size().
 {
     return (widget && widget->parentWidget() &&
             (qobject_cast<const QTreeView *>(widget->parentWidget())
 #ifdef QT3_SUPPORT
              || widget->parentWidget()->inherits("Q3ListView")
 #endif
              ));
 }
isVerticalTabs()
static bool isVerticalTabs (const QTabBar::Shape shape) static
Definition at line 144 of file qmacstyle_mac.mm.
Referenced by drawTabBase(), and rotateTabPainter().
{
     return (shape == QTabBar::RoundedEast
                 || shape == QTabBar::TriangularEast
                 || shape == QTabBar::RoundedWest
                 || shape == QTabBar::TriangularWest);
 }
qt_aqua_get_known_size()
static QSize qt_aqua_get_known_size (QStyle::ContentsType ct, const QWidget * widg, QSize szHint, QAquaWidgetSize sz) static
Definition at line 511 of file qmacstyle_mac.mm.
Referenced by QMacStylePrivate::aquaSizeConstrain(), and QMacStyle::pixelMetric().
 {
     QSize ret(-1, -1);
     if (sz != QAquaSizeSmall && sz != QAquaSizeLarge && sz != QAquaSizeMini) {
         qDebug("Not sure how to return this...");
         return ret;
     }
     if ((widg && widg->testAttribute(Qt::WA_SetFont)) || !QApplication::desktopSettingsAware()) {
         // If you're using a custom font and it's bigger than the default font,
         // then no constraints for you. If you are smaller, we can try to help you out
         QFont font = qt_app_fonts_hash()->value(widg->metaObject()->className(), QFont());
         if (widg->font().pointSize() > font.pointSize())
             return ret;
     }
     if (ct == QStyle::CT_CustomBase && widg) {
         if (qobject_cast<const QPushButton *>(widg))
             ct = QStyle::CT_PushButton;
         else if (qobject_cast<const QRadioButton *>(widg))
             ct = QStyle::CT_RadioButton;
         else if (qobject_cast<const QCheckBox *>(widg))
             ct = QStyle::CT_CheckBox;
         else if (qobject_cast<const QComboBox *>(widg))
             ct = QStyle::CT_ComboBox;
         else if (qobject_cast<const QToolButton *>(widg))
             ct = QStyle::CT_ToolButton;
         else if (qobject_cast<const QSlider *>(widg))
             ct = QStyle::CT_Slider;
         else if (qobject_cast<const QProgressBar *>(widg))
             ct = QStyle::CT_ProgressBar;
         else if (qobject_cast<const QLineEdit *>(widg))
             ct = QStyle::CT_LineEdit;
         else if (qobject_cast<const QHeaderView *>(widg)
 #ifdef QT3_SUPPORT
                  || widg->inherits("Q3Header")
 #endif
                 )
             ct = QStyle::CT_HeaderSection;
         else if (qobject_cast<const QMenuBar *>(widg)
 #ifdef QT3_SUPPORT
                 || widg->inherits("Q3MenuBar")
 #endif
                )
             ct = QStyle::CT_MenuBar;
         else if (qobject_cast<const QSizeGrip *>(widg))
             ct = QStyle::CT_SizeGrip;
         else
             return ret;
     }
     switch (ct) {
     case QStyle::CT_PushButton: {
         const QPushButton *psh = qobject_cast<const QPushButton *>(widg);
         // If this comparison is false, then the widget was not a push button.
         // This is bad and there's very little we can do since we were requested to find a
         // sensible size for a widget that pretends to be a QPushButton but is not.
         if(psh) {
             QString buttonText = qt_mac_removeMnemonics(psh->text());
             if (buttonText.contains(QLatin1Char('\n')))
                 ret = QSize(-1, -1);
             else if (sz == QAquaSizeLarge)
                 ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricPushButtonHeight));
             else if (sz == QAquaSizeSmall)
                 ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricSmallPushButtonHeight));
             else if (sz == QAquaSizeMini)
                 ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricMiniPushButtonHeight));
             if (!psh->icon().isNull()){
                 // If the button got an icon, and the icon is larger than the
                 // button, we can't decide on a default size
                 ret.setWidth(-1);
                 if (ret.height() < psh->iconSize().height())
                     ret.setHeight(-1);
             }
             else if (buttonText == QLatin1String("OK") || buttonText == QLatin1String("Cancel")){
                 // Aqua Style guidelines restrict the size of OK and Cancel buttons to 68 pixels.
                 // However, this doesn't work for German, therefore only do it for English,
                 // I suppose it would be better to do some sort of lookups for languages
                 // that like to have really long words.
                 ret.setWidth(77 - 8);
             }
         } else {
             // The only sensible thing to do is to return whatever the style suggests...
             if (sz == QAquaSizeLarge)
                 ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricPushButtonHeight));
             else if (sz == QAquaSizeSmall)
                 ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricSmallPushButtonHeight));
             else if (sz == QAquaSizeMini)
                 ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricMiniPushButtonHeight));
             else
                 // Since there's no default size we return the large size...
                 ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricPushButtonHeight));
          }
 #if 0 //Not sure we are applying the rules correctly for RadioButtons/CheckBoxes --Sam
     } else if (ct == QStyle::CT_RadioButton) {
         QRadioButton *rdo = static_cast<QRadioButton *>(widg);
         // Exception for case where multiline radio button text requires no size constrainment
         if (rdo->text().find('\n') != -1)
             return ret;
         if (sz == QAquaSizeLarge)
             ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricRadioButtonHeight));
         else if (sz == QAquaSizeSmall)
             ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricSmallRadioButtonHeight));
         else if (sz == QAquaSizeMini)
             ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricMiniRadioButtonHeight));
     } else if (ct == QStyle::CT_CheckBox) {
         if (sz == QAquaSizeLarge)
             ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricCheckBoxHeight));
         else if (sz == QAquaSizeSmall)
             ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricSmallCheckBoxHeight));
         else if (sz == QAquaSizeMini)
             ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricMiniCheckBoxHeight));
 #endif
         break;
     }
     case QStyle::CT_SizeGrip:
         if (sz == QAquaSizeLarge || sz == QAquaSizeSmall) {
             HIRect r;
             HIPoint p = { 0, 0 };
             HIThemeGrowBoxDrawInfo gbi;
             gbi.version = 0;
             gbi.state = kThemeStateActive;
             gbi.kind = kHIThemeGrowBoxKindNormal;
             gbi.direction = QApplication::isRightToLeft() ? kThemeGrowLeft | kThemeGrowDown
                                                           : kThemeGrowRight | kThemeGrowDown;
             gbi.size = sz == QAquaSizeSmall ? kHIThemeGrowBoxSizeSmall : kHIThemeGrowBoxSizeNormal;
             if (HIThemeGetGrowBoxBounds(&p, &gbi, &r) == noErr)
                 ret = QSize(r.size.width, r.size.height);
         }
         break;
     case QStyle::CT_ComboBox:
         switch (sz) {
         case QAquaSizeLarge:
             ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricPopupButtonHeight));
             break;
         case QAquaSizeSmall:
             ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricSmallPopupButtonHeight));
             break;
         case QAquaSizeMini:
             ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricMiniPopupButtonHeight));
             break;
         default:
             break;
         }
         break;
     case QStyle::CT_ToolButton:
         if (sz == QAquaSizeSmall) {
             int width = 0, height = 0;
             if (szHint == QSize(-1, -1)) { //just 'guess'..
                 const QToolButton *bt = qobject_cast<const QToolButton *>(widg);
                 // If this conversion fails then the widget was not what it claimed to be.
                 if(bt) {
                     if (!bt->icon().isNull()) {
                         QSize iconSize = bt->iconSize();
                         QSize pmSize = bt->icon().actualSize(QSize(32, 32), QIcon::Normal);
                         width = qMax(width, qMax(iconSize.width(), pmSize.width()));
                         height = qMax(height, qMax(iconSize.height(), pmSize.height()));
                     }
                     if (!bt->text().isNull() && bt->toolButtonStyle() != Qt::ToolButtonIconOnly) {
                         int text_width = bt->fontMetrics().width(bt->text()),
                            text_height = bt->fontMetrics().height();
                         if (bt->toolButtonStyle() == Qt::ToolButtonTextUnderIcon) {
                             width = qMax(width, text_width);
                             height += text_height;
                         } else {
                             width += text_width;
                             width = qMax(height, text_height);
                         }
                     }
                 } else {
                     // Let's return the size hint...
                     width = szHint.width();
                     height = szHint.height();
                 }
             } else {
                 width = szHint.width();
                 height = szHint.height();
             }
             width =  qMax(20, width +  5); //border
             height = qMax(20, height + 5); //border
             ret = QSize(width, height);
         }
         break;
     case QStyle::CT_Slider: {
         int w = -1;
         const QSlider *sld = qobject_cast<const QSlider *>(widg);
         // If this conversion fails then the widget was not what it claimed to be.
         if(sld) {
             if (sz == QAquaSizeLarge) {
                 if (sld->orientation() == Qt::Horizontal) {
                     w = qt_mac_aqua_get_metric(kThemeMetricHSliderHeight);
                     if (sld->tickPosition() != QSlider::NoTicks)
                         w += qt_mac_aqua_get_metric(kThemeMetricHSliderTickHeight);
                 } else {
                     w = qt_mac_aqua_get_metric(kThemeMetricVSliderWidth);
                     if (sld->tickPosition() != QSlider::NoTicks)
                         w += qt_mac_aqua_get_metric(kThemeMetricVSliderTickWidth);
                 }
             } else if (sz == QAquaSizeSmall) {
                 if (sld->orientation() == Qt::Horizontal) {
                     w = qt_mac_aqua_get_metric(kThemeMetricSmallHSliderHeight);
                     if (sld->tickPosition() != QSlider::NoTicks)
                         w += qt_mac_aqua_get_metric(kThemeMetricSmallHSliderTickHeight);
                 } else {
                     w = qt_mac_aqua_get_metric(kThemeMetricSmallVSliderWidth);
                     if (sld->tickPosition() != QSlider::NoTicks)
                         w += qt_mac_aqua_get_metric(kThemeMetricSmallVSliderTickWidth);
                 }
             } else if (sz == QAquaSizeMini) {
                 if (sld->orientation() == Qt::Horizontal) {
                     w = qt_mac_aqua_get_metric(kThemeMetricMiniHSliderHeight);
                     if (sld->tickPosition() != QSlider::NoTicks)
                         w += qt_mac_aqua_get_metric(kThemeMetricMiniHSliderTickHeight);
                 } else {
                     w = qt_mac_aqua_get_metric(kThemeMetricMiniVSliderWidth);
                     if (sld->tickPosition() != QSlider::NoTicks)
                         w += qt_mac_aqua_get_metric(kThemeMetricMiniVSliderTickWidth);
                 }
             }
         } else {
             // This is tricky, we were requested to find a size for a slider which is not
             // a slider. We don't know if this is vertical or horizontal or if we need to
             // have tick marks or not.
             // For this case we will return an horizontal slider without tick marks.
             w = qt_mac_aqua_get_metric(kThemeMetricHSliderHeight);
             w += qt_mac_aqua_get_metric(kThemeMetricHSliderTickHeight);
         }
         if (sld->orientation() == Qt::Horizontal)
             ret.setHeight(w);
         else
             ret.setWidth(w);
         break;
     }
     case QStyle::CT_ProgressBar: {
         int finalValue = -1;
         Qt::Orientation orient = Qt::Horizontal;
         if (const QProgressBar *pb = qobject_cast<const QProgressBar *>(widg))
             orient = pb->orientation();
         if (sz == QAquaSizeLarge)
             finalValue = qt_mac_aqua_get_metric(kThemeMetricLargeProgressBarThickness)
                             + qt_mac_aqua_get_metric(kThemeMetricProgressBarShadowOutset);
         else
             finalValue = qt_mac_aqua_get_metric(kThemeMetricNormalProgressBarThickness)
                             + qt_mac_aqua_get_metric(kThemeMetricSmallProgressBarShadowOutset);
         if (orient == Qt::Horizontal)
             ret.setHeight(finalValue);
         else
             ret.setWidth(finalValue);
         break;
     }
     case QStyle::CT_LineEdit:
         if (!widg || !qobject_cast<QComboBox *>(widg->parentWidget())) {
             //should I take into account the font dimentions of the lineedit? -Sam
             if (sz == QAquaSizeLarge)
                 ret = QSize(-1, 21);
             else
                 ret = QSize(-1, 19);
         }
         break;
     case QStyle::CT_HeaderSection:
         if (isTreeView(widg))
            ret = QSize(-1, qt_mac_aqua_get_metric(kThemeMetricListHeaderHeight));
         break;
     case QStyle::CT_MenuBar:
         if (sz == QAquaSizeLarge) {
 #ifndef QT_MAC_USE_COCOA
             SInt16 size;
             if (!GetThemeMenuBarHeight(&size))
                 ret = QSize(-1, size);
 #else
             ret = QSize(-1, [[NSApp mainMenu] menuBarHeight]);
             // In the qt_mac_set_native_menubar(false) case,
             // we come it here with a zero-height main menu,
             // preventing the in-window menu from displaying.
             // Use 22 pixels for the height, by observation.
             if (ret.height() <= 0)
                 ret.setHeight(22);
 #endif
         }
         break;
     default:
         break;
     }
     return ret;
 }
qt_aqua_guess_size()
static QAquaWidgetSize qt_aqua_guess_size (const QWidget * widg, QSize large, QSize small, QSize mini) static
Definition at line 801 of file qmacstyle_mac.mm.
Referenced by QMacStylePrivate::aquaSizeConstrain().
 {
     if (large == QSize(-1, -1)) {
         if (small != QSize(-1, -1))
             return QAquaSizeSmall;
         if (mini != QSize(-1, -1))
             return QAquaSizeMini;
         return QAquaSizeUnknown;
     } else if (small == QSize(-1, -1)) {
         if (mini != QSize(-1, -1))
             return QAquaSizeMini;
         return QAquaSizeLarge;
     } else if (mini == QSize(-1, -1)) {
         return QAquaSizeLarge;
     }
 #ifndef QT_NO_MAINWINDOW
     if (qobject_cast<QDockWidget *>(widg->window()) || !qgetenv("QWIDGET_ALL_SMALL").isNull()) {
         //if (small.width() != -1 || small.height() != -1)
         return QAquaSizeSmall;
     } else if (!qgetenv("QWIDGET_ALL_MINI").isNull()) {
         return QAquaSizeMini;
     }
 #endif
 #if 0
     /* Figure out which size we're closer to, I just hacked this in, I haven't
        tested it as it would probably look pretty strange to have some widgets
        big and some widgets small in the same window?? -Sam */
     int large_delta=0;
     if (large.width() != -1) {
         int delta = large.width() - widg->width();
         large_delta += delta * delta;
     }
     if (large.height() != -1) {
         int delta = large.height() - widg->height();
         large_delta += delta * delta;
     }
     int small_delta=0;
     if (small.width() != -1) {
         int delta = small.width() - widg->width();
         small_delta += delta * delta;
     }
     if (small.height() != -1) {
         int delta = small.height() - widg->height();
         small_delta += delta * delta;
     }
     int mini_delta=0;
     if (mini.width() != -1) {
         int delta = mini.width() - widg->width();
         mini_delta += delta * delta;
     }
     if (mini.height() != -1) {
         int delta = mini.height() - widg->height();
         mini_delta += delta * delta;
     }
     if (mini_delta < small_delta && mini_delta < large_delta)
         return QAquaSizeMini;
     else if (small_delta < large_delta)
         return QAquaSizeSmall;
 #endif
     return QAquaSizeLarge;
 }
qt_hirectForQRect()
static HIRect qt_hirectForQRect (const QRect & convertRect, const QRect & rect = QRect()) inline static
Definition at line 478 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawComplexControl(), QMacStyle::drawControl(), QMacStyle::drawPrimitive(), drawToolbarButtonArrow(), QMacStylePrivate::getSliderInfo(), QMacStyle::hitTestComplexControl(), QMacStyle::pixelMetric(), QMacStylePrivate::pushButtonContentBounds(), and QMacStyle::subControlRect().
 {
     return CGRectMake(convertRect.x() + rect.x(), convertRect.y() + rect.y(),
                       convertRect.width() - rect.width(), convertRect.height() - rect.height());
 }
qt_mac_aqua_get_metric()
static int qt_mac_aqua_get_metric (ThemeMetric met) static
Definition at line 504 of file qmacstyle_mac.mm.
Referenced by qt_aqua_get_known_size().
 {
     SInt32 ret;
     GetThemeMetric(met, &ret);
     return ret;
 }
qt_mac_buttonIsRenderedFlat()
bool qt_mac_buttonIsRenderedFlat (const QPushButton * pushButton, const QStyleOptionButton * option)
Definition at line 1062 of file qmacstyle_mac.mm.
Referenced by QPushButton::hitButton().
 {
     QMacStyle *macStyle = qobject_cast<QMacStyle *>(pushButton->style());
     if (!macStyle)
         return true;    // revert to 'flat' behavior if not Mac style
     HIThemeButtonDrawInfo bdi;
     macStyle->d->initHIThemePushButton(option, pushButton, kThemeStateActive, &bdi);
     return bdi.kind == kThemeBevelButton;
 }
qt_mac_cg_context()
CGContextRef qt_mac_cg_context (const QPaintDevice * pdev)
Returns the CoreGraphics CGContextRef of the paint device.
Warning
This function is not part of the public interface.
0 is returned if it can't be obtained. It is the caller's responsiblity to CGContextRelease the context when finished using it.
Warning
This function is only available on Mac OS X.
Definition at line 118 of file qpaintdevice_mac.cpp.
Referenced by getTabDirection(), QMacStyle::polish(), and qt_mac_fill_background().
 {
     if (pdev->devType() == QInternal::Pixmap) {
         const QPixmap *pm = static_cast<const QPixmap*>(pdev);
         CGColorSpaceRef colorspace = qt_mac_colorSpaceForDeviceType(pdev);
         uint flags = kCGImageAlphaPremultipliedFirst;
 #ifdef kCGBitmapByteOrder32Host //only needed because CGImage.h added symbols in the minor version
         flags |= kCGBitmapByteOrder32Host;
 #endif
         CGContextRef ret = 0;
         // It would make sense to put this into a mac #ifdef'ed
         // virtual function in the QPixmapData at some point
         if (pm->data->classId() == QPixmapData::MacClass) {
             const QMacPixmapData *pmData = static_cast<const QMacPixmapData*>(pm->data.data());
             ret = CGBitmapContextCreate(pmData->pixels, pmData->w, pmData->h,
                                                      8, pmData->bytesPerRow, colorspace,
                                                      flags);
             if(!ret)
                 qWarning("QPaintDevice: Unable to create context for pixmap (%d/%d/%d)",
                          pmData->w, pmData->h, (pmData->bytesPerRow * pmData->h));
         } else if (pm->data->classId() == QPixmapData::RasterClass) {
             QImage *image = pm->data->buffer();
             ret = CGBitmapContextCreate(image->bits(), image->width(), image->height(),
                                         8, image->bytesPerLine(), colorspace, flags);
         }
         CGContextTranslateCTM(ret, 0, pm->height());
         CGContextScaleCTM(ret, 1, -1);
         return ret;
     } else if (pdev->devType() == QInternal::Widget) {
         CGContextRef ret = static_cast<CGContextRef>(static_cast<const QWidget *>(pdev)->macCGHandle());
         CGContextRetain(ret);
         return ret;
     } else if (pdev->devType() == QInternal::MacQuartz) {
         return static_cast<const QMacQuartzPaintDevice *>(pdev)->cgContext();
     }
     return 0;
 }
qt_mac_convert_mac_region() [1/2]
QRegion qt_mac_convert_mac_region (RgnHandle)
Referenced by getTabDirection().
qt_mac_convert_mac_region() [2/2]
QRegion qt_mac_convert_mac_region (HIShapeRef)
qt_mac_dispose_rgn()
void qt_mac_dispose_rgn (RgnHandle r)
Referenced by getTabDirection().
qt_mac_fill_background()
void qt_mac_fill_background (QPainter * painter, const QRegion & rgn, const QBrush & brush)
Warning
This function is not part of the public interface. Fills the given rect with the pattern stored in brush. As an optimization, HIThemeSetFill us used directly if we are filling with the standard background.
Definition at line 1811 of file qmacstyle_mac.mm.
Referenced by fillRegion().
 {
     QPoint dummy;
     const QPaintDevice *target = painter->device();
     const QPaintDevice *redirected = QPainter::redirected(target, &dummy);
     const bool usePainter = redirected && redirected != target;
     if (!usePainter && qt_mac_backgroundPattern
         && qt_mac_backgroundPattern->cacheKey() == brush.texture().cacheKey()) {
         painter->setClipRegion(rgn);
         QCFType<CGContextRef> cg = qt_mac_cg_context(target);
         CGContextSaveGState(cg);
         HIThemeSetFill(kThemeBrushDialogBackgroundActive, 0, cg, kHIThemeOrientationInverted);
         const QVector<QRect> &rects = rgn.rects();
         for (int i = 0; i < rects.size(); ++i) {
             const QRect rect(rects.at(i));
             // Anchor the pattern to the top so it stays put when the window is resized.
             CGContextSetPatternPhase(cg, CGSizeMake(rect.width(), rect.height()));
             CGRect mac_rect = CGRectMake(rect.x(), rect.y(), rect.width(), rect.height());
             CGContextFillRect(cg, mac_rect);
         }
         CGContextRestoreGState(cg);
     } else {
         const QRect rect(rgn.boundingRect());
         painter->setClipRegion(rgn);
         painter->drawTiledPixmap(rect, brush.texture(), rect.topLeft());
     }
 }
qt_mac_hitheme_tab_version()
static int qt_mac_hitheme_tab_version () inline static
Definition at line 473 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawPrimitive().
 {
     return 1;
 }
qt_mac_is_metal()
bool qt_mac_is_metal (const QWidget * w) inline
Definition at line 490 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawComplexControl(), QMacStyle::drawControl(), QMacStyle::polish(), and QMacStyle::unpolish().
 {
     for (; w; w = w->parentWidget()) {
         if (w->testAttribute(Qt::WA_MacBrushedMetal))
             return true;
         if (w->isWindow() && w->testAttribute(Qt::WA_WState_Created)) {  // If not created will fall through to the opaque check and be fine anyway.
             return macWindowIsTextured(qt_mac_window_for(w));
         }
         if (w->d_func()->isOpaque)
             break;
     }
     return false;
 }
qt_mac_removeMnemonics()
QString qt_mac_removeMnemonics (const QString & original)
Definition at line 398 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawComplexControl(), QMacStyle::drawControl(), QMacCocoaAutoReleasePool::handle(), qt_aqua_get_known_size(), qt_mac_menu_merge_action(), QMacStyle::subControlRect(), QMenuBarPrivate::QMacMenuBarPrivate::syncAction(), and QMenuPrivate::QMacMenuPrivate::syncAction().
 {
     QString returnText(original.size(), 0);
     int finalDest = 0;
     int currPos = 0;
     int l = original.length();
     while (l) {
         if (original.at(currPos) == QLatin1Char('&')
             && (l == 1 || original.at(currPos + 1) != QLatin1Char('&'))) {
             ++currPos;
             --l;
             if (l == 0)
                 break;
         }
         returnText[finalDest] = original.at(currPos);
         ++currPos;
         ++finalDest;
         --l;
     }
     returnText.truncate(finalDest);
     return returnText;
 }
qt_qrectForHIRect()
static const QRect qt_qrectForHIRect (const HIRect & hirect) inline static
Definition at line 484 of file qmacstyle_mac.mm.
Referenced by QMacStylePrivate::contentFitsInPushButton(), QMacStyle::drawComplexControl(), QMacStyle::drawControl(), QMacStyle::subControlRect(), and QMacStyle::subElementRect().
 {
     return QRect(QPoint(int(hirect.origin.x), int(hirect.origin.y)),
                  QSize(int(hirect.size.width), int(hirect.size.height)));
 }
rotateTabPainter()
QRect rotateTabPainter (QPainter * p, QTabBar::Shape shape, QRect tabRect)
Definition at line 188 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawControl(), drawTabBase(), and drawTabShape().
 {
     if (isVerticalTabs(shape)) {
         int newX, newY, newRot;
         if (shape == QTabBar::RoundedEast
             || shape == QTabBar::TriangularEast) {
             newX = tabRect.width();
             newY = tabRect.y();
             newRot = 90;
         } else {
             newX = 0;
             newY = tabRect.y() + tabRect.height();
             newRot = -90;
         }
         tabRect.setRect(0, 0, tabRect.height(), tabRect.width());
         QMatrix m;
         m.translate(newX, newY);
         m.rotate(newRot);
         p->setMatrix(m, true);
     }
     return tabRect;
 }
scrollButtonsCutoffSize()
static int scrollButtonsCutoffSize (ScrollBarCutoffType cutoffType, QMacStyle::WidgetSizePolicy widgetSize) static
Definition at line 1345 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawComplexControl(), QMacStyle::hitTestComplexControl(), and QMacStyle::sizeFromContents().
 {
     // Mini scroll bars do not exist as of version 10.4.
     if (widgetSize ==  QMacStyle::SizeMini)
         return 0;
     const int sizeIndex = (widgetSize == QMacStyle::SizeSmall) ? 1 : 0;
     static const int sizeTable[2][2] = { { 61, 56 }, { 49, 44 } };
     return sizeTable[sizeIndex][cutoffType];
 }
setLayoutItemMargins()
static void setLayoutItemMargins (int left, int top, int right, int bottom, QRect * rect, Qt::LayoutDirection dir) static
Definition at line 4251 of file qmacstyle_mac.mm.
Referenced by QGroupBoxPrivate::calculateFrame(), QToolButtonPrivate::init(), QLabelPrivate::init(), QComboBoxPrivate::init(), QPushButtonPrivate::resetLayoutItemMargins(), QWidgetPrivate::setFont_helper(), QMacStyle::subElementRect(), and QFramePrivate::updateFrameWidth().
 {
     if (dir == Qt::RightToLeft) {
         rect->adjust(-right, top, -left, bottom);
     } else {
         rect->adjust(left, top, right, bottom);
     }
 }
Variable Documentation
closeButtonSize
int closeButtonSize = 12 static
Definition at line 140 of file qmacstyle_mac.mm.
Referenced by drawTabCloseButton(), QMacStyle::pixelMetric(), and QBalloonTip::QBalloonTip().
DisclosureOffset
const int DisclosureOffset = 4 static
Definition at line 134 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawPrimitive(), and QMacStyle::subElementRect().
macItemFrame
const int macItemFrame = 2
Definition at line 463 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawControl().
macItemHMargin
const int macItemHMargin = 3
Definition at line 464 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawControl().
macItemVMargin
const int macItemVMargin = 2
Definition at line 465 of file qmacstyle_mac.mm.
macRightBorder
const int macRightBorder = 12
Definition at line 466 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawControl().
mainWindowGradientBegin
const QColor mainWindowGradientBegin(240, 240, 240) static
Referenced by QMacStyle::drawControl().
mainWindowGradientEnd
const QColor mainWindowGradientEnd(200, 200, 200) static
Referenced by QMacStyle::drawControl().
ptrHIShapeGetBounds
PtrHIShapeGetBounds ptrHIShapeGetBounds = 0 static
Definition at line 138 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawComplexControl(), QMacStyle::drawControl(), QMacStyle::pixelMetric(), QMacStylePrivate::QMacStylePrivate(), QMacStyle::subControlRect(), and QMacStyle::subElementRect().
qt_mac_backgroundPattern
QPixmap* qt_mac_backgroundPattern = 0
Definition at line 468 of file qmacstyle_mac.mm.
Referenced by QMacStyle::~QMacStyle().
qt_mac_hitheme_version
const int qt_mac_hitheme_version = 0
Definition at line 462 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawComplexControl(), QMacStyle::drawControl(), QMacStyle::drawPrimitive(), drawToolbarButtonArrow(), QMacStylePrivate::getSliderInfo(), QMacStyle::hitTestComplexControl(), QMacStylePrivate::initComboboxBdi(), QMacStylePrivate::initHIThemePushButton(), QMacStyle::pixelMetric(), QMacStyle::polish(), QMacStyle::sizeFromContents(), QMacStyle::subControlRect(), and QMacStyle::subElementRect().
qt_mac_safe_pdev
QPaintDevice* qt_mac_safe_pdev
Definition at line 166 of file qapplication_mac.mm.
Referenced by getTabDirection(), and qt_cleanup().
QtWinType
const ThemeWindowType QtWinType = kThemeDocumentWindow
Definition at line 467 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawComplexControl(), QMacStyle::pixelMetric(), and QMacStyle::subControlRect().
titlebarGradientActiveBegin
const QColor titlebarGradientActiveBegin(220, 220, 220) static
Referenced by QMacStyle::drawPrimitive().
titlebarGradientActiveEnd
const QColor titlebarGradientActiveEnd(151, 151, 151) static
Referenced by QMacStyle::drawPrimitive().
titlebarGradientInactiveBegin
const QColor titlebarGradientInactiveBegin(241, 241, 241) static
Referenced by QMacStyle::drawPrimitive().
titlebarGradientInactiveEnd
const QColor titlebarGradientInactiveEnd(207, 207, 207) static
Referenced by QMacStyle::drawPrimitive().
titlebarSeparatorLineActive
const QColor titlebarSeparatorLineActive(111, 111, 111) static
Referenced by QMacStyle::drawPrimitive().
titlebarSeparatorLineInactive
const QColor titlebarSeparatorLineInactive(131, 131, 131) static
Referenced by QMacStyle::drawPrimitive().