Qt 4.8: /src/gui/widgets/qmacnativewidget_mac.mm File Reference
qmacnativewidget_mac.mm File Reference
#import <Cocoa/Cocoa.h>
#import <private/qcocoaview_mac_p.h>
#include "qmacnativewidget_mac.h"
#include <private/qwidget_p.h>
Classes
class QMacNativeWidgetPrivate
Functions
OSViewRef qt_mac_create_widget (QWidget *widget, QWidgetPrivate *widgetPrivate, OSViewRef parent)
Function Documentation
qt_mac_create_widget()
OSViewRef qt_mac_create_widget (QWidget * widget, QWidgetPrivate * widgetPrivate, OSViewRef parent)
Definition at line 1602 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::create_sys(), QMacNativeWidget::QMacNativeWidget(), and qt_mac_unregister_widget().
 {
 #ifdef QT_MAC_USE_COCOA
     QMacCocoaAutoReleasePool pool;
     QT_MANGLE_NAMESPACE(QCocoaView) *view = [[QT_MANGLE_NAMESPACE(QCocoaView) alloc] initWithQWidget:widget widgetPrivate:widgetPrivate];
 #ifdef ALIEN_DEBUG
     qDebug() << "Creating NSView for" << widget;
 #endif
     if (view && parent)
         [parent addSubview:view];
     return view;
 #else
     Q_UNUSED(widget);
     Q_UNUSED(widgetPrivate);
     if(!widget_class) {
         OSStatus err = HIObjectRegisterSubclass(kObjectQWidget, kHIViewClassID, 0, make_widget_eventUPP(),
                                                 GetEventTypeCount(widget_events), widget_events,
                                                 0, &widget_class);
         if (err && err != hiObjectClassExistsErr)
             qWarning("QWidget: Internal error (%d)", __LINE__);
     }
     HIViewRef ret = 0;
     if(HIObjectCreate(kObjectQWidget, 0, (HIObjectRef*)&ret) != noErr)
         qWarning("QWidget: Internal error (%d)", __LINE__);
     if(ret && parent)
         HIViewAddSubview(parent, ret);
     return ret;
 #endif
 }