Qt 4.8: /src/gui/widgets/qmainwindow.cpp File Reference
qmainwindow.cpp File Reference
#include "qmainwindow.h"
#include "qmainwindowlayout_p.h"
#include "qdockwidget.h"
#include "qtoolbar.h"
#include <qapplication.h>
#include <qmenubar.h>
#include <qstatusbar.h>
#include <qevent.h>
#include <qstyle.h>
#include <qdebug.h>
#include <qpainter.h>
#include <private/qwidget_p.h>
#include "qtoolbar_p.h"
#include "qwidgetanimator_p.h"
#include <private/qt_mac_p.h>
#include <private/qt_cocoa_helpers_mac_p.h>
Classes
class QMainWindowPrivate
Functions
static bool checkDockWidgetArea (Qt::DockWidgetArea area, const char *where)
static bool checkToolBarArea (Qt::ToolBarArea area, const char *where)
OSWindowRef qt_mac_window_for (const QWidget *)
QMainWindowLayout * qt_mainwindow_layout (const QMainWindow *mainWindow)
Function Documentation
checkDockWidgetArea()
static bool checkDockWidgetArea (Qt::DockWidgetArea area, const char * where) static
Definition at line 1003 of file qmainwindow.cpp.
Referenced by QMainWindow::addDockWidget(), and QMainWindow::tabPosition().
 {
     switch (area) {
     case Qt::LeftDockWidgetArea:
     case Qt::RightDockWidgetArea:
     case Qt::TopDockWidgetArea:
     case Qt::BottomDockWidgetArea:
         return true;
     default:
         break;
     }
     qWarning("%s: invalid 'area' argument", where);
     return false;
 }
checkToolBarArea()
static bool checkToolBarArea (Qt::ToolBarArea area, const char * where) static
Definition at line 714 of file qmainwindow.cpp.
Referenced by QMainWindow::addToolBar(), and QMainWindow::addToolBarBreak().
 {
     switch (area) {
     case Qt::LeftToolBarArea:
     case Qt::RightToolBarArea:
     case Qt::TopToolBarArea:
     case Qt::BottomToolBarArea:
         return true;
     default:
         break;
     }
     qWarning("%s: invalid 'area' argument", where);
     return false;
 }
qt_mac_window_for()
OSWindowRef qt_mac_window_for (const QWidget *)
Definition at line 484 of file qwidget_mac.mm.
 {
     if (OSViewRef hiview = qt_mac_effectiveview_for(w)) {
         OSWindowRef window = qt_mac_window_for(hiview);
         if (window)
             return window;
         if (qt_isGenuineQWidget(hiview)) {
             // This is a workaround for NSToolbar. When a widget is hidden
             // by clicking the toolbar button, Cocoa reparents the widgets
             // to another window (but Qt doesn't know about it).
             // When we start showing them, it reparents back,
             // but at this point it's window is nil, but the window it's being brought
             // into (the Qt one) is for sure created.
             // This stops the hierarchy moving under our feet.
             QWidget *toplevel = w->window();
             if (toplevel != w) {
                 hiview = qt_mac_nativeview_for(toplevel);
                 if (OSWindowRef w = qt_mac_window_for(hiview))
                     return w;
             }
             toplevel->d_func()->createWindow_sys();
             // Reget the hiview since "create window" could potentially move the view (I guess).
             hiview = qt_mac_nativeview_for(toplevel);
             return qt_mac_window_for(hiview);
         }
     }
     return 0;
 }
qt_mainwindow_layout()
QMainWindowLayout* qt_mainwindow_layout (const QMainWindow * mainWindow)
Definition at line 111 of file qmainwindow.cpp.
Referenced by QMainWindowLayoutState::apply(), QToolBarAreaLayout::apply(), QDockAreaLayout::apply(), QDockWidget::changeEvent(), QDockWidgetPrivate::endDrag(), QToolBarPrivate::endDrag(), QDockWidget::event(), QToolBar::event(), QDockWidgetPrivate::initDrag(), QToolBarPrivate::initDrag(), QToolBar::initStyleOption(), QDockWidgetPrivate::isAnimating(), QDockAreaLayoutInfo::mainWindowLayout(), QDockWidgetPrivate::mouseMoveEvent(), QToolBarPrivate::mouseMoveEvent(), QDockWidgetPrivate::moveEvent(), QDockWidgetPrivate::nonClientAreaMouseEvent(), qt_mac_unregister_widget(), qt_mac_updateToolBarButtonHint(), QToolBarLayout::setExpanded(), QToolBarLayout::setGeometry(), QWidgetPrivate::setModal_sys(), QWidgetPrivate::setParent_sys(), QDockWidgetPrivate::setWindowState(), QDockWidgetPrivate::startDrag(), QToolBarPrivate::startDrag(), QDockAreaLayout::updateSeparatorWidgets(), QToolBar::widgetForAction(), and QToolBar::~QToolBar().
 {
     return QMainWindowPrivate::mainWindowLayout(mainWindow);
 }