Qt 4.8: /src/gui/widgets/qmainwindowlayout.cpp File Reference
qmainwindowlayout.cpp File Reference
#include "qmainwindowlayout_p.h"
#include "qdockarealayout_p.h"
#include "qdockwidget.h"
#include "qdockwidget_p.h"
#include "qtoolbar_p.h"
#include "qmainwindow.h"
#include "qtoolbar.h"
#include "qtoolbarlayout_p.h"
#include "qwidgetanimator_p.h"
#include "qrubberband.h"
#include "qtabbar_p.h"
#include <qapplication.h>
#include <qstatusbar.h>
#include <qstring.h>
#include <qstyle.h>
#include <qvarlengtharray.h>
#include <qstack.h>
#include <qmap.h>
#include <qtimer.h>
#include <qdebug.h>
#include <private/qapplication_p.h>
#include <private/qlayoutengine_p.h>
#include <private/qcore_mac_p.h>
#include <private/qt_cocoa_helpers_mac_p.h>
Classes
class QMainWindowTabBar
Functions
template<typename T >
static QList< T > findChildrenHelper (const QObject *o)
static void fixToolBarOrientation (QLayoutItem *item, int dockPos)
static QTabBar::Shape tabBarShapeFrom (QTabWidget::TabShape shape, QTabWidget::TabPosition position)
static QInternal::DockPosition toDockPos (Qt::ToolBarArea area)
static QInternal::DockPosition toDockPos (Qt::DockWidgetArea area)
static Qt::DockWidgetArea toDockWidgetArea (QInternal::DockPosition pos)
static Qt::DockWidgetArea toDockWidgetArea (int pos)
static Qt::ToolBarArea toToolBarArea (QInternal::DockPosition pos)
static Qt::ToolBarArea toToolBarArea (int pos)
static void validateDockWidgetArea (Qt::DockWidgetArea &area)
static void validateToolBarArea (Qt::ToolBarArea &area)
Function Documentation
findChildrenHelper()
template<typename T > static QList<T> findChildrenHelper (const QObject * o) static
Definition at line 609 of file qmainwindowlayout.cpp.
 {
     const QObjectList &list = o->children();
     QList<T> result;
     for (int i=0; i < list.size(); ++i) {
         if (T t = qobject_cast<T>(list[i])) {
             result.append(t);
         }
     }
     return result;
 }
fixToolBarOrientation()
static void fixToolBarOrientation (QLayoutItem * item, int dockPos) static
Definition at line 1527 of file qmainwindowlayout.cpp.
Referenced by QMainWindowLayout::hover(), QMainWindowLayout::plug(), QMainWindowLayout::revert(), and QMainWindowLayout::unplug().
 {
 #ifndef QT_NO_TOOLBAR
     QToolBar *toolBar = qobject_cast<QToolBar*>(item->widget());
     if (toolBar == 0)
         return;
     QRect oldGeo = toolBar->geometry();
     QInternal::DockPosition pos
         = static_cast<QInternal::DockPosition>(dockPos);
     Qt::Orientation o = pos == QInternal::TopDock || pos == QInternal::BottomDock
                         ? Qt::Horizontal : Qt::Vertical;
     if (o != toolBar->orientation())
         toolBar->setOrientation(o);
     QSize hint = toolBar->sizeHint().boundedTo(toolBar->maximumSize())
                     .expandedTo(toolBar->minimumSize());
     if (toolBar->size() != hint) {
         QRect newGeo(oldGeo.topLeft(), hint);
         if (toolBar->layoutDirection() == Qt::RightToLeft)
             newGeo.moveRight(oldGeo.right());
         toolBar->setGeometry(newGeo);
     }
 #else
     Q_UNUSED(item);
     Q_UNUSED(dockPos);
 #endif
 }
tabBarShapeFrom()
static QTabBar::Shape tabBarShapeFrom (QTabWidget::TabShape shape, QTabWidget::TabPosition position) inline static
Definition at line 1197 of file qmainwindowlayout.cpp.
Referenced by QMainWindowLayout::updateTabBarShapes().
 {
     const bool rounded = (shape == QTabWidget::Rounded);
     if (position == QTabWidget::North)
         return rounded ? QTabBar::RoundedNorth : QTabBar::TriangularNorth;
     if (position == QTabWidget::South)
         return rounded ? QTabBar::RoundedSouth : QTabBar::TriangularSouth;
     if (position == QTabWidget::East)
         return rounded ? QTabBar::RoundedEast : QTabBar::TriangularEast;
     if (position == QTabWidget::West)
         return rounded ? QTabBar::RoundedWest : QTabBar::TriangularWest;
     return QTabBar::RoundedNorth;
 }
toDockPos() [1/2]
static QInternal::DockPosition toDockPos (Qt::ToolBarArea area) static
Definition at line 773 of file qmainwindowlayout.cpp.
Referenced by QMainWindowLayout::addDockWidget(), QMainWindowLayout::addToolBar(), QMainWindowLayout::addToolBarBreak(), and QMainWindowLayout::tabPosition().
 {
     switch (area) {
         case Qt::LeftToolBarArea: return QInternal::LeftDock;
         case Qt::RightToolBarArea: return QInternal::RightDock;
         case Qt::TopToolBarArea: return QInternal::TopDock;
         case Qt::BottomToolBarArea: return QInternal::BottomDock;
         default:
             break;
     }
     return QInternal::DockCount;
 }
toDockPos() [2/2]
static QInternal::DockPosition toDockPos (Qt::DockWidgetArea area) static
Definition at line 1037 of file qmainwindowlayout.cpp.
 {
     switch (area) {
         case Qt::LeftDockWidgetArea: return QInternal::LeftDock;
         case Qt::RightDockWidgetArea: return QInternal::RightDock;
         case Qt::TopDockWidgetArea: return QInternal::TopDock;
         case Qt::BottomDockWidgetArea: return QInternal::BottomDock;
         default:
             break;
     }
     return QInternal::DockCount;
 }
toDockWidgetArea() [1/2]
static Qt::DockWidgetArea toDockWidgetArea (QInternal::DockPosition pos) static
Definition at line 1051 of file qmainwindowlayout.cpp.
Referenced by QMainWindowLayout::dockWidgetArea(), QMainWindowLayout::hover(), and toDockWidgetArea().
 {
     switch (pos) {
         case QInternal::LeftDock : return Qt::LeftDockWidgetArea;
         case QInternal::RightDock : return Qt::RightDockWidgetArea;
         case QInternal::TopDock : return Qt::TopDockWidgetArea;
         case QInternal::BottomDock : return Qt::BottomDockWidgetArea;
         default:
             break;
     }
     return Qt::NoDockWidgetArea;
 }
toDockWidgetArea() [2/2]
static Qt::DockWidgetArea toDockWidgetArea (int pos) inline static
Definition at line 1065 of file qmainwindowlayout.cpp.
 {
     return toDockWidgetArea(static_cast<QInternal::DockPosition>(pos));
 }
toToolBarArea() [1/2]
static Qt::ToolBarArea toToolBarArea (QInternal::DockPosition pos) static
Definition at line 787 of file qmainwindowlayout.cpp.
Referenced by QMainWindowLayout::hover(), and toToolBarArea().
 {
     switch (pos) {
         case QInternal::LeftDock:   return Qt::LeftToolBarArea;
         case QInternal::RightDock:  return Qt::RightToolBarArea;
         case QInternal::TopDock:    return Qt::TopToolBarArea;
         case QInternal::BottomDock: return Qt::BottomToolBarArea;
         default: break;
     }
     return Qt::NoToolBarArea;
 }
toToolBarArea() [2/2]
static Qt::ToolBarArea toToolBarArea (int pos) inline static
Definition at line 799 of file qmainwindowlayout.cpp.
 {
     return toToolBarArea(static_cast<QInternal::DockPosition>(pos));
 }
validateDockWidgetArea()
static void validateDockWidgetArea (Qt::DockWidgetArea & area) inline static
Definition at line 1024 of file qmainwindowlayout.cpp.
 {
     switch (area) {
     case Qt::LeftDockWidgetArea:
     case Qt::RightDockWidgetArea:
     case Qt::TopDockWidgetArea:
     case Qt::BottomDockWidgetArea:
         break;
     default:
         area = Qt::LeftDockWidgetArea;
     }
 }
validateToolBarArea()
static void validateToolBarArea (Qt::ToolBarArea & area) inline static
Definition at line 760 of file qmainwindowlayout.cpp.
Referenced by QMainWindowLayout::addToolBar(), and QMainWindowLayout::addToolBarBreak().
 {
     switch (area) {
     case Qt::LeftToolBarArea:
     case Qt::RightToolBarArea:
     case Qt::TopToolBarArea:
     case Qt::BottomToolBarArea:
         break;
     default:
         area = Qt::TopToolBarArea;
     }
 }