Qt 4.8: /src/gui/widgets/qmainwindowlayout_mac.mm File Reference
qmainwindowlayout_mac.mm File Reference
#include <private/qmainwindowlayout_p.h>
#include <qtoolbar.h>
#include <private/qtoolbarlayout_p.h>
#include <private/qt_cocoa_helpers_mac_p.h>
#include <private/qtoolbar_p.h>
#include <Carbon/Carbon.h>
Classes
struct QToolBarInHIToolbarInfo
Macros
#define kWindowUnifiedTitleAndToolbarAttribute (1 << 7)
#define MacToolbar "com.trolltech.qt-" S0(QT_NAMESPACE) ".qmainwindow.mactoolbar"
#define S "com.trolltech.qt-" S0(QT_NAMESPACE) ".qmainwindow.qtoolbarInHIToolbar"
#define S0(x) SS(x)
#define SNSToolbar "com.trolltech.qt-" S0(QT_NAMESPACE) ".qtoolbarInNSToolbar"
#define SS(x) #x
#define SToolbar "com.trolltech.qt-" S0(QT_NAMESPACE) ".hitoolbar-qtoolbar"
Functions
static void GetToolbarAllowedItems (CFMutableArrayRef array)
Variables
static const int kEventParamQMainWindowLayout = 'QMWL'
static const int kEventParamQToolBar = 'QTBR'
static CFStringRef kQMainWindowMacToolbarID = CFSTR(MacToolbar)
static CFStringRef kQToolBarHIToolbarIdentifier = CFSTR(SToolbar)
static CFStringRef kQToolBarHIToolbarItemClassID = CFSTR(S)
static const EventTypeSpec kToolbarEvents []
const EventTypeSpec qtoolbarEvents []
Macro Definition Documentation
kWindowUnifiedTitleAndToolbarAttribute
#define kWindowUnifiedTitleAndToolbarAttribute (1 << 7)
Definition at line 326 of file qmainwindowlayout_mac.mm.
Referenced by QMainWindowLayout::updateHIToolBarStatus().
MacToolbar
#define MacToolbar "com.trolltech.qt-" S0(QT_NAMESPACE) ".qmainwindow.mactoolbar"
Definition at line 65 of file qmainwindowlayout_mac.mm.
S
#define S "com.trolltech.qt-" S0(QT_NAMESPACE) ".qmainwindow.qtoolbarInHIToolbar"
Definition at line 62 of file qmainwindowlayout_mac.mm.
S0
#define S0 (x) SS(x)
Definition at line 61 of file qmainwindowlayout_mac.mm.
SNSToolbar
#define SNSToolbar "com.trolltech.qt-" S0(QT_NAMESPACE) ".qtoolbarInNSToolbar"
Definition at line 64 of file qmainwindowlayout_mac.mm.
SS
#define SS (x) #x
Definition at line 60 of file qmainwindowlayout_mac.mm.
SToolbar
#define SToolbar "com.trolltech.qt-" S0(QT_NAMESPACE) ".hitoolbar-qtoolbar"
Definition at line 63 of file qmainwindowlayout_mac.mm.
Function Documentation
GetToolbarAllowedItems()
static void GetToolbarAllowedItems (CFMutableArrayRef array) static
Definition at line 190 of file qmainwindowlayout_mac.mm.
Referenced by QMainWindowLayout::qtmacToolbarDelegate().
 {
     CFArrayAppendValue(array, kQToolBarHIToolbarIdentifier);
 }
Variable Documentation
kEventParamQMainWindowLayout
const int kEventParamQMainWindowLayout = 'QMWL' static
Definition at line 94 of file qmainwindowlayout_mac.mm.
Referenced by QMainWindowLayout::createQToolBarInHIToolbarItem(), and QMainWindowLayout::qtoolbarInHIToolbarHandler().
kEventParamQToolBar
const int kEventParamQToolBar = 'QTBR' static
Definition at line 93 of file qmainwindowlayout_mac.mm.
Referenced by QMainWindowLayout::createQToolBarInHIToolbarItem(), and QMainWindowLayout::qtoolbarInHIToolbarHandler().
kQMainWindowMacToolbarID
CFStringRef kQMainWindowMacToolbarID = CFSTR(MacToolbar) static
Definition at line 73 of file qmainwindowlayout_mac.mm.
Referenced by QMainWindowLayout::insertIntoMacToolbar().
kQToolBarHIToolbarIdentifier
CFStringRef kQToolBarHIToolbarIdentifier = CFSTR(SToolbar) static
Definition at line 69 of file qmainwindowlayout_mac.mm.
Referenced by QMainWindowLayout::createQToolBarInHIToolbarItem(), QMainWindowLayout::CreateToolbarItemForIdentifier(), GetToolbarAllowedItems(), and QMainWindowLayout::insertIntoMacToolbar().
kQToolBarHIToolbarItemClassID
CFStringRef kQToolBarHIToolbarItemClassID = CFSTR(S) static
Definition at line 68 of file qmainwindowlayout_mac.mm.
Referenced by QMainWindowLayout::createQToolBarInHIToolbarItem(), and QMainWindowLayout::qtMacHIToolbarRegisterQToolBarInHIToolborItemClass().
kToolbarEvents
const EventTypeSpec kToolbarEvents[] static
Initial value:
= {
{ kEventClassToolbar, kEventToolbarGetDefaultIdentifiers },
{ kEventClassToolbar, kEventToolbarGetAllowedIdentifiers },
{ kEventClassToolbar, kEventToolbarCreateItemWithIdentifier },
{ kEventClassToolbar, kEventToolbarItemAdded },
{ kEventClassToolbar, kEventToolbarItemRemoved }
}
Definition at line 238 of file qmainwindowlayout_mac.mm.
Referenced by QMainWindowLayout::insertIntoMacToolbar().
qtoolbarEvents
const EventTypeSpec qtoolbarEvents[]
Initial value:
=
{
    { kEventClassHIObject, kEventHIObjectConstruct },
    { kEventClassHIObject, kEventHIObjectDestruct },
    { kEventClassHIObject, kEventHIObjectInitialize },
    { kEventClassToolbarItem, kEventToolbarItemCreateCustomView }
}
Definition at line 96 of file qmainwindowlayout_mac.mm.
Referenced by QMainWindowLayout::qtMacHIToolbarRegisterQToolBarInHIToolborItemClass().