Qt 4.8: /src/corelib/global/qmalloc.cpp File Reference
qmalloc.cpp File Reference
#include "qplatformdefs.h"
#include <stdlib.h>
Functions
void qFree (void *ptr)
void qFreeAligned (void *ptr)
void * qMalloc (size_t size)
void * qMallocAligned (size_t size, size_t alignment)
void * qRealloc (void *ptr, size_t size)
void * qReallocAligned (void *oldptr, size_t newsize, size_t oldsize, size_t alignment)
Function Documentation
qFree()
void qFree (void * ptr)
Definition at line 58 of file qmalloc.cpp.
Referenced by QSGGeometry::allocate(), QScopedPointerPodDeleter::cleanup(), QGL2PaintEngineExPrivate::cleanupVectorPath(), QByteArray::clear(), QMapData::continueFreeData(), QDeclarativeOpenMetaObjectType::createProperty(), QList< QPostEvent >::detach_helper(), QList< QPostEvent >::detach_helper_grow(), QGL2PaintEngineExPrivate::fill(), QVectorData::free(), QList< QPostEvent >::free(), QString::free(), QHashData::freeNode(), QScriptEnginePrivate::freeScriptValuePrivate(), QPixmap::fromWinHBITMAP(), QString::insert(), interfaceListing(), interfaceListingWin2k(), interfaceListingWinXP(), QMetaMethod::invoke(), ipv4Netmasks(), QHostInfo::localDomainName(), QMapData::node_delete(), QScriptValuePrivate::operator delete(), QByteArray::operator=(), QAudioDeviceInfoInternal::QAudioDeviceInfoInternal(), readSymLink(), QVarLengthArray< QVariant, 9 >::realloc(), QByteArray::realloc(), QString::replace_helper(), QByteArray::resize(), QDataBuffer< GLfloat >::shrink(), QPixmap::toWinHICON(), QTiffHandler::write(), QTextCodec::ConverterState::~ConverterState(), QDeclarativeJS::MemoryPool::~MemoryPool(), QDeclarativeJS::Parser::~Parser(), QtMultimediaInternal::QAudioBufferList::~QAudioBufferList(), QByteArray::~QByteArray(), QDataBuffer< GLfloat >::~QDataBuffer(), QDeclarativeBoundSignalParameters::~QDeclarativeBoundSignalParameters(), QDeclarativeOpenMetaObjectType::~QDeclarativeOpenMetaObjectType(), QMetaCallEvent::~QMetaCallEvent(), QScriptEnginePrivate::~QScriptEnginePrivate(), QScriptParser::~QScriptParser(), QSGGeometry::~QSGGeometry(), QTestCharBuffer::~QTestCharBuffer(), QVarLengthArray< QVariant, 9 >::~QVarLengthArray(), QXmlStreamReaderPrivate::~QXmlStreamReaderPrivate(), QXmlStreamSimpleStack< QXmlStreamReaderPrivate::Entity *>::~QXmlStreamSimpleStack(), and QScript::SyntaxChecker::~SyntaxChecker().
 {
     ::free(ptr);
 }
qFreeAligned()
void qFreeAligned (void * ptr)
Definition at line 118 of file qmalloc.cpp.
Referenced by QMapData::continueFreeData(), QContiguousCacheData::free(), QVectorData::free(), QHashData::freeNode(), and QMapData::node_delete().
 {
     if (!ptr)
         return;
     void **ptr2 = static_cast<void **>(ptr);
     free(ptr2[-1]);
 }
qMalloc()
void* qMalloc (size_t size)
Definition at line 53 of file qmalloc.cpp.
Referenced by QSGGeometry::allocate(), QVectorData::allocate(), QDeclarativeJS::MemoryPool::allocate(), QHashData::allocateNode(), QScriptEnginePrivate::allocateScriptValuePrivate(), QListData::detach(), QListData::detach2(), QListData::detach_grow(), QGL2PaintEngineExPrivate::fill(), QString::fromLatin1_helper(), QByteArray::fromRawData(), QString::fromRawData(), QPixmap::fromWinHBITMAP(), QString::insert(), interfaceListing(), interfaceListingWin2k(), interfaceListingWinXP(), QMetaMethod::invoke(), ipv4Netmasks(), QHostInfo::localDomainName(), QVectorData::malloc(), QMapData::node_create(), QScriptValuePrivate::operator new(), QtMultimediaInternal::QAudioBufferList::QAudioBufferList(), QAudioDeviceInfoInternal::QAudioDeviceInfoInternal(), QByteArray::QByteArray(), QDataBuffer< GLfloat >::QDataBuffer(), QString::QString(), queued_activate(), QVarLengthArray< QVariant, 9 >::QVarLengthArray(), readSymLink(), QVarLengthArray< QVariant, 9 >::realloc(), QByteArray::realloc(), QString::realloc(), QString::replace_helper(), QTestCharBuffer::reset(), QByteArray::resize(), QMetaObjectBuilder::toMetaObject(), QPixmap::toWinHICON(), and QTiffHandler::write().
 {
     return ::malloc(size);
 }
qMallocAligned()
void* qMallocAligned (size_t size, size_t alignment)
Definition at line 68 of file qmalloc.cpp.
Referenced by QContiguousCacheData::allocate(), QVectorData::allocate(), QHashData::allocateNode(), and QMapData::node_create().
 {
     return qReallocAligned(0, size, 0, alignment);
 }
qRealloc()
void* qRealloc (void * ptr, size_t size)
Definition at line 63 of file qmalloc.cpp.
Referenced by QDeclarativeJS::MemoryPool::allocate(), qReallocAligned(), QListData::realloc(), QByteArray::realloc(), QString::realloc(), QVectorData::reallocate(), QScript::SyntaxChecker::reallocateStack(), QScriptParser::reallocateStack(), QDeclarativeJS::Parser::reallocateStack(), QXmlStreamReaderPrivate::reallocateStack(), QDataBuffer< GLfloat >::reserve(), QXmlStreamSimpleStack< QXmlStreamReaderPrivate::Entity *>::reserve(), QTestCharBuffer::reset(), and QDataBuffer< GLfloat >::shrink().
 {
     return ::realloc(ptr, size);
 }
qReallocAligned()
void* qReallocAligned (void * oldptr, size_t newsize, size_t oldsize, size_t alignment)
Definition at line 73 of file qmalloc.cpp.
Referenced by qMallocAligned(), and QVectorData::reallocate().
 {
     // fake an aligned allocation
     Q_UNUSED(oldsize);
     void *actualptr = oldptr ? static_cast<void **>(oldptr)[-1] : 0;
     if (alignment <= sizeof(void*)) {
         // special, fast case
         void **newptr = static_cast<void **>(qRealloc(actualptr, newsize + sizeof(void*)));
         if (!newptr)
             return 0;
         if (newptr == actualptr) {
             // realloc succeeded without reallocating
             return oldptr;
         }
         *newptr = newptr;
         return newptr + 1;
     }
     // qMalloc returns pointers aligned at least at sizeof(size_t) boundaries
     // but usually more (8- or 16-byte boundaries).
     // So we overallocate by alignment-sizeof(size_t) bytes, so we're guaranteed to find a
     // somewhere within the first alignment-sizeof(size_t) that is properly aligned.
     // However, we need to store the actual pointer, so we need to allocate actually size +
     // alignment anyway.
     void *real = qRealloc(actualptr, newsize + alignment);
     if (!real)
         return 0;
     quintptr faked = reinterpret_cast<quintptr>(real) + alignment;
     faked &= ~(alignment - 1);
     void **faked_ptr = reinterpret_cast<void **>(faked);
     // now save the value of the real pointer at faked-sizeof(void*)
     // by construction, alignment > sizeof(void*) and is a power of 2, so
     // faked-sizeof(void*) is properly aligned for a pointer
     faked_ptr[-1] = real;
     return faked_ptr;
 }