Qt 4.8: /src/gui/painting/qmatrix.h File Reference
qmatrix.h File Reference
#include <QtGui/qpolygon.h>
#include <QtGui/qregion.h>
#include <QtGui/qwindowdefs.h>
#include <QtCore/qline.h>
#include <QtCore/qpoint.h>
#include <QtCore/qrect.h>
Classes
class QMatrix
The QMatrix class specifies 2D transformations of a coordinate system.
Functions
Q_GUI_EXPORT_INLINE QPoint operator* (const QPoint &p, const QMatrix &m)
Q_GUI_EXPORT_INLINE QPointF operator* (const QPointF &p, const QMatrix &m)
Q_GUI_EXPORT_INLINE QLineF operator* (const QLineF &l, const QMatrix &m)
Q_GUI_EXPORT_INLINE QLine operator* (const QLine &l, const QMatrix &m)
Q_GUI_EXPORT_INLINE QPolygon operator* (const QPolygon &a, const QMatrix &m)
Q_GUI_EXPORT_INLINE QPolygonF operator* (const QPolygonF &a, const QMatrix &m)
Q_GUI_EXPORT_INLINE QRegion operator* (const QRegion &r, const QMatrix &m)
Q_GUI_EXPORT QPainterPath operator* (const QPainterPath &p, const QMatrix &m)
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &, const QMatrix &)
Q_GUI_EXPORT QDebug operator<< (QDebug, const QMatrix &)
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &, QMatrix &)
Q_DECLARE_TYPEINFO (QMatrix, Q_MOVABLE_TYPE)
bool qFuzzyCompare (const QMatrix &m1, const QMatrix &m2)
Function Documentation
operator*() [1/8]
Q_GUI_EXPORT_INLINE QPoint operator* (const QPoint & p, const QMatrix & m) related
Definition at line 150 of file qmatrix.h.
Referenced by QMatrix::det(), and operator*().
 { return m.map(p); }
operator*() [2/8]
Q_GUI_EXPORT_INLINE QPointF operator* (const QPointF & p, const QMatrix & m) related
Definition at line 152 of file qmatrix.h.
 { return m.map(p); }
operator*() [3/8]
Q_GUI_EXPORT_INLINE QLineF operator* (const QLineF & l, const QMatrix & m) related
Definition at line 154 of file qmatrix.h.
 { return m.map(l); }
operator*() [4/8]
Q_GUI_EXPORT_INLINE QLine operator* (const QLine & l, const QMatrix & m) related
Definition at line 156 of file qmatrix.h.
 { return m.map(l); }
operator*() [5/8]
Q_GUI_EXPORT_INLINE QPolygon operator* (const QPolygon & a, const QMatrix & m) related
Definition at line 158 of file qmatrix.h.
 { return m.map(a); }
operator*() [6/8]
Q_GUI_EXPORT_INLINE QPolygonF operator* (const QPolygonF & a, const QMatrix & m) related
Definition at line 160 of file qmatrix.h.
 { return m.map(a); }
operator*() [7/8]
Q_GUI_EXPORT_INLINE QRegion operator* (const QRegion & r, const QMatrix & m) related
Definition at line 162 of file qmatrix.h.
 { return m.map(r); }
operator*() [8/8]
Q_GUI_EXPORT QPainterPath operator* (const QPainterPath & p, const QMatrix & m) related
Definition at line 1200 of file qmatrix.cpp.
 {
     return m.map(p);
 }
operator<<() [1/2]
Q_GUI_EXPORT QDataStream& operator<< (QDataStream & , const QMatrix &) related
Definition at line 1223 of file qmatrix.cpp.
Referenced by qFuzzyCompare().
 {
     if (s.version() == 1) {
         s << (float)m.m11() << (float)m.m12() << (float)m.m21()
           << (float)m.m22() << (float)m.dx()  << (float)m.dy();
     } else {
         s << double(m.m11())
           << double(m.m12())
           << double(m.m21())
           << double(m.m22())
           << double(m.dx())
           << double(m.dy());
     }
     return s;
 }
operator<<() [2/2]
Q_GUI_EXPORT QDebug operator<< (QDebug , const QMatrix &)
Definition at line 1275 of file qmatrix.cpp.
 {
     dbg.nospace() << "QMatrix("
                   << "11=" << m.m11()
                   << " 12=" << m.m12()
                   << " 21=" << m.m21()
                   << " 22=" << m.m22()
                   << " dx=" << m.dx()
                   << " dy=" << m.dy()
                   << ')';
     return dbg.space();
 }
operator>>()
Q_GUI_EXPORT QDataStream& operator>> (QDataStream & , QMatrix &) related
Definition at line 1252 of file qmatrix.cpp.
Referenced by qFuzzyCompare().
 {
     if (s.version() == 1) {
         float m11, m12, m21, m22, dx, dy;
         s >> m11;  s >> m12;  s >> m21;  s >> m22;
         s >> dx;   s >> dy;
         m.setMatrix(m11, m12, m21, m22, dx, dy);
     }
     else {
         double m11, m12, m21, m22, dx, dy;
         s >> m11;
         s >> m12;
         s >> m21;
         s >> m22;
         s >> dx;
         s >> dy;
         m.setMatrix(m11, m12, m21, m22, dx, dy);
     }
     return s;
 }
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QMatrix , Q_MOVABLE_TYPE)
qFuzzyCompare()
bool qFuzzyCompare (const QMatrix & m1, const QMatrix & m2) related
Definition at line 172 of file qmatrix.h.
 {
     return qFuzzyCompare(m1.m11(), m2.m11())
         && qFuzzyCompare(m1.m12(), m2.m12())
         && qFuzzyCompare(m1.m21(), m2.m21())
         && qFuzzyCompare(m1.m22(), m2.m22())
         && qFuzzyCompare(m1.dx(), m2.dx())
         && qFuzzyCompare(m1.dy(), m2.dy());
 }