Qt 4.8: /src/gui/painting/qmatrix.cpp File Reference
qmatrix.cpp File Reference
#include "qdatastream.h"
#include "qdebug.h"
#include "qmatrix.h"
#include "qregion.h"
#include "qpainterpath.h"
#include "qvariant.h"
#include <qmath.h>
#include <limits.h>
Macros
#define MAPDOUBLE(x, y, nx, ny)
#define MAPINT(x, y, nx, ny)
Functions
Q_GUI_EXPORT QPainterPath operator* (const QPainterPath &p, const QMatrix &m)
QDataStream & operator<< (QDataStream &s, const QMatrix &m)
QDebug operator<< (QDebug dbg, const QMatrix &m)
QDataStream & operator>> (QDataStream &s, QMatrix &m)
Q_AUTOTEST_EXPORT QPainterPath qt_regionToPath (const QRegion &region)
Variables
const qreal deg2rad = qreal(0.017453292519943295769)
Macro Definition Documentation
MAPDOUBLE
#define MAPDOUBLE (x, y, nx, ny)
Value:
{ \
    qreal fx = x; \
    qreal fy = y; \
    nx = _m11*fx + _m21*fy + _dx; \
    ny = _m12*fx + _m22*fy + _dy; \
}
Definition at line 183 of file qmatrix.cpp.
Referenced by QMatrix::map(), QMatrix::mapRect(), and QMatrix::mapToPolygon().
MAPINT
#define MAPINT (x, y, nx, ny)
Value:
{ \
    qreal fx = x; \
    qreal fy = y; \
    nx = qRound(_m11*fx + _m21*fy + _dx); \
    ny = qRound(_m12*fx + _m22*fy + _dy); \
}
Definition at line 191 of file qmatrix.cpp.
Referenced by QMatrix::map().
Function Documentation
operator*()
Q_GUI_EXPORT QPainterPath operator* (const QPainterPath & p, const QMatrix & m) related
Definition at line 1200 of file qmatrix.cpp.
 {
     return m.map(p);
 }
operator<<() [1/2]
QDataStream& operator<< (QDataStream & s, const QMatrix & m) related
Definition at line 1223 of file qmatrix.cpp.
Referenced by qFuzzyCompare().
 {
     if (s.version() == 1) {
         s << (float)m.m11() << (float)m.m12() << (float)m.m21()
           << (float)m.m22() << (float)m.dx()  << (float)m.dy();
     } else {
         s << double(m.m11())
           << double(m.m12())
           << double(m.m21())
           << double(m.m22())
           << double(m.dx())
           << double(m.dy());
     }
     return s;
 }
operator<<() [2/2]
QDebug operator<< (QDebug dbg, const QMatrix & m)
Definition at line 1275 of file qmatrix.cpp.
 {
     dbg.nospace() << "QMatrix("
                   << "11=" << m.m11()
                   << " 12=" << m.m12()
                   << " 21=" << m.m21()
                   << " 22=" << m.m22()
                   << " dx=" << m.dx()
                   << " dy=" << m.dy()
                   << ')';
     return dbg.space();
 }
operator>>()
QDataStream& operator>> (QDataStream & s, QMatrix & m) related
Definition at line 1252 of file qmatrix.cpp.
Referenced by qFuzzyCompare().
 {
     if (s.version() == 1) {
         float m11, m12, m21, m22, dx, dy;
         s >> m11;  s >> m12;  s >> m21;  s >> m22;
         s >> dx;   s >> dy;
         m.setMatrix(m11, m12, m21, m22, dx, dy);
     }
     else {
         double m11, m12, m21, m22, dx, dy;
         s >> m11;
         s >> m12;
         s >> m21;
         s >> m22;
         s >> dx;
         s >> dy;
         m.setMatrix(m11, m12, m21, m22, dx, dy);
     }
     return s;
 }
qt_regionToPath()
Q_AUTOTEST_EXPORT QPainterPath qt_regionToPath (const QRegion & region)
Definition at line 1160 of file qregion.cpp.
Referenced by QMatrix::map().
 {
     QPainterPath result;
     if (region.rectCount() == 1) {
         result.addRect(region.boundingRect());
         return result;
     }
     const QVector<QRect> rects = region.rects();
     QVarLengthArray<Segment> segments;
     segments.resize(4 * rects.size());
     const QRect *rect = rects.constData();
     const QRect *end = rect + rects.size();
     int lastRowSegmentCount = 0;
     Segment *lastRowSegments = 0;
     int lastSegment = 0;
     int lastY = 0;
     while (rect != end) {
         const int y = rect[0].y();
         int count = 0;
         while (&rect[count] != end && rect[count].y() == y)
             ++count;
         for (int i = 0; i < count; ++i) {
             int offset = lastSegment + i;
             segments[offset] = Segment(rect[i].topLeft());
             segments[offset += count] = Segment(rect[i].topRight() + QPoint(1, 0));
             segments[offset += count] = Segment(rect[i].bottomRight() + QPoint(1, 1));
             segments[offset += count] = Segment(rect[i].bottomLeft() + QPoint(0, 1));
             offset = lastSegment + i;
             for (int j = 0; j < 4; ++j)
                 segments[offset + j * count].connect(segments[offset + ((j + 1) % 4) * count]);
         }
         if (lastRowSegments && lastY == y)
             mergeSegments(lastRowSegments, lastRowSegmentCount, &segments[lastSegment], count);
         lastRowSegments = &segments[lastSegment + 2 * count];
         lastRowSegmentCount = count;
         lastSegment += 4 * count;
         lastY = y + rect[0].height();
         rect += count;
     }
     for (int i = 0; i < lastSegment; ++i) {
         Segment *segment = &segments[i];
         if (!segment->added)
             addSegmentsToPath(segment, result);
     }
     return result;
 }
Variable Documentation
deg2rad
const qreal deg2rad = qreal(0.017453292519943295769)
Definition at line 970 of file qmatrix.cpp.
Referenced by parseTransformationMatrix(), QSvgAnimateTransform::resolveMatrix(), and QMatrix::rotate().