Qt 4.8: /src/gui/math3d/qmatrix4x4.h File Reference
qmatrix4x4.h File Reference
#include <QtGui/qvector3d.h>
#include <QtGui/qvector4d.h>
#include <QtGui/qquaternion.h>
#include <QtGui/qgenericmatrix.h>
#include <QtCore/qrect.h>
Classes
class QMatrix4x4
The QMatrix4x4 class represents a 4x4 transformation matrix in 3D space.
Functions
QMatrix4x4 operator* (const QMatrix4x4 &m1, const QMatrix4x4 &m2)
QVector3D operator* (const QVector3D &vector, const QMatrix4x4 &matrix)
QVector3D operator* (const QMatrix4x4 &matrix, const QVector3D &vector)
QVector4D operator* (const QVector4D &vector, const QMatrix4x4 &matrix)
QVector4D operator* (const QMatrix4x4 &matrix, const QVector4D &vector)
QPoint operator* (const QPoint &point, const QMatrix4x4 &matrix)
QPointF operator* (const QPointF &point, const QMatrix4x4 &matrix)
QPoint operator* (const QMatrix4x4 &matrix, const QPoint &point)
QPointF operator* (const QMatrix4x4 &matrix, const QPointF &point)
QMatrix4x4 operator* (qreal factor, const QMatrix4x4 &matrix)
QMatrix4x4 operator* (const QMatrix4x4 &matrix, qreal factor)
QMatrix4x4 operator+ (const QMatrix4x4 &m1, const QMatrix4x4 &m2)
QMatrix4x4 operator- (const QMatrix4x4 &m1, const QMatrix4x4 &m2)
QMatrix4x4 operator- (const QMatrix4x4 &matrix)
Q_GUI_EXPORT QMatrix4x4 operator/ (const QMatrix4x4 &matrix, qreal divisor)
Q_GUI_EXPORT QDebug operator<< (QDebug dbg, const QMatrix4x4 &m)
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &, const QMatrix4x4 &)
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &, QMatrix4x4 &)
Q_DECLARE_TYPEINFO (QMatrix4x4, Q_MOVABLE_TYPE)
bool qFuzzyCompare (const QMatrix4x4 &m1, const QMatrix4x4 &m2)
template<int N, int M>
QT_DEPRECATED QGenericMatrix< N, M, qreal > qGenericMatrixFromMatrix4x4 (const QMatrix4x4 &matrix)
template<int N, int M>
QT_DEPRECATED QMatrix4x4 qGenericMatrixToMatrix4x4 (const QGenericMatrix< N, M, qreal > &matrix)
Function Documentation
operator*() [1/11]
QMatrix4x4 operator* (const QMatrix4x4 & m1, const QMatrix4x4 & m2) inline
Definition at line 529 of file qmatrix4x4.h.
Referenced by QMatrix4x4::QMatrix4x4().
 {
     if (m1.flagBits == QMatrix4x4::Identity)
         return m2;
     else if (m2.flagBits == QMatrix4x4::Identity)
         return m1;
     QMatrix4x4 m(1);
     m.m[0][0] = m1.m[0][0] * m2.m[0][0] +
                 m1.m[1][0] * m2.m[0][1] +
                 m1.m[2][0] * m2.m[0][2] +
                 m1.m[3][0] * m2.m[0][3];
     m.m[0][1] = m1.m[0][1] * m2.m[0][0] +
                 m1.m[1][1] * m2.m[0][1] +
                 m1.m[2][1] * m2.m[0][2] +
                 m1.m[3][1] * m2.m[0][3];
     m.m[0][2] = m1.m[0][2] * m2.m[0][0] +
                 m1.m[1][2] * m2.m[0][1] +
                 m1.m[2][2] * m2.m[0][2] +
                 m1.m[3][2] * m2.m[0][3];
     m.m[0][3] = m1.m[0][3] * m2.m[0][0] +
                 m1.m[1][3] * m2.m[0][1] +
                 m1.m[2][3] * m2.m[0][2] +
                 m1.m[3][3] * m2.m[0][3];
     m.m[1][0] = m1.m[0][0] * m2.m[1][0] +
                 m1.m[1][0] * m2.m[1][1] +
                 m1.m[2][0] * m2.m[1][2] +
                 m1.m[3][0] * m2.m[1][3];
     m.m[1][1] = m1.m[0][1] * m2.m[1][0] +
                 m1.m[1][1] * m2.m[1][1] +
                 m1.m[2][1] * m2.m[1][2] +
                 m1.m[3][1] * m2.m[1][3];
     m.m[1][2] = m1.m[0][2] * m2.m[1][0] +
                 m1.m[1][2] * m2.m[1][1] +
                 m1.m[2][2] * m2.m[1][2] +
                 m1.m[3][2] * m2.m[1][3];
     m.m[1][3] = m1.m[0][3] * m2.m[1][0] +
                 m1.m[1][3] * m2.m[1][1] +
                 m1.m[2][3] * m2.m[1][2] +
                 m1.m[3][3] * m2.m[1][3];
     m.m[2][0] = m1.m[0][0] * m2.m[2][0] +
                 m1.m[1][0] * m2.m[2][1] +
                 m1.m[2][0] * m2.m[2][2] +
                 m1.m[3][0] * m2.m[2][3];
     m.m[2][1] = m1.m[0][1] * m2.m[2][0] +
                 m1.m[1][1] * m2.m[2][1] +
                 m1.m[2][1] * m2.m[2][2] +
                 m1.m[3][1] * m2.m[2][3];
     m.m[2][2] = m1.m[0][2] * m2.m[2][0] +
                 m1.m[1][2] * m2.m[2][1] +
                 m1.m[2][2] * m2.m[2][2] +
                 m1.m[3][2] * m2.m[2][3];
     m.m[2][3] = m1.m[0][3] * m2.m[2][0] +
                 m1.m[1][3] * m2.m[2][1] +
                 m1.m[2][3] * m2.m[2][2] +
                 m1.m[3][3] * m2.m[2][3];
     m.m[3][0] = m1.m[0][0] * m2.m[3][0] +
                 m1.m[1][0] * m2.m[3][1] +
                 m1.m[2][0] * m2.m[3][2] +
                 m1.m[3][0] * m2.m[3][3];
     m.m[3][1] = m1.m[0][1] * m2.m[3][0] +
                 m1.m[1][1] * m2.m[3][1] +
                 m1.m[2][1] * m2.m[3][2] +
                 m1.m[3][1] * m2.m[3][3];
     m.m[3][2] = m1.m[0][2] * m2.m[3][0] +
                 m1.m[1][2] * m2.m[3][1] +
                 m1.m[2][2] * m2.m[3][2] +
                 m1.m[3][2] * m2.m[3][3];
     m.m[3][3] = m1.m[0][3] * m2.m[3][0] +
                 m1.m[1][3] * m2.m[3][1] +
                 m1.m[2][3] * m2.m[3][2] +
                 m1.m[3][3] * m2.m[3][3];
     return m;
 }
operator*() [2/11]
QVector3D operator* (const QVector3D & vector, const QMatrix4x4 & matrix) inline
Definition at line 606 of file qmatrix4x4.h.
 {
     qreal x, y, z, w;
     x = vector.x() * matrix.m[0][0] +
         vector.y() * matrix.m[0][1] +
         vector.z() * matrix.m[0][2] +
         matrix.m[0][3];
     y = vector.x() * matrix.m[1][0] +
         vector.y() * matrix.m[1][1] +
         vector.z() * matrix.m[1][2] +
         matrix.m[1][3];
     z = vector.x() * matrix.m[2][0] +
         vector.y() * matrix.m[2][1] +
         vector.z() * matrix.m[2][2] +
         matrix.m[2][3];
     w = vector.x() * matrix.m[3][0] +
         vector.y() * matrix.m[3][1] +
         vector.z() * matrix.m[3][2] +
         matrix.m[3][3];
     if (w == 1.0f)
         return QVector3D(x, y, z);
     else
         return QVector3D(x / w, y / w, z / w);
 }
operator*() [3/11]
QVector3D operator* (const QMatrix4x4 & matrix, const QVector3D & vector) inline
Definition at line 631 of file qmatrix4x4.h.
 {
     qreal x, y, z, w;
     if (matrix.flagBits == QMatrix4x4::Identity) {
         return vector;
     } else if (matrix.flagBits == QMatrix4x4::Translation) {
         return QVector3D(vector.x() + matrix.m[3][0],
                          vector.y() + matrix.m[3][1],
                          vector.z() + matrix.m[3][2]);
     } else if (matrix.flagBits ==
                     (QMatrix4x4::Translation | QMatrix4x4::Scale)) {
         return QVector3D(vector.x() * matrix.m[0][0] + matrix.m[3][0],
                          vector.y() * matrix.m[1][1] + matrix.m[3][1],
                          vector.z() * matrix.m[2][2] + matrix.m[3][2]);
     } else if (matrix.flagBits == QMatrix4x4::Scale) {
         return QVector3D(vector.x() * matrix.m[0][0],
                          vector.y() * matrix.m[1][1],
                          vector.z() * matrix.m[2][2]);
     } else {
         x = vector.x() * matrix.m[0][0] +
             vector.y() * matrix.m[1][0] +
             vector.z() * matrix.m[2][0] +
             matrix.m[3][0];
         y = vector.x() * matrix.m[0][1] +
             vector.y() * matrix.m[1][1] +
             vector.z() * matrix.m[2][1] +
             matrix.m[3][1];
         z = vector.x() * matrix.m[0][2] +
             vector.y() * matrix.m[1][2] +
             vector.z() * matrix.m[2][2] +
             matrix.m[3][2];
         w = vector.x() * matrix.m[0][3] +
             vector.y() * matrix.m[1][3] +
             vector.z() * matrix.m[2][3] +
             matrix.m[3][3];
         if (w == 1.0f)
             return QVector3D(x, y, z);
         else
             return QVector3D(x / w, y / w, z / w);
     }
 }
operator*() [4/11]
QVector4D operator* (const QVector4D & vector, const QMatrix4x4 & matrix) inline
Definition at line 677 of file qmatrix4x4.h.
 {
     qreal x, y, z, w;
     x = vector.x() * matrix.m[0][0] +
         vector.y() * matrix.m[0][1] +
         vector.z() * matrix.m[0][2] +
         vector.w() * matrix.m[0][3];
     y = vector.x() * matrix.m[1][0] +
         vector.y() * matrix.m[1][1] +
         vector.z() * matrix.m[1][2] +
         vector.w() * matrix.m[1][3];
     z = vector.x() * matrix.m[2][0] +
         vector.y() * matrix.m[2][1] +
         vector.z() * matrix.m[2][2] +
         vector.w() * matrix.m[2][3];
     w = vector.x() * matrix.m[3][0] +
         vector.y() * matrix.m[3][1] +
         vector.z() * matrix.m[3][2] +
         vector.w() * matrix.m[3][3];
     return QVector4D(x, y, z, w);
 }
operator*() [5/11]
QVector4D operator* (const QMatrix4x4 & matrix, const QVector4D & vector) inline
Definition at line 699 of file qmatrix4x4.h.
 {
     qreal x, y, z, w;
     x = vector.x() * matrix.m[0][0] +
         vector.y() * matrix.m[1][0] +
         vector.z() * matrix.m[2][0] +
         vector.w() * matrix.m[3][0];
     y = vector.x() * matrix.m[0][1] +
         vector.y() * matrix.m[1][1] +
         vector.z() * matrix.m[2][1] +
         vector.w() * matrix.m[3][1];
     z = vector.x() * matrix.m[0][2] +
         vector.y() * matrix.m[1][2] +
         vector.z() * matrix.m[2][2] +
         vector.w() * matrix.m[3][2];
     w = vector.x() * matrix.m[0][3] +
         vector.y() * matrix.m[1][3] +
         vector.z() * matrix.m[2][3] +
         vector.w() * matrix.m[3][3];
     return QVector4D(x, y, z, w);
 }
operator*() [6/11]
QPoint operator* (const QPoint & point, const QMatrix4x4 & matrix) inline
Definition at line 723 of file qmatrix4x4.h.
 {
     qreal xin, yin;
     qreal x, y, w;
     xin = point.x();
     yin = point.y();
     x = xin * matrix.m[0][0] +
         yin * matrix.m[0][1] +
         matrix.m[0][3];
     y = xin * matrix.m[1][0] +
         yin * matrix.m[1][1] +
         matrix.m[1][3];
     w = xin * matrix.m[3][0] +
         yin * matrix.m[3][1] +
         matrix.m[3][3];
     if (w == 1.0f)
         return QPoint(qRound(x), qRound(y));
     else
         return QPoint(qRound(x / w), qRound(y / w));
 }
operator*() [7/11]
QPointF operator* (const QPointF & point, const QMatrix4x4 & matrix) inline
Definition at line 744 of file qmatrix4x4.h.
 {
     qreal xin, yin;
     qreal x, y, w;
     xin = point.x();
     yin = point.y();
     x = xin * matrix.m[0][0] +
         yin * matrix.m[0][1] +
         matrix.m[0][3];
     y = xin * matrix.m[1][0] +
         yin * matrix.m[1][1] +
         matrix.m[1][3];
     w = xin * matrix.m[3][0] +
         yin * matrix.m[3][1] +
         matrix.m[3][3];
     if (w == 1.0f) {
         return QPointF(qreal(x), qreal(y));
     } else {
         return QPointF(qreal(x / w), qreal(y / w));
     }
 }
operator*() [8/11]
QPoint operator* (const QMatrix4x4 & matrix, const QPoint & point) inline
Definition at line 766 of file qmatrix4x4.h.
 {
     qreal xin, yin;
     qreal x, y, w;
     xin = point.x();
     yin = point.y();
     if (matrix.flagBits == QMatrix4x4::Identity) {
         return point;
     } else if (matrix.flagBits == QMatrix4x4::Translation) {
         return QPoint(qRound(xin + matrix.m[3][0]),
                       qRound(yin + matrix.m[3][1]));
     } else if (matrix.flagBits ==
                     (QMatrix4x4::Translation | QMatrix4x4::Scale)) {
         return QPoint(qRound(xin * matrix.m[0][0] + matrix.m[3][0]),
                       qRound(yin * matrix.m[1][1] + matrix.m[3][1]));
     } else if (matrix.flagBits == QMatrix4x4::Scale) {
         return QPoint(qRound(xin * matrix.m[0][0]),
                       qRound(yin * matrix.m[1][1]));
     } else {
         x = xin * matrix.m[0][0] +
             yin * matrix.m[1][0] +
             matrix.m[3][0];
         y = xin * matrix.m[0][1] +
             yin * matrix.m[1][1] +
             matrix.m[3][1];
         w = xin * matrix.m[0][3] +
             yin * matrix.m[1][3] +
             matrix.m[3][3];
         if (w == 1.0f)
             return QPoint(qRound(x), qRound(y));
         else
             return QPoint(qRound(x / w), qRound(y / w));
     }
 }
operator*() [9/11]
QPointF operator* (const QMatrix4x4 & matrix, const QPointF & point) inline
Definition at line 801 of file qmatrix4x4.h.
 {
     qreal xin, yin;
     qreal x, y, w;
     xin = point.x();
     yin = point.y();
     if (matrix.flagBits == QMatrix4x4::Identity) {
         return point;
     } else if (matrix.flagBits == QMatrix4x4::Translation) {
         return QPointF(xin + matrix.m[3][0],
                        yin + matrix.m[3][1]);
     } else if (matrix.flagBits ==
                     (QMatrix4x4::Translation | QMatrix4x4::Scale)) {
         return QPointF(xin * matrix.m[0][0] + matrix.m[3][0],
                        yin * matrix.m[1][1] + matrix.m[3][1]);
     } else if (matrix.flagBits == QMatrix4x4::Scale) {
         return QPointF(xin * matrix.m[0][0],
                        yin * matrix.m[1][1]);
     } else {
         x = xin * matrix.m[0][0] +
             yin * matrix.m[1][0] +
             matrix.m[3][0];
         y = xin * matrix.m[0][1] +
             yin * matrix.m[1][1] +
             matrix.m[3][1];
         w = xin * matrix.m[0][3] +
             yin * matrix.m[1][3] +
             matrix.m[3][3];
         if (w == 1.0f) {
             return QPointF(qreal(x), qreal(y));
         } else {
             return QPointF(qreal(x / w), qreal(y / w));
         }
     }
 }
operator*() [10/11]
QMatrix4x4 operator* (qreal factor, const QMatrix4x4 & matrix) inline
Definition at line 859 of file qmatrix4x4.h.
 {
     QMatrix4x4 m(1);
     m.m[0][0] = matrix.m[0][0] * factor;
     m.m[0][1] = matrix.m[0][1] * factor;
     m.m[0][2] = matrix.m[0][2] * factor;
     m.m[0][3] = matrix.m[0][3] * factor;
     m.m[1][0] = matrix.m[1][0] * factor;
     m.m[1][1] = matrix.m[1][1] * factor;
     m.m[1][2] = matrix.m[1][2] * factor;
     m.m[1][3] = matrix.m[1][3] * factor;
     m.m[2][0] = matrix.m[2][0] * factor;
     m.m[2][1] = matrix.m[2][1] * factor;
     m.m[2][2] = matrix.m[2][2] * factor;
     m.m[2][3] = matrix.m[2][3] * factor;
     m.m[3][0] = matrix.m[3][0] * factor;
     m.m[3][1] = matrix.m[3][1] * factor;
     m.m[3][2] = matrix.m[3][2] * factor;
     m.m[3][3] = matrix.m[3][3] * factor;
     return m;
 }
operator*() [11/11]
QMatrix4x4 operator* (const QMatrix4x4 & matrix, qreal factor) inline
Definition at line 881 of file qmatrix4x4.h.
 {
     QMatrix4x4 m(1);
     m.m[0][0] = matrix.m[0][0] * factor;
     m.m[0][1] = matrix.m[0][1] * factor;
     m.m[0][2] = matrix.m[0][2] * factor;
     m.m[0][3] = matrix.m[0][3] * factor;
     m.m[1][0] = matrix.m[1][0] * factor;
     m.m[1][1] = matrix.m[1][1] * factor;
     m.m[1][2] = matrix.m[1][2] * factor;
     m.m[1][3] = matrix.m[1][3] * factor;
     m.m[2][0] = matrix.m[2][0] * factor;
     m.m[2][1] = matrix.m[2][1] * factor;
     m.m[2][2] = matrix.m[2][2] * factor;
     m.m[2][3] = matrix.m[2][3] * factor;
     m.m[3][0] = matrix.m[3][0] * factor;
     m.m[3][1] = matrix.m[3][1] * factor;
     m.m[3][2] = matrix.m[3][2] * factor;
     m.m[3][3] = matrix.m[3][3] * factor;
     return m;
 }
operator+()
QMatrix4x4 operator+ (const QMatrix4x4 & m1, const QMatrix4x4 & m2) inline
Definition at line 485 of file qmatrix4x4.h.
Referenced by QMatrix4x4::QMatrix4x4().
 {
     QMatrix4x4 m(1);
     m.m[0][0] = m1.m[0][0] + m2.m[0][0];
     m.m[0][1] = m1.m[0][1] + m2.m[0][1];
     m.m[0][2] = m1.m[0][2] + m2.m[0][2];
     m.m[0][3] = m1.m[0][3] + m2.m[0][3];
     m.m[1][0] = m1.m[1][0] + m2.m[1][0];
     m.m[1][1] = m1.m[1][1] + m2.m[1][1];
     m.m[1][2] = m1.m[1][2] + m2.m[1][2];
     m.m[1][3] = m1.m[1][3] + m2.m[1][3];
     m.m[2][0] = m1.m[2][0] + m2.m[2][0];
     m.m[2][1] = m1.m[2][1] + m2.m[2][1];
     m.m[2][2] = m1.m[2][2] + m2.m[2][2];
     m.m[2][3] = m1.m[2][3] + m2.m[2][3];
     m.m[3][0] = m1.m[3][0] + m2.m[3][0];
     m.m[3][1] = m1.m[3][1] + m2.m[3][1];
     m.m[3][2] = m1.m[3][2] + m2.m[3][2];
     m.m[3][3] = m1.m[3][3] + m2.m[3][3];
     return m;
 }
operator-() [1/2]
QMatrix4x4 operator- (const QMatrix4x4 & m1, const QMatrix4x4 & m2) inline
Definition at line 507 of file qmatrix4x4.h.
Referenced by QMatrix4x4::QMatrix4x4().
 {
     QMatrix4x4 m(1);
     m.m[0][0] = m1.m[0][0] - m2.m[0][0];
     m.m[0][1] = m1.m[0][1] - m2.m[0][1];
     m.m[0][2] = m1.m[0][2] - m2.m[0][2];
     m.m[0][3] = m1.m[0][3] - m2.m[0][3];
     m.m[1][0] = m1.m[1][0] - m2.m[1][0];
     m.m[1][1] = m1.m[1][1] - m2.m[1][1];
     m.m[1][2] = m1.m[1][2] - m2.m[1][2];
     m.m[1][3] = m1.m[1][3] - m2.m[1][3];
     m.m[2][0] = m1.m[2][0] - m2.m[2][0];
     m.m[2][1] = m1.m[2][1] - m2.m[2][1];
     m.m[2][2] = m1.m[2][2] - m2.m[2][2];
     m.m[2][3] = m1.m[2][3] - m2.m[2][3];
     m.m[3][0] = m1.m[3][0] - m2.m[3][0];
     m.m[3][1] = m1.m[3][1] - m2.m[3][1];
     m.m[3][2] = m1.m[3][2] - m2.m[3][2];
     m.m[3][3] = m1.m[3][3] - m2.m[3][3];
     return m;
 }
operator-() [2/2]
QMatrix4x4 operator- (const QMatrix4x4 & matrix) inline
Definition at line 837 of file qmatrix4x4.h.
 {
     QMatrix4x4 m(1);
     m.m[0][0] = -matrix.m[0][0];
     m.m[0][1] = -matrix.m[0][1];
     m.m[0][2] = -matrix.m[0][2];
     m.m[0][3] = -matrix.m[0][3];
     m.m[1][0] = -matrix.m[1][0];
     m.m[1][1] = -matrix.m[1][1];
     m.m[1][2] = -matrix.m[1][2];
     m.m[1][3] = -matrix.m[1][3];
     m.m[2][0] = -matrix.m[2][0];
     m.m[2][1] = -matrix.m[2][1];
     m.m[2][2] = -matrix.m[2][2];
     m.m[2][3] = -matrix.m[2][3];
     m.m[3][0] = -matrix.m[3][0];
     m.m[3][1] = -matrix.m[3][1];
     m.m[3][2] = -matrix.m[3][2];
     m.m[3][3] = -matrix.m[3][3];
     return m;
 }
operator/()
Q_GUI_EXPORT QMatrix4x4 operator/ (const QMatrix4x4 & matrix, qreal divisor)
Referenced by QMatrix4x4::QMatrix4x4(), and QMatrix4x4::setRow().
operator<<() [1/2]
Q_GUI_EXPORT QDebug operator<< (QDebug dbg, const QMatrix4x4 & m)
Definition at line 1955 of file qmatrix4x4.cpp.
Referenced by QMatrix4x4::constData(), and QMatrix4x4::data().
 {
     // Create a string that represents the matrix type.
     QByteArray bits;
     if ((m.flagBits & QMatrix4x4::Identity) != 0)
         bits += "Identity,";
     if ((m.flagBits & QMatrix4x4::General) != 0)
         bits += "General,";
     if ((m.flagBits & QMatrix4x4::Translation) != 0)
         bits += "Translation,";
     if ((m.flagBits & QMatrix4x4::Scale) != 0)
         bits += "Scale,";
     if ((m.flagBits & QMatrix4x4::Rotation) != 0)
         bits += "Rotation,";
     if (bits.size() > 0)
         bits = bits.left(bits.size() - 1);
     // Output in row-major order because it is more human-readable.
     dbg.nospace() << "QMatrix4x4(type:" << bits.constData() << endl
         << qSetFieldWidth(10)
         << m(0, 0) << m(0, 1) << m(0, 2) << m(0, 3) << endl
         << m(1, 0) << m(1, 1) << m(1, 2) << m(1, 3) << endl
         << m(2, 0) << m(2, 1) << m(2, 2) << m(2, 3) << endl
         << m(3, 0) << m(3, 1) << m(3, 2) << m(3, 3) << endl
         << qSetFieldWidth(0) << ')';
     return dbg.space();
 }
operator<<() [2/2]
Q_GUI_EXPORT QDataStream& operator<< (QDataStream & , const QMatrix4x4 &) related
Definition at line 2000 of file qmatrix4x4.cpp.
 {
     for (int row = 0; row < 4; ++row)
         for (int col = 0; col < 4; ++col)
             stream << double(matrix(row, col));
     return stream;
 }
operator>>()
Q_GUI_EXPORT QDataStream& operator>> (QDataStream & , QMatrix4x4 &) related
Definition at line 2021 of file qmatrix4x4.cpp.
Referenced by QMatrix4x4::data().
 {
     double x;
     for (int row = 0; row < 4; ++row) {
         for (int col = 0; col < 4; ++col) {
             stream >> x;
             matrix(row, col) = qreal(x);
         }
     }
     matrix.optimize();
     return stream;
 }
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QMatrix4x4 , Q_MOVABLE_TYPE)
qFuzzyCompare()
bool qFuzzyCompare (const QMatrix4x4 & m1, const QMatrix4x4 & m2) inline
Definition at line 903 of file qmatrix4x4.h.
Referenced by QMatrix4x4::QMatrix4x4().
 {
     return qFuzzyCompare(m1.m[0][0], m2.m[0][0]) &&
            qFuzzyCompare(m1.m[0][1], m2.m[0][1]) &&
            qFuzzyCompare(m1.m[0][2], m2.m[0][2]) &&
            qFuzzyCompare(m1.m[0][3], m2.m[0][3]) &&
            qFuzzyCompare(m1.m[1][0], m2.m[1][0]) &&
            qFuzzyCompare(m1.m[1][1], m2.m[1][1]) &&
            qFuzzyCompare(m1.m[1][2], m2.m[1][2]) &&
            qFuzzyCompare(m1.m[1][3], m2.m[1][3]) &&
            qFuzzyCompare(m1.m[2][0], m2.m[2][0]) &&
            qFuzzyCompare(m1.m[2][1], m2.m[2][1]) &&
            qFuzzyCompare(m1.m[2][2], m2.m[2][2]) &&
            qFuzzyCompare(m1.m[2][3], m2.m[2][3]) &&
            qFuzzyCompare(m1.m[3][0], m2.m[3][0]) &&
            qFuzzyCompare(m1.m[3][1], m2.m[3][1]) &&
            qFuzzyCompare(m1.m[3][2], m2.m[3][2]) &&
            qFuzzyCompare(m1.m[3][3], m2.m[3][3]);
 }
qGenericMatrixFromMatrix4x4()
template<int N, int M> QT_DEPRECATED QGenericMatrix<N, M, qreal> qGenericMatrixFromMatrix4x4 (const QMatrix4x4 & matrix) related
Definition at line 997 of file qmatrix4x4.h.
 {
     QGenericMatrix<N, M, qreal> result;
     const qreal *m = matrix.constData();
     qreal *values = result.data();
     for (int col = 0; col < N; ++col) {
         for (int row = 0; row < M; ++row) {
             if (col < 4 && row < 4)
                 values[col * M + row] = m[col * 4 + row];
             else if (col == row)
                 values[col * M + row] = 1.0f;
             else
                 values[col * M + row] = 0.0f;
         }
     }
     return result;
 }
qGenericMatrixToMatrix4x4()
template<int N, int M> QT_DEPRECATED QMatrix4x4 qGenericMatrixToMatrix4x4 (const QGenericMatrix< N, M, qreal > & matrix) related
Definition at line 991 of file qmatrix4x4.h.
 {
     return QMatrix4x4(matrix.constData(), N, M);
 }