Qt 4.8: /src/gui/math3d/qmatrix4x4.cpp File Reference
qmatrix4x4.cpp File Reference
#include "qmatrix4x4.h"
#include <QtCore/qmath.h>
#include <QtCore/qvariant.h>
#include <QtGui/qmatrix.h>
#include <QtGui/qtransform.h>
Functions
static qreal matrixDet3 (const qreal m[4][4], int col0, int col1, int col2, int row0, int row1, int row2)
static qreal matrixDet4 (const qreal m[4][4])
QDebug operator<< (QDebug dbg, const QMatrix4x4 &m)
QDataStream & operator<< (QDataStream &stream, const QMatrix4x4 &matrix)
QDataStream & operator>> (QDataStream &stream, QMatrix4x4 &matrix)
Variables
static const qreal inv_dist_to_plane = 1. / 1024.
Function Documentation
matrixDet3()
static qreal matrixDet3 (const qreal m[4][4], int col0, int col1, int col2, int row0, int row1, int row2) inline static
Definition at line 363 of file qmatrix4x4.cpp.
Referenced by QMatrix4x4::inverted(), matrixDet4(), QMatrix4x4::normalMatrix(), and QMatrix4x4::QMatrix4x4().
 {
     return m[col0][row0] *
                 (m[col1][row1] * m[col2][row2] -
                  m[col1][row2] * m[col2][row1]) -
            m[col1][row0] *
                 (m[col0][row1] * m[col2][row2] -
                  m[col0][row2] * m[col2][row1]) +
            m[col2][row0] *
                 (m[col0][row1] * m[col1][row2] -
                  m[col0][row2] * m[col1][row1]);
 }
matrixDet4()
static qreal matrixDet4 (const qreal m[4][4]) inline static
Definition at line 378 of file qmatrix4x4.cpp.
Referenced by QMatrix4x4::determinant(), and QMatrix4x4::inverted().
 {
     qreal det;
     det  = m[0][0] * matrixDet3(m, 1, 2, 3, 1, 2, 3);
     det -= m[1][0] * matrixDet3(m, 0, 2, 3, 1, 2, 3);
     det += m[2][0] * matrixDet3(m, 0, 1, 3, 1, 2, 3);
     det -= m[3][0] * matrixDet3(m, 0, 1, 2, 1, 2, 3);
     return det;
 }
operator<<() [1/2]
QDebug operator<< (QDebug dbg, const QMatrix4x4 & m)
Definition at line 1955 of file qmatrix4x4.cpp.
Referenced by QMatrix4x4::constData(), and QMatrix4x4::data().
 {
     // Create a string that represents the matrix type.
     QByteArray bits;
     if ((m.flagBits & QMatrix4x4::Identity) != 0)
         bits += "Identity,";
     if ((m.flagBits & QMatrix4x4::General) != 0)
         bits += "General,";
     if ((m.flagBits & QMatrix4x4::Translation) != 0)
         bits += "Translation,";
     if ((m.flagBits & QMatrix4x4::Scale) != 0)
         bits += "Scale,";
     if ((m.flagBits & QMatrix4x4::Rotation) != 0)
         bits += "Rotation,";
     if (bits.size() > 0)
         bits = bits.left(bits.size() - 1);
     // Output in row-major order because it is more human-readable.
     dbg.nospace() << "QMatrix4x4(type:" << bits.constData() << endl
         << qSetFieldWidth(10)
         << m(0, 0) << m(0, 1) << m(0, 2) << m(0, 3) << endl
         << m(1, 0) << m(1, 1) << m(1, 2) << m(1, 3) << endl
         << m(2, 0) << m(2, 1) << m(2, 2) << m(2, 3) << endl
         << m(3, 0) << m(3, 1) << m(3, 2) << m(3, 3) << endl
         << qSetFieldWidth(0) << ')';
     return dbg.space();
 }
operator<<() [2/2]
QDataStream& operator<< (QDataStream & stream, const QMatrix4x4 & matrix) related
Definition at line 2000 of file qmatrix4x4.cpp.
 {
     for (int row = 0; row < 4; ++row)
         for (int col = 0; col < 4; ++col)
             stream << double(matrix(row, col));
     return stream;
 }
operator>>()
QDataStream& operator>> (QDataStream & stream, QMatrix4x4 & matrix) related
Definition at line 2021 of file qmatrix4x4.cpp.
Referenced by QMatrix4x4::data().
 {
     double x;
     for (int row = 0; row < 4; ++row) {
         for (int col = 0; col < 4; ++col) {
             stream >> x;
             matrix(row, col) = qreal(x);
         }
     }
     matrix.optimize();
     return stream;
 }
Variable Documentation
inv_dist_to_plane
const qreal inv_dist_to_plane = 1. / 1024. static
Definition at line 64 of file qmatrix4x4.cpp.
Referenced by QMatrix4x4::projectedRotate(), and QMatrix4x4::toTransform().