Qt 4.8: /src/corelib/kernel/qmath.h File Reference
qmath.h File Reference
#include <math.h>
#include <QtCore/qglobal.h>
Macros
#define M_PI (3.14159265358979323846)
#define QT_SINE_TABLE_SIZE 256
Functions
qreal qAcos (qreal v)
qreal qAsin (qreal v)
qreal qAtan (qreal v)
qreal qAtan2 (qreal x, qreal y)
int qCeil (qreal v)
qreal qCos (qreal v)
qreal qExp (qreal v)
qreal qFabs (qreal v)
qreal qFastCos (qreal x)
qreal qFastSin (qreal x)
int qFloor (qreal v)
qreal qLn (qreal v)
qreal qPow (qreal x, qreal y)
qreal qSin (qreal v)
qreal qSqrt (qreal v)
qreal qTan (qreal v)
Variables
Q_CORE_EXPORT const qreal qt_sine_table [QT_SINE_TABLE_SIZE]
Macro Definition Documentation
M_PI
#define M_PI (3.14159265358979323846)
Definition at line 261 of file qmath.h.
Referenced by QDeclarativeParentChangePrivate::doChange(), QCoreGraphicsPaintEngine::drawEllipse(), QQuaternion::fromAxisAndAngle(), QMatrix4x4::perspective(), QMatrix4x4::projectedRotate(), qFastCos(), qFastSin(), QMatrix4x4::rotate(), QDeclarativeParentAnimation::transition(), and QUIKitWindow::updateGeometryAndOrientation().
QT_SINE_TABLE_SIZE
#define QT_SINE_TABLE_SIZE 256
Definition at line 59 of file qmath.h.
Referenced by qFastCos(), and qFastSin().
Function Documentation
qAcos()
qreal qAcos (qreal v) inline
Definition at line 141 of file qmath.h.
Referenced by addCircle(), QLineF::angle(), and QQuaternion::slerp().
 {
 #ifdef Q_OS_SYMBIAN
     TReal acos_v;
     Math::ACos(acos_v, static_cast<TReal>(v));
     return static_cast<qreal>(acos_v);
 #else
 #    ifdef QT_USE_MATH_H_FLOATS
         if (sizeof(qreal) == sizeof(float))
             return acosf(float(v));
         else
 #    endif
            return acos(v);
 #endif
 }
qAsin()
qreal qAsin (qreal v) inline
Definition at line 157 of file qmath.h.
 {
 #ifdef Q_OS_SYMBIAN
     TReal asin_v;
     Math::ASin(asin_v, static_cast<TReal>(v));
     return static_cast<qreal>(asin_v);
 #else
 #    ifdef QT_USE_MATH_H_FLOATS
         if (sizeof(qreal) == sizeof(float))
             return asinf(float(v));
         else
 #    endif
             return asin(v);
 #endif
 }
qAtan()
qreal qAtan (qreal v) inline
Definition at line 173 of file qmath.h.
Referenced by QStyleHelper::angle().
 {
 #ifdef Q_OS_SYMBIAN
     TReal atan_v;
     Math::ATan(atan_v, static_cast<TReal>(v));
     return static_cast<qreal>(atan_v);
 #else
 #    ifdef QT_USE_MATH_H_FLOATS
         if(sizeof(qreal) == sizeof(float))
             return atanf(float(v));
         else
 #    endif
             return atan(v);
 #endif
 }
qAtan2()
qreal qAtan2 (qreal x, qreal y) inline
Definition at line 189 of file qmath.h.
Referenced by QLineF::angle(), computeAngle(), pathArc(), qt_fetch_conical_gradient(), and QDialPrivate::valueFromPoint().
 {
 #ifdef Q_OS_SYMBIAN
     TReal atan2_v;
     Math::ATan(atan2_v, static_cast<TReal>(x), static_cast<TReal>(y));
     return static_cast<qreal>(atan2_v);
 #else
 #    ifdef QT_USE_MATH_H_FLOATS
         if(sizeof(qreal) == sizeof(float))
             return atan2f(float(x), float(y));
         else
 #    endif
             return atan2(x, y);
 #endif
 }
qCeil()
int qCeil (qreal v) inline
Definition at line 63 of file qmath.h.
Referenced by QFontEngine::alphaMapForGlyph(), alphaMapFromPath(), QSvgAnimateColor::apply(), QDeclarativePath::createPointCache(), QCommandLinkButtonPrivate::descriptionHeight(), QDeclarativePaintedItem::dirtyCache(), QDeclarativeFlow::doPositioning(), QPaintEngine::drawImage(), QRasterPaintEngine::drawImage(), drawTextItemDecoration(), QOpenGLPaintEngine::drawTiledPixmap(), QTextDocumentLayout::dynamicPageCount(), fetchTransformedBilinear(), QTimeLine::frameForTime(), QDeclarativeRectangle::generateRoundedRect(), generateWavyPixmap(), QRasterPaintEnginePrivate::getPenFunc(), intmaxlog(), QPrintPreviewWidgetPrivate::layoutPages(), QPaintBuffer::metric(), QDeclarativePaintedItem::paint(), pathArc(), QPdf::patternForBrush(), QGLPixmapBlurFilter::processGL(), qDrawBorderPixmap(), qSubImage(), qt_scale_image_16bit(), qt_scale_image_32bit(), qt_transform_image(), QMdi::RegularTiler::rearrange(), QComboBoxPrivate::recomputeSizeHint(), QMdiAreaPrivate::resizeToMinimumTileSize(), QSvgAnimateTransform::resolveMatrix(), QSvgPaintEngine::saveGradientStops(), QDeclarativeTextPrivate::setupTextLayout(), QLabelPrivate::sizeForWidth(), QMacStyle::subControlRect(), QCommonStyle::subElementRect(), QItemDelegate::textRectangle(), QRectF::toAlignedRect(), QDeclarativeListView::trackedPositionChanged(), QDeclarativeTextEdit::updateSize(), QCommonStylePrivate::viewItemSize(), and QPicturePaintEngine::writeCmdLength().
 {
 #ifdef QT_USE_MATH_H_FLOATS
     if (sizeof(qreal) == sizeof(float))
         return int(ceilf(float(v)));
     else
 #endif
         return int(ceil(v));
 }
qCos()
qreal qCos (qreal v) inline
Definition at line 109 of file qmath.h.
Referenced by calcArrow(), QStyleHelper::calcLines(), QStyleHelper::calcRadialPos(), QQuaternion::fromAxisAndAngle(), QLineF::fromPolar(), pathArc(), pathArcSegment(), QMatrix4x4::perspective(), QMatrix4x4::projectedRotate(), qt_t_for_arc_angle(), QAccessibleDial::rect(), QMatrix::rotate(), QTransform::rotate(), QMatrix4x4::rotate(), QTransform::rotateRadians(), and QLineF::setAngle().
 {
 #ifdef Q_OS_SYMBIAN
     TReal cos_v;
     Math::Cos(cos_v, static_cast<TReal>(v));
     return static_cast<qreal>(cos_v);
 #else
 #    ifdef QT_USE_MATH_H_FLOATS
         if (sizeof(qreal) == sizeof(float))
             return cosf(float(v));
         else
 #    endif
             return cos(v);
 #endif
 }
qExp()
qreal qExp (qreal v) inline
Definition at line 231 of file qmath.h.
 {
 #ifdef Q_OS_SYMBIAN
     TReal exp_v;
     Math::Exp(exp_v, static_cast<TReal>(v));
     return static_cast<qreal>(exp_v);
 #else
     // only one signature
     // exists, exp(double)
     return exp(v);
 #endif
 }
qFabs()
qreal qFabs (qreal v) inline
Definition at line 83 of file qmath.h.
 {
 #ifdef QT_USE_MATH_H_FLOATS
     if(sizeof(qreal) == sizeof(float))
         return fabsf(float(v));
     else
 #endif
         return fabs(v);
 }
qFastCos()
qreal qFastCos (qreal x) inline
Definition at line 274 of file qmath.h.
Referenced by QGL2PaintEngineExPrivate::drawPixmapFragments(), and QTriangulatingStroker::process().
 {
     int ci = int(x * (0.5 * QT_SINE_TABLE_SIZE / M_PI)); // Would be more accurate with qRound, but slower.
     qreal d = x - ci * (2.0 * M_PI / QT_SINE_TABLE_SIZE);
     int si = ci + QT_SINE_TABLE_SIZE / 4;
     si &= QT_SINE_TABLE_SIZE - 1;
     ci &= QT_SINE_TABLE_SIZE - 1;
     return qt_sine_table[si] - (qt_sine_table[ci] + 0.5 * qt_sine_table[si] * d) * d;
 }
qFastSin()
qreal qFastSin (qreal x) inline
Definition at line 264 of file qmath.h.
Referenced by QGL2PaintEngineExPrivate::drawPixmapFragments(), and QTriangulatingStroker::process().
 {
     int si = int(x * (0.5 * QT_SINE_TABLE_SIZE / M_PI)); // Would be more accurate with qRound, but slower.
     qreal d = x - si * (2.0 * M_PI / QT_SINE_TABLE_SIZE);
     int ci = si + QT_SINE_TABLE_SIZE / 4;
     si &= QT_SINE_TABLE_SIZE - 1;
     ci &= QT_SINE_TABLE_SIZE - 1;
     return qt_sine_table[si] + (qt_sine_table[ci] - 0.5 * qt_sine_table[si] * d) * d;
 }
qFloor()
int qFloor (qreal v) inline
Definition at line 73 of file qmath.h.
Referenced by addSelectedRegionsToPath(), QFontEngine::alphaMapForGlyph(), alphaMapFromPath(), QSvgAnimateColor::apply(), QGL2PaintEngineExPrivate::drawCachedGlyphs(), QRasterPaintEngine::drawCachedGlyphs(), QPaintEngine::drawImage(), QRasterPaintEngine::drawImage(), QX11PaintEngine::drawPoints(), QRasterPaintEngine::drawTextItem(), drawTextItemDecoration(), QX11PaintEnginePrivate::fillPolygon_dev(), generateWavyPixmap(), QPrintPreviewWidgetPrivate::layoutPages(), QFontDatabase::loadXlfd(), QDeclarativePaintedItem::paint(), QPdf::patternForBrush(), QDashStroker::processCurrentSubpath(), qDrawEdge(), qSubImage(), qt_curves_for_arc(), qt_find_ellipse_coords(), qt_scale_image_16bit(), qt_scale_image_32bit(), qt_transform_image(), QSvgAnimateTransform::resolveMatrix(), setPenAndDrawBackground(), QRasterPaintEngine::stroke(), QRectF::toAlignedRect(), and QPicturePaintEngine::writeCmdLength().
 {
 #ifdef QT_USE_MATH_H_FLOATS
     if (sizeof(qreal) == sizeof(float))
         return int(floorf(float(v)));
     else
 #endif
         return int(floor(v));
 }
qLn()
qreal qLn (qreal v) inline
Definition at line 221 of file qmath.h.
Referenced by intmaxlog().
 {
 #ifdef QT_USE_MATH_H_FLOATS
     if (sizeof(qreal) == sizeof(float))
         return logf(float(v));
     else
 #endif
         return log(v);
 }
qPow()
qreal qPow (qreal x, qreal y) inline
Definition at line 244 of file qmath.h.
Referenced by QODBCResult::exec(), expblur(), growthFactorBelowPreferredSize(), qt_build_pow_tables(), and qt_sRGB_to_linear_RGB().
 {
 #ifdef Q_OS_SYMBIAN
     TReal pow_v;
     Math::Pow(pow_v, static_cast<TReal>(x), static_cast<TReal>(y));
     return static_cast<qreal>(pow_v);
 #else
 #    ifdef QT_USE_MATH_H_FLOATS
         if (sizeof(qreal) == sizeof(float))
             return powf(float(x), float(y));
         else
 #    endif
             return pow(x, y);
 #endif
 }
qSin()
qreal qSin (qreal v) inline
Definition at line 93 of file qmath.h.
Referenced by calcArrow(), QStyleHelper::calcLines(), QStyleHelper::calcRadialPos(), QQuaternion::fromAxisAndAngle(), QLineF::fromPolar(), pathArc(), pathArcSegment(), QMatrix4x4::perspective(), QMatrix4x4::projectedRotate(), qt_t_for_arc_angle(), QAccessibleDial::rect(), QMatrix::rotate(), QTransform::rotate(), QMatrix4x4::rotate(), QTransform::rotateRadians(), QLineF::setAngle(), and QQuaternion::slerp().
 {
 #ifdef Q_OS_SYMBIAN
     TReal sin_v;
     Math::Sin(sin_v, static_cast<TReal>(v));
     return static_cast<qreal>(sin_v);
 #else
 #    ifdef QT_USE_MATH_H_FLOATS
         if (sizeof(qreal) == sizeof(float))
             return sinf(float(v));
         else
 #    endif
             return sin(v);
 #endif
 }
qSqrt()
qreal qSqrt (qreal v) inline
Definition at line 205 of file qmath.h.
Referenced by addCircle(), QDeclarativeParentChangePrivate::doChange(), QOpenGLPaintEngine::drawPath(), drawTrapezoid(), QToolBarLayout::expandedSize(), RadialFetchPlain::fetch(), QDeclarativeGridViewPrivate::flick(), QDeclarativeListViewPrivate::flick(), QQuaternion::fromAxisAndAngle(), QPrintPreviewWidgetPrivate::layoutPages(), QVector2D::length(), QVector3D::length(), QVector4D::length(), QQuaternion::length(), QLineF::length(), QStyleOptionGraphicsItem::levelOfDetailFromTransform(), QFontEngineFT::loadTransformedGlyphSet(), QMatrix::mapToPolygon(), QAccessibleWidget::navigate(), QVector2D::normalize(), normalize(), QVector3D::normalize(), QVector4D::normalize(), QQuaternion::normalize(), QVector2D::normalized(), QVector3D::normalized(), QVector4D::normalized(), QQuaternion::normalized(), pathArc(), QMatrix4x4::projectedRotate(), qIntSqrtInt(), qt_painterpath_bezier_extrema(), qt_scaleForTransform(), quadraticRoots(), QMdi::RegularTiler::rearrange(), QSmoothedAnimation::recalc(), QMdiAreaPrivate::resizeToMinimumTileSize(), QMatrix4x4::rotate(), QGLEllipseMaskGenerator::screenRect(), soft_light_op(), QBezier::stationaryYPoints(), QTessellator::tessellateRect(), QDeclarativeParentAnimation::transition(), QLineF::unitVector(), and QOpenGLPaintEnginePrivate::updateGradient().
 {
 #ifdef Q_OS_SYMBIAN
     TReal sqrt_v;
     Math::Sqrt(sqrt_v, static_cast<TReal>(v));
     return static_cast<qreal>(sqrt_v);
 #else
 #    ifdef QT_USE_MATH_H_FLOATS
         if (sizeof(qreal) == sizeof(float))
             return sqrtf(float(v));
         else
 #    endif
             return sqrt(v);
 #endif
 }
qTan()
qreal qTan (qreal v) inline
Definition at line 125 of file qmath.h.
Referenced by parseTransformationMatrix(), and QSvgAnimateTransform::resolveMatrix().
 {
 #ifdef Q_OS_SYMBIAN
     TReal tan_v;
     Math::Tan(tan_v, static_cast<TReal>(v));
     return static_cast<qreal>(tan_v);
 #else
 #    ifdef QT_USE_MATH_H_FLOATS
         if (sizeof(qreal) == sizeof(float))
             return tanf(float(v));
         else
 #    endif
             return tan(v);
 #endif
 }
Variable Documentation
qt_sine_table
Q_CORE_EXPORT const qreal qt_sine_table[QT_SINE_TABLE_SIZE]
Definition at line 46 of file qmath.cpp.