Qt 4.8: /src/gui/painting/qmath_p.h File Reference
qmath_p.h File Reference
#include <math.h>
#include <qmath.h>
Functions
int qIntSqrtInt (int v)
Variables
static const qreal Q_2PI = qreal(6.28318530717958647693)
static const qreal Q_PI = qreal(3.14159265358979323846)
static const qreal Q_PI2 = qreal(1.57079632679489661923)
Function Documentation
qIntSqrtInt()
int qIntSqrtInt (int v) inline
Definition at line 65 of file qmath_p.h.
Referenced by soft_light_op().
 {
     return static_cast<int>(qSqrt(static_cast<qreal>(v)));
 }
Variable Documentation
Q_2PI
const qreal Q_2PI = qreal(6.28318530717958647693) static
Definition at line 62 of file qmath_p.h.
Q_PI
const qreal Q_PI = qreal(3.14159265358979323846) static
Definition at line 61 of file qmath_p.h.
Referenced by addCircle(), QStyleHelper::angle(), calcArrow(), QStyleHelper::calcLines(), QStyleHelper::calcRadialPos(), computeAngle(), QGL2PaintEngineExPrivate::drawPixmapFragments(), pathArc(), pathArcSegment(), QTriangulatingStroker::process(), qt_fetch_conical_gradient(), qt_t_for_arc_angle(), QAccessibleDial::rect(), QSpanData::setup(), QDial::setWrapping(), QETWidget::translateTabletEvent(), QGL2PaintEngineExPrivate::updateBrushUniforms(), QOpenGLPaintEnginePrivate::updateGradient(), and QDialPrivate::valueFromPoint().
Q_PI2
const qreal Q_PI2 = qreal(1.57079632679489661923) static
Definition at line 63 of file qmath_p.h.