Qt 4.8: /src/gui/widgets/qmdisubwindow.cpp File Reference
qmdisubwindow.cpp File Reference
#include "qmdisubwindow_p.h"
#include <QApplication>
#include <QStylePainter>
#include <QVBoxLayout>
#include <QMouseEvent>
#include <QWhatsThis>
#include <QToolTip>
#include <QMainWindow>
#include <QScrollBar>
#include <QDebug>
#include <QScopedValueRollback>
#include <QMacStyle>
#include <QMdiArea>
#include "moc_qmdisubwindow.cpp"
#include "qmdisubwindow.moc"
Classes
class QMdi::ControlLabel
class QMdi::ControllerWidget
Namespaces
QMdi
Macros
#define COLOR_GRADIENTACTIVECAPTION 27
#define COLOR_GRADIENTINACTIVECAPTION 28
#define SPI_GETGRADIENTCAPTIONS 0x1008
Functions
static QRgb colorref2qrgb (COLORREF col)
static int getMoveDeltaComponent (uint cflags, uint moveFlag, uint resizeFlag, int delta, int maxDelta, int minDelta)
static int getResizeDeltaComponent (uint cflags, uint resizeFlag, uint resizeReverseFlag, int delta)
static bool isChildOfQMdiSubWindow (const QWidget *child)
static bool isChildOfTabbedQMdiArea (const QMdiSubWindow *child)
static bool isHoverControl (QStyle::SubControl control)
template<typename T >
static ControlElement< T > * ptr (QWidget *widget)
QString qt_setWindowTitle_helperHelper (const QString &, const QWidget *)
Returns a modified window title with the [*] place holder replaced according to the rules described in QWidget::setWindowTitle.
static void showToolTip (QHelpEvent *helpEvent, QWidget *widget, const QStyleOptionComplex &opt, QStyle::ComplexControl complexControl, QStyle::SubControl subControl)
Variables
static const int BoundaryMargin = 5
static const QStyle::StandardPixmap ButtonPixmaps []
static const Qt::WindowFlags CustomizeWindowFlags
static const int NumButtonPixmaps = sizeof(ButtonPixmaps) / sizeof(ButtonPixmaps[0])
static const int NumSubControls = sizeof(SubControls) / sizeof(SubControls[0])
static const QStyle::SubControl SubControls []
Macro Definition Documentation
COLOR_GRADIENTACTIVECAPTION
#define COLOR_GRADIENTACTIVECAPTION 27
Referenced by QMdiSubWindowPrivate::desktopPalette().
COLOR_GRADIENTINACTIVECAPTION
#define COLOR_GRADIENTINACTIVECAPTION 28
Referenced by QMdiSubWindowPrivate::desktopPalette().
SPI_GETGRADIENTCAPTIONS
#define SPI_GETGRADIENTCAPTIONS 0x1008
Referenced by QMdiSubWindowPrivate::desktopPalette().
Function Documentation
colorref2qrgb()
static QRgb colorref2qrgb (COLORREF col) inline static
Definition at line 306 of file qmdisubwindow.cpp.
Referenced by QMdiSubWindowPrivate::desktopPalette().
 {
     return qRgb(GetRValue(col),GetGValue(col),GetBValue(col));
 }
getMoveDeltaComponent()
static int getMoveDeltaComponent (uint cflags, uint moveFlag, uint resizeFlag, int delta, int maxDelta, int minDelta) inline static
Definition at line 219 of file qmdisubwindow.cpp.
Referenced by QMdiSubWindowPrivate::setNewGeometry().
 {
     if (cflags & moveFlag) {
         if (delta > 0)
             return (cflags & resizeFlag) ? qMin(delta, maxDelta) : delta;
         return (cflags & resizeFlag) ? qMax(delta, minDelta) : delta;
     }
     return 0;
 }
getResizeDeltaComponent()
static int getResizeDeltaComponent (uint cflags, uint resizeFlag, uint resizeReverseFlag, int delta) inline static
Definition at line 230 of file qmdisubwindow.cpp.
Referenced by QMdiSubWindowPrivate::setNewGeometry().
 {
     if (cflags & resizeFlag) {
         if (cflags & resizeReverseFlag)
             return -delta;
         return delta;
     }
     return 0;
 }
isChildOfQMdiSubWindow()
static bool isChildOfQMdiSubWindow (const QWidget * child) inline static
Definition at line 241 of file qmdisubwindow.cpp.
Referenced by QMdiSubWindowPrivate::drawTitleBarWhenMaximized().
 {
     Q_ASSERT(child);
     QWidget *parent = child->parentWidget();
     while (parent) {
         if (qobject_cast<QMdiSubWindow *>(parent))
             return true;
         parent = parent->parentWidget();
     }
     return false;
 }
isChildOfTabbedQMdiArea()
static bool isChildOfTabbedQMdiArea (const QMdiSubWindow * child) inline static
Definition at line 253 of file qmdisubwindow.cpp.
Referenced by QMdiSubWindowPrivate::drawTitleBarWhenMaximized(), QMdiSubWindow::maximizedButtonsWidget(), QMdiSubWindow::maximizedSystemMenuIconWidget(), QMdiSubWindowPrivate::menuBar(), QMdiSubWindowPrivate::removeButtonsFromMenuBar(), and QMdiSubWindowPrivate::showButtonsInMenuBar().
 {
     Q_ASSERT(child);
     if (QMdiArea *mdiArea = child->mdiArea()) {
         if (mdiArea->viewMode() == QMdiArea::TabbedView)
             return true;
     }
     return false;
 }
isHoverControl()
static bool isHoverControl (QStyle::SubControl control) inline static
Definition at line 300 of file qmdisubwindow.cpp.
Referenced by QMdiSubWindow::mouseMoveEvent().
 {
     return control != QStyle::SC_None && control != QStyle::SC_TitleBarLabel;
 }
ptr()
template<typename T > static ControlElement<T>* ptr (QWidget * widget) inline static
Definition at line 264 of file qmdisubwindow.cpp.
 {
     if (widget && widget->qt_metacast("ControlElement")
             && strcmp(widget->metaObject()->className(), T::staticMetaObject.className()) == 0) {
         return static_cast<ControlElement<T> *>(widget);
     }
     return 0;
 }
qt_setWindowTitle_helperHelper()
QString qt_setWindowTitle_helperHelper (const QString & title, const QWidget * widget)
Returns a modified window title with the [*] place holder replaced according to the rules described in QWidget::setWindowTitle.
This function assumes that "[*]" can be quoted by another "[*]", so it will replace two place holders by one and a single last one by either "*" or nothing depending on the modified flag.
Warning
This function is not part of the public interface.
Definition at line 6240 of file qwidget.cpp.
Referenced by QMdiSubWindowPrivate::getOperation(), and QMdiSubWindowPrivate::updateInternalWindowTitle().
 {
     Q_ASSERT(widget);
 #ifdef QT_EVAL
     extern QString qt_eval_adapt_window_title(const QString &title);
     QString cap = qt_eval_adapt_window_title(title);
 #else
     QString cap = title;
 #endif
     if (cap.isEmpty())
         return cap;
     QLatin1String placeHolder("[*]");
     int placeHolderLength = 3; // QLatin1String doesn't have length()
     int index = cap.indexOf(placeHolder);
     // here the magic begins
     while (index != -1) {
         index += placeHolderLength;
         int count = 1;
         while (cap.indexOf(placeHolder, index) == index) {
             ++count;
             index += placeHolderLength;
         }
         if (count%2) { // odd number of [*] -> replace last one
             int lastIndex = cap.lastIndexOf(placeHolder, index - 1);
             if (widget->isWindowModified()
              && widget->style()->styleHint(QStyle::SH_TitleBar_ModifyNotification, 0, widget))
                 cap.replace(lastIndex, 3, QWidget::tr("*"));
             else
                 cap.remove(lastIndex, 3);
         }
         index = cap.indexOf(placeHolder, index);
     }
     cap.replace(QLatin1String("[*][*]"), placeHolder);
     return cap;
 }
showToolTip()
static void showToolTip (QHelpEvent * helpEvent, QWidget * widget, const QStyleOptionComplex & opt, QStyle::ComplexControl complexControl, QStyle::SubControl subControl) static
Definition at line 313 of file qmdisubwindow.cpp.
Referenced by QMdiSubWindow::event(), QApplication::event(), QMdi::ControlLabel::event(), QMdi::ControllerWidget::event(), and QScriptToolTipProviderInterface::~QScriptToolTipProviderInterface().
 {
     Q_ASSERT(helpEvent);
     Q_ASSERT(helpEvent->type() == QEvent::ToolTip);
     Q_ASSERT(widget);
 #if defined(Q_WS_MAC) && !defined(QT_NO_STYLE_MAC)
     // Native Mac windows don't show tool tip.
     if (qobject_cast<QMacStyle *>(widget->style()))
         return;
 #endif
     // Convert CC_MdiControls to CC_TitleBar. Sub controls of different complex
     // controls cannot be in the same switch as they might have the same value.
     if (complexControl == QStyle::CC_MdiControls) {
         if (subControl == QStyle::SC_MdiMinButton)
             subControl = QStyle::SC_TitleBarMinButton;
         else if (subControl == QStyle::SC_MdiCloseButton)
             subControl = QStyle::SC_TitleBarCloseButton;
         else if (subControl == QStyle::SC_MdiNormalButton)
             subControl = QStyle::SC_TitleBarNormalButton;
         else
             subControl = QStyle::SC_None;
     }
     // Don't change the tooltip for the base widget itself.
     if (subControl == QStyle::SC_None)
         return;
     QString toolTip;
     switch (subControl) {
     case QStyle::SC_TitleBarMinButton:
         toolTip = QMdiSubWindow::tr("Minimize");
         break;
     case QStyle::SC_TitleBarMaxButton:
         toolTip = QMdiSubWindow::tr("Maximize");
         break;
     case QStyle::SC_TitleBarUnshadeButton:
         toolTip = QMdiSubWindow::tr("Unshade");
         break;
     case QStyle::SC_TitleBarShadeButton:
         toolTip = QMdiSubWindow::tr("Shade");
         break;
     case QStyle::SC_TitleBarNormalButton:
         if (widget->isMaximized() || !qobject_cast<QMdiSubWindow *>(widget))
             toolTip = QMdiSubWindow::tr("Restore Down");
         else
             toolTip = QMdiSubWindow::tr("Restore");
         break;
     case QStyle::SC_TitleBarCloseButton:
         toolTip = QMdiSubWindow::tr("Close");
         break;
     case QStyle::SC_TitleBarContextHelpButton:
         toolTip = QMdiSubWindow::tr("Help");
         break;
     case QStyle::SC_TitleBarSysMenu:
         toolTip = QMdiSubWindow::tr("Menu");
         break;
     default:
         break;
     }
     const QRect rect = widget->style()->subControlRect(complexControl, &opt, subControl, widget);
     QToolTip::showText(helpEvent->globalPos(), toolTip, widget, rect);
 }
Variable Documentation
BoundaryMargin
const int BoundaryMargin = 5 static
Definition at line 217 of file qmdisubwindow.cpp.
Referenced by QMdiSubWindowPrivate::setNewGeometry().
ButtonPixmaps
const QStyle::StandardPixmap ButtonPixmaps[] static
Initial value:
=
{
    QStyle::SP_TitleBarMinButton,
    QStyle::SP_TitleBarNormalButton,
    QStyle::SP_TitleBarCloseButton
}
Definition at line 199 of file qmdisubwindow.cpp.
CustomizeWindowFlags
const Qt::WindowFlags CustomizeWindowFlags static
Initial value:
=
      Qt::FramelessWindowHint
    | Qt::CustomizeWindowHint
    | Qt::WindowTitleHint
    | Qt::WindowSystemMenuHint
    | Qt::WindowMinimizeButtonHint
    | Qt::WindowMaximizeButtonHint
    | Qt::WindowMinMaxButtonsHint
Definition at line 207 of file qmdisubwindow.cpp.
NumButtonPixmaps
const int NumButtonPixmaps = sizeof(ButtonPixmaps) / sizeof(ButtonPixmaps[0]) static
Definition at line 205 of file qmdisubwindow.cpp.
NumSubControls
const int NumSubControls = sizeof(SubControls) / sizeof(SubControls[0]) static
Definition at line 197 of file qmdisubwindow.cpp.
Referenced by QMdiSubWindowPrivate::getRegion(), and QMdiSubWindowPrivate::sizeParameters().
SubControls
const QStyle::SubControl SubControls[] static
Initial value:
=
{
    QStyle::SC_TitleBarLabel,
    QStyle::SC_TitleBarSysMenu,
    QStyle::SC_TitleBarMinButton,
    QStyle::SC_TitleBarMaxButton,
    QStyle::SC_TitleBarShadeButton,
    QStyle::SC_TitleBarCloseButton,
    QStyle::SC_TitleBarNormalButton,
    QStyle::SC_TitleBarUnshadeButton,
    QStyle::SC_TitleBarContextHelpButton
}
Definition at line 185 of file qmdisubwindow.cpp.
Referenced by QWindowsVistaStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QMdiSubWindowPrivate::getRegion(), and QMdiSubWindowPrivate::sizeParameters().