Qt 4.8: /src/gui/widgets/qmdiarea.cpp File Reference
qmdiarea.cpp File Reference
#include "qmdiarea_p.h"
#include <QApplication>
#include <QStyle>
#include <QMacStyle>
#include <QChildEvent>
#include <QResizeEvent>
#include <QScrollBar>
#include <QtAlgorithms>
#include <QMutableListIterator>
#include <QPainter>
#include <QFontMetrics>
#include <QStyleOption>
#include <QDesktopWidget>
#include <QDebug>
#include <qmath.h>
#include <private/qlayoutengine_p.h>
#include "moc_qmdiarea.cpp"
Classes
class QMdiAreaTabBar
Functions
static QMdiArea * mdiAreaParent (QWidget *widget)
static bool sanityCheck (const QMdiSubWindow *const child, const char *where)
static bool sanityCheck (const QList< QWidget *> &widgets, const int index, const char *where)
static void setIndex (int *index, int candidate, int min, int max, bool isIncreasing)
static QTabBar::Shape tabBarShapeFrom (QTabWidget::TabShape shape, QTabWidget::TabPosition position)
static QString tabTextFor (QMdiSubWindow *subWindow)
static bool useScrollBar (const QRect &childrenRect, const QSize &maxViewportSize, Qt::Orientation orientation)
Function Documentation
mdiAreaParent()
static QMdiArea* mdiAreaParent (QWidget * widget) inline static
Definition at line 259 of file qmdiarea.cpp.
Referenced by QMdiArea::eventFilter().
 {
     if (!widget)
         return 0;
     QWidget *parent = widget->parentWidget();
     while (parent) {
         if (QMdiArea *area = qobject_cast<QMdiArea *>(parent))
             return area;
         parent = parent->parentWidget();
     }
     return 0;
 }
sanityCheck() [1/2]
static bool sanityCheck (const QMdiSubWindow *const child, const char * where) static
Definition at line 198 of file qmdiarea.cpp.
Referenced by QMdiAreaPrivate::_q_deactivateAllWindows(), QMdiArea::closeAllSubWindows(), QMdiArea::event(), QMdiAreaPrivate::internalRaise(), QMdiArea::minimumSizeHint(), QMdiAreaPrivate::place(), QMdi::RegularTiler::rearrange(), QMdi::SimpleCascader::rearrange(), QMdi::IconTiler::rearrange(), QMdiAreaPrivate::rearrange(), QMdiArea::removeSubWindow(), QMdiArea::resizeEvent(), QMdiAreaPrivate::scrollBarPolicyChanged(), QMdiArea::setupViewport(), and QMdiArea::sizeHint().
 {
     if (!child) {
         const char error[] = "null pointer";
         Q_ASSERT_X(false, where, error);
         qWarning("%s:%s", where, error);
         return false;
     }
     return true;
 }
sanityCheck() [2/2]
static bool sanityCheck (const QList< QWidget *> & widgets, const int index, const char * where) static
Definition at line 209 of file qmdiarea.cpp.
 {
     if (index < 0 || index >= widgets.size()) {
         const char error[] = "index out of range";
         Q_ASSERT_X(false, where, error);
         qWarning("%s:%s", where, error);
         return false;
     }
     if (!widgets.at(index)) {
         const char error[] = "null pointer";
         Q_ASSERT_X(false, where, error);
         qWarning("%s:%s", where, error);
         return false;
     }
     return true;
 }
setIndex()
static void setIndex (int * index, int candidate, int min, int max, bool isIncreasing) static
Definition at line 226 of file qmdiarea.cpp.
Referenced by QMdiAreaPrivate::nextVisibleSubWindow().
 {
     if (!index)
         return;
     if (isIncreasing) {
         if (candidate > max)
             *index = min;
         else
             *index = qMax(candidate, min);
     } else {
         if (candidate < min)
             *index = max;
         else
             *index = qMin(candidate, max);
     }
     Q_ASSERT(*index >= min && *index <= max);
 }
tabBarShapeFrom()
static QTabBar::Shape tabBarShapeFrom (QTabWidget::TabShape shape, QTabWidget::TabPosition position) inline static
Definition at line 274 of file qmdiarea.cpp.
Referenced by QMdiAreaPrivate::refreshTabBar(), QMdiAreaPrivate::setViewMode(), and QMdiAreaPrivate::updateTabBarGeometry().
 {
     const bool rounded = (shape == QTabWidget::Rounded);
     if (position == QTabWidget::North)
         return rounded ? QTabBar::RoundedNorth : QTabBar::TriangularNorth;
     if (position == QTabWidget::South)
         return rounded ? QTabBar::RoundedSouth : QTabBar::TriangularSouth;
     if (position == QTabWidget::East)
         return rounded ? QTabBar::RoundedEast : QTabBar::TriangularEast;
     if (position == QTabWidget::West)
         return rounded ? QTabBar::RoundedWest : QTabBar::TriangularWest;
     return QTabBar::RoundedNorth;
 }
tabTextFor()
static QString tabTextFor (QMdiSubWindow * subWindow) inline static
Definition at line 289 of file qmdiarea.cpp.
Referenced by QMdiAreaPrivate::appendChild(), QMdiArea::eventFilter(), and QMdiAreaPrivate::setViewMode().
 {
     if (!subWindow)
         return QString();
     QString title = subWindow->windowTitle();
     if (subWindow->isWindowModified()) {
         title.replace(QLatin1String("[*]"), QLatin1String("*"));
     } else {
         extern QString qt_setWindowTitle_helperHelper(const QString&, const QWidget*);
         title = qt_setWindowTitle_helperHelper(title, subWindow);
     }
     return title.isEmpty() ? QMdiArea::tr("(Untitled)") : title;
 }
useScrollBar()
static bool useScrollBar (const QRect & childrenRect, const QSize & maxViewportSize, Qt::Orientation orientation) inline static
Definition at line 245 of file qmdiarea.cpp.
Referenced by QMdiAreaPrivate::updateScrollBars().
 {
     if (orientation == Qt::Horizontal)
         return  childrenRect.width() > maxViewportSize.width()
                 || childrenRect.left() < 0
                 || childrenRect.right() >= maxViewportSize.width();
     else
         return childrenRect.height() > maxViewportSize.height()
                || childrenRect.top() < 0
                || childrenRect.bottom() >= maxViewportSize.height();
 }