Qt 4.8: /src/plugins/graphicssystems/meego/qmeegolivepixmapdata.cpp File Reference
qmeegolivepixmapdata.cpp File Reference
#include "qmeegolivepixmapdata.h"
#include "qmeegorasterpixmapdata.h"
#include <private/qimage_p.h>
#include <private/qwindowsurface_gl_p.h>
#include <private/qeglcontext_p.h>
#include <private/qapplication_p.h>
#include <private/qgraphicssystem_runtime_p.h>
#include <private/qpixmap_x11_p.h>
#include <stdio.h>
Functions
void qt_scrollRectInImage (QImage &img, const QRect &rect, const QPoint &offset)
Variables
static QMeeGoLivePixmapDataList all_live_pixmaps
static EGLint lock_attribs []
static EGLint preserved_attribs []
Function Documentation
qt_scrollRectInImage()
void qt_scrollRectInImage (QImage & img, const QRect & rect, const QPoint & offset)
Definition at line 66 of file qmeegolivepixmapdata.cpp.
Referenced by QWSMemorySurface::beginPaint(), QXlibWindowSurface::flush(), QRasterPixmapData::fromImageReader(), QXcbWindowSurface::resize(), QMeeGoLivePixmapData::scroll(), QXcbWindowSurface::scroll(), QXlibWindowSurface::scroll(), QRasterPixmapData::scroll(), QRasterWindowSurface::scroll(), QWSMemorySurface::scroll(), and QRasterWindowSurface::setGeometry().
 {
     // make sure we don't detach
     uchar *mem = const_cast<uchar*>(const_cast<const QImage &>(img).bits());
     int lineskip = img.bytesPerLine();
     int depth = img.depth() >> 3;
     const QRect imageRect(0, 0, img.width(), img.height());
     const QRect r = rect & imageRect & imageRect.translated(-offset);
     const QPoint p = rect.topLeft() + offset;
     if (r.isEmpty())
         return;
     const uchar *src;
     uchar *dest;
     if (r.top() < p.y()) {
         src = mem + r.bottom() * lineskip + r.left() * depth;
         dest = mem + (p.y() + r.height() - 1) * lineskip + p.x() * depth;
         lineskip = -lineskip;
     } else {
         src = mem + r.top() * lineskip + r.left() * depth;
         dest = mem + p.y() * lineskip + p.x() * depth;
     }
     const int w = r.width();
     int h = r.height();
     const int bytes = w * depth;
     // overlapping segments?
     if (offset.y() == 0 && qAbs(offset.x()) < w) {
         do {
             ::memmove(dest, src, bytes);
             dest += lineskip;
             src += lineskip;
         } while (--h);
     } else {
         do {
             ::memcpy(dest, src, bytes);
             dest += lineskip;
             src += lineskip;
         } while (--h);
     }
 }
Variable Documentation
all_live_pixmaps
QMeeGoLivePixmapDataList all_live_pixmaps static
Definition at line 52 of file qmeegolivepixmapdata.cpp.
lock_attribs
EGLint lock_attribs[] static
Initial value:
= {
    EGL_MAP_PRESERVE_PIXELS_KHR, EGL_TRUE,
    EGL_LOCK_USAGE_HINT_KHR, EGL_READ_SURFACE_BIT_KHR | EGL_WRITE_SURFACE_BIT_KHR,
    EGL_NONE
}
Definition at line 54 of file qmeegolivepixmapdata.cpp.
Referenced by QMeeGoLivePixmapData::lock().
preserved_attribs
EGLint preserved_attribs[] static
Initial value:
= {
    EGL_IMAGE_PRESERVED_KHR, EGL_TRUE,
    EGL_NONE
}
Definition at line 60 of file qmeegolivepixmapdata.cpp.
Referenced by QMeeGoLivePixmapData::initializeThroughEGLImage().