Qt 4.8: /src/gui/painting/qmemrotate_p.h File Reference
qmemrotate_p.h File Reference
#include "private/qdrawhelper_p.h"
Macros
#define Q_GUI_QWS_EXPORT Q_GUI_EXPORT
#define QT_DECL_MEMROTATE(srctype, desttype)
#define QT_ROTATION_ALGORITHM QT_ROTATION_TILED
#define QT_ROTATION_CACHEDREAD 1
#define QT_ROTATION_CACHEDWRITE 2
#define QT_ROTATION_PACKING 3
#define QT_ROTATION_TILED 4
Functions
QT_DECL_MEMROTATE (quint32, quint16)
QT_DECL_MEMROTATE (quint16, quint32)
QT_DECL_MEMROTATE (quint16, quint16)
QT_DECL_MEMROTATE (quint24, quint24)
QT_DECL_MEMROTATE (quint32, quint24)
QT_DECL_MEMROTATE (quint32, quint18)
QT_DECL_MEMROTATE (quint32, quint8)
QT_DECL_MEMROTATE (quint16, quint8)
QT_DECL_MEMROTATE (qrgb444, quint8)
QT_DECL_MEMROTATE (quint8, quint8)
void Q_GUI_QWS_EXPORT qt_memrotate180 (const quint32 *, int, int, int, quint32 *, int)
void Q_GUI_QWS_EXPORT qt_memrotate270 (const quint32 *, int, int, int, quint32 *, int)
void Q_GUI_EXPORT qt_memrotate90 (const quint32 *, int, int, int, quint32 *, int)
Macro Definition Documentation
Q_GUI_QWS_EXPORT
#define Q_GUI_QWS_EXPORT Q_GUI_EXPORT
Definition at line 74 of file qmemrotate_p.h.
QT_DECL_MEMROTATE
#define QT_DECL_MEMROTATE (srctype, desttype)
Value:
void Q_GUI_QWS_EXPORT qt_memrotate90(const srctype*, int, int, int, desttype*, int); \
    void Q_GUI_QWS_EXPORT qt_memrotate180(const srctype*, int, int, int, desttype*, int); \
    void Q_GUI_QWS_EXPORT qt_memrotate270(const srctype*, int, int, int, desttype*, int)
Definition at line 79 of file qmemrotate_p.h.
QT_ROTATION_ALGORITHM
#define QT_ROTATION_ALGORITHM QT_ROTATION_TILED
Definition at line 67 of file qmemrotate_p.h.
QT_ROTATION_CACHEDREAD
#define QT_ROTATION_CACHEDREAD 1
Definition at line 60 of file qmemrotate_p.h.
QT_ROTATION_CACHEDWRITE
#define QT_ROTATION_CACHEDWRITE 2
Definition at line 61 of file qmemrotate_p.h.
QT_ROTATION_PACKING
#define QT_ROTATION_PACKING 3
Definition at line 62 of file qmemrotate_p.h.
QT_ROTATION_TILED
#define QT_ROTATION_TILED 4
Definition at line 63 of file qmemrotate_p.h.
Function Documentation
QT_DECL_MEMROTATE() [1/10]
QT_DECL_MEMROTATE (quint32 , quint16)
QT_DECL_MEMROTATE() [2/10]
QT_DECL_MEMROTATE (quint16 , quint32)
QT_DECL_MEMROTATE() [3/10]
QT_DECL_MEMROTATE (quint16 , quint16)
QT_DECL_MEMROTATE() [4/10]
QT_DECL_MEMROTATE (quint24 , quint24)
QT_DECL_MEMROTATE() [5/10]
QT_DECL_MEMROTATE (quint32 , quint24)
QT_DECL_MEMROTATE() [6/10]
QT_DECL_MEMROTATE (quint32 , quint18)
QT_DECL_MEMROTATE() [7/10]
QT_DECL_MEMROTATE (quint32 , quint8)
QT_DECL_MEMROTATE() [8/10]
QT_DECL_MEMROTATE (quint16 , quint8)
QT_DECL_MEMROTATE() [9/10]
QT_DECL_MEMROTATE (qrgb444 , quint8)
QT_DECL_MEMROTATE() [10/10]
QT_DECL_MEMROTATE (quint8 , quint8)
qt_memrotate180()
void Q_GUI_QWS_EXPORT qt_memrotate180 (const quint32 * , int , int , int , quint32 * , int)
Referenced by blit180(), qt_memrotate180_16(), and qt_memrotate180_32().
qt_memrotate270()
void Q_GUI_QWS_EXPORT qt_memrotate270 (const quint32 * , int , int , int , quint32 * , int)
Referenced by blit270(), expblur(), qt_memrotate270_16(), qt_memrotate270_32(), and rotated90().
qt_memrotate90()
void Q_GUI_EXPORT qt_memrotate90 (const quint32 * , int , int , int , quint32 * , int)
Referenced by blit90(), expblur(), qt_memrotate90_16(), qt_memrotate90_32(), and rotated270().