Qt 4.8: /src/gui/widgets/qmenu_wince.cpp File Reference
qmenu_wince.cpp File Reference
#include "qmenu.h"
#include "qt_windows.h"
#include "qapplication.h"
#include "qmainwindow.h"
#include "qtoolbar.h"
#include "qevent.h"
#include "qstyle.h"
#include "qdebug.h"
#include "qwidgetaction.h"
#include <private/qapplication_p.h>
#include <private/qmenu_p.h>
#include <private/qmenubar_p.h>
#include "qmenu_wince_resource_p.h"
#include <QtCore/qlibrary.h>
#include <commctrl.h>
#include "qguifunctions_wince.h"
Classes
struct qt_SHMENUBARINFO
Macros
#define SHCMBF_EMPTYBAR 0x0001
#define SHCMBM_GETSUBMENU (WM_USER + 401)
Typedefs
typedef BOOL(WINAPI * AygCreateMenuBar) (qt_SHMENUBARINFO *)
typedef HRESULT(WINAPI * AygEnableSoftKey) (HWND, UINT, BOOL, BOOL)
Functions
static void qt_wce_change_command (HWND menuHandle, int item, int command)
static void qt_wce_clear_menu (HMENU hMenu)
static HWND qt_wce_create_menubar (HWND parentHandle, HINSTANCE resourceHandle, int toolbarID, int flags=0)
static void qt_wce_delete_action_list (QList< QWceMenuAction *> *list)
static void qt_wce_disable_soft_key (HWND handle, uint command)
static void qt_wce_enable_soft_key (HWND handle, uint command)
static HMODULE qt_wce_get_module_handle ()
static QAction * qt_wce_get_quit_action (QList< QAction *> actionItems)
static QAction * qt_wce_get_quit_action (QList< QWceMenuAction *> actionItems)
static void qt_wce_insert_action (HMENU menu, QWceMenuAction *action)
static void qt_wce_rename_menu_item (HWND menuHandle, int item, const QString &newText)
bool qt_wince_is_pocket_pc ()
bool qt_wince_is_smartphone ()
static void resolveAygLibs ()
Variables
static bool aygResolved = false
static QList< QMenuBar * > nativeMenuBars
static AygCreateMenuBar ptrCreateMenuBar = 0
static AygEnableSoftKey ptrEnableSoftKey = 0
static uint qt_wce_menu_static_cmd_id = 200
Macro Definition Documentation
SHCMBF_EMPTYBAR
#define SHCMBF_EMPTYBAR 0x0001
Definition at line 70 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::wceCreateMenuBar().
SHCMBM_GETSUBMENU
#define SHCMBM_GETSUBMENU (WM_USER + 401)
Definition at line 74 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::rebuild().
Typedef Documentation
AygCreateMenuBar
typedef BOOL(WINAPI * AygCreateMenuBar) (qt_SHMENUBARINFO *)
Definition at line 104 of file qmenu_wince.cpp.
AygEnableSoftKey
typedef HRESULT(WINAPI * AygEnableSoftKey) (HWND, UINT, BOOL, BOOL)
Definition at line 105 of file qmenu_wince.cpp.
Function Documentation
qt_wce_change_command()
static void qt_wce_change_command (HWND menuHandle, int item, int command) static
Definition at line 186 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::rebuild().
 {
 TBBUTTONINFOA tbbi;
     memset(&tbbi,0,sizeof(tbbi));
     tbbi.cbSize = sizeof(tbbi);
     tbbi.dwMask = TBIF_COMMAND;
     tbbi.idCommand = command;
     SendMessage(menuHandle, TB_SETBUTTONINFO, item, (LPARAM)&tbbi);
 }
qt_wce_clear_menu()
static void qt_wce_clear_menu (HMENU hMenu) static
Definition at line 263 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::rebuild(), and QMenuPrivate::QWceMenuPrivate::rebuild().
 {
     while (RemoveMenu(hMenu, 0, MF_BYPOSITION));
 }
qt_wce_create_menubar()
static HWND qt_wce_create_menubar (HWND parentHandle, HINSTANCE resourceHandle, int toolbarID, int flags = 0) static
Definition at line 208 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::rebuild(), and QMenuBarPrivate::wceCreateMenuBar().
 {
     resolveAygLibs();
     if (ptrCreateMenuBar) {
         qt_SHMENUBARINFO mbi;
         memset(&mbi, 0, sizeof(qt_SHMENUBARINFO));
         mbi.cbSize     = sizeof(qt_SHMENUBARINFO);
         mbi.hwndParent = parentHandle;
         mbi.hInstRes   = resourceHandle;
         mbi.dwFlags = flags;
         mbi.nToolBarId = toolbarID;
         if (ptrCreateMenuBar(&mbi)) {
 #ifdef Q_OS_WINCE_WM
             // Tell the menu bar that we want to override hot key behaviour.
             LPARAM lparam = MAKELPARAM(SHMBOF_NODEFAULT | SHMBOF_NOTIFY,
                                        SHMBOF_NODEFAULT | SHMBOF_NOTIFY);
             SendMessage(mbi.hwndMB, SHCMBM_OVERRIDEKEY, VK_TBACK, lparam);
 #endif
             return mbi.hwndMB;
         }
     }
     return 0;
 }
qt_wce_delete_action_list()
static void qt_wce_delete_action_list (QList< QWceMenuAction *> * list) static
Definition at line 135 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::rebuild(), QMenuBarPrivate::QWceMenuBarPrivate::~QWceMenuBarPrivate(), and QMenuPrivate::QWceMenuPrivate::~QWceMenuPrivate().
 {
     for(QList<QWceMenuAction*>::Iterator it = list->begin(); it != list->end(); ++it) {
         QWceMenuAction *action = (*it);
         delete action;
         action = 0;
     }
     list->clear();
 }
qt_wce_disable_soft_key()
static void qt_wce_disable_soft_key (HWND handle, uint command) static
Definition at line 128 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::rebuild().
 {
     resolveAygLibs();
     if (ptrEnableSoftKey)
         ptrEnableSoftKey(handle, command, false, false);
 }
qt_wce_enable_soft_key()
static void qt_wce_enable_soft_key (HWND handle, uint command) static
Definition at line 121 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::rebuild().
 {
     resolveAygLibs();
     if (ptrEnableSoftKey)
         ptrEnableSoftKey(handle, command, false, true);
 }
qt_wce_get_module_handle()
static HMODULE qt_wce_get_module_handle () static
Definition at line 176 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::rebuild().
 {
     HMODULE module =  0; //handle to resources
     if (!(module = GetModuleHandle(L"QtGui4"))) //release dynamic
         if (!(module = GetModuleHandle(L"QtGuid4"))) //debug dynamic
             module = (HINSTANCE)qWinAppInst(); //static
     Q_ASSERT_X(module, "qt_wce_get_module_handle()", "cannot get handle to module?");
     return module;
 }
qt_wce_get_quit_action() [1/2]
static QAction* qt_wce_get_quit_action (QList< QAction *> actionItems) static
Definition at line 146 of file qmenu_wince.cpp.
Referenced by qt_wce_get_quit_action(), and QMenuBarPrivate::QWceMenuBarPrivate::rebuild().
 {
     QAction *returnAction = 0;
     for (int i = 0; i < actionItems.size(); ++i) {
         QAction *action = actionItems.at(i);
         if (action->menuRole() == QAction::QuitRole)
             returnAction = action;
         else
             if (action->menu())
                 returnAction = qt_wce_get_quit_action(action->menu()->actions());
         if (returnAction)
             return returnAction; //return first action found
     }
     return 0; //nothing found;
 }
qt_wce_get_quit_action() [2/2]
static QAction* qt_wce_get_quit_action (QList< QWceMenuAction *> actionItems) static
Definition at line 162 of file qmenu_wince.cpp.
 {
     for (int i = 0; i < actionItems.size(); ++i) {
         if (actionItems.at(i)->action->menuRole() == QAction::QuitRole)
             return actionItems.at(i)->action;
         else if (actionItems.at(i)->action->menu()) {
             QAction *returnAction = qt_wce_get_quit_action(actionItems.at(i)->action->menu()->actions());
             if (returnAction)
                 return returnAction;
         }
     }
     return 0;
 }
qt_wce_insert_action()
static void qt_wce_insert_action (HMENU menu, QWceMenuAction * action) static
Definition at line 234 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::rebuild(), and QMenuPrivate::QWceMenuPrivate::rebuild().
 {
     Q_ASSERT_X(menu, "AppendMenu", "menu is 0");
     if (action->action->isVisible()) {
         int flags;
         action->action->isEnabled() ? flags = MF_ENABLED : flags = MF_GRAYED;
         QString text = action->action->iconText();
         text.remove(QChar::fromLatin1('&'));
         if (action->action->isSeparator()) {
             AppendMenu (menu, MF_SEPARATOR , 0, 0);
         }
         else if (action->action->menu()) {
             text.remove(QChar::fromLatin1('&'));
             AppendMenu (menu, MF_STRING | flags | MF_POPUP,
             (UINT) action->action->menu()->wceMenu(), reinterpret_cast<const wchar_t *> (text.utf16()));
         }
         else {
             AppendMenu (menu, MF_STRING | flags, action->command, reinterpret_cast<const wchar_t *> (text.utf16()));
         }
         if (action->action->isCheckable())
             if (action->action->isChecked())
                 CheckMenuItem(menu, action->command, MF_BYCOMMAND | MF_CHECKED);
             else
                 CheckMenuItem(menu, action->command, MF_BYCOMMAND | MF_UNCHECKED);
     }
 }
qt_wce_rename_menu_item()
static void qt_wce_rename_menu_item (HWND menuHandle, int item, const QString & newText) static
Definition at line 196 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::rebuild().
 {
     TBBUTTONINFOA tbbi;
     memset(&tbbi,0,sizeof(tbbi));
     tbbi.cbSize = sizeof(tbbi);
     tbbi.dwMask = TBIF_TEXT;
     QString text = newText;
     text.remove(QChar::fromLatin1('&'));
     tbbi.pszText = (LPSTR) text.utf16();
     SendMessage(menuHandle, TB_SETBUTTONINFO, item, (LPARAM)&tbbi);
 }
qt_wince_is_pocket_pc()
bool qt_wince_is_pocket_pc ()
Definition at line 289 of file qguifunctions_wince.cpp.
Referenced by qt_wince_is_high_dpi(), qt_wince_is_mobile(), and QMenuBarPrivate::wceCreateMenuBar().
{
     return qt_wince_is_platform(QString::fromLatin1("PocketPC"));
 }
qt_wince_is_smartphone()
bool qt_wince_is_smartphone ()
Definition at line 293 of file qguifunctions_wince.cpp.
Referenced by qt_wince_is_mobile(), and QMenuBarPrivate::wceCreateMenuBar().
{
        return qt_wince_is_platform(QString::fromLatin1("Smartphone"));
 }
resolveAygLibs()
static void resolveAygLibs () static
Definition at line 111 of file qmenu_wince.cpp.
Referenced by qt_wce_create_menubar(), qt_wce_disable_soft_key(), and qt_wce_enable_soft_key().
 {
     if (!aygResolved) {
         QLibrary aygLib(QLatin1String("aygshell"));
         ptrCreateMenuBar = (AygCreateMenuBar) aygLib.resolve("SHCreateMenuBar");
         ptrEnableSoftKey = (AygEnableSoftKey) aygLib.resolve("SHEnableSoftkey");
         aygResolved = true;
     }
 }
Variable Documentation
aygResolved
bool aygResolved = false static
Definition at line 107 of file qmenu_wince.cpp.
Referenced by resolveAygLibs().
nativeMenuBars
QList<QMenuBar*> nativeMenuBars static
Definition at line 89 of file qmenu_wince.cpp.
ptrCreateMenuBar
AygCreateMenuBar ptrCreateMenuBar = 0 static
Definition at line 108 of file qmenu_wince.cpp.
Referenced by qt_wce_create_menubar(), and resolveAygLibs().
ptrEnableSoftKey
AygEnableSoftKey ptrEnableSoftKey = 0 static
Definition at line 109 of file qmenu_wince.cpp.
Referenced by qt_wce_disable_soft_key(), qt_wce_enable_soft_key(), and resolveAygLibs().
qt_wce_menu_static_cmd_id
uint qt_wce_menu_static_cmd_id = 200 static
Definition at line 88 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::addAction(), QMenuPrivate::QWceMenuPrivate::addAction(), and QMenuBarPrivate::QWceMenuBarPrivate::rebuild().