Qt 4.8: /src/gui/widgets/qmenubar.cpp File Reference
qmenubar.cpp File Reference
#include <qmenubar.h>
#include <qstyle.h>
#include <qlayout.h>
#include <qapplication.h>
#include <qdesktopwidget.h>
#include <qaccessible.h>
#include <qpainter.h>
#include <qstylepainter.h>
#include <qevent.h>
#include <qmainwindow.h>
#include <qtoolbar.h>
#include <qtoolbutton.h>
#include <qwhatsthis.h>
#include <qpluginloader.h>
#include "qmenu_p.h"
#include "qmenubar_p.h"
#include "qdebug.h"
#include "qmenubar_x11_p.h"
#include <moc_qmenubar.cpp>
Classes
class QMenuBarExtension
Functions
bool qt_wince_is_mobile ()
Function Documentation
qt_wince_is_mobile()
bool qt_wince_is_mobile ()
Definition at line 296 of file qguifunctions_wince.cpp.
Referenced by QMenuBarPrivate::handleReparent(), QMenuBarPrivate::init(), qt_wince_full_screen(), qt_wince_maximize(), qt_wince_unmaximize(), QMenuBar::setDefaultAction(), and QMenuBar::~QMenuBar().
{
      return (qt_wince_is_smartphone() || qt_wince_is_pocket_pc());
 }