Qt 4.8: /src/gui/dialogs/qmessagebox.cpp File Reference
qmessagebox.cpp File Reference
#include <QtGui/qmessagebox.h>
#include <QtGui/qdialogbuttonbox.h>
#include "private/qlabel_p.h"
#include "private/qapplication_p.h"
#include <QtCore/qlist.h>
#include <QtCore/qdebug.h>
#include <QtGui/qstyle.h>
#include <QtGui/qstyleoption.h>
#include <QtGui/qgridlayout.h>
#include <QtGui/qdesktopwidget.h>
#include <QtGui/qpushbutton.h>
#include <QtGui/qaccessible.h>
#include <QtGui/qicon.h>
#include <QtGui/qtextdocument.h>
#include <QtGui/qapplication.h>
#include <QtGui/qtextedit.h>
#include <QtGui/qtextbrowser.h>
#include <QtGui/qmenu.h>
#include "qdialog_p.h"
#include <QtGui/qfont.h>
#include <QtGui/qfontmetrics.h>
#include <QtGui/qclipboard.h>
#include <qs60style.h>
#include "qguifunctions_wince.h"
#include "moc_qmessagebox.cpp"
Classes
class DetailButton
class QMessageBoxDetailsText
class QMessageBoxDetailsText::TextEdit
class QMessageBoxPrivate
Enumerations
enum Button {
Old_Ok = 1, Old_Cancel = 2, Old_Yes = 3, Old_No = 4,
Old_Abort = 5, Old_Retry = 6, Old_Ignore = 7, Old_YesAll = 8,
Old_NoAll = 9, Old_ButtonMask = 0xFF, NewButtonMask = 0xFFFFFC00, None = 0x000,
Keyboard = 0x001, Mouse = 0x002, Wheel = 0x004, ButtonMask = 0x008,
Up = 0x010, Down = 0x020, DirectionMask = 0x040
}
enum DetailButtonLabel { ShowLabel = 0, HideLabel = 1 }
Functions
static bool detectedCompat (int button0, int button1, int button2)
static QMessageBox::StandardButton newButton (int button)
static int oldButton (int button)
bool qt_wince_is_mobile ()
bool qt_wince_is_pocket_pc ()
bool qt_wince_is_smartphone ()
static QMessageBox::StandardButton showNewMessageBox (QWidget *parent, QMessageBox::Icon icon, const QString &title, const QString &text, QMessageBox::StandardButtons buttons, QMessageBox::StandardButton defaultButton)
Enumeration Type Documentation
Button
enum Button
Enumerator
Old_Ok
Old_Cancel
Old_Yes
Old_No
Old_Abort
Old_Retry
Old_Ignore
Old_YesAll
Old_NoAll
Old_ButtonMask
NewButtonMask
None
Keyboard
Mouse
Wheel
ButtonMask
Up
Down
DirectionMask
Definition at line 82 of file qmessagebox.cpp.
             { Old_Ok = 1, Old_Cancel = 2, Old_Yes = 3, Old_No = 4, Old_Abort = 5, Old_Retry = 6,
               Old_Ignore = 7, Old_YesAll = 8, Old_NoAll = 9, Old_ButtonMask = 0xFF,
               NewButtonMask = 0xFFFFFC00 };
DetailButtonLabel
enum DetailButtonLabel
Enumerator
ShowLabel
HideLabel
Definition at line 86 of file qmessagebox.cpp.
 { ShowLabel = 0, HideLabel = 1 };
Function Documentation
detectedCompat()
static bool detectedCompat (int button0, int button1, int button2) static
Definition at line 1947 of file qmessagebox.cpp.
Referenced by QMessageBoxPrivate::addOldButtons().
 {
     if (button0 != 0 && !(button0 & NewButtonMask))
         return true;
     if (button1 != 0 && !(button1 & NewButtonMask))
         return true;
     if (button2 != 0 && !(button2 & NewButtonMask))
         return true;
     return false;
 }
newButton()
static QMessageBox::StandardButton newButton (int button) static
Definition at line 1914 of file qmessagebox.cpp.
Referenced by QMessageBoxPrivate::abstractButtonForId(), QMessageBoxPrivate::addOldButtons(), QWindowsMobileStyle::drawControl(), and QMessageBoxPrivate::findButton().
 {
     // this is needed for source compatibility with Qt 4.0 and 4.1
     if (button == QMessageBox::NoButton || (button & NewButtonMask))
         return QMessageBox::StandardButton(button & QMessageBox::ButtonMask);
 #if QT_VERSION < 0x050000
     // this is needed for binary compatibility with Qt 4.0 and 4.1
     switch (button & Old_ButtonMask) {
     case Old_Ok:
         return QMessageBox::Ok;
     case Old_Cancel:
         return QMessageBox::Cancel;
     case Old_Yes:
         return QMessageBox::Yes;
     case Old_No:
         return QMessageBox::No;
     case Old_Abort:
         return QMessageBox::Abort;
     case Old_Retry:
         return QMessageBox::Retry;
     case Old_Ignore:
         return QMessageBox::Ignore;
     case Old_YesAll:
         return QMessageBox::YesToAll;
     case Old_NoAll:
         return QMessageBox::NoToAll;
     default:
         return QMessageBox::NoButton;
     }
 #endif
 }
oldButton()
static int oldButton (int button) static
Definition at line 436 of file qmessagebox.cpp.
Referenced by QMessageBoxPrivate::execReturnCode(), and QWizard::setButton().
 {
     switch (button & QMessageBox::ButtonMask) {
     case QMessageBox::Ok:
         return Old_Ok;
     case QMessageBox::Cancel:
         return Old_Cancel;
     case QMessageBox::Yes:
         return Old_Yes;
     case QMessageBox::No:
         return Old_No;
     case QMessageBox::Abort:
         return Old_Abort;
     case QMessageBox::Retry:
         return Old_Retry;
     case QMessageBox::Ignore:
         return Old_Ignore;
     case QMessageBox::YesToAll:
         return Old_YesAll;
     case QMessageBox::NoToAll:
         return Old_NoAll;
     default:
         return 0;
     }
 }
qt_wince_is_mobile()
bool qt_wince_is_mobile ()
Definition at line 296 of file qguifunctions_wince.cpp.
{
      return (qt_wince_is_smartphone() || qt_wince_is_pocket_pc());
 }
qt_wince_is_pocket_pc()
bool qt_wince_is_pocket_pc ()
Definition at line 289 of file qguifunctions_wince.cpp.
{
     return qt_wince_is_platform(QString::fromLatin1("PocketPC"));
 }
qt_wince_is_smartphone()
bool qt_wince_is_smartphone ()
Definition at line 293 of file qguifunctions_wince.cpp.
{
        return qt_wince_is_platform(QString::fromLatin1("Smartphone"));
 }
showNewMessageBox()
static QMessageBox::StandardButton showNewMessageBox (QWidget * parent, QMessageBox::Icon icon, const QString & title, const QString & text, QMessageBox::StandardButtons buttons, QMessageBox::StandardButton defaultButton) static
Definition at line 1573 of file qmessagebox.cpp.
Referenced by QMessageBox::critical(), QMessageBox::information(), QMessageBoxPrivate::QMessageBoxPrivate(), QMessageBox::question(), and QMessageBox::warning().
 {
     // necessary for source compatibility with Qt 4.0 and 4.1
     // handles (Yes, No) and (Yes|Default, No)
     if (defaultButton && !(buttons & defaultButton))
         return (QMessageBox::StandardButton)
                     QMessageBoxPrivate::showOldMessageBox(parent, icon, title,
                                                             text, int(buttons),
                                                             int(defaultButton), 0);
     QMessageBox msgBox(icon, title, text, QMessageBox::NoButton, parent);
     QDialogButtonBox *buttonBox = msgBox.findChild<QDialogButtonBox*>();
     Q_ASSERT(buttonBox != 0);
     uint mask = QMessageBox::FirstButton;
     while (mask <= QMessageBox::LastButton) {
         uint sb = buttons & mask;
         mask <<= 1;
         if (!sb)
             continue;
         QPushButton *button = msgBox.addButton((QMessageBox::StandardButton)sb);
         // Choose the first accept role as the default
         if (msgBox.defaultButton())
             continue;
         if ((defaultButton == QMessageBox::NoButton && buttonBox->buttonRole(button) == QDialogButtonBox::AcceptRole)
             || (defaultButton != QMessageBox::NoButton && sb == uint(defaultButton)))
             msgBox.setDefaultButton(button);
     }
     if (msgBox.exec() == -1)
         return QMessageBox::Cancel;
     return msgBox.standardButton(msgBox.clickedButton());
 }