Qt 4.8: /src/corelib/kernel/qmetatype.h File Reference
qmetatype.h File Reference
#include <QtCore/qglobal.h>
#include <QtCore/qatomic.h>
#include <QtCore/qdatastream.h>
Classes
class QMetaType
The QMetaType class manages named types in the meta-object system.
struct QMetaTypeId< T >
struct QMetaTypeId2< T >
struct QtPrivate::QMetaTypeIdHelper< T, Defined >
struct QtPrivate::QMetaTypeIdHelper< T, false >
Namespaces
QtPrivate
Macros
#define Q_DECLARE_BUILTIN_METATYPE(TYPE, NAME)
#define Q_DECLARE_METATYPE(TYPE)
This macro makes the type Type known to QMetaType as long as it provides a public default constructor, a public copy constructor and a public destructor.
Functions
template<typename T >
void * qMetaTypeConstructHelper (const T *t)
template<typename T >
void qMetaTypeDeleteHelper (T *t)
template<typename T >
int qMetaTypeId ()
template<typename T >
void qMetaTypeLoadHelper (QDataStream &stream, T *t)
template<typename T >
void qMetaTypeSaveHelper (QDataStream &stream, const T *t)
template<typename T >
int qRegisterMetaType (const char *typeName)
template<typename T >
int qRegisterMetaType ()
template<typename T >
void qRegisterMetaTypeStreamOperators (const char *typeName)
template<typename T >
int qRegisterMetaTypeStreamOperators ()
Macro Definition Documentation
Q_DECLARE_BUILTIN_METATYPE
#define Q_DECLARE_BUILTIN_METATYPE (TYPE, NAME)
Value:
QT_BEGIN_NAMESPACE \
    template<> struct QMetaTypeId2<TYPE> \
    { \
        enum { Defined = 1, MetaType = QMetaType::NAME }; \
        static inline int qt_metatype_id() { return QMetaType::NAME; } \
    }; \
    QT_END_NAMESPACE
Definition at line 282 of file qmetatype.h.
Referenced by qVariantCanConvert().
Q_DECLARE_METATYPE
#define Q_DECLARE_METATYPE (TYPE)
Value:
QT_BEGIN_NAMESPACE                                                  \
    template <>                                                         \
    struct QMetaTypeId< TYPE >                                          \
    {                                                                   \
        enum { Defined = 1 };                                           \
        static int qt_metatype_id()                                     \
            {                                                           \
                static QBasicAtomicInt metatype_id = Q_BASIC_ATOMIC_INITIALIZER(0); \
                if (!metatype_id)                                       \
                    metatype_id = qRegisterMetaType< TYPE >(#TYPE,      \
                               reinterpret_cast< TYPE *>(quintptr(-1))); \
                return metatype_id;                                     \
            }                                                           \
    };                                                                  \
    QT_END_NAMESPACE
This macro makes the type Type known to QMetaType as long as it provides a public default constructor, a public copy constructor and a public destructor.
It is needed to use the type Type as a custom type in QVariant.
Ideally, this macro should be placed below the declaration of the class or struct. If that is not possible, it can be put in a private header file which has to be included every time that type is used in a QVariant.
Adding a Q_DECLARE_METATYPE() makes the type known to all template based functions, including QVariant. Note that if you intend to use the type in queued signal and slot connections or in QObject's property system, you also have to call qRegisterMetaType() since the names are resolved at runtime.
This example shows a typical use case of Q_DECLARE_METATYPE():
struct MyStruct
{
    int i;
    ...
};
Q_DECLARE_METATYPE(MyStruct)
If MyStruct is in a namespace, the Q_DECLARE_METATYPE() macro has to be outside the namespace:
namespace MyNamespace
{
    ...
}
Q_DECLARE_METATYPE(MyNamespace::MyStruct)
Since MyStruct is now known to QMetaType, it can be used in QVariant:
MyStruct s;
QVariant var;
var.setValue(s); // copy s into the variant
...
// retrieve the value
MyStruct s2 = var.value<MyStruct>();
See also
qRegisterMetaType()
Definition at line 265 of file qmetatype.h.
Referenced by QLocalePrivate::digitToCLocale(), operator<<(), operator==(), operator>>(), PQfreemem(), qgraphicsitem_cast(), qIsForwardIteratorEnd(), qmlAttachedPropertiesObject(), qobject_cast< QAxObject * >(), scriptValueToQDBusError(), QDeclarativeGuard< QDeclarativeTransition >::setObject(), QTextOption::setTabStop(), QTestEventList::simulate(), QLocale::toCurrencyString(), and QDeclarativeBinding::update().
Function Documentation
qMetaTypeConstructHelper()
template<typename T > void* qMetaTypeConstructHelper (const T * t)
Definition at line 138 of file qmetatype.h.
 {
     if (!t)
         return new T();
     return new T(*static_cast<const T*>(t));
 }
qMetaTypeDeleteHelper()
template<typename T > void qMetaTypeDeleteHelper (T * t)
Definition at line 132 of file qmetatype.h.
 {
     delete t;
 }
qMetaTypeId()
template<typename T > int qMetaTypeId () related
Definition at line 224 of file qmetatype.h.
Referenced by QScriptEnginePrivate::convertValue(), QScriptEnginePrivate::create(), QDeclarativeVMEMetaObject::metaCall(), QDBusReply< QStringList >::operator=(), QDeclarativeObjectMethodScriptClass::property(), qRegisterMetaType(), QDeclarativeEnginePrivate::scriptValueToVariant(), QDeclarativeObjectScriptClass::setProperty(), QDeclarativeBinding::update(), and QDeclarativeExpressionPrivate::value().
 {
     return QMetaTypeId2<T>::qt_metatype_id();
 }
qMetaTypeLoadHelper()
template<typename T > void qMetaTypeLoadHelper (QDataStream & stream, T * t)
Definition at line 153 of file qmetatype.h.
 {
     stream >> *t;
 }
qMetaTypeSaveHelper()
template<typename T > void qMetaTypeSaveHelper (QDataStream & stream, const T * t)
Definition at line 147 of file qmetatype.h.
 {
     stream << *t;
 }
qRegisterMetaType() [1/2]
template<typename T > int qRegisterMetaType (const char * typeName) related
Definition at line 185 of file qmetatype.h.
Referenced by QDeclarativePrivate::qmlRegisterUncreatableType().
 {
     const int typedefOf = dummy ? -1 : QtPrivate::QMetaTypeIdHelper<T>::qt_metatype_id();
     if (typedefOf != -1)
         return QMetaType::registerTypedef(typeName, typedefOf);
     typedef void*(*ConstructPtr)(const T*);
     ConstructPtr cptr = qMetaTypeConstructHelper<T>;
     typedef void(*DeletePtr)(T*);
     DeletePtr dptr = qMetaTypeDeleteHelper<T>;
     return QMetaType::registerType(typeName, reinterpret_cast<QMetaType::Destructor>(dptr),
                                    reinterpret_cast<QMetaType::Constructor>(cptr));
 }
qRegisterMetaType() [2/2]
template<typename T > int qRegisterMetaType () related
Definition at line 234 of file qmetatype.h.
 {
 #ifdef Q_CC_SUN
     return qMetaTypeId(static_cast<T *>(0));
 #else
     return qMetaTypeId(dummy);
 #endif
 }
qRegisterMetaTypeStreamOperators() [1/2]
template<typename T > void qRegisterMetaTypeStreamOperators (const char * typeName) related
Definition at line 206 of file qmetatype.h.
 {
     typedef void(*SavePtr)(QDataStream &, const T *);
     typedef void(*LoadPtr)(QDataStream &, T *);
     SavePtr sptr = qMetaTypeSaveHelper<T>;
     LoadPtr lptr = qMetaTypeLoadHelper<T>;
     qRegisterMetaType<T>(typeName);
     QMetaType::registerStreamOperators(typeName, reinterpret_cast<QMetaType::SaveOperator>(sptr),
                                        reinterpret_cast<QMetaType::LoadOperator>(lptr));
 }
qRegisterMetaTypeStreamOperators() [2/2]
template<typename T > int qRegisterMetaTypeStreamOperators () inline
Definition at line 249 of file qmetatype.h.
 {
     typedef void(*SavePtr)(QDataStream &, const T *);
     typedef void(*LoadPtr)(QDataStream &, T *);
     SavePtr sptr = qMetaTypeSaveHelper<T>;
     LoadPtr lptr = qMetaTypeLoadHelper<T>;
     register int id = qMetaTypeId<T>();
     QMetaType::registerStreamOperators(id,
                                        reinterpret_cast<QMetaType::SaveOperator>(sptr),
                                        reinterpret_cast<QMetaType::LoadOperator>(lptr));
     return id;
 }