Qt 4.8: /src/gui/kernel/qmime_mac.cpp File Reference
qmime_mac.cpp File Reference
#include "qmime.h"
#include "qfile.h"
#include "qfileinfo.h"
#include "qtextstream.h"
#include "qdir.h"
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/fcntl.h>
#include "qdebug.h"
#include "qpixmap.h"
#include "qimagewriter.h"
#include "qimagereader.h"
#include "qdatastream.h"
#include "qbuffer.h"
#include "qdatetime.h"
#include "qapplication_p.h"
#include "qtextcodec.h"
#include "qregexp.h"
#include "qurl.h"
#include "qmap.h"
#include <private/qt_mac_p.h>
Classes
class QMacPasteboardMimeAny
class QMacPasteboardMimeFileUri
class QMacPasteboardMimeHTMLText
class QMacPasteboardMimePlainText
class QMacPasteboardMimeTiff
class QMacPasteboardMimeTypeName
class QMacPasteboardMimeUnicodeText
class QMacPasteboardMimeUrl
class QMacPasteboardMimeVCard
Typedefs
typedef QList< QMacPasteboardMime * > MimeList
Functions
static void cleanup_mimes ()
const QStringList & qEnabledDraggedTypes ()
Q_GUI_EXPORT void qRegisterDraggedTypes (const QStringList &types)
CGImageRef qt_mac_createCGImageFromQImage (const QImage &img, const QImage **imagePtr=0)
Variables
ScrapFlavorType qt_mac_mime_type = 'CUTE'
CFStringRef qt_mac_mime_typeUTI = CFSTR("com.pasteboard.trolltech.marker")
Typedef Documentation
MimeList
typedef QList<QMacPasteboardMime*> MimeList
Definition at line 81 of file qmime_mac.cpp.
Function Documentation
cleanup_mimes()
static void cleanup_mimes () static
Definition at line 84 of file qmime_mac.cpp.
Referenced by QMacPasteboardMime::initialize().
 {
     MimeList *mimes = globalMimeList();
     while (!mimes->isEmpty())
         delete mimes->takeFirst();
 }
qEnabledDraggedTypes()
const QStringList& qEnabledDraggedTypes ()
Definition at line 114 of file qmime_mac.cpp.
 {
     return (*globalDraggedTypesList());
 }
qRegisterDraggedTypes()
Q_GUI_EXPORT void qRegisterDraggedTypes (const QStringList & types) related
Definition at line 109 of file qmime_mac.cpp.
 {
     (*globalDraggedTypesList()) += types;
 }
qt_mac_createCGImageFromQImage()
CGImageRef qt_mac_createCGImageFromQImage (const QImage & img, const QImage ** imagePtr = 0)
Definition at line 1006 of file qpaintengine_mac.cpp.
Referenced by QMacPasteboardMimeHTMLText::convertFromMime(), QMacPasteboardMimeTiff::convertFromMime(), and QCoreGraphicsPaintEngine::drawImage().
 {
     QImage *image;
     if (img.depth() != 32)
         image = new QImage(img.convertToFormat(QImage::Format_ARGB32_Premultiplied));
     else
         image = new QImage(img);
     uint cgflags = kCGImageAlphaNone;
     switch (image->format()) {
     case QImage::Format_ARGB32_Premultiplied:
         cgflags = kCGImageAlphaPremultipliedFirst;
         break;
     case QImage::Format_ARGB32:
         cgflags = kCGImageAlphaFirst;
         break;
     case QImage::Format_RGB32:
         cgflags = kCGImageAlphaNoneSkipFirst;
     default:
         break;
     }
 #if defined(kCGBitmapByteOrder32Host) //only needed because CGImage.h added symbols in the minor version
     cgflags |= kCGBitmapByteOrder32Host;
 #endif
     QCFType<CGDataProviderRef> dataProvider = CGDataProviderCreateWithData(image,
                                                           static_cast<const QImage *>(image)->bits(),
                                                           image->byteCount(),
                                                           drawImageReleaseData);
     if (imagePtr)
         *imagePtr = image;
     return CGImageCreate(image->width(), image->height(), 8, 32,
                                         image->bytesPerLine(),
                                         QCoreGraphicsPaintEngine::macGenericColorSpace(),
                                         cgflags, dataProvider, 0, false, kCGRenderingIntentDefault);
 }
Variable Documentation
qt_mac_mime_type
ScrapFlavorType qt_mac_mime_type = 'CUTE'
Definition at line 125 of file qmime_mac.cpp.
qt_mac_mime_typeUTI
CFStringRef qt_mac_mime_typeUTI = CFSTR("com.pasteboard.trolltech.marker")
Definition at line 126 of file qmime_mac.cpp.