Qt 4.8: /src/gui/kernel/qmime_win.cpp File Reference
qmime_win.cpp File Reference
#include "qmime.h"
#include "qimagereader.h"
#include "qimagewriter.h"
#include "qdatastream.h"
#include "qbuffer.h"
#include "qt_windows.h"
#include "qapplication_p.h"
#include "qtextcodec.h"
#include "qregexp.h"
#include "qalgorithms.h"
#include "qmap.h"
#include "qdnd_p.h"
#include <shlobj.h>
#include "qurl.h"
#include "qvariant.h"
#include "qtextdocument.h"
#include "qdir.h"
#include "qguifunctions_wince.h"
Classes
struct _CIEXYZ
struct _CIEXYZTRIPLE
struct BMP_BITMAPV5HEADER
class QBuiltInMimes
class QLastResortMimes
class QWindowsMimeHtml
class QWindowsMimeImage
class QWindowsMimeList
class QWindowsMimeText
class QWindowsMimeURI
Macros
#define BMP_LCS_GM_IMAGES 0x00000004L
#define BMP_LCS_sRGB 0x73524742
#define CF_DIBV5 17
Functions
static int calc_shift (int mask)
static bool canGetData (int cf, IDataObject *pDataObj)
static QString customMimeType (const QString &mimeType)
static int getCf (const FORMATETC &formatetc)
static QByteArray getData (int cf, IDataObject *pDataObj)
static bool isCustomMimeType (const QString &mimeType)
Q_GLOBAL_STATIC (QWindowsMimeList, theMimeList)
bool qt_read_dib (QDataStream &, QImage &)
static bool qt_read_dibv5 (QDataStream &s, QImage &image)
bool qt_write_dib (QDataStream &, QImage)
static bool qt_write_dibv5 (QDataStream &s, QImage image)
static FORMATETC setCf (int cf)
static bool setData (const QByteArray &data, STGMEDIUM *pmedium)
Variables
static const int BMP_BITFIELDS = 3
static const char x_qt_windows_mime [] = "application/x-qt-windows-mime;value=\""
Macro Definition Documentation
BMP_LCS_GM_IMAGES
#define BMP_LCS_GM_IMAGES 0x00000004L
Definition at line 76 of file qmime_win.cpp.
Referenced by qt_write_dibv5().
BMP_LCS_sRGB
#define BMP_LCS_sRGB 0x73524742
Definition at line 75 of file qmime_win.cpp.
Referenced by qt_write_dibv5().
CF_DIBV5
#define CF_DIBV5 17
Definition at line 69 of file qmime_win.cpp.
Referenced by QWindowsMimeImage::canConvertFromMime(), QWindowsMimeImage::convertFromMime(), QWindowsMimeImage::convertToMime(), QWindowsMimeImage::formatsForMime(), QWindowsMimeImage::hasOriginalDIBV5(), and QWindowsMimeImage::mimeForFormat().
Function Documentation
calc_shift()
static int calc_shift (int mask) static
Definition at line 1460 of file qmime_win.cpp.
Referenced by qt_read_dibv5().
 {
     int result = 0;
     while (!(mask & 1)) {
         result++;
         mask >>= 1;
     }
     return result;
 }
canGetData()
static bool canGetData (int cf, IDataObject * pDataObj) static
Definition at line 191 of file qmime_win.cpp.
Referenced by QWindowsMimeText::canConvertToMime(), QWindowsMimeURI::canConvertToMime(), QWindowsMimeHtml::canConvertToMime(), QWindowsMimeImage::canConvertToMime(), QBuiltInMimes::canConvertToMime(), QLastResortMimes::canConvertToMime(), QWindowsMimeURI::convertToMime(), and QWindowsMimeImage::convertToMime().
 {
     FORMATETC formatetc = setCf(cf);
      if (pDataObj->QueryGetData(&formatetc) != S_OK){
         formatetc.tymed = TYMED_ISTREAM;
         return pDataObj->QueryGetData(&formatetc) == S_OK;
     }
     return true;
 }
customMimeType()
static QString customMimeType (const QString & mimeType) static
Definition at line 1256 of file qmime_win.cpp.
Referenced by QLastResortMimes::canConvertToMime(), and QLastResortMimes::convertToMime().
 {
     int len = sizeof(x_qt_windows_mime) - 1;
     int n = mimeType.lastIndexOf(QLatin1Char('\"'))-len;
     return mimeType.mid(len, n);
 }
getCf()
static int getCf (const FORMATETC & formatetc) static
Definition at line 125 of file qmime_win.cpp.
Referenced by QWindowsMimeText::canConvertFromMime(), QWindowsMimeURI::canConvertFromMime(), QWindowsMimeHtml::canConvertFromMime(), QWindowsMimeImage::canConvertFromMime(), QWindowsMimeText::convertFromMime(), QWindowsMimeURI::convertFromMime(), QWindowsMimeImage::convertFromMime(), QBuiltInMimes::convertFromMime(), QLastResortMimes::convertFromMime(), QWindowsMimeText::mimeForFormat(), QWindowsMimeURI::mimeForFormat(), QWindowsMimeHtml::mimeForFormat(), QWindowsMimeImage::mimeForFormat(), QBuiltInMimes::mimeForFormat(), and QLastResortMimes::mimeForFormat().
 {
     return formatetc.cfFormat;
 }
getData()
static QByteArray getData (int cf, IDataObject * pDataObj) static
Definition at line 156 of file qmime_win.cpp.
Referenced by QWindowsMimeText::convertToMime(), QWindowsMimeURI::convertToMime(), QWindowsMimeHtml::convertToMime(), QWindowsMimeImage::convertToMime(), QBuiltInMimes::convertToMime(), and QLastResortMimes::convertToMime().
 {
     QByteArray data;
     FORMATETC formatetc = setCf(cf);
     STGMEDIUM s;
     if (pDataObj->GetData(&formatetc, &s) == S_OK) {
         DWORD * val = (DWORD*)GlobalLock(s.hGlobal);
         data = QByteArray::fromRawData((char*)val, GlobalSize(s.hGlobal));
         data.detach();
         GlobalUnlock(s.hGlobal);
         ReleaseStgMedium(&s);
     } else  {
         //Try reading IStream data
         formatetc.tymed = TYMED_ISTREAM;
         if (pDataObj->GetData(&formatetc, &s) == S_OK) {
             char szBuffer[4096];
             ULONG actualRead = 0;
             LARGE_INTEGER pos = {{0, 0}};
             //Move to front (can fail depending on the data model implemented)
             HRESULT hr = s.pstm->Seek(pos, STREAM_SEEK_SET, NULL);
             while(SUCCEEDED(hr)){
                 hr = s.pstm->Read(szBuffer, sizeof(szBuffer), &actualRead);
                 if (SUCCEEDED(hr) && actualRead > 0) {
                     data += QByteArray::fromRawData(szBuffer, actualRead);
                 }
                 if (actualRead != sizeof(szBuffer))
                     break;
             }
             data.detach();
             ReleaseStgMedium(&s);
         }
     }
     return data;
 }
isCustomMimeType()
static bool isCustomMimeType (const QString & mimeType) static
Definition at line 1251 of file qmime_win.cpp.
Referenced by QLastResortMimes::canConvertToMime(), and QLastResortMimes::convertToMime().
 {
     return mimeType.startsWith(QLatin1String(x_qt_windows_mime), Qt::CaseInsensitive);
 }
Q_GLOBAL_STATIC()
Q_GLOBAL_STATIC (QWindowsMimeList , theMimeList)
qt_read_dib()
bool qt_read_dib (QDataStream & , QImage &)
Definition at line 685 of file qbmphandler.cpp.
Referenced by QWindowsMimeImage::convertToMime().
 {
     BMP_INFOHDR bi;
     if (!read_dib_infoheader(s, bi))
         return false;
     return read_dib_body(s, bi, -1, -BMP_FILEHDR_SIZE, image);
 }
qt_read_dibv5()
static bool qt_read_dibv5 (QDataStream & s, QImage & image) static
Definition at line 1471 of file qmime_win.cpp.
Referenced by QWindowsMimeImage::convertToMime().
 {
     BMP_BITMAPV5HEADER bi;
     QIODevice* d = s.device();
     if (d->atEnd())
         return false;
     d->read((char *)&bi, sizeof(bi));   // read BITMAPV5HEADER header
     if (s.status() != QDataStream::Ok)
         return false;
     int nbits = bi.bV5BitCount;
     int comp = bi.bV5Compression;
     if (nbits != 32 || bi.bV5Planes != 1 || comp != BMP_BITFIELDS)
         return false; //Unsupported DIBV5 format
     int w = bi.bV5Width, h = bi.bV5Height;
     int red_mask = bi.bV5RedMask;
     int green_mask = bi.bV5GreenMask;
     int blue_mask = bi.bV5BlueMask;
     int alpha_mask = bi.bV5AlphaMask;
     int red_shift = 0;
     int green_shift = 0;
     int blue_shift = 0;
     int alpha_shift = 0;
     QImage::Format format = QImage::Format_ARGB32;
     if (bi.bV5Height < 0)
         h = -h;     // support images with negative height
     if (image.size() != QSize(w, h) || image.format() != format) {
         image = QImage(w, h, format);
         if (image.isNull())     // could not create image
             return false;
     }
     image.setDotsPerMeterX(bi.bV5XPelsPerMeter);
     image.setDotsPerMeterY(bi.bV5YPelsPerMeter);
     // read color table
     DWORD colorSpace[3];
     if (d->read((char *)colorSpace, sizeof(colorSpace)) != sizeof(colorSpace))
         return false;
     red_shift = calc_shift(red_mask);
     green_shift = calc_shift(green_mask);
     blue_shift = calc_shift(blue_mask);
     if (alpha_mask) {
         alpha_shift = calc_shift(alpha_mask);
     }
     int  bpl = image.bytesPerLine();
     uchar *data = image.bits();
     register QRgb *p;
     QRgb  *end;
     uchar *buf24 = new uchar[bpl];
     int    bpl24 = ((w*nbits+31)/32)*4;
     uchar *b;
     unsigned int c;
     while (--h >= 0) {
         p = (QRgb *)(data + h*bpl);
         end = p + w;
         if (d->read((char *)buf24,bpl24) != bpl24)
             break;
         b = buf24;
         while (p < end) {
             c = *b | (*(b+1))<<8 | (*(b+2))<<16 | (*(b+3))<<24;
             *p++ = qRgba(((c & red_mask) >> red_shift) ,
                                     ((c & green_mask) >> green_shift),
                                     ((c & blue_mask) >> blue_shift),
                                     ((c & alpha_mask) >> alpha_shift));
             b += 4;
         }
     }
     delete[] buf24;
     if (bi.bV5Height < 0) {
         // Flip the image
         uchar *buf = new uchar[bpl];
         h = -bi.bV5Height;
         for (int y = 0; y < h/2; ++y) {
             memcpy(buf, data + y*bpl, bpl);
             memcpy(data + y*bpl, data + (h-y-1)*bpl, bpl);
             memcpy(data + (h-y-1)*bpl, buf, bpl);
         }
         delete [] buf;
     }
     return true;
 }
qt_write_dib()
bool qt_write_dib (QDataStream & , QImage)
Definition at line 565 of file qbmphandler.cpp.
Referenced by QWindowsMimeImage::convertFromMime(), and QBmpHandler::write().
 {
     int        nbits;
     int        bpl_bmp;
     int        bpl = image.bytesPerLine();
     QIODevice* d = s.device();
     if (!d->isWritable())
         return false;
     if (image.depth() == 8 && image.colorCount() <= 16) {
         bpl_bmp = (((bpl+1)/2+3)/4)*4;
         nbits = 4;
     } else if (image.depth() == 32) {
         bpl_bmp = ((image.width()*24+31)/32)*4;
         nbits = 24;
 #ifdef Q_WS_QWS
     } else if (image.depth() == 1 || image.depth() == 8) {
         // Qt for Embedded Linux doesn't word align.
         bpl_bmp = ((image.width()*image.depth()+31)/32)*4;
         nbits = image.depth();
 #endif
     } else {
         bpl_bmp = bpl;
         nbits = image.depth();
     }
     BMP_INFOHDR bi;
     bi.biSize               = BMP_WIN;                // build info header
     bi.biWidth               = image.width();
     bi.biHeight               = image.height();
     bi.biPlanes               = 1;
     bi.biBitCount      = nbits;
     bi.biCompression   = BMP_RGB;
     bi.biSizeImage     = bpl_bmp*image.height();
     bi.biXPelsPerMeter = image.dotsPerMeterX() ? image.dotsPerMeterX()
                                                 : 2834; // 72 dpi default
     bi.biYPelsPerMeter = image.dotsPerMeterY() ? image.dotsPerMeterY() : 2834;
     bi.biClrUsed       = image.colorCount();
     bi.biClrImportant  = image.colorCount();
     s << bi;                                        // write info header
     if (s.status() != QDataStream::Ok)
         return false;
     if (image.depth() != 32) {                // write color table
         uchar *color_table = new uchar[4*image.colorCount()];
         uchar *rgb = color_table;
         QVector<QRgb> c = image.colorTable();
         for (int i=0; i<image.colorCount(); i++) {
             *rgb++ = qBlue (c[i]);
             *rgb++ = qGreen(c[i]);
             *rgb++ = qRed  (c[i]);
             *rgb++ = 0;
         }
         if (d->write((char *)color_table, 4*image.colorCount()) == -1) {
             delete [] color_table;
             return false;
         }
         delete [] color_table;
     }
     if (image.format() == QImage::Format_MonoLSB)
         image = image.convertToFormat(QImage::Format_Mono);
     int y;
     if (nbits == 1 || nbits == 8) {                // direct output
 #ifdef Q_WS_QWS
         // Qt for Embedded Linux doesn't word align.
         int pad = bpl_bmp - bpl;
         char padding[4];
 #endif
         for (y=image.height()-1; y>=0; y--) {
             if (d->write((char*)image.scanLine(y), bpl) == -1)
                 return false;
 #ifdef Q_WS_QWS
             if (d->write(padding, pad) == -1)
                 return false;
 #endif
         }
         return true;
     }
     uchar *buf        = new uchar[bpl_bmp];
     uchar *b, *end;
     register uchar *p;
     memset(buf, 0, bpl_bmp);
     for (y=image.height()-1; y>=0; y--) {        // write the image bits
         if (nbits == 4) {                        // convert 8 -> 4 bits
             p = image.scanLine(y);
             b = buf;
             end = b + image.width()/2;
             while (b < end) {
                 *b++ = (*p << 4) | (*(p+1) & 0x0f);
                 p += 2;
             }
             if (image.width() & 1)
                 *b = *p << 4;
         } else {                                // 32 bits
             QRgb *p   = (QRgb *)image.scanLine(y);
             QRgb *end = p + image.width();
             b = buf;
             while (p < end) {
                 *b++ = qBlue(*p);
                 *b++ = qGreen(*p);
                 *b++ = qRed(*p);
                 p++;
             }
         }
         if (bpl_bmp != d->write((char*)buf, bpl_bmp)) {
             delete[] buf;
             return false;
         }
     }
     delete[] buf;
     return true;
 }
qt_write_dibv5()
static bool qt_write_dibv5 (QDataStream & s, QImage image) static
Definition at line 1386 of file qmime_win.cpp.
Referenced by QWindowsMimeImage::convertFromMime().
 {
     QIODevice* d = s.device();
     if (!d->isWritable())
         return false;
     //depth will be always 32
     int bpl_bmp = image.width()*4;
     BMP_BITMAPV5HEADER bi ={0};
     bi.bV5Size          = sizeof(BMP_BITMAPV5HEADER);
     bi.bV5Width         = image.width();
     bi.bV5Height        = image.height();
     bi.bV5Planes        = 1;
     bi.bV5BitCount      = 32;
     bi.bV5Compression   = BI_BITFIELDS;
     bi.bV5SizeImage     = bpl_bmp*image.height();
     bi.bV5XPelsPerMeter = 0;
     bi.bV5YPelsPerMeter = 0;
     bi.bV5ClrUsed       = 0;
     bi.bV5ClrImportant  = 0;
     bi.bV5BlueMask      = 0x000000ff;
     bi.bV5GreenMask     = 0x0000ff00;
     bi.bV5RedMask       = 0x00ff0000;
     bi.bV5AlphaMask     = 0xff000000;
     bi.bV5CSType        = BMP_LCS_sRGB;         //LCS_sRGB
     bi.bV5Intent        = BMP_LCS_GM_IMAGES;    //LCS_GM_IMAGES
     d->write(reinterpret_cast<const char*>(&bi), bi.bV5Size);
     if (s.status() != QDataStream::Ok)
         return false;
     DWORD colorSpace[3] = {0x00ff0000,0x0000ff00,0x000000ff};
     d->write(reinterpret_cast<const char*>(colorSpace), sizeof(colorSpace));
     if (s.status() != QDataStream::Ok)
         return false;
     if (image.format() != QImage::Format_ARGB32)
         image = image.convertToFormat(QImage::Format_ARGB32);
     uchar *buf = new uchar[bpl_bmp];
     uchar *b;
     memset(buf, 0, bpl_bmp);
     for (int y=image.height()-1; y>=0; y--) {
         // write the image bits
         QRgb *p = (QRgb *)image.scanLine(y);
         QRgb *end = p + image.width();
         b = buf;
         while (p < end) {
             int alpha = qAlpha(*p);
             if (alpha) {
                 *b++ = qBlue(*p);
                 *b++ = qGreen(*p);
                 *b++ = qRed(*p);
             } else {
                 //white for fully transparent pixels.
                 *b++ = 0xff;
                 *b++ = 0xff;
                 *b++ = 0xff;
             }
             *b++ = alpha;
             p++;
         }
         d->write((char*)buf, bpl_bmp);
         if (s.status() != QDataStream::Ok) {
             delete[] buf;
             return false;
         }
     }
     delete[] buf;
     return true;
 }
setCf()
static FORMATETC setCf (int cf) static
Definition at line 130 of file qmime_win.cpp.
Referenced by canGetData(), QWindowsMimeText::formatsForMime(), QWindowsMimeURI::formatsForMime(), QWindowsMimeHtml::formatsForMime(), QWindowsMimeImage::formatsForMime(), QBuiltInMimes::formatsForMime(), QLastResortMimes::formatsForMime(), and getData().
 {
     FORMATETC formatetc;
     formatetc.cfFormat = cf;
     formatetc.dwAspect = DVASPECT_CONTENT;
     formatetc.lindex = -1;
     formatetc.ptd = NULL;
     formatetc.tymed = TYMED_HGLOBAL;
     return formatetc;
 }
setData()
static bool setData (const QByteArray & data, STGMEDIUM * pmedium) static
Definition at line 141 of file qmime_win.cpp.
Referenced by QWindowsMimeText::convertFromMime(), QWindowsMimeURI::convertFromMime(), QWindowsMimeHtml::convertFromMime(), QWindowsMimeImage::convertFromMime(), QBuiltInMimes::convertFromMime(), QLastResortMimes::convertFromMime(), QWSProtocolItem::copyFrom(), QXmlInputSource::fetchData(), QXmlInputSource::init(), QWSProtocolItem::read(), QStandardItem::setAccessibleDescription(), QStandardItem::setAccessibleText(), QStandardItem::setBackground(), QListWidgetItem::setBackground(), QTableWidgetItem::setBackground(), QTreeWidgetItem::setBackground(), QListWidgetItem::setBackgroundColor(), QTableWidgetItem::setBackgroundColor(), QTreeWidgetItem::setBackgroundColor(), QStandardItem::setCheckState(), QListWidgetItem::setCheckState(), QTableWidgetItem::setCheckState(), QTreeWidgetItem::setCheckState(), QBuffer::setData(), QXmlInputSource::setData(), QListWidgetItem::setFont(), QStandardItem::setFont(), QTableWidgetItem::setFont(), QTreeWidgetItem::setFont(), QStandardItem::setForeground(), QListWidgetItem::setForeground(), QTableWidgetItem::setForeground(), QTreeWidgetItem::setForeground(), QStandardItem::setIcon(), QListWidgetItem::setIcon(), QTableWidgetItem::setIcon(), QTreeWidgetItem::setIcon(), QClipboard::setPixmap(), QStandardItem::setSizeHint(), QListWidgetItem::setSizeHint(), QTableWidgetItem::setSizeHint(), QTreeWidgetItem::setSizeHint(), QStandardItem::setStatusTip(), QListWidgetItem::setStatusTip(), QTableWidgetItem::setStatusTip(), QTreeWidgetItem::setStatusTip(), QStandardItem::setText(), QListWidgetItem::setText(), QTableWidgetItem::setText(), QTreeWidgetItem::setText(), QAccessibleItemRow::setText(), QListWidgetItem::setTextAlignment(), QStandardItem::setTextAlignment(), QTableWidgetItem::setTextAlignment(), QTreeWidgetItem::setTextAlignment(), QListWidgetItem::setTextColor(), QTableWidgetItem::setTextColor(), QTreeWidgetItem::setTextColor(), QStandardItem::setToolTip(), QListWidgetItem::setToolTip(), QTableWidgetItem::setToolTip(), QTreeWidgetItem::setToolTip(), QGraphicsItem::setTransformOriginPoint(), QStandardItem::setWhatsThis(), QListWidgetItem::setWhatsThis(), QTableWidgetItem::setWhatsThis(), QTreeWidgetItem::setWhatsThis(), and QAbstractItemModel::sibling().
 {
     HGLOBAL hData = GlobalAlloc(0, data.size());
     if (!hData)
         return false;
     void *out = GlobalLock(hData);
     memcpy(out, data.data(), data.size());
     GlobalUnlock(hData);
     pmedium->tymed = TYMED_HGLOBAL;
     pmedium->hGlobal = hData;
     pmedium->pUnkForRelease = 0;
     return true;
 }
Variable Documentation
BMP_BITFIELDS
const int BMP_BITFIELDS = 3 static
Definition at line 112 of file qmime_win.cpp.
Referenced by qt_read_dibv5().
x_qt_windows_mime
const char x_qt_windows_mime[] = "application/x-qt-windows-mime;value=\"" static
Definition at line 1249 of file qmime_win.cpp.
Referenced by customMimeType(), isCustomMimeType(), and QLastResortMimes::mimeForFormat().