Qt 4.8: /src/gui/image/qmnghandler.cpp File Reference
qmnghandler.cpp File Reference
#include "qmnghandler_p.h"
#include "qimage.h"
#include "qvariant.h"
#include "qcolor.h"
#include <libmng.h>
Classes
class QMngHandlerPrivate
Macros
#define MNG_USE_SO
Functions
static mng_ptr myalloc (mng_size_t iSize)
static mng_bool myclosestream (mng_handle hMNG)
static mng_bool myerror (mng_handle, mng_int32 iErrorcode, mng_int8, mng_chunkid iChunkname, mng_uint32, mng_int32 iExtra1, mng_int32 iExtra2, mng_pchar zErrortext)
static void myfree (mng_ptr pPtr, mng_size_t)
static mng_ptr mygetcanvasline (mng_handle hMNG, mng_uint32 iLinenr)
static mng_uint32 mygettickcount (mng_handle hMNG)
static mng_bool myopenstream (mng_handle)
static mng_bool myprocessheader (mng_handle hMNG, mng_uint32 iWidth, mng_uint32 iHeight)
static mng_bool myprocessterm (mng_handle hMNG, mng_uint8 iTermaction, mng_uint8, mng_uint32, mng_uint32 iItermax)
static mng_bool myreaddata (mng_handle hMNG, mng_ptr pBuf, mng_uint32 iSize, mng_uint32p pRead)
static mng_bool myrefresh (mng_handle, mng_uint32, mng_uint32, mng_uint32, mng_uint32)
static mng_bool mysettimer (mng_handle hMNG, mng_uint32 iMsecs)
static mng_bool mytrace (mng_handle, mng_int32 iFuncnr, mng_int32 iFuncseq, mng_pchar zFuncname)
static mng_bool mywritedata (mng_handle hMNG, mng_ptr pBuf, mng_uint32 iSize, mng_uint32p pWritten)
Macro Definition Documentation
MNG_USE_SO
#define MNG_USE_SO
Definition at line 48 of file qmnghandler.cpp.
Function Documentation
myalloc()
static mng_ptr myalloc (mng_size_t iSize) static
Definition at line 104 of file qmnghandler.cpp.
Referenced by QMngHandlerPrivate::QMngHandlerPrivate().
 {
 #if defined(Q_OS_WINCE)
     mng_ptr ptr = malloc(iSize);
     memset(ptr, 0, iSize);
     return ptr;
 #else
     return (mng_ptr)calloc(1, iSize);
 #endif
 }
myclosestream()
static mng_bool myclosestream (mng_handle hMNG) static
Definition at line 125 of file qmnghandler.cpp.
Referenced by QMngHandlerPrivate::QMngHandlerPrivate().
 {
     QMngHandlerPrivate *pMydata = reinterpret_cast<QMngHandlerPrivate *>(mng_get_userdata(hMNG));
     pMydata->haveReadAll = true;
     return MNG_TRUE;
 }
myerror()
static mng_bool myerror (mng_handle , mng_int32 iErrorcode, mng_int8 , mng_chunkid iChunkname, mng_uint32 , mng_int32 iExtra1, mng_int32 iExtra2, mng_pchar zErrortext) static
Definition at line 85 of file qmnghandler.cpp.
Referenced by QMngHandlerPrivate::QMngHandlerPrivate().
 {
     qWarning("MNG error %d: %s; chunk %c%c%c%c; subcode %d:%d",
         iErrorcode,zErrortext,
         (iChunkname>>24)&0xff,
         (iChunkname>>16)&0xff,
         (iChunkname>>8)&0xff,
         (iChunkname>>0)&0xff,
         iExtra1,iExtra2);
     return TRUE;
 }
myfree()
static void myfree (mng_ptr pPtr, mng_size_t) static
Definition at line 115 of file qmnghandler.cpp.
Referenced by QMngHandlerPrivate::QMngHandlerPrivate().
 {
     free(pPtr);
 }
mygetcanvasline()
static mng_ptr mygetcanvasline (mng_handle hMNG, mng_uint32 iLinenr) static
Definition at line 158 of file qmnghandler.cpp.
Referenced by QMngHandlerPrivate::QMngHandlerPrivate(), and QMngHandlerPrivate::writeImage().
 {
     QMngHandlerPrivate *pMydata = reinterpret_cast<QMngHandlerPrivate *>(mng_get_userdata(hMNG));
     return (mng_ptr)pMydata->image.scanLine(iLinenr);
 }
mygettickcount()
static mng_uint32 mygettickcount (mng_handle hMNG) static
Definition at line 174 of file qmnghandler.cpp.
Referenced by QMngHandlerPrivate::QMngHandlerPrivate().
 {
     QMngHandlerPrivate *pMydata = reinterpret_cast<QMngHandlerPrivate *>(mng_get_userdata(hMNG));
     return pMydata->elapsed++;
 }
myopenstream()
static mng_bool myopenstream (mng_handle) static
Definition at line 120 of file qmnghandler.cpp.
Referenced by QMngHandlerPrivate::QMngHandlerPrivate().
 {
     return MNG_TRUE;
 }
myprocessheader()
static mng_bool myprocessheader (mng_handle hMNG, mng_uint32 iWidth, mng_uint32 iHeight) static
Definition at line 150 of file qmnghandler.cpp.
Referenced by QMngHandlerPrivate::QMngHandlerPrivate().
 {
     QMngHandlerPrivate *pMydata = reinterpret_cast<QMngHandlerPrivate *>(mng_get_userdata(hMNG));
     return pMydata->processHeader(iWidth, iHeight);
 }
myprocessterm()
static mng_bool myprocessterm (mng_handle hMNG, mng_uint8 iTermaction, mng_uint8 , mng_uint32 , mng_uint32 iItermax) static
Definition at line 189 of file qmnghandler.cpp.
Referenced by QMngHandlerPrivate::QMngHandlerPrivate().
 {
     QMngHandlerPrivate *pMydata = reinterpret_cast<QMngHandlerPrivate *>(mng_get_userdata(hMNG));
     if (iTermaction == 3)
         pMydata->iterCount = iItermax;
     return MNG_TRUE;
 }
myreaddata()
static mng_bool myreaddata (mng_handle hMNG, mng_ptr pBuf, mng_uint32 iSize, mng_uint32p pRead) static
Definition at line 132 of file qmnghandler.cpp.
Referenced by QMngHandlerPrivate::QMngHandlerPrivate().
 {
     QMngHandlerPrivate *pMydata = reinterpret_cast<QMngHandlerPrivate *>(mng_get_userdata(hMNG));
     return pMydata->readData(pBuf, iSize, pRead);
 }
myrefresh()
static mng_bool myrefresh (mng_handle , mng_uint32 , mng_uint32 , mng_uint32 , mng_uint32) static
Definition at line 165 of file qmnghandler.cpp.
Referenced by QMngHandlerPrivate::QMngHandlerPrivate().
 {
     return MNG_TRUE;
 }
mysettimer()
static mng_bool mysettimer (mng_handle hMNG, mng_uint32 iMsecs) static
Definition at line 180 of file qmnghandler.cpp.
Referenced by QMngHandlerPrivate::QMngHandlerPrivate().
 {
     QMngHandlerPrivate *pMydata = reinterpret_cast<QMngHandlerPrivate *>(mng_get_userdata(hMNG));
     pMydata->elapsed += iMsecs;
     pMydata->nextDelay = iMsecs;
     return MNG_TRUE;
 }
mytrace()
static mng_bool mytrace (mng_handle , mng_int32 iFuncnr, mng_int32 iFuncseq, mng_pchar zFuncname) static
Definition at line 201 of file qmnghandler.cpp.
Referenced by QMngHandlerPrivate::QMngHandlerPrivate().
 {
     qDebug("mng trace: iFuncnr: %d iFuncseq: %d zFuncname: %s", iFuncnr, iFuncseq, zFuncname);
     return MNG_TRUE;
 }
mywritedata()
static mng_bool mywritedata (mng_handle hMNG, mng_ptr pBuf, mng_uint32 iSize, mng_uint32p pWritten) static
Definition at line 141 of file qmnghandler.cpp.
Referenced by QMngHandlerPrivate::QMngHandlerPrivate().
 {
     QMngHandlerPrivate *pMydata = reinterpret_cast<QMngHandlerPrivate *>(mng_get_userdata(hMNG));
     return pMydata->writeData(pBuf, iSize, pWritten);
 }