Qt 4.8: /src/network/socket/qnativesocketengine_unix.cpp File Reference
qnativesocketengine_unix.cpp File Reference
#include "qnativesocketengine_p.h"
#include "private/qnet_unix_p.h"
#include "qiodevice.h"
#include "qhostaddress.h"
#include "qelapsedtimer.h"
#include "qvarlengtharray.h"
#include "qnetworkinterface.h"
#include <time.h>
#include <errno.h>
#include <fcntl.h>
#include <net/if.h>
#include <netinet/tcp.h>
Functions
static bool multicastMembershipHelper (QNativeSocketEnginePrivate *d, int how6, int how4, const QHostAddress &groupAddress, const QNetworkInterface &interface)
static void qt_socket_getPortAndAddress (const qt_sockaddr *s, quint16 *port, QHostAddress *addr)
Function Documentation
multicastMembershipHelper()
static bool multicastMembershipHelper (QNativeSocketEnginePrivate * d, int how6, int how4, const QHostAddress & groupAddress, const QNetworkInterface & interface) static
Definition at line 588 of file qnativesocketengine_unix.cpp.
Referenced by QNativeSocketEnginePrivate::nativeJoinMulticastGroup(), and QNativeSocketEnginePrivate::nativeLeaveMulticastGroup().
 {
     int level = 0;
     int sockOpt = 0;
     void *sockArg;
     int sockArgSize;
     ip_mreq mreq4;
 #ifndef QT_NO_IPV6
     ipv6_mreq mreq6;
     if (groupAddress.protocol() == QAbstractSocket::IPv6Protocol) {
         level = IPPROTO_IPV6;
         sockOpt = how6;
         sockArg = &mreq6;
         sockArgSize = sizeof(mreq6);
         memset(&mreq6, 0, sizeof(mreq6));
         Q_IPV6ADDR ip6 = groupAddress.toIPv6Address();
         memcpy(&mreq6.ipv6mr_multiaddr, &ip6, sizeof(ip6));
         mreq6.ipv6mr_interface = interface.index();
     } else
 #endif
     if (groupAddress.protocol() == QAbstractSocket::IPv4Protocol) {
         level = IPPROTO_IP;
         sockOpt = how4;
         sockArg = &mreq4;
         sockArgSize = sizeof(mreq4);
         memset(&mreq4, 0, sizeof(mreq4));
         mreq4.imr_multiaddr.s_addr = htonl(groupAddress.toIPv4Address());
         if (interface.isValid()) {
             QList<QNetworkAddressEntry> addressEntries = interface.addressEntries();
             if (!addressEntries.isEmpty()) {
                 QHostAddress firstIP = addressEntries.first().ip();
                 mreq4.imr_interface.s_addr = htonl(firstIP.toIPv4Address());
             } else {
                 d->setError(QAbstractSocket::NetworkError,
                             QNativeSocketEnginePrivate::NetworkUnreachableErrorString);
                 return false;
             }
         } else {
             mreq4.imr_interface.s_addr = INADDR_ANY;
         }
     } else {
         // unreachable
         d->setError(QAbstractSocket::UnsupportedSocketOperationError,
                     QNativeSocketEnginePrivate::ProtocolUnsupportedErrorString);
         return false;
     }
     int res = setsockopt(d->socketDescriptor, level, sockOpt, sockArg, sockArgSize);
     if (res == -1) {
         switch (errno) {
         case ENOPROTOOPT:
             d->setError(QAbstractSocket::UnsupportedSocketOperationError,
                         QNativeSocketEnginePrivate::OperationUnsupportedErrorString);
             break;
         case EADDRNOTAVAIL:
             d->setError(QAbstractSocket::SocketAddressNotAvailableError,
                         QNativeSocketEnginePrivate::AddressNotAvailableErrorString);
             break;
         default:
             d->setError(QAbstractSocket::UnknownSocketError,
                         QNativeSocketEnginePrivate::UnknownSocketErrorString);
             break;
         }
         return false;
     }
     return true;
 }
qt_socket_getPortAndAddress()
static void qt_socket_getPortAndAddress (const qt_sockaddr * s, quint16 * port, QHostAddress * addr) inline static
Definition at line 108 of file qnativesocketengine_unix.cpp.
Referenced by QNativeSocketEnginePrivate::fetchConnectionParameters(), and QNativeSocketEnginePrivate::nativeReceiveDatagram().
 {
 #if !defined(QT_NO_IPV6)
     if (s->a.sa_family == AF_INET6) {
         Q_IPV6ADDR tmp;
         memcpy(&tmp, &s->a6.sin6_addr, sizeof(tmp));
         if (addr) {
             QHostAddress tmpAddress;
             tmpAddress.setAddress(tmp);
             *addr = tmpAddress;
 #ifndef QT_NO_IPV6IFNAME
             char scopeid[IFNAMSIZ];
             if (::if_indextoname(s->a6.sin6_scope_id, scopeid)) {
                 addr->setScopeId(QLatin1String(scopeid));
             } else
 #endif
             addr->setScopeId(QString::number(s->a6.sin6_scope_id));
         }
         if (port)
             *port = ntohs(s->a6.sin6_port);
         return;
     }
 #endif
     if (port)
         *port = ntohs(s->a4.sin_port);
     if (addr) {
         QHostAddress tmpAddress;
         tmpAddress.setAddress(ntohl(s->a4.sin_addr.s_addr));
         *addr = tmpAddress;
     }
 }