Qt 4.8: /src/network/bearer/qnetworkconfigmanager.cpp File Reference
qnetworkconfigmanager.cpp File Reference
#include "qnetworkconfigmanager.h"
#include "qnetworkconfigmanager_p.h"
#include "qbearerengine_p.h"
#include <QtCore/qstringlist.h>
#include <QtCore/qcoreapplication.h>
#include <QtCore/qmutex.h>
#include <QtCore/qthread.h>
#include <QtCore/private/qcoreapplication_p.h>
#include "moc_qnetworkconfigmanager.cpp"
Functions
static QNetworkConfigurationManagerPrivate * connManager ()
static void connManager_cleanup ()
QNetworkConfigurationManagerPrivate * qNetworkConfigurationManagerPrivate ()
Variables
static QBasicAtomicInt appShutdown
static QBasicAtomicPointer< QNetworkConfigurationManagerPrivate > connManager_ptr
Function Documentation
connManager()
static QNetworkConfigurationManagerPrivate* connManager () static
Definition at line 76 of file qnetworkconfigmanager.cpp.
Referenced by QNetworkConfigurationManager::allConfigurations(), QNetworkConfigurationManager::capabilities(), QNetworkConfigurationManager::configurationFromIdentifier(), QNetworkConfigurationManager::defaultConfiguration(), QNetworkConfigurationManager::isOnline(), qNetworkConfigurationManagerPrivate(), QNetworkConfigurationManager::updateConfigurations(), and QNetworkConfigurationManager::~QNetworkConfigurationManager().
 {
     QNetworkConfigurationManagerPrivate *ptr = connManager_ptr.fetchAndAddAcquire(0);
     if (!ptr && !appShutdown) {
         QMutexLocker locker(connManager_mutex());
         if (!(ptr = connManager_ptr.fetchAndAddAcquire(0))) {
             ptr = new QNetworkConfigurationManagerPrivate;
             if (QCoreApplicationPrivate::mainThread() == QThread::currentThread()) {
                 // right thread or no main thread yet
                 ptr->addPostRoutine();
                 ptr->initialize();
             } else {
                 // wrong thread, we need to make the main thread do this
                 QObject *obj = new QObject;
                 QObject::connect(obj, SIGNAL(destroyed()), ptr, SLOT(addPostRoutine()), Qt::DirectConnection);
                 ptr->initialize(); // this moves us to the right thread
                 obj->moveToThread(QCoreApplicationPrivate::mainThread());
                 obj->deleteLater();
             }
             connManager_ptr.fetchAndStoreRelease(ptr);
         }
     }
     return ptr;
 }
connManager_cleanup()
static void connManager_cleanup () static
Definition at line 61 of file qnetworkconfigmanager.cpp.
Referenced by QNetworkConfigurationManagerPrivate::addPostRoutine().
 {
     // this is not atomic or thread-safe!
     int shutdown = appShutdown.fetchAndStoreAcquire(1);
     Q_ASSERT(shutdown == 0);
     if(connManager_ptr)
         connManager_ptr->cleanup();
     connManager_ptr = 0;
 }
qNetworkConfigurationManagerPrivate()
QNetworkConfigurationManagerPrivate* qNetworkConfigurationManagerPrivate ()
Definition at line 103 of file qnetworkconfigmanager.cpp.
Referenced by getEngineFromId(), QNetworkConfigurationManager::QNetworkConfigurationManager(), and QNetworkSession::QNetworkSession().
 {
     return connManager();
 }
Variable Documentation
appShutdown
QBasicAtomicInt appShutdown static
Definition at line 59 of file qnetworkconfigmanager.cpp.
Referenced by connManager().
connManager_ptr
QBasicAtomicPointer<QNetworkConfigurationManagerPrivate> connManager_ptr static
Definition at line 57 of file qnetworkconfigmanager.cpp.