Qt 4.8: /src/network/access/qnetworkaccessftpbackend.cpp File Reference
qnetworkaccessftpbackend.cpp File Reference
#include "qnetworkaccessftpbackend_p.h"
#include "qnetworkaccessmanager_p.h"
#include "QtNetwork/qauthenticator.h"
#include "private/qnoncontiguousbytedevice_p.h"
Classes
class QNetworkAccessCachedFtpConnection
Enumerations
enum { DefaultFtpPort = 21 }
Functions
static QByteArray makeCacheKey (const QUrl &url)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DefaultFtpPort
Definition at line 51 of file qnetworkaccessftpbackend.cpp.
      {
     DefaultFtpPort = 21
 };
Function Documentation
makeCacheKey()
static QByteArray makeCacheKey (const QUrl & url) static
Definition at line 55 of file qnetworkaccessftpbackend.cpp.
Referenced by QNetworkAccessFtpBackend::disconnectFromFtp(), QNetworkAccessFtpBackend::ftpDone(), and QNetworkAccessFtpBackend::open().
 {
     QUrl copy = url;
     copy.setPort(url.port(DefaultFtpPort));
     return "ftp-connection:" +
         copy.toEncoded(QUrl::RemovePassword | QUrl::RemovePath | QUrl::RemoveQuery |
                        QUrl::RemoveFragment);
 }