Qt 4.8: /src/network/access/qnetworkaccesshttpbackend.cpp File Reference
qnetworkaccesshttpbackend.cpp File Reference
#include "qnetworkaccesshttpbackend_p.h"
#include "qnetworkaccessmanager_p.h"
#include "qnetworkaccesscache_p.h"
#include "qabstractnetworkcache.h"
#include "qnetworkrequest.h"
#include "qnetworkreply.h"
#include "QtNetwork/private/qnetworksession_p.h"
#include "qnetworkrequest_p.h"
#include "qnetworkcookie_p.h"
#include "QtCore/qdatetime.h"
#include "QtCore/qelapsedtimer.h"
#include "QtNetwork/qsslconfiguration.h"
#include "qhttpthreaddelegate_p.h"
#include "qthread.h"
#include <string.h>
Functions
static QHttpNetworkRequest::Priority convert (const QNetworkRequest::Priority &prio)
static bool isSeparator (register char c)
static QHash< QByteArray, QByteArray > parseHttpOptionHeader (const QByteArray &header)
Function Documentation
convert()
static QHttpNetworkRequest::Priority convert (const QNetworkRequest::Priority & prio) static
Definition at line 348 of file qnetworkaccesshttpbackend.cpp.
Referenced by QNetworkAccessHttpBackend::postRequest().
 {
     switch (prio) {
     case QNetworkRequest::LowPriority:
         return QHttpNetworkRequest::LowPriority;
     case QNetworkRequest::HighPriority:
         return QHttpNetworkRequest::HighPriority;
     case QNetworkRequest::NormalPriority:
     default:
         return QHttpNetworkRequest::NormalPriority;
     }
 }
isSeparator()
static bool isSeparator (register char c) inline static
Definition at line 69 of file qnetworkaccesshttpbackend.cpp.
Referenced by QComboBoxDelegate::paint(), parseHttpOptionHeader(), and QComboBoxDelegate::sizeHint().
 {
     static const char separators[] = "()<>@,;:\\\"/[]?={}";
     return isLWS(c) || strchr(separators, c) != 0;
 }
parseHttpOptionHeader()
static QHash<QByteArray, QByteArray> parseHttpOptionHeader (const QByteArray & header) static
Definition at line 76 of file qnetworkaccesshttpbackend.cpp.
Referenced by QNetworkAccessHttpBackend::fetchCacheMetaData(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), and QNetworkAccessHttpBackend::replyDownloadMetaData().
 {
     // The HTTP header is of the form:
     // header          = #1(directives)
     // directives      = token | value-directive
     // value-directive = token "=" (token | quoted-string)
     QHash<QByteArray, QByteArray> result;
     int pos = 0;
     while (true) {
         // skip spaces
         pos = nextNonWhitespace(header, pos);
         if (pos == header.length())
             return result;      // end of parsing
         // pos points to a non-whitespace
         int comma = header.indexOf(',', pos);
         int equal = header.indexOf('=', pos);
         if (comma == pos || equal == pos)
             // huh? Broken header.
             return result;
         // The key name is delimited by either a comma, an equal sign or the end
         // of the header, whichever comes first
         int end = comma;
         if (end == -1)
             end = header.length();
         if (equal != -1 && end > equal)
             end = equal;        // equal sign comes before comma/end
         QByteArray key = QByteArray(header.constData() + pos, end - pos).trimmed().toLower();
         pos = end + 1;
         if (uint(equal) < uint(comma)) {
             // case: token "=" (token | quoted-string)
             // skip spaces
             pos = nextNonWhitespace(header, pos);
             if (pos == header.length())
                 // huh? Broken header
                 return result;
             QByteArray value;
             value.reserve(header.length() - pos);
             if (header.at(pos) == '"') {
                 // case: quoted-string
                 // quoted-string  = ( <"> *(qdtext | quoted-pair ) <"> )
                 // qdtext         = <any TEXT except <">>
                 // quoted-pair    = "\" CHAR
                 ++pos;
                 while (pos < header.length()) {
                     register char c = header.at(pos);
                     if (c == '"') {
                         // end of quoted text
                         break;
                     } else if (c == '\\') {
                         ++pos;
                         if (pos >= header.length())
                             // broken header
                             return result;
                         c = header.at(pos);
                     }
                     value += c;
                     ++pos;
                 }
             } else {
                 // case: token
                 while (pos < header.length()) {
                     register char c = header.at(pos);
                     if (isSeparator(c))
                         break;
                     value += c;
                     ++pos;
                 }
             }
             result.insert(key, value);
             // find the comma now:
             comma = header.indexOf(',', pos);
             if (comma == -1)
                 return result;  // end of parsing
             pos = comma + 1;
         } else {
             // case: token
             // key is already set
             result.insert(key, QByteArray());
         }
     }
 }