Qt 4.8: /src/network/access/qnetworkrequest.cpp File Reference
qnetworkrequest.cpp File Reference
#include "qplatformdefs.h"
#include "qnetworkrequest.h"
#include "qnetworkcookie.h"
#include "qnetworkrequest_p.h"
#include "qsslconfiguration.h"
#include "QtCore/qshareddata.h"
#include "QtCore/qlocale.h"
#include "QtCore/qdatetime.h"
#include <ctype.h>
#include <stdio.h>
Classes
class QNetworkRequestPrivate
Functions
static QByteArray headerName (QNetworkRequest::KnownHeaders header)
static QByteArray headerValue (QNetworkRequest::KnownHeaders header, const QVariant &value)
static int name_to_month (const char *month_str)
static QVariant parseCookieHeader (const QByteArray &raw)
static QNetworkRequest::KnownHeaders parseHeaderName (const QByteArray &headerName)
static QVariant parseHeaderValue (QNetworkRequest::KnownHeaders header, const QByteArray &value)
static QVariant parseHttpDate (const QByteArray &raw)
Function Documentation
headerName()
static QByteArray headerName (QNetworkRequest::KnownHeaders header) static
Definition at line 654 of file qnetworkrequest.cpp.
Referenced by QHttpPart::operator!=(), QNetworkRequest::operator!=(), qmlxmlhttprequest_getResponseHeader(), and QNetworkHeadersPrivate::setCookedHeader().
 {
     switch (header) {
     case QNetworkRequest::ContentTypeHeader:
         return "Content-Type";
     case QNetworkRequest::ContentLengthHeader:
         return "Content-Length";
     case QNetworkRequest::LocationHeader:
         return "Location";
     case QNetworkRequest::LastModifiedHeader:
         return "Last-Modified";
     case QNetworkRequest::CookieHeader:
         return "Cookie";
     case QNetworkRequest::SetCookieHeader:
         return "Set-Cookie";
     case QNetworkRequest::ContentDispositionHeader:
         return "Content-Disposition";
     // no default:
     // if new values are added, this will generate a compiler warning
     }
     return QByteArray();
 }
headerValue()
static QByteArray headerValue (QNetworkRequest::KnownHeaders header, const QVariant & value) static
Definition at line 685 of file qnetworkrequest.cpp.
Referenced by QHttpPart::operator!=(), and QNetworkHeadersPrivate::setCookedHeader().
 {
     switch (header) {
     case QNetworkRequest::ContentTypeHeader:
     case QNetworkRequest::ContentLengthHeader:
     case QNetworkRequest::ContentDispositionHeader:
         return value.toByteArray();
     case QNetworkRequest::LocationHeader:
         switch (value.type()) {
         case QVariant::Url:
             return value.toUrl().toEncoded();
         default:
             return value.toByteArray();
         }
     case QNetworkRequest::LastModifiedHeader:
         switch (value.type()) {
         case QVariant::Date:
         case QVariant::DateTime:
             // generate RFC 1123/822 dates:
             return QNetworkHeadersPrivate::toHttpDate(value.toDateTime());
         default:
             return value.toByteArray();
         }
     case QNetworkRequest::CookieHeader: {
         QList<QNetworkCookie> cookies = qvariant_cast<QList<QNetworkCookie> >(value);
         if (cookies.isEmpty() && value.userType() == qMetaTypeId<QNetworkCookie>())
             cookies << qvariant_cast<QNetworkCookie>(value);
         QByteArray result;
         bool first = true;
         foreach (const QNetworkCookie &cookie, cookies) {
             if (!first)
                 result += "; ";
             first = false;
             result += cookie.toRawForm(QNetworkCookie::NameAndValueOnly);
         }
         return result;
     }
     case QNetworkRequest::SetCookieHeader: {
         QList<QNetworkCookie> cookies = qvariant_cast<QList<QNetworkCookie> >(value);
         if (cookies.isEmpty() && value.userType() == qMetaTypeId<QNetworkCookie>())
             cookies << qvariant_cast<QNetworkCookie>(value);
         QByteArray result;
         bool first = true;
         foreach (const QNetworkCookie &cookie, cookies) {
             if (!first)
                 result += ", ";
             first = false;
             result += cookie.toRawForm(QNetworkCookie::Full);
         }
         return result;
     }
     }
     return QByteArray();
 }
name_to_month()
static int name_to_month (const char * month_str) static
Definition at line 967 of file qnetworkrequest.cpp.
Referenced by QNetworkHeadersPrivate::fromHttpDate().
 {
     switch (month_str[0]) {
     case 'J':
         switch (month_str[1]) {
         case 'a':
             return 1;
             break;
         case 'u':
             switch (month_str[2] ) {
             case 'n':
                 return 6;
                 break;
             case 'l':
                 return 7;
                 break;
             }
         }
         break;
     case 'F':
         return 2;
         break;
     case 'M':
         switch (month_str[2] ) {
         case 'r':
             return 3;
             break;
         case 'y':
             return 5;
             break;
         }
         break;
     case 'A':
         switch (month_str[1]) {
         case 'p':
             return 4;
             break;
         case 'u':
             return 8;
             break;
         }
         break;
     case 'O':
         return 10;
         break;
     case 'S':
         return 9;
         break;
     case 'N':
         return 11;
         break;
     case 'D':
         return 12;
         break;
     }
     return 0;
 }
parseCookieHeader()
static QVariant parseCookieHeader (const QByteArray & raw) static
Definition at line 788 of file qnetworkrequest.cpp.
Referenced by parseHeaderValue().
 {
     QList<QNetworkCookie> result;
     QList<QByteArray> cookieList = raw.split(';');
     foreach (const QByteArray &cookie, cookieList) {
         QList<QNetworkCookie> parsed = QNetworkCookie::parseCookies(cookie.trimmed());
         if (parsed.count() != 1)
             return QVariant();  // invalid Cookie: header
         result += parsed;
     }
     return QVariant::fromValue(result);
 }
parseHeaderName()
static QNetworkRequest::KnownHeaders parseHeaderName (const QByteArray & headerName) static
Definition at line 749 of file qnetworkrequest.cpp.
Referenced by QNetworkHeadersPrivate::parseAndSetHeader().
 {
     if (headerName.isEmpty())
         return QNetworkRequest::KnownHeaders(-1);
     switch (tolower(headerName.at(0))) {
     case 'c':
         if (qstricmp(headerName.constData(), "content-type") == 0)
             return QNetworkRequest::ContentTypeHeader;
         else if (qstricmp(headerName.constData(), "content-length") == 0)
             return QNetworkRequest::ContentLengthHeader;
         else if (qstricmp(headerName.constData(), "cookie") == 0)
             return QNetworkRequest::CookieHeader;
         break;
     case 'l':
         if (qstricmp(headerName.constData(), "location") == 0)
             return QNetworkRequest::LocationHeader;
         else if (qstricmp(headerName.constData(), "last-modified") == 0)
             return QNetworkRequest::LastModifiedHeader;
         break;
     case 's':
         if (qstricmp(headerName.constData(), "set-cookie") == 0)
             return QNetworkRequest::SetCookieHeader;
         break;
     }
     return QNetworkRequest::KnownHeaders(-1); // nothing found
 }
parseHeaderValue()
static QVariant parseHeaderValue (QNetworkRequest::KnownHeaders header, const QByteArray & value) static
Definition at line 803 of file qnetworkrequest.cpp.
Referenced by QNetworkHeadersPrivate::parseAndSetHeader().
 {
     // header is always a valid value
     switch (header) {
     case QNetworkRequest::ContentTypeHeader:
         // copy exactly, convert to QString
         return QString::fromLatin1(value);
     case QNetworkRequest::ContentLengthHeader: {
         bool ok;
         qint64 result = value.trimmed().toLongLong(&ok);
         if (ok)
             return result;
         return QVariant();
     }
     case QNetworkRequest::LocationHeader: {
         QUrl result = QUrl::fromEncoded(value, QUrl::StrictMode);
         if (result.isValid() && !result.scheme().isEmpty())
             return result;
         return QVariant();
     }
     case QNetworkRequest::LastModifiedHeader:
         return parseHttpDate(value);
     case QNetworkRequest::CookieHeader:
         return parseCookieHeader(value);
     case QNetworkRequest::SetCookieHeader:
         return QVariant::fromValue(QNetworkCookie::parseCookies(value));
     default:
         Q_ASSERT(0);
     }
     return QVariant();
 }
parseHttpDate()
static QVariant parseHttpDate (const QByteArray & raw) static
Definition at line 780 of file qnetworkrequest.cpp.
Referenced by parseHeaderValue().
 {
     QDateTime dt = QNetworkHeadersPrivate::fromHttpDate(raw);
     if (dt.isValid())
         return dt;
     return QVariant();          // transform an invalid QDateTime into a null QVariant
 }