Qt 4.8: /src/network/bearer/qnetworkconfigmanager_p.h File Reference
qnetworkconfigmanager_p.h File Reference
#include "qnetworkconfigmanager.h"
#include "qnetworkconfiguration_p.h"
#include <QtCore/qmutex.h>
#include <QtCore/qset.h>
Classes
class QNetworkConfigurationManagerPrivate
Functions
Q_NETWORK_EXPORT QNetworkConfigurationManagerPrivate * qNetworkConfigurationManagerPrivate ()
Function Documentation
qNetworkConfigurationManagerPrivate()
Q_NETWORK_EXPORT QNetworkConfigurationManagerPrivate* qNetworkConfigurationManagerPrivate ()
Definition at line 103 of file qnetworkconfigmanager.cpp.
Referenced by getEngineFromId(), QNetworkConfigurationManager::QNetworkConfigurationManager(), and QNetworkSession::QNetworkSession().
 {
     return connManager();
 }