Qt 4.8: /src/network/access/qnetworkaccessauthenticationmanager.cpp File Reference
qnetworkaccessauthenticationmanager.cpp File Reference
#include "qnetworkaccessmanager.h"
#include "qnetworkaccessmanager_p.h"
#include "qnetworkaccessauthenticationmanager_p.h"
#include "QtCore/qbuffer.h"
#include "QtCore/qurl.h"
#include "QtCore/qvector.h"
#include "QtCore/QMutexLocker"
#include "QtNetwork/qauthenticator.h"
Classes
class QNetworkAuthenticationCache
Functions
static QByteArray authenticationKey (const QUrl &url, const QString &realm)
static QByteArray proxyAuthenticationKey (const QNetworkProxy &proxy, const QString &realm)
Function Documentation
authenticationKey()
static QByteArray authenticationKey (const QUrl & url, const QString & realm) inline static
Definition at line 141 of file qnetworkaccessauthenticationmanager.cpp.
Referenced by QNetworkAccessAuthenticationManager::cacheCredentials(), and QNetworkAccessAuthenticationManager::fetchCachedCredentials().
 {
     QUrl copy = url;
     copy.setFragment(realm);
     return "auth:" + copy.toEncoded(QUrl::RemovePassword | QUrl::RemovePath | QUrl::RemoveQuery);
 }
proxyAuthenticationKey()
static QByteArray proxyAuthenticationKey (const QNetworkProxy & proxy, const QString & realm) static
Definition at line 102 of file qnetworkaccessauthenticationmanager.cpp.
Referenced by QNetworkAccessAuthenticationManager::cacheProxyCredentials(), and QNetworkAccessAuthenticationManager::fetchCachedProxyCredentials().
 {
     QUrl key;
     switch (proxy.type()) {
     case QNetworkProxy::Socks5Proxy:
         key.setScheme(QLatin1String("proxy-socks5"));
         break;
     case QNetworkProxy::HttpProxy:
     case QNetworkProxy::HttpCachingProxy:
         key.setScheme(QLatin1String("proxy-http"));
         break;
     case QNetworkProxy::FtpCachingProxy:
         key.setScheme(QLatin1String("proxy-ftp"));
         break;
     case QNetworkProxy::DefaultProxy:
     case QNetworkProxy::NoProxy:
         // shouldn't happen
         return QByteArray();
         // no default:
         // let there be errors if a new proxy type is added in the future
     }
     if (key.scheme().isEmpty())
         // proxy type not handled
         return QByteArray();
     key.setUserName(proxy.user());
     key.setHost(proxy.hostName());
     key.setPort(proxy.port());
     key.setFragment(realm);
     return "auth:" + key.toEncoded();
 }