Qt 4.8: /src/network/access/qnetworkcookiejar.cpp File Reference
qnetworkcookiejar.cpp File Reference
#include "qnetworkcookiejar.h"
#include "qnetworkcookiejar_p.h"
#include "QtNetwork/qnetworkcookie.h"
#include "QtCore/qurl.h"
#include "QtCore/qdatetime.h"
#include "private/qtldurl_p.h"
Functions
static bool isParentDomain (QString domain, QString reference)
static bool isParentPath (QString path, QString reference)
Function Documentation
isParentDomain()
static bool isParentDomain (QString domain, QString reference) inline static
Definition at line 151 of file qnetworkcookiejar.cpp.
Referenced by QNetworkCookieJar::cookiesForUrl(), and QNetworkCookieJar::setCookiesFromUrl().
 {
     if (!reference.startsWith(QLatin1Char('.')))
         return domain == reference;
     return domain.endsWith(reference) || domain == reference.mid(1);
 }
isParentPath()
static bool isParentPath (QString path, QString reference) inline static
Definition at line 142 of file qnetworkcookiejar.cpp.
Referenced by QNetworkCookieJar::cookiesForUrl().
 {
     if (!path.endsWith(QLatin1Char('/')))
         path += QLatin1Char('/');
     if (!reference.endsWith(QLatin1Char('/')))
         reference += QLatin1Char('/');
     return path.startsWith(reference);
 }