Qt 4.8: /src/network/access/qnetworkcookie_p.h File Reference
qnetworkcookie_p.h File Reference
#include "QtCore/qdatetime.h"
Classes
class QNetworkCookiePrivate
Functions
static bool isLWS (register char c)
static int nextNonWhitespace (const QByteArray &text, int from)
Function Documentation
isLWS()
static bool isLWS (register char c) inline static
Definition at line 76 of file qnetworkcookie_p.h.
Referenced by isSeparator(), nextField(), and nextNonWhitespace().
 {
     return c == ' ' || c == '\t' || c == '\r' || c == '\n';
 }
nextNonWhitespace()
static int nextNonWhitespace (const QByteArray & text, int from) static
Definition at line 81 of file qnetworkcookie_p.h.
Referenced by nextField(), parseHttpOptionHeader(), and QNetworkCookiePrivate::parseSetCookieHeaderLine().
 {
     // RFC 2616 defines linear whitespace as:
     //  LWS = [CRLF] 1*( SP | HT )
     // We ignore the fact that CRLF must come as a pair at this point
     // It's an invalid HTTP header if that happens.
     while (from < text.length()) {
         if (isLWS(text.at(from)))
             ++from;
         else
             return from;        // non-whitespace
     }
     // reached the end
     return text.length();
 }