Qt 4.8: /src/network/socket/qnet_unix_p.h File Reference
qnet_unix_p.h File Reference
#include "private/qcore_unix_p.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <resolv.h>
Macros
#define QT_SOCKET_CONNECT qt_safe_connect
#define QT_SOCKOPTLEN_T QT_SOCKLEN_T
Functions
static int qt_safe_accept (int s, struct sockaddr *addr, QT_SOCKLEN_T *addrlen, int flags=0)
static int qt_safe_connect (int sockfd, const struct sockaddr *addr, QT_SOCKLEN_T addrlen)
static in_addr_t qt_safe_inet_addr (const char *cp)
template<typename T >
static int qt_safe_ioctl (int sockfd, int request, T arg)
static int qt_safe_listen (int s, int backlog)
static int qt_safe_sendto (int sockfd, const void *buf, size_t len, int flags, const struct sockaddr *to, QT_SOCKLEN_T tolen)
static int qt_safe_socket (int domain, int type, int protocol, int flags=0)
Macro Definition Documentation
QT_SOCKET_CONNECT
#define QT_SOCKET_CONNECT qt_safe_connect
Definition at line 153 of file qnet_unix_p.h.
Referenced by qt_safe_connect().
QT_SOCKOPTLEN_T
#define QT_SOCKOPTLEN_T QT_SOCKLEN_T
Definition at line 79 of file qnet_unix_p.h.
Function Documentation
qt_safe_accept()
static int qt_safe_accept (int s, struct sockaddr * addr, QT_SOCKLEN_T * addrlen, int flags = 0) inline static
Definition at line 111 of file qnet_unix_p.h.
Referenced by QNativeSocketEnginePrivate::nativeAccept().
 {
     Q_ASSERT((flags & ~O_NONBLOCK) == 0);
     register int fd;
 #if QT_UNIX_SUPPORTS_THREADSAFE_CLOEXEC && defined(SOCK_CLOEXEC) && defined(SOCK_NONBLOCK)
     // use accept4
     int sockflags = SOCK_CLOEXEC;
     if (flags & O_NONBLOCK)
         sockflags |= SOCK_NONBLOCK;
     fd = ::accept4(s, addr, static_cast<QT_SOCKLEN_T *>(addrlen), sockflags);
     if (fd != -1 || !(errno == ENOSYS || errno == EINVAL))
         return fd;
 #endif
     fd = ::accept(s, addr, static_cast<QT_SOCKLEN_T *>(addrlen));
     if (fd == -1)
         return -1;
     ::fcntl(fd, F_SETFD, FD_CLOEXEC);
     // set non-block too?
     if (flags & O_NONBLOCK)
         ::fcntl(fd, F_SETFL, ::fcntl(fd, F_GETFL) | O_NONBLOCK);
     return fd;
 }
qt_safe_connect()
static int qt_safe_connect (int sockfd, const struct sockaddr * addr, QT_SOCKLEN_T addrlen) inline static
Definition at line 145 of file qnet_unix_p.h.
Referenced by QNativeSocketEnginePrivate::nativeConnect().
 {
     register int ret;
     // Solaris e.g. expects a non-const 2nd parameter
     EINTR_LOOP(ret, QT_SOCKET_CONNECT(sockfd, const_cast<struct sockaddr *>(addr), addrlen));
     return ret;
 }
qt_safe_inet_addr()
static in_addr_t qt_safe_inet_addr (const char * cp) inline static
Definition at line 177 of file qnet_unix_p.h.
Referenced by QHostInfoAgent::fromName().
 {
 #ifdef Q_OS_VXWORKS
     return ::inet_addr((char *) cp);
 #else
     return ::inet_addr(cp);
 #endif
 }
qt_safe_ioctl()
template<typename T > static int qt_safe_ioctl (int sockfd, int request, T arg) inline static
Definition at line 167 of file qnet_unix_p.h.
Referenced by convertFlags(), QNativeSocketEnginePrivate::nativeBytesAvailable(), and QNativeSocketEnginePrivate::setOption().
 {
 #ifdef Q_OS_VXWORKS
     return ::ioctl(sockfd, request, (int) arg);
 #else
     return ::ioctl(sockfd, request, arg);
 #endif
 }
qt_safe_listen()
static int qt_safe_listen (int s, int backlog) inline static
Definition at line 140 of file qnet_unix_p.h.
Referenced by QNativeSocketEnginePrivate::nativeListen().
 {
     return ::listen(s, backlog);
 }
qt_safe_sendto()
static int qt_safe_sendto (int sockfd, const void * buf, size_t len, int flags, const struct sockaddr * to, QT_SOCKLEN_T tolen) inline static
Definition at line 187 of file qnet_unix_p.h.
Referenced by QNativeSocketEnginePrivate::nativeSendDatagram().
 {
 #ifdef MSG_NOSIGNAL
     flags |= MSG_NOSIGNAL;
 #else
     qt_ignore_sigpipe();
 #endif
     register int ret;
 #ifdef Q_OS_VXWORKS
     EINTR_LOOP(ret, ::sendto(sockfd, (char *) buf, len, flags, (struct sockaddr *) to, tolen));
 #else
     EINTR_LOOP(ret, ::sendto(sockfd, buf, len, flags, to, tolen));
 #endif
     return ret;
 }
qt_safe_socket()
static int qt_safe_socket (int domain, int type, int protocol, int flags = 0) inline static
Definition at line 83 of file qnet_unix_p.h.
Referenced by convertFlags(), QNativeSocketEnginePrivate::createNewSocket(), and interfaceListing().
 {
     Q_ASSERT((flags & ~O_NONBLOCK) == 0);
     register int fd;
 #if defined(SOCK_CLOEXEC) && defined(SOCK_NONBLOCK)
     int newtype = type | SOCK_CLOEXEC;
     if (flags & O_NONBLOCK)
         newtype |= SOCK_NONBLOCK;
     fd = ::socket(domain, newtype, protocol);
     if (fd != -1 || errno != EINVAL)
         return fd;
 #endif
     fd = ::socket(domain, type, protocol);
     if (fd == -1)
         return -1;
     ::fcntl(fd, F_SETFD, FD_CLOEXEC);
     // set non-block too?
     if (flags & O_NONBLOCK)
         ::fcntl(fd, F_SETFL, ::fcntl(fd, F_GETFL) | O_NONBLOCK);
     return fd;
 }