Qt 4.8: /src/network/access/qnetworkcookie.cpp File Reference
qnetworkcookie.cpp File Reference
#include "qnetworkcookie.h"
#include "qnetworkcookie_p.h"
#include "qnetworkrequest.h"
#include "qnetworkreply.h"
#include "QtCore/qbytearray.h"
#include "QtCore/qdebug.h"
#include "QtCore/qlist.h"
#include "QtCore/qlocale.h"
#include "QtCore/qstring.h"
#include "QtCore/qstringlist.h"
#include "QtCore/qurl.h"
#include "private/qobject_p.h"
Macros
#define ADAY 1
#define AMONTH 2
#define AYEAR 4
Functions
static bool checkStaticArray (int &val, const QByteArray &dateString, int at, const char *array, int size)
static bool isNumber (char s)
static bool isTerminator (char c)
static bool isValueSeparator (char c)
static bool isWhitespace (char c)
static QPair< QByteArray, QByteArray > nextField (const QByteArray &text, int &position, bool isNameValue)
QDebug operator<< (QDebug s, const QNetworkCookie &cookie)
static QDateTime parseDateString (const QByteArray &dateString)
Variables
static const char months []
static int zoneOffsets [] = {-8, -8, -7, -7, -6, -6, -5, -5, -4, -3, 0, 0, 0, 1, 2, 9 }
static const char zones []
Macro Definition Documentation
ADAY
#define ADAY 1
Definition at line 618 of file qnetworkcookie.cpp.
Referenced by parseDateString().
AMONTH
#define AMONTH 2
Definition at line 619 of file qnetworkcookie.cpp.
Referenced by parseDateString().
AYEAR
#define AYEAR 4
Definition at line 620 of file qnetworkcookie.cpp.
Referenced by parseDateString().
Function Documentation
checkStaticArray()
static bool checkStaticArray (int & val, const QByteArray & dateString, int at, const char * array, int size) static
Definition at line 594 of file qnetworkcookie.cpp.
Referenced by parseDateString().
 {
     if (dateString[at] < 'a' || dateString[at] > 'z')
         return false;
     if (val == -1 && dateString.length() >= at + 3) {
         int j = 0;
         int i = 0;
         while (i <= size) {
             const char *str = array + i;
             if (str[0] == dateString[at]
                 && str[1] == dateString[at + 1]
                 && str[2] == dateString[at + 2]) {
                 val = j;
                 return true;
             }
             i += strlen(str) + 1;
             ++j;
         }
     }
     return false;
 }
isNumber()
static bool isNumber (char s) inline static
Definition at line 582 of file qnetworkcookie.cpp.
Referenced by QAxBase::dynamicCallHelper(), QChar::isNull(), and parseDateString().
 { return s >= '0' && s <= '9'; }
isTerminator()
static bool isTerminator (char c) inline static
Definition at line 585 of file qnetworkcookie.cpp.
Referenced by isValueSeparator().
 { return c == '\n' || c == '\r'; }
isValueSeparator()
static bool isValueSeparator (char c) inline static
Definition at line 588 of file qnetworkcookie.cpp.
Referenced by QNetworkCookiePrivate::parseSetCookieHeaderLine().
 { return isTerminator(c) || c == ';'; }
isWhitespace()
static bool isWhitespace (char c) inline static
Definition at line 591 of file qnetworkcookie.cpp.
Referenced by QXmlStreamReader::isCharacters(), QXmlStreamReaderPrivate::parse(), and parseDateString().
 { return c == ' '  || c == '\t'; }
nextField()
static QPair<QByteArray, QByteArray> nextField (const QByteArray & text, int & position, bool isNameValue) static
Definition at line 374 of file qnetworkcookie.cpp.
Referenced by QNetworkCookiePrivate::parseSetCookieHeaderLine().
 {
     // format is one of:
     //    (1)  token
     //    (2)  token = token
     //    (3)  token = quoted-string
     int i;
     const int length = text.length();
     position = nextNonWhitespace(text, position);
     // parse the first part, before the equal sign
     for (i = position; i < length; ++i) {
         register char c = text.at(i);
         if (c == ';' || c == '=')
             break;
     }
     QByteArray first = text.mid(position, i - position).trimmed();
     position = i;
     if (first.isEmpty())
         return qMakePair(QByteArray(), QByteArray());
     if (i == length || text.at(i) != '=')
         // no equal sign, we found format (1)
         return qMakePair(first, QByteArray());
     QByteArray second;
     second.reserve(32);         // arbitrary but works for most cases
     i = nextNonWhitespace(text, position + 1);
     if (i < length && text.at(i) == '"') {
         // a quote, we found format (3), where:
         // quoted-string  = ( <"> *(qdtext | quoted-pair ) <"> )
         // qdtext         = <any TEXT except <">>
         // quoted-pair    = "\" CHAR
         // If it is NAME=VALUE, retain the value as is
         // refer to http://bugreports.qt-project.org/browse/QTBUG-17746
         if (isNameValue)
             second += '"';
         ++i;
         while (i < length) {
             register char c = text.at(i);
             if (c == '"') {
                 // end of quoted text
                 if (isNameValue)
                     second += '"';
                 break;
             } else if (c == '\\') {
                 if (isNameValue)
                     second += '\\';
                 ++i;
                 if (i >= length)
                     // broken line
                     return qMakePair(QByteArray(), QByteArray());
                 c = text.at(i);
             }
             second += c;
             ++i;
         }
         for ( ; i < length; ++i) {
             register char c = text.at(i);
             if (c == ';')
                 break;
         }
         position = i;
     } else {
         // no quote, we found format (2)
         position = i;
         for ( ; i < length; ++i) {
             register char c = text.at(i);
             // for name value pairs, we want to parse until reaching the next ';'
             // and not break when reaching a space char
             if (c == ';' || ((isNameValue && (c == '\n' || c == '\r')) || (!isNameValue && isLWS(c))))
                 break;
         }
         second = text.mid(position, i - position).trimmed();
         position = i;
     }
     if (second.isNull())
         second.resize(0); // turns into empty-but-not-null
     return qMakePair(first, second);
 }
operator<<()
QDebug operator<< (QDebug s, const QNetworkCookie & cookie)
Definition at line 1053 of file qnetworkcookie.cpp.
 {
     s.nospace() << "QNetworkCookie(" << cookie.toRawForm(QNetworkCookie::Full) << ')';
     return s.space();
 }
parseDateString()
static QDateTime parseDateString (const QByteArray & dateString) static
Definition at line 641 of file qnetworkcookie.cpp.
Referenced by QNetworkCookiePrivate::parseSetCookieHeaderLine().
 {
     QTime time;
     // placeholders for values when we are not sure it is a year, month or day
     int unknown[3] = {-1, -1, -1};
     int month = -1;
     int day = -1;
     int year = -1;
     int zoneOffset = -1;
     // hour:minute:second.ms pm
     QRegExp timeRx(QLatin1String("(\\d{1,2}):(\\d{1,2})(:(\\d{1,2})|)(\\.(\\d{1,3})|)((\\s{0,}(am|pm))|)"));
     int at = 0;
     while (at < dateString.length()) {
 #ifdef PARSEDATESTRINGDEBUG
         qDebug() << dateString.mid(at);
 #endif
         bool isNum = isNumber(dateString[at]);
         // Month
         if (!isNum
             && checkStaticArray(month, dateString, at, months, sizeof(months)- 1)) {
             ++month;
 #ifdef PARSEDATESTRINGDEBUG
             qDebug() << "Month:" << month;
 #endif
             at += 3;
             continue;
         }
         // Zone
         if (!isNum
             && zoneOffset == -1
             && checkStaticArray(zoneOffset, dateString, at, zones, sizeof(zones)- 1)) {
             int sign = (at >= 0 && dateString[at - 1] == '-') ? -1 : 1;
             zoneOffset = sign * zoneOffsets[zoneOffset] * 60 * 60;
 #ifdef PARSEDATESTRINGDEBUG
             qDebug() << "Zone:" << month;
 #endif
             at += 3;
             continue;
         }
         // Zone offset
         if (!isNum
             && (zoneOffset == -1 || zoneOffset == 0) // Can only go after gmt
             && (dateString[at] == '+' || dateString[at] == '-')
             && (at == 0
                 || isWhitespace(dateString[at - 1])
                 || dateString[at - 1] == ','
                 || (at >= 3
                     && (dateString[at - 3] == 'g')
                     && (dateString[at - 2] == 'm')
                     && (dateString[at - 1] == 't')))) {
             int end = 1;
             while (end < 5 && dateString.length() > at+end
                    && dateString[at + end] >= '0' && dateString[at + end] <= '9')
                 ++end;
             int minutes = 0;
             int hours = 0;
             switch (end - 1) {
             case 4:
                 minutes = atoi(dateString.mid(at + 3, 2).constData());
                 // fall through
             case 2:
                 hours = atoi(dateString.mid(at + 1, 2).constData());
                 break;
             case 1:
                 hours = atoi(dateString.mid(at + 1, 1).constData());
                 break;
             default:
                 at += end;
                 continue;
             }
             if (end != 1) {
                 int sign = dateString[at] == '-' ? -1 : 1;
                 zoneOffset = sign * ((minutes * 60) + (hours * 60 * 60));
 #ifdef PARSEDATESTRINGDEBUG
                 qDebug() << "Zone offset:" << zoneOffset << hours << minutes;
 #endif
                 at += end;
                 continue;
             }
         }
         // Time
         if (isNum && time.isNull()
             && dateString.length() >= at + 3
             && (dateString[at + 2] == ':' || dateString[at + 1] == ':')) {
             // While the date can be found all over the string the format
             // for the time is set and a nice regexp can be used.
             int pos = timeRx.indexIn(QLatin1String(dateString), at);
             if (pos != -1) {
                 QStringList list = timeRx.capturedTexts();
                 int h = atoi(list.at(1).toLatin1().constData());
                 int m = atoi(list.at(2).toLatin1().constData());
                 int s = atoi(list.at(4).toLatin1().constData());
                 int ms = atoi(list.at(6).toLatin1().constData());
                 if (h < 12 && !list.at(9).isEmpty())
                     if (list.at(9) == QLatin1String("pm"))
                         h += 12;
                 time = QTime(h, m, s, ms);
 #ifdef PARSEDATESTRINGDEBUG
                 qDebug() << "Time:" << list << timeRx.matchedLength();
 #endif
                 at += timeRx.matchedLength();
                 continue;
             }
         }
         // 4 digit Year
         if (isNum
             && year == -1
             && dateString.length() > at + 3) {
             if (isNumber(dateString[at + 1])
                 && isNumber(dateString[at + 2])
                 && isNumber(dateString[at + 3])) {
                 year = atoi(dateString.mid(at, 4).constData());
                 at += 4;
 #ifdef PARSEDATESTRINGDEBUG
                 qDebug() << "Year:" << year;
 #endif
                 continue;
             }
         }
         // a one or two digit number
         // Could be month, day or year
         if (isNum) {
             int length = 1;
             if (dateString.length() > at + 1
                 && isNumber(dateString[at + 1]))
                 ++length;
             int x = atoi(dateString.mid(at, length).constData());
             if (year == -1 && (x > 31 || x == 0)) {
                 year = x;
             } else {
                 if (unknown[0] == -1) unknown[0] = x;
                 else if (unknown[1] == -1) unknown[1] = x;
                 else if (unknown[2] == -1) unknown[2] = x;
             }
             at += length;
 #ifdef PARSEDATESTRINGDEBUG
             qDebug() << "Saving" << x;
 #endif
             continue;
         }
         // Unknown character, typically a weekday such as 'Mon'
         ++at;
     }
     // Once we are done parsing the string take the digits in unknown
     // and determine which is the unknown year/month/day
     int couldBe[3] = { 0, 0, 0 };
     int unknownCount = 3;
     for (int i = 0; i < unknownCount; ++i) {
         if (unknown[i] == -1) {
             couldBe[i] = ADAY | AYEAR | AMONTH;
             unknownCount = i;
             continue;
         }
         if (unknown[i] >= 1)
             couldBe[i] = ADAY;
         if (month == -1 && unknown[i] >= 1 && unknown[i] <= 12)
             couldBe[i] |= AMONTH;
         if (year == -1)
             couldBe[i] |= AYEAR;
     }
     // For any possible day make sure one of the values that could be a month
     // can contain that day.
     // For any possible month make sure one of the values that can be a
     // day that month can have.
     // Example: 31 11 06
     // 31 can't be a day because 11 and 6 don't have 31 days
     for (int i = 0; i < unknownCount; ++i) {
         int currentValue = unknown[i];
         bool findMatchingMonth = couldBe[i] & ADAY && currentValue >= 29;
         bool findMatchingDay = couldBe[i] & AMONTH;
         if (!findMatchingMonth || !findMatchingDay)
             continue;
         for (int j = 0; j < 3; ++j) {
             if (j == i)
                 continue;
             for (int k = 0; k < 2; ++k) {
                 if (k == 0 && !(findMatchingMonth && (couldBe[j] & AMONTH)))
                     continue;
                 else if (k == 1 && !(findMatchingDay && (couldBe[j] & ADAY)))
                     continue;
                 int m = currentValue;
                 int d = unknown[j];
                 if (k == 0)
                     qSwap(m, d);
                 if (m == -1) m = month;
                 bool found = true;
                 switch(m) {
                     case 2:
                         // When we get 29 and the year ends up having only 28
                         // See date.isValid below
                         // Example: 29 23 Feb
                         if (d <= 29)
                             found = false;
                         break;
                     case 4: case 6: case 9: case 11:
                         if (d <= 30)
                             found = false;
                         break;
                     default:
                         if (d > 0 && d <= 31)
                             found = false;
                 }
                 if (k == 0) findMatchingMonth = found;
                 else if (k == 1) findMatchingDay = found;
             }
         }
         if (findMatchingMonth)
             couldBe[i] &= ~ADAY;
         if (findMatchingDay)
             couldBe[i] &= ~AMONTH;
     }
     // First set the year/month/day that have been deduced
     // and reduce the set as we go along to deduce more
     for (int i = 0; i < unknownCount; ++i) {
         int unset = 0;
         for (int j = 0; j < 3; ++j) {
             if (couldBe[j] == ADAY && day == -1) {
                 day = unknown[j];
                 unset |= ADAY;
             } else if (couldBe[j] == AMONTH && month == -1) {
                 month = unknown[j];
                 unset |= AMONTH;
             } else if (couldBe[j] == AYEAR && year == -1) {
                 year = unknown[j];
                 unset |= AYEAR;
             } else {
                 // common case
                 break;
             }
             couldBe[j] &= ~unset;
         }
     }
     // Now fallback to a standardized order to fill in the rest with
     for (int i = 0; i < unknownCount; ++i) {
         if (couldBe[i] & AMONTH && month == -1) month = unknown[i];
         else if (couldBe[i] & ADAY && day == -1) day = unknown[i];
         else if (couldBe[i] & AYEAR && year == -1) year = unknown[i];
     }
 #ifdef PARSEDATESTRINGDEBUG
         qDebug() << "Final set" << year << month << day;
 #endif
     if (year == -1 || month == -1 || day == -1) {
 #ifdef PARSEDATESTRINGDEBUG
         qDebug() << "Parser failure" << year << month << day;
 #endif
         return QDateTime();
     }
     // Y2k behavior
     int y2k = 0;
     if (year < 70)
         y2k = 2000;
     else if (year < 100)
         y2k = 1900;
     QDate date(year + y2k, month, day);
     // When we were given a bad cookie that when parsed
     // set the day to 29 and the year to one that doesn't
     // have the 29th of Feb rather then adding the extra
     // complicated checking earlier just swap here.
     // Example: 29 23 Feb
     if (!date.isValid())
         date = QDate(day + y2k, month, year);
     QDateTime dateTime(date, time, Qt::UTC);
     if (zoneOffset != -1) {
         dateTime = dateTime.addSecs(zoneOffset);
     }
     if (!dateTime.isValid())
         return QDateTime();
     return dateTime;
 }
Variable Documentation
months
const char months[] static
Initial value:
=
    "jan\0"
    "feb\0"
    "mar\0"
    "apr\0"
    "may\0"
    "jun\0"
    "jul\0"
    "aug\0"
    "sep\0"
    "oct\0"
    "nov\0"
    "dec\0"
    "\0"
Definition at line 567 of file qnetworkcookie.cpp.
Referenced by QDate::isNull(), and parseDateString().
zoneOffsets
int zoneOffsets[] = {-8, -8, -7, -7, -6, -6, -5, -5, -4, -3, 0, 0, 0, 1, 2, 9 } static
Definition at line 565 of file qnetworkcookie.cpp.
Referenced by parseDateString().
zones
const char zones[] static
Initial value:
=
    "pst\0"
    "pdt\0"
    "mst\0"
    "mdt\0"
    "cst\0"
    "cdt\0"
    "est\0"
    "edt\0"
    "ast\0"
    "nst\0"
    "gmt\0"
    "utc\0"
    "bst\0"
    "met\0"
    "eet\0"
    "jst\0"
    "\0"
Definition at line 547 of file qnetworkcookie.cpp.
Referenced by parseDateString().