Qt 4.8: /src/network/kernel/qnetworkinterface_unix.cpp File Reference
qnetworkinterface_unix.cpp File Reference
#include "qset.h"
#include "qnetworkinterface.h"
#include "qnetworkinterface_p.h"
#include "qalgorithms.h"
#include "private/qnet_unix_p.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <net/if.h>
#include <ifaddrs.h>
#include <qplatformdefs.h>
#include <features.h>
Macros
#define IP_MULTICAST
Functions
static QHostAddress addressFromSockaddr (sockaddr *sa)
static QNetworkInterface::InterfaceFlags convertFlags (uint rawFlags)
static QList< QNetworkInterfacePrivate * > createInterfaces (ifaddrs *rawList)
static QList< QNetworkInterfacePrivate * > interfaceListing ()
Macro Definition Documentation
IP_MULTICAST
#define IP_MULTICAST
Definition at line 50 of file qnetworkinterface_unix.cpp.
Function Documentation
addressFromSockaddr()
static QHostAddress addressFromSockaddr (sockaddr * sa) static
Definition at line 75 of file qnetworkinterface_unix.cpp.
Referenced by convertFlags(), and interfaceListing().
 {
     QHostAddress address;
     if (!sa)
         return address;
     if (sa->sa_family == AF_INET)
         address.setAddress(htonl(((sockaddr_in *)sa)->sin_addr.s_addr));
 #ifndef QT_NO_IPV6
     else if (sa->sa_family == AF_INET6) {
         address.setAddress(((sockaddr_in6 *)sa)->sin6_addr.s6_addr);
         int scope = ((sockaddr_in6 *)sa)->sin6_scope_id;
         if (scope) {
 #ifndef QT_NO_IPV6IFNAME
             char scopeid[IFNAMSIZ];
             if (::if_indextoname(scope, scopeid)) {
                 address.setScopeId(QLatin1String(scopeid));
             } else
 #endif
                 address.setScopeId(QString::number(scope));
         }
     }
 #endif
     return address;
 }
convertFlags()
static QNetworkInterface::InterfaceFlags convertFlags (uint rawFlags) static
Definition at line 102 of file qnetworkinterface_unix.cpp.
Referenced by createInterfaces().
 {
     QNetworkInterface::InterfaceFlags flags = 0;
     flags |= (rawFlags & IFF_UP) ? QNetworkInterface::IsUp : QNetworkInterface::InterfaceFlag(0);
     flags |= (rawFlags & IFF_RUNNING) ? QNetworkInterface::IsRunning : QNetworkInterface::InterfaceFlag(0);
     flags |= (rawFlags & IFF_BROADCAST) ? QNetworkInterface::CanBroadcast : QNetworkInterface::InterfaceFlag(0);
     flags |= (rawFlags & IFF_LOOPBACK) ? QNetworkInterface::IsLoopBack : QNetworkInterface::InterfaceFlag(0);
 #ifdef IFF_POINTOPOINT //cygwin doesn't define IFF_POINTOPOINT
     flags |= (rawFlags & IFF_POINTOPOINT) ? QNetworkInterface::IsPointToPoint : QNetworkInterface::InterfaceFlag(0);
 #endif
 #ifdef IFF_MULTICAST
     flags |= (rawFlags & IFF_MULTICAST) ? QNetworkInterface::CanMulticast : QNetworkInterface::InterfaceFlag(0);
 #endif
     return flags;
 }
createInterfaces()
static QList<QNetworkInterfacePrivate *> createInterfaces (ifaddrs * rawList) static
Definition at line 370 of file qnetworkinterface_unix.cpp.
Referenced by convertFlags(), and interfaceListing().
 {
     QList<QNetworkInterfacePrivate *> interfaces;
     // make sure there's one entry for each interface
     for (ifaddrs *ptr = rawList; ptr; ptr = ptr->ifa_next) {
         // Get the interface index
         int ifindex = if_nametoindex(ptr->ifa_name);
         QList<QNetworkInterfacePrivate *>::Iterator if_it = interfaces.begin();
         for ( ; if_it != interfaces.end(); ++if_it)
             if ((*if_it)->index == ifindex)
                 // this one has been added already
                 break;
         if (if_it == interfaces.end()) {
             // none found, create
             QNetworkInterfacePrivate *iface = new QNetworkInterfacePrivate;
             interfaces << iface;
             iface->index = ifindex;
             iface->name = QString::fromLatin1(ptr->ifa_name);
             iface->flags = convertFlags(ptr->ifa_flags);
         }
     }
     return interfaces;
 }
interfaceListing()
static QList<QNetworkInterfacePrivate *> interfaceListing () static
Definition at line 402 of file qnetworkinterface_unix.cpp.
Referenced by convertFlags(), and QNetworkInterfaceManager::scan().
 {
     QList<QNetworkInterfacePrivate *> interfaces;
     int socket;
     if ((socket = qt_safe_socket(AF_INET, SOCK_STREAM, IPPROTO_IP)) == -1)
         return interfaces;      // error
     ifaddrs *interfaceListing;
     if (getifaddrs(&interfaceListing) == -1) {
         // error
         ::close(socket);
         return interfaces;
     }
     interfaces = createInterfaces(interfaceListing);
     for (ifaddrs *ptr = interfaceListing; ptr; ptr = ptr->ifa_next) {
         // Get the interface index
         int ifindex = if_nametoindex(ptr->ifa_name);
         QNetworkInterfacePrivate *iface = 0;
         QList<QNetworkInterfacePrivate *>::Iterator if_it = interfaces.begin();
         for ( ; if_it != interfaces.end(); ++if_it)
             if ((*if_it)->index == ifindex) {
                 // found this interface already
                 iface = *if_it;
                 break;
             }
         if (!iface) {
             // skip all non-IP interfaces
             continue;
         }
         QNetworkAddressEntry entry;
         entry.setIp(addressFromSockaddr(ptr->ifa_addr));
         if (entry.ip().isNull())
             // could not parse the address
             continue;
         entry.setNetmask(addressFromSockaddr(ptr->ifa_netmask));
         if (iface->flags & QNetworkInterface::CanBroadcast)
             entry.setBroadcast(addressFromSockaddr(ptr->ifa_broadaddr));
         iface->addressEntries << entry;
     }
     freeifaddrs(interfaceListing);
     ::close(socket);
     return interfaces;
 }