Qt 4.8: /src/network/access/qnetworkaccessmanager.cpp File Reference
qnetworkaccessmanager.cpp File Reference
#include "qnetworkaccessmanager.h"
#include "qnetworkaccessmanager_p.h"
#include "qnetworkrequest.h"
#include "qnetworkreply.h"
#include "qnetworkreply_p.h"
#include "qnetworkcookie.h"
#include "qabstractnetworkcache.h"
#include "QtNetwork/qnetworksession.h"
#include "QtNetwork/private/qsharednetworksession_p.h"
#include "qnetworkaccesshttpbackend_p.h"
#include "qnetworkaccessftpbackend_p.h"
#include "qnetworkaccessfilebackend_p.h"
#include "qnetworkaccessdebugpipebackend_p.h"
#include "qnetworkaccesscachebackend_p.h"
#include "qnetworkreplydataimpl_p.h"
#include "qnetworkreplyfileimpl_p.h"
#include "QtCore/qbuffer.h"
#include "QtCore/qurl.h"
#include "QtCore/qvector.h"
#include "QtNetwork/private/qauthenticator_p.h"
#include "QtNetwork/qsslconfiguration.h"
#include "QtNetwork/qnetworkconfigmanager.h"
#include "QtNetwork/qhttpmultipart.h"
#include "qhttpmultipart_p.h"
#include "qthread.h"
#include "moc_qnetworkaccessmanager.cpp"
Functions
static void ensureInitialized ()
Function Documentation
ensureInitialized()
static void ensureInitialized () static
Definition at line 86 of file qnetworkaccessmanager.cpp.
Referenced by QResourcePrivate::ensureChildren(), QScriptValueIterator::hasNext(), QScriptValueIterator::hasPrevious(), QIconLoader::invalidateKey(), QNetworkAccessManager::QNetworkAccessManager(), and QResourcePrivate::~QResourcePrivate().
 {
 #ifndef QT_NO_HTTP
     (void) httpBackend();
 #endif // QT_NO_HTTP
 #ifndef QT_NO_FTP
     (void) ftpBackend();
 #endif
 #ifdef QT_BUILD_INTERNAL
     (void) debugpipeBackend();
 #endif
     // leave this one last since it will query the special QAbstractFileEngines
     (void) fileBackend();
 }