Qt 4.8: /src/gui/dialogs/qnspanelproxy_mac.mm File Reference
qnspanelproxy_mac.mm File Reference
#include <qdialogbuttonbox.h>
#include <private/qt_mac_p.h>
#include <private/qcocoaintrospection_p.h>
#import <AppKit/AppKit.h>
#import <Foundation/Foundation.h>
#import <objc/objc-class.h>
Classes
class QNSPanelProxy
class QNSWindowProxy
Functions
NSButton * macCreateButton (const char *text, NSView *superview)
void macStartInterceptNSPanelCtor ()
void macStartInterceptWindowTitle (QWidget *window)
void macStopInterceptNSPanelCtor ()
void macStopInterceptWindowTitle ()
Variables
static QWidget * currentWindow = 0
Function Documentation
macCreateButton()
NSButton* macCreateButton (const char * text, NSView * superview)
Definition at line 211 of file qnspanelproxy_mac.mm.
Referenced by QFontDialogPrivate::createNSFontPanelDelegate(), and QColorDialogPrivate::openCocoaColorPanel().
 {
     static const NSRect buttonFrameRect = { { 0.0, 0.0 }, { 0.0, 0.0 } };
     NSButton *button = [[NSButton alloc] initWithFrame:buttonFrameRect];
     [button setButtonType:NSMomentaryLightButton];
     [button setBezelStyle:NSRoundedBezelStyle];
     [button setTitle:(NSString*)(CFStringRef)QCFString(QDialogButtonBox::tr(text)
                                                        .remove(QLatin1Char('&')))];
     [[button cell] setFont:[NSFont systemFontOfSize:
             [NSFont systemFontSizeForControlSize:NSRegularControlSize]]];
     [superview addSubview:button];
     return button;
 }
macStartInterceptNSPanelCtor()
void macStartInterceptNSPanelCtor ()
Definition at line 150 of file qnspanelproxy_mac.mm.
Referenced by QColorDialogPrivate::openCocoaColorPanel().
 {
     qt_cocoa_change_implementation(
             [NSPanel class],
             @selector(initWithContentRect:styleMask:backing:defer:),
             [QT_MANGLE_NAMESPACE(QNSPanelProxy) class],
             @selector(initWithContentRect:styleMask:backing:defer:),
             @selector(qt_fakeInitWithContentRect:styleMask:backing:defer:));
     qt_cocoa_change_implementation(
             [NSPanel class],
             @selector(initWithContentRect:styleMask:backing:defer:screen:),
             [QT_MANGLE_NAMESPACE(QNSPanelProxy) class],
             @selector(initWithContentRect:styleMask:backing:defer:screen:),
             @selector(qt_fakeInitWithContentRect:styleMask:backing:defer:screen:));
 }
macStartInterceptWindowTitle()
void macStartInterceptWindowTitle (QWidget * window)
Definition at line 185 of file qnspanelproxy_mac.mm.
Referenced by QPageSetupDialogPrivate::closeCarbonPageLayout(), and QPrintDialogPrivate::closeCarbonPrintPanel().
 {
     currentWindow = window;
     qt_cocoa_change_implementation(
             [NSWindow class],
             @selector(setTitle:),
             [QT_MANGLE_NAMESPACE(QNSWindowProxy) class],
             @selector(setTitle:),
             @selector(qt_fakeSetTitle:));
 }
macStopInterceptNSPanelCtor()
void macStopInterceptNSPanelCtor ()
Definition at line 169 of file qnspanelproxy_mac.mm.
Referenced by QColorDialogPrivate::openCocoaColorPanel().
 {
     qt_cocoa_change_back_implementation(
             [NSPanel class],
             @selector(initWithContentRect:styleMask:backing:defer:screen:),
             @selector(qt_fakeInitWithContentRect:styleMask:backing:defer:screen:));
     qt_cocoa_change_back_implementation(
             [NSPanel class],
             @selector(initWithContentRect:styleMask:backing:defer:),
             @selector(qt_fakeInitWithContentRect:styleMask:backing:defer:));
 }
macStopInterceptWindowTitle()
void macStopInterceptWindowTitle ()
Definition at line 199 of file qnspanelproxy_mac.mm.
Referenced by QPageSetupDialogPrivate::closeCarbonPageLayout(), and QPrintDialogPrivate::closeCarbonPrintPanel().
 {
     currentWindow = 0;
     qt_cocoa_change_back_implementation(
             [NSWindow class],
             @selector(setTitle:),
             @selector(qt_fakeSetTitle:));
 }
Variable Documentation
currentWindow
QWidget* currentWindow = 0 static
Definition at line 51 of file qnspanelproxy_mac.mm.