Qt 4.8: /src/corelib/global/qnumeric.h File Reference
qnumeric.h File Reference
#include <QtCore/qglobal.h>
Macros
#define Q_INFINITY (QT_PREPEND_NAMESPACE(qInf)())
#define Q_QNAN (QT_PREPEND_NAMESPACE(qQNaN)())
#define Q_SNAN (QT_PREPEND_NAMESPACE(qSNaN)())
Functions
Q_CORE_EXPORT double qInf ()
Returns the bit pattern for an infinite number as a double.
Q_CORE_EXPORT bool qIsFinite (double d)
Returns true if the double {d} is a finite number.
Q_CORE_EXPORT bool qIsFinite (float f)
Returns true if the float {f} is a finite number.
Q_CORE_EXPORT bool qIsInf (double d)
Returns true if the double {d} is equivalent to infinity.
Q_CORE_EXPORT bool qIsInf (float f)
Returns true if the float {f} is equivalent to infinity.
Q_CORE_EXPORT bool qIsNaN (double d)
Returns true if the double {d} is not a number (NaN).
Q_CORE_EXPORT bool qIsNaN (float f)
Returns true if the float {f} is not a number (NaN).
Q_CORE_EXPORT double qQNaN ()
Returns the bit pattern of a quiet NaN as a double.
Q_CORE_EXPORT double qSNaN ()
Returns the bit pattern of a signalling NaN as a double.
Macro Definition Documentation
Q_INFINITY
#define Q_INFINITY (QT_PREPEND_NAMESPACE(qInf)())
Definition at line 63 of file qnumeric.h.
Q_QNAN
#define Q_QNAN (QT_PREPEND_NAMESPACE(qQNaN)())
Definition at line 65 of file qnumeric.h.
Q_SNAN
#define Q_SNAN (QT_PREPEND_NAMESPACE(qSNaN)())
Definition at line 64 of file qnumeric.h.
Function Documentation
qInf()
Q_CORE_EXPORT double qInf ()
Returns the bit pattern for an infinite number as a double.
Definition at line 90 of file qnumeric.cpp.
Referenced by QTextStreamPrivate::getReal(), QDeclarativeJS::integerFromString(), and QScript::integerFromString().
 { return qt_inf(); }
qIsFinite() [1/2]
Q_CORE_EXPORT bool qIsFinite (double d)
Returns true if the double {d} is a finite number.
Definition at line 60 of file qnumeric.cpp.
 { return qt_is_finite(d); }
qIsFinite() [2/2]
Q_CORE_EXPORT bool qIsFinite (float f)
Returns true if the float {f} is a finite number.
Definition at line 75 of file qnumeric.cpp.
 { return qt_is_finite(f); }
qIsInf() [1/2]
Q_CORE_EXPORT bool qIsInf (double d)
Returns true if the double {d} is equivalent to infinity.
Definition at line 50 of file qnumeric.cpp.
Referenced by QPatternist::DurationNumericMathematician::calculate(), QPatternist::AbstractFloat< isDouble >::isEqual(), QPatternist::AbstractFloat< isDouble >::isInf(), QPatternist::Numeric::roundFloat(), QPatternist::AbstractFloat< isDouble >::stringValue(), QScript::ToInt32(), QScript::ToInteger(), QScript::ToUInt16(), and QScript::ToUInt32().
 { return qt_is_inf(d); }
qIsInf() [2/2]
Q_CORE_EXPORT bool qIsInf (float f)
Returns true if the float {f} is equivalent to infinity.
Definition at line 65 of file qnumeric.cpp.
 { return qt_is_inf(f); }
qIsNaN() [1/2]
Q_CORE_EXPORT bool qIsNaN (double d)
Returns true if the double {d} is not a number (NaN).
Definition at line 55 of file qnumeric.cpp.
Referenced by _q_equal(), QGraphicsRotation::applyTo(), QPatternist::DurationNumericMathematician::calculate(), QPatternist::NumericToBooleanCaster::castFrom(), QPatternist::AbstractFloatSortComparator< t_op >::compare(), QDeclarativePath::createPointCache(), QPatternist::AbstractFloat< isDouble >::evaluateEBV(), QPatternist::SubstringFN::evaluateSingleton(), QTransform::fromScale(), QTransform::fromTranslate(), QPatternist::AbstractFloat< isDouble >::isNaN(), QPatternist::loadPattern(), QScript::MsToDateTime(), qt_real_to_string(), QTransform::rotate(), QTransform::rotateRadians(), QPatternist::Numeric::roundFloat(), QTransform::scale(), QGradient::setColorAt(), QGraphicsWidgetPrivate::setHeight(), QDeclarativeItemPrivate::setHeight(), QGraphicsWidgetPrivate::setWidth(), QDeclarativeItemPrivate::setWidth(), QGraphicsItem::setX(), QGraphicsItem::setY(), QTransform::shear(), QPatternist::AbstractFloat< isDouble >::stringValue(), QScript::ToBool(), QScript::ToInt32(), QScript::ToInteger(), QScript::ToUInt16(), QScript::ToUInt32(), and QTransform::translate().
 { return qt_is_nan(d); }
qIsNaN() [2/2]
Q_CORE_EXPORT bool qIsNaN (float f)
Returns true if the float {f} is not a number (NaN).
Definition at line 70 of file qnumeric.cpp.
 { return qt_is_nan(f); }
qQNaN()
Q_CORE_EXPORT double qQNaN ()
Returns the bit pattern of a quiet NaN as a double.
Definition at line 85 of file qnumeric.cpp.
 { return qt_qnan(); }
qSNaN()
Q_CORE_EXPORT double qSNaN ()
Returns the bit pattern of a signalling NaN as a double.
Definition at line 80 of file qnumeric.cpp.
Referenced by QScript::DateTimeToMs(), QTextStreamPrivate::getReal(), QDeclarativeJS::integerFromString(), and QScript::integerFromString().
 { return qt_snan(); }