Qt 4.8: /src/corelib/kernel/qobject.h File Reference
qobject.h File Reference
#include <QtCore/qobjectdefs.h>
#include <QtCore/qstring.h>
#include <QtCore/qbytearray.h>
#include <QtCore/qlist.h>
#include <QtCore/qscopedpointer.h>
Classes
class QObject
The QObject class is the base class of all Qt objects.
class QObjectData
class QObjectUserData
Macros
#define Q_DECLARE_INTERFACE(IFace, IId)
Typedefs
typedef QList< QObject * > QObjectList
Functions
Q_CORE_EXPORT QDebug operator<< (QDebug, const QObject *)
T qFindChild (const QObject *o, const QString &name=QString())
QList< T > qFindChildren (const QObject *oobj, const QString &name=QString())
QList< T > qFindChildren (const QObject *o, const QRegExp &re)
template<class T >
T qobject_cast (QObject *object)
template<class T >
T qobject_cast (const QObject *object)
template<class T >
const char * qobject_interface_iid ()
Q_CORE_EXPORT QObject * qt_qFindChild_helper (const QObject *parent, const QString &name, const QMetaObject &mo)
Q_CORE_EXPORT void qt_qFindChildren_helper (const QObject *parent, const QString &name, const QRegExp *re, const QMetaObject &mo, QList< void *> *list)
Macro Definition Documentation
Q_DECLARE_INTERFACE
#define Q_DECLARE_INTERFACE (IFace, IId)
Value:
template <> inline const char *qobject_interface_iid<IFace *>() \
    { return IId; } \
    template <> inline IFace *qobject_cast<IFace *>(QObject *object) \
    { return reinterpret_cast<IFace *>((object ? object->qt_metacast(IId) : 0)); } \
    template <> inline IFace *qobject_cast<IFace *>(const QObject *object) \
    { return reinterpret_cast<IFace *>((object ? const_cast<QObject *>(object)->qt_metacast(IId) : 0)); }
Definition at line 397 of file qobject.h.
Referenced by QDeclarativeDebugServerConnection::~QDeclarativeDebugServerConnection(), QDeclarativeExtensionInterface::~QDeclarativeExtensionInterface(), QDeclarativeInspectorInterface::~QDeclarativeInspectorInterface(), QFactoryInterface::~QFactoryInterface(), and QTextObjectInterface::~QTextObjectInterface().
Typedef Documentation
QObjectList
typedef QList<QObject*> QObjectList related
Definition at line 75 of file qobject.h.
Function Documentation
operator<<()
Q_CORE_EXPORT QDebug operator<< (QDebug , const QObject *)
Definition at line 4030 of file qobject.cpp.
{
 #ifndef Q_BROKEN_DEBUG_STREAM
     if (!o)
         return dbg << "QObject(0x0) ";
     dbg.nospace() << o->metaObject()->className() << '(' << (void *)o;
     if (!o->objectName().isEmpty())
         dbg << ", name = " << o->objectName();
     dbg << ')';
     return dbg.space();
 #else
     qWarning("This compiler doesn't support streaming QObject to QDebug");
     return dbg;
     Q_UNUSED(o);
 #endif
 }
qFindChild()
QT_DEPRECATED T qFindChild (const QObject * o, const QString & name = QString()) inline
Definition at line 355 of file qobject.h.
 { return o->findChild<T>(name); }
qFindChildren() [1/2]
QT_DEPRECATED QList< T > qFindChildren (const QObject * oobj, const QString & name = QString()) inline
Definition at line 359 of file qobject.h.
 {
     return o->findChildren<T>(name);
 }
qFindChildren() [2/2]
QT_DEPRECATED QList< T > qFindChildren (const QObject * o, const QRegExp & re) inline
Definition at line 366 of file qobject.h.
 {
     return o->findChildren<T>(re);
 }
qobject_cast() [1/2]
template<class T > T qobject_cast (QObject * object) related
Definition at line 375 of file qobject.h.
Referenced by QActionGroupPrivate::_q_actionChanged(), QActionGroupPrivate::_q_actionHovered(), QActionGroupPrivate::_q_actionTriggered(), QPlainTextEditPrivate::_q_adjustScrollbars(), QStateMachinePrivate::_q_animationFinished(), QMdiAreaPrivate::_q_deactivateAllWindows(), QMdiSubWindowPrivate::_q_enterInteractiveMode(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointEnableRequest(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointToggleRequest(), QScriptDebuggerLocalsWidgetPrivate::_q_onCompletionTaskFinished(), QScriptDebuggerConsoleWidgetPrivate::_q_onCompletionTaskFinished(), QMdiAreaPrivate::_q_processWindowStateChanged(), QFileDialogPrivate::_q_showHeader(), QTextCursorPrivate::aboutToRemoveCell(), QAccessibleAbstractSpinBox::abstractSpinBox(), QAccessibleButton::actionText(), QTextCursorPrivate::adjustCursor(), QDockAreaLayoutInfo::apply(), QToolBarAreaLayout::apply(), QStateMachinePrivate::applyProperties(), QStyleSheetStyleSelector::attribute(), QAudioDeviceFactory::audioDeviceInfo(), QAudioDeviceFactory::availableDevices(), QAccessibleButton::button(), QTextDocumentPrivate::changeObjectFormat(), QAccessibleTree::childAt(), QAccessibleTree::childCount(), childWidgets(), QAccessibleComboBox::comboBox(), QTextCursorPrivate::complexSelectionTable(), QShortcutMap::correctContext(), QShortcutMap::correctGraphicsWidgetContext(), QShortcutMap::correctWidgetContext(), QDeclarativeGridViewPrivate::createComponentItem(), QAudioDeviceFactory::createInputDevice(), QAudioDeviceFactory::createOutputDevice(), createReadHandlerHelper(), QTextTablePrivate::createTable(), QGLGraphicsSystem::createWindowSurface(), QTextCursor::currentList(), QTextCursor::currentTable(), QAudioDeviceFactory::defaultInputDevice(), QAudioDeviceFactory::defaultOutputDevice(), QWidget::destroy(), QAccessibleButton::doAction(), dockedGeometry(), QDockWidgetItem::dockWidgetLayout(), QAccessibleTitleBar::dockWidgetLayout(), QTextDocumentLayoutPrivate::drawFrame(), QMdiSubWindowPrivate::drawTitleBarWhenMaximized(), QDockWidgetPrivate::endDrag(), QUIKitSoftwareInputHandler::eventFilter(), QWindowsStyle::eventFilter(), QZipWriter::exists(), QZipReader::exists(), QTextDocumentWriter::fileName(), QImageWriter::fileName(), QImageReader::fileName(), QTextStreamPrivate::fillReadBuffer(), findMenubarForWindow(), QTextStreamPrivate::flushWriteBuffer(), QGraphicsItemPrivate::genericMapFromScene(), QScriptDebuggerLocalsModelPrivate::get(), getNamedAttribute(), QScriptDebuggerScriptedConsoleCommandJob::handleResponse(), handleSplitterContentsAttribute(), handleSplittersAttribute(), QAccessibleHeader::header(), QAInterface::hiObject(), QAccessibleDisplay::imagePosition(), QAccessibleDisplay::imageSize(), QAccessibleTree::indexFromLogical(), QAccessibleTree::indexOfChild(), QAccessibleStackedWidget::indexOfChild(), QAccessibleToolBox::indexOfChild(), QDockWidgetPrivate::initDrag(), QToolBarPrivate::initDrag(), QStateMachinePrivate::initializeAnimation(), initializeDb(), QDialogButtonBoxPrivate::initLayout(), QDockWidget::initStyleOption(), QTextDocumentPrivate::insert_block(), QTextDocumentPrivate::insert_string(), QTreeWidgetItem::insertChildren(), QTextDocumentPrivate::insertFrame(), QMdiAreaPrivate::internalRaise(), QDockWidgetPrivate::isAnimating(), isEmptyBlockAfterTable(), isEmptyBlockBeforeTable(), isItemView(), isLineSeparatorBlockAfterTable(), QScriptDebuggerLocalsModelPrivate::isTopLevelNode(), EGLNullWSWindowSurface::isValid(), QGraphicsScenePrivate::itemsAtPosition(), QAccessibleItemView::itemView(), QTextDocumentLayoutPrivate::layoutFlow(), QTabBarPrivate::layoutTabs(), QAccessibleLineEdit::lineEdit(), QListWidgetPrivate::listModel(), QSvgIOHandlerPrivate::load(), loadSingleEngine(), QAccessibleMainWindow::mainWindow(), QGestureEvent::mapToGraphicsScene(), mdiAreaNavigate(), QAccessibleMenu::menu(), QAccessibleMenuBar::menuBar(), ModelIndexIterator::ModelIndexIterator(), QDockWidgetPrivate::mouseDoubleClickEvent(), QDockWidgetPrivate::mouseMoveEvent(), QToolBarPrivate::mouseMoveEvent(), QDockWidgetPrivate::mousePressEvent(), QTextDocumentPrivate::move(), QTextCursorPrivate::movePosition(), QVNCIntegration::moveToScreen(), my_jpeg_source_mgr::my_jpeg_source_mgr(), QAccessibleDisplay::navigate(), QAccessibleMdiSubWindow::navigate(), QPdfBaseEngine::newPage(), QAccessibleItemView::object(), QLayout::parentWidget(), QAccessibleProgressBar::progressBar(), q_createNativeChildrenAndSetParent(), QOpenKODEWindow::QOpenKODEWindow(), QRenderRule::QRenderRule(), qt_GetMessageHook(), qt_guiPlatformMenuBarFactory(), qt_mac_unregister_widget(), qt_mainwindow_layout(), QAxClientSite::qt_metacall(), qt_x11_recreateNativeWidgetsRecursive(), QTestLiteStaticInfoPrivate::QTestLiteStaticInfoPrivate(), QTreeWidgetItem::QTreeWidgetItem(), QTreeWidgetItemIterator::QTreeWidgetItemIterator(), QAccessible::queryAccessibleInterface(), QUnixPrintWidgetPrivate::QUnixPrintWidgetPrivate(), QVNCIntegration::QVNCIntegration(), QAccessibleDockWidget::rect(), QAccessibleTitleBar::rect(), QAccessibleDisplay::relationTo(), QTextDocumentPrivate::remove_block(), QTextDocumentPrivate::remove_string(), QMdiSubWindowPrivate::removeButtonsFromMenuBar(), QAccessibleDisplay::role(), QTextDocumentPrivate::rootFrame(), QTestAccessibility::rootObjectHandler(), QAccessibleTree::rowCount(), QAccessibleTable2Cell::rowIndex(), QTextDocumentPrivate::scan_frames(), QAccessibleScrollBar::scrollBar(), QWidgetPrivate::scrollChildren(), QTextCursorPrivate::selectedTableCells(), QTextDocumentPrivate::setBlockFormat(), QTreeWidgetItem::setData(), QOpenKODEWindow::setGeometry(), QRasterWindowSurface::setGeometry(), QInputDialogPrivate::setInputWidget(), QMdiSubWindowPrivate::setMaximizeMode(), QWidgetPrivate::setModal_sys(), QLocalSocket::setSocketDescriptor(), QDockWidgetPrivate::setWindowState(), QFileDialogComboBox::showPopup(), showToolTip(), QAccessibleSlider::slider(), QTreeWidgetItemPrivate::sortChildren(), QTreeWidgetItem::sortChildren(), QAbstractTransitionPrivate::sourceState(), QAccessibleSpinBox::spinBox(), QHttpNetworkReply::sslConfiguration(), QScriptDebuggerScriptedConsoleCommandJob::start(), QToolBarPrivate::startDrag(), QAccessibleButton::state(), QAccessibleTable2Cell::state(), QMdiAreaTabBar::subWindowFromIndex(), QMdiAreaPrivate::subWindowList(), QImageWriter::supportedImageFormats(), QImageReader::supportedImageFormats(), QAccessibleTabBar::tabBar(), QTreeWidgetItem::takeChild(), QTreeWidgetItem::takeChildren(), IsWindowAndNotDrawerOrSheetTest::test(), QAccessibleButton::text(), QAccessibleDisplay::text(), QAccessibleToolButton::toolButton(), QKeyMapperPrivate::translateKeyEvent(), QTextDocumentPrivate::undoRedo(), QDockWidgetPrivate::unplug(), QDockWidgetPrivate::updateButtons(), QWidgetBackingStore::updateLists(), QDockAreaLayoutInfo::updateTabBar(), QScriptDebuggerLocalsItemDelegate::validateInput(), QAccessibleTable2::view(), QAxAggregated::widget(), QAccessibleWidget::widget(), QLayout::widgetEvent(), QAccessibleWidgetStack::widgetStack(), QAxScriptSite::window(), QTextOdfWriter::writeFrame(), QSQLiteResult::~QSQLiteResult(), and QTreeWidgetItem::~QTreeWidgetItem().
 {
 #if !defined(QT_NO_QOBJECT_CHECK)
     reinterpret_cast<T>(object)->qt_check_for_QOBJECT_macro(*reinterpret_cast<T>(object));
 #endif
     return static_cast<T>(reinterpret_cast<T>(object)->staticMetaObject.cast(object));
 }
qobject_cast() [2/2]
template<class T > T qobject_cast (const QObject * object) inline
Definition at line 384 of file qobject.h.
 {
 #if !defined(QT_NO_QOBJECT_CHECK)
     reinterpret_cast<T>(object)->qt_check_for_QOBJECT_macro(*reinterpret_cast<T>(const_cast<QObject *>(object)));
 #endif
     return static_cast<T>(reinterpret_cast<T>(object)->staticMetaObject.cast(object));
 }
qobject_interface_iid()
template<class T > const char* qobject_interface_iid () inline
Definition at line 393 of file qobject.h.
 { return 0; }
qt_qFindChild_helper()
Q_CORE_EXPORT QObject* qt_qFindChild_helper (const QObject * parent, const QString & name, const QMetaObject & mo)
Warning
This function is not part of the public interface.
Definition at line 1924 of file qobject.cpp.
Referenced by QObject::findChild(), and qt_qFindChild_helper().
 {
     if (!parent)
         return 0;
     const QObjectList &children = parent->children();
     QObject *obj;
     int i;
     for (i = 0; i < children.size(); ++i) {
         obj = children.at(i);
         if (mo.cast(obj) && (name.isNull() || obj->objectName() == name))
             return obj;
     }
     for (i = 0; i < children.size(); ++i) {
         obj = qt_qFindChild_helper(children.at(i), name, mo);
         if (obj)
             return obj;
     }
     return 0;
 }
qt_qFindChildren_helper()
Q_CORE_EXPORT void qt_qFindChildren_helper (const QObject * parent, const QString & name, const QRegExp * re, const QMetaObject & mo, QList< void *> * list)
Warning
This function is not part of the public interface.
Definition at line 1900 of file qobject.cpp.
Referenced by QObject::findChildren(), and qt_qFindChildren_helper().
 {
     if (!parent || !list)
         return;
     const QObjectList &children = parent->children();
     QObject *obj;
     for (int i = 0; i < children.size(); ++i) {
         obj = children.at(i);
         if (mo.cast(obj)) {
             if (re) {
                 if (re->indexIn(obj->objectName()) != -1)
                     list->append(obj);
             } else {
                 if (name.isNull() || obj->objectName() == name)
                     list->append(obj);
             }
         }
         qt_qFindChildren_helper(obj, name, re, mo, list);
     }
 }