Qt 4.8: /src/corelib/kernel/qobject.cpp File Reference
qobject.cpp File Reference
#include "qobject.h"
#include "qobject_p.h"
#include "qmetaobject_p.h"
#include "qabstracteventdispatcher.h"
#include "qcoreapplication.h"
#include "qcoreapplication_p.h"
#include "qvariant.h"
#include "qmetaobject.h"
#include <qregexp.h>
#include <qthread.h>
#include <private/qthread_p.h>
#include <qdebug.h>
#include <qhash.h>
#include <qpair.h>
#include <qset.h>
#include <qsemaphore.h>
#include <qsharedpointer.h>
#include <private/qorderedmutexlocker_p.h>
#include <private/qmutexpool_p.h>
#include <new>
#include <ctype.h>
#include <limits.h>
#include "moc_qobject.cpp"
Classes
class QObjectConnectionListVector
Typedefs
typedef QMultiHash< QObject *, QObject ** > GuardHash
Functions
static void check_and_warn_compat (const QMetaObject *sender, const QMetaMethod &signal, const QMetaObject *receiver, const QMetaMethod &method)
static bool check_method_code (int code, const QObject *object, const char *method, const char *func)
static bool check_parent_thread (QObject *parent, QThreadData *parentThreadData, QThreadData *currentThreadData)
static bool check_signal_macro (const QObject *sender, const char *signal, const char *func, const char *op)
static void computeOffsets (const QMetaObject *metaobject, int *signalOffset, int *methodOffset)
static void dumpRecursive (int level, QObject *object)
static void err_info_about_objects (const char *func, const QObject *sender, const QObject *receiver)
static void err_method_notfound (const QObject *object, const char *method, const char *func)
static int extract_code (const char *member)
static const char * extract_location (const char *member)
static int methodIndexToSignalIndex (const QMetaObject *metaObject, int signal_index)
QDebug operator<< (QDebug dbg, const QObject *o)
void qDeleteInEventHandler (QObject *o)
const char * qFlagLocation (const char *method)
Q_CORE_EXPORT void qt_addObject (QObject *)
QObject * qt_qFindChild_helper (const QObject *parent, const QString &name, const QMetaObject &mo)
void qt_qFindChildren_helper (const QObject *parent, const QString &name, const QRegExp *re, const QMetaObject &mo, QList< void *> *list)
Q_CORE_EXPORT void qt_removeObject (QObject *)
static void queued_activate (QObject *sender, int signal, QObjectPrivate::Connection *c, void **argv)
static int * queuedConnectionTypes (const QList< QByteArray > &typeNames)
static QMutex * signalSlotLock (const QObject *o)
Variables
static int DIRECT_CONNECTION_ONLY = 0
static QBasicAtomicInt objectCount = Q_BASIC_ATOMIC_INITIALIZER(0)
static QBasicAtomicPointer< QMutexPool > signalSlotMutexes = Q_BASIC_ATOMIC_INITIALIZER(0)
Typedef Documentation
GuardHash
typedef QMultiHash<QObject *, QObject **> GuardHash
Definition at line 384 of file qobject.cpp.
Function Documentation
check_and_warn_compat()
static void check_and_warn_compat (const QMetaObject * sender, const QMetaMethod & signal, const QMetaObject * receiver, const QMetaMethod & method) inline static
Definition at line 2497 of file qobject.cpp.
Referenced by QObject::connect().
 {
     if (signal.attributes() & QMetaMethod::Compatibility) {
         if (!(method.attributes() & QMetaMethod::Compatibility))
             qWarning("QObject::connect: Connecting from COMPAT signal (%s::%s)",
                      sender->className(), signal.signature());
     } else if ((method.attributes() & QMetaMethod::Compatibility) &&
                method.methodType() == QMetaMethod::Signal) {
         qWarning("QObject::connect: Connecting from %s::%s to COMPAT slot (%s::%s)",
                  sender->className(), signal.signature(),
                  receiver->className(), method.signature());
     }
 }
check_method_code()
static bool check_method_code (int code, const QObject * object, const char * method, const char * func) static
Definition at line 2261 of file qobject.cpp.
Referenced by QObject::connect(), and QObject::disconnect().
 {
     if (code != QSLOT_CODE && code != QSIGNAL_CODE) {
         qWarning("Object::%s: Use the SLOT or SIGNAL macro to "
                  "%s %s::%s", func, func, object->metaObject()->className(), method);
         return false;
     }
     return true;
 }
check_parent_thread()
static bool check_parent_thread (QObject * parent, QThreadData * parentThreadData, QThreadData * currentThreadData) static
Definition at line 718 of file qobject.cpp.
Referenced by QObject::QObject().
 {
     if (parent && parentThreadData != currentThreadData) {
         QThread *parentThread = parentThreadData->thread;
         QThread *currentThread = currentThreadData->thread;
         qWarning("QObject: Cannot create children for a parent that is in a different thread.\n"
                  "(Parent is %s(%p), parent's thread is %s(%p), current thread is %s(%p)",
                  parent->metaObject()->className(),
                  parent,
                  parentThread ? parentThread->metaObject()->className() : "QThread",
                  parentThread,
                  currentThread ? currentThread->metaObject()->className() : "QThread",
                  currentThread);
         return false;
     }
     return true;
 }
check_signal_macro()
static bool check_signal_macro (const QObject * sender, const char * signal, const char * func, const char * op) static
Definition at line 2245 of file qobject.cpp.
Referenced by QObject::connect(), QObject::disconnect(), and QObject::receivers().
 {
     int sigcode = extract_code(signal);
     if (sigcode != QSIGNAL_CODE) {
         if (sigcode == QSLOT_CODE)
             qWarning("Object::%s: Attempt to %s non-signal %s::%s",
                      func, op, sender->metaObject()->className(), signal+1);
         else
             qWarning("Object::%s: Use the SIGNAL macro to %s %s::%s",
                      func, op, sender->metaObject()->className(), signal);
         return false;
     }
     return true;
 }
computeOffsets()
static void computeOffsets (const QMetaObject * metaobject, int * signalOffset, int * methodOffset) static
Warning
This function is not part of the public interface. For a given metaobject, compute the signal offset, and the method offset (including signals)
Definition at line 225 of file qobject.cpp.
Referenced by QMetaObject::activate(), QObject::connect(), QMetaObject::connectSlotsByName(), QObject::disconnect(), QObject::dumpObjectInfo(), QMetaObjectPrivate::memberIndexes(), methodIndexToSignalIndex(), and QObjectPrivate::signalIndex().
 {
     *signalOffset = *methodOffset = 0;
     const QMetaObject *m = metaobject->d.superdata;
     while (m) {
         const QMetaObjectPrivate *d = QMetaObjectPrivate::get(m);
         *methodOffset += d->methodCount;
         *signalOffset += (d->revision >= 4) ? d->signalCount : d->methodCount;
         /*Before Qt 4.6 (revision 4), the signalCount information was not generated by moc.
            so for compatibility we consider all the method as slot for old moc output*/
         m = m->d.superdata;
     }
 }
dumpRecursive()
static void dumpRecursive (int level, QObject * object) static
Definition at line 3854 of file qobject.cpp.
Referenced by QObject::dumpObjectTree().
 {
 #if defined(QT_DEBUG)
     if (object) {
         QByteArray buf;
         buf.fill(' ', level / 2 * 8);
         if (level % 2)
             buf += "    ";
         QString name = object->objectName();
         QString flags = QLatin1String("");
 #if 0
         if (qApp->focusWidget() == object)
             flags += 'F';
         if (object->isWidgetType()) {
             QWidget * w = (QWidget *)object;
             if (w->isVisible()) {
                 QString t("<%1,%2,%3,%4>");
                 flags += t.arg(w->x()).arg(w->y()).arg(w->width()).arg(w->height());
             } else {
                 flags += 'I';
             }
         }
 #endif
         qDebug("%s%s::%s %s", (const char*)buf, object->metaObject()->className(), name.toLocal8Bit().data(),
                flags.toLatin1().data());
         QObjectList children = object->children();
         if (!children.isEmpty()) {
             for (int i = 0; i < children.size(); ++i)
                 dumpRecursive(level+1, children.at(i));
         }
     }
 #else
     Q_UNUSED(level)
         Q_UNUSED(object)
 #endif
 }
err_info_about_objects()
static void err_info_about_objects (const char * func, const QObject * sender, const QObject * receiver) static
Definition at line 2293 of file qobject.cpp.
Referenced by QObject::connect(), and QObject::disconnect().
 {
     QString a = sender ? sender->objectName() : QString();
     QString b = receiver ? receiver->objectName() : QString();
     if (!a.isEmpty())
         qWarning("Object::%s:  (sender name:   '%s')", func, a.toLocal8Bit().data());
     if (!b.isEmpty())
         qWarning("Object::%s:  (receiver name: '%s')", func, b.toLocal8Bit().data());
 }
err_method_notfound()
static void err_method_notfound (const QObject * object, const char * method, const char * func) static
Definition at line 2272 of file qobject.cpp.
Referenced by QObject::connect(), QObject::disconnect(), and QObject::receivers().
 {
     const char *type = "method";
     switch (extract_code(method)) {
         case QSLOT_CODE:   type = "slot";   break;
         case QSIGNAL_CODE: type = "signal"; break;
     }
     const char *loc = extract_location(method);
     if (strchr(method,')') == 0)                // common typing mistake
         qWarning("Object::%s: Parentheses expected, %s %s::%s%s%s",
                  func, type, object->metaObject()->className(), method+1,
                  loc ? " in ": "", loc ? loc : "");
     else
         qWarning("Object::%s: No such %s %s::%s%s%s",
                  func, type, object->metaObject()->className(), method+1,
                  loc ? " in ": "", loc ? loc : "");
 }
extract_code()
static int extract_code (const char * member) static
Definition at line 2228 of file qobject.cpp.
Referenced by check_signal_macro(), QObject::connect(), QObject::disconnect(), and err_method_notfound().
 {
     // extract code, ensure QMETHOD_CODE <= code <= QSIGNAL_CODE
     return (((int)(*member) - '0') & 0x3);
 }
extract_location()
static const char* extract_location (const char * member) static
Definition at line 2234 of file qobject.cpp.
Referenced by err_method_notfound().
 {
     if (QThreadData::current()->flaggedSignatures.contains(member)) {
         // signature includes location information after the first null-terminator
         const char *location = member + qstrlen(member) + 1;
         if (*location != '\0')
             return location;
     }
     return 0;
 }
methodIndexToSignalIndex()
static int methodIndexToSignalIndex (const QMetaObject * metaObject, int signal_index) static
Definition at line 3169 of file qobject.cpp.
Referenced by QMetaObject::connect(), QMetaObject::disconnect(), and QMetaObject::disconnectOne().
 {
     if (signal_index < 0)
         return signal_index;
     while (metaObject && metaObject->methodOffset() > signal_index)
         metaObject = metaObject->superClass();
     if (metaObject) {
         int signalOffset, methodOffset;
         computeOffsets(metaObject, &signalOffset, &methodOffset);
         if (signal_index < metaObject->methodCount())
             signal_index = QMetaObjectPrivate::originalClone(metaObject, signal_index - methodOffset) + signalOffset;
         else
             signal_index = signal_index - methodOffset + signalOffset;
     }
     return signal_index;
 }
operator<<()
QDebug operator<< (QDebug dbg, const QObject * o)
Definition at line 4030 of file qobject.cpp.
{
 #ifndef Q_BROKEN_DEBUG_STREAM
     if (!o)
         return dbg << "QObject(0x0) ";
     dbg.nospace() << o->metaObject()->className() << '(' << (void *)o;
     if (!o->objectName().isEmpty())
         dbg << ", name = " << o->objectName();
     dbg << ')';
     return dbg.space();
 #else
     qWarning("This compiler doesn't support streaming QObject to QDebug");
     return dbg;
     Q_UNUSED(o);
 #endif
 }
qDeleteInEventHandler()
void qDeleteInEventHandler (QObject * o)
Definition at line 4348 of file qobject.cpp.
Referenced by QProcessPrivate::cleanup(), QStatusBar::clearMessage(), QNativeSocketEngine::close(), QProcessPrivate::closeWriteChannel(), QObject::event(), findRealWindow(), QWhatsThis::hideText(), and QSingleShotTimer::timerEvent().
 {
 #ifdef QT_JAMBI_BUILD
     if (!o)
         return;
     QObjectPrivate::get(o)->inEventHandler = false;
 #endif
     delete o;
 }
qFlagLocation()
const char* qFlagLocation (const char * method)
Definition at line 2222 of file qobject.cpp.
 {
     QThreadData::current()->flaggedSignatures.store(method);
     return method;
 }
qt_addObject()
Q_CORE_EXPORT void qt_addObject (QObject *)
Definition at line 114 of file qobject.cpp.
Referenced by QObject::QObject().
 {
     objectCount.ref();
 }
qt_qFindChild_helper()
QObject* qt_qFindChild_helper (const QObject * parent, const QString & name, const QMetaObject & mo)
Warning
This function is not part of the public interface.
Definition at line 1924 of file qobject.cpp.
Referenced by QObject::findChild(), and qt_qFindChild_helper().
 {
     if (!parent)
         return 0;
     const QObjectList &children = parent->children();
     QObject *obj;
     int i;
     for (i = 0; i < children.size(); ++i) {
         obj = children.at(i);
         if (mo.cast(obj) && (name.isNull() || obj->objectName() == name))
             return obj;
     }
     for (i = 0; i < children.size(); ++i) {
         obj = qt_qFindChild_helper(children.at(i), name, mo);
         if (obj)
             return obj;
     }
     return 0;
 }
qt_qFindChildren_helper()
void qt_qFindChildren_helper (const QObject * parent, const QString & name, const QRegExp * re, const QMetaObject & mo, QList< void *> * list)
Warning
This function is not part of the public interface.
Definition at line 1900 of file qobject.cpp.
Referenced by QObject::findChildren(), and qt_qFindChildren_helper().
 {
     if (!parent || !list)
         return;
     const QObjectList &children = parent->children();
     QObject *obj;
     for (int i = 0; i < children.size(); ++i) {
         obj = children.at(i);
         if (mo.cast(obj)) {
             if (re) {
                 if (re->indexIn(obj->objectName()) != -1)
                     list->append(obj);
             } else {
                 if (name.isNull() || obj->objectName() == name)
                     list->append(obj);
             }
         }
         qt_qFindChildren_helper(obj, name, re, mo, list);
     }
 }
qt_removeObject()
Q_CORE_EXPORT void qt_removeObject (QObject *)
Definition at line 119 of file qobject.cpp.
Referenced by QObject::~QObject().
 {
     if(!objectCount.deref()) {
         QMutexPool *old = signalSlotMutexes.fetchAndStoreAcquire(0);
         delete old;
     }
 }
queued_activate()
static void queued_activate (QObject * sender, int signal, QObjectPrivate::Connection * c, void ** argv) static
Definition at line 3459 of file qobject.cpp.
Referenced by QMetaObject::activate().
 {
     if (!c->argumentTypes && c->argumentTypes != &DIRECT_CONNECTION_ONLY) {
         QMetaMethod m = sender->metaObject()->method(signal);
         int *tmp = queuedConnectionTypes(m.parameterTypes());
         if (!tmp) // cannot queue arguments
             tmp = &DIRECT_CONNECTION_ONLY;
         if (!c->argumentTypes.testAndSetOrdered(0, tmp)) {
             if (tmp != &DIRECT_CONNECTION_ONLY)
                 delete [] tmp;
         }
     }
     if (c->argumentTypes == &DIRECT_CONNECTION_ONLY) // cannot activate
         return;
     int nargs = 1; // include return type
     while (c->argumentTypes[nargs-1])
         ++nargs;
     int *types = (int *) qMalloc(nargs*sizeof(int));
     Q_CHECK_PTR(types);
     void **args = (void **) qMalloc(nargs*sizeof(void *));
     Q_CHECK_PTR(args);
     types[0] = 0; // return type
     args[0] = 0; // return value
     for (int n = 1; n < nargs; ++n)
         args[n] = QMetaType::construct((types[n] = c->argumentTypes[n-1]), argv[n]);
     QCoreApplication::postEvent(c->receiver, new QMetaCallEvent(c->method_offset,
                                                                 c->method_relative,
                                                                 c->callFunction,
                                                                 sender, signal, nargs,
                                                                 types, args));
 }
queuedConnectionTypes()
static int* queuedConnectionTypes (const QList< QByteArray > & typeNames) static
Definition at line 73 of file qobject.cpp.
Referenced by QObject::connect(), and queued_activate().
 {
     int *types = new int [typeNames.count() + 1];
     Q_CHECK_PTR(types);
     for (int i = 0; i < typeNames.count(); ++i) {
         const QByteArray typeName = typeNames.at(i);
         if (typeName.endsWith('*'))
             types[i] = QMetaType::VoidStar;
         else
             types[i] = QMetaType::type(typeName);
         if (!types[i]) {
             qWarning("QObject::connect: Cannot queue arguments of type '%s'\n"
                      "(Make sure '%s' is registered using qRegisterMetaType().)",
                      typeName.constData(), typeName.constData());
             delete [] types;
             return 0;
         }
     }
     types[typeNames.count()] = 0;
     return types;
 }
signalSlotLock()
static QMutex* signalSlotLock (const QObject * o) inline static
Warning
This function is not part of the public interface. mutex to be locked when accessing the connectionlists or the senders list
Definition at line 103 of file qobject.cpp.
Referenced by QMetaObject::activate(), QMetaObjectPrivate::connect(), QMetaObjectPrivate::disconnect(), QMetaObjectPrivate::disconnectHelper(), QObject::dumpObjectInfo(), QObjectPrivate::isSender(), QObjectPrivate::receiverList(), QObject::receivers(), QObject::sender(), QObjectPrivate::senderList(), QObject::senderSignalIndex(), and QObject::~QObject().
 {
     if (!signalSlotMutexes) {
         QMutexPool *mp = new QMutexPool;
         if (!signalSlotMutexes.testAndSetOrdered(0, mp)) {
             delete mp;
         }
     }
     return signalSlotMutexes->get(o);
 }
Variable Documentation
DIRECT_CONNECTION_ONLY
int DIRECT_CONNECTION_ONLY = 0 static
Definition at line 71 of file qobject.cpp.
Referenced by queued_activate(), and QObjectPrivate::Connection::~Connection().
objectCount
QBasicAtomicInt objectCount = Q_BASIC_ATOMIC_INITIALIZER(0) static
Definition at line 98 of file qobject.cpp.
Referenced by QDeclarativeEngineDebugPrivate::decode().
signalSlotMutexes
QBasicAtomicPointer<QMutexPool> signalSlotMutexes = Q_BASIC_ATOMIC_INITIALIZER(0) static
Definition at line 97 of file qobject.cpp.