Qt 4.8: /src/gui/painting/qoutlinemapper.cpp File Reference
qoutlinemapper.cpp File Reference
#include "qoutlinemapper_p.h"
#include <private/qpainterpath_p.h>
#include "qmath.h"
#include <stdlib.h>
Macros
#define qreal_to_fixed_26_6(f) (int(f * 64))
Functions
static const QRectF boundingRect (const QPointF *points, int pointCount)
Variables
static const qreal aliasedCoordinateDelta = 0.5 - 0.015625
Macro Definition Documentation
qreal_to_fixed_26_6
#define qreal_to_fixed_26_6 (f) (int(f * 64))
Definition at line 52 of file qoutlinemapper.cpp.
Referenced by QOutlineMapper::convertElements().
Function Documentation
boundingRect()
static const QRectF boundingRect (const QPointF * points, int pointCount) static
Definition at line 57 of file qoutlinemapper.cpp.
Referenced by QAlphaPaintEnginePrivate::addPenWidth(), adjustedItemBoundingRect(), adjustedItemEffectiveBoundingRect(), QmlJSDebugger::QDeclarativeViewInspector::adjustToScreenBoundaries(), QFontMetrics::boundingRect(), QPainter::boundingRect(), QPrintPreviewWidgetPrivate::calcCurrentPage(), QGraphicsItemEffectSourcePrivate::deviceRect(), QWidgetEffectSourcePrivate::deviceRect(), QTextLayout::draw(), QPainterPrivate::draw_helper(), QPainterPrivate::drawStretchedGradient(), QGL2PaintEngineExPrivate::drawVertexArrays(), QPicturePaintEngine::end(), QOutlineMapper::endOutline(), QGraphicsViewPrivate::findItems(), QIntersectionFinder::hasIntersections(), QGraphicsScene::itemsBoundingRect(), QFontMetrics::operator!=(), QDecorationWindows::paintButton(), QDecorationDefault::paintButton(), QGraphicsView::paintEvent(), QWidgetPrivate::paintSiblingsRecursive(), QmlJSDebugger::LiveSelectionRectangle::rect(), QWidgetPrivate::screenGeometry(), QGLEllipseMaskGenerator::screenRect(), QX11WindowSurface::setGeometry(), QmlJSDebugger::LiveSelectionIndicator::setItems(), QWSServer::setMaxWindowRect(), QGraphicsItem::setTransformOriginPoint(), QGL2PEXVertexArray::stopCount(), QPolygon::swap(), QPainterPath::swap(), QPainter::testRenderHint(), QGraphicsView::updateScene(), QGraphicsScenePrivate::updateTouchPointsForItem(), and QRegion::xored().
 {
     const QPointF *e = points;
     const QPointF *last = points + pointCount;
     qreal minx, maxx, miny, maxy;
     minx = maxx = e->x();
     miny = maxy = e->y();
     while (++e < last) {
         if (e->x() < minx)
             minx = e->x();
         else if (e->x() > maxx)
             maxx = e->x();
         if (e->y() < miny)
             miny = e->y();
         else if (e->y() > maxy)
             maxy = e->y();
     }
     return QRectF(QPointF(minx, miny), QPointF(maxx, maxy));
 }
Variable Documentation
aliasedCoordinateDelta
const qreal aliasedCoordinateDelta = 0.5 - 0.015625 static
Definition at line 50 of file qoutlinemapper.cpp.