Qt 4.8: /src/gui/dialogs/qpagesetupdialog_unix.cpp File Reference
qpagesetupdialog_unix.cpp File Reference
#include "qpagesetupdialog.h"
#include "qpagesetupdialog_unix_p.h"
#include "qpainter.h"
#include "qprintdialog.h"
#include "qdialogbuttonbox.h"
#include <ui_qpagesetupwidget.h>
#include <QtGui/qprinter.h>
#include <private/qabstractpagesetupdialog_p.h>
#include <private/qprinter_p.h>
#include <private/qcups_p.h>
#include <cups/cups.h>
#include <private/qpdf_p.h>
#include "moc_qpagesetupdialog.cpp"
Classes
class QPagePreview
class QPageSetupDialogPrivate
Functions
static void populatePaperSizes (QComboBox *cb)
double qt_multiplierForUnit (QPrinter::Unit unit, int resolution)
return the multiplier of converting from the unit value to postscript-points.
QSizeF qt_printerPaperSize (QPrinter::Orientation, QPrinter::PaperSize, QPrinter::Unit, int)
static QSizeF sizeForOrientation (QPrinter::Orientation orientation, const QSizeF &size)
Function Documentation
populatePaperSizes()
static void populatePaperSizes (QComboBox * cb) static
Definition at line 70 of file qpagesetupdialog_unix.cpp.
Referenced by QPageSetupWidget::QPageSetupWidget(), QPageSetupWidget::selectPdfPsPrinter(), and QPageSetupWidget::selectPrinter().
 {
     cb->addItem(QPrintDialog::tr("A0"), QPrinter::A0);
     cb->addItem(QPrintDialog::tr("A1"), QPrinter::A1);
     cb->addItem(QPrintDialog::tr("A2"), QPrinter::A2);
     cb->addItem(QPrintDialog::tr("A3"), QPrinter::A3);
     cb->addItem(QPrintDialog::tr("A4"), QPrinter::A4);
     cb->addItem(QPrintDialog::tr("A5"), QPrinter::A5);
     cb->addItem(QPrintDialog::tr("A6"), QPrinter::A6);
     cb->addItem(QPrintDialog::tr("A7"), QPrinter::A7);
     cb->addItem(QPrintDialog::tr("A8"), QPrinter::A8);
     cb->addItem(QPrintDialog::tr("A9"), QPrinter::A9);
     cb->addItem(QPrintDialog::tr("B0"), QPrinter::B0);
     cb->addItem(QPrintDialog::tr("B1"), QPrinter::B1);
     cb->addItem(QPrintDialog::tr("B2"), QPrinter::B2);
     cb->addItem(QPrintDialog::tr("B3"), QPrinter::B3);
     cb->addItem(QPrintDialog::tr("B4"), QPrinter::B4);
     cb->addItem(QPrintDialog::tr("B5"), QPrinter::B5);
     cb->addItem(QPrintDialog::tr("B6"), QPrinter::B6);
     cb->addItem(QPrintDialog::tr("B7"), QPrinter::B7);
     cb->addItem(QPrintDialog::tr("B8"), QPrinter::B8);
     cb->addItem(QPrintDialog::tr("B9"), QPrinter::B9);
     cb->addItem(QPrintDialog::tr("B10"), QPrinter::B10);
     cb->addItem(QPrintDialog::tr("C5E"), QPrinter::C5E);
     cb->addItem(QPrintDialog::tr("DLE"), QPrinter::DLE);
     cb->addItem(QPrintDialog::tr("Executive"), QPrinter::Executive);
     cb->addItem(QPrintDialog::tr("Folio"), QPrinter::Folio);
     cb->addItem(QPrintDialog::tr("Ledger"), QPrinter::Ledger);
     cb->addItem(QPrintDialog::tr("Legal"), QPrinter::Legal);
     cb->addItem(QPrintDialog::tr("Letter"), QPrinter::Letter);
     cb->addItem(QPrintDialog::tr("Tabloid"), QPrinter::Tabloid);
     cb->addItem(QPrintDialog::tr("US Common #10 Envelope"), QPrinter::Comm10E);
     cb->addItem(QPrintDialog::tr("Custom"), QPrinter::Custom);
 }
qt_multiplierForUnit()
double qt_multiplierForUnit (QPrinter::Unit unit, int resolution)
return the multiplier of converting from the unit value to postscript-points.
Definition at line 123 of file qprinter.cpp.
Referenced by QPageSetupWidget::_q_pageOrientationChanged(), QPrinter::getPageMargins(), QPrinter::pageRect(), QPrinter::paperRect(), QPrinter::paperSize(), qt_printerPaperSize(), QPrinter::setPageMargins(), QPrinter::setPaperSize(), and QPageSetupWidget::unitChanged().
 {
     switch(unit) {
     case QPrinter::Millimeter:
         return 2.83464566929;
     case QPrinter::Point:
         return 1.0;
     case QPrinter::Inch:
         return 72.0;
     case QPrinter::Pica:
         return 12;
     case QPrinter::Didot:
         return 1.065826771;
     case QPrinter::Cicero:
         return 12.789921252;
     case QPrinter::DevicePixel:
         return 72.0/resolution;
     }
     return 1.0;
 }
qt_printerPaperSize()
QSizeF qt_printerPaperSize (QPrinter::Orientation , QPrinter::PaperSize , QPrinter::Unit , int)
Definition at line 145 of file qprinter.cpp.
Referenced by QPageSetupWidget::_q_paperSizeChanged(), and QPrinter::paperSize().
 {
     int width_index = 0;
     int height_index = 1;
     if (orientation == QPrinter::Landscape) {
         width_index = 1;
         height_index = 0;
     }
     const qreal multiplier = qt_multiplierForUnit(unit, resolution);
     return QSizeF((qt_paperSizes[paperSize][width_index] * 72 / 25.4) / multiplier,
                   (qt_paperSizes[paperSize][height_index] * 72 / 25.4) / multiplier);
 }
sizeForOrientation()
static QSizeF sizeForOrientation (QPrinter::Orientation orientation, const QSizeF & size) static
Definition at line 106 of file qpagesetupdialog_unix.cpp.
Referenced by QPageSetupWidget::setupPrinter().
 {
     return (orientation == QPrinter::Portrait) ? size : QSizeF(size.height(), size.width());
 }