Qt 4.8: /src/opengl/qpaintengine_opengl.cpp File Reference
qpaintengine_opengl.cpp File Reference
#include <qdebug.h>
#include <private/qfontengine_p.h>
#include <qmath.h>
#include <private/qmath_p.h>
#include <private/qdrawhelper_p.h>
#include <private/qpaintengine_p.h>
#include "qapplication.h"
#include "qbrush.h"
#include "qgl.h"
#include <private/qgl_p.h>
#include <private/qglpaintdevice_p.h>
#include <private/qpainter_p.h>
#include "qmap.h"
#include <private/qpaintengine_opengl_p.h>
#include <private/qdatabuffer_p.h>
#include "qpen.h"
#include "qvarlengtharray.h"
#include <private/qglpixelbuffer_p.h>
#include <private/qbezier_p.h>
#include <qglframebufferobject.h>
#include <private/qstatictext_p.h>
#include "private/qtessellator_p.h"
#include "util/fragmentprograms_p.h"
#include "private/qglwindowsurface_qws_p.h"
#include "qwsmanager_qws.h"
#include "private/qwsmanager_p.h"
#include <stdlib.h>
#include "qpaintengine_opengl_p.h"
#include "qpaintengine_opengl.moc"
Classes
struct GLProgram
struct QDrawQueueItem
class QGLEllipseMaskGenerator
struct QGLFontTexture
class QGLGlyphCache
struct QGLGlyphCoord
class QGLGradientCache
struct QGLGradientCache::CacheInfo
class QGLLineMaskGenerator
class QGLMaskGenerator
class QGLMaskTextureCache
struct QGLMaskTextureCache::CacheInfo
struct QGLMaskTextureCache::CacheLocation
struct QGLMaskTextureCache::QuadTreeNode
class QGLOffscreen
class QGLPathMaskGenerator
class QGLPrivateCleanup
class QGLProgramCache
class QGLRectMaskGenerator
class QGLStrokeCache
struct QGLStrokeCache::CacheInfo
struct QGLTrapezoid
class QGLTrapezoidMaskGenerator
class QOpenGLCoordinateOffset
class QOpenGLImmediateModeTessellator
class QOpenGLPaintEnginePrivate
class QOpenGLTessellator
class QOpenGLTrapezoidToArrayTessellator
struct QT_PointF
Macros
#define DEBUG_ONCE if (0)
#define DEBUG_ONCE_STR(str) ;
#define DEBUG_OVERRIDE(state) ;
#define DISABLE_DEBUG_ONCE
#define FloatToQuint64(i) (quint64)((i) * 32)
#define QGL_FUNC_CONTEXT QGLContext *ctx = const_cast<QGLContext *>(device->context());
#define QREAL_MAX 9e100
#define QREAL_MIN -9e100
Typedefs
typedef QHash< const QGLContext *, QGLFontGlyphHash * > QGLContextHash
typedef QHash< QFontEngine *, QGLGlyphHash * > QGLFontGlyphHash
typedef QHash< quint64, QGLFontTexture * > QGLFontTexHash
typedef QHash< glyph_t, QGLGlyphCoord * > QGLGlyphHash
typedef QMultiHash< const QGLContext *, GLProgram > QGLProgramHash
Functions
static void addQuadAsTriangle (GLfloat *quad, GLfloat *triangle)
static void drawTrapezoid (const QGLTrapezoid &trap, const qreal offscreenHeight, QGLContext *ctx)
static QPainterPath ellipseRectToPath (const QRectF &rect)
static uint endianColor (uint c)
template<typename T >
static bool isRect (const T *pts, int elementCount)
static bool needsEmulation (Qt::BrushStyle style)
static bool pathClosed (const QPainterPath &path)
void qgl_cleanup_glyph_cache (QGLContext *ctx)
template<typename T >
static const T qSubImage (const T &image, const QRectF &src, QRectF *srcNew)
void qt_add_rect_to_array (const QRectF &r, GLfloat *array)
void qt_add_texcoords_to_array (qreal x1, qreal y1, qreal x2, qreal y2, GLfloat *array)
static void qt_delete_glyph_hash (QGLGlyphHash *hash)
static void qt_glColor4ubv (unsigned char *col)
Q_GUI_EXPORT QImage qt_imageForBrush (int brushStyle, bool invert)
Q_GUI_EXPORT bool qt_isExtendedRadialGradient (const QBrush &brush)
int qt_next_power_of_two (int v)
Q_GUI_EXPORT QPainterPath qt_painterPathFromVectorPath (const QVectorPath &path)
Q_GUI_EXPORT bool qt_scaleForTransform (const QTransform &transform, qreal *scale)
static const QRectF scaleRect (const QRectF &r, qreal sx, qreal sy)
static QPainterPath strokeForPath (const QPainterPath &path, const QPen &cpen)
static void updateTextureFilter (GLenum target, GLenum wrapMode, bool smoothPixmapTransform)
Variables
static bool qt_nvidiaFboNeedsFinish = false
static const int x_margin = 1
static const int y_margin = 0
Macro Definition Documentation
DEBUG_ONCE
#define DEBUG_ONCE if (0)
Definition at line 99 of file qpaintengine_opengl.cpp.
Referenced by QGLOffscreen::bind(), QGLMaskTextureCache::clearCache(), QOpenGLPaintEnginePrivate::composite(), QOpenGLPaintEnginePrivate::copyDrawable(), QOpenGLPaintEngine::drawPath(), QOpenGLPaintEnginePrivate::fillPolygon_dev(), QOpenGLPaintEnginePrivate::fillVertexArray(), QOpenGLPaintEnginePrivate::flushDrawQueue(), QGLOffscreen::initialize(), and QGLMaskTextureCache::quadtreeBlocksize().
DEBUG_ONCE_STR
#define DEBUG_ONCE_STR (str) ;
Definition at line 98 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEngine::drawEllipse(), QOpenGLPaintEnginePrivate::drawFastRect(), QOpenGLPaintEnginePrivate::drawOffscreenPath(), QGLMaskTextureCache::getMask(), QGLOffscreen::release(), QOpenGLPaintEnginePrivate::strokeLines(), and QOpenGLPaintEngine::updateRenderHints().
DEBUG_OVERRIDE
#define DEBUG_OVERRIDE (state) ;
Definition at line 97 of file qpaintengine_opengl.cpp.
DISABLE_DEBUG_ONCE
#define DISABLE_DEBUG_ONCE
Definition at line 92 of file qpaintengine_opengl.cpp.
FloatToQuint64
#define FloatToQuint64 (i) (quint64)((i) * 32)
Definition at line 2730 of file qpaintengine_opengl.cpp.
Referenced by QGLMaskTextureCache::hash().
QGL_FUNC_CONTEXT
#define QGL_FUNC_CONTEXT QGLContext *ctx = const_cast<QGLContext *>(device->context());
Definition at line 75 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEnginePrivate::composite(), QOpenGLPaintEnginePrivate::fillVertexArray(), and QOpenGLPaintEnginePrivate::updateFragmentProgramData().
QREAL_MAX
#define QREAL_MAX 9e100
Definition at line 87 of file qpaintengine_opengl.cpp.
Referenced by QGLEllipseMaskGenerator::screenRect().
QREAL_MIN
#define QREAL_MIN -9e100
Definition at line 88 of file qpaintengine_opengl.cpp.
Typedef Documentation
QGLContextHash
typedef QHash<const QGLContext*, QGLFontGlyphHash*> QGLContextHash
Definition at line 4551 of file qpaintengine_opengl.cpp.
QGLFontGlyphHash
typedef QHash<QFontEngine*, QGLGlyphHash*> QGLFontGlyphHash
Definition at line 4549 of file qpaintengine_opengl.cpp.
QGLFontTexHash
typedef QHash<quint64, QGLFontTexture*> QGLFontTexHash
Definition at line 4550 of file qpaintengine_opengl.cpp.
QGLGlyphHash
typedef QHash<glyph_t, QGLGlyphCoord*> QGLGlyphHash
Definition at line 4548 of file qpaintengine_opengl.cpp.
QGLProgramHash
typedef QMultiHash<const QGLContext *, GLProgram> QGLProgramHash
Definition at line 516 of file qpaintengine_opengl.cpp.
Function Documentation
addQuadAsTriangle()
static void addQuadAsTriangle (GLfloat * quad, GLfloat * triangle) static
Definition at line 3558 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEngine::drawLines().
 {
     triangle[0] = quad[0];
     triangle[1] = quad[1];
     triangle[2] = quad[2];
     triangle[3] = quad[3];
     triangle[4] = quad[4];
     triangle[5] = quad[5];
     triangle[6] = quad[4];
     triangle[7] = quad[5];
     triangle[8] = quad[6];
     triangle[9] = quad[7];
     triangle[10] = quad[0];
     triangle[11] = quad[1];
 }
drawTrapezoid()
static void drawTrapezoid (const QGLTrapezoid & trap, const qreal offscreenHeight, QGLContext * ctx) static
Definition at line 1730 of file qpaintengine_opengl.cpp.
Referenced by QGLTrapezoidMaskGenerator::drawMask().
 {
     qreal minX = qMin(trap.topLeftX, trap.bottomLeftX);
     qreal maxX = qMax(trap.topRightX, trap.bottomRightX);
     if (qFuzzyCompare(trap.top, trap.bottom) || qFuzzyCompare(minX, maxX) ||
         (qFuzzyCompare(trap.topLeftX, trap.topRightX) && qFuzzyCompare(trap.bottomLeftX, trap.bottomRightX)))
         return;
     const qreal xpadding = 1.0;
     const qreal ypadding = 1.0;
     qreal topDist = offscreenHeight - trap.top;
     qreal bottomDist = offscreenHeight - trap.bottom;
     qreal reciprocal = bottomDist / (bottomDist - topDist);
     qreal leftB = trap.bottomLeftX + (trap.topLeftX - trap.bottomLeftX) * reciprocal;
     qreal rightB = trap.bottomRightX + (trap.topRightX - trap.bottomRightX) * reciprocal;
     const bool topZero = qFuzzyIsNull(topDist);
     reciprocal = topZero ? 1.0 / bottomDist : 1.0 / topDist;
     qreal leftA = topZero ? (trap.bottomLeftX - leftB) * reciprocal : (trap.topLeftX - leftB) * reciprocal;
     qreal rightA = topZero ? (trap.bottomRightX - rightB) * reciprocal : (trap.topRightX - rightB) * reciprocal;
     qreal invLeftA = qFuzzyIsNull(leftA) ? 0.0 : 1.0 / leftA;
     qreal invRightA = qFuzzyIsNull(rightA) ? 0.0 : 1.0 / rightA;
     // fragment program needs the negative of invRightA as it mirrors the line
     glTexCoord4f(topDist, bottomDist, invLeftA, -invRightA);
     glMultiTexCoord4f(GL_TEXTURE1, leftA, leftB, rightA, rightB);
     qreal topY = trap.top - ypadding;
     qreal bottomY = trap.bottom + ypadding;
     qreal bounds_bottomLeftX = leftA * (offscreenHeight - bottomY) + leftB;
     qreal bounds_bottomRightX = rightA * (offscreenHeight - bottomY) + rightB;
     qreal bounds_topLeftX = leftA * (offscreenHeight - topY) + leftB;
     qreal bounds_topRightX = rightA * (offscreenHeight - topY) + rightB;
     QPointF leftNormal(1, -leftA);
     leftNormal /= qSqrt(leftNormal.x() * leftNormal.x() + leftNormal.y() * leftNormal.y());
     QPointF rightNormal(1, -rightA);
     rightNormal /= qSqrt(rightNormal.x() * rightNormal.x() + rightNormal.y() * rightNormal.y());
     qreal left_padding = xpadding / qAbs(leftNormal.x());
     qreal right_padding = xpadding / qAbs(rightNormal.x());
     glVertex2d(bounds_topLeftX - left_padding, topY);
     glVertex2d(bounds_topRightX + right_padding, topY);
     glVertex2d(bounds_bottomRightX + right_padding, bottomY);
     glVertex2d(bounds_bottomLeftX - left_padding, bottomY);
     glTexCoord4f(0.0f, 0.0f, 0.0f, 1.0f);
 }
ellipseRectToPath()
static QPainterPath ellipseRectToPath (const QRectF & rect) static
Definition at line 3280 of file qpaintengine_opengl.cpp.
 {
     QPainterPath path;
     path.addEllipse(rect);
     return path;
 }
endianColor()
static uint endianColor (uint c) inline static
Definition at line 1103 of file qpaintengine_opengl.cpp.
Referenced by QGLGradientCache::generateGradientColorTable().
 {
 #if Q_BYTE_ORDER == Q_LITTLE_ENDIAN
     return c;
 #else
     return ( (c << 24) & 0xff000000)
            | ((c >> 24) & 0x000000ff)
            | ((c << 8) & 0x00ff0000)
            | ((c >> 8) & 0x0000ff00);
 #endif // Q_BYTE_ORDER
 }
isRect()
template<typename T > static bool isRect (const T * pts, int elementCount) inline static
Definition at line 5489 of file qpaintengine_opengl.cpp.
{
     return (elementCount == 5 // 5-point polygon, check for closed rect
             && pts[0] == pts[8] && pts[1] == pts[9] // last point == first point
             && pts[0] == pts[6] && pts[2] == pts[4] // x values equal
             && pts[1] == pts[3] && pts[5] == pts[7] // y values equal...
             ) ||
            (elementCount == 4 // 4-point polygon, check for unclosed rect
             && pts[0] == pts[6] && pts[2] == pts[4] // x values equal
             && pts[1] == pts[3] && pts[5] == pts[7] // y values equal...
             );
 }
needsEmulation()
static bool needsEmulation (Qt::BrushStyle style) inline static
Definition at line 2124 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEngine::fill(), and QOpenGLPaintEnginePrivate::updateUseEmulation().
 {
     return !(style == Qt::SolidPattern
              || (style == Qt::LinearGradientPattern
                  && (QGLExtensions::glExtensions() & QGLExtensions::MirroredRepeat)));
 }
pathClosed()
static bool pathClosed (const QPainterPath & path) static
Definition at line 4138 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEngine::drawPath().
 {
     QPointF lastMoveTo = path.elementAt(0);
     QPointF lastPoint = lastMoveTo;
     for (int i = 1; i < path.elementCount(); ++i) {
         const QPainterPath::Element &e = path.elementAt(i);
         switch (e.type) {
         case QPainterPath::MoveToElement:
             if (lastMoveTo != lastPoint)
                 return false;
             lastMoveTo = lastPoint = e;
             break;
         case QPainterPath::LineToElement:
             lastPoint = e;
             break;
         case QPainterPath::CurveToElement:
             lastPoint = path.elementAt(i + 2);
             i+=2;
             break;
         default:
             break;
         }
     }
     return lastMoveTo == lastPoint;
 }
qgl_cleanup_glyph_cache()
void qgl_cleanup_glyph_cache (QGLContext * ctx)
Definition at line 4917 of file qpaintengine_opengl.cpp.
Referenced by QGLPixelBuffer::~QGLPixelBuffer().
 {
     qt_glyph_cache()->cleanupContext(ctx);
 }
qSubImage()
template<typename T > static const T qSubImage (const T & image, const QRectF & src, QRectF * srcNew) static
Definition at line 4274 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEngine::drawImage(), and QOpenGLPaintEngine::drawPixmap().
 {
     const int sx1 = qMax(0, qFloor(src.left()));
     const int sy1 = qMax(0, qFloor(src.top()));
     const int sx2 = qMin(image.width(), qCeil(src.right()));
     const int sy2 = qMin(image.height(), qCeil(src.bottom()));
     const T sub = image.copy(sx1, sy1, sx2 - sx1, sy2 - sy1);
     if (srcNew)
         *srcNew = src.translated(-sx1, -sy1);
     return sub;
 }
qt_add_rect_to_array()
void qt_add_rect_to_array (const QRectF & r, GLfloat * array)
Definition at line 2972 of file qgl.cpp.
Referenced by QOpenGLPaintEnginePrivate::composite(), QOpenGLPaintEnginePrivate::drawFastRect(), QGLTrapezoidMaskGenerator::drawMask(), QGLEllipseMaskGenerator::drawMask(), QOpenGLPaintEngine::drawStaticTextItem(), drawTexture(), QOpenGLPaintEngine::drawTextureRect(), QOpenGLPaintEngine::drawTiledPixmap(), and QGLTrapezoidMaskGenerator::QGLTrapezoidMaskGenerator().
 {
     qreal left = r.left();
     qreal right = r.right();
     qreal top = r.top();
     qreal bottom = r.bottom();
     array[0] = left;
     array[1] = top;
     array[2] = right;
     array[3] = top;
     array[4] = right;
     array[5] = bottom;
     array[6] = left;
     array[7] = bottom;
 }
qt_add_texcoords_to_array()
void qt_add_texcoords_to_array (qreal x1, qreal y1, qreal x2, qreal y2, GLfloat * array)
Definition at line 2989 of file qgl.cpp.
Referenced by QOpenGLPaintEngine::drawStaticTextItem(), QOpenGLPaintEngine::drawTextureRect(), QOpenGLPaintEngine::drawTiledPixmap(), and QGLTrapezoidMaskGenerator::QGLTrapezoidMaskGenerator().
 {
     array[0] = x1;
     array[1] = y1;
     array[2] = x2;
     array[3] = y1;
     array[4] = x2;
     array[5] = y2;
     array[6] = x1;
     array[7] = y2;
 }
qt_delete_glyph_hash()
static void qt_delete_glyph_hash (QGLGlyphHash * hash) inline static
Definition at line 4553 of file qpaintengine_opengl.cpp.
Referenced by QGLGlyphCache::cleanCache(), QGLGlyphCache::cleanupContext(), and QGLGlyphCache::fontEngineDestroyed().
 {
     qDeleteAll(*hash);
     delete hash;
 }
qt_glColor4ubv()
static void qt_glColor4ubv (unsigned char * col) inline static
Definition at line 112 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEngine::drawStaticTextItem(), QOpenGLPaintEnginePrivate::flushDrawQueue(), QOpenGLPaintEnginePrivate::setGradientOps(), and QOpenGLPaintEnginePrivate::updateGradient().
 {
     glColor4f(col[0]/255.0f, col[1]/255.0f, col[2]/255.0f, col[3]/255.0f);
 }
qt_imageForBrush()
Q_GUI_EXPORT QImage qt_imageForBrush (int brushStyle, bool invert)
Definition at line 167 of file qbrush.cpp.
Referenced by QOpenGLPaintEnginePrivate::composite().
 {
     return qt_brushPatternImageCache()->getImage(brushStyle, invert);
 }
qt_isExtendedRadialGradient()
Q_GUI_EXPORT bool qt_isExtendedRadialGradient (const QBrush & brush)
Definition at line 881 of file qbrush.cpp.
Referenced by QOpenGLPaintEngine::fill(), QOpenGLPaintEnginePrivate::fillPath(), QBrush::isOpaque(), QVGPaintEnginePrivate::needsEmulation(), and QOpenGLPaintEnginePrivate::updateUseEmulation().
 {
     if (brush.style() == Qt::RadialGradientPattern) {
         const QGradient *g = brush.gradient();
         const QRadialGradient *rg = static_cast<const QRadialGradient *>(g);
         if (!qFuzzyIsNull(rg->focalRadius()))
             return true;
         QPointF delta = rg->focalPoint() - rg->center();
         if (delta.x() * delta.x() + delta.y() * delta.y() > rg->radius() * rg->radius())
             return true;
     }
     return false;
 }
qt_next_power_of_two()
int qt_next_power_of_two (int v)
Definition at line 1886 of file qgl.cpp.
Referenced by QOpenGLPaintEngine::begin(), QGLGlyphCache::cacheGlyphs(), QGLOffscreen::initialize(), and QGLMaskTextureCache::quadtreeFindExistingLocation().
 {
     v--;
     v |= v >> 1;
     v |= v >> 2;
     v |= v >> 4;
     v |= v >> 8;
     v |= v >> 16;
     ++v;
     return v;
 }
qt_painterPathFromVectorPath()
Q_GUI_EXPORT QPainterPath qt_painterPathFromVectorPath (const QVectorPath & path)
Definition at line 1033 of file qpaintengineex.cpp.
Referenced by QOpenGLPaintEngine::fill(), and QOpenGLPaintEngine::transformChanged().
 {
     const qreal *points = path.points();
     const QPainterPath::ElementType *types = path.elements();
     QPainterPath p;
     if (types) {
         int id = 0;
         for (int i=0; i<path.elementCount(); ++i) {
             switch(types[i]) {
             case QPainterPath::MoveToElement:
                 p.moveTo(QPointF(points[id], points[id+1]));
                 id+=2;
                 break;
             case QPainterPath::LineToElement:
                 p.lineTo(QPointF(points[id], points[id+1]));
                 id+=2;
                 break;
             case QPainterPath::CurveToElement: {
                 QPointF p1(points[id], points[id+1]);
                 QPointF p2(points[id+2], points[id+3]);
                 QPointF p3(points[id+4], points[id+5]);
                 p.cubicTo(p1, p2, p3);
                 id+=6;
                 break;
             }
             case QPainterPath::CurveToDataElement:
                 ;
                 break;
             }
         }
     } else {
         p.moveTo(QPointF(points[0], points[1]));
         int id = 2;
         for (int i=1; i<path.elementCount(); ++i) {
             p.lineTo(QPointF(points[id], points[id+1]));
             id+=2;
         }
     }
     if (path.hints() & QVectorPath::WindingFill)
         p.setFillRule(Qt::WindingFill);
     return p;
 }
qt_scaleForTransform()
Q_GUI_EXPORT bool qt_scaleForTransform (const QTransform & transform, qreal * scale)
Definition at line 2407 of file qtransform.cpp.
Referenced by QOpenGLPaintEnginePrivate::strokeLines(), and QOpenGLPaintEnginePrivate::strokePath().
 {
     const QTransform::TransformationType type = transform.type();
     if (type <= QTransform::TxTranslate) {
         if (scale)
             *scale = 1;
         return true;
     } else if (type == QTransform::TxScale) {
         const qreal xScale = qAbs(transform.m11());
         const qreal yScale = qAbs(transform.m22());
         if (scale)
             *scale = qMax(xScale, yScale);
         return qFuzzyCompare(xScale, yScale);
     }
     const qreal xScale = transform.m11() * transform.m11()
                          + transform.m21() * transform.m21();
     const qreal yScale = transform.m12() * transform.m12()
                          + transform.m22() * transform.m22();
     if (scale)
         *scale = qSqrt(qMax(xScale, yScale));
     return type == QTransform::TxRotate && qFuzzyCompare(xScale, yScale);
 }
scaleRect()
static const QRectF scaleRect (const QRectF & r, qreal sx, qreal sy) static
Definition at line 4268 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEngine::drawImage(), and QOpenGLPaintEngine::drawPixmap().
 {
     return QRectF(r.x() * sx, r.y() * sy, r.width() * sx, r.height() * sy);
 }
strokeForPath()
static QPainterPath strokeForPath (const QPainterPath & path, const QPen & cpen) inline static
Definition at line 916 of file qpaintengine_opengl.cpp.
Referenced by QGLStrokeCache::addCacheElement(), and QOpenGLPaintEnginePrivate::strokePath().
{
     QPainterPathStroker stroker;
     if (cpen.style() == Qt::CustomDashLine)
         stroker.setDashPattern(cpen.dashPattern());
     else
         stroker.setDashPattern(cpen.style());
     stroker.setCapStyle(cpen.capStyle());
     stroker.setJoinStyle(cpen.joinStyle());
     stroker.setMiterLimit(cpen.miterLimit());
     stroker.setDashOffset(cpen.dashOffset());
     qreal width = cpen.widthF();
     if (width == 0)
         stroker.setWidth(1);
     else
         stroker.setWidth(width);
     QPainterPath stroke = stroker.createStroke(path);
     stroke.setFillRule(Qt::WindingFill);
     return stroke;
 }
updateTextureFilter()
static void updateTextureFilter (GLenum target, GLenum wrapMode, bool smoothPixmapTransform) inline static
Definition at line 903 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEnginePrivate::composite(), QGL2PaintEngineExPrivate::drawCachedGlyphs(), QGL2PaintEngineExPrivate::drawPixmapFragments(), QOpenGLPaintEngine::drawTextureRect(), QOpenGLPaintEngine::drawTiledPixmap(), and QGL2PaintEngineExPrivate::QGL2PaintEngineExPrivate().
 {
     if (smoothPixmapTransform) {
         glTexParameterf(target, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
         glTexParameterf(target, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
     } else {
         glTexParameterf(target, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
         glTexParameterf(target, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
     }
     glTexParameterf(target, GL_TEXTURE_WRAP_S, wrapMode);
     glTexParameterf(target, GL_TEXTURE_WRAP_T, wrapMode);
 }
Variable Documentation
qt_nvidiaFboNeedsFinish
bool qt_nvidiaFboNeedsFinish = false static
Definition at line 109 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEngine::begin(), and QGLOffscreen::release().
x_margin
const int x_margin = 1 static
Definition at line 4522 of file qpaintengine_opengl.cpp.
Referenced by QGLGlyphCache::cacheGlyphs().
y_margin
const int y_margin = 0 static
Definition at line 4523 of file qpaintengine_opengl.cpp.
Referenced by QGLGlyphCache::cacheGlyphs().