Qt 4.8: /src/gui/painting/qpaintbuffer.cpp File Reference
qpaintbuffer.cpp File Reference
#include <qmath.h>
#include <private/qpainterpath_p.h>
#include <private/qpaintbuffer_p.h>
#include <private/qfontengine_p.h>
#include <private/qemulationpaintengine_p.h>
#include <private/qimage_p.h>
#include <qstatictext.h>
#include <private/qstatictext_p.h>
#include <private/qrawfont_p.h>
#include <QDebug>
Classes
class QFakeDevice
struct QPaintBufferCacheEntry
struct QPaintBufferCacheEntryV2
struct QPaintBufferCacheEntryV2::Flags
class QPaintBufferEnginePrivate
Functions
QDataStream & operator<< (QDataStream &stream, const QPaintBufferCommand &command)
QDataStream & operator<< (QDataStream &stream, const QPaintBufferCacheEntry &entry)
QDataStream & operator<< (QDataStream &stream, const QPaintBufferCacheEntryV2 &entry)
QDataStream & operator<< (QDataStream &stream, const QPaintBuffer &buffer)
QDataStream & operator>> (QDataStream &stream, QPaintBufferCommand &command)
QDataStream & operator>> (QDataStream &stream, QPaintBufferCacheEntry &entry)
QDataStream & operator>> (QDataStream &stream, QPaintBufferCacheEntryV2 &entry)
QDataStream & operator>> (QDataStream &stream, QPaintBuffer &buffer)
static QImage qpaintbuffer_storable_image (const QImage &src)
static int qRegisterPaintBufferMetaTypes ()
void qt_format_text (const QFont &font, const QRectF &_r, int tf, const QTextOption *option, const QString &str, QRectF *brect, int tabstops, int *tabarray, int tabarraylen, QPainter *painter)
Function Documentation
operator<<() [1/4]
QDataStream& operator<< (QDataStream & stream, const QPaintBufferCommand & command)
Definition at line 2100 of file qpaintbuffer.cpp.
 {
     quint32 id = command.id;
     quint32 size = command.size;
     stream << id << size;
     stream << command.offset << command.offset2 << command.extra;
     return stream;
 }
operator<<() [2/4]
QDataStream& operator<< (QDataStream & stream, const QPaintBufferCacheEntry & entry)
Definition at line 2149 of file qpaintbuffer.cpp.
 {
     return stream << entry.type << entry.cacheKey;
 }
operator<<() [3/4]
QDataStream& operator<< (QDataStream & stream, const QPaintBufferCacheEntryV2 & entry)
Definition at line 2159 of file qpaintbuffer.cpp.
 {
     return stream << entry.bits;
 }
operator<<() [4/4]
QDataStream& operator<< (QDataStream & stream, const QPaintBuffer & buffer)
Definition at line 2181 of file qpaintbuffer.cpp.
 {
     QHash<qint64, uint> pixmapKeys;
     QHash<qint64, uint> imageKeys;
     QHash<qint64, QPixmap> pixmaps;
     QHash<qint64, QImage> images;
     QVector<QVariant> variants = buffer.d_ptr->variants;
     for (int i = 0; i < variants.size(); ++i) {
         const QVariant &v = variants.at(i);
         if (v.type() == QVariant::Image) {
             const QImage image(v.value<QImage>());
             QPaintBufferCacheEntryV2 entry;
             entry.flags.type = QPaintBufferCacheEntryV2::ImageKey;
             QHash<qint64, uint>::iterator it = imageKeys.find(image.cacheKey());
             if (it != imageKeys.end()) {
                 entry.flags.key = *it;
             } else {
                 imageKeys[image.cacheKey()] = entry.flags.key = images.size();
                 images[images.size()] = image;
             }
             variants[i] = QVariant::fromValue(entry);
         } else if (v.type() == QVariant::Pixmap) {
             const QPixmap pixmap(v.value<QPixmap>());
             QPaintBufferCacheEntryV2 entry;
             entry.flags.type = QPaintBufferCacheEntryV2::PixmapKey;
             QHash<qint64, uint>::iterator it = pixmapKeys.find(pixmap.cacheKey());
             if (it != pixmapKeys.end()) {
                 entry.flags.key = *it;
             } else {
                 pixmapKeys[pixmap.cacheKey()] = entry.flags.key = pixmaps.size();
                 pixmaps[pixmaps.size()] = pixmap;
             }
             variants[i] = QVariant::fromValue(entry);
         }
     }
     stream << pixmaps;
     stream << images;
     stream << buffer.d_ptr->ints;
     stream << buffer.d_ptr->floats;
     stream << variants;
     stream << buffer.d_ptr->commands;
     stream << buffer.d_ptr->boundingRect;
     stream << buffer.d_ptr->frames;
     return stream;
 }
operator>>() [1/4]
QDataStream& operator>> (QDataStream & stream, QPaintBufferCommand & command)
Definition at line 2109 of file qpaintbuffer.cpp.
 {
     quint32 id;
     quint32 size;
     stream >> id >> size;
     stream >> command.offset >> command.offset2 >> command.extra;
     command.id = id;
     command.size = size;
     return stream;
 }
operator>>() [2/4]
QDataStream& operator>> (QDataStream & stream, QPaintBufferCacheEntry & entry)
Definition at line 2154 of file qpaintbuffer.cpp.
 {
     return stream >> entry.type >> entry.cacheKey;
 }
operator>>() [3/4]
QDataStream& operator>> (QDataStream & stream, QPaintBufferCacheEntryV2 & entry)
Definition at line 2164 of file qpaintbuffer.cpp.
 {
     return stream >> entry.bits;
 }
operator>>() [4/4]
QDataStream& operator>> (QDataStream & stream, QPaintBuffer & buffer)
Definition at line 2238 of file qpaintbuffer.cpp.
 {
     QHash<qint64, QPixmap> pixmaps;
     QHash<qint64, QImage> images;
     stream >> pixmaps;
     stream >> images;
     stream >> buffer.d_ptr->ints;
     stream >> buffer.d_ptr->floats;
     stream >> buffer.d_ptr->variants;
     stream >> buffer.d_ptr->commands;
     stream >> buffer.d_ptr->boundingRect;
     stream >> buffer.d_ptr->frames;
     QVector<QVariant> &variants = buffer.d_ptr->variants;
     for (int i = 0; i < variants.size(); ++i) {
         const QVariant &v = variants.at(i);
         if (v.canConvert<QPaintBufferCacheEntry>()) {
             QPaintBufferCacheEntry entry = v.value<QPaintBufferCacheEntry>();
             if (entry.type == QVariant::Image)
                 variants[i] = QVariant(images.value(entry.cacheKey));
             else
                 variants[i] = QVariant(pixmaps.value(entry.cacheKey));
         } else if (v.canConvert<QPaintBufferCacheEntryV2>()) {
             QPaintBufferCacheEntryV2 entry = v.value<QPaintBufferCacheEntryV2>();
             if (entry.flags.type == QPaintBufferCacheEntryV2::ImageKey)
                 variants[i] = QVariant(images.value(entry.flags.key));
             else if (entry.flags.type == QPaintBufferCacheEntryV2::PixmapKey)
                 variants[i] = QVariant(pixmaps.value(entry.flags.key));
             else
                 qWarning() << "operator<<(QDataStream &stream, QPaintBuffer &buffer): unrecognized cache entry type:" << entry.flags.type;
         }
     }
     return stream;
 }
qpaintbuffer_storable_image()
static QImage qpaintbuffer_storable_image (const QImage & src) inline static
Definition at line 1212 of file qpaintbuffer.cpp.
Referenced by QPaintBufferEngine::drawImage().
 {
     QImageData *d = const_cast<QImage &>(src).data_ptr();
     return d->own_data ? src : src.copy();
 }
qRegisterPaintBufferMetaTypes()
static int qRegisterPaintBufferMetaTypes () static
Definition at line 2169 of file qpaintbuffer.cpp.
 {
     qRegisterMetaType<QPaintBufferCacheEntry>();
     qRegisterMetaTypeStreamOperators<QPaintBufferCacheEntry>("QPaintBufferCacheEntry");
     qRegisterMetaType<QPaintBufferCacheEntryV2>();
     qRegisterMetaTypeStreamOperators<QPaintBufferCacheEntryV2>("QPaintBufferCacheEntryV2");
     return 0; // something
 }
qt_format_text()
void qt_format_text (const QFont & font, const QRectF & _r, int tf, const QTextOption * option, const QString & str, QRectF * brect, int tabstops, int * tabarray, int tabarraylen, QPainter * painter)
Definition at line 8458 of file qpainter.cpp.
Referenced by QPainter::boundingRect(), QPainter::drawText(), QPainterReplayer::process(), and qt_format_text().
 {
     Q_ASSERT( !((tf & ~Qt::TextDontPrint)!=0 && option!=0) ); // we either have an option or flags
     if (option) {
         tf |= option->alignment();
         if (option->wrapMode() != QTextOption::NoWrap)
             tf |= Qt::TextWordWrap;
         if (option->flags() & QTextOption::IncludeTrailingSpaces)
             tf |= Qt::TextIncludeTrailingSpaces;
         if (option->tabStop() >= 0 || !option->tabArray().isEmpty())
             tf |= Qt::TextExpandTabs;
     }
     // we need to copy r here to protect against the case (&r == brect).
     QRectF r(_r);
     bool dontclip  = (tf & Qt::TextDontClip);
     bool wordwrap  = (tf & Qt::TextWordWrap) || (tf & Qt::TextWrapAnywhere);
     bool singleline = (tf & Qt::TextSingleLine);
     bool showmnemonic = (tf & Qt::TextShowMnemonic);
     bool hidemnmemonic = (tf & Qt::TextHideMnemonic);
     Qt::LayoutDirection layout_direction;
     if (tf & Qt::TextForceLeftToRight)
         layout_direction = Qt::LeftToRight;
     else if (tf & Qt::TextForceRightToLeft)
         layout_direction = Qt::RightToLeft;
     else if (option)
         layout_direction = option->textDirection();
     else if (painter)
         layout_direction = painter->layoutDirection();
     else
         layout_direction = Qt::LeftToRight;
     tf = QStyle::visualAlignment(layout_direction, QFlag(tf));
     bool isRightToLeft = layout_direction == Qt::RightToLeft;
     bool expandtabs = ((tf & Qt::TextExpandTabs) &&
                         (((tf & Qt::AlignLeft) && !isRightToLeft) ||
                           ((tf & Qt::AlignRight) && isRightToLeft)));
     if (!painter)
         tf |= Qt::TextDontPrint;
     uint maxUnderlines = 0;
     int numUnderlines = 0;
     QVarLengthArray<int, 32> underlinePositions(1);
     QFontMetricsF fm(fnt);
     QString text = str;
     int offset = 0;
 start_lengthVariant:
     bool hasMoreLengthVariants = false;
     // compatible behaviour to the old implementation. Replace
     // tabs by spaces
     int old_offset = offset;
     for (; offset < text.length(); offset++) {
         QChar chr = text.at(offset);
         if (chr == QLatin1Char('\r') || (singleline && chr == QLatin1Char('\n'))) {
             text[offset] = QLatin1Char(' ');
         } else if (chr == QLatin1Char('\n')) {
             text[offset] = QChar::LineSeparator;
         } else if (chr == QLatin1Char('&')) {
             ++maxUnderlines;
         } else if (chr == QLatin1Char('\t')) {
             if (!expandtabs) {
                 text[offset] = QLatin1Char(' ');
             } else if (!tabarraylen && !tabstops) {
                 tabstops = qRound(fm.width(QLatin1Char('x'))*8);
             }
         } else if (chr == QChar(ushort(0x9c))) {
             // string with multiple length variants
             hasMoreLengthVariants = true;
             break;
         }
     }
     int length = offset - old_offset;
     if ((hidemnmemonic || showmnemonic) && maxUnderlines > 0) {
         underlinePositions.resize(maxUnderlines + 1);
         QChar *cout = text.data() + old_offset;
         QChar *cin = cout;
         int l = length;
         while (l) {
             if (*cin == QLatin1Char('&')) {
                 ++cin;
                 --length;
                 --l;
                 if (!l)
                     break;
                 if (*cin != QLatin1Char('&') && !hidemnmemonic)
                     underlinePositions[numUnderlines++] = cout - text.data() - old_offset;
             }
             *cout = *cin;
             ++cout;
             ++cin;
             --l;
         }
     }
     // no need to do extra work for underlines if we don't paint
     if (tf & Qt::TextDontPrint)
         numUnderlines = 0;
     underlinePositions[numUnderlines] = -1;
     qreal height = 0;
     qreal width = 0;
     QString finalText = text.mid(old_offset, length);
     QStackTextEngine engine(finalText, fnt);
     if (option) {
         engine.option = *option;
     }
     if (engine.option.tabStop() < 0 && tabstops > 0)
         engine.option.setTabStop(tabstops);
     if (engine.option.tabs().isEmpty() && ta) {
         QList<qreal> tabs;
         for (int i = 0; i < tabarraylen; i++)
             tabs.append(qreal(ta[i]));
         engine.option.setTabArray(tabs);
     }
     engine.option.setTextDirection(layout_direction);
     if (tf & Qt::AlignJustify)
         engine.option.setAlignment(Qt::AlignJustify);
     else
         engine.option.setAlignment(Qt::AlignLeft); // do not do alignment twice
     if (!option && (tf & Qt::TextWrapAnywhere))
         engine.option.setWrapMode(QTextOption::WrapAnywhere);
     if (tf & Qt::TextJustificationForced)
         engine.forceJustification = true;
     QTextLayout textLayout(&engine);
     textLayout.setCacheEnabled(true);
     textLayout.engine()->underlinePositions = underlinePositions.data();
     if (finalText.isEmpty()) {
         height = fm.height();
         width = 0;
         tf |= Qt::TextDontPrint;
     } else {
         qreal lineWidth = 0x01000000;
         if (wordwrap || (tf & Qt::TextJustificationForced))
             lineWidth = qMax<qreal>(0, r.width());
         if(!wordwrap)
             tf |= Qt::TextIncludeTrailingSpaces;
         textLayout.engine()->ignoreBidi = bool(tf & Qt::TextDontPrint);
         textLayout.beginLayout();
         qreal leading = fm.leading();
         height = -leading;
         while (1) {
             QTextLine l = textLayout.createLine();
             if (!l.isValid())
                 break;
             l.setLineWidth(lineWidth);
             height += leading;
             l.setPosition(QPointF(0., height));
             height += l.height();
             width = qMax(width, l.naturalTextWidth());
             if (!dontclip && !brect && height >= r.height())
                 break;
         }
         textLayout.endLayout();
     }
     qreal yoff = 0;
     qreal xoff = 0;
     if (tf & Qt::AlignBottom) {
         yoff = r.height() - height;
     } else if (tf & Qt::AlignVCenter) {
         yoff = (r.height() - height)/2;
         if (painter) {
             QTransform::TransformationType type = painter->transform().type();
             if (type <= QTransform::TxScale) {
                 // do the rounding manually to work around inconsistencies
                 // in the paint engines when drawing on floating point offsets
                 const qreal scale = painter->transform().m22();
                 if (scale != 0)
                     yoff = -qRound(-yoff * scale) / scale;
             }
         }
     }
     if (tf & Qt::AlignRight) {
         xoff = r.width() - width;
     } else if (tf & Qt::AlignHCenter) {
         xoff = (r.width() - width)/2;
         if (painter) {
             QTransform::TransformationType type = painter->transform().type();
             if (type <= QTransform::TxScale) {
                 // do the rounding manually to work around inconsistencies
                 // in the paint engines when drawing on floating point offsets
                 const qreal scale = painter->transform().m11();
                 if (scale != 0)
                     xoff = qRound(xoff * scale) / scale;
             }
         }
     }
     QRectF bounds = QRectF(r.x() + xoff, r.y() + yoff, width, height);
     if (hasMoreLengthVariants && !(tf & Qt::TextLongestVariant) && !r.contains(bounds)) {
         offset++;
         goto start_lengthVariant;
     }
     if (brect)
         *brect = bounds;
     if (!(tf & Qt::TextDontPrint)) {
         bool restore = false;
         if (!dontclip && !r.contains(bounds)) {
             restore = true;
             painter->save();
             painter->setClipRect(r, Qt::IntersectClip);
         }
         for (int i = 0; i < textLayout.lineCount(); i++) {
             QTextLine line = textLayout.lineAt(i);
             qreal advance = line.horizontalAdvance();
             xoff = 0;
             if (tf & Qt::AlignRight) {
                 QTextEngine *eng = textLayout.engine();
                 xoff = r.width() - advance -
                     eng->leadingSpaceWidth(eng->lines[line.lineNumber()]).toReal();
             }
             else if (tf & Qt::AlignHCenter)
                 xoff = (r.width() - advance) / 2;
             line.draw(painter, QPointF(r.x() + xoff, r.y() + yoff));
         }
         if (restore) {
             painter->restore();
         }
     }
 }