Qt 4.8: /src/gui/painting/qpaintengineex.cpp File Reference
qpaintengineex.cpp File Reference
#include "qpaintengineex_p.h"
#include "qpainter_p.h"
#include "qstroker_p.h"
#include "qbezier_p.h"
#include <private/qpainterpath_p.h>
#include <private/qfontengine_p.h>
#include <private/qstatictext_p.h>
#include <qvarlengtharray.h>
#include <qdebug.h>
Classes
struct StrokeHandler
Functions
QDebug Q_GUI_EXPORT & operator<< (QDebug &s, const QVectorPath &path)
static void qpaintengineex_cubicTo (qreal c1x, qreal c1y, qreal c2x, qreal c2y, qreal ex, qreal ey, void *data)
static void qpaintengineex_lineTo (qreal x, qreal y, void *data)
static void qpaintengineex_moveTo (qreal x, qreal y, void *data)
Q_GUI_EXPORT QPainterPath qt_painterPathFromVectorPath (const QVectorPath &path)
Q_GUI_EXPORT bool qt_scaleForTransform (const QTransform &transform, qreal *scale)
const QVectorPath & qtVectorPathForPath (const QPainterPath &path)
Variables
static QPainterPath::ElementType qpaintengineex_ellipse_types []
static QPainterPath::ElementType qpaintengineex_line_types_16 []
static QPainterPath::ElementType qpaintengineex_rect4_types_32 []
static QPainterPath::ElementType qpaintengineex_roundedrect_types []
Function Documentation
operator<<()
QDebug Q_GUI_EXPORT& operator<< (QDebug & s, const QVectorPath & path)
Definition at line 136 of file qpaintengineex.cpp.
 {
     QRectF rf = path.controlPointRect();
     s << "QVectorPath(size:" << path.elementCount()
       << " hints:" << hex << path.hints()
       << rf << ')';
     return s;
 }
qpaintengineex_cubicTo()
static void qpaintengineex_cubicTo (qreal c1x, qreal c1y, qreal c2x, qreal c2y, qreal ex, qreal ey, void * data) static
Definition at line 353 of file qpaintengineex.cpp.
Referenced by QPaintEngineEx::stroke().
{
     ((StrokeHandler *) data)->pts.add(c1x);
     ((StrokeHandler *) data)->pts.add(c1y);
     ((StrokeHandler *) data)->types.add(QPainterPath::CurveToElement);
     ((StrokeHandler *) data)->pts.add(c2x);
     ((StrokeHandler *) data)->pts.add(c2y);
     ((StrokeHandler *) data)->types.add(QPainterPath::CurveToDataElement);
     ((StrokeHandler *) data)->pts.add(ex);
     ((StrokeHandler *) data)->pts.add(ey);
     ((StrokeHandler *) data)->types.add(QPainterPath::CurveToDataElement);
 }
qpaintengineex_lineTo()
static void qpaintengineex_lineTo (qreal x, qreal y, void * data) static
Definition at line 347 of file qpaintengineex.cpp.
Referenced by QPaintEngineEx::stroke().
{
     ((StrokeHandler *) data)->pts.add(x);
     ((StrokeHandler *) data)->pts.add(y);
     ((StrokeHandler *) data)->types.add(QPainterPath::LineToElement);
 }
qpaintengineex_moveTo()
static void qpaintengineex_moveTo (qreal x, qreal y, void * data) static
Definition at line 341 of file qpaintengineex.cpp.
Referenced by QPaintEngineEx::stroke().
{
     ((StrokeHandler *) data)->pts.add(x);
     ((StrokeHandler *) data)->pts.add(y);
     ((StrokeHandler *) data)->types.add(QPainterPath::MoveToElement);
 }
qt_painterPathFromVectorPath()
Q_GUI_EXPORT QPainterPath qt_painterPathFromVectorPath (const QVectorPath & path)
Definition at line 1033 of file qpaintengineex.cpp.
Referenced by QVGPaintEngine::draw(), QVGPaintEngine::fill(), QOpenGLPaintEngine::fill(), and QOpenGLPaintEngine::transformChanged().
 {
     const qreal *points = path.points();
     const QPainterPath::ElementType *types = path.elements();
     QPainterPath p;
     if (types) {
         int id = 0;
         for (int i=0; i<path.elementCount(); ++i) {
             switch(types[i]) {
             case QPainterPath::MoveToElement:
                 p.moveTo(QPointF(points[id], points[id+1]));
                 id+=2;
                 break;
             case QPainterPath::LineToElement:
                 p.lineTo(QPointF(points[id], points[id+1]));
                 id+=2;
                 break;
             case QPainterPath::CurveToElement: {
                 QPointF p1(points[id], points[id+1]);
                 QPointF p2(points[id+2], points[id+3]);
                 QPointF p3(points[id+4], points[id+5]);
                 p.cubicTo(p1, p2, p3);
                 id+=6;
                 break;
             }
             case QPainterPath::CurveToDataElement:
                 ;
                 break;
             }
         }
     } else {
         p.moveTo(QPointF(points[0], points[1]));
         int id = 2;
         for (int i=1; i<path.elementCount(); ++i) {
             p.lineTo(QPointF(points[id], points[id+1]));
             id+=2;
         }
     }
     if (path.hints() & QVectorPath::WindingFill)
         p.setFillRule(Qt::WindingFill);
     return p;
 }
qt_scaleForTransform()
Q_GUI_EXPORT bool qt_scaleForTransform (const QTransform & transform, qreal * scale)
Definition at line 2407 of file qtransform.cpp.
Referenced by QPaintEngineEx::createState().
 {
     const QTransform::TransformationType type = transform.type();
     if (type <= QTransform::TxTranslate) {
         if (scale)
             *scale = 1;
         return true;
     } else if (type == QTransform::TxScale) {
         const qreal xScale = qAbs(transform.m11());
         const qreal yScale = qAbs(transform.m22());
         if (scale)
             *scale = qMax(xScale, yScale);
         return qFuzzyCompare(xScale, yScale);
     }
     const qreal xScale = transform.m11() * transform.m11()
                          + transform.m21() * transform.m21();
     const qreal yScale = transform.m12() * transform.m12()
                          + transform.m22() * transform.m22();
     if (scale)
         *scale = qSqrt(qMax(xScale, yScale));
     return type == QTransform::TxRotate && qFuzzyCompare(xScale, yScale);
 }
qtVectorPathForPath()
const QVectorPath& qtVectorPathForPath (const QPainterPath & path)
Definition at line 129 of file qpaintengineex.cpp.
Referenced by QGL2PaintEngineEx::clip(), QPaintEngineEx::clip(), QPaintEngineEx::drawPath(), QPaintEngineEx::drawStaticTextItem(), QPainter::fillPath(), QTriangulator< T >::initialize(), QPainter::strokePath(), and QGL2PaintEngineExPrivate::systemStateChanged().
 {
     Q_ASSERT(path.d_func());
     return path.d_func()->vectorPath();
 }
Variable Documentation
qpaintengineex_ellipse_types
QPainterPath::ElementType qpaintengineex_ellipse_types[] static
Initial value:
= {
    QPainterPath::MoveToElement,
    QPainterPath::CurveToElement,
    QPainterPath::CurveToDataElement,
    QPainterPath::CurveToDataElement,
    QPainterPath::CurveToElement,
    QPainterPath::CurveToDataElement,
    QPainterPath::CurveToDataElement,
    QPainterPath::CurveToElement,
    QPainterPath::CurveToDataElement,
    QPainterPath::CurveToDataElement,
    QPainterPath::CurveToElement,
    QPainterPath::CurveToDataElement,
    QPainterPath::CurveToDataElement
}
Definition at line 245 of file qpaintengineex.cpp.
Referenced by QPaintEngineEx::drawEllipse().
qpaintengineex_line_types_16
QPainterPath::ElementType qpaintengineex_line_types_16[] static
Initial value:
= {
    QPainterPath::MoveToElement, QPainterPath::LineToElement,
    QPainterPath::MoveToElement, QPainterPath::LineToElement,
    QPainterPath::MoveToElement, QPainterPath::LineToElement,
    QPainterPath::MoveToElement, QPainterPath::LineToElement,
    QPainterPath::MoveToElement, QPainterPath::LineToElement,
    QPainterPath::MoveToElement, QPainterPath::LineToElement,
    QPainterPath::MoveToElement, QPainterPath::LineToElement,
    QPainterPath::MoveToElement, QPainterPath::LineToElement,
    QPainterPath::MoveToElement, QPainterPath::LineToElement,
    QPainterPath::MoveToElement, QPainterPath::LineToElement,
    QPainterPath::MoveToElement, QPainterPath::LineToElement,
    QPainterPath::MoveToElement, QPainterPath::LineToElement,
    QPainterPath::MoveToElement, QPainterPath::LineToElement,
    QPainterPath::MoveToElement, QPainterPath::LineToElement,
    QPainterPath::MoveToElement, QPainterPath::LineToElement,
    QPainterPath::MoveToElement, QPainterPath::LineToElement
}
Definition at line 264 of file qpaintengineex.cpp.
Referenced by QPaintEngineEx::drawLines(), and QPaintEngineEx::drawPoints().
qpaintengineex_rect4_types_32
QPainterPath::ElementType qpaintengineex_rect4_types_32[] static
Definition at line 283 of file qpaintengineex.cpp.
Referenced by QPaintEngineEx::clip().
qpaintengineex_roundedrect_types
QPainterPath::ElementType qpaintengineex_roundedrect_types[] static
Initial value:
= {
    QPainterPath::MoveToElement,
    QPainterPath::LineToElement,
    QPainterPath::CurveToElement,
    QPainterPath::CurveToDataElement,
    QPainterPath::CurveToDataElement,
    QPainterPath::LineToElement,
    QPainterPath::CurveToElement,
    QPainterPath::CurveToDataElement,
    QPainterPath::CurveToDataElement,
    QPainterPath::LineToElement,
    QPainterPath::CurveToElement,
    QPainterPath::CurveToDataElement,
    QPainterPath::CurveToDataElement,
    QPainterPath::LineToElement,
    QPainterPath::CurveToElement,
    QPainterPath::CurveToDataElement,
    QPainterPath::CurveToDataElement
}
Definition at line 319 of file qpaintengineex.cpp.
Referenced by QPaintEngineEx::drawRoundedRect().