Qt 4.8: /src/gui/painting/qpaintdevice.cpp File Reference
qpaintdevice.cpp File Reference
#include "qpaintdevice.h"
Functions
Q_GUI_EXPORT int qt_paint_device_metric (const QPaintDevice *device, QPaintDevice::PaintDeviceMetric metric)
void qt_painter_removePaintDevice (QPaintDevice *)
Function Documentation
qt_paint_device_metric()
Q_GUI_EXPORT int qt_paint_device_metric (const QPaintDevice * device, QPaintDevice::PaintDeviceMetric metric)
Definition at line 70 of file qpaintdevice.cpp.
Referenced by QGLWindowSurfaceGLPaintDevice::metric(), and QCustomRasterPaintDevice::metric().
 {
     return device->metric(metric);
 }
qt_painter_removePaintDevice()
void qt_painter_removePaintDevice (QPaintDevice *)
Definition at line 8419 of file qpainter.cpp.
Referenced by QPaintDevice::~QPaintDevice().
 {
     if (!globalRedirectionAtomic() || *globalRedirectionAtomic() == 0)
         return;
     QMutex *mutex = 0;
     QT_TRY {
         mutex = globalRedirectionsMutex();
     } QT_CATCH(...) {
         // ignore the missing mutex, since we could be called from
         // a destructor, and destructors shall not throw
     }
     QMutexLocker locker(mutex);
     QPaintDeviceRedirectionList *redirections = 0;
     QT_TRY {
         redirections = globalRedirections();
     } QT_CATCH(...) {
         // do nothing - code below is safe with redirections being 0.
     }
     if (redirections) {
         for (int i = 0; i < redirections->size(); ) {
             if(redirections->at(i) == dev || redirections->at(i).replacement == dev)
                 redirections->removeAt(i);
             else
                 ++i;
         }
     }
 }