Qt 4.8: /src/opengl/gl2paintengineex/qpaintengineex_opengl2.cpp File Reference
qpaintengineex_opengl2.cpp File Reference
#include "qglgradientcache_p.h"
#include "qpaintengineex_opengl2_p.h"
#include <string.h>
#include <qmath.h>
#include <private/qgl_p.h>
#include <private/qmath_p.h>
#include <private/qpaintengineex_p.h>
#include <QPaintEngine>
#include <private/qpainter_p.h>
#include <private/qfontengine_p.h>
#include <private/qpixmapdata_gl_p.h>
#include <private/qdatabuffer_p.h>
#include <private/qstatictext_p.h>
#include <private/qtriangulator_p.h>
#include "qglengineshadermanager_p.h"
#include "qgl2pexvertexarray_p.h"
#include "qtriangulatingstroker_p.h"
#include "qtextureglyphcache_gl_p.h"
#include <QDebug>
Classes
struct QGL2PEVectorPathCache
Macros
#define QT_MAX_CACHED_GLYPH_SIZE 64
Functions
static bool fontSmoothingApproximately (qreal target)
static bool isPowerOfTwo (uint x)
Q_GUI_EXPORT QImage qt_imageForBrush (int brushStyle, bool invert)
QColor qt_premultiplyColor (QColor c, GLfloat opacity)
Q_GUI_EXPORT bool qt_scaleForTransform (const QTransform &transform, qreal *scale)
static qreal qt_sRGB_to_linear_RGB (qreal f)
static const QRectF scaleRect (const QRectF &r, qreal sx, qreal sy)
static void setCoords (GLfloat *coords, const QGLRect &rect)
Variables
bool qt_applefontsmoothing_enabled
Q_GUI_EXPORT bool qt_cleartype_enabled
Macro Definition Documentation
QT_MAX_CACHED_GLYPH_SIZE
#define QT_MAX_CACHED_GLYPH_SIZE 64
Definition at line 107 of file qpaintengineex_opengl2.cpp.
Referenced by QGL2PaintEngineEx::drawStaticTextItem(), and QGL2PaintEngineEx::drawTextItem().
Function Documentation
fontSmoothingApproximately()
static bool fontSmoothingApproximately (qreal target) static
Definition at line 1578 of file qpaintengineex_opengl2.cpp.
Referenced by QGL2PaintEngineEx::begin(), and QGL2PaintEngineExPrivate::drawCachedGlyphs().
 {
     extern Q_GUI_EXPORT qreal qt_fontsmoothing_gamma; // qapplication_win.cpp
     return (qAbs(qt_fontsmoothing_gamma - target) < 0.2);
 }
isPowerOfTwo()
static bool isPowerOfTwo (uint x) inline static
Definition at line 93 of file qpaintengineex_opengl2.cpp.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs(), and QGL2PaintEngineExPrivate::updateBrushTexture().
 {
     return x && !(x & (x - 1));
 }
qt_imageForBrush()
Q_GUI_EXPORT QImage qt_imageForBrush (int brushStyle, bool invert)
Definition at line 167 of file qbrush.cpp.
Referenced by QGL2PaintEngineExPrivate::updateBrushTexture().
 {
     return qt_brushPatternImageCache()->getImage(brushStyle, invert);
 }
qt_premultiplyColor()
QColor qt_premultiplyColor (QColor c, GLfloat opacity) inline
Definition at line 151 of file qpaintengineex_opengl2.cpp.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs(), QGL2PaintEngineExPrivate::drawPixmapFragments(), QGL2PaintEngineExPrivate::drawTexture(), and QGL2PaintEngineExPrivate::updateBrushUniforms().
 {
     qreal alpha = c.alphaF() * opacity;
     c.setAlphaF(alpha);
     c.setRedF(c.redF() * alpha);
     c.setGreenF(c.greenF() * alpha);
     c.setBlueF(c.blueF() * alpha);
     return c;
 }
qt_scaleForTransform()
Q_GUI_EXPORT bool qt_scaleForTransform (const QTransform & transform, qreal * scale)
Definition at line 2407 of file qtransform.cpp.
Referenced by QGL2PaintEngineEx::fill(), and QGL2PaintEngineEx::stroke().
 {
     const QTransform::TransformationType type = transform.type();
     if (type <= QTransform::TxTranslate) {
         if (scale)
             *scale = 1;
         return true;
     } else if (type == QTransform::TxScale) {
         const qreal xScale = qAbs(transform.m11());
         const qreal yScale = qAbs(transform.m22());
         if (scale)
             *scale = qMax(xScale, yScale);
         return qFuzzyCompare(xScale, yScale);
     }
     const qreal xScale = transform.m11() * transform.m11()
                          + transform.m21() * transform.m21();
     const qreal yScale = transform.m12() * transform.m12()
                          + transform.m22() * transform.m22();
     if (scale)
         *scale = qSqrt(qMax(xScale, yScale));
     return type == QTransform::TxRotate && qFuzzyCompare(xScale, yScale);
 }
qt_sRGB_to_linear_RGB()
static qreal qt_sRGB_to_linear_RGB (qreal f) inline static
Definition at line 1585 of file qpaintengineex_opengl2.cpp.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs().
 {
     return f > 0.04045 ? qPow((f + 0.055) / 1.055, 2.4) : f / 12.92;
 }
scaleRect()
static const QRectF scaleRect (const QRectF & r, qreal sx, qreal sy) static
Definition at line 1369 of file qpaintengineex_opengl2.cpp.
Referenced by QGL2PaintEngineEx::drawImage(), and QGL2PaintEngineEx::drawPixmap().
 {
     return QRectF(r.x() * sx, r.y() * sy, r.width() * sx, r.height() * sy);
 }
setCoords()
static void setCoords (GLfloat * coords, const QGLRect & rect) inline static
Definition at line 511 of file qpaintengineex_opengl2.cpp.
Referenced by QGL2PaintEngineExPrivate::composite(), QGL2PaintEngineExPrivate::drawTexture(), and QRect::QRect().
 {
     coords[0] = rect.left;
     coords[1] = rect.top;
     coords[2] = rect.right;
     coords[3] = rect.top;
     coords[4] = rect.right;
     coords[5] = rect.bottom;
     coords[6] = rect.left;
     coords[7] = rect.bottom;
 }
Variable Documentation
qt_applefontsmoothing_enabled
bool qt_applefontsmoothing_enabled
Definition at line 208 of file qapplication_mac.mm.
Referenced by QGL2PaintEngineEx::begin(), isPowerOfTwo(), and qt_mac_read_fontsmoothing_settings().
qt_cleartype_enabled
Q_GUI_EXPORT bool qt_cleartype_enabled
Definition at line 241 of file qapplication_win.cpp.
Referenced by QGL2PaintEngineEx::begin(), and isPowerOfTwo().