Qt 4.8: /src/gui/painting/qpainter.cpp File Reference
qpainter.cpp File Reference
#include <qdebug.h>
#include <qmath.h>
#include <qmutex.h>
#include "qbitmap.h"
#include "qimage.h"
#include "qpaintdevice.h"
#include "qpaintengine.h"
#include "qpainter.h"
#include "qpainter_p.h"
#include "qpainterpath.h"
#include "qpicture.h"
#include "qpixmapcache.h"
#include "qpolygon.h"
#include "qtextlayout.h"
#include "qwidget.h"
#include "qapplication.h"
#include "qstyle.h"
#include "qthread.h"
#include "qvarlengtharray.h"
#include "qstatictext.h"
#include "qglyphrun.h"
#include <private/qfontengine_p.h>
#include <private/qpaintengine_p.h>
#include <private/qemulationpaintengine_p.h>
#include <private/qpainterpath_p.h>
#include <private/qtextengine_p.h>
#include <private/qwidget_p.h>
#include <private/qpaintengine_raster_p.h>
#include <private/qmath_p.h>
#include <private/qstatictext_p.h>
#include <private/qglyphrun_p.h>
#include <private/qstylehelper_p.h>
#include <private/qrawfont_p.h>
Classes
struct QPaintDeviceRedirection
Macros
#define QGradient_StretchToDevice 0x10000000
#define QPaintEngine_OpaqueBackground 0x40000000
Typedefs
typedef QList< QPaintDeviceRedirection > QPaintDeviceRedirectionList
Functions
static bool check_gradient (const QBrush &brush)
static QGradient::CoordinateMode coordinateMode (const QBrush &brush)
static void drawTextItemDecoration (QPainter *painter, const QPointF &pos, const QFontEngine *fe, QTextCharFormat::UnderlineStyle underlineStyle, QTextItem::RenderFlags flags, qreal width, const QTextCharFormat &charFormat)
static QPixmap generateWavyPixmap (qreal maxRadius, const QPen &pen)
static bool is_brush_transparent (const QBrush &brush)
static bool is_pen_transparent (const QPen &pen)
static uint line_emulation (uint emulation)
static bool needsResolving (const QBrush &brush)
bool qHasPixmapTexture (const QBrush &)
static void qt_cleanup_painter_state (QPainterPrivate *d)
Q_GUI_EXPORT void qt_draw_decoration_for_glyphs (QPainter *painter, const glyph_t *glyphArray, const QFixedPoint *positions, int glyphCount, QFontEngine *fontEngine, const QFont &font, const QTextCharFormat &charFormat)
void qt_draw_helper (QPainterPrivate *p, const QPainterPath &path, QPainterPrivate::DrawOperation operation)
void qt_format_text (const QFont &font, const QRectF &_r, int tf, const QTextOption *option, const QString &str, QRectF *brect, int tabstops, int *tabarray, int tabarraylen, QPainter *painter)
void qt_format_text (const QFont &fnt, const QRectF &_r, int tf, const QString &str, QRectF *brect, int tabstops, int *ta, int tabarraylen, QPainter *painter)
Q_GUI_EXPORT bool qt_isExtendedRadialGradient (const QBrush &brush)
void qt_painter_removePaintDevice (QPaintDevice *dev)
static bool qt_painter_thread_test (int devType, const char *what, bool extraCondition=false)
QPixmap qt_pixmapForBrush (int style, bool invert)
Q_AUTOTEST_EXPORT QPainterPath qt_regionToPath (const QRegion &region)
static QPointF roundInDeviceCoordinates (const QPointF &p, const QTransform &m)
static QBrush stretchGradientToUserSpace (const QBrush &brush, const QRectF &boundingRect)
Macro Definition Documentation
QGradient_StretchToDevice
#define QGradient_StretchToDevice 0x10000000
Definition at line 82 of file qpainter.cpp.
Referenced by QPainterPrivate::draw_helper(), line_emulation(), and QPainterPrivate::updateEmulationSpecifier().
QPaintEngine_OpaqueBackground
#define QPaintEngine_OpaqueBackground 0x40000000
Definition at line 83 of file qpainter.cpp.
Referenced by QPainterPrivate::draw_helper(), line_emulation(), and QPainterPrivate::updateEmulationSpecifier().
Typedef Documentation
QPaintDeviceRedirectionList
typedef QList<QPaintDeviceRedirection> QPaintDeviceRedirectionList
Definition at line 8262 of file qpainter.cpp.
Function Documentation
check_gradient()
static bool check_gradient (const QBrush & brush) inline static
Definition at line 120 of file qpainter.cpp.
 {
     return coordinateMode(brush) == QGradient::StretchToDeviceMode;
 }
coordinateMode()
static QGradient::CoordinateMode coordinateMode (const QBrush & brush) inline static
Definition at line 106 of file qpainter.cpp.
Referenced by check_gradient(), QPainterPrivate::drawStretchedGradient(), QGradient::spread(), and QPainterPrivate::updateEmulationSpecifier().
 {
     switch (brush.style()) {
     case Qt::LinearGradientPattern:
     case Qt::RadialGradientPattern:
     case Qt::ConicalGradientPattern:
         return brush.gradient()->coordinateMode();
     default:
         ;
     }
     return QGradient::LogicalMode;
 }
drawTextItemDecoration()
static void drawTextItemDecoration (QPainter * painter, const QPointF & pos, const QFontEngine * fe, QTextCharFormat::UnderlineStyle underlineStyle, QTextItem::RenderFlags flags, qreal width, const QTextCharFormat & charFormat) static
Definition at line 6738 of file qpainter.cpp.
Referenced by QPainterPrivate::drawGlyphs(), QPainter::drawTextItem(), and qt_draw_decoration_for_glyphs().
 {
     if (underlineStyle == QTextCharFormat::NoUnderline
         && !(flags & (QTextItem::StrikeOut | QTextItem::Overline)))
         return;
     const QPen oldPen = painter->pen();
     const QBrush oldBrush = painter->brush();
     painter->setBrush(Qt::NoBrush);
     QPen pen = oldPen;
     pen.setStyle(Qt::SolidLine);
     pen.setWidthF(fe->lineThickness().toReal());
     pen.setCapStyle(Qt::FlatCap);
     QLineF line(pos.x(), pos.y(), pos.x() + qFloor(width), pos.y());
     qreal underlineOffset = fe->underlinePosition().toReal();
     qreal y = pos.y();
     // compensate for different rounding rule in Core Graphics paint engine,
     // ideally code like this should be moved to respective engines.
     if (painter->paintEngine()->type() == QPaintEngine::CoreGraphics) {
         y = qCeil(y);
     }
     // deliberately ceil the offset to avoid the underline coming too close to
     // the text above it.
     const qreal underlinePos = y + qCeil(underlineOffset);
     if (underlineStyle == QTextCharFormat::SpellCheckUnderline) {
         underlineStyle = QTextCharFormat::UnderlineStyle(QApplication::style()->styleHint(QStyle::SH_SpellCheckUnderlineStyle));
     }
     if (underlineStyle == QTextCharFormat::WaveUnderline) {
         painter->save();
         painter->translate(0, pos.y() + 1);
         QColor uc = charFormat.underlineColor();
         if (uc.isValid())
             pen.setColor(uc);
         // Adapt wave to underlineOffset or pen width, whatever is larger, to make it work on all platforms
         const QPixmap wave = generateWavyPixmap(qMax(underlineOffset, pen.widthF()), pen);
         const int descent = (int) fe->descent().toReal();
         painter->setBrushOrigin(painter->brushOrigin().x(), 0);
         painter->fillRect(pos.x(), 0, qCeil(width), qMin(wave.height(), descent), wave);
         painter->restore();
     } else if (underlineStyle != QTextCharFormat::NoUnderline) {
         QLineF underLine(line.x1(), underlinePos, line.x2(), underlinePos);
         QColor uc = charFormat.underlineColor();
         if (uc.isValid())
             pen.setColor(uc);
         pen.setStyle((Qt::PenStyle)(underlineStyle));
         painter->setPen(pen);
         painter->drawLine(underLine);
     }
     pen.setStyle(Qt::SolidLine);
     pen.setColor(oldPen.color());
     if (flags & QTextItem::StrikeOut) {
         QLineF strikeOutLine = line;
         strikeOutLine.translate(0., - fe->ascent().toReal() / 3.);
         painter->setPen(pen);
         painter->drawLine(strikeOutLine);
     }
     if (flags & QTextItem::Overline) {
         QLineF overLine = line;
         overLine.translate(0., - fe->ascent().toReal());
         painter->setPen(pen);
         painter->drawLine(overLine);
     }
     painter->setPen(oldPen);
     painter->setBrush(oldBrush);
 }
generateWavyPixmap()
static QPixmap generateWavyPixmap (qreal maxRadius, const QPen & pen) static
Definition at line 6687 of file qpainter.cpp.
Referenced by drawTextItemDecoration().
 {
     const qreal radiusBase = qMax(qreal(1), maxRadius);
     QString key = QLatin1Literal("WaveUnderline-")
                   % pen.color().name()
                   % HexString<qreal>(radiusBase);
     QPixmap pixmap;
     if (QPixmapCache::find(key, pixmap))
         return pixmap;
     const qreal halfPeriod = qMax(qreal(2), qreal(radiusBase * 1.61803399)); // the golden ratio
     const int width = qCeil(100 / (2 * halfPeriod)) * (2 * halfPeriod);
     const int radius = qFloor(radiusBase);
     QPainterPath path;
     qreal xs = 0;
     qreal ys = radius;
     while (xs < width) {
         xs += halfPeriod;
         ys = -ys;
         path.quadTo(xs - halfPeriod / 2, ys, xs, 0);
     }
     pixmap = QPixmap(width, radius * 2);
     pixmap.fill(Qt::transparent);
     {
         QPen wavePen = pen;
         wavePen.setCapStyle(Qt::SquareCap);
         // This is to protect against making the line too fat, as happens on Mac OS X
         // due to it having a rather thick width for the regular underline.
         const qreal maxPenWidth = .8 * radius;
         if (wavePen.widthF() > maxPenWidth)
             wavePen.setWidth(maxPenWidth);
         QPainter imgPainter(&pixmap);
         imgPainter.setPen(wavePen);
         imgPainter.setRenderHint(QPainter::Antialiasing);
         imgPainter.translate(0, radius);
         imgPainter.drawPath(path);
     }
     QPixmapCache::insert(key, pixmap);
     return pixmap;
 }
is_brush_transparent()
static bool is_brush_transparent (const QBrush & brush) inline static
Definition at line 127 of file qpainter.cpp.
Referenced by is_pen_transparent(), and QPainterPrivate::updateEmulationSpecifier().
{
     Qt::BrushStyle s = brush.style();
     bool brushBitmap = qHasPixmapTexture(brush)
                        ? brush.texture().isQBitmap()
                        : (brush.textureImage().depth() == 1);
     return ((s >= Qt::Dense1Pattern && s <= Qt::DiagCrossPattern)
             || (s == Qt::TexturePattern && brushBitmap));
 }
is_pen_transparent()
static bool is_pen_transparent (const QPen & pen) inline static
Definition at line 136 of file qpainter.cpp.
Referenced by QPainterPrivate::updateEmulationSpecifier().
{
     return pen.style() > Qt::SolidLine || is_brush_transparent(pen.brush());
 }
line_emulation()
static uint line_emulation (uint emulation) inline static
Definition at line 143 of file qpainter.cpp.
Referenced by QPainter::drawLines(), and QPainter::drawPolyline().
 {
     return emulation & (QPaintEngine::PrimitiveTransform
                         | QPaintEngine::AlphaBlend
                         | QPaintEngine::Antialiasing
                         | QPaintEngine::BrushStroke
                         | QPaintEngine::ConstantOpacity
                         | QGradient_StretchToDevice
                         | QPaintEngine::ObjectBoundingModeGradients
                         | QPaintEngine_OpaqueBackground);
 }
needsResolving()
static bool needsResolving (const QBrush & brush) inline static
Definition at line 7339 of file qpainter.cpp.
Referenced by QPaintEngineState::brushNeedsResolving(), QPaintEngineState::penNeedsResolving(), and QOpenGLPaintEnginePrivate::setGLBrush().
 {
     Qt::BrushStyle s = brush.style();
     return ((s == Qt::LinearGradientPattern || s == Qt::RadialGradientPattern ||
              s == Qt::ConicalGradientPattern) &&
             brush.gradient()->coordinateMode() == QGradient::ObjectBoundingMode);
 }
qHasPixmapTexture()
bool qHasPixmapTexture (const QBrush &)
Definition at line 223 of file qbrush.cpp.
Referenced by check_gradient(), is_brush_transparent(), and QPainterPrivate::updateEmulationSpecifier().
 {
     if (brush.style() != Qt::TexturePattern)
         return false;
     QTexturedBrushData *tx_data = static_cast<QTexturedBrushData *>(brush.d.data());
     return tx_data->m_has_pixmap_texture;
 }
qt_cleanup_painter_state()
static void qt_cleanup_painter_state (QPainterPrivate * d) inline static
Definition at line 1714 of file qpainter.cpp.
Referenced by QPainter::begin(), and QPainter::end().
 {
     d->states.clear();
     delete d->state;
     d->state = 0;
     d->engine = 0;
     d->device = 0;
 }
qt_draw_decoration_for_glyphs()
Q_GUI_EXPORT void qt_draw_decoration_for_glyphs (QPainter * painter, const glyph_t * glyphArray, const QFixedPoint * positions, int glyphCount, QFontEngine * fontEngine, const QFont & font, const QTextCharFormat & charFormat)
Definition at line 6820 of file qpainter.cpp.
Referenced by QDeclarativeTextLayout::draw(), QPainter::drawStaticText(), and QDeclarativeTextLayout::prepare().
 {
     if (!(font.underline() || font.strikeOut() || font.overline()))
         return;
     QFixed leftMost;
     QFixed rightMost;
     QFixed baseLine;
     for (int i=0; i<glyphCount; ++i) {
         glyph_metrics_t gm = fontEngine->boundingBox(glyphArray[i]);
         if (i == 0 || leftMost > positions[i].x)
             leftMost = positions[i].x;
         // We don't support glyphs that do not share a common baseline. If this turns out to
         // be a relevant use case, then we need to find clusters of glyphs that share a baseline
         // and do a drawTextItemDecorations call per cluster.
         if (i == 0 || baseLine < positions[i].y)
             baseLine = positions[i].y;
         // We use the advance rather than the actual bounds to match the algorithm in drawText()
         if (i == 0 || rightMost < positions[i].x + gm.xoff)
             rightMost = positions[i].x + gm.xoff;
     }
     QFixed width = rightMost - leftMost;
     QTextItem::RenderFlags flags = 0;
     if (font.underline())
         flags |= QTextItem::Underline;
     if (font.overline())
         flags |= QTextItem::Overline;
     if (font.strikeOut())
         flags |= QTextItem::StrikeOut;
     drawTextItemDecoration(painter, QPointF(leftMost.toReal(), baseLine.toReal()),
                            fontEngine,
                            font.underline() ? QTextCharFormat::SingleUnderline
                                             : QTextCharFormat::NoUnderline, flags,
                            width.toReal(), charFormat);
 }
qt_draw_helper()
void qt_draw_helper (QPainterPrivate * p, const QPainterPath & path, QPainterPrivate::DrawOperation operation)
Definition at line 9937 of file qpainter.cpp.
Referenced by QVGPaintEngine::fill(), and QOpenGLPaintEngine::fill().
 {
     p->draw_helper(path, operation);
 }
qt_format_text() [1/2]
void qt_format_text (const QFont & font, const QRectF & _r, int tf, const QTextOption * option, const QString & str, QRectF * brect, int tabstops, int * tabarray, int tabarraylen, QPainter * painter)
Definition at line 8458 of file qpainter.cpp.
Referenced by QPainter::boundingRect(), QPainter::drawText(), QPicture::exec(), QPainterReplayer::process(), and qt_format_text().
 {
     Q_ASSERT( !((tf & ~Qt::TextDontPrint)!=0 && option!=0) ); // we either have an option or flags
     if (option) {
         tf |= option->alignment();
         if (option->wrapMode() != QTextOption::NoWrap)
             tf |= Qt::TextWordWrap;
         if (option->flags() & QTextOption::IncludeTrailingSpaces)
             tf |= Qt::TextIncludeTrailingSpaces;
         if (option->tabStop() >= 0 || !option->tabArray().isEmpty())
             tf |= Qt::TextExpandTabs;
     }
     // we need to copy r here to protect against the case (&r == brect).
     QRectF r(_r);
     bool dontclip  = (tf & Qt::TextDontClip);
     bool wordwrap  = (tf & Qt::TextWordWrap) || (tf & Qt::TextWrapAnywhere);
     bool singleline = (tf & Qt::TextSingleLine);
     bool showmnemonic = (tf & Qt::TextShowMnemonic);
     bool hidemnmemonic = (tf & Qt::TextHideMnemonic);
     Qt::LayoutDirection layout_direction;
     if (tf & Qt::TextForceLeftToRight)
         layout_direction = Qt::LeftToRight;
     else if (tf & Qt::TextForceRightToLeft)
         layout_direction = Qt::RightToLeft;
     else if (option)
         layout_direction = option->textDirection();
     else if (painter)
         layout_direction = painter->layoutDirection();
     else
         layout_direction = Qt::LeftToRight;
     tf = QStyle::visualAlignment(layout_direction, QFlag(tf));
     bool isRightToLeft = layout_direction == Qt::RightToLeft;
     bool expandtabs = ((tf & Qt::TextExpandTabs) &&
                         (((tf & Qt::AlignLeft) && !isRightToLeft) ||
                           ((tf & Qt::AlignRight) && isRightToLeft)));
     if (!painter)
         tf |= Qt::TextDontPrint;
     uint maxUnderlines = 0;
     int numUnderlines = 0;
     QVarLengthArray<int, 32> underlinePositions(1);
     QFontMetricsF fm(fnt);
     QString text = str;
     int offset = 0;
 start_lengthVariant:
     bool hasMoreLengthVariants = false;
     // compatible behaviour to the old implementation. Replace
     // tabs by spaces
     int old_offset = offset;
     for (; offset < text.length(); offset++) {
         QChar chr = text.at(offset);
         if (chr == QLatin1Char('\r') || (singleline && chr == QLatin1Char('\n'))) {
             text[offset] = QLatin1Char(' ');
         } else if (chr == QLatin1Char('\n')) {
             text[offset] = QChar::LineSeparator;
         } else if (chr == QLatin1Char('&')) {
             ++maxUnderlines;
         } else if (chr == QLatin1Char('\t')) {
             if (!expandtabs) {
                 text[offset] = QLatin1Char(' ');
             } else if (!tabarraylen && !tabstops) {
                 tabstops = qRound(fm.width(QLatin1Char('x'))*8);
             }
         } else if (chr == QChar(ushort(0x9c))) {
             // string with multiple length variants
             hasMoreLengthVariants = true;
             break;
         }
     }
     int length = offset - old_offset;
     if ((hidemnmemonic || showmnemonic) && maxUnderlines > 0) {
         underlinePositions.resize(maxUnderlines + 1);
         QChar *cout = text.data() + old_offset;
         QChar *cin = cout;
         int l = length;
         while (l) {
             if (*cin == QLatin1Char('&')) {
                 ++cin;
                 --length;
                 --l;
                 if (!l)
                     break;
                 if (*cin != QLatin1Char('&') && !hidemnmemonic)
                     underlinePositions[numUnderlines++] = cout - text.data() - old_offset;
             }
             *cout = *cin;
             ++cout;
             ++cin;
             --l;
         }
     }
     // no need to do extra work for underlines if we don't paint
     if (tf & Qt::TextDontPrint)
         numUnderlines = 0;
     underlinePositions[numUnderlines] = -1;
     qreal height = 0;
     qreal width = 0;
     QString finalText = text.mid(old_offset, length);
     QStackTextEngine engine(finalText, fnt);
     if (option) {
         engine.option = *option;
     }
     if (engine.option.tabStop() < 0 && tabstops > 0)
         engine.option.setTabStop(tabstops);
     if (engine.option.tabs().isEmpty() && ta) {
         QList<qreal> tabs;
         for (int i = 0; i < tabarraylen; i++)
             tabs.append(qreal(ta[i]));
         engine.option.setTabArray(tabs);
     }
     engine.option.setTextDirection(layout_direction);
     if (tf & Qt::AlignJustify)
         engine.option.setAlignment(Qt::AlignJustify);
     else
         engine.option.setAlignment(Qt::AlignLeft); // do not do alignment twice
     if (!option && (tf & Qt::TextWrapAnywhere))
         engine.option.setWrapMode(QTextOption::WrapAnywhere);
     if (tf & Qt::TextJustificationForced)
         engine.forceJustification = true;
     QTextLayout textLayout(&engine);
     textLayout.setCacheEnabled(true);
     textLayout.engine()->underlinePositions = underlinePositions.data();
     if (finalText.isEmpty()) {
         height = fm.height();
         width = 0;
         tf |= Qt::TextDontPrint;
     } else {
         qreal lineWidth = 0x01000000;
         if (wordwrap || (tf & Qt::TextJustificationForced))
             lineWidth = qMax<qreal>(0, r.width());
         if(!wordwrap)
             tf |= Qt::TextIncludeTrailingSpaces;
         textLayout.engine()->ignoreBidi = bool(tf & Qt::TextDontPrint);
         textLayout.beginLayout();
         qreal leading = fm.leading();
         height = -leading;
         while (1) {
             QTextLine l = textLayout.createLine();
             if (!l.isValid())
                 break;
             l.setLineWidth(lineWidth);
             height += leading;
             l.setPosition(QPointF(0., height));
             height += l.height();
             width = qMax(width, l.naturalTextWidth());
             if (!dontclip && !brect && height >= r.height())
                 break;
         }
         textLayout.endLayout();
     }
     qreal yoff = 0;
     qreal xoff = 0;
     if (tf & Qt::AlignBottom) {
         yoff = r.height() - height;
     } else if (tf & Qt::AlignVCenter) {
         yoff = (r.height() - height)/2;
         if (painter) {
             QTransform::TransformationType type = painter->transform().type();
             if (type <= QTransform::TxScale) {
                 // do the rounding manually to work around inconsistencies
                 // in the paint engines when drawing on floating point offsets
                 const qreal scale = painter->transform().m22();
                 if (scale != 0)
                     yoff = -qRound(-yoff * scale) / scale;
             }
         }
     }
     if (tf & Qt::AlignRight) {
         xoff = r.width() - width;
     } else if (tf & Qt::AlignHCenter) {
         xoff = (r.width() - width)/2;
         if (painter) {
             QTransform::TransformationType type = painter->transform().type();
             if (type <= QTransform::TxScale) {
                 // do the rounding manually to work around inconsistencies
                 // in the paint engines when drawing on floating point offsets
                 const qreal scale = painter->transform().m11();
                 if (scale != 0)
                     xoff = qRound(xoff * scale) / scale;
             }
         }
     }
     QRectF bounds = QRectF(r.x() + xoff, r.y() + yoff, width, height);
     if (hasMoreLengthVariants && !(tf & Qt::TextLongestVariant) && !r.contains(bounds)) {
         offset++;
         goto start_lengthVariant;
     }
     if (brect)
         *brect = bounds;
     if (!(tf & Qt::TextDontPrint)) {
         bool restore = false;
         if (!dontclip && !r.contains(bounds)) {
             restore = true;
             painter->save();
             painter->setClipRect(r, Qt::IntersectClip);
         }
         for (int i = 0; i < textLayout.lineCount(); i++) {
             QTextLine line = textLayout.lineAt(i);
             qreal advance = line.horizontalAdvance();
             xoff = 0;
             if (tf & Qt::AlignRight) {
                 QTextEngine *eng = textLayout.engine();
                 xoff = r.width() - advance -
                     eng->leadingSpaceWidth(eng->lines[line.lineNumber()]).toReal();
             }
             else if (tf & Qt::AlignHCenter)
                 xoff = (r.width() - advance) / 2;
             line.draw(painter, QPointF(r.x() + xoff, r.y() + yoff));
         }
         if (restore) {
             painter->restore();
         }
     }
 }
qt_format_text() [2/2]
void qt_format_text (const QFont & fnt, const QRectF & _r, int tf, const QString & str, QRectF * brect, int tabstops, int * ta, int tabarraylen, QPainter * painter)
Definition at line 8448 of file qpainter.cpp.
Referenced by QFontMetrics::boundingRect(), and QFontMetricsF::boundingRect().
 {
     qt_format_text(fnt, _r,
                     tf, 0, str, brect,
                     tabstops, ta, tabarraylen,
                     painter);
 }
qt_isExtendedRadialGradient()
Q_GUI_EXPORT bool qt_isExtendedRadialGradient (const QBrush & brush)
Definition at line 881 of file qbrush.cpp.
Referenced by QPainterPrivate::updateEmulationSpecifier(), and QPainterPrivate::updateInvMatrix().
 {
     if (brush.style() == Qt::RadialGradientPattern) {
         const QGradient *g = brush.gradient();
         const QRadialGradient *rg = static_cast<const QRadialGradient *>(g);
         if (!qFuzzyIsNull(rg->focalRadius()))
             return true;
         QPointF delta = rg->focalPoint() - rg->center();
         if (delta.x() * delta.x() + delta.y() * delta.y() > rg->radius() * rg->radius())
             return true;
     }
     return false;
 }
qt_painter_removePaintDevice()
void qt_painter_removePaintDevice (QPaintDevice * dev)
Definition at line 8419 of file qpainter.cpp.
Referenced by QPaintDevice::~QPaintDevice().
 {
     if (!globalRedirectionAtomic() || *globalRedirectionAtomic() == 0)
         return;
     QMutex *mutex = 0;
     QT_TRY {
         mutex = globalRedirectionsMutex();
     } QT_CATCH(...) {
         // ignore the missing mutex, since we could be called from
         // a destructor, and destructors shall not throw
     }
     QMutexLocker locker(mutex);
     QPaintDeviceRedirectionList *redirections = 0;
     QT_TRY {
         redirections = globalRedirections();
     } QT_CATCH(...) {
         // do nothing - code below is safe with redirections being 0.
     }
     if (redirections) {
         for (int i = 0; i < redirections->size(); ) {
             if(redirections->at(i) == dev || redirections->at(i).replacement == dev)
                 redirections->removeAt(i);
             else
                 ++i;
         }
     }
 }
qt_painter_thread_test()
static bool qt_painter_thread_test (int devType, const char * what, bool extraCondition = false) static
Definition at line 156 of file qpainter.cpp.
Referenced by QPainter::drawPixmap(), QPainter::drawTextItem(), and QPainter::drawTiledPixmap().
 {
     switch (devType) {
     case QInternal::Image:
     case QInternal::Printer:
     case QInternal::Picture:
         // can be drawn onto these devices safely from any thread
 #ifndef Q_WS_WIN
         if (extraCondition)
 #endif
             break;
     default:
 #ifdef Q_WS_X11
         if (QApplication::testAttribute(Qt::AA_X11InitThreads))
             return true;
 #endif
         if (!extraCondition && QThread::currentThread() != qApp->thread()) {
             qWarning("QPainter: It is not safe to use %s outside the GUI thread", what);
             return false;
         }
         break;
     }
     return true;
 }
qt_pixmapForBrush()
QPixmap qt_pixmapForBrush (int style, bool invert)
Definition at line 99 of file qbrush.cpp.
 {
     QPixmap pm;
     QString key = QLatin1Literal("$qt-brush$")
                   % HexString<uint>(brushStyle)
                   % QLatin1Char(invert ? '1' : '0');
     if (!QPixmapCache::find(key, pm)) {
         pm = QBitmap::fromData(QSize(8, 8), qt_patternForBrush(brushStyle, invert),
                                QImage::Format_MonoLSB);
         QPixmapCache::insert(key, pm);
     }
     return pm;
 }
qt_regionToPath()
Q_AUTOTEST_EXPORT QPainterPath qt_regionToPath (const QRegion & region)
Definition at line 1160 of file qregion.cpp.
Referenced by QPainter::clipPath(), and QPainter::clipRegion().
 {
     QPainterPath result;
     if (region.rectCount() == 1) {
         result.addRect(region.boundingRect());
         return result;
     }
     const QVector<QRect> rects = region.rects();
     QVarLengthArray<Segment> segments;
     segments.resize(4 * rects.size());
     const QRect *rect = rects.constData();
     const QRect *end = rect + rects.size();
     int lastRowSegmentCount = 0;
     Segment *lastRowSegments = 0;
     int lastSegment = 0;
     int lastY = 0;
     while (rect != end) {
         const int y = rect[0].y();
         int count = 0;
         while (&rect[count] != end && rect[count].y() == y)
             ++count;
         for (int i = 0; i < count; ++i) {
             int offset = lastSegment + i;
             segments[offset] = Segment(rect[i].topLeft());
             segments[offset += count] = Segment(rect[i].topRight() + QPoint(1, 0));
             segments[offset += count] = Segment(rect[i].bottomRight() + QPoint(1, 1));
             segments[offset += count] = Segment(rect[i].bottomLeft() + QPoint(0, 1));
             offset = lastSegment + i;
             for (int j = 0; j < 4; ++j)
                 segments[offset + j * count].connect(segments[offset + ((j + 1) % 4) * count]);
         }
         if (lastRowSegments && lastY == y)
             mergeSegments(lastRowSegments, lastRowSegmentCount, &segments[lastSegment], count);
         lastRowSegments = &segments[lastSegment + 2 * count];
         lastRowSegmentCount = count;
         lastSegment += 4 * count;
         lastY = y + rect[0].height();
         rect += count;
     }
     for (int i = 0; i < lastSegment; ++i) {
         Segment *segment = &segments[i];
         if (!segment->added)
             addSegmentsToPath(segment, result);
     }
     return result;
 }
roundInDeviceCoordinates()
static QPointF roundInDeviceCoordinates (const QPointF & p, const QTransform & m) inline static
Definition at line 5518 of file qpainter.cpp.
Referenced by QPainter::drawImage(), QPainter::drawPixmap(), and QPainter::drawTiledPixmap().
 {
     return m.inverted().map(QPointF(m.map(p).toPoint()));
 }
stretchGradientToUserSpace()
static QBrush stretchGradientToUserSpace (const QBrush & brush, const QRectF & boundingRect) inline static
Definition at line 531 of file qpainter.cpp.
Referenced by QPainterPrivate::drawStretchedGradient().
 {
     Q_ASSERT(brush.style() >= Qt::LinearGradientPattern
              && brush.style() <= Qt::ConicalGradientPattern);
     QTransform gradientToUser(boundingRect.width(), 0, 0, boundingRect.height(),
                               boundingRect.x(), boundingRect.y());
     QGradient g = *brush.gradient();
     g.setCoordinateMode(QGradient::LogicalMode);
     QBrush b(g);
     b.setTransform(gradientToUser * b.transform());
     return b;
 }