Qt 4.8: /src/gui/painting/qpainter_p.h File Reference
qpainter_p.h File Reference
#include "QtGui/qbrush.h"
#include "QtGui/qfont.h"
#include "QtGui/qpen.h"
#include "QtGui/qregion.h"
#include "QtGui/qmatrix.h"
#include "QtGui/qpainter.h"
#include "QtGui/qpainterpath.h"
#include "QtGui/qpaintengine.h"
#include <QtCore/qhash.h>
#include <private/qpen_p.h>
Classes
struct DataPtrContainer
class QPainterClipInfo
struct QPainterDummyState
class QPainterPrivate
class QPainterState
Functions
void * data_ptr (const QTransform &t)
QPen::DataPtr & data_ptr (const QPen &p)
QBrush::DataPtr & data_ptr (const QBrush &p)
const QColor & qbrush_color (const QBrush &b)
bool qbrush_fast_equals (const QBrush &a, const QBrush &b)
bool qbrush_has_transform (const QBrush &b)
Qt::BrushStyle qbrush_style (const QBrush &b)
QBrush qpen_brush (const QPen &p)
Qt::PenCapStyle qpen_capStyle (const QPen &p)
bool qpen_fast_equals (const QPen &a, const QPen &b)
Qt::PenJoinStyle qpen_joinStyle (const QPen &p)
Qt::PenStyle qpen_style (const QPen &p)
qreal qpen_widthf (const QPen &p)
Q_GUI_EXPORT void qt_draw_helper (QPainterPrivate *p, const QPainterPath &path, QPainterPrivate::DrawOperation operation)
QString qt_generate_brush_key (const QBrush &brush)
bool qtransform_fast_equals (const QTransform &a, const QTransform &b)
Function Documentation
data_ptr() [1/3]
void* data_ptr (const QTransform & t) inline
Definition at line 81 of file qpainter_p.h.
Referenced by QRasterPixmapData::createPixmapForImage(), QEgl::createSurface(), data_ptr(), QGLContextPrivate::eglSurfaceForDevice(), QImagePixmapCleanupHooks::enableCleanupHooks(), QMeeGoPixmapData::fromEGLSharedImage(), QDirectFBPaintEnginePrivate::getSurface(), QX11AlphaDetector::hasAlpha(), QMeeGoPixmapData::imageToEGLSharedImage(), QSpanData::initTexture(), QImagePixmapCleanupHooks::isImageCached(), QImagePixmapCleanupHooks::isPixmapCached(), QMeeGoGraphicsSystem::pixmapDataFromEGLSharedImage(), qbrush_color(), qbrush_fast_equals(), qbrush_has_transform(), qbrush_style(), qpaintbuffer_storable_image(), qpen_brush(), qpen_capStyle(), qpen_fast_equals(), qpen_joinStyle(), qpen_style(), qpen_widthf(), qtransform_fast_equals(), QRasterPixmapData::toImage(), and QGLPixmapData::toImage().
 { return (DataPtrContainer *) &t; }
data_ptr() [2/3]
QPen::DataPtr& data_ptr (const QPen & p) inline
Definition at line 85 of file qpainter_p.h.
 { return const_cast<QPen &>(p).data_ptr(); }
data_ptr() [3/3]
QBrush::DataPtr& data_ptr (const QBrush & p) inline
Definition at line 94 of file qpainter_p.h.
 { return const_cast<QBrush &>(p).data_ptr(); }
qbrush_color()
const QColor& qbrush_color (const QBrush & b) inline
Definition at line 97 of file qpainter_p.h.
Referenced by QBlitterPaintEngine::drawRects(), QBlitterPaintEngine::fillRect(), QSpanData::setup(), and QBlitterPaintEnginePrivate::updateBrushState().
 { return data_ptr(b)->color; }
qbrush_fast_equals()
bool qbrush_fast_equals (const QBrush & a, const QBrush & b) inline
Definition at line 95 of file qpainter_p.h.
Referenced by QRasterPaintEngine::ensureBrush(), and QGL2PaintEngineExPrivate::setBrush().
 { return data_ptr(a) == data_ptr(b); }
qbrush_has_transform()
bool qbrush_has_transform (const QBrush & b) inline
Definition at line 98 of file qpainter_p.h.
 { return data_ptr(b)->transform.type() > QTransform::TxNone; }
qbrush_style()
Qt::BrushStyle qbrush_style (const QBrush & b) inline
Definition at line 96 of file qpainter_p.h.
Referenced by QVGPaintEnginePrivate::draw(), QPaintEngineEx::draw(), QPaintBufferEngine::draw(), QEmulationPaintEngine::drawTextItem(), QEmulationPaintEngine::fill(), QGL2PaintEngineEx::fill(), QBlitterPaintEngine::fillRect(), QGL2PaintEngineExPrivate::setBrush(), QSpanData::setup(), QEmulationPaintEngine::stroke(), QGL2PaintEngineEx::stroke(), QPaintEngineEx::stroke(), QBlitterPaintEnginePrivate::updateBrushState(), and QPainterPrivate::updateEmulationSpecifier().
 { return data_ptr(b)->style; }
qpen_brush()
QBrush qpen_brush (const QPen & p) inline
Definition at line 87 of file qpainter_p.h.
Referenced by QPainterPrivate::checkEmulation(), QVGPaintEnginePrivate::draw(), QPaintEngineEx::draw(), QPaintBufferEngine::draw(), QGL2PaintEngineEx::stroke(), QGL2PaintEngineExPrivate::stroke(), QPainter::strokePath(), and QPainterPrivate::updateEmulationSpecifier().
 { return data_ptr(p)->brush; }
qpen_capStyle()
Qt::PenCapStyle qpen_capStyle (const QPen & p) inline
Definition at line 90 of file qpainter_p.h.
Referenced by QTriangulatingStroker::process(), and QRasterPaintEngine::updatePen().
 { return data_ptr(p)->capStyle; }
qpen_fast_equals()
bool qpen_fast_equals (const QPen & a, const QPen & b) inline
Definition at line 86 of file qpainter_p.h.
Referenced by QRasterPaintEngine::ensurePen(), and QPaintEngineEx::stroke().
 { return data_ptr(a) == data_ptr(b); }
qpen_joinStyle()
Qt::PenJoinStyle qpen_joinStyle (const QPen & p) inline
Definition at line 91 of file qpainter_p.h.
Referenced by QTriangulatingStroker::process(), and QRasterPaintEngine::updatePen().
 { return data_ptr(p)->joinStyle; }
qpen_style()
Qt::PenStyle qpen_style (const QPen & p) inline
Definition at line 89 of file qpainter_p.h.
Referenced by QVGPaintEnginePrivate::draw(), QPaintEngineEx::draw(), QPaintBufferEngine::draw(), QRasterPaintEngine::drawEllipse(), QGL2PaintEngineEx::stroke(), QRasterPaintEngine::stroke(), QGL2PaintEngineExPrivate::stroke(), QPainterPrivate::updateEmulationSpecifier(), QRasterPaintEngine::updatePen(), and QBlitterPaintEnginePrivate::updatePenState().
 { return data_ptr(p)->style; }
qpen_widthf()
qreal qpen_widthf (const QPen & p) inline
Definition at line 88 of file qpainter_p.h.
Referenced by QTriangulatingStroker::process(), QDashedStrokeProcessor::process(), QRasterPaintEngine::stroke(), QGL2PaintEngineExPrivate::stroke(), and QRasterPaintEngine::updatePen().
 { return data_ptr(p)->width; }
qt_draw_helper()
Q_GUI_EXPORT void qt_draw_helper (QPainterPrivate * p, const QPainterPath & path, QPainterPrivate::DrawOperation operation)
Definition at line 9937 of file qpainter.cpp.
Referenced by QVGPaintEngine::fill(), and QOpenGLPaintEngine::fill().
 {
     p->draw_helper(path, operation);
 }
qt_generate_brush_key()
QString qt_generate_brush_key (const QBrush & brush)
qtransform_fast_equals()
bool qtransform_fast_equals (const QTransform & a, const QTransform & b) inline
Definition at line 82 of file qpainter_p.h.
 { return data_ptr(a) == data_ptr(b); }