Qt 4.8: /src/gui/painting/qpaintdevice_mac.cpp File Reference
qpaintdevice_mac.cpp File Reference
#include "qpaintdevice.h"
#include "qpainter.h"
#include "qwidget.h"
#include "qbitmap.h"
#include "qapplication.h"
#include "qprinter.h"
#include <qdebug.h>
#include <private/qt_mac_p.h>
#include <private/qprintengine_mac_p.h>
#include <private/qpixmap_mac_p.h>
#include <private/qpixmap_raster_p.h>
Functions
Q_GUI_EXPORT CGContextRef qt_mac_cg_context (const QPaintDevice *pdev)
Returns the CoreGraphics CGContextRef of the paint device.
CGColorSpaceRef qt_mac_colorSpaceForDeviceType (const QPaintDevice *pdev)
float qt_mac_defaultDpi_x ()
float qt_mac_defaultDpi_y ()
Q_GUI_EXPORT GrafPtr qt_mac_qd_context (const QPaintDevice *device)
Returns the QuickDraw CGrafPtr of the paint device.
Function Documentation
qt_mac_cg_context()
Q_GUI_EXPORT CGContextRef qt_mac_cg_context (const QPaintDevice * pdev)
Returns the CoreGraphics CGContextRef of the paint device.
Warning
This function is not part of the public interface.
0 is returned if it can't be obtained. It is the caller's responsiblity to CGContextRelease the context when finished using it.
Warning
This function is only available on Mac OS X.
Definition at line 118 of file qpaintdevice_mac.cpp.
Referenced by QCoreGraphicsPaintEngine::begin(), getTabDirection(), QMacStyle::polish(), QMacCGContext::QMacCGContext(), qt_mac_convert_iconref(), qt_mac_draw_pattern(), qt_mac_fill_background(), and QMacWindowSurface::scroll().
 {
     if (pdev->devType() == QInternal::Pixmap) {
         const QPixmap *pm = static_cast<const QPixmap*>(pdev);
         CGColorSpaceRef colorspace = qt_mac_colorSpaceForDeviceType(pdev);
         uint flags = kCGImageAlphaPremultipliedFirst;
 #ifdef kCGBitmapByteOrder32Host //only needed because CGImage.h added symbols in the minor version
         flags |= kCGBitmapByteOrder32Host;
 #endif
         CGContextRef ret = 0;
         // It would make sense to put this into a mac #ifdef'ed
         // virtual function in the QPixmapData at some point
         if (pm->data->classId() == QPixmapData::MacClass) {
             const QMacPixmapData *pmData = static_cast<const QMacPixmapData*>(pm->data.data());
             ret = CGBitmapContextCreate(pmData->pixels, pmData->w, pmData->h,
                                                      8, pmData->bytesPerRow, colorspace,
                                                      flags);
             if(!ret)
                 qWarning("QPaintDevice: Unable to create context for pixmap (%d/%d/%d)",
                          pmData->w, pmData->h, (pmData->bytesPerRow * pmData->h));
         } else if (pm->data->classId() == QPixmapData::RasterClass) {
             QImage *image = pm->data->buffer();
             ret = CGBitmapContextCreate(image->bits(), image->width(), image->height(),
                                         8, image->bytesPerLine(), colorspace, flags);
         }
         CGContextTranslateCTM(ret, 0, pm->height());
         CGContextScaleCTM(ret, 1, -1);
         return ret;
     } else if (pdev->devType() == QInternal::Widget) {
         CGContextRef ret = static_cast<CGContextRef>(static_cast<const QWidget *>(pdev)->macCGHandle());
         CGContextRetain(ret);
         return ret;
     } else if (pdev->devType() == QInternal::MacQuartz) {
         return static_cast<const QMacQuartzPaintDevice *>(pdev)->cgContext();
     }
     return 0;
 }
qt_mac_colorSpaceForDeviceType()
CGColorSpaceRef qt_mac_colorSpaceForDeviceType (const QPaintDevice * pdev)
Definition at line 153 of file qpaintengine_mac.cpp.
Referenced by cgColorForQColor(), QMacCGContext::QMacCGContext(), qt_mac_cg_context(), qt_mac_qd_context(), and QCoreGraphicsPaintEnginePrivate::setFillBrush().
 {
     bool isWidget = (paintDevice->devType() == QInternal::Widget);
     return QCoreGraphicsPaintEngine::macDisplayColorSpace(isWidget ? static_cast<const QWidget *>(paintDevice)
                                                                    : 0);
 }
qt_mac_defaultDpi_x()
float qt_mac_defaultDpi_x ()
Warning
This function is not part of the public interface.
Definition at line 61 of file qpaintdevice_mac.cpp.
Referenced by QMacPixmapData::metric(), QWidget::metric(), qt_defaultDpiX(), qt_mac_pixelsize(), and qt_mac_pointsize().
 {
     // Mac OS X currently assumes things to be 72 dpi.
     // (see http://developer.apple.com/releasenotes/GraphicsImaging/RN-ResolutionIndependentUI/)
     // This may need to be re-worked as we go further in the resolution-independence stuff.
     return 72;
 }
qt_mac_defaultDpi_y()
float qt_mac_defaultDpi_y ()
Warning
This function is not part of the public interface.
Definition at line 70 of file qpaintdevice_mac.cpp.
Referenced by QMacPixmapData::metric(), QWidget::metric(), and qt_defaultDpiY().
 {
     // Mac OS X currently assumes things to be 72 dpi.
     // (see http://developer.apple.com/releasenotes/GraphicsImaging/RN-ResolutionIndependentUI/)
     // This may need to be re-worked as we go further in the resolution-independence stuff.
     return 72;
 }
qt_mac_qd_context()
Q_GUI_EXPORT GrafPtr qt_mac_qd_context (const QPaintDevice * device)
Returns the QuickDraw CGrafPtr of the paint device.
Warning
This function is not part of the public interface.
0 is returned if it can't be obtained. Do not hold the pointer around for long as it can be relocated.
Warning
This function is only available on Mac OS X.
Definition at line 91 of file qpaintdevice_mac.cpp.
 {
     if (device->devType() == QInternal::Pixmap) {
         return static_cast<GrafPtr>(static_cast<const QPixmap *>(device)->macQDHandle());
     } else if(device->devType() == QInternal::Widget) {
         return static_cast<GrafPtr>(static_cast<const QWidget *>(device)->macQDHandle());
     } else if(device->devType() == QInternal::Printer) {
         QPaintEngine *engine = static_cast<const QPrinter *>(device)->paintEngine();
         return static_cast<GrafPtr>(static_cast<const QMacPrintEngine *>(engine)->handle());
     }
     return 0;
 }