Qt 4.8: /src/gui/painting/qpaintengine.cpp File Reference
qpaintengine.cpp File Reference
#include "qpaintengine.h"
#include "qpaintengine_p.h"
#include "qpainter_p.h"
#include "qpolygon.h"
#include "qbitmap.h"
#include "qapplication.h"
#include <qdebug.h>
#include <qmath.h>
#include <private/qtextengine_p.h>
#include <qvarlengtharray.h>
#include <private/qfontengine_p.h>
#include <private/qpaintengineex_p.h>
Classes
struct QT_Point
struct QT_PointF
Functions
void qt_draw_tile (QPaintEngine *gc, qreal x, qreal y, qreal w, qreal h, const QPixmap &pixmap, qreal xOffset, qreal yOffset)
void qt_fill_tile (QPixmap *tile, const QPixmap &pixmap)
Variables
static QPaintEngine * qt_polygon_recursion = 0
Function Documentation
qt_draw_tile()
void qt_draw_tile (QPaintEngine * gc, qreal x, qreal y, qreal w, qreal h, const QPixmap & pixmap, qreal xOffset, qreal yOffset)
Definition at line 600 of file qpaintengine.cpp.
Referenced by QX11PaintEngine::drawTiledPixmap(), QPaintEngine::drawTiledPixmap(), and QX11PaintEngine::handle().
 {
     qreal yPos, xPos, drawH, drawW, yOff, xOff;
     yPos = y;
     yOff = yOffset;
     while(yPos < y + h) {
         drawH = pixmap.height() - yOff;    // Cropping first row
         if (yPos + drawH > y + h)           // Cropping last row
             drawH = y + h - yPos;
         xPos = x;
         xOff = xOffset;
         while(xPos < x + w) {
             drawW = pixmap.width() - xOff; // Cropping first column
             if (xPos + drawW > x + w)           // Cropping last column
                 drawW = x + w - xPos;
             if (drawW > 0 && drawH > 0)
                 gc->drawPixmap(QRectF(xPos, yPos, drawW, drawH), pixmap, QRectF(xOff, yOff, drawW, drawH));
             xPos += drawW;
             xOff = 0;
         }
         yPos += drawH;
         yOff = 0;
     }
 }
qt_fill_tile()
void qt_fill_tile (QPixmap * tile, const QPixmap & pixmap)
Definition at line 584 of file qpaintengine.cpp.
Referenced by QPaintEngine::drawTiledPixmap().
 {
     QPainter p(tile);
     p.drawPixmap(0, 0, pixmap);
     int x = pixmap.width();
     while (x < tile->width()) {
         p.drawPixmap(x, 0, *tile, 0, 0, x, pixmap.height());
         x *= 2;
     }
     int y = pixmap.height();
     while (y < tile->height()) {
         p.drawPixmap(0, y, *tile, 0, 0, tile->width(), y);
         y *= 2;
     }
 }
Variable Documentation
qt_polygon_recursion
QPaintEngine* qt_polygon_recursion = 0 static
Definition at line 344 of file qpaintengine.cpp.