Qt 4.8: /src/corelib/tools/qpair.h File Reference
qpair.h File Reference
#include <QtCore/qdatastream.h>
Classes
struct QPair< T1, T2 >
Functions
template<class T1 , class T2 >
Q_INLINE_TEMPLATE bool operator!= (const QPair< T1, T2 > &p1, const QPair< T1, T2 > &p2)
template<class T1 , class T2 >
Q_INLINE_TEMPLATE bool operator< (const QPair< T1, T2 > &p1, const QPair< T1, T2 > &p2)
template<class T1 , class T2 >
QDataStream & operator<< (QDataStream &s, const QPair< T1, T2 > &p)
template<class T1 , class T2 >
Q_INLINE_TEMPLATE bool operator<= (const QPair< T1, T2 > &p1, const QPair< T1, T2 > &p2)
template<class T1 , class T2 >
Q_INLINE_TEMPLATE bool operator== (const QPair< T1, T2 > &p1, const QPair< T1, T2 > &p2)
template<class T1 , class T2 >
Q_INLINE_TEMPLATE bool operator> (const QPair< T1, T2 > &p1, const QPair< T1, T2 > &p2)
template<class T1 , class T2 >
Q_INLINE_TEMPLATE bool operator>= (const QPair< T1, T2 > &p1, const QPair< T1, T2 > &p2)
template<class T1 , class T2 >
QDataStream & operator>> (QDataStream &s, QPair< T1, T2 > &p)
template<class T1 , class T2 >
Q_OUTOFLINE_TEMPLATE QPair< T1, T2 > qMakePair (const T1 &x, const T2 &y)
Function Documentation
operator!=()
template<class T1 , class T2 > Q_INLINE_TEMPLATE bool operator!= (const QPair< T1, T2 > & p1, const QPair< T1, T2 > & p2)
Definition at line 74 of file qpair.h.
 { return !(p1 == p2); }
operator<()
template<class T1 , class T2 > Q_INLINE_TEMPLATE bool operator< (const QPair< T1, T2 > & p1, const QPair< T1, T2 > & p2)
Definition at line 78 of file qpair.h.
 {
     return p1.first < p2.first || (!(p2.first < p1.first) && p1.second < p2.second);
 }
operator<<()
template<class T1 , class T2 > QDataStream& operator<< (QDataStream & s, const QPair< T1, T2 > & p) inline
Definition at line 116 of file qpair.h.
 {
     s << p.first << p.second;
     return s;
 }
operator<=()
template<class T1 , class T2 > Q_INLINE_TEMPLATE bool operator<= (const QPair< T1, T2 > & p1, const QPair< T1, T2 > & p2)
Definition at line 90 of file qpair.h.
 {
     return !(p2 < p1);
 }
operator==()
template<class T1 , class T2 > Q_INLINE_TEMPLATE bool operator== (const QPair< T1, T2 > & p1, const QPair< T1, T2 > & p2)
Definition at line 70 of file qpair.h.
 { return p1.first == p2.first && p1.second == p2.second; }
operator>()
template<class T1 , class T2 > Q_INLINE_TEMPLATE bool operator> (const QPair< T1, T2 > & p1, const QPair< T1, T2 > & p2)
Definition at line 84 of file qpair.h.
 {
     return p2 < p1;
 }
operator>=()
template<class T1 , class T2 > Q_INLINE_TEMPLATE bool operator>= (const QPair< T1, T2 > & p1, const QPair< T1, T2 > & p2)
Definition at line 96 of file qpair.h.
 {
     return !(p1 < p2);
 }
operator>>()
template<class T1 , class T2 > QDataStream& operator>> (QDataStream & s, QPair< T1, T2 > & p) inline
Definition at line 109 of file qpair.h.
 {
     s >> p.first >> p.second;
     return s;
 }
qMakePair()
template<class T1 , class T2 > Q_OUTOFLINE_TEMPLATE QPair<T1, T2> qMakePair (const T1 & x, const T2 & y)
Definition at line 102 of file qpair.h.
Referenced by QDeclarativeFastProperties::accessorIndexForProperty(), QDeclarativeFastProperties::add(), QScriptBreakpointsModel::addBreakpoint(), QScriptDebuggerScriptsModel::addExtraScriptInfo(), QDeclarativeXmlQueryEngine::addIndexToRangeList(), QDeclarativeParser::Object::addScriptStringProperty(), QUrlModel::addUrls(), QHttpHeader::addValue(), QDeclarativeTimeLinePrivate::advance(), QDeclarativeParticles::burst(), QDeclarativeEnginePrivate::cache(), QGraphicsAnchorLayoutPrivate::calculateVertexPositions(), QDeclarativePropertyChangesParser::compileList(), Graph< AnchorVertex, AnchorData >::connections(), QScriptDebuggerAgent::contextsCheckpoint(), QDeclarativeEnginePrivate::createCache(), createSlack(), QDeclarativeXmlListModel::dataCleared(), QDeclarativePropertyChangesPrivate::decode(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::dfaStateForNfaState(), QDeclarativeXmlQueryEngine::doSubQueryJob(), QAbstractItemViewPrivate::draggablePaintPairs(), QListViewPrivate::draggablePaintPairs(), QUrl::encodedQueryItems(), QThreadPoolPrivate::enqueueTask(), QPatternist::IdFN::evaluateSequence(), QGridLayoutEngine::fillRowData(), QGraphicsAnchorLayoutPrivate::findPaths(), getFactor(), QStateMachinePrivate::initializeAnimation(), QGraphicsAnchorLayoutPrivate::internalVertex(), QScriptBreakpointsModel::modifyBreakpoint(), QPatternist::PullBridge::next(), QPatternist::OperandsIterator::next(), nextField(), QPatternist::AccelTreeResourceLoader::openUnparsedText(), QPatternist::OperandsIterator::OperandsIterator(), QHttpNetworkReplyPrivate::parseHeader(), QAuthenticatorPrivate::parseHttpResponse(), QHostAddress::parseSubnet(), QDeclarativeDomObjectPrivate::properties(), QPatternist::PullBridge::PullBridge(), qDBusAddTimeout(), QUrl::queryItems(), QHttpNetworkConnectionPrivate::queueRequest(), QXmlSerializerPrivate::QXmlSerializerPrivate(), QVariantAnimationPrivate::recalculateCurrentInterval(), QDeclarativeBindingCompilerPrivate::registerCleanup(), QDeclarativeEnginePrivate::registerFinalizedParserStatusObject(), QDeclarativeVMEMetaObject::registerInterceptor(), QDeclarativeBindingCompilerPrivate::registerString(), QGraphicsAnchorLayoutPrivate::removeAnchor(), QPatternist::AccelTreeResourceLoader::retrieveUnparsedText(), QScriptDebuggerAgent::scriptsDelta(), QItemSelectionModel::selectedColumns(), QItemSelectionModel::selectedRows(), QHttpNetworkHeaderPrivate::setHeaderField(), QRegExpEngine::setupCategoriesRangeMap(), QErrorMessage::showMessage(), QGraphicsAnchorLayoutPrivate::simplifyGraphIteration(), QXmlSerializer::startElement(), QPatternist::AccelTreeBuilder< true >::startElement(), QSortFilterProxyModelPrivate::store_persistent_indexes(), QPatternist::XsdParticleChecker::subsumes(), QVariantAnimationPrivate::valueAt(), and QPatternist::yyparse().
 {
     return QPair<T1, T2>(x, y);
 }