Qt 4.8: /src/gui/kernel/qpalette.cpp File Reference
qpalette.cpp File Reference
#include "qpalette.h"
#include "qapplication.h"
#include "qdatastream.h"
#include "qvariant.h"
Classes
class QPalettePrivate
Functions
static QColor qt_mix_colors (QColor a, QColor b)
static void qt_palette_from_color (QPalette &pal, const QColor &button)
static void readV1ColorGroup (QDataStream &s, QPalette &pal, QPalette::ColorGroup grp)
Variables
static const int NumOldRoles = 7
static const int oldRoles [7]
static int qt_palette_count = 1
Function Documentation
qt_mix_colors()
static QColor qt_mix_colors (QColor a, QColor b) static
Definition at line 60 of file qpalette.cpp.
Referenced by QPalette::setColorGroup().
 {
     return QColor((a.red() + b.red()) / 2, (a.green() + b.green()) / 2,
                   (a.blue() + b.blue()) / 2, (a.alpha() + b.alpha()) / 2);
 }
qt_palette_from_color()
static void qt_palette_from_color (QPalette & pal, const QColor & button) static
Definition at line 681 of file qpalette.cpp.
Referenced by QPalette::QPalette().
 {
     QColor bg = button,
            btn = button,
            fg, base;
     int h, s, v;
     bg.getHsv(&h, &s, &v);
     if(v > 128) {
         fg   = Qt::black;
         base = Qt::white;
     } else {
         fg   = Qt::white;
         base = Qt::black;
     }
     //inactive and active are the same..
     pal.setColorGroup(QPalette::Active, QBrush(fg), QBrush(btn), QBrush(btn.lighter(150)),
                       QBrush(btn.darker()), QBrush(btn.darker(150)), QBrush(fg), QBrush(Qt::white),
                       QBrush(base), QBrush(bg));
     pal.setColorGroup(QPalette::Inactive, QBrush(fg), QBrush(btn), QBrush(btn.lighter(150)),
                       QBrush(btn.darker()), QBrush(btn.darker(150)), QBrush(fg), QBrush(Qt::white),
                       QBrush(base), QBrush(bg));
     pal.setColorGroup(QPalette::Disabled, QBrush(btn.darker()), QBrush(btn), QBrush(btn.lighter(150)),
                       QBrush(btn.darker()), QBrush(btn.darker(150)), QBrush(btn.darker()),
                       QBrush(Qt::white), QBrush(bg), QBrush(bg));
 }
readV1ColorGroup()
static void readV1ColorGroup (QDataStream & s, QPalette & pal, QPalette::ColorGroup grp) static
Definition at line 1174 of file qpalette.cpp.
Referenced by QPalette::operator>>().
 {
     for (int i = 0; i < NumOldRoles; ++i) {
         QColor col;
         s >> col;
         pal.setColor(grp, (QPalette::ColorRole)oldRoles[i], col);
     }
 }
Variable Documentation
NumOldRoles
const int NumOldRoles = 7 static
Definition at line 1138 of file qpalette.cpp.
Referenced by readV1ColorGroup().
oldRoles
const int oldRoles[7] static
Initial value:
= { QPalette::Foreground, QPalette::Background, QPalette::Light,
                                 QPalette::Dark, QPalette::Mid, QPalette::Text, QPalette::Base }
Definition at line 1139 of file qpalette.cpp.
Referenced by readV1ColorGroup().
qt_palette_count
int qt_palette_count = 1 static
Definition at line 49 of file qpalette.cpp.