Qt 4.8: /src/gui/painting/qpdf.cpp File Reference
qpdf.cpp File Reference
#include "qplatformdefs.h"
#include <qdebug.h>
#include "qpdf_p.h"
#include <qfile.h>
#include <qtemporaryfile.h>
#include <private/qmath_p.h>
#include "private/qcups_p.h"
#include "qprinterinfo.h"
#include <qnumeric.h>
#include "private/qfont_p.h"
#include "private/qcore_unix_p.h"
Namespaces
QPdf
Macros
#define Q_IN(n) int(n * 72)
#define Q_MM(n) int((n * 720 + 127) / 254)
#define QT_PATH_ELEMENT(elm)
Functions
static void closeAllOpenFds ()
static void cubicToHook (qfixed c1x, qfixed c1y, qfixed c2x, qfixed c2y, qfixed ex, qfixed ey, void *data)
static void lineToHook (qfixed x, qfixed y, void *data)
static void moveToHook (qfixed x, qfixed y, void *data)
const char * qt_int_to_string (int val, char *buf)
QSizeF qt_paperSizeToQSizeF (QPrinter::PaperSize size)
const char * qt_real_to_string (qreal val, char *buf)
Q_AUTOTEST_EXPORT QPainterPath qt_regionToPath (const QRegion &region)
Variables
static const char * pattern_for_brush []
static const char *const psToStr [QPrinter::NPaperSize+1]
Macro Definition Documentation
Q_IN
#define Q_IN (n) int(n * 72)
Definition at line 895 of file qpdf.cpp.
Q_MM
#define Q_MM (n) int((n * 720 + 127) / 254)
Definition at line 894 of file qpdf.cpp.
Referenced by QPdf::paperSize().
QT_PATH_ELEMENT
#define QT_PATH_ELEMENT (elm)
Definition at line 270 of file qpdf.cpp.
Function Documentation
closeAllOpenFds()
static void closeAllOpenFds () static
Definition at line 1645 of file qpdf.cpp.
Referenced by QPdfBaseEnginePrivate::openPrintDevice().
 {
     // hack time... getting the maximum number of open
     // files, if possible.  if not we assume it's the
     // larger of 256 and the fd we got
     int i;
 #if defined(_SC_OPEN_MAX)
     i = (int)sysconf(_SC_OPEN_MAX);
 #elif defined(_POSIX_OPEN_MAX)
     i = (int)_POSIX_OPEN_MAX;
 #elif defined(OPEN_MAX)
     i = (int)OPEN_MAX;
 #else
     i = 256;
 #endif
     // leave stdin/out/err untouched
     while(--i > 2)
         QT_CLOSE(i);
 }
cubicToHook()
static void cubicToHook (qfixed c1x, qfixed c1y, qfixed c2x, qfixed c2y, qfixed ex, qfixed ey, void * data) static
Definition at line 735 of file qpdf.cpp.
Referenced by QStrokerOps::setCubicToHook(), and QPdf::Stroker::Stroker().
 {
     QPdf::Stroker *t = (QPdf::Stroker *)data;
     if (!t->cosmeticPen) {
         t->matrix.map(c1x, c1y, &c1x, &c1y);
         t->matrix.map(c2x, c2y, &c2x, &c2y);
         t->matrix.map(ex, ey, &ex, &ey);
     }
     *t->stream << c1x << c1y
                << c2x << c2y
                << ex << ey
                << "c\n";
 }
lineToHook()
static void lineToHook (qfixed x, qfixed y, void * data) static
Definition at line 727 of file qpdf.cpp.
Referenced by QStrokerOps::setLineToHook(), and QPdf::Stroker::Stroker().
 {
     QPdf::Stroker *t = (QPdf::Stroker *)data;
     if (!t->cosmeticPen)
         t->matrix.map(x, y, &x, &y);
     *t->stream << x << y << "l\n";
 }
moveToHook()
static void moveToHook (qfixed x, qfixed y, void * data) static
Definition at line 716 of file qpdf.cpp.
Referenced by QStrokerOps::setMoveToHook(), and QPdf::Stroker::Stroker().
 {
     QPdf::Stroker *t = (QPdf::Stroker *)data;
     if (!t->first)
         *t->stream << "h\n";
     if (!t->cosmeticPen)
         t->matrix.map(x, y, &x, &y);
     *t->stream << x << y << "m\n";
     t->first = false;
 }
qt_int_to_string()
const char* qt_int_to_string (int val, char * buf)
Definition at line 115 of file qpdf.cpp.
Referenced by QPdf::ByteStream::operator<<().
{
     const char *ret = buf;
     if (val < 0) {
         *(buf++) = '-';
         val = -val;
     }
     char output[256];
     int i = 0;
     while (val) {
         output[i] = '0' + (val % 10);
         ++i;
         val /= 10;
     }
     if (i == 0) {
         *(buf++) = '0';
     } else {
         while (i)
             *(buf++) = output[--i];
     }
     *(buf++) = ' ';
     *buf = 0;
     return ret;
 }
qt_paperSizeToQSizeF()
QSizeF qt_paperSizeToQSizeF (QPrinter::PaperSize size)
Definition at line 2615 of file qprinter.cpp.
Referenced by QPdf::paperSize().
 {
     if (size == QPrinter::Custom) return QSizeF(0, 0);
     return QSizeF(qt_paperSizes[size][0], qt_paperSizes[size][1]);
 }
qt_real_to_string()
const char* qt_real_to_string (qreal val, char * buf)
Definition at line 63 of file qpdf.cpp.
Referenced by QPdf::ByteStream::operator<<().
{
     const char *ret = buf;
     if (qIsNaN(val)) {
         *(buf++) = '0';
         *(buf++) = ' ';
         *buf = 0;
         return ret;
     }
     if (val < 0) {
         *(buf++) = '-';
         val = -val;
     }
     unsigned int ival = (unsigned int) val;
     qreal frac = val - (qreal)ival;
     int ifrac = (int)(frac * 1000000000);
     if (ifrac == 1000000000) {
         ++ival;
         ifrac = 0;
     }
     char output[256];
     int i = 0;
     while (ival) {
         output[i] = '0' + (ival % 10);
         ++i;
         ival /= 10;
     }
     int fact = 100000000;
     if (i == 0) {
         *(buf++) = '0';
     } else {
         while (i) {
             *(buf++) = output[--i];
             fact /= 10;
             ifrac /= 10;
         }
     }
     if (ifrac) {
         *(buf++) =  '.';
         while (fact) {
             *(buf++) = '0' + ((ifrac/fact) % 10);
             fact /= 10;
         }
     }
     *(buf++) = ' ';
     *buf = 0;
     return ret;
 }
qt_regionToPath()
Q_AUTOTEST_EXPORT QPainterPath qt_regionToPath (const QRegion & region)
Definition at line 1160 of file qregion.cpp.
Referenced by QPdfBaseEngine::setupGraphicsState(), and QPdfBaseEngine::updateClipPath().
 {
     QPainterPath result;
     if (region.rectCount() == 1) {
         result.addRect(region.boundingRect());
         return result;
     }
     const QVector<QRect> rects = region.rects();
     QVarLengthArray<Segment> segments;
     segments.resize(4 * rects.size());
     const QRect *rect = rects.constData();
     const QRect *end = rect + rects.size();
     int lastRowSegmentCount = 0;
     Segment *lastRowSegments = 0;
     int lastSegment = 0;
     int lastY = 0;
     while (rect != end) {
         const int y = rect[0].y();
         int count = 0;
         while (&rect[count] != end && rect[count].y() == y)
             ++count;
         for (int i = 0; i < count; ++i) {
             int offset = lastSegment + i;
             segments[offset] = Segment(rect[i].topLeft());
             segments[offset += count] = Segment(rect[i].topRight() + QPoint(1, 0));
             segments[offset += count] = Segment(rect[i].bottomRight() + QPoint(1, 1));
             segments[offset += count] = Segment(rect[i].bottomLeft() + QPoint(0, 1));
             offset = lastSegment + i;
             for (int j = 0; j < 4; ++j)
                 segments[offset + j * count].connect(segments[offset + ((j + 1) % 4) * count]);
         }
         if (lastRowSegments && lastY == y)
             mergeSegments(lastRowSegments, lastRowSegmentCount, &segments[lastSegment], count);
         lastRowSegments = &segments[lastSegment + 2 * count];
         lastRowSegmentCount = count;
         lastSegment += 4 * count;
         lastY = y + rect[0].height();
         rect += count;
     }
     for (int i = 0; i < lastSegment; ++i) {
         Segment *segment = &segments[i];
         if (!segment->added)
             addSegmentsToPath(segment, result);
     }
     return result;
 }
Variable Documentation
pattern_for_brush
const char* pattern_for_brush[] static
Definition at line 371 of file qpdf.cpp.
Referenced by QPdf::patternForBrush().
psToStr
const char* const psToStr[QPrinter::NPaperSize+1] static
Initial value:
=
{
    "A4", "B5", "Letter", "Legal", "Executive",
    "A0", "A1", "A2", "A3", "A5", "A6", "A7", "A8", "A9", "B0", "B1",
    "B10", "B2", "B3", "B4", "B6", "B7", "B8", "B9", "C5E", "Comm10E",
    "DLE", "Folio", "Ledger", "Tabloid", 0
}
Definition at line 897 of file qpdf.cpp.
Referenced by QPdf::paperSizeToString().