Qt 4.8: /src/gui/painting/qpen.h File Reference
qpen.h File Reference
#include <QtGui/qcolor.h>
#include <QtGui/qbrush.h>
Classes
class QPen
The QPen class defines how a QPainter should draw lines and outlines of shapes.
Functions
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &, const QPen &)
Q_GUI_EXPORT QDebug operator<< (QDebug, const QPen &)
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &, QPen &)
Q_DECLARE_TYPEINFO (QPen, Q_MOVABLE_TYPE)
Function Documentation
operator<<() [1/2]
Q_GUI_EXPORT QDataStream& operator<< (QDataStream & , const QPen &)
Definition at line 936 of file qpen.cpp.
Referenced by QPen::data_ptr(), and QPen::operator!=().
 {
     QPenData *dd = static_cast<QPenData *>(p.d);
     if (s.version() < 3) {
         s << (quint8)p.style();
     } else if (s.version() < QDataStream::Qt_4_3) {
         s << (quint8)(p.style() | p.capStyle() | p.joinStyle());
     } else {
         s << (quint16)(p.style() | p.capStyle() | p.joinStyle());
         s << (bool)(dd->cosmetic);
     }
     if (s.version() < 7) {
         s << (quint8)p.width();
         s << p.color();
     } else {
         s << double(p.widthF());
         s << p.brush();
         s << double(p.miterLimit());
         if (sizeof(qreal) == sizeof(double)) {
             s << p.dashPattern();
         } else {
             // ensure that we write doubles here instead of streaming the pattern
             // directly; otherwise, platforms that redefine qreal might generate
             // data that cannot be read on other platforms.
             QVector<qreal> pattern = p.dashPattern();
             s << quint32(pattern.size());
             for (int i = 0; i < pattern.size(); ++i)
                 s << double(pattern.at(i));
         }
         if (s.version() >= 9)
             s << double(p.dashOffset());
     }
     return s;
 }
operator<<() [2/2]
Q_GUI_EXPORT QDebug operator<< (QDebug , const QPen &)
Definition at line 1045 of file qpen.cpp.
 {
 #ifndef Q_BROKEN_DEBUG_STREAM
     const char *PEN_STYLES[] = {
         "NoPen",
         "SolidLine",
         "DashLine",
         "DotLine",
         "DashDotLine",
         "DashDotDotLine",
         "CustomDashLine"
     };
     dbg.nospace() << "QPen(" << p.width() << ',' << p.brush()
                   << ',' << PEN_STYLES[p.style()] << ',' << int(p.capStyle())
                   << ',' << int(p.joinStyle()) << ',' << p.dashPattern()
                   << ',' << p.dashOffset()
                   << ',' << p.miterLimit() << ')';
     return dbg.space();
 #else
     qWarning("This compiler doesn't support streaming QPen to QDebug");
     return dbg;
     Q_UNUSED(p);
 #endif
 }
operator>>()
Q_GUI_EXPORT QDataStream& operator>> (QDataStream & , QPen &)
Definition at line 985 of file qpen.cpp.
Referenced by QPen::operator!=().
 {
     quint16 style;
     quint8 width8 = 0;
     double width = 0;
     QColor color;
     QBrush brush;
     double miterLimit = 2;
     QVector<qreal> dashPattern;
     double dashOffset = 0;
     bool cosmetic = false;
     if (s.version() < QDataStream::Qt_4_3) {
         quint8 style8;
         s >> style8;
         style = style8;
     } else {
         s >> style;
         s >> cosmetic;
     }
     if (s.version() < 7) {
         s >> width8;
         s >> color;
         brush = color;
         width = width8;
     } else {
         s >> width;
         s >> brush;
         s >> miterLimit;
         if (sizeof(qreal) == sizeof(double)) {
             s >> dashPattern;
         } else {
             quint32 numDashes;
             s >> numDashes;
             double dash;
             for (quint32 i = 0; i < numDashes; ++i) {
                 s >> dash;
                 dashPattern << dash;
             }
         }
         if (s.version() >= 9)
             s >> dashOffset;
     }
     p.detach();
     QPenData *dd = static_cast<QPenData *>(p.d);
     dd->width = width;
     dd->brush = brush;
     dd->style = Qt::PenStyle(style & Qt::MPenStyle);
     dd->capStyle = Qt::PenCapStyle(style & Qt::MPenCapStyle);
     dd->joinStyle = Qt::PenJoinStyle(style & Qt::MPenJoinStyle);
     dd->dashPattern = dashPattern;
     dd->miterLimit = miterLimit;
     dd->dashOffset = dashOffset;
     dd->cosmetic = cosmetic;
     return s;
 }
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QPen , Q_MOVABLE_TYPE)
Referenced by QPen::data_ptr().