Qt 4.8: /src/gui/painting/qpen.cpp File Reference
qpen.cpp File Reference
#include "qpen.h"
#include "qpen_p.h"
#include "qdatastream.h"
#include "qvariant.h"
#include "qbrush.h"
#include <qdebug.h>
Classes
class QGlobalStaticDeleter< QPenPrivate >
Typedefs
typedef QPenPrivate QPenData
Functions
QDataStream & operator<< (QDataStream &s, const QPen &p)
QDebug operator<< (QDebug dbg, const QPen &p)
QDataStream & operator>> (QDataStream &s, QPen &p)
Q_GLOBAL_STATIC_WITH_ARGS (QPenData, defaultPenInstance,(Qt::black, 0, Qt::SolidLine, qpen_default_cap, qpen_default_join)) Q_GLOBAL_STATIC_WITH_ARGS(QPenData
Variables
nullPenInstance
static const Qt::PenCapStyle qpen_default_cap = Qt::SquareCap
static const Qt::PenJoinStyle qpen_default_join = Qt::BevelJoin
Typedef Documentation
QPenData
typedef QPenPrivate QPenData
Definition at line 51 of file qpen.cpp.
Function Documentation
operator<<() [1/2]
QDataStream& operator<< (QDataStream & s, const QPen & p)
Definition at line 936 of file qpen.cpp.
Referenced by QPen::data_ptr(), and QPen::operator!=().
 {
     QPenData *dd = static_cast<QPenData *>(p.d);
     if (s.version() < 3) {
         s << (quint8)p.style();
     } else if (s.version() < QDataStream::Qt_4_3) {
         s << (quint8)(p.style() | p.capStyle() | p.joinStyle());
     } else {
         s << (quint16)(p.style() | p.capStyle() | p.joinStyle());
         s << (bool)(dd->cosmetic);
     }
     if (s.version() < 7) {
         s << (quint8)p.width();
         s << p.color();
     } else {
         s << double(p.widthF());
         s << p.brush();
         s << double(p.miterLimit());
         if (sizeof(qreal) == sizeof(double)) {
             s << p.dashPattern();
         } else {
             // ensure that we write doubles here instead of streaming the pattern
             // directly; otherwise, platforms that redefine qreal might generate
             // data that cannot be read on other platforms.
             QVector<qreal> pattern = p.dashPattern();
             s << quint32(pattern.size());
             for (int i = 0; i < pattern.size(); ++i)
                 s << double(pattern.at(i));
         }
         if (s.version() >= 9)
             s << double(p.dashOffset());
     }
     return s;
 }
operator<<() [2/2]
QDebug operator<< (QDebug dbg, const QPen & p)
Definition at line 1045 of file qpen.cpp.
 {
 #ifndef Q_BROKEN_DEBUG_STREAM
     const char *PEN_STYLES[] = {
         "NoPen",
         "SolidLine",
         "DashLine",
         "DotLine",
         "DashDotLine",
         "DashDotDotLine",
         "CustomDashLine"
     };
     dbg.nospace() << "QPen(" << p.width() << ',' << p.brush()
                   << ',' << PEN_STYLES[p.style()] << ',' << int(p.capStyle())
                   << ',' << int(p.joinStyle()) << ',' << p.dashPattern()
                   << ',' << p.dashOffset()
                   << ',' << p.miterLimit() << ')';
     return dbg.space();
 #else
     qWarning("This compiler doesn't support streaming QPen to QDebug");
     return dbg;
     Q_UNUSED(p);
 #endif
 }
operator>>()
QDataStream& operator>> (QDataStream & s, QPen & p)
Definition at line 985 of file qpen.cpp.
Referenced by QPen::operator!=().
 {
     quint16 style;
     quint8 width8 = 0;
     double width = 0;
     QColor color;
     QBrush brush;
     double miterLimit = 2;
     QVector<qreal> dashPattern;
     double dashOffset = 0;
     bool cosmetic = false;
     if (s.version() < QDataStream::Qt_4_3) {
         quint8 style8;
         s >> style8;
         style = style8;
     } else {
         s >> style;
         s >> cosmetic;
     }
     if (s.version() < 7) {
         s >> width8;
         s >> color;
         brush = color;
         width = width8;
     } else {
         s >> width;
         s >> brush;
         s >> miterLimit;
         if (sizeof(qreal) == sizeof(double)) {
             s >> dashPattern;
         } else {
             quint32 numDashes;
             s >> numDashes;
             double dash;
             for (quint32 i = 0; i < numDashes; ++i) {
                 s >> dash;
                 dashPattern << dash;
             }
         }
         if (s.version() >= 9)
             s >> dashOffset;
     }
     p.detach();
     QPenData *dd = static_cast<QPenData *>(p.d);
     dd->width = width;
     dd->brush = brush;
     dd->style = Qt::PenStyle(style & Qt::MPenStyle);
     dd->capStyle = Qt::PenCapStyle(style & Qt::MPenCapStyle);
     dd->joinStyle = Qt::PenJoinStyle(style & Qt::MPenJoinStyle);
     dd->dashPattern = dashPattern;
     dd->miterLimit = miterLimit;
     dd->dashOffset = dashOffset;
     dd->cosmetic = cosmetic;
     return s;
 }
Q_GLOBAL_STATIC_WITH_ARGS()
Q_GLOBAL_STATIC_WITH_ARGS (QPenData , defaultPenInstance , (Qt::black, 0, Qt::SolidLine, qpen_default_cap, qpen_default_join))
Variable Documentation
nullPenInstance
nullPenInstance
Definition at line 272 of file qpen.cpp.
Referenced by QPen::QPen().
qpen_default_cap
qpen_default_cap = Qt::SquareCap static
Definition at line 246 of file qpen.cpp.
Referenced by QPen::QPen().
qpen_default_join
const Qt::PenJoinStyle qpen_default_join = Qt::BevelJoin static
Definition at line 247 of file qpen.cpp.
Referenced by QPen::QPen().