Qt 4.8: /src/gui/image/qpicture.cpp File Reference
qpicture.cpp File Reference
#include "qpicture.h"
#include <private/qpicture_p.h>
#include <private/qfactoryloader_p.h>
#include <private/qpaintengine_pic_p.h>
#include <private/qfont_p.h>
#include "qdatastream.h"
#include "qfile.h"
#include "qimage.h"
#include "qmutex.h"
#include "qpainter.h"
#include "qpainterpath.h"
#include "qpixmap.h"
#include "qregion.h"
#include "qdebug.h"
#include "qregexp.h"
#include "qapplication.h"
#include "qpictureformatplugin.h"
Classes
class QFakeDevice
class QPictureHandler
struct QPictureIOData
Typedefs
typedef QList< QPictureHandler * > QPHList
Functions
static void cleanup ()
static QPictureHandler * get_picture_handler (const char *format)
Q_GLOBAL_STATIC_WITH_ARGS (QFactoryLoader, factoryLoader,(QPictureFormatInterface_iid, QLatin1String("/pictureformats"))) void qt_init_picture_plugins()
void qt_format_text (const QFont &fnt, const QRectF &_r, int tf, const QTextOption *opt, const QString &str, QRectF *brect, int tabstops, int *, int tabarraylen, QPainter *painter)
void qt_init_picture_handlers ()
static QStringList qToStringList (const QList< QByteArray > arr)
Variables
static const quint16 mfhdr_maj = 11
static const quint16 mfhdr_min = 0
const char * qt_mfhdr_tag = "QPIC"
Typedef Documentation
QPHList
typedef QList<QPictureHandler *> QPHList
Definition at line 1487 of file qpicture.cpp.
Function Documentation
cleanup()
static void cleanup () static
Definition at line 1508 of file qpicture.cpp.
Referenced by QProcessPrivate::_q_processDied(), QProcessPrivate::_q_startupNotification(), QVectorPath::addCacheData(), QIcdEngine::changedSessionConfiguration(), QDeclarativeBindingCompilerPrivate::compile(), QProcessPrivate::createChannel(), IapMonitor::IapMonitor(), QMacInputContext::identifierName(), QTestAccessibility::initialize(), QTabBarPrivate::moveTabFinished(), QDeclarativeObjectMethodScriptClass::property(), QGLPixelBufferPrivate::QGLPixelBufferPrivate(), qt_init_picture_handlers(), QDeclarativeBindingCompilerPrivate::releaseReg(), QScopedPointer< QXmlResultItemsPrivate >::reset(), QDeclarativeCompiledBindingsPrivate::run(), QVGPixmapData::size(), QProcessPrivate::startProcess(), utcToLocal(), QDeclarativeEnginePrivate::~QDeclarativeEnginePrivate(), QIBaseResultPrivate::~QIBaseResultPrivate(), QScopedPointer< QXmlResultItemsPrivate >::~QScopedPointer(), QWindowsXPStylePrivate::~QWindowsXPStylePrivate(), and QTest::TestFuncCleanup::~TestFuncCleanup().
 {
     // make sure that picture handlers are delete before plugin manager
     if (QPHList *list = pictureHandlers()) {
         qDeleteAll(*list);
         list->clear();
     }
 }
get_picture_handler()
static QPictureHandler* get_picture_handler (const char * format) static
Definition at line 1525 of file qpicture.cpp.
Referenced by QPictureIO::read(), and QPictureIO::write().
 {                                                // get pointer to handler
     qt_init_picture_handlers();
     qt_init_picture_plugins();
     if (QPHList *list = pictureHandlers()) {
         for (int i = 0; i < list->size(); ++i) {
             if (list->at(i)->format == format)
                 return list->at(i);
         }
     }
     return 0;                                        // no such handler
 }
Q_GLOBAL_STATIC_WITH_ARGS()
Q_GLOBAL_STATIC_WITH_ARGS (QFactoryLoader , factoryLoader , (QPictureFormatInterface_iid, QLatin1String("/pictureformats")))
Definition at line 1492 of file qpicture.cpp.
 {
 #ifndef QT_NO_LIBRARY
     QMutexLocker locker(mutex());
     QFactoryLoader *loader = factoryLoader();
     QStringList keys = loader->keys();
     for (int i = 0; i < keys.count(); ++i)
         if (QPictureFormatInterface *format = qobject_cast<QPictureFormatInterface*>(loader->instance(keys.at(i))))
             format->installIOHandler(keys.at(i));
 #endif
 }
qt_format_text()
void qt_format_text (const QFont & fnt, const QRectF & _r, int tf, const QTextOption * opt, const QString & str, QRectF * brect, int tabstops, int * ta, int tabarraylen, QPainter * painter)
Definition at line 8458 of file qpainter.cpp.
Referenced by QPicture::exec().
 {
     Q_ASSERT( !((tf & ~Qt::TextDontPrint)!=0 && option!=0) ); // we either have an option or flags
     if (option) {
         tf |= option->alignment();
         if (option->wrapMode() != QTextOption::NoWrap)
             tf |= Qt::TextWordWrap;
         if (option->flags() & QTextOption::IncludeTrailingSpaces)
             tf |= Qt::TextIncludeTrailingSpaces;
         if (option->tabStop() >= 0 || !option->tabArray().isEmpty())
             tf |= Qt::TextExpandTabs;
     }
     // we need to copy r here to protect against the case (&r == brect).
     QRectF r(_r);
     bool dontclip  = (tf & Qt::TextDontClip);
     bool wordwrap  = (tf & Qt::TextWordWrap) || (tf & Qt::TextWrapAnywhere);
     bool singleline = (tf & Qt::TextSingleLine);
     bool showmnemonic = (tf & Qt::TextShowMnemonic);
     bool hidemnmemonic = (tf & Qt::TextHideMnemonic);
     Qt::LayoutDirection layout_direction;
     if (tf & Qt::TextForceLeftToRight)
         layout_direction = Qt::LeftToRight;
     else if (tf & Qt::TextForceRightToLeft)
         layout_direction = Qt::RightToLeft;
     else if (option)
         layout_direction = option->textDirection();
     else if (painter)
         layout_direction = painter->layoutDirection();
     else
         layout_direction = Qt::LeftToRight;
     tf = QStyle::visualAlignment(layout_direction, QFlag(tf));
     bool isRightToLeft = layout_direction == Qt::RightToLeft;
     bool expandtabs = ((tf & Qt::TextExpandTabs) &&
                         (((tf & Qt::AlignLeft) && !isRightToLeft) ||
                           ((tf & Qt::AlignRight) && isRightToLeft)));
     if (!painter)
         tf |= Qt::TextDontPrint;
     uint maxUnderlines = 0;
     int numUnderlines = 0;
     QVarLengthArray<int, 32> underlinePositions(1);
     QFontMetricsF fm(fnt);
     QString text = str;
     int offset = 0;
 start_lengthVariant:
     bool hasMoreLengthVariants = false;
     // compatible behaviour to the old implementation. Replace
     // tabs by spaces
     int old_offset = offset;
     for (; offset < text.length(); offset++) {
         QChar chr = text.at(offset);
         if (chr == QLatin1Char('\r') || (singleline && chr == QLatin1Char('\n'))) {
             text[offset] = QLatin1Char(' ');
         } else if (chr == QLatin1Char('\n')) {
             text[offset] = QChar::LineSeparator;
         } else if (chr == QLatin1Char('&')) {
             ++maxUnderlines;
         } else if (chr == QLatin1Char('\t')) {
             if (!expandtabs) {
                 text[offset] = QLatin1Char(' ');
             } else if (!tabarraylen && !tabstops) {
                 tabstops = qRound(fm.width(QLatin1Char('x'))*8);
             }
         } else if (chr == QChar(ushort(0x9c))) {
             // string with multiple length variants
             hasMoreLengthVariants = true;
             break;
         }
     }
     int length = offset - old_offset;
     if ((hidemnmemonic || showmnemonic) && maxUnderlines > 0) {
         underlinePositions.resize(maxUnderlines + 1);
         QChar *cout = text.data() + old_offset;
         QChar *cin = cout;
         int l = length;
         while (l) {
             if (*cin == QLatin1Char('&')) {
                 ++cin;
                 --length;
                 --l;
                 if (!l)
                     break;
                 if (*cin != QLatin1Char('&') && !hidemnmemonic)
                     underlinePositions[numUnderlines++] = cout - text.data() - old_offset;
             }
             *cout = *cin;
             ++cout;
             ++cin;
             --l;
         }
     }
     // no need to do extra work for underlines if we don't paint
     if (tf & Qt::TextDontPrint)
         numUnderlines = 0;
     underlinePositions[numUnderlines] = -1;
     qreal height = 0;
     qreal width = 0;
     QString finalText = text.mid(old_offset, length);
     QStackTextEngine engine(finalText, fnt);
     if (option) {
         engine.option = *option;
     }
     if (engine.option.tabStop() < 0 && tabstops > 0)
         engine.option.setTabStop(tabstops);
     if (engine.option.tabs().isEmpty() && ta) {
         QList<qreal> tabs;
         for (int i = 0; i < tabarraylen; i++)
             tabs.append(qreal(ta[i]));
         engine.option.setTabArray(tabs);
     }
     engine.option.setTextDirection(layout_direction);
     if (tf & Qt::AlignJustify)
         engine.option.setAlignment(Qt::AlignJustify);
     else
         engine.option.setAlignment(Qt::AlignLeft); // do not do alignment twice
     if (!option && (tf & Qt::TextWrapAnywhere))
         engine.option.setWrapMode(QTextOption::WrapAnywhere);
     if (tf & Qt::TextJustificationForced)
         engine.forceJustification = true;
     QTextLayout textLayout(&engine);
     textLayout.setCacheEnabled(true);
     textLayout.engine()->underlinePositions = underlinePositions.data();
     if (finalText.isEmpty()) {
         height = fm.height();
         width = 0;
         tf |= Qt::TextDontPrint;
     } else {
         qreal lineWidth = 0x01000000;
         if (wordwrap || (tf & Qt::TextJustificationForced))
             lineWidth = qMax<qreal>(0, r.width());
         if(!wordwrap)
             tf |= Qt::TextIncludeTrailingSpaces;
         textLayout.engine()->ignoreBidi = bool(tf & Qt::TextDontPrint);
         textLayout.beginLayout();
         qreal leading = fm.leading();
         height = -leading;
         while (1) {
             QTextLine l = textLayout.createLine();
             if (!l.isValid())
                 break;
             l.setLineWidth(lineWidth);
             height += leading;
             l.setPosition(QPointF(0., height));
             height += l.height();
             width = qMax(width, l.naturalTextWidth());
             if (!dontclip && !brect && height >= r.height())
                 break;
         }
         textLayout.endLayout();
     }
     qreal yoff = 0;
     qreal xoff = 0;
     if (tf & Qt::AlignBottom) {
         yoff = r.height() - height;
     } else if (tf & Qt::AlignVCenter) {
         yoff = (r.height() - height)/2;
         if (painter) {
             QTransform::TransformationType type = painter->transform().type();
             if (type <= QTransform::TxScale) {
                 // do the rounding manually to work around inconsistencies
                 // in the paint engines when drawing on floating point offsets
                 const qreal scale = painter->transform().m22();
                 if (scale != 0)
                     yoff = -qRound(-yoff * scale) / scale;
             }
         }
     }
     if (tf & Qt::AlignRight) {
         xoff = r.width() - width;
     } else if (tf & Qt::AlignHCenter) {
         xoff = (r.width() - width)/2;
         if (painter) {
             QTransform::TransformationType type = painter->transform().type();
             if (type <= QTransform::TxScale) {
                 // do the rounding manually to work around inconsistencies
                 // in the paint engines when drawing on floating point offsets
                 const qreal scale = painter->transform().m11();
                 if (scale != 0)
                     xoff = qRound(xoff * scale) / scale;
             }
         }
     }
     QRectF bounds = QRectF(r.x() + xoff, r.y() + yoff, width, height);
     if (hasMoreLengthVariants && !(tf & Qt::TextLongestVariant) && !r.contains(bounds)) {
         offset++;
         goto start_lengthVariant;
     }
     if (brect)
         *brect = bounds;
     if (!(tf & Qt::TextDontPrint)) {
         bool restore = false;
         if (!dontclip && !r.contains(bounds)) {
             restore = true;
             painter->save();
             painter->setClipRect(r, Qt::IntersectClip);
         }
         for (int i = 0; i < textLayout.lineCount(); i++) {
             QTextLine line = textLayout.lineAt(i);
             qreal advance = line.horizontalAdvance();
             xoff = 0;
             if (tf & Qt::AlignRight) {
                 QTextEngine *eng = textLayout.engine();
                 xoff = r.width() - advance -
                     eng->leadingSpaceWidth(eng->lines[line.lineNumber()]).toReal();
             }
             else if (tf & Qt::AlignHCenter)
                 xoff = (r.width() - advance) / 2;
             line.draw(painter, QPointF(r.x() + xoff, r.y() + yoff));
         }
         if (restore) {
             painter->restore();
         }
     }
 }
qt_init_picture_handlers()
void qt_init_picture_handlers ()
Definition at line 1517 of file qpicture.cpp.
Referenced by QPictureIO::defineIOHandler(), get_picture_handler(), QPictureIO::inputFormats(), QPictureIO::outputFormats(), and QPictureIO::pictureFormat().
 {
     static QBasicAtomicInt done = Q_BASIC_ATOMIC_INITIALIZER(0);
     if (done.testAndSetRelaxed(0, 1)) {
         qAddPostRoutine(cleanup);
     }
 }
qToStringList()
static QStringList qToStringList (const QList< QByteArray > arr) static
Definition at line 1291 of file qpicture.cpp.
Referenced by QPicture::inputFormatList(), and QPicture::outputFormatList().
 {
     QStringList list;
     for (int i = 0; i < arr.count(); ++i)
         list.append(QString::fromLatin1(arr.at(i)));
     return list;
 }
Variable Documentation
mfhdr_maj
const quint16 mfhdr_maj = 11 static
Definition at line 113 of file qpicture.cpp.
Referenced by QPicturePrivate::checkFormat(), QPicture::QPicture(), and QPicturePrivate::resetFormat().
mfhdr_min
const quint16 mfhdr_min = 0 static
Definition at line 114 of file qpicture.cpp.
Referenced by QPicturePrivate::resetFormat().
qt_mfhdr_tag
const char* qt_mfhdr_tag = "QPIC"
Definition at line 112 of file qpicture.cpp.
Referenced by QPicturePaintEngine::begin(), and QPicturePrivate::checkFormat().