Qt 4.8: /src/gui/image/qpixmap_raster.cpp File Reference
qpixmap_raster.cpp File Reference
#include "qpixmap.h"
#include <private/qfont_p.h>
#include "qpixmap_raster_p.h"
#include "qnativeimage_p.h"
#include "qimage_p.h"
#include "qpaintengine.h"
#include "qbitmap.h"
#include "qimage.h"
#include <QBuffer>
#include <QImageReader>
#include <private/qimage_p.h>
#include <private/qsimd_p.h>
#include <private/qwidget_p.h>
#include <private/qdrawhelper_p.h>
Functions
void qt_scrollRectInImage (QImage &img, const QRect &rect, const QPoint &offset)
QPixmap qt_toRasterPixmap (const QImage &image)
QPixmap qt_toRasterPixmap (const QPixmap &pixmap)
Variables
const uchar qt_pixmap_bit_mask []
Function Documentation
qt_scrollRectInImage()
void qt_scrollRectInImage (QImage & img, const QRect & rect, const QPoint & offset)
Definition at line 345 of file qwindowsurface.cpp.
Referenced by QRasterPixmapData::fromImageReader(), and QRasterPixmapData::scroll().
 {
     // make sure we don't detach
     uchar *mem = const_cast<uchar*>(const_cast<const QImage &>(img).bits());
     int lineskip = img.bytesPerLine();
     int depth = img.depth() >> 3;
     const QRect imageRect(0, 0, img.width(), img.height());
     const QRect r = rect & imageRect & imageRect.translated(-offset);
     const QPoint p = rect.topLeft() + offset;
     if (r.isEmpty())
         return;
     const uchar *src;
     uchar *dest;
     if (r.top() < p.y()) {
         src = mem + r.bottom() * lineskip + r.left() * depth;
         dest = mem + (p.y() + r.height() - 1) * lineskip + p.x() * depth;
         lineskip = -lineskip;
     } else {
         src = mem + r.top() * lineskip + r.left() * depth;
         dest = mem + p.y() * lineskip + p.x() * depth;
     }
     const int w = r.width();
     int h = r.height();
     const int bytes = w * depth;
     // overlapping segments?
     if (offset.y() == 0 && qAbs(offset.x()) < w) {
         do {
             ::memmove(dest, src, bytes);
             dest += lineskip;
             src += lineskip;
         } while (--h);
     } else {
         do {
             ::memcpy(dest, src, bytes);
             dest += lineskip;
             src += lineskip;
         } while (--h);
     }
 }
qt_toRasterPixmap() [1/2]
QPixmap qt_toRasterPixmap (const QImage & image)
Definition at line 65 of file qpixmap_raster.cpp.
Referenced by qt_toRasterPixmap().
 {
     QPixmapData *data =
         new QRasterPixmapData(image.depth() == 1
                            ? QPixmapData::BitmapType
                            : QPixmapData::PixmapType);
     data->fromImage(image, Qt::AutoColor);
     return QPixmap(data);
 }
qt_toRasterPixmap() [2/2]
QPixmap qt_toRasterPixmap (const QPixmap & pixmap)
Definition at line 77 of file qpixmap_raster.cpp.
 {
     if (pixmap.isNull())
         return QPixmap();
     if (QPixmap(pixmap).data_ptr()->classId() == QPixmapData::RasterClass)
         return pixmap;
     return qt_toRasterPixmap(pixmap.toImage());
 }
Variable Documentation
qt_pixmap_bit_mask
const uchar qt_pixmap_bit_mask[]
Initial value:
= { 0x01, 0x02, 0x04, 0x08,
                                     0x10, 0x20, 0x40, 0x80 }
Definition at line 62 of file qpixmap_raster.cpp.
Referenced by QRasterPixmapData::setMask().