Qt 4.8: /src/gui/image/qpixmapfilter.cpp File Reference
qpixmapfilter.cpp File Reference
#include <qglobal.h>
#include <QDebug>
#include "qpainter.h"
#include "qpixmap.h"
#include "qpixmapfilter_p.h"
#include "qvarlengtharray.h"
#include "private/qapplication_p.h"
#include "private/qgraphicssystem_p.h"
#include "private/qpaintengineex_p.h"
#include "private/qpaintengine_raster_p.h"
#include "qmath.h"
#include "private/qmath_p.h"
#include "private/qmemrotate_p.h"
#include "private/qdrawhelper_p.h"
Classes
class QPixmapBlurFilterPrivate
class QPixmapColorizeFilterPrivate
class QPixmapConvolutionFilterPrivate
class QPixmapDropShadowFilterPrivate
class QPixmapFilterPrivate
Macros
#define AVG(a, b) (((((a)^(b)) & 0xfefefefeUL) >> 1) + ((a)&(b)))
#define AVG16(a, b) (((((a)^(b)) & 0xf7deUL) >> 1) + ((a)&(b)))
#define Z_MASK (0xff << zprec)
#define ZA_MASK (0xff << (zprec + aprec))
Functions
static void convolute (QImage *destImage, const QPointF &pos, const QImage &srcImage, const QRectF &srcRect, QPainter::CompositionMode mode, qreal *kernel, int kernelWidth, int kernelHeight)
template<int aprec, int zprec, bool alphaOnly>
void expblur (QImage &img, qreal radius, bool improvedQuality=false, int transposed=0)
static void grayscale (const QImage &image, QImage &dest, const QRect &rect=QRect())
Q_GUI_EXPORT void qt_blurImage (QPainter *p, QImage &blurImage, qreal radius, bool quality, bool alphaOnly, int transposed=0)
Q_GUI_EXPORT void qt_blurImage (QImage &blurImage, qreal radius, bool quality, int transposed=0)
template<int aprec, int zprec>
void qt_blurinner (uchar *bptr, int &zR, int &zG, int &zB, int &zA, int alpha)
template<int aprec, int zprec>
void qt_blurinner_alphaOnly (uchar *bptr, int &z, int alpha)
template<int aprec, int zprec, bool alphaOnly>
void qt_blurrow (QImage &im, int line, int alpha)
Q_GUI_EXPORT QImage qt_halfScaled (const QImage &source)
Q_GUI_EXPORT bool qt_scaleForTransform (const QTransform &transform, qreal *scale)
template<int shift>
int qt_static_shift (int value)
Variables
const int alphaIndex = (QSysInfo::ByteOrder == QSysInfo::BigEndian ? 0 : 3)
const qreal radiusScale = qreal(2.5)
Macro Definition Documentation
AVG
#define AVG (a, b) (((((a)^(b)) & 0xfefefefeUL) >> 1) + ((a)&(b)))
Definition at line 794 of file qpixmapfilter.cpp.
Referenced by qt_halfScaled().
AVG16
#define AVG16 (a, b) (((((a)^(b)) & 0xf7deUL) >> 1) + ((a)&(b)))
Definition at line 795 of file qpixmapfilter.cpp.
Referenced by qt_halfScaled().
Z_MASK
#define Z_MASK (0xff << zprec)
Referenced by qt_blurinner().
ZA_MASK
#define ZA_MASK (0xff << (zprec + aprec))
Referenced by qt_blurinner().
Function Documentation
convolute()
static void convolute (QImage * destImage, const QPointF & pos, const QImage & srcImage, const QRectF & srcRect, QPainter::CompositionMode mode, qreal * kernel, int kernelWidth, int kernelHeight) static
Definition at line 322 of file qpixmapfilter.cpp.
Referenced by QPixmapConvolutionFilter::draw().
 {
     const QImage processImage = (srcImage.format() != QImage::Format_ARGB32_Premultiplied ) ?               srcImage.convertToFormat(QImage::Format_ARGB32_Premultiplied) : srcImage;
     // TODO: support also other formats directly without copying
     int *fixedKernel = new int[kernelWidth*kernelHeight];
     for(int i = 0; i < kernelWidth*kernelHeight; i++)
     {
         fixedKernel[i] = (int)(65536 * kernel[i]);
     }
     QRectF trect = srcRect.isNull() ? processImage.rect() : srcRect;
     trect.moveTo(pos);
     QRectF bounded = trect.adjusted(-kernelWidth / 2, -kernelHeight / 2, (kernelWidth - 1) / 2, (kernelHeight - 1) / 2);
     QRect rect = bounded.toAlignedRect();
     QRect targetRect = rect.intersected(destImage->rect());
     QRectF srect = srcRect.isNull() ? processImage.rect() : srcRect;
     QRectF sbounded = srect.adjusted(-kernelWidth / 2, -kernelHeight / 2, (kernelWidth - 1) / 2, (kernelHeight - 1) / 2);
     QPoint srcStartPoint = sbounded.toAlignedRect().topLeft()+(targetRect.topLeft()-rect.topLeft());
     const uint *sourceStart = (uint*)processImage.scanLine(0);
     uint *outputStart = (uint*)destImage->scanLine(0);
     int yk = srcStartPoint.y();
     for (int y = targetRect.top(); y <= targetRect.bottom(); y++) {
         uint* output = outputStart + (destImage->bytesPerLine()/sizeof(uint))*y+targetRect.left();
         int xk = srcStartPoint.x();
         for(int x = targetRect.left(); x <= targetRect.right(); x++) {
             int r = 0;
             int g = 0;
             int b = 0;
             int a = 0;
             // some out of bounds pre-checking to avoid inner-loop ifs
             int kernely = -kernelHeight/2;
             int starty = 0;
             int endy = kernelHeight;
             if(yk+kernely+endy >= srcImage.height())
                 endy = kernelHeight-((yk+kernely+endy)-srcImage.height())-1;
             if(yk+kernely < 0)
                 starty = -(yk+kernely);
             int kernelx = -kernelWidth/2;
             int startx = 0;
             int endx = kernelWidth;
             if(xk+kernelx+endx >= srcImage.width())
                 endx = kernelWidth-((xk+kernelx+endx)-srcImage.width())-1;
             if(xk+kernelx < 0)
                 startx = -(xk+kernelx);
             for (int ys = starty; ys < endy; ys ++) {
                 const uint *pix = sourceStart + (processImage.bytesPerLine()/sizeof(uint))*(yk+kernely+ys) + ((xk+kernelx+startx));
                 const uint *endPix = pix+endx-startx;
                 int kernelPos = ys*kernelWidth+startx;
                 while (pix < endPix) {
                     int factor = fixedKernel[kernelPos++];
                     a += (((*pix) & 0xff000000)>>24) * factor;
                     r += (((*pix) & 0x00ff0000)>>16) * factor;
                     g += (((*pix) & 0x0000ff00)>>8 ) * factor;
                     b += (((*pix) & 0x000000ff)    ) * factor;
                     pix++;
                 }
             }
             r = qBound((int)0, r >> 16, (int)255);
             g = qBound((int)0, g >> 16, (int)255);
             b = qBound((int)0, b >> 16, (int)255);
             a = qBound((int)0, a >> 16, (int)255);
             // composition mode checking could be moved outside of loop
             if(mode == QPainter::CompositionMode_Source) {
                 uint color = (a<<24)+(r<<16)+(g<<8)+b;
                 *output++ = color;
             } else {
                 uint current = *output;
                 uchar ca = (current&0xff000000)>>24;
                 uchar cr = (current&0x00ff0000)>>16;
                 uchar cg = (current&0x0000ff00)>>8;
                 uchar cb = (current&0x000000ff);
                 uint color =
                         (((ca*(255-a) >> 8)+a) << 24)+
                         (((cr*(255-a) >> 8)+r) << 16)+
                         (((cg*(255-a) >> 8)+g) << 8)+
                         (((cb*(255-a) >> 8)+b));
                 *output++ = color;;
             }
             xk++;
         }
         yk++;
     }
     delete[] fixedKernel;
 }
expblur()
template<int aprec, int zprec, bool alphaOnly> void expblur (QImage & img, qreal radius, bool improvedQuality = false, int transposed = 0)
Definition at line 721 of file qpixmapfilter.cpp.
 {
     // halve the radius if we're using two passes
     if (improvedQuality)
         radius *= qreal(0.5);
     Q_ASSERT(img.format() == QImage::Format_ARGB32_Premultiplied
              || img.format() == QImage::Format_RGB32
              || img.format() == QImage::Format_Indexed8);
     // choose the alpha such that pixels at radius distance from a fully
     // saturated pixel will have an alpha component of no greater than
     // the cutOffIntensity
     const qreal cutOffIntensity = 2;
     int alpha = radius <= qreal(1e-5)
         ? ((1 << aprec)-1)
         : qRound((1<<aprec)*(1 - qPow(cutOffIntensity * (1 / qreal(255)), 1 / radius)));
     int img_height = img.height();
     for (int row = 0; row < img_height; ++row) {
         for (int i = 0; i <= int(improvedQuality); ++i)
             qt_blurrow<aprec, zprec, alphaOnly>(img, row, alpha);
     }
     QImage temp(img.height(), img.width(), img.format());
     if (transposed >= 0) {
         if (img.depth() == 8) {
             qt_memrotate270(reinterpret_cast<const quint8*>(img.bits()),
                             img.width(), img.height(), img.bytesPerLine(),
                             reinterpret_cast<quint8*>(temp.bits()),
                             temp.bytesPerLine());
         } else {
             qt_memrotate270(reinterpret_cast<const quint32*>(img.bits()),
                             img.width(), img.height(), img.bytesPerLine(),
                             reinterpret_cast<quint32*>(temp.bits()),
                             temp.bytesPerLine());
         }
     } else {
         if (img.depth() == 8) {
             qt_memrotate90(reinterpret_cast<const quint8*>(img.bits()),
                            img.width(), img.height(), img.bytesPerLine(),
                            reinterpret_cast<quint8*>(temp.bits()),
                            temp.bytesPerLine());
         } else {
             qt_memrotate90(reinterpret_cast<const quint32*>(img.bits()),
                            img.width(), img.height(), img.bytesPerLine(),
                            reinterpret_cast<quint32*>(temp.bits()),
                            temp.bytesPerLine());
         }
     }
     img_height = temp.height();
     for (int row = 0; row < img_height; ++row) {
         for (int i = 0; i <= int(improvedQuality); ++i)
             qt_blurrow<aprec, zprec, alphaOnly>(temp, row, alpha);
     }
     if (transposed == 0) {
         if (img.depth() == 8) {
             qt_memrotate90(reinterpret_cast<const quint8*>(temp.bits()),
                            temp.width(), temp.height(), temp.bytesPerLine(),
                            reinterpret_cast<quint8*>(img.bits()),
                            img.bytesPerLine());
         } else {
             qt_memrotate90(reinterpret_cast<const quint32*>(temp.bits()),
                            temp.width(), temp.height(), temp.bytesPerLine(),
                            reinterpret_cast<quint32*>(img.bits()),
                            img.bytesPerLine());
         }
     } else {
         img = temp;
     }
 }
grayscale()
static void grayscale (const QImage & image, QImage & dest, const QRect & rect = QRect()) static
Definition at line 977 of file qpixmapfilter.cpp.
Referenced by QPixmapColorizeFilter::draw(), and QTiffHandler::read().
 {
     QRect destRect = rect;
     QRect srcRect = rect;
     if (rect.isNull()) {
         srcRect = dest.rect();
         destRect = dest.rect();
     }
     if (&image != &dest) {
         destRect.moveTo(QPoint(0, 0));
     }
     unsigned int *data = (unsigned int *)image.bits();
     unsigned int *outData = (unsigned int *)dest.bits();
     if (dest.size() == image.size() && image.rect() == srcRect) {
         // a bit faster loop for grayscaling everything
         int pixels = dest.width() * dest.height();
         for (int i = 0; i < pixels; ++i) {
             int val = qGray(data[i]);
             outData[i] = qRgba(val, val, val, qAlpha(data[i]));
         }
     } else {
         int yd = destRect.top();
         for (int y = srcRect.top(); y <= srcRect.bottom() && y < image.height(); y++) {
             data = (unsigned int*)image.scanLine(y);
             outData = (unsigned int*)dest.scanLine(yd++);
             int xd = destRect.left();
             for (int x = srcRect.left(); x <= srcRect.right() && x < image.width(); x++) {
                 int val = qGray(data[x]);
                 outData[xd++] = qRgba(val, val, val, qAlpha(data[x]));
             }
         }
     }
 }
qt_blurImage() [1/2]
Q_GUI_EXPORT void qt_blurImage (QPainter * p, QImage & blurImage, qreal radius, bool quality, bool alphaOnly, int transposed = 0)
Definition at line 885 of file qpixmapfilter.cpp.
Referenced by QPixmapBlurFilter::draw(), and QPixmapDropShadowFilter::draw().
 {
     if (blurImage.format() != QImage::Format_ARGB32_Premultiplied
         && blurImage.format() != QImage::Format_RGB32)
     {
         blurImage = blurImage.convertToFormat(QImage::Format_ARGB32_Premultiplied);
     }
     qreal scale = 1;
     if (radius >= 4 && blurImage.width() >= 2 && blurImage.height() >= 2) {
         blurImage = qt_halfScaled(blurImage);
         scale = 2;
         radius *= qreal(0.5);
     }
     if (alphaOnly)
         expblur<12, 10, true>(blurImage, radius, quality, transposed);
     else
         expblur<12, 10, false>(blurImage, radius, quality, transposed);
     if (p) {
         p->scale(scale, scale);
         p->setRenderHint(QPainter::SmoothPixmapTransform);
         p->drawImage(QRect(0, 0, blurImage.width(), blurImage.height()), blurImage);
     }
 }
qt_blurImage() [2/2]
Q_GUI_EXPORT void qt_blurImage (QImage & blurImage, qreal radius, bool quality, int transposed = 0)
Definition at line 912 of file qpixmapfilter.cpp.
Referenced by QGLPixmapBlurFilter::processGL(), and QGLPixmapDropShadowFilter::processGL().
 {
     if (blurImage.format() == QImage::Format_Indexed8)
         expblur<12, 10, true>(blurImage, radius, quality, transposed);
     else
         expblur<12, 10, false>(blurImage, radius, quality, transposed);
 }
qt_blurinner()
template<int aprec, int zprec> void qt_blurinner (uchar * bptr, int & zR, int & zG, int & zB, int & zA, int alpha) inline
Definition at line 631 of file qpixmapfilter.cpp.
 {
     QRgb *pixel = (QRgb *)bptr;
 #define Z_MASK (0xff << zprec)
     const int A_zprec = qt_static_shift<zprec - 24>(*pixel) & Z_MASK;
     const int R_zprec = qt_static_shift<zprec - 16>(*pixel) & Z_MASK;
     const int G_zprec = qt_static_shift<zprec - 8>(*pixel)  & Z_MASK;
     const int B_zprec = qt_static_shift<zprec>(*pixel)      & Z_MASK;
 #undef Z_MASK
     const int zR_zprec = zR >> aprec;
     const int zG_zprec = zG >> aprec;
     const int zB_zprec = zB >> aprec;
     const int zA_zprec = zA >> aprec;
     zR += alpha * (R_zprec - zR_zprec);
     zG += alpha * (G_zprec - zG_zprec);
     zB += alpha * (B_zprec - zB_zprec);
     zA += alpha * (A_zprec - zA_zprec);
 #define ZA_MASK (0xff << (zprec + aprec))
     *pixel =
         qt_static_shift<24 - zprec - aprec>(zA & ZA_MASK)
         | qt_static_shift<16 - zprec - aprec>(zR & ZA_MASK)
         | qt_static_shift<8 - zprec - aprec>(zG & ZA_MASK)
         | qt_static_shift<-zprec - aprec>(zB & ZA_MASK);
 #undef ZA_MASK
 }
qt_blurinner_alphaOnly()
template<int aprec, int zprec> void qt_blurinner_alphaOnly (uchar * bptr, int & z, int alpha) inline
Definition at line 664 of file qpixmapfilter.cpp.
 {
     const int A_zprec = int(*(bptr)) << zprec;
     const int z_zprec = z >> aprec;
     z += alpha * (A_zprec - z_zprec);
     *(bptr) = z >> (zprec + aprec);
 }
qt_blurrow()
template<int aprec, int zprec, bool alphaOnly> void qt_blurrow (QImage & im, int line, int alpha) inline
Definition at line 673 of file qpixmapfilter.cpp.
 {
     uchar *bptr = im.scanLine(line);
     int zR = 0, zG = 0, zB = 0, zA = 0;
     if (alphaOnly && im.format() != QImage::Format_Indexed8)
         bptr += alphaIndex;
     const int stride = im.depth() >> 3;
     const int im_width = im.width();
     for (int index = 0; index < im_width; ++index) {
         if (alphaOnly)
             qt_blurinner_alphaOnly<aprec, zprec>(bptr, zA, alpha);
         else
             qt_blurinner<aprec, zprec>(bptr, zR, zG, zB, zA, alpha);
         bptr += stride;
     }
     bptr -= stride;
     for (int index = im_width - 2; index >= 0; --index) {
         bptr -= stride;
         if (alphaOnly)
             qt_blurinner_alphaOnly<aprec, zprec>(bptr, zA, alpha);
         else
             qt_blurinner<aprec, zprec>(bptr, zR, zG, zB, zA, alpha);
     }
 }
qt_halfScaled()
Q_GUI_EXPORT QImage qt_halfScaled (const QImage & source)
Definition at line 797 of file qpixmapfilter.cpp.
Referenced by QGLBlurTextureInfo::paddedImage(), QGLPixmapBlurFilter::processGL(), QGLPixmapDropShadowFilter::processGL(), and qt_blurImage().
 {
     if (source.width() < 2 || source.height() < 2)
         return QImage();
     QImage srcImage = source;
     if (source.format() == QImage::Format_Indexed8) {
         // assumes grayscale
         QImage dest(source.width() / 2, source.height() / 2, srcImage.format());
         const uchar *src = reinterpret_cast<const uchar*>(const_cast<const QImage &>(srcImage).bits());
         int sx = srcImage.bytesPerLine();
         int sx2 = sx << 1;
         uchar *dst = reinterpret_cast<uchar*>(dest.bits());
         int dx = dest.bytesPerLine();
         int ww = dest.width();
         int hh = dest.height();
         for (int y = hh; y; --y, dst += dx, src += sx2) {
             const uchar *p1 = src;
             const uchar *p2 = src + sx;
             uchar *q = dst;
             for (int x = ww; x; --x, ++q, p1 += 2, p2 += 2)
                 *q = ((int(p1[0]) + int(p1[1]) + int(p2[0]) + int(p2[1])) + 2) >> 2;
         }
         return dest;
     } else if (source.format() == QImage::Format_ARGB8565_Premultiplied) {
         QImage dest(source.width() / 2, source.height() / 2, srcImage.format());
         const uchar *src = reinterpret_cast<const uchar*>(const_cast<const QImage &>(srcImage).bits());
         int sx = srcImage.bytesPerLine();
         int sx2 = sx << 1;
         uchar *dst = reinterpret_cast<uchar*>(dest.bits());
         int dx = dest.bytesPerLine();
         int ww = dest.width();
         int hh = dest.height();
         for (int y = hh; y; --y, dst += dx, src += sx2) {
             const uchar *p1 = src;
             const uchar *p2 = src + sx;
             uchar *q = dst;
             for (int x = ww; x; --x, q += 3, p1 += 6, p2 += 6) {
                 // alpha
                 q[0] = AVG(AVG(p1[0], p1[3]), AVG(p2[0], p2[3]));
                 // rgb
                 const quint16 p16_1 = (p1[2] << 8) | p1[1];
                 const quint16 p16_2 = (p1[5] << 8) | p1[4];
                 const quint16 p16_3 = (p2[2] << 8) | p2[1];
                 const quint16 p16_4 = (p2[5] << 8) | p2[4];
                 const quint16 result = AVG16(AVG16(p16_1, p16_2), AVG16(p16_3, p16_4));
                 q[1] = result & 0xff;
                 q[2] = result >> 8;
             }
         }
         return dest;
     } else if (source.format() != QImage::Format_ARGB32_Premultiplied
                && source.format() != QImage::Format_RGB32)
     {
         srcImage = source.convertToFormat(QImage::Format_ARGB32_Premultiplied);
     }
     QImage dest(source.width() / 2, source.height() / 2, srcImage.format());
     const quint32 *src = reinterpret_cast<const quint32*>(const_cast<const QImage &>(srcImage).bits());
     int sx = srcImage.bytesPerLine() >> 2;
     int sx2 = sx << 1;
     quint32 *dst = reinterpret_cast<quint32*>(dest.bits());
     int dx = dest.bytesPerLine() >> 2;
     int ww = dest.width();
     int hh = dest.height();
     for (int y = hh; y; --y, dst += dx, src += sx2) {
         const quint32 *p1 = src;
         const quint32 *p2 = src + sx;
         quint32 *q = dst;
         for (int x = ww; x; --x, q++, p1 += 2, p2 += 2)
             *q = AVG(AVG(p1[0], p1[1]), AVG(p2[0], p2[1]));
     }
     return dest;
 }
qt_scaleForTransform()
Q_GUI_EXPORT bool qt_scaleForTransform (const QTransform & transform, qreal * scale)
Definition at line 2407 of file qtransform.cpp.
Referenced by QPixmapBlurFilter::draw(), qt_blurImage(), and QX11PaintEngine::updateMatrix().
 {
     const QTransform::TransformationType type = transform.type();
     if (type <= QTransform::TxTranslate) {
         if (scale)
             *scale = 1;
         return true;
     } else if (type == QTransform::TxScale) {
         const qreal xScale = qAbs(transform.m11());
         const qreal yScale = qAbs(transform.m22());
         if (scale)
             *scale = qMax(xScale, yScale);
         return qFuzzyCompare(xScale, yScale);
     }
     const qreal xScale = transform.m11() * transform.m11()
                          + transform.m21() * transform.m21();
     const qreal yScale = transform.m12() * transform.m12()
                          + transform.m22() * transform.m22();
     if (scale)
         *scale = qSqrt(qMax(xScale, yScale));
     return type == QTransform::TxRotate && qFuzzyCompare(xScale, yScale);
 }
qt_static_shift()
template<int shift> int qt_static_shift (int value) inline
Definition at line 620 of file qpixmapfilter.cpp.
Referenced by qt_blurinner().
 {
     if (shift == 0)
         return value;
     else if (shift > 0)
         return value << (uint(shift) & 0x1f);
     else
         return value >> (uint(-shift) & 0x1f);
 }
Variable Documentation
alphaIndex
const int alphaIndex = (QSysInfo::ByteOrder == QSysInfo::BigEndian ? 0 : 3)
Definition at line 661 of file qpixmapfilter.cpp.
Referenced by qt_blurrow().
radiusScale
const qreal radiusScale = qreal(2.5)
Definition at line 607 of file qpixmapfilter.cpp.
Referenced by QPixmapBlurFilter::boundingRectFor(), and QPixmapBlurFilter::draw().