Qt 4.8: /src/opengl/qpixmapdata_gl.cpp File Reference
qpixmapdata_gl.cpp File Reference
#include "qpixmap.h"
#include "qglframebufferobject.h"
#include <private/qpaintengine_raster_p.h>
#include "qpixmapdata_gl_p.h"
#include <private/qgl_p.h>
#include <private/qdrawhelper_p.h>
#include <private/qimage_p.h>
#include <private/qfont_p.h>
#include <private/qpaintengineex_opengl2_p.h>
#include <qdesktopwidget.h>
#include <qfile.h>
#include <qimagereader.h>
#include <qbuffer.h>
Classes
struct TextureBuffer
Functions
static int areaDiff (const QSize &size, const QGLFramebufferObject *fbo)
static QSize maybeRoundToNextPowerOfTwo (const QSize &sz)
QGLFramebufferObjectPool * qgl_fbo_pool ()
QRgb qt_gl_convertToGLFormat (QRgb src_pixel, GLenum texture_format)
QImage qt_gl_read_texture (const QSize &size, bool alpha_format, bool include_alpha)
Q_OPENGL_EXPORT const QGLContext * qt_gl_share_context ()
int qt_next_power_of_two (int v)
Variables
static int qt_gl_pixmap_serial = 0
Function Documentation
areaDiff()
static int areaDiff (const QSize & size, const QGLFramebufferObject * fbo) inline static
Definition at line 81 of file qpixmapdata_gl.cpp.
Referenced by QGLFramebufferObjectPool::acquire().
 {
     return qAbs(size.width() * size.height() - fbo->width() * fbo->height());
 }
maybeRoundToNextPowerOfTwo()
static QSize maybeRoundToNextPowerOfTwo (const QSize & sz) inline static
Definition at line 88 of file qpixmapdata_gl.cpp.
Referenced by QGLFramebufferObjectPool::acquire().
 {
 #ifdef QT_OPENGL_ES_2
     QSize rounded(qt_next_power_of_two(sz.width()), qt_next_power_of_two(sz.height()));
     if (rounded.width() * rounded.height() < 1.20 * sz.width() * sz.height())
         return rounded;
 #endif
     return sz;
 }
qgl_fbo_pool()
QGLFramebufferObjectPool* qgl_fbo_pool ()
Definition at line 663 of file qpixmapdata_gl.cpp.
Referenced by QGLPixmapGLPaintDevice::endPaint(), QGLWindowSurface::flush(), and QGLPixmapData::paintEngine().
 {
     return _qgl_fbo_pool();
 }
qt_gl_convertToGLFormat()
QRgb qt_gl_convertToGLFormat (QRgb src_pixel, GLenum texture_format)
Definition at line 2281 of file qgl.cpp.
Referenced by QGLPixmapData::bind(), and QGLPixmapData::paintEngine().
 {
     return qt_gl_convertToGLFormatHelper(src_pixel, texture_format);
 }
qt_gl_read_texture()
QImage qt_gl_read_texture (const QSize & size, bool alpha_format, bool include_alpha)
Definition at line 1871 of file qgl.cpp.
Referenced by QGLPixmapData::fillImage(), and QGLPixmapData::toImage().
 {
     QImage img(size, alpha_format ? QImage::Format_ARGB32_Premultiplied : QImage::Format_RGB32);
     int w = size.width();
     int h = size.height();
 #if !defined(QT_OPENGL_ES_2) && !defined(QT_OPENGL_ES_1)
     //### glGetTexImage not in GL ES 2.0, need to do something else here!
     glGetTexImage(GL_TEXTURE_2D, 0, GL_RGBA, GL_UNSIGNED_BYTE, img.bits());
 #endif
     convertFromGLImage(img, w, h, alpha_format, include_alpha);
     return img;
 }
qt_gl_share_context()
Q_OPENGL_EXPORT const QGLContext* qt_gl_share_context ()
Definition at line 284 of file qwindowsurface_gl.cpp.
Referenced by QGLPixmapData::copy(), QGLPixmapData::copyBackFromRenderFbo(), QGLPixmapData::createPixmapForImage(), QGLPixmapData::ensureCreated(), QGLPixmapData::fromData(), QGLPixmapData::fromFile(), QGLWindowSurface::hijackWindow(), QGLPixmapData::isValidContext(), QGLPixmapData::paintEngine(), QGLPixmapData::resize(), QGLPixmapData::toImage(), QGLPixmapData::~QGLPixmapData(), and QGLWindowSurface::~QGLWindowSurface().
 {
     QGLWidget *widget = qt_gl_share_widget();
     if (widget)
         return widget->context();
     return 0;
 }
qt_next_power_of_two()
int qt_next_power_of_two (int v)
Definition at line 1886 of file qgl.cpp.
Referenced by areaDiff(), and maybeRoundToNextPowerOfTwo().
 {
     v--;
     v |= v >> 1;
     v |= v >> 2;
     v |= v >> 4;
     v |= v >> 8;
     v |= v >> 16;
     ++v;
     return v;
 }
Variable Documentation
qt_gl_pixmap_serial
int qt_gl_pixmap_serial = 0 static
Definition at line 252 of file qpixmapdata_gl.cpp.
Referenced by QGLPixmapData::createPixmapForImage(), QGLPixmapData::QGLPixmapData(), and QGLPixmapData::resize().