Qt 4.8: /src/gui/image/qpixmap.cpp File Reference
qpixmap.cpp File Reference
#include <qglobal.h>
#include "qpixmap.h"
#include "qpixmapdata_p.h"
#include "qimagepixmapcleanuphooks_p.h"
#include "qbitmap.h"
#include "qcolormap.h"
#include "qimage.h"
#include "qwidget.h"
#include "qpainter.h"
#include "qdatastream.h"
#include "qbuffer.h"
#include "qapplication.h"
#include <private/qapplication_p.h>
#include <private/qgraphicssystem_p.h>
#include <private/qwidget_p.h>
#include "qevent.h"
#include "qfile.h"
#include "qfileinfo.h"
#include "qpixmapcache.h"
#include "qdatetime.h"
#include "qimagereader.h"
#include "qimagewriter.h"
#include "qpaintengine.h"
#include "qthread.h"
#include "private/qt_mac_p.h"
#include "private/qpixmap_mac_p.h"
#include "qx11info_x11.h"
#include <private/qt_x11_p.h>
#include <private/qpixmap_x11_p.h>
#include "qpixmap_raster_p.h"
#include "private/qstylehelper_p.h"
Functions
Q_GUI_EXPORT qint64 qt_pixmap_id (const QPixmap &pixmap)
static bool qt_pixmap_thread_test ()
static void sendResizeEvents (QWidget *target)
Variables
QApplication::Type qt_appType
Function Documentation
qt_pixmap_id()
Q_GUI_EXPORT qint64 qt_pixmap_id (const QPixmap & pixmap)
Definition at line 94 of file qpixmap.cpp.
Referenced by QPdfEnginePrivate::addBrushPattern(), and QItemDelegate::selected().
 {
     return pixmap.cacheKey();
 }
qt_pixmap_thread_test()
static bool qt_pixmap_thread_test () static
Definition at line 99 of file qpixmap.cpp.
Referenced by QPixmap::handle(), and QPixmap::QPixmap().
 {
     if (!qApp) {
         qFatal("QPixmap: Must construct a QApplication before a QPaintDevice");
         return false;
     }
     if (qApp->thread() != QThread::currentThread()) {
         bool fail = false;
 #if defined (Q_WS_X11)
         if (!QApplication::testAttribute(Qt::AA_X11InitThreads))
             fail = true;
 #elif defined (Q_WS_QPA)
         if (!QApplicationPrivate::platformIntegration()->hasCapability(QPlatformIntegration::ThreadedPixmaps)) {
             printf("Lighthouse plugin does not support threaded pixmaps!\n");
             fail = true;
         }
 #else
         if (QApplicationPrivate::graphics_system_name != QLatin1String("raster"))
             fail = true;
 #endif
         if (fail) {
             qWarning("QPixmap: It is not safe to use pixmaps outside the GUI thread");
             return false;
         }
     }
     return true;
 }
sendResizeEvents()
static void sendResizeEvents (QWidget * target) static
Definition at line 1145 of file qpixmap.cpp.
Referenced by QPixmap::grabWidget().
 {
     QResizeEvent e(target->size(), QSize());
     QApplication::sendEvent(target, &e);
     const QObjectList children = target->children();
     for (int i = 0; i < children.size(); ++i) {
         QWidget *child = static_cast<QWidget*>(children.at(i));
         if (child->isWidgetType() && !child->isWindow() && child->testAttribute(Qt::WA_PendingResizeEvent))
             sendResizeEvents(child);
     }
 }
Variable Documentation
qt_appType
QApplication::Type qt_appType
Definition at line 163 of file qapplication.cpp.
Referenced by QPixmap::init().