Qt 4.8: /src/gui/image/qpixmap_x11.cpp File Reference
qpixmap_x11.cpp File Reference
#include "qplatformdefs.h"
#include "qdebug.h"
#include "qiodevice.h"
#include "qpixmap_x11_p.h"
#include "qbitmap.h"
#include "qcolormap.h"
#include "qimage.h"
#include "qmatrix.h"
#include "qapplication.h"
#include <private/qpaintengine_x11_p.h>
#include <private/qt_x11_p.h>
#include "qx11info_x11.h"
#include <private/qdrawhelper_p.h>
#include <private/qimage_p.h>
#include <private/qimagepixmapcleanuphooks_p.h>
#include <stdlib.h>
Classes
struct QX11AlphaDetector
struct QXImageWrapper
Macros
#define CYCLE(body)
#define GET_PIXEL
#define GET_PIXEL_DITHER_TC
#define GET_PIXEL_DITHER_TC_OPT(red_shift, green_shift, blue_shift, red_mask, green_mask, blue_mask, rbits, gbits, bbits)
Functions
static void build_scale_table (uint **table, uint nBits)
static void cleanup_scale_tables ()
static int highest_bit (uint v)
static int lowest_bit (uint v)
static uint n_bits (uint v)
static void qSafeXDestroyImage (XImage *x)
const uchar * qt_get_bitflip_array ()
static XRenderPictFormat * qt_renderformat_for_depth (const QX11Info &xinfo, int depth)
QPixmap qt_toX11Pixmap (const QImage &image)
QPixmap qt_toX11Pixmap (const QPixmap &pixmap)
Variables
static uint * blue_scale_table = 0
static int defaultScreen = -1
static uint * green_scale_table = 0
QBasicAtomicInt qt_pixmap_serial = Q_BASIC_ATOMIC_INITIALIZER(0)
int Q_GUI_EXPORT qt_x11_preferred_pixmap_depth = 0
static uint * red_scale_table = 0
Macro Definition Documentation
CYCLE
#define CYCLE (body)
Value:
for (int y=0; y<h; y++) {                               \
            const uchar* src = cimage.scanLine(y);              \
            uchar* dst = newbits + xi->bytes_per_line*y;        \
            const QRgb* p = (const QRgb *)src;                  \
            body                                                \
                }
Referenced by QX11PixmapData::fromImage().
GET_PIXEL
#define GET_PIXEL
Value:
uint pixel;                                                     \
        if (d8) pixel = pix[*src++];                                    \
        else {                                                          \
            int r = qRed  (*p);                                         \
            int g = qGreen(*p);                                         \
            int b = qBlue (*p++);                                       \
            r = red_shift   > 0                                         \
                ? r << red_shift   : r >> -red_shift;                   \
            g = green_shift > 0                                         \
                ? g << green_shift : g >> -green_shift;                 \
            b = blue_shift  > 0                                         \
                ? b << blue_shift  : b >> -blue_shift;                  \
            pixel = (r & red_mask)|(g & green_mask) | (b & blue_mask)   \
                    | ~(blue_mask | green_mask | red_mask);             \
        }
Referenced by QX11PixmapData::fromImage().
GET_PIXEL_DITHER_TC
#define GET_PIXEL_DITHER_TC
Value:
int r = qRed  (*p);                                             \
        int g = qGreen(*p);                                             \
        int b = qBlue (*p++);                                           \
        const int thres = D[x%16][y%16];                                \
        if (r <= (255-(1<<(8-rbits))) && ((r<<rbits) & 255)             \
            > thres)                                                    \
            r += (1<<(8-rbits));                                        \
        if (g <= (255-(1<<(8-gbits))) && ((g<<gbits) & 255)             \
            > thres)                                                    \
            g += (1<<(8-gbits));                                        \
        if (b <= (255-(1<<(8-bbits))) && ((b<<bbits) & 255)             \
            > thres)                                                    \
            b += (1<<(8-bbits));                                        \
        r = red_shift   > 0                                             \
            ? r << red_shift   : r >> -red_shift;                       \
        g = green_shift > 0                                             \
            ? g << green_shift : g >> -green_shift;                     \
        b = blue_shift  > 0                                             \
            ? b << blue_shift  : b >> -blue_shift;                      \
        uint pixel = (r & red_mask)|(g & green_mask) | (b & blue_mask);
Referenced by QX11PixmapData::fromImage().
GET_PIXEL_DITHER_TC_OPT
#define GET_PIXEL_DITHER_TC_OPT (red_shift, green_shift, blue_shift, red_mask, green_mask, blue_mask, rbits, gbits, bbits)
Value:
const int thres = D[x%16][y%16];                                \
        int r = qRed  (*p);                                             \
        if (r <= (255-(1<<(8-rbits))) && ((r<<rbits) & 255)             \
            > thres)                                                    \
            r += (1<<(8-rbits));                                        \
        int g = qGreen(*p);                                             \
        if (g <= (255-(1<<(8-gbits))) && ((g<<gbits) & 255)             \
            > thres)                                                    \
            g += (1<<(8-gbits));                                        \
        int b = qBlue (*p++);                                           \
        if (b <= (255-(1<<(8-bbits))) && ((b<<bbits) & 255)             \
            > thres)                                                    \
            b += (1<<(8-bbits));                                        \
        uint pixel = ((r red_shift) & red_mask)                         \
                     | ((g green_shift) & green_mask)                   \
                     | ((b blue_shift) & blue_mask);
Referenced by QX11PixmapData::fromImage().
Function Documentation
build_scale_table()
static void build_scale_table (uint ** table, uint nBits) static
Definition at line 286 of file qpixmap_x11.cpp.
Referenced by QX11PixmapData::toImage().
 {
     if (nBits > 7) {
         qWarning("build_scale_table: internal error, nBits = %i", nBits);
         return;
     }
     if (!*table) {
         static bool firstTable = true;
         if (firstTable) {
             qAddPostRoutine(cleanup_scale_tables);
             firstTable = false;
         }
         *table = new uint[256];
     }
     int   maxVal   = (1 << nBits) - 1;
     int   valShift = 8 - nBits;
     int i;
     for(i = 0 ; i < maxVal + 1 ; i++)
         (*table)[i << valShift] = i*255/maxVal;
 }
cleanup_scale_tables()
static void cleanup_scale_tables () static
Definition at line 275 of file qpixmap_x11.cpp.
Referenced by build_scale_table().
 {
     delete[] red_scale_table;
     delete[] green_scale_table;
     delete[] blue_scale_table;
 }
highest_bit()
static int highest_bit (uint v) static
Definition at line 241 of file qpixmap_x11.cpp.
Referenced by QX11PixmapData::fromImage(), and QX11PixmapData::toImage().
 {
     int i;
     uint b = (uint)1 << 31;
     for (i=31; ((b & v) == 0) && i>=0;         i--)
         b >>= 1;
     return i;
 }
lowest_bit()
static int lowest_bit (uint v) static
Definition at line 251 of file qpixmap_x11.cpp.
Referenced by QX11PixmapData::fromImage().
 {
     int i;
     ulong lb;
     lb = 1;
     for (i=0; ((v & lb) == 0) && i<32;  i++, lb<<=1) {}
     return i==32 ? -1 : i;
 }
n_bits()
static uint n_bits (uint v) static
Definition at line 261 of file qpixmap_x11.cpp.
Referenced by QX11PixmapData::fromImage(), and QX11PixmapData::toImage().
 {
     int i = 0;
     while (v) {
         v = v & (v - 1);
         i++;
     }
     return i;
 }
qSafeXDestroyImage()
static void qSafeXDestroyImage (XImage * x) inline static
Definition at line 107 of file qpixmap_x11.cpp.
Referenced by QX11PixmapData::bitmap_to_mask(), QX11PixmapData::fromImage(), QX11PixmapData::toImage(), and QX11PixmapData::transformed().
 {
     if (x->data) {
         free(x->data);
         x->data = 0;
     }
     XDestroyImage(x);
 }
qt_get_bitflip_array()
const uchar* qt_get_bitflip_array ()
Definition at line 765 of file qimage.cpp.
Referenced by QX11PixmapData::bitmap_to_mask().
 {
     return bitflip;
 }
qt_renderformat_for_depth()
static XRenderPictFormat* qt_renderformat_for_depth (const QX11Info & xinfo, int depth) static
Definition at line 2189 of file qpixmap_x11.cpp.
Referenced by QX11PixmapData::convertToARGB32(), and QX11PixmapData::paintEngine().
 {
     if (depth == 1)
         return XRenderFindStandardFormat(X11->display, PictStandardA1);
     else if (depth == 32)
         return XRenderFindStandardFormat(X11->display, PictStandardARGB32);
     else
         return XRenderFindVisualFormat(X11->display, (Visual *)xinfo.visual());
 }
qt_toX11Pixmap() [1/2]
QPixmap qt_toX11Pixmap (const QImage & image)
Definition at line 81 of file qpixmap_x11.cpp.
Referenced by QWidgetPrivate::mapFromGlobal(), QCursor::QCursor(), qstring_to_xtp(), qt_toX11Pixmap(), and QX11PixmapData::transformed().
 {
     QPixmapData *data =
         new QX11PixmapData(image.depth() == 1
                            ? QPixmapData::BitmapType
                            : QPixmapData::PixmapType);
     data->fromImage(image, Qt::AutoColor);
     return QPixmap(data);
 }
qt_toX11Pixmap() [2/2]
QPixmap qt_toX11Pixmap (const QPixmap & pixmap)
Definition at line 93 of file qpixmap_x11.cpp.
Referenced by QX11PaintEngine::drawPixmap(), and QX11PaintEngine::updateBrush().
 {
     if (pixmap.isNull())
         return QPixmap();
     if (QPixmap(pixmap).data_ptr()->classId() == QPixmapData::X11Class)
         return pixmap;
     return qt_toX11Pixmap(pixmap.toImage());
 }
Variable Documentation
blue_scale_table
uint* blue_scale_table = 0 static
Definition at line 273 of file qpixmap_x11.cpp.
Referenced by cleanup_scale_tables(), and QX11PixmapData::toImage().
defaultScreen
int defaultScreen = -1 static
Definition at line 307 of file qpixmap_x11.cpp.
Referenced by QX11PixmapData::convertToARGB32(), QX11PixmapData::fromImage(), QX11PixmapData::resize(), and QX11PixmapData::transformed().
green_scale_table
uint* green_scale_table = 0 static
Definition at line 272 of file qpixmap_x11.cpp.
Referenced by cleanup_scale_tables(), and QX11PixmapData::toImage().
qt_pixmap_serial
QBasicAtomicInt qt_pixmap_serial = Q_BASIC_ATOMIC_INITIALIZER(0)
Definition at line 313 of file qpixmap_x11.cpp.
qt_x11_preferred_pixmap_depth
int Q_GUI_EXPORT qt_x11_preferred_pixmap_depth = 0
Definition at line 314 of file qpixmap_x11.cpp.
Referenced by QX11PixmapData::fromImage(), and QX11PixmapData::resize().
red_scale_table
uint* red_scale_table = 0 static
Definition at line 271 of file qpixmap_x11.cpp.
Referenced by cleanup_scale_tables(), and QX11PixmapData::toImage().