Qt 4.8: /src/openvg/qpixmapfilter_vg.cpp File Reference
qpixmapfilter_vg.cpp File Reference
#include "qpixmapfilter_vg_p.h"
#include "qvgimagepool_p.h"
#include <QtCore/qvarlengtharray.h>
#include <QtGui/qpainter.h>
Functions
void qt_vg_drawVGImage (QPainter *painter, const QPointF &pos, VGImage vgImg)
void qt_vg_drawVGImageStencil (QPainter *painter, const QPointF &pos, VGImage vgImg, const QBrush &brush)
Function Documentation
qt_vg_drawVGImage()
void qt_vg_drawVGImage (QPainter * painter, const QPointF & pos, VGImage vgImg)
Definition at line 3278 of file qpaintengine_vg.cpp.
Referenced by QVGPixmapConvolutionFilter::draw(), QVGPixmapColorizeFilter::draw(), QVGPixmapBlurFilter::draw(), and QVGPixmapConvolutionFilter::~QVGPixmapConvolutionFilter().
 {
     QVGPaintEngine *engine =
         static_cast<QVGPaintEngine *>(painter->paintEngine());
     drawVGImage(engine->vgPrivate(), pos, vgImg);
 }
qt_vg_drawVGImageStencil()
void qt_vg_drawVGImageStencil (QPainter * painter, const QPointF & pos, VGImage vgImg, const QBrush & brush)
Definition at line 3287 of file qpaintengine_vg.cpp.
Referenced by QVGPixmapDropShadowFilter::draw(), qt_vg_drawVGImage(), and QVGPixmapConvolutionFilter::~QVGPixmapConvolutionFilter().
 {
     QVGPaintEngine *engine =
         static_cast<QVGPaintEngine *>(painter->paintEngine());
     QVGPaintEnginePrivate *d = engine->vgPrivate();
     QTransform transform(d->imageTransform);
     transform.translate(pos.x(), pos.y());
     d->setTransform(VG_MATRIX_IMAGE_USER_TO_SURFACE, transform);
     d->ensureBrush(brush);
     d->setImageMode(VG_DRAW_IMAGE_STENCIL);
     vgDrawImage(vgImg);
 }