Qt 4.8: /src/gui/image/qpixmap_win.cpp File Reference
qpixmap_win.cpp File Reference
#include "qpixmap.h"
#include "qpixmap_raster_p.h"
#include "qbitmap.h"
#include "qimage.h"
#include "qwidget.h"
#include "qpainter.h"
#include "qdatastream.h"
#include "qbuffer.h"
#include "qapplication.h"
#include "qevent.h"
#include "qfile.h"
#include "qfileinfo.h"
#include "qdatetime.h"
#include "qpixmapcache.h"
#include "qimagereader.h"
#include "qimagewriter.h"
#include "qdebug.h"
#include "qt_windows.h"
#include <winbase.h>
#include "qguifunctions_wince.h"
Macros
#define CAPTUREBLT ((DWORD)0x40000000)
Functions
HBITMAP qt_createIconMask (const QBitmap &bitmap)
bool qt_wince_is_high_dpi ()
bool qt_wince_is_pocket_pc ()
Macro Definition Documentation
CAPTUREBLT
#define CAPTUREBLT ((DWORD)0x40000000)
Definition at line 70 of file qpixmap_win.cpp.
Function Documentation
qt_createIconMask()
HBITMAP qt_createIconMask (const QBitmap & bitmap)
Definition at line 242 of file qpixmap_win.cpp.
Referenced by create32BitCursor(), QCursor::QCursor(), and QPixmap::toWinHICON().
 {
     QImage bm = bitmap.toImage().convertToFormat(QImage::Format_Mono);
     int w = bm.width();
     int h = bm.height();
     int bpl = ((w+15)/16)*2;                        // bpl, 16 bit alignment
     uchar *bits = new uchar[bpl*h];
     bm.invertPixels();
     for (int y=0; y<h; y++)
         memcpy(bits+y*bpl, bm.scanLine(y), bpl);
     HBITMAP hbm = CreateBitmap(w, h, 1, 1, bits);
     delete [] bits;
     return hbm;
 }
qt_wince_is_high_dpi()
bool qt_wince_is_high_dpi ()
Definition at line 300 of file qguifunctions_wince.cpp.
{
     if (!qt_wince_is_pocket_pc())
         return false;
     HDC deviceContext = GetDC(0);
     int dpi = GetDeviceCaps(deviceContext, LOGPIXELSX);
     ReleaseDC(0, deviceContext);
     if ((dpi < 1000) && (dpi > 0))
         return dpi > 96;
     else
         return false;
 }
qt_wince_is_pocket_pc()
bool qt_wince_is_pocket_pc ()
Definition at line 289 of file qguifunctions_wince.cpp.
{
     return qt_wince_is_platform(QString::fromLatin1("PocketPC"));
 }