Qt 4.8: /src/gui/kernel/qplatformscreen_qpa.cpp File Reference
qplatformscreen_qpa.cpp File Reference
#include "qplatformscreen_qpa.h"
#include <QtGui/qapplication.h>
#include <QtGui/private/qapplication_p.h>
#include <QtGui/qdesktopwidget.h>
#include <QtGui/qplatformintegration_qpa.h>
#include <QtGui/qwidget.h>
#include <QtGui/private/qwidget_p.h>
Functions
Q_GUI_EXPORT QWidgetPrivate * qt_widget_private (QWidget *widget)
Function Documentation
qt_widget_private()
Q_GUI_EXPORT QWidgetPrivate* qt_widget_private (QWidget * widget)
Definition at line 12920 of file qwidget.cpp.
Referenced by QVGWindowSurface::beginPaint(), QRasterWindowSurface::beginPaint(), QVGGraphicsSystem::createWindowSurface(), QGLGraphicsSystem::createWindowSurface(), QGraphicsViewPrivate::dispatchPendingUpdateRequests(), QInputDialogPrivate::ensureComboBox(), QInputDialogPrivate::ensureLineEdit(), QDirectFBWindowSurface::flush(), QRasterWindowSurface::flush(), QPixmap::grabWidget(), QTabWidgetPrivate::hasHeightForWidth(), QGLWidgetPrivate::init(), macWindowToolbarShow(), QDeclarativeTextInput::mouseReleaseEvent(), QDeclarativeTextEdit::mouseReleaseEvent(), QGraphicsTextItem::mouseReleaseEvent(), QApplication::notify(), QPlatformScreen::physicalSize(), QPlatformScreen::platformScreenForWidget(), qstring_to_xtp(), qt_dirtyRegion(), qt_event_request_window_change(), qt_mac_post_retranslateAppMenu(), qt_mac_send_posted_gl_updates(), qt_mac_update_child_gl_widgets(), qt_mac_update_intersected_gl_widgets(), qt_mac_update_widget_position(), qt_post_window_change_event(), qt_reg_winclass(), QWidgetBackingStoreTracker::registerWidget(), QMdi::ControlContainer::removeButtonsFromMenuBar(), QRasterWindowSurface::setGeometry(), QRuntimeGraphicsSystem::setGraphicsSystem(), QGL2PaintEngineExPrivate::systemStateChanged(), QAccessible::updateAccessibility(), QOpenGLPaintEngine::updateClipRegion(), QTabBarPrivate::updateMacBorderMetrics(), and updateRedirectedToGraphicsProxyWidget().
 {
     return widget->d_func();
 }