Qt 4.8: /src/gui/styles/qplastiquestyle.cpp File Reference
qplastiquestyle.cpp File Reference
#include "qplastiquestyle.h"
#include "qwindowsstyle_p.h"
#include <qapplication.h>
#include <qbitmap.h>
#include <qabstractitemview.h>
#include <qcheckbox.h>
#include <qcombobox.h>
#include <qdebug.h>
#include <qdialogbuttonbox.h>
#include <qformlayout.h>
#include <qgroupbox.h>
#include <qimage.h>
#include <qlineedit.h>
#include <qmainwindow.h>
#include <qmenu.h>
#include <qmenubar.h>
#include <qpainter.h>
#include <qpaintengine.h>
#include <qpainterpath.h>
#include <qpalette.h>
#include <qpen.h>
#include <qpixmap.h>
#include <qpixmapcache.h>
#include <qprogressbar.h>
#include <qpushbutton.h>
#include <qradiobutton.h>
#include <qscrollbar.h>
#include <qspinbox.h>
#include <qsplitter.h>
#include <qstyleoption.h>
#include <qtextedit.h>
#include <qelapsedtimer.h>
#include <qtoolbar.h>
#include <qtoolbox.h>
#include <qtoolbutton.h>
#include <qworkspace.h>
#include <qprocess.h>
#include <qvarlengtharray.h>
#include <limits.h>
#include <private/qstylehelper_p.h>
Classes
class QPlastiqueStylePrivate
Macros
#define CT1(c) CT2(c, c)
#define CT2(c1, c2) (((uint)c1 << 16) | (uint)c2)
Functions
static QString elliditide (const QString &text, const QFontMetrics &fontMetrics, const QRect &rect, int *textWidth=0)
static QColor mergedColors (const QColor &colorA, const QColor &colorB, int factor=50)
static QBrush qBrushDark (QBrush brush, int dark)
static QBrush qBrushLight (QBrush brush, int light)
static void qBrushSetAlphaF (QBrush *brush, qreal alpha)
static QBrush qMapBrushToRect (const QBrush &brush, const QRectF &rect)
static QLinearGradient qMapGradientToRect (const QLinearGradient &gradient, const QRectF &rect)
static void qt_plastique_draw_frame (QPainter *painter, const QRect &rect, const QStyleOption *option, QFrame::Shadow shadow=QFrame::Plain)
static void qt_plastique_draw_gradient (QPainter *painter, const QRect &rect, const QColor &gradientStart, const QColor &gradientStop)
static void qt_plastique_draw_handle (QPainter *painter, const QStyleOption *option, const QRect &rect, Qt::Orientation orientation, const QWidget *widget)
static void qt_plastique_draw_mdibutton (QPainter *painter, const QStyleOptionTitleBar *option, const QRect &tmp, bool hover, bool sunken)
static void qt_plastique_drawFrame (QPainter *painter, const QStyleOption *option, const QWidget *widget)
static void qt_plastique_drawShadedPanel (QPainter *painter, const QStyleOption *option, bool base, const QWidget *widget)
Variables
static const bool AnimateBusyProgressBar = true
static const bool AnimateProgressBar = false
static const int blueFrameWidth = 2
static const int ProgressBarFps = 25
static const char *const qt_plastique_slider_horizontalhandle []
static const char *const qt_plastique_slider_horizontalhandle_up []
static const char *const qt_plastique_slider_verticalhandle []
static const char *const qt_plastique_slider_verticalhandle_left []
static const char *const qt_scrollbar_button_arrow_down []
static const char *const qt_scrollbar_button_arrow_left []
static const char *const qt_scrollbar_button_arrow_right []
static const char *const qt_scrollbar_button_arrow_up []
static const char *const qt_scrollbar_button_down []
static const char *const qt_scrollbar_button_left []
static const char *const qt_scrollbar_button_right []
static const char *const qt_scrollbar_button_up []
static const char *const qt_scrollbar_slider_pattern_horizontal []
static const char *const qt_scrollbar_slider_pattern_vertical []
static const char *const qt_simple_toolbarhandle []
static const char *const qt_titlebar_context_help []
static const char *const qt_toolbarhandle []
static const int windowsArrowHMargin = 6
static const int windowsCheckMarkWidth = 12
static const int windowsItemFrame = 2
static const int windowsItemHMargin = 3
static const int windowsItemVMargin = 2
static const int windowsRightBorder = 15
static const int windowsSepHeight = 2
static const int windowsTabSpacing = 12
Macro Definition Documentation
CT1
#define CT1 (c) CT2(c, c)
Definition at line 5867 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::layoutSpacingImplementation().
CT2
#define CT2 (c1, c2) (((uint)c1 << 16) | (uint)c2)
Definition at line 5868 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::layoutSpacingImplementation().
Function Documentation
elliditide()
static QString elliditide (const QString & text, const QFontMetrics & fontMetrics, const QRect & rect, int * textWidth = 0) static
Definition at line 918 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl().
 {
     // Chop and insert ellide into title if text is too wide
     QString title = text;
     int width = textWidth ? *textWidth : fontMetrics.width(text);
     QString ellipsis = QLatin1String("...");
     if (width > rect.width()) {
         QString leftHalf = title.left(title.size() / 2);
         QString rightHalf = title.mid(leftHalf.size() + 1);
         while (!leftHalf.isEmpty() && !rightHalf.isEmpty()) {
             leftHalf.chop(1);
             int width = fontMetrics.width(leftHalf + ellipsis + rightHalf);
             if (width < rect.width()) {
                 title = leftHalf + ellipsis + rightHalf;
                 width = width;
                 break;
             }
             rightHalf.remove(0, 1);
             width = fontMetrics.width(leftHalf + ellipsis + rightHalf);
             if (width < rect.width()) {
                 title = leftHalf + ellipsis + rightHalf;
                 width = width;
                 break;
             }
         }
     }
     if (textWidth)
         *textWidth = width;
     return title;
 }
mergedColors()
static QColor mergedColors (const QColor & colorA, const QColor & colorB, int factor = 50) static
Definition at line 730 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QPlastiqueStyle::drawPrimitive(), qt_plastique_draw_handle(), and qt_plastique_drawFrame().
 {
     const int maxFactor = 100;
     QColor tmp = colorA;
     tmp.setRed((tmp.red() * factor) / maxFactor + (colorB.red() * (maxFactor - factor)) / maxFactor);
     tmp.setGreen((tmp.green() * factor) / maxFactor + (colorB.green() * (maxFactor - factor)) / maxFactor);
     tmp.setBlue((tmp.blue() * factor) / maxFactor + (colorB.blue() * (maxFactor - factor)) / maxFactor);
     return tmp;
 }
qBrushDark()
static QBrush qBrushDark (QBrush brush, int dark) static
Definition at line 578 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QPlastiqueStyle::drawPrimitive(), and qt_plastique_draw_frame().
 {
     if (const QGradient *gradient = brush.gradient()) {
         // Use the gradient. Call QColor::darker() on all color stops.
         QGradientStops stops = gradient->stops();
         QMutableVectorIterator<QGradientStop> it(stops);
         while (it.hasNext()) {
             it.next();
             it.setValue(QPair<qreal, QColor>(it.value().first, it.value().second.darker(dark)));
         }
         switch (gradient->type()) {
         case QGradient::RadialGradient: {
             QRadialGradient grad = *static_cast<const QRadialGradient *>(gradient);
             grad.setStops(stops);
             brush = QBrush(grad);
             break;
         }
         case QGradient::ConicalGradient: {
             QConicalGradient grad = *static_cast<const QConicalGradient *>(gradient);
             grad.setStops(stops);
             brush = QBrush(grad);
             break;
         }
         default:
             qWarning("QPlastiqueStyle::qBrushDark() - unknown gradient type"
                      " - falling back to QLinearGradient");
         case QGradient::LinearGradient: {
             QLinearGradient grad = *static_cast<const QLinearGradient *>(gradient);
             grad.setStops(stops);
             brush = QBrush(grad);
             break;
         }
         }
     } else if (!brush.texture().isNull()) {
         // Modify the texture - ridiculously expensive.
         QPixmap texture = brush.texture();
         QPixmap pixmap;
         QString name = QLatin1Literal("qbrushtexture-dark")
                        % HexString<int>(dark)
                        % HexString<qint64>(texture.cacheKey());
         if (!QPixmapCache::find(name, pixmap)) {
             QImage image = texture.toImage();
             QRgb *rgb = reinterpret_cast<QRgb *>(image.bits());
             int pixels = image.width() * image.height();
             QColor tmpColor;
             while (pixels--) {
                 tmpColor.setRgb(*rgb);
                 *rgb++ = tmpColor.darker(dark).rgba();
             }
             pixmap = QPixmap::fromImage(image);
             QPixmapCache::insert(name, pixmap);
         }
         brush.setTexture(pixmap);
     } else {
         // Use the color
         brush.setColor(brush.color().darker(dark));
     }
     return brush;
 }
qBrushLight()
static QBrush qBrushLight (QBrush brush, int light) static
Definition at line 516 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), and QPlastiqueStyle::drawPrimitive().
 {
     if (const QGradient *gradient = brush.gradient()) {
         // Use the gradient. Call QColor::lighter() on all color stops.
         QGradientStops stops = gradient->stops();
         QMutableVectorIterator<QGradientStop> it(stops);
         while (it.hasNext()) {
             it.next();
             it.setValue(QPair<qreal, QColor>(it.value().first, it.value().second.lighter(light)));
         }
         switch (gradient->type()) {
         case QGradient::RadialGradient: {
             QRadialGradient grad = *static_cast<const QRadialGradient *>(gradient);
             grad.setStops(stops);
             brush = QBrush(grad);
             break;
         }
         case QGradient::ConicalGradient: {
             QConicalGradient grad = *static_cast<const QConicalGradient *>(gradient);
             grad.setStops(stops);
             brush = QBrush(grad);
             break;
         }
         default:
             qWarning("QPlastiqueStyle::qBrushLight() - unknown gradient type"
                      " - falling back to QLinearGradient");
         case QGradient::LinearGradient: {
             QLinearGradient grad = *static_cast<const QLinearGradient *>(gradient);
             grad.setStops(stops);
             brush = QBrush(grad);
             break;
         }
         }
     } else if (!brush.texture().isNull()) {
         // Modify the texture - ridiculously expensive.
         QPixmap texture = brush.texture();
         QPixmap pixmap;
         QString name = QLatin1Literal("qbrushtexture-light")
                        % HexString<int>(light)
                        % HexString<qint64>(texture.cacheKey());
         if (!QPixmapCache::find(name, pixmap)) {
             QImage image = texture.toImage();
             QRgb *rgb = reinterpret_cast<QRgb *>(image.bits());
             int pixels = image.width() * image.height();
             QColor tmpColor;
             while (pixels--) {
                 tmpColor.setRgb(*rgb);
                 *rgb++ = tmpColor.lighter(light).rgba();
             }
             pixmap = QPixmap::fromImage(image);
             QPixmapCache::insert(name, pixmap);
         }
         brush.setTexture(pixmap);
     } else {
         // Use the color
         brush.setColor(brush.color().lighter(light));
     }
     return brush;
 }
qBrushSetAlphaF()
static void qBrushSetAlphaF (QBrush * brush, qreal alpha) static
Definition at line 450 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QPlastiqueStylePrivate::drawPartialFrame(), QPlastiqueStyle::drawPrimitive(), and qt_plastique_draw_frame().
 {
     if (const QGradient *gradient = brush->gradient()) {
         // Use the gradient. Call QColor::setAlphaF() on all color stops.
         QGradientStops stops = gradient->stops();
         QMutableVectorIterator<QGradientStop> it(stops);
         QColor tmpColor;
         while (it.hasNext()) {
             it.next();
             tmpColor = it.value().second;
             tmpColor.setAlphaF(alpha * tmpColor.alphaF());
             it.setValue(QPair<qreal, QColor>(it.value().first, tmpColor));
         }
         switch (gradient->type()) {
         case QGradient::RadialGradient: {
             QRadialGradient grad = *static_cast<const QRadialGradient *>(gradient);
             grad.setStops(stops);
             *brush = QBrush(grad);
             break;
         }
         case QGradient::ConicalGradient: {
             QConicalGradient grad = *static_cast<const QConicalGradient *>(gradient);
             grad.setStops(stops);
             *brush = QBrush(grad);
             break;
         }
         default:
             qWarning("QPlastiqueStyle::qBrushLight() - unknown gradient type"
                      " - falling back to QLinearGradient");
         case QGradient::LinearGradient: {
             QLinearGradient grad = *static_cast<const QLinearGradient *>(gradient);
             grad.setStops(stops);
             *brush = QBrush(grad);
             break;
         }
         }
     } else if (!brush->texture().isNull()) {
         // Modify the texture - ridiculously expensive.
         QPixmap texture = brush->texture();
         QPixmap pixmap;
         QString name = QLatin1Literal("qbrushtexture-alpha")
                        % HexString<qreal>(alpha)
                        % HexString<qint64>(texture.cacheKey());
         if (!QPixmapCache::find(name, pixmap)) {
             QImage image = texture.toImage();
             QRgb *rgb = reinterpret_cast<QRgb *>(image.bits());
             int pixels = image.width() * image.height();
             QColor tmpColor;
             while (pixels--) {
                 tmpColor.setRgb(*rgb);
                 tmpColor.setAlphaF(alpha * tmpColor.alphaF());
                 *rgb++ = tmpColor.rgba();
             }
             pixmap = QPixmap::fromImage(image);
             QPixmapCache::insert(name, pixmap);
         }
         brush->setTexture(pixmap);
     } else {
         // Use the color
         QColor tmpColor = brush->color();
         tmpColor.setAlphaF(alpha * tmpColor.alphaF());
         brush->setColor(tmpColor);
     }
 }
qMapBrushToRect()
static QBrush qMapBrushToRect (const QBrush & brush, const QRectF & rect) static
Definition at line 440 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), and QPlastiqueStyle::drawPrimitive().
 {
     if (!brush.gradient())
         return brush;
     // ### Ugly assumption that it's a linear gradient
     QBrush tmp(qMapGradientToRect(*static_cast<const QLinearGradient *>(brush.gradient()), rect));
     return tmp;
 }
qMapGradientToRect()
static QLinearGradient qMapGradientToRect (const QLinearGradient & gradient, const QRectF & rect) static
Definition at line 432 of file qplastiquestyle.cpp.
Referenced by qMapBrushToRect().
 {
     QLinearGradient tmpGrad(rect.center().x(), rect.top(),
                             rect.center().x(), rect.bottom());
     tmpGrad.setStops(gradient.stops());
     return tmpGrad;
 }
qt_plastique_draw_frame()
static void qt_plastique_draw_frame (QPainter * painter, const QRect & rect, const QStyleOption * option, QFrame::Shadow shadow = QFrame::Plain) static
Definition at line 652 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawComplexControl(), and QPlastiqueStyle::drawPrimitive().
 {
     QPen oldPen = painter->pen();
     QBrush border;
     QBrush corner;
     QBrush innerTopLeft;
     QBrush innerBottomRight;
     if (shadow != QFrame::Plain && (option->state & QStyle::State_HasFocus)) {
         border = option->palette.highlight();
         qBrushSetAlphaF(&border, qreal(0.8));
         corner = option->palette.highlight();
         qBrushSetAlphaF(&corner, 0.5);
         innerTopLeft = qBrushDark(option->palette.highlight(), 125);
         innerBottomRight = option->palette.highlight();
         qBrushSetAlphaF(&innerBottomRight, qreal(0.65));
     } else {
         border = option->palette.shadow();
         qBrushSetAlphaF(&border, qreal(0.4));
         corner = option->palette.shadow();
         qBrushSetAlphaF(&corner, 0.25);
         innerTopLeft = option->palette.shadow();
         innerBottomRight = option->palette.shadow();
         if (shadow == QFrame::Sunken) {
             qBrushSetAlphaF(&innerTopLeft, qreal(0.23));
             qBrushSetAlphaF(&innerBottomRight, qreal(0.075));
         } else {
             qBrushSetAlphaF(&innerTopLeft, qreal(0.075));
             qBrushSetAlphaF(&innerBottomRight, qreal(0.23));
         }
     }
     QLine lines[4];
     QPoint points[8];
     // Opaque corner lines
     painter->setPen(QPen(border, 0));
     lines[0] = QLine(rect.left() + 2, rect.top(), rect.right() - 2, rect.top());
     lines[1] = QLine(rect.left() + 2, rect.bottom(), rect.right() - 2, rect.bottom());
     lines[2] = QLine(rect.left(), rect.top() + 2, rect.left(), rect.bottom() - 2);
     lines[3] = QLine(rect.right(), rect.top() + 2, rect.right(), rect.bottom() - 2);
     painter->drawLines(lines, 4);
     // Opaque corner dots
     points[0] = QPoint(rect.left() + 1, rect.top() + 1);
     points[1] = QPoint(rect.left() + 1, rect.bottom() - 1);
     points[2] = QPoint(rect.right() - 1, rect.top() + 1);
     points[3] = QPoint(rect.right() - 1, rect.bottom() - 1);
     painter->drawPoints(points, 4);
     // Shaded corner dots
     painter->setPen(QPen(corner, 0));
     points[0] = QPoint(rect.left(), rect.top() + 1);
     points[1] = QPoint(rect.left(), rect.bottom() - 1);
     points[2] = QPoint(rect.left() + 1, rect.top());
     points[3] = QPoint(rect.left() + 1, rect.bottom());
     points[4] = QPoint(rect.right(), rect.top() + 1);
     points[5] = QPoint(rect.right(), rect.bottom() - 1);
     points[6] = QPoint(rect.right() - 1, rect.top());
     points[7] = QPoint(rect.right() - 1, rect.bottom());
     painter->drawPoints(points, 8);
     // Shadows
     if (shadow != QFrame::Plain) {
         painter->setPen(QPen(innerTopLeft, 0));
         lines[0] = QLine(rect.left() + 2, rect.top() + 1, rect.right() - 2, rect.top() + 1);
         lines[1] = QLine(rect.left() + 1, rect.top() + 2, rect.left() + 1, rect.bottom() - 2);
         painter->drawLines(lines, 2);
         painter->setPen(QPen(innerBottomRight, 0));
         lines[0] = QLine(rect.left() + 2, rect.bottom() - 1, rect.right() - 2, rect.bottom() - 1);
         lines[1] = QLine(rect.right() - 1, rect.top() + 2, rect.right() - 1, rect.bottom() - 2);
         painter->drawLines(lines, 2);
     }
     painter->setPen(oldPen);
 }
qt_plastique_draw_gradient()
static void qt_plastique_draw_gradient (QPainter * painter, const QRect & rect, const QColor & gradientStart, const QColor & gradientStop) static
Definition at line 740 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QPlastiqueStyle::drawPrimitive(), qt_plastique_draw_mdibutton(), and qt_plastique_drawShadedPanel().
 {
     QString gradientName = QLatin1Literal("qplastique-g")
                    % HexString<int>(rect.width())
                    % HexString<int>(rect.height())
                    % HexString<QRgb>(gradientStart.rgba())
                    % HexString<QRgb>(gradientStop.rgba());
     QPixmap cache;
     QPainter *p = painter;
     QRect r = rect;
     bool doPixmapCache = painter->deviceTransform().isIdentity()
     && painter->worldMatrix().isIdentity();
     if (doPixmapCache && QPixmapCache::find(gradientName, cache)) {
         painter->drawPixmap(rect, cache);
     } else {
         if (doPixmapCache) {
             cache = QPixmap(rect.size());
             cache.fill(Qt::transparent);
             p = new QPainter(&cache);
         r = QRect(0, 0, rect.width(), rect.height());
         }
         int x = r.center().x();
         QLinearGradient gradient(x, r.top(), x, r.bottom());
         gradient.setColorAt(0, gradientStart);
         gradient.setColorAt(1, gradientStop);
         p->fillRect(r, gradient);
         if (doPixmapCache) {
         p->end();
         delete p;
         painter->drawPixmap(rect, cache);
             QPixmapCache::insert(gradientName, cache);
     }
     }
 }
qt_plastique_draw_handle()
static void qt_plastique_draw_handle (QPainter * painter, const QStyleOption * option, const QRect & rect, Qt::Orientation orientation, const QWidget * widget) static
Definition at line 951 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl(), and QPlastiqueStyle::drawPrimitive().
 {
     QColor borderColor = option->palette.background().color().darker(178);
     QColor alphaCornerColor;
     if (widget) {
         // ### backgroundrole/foregroundrole should be part of the style option
         alphaCornerColor = mergedColors(option->palette.color(widget->backgroundRole()), borderColor);
     } else {
         alphaCornerColor = mergedColors(option->palette.background().color(), borderColor);
     }
     QImage handle(qt_simple_toolbarhandle);
     alphaCornerColor.setAlpha(170);
     handle.setColor(1, alphaCornerColor.rgba());
     handle.setColor(2, mergedColors(alphaCornerColor, option->palette.light().color()).rgba());
     handle.setColor(3, option->palette.light().color().rgba());
     const int spacing = 2;
     if (orientation == Qt::Vertical) {
         int nchunks = rect.width() / (handle.width() + spacing);
         for (int i = 0; i < nchunks; ++i)
             painter->drawImage(QPoint(rect.left() + i * (handle.width() + spacing), rect.top()), handle);
     } else {
         int nchunks = rect.height() / (handle.height() + spacing);
         for (int i = 0; i < nchunks; ++i)
             painter->drawImage(QPoint(rect.left(), rect.top() + i * (handle.height() + spacing)), handle);
     }
 }
qt_plastique_draw_mdibutton()
static void qt_plastique_draw_mdibutton (QPainter * painter, const QStyleOptionTitleBar * option, const QRect & tmp, bool hover, bool sunken) static
Definition at line 874 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawComplexControl().
 {
     if (tmp.isNull())
         return;
     bool active = (option->titleBarState & QStyle::State_Active);
     // ### use palette colors instead
     QColor mdiButtonGradientStartColor;
     QColor mdiButtonGradientStopColor;
     if (active) {
         mdiButtonGradientStartColor = QColor((hover || sunken) ? 0x7d8bb1 : 0x55689a);
         mdiButtonGradientStopColor = QColor((hover || sunken) ? 0x939ebe : 0x7381ab);
     } else {
         mdiButtonGradientStartColor = QColor((hover || sunken) ? 0x9e9e9e : 0x818181);
         mdiButtonGradientStopColor = QColor((hover || sunken) ? 0xababab : 0x929292);
     }
     qt_plastique_draw_gradient(painter, tmp.adjusted(1, 1, -1, -1),
                                mdiButtonGradientStartColor, mdiButtonGradientStopColor);
     QColor mdiButtonBorderColor;
     if (active) {
         mdiButtonBorderColor = (hover || sunken) ? QColor(0x627097) : QColor(0x324577);
     } else {
         mdiButtonBorderColor = (hover || sunken) ? QColor(0x838383) : QColor(0x5e5e5e);
     }
     painter->setPen(QPen(mdiButtonBorderColor, 1));
     const QLine lines[4] = {
         QLine(tmp.left() + 2, tmp.top(), tmp.right() - 2, tmp.top()),
         QLine(tmp.left() + 2, tmp.bottom(), tmp.right() - 2, tmp.bottom()),
         QLine(tmp.left(), tmp.top() + 2, tmp.left(), tmp.bottom() - 2),
         QLine(tmp.right(), tmp.top() + 2, tmp.right(), tmp.bottom() - 2) };
     painter->drawLines(lines, 4);
     const QPoint points[4] = {
         QPoint(tmp.left() + 1, tmp.top() + 1),
         QPoint(tmp.right() - 1, tmp.top() + 1),
         QPoint(tmp.left() + 1, tmp.bottom() - 1),
         QPoint(tmp.right() - 1, tmp.bottom() - 1) };
     painter->drawPoints(points, 4);
 }
qt_plastique_drawFrame()
static void qt_plastique_drawFrame (QPainter * painter, const QStyleOption * option, const QWidget * widget) static
Definition at line 780 of file qplastiquestyle.cpp.
Referenced by qt_plastique_drawShadedPanel().
 {
     QRect rect = option->rect;
     QPen oldPen = painter->pen();
     QColor borderColor = option->palette.background().color().darker(178);
     QColor gradientStartColor = option->palette.button().color().lighter(104);
     QColor gradientStopColor = option->palette.button().color().darker(105);
     QColor alphaCornerColor;
     if (widget) {
         // ### backgroundrole/foregroundrole should be part of the style option
         alphaCornerColor = mergedColors(option->palette.color(widget->backgroundRole()), borderColor);
     } else {
         alphaCornerColor = mergedColors(option->palette.background().color(), borderColor);
     }
     QLine lines[4];
     QPoint points[8];
     // outline / border
     painter->setPen(borderColor);
     lines[0] = QLine(rect.left() + 2, rect.top(), rect.right() - 2, rect.top());
     lines[1] = QLine(rect.left() + 2, rect.bottom(), rect.right() - 2, rect.bottom());
     lines[2] = QLine(rect.left(), rect.top() + 2, rect.left(), rect.bottom() - 2);
     lines[3] = QLine(rect.right(), rect.top() + 2, rect.right(), rect.bottom() - 2);
     painter->drawLines(lines, 4);
     points[0] = QPoint(rect.left() + 1, rect.top() + 1);
     points[1] = QPoint(rect.right() - 1, rect.top() + 1);
     points[2] = QPoint(rect.left() + 1, rect.bottom() - 1);
     points[3] = QPoint(rect.right() - 1, rect.bottom() - 1);
     painter->drawPoints(points, 4);
     painter->setPen(alphaCornerColor);
     points[0] = QPoint(rect.left() + 1, rect.top());
     points[1] = QPoint(rect.right() - 1, rect.top());
     points[2] = QPoint(rect.left() + 1, rect.bottom());
     points[3] = QPoint(rect.right() - 1, rect.bottom());
     points[4] = QPoint(rect.left(), rect.top() + 1);
     points[5] = QPoint(rect.right(), rect.top() + 1);
     points[6] = QPoint(rect.left(), rect.bottom() - 1);
     points[7] = QPoint(rect.right(), rect.bottom() - 1);
     painter->drawPoints(points, 8);
     // inner border
     if ((option->state & QStyle::State_Sunken) || (option->state & QStyle::State_On))
         painter->setPen(option->palette.button().color().darker(118));
     else
         painter->setPen(gradientStartColor);
     lines[0] = QLine(rect.left() + 2, rect.top() + 1, rect.right() - 2, option->rect.top() + 1);
     lines[1] = QLine(rect.left() + 1, rect.top() + 2, rect.left() + 1, option->rect.bottom() - 2);
     painter->drawLines(lines, 2);
     if ((option->state & QStyle::State_Sunken) || (option->state & QStyle::State_On))
         painter->setPen(option->palette.button().color().darker(110));
     else
         painter->setPen(gradientStopColor.darker(102));
     lines[0] = QLine(rect.left() + 2, rect.bottom() - 1, rect.right() - 2, rect.bottom() - 1);
     lines[1] = QLine(rect.right() - 1, rect.top() + 2, rect.right() - 1, rect.bottom() - 2);
     painter->drawLines(lines, 2);
     painter->setPen(oldPen);
 }
qt_plastique_drawShadedPanel()
static void qt_plastique_drawShadedPanel (QPainter * painter, const QStyleOption * option, bool base, const QWidget * widget) static
Definition at line 847 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl(), and QPlastiqueStyle::drawPrimitive().
 {
     QRect rect = option->rect;
     QPen oldPen = painter->pen();
     QColor gradientStartColor = option->palette.button().color().lighter(104);
     QColor gradientStopColor = option->palette.button().color().darker(105);
     // gradient fill
     if ((option->state & QStyle::State_Enabled) || !(option->state & QStyle::State_AutoRaise)) {
         if ((option->state & QStyle::State_Sunken) || (option->state & QStyle::State_On)) {
             qt_plastique_draw_gradient(painter, rect.adjusted(1, 1, -1, -1),
                                        option->palette.button().color().darker(114),
                                        option->palette.button().color().darker(106));
         } else {
             qt_plastique_draw_gradient(painter, rect.adjusted(1, 1, -1, -1),
                                        base ? option->palette.background().color().lighter(105) : gradientStartColor,
                                        base ? option->palette.background().color().darker(102) : gradientStopColor);
         }
     }
     qt_plastique_drawFrame(painter, option, widget);
     painter->setPen(oldPen);
 }
Variable Documentation
AnimateBusyProgressBar
const bool AnimateBusyProgressBar = true static
Definition at line 46 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl(), QPlastiqueStyle::polish(), and QPlastiqueStyle::unpolish().
AnimateProgressBar
const bool AnimateProgressBar = false static
Definition at line 47 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl(), and QPlastiqueStyle::timerEvent().
blueFrameWidth
const int blueFrameWidth = 2 static
Definition at line 50 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStylePrivate::drawPartialFrame(), and QPlastiqueStyle::subControlRect().
ProgressBarFps
const int ProgressBarFps = 25 static
Definition at line 49 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl(), QPlastiqueStyle::eventFilter(), and QPlastiqueStyle::timerEvent().
qt_plastique_slider_horizontalhandle
const char* const qt_plastique_slider_horizontalhandle[] static
Initial value:
= {
    "11 15 6 1",
    "   c None",
    "+  c #979797",
    "@  c #C9C9C9",
    "$  c #C1C1C1",
    "b  c None",
    "d  c None",
    " $+++++++$ ",
    "$+bbbbbbb+$",
    "+b       d+",
    "+b$$   $$d+",
    "+b$@   $@d+",
    "+b       d+",
    "+b       d+",
    "+b       d+",
    "+b       d+",
    "+b       d+",
    "$+      d+$",
    " $+    d+$ ",
    "  $+  d+$  ",
    "   $+d+$   ",
    "    $+$    "}
Definition at line 144 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawComplexControl().
qt_plastique_slider_horizontalhandle_up
const char* const qt_plastique_slider_horizontalhandle_up[] static
Initial value:
= {
    "11 15 6 1",
    "   c None",
    "+  c #979797",
    "@  c #C9C9C9",
    "$  c #C1C1C1",
    "b  c None",
    "d  c None",
    "    $+$    ",
    "   $+b+$   ",
    "  $+b  +$  ",
    " $+b    +$ ",
    "$+b      +$",
    "+b       d+",
    "+b       d+",
    "+b       d+",
    "+b       d+",
    "+b       d+",
    "+b$$   $$d+",
    "+b$@   $@d+",
    "+b       d+",
    "$+ddddddd+$",
    " $+++++++$ "}
Definition at line 168 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawComplexControl().
qt_plastique_slider_verticalhandle
const char* const qt_plastique_slider_verticalhandle[] static
Initial value:
= {
    "15 11 6 1",
    "   c None",
    "+  c #979797",
    "@  c #C9C9C9",
    "$  c #C1C1C1",
    "b  c None",
    "d  c None",
    " $++++++++$    ",
    "$+bbbbbbbb+$   ",
    "+b $$      +$  ",
    "+b $@       +$ ",
    "+b           +$",
    "+b           d+",
    "+b          d+$",
    "+b $$      d+$ ",
    "+b $@     d+$  ",
    "$+dddddddd+$   ",
    " $++++++++$    "}
Definition at line 104 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawComplexControl().
qt_plastique_slider_verticalhandle_left
const char* const qt_plastique_slider_verticalhandle_left[] static
Initial value:
= {
    "15 11 6 1",
    "   c None",
    "+  c #979797",
    "@  c #C9C9C9",
    "$  c #C1C1C1",
    "b  c None",
    "d  c None",
    "    $++++++++$ ",
    "   $+bbbbbbbb+$",
    "  $+b     $$ d+",
    " $+b      $@ d+",
    "$+b          d+",
    "+b           d+",
    "$+           d+",
    " $+       $$ d+",
    "  $+      $@ d+",
    "   $+dddddddd+$",
    "    $++++++++$ "}
Definition at line 124 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawComplexControl().
qt_scrollbar_button_arrow_down
const char* const qt_scrollbar_button_arrow_down[] static
Initial value:
= {
    "7 4 2 1",
    "   c None",
    "*  c #BFBFBF",
    "*******",
    " ***** ",
    "  ***  ",
    "   *   "}
Definition at line 225 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl().
qt_scrollbar_button_arrow_left
const char* const qt_scrollbar_button_arrow_left[] static
Initial value:
= {
    "4 7 2 1",
    "   c None",
    "*  c #BFBFBF",
    "   *",
    "  **",
    " ***",
    "****",
    " ***",
    "  **",
    "   *"}
Definition at line 192 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl().
qt_scrollbar_button_arrow_right
const char* const qt_scrollbar_button_arrow_right[] static
Initial value:
= {
    "4 7 2 1",
    "   c None",
    "*  c #BFBFBF",
    "*   ",
    "**  ",
    "*** ",
    "****",
    "*** ",
    "**  ",
    "*   "}
Definition at line 204 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl().
qt_scrollbar_button_arrow_up
const char* const qt_scrollbar_button_arrow_up[] static
Initial value:
= {
    "7 4 2 1",
    "   c None",
    "*  c #BFBFBF",
    "   *   ",
    "  ***  ",
    " ***** ",
    "*******"}
Definition at line 216 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl().
qt_scrollbar_button_down
const char* const qt_scrollbar_button_down[] static
Initial value:
= {
    "16 16 6 1",
    "   c None",
    ".  c #BFBFBF",
    "+  c #979797",
    "#  c #FAFAFA",
    "<  c #FAFAFA",
    "*  c #FAFAFA",
    "++++++++++++++++",
    "+##############+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    ".+<<<<<<<<<<<<+.",
    " .++++++++++++. "}
Definition at line 309 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl().
qt_scrollbar_button_left
const char* const qt_scrollbar_button_left[] static
Initial value:
= {
    "16 16 6 1",
    "   c None",
    ".  c #BFBFBF",
    "+  c #979797",
    "#  c #FAFAFA",
    "<  c #FAFAFA",
    "*  c #FAFAFA",
    " .+++++++++++++.",
    ".+#############+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    ".+<<<<<<<<<<<<<+",
    " .+++++++++++++."}
Definition at line 234 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl().
qt_scrollbar_button_right
const char* const qt_scrollbar_button_right[] static
Initial value:
= {
    "16 16 6 1",
    "   c None",
    ".  c #BFBFBF",
    "+  c #979797",
    "#  c #FAFAFA",
    "<  c #FAFAFA",
    "*  c #FAFAFA",
    ".+++++++++++++. ",
    "+#############+.",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+<<<<<<<<<<<<<+.",
    ".+++++++++++++. "}
Definition at line 259 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl().
qt_scrollbar_button_up
const char* const qt_scrollbar_button_up[] static
Initial value:
= {
    "16 16 6 1",
    "   c None",
    ".  c #BFBFBF",
    "+  c #979797",
    "#  c #FAFAFA",
    "<  c #FAFAFA",
    "*  c #FAFAFA",
    " .++++++++++++. ",
    ".+############+.",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+#            <+",
    "+<<<<<<<<<<<<<<+",
    ".++++++++++++++."}
Definition at line 284 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl().
qt_scrollbar_slider_pattern_horizontal
const char* const qt_scrollbar_slider_pattern_horizontal[] static
Initial value:
= {
    "18 10 3 1",
    "   c None",
    ".  c #BFBFBF",
    "+  c #979797",
    "..  ..  ..  ..  ..",
    ".+  .+  .+  .+  .+",
    "                  ",
    "                  ",
    "..  ..  ..  ..  ..",
    ".+  .+  .+  .+  .+",
    "                  ",
    "                  ",
    "..  ..  ..  ..  ..",
    ".+  .+  .+  .+  .+"}
Definition at line 358 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl().
qt_scrollbar_slider_pattern_vertical
const char* const qt_scrollbar_slider_pattern_vertical[] static
Initial value:
= {
    "10 18 3 1",
    "   c None",
    ".  c #BFBFBF",
    "+  c #979797",
    "..  ..  ..",
    ".+  .+  .+",
    "          ",
    "          ",
    "..  ..  ..",
    ".+  .+  .+",
    "          ",
    "          ",
    "..  ..  ..",
    ".+  .+  .+",
    "          ",
    "          ",
    "..  ..  ..",
    ".+  .+  .+",
    "          ",
    "          ",
    "..  ..  ..",
    ".+  .+  .+"}
Definition at line 334 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl().
qt_simple_toolbarhandle
const char* const qt_simple_toolbarhandle[] static
Initial value:
= {
    "3 3 4 1",
    "       c None",
    ".      c #C5C5C5",
    "+      c #EEEEEE",
    "@      c #FAFAFA",
    ".. ",
    ".+@",
    " @@"}
Definition at line 387 of file qplastiquestyle.cpp.
Referenced by qt_plastique_draw_handle().
qt_titlebar_context_help
const char* const qt_titlebar_context_help[] static
Definition at line 397 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawComplexControl().
qt_toolbarhandle
const char* const qt_toolbarhandle[] static
Initial value:
= {
    "6 6 4 1",
    "       c None",
    ".      c #C5C5C5",
    "+      c #EEEEEE",
    "@      c #FAFAFA",
    "..    ",
    ".+@   ",
    " @@   ",
    "   .. ",
    "   .+@",
    "    @@"}
Definition at line 374 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl(), and QPlastiqueStyle::drawPrimitive().
windowsArrowHMargin
const int windowsArrowHMargin = 6 static
Definition at line 99 of file qplastiquestyle.cpp.
windowsCheckMarkWidth
const int windowsCheckMarkWidth = 12 static
Definition at line 102 of file qplastiquestyle.cpp.
windowsItemFrame
const int windowsItemFrame = 2 static
Definition at line 95 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl().
windowsItemHMargin
const int windowsItemHMargin = 3 static
Definition at line 97 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl().
windowsItemVMargin
const int windowsItemVMargin = 2 static
Definition at line 98 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl().
windowsRightBorder
const int windowsRightBorder = 15 static
Definition at line 101 of file qplastiquestyle.cpp.
Referenced by QPlastiqueStyle::drawControl().
windowsSepHeight
const int windowsSepHeight = 2 static
Definition at line 96 of file qplastiquestyle.cpp.
windowsTabSpacing
const int windowsTabSpacing = 12 static
Definition at line 100 of file qplastiquestyle.cpp.