Qt 4.8: /src/gui/image/qpnghandler.cpp File Reference
qpnghandler.cpp File Reference
#include "private/qpnghandler_p.h"
#include <qcoreapplication.h>
#include <qiodevice.h>
#include <qimage.h>
#include <qlist.h>
#include <qtextcodec.h>
#include <qvariant.h>
#include <qvector.h>
#include <png.h>
#include <pngconf.h>
Classes
class QPngHandlerPrivate
class QPNGImageWriter
Macros
#define CALLBACK_CALL_TYPE __cdecl
#define FAST_SCAN_LINE(data, bpl, y) (data + (y) * bpl)
#define Q_INTERNAL_WIN_NO_THROW
Functions
static void CALLBACK_CALL_TYPE iod_read_fn (png_structp png_ptr, png_bytep data, png_size_t length)
static void CALLBACK_CALL_TYPE qpiw_flush_fn (png_structp)
static void CALLBACK_CALL_TYPE qpiw_write_fn (png_structp png_ptr, png_bytep data, png_size_t length)
static void CALLBACK_CALL_TYPE qt_png_warning (png_structp, png_const_charp message)
static void set_text (const QImage &image, png_structp png_ptr, png_infop info_ptr, const QString &description)
static void setup_qt (QImage &image, png_structp png_ptr, png_infop info_ptr, float screen_gamma=0.0)
static bool write_png_image (const QImage &image, QIODevice *device, int quality, float gamma, const QString &description)
Macro Definition Documentation
CALLBACK_CALL_TYPE
#define CALLBACK_CALL_TYPE __cdecl
Definition at line 85 of file qpnghandler.cpp.
FAST_SCAN_LINE
#define FAST_SCAN_LINE (data, bpl, y) (data + (y) * bpl)
Definition at line 99 of file qpnghandler.cpp.
Referenced by QPngHandlerPrivate::readPngImage().
Q_INTERNAL_WIN_NO_THROW
#define Q_INTERNAL_WIN_NO_THROW
Definition at line 95 of file qpnghandler.cpp.
Function Documentation
iod_read_fn()
static void CALLBACK_CALL_TYPE iod_read_fn (png_structp png_ptr, png_bytep data, png_size_t length) static
Definition at line 179 of file qpnghandler.cpp.
Referenced by QPngHandlerPrivate::readPngHeader().
 {
     QPngHandlerPrivate *d = (QPngHandlerPrivate *)png_get_io_ptr(png_ptr);
     QIODevice *in = d->q->device();
     if (d->state == QPngHandlerPrivate::ReadingEnd && !in->isSequential() && (in->size() - in->pos()) < 4 && length == 4) {
         // Workaround for certain malformed PNGs that lack the final crc bytes
         uchar endcrc[4] = { 0xae, 0x42, 0x60, 0x82 };
         qMemCopy(data, endcrc, 4);
         in->seek(in->size());
         return;
     }
     while (length) {
         int nr = in->read((char*)data, length);
         if (nr <= 0) {
             png_error(png_ptr, "Read Error");
             return;
         }
         length -= nr;
     }
 }
qpiw_flush_fn()
static void CALLBACK_CALL_TYPE qpiw_flush_fn (png_structp) static
Definition at line 218 of file qpnghandler.cpp.
Referenced by QPNGImageWriter::writeImage().
 {
 }
qpiw_write_fn()
static void CALLBACK_CALL_TYPE qpiw_write_fn (png_structp png_ptr, png_bytep data, png_size_t length) static
Definition at line 204 of file qpnghandler.cpp.
Referenced by QPNGImageWriter::writeImage().
 {
     QPNGImageWriter* qpiw = (QPNGImageWriter*)png_get_io_ptr(png_ptr);
     QIODevice* out = qpiw->device();
     uint nr = out->write((char*)data, length);
     if (nr != length) {
         png_error(png_ptr, "Write Error");
         return;
     }
 }
qt_png_warning()
static void CALLBACK_CALL_TYPE qt_png_warning (png_structp , png_const_charp message) static
Definition at line 378 of file qpnghandler.cpp.
Referenced by QPngHandlerPrivate::readPngHeader(), and QPNGImageWriter::writeImage().
 {
     qWarning("libpng warning: %s", message);
 }
set_text()
static void set_text (const QImage & image, png_structp png_ptr, png_infop info_ptr, const QString & description) static
Definition at line 649 of file qpnghandler.cpp.
Referenced by QPNGImageWriter::writeImage().
 {
     QMap<QString, QString> text;
     foreach (const QString &key, image.textKeys()) {
         if (!key.isEmpty())
             text.insert(key, image.text(key));
     }
     foreach (const QString &pair, description.split(QLatin1String("\n\n"))) {
         int index = pair.indexOf(QLatin1Char(':'));
         if (index >= 0 && pair.indexOf(QLatin1Char(' ')) < index) {
             QString s = pair.simplified();
             if (!s.isEmpty())
                 text.insert(QLatin1String("Description"), s);
         } else {
             QString key = pair.left(index);
             if (!key.simplified().isEmpty())
                 text.insert(key, pair.mid(index + 2).simplified());
         }
     }
     if (text.isEmpty())
         return;
     png_textp text_ptr = new png_text[text.size()];
     qMemSet(text_ptr, 0, text.size() * sizeof(png_text));
     QMap<QString, QString>::ConstIterator it = text.constBegin();
     int i = 0;
     while (it != text.constEnd()) {
         text_ptr[i].key = qstrdup(it.key().left(79).toLatin1().constData());
         bool noCompress = (it.value().length() < 40);
 #ifdef PNG_iTXt_SUPPORTED
         bool needsItxt = false;
         foreach(const QChar c, it.value()) {
             uchar ch = c.cell();
             if (c.row() || (ch < 0x20 && ch != '\n') || (ch > 0x7e && ch < 0xa0)) {
                 needsItxt = true;
                 break;
             }
         }
         if (needsItxt) {
             text_ptr[i].compression = noCompress ? PNG_ITXT_COMPRESSION_NONE : PNG_ITXT_COMPRESSION_zTXt;
             QByteArray value = it.value().toUtf8();
             text_ptr[i].text = qstrdup(value.constData());
             text_ptr[i].itxt_length = value.size();
             text_ptr[i].lang = const_cast<char*>("UTF-8");
             text_ptr[i].lang_key = qstrdup(it.key().toUtf8().constData());
         }
         else
 #endif
         {
             text_ptr[i].compression = noCompress ? PNG_TEXT_COMPRESSION_NONE : PNG_TEXT_COMPRESSION_zTXt;
             QByteArray value = it.value().toLatin1();
             text_ptr[i].text = qstrdup(value.constData());
             text_ptr[i].text_length = value.size();
         }
         ++i;
         ++it;
     }
     png_set_text(png_ptr, info_ptr, text_ptr, i);
     for (i = 0; i < text.size(); ++i) {
         delete [] text_ptr[i].key;
         delete [] text_ptr[i].text;
 #ifdef PNG_iTXt_SUPPORTED
         delete [] text_ptr[i].lang_key;
 #endif
     }
     delete [] text_ptr;
 }
setup_qt()
static void setup_qt (QImage & image, png_structp png_ptr, png_infop info_ptr, float screen_gamma = 0.0) static
Definition at line 227 of file qpnghandler.cpp.
Referenced by QPngHandlerPrivate::readPngImage().
 {
     if (screen_gamma != 0.0 && png_get_valid(png_ptr, info_ptr, PNG_INFO_gAMA)) {
         double file_gamma;
         png_get_gAMA(png_ptr, info_ptr, &file_gamma);
         png_set_gamma(png_ptr, screen_gamma, file_gamma);
     }
     png_uint_32 width;
     png_uint_32 height;
     int bit_depth;
     int color_type;
     png_bytep trans_alpha = 0;
     png_color_16p trans_color_p = 0;
     int num_trans;
     png_colorp palette = 0;
     int num_palette;
     png_get_IHDR(png_ptr, info_ptr, &width, &height, &bit_depth, &color_type, 0, 0, 0);
     png_set_interlace_handling(png_ptr);
     if (color_type == PNG_COLOR_TYPE_GRAY) {
         // Black & White or 8-bit grayscale
         if (bit_depth == 1 && png_get_channels(png_ptr, info_ptr) == 1) {
             png_set_invert_mono(png_ptr);
             png_read_update_info(png_ptr, info_ptr);
             if (image.size() != QSize(width, height) || image.format() != QImage::Format_Mono) {
                 image = QImage(width, height, QImage::Format_Mono);
                 if (image.isNull())
                     return;
             }
             image.setColorCount(2);
             image.setColor(1, qRgb(0,0,0));
             image.setColor(0, qRgb(255,255,255));
         } else if (bit_depth == 16 && png_get_valid(png_ptr, info_ptr, PNG_INFO_tRNS)) {
             png_set_expand(png_ptr);
             png_set_strip_16(png_ptr);
             png_set_gray_to_rgb(png_ptr);
             if (image.size() != QSize(width, height) || image.format() != QImage::Format_ARGB32) {
                 image = QImage(width, height, QImage::Format_ARGB32);
                 if (image.isNull())
                     return;
             }
             if (QSysInfo::ByteOrder == QSysInfo::BigEndian)
                 png_set_swap_alpha(png_ptr);
             png_read_update_info(png_ptr, info_ptr);
         } else {
             if (bit_depth == 16)
                 png_set_strip_16(png_ptr);
             else if (bit_depth < 8)
                 png_set_packing(png_ptr);
             int ncols = bit_depth < 8 ? 1 << bit_depth : 256;
             png_read_update_info(png_ptr, info_ptr);
             if (image.size() != QSize(width, height) || image.format() != QImage::Format_Indexed8) {
                 image = QImage(width, height, QImage::Format_Indexed8);
                 if (image.isNull())
                     return;
             }
             image.setColorCount(ncols);
             for (int i=0; i<ncols; i++) {
                 int c = i*255/(ncols-1);
                 image.setColor(i, qRgba(c,c,c,0xff));
             }
             if (png_get_tRNS(png_ptr, info_ptr, &trans_alpha, &num_trans, &trans_color_p) && trans_color_p) {
                 const int g = trans_color_p->gray;
                 if (g < ncols) {
                     image.setColor(g, 0);
                 }
             }
         }
     } else if (color_type == PNG_COLOR_TYPE_PALETTE
                && png_get_PLTE(png_ptr, info_ptr, &palette, &num_palette)
                && num_palette <= 256)
     {
         // 1-bit and 8-bit color
         if (bit_depth != 1)
             png_set_packing(png_ptr);
         png_read_update_info(png_ptr, info_ptr);
         png_get_IHDR(png_ptr, info_ptr, &width, &height, &bit_depth, &color_type, 0, 0, 0);
         QImage::Format format = bit_depth == 1 ? QImage::Format_Mono : QImage::Format_Indexed8;
         if (image.size() != QSize(width, height) || image.format() != format) {
             image = QImage(width, height, format);
             if (image.isNull())
                 return;
         }
         png_get_PLTE(png_ptr, info_ptr, &palette, &num_palette);
         image.setColorCount(num_palette);
         int i = 0;
         if (png_get_tRNS(png_ptr, info_ptr, &trans_alpha, &num_trans, &trans_color_p) && trans_alpha) {
             while (i < num_trans) {
                 image.setColor(i, qRgba(
                     palette[i].red,
                     palette[i].green,
                     palette[i].blue,
                     trans_alpha[i]
                    )
                );
                 i++;
             }
         }
         while (i < num_palette) {
             image.setColor(i, qRgba(
                 palette[i].red,
                 palette[i].green,
                 palette[i].blue,
                 0xff
                )
            );
             i++;
         }
     } else {
         // 32-bit
         if (bit_depth == 16)
             png_set_strip_16(png_ptr);
         png_set_expand(png_ptr);
         if (color_type == PNG_COLOR_TYPE_GRAY_ALPHA)
             png_set_gray_to_rgb(png_ptr);
         QImage::Format format = QImage::Format_ARGB32;
         // Only add filler if no alpha, or we can get 5 channel data.
         if (!(color_type & PNG_COLOR_MASK_ALPHA)
             && !png_get_valid(png_ptr, info_ptr, PNG_INFO_tRNS)) {
             png_set_filler(png_ptr, 0xff, QSysInfo::ByteOrder == QSysInfo::BigEndian ?
                            PNG_FILLER_BEFORE : PNG_FILLER_AFTER);
             // We want 4 bytes, but it isn't an alpha channel
             format = QImage::Format_RGB32;
         }
         if (image.size() != QSize(width, height) || image.format() != format) {
             image = QImage(width, height, format);
             if (image.isNull())
                 return;
         }
         if (QSysInfo::ByteOrder == QSysInfo::BigEndian)
             png_set_swap_alpha(png_ptr);
         png_read_update_info(png_ptr, info_ptr);
     }
     // Qt==ARGB==Big(ARGB)==Little(BGRA)
     if (QSysInfo::ByteOrder == QSysInfo::LittleEndian) {
         png_set_bgr(png_ptr);
     }
 }
write_png_image()
static bool write_png_image (const QImage & image, QIODevice * device, int quality, float gamma, const QString & description) static
Definition at line 915 of file qpnghandler.cpp.
Referenced by QPngHandler::write().
 {
     QPNGImageWriter writer(device);
     if (quality >= 0) {
         quality = qMin(quality, 100);
         quality = (100-quality) * 9 / 91; // map [0,100] -> [9,0]
     }
     writer.setGamma(gamma);
     return writer.writeImage(image, quality, description);
 }