Qt 4.8: /src/gui/painting/qprinter.cpp File Reference
qprinter.cpp File Reference
#include "qprinter_p.h"
#include "qprinter.h"
#include "qprintengine.h"
#include "qprinterinfo.h"
#include "qlist.h"
#include <qpagesetupdialog.h>
#include <qapplication.h>
#include <qfileinfo.h>
#include "private/qcups_p.h"
#include <private/qprintengine_win_p.h>
#include <private/qprintengine_ps_p.h>
#include <private/qt_x11_p.h>
#include "qprintengine_pdf_p.h"
#include <qpicture.h>
#include <private/qpaintengine_preview_p.h>
Macros
#define ABORT_IF_ACTIVE(location)
Functions
QPrinter::PaperSize qSizeFTopaperSize (const QSizeF &size)
double qt_multiplierForUnit (QPrinter::Unit unit, int resolution)
return the multiplier of converting from the unit value to postscript-points.
QSizeF qt_paperSizeToQSizeF (QPrinter::PaperSize size)
QSizeF qt_printerPaperSize (QPrinter::Orientation orientation, QPrinter::PaperSize paperSize, QPrinter::Unit unit, int resolution)
Variables
static const float qt_paperSizes [][2]
Macro Definition Documentation
ABORT_IF_ACTIVE
#define ABORT_IF_ACTIVE (location)
Value:
if (d->printEngine->printerState() == QPrinter::Active) { \
        qWarning("%s: Cannot be changed while printer is active", location); \
        return; \
    }
Definition at line 82 of file qprinter.cpp.
Referenced by QPrinter::setCollateCopies(), QPrinter::setColorMode(), QPrinter::setCopyCount(), QPrinter::setCreator(), QPrinter::setDocName(), QPrinter::setNumCopies(), QPrinter::setOutputFileName(), QPrinter::setPageOrder(), QPrinter::setPaperSize(), QPrinter::setPrinterName(), QPrinter::setPrintProgram(), QPrinter::setResolution(), and QPrinter::setWinPageSize().
Function Documentation
qSizeFTopaperSize()
QPrinter::PaperSize qSizeFTopaperSize (const QSizeF & size)
Definition at line 2629 of file qprinter.cpp.
Referenced by QPrinterInfo::supportedPaperSizes().
 {
     for (int i = 0; i < static_cast<int>(QPrinter::NPaperSize); ++i) {
         if (qt_paperSizes[i][0] >= size.width() - 1 &&
                 qt_paperSizes[i][0] <= size.width() + 1 &&
                 qt_paperSizes[i][1] >= size.height() - 1 &&
                 qt_paperSizes[i][1] <= size.height() + 1) {
             return QPrinter::PaperSize(i);
         }
     }
     return QPrinter::Custom;
 }
qt_multiplierForUnit()
double qt_multiplierForUnit (QPrinter::Unit unit, int resolution)
return the multiplier of converting from the unit value to postscript-points.
Definition at line 123 of file qprinter.cpp.
Referenced by QPageSetupWidget::_q_pageOrientationChanged(), QPrinter::getPageMargins(), QPrinter::pageRect(), QPrinter::paperRect(), QPrinter::paperSize(), qt_printerPaperSize(), QPrinter::setPageMargins(), QPrinter::setPaperSize(), and QPageSetupWidget::unitChanged().
 {
     switch(unit) {
     case QPrinter::Millimeter:
         return 2.83464566929;
     case QPrinter::Point:
         return 1.0;
     case QPrinter::Inch:
         return 72.0;
     case QPrinter::Pica:
         return 12;
     case QPrinter::Didot:
         return 1.065826771;
     case QPrinter::Cicero:
         return 12.789921252;
     case QPrinter::DevicePixel:
         return 72.0/resolution;
     }
     return 1.0;
 }
qt_paperSizeToQSizeF()
QSizeF qt_paperSizeToQSizeF (QPrinter::PaperSize size)
Definition at line 2615 of file qprinter.cpp.
Referenced by QtopiaPrintEngine::paperRect(), QMacPrintEnginePrivate::paperSize(), QPdf::paperSize(), and QMacPrintEnginePrivate::setPaperSize().
 {
     if (size == QPrinter::Custom) return QSizeF(0, 0);
     return QSizeF(qt_paperSizes[size][0], qt_paperSizes[size][1]);
 }
qt_printerPaperSize()
QSizeF qt_printerPaperSize (QPrinter::Orientation orientation, QPrinter::PaperSize paperSize, QPrinter::Unit unit, int resolution)
Definition at line 145 of file qprinter.cpp.
Referenced by QPageSetupWidget::_q_paperSizeChanged(), and QPrinter::paperSize().
 {
     int width_index = 0;
     int height_index = 1;
     if (orientation == QPrinter::Landscape) {
         width_index = 1;
         height_index = 0;
     }
     const qreal multiplier = qt_multiplierForUnit(unit, resolution);
     return QSizeF((qt_paperSizes[paperSize][width_index] * 72 / 25.4) / multiplier,
                   (qt_paperSizes[paperSize][height_index] * 72 / 25.4) / multiplier);
 }
Variable Documentation
qt_paperSizes
const float qt_paperSizes[][2] static
Definition at line 89 of file qprinter.cpp.
Referenced by qSizeFTopaperSize(), qt_paperSizeToQSizeF(), and qt_printerPaperSize().