Qt 4.8: /src/gui/dialogs/qprintdialog_win.cpp File Reference
qprintdialog_win.cpp File Reference
#include "qprintdialog.h"
#include <qwidget.h>
#include <qapplication.h>
#include <qmessagebox.h>
#include <private/qapplication_p.h>
#include <private/qabstractprintdialog_p.h>
#include <private/qprintengine_win_p.h>
#include <private/qprinter_p.h>
#include "moc_qprintdialog.cpp"
Classes
class QPrintDialogPrivate
Macros
#define PD_NOCURRENTPAGE 0x00800000
#define PD_RESULT_APPLY 2
#define PD_RESULT_PRINT 1
#define START_PAGE_GENERAL 0XFFFFFFFF
Functions
void qt_win_eatMouseMove ()
static void qt_win_read_back_PRINTDLGEX (PRINTDLGEX *pd, QPrintDialog *pdlg, QPrintDialogPrivate *d)
static void qt_win_setup_PRINTDLGEX (PRINTDLGEX *pd, QWidget *parent, QPrintDialog *pdlg, QPrintDialogPrivate *d, HGLOBAL *tempDevNames)
static bool warnIfNotNative (QPrinter *printer)
Macro Definition Documentation
PD_NOCURRENTPAGE
#define PD_NOCURRENTPAGE 0x00800000
Definition at line 56 of file qprintdialog_win.cpp.
Referenced by qt_win_setup_PRINTDLGEX().
PD_RESULT_APPLY
#define PD_RESULT_APPLY 2
Definition at line 58 of file qprintdialog_win.cpp.
Referenced by QPrintDialogPrivate::openWindowsPrintDialogModally().
PD_RESULT_PRINT
#define PD_RESULT_PRINT 1
Definition at line 57 of file qprintdialog_win.cpp.
Referenced by QPrintDialogPrivate::openWindowsPrintDialogModally().
START_PAGE_GENERAL
#define START_PAGE_GENERAL 0XFFFFFFFF
Definition at line 59 of file qprintdialog_win.cpp.
Referenced by qt_win_setup_PRINTDLGEX().
Function Documentation
qt_win_eatMouseMove()
void qt_win_eatMouseMove ()
Definition at line 3016 of file qapplication_win.cpp.
Referenced by QPrintDialogPrivate::openWindowsPrintDialogModally().
 {
     // after closing a windows dialog with a double click (i.e. open a file)
     // the message queue still contains a dubious WM_MOUSEMOVE message where
     // the left button is reported to be down (wParam != 0).
     // remove all those messages (usually 1) and post the last one with a
     // reset button state
     MSG msg = {0, 0, 0, 0, 0, {0, 0} };
     while (PeekMessage(&msg, 0, WM_MOUSEMOVE, WM_MOUSEMOVE, PM_REMOVE))
         ;
     if (msg.message == WM_MOUSEMOVE)
         PostMessage(msg.hwnd, msg.message, 0, msg.lParam);
 }
qt_win_read_back_PRINTDLGEX()
static void qt_win_read_back_PRINTDLGEX (PRINTDLGEX * pd, QPrintDialog * pdlg, QPrintDialogPrivate * d) static
Definition at line 153 of file qprintdialog_win.cpp.
Referenced by QPrintDialogPrivate::openWindowsPrintDialogModally().
 {
     if (pd->Flags & PD_SELECTION) {
         pdlg->setPrintRange(QPrintDialog::Selection);
         pdlg->setFromTo(0, 0);
     } else if (pd->Flags & PD_PAGENUMS) {
         pdlg->setPrintRange(QPrintDialog::PageRange);
         pdlg->setFromTo(pd->lpPageRanges[0].nFromPage, pd->lpPageRanges[0].nToPage);
     } else if (pd->Flags & PD_CURRENTPAGE) {
         pdlg->setPrintRange(QPrintDialog::CurrentPage);
         pdlg->setFromTo(0, 0);
     } else { // PD_ALLPAGES
         pdlg->setPrintRange(QPrintDialog::AllPages);
         pdlg->setFromTo(0, 0);
     }
     d->ep->printToFile = (pd->Flags & PD_PRINTTOFILE) != 0;
     d->ep->readDevnames(pd->hDevNames);
     d->ep->readDevmode(pd->hDevMode);
     d->ep->updateCustomPaperSize();
     if (d->ep->printToFile && d->ep->fileName.isEmpty())
         d->ep->fileName = d->ep->port;
     else if (!d->ep->printToFile && d->ep->fileName == QLatin1String("FILE:"))
         d->ep->fileName.clear();
 }
qt_win_setup_PRINTDLGEX()
static void qt_win_setup_PRINTDLGEX (PRINTDLGEX * pd, QWidget * parent, QPrintDialog * pdlg, QPrintDialogPrivate * d, HGLOBAL * tempDevNames) static
Definition at line 87 of file qprintdialog_win.cpp.
Referenced by QPrintDialogPrivate::openWindowsPrintDialogModally().
 {
     DEVMODE *devMode = d->ep->devMode;
     if (devMode) {
         int size = sizeof(DEVMODE) + devMode->dmDriverExtra;
         pd->hDevMode = GlobalAlloc(GHND, size);
         {
             void *dest = GlobalLock(pd->hDevMode);
             memcpy(dest, devMode, size);
             GlobalUnlock(pd->hDevMode);
         }
     } else {
         pd->hDevMode = NULL;
     }
     pd->hDevNames  = tempDevNames;
     pd->Flags = PD_RETURNDC;
     pd->Flags |= PD_USEDEVMODECOPIESANDCOLLATE;
     if (!pdlg->isOptionEnabled(QPrintDialog::PrintSelection))
         pd->Flags |= PD_NOSELECTION;
     if (pdlg->isOptionEnabled(QPrintDialog::PrintPageRange)) {
         pd->nMinPage = pdlg->minPage();
         pd->nMaxPage = pdlg->maxPage();
     }
     if(!pdlg->isOptionEnabled(QPrintDialog::PrintToFile))
         pd->Flags |= PD_DISABLEPRINTTOFILE;
     if (pdlg->isOptionEnabled(QPrintDialog::PrintSelection) && pdlg->printRange() == QPrintDialog::Selection)
         pd->Flags |= PD_SELECTION;
     else if (pdlg->isOptionEnabled(QPrintDialog::PrintPageRange) && pdlg->printRange() == QPrintDialog::PageRange)
         pd->Flags |= PD_PAGENUMS;
     else if (pdlg->isOptionEnabled(QPrintDialog::PrintCurrentPage) && pdlg->printRange() == QPrintDialog::CurrentPage)
         pd->Flags |= PD_CURRENTPAGE;
     else
         pd->Flags |= PD_ALLPAGES;
     // As stated by MSDN, to enable collate option when minpage==maxpage==0
     // set the PD_NOPAGENUMS flag
     if (pd->nMinPage==0 && pd->nMaxPage==0)
         pd->Flags |= PD_NOPAGENUMS;
     // Disable Current Page option if not required as default is Enabled
     if (!pdlg->isOptionEnabled(QPrintDialog::PrintCurrentPage))
         pd->Flags |= PD_NOCURRENTPAGE;
     // Default to showing the General tab first
     pd->nStartPage = START_PAGE_GENERAL;
     // We don't support more than one page range in the QPrinter API yet.
     pd->nPageRanges = 1;
     pd->nMaxPageRanges = 1;
     if (d->ep->printToFile)
         pd->Flags |= PD_PRINTTOFILE;
     Q_ASSERT(parent);
     pd->hwndOwner = parent->window()->winId();
     pd->lpPageRanges[0].nFromPage = qMax(pdlg->fromPage(), pdlg->minPage());
     pd->lpPageRanges[0].nToPage   = (pdlg->toPage() > 0) ? qMin(pdlg->toPage(), pdlg->maxPage()) : 1;
     pd->nCopies = d->ep->num_copies;
 }
warnIfNotNative()
static bool warnIfNotNative (QPrinter * printer) static
Definition at line 181 of file qprintdialog_win.cpp.
Referenced by QPrintDialogPrivate::openWindowsPrintDialogModally().
 {
     if (printer->outputFormat() != QPrinter::NativeFormat) {
         qWarning("QPrintDialog: Cannot be used on non-native printers");
         return false;
     }
     return true;
 }