Qt 4.8: /src/gui/painting/qprintengine_win.cpp File Reference
qprintengine_win.cpp File Reference
#include "qprinter_p.h"
#include "qprintengine_win_p.h"
#include <limits.h>
#include <private/qfont_p.h>
#include <private/qfontengine_p.h>
#include <private/qpainter_p.h>
#include <qbitmap.h>
#include <qdebug.h>
#include <qvector.h>
#include <qpicture.h>
#include <private/qpicture_p.h>
Functions
static void draw_text_item_win (const QPointF &_pos, const QTextItemInt &ti, HDC hdc, bool convertToText, const QTransform &xform, const QPointF &topLeft)
static qreal inchesToMM (double in)
QPrinter::PaperSize mapDevmodePaperSize (int s)
static QPrinter::PaperSource mapDevmodePaperSource (int s)
static int mapPaperSizeDevmode (QPrinter::PaperSize s)
static int mapPaperSourceDevmode (QPrinter::PaperSource s)
static qreal mmToInches (double mm)
QPainterPath qt_regionToPath (const QRegion &region)
Variables
struct {
QPrinter::PaperSize qtSizeName
int winSizeName
} dmMapping []
struct {
QPrinter::PaperSource qtSourceName
int winSourceName
} sources []
Function Documentation
draw_text_item_win()
static void draw_text_item_win (const QPointF & _pos, const QTextItemInt & ti, HDC hdc, bool convertToText, const QTransform & xform, const QPointF & topLeft) static
Definition at line 1636 of file qprintengine_win.cpp.
Referenced by QWin32PrintEngine::drawTextItem().
 {
     QFontEngine *fe = ti.fontEngine;
     QPointF baseline_pos = xform.inverted().map(xform.map(pos) - topLeft);
     SetTextAlign(hdc, TA_BASELINE);
     SetBkMode(hdc, TRANSPARENT);
     bool has_kerning = ti.f && ti.f->kerning();
     QFontEngineWin *winfe = (fe->type() == QFontEngine::Win) ? static_cast<QFontEngineWin *>(fe) : 0;
     HFONT hfont;
     bool ttf = false;
     if (winfe) {
         hfont = winfe->hfont;
         ttf = winfe->ttf;
     } else {
         hfont = (HFONT)GetStockObject(ANSI_VAR_FONT);
     }
     HGDIOBJ old_font = SelectObject(hdc, hfont);
     unsigned int options = (ttf && !convertToText) ? ETO_GLYPH_INDEX : 0;
     wchar_t *convertedGlyphs = (wchar_t *)ti.chars;
     QGlyphLayout glyphs = ti.glyphs;
     bool fast = !has_kerning && !(ti.flags & QTextItem::RightToLeft);
     for (int i = 0; fast && i < glyphs.numGlyphs; i++) {
         if (glyphs.offsets[i].x != 0 || glyphs.offsets[i].y != 0 || glyphs.justifications[i].space_18d6 != 0
             || glyphs.attributes[i].dontPrint) {
             fast = false;
             break;
         }
     }
 #if !defined(Q_OS_WINCE)
     // Scale, rotate and translate here.
     XFORM win_xform;
     win_xform.eM11 = xform.m11();
     win_xform.eM12 = xform.m12();
     win_xform.eM21 = xform.m21();
     win_xform.eM22 = xform.m22();
     win_xform.eDx = xform.dx();
     win_xform.eDy = xform.dy();
     SetGraphicsMode(hdc, GM_ADVANCED);
     SetWorldTransform(hdc, &win_xform);
 #endif
     if (fast) {
         // fast path
         QVarLengthArray<wchar_t> g(glyphs.numGlyphs);
         for (int i = 0; i < glyphs.numGlyphs; ++i)
             g[i] = glyphs.glyphs[i];
         ExtTextOut(hdc,
                    qRound(baseline_pos.x() + glyphs.offsets[0].x.toReal()),
                    qRound(baseline_pos.y() + glyphs.offsets[0].y.toReal()),
                    options, 0, convertToText ? convertedGlyphs : g.data(), glyphs.numGlyphs, 0);
     } else {
         QVarLengthArray<QFixedPoint> positions;
         QVarLengthArray<glyph_t> _glyphs;
         QTransform matrix = QTransform::fromTranslate(baseline_pos.x(), baseline_pos.y());
         ti.fontEngine->getGlyphPositions(ti.glyphs, matrix, ti.flags,
             _glyphs, positions);
         if (_glyphs.size() == 0) {
             SelectObject(hdc, old_font);
             return;
         }
         convertToText = convertToText && glyphs.numGlyphs == _glyphs.size();
         bool outputEntireItem = _glyphs.size() > 0;
         if (outputEntireItem) {
             options |= ETO_PDY;
             QVarLengthArray<INT> glyphDistances(_glyphs.size() * 2);
             QVarLengthArray<wchar_t> g(_glyphs.size());
             for (int i=0; i<_glyphs.size() - 1; ++i) {
                 glyphDistances[i * 2] = qRound(positions[i + 1].x) - qRound(positions[i].x);
                 glyphDistances[i * 2 + 1] = qRound(positions[i + 1].y) - qRound(positions[i].y);
                 g[i] = _glyphs[i];
             }
             glyphDistances[(_glyphs.size() - 1) * 2] = 0;
             glyphDistances[(_glyphs.size() - 1) * 2 + 1] = 0;
             g[_glyphs.size() - 1] = _glyphs[_glyphs.size() - 1];
             ExtTextOut(hdc, qRound(positions[0].x), qRound(positions[0].y), options, 0,
                        convertToText ? convertedGlyphs : g.data(), _glyphs.size(),
                        glyphDistances.data());
         } else {
             int i = 0;
             while(i < _glyphs.size()) {
                 wchar_t g = _glyphs[i];
                 ExtTextOut(hdc, qRound(positions[i].x),
                            qRound(positions[i].y), options, 0,
                            convertToText ? convertedGlyphs + i : &g, 1, 0);
                 ++i;
             }
         }
     }
 #if !defined(Q_OS_WINCE)
         win_xform.eM11 = win_xform.eM22 = 1.0;
         win_xform.eM12 = win_xform.eM21 = win_xform.eDx = win_xform.eDy = 0.0;
         SetWorldTransform(hdc, &win_xform);
 #endif
     SelectObject(hdc, old_font);
 }
inchesToMM()
static qreal inchesToMM (double in) inline static
Definition at line 400 of file qprintengine_win.cpp.
Referenced by QWin32PrintEnginePrivate::getPageMargins().
 {
     return in/0.039370147;
 }
mapDevmodePaperSize()
QPrinter::PaperSize mapDevmodePaperSize (int s)
Definition at line 110 of file qprintengine_win.cpp.
Referenced by QWin32PrintEngine::property(), and QWin32PrintEnginePrivate::updateCustomPaperSize().
 {
     int i = 0;
     while ((dmMapping[i].winSizeName > 0) && (dmMapping[i].winSizeName != s))
         i++;
     return dmMapping[i].qtSizeName;
 }
mapDevmodePaperSource()
static QPrinter::PaperSource mapDevmodePaperSource (int s) static
Definition at line 146 of file qprintengine_win.cpp.
Referenced by QWin32PrintEngine::property().
 {
     int i = 0;
     while ((sources[i].winSourceName > 0) && (sources[i].winSourceName != s))
         i++;
     return sources[i].winSourceName ? sources[i].qtSourceName : (QPrinter::PaperSource) s;
 }
mapPaperSizeDevmode()
static int mapPaperSizeDevmode (QPrinter::PaperSize s) static
Definition at line 118 of file qprintengine_win.cpp.
Referenced by QWin32PrintEngine::setProperty().
 {
     int i = 0;
  while ((dmMapping[i].winSizeName > 0) && (dmMapping[i].qtSizeName != s))
         i++;
     return dmMapping[i].winSizeName;
 }
mapPaperSourceDevmode()
static int mapPaperSourceDevmode (QPrinter::PaperSource s) static
Definition at line 154 of file qprintengine_win.cpp.
Referenced by QWin32PrintEngine::setProperty().
 {
     int i = 0;
     while ((sources[i].qtSourceName >= 0) && (sources[i].qtSourceName != s))
         i++;
     return sources[i].winSourceName ? sources[i].winSourceName : s;
 }
mmToInches()
static qreal mmToInches (double mm) inline static
Definition at line 395 of file qprintengine_win.cpp.
Referenced by QWin32PrintEnginePrivate::initDevRects(), QWin32PrintEngine::metric(), QWin32PrintEngine::property(), and QWin32PrintEnginePrivate::setPageMargins().
 {
     return mm*0.039370147;
 }
qt_regionToPath()
QPainterPath qt_regionToPath (const QRegion & region)
Definition at line 1160 of file qregion.cpp.
Referenced by QWin32PrintEngine::updateClipPath(), and QWin32PrintEngine::updateState().
 {
     QPainterPath result;
     if (region.rectCount() == 1) {
         result.addRect(region.boundingRect());
         return result;
     }
     const QVector<QRect> rects = region.rects();
     QVarLengthArray<Segment> segments;
     segments.resize(4 * rects.size());
     const QRect *rect = rects.constData();
     const QRect *end = rect + rects.size();
     int lastRowSegmentCount = 0;
     Segment *lastRowSegments = 0;
     int lastSegment = 0;
     int lastY = 0;
     while (rect != end) {
         const int y = rect[0].y();
         int count = 0;
         while (&rect[count] != end && rect[count].y() == y)
             ++count;
         for (int i = 0; i < count; ++i) {
             int offset = lastSegment + i;
             segments[offset] = Segment(rect[i].topLeft());
             segments[offset += count] = Segment(rect[i].topRight() + QPoint(1, 0));
             segments[offset += count] = Segment(rect[i].bottomRight() + QPoint(1, 1));
             segments[offset += count] = Segment(rect[i].bottomLeft() + QPoint(0, 1));
             offset = lastSegment + i;
             for (int j = 0; j < 4; ++j)
                 segments[offset + j * count].connect(segments[offset + ((j + 1) % 4) * count]);
         }
         if (lastRowSegments && lastY == y)
             mergeSegments(lastRowSegments, lastRowSegmentCount, &segments[lastSegment], count);
         lastRowSegments = &segments[lastSegment + 2 * count];
         lastRowSegmentCount = count;
         lastSegment += 4 * count;
         lastY = y + rect[0].height();
         rect += count;
     }
     for (int i = 0; i < lastSegment; ++i) {
         Segment *segment = &segments[i];
         if (!segment->added)
             addSegmentsToPath(segment, result);
     }
     return result;
 }
Variable Documentation
dmMapping
const { ... } dmMapping[]
Referenced by mapDevmodePaperSize(), and mapPaperSizeDevmode().
qtSizeName
QPrinter::PaperSize qtSizeName
Definition at line 70 of file qprintengine_win.cpp.
Referenced by mapPaperSizeDevmode().
qtSourceName
QPrinter::PaperSource qtSourceName
Definition at line 128 of file qprintengine_win.cpp.
Referenced by mapPaperSourceDevmode().
sources
const { ... } sources[]
Initial value:
= {
    { DMBIN_ONLYONE,        QPrinter::OnlyOne },
    { DMBIN_LOWER,          QPrinter::Lower },
    { DMBIN_MIDDLE,         QPrinter::Middle },
    { DMBIN_MANUAL,         QPrinter::Manual },
    { DMBIN_ENVELOPE,       QPrinter::Envelope },
    { DMBIN_ENVMANUAL,      QPrinter::EnvelopeManual },
    { DMBIN_AUTO,           QPrinter::Auto },
    { DMBIN_TRACTOR,        QPrinter::Tractor },
    { DMBIN_SMALLFMT,       QPrinter::SmallFormat },
    { DMBIN_LARGEFMT,       QPrinter::LargeFormat },
    { DMBIN_LARGECAPACITY,  QPrinter::LargeCapacity },
    { DMBIN_CASSETTE,       QPrinter::Cassette },
    { DMBIN_FORMSOURCE,     QPrinter::FormSource },
    { 0, (QPrinter::PaperSource) -1 }
}
Referenced by mapDevmodePaperSource(), and mapPaperSourceDevmode().
winSizeName
int winSizeName
Definition at line 69 of file qprintengine_win.cpp.
Referenced by mapDevmodePaperSize(), and mapPaperSizeDevmode().
winSourceName
int winSourceName
Definition at line 127 of file qprintengine_win.cpp.
Referenced by mapDevmodePaperSource().