Qt 4.8: /src/gui/painting/qprintengine_mac.mm File Reference
qprintengine_mac.mm File Reference
#include <private/qprintengine_mac_p.h>
#include <qthread.h>
#include <quuid.h>
#include <QtCore/qcoreapplication.h>
Functions
static int qt_get_PDMHeight (PMPageFormat pformat, bool fullPage, const PMResolution &resolution)
static int qt_get_PDMWidth (PMPageFormat pformat, bool fullPage, const PMResolution &resolution)
QSizeF qt_paperSizeToQSizeF (QPrinter::PaperSize size)
Function Documentation
qt_get_PDMHeight()
static int qt_get_PDMHeight (PMPageFormat pformat, bool fullPage, const PMResolution & resolution) inline static
Definition at line 323 of file qprintengine_mac.mm.
Referenced by QMacPrintEngine::metric().
 {
     int val = 0;
     PMRect r;
     qreal vRatio = resolution.vRes / 72;
     if (fullPage) {
         if (PMGetAdjustedPaperRect(pformat, &r) == noErr)
             val = qRound((r.bottom - r.top) * vRatio);
     } else {
         if (PMGetAdjustedPageRect(pformat, &r) == noErr)
             val = qRound((r.bottom - r.top) * vRatio);
     }
     return val;
 }
qt_get_PDMWidth()
static int qt_get_PDMWidth (PMPageFormat pformat, bool fullPage, const PMResolution & resolution) inline static
Definition at line 307 of file qprintengine_mac.mm.
Referenced by QMacPrintEngine::metric().
 {
     int val = 0;
     PMRect r;
     qreal hRatio = resolution.hRes / 72;
     if (fullPage) {
         if (PMGetAdjustedPaperRect(pformat, &r) == noErr)
             val = qRound((r.right - r.left) * hRatio);
     } else {
         if (PMGetAdjustedPageRect(pformat, &r) == noErr)
             val = qRound((r.right - r.left) * hRatio);
     }
     return val;
 }
qt_paperSizeToQSizeF()
QSizeF qt_paperSizeToQSizeF (QPrinter::PaperSize size)
Definition at line 2615 of file qprinter.cpp.
Referenced by QMacPrintEnginePrivate::paperSize(), and QMacPrintEnginePrivate::setPaperSize().
 {
     if (size == QPrinter::Custom) return QSizeF(0, 0);
     return QSizeF(qt_paperSizes[size][0], qt_paperSizes[size][1]);
 }