Qt 4.8: /src/corelib/io/qprocess_p.h File Reference
qprocess_p.h File Reference
#include "QtCore/qprocess.h"
#include "QtCore/qstringlist.h"
#include "QtCore/qhash.h"
#include "QtCore/qshareddata.h"
#include "private/qringbuffer_p.h"
#include "private/qiodevice_p.h"
#include <QtCore/private/qorderedmutexlocker_p.h>
#include "QtCore/qt_windows.h"
Classes
class QProcEnvKey
class QProcessEnvironmentPrivate
struct QProcessEnvironmentPrivate::MutexLocker
struct QProcessEnvironmentPrivate::OrderedMutexLocker
class QProcessPrivate
struct QProcessPrivate::Channel
Macros
#define INVALID_Q_PIPE INVALID_HANDLE_VALUE
Typedefs
typedef HANDLE Q_PIPE
typedef QString QProcEnvValue
Functions
Q_DECLARE_TYPEINFO (QProcEnvKey, Q_MOVABLE_TYPE)
uint qHash (const QProcEnvKey &key)
Macro Definition Documentation
INVALID_Q_PIPE
#define INVALID_Q_PIPE INVALID_HANDLE_VALUE
Definition at line 69 of file qprocess_p.h.
Referenced by QProcessPrivate::Channel::Channel(), QProcessPrivate::createChannel(), QProcessPrivate::QProcessPrivate(), qt_create_commandline(), and qt_create_pipe().
Typedef Documentation
Q_PIPE
typedef HANDLE Q_PIPE
Definition at line 68 of file qprocess_p.h.
QProcEnvValue
typedef QString QProcEnvValue
Definition at line 98 of file qprocess_p.h.
Function Documentation
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QProcEnvKey , Q_MOVABLE_TYPE)
qHash()
uint qHash (const QProcEnvKey & key) inline
Definition at line 96 of file qprocess_p.h.
Referenced by QNetworkManagerEngine::activationFinished(), QNetworkManagerEngine::activeConnectionPropertiesChanged(), QConnmanEngine::addServiceConfiguration(), QNetworkManagerEngine::connectionFromId(), QCoreWlanEngine::connectToId(), QNativeWifiEngine::connectToId(), QNetworkManagerEngine::disconnectFromId(), QGenericEngine::doRequestUpdate(), QResourceRoot::findNode(), QNativeWifiEngine::getInterfaceFromId(), QNetworkManagerEngine::getInterfaceFromId(), QScanThread::getSsidFromNetworkName(), QNativeWifiEngine::hasIdentifier(), QNetworkManagerEngine::hasIdentifier(), QNetworkManagerEngine::interfacePropertiesChanged(), QNetworkManagerEngine::newAccessPoint(), QNetworkManagerEngine::parseConnection(), QNlaThread::parseQuerySet(), qt_CoCreateGuid(), QNetworkManagerEngine::removeAccessPoint(), QNetworkManagerEngine::removeConnection(), QScanThread::run(), QNativeWifiEngine::scanComplete(), QConnmanEngine::serviceFromId(), QConnmanEngine::servicePropertyChangedContext(), QNetworkManagerEngine::sessionStateForId(), QCoreWlanEngine::startTime(), QNetworkManagerEngine::updateAccessPoint(), and variantHash().
 { return qHash(key.toCaseFolded()); }