Qt 4.8: /src/corelib/io/qprocess_unix.cpp File Reference
qprocess_unix.cpp File Reference
#include "qdebug.h"
#include "qplatformdefs.h"
#include "qprocess.h"
#include "qprocess_p.h"
#include "private/qcore_unix_p.h"
#include <private/qcore_mac_p.h>
#include <private/qcoreapplication_p.h>
#include <private/qthread_p.h>
#include <qfile.h>
#include <qfileinfo.h>
#include <qlist.h>
#include <qhash.h>
#include <qmutex.h>
#include <qsemaphore.h>
#include <qsocketnotifier.h>
#include <qthread.h>
#include <qelapsedtimer.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <crt_externs.h>
#include "qprocess_unix.moc"
Classes
struct QProcessInfo
class QProcessManager
Macros
#define environ (*_NSGetEnviron())
Functions
static char ** _q_dupEnvironment (const QProcessEnvironmentPrivate::Hash &environment, int *envc)
static void add_fd (int &nfds, int fd, fd_set *fdset)
static QProcessManager * processManager ()
Q_GLOBAL_STATIC (QMutex, cfbundleMutex)
static int qt_create_pipe (int *pipe)
static void qt_sa_sigchld_sigaction (int signum, siginfo_t *info, void *context)
static int qt_timeout_value (int msecs, int elapsed)
static int select_msecs (int nfds, fd_set *fdread, fd_set *fdwrite, int timeout)
Variables
static const int errorBufferMax = 512
static QBasicAtomicInt idCounter = Q_BASIC_ATOMIC_INITIALIZER(1)
static int qt_qprocess_deadChild_pipe [2]
static struct sigaction qt_sa_old_sigchld_handler
Macro Definition Documentation
environ
#define environ (*_NSGetEnviron())
Definition at line 493 of file qprocess_unix.cpp.
Function Documentation
_q_dupEnvironment()
static char** _q_dupEnvironment (const QProcessEnvironmentPrivate::Hash & environment, int * envc) static
Definition at line 518 of file qprocess_unix.cpp.
Referenced by QProcessPrivate::startProcess().
 {
     *envc = 0;
     if (environment.isEmpty())
         return 0;
     // if LD_LIBRARY_PATH exists in the current environment, but
     // not in the environment list passed by the programmer, then
     // copy it over.
 #if defined(Q_OS_MAC)
     static const char libraryPath[] = "DYLD_LIBRARY_PATH";
 #else
     static const char libraryPath[] = "LD_LIBRARY_PATH";
 #endif
     const QByteArray envLibraryPath = qgetenv(libraryPath);
     bool needToAddLibraryPath = !envLibraryPath.isEmpty() &&
                                 !environment.contains(QProcessEnvironmentPrivate::Key(QByteArray(libraryPath)));
     char **envp = new char *[environment.count() + 2];
     envp[environment.count()] = 0;
     envp[environment.count() + 1] = 0;
     QProcessEnvironmentPrivate::Hash::ConstIterator it = environment.constBegin();
     const QProcessEnvironmentPrivate::Hash::ConstIterator end = environment.constEnd();
     for ( ; it != end; ++it) {
         QByteArray key = it.key().key;
         QByteArray value = it.value().bytes();
         key.reserve(key.length() + 1 + value.length());
         key.append('=');
         key.append(value);
         envp[(*envc)++] = ::strdup(key.constData());
     }
     if (needToAddLibraryPath)
         envp[(*envc)++] = ::strdup(QByteArray(QByteArray(libraryPath) + '=' +
                                  envLibraryPath).constData());
     return envp;
 }
add_fd()
static void add_fd (int & nfds, int fd, fd_set * fdset) inline static
Definition at line 161 of file qprocess_unix.cpp.
Referenced by QProcessPrivate::waitForBytesWritten(), QProcessPrivate::waitForFinished(), and QProcessPrivate::waitForReadyRead().
 {
     FD_SET(fd, fdset);
     if ((fd) > nfds)
         nfds = fd;
 }
processManager()
static QProcessManager* processManager () static
Definition at line 198 of file qprocess_unix.cpp.
Referenced by QProcessPrivate::findExitCode(), QProcessPrivate::startDetached(), QProcessPrivate::startProcess(), and QProcessPrivate::waitForDeadChild().
{
     // The constructor of QProcessManager should be called only once
     // so we cannot use Q_GLOBAL_STATIC directly for QProcessManager
     QMutex *mutex = processManagerGlobalMutex();
     QMutexLocker locker(mutex);
     static QProcessManager processManager;
     return &processManager;
 }
Q_GLOBAL_STATIC()
Q_GLOBAL_STATIC (QMutex , cfbundleMutex)
Referenced by _q_dupEnvironment().
qt_create_pipe()
static int qt_create_pipe (int * pipe) static
Definition at line 352 of file qprocess_unix.cpp.
Referenced by QProcessPrivate::createChannel(), and QProcessPrivate::startProcess().
 {
     if (pipe[0] != -1)
         qt_safe_close(pipe[0]);
     if (pipe[1] != -1)
         qt_safe_close(pipe[1]);
     int pipe_ret = qt_safe_pipe(pipe);
     if (pipe_ret != 0) {
         qWarning("QProcessPrivate::createPipe: Cannot create pipe %p: %s",
                  pipe, qPrintable(qt_error_string(errno)));
     }
     return pipe_ret;
 }
qt_sa_sigchld_sigaction()
static void qt_sa_sigchld_sigaction (int signum, siginfo_t * info, void * context) static
Definition at line 131 of file qprocess_unix.cpp.
Referenced by QProcessManager::QProcessManager(), and QProcessManager::~QProcessManager().
 {
     // *Never* use the info or contect variables in this function
     // (except for passing them to the next signal in the chain).
     // We cannot be sure if another library or if the application
     // installed a signal handler for SIGCHLD without SA_SIGINFO
     // and fails to pass the arguments to us. If they do that,
     // these arguments contain garbage and we'd most likely crash.
     qt_safe_write(qt_qprocess_deadChild_pipe[1], "", 1);
 #if defined (QPROCESS_DEBUG)
     fprintf(stderr, "*** SIGCHLD\n");
 #endif
     // load as volatile
     volatile struct sigaction *vsa = &qt_sa_old_sigchld_handler;
     if (qt_sa_old_sigchld_handler.sa_flags & SA_SIGINFO) {
         void (*oldAction)(int, siginfo_t *, void *) = vsa->sa_sigaction;
         if (oldAction)
             oldAction(signum, info, context);
     } else {
         void (*oldAction)(int) = vsa->sa_handler;
         if (oldAction && oldAction != SIG_IGN)
             oldAction(signum);
     }
 }
qt_timeout_value()
static int qt_timeout_value (int msecs, int elapsed) static
Definition at line 1045 of file qprocess_unix.cpp.
Referenced by QProcessPrivate::waitForBytesWritten(), QProcessPrivate::waitForFinished(), and QProcessPrivate::waitForReadyRead().
 {
     if (msecs == -1)
         return -1;
     int timeout = msecs - elapsed;
     return timeout < 0 ? 0 : timeout;
 }
select_msecs()
static int select_msecs (int nfds, fd_set * fdread, fd_set * fdwrite, int timeout) static
Definition at line 1030 of file qprocess_unix.cpp.
Referenced by QProcessPrivate::waitForBytesWritten(), QProcessPrivate::waitForFinished(), QProcessPrivate::waitForReadyRead(), QProcessPrivate::waitForStarted(), and QProcessPrivate::waitForWrite().
 {
     if (timeout < 0)
         return qt_safe_select(nfds, fdread, fdwrite, 0, 0);
     struct timeval tv;
     tv.tv_sec = timeout / 1000;
     tv.tv_usec = (timeout % 1000) * 1000;
     return qt_safe_select(nfds, fdread, fdwrite, 0, &tv);
 }
Variable Documentation
errorBufferMax
const int errorBufferMax = 512 static
Definition at line 120 of file qprocess_unix.cpp.
Referenced by QProcessPrivate::processStarted().
idCounter
QBasicAtomicInt idCounter = Q_BASIC_ATOMIC_INITIALIZER(1) static
Definition at line 309 of file qprocess_unix.cpp.
qt_qprocess_deadChild_pipe
int qt_qprocess_deadChild_pipe[2] static
Definition at line 129 of file qprocess_unix.cpp.
qt_sa_old_sigchld_handler
struct sigaction qt_sa_old_sigchld_handler static
Definition at line 130 of file qprocess_unix.cpp.
Referenced by QProcessManager::QProcessManager(), qt_sa_sigchld_sigaction(), and QProcessManager::~QProcessManager().