Qt 4.8: /src/gui/painting/qrasterizer.cpp File Reference
qrasterizer.cpp File Reference
#include "qrasterizer_p.h"
#include <QPoint>
#include <QRect>
#include <private/qmath_p.h>
#include <private/qdatabuffer_p.h>
#include <private/qdrawhelper_p.h>
Classes
struct QBoolToType< B >
class QRasterizerPrivate
class QScanConverter
struct QScanConverter::Intersection
struct QScanConverter::Line
class QSpanBuffer
Macros
#define CHUNK_SIZE 64
#define COORD_OFFSET 32
#define COORD_ROUNDING 1
#define DO_SEGMENT(next, li, ri, ls, rs)
#define FloatToQ16Dot16(i) (int)((i) * qreal(65536.))
#define IntToQ16Dot16(i) ((i) << 16)
#define Q16Dot16Factor 65536
#define Q16Dot16FastMultiply(x, y) (((x) * (y)) >> 16)
#define Q16Dot16Multiply(x, y) (int)((qlonglong(x) * qlonglong(y)) >> 16)
#define Q16Dot16ToFloat(i) ((i)/qreal(65536.))
#define Q16Dot16ToInt(i) ((i) >> 16)
#define SPAN_BUFFER_SIZE 256
Typedefs
typedef int Q16Dot16
Functions
static Q16Dot16 intersectPixelFP (int x, Q16Dot16 top, Q16Dot16 bottom, Q16Dot16 leftIntersectX, Q16Dot16 rightIntersectX, Q16Dot16 slope, Q16Dot16 invSlope)
static QT_FT_Vector PointToVector (const QPointF &p)
static bool q26Dot6Compare (qreal p1, qreal p2)
static qreal qFloorF (qreal v)
static qreal qSafeDivide (qreal x, qreal y)
static int qSafeFloatToQ16Dot16 (qreal x)
template<typename T >
void qScanConvert (QScanConverter &d, T allVertical)
static QPointF snapTo26Dot6Grid (const QPointF &p)
static void split (QT_FT_Vector *b)
static bool topOrder (const QScanConverter::Line &a, const QScanConverter::Line &b)
static bool xOrder (const QScanConverter::Line *a, const QScanConverter::Line *b)
Macro Definition Documentation
CHUNK_SIZE
#define CHUNK_SIZE 64
Definition at line 124 of file qrasterizer.cpp.
Referenced by QScanConverter::emitSpans(), QScanConverter::end(), QScanConverter::prepareChunk(), and qt_inflateGZipDataFrom().
COORD_OFFSET
#define COORD_OFFSET 32
Definition at line 66 of file qrasterizer.cpp.
Referenced by QScanConverter::mergeLine(), QRasterizer::rasterize(), and QRasterizer::rasterizeLine().
COORD_ROUNDING
#define COORD_ROUNDING 1
Definition at line 65 of file qrasterizer.cpp.
Referenced by QScanConverter::mergeLine(), QRasterizer::rasterize(), and QRasterizer::rasterizeLine().
DO_SEGMENT
#define DO_SEGMENT (next, li, ri, ls, rs)
Value:
ny = qMin(next + 1, d->clipRect.top()); \
            if (y < ny) { \
                li += ls * (ny - y); \
                ri += rs * (ny - y); \
                y = ny; \
            } \
            if (next > d->clipRect.bottom()) \
                next = d->clipRect.bottom(); \
            for (; y <= next; ++y) { \
                const int x1 = qMax(Q16Dot16ToInt(li), d->clipRect.left()); \
                const int x2 = qMin(Q16Dot16ToInt(ri), d->clipRect.right()); \
                if (x2 >= x1) \
                    buffer.addSpan(x1, x2 - x1 + 1, y, 255); \
                li += ls; \
                ri += rs; \
             }
Referenced by QRasterizer::rasterizeLine().
FloatToQ16Dot16
#define FloatToQ16Dot16 (i) (int)((i) * qreal(65536.))
Definition at line 55 of file qrasterizer.cpp.
Referenced by QScanConverter::mergeLine(), and QRasterizer::rasterizeLine().
IntToQ16Dot16
#define IntToQ16Dot16 (i) ((i) << 16)
Definition at line 56 of file qrasterizer.cpp.
Referenced by QScanConverter::begin(), intersectPixelFP(), QScanConverter::mergeLine(), and QRasterizer::rasterizeLine().
Q16Dot16Factor
#define Q16Dot16Factor 65536
Definition at line 58 of file qrasterizer.cpp.
Referenced by intersectPixelFP(), QScanConverter::mergeLine(), and QRasterizer::rasterizeLine().
Q16Dot16FastMultiply
#define Q16Dot16FastMultiply (x, y) (((x) * (y)) >> 16)
Definition at line 61 of file qrasterizer.cpp.
Referenced by intersectPixelFP().
Q16Dot16Multiply
#define Q16Dot16Multiply (x, y) (int)((qlonglong(x) * qlonglong(y)) >> 16)
Definition at line 60 of file qrasterizer.cpp.
Referenced by intersectPixelFP(), QScanConverter::mergeLine(), and QRasterizer::rasterizeLine().
Q16Dot16ToFloat
#define Q16Dot16ToFloat (i) ((i)/qreal(65536.))
Definition at line 54 of file qrasterizer.cpp.
Referenced by QScanConverter::clip().
Q16Dot16ToInt
#define Q16Dot16ToInt (i) ((i) >> 16)
Definition at line 57 of file qrasterizer.cpp.
Referenced by QScanConverter::clip(), QScanConverter::end(), qScanConvert(), and QRasterizer::rasterizeLine().
SPAN_BUFFER_SIZE
#define SPAN_BUFFER_SIZE 256
Definition at line 63 of file qrasterizer.cpp.
Referenced by QSpanBuffer::addSpan().
Typedef Documentation
Q16Dot16
typedef int Q16Dot16
Definition at line 53 of file qrasterizer.cpp.
Function Documentation
intersectPixelFP()
static Q16Dot16 intersectPixelFP (int x, Q16Dot16 top, Q16Dot16 bottom, Q16Dot16 leftIntersectX, Q16Dot16 rightIntersectX, Q16Dot16 slope, Q16Dot16 invSlope) static
Definition at line 661 of file qrasterizer.cpp.
Referenced by QRasterizer::rasterizeLine().
 {
     Q16Dot16 leftX = IntToQ16Dot16(x);
     Q16Dot16 rightX = IntToQ16Dot16(x) + Q16Dot16Factor;
     Q16Dot16 leftIntersectY, rightIntersectY;
     if (slope > 0) {
         leftIntersectY = top + Q16Dot16Multiply(leftX - leftIntersectX, invSlope);
         rightIntersectY = leftIntersectY + invSlope;
     } else {
         leftIntersectY = top + Q16Dot16Multiply(leftX - rightIntersectX, invSlope);
         rightIntersectY = leftIntersectY + invSlope;
     }
     if (leftIntersectX >= leftX && rightIntersectX <= rightX) {
         return Q16Dot16Multiply(bottom - top, leftIntersectX - leftX + ((rightIntersectX - leftIntersectX) >> 1));
     } else if (leftIntersectX >= rightX) {
         return bottom - top;
     } else if (leftIntersectX >= leftX) {
         if (slope > 0) {
             return (bottom - top) - Q16Dot16FastMultiply((rightX - leftIntersectX) >> 1, rightIntersectY - top);
         } else {
             return (bottom - top) - Q16Dot16FastMultiply((rightX - leftIntersectX) >> 1, bottom - rightIntersectY);
         }
     } else if (rightIntersectX <= leftX) {
         return 0;
     } else if (rightIntersectX <= rightX) {
         if (slope > 0) {
             return Q16Dot16FastMultiply((rightIntersectX - leftX) >> 1, bottom - leftIntersectY);
         } else {
             return Q16Dot16FastMultiply((rightIntersectX - leftX) >> 1, leftIntersectY - top);
         }
     } else {
         if (slope > 0) {
             return (bottom - rightIntersectY) + ((rightIntersectY - leftIntersectY) >> 1);
         } else {
             return (rightIntersectY - top) + ((leftIntersectY - rightIntersectY) >> 1);
         }
     }
 }
PointToVector()
static QT_FT_Vector PointToVector (const QPointF & p) inline static
Definition at line 68 of file qrasterizer.cpp.
Referenced by QRasterizer::rasterize().
 {
     QT_FT_Vector result = { QT_FT_Pos(p.x() * 64), QT_FT_Pos(p.y() * 64) };
     return result;
 }
q26Dot6Compare()
static bool q26Dot6Compare (qreal p1, qreal p2) inline static
Definition at line 702 of file qrasterizer.cpp.
Referenced by QRasterizer::rasterizeLine().
 {
     return int((p2  - p1) * qreal(64.)) == 0;
 }
qFloorF()
static qreal qFloorF (qreal v) inline static
Definition at line 707 of file qrasterizer.cpp.
Referenced by snapTo26Dot6Grid().
 {
 #ifdef QT_USE_MATH_H_FLOATS
     if (sizeof(qreal) == sizeof(float))
         return floorf(v);
     else
 #endif
         return floor(v);
 }
qSafeDivide()
static qreal qSafeDivide (qreal x, qreal y) inline static
Definition at line 731 of file qrasterizer.cpp.
Referenced by QRasterizer::rasterizeLine().
 {
     if (y == 0)
         return x > 0 ? 1e20 : -1e20;
     return x / y;
 }
qSafeFloatToQ16Dot16()
static int qSafeFloatToQ16Dot16 (qreal x) inline static
Definition at line 742 of file qrasterizer.cpp.
Referenced by QRasterizer::rasterizeLine().
 {
     qreal tmp = x * 65536.;
     if (tmp > qreal(INT_MAX))
         return INT_MAX;
     else if (tmp < qreal(INT_MIN))
         return -INT_MAX;
     return int(tmp);
 }
qScanConvert()
template<typename T > void qScanConvert (QScanConverter & d, T allVertical)
Definition at line 319 of file qrasterizer.cpp.
 {
     if (!d.m_lines.size()) {
         d.m_active.reset();
         return;
     }
     qSort(d.m_lines.data(), d.m_lines.data() + d.m_lines.size(), QT_PREPEND_NAMESPACE(topOrder));
     int line = 0;
     for (int y = d.m_lines.first().top; y <= d.m_bottom; ++y) {
         for (; line < d.m_lines.size() && d.m_lines.at(line).top == y; ++line) {
             // add node to active list
             if (allVertical()) {
                 QScanConverter::Line *l = &d.m_lines.at(line);
                 d.m_active.resize(d.m_active.size() + 1);
                 int j;
                 for (j = d.m_active.size() - 2; j >= 0 && QT_PREPEND_NAMESPACE(xOrder)(l, d.m_active.at(j)); --j)
                     d.m_active.at(j+1) = d.m_active.at(j);
                 d.m_active.at(j+1) = l;
             } else {
                 d.m_active << &d.m_lines.at(line);
             }
         }
         int numActive = d.m_active.size();
         if (!allVertical()) {
         // use insertion sort instead of qSort, as the active edge list is quite small
         // and in the average case already sorted
             for (int i = 1; i < numActive; ++i) {
                 QScanConverter::Line *l = d.m_active.at(i);
                 int j;
                 for (j = i-1; j >= 0 && QT_PREPEND_NAMESPACE(xOrder)(l, d.m_active.at(j)); --j)
                     d.m_active.at(j+1) = d.m_active.at(j);
                 d.m_active.at(j+1) = l;
             }
         }
         int x = 0;
         int winding = 0;
         for (int i = 0; i < numActive; ++i) {
             QScanConverter::Line *node = d.m_active.at(i);
             const int current = Q16Dot16ToInt(node->x);
             if (winding & d.m_fillRuleMask)
                 d.m_spanBuffer->addSpan(x, current - x, y, 0xff);
             x = current;
             winding += node->winding;
             if (node->bottom == y) {
                 // remove node from active list
                 for (int j = i; j < numActive - 1; ++j)
                     d.m_active.at(j) = d.m_active.at(j+1);
                 d.m_active.resize(--numActive);
                 --i;
             } else if (!allVertical())
                 node->x += node->delta;
         }
     }
     d.m_active.reset();
 }
snapTo26Dot6Grid()
static QPointF snapTo26Dot6Grid (const QPointF & p) inline static
Definition at line 717 of file qrasterizer.cpp.
Referenced by QRasterizer::rasterizeLine().
 {
     return QPointF(qFloorF(p.x() * 64) * (1 / qreal(64)),
                    qFloorF(p.y() * 64) * (1 / qreal(64)));
 }
split()
static void split (QT_FT_Vector * b) static
Definition at line 274 of file qrasterizer.cpp.
Referenced by QItemSelectionModelPrivate::_q_columnsAboutToBeInserted(), QItemSelectionModelPrivate::_q_rowsAboutToBeInserted(), QCoreApplication::applicationFilePath(), QDBusAbstractInterface::callWithArgumentList(), QDeclarativeCompiler::deferredProperties(), QNativeWifiEngine::disconnectFromId(), QIntersectionFinder::hasIntersections(), QByteArray::isSharedWith(), QStringList::lastIndexOf(), QItemSelection::merge(), QScanConverter::mergeCurve(), QXlibMime::mimeConvertToFormat(), QStringList::operator<<(), QBezier::pt4(), QItemSelection::QItemSelection(), QTextDocumentPrivate::setDefaultFont(), QTriangulator< T >::ComplexToSimple::splitEdge(), QTriangulator< T >::ComplexToSimple::splitEdgeListRange(), and QX11Data::xdndMimeConvertToFormat().
 {
     b[6] = b[3];
     {
         const QT_FT_Pos temp = (b[1].x + b[2].x)/2;
         b[1].x = (b[0].x + b[1].x)/2;
         b[5].x = (b[2].x + b[3].x)/2;
         b[2].x = (b[1].x + temp)/2;
         b[4].x = (b[5].x + temp)/2;
         b[3].x = (b[2].x + b[4].x)/2;
     }
     {
         const QT_FT_Pos temp = (b[1].y + b[2].y)/2;
         b[1].y = (b[0].y + b[1].y)/2;
         b[5].y = (b[2].y + b[3].y)/2;
         b[2].y = (b[1].y + temp)/2;
         b[4].y = (b[5].y + temp)/2;
         b[3].y = (b[2].y + b[4].y)/2;
     }
 }
topOrder()
static bool topOrder (const QScanConverter::Line & a, const QScanConverter::Line & b) inline static
Definition at line 298 of file qrasterizer.cpp.
Referenced by qScanConvert().
 {
     return a.top < b.top;
 }
xOrder()
static bool xOrder (const QScanConverter::Line * a, const QScanConverter::Line * b) inline static
Definition at line 303 of file qrasterizer.cpp.
Referenced by qScanConvert().
 {
     return a->x < b->x;
 }