Qt 4.8: /src/gui/text/qrawfont_mac.cpp File Reference
qrawfont_mac.cpp File Reference
#include <QtCore/qglobal.h>
#include "qrawfont_p.h"
#include "qfontengine_coretext_p.h"
Functions
int qt_defaultDpi ()
static void releaseFontData (void *info, const void *data, size_t size)
Function Documentation
qt_defaultDpi()
int qt_defaultDpi ()
Definition at line 240 of file qfont.cpp.
Referenced by QTextDocumentLayoutPrivate::blockIndent(), QPicturePaintEngine::drawTextItem(), getImageSize(), getPixmapSize(), QMacPrintEnginePrivate::initialize(), QTextDocumentLayoutPrivate::layoutBlock(), QFontMetrics::QFontMetrics(), QFontMetricsF::QFontMetricsF(), QPdfBaseEnginePrivate::QPdfBaseEnginePrivate(), qt_load_font_engine_win(), releaseFontData(), QTextDocumentLayoutPrivate::scaleToDevice(), QDeclarativeFontValueType::setPointSize(), and QDeclarativeFontValueType::setStrikeout().
 {
     return qt_defaultDpiY();
 }
releaseFontData()
static void releaseFontData (void * info, const void * data, size_t size) static
Definition at line 55 of file qrawfont_mac.cpp.
 {
     Q_UNUSED(data);
     Q_UNUSED(size);
     delete (QByteArray*)info;
 }