Qt 4.8: /src/gui/text/qrawfont.cpp File Reference
qrawfont.cpp File Reference
#include "qglobal.h"
#include "qrawfont.h"
#include "qrawfont_p.h"
#include <QtCore/qendian.h>
Functions
QList< QFontDatabase::WritingSystem > qt_determine_writing_systems_from_truetype_bits (quint32 unicodeRange[4], quint32 codePageRange[2])
int qt_script_for_writing_system (QFontDatabase::WritingSystem writingSystem)
Function Documentation
qt_determine_writing_systems_from_truetype_bits()
QList<QFontDatabase::WritingSystem> qt_determine_writing_systems_from_truetype_bits (quint32 unicodeRange[4], quint32 codePageRange[2])
Definition at line 587 of file qfontdatabase.cpp.
Referenced by addFontToDatabase(), QFontDatabasePrivate::addTTFile(), QRawFont::fontTable(), initWritingSystems(), and QRawFont::supportedWritingSystems().
 {
     QList<QFontDatabase::WritingSystem> writingSystems;
     bool hasScript = false;
     int i;
     for(i = 0; i < QFontDatabase::WritingSystemsCount; i++) {
         int bit = requiredUnicodeBits[i][0];
         int index = bit/32;
         int flag =  1 << (bit&31);
         if (bit != 126 && unicodeRange[index] & flag) {
             bit = requiredUnicodeBits[i][1];
             index = bit/32;
             flag =  1 << (bit&31);
             if (bit == 127 || unicodeRange[index] & flag) {
                 writingSystems.append(QFontDatabase::WritingSystem(i));
                 hasScript = true;
                 // qDebug("font %s: index=%d, flag=%8x supports script %d", familyName.latin1(), index, flag, i);
             }
         }
     }
     if(codePageRange[0] & (1 << SimplifiedChineseCsbBit)) {
         writingSystems.append(QFontDatabase::SimplifiedChinese);
         hasScript = true;
         //qDebug("font %s supports Simplified Chinese", familyName.latin1());
     }
     if(codePageRange[0] & (1 << TraditionalChineseCsbBit)) {
         writingSystems.append(QFontDatabase::TraditionalChinese);
         hasScript = true;
         //qDebug("font %s supports Traditional Chinese", familyName.latin1());
     }
     if(codePageRange[0] & (1 << JapaneseCsbBit)) {
         writingSystems.append(QFontDatabase::Japanese);
         hasScript = true;
         //qDebug("font %s supports Japanese", familyName.latin1());
     }
     if(codePageRange[0] & (1 << KoreanCsbBit)) {
         writingSystems.append(QFontDatabase::Korean);
         hasScript = true;
         //qDebug("font %s supports Korean", familyName.latin1());
     }
     if (!hasScript)
         writingSystems.append(QFontDatabase::Symbol);
     return writingSystems;
 }
qt_script_for_writing_system()
int qt_script_for_writing_system (QFontDatabase::WritingSystem writingSystem)
Definition at line 938 of file qfontdatabase.cpp.
Referenced by QRawFont::fromFont(), and QRawFont::supportsCharacter().
 {
     return scriptForWritingSystem[writingSystem];
 }