Qt 4.8: /src/gui/painting/qregion_win.cpp File Reference
qregion_win.cpp File Reference
#include "qatomic.h"
#include "qbitmap.h"
#include "qbuffer.h"
#include "qimage.h"
#include "qpolygon.h"
#include "qregion.h"
#include "qt_windows.h"
#include "qpainterpath.h"
Functions
static void qt_add_rect (HRGN &winRegion, QRect r)
QRegion qt_region_from_HRGN (HRGN rgn)
HRGN qt_tryCreateRegion (QRegion::RegionType type, int left, int top, int right, int bottom)
void qt_win_dispose_rgn (HRGN r)
Function Documentation
qt_add_rect()
static void qt_add_rect (HRGN & winRegion, QRect r) static
Definition at line 116 of file qregion_win.cpp.
Referenced by QRegion::ensureHandle().
 {
     HRGN rgn = CreateRectRgn(r.left(), r.top(), r.x() + r.width(), r.y() + r.height());
     if (rgn) {
         HRGN dest = CreateRectRgn(0,0,0,0);
         int result = CombineRgn(dest, winRegion, rgn, RGN_OR);
         if (result) {
             DeleteObject(winRegion);
             winRegion = dest;
         }
         DeleteObject(rgn);
     }
 }
qt_region_from_HRGN()
QRegion qt_region_from_HRGN (HRGN rgn)
Definition at line 80 of file qregion_win.cpp.
Referenced by QWindowsXPStylePrivate::region().
 {
     int numBytes = GetRegionData(rgn, 0, 0);
     if (numBytes == 0)
         return QRegion();
     char *buf = new char[numBytes];
     if (buf == 0)
         return QRegion();
     RGNDATA *rd = reinterpret_cast<RGNDATA*>(buf);
     if (GetRegionData(rgn, numBytes, rd) == 0) {
         delete [] buf;
         return QRegion();
     }
     QRegion region;
     RECT *r = reinterpret_cast<RECT*>(rd->Buffer);
     for (uint i = 0; i < rd->rdh.nCount; ++i) {
         QRect rect;
         rect.setCoords(r->left, r->top, r->right - 1, r->bottom - 1);
         ++r;
         region |= rect;
     }
     delete [] buf;
     return region;
 }
qt_tryCreateRegion()
HRGN qt_tryCreateRegion (QRegion::RegionType type, int left, int top, int right, int bottom)
Definition at line 55 of file qregion_win.cpp.
Referenced by qt_grab_cursor(), and QtWndProc().
 {
     const int tries = 10;
     for (int i = 0; i < tries; ++i) {
         HRGN region = 0;
         switch (type) {
         case QRegion::Rectangle:
             region = CreateRectRgn(left, top, right, bottom);
             break;
         case QRegion::Ellipse:
 #ifndef Q_OS_WINCE
             region = CreateEllipticRgn(left, top, right, bottom);
 #endif
             break;
         }
         if (region) {
             if (GetRegionData(region, 0, 0))
                 return region;
             else
                 DeleteObject(region);
         }
     }
     return 0;
 }
qt_win_dispose_rgn()
void qt_win_dispose_rgn (HRGN r)
Definition at line 110 of file qregion_win.cpp.
Referenced by QRegion::cleanUp().
 {
     if (r)
         DeleteObject(r);
 }