Qt 4.8: /src/corelib/io/qresource.cpp File Reference
qresource.cpp File Reference
#include "qresource.h"
#include "qresource_p.h"
#include "qresource_iterator_p.h"
#include "qset.h"
#include "qhash.h"
#include "qmutex.h"
#include "qdebug.h"
#include "qlocale.h"
#include "qglobal.h"
#include "qvector.h"
#include "qdatetime.h"
#include "qbytearray.h"
#include "qstringlist.h"
#include <qshareddata.h>
#include <qplatformdefs.h>
#include "private/qabstractfileengine_p.h"
#include "private/qcore_unix_p.h"
#include <sys/mman.h>
#include <errno.h>
Classes
class QDynamicBufferResourceRoot
class QDynamicFileResourceRoot
class QResourceFileEnginePrivate
class QResourcePrivate
class QResourceRoot
class QStringSplitter
Macros
#define MAP_FAILED -1
#define MAP_FILE 0
#define QT_USE_MMAP
Typedefs
typedef QList< QResourceRoot * > ResourceList
Functions
static QString cleanPath (const QString &_path)
Q_DECLARE_TYPEINFO (QResourceRoot, Q_MOVABLE_TYPE)
Q_CORE_EXPORT void qInitResourceIO ()
Q_CORE_EXPORT bool qRegisterResourceData (int version, const unsigned char *tree, const unsigned char *name, const unsigned char *data)
static QString qt_resource_fixResourceRoot (QString r)
Q_CORE_EXPORT bool qUnregisterResourceData (int version, const unsigned char *tree, const unsigned char *name, const unsigned char *data)
Macro Definition Documentation
MAP_FAILED
#define MAP_FAILED -1
Referenced by QFontDatabasePrivate::addQPF2File(), QSharedMemoryPrivate::attach(), QFontEngineQPF::cleanUpAfterClientCrash(), QFSFileEnginePrivate::map(), QFontEngineQPF::QFontEngineQPF(), QWaylandShmBuffer::QWaylandShmBuffer(), QDynamicFileResourceRoot::registerSelf(), and QFontEngineQPF::remapFontData().
MAP_FILE
#define MAP_FILE 0
Referenced by QDynamicFileResourceRoot::registerSelf().
QT_USE_MMAP
#define QT_USE_MMAP
Definition at line 944 of file qresource.cpp.
Typedef Documentation
ResourceList
typedef QList<QResourceRoot*> ResourceList
Definition at line 162 of file qresource.cpp.
Function Documentation
cleanPath()
static QString cleanPath (const QString & _path) static
Definition at line 148 of file qresource.cpp.
Referenced by QResourcePrivate::ensureChildren(), QResourcePrivate::load(), and QDir::temp().
 {
     QString path = QDir::cleanPath(_path);
     // QDir::cleanPath does not remove two trailing slashes under _Windows_
     // due to support for UNC paths. Remove those manually.
     if (path.startsWith(QLatin1String("//")))
         path.remove(0, 1);
     return path;
 }
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QResourceRoot , Q_MOVABLE_TYPE)
Referenced by cleanPath().
qInitResourceIO()
Q_CORE_EXPORT void qInitResourceIO ()
Definition at line 1512 of file qresource.cpp.
 { } // ### Qt 5: remove
qRegisterResourceData()
Q_CORE_EXPORT bool qRegisterResourceData (int version, const unsigned char * tree, const unsigned char * name, const unsigned char * data)
Definition at line 850 of file qresource.cpp.
 {
     QMutexLocker lock(resourceMutex());
     if(version == 0x01 && resourceList()) {
         bool found = false;
         QResourceRoot res(tree, name, data);
         for(int i = 0; i < resourceList()->size(); ++i) {
             if(*resourceList()->at(i) == res) {
                 found = true;
                 break;
             }
         }
         if(!found) {
             QResourceRoot *root = new QResourceRoot(tree, name, data);
             root->ref.ref();
             resourceList()->append(root);
         }
         return true;
     }
     return false;
 }
qt_resource_fixResourceRoot()
static QString qt_resource_fixResourceRoot (QString r) static
Definition at line 1052 of file qresource.cpp.
Referenced by QResource::registerResource(), and QResource::unregisterResource().
{
     if(!r.isEmpty()) {
         if(r.startsWith(QLatin1Char(':')))
             r = r.mid(1);
         if(!r.isEmpty())
             r = QDir::cleanPath(r);
     }
     return r;
 }
qUnregisterResourceData()
Q_CORE_EXPORT bool qUnregisterResourceData (int version, const unsigned char * tree, const unsigned char * name, const unsigned char * data)
Definition at line 873 of file qresource.cpp.
 {
     QMutexLocker lock(resourceMutex());
     if(version == 0x01 && resourceList()) {
         QResourceRoot res(tree, name, data);
         for(int i = 0; i < resourceList()->size(); ) {
             if(*resourceList()->at(i) == res) {
                 QResourceRoot *root = resourceList()->takeAt(i);
                 if(!root->ref.deref())
                     delete root;
             } else {
                 ++i;
             }
         }
         return true;
     }
     return false;
 }