Qt 4.8: /src/plugins/gfxdrivers/ahi/qscreenahi_qws.cpp File Reference
qscreenahi_qws.cpp File Reference
#include "qscreenahi_qws.h"
#include <QtGui/qcolor.h>
#include <QtGui/qapplication.h>
#include <QtCore/qvector.h>
#include <QtCore/qvarlengtharray.h>
#include <private/qwssignalhandler_p.h>
#include <ahi.h>
Classes
class QAhiScreenCursor
class QAhiScreenPrivate
Functions
static int depthForPixelFormat (const AhiPixelFormat_t format)
static AhiPixelFormat_t pixelFormatForImageFormat (const QImage::Format format)
Function Documentation
depthForPixelFormat()
static int depthForPixelFormat (const AhiPixelFormat_t format) static
Definition at line 56 of file qscreenahi_qws.cpp.
Referenced by QAhiScreen::setMode().
 {
     switch (format) {
     case AhiPix1bpp:
         return 1;
     case AhiPix2bpp:
         return 2;
     case AhiPix4bpp:
         return 4;
     case AhiPix8bpp_332RGB:
     case AhiPix8bpp:
         return 8;
     case AhiPix16bpp_444RGB:
         return 12;
     case AhiPix16bpp_555RGB:
         return 15;
     case AhiPix16bpp_565RGB:
         return 16;
     case AhiPix32bpp_8888ARGB:
     case AhiPix32bpp_8888BGRA:
         return 32;
     default:
         return 0;
     }
 }
pixelFormatForImageFormat()
static AhiPixelFormat_t pixelFormatForImageFormat (const QImage::Format format) static
Definition at line 82 of file qscreenahi_qws.cpp.
Referenced by QAhiScreen::blit(), and QAhiScreenCursor::set().
 {
     switch (format) {
     case QImage::Format_Mono:
     case QImage::Format_MonoLSB:
         return AhiPix1bpp;
     case QImage::Format_Indexed8:
         return AhiPix8bpp;
     case QImage::Format_RGB32:
     case QImage::Format_ARGB32:
     case QImage::Format_ARGB32_Premultiplied:
         return AhiPix32bpp_8888ARGB;
     case QImage::Format_RGB16:
         return AhiPix16bpp_565RGB;
     case QImage::Format_RGB555:
         return AhiPix16bpp_555RGB;
     case QImage::Format_ARGB4444_Premultiplied:
     case QImage::Format_RGB444:
         return AhiPix16bpp_444RGB;
     default:
         return AhiPixelFormatMax;
     }
 }