Qt 4.8: /src/plugins/gfxdrivers/vnc/qscreenvnc_qws.cpp File Reference
qscreenvnc_qws.cpp File Reference
#include "qscreenvnc_qws.h"
#include "qscreenvnc_p.h"
#include "qwindowsystem_qws.h"
#include "qwsdisplay_qws.h"
#include "qscreendriverfactory_qws.h"
#include <QtCore/qtimer.h>
#include <QtCore/qregexp.h>
#include <QtGui/qwidget.h>
#include <QtGui/qpolygon.h>
#include <QtGui/qpainter.h>
#include <qdebug.h>
#include <private/qwindowsurface_qws_p.h>
#include <private/qwssignalhandler_p.h>
#include <private/qwidget_p.h>
#include <private/qdrawhelper_p.h>
#include <stdlib.h>
Functions
static void blendCursor (QImage &image, const QRect &imageRect)
static int getDisplayId (const QString &spec)
QString qws_qtePipeFilename ()
Variables
struct {
int keycode
int keysym
} keyMap []
Function Documentation
blendCursor()
static void blendCursor (QImage & image, const QRect & imageRect) static
Definition at line 1651 of file qscreenvnc_qws.cpp.
Referenced by QRfbRawEncoder::write(), and QRfbHextileEncoder< SRC >::write().
 {
     const QRect cursorRect = qt_screencursor->boundingRect();
     const QRect intersection = (cursorRect & imageRect);
     const QRect destRect = intersection.translated(-imageRect.topLeft());
     const QRect srcRect = intersection.translated(-cursorRect.topLeft());
     QPainter painter(&image);
     painter.drawImage(destRect, qt_screencursor->image(), srcRect);
     painter.end();
 }
getDisplayId()
static int getDisplayId (const QString & spec) static
Definition at line 2129 of file qscreenvnc_qws.cpp.
Referenced by QVNCScreen::connect().
 {
     QRegExp regexp(QLatin1String(":(\\d+)\\b"));
     if (regexp.lastIndexIn(spec) != -1) {
         const QString capture = regexp.cap(1);
         return capture.toInt();
     }
     return 0;
 }
qws_qtePipeFilename()
QString qws_qtePipeFilename ()
Definition at line 220 of file qapplication_qws.cpp.
Referenced by QVNCScreenPrivate::configure(), QWSDisplay::Data::connectToPipe(), QWSDisplay::Data::init(), and QWSDisplay::Data::reinit().
 {
     qws_dataDir();
     return QTE_PIPE(qws_display_id);
 }
Variable Documentation
keycode
int keycode
Definition at line 292 of file qscreenvnc_qws.cpp.
Referenced by QWSIntKbPrivate::dataReady(), QAxWidget::qObject(), QRfbKeyEvent::read(), QDirectFBKeyboardHandlerPrivate::readKeyboardData(), QWSServerPrivate::sendKeyEventUnfiltered(), QRfbServerInit::size(), translateKeySym(), and QWSServer::KeyboardFilter::~KeyboardFilter().
keyMap
const { ... } keyMap[]
Referenced by QRfbKeyEvent::read().
keysym
int keysym
Definition at line 291 of file qscreenvnc_qws.cpp.
Referenced by qt_keyrelease_scanner(), QRfbKeyEvent::read(), and translateKeySym().