Qt 4.8: /src/scripttools/debugging/qscriptdebuggerlocalsmodel.cpp File Reference
qscriptdebuggerlocalsmodel.cpp File Reference
#include "qscriptdebuggerlocalsmodel_p.h"
#include "qscriptdebuggercommandschedulerjob_p.h"
#include "qscriptdebuggervalue_p.h"
#include "qscriptdebuggerresponse_p.h"
#include "qscriptdebuggerevent_p.h"
#include "qscriptdebuggervalueproperty_p.h"
#include "qscriptdebuggercommandschedulerinterface_p.h"
#include "qscriptdebuggercommandschedulerfrontend_p.h"
#include "qscriptdebuggerjobschedulerinterface_p.h"
#include "qscriptdebuggerobjectsnapshotdelta_p.h"
#include "private/qabstractitemmodel_p.h"
#include <QtCore/qdebug.h>
#include <QtCore/qcoreapplication.h>
#include <QtCore/qpointer.h>
#include <QtGui/qbrush.h>
#include <QtGui/qfont.h>
Classes
struct QScriptDebuggerLocalsModelNode
class QScriptDebuggerLocalsModelPrivate
Functions
static QList< qint64 > findSnapshotIdsRecursively (QScriptDebuggerLocalsModelNode *root)
Function Documentation
findSnapshotIdsRecursively()
static QList<qint64> findSnapshotIdsRecursively (QScriptDebuggerLocalsModelNode * root) static
Definition at line 165 of file qscriptdebuggerlocalsmodel.cpp.
Referenced by QScriptDebuggerLocalsModelPrivate::deleteAllObjectSnapshots(), QScriptDebuggerLocalsModelPrivate::depopulate(), and QScriptDebuggerLocalsModelPrivate::removeChild().
 {
     QList<qint64> result;
     if (root->snapshotId == -1) {
         Q_ASSERT(root->children.isEmpty());
         return result;
     }
     QList<QScriptDebuggerLocalsModelNode*> nodeStack;
     nodeStack.append(root);
     while (!nodeStack.isEmpty()) {
         QScriptDebuggerLocalsModelNode *node = nodeStack.takeFirst();
         result.append(node->snapshotId);
         for (int i = 0; i < node->children.count(); ++i) {
             QScriptDebuggerLocalsModelNode *child = node->children.at(i);
             if (child->snapshotId != -1)
                 nodeStack.prepend(child);
         }
     }
     return result;
 }