Qt 4.8: /src/script/api/qscriptengine.h File Reference
qscriptengine.h File Reference
#include <QtCore/qmetatype.h>
#include <QtCore/qvariant.h>
#include <QtCore/qsharedpointer.h>
#include <QtCore/qobject.h>
#include <QtScript/qscriptvalue.h>
#include <QtScript/qscriptcontext.h>
#include <QtScript/qscriptstring.h>
#include <QtScript/qscriptprogram.h>
Classes
class QScriptEngine
The QScriptEngine class provides an environment for evaluating Qt Script code.
class QScriptSyntaxCheckResult
The QScriptSyntaxCheckResult class provides the result of a script syntax check.
Macros
#define Q_SCRIPT_DECLARE_QMETAOBJECT(T, _Arg1)
Functions
Q_SCRIPT_EXPORT bool qScriptConnect (QObject *sender, const char *signal, const QScriptValue &receiver, const QScriptValue &function)
Q_SCRIPT_EXPORT bool qScriptDisconnect (QObject *sender, const char *signal, const QScriptValue &receiver, const QScriptValue &function)
template<class T >
QScriptValue qscriptQMetaObjectConstructor (QScriptContext *, QScriptEngine *, T *)
template<typename T >
int qScriptRegisterMetaType (QScriptEngine *eng, QScriptValue(*toScriptValue)(QScriptEngine *, const T &t), void(*fromScriptValue)(const QScriptValue &, T &t), const QScriptValue &prototype=QScriptValue())
void qScriptRegisterMetaType_helper (QScriptEngine *eng, int type, QScriptEngine::MarshalFunction mf, QScriptEngine::DemarshalFunction df, const QScriptValue &prototype)
template<typename T >
int qScriptRegisterSequenceMetaType (QScriptEngine *engine, const QScriptValue &prototype=QScriptValue())
template<typename T >
T qscriptvalue_cast (const QScriptValue &)
template<>
QVariant qscriptvalue_cast< QVariant > (const QScriptValue &value)
bool qscriptvalue_cast_helper (const QScriptValue &value, int type, void *ptr)
template<class T >
QT_DEPRECATED QScriptValue qScriptValueFromQMetaObject (QScriptEngine *engine)
template<class Container >
QScriptValue qScriptValueFromSequence (QScriptEngine *eng, const Container &cont)
template<typename T >
QScriptValue qScriptValueFromValue (QScriptEngine *, const T &)
template<>
QScriptValue qScriptValueFromValue< QVariant > (QScriptEngine *engine, const QVariant &v)
QScriptValue qScriptValueFromValue_helper (QScriptEngine *engine, int type, const void *ptr)
template<class Container >
void qScriptValueToSequence (const QScriptValue &value, Container &cont)
template<typename T >
QT_DEPRECATED T qScriptValueToValue (const QScriptValue &value)
Macro Definition Documentation
Q_SCRIPT_DECLARE_QMETAOBJECT
#define Q_SCRIPT_DECLARE_QMETAOBJECT (T, _Arg1)
Value:
template<> inline QScriptValue qscriptQMetaObjectConstructor<T>(QScriptContext *ctx, QScriptEngine *eng, T *) \
{ \
    _Arg1 arg1 = qscriptvalue_cast<_Arg1> (ctx->argument(0)); \
    T* t = new T(arg1); \
    if (ctx->isCalledAsConstructor()) \
        return eng->newQObject(ctx->thisObject(), t, QScriptEngine::AutoOwnership); \
    QScriptValue o = eng->newQObject(t, QScriptEngine::AutoOwnership); \
    o.setPrototype(ctx->callee().property(QString::fromLatin1("prototype"))); \
    return o; \
}
Since
4.3
Declares the given QMetaObject. Used in combination with QScriptEngine::scriptValueFromQMetaObject() to make enums and instantiation of QMetaObject available to script code. The constructor generated by this macro takes a single argument of type ArgType; typically the argument is the parent type of the new instance, in which case ArgType is QWidget* or QObject*. Objects created by the constructor will have QScriptEngine::AutoOwnership ownership.
Definition at line 283 of file qscriptengine.h.
Function Documentation
qScriptConnect()
Q_SCRIPT_EXPORT bool qScriptConnect (QObject * sender, const char * signal, const QScriptValue & receiver, const QScriptValue & function) related
Referenced by QDeclarativeObjectMethodScriptClass::connect(), and qScriptRegisterSequenceMetaType().
qScriptDisconnect()
Q_SCRIPT_EXPORT bool qScriptDisconnect (QObject * sender, const char * signal, const QScriptValue & receiver, const QScriptValue & function) related
Referenced by QDeclarativeObjectMethodScriptClass::disconnect(), and qScriptRegisterSequenceMetaType().
qscriptQMetaObjectConstructor()
template<class T > QScriptValue qscriptQMetaObjectConstructor (QScriptContext * , QScriptEngine * , T *) inline
Definition at line 57 of file qscriptengine.h.
 {
     return QScriptValue();
 }
qScriptRegisterMetaType()
template<typename T > int qScriptRegisterMetaType (QScriptEngine * eng, QScriptValue(*)(QScriptEngine *, const T &t) toScriptValue, void(*)(const QScriptValue &, T &t) fromScriptValue, const QScriptValue & prototype = QScriptValue()) related
Definition at line 380 of file qscriptengine.h.
 {
     const int id = qRegisterMetaType<T>(); // make sure it's registered
     qScriptRegisterMetaType_helper(
         eng, id, reinterpret_cast<QScriptEngine::MarshalFunction>(toScriptValue),
         reinterpret_cast<QScriptEngine::DemarshalFunction>(fromScriptValue),
         prototype);
     return id;
 }
qScriptRegisterMetaType_helper()
void qScriptRegisterMetaType_helper (QScriptEngine * eng, int type, QScriptEngine::MarshalFunction mf, QScriptEngine::DemarshalFunction df, const QScriptValue & prototype) inline
Definition at line 371 of file qscriptengine.h.
Referenced by QScriptEngine::fromScriptValue(), and qScriptRegisterMetaType().
 {
     eng->registerCustomType(type, mf, df, prototype);
 }
qScriptRegisterSequenceMetaType()
template<typename T > int qScriptRegisterSequenceMetaType (QScriptEngine * engine, const QScriptValue & prototype = QScriptValue()) related
Definition at line 424 of file qscriptengine.h.
 {
     return qScriptRegisterMetaType<T>(engine, qScriptValueFromSequence,
                                       qScriptValueToSequence, prototype);
 }
qscriptvalue_cast()
template<typename T > T qscriptvalue_cast (const QScriptValue & value) related
Definition at line 344 of file qscriptengine.h.
Referenced by Node::attributes(), Node::childNodes(), Document::documentElement(), Node::firstChild(), QScriptEngine::fromScriptValue(), Text::isElementContentWhitespace(), Node::lastChild(), NamedNodeMap::length(), NodeList::length(), CharacterData::length(), Attr::name(), Node::nextSibling(), Node::nodeName(), Node::nodeType(), Node::nodeValue(), Attr::ownerElement(), Node::parentNode(), Node::previousSibling(), QDeclarativeSqlQueryScriptClass::property(), NamedNodeMapClass::property(), NodeListClass::property(), qmlsqldatabase_change_version(), qmlsqldatabase_executeSql(), qmlsqldatabase_item(), qmlsqldatabase_transaction_shared(), qScriptValueToValue(), NamedNodeMapClass::queryProperty(), NodeListClass::queryProperty(), QDeclarativeSqlQueryScriptClass::setProperty(), QScriptDebuggerBackendPrivate::trace(), Attr::value(), Text::wholeText(), Document::xmlEncoding(), Document::xmlStandalone(), and Document::xmlVersion().
 {
     T t;
     const int id = qMetaTypeId<T>();
     if (qscriptvalue_cast_helper(value, id, &t))
         return t;
     else if (value.isVariant())
         return qvariant_cast<T>(value.toVariant());
     return T();
 }
qscriptvalue_cast< QVariant >()
template<> QVariant qscriptvalue_cast< QVariant > (const QScriptValue & value) inline
Definition at line 358 of file qscriptengine.h.
 {
     return value.toVariant();
 }
qscriptvalue_cast_helper()
bool qscriptvalue_cast_helper (const QScriptValue & value, int type, void * ptr) inline
Definition at line 338 of file qscriptengine.h.
Referenced by QScriptEngine::fromScriptValue(), and qscriptvalue_cast().
 {
     return QScriptEngine::convertV2(value, type, ptr);
 }
qScriptValueFromQMetaObject()
template<class T > QT_DEPRECATED QScriptValue qScriptValueFromQMetaObject (QScriptEngine * engine) related
Definition at line 305 of file qscriptengine.h.
 {
     return engine->scriptValueFromQMetaObject<T>();
 }
qScriptValueFromSequence()
template<class Container > QScriptValue qScriptValueFromSequence (QScriptEngine * eng, const Container & cont) related
Definition at line 401 of file qscriptengine.h.
Referenced by qScriptRegisterSequenceMetaType().
 {
     QScriptValue a = eng->newArray();
     typename Container::const_iterator begin = cont.begin();
     typename Container::const_iterator end = cont.end();
     typename Container::const_iterator it;
     quint32 i;
     for (it = begin, i = 0; it != end; ++it, ++i)
         a.setProperty(i, eng->toScriptValue(*it));
     return a;
 }
qScriptValueFromValue()
template<typename T > QScriptValue qScriptValueFromValue (QScriptEngine * engine, const T & t) related
Definition at line 327 of file qscriptengine.h.
Referenced by QScriptEngine::toScriptValue(), and QScriptDebuggerBackend::traceFunction().
 {
     return qScriptValueFromValue_helper(engine, qMetaTypeId<T>(), &t);
 }
qScriptValueFromValue< QVariant >()
template<> QScriptValue qScriptValueFromValue< QVariant > (QScriptEngine * engine, const QVariant & v) inline
Definition at line 333 of file qscriptengine.h.
 {
     return qScriptValueFromValue_helper(engine, v.userType(), v.data());
 }
qScriptValueFromValue_helper()
QScriptValue qScriptValueFromValue_helper (QScriptEngine * engine, int type, const void * ptr) inline
Definition at line 318 of file qscriptengine.h.
Referenced by QScriptEngine::fromScriptValue(), qScriptValueFromValue(), and qScriptValueFromValue< QVariant >().
 {
     if (!engine)
         return QScriptValue();
     return engine->create(type, ptr);
 }
qScriptValueToSequence()
template<class Container > void qScriptValueToSequence (const QScriptValue & value, Container & cont) related
Definition at line 414 of file qscriptengine.h.
Referenced by QScriptDebuggerScriptedConsoleCommand::parse(), and qScriptRegisterSequenceMetaType().
 {
     quint32 len = value.property(QLatin1String("length")).toUInt32();
     for (quint32 i = 0; i < len; ++i) {
         QScriptValue item = value.property(i);
         cont.push_back(qscriptvalue_cast<typename Container::value_type>(item));
     }
 }
qScriptValueToValue()
template<typename T > QT_DEPRECATED T qScriptValueToValue (const QScriptValue & value) related
Definition at line 365 of file qscriptengine.h.
 {
     return qscriptvalue_cast<T>(value);
 }