Qt 4.8: /src/scripttools/debugging/qscriptdebuggerconsole.cpp File Reference
qscriptdebuggerconsole.cpp File Reference
#include "qscriptdebuggerconsole_p.h"
#include "qscriptdebuggerconsolecommandjob_p.h"
#include "qscriptdebuggerconsolecommandmanager_p.h"
#include "qscriptdebuggerscriptedconsolecommand_p.h"
#include "qscriptmessagehandlerinterface_p.h"
#include "qscriptbreakpointdata_p.h"
#include "qscriptdebuggerresponse_p.h"
#include "qscriptdebuggervalueproperty_p.h"
#include "qscriptscriptdata_p.h"
#include <QtCore/qdir.h>
#include <QtCore/qfileinfo.h>
#include <QtCore/qstring.h>
#include <QtCore/qstringlist.h>
#include <QtCore/qdebug.h>
#include <QtScript/qscriptcontextinfo.h>
#include <QtScript/qscriptengine.h>
Classes
class QScriptDebuggerConsolePrivate
Functions
static void breakpointDataFromScriptValue (const QScriptValue &in, QScriptBreakpointData &out)
static QScriptValue breakpointDataToScriptValue (QScriptEngine *eng, const QScriptBreakpointData &in)
static void breakpointMapFromScriptValue (const QScriptValue &, QScriptBreakpointMap &)
static QScriptValue breakpointMapToScriptValue (QScriptEngine *eng, const QScriptBreakpointMap &in)
static void consoleCommandFromScriptValue (const QScriptValue &, QScriptDebuggerConsoleCommand *&)
static void consoleCommandGroupDataFromScriptValue (const QScriptValue &, QScriptDebuggerConsoleCommandGroupData &)
static QScriptValue consoleCommandGroupDataToScriptValue (QScriptEngine *eng, const QScriptDebuggerConsoleCommandGroupData &in)
static void consoleCommandGroupMapFromScriptValue (const QScriptValue &, QScriptDebuggerConsoleCommandGroupMap &)
static QScriptValue consoleCommandGroupMapToScriptValue (QScriptEngine *eng, const QScriptDebuggerConsoleCommandGroupMap &in)
static QScriptValue consoleCommandToScriptValue (QScriptEngine *eng, QScriptDebuggerConsoleCommand *const &in)
static void contextInfoFromScriptValue (const QScriptValue &, QScriptContextInfo &)
static QScriptValue contextInfoToScriptValue (QScriptEngine *eng, const QScriptContextInfo &in)
static void debuggerResponseFromScriptValue (const QScriptValue &, QScriptDebuggerResponse &)
static QScriptValue debuggerResponseToScriptValue (QScriptEngine *eng, const QScriptDebuggerResponse &in)
static void debuggerScriptValuePropertyFromScriptValue (const QScriptValue &in, QScriptDebuggerValueProperty &out)
static QScriptValue debuggerScriptValuePropertyToScriptValue (QScriptEngine *eng, const QScriptDebuggerValueProperty &in)
static void scriptDataFromScriptValue (const QScriptValue &in, QScriptScriptData &out)
static QScriptValue scriptDataToScriptValue (QScriptEngine *eng, const QScriptScriptData &in)
static void scriptMapFromScriptValue (const QScriptValue &, QScriptScriptMap &)
static QScriptValue scriptMapToScriptValue (QScriptEngine *eng, const QScriptScriptMap &in)
Function Documentation
breakpointDataFromScriptValue()
static void breakpointDataFromScriptValue (const QScriptValue & in, QScriptBreakpointData & out) static
Definition at line 103 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     QScriptValue scriptId = in.property(QString::fromLatin1("scriptId"));
     if (scriptId.isValid())
         out.setScriptId((qint64)scriptId.toNumber());
     out.setFileName(in.property(QString::fromLatin1("fileName")).toString());
     out.setLineNumber(in.property(QString::fromLatin1("lineNumber")).toInt32());
     QScriptValue enabled = in.property(QString::fromLatin1("enabled"));
     if (enabled.isValid())
         out.setEnabled(enabled.toBoolean());
     QScriptValue singleShot = in.property(QString::fromLatin1("singleShot"));
     if (singleShot.isValid())
         out.setSingleShot(singleShot.toBoolean());
     out.setIgnoreCount(in.property(QString::fromLatin1("ignoreCount")).toInt32());
     out.setCondition(in.property(QString::fromLatin1("condition")).toString());
 }
breakpointDataToScriptValue()
static QScriptValue breakpointDataToScriptValue (QScriptEngine * eng, const QScriptBreakpointData & in) static
Definition at line 90 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     QScriptValue out = eng->newObject();
     out.setProperty(QString::fromLatin1("scriptId"), QScriptValue(eng, qsreal(in.scriptId())));
     out.setProperty(QString::fromLatin1("fileName"), QScriptValue(eng, in.fileName()));
     out.setProperty(QString::fromLatin1("lineNumber"), QScriptValue(eng, in.lineNumber()));
     out.setProperty(QString::fromLatin1("enabled"), QScriptValue(eng, in.isEnabled()));
     out.setProperty(QString::fromLatin1("singleShot"), QScriptValue(eng, in.isSingleShot()));
     out.setProperty(QString::fromLatin1("ignoreCount"), QScriptValue(eng, in.ignoreCount()));
     out.setProperty(QString::fromLatin1("condition"), QScriptValue(eng, in.condition()));
     return out;
 }
breakpointMapFromScriptValue()
static void breakpointMapFromScriptValue (const QScriptValue & , QScriptBreakpointMap &) static
Definition at line 130 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     Q_ASSERT(0);
 }
breakpointMapToScriptValue()
static QScriptValue breakpointMapToScriptValue (QScriptEngine * eng, const QScriptBreakpointMap & in) static
Definition at line 120 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     QScriptValue out = eng->newObject();
     QScriptBreakpointMap::const_iterator it;
     for (it = in.constBegin(); it != in.constEnd(); ++it) {
         out.setProperty(QString::number(it.key()), eng->toScriptValue(it.value()));
     }
     return out;
 }
consoleCommandFromScriptValue()
static void consoleCommandFromScriptValue (const QScriptValue & , QScriptDebuggerConsoleCommand *&) static
Definition at line 183 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     Q_ASSERT(0);
 }
consoleCommandGroupDataFromScriptValue()
static void consoleCommandGroupDataFromScriptValue (const QScriptValue & , QScriptDebuggerConsoleCommandGroupData &) static
Definition at line 198 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     Q_ASSERT(0);
 }
consoleCommandGroupDataToScriptValue()
static QScriptValue consoleCommandGroupDataToScriptValue (QScriptEngine * eng, const QScriptDebuggerConsoleCommandGroupData & in) static
Definition at line 189 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     QScriptValue out = eng->newObject();
     out.setProperty(QString::fromLatin1("longDescription"), QScriptValue(eng, in.longDescription()));
     out.setProperty(QString::fromLatin1("shortDescription"), QScriptValue(eng, in.shortDescription()));
     return out;
 }
consoleCommandGroupMapFromScriptValue()
static void consoleCommandGroupMapFromScriptValue (const QScriptValue & , QScriptDebuggerConsoleCommandGroupMap &) static
Definition at line 215 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     Q_ASSERT(0);
 }
consoleCommandGroupMapToScriptValue()
static QScriptValue consoleCommandGroupMapToScriptValue (QScriptEngine * eng, const QScriptDebuggerConsoleCommandGroupMap & in) static
Definition at line 204 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     QScriptValue out = eng->newObject();
     QScriptDebuggerConsoleCommandGroupMap::const_iterator it;
     for (it = in.constBegin(); it != in.constEnd(); ++it) {
         out.setProperty(it.key(), eng->toScriptValue(it.value()));
     }
     return out;
 }
consoleCommandToScriptValue()
static QScriptValue consoleCommandToScriptValue (QScriptEngine * eng, QScriptDebuggerConsoleCommand *const & in) static
Definition at line 168 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     if (!in)
         return eng->undefinedValue();
     QScriptValue out = eng->newObject();
     out.setProperty(QString::fromLatin1("name"), QScriptValue(eng, in->name()));
     out.setProperty(QString::fromLatin1("group"), QScriptValue(eng, in->group()));
     out.setProperty(QString::fromLatin1("shortDescription"), QScriptValue(eng, in->shortDescription()));
     out.setProperty(QString::fromLatin1("longDescription"), QScriptValue(eng, in->longDescription()));
     out.setProperty(QString::fromLatin1("aliases"), eng->toScriptValue(in->aliases()));
     out.setProperty(QString::fromLatin1("seeAlso"), eng->toScriptValue(in->seeAlso()));
     return out;
 }
contextInfoFromScriptValue()
static void contextInfoFromScriptValue (const QScriptValue & , QScriptContextInfo &) static
Definition at line 232 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     Q_ASSERT(0);
 }
contextInfoToScriptValue()
static QScriptValue contextInfoToScriptValue (QScriptEngine * eng, const QScriptContextInfo & in) static
Definition at line 221 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     QScriptValue out = eng->newObject();
     out.setProperty(QString::fromLatin1("scriptId"), QScriptValue(eng, qsreal(in.scriptId())));
     out.setProperty(QString::fromLatin1("fileName"), QScriptValue(eng, in.fileName()));
     out.setProperty(QString::fromLatin1("lineNumber"), QScriptValue(eng, in.lineNumber()));
     out.setProperty(QString::fromLatin1("columnNumber"), QScriptValue(eng, in.columnNumber()));
     out.setProperty(QString::fromLatin1("functionName"), QScriptValue(eng, in.functionName()));
     return out;
 }
debuggerResponseFromScriptValue()
static void debuggerResponseFromScriptValue (const QScriptValue & , QScriptDebuggerResponse &) static
Definition at line 85 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     Q_ASSERT(0);
 }
debuggerResponseToScriptValue()
static QScriptValue debuggerResponseToScriptValue (QScriptEngine * eng, const QScriptDebuggerResponse & in) static
Definition at line 76 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     QScriptValue out = eng->newObject();
     out.setProperty(QString::fromLatin1("result"), eng->toScriptValue(in.result()));
     out.setProperty(QString::fromLatin1("error"), QScriptValue(eng, in.error()));
     out.setProperty(QString::fromLatin1("async"), QScriptValue(eng, in.async()));
     return out;
 }
debuggerScriptValuePropertyFromScriptValue()
static void debuggerScriptValuePropertyFromScriptValue (const QScriptValue & in, QScriptDebuggerValueProperty & out) static
Definition at line 247 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     QString name = in.property(QString::fromLatin1("name")).toString();
     QScriptDebuggerValue value = qscriptvalue_cast<QScriptDebuggerValue>(in.property(QString::fromLatin1("value")));
     QString valueAsString = in.property(QString::fromLatin1("valueAsString")).toString();
     int flags = in.property(QString::fromLatin1("flags")).toInt32();
     QScriptDebuggerValueProperty tmp(name, value, valueAsString, QScriptValue::PropertyFlags(flags));
     out = tmp;
 }
debuggerScriptValuePropertyToScriptValue()
static QScriptValue debuggerScriptValuePropertyToScriptValue (QScriptEngine * eng, const QScriptDebuggerValueProperty & in) static
Definition at line 237 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     QScriptValue out = eng->newObject();
     out.setProperty(QString::fromLatin1("name"), QScriptValue(eng, in.name()));
     out.setProperty(QString::fromLatin1("value"), eng->toScriptValue(in.value()));
     out.setProperty(QString::fromLatin1("valueAsString"), QScriptValue(eng, in.valueAsString()));
     out.setProperty(QString::fromLatin1("flags"), QScriptValue(eng, static_cast<int>(in.flags())));
     return out;
 }
scriptDataFromScriptValue()
static void scriptDataFromScriptValue (const QScriptValue & in, QScriptScriptData & out) static
Definition at line 144 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     QString contents = in.property(QString::fromLatin1("contents")).toString();
     QString fileName = in.property(QString::fromLatin1("fileName")).toString();
     int baseLineNumber = in.property(QString::fromLatin1("baseLineNumber")).toInt32();
     QScriptScriptData tmp(contents, fileName, baseLineNumber);
     out = tmp;
 }
scriptDataToScriptValue()
static QScriptValue scriptDataToScriptValue (QScriptEngine * eng, const QScriptScriptData & in) static
Definition at line 135 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     QScriptValue out = eng->newObject();
     out.setProperty(QString::fromLatin1("contents"), QScriptValue(eng, in.contents()));
     out.setProperty(QString::fromLatin1("fileName"), QScriptValue(eng, in.fileName()));
     out.setProperty(QString::fromLatin1("baseLineNumber"), QScriptValue(eng, in.baseLineNumber()));
     return out;
 }
scriptMapFromScriptValue()
static void scriptMapFromScriptValue (const QScriptValue & , QScriptScriptMap &) static
Definition at line 163 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     Q_ASSERT(0);
 }
scriptMapToScriptValue()
static QScriptValue scriptMapToScriptValue (QScriptEngine * eng, const QScriptScriptMap & in) static
Definition at line 153 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerConsolePrivate::QScriptDebuggerConsolePrivate().
 {
     QScriptValue out = eng->newObject();
     QScriptScriptMap::const_iterator it;
     for (it = in.constBegin(); it != in.constEnd(); ++it) {
         out.setProperty(QString::number(it.key()), eng->toScriptValue(it.value()));
     }
     return out;
 }