Qt 4.8: /src/script/bridge/qscriptdeclarativeclass.cpp File Reference
qscriptdeclarativeclass.cpp File Reference
#include "qscriptdeclarativeclass_p.h"
#include "qscriptdeclarativeobject_p.h"
#include "qscriptobject_p.h"
#include "qscriptstaticscopeobject_p.h"
#include <QtScript/qscriptstring.h>
#include <QtScript/qscriptengine.h>
#include <QtScript/qscriptengineagent.h>
#include <private/qscriptengine_p.h>
#include <private/qscriptvalue_p.h>
#include <private/qscriptqobject_p.h>
#include <private/qscriptactivationobject_p.h>
#include <QtCore/qstringlist.h>
Functions
static QScriptDeclarativeClass::Value jscToValue (const JSC::JSValue &val)
Function Documentation
jscToValue()
static QScriptDeclarativeClass::Value jscToValue (const JSC::JSValue & val) static
Definition at line 62 of file qscriptdeclarativeclass.cpp.
Referenced by QScriptDeclarativeClass::functionValue(), QScriptDeclarativeClass::newObjectValue(), and QScriptDeclarativeClass::propertyValue().
 {
     return QScriptDeclarativeClass::Value((QScriptDeclarativeClass::Value &)val);
 }