Qt 4.8: /src/gui/embedded/qscreenqnx_qws.cpp File Reference
qscreenqnx_qws.cpp File Reference
#include "qscreenqnx_qws.h"
#include <qapplication.h>
#include <qregexp.h>
#include <gf/gf.h>
Classes
struct QQnxScreenContext
Functions
static bool attachDevice (QQnxScreenContext *const d, const char *name)
Attaches to the named device name.
static bool attachDisplay (QQnxScreenContext *const d, int displayIndex)
Attaches to the display at index displayIndex.
static bool attachLayer (QQnxScreenContext *const d, int layerIndex)
Attaches to the layer layerIndex.
static bool createHwSurface (QQnxScreenContext *const d, int w, int h)
static bool createMemSurface (QQnxScreenContext *const d, int w, int h)
Function Documentation
attachDevice()
static bool attachDevice (QQnxScreenContext *const d, const char * name) inline static
Attaches to the named device name.
Warning
This function is not part of the public interface.
Definition at line 177 of file qscreenqnx_qws.cpp.
Referenced by QQnxScreen::connect().
 {
     int ret = gf_dev_attach(&d->device, name, &d->deviceInfo);
     if (ret != GF_ERR_OK) {
         qWarning("QQnxScreen: gf_dev_attach(%s) failed with error code %d", name, ret);
         return false;
     }
     return true;
 }
attachDisplay()
static bool attachDisplay (QQnxScreenContext *const d, int displayIndex) inline static
Attaches to the display at index displayIndex.
Warning
This function is not part of the public interface.
Definition at line 194 of file qscreenqnx_qws.cpp.
Referenced by QQnxScreen::connect().
 {
     int ret = gf_display_attach(&d->display, d->device, displayIndex, &d->displayInfo);
     if (ret != GF_ERR_OK) {
         qWarning("QQnxScreen: gf_display_attach(%d) failed with error code %d", displayIndex, ret);
         return false;
     }
     return true;
 }
attachLayer()
static bool attachLayer (QQnxScreenContext *const d, int layerIndex) inline static
Attaches to the layer layerIndex.
Warning
This function is not part of the public interface.
Definition at line 211 of file qscreenqnx_qws.cpp.
Referenced by QQnxScreen::connect().
 {
     unsigned flags = QApplication::type() != QApplication::GuiServer ? GF_LAYER_ATTACH_PASSIVE : 0;
     int ret = gf_layer_attach(&d->layer, d->display, layerIndex, flags);
     if (ret != GF_ERR_OK) {
         qWarning("QQnxScreen: gf_layer_attach(%d) failed with error code %d", layerIndex, ret);
         return false;
     }
     return true;
 }
createHwSurface()
static bool createHwSurface (QQnxScreenContext *const d, int w, int h) inline static
Warning
This function is not part of the public interface. Creates a new hardware surface (usually on the Gfx card memory) with the dimensions w * h.
Definition at line 227 of file qscreenqnx_qws.cpp.
Referenced by QQnxScreen::connect().
 {
     int ret = gf_surface_create_layer(&d->hwSurface, &d->layer, 1, 0,
                                       w, h, d->displayInfo.format, 0, 0);
     if (ret != GF_ERR_OK) {
         qWarning("QQnxScreen: gf_surface_create_layer(%dx%d) failed with error code %d", w, h, ret);
         return false;
     }
     gf_layer_set_surfaces(d->layer, &d->hwSurface, 1);
     gf_layer_enable(d->layer);
     ret = gf_layer_update(d->layer, 0);
     if (ret != GF_ERR_OK) {
         qWarning("QQnxScreen: gf_layer_update() failed with error code %d\n", ret);
         return false;
     }
     ret = gf_context_create(&d->context);
     if (ret != GF_ERR_OK) {
         qWarning("QQnxScreen: gf_context_create() failed with error code %d", ret);
         return false;
     }
     ret = gf_context_set_surface(d->context, d->hwSurface);
     if (ret != GF_ERR_OK) {
         qWarning("QQnxScreen: gf_context_set_surface() failed with error code %d", ret);
         return false;
     }
     return true;
 }
createMemSurface()
static bool createMemSurface (QQnxScreenContext *const d, int w, int h) inline static
Warning
This function is not part of the public interface. Creates an in-memory, linear accessible surface of dimensions w * h. This is the main surface that QWS blits to.
Definition at line 266 of file qscreenqnx_qws.cpp.
Referenced by QQnxScreen::connect().
 {
 #ifndef QT_NO_QWS_MULTIPROCESS
     if (QApplication::type() != QApplication::GuiServer) {
         unsigned sidlist[64];
         int n = gf_surface_sidlist(d->device, sidlist); // undocumented API
         for (int i = 0; i < n; ++i) {
             int ret = gf_surface_attach_by_sid(&d->memSurface, d->device, sidlist[i]);
             if (ret == GF_ERR_OK) {
                 gf_surface_get_info(d->memSurface, &d->memSurfaceInfo);
                 if (d->memSurfaceInfo.sid != unsigned(GF_SID_INVALID)) {
                     // can we use the surface's vaddr?
                     unsigned flags = GF_SURFACE_CPU_LINEAR_READABLE | GF_SURFACE_CPU_LINEAR_WRITEABLE;
                     if ((d->memSurfaceInfo.flags & flags) == flags)
                         return true;
                 }
                 gf_surface_free(d->memSurface);
                 d->memSurface = 0;
             }
         }
         qWarning("QQnxScreen: cannot attach to an usable surface; create a new one.");
     }
 #endif
     int ret = gf_surface_create(&d->memSurface, d->device, w, h, d->displayInfo.format, 0,
                 GF_SURFACE_CREATE_CPU_FAST_ACCESS | GF_SURFACE_CREATE_CPU_LINEAR_ACCESSIBLE
                 | GF_SURFACE_CREATE_PHYS_CONTIG | GF_SURFACE_CREATE_SHAREABLE);
     if (ret != GF_ERR_OK) {
         qWarning("QQnxScreen: gf_surface_create(%dx%d) failed with error code %d",
                  w, h, ret);
         return false;
     }
     gf_surface_get_info(d->memSurface, &d->memSurfaceInfo);
     if (d->memSurfaceInfo.sid == unsigned(GF_SID_INVALID)) {
         qWarning("QQnxScreen: gf_surface_get_info() failed.");
         return false;
     }
     return true;
 }