Qt 4.8: /src/gui/embedded/qscreentransformed_qws.cpp File Reference
qscreentransformed_qws.cpp File Reference
#include "qscreentransformed_qws.h"
#include <qscreendriverfactory_qws.h>
#include <qvector.h>
#include <private/qpainter_p.h>
#include <private/qmemrotate_p.h>
#include <qmatrix.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <errno.h>
#include <qwindowsystem_qws.h>
#include <qwsdisplay_qws.h>
Classes
class QTransformedScreenPrivate
Macros
#define SET_BLIT_FUNC(dst, src, rotation, func)
Typedefs
typedef void(* BlitFunc) (QScreen *, const QImage &, const QRect &, const QPoint &)
Functions
template<class DST , class SRC >
static void blit180 (QScreen *screen, const QImage &image, const QRect &rect, const QPoint &topLeft)
template<class DST , class SRC >
static void blit270 (QScreen *screen, const QImage &image, const QRect &rect, const QPoint &topLeft)
template<class DST , class SRC >
static void blit90 (QScreen *screen, const QImage &image, const QRect &rect, const QPoint &topLeft)
static QRect correctNormalized (const QRect &r)
static QTransformedScreen::Transformation filterTransformation (QString &spec)
static int getDisplayId (const QString &spec)
Q_DECL_EXPORT void qws_setScreenTransformation (QScreen *that, int t)
Macro Definition Documentation
SET_BLIT_FUNC
#define SET_BLIT_FUNC (dst, src, rotation, func)
Value:
do {                                            \
    switch (rotation) {                         \
    case Rot90:                                 \
        func = blit90<dst, src>;                \
        break;                                  \
    case Rot180:                                \
        func = blit180<dst, src>;               \
        break;                                  \
    case Rot270:                                \
        func = blit270<dst, src>;               \
        break;                                  \
    default:                                    \
        break;                                  \
    }                                           \
} while (0)
Definition at line 348 of file qscreentransformed_qws.cpp.
Referenced by QTransformedScreen::blit().
Typedef Documentation
BlitFunc
typedef void(* BlitFunc) (QScreen *, const QImage &, const QRect &, const QPoint &)
Definition at line 346 of file qscreentransformed_qws.cpp.
Function Documentation
blit180()
template<class DST , class SRC > static void blit180 (QScreen * screen, const QImage & image, const QRect & rect, const QPoint & topLeft) inline static
Definition at line 325 of file qscreentransformed_qws.cpp.
 {
     const SRC *src = (const SRC*)(image.scanLine(rect.top())) + rect.left();
     DST *dest = (DST*)(screen->base() + topLeft.y() * screen->linestep())
                 + topLeft.x();
     qt_memrotate180(src, rect.width(), rect.height(), image.bytesPerLine(),
                     dest, screen->linestep());
 }
blit270()
template<class DST , class SRC > static void blit270 (QScreen * screen, const QImage & image, const QRect & rect, const QPoint & topLeft) inline static
Definition at line 336 of file qscreentransformed_qws.cpp.
 {
     const SRC *src = (const SRC *)(image.scanLine(rect.top())) + rect.left();
     DST *dest = (DST*)(screen->base() + topLeft.y() * screen->linestep())
                 + topLeft.x();
     qt_memrotate270(src, rect.width(), rect.height(), image.bytesPerLine(),
                     dest, screen->linestep());
 }
blit90()
template<class DST , class SRC > static void blit90 (QScreen * screen, const QImage & image, const QRect & rect, const QPoint & topLeft) inline static
Definition at line 314 of file qscreentransformed_qws.cpp.
 {
     const SRC *src = (const SRC*)(image.scanLine(rect.top())) + rect.left();
     DST *dest = (DST*)(screen->base() + topLeft.y() * screen->linestep())
                 + topLeft.x();
     qt_memrotate90(src, rect.width(), rect.height(), image.bytesPerLine(),
                    dest, screen->linestep());
 }
correctNormalized()
static QRect correctNormalized (const QRect & r) inline static
Definition at line 304 of file qscreentransformed_qws.cpp.
Referenced by QTransformedScreen::mapFromDevice(), and QTransformedScreen::mapToDevice().
{
     const int x1 = qMin(r.left(), r.right());
     const int x2 = qMax(r.left(), r.right());
     const int y1 = qMin(r.top(), r.bottom());
     const int y2 = qMax(r.top(), r.bottom());
     return QRect( QPoint(x1,y1), QPoint(x2,y2) );
 }
filterTransformation()
static QTransformedScreen::Transformation filterTransformation (QString & spec) static
Definition at line 196 of file qscreentransformed_qws.cpp.
Referenced by QTransformedScreen::connect().
 {
     QRegExp regexp(QLatin1String("\\bRot(\\d+):?\\b"), Qt::CaseInsensitive);
     if (regexp.indexIn(spec) == -1)
         return QTransformedScreen::None;
     const int degrees = regexp.cap(1).toInt();
     spec.remove(regexp.pos(0), regexp.matchedLength());
     return static_cast<QTransformedScreen::Transformation>(degrees / 90);
 }
getDisplayId()
static int getDisplayId (const QString & spec) static
Definition at line 186 of file qscreentransformed_qws.cpp.
Referenced by QTransformedScreen::connect().
 {
     QRegExp regexp(QLatin1String(":(\\d+)\\b"));
     if (regexp.lastIndexIn(spec) != -1) {
         const QString capture = regexp.cap(1);
         return capture.toInt();
     }
     return 0;
 }
qws_setScreenTransformation()
Q_DECL_EXPORT void qws_setScreenTransformation (QScreen * that, int t)
Definition at line 97 of file qscreentransformed_qws.cpp.
Referenced by getTransformationFunction().
 {
     QTransformedScreen *tscreen = static_cast<QTransformedScreen*>(that);
     tscreen->setTransformation((QTransformedScreen::Transformation)t);
 }