Qt 4.8: /src/scripttools/debugging/qscriptdebuggercommandexecutor.cpp File Reference
qscriptdebuggercommandexecutor.cpp File Reference
#include "qscriptdebuggercommandexecutor_p.h"
#include "qscriptdebuggerbackend_p.h"
#include "qscriptdebuggercommand_p.h"
#include "qscriptdebuggerresponse_p.h"
#include "qscriptdebuggervalue_p.h"
#include "qscriptdebuggervalueproperty_p.h"
#include "qscriptbreakpointdata_p.h"
#include "qscriptobjectsnapshot_p.h"
#include "qscriptdebuggerobjectsnapshotdelta_p.h"
#include <QtCore/qstringlist.h>
#include <QtScript/qscriptengine.h>
#include <QtScript/qscriptcontextinfo.h>
#include <QtScript/qscriptvalueiterator.h>
#include <QtCore/qdebug.h>
Classes
class QScriptDebuggerCommandExecutorPrivate
Functions
static bool isPrefixOf (const QString &prefix, const QString &what)
Function Documentation
isPrefixOf()
static bool isPrefixOf (const QString & prefix, const QString & what) static
Definition at line 106 of file qscriptdebuggercommandexecutor.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute(), QScriptCompleteScriptsJob::handleResponse(), and QScriptCompletionTask::start().
 {
     return ((what.length() > prefix.length())
             && what.startsWith(prefix));
 }