Qt 4.8: /src/corelib/io/qsettings.cpp File Reference
qsettings.cpp File Reference
#include <qdebug.h>
#include "qplatformdefs.h"
#include "qsettings.h"
#include "qsettings_p.h"
#include "qcache.h"
#include "qfile.h"
#include "qdir.h"
#include "qfileinfo.h"
#include "qmutex.h"
#include "qlibraryinfo.h"
#include "qtemporaryfile.h"
#include "qtextcodec.h"
#include "qsize.h"
#include "qpoint.h"
#include "qrect.h"
#include "qcoreapplication.h"
#include "qt_windows.h"
#include <private/qsystemlibrary_p.h>
#include <stdlib.h>
Classes
struct QConfFileCustomFormat
class QSettingsIniKey
struct QSettingsIniSection
Macros
#define CSIDL_APPDATA 0x001a
#define CSIDL_COMMON_APPDATA 0x0023
#define FLUSH_CURRENT_SECTION()
#define Q_AUTOTEST_EXPORT_HELPER Q_AUTOTEST_EXPORT
Typedefs
typedef QCache< QString, QConfFile > ConfFileCache
typedef QHash< QString, QConfFile * > ConfFileHash
typedef QVector< QConfFileCustomFormat > CustomFormatVector
typedef QMap< QSettingsIniKey, QVariant > IniKeyMap
typedef QMap< QString, QSettingsIniSection > IniMap
typedef QHash< int, QString > PathHash
Enumerations
enum { Space = 0x1, Special = 0x2 }
Functions
static QString getPath (QSettings::Format format, QSettings::Scope scope)
static void iniChopTrailingSpaces (QString &str)
static void initDefaultPaths (QMutexLocker *locker)
static bool operator< (const QSettingsIniKey &k1, const QSettingsIniKey &k2)
static int pathHashKey (QSettings::Format format, QSettings::Scope scope)
static QString windowsConfigPath (int type)
Variables
static const char charTraits [256]
static QSettings::Format globalDefaultFormat = QSettings::NativeFormat
static const char hexDigits [] = "0123456789ABCDEF"
Macro Definition Documentation
CSIDL_APPDATA
#define CSIDL_APPDATA 0x001a
Definition at line 87 of file qsettings.cpp.
Referenced by initDefaultPaths(), launchWebBrowser(), and windowsConfigPath().
CSIDL_COMMON_APPDATA
#define CSIDL_COMMON_APPDATA 0x0023
Definition at line 83 of file qsettings.cpp.
Referenced by initDefaultPaths(), and windowsConfigPath().
FLUSH_CURRENT_SECTION
#define FLUSH_CURRENT_SECTION ()
Value:
{ \
        QByteArray &sectionData = (*unparsedIniSections)[QSettingsKey(currentSection, \
                                                                      IniCaseSensitivity, \
                                                                      sectionPosition)]; \
        if (!sectionData.isEmpty()) \
            sectionData.append('\n'); \
        sectionData += data.mid(currentSectionStart, lineStart - currentSectionStart); \
        sectionPosition = ++position; \
    }
Referenced by QConfFileSettingsPrivate::readIniFile().
Q_AUTOTEST_EXPORT_HELPER
#define Q_AUTOTEST_EXPORT_HELPER Q_AUTOTEST_EXPORT
Definition at line 91 of file qsettings.cpp.
Typedef Documentation
ConfFileCache
typedef QCache<QString, QConfFile> ConfFileCache
Definition at line 117 of file qsettings.cpp.
ConfFileHash
typedef QHash<QString, QConfFile *> ConfFileHash
Definition at line 116 of file qsettings.cpp.
CustomFormatVector
typedef QVector<QConfFileCustomFormat> CustomFormatVector
Definition at line 119 of file qsettings.cpp.
IniKeyMap
typedef QMap<QSettingsIniKey, QVariant> IniKeyMap
Definition at line 1865 of file qsettings.cpp.
IniMap
typedef QMap<QString, QSettingsIniSection> IniMap
Definition at line 1875 of file qsettings.cpp.
PathHash
typedef QHash<int, QString> PathHash
Definition at line 118 of file qsettings.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
Space
Special
Definition at line 1633 of file qsettings.cpp.
 { Space = 0x1, Special = 0x2 };
Function Documentation
getPath()
static QString getPath (QSettings::Format format, QSettings::Scope scope) static
Definition at line 1132 of file qsettings.cpp.
Referenced by QConfFileSettingsPrivate::QConfFileSettingsPrivate().
 {
     Q_ASSERT((int)QSettings::NativeFormat == 0);
     Q_ASSERT((int)QSettings::IniFormat == 1);
     QMutexLocker locker(globalMutex());
     PathHash *pathHash = pathHashFunc();
     if (pathHash->isEmpty())
         initDefaultPaths(&locker);
     QString result = pathHash->value(pathHashKey(format, scope));
     if (!result.isEmpty())
         return result;
     // fall back on INI path
     return pathHash->value(pathHashKey(QSettings::IniFormat, scope));
 }
iniChopTrailingSpaces()
static void iniChopTrailingSpaces (QString & str) inline static
Definition at line 758 of file qsettings.cpp.
Referenced by QSettingsPrivate::iniUnescapedStringList().
 {
     int n = str.size() - 1;
     QChar ch;
     while (n >= 0 && ((ch = str.at(n)) == QLatin1Char(' ') || ch == QLatin1Char('\t')))
         str.truncate(n--);
 }
initDefaultPaths()
static void initDefaultPaths (QMutexLocker * locker) static
Definition at line 1073 of file qsettings.cpp.
Referenced by getPath(), and QSettings::setPath().
 {
     PathHash *pathHash = pathHashFunc();
     QString homePath = QDir::homePath();
     QString systemPath;
     locker->unlock();
     /*
        QLibraryInfo::location() uses QSettings, so in order to
        avoid a dead-lock, we can't hold the global mutex while
        calling it.
     */
     systemPath = QLibraryInfo::location(QLibraryInfo::SettingsPath);
     systemPath += QLatin1Char('/');
     locker->relock();
     if (pathHash->isEmpty()) {
         /*
            Lazy initialization of pathHash. We initialize the
            IniFormat paths and (on Unix) the NativeFormat paths.
            (The NativeFormat paths are not configurable for the
            Windows registry and the Mac CFPreferences.)
        */
 #ifdef Q_OS_WIN
         pathHash->insert(pathHashKey(QSettings::IniFormat, QSettings::UserScope),
                          windowsConfigPath(CSIDL_APPDATA) + QDir::separator());
         pathHash->insert(pathHashKey(QSettings::IniFormat, QSettings::SystemScope),
                          windowsConfigPath(CSIDL_COMMON_APPDATA) + QDir::separator());
 #else
         QString userPath;
         char *env = getenv("XDG_CONFIG_HOME");
         if (env == 0) {
             userPath = homePath;
             userPath += QLatin1Char('/');
 #if defined(Q_WS_QWS) || defined(Q_WS_QPA)
             userPath += QLatin1String("Settings");
 #else
             userPath += QLatin1String(".config");
 #endif
         } else if (*env == '/') {
             userPath = QFile::decodeName(env);
         } else {
             userPath = homePath;
             userPath += QLatin1Char('/');
             userPath += QFile::decodeName(env);
         }
         userPath += QLatin1Char('/');
         pathHash->insert(pathHashKey(QSettings::IniFormat, QSettings::UserScope), userPath);
         pathHash->insert(pathHashKey(QSettings::IniFormat, QSettings::SystemScope), systemPath);
 #ifndef Q_OS_MAC
         pathHash->insert(pathHashKey(QSettings::NativeFormat, QSettings::UserScope), userPath);
         pathHash->insert(pathHashKey(QSettings::NativeFormat, QSettings::SystemScope), systemPath);
 #endif
 #endif
     }
 }
operator<()
static bool operator< (const QSettingsIniKey & k1, const QSettingsIniKey & k2) static
Definition at line 1858 of file qsettings.cpp.
 {
     if (k1.position != k2.position)
         return k1.position < k2.position;
     return static_cast<const QString &>(k1) < static_cast<const QString &>(k2);
 }
pathHashKey()
static int pathHashKey (QSettings::Format format, QSettings::Scope scope) inline static
Definition at line 1068 of file qsettings.cpp.
Referenced by getPath(), initDefaultPaths(), and QSettings::setPath().
 {
     return int((uint(format) << 1) | uint(scope == QSettings::SystemScope));
 }
windowsConfigPath()
static QString windowsConfigPath (int type) static
Definition at line 1025 of file qsettings.cpp.
Referenced by initDefaultPaths().
 {
     QString result;
 #ifndef Q_OS_WINCE
     QSystemLibrary library(QLatin1String("shell32"));
 #else
     QSystemLibrary library(QLatin1String("coredll"));
 #endif // Q_OS_WINCE
     typedef BOOL (WINAPI*GetSpecialFolderPath)(HWND, LPWSTR, int, BOOL);
     GetSpecialFolderPath SHGetSpecialFolderPath = (GetSpecialFolderPath)library.resolve("SHGetSpecialFolderPathW");
     if (SHGetSpecialFolderPath) {
         wchar_t path[MAX_PATH];
         SHGetSpecialFolderPath(0, path, type, FALSE);
         result = QString::fromWCharArray(path);
     }
     if (result.isEmpty()) {
         switch (type) {
 #ifndef Q_OS_WINCE
         case CSIDL_COMMON_APPDATA:
             result = QLatin1String("C:\\temp\\qt-common");
             break;
         case CSIDL_APPDATA:
             result = QLatin1String("C:\\temp\\qt-user");
             break;
 #else
         case CSIDL_COMMON_APPDATA:
             result = QLatin1String("\\Temp\\qt-common");
             break;
         case CSIDL_APPDATA:
             result = QLatin1String("\\Temp\\qt-user");
             break;
 #endif
         default:
             ;
         }
     }
     return result;
 }
Variable Documentation
charTraits
const char charTraits[256] static
Initial value:
=
{
    0, 0, 0, 0, 0, 0, 0, 0, 0, Space, Space | Special, 0, 0, Space | Special, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    Space, 0, Special, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, Special, 0, Special, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, Special, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
}
Definition at line 1635 of file qsettings.cpp.
globalDefaultFormat
QSettings::Format globalDefaultFormat = QSettings::NativeFormat static
Definition at line 126 of file qsettings.cpp.
Referenced by QSettings::defaultFormat(), QSettings::QSettings(), and QSettings::setDefaultFormat().
hexDigits
const char hexDigits[] = "0123456789ABCDEF" static
Definition at line 594 of file qsettings.cpp.
Referenced by QSettingsPrivate::iniUnescapedStringList().