Qt 4.8: /src/corelib/io/qsettings_win.cpp File Reference
qsettings_win.cpp File Reference
#include "qsettings.h"
#include "qsettings_p.h"
#include "qvector.h"
#include "qmap.h"
#include "qt_windows.h"
#include "qdebug.h"
Classes
class QWinSettingsPrivate
class RegistryKey
Typedefs
typedef QMap< QString, QString > NameSet
typedef QVector< RegistryKey > RegistryKeyList
Functions
static void allKeys (HKEY parentHandle, const QString &rSubKey, NameSet *result)
static QStringList childKeysOrGroups (HKEY parentHandle, QSettingsPrivate::ChildSpec spec)
static HKEY createOrOpenKey (HKEY parentHandle, REGSAM perms, const QString &rSubKey)
static HKEY createOrOpenKey (HKEY parentHandle, const QString &rSubKey, bool *readOnly)
static void deleteChildGroups (HKEY parentHandle)
static QString errorCodeToString (DWORD errorCode)
static QString escapedKey (QString uKey)
static QString keyName (const QString &rKey)
static QString keyPath (const QString &rKey)
static void mergeKeySets (NameSet *dest, const NameSet &src)
static void mergeKeySets (NameSet *dest, const QStringList &src)
static HKEY openKey (HKEY parentHandle, REGSAM perms, const QString &rSubKey)
static bool stringContainsNullChar (const QString &s)
static QString unescapedKey (QString rKey)
Variables
static const REGSAM registryPermissions = KEY_READ | KEY_WRITE
Typedef Documentation
NameSet
typedef QMap<QString, QString> NameSet
Definition at line 111 of file qsettings_win.cpp.
RegistryKeyList
typedef QVector<RegistryKey> RegistryKeyList
Definition at line 372 of file qsettings_win.cpp.
Function Documentation
allKeys()
static void allKeys (HKEY parentHandle, const QString & rSubKey, NameSet * result) static
Definition at line 258 of file qsettings_win.cpp.
Referenced by QWinSettingsPrivate::children(), QCoreTextFontDatabase::populateFontDatabase(), QShortcutMap::removeShortcut(), QShortcutMap::setShortcutAutoRepeat(), and QShortcutMap::setShortcutEnabled().
 {
     HKEY handle = openKey(parentHandle, KEY_READ, rSubKey);
     if (handle == 0)
         return;
     QStringList childKeys = childKeysOrGroups(handle, QSettingsPrivate::ChildKeys);
     QStringList childGroups = childKeysOrGroups(handle, QSettingsPrivate::ChildGroups);
     RegCloseKey(handle);
     for (int i = 0; i < childKeys.size(); ++i) {
         QString s = rSubKey;
         if (!s.isEmpty())
             s += QLatin1Char('\\');
         s += childKeys.at(i);
         result->insert(s, QString());
     }
     for (int i = 0; i < childGroups.size(); ++i) {
         QString s = rSubKey;
         if (!s.isEmpty())
             s += QLatin1Char('\\');
         s += childGroups.at(i);
         allKeys(parentHandle, s, result);
     }
 }
childKeysOrGroups()
static QStringList childKeysOrGroups (HKEY parentHandle, QSettingsPrivate::ChildSpec spec) static
Definition at line 201 of file qsettings_win.cpp.
Referenced by allKeys(), QWinSettingsPrivate::children(), deleteChildGroups(), and QWinSettingsPrivate::remove().
 {
     QStringList result;
     DWORD numKeys;
     DWORD maxKeySize;
     DWORD numSubgroups;
     DWORD maxSubgroupSize;
     // Find the number of keys and subgroups, as well as the max of their lengths.
     LONG res = RegQueryInfoKey(parentHandle, 0, 0, 0, &numSubgroups, &maxSubgroupSize, 0,
                                &numKeys, &maxKeySize, 0, 0, 0);
     if (res != ERROR_SUCCESS) {
         qWarning("QSettings: RegQueryInfoKey() failed: %s", errorCodeToString(res).toLatin1().data());
         return result;
     }
     ++maxSubgroupSize;
     ++maxKeySize;
     int n;
     int m;
     if (spec == QSettingsPrivate::ChildKeys) {
         n = numKeys;
         m = maxKeySize;
     } else {
         n = numSubgroups;
         m = maxSubgroupSize;
     }
     /* The size does not include the terminating null character. */
     ++m;
     // Get the list
     QByteArray buff(m * sizeof(wchar_t), 0);
     for (int i = 0; i < n; ++i) {
         QString item;
         DWORD l = buff.size() / sizeof(wchar_t);
         if (spec == QSettingsPrivate::ChildKeys) {
             res = RegEnumValue(parentHandle, i, reinterpret_cast<wchar_t *>(buff.data()), &l, 0, 0, 0, 0);
         } else {
             res = RegEnumKeyEx(parentHandle, i, reinterpret_cast<wchar_t *>(buff.data()), &l, 0, 0, 0, 0);
         }
         if (res == ERROR_SUCCESS)
             item = QString::fromWCharArray((const wchar_t *)buff.constData(), l);
         if (res != ERROR_SUCCESS) {
             qWarning("QSettings: RegEnumValue failed: %s", errorCodeToString(res).toLatin1().data());
             continue;
         }
         if (item.isEmpty())
             item = QLatin1String(".");
         result.append(item);
     }
     return result;
 }
createOrOpenKey() [1/2]
static HKEY createOrOpenKey (HKEY parentHandle, REGSAM perms, const QString & rSubKey) static
Definition at line 160 of file qsettings_win.cpp.
Referenced by createOrOpenKey(), RegistryKey::handle(), and QWinSettingsPrivate::set().
 {
     // try to open it
     HKEY resultHandle = openKey(parentHandle, perms, rSubKey);
     if (resultHandle != 0)
         return resultHandle;
     // try to create it
     LONG res = RegCreateKeyEx(parentHandle, reinterpret_cast<const wchar_t *>(rSubKey.utf16()), 0, 0,
                               REG_OPTION_NON_VOLATILE, perms, 0, &resultHandle, 0);
     if (res == ERROR_SUCCESS)
         return resultHandle;
     //qWarning("QSettings: Failed to create subkey \"%s\": %s",
     //        rSubKey.toLatin1().data(), errorCodeToString(res).toLatin1().data());
     return 0;
 }
createOrOpenKey() [2/2]
static HKEY createOrOpenKey (HKEY parentHandle, const QString & rSubKey, bool * readOnly) static
Definition at line 181 of file qsettings_win.cpp.
 {
     // try to open or create it read/write
     HKEY resultHandle = createOrOpenKey(parentHandle, registryPermissions, rSubKey);
     if (resultHandle != 0) {
         if (readOnly != 0)
             *readOnly = false;
         return resultHandle;
     }
     // try to open or create it read/only
     resultHandle = createOrOpenKey(parentHandle, KEY_READ, rSubKey);
     if (resultHandle != 0) {
         if (readOnly != 0)
             *readOnly = true;
         return resultHandle;
     }
     return 0;
 }
deleteChildGroups()
static void deleteChildGroups (HKEY parentHandle) static
Definition at line 285 of file qsettings_win.cpp.
Referenced by QWinSettingsPrivate::remove().
 {
     QStringList childGroups = childKeysOrGroups(parentHandle, QSettingsPrivate::ChildGroups);
     for (int i = 0; i < childGroups.size(); ++i) {
         QString group = childGroups.at(i);
         // delete subgroups in group
         HKEY childGroupHandle = openKey(parentHandle, registryPermissions, group);
         if (childGroupHandle == 0)
             continue;
         deleteChildGroups(childGroupHandle);
         RegCloseKey(childGroupHandle);
         // delete group itself
         LONG res = RegDeleteKey(parentHandle, reinterpret_cast<const wchar_t *>(group.utf16()));
         if (res != ERROR_SUCCESS) {
             qWarning("QSettings: RegDeleteKey failed on subkey \"%s\": %s",
                       group.toLatin1().data(), errorCodeToString(res).toLatin1().data());
             return;
         }
     }
 }
errorCodeToString()
static QString errorCodeToString (DWORD errorCode) static
Definition at line 131 of file qsettings_win.cpp.
Referenced by childKeysOrGroups(), deleteChildGroups(), QWinSettingsPrivate::remove(), QWinSettingsPrivate::set(), and QWinSettingsPrivate::~QWinSettingsPrivate().
 {
     wchar_t *data = 0;
     FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM, 0, errorCode, 0, data, 0, 0);
     QString result = QString::fromWCharArray(data);
     if (data != 0)
         LocalFree(data);
     if (result.endsWith(QLatin1Char('\n')))
         result.truncate(result.length() - 1);
     return result;
 }
escapedKey()
static QString escapedKey (QString uKey) static
Definition at line 92 of file qsettings_win.cpp.
Referenced by QWinSettingsPrivate::children(), QWinSettingsPrivate::get(), QWinSettingsPrivate::remove(), QWinSettingsPrivate::set(), and unescapedKey().
 {
     QChar *data = uKey.data();
     int l = uKey.length();
     for (int i = 0; i < l; ++i) {
         ushort &ucs = data[i].unicode();
         if (ucs == '\\')
             ucs = '/';
         else if (ucs == '/')
             ucs = '\\';
     }
     return uKey;
 }
keyName()
static QString keyName (const QString & rKey) static
Definition at line 76 of file qsettings_win.cpp.
Referenced by QCoreWlanEngine::connectToId(), QKeySequencePrivate::decodeString(), launchWebBrowser(), QWinSettingsPrivate::readKey(), QWinSettingsPrivate::remove(), and QWinSettingsPrivate::set().
 {
     int idx = rKey.lastIndexOf(QLatin1Char('\\'));
     QString res;
     if (idx == -1)
         res = rKey;
     else
         res = rKey.mid(idx + 1);
     if (res == QLatin1String("Default") || res == QLatin1String("."))
         res = QLatin1String("");
     return res;
 }
keyPath()
static QString keyPath (const QString & rKey) static
Definition at line 68 of file qsettings_win.cpp.
Referenced by QWinSettingsPrivate::readKey(), QWinSettingsPrivate::remove(), QWinSettingsPrivate::set(), and UpdateRegistry().
 {
     int idx = rKey.lastIndexOf(QLatin1Char('\\'));
     if (idx == -1)
         return QString();
     return rKey.left(idx + 1);
 }
mergeKeySets() [1/2]
static void mergeKeySets (NameSet * dest, const NameSet & src) static
Definition at line 113 of file qsettings_win.cpp.
Referenced by QWinSettingsPrivate::children().
 {
     NameSet::const_iterator it = src.constBegin();
     for (; it != src.constEnd(); ++it)
         dest->insert(unescapedKey(it.key()), QString());
 }
mergeKeySets() [2/2]
static void mergeKeySets (NameSet * dest, const QStringList & src) static
Definition at line 120 of file qsettings_win.cpp.
 {
     QStringList::const_iterator it = src.constBegin();
     for (; it != src.constEnd(); ++it)
         dest->insert(unescapedKey(*it), QString());
 }
openKey()
static HKEY openKey (HKEY parentHandle, REGSAM perms, const QString & rSubKey) static
Definition at line 147 of file qsettings_win.cpp.
Referenced by allKeys(), QWinSettingsPrivate::children(), createOrOpenKey(), deleteChildGroups(), RegistryKey::handle(), QWinSettingsPrivate::readKey(), and QWinSettingsPrivate::remove().
 {
     HKEY resultHandle = 0;
     LONG res = RegOpenKeyEx(parentHandle, reinterpret_cast<const wchar_t *>(rSubKey.utf16()),
                             0, perms, &resultHandle);
     if (res == ERROR_SUCCESS)
         return resultHandle;
     return 0;
 }
stringContainsNullChar()
static bool stringContainsNullChar (const QString & s) static
Definition at line 637 of file qsettings_win.cpp.
Referenced by QWinSettingsPrivate::set().
 {
     for (int i = 0; i < s.length(); ++i) {
         if (s.at(i).unicode() == 0)
             return true;
     }
     return false;
 }
unescapedKey()
static QString unescapedKey (QString rKey) static
Definition at line 106 of file qsettings_win.cpp.
Referenced by mergeKeySets().
 {
     return escapedKey(rKey);
 }
Variable Documentation
registryPermissions
const REGSAM registryPermissions = KEY_READ | KEY_WRITE static
Definition at line 66 of file qsettings_win.cpp.
Referenced by createOrOpenKey(), deleteChildGroups(), QWinSettingsPrivate::remove(), and QWinSettingsPrivate::set().