Qt 4.8: /src/corelib/io/qsettings_mac.cpp File Reference
qsettings_mac.cpp File Reference
#include "qsettings.h"
#include "qsettings_p.h"
#include "qdatetime.h"
#include "qdir.h"
#include "qvarlengtharray.h"
#include "private/qcore_mac_p.h"
#include "qcoreapplication.h"
Classes
class QMacSettingsPrivate
struct QMacSettingsPrivate::SearchDomain
Enumerations
enum RotateShift { Macify = 1, Qtify = 2 }
Functions
static QString comify (const QString &organization)
static QCFType< CFStringRef > macKey (const QString &key)
static CFArrayRef macList (const QList< QVariant > &list)
static QCFType< CFPropertyListRef > macValue (const QVariant &value)
static QString qtKey (CFStringRef cfkey)
static QVariant qtValue (CFPropertyListRef cfvalue)
static QString rotateSlashesDotsAndMiddots (const QString &key, int shift)
static QCFType< CFURLRef > urlFromFileName (const QString &fileName)
Variables
static const CFStringRef hostNames [2] = { kCFPreferencesCurrentHost, kCFPreferencesAnyHost }
static const int numHostNames = 2
Enumeration Type Documentation
RotateShift
enum RotateShift
Enumerator
Macify
Qtify
Definition at line 69 of file qsettings_mac.cpp.
 { Macify = 1, Qtify = 2 };
Function Documentation
comify()
static QString comify (const QString & organization) static
Definition at line 304 of file qsettings_mac.cpp.
Referenced by QMacSettingsPrivate::QMacSettingsPrivate().
 {
     for (int i = organization.size() - 1; i >= 0; --i) {
         QChar ch = organization.at(i);
         if (ch == QLatin1Char('.') || ch == QChar(0x3002) || ch == QChar(0xff0e)
                 || ch == QChar(0xff61)) {
             QString suffix = organization.mid(i + 1).toLower();
             if (suffix.size() == 2 || suffix == QLatin1String("com")
                     || suffix == QLatin1String("org") || suffix == QLatin1String("net")
                     || suffix == QLatin1String("edu") || suffix == QLatin1String("gov")
                     || suffix == QLatin1String("mil") || suffix == QLatin1String("biz")
                     || suffix == QLatin1String("info") || suffix == QLatin1String("name")
                     || suffix == QLatin1String("pro") || suffix == QLatin1String("aero")
                     || suffix == QLatin1String("coop") || suffix == QLatin1String("museum")) {
                 QString result = organization;
                 result.replace(QLatin1Char('/'), QLatin1Char(' '));
                 return result;
             }
             break;
         }
         int uc = ch.unicode();
         if ((uc < 'a' || uc > 'z') && (uc < 'A' || uc > 'Z'))
             break;
     }
     QString domain;
     for (int i = 0; i < organization.size(); ++i) {
         QChar ch = organization.at(i);
         int uc = ch.unicode();
         if ((uc >= 'a' && uc <= 'z') || (uc >= '0' && uc <= '9')) {
             domain += ch;
         } else if (uc >= 'A' && uc <= 'Z') {
             domain += ch.toLower();
         } else {
            domain += QLatin1Char(' ');
         }
     }
     domain = domain.simplified();
     domain.replace(QLatin1Char(' '), QLatin1Char('-'));
     if (!domain.isEmpty())
         domain.append(QLatin1String(".com"));
     return domain;
 }
macKey()
static QCFType<CFStringRef> macKey (const QString & key) static
Definition at line 88 of file qsettings_mac.cpp.
Referenced by QMacSettingsPrivate::get(), QMacSettingsPrivate::remove(), QMacSettingsPrivate::set(), and QConfFileSettingsPrivate::writePlistFile().
 {
     return QCFString::toCFStringRef(rotateSlashesDotsAndMiddots(key, Macify));
 }
macList()
static CFArrayRef macList (const QList< QVariant > & list) static
Definition at line 100 of file qsettings_mac.cpp.
Referenced by macValue().
 {
     int n = list.size();
     QVarLengthArray<QCFType<CFPropertyListRef> > cfvalues(n);
     for (int i = 0; i < n; ++i)
         cfvalues[i] = macValue(list.at(i));
     return CFArrayCreate(kCFAllocatorDefault, reinterpret_cast<const void **>(cfvalues.data()),
                          CFIndex(n), &kCFTypeArrayCallBacks);
 }
macValue()
static QCFType< CFPropertyListRef > macValue (const QVariant & value) static
Definition at line 110 of file qsettings_mac.cpp.
Referenced by macList(), qtKey(), QMacSettingsPrivate::set(), and QConfFileSettingsPrivate::writePlistFile().
 {
     CFPropertyListRef result = 0;
     switch (value.type()) {
     case QVariant::ByteArray:
         {
             QByteArray ba = value.toByteArray();
             result = CFDataCreate(kCFAllocatorDefault, reinterpret_cast<const UInt8 *>(ba.data()),
                                   CFIndex(ba.size()));
         }
         break;
     // should be same as below (look for LIST)
     case QVariant::List:
     case QVariant::StringList:
     case QVariant::Polygon:
         result = macList(value.toList());
         break;
     case QVariant::Map:
         {
             /*
                 QMap<QString, QVariant> is potentially a multimap,
                 whereas CFDictionary is a single-valued map. To allow
                 for multiple values with the same key, we store
                 multiple values in a CFArray. To avoid ambiguities,
                 we also wrap lists in a CFArray singleton.
             */
             QMap<QString, QVariant> map = value.toMap();
             QMap<QString, QVariant>::const_iterator i = map.constBegin();
             int maxUniqueKeys = map.size();
             int numUniqueKeys = 0;
             QVarLengthArray<QCFType<CFPropertyListRef> > cfkeys(maxUniqueKeys);
             QVarLengthArray<QCFType<CFPropertyListRef> > cfvalues(maxUniqueKeys);
             while (i != map.constEnd()) {
                 const QString &key = i.key();
                 QList<QVariant> values;
                 do {
                     values << i.value();
                     ++i;
                 } while (i != map.constEnd() && i.key() == key);
                 bool singleton = (values.count() == 1);
                 if (singleton) {
                     switch (values.first().type()) {
                     // should be same as above (look for LIST)
                     case QVariant::List:
                     case QVariant::StringList:
                     case QVariant::Polygon:
                         singleton = false;
                     default:
                         ;
                     }
                 }
                 cfkeys[numUniqueKeys] = QCFString::toCFStringRef(key);
                 cfvalues[numUniqueKeys] = singleton ? macValue(values.first()) : macList(values);
                 ++numUniqueKeys;
             }
             result = CFDictionaryCreate(kCFAllocatorDefault,
                                         reinterpret_cast<const void **>(cfkeys.data()),
                                         reinterpret_cast<const void **>(cfvalues.data()),
                                         CFIndex(numUniqueKeys),
                                         &kCFTypeDictionaryKeyCallBacks,
                                         &kCFTypeDictionaryValueCallBacks);
         }
         break;
     case QVariant::DateTime:
         {
             /*
                 CFDate, unlike QDateTime, doesn't store timezone information.
             */
             QDateTime dt = value.toDateTime();
             if (dt.timeSpec() == Qt::LocalTime) {
                 QDateTime reference;
                 reference.setTime_t((uint)kCFAbsoluteTimeIntervalSince1970);
                 result = CFDateCreate(kCFAllocatorDefault, CFAbsoluteTime(reference.secsTo(dt)));
             } else {
                 goto string_case;
             }
         }
         break;
     case QVariant::Bool:
         result = value.toBool() ? kCFBooleanTrue : kCFBooleanFalse;
         break;
     case QVariant::Int:
     case QVariant::UInt:
         {
             int n = value.toInt();
             result = CFNumberCreate(kCFAllocatorDefault, kCFNumberIntType, &n);
         }
         break;
     case QVariant::Double:
         {
             double n = value.toDouble();
             result = CFNumberCreate(kCFAllocatorDefault, kCFNumberDoubleType, &n);
         }
         break;
     case QVariant::LongLong:
     case QVariant::ULongLong:
         {
             qint64 n = value.toLongLong();
             result = CFNumberCreate(0, kCFNumberLongLongType, &n);
         }
         break;
     case QVariant::String:
     string_case:
     default:
         result = QCFString::toCFStringRef(QSettingsPrivate::variantToString(value));
     }
     return result;
 }
qtKey()
static QString qtKey (CFStringRef cfkey) static
Definition at line 93 of file qsettings_mac.cpp.
Referenced by QMacSettingsPrivate::children(), QTestEventList::clear(), QKeySequencePrivate::decodeString(), QOpenKODEWindow::processKeyEvents(), qtKey2CocoaKey(), QConfFileSettingsPrivate::readPlistFile(), and QKeyMapperPrivate::updatePossibleKeyCodes().
 {
     return rotateSlashesDotsAndMiddots(QCFString::toQString(cfkey), Qtify);
 }
qtValue()
static QVariant qtValue (CFPropertyListRef cfvalue) static
Definition at line 226 of file qsettings_mac.cpp.
Referenced by QMacSettingsPrivate::get(), and QConfFileSettingsPrivate::readPlistFile().
 {
     if (!cfvalue)
         return QVariant();
     CFTypeID typeId = CFGetTypeID(cfvalue);
     /*
         Sorted grossly from most to least frequent type.
     */
     if (typeId == CFStringGetTypeID()) {
         return QSettingsPrivate::stringToVariant(QCFString::toQString(static_cast<CFStringRef>(cfvalue)));
     } else if (typeId == CFNumberGetTypeID()) {
         CFNumberRef cfnumber = static_cast<CFNumberRef>(cfvalue);
         if (CFNumberIsFloatType(cfnumber)) {
             double d;
             CFNumberGetValue(cfnumber, kCFNumberDoubleType, &d);
             return d;
         } else {
             int i;
             qint64 ll;
             if (CFNumberGetValue(cfnumber, kCFNumberIntType, &i))
                 return i;
             CFNumberGetValue(cfnumber, kCFNumberLongLongType, &ll);
             return ll;
         }
     } else if (typeId == CFArrayGetTypeID()) {
         CFArrayRef cfarray = static_cast<CFArrayRef>(cfvalue);
         QList<QVariant> list;
         CFIndex size = CFArrayGetCount(cfarray);
         bool metNonString = false;
         for (CFIndex i = 0; i < size; ++i) {
             QVariant value = qtValue(CFArrayGetValueAtIndex(cfarray, i));
             if (value.type() != QVariant::String)
                 metNonString = true;
             list << value;
         }
         if (metNonString)
             return list;
         else
             return QVariant(list).toStringList();
     } else if (typeId == CFBooleanGetTypeID()) {
         return (bool)CFBooleanGetValue(static_cast<CFBooleanRef>(cfvalue));
     } else if (typeId == CFDataGetTypeID()) {
         CFDataRef cfdata = static_cast<CFDataRef>(cfvalue);
         return QByteArray(reinterpret_cast<const char *>(CFDataGetBytePtr(cfdata)),
                           CFDataGetLength(cfdata));
     } else if (typeId == CFDictionaryGetTypeID()) {
         CFDictionaryRef cfdict = static_cast<CFDictionaryRef>(cfvalue);
         CFTypeID arrayTypeId = CFArrayGetTypeID();
         int size = (int)CFDictionaryGetCount(cfdict);
         QVarLengthArray<CFPropertyListRef> keys(size);
         QVarLengthArray<CFPropertyListRef> values(size);
         CFDictionaryGetKeysAndValues(cfdict, keys.data(), values.data());
         QMultiMap<QString, QVariant> map;
         for (int i = 0; i < size; ++i) {
             QString key = QCFString::toQString(static_cast<CFStringRef>(keys[i]));
             if (CFGetTypeID(values[i]) == arrayTypeId) {
                 CFArrayRef cfarray = static_cast<CFArrayRef>(values[i]);
                 CFIndex arraySize = CFArrayGetCount(cfarray);
                 for (CFIndex j = arraySize - 1; j >= 0; --j)
                     map.insert(key, qtValue(CFArrayGetValueAtIndex(cfarray, j)));
             } else {
                 map.insert(key, qtValue(values[i]));
             }
         }
         return map;
     } else if (typeId == CFDateGetTypeID()) {
         QDateTime dt;
         dt.setTime_t((uint)kCFAbsoluteTimeIntervalSince1970);
         return dt.addSecs((int)CFDateGetAbsoluteTime(static_cast<CFDateRef>(cfvalue)));
     }
     return QVariant();
 }
rotateSlashesDotsAndMiddots()
static QString rotateSlashesDotsAndMiddots (const QString & key, int shift) static
Definition at line 71 of file qsettings_mac.cpp.
Referenced by macKey(), and qtKey().
 {
     static const int NumKnights = 3;
     static const char knightsOfTheRoundTable[NumKnights] = { '/', '.', '\xb7' };
     QString result = key;
     for (int i = 0; i < result.size(); ++i) {
         for (int j = 0; j < NumKnights; ++j) {
             if (result.at(i) == QLatin1Char(knightsOfTheRoundTable[j])) {
                 result[i] = QLatin1Char(knightsOfTheRoundTable[(j + shift) % NumKnights]).unicode();
                 break;
             }
         }
     }
     return result;
 }
urlFromFileName()
static QCFType<CFURLRef> urlFromFileName (const QString & fileName) static
Definition at line 671 of file qsettings_mac.cpp.
Referenced by QConfFileSettingsPrivate::readPlistFile(), and QConfFileSettingsPrivate::writePlistFile().
 {
     return CFURLCreateWithFileSystemPath(kCFAllocatorDefault, QCFString(fileName),
                                          kCFURLPOSIXPathStyle, false);
 }
Variable Documentation
hostNames
const CFStringRef hostNames[2] = { kCFPreferencesCurrentHost, kCFPreferencesAnyHost } static
Definition at line 58 of file qsettings_mac.cpp.
Referenced by QMacSettingsPrivate::children(), QMacSettingsPrivate::get(), and QMacSettingsPrivate::sync().
numHostNames
const int numHostNames = 2 static
Definition at line 59 of file qsettings_mac.cpp.
Referenced by QMacSettingsPrivate::children(), QMacSettingsPrivate::get(), and QMacSettingsPrivate::sync().