Qt 4.8: /src/network/bearer/qsharednetworksession.cpp File Reference
qsharednetworksession.cpp File Reference
#include "qsharednetworksession_p.h"
#include "qbearerengine_p.h"
#include <QThreadStorage>
Functions
static void doDeleteLater (QObject *obj)
uint qHash (const QNetworkConfiguration &config)
QSharedNetworkSessionManager * sharedNetworkSessionManager ()
Variables
QThreadStorage< QSharedNetworkSessionManager * > tls
Function Documentation
doDeleteLater()
static void doDeleteLater (QObject * obj) static
Definition at line 62 of file qsharednetworksession.cpp.
Referenced by QSharedNetworkSessionManager::getSession().
 {
     obj->deleteLater();
 }
qHash()
uint qHash (const QNetworkConfiguration & config)
Definition at line 88 of file qsharednetworksession.cpp.
 {
     return ((uint)config.type()) | (((uint)config.bearerType()) << 8) | (((uint)config.purpose()) << 16);
 }
sharedNetworkSessionManager()
QSharedNetworkSessionManager* sharedNetworkSessionManager () inline
Definition at line 52 of file qsharednetworksession.cpp.
Referenced by QSharedNetworkSessionManager::getSession(), and QSharedNetworkSessionManager::setSession().
 {
     QSharedNetworkSessionManager* rv = tls.localData();
     if (!rv) {
         rv = new QSharedNetworkSessionManager;
         tls.setLocalData(rv);
     }
     return rv;
 }
Variable Documentation
tls
QThreadStorage<QSharedNetworkSessionManager *> tls
Definition at line 50 of file qsharednetworksession.cpp.
Referenced by QThreadStorageData::finish(), QThreadStorageData::get(), and QThreadStorageData::set().