Qt 4.8: /src/corelib/tools/qshareddata.h File Reference
qshareddata.h File Reference
#include <QtCore/qglobal.h>
#include <QtCore/qatomic.h>
Classes
class QExplicitlySharedDataPointer< T >
The QExplicitlySharedDataPointer class represents a pointer to an explicitly shared object.
class QSharedData
The QSharedData class is a base class for shared data objects.
class QSharedDataPointer< T >
The QSharedDataPointer class represents a pointer to an implicitly shared object.
class QSharedDataPointer< T >
The QSharedDataPointer class represents a pointer to an implicitly shared object.
Functions
template<class T >
Q_INLINE_TEMPLATE void qSwap (QSharedDataPointer< T > &p1, QSharedDataPointer< T > &p2)
template<class T >
Q_INLINE_TEMPLATE void qSwap (QExplicitlySharedDataPointer< T > &p1, QExplicitlySharedDataPointer< T > &p2)
template<class T >
Q_INLINE_TEMPLATE void std::swap (::QSharedDataPointer< T > &p1, ::QSharedDataPointer< T > &p2)
template<class T >
Q_INLINE_TEMPLATE void std::swap (::QExplicitlySharedDataPointer< T > &p1, ::QExplicitlySharedDataPointer< T > &p2)
Function Documentation
qSwap() [1/2]
template<class T > Q_INLINE_TEMPLATE void qSwap (QSharedDataPointer< T > & p1, QSharedDataPointer< T > & p2)
Definition at line 261 of file qshareddata.h.
Referenced by QSharedDataPointer< QSslConfigurationPrivate >::operator=(), QExplicitlySharedDataPointer< QSslConfigurationPrivate >::operator=(), QSharedDataPointer< QSslConfigurationPrivate >::swap(), and QExplicitlySharedDataPointer< QSslConfigurationPrivate >::swap().
 { p1.swap(p2); }
qSwap() [2/2]
template<class T > Q_INLINE_TEMPLATE void qSwap (QExplicitlySharedDataPointer< T > & p1, QExplicitlySharedDataPointer< T > & p2)
Definition at line 265 of file qshareddata.h.
 { p1.swap(p2); }
swap() [1/2]
template<class T > Q_INLINE_TEMPLATE void std::swap (::QSharedDataPointer< T > & p1, ::QSharedDataPointer< T > & p2)
Definition at line 272 of file qshareddata.h.
     { p1.swap(p2); }
swap() [2/2]
template<class T > Q_INLINE_TEMPLATE void std::swap (::QExplicitlySharedDataPointer< T > & p1, ::QExplicitlySharedDataPointer< T > & p2)
Definition at line 276 of file qshareddata.h.
     { p1.swap(p2); }