Qt 4.8: /src/corelib/tools/qsimd_p.h File Reference
qsimd_p.h File Reference
#include <qglobal.h>
Macros
#define ALIGNMENT_PROLOGUE_16BYTES(ptr, i, length) for (; i < static_cast<int>(qMin(static_cast<quintptr>(length), ((4 - ((reinterpret_cast<quintptr>(ptr) >> 2) & 0x3)) & 0x3))); ++i)
Enumerations
enum CPUFeatures {
None = 0, MMX = 0x1, MMXEXT = 0x2, MMX3DNOW = 0x4,
MMX3DNOWEXT = 0x8, SSE = 0x10, SSE2 = 0x20, CMOV = 0x40,
IWMMXT = 0x80, NEON = 0x100, SSE3 = 0x200, SSSE3 = 0x400,
SSE4_1 = 0x800, SSE4_2 = 0x1000, AVX = 0x2000
}
Functions
Q_CORE_EXPORT uint qDetectCPUFeatures ()
Macro Definition Documentation
ALIGNMENT_PROLOGUE_16BYTES
#define ALIGNMENT_PROLOGUE_16BYTES (ptr, i, length) for (; i < static_cast<int>(qMin(static_cast<quintptr>(length), ((4 - ((reinterpret_cast<quintptr>(ptr) >> 2) & 0x3)) & 0x3))); ++i)
Definition at line 231 of file qsimd_p.h.
Enumeration Type Documentation
CPUFeatures
enum CPUFeatures
Enumerator
None
MMX
MMXEXT
MMX3DNOW
MMX3DNOWEXT
SSE
SSE2
CMOV
IWMMXT
NEON
SSE3
SSSE3
SSE4_1
SSE4_2
AVX
Definition at line 210 of file qsimd_p.h.
                  {
     None        = 0,
     MMX         = 0x1,
     MMXEXT      = 0x2,
     MMX3DNOW    = 0x4,
     MMX3DNOWEXT = 0x8,
     SSE         = 0x10,
     SSE2        = 0x20,
     CMOV        = 0x40,
     IWMMXT      = 0x80,
     NEON        = 0x100,
     SSE3        = 0x200,
     SSSE3       = 0x400,
     SSE4_1      = 0x800,
     SSE4_2      = 0x1000,
     AVX         = 0x2000
 };
Function Documentation
qDetectCPUFeatures()
Q_CORE_EXPORT uint qDetectCPUFeatures ()
Definition at line 382 of file qsimd.cpp.
Referenced by qDumpCPUFeatures(), qInitDrawhelperAsm(), qInitImageConversions(), and QJpegHandler::QJpegHandler().
 {
     static QBasicAtomicInt features = Q_BASIC_ATOMIC_INITIALIZER(-1);
     if (features != -1)
         return features;
     uint f = detectProcessorFeatures();
     QByteArray disable = qgetenv("QT_NO_CPU_FEATURE");
     if (!disable.isEmpty()) {
         disable.prepend(' ');
         for (int i = 0; i < features_count; ++i) {
             if (disable.contains(features_string + features_indices[i]))
                 f &= ~(1 << i);
         }
     }
     features = f;
     return features;
 }