Qt 4.8: /src/corelib/tools/qsimd.cpp File Reference
qsimd.cpp File Reference
#include "qsimd_p.h"
#include <QByteArray>
#include <stdio.h>
#include <windows.h>
Functions
static uint detectProcessorFeatures ()
uint qDetectCPUFeatures ()
void qDumpCPUFeatures ()
Variables
const int features_count = (sizeof features_indices - 1) / (sizeof features_indices[0])
static const int features_indices []
static const char features_string []
Function Documentation
detectProcessorFeatures()
static uint detectProcessorFeatures () inline static
Definition at line 81 of file qsimd.cpp.
Referenced by qDetectCPUFeatures().
 {
     uint features = 0;
 #if defined (ARM)
     if (IsProcessorFeaturePresent(PF_ARM_INTEL_WMMX)) {
         features = IWMMXT;
         return features;
     }
 #elif defined(_X86_)
     features = 0;
 #if defined QT_HAVE_MMX
     if (IsProcessorFeaturePresent(PF_MMX_INSTRUCTIONS_AVAILABLE))
         features |= MMX;
 #endif
 #if defined QT_HAVE_3DNOW
     if (IsProcessorFeaturePresent(PF_3DNOW_INSTRUCTIONS_AVAILABLE))
         features |= MMX3DNOW;
 #endif
     return features;
 #endif
     features = 0;
     return features;
 }
qDetectCPUFeatures()
uint qDetectCPUFeatures ()
Definition at line 382 of file qsimd.cpp.
Referenced by qDumpCPUFeatures(), qInitDrawhelperAsm(), qInitImageConversions(), and QJpegHandler::QJpegHandler().
 {
     static QBasicAtomicInt features = Q_BASIC_ATOMIC_INITIALIZER(-1);
     if (features != -1)
         return features;
     uint f = detectProcessorFeatures();
     QByteArray disable = qgetenv("QT_NO_CPU_FEATURE");
     if (!disable.isEmpty()) {
         disable.prepend(' ');
         for (int i = 0; i < features_count; ++i) {
             if (disable.contains(features_string + features_indices[i]))
                 f &= ~(1 << i);
         }
     }
     features = f;
     return features;
 }
qDumpCPUFeatures()
void qDumpCPUFeatures ()
Definition at line 402 of file qsimd.cpp.
Referenced by QLibraryInfo::location().
 {
     uint features = qDetectCPUFeatures();
     printf("Processor features: ");
     for (int i = 0; i < features_count; ++i) {
         if (features & (1 << i))
             printf("%s", features_string + features_indices[i]);
     }
     puts("");
 }
Variable Documentation
features_count
const int features_count = (sizeof features_indices - 1) / (sizeof features_indices[0])
Definition at line 380 of file qsimd.cpp.
Referenced by qDetectCPUFeatures(), and qDumpCPUFeatures().
features_indices
const int features_indices[] static
Initial value:
= {
       0,    5,   13,   23,   36,   41,   47,   53,
      61,   67,   73,   80,   88,   96,   -1
}
Definition at line 374 of file qsimd.cpp.
Referenced by qDetectCPUFeatures(), and qDumpCPUFeatures().
features_string
const char features_string[] static
Initial value:
=
    " mmx\0"
    " mmxext\0"
    " mmx3dnow\0"
    " mmx3dnowext\0"
    " sse\0"
    " sse2\0"
    " cmov\0"
    " iwmmxt\0"
    " neon\0"
    " sse3\0"
    " ssse3\0"
    " sse4.1\0"
    " sse4.2\0"
    " avx\0"
    "\0"
Definition at line 357 of file qsimd.cpp.
Referenced by qDetectCPUFeatures(), and qDumpCPUFeatures().