Qt 4.8: /src/gui/widgets/qsizegrip.cpp File Reference
qsizegrip.cpp File Reference
#include "qsizegrip.h"
#include "qapplication.h"
#include "qevent.h"
#include "qpainter.h"
#include "qstyle.h"
#include "qstyleoption.h"
#include "qlayout.h"
#include "qdebug.h"
#include <QDesktopWidget>
#include <private/qt_x11_p.h>
#include <private/qt_mac_p.h>
#include <private/qwidget_p.h>
#include <QtGui/qabstractscrollarea.h>
#include "moc_qsizegrip.cpp"
Classes
class QSizeGripPrivate
Macros
#define SZ_SIZEBOTTOMLEFT 0xf007
#define SZ_SIZEBOTTOMRIGHT 0xf008
#define SZ_SIZETOPLEFT 0xf004
#define SZ_SIZETOPRIGHT 0xf005
Functions
static QWidget * qt_sizegrip_topLevelWidget (QWidget *w)
Macro Definition Documentation
SZ_SIZEBOTTOMLEFT
#define SZ_SIZEBOTTOMLEFT 0xf007
Definition at line 68 of file qsizegrip.cpp.
Referenced by QSizeGrip::mousePressEvent().
SZ_SIZEBOTTOMRIGHT
#define SZ_SIZEBOTTOMRIGHT 0xf008
Definition at line 67 of file qsizegrip.cpp.
Referenced by QSizeGrip::mousePressEvent().
SZ_SIZETOPLEFT
#define SZ_SIZETOPLEFT 0xf004
Definition at line 69 of file qsizegrip.cpp.
Referenced by QSizeGrip::mousePressEvent().
SZ_SIZETOPRIGHT
#define SZ_SIZETOPRIGHT 0xf005
Definition at line 70 of file qsizegrip.cpp.
Referenced by QSizeGrip::mousePressEvent().
Function Documentation
qt_sizegrip_topLevelWidget()
static QWidget* qt_sizegrip_topLevelWidget (QWidget * w) static
Definition at line 74 of file qsizegrip.cpp.
Referenced by QSizeGripPrivate::corner(), QSizeGrip::mouseMoveEvent(), QSizeGrip::mousePressEvent(), QSizeGripPrivate::updateMacSizer(), and QSizeGripPrivate::updateTopLevelWidget().
 {
     while (w && !w->isWindow() && w->windowType() != Qt::SubWindow)
         w = w->parentWidget();
     return w;
 }