Qt 4.8: /src/network/socket/qsocks5socketengine.cpp File Reference
qsocks5socketengine.cpp File Reference
#include "qsocks5socketengine_p.h"
#include "qtcpsocket.h"
#include "qudpsocket.h"
#include "qtcpserver.h"
#include "qdebug.h"
#include "qhash.h"
#include "qqueue.h"
#include "qelapsedtimer.h"
#include "qmutex.h"
#include "qthread.h"
#include "qcoreapplication.h"
#include "qurl.h"
#include "qauthenticator.h"
#include <qendian.h>
#include <qnetworkinterface.h>
Classes
struct QSocks5BindData
class QSocks5BindStore
struct QSocks5ConnectData
struct QSocks5Data
struct QSocks5RevivedDatagram
struct QSocks5UdpAssociateData
Macros
#define MAX_DATA_DUMP 256
#define Q_INIT_CHECK(returnValue)
#define QSOCKS5_D_DEBUG if (0) qDebug()
#define QSOCKS5_DEBUG if (0) qDebug()
#define QSOCKS5_Q_DEBUG if (0) qDebug()
#define S5_AUTHMETHOD_NONE 0x00
#define S5_AUTHMETHOD_NOTACCEPTABLE 0xFF
#define S5_AUTHMETHOD_PASSWORD 0x02
#define S5_BIND 0x02
#define S5_CONNECT 0x01
#define S5_DOMAINNAME 0x03
#define S5_IP_V4 0x01
#define S5_IP_V6 0x04
#define S5_PASSWORDAUTH_VERSION 0x01
#define S5_R_ERROR_ADD_TYPE_NOT_SUPORTED 0x08
#define S5_R_ERROR_CMD_NOT_SUPPORTED 0x07
#define S5_R_ERROR_CON_NOT_ALLOWED 0x02
#define S5_R_ERROR_CONN_REFUSED 0x05
#define S5_R_ERROR_HOST_UNREACH 0x04
#define S5_R_ERROR_NET_UNREACH 0x03
#define S5_R_ERROR_SOCKS_FAILURE 0x01
#define S5_R_ERROR_TTL 0x06
#define S5_SUCCESS 0x00
#define S5_UDP_ASSOCIATE 0x03
#define S5_VERSION_5 0x05
#define SOCKS5_BLOCKING_BIND_TIMEOUT 10000
Functions
static QString dump (const QByteArray &)
static bool qt_socks5_get_host_address_and_port (const QByteArray &buf, QHostAddress *pAddress, quint16 *pPort, int *pPos)
static bool qt_socks5_set_host_address_and_port (const QHostAddress &address, quint16 port, QByteArray *pBuf)
static bool qt_socks5_set_host_name_and_port (const QString &hostname, quint16 port, QByteArray *pBuf)
static int qt_timeout_value (int msecs, int elapsed)
Variables
static QBasicAtomicInt descriptorCounter = Q_BASIC_ATOMIC_INITIALIZER(1)
static const int MaxWriteBufferSize = 128*1024
static QString s5StateToString (QSocks5SocketEnginePrivate::Socks5State)
Macro Definition Documentation
MAX_DATA_DUMP
#define MAX_DATA_DUMP 256
Definition at line 71 of file qsocks5socketengine.cpp.
Q_INIT_CHECK
#define Q_INIT_CHECK (returnValue)
Value:
do { \
    if (!d->data) { \
        return returnValue; \
    } } while (0)
Definition at line 78 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEngine::hasPendingDatagrams().
QSOCKS5_D_DEBUG
#define QSOCKS5_D_DEBUG if (0) qDebug()
Definition at line 149 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::_q_controlSocketDisconnected(), QSocks5SocketEnginePrivate::_q_controlSocketError(), QSocks5SocketEnginePrivate::_q_controlSocketReadNotification(), QSocks5SocketEnginePrivate::_q_controlSocketStateChanged(), QSocks5SocketEnginePrivate::_q_emitPendingConnectionNotification(), QSocks5SocketEnginePrivate::_q_emitPendingReadNotification(), QSocks5SocketEnginePrivate::_q_emitPendingWriteNotification(), QSocks5SocketEnginePrivate::_q_udpSocketReadNotification(), QSocks5SocketEnginePrivate::emitConnectionNotification(), QSocks5SocketEnginePrivate::emitReadNotification(), QSocks5SocketEnginePrivate::emitWriteNotification(), QSocks5SocketEnginePrivate::initialize(), and QSocks5SocketEnginePrivate::parseAuthenticationMethodReply().
QSOCKS5_DEBUG
#define QSOCKS5_DEBUG if (0) qDebug()
Definition at line 147 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::_q_controlSocketBytesWritten(), QSocks5SocketEnginePrivate::_q_controlSocketConnected(), QSocks5SocketEnginePrivate::_q_controlSocketReadNotification(), QSocks5SocketEnginePrivate::_q_udpSocketReadNotification(), QSocks5SocketEngine::bind(), QSocks5SocketEngine::connectToHost(), QSocks5SocketEngineHandler::createSocketEngine(), QSocks5SocketEnginePrivate::parseRequestMethodReply(), qt_socks5_get_host_address_and_port(), qt_socks5_set_host_address_and_port(), qt_socks5_set_host_name_and_port(), QSocks5SocketEngine::read(), QSocks5SocketEnginePrivate::reauthenticate(), QSocks5BindStore::retrieve(), QSocks5SocketEnginePrivate::sendRequestMethod(), QSocks5BindStore::timerEvent(), QSocks5SocketEngine::waitForRead(), QSocks5SocketEngine::waitForWrite(), and QSocks5SocketEngine::writeDatagram().
QSOCKS5_Q_DEBUG
#define QSOCKS5_Q_DEBUG if (0) qDebug()
Definition at line 148 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEngine::accept(), QSocks5SocketEngine::bind(), QSocks5SocketEngine::close(), QSocks5SocketEngine::initialize(), QSocks5SocketEngine::listen(), QSocks5SocketEngine::read(), QSocks5SocketEngine::setReadNotificationEnabled(), and QSocks5SocketEngine::write().
S5_AUTHMETHOD_NONE
#define S5_AUTHMETHOD_NONE 0x00
Definition at line 100 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::parseAuthenticationMethodReply().
S5_AUTHMETHOD_NOTACCEPTABLE
#define S5_AUTHMETHOD_NOTACCEPTABLE 0xFF
Definition at line 102 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::parseAuthenticationMethodReply().
S5_AUTHMETHOD_PASSWORD
#define S5_AUTHMETHOD_PASSWORD 0x02
Definition at line 101 of file qsocks5socketengine.cpp.
S5_BIND
#define S5_BIND 0x02
Definition at line 85 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::sendRequestMethod().
S5_CONNECT
#define S5_CONNECT 0x01
Definition at line 84 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::sendRequestMethod().
S5_DOMAINNAME
#define S5_DOMAINNAME 0x03
Definition at line 88 of file qsocks5socketengine.cpp.
Referenced by qt_socks5_get_host_address_and_port(), and qt_socks5_set_host_name_and_port().
S5_IP_V4
#define S5_IP_V4 0x01
Definition at line 87 of file qsocks5socketengine.cpp.
Referenced by qt_socks5_get_host_address_and_port(), and qt_socks5_set_host_address_and_port().
S5_IP_V6
#define S5_IP_V6 0x04
Definition at line 89 of file qsocks5socketengine.cpp.
Referenced by qt_socks5_get_host_address_and_port(), and qt_socks5_set_host_address_and_port().
S5_PASSWORDAUTH_VERSION
#define S5_PASSWORDAUTH_VERSION 0x01
Definition at line 104 of file qsocks5socketengine.cpp.
Referenced by QSocks5PasswordAuthenticator::beginAuthenticate(), and QSocks5PasswordAuthenticator::continueAuthenticate().
S5_R_ERROR_ADD_TYPE_NOT_SUPORTED
#define S5_R_ERROR_ADD_TYPE_NOT_SUPORTED 0x08
Definition at line 98 of file qsocks5socketengine.cpp.
S5_R_ERROR_CMD_NOT_SUPPORTED
#define S5_R_ERROR_CMD_NOT_SUPPORTED 0x07
Definition at line 97 of file qsocks5socketengine.cpp.
S5_R_ERROR_CON_NOT_ALLOWED
#define S5_R_ERROR_CON_NOT_ALLOWED 0x02
Definition at line 92 of file qsocks5socketengine.cpp.
S5_R_ERROR_CONN_REFUSED
#define S5_R_ERROR_CONN_REFUSED 0x05
Definition at line 95 of file qsocks5socketengine.cpp.
S5_R_ERROR_HOST_UNREACH
#define S5_R_ERROR_HOST_UNREACH 0x04
Definition at line 94 of file qsocks5socketengine.cpp.
S5_R_ERROR_NET_UNREACH
#define S5_R_ERROR_NET_UNREACH 0x03
Definition at line 93 of file qsocks5socketengine.cpp.
S5_R_ERROR_SOCKS_FAILURE
#define S5_R_ERROR_SOCKS_FAILURE 0x01
Definition at line 91 of file qsocks5socketengine.cpp.
S5_R_ERROR_TTL
#define S5_R_ERROR_TTL 0x06
Definition at line 96 of file qsocks5socketengine.cpp.
S5_SUCCESS
#define S5_SUCCESS 0x00
Definition at line 90 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::parseRequestMethodReply().
S5_UDP_ASSOCIATE
#define S5_UDP_ASSOCIATE 0x03
Definition at line 86 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::sendRequestMethod().
S5_VERSION_5
#define S5_VERSION_5 0x05
Definition at line 83 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::_q_controlSocketConnected(), QSocks5SocketEnginePrivate::parseAuthenticationMethodReply(), QSocks5SocketEnginePrivate::parseRequestMethodReply(), and QSocks5SocketEnginePrivate::sendRequestMethod().
SOCKS5_BLOCKING_BIND_TIMEOUT
#define SOCKS5_BLOCKING_BIND_TIMEOUT 10000
Definition at line 75 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEngine::bind().
Function Documentation
dump()
static QString dump (const QByteArray &) inline static
Definition at line 152 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::_q_controlSocketReadNotification(), QSocks5SocketEnginePrivate::_q_udpSocketReadNotification(), QGraphicsLinearLayout::addStretch(), QRegExpEngine::captureCount(), QRegExpEngine::Box::clear(), QHashData::destroyAndFree(), QMap< int, QFrameInfo >::empty(), QHash< QExplicitlySharedDataPointer, QHash >::empty(), QRegExpCharClass::firstOccurrence(), QGridLayoutItem::layoutItem(), QMapData::node_delete(), QContiguousCache< T >::normalizeIndexes(), QSocks5SocketEnginePrivate::parseRequestMethodReply(), QGridLayoutBox::QGridLayoutBox(), QGridLayoutRowInfo::QGridLayoutRowInfo(), QSocks5SocketEngine::read(), QGridLayoutEngine::removeRows(), QFormLayout::resetLabelAlignment(), QSocks5SocketEnginePrivate::sendRequestMethod(), AnchorData::updateChildrenSizes(), QSocks5SocketEngine::write(), and QSocks5SocketEngine::writeDatagram().
 { return QString(); }
qt_socks5_get_host_address_and_port()
static bool qt_socks5_get_host_address_and_port (const QByteArray & buf, QHostAddress * pAddress, quint16 * pPort, int * pPos) static
Definition at line 222 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::_q_udpSocketReadNotification(), and QSocks5SocketEnginePrivate::parseRequestMethodReply().
 {
     bool ret = false;
     int pos = *pPos;
     const unsigned char *pBuf = reinterpret_cast<const unsigned char*>(buf.constData());
     QHostAddress address;
     quint16 port = 0;
     if (buf.size() - pos < 1) {
         QSOCKS5_DEBUG << "need more data address/port";
         return false;
     }
     if (pBuf[pos] == S5_IP_V4) {
         pos++;
         if (buf.size() - pos < 4) {
             QSOCKS5_DEBUG << "need more data for ip4 address";
             return false;
         }
         address.setAddress(qFromBigEndian<quint32>(&pBuf[pos]));
         pos += 4;
         ret = true;
     } else if (pBuf[pos] == S5_IP_V6) {
         pos++;
         if (buf.size() - pos < 16) {
             QSOCKS5_DEBUG << "need more data for ip6 address";
             return false;
         }
         QIPv6Address add;
         for (int i = 0; i < 16; ++i)
             add[i] = buf[pos++];
         ret = true;
     } else if (pBuf[pos] == S5_DOMAINNAME){
         // just skip it
         pos++;
         qDebug() << "skipping hostname of len" << uint(pBuf[pos]);
         pos += uchar(pBuf[pos]);
     } else {
         QSOCKS5_DEBUG << "invalid address type" << (int)pBuf[pos];
         ret = false;
     }
     if (ret) {
         if (buf.size() - pos < 2) {
             QSOCKS5_DEBUG << "need more data for port";
             return false;
         }
         port = qFromBigEndian<quint16>(&pBuf[pos]);
         pos += 2;
     }
     if (ret) {
         QSOCKS5_DEBUG << "got [" << address << ':' << port << ']';
         *pAddress = address;
         *pPort = port;
         *pPos = pos;
     }
     return ret;
 }
qt_socks5_set_host_address_and_port()
static bool qt_socks5_set_host_address_and_port (const QHostAddress & address, quint16 port, QByteArray * pBuf) static
Definition at line 159 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::sendRequestMethod(), and QSocks5SocketEngine::writeDatagram().
 {
     QSOCKS5_DEBUG << "setting [" << address << ':' << port << ']';
     union {
         quint16 port;
         quint32 ipv4;
         QIPv6Address ipv6;
         char ptr;
     } data;
     // add address
     if (address.protocol() == QAbstractSocket::IPv4Protocol) {
         data.ipv4 = qToBigEndian<quint32>(address.toIPv4Address());
         pBuf->append(S5_IP_V4);
         pBuf->append(QByteArray::fromRawData(&data.ptr, sizeof data.ipv4));
     } else if (address.protocol() == QAbstractSocket::IPv6Protocol) {
         data.ipv6 = address.toIPv6Address();
         pBuf->append(S5_IP_V6);
         pBuf->append(QByteArray::fromRawData(&data.ptr, sizeof data.ipv6));
     } else {
         return false;
     }
     // add port
     data.port = qToBigEndian<quint16>(port);
     pBuf->append(QByteArray::fromRawData(&data.ptr, sizeof data.port));
     return true;
 }
qt_socks5_set_host_name_and_port()
static bool qt_socks5_set_host_name_and_port (const QString & hostname, quint16 port, QByteArray * pBuf) static
Definition at line 192 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::sendRequestMethod().
 {
     QSOCKS5_DEBUG << "setting [" << hostname << ':' << port << ']';
     QByteArray encodedHostName = QUrl::toAce(hostname);
     QByteArray &buf = *pBuf;
     if (encodedHostName.length() > 255)
         return false;
     buf.append(S5_DOMAINNAME);
     buf.append(uchar(encodedHostName.length()));
     buf.append(encodedHostName);
     // add port
     union {
         quint16 port;
         char ptr;
     } data;
     data.port = qToBigEndian<quint16>(port);
     buf.append(QByteArray::fromRawData(&data.ptr, sizeof data.port));
     return true;
 }
qt_timeout_value()
static int qt_timeout_value (int msecs, int elapsed) static
Definition at line 286 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEngine::bind(), QSocks5SocketEngine::close(), QSocks5SocketEnginePrivate::waitForConnected(), QSocks5SocketEngine::waitForRead(), and QSocks5SocketEngine::waitForWrite().
 {
     if (msecs == -1)
         return -1;
     int timeout = msecs - elapsed;
     return timeout < 0 ? 0 : timeout;
 }
Variable Documentation
descriptorCounter
QBasicAtomicInt descriptorCounter = Q_BASIC_ATOMIC_INITIALIZER(1) static
Definition at line 1011 of file qsocks5socketengine.cpp.
MaxWriteBufferSize
const int MaxWriteBufferSize = 128*1024 static
Definition at line 66 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::_q_controlSocketBytesWritten(), QSocks5SocketEngine::waitForWrite(), and QSocks5SocketEngine::write().
s5StateToString
QString s5StateToString(QSocks5SocketEnginePrivate::Socks5State) inline static
Definition at line 151 of file qsocks5socketengine.cpp.
Referenced by QSocks5SocketEnginePrivate::_q_controlSocketReadNotification().
 { return QString(); }