Qt 4.8: /src/gui/kernel/qsound.cpp File Reference
qsound.cpp File Reference
#include "qsound.h"
#include "qlist.h"
#include <private/qobject_p.h>
#include "qsound_p.h"
Classes
class QSoundPrivate
Functions
QAuServer * qt_new_audio_server ()
static QAuServer & server ()
Variables
static QList< QAuServer * > * servers =0
Function Documentation
qt_new_audio_server()
QAuServer* qt_new_audio_server ()
Definition at line 181 of file qsound_mac.mm.
Referenced by QAuServer::play(), and server().
 {
     return new QAuServerMac(qApp);
 }
server()
static QAuServer& server () static
Definition at line 79 of file qsound.cpp.
Referenced by QNativeSocketEnginePrivate::checkProxy(), QWSServer::closedown(), RUsbOstComm::Connect(), QAxBase::initializeRemote(), QDeclarativeDebugServer::instance(), QSound::isAvailable(), parseServerList(), QSound::play(), QAuServerQWS::play(), QAuServerQWS::QAuServerQWS(), QSound::QSound(), QVNCDirtyMap::QVNCDirtyMap(), QWSSoundServerPrivate::QWSSoundServerPrivate(), QApplicationPrivate::setScreenTransformation(), QTcpServerConnection::setServer(), QmlOstPlugin::setServer(), SoundPlayProc(), QSound::stop(), QAuServerQWS::stop(), and QDeclarativeDebugServerConnection::~QDeclarativeDebugServerConnection().
 {
     if (!servers) qt_new_audio_server();
     return *servers->first();
 }
Variable Documentation
servers
QList<QAuServer*>* servers =0 static
Definition at line 52 of file qsound.cpp.
Referenced by QAuServer::~QAuServer().