Qt 4.8: /src/gui/kernel/qsound_x11.cpp File Reference
qsound_x11.cpp File Reference
#include "qsound.h"
#include "qhash.h"
#include "qsocketnotifier.h"
#include "qapplication.h"
#include "qsound_p.h"
#include <audio/audiolib.h>
#include <audio/soundlib.h>
#include "qsound_x11.moc"
Classes
class QAuBucketNAS
class QAuServerNAS
class QAuServerNull
Typedefs
typedef QHash< void *, QAuServerNAS * > AuServerHash
Functions
static void callback (AuServer *, AuEventHandlerRec *, AuEvent *e, AuPointer p)
static AuBool eventPred (AuServer *, AuEvent *e, AuPointer p)
QAuServer * qt_new_audio_server ()
Variables
static AuServerHash * inprogress =0
static AuServer * nas =0
Typedef Documentation
AuServerHash
typedef QHash<void*,QAuServerNAS*> AuServerHash
Definition at line 144 of file qsound_x11.cpp.
Function Documentation
callback()
static void callback (AuServer * , AuEventHandlerRec * , AuEvent * e, AuPointer p) static
Definition at line 170 of file qsound_x11.cpp.
Referenced by QSegfaultHandler::crashHandler(), QDeclarativeTypeData::done(), QDeclarativeTypeData::downloadProgressChanged(), QXmlQueryPrivate::dynamicContext(), QAuServerNAS::play(), qmlsqldatabase_change_version(), qmlsqldatabase_transaction_shared(), qwsEventSourceDispatch(), QRasterPaintEnginePrivate::rasterize(), QMeeGoGraphicsSystem::registerSwitchCallback(), and x11EventSourceDispatch().
 {
     if (inprogress->contains(p) && e) {
         if (e->type==AuEventTypeElementNotify &&
                     e->auelementnotify.kind==AuElementNotifyKindState) {
             if (e->auelementnotify.cur_state == AuStateStop) {
                 AuServerHash::Iterator it = inprogress->find(p);
                 if (it != inprogress->end())
                     (*it)->setDone((QSound*)p);
             }
         }
     }
 }
eventPred()
static AuBool eventPred (AuServer * , AuEvent * e, AuPointer p) static
Definition at line 62 of file qsound_x11.cpp.
Referenced by QAuBucketNAS::~QAuBucketNAS().
 {
     if (e && (e->type == AuEventTypeElementNotify)) {
         if (e->auelementnotify.flow == *((AuFlowID *)p))
             return true;
     }
     return false;
 }
qt_new_audio_server()
QAuServer* qt_new_audio_server ()
Definition at line 282 of file qsound_x11.cpp.
Referenced by QAuServer::play(), and server().
 {
 #ifndef QT_NO_NAS
     QAuServer* s = new QAuServerNAS(qApp);
     if (s->okay())
         return s;
     else
         delete s;
 #endif
     return new QAuServerNull(qApp);
 }
Variable Documentation
inprogress
AuServerHash* inprogress =0 static
Definition at line 145 of file qsound_x11.cpp.
nas
AuServer* nas =0 static
Definition at line 60 of file qsound_x11.cpp.
Referenced by QAuServerNAS::dataReceived(), QAuServerNAS::init(), QAuServerNAS::okay(), QAuServerNAS::play(), QAuServerNAS::QAuServerNAS(), QAuServerNAS::setDone(), QAuServerNAS::stop(), QAuBucketNAS::~QAuBucketNAS(), and QAuServerNAS::~QAuServerNAS().