Qt 4.8: /src/sql/drivers/db2/qsql_db2.cpp File Reference
qsql_db2.cpp File Reference
#include "qsql_db2.h"
#include <qcoreapplication.h>
#include <qdatetime.h>
#include <qsqlfield.h>
#include <qsqlerror.h>
#include <qsqlindex.h>
#include <qsqlrecord.h>
#include <qstringlist.h>
#include <qvarlengtharray.h>
#include <qvector.h>
#include <QDebug>
#include <sqlcli1.h>
#include <string.h>
Classes
class QDB2DriverPrivate
class QDB2ResultPrivate
Macros
#define UNICODE
Functions
static QString qDB2Warn (const QDB2DriverPrivate *d)
static QString qDB2Warn (const QDB2ResultPrivate *d)
static QVariant::Type qDecodeDB2Type (SQLSMALLINT sqltype)
static QString qFromTChar (SQLTCHAR *str)
static SQLBIGINT qGetBigIntData (SQLHANDLE hStmt, int column, bool &isNull)
static QByteArray qGetBinaryData (SQLHANDLE hStmt, int column, SQLINTEGER &lengthIndicator, bool &isNull)
static double qGetDoubleData (SQLHANDLE hStmt, int column, bool &isNull)
static int qGetIntData (SQLHANDLE hStmt, int column, bool &isNull)
static QString qGetStringData (SQLHANDLE hStmt, int column, int colSize, bool &isNull)
static QSqlError qMakeError (const QString &err, QSqlError::ErrorType type, const QDB2DriverPrivate *p)
static QSqlError qMakeError (const QString &err, QSqlError::ErrorType type, const QDB2ResultPrivate *p)
static QSqlField qMakeFieldInfo (const QDB2ResultPrivate *d, int i)
static QSqlField qMakeFieldInfo (const SQLHANDLE hStmt)
static bool qMakeStatement (QDB2ResultPrivate *d, bool forwardOnly, bool setForwardOnly=true)
static void qSplitTableQualifier (const QString &qualifier, QString *catalog, QString *schema, QString *table)
static void qSqlWarning (const QString &message, const QDB2DriverPrivate *d)
static void qSqlWarning (const QString &message, const QDB2ResultPrivate *d)
static SQLTCHAR * qToTChar (const QString &str)
static QString qWarnDB2Handle (int handleType, SQLHANDLE handle)
Variables
static const int COLNAMESIZE = 255
static const SQLSMALLINT qParamType [4] = { SQL_PARAM_INPUT, SQL_PARAM_INPUT, SQL_PARAM_OUTPUT, SQL_PARAM_INPUT_OUTPUT }
Macro Definition Documentation
UNICODE
#define UNICODE
Definition at line 62 of file qsql_db2.cpp.
Referenced by QODBCDriver::open(), QODBCDriver::primaryIndex(), qGetODBCVersion(), QODBCDriver::record(), and QODBCDriver::tables().
Function Documentation
qDB2Warn() [1/2]
static QString qDB2Warn (const QDB2DriverPrivate * d) static
Definition at line 142 of file qsql_db2.cpp.
Referenced by QDB2Result::exec(), qMakeError(), and qSqlWarning().
 {
     return (qWarnDB2Handle(SQL_HANDLE_ENV, d->hEnv) + QLatin1Char(' ')
              + qWarnDB2Handle(SQL_HANDLE_DBC, d->hDbc));
 }
qDB2Warn() [2/2]
static QString qDB2Warn (const QDB2ResultPrivate * d) static
Definition at line 148 of file qsql_db2.cpp.
 {
     return (qWarnDB2Handle(SQL_HANDLE_ENV, d->dp->hEnv) + QLatin1Char(' ')
              + qWarnDB2Handle(SQL_HANDLE_DBC, d->dp->hDbc)
              + qWarnDB2Handle(SQL_HANDLE_STMT, d->hStmt));
 }
qDecodeDB2Type()
static QVariant::Type qDecodeDB2Type (SQLSMALLINT sqltype) static
Definition at line 179 of file qsql_db2.cpp.
Referenced by qMakeFieldInfo().
 {
     QVariant::Type type = QVariant::Invalid;
     switch (sqltype) {
     case SQL_REAL:
     case SQL_FLOAT:
     case SQL_DOUBLE:
     case SQL_DECIMAL:
     case SQL_NUMERIC:
         type = QVariant::Double;
         break;
     case SQL_SMALLINT:
     case SQL_INTEGER:
     case SQL_BIT:
     case SQL_TINYINT:
         type = QVariant::Int;
         break;
     case SQL_BIGINT:
         type = QVariant::LongLong;
         break;
     case SQL_BLOB:
     case SQL_BINARY:
     case SQL_VARBINARY:
     case SQL_LONGVARBINARY:
     case SQL_CLOB:
     case SQL_DBCLOB:
         type = QVariant::ByteArray;
         break;
     case SQL_DATE:
     case SQL_TYPE_DATE:
         type = QVariant::Date;
         break;
     case SQL_TIME:
     case SQL_TYPE_TIME:
         type = QVariant::Time;
         break;
     case SQL_TIMESTAMP:
     case SQL_TYPE_TIMESTAMP:
         type = QVariant::DateTime;
         break;
     case SQL_WCHAR:
     case SQL_WVARCHAR:
     case SQL_WLONGVARCHAR:
     case SQL_CHAR:
     case SQL_VARCHAR:
     case SQL_LONGVARCHAR:
         type = QVariant::String;
         break;
     default:
         type = QVariant::ByteArray;
         break;
     }
     return type;
 }
qFromTChar()
static QString qFromTChar (SQLTCHAR * str) static
Definition at line 110 of file qsql_db2.cpp.
Referenced by qGetStringData(), qMakeFieldInfo(), and qWarnDB2Handle().
 {
     return QString((const QChar *)str);
 }
qGetBigIntData()
static SQLBIGINT qGetBigIntData (SQLHANDLE hStmt, int column, bool & isNull) static
Definition at line 307 of file qsql_db2.cpp.
Referenced by QDB2Result::data().
 {
     SQLBIGINT lngbuf = Q_INT64_C(0);
     isNull = false;
     SQLINTEGER lengthIndicator = 0;
     SQLRETURN r = SQLGetData(hStmt,
                               column+1,
                               SQL_C_SBIGINT,
                               (SQLPOINTER) &lngbuf,
                               0,
                               &lengthIndicator);
     if ((r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO) || lengthIndicator == SQL_NULL_DATA)
         isNull = true;
     return lngbuf;
 }
qGetBinaryData()
static QByteArray qGetBinaryData (SQLHANDLE hStmt, int column, SQLINTEGER & lengthIndicator, bool & isNull) static
Definition at line 364 of file qsql_db2.cpp.
Referenced by QDB2Result::data().
 {
     QByteArray fieldVal;
     SQLSMALLINT colNameLen;
     SQLSMALLINT colType;
     SQLUINTEGER colSize;
     SQLSMALLINT colScale;
     SQLSMALLINT nullable;
     SQLRETURN r = SQL_ERROR;
     SQLTCHAR colName[COLNAMESIZE];
     r = SQLDescribeCol(hStmt,
                         column+1,
                         colName,
                         COLNAMESIZE,
                         &colNameLen,
                         &colType,
                         &colSize,
                         &colScale,
                         &nullable);
     if (r != SQL_SUCCESS)
         qWarning("qGetBinaryData: Unable to describe column %d", column);
     // SQLDescribeCol may return 0 if size cannot be determined
     if (!colSize)
         colSize = 255;
     else if (colSize > 65536) // read the field in 64 KB chunks
         colSize = 65536;
     char * buf = new char[colSize];
     while (true) {
         r = SQLGetData(hStmt,
                         column+1,
                         colType == SQL_DBCLOB ? SQL_C_CHAR : SQL_C_BINARY,
                         (SQLPOINTER) buf,
                         colSize,
                         &lengthIndicator);
         if (r == SQL_SUCCESS || r == SQL_SUCCESS_WITH_INFO) {
             if (lengthIndicator == SQL_NULL_DATA) {
                 isNull = true;
                 break;
             } else {
                 int rSize;
                 r == SQL_SUCCESS ? rSize = lengthIndicator : rSize = colSize;
                 if (lengthIndicator == SQL_NO_TOTAL) // size cannot be determined
                     rSize = colSize;
                 fieldVal.append(QByteArray(buf, rSize));
                 if (r == SQL_SUCCESS) // the whole field was read in one chunk
                     break;
             }
         } else {
             break;
         }
     }
     delete [] buf;
     return fieldVal;
 }
qGetDoubleData()
static double qGetDoubleData (SQLHANDLE hStmt, int column, bool & isNull) static
Definition at line 288 of file qsql_db2.cpp.
Referenced by QDB2Result::data().
 {
     SQLDOUBLE dblbuf;
     isNull = false;
     SQLINTEGER lengthIndicator = 0;
     SQLRETURN r = SQLGetData(hStmt,
                               column+1,
                               SQL_C_DOUBLE,
                               (SQLPOINTER) &dblbuf,
                               0,
                               &lengthIndicator);
     if ((r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO) || lengthIndicator == SQL_NULL_DATA) {
         isNull = true;
         return 0.0;
     }
     return (double) dblbuf;
 }
qGetIntData()
static int qGetIntData (SQLHANDLE hStmt, int column, bool & isNull) static
Definition at line 270 of file qsql_db2.cpp.
Referenced by QDB2Result::data(), and qMakeFieldInfo().
 {
     SQLINTEGER intbuf;
     isNull = false;
     SQLINTEGER lengthIndicator = 0;
     SQLRETURN r = SQLGetData(hStmt,
                               column + 1,
                               SQL_C_SLONG,
                               (SQLPOINTER) &intbuf,
                               0,
                               &lengthIndicator);
     if ((r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO) || lengthIndicator == SQL_NULL_DATA) {
         isNull = true;
         return 0;
     }
     return int(intbuf);
 }
qGetStringData()
static QString qGetStringData (SQLHANDLE hStmt, int column, int colSize, bool & isNull) static
Definition at line 324 of file qsql_db2.cpp.
Referenced by QDB2Result::data(), QDB2Driver::primaryIndex(), qMakeFieldInfo(), and QDB2Driver::tables().
 {
     QString     fieldVal;
     SQLRETURN   r = SQL_ERROR;
     SQLINTEGER  lengthIndicator = 0;
     if (colSize <= 0)
         colSize = 255;
     else if (colSize > 65536) // limit buffer size to 64 KB
         colSize = 65536;
     else
         colSize++; // make sure there is room for more than the 0 termination
     SQLTCHAR* buf = new SQLTCHAR[colSize];
     while (true) {
         r = SQLGetData(hStmt,
                         column + 1,
                         SQL_C_WCHAR,
                         (SQLPOINTER)buf,
                         colSize * sizeof(SQLTCHAR),
                         &lengthIndicator);
         if (r == SQL_SUCCESS || r == SQL_SUCCESS_WITH_INFO) {
             if (lengthIndicator == SQL_NULL_DATA || lengthIndicator == SQL_NO_TOTAL) {
                 fieldVal.clear();
                 isNull = true;
                 break;
             }
             fieldVal += qFromTChar(buf);
         } else if (r == SQL_NO_DATA) {
             break;
         } else {
             qWarning("qGetStringData: Error while fetching data (%d)", r);
             fieldVal.clear();
             break;
         }
     }
     delete[] buf;
     return fieldVal;
 }
qMakeError() [1/2]
static QSqlError qMakeError (const QString & err, QSqlError::ErrorType type, const QDB2DriverPrivate * p) static
Definition at line 167 of file qsql_db2.cpp.
Referenced by QDB2Driver::commitTransaction(), QDB2Result::exec(), QDB2Result::fetch(), QDB2Result::fetchFirst(), QDB2Result::fetchNext(), QDB2Result::nextResult(), QDB2Driver::open(), QDB2Result::prepare(), QDB2Result::reset(), QDB2Driver::rollbackTransaction(), and QDB2Driver::setAutoCommit().
 {
     return QSqlError(QLatin1String("QDB2: ") + err, qDB2Warn(p), type);
 }
qMakeError() [2/2]
static QSqlError qMakeError (const QString & err, QSqlError::ErrorType type, const QDB2ResultPrivate * p) static
Definition at line 173 of file qsql_db2.cpp.
 {
     return QSqlError(QLatin1String("QDB2: ") + err, qDB2Warn(p), type);
 }
qMakeFieldInfo() [1/2]
static QSqlField qMakeFieldInfo (const QDB2ResultPrivate * d, int i) static
Definition at line 234 of file qsql_db2.cpp.
Referenced by QDB2Result::exec(), QDB2Result::nextResult(), QDB2Driver::record(), and QDB2Result::reset().
 {
     SQLSMALLINT colNameLen;
     SQLSMALLINT colType;
     SQLUINTEGER colSize;
     SQLSMALLINT colScale;
     SQLSMALLINT nullable;
     SQLRETURN r = SQL_ERROR;
     SQLTCHAR colName[COLNAMESIZE];
     r = SQLDescribeCol(d->hStmt,
                         i+1,
                         colName,
                         (SQLSMALLINT) COLNAMESIZE,
                         &colNameLen,
                         &colType,
                         &colSize,
                         &colScale,
                         &nullable);
     if (r != SQL_SUCCESS) {
         qSqlWarning(QString::fromLatin1("qMakeFieldInfo: Unable to describe column %1").arg(i), d);
         return QSqlField();
     }
     QSqlField f(qFromTChar(colName), qDecodeDB2Type(colType));
     // nullable can be SQL_NO_NULLS, SQL_NULLABLE or SQL_NULLABLE_UNKNOWN
     if (nullable == SQL_NO_NULLS)
         f.setRequired(true);
     else if (nullable == SQL_NULLABLE)
         f.setRequired(false);
     // else required is unknown
     f.setLength(colSize == 0 ? -1 : int(colSize));
     f.setPrecision(colScale == 0 ? -1 : int(colScale));
     f.setSqlType(int(colType));
     return f;
 }
qMakeFieldInfo() [2/2]
static QSqlField qMakeFieldInfo (const SQLHANDLE hStmt) static
Definition at line 453 of file qsql_db2.cpp.
 {
     bool isNull;
     int type = qGetIntData(hStmt, 4, isNull);
     QSqlField f(qGetStringData(hStmt, 3, -1, isNull), qDecodeDB2Type(type));
     int required = qGetIntData(hStmt, 10, isNull); // nullable-flag
     // required can be SQL_NO_NULLS, SQL_NULLABLE or SQL_NULLABLE_UNKNOWN
     if (required == SQL_NO_NULLS)
         f.setRequired(true);
     else if (required == SQL_NULLABLE)
         f.setRequired(false);
     // else we don't know.
     f.setLength(qGetIntData(hStmt, 6, isNull)); // column size
     f.setPrecision(qGetIntData(hStmt, 8, isNull)); // precision
     f.setSqlType(type);
     return f;
 }
qMakeStatement()
static bool qMakeStatement (QDB2ResultPrivate * d, bool forwardOnly, bool setForwardOnly = true) static
Definition at line 471 of file qsql_db2.cpp.
Referenced by QDB2Result::exec(), QDB2Result::prepare(), and QDB2Result::reset().
 {
     SQLRETURN r;
     if (!d->hStmt) {
         r = SQLAllocHandle(SQL_HANDLE_STMT,
                             d->dp->hDbc,
                             &d->hStmt);
         if (r != SQL_SUCCESS) {
             qSqlWarning(QLatin1String("QDB2Result::reset: Unable to allocate statement handle"), d);
             return false;
         }
     } else {
         r = SQLFreeStmt(d->hStmt, SQL_CLOSE);
         if (r != SQL_SUCCESS) {
             qSqlWarning(QLatin1String("QDB2Result::reset: Unable to close statement handle"), d);
             return false;
         }
     }
     if (!setForwardOnly)
         return true;
     if (forwardOnly) {
         r = SQLSetStmtAttr(d->hStmt,
                             SQL_ATTR_CURSOR_TYPE,
                             (SQLPOINTER) SQL_CURSOR_FORWARD_ONLY,
                             SQL_IS_UINTEGER);
     } else {
         r = SQLSetStmtAttr(d->hStmt,
                             SQL_ATTR_CURSOR_TYPE,
                             (SQLPOINTER) SQL_CURSOR_STATIC,
                             SQL_IS_UINTEGER);
     }
     if (r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO) {
         qSqlWarning(QString::fromLatin1("QDB2Result::reset: Unable to set %1 attribute.").arg(
                      forwardOnly ? QLatin1String("SQL_CURSOR_FORWARD_ONLY")
                                  : QLatin1String("SQL_CURSOR_STATIC")), d);
         return false;
     }
     return true;
 }
qSplitTableQualifier()
static void qSplitTableQualifier (const QString & qualifier, QString * catalog, QString * schema, QString * table) static
Definition at line 420 of file qsql_db2.cpp.
Referenced by QDB2Driver::primaryIndex(), and QDB2Driver::record().
 {
     if (!catalog || !schema || !table)
         return;
     QStringList l = qualifier.split(QLatin1Char('.'));
     if (l.count() > 3)
         return; // can't possibly be a valid table qualifier
     int i = 0, n = l.count();
     if (n == 1) {
         *table = qualifier;
     } else {
         for (QStringList::Iterator it = l.begin(); it != l.end(); ++it) {
             if (n == 3) {
                 if (i == 0)
                     *catalog = *it;
                 else if (i == 1)
                     *schema = *it;
                 else if (i == 2)
                     *table = *it;
             } else if (n == 2) {
                 if (i == 0)
                     *schema = *it;
                 else if (i == 1)
                     *table = *it;
             }
             i++;
         }
     }
 }
qSqlWarning() [1/2]
static void qSqlWarning (const QString & message, const QDB2DriverPrivate * d) static
Definition at line 155 of file qsql_db2.cpp.
Referenced by QDB2Driver::close(), QDB2Result::numRowsAffected(), QDB2Driver::open(), QDB2Driver::primaryIndex(), qMakeFieldInfo(), qMakeStatement(), QDB2Driver::record(), QDB2Driver::tables(), and QDB2Result::~QDB2Result().
 {
     qWarning("%s\tError: %s", message.toLocal8Bit().constData(),
                               qDB2Warn(d).toLocal8Bit().constData());
 }
qSqlWarning() [2/2]
static void qSqlWarning (const QString & message, const QDB2ResultPrivate * d) static
Definition at line 161 of file qsql_db2.cpp.
 {
     qWarning("%s\tError: %s", message.toLocal8Bit().constData(),
                               qDB2Warn(d).toLocal8Bit().constData());
 }
qToTChar()
static SQLTCHAR* qToTChar (const QString & str) static
Definition at line 117 of file qsql_db2.cpp.
Referenced by QDB2Driver::open(), QDB2Result::prepare(), QDB2Driver::primaryIndex(), QDB2Driver::record(), QDB2Result::reset(), and QDB2Driver::tables().
 {
     return (SQLTCHAR*)str.utf16();
 }
qWarnDB2Handle()
static QString qWarnDB2Handle (int handleType, SQLHANDLE handle) static
Definition at line 122 of file qsql_db2.cpp.
Referenced by qDB2Warn().
 {
     SQLINTEGER nativeCode;
     SQLSMALLINT msgLen;
     SQLRETURN r = SQL_ERROR;
     SQLTCHAR state[SQL_SQLSTATE_SIZE + 1];
     SQLTCHAR description[SQL_MAX_MESSAGE_LENGTH];
     r = SQLGetDiagRec(handleType,
                        handle,
                        1,
                        (SQLTCHAR*) state,
                        &nativeCode,
                        (SQLTCHAR*) description,
                        SQL_MAX_MESSAGE_LENGTH - 1, /* in bytes, not in characters */
                        &msgLen);
     if (r == SQL_SUCCESS || r == SQL_SUCCESS_WITH_INFO)
         return QString(qFromTChar(description));
     return QString();
 }
Variable Documentation
COLNAMESIZE
const int COLNAMESIZE = 255 static
Definition at line 70 of file qsql_db2.cpp.
Referenced by qGetBinaryData(), and qMakeFieldInfo().
qParamType
const SQLSMALLINT qParamType[4] = { SQL_PARAM_INPUT, SQL_PARAM_INPUT, SQL_PARAM_OUTPUT, SQL_PARAM_INPUT_OUTPUT } static
Definition at line 71 of file qsql_db2.cpp.
Referenced by QDB2Result::exec().