Qt 4.8: /src/sql/drivers/symsql/qsql_symsql.cpp File Reference
qsql_symsql.cpp File Reference
#include "qsql_symsql.h"
#include <qcoreapplication.h>
#include <qvariant.h>
#include <qsqlerror.h>
#include <qsqlfield.h>
#include <qsqlindex.h>
#include <qsqlquery.h>
#include <qstringlist.h>
#include <qvector.h>
#include <qdebug.h>
#include "../../../corelib/kernel/qcore_symbian_p.h"
#include <qt_windows.h>
#include <sqldb.h>
#include <e32capability.h>
Classes
class QSymSQLDriverPrivate
class QSymSQLResultPrivate
Macros
#define SYMBIAN_ENABLE_PUBLIC_PLATFORM_HEADER_SPLIT
Functions
static QString _q_escapeIdentifier (const QString &identifier)
static QSqlError gMakeErrorOpen (const QString &descr, QSqlError::ErrorType type, TInt errorCode)
bool qExtractSecurityPolicyFromString (const QString &string, TSecurityPolicy &policy)
static QVariant::Type qGetColumnType (const TSqlColumnType coltype)
static QVariant::Type qGetColumnType (const QString &tpName)
static QSqlError qMakeError (RSqlDatabase &access, const QString &descr, QSqlError::ErrorType type, int errorCode=-1)
TCapability qMatchCapStr (QString &str)
Converts capability string to TCapability.
Variables
const QString fieldSeparator (QLatin1String(","))
const char * qCapabilityNames [ECapability_Limit]
const char qCapabilityNone [] = "None"
const QString valueSeparator (QLatin1String("="))
Macro Definition Documentation
SYMBIAN_ENABLE_PUBLIC_PLATFORM_HEADER_SPLIT
#define SYMBIAN_ENABLE_PUBLIC_PLATFORM_HEADER_SPLIT
Definition at line 45 of file qsql_symsql.cpp.
Function Documentation
_q_escapeIdentifier()
static QString _q_escapeIdentifier (const QString & identifier) static
Definition at line 102 of file qsql_symsql.cpp.
Referenced by qExtractSecurityPolicyFromString().
 {
     QString res = identifier;
     if (!identifier.isEmpty()
             && identifier.left(1) != QString(QLatin1Char('"'))
             && identifier.right(1) != QString(QLatin1Char('"'))) {
         res.replace(QLatin1Char('"'), QLatin1String("\"\""));
         res.prepend(QLatin1Char('"')).append(QLatin1Char('"'));
         res.replace(QLatin1Char('.'), QLatin1String("\".\""));
     }
     return res;
 }
gMakeErrorOpen()
static QSqlError gMakeErrorOpen (const QString & descr, QSqlError::ErrorType type, TInt errorCode) static
Definition at line 161 of file qsql_symsql.cpp.
Referenced by qExtractSecurityPolicyFromString().
 {
     return QSqlError(descr, QLatin1String(""), type, errorCode);
 }
qExtractSecurityPolicyFromString()
bool qExtractSecurityPolicyFromString (const QString & string, TSecurityPolicy & policy)
Definition at line 696 of file qsql_symsql.cpp.
 {
     int startPos = string.indexOf(QLatin1Char('='));
     QStringList values;
     bool ret = false;
     if (startPos == -1) {
         values = string.split(QLatin1Char(','), QString::SkipEmptyParts);
     } else {
         values = string.mid(startPos + 1).split(QLatin1Char(','), QString::SkipEmptyParts);
     }
     if (values.count() > 0) {
         const QString findVid(QLatin1String("vid["));
         const QString findSid(QLatin1String("sid["));
         const int MaxCapCount = 7;
         const int VidMaxCount = 3;
         const int SidMaxCount = 3;
         TCapability capList[MaxCapCount] = { ECapability_None,ECapability_None,ECapability_None,
                                     ECapability_None,ECapability_None,ECapability_None,ECapability_None };
         bool isVID = false;
         bool isSID = false;
         QString idString(QLatin1String(""));
         int maxAllowed = MaxCapCount;
         if (values[0].contains(findVid, Qt::CaseInsensitive)) {
             idString = values[0].remove(findVid, Qt::CaseInsensitive);
             idString = idString.remove(QLatin1Char(']'));
             values.removeAt(0);
             isVID = true;
             maxAllowed = VidMaxCount;
         } else if (values[0].contains(findSid, Qt::CaseInsensitive)) {
             idString = values[0].remove(findSid, Qt::CaseInsensitive);
             idString = idString.remove(QLatin1Char(']'));
             values.removeAt(0);
             isSID = true;
             maxAllowed = SidMaxCount;
         }
         if (values.count() <= maxAllowed) {
             bool wasSuccesful = true;
             for (int i = 0; i < values.count(); i++) {
                 capList[i] = qMatchCapStr(values[i]);
                 if (capList[i] == ECapability_HardLimit) {
                     wasSuccesful = false;
                     break;
                 }
             }
             if (wasSuccesful) {
                 if (isVID || isSID){
                     bool ok = true;
                     quint32 id = idString.toUInt(&ok, 16);
                     if (ok) {
                         if (isVID) {
                             TVendorId vid(id);
                             policy = TSecurityPolicy(vid, capList[0], capList[1], capList[2]);
                         } else {
                             TSecureId sid(id);
                             policy = TSecurityPolicy(sid, capList[0], capList[1], capList[2]);
                         }
                         ret = true; //Everything is fine
                     }
                 } else {
                     policy = TSecurityPolicy(capList[0], capList[1], capList[2], capList[3],
                                         capList[4], capList[5], capList[6]);
                     ret = true;  //Everything is fine
                 }
             }
         }
     }
     return ret;
 }
qGetColumnType() [1/2]
static QVariant::Type qGetColumnType (const TSqlColumnType coltype) static
Definition at line 115 of file qsql_symsql.cpp.
Referenced by QSymSQLResultPrivate::initColumns(), and qExtractSecurityPolicyFromString().
 {
     switch(coltype){
     case ESqlInt:
     case ESqlInt64:
         return QVariant::Int;
     case ESqlReal:
         return QVariant::Double;
     case ESqlBinary:
         return QVariant::ByteArray;
     case ESqlText:
     case ESqlNull:
     default:
         return QVariant::String;
     }
 }
qGetColumnType() [2/2]
static QVariant::Type qGetColumnType (const QString & tpName) static
Definition at line 132 of file qsql_symsql.cpp.
 {
     const QString typeName = tpName.toLower();
     if (typeName == QLatin1String("integer")
         || typeName == QLatin1String("int"))
         return QVariant::Int;
     if (typeName == QLatin1String("double")
         || typeName == QLatin1String("float")
         || typeName == QLatin1String("real")
         || typeName.startsWith(QLatin1String("numeric")))
         return QVariant::Double;
     if (typeName == QLatin1String("blob"))
         return QVariant::ByteArray;
     return QVariant::String;
 }
qMakeError()
static QSqlError qMakeError (RSqlDatabase & access, const QString & descr, QSqlError::ErrorType type, int errorCode = -1) static
Definition at line 149 of file qsql_symsql.cpp.
Referenced by QSymSQLResult::exec(), QSymSQLResultPrivate::fetchNext(), QSymSQLResultPrivate::initColumns(), and QSymSQLResult::prepare().
 {
     return QSqlError(descr,
                      QString::fromUtf16(static_cast<const ushort *>(access.LastErrorMessage().Ptr())),
                      type,
                      errorCode);
 }
qMatchCapStr()
TCapability qMatchCapStr (QString & str)
Converts capability string to TCapability.
Definition at line 677 of file qsql_symsql.cpp.
Referenced by qExtractSecurityPolicyFromString().
 {
     TCapability cap = ECapability_HardLimit;
     for (int i = 0; i < static_cast<int>(ECapability_Limit); i++) {
         if (str.compare(QLatin1String(qCapabilityNames[i]), Qt::CaseInsensitive) == 0) {
             cap = static_cast<TCapability>(i);
             break;
         }
     }
     //Special case, we allow ECapability_None to be defined
     if (cap == ECapability_HardLimit
         && str.compare(QLatin1String(qCapabilityNone), Qt::CaseInsensitive) == 0)
         cap = ECapability_None;
     return cap;
 }
Variable Documentation
fieldSeparator
const QString fieldSeparator(QLatin1String(","))
qCapabilityNames
const char* qCapabilityNames[ECapability_Limit]
Initial value:
=
{
    "TCB",
    "CommDD",
    "PowerMgmt",
    "MultimediaDD",
    "ReadDeviceData",
    "WriteDeviceData",
    "DRM",
    "TrustedUI",
    "ProtServ",
    "DiskAdmin",
    "NetworkControl",
    "AllFiles",
    "SwEvent",
    "NetworkServices",
    "LocalServices",
    "ReadUserData",
    "WriteUserData",
    "Location",
    "SurroundingsDD",
    "UserEnvironment"
}
Definition at line 67 of file qsql_symsql.cpp.
Referenced by qMatchCapStr().
qCapabilityNone
const char qCapabilityNone[] = "None"
Definition at line 91 of file qsql_symsql.cpp.
Referenced by qMatchCapStr().
valueSeparator
const QString valueSeparator(QLatin1String("="))