Qt 4.8: /src/sql/drivers/psql/qsql_psql.cpp File Reference
qsql_psql.cpp File Reference
#include "qsql_psql.h"
#include <qcoreapplication.h>
#include <qvariant.h>
#include <qdatetime.h>
#include <qregexp.h>
#include <qsqlerror.h>
#include <qsqlfield.h>
#include <qsqlindex.h>
#include <qsqlrecord.h>
#include <qsqlquery.h>
#include <qsocketnotifier.h>
#include <qstringlist.h>
#include <qmutex.h>
#include <libpq-fe.h>
#include <pg_config.h>
#include <stdlib.h>
#include <math.h>
Classes
class QPSQLDriverPrivate
class QPSQLResultPrivate
Macros
#define isinf(x)
#define isnan(x)
#define QABSTIMEOID 702
#define QBOOLOID 16
#define QBYTEAOID 17
#define QCIDOID 29
#define QDATEOID 1082
#define QFLOAT4OID 700
#define QFLOAT8OID 701
#define QINT2OID 21
#define QINT4OID 23
#define QINT8OID 20
#define QNUMERICOID 1700
#define QOIDOID 2278
#define QREGPROCOID 24
#define QRELTIMEOID 703
#define QTIMEOID 1083
#define QTIMESTAMPOID 1114
#define QTIMESTAMPTZOID 1184
#define QTIMETZOID 1266
#define QXIDOID 28
Functions
static int isinf_d (double x)
static int isinf_f (float x)
static int isinf_ld (long double x)
static int isnan_d (double x)
static int isnan_f (float x)
static int isnan_ld (long double x)
template<typename T >
void PQfreemem (T *t, int=0)
static QString qCreateParamString (const QVector< QVariant > boundValues, const QSqlDriver *driver)
static void qDeallocatePreparedStmt (QPSQLResultPrivate *d)
static QVariant::Type qDecodePSQLType (int t)
static QSqlError qMakeError (const QString &err, QSqlError::ErrorType type, const QPSQLDriverPrivate *p, PGresult *result=0)
QString qMakePreparedStmtId ()
static QPSQLDriver::Protocol qMakePSQLVersion (int vMaj, int vMin)
void qPQfreemem (void *buffer)
static QString qQuote (QString s)
static QString qReplacePlaceholderMarkers (const QString &query)
static void qSplitTableName (QString &tablename, QString &schema)
Macro Definition Documentation
isinf
#define isinf (x)
Value:
(sizeof (x) == sizeof (long double) ? isinf_ld (x) \
        : sizeof (x) == sizeof (double) ? isinf_d (x) \
        : isinf_f (x))
Definition at line 74 of file qsql_psql.cpp.
Referenced by QPSQLDriver::formatValue().
isnan
#define isnan (x)
Value:
(sizeof (x) == sizeof (long double) ? isnan_ld (x) \
        : sizeof (x) == sizeof (double) ? isnan_d (x) \
        : isnan_f (x))
Definition at line 64 of file qsql_psql.cpp.
Referenced by QPSQLDriver::formatValue(), isinf_d(), isinf_f(), and isinf_ld().
QABSTIMEOID
#define QABSTIMEOID 702
Definition at line 92 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QBOOLOID
#define QBOOLOID 16
Definition at line 85 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QBYTEAOID
#define QBYTEAOID 17
Definition at line 100 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QCIDOID
#define QCIDOID 29
Definition at line 103 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QDATEOID
#define QDATEOID 1082
Definition at line 94 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QFLOAT4OID
#define QFLOAT4OID 700
Definition at line 90 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QFLOAT8OID
#define QFLOAT8OID 701
Definition at line 91 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QINT2OID
#define QINT2OID 21
Definition at line 87 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QINT4OID
#define QINT4OID 23
Definition at line 88 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QINT8OID
#define QINT8OID 20
Definition at line 86 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QNUMERICOID
#define QNUMERICOID 1700
Definition at line 89 of file qsql_psql.cpp.
Referenced by QPSQLResult::data(), and qDecodePSQLType().
QOIDOID
#define QOIDOID 2278
Definition at line 99 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QREGPROCOID
#define QREGPROCOID 24
Definition at line 101 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QRELTIMEOID
#define QRELTIMEOID 703
Definition at line 93 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QTIMEOID
#define QTIMEOID 1083
Definition at line 95 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QTIMESTAMPOID
#define QTIMESTAMPOID 1114
Definition at line 97 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QTIMESTAMPTZOID
#define QTIMESTAMPTZOID 1184
Definition at line 98 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QTIMETZOID
#define QTIMETZOID 1266
Definition at line 96 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
QXIDOID
#define QXIDOID 28
Definition at line 102 of file qsql_psql.cpp.
Referenced by qDecodePSQLType().
Function Documentation
isinf_d()
static int isinf_d (double x) inline static
Definition at line 79 of file qsql_psql.cpp.
 { return isnan (x - x); }
isinf_f()
static int isinf_f (float x) inline static
Definition at line 78 of file qsql_psql.cpp.
 { return isnan (x - x); }
isinf_ld()
static int isinf_ld (long double x) inline static
Definition at line 80 of file qsql_psql.cpp.
 { return isnan (x - x); }
isnan_d()
static int isnan_d (double x) inline static
Definition at line 69 of file qsql_psql.cpp.
 { return x != x; }
isnan_f()
static int isnan_f (float x) inline static
Definition at line 68 of file qsql_psql.cpp.
 { return x != x; }
isnan_ld()
static int isnan_ld (long double x) inline static
Definition at line 70 of file qsql_psql.cpp.
 { return x != x; }
PQfreemem()
template<typename T > void PQfreemem (T * t, int = 0) inline
Definition at line 108 of file qsql_psql.cpp.
Referenced by qPQfreemem().
 { free(t); }
qCreateParamString()
static QString qCreateParamString (const QVector< QVariant > boundValues, const QSqlDriver * driver) static
Definition at line 552 of file qsql_psql.cpp.
Referenced by QPSQLResult::exec().
 {
     if (boundValues.isEmpty())
         return QString();
     QString params;
     QSqlField f;
     for (int i = 0; i < boundValues.count(); ++i) {
         const QVariant &val = boundValues.at(i);
         f.setType(val.type());
         if (val.isNull())
             f.clear();
         else
             f.setValue(val);
         if(!params.isNull())
             params.append(QLatin1String(", "));
         params.append(driver->formatValue(f));
     }
     return params;
 }
qDeallocatePreparedStmt()
static void qDeallocatePreparedStmt (QPSQLResultPrivate * d) static
Definition at line 285 of file qsql_psql.cpp.
Referenced by QPSQLResult::prepare(), and QPSQLResult::~QPSQLResult().
 {
     const QString stmt = QLatin1String("DEALLOCATE ") + d->preparedStmtId;
     PGresult *result = d->driver->exec(stmt);
     if (PQresultStatus(result) != PGRES_COMMAND_OK)
         qWarning("Unable to free statement: %s", PQerrorMessage(d->driver->connection));
     PQclear(result);
     d->preparedStmtId.clear();
 }
qDecodePSQLType()
static QVariant::Type qDecodePSQLType (int t) static
Definition at line 239 of file qsql_psql.cpp.
Referenced by QPSQLResult::data(), QPSQLDriver::primaryIndex(), QPSQLResult::record(), and QPSQLDriver::record().
 {
     QVariant::Type type = QVariant::Invalid;
     switch (t) {
     case QBOOLOID:
         type = QVariant::Bool;
         break;
     case QINT8OID:
         type = QVariant::LongLong;
         break;
     case QINT2OID:
     case QINT4OID:
     case QOIDOID:
     case QREGPROCOID:
     case QXIDOID:
     case QCIDOID:
         type = QVariant::Int;
         break;
     case QNUMERICOID:
     case QFLOAT4OID:
     case QFLOAT8OID:
         type = QVariant::Double;
         break;
     case QABSTIMEOID:
     case QRELTIMEOID:
     case QDATEOID:
         type = QVariant::Date;
         break;
     case QTIMEOID:
     case QTIMETZOID:
         type = QVariant::Time;
         break;
     case QTIMESTAMPOID:
     case QTIMESTAMPTZOID:
         type = QVariant::DateTime;
         break;
     case QBYTEAOID:
         type = QVariant::ByteArray;
         break;
     default:
         type = QVariant::String;
         break;
     }
     return type;
 }
qMakeError()
static QSqlError qMakeError (const QString & err, QSqlError::ErrorType type, const QPSQLDriverPrivate * p, PGresult * result = 0) static
Definition at line 205 of file qsql_psql.cpp.
Referenced by QPSQLDriver::beginTransaction(), QPSQLDriver::commitTransaction(), QPSQLDriver::open(), QPSQLResult::prepare(), QPSQLResultPrivate::processResults(), QPSQLDriver::rollbackTransaction(), QPSQLDriver::subscribeToNotificationImplementation(), and QPSQLDriver::unsubscribeFromNotificationImplementation().
 {
     const char *s = PQerrorMessage(p->connection);
     QString msg = p->isUtf8 ? QString::fromUtf8(s) : QString::fromLocal8Bit(s);
     if (result) {
       const char *sCode = PQresultErrorField(result, PG_DIAG_SQLSTATE);
       msg += QString::fromLatin1("(%1)").arg(QString::fromLatin1(sCode));
     }
     return QSqlError(QLatin1String("QPSQL: ") + err, msg, type);
 }
qMakePreparedStmtId()
QString qMakePreparedStmtId ()
Definition at line 575 of file qsql_psql.cpp.
Referenced by QPSQLResult::prepare().
 {
     qMutex()->lock();
     static unsigned int qPreparedStmtCount = 0;
     QString id = QLatin1String("qpsqlpstmt_") + QString::number(++qPreparedStmtCount, 16);
     qMutex()->unlock();
     return id;
 }
qMakePSQLVersion()
static QPSQLDriver::Protocol qMakePSQLVersion (int vMaj, int vMin) static
Definition at line 667 of file qsql_psql.cpp.
Referenced by QPSQLDriverPrivate::getPSQLVersion().
 {
     switch (vMaj) {
     case 6:
         return QPSQLDriver::Version6;
     case 7:
     {
         switch (vMin) {
         case 1:
             return QPSQLDriver::Version71;
         case 3:
             return QPSQLDriver::Version73;
         case 4:
             return QPSQLDriver::Version74;
         default:
             return QPSQLDriver::Version7;
         }
         break;
     }
     case 8:
     {
         switch (vMin) {
         case 1:
             return QPSQLDriver::Version81;
         case 2:
             return QPSQLDriver::Version82;
         case 3:
             return QPSQLDriver::Version83;
         case 4:
             return QPSQLDriver::Version84;
         default:
             return QPSQLDriver::Version8;
         }
         break;
     }
     case 9:
         return QPSQLDriver::Version9;
         break;
     default:
         break;
     }
     return QPSQLDriver::VersionUnknown;
 }
qPQfreemem()
void qPQfreemem (void * buffer) inline
Definition at line 115 of file qsql_psql.cpp.
Referenced by QPSQLDriver::_q_handleNotification(), QPSQLResult::data(), and QPSQLDriver::formatValue().
 {
     PQfreemem(buffer);
 }
qQuote()
static QString qQuote (QString s) static
Definition at line 828 of file qsql_psql.cpp.
Referenced by QPSQLDriver::open().
 {
     s.replace(QLatin1Char('\\'), QLatin1String("\\\\"));
     s.replace(QLatin1Char('\''), QLatin1String("\\'"));
     s.append(QLatin1Char('\'')).prepend(QLatin1Char('\''));
     return s;
 }
qReplacePlaceholderMarkers()
static QString qReplacePlaceholderMarkers (const QString & query) static
Definition at line 529 of file qsql_psql.cpp.
Referenced by QPSQLResult::prepare().
 {
     const int originalLength = query.length();
     bool inQuote = false;
     int markerIdx = 0;
     QString result;
     result.reserve(originalLength + 23);
     for (int i = 0; i < originalLength; ++i) {
         const QChar ch = query.at(i);
         if (ch == QLatin1Char('?') && !inQuote) {
             result += QLatin1Char('$');
             result += QString::number(++markerIdx);
         } else {
             if (ch == QLatin1Char('\''))
                 inQuote = !inQuote;
             result += ch;
         }
     }
     result.squeeze();
     return result;
 }
qSplitTableName()
static void qSplitTableName (QString & tablename, QString & schema) static
Definition at line 996 of file qsql_psql.cpp.
Referenced by QPSQLDriver::primaryIndex(), and QPSQLDriver::record().
 {
     int dot = tablename.indexOf(QLatin1Char('.'));
     if (dot == -1)
         return;
     schema = tablename.left(dot);
     tablename = tablename.mid(dot + 1);
 }