Qt 4.8: /src/sql/drivers/oci/qsql_oci.cpp File Reference
qsql_oci.cpp File Reference
#include "qsql_oci.h"
#include <qcoreapplication.h>
#include <qvariant.h>
#include <qdatetime.h>
#include <qmetatype.h>
#include <qregexp.h>
#include <qshareddata.h>
#include <qsqlerror.h>
#include <qsqlfield.h>
#include <qsqlindex.h>
#include <qsqlquery.h>
#include <qstringlist.h>
#include <qvarlengtharray.h>
#include <qvector.h>
#include <qdebug.h>
#include <oci.h>
#include <stdlib.h>
Classes
struct OraFieldInfo
struct QOCIBatchCleanupHandler
struct QOCIBatchColumn
class QOCICols
class QOCICols::OraFieldInf
struct QOCIDriverPrivate
struct QOCIResultPrivate
class QOCIRowId
Macros
#define QOCI_DYNAMIC_CHUNK_SIZE 65535
#define QOCI_PREFETCH_MEM 10240
#define QOCI_THREADED
Typedefs
typedef QVarLengthArray< sb2, 32 > IndicatorArray
typedef QSharedDataPointer< QOCIRowId > QOCIRowIdPointer
typedef QVarLengthArray< ub2, 32 > SizeArray
Enumerations
enum { QOCIEncoding = 2002 }
Functions
QVariant::Type qDecodeOCIType (const QString &ocitype, QSql::NumericalPrecisionPolicy precisionPolicy)
QVariant::Type qDecodeOCIType (int ocitype, QSql::NumericalPrecisionPolicy precisionPolicy)
static QSqlField qFromOraInf (const OraFieldInfo &ofi)
static QDateTime qMakeDate (const char *oraDate)
static QSqlError qMakeError (const QString &errString, QSqlError::ErrorType type, OCIError *err)
static qlonglong qMakeLongLong (const char *ociNumber, OCIError *err)
static QByteArray qMakeOCINumber (const qlonglong &ll, OCIError *err)
Convert qlonglong to the internal Oracle OCINumber format.
static QByteArray qMakeOCINumber (const qulonglong &ull, OCIError *err)
Convert qulonglong to the internal Oracle OCINumber format.
static QByteArray qMakeOraDate (const QDateTime &dt)
Convert QDateTime to the internal Oracle DATE format NB! It does not handle BCE dates.
static qulonglong qMakeULongLong (const char *ociNumber, OCIError *err)
static int qOraErrorNumber (OCIError *err)
static void qOraOutValue (QVariant &value, QList< QByteArray > &storage, OCIError *err)
static QString qOraWarn (OCIError *err, int *errorCode=0)
static void qOraWarning (const char *msg, OCIError *err)
static void qParseOpts (const QString &options, QOCIDriverPrivate *d)
template<class T , int sz>
int qReadLob (T &buf, const QOCIResultPrivate *d, OCILobLocator *lob)
void qSplitTableAndOwner (const QString &tname, QString *tbl, QString *owner)
Variables
static const ub2 qOraCharset = OCI_UCS2ID
Macro Definition Documentation
QOCI_DYNAMIC_CHUNK_SIZE
#define QOCI_DYNAMIC_CHUNK_SIZE 65535
Definition at line 75 of file qsql_oci.cpp.
Referenced by QOCICols::readPiecewise().
QOCI_PREFETCH_MEM
#define QOCI_PREFETCH_MEM 10240
Definition at line 76 of file qsql_oci.cpp.
QOCI_THREADED
#define QOCI_THREADED
Definition at line 81 of file qsql_oci.cpp.
Typedef Documentation
IndicatorArray
typedef QVarLengthArray<sb2, 32> IndicatorArray
Definition at line 110 of file qsql_oci.cpp.
QOCIRowIdPointer
typedef QSharedDataPointer<QOCIRowId> QOCIRowIdPointer
Definition at line 157 of file qsql_oci.cpp.
SizeArray
typedef QVarLengthArray<ub2, 32> SizeArray
Definition at line 111 of file qsql_oci.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
QOCIEncoding
Definition at line 91 of file qsql_oci.cpp.
 { QOCIEncoding = 2002 }; // AL16UTF16LE
Function Documentation
qDecodeOCIType() [1/2]
QVariant::Type qDecodeOCIType (const QString & ocitype, QSql::NumericalPrecisionPolicy precisionPolicy)
Definition at line 561 of file qsql_oci.cpp.
Referenced by QOCIDriver::primaryIndex(), QOCICols::qMakeOraField(), and QOCIDriver::record().
 {
     QVariant::Type type = QVariant::Invalid;
     if (ocitype == QLatin1String("VARCHAR2") || ocitype == QLatin1String("VARCHAR")
          || ocitype.startsWith(QLatin1String("INTERVAL"))
          || ocitype == QLatin1String("CHAR") || ocitype == QLatin1String("NVARCHAR2")
          || ocitype == QLatin1String("NCHAR"))
         type = QVariant::String;
     else if (ocitype == QLatin1String("NUMBER")
              || ocitype == QLatin1String("FLOAT")
              || ocitype == QLatin1String("BINARY_FLOAT")
              || ocitype == QLatin1String("BINARY_DOUBLE")) {
         switch(precisionPolicy) {
             case QSql::LowPrecisionInt32:
                 type = QVariant::Int;
                 break;
             case QSql::LowPrecisionInt64:
                 type = QVariant::LongLong;
                 break;
             case QSql::LowPrecisionDouble:
                 type = QVariant::Double;
                 break;
             case QSql::HighPrecision:
             default:
                 type = QVariant::String;
                 break;
         }
     }
     else if (ocitype == QLatin1String("LONG") || ocitype == QLatin1String("NCLOB")
              || ocitype == QLatin1String("CLOB"))
         type = QVariant::ByteArray;
     else if (ocitype == QLatin1String("RAW") || ocitype == QLatin1String("LONG RAW")
              || ocitype == QLatin1String("ROWID") || ocitype == QLatin1String("BLOB")
              || ocitype == QLatin1String("CFILE") || ocitype == QLatin1String("BFILE"))
         type = QVariant::ByteArray;
     else if (ocitype == QLatin1String("DATE") ||  ocitype.startsWith(QLatin1String("TIME")))
         type = QVariant::DateTime;
     else if (ocitype == QLatin1String("UNDEFINED"))
         type = QVariant::Invalid;
     if (type == QVariant::Invalid)
         qWarning("qDecodeOCIType: unknown type: %s", ocitype.toLocal8Bit().constData());
     return type;
 }
qDecodeOCIType() [2/2]
QVariant::Type qDecodeOCIType (int ocitype, QSql::NumericalPrecisionPolicy precisionPolicy)
Definition at line 605 of file qsql_oci.cpp.
 {
     QVariant::Type type = QVariant::Invalid;
     switch (ocitype) {
     case SQLT_STR:
     case SQLT_VST:
     case SQLT_CHR:
     case SQLT_AFC:
     case SQLT_VCS:
     case SQLT_AVC:
     case SQLT_RDD:
     case SQLT_LNG:
 #ifdef SQLT_INTERVAL_YM
     case SQLT_INTERVAL_YM:
 #endif
 #ifdef SQLT_INTERVAL_DS
     case SQLT_INTERVAL_DS:
 #endif
         type = QVariant::String;
         break;
     case SQLT_INT:
         type = QVariant::Int;
         break;
     case SQLT_FLT:
     case SQLT_NUM:
     case SQLT_VNU:
     case SQLT_UIN:
         switch(precisionPolicy) {
             case QSql::LowPrecisionInt32:
                 type = QVariant::Int;
                 break;
             case QSql::LowPrecisionInt64:
                 type = QVariant::LongLong;
                 break;
             case QSql::LowPrecisionDouble:
                 type = QVariant::Double;
                 break;
             case QSql::HighPrecision:
             default:
                 type = QVariant::String;
                 break;
         }
         break;
     case SQLT_VBI:
     case SQLT_BIN:
     case SQLT_LBI:
     case SQLT_LVC:
     case SQLT_LVB:
     case SQLT_BLOB:
     case SQLT_CLOB:
     case SQLT_FILE:
     case SQLT_NTY:
     case SQLT_REF:
     case SQLT_RID:
         type = QVariant::ByteArray;
         break;
     case SQLT_DAT:
     case SQLT_ODT:
 #ifdef SQLT_TIMESTAMP
     case SQLT_TIMESTAMP:
     case SQLT_TIMESTAMP_TZ:
     case SQLT_TIMESTAMP_LTZ:
 #endif
         type = QVariant::DateTime;
         break;
     default:
         type = QVariant::Invalid;
         qWarning("qDecodeOCIType: unknown OCI datatype: %d", ocitype);
         break;
     }
         return type;
 }
qFromOraInf()
static QSqlField qFromOraInf (const OraFieldInfo & ofi) static
Definition at line 678 of file qsql_oci.cpp.
Referenced by QOCICols::QOCICols().
 {
     QSqlField f(ofi.name, ofi.type);
     f.setRequired(ofi.oraIsNull == 0);
     if (ofi.type == QVariant::String && ofi.oraType != SQLT_NUM && ofi.oraType != SQLT_VNU)
         f.setLength(ofi.oraFieldLength);
     else
         f.setLength(ofi.oraPrecision == 0 ? 38 : int(ofi.oraPrecision));
     f.setPrecision(ofi.oraScale);
     f.setSqlType(int(ofi.oraType));
     return f;
 }
qMakeDate()
QDateTime qMakeDate (const char * oraDate) static
Definition at line 773 of file qsql_oci.cpp.
Referenced by QOCICols::execBatch(), QOCICols::getValues(), and qOraOutValue().
 {
     int century = uchar(oraDate[0]);
     if(century >= 100){
         int year    = uchar(oraDate[1]);
         year = ((century-100)*100) + (year-100);
         int month = oraDate[2];
         int day   = oraDate[3];
         int hour  = oraDate[4] - 1;
         int min   = oraDate[5] - 1;
         int sec   = oraDate[6] - 1;
         return QDateTime(QDate(year,month,day), QTime(hour,min,sec));
     }
     return QDateTime();
 }
qMakeError()
QSqlError qMakeError (const QString & errString, QSqlError::ErrorType type, OCIError * err) static
Definition at line 554 of file qsql_oci.cpp.
Referenced by QOCIDriver::beginTransaction(), QOCIDriver::commitTransaction(), QOCIResult::exec(), QOCICols::execBatch(), QOCIResult::gotoNext(), QOCIDriver::open(), QOCIResult::prepare(), QOCIDriver::QOCIDriver(), and QOCIDriver::rollbackTransaction().
 {
     int errorCode = 0;
     const QString oraErrorString = qOraWarn(err, &errorCode);
     return QSqlError(errString, oraErrorString, type, errorCode);
 }
qMakeLongLong()
qlonglong qMakeLongLong (const char * ociNumber, OCIError * err) static
Definition at line 757 of file qsql_oci.cpp.
Referenced by QOCICols::execBatch(), and qOraOutValue().
 {
     qlonglong qll = 0;
     OCINumberToInt(err, reinterpret_cast<const OCINumber *>(ociNumber), sizeof(qlonglong),
                    OCI_NUMBER_SIGNED, &qll);
     return qll;
 }
qMakeOCINumber() [1/2]
QByteArray qMakeOCINumber (const qlonglong & ll, OCIError * err) static
Convert qlonglong to the internal Oracle OCINumber format.
Warning
This function is not part of the public interface.
Definition at line 725 of file qsql_oci.cpp.
Referenced by QOCIResultPrivate::bindValue(), and QOCICols::execBatch().
 {
     QByteArray ba(sizeof(OCINumber), 0);
     OCINumberFromInt(err,
                      &ll,
                      sizeof(qlonglong),
                      OCI_NUMBER_SIGNED,
                      reinterpret_cast<OCINumber*>(ba.data()));
     return ba;
 }
qMakeOCINumber() [2/2]
QByteArray qMakeOCINumber (const qulonglong & ull, OCIError * err) static
Convert qulonglong to the internal Oracle OCINumber format.
Warning
This function is not part of the public interface.
Definition at line 745 of file qsql_oci.cpp.
 {
     QByteArray ba(sizeof(OCINumber), 0);
     OCINumberFromInt(err,
                      &ull,
                      sizeof(qlonglong),
                      OCI_NUMBER_UNSIGNED,
                      reinterpret_cast<OCINumber*>(ba.data()));
     return ba;
 }
qMakeOraDate()
QByteArray qMakeOraDate (const QDateTime & dt) static
Convert QDateTime to the internal Oracle DATE format NB! It does not handle BCE dates.
Warning
This function is not part of the public interface.
Definition at line 702 of file qsql_oci.cpp.
Referenced by QOCIResultPrivate::bindValue(), and QOCICols::execBatch().
 {
     QByteArray ba;
     ba.resize(7);
     int year = dt.date().year();
     ba[0]= (year / 100) + 100; // century
     ba[1]= (year % 100) + 100; // year
     ba[2]= dt.date().month();
     ba[3]= dt.date().day();
     ba[4]= dt.time().hour() + 1;
     ba[5]= dt.time().minute() + 1;
     ba[6]= dt.time().second() + 1;
     return ba;
 }
qMakeULongLong()
qulonglong qMakeULongLong (const char * ociNumber, OCIError * err) static
Definition at line 765 of file qsql_oci.cpp.
Referenced by QOCICols::execBatch(), and qOraOutValue().
 {
     qulonglong qull = 0;
     OCINumberToInt(err, reinterpret_cast<const OCINumber *>(ociNumber), sizeof(qulonglong),
                    OCI_NUMBER_UNSIGNED, &qull);
     return qull;
 }
qOraErrorNumber()
static int qOraErrorNumber (OCIError * err) static
Definition at line 541 of file qsql_oci.cpp.
Referenced by QOCIResult::gotoNext().
 {
     sb4 errcode;
     OCIErrorGet(err,
                 1,
                 0,
                 &errcode,
                 0,
                 0,
                 OCI_HTYPE_ERROR);
     return errcode;
 }
qOraOutValue()
static void qOraOutValue (QVariant & value, QList< QByteArray > & storage, OCIError * err) static
Definition at line 419 of file qsql_oci.cpp.
Referenced by QOCICols::execBatch(), and QOCIResultPrivate::outValues().
 {
     switch (value.type()) {
     case QVariant::Time:
         value = qMakeDate(storage.takeFirst()).time();
         break;
     case QVariant::Date:
         value = qMakeDate(storage.takeFirst()).date();
         break;
     case QVariant::DateTime:
         value = qMakeDate(storage.takeFirst());
         break;
     case QVariant::LongLong:
         value = qMakeLongLong(storage.takeFirst(), err);
         break;
     case QVariant::ULongLong:
         value = qMakeULongLong(storage.takeFirst(), err);
         break;
     case QVariant::String:
         value = QString(
                 reinterpret_cast<const QChar *>(storage.takeFirst().constData()));
         break;
     default:
         break; //nothing
     }
 }
qOraWarn()
QString qOraWarn (OCIError * err, int * errorCode = 0) static
Definition at line 512 of file qsql_oci.cpp.
Referenced by qMakeError(), and qOraWarning().
 {
     sb4 errcode;
     text errbuf[1024];
     errbuf[0] = 0;
     errbuf[1] = 0;
     OCIErrorGet(err,
                 1,
                 0,
                 &errcode,
                 errbuf,
                 sizeof(errbuf),
                 OCI_HTYPE_ERROR);
     if (errorCode)
         *errorCode = errcode;
     return QString(reinterpret_cast<const QChar *>(errbuf));
 }
qOraWarning()
void qOraWarning (const char * msg, OCIError * err) static
Definition at line 531 of file qsql_oci.cpp.
Referenced by QOCIDriver::beginTransaction(), QOCIResultPrivate::bindValue(), QOCIDriver::commitTransaction(), QOCIResult::exec(), QOCICols::execBatch(), QOCIResult::gotoNext(), QOCIResult::prepare(), QOCICols::qMakeOraField(), QOCICols::QOCICols(), qReadLob(), QOCICols::readPiecewise(), QOCIDriver::rollbackTransaction(), QOCIResultPrivate::setCharset(), and QOCIResultPrivate::setStatementAttributes().
 {
 #ifdef QOCI_DEBUG
     qWarning("%s %s", msg, qPrintable(qOraWarn(err)));
 #else
     Q_UNUSED(msg);
     Q_UNUSED(err);
 #endif
 }
qParseOpts()
static void qParseOpts (const QString & options, QOCIDriverPrivate * d) static
Definition at line 2151 of file qsql_oci.cpp.
Referenced by QOCIDriver::open().
 {
     const QStringList opts(options.split(QLatin1Char(';'), QString::SkipEmptyParts));
     for (int i = 0; i < opts.count(); ++i) {
         const QString tmp(opts.at(i));
         int idx;
         if ((idx = tmp.indexOf(QLatin1Char('='))) == -1) {
             qWarning("QOCIDriver::parseArgs: Invalid parameter: '%s'",
                      tmp.toLocal8Bit().constData());
             continue;
         }
         const QString opt = tmp.left(idx);
         const QString val = tmp.mid(idx + 1).simplified();
         bool ok;
         if (opt == QLatin1String("OCI_ATTR_PREFETCH_ROWS")) {
             d->prefetchRows = val.toInt(&ok);
             if (!ok)
                 d->prefetchRows = -1;
         } else if (opt == QLatin1String("OCI_ATTR_PREFETCH_MEMORY")) {
             d->prefetchMem = val.toInt(&ok);
             if (!ok)
                 d->prefetchMem = -1;
         } else {
             qWarning ("QOCIDriver::parseArgs: Invalid parameter: '%s'",
                       opt.toLocal8Bit().constData());
         }
     }
 }
qReadLob()
template<class T , int sz> int qReadLob (T & buf, const QOCIResultPrivate * d, OCILobLocator * lob)
Definition at line 1630 of file qsql_oci.cpp.
 {
     ub1 csfrm;
     ub4 amount;
     int r;
     // Read this from the database, don't assume we know what it is set to
     r = OCILobCharSetForm(d->env, d->err, lob, &csfrm);
     if (r != OCI_SUCCESS) {
         qOraWarning("OCIResultPrivate::readLobs: Couldn't get LOB char set form: ", d->err);
         csfrm = 0;
     }
     // Get the length of the LOB (this is in characters)
     r = OCILobGetLength(d->svc, d->err, lob, &amount);
     if (r == OCI_SUCCESS) {
         if (amount == 0) {
             // Short cut for null LOBs
             buf.resize(0);
             return OCI_SUCCESS;
         }
     } else {
         qOraWarning("OCIResultPrivate::readLobs: Couldn't get LOB length: ", d->err);
         return r;
     }
     // Resize the buffer to hold the LOB contents
     buf.resize(amount);
     // Read the LOB into the buffer
     r = OCILobRead(d->svc,
                    d->err,
                    lob,
                    &amount,
                    1,
                    buf.data(),
                    buf.size() * sz, // this argument is in bytes, not characters
                    0,
                    0,
                    // Extract the data from a CLOB in UTF-16 (ie. what QString uses internally)
                    sz == 1 ? ub2(0) : ub2(QOCIEncoding),
                    csfrm);
     if (r != OCI_SUCCESS)
         qOraWarning("OCIResultPrivate::readLOBs: Cannot read LOB: ", d->err);
     return r;
 }
qSplitTableAndOwner()
void qSplitTableAndOwner (const QString & tname, QString * tbl, QString * owner)
Definition at line 2444 of file qsql_oci.cpp.
Referenced by QOCIDriver::primaryIndex(), and QOCIDriver::record().
 {
     int i = tname.indexOf(QLatin1Char('.')); // prefixed with owner?
     if (i != -1) {
         *tbl = tname.right(tname.length() - i - 1);
         *owner = tname.left(i);
     } else {
         *tbl = tname;
     }
 }
Variable Documentation
qOraCharset
const ub2 qOraCharset = OCI_UCS2ID static
Definition at line 107 of file qsql_oci.cpp.
Referenced by QOCIResultPrivate::setCharset().