Qt 4.8: /src/sql/kernel/qsqlresult.cpp File Reference
qsqlresult.cpp File Reference
#include "qvariant.h"
#include "qhash.h"
#include "qregexp.h"
#include "qsqlerror.h"
#include "qsqlfield.h"
#include "qsqlrecord.h"
#include "qsqlresult.h"
#include "qvector.h"
#include "qsqldriver.h"
#include "qpointer.h"
#include <QDebug>
Classes
struct QHolder
class QSqlResultPrivate
Functions
static QString qFieldSerial (int i)
static bool qIsAlnum (QChar ch)
Function Documentation
qFieldSerial()
static QString qFieldSerial (int i) static
Definition at line 130 of file qsqlresult.cpp.
Referenced by QSqlResult::bindValue(), and QSqlResultPrivate::positionalToNamedBinding().
 {
     ushort arr[] = { ':', 'f', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
     ushort *ptr = &arr[1];
     while (i > 0) {
         *(++ptr) = 'a' + i % 16;
         i >>= 4;
     }
     return QString(reinterpret_cast<const QChar *>(arr), int(ptr - arr) + 1);
 }
qIsAlnum()
static bool qIsAlnum (QChar ch) static
Definition at line 143 of file qsqlresult.cpp.
Referenced by QSqlResultPrivate::namedToPositionalBinding(), and QSqlResult::prepare().
 {
     uint u = uint(ch.unicode());
     // matches [a-zA-Z0-9_]
     return u - 'a' < 26 || u - 'A' < 26 || u - '0' < 10 || u == '_';
 }