Qt 4.8: /src/sql/drivers/sqlite/qsql_sqlite.cpp File Reference
qsql_sqlite.cpp File Reference
#include "qsql_sqlite.h"
#include <qcoreapplication.h>
#include <qvariant.h>
#include <qsqlerror.h>
#include <qsqlfield.h>
#include <qsqlindex.h>
#include <qsqlquery.h>
#include <qstringlist.h>
#include <qvector.h>
#include <qdebug.h>
#include <qt_windows.h>
#include <sqlite3.h>
Classes
class QSQLiteDriverPrivate
class QSQLiteResultPrivate
Functions
static QString _q_escapeIdentifier (const QString &identifier)
static QVariant::Type qGetColumnType (const QString &tpName)
static QSqlIndex qGetTableInfo (QSqlQuery &q, const QString &tableName, bool onlyPIndex=false)
static QSqlError qMakeError (sqlite3 *access, const QString &descr, QSqlError::ErrorType type, int errorCode=-1)
Function Documentation
_q_escapeIdentifier()
static QString _q_escapeIdentifier (const QString & identifier) static
Definition at line 67 of file qsql_sqlite.cpp.
Referenced by QSQLiteDriver::escapeIdentifier(), and qGetTableInfo().
 {
     QString res = identifier;
     if(!identifier.isEmpty() && identifier.left(1) != QString(QLatin1Char('"')) && identifier.right(1) != QString(QLatin1Char('"')) ) {
         res.replace(QLatin1Char('"'), QLatin1String("\"\""));
         res.prepend(QLatin1Char('"')).append(QLatin1Char('"'));
         res.replace(QLatin1Char('.'), QLatin1String("\".\""));
     }
     return res;
 }
qGetColumnType()
static QVariant::Type qGetColumnType (const QString & tpName) static
Definition at line 78 of file qsql_sqlite.cpp.
Referenced by QSQLiteResultPrivate::initColumns(), and qGetTableInfo().
 {
     const QString typeName = tpName.toLower();
     if (typeName == QLatin1String("integer")
         || typeName == QLatin1String("int"))
         return QVariant::Int;
     if (typeName == QLatin1String("double")
         || typeName == QLatin1String("float")
         || typeName == QLatin1String("real")
         || typeName.startsWith(QLatin1String("numeric")))
         return QVariant::Double;
     if (typeName == QLatin1String("blob"))
         return QVariant::ByteArray;
     return QVariant::String;
 }
qGetTableInfo()
static QSqlIndex qGetTableInfo (QSqlQuery & q, const QString & tableName, bool onlyPIndex = false) static
Definition at line 681 of file qsql_sqlite.cpp.
Referenced by QSQLiteDriver::primaryIndex(), qExtractSecurityPolicyFromString(), and QSQLiteDriver::record().
 {
     QString schema;
     QString table(tableName);
     int indexOfSeparator = tableName.indexOf(QLatin1Char('.'));
     if (indexOfSeparator > -1) {
         schema = tableName.left(indexOfSeparator).append(QLatin1Char('.'));
         table = tableName.mid(indexOfSeparator + 1);
     }
     q.exec(QLatin1String("PRAGMA ") + schema + QLatin1String("table_info (") + _q_escapeIdentifier(table) + QLatin1String(")"));
     QSqlIndex ind;
     while (q.next()) {
         bool isPk = q.value(5).toInt();
         if (onlyPIndex && !isPk)
             continue;
         QString typeName = q.value(2).toString().toLower();
         QSqlField fld(q.value(1).toString(), qGetColumnType(typeName));
         if (isPk && (typeName == QLatin1String("integer")))
             // INTEGER PRIMARY KEY fields are auto-generated in sqlite
             // INT PRIMARY KEY is not the same as INTEGER PRIMARY KEY!
             fld.setAutoValue(true);
         fld.setRequired(q.value(3).toInt() != 0);
         fld.setDefaultValue(q.value(4));
         ind.append(fld);
     }
     return ind;
 }
qMakeError()
static QSqlError qMakeError (sqlite3 * access, const QString & descr, QSqlError::ErrorType type, int errorCode = -1) static
Definition at line 95 of file qsql_sqlite.cpp.
Referenced by QSQLiteDriver::close(), QSQLiteResult::exec(), QSQLiteResultPrivate::fetchNext(), QSQLiteDriver::open(), and QSQLiteResult::prepare().
 {
     return QSqlError(descr,
                      QString(reinterpret_cast<const QChar *>(sqlite3_errmsg16(access))),
                      type, errorCode);
 }