Qt 4.8: /src/sql/drivers/mysql/qsql_mysql.cpp File Reference
qsql_mysql.cpp File Reference
#include "qsql_mysql.h"
#include <qcoreapplication.h>
#include <qvariant.h>
#include <qdatetime.h>
#include <qsqlerror.h>
#include <qsqlfield.h>
#include <qsqlindex.h>
#include <qsqlquery.h>
#include <qsqlrecord.h>
#include <qstringlist.h>
#include <qtextcodec.h>
#include <qvector.h>
#include <qdebug.h>
#include "qsql_mysql.moc"
Classes
class QMYSQLDriverPrivate
class QMYSQLResultPrivate
struct QMYSQLResultPrivate::QMyField
Macros
#define Q_CLIENT_MULTI_STATEMENTS 0
Functions
static QTextCodec * codec (MYSQL *mysql)
static QByteArray fromUnicode (QTextCodec *tc, const QString &str)
static QVariant qDateFromString (const QString &val)
static QVariant qDateTimeFromString (QString &val)
static QVariant::Type qDecodeMYSQLType (int mysqltype, uint flags)
static void qLibraryEnd ()
static void qLibraryInit ()
static QSqlError qMakeError (const QString &err, QSqlError::ErrorType type, const QMYSQLDriverPrivate *p)
static QVariant qTimeFromString (const QString &val)
static QSqlField qToField (MYSQL_FIELD *field, QTextCodec *tc)
static void setOptionFlag (uint &optionFlags, const QString &opt)
static QString toUnicode (QTextCodec *tc, const char *str)
static QString toUnicode (QTextCodec *tc, const char *str, int length)
Variables
static int qMySqlConnectionCount = 0
static bool qMySqlInitHandledByUser = false
Macro Definition Documentation
Q_CLIENT_MULTI_STATEMENTS
#define Q_CLIENT_MULTI_STATEMENTS 0
Definition at line 74 of file qsql_mysql.cpp.
Referenced by QMYSQLDriver::open().
Function Documentation
codec()
static QTextCodec* codec (MYSQL * mysql) static
Definition at line 220 of file qsql_mysql.cpp.
Referenced by QTextCodec::codecForMib(), QTextCodec::codecForName(), encodeText(), QDeclarativeXMLHttpRequest::findTextCodec(), QString::fromLocal8Bit(), QXmlInputSource::fromRawData(), QSettingsPrivate::iniEscapedStringList(), QXlibMime::mimeConvertToFormat(), QMYSQLDriver::open(), QMYSQLDriver::QMYSQLDriver(), QApplicationPrivate::qt_mac_apply_settings(), qt_x11_set_fallback_font_family(), QTextDecoder::QTextDecoder(), QTextEncoder::QTextEncoder(), QMimeDataPrivate::retrieveTypedData(), QPatternist::AccelTreeResourceLoader::retrieveUnparsedText(), QDomDocumentPrivate::saveDocument(), QTextOdfWriter::setCodec(), QSettings::setIniCodec(), QTextBrowserPrivate::setSource(), QClipboard::text(), QApplicationPrivate::x11_apply_settings(), and QX11Data::xdndMimeConvertToFormat().
 {
 #if MYSQL_VERSION_ID >= 32321
     QTextCodec* heuristicCodec = QTextCodec::codecForName(mysql_character_set_name(mysql));
     if (heuristicCodec)
         return heuristicCodec;
 #endif
     return QTextCodec::codecForLocale();
 }
fromUnicode()
static QByteArray fromUnicode (QTextCodec * tc, const QString & str) inline static
Definition at line 115 of file qsql_mysql.cpp.
Referenced by QTextCodec::codecForName(), QTextCodec::fromUnicode(), QTextEncoder::QTextEncoder(), QMYSQLResult::reset(), and QMYSQLResult::virtual_hook().
 {
 #ifdef QT_NO_TEXTCODEC
     Q_UNUSED(tc);
     return str.toLatin1();
 #else
     return tc->fromUnicode(str);
 #endif
 }
qDateFromString()
static QVariant qDateFromString (const QString & val) inline static
Definition at line 125 of file qsql_mysql.cpp.
Referenced by QMYSQLResult::data().
 {
 #ifdef QT_NO_DATESTRING
     Q_UNUSED(val);
     return QVariant(val);
 #else
     if (val.isEmpty())
         return QVariant(QDate());
     return QVariant(QDate::fromString(val, Qt::ISODate));
 #endif
 }
qDateTimeFromString()
static QVariant qDateTimeFromString (QString & val) inline static
Definition at line 149 of file qsql_mysql.cpp.
Referenced by QMYSQLResult::data().
 {
 #ifdef QT_NO_DATESTRING
     Q_UNUSED(val);
     return QVariant(val);
 #else
     if (val.isEmpty())
         return QVariant(QDateTime());
     if (val.length() == 14)
         // TIMESTAMPS have the format yyyyMMddhhmmss
         val.insert(4, QLatin1Char('-')).insert(7, QLatin1Char('-')).insert(10,
                     QLatin1Char('T')).insert(13, QLatin1Char(':')).insert(16, QLatin1Char(':'));
     return QVariant(QDateTime::fromString(val, Qt::ISODate));
 #endif
 }
qDecodeMYSQLType()
static QVariant::Type qDecodeMYSQLType (int mysqltype, uint flags) static
Definition at line 241 of file qsql_mysql.cpp.
Referenced by QMYSQLResult::nextResult(), qToField(), and QMYSQLResult::reset().
 {
     QVariant::Type type;
     switch (mysqltype) {
     case FIELD_TYPE_TINY :
     case FIELD_TYPE_SHORT :
     case FIELD_TYPE_LONG :
     case FIELD_TYPE_INT24 :
         type = (flags & UNSIGNED_FLAG) ? QVariant::UInt : QVariant::Int;
         break;
     case FIELD_TYPE_YEAR :
         type = QVariant::Int;
         break;
     case FIELD_TYPE_LONGLONG :
         type = (flags & UNSIGNED_FLAG) ? QVariant::ULongLong : QVariant::LongLong;
         break;
     case FIELD_TYPE_FLOAT :
     case FIELD_TYPE_DOUBLE :
     case FIELD_TYPE_DECIMAL :
 #if defined(FIELD_TYPE_NEWDECIMAL)
     case FIELD_TYPE_NEWDECIMAL:
 #endif
         type = QVariant::Double;
         break;
     case FIELD_TYPE_DATE :
         type = QVariant::Date;
         break;
     case FIELD_TYPE_TIME :
         type = QVariant::Time;
         break;
     case FIELD_TYPE_DATETIME :
     case FIELD_TYPE_TIMESTAMP :
         type = QVariant::DateTime;
         break;
     case FIELD_TYPE_STRING :
     case FIELD_TYPE_VAR_STRING :
     case FIELD_TYPE_BLOB :
     case FIELD_TYPE_TINY_BLOB :
     case FIELD_TYPE_MEDIUM_BLOB :
     case FIELD_TYPE_LONG_BLOB :
         type = (flags & BINARY_FLAG) ? QVariant::ByteArray : QVariant::String;
         break;
     default:
     case FIELD_TYPE_ENUM :
     case FIELD_TYPE_SET :
         type = QVariant::String;
         break;
     }
     return type;
 }
qLibraryEnd()
static void qLibraryEnd () static
Definition at line 1110 of file qsql_mysql.cpp.
Referenced by QMYSQLDriver::~QMYSQLDriver().
 {
 #ifndef Q_NO_MYSQL_EMBEDDED
 # if MYSQL_VERSION_ID > 40000
 #  if (MYSQL_VERSION_ID >= 40110 && MYSQL_VERSION_ID < 50000) || MYSQL_VERSION_ID >= 50003
     mysql_library_end();
 #  else
     mysql_server_end();
 #  endif
 # endif
 #endif
 }
qLibraryInit()
static void qLibraryInit () static
Definition at line 1092 of file qsql_mysql.cpp.
Referenced by QMYSQLDriver::QMYSQLDriver().
 {
 #ifndef Q_NO_MYSQL_EMBEDDED
 # if MYSQL_VERSION_ID >= 40000
     if (qMySqlInitHandledByUser || qMySqlConnectionCount > 1)
         return;
 # if (MYSQL_VERSION_ID >= 40110 && MYSQL_VERSION_ID < 50000) || MYSQL_VERSION_ID >= 50003
     if (mysql_library_init(0, 0, 0)) {
 # else
     if (mysql_server_init(0, 0, 0)) {
 # endif
         qWarning("QMYSQLDriver::qServerInit: unable to start server.");
     }
 # endif // MYSQL_VERSION_ID
 #endif // Q_NO_MYSQL_EMBEDDED
 }
qMakeError()
static QSqlError qMakeError (const QString & err, QSqlError::ErrorType type, const QMYSQLDriverPrivate * p) static
Definition at line 231 of file qsql_mysql.cpp.
Referenced by QMYSQLDriver::beginTransaction(), QMYSQLDriver::commitTransaction(), QMYSQLResult::nextResult(), QMYSQLDriver::open(), QMYSQLResult::reset(), QMYSQLDriver::rollbackTransaction(), and QMYSQLResult::virtual_hook().
 {
     const char *cerr = p->mysql ? mysql_error(p->mysql) : 0;
     return QSqlError(QLatin1String("QMYSQL: ") + err,
                      p->tc ? toUnicode(p->tc, cerr) : QString::fromLatin1(cerr),
                      type, mysql_errno(p->mysql));
 }
qTimeFromString()
static QVariant qTimeFromString (const QString & val) inline static
Definition at line 137 of file qsql_mysql.cpp.
Referenced by QMYSQLResult::data().
 {
 #ifdef QT_NO_DATESTRING
     Q_UNUSED(val);
     return QVariant(val);
 #else
     if (val.isEmpty())
         return QVariant(QTime());
     return QVariant(QTime::fromString(val, Qt::ISODate));
 #endif
 }
qToField()
static QSqlField qToField (MYSQL_FIELD * field, QTextCodec * tc) static
Definition at line 292 of file qsql_mysql.cpp.
Referenced by QMYSQLResult::record(), and QMYSQLDriver::record().
 {
     QSqlField f(toUnicode(tc, field->name),
                 qDecodeMYSQLType(int(field->type), field->flags));
     f.setRequired(IS_NOT_NULL(field->flags));
     f.setLength(field->length);
     f.setPrecision(field->decimals);
     f.setSqlType(field->type);
     f.setAutoValue(field->flags & AUTO_INCREMENT_FLAG);
     return f;
 }
setOptionFlag()
static void setOptionFlag (uint & optionFlags, const QString & opt) static
Definition at line 1209 of file qsql_mysql.cpp.
Referenced by QMYSQLDriver::open().
 {
     if (opt == QLatin1String("CLIENT_COMPRESS"))
         optionFlags |= CLIENT_COMPRESS;
     else if (opt == QLatin1String("CLIENT_FOUND_ROWS"))
         optionFlags |= CLIENT_FOUND_ROWS;
     else if (opt == QLatin1String("CLIENT_IGNORE_SPACE"))
         optionFlags |= CLIENT_IGNORE_SPACE;
     else if (opt == QLatin1String("CLIENT_INTERACTIVE"))
         optionFlags |= CLIENT_INTERACTIVE;
     else if (opt == QLatin1String("CLIENT_NO_SCHEMA"))
         optionFlags |= CLIENT_NO_SCHEMA;
     else if (opt == QLatin1String("CLIENT_ODBC"))
         optionFlags |= CLIENT_ODBC;
     else if (opt == QLatin1String("CLIENT_SSL"))
         optionFlags |= CLIENT_SSL;
     else
         qWarning("QMYSQLDriver::open: Unknown connect option '%s'", opt.toLocal8Bit().constData());
 }
toUnicode() [1/2]
static QString toUnicode (QTextCodec * tc, const char * str) inline static
Definition at line 95 of file qsql_mysql.cpp.
Referenced by QTextCodec::codecForName(), QMYSQLResult::data(), QPdfEnginePrivate::embedFont(), QFontEngineXLFD::fontStruct(), QMYSQLDriver::formatValue(), QTextCodec::fromUnicode(), QFontSubset::glyphName(), qMakeError(), QTextDecoder::QTextDecoder(), qToField(), and QMYSQLDriver::tables().
 {
 #ifdef QT_NO_TEXTCODEC
     Q_UNUSED(tc);
     return QString::fromLatin1(str);
 #else
     return tc->toUnicode(str);
 #endif
 }
toUnicode() [2/2]
static QString toUnicode (QTextCodec * tc, const char * str, int length) inline static
Definition at line 105 of file qsql_mysql.cpp.
 {
 #ifdef QT_NO_TEXTCODEC
     Q_UNUSED(tc);
     return QString::fromLatin1(str, length);
 #else
     return tc->toUnicode(str, length);
 #endif
 }
Variable Documentation
qMySqlConnectionCount
int qMySqlConnectionCount = 0 static
Definition at line 1089 of file qsql_mysql.cpp.
qMySqlInitHandledByUser
bool qMySqlInitHandledByUser = false static
Definition at line 1090 of file qsql_mysql.cpp.