Qt 4.8: /src/network/ssl/qsslsocket_openssl_symbols_p.h File Reference
qsslsocket_openssl_symbols_p.h File Reference
#include "qsslsocket_openssl_p.h"
Macros
#define DEFINEFUNC(ret, func, arg, a, err, funcret)
#define DEFINEFUNC2(ret, func, arg1, a, arg2, b, err, funcret)
#define DEFINEFUNC3(ret, func, arg1, a, arg2, b, arg3, c, err, funcret)
#define DEFINEFUNC4(ret, func, arg1, a, arg2, b, arg3, c, arg4, d, err, funcret)
#define DEFINEFUNC5(ret, func, arg1, a, arg2, b, arg3, c, arg4, d, arg5, e, err, funcret)
#define DEFINEFUNC6(ret, func, arg1, a, arg2, b, arg3, c, arg4, d, arg5, e, arg6, f, err, funcret)
#define DEFINEFUNC7(ret, func, arg1, a, arg2, b, arg3, c, arg4, d, arg5, e, arg6, f, arg7, g, err, funcret)
#define DEFINEFUNC9(ret, func, arg1, a, arg2, b, arg3, c, arg4, d, arg5, e, arg6, f, arg7, g, arg8, h, arg9, i, err, funcret)
#define DUMMYARG
#define q_BIO_get_mem_data(b, pp) (int)q_BIO_ctrl(b,BIO_CTRL_INFO,0,(char *)pp)
#define q_BIO_pending(b) (int)q_BIO_ctrl(b,BIO_CTRL_PENDING,0,NULL)
#define q_EVP_PKEY_assign_DSA(pkey, dsa)
#define q_EVP_PKEY_assign_RSA(pkey, rsa)
#define q_OpenSSL_add_all_algorithms() q_OPENSSL_add_all_algorithms_noconf()
#define q_sk_GENERAL_NAME_num(st) q_SKM_sk_num(GENERAL_NAME, (st))
#define q_sk_GENERAL_NAME_value(st, i) q_SKM_sk_value(GENERAL_NAME, (st), (i))
#define q_sk_SSL_CIPHER_num(st) q_SKM_sk_num(SSL_CIPHER, (st))
#define q_sk_SSL_CIPHER_value(st, i) q_SKM_sk_value(SSL_CIPHER, (st), (i))
#define q_sk_X509_num(st) q_SKM_sk_num(X509, (st))
#define q_sk_X509_value(st, i) q_SKM_sk_value(X509, (st), (i))
#define q_SKM_sk_num(type, st) ((int (*)(const STACK_OF(type) *))q_sk_num)(st)
#define q_SKM_sk_value(type, st, i) ((type * (*)(const STACK_OF(type) *, int))q_sk_value)(st, i)
#define q_SSL_CTX_add_extra_chain_cert(ctx, x509) q_SSL_CTX_ctrl(ctx,SSL_CTRL_EXTRA_CHAIN_CERT,0,(char *)x509)
#define q_SSL_CTX_set_options(ctx, op) q_SSL_CTX_ctrl((ctx),SSL_CTRL_OPTIONS,(op),NULL)
#define q_X509_get_notAfter(x) X509_get_notAfter(x)
#define q_X509_get_notBefore(x) X509_get_notBefore(x)
Functions
long q_ASN1_INTEGER_get (ASN1_INTEGER *a)
unsigned char * q_ASN1_STRING_data (ASN1_STRING *a)
int q_ASN1_STRING_length (ASN1_STRING *a)
int q_ASN1_STRING_to_UTF8 (unsigned char **a, ASN1_STRING *b)
long q_BIO_ctrl (BIO *a, int b, long c, void *d)
int q_BIO_free (BIO *a)
BIO * q_BIO_new (BIO_METHOD *a)
BIO * q_BIO_new_mem_buf (void *a, int b)
int q_BIO_read (BIO *a, void *b, int c)
BIO_METHOD * q_BIO_s_mem ()
int q_BIO_write (BIO *a, const void *b, int c)
int q_BN_num_bits (const BIGNUM *a)
void q_CRYPTO_free (void *a)
int q_CRYPTO_num_locks ()
void q_CRYPTO_set_id_callback (unsigned long(*a)())
void q_CRYPTO_set_locking_callback (void(*a)(int, int, const char *, int))
X509 * q_d2i_X509 (X509 **a, unsigned char **b, long c)
void q_DSA_free (DSA *a)
char * q_ERR_error_string (unsigned long a, char *b)
unsigned long q_ERR_get_error ()
const EVP_CIPHER * q_EVP_des_ede3_cbc ()
int q_EVP_PKEY_assign (EVP_PKEY *a, int b, char *c)
void q_EVP_PKEY_free (EVP_PKEY *a)
DSA * q_EVP_PKEY_get1_DSA (EVP_PKEY *a)
RSA * q_EVP_PKEY_get1_RSA (EVP_PKEY *a)
EVP_PKEY * q_EVP_PKEY_new ()
int q_EVP_PKEY_set1_DSA (EVP_PKEY *a, DSA *b)
int q_EVP_PKEY_set1_RSA (EVP_PKEY *a, RSA *b)
int q_EVP_PKEY_type (int a)
QDateTime q_getTimeFromASN1 (const ASN1_TIME *aTime)
int q_i2d_X509 (X509 *a, unsigned char **b)
const char * q_OBJ_nid2sn (int a)
int q_OBJ_obj2nid (const ASN1_OBJECT *a)
void q_OPENSSL_add_all_algorithms_conf ()
void q_OPENSSL_add_all_algorithms_noconf ()
DSA * q_PEM_read_bio_DSA_PUBKEY (BIO *a, DSA **b, pem_password_cb *c, void *d)
DSA * q_PEM_read_bio_DSAPrivateKey (BIO *a, DSA **b, pem_password_cb *c, void *d)
RSA * q_PEM_read_bio_RSA_PUBKEY (BIO *a, RSA **b, pem_password_cb *c, void *d)
RSA * q_PEM_read_bio_RSAPrivateKey (BIO *a, RSA **b, pem_password_cb *c, void *d)
int q_PEM_write_bio_DSA_PUBKEY (BIO *a, DSA *b)
int q_PEM_write_bio_DSAPrivateKey (BIO *a, DSA *b, const EVP_CIPHER *c, unsigned char *d, int e, pem_password_cb *f, void *g)
int q_PEM_write_bio_RSA_PUBKEY (BIO *a, RSA *b)
int q_PEM_write_bio_RSAPrivateKey (BIO *a, RSA *b, const EVP_CIPHER *c, unsigned char *d, int e, pem_password_cb *f, void *g)
void q_RAND_seed (const void *a, int b)
int q_RAND_status ()
bool q_resolveOpenSslSymbols ()
void q_RSA_free (RSA *a)
void q_sk_free (STACK *a)
int q_sk_num (STACK *a)
void q_sk_pop_free (STACK *a, void(*b)(void *))
char * q_sk_value (STACK *a, int b)
int q_SSL_accept (SSL *a)
char * q_SSL_CIPHER_description (SSL_CIPHER *a, char *b, int c)
int q_SSL_clear (SSL *a)
int q_SSL_connect (SSL *a)
int q_SSL_CTX_check_private_key (SSL_CTX *a)
long q_SSL_CTX_ctrl (SSL_CTX *a, int b, long c, void *d)
void q_SSL_CTX_free (SSL_CTX *a)
int q_SSL_CTX_load_verify_locations (SSL_CTX *ctx, const char *CAfile, const char *CApath)
SSL_CTX * q_SSL_CTX_new (SSL_METHOD *a)
int q_SSL_CTX_set_cipher_list (SSL_CTX *a, const char *b)
int q_SSL_CTX_set_default_verify_paths (SSL_CTX *a)
void q_SSL_CTX_set_verify (SSL_CTX *a, int b, int(*c)(int, X509_STORE_CTX *))
void q_SSL_CTX_set_verify_depth (SSL_CTX *a, int b)
int q_SSL_CTX_use_certificate (SSL_CTX *a, X509 *b)
int q_SSL_CTX_use_certificate_file (SSL_CTX *a, const char *b, int c)
int q_SSL_CTX_use_PrivateKey (SSL_CTX *a, EVP_PKEY *b)
int q_SSL_CTX_use_PrivateKey_file (SSL_CTX *a, const char *b, int c)
int q_SSL_CTX_use_RSAPrivateKey (SSL_CTX *a, RSA *b)
void q_SSL_free (SSL *a)
SSL_CIPHER * q_SSL_get_current_cipher (SSL *a)
int q_SSL_get_error (SSL *a, int b)
X509 * q_SSL_get_peer_certificate (SSL *a)
long q_SSL_get_verify_result (SSL *a)
int q_SSL_library_init ()
void q_SSL_load_error_strings ()
SSL * q_SSL_new (SSL_CTX *a)
int q_SSL_read (SSL *a, void *b, int c)
void q_SSL_set_accept_state (SSL *a)
void q_SSL_set_bio (SSL *a, BIO *b, BIO *c)
void q_SSL_set_connect_state (SSL *a)
int q_SSL_shutdown (SSL *a)
int q_SSL_write (SSL *a, const void *b, int c)
long q_SSLeay ()
SSL_METHOD * q_SSLv23_client_method ()
SSL_METHOD * q_SSLv23_server_method ()
SSL_METHOD * q_SSLv2_client_method ()
SSL_METHOD * q_SSLv2_server_method ()
SSL_METHOD * q_SSLv3_client_method ()
SSL_METHOD * q_SSLv3_server_method ()
SSL_METHOD * q_TLSv1_client_method ()
SSL_METHOD * q_TLSv1_server_method ()
int q_X509_cmp (X509 *a, X509 *b)
X509 * q_X509_dup (X509 *a)
ASN1_OBJECT * q_X509_EXTENSION_get_object (X509_EXTENSION *a)
void q_X509_free (X509 *a)
X509_EXTENSION * q_X509_get_ext (X509 *a, int b)
int q_X509_get_ext_count (X509 *a)
void * q_X509_get_ext_d2i (X509 *a, int b, int *c, int *d)
X509_NAME * q_X509_get_issuer_name (X509 *a)
X509_NAME * q_X509_get_subject_name (X509 *a)
int q_X509_NAME_entry_count (X509_NAME *a)
ASN1_STRING * q_X509_NAME_ENTRY_get_data (X509_NAME_ENTRY *a)
ASN1_OBJECT * q_X509_NAME_ENTRY_get_object (X509_NAME_ENTRY *a)
X509_NAME_ENTRY * q_X509_NAME_get_entry (X509_NAME *a, int b)
EVP_PKEY * q_X509_PUBKEY_get (X509_PUBKEY *a)
int q_X509_STORE_add_cert (X509_STORE *ctx, X509 *x)
void q_X509_STORE_CTX_free (X509_STORE_CTX *storeCtx)
X509 * q_X509_STORE_CTX_get_current_cert (X509_STORE_CTX *ctx)
int q_X509_STORE_CTX_get_error (X509_STORE_CTX *ctx)
int q_X509_STORE_CTX_get_error_depth (X509_STORE_CTX *ctx)
int q_X509_STORE_CTX_init (X509_STORE_CTX *ctx, X509_STORE *store, X509 *x509, STACK_OF(X509) *chain)
X509_STORE_CTX * q_X509_STORE_CTX_new ()
int q_X509_STORE_CTX_set_purpose (X509_STORE_CTX *ctx, int purpose)
void q_X509_STORE_free (X509_STORE *store)
X509_STORE * q_X509_STORE_new ()
int q_X509_verify_cert (X509_STORE_CTX *ctx)
STACK_OF (SSL_CIPHER) *q_SSL_get_ciphers(SSL *a)
STACK_OF (X509) *q_SSL_get_peer_cert_chain(SSL *a)
Macro Definition Documentation
DEFINEFUNC
#define DEFINEFUNC (ret, func, arg, a, err, funcret)
Value:
typedef ret (*_q_PTR_##func)(arg);                  \
    static _q_PTR_##func _q_##func = 0;                 \
    ret q_##func(arg) {                     \
        if (!_q_##func) {               \
            qWarning("QSslSocket: cannot call unresolved function "#func);  \
            err;                                \
        } \
        funcret _q_##func(a); \
    }
Definition at line 67 of file qsslsocket_openssl_symbols_p.h.
DEFINEFUNC2
#define DEFINEFUNC2 (ret, func, arg1, a, arg2, b, err, funcret)
Value:
typedef ret (*_q_PTR_##func)(arg1, arg2);         \
    static _q_PTR_##func _q_##func = 0;               \
    ret q_##func(arg1, arg2) { \
        if (!_q_##func) { \
            qWarning("QSslSocket: cannot call unresolved function "#func);\
            err; \
        } \
        funcret _q_##func(a, b); \
    }
Definition at line 79 of file qsslsocket_openssl_symbols_p.h.
DEFINEFUNC3
#define DEFINEFUNC3 (ret, func, arg1, a, arg2, b, arg3, c, err, funcret)
Value:
typedef ret (*_q_PTR_##func)(arg1, arg2, arg3);            \
    static _q_PTR_##func _q_##func = 0;                        \
    ret q_##func(arg1, arg2, arg3) { \
        if (!_q_##func) { \
            qWarning("QSslSocket: cannot call unresolved function "#func); \
            err; \
        } \
        funcret _q_##func(a, b, c); \
    }
Definition at line 91 of file qsslsocket_openssl_symbols_p.h.
DEFINEFUNC4
#define DEFINEFUNC4 (ret, func, arg1, a, arg2, b, arg3, c, arg4, d, err, funcret)
Value:
typedef ret (*_q_PTR_##func)(arg1, arg2, arg3, arg4);               \
    static _q_PTR_##func _q_##func = 0;                                 \
    ret q_##func(arg1, arg2, arg3, arg4) { \
         if (!_q_##func) { \
             qWarning("QSslSocket: cannot call unresolved function "#func); \
             err; \
         } \
         funcret _q_##func(a, b, c, d); \
    }
Definition at line 103 of file qsslsocket_openssl_symbols_p.h.
DEFINEFUNC5
#define DEFINEFUNC5 (ret, func, arg1, a, arg2, b, arg3, c, arg4, d, arg5, e, err, funcret)
Value:
typedef ret (*_q_PTR_##func)(arg1, arg2, arg3, arg4, arg5);         \
    static _q_PTR_##func _q_##func = 0;                                 \
    ret q_##func(arg1, arg2, arg3, arg4, arg5) { \
        if (!_q_##func) { \
            qWarning("QSslSocket: cannot call unresolved function "#func); \
            err; \
        } \
        funcret _q_##func(a, b, c, d, e); \
    }
Definition at line 115 of file qsslsocket_openssl_symbols_p.h.
DEFINEFUNC6
#define DEFINEFUNC6 (ret, func, arg1, a, arg2, b, arg3, c, arg4, d, arg5, e, arg6, f, err, funcret)
Value:
typedef ret (*_q_PTR_##func)(arg1, arg2, arg3, arg4, arg5, arg6);   \
    static _q_PTR_##func _q_##func = 0;                                 \
    ret q_##func(arg1, arg2, arg3, arg4, arg5, arg6) { \
        if (!_q_##func) { \
            qWarning("QSslSocket: cannot call unresolved function "#func); \
            err; \
        } \
        funcret _q_##func(a, b, c, d, e, f); \
    }
Definition at line 127 of file qsslsocket_openssl_symbols_p.h.
DEFINEFUNC7
#define DEFINEFUNC7 (ret, func, arg1, a, arg2, b, arg3, c, arg4, d, arg5, e, arg6, f, arg7, g, err, funcret)
Value:
typedef ret (*_q_PTR_##func)(arg1, arg2, arg3, arg4, arg5, arg6, arg7);   \
    static _q_PTR_##func _q_##func = 0;                                       \
    ret q_##func(arg1, arg2, arg3, arg4, arg5, arg6, arg7) { \
        if (!_q_##func) { \
            qWarning("QSslSocket: cannot call unresolved function "#func); \
            err; \
        } \
        funcret _q_##func(a, b, c, d, e, f, g); \
    }
Definition at line 139 of file qsslsocket_openssl_symbols_p.h.
DEFINEFUNC9
#define DEFINEFUNC9 (ret, func, arg1, a, arg2, b, arg3, c, arg4, d, arg5, e, arg6, f, arg7, g, arg8, h, arg9, i, err, funcret)
Value:
typedef ret (*_q_PTR_##func)(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);   \
    static _q_PTR_##func _q_##func = 0;                                                   \
    ret q_##func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) { \
        if (_q_##func) { \
            qWarning("QSslSocket: cannot call unresolved function "#func); \
            err; \
        }   \
        funcret _q_##func(a, b, c, d, e, f, g, h, i); \
    }
Definition at line 151 of file qsslsocket_openssl_symbols_p.h.
DUMMYARG
#define DUMMYARG
Definition at line 61 of file qsslsocket_openssl_symbols_p.h.
q_BIO_get_mem_data
#define q_BIO_get_mem_data (b, pp) (int)q_BIO_ctrl(b,BIO_CTRL_INFO,0,(char *)pp)
Definition at line 382 of file qsslsocket_openssl_symbols_p.h.
Referenced by QSslKey::toPem().
q_BIO_pending
#define q_BIO_pending (b) (int)q_BIO_ctrl(b,BIO_CTRL_PENDING,0,NULL)
Definition at line 383 of file qsslsocket_openssl_symbols_p.h.
Referenced by QSslSocketBackendPrivate::transmit().
q_EVP_PKEY_assign_DSA
#define q_EVP_PKEY_assign_DSA (pkey, dsa)
Value:
q_EVP_PKEY_assign((pkey),EVP_PKEY_DSA,\
                    (char *)(dsa))
Definition at line 417 of file qsslsocket_openssl_symbols_p.h.
q_EVP_PKEY_assign_RSA
#define q_EVP_PKEY_assign_RSA (pkey, rsa)
Value:
q_EVP_PKEY_assign((pkey),EVP_PKEY_RSA,\
                    (char *)(rsa))
Definition at line 415 of file qsslsocket_openssl_symbols_p.h.
q_OpenSSL_add_all_algorithms
#define q_OpenSSL_add_all_algorithms () q_OPENSSL_add_all_algorithms_noconf()
Definition at line 422 of file qsslsocket_openssl_symbols_p.h.
Referenced by QSslSocketPrivate::ensureLibraryLoaded().
q_sk_GENERAL_NAME_num
#define q_sk_GENERAL_NAME_num (st) q_SKM_sk_num(GENERAL_NAME, (st))
Definition at line 405 of file qsslsocket_openssl_symbols_p.h.
Referenced by QSslCertificate::alternateSubjectNames().
q_sk_GENERAL_NAME_value
#define q_sk_GENERAL_NAME_value (st, i) q_SKM_sk_value(GENERAL_NAME, (st), (i))
Definition at line 406 of file qsslsocket_openssl_symbols_p.h.
Referenced by QSslCertificate::alternateSubjectNames().
q_sk_SSL_CIPHER_num
#define q_sk_SSL_CIPHER_num (st) q_SKM_sk_num(SSL_CIPHER, (st))
Definition at line 409 of file qsslsocket_openssl_symbols_p.h.
Referenced by QSslSocketPrivate::resetDefaultCiphers().
q_sk_SSL_CIPHER_value
#define q_sk_SSL_CIPHER_value (st, i) q_SKM_sk_value(SSL_CIPHER, (st), (i))
Definition at line 410 of file qsslsocket_openssl_symbols_p.h.
Referenced by QSslSocketPrivate::resetDefaultCiphers().
q_sk_X509_num
#define q_sk_X509_num (st) q_SKM_sk_num(X509, (st))
Definition at line 407 of file qsslsocket_openssl_symbols_p.h.
Referenced by QSslSocketBackendPrivate::STACKOFX509_to_QSslCertificates().
q_sk_X509_value
#define q_sk_X509_value (st, i) q_SKM_sk_value(X509, (st), (i))
Definition at line 408 of file qsslsocket_openssl_symbols_p.h.
Referenced by QSslSocketBackendPrivate::STACKOFX509_to_QSslCertificates().
q_SKM_sk_num
#define q_SKM_sk_num (type, st) ((int (*)(const STACK_OF(type) *))q_sk_num)(st)
Definition at line 403 of file qsslsocket_openssl_symbols_p.h.
q_SKM_sk_value
#define q_SKM_sk_value (type, st, i) ((type * (*)(const STACK_OF(type) *, int))q_sk_value)(st, i)
Definition at line 404 of file qsslsocket_openssl_symbols_p.h.
q_SSL_CTX_add_extra_chain_cert
#define q_SSL_CTX_add_extra_chain_cert (ctx, x509) q_SSL_CTX_ctrl(ctx,SSL_CTRL_EXTRA_CHAIN_CERT,0,(char *)x509)
Definition at line 411 of file qsslsocket_openssl_symbols_p.h.
q_SSL_CTX_set_options
#define q_SSL_CTX_set_options (ctx, op) q_SSL_CTX_ctrl((ctx),SSL_CTRL_OPTIONS,(op),NULL)
Definition at line 402 of file qsslsocket_openssl_symbols_p.h.
Referenced by QSslSocketBackendPrivate::initSslContext().
q_X509_get_notAfter
#define q_X509_get_notAfter (x) X509_get_notAfter(x)
Definition at line 413 of file qsslsocket_openssl_symbols_p.h.
Referenced by QSslCertificatePrivate::QSslCertificate_from_X509().
q_X509_get_notBefore
#define q_X509_get_notBefore (x) X509_get_notBefore(x)
Definition at line 414 of file qsslsocket_openssl_symbols_p.h.
Referenced by QSslCertificatePrivate::QSslCertificate_from_X509().
Function Documentation
q_ASN1_INTEGER_get()
long q_ASN1_INTEGER_get (ASN1_INTEGER * a)
Referenced by QSslCertificate::serialNumber(), and QSslCertificate::version().
q_ASN1_STRING_data()
unsigned char* q_ASN1_STRING_data (ASN1_STRING * a)
Referenced by QSslCertificate::alternateSubjectNames().
q_ASN1_STRING_length()
int q_ASN1_STRING_length (ASN1_STRING * a)
Referenced by QSslCertificate::alternateSubjectNames().
q_ASN1_STRING_to_UTF8()
int q_ASN1_STRING_to_UTF8 (unsigned char ** a, ASN1_STRING * b)
Referenced by _q_mapFromX509Name().
q_BIO_ctrl()
long q_BIO_ctrl (BIO * a, int b, long c, void * d)
q_BIO_free()
int q_BIO_free (BIO * a)
Referenced by QSslKeyPrivate::decodePem(), and QSslKey::toPem().
q_BIO_new()
BIO* q_BIO_new (BIO_METHOD * a)
Referenced by QSslSocketBackendPrivate::initSslContext(), and QSslKey::toPem().
q_BIO_new_mem_buf()
BIO* q_BIO_new_mem_buf (void * a, int b)
Referenced by QSslKeyPrivate::decodePem().
q_BIO_read()
int q_BIO_read (BIO * a, void * b, int c)
Referenced by QSslSocketBackendPrivate::transmit().
q_BIO_s_mem()
BIO_METHOD* q_BIO_s_mem ()
Referenced by QSslSocketBackendPrivate::initSslContext(), and QSslKey::toPem().
q_BIO_write()
int q_BIO_write (BIO * a, const void * b, int c)
Referenced by QSslSocketBackendPrivate::transmit().
q_BN_num_bits()
int q_BN_num_bits (const BIGNUM * a)
Referenced by QSslKey::length().
q_CRYPTO_free()
void q_CRYPTO_free (void * a)
Referenced by _q_mapFromX509Name().
q_CRYPTO_num_locks()
int q_CRYPTO_num_locks ()
Referenced by QOpenSslLocks::QOpenSslLocks(), and QOpenSslLocks::~QOpenSslLocks().
q_CRYPTO_set_id_callback()
void q_CRYPTO_set_id_callback (unsigned long(*)() a)
Referenced by QSslSocketPrivate::deinitialize(), and QSslSocketPrivate::ensureLibraryLoaded().
q_CRYPTO_set_locking_callback()
void q_CRYPTO_set_locking_callback (void(*)(int, int, const char *, int) a)
Referenced by QSslSocketPrivate::deinitialize(), and QSslSocketPrivate::ensureLibraryLoaded().
q_d2i_X509()
X509* q_d2i_X509 (X509 ** a, unsigned char ** b, long c)
Referenced by QSslCertificatePrivate::certificatesFromDer(), and QSslCertificatePrivate::certificatesFromPem().
q_DSA_free()
void q_DSA_free (DSA * a)
Referenced by QSslKeyPrivate::clear().
q_ERR_error_string()
char* q_ERR_error_string (unsigned long a, char * b)
Referenced by QSslSocketBackendPrivate::getErrorsFromOpenSsl().
q_ERR_get_error()
unsigned long q_ERR_get_error ()
Referenced by QSslSocketBackendPrivate::getErrorsFromOpenSsl().
q_EVP_des_ede3_cbc()
const EVP_CIPHER* q_EVP_des_ede3_cbc ()
Referenced by QSslKey::toPem().
q_EVP_PKEY_assign()
int q_EVP_PKEY_assign (EVP_PKEY * a, int b, char * c)
q_EVP_PKEY_free()
void q_EVP_PKEY_free (EVP_PKEY * a)
Referenced by QSslSocketBackendPrivate::destroySslContext(), and QSslCertificate::publicKey().
q_EVP_PKEY_get1_DSA()
DSA* q_EVP_PKEY_get1_DSA (EVP_PKEY * a)
Referenced by QSslCertificate::publicKey().
q_EVP_PKEY_get1_RSA()
RSA* q_EVP_PKEY_get1_RSA (EVP_PKEY * a)
Referenced by QSslCertificate::publicKey().
q_EVP_PKEY_new()
EVP_PKEY* q_EVP_PKEY_new ()
Referenced by QSslSocketBackendPrivate::initSslContext().
q_EVP_PKEY_set1_DSA()
int q_EVP_PKEY_set1_DSA (EVP_PKEY * a, DSA * b)
Referenced by QSslSocketBackendPrivate::initSslContext().
q_EVP_PKEY_set1_RSA()
int q_EVP_PKEY_set1_RSA (EVP_PKEY * a, RSA * b)
Referenced by QSslSocketBackendPrivate::initSslContext().
q_EVP_PKEY_type()
int q_EVP_PKEY_type (int a)
Referenced by QSslCertificate::publicKey().
q_getTimeFromASN1()
QDateTime q_getTimeFromASN1 (const ASN1_TIME * aTime)
Definition at line 893 of file qsslsocket_openssl_symbols.cpp.
Referenced by QSslCertificatePrivate::QSslCertificate_from_X509().
 {
     size_t lTimeLength = aTime->length;
     char *pString = (char *) aTime->data;
     if (aTime->type == V_ASN1_UTCTIME) {
         char lBuffer[24];
         char *pBuffer = lBuffer;
         if ((lTimeLength < 11) || (lTimeLength > 17))
             return QDateTime();
         memcpy(pBuffer, pString, 10);
         pBuffer += 10;
         pString += 10;
         if ((*pString == 'Z') || (*pString == '-') || (*pString == '+')) {
             *pBuffer++ = '0';
             *pBuffer++ = '0';
         } else {
             *pBuffer++ = *pString++;
             *pBuffer++ = *pString++;
             // Skip any fractional seconds...
             if (*pString == '.') {
                 pString++;
                 while ((*pString >= '0') && (*pString <= '9'))
                     pString++;
             }
         }
         *pBuffer++ = 'Z';
         *pBuffer++ = '\0';
         time_t lSecondsFromUCT;
         if (*pString == 'Z') {
             lSecondsFromUCT = 0;
         } else {
             if ((*pString != '+') && (*pString != '-'))
                 return QDateTime();
             lSecondsFromUCT = ((pString[1] - '0') * 10 + (pString[2] - '0')) * 60;
             lSecondsFromUCT += (pString[3] - '0') * 10 + (pString[4] - '0');
             lSecondsFromUCT *= 60;
             if (*pString == '-')
                 lSecondsFromUCT = -lSecondsFromUCT;
         }
         tm lTime;
         lTime.tm_sec = ((lBuffer[10] - '0') * 10) + (lBuffer[11] - '0');
         lTime.tm_min = ((lBuffer[8] - '0') * 10) + (lBuffer[9] - '0');
         lTime.tm_hour = ((lBuffer[6] - '0') * 10) + (lBuffer[7] - '0');
         lTime.tm_mday = ((lBuffer[4] - '0') * 10) + (lBuffer[5] - '0');
         lTime.tm_mon = (((lBuffer[2] - '0') * 10) + (lBuffer[3] - '0')) - 1;
         lTime.tm_year = ((lBuffer[0] - '0') * 10) + (lBuffer[1] - '0');
         if (lTime.tm_year < 50)
             lTime.tm_year += 100; // RFC 2459
         QDate resDate(lTime.tm_year + 1900, lTime.tm_mon + 1, lTime.tm_mday);
         QTime resTime(lTime.tm_hour, lTime.tm_min, lTime.tm_sec);
         QDateTime result(resDate, resTime, Qt::UTC);
         result = result.addSecs(lSecondsFromUCT);
         return result;
     } else if (aTime->type == V_ASN1_GENERALIZEDTIME) {
         if (lTimeLength < 15)
             return QDateTime(); // hopefully never triggered
         // generalized time is always YYYYMMDDHHMMSSZ (RFC 2459, section 4.1.2.5.2)
         tm lTime;
         lTime.tm_sec = ((pString[12] - '0') * 10) + (pString[13] - '0');
         lTime.tm_min = ((pString[10] - '0') * 10) + (pString[11] - '0');
         lTime.tm_hour = ((pString[8] - '0') * 10) + (pString[9] - '0');
         lTime.tm_mday = ((pString[6] - '0') * 10) + (pString[7] - '0');
         lTime.tm_mon = (((pString[4] - '0') * 10) + (pString[5] - '0'));
         lTime.tm_year = ((pString[0] - '0') * 1000) + ((pString[1] - '0') * 100) +
                         ((pString[2] - '0') * 10) + (pString[3] - '0');
         QDate resDate(lTime.tm_year, lTime.tm_mon, lTime.tm_mday);
         QTime resTime(lTime.tm_hour, lTime.tm_min, lTime.tm_sec);
         QDateTime result(resDate, resTime, Qt::UTC);
         return result;
     } else {
         qWarning("unsupported date format detected");
         return QDateTime();
     }
 }
q_i2d_X509()
int q_i2d_X509 (X509 * a, unsigned char ** b)
Referenced by QSslCertificatePrivate::QByteArray_from_X509().
q_OBJ_nid2sn()
const char* q_OBJ_nid2sn (int a)
Referenced by _q_mapFromX509Name().
q_OBJ_obj2nid()
int q_OBJ_obj2nid (const ASN1_OBJECT * a)
Referenced by _q_mapFromX509Name().
q_OPENSSL_add_all_algorithms_conf()
void q_OPENSSL_add_all_algorithms_conf ()
q_OPENSSL_add_all_algorithms_noconf()
void q_OPENSSL_add_all_algorithms_noconf ()
q_PEM_read_bio_DSA_PUBKEY()
DSA* q_PEM_read_bio_DSA_PUBKEY (BIO * a, DSA ** b, pem_password_cb * c, void * d)
Referenced by QSslKeyPrivate::decodePem().
q_PEM_read_bio_DSAPrivateKey()
DSA* q_PEM_read_bio_DSAPrivateKey (BIO * a, DSA ** b, pem_password_cb * c, void * d)
Referenced by QSslKeyPrivate::decodePem().
q_PEM_read_bio_RSA_PUBKEY()
RSA* q_PEM_read_bio_RSA_PUBKEY (BIO * a, RSA ** b, pem_password_cb * c, void * d)
Referenced by QSslKeyPrivate::decodePem().
q_PEM_read_bio_RSAPrivateKey()
RSA* q_PEM_read_bio_RSAPrivateKey (BIO * a, RSA ** b, pem_password_cb * c, void * d)
Referenced by QSslKeyPrivate::decodePem().
q_PEM_write_bio_DSA_PUBKEY()
int q_PEM_write_bio_DSA_PUBKEY (BIO * a, DSA * b)
Referenced by QSslKey::toPem().
q_PEM_write_bio_DSAPrivateKey()
int q_PEM_write_bio_DSAPrivateKey (BIO * a, DSA * b, const EVP_CIPHER * c, unsigned char * d, int e, pem_password_cb * f, void * g)
Referenced by QSslKey::toPem().
q_PEM_write_bio_RSA_PUBKEY()
int q_PEM_write_bio_RSA_PUBKEY (BIO * a, RSA * b)
Referenced by QSslKey::toPem().
q_PEM_write_bio_RSAPrivateKey()
int q_PEM_write_bio_RSAPrivateKey (BIO * a, RSA * b, const EVP_CIPHER * c, unsigned char * d, int e, pem_password_cb * f, void * g)
Referenced by QSslKey::toPem().
q_RAND_seed()
void q_RAND_seed (const void * a, int b)
Referenced by QSslSocketPrivate::ensureLibraryLoaded().
q_RAND_status()
int q_RAND_status ()
Referenced by QSslSocketPrivate::ensureLibraryLoaded().
q_resolveOpenSslSymbols()
bool q_resolveOpenSslSymbols ()
Definition at line 574 of file qsslsocket_openssl_symbols.cpp.
Referenced by QSslSocketPrivate::ensureLibraryLoaded(), and q_resolveOpenSslSymbols().
 {
     static volatile bool symbolsResolved = false;
     static volatile bool triedToResolveSymbols = false;
 #ifndef QT_NO_THREAD
     QMutexLocker locker(QMutexPool::globalInstanceGet((void *)&q_SSL_library_init));
 #endif
     if (symbolsResolved)
         return true;
     if (triedToResolveSymbols)
         return false;
     triedToResolveSymbols = true;
 #ifdef Q_OS_WIN
     QPair<QSystemLibrary *, QSystemLibrary *> libs = loadOpenSslWin32();
 #else
     QPair<QLibrary *, QLibrary *> libs = loadOpenSsl();
 #endif
     if (!libs.first || !libs.second)
         // failed to load them
         return false;
 #ifdef Q_OS_SYMBIAN
 #ifdef SSLEAY_MACROS
     RESOLVEFUNC(ASN1_dup, 125, libs.second )
 #endif
     RESOLVEFUNC(ASN1_INTEGER_get, 48, libs.second )
     RESOLVEFUNC(ASN1_STRING_data, 71, libs.second )
     RESOLVEFUNC(ASN1_STRING_length, 76, libs.second )
     RESOLVEFUNC(ASN1_STRING_to_UTF8, 86, libs.second )
     RESOLVEFUNC(BIO_ctrl, 184, libs.second )
     RESOLVEFUNC(BIO_free, 209, libs.second )
     RESOLVEFUNC(BIO_new, 222, libs.second )
     RESOLVEFUNC(BIO_new_mem_buf, 230, libs.second )
     RESOLVEFUNC(BIO_read, 244, libs.second )
     RESOLVEFUNC(BIO_s_mem, 251, libs.second )
     RESOLVEFUNC(BIO_write, 269, libs.second )
     RESOLVEFUNC(BN_num_bits, 387, libs.second )
     RESOLVEFUNC(CRYPTO_free, 469, libs.second )
     RESOLVEFUNC(CRYPTO_num_locks, 500, libs.second )
     RESOLVEFUNC(CRYPTO_set_id_callback, 513, libs.second )
     RESOLVEFUNC(CRYPTO_set_locking_callback, 516, libs.second )
     RESOLVEFUNC(DSA_free, 594, libs.second )
     RESOLVEFUNC(ERR_error_string, 744, libs.second )
     RESOLVEFUNC(ERR_get_error, 749, libs.second )
     RESOLVEFUNC(EVP_des_ede3_cbc, 919, libs.second )
     RESOLVEFUNC(EVP_PKEY_assign, 859, libs.second )
     RESOLVEFUNC(EVP_PKEY_set1_RSA, 880, libs.second )
     RESOLVEFUNC(EVP_PKEY_set1_DSA, 879, libs.second )
     RESOLVEFUNC(EVP_PKEY_free, 867, libs.second )
     RESOLVEFUNC(EVP_PKEY_get1_DSA, 869, libs.second )
     RESOLVEFUNC(EVP_PKEY_get1_RSA, 870, libs.second )
     RESOLVEFUNC(EVP_PKEY_new, 876, libs.second )
     RESOLVEFUNC(EVP_PKEY_type, 882, libs.second )
     RESOLVEFUNC(OBJ_nid2sn, 1036, libs.second )
     RESOLVEFUNC(OBJ_obj2nid, 1037, libs.second )
 #ifdef SSLEAY_MACROS // ### verify
     RESOLVEFUNC(PEM_ASN1_read_bio, 1180, libs.second )
 #else
     RESOLVEFUNC(PEM_read_bio_DSAPrivateKey, 1219, libs.second )
     RESOLVEFUNC(PEM_read_bio_RSAPrivateKey, 1228, libs.second )
     RESOLVEFUNC(PEM_write_bio_DSAPrivateKey, 1260, libs.second )
     RESOLVEFUNC(PEM_write_bio_RSAPrivateKey, 1271, libs.second )
 #endif
     RESOLVEFUNC(PEM_read_bio_DSA_PUBKEY, 1220, libs.second )
     RESOLVEFUNC(PEM_read_bio_RSA_PUBKEY, 1230, libs.second )
     RESOLVEFUNC(PEM_write_bio_DSA_PUBKEY, 1261, libs.second )
     RESOLVEFUNC(PEM_write_bio_RSA_PUBKEY, 1273, libs.second )
     RESOLVEFUNC(RAND_seed, 1426, libs.second )
     RESOLVEFUNC(RAND_status, 1429, libs.second )
     RESOLVEFUNC(RSA_free, 1450, libs.second )
     RESOLVEFUNC(sk_free, 2571, libs.second )
     RESOLVEFUNC(sk_num, 2576, libs.second )
     RESOLVEFUNC(sk_pop_free, 2578, libs.second )
     RESOLVEFUNC(sk_value, 2585, libs.second )
     RESOLVEFUNC(SSL_CIPHER_description, 11, libs.first )
     RESOLVEFUNC(SSL_CTX_check_private_key, 21, libs.first )
     RESOLVEFUNC(SSL_CTX_ctrl, 22, libs.first )
     RESOLVEFUNC(SSL_CTX_free, 24, libs.first )
     RESOLVEFUNC(SSL_CTX_new, 35, libs.first )
     RESOLVEFUNC(SSL_CTX_set_cipher_list, 40, libs.first )
     RESOLVEFUNC(SSL_CTX_set_default_verify_paths, 44, libs.first )
     RESOLVEFUNC(SSL_CTX_set_verify, 56, libs.first )
     RESOLVEFUNC(SSL_CTX_set_verify_depth, 57, libs.first )
     RESOLVEFUNC(SSL_CTX_use_certificate, 64, libs.first )
     RESOLVEFUNC(SSL_CTX_use_certificate_file, 67, libs.first )
     RESOLVEFUNC(SSL_CTX_use_PrivateKey, 58, libs.first )
     RESOLVEFUNC(SSL_CTX_use_RSAPrivateKey, 61, libs.first )
     RESOLVEFUNC(SSL_CTX_use_PrivateKey_file, 60, libs.first )
     RESOLVEFUNC(SSL_accept, 82, libs.first )
     RESOLVEFUNC(SSL_clear, 92, libs.first )
     RESOLVEFUNC(SSL_connect, 93, libs.first )
     RESOLVEFUNC(SSL_free, 99, libs.first )
     RESOLVEFUNC(SSL_get_ciphers, 104, libs.first )
     RESOLVEFUNC(SSL_get_current_cipher, 106, libs.first )
     RESOLVEFUNC(SSL_get_error, 110, libs.first )
     RESOLVEFUNC(SSL_get_peer_cert_chain, 117, libs.first )
     RESOLVEFUNC(SSL_get_peer_certificate, 118, libs.first )
     RESOLVEFUNC(SSL_get_verify_result, 132, libs.first )
     RESOLVEFUNC(SSL_library_init, 137, libs.first )
     RESOLVEFUNC(SSL_load_error_strings, 139, libs.first )
     RESOLVEFUNC(SSL_new, 140, libs.first )
 #if OPENSSL_VERSION_NUMBER >= 0x0090806fL && !defined(OPENSSL_NO_TLSEXT)
     RESOLVEFUNC(SSL_ctrl, 95, libs.first )
 #endif
     RESOLVEFUNC(SSL_read, 143, libs.first )
     RESOLVEFUNC(SSL_set_accept_state, 148, libs.first )
     RESOLVEFUNC(SSL_set_bio, 149, libs.first )
     RESOLVEFUNC(SSL_set_connect_state, 152, libs.first )
     RESOLVEFUNC(SSL_shutdown, 173, libs.first )
     RESOLVEFUNC(SSL_write, 188, libs.first )
     RESOLVEFUNC(SSLv2_client_method, 192, libs.first )
     RESOLVEFUNC(SSLv3_client_method, 195, libs.first )
     RESOLVEFUNC(SSLv23_client_method, 189, libs.first )
     RESOLVEFUNC(TLSv1_client_method, 198, libs.first )
     RESOLVEFUNC(SSLv2_server_method, 194, libs.first )
     RESOLVEFUNC(SSLv3_server_method, 197, libs.first )
     RESOLVEFUNC(SSLv23_server_method, 191, libs.first )
     RESOLVEFUNC(TLSv1_server_method, 200, libs.first )
     RESOLVEFUNC(SSL_CTX_load_verify_locations, 34, libs.first )
     RESOLVEFUNC(X509_NAME_entry_count, 1821, libs.second )
     RESOLVEFUNC(X509_NAME_get_entry, 1823, libs.second )
     RESOLVEFUNC(X509_NAME_ENTRY_get_data, 1808, libs.second )
     RESOLVEFUNC(X509_NAME_ENTRY_get_object, 1809, libs.second )
     RESOLVEFUNC(X509_PUBKEY_get, 1844, libs.second )
     RESOLVEFUNC(X509_STORE_free, 1939, libs.second )
     RESOLVEFUNC(X509_STORE_new, 1942, libs.second )
     RESOLVEFUNC(X509_STORE_add_cert, 1936, libs.second )
     RESOLVEFUNC(X509_STORE_CTX_free, 1907, libs.second )
     RESOLVEFUNC(X509_STORE_CTX_init, 1919, libs.second )
     RESOLVEFUNC(X509_STORE_CTX_new, 1920, libs.second )
     RESOLVEFUNC(X509_STORE_CTX_set_purpose, 1931, libs.second )
     RESOLVEFUNC(X509_cmp, 1992, libs.second )
 #ifndef SSLEAY_MACROS
     RESOLVEFUNC(X509_dup, 1997, libs.second )
 #endif
     RESOLVEFUNC(X509_EXTENSION_get_object, 1785, libs.second )
     RESOLVEFUNC(X509_free, 2001, libs.second )
     RESOLVEFUNC(X509_get_ext, 2012, libs.second )
     RESOLVEFUNC(X509_get_ext_count, 2016, libs.second )
     RESOLVEFUNC(X509_get_ext_d2i, 2017, libs.second )
     RESOLVEFUNC(X509_get_issuer_name, 2018, libs.second )
     RESOLVEFUNC(X509_get_subject_name, 2022, libs.second )
     RESOLVEFUNC(X509_verify_cert, 2069, libs.second )
     RESOLVEFUNC(d2i_X509, 2309, libs.second )
     RESOLVEFUNC(i2d_X509, 2489, libs.second )
 #ifdef SSLEAY_MACROS
     RESOLVEFUNC(i2d_DSAPrivateKey, 2395, libs.second )
     RESOLVEFUNC(i2d_RSAPrivateKey, 2476, libs.second )
     RESOLVEFUNC(d2i_DSAPrivateKey, 2220, libs.second )
     RESOLVEFUNC(d2i_RSAPrivateKey, 2296, libs.second )
 #endif
     RESOLVEFUNC(OPENSSL_add_all_algorithms_noconf, 1153, libs.second )
     RESOLVEFUNC(OPENSSL_add_all_algorithms_conf, 1152, libs.second )
     RESOLVEFUNC(SSLeay, 1504, libs.second )
 #else // Q_OS_SYMBIAN
 #ifdef SSLEAY_MACROS
     RESOLVEFUNC(ASN1_dup)
 #endif
     RESOLVEFUNC(ASN1_INTEGER_get)
     RESOLVEFUNC(ASN1_STRING_data)
     RESOLVEFUNC(ASN1_STRING_length)
     RESOLVEFUNC(ASN1_STRING_to_UTF8)
     RESOLVEFUNC(BIO_ctrl)
     RESOLVEFUNC(BIO_free)
     RESOLVEFUNC(BIO_new)
     RESOLVEFUNC(BIO_new_mem_buf)
     RESOLVEFUNC(BIO_read)
     RESOLVEFUNC(BIO_s_mem)
     RESOLVEFUNC(BIO_write)
     RESOLVEFUNC(BN_num_bits)
     RESOLVEFUNC(CRYPTO_free)
     RESOLVEFUNC(CRYPTO_num_locks)
     RESOLVEFUNC(CRYPTO_set_id_callback)
     RESOLVEFUNC(CRYPTO_set_locking_callback)
     RESOLVEFUNC(DSA_free)
     RESOLVEFUNC(ERR_error_string)
     RESOLVEFUNC(ERR_get_error)
     RESOLVEFUNC(EVP_des_ede3_cbc)
     RESOLVEFUNC(EVP_PKEY_assign)
     RESOLVEFUNC(EVP_PKEY_set1_RSA)
     RESOLVEFUNC(EVP_PKEY_set1_DSA)
     RESOLVEFUNC(EVP_PKEY_free)
     RESOLVEFUNC(EVP_PKEY_get1_DSA)
     RESOLVEFUNC(EVP_PKEY_get1_RSA)
     RESOLVEFUNC(EVP_PKEY_new)
     RESOLVEFUNC(EVP_PKEY_type)
     RESOLVEFUNC(OBJ_nid2sn)
     RESOLVEFUNC(OBJ_obj2nid)
 #ifdef SSLEAY_MACROS // ### verify
     RESOLVEFUNC(PEM_ASN1_read_bio)
 #else
     RESOLVEFUNC(PEM_read_bio_DSAPrivateKey)
     RESOLVEFUNC(PEM_read_bio_RSAPrivateKey)
     RESOLVEFUNC(PEM_write_bio_DSAPrivateKey)
     RESOLVEFUNC(PEM_write_bio_RSAPrivateKey)
 #endif
     RESOLVEFUNC(PEM_read_bio_DSA_PUBKEY)
     RESOLVEFUNC(PEM_read_bio_RSA_PUBKEY)
     RESOLVEFUNC(PEM_write_bio_DSA_PUBKEY)
     RESOLVEFUNC(PEM_write_bio_RSA_PUBKEY)
     RESOLVEFUNC(RAND_seed)
     RESOLVEFUNC(RAND_status)
     RESOLVEFUNC(RSA_free)
     RESOLVEFUNC(sk_free)
     RESOLVEFUNC(sk_num)
     RESOLVEFUNC(sk_pop_free)
     RESOLVEFUNC(sk_value)
     RESOLVEFUNC(SSL_CIPHER_description)
     RESOLVEFUNC(SSL_CTX_check_private_key)
     RESOLVEFUNC(SSL_CTX_ctrl)
     RESOLVEFUNC(SSL_CTX_free)
     RESOLVEFUNC(SSL_CTX_new)
     RESOLVEFUNC(SSL_CTX_set_cipher_list)
     RESOLVEFUNC(SSL_CTX_set_default_verify_paths)
     RESOLVEFUNC(SSL_CTX_set_verify)
     RESOLVEFUNC(SSL_CTX_set_verify_depth)
     RESOLVEFUNC(SSL_CTX_use_certificate)
     RESOLVEFUNC(SSL_CTX_use_certificate_file)
     RESOLVEFUNC(SSL_CTX_use_PrivateKey)
     RESOLVEFUNC(SSL_CTX_use_RSAPrivateKey)
     RESOLVEFUNC(SSL_CTX_use_PrivateKey_file)
     RESOLVEFUNC(SSL_accept)
     RESOLVEFUNC(SSL_clear)
     RESOLVEFUNC(SSL_connect)
     RESOLVEFUNC(SSL_free)
     RESOLVEFUNC(SSL_get_ciphers)
     RESOLVEFUNC(SSL_get_current_cipher)
     RESOLVEFUNC(SSL_get_error)
     RESOLVEFUNC(SSL_get_peer_cert_chain)
     RESOLVEFUNC(SSL_get_peer_certificate)
     RESOLVEFUNC(SSL_get_verify_result)
     RESOLVEFUNC(SSL_library_init)
     RESOLVEFUNC(SSL_load_error_strings)
     RESOLVEFUNC(SSL_new)
 #if OPENSSL_VERSION_NUMBER >= 0x0090806fL && !defined(OPENSSL_NO_TLSEXT)
     RESOLVEFUNC(SSL_ctrl)
 #endif
     RESOLVEFUNC(SSL_read)
     RESOLVEFUNC(SSL_set_accept_state)
     RESOLVEFUNC(SSL_set_bio)
     RESOLVEFUNC(SSL_set_connect_state)
     RESOLVEFUNC(SSL_shutdown)
     RESOLVEFUNC(SSL_write)
 #ifndef OPENSSL_NO_SSL2
     RESOLVEFUNC(SSLv2_client_method)
 #endif
     RESOLVEFUNC(SSLv3_client_method)
     RESOLVEFUNC(SSLv23_client_method)
     RESOLVEFUNC(TLSv1_client_method)
 #ifndef OPENSSL_NO_SSL2
     RESOLVEFUNC(SSLv2_server_method)
 #endif
     RESOLVEFUNC(SSLv3_server_method)
     RESOLVEFUNC(SSLv23_server_method)
     RESOLVEFUNC(TLSv1_server_method)
     RESOLVEFUNC(X509_NAME_entry_count)
     RESOLVEFUNC(X509_NAME_get_entry)
     RESOLVEFUNC(X509_NAME_ENTRY_get_data)
     RESOLVEFUNC(X509_NAME_ENTRY_get_object)
     RESOLVEFUNC(X509_PUBKEY_get)
     RESOLVEFUNC(X509_STORE_free)
     RESOLVEFUNC(X509_STORE_new)
     RESOLVEFUNC(X509_STORE_add_cert)
     RESOLVEFUNC(X509_STORE_CTX_free)
     RESOLVEFUNC(X509_STORE_CTX_init)
     RESOLVEFUNC(X509_STORE_CTX_new)
     RESOLVEFUNC(X509_STORE_CTX_set_purpose)
     RESOLVEFUNC(X509_STORE_CTX_get_error)
     RESOLVEFUNC(X509_STORE_CTX_get_error_depth)
     RESOLVEFUNC(X509_STORE_CTX_get_current_cert)
     RESOLVEFUNC(X509_STORE_CTX_get_chain)
     RESOLVEFUNC(X509_cmp)
 #ifndef SSLEAY_MACROS
     RESOLVEFUNC(X509_dup)
 #endif
     RESOLVEFUNC(X509_EXTENSION_get_object)
     RESOLVEFUNC(X509_free)
     RESOLVEFUNC(X509_get_ext)
     RESOLVEFUNC(X509_get_ext_count)
     RESOLVEFUNC(X509_get_ext_d2i)
     RESOLVEFUNC(X509_get_issuer_name)
     RESOLVEFUNC(X509_get_subject_name)
     RESOLVEFUNC(X509_verify_cert)
     RESOLVEFUNC(d2i_X509)
     RESOLVEFUNC(i2d_X509)
 #ifdef SSLEAY_MACROS
     RESOLVEFUNC(i2d_DSAPrivateKey)
     RESOLVEFUNC(i2d_RSAPrivateKey)
     RESOLVEFUNC(d2i_DSAPrivateKey)
     RESOLVEFUNC(d2i_RSAPrivateKey)
 #endif
     RESOLVEFUNC(OPENSSL_add_all_algorithms_noconf)
     RESOLVEFUNC(OPENSSL_add_all_algorithms_conf)
     RESOLVEFUNC(SSL_CTX_load_verify_locations)
     RESOLVEFUNC(SSLeay)
 #endif // Q_OS_SYMBIAN
     symbolsResolved = true;
     delete libs.first;
     delete libs.second;
     return true;
 }
q_RSA_free()
void q_RSA_free (RSA * a)
Referenced by QSslKeyPrivate::clear().
q_sk_free()
void q_sk_free (STACK * a)
Referenced by QSslCertificate::alternateSubjectNames().
q_sk_num()
int q_sk_num (STACK * a)
q_sk_pop_free()
void q_sk_pop_free (STACK * a, void(*)(void *) b)
Referenced by QSslCertificate::alternateSubjectNames().
q_sk_value()
char* q_sk_value (STACK * a, int b)
q_SSL_accept()
int q_SSL_accept (SSL * a)
Referenced by QSslSocketBackendPrivate::startHandshake().
q_SSL_CIPHER_description()
char* q_SSL_CIPHER_description (SSL_CIPHER * a, char * b, int c)
Referenced by QSslSocketBackendPrivate::QSslCipher_from_SSL_CIPHER().
q_SSL_clear()
int q_SSL_clear (SSL * a)
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSL_connect()
int q_SSL_connect (SSL * a)
Referenced by QSslSocketBackendPrivate::startHandshake().
q_SSL_CTX_check_private_key()
int q_SSL_CTX_check_private_key (SSL_CTX * a)
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSL_CTX_ctrl()
long q_SSL_CTX_ctrl (SSL_CTX * a, int b, long c, void * d)
q_SSL_CTX_free()
void q_SSL_CTX_free (SSL_CTX * a)
Referenced by QSslSocketBackendPrivate::destroySslContext(), and QSslSocketPrivate::resetDefaultCiphers().
q_SSL_CTX_load_verify_locations()
int q_SSL_CTX_load_verify_locations (SSL_CTX * ctx, const char * CAfile, const char * CApath)
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSL_CTX_new()
SSL_CTX* q_SSL_CTX_new (SSL_METHOD * a)
Referenced by QSslSocketBackendPrivate::initSslContext(), and QSslSocketPrivate::resetDefaultCiphers().
q_SSL_CTX_set_cipher_list()
int q_SSL_CTX_set_cipher_list (SSL_CTX * a, const char * b)
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSL_CTX_set_default_verify_paths()
int q_SSL_CTX_set_default_verify_paths (SSL_CTX * a)
q_SSL_CTX_set_verify()
void q_SSL_CTX_set_verify (SSL_CTX * a, int b, int(*)(int, X509_STORE_CTX *) c)
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSL_CTX_set_verify_depth()
void q_SSL_CTX_set_verify_depth (SSL_CTX * a, int b)
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSL_CTX_use_certificate()
int q_SSL_CTX_use_certificate (SSL_CTX * a, X509 * b)
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSL_CTX_use_certificate_file()
int q_SSL_CTX_use_certificate_file (SSL_CTX * a, const char * b, int c)
q_SSL_CTX_use_PrivateKey()
int q_SSL_CTX_use_PrivateKey (SSL_CTX * a, EVP_PKEY * b)
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSL_CTX_use_PrivateKey_file()
int q_SSL_CTX_use_PrivateKey_file (SSL_CTX * a, const char * b, int c)
q_SSL_CTX_use_RSAPrivateKey()
int q_SSL_CTX_use_RSAPrivateKey (SSL_CTX * a, RSA * b)
q_SSL_free()
void q_SSL_free (SSL * a)
Referenced by QSslSocketBackendPrivate::destroySslContext(), and QSslSocketPrivate::resetDefaultCiphers().
q_SSL_get_current_cipher()
SSL_CIPHER* q_SSL_get_current_cipher (SSL * a)
Referenced by QSslSocketBackendPrivate::sessionCipher().
q_SSL_get_error()
int q_SSL_get_error (SSL * a, int b)
Referenced by QSslSocketBackendPrivate::startHandshake(), and QSslSocketBackendPrivate::transmit().
q_SSL_get_peer_certificate()
X509* q_SSL_get_peer_certificate (SSL * a)
Referenced by QSslSocketBackendPrivate::startHandshake().
q_SSL_get_verify_result()
long q_SSL_get_verify_result (SSL * a)
q_SSL_library_init()
int q_SSL_library_init ()
Referenced by QSslSocketPrivate::ensureLibraryLoaded(), QSslSocketBackendPrivate::initSslContext(), and q_resolveOpenSslSymbols().
q_SSL_load_error_strings()
void q_SSL_load_error_strings ()
Referenced by QSslSocketPrivate::ensureLibraryLoaded().
q_SSL_new()
SSL* q_SSL_new (SSL_CTX * a)
Referenced by QSslSocketBackendPrivate::initSslContext(), and QSslSocketPrivate::resetDefaultCiphers().
q_SSL_read()
int q_SSL_read (SSL * a, void * b, int c)
Referenced by QSslSocketBackendPrivate::transmit().
q_SSL_set_accept_state()
void q_SSL_set_accept_state (SSL * a)
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSL_set_bio()
void q_SSL_set_bio (SSL * a, BIO * b, BIO * c)
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSL_set_connect_state()
void q_SSL_set_connect_state (SSL * a)
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSL_shutdown()
int q_SSL_shutdown (SSL * a)
Referenced by QSslSocketBackendPrivate::disconnectFromHost().
q_SSL_write()
int q_SSL_write (SSL * a, const void * b, int c)
Referenced by QSslSocketBackendPrivate::transmit().
q_SSLeay()
long q_SSLeay ()
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSLv23_client_method()
SSL_METHOD* q_SSLv23_client_method ()
Referenced by QSslSocketBackendPrivate::initSslContext(), and QSslSocketPrivate::resetDefaultCiphers().
q_SSLv23_server_method()
SSL_METHOD* q_SSLv23_server_method ()
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSLv2_client_method()
SSL_METHOD* q_SSLv2_client_method ()
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSLv2_server_method()
SSL_METHOD* q_SSLv2_server_method ()
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSLv3_client_method()
SSL_METHOD* q_SSLv3_client_method ()
Referenced by QSslSocketBackendPrivate::initSslContext().
q_SSLv3_server_method()
SSL_METHOD* q_SSLv3_server_method ()
Referenced by QSslSocketBackendPrivate::initSslContext().
q_TLSv1_client_method()
SSL_METHOD* q_TLSv1_client_method ()
Referenced by QSslSocketBackendPrivate::initSslContext().
q_TLSv1_server_method()
SSL_METHOD* q_TLSv1_server_method ()
Referenced by QSslSocketBackendPrivate::initSslContext().
q_X509_cmp()
int q_X509_cmp (X509 * a, X509 * b)
Referenced by QSslCertificate::operator==().
q_X509_dup()
X509* q_X509_dup (X509 * a)
Referenced by QSslCertificatePrivate::init(), and QSslCertificatePrivate::QSslCertificate_from_X509().
q_X509_EXTENSION_get_object()
ASN1_OBJECT* q_X509_EXTENSION_get_object (X509_EXTENSION * a)
q_X509_free()
void q_X509_free (X509 * a)
Referenced by QSslCertificatePrivate::certificatesFromDer(), QSslCertificatePrivate::certificatesFromPem(), QSslSocketBackendPrivate::startHandshake(), and QSslCertificatePrivate::~QSslCertificatePrivate().
q_X509_get_ext()
X509_EXTENSION* q_X509_get_ext (X509 * a, int b)
q_X509_get_ext_count()
int q_X509_get_ext_count (X509 * a)
q_X509_get_ext_d2i()
void* q_X509_get_ext_d2i (X509 * a, int b, int * c, int * d)
Referenced by QSslCertificate::alternateSubjectNames().
q_X509_get_issuer_name()
X509_NAME* q_X509_get_issuer_name (X509 * a)
Referenced by QSslCertificate::issuerInfo().
q_X509_get_subject_name()
X509_NAME* q_X509_get_subject_name (X509 * a)
Referenced by QSslCertificate::subjectInfo().
q_X509_NAME_entry_count()
int q_X509_NAME_entry_count (X509_NAME * a)
Referenced by _q_mapFromX509Name().
q_X509_NAME_ENTRY_get_data()
ASN1_STRING* q_X509_NAME_ENTRY_get_data (X509_NAME_ENTRY * a)
Referenced by _q_mapFromX509Name().
q_X509_NAME_ENTRY_get_object()
ASN1_OBJECT* q_X509_NAME_ENTRY_get_object (X509_NAME_ENTRY * a)
Referenced by _q_mapFromX509Name().
q_X509_NAME_get_entry()
X509_NAME_ENTRY* q_X509_NAME_get_entry (X509_NAME * a, int b)
Referenced by _q_mapFromX509Name().
q_X509_PUBKEY_get()
EVP_PKEY* q_X509_PUBKEY_get (X509_PUBKEY * a)
Referenced by QSslCertificate::publicKey().
q_X509_STORE_add_cert()
int q_X509_STORE_add_cert (X509_STORE * ctx, X509 * x)
Referenced by QSslSocketBackendPrivate::initSslContext().
q_X509_STORE_CTX_free()
void q_X509_STORE_CTX_free (X509_STORE_CTX * storeCtx)
q_X509_STORE_CTX_get_current_cert()
X509* q_X509_STORE_CTX_get_current_cert (X509_STORE_CTX * ctx)
q_X509_STORE_CTX_get_error()
int q_X509_STORE_CTX_get_error (X509_STORE_CTX * ctx)
Referenced by q_X509Callback().
q_X509_STORE_CTX_get_error_depth()
int q_X509_STORE_CTX_get_error_depth (X509_STORE_CTX * ctx)
Referenced by q_X509Callback().
q_X509_STORE_CTX_init()
int q_X509_STORE_CTX_init (X509_STORE_CTX * ctx, X509_STORE * store, X509 * x509, STACK_OF(X509) * chain)
q_X509_STORE_CTX_new()
X509_STORE_CTX* q_X509_STORE_CTX_new ()
q_X509_STORE_CTX_set_purpose()
int q_X509_STORE_CTX_set_purpose (X509_STORE_CTX * ctx, int purpose)
q_X509_STORE_free()
void q_X509_STORE_free (X509_STORE * store)
q_X509_STORE_new()
X509_STORE* q_X509_STORE_new ()
q_X509_verify_cert()
int q_X509_verify_cert (X509_STORE_CTX * ctx)
STACK_OF() [1/2]
STACK_OF (SSL_CIPHER)
STACK_OF() [2/2]
STACK_OF (X509)