Qt 4.8: /src/network/ssl/qsslsocket_openssl.cpp File Reference
qsslsocket_openssl.cpp File Reference
#include "qsslsocket_openssl_p.h"
#include "qsslsocket_openssl_symbols_p.h"
#include "qsslsocket.h"
#include "qsslcertificate_p.h"
#include "qsslcipher_p.h"
#include <QtCore/qdatetime.h>
#include <QtCore/qdebug.h>
#include <QtCore/qdir.h>
#include <QtCore/qdiriterator.h>
#include <QtCore/qelapsedtimer.h>
#include <QtCore/qfile.h>
#include <QtCore/qfileinfo.h>
#include <QtCore/qmutex.h>
#include <QtCore/qthread.h>
#include <QtCore/qurl.h>
#include <QtCore/qvarlengtharray.h>
#include <QLibrary>
Classes
class QOpenSslLocks
struct QSslErrorList
Macros
#define kSecTrustSettingsDomainSystem 2
Functions
static QSslError _q_OpenSSL_to_QSslError (int errorCode, const QSslCertificate &cert)
static unsigned long id_function ()
static void locking_function (int mode, int lockNumber, const char *, int)
static int q_X509Callback (int ok, X509_STORE_CTX *ctx)
Macro Definition Documentation
kSecTrustSettingsDomainSystem
#define kSecTrustSettingsDomainSystem 2
Definition at line 73 of file qsslsocket_openssl.cpp.
Referenced by QSslSocketPrivate::systemCaCertificates().
Function Documentation
_q_OpenSSL_to_QSslError()
static QSslError _q_OpenSSL_to_QSslError (int errorCode, const QSslCertificate & cert) static
Definition at line 1205 of file qsslsocket_openssl.cpp.
Referenced by QSslSocketBackendPrivate::startHandshake().
 {
     QSslError error;
     switch (errorCode) {
     case X509_V_OK:
         // X509_V_OK is also reported if the peer had no certificate.
         break;
     case X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT:
         error = QSslError(QSslError::UnableToGetIssuerCertificate, cert); break;
     case X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE:
         error = QSslError(QSslError::UnableToDecryptCertificateSignature, cert); break;
     case X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY:
         error = QSslError(QSslError::UnableToDecodeIssuerPublicKey, cert); break;
     case X509_V_ERR_CERT_SIGNATURE_FAILURE:
         error = QSslError(QSslError::CertificateSignatureFailed, cert); break;
     case X509_V_ERR_CERT_NOT_YET_VALID:
         error = QSslError(QSslError::CertificateNotYetValid, cert); break;
     case X509_V_ERR_CERT_HAS_EXPIRED:
         error = QSslError(QSslError::CertificateExpired, cert); break;
     case X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD:
         error = QSslError(QSslError::InvalidNotBeforeField, cert); break;
     case X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD:
         error = QSslError(QSslError::InvalidNotAfterField, cert); break;
     case X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT:
         error = QSslError(QSslError::SelfSignedCertificate, cert); break;
     case X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN:
         error = QSslError(QSslError::SelfSignedCertificateInChain, cert); break;
     case X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY:
         error = QSslError(QSslError::UnableToGetLocalIssuerCertificate, cert); break;
     case X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE:
         error = QSslError(QSslError::UnableToVerifyFirstCertificate, cert); break;
     case X509_V_ERR_CERT_REVOKED:
         error = QSslError(QSslError::CertificateRevoked, cert); break;
     case X509_V_ERR_INVALID_CA:
         error = QSslError(QSslError::InvalidCaCertificate, cert); break;
     case X509_V_ERR_PATH_LENGTH_EXCEEDED:
         error = QSslError(QSslError::PathLengthExceeded, cert); break;
     case X509_V_ERR_INVALID_PURPOSE:
         error = QSslError(QSslError::InvalidPurpose, cert); break;
     case X509_V_ERR_CERT_UNTRUSTED:
         error = QSslError(QSslError::CertificateUntrusted, cert); break;
     case X509_V_ERR_CERT_REJECTED:
         error = QSslError(QSslError::CertificateRejected, cert); break;
     default:
         error = QSslError(QSslError::UnspecifiedError, cert); break;
     }
     return error;
 }
id_function()
static unsigned long id_function () static
Definition at line 167 of file qsslsocket_openssl.cpp.
Referenced by QSslSocketPrivate::ensureLibraryLoaded().
 {
     return (quintptr)QThread::currentThreadId();
 }
locking_function()
static void locking_function (int mode, int lockNumber, const char * , int) static
Definition at line 157 of file qsslsocket_openssl.cpp.
Referenced by QSslSocketPrivate::ensureLibraryLoaded().
 {
     QMutex *mutex = openssl_locks()->lock(lockNumber);
     // Lock or unlock it
     if (mode & CRYPTO_LOCK)
         mutex->lock();
     else
         mutex->unlock();
 }
q_X509Callback()
static int q_X509Callback (int ok, X509_STORE_CTX * ctx) static
Definition at line 236 of file qsslsocket_openssl.cpp.
Referenced by QSslSocketBackendPrivate::initSslContext().
 {
     if (!ok) {
         // Store the error and at which depth the error was detected.
         _q_sslErrorList()->errors << qMakePair<int, int>(q_X509_STORE_CTX_get_error(ctx), q_X509_STORE_CTX_get_error_depth(ctx));
     }
     // Always return OK to allow verification to continue. We're handle the
     // errors gracefully after collecting all errors, after verification has
     // completed.
     return 1;
 }