Qt 4.8: /src/network/ssl/qsslcertificate.cpp File Reference
qsslcertificate.cpp File Reference
#include "qsslsocket_openssl_symbols_p.h"
#include "qsslcertificate.h"
#include "qsslcertificate_p.h"
#include "qsslkey.h"
#include "qsslkey_p.h"
#include <QtCore/qatomic.h>
#include <QtCore/qdatetime.h>
#include <QtCore/qdebug.h>
#include <QtCore/qdir.h>
#include <QtCore/qdiriterator.h>
#include <QtCore/qfile.h>
#include <QtCore/qfileinfo.h>
#include <QtCore/qmap.h>
#include <QtCore/qmutex.h>
#include <QtCore/private/qmutexpool_p.h>
#include <QtCore/qstring.h>
#include <QtCore/qstringlist.h>
Macros
#define BEGINCERTSTRING "-----BEGIN CERTIFICATE-----"
#define ENDCERTSTRING "-----END CERTIFICATE-----"
Functions
static QMap< QString, QString > _q_mapFromX509Name (X509_NAME *name)
static QString _q_SubjectInfoToString (QSslCertificate::SubjectInfo info)
static bool matchLineFeed (const QByteArray &pem, int *offset)
QDebug operator<< (QDebug debug, const QSslCertificate &certificate)
QDebug operator<< (QDebug debug, QSslCertificate::SubjectInfo info)
Variables
static const char * certificate_blacklist []
Macro Definition Documentation
BEGINCERTSTRING
#define BEGINCERTSTRING "-----BEGIN CERTIFICATE-----"
Definition at line 653 of file qsslcertificate.cpp.
Referenced by QSslCertificatePrivate::certificatesFromPem(), and QSslCertificatePrivate::QByteArray_from_X509().
ENDCERTSTRING
#define ENDCERTSTRING "-----END CERTIFICATE-----"
Definition at line 654 of file qsslcertificate.cpp.
Referenced by QSslCertificatePrivate::certificatesFromPem(), and QSslCertificatePrivate::QByteArray_from_X509().
Function Documentation
_q_mapFromX509Name()
static QMap< QString, QString > _q_mapFromX509Name (X509_NAME * name) static
Definition at line 692 of file qsslcertificate.cpp.
Referenced by QSslCertificate::issuerInfo(), and QSslCertificate::subjectInfo().
 {
     QMap<QString, QString> info;
     for (int i = 0; i < q_X509_NAME_entry_count(name); ++i) {
         X509_NAME_ENTRY *e = q_X509_NAME_get_entry(name, i);
         const char *obj = q_OBJ_nid2sn(q_OBJ_obj2nid(q_X509_NAME_ENTRY_get_object(e)));
         unsigned char *data = 0;
         int size = q_ASN1_STRING_to_UTF8(&data, q_X509_NAME_ENTRY_get_data(e));
         info[QString::fromUtf8(obj)] = QString::fromUtf8((char*)data, size);
         q_CRYPTO_free(data);
     }
     return info;
 }
_q_SubjectInfoToString()
static QString _q_SubjectInfoToString (QSslCertificate::SubjectInfo info) static
Definition at line 312 of file qsslcertificate.cpp.
Referenced by QSslCertificate::issuerInfo(), and QSslCertificate::subjectInfo().
 {
     QString str;
     switch (info) {
     case QSslCertificate::Organization: str = QLatin1String("O"); break;
     case QSslCertificate::CommonName: str = QLatin1String("CN"); break;
     case QSslCertificate::LocalityName: str = QLatin1String("L"); break;
     case QSslCertificate::OrganizationalUnitName: str = QLatin1String("OU"); break;
     case QSslCertificate::CountryName: str = QLatin1String("C"); break;
     case QSslCertificate::StateOrProvinceName: str = QLatin1String("ST"); break;
     }
     return str;
 }
matchLineFeed()
static bool matchLineFeed (const QByteArray & pem, int * offset) static
Definition at line 722 of file qsslcertificate.cpp.
Referenced by QSslCertificatePrivate::certificatesFromPem().
 {
     char ch = 0;
     // ignore extra whitespace at the end of the line
     while (*offset < pem.size() && (ch = pem.at(*offset)) == ' ')
         ++*offset;
     if (ch == '\n') {
         *offset += 1;
         return true;
     }
     if (ch == '\r' && pem.size() > (*offset + 1) && pem.at(*offset + 1) == '\n') {
         *offset += 2;
         return true;
     }
     return false;
 }
operator<<() [1/2]
QDebug operator<< (QDebug debug, const QSslCertificate & certificate)
Definition at line 866 of file qsslcertificate.cpp.
 {
     debug << "QSslCertificate("
           << certificate.version()
           << ',' << certificate.serialNumber()
           << ',' << certificate.digest().toBase64()
           << ',' << certificate.issuerInfo(QSslCertificate::Organization)
           << ',' << certificate.subjectInfo(QSslCertificate::Organization)
           << ',' << certificate.alternateSubjectNames()
 #ifndef QT_NO_TEXTSTREAM
           << ',' << certificate.effectiveDate()
           << ',' << certificate.expiryDate()
 #endif
           << ')';
     return debug;
 }
operator<<() [2/2]
QDebug operator<< (QDebug debug, QSslCertificate::SubjectInfo info)
Definition at line 882 of file qsslcertificate.cpp.
 {
     switch (info) {
     case QSslCertificate::Organization: debug << "Organization"; break;
     case QSslCertificate::CommonName: debug << "CommonName"; break;
     case QSslCertificate::CountryName: debug << "CountryName"; break;
     case QSslCertificate::LocalityName: debug << "LocalityName"; break;
     case QSslCertificate::OrganizationalUnitName: debug << "OrganizationalUnitName"; break;
     case QSslCertificate::StateOrProvinceName: debug << "StateOrProvinceName"; break;
     }
     return debug;
 }
Variable Documentation
certificate_blacklist
const char* certificate_blacklist[] static
Definition at line 808 of file qsslcertificate.cpp.
Referenced by QSslCertificatePrivate::isBlacklisted().