Qt 4.8: /src/corelib/statemachine/qstatemachine.cpp File Reference
qstatemachine.cpp File Reference
#include "qstatemachine.h"
#include "qstate.h"
#include "qstate_p.h"
#include "qstatemachine_p.h"
#include "qabstracttransition.h"
#include "qabstracttransition_p.h"
#include "qsignaltransition.h"
#include "qsignaltransition_p.h"
#include "qsignaleventgenerator_p.h"
#include "qabstractstate.h"
#include "qabstractstate_p.h"
#include "qfinalstate.h"
#include "qhistorystate.h"
#include "qhistorystate_p.h"
#include "private/qobject_p.h"
#include "private/qthread_p.h"
#include "qeventtransition.h"
#include "qeventtransition_p.h"
#include "qpropertyanimation.h"
#include "qanimationgroup.h"
#include <private/qvariantanimation_p.h>
#include <QtCore/qmetaobject.h>
#include <qdebug.h>
#include "moc_qstatemachine.cpp"
Classes
class _QStateMachine_Internal::GoToStateTransition
Namespaces
_QStateMachine_Internal
Functions
static QEvent * cloneEvent (QEvent *e)
static int indexOfDescendant (QState *s, QAbstractState *desc)
Q_CORE_EXPORT const QStateMachinePrivate::Handler * qcoreStateMachineHandler ()
Variables
const QStateMachinePrivate::Handler qt_kernel_statemachine_handler
static const uint qt_meta_data_QSignalEventGenerator []
static const char qt_meta_stringdata_QSignalEventGenerator []
Function Documentation
cloneEvent()
static QEvent* cloneEvent (QEvent * e) static
Definition at line 226 of file qstatemachine.cpp.
 {
     switch (e->type()) {
     case QEvent::None:
         return new QEvent(*e);
     case QEvent::Timer:
         return new QTimerEvent(*static_cast<QTimerEvent*>(e));
     default:
         Q_ASSERT_X(false, "cloneEvent()", "not implemented");
         break;
     }
     return 0;
 }
indexOfDescendant()
static int indexOfDescendant (QState * s, QAbstractState * desc) static
Definition at line 251 of file qstatemachine.cpp.
Referenced by QStateMachinePrivate::stateEntryLessThan(), and QStateMachinePrivate::stateExitLessThan().
 {
     QList<QAbstractState*> childStates = QStatePrivate::get(s)->childStates();
     for (int i = 0; i < childStates.size(); ++i) {
         QAbstractState *c = childStates.at(i);
         if ((c == desc) || QStateMachinePrivate::isDescendantOf(desc, c)) {
             return i;
         }
     }
     return -1;
 }
qcoreStateMachineHandler()
Q_CORE_EXPORT const QStateMachinePrivate::Handler* qcoreStateMachineHandler ()
Definition at line 246 of file qstatemachine.cpp.
Referenced by cloneEvent().
 {
     return &qt_kernel_statemachine_handler;
 }
Variable Documentation
qt_kernel_statemachine_handler
const QStateMachinePrivate::Handler qt_kernel_statemachine_handler
Initial value:
= {
    cloneEvent
}
Definition at line 240 of file qstatemachine.cpp.
Referenced by qcoreStateMachineHandler().
qt_meta_data_QSignalEventGenerator
const uint qt_meta_data_QSignalEventGenerator[] static
Initial value:
= {
       2,
       0,
       0,    0,
       1,   12,
       0,    0,
       0,    0,
       0,    0,
      23,   22,   22,   22, 0x0a,
       0
}
Definition at line 2271 of file qstatemachine.cpp.
qt_meta_stringdata_QSignalEventGenerator
const char qt_meta_stringdata_QSignalEventGenerator[] static
Initial value:
= {
    "QSignalEventGenerator\0\0execute()\0"
}
Definition at line 2288 of file qstatemachine.cpp.
Referenced by QSignalEventGenerator::qt_metacast().