Qt 4.8: /src/gui/painting/qstroker.cpp File Reference
qstroker.cpp File Reference
#include "private/qstroker_p.h"
#include "private/qbezier_p.h"
#include "private/qmath_p.h"
#include "qline.h"
#include "qtransform.h"
#include <qmath.h>
Classes
class QSubpathBackwardIterator
class QSubpathFlatIterator
class QSubpathForwardIterator
Functions
static qreal adapted_angle_on_x (const QLineF &line)
static bool lineIntersectsRect (qfixed2d p1, qfixed2d p2, const qfixed2d &tl, const qfixed2d &br)
static bool lineRectIntersectsRect (qfixed2d p1, qfixed2d p2, const qfixed2d &tl, const qfixed2d &br)
static void qdashstroker_cubicTo (qfixed, qfixed, qfixed, qfixed, qfixed, qfixed, void *)
static void qdashstroker_lineTo (qfixed x, qfixed y, void *data)
static void qdashstroker_moveTo (qfixed x, qfixed y, void *data)
QPointF qt_curves_for_arc (const QRectF &rect, qreal startAngle, qreal sweepLength, QPointF *curves, int *point_count)
Creates a number of curves for a given arc definition.
Q_GUI_EXPORT void qt_find_ellipse_coords (const QRectF &r, qreal angle, qreal length, QPointF *startPoint, QPointF *endPoint)
template<class Iterator >
bool qt_stroke_side (Iterator *it, QStroker *stroker, bool capFirst, QLineF *startTangent)
qreal qt_t_for_arc_angle (qreal angle)
Function Documentation
adapted_angle_on_x()
static qreal adapted_angle_on_x (const QLineF & line) inline static
Definition at line 182 of file qstroker.cpp.
Referenced by QStroker::joinPoints().
 {
     qreal angle = line.angle(QLineF(0, 0, 1, 0));
     if (line.dy() > 0)
         angle = 360 - angle;
     return angle;
 }
lineIntersectsRect()
static bool lineIntersectsRect (qfixed2d p1, qfixed2d p2, const qfixed2d & tl, const qfixed2d & br) static
Definition at line 1069 of file qstroker.cpp.
Referenced by QDashStroker::processCurrentSubpath().
 {
     if (!lineRectIntersectsRect(p1, p2, tl, br))
         return false;
     if (p1.x == p2.x || p1.y == p2.y)
         return true;
     if (p1.y > p2.y)
         qSwap(p1, p2); // make p1 above p2
     qfixed2d u;
     qfixed2d v;
     qfixed2d w = {p2.x - p1.x, p2.y - p1.y};
     if (p1.x < p2.x) {
         // backslash
         u.x = tl.x - p1.x; u.y = br.y - p1.y;
         v.x = br.x - p1.x; v.y = tl.y - p1.y;
     } else {
         // slash
         u.x = tl.x - p1.x; u.y = tl.y - p1.y;
         v.x = br.x - p1.x; v.y = br.y - p1.y;
     }
 #if defined(QFIXED_IS_26_6) || defined(QFIXED_IS_16_16)
     qint64 val1 = qint64(u.x) * qint64(w.y) - qint64(u.y) * qint64(w.x);
     qint64 val2 = qint64(v.x) * qint64(w.y) - qint64(v.y) * qint64(w.x);
     return (val1 < 0 && val2 > 0) || (val1 > 0 && val2 < 0);
 #elif defined(QFIXED_IS_32_32)
     // Cannot do proper test because it may overflow.
     return true;
 #else
     qreal val1 = u.x * w.y - u.y * w.x;
     qreal val2 = v.x * w.y - v.y * w.x;
     return (val1 < 0 && val2 > 0) || (val1 > 0 && val2 < 0);
 #endif
 }
lineRectIntersectsRect()
static bool lineRectIntersectsRect (qfixed2d p1, qfixed2d p2, const qfixed2d & tl, const qfixed2d & br) inline static
Definition at line 1062 of file qstroker.cpp.
Referenced by lineIntersectsRect(), and QDashStroker::processCurrentSubpath().
 {
     return ((p1.x > tl.x || p2.x > tl.x) && (p1.x < br.x || p2.x < br.x)
         && (p1.y > tl.y || p2.y > tl.y) && (p1.y < br.y || p2.y < br.y));
 }
qdashstroker_cubicTo()
static void qdashstroker_cubicTo (qfixed , qfixed , qfixed , qfixed , qfixed , qfixed , void *) inline static
Definition at line 1015 of file qstroker.cpp.
Referenced by QDashStroker::QDashStroker().
{
     Q_ASSERT(0);
 //     ((QStroker *) data)->cubicTo(c1x, c1y, c2x, c2y, ex, ey);
 }
qdashstroker_lineTo()
static void qdashstroker_lineTo (qfixed x, qfixed y, void * data) inline static
Definition at line 1011 of file qstroker.cpp.
Referenced by QDashStroker::QDashStroker().
{
     ((QStroker *) data)->lineTo(x, y);
 }
qdashstroker_moveTo()
static void qdashstroker_moveTo (qfixed x, qfixed y, void * data) inline static
Definition at line 1007 of file qstroker.cpp.
Referenced by QDashStroker::QDashStroker().
{
     ((QStroker *) data)->moveTo(x, y);
 }
qt_curves_for_arc()
QPointF qt_curves_for_arc (const QRectF & rect, qreal startAngle, qreal sweepLength, QPointF * curves, int * point_count)
Creates a number of curves for a given arc definition.
Warning
This function is not part of the public interface.
The arc is defined an arc along the ellipses that fits into rect starting at startAngle and an arc length of sweepLength.
The function has three out parameters. The return value is the starting point of the arc. The curves array represents the list of cubicTo elements up to a maximum of point_count. There are of course 3 points pr curve.
Definition at line 859 of file qstroker.cpp.
Referenced by QPainterPath::addEllipse(), QPainterPath::arcTo(), QPaintEngineEx::drawEllipse(), QStroker::joinPoints(), and QStrokerOps::strokeEllipse().
 {
     Q_ASSERT(point_count);
     Q_ASSERT(curves);
     *point_count = 0;
     if (qt_is_nan(rect.x()) || qt_is_nan(rect.y()) || qt_is_nan(rect.width()) || qt_is_nan(rect.height())
         || qt_is_nan(startAngle) || qt_is_nan(sweepLength)) {
         qWarning("QPainterPath::arcTo: Adding arc where a parameter is NaN, results are undefined");
         return QPointF();
     }
     if (rect.isNull()) {
         return QPointF();
     }
     qreal x = rect.x();
     qreal y = rect.y();
     qreal w = rect.width();
     qreal w2 = rect.width() / 2;
     qreal w2k = w2 * QT_PATH_KAPPA;
     qreal h = rect.height();
     qreal h2 = rect.height() / 2;
     qreal h2k = h2 * QT_PATH_KAPPA;
     QPointF points[16] =
     {
         // start point
         QPointF(x + w, y + h2),
         // 0 -> 270 degrees
         QPointF(x + w, y + h2 + h2k),
         QPointF(x + w2 + w2k, y + h),
         QPointF(x + w2, y + h),
         // 270 -> 180 degrees
         QPointF(x + w2 - w2k, y + h),
         QPointF(x, y + h2 + h2k),
         QPointF(x, y + h2),
         // 180 -> 90 degrees
         QPointF(x, y + h2 - h2k),
         QPointF(x + w2 - w2k, y),
         QPointF(x + w2, y),
         // 90 -> 0 degrees
         QPointF(x + w2 + w2k, y),
         QPointF(x + w, y + h2 - h2k),
         QPointF(x + w, y + h2)
     };
     if (sweepLength > 360) sweepLength = 360;
     else if (sweepLength < -360) sweepLength = -360;
     // Special case fast paths
     if (startAngle == 0.0) {
         if (sweepLength == 360.0) {
             for (int i = 11; i >= 0; --i)
                 curves[(*point_count)++] = points[i];
             return points[12];
         } else if (sweepLength == -360.0) {
             for (int i = 1; i <= 12; ++i)
                 curves[(*point_count)++] = points[i];
             return points[0];
         }
     }
     int startSegment = int(qFloor(startAngle / 90));
     int endSegment = int(qFloor((startAngle + sweepLength) / 90));
     qreal startT = (startAngle - startSegment * 90) / 90;
     qreal endT = (startAngle + sweepLength - endSegment * 90) / 90;
     int delta = sweepLength > 0 ? 1 : -1;
     if (delta < 0) {
         startT = 1 - startT;
         endT = 1 - endT;
     }
     // avoid empty start segment
     if (qFuzzyIsNull(startT - qreal(1))) {
         startT = 0;
         startSegment += delta;
     }
     // avoid empty end segment
     if (qFuzzyIsNull(endT)) {
         endT = 1;
         endSegment -= delta;
     }
     startT = qt_t_for_arc_angle(startT * 90);
     endT = qt_t_for_arc_angle(endT * 90);
     const bool splitAtStart = !qFuzzyIsNull(startT);
     const bool splitAtEnd = !qFuzzyIsNull(endT - qreal(1));
     const int end = endSegment + delta;
     // empty arc?
     if (startSegment == end) {
         const int quadrant = 3 - ((startSegment % 4) + 4) % 4;
         const int j = 3 * quadrant;
         return delta > 0 ? points[j + 3] : points[j];
     }
     QPointF startPoint, endPoint;
     qt_find_ellipse_coords(rect, startAngle, sweepLength, &startPoint, &endPoint);
     for (int i = startSegment; i != end; i += delta) {
         const int quadrant = 3 - ((i % 4) + 4) % 4;
         const int j = 3 * quadrant;
         QBezier b;
         if (delta > 0)
             b = QBezier::fromPoints(points[j + 3], points[j + 2], points[j + 1], points[j]);
         else
             b = QBezier::fromPoints(points[j], points[j + 1], points[j + 2], points[j + 3]);
         // empty arc?
         if (startSegment == endSegment && qFuzzyCompare(startT, endT))
             return startPoint;
         if (i == startSegment) {
             if (i == endSegment && splitAtEnd)
                 b = b.bezierOnInterval(startT, endT);
             else if (splitAtStart)
                 b = b.bezierOnInterval(startT, 1);
         } else if (i == endSegment && splitAtEnd) {
             b = b.bezierOnInterval(0, endT);
         }
         // push control points
         curves[(*point_count)++] = b.pt2();
         curves[(*point_count)++] = b.pt3();
         curves[(*point_count)++] = b.pt4();
     }
     Q_ASSERT(*point_count > 0);
     curves[*(point_count)-1] = endPoint;
     return startPoint;
 }
qt_find_ellipse_coords()
Q_GUI_EXPORT void qt_find_ellipse_coords (const QRectF & r, qreal angle, qreal length, QPointF * startPoint, QPointF * endPoint)
Definition at line 97 of file qpainterpath.cpp.
Referenced by QPainterPath::arcMoveTo(), qt_curves_for_arc(), and qt_t_for_arc_angle().
 {
     if (r.isNull()) {
         if (startPoint)
             *startPoint = QPointF();
         if (endPoint)
             *endPoint = QPointF();
         return;
     }
     qreal w2 = r.width() / 2;
     qreal h2 = r.height() / 2;
     qreal angles[2] = { angle, angle + length };
     QPointF *points[2] = { startPoint, endPoint };
     for (int i = 0; i < 2; ++i) {
         if (!points[i])
             continue;
         qreal theta = angles[i] - 360 * qFloor(angles[i] / 360);
         qreal t = theta / 90;
         // truncate
         int quadrant = int(t);
         t -= quadrant;
         t = qt_t_for_arc_angle(90 * t);
         // swap x and y?
         if (quadrant & 1)
             t = 1 - t;
         qreal a, b, c, d;
         QBezier::coefficients(t, a, b, c, d);
         QPointF p(a + b + c*QT_PATH_KAPPA, d + c + b*QT_PATH_KAPPA);
         // left quadrants
         if (quadrant == 1 || quadrant == 2)
             p.rx() = -p.x();
         // top quadrants
         if (quadrant == 0 || quadrant == 1)
             p.ry() = -p.y();
         *points[i] = r.center() + QPointF(w2 * p.x(), h2 * p.y());
     }
 }
qt_stroke_side()
template<class Iterator > bool qt_stroke_side (Iterator * it, QStroker * stroker, bool capFirst, QLineF * startTangent)
Definition at line 635 of file qstroker.cpp.
Referenced by QStroker::processCurrentSubpath().
 {
     // Used in CurveToElement section below.
     const int MAX_OFFSET = 16;
     QBezier offsetCurves[MAX_OFFSET];
     Q_ASSERT(it->hasNext()); // The initaial move to
     QStrokerOps::Element first_element = it->next();
     Q_ASSERT(first_element.isMoveTo());
     qfixed2d start = first_element;
 #ifdef QPP_STROKE_DEBUG
     qDebug(" -> (side) [%.2f, %.2f], startPos=%d",
            qt_fixed_to_real(start.x),
            qt_fixed_to_real(start.y));
 #endif
     qfixed2d prev = start;
     bool first = true;
     qfixed offset = stroker->strokeWidth() / 2;
     while (it->hasNext()) {
         QStrokerOps::Element e = it->next();
         // LineToElement
         if (e.isLineTo()) {
 #ifdef QPP_STROKE_DEBUG
             qDebug("\n ---> (side) lineto [%.2f, %.2f]", e.x, e.y);
 #endif
             QLineF line(qt_fixed_to_real(prev.x), qt_fixed_to_real(prev.y),
                         qt_fixed_to_real(e.x), qt_fixed_to_real(e.y));
             if (line.p1() != line.p2()) {
                 QLineF normal = line.normalVector();
                 normal.setLength(offset);
                 line.translate(normal.dx(), normal.dy());
                 // If we are starting a new subpath, move to correct starting point.
                 if (first) {
                     if (capFirst)
                         stroker->joinPoints(prev.x, prev.y, line, stroker->capStyleMode());
                     else
                         stroker->emitMoveTo(qt_real_to_fixed(line.x1()), qt_real_to_fixed(line.y1()));
                     *startTangent = line;
                     first = false;
                 } else {
                     stroker->joinPoints(prev.x, prev.y, line, stroker->joinStyleMode());
                 }
                 // Add the stroke for this line.
                 stroker->emitLineTo(qt_real_to_fixed(line.x2()),
                                     qt_real_to_fixed(line.y2()));
                 prev = e;
             }
         // CurveToElement
         } else if (e.isCurveTo()) {
             QStrokerOps::Element cp2 = it->next(); // control point 2
             QStrokerOps::Element ep = it->next();  // end point
 #ifdef QPP_STROKE_DEBUG
             qDebug("\n ---> (side) cubicTo [%.2f, %.2f]",
                    qt_fixed_to_real(ep.x),
                    qt_fixed_to_real(ep.y));
 #endif
             QBezier bezier =
                 QBezier::fromPoints(QPointF(qt_fixed_to_real(prev.x), qt_fixed_to_real(prev.y)),
                                     QPointF(qt_fixed_to_real(e.x), qt_fixed_to_real(e.y)),
                                     QPointF(qt_fixed_to_real(cp2.x), qt_fixed_to_real(cp2.y)),
                                     QPointF(qt_fixed_to_real(ep.x), qt_fixed_to_real(ep.y)));
             int count = bezier.shifted(offsetCurves,
                                        MAX_OFFSET,
                                        offset,
                                        stroker->curveThreshold());
             if (count) {
                 // If we are starting a new subpath, move to correct starting point
                 QLineF tangent = bezier.startTangent();
                 tangent.translate(offsetCurves[0].pt1() - bezier.pt1());
                 if (first) {
                     QPointF pt = offsetCurves[0].pt1();
                     if (capFirst) {
                         stroker->joinPoints(prev.x, prev.y,
                                             tangent,
                                             stroker->capStyleMode());
                     } else {
                         stroker->emitMoveTo(qt_real_to_fixed(pt.x()),
                                             qt_real_to_fixed(pt.y()));
                     }
                     *startTangent = tangent;
                     first = false;
                 } else {
                     stroker->joinPoints(prev.x, prev.y,
                                         tangent,
                                         stroker->joinStyleMode());
                 }
                 // Add these beziers
                 for (int i=0; i<count; ++i) {
                     QPointF cp1 = offsetCurves[i].pt2();
                     QPointF cp2 = offsetCurves[i].pt3();
                     QPointF ep = offsetCurves[i].pt4();
                     stroker->emitCubicTo(qt_real_to_fixed(cp1.x()), qt_real_to_fixed(cp1.y()),
                                          qt_real_to_fixed(cp2.x()), qt_real_to_fixed(cp2.y()),
                                          qt_real_to_fixed(ep.x()), qt_real_to_fixed(ep.y()));
                 }
             }
             prev = ep;
         }
     }
     if (start == prev) {
         // closed subpath, join first and last point
 #ifdef QPP_STROKE_DEBUG
         qDebug("\n ---> (side) closed subpath");
 #endif
         // don't join empty subpaths
         if (!first)
             stroker->joinPoints(prev.x, prev.y, *startTangent, stroker->joinStyleMode());
         return true;
     } else {
 #ifdef QPP_STROKE_DEBUG
         qDebug("\n ---> (side) open subpath");
 #endif
         return false;
     }
 }
qt_t_for_arc_angle()
qreal qt_t_for_arc_angle (qreal angle)
Warning
This function is not part of the public interface.
For a given angle in the range [0 .. 90], finds the corresponding parameter t of the prototype cubic bezier arc segment b = fromPoints(QPointF(1, 0), QPointF(1, KAPPA), QPointF(KAPPA, 1), QPointF(0, 1));
From the bezier equation: b.pointAt(t).x() = (1-t)^3 + t*(1-t)^2 + t^2*(1-t)*KAPPA b.pointAt(t).y() = t*(1-t)^2 * KAPPA + t^2*(1-t) + t^3
Third degree coefficients: b.pointAt(t).x() = at^3 + bt^2 + ct + d where a = 2-3*KAPPA, b = 3*(KAPPA-1), c = 0, d = 1
b.pointAt(t).y() = at^3 + bt^2 + ct + d where a = 3*KAPPA-2, b = 6*KAPPA+3, c = 3*KAPPA, d = 0
Newton's method to find the zero of a function: given a function f(x) and initial guess x_0 x_1 = f(x_0) / f'(x_0) x_2 = f(x_1) / f'(x_1) etc...
Definition at line 796 of file qstroker.cpp.
Referenced by qt_curves_for_arc(), and qt_find_ellipse_coords().
 {
     if (qFuzzyIsNull(angle))
         return 0;
     if (qFuzzyCompare(angle, qreal(90)))
         return 1;
     qreal radians = Q_PI * angle / 180;
     qreal cosAngle = qCos(radians);
     qreal sinAngle = qSin(radians);
     // initial guess
     qreal tc = angle / 90;
     // do some iterations of newton's method to approximate cosAngle
     // finds the zero of the function b.pointAt(tc).x() - cosAngle
     tc -= ((((2-3*QT_PATH_KAPPA) * tc + 3*(QT_PATH_KAPPA-1)) * tc) * tc + 1 - cosAngle) // value
          / (((6-9*QT_PATH_KAPPA) * tc + 6*(QT_PATH_KAPPA-1)) * tc); // derivative
     tc -= ((((2-3*QT_PATH_KAPPA) * tc + 3*(QT_PATH_KAPPA-1)) * tc) * tc + 1 - cosAngle) // value
          / (((6-9*QT_PATH_KAPPA) * tc + 6*(QT_PATH_KAPPA-1)) * tc); // derivative
     // initial guess
     qreal ts = tc;
     // do some iterations of newton's method to approximate sinAngle
     // finds the zero of the function b.pointAt(tc).y() - sinAngle
     ts -= ((((3*QT_PATH_KAPPA-2) * ts -  6*QT_PATH_KAPPA + 3) * ts + 3*QT_PATH_KAPPA) * ts - sinAngle)
          / (((9*QT_PATH_KAPPA-6) * ts + 12*QT_PATH_KAPPA - 6) * ts + 3*QT_PATH_KAPPA);
     ts -= ((((3*QT_PATH_KAPPA-2) * ts -  6*QT_PATH_KAPPA + 3) * ts + 3*QT_PATH_KAPPA) * ts - sinAngle)
          / (((9*QT_PATH_KAPPA-6) * ts + 12*QT_PATH_KAPPA - 6) * ts + 3*QT_PATH_KAPPA);
     // use the average of the t that best approximates cosAngle
     // and the t that best approximates sinAngle
     qreal t = 0.5 * (tc + ts);
 #if 0
     printf("angle: %f, t: %f\n", angle, t);
     qreal a, b, c, d;
     bezierCoefficients(t, a, b, c, d);
     printf("cosAngle: %.10f, value: %.10f\n", cosAngle, a + b + c * QT_PATH_KAPPA);
     printf("sinAngle: %.10f, value: %.10f\n", sinAngle, b * QT_PATH_KAPPA + c + d);
 #endif
     return t;
 }