Qt 4.8: /src/corelib/tools/qstring.h File Reference
qstring.h File Reference
#include <QtCore/qchar.h>
#include <QtCore/qbytearray.h>
#include <QtCore/qatomic.h>
#include <QtCore/qnamespace.h>
#include <string>
#include <stdarg.h>
Classes
class QCharRef
The QCharRef class is a helper class for QString.
class QLatin1String
The QLatin1String class provides a thin wrapper around an US-ASCII/Latin-1 encoded string literal.
class QString
The QString class provides a Unicode character string.
struct QString::Data
struct QString::Null
class QStringRef
The QStringRef class provides a thin wrapper around QString substrings.
class QVector< T >
The QVector class is a template class that provides a dynamic array.
Typedefs
typedef std::basic_string< wchar_t > QStdWString
Functions
bool operator!= (QString::Null, QString::Null)
bool operator!= (QString::Null, const QString &s)
bool operator!= (const QString &s, QString::Null)
QT_ASCII_CAST_WARN bool operator!= (const char *s1, const QString &s2)
QT_ASCII_CAST_WARN bool operator!= (const char *s1, const QLatin1String &s2)
bool operator!= (const QLatin1String &s1, const QLatin1String &s2)
bool operator!= (const QStringRef &s1, const QStringRef &s2)
bool operator!= (const QString &s1, const QStringRef &s2)
bool operator!= (const QStringRef &s1, const QString &s2)
bool operator!= (const QLatin1String &s1, const QStringRef &s2)
bool operator!= (const QStringRef &s1, const QLatin1String &s2)
QT_ASCII_CAST_WARN bool operator!= (const char *s1, const QStringRef &s2)
QT_ASCII_CAST_WARN bool operator!= (const QStringRef &s1, const char *s2)
const QString operator+ (const QString &s1, const QString &s2)
const QString operator+ (const QString &s1, QChar s2)
const QString operator+ (QChar s1, const QString &s2)
QT_ASCII_CAST_WARN const QString operator+ (const QString &s1, const char *s2)
QT_ASCII_CAST_WARN const QString operator+ (const char *s1, const QString &s2)
QT_ASCII_CAST_WARN const QString operator+ (char c, const QString &s)
QT_ASCII_CAST_WARN const QString operator+ (const QString &s, char c)
QT_ASCII_CAST_WARN const QString operator+ (const QByteArray &ba, const QString &s)
QT_ASCII_CAST_WARN const QString operator+ (const QString &s, const QByteArray &ba)
QT_ASCII_CAST_WARN bool operator< (const char *s1, const QString &s2)
QT_ASCII_CAST_WARN bool operator< (const char *s1, const QLatin1String &s2)
bool operator< (const QLatin1String &s1, const QLatin1String &s2)
Q_CORE_EXPORT bool operator< (const QStringRef &s1, const QStringRef &s2)
Q_CORE_EXPORT QDataStream & operator<< (QDataStream &, const QString &)
QT_ASCII_CAST_WARN bool operator<= (const char *s1, const QString &s2)
QT_ASCII_CAST_WARN bool operator<= (const char *s1, const QLatin1String &s2)
bool operator<= (const QLatin1String &s1, const QLatin1String &s2)
bool operator<= (const QStringRef &s1, const QStringRef &s2)
bool operator== (QString::Null, QString::Null)
bool operator== (QString::Null, const QString &s)
bool operator== (const QString &s, QString::Null)
QT_ASCII_CAST_WARN bool operator== (const char *s1, const QString &s2)
QT_ASCII_CAST_WARN bool operator== (const char *s1, const QLatin1String &s2)
bool operator== (const QLatin1String &s1, const QLatin1String &s2)
Q_CORE_EXPORT bool operator== (const QStringRef &s1, const QStringRef &s2)
Q_CORE_EXPORT bool operator== (const QString &s1, const QStringRef &s2)
bool operator== (const QStringRef &s1, const QString &s2)
Q_CORE_EXPORT bool operator== (const QLatin1String &s1, const QStringRef &s2)
bool operator== (const QStringRef &s1, const QLatin1String &s2)
QT_ASCII_CAST_WARN bool operator== (const char *s1, const QStringRef &s2)
QT_ASCII_CAST_WARN bool operator== (const QStringRef &s1, const char *s2)
QT_ASCII_CAST_WARN bool operator> (const char *s1, const QString &s2)
QT_ASCII_CAST_WARN bool operator> (const char *s1, const QLatin1String &s2)
bool operator> (const QLatin1String &s1, const QLatin1String &s2)
bool operator> (const QStringRef &s1, const QStringRef &s2)
QT_ASCII_CAST_WARN bool operator>= (const char *s1, const QString &s2)
QT_ASCII_CAST_WARN bool operator>= (const char *s1, const QLatin1String &s2)
bool operator>= (const QLatin1String &s1, const QLatin1String &s2)
bool operator>= (const QStringRef &s1, const QStringRef &s2)
Q_CORE_EXPORT QDataStream & operator>> (QDataStream &, QString &)
Q_DECLARE_TYPEINFO (QString, Q_MOVABLE_TYPE)
bool qStringComparisonHelper (const QString &s1, const char *s2)
bool qStringComparisonHelper (const QStringRef &s1, const char *s2)
Typedef Documentation
QStdWString
typedef std::basic_string<wchar_t> QStdWString
Definition at line 58 of file qstring.h.
Function Documentation
operator!=() [1/13]
bool operator!= (QString::Null , QString::Null) inline
Definition at line 911 of file qstring.h.
Referenced by QString::operator+=().
 { return false; }
operator!=() [2/13]
bool operator!= (QString::Null , const QString & s) inline
Definition at line 912 of file qstring.h.
 { return !s.isNull(); }
operator!=() [3/13]
bool operator!= (const QString & s, QString::Null) inline
Definition at line 913 of file qstring.h.
 { return !s.isNull(); }
operator!=() [4/13]
QT_ASCII_CAST_WARN bool operator!= (const char * s1, const QString & s2) related
Definition at line 938 of file qstring.h.
 { return !qStringComparisonHelper(s2, s1); }
operator!=() [5/13]
QT_ASCII_CAST_WARN bool operator!= (const char * s1, const QLatin1String & s2) inline
Definition at line 951 of file qstring.h.
 { return QString::fromAscii(s1) != s2; }
operator!=() [6/13]
bool operator!= (const QLatin1String & s1, const QLatin1String & s2) inline
Definition at line 964 of file qstring.h.
 { return (qstrcmp(s1.latin1(), s2.latin1()) != 0); }
operator!=() [7/13]
bool operator!= (const QStringRef & s1, const QStringRef & s2) inline
Definition at line 1203 of file qstring.h.
 { return !(s1 == s2); }
operator!=() [8/13]
bool operator!= (const QString & s1, const QStringRef & s2) inline
Definition at line 1206 of file qstring.h.
 { return !(s1 == s2); }
operator!=() [9/13]
bool operator!= (const QStringRef & s1, const QString & s2) inline
Definition at line 1210 of file qstring.h.
 { return s2 != s1; }
operator!=() [10/13]
bool operator!= (const QLatin1String & s1, const QStringRef & s2) inline
Definition at line 1213 of file qstring.h.
 { return !(s1 == s2); }
operator!=() [11/13]
bool operator!= (const QStringRef & s1, const QLatin1String & s2) inline
Definition at line 1217 of file qstring.h.
 { return s2 != s1; }
operator!=() [12/13]
QT_ASCII_CAST_WARN bool operator!= (const char * s1, const QStringRef & s2) inline
Definition at line 1240 of file qstring.h.
 { return !qStringComparisonHelper(s2, s1); }
operator!=() [13/13]
QT_ASCII_CAST_WARN bool operator!= (const QStringRef & s1, const char * s2) inline
Definition at line 1242 of file qstring.h.
 { return !qStringComparisonHelper(s1, s2); }
operator+() [1/9]
const QString operator+ (const QString & s1, const QString & s2) related
Definition at line 1021 of file qstring.h.
 { QString t(s1); t += s2; return t; }
operator+() [2/9]
const QString operator+ (const QString & s1, QChar s2) inline
Definition at line 1023 of file qstring.h.
 { QString t(s1); t += s2; return t; }
operator+() [3/9]
const QString operator+ (QChar s1, const QString & s2) inline
Definition at line 1025 of file qstring.h.
 { QString t(s1); t += s2; return t; }
operator+() [4/9]
QT_ASCII_CAST_WARN const QString operator+ (const QString & s1, const char * s2) related
Definition at line 1028 of file qstring.h.
 { QString t(s1); t += QString::fromAscii(s2); return t; }
operator+() [5/9]
QT_ASCII_CAST_WARN const QString operator+ (const char * s1, const QString & s2) related
Definition at line 1030 of file qstring.h.
 { QString t = QString::fromAscii(s1); t += s2; return t; }
operator+() [6/9]
QT_ASCII_CAST_WARN const QString operator+ (char c, const QString & s) related
Definition at line 1032 of file qstring.h.
 { QString t = s; t.prepend(QChar::fromAscii(c)); return t; }
operator+() [7/9]
QT_ASCII_CAST_WARN const QString operator+ (const QString & s, char c) related
Definition at line 1034 of file qstring.h.
 { QString t = s; t += QChar::fromAscii(c); return t; }
operator+() [8/9]
QT_ASCII_CAST_WARN const QString operator+ (const QByteArray & ba, const QString & s) inline
Definition at line 1036 of file qstring.h.
 { QString t = QString::fromAscii(ba.constData(), qstrnlen(ba.constData(), ba.size())); t += s; return t; }
operator+() [9/9]
QT_ASCII_CAST_WARN const QString operator+ (const QString & s, const QByteArray & ba) inline
Definition at line 1038 of file qstring.h.
 { QString t(s); t += QString::fromAscii(ba.constData(), qstrnlen(ba.constData(), ba.size())); return t; }
operator<() [1/4]
QT_ASCII_CAST_WARN bool operator< (const char * s1, const QString & s2) related
Definition at line 940 of file qstring.h.
Referenced by QString::localeAwareCompare(), QString::operator+=(), and QString::operator>=().
 { return (QString::fromAscii(s1) < s2); }
operator<() [2/4]
QT_ASCII_CAST_WARN bool operator< (const char * s1, const QLatin1String & s2) inline
Definition at line 953 of file qstring.h.
 { return (QString::fromAscii(s1) < s2); }
operator<() [3/4]
bool operator< (const QLatin1String & s1, const QLatin1String & s2) inline
Definition at line 966 of file qstring.h.
 { return (qstrcmp(s1.latin1(), s2.latin1()) < 0); }
operator<() [4/4]
Q_CORE_EXPORT bool operator< (const QStringRef & s1, const QStringRef & s2) related
operator<<()
Q_CORE_EXPORT QDataStream& operator<< (QDataStream & , const QString &) related
Definition at line 8034 of file qstring.cpp.
 {
     if (out.version() == 1) {
         out << str.toLatin1();
     } else {
         if (!str.isNull() || out.version() < 3) {
             if ((out.byteOrder() == QDataStream::BigEndian) == (QSysInfo::ByteOrder == QSysInfo::BigEndian)) {
                 out.writeBytes(reinterpret_cast<const char *>(str.unicode()), sizeof(QChar) * str.length());
             } else {
                 QVarLengthArray<ushort> buffer(str.length());
                 const ushort *data = reinterpret_cast<const ushort *>(str.constData());
                 for (int i = 0; i < str.length(); i++) {
                     buffer[i] = qbswap(*data);
                     ++data;
                 }
                 out.writeBytes(reinterpret_cast<const char *>(buffer.data()), sizeof(ushort) * buffer.size());
             }
         } else {
             // write null marker
             out << (quint32)0xffffffff;
         }
     }
     return out;
 }
operator<=() [1/4]
QT_ASCII_CAST_WARN bool operator<= (const char * s1, const QString & s2) related
Definition at line 944 of file qstring.h.
Referenced by QString::operator+=().
 { return (QString::fromAscii(s1) <= s2); }
operator<=() [2/4]
QT_ASCII_CAST_WARN bool operator<= (const char * s1, const QLatin1String & s2) inline
Definition at line 957 of file qstring.h.
 { return (QString::fromAscii(s1) <= s2); }
operator<=() [3/4]
bool operator<= (const QLatin1String & s1, const QLatin1String & s2) inline
Definition at line 968 of file qstring.h.
 { return (qstrcmp(s1.latin1(), s2.latin1()) <= 0); }
operator<=() [4/4]
bool operator<= (const QStringRef & s1, const QStringRef & s2) related
Definition at line 1223 of file qstring.h.
 { return !(s1 > s2); }
operator==() [1/13]
bool operator== (QString::Null , QString::Null) inline
Definition at line 908 of file qstring.h.
Referenced by QString::localeAwareCompare(), QString::operator!=(), QString::operator+=(), and QString::operator>=().
 { return true; }
operator==() [2/13]
bool operator== (QString::Null , const QString & s) inline
Definition at line 909 of file qstring.h.
 { return s.isNull(); }
operator==() [3/13]
bool operator== (const QString & s, QString::Null) inline
Definition at line 910 of file qstring.h.
 { return s.isNull(); }
operator==() [4/13]
QT_ASCII_CAST_WARN bool operator== (const char * s1, const QString & s2) inline
Definition at line 936 of file qstring.h.
 { return qStringComparisonHelper(s2, s1); }
operator==() [5/13]
QT_ASCII_CAST_WARN bool operator== (const char * s1, const QLatin1String & s2) inline
Definition at line 949 of file qstring.h.
 { return QString::fromAscii(s1) == s2; }
operator==() [6/13]
bool operator== (const QLatin1String & s1, const QLatin1String & s2) inline
Definition at line 962 of file qstring.h.
 { return (qstrcmp(s1.latin1(), s2.latin1()) == 0); }
operator==() [7/13]
Q_CORE_EXPORT bool operator== (const QStringRef & s1, const QStringRef & s2) related
operator==() [8/13]
Q_CORE_EXPORT bool operator== (const QString & s1, const QStringRef & s2) related
operator==() [9/13]
bool operator== (const QStringRef & s1, const QString & s2) inline
Definition at line 1208 of file qstring.h.
 { return s2 == s1; }
operator==() [10/13]
Q_CORE_EXPORT bool operator== (const QLatin1String & s1, const QStringRef & s2) related
operator==() [11/13]
bool operator== (const QStringRef & s1, const QLatin1String & s2) inline
Definition at line 1215 of file qstring.h.
 { return s2 == s1; }
operator==() [12/13]
QT_ASCII_CAST_WARN bool operator== (const char * s1, const QStringRef & s2) inline
Definition at line 1236 of file qstring.h.
 { return qStringComparisonHelper(s2, s1); }
operator==() [13/13]
QT_ASCII_CAST_WARN bool operator== (const QStringRef & s1, const char * s2) inline
Definition at line 1238 of file qstring.h.
 { return qStringComparisonHelper(s1, s2); }
operator>() [1/4]
QT_ASCII_CAST_WARN bool operator> (const char * s1, const QString & s2) related
Definition at line 942 of file qstring.h.
Referenced by QString::operator+=(), QString::operator<=(), and QString::operator>=().
 { return (QString::fromAscii(s1) > s2); }
operator>() [2/4]
QT_ASCII_CAST_WARN bool operator> (const char * s1, const QLatin1String & s2) inline
Definition at line 955 of file qstring.h.
 { return (QString::fromAscii(s1) > s2); }
operator>() [3/4]
bool operator> (const QLatin1String & s1, const QLatin1String & s2) inline
Definition at line 970 of file qstring.h.
 { return (qstrcmp(s1.latin1(), s2.latin1()) > 0); }
operator>() [4/4]
bool operator> (const QStringRef & s1, const QStringRef & s2) related
Definition at line 1221 of file qstring.h.
 { return s2 < s1; }
operator>=() [1/4]
QT_ASCII_CAST_WARN bool operator>= (const char * s1, const QString & s2) related
Definition at line 946 of file qstring.h.
Referenced by QString::operator+=().
 { return (QString::fromAscii(s1) >= s2); }
operator>=() [2/4]
QT_ASCII_CAST_WARN bool operator>= (const char * s1, const QLatin1String & s2) inline
Definition at line 959 of file qstring.h.
 { return (QString::fromAscii(s1) >= s2); }
operator>=() [3/4]
bool operator>= (const QLatin1String & s1, const QLatin1String & s2) inline
Definition at line 972 of file qstring.h.
 { return (qstrcmp(s1.latin1(), s2.latin1()) >= 0); }
operator>=() [4/4]
bool operator>= (const QStringRef & s1, const QStringRef & s2) related
Definition at line 1225 of file qstring.h.
 { return !(s1 < s2); }
operator>>()
Q_CORE_EXPORT QDataStream& operator>> (QDataStream & , QString &) related
Definition at line 8071 of file qstring.cpp.
 {
 #ifdef QT_QSTRING_UCS_4
 #if defined(Q_CC_GNU)
 #warning "operator>> not working properly"
 #endif
 #endif
     if (in.version() == 1) {
         QByteArray l;
         in >> l;
         str = QString::fromLatin1(l);
     } else {
         quint32 bytes = 0;
         in >> bytes;                                  // read size of string
         if (bytes == 0xffffffff) {                    // null string
             str.clear();
         } else if (bytes > 0) {                       // not empty
             if (bytes & 0x1) {
                 str.clear();
                 in.setStatus(QDataStream::ReadCorruptData);
                 return in;
             }
             const quint32 Step = 1024 * 1024;
             quint32 len = bytes / 2;
             quint32 allocated = 0;
             while (allocated < len) {
                 int blockSize = qMin(Step, len - allocated);
                 str.resize(allocated + blockSize);
                 if (in.readRawData(reinterpret_cast<char *>(str.data()) + allocated * 2,
                                    blockSize * 2) != blockSize * 2) {
                     str.clear();
                     in.setStatus(QDataStream::ReadPastEnd);
                     return in;
                 }
                 allocated += blockSize;
             }
             if ((in.byteOrder() == QDataStream::BigEndian)
                     != (QSysInfo::ByteOrder == QSysInfo::BigEndian)) {
                 ushort *data = reinterpret_cast<ushort *>(str.data());
                 while (len--) {
                     *data = qbswap(*data);
                     ++data;
                 }
             }
         } else {
             str = QLatin1String("");
         }
     }
     return in;
 }
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QString , Q_MOVABLE_TYPE)
Referenced by QString::fromStdWString().
qStringComparisonHelper() [1/2]
bool qStringComparisonHelper (const QString & s1, const char * s2) inline
Definition at line 916 of file qstring.h.
Referenced by operator!=(), and operator==().
 {
 #  ifndef QT_NO_TEXTCODEC
     if (QString::codecForCStrings) return (s1 == QString::fromAscii(s2));
 #  endif
     return (s1 == QLatin1String(s2));
 }
qStringComparisonHelper() [2/2]
bool qStringComparisonHelper (const QStringRef & s1, const char * s2) inline
Definition at line 1228 of file qstring.h.
 {
 #  ifndef QT_NO_TEXTCODEC
     if (QString::codecForCStrings) return (s1 == QString::fromAscii(s2));
 #  endif
     return (s1 == QLatin1String(s2));
 }