Qt 4.8: /src/gui/styles/qstylesheetstyle.cpp File Reference
qstylesheetstyle.cpp File Reference
#include <qglobal.h>
#include "qstylesheetstyle_p.h"
#include "private/qcssutil_p.h"
#include <qdebug.h>
#include <qapplication.h>
#include <qmenu.h>
#include <qmenubar.h>
#include <qpainter.h>
#include <qstyleoption.h>
#include <qlineedit.h>
#include <qwindowsstyle.h>
#include <qcombobox.h>
#include <qplastiquestyle.h>
#include "private/qcssparser_p.h"
#include "private/qmath_p.h"
#include <qabstractscrollarea.h>
#include "private/qabstractscrollarea_p.h"
#include <qtooltip.h>
#include <qshareddata.h>
#include <qradiobutton.h>
#include <qtoolbutton.h>
#include <qscrollbar.h>
#include <qstring.h>
#include <qfile.h>
#include <qcheckbox.h>
#include <qstatusbar.h>
#include <qheaderview.h>
#include <qprogressbar.h>
#include <private/qwindowsstyle_p.h>
#include <qtabbar.h>
#include <QMetaProperty>
#include <qmainwindow.h>
#include <qdockwidget.h>
#include <qmdisubwindow.h>
#include <qdialog.h>
#include <private/qwidget_p.h>
#include <QAbstractSpinBox>
#include <QLabel>
#include "qdrawutil.h"
#include <limits.h>
#include <QtGui/qtoolbar.h>
#include "moc_qstylesheetstyle_p.cpp"
Classes
struct PseudoElementInfo
class QRenderRule
struct QStyleSheetBackgroundData
struct QStyleSheetBorderData
struct QStyleSheetBorderImageData
struct QStyleSheetBoxData
struct QStyleSheetGeometryData
struct QStyleSheetImageData
struct QStyleSheetOutlineData
struct QStyleSheetPaletteData
struct QStyleSheetPositionData
class QStyleSheetStylePrivate
class QStyleSheetStyleRecursionGuard
class QStyleSheetStyleSelector
Macros
#define ceil(x) ((int)(x) + ((x) > 0 && (x) != (int)(x)))
#define RECURSION_GUARD(RETURN)
#define WIDGET(x) (static_cast<QWidget *>(x.ptr))
Enumerations
enum PseudoElement {
PseudoElement_None, PseudoElement_DownArrow, PseudoElement_UpArrow, PseudoElement_LeftArrow,
PseudoElement_RightArrow, PseudoElement_Indicator, PseudoElement_ExclusiveIndicator, PseudoElement_PushButtonMenuIndicator,
PseudoElement_ComboBoxDropDown, PseudoElement_ComboBoxArrow, PseudoElement_Item, PseudoElement_SpinBoxUpButton,
PseudoElement_SpinBoxUpArrow, PseudoElement_SpinBoxDownButton, PseudoElement_SpinBoxDownArrow, PseudoElement_GroupBoxTitle,
PseudoElement_GroupBoxIndicator, PseudoElement_ToolButtonMenu, PseudoElement_ToolButtonMenuArrow, PseudoElement_ToolButtonDownArrow,
PseudoElement_ToolBoxTab, PseudoElement_ScrollBarSlider, PseudoElement_ScrollBarAddPage, PseudoElement_ScrollBarSubPage,
PseudoElement_ScrollBarAddLine, PseudoElement_ScrollBarSubLine, PseudoElement_ScrollBarFirst, PseudoElement_ScrollBarLast,
PseudoElement_ScrollBarUpArrow, PseudoElement_ScrollBarDownArrow, PseudoElement_ScrollBarLeftArrow, PseudoElement_ScrollBarRightArrow,
PseudoElement_SplitterHandle, PseudoElement_ToolBarHandle, PseudoElement_ToolBarSeparator, PseudoElement_MenuScroller,
PseudoElement_MenuTearoff, PseudoElement_MenuCheckMark, PseudoElement_MenuSeparator, PseudoElement_MenuIcon,
PseudoElement_MenuRightArrow, PseudoElement_TreeViewBranch, PseudoElement_HeaderViewSection, PseudoElement_HeaderViewUpArrow,
PseudoElement_HeaderViewDownArrow, PseudoElement_ProgressBarChunk, PseudoElement_TabBarTab, PseudoElement_TabBarScroller,
PseudoElement_TabBarTear, PseudoElement_SliderGroove, PseudoElement_SliderHandle, PseudoElement_SliderAddPage,
PseudoElement_SliderSubPage, PseudoElement_SliderTickmark, PseudoElement_TabWidgetPane, PseudoElement_TabWidgetTabBar,
PseudoElement_TabWidgetLeftCorner, PseudoElement_TabWidgetRightCorner, PseudoElement_DockWidgetTitle, PseudoElement_DockWidgetCloseButton,
PseudoElement_DockWidgetFloatButton, PseudoElement_DockWidgetSeparator, PseudoElement_MdiCloseButton, PseudoElement_MdiMinButton,
PseudoElement_MdiNormalButton, PseudoElement_TitleBar, PseudoElement_TitleBarCloseButton, PseudoElement_TitleBarMinButton,
PseudoElement_TitleBarMaxButton, PseudoElement_TitleBarShadeButton, PseudoElement_TitleBarUnshadeButton, PseudoElement_TitleBarNormalButton,
PseudoElement_TitleBarContextHelpButton, PseudoElement_TitleBarSysMenu, PseudoElement_ViewItem, PseudoElement_ViewItemIcon,
PseudoElement_ViewItemText, PseudoElement_ViewItemIndicator, PseudoElement_ScrollAreaCorner, PseudoElement_TabBarTabCloseButton,
NumPseudoElements
}
Functions
static QWidget * containerWidget (const QWidget *w)
static QVector< Declaration > declarations (const QVector< StyleRule > &styleRules, const QString &part, quint64 pseudoClass=PseudoClass_Unspecified)
static Origin defaultOrigin (int pe)
static Qt::Alignment defaultPosition (int pe)
static PositionMode defaultPositionMode (int pe)
static QWidget * embeddedWidget (QWidget *w)
static quint64 extendedPseudoClass (const QWidget *w)
static QWidget * parentWidget (const QWidget *w)
static QLatin1String propertyNameForStandardPixmap (QStyle::StandardPixmap sp)
static quint64 pseudoClass (QStyle::State state)
static void qt_check_if_internal_widget (const QWidget **w, int *element)
static QStyle::StandardPixmap subControlIcon (int pe)
static QList< QVariant > subControlLayout (const QString &layout)
static bool unstylable (const QWidget *w)
static void updateWidgets (const QList< const QWidget *> &widgets)
static bool verticalTabs (QTabBar::Shape shape)
Variables
static const QStyleSheetStyle * globalStyleSheetStyle = 0
static const PseudoElementInfo knownPseudoElements [NumPseudoElements]
static const char * knownStyleHints []
static const int numKnownStyleHints = sizeof(knownStyleHints)/sizeof(knownStyleHints[0])
static QStyleSheetStyleCaches * styleSheetCaches = 0
Macro Definition Documentation
ceil
#define ceil (x) ((int)(x) + ((x) > 0 && (x) != (int)(x)))
Definition at line 129 of file qstylesheetstyle.cpp.
Referenced by QPatternist::Decimal::ceiling(), QPatternist::AbstractFloat< isDouble >::ceiling(), QStyleSheetStyle::drawControl(), qCeil(), and QSmoothedAnimation::recalc().
RECURSION_GUARD
#define RECURSION_GUARD (RETURN)
Value:
if (globalStyleSheetStyle != 0 && globalStyleSheetStyle != this) { RETURN; } \
    QStyleSheetStyleRecursionGuard recursion_guard(this);
Definition at line 125 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyle::drawComplexControl(), QStyleSheetStyle::drawControl(), QStyleSheetStyle::drawPrimitive(), QStyleSheetStyle::hitTestComplexControl(), QStyleSheetStyle::pixelMetric(), QStyleSheetStyle::polish(), QStyleSheetStyle::sizeFromContents(), QStyleSheetStyle::standardIconImplementation(), QStyleSheetStyle::standardPixmap(), QStyleSheetStyle::styleHint(), QStyleSheetStyle::styleSheetPalette(), QStyleSheetStyle::subControlRect(), QStyleSheetStyle::subElementRect(), and QStyleSheetStyle::unpolish().
WIDGET
#define WIDGET (x) (static_cast<QWidget *>(x.ptr))
Definition at line 1409 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyleSelector::attribute(), QStyleSheetStyleSelector::nodeIds(), QStyleSheetStyleSelector::nodeNameEquals(), QStyleSheetStyleSelector::nodeNames(), and QStyleSheetStyleSelector::parentNode().
Enumeration Type Documentation
PseudoElement
enum PseudoElement
Enumerator
PseudoElement_None
PseudoElement_DownArrow
PseudoElement_UpArrow
PseudoElement_LeftArrow
PseudoElement_RightArrow
PseudoElement_Indicator
PseudoElement_ExclusiveIndicator
PseudoElement_PushButtonMenuIndicator
PseudoElement_ComboBoxDropDown
PseudoElement_ComboBoxArrow
PseudoElement_Item
PseudoElement_SpinBoxUpButton
PseudoElement_SpinBoxUpArrow
PseudoElement_SpinBoxDownButton
PseudoElement_SpinBoxDownArrow
PseudoElement_GroupBoxTitle
PseudoElement_GroupBoxIndicator
PseudoElement_ToolButtonMenu
PseudoElement_ToolButtonMenuArrow
PseudoElement_ToolButtonDownArrow
PseudoElement_ToolBoxTab
PseudoElement_ScrollBarSlider
PseudoElement_ScrollBarAddPage
PseudoElement_ScrollBarSubPage
PseudoElement_ScrollBarAddLine
PseudoElement_ScrollBarSubLine
PseudoElement_ScrollBarFirst
PseudoElement_ScrollBarLast
PseudoElement_ScrollBarUpArrow
PseudoElement_ScrollBarDownArrow
PseudoElement_ScrollBarLeftArrow
PseudoElement_ScrollBarRightArrow
PseudoElement_SplitterHandle
PseudoElement_ToolBarHandle
PseudoElement_ToolBarSeparator
PseudoElement_MenuScroller
PseudoElement_MenuTearoff
PseudoElement_MenuCheckMark
PseudoElement_MenuSeparator
PseudoElement_MenuIcon
PseudoElement_MenuRightArrow
PseudoElement_TreeViewBranch
PseudoElement_HeaderViewSection
PseudoElement_HeaderViewUpArrow
PseudoElement_HeaderViewDownArrow
PseudoElement_ProgressBarChunk
PseudoElement_TabBarTab
PseudoElement_TabBarScroller
PseudoElement_TabBarTear
PseudoElement_SliderGroove
PseudoElement_SliderHandle
PseudoElement_SliderAddPage
PseudoElement_SliderSubPage
PseudoElement_SliderTickmark
PseudoElement_TabWidgetPane
PseudoElement_TabWidgetTabBar
PseudoElement_TabWidgetLeftCorner
PseudoElement_TabWidgetRightCorner
PseudoElement_DockWidgetTitle
PseudoElement_DockWidgetCloseButton
PseudoElement_DockWidgetFloatButton
PseudoElement_DockWidgetSeparator
PseudoElement_MdiCloseButton
PseudoElement_MdiMinButton
PseudoElement_MdiNormalButton
PseudoElement_TitleBar
PseudoElement_TitleBarCloseButton
PseudoElement_TitleBarMinButton
PseudoElement_TitleBarMaxButton
PseudoElement_TitleBarShadeButton
PseudoElement_TitleBarUnshadeButton
PseudoElement_TitleBarNormalButton
PseudoElement_TitleBarContextHelpButton
PseudoElement_TitleBarSysMenu
PseudoElement_ViewItem
PseudoElement_ViewItemIcon
PseudoElement_ViewItemText
PseudoElement_ViewItemIndicator
PseudoElement_ScrollAreaCorner
PseudoElement_TabBarTabCloseButton
NumPseudoElements
Definition at line 131 of file qstylesheetstyle.cpp.
                    {
     PseudoElement_None,
     PseudoElement_DownArrow,
     PseudoElement_UpArrow,
     PseudoElement_LeftArrow,
     PseudoElement_RightArrow,
     PseudoElement_Indicator,
     PseudoElement_ExclusiveIndicator,
     PseudoElement_PushButtonMenuIndicator,
     PseudoElement_ComboBoxDropDown,
     PseudoElement_ComboBoxArrow,
     PseudoElement_Item,
     PseudoElement_SpinBoxUpButton,
     PseudoElement_SpinBoxUpArrow,
     PseudoElement_SpinBoxDownButton,
     PseudoElement_SpinBoxDownArrow,
     PseudoElement_GroupBoxTitle,
     PseudoElement_GroupBoxIndicator,
     PseudoElement_ToolButtonMenu,
     PseudoElement_ToolButtonMenuArrow,
     PseudoElement_ToolButtonDownArrow,
     PseudoElement_ToolBoxTab,
     PseudoElement_ScrollBarSlider,
     PseudoElement_ScrollBarAddPage,
     PseudoElement_ScrollBarSubPage,
     PseudoElement_ScrollBarAddLine,
     PseudoElement_ScrollBarSubLine,
     PseudoElement_ScrollBarFirst,
     PseudoElement_ScrollBarLast,
     PseudoElement_ScrollBarUpArrow,
     PseudoElement_ScrollBarDownArrow,
     PseudoElement_ScrollBarLeftArrow,
     PseudoElement_ScrollBarRightArrow,
     PseudoElement_SplitterHandle,
     PseudoElement_ToolBarHandle,
     PseudoElement_ToolBarSeparator,
     PseudoElement_MenuScroller,
     PseudoElement_MenuTearoff,
     PseudoElement_MenuCheckMark,
     PseudoElement_MenuSeparator,
     PseudoElement_MenuIcon,
     PseudoElement_MenuRightArrow,
     PseudoElement_TreeViewBranch,
     PseudoElement_HeaderViewSection,
     PseudoElement_HeaderViewUpArrow,
     PseudoElement_HeaderViewDownArrow,
     PseudoElement_ProgressBarChunk,
     PseudoElement_TabBarTab,
     PseudoElement_TabBarScroller,
     PseudoElement_TabBarTear,
     PseudoElement_SliderGroove,
     PseudoElement_SliderHandle,
     PseudoElement_SliderAddPage,
     PseudoElement_SliderSubPage,
     PseudoElement_SliderTickmark,
     PseudoElement_TabWidgetPane,
     PseudoElement_TabWidgetTabBar,
     PseudoElement_TabWidgetLeftCorner,
     PseudoElement_TabWidgetRightCorner,
     PseudoElement_DockWidgetTitle,
     PseudoElement_DockWidgetCloseButton,
     PseudoElement_DockWidgetFloatButton,
     PseudoElement_DockWidgetSeparator,
     PseudoElement_MdiCloseButton,
     PseudoElement_MdiMinButton,
     PseudoElement_MdiNormalButton,
     PseudoElement_TitleBar,
     PseudoElement_TitleBarCloseButton,
     PseudoElement_TitleBarMinButton,
     PseudoElement_TitleBarMaxButton,
     PseudoElement_TitleBarShadeButton,
     PseudoElement_TitleBarUnshadeButton,
     PseudoElement_TitleBarNormalButton,
     PseudoElement_TitleBarContextHelpButton,
     PseudoElement_TitleBarSysMenu,
     PseudoElement_ViewItem,
     PseudoElement_ViewItemIcon,
     PseudoElement_ViewItemText,
     PseudoElement_ViewItemIndicator,
     PseudoElement_ScrollAreaCorner,
     PseudoElement_TabBarTabCloseButton,
     NumPseudoElements
 };
Function Documentation
containerWidget()
static QWidget* containerWidget (const QWidget * w) static
Warning
This function is not part of the public interface. in case w is an embedded widget, return the container widget (i.e, the widget for which the rules actualy apply) (exemple, if w is a lineedit embedded in a combobox, return the combobox)
if w is not embedded, return w itself
Definition at line 2356 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyle::drawPrimitive(), QStyleSheetStyle::styleSheetPalette(), unstylable(), and QStyleSheetStyle::updateStyleSheetFont().
 {
 #ifndef QT_NO_LINEEDIT
     if (qobject_cast<const QLineEdit *>(w)) {
         //if the QLineEdit is an embeddedWidget, we need the rule of the real widget
 #ifndef QT_NO_COMBOBOX
         if (qobject_cast<const QComboBox *>(w->parentWidget()))
             return w->parentWidget();
 #endif
 #ifndef QT_NO_SPINBOX
         if (qobject_cast<const QAbstractSpinBox *>(w->parentWidget()))
             return w->parentWidget();
 #endif
     }
 #endif // QT_NO_LINEEDIT
 #ifndef QT_NO_SCROLLAREA
     if (const QAbstractScrollArea *sa = qobject_cast<const QAbstractScrollArea *>(w->parentWidget())) {
         if (sa->viewport() == w)
             return w->parentWidget();
     }
 #endif
     return const_cast<QWidget *>(w);
 }
declarations()
static QVector<Declaration> declarations (const QVector< StyleRule > & styleRules, const QString & part, quint64 pseudoClass = PseudoClass_Unspecified) static
Definition at line 1597 of file qstylesheetstyle.cpp.
Referenced by QScript::AST::VariableStatement::accept0(), QScript::AST::LocalForStatement::accept0(), QDeclarativeJS::AST::VariableStatement::accept0(), QDeclarativeJS::AST::LocalForStatement::accept0(), QStyleSheetStyle::hasStyleRule(), QStyleSheetStyle::renderRule(), QDeclarativeXmlListModel::setNamespaceDeclarations(), QStyleSheetStyle::setProperties(), and QTextHtmlParserNode::uncollapsedMargin().
 {
     QVector<Declaration> decls;
     for (int i = 0; i < styleRules.count(); i++) {
         const Selector& selector = styleRules.at(i).selectors.at(0);
         // Rules with pseudo elements don't cascade. This is an intentional
         // diversion for CSS
         if (part.compare(selector.pseudoElement(), Qt::CaseInsensitive) != 0)
             continue;
         quint64 negated = 0;
         quint64 cssClass = selector.pseudoClass(&negated);
         if ((pseudoClass == PseudoClass_Any) || (cssClass == PseudoClass_Unspecified)
             || ((((cssClass & pseudoClass) == cssClass)) && ((negated & pseudoClass) == 0)))
             decls += styleRules.at(i).declarations;
     }
     return decls;
 }
defaultOrigin()
static Origin defaultOrigin (int pe) static
Definition at line 2061 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyle::positionRect(), and QStyleSheetStyle::subControlRect().
 {
     switch (pe) {
     case PseudoElement_ScrollBarAddPage:
     case PseudoElement_ScrollBarSubPage:
     case PseudoElement_ScrollBarAddLine:
     case PseudoElement_ScrollBarSubLine:
     case PseudoElement_ScrollBarFirst:
     case PseudoElement_ScrollBarLast:
     case PseudoElement_GroupBoxTitle:
     case PseudoElement_GroupBoxIndicator: // never used
     case PseudoElement_ToolButtonMenu:
     case PseudoElement_SliderAddPage:
     case PseudoElement_SliderSubPage:
         return Origin_Border;
     case PseudoElement_SpinBoxUpButton:
     case PseudoElement_SpinBoxDownButton:
     case PseudoElement_PushButtonMenuIndicator:
     case PseudoElement_ComboBoxDropDown:
     case PseudoElement_ToolButtonDownArrow:
     case PseudoElement_MenuCheckMark:
     case PseudoElement_MenuIcon:
     case PseudoElement_MenuRightArrow:
         return Origin_Padding;
     case PseudoElement_Indicator:
     case PseudoElement_ExclusiveIndicator:
     case PseudoElement_ComboBoxArrow:
     case PseudoElement_ScrollBarSlider:
     case PseudoElement_ScrollBarUpArrow:
     case PseudoElement_ScrollBarDownArrow:
     case PseudoElement_ScrollBarLeftArrow:
     case PseudoElement_ScrollBarRightArrow:
     case PseudoElement_SpinBoxUpArrow:
     case PseudoElement_SpinBoxDownArrow:
     case PseudoElement_ToolButtonMenuArrow:
     case PseudoElement_HeaderViewUpArrow:
     case PseudoElement_HeaderViewDownArrow:
     case PseudoElement_SliderGroove:
     case PseudoElement_SliderHandle:
         return Origin_Content;
     default:
         return Origin_Margin;
     }
 }
defaultPosition()
static Qt::Alignment defaultPosition (int pe) static
Definition at line 2109 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyle::positionRect().
 {
     switch (pe) {
     case PseudoElement_Indicator:
     case PseudoElement_ExclusiveIndicator:
     case PseudoElement_MenuCheckMark:
     case PseudoElement_MenuIcon:
         return Qt::AlignLeft | Qt::AlignVCenter;
     case PseudoElement_ScrollBarAddLine:
     case PseudoElement_ScrollBarLast:
     case PseudoElement_SpinBoxDownButton:
     case PseudoElement_PushButtonMenuIndicator:
     case PseudoElement_ToolButtonDownArrow:
         return Qt::AlignRight | Qt::AlignBottom;
     case PseudoElement_ScrollBarSubLine:
     case PseudoElement_ScrollBarFirst:
     case PseudoElement_SpinBoxUpButton:
     case PseudoElement_ComboBoxDropDown:
     case PseudoElement_ToolButtonMenu:
     case PseudoElement_DockWidgetCloseButton:
     case PseudoElement_DockWidgetFloatButton:
         return Qt::AlignRight | Qt::AlignTop;
     case PseudoElement_ScrollBarUpArrow:
     case PseudoElement_ScrollBarDownArrow:
     case PseudoElement_ScrollBarLeftArrow:
     case PseudoElement_ScrollBarRightArrow:
     case PseudoElement_SpinBoxUpArrow:
     case PseudoElement_SpinBoxDownArrow:
     case PseudoElement_ComboBoxArrow:
     case PseudoElement_DownArrow:
     case PseudoElement_ToolButtonMenuArrow:
     case PseudoElement_SliderGroove:
         return Qt::AlignCenter;
     case PseudoElement_GroupBoxTitle:
     case PseudoElement_GroupBoxIndicator: // never used
         return Qt::AlignLeft | Qt::AlignTop;
     case PseudoElement_HeaderViewUpArrow:
     case PseudoElement_HeaderViewDownArrow:
     case PseudoElement_MenuRightArrow:
         return Qt::AlignRight | Qt::AlignVCenter;
     default:
         return 0;
     }
 }
defaultPositionMode()
static PositionMode defaultPositionMode (int pe) static
Definition at line 2261 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyle::positionRect().
 {
     switch (pe) {
     case PseudoElement_ScrollBarFirst:
     case PseudoElement_ScrollBarLast:
     case PseudoElement_ScrollBarAddLine:
     case PseudoElement_ScrollBarSubLine:
     case PseudoElement_ScrollBarAddPage:
     case PseudoElement_ScrollBarSubPage:
     case PseudoElement_ScrollBarSlider:
     case PseudoElement_SliderGroove:
     case PseudoElement_SliderHandle:
     case PseudoElement_TabWidgetPane:
         return PositionMode_Absolute;
     default:
         return PositionMode_Static;
     }
 }
embeddedWidget()
static QWidget* embeddedWidget (QWidget * w) static
Warning
This function is not part of the public interface. For widget that have an embedded widget (such as combobox) return that embedded widget. otherwise return the widget itself
Definition at line 2325 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyle::polish(), QStyleSheetStyle::setPalette(), and QStyleSheetStyle::unsetPalette().
 {
 #ifndef QT_NO_COMBOBOX
     if (QComboBox *cmb = qobject_cast<QComboBox *>(w)) {
         if (cmb->isEditable())
             return cmb->lineEdit();
         else
             return cmb;
     }
 #endif
 #ifndef QT_NO_SPINBOX
     if (QAbstractSpinBox *sb = qobject_cast<QAbstractSpinBox *>(w))
         return sb->findChild<QLineEdit *>();
 #endif
 #ifndef QT_NO_SCROLLAREA
     if (QAbstractScrollArea *sa = qobject_cast<QAbstractScrollArea *>(w))
         return sa->viewport();
 #endif
     return w;
 }
extendedPseudoClass()
static quint64 extendedPseudoClass (const QWidget * w) static
Definition at line 2410 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyle::setGeometry(), QStyleSheetStyle::setPalette(), QStyleSheetStyle::styleSheetPalette(), and QStyleSheetStyle::updateStyleSheetFont().
 {
     quint64 pc = w->isWindow() ? quint64(PseudoClass_Window) : 0;
     if (const QAbstractSlider *slider = qobject_cast<const QAbstractSlider *>(w)) {
         pc |= ((slider->orientation() == Qt::Vertical) ? PseudoClass_Vertical : PseudoClass_Horizontal);
     } else
 #ifndef QT_NO_COMBOBOX
     if (const QComboBox *combo = qobject_cast<const QComboBox *>(w)) {
         if (combo->isEditable())
         pc |= (combo->isEditable() ? PseudoClass_Editable : PseudoClass_ReadOnly);
     } else
 #endif
 #ifndef QT_NO_LINEEDIT
     if (const QLineEdit *edit = qobject_cast<const QLineEdit *>(w)) {
         pc |= (edit->isReadOnly() ? PseudoClass_ReadOnly : PseudoClass_Editable);
     } else
 #endif
     { } // required for the above ifdef'ery to work
     return pc;
 }
parentWidget()
static QWidget* parentWidget (const QWidget * w) inline static
Definition at line 1411 of file qstylesheetstyle.cpp.
Referenced by QGraphicsAnchorLayoutPrivate::addAnchor(), QLayout::addChildLayout(), QLayout::addChildWidget(), QLayout::alignmentRect(), QWidgetPrivate::create_sys(), QWidget::destroy(), getNetWmState(), QFormLayoutPrivate::getStyle(), QToolBarPrivate::init(), QTabBar::initStyleOption(), QWidgetPrivate::isBackgroundInherited(), isServerProcess(), QWidget::mapFromGlobal(), QWidget::mapToGlobal(), QStyleSheetStyleSelector::parentNode(), q_createNativeChildrenAndSetParent(), qt_mac_unregister_widget(), qt_mac_update_widget_position(), QWidgetPrivate::raise_sys(), QMainWindowLayout::removeFromMacToolbar(), QMainWindowLayout::removeToolBar(), QGraphicsWidgetPrivate::resolveLayoutDirection(), QDeclarativeVME::run(), QWidget::setShown(), QBoxLayoutPrivate::setupGeom(), QGridLayoutPrivate::setupSpacings(), QXlibWindow::setVisible(), QWidget::setWindowState(), QStyleSheetStyle::styleRules(), QMdiAreaTabBar::subWindowFromIndex(), QCoreFuriCuri::timerEvent(), QMainWindowLayout::toggleToolBarsVisible(), QLayout::totalHeightForWidth(), QLayout::totalMaximumSize(), QLayout::totalMinimumSize(), QLayout::totalSizeHint(), QAccessible::updateAccessibility(), QGraphicsProxyWidgetPrivate::updateProxyGeometryFromWidget(), and updateRedirectedToGraphicsProxyWidget().
 {
     if(qobject_cast<const QLabel *>(w) && qstrcmp(w->metaObject()->className(), "QTipLabel") == 0) {
         QWidget *p = qvariant_cast<QWidget *>(w->property("_q_stylesheet_parent"));
         if (p)
             return p;
     }
     return w->parentWidget();
 }
propertyNameForStandardPixmap()
static QLatin1String propertyNameForStandardPixmap (QStyle::StandardPixmap sp) static
Warning
This function is not part of the public interface.
Definition at line 5013 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyle::standardIconImplementation(), and QStyleSheetStyle::standardPixmap().
 {
     switch (sp) {
         case QStyle::SP_TitleBarMenuButton: return QLatin1String("titlebar-menu-icon");
         case QStyle::SP_TitleBarMinButton: return QLatin1String("titlebar-minimize-icon");
         case QStyle::SP_TitleBarMaxButton: return QLatin1String("titlebar-maximize-icon");
         case QStyle::SP_TitleBarCloseButton: return QLatin1String("titlebar-close-icon");
         case QStyle::SP_TitleBarNormalButton: return QLatin1String("titlebar-normal-icon");
         case QStyle::SP_TitleBarShadeButton: return QLatin1String("titlebar-shade-icon");
         case QStyle::SP_TitleBarUnshadeButton: return QLatin1String("titlebar-unshade-icon");
         case QStyle::SP_TitleBarContextHelpButton: return QLatin1String("titlebar-contexthelp-icon");
         case QStyle::SP_DockWidgetCloseButton: return QLatin1String("dockwidget-close-icon");
         case QStyle::SP_MessageBoxInformation: return QLatin1String("messagebox-information-icon");
         case QStyle::SP_MessageBoxWarning: return QLatin1String("messagebox-warning-icon");
         case QStyle::SP_MessageBoxCritical: return QLatin1String("messagebox-critical-icon");
         case QStyle::SP_MessageBoxQuestion: return QLatin1String("messagebox-question-icon");
         case QStyle::SP_DesktopIcon: return QLatin1String("desktop-icon");
         case QStyle::SP_TrashIcon: return QLatin1String("trash-icon");
         case QStyle::SP_ComputerIcon: return QLatin1String("computer-icon");
         case QStyle::SP_DriveFDIcon: return QLatin1String("floppy-icon");
         case QStyle::SP_DriveHDIcon: return QLatin1String("harddisk-icon");
         case QStyle::SP_DriveCDIcon: return QLatin1String("cd-icon");
         case QStyle::SP_DriveDVDIcon: return QLatin1String("dvd-icon");
         case QStyle::SP_DriveNetIcon: return QLatin1String("network-icon");
         case QStyle::SP_DirOpenIcon: return QLatin1String("directory-open-icon");
         case QStyle::SP_DirClosedIcon: return QLatin1String("directory-closed-icon");
         case QStyle::SP_DirLinkIcon: return QLatin1String("directory-link-icon");
         case QStyle::SP_FileIcon: return QLatin1String("file-icon");
         case QStyle::SP_FileLinkIcon: return QLatin1String("file-link-icon");
         case QStyle::SP_FileDialogStart: return QLatin1String("filedialog-start-icon");
         case QStyle::SP_FileDialogEnd: return QLatin1String("filedialog-end-icon");
         case QStyle::SP_FileDialogToParent: return QLatin1String("filedialog-parent-directory-icon");
         case QStyle::SP_FileDialogNewFolder: return QLatin1String("filedialog-new-directory-icon");
         case QStyle::SP_FileDialogDetailedView: return QLatin1String("filedialog-detailedview-icon");
         case QStyle::SP_FileDialogInfoView: return QLatin1String("filedialog-infoview-icon");
         case QStyle::SP_FileDialogContentsView: return QLatin1String("filedialog-contentsview-icon");
         case QStyle::SP_FileDialogListView: return QLatin1String("filedialog-listview-icon");
         case QStyle::SP_FileDialogBack: return QLatin1String("filedialog-backward-icon");
         case QStyle::SP_DirIcon: return QLatin1String("directory-icon");
         case QStyle::SP_DialogOkButton: return QLatin1String("dialog-ok-icon");
         case QStyle::SP_DialogCancelButton: return QLatin1String("dialog-cancel-icon");
         case QStyle::SP_DialogHelpButton: return QLatin1String("dialog-help-icon");
         case QStyle::SP_DialogOpenButton: return QLatin1String("dialog-open-icon");
         case QStyle::SP_DialogSaveButton: return QLatin1String("dialog-save-icon");
         case QStyle::SP_DialogCloseButton: return QLatin1String("dialog-close-icon");
         case QStyle::SP_DialogApplyButton: return QLatin1String("dialog-apply-icon");
         case QStyle::SP_DialogResetButton: return QLatin1String("dialog-reset-icon");
         case QStyle::SP_DialogDiscardButton: return QLatin1String("discard-icon");
         case QStyle::SP_DialogYesButton: return QLatin1String("dialog-yes-icon");
         case QStyle::SP_DialogNoButton: return QLatin1String("dialog-no-icon");
         case QStyle::SP_ArrowUp: return QLatin1String("uparrow-icon");
         case QStyle::SP_ArrowDown: return QLatin1String("downarrow-icon");
         case QStyle::SP_ArrowLeft: return QLatin1String("leftarrow-icon");
         case QStyle::SP_ArrowRight: return QLatin1String("rightarrow-icon");
         case QStyle::SP_ArrowBack: return QLatin1String("backward-icon");
         case QStyle::SP_ArrowForward: return QLatin1String("forward-icon");
         case QStyle::SP_DirHomeIcon: return QLatin1String("home-icon");
         default: return QLatin1String("");
     }
 }
pseudoClass()
static quint64 pseudoClass (QStyle::State state) static
Definition at line 1651 of file qstylesheetstyle.cpp.
Referenced by declarations(), QCss::StyleSelector::declarationsForNode(), QStyleSheetStyle::renderRule(), and QStyleSheetStyle::styleSheetPalette().
 {
     quint64 pc = 0;
     if (state & QStyle::State_Enabled) {
         pc |= PseudoClass_Enabled;
         if (state & QStyle::State_MouseOver)
             pc |= PseudoClass_Hover;
     } else {
         pc |= PseudoClass_Disabled;
     }
     if (state & QStyle::State_Active)
         pc |= PseudoClass_Active;
     if (state & QStyle::State_Window)
         pc |= PseudoClass_Window;
     if (state & QStyle::State_Sunken)
         pc |= PseudoClass_Pressed;
     if (state & QStyle::State_HasFocus)
         pc |= PseudoClass_Focus;
     if (state & QStyle::State_On)
         pc |= (PseudoClass_On | PseudoClass_Checked);
     if (state & QStyle::State_Off)
         pc |= (PseudoClass_Off | PseudoClass_Unchecked);
     if (state & QStyle::State_NoChange)
         pc |= PseudoClass_Indeterminate;
     if (state & QStyle::State_Selected)
         pc |= PseudoClass_Selected;
     if (state & QStyle::State_Horizontal)
         pc |= PseudoClass_Horizontal;
     else
         pc |= PseudoClass_Vertical;
     if (state & (QStyle::State_Open | QStyle::State_On | QStyle::State_Sunken))
         pc |= PseudoClass_Open;
     else
         pc |= PseudoClass_Closed;
     if (state & QStyle::State_Children)
         pc |= PseudoClass_Children;
     if (state & QStyle::State_Sibling)
         pc |= PseudoClass_Sibling;
     if (state & QStyle::State_ReadOnly)
         pc |= PseudoClass_ReadOnly;
     if (state & QStyle::State_Item)
         pc |= PseudoClass_Item;
 #ifdef QT_KEYPAD_NAVIGATION
     if (state & QStyle::State_HasEditFocus)
         pc |= PseudoClass_EditFocus;
 #endif
     return pc;
 }
qt_check_if_internal_widget()
static void qt_check_if_internal_widget (const QWidget ** w, int * element) static
Definition at line 1700 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyle::renderRule().
 {
 #ifdef QT_NO_DOCKWIDGET
     Q_UNUSED(w);
     Q_UNUSED(element);
 #else
     if (*w && qstrcmp((*w)->metaObject()->className(), "QDockWidgetTitleButton") == 0) {
         if ((*w)->objectName() == QLatin1String("qt_dockwidget_closebutton")) {
             *element = PseudoElement_DockWidgetCloseButton;
         } else if ((*w)->objectName() == QLatin1String("qt_dockwidget_floatbutton")) {
             *element = PseudoElement_DockWidgetFloatButton;
         }
         *w = (*w)->parentWidget();
     }
 #endif
 }
subControlIcon()
static QStyle::StandardPixmap subControlIcon (int pe) static
Definition at line 845 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyle::drawComplexControl().
 {
     switch (pe) {
     case PseudoElement_MdiCloseButton: return QStyle::SP_TitleBarCloseButton;
     case PseudoElement_MdiMinButton: return QStyle::SP_TitleBarMinButton;
     case PseudoElement_MdiNormalButton: return QStyle::SP_TitleBarNormalButton;
     case PseudoElement_TitleBarCloseButton: return QStyle::SP_TitleBarCloseButton;
     case PseudoElement_TitleBarMinButton: return QStyle::SP_TitleBarMinButton;
     case PseudoElement_TitleBarMaxButton: return QStyle::SP_TitleBarMaxButton;
     case PseudoElement_TitleBarShadeButton: return QStyle::SP_TitleBarShadeButton;
     case PseudoElement_TitleBarUnshadeButton: return QStyle::SP_TitleBarUnshadeButton;
     case PseudoElement_TitleBarNormalButton: return QStyle::SP_TitleBarNormalButton;
     case PseudoElement_TitleBarContextHelpButton: return QStyle::SP_TitleBarContextHelpButton;
     default: break;
     }
     return QStyle::SP_CustomBase;
 }
subControlLayout()
static QList<QVariant> subControlLayout (const QString & layout) static
Definition at line 690 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyle::drawComplexControl(), QRenderRule::QRenderRule(), QStyleSheetStyle::sizeFromContents(), QStyleSheetStyle::subControlRect(), and QStyleSheetStyle::titleBarLayout().
 {
     QList<QVariant> buttons;
     for (int i = 0; i < layout.count(); i++) {
         int button = layout[i].toAscii();
         switch (button) {
         case 'm':
             buttons.append(PseudoElement_MdiMinButton);
             buttons.append(PseudoElement_TitleBarMinButton);
             break;
         case 'M':
             buttons.append(PseudoElement_TitleBarMaxButton);
             break;
         case 'X':
             buttons.append(PseudoElement_MdiCloseButton);
             buttons.append(PseudoElement_TitleBarCloseButton);
             break;
         case 'N':
             buttons.append(PseudoElement_MdiNormalButton);
             buttons.append(PseudoElement_TitleBarNormalButton);
             break;
         case 'I':
             buttons.append(PseudoElement_TitleBarSysMenu);
             break;
         case 'T':
             buttons.append(PseudoElement_TitleBar);
             break;
         case 'H':
             buttons.append(PseudoElement_TitleBarContextHelpButton);
             break;
         case 'S':
             buttons.append(PseudoElement_TitleBarShadeButton);
             break;
         default:
             buttons.append(button);
             break;
         }
     }
     return buttons;
 }
unstylable()
static bool unstylable (const QWidget * w) static
Warning
This function is not part of the public interface. returns true if the widget can NOT be styled directly
Definition at line 2385 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyle::initWidget().
 {
     if (w->windowType() == Qt::Desktop)
         return true;
     if (!w->styleSheet().isEmpty())
         return false;
     if (containerWidget(w) != w)
         return true;
 #ifndef QT_NO_FRAME
     // detect QComboBoxPrivateContainer
     else if (qobject_cast<const QFrame *>(w)) {
         if (0
 #ifndef QT_NO_COMBOBOX
             || qobject_cast<const QComboBox *>(w->parentWidget())
 #endif
            )
             return true;
     }
 #endif
     return false;
 }
updateWidgets()
static void updateWidgets (const QList< const QWidget *> & widgets) static
Definition at line 2587 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyle::repolish().
 {
     if (!styleSheetCaches->styleRulesCache.isEmpty() || !styleSheetCaches->hasStyleRuleCache.isEmpty() || !styleSheetCaches->renderRulesCache.isEmpty()) {
         for (int i = 0; i < widgets.size(); ++i) {
             const QWidget *widget = widgets.at(i);
             styleSheetCaches->styleRulesCache.remove(widget);
             styleSheetCaches->hasStyleRuleCache.remove(widget);
             styleSheetCaches->renderRulesCache.remove(widget);
         }
     }
     for (int i = 0; i < widgets.size(); ++i) {
         QWidget *widget = const_cast<QWidget *>(widgets.at(i));
         if (widget == 0)
             continue;
         widget->style()->polish(widget);
         QEvent event(QEvent::StyleChange);
         QApplication::sendEvent(widget, &event);
         widget->update();
         widget->updateGeometry();
     }
 }
verticalTabs()
static bool verticalTabs (QTabBar::Shape shape) inline static
Definition at line 2836 of file qstylesheetstyle.cpp.
Referenced by QCommonStyle::drawControl(), QMacStyle::drawControl(), QStyleSheetStyle::sizeFromContents(), QCommonStyle::subElementRect(), and QCommonStylePrivate::tabLayout().
 {
     return shape == QTabBar::RoundedWest
            || shape == QTabBar::RoundedEast
            || shape == QTabBar::TriangularWest
            || shape == QTabBar::TriangularEast;
 }
Variable Documentation
globalStyleSheetStyle
const QStyleSheetStyle* globalStyleSheetStyle = 0 static
Definition at line 113 of file qstylesheetstyle.cpp.
Referenced by QRenderRule::QRenderRule().
knownPseudoElements
const PseudoElementInfo knownPseudoElements[NumPseudoElements] static
Definition at line 220 of file qstylesheetstyle.cpp.
knownStyleHints
const char* knownStyleHints[] static
Definition at line 599 of file qstylesheetstyle.cpp.
Referenced by QRenderRule::QRenderRule().
numKnownStyleHints
const int numKnownStyleHints = sizeof(knownStyleHints)/sizeof(knownStyleHints[0]) static
Definition at line 688 of file qstylesheetstyle.cpp.
Referenced by QRenderRule::QRenderRule().
styleSheetCaches
QStyleSheetStyleCaches* styleSheetCaches = 0 static
Definition at line 102 of file qstylesheetstyle.cpp.
Referenced by QStyleSheetStyle::~QStyleSheetStyle().