Qt 4.8: /src/gui/styles/qstyleoption.h File Reference
qstyleoption.h File Reference
#include <QtCore/qvariant.h>
#include <QtGui/qabstractspinbox.h>
#include <QtGui/qicon.h>
#include <QtGui/qmatrix.h>
#include <QtGui/qslider.h>
#include <QtGui/qstyle.h>
#include <QtGui/qtabbar.h>
#include <QtGui/qtabwidget.h>
#include <QtGui/qrubberband.h>
#include <QtGui/qframe.h>
#include <QtCore/qabstractitemmodel.h>
Classes
class QStyleHintReturn
The QStyleHintReturn class provides style hints that return more than basic data types.
class QStyleHintReturnMask
The QStyleHintReturnMask class provides style hints that return a QRegion.
class QStyleHintReturnVariant
The QStyleHintReturnVariant class provides style hints that return a QVariant.
class QStyleOption
The QStyleOption class stores the parameters used by QStyle functions.
class QStyleOptionButton
The QStyleOptionButton class is used to describe the parameters for drawing buttons.
class QStyleOptionComboBox
The QStyleOptionComboBox class is used to describe the parameter for drawing a combobox.
class QStyleOptionComplex
The QStyleOptionComplex class is used to hold parameters that are common to all complex controls.
class QStyleOptionDockWidget
The QStyleOptionDockWidget class is used to describe the parameters for drawing a dock widget.
class QStyleOptionDockWidgetV2
class QStyleOptionFocusRect
The QStyleOptionFocusRect class is used to describe the parameters for drawing a focus rectangle with QStyle.
class QStyleOptionFrame
The QStyleOptionFrame class is used to describe the parameters for drawing a frame.
class QStyleOptionFrameV2
The QStyleOptionFrameV2 class is used to describe the parameters necessary for drawing a frame in Qt 4.1 or above.
class QStyleOptionFrameV3
The QStyleOptionFrameV3 class is used to describe the parameters necessary for drawing a frame in Qt 4.1 or above.
class QStyleOptionGraphicsItem
The QStyleOptionGraphicsItem class is used to describe the parameters needed to draw a QGraphicsItem.
class QStyleOptionGroupBox
The QStyleOptionGroupBox class describes the parameters for drawing a group box.
class QStyleOptionHeader
The QStyleOptionHeader class is used to describe the parameters for drawing a header.
class QStyleOptionMenuItem
The QStyleOptionMenuItem class is used to describe the parameter necessary for drawing a menu item.
class QStyleOptionProgressBar
The QStyleOptionProgressBar class is used to describe the parameters necessary for drawing a progress bar.
class QStyleOptionProgressBarV2
The QStyleOptionProgressBarV2 class is used to describe the parameters necessary for drawing a progress bar in Qt 4.1 or above.
class QStyleOptionQ3DockWindow
The QStyleOptionQ3DockWindow class is used to describe the parameters for drawing various parts of a Q3DockWindow.
class QStyleOptionQ3ListView
The QStyleOptionQ3ListView class is used to describe the parameters for drawing a Q3ListView.
class QStyleOptionQ3ListViewItem
The QStyleOptionQ3ListViewItem class is used to describe an item drawn in a Q3ListView.
class QStyleOptionRubberBand
The QStyleOptionRubberBand class is used to describe the parameters needed for drawing a rubber band.
class QStyleOptionSizeGrip
The QStyleOptionSizeGrip class is used to describe the parameter for drawing a size grip.
class QStyleOptionSlider
The QStyleOptionSlider class is used to describe the parameters needed for drawing a slider.
class QStyleOptionSpinBox
The QStyleOptionSpinBox class is used to describe the parameters necessary for drawing a spin box.
class QStyleOptionTab
The QStyleOptionTab class is used to describe the parameters for drawing a tab bar.
class QStyleOptionTabBarBase
The QStyleOptionTabBarBase class is used to describe the base of a tab bar, i.e.
class QStyleOptionTabBarBaseV2
The QStyleOptionTabBarBaseV2 class is used to describe the base of a tab bar, i.e.
class QStyleOptionTabV2
The QStyleOptionTabV2 class is used to describe the parameters necessary for drawing a tabs in Qt 4.1 or above.
class QStyleOptionTabV3
The QStyleOptionTabV3 class is used to describe the parameters necessary for drawing a tabs in Qt 4.5 or above.
class QStyleOptionTabWidgetFrame
The QStyleOptionTabWidgetFrame class is used to describe the parameters for drawing the frame around a tab widget.
class QStyleOptionTabWidgetFrameV2
The QStyleOptionTabWidgetFrameV2 class is used to describe the parameters for drawing the frame around a tab widget.
class QStyleOptionTitleBar
The QStyleOptionTitleBar class is used to describe the parameters for drawing a title bar.
class QStyleOptionToolBar
The QStyleOptionToolBar class is used to describe the parameters for drawing a toolbar.
class QStyleOptionToolBox
The QStyleOptionToolBox class is used to describe the parameters needed for drawing a tool box.
class QStyleOptionToolBoxV2
The QStyleOptionToolBoxV2 class is used to describe the parameters necessary for drawing a frame in Qt 4.3 or above.
class QStyleOptionToolButton
The QStyleOptionToolButton class is used to describe the parameters for drawing a tool button.
class QStyleOptionViewItem
The QStyleOptionViewItem class is used to describe the parameters used to draw an item in a view widget.
class QStyleOptionViewItemV2
The QStyleOptionViewItemV2 class is used to describe the parameters necessary for drawing a frame in Qt 4.2 or above.
class QStyleOptionViewItemV3
The QStyleOptionViewItemV3 class is used to describe the parameters necessary for drawing a frame in Qt 4.3 or above.
class QStyleOptionViewItemV4
The QStyleOptionViewItemV4 class is used to describe the parameters necessary for drawing a frame in Qt 4.4 or above.
Functions
Q_GUI_EXPORT QDebug operator<< (QDebug debug, const QStyleOption::OptionType &optionType)
Q_GUI_EXPORT QDebug operator<< (QDebug debug, const QStyleOption &option)
template<typename T >
T qstyleoption_cast (const QStyleOption *opt)
template<typename T >
T qstyleoption_cast (QStyleOption *opt)
template<typename T >
T qstyleoption_cast (const QStyleHintReturn *hint)
template<typename T >
T qstyleoption_cast (QStyleHintReturn *hint)
Function Documentation
operator<<() [1/2]
Q_GUI_EXPORT QDebug operator<< (QDebug debug, const QStyleOption::OptionType & optionType)
Definition at line 6396 of file qstyleoption.cpp.
Referenced by qstyleoption_cast().
 {
 #if !defined(QT_NO_DEBUG)
     switch (optionType) {
     case QStyleOption::SO_Default:
         debug << "SO_Default"; break;
     case QStyleOption::SO_FocusRect:
         debug << "SO_FocusRect"; break;
     case QStyleOption::SO_Button:
         debug << "SO_Button"; break;
     case QStyleOption::SO_Tab:
         debug << "SO_Tab"; break;
     case QStyleOption::SO_MenuItem:
         debug << "SO_MenuItem"; break;
     case QStyleOption::SO_Frame:
         debug << "SO_Frame"; break;
     case QStyleOption::SO_ProgressBar:
         debug << "SO_ProgressBar"; break;
     case QStyleOption::SO_ToolBox:
         debug << "SO_ToolBox"; break;
     case QStyleOption::SO_Header:
         debug << "SO_Header"; break;
     case QStyleOption::SO_Q3DockWindow:
         debug << "SO_Q3DockWindow"; break;
     case QStyleOption::SO_DockWidget:
         debug << "SO_DockWidget"; break;
     case QStyleOption::SO_Q3ListViewItem:
         debug << "SO_Q3ListViewItem"; break;
     case QStyleOption::SO_ViewItem:
         debug << "SO_ViewItem"; break;
     case QStyleOption::SO_TabWidgetFrame:
         debug << "SO_TabWidgetFrame"; break;
     case QStyleOption::SO_TabBarBase:
         debug << "SO_TabBarBase"; break;
     case QStyleOption::SO_RubberBand:
         debug << "SO_RubberBand"; break;
     case QStyleOption::SO_Complex:
         debug << "SO_Complex"; break;
     case QStyleOption::SO_Slider:
         debug << "SO_Slider"; break;
     case QStyleOption::SO_SpinBox:
         debug << "SO_SpinBox"; break;
     case QStyleOption::SO_ToolButton:
         debug << "SO_ToolButton"; break;
     case QStyleOption::SO_ComboBox:
         debug << "SO_ComboBox"; break;
     case QStyleOption::SO_Q3ListView:
         debug << "SO_Q3ListView"; break;
     case QStyleOption::SO_TitleBar:
         debug << "SO_TitleBar"; break;
     case QStyleOption::SO_CustomBase:
         debug << "SO_CustomBase"; break;
     case QStyleOption::SO_GroupBox:
         debug << "SO_GroupBox"; break;
     case QStyleOption::SO_ToolBar:
         debug << "SO_ToolBar"; break;
     case QStyleOption::SO_ComplexCustomBase:
         debug << "SO_ComplexCustomBase"; break;
     case QStyleOption::SO_SizeGrip:
         debug << "SO_SizeGrip"; break;
     case QStyleOption::SO_GraphicsItem:
         debug << "SO_GraphicsItem"; break;
     }
 #else
     Q_UNUSED(optionType);
 #endif
     return debug;
 }
operator<<() [2/2]
Q_GUI_EXPORT QDebug operator<< (QDebug debug, const QStyleOption & option)
Definition at line 6465 of file qstyleoption.cpp.
 {
 #if !defined(QT_NO_DEBUG)
     debug << "QStyleOption(";
     debug << QStyleOption::OptionType(option.type);
     debug << ',' << (option.direction == Qt::RightToLeft ? "RightToLeft" : "LeftToRight");
     debug << ',' << option.state;
     debug << ',' << option.rect;
     debug << ')';
 #else
     Q_UNUSED(option);
 #endif
     return debug;
 }
qstyleoption_cast() [1/4]
template<typename T > T qstyleoption_cast (const QStyleOption * opt) related
Definition at line 885 of file qstyleoption.h.
Referenced by QMacStylePrivate::drawColorlessButton(), QCommonStyle::drawControl(), QWindowsVistaStyle::drawControl(), QWindowsMobileStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QCommonStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QDockWidget::initStyleOption(), QItemDelegate::paint(), QCommonStyle::pixelMetric(), QMacStyle::sizeFromContents(), QPlastiqueStyle::styleHint(), QWindowsXPStyle::styleHint(), QCommonStyle::subElementRect(), QCleanlooksStyle::subElementRect(), QWindowsXPStyle::subElementRect(), QWindowsStyle::subElementRect(), QMacStyle::subElementRect(), and QStyleHelper::uniqueName().
 {
     if (opt && opt->version >= static_cast<T>(0)->Version && (opt->type == static_cast<T>(0)->Type
         || int(static_cast<T>(0)->Type) == QStyleOption::SO_Default
         || (int(static_cast<T>(0)->Type) == QStyleOption::SO_Complex
             && opt->type > QStyleOption::SO_Complex)))
         return static_cast<T>(opt);
     return 0;
 }
qstyleoption_cast() [2/4]
template<typename T > T qstyleoption_cast (QStyleOption * opt) related
Definition at line 896 of file qstyleoption.h.
 {
     if (opt && opt->version >= static_cast<T>(0)->Version && (opt->type == static_cast<T>(0)->Type
         || int(static_cast<T>(0)->Type) == QStyleOption::SO_Default
         || (int(static_cast<T>(0)->Type) == QStyleOption::SO_Complex
             && opt->type > QStyleOption::SO_Complex)))
         return static_cast<T>(opt);
     return 0;
 }
qstyleoption_cast() [3/4]
template<typename T > T qstyleoption_cast (const QStyleHintReturn * hint) related
Definition at line 944 of file qstyleoption.h.
 {
     if (hint && hint->version <= static_cast<T>(0)->Version &&
         (hint->type == static_cast<T>(0)->Type || int(static_cast<T>(0)->Type) == QStyleHintReturn::SH_Default))
         return static_cast<T>(hint);
     return 0;
 }
qstyleoption_cast() [4/4]
template<typename T > T qstyleoption_cast (QStyleHintReturn * hint) related
Definition at line 953 of file qstyleoption.h.
 {
     if (hint && hint->version <= static_cast<T>(0)->Version &&
         (hint->type == static_cast<T>(0)->Type || int(static_cast<T>(0)->Type) == QStyleHintReturn::SH_Default))
         return static_cast<T>(hint);
     return 0;
 }