Qt 4.8: /src/svg/qsvggraphics.cpp File Reference
qsvggraphics.cpp File Reference
#include "qsvggraphics_p.h"
#include "qsvgfont_p.h"
#include "qpainter.h"
#include "qtextdocument.h"
#include "qabstracttextdocumentlayout.h"
#include "qtextcursor.h"
#include "qdebug.h"
#include <math.h>
#include <limits.h>
Macros
#define QT_SVG_DRAW_SHAPE(command)
Functions
static QRectF boundsOnStroke (QPainter *p, const QPainterPath &path, qreal width)
Macro Definition Documentation
QT_SVG_DRAW_SHAPE
#define QT_SVG_DRAW_SHAPE (command)
Value:
qreal oldOpacity = p->opacity();                        \
    QBrush oldBrush = p->brush();                           \
    QPen oldPen = p->pen();                                 \
    p->setPen(Qt::NoPen);                                   \
    p->setOpacity(oldOpacity * states.fillOpacity);         \
    command;                                                \
    p->setPen(oldPen);                                      \
    if (oldPen.widthF() != 0) {                             \
        p->setOpacity(oldOpacity * states.strokeOpacity);   \
        p->setBrush(Qt::NoBrush);                           \
        command;                                            \
        p->setBrush(oldBrush);                              \
    }                                                       \
    p->setOpacity(oldOpacity);
Definition at line 59 of file qsvggraphics.cpp.
Referenced by QSvgEllipse::draw(), QSvgPath::draw(), QSvgPolygon::draw(), and QSvgRect::draw().
Function Documentation
boundsOnStroke()
static QRectF boundsOnStroke (QPainter * p, const QPainterPath & path, qreal width) inline static
Definition at line 81 of file qsvggraphics.cpp.
Referenced by QSvgArc::bounds(), QSvgEllipse::bounds(), QSvgLine::bounds(), QSvgPath::bounds(), QSvgPolygon::bounds(), QSvgPolyline::bounds(), and QSvgRect::bounds().
 {
     QPainterPathStroker stroker;
     stroker.setWidth(width);
     QPainterPath stroke = stroker.createStroke(path);
     return p->transform().map(stroke).boundingRect();
 }