Qt 4.8: /src/svg/qsvggenerator.cpp File Reference
qsvggenerator.cpp File Reference
#include "qsvggenerator.h"
#include "qpainterpath.h"
#include "private/qpaintengine_p.h"
#include "private/qtextengine_p.h"
#include "private/qdrawhelper_p.h"
#include "qfile.h"
#include "qtextcodec.h"
#include "qtextstream.h"
#include "qbuffer.h"
#include "qmath.h"
#include "qdebug.h"
Classes
class QSvgGeneratorPrivate
class QSvgPaintEngine
class QSvgPaintEnginePrivate
struct QSvgPaintEnginePrivate::_attributes
Functions
static QPaintEngine::PaintEngineFeatures svgEngineFeatures ()
static void translate_color (const QColor &color, QString *color_string, QString *opacity_string)
static void translate_dashPattern (QVector< qreal > pattern, const qreal &width, QString *pattern_string)
Function Documentation
svgEngineFeatures()
static QPaintEngine::PaintEngineFeatures svgEngineFeatures () inline static
Definition at line 146 of file qsvggenerator.cpp.
 {
     return QPaintEngine::PaintEngineFeatures(
         QPaintEngine::AllFeatures
         & ~QPaintEngine::PatternBrush
         & ~QPaintEngine::PerspectiveTransform
         & ~QPaintEngine::ConicalGradientFill
         & ~QPaintEngine::PorterDuff);
 }
translate_color()
static void translate_color (const QColor & color, QString * color_string, QString * opacity_string) static
Definition at line 62 of file qsvggenerator.cpp.
Referenced by QSvgPaintEngine::qbrushToSvg(), and QSvgPaintEngine::qpenToSvg().
 {
     Q_ASSERT(color_string);
     Q_ASSERT(opacity_string);
     *color_string =
         QString::fromLatin1("#%1%2%3")
         .arg(color.red(), 2, 16, QLatin1Char('0'))
         .arg(color.green(), 2, 16, QLatin1Char('0'))
         .arg(color.blue(), 2, 16, QLatin1Char('0'));
     *opacity_string = QString::number(color.alphaF());
 }
translate_dashPattern()
static void translate_dashPattern (QVector< qreal > pattern, const qreal & width, QString * pattern_string) static
Definition at line 76 of file qsvggenerator.cpp.
Referenced by QSvgPaintEngine::qpenToSvg().
 {
     Q_ASSERT(pattern_string);
     // Note that SVG operates in absolute lengths, whereas Qt uses a length/width ratio.
     foreach (qreal entry, pattern)
         *pattern_string += QString::fromLatin1("%1,").arg(entry * width);
     pattern_string->chop(1);
 }