Qt 4.8: /src/corelib/kernel/qsystemerror.cpp File Reference
qsystemerror.cpp File Reference
#include <qglobal.h>
#include "qsystemerror_p.h"
#include <windows.h>
Functions
static QString standardLibraryErrorString (int errorCode)
static QString windowsErrorString (int errorCode)
Function Documentation
standardLibraryErrorString()
static QString standardLibraryErrorString (int errorCode) static
Definition at line 104 of file qsystemerror.cpp.
Referenced by QSystemError::toString().
 {
     const char *s = 0;
     QString ret;
     switch (errorCode) {
     case 0:
         break;
     case EACCES:
         s = QT_TRANSLATE_NOOP("QIODevice", "Permission denied");
         break;
     case EMFILE:
         s = QT_TRANSLATE_NOOP("QIODevice", "Too many open files");
         break;
     case ENOENT:
         s = QT_TRANSLATE_NOOP("QIODevice", "No such file or directory");
         break;
     case ENOSPC:
         s = QT_TRANSLATE_NOOP("QIODevice", "No space left on device");
         break;
     default: {
     #ifdef Q_OS_WINCE
         ret = windowsErrorString(errorCode);
     #else
         #if !defined(QT_NO_THREAD) && defined(_POSIX_THREAD_SAFE_FUNCTIONS) && _POSIX_VERSION >= 200112L && !defined(Q_OS_INTEGRITY) && !defined(Q_OS_QNX)
             QByteArray buf(1024, '\0');
             ret = fromstrerror_helper(strerror_r(errorCode, buf.data(), buf.size()), buf);
         #else
             ret = QString::fromLocal8Bit(strerror(errorCode));
         #endif
     #endif
     break; }
     }
     if (s) {
         // ######## this breaks moc build currently
         // ret = QCoreApplication::translate("QIODevice", s);
         ret = QString::fromLatin1(s);
     }
     return ret.trimmed();
 }
windowsErrorString()
static QString windowsErrorString (int errorCode) static
Definition at line 84 of file qsystemerror.cpp.
Referenced by standardLibraryErrorString(), and QSystemError::toString().
 {
     QString ret;
     wchar_t *string = 0;
     FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER|FORMAT_MESSAGE_FROM_SYSTEM,
                   NULL,
                   errorCode,
                   MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
                   (LPWSTR)&string,
                   0,
                   NULL);
     ret = QString::fromWCharArray(string);
     LocalFree((HLOCAL)string);
     if (ret.isEmpty() && errorCode == ERROR_MOD_NOT_FOUND)
         ret = QString::fromLatin1("The specified module could not be found.");
     return ret;
 }