Qt 4.8: /src/gui/util/qsystemtrayicon_mac.mm File Reference
qsystemtrayicon_mac.mm File Reference
#include <private/qt_cocoa_helpers_mac_p.h>
#include <private/qsystemtrayicon_p.h>
#include <qtemporaryfile.h>
#include <qimagewriter.h>
#include <qapplication.h>
#include <qdebug.h>
#include <qstyle.h>
#include <private/qt_mac_p.h>
#import <AppKit/AppKit.h>
Classes
protocol <NSMenuDelegate >
class QNSImageView
class QNSMenu
class QNSStatusItem
class QSystemTrayIconQMenu
class QSystemTrayIconSys
Macros
#define QT_MAC_SYSTEMTRAY_USE_GROWL
Functions
Qt::MouseButton cocoaButton2QtButton (NSInteger buttonNum)
NSUInteger keySequenceModifierMask (const QKeySequence &accel)
NSString * keySequenceToKeyEqivalent (const QKeySequence &accel)
bool qt_mac_execute_apple_script (const QString &script, AEDesc *ret)
void qtsystray_sendActivated (QSystemTrayIcon *i, int r)
Macro Definition Documentation
QT_MAC_SYSTEMTRAY_USE_GROWL
#define QT_MAC_SYSTEMTRAY_USE_GROWL
Definition at line 76 of file qsystemtrayicon_mac.mm.
Function Documentation
cocoaButton2QtButton()
Qt::MouseButton cocoaButton2QtButton (NSInteger buttonNum)
Definition at line 797 of file qt_cocoa_helpers_mac.mm.
Referenced by flipPoint().
 {
     if (buttonNum == 0)
         return Qt::LeftButton;
     if (buttonNum == 1)
         return Qt::RightButton;
     if (buttonNum == 2)
         return Qt::MidButton;
     if (buttonNum == 3)
         return Qt::XButton1;
     if (buttonNum == 4)
         return Qt::XButton2;
     return Qt::NoButton;
 }
keySequenceModifierMask()
NSUInteger keySequenceModifierMask (const QKeySequence & accel)
Definition at line 1265 of file qmenu_mac.mm.
Referenced by QMenuPrivate::QMacMenuPrivate::syncAction().
 {
     return constructModifierMask(accel[0]);
 }
keySequenceToKeyEqivalent()
NSString* keySequenceToKeyEqivalent (const QKeySequence & accel)
Definition at line 1254 of file qmenu_mac.mm.
Referenced by QMenuPrivate::QMacMenuPrivate::syncAction().
 {
     quint32 accel_key = (accel[0] & ~(Qt::MODIFIER_MASK | Qt::UNICODE_ACCEL));
     extern QChar qtKey2CocoaKey(Qt::Key key);
     QChar cocoa_key = qtKey2CocoaKey(Qt::Key(accel_key));
     if (cocoa_key.isNull())
         cocoa_key = QChar(accel_key).toLower().unicode();
     return [NSString stringWithCharacters:&cocoa_key.unicode() length:1];
 }
qt_mac_execute_apple_script()
bool qt_mac_execute_apple_script (const QString & script, AEDesc * ret)
Definition at line 346 of file qapplication_mac.mm.
Referenced by QSystemTrayIconPrivate::showMessage_sys().
 {
     const QByteArray l = script.toUtf8(); return qt_mac_execute_apple_script(l.constData(), l.size(), ret);
 }
qtsystray_sendActivated()
void qtsystray_sendActivated (QSystemTrayIcon * i, int r)
Definition at line 703 of file qsystemtrayicon.cpp.
 {
     emit i->activated((QSystemTrayIcon::ActivationReason)r);
 }