Qt 4.8: /src/gui/kernel/qt_cocoa_helpers_mac_p.h File Reference
qt_cocoa_helpers_mac_p.h File Reference
#include <private/qt_mac_p.h>
#include <qapplication.h>
#include <qdesktopwidget.h>
#include <qwidget.h>
#include <qevent.h>
#include <qhash.h>
#include <qlabel.h>
#include <qpointer.h>
#include <qstyle.h>
#include <qstyleoption.h>
#include <qstylepainter.h>
#include <qtimer.h>
#include <qtooltip.h>
#include <private/qeffects_p.h>
#include <private/qwidget_p.h>
#include <qtextdocument.h>
#include <qdebug.h>
#include <qpoint.h>
Classes
class QMacScrollOptimization
Typedefs
typedef struct CGPoint NSPoint
Enumerations
enum { QtCocoaEventSubTypeWakeup = SHRT_MAX, QtCocoaEventSubTypePostMessage = SHRT_MAX-1 }
Functions
QPointF flipPoint (const NSPoint &p)
NSPoint flipPoint (const QPoint &p)
NSPoint flipPoint (const QPointF &p)
int flipYCoordinate (int y)
qreal flipYCoordinate (qreal y)
void macSendToolbarChangeEvent (QWidget *widget)
void macWindowFade (void *window, float durationSeconds=0.15)
void macWindowFlush (void *window)
bool macWindowIsTextured (void *window)
void macWindowSetHasShadow (void *window, bool hasShadow)
bool macWindowToolbarIsVisible (void *window)
void macWindowToolbarSet (void *window, void *toolbarRef)
void macWindowToolbarShow (const QWidget *widget, bool show)
QApplication * qAppInstance ()
Qt::KeyboardModifiers qt_cocoaDragOperation2QtModifiers (uint dragOperations)
Qt::KeyboardModifiers qt_cocoaModifiers2QtModifiers (ulong modifierFlags)
bool qt_dispatchKeyEvent (void *keyEvent, QWidget *widgetToGetEvent)
void qt_dispatchModifiersChanged (void *flagsChangedEvent, QWidget *widgetToGetEvent)
void qt_dispatchTabletProximityEvent (void *tabletEvent)
void qt_dispatchTabletProximityEvent (const ::TabletProximityRec &proxRec)
bool qt_mac_checkForNativeSizeGrip (const QWidget *widget)
void qt_mac_constructQIconFromIconRef (const IconRef icon, const IconRef overlayIcon, QIcon *retIcon, QStyle::StandardPixmap standardIcon=QStyle::SP_CustomBase)
QPixmap qt_mac_convert_iconref (const IconRef icon, int width, int height)
void * qt_mac_create_nsimage (const QPixmap &pm)
void qt_mac_draw_image (CGContextRef context, CGContextRef imageContext, CGRect area, CGRect drawingArea)
OSStatus qt_mac_drawCGImage (CGContextRef cg, const CGRect *inbounds, CGImageRef)
Qt::MouseButton qt_mac_get_button (EventMouseButton button)
Qt::MouseButtons qt_mac_get_buttons (int buttons)
QString qt_mac_get_pasteboardString (OSPasteboardRef paste)
CGFloat qt_mac_get_scalefactor ()
bool qt_mac_handleTabletEvent (void *view, void *event)
QStringList qt_mac_NSArrayToQStringList (void *nsarray)
void qt_mac_post_retranslateAppMenu ()
void * qt_mac_QStringListToNSMutableArrayVoid (const QStringList &list)
void qt_mac_release_graphics_context (CGContextRef context)
void qt_mac_replaceDrawRect (void *window, QWidgetPrivate *widget)
void qt_mac_replaceDrawRectOriginal (void *window, QWidgetPrivate *widget)
void qt_mac_retain_graphics_context (CGContextRef context)
void qt_mac_showBaseLineSeparator (void *window, bool show)
void qt_mac_update_mouseTracking (QWidget *widget)
void qt_mac_updateContentBorderMetricts (void *window, const ::HIContentBorderMetrics &metrics)
void qt_syncCocoaTitleBarButtons (OSWindowRef window, QWidget *widgetForWindow)
Typedef Documentation
NSPoint
typedef struct CGPoint NSPoint
Definition at line 118 of file qt_cocoa_helpers_mac_p.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
QtCocoaEventSubTypeWakeup
QtCocoaEventSubTypePostMessage
Definition at line 123 of file qt_cocoa_helpers_mac_p.h.
      {
     QtCocoaEventSubTypeWakeup       = SHRT_MAX,
     QtCocoaEventSubTypePostMessage  = SHRT_MAX-1
 };
Function Documentation
flipPoint() [1/3]
QPointF flipPoint (const NSPoint & p)
Definition at line 862 of file qt_cocoa_helpers_mac.mm.
Referenced by flipPoint(), flipYCoordinate(), QWidget::mapToGlobal(), QCursor::pos(), qt_mac_handleTabletEvent(), and QApplication::topLevelAt().
 {
     return QPointF(p.x, flipYCoordinate(p.y));
 }
flipPoint() [2/3]
NSPoint flipPoint (const QPoint & p)
Definition at line 867 of file qt_cocoa_helpers_mac.mm.
 {
     return NSMakePoint(p.x(), flipYCoordinate(p.y()));
 }
flipPoint() [3/3]
NSPoint flipPoint (const QPointF & p)
Definition at line 872 of file qt_cocoa_helpers_mac.mm.
 {
     return NSMakePoint(p.x(), flipYCoordinate(p.y()));
 }
flipYCoordinate() [1/2]
int flipYCoordinate (int y) inline
Definition at line 188 of file qt_cocoa_helpers_mac_p.h.
Referenced by QWidgetPrivate::create_sys(), flipPoint(), QWidget::mapFromGlobal(), qt_mac_unregister_widget(), QWidgetPrivate::setGeometry_sys(), and updateRedirectedToGraphicsProxyWidget().
 {
     return QApplication::desktop()->screenGeometry(0).height() - y;
 }
flipYCoordinate() [2/2]
qreal flipYCoordinate (qreal y) inline
Definition at line 193 of file qt_cocoa_helpers_mac_p.h.
 {
     return QApplication::desktop()->screenGeometry(0).height() - y;
 }
macSendToolbarChangeEvent()
void macSendToolbarChangeEvent (QWidget * widget)
Definition at line 435 of file qt_cocoa_helpers_mac.mm.
Referenced by make_win_eventUPP().
 {
     QToolBarChangeEvent ev(!(GetCurrentKeyModifiers() & cmdKey));
     qt_sendSpontaneousEvent(widget, &ev);
 }
macWindowFade()
void macWindowFade (void * window, float durationSeconds = 0.15)
Definition at line 155 of file qt_cocoa_helpers_mac.mm.
Referenced by QMenuPrivate::hideMenu(), QComboBox::hidePopup(), and QTipLabel::timerEvent().
 {
 #ifdef QT_MAC_USE_COCOA
     QMacCocoaAutoReleasePool pool;
 #endif
     OSWindowRef wnd = static_cast<OSWindowRef>(window);
     if (wnd) {
         QWidget *widget;
 #if QT_MAC_USE_COCOA
         widget = [wnd QT_MANGLE_NAMESPACE(qt_qwidget)];
 #else
     const UInt32 kWidgetCreatorQt = kEventClassQt;
     enum {
         kWidgetPropertyQWidget = 'QWId' //QWidget *
     };
         if (GetWindowProperty(static_cast<WindowRef>(window), kWidgetCreatorQt, kWidgetPropertyQWidget, sizeof(widget), 0, &widget) != noErr)
             widget = 0;
 #endif
         if (widget) {
             QMacWindowFader::currentFader()->setFadeDuration(durationSeconds);
             QMacWindowFader::currentFader()->registerWindowToFade(widget);
             QMacWindowFader::currentFader()->performFade();
         }
     }
 }
macWindowFlush()
void macWindowFlush (void * window)
Definition at line 312 of file qt_cocoa_helpers_mac.mm.
Referenced by QEventDispatcherMac::flush().
 {
     OSWindowRef wnd = static_cast<OSWindowRef>(window);
 #if QT_MAC_USE_COCOA
     [wnd flushWindowIfNeeded];
 #else
     HIWindowFlush(wnd);
 #endif
 }
macWindowIsTextured()
bool macWindowIsTextured (void * window)
Definition at line 245 of file qt_cocoa_helpers_mac.mm.
Referenced by qt_mac_is_metal().
 {
     OSWindowRef wnd = static_cast<OSWindowRef>(window);
 #if QT_MAC_USE_COCOA
     return ( [wnd styleMask] & NSTexturedBackgroundWindowMask ) ? true : false;
 #else
     WindowAttributes currentAttributes;
     GetWindowAttributes(wnd, &currentAttributes);
     return (currentAttributes & kWindowMetalAttribute) ? true : false;
 #endif
 }
macWindowSetHasShadow()
void macWindowSetHasShadow (void * window, bool hasShadow)
Definition at line 299 of file qt_cocoa_helpers_mac.mm.
Referenced by QRubberBand::QRubberBand().
 {
     OSWindowRef wnd = static_cast<OSWindowRef>(window);
 #if QT_MAC_USE_COCOA
     [wnd setHasShadow:BOOL(hasShadow)];
 #else
     if (hasShadow)
         ChangeWindowAttributes(wnd, 0, kWindowNoShadowAttribute);
     else
         ChangeWindowAttributes(wnd, kWindowNoShadowAttribute, 0);
 #endif
 }
macWindowToolbarIsVisible()
bool macWindowToolbarIsVisible (void * window)
Definition at line 287 of file qt_cocoa_helpers_mac.mm.
Referenced by QToolBar::event(), and QMainWindowLayout::toggleToolBarsVisible().
 {
     OSWindowRef wnd = static_cast<OSWindowRef>(window);
 #if QT_MAC_USE_COCOA
     if (NSToolbar *toolbar = [wnd toolbar])
         return [toolbar isVisible];
     return false;
 #else
     return IsWindowToolbarVisible(wnd);
 #endif
 }
macWindowToolbarSet()
void macWindowToolbarSet (void * window, void * toolbarRef)
Definition at line 277 of file qt_cocoa_helpers_mac.mm.
Referenced by QMainWindowLayout::insertIntoMacToolbar(), and QMainWindowLayout::updateHIToolBarStatus().
 {
     OSWindowRef wnd = static_cast<OSWindowRef>(window);
 #if QT_MAC_USE_COCOA
     [wnd setToolbar:static_cast<NSToolbar *>(toolbarRef)];
 #else
     SetWindowToolbar(wnd, static_cast<HIToolbarRef>(toolbarRef));
 #endif
 }
macWindowToolbarShow()
void macWindowToolbarShow (const QWidget * widget, bool show)
Definition at line 257 of file qt_cocoa_helpers_mac.mm.
Referenced by QToolBar::event(), QToolBarPrivate::init(), QMainWindowLayout::insertIntoMacToolbar(), QMainWindowLayout::syncUnifiedToolbarVisibility(), QMainWindowLayout::updateHIToolBarStatus(), and QToolBar::~QToolBar().
 {
     OSWindowRef wnd = qt_mac_window_for(widget);
 #if QT_MAC_USE_COCOA
     if (NSToolbar *toolbar = [wnd toolbar]) {
         QMacCocoaAutoReleasePool pool;
         if (show != [toolbar isVisible]) {
            [toolbar setVisible:show];
         } else {
             // The toolbar may be in sync, but we are not, update our framestrut.
             qt_widget_private(const_cast<QWidget *>(widget))->updateFrameStrut();
         }
     }
 #else
     qt_widget_private(const_cast<QWidget *>(widget))->updateFrameStrut();
     ShowHideWindowToolbar(wnd, show, false);
 #endif
 }
qAppInstance()
QApplication* qAppInstance () inline
Definition at line 158 of file qt_cocoa_helpers_mac_p.h.
Referenced by qt_mac_handleTabletEvent().
 { return static_cast<QApplication *>(QCoreApplication::instance()); }
qt_cocoaDragOperation2QtModifiers()
Qt::KeyboardModifiers qt_cocoaDragOperation2QtModifiers (uint dragOperations)
Referenced by qAppInstance(), and qtKey2CocoaKey().
qt_cocoaModifiers2QtModifiers()
Qt::KeyboardModifiers qt_cocoaModifiers2QtModifiers (ulong modifierFlags)
Referenced by flipPoint(), qAppInstance(), qt_mac_handleTabletEvent(), and qtKey2CocoaKey().
qt_dispatchKeyEvent()
bool qt_dispatchKeyEvent (void * keyEvent, QWidget * widgetToGetEvent)
Definition at line 812 of file qt_cocoa_helpers_mac.mm.
 {
 #ifndef QT_MAC_USE_COCOA
     Q_UNUSED(keyEvent);
     Q_UNUSED(widgetToGetEvent);
     return false;
 #else
     NSEvent *event = static_cast<NSEvent *>(keyEvent);
     EventRef key_event = static_cast<EventRef>(const_cast<void *>([event eventRef]));
     Q_ASSERT(key_event);
     unsigned int info = 0;
     if ([event type] == NSKeyDown) {
         NSString *characters = [event characters];
         if ([characters length]) {
             unichar value = [characters characterAtIndex:0];
             qt_keymapper_private()->updateKeyMap(0, key_event, (void *)&value);
             info = value;
         }
     }
     if (qt_mac_sendMacEventToWidget(widgetToGetEvent, key_event))
         return true;
     if (mustUseCocoaKeyEvent())
         return qt_dispatchKeyEventWithCocoa(keyEvent, widgetToGetEvent);
     bool consumed = qt_keymapper_private()->translateKeyEvent(widgetToGetEvent, 0, key_event, &info, true);
     return consumed && (info != 0);
 #endif
 }
qt_dispatchModifiersChanged()
void qt_dispatchModifiersChanged (void * flagsChangedEvent, QWidget * widgetToGetEvent)
Definition at line 844 of file qt_cocoa_helpers_mac.mm.
 {
 #ifndef QT_MAC_USE_COCOA
     Q_UNUSED(flagsChangedEvent);
     Q_UNUSED(widgetToGetEvent);
 #else
     UInt32 modifiers = 0;
     // Sync modifiers with Qt
     NSEvent *event = static_cast<NSEvent *>(flagsChangedEvent);
     EventRef key_event = static_cast<EventRef>(const_cast<void *>([event eventRef]));
     Q_ASSERT(key_event);
     GetEventParameter(key_event, kEventParamKeyModifiers, typeUInt32, 0,
                       sizeof(modifiers), 0, &modifiers);
     extern void qt_mac_send_modifiers_changed(quint32 modifiers, QObject *object);
     qt_mac_send_modifiers_changed(modifiers, widgetToGetEvent);
 #endif
 }
qt_dispatchTabletProximityEvent() [1/2]
void qt_dispatchTabletProximityEvent (void * tabletEvent)
Referenced by qAppInstance().
qt_dispatchTabletProximityEvent() [2/2]
void qt_dispatchTabletProximityEvent (const ::TabletProximityRec & proxRec)
Definition at line 477 of file qt_cocoa_helpers_mac.mm.
Referenced by QApplicationPrivate::globalEventProcessor(), qt_mac_tablet_hash(), and QApplicationPrivate::tabletProximityCallback().
 {
     QTabletDeviceData proximityDevice;
     proximityDevice.tabletUniqueID = proxRec.uniqueID;
     proximityDevice.capabilityMask = proxRec.capabilityMask;
     switch (proxRec.pointerType) {
         case NSUnknownPointingDevice:
         default:
             proximityDevice.tabletPointerType = QTabletEvent::UnknownPointer;
             break;
         case NSPenPointingDevice:
             proximityDevice.tabletPointerType = QTabletEvent::Pen;
             break;
         case NSCursorPointingDevice:
             proximityDevice.tabletPointerType = QTabletEvent::Cursor;
             break;
         case NSEraserPointingDevice:
             proximityDevice.tabletPointerType = QTabletEvent::Eraser;
             break;
     }
     uint bits = proxRec.vendorPointerType;
     if (bits == 0 && proximityDevice.tabletUniqueID != 0) {
         // Fallback. It seems that the driver doesn't always include all the information.
         // High-End Wacom devices store their "type" in the uper bits of the Unique ID.
         // I'm not sure how to handle it for consumer devices, but I'll test that in a bit.
         bits = proximityDevice.tabletUniqueID >> 32;
     }
     // Defined in the "EN0056-NxtGenImpGuideX"
     // on Wacom's Developer Website (www.wacomeng.com)
     if (((bits & 0x0006) == 0x0002) && ((bits & 0x0F06) != 0x0902)) {
         proximityDevice.tabletDeviceType = QTabletEvent::Stylus;
     } else {
         switch (bits & 0x0F06) {
             case 0x0802:
                 proximityDevice.tabletDeviceType = QTabletEvent::Stylus;
                 break;
             case 0x0902:
                 proximityDevice.tabletDeviceType = QTabletEvent::Airbrush;
                 break;
             case 0x0004:
                 proximityDevice.tabletDeviceType = QTabletEvent::FourDMouse;
                 break;
             case 0x0006:
                 proximityDevice.tabletDeviceType = QTabletEvent::Puck;
                 break;
             case 0x0804:
                 proximityDevice.tabletDeviceType = QTabletEvent::RotationStylus;
                 break;
             default:
                 proximityDevice.tabletDeviceType = QTabletEvent::NoDevice;
         }
     }
     // The deviceID is "unique" while in the proximity, it's a key that we can use for
     // linking up TabletDeviceData to an event (especially if there are two devices in action).
     bool entering = proxRec.enterProximity;
     if (entering) {
         qt_mac_tablet_hash()->insert(proxRec.deviceID, proximityDevice);
     } else {
         qt_mac_tablet_hash()->remove(proxRec.deviceID);
     }
     QTabletEvent qtabletProximity(entering ? QEvent::TabletEnterProximity
                                   : QEvent::TabletLeaveProximity,
                                   QPoint(), QPoint(), QPointF(), proximityDevice.tabletDeviceType,
                                   proximityDevice.tabletPointerType, 0., 0, 0, 0., 0., 0, 0,
                                   proximityDevice.tabletUniqueID);
     qt_sendSpontaneousEvent(qApp, &qtabletProximity);
 }
qt_mac_checkForNativeSizeGrip()
bool qt_mac_checkForNativeSizeGrip (const QWidget * widget)
Definition at line 371 of file qt_cocoa_helpers_mac.mm.
Referenced by QAbstractScrollAreaPrivate::layoutChildren().
 {
 #ifndef QT_MAC_USE_COCOA
     OSViewRef nativeSizeGrip = 0;
     HIViewFindByID(HIViewGetRoot(HIViewGetWindow(HIViewRef(widget->winId()))), kHIViewWindowGrowBoxID, &nativeSizeGrip);
     return (nativeSizeGrip != 0);
 #else
     return [[reinterpret_cast<NSView *>(widget->effectiveWinId()) window] showsResizeIndicator];
 #endif
 }
qt_mac_constructQIconFromIconRef()
void qt_mac_constructQIconFromIconRef (const IconRef icon, const IconRef overlayIcon, QIcon * retIcon, QStyle::StandardPixmap standardIcon = QStyle::SP_CustomBase)
Definition at line 1610 of file qt_cocoa_helpers_mac.mm.
Referenced by QFileIconProviderPrivate::getWinIcon(), qAppInstance(), and QCommonStyle::standardIconImplementation().
 {
     int size = 16;
     while (size <= 128) {
         const QString cacheKey = QLatin1String("qt_mac_constructQIconFromIconRef") + QString::number(standardIcon) + QString::number(size);
         QPixmap mainIcon;
         if (standardIcon >= QStyle::SP_CustomBase) {
             mainIcon = qt_mac_convert_iconref(icon, size, size);
         } else if (QPixmapCache::find(cacheKey, mainIcon) == false) {
             mainIcon = qt_mac_convert_iconref(icon, size, size);
             QPixmapCache::insert(cacheKey, mainIcon);
         }
         if (overlayIcon) {
             int littleSize = size / 2;
             QPixmap overlayPix = qt_mac_convert_iconref(overlayIcon, littleSize, littleSize);
             QPainter painter(&mainIcon);
             painter.drawPixmap(size - littleSize, size - littleSize, overlayPix);
         }
         retIcon->addPixmap(mainIcon);
         size += size;  // 16 -> 32 -> 64 -> 128
     }
 }
qt_mac_convert_iconref()
QPixmap qt_mac_convert_iconref (const IconRef icon, int width, int height)
Definition at line 1591 of file qt_cocoa_helpers_mac.mm.
Referenced by qAppInstance(), and qt_mac_constructQIconFromIconRef().
 {
     QPixmap ret(width, height);
     ret.fill(QColor(0, 0, 0, 0));
     CGRect rect = CGRectMake(0, 0, width, height);
     CGContextRef ctx = qt_mac_cg_context(&ret);
     CGAffineTransform old_xform = CGContextGetCTM(ctx);
     CGContextConcatCTM(ctx, CGAffineTransformInvert(old_xform));
     CGContextConcatCTM(ctx, CGAffineTransformIdentity);
     ::RGBColor b;
     b.blue = b.green = b.red = 255*255;
     PlotIconRefInContext(ctx, &rect, kAlignNone, kTransformNone, &b, kPlotIconRefNormalFlags, icon);
     CGContextRelease(ctx);
     return ret;
 }
qt_mac_create_nsimage()
void* qt_mac_create_nsimage (const QPixmap & pm)
Definition at line 322 of file qt_cocoa_helpers_mac.mm.
Referenced by qt_mac_set_app_icon(), QCursor::setPos(), QWidgetPrivate::setWindowIcon_sys(), QMenuPrivate::QMacMenuPrivate::syncAction(), and QSystemTrayIconPrivate::updateIcon_sys().
 {
     QMacCocoaAutoReleasePool pool;
     if(QCFType<CGImageRef> image = pm.toMacCGImageRef()) {
         NSImage *newImage = 0;
         NSRect imageRect = NSMakeRect(0.0, 0.0, CGImageGetWidth(image), CGImageGetHeight(image));
         newImage = [[NSImage alloc] initWithSize:imageRect.size];
         [newImage lockFocus];
         {
             CGContextRef imageContext = (CGContextRef)[[NSGraphicsContext currentContext] graphicsPort];
             CGContextDrawImage(imageContext, *(CGRect*)&imageRect, image);
         }
         [newImage unlockFocus];
         return newImage;
     }
     return 0;
 }
qt_mac_draw_image()
void qt_mac_draw_image (CGContextRef context, CGContextRef imageContext, CGRect area, CGRect drawingArea) inline
Definition at line 325 of file qt_cocoa_helpers_mac_p.h.
 {
     CGImageRef image = CGBitmapContextCreateImage(imageContext);
     CGImageRef subImage = CGImageCreateWithImageInRect(image, area);
     CGContextTranslateCTM (context, 0, drawingArea.origin.y + CGRectGetMaxY(drawingArea));
     CGContextScaleCTM(context, 1, -1);
     CGContextDrawImage(context, drawingArea, subImage);
     CGImageRelease(subImage);
     CGImageRelease(image);
 }
qt_mac_drawCGImage()
OSStatus qt_mac_drawCGImage (CGContextRef cg, const CGRect * inbounds, CGImageRef)
Definition at line 349 of file qt_cocoa_helpers_mac.mm.
Referenced by QCoreGraphicsPaintEngine::drawImage(), QCoreGraphicsPaintEngine::drawPixmap(), QMacWindowSurface::flush(), QRasterWindowSurface::flush(), QPixmap::fromMacCGImageRef(), qt_mac_draw_pattern(), and QMacWindowSurface::scroll().
 {
     // Verbatim copy if HIViewDrawCGImage (as shown on Carbon-Dev)
     OSStatus err = noErr;
     require_action(inContext != NULL, InvalidContext, err = paramErr);
     require_action(inBounds != NULL, InvalidBounds, err = paramErr);
     require_action(inImage != NULL, InvalidImage, err = paramErr);
     CGContextSaveGState( inContext );
     CGContextTranslateCTM (inContext, 0, inBounds->origin.y + CGRectGetMaxY(*inBounds));
     CGContextScaleCTM(inContext, 1, -1);
     CGContextDrawImage(inContext, *inBounds, inImage);
     CGContextRestoreGState(inContext);
 InvalidImage:
 InvalidBounds:
 InvalidContext:
     return err;
 }
qt_mac_get_button()
Qt::MouseButton qt_mac_get_button (EventMouseButton button)
Definition at line 418 of file qt_cocoa_helpers_mac.mm.
Referenced by QApplicationPrivate::globalEventProcessor().
 {
 #ifdef DEBUG_MOUSE_MAPS
     qDebug("Qt: internal: **Mapping button: %d (0x%04x)", button, button);
 #endif
     Qt::MouseButtons ret = 0;
     for(int i = 0; qt_mac_mouse_symbols[i].qt_code; i++) {
         if (button == qt_mac_mouse_symbols[i].mac_code) {
 #ifdef DEBUG_MOUSE_MAPS
             qDebug("Qt: internal: got button: %s", qt_mac_mouse_symbols[i].desc);
 #endif
             return Qt::MouseButton(qt_mac_mouse_symbols[i].qt_code);
         }
     }
     return Qt::NoButton;
 }
qt_mac_get_buttons()
Qt::MouseButtons qt_mac_get_buttons (int buttons)
Definition at line 402 of file qt_cocoa_helpers_mac.mm.
Referenced by flipPoint(), and QApplicationPrivate::globalEventProcessor().
 {
 #ifdef DEBUG_MOUSE_MAPS
     qDebug("Qt: internal: **Mapping buttons: %d (0x%04x)", buttons, buttons);
 #endif
     Qt::MouseButtons ret = Qt::NoButton;
     for(int i = 0; qt_mac_mouse_symbols[i].qt_code; i++) {
         if (buttons & (0x01<<(qt_mac_mouse_symbols[i].mac_code-1))) {
 #ifdef DEBUG_MOUSE_MAPS
             qDebug("Qt: internal: got button: %s", qt_mac_mouse_symbols[i].desc);
 #endif
             ret |= Qt::MouseButtons(qt_mac_mouse_symbols[i].qt_code);
         }
     }
     return ret;
 }
qt_mac_get_pasteboardString()
QString qt_mac_get_pasteboardString (OSPasteboardRef paste)
Definition at line 1572 of file qt_cocoa_helpers_mac.mm.
Referenced by flipYCoordinate(), and QMacPasteboard::retrieveData().
 {
     QMacCocoaAutoReleasePool pool;
     NSPasteboard *pb = nil;
     CFStringRef pbname;
     if (PasteboardCopyName(paste, &pbname) == noErr) {
         pb = [NSPasteboard pasteboardWithName:const_cast<NSString *>(reinterpret_cast<const NSString *>(pbname))];
         CFRelease(pbname);
     } else {
         pb = [NSPasteboard generalPasteboard];
     }
     if (pb) {
         NSString *text = [pb stringForType:NSStringPboardType];
         if (text)
             return qt_mac_NSStringToQString(text);
     }
     return QString();
 }
qt_mac_get_scalefactor()
CGFloat qt_mac_get_scalefactor ()
Definition at line 1558 of file qt_cocoa_helpers_mac.mm.
Referenced by QStyleHelper::dpiScaled(), flipYCoordinate(), QPixmapIconEngine::paint(), QIconLoaderEngine::paint(), qt_mac_grabDisplayRect(), QToolButton::sizeHint(), and QCoreGraphicsPaintEngine::updateRenderHints().
 {
 #ifndef QT_MAC_USE_COCOA
     return HIGetScaleFactor();
 #endif
 #if (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_7)
     NSScreen *mainScreen = [NSScreen mainScreen];
     if ([mainScreen respondsToSelector:@selector(backingScaleFactor)])
         return [mainScreen backingScaleFactor];
 #endif
     return 1.0;
 }
qt_mac_handleTabletEvent()
bool qt_mac_handleTabletEvent (void * view, void * event)
Definition at line 1292 of file qt_cocoa_helpers_mac.mm.
Referenced by flipPoint().
 {
 #ifndef QT_MAC_USE_COCOA
     Q_UNUSED(view);
     Q_UNUSED(tabletEvent);
     return false;
 #else
     QT_MANGLE_NAMESPACE(QCocoaView) *theView = static_cast<QT_MANGLE_NAMESPACE(QCocoaView) *>(view);
     NSView *theNSView = static_cast<NSView *>(view);
     NSEvent *theTabletEvent = static_cast<NSEvent *>(tabletEvent);
     NSEventType eventType = [theTabletEvent type];
     if (eventType != NSTabletPoint && [theTabletEvent subtype] != NSTabletPointEventSubtype)
         return false; // Not a tablet event.
     NSPoint windowPoint = [theTabletEvent locationInWindow];
     NSPoint globalPoint = [[theTabletEvent window] convertBaseToScreen:windowPoint];
     QWidget *qwidget = [theView qt_qwidget];
     QWidget *widgetToGetMouse = qwidget;
     QWidget *popup = qAppInstance()->activePopupWidget();
     if (popup && popup != qwidget->window())
         widgetToGetMouse = popup;
     if (qt_mac_sendMacEventToWidget(widgetToGetMouse,
                                 static_cast<EventRef>(const_cast<void *>([theTabletEvent eventRef]))))
         return true;
     if (widgetToGetMouse != qwidget) {
         theNSView = qt_mac_nativeview_for(widgetToGetMouse);
         windowPoint = [[theNSView window] convertScreenToBase:globalPoint];
     }
     NSPoint localPoint = [theNSView convertPoint:windowPoint fromView:nil];
     // Tablet events do not handle WA_TransparentForMouseEvents ATM
     // In theory, people who set the WA_TransparentForMouseEvents attribute won't handle
     // tablet events either in which case they will fall into the mouse event case and get
     // them passed on. This will NOT handle the raw events, but that might not be a big problem.
     const QMacTabletHash *tabletHash = qt_mac_tablet_hash();
     if (!tabletHash->contains([theTabletEvent deviceID])) {
         qWarning("QCocoaView handleTabletEvent: This tablet device is unknown"
                  " (received no proximity event for it). Discarding event.");
         return false;
     }
     const QTabletDeviceData &deviceData = tabletHash->value([theTabletEvent deviceID]);
     QEvent::Type qType;
     switch (eventType) {
     case NSLeftMouseDown:
     case NSRightMouseDown:
         qType = QEvent::TabletPress;
         break;
     case NSLeftMouseUp:
     case NSRightMouseUp:
         qType = QEvent::TabletRelease;
         break;
     case NSMouseMoved:
     case NSTabletPoint:
     case NSLeftMouseDragged:
     case NSRightMouseDragged:
     default:
         qType = QEvent::TabletMove;
         break;
     }
     qreal pressure;
     if (eventType != NSMouseMoved) {
         pressure = [theTabletEvent pressure];
     } else {
         pressure = 0.0;
     }
     NSPoint tilt = [theTabletEvent tilt];
     int xTilt = qRound(tilt.x * 60.0);
     int yTilt = qRound(tilt.y * -60.0);
     qreal tangentialPressure = 0;
     qreal rotation = 0;
     int z = 0;
     if (deviceData.capabilityMask & 0x0200)
         z = [theTabletEvent absoluteZ];
     if (deviceData.capabilityMask & 0x0800)
         tangentialPressure = [theTabletEvent tangentialPressure];
     rotation = [theTabletEvent rotation];
     QPointF hiRes = flipPoint(globalPoint);
     QTabletEvent qtabletEvent(qType, QPoint(localPoint.x, localPoint.y),
                               hiRes.toPoint(), hiRes,
                               deviceData.tabletDeviceType, deviceData.tabletPointerType,
                               pressure, xTilt, yTilt, tangentialPressure, rotation, z,
                               qt_cocoaModifiers2QtModifiers([theTabletEvent modifierFlags]),
                               deviceData.tabletUniqueID);
     qt_sendSpontaneousEvent(widgetToGetMouse, &qtabletEvent);
     return qtabletEvent.isAccepted();
 #endif
 }
qt_mac_NSArrayToQStringList()
QStringList qt_mac_NSArrayToQStringList (void * nsarray)
Definition at line 1486 of file qt_cocoa_helpers_mac.mm.
Referenced by flipYCoordinate().
 {
     QStringList result;
     NSArray *array = static_cast<NSArray *>(nsarray);
     for (NSUInteger i=0; i<[array count]; ++i)
         result << qt_mac_NSStringToQString([array objectAtIndex:i]);
     return result;
 }
qt_mac_post_retranslateAppMenu()
void qt_mac_post_retranslateAppMenu ()
Definition at line 1726 of file qt_cocoa_helpers_mac.mm.
Referenced by QApplication::event(), and QMacScrollOptimization::performDelayedScroll().
 {
 #ifdef QT_MAC_USE_COCOA
     QMacCocoaAutoReleasePool pool;
     qt_cocoaPostMessage([NSApp QT_MANGLE_NAMESPACE(qt_qcocoamenuLoader)], @selector(qtTranslateApplicationMenu));
 #endif
 }
qt_mac_QStringListToNSMutableArrayVoid()
void* qt_mac_QStringListToNSMutableArrayVoid (const QStringList & list)
Definition at line 1495 of file qt_cocoa_helpers_mac.mm.
Referenced by flipYCoordinate().
 {
     NSMutableArray *result = [NSMutableArray arrayWithCapacity:list.size()];
     for (int i=0; i<list.size(); ++i){
         [result addObject:reinterpret_cast<const NSString *>(QCFString::toCFStringRef(list[i]))];
     }
     return result;
 }
qt_mac_release_graphics_context()
void qt_mac_release_graphics_context (CGContextRef context) inline
Definition at line 319 of file qt_cocoa_helpers_mac_p.h.
 {
     CGContextRestoreGState(context);
     CGContextRelease(context);
 }
qt_mac_replaceDrawRect()
void qt_mac_replaceDrawRect (void * window, QWidgetPrivate * widget)
Referenced by QWidget::clearMask(), and qt_mac_updateContentBorderMetricts().
qt_mac_replaceDrawRectOriginal()
void qt_mac_replaceDrawRectOriginal (void * window, QWidgetPrivate * widget)
Referenced by QWidget::clearMask(), and qt_mac_updateContentBorderMetricts().
qt_mac_retain_graphics_context()
void qt_mac_retain_graphics_context (CGContextRef context) inline
Definition at line 313 of file qt_cocoa_helpers_mac_p.h.
 {
     CGContextRetain(context);
     CGContextSaveGState(context);
 }
qt_mac_showBaseLineSeparator()
void qt_mac_showBaseLineSeparator (void * window, bool show)
Referenced by qt_mac_updateContentBorderMetricts().
qt_mac_update_mouseTracking()
void qt_mac_update_mouseTracking (QWidget * widget)
Definition at line 340 of file qt_cocoa_helpers_mac.mm.
Referenced by QWidget::changeEvent(), and QWidget::setAttribute().
 {
 #ifdef QT_MAC_USE_COCOA
     [qt_mac_nativeview_for(widget) updateTrackingAreas];
 #else
     Q_UNUSED(widget);
 #endif
 }
qt_mac_updateContentBorderMetricts()
void qt_mac_updateContentBorderMetricts (void * window, const ::HIContentBorderMetrics & metrics)
Definition at line 1390 of file qt_cocoa_helpers_mac.mm.
Referenced by QTabBarPrivate::updateMacBorderMetrics().
 {
     OSWindowRef theWindow = static_cast<OSWindowRef>(window);
 #if !defined(QT_MAC_USE_COCOA)
 #  if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5
     if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_5) {
         ::HIWindowSetContentBorderThickness(theWindow, &metrics);
     }
 #  else
     Q_UNUSED(window);
     Q_UNUSED(metrics);
 #  endif
 #else
     if ([theWindow styleMask] & NSTexturedBackgroundWindowMask)
         [theWindow setContentBorderThickness:metrics.top forEdge:NSMaxYEdge];
     [theWindow setContentBorderThickness:metrics.bottom forEdge:NSMinYEdge];
 #endif
 }
qt_syncCocoaTitleBarButtons()
void qt_syncCocoaTitleBarButtons (OSWindowRef window, QWidget * widgetForWindow)
Referenced by flipYCoordinate(), qt_mac_QStringListToNSMutableArrayVoid(), and updateRedirectedToGraphicsProxyWidget().