Qt 4.8: /src/gui/kernel/qt_mac_p.h File Reference
qt_mac_p.h File Reference
#include "qmacdefines_mac.h"
#include <CoreServices/CoreServices.h>
#include "QtCore/qglobal.h"
#include "QtCore/qvariant.h"
#include "QtCore/qmimedata.h"
#include "QtCore/qpointer.h"
#include "private/qcore_mac_p.h"
#include "QtGui/qpainter.h"
#include <Carbon/Carbon.h>
Classes
class QMacCGContext
class QMacCocoaAutoReleasePool
struct QMacDndAnswerRecord
class QMacPasteboard
struct QMacPasteboard::Promise
class QMacSmartQuickDrawRegion
class QMacWindowChangeEvent
class QMacWindowFader
Enumerations
enum {
typeAEClipboardChanged = 1, typeQWidget = 1, kEventParamQWidget = 'qwid', kEventQtRequestContext = 13,
kEventQtRequestMenubarUpdate = 14, kEventQtRequestShowSheet = 17, kEventQtRequestActivate = 18, kEventQtRequestWindowChange = 20
}
Functions
QColor qcolorForTheme (ThemeBrush brush)
QColor qcolorForThemeTextColor (ThemeTextColor themeColor)
QFont qfontForThemeFont (ThemeFontID themeID)
void qt_mac_copy_answer_rect (const QDragMoveEvent &event)
bool qt_mac_mouse_inside_answer_rect (QPoint mouse)
QPoint qt_mac_nativeMapFromParent (const QWidget *child, const QPoint &pt)
OSViewRef qt_mac_nativeview_for (const QWidget *)
QString qt_mac_removeMnemonics (const QString &original)
OSWindowRef qt_mac_window_for (const QWidget *)
Variables
const UInt32 kEventClassQt = 'Cute'
QMacDndAnswerRecord qt_mac_dnd_answer_rec
QPaintDevice * qt_mac_safe_pdev
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
typeAEClipboardChanged
typeQWidget
kEventParamQWidget
kEventQtRequestContext
kEventQtRequestMenubarUpdate
kEventQtRequestShowSheet
kEventQtRequestActivate
kEventQtRequestWindowChange
Definition at line 95 of file qt_mac_p.h.
      {
     //AE types
     typeAEClipboardChanged = 1,
     //types
     typeQWidget = 1,  /* QWidget *  */
     //params
     kEventParamQWidget = 'qwid',   /* typeQWidget */
     //events
     kEventQtRequestContext = 13,
     kEventQtRequestMenubarUpdate = 14,
     kEventQtRequestShowSheet = 17,
     kEventQtRequestActivate = 18,
     kEventQtRequestWindowChange = 20
 };
Function Documentation
qcolorForTheme()
QColor qcolorForTheme (ThemeBrush brush)
Definition at line 110 of file qt_mac.cpp.
Referenced by QApplicationPrivate::initializeWidgetPaletteHash(), and QMacStyle::polish().
 {
 #ifndef QT_MAC_USE_COCOA
 #  if (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
     if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_5) {
         return leopardBrush(brush);
     } else
 #  endif
     {
         RGBColor rgbcolor;
         GetThemeBrushAsColor(brush, 32, true, &rgbcolor);
         return QColor(rgbcolor.red / 256, rgbcolor.green / 256, rgbcolor.blue / 256);
     }
 #else
     return leopardBrush(brush);
 #endif
 }
qcolorForThemeTextColor()
QColor qcolorForThemeTextColor (ThemeTextColor themeColor)
Definition at line 128 of file qt_mac.cpp.
Referenced by QApplicationPrivate::initializeWidgetPaletteHash().
 {
 #ifdef Q_OS_MAC32
     RGBColor c;
     GetThemeTextColor(themeColor, 32, true, &c);
     QColor color = QColor(c.red / 256, c.green / 256, c.blue / 256);
     return color;
 #else
     // There is no equivalent to GetThemeTextColor in 64-bit and it was rather bad that
     // I didn't file a request to implement this for Snow Leopard. So, in the meantime
     // I've encoded the values from the GetThemeTextColor. This is not exactly ideal
     // as if someone really wants to mess with themeing, these colors will be wrong.
     // It also means that we need to make sure the values for differences between
     // OS releases (and it will be likely that we are a step behind.)
     switch (themeColor) {
     case kThemeTextColorAlertActive:
     case kThemeTextColorTabFrontActive:
     case kThemeTextColorBevelButtonActive:
     case kThemeTextColorListView:
     case kThemeTextColorPlacardActive:
     case kThemeTextColorPopupButtonActive:
     case kThemeTextColorPopupLabelActive:
     case kThemeTextColorPushButtonActive:
         return Qt::black;
     case kThemeTextColorAlertInactive:
     case kThemeTextColorDialogInactive:
     case kThemeTextColorPlacardInactive:
         return QColor(69, 69, 69, 255);
     case kThemeTextColorPopupButtonInactive:
     case kThemeTextColorPopupLabelInactive:
     case kThemeTextColorPushButtonInactive:
     case kThemeTextColorTabFrontInactive:
     case kThemeTextColorBevelButtonInactive:
         return QColor(127, 127, 127, 255);
     default: {
         QNativeImage nativeImage(16,16, QNativeImage::systemFormat());
         CGRect cgrect = CGRectMake(0, 0, 16, 16);
         HIThemeSetTextFill(themeColor, 0, nativeImage.cg, kHIThemeOrientationNormal);
         CGContextFillRect(nativeImage.cg, cgrect);
         QColor color = nativeImage.image.pixel(0,0);
         return QColor(nativeImage.image.pixel(0 , 0));
     }
     }
 #endif
 }
qfontForThemeFont()
QFont qfontForThemeFont (ThemeFontID themeID)
Definition at line 56 of file qt_mac.cpp.
 {
 #ifndef QT_MAC_USE_COCOA
     static const ScriptCode Script = smRoman;
     Str255 f_name;
     SInt16 f_size;
     Style f_style;
     GetThemeFont(themeID, Script, f_name, &f_size, &f_style);
     return QFont(qt_mac_from_pascal_string(f_name), f_size,
                  (f_style & ::bold) ? QFont::Bold : QFont::Normal,
                  (bool)(f_style & ::italic));
 #else
     QCFType<CTFontRef> ctfont = CopyCTThemeFont(themeID);
     QString familyName = QCFString(CTFontCopyFamilyName(ctfont));
     QCFType<CFDictionaryRef> dict = CTFontCopyTraits(ctfont);
     CFNumberRef num = static_cast<CFNumberRef>(CFDictionaryGetValue(dict, kCTFontWeightTrait));
     float fW;
     CFNumberGetValue(num, kCFNumberFloat32Type, &fW);
     QFont::Weight wght = fW > 0. ? QFont::Bold : QFont::Normal;
     num = static_cast<CFNumberRef>(CFDictionaryGetValue(dict, kCTFontSlantTrait));
     CFNumberGetValue(num, kCFNumberFloatType, &fW);
     bool italic = (fW != 0.0);
     return QFont(familyName, CTFontGetSize(ctfont), wght, italic);
 #endif
 }
qt_mac_copy_answer_rect()
void qt_mac_copy_answer_rect (const QDragMoveEvent & event)
If an answer rect has been set on the event (after being sent to the global event processor), we store that rect so we can check if the mouse is in the same area upon next drag move event.
Definition at line 318 of file qdnd_mac.mm.
Referenced by QMacDndAnswerRecord::clear(), and qt_mac_mouse_inside_answer_rect().
 {
     if (!event.answerRect().isEmpty()) {
         qt_mac_dnd_answer_rec.rect = event.answerRect();
         qt_mac_dnd_answer_rec.buttons = event.mouseButtons();
         qt_mac_dnd_answer_rec.modifiers = event.keyboardModifiers();
         qt_mac_dnd_answer_rec.lastAction = event.dropAction();
     }
 }
qt_mac_mouse_inside_answer_rect()
bool qt_mac_mouse_inside_answer_rect (QPoint mouse)
Definition at line 328 of file qdnd_mac.mm.
Referenced by QMacDndAnswerRecord::clear(), and qt_mac_mouse_inside_answer_rect().
 {
     if (!qt_mac_dnd_answer_rec.rect.isEmpty()
             && qt_mac_dnd_answer_rec.rect.contains(mouse)
             && QApplication::mouseButtons() == qt_mac_dnd_answer_rec.buttons
             && QApplication::keyboardModifiers() == qt_mac_dnd_answer_rec.modifiers)
         return true;
     else
         return false;
 }
qt_mac_nativeMapFromParent()
QPoint qt_mac_nativeMapFromParent (const QWidget * child, const QPoint & pt)
Definition at line 3576 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::childAtRecursiveHelper().
 {
 #ifndef QT_MAC_USE_COCOA
     CGPoint nativePoint = CGPointMake(pt.x(), pt.y());
     HIViewConvertPoint(&nativePoint, qt_mac_nativeview_for(child->parentWidget()),
                        qt_mac_nativeview_for(child));
 #else
     NSPoint nativePoint = [qt_mac_nativeview_for(child) convertPoint:NSMakePoint(pt.x(), pt.y()) fromView:qt_mac_nativeview_for(child->parentWidget())];
 #endif
     return QPoint(nativePoint.x, nativePoint.y);
 }
qt_mac_nativeview_for()
OSViewRef qt_mac_nativeview_for (const QWidget *)
Definition at line 419 of file qwidget_mac.mm.
Referenced by QMenuPrivate::QMacMenuPrivate::addAction(), QWidgetPrivate::create_sys(), QWidget::destroy(), QWidgetPrivate::hide_sys(), QWidgetPrivate::lower_sys(), make_widget_eventUPP(), make_win_eventUPP(), QWidget::mapFromGlobal(), QWidget::mapToGlobal(), QWidget::metric(), qt_mac_dispatchPendingUpdateRequests(), qt_mac_handleTabletEvent(), qt_mac_nativeMapFromParent(), qt_mac_post_retranslateAppMenu(), qt_mac_tablet_hash(), qt_mac_unregister_widget(), qt_mac_update_intersected_gl_widgets(), qt_mac_update_mouseTracking(), qt_mac_update_widget_position(), qt_mac_window_for(), QWidgetPrivate::raise_sys(), QWidgetPrivate::registerDropSite(), QWidgetPrivate::scroll_sys(), QWidgetPrivate::setFocus_sys(), QWidgetPrivate::setGeometry_sys(), QWidgetPrivate::setMask_sys(), QWidgetPrivate::setModal_sys(), QWidgetPrivate::setParent_sys(), QWidgetPrivate::show_sys(), QWidgetPrivate::stackUnder_sys(), QGLContext::updatePaintDevice(), and updateRedirectedToGraphicsProxyWidget().
 {
     return reinterpret_cast<OSViewRef>(w->internalWinId());
 }
qt_mac_removeMnemonics()
QString qt_mac_removeMnemonics (const QString & original)
Definition at line 398 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawComplexControl(), QMacStyle::drawControl(), QMacCocoaAutoReleasePool::handle(), qt_aqua_get_known_size(), qt_mac_menu_merge_action(), QMacStyle::subControlRect(), QMenuBarPrivate::QMacMenuBarPrivate::syncAction(), and QMenuPrivate::QMacMenuPrivate::syncAction().
 {
     QString returnText(original.size(), 0);
     int finalDest = 0;
     int currPos = 0;
     int l = original.length();
     while (l) {
         if (original.at(currPos) == QLatin1Char('&')
             && (l == 1 || original.at(currPos + 1) != QLatin1Char('&'))) {
             ++currPos;
             --l;
             if (l == 0)
                 break;
         }
         returnText[finalDest] = original.at(currPos);
         ++currPos;
         ++finalDest;
         --l;
     }
     returnText.truncate(finalDest);
     return returnText;
 }
qt_mac_window_for()
OSWindowRef qt_mac_window_for (const QWidget *)
Definition at line 484 of file qwidget_mac.mm.
 {
     if (OSViewRef hiview = qt_mac_effectiveview_for(w)) {
         OSWindowRef window = qt_mac_window_for(hiview);
         if (window)
             return window;
         if (qt_isGenuineQWidget(hiview)) {
             // This is a workaround for NSToolbar. When a widget is hidden
             // by clicking the toolbar button, Cocoa reparents the widgets
             // to another window (but Qt doesn't know about it).
             // When we start showing them, it reparents back,
             // but at this point it's window is nil, but the window it's being brought
             // into (the Qt one) is for sure created.
             // This stops the hierarchy moving under our feet.
             QWidget *toplevel = w->window();
             if (toplevel != w) {
                 hiview = qt_mac_nativeview_for(toplevel);
                 if (OSWindowRef w = qt_mac_window_for(hiview))
                     return w;
             }
             toplevel->d_func()->createWindow_sys();
             // Reget the hiview since "create window" could potentially move the view (I guess).
             hiview = qt_mac_nativeview_for(toplevel);
             return qt_mac_window_for(hiview);
         }
     }
     return 0;
 }
Variable Documentation
kEventClassQt
const UInt32 kEventClassQt = 'Cute'
Definition at line 92 of file qt_mac_p.h.
Referenced by QApplicationPrivate::globalEventProcessor(), macWindowFade(), QEventDispatcherMac::processEvents(), qt_event_activate_timer_callbk(), qt_event_request_context(), qt_event_request_menubarupdate(), qt_event_request_showsheet(), qt_event_request_window_change(), and qt_event_send_clipboard_changed().
qt_mac_dnd_answer_rec
QMacDndAnswerRecord qt_mac_dnd_answer_rec
Definition at line 67 of file qdnd_mac.mm.
Referenced by QMacDndAnswerRecord::clear().
qt_mac_safe_pdev
QPaintDevice* qt_mac_safe_pdev
Definition at line 166 of file qapplication_mac.mm.