Qt 4.8: /src/gui/widgets/qtabwidget.cpp File Reference
qtabwidget.cpp File Reference
#include "qtabwidget.h"
#include "private/qwidget_p.h"
#include "private/qtabbar_p.h"
#include "qapplication.h"
#include "qbitmap.h"
#include "qdesktopwidget.h"
#include "qevent.h"
#include "qlayout.h"
#include "qstackedwidget.h"
#include "qstyle.h"
#include "qstyleoption.h"
#include "qstylepainter.h"
#include "qtabbar.h"
#include "qtoolbutton.h"
#include "moc_qtabwidget.cpp"
Classes
class QTabWidgetPrivate
Functions
static QSize basicSize (bool horizontal, const QSize &lc, const QSize &rc, const QSize &s, const QSize &t)
Function Documentation
basicSize()
static QSize basicSize (bool horizontal, const QSize & lc, const QSize & rc, const QSize & s, const QSize & t) inline static
Warning
This function is not part of the public interface.
Definition at line 836 of file qtabwidget.cpp.
Referenced by QTabWidget::heightForWidth(), QTabWidget::minimumSizeHint(), and QTabWidget::sizeHint().
 {
     return horizontal
         ? QSize(qMax(s.width(), t.width() + rc.width() + lc.width()),
                 s.height() + (qMax(rc.height(), qMax(lc.height(), t.height()))))
         : QSize(s.width() + (qMax(rc.width(), qMax(lc.width(), t.width()))),
                 qMax(s.height(), t.height() + rc.height() + lc.height()));
 }