Qt 4.8: /src/gui/widgets/qtabbar.cpp File Reference
qtabbar.cpp File Reference
#include "private/qlayoutengine_p.h"
#include "qabstractitemdelegate.h"
#include "qapplication.h"
#include "qbitmap.h"
#include "qcursor.h"
#include "qevent.h"
#include "qpainter.h"
#include "qstyle.h"
#include "qstyleoption.h"
#include "qstylepainter.h"
#include "qtabwidget.h"
#include "qtooltip.h"
#include "qwhatsthis.h"
#include "private/qtextengine_p.h"
#include "qaccessible.h"
#include "qdebug.h"
#include "private/qtabbar_p.h"
#include <private/qt_mac_p.h>
#include <private/qt_cocoa_helpers_mac_p.h>
#include "qs60style.h"
#include "moc_qtabbar.cpp"
Functions
static QString computeElidedText (Qt::TextElideMode mode, const QString &text)
static bool verticalTabs (QTabBar::Shape shape)
Function Documentation
computeElidedText()
static QString computeElidedText (Qt::TextElideMode mode, const QString & text) static
Definition at line 1349 of file qtabbar.cpp.
Referenced by QTabBarPrivate::minimumTabSizeHint().
 {
     if (text.length() <= 3)
         return text;
     static const QLatin1String Ellipses("...");
     QString ret;
     switch (mode) {
     case Qt::ElideRight:
         ret = text.left(2) + Ellipses;
         break;
     case Qt::ElideMiddle:
         ret = text.left(1) + Ellipses + text.right(1);
         break;
     case Qt::ElideLeft:
         ret = Ellipses + text.right(2);
         break;
     case Qt::ElideNone:
         ret = text;
         break;
     }
     return ret;
 }
verticalTabs()
static bool verticalTabs (QTabBar::Shape shape) inline static
Definition at line 77 of file qtabbar.cpp.
Referenced by QTabBarPrivate::_q_scrollTabs(), QTabBarPrivate::layoutTab(), QTabBarPrivate::layoutTabs(), QTabBarPrivate::makeVisible(), QTabBar::minimumSizeHint(), QTabBar::mouseMoveEvent(), QTabBar::mouseReleaseEvent(), QTabBar::moveTab(), QTabBar::paintEvent(), QTabBarPrivate::slide(), QTabBar::tabRect(), and QTabBar::tabSizeHint().
 {
     return shape == QTabBar::RoundedWest
            || shape == QTabBar::RoundedEast
            || shape == QTabBar::TriangularWest
            || shape == QTabBar::TriangularEast;
 }