Qt 4.8: /src/corelib/concurrent/qtconcurrentiteratekernel.cpp File Reference
qtconcurrentiteratekernel.cpp File Reference
#include "qtconcurrentiteratekernel.h"
#include <mach/mach.h>
#include <mach/mach_time.h>
#include <unistd.h>
#include "private/qfunctions_p.h"
Namespaces
QtConcurrent
The QtConcurrent namespace provides high-level APIs that make it possible to write multi-threaded programs without using low-level threading primitives.
Enumerations
enum { TargetRatio = 100, MedianSize = 7 }
Functions
static double elapsed (qint64 after, qint64 before)
static qint64 getticks ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TargetRatio
MedianSize
Definition at line 65 of file qtconcurrentiteratekernel.cpp.
      {
     TargetRatio = 100,
     MedianSize = 7
 };
Function Documentation
elapsed()
static double elapsed (qint64 after, qint64 before) static
Definition at line 135 of file qtconcurrentiteratekernel.cpp.
Referenced by QDeclarativeFlickablePrivate::handleMouseMoveEvent(), QDeclarativePathViewPrivate::handleMouseReleaseEvent(), QDeclarativeFlickablePrivate::handleMouseReleaseEvent(), QBenchmarkTimeMeasurer::metricType(), QDeclarativeItemPrivate::mirrorChange(), QTime::operator>=(), QDeclarativeSpringAnimationPrivate::QDeclarativeSpringAnimationPrivate(), qt_timeout_value(), QTimeLinePrivate::setCurrentTime(), QProgressDialog::setValue(), QDeclarativeSpringAnimationPrivate::tick(), QSemaphore::tryAcquire(), QUnifiedTimer::updateAnimationsTime(), and QDeclarativeFlickable::viewportMoved().
 {
     return double(after - before);
 }
getticks()
static qint64 getticks () static
Definition at line 72 of file qtconcurrentiteratekernel.cpp.
Referenced by elapsed(), and QBenchmarkTimeMeasurer::metricType().
 {
     return mach_absolute_time();
 }