Qt 4.8: /src/corelib/kernel/qtcore_eval.cpp File Reference
qtcore_eval.cpp File Reference
#include <qcoreevent.h>
#include <qdatetime.h>
#include <qlibraryinfo.h>
#include <qobject.h>
#include <qcoreapplication.h>
#include "stdio.h"
#include "stdlib.h"
#include "qconfig_eval.cpp"
Classes
class QCoreFuriCuri
Macros
#define KILL_DELAY 60 * 1000 * 1
#define WARN_TIMEOUT 60 * 1000 * 119
Functions
static int qt_eval_days_left ()
static int qt_eval_is_supported ()
static QString qt_eval_string ()
Variables
static const char boilerplate_expired []
static const char boilerplate_supported []
static const char boilerplate_unsuported []
static const char will_shutdown_1min []
static const char will_shutdown_now []
Macro Definition Documentation
KILL_DELAY
#define KILL_DELAY 60 * 1000 * 1
Definition at line 147 of file qtcore_eval.cpp.
Referenced by QCoreFuriCuri::timerEvent().
WARN_TIMEOUT
#define WARN_TIMEOUT 60 * 1000 * 119
Definition at line 146 of file qtcore_eval.cpp.
Referenced by QCoreFuriCuri::QCoreFuriCuri().
Function Documentation
qt_eval_days_left()
static int qt_eval_days_left () static
Definition at line 115 of file qtcore_eval.cpp.
Referenced by qt_eval_string(), and QCoreFuriCuri::timerEvent().
 {
     if (qt_eval_is_supported() < 0)
         return -2;
     QDate today = QDate::currentDate();
     QDate build = QLibraryInfo::buildDate();
     return qMax(-1, today.daysTo(build) + 30);
 }
qt_eval_is_supported()
static int qt_eval_is_supported () static
Definition at line 91 of file qtcore_eval.cpp.
Referenced by QCoreFuriCuri::QCoreFuriCuri(), qt_eval_days_left(), and qt_eval_string().
 {
     const volatile char *const license_key = qt_eval_key_data + 12;
     // fast fail
     if (!qt_eval_key_data[0] || !*license_key)
         return -1;
     // is this an unsupported evaluation?
     const volatile char *typecode = license_key;
     int field = 2;
     for ( ; field && *typecode; ++typecode)
         if (*typecode == '-')
             --field;
     if (!field && typecode[1] == '4' && typecode[2] == 'M') {
         if (typecode[0] == 'Q')
             return 0;
         else if (typecode[0] == 'R' || typecode[0] == 'Z')
             return 1;
     }
     return -1;
 }
qt_eval_string()
static QString qt_eval_string () static
Definition at line 125 of file qtcore_eval.cpp.
Referenced by QCoreFuriCuri::timerEvent().
 {
     const char *msg;
     switch (qt_eval_is_supported()) {
     case 0:
         msg = boilerplate_unsuported;
         break;
     case 1:
         msg = boilerplate_supported;
         break;
     default:
         return QString();
         msg = 0;
     }
     return QString::fromLatin1(msg)
         .arg(QLatin1String(QT_VERSION_STR))
         .arg(QLibraryInfo::licensee())
         .arg(qt_eval_days_left());
 }
Variable Documentation
boilerplate_expired
const char boilerplate_expired[] static
Initial value:
=
    "This software is using the trial version of the Qt GUI toolkit.\n"
    "The trial period has expired. If you need more time to\n"
    "evaluate Qt, or if you have any questions about Qt, contact us\n"
    "at: http://qt.nokia.com/about/contact-us.\n\n"
Definition at line 76 of file qtcore_eval.cpp.
Referenced by QCoreFuriCuri::timerEvent().
boilerplate_supported
const char boilerplate_supported[] static
Initial value:
=
    "\nQt %1 Evaluation License\n"
    "Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).\n"
    "All rights reserved.\n\n"
    "This trial version may only be used for evaluation purposes\n"
    "Registered to:\n"
    "   Licensee: %2\n\n"
    "The evaluation expires in %4 days\n\n"
    "Contact http://qt.nokia.com/about/contact-us for pricing and purchasing information.\n"
Definition at line 66 of file qtcore_eval.cpp.
Referenced by qt_eval_string().
boilerplate_unsuported
const char boilerplate_unsuported[] static
Initial value:
=
    "\nQt %1 Evaluation License\n"
    "Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).\n"
    "All rights reserved.\n\n"
    "This trial version may only be used for evaluation purposes\n"
    "and will shut down after 120 minutes.\n"
    "Registered to:\n"
    "   Licensee: %2\n\n"
    "The evaluation expires in %4 days\n\n"
    "Contact http://qt.nokia.com/about/contact-us for pricing and purchasing information.\n"
Definition at line 55 of file qtcore_eval.cpp.
Referenced by qt_eval_string().
will_shutdown_1min
const char will_shutdown_1min[] static
Initial value:
=
    "\nThe evaluation of Qt will SHUT DOWN in 1 minute.\n"
    "Contact http://qt.nokia.com/about/contact-us for pricing and purchasing information.\n"
Definition at line 82 of file qtcore_eval.cpp.
Referenced by QCoreFuriCuri::timerEvent().
will_shutdown_now
const char will_shutdown_now[] static
Initial value:
=
    "\nThe evaluation of Qt has now reached its automatic\n"
    "timeout and will shut down.\n"
    "Contact http://qt.nokia.com/about/contact-us for pricing and purchasing information.\n"
Definition at line 86 of file qtcore_eval.cpp.
Referenced by QCoreFuriCuri::timerEvent().