Qt 4.8: /src/testlib/qtestresult.cpp File Reference
qtestresult.cpp File Reference
#include "QtTest/private/qtestresult_p.h"
#include <QtCore/qglobal.h>
#include "QtTest/private/qtestlog_p.h"
#include "QtTest/qtestdata.h"
#include "QtTest/qtestassert.h"
#include <stdio.h>
#include <string.h>
Namespaces
QTest
The QTest namespace contains all the functions and declarations that are related to the QTestLib tool.
Functions
static bool checkStatement (bool statement, const char *msg, const char *file, int line)
static void clearExpectFail ()
static bool isExpectFailData (const char *dataIndex)
Variables
static const char * QTest::currentAppName = 0
static QTestData * QTest::currentGlobalTestData = 0
static QTestData * QTest::currentTestData = 0
static const char * QTest::currentTestFunc = 0
static const char * QTest::currentTestObjectName = 0
static bool QTest::dataFailed = false
static const char * QTest::expectFailComment = 0
static int QTest::expectFailMode = 0
static bool QTest::failed = false
static int QTest::fails = 0
static QTestResult::TestLocation QTest::location = QTestResult::NoWhere
static int QTest::passes = 0
static bool QTest::skipCurrentTest = false
static int QTest::skips = 0
Function Documentation
checkStatement()
static bool checkStatement (bool statement, const char * msg, const char * file, int line) static
Definition at line 213 of file qtestresult.cpp.
Referenced by QTestResult::compare(), and QTestResult::verify().
 {
     if (statement) {
         if (QTest::expectFailMode) {
             QTestLog::addXPass(msg, file, line);
             bool doContinue = (QTest::expectFailMode == QTest::Continue);
             clearExpectFail();
             QTest::failed = true;
             ++QTest::fails;
             return doContinue;
         }
         return true;
     }
     if (QTest::expectFailMode) {
         QTestLog::addXFail(QTest::expectFailComment, file, line);
         bool doContinue = (QTest::expectFailMode == QTest::Continue);
         clearExpectFail();
         return doContinue;
     }
     QTestResult::addFailure(msg, file, line);
     return false;
 }
clearExpectFail()
static void clearExpectFail () static
Definition at line 134 of file qtestresult.cpp.
Referenced by QTestResult::addFailure(), QTestResult::addSkip(), checkStatement(), QTestResult::expectFail(), and QTestResult::finishedCurrentTestFunction().
 {
     QTest::expectFailMode = 0;
     delete [] const_cast<char *>(QTest::expectFailComment);
     QTest::expectFailComment = 0;
 }
isExpectFailData()
static bool isExpectFailData (const char * dataIndex) static
Definition at line 179 of file qtestresult.cpp.
Referenced by QTestResult::expectFail().
 {
     if (!dataIndex || dataIndex[0] == '\0')
         return true;
     if (!QTest::currentTestData)
         return false;
     if (strcmp(dataIndex, QTest::currentTestData->dataTag()) == 0)
         return true;
     return false;
 }