Qt 4.8: /src/gui/text/qtextcontrol.cpp File Reference
qtextcontrol.cpp File Reference
#include "qtextcontrol_p.h"
#include "qtextcontrol_p_p.h"
#include <qfont.h>
#include <qpainter.h>
#include <qevent.h>
#include <qdebug.h>
#include <qmime.h>
#include <qdrag.h>
#include <qconfig.h>
#include <qclipboard.h>
#include <qmenu.h>
#include <qstyle.h>
#include <qtimer.h>
#include "private/qtextdocumentlayout_p.h"
#include "private/qabstracttextdocumentlayout_p.h"
#include "private/qtextedit_p.h"
#include "qtextdocument.h"
#include "private/qtextdocument_p.h"
#include "qtextlist.h"
#include "private/qtextcontrol_p.h"
#include "qgraphicssceneevent.h"
#include "qprinter.h"
#include "qtextdocumentwriter.h"
#include "private/qtextcursor_p.h"
#include <qtextformat.h>
#include <qdatetime.h>
#include <qbuffer.h>
#include <qapplication.h>
#include <limits.h>
#include <qtexttable.h>
#include <qvariant.h>
#include <qurl.h>
#include <qdesktopservices.h>
#include <qinputcontext.h>
#include <qtooltip.h>
#include <qstyleoption.h>
#include <QtGui/qlineedit.h>
#include <QtGui/qaccessible.h>
#include "private/qapplication_p.h"
#include "private/qshortcutmap_p.h"
#include <qkeysequence.h>
#include "moc_qtextcontrol_p.cpp"
Classes
struct QUnicodeControlCharacter
Macros
#define ACCEL_KEY(k) (!qApp->d_func()->shortcutMap.hasShortcutForKeySequence(k) ? QLatin1Char('\t') + QString(QKeySequence(k)) : QString())
#define NUM_CONTROL_CHARACTERS 10
Functions
static QRectF boundingRectOfFloatsInSelection (const QTextCursor &cursor)
static QTextLine currentTextLine (const QTextCursor &cursor)
static bool cursorPosLessThanLastFramePos (int position, QTextFrame *frame)
static bool firstFramePosLessThanCursorPos (QTextFrame *frame, int position)
Variables
const struct QUnicodeControlCharacter qt_controlCharacters [NUM_CONTROL_CHARACTERS]
bool qt_use_rtl_extensions
Macro Definition Documentation
ACCEL_KEY
#define ACCEL_KEY (k) (!qApp->d_func()->shortcutMap.hasShortcutForKeySequence(k) ? QLatin1Char('\t') + QString(QKeySequence(k)) : QString())
Definition at line 89 of file qtextcontrol.cpp.
Referenced by QTextControl::createStandardContextMenu().
NUM_CONTROL_CHARACTERS
#define NUM_CONTROL_CHARACTERS 10
Definition at line 3082 of file qtextcontrol.cpp.
Referenced by QUnicodeControlCharacterMenu::menuActionTriggered(), and QUnicodeControlCharacterMenu::QUnicodeControlCharacterMenu().
Function Documentation
boundingRectOfFloatsInSelection()
static QRectF boundingRectOfFloatsInSelection (const QTextCursor & cursor) static
Definition at line 1406 of file qtextcontrol.cpp.
Referenced by QTextControl::selectionRect().
 {
     QRectF r;
     QTextFrame *frame = cursor.currentFrame();
     const QList<QTextFrame *> children = frame->childFrames();
     const QList<QTextFrame *>::ConstIterator firstFrame = qLowerBound(children.constBegin(), children.constEnd(),
                                                                       cursor.selectionStart(), firstFramePosLessThanCursorPos);
     const QList<QTextFrame *>::ConstIterator lastFrame = qUpperBound(children.constBegin(), children.constEnd(),
                                                                      cursor.selectionEnd(), cursorPosLessThanLastFramePos);
     for (QList<QTextFrame *>::ConstIterator it = firstFrame; it != lastFrame; ++it) {
         if ((*it)->frameFormat().position() != QTextFrameFormat::InFlow)
             r |= frame->document()->documentLayout()->frameBoundingRect(*it);
     }
     return r;
 }
currentTextLine()
static QTextLine currentTextLine (const QTextCursor & cursor) static
Definition at line 103 of file qtextcontrol.cpp.
Referenced by QTextControlPrivate::cursorMoveKeyEvent(), QTextControlPrivate::extendWordwiseSelection(), and QTextControlPrivate::mouseDoubleClickEvent().
 {
     const QTextBlock block = cursor.block();
     if (!block.isValid())
         return QTextLine();
     const QTextLayout *layout = block.layout();
     if (!layout)
         return QTextLine();
     const int relativePos = cursor.position() - block.position();
     return layout->lineForTextPosition(relativePos);
 }
cursorPosLessThanLastFramePos()
static bool cursorPosLessThanLastFramePos (int position, QTextFrame * frame) inline static
Definition at line 1401 of file qtextcontrol.cpp.
Referenced by boundingRectOfFloatsInSelection().
 {
     return position < frame->lastPosition();
 }
firstFramePosLessThanCursorPos()
static bool firstFramePosLessThanCursorPos (QTextFrame * frame, int position) inline static
Definition at line 1396 of file qtextcontrol.cpp.
Referenced by boundingRectOfFloatsInSelection().
 {
     return frame->firstPosition() < position;
 }
Variable Documentation
qt_controlCharacters
const struct QUnicodeControlCharacter qt_controlCharacters[NUM_CONTROL_CHARACTERS]
Initial value:
= {
    { QT_TRANSLATE_NOOP("QUnicodeControlCharacterMenu", "LRM Left-to-right mark"), 0x200e },
    { QT_TRANSLATE_NOOP("QUnicodeControlCharacterMenu", "RLM Right-to-left mark"), 0x200f },
    { QT_TRANSLATE_NOOP("QUnicodeControlCharacterMenu", "ZWJ Zero width joiner"), 0x200d },
    { QT_TRANSLATE_NOOP("QUnicodeControlCharacterMenu", "ZWNJ Zero width non-joiner"), 0x200c },
    { QT_TRANSLATE_NOOP("QUnicodeControlCharacterMenu", "ZWSP Zero width space"), 0x200b },
    { QT_TRANSLATE_NOOP("QUnicodeControlCharacterMenu", "LRE Start of left-to-right embedding"), 0x202a },
    { QT_TRANSLATE_NOOP("QUnicodeControlCharacterMenu", "RLE Start of right-to-left embedding"), 0x202b },
    { QT_TRANSLATE_NOOP("QUnicodeControlCharacterMenu", "LRO Start of left-to-right override"), 0x202d },
    { QT_TRANSLATE_NOOP("QUnicodeControlCharacterMenu", "RLO Start of right-to-left override"), 0x202e },
    { QT_TRANSLATE_NOOP("QUnicodeControlCharacterMenu", "PDF Pop directional formatting"), 0x202c },
}
Referenced by QUnicodeControlCharacterMenu::menuActionTriggered(), and QUnicodeControlCharacterMenu::QUnicodeControlCharacterMenu().
qt_use_rtl_extensions
bool qt_use_rtl_extensions
Definition at line 266 of file qapplication_win.cpp.
Referenced by QTextControl::createStandardContextMenu().