Qt 4.8: /src/gui/widgets/qtextedit.cpp File Reference
qtextedit.cpp File Reference
#include "qtextedit_p.h"
#include "qlineedit.h"
#include "qtextbrowser.h"
#include <qfont.h>
#include <qpainter.h>
#include <qevent.h>
#include <qdebug.h>
#include <qmime.h>
#include <qdrag.h>
#include <qclipboard.h>
#include <qmenu.h>
#include <qstyle.h>
#include <qtimer.h>
#include "private/qtextdocumentlayout_p.h"
#include "qtextdocument.h"
#include "private/qtextdocument_p.h"
#include "qtextlist.h"
#include "private/qtextcontrol_p.h"
#include <qtextformat.h>
#include <qdatetime.h>
#include <qapplication.h>
#include <limits.h>
#include <qtexttable.h>
#include <qvariant.h>
#include <qinputcontext.h>
#include "moc_qtextedit.cpp"
Classes
class QTextEditControl
Functions
static QSize documentSize (QTextControl *control)
static bool shouldEnableInputMethod (QTextEdit *textedit)
Function Documentation
documentSize()
static QSize documentSize (QTextControl * control) static
Definition at line 238 of file qtextedit.cpp.
Referenced by QTextEditPrivate::_q_adjustScrollbars(), and QPlainTextEditPrivate::_q_adjustScrollbars().
 {
     QTextDocument *doc = control->document();
     QAbstractTextDocumentLayout *layout = doc->documentLayout();
     QSize docSize;
     if (QTextDocumentLayout *tlayout = qobject_cast<QTextDocumentLayout *>(layout)) {
         docSize = tlayout->dynamicDocumentSize().toSize();
         int percentageDone = tlayout->layoutStatus();
         // extrapolate height
         if (percentageDone > 0)
             docSize.setHeight(docSize.height() * 100 / percentageDone);
     } else {
         docSize = layout->documentSize().toSize();
     }
     return docSize;
 }
shouldEnableInputMethod()
static bool shouldEnableInputMethod (QTextEdit * textedit) inline static
Definition at line 77 of file qtextedit.cpp.
Referenced by QTextEdit::setReadOnly().
 {
     return !textedit->isReadOnly();
 }