Qt 4.8: /src/corelib/io/qtextstream.h File Reference
qtextstream.h File Reference
#include <QtCore/qiodevice.h>
#include <QtCore/qstring.h>
#include <QtCore/qchar.h>
#include <QtCore/qlocale.h>
#include <QtCore/qscopedpointer.h>
#include <stdio.h>
Classes
class QTextStream
The QTextStream class provides a convenient interface for reading and writing text.
class QTextStreamManipulator
Typedefs
typedef QTextStream &(* QTextStreamFunction) (QTextStream &)
typedef void(QTextStream::* QTSMFC) (QChar)
typedef void(QTextStream::* QTSMFI) (int)
Functions
Q_CORE_EXPORT QTextStream & bin (QTextStream &s)
Q_CORE_EXPORT QTextStream & bom (QTextStream &s)
Q_CORE_EXPORT QTextStream & center (QTextStream &s)
Q_CORE_EXPORT QTextStream & dec (QTextStream &s)
Q_CORE_EXPORT QTextStream & endl (QTextStream &s)
Q_CORE_EXPORT QTextStream & fixed (QTextStream &s)
Q_CORE_EXPORT QTextStream & flush (QTextStream &s)
Q_CORE_EXPORT QTextStream & forcepoint (QTextStream &s)
Q_CORE_EXPORT QTextStream & forcesign (QTextStream &s)
Q_CORE_EXPORT QTextStream & hex (QTextStream &s)
Q_CORE_EXPORT QTextStream & left (QTextStream &s)
Q_CORE_EXPORT QTextStream & lowercasebase (QTextStream &s)
Q_CORE_EXPORT QTextStream & lowercasedigits (QTextStream &s)
Q_CORE_EXPORT QTextStream & noforcepoint (QTextStream &s)
Q_CORE_EXPORT QTextStream & noforcesign (QTextStream &s)
Q_CORE_EXPORT QTextStream & noshowbase (QTextStream &s)
Q_CORE_EXPORT QTextStream & oct (QTextStream &s)
QTextStream & operator<< (QTextStream &s, QTextStreamFunction f)
QTextStream & operator<< (QTextStream &s, QTextStreamManipulator m)
QTextStream & operator>> (QTextStream &s, QTextStreamFunction f)
QTextStreamManipulator qSetFieldWidth (int width)
QTextStreamManipulator qSetPadChar (QChar ch)
QTextStreamManipulator qSetRealNumberPrecision (int precision)
Q_CORE_EXPORT QTextStream & reset (QTextStream &s)
Q_CORE_EXPORT QTextStream & right (QTextStream &s)
Q_CORE_EXPORT QTextStream & scientific (QTextStream &s)
Q_CORE_EXPORT QTextStream & showbase (QTextStream &s)
Q_CORE_EXPORT QTextStream & uppercasebase (QTextStream &s)
Q_CORE_EXPORT QTextStream & uppercasedigits (QTextStream &s)
Q_CORE_EXPORT QTextStream & ws (QTextStream &s)
Typedef Documentation
QTextStreamFunction
typedef QTextStream&(* QTextStreamFunction) (QTextStream &)
Definition at line 270 of file qtextstream.h.
QTSMFC
typedef void(QTextStream::* QTSMFC) (QChar)
Definition at line 272 of file qtextstream.h.
QTSMFI
typedef void(QTextStream::* QTSMFI) (int)
Definition at line 271 of file qtextstream.h.
Function Documentation
bin()
Q_CORE_EXPORT QTextStream& bin (QTextStream & s) related
Referenced by operator<<(), and splitPolygon().
bom()
Q_CORE_EXPORT QTextStream& bom (QTextStream & s) related
Referenced by QUtf16::convertFromUnicode(), operator<<(), and setByteOrder().
center()
Q_CORE_EXPORT QTextStream& center (QTextStream & s) related
Referenced by QMenuPrivate::activateAction(), dockPosHelper(), QMacStylePrivate::drawCombobox(), QPlastiqueStyle::drawComplexControl(), QWindowsXPStyle::drawControl(), QPlastiqueStyle::drawPrimitive(), QMacStylePrivate::drawTableHeader(), QPlainTextEditPrivate::ensureCursorVisible(), QWidget::event(), QToolBarAreaLayout::fitLayout(), QBspTree::init(), QDockAreaLayout::minimumSize(), QSlider::mousePressEvent(), QAbstractItemView::mousePressEvent(), QTriangulator< T >::ComplexToSimple::Event::operator<(), operator<<(), operator>>(), QPagePreview::paintEvent(), QTriangulator< T >::SimpleToMonotone::pointIsInSector(), QMatrix4x4::QMatrix4x4(), qt_cleanup(), qt_init(), QGraphicsAnchorLayoutPrivate::removeCenterAnchors(), QGraphicsAnchorLayoutPrivate::removeCenterConstraints(), QBBScreen::resizeTopLevelWindow(), QGLEllipseMaskGenerator::screenRect(), QDialogButtonBox::setCenterButtons(), QCoreGraphicsPaintEnginePrivate::setFillBrush(), QSplashScreen::setPixmap(), QSpanData::setup(), QDockAreaLayout::sizeHint(), QPlastiqueStyle::subControlRect(), QCleanlooksStyle::subControlRect(), QGtkStyle::subControlRect(), QPainterPath::swap(), and QmlJSDebugger::ZoomTool::zoomTo100().
dec()
Q_CORE_EXPORT QTextStream& dec (QTextStream & s) related
Referenced by QDoubleValidator::decimals(), operator<<(), QApplication::qwsSetCustomColors(), QXlibWindow::resizeEvent(), QDeclarativePathView::setFlickDeceleration(), QFontEngineQPA::stringToCMap(), QFontEngineQPF::stringToCMap(), QDoubleSpinBoxPrivate::validateAndInterpret(), and QLocalePrivate::validateChars().
endl()
Q_CORE_EXPORT QTextStream& endl (QTextStream & s) related
Referenced by QTransportAuth::authorizeRequest(), QSvgPaintEngine::begin(), QMacPasteboardMimeVCard::convertFromMime(), QSvgPaintEngine::drawPath(), QSvgPaintEngine::drawPolygon(), QSvgPaintEngine::drawTextItem(), QSvgPaintEngine::end(), QWin32PrintEnginePrivate::initialize(), operator<<(), QSplitter::operator<<(), QSvgPaintEngine::qfontToSvg(), QDomDocumentTypePrivate::save(), QSvgPaintEngine::saveLinearGradientBrush(), QSvgPaintEngine::saveRadialGradientBrush(), QSvgPaintEngine::updateState(), write_xpm_image(), and QWSCalibratedMouseHandler::writeCalibration().
fixed()
Q_CORE_EXPORT QTextStream& fixed (QTextStream & s) related
Referenced by QFixed::fromFixed(), QWSDisplay::instance(), QWSServerPrivate::invokeSetAltitude(), loadFontConfig(), operator<<(), QPatternist::XsdSchemaParser::parseFractionDigitsFacet(), QPatternist::XsdSchemaParser::parseLengthFacet(), QPatternist::XsdSchemaParser::parseMaxExclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxInclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxLengthFacet(), QPatternist::XsdSchemaParser::parseMinExclusiveFacet(), QPatternist::XsdSchemaParser::parseMinInclusiveFacet(), QPatternist::XsdSchemaParser::parseMinLengthFacet(), QPatternist::XsdSchemaParser::parseTotalDigitsFacet(), QPatternist::XsdSchemaParser::parseWhiteSpaceFacet(), QFontconfigDatabase::populateFontDatabase(), qt_fillFontDef(), and QWSDisplay::setAltitude().
flush()
Q_CORE_EXPORT QTextStream& flush (QTextStream & s) related
Referenced by QLocalSocketPrivate::_q_pipeClosed(), QWSSoundServerPrivate::feedDevice(), QtMultimediaInternal::QAudioInputBuffer::flushBuffer(), QBBWindow::hasBuffers(), operator<<(), QBBGLWindowSurface::paintDevice(), QFbWindowSurface::paintDevice(), runlengthEncode(), and QFile::symLinkTarget().
forcepoint()
Q_CORE_EXPORT QTextStream& forcepoint (QTextStream & s) related
Referenced by operator<<().
forcesign()
Q_CORE_EXPORT QTextStream& forcesign (QTextStream & s) related
Referenced by operator<<().
hex()
Q_CORE_EXPORT QTextStream& hex (QTextStream & s) related
Referenced by QBasicUnixFontDatabase::addTTFile(), QFontDatabasePrivate::addTTFile(), QRasterPaintEngine::fill(), QPatternist::HexBinary::fromLexical(), QXlibScreen::handleEvent(), QSharedMemoryPrivate::makePlatformSafeKey(), operator<<(), QXlibWindow::QXlibWindow(), QRasterPaintEngine::renderHintsChanged(), QSslSocketPrivate::resetDefaultCiphers(), QXlibWindow::resizeEvent(), QXlibWindow::setVisible(), QXlibWindow::setWindowFlags(), QWSQnxKeyboardHandler::socketActivated(), QFontEngineQPA::stringToCMap(), QFontEngineQPF::stringToCMap(), QPdf::toHex(), QByteArray::toHex(), and QXlibWindow::~QXlibWindow().
left()
Q_CORE_EXPORT QTextStream& left (QTextStream & s) related
Referenced by QScript::AST::BinaryExpression::accept0(), QScript::AST::Expression::accept0(), QDeclarativeJS::AST::BinaryExpression::accept0(), QDeclarativeJS::AST::Expression::accept0(), QBezier::addIfClose(), QGL2PEXVertexArray::addQuad(), QGL2PEXVertexArray::addRect(), QTreeViewPrivate::adjustViewOptionsForIndex(), QFontEngineFT::alphaMapBoundingBox(), QDeclarativeItemPrivate::AnchorLines::AnchorLines(), QFontEngineFT::boundingBox(), QMenuBarPrivate::calcActionRects(), QTriangulator< T >::ComplexToSimple::calculateIntersection(), QTriangulator< T >::ComplexToSimple::calculateIntersections(), QDeclarativeContents::calcWidth(), QAccessibleLineEdit::characterRect(), clipLine(), QItemSelectionModel::columnIntersectsSelection(), QTableView::columnMoved(), QFileSystemModelSorter::compareNodes(), QLayout::contentsMargins(), QGraphicsLayoutItem::contentsRect(), QLayout::contentsRect(), QOpenGLPaintEnginePrivate::copyDrawable(), QAbstractItemModel::decodeData(), QTriangulator< T >::MonotoneToTriangles::decompose(), QBoxLayoutPrivate::deleteAll(), QGridLayoutPrivate::distribute(), QStyleHelper::drawBorderPixmap(), QCommonStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QOpenGLPaintEnginePrivate::drawFastRect(), QGL2PaintEngineExPrivate::drawPixmapFragments(), QPaintBufferEngine::drawRects(), QTreeView::drawRow(), QTableWidget::dropEvent(), QAbstractTableModel::dropMimeData(), QAbstractListModel::dropMimeData(), QStandardItemModel::dropMimeData(), QTessellatorPrivate::emitEdges(), QTextHtmlExporter::emitMargins(), QGraphicsView::ensureVisible(), QFragmentMapData< QTextBlockData >::erase_single(), QWSSoundServerPrivate::feedDevice(), fillTrapezoid(), QOpenGLPaintEnginePrivate::fillVertexArray(), QTextEngine::findItem(), QTextDocumentLayoutPrivate::findY(), QDeclarativeJS::AST::BinaryExpression::firstSourceLocation(), QMatrix4x4::frustum(), QDockAreaLayout::getGrid(), QGridLayoutPrivate::getItemPosition(), QFontEngine::getTrueTypeGlyphIndex(), QFontEngineFT::getUnscaledGlyph(), QXcbKeyboard::handleKeyEvent(), QIntersectionFinder::hasIntersections(), QBoxLayout::heightForWidth(), QGridLayoutPrivate::heightForWidth(), QTableModel::index(), QAxBase::initializeActive(), QAxBase::initializeLicensed(), QAxBase::initializeRemote(), QDialogButtonBoxPrivate::initLayout(), QFragmentMapData< QTextBlockData >::insert_single(), QRegion::intersects(), QDeclarativeItemPrivate::isMirrored(), QByteArray::isSharedWith(), QPatternist::XsdParticleChecker::isUPAConformXsdAll(), QItemSelectionRange::isValid(), QTreeModel::itemChanged(), kerning(), QTextDocumentLayoutPrivate::layoutBlock(), QAbstractScrollAreaPrivate::layoutChildren(), QTextDocumentLayoutPrivate::layoutFlow(), QTableWidgetSelectionRange::leftColumn(), QFontEngineFT::loadGlyph(), QGridLayout::maximumSize(), QDockAreaLayoutItem::maximumSize(), QStatusBarPrivate::messageRect(), QGridLayout::minimumSize(), QDockAreaLayoutItem::minimumSize(), QDockAreaLayout::minimumSize(), miSubtractO(), QFragmentMapData< QTextBlockData >::next(), operator<<(), QMatrix4x4::ortho(), QDeclarativeBorderImage::paint(), QTableView::paintEvent(), QMaxHeap< QTriangulator::ComplexToSimple::Intersection >::pop(), QTextDocumentLayoutPrivate::positionFloat(), QTextEngine::positionInLigature(), QStyleSheetStyle::positionRect(), QFragmentMapData< QTextBlockData >::previous(), QBezier::pt4(), QMatrix4x4::QMatrix4x4(), QRBTree< int >::QRBTree(), QRenderRule::QRenderRule(), qt_grab_cursor(), QAxClientSite::qt_metacall(), qt_painterpath_isect_line_rect(), qt_region_strictContains(), QRasterizer::rasterizeLine(), QFragmentMapData< QTextBlockData >::rebalance(), QGraphicsWidget::rect(), QTriangulator< T >::ComplexToSimple::removeUnwantedEdgesAndConnect(), QTriangulator< T >::ComplexToSimple::reorderEdgeListRange(), QFragmentMapData< QTextBlockData >::rotateLeft(), QItemSelectionModel::rowIntersectsSelection(), QTreeViewPrivate::select(), QRectVectorPath::set(), QLayout::setAlignment(), QGraphicsLayout::setContentsMargins(), QGraphicsWidget::setContentsMargins(), QLayout::setContentsMargins(), QWidget::setContentsMargins(), QWidgetPrivate::setFont_helper(), QSplitterPrivate::setGeo(), QGraphicsLinearLayout::setGeometry(), QBoxLayout::setGeometry(), QGraphicsGridLayout::setGeometry(), QPagePreview::setMargins(), QWin32PrintEngine::setProperty(), QRegion::setRects(), QGL2PaintEngineExPrivate::setScissor(), QTableView::setSelection(), QListView::setSelection(), QWidget::setShown(), QLineEdit::setTextMargins(), QBoxLayoutPrivate::setupGeom(), QAbstractScrollArea::setViewportMargins(), QGraphicsProxyWidgetPrivate::setWidget_helper(), QGraphicsWidget::setWindowFrameMargins(), QDockWidgetLayout::sizeFromContent(), QGridLayout::sizeHint(), QGraphicsLinearLayout::sizeHint(), QDockAreaLayoutItem::sizeHint(), QGraphicsAnchorLayout::sizeHint(), QGraphicsGridLayout::sizeHint(), QDockAreaLayout::sizeHint(), QTableView::sizeHintForRow(), QCommonStyle::subControlRect(), QWindowsMobileStyle::subControlRect(), QWindowsCEStyle::subControlRect(), QMacStyle::subControlRect(), QCommonStyle::subElementRect(), QMacStyle::subElementRect(), QBezier::tAtLength(), QTessellator::tessellateConvex(), QAccessibleTabBar::text(), QTableViewPrivate::trimHiddenSelections(), QNetworkDiskCachePrivate::uniqueFileName(), QOpenGLPaintEnginePrivate::updateDepthClip(), QExpandingLineEdit::updateMinimumWidth(), QTreeViewPrivate::AnimatedOperation::updateState(), QRegionPrivate::vectorize(), QTreeModel::view(), QTableView::visualRegionForSelection(), QHeaderView::visualRegionForSelection(), QGraphicsWidget::windowFrameSectionAt(), and QRBTree< T >::Node::~Node().
lowercasebase()
Q_CORE_EXPORT QTextStream& lowercasebase (QTextStream & s) related
Referenced by operator<<().
lowercasedigits()
Q_CORE_EXPORT QTextStream& lowercasedigits (QTextStream & s) related
Referenced by operator<<().
noforcepoint()
Q_CORE_EXPORT QTextStream& noforcepoint (QTextStream & s) related
Referenced by operator<<().
noforcesign()
Q_CORE_EXPORT QTextStream& noforcesign (QTextStream & s) related
Referenced by operator<<().
noshowbase()
Q_CORE_EXPORT QTextStream& noshowbase (QTextStream & s) related
Referenced by operator<<().
oct()
Q_CORE_EXPORT QTextStream& oct (QTextStream & s) related
Referenced by operator<<().
operator<<() [1/2]
QTextStream& operator<< (QTextStream & s, QTextStreamFunction f) inline
Definition at line 291 of file qtextstream.h.
 { return (*f)(s); }
operator<<() [2/2]
QTextStream& operator<< (QTextStream & s, QTextStreamManipulator m) inline
Definition at line 294 of file qtextstream.h.
 { m.exec(s); return s; }
operator>>()
QTextStream& operator>> (QTextStream & s, QTextStreamFunction f) inline
Definition at line 288 of file qtextstream.h.
 { return (*f)(s); }
qSetFieldWidth()
QTextStreamManipulator qSetFieldWidth (int width) related
Definition at line 329 of file qtextstream.h.
Referenced by operator<<().
 {
     QTSMFI func = &QTextStream::setFieldWidth;
     return QTextStreamManipulator(func,width);
 }
qSetPadChar()
QTextStreamManipulator qSetPadChar (QChar ch) related
Definition at line 335 of file qtextstream.h.
 {
     QTSMFC func = &QTextStream::setPadChar;
     return QTextStreamManipulator(func, ch);
 }
qSetRealNumberPrecision()
QTextStreamManipulator qSetRealNumberPrecision (int precision) related
Definition at line 341 of file qtextstream.h.
 {
     QTSMFI func = &QTextStream::setRealNumberPrecision;
     return QTextStreamManipulator(func, precision);
 }
reset()
Q_CORE_EXPORT QTextStream& reset (QTextStream & s) related
Referenced by QMatrix::dy(), QSqlResult::exec(), QTextEngine::FontEngineCache::FontEngineCache(), QImage::fromData(), QWinInputContext::identifierName(), QCoeFepInputContext::identifierName(), QWSInputMethod::mouseHandler(), operator<<(), QPatternist::AutoPtr< NodeBuilder >::operator=(), QDirectFBPointer< IDirectFBSurface >::outPtr(), QIcon::paint(), QConfFileSettingsPrivate::QConfFileSettingsPrivate(), QTransform::QTransform(), QWizardPrivate::QWizardPrivate(), QCacheItem::read(), QMacPinchGestureRecognizer::reset(), QAbstractItemModel::sibling(), QUrl::swap(), QProgressBar::textDirection(), QWSInputMethod::updateHandler(), QPatternist::yyparse(), QAccessibleHierarchyManager::~QAccessibleHierarchyManager(), and QBoolBlocker::~QBoolBlocker().
right()
Q_CORE_EXPORT QTextStream& right (QTextStream & s) related
Referenced by QScript::AST::BinaryExpression::accept0(), QScript::AST::Expression::accept0(), QDeclarativeJS::AST::BinaryExpression::accept0(), QDeclarativeJS::AST::Expression::accept0(), QBezier::addIfClose(), QGL2PEXVertexArray::addQuad(), QGL2PEXVertexArray::addRect(), QTreeViewPrivate::adjustViewOptionsForIndex(), QFontEngineFT::alphaMapBoundingBox(), QDeclarativeItemPrivate::AnchorLines::AnchorLines(), QFontEngineFT::boundingBox(), QTriangulator< T >::ComplexToSimple::calculateIntersection(), QTriangulator< T >::ComplexToSimple::calculateIntersections(), QDeclarativeContents::calcWidth(), QAccessibleLineEdit::characterRect(), QPaintEngineEx::clip(), QScanConverter::clip(), clipLine(), QItemSelectionModel::columnIntersectsSelection(), QTableView::columnMoved(), QFileSystemModelSorter::compareNodes(), QPainterPath::computeBoundingRect(), QLayout::contentsMargins(), QGraphicsLayoutItem::contentsRect(), QLayout::contentsRect(), QAbstractItemModel::decodeData(), QTriangulator< T >::MonotoneToTriangles::decompose(), QBoxLayoutPrivate::deleteAll(), QGridLayoutPrivate::distribute(), QStyleHelper::drawBorderPixmap(), QCommonStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsMobileStyle::drawControl(), QWindowsStyle::drawControl(), QMotifStyle::drawControl(), QOpenGLPaintEnginePrivate::drawFastRect(), QGL2PaintEngineExPrivate::drawPixmapFragments(), QPaintEngineEx::drawRects(), QPaintBufferEngine::drawRects(), QTreeView::drawRow(), QStandardItemModel::dropMimeData(), QTessellatorPrivate::emitEdges(), QTextHtmlExporter::emitMargins(), QGraphicsView::ensureVisible(), QFragmentMapData< QTextBlockData >::erase_single(), QDockWidget::event(), QWSSoundServerPrivate::feedDevice(), fillTrapezoid(), QTextEngine::findItem(), QTextDocumentLayoutPrivate::findY(), QMatrix4x4::frustum(), getFmtString(), QDockAreaLayout::getGrid(), QGridLayoutPrivate::getItemPosition(), QFontEngine::getTrueTypeGlyphIndex(), QFontEngineFT::getUnscaledGlyph(), handleSpans(), QIntersectionFinder::hasIntersections(), QBoxLayout::heightForWidth(), QGridLayoutPrivate::heightForWidth(), QTableModel::index(), QDialogButtonBoxPrivate::initLayout(), QFragmentMapData< QTextBlockData >::insert_single(), QMenu::internalDelayedPopup(), QRegion::intersects(), QDeclarativeItemPrivate::isMirrored(), QByteArray::isSharedWith(), QPatternist::XsdParticleChecker::isUPAConformXsdAll(), QItemSelectionRange::isValid(), QTreeModel::itemChanged(), QDeclarativeJS::AST::BinaryExpression::lastSourceLocation(), QTextDocumentLayoutPrivate::layoutBlock(), QAbstractScrollAreaPrivate::layoutChildren(), QTextDocumentLayoutPrivate::layoutFlow(), QFontEngineFT::loadGlyph(), QMatrix::mapToPolygon(), QTransform::mapToPolygon(), QGridLayout::maximumSize(), QDockAreaLayoutItem::maximumSize(), QStatusBarPrivate::messageRect(), QGridLayout::minimumSize(), QDockAreaLayoutItem::minimumSize(), QDockAreaLayout::minimumSize(), miSubtractO(), QTableView::moveCursor(), QFragmentMapData< QTextBlockData >::next(), operator<<(), QMatrix4x4::ortho(), QDeclarativeBorderImage::paint(), QTableView::paintEvent(), QMaxHeap< QTriangulator::ComplexToSimple::Intersection >::pop(), QTextDocumentLayoutPrivate::positionFloat(), QFragmentMapData< QTextBlockData >::previous(), QMatrix4x4::QMatrix4x4(), QRBTree< int >::QRBTree(), QRenderRule::QRenderRule(), qt_grab_cursor(), qt_painterpath_isect_line_rect(), qt_region_strictContains(), QRasterizer::rasterizeLine(), QFragmentMapData< QTextBlockData >::rebalance(), QGraphicsWidget::rect(), QTriangulator< T >::ComplexToSimple::reorderEdgeListRange(), QPaintEngineExPrivate::replayClipOperations(), QTableWidgetSelectionRange::rightColumn(), QFragmentMapData< QTextBlockData >::rotateRight(), QItemSelectionModel::rowIntersectsSelection(), QTreeViewPrivate::select(), QRectVectorPath::set(), QLayout::setAlignment(), QPainter::setClipRect(), QGraphicsLayout::setContentsMargins(), QGraphicsWidget::setContentsMargins(), QLayout::setContentsMargins(), QWidget::setContentsMargins(), QWidgetPrivate::setFont_helper(), QSplitterPrivate::setGeo(), QGraphicsLinearLayout::setGeometry(), QBoxLayout::setGeometry(), QGraphicsGridLayout::setGeometry(), QPagePreview::setMargins(), QWin32PrintEngine::setProperty(), QRegion::setRects(), QTableView::setSelection(), QListView::setSelection(), QWidget::setShown(), QLineEdit::setTextMargins(), QBoxLayoutPrivate::setupGeom(), QAbstractScrollArea::setViewportMargins(), QGraphicsProxyWidgetPrivate::setWidget_helper(), QGraphicsWidget::setWindowFrameMargins(), QDockWidgetLayout::sizeFromContent(), QGridLayout::sizeHint(), QGraphicsLinearLayout::sizeHint(), QDockAreaLayoutItem::sizeHint(), QGraphicsAnchorLayout::sizeHint(), QGraphicsGridLayout::sizeHint(), QDockAreaLayout::sizeHint(), QTableView::sizeHintForRow(), QCommonStyle::subElementRect(), QMacStyle::subElementRect(), QBezier::tAtLength(), QTessellator::tessellateConvex(), QTableViewPrivate::trimHiddenSelections(), QExpandingLineEdit::updateMinimumWidth(), QTreeViewPrivate::AnimatedOperation::updateState(), QRegionPrivate::vectorize(), QTreeModel::view(), QTableView::visualRegionForSelection(), QHeaderView::visualRegionForSelection(), QGraphicsWidget::windowFrameSectionAt(), and QRBTree< T >::Node::~Node().
scientific()
Q_CORE_EXPORT QTextStream& scientific (QTextStream & s) related
Referenced by operator<<(), and QLocalePrivate::validateChars().
showbase()
Q_CORE_EXPORT QTextStream& showbase (QTextStream & s) related
Referenced by operator<<().
uppercasebase()
Q_CORE_EXPORT QTextStream& uppercasebase (QTextStream & s) related
Referenced by operator<<().
uppercasedigits()
Q_CORE_EXPORT QTextStream& uppercasedigits (QTextStream & s) related
Referenced by operator<<().
ws()
Q_CORE_EXPORT QTextStream& ws (QTextStream & s) related
Referenced by QFontDatabasePrivate::addFont(), QWindowsLocalCodec::convertToUnicodeCharByChar(), QSplitterPrivate::doMove(), effectiveState(), QWorkspaceChild::eventFilter(), QDirectFBScreen::exposeRegion(), findEncoding(), QFontDialogPrivate::init(), initializeDb(), load(), QFontDatabasePrivate::loadFromCache(), QMacPixmapData::macCreatePixels(), QSplitter::moveSplitter(), QPatternist::XQueryTokenizer::nextToken(), operator<<(), QFontconfigDatabase::populateFontDatabase(), QWaylandDisplay::readEvents(), QWidget::restoreGeometry(), QStackedLayout::sizeHint(), QX11PixmapData::transformed(), and QImage::transformed().