Qt 4.8: /src/gui/text/qtextimagehandler.cpp File Reference
qtextimagehandler.cpp File Reference
#include "qtextimagehandler_p.h"
#include <qapplication.h>
#include <qtextformat.h>
#include <qpainter.h>
#include <qdebug.h>
#include <private/qtextengine_p.h>
#include <qpalette.h>
#include <qtextbrowser.h>
#include <qthread.h>
Functions
static QImage getImage (QTextDocument *doc, const QTextImageFormat &format)
static QSize getImageSize (QTextDocument *doc, const QTextImageFormat &format)
static QPixmap getPixmap (QTextDocument *doc, const QTextImageFormat &format)
static QSize getPixmapSize (QTextDocument *doc, const QTextImageFormat &format)
Function Documentation
getImage()
static QImage getImage (QTextDocument * doc, const QTextImageFormat & format) static
Definition at line 136 of file qtextimagehandler.cpp.
Referenced by QTextImageHandler::drawObject(), and getImageSize().
 {
     QImage image;
     QString name = format.name();
     if (name.startsWith(QLatin1String(":/"))) // auto-detect resources
         name.prepend(QLatin1String("qrc"));
     QUrl url = QUrl::fromEncoded(name.toUtf8());
     const QVariant data = doc->resource(QTextDocument::ImageResource, url);
     if (data.type() == QVariant::Image) {
         image = qvariant_cast<QImage>(data);
     } else if (data.type() == QVariant::ByteArray) {
         image.loadFromData(data.toByteArray());
     }
     if (image.isNull()) {
         QString context;
 #ifndef QT_NO_TEXTBROWSER
         QTextBrowser *browser = qobject_cast<QTextBrowser *>(doc->parent());
         if (browser)
             context = browser->source().toString();
 #endif
         if (QTextImageHandler::externalLoader)
             image = QTextImageHandler::externalLoader(name, context);
         if (image.isNull()) { // try direct loading
             name = format.name(); // remove qrc:/ prefix again
             if (name.isEmpty() || !image.load(name))
                 return QImage(QLatin1String(":/trolltech/styles/commonstyle/images/file-16.png"));
         }
         doc->addResource(QTextDocument::ImageResource, url, image);
     }
     return image;
 }
getImageSize()
static QSize getImageSize (QTextDocument * doc, const QTextImageFormat & format) static
Definition at line 172 of file qtextimagehandler.cpp.
Referenced by QTextImageHandler::intrinsicSize().
 {
     QImage image;
     const bool hasWidth = format.hasProperty(QTextFormat::ImageWidth);
     const int width = qRound(format.width());
     const bool hasHeight = format.hasProperty(QTextFormat::ImageHeight);
     const int height = qRound(format.height());
     QSize size(width, height);
     if (!hasWidth || !hasHeight) {
         image = getImage(doc, format);
         if (!hasWidth)
             size.setWidth(image.width());
         if (!hasHeight)
             size.setHeight(image.height());
     }
     qreal scale = 1.0;
     QPaintDevice *pdev = doc->documentLayout()->paintDevice();
     if (pdev) {
         if (image.isNull())
             image = getImage(doc, format);
         if (!image.isNull())
             scale = qreal(pdev->logicalDpiY()) / qreal(qt_defaultDpi());
     }
     size *= scale;
     return size;
 }
getPixmap()
static QPixmap getPixmap (QTextDocument * doc, const QTextImageFormat & format) static
Definition at line 59 of file qtextimagehandler.cpp.
Referenced by QTextImageHandler::drawObject(), and getPixmapSize().
 {
     QPixmap pm;
     QString name = format.name();
     if (name.startsWith(QLatin1String(":/"))) // auto-detect resources
         name.prepend(QLatin1String("qrc"));
     QUrl url = QUrl::fromEncoded(name.toUtf8());
     const QVariant data = doc->resource(QTextDocument::ImageResource, url);
     if (data.type() == QVariant::Pixmap || data.type() == QVariant::Image) {
         pm = qvariant_cast<QPixmap>(data);
     } else if (data.type() == QVariant::ByteArray) {
         pm.loadFromData(data.toByteArray());
     }
     if (pm.isNull()) {
         QString context;
 #ifndef QT_NO_TEXTBROWSER
         QTextBrowser *browser = qobject_cast<QTextBrowser *>(doc->parent());
         if (browser)
             context = browser->source().toString();
 #endif
         QImage img;
         if (QTextImageHandler::externalLoader)
             img = QTextImageHandler::externalLoader(name, context);
         if (img.isNull()) { // try direct loading
             name = format.name(); // remove qrc:/ prefix again
             if (name.isEmpty() || !img.load(name))
                 return QPixmap(QLatin1String(":/trolltech/styles/commonstyle/images/file-16.png"));
         }
         pm = QPixmap::fromImage(img);
         doc->addResource(QTextDocument::ImageResource, url, pm);
     }
     return pm;
 }
getPixmapSize()
static QSize getPixmapSize (QTextDocument * doc, const QTextImageFormat & format) static
Definition at line 97 of file qtextimagehandler.cpp.
Referenced by QTextImageHandler::intrinsicSize().
 {
     QPixmap pm;
     const bool hasWidth = format.hasProperty(QTextFormat::ImageWidth);
     const int width = qRound(format.width());
     const bool hasHeight = format.hasProperty(QTextFormat::ImageHeight);
     const int height = qRound(format.height());
     QSize size(width, height);
     if (!hasWidth || !hasHeight) {
         pm = getPixmap(doc, format);
         if (!hasWidth) {
             if (!hasHeight)
                 size.setWidth(pm.width());
             else
                 size.setWidth(qRound(height * (pm.width() / (qreal) pm.height())));
         }
         if (!hasHeight) {
             if (!hasWidth)
                 size.setHeight(pm.height());
             else
                 size.setHeight(qRound(width * (pm.height() / (qreal) pm.width())));
         }
     }
     qreal scale = 1.0;
     QPaintDevice *pdev = doc->documentLayout()->paintDevice();
     if (pdev) {
         if (pm.isNull())
             pm = getPixmap(doc, format);
         if (!pm.isNull())
             scale = qreal(pdev->logicalDpiY()) / qreal(qt_defaultDpi());
     }
     size *= scale;
     return size;
 }