Qt 4.8: /src/gui/text/qtextdocument.cpp File Reference
qtextdocument.cpp File Reference
#include "qtextdocument.h"
#include <qtextformat.h>
#include "qtextdocumentlayout_p.h"
#include "qtextdocumentfragment.h"
#include "qtextdocumentfragment_p.h"
#include "qtexttable.h"
#include "qtextlist.h"
#include <qdebug.h>
#include <qregexp.h>
#include <qvarlengtharray.h>
#include <qtextcodec.h>
#include <qthread.h>
#include "qtexthtmlparser_p.h"
#include "qpainter.h"
#include "qprinter.h"
#include "qtextedit.h"
#include <qfile.h>
#include <qfileinfo.h>
#include <qdir.h>
#include <qapplication.h>
#include "qtextcontrol_p.h"
#include "qfont_p.h"
#include "private/qtextedit_p.h"
#include "private/qdataurl_p.h"
#include "qtextdocument_p.h"
#include <private/qprinter_p.h>
#include <private/qabstracttextdocumentlayout_p.h>
#include <limits.h>
Functions
static bool findInBlock (const QTextBlock &block, const QRegExp &expression, int offset, QTextDocument::FindFlags options, QTextCursor &cursor)
static QTextFormat formatDifference (const QTextFormat &from, const QTextFormat &to)
static bool isOrderedList (int style)
static void printPage (int index, QPainter *painter, const QTextDocument *doc, const QRectF &body, const QPointF &pageNumberPos)
bool qHasPixmapTexture (const QBrush &brush)
Q_CORE_EXPORT unsigned int qt_int_sqrt (unsigned int n)
Function Documentation
findInBlock()
static bool findInBlock (const QTextBlock & block, const QRegExp & expression, int offset, QTextDocument::FindFlags options, QTextCursor & cursor) static
Definition at line 1448 of file qtextdocument.cpp.
Referenced by QTextDocument::find().
 {
     const QRegExp expr(expression);
     QString text = block.text();
     text.replace(QChar::Nbsp, QLatin1Char(' '));
     int idx = -1;
     while (offset >=0 && offset <= text.length()) {
         idx = (options & QTextDocument::FindBackward) ?
                expr.lastIndexIn(text, offset) : expr.indexIn(text, offset);
         if (idx == -1)
             return false;
         if (options & QTextDocument::FindWholeWords) {
             const int start = idx;
             const int end = start + expr.matchedLength();
             if ((start != 0 && text.at(start - 1).isLetterOrNumber())
                 || (end != text.length() && text.at(end).isLetterOrNumber())) {
                 //if this is not a whole word, continue the search in the string
                 offset = (options & QTextDocument::FindBackward) ? idx-1 : end+1;
                 idx = -1;
                 continue;
             }
         }
         //we have a hit, return the cursor for that.
         break;
     }
     if (idx == -1)
         return false;
     cursor = QTextCursor(block.docHandle(), block.position() + idx);
     cursor.setPosition(cursor.position() + expr.matchedLength(), QTextCursor::KeepAnchor);
     return true;
 }
formatDifference()
static QTextFormat formatDifference (const QTextFormat & from, const QTextFormat & to) static
Definition at line 2209 of file qtextdocument.cpp.
Referenced by QTextHtmlExporter::emitBlock(), and QTextHtmlExporter::emitBlockAttributes().
 {
     QTextFormat diff = to;
     const QMap<int, QVariant> props = to.properties();
     for (QMap<int, QVariant>::ConstIterator it = props.begin(), end = props.end();
          it != end; ++it)
         if (it.value() == from.property(it.key()))
             diff.clearProperty(it.key());
     return diff;
 }
isOrderedList()
static bool isOrderedList (int style) static
Definition at line 2699 of file qtextdocument.cpp.
Referenced by QTextHtmlExporter::emitBlock().
 {
     return style == QTextListFormat::ListDecimal || style == QTextListFormat::ListLowerAlpha
            || style == QTextListFormat::ListUpperAlpha
            || style == QTextListFormat::ListUpperRoman
            || style == QTextListFormat::ListLowerRoman
        ;
 }
printPage()
static void printPage (int index, QPainter * painter, const QTextDocument * doc, const QRectF & body, const QPointF & pageNumberPos) static
Definition at line 1829 of file qtextdocument.cpp.
 {
     painter->save();
     painter->translate(body.left(), body.top() - (index - 1) * body.height());
     QRectF view(0, (index - 1) * body.height(), body.width(), body.height());
     QAbstractTextDocumentLayout *layout = doc->documentLayout();
     QAbstractTextDocumentLayout::PaintContext ctx;
     painter->setClipRect(view);
     ctx.clip = view;
     // don't use the system palette text as default text color, on HP/UX
     // for example that's white, and white text on white paper doesn't
     // look that nice
     ctx.palette.setColor(QPalette::Text, Qt::black);
     layout->draw(painter, ctx);
     if (!pageNumberPos.isNull()) {
         painter->setClipping(false);
         painter->setFont(QFont(doc->defaultFont()));
         const QString pageString = QString::number(index);
         painter->drawText(qRound(pageNumberPos.x() - painter->fontMetrics().width(pageString)),
                           qRound(pageNumberPos.y() + view.top()),
                           pageString);
     }
     painter->restore();
 }
qHasPixmapTexture()
bool qHasPixmapTexture (const QBrush & brush)
Definition at line 223 of file qbrush.cpp.
Referenced by QTextHtmlExporter::emitBackgroundAttribute(), QTextHtmlExporter::emitBlock(), QGL2PaintEngineExPrivate::setBrush(), QSpanData::setup(), and QGL2PaintEngineExPrivate::updateBrushUniforms().
 {
     if (brush.style() != Qt::TexturePattern)
         return false;
     QTexturedBrushData *tx_data = static_cast<QTexturedBrushData *>(brush.d.data());
     return tx_data->m_has_pixmap_texture;
 }
qt_int_sqrt()
Q_CORE_EXPORT unsigned int qt_int_sqrt (unsigned int n)
Definition at line 2478 of file qglobal.cpp.
Referenced by QTextDocument::adjustSize(), and qt_int_sqrt().
 {
     // n must be in the range 0...UINT_MAX/2-1
     if (n >= (UINT_MAX>>2)) {
         unsigned int r = 2 * qt_int_sqrt(n / 4);
         unsigned int r2 = r + 1;
         return (n >= r2 * r2) ? r2 : r;
     }
     uint h, p= 0, q= 1, r= n;
     while (q <= n)
         q <<= 2;
     while (q != 1) {
         q >>= 2;
         h= p + q;
         p >>= 1;
         if (r >= h) {
             p += q;
             r -= h;
         }
     }
     return p;
 }