Qt 4.8: /src/gui/text/qtextdocumentlayout.cpp File Reference
qtextdocumentlayout.cpp File Reference
#include "qtextdocumentlayout_p.h"
#include "qtextdocument_p.h"
#include "qtextimagehandler_p.h"
#include "qtexttable.h"
#include "qtextlist.h"
#include "qtextengine_p.h"
#include "private/qcssutil_p.h"
#include "qabstracttextdocumentlayout_p.h"
#include "qcssparser_p.h"
#include <qpainter.h>
#include <qmath.h>
#include <qrect.h>
#include <qpalette.h>
#include <qdebug.h>
#include <qvarlengtharray.h>
#include <limits.h>
#include <qstyle.h>
#include <qbasictimer.h>
#include "private/qfunctions_p.h"
#include "moc_qtextdocumentlayout_p.cpp"
Classes
struct QCheckPoint
class QTextDocumentLayoutPrivate
class QTextFrameData
struct QTextLayoutStruct
class QTextTableData
Macros
#define DEC_INDENT do {} while(0)
#define INC_INDENT do {} while(0)
#define LDEBUG if(0) qDebug()
Functions
static void adjustContextSelectionsForCell (QAbstractTextDocumentLayout::PaintContext &cell_context, const QTextTableCell &cell, int r, int c, const int *selectedTableCells)
static QTextFrameData * createData (QTextFrame *f)
static QTextFrameData * data (QTextFrame *f)
static void fillBackground (QPainter *p, const QRectF &rect, QBrush brush, const QPointF &origin, QRectF gradientRect=QRectF())
static QFixed firstChildPos (const QTextFrame *f)
static QFixed flowPosition (const QTextFrame::iterator it)
static void getLineHeightParams (const QTextBlockFormat &blockFormat, const QTextLine &line, qreal scaling, QFixed *lineAdjustment, QFixed *lineBreakHeight, QFixed *lineHeight)
static bool isEmptyBlockAfterTable (const QTextBlock &block, const QTextFrame *previousFrame)
static bool isEmptyBlockBeforeTable (const QTextBlock &block, const QTextBlockFormat &format, const QTextFrame::Iterator &nextIt)
static bool isEmptyBlockBeforeTable (QTextFrame::Iterator it)
static bool isFrameFromInlineObject (QTextFrame *f)
static bool isLineSeparatorBlockAfterTable (const QTextBlock &block, const QTextFrame *previousFrame)
static void markFrames (QTextFrame *current, int from, int oldLength, int length)
Q_STATIC_GLOBAL_OPERATOR bool operator< (const QCheckPoint &checkPoint, QFixed y)
Q_STATIC_GLOBAL_OPERATOR bool operator< (const QCheckPoint &checkPoint, int pos)
Q_DECLARE_TYPEINFO (QCheckPoint, Q_PRIMITIVE_TYPE)
Macro Definition Documentation
DEC_INDENT
#define DEC_INDENT do {} while(0)
Definition at line 73 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::hitTest().
INC_INDENT
#define INC_INDENT do {} while(0)
Definition at line 72 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::hitTest().
LDEBUG
#define LDEBUG if(0) qDebug()
Definition at line 71 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutCell(), QTextDocumentLayoutPrivate::layoutFlow(), QTextDocumentLayoutPrivate::layoutFrame(), and QTextDocumentLayoutPrivate::layoutTable().
Function Documentation
adjustContextSelectionsForCell()
static void adjustContextSelectionsForCell (QAbstractTextDocumentLayout::PaintContext & cell_context, const QTextTableCell & cell, int r, int c, const int * selectedTableCells) static
Definition at line 896 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::drawFrame().
 {
     for (int i = 0; i < cell_context.selections.size(); ++i) {
         int row_start = selectedTableCells[i * 4];
         int col_start = selectedTableCells[i * 4 + 1];
         int num_rows = selectedTableCells[i * 4 + 2];
         int num_cols = selectedTableCells[i * 4 + 3];
         if (row_start != -1) {
             if (r >= row_start && r < row_start + num_rows
                 && c >= col_start && c < col_start + num_cols)
             {
                 int firstPosition = cell.firstPosition();
                 int lastPosition = cell.lastPosition();
                 // make sure empty cells are still selected
                 if (firstPosition == lastPosition)
                     ++lastPosition;
                 cell_context.selections[i].cursor.setPosition(firstPosition);
                 cell_context.selections[i].cursor.setPosition(lastPosition, QTextCursor::KeepAnchor);
             } else {
                 cell_context.selections[i].cursor.clearSelection();
             }
         }
         // FullWidthSelection is not useful for tables
         cell_context.selections[i].format.clearProperty(QTextFormat::FullWidthSelection);
     }
 }
createData()
static QTextFrameData* createData (QTextFrame * f) static
Definition at line 237 of file qtextdocumentlayout.cpp.
Referenced by data().
 {
     QTextFrameData *data;
     if (qobject_cast<QTextTable *>(f))
         data = new QTextTableData;
     else
         data = new QTextFrameData;
     f->setLayoutData(data);
     return data;
 }
data()
static QTextFrameData* data (QTextFrame * f) inline static
Definition at line 248 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayout::blockBoundingRect(), createData(), QTextDocumentLayout::doLayout(), QTextDocumentLayout::draw(), QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentLayoutPrivate::drawFrame(), QTextDocumentLayout::dynamicDocumentSize(), QTextDocumentLayoutPrivate::findY(), QTextDocumentLayoutPrivate::floatMargins(), flowPosition(), QTextDocumentLayoutPrivate::frameBoundingRectInternal(), QTextDocumentLayoutPrivate::frameIteratorForYPosition(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentLayoutPrivate::layoutCell(), QTextDocumentLayoutPrivate::layoutFlow(), QTextDocumentLayoutPrivate::layoutFrame(), QTextDocumentLayoutPrivate::layoutTable(), markFrames(), QTextDocumentLayoutPrivate::positionFloat(), and QTextDocumentLayout::resizeInlineObject().
 {
     QTextFrameData *data = static_cast<QTextFrameData *>(f->layoutData());
     if (!data)
         data = createData(f);
     return data;
 }
fillBackground()
static void fillBackground (QPainter * p, const QRectF & rect, QBrush brush, const QPointF & origin, QRectF gradientRect = QRectF()) static
Definition at line 402 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentLayoutPrivate::drawFrameDecoration(), QTextDocumentLayoutPrivate::drawTableCell(), and QGraphicsWidget::paintWindowFrame().
 {
     p->save();
     if (brush.style() >= Qt::LinearGradientPattern && brush.style() <= Qt::ConicalGradientPattern) {
         if (!gradientRect.isNull()) {
             QTransform m;
             m.translate(gradientRect.left(), gradientRect.top());
             m.scale(gradientRect.width(), gradientRect.height());
             brush.setTransform(m);
             const_cast<QGradient *>(brush.gradient())->setCoordinateMode(QGradient::LogicalMode);
         }
     } else {
         p->setBrushOrigin(origin);
     }
     p->fillRect(rect, brush);
     p->restore();
 }
firstChildPos()
static QFixed firstChildPos (const QTextFrame * f) static
Definition at line 1494 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutFlow().
 {
     return flowPosition(f->begin());
 }
flowPosition()
static QFixed flowPosition (const QTextFrame::iterator it) static
Definition at line 1477 of file qtextdocumentlayout.cpp.
Referenced by QIconModeViewBase::doDynamicLayout(), QListModeViewBase::doStaticLayout(), firstChildPos(), and QTextDocumentLayoutPrivate::layoutTable().
 {
     if (it.atEnd())
         return 0;
     if (it.currentFrame()) {
         return data(it.currentFrame())->position.y;
     } else {
         QTextBlock block = it.currentBlock();
         QTextLayout *layout = block.layout();
         if (layout->lineCount() == 0)
             return QFixed::fromReal(layout->position().y());
         else
             return QFixed::fromReal(layout->position().y() + layout->lineAt(0).y());
     }
 }
getLineHeightParams()
static void getLineHeightParams (const QTextBlockFormat & blockFormat, const QTextLine & line, qreal scaling, QFixed * lineAdjustment, QFixed * lineBreakHeight, QFixed * lineHeight) inline static
Definition at line 2520 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutBlock().
 {
     *lineHeight = QFixed::fromReal(blockFormat.lineHeight(line.height(), scaling));
     if (blockFormat.lineHeightType() == QTextBlockFormat::FixedHeight || blockFormat.lineHeightType() == QTextBlockFormat::MinimumHeight) {
         *lineBreakHeight = *lineHeight;
         if (blockFormat.lineHeightType() == QTextBlockFormat::FixedHeight)
             *lineAdjustment = QFixed::fromReal(line.ascent() + qMax(line.leading(), qreal(0.0))) - ((*lineHeight * 4) / 5);
         else
             *lineAdjustment = QFixed::fromReal(line.height()) - *lineHeight;
     }
     else {
         *lineBreakHeight = QFixed::fromReal(line.height());
         *lineAdjustment = 0;
     }
 }
isEmptyBlockAfterTable()
static bool isEmptyBlockAfterTable (const QTextBlock & block, const QTextFrame * previousFrame) inline static
Definition at line 307 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::drawFlow(), and QTextDocumentLayoutPrivate::layoutFlow().
 {
     return qobject_cast<const QTextTable *>(previousFrame)
            && block.isValid()
            && block.length() == 1
            && previousFrame->lastPosition() == block.position() - 1
            ;
 }
isEmptyBlockBeforeTable() [1/2]
static bool isEmptyBlockBeforeTable (const QTextBlock & block, const QTextBlockFormat & format, const QTextFrame::Iterator & nextIt) inline static
Definition at line 286 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::drawFlow(), QTextDocumentLayoutPrivate::hitTest(), isEmptyBlockBeforeTable(), and QTextDocumentLayoutPrivate::layoutFlow().
 {
     return !nextIt.atEnd()
            && qobject_cast<QTextTable *>(nextIt.currentFrame())
            && block.isValid()
            && block.length() == 1
            && !format.hasProperty(QTextFormat::BlockTrailingHorizontalRulerWidth)
            && !format.hasProperty(QTextFormat::BackgroundBrush)
            && nextIt.currentFrame()->firstPosition() == block.position() + 1
            ;
 }
isEmptyBlockBeforeTable() [2/2]
static bool isEmptyBlockBeforeTable (QTextFrame::Iterator it) inline static
Definition at line 298 of file qtextdocumentlayout.cpp.
 {
     QTextFrame::Iterator next = it; ++next;
     if (it.currentFrame())
         return false;
     QTextBlock block = it.currentBlock();
     return isEmptyBlockBeforeTable(block, block.blockFormat(), next);
 }
isFrameFromInlineObject()
static bool isFrameFromInlineObject (QTextFrame * f) static
Definition at line 256 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::drawFlow(), QTextDocumentLayoutPrivate::hitTest(), and QTextDocumentLayoutPrivate::layoutFrame().
 {
     return f->firstPosition() > f->lastPosition();
 }
isLineSeparatorBlockAfterTable()
static bool isLineSeparatorBlockAfterTable (const QTextBlock & block, const QTextFrame * previousFrame) inline static
Definition at line 316 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutFlow().
 {
     return qobject_cast<const QTextTable *>(previousFrame)
            && block.isValid()
            && block.length() > 1
            && block.text().at(0) == QChar::LineSeparator
            && previousFrame->lastPosition() == block.position() - 1
            ;
 }
markFrames()
static void markFrames (QTextFrame * current, int from, int oldLength, int length) static
Definition at line 2847 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayout::doLayout().
 {
     int end = qMax(oldLength, length) + from;
     if (current->firstPosition() >= end || current->lastPosition() < from)
         return;
     QTextFrameData *fd = data(current);
     for (int i = 0; i < fd->floats.size(); ++i) {
         QTextFrame *f = fd->floats[i];
         if (!f) {
             // float got removed in editing operation
             fd->floats.removeAt(i);
             --i;
         }
     }
     fd->layoutDirty = true;
     fd->sizeDirty = true;
 //     qDebug("    marking frame (%d--%d) as dirty", current->firstPosition(), current->lastPosition());
     QList<QTextFrame *> children = current->childFrames();
     for (int i = 0; i < children.size(); ++i)
         markFrames(children.at(i), from, oldLength, length);
 }
operator<() [1/2]
Q_STATIC_GLOBAL_OPERATOR bool operator< (const QCheckPoint & checkPoint, QFixed y)
Definition at line 392 of file qtextdocumentlayout.cpp.
 {
     return checkPoint.y < y;
 }
operator<() [2/2]
Q_STATIC_GLOBAL_OPERATOR bool operator< (const QCheckPoint & checkPoint, int pos)
Definition at line 397 of file qtextdocumentlayout.cpp.
 {
     return checkPoint.positionInFrame < pos;
 }
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QCheckPoint , Q_PRIMITIVE_TYPE)