Qt 4.8: /src/gui/text/qtextodfwriter.cpp File Reference
qtextodfwriter.cpp File Reference
#include <qglobal.h>
#include "qtextodfwriter_p.h"
#include <QImageWriter>
#include <QTextListFormat>
#include <QTextList>
#include <QBuffer>
#include <QUrl>
#include "qtextdocument_p.h"
#include "qtexttable.h"
#include "qtextcursor.h"
#include "qtextimagehandler_p.h"
#include "qzipwriter_p.h"
#include <QDebug>
Classes
class QOutputStrategy
class QXmlStreamStrategy
class QZipStreamStrategy
Functions
static QString bulletChar (QTextListFormat::Style style)
static QString pixelToPoint (qreal pixels)
Convert pixels to postscript point units.
Function Documentation
bulletChar()
static QString bulletChar (QTextListFormat::Style style) static
Definition at line 163 of file qtextodfwriter.cpp.
Referenced by QTextOdfWriter::writeListFormat().
 {
     switch(style) {
     case QTextListFormat::ListDisc:
         return QChar(0x25cf); // bullet character
     case QTextListFormat::ListCircle:
         return QChar(0x25cb); // white circle
     case QTextListFormat::ListSquare:
         return QChar(0x25a1); // white square
     case QTextListFormat::ListDecimal:
         return QString::fromLatin1("1");
     case QTextListFormat::ListLowerAlpha:
         return QString::fromLatin1("a");
     case QTextListFormat::ListUpperAlpha:
         return QString::fromLatin1("A");
     case QTextListFormat::ListLowerRoman:
         return QString::fromLatin1("i");
     case QTextListFormat::ListUpperRoman:
         return QString::fromLatin1("I");
     default:
     case QTextListFormat::ListStyleUndefined:
         return QString();
     }
 }
pixelToPoint()
static QString pixelToPoint (qreal pixels) static
Convert pixels to postscript point units.
Definition at line 65 of file qtextodfwriter.cpp.
Referenced by QTextOdfWriter::writeBlockFormat(), QTextOdfWriter::writeCharacterFormat(), QTextOdfWriter::writeFrameFormat(), QTextOdfWriter::writeInlineCharacter(), and QTextOdfWriter::writeTableCellFormat().
 {
     // we hardcode 96 DPI, we do the same in the ODF importer to have a perfect roundtrip.
     return QString::number(pixels * 72 / 96) + QString::fromLatin1("pt");
 }