Qt 4.8: /src/gui/text/qtextengine_p.h File Reference
qtextengine_p.h File Reference
#include "QtCore/qglobal.h"
#include "QtCore/qstring.h"
#include "QtCore/qvarlengtharray.h"
#include "QtCore/qnamespace.h"
#include "QtGui/qtextlayout.h"
#include "private/qtextformat_p.h"
#include "private/qfont_p.h"
#include "QtCore/qvector.h"
#include "QtGui/qpaintengine.h"
#include "QtGui/qtextobject.h"
#include "QtGui/qtextoption.h"
#include "QtGui/qtextcursor.h"
#include "QtCore/qset.h"
#include "QtCore/qdebug.h"
#include "private/qtextdocument_p.h"
#include "private/qharfbuzz_p.h"
#include "private/qfixed_p.h"
#include <stdlib.h>
Classes
struct glyph_metrics_t
struct QGlyphJustification
struct QGlyphLayout
struct QGlyphLayoutArray< N >
struct QGlyphLayoutInstance
struct QScriptAnalysis
struct QScriptItem
struct QScriptLine
class QStackTextEngine
class QTextEngine
struct QTextEngine::FontEngineCache
struct QTextEngine::LayoutData
struct QTextEngine::SpecialData
class QTextItemInt
Internal QTextItem.
struct QTextLineItemIterator
class QVarLengthGlyphLayoutArray
Typedefs
typedef QVector< QScriptItem > QScriptItemArray
typedef QVector< QScriptLine > QScriptLineArray
Functions
Q_DECLARE_TYPEINFO (glyph_metrics_t, Q_PRIMITIVE_TYPE)
Q_DECLARE_TYPEINFO (QScriptAnalysis, Q_PRIMITIVE_TYPE)
Q_DECLARE_TYPEINFO (QGlyphJustification, Q_PRIMITIVE_TYPE)
Q_DECLARE_TYPEINFO (QScriptItem, Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO (QScriptLine, Q_PRIMITIVE_TYPE)
bool qIsControlChar (ushort uc)
Typedef Documentation
QScriptItemArray
typedef QVector<QScriptItem> QScriptItemArray
Definition at line 373 of file qtextengine_p.h.
QScriptLineArray
typedef QVector<QScriptLine> QScriptLineArray
Definition at line 416 of file qtextengine_p.h.
Function Documentation
Q_DECLARE_TYPEINFO() [1/5]
Q_DECLARE_TYPEINFO (glyph_metrics_t , Q_PRIMITIVE_TYPE)
Referenced by QScriptLine::base(), QScriptItem::height(), glyph_metrics_t::isValid(), and QScriptAnalysis::operator==().
Q_DECLARE_TYPEINFO() [2/5]
Q_DECLARE_TYPEINFO (QScriptAnalysis , Q_PRIMITIVE_TYPE)
Q_DECLARE_TYPEINFO() [3/5]
Q_DECLARE_TYPEINFO (QGlyphJustification , Q_PRIMITIVE_TYPE)
Q_DECLARE_TYPEINFO() [4/5]
Q_DECLARE_TYPEINFO (QScriptItem , Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO() [5/5]
Q_DECLARE_TYPEINFO (QScriptLine , Q_PRIMITIVE_TYPE)
qIsControlChar()
bool qIsControlChar (ushort uc) inline
Definition at line 340 of file qtextengine_p.h.
Referenced by heuristicSetGlyphAttributes().
 {
     return uc >= 0x200b && uc <= 0x206f
         && (uc <= 0x200f /* ZW Space, ZWNJ, ZWJ, LRM and RLM */
             || (uc >= 0x2028 && uc <= 0x202f /* LS, PS, LRE, RLE, PDF, LRO, RLO, NNBSP */)
             || uc >= 0x206a /* ISS, ASS, IAFS, AFS, NADS, NODS */);
 }