Qt 4.8: /src/gui/text/qtextlayout.cpp File Reference
qtextlayout.cpp File Reference
#include "qtextlayout.h"
#include "qtextengine_p.h"
#include <qfont.h>
#include <qapplication.h>
#include <qmath.h>
#include <qpainter.h>
#include <qvarlengtharray.h>
#include <qtextformat.h>
#include <qabstracttextdocumentlayout.h>
#include "qtextdocument_p.h"
#include "qtextformat_p.h"
#include "qstyleoption.h"
#include "qpainterpath.h"
#include "qglyphrun.h"
#include "qglyphrun_p.h"
#include "qrawfont.h"
#include "qrawfont_p.h"
#include <limits.h>
#include <qdebug.h>
#include "qfontengine_p.h"
#include "qfontengine_ft_p.h"
Macros
#define LB_DEBUG if (0) qDebug
#define ObjectSelectionBrush (QTextFormat::ForegroundBrush + 1)
#define SuppressBackground 0x513
#define SuppressText 0x5012
Functions
static void addNextCluster (int &pos, int end, QScriptLine &line, int &glyphCount, const QScriptItem &current, const unsigned short *logClusters, const QGlyphLayout &glyphs)
static void addSelectedRegionsToPath (QTextEngine *eng, int lineNumber, const QPointF &pos, QTextLayout::FormatRange *selection, QPainterPath *region, QRectF boundingRect)
static QRectF clipIfValid (const QRectF &rect, const QRectF &clip)
static void drawMenuText (QPainter *p, QFixed x, QFixed y, const QScriptItem &si, QTextItemInt &gf, QTextEngine *eng, int start, int glyph_start)
static void setPenAndDrawBackground (QPainter *p, const QPen &defaultPen, const QTextCharFormat &chf, const QRectF &r)
Macro Definition Documentation
LB_DEBUG
#define LB_DEBUG if (0) qDebug
Definition at line 1639 of file qtextlayout.cpp.
Referenced by QTextLine::layout_helper().
ObjectSelectionBrush
#define ObjectSelectionBrush (QTextFormat::ForegroundBrush + 1)
Definition at line 72 of file qtextlayout.cpp.
Referenced by QTextLayout::draw(), and QTextLine::draw().
SuppressBackground
#define SuppressBackground 0x513
Definition at line 74 of file qtextlayout.cpp.
Referenced by QTextLayout::draw(), and setPenAndDrawBackground().
SuppressText
#define SuppressText 0x5012
Definition at line 73 of file qtextlayout.cpp.
Referenced by QTextLayout::draw(), and QTextLine::draw().
Function Documentation
addNextCluster()
static void addNextCluster (int & pos, int end, QScriptLine & line, int & glyphCount, const QScriptItem & current, const unsigned short * logClusters, const QGlyphLayout & glyphs) inline static
Definition at line 1760 of file qtextlayout.cpp.
Referenced by QTextLine::layout_helper().
 {
     int glyphPosition = logClusters[pos];
     do { // got to the first next cluster
         ++pos;
         ++line.length;
     } while (pos < end && logClusters[pos] == glyphPosition);
     do { // calculate the textWidth for the rest of the current cluster.
         if (!glyphs.attributes[glyphPosition].dontPrint)
             line.textWidth += glyphs.advances_x[glyphPosition];
         ++glyphPosition;
     } while (glyphPosition < current.num_glyphs && !glyphs.attributes[glyphPosition].clusterStart);
     Q_ASSERT((pos == end && glyphPosition == current.num_glyphs) || logClusters[pos] == glyphPosition);
     ++glyphCount;
 }
addSelectedRegionsToPath()
static void addSelectedRegionsToPath (QTextEngine * eng, int lineNumber, const QPointF & pos, QTextLayout::FormatRange * selection, QPainterPath * region, QRectF boundingRect) static
Definition at line 1000 of file qtextlayout.cpp.
Referenced by QTextLayout::draw().
 {
     const QScriptLine &line = eng->lines[lineNumber];
     QTextLineItemIterator iterator(eng, lineNumber, pos, selection);
     const qreal selectionY = pos.y() + line.y.toReal();
     const qreal lineHeight = line.height().toReal();
     QFixed lastSelectionX = iterator.x;
     QFixed lastSelectionWidth;
     while (!iterator.atEnd()) {
         iterator.next();
         QFixed selectionX, selectionWidth;
         if (iterator.getSelectionBounds(&selectionX, &selectionWidth)) {
             if (selectionX == lastSelectionX + lastSelectionWidth) {
                 lastSelectionWidth += selectionWidth;
                 continue;
             }
             if (lastSelectionWidth > 0) {
                 QRectF rect = boundingRect & QRectF(lastSelectionX.toReal(), selectionY, lastSelectionWidth.toReal(), lineHeight);
                 rect.moveLeft(qFloor(rect.left()));
                 rect.moveTop(qFloor(rect.top()));
                 region->addRect(rect);
             }
             lastSelectionX = selectionX;
             lastSelectionWidth = selectionWidth;
         }
     }
     if (lastSelectionWidth > 0) {
         QRectF rect = boundingRect & QRectF(lastSelectionX.toReal(), selectionY, lastSelectionWidth.toReal(), lineHeight);
         rect.moveLeft(qFloor(rect.left()));
         rect.moveTop(qFloor(rect.top()));
         region->addRect(rect);
     }
 }
clipIfValid()
static QRectF clipIfValid (const QRectF & rect, const QRectF & clip) inline static
Definition at line 1044 of file qtextlayout.cpp.
Referenced by QTextLayout::draw().
 {
     return clip.isValid() ? (rect & clip) : rect;
 }
drawMenuText()
static void drawMenuText (QPainter * p, QFixed x, QFixed y, const QScriptItem & si, QTextItemInt & gf, QTextEngine * eng, int start, int glyph_start) static
Definition at line 2077 of file qtextlayout.cpp.
Referenced by QTextLine::draw().
 {
     int ge = glyph_start + gf.glyphs.numGlyphs;
     int gs = glyph_start;
     int end = start + gf.num_chars;
     unsigned short *logClusters = eng->logClusters(&si);
     QGlyphLayout glyphs = eng->shapedGlyphs(&si);
     QFixed orig_width = gf.width;
     int *ul = eng->underlinePositions;
     if (ul)
         while (*ul != -1 && *ul < start)
             ++ul;
     bool rtl = si.analysis.bidiLevel % 2;
     if (rtl)
         x += si.width;
     do {
         int gtmp = ge;
         int stmp = end;
         if (ul && *ul != -1 && *ul < end) {
             stmp = *ul;
             gtmp = logClusters[*ul-si.position];
         }
         gf.glyphs = glyphs.mid(gs, gtmp - gs);
         gf.num_chars = stmp - start;
         gf.chars = eng->layoutData->string.unicode() + start;
         QFixed w = 0;
         while (gs < gtmp) {
             w += glyphs.effectiveAdvance(gs);
             ++gs;
         }
         start = stmp;
         gf.width = w;
         if (rtl)
             x -= w;
         if (gf.num_chars)
             p->drawTextItem(QPointF(x.toReal(), y.toReal()), gf);
         if (!rtl)
             x += w;
         if (ul && *ul != -1 && *ul < end) {
             // draw underline
             gtmp = (*ul == end-1) ? ge : logClusters[*ul+1-si.position];
             ++stmp;
             gf.glyphs = glyphs.mid(gs, gtmp - gs);
             gf.num_chars = stmp - start;
             gf.chars = eng->layoutData->string.unicode() + start;
             gf.logClusters = logClusters + start - si.position;
             w = 0;
             while (gs < gtmp) {
                 w += glyphs.effectiveAdvance(gs);
                 ++gs;
             }
             ++start;
             gf.width = w;
             gf.underlineStyle = QTextCharFormat::SingleUnderline;
             if (rtl)
                 x -= w;
             p->drawTextItem(QPointF(x.toReal(), y.toReal()), gf);
             if (!rtl)
                 x += w;
             gf.underlineStyle = QTextCharFormat::NoUnderline;
             ++gf.chars;
             ++ul;
         }
     } while (gs < ge);
     gf.width = orig_width;
 }
setPenAndDrawBackground()
static void setPenAndDrawBackground (QPainter * p, const QPen & defaultPen, const QTextCharFormat & chf, const QRectF & r) static
Definition at line 2150 of file qtextlayout.cpp.
Referenced by QTextLine::draw().
 {
     QBrush c = chf.foreground();
     if (c.style() == Qt::NoBrush) {
         p->setPen(defaultPen);
     }
     QBrush bg = chf.background();
     if (bg.style() != Qt::NoBrush && !chf.property(SuppressBackground).toBool())
         p->fillRect(QRectF(qFloor(r.x()), qFloor(r.y()), r.width(), r.height()), bg);
     if (c.style() != Qt::NoBrush) {
         p->setPen(QPen(c, 0));
     }
 }