Qt 4.8: /src/gui/text/qtextengine_mac.cpp File Reference
qtextengine_mac.cpp File Reference
#include "qtextengine_p.h"
#include <private/qfontengine_coretext_p.h>
#include <private/qfontengine_mac_p.h>
Classes
struct JoiningPair
struct QArabicProperties
Enumerations
enum ArabicGroup {
ArabicNone, ArabicSpace, Transparent, Center,
Kashida, Beh, Noon, Meem = Noon,
Heh = Noon, KnottedHeh = Noon, HehGoal = Noon, SwashKaf = Noon,
Yeh, Hah, Seen, Sad = Seen,
Tah, Kaf = Tah, Gaf = Tah, Lam = Tah,
Ain, Feh = Ain, Qaf = Ain, Alef,
Waw, Dal, TehMarbuta = Dal, Reh,
HamzaOnHehGoal, YehWithTail = HamzaOnHehGoal, YehBarre = HamzaOnHehGoal, Beth = Beh,
Gamal = Ain, Heth = Noon, Teth = Hah, Yudh = Noon,
Kaph = Noon, Lamadh = Lam, Mim = Noon, Nun = Noon,
Semakh = Noon, FinalSemakh = Noon, SyriacE = Ain, Pe = Ain,
ReversedPe = Hah, Qaph = Noon, Shin = Noon, Fe = Ain,
Alaph = Alef, Dalath = Dal, He = Dal, SyriacWaw = Waw,
Zain = Alef, YudhHe = Waw, Sadhe = HamzaOnHehGoal, Taw = Dal,
Dummy = HamzaOnHehGoal, ArabicGroupsEnd
}
enum Joining {
JNone, JCausing, JDual, JRight,
JTransparent
}
enum QArabicShape {
XIsolated, XFinal, XInitial, XMedial,
XCausing
}
Functions
static ArabicGroup arabicGroup (unsigned short uc)
static void heuristicSetGlyphAttributes (const QChar *uc, int length, QGlyphLayout *glyphs, unsigned short *logClusters, int num_glyphs)
Q_DECLARE_TYPEINFO (QArabicProperties, Q_PRIMITIVE_TYPE)
void qt_getArabicProperties (const unsigned short *chars, int len, QArabicProperties *properties)
Variables
static const unsigned char arabic_group [0x150]
static const Joining joining_for_group [ArabicGroupsEnd]
static const JoiningPair joining_table [5][4]
Enumeration Type Documentation
ArabicGroup
enum ArabicGroup
Enumerator
ArabicNone
ArabicSpace
Transparent
Center
Kashida
Beh
Noon
Meem
Heh
KnottedHeh
HehGoal
SwashKaf
Yeh
Hah
Seen
Sad
Tah
Kaf
Gaf
Lam
Ain
Feh
Qaf
Alef
Waw
Dal
TehMarbuta
Reh
HamzaOnHehGoal
YehWithTail
YehBarre
Beth
Gamal
Heth
Teth
Yudh
Kaph
Lamadh
Mim
Nun
Semakh
FinalSemakh
SyriacE
Pe
ReversedPe
Qaph
Shin
Fe
Alaph
Dalath
He
SyriacWaw
Zain
YudhHe
Sadhe
Taw
Dummy
ArabicGroupsEnd
Definition at line 122 of file qtextengine_mac.cpp.
                  {
     // NonJoining
     ArabicNone,
     ArabicSpace,
     // Transparent
     Transparent,
     // Causing
     Center,
     Kashida,
     // Arabic
     // Dual
     Beh,
     Noon,
     Meem = Noon,
     Heh = Noon,
     KnottedHeh = Noon,
     HehGoal = Noon,
     SwashKaf = Noon,
     Yeh,
     Hah,
     Seen,
     Sad = Seen,
     Tah,
     Kaf = Tah,
     Gaf = Tah,
     Lam = Tah,
     Ain,
     Feh = Ain,
     Qaf = Ain,
     // Right
     Alef,
     Waw,
     Dal,
     TehMarbuta = Dal,
     Reh,
     HamzaOnHehGoal,
     YehWithTail = HamzaOnHehGoal,
     YehBarre = HamzaOnHehGoal,
     // Syriac
     // Dual
     Beth = Beh,
     Gamal = Ain,
     Heth = Noon,
     Teth = Hah,
     Yudh = Noon,
     Kaph = Noon,
     Lamadh = Lam,
     Mim = Noon,
     Nun = Noon,
     Semakh = Noon,
     FinalSemakh = Noon,
     SyriacE = Ain,
     Pe = Ain,
     ReversedPe = Hah,
     Qaph = Noon,
     Shin = Noon,
     Fe = Ain,
     // Right
     Alaph = Alef,
     Dalath = Dal,
     He = Dal,
     SyriacWaw = Waw,
     Zain = Alef,
     YudhHe = Waw,
     Sadhe = HamzaOnHehGoal,
     Taw = Dal,
     // Compiler bug? Otherwise ArabicGroupsEnd would be equal to Dal + 1.
     Dummy = HamzaOnHehGoal,
     ArabicGroupsEnd
 };
Joining
enum Joining
Enumerator
JNone
JCausing
JDual
JRight
JTransparent
Definition at line 354 of file qtextengine_mac.cpp.
              {
     JNone,
     JCausing,
     JDual,
     JRight,
     JTransparent
 };
QArabicShape
enum QArabicShape
Enumerator
XIsolated
XFinal
XInitial
XMedial
XCausing
Definition at line 106 of file qtextengine_mac.cpp.
                   {
     XIsolated,
     XFinal,
     XInitial,
     XMedial,
     // intermediate state
     XCausing
 };
Function Documentation
arabicGroup()
static ArabicGroup arabicGroup (unsigned short uc) inline static
Definition at line 308 of file qtextengine_mac.cpp.
Referenced by qt_getArabicProperties().
 {
     if (uc >= 0x0600 && uc < 0x750)
         return (ArabicGroup) arabic_group[uc-0x600];
     else if (uc == 0x200d)
         return Center;
     else if (QChar::category(uc) == QChar::Separator_Space)
         return ArabicSpace;
     else
         return ArabicNone;
 }
heuristicSetGlyphAttributes()
static void heuristicSetGlyphAttributes (const QChar * uc, int length, QGlyphLayout * glyphs, unsigned short * logClusters, int num_glyphs) static
Definition at line 52 of file qtextengine_mac.cpp.
Referenced by QTextEngine::shapeTextMac().
 {
     // ### zeroWidth and justification are missing here!!!!!
     Q_UNUSED(num_glyphs);
 //     qDebug("QScriptEngine::heuristicSetGlyphAttributes, num_glyphs=%d", item->num_glyphs);
     const bool symbolFont = false; // ####
     glyphs->attributes[0].mark = false;
     glyphs->attributes[0].clusterStart = true;
     glyphs->attributes[0].dontPrint = (!symbolFont && uc[0].unicode() == 0x00ad) || qIsControlChar(uc[0].unicode());
     int pos = 0;
     int lastCat = QChar::category(uc[0].unicode());
     for (int i = 1; i < length; ++i) {
         if (logClusters[i] == pos)
             // same glyph
             continue;
         ++pos;
         while (pos < logClusters[i]) {
             ++pos;
         }
         // hide soft-hyphens by default
         if ((!symbolFont && uc[i].unicode() == 0x00ad) || qIsControlChar(uc[i].unicode()))
             glyphs->attributes[pos].dontPrint = true;
         const QUnicodeTables::Properties *prop = QUnicodeTables::properties(uc[i].unicode());
         int cat = prop->category;
         // one gets an inter character justification point if the current char is not a non spacing mark.
         // as then the current char belongs to the last one and one gets a space justification point
         // after the space char.
         if (lastCat == QChar::Separator_Space)
             glyphs->attributes[pos-1].justification = HB_Space;
         else if (cat != QChar::Mark_NonSpacing)
             glyphs->attributes[pos-1].justification = HB_Character;
         else
             glyphs->attributes[pos-1].justification = HB_NoJustification;
         lastCat = cat;
     }
     pos = logClusters[length-1];
     if (lastCat == QChar::Separator_Space)
         glyphs->attributes[pos].justification = HB_Space;
     else
         glyphs->attributes[pos].justification = HB_Character;
 }
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QArabicProperties , Q_PRIMITIVE_TYPE)
qt_getArabicProperties()
void qt_getArabicProperties (const unsigned short * chars, int len, QArabicProperties * properties)
Definition at line 446 of file qtextengine_mac.cpp.
Referenced by QTextEngine::shapeTextMac().
 {
 //     qDebug("arabicSyriacOpenTypeShape: properties:");
     int lastPos = 0;
     int lastGroup = ArabicNone;
     ArabicGroup group = arabicGroup(chars[0]);
     Joining j = joining_for_group[group];
     QArabicShape shape = joining_table[XIsolated][j].form2;
     properties[0].justification = HB_NoJustification;
     for (int i = 1; i < len; ++i) {
         // #### fix handling for spaces and punktuation
         properties[i].justification = HB_NoJustification;
         group = arabicGroup(chars[i]);
         j = joining_for_group[group];
         if (j == JTransparent) {
             properties[i].shape = XIsolated;
             continue;
         }
         properties[lastPos].shape = joining_table[shape][j].form1;
         shape = joining_table[shape][j].form2;
         switch(lastGroup) {
         case Seen:
             if (properties[lastPos].shape == XInitial || properties[lastPos].shape == XMedial)
                 properties[i-1].justification = HB_Arabic_Seen;
             break;
         case Hah:
             if (properties[lastPos].shape == XFinal)
                 properties[lastPos-1].justification = HB_Arabic_HaaDal;
             break;
         case Alef:
             if (properties[lastPos].shape == XFinal)
                 properties[lastPos-1].justification = HB_Arabic_Alef;
             break;
         case Ain:
             if (properties[lastPos].shape == XFinal)
                 properties[lastPos-1].justification = HB_Arabic_Waw;
             break;
         case Noon:
             if (properties[lastPos].shape == XFinal)
                 properties[lastPos-1].justification = HB_Arabic_Normal;
             break;
         case ArabicNone:
             break;
         default:
             Q_ASSERT(false);
         }
         lastGroup = ArabicNone;
         switch(group) {
         case ArabicNone:
         case Transparent:
         // ### Center should probably be treated as transparent when it comes to justification.
         case Center:
             break;
         case ArabicSpace:
             properties[i].justification = HB_Arabic_Space;
             break;
         case Kashida:
             properties[i].justification = HB_Arabic_Kashida;
             break;
         case Seen:
             lastGroup = Seen;
             break;
         case Hah:
         case Dal:
             lastGroup = Hah;
             break;
         case Alef:
         case Tah:
             lastGroup = Alef;
             break;
         case Yeh:
         case Reh:
             if (properties[lastPos].shape == XMedial && arabicGroup(chars[lastPos]) == Beh)
                 properties[lastPos-1].justification = HB_Arabic_BaRa;
             break;
         case Ain:
         case Waw:
             lastGroup = Ain;
             break;
         case Noon:
         case Beh:
         case HamzaOnHehGoal:
             lastGroup = Noon;
             break;
         case ArabicGroupsEnd:
             Q_ASSERT(false);
         }
         lastPos = i;
     }
     properties[lastPos].shape = joining_table[shape][JNone].form1;
 //     for (int i = 0; i < len; ++i)
 //         qDebug("arabic properties(%d): uc=%x shape=%d, justification=%d", i, chars[i], properties[i].shape, properties[i].justification);
 }
Variable Documentation
arabic_group
const unsigned char arabic_group[0x150] static
Definition at line 197 of file qtextengine_mac.cpp.
Referenced by arabicGroup().
joining_for_group
const Joining joining_for_group[ArabicGroupsEnd] static
Initial value:
= {
    JNone,
    JNone,
    JTransparent,
    JCausing,
    JCausing,
    JDual,
    JDual,
    JDual,
    JDual,
    JDual,
    JDual,
    JDual,
    JRight,
    JRight,
    JRight,
    JRight,
    JRight
}
Definition at line 362 of file qtextengine_mac.cpp.
Referenced by qt_getArabicProperties().
joining_table
const JoiningPair joining_table[5][4] static
Initial value:
=
{
    { { XIsolated, XIsolated }, { XIsolated, XCausing }, { XIsolated, XInitial }, { XIsolated, XIsolated } },
    { { XFinal, XIsolated }, { XFinal, XCausing }, { XFinal, XInitial }, { XFinal, XIsolated } },
    { { XIsolated, XIsolated }, { XInitial, XCausing }, { XInitial, XMedial }, { XInitial, XFinal } },
    { { XFinal, XIsolated }, { XMedial, XCausing }, { XMedial, XMedial }, { XMedial, XFinal } },
    { { XIsolated, XIsolated }, { XIsolated, XCausing }, { XIsolated, XMedial }, { XIsolated, XFinal } },
}
Definition at line 393 of file qtextengine_mac.cpp.