Qt 4.8: /src/gui/text/qtextformat.cpp File Reference
qtextformat.cpp File Reference
#include "qtextformat.h"
#include "qtextformat_p.h"
#include <qvariant.h>
#include <qdatastream.h>
#include <qdebug.h>
#include <qmap.h>
#include <qhash.h>
Classes
class QTextFormatPrivate
struct QTextFormatPrivate::Property
Functions
static int getHash (const QTextFormatPrivate *d, int format)
static uint hash (float d)
static uint hash (const QColor &color)
static uint hash (const QPen &pen)
static uint hash (const QBrush &brush)
QDataStream & operator<< (QDataStream &stream, const QTextLength &length)
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &stream, const QTextFormat &fmt)
QDataStream & operator>> (QDataStream &stream, QTextLength &length)
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &stream, QTextFormat &fmt)
static uint variantHash (const QVariant &variant)
Function Documentation
getHash()
static int getHash (const QTextFormatPrivate * d, int format) inline static
Definition at line 347 of file qtextformat.cpp.
Referenced by QTextFormatCollection::hasFormatCached(), and QTextFormatCollection::indexForFormat().
 {
     return (d ? d->hash() : 0) + format;
 }
hash() [1/4]
static uint hash (float d) inline static
Definition at line 296 of file qtextformat.cpp.
Referenced by QTextFormatCollection::hasFormatCached(), and QTextFormatCollection::indexForFormat().
 {
 #ifdef Q_CC_GNU
     // this is a GCC extension and isn't guaranteed to work in other compilers
     // the reinterpret_cast below generates a strict-aliasing warning with GCC
     union { float f; uint u; } cvt;
     cvt.f = d;
     return cvt.u;
 #else
     return reinterpret_cast<uint&>(d);
 #endif
 }
hash() [2/4]
static uint hash (const QColor & color) inline static
Definition at line 309 of file qtextformat.cpp.
 {
     return (color.isValid()) ? color.rgba() : 0x234109;
 }
hash() [3/4]
static uint hash (const QPen & pen) inline static
Definition at line 314 of file qtextformat.cpp.
 {
     return hash(pen.color()) + hash(pen.widthF());
 }
hash() [4/4]
static uint hash (const QBrush & brush) inline static
Definition at line 319 of file qtextformat.cpp.
 {
     return hash(brush.color()) + (brush.style() << 3);
 }
operator<<() [1/2]
QDataStream& operator<< (QDataStream & stream, const QTextLength & length)
Definition at line 179 of file qtextformat.cpp.
 {
     return stream << qint32(length.lengthType) << double(length.fixedValueOrPercentage);
 }
operator<<() [2/2]
Q_GUI_EXPORT QDataStream& operator<< (QDataStream & stream, const QTextFormat & fmt)
Definition at line 459 of file qtextformat.cpp.
 {
     stream << fmt.format_type << fmt.properties();
     return stream;
 }
operator>>() [1/2]
QDataStream& operator>> (QDataStream & stream, QTextLength & length)
Definition at line 184 of file qtextformat.cpp.
 {
     qint32 type;
     double fixedValueOrPercentage;
     stream >> type >> fixedValueOrPercentage;
     length.fixedValueOrPercentage = fixedValueOrPercentage;
     length.lengthType = QTextLength::Type(type);
     return stream;
 }
operator>>() [2/2]
Q_GUI_EXPORT QDataStream& operator>> (QDataStream & stream, QTextFormat & fmt)
Definition at line 465 of file qtextformat.cpp.
 {
     QMap<qint32, QVariant> properties;
     stream >> fmt.format_type >> properties;
     // QTextFormat's default constructor doesn't allocate the private structure, so
     // we have to do this, in case fmt is a default constructed value.
     if(!fmt.d)
         fmt.d = new QTextFormatPrivate();
     for (QMap<qint32, QVariant>::ConstIterator it = properties.constBegin();
          it != properties.constEnd(); ++it)
         fmt.d->insertProperty(it.key(), it.value());
     return stream;
 }
variantHash()
static uint variantHash (const QVariant & variant) inline static
Definition at line 324 of file qtextformat.cpp.
Referenced by QTextFormatPrivate::recalcHash().
 {
     // simple and fast hash functions to differentiate between type and value
     switch (variant.userType()) { // sorted by occurrence frequency
     case QVariant::String: return qHash(variant.toString());
     case QVariant::Double: return hash(variant.toDouble());
     case QVariant::Int: return 0x811890 + variant.toInt();
     case QVariant::Brush:
         return 0x01010101 + hash(qvariant_cast<QBrush>(variant));
     case QVariant::Bool: return 0x371818 + variant.toBool();
     case QVariant::Pen: return 0x02020202 + hash(qvariant_cast<QPen>(variant));
     case QVariant::List:
         return 0x8377 + qvariant_cast<QVariantList>(variant).count();
     case QVariant::Color: return hash(qvariant_cast<QColor>(variant));
       case QVariant::TextLength:
         return 0x377 + hash(qvariant_cast<QTextLength>(variant).rawValue());
     case QMetaType::Float: return hash(variant.toFloat());
     case QVariant::Invalid: return 0;
     default: break;
     }
     return qHash(variant.typeName());
 }