Qt 4.8: /src/gui/text/qtextdocument_p.cpp File Reference
qtextdocument_p.cpp File Reference
#include <private/qtools_p.h>
#include <qdebug.h>
#include "qtextdocument_p.h"
#include "qtextdocument.h"
#include <qtextformat.h>
#include "qtextformat_p.h"
#include "qtextobject_p.h"
#include "qtextcursor.h"
#include "qtextimagehandler_p.h"
#include "qtextcursor_p.h"
#include "qtextdocumentlayout_p.h"
#include "qtexttable.h"
#include "qtextengine_p.h"
#include <stdlib.h>
Macros
#define PMDEBUG if(0) qDebug
#define QT_INIT_TEXTUNDOCOMMAND(c, a1, a2, a3, a4, a5, a6, a7, a8) QTextUndoCommand c = { a1, a2, 0, 0, quint8(a3), a4, quint32(a5), quint32(a6), { int(a7) }, quint32(a8) }
Functions
static QTextFrame * findChildFrame (QTextFrame *f, int pos)
static bool isAncestorFrame (QTextFrame *possibleAncestor, QTextFrame *child)
static bool isValidBlockSeparator (const QChar &ch)
static bool noBlockInString (const QString &str)
Macro Definition Documentation
PMDEBUG
#define PMDEBUG if(0) qDebug
Definition at line 61 of file qtextdocument_p.cpp.
Referenced by QTextDocumentPrivate::appendUndoItem(), and QTextDocumentPrivate::undoRedo().
QT_INIT_TEXTUNDOCOMMAND
#define QT_INIT_TEXTUNDOCOMMAND (c, a1, a2, a3, a4, a5, a6, a7, a8) QTextUndoCommand c = { a1, a2, 0, 0, quint8(a3), a4, quint32(a5), quint32(a6), { int(a7) }, quint32(a8) }
Definition at line 65 of file qtextdocument_p.cpp.
Referenced by QTextDocumentPrivate::appendUndoItem(), QTextDocumentPrivate::changeObjectFormat(), QTextDocumentPrivate::insert(), QTextDocumentPrivate::insertBlock(), QTextDocumentPrivate::move(), QTextDocumentPrivate::setBlockFormat(), and QTextDocumentPrivate::setCharFormat().
Function Documentation
findChildFrame()
static QTextFrame* findChildFrame (QTextFrame * f, int pos) static
Definition at line 1423 of file qtextdocument_p.cpp.
Referenced by QTextDocumentPrivate::frameAt().
 {
     /* Binary search for frame at pos */
     const QList<QTextFrame *> children = f->childFrames();
     int first = 0;
     int last = children.size() - 1;
     while (first <= last) {
         int mid = (first + last) / 2;
         QTextFrame *c = children.at(mid);
         if (pos > c->lastPosition())
             first = mid + 1;
         else if (pos < c->firstPosition())
             last = mid - 1;
         else
             return c;
     }
     return 0;
 }
isAncestorFrame()
static bool isAncestorFrame (QTextFrame * possibleAncestor, QTextFrame * child) static
Definition at line 567 of file qtextdocument_p.cpp.
Referenced by QTextDocumentPrivate::move().
 {
     while (child) {
         if (child == possibleAncestor)
             return true;
         child = child->parentFrame();
     }
     return false;
 }
isValidBlockSeparator()
static bool isValidBlockSeparator (const QChar & ch) static
Definition at line 129 of file qtextdocument_p.cpp.
Referenced by QTextDocumentPrivate::insert_block(), QTextDocumentPrivate::insertBlock(), QTextDocumentPrivate::move(), QTextDocumentPrivate::remove_block(), and QTextDocumentPrivate::unite().
 {
     return ch == QChar::ParagraphSeparator
         || ch == QTextBeginningOfFrame
         || ch == QTextEndOfFrame;
 }
noBlockInString()
static bool noBlockInString (const QString & str) static
Definition at line 137 of file qtextdocument_p.cpp.
Referenced by QTextDocumentPrivate::insert(), QTextDocumentPrivate::insert_string(), QTextDocumentPrivate::move(), and QTextDocumentPrivate::remove_string().
 {
     return !str.contains(QChar::ParagraphSeparator)
         && !str.contains(QTextBeginningOfFrame)
         && !str.contains(QTextEndOfFrame);
 }