Qt 4.8: /src/gui/text/qtextengine.cpp File Reference
qtextengine.cpp File Reference
#include "qdebug.h"
#include "qtextformat.h"
#include "qtextformat_p.h"
#include "qtextengine_p.h"
#include "qabstracttextdocumentlayout.h"
#include "qtextlayout.h"
#include "qtextboundaryfinder.h"
#include "qvarlengtharray.h"
#include "qfont.h"
#include "qfont_p.h"
#include "qfontengine_p.h"
#include "qstring.h"
#include <private/qunicodetables_p.h>
#include "qtextdocument_p.h"
#include <qapplication.h>
#include <stdlib.h>
#include "qfontengine_ft_p.h"
#include <private/qharfbuzz_p.h>
Classes
struct QBidiControl
struct QBidiStatus
struct QJustificationPoint
Macros
#define BIDI_DEBUG 0
Enumerations
enum { MaxBidiLevel = 61 }
Functions
static void appendItems (QScriptAnalysis *analysis, int &start, int &stop, const QBidiControl &control, QChar::Direction dir)
static bool bidiItemize (QTextEngine *engine, QScriptAnalysis *analysis, QBidiControl &control)
static bool enableHarfBuzz ()
static bool hasCaseChange (const QScriptItem &si)
static void heuristicSetGlyphAttributes (const QChar *uc, int length, QGlyphLayout *glyphs, unsigned short *logClusters, int num_glyphs)
static void init (QTextEngine *e)
static void moveGlyphData (const QGlyphLayout &destination, const QGlyphLayout &source, int num)
static bool nextCharJoins (const QString &string, int pos)
static bool prevCharJoins (const QString &string, int pos)
Q_DECLARE_TYPEINFO (QJustificationPoint, Q_PRIMITIVE_TYPE)
QTransform qt_true_matrix (qreal w, qreal h, QTransform x)
static void releaseCachedFontEngine (QFontEngine *fontEngine)
static void set (QJustificationPoint *point, int type, const QGlyphLayout &glyph, QFontEngine *fe)
static QChar::Direction skipBoundryNeutrals (QScriptAnalysis *analysis, const ushort *unicode, int length, int &sor, int &eor, QBidiControl &control)
static bool stringToGlyphs (HB_ShaperItem *item, QGlyphLayout *glyphs, QFontEngine *fontEngine)
Macro Definition Documentation
BIDI_DEBUG
#define BIDI_DEBUG 0
Definition at line 227 of file qtextengine.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MaxBidiLevel
Definition at line 254 of file qtextengine.cpp.
 { MaxBidiLevel = 61 };
Function Documentation
appendItems()
static void appendItems (QScriptAnalysis * analysis, int & start, int & stop, const QBidiControl & control, QChar::Direction dir) static
Definition at line 302 of file qtextengine.cpp.
Referenced by bidiItemize().
 {
     if (start > stop)
         return;
     int level = control.level;
     if(dir != QChar::DirON && !control.override) {
         // add level of run (cases I1 & I2)
         if(level % 2) {
             if(dir == QChar::DirL || dir == QChar::DirAN || dir == QChar::DirEN)
                 level++;
         } else {
             if(dir == QChar::DirR)
                 level++;
             else if(dir == QChar::DirAN || dir == QChar::DirEN)
                 level += 2;
         }
     }
 #if (BIDI_DEBUG >= 1)
     qDebug("new run: dir=%s from %d, to %d level = %d override=%d", directions[dir], start, stop, level, control.override);
 #endif
     QScriptAnalysis *s = analysis + start;
     const QScriptAnalysis *e = analysis + stop;
     while (s <= e) {
         s->bidiLevel = level;
         ++s;
     }
     ++stop;
     start = stop;
 }
bidiItemize()
static bool bidiItemize (QTextEngine * engine, QScriptAnalysis * analysis, QBidiControl & control) static
Definition at line 357 of file qtextengine.cpp.
Referenced by QTextEngine::itemize().
 {
     bool rightToLeft = (control.basicDirection() == 1);
     bool hasBidi = rightToLeft;
 #if BIDI_DEBUG >= 2
     qDebug() << "bidiItemize: rightToLeft=" << rightToLeft << engine->layoutData->string;
 #endif
     int sor = 0;
     int eor = -1;
     int length = engine->layoutData->string.length();
     const ushort *unicode = (const ushort *)engine->layoutData->string.unicode();
     int current = 0;
     QChar::Direction dir = rightToLeft ? QChar::DirR : QChar::DirL;
     QBidiStatus status;
     QChar::Direction sdir = QChar::direction(*unicode);
     if (sdir != QChar::DirL && sdir != QChar::DirR && sdir != QChar::DirEN && sdir != QChar::DirAN)
         sdir = QChar::DirON;
     else
         dir = QChar::DirON;
     status.eor = sdir;
     status.lastStrong = rightToLeft ? QChar::DirR : QChar::DirL;
     status.last = status.lastStrong;
     status.dir = sdir;
     while (current <= length) {
         QChar::Direction dirCurrent;
         if (current == (int)length)
             dirCurrent = control.basicDirection();
         else
             dirCurrent = QChar::direction(unicode[current]);
 #if (BIDI_DEBUG >= 2)
 //         qDebug() << "pos=" << current << " dir=" << directions[dir]
 //                  << " current=" << directions[dirCurrent] << " last=" << directions[status.last]
 //                  << " eor=" << eor << '/' << directions[status.eor]
 //                  << " sor=" << sor << " lastStrong="
 //                  << directions[status.lastStrong]
 //                  << " level=" << (int)control.level << " override=" << (bool)control.override;
 #endif
         switch(dirCurrent) {
             // embedding and overrides (X1-X9 in the BiDi specs)
         case QChar::DirRLE:
         case QChar::DirRLO:
         case QChar::DirLRE:
         case QChar::DirLRO:
             {
                 bool rtl = (dirCurrent == QChar::DirRLE || dirCurrent == QChar::DirRLO);
                 hasBidi |= rtl;
                 bool override = (dirCurrent == QChar::DirLRO || dirCurrent == QChar::DirRLO);
                 unsigned int level = control.level+1;
                 if ((level%2 != 0) == rtl) ++level;
                 if(level < MaxBidiLevel) {
                     eor = current-1;
                     appendItems(analysis, sor, eor, control, dir);
                     eor = current;
                     control.embed(rtl, override);
                     QChar::Direction edir = (rtl ? QChar::DirR : QChar::DirL);
                     dir = status.eor = edir;
                     status.lastStrong = edir;
                 }
                 break;
             }
         case QChar::DirPDF:
             {
                 if (control.canPop()) {
                     if (dir != control.direction()) {
                         eor = current-1;
                         appendItems(analysis, sor, eor, control, dir);
                         dir = control.direction();
                     }
                     eor = current;
                     appendItems(analysis, sor, eor, control, dir);
                     control.pdf();
                     dir = QChar::DirON; status.eor = QChar::DirON;
                     status.last = control.direction();
                     if (control.override)
                         dir = control.direction();
                     else
                         dir = QChar::DirON;
                     status.lastStrong = control.direction();
                 }
                 break;
             }
             // strong types
         case QChar::DirL:
             if(dir == QChar::DirON)
                 dir = QChar::DirL;
             switch(status.last)
                 {
                 case QChar::DirL:
                     eor = current; status.eor = QChar::DirL; break;
                 case QChar::DirR:
                 case QChar::DirAL:
                 case QChar::DirEN:
                 case QChar::DirAN:
                     if (eor >= 0) {
                         appendItems(analysis, sor, eor, control, dir);
                         status.eor = dir = skipBoundryNeutrals(analysis, unicode, length, sor, eor, control);
                     } else {
                         eor = current; status.eor = dir;
                     }
                     break;
                 case QChar::DirES:
                 case QChar::DirET:
                 case QChar::DirCS:
                 case QChar::DirBN:
                 case QChar::DirB:
                 case QChar::DirS:
                 case QChar::DirWS:
                 case QChar::DirON:
                     if(dir != QChar::DirL) {
                         //last stuff takes embedding dir
                         if(control.direction() == QChar::DirR) {
                             if(status.eor != QChar::DirR) {
                                 // AN or EN
                                 appendItems(analysis, sor, eor, control, dir);
                                 status.eor = QChar::DirON;
                                 dir = QChar::DirR;
                             }
                             eor = current - 1;
                             appendItems(analysis, sor, eor, control, dir);
                             status.eor = dir = skipBoundryNeutrals(analysis, unicode, length, sor, eor, control);
                         } else {
                             if(status.eor != QChar::DirL) {
                                 appendItems(analysis, sor, eor, control, dir);
                                 status.eor = QChar::DirON;
                                 dir = QChar::DirL;
                             } else {
                                 eor = current; status.eor = QChar::DirL; break;
                             }
                         }
                     } else {
                         eor = current; status.eor = QChar::DirL;
                     }
                 default:
                     break;
                 }
             status.lastStrong = QChar::DirL;
             break;
         case QChar::DirAL:
         case QChar::DirR:
             hasBidi = true;
             if(dir == QChar::DirON) dir = QChar::DirR;
             switch(status.last)
                 {
                 case QChar::DirL:
                 case QChar::DirEN:
                 case QChar::DirAN:
                     if (eor >= 0)
                         appendItems(analysis, sor, eor, control, dir);
                     // fall through
                 case QChar::DirR:
                 case QChar::DirAL:
                     dir = QChar::DirR; eor = current; status.eor = QChar::DirR; break;
                 case QChar::DirES:
                 case QChar::DirET:
                 case QChar::DirCS:
                 case QChar::DirBN:
                 case QChar::DirB:
                 case QChar::DirS:
                 case QChar::DirWS:
                 case QChar::DirON:
                     if(status.eor != QChar::DirR && status.eor != QChar::DirAL) {
                         //last stuff takes embedding dir
                         if(control.direction() == QChar::DirR
                            || status.lastStrong == QChar::DirR || status.lastStrong == QChar::DirAL) {
                             appendItems(analysis, sor, eor, control, dir);
                             dir = QChar::DirR; status.eor = QChar::DirON;
                             eor = current;
                         } else {
                             eor = current - 1;
                             appendItems(analysis, sor, eor, control, dir);
                             dir = QChar::DirR; status.eor = QChar::DirON;
                         }
                     } else {
                         eor = current; status.eor = QChar::DirR;
                     }
                 default:
                     break;
                 }
             status.lastStrong = dirCurrent;
             break;
             // weak types:
         case QChar::DirNSM:
             if (eor == current-1)
                 eor = current;
             break;
         case QChar::DirEN:
             // if last strong was AL change EN to AN
             if(status.lastStrong != QChar::DirAL) {
                 if(dir == QChar::DirON) {
                     if(status.lastStrong == QChar::DirL)
                         dir = QChar::DirL;
                     else
                         dir = QChar::DirEN;
                 }
                 switch(status.last)
                     {
                     case QChar::DirET:
                         if (status.lastStrong == QChar::DirR || status.lastStrong == QChar::DirAL) {
                             appendItems(analysis, sor, eor, control, dir);
                             status.eor = QChar::DirON;
                             dir = QChar::DirAN;
                         }
                         // fall through
                     case QChar::DirEN:
                     case QChar::DirL:
                         eor = current;
                         status.eor = dirCurrent;
                         break;
                     case QChar::DirR:
                     case QChar::DirAL:
                     case QChar::DirAN:
                         if (eor >= 0)
                             appendItems(analysis, sor, eor, control, dir);
                         else
                             eor = current;
                         status.eor = QChar::DirEN;
                         dir = QChar::DirAN; break;
                     case QChar::DirES:
                     case QChar::DirCS:
                         if(status.eor == QChar::DirEN || dir == QChar::DirAN) {
                             eor = current; break;
                         }
                     case QChar::DirBN:
                     case QChar::DirB:
                     case QChar::DirS:
                     case QChar::DirWS:
                     case QChar::DirON:
                         if(status.eor == QChar::DirR) {
                             // neutrals go to R
                             eor = current - 1;
                             appendItems(analysis, sor, eor, control, dir);
                             dir = QChar::DirON; status.eor = QChar::DirEN;
                             dir = QChar::DirAN;
                         }
                         else if(status.eor == QChar::DirL ||
                                  (status.eor == QChar::DirEN && status.lastStrong == QChar::DirL)) {
                             eor = current; status.eor = dirCurrent;
                         } else {
                             // numbers on both sides, neutrals get right to left direction
                             if(dir != QChar::DirL) {
                                 appendItems(analysis, sor, eor, control, dir);
                                 dir = QChar::DirON; status.eor = QChar::DirON;
                                 eor = current - 1;
                                 dir = QChar::DirR;
                                 appendItems(analysis, sor, eor, control, dir);
                                 dir = QChar::DirON; status.eor = QChar::DirON;
                                 dir = QChar::DirAN;
                             } else {
                                 eor = current; status.eor = dirCurrent;
                             }
                         }
                     default:
                         break;
                     }
                 break;
             }
         case QChar::DirAN:
             hasBidi = true;
             dirCurrent = QChar::DirAN;
             if(dir == QChar::DirON) dir = QChar::DirAN;
             switch(status.last)
                 {
                 case QChar::DirL:
                 case QChar::DirAN:
                     eor = current; status.eor = QChar::DirAN; break;
                 case QChar::DirR:
                 case QChar::DirAL:
                 case QChar::DirEN:
                     if (eor >= 0){
                         appendItems(analysis, sor, eor, control, dir);
                     } else {
                         eor = current;
                     }
                     dir = QChar::DirAN; status.eor = QChar::DirAN;
                     break;
                 case QChar::DirCS:
                     if(status.eor == QChar::DirAN) {
                         eor = current; break;
                     }
                 case QChar::DirES:
                 case QChar::DirET:
                 case QChar::DirBN:
                 case QChar::DirB:
                 case QChar::DirS:
                 case QChar::DirWS:
                 case QChar::DirON:
                     if(status.eor == QChar::DirR) {
                         // neutrals go to R
                         eor = current - 1;
                         appendItems(analysis, sor, eor, control, dir);
                         status.eor = QChar::DirAN;
                         dir = QChar::DirAN;
                     } else if(status.eor == QChar::DirL ||
                                (status.eor == QChar::DirEN && status.lastStrong == QChar::DirL)) {
                         eor = current; status.eor = dirCurrent;
                     } else {
                         // numbers on both sides, neutrals get right to left direction
                         if(dir != QChar::DirL) {
                             appendItems(analysis, sor, eor, control, dir);
                             status.eor = QChar::DirON;
                             eor = current - 1;
                             dir = QChar::DirR;
                             appendItems(analysis, sor, eor, control, dir);
                             status.eor = QChar::DirAN;
                             dir = QChar::DirAN;
                         } else {
                             eor = current; status.eor = dirCurrent;
                         }
                     }
                 default:
                     break;
                 }
             break;
         case QChar::DirES:
         case QChar::DirCS:
             break;
         case QChar::DirET:
             if(status.last == QChar::DirEN) {
                 dirCurrent = QChar::DirEN;
                 eor = current; status.eor = dirCurrent;
             }
             break;
             // boundary neutrals should be ignored
         case QChar::DirBN:
             break;
             // neutrals
         case QChar::DirB:
             // ### what do we do with newline and paragraph separators that come to here?
             break;
         case QChar::DirS:
             // ### implement rule L1
             break;
         case QChar::DirWS:
         case QChar::DirON:
             break;
         default:
             break;
         }
         //qDebug() << "     after: dir=" << //        dir << " current=" << dirCurrent << " last=" << status.last << " eor=" << status.eor << " lastStrong=" << status.lastStrong << " embedding=" << control.direction();
         if(current >= (int)length) break;
         // set status.last as needed.
         switch(dirCurrent) {
         case QChar::DirET:
         case QChar::DirES:
         case QChar::DirCS:
         case QChar::DirS:
         case QChar::DirWS:
         case QChar::DirON:
             switch(status.last)
             {
             case QChar::DirL:
             case QChar::DirR:
             case QChar::DirAL:
             case QChar::DirEN:
             case QChar::DirAN:
                 status.last = dirCurrent;
                 break;
             default:
                 status.last = QChar::DirON;
             }
             break;
         case QChar::DirNSM:
         case QChar::DirBN:
             // ignore these
             break;
         case QChar::DirLRO:
         case QChar::DirLRE:
             status.last = QChar::DirL;
             break;
         case QChar::DirRLO:
         case QChar::DirRLE:
             status.last = QChar::DirR;
             break;
         case QChar::DirEN:
             if (status.last == QChar::DirL) {
                 status.last = QChar::DirL;
                 break;
             }
             // fall through
         default:
             status.last = dirCurrent;
         }
         ++current;
     }
 #if (BIDI_DEBUG >= 1)
     qDebug() << "reached end of line current=" << current << ", eor=" << eor;
 #endif
     eor = current - 1; // remove dummy char
     if (sor <= eor)
         appendItems(analysis, sor, eor, control, dir);
     return hasBidi;
 }
enableHarfBuzz()
static bool enableHarfBuzz () static
Definition at line 891 of file qtextengine.cpp.
Referenced by QTextEngine::shapeText().
 {
     static enum { Yes, No, Unknown } status = Unknown;
     if (status == Unknown) {
         QByteArray v = qgetenv("QT_ENABLE_HARFBUZZ");
         bool value = !v.isEmpty() && v != "0" && v != "false";
         if (value) status = Yes;
         else status = No;
     }
     return status == Yes;
 }
hasCaseChange()
static bool hasCaseChange (const QScriptItem & si) inline static
Definition at line 987 of file qtextengine.cpp.
Referenced by QTextEngine::shapeTextWithCE(), and QTextEngine::shapeTextWithHarfbuzz().
 {
     return si.analysis.flags == QScriptAnalysis::SmallCaps ||
            si.analysis.flags == QScriptAnalysis::Uppercase ||
            si.analysis.flags == QScriptAnalysis::Lowercase;
 }
heuristicSetGlyphAttributes()
static void heuristicSetGlyphAttributes (const QChar * uc, int length, QGlyphLayout * glyphs, unsigned short * logClusters, int num_glyphs) static
Definition at line 998 of file qtextengine.cpp.
Referenced by QTextEngine::shapeTextWithCE().
 {
     // ### zeroWidth and justification are missing here!!!!!
     Q_UNUSED(num_glyphs);
     Q_ASSERT(num_glyphs <= length);
 //     qDebug("QScriptEngine::heuristicSetGlyphAttributes, num_glyphs=%d", item->num_glyphs);
     int glyph_pos = 0;
     for (int i = 0; i < length; i++) {
         if (uc[i].isHighSurrogate() && i < length-1 && uc[i+1].isLowSurrogate()) {
             logClusters[i] = glyph_pos;
             logClusters[++i] = glyph_pos;
         } else {
             logClusters[i] = glyph_pos;
         }
         ++glyph_pos;
     }
     // first char in a run is never (treated as) a mark
     int cStart = 0;
     const bool symbolFont = false; // ####
     glyphs->attributes[0].mark = false;
     glyphs->attributes[0].clusterStart = true;
     glyphs->attributes[0].dontPrint = (!symbolFont && uc[0].unicode() == 0x00ad) || qIsControlChar(uc[0].unicode());
     int pos = 0;
     int lastCat = QChar::category(uc[0].unicode());
     for (int i = 1; i < length; ++i) {
         if (logClusters[i] == pos)
             // same glyph
             continue;
         ++pos;
         while (pos < logClusters[i]) {
             glyphs[pos].attributes = glyphs[pos-1].attributes;
             ++pos;
         }
         // hide soft-hyphens by default
         if ((!symbolFont && uc[i].unicode() == 0x00ad) || qIsControlChar(uc[i].unicode()))
             glyphs->attributes[pos].dontPrint = true;
         const QUnicodeTables::Properties *prop = QUnicodeTables::properties(uc[i].unicode());
         int cat = prop->category;
         if (cat != QChar::Mark_NonSpacing) {
             glyphs->attributes[pos].mark = false;
             glyphs->attributes[pos].clusterStart = true;
             glyphs->attributes[pos].combiningClass = 0;
             cStart = logClusters[i];
         } else {
             int cmb = prop->combiningClass;
             if (cmb == 0) {
                 // Fix 0 combining classes
                 if ((uc[pos].unicode() & 0xff00) == 0x0e00) {
                     // thai or lao
                     unsigned char col = uc[pos].cell();
                     if (col == 0x31 ||
                          col == 0x34 ||
                          col == 0x35 ||
                          col == 0x36 ||
                          col == 0x37 ||
                          col == 0x47 ||
                          col == 0x4c ||
                          col == 0x4d ||
                          col == 0x4e) {
                         cmb = QChar::Combining_AboveRight;
                     } else if (col == 0xb1 ||
                                 col == 0xb4 ||
                                 col == 0xb5 ||
                                 col == 0xb6 ||
                                 col == 0xb7 ||
                                 col == 0xbb ||
                                 col == 0xcc ||
                                 col == 0xcd) {
                         cmb = QChar::Combining_Above;
                     } else if (col == 0xbc) {
                         cmb = QChar::Combining_Below;
                     }
                 }
             }
             glyphs->attributes[pos].mark = true;
             glyphs->attributes[pos].clusterStart = false;
             glyphs->attributes[pos].combiningClass = cmb;
             logClusters[i] = cStart;
             glyphs->advances_x[pos] = 0;
             glyphs->advances_y[pos] = 0;
         }
         // one gets an inter character justification point if the current char is not a non spacing mark.
         // as then the current char belongs to the last one and one gets a space justification point
         // after the space char.
         if (lastCat == QChar::Separator_Space)
             glyphs->attributes[pos-1].justification = HB_Space;
         else if (cat != QChar::Mark_NonSpacing)
             glyphs->attributes[pos-1].justification = HB_Character;
         else
             glyphs->attributes[pos-1].justification = HB_NoJustification;
         lastCat = cat;
     }
     pos = logClusters[length-1];
     if (lastCat == QChar::Separator_Space)
         glyphs->attributes[pos].justification = HB_Space;
     else
         glyphs->attributes[pos].justification = HB_Character;
 }
init()
static void init (QTextEngine * e) static
Definition at line 1368 of file qtextengine.cpp.
Referenced by QTextEngine::QTextEngine().
 {
     e->ignoreBidi = false;
     e->cacheGlyphs = false;
     e->forceJustification = false;
     e->visualMovement = false;
     e->layoutData = 0;
     e->minWidth = 0;
     e->maxWidth = 0;
     e->underlinePositions = 0;
     e->specialData = 0;
     e->stackEngine = false;
 }
moveGlyphData()
static void moveGlyphData (const QGlyphLayout & destination, const QGlyphLayout & source, int num) inline static
Definition at line 1175 of file qtextengine.cpp.
Referenced by QTextEngine::shapeTextWithHarfbuzz().
 {
     if (num > 0 && destination.glyphs != source.glyphs) {
         memmove(destination.glyphs, source.glyphs, num * sizeof(HB_Glyph));
         memmove(destination.attributes, source.attributes, num * sizeof(HB_GlyphAttributes));
         memmove(destination.advances_x, source.advances_x, num * sizeof(HB_Fixed));
         memmove(destination.offsets, source.offsets, num * sizeof(HB_FixedPoint));
     }
 }
nextCharJoins()
static bool nextCharJoins (const QString & string, int pos) inline static
Definition at line 2467 of file qtextengine.cpp.
Referenced by QTextEngine::elidedText().
 {
     while (pos < string.length() && string.at(pos).category() == QChar::Mark_NonSpacing)
         ++pos;
     if (pos == string.length())
         return false;
     return string.at(pos).joining() != QChar::OtherJoining;
 }
prevCharJoins()
static bool prevCharJoins (const QString & string, int pos) inline static
Definition at line 2476 of file qtextengine.cpp.
Referenced by QTextEngine::elidedText().
 {
     while (pos > 0 && string.at(pos - 1).category() == QChar::Mark_NonSpacing)
         --pos;
     if (pos == 0)
         return false;
     QChar::Joining joining = string.at(pos - 1).joining();
     return (joining == QChar::Dual || joining == QChar::Center);
 }
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QJustificationPoint , Q_PRIMITIVE_TYPE)
qt_true_matrix()
QTransform qt_true_matrix (qreal w, qreal h, QTransform x)
Definition at line 3154 of file qtextengine.cpp.
Referenced by glyph_metrics_t::transformed().
 {
     QRectF rect = x.mapRect(QRectF(0, 0, w, h));
     return x * QTransform::fromTranslate(-rect.x(), -rect.y());
 }
releaseCachedFontEngine()
static void releaseCachedFontEngine (QFontEngine * fontEngine) inline static
Definition at line 1454 of file qtextengine.cpp.
Referenced by QTextEngine::fontEngine(), and QTextEngine::resetFontEngineCache().
 {
     if (fontEngine) {
         fontEngine->ref.deref();
         if (fontEngine->cache_count == 0 && fontEngine->ref == 0)
             delete fontEngine;
     }
 }
set()
static void set (QJustificationPoint * point, int type, const QGlyphLayout & glyph, QFontEngine * fe) static
Definition at line 1974 of file qtextengine.cpp.
Referenced by QX11PaintEngine::drawFreetype(), QFontEngineFT::loadFlags(), QFontEngineFT::loadGlyph(), and QFontEngineX11FT::uploadGlyphToServer().
 {
     point->type = type;
     point->glyph = glyph;
     point->fontEngine = fe;
     if (type >= HB_Arabic_Normal) {
         QChar ch(0x640); // Kashida character
         QGlyphLayoutArray<8> glyphs;
         int nglyphs = 7;
         fe->stringToCMap(&ch, 1, &glyphs, &nglyphs, 0);
         if (glyphs.glyphs[0] && glyphs.advances_x[0] != 0) {
             point->kashidaWidth = glyphs.advances_x[0];
         } else {
             point->type = HB_NoJustification;
             point->kashidaWidth = 0;
         }
     }
 }
skipBoundryNeutrals()
static QChar::Direction skipBoundryNeutrals (QScriptAnalysis * analysis, const ushort * unicode, int length, int & sor, int & eor, QBidiControl & control) static
Definition at line 335 of file qtextengine.cpp.
Referenced by bidiItemize().
 {
     QChar::Direction dir = control.basicDirection();
     int level = sor > 0 ? analysis[sor - 1].bidiLevel : control.level;
     while (sor < length) {
         dir = QChar::direction(unicode[sor]);
         // Keep skipping DirBN as if it doesn't exist
         if (dir != QChar::DirBN)
             break;
         analysis[sor++].bidiLevel = level;
     }
     eor = sor;
     if (eor == length)
         dir = control.basicDirection();
     return dir;
 }
stringToGlyphs()
static bool stringToGlyphs (HB_ShaperItem * item, QGlyphLayout * glyphs, QFontEngine * fontEngine) static
Definition at line 846 of file qtextengine.cpp.
Referenced by QTextEngine::shapeTextWithHarfbuzz().
 {
     int nGlyphs = item->num_glyphs;
     QTextEngine::ShaperFlags shaperFlags(QTextEngine::GlyphIndicesOnly);
     if (item->item.bidiLevel % 2)
         shaperFlags |= QTextEngine::RightToLeft;
     bool result = fontEngine->stringToCMap(reinterpret_cast<const QChar *>(item->string + item->item.pos), item->item.length, glyphs, &nGlyphs, shaperFlags);
     item->num_glyphs = nGlyphs;
     glyphs->numGlyphs = nGlyphs;
     return result;
 }