Qt 4.8: /src/corelib/codecs/qtextcodec.cpp File Reference
qtextcodec.cpp File Reference
#include "qplatformdefs.h"
#include "qtextcodec.h"
#include "qtextcodec_p.h"
#include "qlist.h"
#include "qfile.h"
#include "qvarlengtharray.h"
#include "qcoreapplication.h"
#include "qtextcodecplugin.h"
#include "private/qfactoryloader_p.h"
#include "qstringlist.h"
#include "qiconvcodec_p.h"
#include "qutfcodec_p.h"
#include "qsimplecodec_p.h"
#include "qlatincodec_p.h"
#include "qtsciicodec_p.h"
#include "qisciicodec_p.h"
#include "qfontlaocodec_p.h"
#include "../../plugins/codecs/jp/qfontjpcodec.h"
#include "qlocale.h"
#include "qmutex.h"
#include "qhash.h"
#include <stdlib.h>
#include <ctype.h>
#include <locale.h>
Classes
class QTextCodecCleanup
class QWindowsLocalCodec
Macros
#define QT_NO_SETLOCALE
Functions
static QTextCodec * createForMib (int mib)
static QTextCodec * createForName (const QByteArray &name)
static bool nameMatch (const QByteArray &name, const QByteArray &test)
Q_GLOBAL_STATIC_WITH_ARGS (QFactoryLoader, loader,(QTextCodecFactoryInterface_iid, QLatin1String("/codecs"))) typedef QHash< QByteArray
Q_GLOBAL_STATIC_WITH_ARGS (QMutex, textCodecsMutex,(QMutex::Recursive))
static bool qisalnum (register char c)
static char qtolower (register char c)
static void setup ()
static void setupLocaleMapper ()
Variables
static QList< QTextCodec * > * all = 0
static QTextCodec * localeMapper = 0
QTextCodec * QTextCodecCache
Macro Definition Documentation
QT_NO_SETLOCALE
#define QT_NO_SETLOCALE
Definition at line 96 of file qtextcodec.cpp.
Function Documentation
createForMib()
static QTextCodec* createForMib (int mib) static
Definition at line 175 of file qtextcodec.cpp.
Referenced by QTextCodec::codecForMib().
 {
 #ifndef QT_NO_TEXTCODECPLUGIN
     QString name = QLatin1String("MIB: ") + QString::number(mib);
     if (QTextCodecFactoryInterface *factory
         = qobject_cast<QTextCodecFactoryInterface*>(loader()->instance(name)))
         return factory->create(name);
 #else
     Q_UNUSED(mib);
 #endif
     return 0;
 }
createForName()
static QTextCodec* createForName (const QByteArray & name) static
Definition at line 155 of file qtextcodec.cpp.
Referenced by QTextCodec::codecForName().
 {
 #if !defined(QT_NO_LIBRARY) && !defined(QT_NO_TEXTCODECPLUGIN)
     QFactoryLoader *l = loader();
     QStringList keys = l->keys();
     for (int i = 0; i < keys.size(); ++i) {
         if (nameMatch(name, keys.at(i).toLatin1())) {
             QString realName = keys.at(i);
             if (QTextCodecFactoryInterface *factory
                 = qobject_cast<QTextCodecFactoryInterface*>(l->instance(realName))) {
                 return factory->create(realName);
             }
         }
     }
 #else
     Q_UNUSED(name);
 #endif
     return 0;
 }
nameMatch()
static bool nameMatch (const QByteArray & name, const QByteArray & test) static
Definition at line 124 of file qtextcodec.cpp.
Referenced by QTextCodec::codecForName(), and createForName().
 {
     // if they're the same, return a perfect score
     if (qstricmp(name, test) == 0)
         return true;
     const char *n = name.constData();
     const char *h = test.constData();
     // if the letters and numbers are the same, we have a match
     while (*n != '\0') {
         if (qisalnum(*n)) {
             for (;;) {
                 if (*h == '\0')
                     return false;
                 if (qisalnum(*h))
                     break;
                 ++h;
             }
             if (qtolower(*n) != qtolower(*h))
                 return false;
             ++h;
         }
         ++n;
     }
     while (*h && !qisalnum(*h))
            ++h;
     return (*h == '\0');
 }
Q_GLOBAL_STATIC_WITH_ARGS() [1/2]
Q_GLOBAL_STATIC_WITH_ARGS (QFactoryLoader , loader , (QTextCodecFactoryInterface_iid, QLatin1String("/codecs")))
Referenced by setupLocaleMapper().
Q_GLOBAL_STATIC_WITH_ARGS() [2/2]
Q_GLOBAL_STATIC_WITH_ARGS (QMutex , textCodecsMutex , (QMutex::Recursive))
qisalnum()
static bool qisalnum (register char c) static
Definition at line 121 of file qtextcodec.cpp.
Referenced by nameMatch().
 { return (c >= '0' && c <= '9') || ((c | 0x20) >= 'a' && (c | 0x20) <= 'z'); }
qtolower()
static char qtolower (register char c) static
Definition at line 119 of file qtextcodec.cpp.
Referenced by nameMatch().
 { if (c >= 'A' && c <= 'Z') return c + 0x20; return c; }
setup()
static void setup () static
Definition at line 718 of file qtextcodec.cpp.
Referenced by QTextCodec::availableCodecs(), QTextCodec::availableMibs(), QTextCodec::codecForLocale(), QTextCodec::codecForMib(), QTextCodec::codecForName(), QDeclarativeBindingCompilerPrivate::fetch(), IapMonitor::IapMonitor(), QListWidgetPrivate::listModel(), QPrinter::printRange(), QRegExpEngine::QRegExpEngine(), QTextCodec::QTextCodec(), QTextEditMimeData::QTextEditMimeData(), QWizardHeader::QWizardHeader(), QTextEditMimeData::retrieveData(), QTableWidgetPrivate::tableModel(), QIntKeyboardListenThread::~QIntKeyboardListenThread(), and QIntMouseListenThread::~QIntMouseListenThread().
 {
     if (all)
         return;
 #ifdef Q_OS_SYMBIAN
     // If we don't have a trap handler, we're outside of the main() function,
     // ie. in global constructors or destructors. Don't create codecs in this
     // case as it would lead to crashes because of a missing cleanup stack on Symbian
     if (User::TrapHandler() == NULL)
         return;
 #endif
 #ifdef Q_DEBUG_TEXTCODEC
     if (destroying_is_ok)
         qWarning("QTextCodec: Creating new codec during codec cleanup");
 #endif
     all = new QList<QTextCodec*>;
     // create the cleanup object to cleanup all codecs on exit
     (void) createQTextCodecCleanup();
 #ifndef QT_NO_CODECS
     (void)new QTsciiCodec;
     for (int i = 0; i < 9; ++i)
         (void)new QIsciiCodec(i);
     for (int i = 0; i < QSimpleTextCodec::numSimpleCodecs; ++i)
         (void)new QSimpleTextCodec(i);
 #ifdef Q_OS_SYMBIAN
     localeMapper = QSymbianTextCodec::init();
 #endif
 #  if defined(Q_WS_X11) && !defined(QT_BOOTSTRAPPED)
     // no font codecs when bootstrapping
     (void)new QFontLaoCodec;
 #    if defined(QT_NO_ICONV)
     // no iconv(3) support, must build all codecs into the library
     (void)new QFontGb2312Codec;
     (void)new QFontGbkCodec;
     (void)new QFontGb18030_0Codec;
     (void)new QFontJis0208Codec;
     (void)new QFontJis0201Codec;
     (void)new QFontKsc5601Codec;
     (void)new QFontBig5hkscsCodec;
     (void)new QFontBig5Codec;
 #    endif // QT_NO_ICONV && !QT_BOOTSTRAPPED
 #  endif // Q_WS_X11
 #if !defined(Q_OS_SYMBIAN) && !defined(Q_OS_INTEGRITY)
 #  if defined(QT_NO_ICONV) && !defined(QT_BOOTSTRAPPED) && !defined(QT_CODEC_PLUGINS)
     // no asian codecs when bootstrapping, sorry
     (void)new QGb18030Codec;
     (void)new QGbkCodec;
     (void)new QGb2312Codec;
     (void)new QEucJpCodec;
     (void)new QJisCodec;
     (void)new QSjisCodec;
     (void)new QEucKrCodec;
     (void)new QCP949Codec;
     (void)new QBig5Codec;
     (void)new QBig5hkscsCodec;
 #  endif // QT_NO_ICONV && !QT_BOOTSTRAPPED && !QT_CODEC_PLUGINS
 #endif //Q_OS_SYMBIAN
 #endif // QT_NO_CODECS
 #if defined(Q_OS_WIN32) || defined(Q_OS_WINCE)
     (void) new QWindowsLocalCodec;
 #endif // Q_OS_WIN32
     (void)new QUtf16Codec;
     (void)new QUtf16BECodec;
     (void)new QUtf16LECodec;
     (void)new QUtf32Codec;
     (void)new QUtf32BECodec;
     (void)new QUtf32LECodec;
 #ifndef Q_OS_SYMBIAN
     (void)new QLatin15Codec;
 #endif
     (void)new QLatin1Codec;
     (void)new QUtf8Codec;
 #if !defined(Q_OS_SYMBIAN) && !defined(Q_OS_INTEGRITY)
 #if defined(Q_OS_UNIX) && !defined(QT_NO_ICONV) && !defined(QT_BOOTSTRAPPED)
     // QIconvCodec depends on the UTF-16 codec, so it needs to be created last
     (void) new QIconvCodec();
 #endif
 #endif
     if (!localeMapper)
         setupLocaleMapper();
 }
setupLocaleMapper()
static void setupLocaleMapper () static
Definition at line 581 of file qtextcodec.cpp.
Referenced by QTextCodec::setCodecForLocale().
 {
 #ifdef Q_OS_SYMBIAN
     localeMapper = QSymbianTextCodec::localeMapper;
     if (localeMapper)
         return;
 #endif
 #if defined(Q_OS_WIN32) || defined(Q_OS_WINCE)
     localeMapper = QTextCodec::codecForName("System");
 #else
 #ifndef QT_NO_ICONV
     localeMapper = QTextCodec::codecForName("System");
 #endif
 #if defined (_XOPEN_UNIX) && !defined(Q_OS_QNX) && !defined(Q_OS_OSF)
     if (!localeMapper) {
         char *charset = nl_langinfo (CODESET);
         if (charset)
             localeMapper = QTextCodec::codecForName(charset);
     }
 #endif
     if (!localeMapper) {
         // Very poorly defined and followed standards causes lots of
         // code to try to get all the cases... This logic is
         // duplicated in QIconvCodec, so if you change it here, change
         // it there too.
         // Try to determine locale codeset from locale name assigned to
         // LC_CTYPE category.
         // First part is getting that locale name.  First try setlocale() which
         // definitely knows it, but since we cannot fully trust it, get ready
         // to fall back to environment variables.
 #if !defined(QT_NO_SETLOCALE)
         const QByteArray ctype = setlocale(LC_CTYPE, 0);
 #else
         const QByteArray ctype;
 #endif
         // Get the first nonempty value from $LC_ALL, $LC_CTYPE, and $LANG
         // environment variables.
         QByteArray lang = qgetenv("LC_ALL");
         if (lang.isEmpty() || lang == "C") {
             lang = qgetenv("LC_CTYPE");
         }
         if (lang.isEmpty() || lang == "C") {
             lang = qgetenv("LANG");
         }
         // Now try these in order:
         // 1. CODESET from ctype if it contains a .CODESET part (e.g. en_US.ISO8859-15)
         // 2. CODESET from lang if it contains a .CODESET part
         // 3. ctype (maybe the locale is named "ISO-8859-1" or something)
         // 4. locale (ditto)
         // 5. check for "@euro"
         // 6. guess locale from ctype unless ctype is "C"
         // 7. guess locale from lang
         // 1. CODESET from ctype if it contains a .CODESET part (e.g. en_US.ISO8859-15)
         int indexOfDot = ctype.indexOf('.');
         if (indexOfDot != -1)
             localeMapper = checkForCodec( ctype.mid(indexOfDot + 1) );
         // 2. CODESET from lang if it contains a .CODESET part
         if (!localeMapper) {
             indexOfDot = lang.indexOf('.');
             if (indexOfDot != -1)
                 localeMapper = checkForCodec( lang.mid(indexOfDot + 1) );
         }
         // 3. ctype (maybe the locale is named "ISO-8859-1" or something)
         if (!localeMapper && !ctype.isEmpty() && ctype != "C")
             localeMapper = checkForCodec(ctype);
         // 4. locale (ditto)
         if (!localeMapper && !lang.isEmpty())
             localeMapper = checkForCodec(lang);
         // 5. "@euro"
         if ((!localeMapper && ctype.contains("@euro")) || lang.contains("@euro"))
             localeMapper = checkForCodec("ISO 8859-15");
         // 6. guess locale from ctype unless ctype is "C"
         // 7. guess locale from lang
         const QByteArray &try_by_name = (!ctype.isEmpty() && ctype != "C") ? lang : ctype;
         // Now do the guessing.
         if (!lang.isEmpty() && !localeMapper && !try_by_name.isEmpty()) {
             if (try_locale_list(iso8859_15locales, lang))
                 localeMapper = QTextCodec::codecForName("ISO 8859-15");
             else if (try_locale_list(iso8859_2locales, lang))
                 localeMapper = QTextCodec::codecForName("ISO 8859-2");
             else if (try_locale_list(iso8859_3locales, lang))
                 localeMapper = QTextCodec::codecForName("ISO 8859-3");
             else if (try_locale_list(iso8859_4locales, lang))
                 localeMapper = QTextCodec::codecForName("ISO 8859-4");
             else if (try_locale_list(iso8859_5locales, lang))
                 localeMapper = QTextCodec::codecForName("ISO 8859-5");
             else if (try_locale_list(iso8859_6locales, lang))
                 localeMapper = QTextCodec::codecForName("ISO 8859-6");
             else if (try_locale_list(iso8859_7locales, lang))
                 localeMapper = QTextCodec::codecForName("ISO 8859-7");
             else if (try_locale_list(iso8859_8locales, lang))
                 localeMapper = QTextCodec::codecForName("ISO 8859-8-I");
             else if (try_locale_list(iso8859_9locales, lang))
                 localeMapper = QTextCodec::codecForName("ISO 8859-9");
             else if (try_locale_list(iso8859_13locales, lang))
                 localeMapper = QTextCodec::codecForName("ISO 8859-13");
             else if (try_locale_list(tis_620locales, lang))
                 localeMapper = QTextCodec::codecForName("ISO 8859-11");
             else if (try_locale_list(koi8_ulocales, lang))
                 localeMapper = QTextCodec::codecForName("KOI8-U");
             else if (try_locale_list(cp_1251locales, lang))
                 localeMapper = QTextCodec::codecForName("CP 1251");
             else if (try_locale_list(pt_154locales, lang))
                 localeMapper = QTextCodec::codecForName("PT 154");
             else if (try_locale_list(probably_koi8_rlocales, lang))
                 localeMapper = ru_RU_hack(lang);
         }
     }
     // If everything failed, we default to 8859-1
     // We could perhaps default to 8859-15.
     if (!localeMapper)
         localeMapper = QTextCodec::codecForName("ISO 8859-1");
 #endif
 }
Variable Documentation
all
QList<QTextCodec*>* all = 0 static
Definition at line 188 of file qtextcodec.cpp.
Referenced by QTextCodec::availableCodecs(), QTextCodec::availableMibs(), QTextCodec::codecForMib(), QTextCodec::codecForName(), QTextCodec::QTextCodec(), setup(), QTextCodec::~QTextCodec(), and QTextCodecCleanup::~QTextCodecCleanup().
localeMapper
QTextCodec* localeMapper = 0 static
Definition at line 193 of file qtextcodec.cpp.
Referenced by QTextCodec::codecForLocale(), QTextCodec::setCodecForLocale(), and setupLocaleMapper().
QTextCodecCache
QTextCodec* QTextCodecCache
Definition at line 115 of file qtextcodec.cpp.
Referenced by QTextCodec::codecForMib(), QTextCodec::codecForName(), and QTextCodec::~QTextCodec().