Qt 4.8: /src/corelib/thread/qthread.cpp File Reference
qthread.cpp File Reference
#include "qthread.h"
#include "qthreadstorage.h"
#include "qmutex.h"
#include "qmutexpool_p.h"
#include "qreadwritelock.h"
#include "qabstracteventdispatcher.h"
#include <qeventloop.h>
#include <qhash.h>
#include "qthread_p.h"
#include "private/qcoreapplication_p.h"
Functions
void qt_create_tls ()
Initializes the QThread system.
Function Documentation
qt_create_tls()
void qt_create_tls ()
Initializes the QThread system.
Warning
This function is not part of the public interface.
Definition at line 78 of file qthread_win.cpp.
Referenced by QThread::initialize(), qt_adopted_thread_watcher_function(), and qt_free_tls().
 {
     if (qt_current_thread_data_tls_index != TLS_OUT_OF_INDEXES)
         return;
     static QMutex mutex;
     QMutexLocker locker(&mutex);
     qt_current_thread_data_tls_index = TlsAlloc();
 }