Qt 4.8: /src/corelib/concurrent/qthreadpool.cpp File Reference
qthreadpool.cpp File Reference
#include "qthreadpool.h"
#include "qthreadpool_p.h"
#include "qelapsedtimer.h"
Classes
class QThreadPoolThread
Functions
bool operator< (int priority, const QPair< QRunnable *, int > &p)
bool operator< (const QPair< QRunnable *, int > &p, int priority)
Function Documentation
operator<() [1/2]
bool operator< (int priority, const QPair< QRunnable *, int > & p) inline
Definition at line 50 of file qthreadpool.cpp.
Referenced by QVector< QPoint >::constData(), QIntersectionPoint::isAccurate(), QUuid::operator!=(), QKeySequence::operator!=(), QDateTime::operator!=(), QWindowsXPStyle::QWindowsXPStyle(), QListWidgetItem::setSizeHint(), QTableWidgetItem::setSizeHint(), QTreeWidgetItem::setSizeHint(), and QUrl::swap().
 {
     return p.second < priority;
 }
operator<() [2/2]
bool operator< (const QPair< QRunnable *, int > & p, int priority) inline
Definition at line 54 of file qthreadpool.cpp.
 {
     return priority < p.second;
 }