Qt 4.8: /src/corelib/thread/qthreadstorage.h File Reference
qthreadstorage.h File Reference
#include <QtCore/qglobal.h>
Classes
class QThreadStorage< T >
The QThreadStorage class provides per-thread data storage.
class QThreadStorageData
Functions
template<typename T >
void qThreadStorage_deleteData (void *d, T **)
template<typename T >
void qThreadStorage_deleteData (void *d, T *)
template<typename T >
T *& qThreadStorage_localData (QThreadStorageData &d, T **)
template<typename T >
T & qThreadStorage_localData (QThreadStorageData &d, T *)
template<typename T >
T * qThreadStorage_localData_const (const QThreadStorageData &d, T **)
template<typename T >
T qThreadStorage_localData_const (const QThreadStorageData &d, T *)
template<typename T >
void qThreadStorage_setLocalData (QThreadStorageData &d, T **t)
template<typename T >
void qThreadStorage_setLocalData (QThreadStorageData &d, T *t)
Function Documentation
qThreadStorage_deleteData() [1/2]
template<typename T > void qThreadStorage_deleteData (void * d, T **) inline
Definition at line 96 of file qthreadstorage.h.
Referenced by QThreadStorage< QNetworkAccessCache *>::deleteData().
 { delete static_cast<T *>(d); }
qThreadStorage_deleteData() [2/2]
template<typename T > void qThreadStorage_deleteData (void * d, T *) inline
Definition at line 124 of file qthreadstorage.h.
 { delete static_cast<T *>(d); }
qThreadStorage_localData() [1/2]
template<typename T > T*& qThreadStorage_localData (QThreadStorageData & d, T **) inline
Definition at line 74 of file qthreadstorage.h.
Referenced by QThreadStorage< QNetworkAccessCache *>::localData().
 {
     void **v = d.get();
     if (!v) v = d.set(0);
     return *(reinterpret_cast<T**>(v));
 }
qThreadStorage_localData() [2/2]
template<typename T > T& qThreadStorage_localData (QThreadStorageData & d, T *) inline
Definition at line 102 of file qthreadstorage.h.
 {
     void **v = d.get();
     if (!v) v = d.set(new T());
     return *(reinterpret_cast<T*>(*v));
 }
qThreadStorage_localData_const() [1/2]
template<typename T > T* qThreadStorage_localData_const (const QThreadStorageData & d, T **) inline
Definition at line 83 of file qthreadstorage.h.
Referenced by QThreadStorage< QNetworkAccessCache *>::localData().
 {
     void **v = d.get();
     return v ? *(reinterpret_cast<T**>(v)) : 0;
 }
qThreadStorage_localData_const() [2/2]
template<typename T > T qThreadStorage_localData_const (const QThreadStorageData & d, T *) inline
Definition at line 111 of file qthreadstorage.h.
 {
     void **v = d.get();
     return v ? *(reinterpret_cast<T*>(*v)) : T();
 }
qThreadStorage_setLocalData() [1/2]
template<typename T > void qThreadStorage_setLocalData (QThreadStorageData & d, T ** t) inline
Definition at line 91 of file qthreadstorage.h.
Referenced by QThreadStorage< QNetworkAccessCache *>::setLocalData().
 { (void) d.set(*t); }
qThreadStorage_setLocalData() [2/2]
template<typename T > void qThreadStorage_setLocalData (QThreadStorageData & d, T * t) inline
Definition at line 119 of file qthreadstorage.h.
 { (void) d.set(new T(*t)); }