Qt 4.8: /src/gui/image/qtiffhandler.cpp File Reference
qtiffhandler.cpp File Reference
#include "qtiffhandler_p.h"
#include <qvariant.h>
#include <qdebug.h>
#include <qimage.h>
#include <qglobal.h>
#include "tiffio.h"
Functions
static bool checkGrayscale (const QVector< QRgb > &colorTable)
int qtiffCloseProc (thandle_t)
int qtiffMapProc (thandle_t, tdata_t *, toff_t *)
tsize_t qtiffReadProc (thandle_t fd, tdata_t buf, tsize_t size)
toff_t qtiffSeekProc (thandle_t fd, toff_t off, int whence)
toff_t qtiffSizeProc (thandle_t fd)
void qtiffUnmapProc (thandle_t, tdata_t, toff_t)
tsize_t qtiffWriteProc (thandle_t fd, tdata_t buf, tsize_t size)
void rotate_right_mirror_horizontal (QImage *const image)
void rotate_right_mirror_vertical (QImage *const image)
Function Documentation
checkGrayscale()
static bool checkGrayscale (const QVector< QRgb > & colorTable) static
Definition at line 391 of file qtiffhandler.cpp.
Referenced by QTiffHandler::write().
 {
     if (colorTable.size() != 256)
         return false;
     const bool increasing = (colorTable.at(0) == 0xff000000);
     for (int i = 0; i < 256; ++i) {
         if ((increasing && colorTable.at(i) != qRgb(i, i, i))
             || (!increasing && colorTable.at(i) != qRgb(255 - i, 255 - i, 255 - i)))
             return false;
     }
     return true;
 }
qtiffCloseProc()
int qtiffCloseProc (thandle_t)
Definition at line 82 of file qtiffhandler.cpp.
Referenced by QTiffHandler::option(), QTiffHandler::read(), and QTiffHandler::write().
 {
     return 0;
 }
qtiffMapProc()
int qtiffMapProc (thandle_t , tdata_t * , toff_t *)
Definition at line 92 of file qtiffhandler.cpp.
Referenced by QTiffHandler::option(), QTiffHandler::read(), and QTiffHandler::write().
 {
     return 0;
 }
qtiffReadProc()
tsize_t qtiffReadProc (thandle_t fd, tdata_t buf, tsize_t size)
Definition at line 53 of file qtiffhandler.cpp.
Referenced by QTiffHandler::option(), QTiffHandler::read(), and QTiffHandler::write().
 {
     QIODevice* device = static_cast<QTiffHandler*>(fd)->device();
     return device->isReadable() ? device->read(static_cast<char *>(buf), size) : -1;
 }
qtiffSeekProc()
toff_t qtiffSeekProc (thandle_t fd, toff_t off, int whence)
Definition at line 64 of file qtiffhandler.cpp.
Referenced by QTiffHandler::option(), QTiffHandler::read(), and QTiffHandler::write().
 {
     QIODevice *device = static_cast<QTiffHandler*>(fd)->device();
     switch (whence) {
     case SEEK_SET:
         device->seek(off);
         break;
     case SEEK_CUR:
         device->seek(device->pos() + off);
         break;
     case SEEK_END:
         device->seek(device->size() + off);
         break;
     }
     return device->pos();
 }
qtiffSizeProc()
toff_t qtiffSizeProc (thandle_t fd)
Definition at line 87 of file qtiffhandler.cpp.
Referenced by QTiffHandler::option(), QTiffHandler::read(), and QTiffHandler::write().
 {
     return static_cast<QTiffHandler*>(fd)->device()->size();
 }
qtiffUnmapProc()
void qtiffUnmapProc (thandle_t , tdata_t , toff_t)
Definition at line 97 of file qtiffhandler.cpp.
Referenced by QTiffHandler::option(), QTiffHandler::read(), and QTiffHandler::write().
 {
 }
qtiffWriteProc()
tsize_t qtiffWriteProc (thandle_t fd, tdata_t buf, tsize_t size)
Definition at line 59 of file qtiffhandler.cpp.
Referenced by QTiffHandler::option(), QTiffHandler::read(), and QTiffHandler::write().
 {
     return static_cast<QTiffHandler*>(fd)->device()->write(static_cast<char *>(buf), size);
 }
rotate_right_mirror_horizontal()
void rotate_right_mirror_horizontal (QImage *const image) inline
Definition at line 102 of file qtiffhandler.cpp.
Referenced by QTiffHandler::read().
 {
     const int height = image->height();
     const int width = image->width();
     QImage generated(/* width = */ height, /* height = */ width, image->format());
     const uint32 *originalPixel = reinterpret_cast<const uint32*>(image->bits());
     uint32 *const generatedPixels = reinterpret_cast<uint32*>(generated.bits());
     for (int row=0; row < height; ++row) {
         for (int col=0; col < width; ++col) {
             int idx = col * height + row;
             generatedPixels[idx] = *originalPixel;
             ++originalPixel;
         }
     }
     *image = generated;
 }
rotate_right_mirror_vertical()
void rotate_right_mirror_vertical (QImage *const image) inline
Definition at line 119 of file qtiffhandler.cpp.
Referenced by QTiffHandler::read().
 {
     const int height = image->height();
     const int width = image->width();
     QImage generated(/* width = */ height, /* height = */ width, image->format());
     const int lastCol = width - 1;
     const int lastRow = height - 1;
     const uint32 *pixel = reinterpret_cast<const uint32*>(image->bits());
     uint32 *const generatedBits = reinterpret_cast<uint32*>(generated.bits());
     for (int row=0; row < height; ++row) {
         for (int col=0; col < width; ++col) {
             int idx = (lastCol - col) * height + (lastRow - row);
             generatedBits[idx] = *pixel;
             ++pixel;
         }
     }
     *image = generated;
 }