Qt 4.8: /src/corelib/io/qtldurl_p.h File Reference
qtldurl_p.h File Reference
#include "QtCore/qurl.h"
#include "QtCore/qstring.h"
Functions
Q_CORE_EXPORT bool qIsEffectiveTLD (const QString &domain)
Return true if domain is a top-level-domain per Qt's copy of the Mozilla public suffix list.
Q_CORE_EXPORT QString qTopLevelDomain (const QString &domain)
Return the top-level-domain per Qt's copy of the Mozilla public suffix list of domain.
Function Documentation
qIsEffectiveTLD()
Q_CORE_EXPORT bool qIsEffectiveTLD (const QString & domain)
Return true if domain is a top-level-domain per Qt's copy of the Mozilla public suffix list.
Warning
This function is not part of the public interface.
Definition at line 97 of file qtldurl.cpp.
Referenced by qTopLevelDomain(), and QNetworkCookieJar::setCookiesFromUrl().
 {
     // for domain 'foo.bar.com':
     // 1. return if TLD table contains 'foo.bar.com'
     if (containsTLDEntry(domain))
         return true;
     if (domain.contains(QLatin1Char('.'))) {
         int count = domain.size() - domain.indexOf(QLatin1Char('.'));
         QString wildCardDomain;
         wildCardDomain.reserve(count + 1);
         wildCardDomain.append(QLatin1Char('*'));
         wildCardDomain.append(domain.right(count));
         // 2. if table contains '*.bar.com',
         // test if table contains '!foo.bar.com'
         if (containsTLDEntry(wildCardDomain)) {
             QString exceptionDomain;
             exceptionDomain.reserve(domain.size() + 1);
             exceptionDomain.append(QLatin1Char('!'));
             exceptionDomain.append(domain);
             return (! containsTLDEntry(exceptionDomain));
         }
     }
     return false;
 }
qTopLevelDomain()
Q_CORE_EXPORT QString qTopLevelDomain (const QString & domain)
Return the top-level-domain per Qt's copy of the Mozilla public suffix list of domain.
Warning
This function is not part of the public interface.
Definition at line 73 of file qtldurl.cpp.
Referenced by QUrl::topLevelDomain().
 {
     QStringList sections = domain.toLower().split(QLatin1Char('.'), QString::SkipEmptyParts);
     if (sections.isEmpty())
         return QString();
     QString level, tld;
     for (int j = sections.count() - 1; j >= 0; --j) {
         level.prepend(QLatin1Char('.') + sections.at(j));
         if (qIsEffectiveTLD(level.right(level.size() - 1)))
             tld = level;
     }
     return tld;
 }