Qt 4.8: /src/gui/widgets/qtoolbararealayout.cpp File Reference
qtoolbararealayout.cpp File Reference
#include <QWidgetItem>
#include <QToolBar>
#include <QStyleOption>
#include <QApplication>
#include <qdebug.h>
#include "qtoolbararealayout_p.h"
#include "qmainwindowlayout_p.h"
#include "qwidgetanimator_p.h"
#include "qtoolbarlayout_p.h"
#include "qtoolbar_p.h"
Functions
static int getInt (QDataStream &stream, Qt::Orientation o, bool pre43)
static void packRect (uint *geom0, uint *geom1, const QRect &rect, bool floating)
QMainWindowLayout * qt_mainwindow_layout (const QMainWindow *mainWindow)
static QRect unpackRect (uint geom0, uint geom1, bool *floating)
Function Documentation
getInt()
static int getInt (QDataStream & stream, Qt::Orientation o, bool pre43) inline static
Definition at line 1296 of file qtoolbararealayout.cpp.
Referenced by QToolBarAreaLayout::restoreState().
 {
     if (pre43) {
         QPoint p;
         stream >> p;
         return pick(o, p);
     } else {
         int x;
         stream >> x;
         return x;
     }
 }
packRect()
static void packRect (uint * geom0, uint * geom1, const QRect & rect, bool floating) static
Definition at line 1220 of file qtoolbararealayout.cpp.
Referenced by QToolBarAreaLayout::saveState().
 {
     *geom0 = 0;
     *geom1 = 0;
     if (!floating)
         return;
     // The 0x7FFF is half of 0xFFFF. We add it so we can handle negative coordinates on
     // dual monitors. It's subtracted when unpacking.
     *geom0 |= qMax(0, rect.width()) & 0x0000ffff;
     *geom1 |= qMax(0, rect.height()) & 0x0000ffff;
     *geom0 <<= 16;
     *geom1 <<= 16;
     *geom0 |= qMax(0, rect.x() + 0x7FFF) & 0x0000ffff;
     *geom1 |= qMax(0, rect.y() + 0x7FFF) & 0x0000ffff;
     // yeah, we chop one bit off the width, but it still has a range up to 32512
     *geom0 <<= 1;
     *geom0 |= 1;
 }
qt_mainwindow_layout()
QMainWindowLayout* qt_mainwindow_layout (const QMainWindow * mainWindow)
Definition at line 111 of file qmainwindow.cpp.
Referenced by QToolBarAreaLayout::apply().
 {
     return QMainWindowPrivate::mainWindowLayout(mainWindow);
 }
unpackRect()
static QRect unpackRect (uint geom0, uint geom1, bool * floating) static
Definition at line 1200 of file qtoolbararealayout.cpp.
Referenced by QToolBarAreaLayout::restoreState().
 {
     *floating = geom0 & 1;
     if (!*floating)
         return QRect();
     geom0 >>= 1;
     int x = (int)(geom0 & 0x0000ffff) - 0x7FFF;
     int y = (int)(geom1 & 0x0000ffff) - 0x7FFF;
     geom0 >>= 16;
     geom1 >>= 16;
     int w = geom0 & 0x0000ffff;
     int h = geom1 & 0x0000ffff;
     return QRect(x, y, w, h);
 }