Qt 4.8: /src/gui/widgets/qtoolbararealayout_p.h File Reference
qtoolbararealayout_p.h File Reference
#include <QList>
#include <QSize>
#include <QRect>
Classes
class QToolBarAreaLayout
class QToolBarAreaLayoutInfo
class QToolBarAreaLayoutItem
class QToolBarAreaLayoutLine
Functions
static int perp (Qt::Orientation o, const QPoint &pos)
static int perp (Qt::Orientation o, const QSize &size)
static int pick (Qt::Orientation o, const QPoint &pos)
static int pick (Qt::Orientation o, const QSize &size)
static QSizePolicy::Policy pick (Qt::Orientation o, const QSizePolicy &policy)
static int & rperp (Qt::Orientation o, QPoint &pos)
static int & rperp (Qt::Orientation o, QSize &size)
static int & rpick (Qt::Orientation o, QPoint &pos)
static int & rpick (Qt::Orientation o, QSize &size)
Function Documentation
perp() [1/2]
static int perp (Qt::Orientation o, const QPoint & pos) inline static
Definition at line 77 of file qtoolbararealayout_p.h.
 { return o == Qt::Vertical ? pos.x() : pos.y(); }
perp() [2/2]
static int perp (Qt::Orientation o, const QSize & size) inline static
Definition at line 80 of file qtoolbararealayout_p.h.
 { return o == Qt::Vertical ? size.width() : size.height(); }
pick() [1/3]
static int pick (Qt::Orientation o, const QPoint & pos) inline static
Definition at line 62 of file qtoolbararealayout_p.h.
Referenced by QToolBarAreaLayoutItem::extendSize(), and QToolBarAreaLayoutItem::resize().
 { return o == Qt::Horizontal ? pos.x() : pos.y(); }
pick() [2/3]
static int pick (Qt::Orientation o, const QSize & size) inline static
Definition at line 65 of file qtoolbararealayout_p.h.
 { return o == Qt::Horizontal ? size.width() : size.height(); }
pick() [3/3]
static QSizePolicy::Policy pick (Qt::Orientation o, const QSizePolicy & policy) inline static
Definition at line 74 of file qtoolbararealayout_p.h.
 { return o == Qt::Horizontal ? policy.horizontalPolicy() : policy.verticalPolicy(); }
rperp() [1/2]
static int& rperp (Qt::Orientation o, QPoint & pos) inline static
Definition at line 83 of file qtoolbararealayout_p.h.
Referenced by QToolBarLayout::expandedSize(), QDockAreaLayout::gapRect(), QDockAreaLayoutInfo::itemRect(), QToolBarLayout::layoutActions(), QDockAreaLayoutInfo::maximumSize(), QDockAreaLayoutInfo::minimumSize(), QToolBarAreaLayoutLine::minimumSize(), QToolBarAreaLayoutInfo::minimumSize(), QDockAreaLayoutInfo::plug(), QToolBarLayout::setGeometry(), QDockAreaLayoutInfo::sizeHint(), QToolBarAreaLayoutLine::sizeHint(), QToolBarAreaLayoutInfo::sizeHint(), and QToolBarLayout::updateGeomArray().
 { return o == Qt::Vertical ? pos.rx() : pos.ry(); }
rperp() [2/2]
static int& rperp (Qt::Orientation o, QSize & size) inline static
Definition at line 86 of file qtoolbararealayout_p.h.
 { return o == Qt::Vertical ? size.rwidth() : size.rheight(); }
rpick() [1/2]
static int& rpick (Qt::Orientation o, QPoint & pos) inline static
Definition at line 68 of file qtoolbararealayout_p.h.
Referenced by QToolBarLayout::expandedSize(), QDockAreaLayout::gapRect(), QDockAreaLayoutInfo::itemRect(), QToolBarLayout::layoutActions(), QDockAreaLayoutInfo::maximumSize(), QDockAreaLayoutInfo::minimumSize(), QToolBarAreaLayoutLine::minimumSize(), QToolBarAreaLayoutInfo::minimumSize(), QDockAreaLayoutInfo::plug(), QDockAreaLayoutInfo::separatorRect(), QToolBarLayout::setGeometry(), QDockAreaLayoutInfo::sizeHint(), QToolBarAreaLayoutLine::sizeHint(), QToolBarAreaLayoutInfo::sizeHint(), and QToolBarLayout::updateGeomArray().
 { return o == Qt::Horizontal ? pos.rx() : pos.ry(); }
rpick() [2/2]
static int& rpick (Qt::Orientation o, QSize & size) inline static
Definition at line 71 of file qtoolbararealayout_p.h.
 { return o == Qt::Horizontal ? size.rwidth() : size.rheight(); }