Qt 4.8: /src/corelib/tools/qtools_p.h File Reference
qtools_p.h File Reference
#include "QtCore/qglobal.h"
Functions
int Q_CORE_EXPORT qAllocMore (int alloc, int extra)
Function Documentation
qAllocMore()
int Q_CORE_EXPORT qAllocMore (int alloc, int extra)
Definition at line 70 of file qbytearray.cpp.
Referenced by QByteArray::append(), QFragmentMapData< QTextBlockData >::createFragment(), grow(), QVectorData::grow(), QString::grow(), and QByteArray::prepend().
 {
     Q_ASSERT(alloc >= 0 && extra >= 0);
     Q_ASSERT_X(alloc < (1 << 30) - extra, "qAllocMore", "Requested size is too large!");
     if (alloc == 0 && extra == 0)
         return 0;
     const int page = 1 << 12;
     int nalloc;
     alloc += extra;
     if (alloc < 1<<6) {
         nalloc = (1<<3) + ((alloc >>3) << 3);
     } else  {
         // don't do anything if the loop will overflow signed int.
         if (alloc >= INT_MAX/2)
             return INT_MAX;
         nalloc = (alloc < page) ? 1 << 3 : page;
         while (nalloc < alloc) {
             if (nalloc <= 0)
                 return INT_MAX;
             nalloc *= 2;
         }
     }
     return nalloc - extra;
 }