Qt 4.8: /src/gui/widgets/qtoolbar.cpp File Reference
qtoolbar.cpp File Reference
#include "qtoolbar.h"
#include <qapplication.h>
#include <qcombobox.h>
#include <qevent.h>
#include <qlayout.h>
#include <qmainwindow.h>
#include <qmenu.h>
#include <qmenubar.h>
#include <qrubberband.h>
#include <qsignalmapper.h>
#include <qstylepainter.h>
#include <qtoolbutton.h>
#include <qwidgetaction.h>
#include <qtimer.h>
#include <private/qwidgetaction_p.h>
#include <private/qt_mac_p.h>
#include <private/qt_cocoa_helpers_mac_p.h>
#include <private/qmainwindowlayout_p.h>
#include "qtoolbar_p.h"
#include "qtoolbarseparator_p.h"
#include "qtoolbarlayout_p.h"
#include "qdebug.h"
#include "moc_qtoolbar.cpp"
Macros
#define POPUP_TIMER_INTERVAL 500
Functions
static void qt_mac_updateToolBarButtonHint (QWidget *parentWidget)
QMainWindowLayout * qt_mainwindow_layout (const QMainWindow *window)
static bool toolbarInUnifiedToolBar (QToolBar *toolbar)
static bool waitForPopup (QToolBar *tb, QWidget *popup)
Macro Definition Documentation
POPUP_TIMER_INTERVAL
#define POPUP_TIMER_INTERVAL 500
Definition at line 73 of file qtoolbar.cpp.
Referenced by QToolBar::event().
Function Documentation
qt_mac_updateToolBarButtonHint()
static void qt_mac_updateToolBarButtonHint (QWidget * parentWidget) static
Definition at line 78 of file qtoolbar.cpp.
Referenced by QToolBar::event(), and QToolBarPrivate::init().
 {
     if (!(parentWidget->windowFlags() & Qt::CustomizeWindowHint))
         parentWidget->setWindowFlags(parentWidget->windowFlags() | Qt::MacWindowToolBarButtonHint);
 }
qt_mainwindow_layout()
QMainWindowLayout* qt_mainwindow_layout (const QMainWindow * window)
Definition at line 111 of file qmainwindow.cpp.
Referenced by QToolBarPrivate::endDrag(), QToolBar::event(), QToolBarPrivate::initDrag(), QToolBar::initStyleOption(), QToolBarPrivate::mouseMoveEvent(), qt_mac_updateToolBarButtonHint(), QToolBarPrivate::startDrag(), QToolBar::widgetForAction(), and QToolBar::~QToolBar().
 {
     return QMainWindowPrivate::mainWindowLayout(mainWindow);
 }
toolbarInUnifiedToolBar()
static bool toolbarInUnifiedToolBar (QToolBar * toolbar) static
Definition at line 1171 of file qtoolbar.cpp.
Referenced by QToolBar::event().
 {
     const QMainWindow *mainWindow = qobject_cast<const QMainWindow *>(toolbar->parentWidget());
     return mainWindow && mainWindow->unifiedTitleAndToolBarOnMac()
             && mainWindow->toolBarArea(toolbar) == Qt::TopToolBarArea;
 }
waitForPopup()
static bool waitForPopup (QToolBar * tb, QWidget * popup) static
Definition at line 1144 of file qtoolbar.cpp.
Referenced by QToolBar::event().
 {
     if (popup == 0 || popup->isHidden())
         return false;
     QWidget *w = popup;
     while (w != 0) {
         if (w == tb)
             return true;
         w = w->parentWidget();
     }
     QMenu *menu = qobject_cast<QMenu*>(popup);
     if (menu == 0)
         return false;
     QAction *action = menu->menuAction();
     QList<QWidget*> widgets = action->associatedWidgets();
     for (int i = 0; i < widgets.count(); ++i) {
         if (waitForPopup(tb, widgets.at(i)))
             return true;
     }
     return false;
 }