Qt 4.8: /src/gui/widgets/qtoolbarlayout.cpp File Reference
qtoolbarlayout.cpp File Reference
#include <qaction.h>
#include <qwidgetaction.h>
#include <qtoolbar.h>
#include <qstyleoption.h>
#include <qtoolbutton.h>
#include <qmenu.h>
#include <qdebug.h>
#include <qmath.h>
#include "qmainwindowlayout_p.h"
#include "qtoolbarextension_p.h"
#include "qtoolbarlayout_p.h"
#include "qtoolbarseparator_p.h"
Functions
static bool defaultWidgetAction (QToolBarItem *item)
QMainWindowLayout * qt_mainwindow_layout (const QMainWindow *window)
Function Documentation
defaultWidgetAction()
static bool defaultWidgetAction (QToolBarItem * item) static
Definition at line 352 of file qtoolbarlayout.cpp.
Referenced by QToolBarLayout::layoutActions().
 {
     QWidgetAction *a = qobject_cast<QWidgetAction*>(item->action);
     return a != 0 && a->defaultWidget() == item->widget();
 }
qt_mainwindow_layout()
QMainWindowLayout* qt_mainwindow_layout (const QMainWindow * window)
Definition at line 111 of file qmainwindow.cpp.
Referenced by QToolBarLayout::setExpanded(), and QToolBarLayout::setGeometry().
 {
     return QMainWindowPrivate::mainWindowLayout(mainWindow);
 }