Qt 4.8: /src/gui/painting/qtransform.h File Reference
qtransform.h File Reference
#include <QtGui/qmatrix.h>
#include <QtGui/qpainterpath.h>
#include <QtGui/qpolygon.h>
#include <QtGui/qregion.h>
#include <QtGui/qwindowdefs.h>
#include <QtCore/qline.h>
#include <QtCore/qpoint.h>
#include <QtCore/qrect.h>
Classes
class QTransform
The QTransform class specifies 2D transformations of a coordinate system.
Functions
Q_GUI_EXPORT_INLINE QPoint operator* (const QPoint &p, const QTransform &m)
Q_GUI_EXPORT_INLINE QPointF operator* (const QPointF &p, const QTransform &m)
Q_GUI_EXPORT_INLINE QLineF operator* (const QLineF &l, const QTransform &m)
Q_GUI_EXPORT_INLINE QLine operator* (const QLine &l, const QTransform &m)
Q_GUI_EXPORT_INLINE QPolygon operator* (const QPolygon &a, const QTransform &m)
Q_GUI_EXPORT_INLINE QPolygonF operator* (const QPolygonF &a, const QTransform &m)
Q_GUI_EXPORT_INLINE QRegion operator* (const QRegion &r, const QTransform &m)
Q_GUI_EXPORT_INLINE QPainterPath operator* (const QPainterPath &p, const QTransform &m)
Q_GUI_EXPORT_INLINE QTransform operator* (const QTransform &a, qreal n)
Q_GUI_EXPORT_INLINE QTransform operator+ (const QTransform &a, qreal n)
Q_GUI_EXPORT_INLINE QTransform operator- (const QTransform &a, qreal n)
Q_GUI_EXPORT_INLINE QTransform operator/ (const QTransform &a, qreal n)
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &, const QTransform &)
Q_GUI_EXPORT QDebug operator<< (QDebug, const QTransform &)
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &, QTransform &)
Q_DECLARE_TYPEINFO (QTransform, Q_MOVABLE_TYPE)
bool qFuzzyCompare (const QTransform &t1, const QTransform &t2)
Function Documentation
operator*() [1/9]
Q_GUI_EXPORT_INLINE QPoint operator* (const QPoint & p, const QTransform & m) related
Definition at line 365 of file qtransform.h.
Referenced by QTransform::QTransform().
 { return m.map(p); }
operator*() [2/9]
Q_GUI_EXPORT_INLINE QPointF operator* (const QPointF & p, const QTransform & m) related
Definition at line 367 of file qtransform.h.
 { return m.map(p); }
operator*() [3/9]
Q_GUI_EXPORT_INLINE QLineF operator* (const QLineF & l, const QTransform & m) related
Definition at line 369 of file qtransform.h.
 { return m.map(l); }
operator*() [4/9]
Q_GUI_EXPORT_INLINE QLine operator* (const QLine & l, const QTransform & m) related
Definition at line 371 of file qtransform.h.
 { return m.map(l); }
operator*() [5/9]
Q_GUI_EXPORT_INLINE QPolygon operator* (const QPolygon & a, const QTransform & m) related
Definition at line 373 of file qtransform.h.
 { return m.map(a); }
operator*() [6/9]
Q_GUI_EXPORT_INLINE QPolygonF operator* (const QPolygonF & a, const QTransform & m) related
Definition at line 375 of file qtransform.h.
 { return m.map(a); }
operator*() [7/9]
Q_GUI_EXPORT_INLINE QRegion operator* (const QRegion & r, const QTransform & m) related
Definition at line 377 of file qtransform.h.
 { return m.map(r); }
operator*() [8/9]
Q_GUI_EXPORT_INLINE QPainterPath operator* (const QPainterPath & p, const QTransform & m) related
Definition at line 379 of file qtransform.h.
 { return m.map(p); }
operator*() [9/9]
Q_GUI_EXPORT_INLINE QTransform operator* (const QTransform & a, qreal n)
Definition at line 382 of file qtransform.h.
 { QTransform t(a); t *= n; return t; }
operator+()
Q_GUI_EXPORT_INLINE QTransform operator+ (const QTransform & a, qreal n)
Definition at line 386 of file qtransform.h.
 { QTransform t(a); t += n; return t; }
operator-()
Q_GUI_EXPORT_INLINE QTransform operator- (const QTransform & a, qreal n)
Definition at line 388 of file qtransform.h.
 { QTransform t(a); t -= n; return t; }
operator/()
Q_GUI_EXPORT_INLINE QTransform operator/ (const QTransform & a, qreal n)
Definition at line 384 of file qtransform.h.
 { QTransform t(a); t /= n; return t; }
operator<<() [1/2]
Q_GUI_EXPORT QDataStream& operator<< (QDataStream & , const QTransform &) related
Definition at line 1064 of file qtransform.cpp.
Referenced by qFuzzyCompare().
 {
     s << double(m.m11())
       << double(m.m12())
       << double(m.m13())
       << double(m.m21())
       << double(m.m22())
       << double(m.m23())
       << double(m.m31())
       << double(m.m32())
       << double(m.m33());
     return s;
 }
operator<<() [2/2]
Q_GUI_EXPORT QDebug operator<< (QDebug , const QTransform &)
Definition at line 1115 of file qtransform.cpp.
 {
     static const char *typeStr[] =
     {
         "TxNone",
         "TxTranslate",
         "TxScale",
         0,
         "TxRotate",
         0, 0, 0,
         "TxShear",
         0, 0, 0, 0, 0, 0, 0,
         "TxProject"
     };
     dbg.nospace() << "QTransform(type=" << typeStr[m.type()] << ','
                   << " 11=" << m.m11()
                   << " 12=" << m.m12()
                   << " 13=" << m.m13()
                   << " 21=" << m.m21()
                   << " 22=" << m.m22()
                   << " 23=" << m.m23()
                   << " 31=" << m.m31()
                   << " 32=" << m.m32()
                   << " 33=" << m.m33()
                   << ')';
     return dbg.space();
 }
operator>>()
Q_GUI_EXPORT QDataStream& operator>> (QDataStream & , QTransform &) related
Definition at line 1091 of file qtransform.cpp.
Referenced by qFuzzyCompare().
 {
      double m11, m12, m13,
          m21, m22, m23,
          m31, m32, m33;
      s >> m11;
      s >> m12;
      s >> m13;
      s >> m21;
      s >> m22;
      s >> m23;
      s >> m31;
      s >> m32;
      s >> m33;
      t.setMatrix(m11, m12, m13,
                  m21, m22, m23,
                  m31, m32, m33);
      return s;
 }
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QTransform , Q_MOVABLE_TYPE)
qFuzzyCompare()
bool qFuzzyCompare (const QTransform & t1, const QTransform & t2) related
Definition at line 339 of file qtransform.h.
 {
     return qFuzzyCompare(t1.m11(), t2.m11())
         && qFuzzyCompare(t1.m12(), t2.m12())
         && qFuzzyCompare(t1.m13(), t2.m13())
         && qFuzzyCompare(t1.m21(), t2.m21())
         && qFuzzyCompare(t1.m22(), t2.m22())
         && qFuzzyCompare(t1.m23(), t2.m23())
         && qFuzzyCompare(t1.m31(), t2.m31())
         && qFuzzyCompare(t1.m32(), t2.m32())
         && qFuzzyCompare(t1.m33(), t2.m33());
 }