Qt 4.8: /src/gui/embedded/qtransportauth_qws.cpp File Reference
qtransportauth_qws.cpp File Reference
#include "qtransportauth_qws.h"
#include "qtransportauth_qws_p.h"
#include "../../3rdparty/md5/md5.h"
#include "../../3rdparty/md5/md5.cpp"
#include "qwsutils_qws.h"
#include "qwssocket_qws.h"
#include "qwscommand_qws_p.h"
#include "qwindowsystem_qws.h"
#include "qbuffer.h"
#include "qthread.h"
#include "qabstractsocket.h"
#include "qlibraryinfo.h"
#include "qfile.h"
#include "qdebug.h"
#include <private/qcore_unix_p.h>
#include <syslog.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/file.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <time.h>
#include <QtCore/qcache.h>
#include "moc_qtransportauth_qws_p.cpp"
Macros
#define BUF_SIZE 512
#define KEY_CACHE_SIZE 30
Functions
bool __fileOpen (QFile *f)
Q_GUI_EXPORT void * guaranteed_memset (void *v, int c, size_t n)
static int hmac_md5 (unsigned char *text, int text_length, const unsigned char *key, int key_length, unsigned char *digest)
Variables
const char *const errorStrings []
Macro Definition Documentation
BUF_SIZE
#define BUF_SIZE 512
Definition at line 75 of file qtransportauth_qws.cpp.
Referenced by QTransportAuth::authorizeRequest(), and QX11PaintEngine::drawPoints().
KEY_CACHE_SIZE
#define KEY_CACHE_SIZE 30
Definition at line 145 of file qtransportauth_qws.cpp.
Function Documentation
__fileOpen()
bool __fileOpen (QFile * f) inline
Definition at line 607 of file qtransportauth_qws.cpp.
Referenced by QTransportAuthPrivate::getClientKey().
 {
 #ifdef QTRANSPORTAUTH_DEBUG
     if ( f->open( QIODevice::ReadOnly ))
     {
         qDebug( "Opened file: %s\n", qPrintable( f->fileName() ));
         return true;
     }
     else
     {
         qWarning( "Could not open file: %s\n", qPrintable( f->fileName() ));
         return false;
     }
 #else
     return ( f->open( QIODevice::ReadOnly ));
 #endif
 }
guaranteed_memset()
Q_GUI_EXPORT void* guaranteed_memset (void * v, int c, size_t n)
Warning
This function is not part of the public interface. memset for security purposes, guaranteed not to be optimized away http://www.faqs.org/docs/Linux-HOWTO/Secure-Programs-HOWTO.html
Definition at line 84 of file qtransportauth_qws.cpp.
 {
     volatile char *p = (char *)v; while (n--) *p++=c; return v;
 }
hmac_md5()
static int hmac_md5 (unsigned char * text, int text_length, const unsigned char * key, int key_length, unsigned char * digest) static
Definition at line 1466 of file qtransportauth_qws.cpp.
Referenced by QTransportAuth::authFromMessage(), QTransportAuth::authToMessage(), and guaranteed_memset().
 {
         MD5Context context;
         unsigned char k_ipad[65];    /* inner padding - * key XORd with ipad */
         unsigned char k_opad[65];    /* outer padding - * key XORd with opad */
         int i;
         /* in this implementation key_length == 16 */
         if ( key_length != 16 )
         {
             fprintf( stderr, "Key length was %d - must be 16 bytes", key_length );
             return 0;
         }
         /* start out by storing key in pads */
         memset( k_ipad, 0, sizeof k_ipad );
         memset( k_opad, 0, sizeof k_opad );
         memcpy( k_ipad, key, key_length );
         memcpy( k_opad, key, key_length );
         /* XOR key with ipad and opad values */
         for (i=0; i<64; i++) {
                 k_ipad[i] ^= 0x36;
                 k_opad[i] ^= 0x5c;
         }
         /* perform inner MD5 */
         MD5Init(&context);                   /* init context for 1st pass */
         MD5Update(&context, k_ipad, 64);     /* start with inner pad */
         MD5Update(&context, text, text_length); /* then text of datagram */
         MD5Final(&context, digest);          /* finish up 1st pass */
         /* perform outer MD5 */
         MD5Init(&context);                   /* init context for 2nd pass */
         MD5Update(&context, k_opad, 64);     /* start with outer pad */
         MD5Update(&context, digest, 16);     /* then results of 1st * hash */
         MD5Final(&context, digest);          /* finish up 2nd pass */
         return 1;
 }
Variable Documentation
errorStrings
const char* const errorStrings[]
Initial value:
= {
    "pending identity verification",
    "message too small to carry auth data",
    "cache miss on connection oriented transport",
    "no magic bytes on message",
    "key not found for prog id",
    "authorization key match failed",
    "key out of date"
}
Definition at line 147 of file qtransportauth_qws.cpp.
Referenced by QTransportAuth::errorString().