Qt 4.8: /src/corelib/kernel/qtranslator.cpp File Reference
qtranslator.cpp File Reference
#include "qplatformdefs.h"
#include "qtranslator.h"
#include "qfileinfo.h"
#include "qstring.h"
#include "qstringlist.h"
#include "qcoreapplication.h"
#include "qcoreapplication_p.h"
#include "qdatastream.h"
#include "qdir.h"
#include "qfile.h"
#include "qmap.h"
#include "qalgorithms.h"
#include "qhash.h"
#include "qtranslator_p.h"
#include "qlocale.h"
#include "qresource.h"
#include "private/qcore_unix_p.h"
#include <sys/mman.h>
#include <errno.h>
#include <stdlib.h>
#include "qobject_p.h"
Classes
class QTranslatorPrivate
Macros
#define CHECK_RANGE
#define MAP_FAILED -1
#define MAP_FILE 0
#define QT_USE_MMAP
Enumerations
enum Tag {
Tag_End = 1, Tag_SourceText16, Tag_Translation, Tag_Context16,
Tag_Obsolete1, Tag_SourceText, Tag_Context, Tag_Comment,
Tag_Obsolete2
}
Functions
static uint elfHash (const char *name)
static QString find_translation (const QLocale &locale, const QString &filename, const QString &prefix, const QString &directory, const QString &suffix)
static QString getMessage (const uchar *m, const uchar *end, const char *context, const char *sourceText, const char *comment, int numerus)
static bool match (const uchar *found, const char *target, uint len)
static int numerusHelper (int n, const uchar *rules, int rulesSize)
static quint16 read16 (const uchar *data)
static quint32 read32 (const uchar *data)
static quint8 read8 (const uchar *data)
Variables
static const uchar magic [MagicLength]
static const int MagicLength = 16
Macro Definition Documentation
CHECK_RANGE
#define CHECK_RANGE
Value:
do { \
        if (i >= rulesSize) \
            return -1; \
    } while (0)
Referenced by numerusHelper().
MAP_FAILED
#define MAP_FAILED -1
Referenced by QTranslatorPrivate::do_load().
MAP_FILE
#define MAP_FILE 0
Referenced by QTranslatorPrivate::do_load().
QT_USE_MMAP
#define QT_USE_MMAP
Definition at line 64 of file qtranslator.cpp.
Enumeration Type Documentation
Tag
enum Tag
Enumerator
Tag_End
Tag_SourceText16
Tag_Translation
Tag_Context16
Tag_Obsolete1
Tag_SourceText
Tag_Context
Tag_Comment
Tag_Obsolete2
Definition at line 86 of file qtranslator.cpp.
          { Tag_End = 1, Tag_SourceText16, Tag_Translation, Tag_Context16, Tag_Obsolete1,
            Tag_SourceText, Tag_Context, Tag_Comment, Tag_Obsolete2 };
Function Documentation
elfHash()
static uint elfHash (const char * name) static
Definition at line 110 of file qtranslator.cpp.
Referenced by QTranslatorPrivate::do_translate().
 {
     const uchar *k;
     uint h = 0;
     uint g;
     if (name) {
         k = (const uchar *) name;
         while (*k) {
             h = (h << 4) + *k++;
             if ((g = (h & 0xf0000000)) != 0)
                 h ^= g >> 24;
             h &= ~g;
         }
     }
     if (!h)
         h = 1;
     return h;
 }
find_translation()
static QString find_translation (const QLocale & locale, const QString & filename, const QString & prefix, const QString & directory, const QString & suffix) static
Definition at line 586 of file qtranslator.cpp.
Referenced by QTranslator::load().
 {
     QString path;
     if (QFileInfo(filename).isRelative()) {
         path = directory;
         if (!path.isEmpty() && !path.endsWith(QLatin1Char('/')))
             path += QLatin1Char('/');
     }
     QFileInfo fi;
     QString realname;
     QStringList fuzzyLocales;
     // see http://www.unicode.org/reports/tr35/#LanguageMatching for inspiration
     QStringList languages = locale.uiLanguages();
 #if defined(Q_OS_UNIX) && !defined(Q_OS_SYMBIAN)
     for (int i = languages.size()-1; i >= 0; --i) {
         QString lang = languages.at(i);
         QString lowerLang = lang.toLower();
         if (lang != lowerLang)
             languages.insert(i+1, lowerLang);
     }
 #endif
     // try explicit locales names first
     foreach (QString localeName, languages) {
         localeName.replace(QLatin1Char('-'), QLatin1Char('_'));
         realname = path + filename + prefix + localeName + (suffix.isNull() ? QLatin1String(".qm") : suffix);
         fi.setFile(realname);
         if (fi.isReadable() && fi.isFile())
             return realname;
         realname = path + filename + prefix + localeName;
         fi.setFile(realname);
         if (fi.isReadable() && fi.isFile())
             return realname;
         fuzzyLocales.append(localeName);
     }
     // start guessing
     foreach (QString localeName, fuzzyLocales) {
         for (;;) {
             int rightmost = localeName.lastIndexOf(QLatin1Char('_'));
             // no truncations? fail
             if (rightmost <= 0)
                 break;
             localeName.truncate(rightmost);
             realname = path + filename + prefix + localeName + (suffix.isNull() ? QLatin1String(".qm") : suffix);
             fi.setFile(realname);
             if (fi.isReadable() && fi.isFile())
                 return realname;
             realname = path + filename + prefix + localeName;
             fi.setFile(realname);
             if (fi.isReadable() && fi.isFile())
                 return realname;
         }
     }
     if (!suffix.isNull()) {
         realname = path + filename + suffix;
         fi.setFile(realname);
         if (fi.isReadable() && fi.isFile())
             return realname;
     }
     realname = path + filename + prefix;
     fi.setFile(realname);
     if (fi.isReadable() && fi.isFile())
         return realname;
     realname = path + filename;
     fi.setFile(realname);
     if (fi.isReadable() && fi.isFile())
         return realname;
     return QString();
 }
getMessage()
static QString getMessage (const uchar * m, const uchar * end, const char * context, const char * sourceText, const char * comment, int numerus) static
Definition at line 806 of file qtranslator.cpp.
Referenced by QTranslatorPrivate::do_translate().
 {
     const uchar *tn = 0;
     uint tn_length = 0;
     int currentNumerus = -1;
     for (;;) {
         uchar tag = 0;
         if (m < end)
             tag = read8(m++);
         switch((Tag)tag) {
         case Tag_End:
             goto end;
         case Tag_Translation: {
             int len = read32(m);
             if (len % 1)
                 return QString();
             m += 4;
             if (++currentNumerus == numerus) {
                 tn_length = len;
                 tn = m;
             }
             m += len;
             break;
         }
         case Tag_Obsolete1:
             m += 4;
             break;
         case Tag_SourceText: {
             quint32 len = read32(m);
             m += 4;
             if (!match(m, sourceText, len))
                 return QString();
             m += len;
         }
             break;
         case Tag_Context: {
             quint32 len = read32(m);
             m += 4;
             if (!match(m, context, len))
                 return QString();
             m += len;
         }
             break;
         case Tag_Comment: {
             quint32 len = read32(m);
             m += 4;
             if (*m && !match(m, comment, len))
                 return QString();
             m += len;
         }
             break;
         default:
             return QString();
         }
     }
 end:
     if (!tn)
         return QString();
     QString str = QString((const QChar *)tn, tn_length/2);
     if (QSysInfo::ByteOrder == QSysInfo::LittleEndian) {
         for (int i = 0; i < str.length(); ++i)
             str[i] = QChar((str.at(i).unicode() >> 8) + ((str.at(i).unicode() << 8) & 0xff00));
     }
     return str;
 }
match()
static bool match (const uchar * found, const char * target, uint len) static
Definition at line 101 of file qtranslator.cpp.
Referenced by QDBusAbstractInterface::callWithArgumentList(), QTranslatorPrivate::do_translate(), QRegExpMatchState::drain(), findEncoding(), QFontDatabase::findFont(), getFcPattern(), QGraphicsAnchorLayoutPrivate::getGraphParts(), getMessage(), QTreeView::keyboardSearch(), QAbstractItemView::keyboardSearch(), QFontEngineMultiFT::loadEngine(), loadFc(), loadWin(), QFontDatabase::loadXlfd(), QResourceRoot::mappingRoot(), QShortcutMap::matches(), QKeySequence::matches(), QRegExpAutomatonState::QRegExpAutomatonState(), registerFont(), QCss::StyleSelector::selectorMatches(), QEglContext::setApi(), QAbstractItemModel::sibling(), and QDir::temp().
 {
     // catch the case if \a found has a zero-terminating symbol and \a len includes it.
     // (normalize it to be without the zero-terminating symbol)
     if (len > 0 && found[len-1] == '\0')
         --len;
     return (memcmp(found, target, len) == 0 && target[len] == '\0');
 }
numerusHelper()
static int numerusHelper (int n, const uchar * rules, int rulesSize) static
Definition at line 130 of file qtranslator.cpp.
Referenced by QTranslatorPrivate::do_translate().
 {
 #define CHECK_RANGE \
     do { \
         if (i >= rulesSize) \
             return -1; \
     } while (0)
     int result = 0;
     int i = 0;
     if (rulesSize == 0)
         return 0;
     for (;;) {
         bool orExprTruthValue = false;
         for (;;) {
             bool andExprTruthValue = true;
             for (;;) {
                 bool truthValue = true;
                 CHECK_RANGE;
                 int opcode = rules[i++];
                 int leftOperand = n;
                 if (opcode & Q_MOD_10) {
                     leftOperand %= 10;
                 } else if (opcode & Q_MOD_100) {
                     leftOperand %= 100;
                 } else if (opcode & Q_LEAD_1000) {
                     while (leftOperand >= 1000)
                         leftOperand /= 1000;
                 }
                 int op = opcode & Q_OP_MASK;
                 CHECK_RANGE;
                 int rightOperand = rules[i++];
                 switch (op) {
                 default:
                     return -1;
                 case Q_EQ:
                     truthValue = (leftOperand == rightOperand);
                     break;
                 case Q_LT:
                     truthValue = (leftOperand < rightOperand);
                     break;
                 case Q_LEQ:
                     truthValue = (leftOperand <= rightOperand);
                     break;
         case Q_BETWEEN:
                     int bottom = rightOperand;
                     CHECK_RANGE;
                     int top = rules[i++];
                     truthValue = (leftOperand >= bottom && leftOperand <= top);
                 }
                 if (opcode & Q_NOT)
                     truthValue = !truthValue;
                 andExprTruthValue = andExprTruthValue && truthValue;
                 if (i == rulesSize || rules[i] != Q_AND)
                     break;
                 ++i;
             }
             orExprTruthValue = orExprTruthValue || andExprTruthValue;
             if (i == rulesSize || rules[i] != Q_OR)
                 break;
             ++i;
         }
         if (orExprTruthValue)
             return result;
         ++result;
         if (i == rulesSize)
             return result;
         if (rules[i++] != Q_NEWRULE)
             break;
     }
     return -1;
 }
read16()
static quint16 read16 (const uchar * data) static
Definition at line 752 of file qtranslator.cpp.
Referenced by QTranslatorPrivate::do_translate().
 {
     return (data[0] << 8) | (data[1]);
 }
read32()
static quint32 read32 (const uchar * data) static
Definition at line 757 of file qtranslator.cpp.
Referenced by QTranslatorPrivate::do_load(), QTranslatorPrivate::do_translate(), and getMessage().
 {
     return (data[0] << 24)
         | (data[1] << 16)
         | (data[2] << 8)
         | (data[3]);
 }
read8()
static quint8 read8 (const uchar * data) static
Definition at line 747 of file qtranslator.cpp.
Referenced by QTranslatorPrivate::do_load(), QTranslatorPrivate::do_translate(), and getMessage().
 {
     return *data;
 }
Variable Documentation
magic
const uchar magic[MagicLength] static
Initial value:
= {
    0x3c, 0xb8, 0x64, 0x18, 0xca, 0xef, 0x9c, 0x95,
    0xcd, 0x21, 0x1c, 0xbf, 0x60, 0xa1, 0xbd, 0xdd
}
Definition at line 96 of file qtranslator.cpp.
Referenced by QTranslatorPrivate::do_load().
MagicLength
const int MagicLength = 16 static
Definition at line 95 of file qtranslator.cpp.
Referenced by QTranslatorPrivate::do_load().