Qt 4.8: /src/opengl/gl2paintengineex/qtriangulatingstroker.cpp File Reference
qtriangulatingstroker.cpp File Reference
#include "qtriangulatingstroker_p.h"
#include <qmath.h>
Macros
#define CURVE_FLATNESS Q_PI / 8
Functions
static void qdashprocessor_cubicTo (qreal, qreal, qreal, qreal, qreal, qreal, void *)
static void qdashprocessor_lineTo (qreal x, qreal y, void *data)
static void qdashprocessor_moveTo (qreal x, qreal y, void *data)
Macro Definition Documentation
CURVE_FLATNESS
#define CURVE_FLATNESS Q_PI / 8
Definition at line 47 of file qtriangulatingstroker.cpp.
Referenced by QTriangulatingStroker::process(), and QDashedStrokeProcessor::process().
Function Documentation
qdashprocessor_cubicTo()
static void qdashprocessor_cubicTo (qreal , qreal , qreal , qreal , qreal , qreal , void *) static
Definition at line 478 of file qtriangulatingstroker.cpp.
Referenced by QDashedStrokeProcessor::QDashedStrokeProcessor().
 {
     Q_ASSERT(0); // The dasher should not produce curves...
 }
qdashprocessor_lineTo()
static void qdashprocessor_lineTo (qreal x, qreal y, void * data) static
Definition at line 473 of file qtriangulatingstroker.cpp.
Referenced by QDashedStrokeProcessor::QDashedStrokeProcessor().
 {
     ((QDashedStrokeProcessor *) data)->addElement(QPainterPath::LineToElement, x, y);
 }
qdashprocessor_moveTo()
static void qdashprocessor_moveTo (qreal x, qreal y, void * data) static
Definition at line 468 of file qtriangulatingstroker.cpp.
Referenced by QDashedStrokeProcessor::QDashedStrokeProcessor().
 {
     ((QDashedStrokeProcessor *) data)->addElement(QPainterPath::MoveToElement, x, y);
 }