Qt 4.8: /src/corelib/codecs/qtsciicodec.cpp File Reference
qtsciicodec.cpp File Reference
#include "qtsciicodec_p.h"
#include "qlist.h"
Macros
#define IsTSCIIChar(c) (((c) >= 0x80) && ((c) <= 0xfd))
Functions
static int cmp (const ushort *s1, const ushort *s2, size_t len)
static unsigned int qt_TSCIIToUnicode (unsigned int code, uint *s)
static unsigned char qt_UnicodeToTSCII (ushort u1, ushort u2, ushort u3)
Variables
static const ushort TsToUn [][3]
static const ushort UnToTs [][4]
static const int UnToTsLast = 124
Macro Definition Documentation
IsTSCIIChar
#define IsTSCIIChar (c) (((c) >= 0x80) && ((c) <= 0xfd))
Definition at line 56 of file qtsciicodec.cpp.
Referenced by QTsciiCodec::convertToUnicode().
Function Documentation
cmp()
static int cmp (const ushort * s1, const ushort * s2, size_t len) static
Definition at line 446 of file qtsciicodec.cpp.
Referenced by detectProcessorFeatures(), QTriangulator< T >::SimpleToMonotone::fillPriorityQueue(), QSortedModelEngine::filter(), QVariant::operator!=(), QTriangulator< T >::ComplexToSimple::CompareEdges::operator()(), QVariant::operator==(), qt_UnicodeToTSCII(), ucstrcmp(), and winLangCodeToIsoName().
 {
     int diff = 0;
     while (len-- && (diff = *s1++ - *s2++) == 0)
         ;
     return diff;
 }
qt_TSCIIToUnicode()
static unsigned int qt_TSCIIToUnicode (unsigned int code, uint * s) static
Definition at line 484 of file qtsciicodec.cpp.
Referenced by QTsciiCodec::convertToUnicode().
 {
     int len = 0;
     for (int i = 0; i < 3; i++) {
         uint u = TsToUn[code & 0x7f][i];
         s[i] = u;
         if (s[i]) len = i + 1;
     }
     return len;
 }
qt_UnicodeToTSCII()
static unsigned char qt_UnicodeToTSCII (ushort u1, ushort u2, ushort u3) static
Definition at line 456 of file qtsciicodec.cpp.
Referenced by QTsciiCodec::convertFromUnicode().
 {
     ushort s[3];
     s[0] = u1;
     s[1] = u2;
     s[2] = u3;
     int a = 0;  // start pos
     int b = UnToTsLast; // end pos
     // do a binary search for the composed unicode in the list
     while (a <= b) {
         int w = (a + b) / 2;
         int j = cmp(UnToTs[w], s, 3);
         if (j == 0)
             // found it
             return UnToTs[w][3];
         if (j < 0)
             a = w + 1;
         else
             b = w - 1;
     }
     return 0;
 }
Variable Documentation
TsToUn
const ushort TsToUn[][3] static
Definition at line 316 of file qtsciicodec.cpp.
Referenced by qt_TSCIIToUnicode().
UnToTs
const ushort UnToTs[][4] static
Definition at line 186 of file qtsciicodec.cpp.
Referenced by qt_UnicodeToTSCII().
UnToTsLast
const int UnToTsLast = 124 static
Definition at line 185 of file qtsciicodec.cpp.
Referenced by qt_UnicodeToTSCII().