Qt 4.8: /src/plugins/platforms/uikit/quikitwindow.mm File Reference
quikitwindow.mm File Reference
#import <QuartzCore/CAEAGLLayer.h>
#include "quikitwindow.h"
#include "quikitscreen.h"
#include <QtDebug>
#include <QtGui/QApplication>
#include <QtGui/QKeyEvent>
#include <QtGui/QPlatformGLContext>
#include <QtGui/QWindowSystemInterface>
Classes
class EAGLPlatformContext
Functions
static GLint depthBits ()
static GLint stencilBits ()
Function Documentation
depthBits()
static GLint depthBits () static
Definition at line 67 of file quikitwindow.mm.
Referenced by EAGLPlatformContext::EAGLPlatformContext().
 {
     // we can choose between GL_DEPTH24_STENCIL8_OES and GL_DEPTH_COMPONENT16
     return stencilBits() > 0 ? 24 : 16;
 }
stencilBits()
static GLint stencilBits () static
Definition at line 56 of file quikitwindow.mm.
Referenced by depthBits(), and EAGLPlatformContext::EAGLPlatformContext().
 {
     static GLint bits;
     static bool initialized = false;
     if (!initialized) {
         glGetIntegerv(GL_STENCIL_BITS, &bits);
         initialized = true;
     }
     return bits;
 }