Qt 4.8: /src/corelib/tools/qunicodetables.cpp File Reference
qunicodetables.cpp File Reference
Classes
struct NormalizationCorrection
Namespaces
QUnicodeTables
Macros
#define GET_DECOMPOSITION_INDEX(ucs4)
#define GET_LIGATURE_INDEX(u2) (u2 < 0x3100 ? uc_ligature_trie[uc_ligature_trie[u2>>5] + (u2 & 0x1f)] : 0xffff);
#define GET_PROP_INDEX(ucs4)
#define GET_PROP_INDEX_UCS2(ucs2) (uc_property_trie[uc_property_trie[ucs2>>5] + (ucs2 & 0x1f)])
#define SPECIAL_CASE_MAX_LEN 3
Enumerations
enum { NumNormalizationCorrections = 6 }
enum { UnicodeBlockCount = 512 }
enum { UnicodeBlockSize = 128 }
Functions
static const QUnicodeTables::Properties * qGetProp (uint ucs4)
static const QUnicodeTables::Properties * qGetProp (ushort ucs2)
Variables
static const ushort specialCaseMap []
static const unsigned short uc_decomposition_map []
static const unsigned short uc_decomposition_trie []
static const unsigned short uc_ligature_map []
static const unsigned short uc_ligature_trie []
static const NormalizationCorrection uc_normalization_corrections []
static const QUnicodeTables::Properties uc_properties []
static const unsigned short uc_property_trie []
static const unsigned char QUnicodeTables::uc_scripts []
Macro Definition Documentation
GET_DECOMPOSITION_INDEX
#define GET_DECOMPOSITION_INDEX (ucs4)
Value:
(ucs4 < 0x3400 \
        ? (uc_decomposition_trie[uc_decomposition_trie[ucs4>>4] + (ucs4 & 0xf)]) \
        : (ucs4 < 0x30000\
           ? uc_decomposition_trie[uc_decomposition_trie[((ucs4 - 0x3400)>>8) + 0x340] + (ucs4 & 0xff)]\
           : 0xffff))
Definition at line 5899 of file qunicodetables.cpp.
Referenced by decompositionHelper(), and QChar::decompositionTag().
GET_LIGATURE_INDEX
#define GET_LIGATURE_INDEX (u2) (u2 < 0x3100 ? uc_ligature_trie[uc_ligature_trie[u2>>5] + (u2 & 0x1f)] : 0xffff);
Definition at line 7772 of file qunicodetables.cpp.
Referenced by ligatureHelper().
GET_PROP_INDEX
#define GET_PROP_INDEX (ucs4)
Value:
(ucs4 < 0x11000 \
        ? (uc_property_trie[uc_property_trie[ucs4>>5] + (ucs4 & 0x1f)]) \
        : (uc_property_trie[uc_property_trie[((ucs4 - 0x11000)>>8) + 0x880] + (ucs4 & 0xff)]))
Definition at line 3419 of file qunicodetables.cpp.
Referenced by QUnicodeTables::properties(), and qGetProp().
GET_PROP_INDEX_UCS2
#define GET_PROP_INDEX_UCS2 (ucs2) (uc_property_trie[uc_property_trie[ucs2>>5] + (ucs2 & 0x1f)])
Definition at line 3424 of file qunicodetables.cpp.
Referenced by QUnicodeTables::properties(), and qGetProp().
SPECIAL_CASE_MAX_LEN
#define SPECIAL_CASE_MAX_LEN 3
Definition at line 4452 of file qunicodetables.cpp.
Referenced by QString::toLower(), and QString::toUpper().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NumNormalizationCorrections
Definition at line 8032 of file qunicodetables.cpp.
 { NumNormalizationCorrections = 6 };
anonymous enum
anonymous enum
Enumerator
UnicodeBlockCount
Definition at line 8034 of file qunicodetables.cpp.
 { UnicodeBlockCount = 512 }; // number of unicode blocks
anonymous enum
anonymous enum
Enumerator
UnicodeBlockSize
Definition at line 8035 of file qunicodetables.cpp.
 { UnicodeBlockSize = 128 }; // size of each block
Function Documentation
qGetProp() [1/2]
static const QUnicodeTables::Properties* qGetProp (uint ucs4) inline static
Definition at line 4325 of file qunicodetables.cpp.
Referenced by canonicalOrderHelper(), QChar::category(), QChar::combiningClass(), composeHelper(), QChar::digitValue(), QChar::direction(), foldCase(), QChar::hasMirrored(), QChar::isDigit(), QChar::isLetter(), QChar::isLetterOrNumber(), QChar::isMark(), QChar::isNumber(), QChar::isPrint(), QChar::isPunct(), QChar::isSpace(), QChar::isSymbol(), QChar::joining(), QUnicodeTables::lineBreakClass(), QChar::mirroredChar(), QChar::toCaseFolded(), QChar::toLower(), QString::toLower(), QChar::toTitleCase(), QChar::toUpper(), QString::toUpper(), and QChar::unicodeVersion().
 {
     int index = GET_PROP_INDEX(ucs4);
     return uc_properties + index;
 }
qGetProp() [2/2]
static const QUnicodeTables::Properties* qGetProp (ushort ucs2) inline static
Definition at line 4331 of file qunicodetables.cpp.
 {
     int index = GET_PROP_INDEX_UCS2(ucs2);
     return uc_properties + index;
 }
Variable Documentation
specialCaseMap
const ushort specialCaseMap[] static
Definition at line 4354 of file qunicodetables.cpp.
Referenced by QString::toLower(), and QString::toUpper().
uc_decomposition_map
const unsigned short uc_decomposition_map[] static
Definition at line 5906 of file qunicodetables.cpp.
Referenced by decompositionHelper(), and QChar::decompositionTag().
uc_decomposition_trie
const unsigned short uc_decomposition_trie[] static
Definition at line 4454 of file qunicodetables.cpp.
uc_ligature_map
const unsigned short uc_ligature_map[] static
Definition at line 7774 of file qunicodetables.cpp.
Referenced by ligatureHelper().
uc_ligature_trie
const unsigned short uc_ligature_trie[] static
Definition at line 7614 of file qunicodetables.cpp.
uc_normalization_corrections
const NormalizationCorrection uc_normalization_corrections[] static
Initial value:
= {
    { 0xf951, 0x96fb, 6 },
    { 0x2f868, 0x2136a, 7 },
    { 0x2f874, 0x5f33, 7 },
    { 0x2f91f, 0x43ab, 7 },
    { 0x2f95f, 0x7aae, 7 },
    { 0x2f9bf, 0x4d57, 7 },
}
Definition at line 8023 of file qunicodetables.cpp.
Referenced by qt_string_normalize().
uc_properties
const QUnicodeTables::Properties uc_properties[] static
Definition at line 3427 of file qunicodetables.cpp.
uc_property_trie
const unsigned short uc_property_trie[] static
Definition at line 46 of file qunicodetables.cpp.