Qt 4.8: /src/corelib/io/qurl.h File Reference
qurl.h File Reference
#include <QtCore/qbytearray.h>
#include <QtCore/qobjectdefs.h>
#include <QtCore/qpair.h>
#include <QtCore/qstring.h>
#include <QtCore/qhash.h>
Classes
class QUrl
The QUrl class provides a convenient interface for working with URLs.
Functions
Q_CORE_EXPORT QDataStream & operator<< (QDataStream &, const QUrl &)
Q_CORE_EXPORT QDebug operator<< (QDebug, const QUrl &)
Q_CORE_EXPORT QDataStream & operator>> (QDataStream &, QUrl &)
Q_DECLARE_TYPEINFO (QUrl, Q_MOVABLE_TYPE)
uint qHash (const QUrl &url)
Function Documentation
operator<<() [1/2]
Q_CORE_EXPORT QDataStream& operator<< (QDataStream & , const QUrl &) related
Referenced by qHash().
operator<<() [2/2]
Q_CORE_EXPORT QDebug operator<< (QDebug , const QUrl &)
Definition at line 6784 of file qurl.cpp.
 {
     d.maybeSpace() << "QUrl(" << url.toString() << ')';
     return d.space();
 }
operator>>()
Q_CORE_EXPORT QDataStream& operator>> (QDataStream & , QUrl &) related
Referenced by qHash().
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QUrl , Q_MOVABLE_TYPE)
Referenced by qHash().
qHash()
uint qHash (const QUrl & url) related
Definition at line 285 of file qurl.h.
 {
     return qHash(url.toEncoded(QUrl::FormattingOption(0x100)));
 }