Qt 4.8: /src/corelib/plugin/quuid.cpp File Reference
quuid.cpp File Reference
#include "quuid.h"
#include "qdatastream.h"
#include "qendian.h"
#include "qdatetime.h"
#include "qfile.h"
#include "qthreadstorage.h"
#include <stdlib.h>
Macros
#define ISLESS(f1, f2) if (f1!=f2) return (f1<f2);
#define ISMORE(f1, f2) if (f1!=f2) return (f1>f2);
Functions
template<class Char , class Integral >
bool _q_fromHex (const Char *&src, Integral &value)
template<class Char , class Integral >
void _q_toHex (Char *&dst, Integral value)
template<class Char >
bool _q_uuidFromHex (const Char *&src, uint &d1, ushort &d2, ushort &d3, uchar(&d4)[8])
template<class Char >
void _q_uuidToHex (Char *&dst, const uint &d1, const ushort &d2, const ushort &d3, const uchar(&d4)[8])
Q_GLOBAL_STATIC (QThreadStorage< QFile *>, devUrandomStorage)
Macro Definition Documentation
ISLESS
#define ISLESS (f1, f2) if (f1!=f2) return (f1<f2);
Definition at line 806 of file quuid.cpp.
Referenced by QUuid::operator<().
ISMORE
#define ISMORE (f1, f2) if (f1!=f2) return (f1>f2);
Definition at line 835 of file quuid.cpp.
Referenced by QUuid::operator>().
Function Documentation
_q_fromHex()
template<class Char , class Integral > bool _q_fromHex (const Char *& src, Integral & value)
Definition at line 68 of file quuid.cpp.
Referenced by _q_uuidFromHex().
 {
     value = 0;
     for (uint i = 0; i < sizeof(Integral) * 2; ++i) {
         int ch = *src++;
         int tmp;
         if (ch >= '0' && ch <= '9')
             tmp = ch - '0';
         else if (ch >= 'a' && ch <= 'f')
             tmp = ch - 'a' + 10;
         else if (ch >= 'A' && ch <= 'F')
             tmp = ch - 'A' + 10;
         else
             return false;
         value = value * 16 + tmp;
     }
     return true;
 }
_q_toHex()
template<class Char , class Integral > void _q_toHex (Char *& dst, Integral value)
Definition at line 51 of file quuid.cpp.
Referenced by _q_uuidToHex().
 {
     static const char digits[] = "0123456789abcdef";
     value = qToBigEndian(value);
     const char* p = reinterpret_cast<const char*>(&value);
     for (uint i = 0; i < sizeof(Integral); ++i, dst += 2) {
         uint j = (p[i] >> 4) & 0xf;
         dst[0] = Char(digits[j]);
         j = p[i] & 0xf;
         dst[1] = Char(digits[j]);
     }
 }
_q_uuidFromHex()
template<class Char > bool _q_uuidFromHex (const Char *& src, uint & d1, ushort & d2, ushort & d3, uchar(&) d4[8])
Definition at line 109 of file quuid.cpp.
Referenced by QUuid::QUuid().
 {
     if (*src == Char('{'))
         src++;
     if (!_q_fromHex(src, d1)
             || *src++ != Char('-')
             || !_q_fromHex(src, d2)
             || *src++ != Char('-')
             || !_q_fromHex(src, d3)
             || *src++ != Char('-')
             || !_q_fromHex(src, d4[0])
             || !_q_fromHex(src, d4[1])
             || *src++ != Char('-')
             || !_q_fromHex(src, d4[2])
             || !_q_fromHex(src, d4[3])
             || !_q_fromHex(src, d4[4])
             || !_q_fromHex(src, d4[5])
             || !_q_fromHex(src, d4[6])
             || !_q_fromHex(src, d4[7])) {
         return false;
     }
     return true;
 }
_q_uuidToHex()
template<class Char > void _q_uuidToHex (Char *& dst, const uint & d1, const ushort & d2, const ushort & d3, const uchar(&) d4[8])
Definition at line 91 of file quuid.cpp.
Referenced by QUuid::toByteArray(), and QUuid::toString().
 {
     *dst++ = Char('{');
     _q_toHex(dst, d1);
     *dst++ = Char('-');
     _q_toHex(dst, d2);
     *dst++ = Char('-');
     _q_toHex(dst, d3);
     *dst++ = Char('-');
     for (int i = 0; i < 2; i++)
         _q_toHex(dst, d4[i]);
     *dst++ = Char('-');
     for (int i = 2; i < 8; i++)
         _q_toHex(dst, d4[i]);
     *dst = Char('}');
 }
Q_GLOBAL_STATIC()
Q_GLOBAL_STATIC (QThreadStorage< QFile *> , devUrandomStorage)
Referenced by QUuid::operator>().