Qt 4.8: /src/corelib/animation/qvariantanimation.cpp File Reference
qvariantanimation.cpp File Reference
#include "qvariantanimation.h"
#include "qvariantanimation_p.h"
#include <QtCore/qrect.h>
#include <QtCore/qline.h>
#include <QtCore/qmutex.h>
#include <private/qmutexpool_p.h>
#include "moc_qvariantanimation.cpp"
Typedefs
typedef QVector< QVariantAnimation::Interpolator > QInterpolatorVector
Functions
template<>
Q_INLINE_TEMPLATE QRect _q_interpolate (const QRect &f, const QRect &t, qreal progress)
template<>
Q_INLINE_TEMPLATE QRectF _q_interpolate (const QRectF &f, const QRectF &t, qreal progress)
template<>
Q_INLINE_TEMPLATE QLine _q_interpolate (const QLine &f, const QLine &t, qreal progress)
template<>
Q_INLINE_TEMPLATE QLineF _q_interpolate (const QLineF &f, const QLineF &t, qreal progress)
static bool animationValueLessThan (const QVariantAnimation::KeyValue &p1, const QVariantAnimation::KeyValue &p2)
template<typename T >
static QVariantAnimation::Interpolator castToInterpolator (QVariant(*func)(const T &from, const T &to, qreal progress))
static QVariant defaultInterpolator (const void *, const void *, qreal)
Typedef Documentation
QInterpolatorVector
typedef QVector<QVariantAnimation::Interpolator> QInterpolatorVector
Definition at line 417 of file qvariantanimation.cpp.
Function Documentation
_q_interpolate() [1/4]
template<> Q_INLINE_TEMPLATE QRect _q_interpolate (const QRect & f, const QRect & t, qreal progress)
Definition at line 177 of file qvariantanimation.cpp.
Referenced by _q_interpolate().
 {
     QRect ret;
     ret.setCoords(_q_interpolate(f.left(), t.left(), progress),
                   _q_interpolate(f.top(), t.top(), progress),
                   _q_interpolate(f.right(), t.right(), progress),
                   _q_interpolate(f.bottom(), t.bottom(), progress));
     return ret;
 }
_q_interpolate() [2/4]
template<> Q_INLINE_TEMPLATE QRectF _q_interpolate (const QRectF & f, const QRectF & t, qreal progress)
Definition at line 187 of file qvariantanimation.cpp.
 {
     qreal x1, y1, w1, h1;
     f.getRect(&x1, &y1, &w1, &h1);
     qreal x2, y2, w2, h2;
     t.getRect(&x2, &y2, &w2, &h2);
     return QRectF(_q_interpolate(x1, x2, progress), _q_interpolate(y1, y2, progress),
                   _q_interpolate(w1, w2, progress), _q_interpolate(h1, h2, progress));
 }
_q_interpolate() [3/4]
template<> Q_INLINE_TEMPLATE QLine _q_interpolate (const QLine & f, const QLine & t, qreal progress)
Definition at line 197 of file qvariantanimation.cpp.
 {
     return QLine( _q_interpolate(f.p1(), t.p1(), progress), _q_interpolate(f.p2(), t.p2(), progress));
 }
_q_interpolate() [4/4]
template<> Q_INLINE_TEMPLATE QLineF _q_interpolate (const QLineF & f, const QLineF & t, qreal progress)
Definition at line 202 of file qvariantanimation.cpp.
 {
     return QLineF( _q_interpolate(f.p1(), t.p1(), progress), _q_interpolate(f.p2(), t.p2(), progress));
 }
animationValueLessThan()
static bool animationValueLessThan (const QVariantAnimation::KeyValue & p1, const QVariantAnimation::KeyValue & p2) static
Definition at line 167 of file qvariantanimation.cpp.
Referenced by QVariantAnimationPrivate::recalculateCurrentInterval(), QVariantAnimation::setKeyValues(), QVariantAnimationPrivate::setValueAt(), and QVariantAnimationPrivate::valueAt().
 {
     return p1.first < p2.first;
 }
castToInterpolator()
template<typename T > static QVariantAnimation::Interpolator castToInterpolator (QVariant(*)(const T &from, const T &to, qreal progress) func) inline static
Definition at line 465 of file qvariantanimation.cpp.
Referenced by QVariantAnimationPrivate::getInterpolator().
 {
      return reinterpret_cast<QVariantAnimation::Interpolator>(func);
 }
defaultInterpolator()
static QVariant defaultInterpolator (const void * , const void * , qreal) static
Definition at line 172 of file qvariantanimation.cpp.
Referenced by QVariantAnimationPrivate::updateInterpolator().
 {
     return QVariant();
 }