Qt 4.8: /src/corelib/kernel/qvariant.cpp File Reference
qvariant.cpp File Reference
#include "qvariant.h"
#include "qbitarray.h"
#include "qbytearray.h"
#include "qdatastream.h"
#include "qdebug.h"
#include "qmap.h"
#include "qdatetime.h"
#include "qeasingcurve.h"
#include "qlist.h"
#include "qstring.h"
#include "qstringlist.h"
#include "qurl.h"
#include "qlocale.h"
#include "private/qvariant_p.h"
#include "qsize.h"
#include "qpoint.h"
#include "qrect.h"
#include "qline.h"
#include <float.h>
Macros
#define DBL_DIG 10
#define FLT_DIG 6
Enumerations
enum { MapFromThreeCount = 36 }
Functions
static void clear (QVariant::Private *d)
static bool compare (const QVariant::Private *a, const QVariant::Private *b)
Compares a to b.
template<typename T >
bool compareNumericMetaType (const QVariant::Private *const a, const QVariant::Private *const b)
static void construct (QVariant::Private *x, const void *copy)
static bool convert (const QVariant::Private *d, QVariant::Type t, void *result, bool *ok)
static bool isNull (const QVariant::Private *d)
QDataStream & operator<< (QDataStream &s, const QVariant &p)
Writes a variant p to the stream s.
QDataStream & operator<< (QDataStream &s, const QVariant::Type p)
Writes a variant type p to the stream s.
QDebug operator<< (QDebug dbg, const QVariant &v)
QDebug operator<< (QDebug dbg, const QVariant::Type p)
QDataStream & operator>> (QDataStream &s, QVariant &p)
Reads a variant p from the stream s.
QDataStream & operator>> (QDataStream &s, QVariant::Type &p)
Reads a variant type p in enum representation from the stream s.
static qlonglong qConvertToNumber (const QVariant::Private *d, bool *ok)
static qulonglong qConvertToUnsignedNumber (const QVariant::Private *d, bool *ok)
Q_CORE_EXPORT const QVariant::Handler * qcoreVariantHandler ()
static bool qIsFloatingPoint (uint tp)
static bool qIsNumericType (uint tp)
static qlonglong qMetaTypeNumber (const QVariant::Private *d)
static qulonglong qMetaTypeUNumber (const QVariant::Private *d)
template<typename T >
T qNumVariantToHelper (const QVariant::Private &d, const QVariant::Handler *handler, bool *ok, const T &val)
template<typename TInput , typename LiteralWrapper >
bool qt_convertToBool (const QVariant::Private *const d)
template<typename T >
T qVariantToHelper (const QVariant::Private &d, QVariant::Type t, const QVariant::Handler *handler, T *=0)
static void streamDebug (QDebug dbg, const QVariant &v)
Variables
static const ushort map_from_three [MapFromThreeCount]
static const quint32 qCanConvertMatrix [QVariant::LastCoreType+1]
const QVariant::Handler qt_kernel_variant_handler
Macro Definition Documentation
DBL_DIG
#define DBL_DIG 10
Definition at line 69 of file qvariant.cpp.
Referenced by convert(), qstrtod(), and QDoubleSpinBox::setDecimals().
FLT_DIG
#define FLT_DIG 6
Definition at line 72 of file qvariant.cpp.
Referenced by convert().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MapFromThreeCount
Definition at line 2046 of file qvariant.cpp.
 { MapFromThreeCount = 36 };
Function Documentation
clear()
static void clear (QVariant::Private * d) static
Definition at line 197 of file qvariant.cpp.
Referenced by QHeaderViewPrivate::_q_sectionsRemoved(), QComboBox::addItems(), QListWidget::addItems(), QGL2PEXVertexArray::addVertex(), QContiguousCache< T >::available(), QBitmap::clear(), QDeclarativeEnginePrivate::SimpleList< T >::clear(), QVector< QPoint >::constData(), QDeclarativeCompiledBindingsPrivate::Binding::destroy(), QFileSystemMetaData::fillFromDirEnt(), QDeclarativeAbstractBinding::getPointer(), SurfaceCache::getSurface(), QDirModelPrivate::init(), QContiguousCache< T >::insert(), QAxBase::internalProperty(), QGraphicsScene::invalidate(), QToolBar::isAreaAllowed(), QLinkedList< JSC::Identifier >::isEmpty(), QList< QPostEvent >::isEmpty(), QString::isSharedWith(), QByteArray::isSharedWith(), QHash< QExplicitlySharedDataPointer, QHash >::isSharedWith(), QInt64Set::isValid(), QListModeViewBase::itemIndex(), QDeclarativeGridViewPrivate::layout(), QDeclarativeListViewPrivate::layout(), QByteArray::length(), QDomDocumentPrivate::nodeType(), QSqlRecord::operator!=(), QProcessEnvironment::operator!=(), QSslCertificate::operator!=(), QHostAddress::operator!=(), QDeclarativeGridViewPrivate::QDeclarativeGridViewPrivate(), QDeclarativeListViewPrivate::QDeclarativeListViewPrivate(), QInt64Set::QInt64Set(), QRBTree< int >::QRBTree(), QResourcePrivate::QResourcePrivate(), QDeclarativePathViewPrivate::regenerate(), QDeclarativeGridViewPrivate::regenerate(), QDeclarativeListViewPrivate::regenerate(), QInt64Set::rehash(), QPatternist::ResourceLoader::ResourceLoader(), QLineControl::selectAll(), QAxBase::setControl(), QGLTextureGlyphCache::setFilterMode(), QMap< int, QFrameInfo >::setInsertInOrder(), QDomNodePrivate::setNodeValue(), QSqlField::setRequired(), QUrl::swap(), QVariant::swap(), QTextControl::toHtml(), QPlainTextEdit::toPlainText(), QSqlField::value(), QHostInfoLookupManager::waitForThreadPoolDone(), QAbstractHostInfoLookupManager::~QAbstractHostInfoLookupManager(), QAxBase::~QAxBase(), QCommonListViewBase::~QCommonListViewBase(), QRBTree< int >::~QRBTree(), QResourcePrivate::~QResourcePrivate(), QSpanCollection::~QSpanCollection(), QTestEventList::~QTestEventList(), QXmlAttributes::~QXmlAttributes(), and SurfaceCache::~SurfaceCache().
 {
     switch (d->type) {
     case QVariant::String:
         v_clear<QString>(d);
         break;
     case QVariant::Char:
         v_clear<QChar>(d);
         break;
     case QVariant::StringList:
         v_clear<QStringList>(d);
         break;
     case QVariant::Map:
         v_clear<QVariantMap>(d);
         break;
     case QVariant::Hash:
         v_clear<QVariantHash>(d);
         break;
     case QVariant::List:
         v_clear<QVariantList>(d);
         break;
     case QVariant::Date:
         v_clear<QDate>(d);
         break;
     case QVariant::Time:
         v_clear<QTime>(d);
         break;
     case QVariant::DateTime:
         v_clear<QDateTime>(d);
         break;
     case QVariant::ByteArray:
         v_clear<QByteArray>(d);
         break;
     case QVariant::BitArray:
         v_clear<QBitArray>(d);
         break;
 #ifndef QT_NO_GEOM_VARIANT
     case QVariant::Point:
         v_clear<QPoint>(d);
         break;
     case QVariant::PointF:
         v_clear<QPointF>(d);
         break;
     case QVariant::Size:
         v_clear<QSize>(d);
         break;
     case QVariant::SizeF:
         v_clear<QSizeF>(d);
         break;
     case QVariant::Rect:
         v_clear<QRect>(d);
         break;
     case QVariant::LineF:
         v_clear<QLineF>(d);
         break;
     case QVariant::Line:
         v_clear<QLine>(d);
         break;
     case QVariant::RectF:
         v_clear<QRectF>(d);
         break;
 #endif
 #ifndef QT_BOOTSTRAPPED
     case QVariant::Url:
         v_clear<QUrl>(d);
         break;
 #endif
     case QVariant::Locale:
         v_clear<QLocale>(d);
         break;
 #ifndef QT_NO_REGEXP
     case QVariant::RegExp:
         v_clear<QRegExp>(d);
         break;
 #endif
 #ifndef QT_BOOTSTRAPPED
     case QVariant::EasingCurve:
         v_clear<QEasingCurve>(d);
         break;
 #endif
     case QVariant::LongLong:
     case QVariant::ULongLong:
     case QVariant::Double:
     case QMetaType::Float:
     case QMetaType::QObjectStar:
         break;
     case QVariant::Invalid:
     case QVariant::UserType:
     case QVariant::Int:
     case QVariant::UInt:
     case QVariant::Bool:
         break;
     default:
         QMetaType::destroy(d->type, d->data.shared->ptr);
         delete d->data.shared;
         break;
     }
     d->type = QVariant::Invalid;
     d->is_null = true;
     d->is_shared = false;
 }
compare()
static bool compare (const QVariant::Private * a, const QVariant::Private * b) static
Compares a to b.
Warning
This function is not part of the public interface.
The caller guarantees that a and b are of the same type.
Definition at line 383 of file qvariant.cpp.
Referenced by QTestResult::compare(), QString::compare(), QPatternist::ComparisonFactory::constructAndCompare(), QPatternist::ComparisonPlatform< IndexOfIterator, false >::detailedFlexibleCompare(), QListModel::ensureSorted(), QTreeModel::ensureSorted(), QTableModel::ensureSorted(), QPatternist::ComparisonPlatform< IndexOfIterator, false >::flexibleCompare(), QSortFilterProxyModelPrivate::proxy_intervals_for_source_items_to_add(), QPatternist::XPath20CoreFunctions::retrieveExpression(), QListModel::sort(), QTableModel::sort(), QTreeModel::sortItems(), and QCss::Parser::testPrio().
 {
     switch(a->type) {
     case QVariant::List:
         return *v_cast<QVariantList>(a) == *v_cast<QVariantList>(b);
     case QVariant::Map: {
         const QVariantMap *m1 = v_cast<QVariantMap>(a);
         const QVariantMap *m2 = v_cast<QVariantMap>(b);
         if (m1->count() != m2->count())
             return false;
         QVariantMap::ConstIterator it = m1->constBegin();
         QVariantMap::ConstIterator it2 = m2->constBegin();
         while (it != m1->constEnd()) {
             if (*it != *it2 || it.key() != it2.key())
                 return false;
             ++it;
             ++it2;
         }
         return true;
     }
     case QVariant::Hash:
         return *v_cast<QVariantHash>(a) == *v_cast<QVariantHash>(b);
     case QVariant::String:
         return *v_cast<QString>(a) == *v_cast<QString>(b);
     case QVariant::Char:
         return *v_cast<QChar>(a) == *v_cast<QChar>(b);
     case QVariant::StringList:
         return *v_cast<QStringList>(a) == *v_cast<QStringList>(b);
 #ifndef QT_NO_GEOM_VARIANT
     case QVariant::Size:
         return *v_cast<QSize>(a) == *v_cast<QSize>(b);
     case QVariant::SizeF:
         return *v_cast<QSizeF>(a) == *v_cast<QSizeF>(b);
     case QVariant::Rect:
         return *v_cast<QRect>(a) == *v_cast<QRect>(b);
     case QVariant::Line:
         return *v_cast<QLine>(a) == *v_cast<QLine>(b);
     case QVariant::LineF:
         return *v_cast<QLineF>(a) == *v_cast<QLineF>(b);
     case QVariant::RectF:
         return *v_cast<QRectF>(a) == *v_cast<QRectF>(b);
     case QVariant::Point:
         return *v_cast<QPoint>(a) == *v_cast<QPoint>(b);
     case QVariant::PointF:
         return *v_cast<QPointF>(a) == *v_cast<QPointF>(b);
 #endif
 #ifndef QT_BOOTSTRAPPED
     case QVariant::Url:
         return *v_cast<QUrl>(a) == *v_cast<QUrl>(b);
 #endif
     case QVariant::Locale:
         return *v_cast<QLocale>(a) == *v_cast<QLocale>(b);
 #ifndef QT_NO_REGEXP
     case QVariant::RegExp:
         return *v_cast<QRegExp>(a) == *v_cast<QRegExp>(b);
 #endif
     case QVariant::Int:
         return a->data.i == b->data.i;
     case QVariant::UInt:
         return a->data.u == b->data.u;
     case QVariant::LongLong:
         return a->data.ll == b->data.ll;
     case QVariant::ULongLong:
         return a->data.ull == b->data.ull;
     case QVariant::Bool:
         return a->data.b == b->data.b;
     case QVariant::Double:
         return a->data.d == b->data.d;
     case QMetaType::Float:
         return a->data.f == b->data.f;
     case QMetaType::QObjectStar:
         return a->data.o == b->data.o;
     case QVariant::Date:
         return *v_cast<QDate>(a) == *v_cast<QDate>(b);
     case QVariant::Time:
         return *v_cast<QTime>(a) == *v_cast<QTime>(b);
     case QVariant::DateTime:
         return *v_cast<QDateTime>(a) == *v_cast<QDateTime>(b);
 #ifndef QT_BOOTSTRAPPED
     case QVariant::EasingCurve:
         return *v_cast<QEasingCurve>(a) == *v_cast<QEasingCurve>(b);
 #endif
     case QVariant::ByteArray:
         return *v_cast<QByteArray>(a) == *v_cast<QByteArray>(b);
     case QVariant::BitArray:
         return *v_cast<QBitArray>(a) == *v_cast<QBitArray>(b);
     case QVariant::Invalid:
         return true;
     case QMetaType::Long:
         return compareNumericMetaType<long>(a, b);
     case QMetaType::ULong:
         return compareNumericMetaType<ulong>(a, b);
     case QMetaType::Short:
         return compareNumericMetaType<short>(a, b);
     case QMetaType::UShort:
         return compareNumericMetaType<ushort>(a, b);
     case QMetaType::UChar:
         return compareNumericMetaType<uchar>(a, b);
     case QMetaType::Char:
         return compareNumericMetaType<char>(a, b);
     default:
         break;
     }
     if (!QMetaType::isRegistered(a->type))
         qFatal("QVariant::compare: type %d unknown to QVariant.", a->type);
     const void *a_ptr = a->is_shared ? a->data.shared->ptr : &(a->data.ptr);
     const void *b_ptr = b->is_shared ? b->data.shared->ptr : &(b->data.ptr);
     /* The reason we cannot place this test in a case branch above for the types
      * QMetaType::VoidStar, QMetaType::QObjectStar and so forth, is that it wouldn't include
      * user defined pointer types. */
     const char *const typeName = QMetaType::typeName(a->type);
     uint typeNameLen = qstrlen(typeName);
     if (typeNameLen > 0 && typeName[typeNameLen - 1] == '*')
         return *static_cast<void *const *>(a_ptr) == *static_cast<void *const *>(b_ptr);
     if (a->is_null && b->is_null)
         return true;
     return a_ptr == b_ptr;
 }
compareNumericMetaType()
template<typename T > bool compareNumericMetaType (const QVariant::Private *const a, const QVariant::Private *const b) inline
Definition at line 369 of file qvariant.cpp.
 {
     return *static_cast<const T *>(a->data.shared->ptr) == *static_cast<const T *>(b->data.shared->ptr);
 }
construct()
static void construct (QVariant::Private * x, const void * copy) static
Definition at line 75 of file qvariant.cpp.
Referenced by QScriptValue::construct(), QApplicationPrivate::graphicsSystem(), and QDeclarativeCompiledBindingsPrivate::run().
 {
     x->is_shared = false;
     switch (x->type) {
     case QVariant::String:
         v_construct<QString>(x, copy);
         break;
     case QVariant::Char:
         v_construct<QChar>(x, copy);
         break;
     case QVariant::StringList:
         v_construct<QStringList>(x, copy);
         break;
     case QVariant::Map:
         v_construct<QVariantMap>(x, copy);
         break;
     case QVariant::Hash:
         v_construct<QVariantHash>(x, copy);
         break;
     case QVariant::List:
         v_construct<QVariantList>(x, copy);
         break;
     case QVariant::Date:
         v_construct<QDate>(x, copy);
         break;
     case QVariant::Time:
         v_construct<QTime>(x, copy);
         break;
     case QVariant::DateTime:
         v_construct<QDateTime>(x, copy);
         break;
     case QVariant::ByteArray:
         v_construct<QByteArray>(x, copy);
         break;
     case QVariant::BitArray:
         v_construct<QBitArray>(x, copy);
         break;
 #ifndef QT_NO_GEOM_VARIANT
     case QVariant::Size:
         v_construct<QSize>(x, copy);
         break;
     case QVariant::SizeF:
         v_construct<QSizeF>(x, copy);
         break;
     case QVariant::Rect:
         v_construct<QRect>(x, copy);
         break;
     case QVariant::LineF:
         v_construct<QLineF>(x, copy);
         break;
     case QVariant::Line:
         v_construct<QLine>(x, copy);
         break;
     case QVariant::RectF:
         v_construct<QRectF>(x, copy);
         break;
     case QVariant::Point:
         v_construct<QPoint>(x, copy);
         break;
     case QVariant::PointF:
         v_construct<QPointF>(x, copy);
         break;
 #endif
 #ifndef QT_BOOTSTRAPPED
     case QVariant::Url:
         v_construct<QUrl>(x, copy);
         break;
 #endif
     case QVariant::Locale:
         v_construct<QLocale>(x, copy);
         break;
 #ifndef QT_NO_REGEXP
     case QVariant::RegExp:
         v_construct<QRegExp>(x, copy);
         break;
 #endif
 #ifndef QT_BOOTSTRAPPED
     case QVariant::EasingCurve:
         v_construct<QEasingCurve>(x, copy);
         break;
 #endif
     case QVariant::Int:
         x->data.i = copy ? *static_cast<const int *>(copy) : 0;
         break;
     case QVariant::UInt:
         x->data.u = copy ? *static_cast<const uint *>(copy) : 0u;
         break;
     case QVariant::Bool:
         x->data.b = copy ? *static_cast<const bool *>(copy) : false;
         break;
     case QVariant::Double:
         x->data.d = copy ? *static_cast<const double*>(copy) : 0.0;
         break;
     case QMetaType::Float:
         x->data.f = copy ? *static_cast<const float*>(copy) : 0.0f;
         break;
     case QMetaType::QObjectStar:
         x->data.o = copy ? *static_cast<QObject *const*>(copy) : 0;
         break;
     case QVariant::LongLong:
         x->data.ll = copy ? *static_cast<const qlonglong *>(copy) : Q_INT64_C(0);
         break;
     case QVariant::ULongLong:
         x->data.ull = copy ? *static_cast<const qulonglong *>(copy) : Q_UINT64_C(0);
         break;
     case QVariant::Invalid:
     case QVariant::UserType:
         break;
     default:
         void *ptr = QMetaType::construct(x->type, copy);
         if (!ptr) {
             x->type = QVariant::Invalid;
         } else {
             x->is_shared = true;
             x->data.shared = new QVariant::PrivateShared(ptr);
         }
         break;
     }
     x->is_null = !copy;
 }
convert()
static bool convert (const QVariant::Private * d, QVariant::Type t, void * result, bool * ok) static
Warning
This function is not part of the public interface.
Converts d to type t, which is placed in result.
Definition at line 627 of file qvariant.cpp.
Referenced by QDeclarativeBindingCompilerPrivate::compile(), QPSQLResult::data(), QScriptEngine::fromScriptValue(), QDeclarativeBindingCompilerPrivate::numberArith(), QDeclarativeBindingCompilerPrivate::stringArith(), and QVariant::swap().
 {
     Q_ASSERT(d->type != uint(t));
     Q_ASSERT(result);
     bool dummy;
     if (!ok)
         ok = &dummy;
     switch (uint(t)) {
 #ifndef QT_BOOTSTRAPPED
     case QVariant::Url:
         switch (d->type) {
         case QVariant::String:
             *static_cast<QUrl *>(result) = QUrl(*v_cast<QString>(d));
             break;
         default:
             return false;
         }
         break;
 #endif
     case QVariant::String: {
         QString *str = static_cast<QString *>(result);
         switch (d->type) {
         case QVariant::Char:
             *str = QString(*v_cast<QChar>(d));
             break;
         case QMetaType::Char:
         case QMetaType::UChar:
             *str = QChar::fromAscii(*static_cast<char *>(d->data.shared->ptr));
             break;
         case QMetaType::Short:
         case QMetaType::Long:
         case QVariant::Int:
         case QVariant::LongLong:
             *str = QString::number(qMetaTypeNumber(d));
             break;
         case QVariant::UInt:
         case QVariant::ULongLong:
         case QMetaType::UShort:
         case QMetaType::ULong:
             *str = QString::number(qMetaTypeUNumber(d));
             break;
         case QMetaType::Float:
             *str = QString::number(d->data.f, 'g', FLT_DIG);
             break;
         case QVariant::Double:
             *str = QString::number(d->data.d, 'g', DBL_DIG);
             break;
 #if !defined(QT_NO_DATESTRING)
         case QVariant::Date:
             *str = v_cast<QDate>(d)->toString(Qt::ISODate);
             break;
         case QVariant::Time:
             *str = v_cast<QTime>(d)->toString(Qt::ISODate);
             break;
         case QVariant::DateTime:
             *str = v_cast<QDateTime>(d)->toString(Qt::ISODate);
             break;
 #endif
         case QVariant::Bool:
             *str = QLatin1String(d->data.b ? "true" : "false");
             break;
         case QVariant::ByteArray:
             *str = QString::fromAscii(v_cast<QByteArray>(d)->constData());
             break;
         case QVariant::StringList:
             if (v_cast<QStringList>(d)->count() == 1)
                 *str = v_cast<QStringList>(d)->at(0);
             break;
 #ifndef QT_BOOTSTRAPPED
         case QVariant::Url:
             *str = v_cast<QUrl>(d)->toString();
             break;
 #endif
         default:
             return false;
         }
         break;
     }
     case QVariant::Char: {
         QChar *c = static_cast<QChar *>(result);
         switch (d->type) {
         case QVariant::Int:
         case QVariant::LongLong:
         case QMetaType::Char:
         case QMetaType::Short:
         case QMetaType::Long:
         case QMetaType::Float:
             *c = QChar(ushort(qMetaTypeNumber(d)));
             break;
         case QVariant::UInt:
         case QVariant::ULongLong:
         case QMetaType::UChar:
         case QMetaType::UShort:
         case QMetaType::ULong:
             *c = QChar(ushort(qMetaTypeUNumber(d)));
             break;
         default:
             return false;
         }
         break;
     }
 #ifndef QT_NO_GEOM_VARIANT
     case QVariant::Size: {
         QSize *s = static_cast<QSize *>(result);
         switch (d->type) {
         case QVariant::SizeF:
             *s = v_cast<QSizeF>(d)->toSize();
             break;
         default:
             return false;
         }
         break;
     }
     case QVariant::SizeF: {
         QSizeF *s = static_cast<QSizeF *>(result);
         switch (d->type) {
         case QVariant::Size:
             *s = QSizeF(*(v_cast<QSize>(d)));
             break;
         default:
             return false;
         }
         break;
     }
     case QVariant::Line: {
         QLine *s = static_cast<QLine *>(result);
         switch (d->type) {
         case QVariant::LineF:
             *s = v_cast<QLineF>(d)->toLine();
             break;
         default:
             return false;
         }
         break;
     }
     case QVariant::LineF: {
         QLineF *s = static_cast<QLineF *>(result);
         switch (d->type) {
         case QVariant::Line:
             *s = QLineF(*(v_cast<QLine>(d)));
             break;
         default:
             return false;
         }
         break;
     }
 #endif
     case QVariant::StringList:
         if (d->type == QVariant::List) {
             QStringList *slst = static_cast<QStringList *>(result);
             const QVariantList *list = v_cast<QVariantList >(d);
             for (int i = 0; i < list->size(); ++i)
                 slst->append(list->at(i).toString());
         } else if (d->type == QVariant::String) {
             QStringList *slst = static_cast<QStringList *>(result);
             *slst = QStringList(*v_cast<QString>(d));
         } else {
             return false;
         }
         break;
     case QVariant::Date: {
         QDate *dt = static_cast<QDate *>(result);
         if (d->type == QVariant::DateTime)
             *dt = v_cast<QDateTime>(d)->date();
 #ifndef QT_NO_DATESTRING
         else if (d->type == QVariant::String)
             *dt = QDate::fromString(*v_cast<QString>(d), Qt::ISODate);
 #endif
         else
             return false;
         return dt->isValid();
     }
     case QVariant::Time: {
         QTime *t = static_cast<QTime *>(result);
         switch (d->type) {
         case QVariant::DateTime:
             *t = v_cast<QDateTime>(d)->time();
             break;
 #ifndef QT_NO_DATESTRING
         case QVariant::String:
             *t = QTime::fromString(*v_cast<QString>(d), Qt::ISODate);
             break;
 #endif
         default:
             return false;
         }
         return t->isValid();
     }
     case QVariant::DateTime: {
         QDateTime *dt = static_cast<QDateTime *>(result);
         switch (d->type) {
 #ifndef QT_NO_DATESTRING
         case QVariant::String:
             *dt = QDateTime::fromString(*v_cast<QString>(d), Qt::ISODate);
             break;
 #endif
         case QVariant::Date:
             *dt = QDateTime(*v_cast<QDate>(d));
             break;
         default:
             return false;
         }
         return dt->isValid();
     }
     case QVariant::ByteArray: {
         QByteArray *ba = static_cast<QByteArray *>(result);
         switch (d->type) {
         case QVariant::String:
             *ba = v_cast<QString>(d)->toAscii();
             break;
         case QVariant::Double:
             *ba = QByteArray::number(d->data.d, 'g', DBL_DIG);
             break;
         case QMetaType::Float:
             *ba = QByteArray::number(d->data.f, 'g', FLT_DIG);
             break;
         case QMetaType::Char:
         case QMetaType::UChar:
             *ba = QByteArray(1, *static_cast<char *>(d->data.shared->ptr));
             break;
         case QVariant::Int:
         case QVariant::LongLong:
         case QMetaType::Short:
         case QMetaType::Long:
             *ba = QByteArray::number(qMetaTypeNumber(d));
             break;
         case QVariant::UInt:
         case QVariant::ULongLong:
         case QMetaType::UShort:
         case QMetaType::ULong:
             *ba = QByteArray::number(qMetaTypeUNumber(d));
             break;
         case QVariant::Bool:
             *ba = QByteArray(d->data.b ? "true" : "false");
             break;
         default:
             return false;
         }
     }
     break;
     case QMetaType::Short:
         *static_cast<short *>(result) = short(qConvertToNumber(d, ok));
         return *ok;
     case QMetaType::Long:
         *static_cast<long *>(result) = long(qConvertToNumber(d, ok));
         return *ok;
     case QMetaType::UShort:
         *static_cast<ushort *>(result) = ushort(qConvertToUnsignedNumber(d, ok));
         return *ok;
     case QMetaType::ULong:
         *static_cast<ulong *>(result) = ulong(qConvertToUnsignedNumber(d, ok));
         return *ok;
     case QVariant::Int:
         *static_cast<int *>(result) = int(qConvertToNumber(d, ok));
         return *ok;
     case QVariant::UInt:
         *static_cast<uint *>(result) = uint(qConvertToUnsignedNumber(d, ok));
         return *ok;
     case QVariant::LongLong:
         *static_cast<qlonglong *>(result) = qConvertToNumber(d, ok);
         return *ok;
     case QVariant::ULongLong: {
         *static_cast<qulonglong *>(result) = qConvertToUnsignedNumber(d, ok);
         return *ok;
     }
     case QMetaType::UChar: {
         *static_cast<uchar *>(result) = qConvertToUnsignedNumber(d, ok);
         return *ok;
     }
     case QVariant::Bool: {
         bool *b = static_cast<bool *>(result);
         switch(d->type) {
         case QVariant::ByteArray:
             *b = qt_convertToBool<QByteArray, QByteArray>(d);
             break;
         case QVariant::String:
             *b = qt_convertToBool<QString, QLatin1String>(d);
             break;
         case QVariant::Char:
             *b = !v_cast<QChar>(d)->isNull();
             break;
         case QVariant::Double:
         case QVariant::Int:
         case QVariant::LongLong:
         case QMetaType::Char:
         case QMetaType::Short:
         case QMetaType::Long:
         case QMetaType::Float:
             *b = qMetaTypeNumber(d) != Q_INT64_C(0);
             break;
         case QVariant::UInt:
         case QVariant::ULongLong:
         case QMetaType::UChar:
         case QMetaType::UShort:
         case QMetaType::ULong:
             *b = qMetaTypeUNumber(d) != Q_UINT64_C(0);
             break;
         default:
             *b = false;
             return false;
         }
         break;
     }
     case QVariant::Double: {
         double *f = static_cast<double *>(result);
         switch (d->type) {
         case QVariant::String:
             *f = v_cast<QString>(d)->toDouble(ok);
             break;
         case QVariant::ByteArray:
             *f = v_cast<QByteArray>(d)->toDouble(ok);
             break;
         case QVariant::Bool:
             *f = double(d->data.b);
             break;
         case QMetaType::Float:
             *f = double(d->data.f);
             break;
         case QVariant::LongLong:
         case QVariant::Int:
         case QMetaType::Char:
         case QMetaType::Short:
         case QMetaType::Long:
             *f = double(qMetaTypeNumber(d));
             break;
         case QVariant::UInt:
         case QVariant::ULongLong:
         case QMetaType::UChar:
         case QMetaType::UShort:
         case QMetaType::ULong:
             *f = double(qMetaTypeUNumber(d));
             break;
         default:
             *f = 0.0;
             return false;
         }
         break;
     }
     case QMetaType::Float: {
         float *f = static_cast<float *>(result);
         switch (d->type) {
         case QVariant::String:
             *f = v_cast<QString>(d)->toFloat(ok);
             break;
         case QVariant::ByteArray:
             *f = v_cast<QByteArray>(d)->toFloat(ok);
             break;
         case QVariant::Bool:
             *f = float(d->data.b);
             break;
         case QVariant::Double:
             *f = float(d->data.d);
             break;
         case QVariant::LongLong:
         case QVariant::Int:
         case QMetaType::Char:
         case QMetaType::Short:
         case QMetaType::Long:
             *f = float(qMetaTypeNumber(d));
             break;
         case QVariant::UInt:
         case QVariant::ULongLong:
         case QMetaType::UChar:
         case QMetaType::UShort:
         case QMetaType::ULong:
             *f = float(qMetaTypeUNumber(d));
             break;
         default:
             *f = 0.0f;
             return false;
         }
         break;
     }
     case QVariant::List:
         if (d->type == QVariant::StringList) {
             QVariantList *lst = static_cast<QVariantList *>(result);
             const QStringList *slist = v_cast<QStringList>(d);
             for (int i = 0; i < slist->size(); ++i)
                 lst->append(QVariant(slist->at(i)));
         } else if (qstrcmp(QMetaType::typeName(d->type), "QList<QVariant>") == 0) {
             *static_cast<QVariantList *>(result) =
                 *static_cast<QList<QVariant> *>(d->data.shared->ptr);
         } else {
             return false;
         }
         break;
     case QVariant::Map:
         if (qstrcmp(QMetaType::typeName(d->type), "QMap<QString, QVariant>") == 0) {
             *static_cast<QVariantMap *>(result) =
                 *static_cast<QMap<QString, QVariant> *>(d->data.shared->ptr);
         } else {
             return false;
         }
         break;
     case QVariant::Hash:
         if (qstrcmp(QMetaType::typeName(d->type), "QHash<QString, QVariant>") == 0) {
             *static_cast<QVariantHash *>(result) =
                 *static_cast<QHash<QString, QVariant> *>(d->data.shared->ptr);
         } else {
             return false;
         }
         break;
 #ifndef QT_NO_GEOM_VARIANT
     case QVariant::Rect:
         if (d->type == QVariant::RectF)
             *static_cast<QRect *>(result) = (v_cast<QRectF>(d))->toRect();
         else
             return false;
         break;
     case QVariant::RectF:
         if (d->type == QVariant::Rect)
             *static_cast<QRectF *>(result) = *v_cast<QRect>(d);
         else
             return false;
         break;
     case QVariant::PointF:
         if (d->type == QVariant::Point)
             *static_cast<QPointF *>(result) = *v_cast<QPoint>(d);
         else
             return false;
         break;
     case QVariant::Point:
         if (d->type == QVariant::PointF)
             *static_cast<QPoint *>(result) = (v_cast<QPointF>(d))->toPoint();
         else
             return false;
         break;
     case QMetaType::Char:
     {
         *static_cast<qint8 *>(result) = qint8(qConvertToNumber(d, ok));
         return *ok;
     }
 #endif
     default:
         return false;
     }
     return true;
 }
isNull()
static bool isNull (const QVariant::Private * d) static
Definition at line 300 of file qvariant.cpp.
Referenced by QMacStylePrivate::aquaSizeConstrain(), QPatternist::Item::asNode(), classIDL(), convert(), DumpIDL(), QAxBase::dynamicCallHelper(), QLabelPrivate::ensureTextPopulated(), QCss::ValueExtractor::extractImage(), QFileInfoPrivate::getFileName(), QFileInfoPrivate::getFileOwner(), QSqlRecord::isNull(), QAbstractXmlNodeModel::iterate(), QByteArray::length(), QPatternist::ReportContext::lookupSourceLocation(), QToolBoxButton::minimumSizeHint(), QWatermarkLabel::minimumSizeHint(), QScopedPointer< QXmlResultItemsPrivate >::operator bool(), QUuid::operator QString(), QPixmap::operator!(), QAuthenticator::operator!=(), QSqlRecord::operator!=(), QSslCipher::operator!=(), QSslConfiguration::operator!=(), QSslCertificate::operator!=(), QHostAddress::operator!=(), QIcon::paint(), QCommandLinkButton::paintEvent(), QDB2Driver::primaryIndex(), QGuiEventDispatcherWin32::processEvents(), QAxBase::propertyBag(), QGLGraphicsSystem::QGLGraphicsSystem(), qMakeFieldInfo(), QMdiSubWindow::QMdiSubWindow(), QRect::QRect(), qt_cleanup(), qt_getLprPrinters(), qt_init(), qt_message_output(), QAxBase::qt_metacall(), qt_wstate_iconified(), QAxBase::setControl(), QmlJSDebugger::LiveSelectionIndicator::setItems(), QAxBase::setPropertyBag(), QListView::setSelection(), QMdiSubWindow::setWidget(), QMdiSubWindow::showShaded(), QPushButton::sizeHint(), QToolBoxButton::sizeHint(), QDockWidgetTitleButton::sizeHint(), QRegion::swap(), QPixmap::swap(), QImage::swap(), QVariant::swap(), QDB2Driver::tables(), QComboBoxPrivate::updateLineEditGeometry(), QSqlField::value(), QPatternist::yyparse(), and QObject::~QObject().
 {
     switch(d->type) {
     case QVariant::String:
         return v_cast<QString>(d)->isNull();
     case QVariant::Char:
         return v_cast<QChar>(d)->isNull();
     case QVariant::Date:
         return v_cast<QDate>(d)->isNull();
     case QVariant::Time:
         return v_cast<QTime>(d)->isNull();
     case QVariant::DateTime:
         return v_cast<QDateTime>(d)->isNull();
     case QVariant::ByteArray:
         return v_cast<QByteArray>(d)->isNull();
     case QVariant::BitArray:
         return v_cast<QBitArray>(d)->isNull();
 #ifndef QT_NO_GEOM_VARIANT
     case QVariant::Size:
         return v_cast<QSize>(d)->isNull();
     case QVariant::SizeF:
         return v_cast<QSizeF>(d)->isNull();
     case QVariant::Rect:
         return v_cast<QRect>(d)->isNull();
     case QVariant::Line:
         return v_cast<QLine>(d)->isNull();
     case QVariant::LineF:
         return v_cast<QLineF>(d)->isNull();
     case QVariant::RectF:
         return v_cast<QRectF>(d)->isNull();
     case QVariant::Point:
         return v_cast<QPoint>(d)->isNull();
     case QVariant::PointF:
         return v_cast<QPointF>(d)->isNull();
 #endif
 #ifndef QT_BOOTSTRAPPED
     case QVariant::EasingCurve:
     case QVariant::Url:
 #endif
     case QVariant::Locale:
     case QVariant::RegExp:
     case QVariant::StringList:
     case QVariant::Map:
     case QVariant::Hash:
     case QVariant::List:
     case QVariant::Invalid:
     case QVariant::UserType:
     case QVariant::Int:
     case QVariant::UInt:
     case QVariant::LongLong:
     case QVariant::ULongLong:
     case QVariant::Bool:
     case QVariant::Double:
     case QMetaType::Float:
     case QMetaType::QObjectStar:
         break;
     }
     return d->is_null;
 }
operator<<() [1/4]
QDataStream& operator<< (QDataStream & s, const QVariant & p)
Writes a variant p to the stream s.
See also
Format of the QDataStream operators
Definition at line 2195 of file qvariant.cpp.
Referenced by QVariant::operator!=(), qVariantCanConvert(), and QVariant::setValue().
 {
     p.save(s);
     return s;
 }
operator<<() [2/4]
QDataStream& operator<< (QDataStream & s, const QVariant::Type p)
Writes a variant type p to the stream s.
Definition at line 2216 of file qvariant.cpp.
 {
     s << static_cast<quint32>(p);
     return s;
 }
operator<<() [3/4]
QDebug operator<< (QDebug dbg, const QVariant & v)
Definition at line 3108 of file qvariant.cpp.
 {
 #ifndef Q_BROKEN_DEBUG_STREAM
     dbg.nospace() << "QVariant(" << v.typeName() << ", ";
     QVariant::handler->debugStream(dbg, v);
     dbg.nospace() << ')';
     return dbg.space();
 #else
     qWarning("This compiler doesn't support streaming QVariant to QDebug");
     return dbg;
     Q_UNUSED(v);
 #endif
 }
operator<<() [4/4]
QDebug operator<< (QDebug dbg, const QVariant::Type p)
Definition at line 3122 of file qvariant.cpp.
 {
 #ifndef Q_BROKEN_DEBUG_STREAM
     dbg.nospace() << "QVariant::" << QVariant::typeToName(p);
     return dbg.space();
 #else
     qWarning("This compiler doesn't support streaming QVariant::Type to QDebug");
     return dbg;
     Q_UNUSED(p);
 #endif
 }
operator>>() [1/2]
QDataStream& operator>> (QDataStream & s, QVariant & p)
Reads a variant p from the stream s.
Since
4.4
See also
Format of the QDataStream operators
Definition at line 2184 of file qvariant.cpp.
Referenced by QVariant::setValue().
 {
     p.load(s);
     return s;
 }
operator>>() [2/2]
QDataStream& operator>> (QDataStream & s, QVariant::Type & p)
Reads a variant type p in enum representation from the stream s.
Definition at line 2204 of file qvariant.cpp.
 {
     quint32 u;
     s >> u;
     p = (QVariant::Type)u;
     return s;
 }
qConvertToNumber()
static qlonglong qConvertToNumber (const QVariant::Private * d, bool * ok) static
Definition at line 549 of file qvariant.cpp.
Referenced by convert().
 {
     *ok = true;
     switch (uint(d->type)) {
     case QVariant::String:
         return v_cast<QString>(d)->toLongLong(ok);
     case QVariant::Char:
         return v_cast<QChar>(d)->unicode();
     case QVariant::ByteArray:
         return v_cast<QByteArray>(d)->toLongLong(ok);
     case QVariant::Bool:
         return qlonglong(d->data.b);
     case QVariant::Double:
     case QVariant::Int:
     case QMetaType::Char:
     case QMetaType::Short:
     case QMetaType::Long:
     case QMetaType::Float:
     case QMetaType::LongLong:
         return qMetaTypeNumber(d);
     case QVariant::ULongLong:
     case QVariant::UInt:
     case QMetaType::UChar:
     case QMetaType::UShort:
     case QMetaType::ULong:
         return qlonglong(qMetaTypeUNumber(d));
     }
     *ok = false;
     return Q_INT64_C(0);
 }
qConvertToUnsignedNumber()
static qulonglong qConvertToUnsignedNumber (const QVariant::Private * d, bool * ok) static
Definition at line 582 of file qvariant.cpp.
Referenced by convert().
 {
     *ok = true;
     switch (uint(d->type)) {
     case QVariant::String:
         return v_cast<QString>(d)->toULongLong(ok);
     case QVariant::Char:
         return v_cast<QChar>(d)->unicode();
     case QVariant::ByteArray:
         return v_cast<QByteArray>(d)->toULongLong(ok);
     case QVariant::Bool:
         return qulonglong(d->data.b);
     case QVariant::Double:
     case QVariant::Int:
     case QMetaType::Char:
     case QMetaType::Short:
     case QMetaType::Long:
     case QMetaType::Float:
     case QMetaType::LongLong:
         return qulonglong(qMetaTypeNumber(d));
     case QVariant::ULongLong:
     case QVariant::UInt:
     case QMetaType::UChar:
     case QMetaType::UShort:
     case QMetaType::ULong:
         return qMetaTypeUNumber(d);
     }
     *ok = false;
     return Q_UINT64_C(0);
 }
qcoreVariantHandler()
Q_CORE_EXPORT const QVariant::Handler* qcoreVariantHandler ()
Definition at line 1193 of file qvariant.cpp.
Referenced by clear(), compare(), construct(), convert(), isNull(), streamDebug(), and v_clear().
 {
     return &qt_kernel_variant_handler;
 }
qIsFloatingPoint()
static bool qIsFloatingPoint (uint tp) static
Definition at line 3039 of file qvariant.cpp.
Referenced by QVariant::cmp().
 {
     return tp == QVariant::Double || tp == QMetaType::Float;
 }
qIsNumericType()
static bool qIsNumericType (uint tp) static
Definition at line 3033 of file qvariant.cpp.
Referenced by QVariant::cmp().
 {
     return (tp >= QVariant::Bool && tp <= QVariant::Double)
            || (tp >= QMetaType::Long && tp <= QMetaType::Float);
 }
qMetaTypeNumber()
static qlonglong qMetaTypeNumber (const QVariant::Private * d) static
Warning
This function is not part of the public interface.
Definition at line 509 of file qvariant.cpp.
Referenced by convert(), qConvertToNumber(), and qConvertToUnsignedNumber().
 {
     switch (d->type) {
     case QMetaType::Int:
         return d->data.i;
     case QMetaType::LongLong:
         return d->data.ll;
     case QMetaType::Char:
         return qlonglong(*static_cast<signed char *>(d->data.shared->ptr));
     case QMetaType::Short:
         return qlonglong(*static_cast<short *>(d->data.shared->ptr));
     case QMetaType::Long:
         return qlonglong(*static_cast<long *>(d->data.shared->ptr));
     case QMetaType::Float:
         return qRound64(d->data.f);
     case QVariant::Double:
         return qRound64(d->data.d);
     }
     Q_ASSERT(false);
     return 0;
 }
qMetaTypeUNumber()
static qulonglong qMetaTypeUNumber (const QVariant::Private * d) static
Definition at line 531 of file qvariant.cpp.
Referenced by convert(), qConvertToNumber(), and qConvertToUnsignedNumber().
 {
     switch (d->type) {
     case QVariant::UInt:
         return d->data.u;
     case QVariant::ULongLong:
         return d->data.ull;
     case QMetaType::UChar:
         return qulonglong(*static_cast<unsigned char *>(d->data.shared->ptr));
     case QMetaType::UShort:
         return qulonglong(*static_cast<ushort *>(d->data.shared->ptr));
     case QMetaType::ULong:
         return qulonglong(*static_cast<ulong *>(d->data.shared->ptr));
     }
     Q_ASSERT(false);
     return 0;
 }
qNumVariantToHelper()
template<typename T > T qNumVariantToHelper (const QVariant::Private & d, const QVariant::Handler * handler, bool * ok, const T & val) inline
Definition at line 2596 of file qvariant.cpp.
 {
     uint t = qMetaTypeId<T>();
     if (ok)
         *ok = true;
     if (d.type == t)
         return val;
     T ret;
     if (!handler->convert(&d, QVariant::Type(t), &ret, ok) && ok)
         *ok = false;
     return ret;
 }
qt_convertToBool()
template<typename TInput , typename LiteralWrapper > bool qt_convertToBool (const QVariant::Private *const d) inline
Definition at line 616 of file qvariant.cpp.
 {
     TInput str = v_cast<TInput>(d)->toLower();
     return !(str == LiteralWrapper("0") || str == LiteralWrapper("false") || str.isEmpty());
 }
qVariantToHelper()
template<typename T > T qVariantToHelper (const QVariant::Private & d, QVariant::Type t, const QVariant::Handler * handler, T * = 0) inline
Definition at line 2236 of file qvariant.cpp.
 {
     if (d.type == t)
         return *v_cast<T>(&d);
     T ret;
     handler->convert(&d, t, &ret, 0);
     return ret;
 }
streamDebug()
static void streamDebug (QDebug dbg, const QVariant & v) static
Definition at line 1073 of file qvariant.cpp.
 {
     switch (v.userType()) {
     case QVariant::Int:
         dbg.nospace() << v.toInt();
         break;
     case QVariant::UInt:
         dbg.nospace() << v.toUInt();
         break;
     case QVariant::LongLong:
         dbg.nospace() << v.toLongLong();
         break;
     case QVariant::ULongLong:
         dbg.nospace() << v.toULongLong();
         break;
     case QMetaType::Float:
         dbg.nospace() << v.toFloat();
         break;
     case QMetaType::QObjectStar:
         dbg.nospace() << qvariant_cast<QObject *>(v);
         break;
     case QVariant::Double:
         dbg.nospace() << v.toDouble();
         break;
     case QVariant::Bool:
         dbg.nospace() << v.toBool();
         break;
     case QVariant::String:
         dbg.nospace() << v.toString();
         break;
     case QVariant::Char:
         dbg.nospace() << v.toChar();
         break;
     case QVariant::StringList:
         dbg.nospace() << v.toStringList();
         break;
     case QVariant::Map:
         dbg.nospace() << v.toMap();
         break;
     case QVariant::Hash:
         dbg.nospace() << v.toHash();
         break;
     case QVariant::List:
         dbg.nospace() << v.toList();
         break;
     case QVariant::Date:
         dbg.nospace() << v.toDate();
         break;
     case QVariant::Time:
         dbg.nospace() << v.toTime();
         break;
     case QVariant::DateTime:
         dbg.nospace() << v.toDateTime();
         break;
 #ifndef QT_BOOTSTRAPPED
     case QVariant::EasingCurve:
         dbg.nospace() << v.toEasingCurve();
         break;
 #endif
     case QVariant::ByteArray:
         dbg.nospace() << v.toByteArray();
         break;
 #ifndef QT_BOOTSTRAPPED
     case QVariant::Url:
         dbg.nospace() << v.toUrl();
         break;
 #endif
 #ifndef QT_NO_GEOM_VARIANT
     case QVariant::Point:
         dbg.nospace() << v.toPoint();
         break;
     case QVariant::PointF:
         dbg.nospace() << v.toPointF();
         break;
     case QVariant::Rect:
         dbg.nospace() << v.toRect();
         break;
     case QVariant::Size:
         dbg.nospace() << v.toSize();
         break;
     case QVariant::SizeF:
         dbg.nospace() << v.toSizeF();
         break;
     case QVariant::Line:
         dbg.nospace() << v.toLine();
         break;
     case QVariant::LineF:
         dbg.nospace() << v.toLineF();
         break;
     case QVariant::RectF:
         dbg.nospace() << v.toRectF();
         break;
 #endif
     case QVariant::BitArray:
         //dbg.nospace() << v.toBitArray();
         break;
     default:
         break;
     }
 }
Variable Documentation
map_from_three
const ushort map_from_three[MapFromThreeCount] static
Definition at line 2047 of file qvariant.cpp.
Referenced by QVariant::load(), and QVariant::save().
qCanConvertMatrix
const quint32 qCanConvertMatrix[QVariant::LastCoreType+1] static
Definition at line 2771 of file qvariant.cpp.
Referenced by QVariant::canConvert().
qt_kernel_variant_handler
const QVariant::Handler qt_kernel_variant_handler
Initial value:
= {
    construct,
    clear,
    isNull,
    0,
    0,
    compare,
    convert,
    0,
    streamDebug
}
Definition at line 1175 of file qvariant.cpp.
Referenced by qcoreVariantHandler().