Qt 4.8: /src/corelib/kernel/qvariant_p.h File Reference
qvariant_p.h File Reference
#include <QtCore/qglobal.h>
#include <QtCore/qvariant.h>
Classes
class QVariantPrivateSharedEx< T >
Functions
Q_CORE_EXPORT const QVariant::Handler * qcoreVariantHandler ()
template<typename T >
const T * v_cast (const QVariant::Private *d, T *=0)
template<typename T >
T * v_cast (QVariant::Private *d, T *=0)
template<class T >
void v_clear (QVariant::Private *d, T *=0)
template<class T >
void v_construct (QVariant::Private *x, const void *copy, T *=0)
template<class T >
void v_construct (QVariant::Private *x, const T &t)
Function Documentation
qcoreVariantHandler()
Q_CORE_EXPORT const QVariant::Handler* qcoreVariantHandler ()
Definition at line 1193 of file qvariant.cpp.
Referenced by v_clear().
 {
     return &qt_kernel_variant_handler;
 }
v_cast() [1/2]
template<typename T > const T* v_cast (const QVariant::Private * d, T * = 0) inline
Definition at line 78 of file qvariant_p.h.
Referenced by QVariant::canConvert(), compare(), convert(), isNull(), qConvertToNumber(), qConvertToUnsignedNumber(), qt_convertToBool(), qVariantToHelper(), and v_clear().
 {
     return ((sizeof(T) > sizeof(QVariant::Private::Data))
             ? static_cast<const T *>(d->data.shared->ptr)
             : static_cast<const T *>(static_cast<const void *>(&d->data.c)));
 }
v_cast() [2/2]
template<typename T > T* v_cast (QVariant::Private * d, T * = 0) inline
Definition at line 86 of file qvariant_p.h.
 {
     return ((sizeof(T) > sizeof(QVariant::Private::Data))
             ? static_cast<T *>(d->data.shared->ptr)
             : static_cast<T *>(static_cast<void *>(&d->data.c)));
 }
v_clear()
template<class T > void v_clear (QVariant::Private * d, T * = 0) inline
Definition at line 136 of file qvariant_p.h.
 {
     if (sizeof(T) > sizeof(QVariant::Private::Data)) {
         //now we need to cast
         //because QVariant::PrivateShared doesn't have a virtual destructor
         delete static_cast<QVariantPrivateSharedEx<T>*>(d->data.shared);
     } else {
         v_cast<T>(d)->~T();
     }
 }
v_construct() [1/2]
template<class T > void v_construct (QVariant::Private * x, const void * copy, T * = 0) inline
Definition at line 109 of file qvariant_p.h.
 {
     if (sizeof(T) > sizeof(QVariant::Private::Data)) {
         x->data.shared = copy ? new QVariantPrivateSharedEx<T>(*static_cast<const T *>(copy))
                               : new QVariantPrivateSharedEx<T>;
         x->is_shared = true;
     } else {
         if (copy)
             new (&x->data.ptr) T(*static_cast<const T *>(copy));
         else
             new (&x->data.ptr) T;
     }
 }
v_construct() [2/2]
template<class T > void v_construct (QVariant::Private * x, const T & t) inline
Definition at line 124 of file qvariant_p.h.
 {
     if (sizeof(T) > sizeof(QVariant::Private::Data)) {
         x->data.shared = new QVariantPrivateSharedEx<T>(t);
         x->is_shared = true;
     } else {
         new (&x->data.ptr) T(t);
     }
 }