Qt 4.8: /src/corelib/kernel/qvariant.h File Reference
qvariant.h File Reference
#include <QtCore/qatomic.h>
#include <QtCore/qbytearray.h>
#include <QtCore/qlist.h>
#include <QtCore/qmetatype.h>
#include <QtCore/qmap.h>
#include <QtCore/qhash.h>
#include <QtCore/qstring.h>
Classes
class QVariant
The QVariant class acts like a union for the most common Qt data types.
Typedefs
typedef QHash< QString, QVariant > QVariantHash
typedef QList< QVariant > QVariantList
typedef QMap< QString, QVariant > QVariantMap
Functions
bool operator!= (const QVariant &v1, const QVariant &v2)
Q_CORE_EXPORT QDataStream & operator<< (QDataStream &s, const QVariant &p)
Writes a variant p to the stream s.
Q_CORE_EXPORT QDataStream & operator<< (QDataStream &s, const QVariant::Type p)
Writes a variant type p to the stream s.
Q_CORE_EXPORT QDebug operator<< (QDebug, const QVariant &)
Q_CORE_EXPORT QDebug operator<< (QDebug, const QVariant::Type)
bool operator== (const QVariant &v1, const QVariant &v2)
Q_CORE_EXPORT QDataStream & operator>> (QDataStream &s, QVariant &p)
Reads a variant p from the stream s.
Q_CORE_EXPORT QDataStream & operator>> (QDataStream &s, QVariant::Type &p)
Reads a variant type p in enum representation from the stream s.
Q_DECLARE_TYPEINFO (QVariant, Q_MOVABLE_TYPE)
template<typename T >
T qvariant_cast (const QVariant &)
template<>
QVariant qvariant_cast< QVariant > (const QVariant &v)
bool qvariant_cast_helper (const QVariant &v, QVariant::Type tp, void *ptr)
template<typename T >
QT_DEPRECATED bool qVariantCanConvert (const QVariant &variant)
template<typename T >
QVariant qVariantFromValue (const T &)
template<>
QVariant qVariantFromValue (const QVariant &t)
template<typename T >
void qVariantSetValue (QVariant &v, const T &t)
template<>
void qVariantSetValue< QVariant > (QVariant &v, const QVariant &t)
template<typename T >
QT_DEPRECATED T qVariantValue (const QVariant &variant)
Typedef Documentation
QVariantHash
typedef QHash<QString, QVariant> QVariantHash related
Definition at line 445 of file qvariant.h.
QVariantList
typedef QList<QVariant> QVariantList related
Definition at line 443 of file qvariant.h.
QVariantMap
typedef QMap<QString, QVariant> QVariantMap related
Definition at line 444 of file qvariant.h.
Function Documentation
operator!=()
bool operator!= (const QVariant & v1, const QVariant & v2) related
Referenced by QVariant::isDetached().
operator<<() [1/4]
Q_CORE_EXPORT QDataStream& operator<< (QDataStream & s, const QVariant & p)
Writes a variant p to the stream s.
See also
Format of the QDataStream operators
Definition at line 2195 of file qvariant.cpp.
Referenced by QVariant::operator!=(), qVariantCanConvert(), and QVariant::setValue().
 {
     p.save(s);
     return s;
 }
operator<<() [2/4]
Q_CORE_EXPORT QDataStream& operator<< (QDataStream & s, const QVariant::Type p)
Writes a variant type p to the stream s.
Definition at line 2216 of file qvariant.cpp.
 {
     s << static_cast<quint32>(p);
     return s;
 }
operator<<() [3/4]
Q_CORE_EXPORT QDebug operator<< (QDebug , const QVariant &)
Definition at line 3108 of file qvariant.cpp.
 {
 #ifndef Q_BROKEN_DEBUG_STREAM
     dbg.nospace() << "QVariant(" << v.typeName() << ", ";
     QVariant::handler->debugStream(dbg, v);
     dbg.nospace() << ')';
     return dbg.space();
 #else
     qWarning("This compiler doesn't support streaming QVariant to QDebug");
     return dbg;
     Q_UNUSED(v);
 #endif
 }
operator<<() [4/4]
Q_CORE_EXPORT QDebug operator<< (QDebug , const QVariant::Type)
Definition at line 3122 of file qvariant.cpp.
 {
 #ifndef Q_BROKEN_DEBUG_STREAM
     dbg.nospace() << "QVariant::" << QVariant::typeToName(p);
     return dbg.space();
 #else
     qWarning("This compiler doesn't support streaming QVariant::Type to QDebug");
     return dbg;
     Q_UNUSED(p);
 #endif
 }
operator==()
bool operator== (const QVariant & v1, const QVariant & v2) related
Referenced by QVariant::isDetached(), and QVariant::operator!=().
operator>>() [1/2]
Q_CORE_EXPORT QDataStream& operator>> (QDataStream & s, QVariant & p)
Reads a variant p from the stream s.
Since
4.4
See also
Format of the QDataStream operators
Definition at line 2184 of file qvariant.cpp.
Referenced by QVariant::setValue().
 {
     p.load(s);
     return s;
 }
operator>>() [2/2]
Q_CORE_EXPORT QDataStream& operator>> (QDataStream & s, QVariant::Type & p)
Reads a variant type p in enum representation from the stream s.
Definition at line 2204 of file qvariant.cpp.
 {
     quint32 u;
     s >> u;
     p = (QVariant::Type)u;
     return s;
 }
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (QVariant , Q_MOVABLE_TYPE)
Referenced by qVariantCanConvert().
qvariant_cast()
template<typename T > T qvariant_cast (const QVariant & v) related
Definition at line 571 of file qvariant.h.
Referenced by QStandardItem::accessibleDescription(), QStandardItem::accessibleText(), QDBusConnectionPrivate::activateCall(), QGraphicsScene::addItem(), QDBusMarshaller::append(), QDBusMarshaller::appendVariantInternal(), QTextHtmlParserNode::applyBackgroundImage(), QDeclarativeListAccessor::at(), QStandardItem::background(), QListWidgetItem::background(), QTableWidgetItem::background(), QTreeWidgetItem::background(), QListWidgetItem::backgroundColor(), QTableWidgetItem::backgroundColor(), QTreeWidgetItem::backgroundColor(), QAccessibleInterface::backgroundColor(), QOCIResultPrivate::bindValue(), QCss::ValueExtractor::borderValue(), QGraphicsItem::boundingRegionGranularity(), QScriptDebuggerCommand::breakpointData(), QTextFormat::brushProperty(), QCss::Declaration::brushValues(), QWindowsMimeImage::canConvertFromMime(), NestedListModel::checkRoles(), ModelNode::clear(), QTextFormat::colorProperty(), QCss::Declaration::colorValues(), QPaintBuffer::commandDescription(), QDeclarativeGestureAreaParser::compile(), QDeclarativeConnectionsParser::compile(), QDeclarativePropertyChangesParser::compile(), QDeclarativePropertyChangesParser::compileList(), QDeclarativeListModelParser::compileProperty(), QScript::ClassObjectDelegate::construct(), QMacPasteboardMimeTiff::convertFromMime(), QWindowsMimeImage::convertFromMime(), QDeclarativeListAccessor::count(), QDockAreaLayoutInfo::currentTabId(), QGraphicsItem::cursor(), NestedListModel::data(), QItemDelegate::decoration(), QTextFormat::doubleProperty(), QColorWell::dropEvent(), QColorShowLabel::dropEvent(), ModelNode::dump(), QMimeDataWrapper::encodedData(), QOCICols::execBatch(), QCss::ValueExtractor::extractBackground(), QFileSystemModel::fileIcon(), fillList(), fillList< float >(), QInputContext::font(), QListWidgetItem::font(), QStandardItem::font(), QTableWidgetItem::font(), QTreeWidgetItem::font(), QStandardItem::foreground(), QListWidgetItem::foreground(), QTableWidgetItem::foreground(), QTreeWidgetItem::foreground(), QAccessibleInterface::foregroundColor(), QWindowsMimeImage::formatsForMime(), NestedListModel::get(), QTextControl::getPaintContext(), QComboMenuDelegate::getStyleOption(), headerValue(), QStandardItem::icon(), QListWidgetItem::icon(), QTableWidgetItem::icon(), QTreeWidgetItem::icon(), QClipboard::image(), QStyledItemDelegate::initStyleOption(), QTextControlPrivate::inputMethodEvent(), QAccessibleAbstractSpinBox::invokeMethodEx(), QAccessibleAbstractSlider::invokeMethodEx(), QAccessibleTextEdit::invokeMethodEx(), QAccessibleLineEdit::invokeMethodEx(), QScriptDebuggerLocalsModelPrivate::isTopLevelNode(), QComboBoxPrivate::itemIcon(), QTextFormat::lengthProperty(), QHostInfo::lookupHost(), QGraphicsItemPrivate::maybeExtraItemCache(), QNetworkReplyImplPrivate::metaDataChanged(), ModelNode::model(), QAxServerBase::OnAmbientPropertyChange(), QDBusReply< QStringList >::operator=(), QItemDelegate::paint(), QHeaderView::paintEvent(), QHeaderView::paintSection(), parentWidget(), parseColorValue(), QTextFormat::penProperty(), QClipboard::pixmap(), QNetworkAccessHttpBackend::postRequest(), QPainterReplayer::process(), QPaintEngineExReplayer::process(), QLineControl::processInputMethodEvent(), QDBusAbstractInterfacePrivate::property(), QConnmanEngine::propertyChangedContext(), qdbus_cast(), qVariantValue(), QWinInputContext::reconvertString(), QItemDelegate::rect(), NestedListModel::remove(), QGraphicsScene::removeItem(), QInternalMimeData::renderDataHelper(), QScriptDebuggerResponse::resultAsBreakpointData(), QScriptDebuggerResponse::resultAsBreakpoints(), QScriptDebuggerResponse::resultAsContextInfo(), QScriptDebuggerResponse::resultAsScriptData(), QScriptDebuggerResponse::resultAsScripts(), QScriptDebuggerResponse::resultAsScriptValue(), QScriptDebuggerResponse::resultAsScriptValueList(), QScriptDebuggerResponse::resultAsScriptValuePropertyList(), QScriptDebuggerEvent::scriptValue(), QScriptDebuggerCommand::scriptValue(), scriptValueToMessage(), QHeaderView::sectionSizeFromContents(), NestedListModel::set(), QDeclarativeListModelParser::setCustomData(), QDeclarativeKeyNavigationAttached::setFocusNavigation(), QDeclarativeRepeater::setModel(), QDeclarativePathView::setModel(), QDeclarativeGridView::setModel(), QDeclarativeListView::setModel(), QDeclarativeVisualDataModel::setModel(), QItemDelegate::setOptions(), QGraphicsItem::setParentItem(), QVideoSurfaceFormat::setProperty(), NestedListModel::setProperty(), QDeclarativeVisualDataModel::setRootIndex(), QGraphicsItem::setTransform(), QUrlModel::setUrl(), QDeclarativePointFValueType::setValue(), QDeclarativePointValueType::setValue(), QDeclarativeSizeFValueType::setValue(), QDeclarativeSizeValueType::setValue(), QDeclarativeRectFValueType::setValue(), QDeclarativeRectValueType::setValue(), QDeclarativeVector2DValueType::setValue(), QDeclarativeVector3DValueType::setValue(), QDeclarativeVector4DValueType::setValue(), QDeclarativeQuaternionValueType::setValue(), QDeclarativeMatrix4x4ValueType::setValue(), QDeclarativeEasingValueType::setValue(), QDeclarativeFontValueType::setValue(), QStandardItem::sizeHint(), QListWidgetItem::sizeHint(), QTableWidgetItem::sizeHint(), QTreeWidgetItem::sizeHint(), QStyleSheetStyle::standardPixmap(), QStandardItem::statusTip(), QScriptDebuggerCommand::subordinateScriptValue(), QAccessibleInterface::supportedMethods(), QScriptDebuggerLocalsModel::sync(), QTextBlockFormat::tabPositions(), QStandardItem::text(), QListWidgetItem::textColor(), QTableWidgetItem::textColor(), QTreeWidgetItem::textColor(), QStandardItem::toolTip(), QWinInputContext::update(), QDeclarativeBinding::update(), ShaderEffectItem::updateEffectState(), ModelNode::updateListIndexes(), QDockAreaLayoutInfo::updateTabBar(), QVariant::value(), NestedListModel::valueForNode(), variantHash(), variantToQObject(), QDeclarativeWorkerScriptEnginePrivate::variantToScriptValue(), QSettingsPrivate::variantToString(), QAbstractSocket::waitForConnected(), QStandardItem::whatsThis(), QDeclarativePropertyPrivate::write(), QTextOdfWriter::writeInlineCharacter(), QDeclarativeVMEMetaObject::writeVarProperty(), QX11Data::xdndMimeDataForAtom(), xdndObtainData(), and QPaintBufferPrivate::~QPaintBufferPrivate().
 {
     const int vid = qMetaTypeId<T>(static_cast<T *>(0));
     if (vid == v.userType())
         return *reinterpret_cast<const T *>(v.constData());
     if (vid < int(QMetaType::User)) {
         T t;
         if (qvariant_cast_helper(v, QVariant::Type(vid), &t))
             return t;
     }
     return T();
 }
qvariant_cast< QVariant >()
template<> QVariant qvariant_cast< QVariant > (const QVariant & v) inline
Definition at line 584 of file qvariant.h.
 {
     if (v.userType() == QMetaType::QVariant)
         return *reinterpret_cast<const QVariant *>(v.constData());
     return v;
 }
qvariant_cast_helper()
bool qvariant_cast_helper (const QVariant & v, QVariant::Type tp, void * ptr) inline
Definition at line 447 of file qvariant.h.
Referenced by QVariant::operator!=(), and qvariant_cast().
 { return QVariant::handler->convert(&v.d, tp, ptr, 0); }
qVariantCanConvert()
template<typename T > QT_DEPRECATED bool qVariantCanConvert (const QVariant & variant) related
Definition at line 597 of file qvariant.h.
 { return variant.template canConvert<T>(); }
qVariantFromValue() [1/2]
template<typename T > QVariant qVariantFromValue (const T & t) related
Definition at line 451 of file qvariant.h.
Referenced by QVariant::fromValue(), QNetworkReplyImplPrivate::getDownloadBuffer(), QSymSQLResult::handle(), QMYSQLResult::handle(), qExtractSecurityPolicyFromString(), QBBClipboard::MimeData::retrieveData(), QOfonoPrimaryDataContextInterface::setActive(), QNetworkReplyImplPrivate::setDownloadBuffer(), QOfonoPrimaryDataContextInterface::setProp(), and QDBusDemarshaller::toVariantInternal().
 {
     return QVariant(qMetaTypeId<T>(reinterpret_cast<T *>(0)), &t, QTypeInfo<T>::isPointer);
 }
qVariantFromValue() [2/2]
template<> QVariant qVariantFromValue (const QVariant & t) inline
Definition at line 457 of file qvariant.h.
 { return t; }
qVariantSetValue()
template<typename T > void qVariantSetValue (QVariant & v, const T & t) related
Definition at line 460 of file qvariant.h.
Referenced by QVariant::setValue().
 {
     //if possible we reuse the current QVariant private
     const uint type = qMetaTypeId<T>(reinterpret_cast<T *>(0));
     QVariant::Private &d = v.data_ptr();
     if (v.isDetached() && (type == d.type || (type <= uint(QVariant::Char) && d.type <= uint(QVariant::Char)))) {
         d.type = type;
         d.is_null = false;
         T *old = reinterpret_cast<T*>(d.is_shared ? d.data.shared->ptr : &d.data.ptr);
         if (QTypeInfo<T>::isComplex)
             old->~T();
         new (old) T(t); //call the copy constructor
     } else {
         v = QVariant(type, &t, QTypeInfo<T>::isPointer);
     }
 }
qVariantSetValue< QVariant >()
template<> void qVariantSetValue< QVariant > (QVariant & v, const QVariant & t) inline
Definition at line 478 of file qvariant.h.
 {
     v = t;
 }
qVariantValue()
template<typename T > QT_DEPRECATED T qVariantValue (const QVariant & variant) related
Definition at line 593 of file qvariant.h.
 { return qvariant_cast<T>(variant); }