Qt 4.8: /src/gui/painting/qvectorpath_p.h File Reference
qvectorpath_p.h File Reference
#include <QtGui/qpaintengine.h>
#include <private/qpaintengine_p.h>
#include <private/qstroker_p.h>
#include <private/qpainter_p.h>
Classes
struct QRealRect
class QVectorPath
struct QVectorPath::CacheEntry
Typedefs
typedef void(* qvectorpath_cache_cleanup) (QPaintEngineEx *engine, void *data)
Functions
Q_GUI_EXPORT const QVectorPath & qtVectorPathForPath (const QPainterPath &path)
Typedef Documentation
qvectorpath_cache_cleanup
typedef void(* qvectorpath_cache_cleanup) (QPaintEngineEx *engine, void *data)
Definition at line 71 of file qvectorpath_p.h.
Function Documentation
qtVectorPathForPath()
Q_GUI_EXPORT const QVectorPath& qtVectorPathForPath (const QPainterPath & path)
Definition at line 129 of file qpaintengineex.cpp.
Referenced by QGL2PaintEngineEx::clip(), QPaintEngineEx::clip(), QPaintEngineEx::drawPath(), QPaintEngineEx::drawStaticTextItem(), QPainter::fillPath(), QTriangulator< T >::initialize(), QPainter::strokePath(), and QGL2PaintEngineExPrivate::systemStateChanged().
 {
     Q_ASSERT(path.d_func());
     return path.d_func()->vectorPath();
 }