Qt 4.8: /src/corelib/tools/qvector.cpp File Reference
qvector.cpp File Reference
#include "qvector.h"
#include "qtools_p.h"
#include <string.h>
Functions
static int alignmentThreshold ()
Function Documentation
alignmentThreshold()
static int alignmentThreshold () inline static
Definition at line 48 of file qvector.cpp.
Referenced by QVectorData::allocate(), QVectorData::free(), and QVectorData::reallocate().
 {
     // malloc on 32-bit platforms should return pointers that are 8-byte aligned or more
     // while on 64-bit platforms they should be 16-byte aligned or more
     return 2 * sizeof(void*);
 }