Qt 4.8: /src/openvg/qvg_p.h File Reference
qvg_p.h File Reference
#include "qvg.h"
#include <QtGui/qimage.h>
#include <QtGui/private/qeglcontext_p.h>
Macros
#define QVG_NO_DRAW_GLYPHS 1
Functions
Q_OPENVG_EXPORT QImage::Format qt_vg_config_to_image_format (QEglContext *context)
Q_OPENVG_EXPORT VGImageFormat qt_vg_config_to_vg_format (QEglContext *context)
Q_OPENVG_EXPORT QEglContext * qt_vg_create_context (QPaintDevice *device, int devType)
Q_OPENVG_EXPORT QVGPaintEngine * qt_vg_create_paint_engine (void)
Q_OPENVG_EXPORT void qt_vg_destroy_context (QEglContext *context, int devType)
Q_OPENVG_EXPORT void qt_vg_destroy_paint_engine (QVGPaintEngine *engine)
Q_OPENVG_EXPORT VGImageFormat qt_vg_image_to_vg_format (QImage::Format format)
Q_OPENVG_EXPORT EGLSurface qt_vg_shared_surface (void)
Macro Definition Documentation
QVG_NO_DRAW_GLYPHS
#define QVG_NO_DRAW_GLYPHS 1
Definition at line 60 of file qvg_p.h.
Function Documentation
qt_vg_config_to_image_format()
Q_OPENVG_EXPORT QImage::Format qt_vg_config_to_image_format (QEglContext * context)
Definition at line 72 of file qwindowsurface_vgegl.cpp.
Referenced by qt_vg_config_to_vg_format().
 {
     EGLint red = context->configAttrib(EGL_RED_SIZE);
     EGLint green = context->configAttrib(EGL_GREEN_SIZE);
     EGLint blue = context->configAttrib(EGL_BLUE_SIZE);
     EGLint alpha = context->configAttrib(EGL_ALPHA_SIZE);
     QImage::Format argbFormat;
 #ifdef EGL_VG_ALPHA_FORMAT_PRE_BIT
     EGLint type = context->configAttrib(EGL_SURFACE_TYPE);
     if ((type & EGL_VG_ALPHA_FORMAT_PRE_BIT) != 0)
         argbFormat = QImage::Format_ARGB32_Premultiplied;
     else
         argbFormat = QImage::Format_ARGB32;
 #else
     argbFormat = QImage::Format_ARGB32;
 #endif
     if (red == 8 && green == 8 && blue == 8 && alpha == 8)
         return argbFormat;
     else if (red == 8 && green == 8 && blue == 8 && alpha == 0)
         return QImage::Format_RGB32;
     else if (red == 5 && green == 6 && blue == 5 && alpha == 0)
         return QImage::Format_RGB16;
     else if (red == 4 && green == 4 && blue == 4 && alpha == 4)
         return QImage::Format_ARGB4444_Premultiplied;
     else
         return argbFormat;       // XXX
 }
qt_vg_config_to_vg_format()
Q_OPENVG_EXPORT VGImageFormat qt_vg_config_to_vg_format (QEglContext * context)
Definition at line 66 of file qwindowsurface_vgegl.cpp.
Referenced by QVGEGLWindowSurfacePrivate::windowSurfaceSize().
 {
     return qt_vg_image_to_vg_format
         (qt_vg_config_to_image_format(context));
 }
qt_vg_create_context()
Q_OPENVG_EXPORT QEglContext* qt_vg_create_context (QPaintDevice * device, int devType)
Definition at line 304 of file qwindowsurface_vgegl.cpp.
Referenced by QVGPixmapData::destroyImageAndContext(), QVGEGLWindowSurfaceDirect::ensureContext(), qt_vg_shared_surface(), QVGPixmapData::toVGImage(), and QVGEGLWindowSurfacePrivate::windowSurfaceSize().
 {
     QVGSharedContext *shared = sharedContext();
     if (devType == QInternal::Widget)
         ++(shared->widgetRefCount);
     if (shared->context) {
         ++(shared->refCount);
         return shared->context;
     } else {
         shared->context = createContext(device);
         shared->refCount = 1;
         return shared->context;
     }
 }
qt_vg_create_paint_engine()
Q_OPENVG_EXPORT QVGPaintEngine* qt_vg_create_paint_engine (void)
Definition at line 144 of file qwindowsurface_vgegl.cpp.
Referenced by QVGEGLWindowSurfacePrivate::paintEngine(), qt_vg_unregister_pixmap(), and QVGCompositionHelper::QVGCompositionHelper().
 {
     QVGSharedContext *shared = sharedContext();
     if (!shared->engine)
         shared->engine = new QVGPaintEngine();
     return shared->engine;
 }
qt_vg_destroy_context()
Q_OPENVG_EXPORT void qt_vg_destroy_context (QEglContext * context, int devType)
Definition at line 361 of file qwindowsurface_vgegl.cpp.
Referenced by QVGPixmapData::destroyImageAndContext(), QVGEGLWindowSurfaceDirect::ensureContext(), qt_vg_shared_surface(), QVGEGLWindowSurfacePrivate::windowSurfaceSize(), and QVGEGLWindowSurfaceDirect::~QVGEGLWindowSurfaceDirect().
 {
     QVGSharedContext *shared = sharedContext();
     if (shared->context != context) {
         // This is not the shared context.  Shouldn't happen!
         delete context;
         return;
     }
     if (devType == QInternal::Widget)
         --(shared->widgetRefCount);
     if (--(shared->refCount) <= 0) {
         qt_vg_destroy_shared_context(shared);
     } else if (shared->widgetRefCount <= 0 && devType == QInternal::Widget) {
         // All of the widget window surfaces have been destroyed
         // but we still have VG pixmaps active.  Ask them to hibernate
         // to free up GPU resources until a widget is shown again.
         // This may eventually cause the EGLContext to be destroyed
         // because nothing in the system needs a context, which will
         // free up even more GPU resources.
         qt_vg_hibernate_pixmaps(shared);
     }
 }
qt_vg_destroy_paint_engine()
Q_OPENVG_EXPORT void qt_vg_destroy_paint_engine (QVGPaintEngine * engine)
Definition at line 152 of file qwindowsurface_vgegl.cpp.
Referenced by QVGEGLWindowSurfacePrivate::destroyPaintEngine(), QVGEGLWindowSurfaceDirect::ensureContext(), and qt_vg_unregister_pixmap().
 {
     Q_UNUSED(engine);
 }
qt_vg_image_to_vg_format()
Q_OPENVG_EXPORT VGImageFormat qt_vg_image_to_vg_format (QImage::Format format)
Definition at line 4239 of file qpaintengine_vg.cpp.
Referenced by QVGPaintEngine::canVgWritePixels(), QVGPaintEngine::drawImage(), drawImageTiled(), QVGPixmapData::ensureReadback(), qt_vg_config_to_vg_format(), and QVGPixmapData::toVGImage().
 {
     switch (format) {
         case QImage::Format_MonoLSB:
             return VG_BW_1;
         case QImage::Format_Indexed8:
             return VG_sL_8;
         case QImage::Format_ARGB32_Premultiplied:
             return VG_sARGB_8888_PRE;
         case QImage::Format_RGB32:
             return VG_sXRGB_8888;
         case QImage::Format_ARGB32:
             return VG_sARGB_8888;
         case QImage::Format_RGB16:
             return VG_sRGB_565;
         case QImage::Format_ARGB4444_Premultiplied:
             return VG_sARGB_4444;
         default:
             break;
     }
     return VG_sARGB_8888;   // XXX
 }
qt_vg_shared_surface()
Q_OPENVG_EXPORT EGLSurface qt_vg_shared_surface (void)
Definition at line 384 of file qwindowsurface_vgegl.cpp.
Referenced by QVGPixmapData::destroyImageAndContext(), qt_vg_destroy_shared_context(), qt_vg_hibernate_pixmaps(), QVGEGLWindowSurfacePrivate::windowSurfaceSize(), and QVGSharedContext::~QVGSharedContext().
 {
     QVGSharedContext *shared = sharedContext();
     if (shared->surface == EGL_NO_SURFACE) {
         EGLint attribs[7];
         attribs[0] = EGL_WIDTH;
         attribs[1] = 16;
         attribs[2] = EGL_HEIGHT;
         attribs[3] = 16;
 #ifdef EGL_VG_ALPHA_FORMAT_PRE_BIT
         if (isPremultipliedContext(shared->context)) {
             attribs[4] = EGL_VG_ALPHA_FORMAT;
             attribs[5] = EGL_VG_ALPHA_FORMAT_PRE;
             attribs[6] = EGL_NONE;
         } else
 #endif
         {
             attribs[4] = EGL_NONE;
         }
         shared->surface = eglCreatePbufferSurface
             (QEgl::display(), shared->context->config(), attribs);
     }
     return shared->surface;
 }