Qt 4.8: /src/plugins/platforms/vnc/qvncintegration.cpp File Reference
qvncintegration.cpp File Reference
#include "qvncintegration.h"
#include "../fb_base/fb_base.h"
#include <private/qapplication_p.h>
#include <QtGui/private/qpixmap_raster_p.h>
#include <QtCore/qdebug.h>
#include <qvncserver.h>
#include <QtGui/QPainter>
#include <QtCore/QTimer>
#include "qgenericunixfontdatabase.h"
Functions
static int defaultDisplay ()
static int defaultHeight ()
static int defaultWidth ()
static void usage ()
Function Documentation
defaultDisplay()
static int defaultDisplay () inline static
Definition at line 87 of file qvncintegration.cpp.
Referenced by QVNCIntegration::QVNCIntegration(), and usage().
 { return 0; }
defaultHeight()
static int defaultHeight () inline static
Definition at line 86 of file qvncintegration.cpp.
Referenced by QVNCIntegration::QVNCIntegration(), and usage().
 { return 600; }
defaultWidth()
static int defaultWidth () inline static
Definition at line 85 of file qvncintegration.cpp.
Referenced by QVNCIntegration::QVNCIntegration(), and usage().
 { return 800; }
usage()
static void usage () static
Definition at line 89 of file qvncintegration.cpp.
Referenced by QVNCIntegration::QVNCIntegration().
 {
     qWarning() << "VNC Platform Integration options:";
     qWarning() << "    size=<Width>x<Height> - set the display width and height";
     qWarning() << "         defaults to" << defaultWidth() << "x" << defaultHeight();
     qWarning() << "    display=<ID> - set the VNC display port to ID + 5900";
     qWarning() << "         defaults to" << defaultDisplay();
     qWarning() << "    offset=<X>x<Y> - set the current screens offset";
     qWarning() << "    vnc - start configuration of a new screen";
     qWarning() << "         size and offset are inherited from the previous screen if not set";
     qWarning() << "         display id is incremented from the previous screen if not set";
     qWarning() << "    virtual - manage the set of screens as a virtual desktop";
 }