Qt 4.8: /src/corelib/thread/qwaitcondition_unix.cpp File Reference
qwaitcondition_unix.cpp File Reference
#include "qplatformdefs.h"
#include "qwaitcondition.h"
#include "qmutex.h"
#include "qreadwritelock.h"
#include "qatomic.h"
#include "qstring.h"
#include "qmutex_p.h"
#include "qreadwritelock_p.h"
#include <errno.h>
Classes
class QWaitConditionPrivate
Functions
static void report_error (int code, const char *where, const char *what)
Function Documentation
report_error()
static void report_error (int code, const char * where, const char * what) static
Definition at line 58 of file qwaitcondition_unix.cpp.
Referenced by QMutexPrivate::QMutexPrivate(), QWaitCondition::QWaitCondition(), QWaitCondition::wait(), QWaitConditionPrivate::wait(), QWaitCondition::wakeAll(), QWaitCondition::wakeOne(), QMutexPrivate::~QMutexPrivate(), and QWaitCondition::~QWaitCondition().
 {
     if (code != 0)
         qWarning("%s: %s failure: %s", where, what, qPrintable(qt_error_string(code)));
 }