Qt 4.8: /src/plugins/platforms/wayland/qwaylandinputdevice.cpp File Reference
qwaylandinputdevice.cpp File Reference
#include "qwaylandinputdevice.h"
#include "qwaylandintegration.h"
#include "qwaylandwindow.h"
#include "qwaylandbuffer.h"
#include <QWindowSystemInterface>
#include <QtGui/private/qpixmap_raster_p.h>
#include <QtGui/QPlatformWindow>
#include <unistd.h>
#include <fcntl.h>
#include <X11/extensions/XKBcommon.h>
#include <X11/keysym.h>
Classes
class QWaylandInputDevice
Functions
static uint32_t translateKey (uint32_t sym, char *string, size_t size)
static Qt::KeyboardModifiers translateModifiers (int s)
Function Documentation
translateKey()
static uint32_t translateKey (uint32_t sym, char * string, size_t size) static
Definition at line 181 of file qwaylandinputdevice.cpp.
Referenced by QWaylandInputDevice::inputHandleKey().
 {
     Q_UNUSED(size);
     string[0] = '\0';
     switch (sym) {
     case XK_Escape:     return Qt::Key_Escape;
     case XK_Tab:        return Qt::Key_Tab;
     case XK_ISO_Left_Tab:   return Qt::Key_Backtab;
     case XK_BackSpace:      return Qt::Key_Backspace;
     case XK_Return:     return Qt::Key_Return;
     case XK_Insert:     return Qt::Key_Insert;
     case XK_Delete:     return Qt::Key_Delete;
     case XK_Clear:      return Qt::Key_Delete;
     case XK_Pause:      return Qt::Key_Pause;
     case XK_Print:      return Qt::Key_Print;
     case XK_Home:       return Qt::Key_Home;
     case XK_End:        return Qt::Key_End;
     case XK_Left:       return Qt::Key_Left;
     case XK_Up:         return Qt::Key_Up;
     case XK_Right:      return Qt::Key_Right;
     case XK_Down:       return Qt::Key_Down;
     case XK_Prior:      return Qt::Key_PageUp;
     case XK_Next:       return Qt::Key_PageDown;
     case XK_Shift_L:        return Qt::Key_Shift;
     case XK_Shift_R:        return Qt::Key_Shift;
     case XK_Shift_Lock:     return Qt::Key_Shift;
     case XK_Control_L:      return Qt::Key_Control;
     case XK_Control_R:      return Qt::Key_Control;
     case XK_Meta_L:     return Qt::Key_Meta;
     case XK_Meta_R:     return Qt::Key_Meta;
     case XK_Alt_L:      return Qt::Key_Alt;
     case XK_Alt_R:      return Qt::Key_Alt;
     case XK_Caps_Lock:      return Qt::Key_CapsLock;
     case XK_Num_Lock:       return Qt::Key_NumLock;
     case XK_Scroll_Lock:    return Qt::Key_ScrollLock;
     case XK_Super_L:        return Qt::Key_Super_L;
     case XK_Super_R:        return Qt::Key_Super_R;
     case XK_Menu:       return Qt::Key_Menu;
     default:
     string[0] = sym;
     string[1] = '\0';
     return toupper(sym);
     }
 }
translateModifiers()
static Qt::KeyboardModifiers translateModifiers (int s) static
Definition at line 163 of file qwaylandinputdevice.cpp.
Referenced by QWaylandInputDevice::inputHandleKey(), and QWaylandInputDevice::inputHandleKeyboardFocus().
 {
     const uchar qt_alt_mask = XKB_COMMON_MOD1_MASK;
     const uchar qt_meta_mask = XKB_COMMON_MOD4_MASK;
     Qt::KeyboardModifiers ret = 0;
     if (s & XKB_COMMON_SHIFT_MASK)
     ret |= Qt::ShiftModifier;
     if (s & XKB_COMMON_CONTROL_MASK)
     ret |= Qt::ControlModifier;
     if (s & qt_alt_mask)
     ret |= Qt::AltModifier;
     if (s & qt_meta_mask)
     ret |= Qt::MetaModifier;
     return ret;
 }