Qt 4.8: /src/gui/kernel/qwidgetcreate_x11.cpp File Reference
qwidgetcreate_x11.cpp File Reference
#include "qwidget.h"
#include "qt_x11_p.h"
Functions
Window qt_XCreateSimpleWindow (const QWidget *, Display *display, Window parent, int x, int y, uint w, uint h, int borderwidth, ulong border, ulong background)
Window qt_XCreateWindow (const QWidget *, Display *display, Window parent, int x, int y, uint w, uint h, int borderwidth, int depth, uint windowclass, Visual *visual, ulong valuemask, XSetWindowAttributes *attributes)
void qt_XDestroyWindow (const QWidget *, Display *display, Window window)
Function Documentation
qt_XCreateSimpleWindow()
Window qt_XCreateSimpleWindow (const QWidget * , Display * display, Window parent, int x, int y, uint w, uint h, int borderwidth, ulong border, ulong background)
Definition at line 64 of file qwidgetcreate_x11.cpp.
Referenced by getNetWmState().
 {
     return XCreateSimpleWindow(display, parent, x, y, w, h, borderwidth,
                                 border, background);
 }
qt_XCreateWindow()
Window qt_XCreateWindow (const QWidget * , Display * display, Window parent, int x, int y, uint w, uint h, int borderwidth, int depth, uint windowclass, Visual * visual, ulong valuemask, XSetWindowAttributes * attributes)
Definition at line 53 of file qwidgetcreate_x11.cpp.
Referenced by getNetWmState().
 {
     return XCreateWindow(display, parent, x, y, w, h, borderwidth, depth,
                           windowclass, visual, valuemask, attributes);
 }
qt_XDestroyWindow()
void qt_XDestroyWindow (const QWidget * , Display * display, Window window)
Definition at line 73 of file qwidgetcreate_x11.cpp.
Referenced by getNetWmState(), and QWidgetPrivate::isBackgroundInherited().
 {
     if (window)
         XDestroyWindow(display, window);
 }