Qt 4.8: /src/gui/kernel/qwidget_p.h File Reference
qwidget_p.h File Reference
#include "QtGui/qwidget.h"
#include "private/qobject_p.h"
#include "QtCore/qrect.h"
#include "QtCore/qlocale.h"
#include "QtCore/qset.h"
#include "QtGui/qregion.h"
#include "QtGui/qsizepolicy.h"
#include "QtGui/qstyle.h"
#include "QtGui/qapplication.h"
#include <private/qgraphicseffect_p.h>
#include "QtGui/qgraphicsproxywidget.h"
#include "QtGui/qgraphicsscene.h"
#include "QtGui/qgraphicsview.h"
#include <private/qgesture_p.h>
#include "QtCore/qt_windows.h"
#include <private/qdnd_p.h>
#include "QtGui/qx11info_x11.h"
#include <private/qt_mac_p.h>
#include "QtGui/qinputcontext.h"
#include "QtGui/qscreen_qws.h"
Classes
struct QTLWExtra
struct QWExtra
class QWidgetBackingStoreTracker
Class which allows tracking of which widgets are using a given backing store.
class QWidgetEffectSourcePrivate
struct QWidgetPaintContext
class QWidgetPrivate
Functions
static bool bypassGraphicsProxyWidget (const QWidget *p)
Returns true if p or any of its parents enable the Qt::BypassGraphicsProxyWidget window flag.
Function Documentation
bypassGraphicsProxyWidget()
static bool bypassGraphicsProxyWidget (const QWidget * p) inline static
Returns true if p or any of its parents enable the Qt::BypassGraphicsProxyWidget window flag.
Warning
This function is not part of the public interface.
Used in QWidget::show() and QWidget::setParent() to determine whether it's necessary to embed the widget into a QGraphicsProxyWidget or not.
Definition at line 353 of file qwidget_p.h.
Referenced by QGraphicsProxyWidget::contextMenuEvent(), QWidgetPrivate::hide_helper(), QMenu::popup(), QWidgetPrivate::screenGeometry(), QWidget::setParent(), and QWidgetPrivate::show_helper().
 {
     while (p) {
         if (p->windowFlags() & Qt::BypassGraphicsProxyWidget)
             return true;
         p = p->parentWidget();
     }
     return false;
 }