Qt 4.8: /src/gui/kernel/qwidget_mac.mm File Reference
qwidget_mac.mm File Reference
#include <private/qt_mac_p.h>
#include <private/qeventdispatcher_mac_p.h>
#include "qapplication.h"
#include "qapplication_p.h"
#include "qbitmap.h"
#include "qcursor.h"
#include "qdesktopwidget.h"
#include "qevent.h"
#include "qfileinfo.h"
#include "qimage.h"
#include "qlayout.h"
#include "qmenubar.h"
#include <private/qbackingstore_p.h>
#include <private/qwindowsurface_mac_p.h>
#include <private/qpaintengine_mac_p.h>
#include "qpainter.h"
#include "qstyle.h"
#include "qtimer.h"
#include "qfocusframe.h"
#include "qdebug.h"
#include <private/qmainwindowlayout_p.h>
#include <private/qabstractscrollarea_p.h>
#include <qabstractscrollarea.h>
#include <ApplicationServices/ApplicationServices.h>
#include <limits.h>
#include <private/qt_cocoa_helpers_mac_p.h>
#include <private/qcocoaview_mac_p.h>
#include <private/qcocoawindow_mac_p.h>
#include <private/qcocoawindowdelegate_mac_p.h>
#include <private/qcocoapanel_mac_p.h>
#include "qwidget_p.h"
#include "qevent_p.h"
#include "qdnd_p.h"
#include <QtGui/qgraphicsproxywidget.h>
#include "qmainwindow.h"
Classes
struct QPaintEngineCleanupHandler
Macros
#define HIViewInstallEventHandler(target, handler, numTypes, list, userData, outHandlerRef) InstallEventHandler(HIObjectGetEventTarget((HIObjectRef) (target)), (handler), (numTypes), (list), (userData), (outHandlerRef))
#define kHIViewFeatureIgnoresClicks kHIViewIgnoresClicks
#define kHIViewScrollRectAdjustInvalid 1
#define kHIViewScrollRectDontInvalidateRevealedArea 2
#define ReleaseWindowGroup(x) Are you sure you wanted to do that? (you wanted qt_mac_release_window_group)
#define S "com.trolltech.qt-" S0(QT_NAMESPACE) ".widget"
#define S0(x) SS(x)
#define SF(x) ((x > max_f) ? max_f : x)
#define SS(x) #x
#define WRECT_MAX 8191
#define XCOORD_MAX 16383
Typedefs
typedef QHash< Qt::WindowFlags, WindowGroupRef > WindowGroupHash
Enumerations
enum { kWidgetPropertyQWidget = 'QWId' }
enum {
kEventClassGesture = 'gest', kEventGestureStarted = 1, kEventGestureEnded = 2, kEventGestureMagnify = 4,
kEventGestureSwipe = 5, kEventGestureRotate = 6, kEventParamRotationAmount = 'rota', kEventParamSwipeDirection = 'swip',
kEventParamMagnificationAmount = 'magn'
}
Functions
OSStatus _HIViewScrollRectWithOptions (HIViewRef, const HIRect *, CGFloat, CGFloat, OptionBits) __attribute__((weak))
static void cleanup_widget_eventUPP ()
static void cleanup_win_eventUPP ()
NSComparisonResult compareViews2Lower (id view1, id view2, void *context)
NSComparisonResult compareViews2Raise (id view1, id view2, void *context)
NSComparisonResult compareViews2StackUnder (id view1, id view2, void *context)
static const EventHandlerUPP make_widget_eventUPP ()
static const EventHandlerUPP make_win_eventUPP ()
bool qt_event_remove_activate ()
void qt_event_request_activate (QWidget *)
void qt_event_request_showsheet (QWidget *)
void qt_event_request_window_change (QWidget *)
static bool qt_isGenuineQWidget (OSViewRef ref)
bool qt_isGenuineQWidget (const QWidget *window)
bool qt_mac_can_clickThrough (const QWidget *w)
QRegion qt_mac_convert_mac_region (RgnHandle rgn)
CGImageRef qt_mac_create_cgimage (const QPixmap &, bool)
IconRef qt_mac_create_iconref (const QPixmap &)
OSViewRef qt_mac_create_widget (QWidget *widget, QWidgetPrivate *widgetPrivate, OSViewRef parent)
static OSWindowRef qt_mac_create_window (QWidget *, WindowClass wclass, WindowAttributes wattr, const QRect &crect)
static QSize qt_mac_desktopSize ()
static void qt_mac_destructDrawer (NSDrawer *drawer)
static void qt_mac_destructView (OSViewRef view)
static void qt_mac_destructWindow (OSWindowRef window)
Q_GUI_EXPORT OSViewRef qt_mac_effectiveview_for (const QWidget *w)
void qt_mac_event_release (QWidget *w)
QWidget * qt_mac_find_window (OSWindowRef window)
Q_GUI_EXPORT OSViewRef qt_mac_get_contentview_for (OSWindowRef w)
SInt32 qt_mac_get_group_level (WindowClass wclass)
RgnHandle qt_mac_get_rgn ()
bool qt_mac_insideKeyWindow (const QWidget *w)
bool qt_mac_is_macdrawer (const QWidget *w)
bool qt_mac_is_macsheet (const QWidget *w)
QWidget * qt_mac_modal_blocked (QWidget *)
QPoint qt_mac_nativeMapFromParent (const QWidget *child, const QPoint &pt)
Q_GUI_EXPORT OSViewRef qt_mac_nativeview_for (const QWidget *w)
Q_GUI_EXPORT QPoint qt_mac_posInWindow (const QWidget *w)
static void qt_mac_release_stays_on_top_group (WindowGroupRef group)
static void qt_mac_release_window_group (WindowGroupRef group)
bool qt_mac_sendMacEventToWidget (QWidget *widget, EventRef ref)
void qt_mac_set_cursor (const QCursor *, const QPoint &)
bool qt_mac_set_drawer_preferred_edge (QWidget *w, Qt::DockWidgetArea where)
static void qt_mac_set_fullscreen_mode (bool b)
void Q_GUI_EXPORT qt_mac_set_raise_process (bool b)
static void qt_mac_set_window_group (OSWindowRef window, Qt::WindowFlags flags, int level)
static void qt_mac_set_window_group_to_popup (OSWindowRef window)
static void qt_mac_set_window_group_to_stays_on_top (OSWindowRef window, Qt::WindowType type)
static void qt_mac_set_window_group_to_tooltip (OSWindowRef window)
void qt_mac_setMouseGrabCursor (bool set, QCursor *cursor=0)
void qt_mac_unregister_widget ()
void qt_mac_update_cursor ()
static void qt_mac_update_widget_position (QWidget *q, QRect oldRect, QRect newRect)
void qt_mac_updateParentUnderAlienWidget (QWidget *alienWidget)
Q_GUI_EXPORT OSWindowRef qt_mac_window_for (OSViewRef view)
Q_GUI_EXPORT OSWindowRef qt_mac_window_for (const QWidget *w)
QMainWindowLayout * qt_mainwindow_layout (const QMainWindow *window)
bool qt_nograb ()
static bool updateRedirectedToGraphicsProxyWidget (QWidget *widget, const QRect &rect)
static bool updateRedirectedToGraphicsProxyWidget (QWidget *widget, const QRegion &rgn)
Variables
static CFStringRef kObjectQWidget = CFSTR(S)
const UInt32 kWidgetCreatorQt = kEventClassQt
QWidget * mac_keyboard_grabber = 0
QWidget * mac_mouse_grabber = 0
static EventHandlerUPP mac_widget_eventUPP = 0
static EventHandlerUPP mac_win_eventUPP = 0
QPointer< QWidget > qt_button_down
QPointer< QWidget > qt_last_mouse_receiver
QPointer< QWidget > qt_last_native_mouse_receiver
static bool qt_mac_raise_process = true
static OSWindowRef qt_root_win = 0
QPointer< QWidget > topLevelAt_cache
static HIObjectClassRef widget_class = 0
static EventTypeSpec widget_events []
static EventTypeSpec window_events []
Macro Definition Documentation
HIViewInstallEventHandler
#define HIViewInstallEventHandler (target, handler, numTypes, list, userData, outHandlerRef) InstallEventHandler(HIObjectGetEventTarget((HIObjectRef) (target)), (handler), (numTypes), (list), (userData), (outHandlerRef))
Referenced by QWidgetPrivate::create_sys().
kHIViewFeatureIgnoresClicks
#define kHIViewFeatureIgnoresClicks kHIViewIgnoresClicks
Referenced by QWidgetPrivate::setModal_sys().
kHIViewScrollRectAdjustInvalid
#define kHIViewScrollRectAdjustInvalid 1
Definition at line 129 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::scroll_sys().
kHIViewScrollRectDontInvalidateRevealedArea
#define kHIViewScrollRectDontInvalidateRevealedArea 2
Definition at line 130 of file qwidget_mac.mm.
ReleaseWindowGroup
#define ReleaseWindowGroup (x) Are you sure you wanted to do that? (you wanted qt_mac_release_window_group)
Definition at line 536 of file qwidget_mac.mm.
Referenced by qt_mac_release_window_group().
S
#define S "com.trolltech.qt-" S0(QT_NAMESPACE) ".widget"
Definition at line 165 of file qwidget_mac.mm.
Referenced by _qdtoa().
S0
#define S0 (x) SS(x)
Definition at line 164 of file qwidget_mac.mm.
SF
#define SF (x) ((x > max_f) ? max_f : x)
Referenced by qt_mac_update_widget_position().
SS
#define SS (x) #x
Definition at line 163 of file qwidget_mac.mm.
WRECT_MAX
#define WRECT_MAX 8191
Definition at line 121 of file qwidget_mac.mm.
Referenced by qt_mac_update_widget_position().
XCOORD_MAX
#define XCOORD_MAX 16383
Definition at line 120 of file qwidget_mac.mm.
Referenced by qt_mac_update_widget_position().
Typedef Documentation
WindowGroupHash
typedef QHash<Qt::WindowFlags, WindowGroupRef> WindowGroupHash
Definition at line 146 of file qwidget_mac.mm.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
kWidgetPropertyQWidget
Definition at line 149 of file qwidget_mac.mm.
      {
     kWidgetPropertyQWidget = 'QWId' //QWidget *
 };
anonymous enum
anonymous enum
Enumerator
kEventClassGesture
kEventGestureStarted
kEventGestureEnded
kEventGestureMagnify
kEventGestureSwipe
kEventGestureRotate
kEventParamRotationAmount
kEventParamSwipeDirection
kEventParamMagnificationAmount
Definition at line 803 of file qwidget_mac.mm.
      {
     kEventClassGesture              = 'gest',
     kEventGestureStarted            = 1,
     kEventGestureEnded              = 2,
     kEventGestureMagnify            = 4,
     kEventGestureSwipe              = 5,
     kEventGestureRotate             = 6,
     kEventParamRotationAmount       = 'rota',
     kEventParamSwipeDirection       = 'swip',
     kEventParamMagnificationAmount  = 'magn'
 };
Function Documentation
_HIViewScrollRectWithOptions()
OSStatus _HIViewScrollRectWithOptions (HIViewRef , const HIRect * , CGFloat , CGFloat , OptionBits)
Referenced by QWidgetPrivate::scroll_sys().
cleanup_widget_eventUPP()
static void cleanup_widget_eventUPP () static
Definition at line 1227 of file qwidget_mac.mm.
Referenced by make_widget_eventUPP().
 {
     DisposeEventHandlerUPP(mac_widget_eventUPP);
     mac_widget_eventUPP = 0;
 }
cleanup_win_eventUPP()
static void cleanup_win_eventUPP () static
Definition at line 841 of file qwidget_mac.mm.
Referenced by make_win_eventUPP().
 {
     DisposeEventHandlerUPP(mac_win_eventUPP);
     mac_win_eventUPP = 0;
 }
compareViews2Lower()
NSComparisonResult compareViews2Lower (id view1, id view2, void * context)
Definition at line 4005 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::lower_sys().
 {
     id topView = reinterpret_cast<id>(context);
     if (view1 == topView)
         return NSOrderedAscending;
     if (view2 == topView)
         return NSOrderedDescending;
     return NSOrderedSame;
 }
compareViews2Raise()
NSComparisonResult compareViews2Raise (id view1, id view2, void * context)
Definition at line 3927 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::raise_sys().
 {
     id topView = reinterpret_cast<id>(context);
     if (view1 == topView)
         return NSOrderedDescending;
     if (view2 == topView)
         return NSOrderedAscending;
     return NSOrderedSame;
 }
compareViews2StackUnder()
NSComparisonResult compareViews2StackUnder (id view1, id view2, void * context)
Definition at line 4041 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::stackUnder_sys().
 {
     const QHash<NSView *, int> &viewOrder = *reinterpret_cast<QHash<NSView *, int> *>(context);
     if (viewOrder[view1] < viewOrder[view2])
         return NSOrderedAscending;
     if (viewOrder[view1] > viewOrder[view2])
         return NSOrderedDescending;
     return NSOrderedSame;
 }
make_widget_eventUPP()
static const EventHandlerUPP make_widget_eventUPP () static
Definition at line 1232 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::create_sys(), and qt_mac_create_widget().
 {
     if(mac_widget_eventUPP)
         return mac_widget_eventUPP;
     qAddPostRoutine(cleanup_widget_eventUPP);
     return mac_widget_eventUPP = NewEventHandlerUPP(QWidgetPrivate::qt_widget_event);
 }
make_win_eventUPP()
static const EventHandlerUPP make_win_eventUPP () static
Definition at line 846 of file qwidget_mac.mm.
Referenced by qt_mac_unregister_widget().
 {
     if(mac_win_eventUPP)
         return mac_win_eventUPP;
     qAddPostRoutine(cleanup_win_eventUPP);
     return mac_win_eventUPP = NewEventHandlerUPP(QWidgetPrivate::qt_window_event);
 }
qt_event_remove_activate()
bool qt_event_remove_activate ()
Definition at line 884 of file qapplication_mac.mm.
Referenced by QWidget::activateWindow(), qt_event_activate_timer_callbk(), and qt_event_request_activate().
 {
     if (request_activate_pending.timer) {
         RemoveEventLoopTimer(request_activate_pending.timer);
         request_activate_pending.timer = 0;
     }
     if (request_activate_pending.event)
         qt_mac_event_release(request_activate_pending.event);
     return true;
 }
qt_event_request_activate()
void qt_event_request_activate (QWidget *)
Definition at line 911 of file qapplication_mac.mm.
Referenced by QWidgetPrivate::hide_sys(), and QWidgetPrivate::show_sys().
 {
     if (w == request_activate_pending.widget)
         return;
     /* We put these into a timer because due to order of events being sent we need to be sure this
        comes from inside of the event loop */
     qt_event_remove_activate();
     if (!request_activate_pending.timerUPP)
         request_activate_pending.timerUPP = NewEventLoopTimerUPP(qt_event_activate_timer_callbk);
     request_activate_pending.widget = w;
     InstallEventLoopTimer(GetMainEventLoop(), 0, 0, request_activate_pending.timerUPP, 0, &request_activate_pending.timer);
 }
qt_event_request_showsheet()
void qt_event_request_showsheet (QWidget *)
Definition at line 748 of file qapplication_mac.mm.
Referenced by QWidgetPrivate::show_sys().
 {
     Q_ASSERT(qt_mac_is_macsheet(w));
 #ifdef QT_MAC_USE_COCOA
     w->repaint();
     [NSApp beginSheet:qt_mac_window_for(w) modalForWindow:qt_mac_window_for(w->parentWidget())
         modalDelegate:nil didEndSelector:nil contextInfo:0];
 #else
     qt_mac_event_remove(request_showsheet_pending);
     CreateEvent(0, kEventClassQt, kEventQtRequestShowSheet, GetCurrentEventTime(),
                 kEventAttributeUserEvent, &request_showsheet_pending);
     SetEventParameter(request_showsheet_pending, kEventParamQWidget, typeQWidget, sizeof(w), &w);
     PostEventToQueue(GetMainEventQueue(), request_showsheet_pending, kEventPriorityStandard);
 #endif
 }
qt_event_request_window_change()
void qt_event_request_window_change (QWidget *)
Definition at line 858 of file qapplication_mac.mm.
Referenced by QWidgetPrivate::hide_sys(), QWidgetPrivate::lower_sys(), make_widget_eventUPP(), make_win_eventUPP(), QWidgetPrivate::raise_sys(), QWidgetPrivate::scroll_sys(), QWidgetPrivate::setGeometry_sys(), QWidgetPrivate::setParent_sys(), QWidget::setWindowState(), QWidgetPrivate::show_sys(), and QWidgetPrivate::stackUnder_sys().
 {
     if (!widget)
         return;
     // Post a kEventQtRequestWindowChange event. This event is semi-public,
     // don't remove this line!
     qt_event_request_window_change();
     // Post update request on gl widgets unconditionally.
     if (qt_widget_private(widget)->isGLWidget == true) {
         qt_post_window_change_event(widget);
         return;
     }
     qt_mac_update_child_gl_widgets(widget);
     qt_mac_update_intersected_gl_widgets(widget);
 }
qt_isGenuineQWidget() [1/2]
static bool qt_isGenuineQWidget (OSViewRef ref) static
Definition at line 464 of file qwidget_mac.mm.
Referenced by make_widget_eventUPP(), qt_isGenuineQWidget(), qt_mac_window_for(), and QWidgetPrivate::setParent_sys().
 {
 #ifdef QT_MAC_USE_COCOA
     return [ref isKindOfClass:[QT_MANGLE_NAMESPACE(QCocoaView) class]];
 #else
     return HIObjectIsOfClass(HIObjectRef(ref), kObjectQWidget);
 #endif
 }
qt_isGenuineQWidget() [2/2]
bool qt_isGenuineQWidget (const QWidget * window)
Definition at line 473 of file qwidget_mac.mm.
Referenced by QApplicationPrivate::globalEventProcessor().
 {
     if (!window)
         return false;
     if (!window->internalWinId())
         return true;  //alien
     return qt_isGenuineQWidget(OSViewRef(window->internalWinId()));
 }
qt_mac_can_clickThrough()
bool qt_mac_can_clickThrough (const QWidget * w)
Definition at line 280 of file qwidget_mac.mm.
Referenced by QApplicationPrivate::globalEventProcessor(), QStyleOption::init(), and QWidget::setForegroundRole().
 {
     static int qt_mac_carbon_clickthrough = -1;
     if (qt_mac_carbon_clickthrough < 0)
         qt_mac_carbon_clickthrough = !qgetenv("QT_MAC_NO_COCOA_CLICKTHROUGH").isEmpty();
     bool ret = !qt_mac_carbon_clickthrough;
     for ( ; w; w = w->parentWidget()) {
         if (w->testAttribute(Qt::WA_MacNoClickThrough)) {
             ret = false;
             break;
         }
     }
     return ret;
 }
qt_mac_convert_mac_region()
QRegion qt_mac_convert_mac_region (RgnHandle rgn)
Referenced by make_widget_eventUPP(), and qt_mac_unregister_widget().
qt_mac_create_cgimage()
CGImageRef qt_mac_create_cgimage (const QPixmap & , bool)
qt_mac_create_iconref()
IconRef qt_mac_create_iconref (const QPixmap &)
Definition at line 1109 of file qpixmap_mac.cpp.
Referenced by QWidgetPrivate::setWindowIcon_sys().
 {
     if (px.isNull())
         return 0;
     //create icon
     IconFamilyHandle iconFamily = reinterpret_cast<IconFamilyHandle>(NewHandle(0));
     //create data
     {
         struct {
             OSType mac_type;
             int width, height, depth;
             bool mask;
         } images[] = {
             { kThumbnail32BitData, 128, 128, 32, false },
             { kThumbnail8BitMask, 128, 128, 8, true },
             { 0, 0, 0, 0, false } //end marker
         };
         for(int i = 0; images[i].mac_type; i++) {
             //get QPixmap data
             QImage scaled_px = px.toImage().scaled(images[i].width, images[i].height);
             quint32 *sptr = (quint32 *) scaled_px.bits();
             quint32 *srow;
             uint sbpr = scaled_px.bytesPerLine();
             //get Handle data
             const int dbpr = images[i].width * (images[i].depth/8);
             Handle hdl = NewHandle(dbpr*images[i].height);
             if(!sptr) { //handle null pixmap
                 memset((*hdl), '\0', dbpr*images[i].height);
             } else if(images[i].mask) {
                 if(images[i].mac_type == kThumbnail8BitMask) {
                     for(int y = 0, hindex = 0; y < images[i].height; ++y) {
                         srow = sptr + (y * (sbpr/4));
                         for(int x = 0; x < images[i].width; ++x)
                             *((*hdl)+(hindex++)) = qAlpha(*(srow+x));
                     }
                 }
             } else {
                 char *dest = (*hdl);
 #if defined(__i386__)
                 if(images[i].depth == 32) {
                     for(int y = 0; y < images[i].height; ++y) {
                         uint *source = (uint*)((const uchar*)sptr+(sbpr*y));
                         for(int x = 0; x < images[i].width; ++x, dest += 4)
                             *((uint*)dest) = CFSwapInt32(*(source + x));
                     }
                 } else
 #endif
                 {
                     for(int y = 0; y < images[i].height; ++y)
                         memcpy(dest+(y*dbpr), ((const uchar*)sptr+(sbpr*y)), dbpr);
                 }
             }
             //set the family data to the Handle
             OSStatus set = SetIconFamilyData(iconFamily, images[i].mac_type, hdl);
             if(set != noErr)
                 qWarning("%s: %d -- Unable to create icon data[%d]!! %ld",
                          __FILE__, __LINE__, i, long(set));
             DisposeHandle(hdl);
         }
     }
     //acquire and cleanup
     IconRef ret;
     static int counter = 0;
     const OSType kQtCreator = 'CUTE';
     RegisterIconRefFromIconFamily(kQtCreator, (OSType)counter, iconFamily, &ret);
     AcquireIconRef(ret);
     UnregisterIconRef(kQtCreator, (OSType)counter);
     DisposeHandle(reinterpret_cast<Handle>(iconFamily));
     counter++;
     return ret;
 }
qt_mac_create_widget()
OSViewRef qt_mac_create_widget (QWidget * widget, QWidgetPrivate * widgetPrivate, OSViewRef parent)
Definition at line 1602 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::create_sys(), QMacNativeWidget::QMacNativeWidget(), and qt_mac_unregister_widget().
 {
 #ifdef QT_MAC_USE_COCOA
     QMacCocoaAutoReleasePool pool;
     QT_MANGLE_NAMESPACE(QCocoaView) *view = [[QT_MANGLE_NAMESPACE(QCocoaView) alloc] initWithQWidget:widget widgetPrivate:widgetPrivate];
 #ifdef ALIEN_DEBUG
     qDebug() << "Creating NSView for" << widget;
 #endif
     if (view && parent)
         [parent addSubview:view];
     return view;
 #else
     Q_UNUSED(widget);
     Q_UNUSED(widgetPrivate);
     if(!widget_class) {
         OSStatus err = HIObjectRegisterSubclass(kObjectQWidget, kHIViewClassID, 0, make_widget_eventUPP(),
                                                 GetEventTypeCount(widget_events), widget_events,
                                                 0, &widget_class);
         if (err && err != hiObjectClassExistsErr)
             qWarning("QWidget: Internal error (%d)", __LINE__);
     }
     HIViewRef ret = 0;
     if(HIObjectCreate(kObjectQWidget, 0, (HIObjectRef*)&ret) != noErr)
         qWarning("QWidget: Internal error (%d)", __LINE__);
     if(ret && parent)
         HIViewAddSubview(parent, ret);
     return ret;
 #endif
 }
qt_mac_create_window()
static OSWindowRef qt_mac_create_window (QWidget * , WindowClass wclass, WindowAttributes wattr, const QRect & crect) static
Definition at line 778 of file qwidget_mac.mm.
Referenced by qt_mac_unregister_widget(), and updateRedirectedToGraphicsProxyWidget().
 {
     OSWindowRef window;
     Rect geo;
     SetRect(&geo, crect.left(), crect.top(), crect.right() + 1, crect.bottom() + 1);
     OSStatus err;
     if(geo.right <= geo.left)       geo.right = geo.left + 1;
     if(geo.bottom <= geo.top)       geo.bottom = geo.top + 1;
     Rect null_rect;
     SetRect(&null_rect, 0, 0, 1, 1);
     err = CreateNewWindow(wclass, wattr, &null_rect, &window);
     if(err == noErr) {
         err = SetWindowBounds(window, kWindowContentRgn, &geo);
         if(err != noErr)
             qWarning("QWidget: Internal error (%s:%d)", __FILE__, __LINE__);
     }
     return window;
 }
qt_mac_desktopSize()
static QSize qt_mac_desktopSize () static
Definition at line 203 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::create_sys(), and qt_mac_unregister_widget().
 {
     int w = 0, h = 0;
     CGDisplayCount cg_count;
     CGGetActiveDisplayList(0, 0, &cg_count);
     QVector<CGDirectDisplayID> displays(cg_count);
     CGGetActiveDisplayList(cg_count, displays.data(), &cg_count);
     Q_ASSERT(cg_count == (CGDisplayCount)displays.size());
     for(int i = 0; i < (int)cg_count; ++i) {
         CGRect r = CGDisplayBounds(displays.at(i));
         w = qMax<int>(w, qRound(r.origin.x + r.size.width));
         h = qMax<int>(h, qRound(r.origin.y + r.size.height));
     }
     return QSize(w, h);
 }
qt_mac_destructDrawer()
static void qt_mac_destructDrawer (NSDrawer * drawer) static
Definition at line 270 of file qwidget_mac.mm.
Referenced by QWidget::destroy(), and QWidgetPrivate::setParent_sys().
 {
 #ifdef QT_MAC_USE_COCOA
     [[QT_MANGLE_NAMESPACE(QCocoaWindowDelegate) sharedDelegate] resignDelegateForDrawer:drawer];
     [drawer release];
 #else
     Q_UNUSED(drawer);
 #endif
 }
qt_mac_destructView()
static void qt_mac_destructView (OSViewRef view) static
Definition at line 235 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::create_sys(), QWidget::destroy(), and QWidgetPrivate::setParent_sys().
 {
 #ifdef QT_MAC_USE_COCOA
     NSWindow *window = [view window];
     if ([window contentView] == view) {
         NSView* newView = [[NSView alloc] initWithFrame:[view bounds]];
         [window setContentView:newView];
         [newView release];
     } else {
         [view removeFromSuperview];
         [view release];
     }
 #else
     HIViewRemoveFromSuperview(view);
     CFRelease(view);
 #endif
 }
qt_mac_destructWindow()
static void qt_mac_destructWindow (OSWindowRef window) static
Definition at line 253 of file qwidget_mac.mm.
Referenced by QWidget::destroy(), qt_mac_unregister_widget(), and QWidgetPrivate::setParent_sys().
 {
 #ifdef QT_MAC_USE_COCOA
     if ([window isVisible] && [window isSheet]){
         [NSApp endSheet:window];
         [window orderOut:window];
     }
     [[QT_MANGLE_NAMESPACE(QCocoaWindowDelegate) sharedDelegate] resignDelegateForWindow:window];
     [window release];
 #else
     // Remove property to clean up memory:
     RemoveWindowProperty(window, kWidgetCreatorQt, kWidgetPropertyQWidget);
     CFRelease(window);
 #endif
 }
qt_mac_effectiveview_for()
Q_GUI_EXPORT OSViewRef qt_mac_effectiveview_for (const QWidget * w)
Definition at line 424 of file qwidget_mac.mm.
Referenced by flipPoint(), QMacWindowFader::performFade(), qt_mac_window_for(), QWidgetPrivate::registerDropSite(), and QWidgetPrivate::setFocus_sys().
 {
     // Get the first non-alien (parent) widget for
     // w, and return its NSView (if it has one):
     return reinterpret_cast<OSViewRef>(w->effectiveWinId());
 }
qt_mac_event_release()
void qt_mac_event_release (QWidget * w)
Definition at line 1002 of file qapplication_mac.mm.
Referenced by QWidget::destroy(), and QWidgetPrivate::hide_sys().
 {
     if (w) {
 #ifndef QT_MAC_USE_COCOA
         qt_mac_event_release(w, request_showsheet_pending);
         qt_mac_event_release(w, request_context_pending);
 #endif
         if (w == qt_mac_dock_menu) {
             qt_mac_dock_menu = 0;
 #ifndef QT_MAC_USE_COCOA
             SetApplicationDockTileMenu(0);
 #else
             [NSApp setDockMenu:0];
 #endif
         }
     }
 }
qt_mac_find_window()
QWidget* qt_mac_find_window (OSWindowRef window)
Definition at line 391 of file qwidget_mac.mm.
Referenced by QApplicationPrivate::globalEventProcessor(), QWidgetPrivate::hide_sys(), make_win_eventUPP(), onApplicationChangedActivation(), qt_mac_window_at(), and QApplicationPrivate::tryModalHelper_sys().
 {
 #ifdef QT_MAC_USE_COCOA
     return [window QT_MANGLE_NAMESPACE(qt_qwidget)];
 #else
     if(!window)
         return 0;
     QWidget *ret;
     if(GetWindowProperty(window, kWidgetCreatorQt, kWidgetPropertyQWidget, sizeof(ret), 0, &ret) == noErr)
         return ret;
     return 0;
 #endif
 }
qt_mac_get_contentview_for()
Q_GUI_EXPORT OSViewRef qt_mac_get_contentview_for (OSWindowRef w)
Definition at line 431 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::create_sys(), qt_mac_unregister_widget(), and QWidgetPrivate::show_sys().
 {
 #ifdef QT_MAC_USE_COCOA
     return [w contentView];
 #else
     HIViewRef contentView = 0;
     OSStatus err = GetRootControl(w, &contentView);  // Returns the window's content view (Apple QA1214)
     if (err == errUnknownControl) {
         contentView = HIViewGetRoot(w);
     } else if (err != noErr) {
         qWarning("Qt:Could not get content or root view of window! %s:%d [%ld]",
                  __FILE__, __LINE__, err);
     }
     return contentView;
 #endif
 }
qt_mac_get_group_level()
SInt32 qt_mac_get_group_level (WindowClass wclass)
Definition at line 538 of file qwidget_mac.mm.
Referenced by qt_mac_set_window_group_to_popup(), qt_mac_set_window_group_to_stays_on_top(), and qt_mac_set_window_group_to_tooltip().
 {
     SInt32 group_level;
     CGWindowLevel tmpLevel;
     GetWindowGroupLevelOfType(GetWindowGroupOfClass(wclass), kWindowGroupLevelActive, &tmpLevel);
     group_level = tmpLevel;
     return group_level;
 }
qt_mac_get_rgn()
RgnHandle qt_mac_get_rgn ()
Referenced by qt_mac_unregister_widget().
qt_mac_insideKeyWindow()
bool qt_mac_insideKeyWindow (const QWidget * w)
Definition at line 311 of file qwidget_mac.mm.
Referenced by QWidget::previousInFocusChain().
 {
 #ifdef QT_MAC_USE_COCOA
     return [[reinterpret_cast<NSView *>(w->effectiveWinId()) window] isKeyWindow];
 #else
     Q_UNUSED(w);
 #endif
     return false;
 }
qt_mac_is_macdrawer()
bool qt_mac_is_macdrawer (const QWidget * w)
Definition at line 306 of file qwidget_mac.mm.
Referenced by QWidget::activateWindow(), QMainWindow::addDockWidget(), QWidget::destroy(), QApplicationPrivate::globalEventProcessor(), QWidgetPrivate::hide_sys(), QWidget::previousInFocusChain(), qt_mac_set_drawer_preferred_edge(), qt_mac_unregister_widget(), QDockAreaLayoutInfo::restoreState(), QWidgetPrivate::setParent_sys(), QWidgetPrivate::show_sys(), and IsWindowAndNotDrawerOrSheetTest::test().
 {
     return (w && w->parentWidget() && w->windowType() == Qt::Drawer);
 }
qt_mac_is_macsheet()
bool qt_mac_is_macsheet (const QWidget * w)
Definition at line 295 of file qwidget_mac.mm.
Referenced by QFileDialogPrivate::createNavServicesDialog(), QApplicationPrivate::enterModal_sys(), QApplicationPrivate::globalEventProcessor(), QWidgetPrivate::hide_sys(), QFileDialogPrivate::hideCarbonNavServicesDialog(), QApplicationPrivate::leaveModal_sys(), make_win_eventUPP(), qt_event_request_showsheet(), qt_mac_unregister_widget(), QWidgetPrivate::show_sys(), QFontDialogPrivate::showCocoaFontPanel(), IsWindowAndNotDrawerOrSheetTest::test(), and QApplicationPrivate::tryModalHelper_sys().
 {
     if (!w)
         return false;
     Qt::WindowModality modality = w->windowModality();
     if (modality == Qt::ApplicationModal)
         return false;
     return w->parentWidget() && (modality == Qt::WindowModal || w->windowType() == Qt::Sheet);
 }
qt_mac_modal_blocked()
QWidget* qt_mac_modal_blocked (QWidget *)
qt_mac_nativeMapFromParent()
QPoint qt_mac_nativeMapFromParent (const QWidget * child, const QPoint & pt)
Definition at line 3576 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::childAtRecursiveHelper().
 {
 #ifndef QT_MAC_USE_COCOA
     CGPoint nativePoint = CGPointMake(pt.x(), pt.y());
     HIViewConvertPoint(&nativePoint, qt_mac_nativeview_for(child->parentWidget()),
                        qt_mac_nativeview_for(child));
 #else
     NSPoint nativePoint = [qt_mac_nativeview_for(child) convertPoint:NSMakePoint(pt.x(), pt.y()) fromView:qt_mac_nativeview_for(child->parentWidget())];
 #endif
     return QPoint(nativePoint.x, nativePoint.y);
 }
qt_mac_nativeview_for()
Q_GUI_EXPORT OSViewRef qt_mac_nativeview_for (const QWidget * w)
Definition at line 419 of file qwidget_mac.mm.
Referenced by QMenuPrivate::QMacMenuPrivate::addAction(), QWidgetPrivate::create_sys(), QWidget::destroy(), QWidgetPrivate::hide_sys(), QWidgetPrivate::lower_sys(), make_widget_eventUPP(), make_win_eventUPP(), QWidget::mapFromGlobal(), QWidget::mapToGlobal(), QWidget::metric(), qt_mac_dispatchPendingUpdateRequests(), qt_mac_handleTabletEvent(), qt_mac_nativeMapFromParent(), qt_mac_post_retranslateAppMenu(), qt_mac_tablet_hash(), qt_mac_unregister_widget(), qt_mac_update_intersected_gl_widgets(), qt_mac_update_mouseTracking(), qt_mac_update_widget_position(), qt_mac_window_for(), QWidgetPrivate::raise_sys(), QWidgetPrivate::registerDropSite(), QWidgetPrivate::scroll_sys(), QWidgetPrivate::setFocus_sys(), QWidgetPrivate::setGeometry_sys(), QWidgetPrivate::setMask_sys(), QWidgetPrivate::setModal_sys(), QWidgetPrivate::setParent_sys(), QWidgetPrivate::show_sys(), QWidgetPrivate::stackUnder_sys(), QGLContext::updatePaintDevice(), and updateRedirectedToGraphicsProxyWidget().
 {
     return reinterpret_cast<OSViewRef>(w->internalWinId());
 }
qt_mac_posInWindow()
Q_GUI_EXPORT QPoint qt_mac_posInWindow (const QWidget * w)
Definition at line 380 of file qwidget_mac.mm.
Referenced by make_widget_eventUPP(), and qt_mac_get_widget_rgn().
 {
     QPoint ret = w->data->wrect.topLeft();
     while(w && !w->isWindow()) {
         ret += w->pos();
         w =  w->parentWidget();
     }
     return ret;
 }
qt_mac_release_stays_on_top_group()
static void qt_mac_release_stays_on_top_group (WindowGroupRef group) static
Definition at line 518 of file qwidget_mac.mm.
Referenced by qt_mac_release_window_group().
 {
     for (WindowGroupHash::iterator it = qt_mac_window_groups()->begin(); it != qt_mac_window_groups()->end(); ++it) {
         if (it.value() == group) {
             qt_mac_window_groups()->remove(it.key());
             return;
         }
     }
 }
qt_mac_release_window_group()
static void qt_mac_release_window_group (WindowGroupRef group) static
Definition at line 530 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::deleteTLSysExtra(), and qt_mac_unregister_widget().
 {
     ReleaseWindowGroup(group);
     if (GetWindowGroupRetainCount(group) == 0)
         qt_mac_release_stays_on_top_group(group);
 }
qt_mac_sendMacEventToWidget()
bool qt_mac_sendMacEventToWidget (QWidget * widget, EventRef ref)
Definition at line 448 of file qwidget_mac.mm.
Referenced by flipPoint(), qt_dispatchKeyEvent(), and qt_mac_handleTabletEvent().
 {
     return widget->macEvent(0, ref);
 }
qt_mac_set_cursor()
void qt_mac_set_cursor (const QCursor * , const QPoint &)
qt_mac_set_drawer_preferred_edge()
bool qt_mac_set_drawer_preferred_edge (QWidget * w, Qt::DockWidgetArea where)
Definition at line 321 of file qwidget_mac.mm.
Referenced by QMainWindow::addDockWidget(), and QDockAreaLayoutInfo::restoreState().
 {
     if(!qt_mac_is_macdrawer(w))
         return false;
 #if QT_MAC_USE_COCOA
     NSDrawer *drawer = qt_mac_drawer_for(w);
     if (!drawer)
         return false;
     NSRectEdge  edge;
     if (where & Qt::LeftDockWidgetArea)
         edge = NSMinXEdge;
     else if (where & Qt::RightDockWidgetArea)
         edge = NSMaxXEdge;
     else if (where & Qt::TopDockWidgetArea)
         edge = NSMaxYEdge;
     else if (where & Qt::BottomDockWidgetArea)
         edge = NSMinYEdge;
     else
         return false;
     if (edge == [drawer preferredEdge]) //no-op
         return false;
     if (w->isVisible()) {
         [drawer close];
         [drawer openOnEdge:edge];
     }
     [drawer setPreferredEdge:edge];
 #else
     OSWindowRef window = qt_mac_window_for(w);
     OptionBits edge;
     if(where & Qt::LeftDockWidgetArea)
         edge = kWindowEdgeLeft;
     else if(where & Qt::RightDockWidgetArea)
         edge = kWindowEdgeRight;
     else if(where & Qt::TopDockWidgetArea)
         edge = kWindowEdgeTop;
     else if(where & Qt::BottomDockWidgetArea)
         edge = kWindowEdgeBottom;
     else
         return false;
     if(edge == GetDrawerPreferredEdge(window)) //no-op
         return false;
     //do it
     SetDrawerPreferredEdge(window, edge);
     if(w->isVisible()) {
         CloseDrawer(window, false);
         OpenDrawer(window, edge, true);
     }
 #endif
     return true;
 }
qt_mac_set_fullscreen_mode()
static void qt_mac_set_fullscreen_mode (bool b) inline static
Definition at line 406 of file qwidget_mac.mm.
Referenced by QWidget::activateWindow(), QWidgetPrivate::hide_sys(), and QWidget::setWindowState().
 {
     extern bool qt_mac_app_fullscreen; //qapplication_mac.mm
     if(qt_mac_app_fullscreen == b)
         return;
     qt_mac_app_fullscreen = b;
     if (b) {
         SetSystemUIMode(kUIModeAllHidden, kUIOptionAutoShowMenuBar);
     } else {
         SetSystemUIMode(kUIModeNormal, 0);
     }
 }
qt_mac_set_raise_process()
void Q_GUI_EXPORT qt_mac_set_raise_process (bool b)
Definition at line 202 of file qwidget_mac.mm.
 { qt_mac_raise_process = b; }
qt_mac_set_window_group()
static void qt_mac_set_window_group (OSWindowRef window, Qt::WindowFlags flags, int level) static
Definition at line 549 of file qwidget_mac.mm.
Referenced by qt_mac_set_window_group_to_popup(), qt_mac_set_window_group_to_stays_on_top(), and qt_mac_set_window_group_to_tooltip().
 {
     WindowGroupRef group = 0;
     if (qt_mac_window_groups()->contains(flags)) {
         group = qt_mac_window_groups()->value(flags);
         RetainWindowGroup(group);
     } else {
         CreateWindowGroup(kWindowActivationScopeNone, &group);
         SetWindowGroupLevel(group, level);
         SetWindowGroupParent(group, GetWindowGroupOfClass(kAllWindowClasses));
         qt_mac_window_groups()->insert(flags, group);
     }
     SetWindowGroup(window, group);
 }
qt_mac_set_window_group_to_popup()
static void qt_mac_set_window_group_to_popup (OSWindowRef window) inline static
Definition at line 582 of file qwidget_mac.mm.
Referenced by qt_mac_unregister_widget().
 {
     // In Qt, a popup is seen as a 'stay on top' window.
     // Since new groups are created for 'stays on top' windows, the
     // same must be done for popups. Otherwise, popups would be drawn
     // below 'stays on top' windows. Add 1 to get above pure stay-on-top windows.
     qt_mac_set_window_group(window, Qt::Popup, qt_mac_get_group_level(kOverlayWindowClass)+1);
 }
qt_mac_set_window_group_to_stays_on_top()
static void qt_mac_set_window_group_to_stays_on_top (OSWindowRef window, Qt::WindowType type) inline static
Definition at line 564 of file qwidget_mac.mm.
Referenced by qt_mac_unregister_widget().
 {
     // We create one static stays on top window group so that
     // all stays on top (aka popups) will fall into the same
     // group and be able to be raise()'d with releation to one another (from
     // within the same window group).
     qt_mac_set_window_group(window, type|Qt::WindowStaysOnTopHint, qt_mac_get_group_level(kOverlayWindowClass));
 }
qt_mac_set_window_group_to_tooltip()
static void qt_mac_set_window_group_to_tooltip (OSWindowRef window) inline static
Definition at line 573 of file qwidget_mac.mm.
Referenced by qt_mac_unregister_widget().
 {
     // Since new groups are created for 'stays on top' windows, the
     // same must be done for tooltips. Otherwise, tooltips would be drawn
     // below 'stays on top' widgets even tough they are on the same level.
     // Also, add 'two' to the group level to make sure they also get on top of popups.
     qt_mac_set_window_group(window, Qt::ToolTip, qt_mac_get_group_level(kHelpWindowClass)+2);
 }
qt_mac_setMouseGrabCursor()
void qt_mac_setMouseGrabCursor (bool set, QCursor * cursor = 0)
Definition at line 227 of file qcursor_mac.mm.
Referenced by QWidget::grabMouse(), and QWidget::releaseMouse().
 {
     if (grabCursor) {
         delete grabCursor;
         grabCursor = 0;
     }
     if (set) {
         if (cursor)
             grabCursor = new QCursor(*cursor);
         else if (lastMouseCursorWidget)
             grabCursor = new QCursor(lastMouseCursorWidget->cursor());
         else
             grabCursor = new QCursor(Qt::ArrowCursor);
     }
     qt_mac_update_cursor();
 }
qt_mac_unregister_widget()
void qt_mac_unregister_widget ()
Definition at line 1634 of file qwidget_mac.mm.
Referenced by qt_cleanup().
 {
 #ifndef QT_MAC_USE_COCOA
     HIObjectUnregisterClass(widget_class);
     widget_class = 0;
 #endif
 }
qt_mac_update_cursor()
void qt_mac_update_cursor ()
Definition at line 201 of file qcursor_mac.mm.
Referenced by QWidgetPrivate::hide_sys(), qt_mac_setMouseGrabCursor(), QWidgetPrivate::setCursor_sys(), QWidgetPrivate::show_sys(), and QWidgetPrivate::unsetCursor_sys().
 {
     // This function is similar to qt_mac_updateCursorWithWidgetUnderMouse
     // except that is clears the optimization cache, and finds the widget
     // under mouse itself. Clearing the cache is useful in cases where the
     // application has been deactivated/activated etc.
     // NB: since we dont have any true native widget, the call to
     // qt_mac_getTargetForMouseEvent will fail when the mouse is over QMacNativeWidgets.
 #ifdef QT_MAC_USE_COCOA
     lastWidgetUnderMouse = 0;
     lastMouseCursorWidget = 0;
     QWidget *widgetUnderMouse = 0;
     if (qt_button_down) {
         widgetUnderMouse = qt_button_down;
     } else {
         QPoint localPoint;
         QPoint globalPoint;
         qt_mac_getTargetForMouseEvent(0, QEvent::None, localPoint, globalPoint, 0, &widgetUnderMouse);
     }
     qt_mac_updateCursorWithWidgetUnderMouse(widgetUnderMouse);
 #else
     qt_mac_updateCursorWithWidgetUnderMouse(QApplication::widgetAt(QCursor::pos()));
 #endif
 }
qt_mac_update_widget_position()
static void qt_mac_update_widget_position (QWidget * q, QRect oldRect, QRect newRect) static
Definition at line 4092 of file qwidget_mac.mm.
 {
     HIRect bounds = CGRectMake(newRect.x(), newRect.y(),
                                newRect.width(), newRect.height());
     const HIViewRef view = qt_mac_nativeview_for(q);
     const bool isMove = (oldRect.topLeft() != newRect.topLeft());
     const bool isResize = (oldRect.size() != newRect.size());
 //    qDebug() << oldRect << newRect << isMove << isResize << q->testAttribute(Qt::WA_OpaquePaintEvent) << q->testAttribute(Qt::WA_StaticContents);
     QWidgetPrivate *qd = qt_widget_private(q);
     // Perform a normal (complete repaint) update in some cases:
     if (
         // always repaint on move.
         (isMove) ||
         // limited update on resize requires WA_StaticContents.
         (isResize && q->testAttribute(Qt::WA_StaticContents) == false) ||
         // one of the rects are invalid
         (oldRect.isValid() == false || newRect.isValid() == false)  ||
         // the position update is a part of a drag-and-drop operation
         QDragManager::self()->object ||
         // we are on Panther (no HIViewSetNeedsDisplayInRect)
         QSysInfo::MacintoshVersion < QSysInfo::MV_10_4
     ){
         HIViewSetFrame(view, &bounds);
         return;
     }
     const int dx = newRect.x() - oldRect.x();
     const int dy = newRect.y() - oldRect.y();
     if (isMove) {
         // HIViewScrollRect silently fails if we try to scroll anything under the grow box.
         // Check if there's one present within the widget rect, and if there is fall back
         // to repainting the entire widget.
         QWidget const * const parentWidget = q->parentWidget();
         const HIViewRef parentView = qt_mac_nativeview_for(parentWidget);
         HIViewRef nativeSizeGrip = 0;
         if (q->testAttribute(Qt::WA_WState_Created))
             HIViewFindByID(HIViewGetRoot(HIViewGetWindow(HIViewRef(q->winId()))), kHIViewWindowGrowBoxID, &nativeSizeGrip);
         if (nativeSizeGrip) {
             QWidget * const window = q->window();
             const int sizeGripSize = 20;
             const QRect oldWidgetRect = QRect(q->mapTo(window, QPoint(0, 0)), QSize(oldRect.width(), oldRect.height()));
             const QRect newWidgetRect = QRect(q->mapTo(window, QPoint(0, 0)), QSize(newRect.width(), newRect.height()));
             const QRect sizeGripRect = QRect(window->rect().bottomRight() - QPoint(sizeGripSize, sizeGripSize),
                                              window->rect().bottomRight());
             if (sizeGripRect.intersects(oldWidgetRect) || sizeGripRect.intersects(newWidgetRect)) {
                 HIViewSetFrame(view, &bounds);
                 return;
             }
         }
         // Don't scroll anything outside the parent widget rect.
         const QRect scrollRect = (oldRect | newRect) & parentWidget->rect();
         const HIRect scrollBounds =
             CGRectMake(scrollRect.x(), scrollRect.y(), scrollRect.width(), scrollRect.height());
         // We cannot scroll when the widget has a mask as that would
         // scroll the masked out areas too
         if (qd->extra && qd->extra->hasMask) {
             HIViewMoveBy(view, dx, dy);
             return;
         }
         OSStatus err = HIViewScrollRect(parentView, &scrollBounds, dx, dy);
         if (err != noErr) {
             HIViewSetNeedsDisplay(view, true);
             qWarning("QWidget: Internal error (%s:%d)", __FILE__, __LINE__);
         }
     }
     // Set the view bounds with drawing disabled to prevent repaints.
     HIViewSetDrawingEnabled(view, false);
     HIViewSetFrame(view, &bounds);
     HIViewSetDrawingEnabled(view, true);
     // Update any newly exposed areas due to resizing.
     const int startx = oldRect.width();
     const int stopx = newRect.width();
     const int starty = oldRect.height();
     const int stopy = newRect.height();
     const HIRect verticalSlice = CGRectMake(startx, 0, stopx , stopy);
     HIViewSetNeedsDisplayInRect(view, &verticalSlice, true);
     const HIRect horizontalSlice = CGRectMake(0, starty, startx, stopy);
     HIViewSetNeedsDisplayInRect(view, &horizontalSlice, true);
 }
qt_mac_updateParentUnderAlienWidget()
void qt_mac_updateParentUnderAlienWidget (QWidget * alienWidget)
Definition at line 2740 of file qwidget_mac.mm.
Referenced by QWidget::destroy(), and QWidgetPrivate::hide_sys().
 {
     QWidget *nativeParent = alienWidget->nativeParentWidget();
     if (!nativeParent)
         return;
     QPoint globalPos = alienWidget->mapToGlobal(QPoint(0, 0));
     QRect dirtyRect = QRect(nativeParent->mapFromGlobal(globalPos), alienWidget->size());
     nativeParent->update(dirtyRect);
 }
qt_mac_window_for() [1/2]
Q_GUI_EXPORT OSWindowRef qt_mac_window_for (OSViewRef view)
Definition at line 453 of file qwidget_mac.mm.
Referenced by QWidget::activateWindow(), QWidgetPrivate::create_sys(), QWidget::destroy(), QWidgetPrivate::hide_sys(), QWidgetPrivate::lower_sys(), make_widget_eventUPP(), QWidget::mapFromGlobal(), QWidget::mapToGlobal(), qt_mac_set_drawer_preferred_edge(), qt_mac_unregister_widget(), qt_mac_update_widget_position(), qt_mac_window_for(), QWidgetPrivate::raise_sys(), QWidgetPrivate::registerDropSite(), QWidgetPrivate::setConstraints_sys(), QWidgetPrivate::setFocus_sys(), QWidgetPrivate::setGeometry_sys(), QWidgetPrivate::setMask_sys(), QWidgetPrivate::setModal_sys(), QWidgetPrivate::setParent_sys(), QWidgetPrivate::setWindowIcon_sys(), QWidgetPrivate::setWindowIconText_sys(), QWidgetPrivate::setWindowOpacity_sys(), QWidget::setWindowState(), QWidgetPrivate::setWindowTitle_sys(), QWidgetPrivate::show_sys(), QWidgetPrivate::updateFrameStrut(), and updateRedirectedToGraphicsProxyWidget().
 {
 #ifdef QT_MAC_USE_COCOA
     if (view)
         return [view window];
     return 0;
 #else
     return HIViewGetWindow(view);
 #endif
 }
qt_mac_window_for() [2/2]
Q_GUI_EXPORT OSWindowRef qt_mac_window_for (const QWidget * w)
Definition at line 484 of file qwidget_mac.mm.
Referenced by QMainWindowLayout::cleanUpMacToolbarItems(), QPrintDialogPrivate::closeCarbonPrintPanel(), QFileDialogPrivate::createNavServicesDialog(), QCoreGraphicsPaintEngine::end(), flipPoint(), QMacWindowSurface::flush(), QRasterWindowSurface::flush(), QEventDispatcherMac::flush(), QApplicationPrivate::globalEventProcessor(), QToolBarPrivate::init(), QMainWindowLayout::insertIntoMacToolbar(), macWindowToolbarShow(), QPageSetupDialogPrivate::openCarbonPageLayout(), QPrintDialogPrivate::openCarbonPrintPanel(), QMacWindowFader::performFade(), qt_event_request_showsheet(), qt_mac_grabScreenRect_10_3(), qt_mac_graphicsContextFor(), qt_mac_is_metal(), qt_mac_post_retranslateAppMenu(), QMainWindowLayout::removeFromMacToolbar(), QMainWindowLayout::toggleToolBarsVisible(), QApplicationPrivate::tryModalHelper_sys(), QMainWindowLayout::updateHIToolBarStatus(), and QTabBarPrivate::updateMacBorderMetrics().
 {
     if (OSViewRef hiview = qt_mac_effectiveview_for(w)) {
         OSWindowRef window = qt_mac_window_for(hiview);
         if (window)
             return window;
         if (qt_isGenuineQWidget(hiview)) {
             // This is a workaround for NSToolbar. When a widget is hidden
             // by clicking the toolbar button, Cocoa reparents the widgets
             // to another window (but Qt doesn't know about it).
             // When we start showing them, it reparents back,
             // but at this point it's window is nil, but the window it's being brought
             // into (the Qt one) is for sure created.
             // This stops the hierarchy moving under our feet.
             QWidget *toplevel = w->window();
             if (toplevel != w) {
                 hiview = qt_mac_nativeview_for(toplevel);
                 if (OSWindowRef w = qt_mac_window_for(hiview))
                     return w;
             }
             toplevel->d_func()->createWindow_sys();
             // Reget the hiview since "create window" could potentially move the view (I guess).
             hiview = qt_mac_nativeview_for(toplevel);
             return qt_mac_window_for(hiview);
         }
     }
     return 0;
 }
qt_mainwindow_layout()
QMainWindowLayout * qt_mainwindow_layout (const QMainWindow * window)
Definition at line 111 of file qmainwindow.cpp.
Referenced by QMainWindowLayoutState::apply(), qt_mac_unregister_widget(), QWidgetPrivate::setModal_sys(), and QWidgetPrivate::setParent_sys().
 {
     return QMainWindowPrivate::mainWindowLayout(mainWindow);
 }
qt_nograb()
bool qt_nograb ()
Definition at line 482 of file qapplication_mac.mm.
Referenced by QWidget::grabKeyboard(), QWidget::grabMouse(), QWidget::releaseKeyboard(), and QWidget::releaseMouse().
 {
 #if defined(QT_DEBUG)
     return appNoGrab;
 #else
     return false;
 #endif
 }
updateRedirectedToGraphicsProxyWidget() [1/2]
static bool updateRedirectedToGraphicsProxyWidget (QWidget * widget, const QRect & rect) inline static
Definition at line 592 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::createDefaultWindowSurface_sys().
 {
     if (!widget)
         return false;
 #ifndef QT_NO_GRAPHICSVIEW
     QWidget *tlw = widget->window();
     QWExtra *extra = qt_widget_private(tlw)->extra;
     if (extra && extra->proxyWidget) {
         extra->proxyWidget->update(rect.translated(widget->mapTo(tlw, QPoint())));
         return true;
     }
 #endif
     return false;
 }
updateRedirectedToGraphicsProxyWidget() [2/2]
static bool updateRedirectedToGraphicsProxyWidget (QWidget * widget, const QRegion & rgn) inline static
Definition at line 609 of file qwidget_mac.mm.
 {
     if (!widget)
         return false;
 #ifndef QT_NO_GRAPHICSVIEW
     QWidget *tlw = widget->window();
     QWExtra *extra = qt_widget_private(tlw)->extra;
     if (extra && extra->proxyWidget) {
         const QPoint offset(widget->mapTo(tlw, QPoint()));
         const QVector<QRect> rects = rgn.rects();
         for (int i = 0; i < rects.size(); ++i)
             extra->proxyWidget->update(rects.at(i).translated(offset));
         return true;
     }
 #endif
     return false;
 }
Variable Documentation
kObjectQWidget
CFStringRef kObjectQWidget = CFSTR(S) static
Definition at line 167 of file qwidget_mac.mm.
Referenced by make_widget_eventUPP(), qt_isGenuineQWidget(), and qt_mac_create_widget().
kWidgetCreatorQt
const UInt32 kWidgetCreatorQt = kEventClassQt
Definition at line 148 of file qwidget_mac.mm.
Referenced by macWindowFade(), qt_mac_destructWindow(), qt_mac_find_window(), and qt_mac_unregister_widget().
mac_keyboard_grabber
QWidget* mac_keyboard_grabber = 0
Definition at line 157 of file qwidget_mac.mm.
Referenced by QApplicationPrivate::globalEventProcessor(), QWidget::keyboardGrabber(), and qt_wstate_iconified().
mac_mouse_grabber
QWidget* mac_mouse_grabber = 0
Definition at line 156 of file qwidget_mac.mm.
Referenced by flipPoint(), QApplicationPrivate::globalEventProcessor(), QWidget::mouseGrabber(), QMacWindowFader::performFade(), and qt_wstate_iconified().
mac_widget_eventUPP
EventHandlerUPP mac_widget_eventUPP = 0 static
Definition at line 1226 of file qwidget_mac.mm.
Referenced by cleanup_widget_eventUPP(), and make_widget_eventUPP().
mac_win_eventUPP
EventHandlerUPP mac_win_eventUPP = 0 static
Definition at line 840 of file qwidget_mac.mm.
Referenced by cleanup_win_eventUPP(), and make_win_eventUPP().
qt_button_down
QPointer<QWidget> qt_button_down
Definition at line 188 of file qapplication_mac.mm.
Referenced by QApplicationPrivate::globalEventProcessor(), QETWidget::translateMouseEvent(), and QETWidget::translateTabletEvent().
qt_last_mouse_receiver
QPointer<QWidget> qt_last_mouse_receiver
Definition at line 189 of file qapplication_mac.mm.
qt_last_native_mouse_receiver
QPointer<QWidget> qt_last_native_mouse_receiver
Referenced by flipPoint().
qt_mac_raise_process
bool qt_mac_raise_process = true static
Definition at line 154 of file qwidget_mac.mm.
Referenced by qt_mac_set_raise_process(), and QWidgetPrivate::raise_sys().
qt_root_win
OSWindowRef qt_root_win = 0 static
Definition at line 155 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::create_sys(), QWidget::destroy(), qt_mac_unregister_widget(), and updateRedirectedToGraphicsProxyWidget().
topLevelAt_cache
QPointer<QWidget> topLevelAt_cache
Definition at line 168 of file qapplication_mac.mm.
widget_class
HIObjectClassRef widget_class = 0 static
Definition at line 1202 of file qwidget_mac.mm.
Referenced by qt_mac_create_widget(), and qt_mac_unregister_widget().
widget_events
EventTypeSpec widget_events[] static
Initial value:
= {
    { kEventClassHIObject, kEventHIObjectConstruct },
    { kEventClassHIObject, kEventHIObjectDestruct },
    { kEventClassControl, kEventControlDraw },
    { kEventClassControl, kEventControlInitialize },
    { kEventClassControl, kEventControlGetPartRegion },
    { kEventClassControl, kEventControlGetClickActivation },
    { kEventClassControl, kEventControlSetFocusPart },
    { kEventClassControl, kEventControlDragEnter },
    { kEventClassControl, kEventControlDragWithin },
    { kEventClassControl, kEventControlDragLeave },
    { kEventClassControl, kEventControlDragReceive },
    { kEventClassControl, kEventControlOwningWindowChanged },
    { kEventClassControl, kEventControlBoundsChanged },
    { kEventClassControl, kEventControlGetSizeConstraints },
    { kEventClassControl, kEventControlVisibilityChanged },
    { kEventClassMouse, kEventMouseDown },
    { kEventClassMouse, kEventMouseUp },
    { kEventClassMouse, kEventMouseMoved },
    { kEventClassMouse, kEventMouseDragged }
}
Definition at line 1203 of file qwidget_mac.mm.
Referenced by QWidgetPrivate::create_sys(), and qt_mac_create_widget().
window_events
EventTypeSpec window_events[] static
Initial value:
= {
    { kEventClassWindow, kEventWindowClose },
    { kEventClassWindow, kEventWindowExpanded },
    { kEventClassWindow, kEventWindowHidden },
    { kEventClassWindow, kEventWindowZoom },
    { kEventClassWindow, kEventWindowZoomed },
    { kEventClassWindow, kEventWindowCollapsed },
    { kEventClassWindow, kEventWindowToolbarSwitchMode },
    { kEventClassWindow, kEventWindowProxyBeginDrag },
    { kEventClassWindow, kEventWindowProxyEndDrag },
    { kEventClassWindow, kEventWindowResizeCompleted },
    { kEventClassWindow, kEventWindowBoundsChanging },
    { kEventClassWindow, kEventWindowGetRegion },
    { kEventClassWindow, kEventWindowGetClickModality },
    { kEventClassWindow, kEventWindowTransitionCompleted },
    { kEventClassGesture, kEventGestureStarted },
    { kEventClassGesture, kEventGestureEnded },
    { kEventClassGesture, kEventGestureMagnify },
    { kEventClassGesture, kEventGestureSwipe },
    { kEventClassGesture, kEventGestureRotate },
    { kEventClassMouse, kEventMouseDown }
}
Definition at line 818 of file qwidget_mac.mm.
Referenced by qt_mac_unregister_widget().