Qt 4.8: /src/gui/kernel/qwidget_x11.cpp File Reference
qwidget_x11.cpp File Reference
#include "qevent.h"
#include "qwidget.h"
#include "qdesktopwidget.h"
#include "qapplication.h"
#include "qapplication_p.h"
#include "qabstracteventdispatcher.h"
#include "qnamespace.h"
#include "qpainter.h"
#include "qbitmap.h"
#include "qlayout.h"
#include "qtextcodec.h"
#include "qelapsedtimer.h"
#include "qcursor.h"
#include "qstack.h"
#include "qcolormap.h"
#include "qdebug.h"
#include "qmenu.h"
#include "private/qmenu_p.h"
#include "private/qbackingstore_p.h"
#include "private/qwindowsurface_x11_p.h"
#include <private/qpixmap_x11_p.h>
#include <private/qpaintengine_x11_p.h>
#include "qt_x11_p.h"
#include "qx11info_x11.h"
#include <stdlib.h>
#include "qinputcontext.h"
#include "qinputcontextfactory.h"
#include "qwidget_p.h"
Classes
struct QtMWMHints
struct QX11WindowAttributes
Macros
#define WRECT_MAX 8191
#define XCOORD_MAX 16383
Enumerations
enum {
MWM_HINTS_FUNCTIONS = (1L << 0), MWM_FUNC_ALL = (1L << 0), MWM_FUNC_RESIZE = (1L << 1), MWM_FUNC_MOVE = (1L << 2),
MWM_FUNC_MINIMIZE = (1L << 3), MWM_FUNC_MAXIMIZE = (1L << 4), MWM_FUNC_CLOSE = (1L << 5), MWM_HINTS_DECORATIONS = (1L << 1),
MWM_DECOR_ALL = (1L << 0), MWM_DECOR_BORDER = (1L << 1), MWM_DECOR_RESIZEH = (1L << 2), MWM_DECOR_TITLE = (1L << 3),
MWM_DECOR_MENU = (1L << 4), MWM_DECOR_MINIMIZE = (1L << 5), MWM_DECOR_MAXIMIZE = (1L << 6), MWM_HINTS_INPUT_MODE = (1L << 2),
MWM_INPUT_MODELESS = 0L, MWM_INPUT_PRIMARY_APPLICATION_MODAL = 1L, MWM_INPUT_FULL_APPLICATION_MODAL = 3L
}
Functions
static void create_wm_client_leader ()
static void do_size_hints (QWidget *widget, QWExtra *x)
static QtMWMHints GetMWMHints (Display *display, Window window)
static QVector< Atom > getNetWmState (QWidget *w)
static bool isTransient (const QWidget *w)
static XTextProperty * qstring_to_xtp (const QString &s)
void qt_change_net_wm_state (const QWidget *w, bool set, Atom one, Atom two=0)
static void qt_insert_sip (QWidget *scrolled_widget, int dx, int dy)
void qt_net_remove_user_time (QWidget *tlw)
void qt_net_update_user_time (QWidget *tlw, unsigned long timestamp)
bool qt_nograb ()
static int qt_sip_count (QWidget *scrolled_widget)
void qt_x11_enforce_cursor (QWidget *w, bool force)
Update the X11 cursor of the widget w.
Q_GUI_EXPORT void qt_x11_enforce_cursor (QWidget *w)
void qt_x11_getX11InfoForWindow (QX11Info *xinfo, const XWindowAttributes &a)
void qt_x11_getX11InfoForWindow (QX11Info *xinfo, const QX11WindowAttributes &att)
static void qt_x11_recreateNativeWidgetsRecursive (QWidget *widget)
static void qt_x11_recreateWidget (QWidget *widget)
void qt_x11_wait_for_window_manager (QWidget *w, bool sendPostedEvents)
Q_GUI_EXPORT void qt_x11_wait_for_window_manager (QWidget *w)
Window qt_XCreateSimpleWindow (const QWidget *creator, Display *display, Window parent, int x, int y, uint w, uint h, int borderwidth, ulong border, ulong background)
Window qt_XCreateWindow (const QWidget *creator, Display *display, Window parent, int x, int y, uint w, uint h, int borderwidth, int depth, uint windowclass, Visual *visual, ulong valuemask, XSetWindowAttributes *attributes)
void qt_XDestroyWindow (const QWidget *destroyer, Display *display, Window window)
static void SetMWMHints (Display *display, Window window, const QtMWMHints &mwmhints)
Variables
int qt_x11_create_desktop_on_screen = -1
const uint stdDesktopEventMask
const uint stdWidgetEventMask
Macro Definition Documentation
WRECT_MAX
#define WRECT_MAX 8191
Definition at line 87 of file qwidget_x11.cpp.
Referenced by do_size_hints().
XCOORD_MAX
#define XCOORD_MAX 16383
Definition at line 86 of file qwidget_x11.cpp.
Referenced by do_size_hints(), and getNetWmState().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MWM_HINTS_FUNCTIONS
MWM_FUNC_ALL
MWM_FUNC_RESIZE
MWM_FUNC_MOVE
MWM_FUNC_MINIMIZE
MWM_FUNC_MAXIMIZE
MWM_FUNC_CLOSE
MWM_HINTS_DECORATIONS
MWM_DECOR_ALL
MWM_DECOR_BORDER
MWM_DECOR_RESIZEH
MWM_DECOR_TITLE
MWM_DECOR_MENU
MWM_DECOR_MINIMIZE
MWM_DECOR_MAXIMIZE
MWM_HINTS_INPUT_MODE
MWM_INPUT_MODELESS
MWM_INPUT_PRIMARY_APPLICATION_MODAL
MWM_INPUT_FULL_APPLICATION_MODAL
Definition at line 110 of file qwidget_x11.cpp.
      {
     MWM_HINTS_FUNCTIONS   = (1L << 0),
     MWM_FUNC_ALL      = (1L << 0),
     MWM_FUNC_RESIZE   = (1L << 1),
     MWM_FUNC_MOVE     = (1L << 2),
     MWM_FUNC_MINIMIZE = (1L << 3),
     MWM_FUNC_MAXIMIZE = (1L << 4),
     MWM_FUNC_CLOSE    = (1L << 5),
     MWM_HINTS_DECORATIONS = (1L << 1),
     MWM_DECOR_ALL      = (1L << 0),
     MWM_DECOR_BORDER   = (1L << 1),
     MWM_DECOR_RESIZEH  = (1L << 2),
     MWM_DECOR_TITLE    = (1L << 3),
     MWM_DECOR_MENU     = (1L << 4),
     MWM_DECOR_MINIMIZE = (1L << 5),
     MWM_DECOR_MAXIMIZE = (1L << 6),
     MWM_HINTS_INPUT_MODE = (1L << 2),
     MWM_INPUT_MODELESS                  = 0L,
     MWM_INPUT_PRIMARY_APPLICATION_MODAL = 1L,
     MWM_INPUT_FULL_APPLICATION_MODAL    = 3L
 };
Function Documentation
create_wm_client_leader()
static void create_wm_client_leader () static
Definition at line 266 of file qwidget_x11.cpp.
Referenced by getNetWmState().
 {
     if (X11->wm_client_leader) return;
     X11->wm_client_leader =
         XCreateSimpleWindow(X11->display,
                              QX11Info::appRootWindow(),
                              0, 0, 1, 1, 0, 0, 0);
     // set client leader property to itself
     XChangeProperty(X11->display,
                      X11->wm_client_leader, ATOM(WM_CLIENT_LEADER),
                      XA_WINDOW, 32, PropModeReplace,
                      (unsigned char *)&X11->wm_client_leader, 1);
 #ifndef QT_NO_SESSIONMANAGER
     // If we are session managed, inform the window manager about it
     QByteArray session = qApp->sessionId().toLatin1();
     if (!session.isEmpty()) {
         XChangeProperty(X11->display,
                          X11->wm_client_leader, ATOM(SM_CLIENT_ID),
                          XA_STRING, 8, PropModeReplace,
                          (unsigned char *)session.data(), session.size());
     }
 #endif
 }
do_size_hints()
static void do_size_hints (QWidget * widget, QWExtra * x) static
Definition at line 2311 of file qwidget_x11.cpp.
Referenced by isTransient(), and qstring_to_xtp().
 {
     Q_ASSERT(widget->testAttribute(Qt::WA_WState_Created));
     XSizeHints s;
     memset(&s, 0, sizeof(s));
     if (x) {
         QRect g = widget->geometry();
         s.x = g.x();
         s.y = g.y();
         s.width = g.width();
         s.height = g.height();
         if (x->minw > 0 || x->minh > 0) {
             // add minimum size hints
             s.flags |= PMinSize;
             s.min_width  = qMin(XCOORD_MAX, x->minw);
             s.min_height = qMin(XCOORD_MAX, x->minh);
         }
         if (x->maxw < QWIDGETSIZE_MAX || x->maxh < QWIDGETSIZE_MAX) {
             // add maximum size hints
             s.flags |= PMaxSize;
             s.max_width  = qMin(XCOORD_MAX, x->maxw);
             s.max_height = qMin(XCOORD_MAX, x->maxh);
         }
         if (x->topextra &&
             (x->topextra->incw > 0 || x->topextra->inch > 0)) {
             // add resize increment hints
             s.flags |= PResizeInc | PBaseSize;
             s.width_inc = x->topextra->incw;
             s.height_inc = x->topextra->inch;
             s.base_width = x->topextra->basew;
             s.base_height = x->topextra->baseh;
         }
     }
     if (widget->testAttribute(Qt::WA_Moved)) {
         // user (i.e. command-line) specified position
         s.flags |= USPosition;
         s.flags |= PPosition;
     }
     if (widget->testAttribute(Qt::WA_Resized)) {
         // user (i.e. command-line) specified size
         s.flags |= USSize;
         s.flags |= PSize;
     }
     s.flags |= PWinGravity;
     if (widget->testAttribute(Qt::WA_Moved) && x && x->topextra && !x->topextra->posFromMove) {
         // position came from setGeometry(), tell the WM that we don't
         // want our window gravity-shifted
         s.win_gravity = StaticGravity;
     } else {
         // position came from move()
         s.x = widget->x();
         s.y = widget->y();
         s.win_gravity = QApplication::isRightToLeft() ? NorthEastGravity : NorthWestGravity;
     }
     if (widget->internalWinId())
         XSetWMNormalHints(X11->display, widget->internalWinId(), &s);
 }
GetMWMHints()
static QtMWMHints GetMWMHints (Display * display, Window window) static
Definition at line 138 of file qwidget_x11.cpp.
Referenced by do_size_hints(), and qstring_to_xtp().
 {
     QtMWMHints mwmhints;
     Atom type;
     int format;
     ulong nitems, bytesLeft;
     uchar *data = 0;
     if ((XGetWindowProperty(display, window, ATOM(_MOTIF_WM_HINTS), 0, 5, false,
                             ATOM(_MOTIF_WM_HINTS), &type, &format, &nitems, &bytesLeft,
                             &data) == Success)
         && (type == ATOM(_MOTIF_WM_HINTS)
             && format == 32
             && nitems >= 5)) {
         mwmhints = *(reinterpret_cast<QtMWMHints *>(data));
     } else {
         mwmhints.flags = 0L;
         mwmhints.functions = MWM_FUNC_ALL;
         mwmhints.decorations = MWM_DECOR_ALL;
         mwmhints.input_mode = 0L;
         mwmhints.status = 0L;
     }
     if (data)
         XFree(data);
     return mwmhints;
 }
getNetWmState()
static QVector<Atom> getNetWmState (QWidget * w) static
Definition at line 445 of file qwidget_x11.cpp.
Referenced by qstring_to_xtp(), and QXlibWindow::visual().
 {
     QVector<Atom> returnValue;
     // Don't read anything, just get the size of the property data
     Atom actualType;
     int actualFormat;
     ulong propertyLength;
     ulong bytesLeft;
     uchar *propertyData = 0;
     if (XGetWindowProperty(X11->display, w->internalWinId(), ATOM(_NET_WM_STATE), 0, 0,
                            False, XA_ATOM, &actualType, &actualFormat,
                            &propertyLength, &bytesLeft, &propertyData) == Success
         && actualType == XA_ATOM && actualFormat == 32) {
         returnValue.resize(bytesLeft / 4);
         XFree((char*) propertyData);
         propertyData = 0;
         // fetch all data
         if (XGetWindowProperty(X11->display, w->internalWinId(), ATOM(_NET_WM_STATE), 0,
                                returnValue.size(), False, XA_ATOM, &actualType, &actualFormat,
                                &propertyLength, &bytesLeft, &propertyData) != Success) {
             returnValue.clear();
         } else if (propertyLength != (ulong)returnValue.size()) {
             returnValue.resize(propertyLength);
         }
         // put it into netWmState
         if (!returnValue.isEmpty()) {
             memcpy(returnValue.data(), propertyData, returnValue.size() * sizeof(Atom));
         }
         if (propertyData)
             XFree((char*) propertyData);
     }
     return returnValue;
 }
isTransient()
static bool isTransient (const QWidget * w) inline static
Definition at line 178 of file qwidget_x11.cpp.
Referenced by QWidgetPrivate::isBackgroundInherited(), and qstring_to_xtp().
 {
     return ((w->windowType() == Qt::Dialog
              || w->windowType() == Qt::Sheet
              || w->windowType() == Qt::Tool
              || w->windowType() == Qt::SplashScreen
              || w->windowType() == Qt::ToolTip
              || w->windowType() == Qt::Drawer
              || w->windowType() == Qt::Popup)
             && !w->testAttribute(Qt::WA_X11BypassTransientForHint));
 }
qstring_to_xtp()
static XTextProperty* qstring_to_xtp (const QString & s) static
Definition at line 1408 of file qwidget_x11.cpp.
 {
     static XTextProperty tp = { 0, 0, 0, 0 };
     static bool free_prop = true; // we can't free tp.value in case it references
     // the data of the static QCString below.
     if (tp.value) {
         if (free_prop)
             XFree(tp.value);
         tp.value = 0;
         free_prop = true;
     }
     static const QTextCodec* mapper = QTextCodec::codecForLocale();
     int errCode = 0;
     if (mapper) {
         QByteArray mapped = mapper->fromUnicode(s);
         char* tl[2];
         tl[0] = mapped.data();
         tl[1] = 0;
         errCode = XmbTextListToTextProperty(X11->display, tl, 1, XStdICCTextStyle, &tp);
 #if defined(QT_DEBUG)
         if (errCode < 0)
             qDebug("qstring_to_xtp result code %d", errCode);
 #endif
     }
     if (!mapper || errCode < 0) {
         static QByteArray qcs;
         qcs = s.toAscii();
         tp.value = (uchar*)qcs.data();
         tp.encoding = XA_STRING;
         tp.format = 8;
         tp.nitems = qcs.length();
         free_prop = false;
     }
     // ### If we knew WM could understand unicode, we could use
     // ### a much simpler, cheaper encoding...
     /*
         tp.value = (XChar2b*)s.unicode();
         tp.encoding = XA_UNICODE; // wish
         tp.format = 16;
         tp.nitems = s.length();
     */
     return &tp;
 }
qt_change_net_wm_state()
void qt_change_net_wm_state (const QWidget * w, bool set, Atom one, Atom two = 0)
Definition at line 413 of file qwidget_x11.cpp.
Referenced by qstring_to_xtp(), and QApplication::syncX().
 {
     if (!w->isVisible()) // not managed by the window manager
         return;
     XEvent e;
     e.xclient.type = ClientMessage;
     e.xclient.message_type = ATOM(_NET_WM_STATE);
     e.xclient.display = X11->display;
     e.xclient.window = w->internalWinId();
     e.xclient.format = 32;
     e.xclient.data.l[0] = set ? 1 : 0;
     e.xclient.data.l[1] = one;
     e.xclient.data.l[2] = two;
     e.xclient.data.l[3] = 0;
     e.xclient.data.l[4] = 0;
     XSendEvent(X11->display, RootWindow(X11->display, w->x11Info().screen()),
                false, (SubstructureNotifyMask | SubstructureRedirectMask), &e);
 }
qt_insert_sip()
static void qt_insert_sip (QWidget * scrolled_widget, int dx, int dy) static
Definition at line 235 of file qwidget_x11.cpp.
Referenced by do_size_hints().
 {
     if (!scrolled_widget->isWindow() && !scrolled_widget->internalWinId())
         return;
     QX11Data::ScrollInProgress sip = { X11->sip_serial++, scrolled_widget, dx, dy };
     X11->sip_list.append(sip);
     XClientMessageEvent client_message;
     client_message.type = ClientMessage;
     client_message.window = scrolled_widget->internalWinId();
     client_message.format = 32;
     client_message.message_type = ATOM(_QT_SCROLL_DONE);
     client_message.data.l[0] = sip.id;
     XSendEvent(X11->display, scrolled_widget->internalWinId(), False, NoEventMask,
         (XEvent*)&client_message);
 }
qt_net_remove_user_time()
void qt_net_remove_user_time (QWidget * tlw)
Definition at line 1508 of file qapplication_x11.cpp.
Referenced by QWidgetPrivate::isBackgroundInherited(), and qt_net_update_user_time().
 {
     Q_ASSERT(tlw);
     QTLWExtra *extra = tlw->d_func()->maybeTopData();
     if (extra && extra->userTimeWindow) {
         Q_ASSERT(tlw->internalWinId());
         XDeleteProperty(X11->display, tlw->internalWinId(), ATOM(_NET_WM_USER_TIME_WINDOW));
         XDestroyWindow(X11->display, extra->userTimeWindow);
         extra->userTimeWindow = 0;
     }
 }
qt_net_update_user_time()
void qt_net_update_user_time (QWidget * tlw, unsigned long timestamp)
Definition at line 1520 of file qapplication_x11.cpp.
Referenced by qstring_to_xtp(), and QApplication::x11ProcessEvent().
 {
     Q_ASSERT(tlw);
     Q_ASSERT(tlw->isWindow());
     Q_ASSERT(tlw->testAttribute(Qt::WA_WState_Created));
     QTLWExtra *extra = tlw->d_func()->topData();
     WId wid = tlw->internalWinId();
     const bool isSupportedByWM = X11->isSupportedByWM(ATOM(_NET_WM_USER_TIME_WINDOW));
     if (extra->userTimeWindow || isSupportedByWM) {
         if (!extra->userTimeWindow) {
             extra->userTimeWindow = XCreateSimpleWindow(X11->display,
                                                         tlw->internalWinId(),
                                                         -1, -1, 1, 1, 0, 0, 0);
             wid = extra->userTimeWindow;
             XChangeProperty(X11->display, tlw->internalWinId(), ATOM(_NET_WM_USER_TIME_WINDOW),
                             XA_WINDOW, 32, PropModeReplace,
                             (unsigned char *)&wid, 1);
             XDeleteProperty(X11->display, tlw->internalWinId(), ATOM(_NET_WM_USER_TIME));
         } else if (!isSupportedByWM) {
             // WM no longer supports it, then we should remove the
             // _NET_WM_USER_TIME_WINDOW atom.
             qt_net_remove_user_time(tlw);
         } else {
             wid = extra->userTimeWindow;
         }
     }
     XChangeProperty(X11->display, wid, ATOM(_NET_WM_USER_TIME),
                     XA_CARDINAL, 32, PropModeReplace, (unsigned char *) &timestamp, 1);
 }
qt_nograb()
bool qt_nograb ()
Definition at line 482 of file qapplication_mac.mm.
Referenced by qJournalRecordProc(), qstring_to_xtp(), and qt_try_modal().
 {
 #if defined(QT_DEBUG)
     return appNoGrab;
 #else
     return false;
 #endif
 }
qt_sip_count()
static int qt_sip_count (QWidget * scrolled_widget) static
Definition at line 253 of file qwidget_x11.cpp.
Referenced by do_size_hints().
 {
     int sips=0;
     for (int i = 0; i < X11->sip_list.size(); ++i) {
         const QX11Data::ScrollInProgress &sip = X11->sip_list.at(i);
         if (sip.scrolled_widget == scrolled_widget)
             sips++;
     }
     return sips;
 }
qt_x11_enforce_cursor() [1/2]
void qt_x11_enforce_cursor (QWidget * w, bool force)
Update the X11 cursor of the widget w.
Warning
This function is not part of the public interface.
force is true if this function is called from dispatchEnterLeave, it means that the mouse is actually directly under this widget.
Definition at line 302 of file qwidget_x11.cpp.
Referenced by QApplicationPrivate::applyX11SpecificCommandLineArguments(), QApplicationPrivate::dispatchEnterLeave(), getNetWmState(), QWidgetPrivate::mapFromGlobal(), qt_x11_enforce_cursor(), and QWidgetPrivate::setEnabled_helper().
 {
     if (!w->testAttribute(Qt::WA_WState_Created))
         return;
     static QPointer<QWidget> lastUnderMouse = 0;
     if (force) {
         lastUnderMouse = w;
     } else if (lastUnderMouse && lastUnderMouse->effectiveWinId() == w->effectiveWinId()) {
         w = lastUnderMouse;
     } else if (!w->internalWinId()) {
         return; //the mouse is not under this widget, and it's not native, so don't change it
     }
     while (!w->internalWinId() && w->parentWidget() && !w->isWindow() && !w->testAttribute(Qt::WA_SetCursor))
         w = w->parentWidget();
     QWidget *nativeParent = w;
     if (!w->internalWinId())
         nativeParent = w->nativeParentWidget();
     // This does the same as effectiveWinId(), but since it is possible
     // to not have a native parent widget due to a special hack in
     // qwidget for reparenting widgets to a different X11 screen,
     // added additional check to make sure native parent widget exists.
     if (!nativeParent || !nativeParent->internalWinId())
         return;
     WId winid = nativeParent->internalWinId();
     if (w->isWindow() || w->testAttribute(Qt::WA_SetCursor)) {
 #ifndef QT_NO_CURSOR
         QCursor *oc = QApplication::overrideCursor();
         if (oc) {
             XDefineCursor(X11->display, winid, oc->handle());
         } else if (w->isEnabled()) {
             XDefineCursor(X11->display, winid, w->cursor().handle());
         } else {
             // enforce the windows behavior of clearing the cursor on
             // disabled widgets
             XDefineCursor(X11->display, winid, XNone);
         }
 #endif
     } else {
         XDefineCursor(X11->display, winid, XNone);
     }
 }
qt_x11_enforce_cursor() [2/2]
Q_GUI_EXPORT void qt_x11_enforce_cursor (QWidget * w)
Definition at line 348 of file qwidget_x11.cpp.
 {
     qt_x11_enforce_cursor(w, false);
 }
qt_x11_getX11InfoForWindow() [1/2]
void qt_x11_getX11InfoForWindow (QX11Info * xinfo, const XWindowAttributes & a)
Definition at line 437 of file qwidget_x11.cpp.
Referenced by getNetWmState(), and QX11PixmapData::transformed().
 {
     QX11WindowAttributes att;
     att.att = &a;
     qt_x11_getX11InfoForWindow(xinfo,att);
 }
qt_x11_getX11InfoForWindow() [2/2]
void qt_x11_getX11InfoForWindow (QX11Info * xinfo, const QX11WindowAttributes & att)
Definition at line 3114 of file qwidget_x11.cpp.
 {
     QX11InfoData* xd = xinfo->getX11Data(true);
     const XWindowAttributes &a = *(att.att);
     // find which screen the window is on...
     xd->screen = QX11Info::appScreen(); // by default, use the default :)
     int i;
     for (i = 0; i < ScreenCount(X11->display); i++) {
         if (RootWindow(X11->display, i) == a.root) {
             xd->screen = i;
             break;
         }
     }
     xd->depth = a.depth;
     xd->cells = DisplayCells(X11->display, xd->screen);
     xd->visual = a.visual;
     xd->defaultVisual = (XVisualIDFromVisual((Visual *) a.visual) ==
                          XVisualIDFromVisual((Visual *) QX11Info::appVisual(xinfo->screen())));
     xd->colormap = a.colormap;
     xd->defaultColormap = (a.colormap == QX11Info::appColormap(xinfo->screen()));
     xinfo->setX11Data(xd);
 }
qt_x11_recreateNativeWidgetsRecursive()
static void qt_x11_recreateNativeWidgetsRecursive (QWidget * widget) static
Definition at line 986 of file qwidget_x11.cpp.
Referenced by QWidgetPrivate::x11UpdateIsOpaque().
 {
     if (widget->internalWinId())
         qt_x11_recreateWidget(widget);
     const QObjectList &children = widget->children();
     for (int i = 0; i < children.size(); ++i) {
         QWidget *child = qobject_cast<QWidget*>(children.at(i));
         if (child)
             qt_x11_recreateNativeWidgetsRecursive(child);
     }
 }
qt_x11_recreateWidget()
static void qt_x11_recreateWidget (QWidget * widget) static
Definition at line 957 of file qwidget_x11.cpp.
Referenced by qt_x11_recreateNativeWidgetsRecursive().
 {
     if (widget->inherits("QGLWidget")) {
         // We send QGLWidgets a ParentChange event which causes them to
         // recreate their GL context, which in turn causes them to choose
         // their visual again. Now that WA_TranslucentBackground is set,
         // QGLContext::chooseVisual will select an ARGB visual.
         // QGLWidget expects a ParentAboutToChange to be sent first
         QEvent aboutToChangeEvent(QEvent::ParentAboutToChange);
         QApplication::sendEvent(widget, &aboutToChangeEvent);
         QEvent parentChangeEvent(QEvent::ParentChange);
         QApplication::sendEvent(widget, &parentChangeEvent);
     } else {
         // For regular widgets, reparent them with their parent which
         // also triggers a recreation of the native window
         QPoint pos = widget->pos();
         bool visible = widget->isVisible();
         if (visible)
             widget->hide();
         widget->setParent(widget->parentWidget(), widget->windowFlags());
         widget->move(pos);
         if (visible)
             widget->show();
     }
 }
qt_x11_wait_for_window_manager() [1/2]
void qt_x11_wait_for_window_manager (QWidget * w, bool sendPostedEvents)
Definition at line 353 of file qwidget_x11.cpp.
Referenced by QSplashScreen::finish(), qstring_to_xtp(), and qt_x11_wait_for_window_manager().
 {
     if (!w || (!w->isWindow() && !w->internalWinId()))
         return;
     QApplication::flush();
     XEvent ev;
     QElapsedTimer t;
     t.start();
     static const int maximumWaitTime = 2000;
     if (!w->testAttribute(Qt::WA_WState_Created))
         return;
     WId winid = w->internalWinId();
     // first deliver events that are already in the local queue
     if (sendPostedEvents)
         QApplication::sendPostedEvents();
     // the normal sequence is:
     //  ... ConfigureNotify ... ReparentNotify ... MapNotify ... Expose
     // with X11BypassWindowManagerHint:
     //  ConfigureNotify ... MapNotify ... Expose
     enum State {
         Initial, Mapped
     } state = Initial;
     do {
         if (XEventsQueued(X11->display, QueuedAlready)) {
             XNextEvent(X11->display, &ev);
             // Pass the event through the event dispatcher filter so that applications
             // which install an event filter on the dispatcher get to handle it first.
             if (!QAbstractEventDispatcher::instance()->filterEvent(&ev)) {
                 qApp->x11ProcessEvent(&ev);
                 switch (state) {
                 case Initial:
                     if (ev.type == MapNotify && ev.xany.window == winid)
                         state = Mapped;
                     break;
                 case Mapped:
                     if (ev.type == Expose && ev.xany.window == winid)
                         return;
                     break;
                 }
             }
         } else {
             if (!XEventsQueued(X11->display, QueuedAfterFlush))
                 qApp->syncX(); // non-busy wait
         }
         if (t.elapsed() > maximumWaitTime)
             return;
     } while(1);
 }
qt_x11_wait_for_window_manager() [2/2]
Q_GUI_EXPORT void qt_x11_wait_for_window_manager (QWidget * w)
Definition at line 408 of file qwidget_x11.cpp.
Referenced by pixmapsAreEqual(), and QTest::qWaitForWindowShown().
 {
     qt_x11_wait_for_window_manager(w, true);
 }
qt_XCreateSimpleWindow()
Window qt_XCreateSimpleWindow (const QWidget * creator, Display * display, Window parent, int x, int y, uint w, uint h, int borderwidth, ulong border, ulong background)
Definition at line 64 of file qwidgetcreate_x11.cpp.
Referenced by getNetWmState().
 {
     return XCreateSimpleWindow(display, parent, x, y, w, h, borderwidth,
                                 border, background);
 }
qt_XCreateWindow()
Window qt_XCreateWindow (const QWidget * creator, Display * display, Window parent, int x, int y, uint w, uint h, int borderwidth, int depth, uint windowclass, Visual * visual, ulong valuemask, XSetWindowAttributes * attributes)
Definition at line 53 of file qwidgetcreate_x11.cpp.
Referenced by getNetWmState().
 {
     return XCreateWindow(display, parent, x, y, w, h, borderwidth, depth,
                           windowclass, visual, valuemask, attributes);
 }
qt_XDestroyWindow()
void qt_XDestroyWindow (const QWidget * destroyer, Display * display, Window window)
Definition at line 73 of file qwidgetcreate_x11.cpp.
Referenced by getNetWmState(), and QWidgetPrivate::isBackgroundInherited().
 {
     if (window)
         XDestroyWindow(display, window);
 }
SetMWMHints()
static void SetMWMHints (Display * display, Window window, const QtMWMHints & mwmhints) static
Definition at line 167 of file qwidget_x11.cpp.
Referenced by do_size_hints(), getNetWmState(), and qstring_to_xtp().
 {
     if (mwmhints.flags != 0l) {
         XChangeProperty(display, window, ATOM(_MOTIF_WM_HINTS), ATOM(_MOTIF_WM_HINTS), 32,
                         PropModeReplace, (unsigned char *) &mwmhints, 5);
     } else {
         XDeleteProperty(display, window, ATOM(_MOTIF_WM_HINTS));
     }
 }
Variable Documentation
qt_x11_create_desktop_on_screen
int qt_x11_create_desktop_on_screen = -1
Definition at line 99 of file qwidget_x11.cpp.
Referenced by getNetWmState(), and QDesktopWidgetPrivate::init().
stdDesktopEventMask
const uint stdDesktopEventMask
Initial value:
=
       (uint)(
           KeymapStateMask |
           EnterWindowMask | LeaveWindowMask |
           PropertyChangeMask
      )
Definition at line 209 of file qwidget_x11.cpp.
stdWidgetEventMask
const uint stdWidgetEventMask
Initial value:
=
        (uint)(
            KeyPressMask | KeyReleaseMask |
            ButtonPressMask | ButtonReleaseMask |
            KeymapStateMask |
            ButtonMotionMask | PointerMotionMask |
            EnterWindowMask | LeaveWindowMask |
            FocusChangeMask |
            ExposureMask |
            PropertyChangeMask |
            StructureNotifyMask
       )
Definition at line 196 of file qwidget_x11.cpp.