Qt 4.8: /src/gui/kernel/qwidget.cpp File Reference
qwidget.cpp File Reference
#include "qapplication.h"
#include "qapplication_p.h"
#include "qbrush.h"
#include "qcursor.h"
#include "qdesktopwidget.h"
#include "qevent.h"
#include "qhash.h"
#include "qlayout.h"
#include "qmenu.h"
#include "qmetaobject.h"
#include "qpixmap.h"
#include "qpointer.h"
#include "qstack.h"
#include "qstyle.h"
#include "qstylefactory.h"
#include "qvariant.h"
#include "qwidget.h"
#include "qstyleoption.h"
#include "qaccessible.h"
#include "qt_windows.h"
#include "qt_mac_p.h"
#include "qt_cocoa_helpers_mac_p.h"
#include "qmainwindow.h"
#include "qtoolbar.h"
#include <private/qmainwindowlayout_p.h>
#include "qwsdisplay_qws.h"
#include "qwsmanager_qws.h"
#include "qpaintengine.h"
#include "private/qwindowsurface_qws_p.h"
#include "qpainter.h"
#include "qtooltip.h"
#include "qwhatsthis.h"
#include "qdebug.h"
#include "private/qstylesheetstyle_p.h"
#include "private/qstyle_p.h"
#include "private/qinputcontext_p.h"
#include "qfileinfo.h"
#include "private/qsoftkeymanager_p.h"
#include <private/qwininputcontext_p.h>
#include <private/qpaintengine_x11_p.h>
#include "qx11info_x11.h"
#include <private/qgraphicseffect_p.h>
#include <private/qwindowsurface_p.h>
#include <private/qbackingstore_p.h>
#include <private/qpaintengine_mac_p.h>
#include <private/qpaintengine_raster_p.h>
#include "qwidget_p.h"
#include "qaction_p.h"
#include "qlayout_p.h"
#include "QtGui/qgraphicsproxywidget.h"
#include "QtGui/qgraphicsscene.h"
#include "private/qgraphicsproxywidget_p.h"
#include "QtGui/qabstractscrollarea.h"
#include "private/qabstractscrollarea_p.h"
#include "private/qevent_p.h"
#include "private/qgraphicssystem_p.h"
#include "private/qgesturemanager_p.h"
#include "moc_qwidget.cpp"
Classes
class QDummyWindowSurface
struct QWidgetExceptionCleaner
Macros
#define QT_NO_PAINT_DEBUG
Functions
static QString constructWindowTitleFromFilePath (const QString &filePath)
static void fillRegion (QPainter *painter, const QRegion &rgn, const QBrush &brush)
static bool hasBackingStoreSupport ()
static bool qRectIntersects (const QRect &r1, const QRect &r2)
QRegion qt_dirtyRegion (QWidget *widget)
Q_GUI_EXPORT QWidgetData * qt_qwidget_data (QWidget *widget)
bool qt_sendSpontaneousEvent (QObject *, QEvent *)
QString qt_setWindowTitle_helperHelper (const QString &title, const QWidget *widget)
Returns a modified window title with the [*] place holder replaced according to the rules described in QWidget::setWindowTitle.
Q_GUI_EXPORT QWidgetPrivate * qt_widget_private (QWidget *widget)
Q_GUI_EXPORT void qt_x11_set_global_double_buffer (bool enable)
static void setAttribute_internal (Qt::WidgetAttribute attribute, bool on, QWidgetData *data, QWidgetPrivate *d)
void setDisabledStyle (QWidget *w, bool setStyle)
Variables
QPointer< QWidget > qt_button_down
QDesktopWidget * qt_desktopWidget
Macro Definition Documentation
QT_NO_PAINT_DEBUG
#define QT_NO_PAINT_DEBUG
Definition at line 179 of file qwidget.cpp.
Function Documentation
constructWindowTitleFromFilePath()
static QString constructWindowTitleFromFilePath (const QString & filePath) static
Definition at line 6185 of file qwidget.cpp.
 {
     QFileInfo fi(filePath);
     QString windowTitle = fi.fileName() + QLatin1String("[*]");
 #ifndef Q_WS_MAC
     QString appName = QApplication::applicationName();
     if (!appName.isEmpty())
         windowTitle += QLatin1Char(' ') + QChar(0x2014) + QLatin1Char(' ') + appName;
 #endif
     return windowTitle;
 }
fillRegion()
static void fillRegion (QPainter * painter, const QRegion & rgn, const QBrush & brush) inline static
Definition at line 2392 of file qwidget.cpp.
Referenced by QWidgetPrivate::paintBackground(), and QVGPaintEngine::vgPrivate().
 {
     Q_ASSERT(painter);
     if (brush.style() == Qt::TexturePattern) {
 #ifdef Q_WS_MAC
         // Optimize pattern filling on mac by using HITheme directly
         // when filling with the standard widget background.
         // Defined in qmacstyle_mac.cpp
         extern void qt_mac_fill_background(QPainter *painter, const QRegion &rgn, const QBrush &brush);
         qt_mac_fill_background(painter, rgn, brush);
 #else
 #if !defined(QT_NO_STYLE_S60)
         // Defined in qs60style.cpp
         extern bool qt_s60_fill_background(QPainter *painter, const QRegion &rgn, const QBrush &brush);
         if (!qt_s60_fill_background(painter, rgn, brush))
 #endif // !defined(QT_NO_STYLE_S60)
         {
             const QRect rect(rgn.boundingRect());
             painter->setClipRegion(rgn);
             painter->drawTiledPixmap(rect, brush.texture(), rect.topLeft());
         }
 #endif // Q_WS_MAC
     } else if (brush.gradient()
                && brush.gradient()->coordinateMode() == QGradient::ObjectBoundingMode) {
         painter->save();
         painter->setClipRegion(rgn);
         painter->fillRect(0, 0, painter->device()->width(), painter->device()->height(), brush);
         painter->restore();
     } else {
         const QVector<QRect> &rects = rgn.rects();
         for (int i = 0; i < rects.size(); ++i)
             painter->fillRect(rects.at(i), brush);
     }
 }
hasBackingStoreSupport()
static bool hasBackingStoreSupport () inline static
Definition at line 169 of file qwidget.cpp.
Referenced by QWidget::create(), QWidget::repaint(), and QWidget::update().
 {
 #ifdef Q_WS_MAC
     return QApplicationPrivate::graphicsSystem() != 0;
 #else
     return true;
 #endif
 }
qRectIntersects()
static bool qRectIntersects (const QRect & r1, const QRect & r2) inline static
Definition at line 163 of file qwidget.cpp.
Referenced by QWidgetPrivate::clipRegion(), QWidgetPrivate::isOverlapped(), QWidgetPrivate::paintSiblingsRecursive(), and QWidgetPrivate::subtractOpaqueSiblings().
 {
     return (qMax(r1.left(), r2.left()) <= qMin(r1.right(), r2.right()) &&
             qMax(r1.top(), r2.top()) <= qMin(r1.bottom(), r2.bottom()));
 }
qt_dirtyRegion()
QRegion qt_dirtyRegion (QWidget * widget)
Definition at line 1111 of file qwidget.cpp.
Referenced by QWidgetBackingStore::hasStaticContents(), and QETWidget::translatePaintEvent().
 {
     if (!widget)
         return QRegion();
     QWidgetBackingStore *bs = qt_widget_private(widget)->maybeBackingStore();
     if (!bs)
         return QRegion();
     return bs->dirtyRegion(widget);
 }
qt_qwidget_data()
Q_GUI_EXPORT QWidgetData* qt_qwidget_data (QWidget * widget)
Definition at line 12915 of file qwidget.cpp.
Referenced by QXcbWindowSurface::flush(), QX11WindowSurface::flush(), QGLWindowSurface::flush(), QRasterWindowSurface::flush(), QWindowSystemInterface::handleEnterEvent(), QWindowSystemInterface::handleExtendedKeyEvent(), QWindowSystemInterface::handleGeometryChange(), QWindowSystemInterface::handleKeyEvent(), QWindowSystemInterface::handleLeaveEvent(), QWindowSystemInterface::handleMouseEvent(), and QWindowSystemInterface::handleWheelEvent().
 {
     return widget->data;
 }
qt_sendSpontaneousEvent()
bool qt_sendSpontaneousEvent (QObject * , QEvent *)
Definition at line 5779 of file qapplication.cpp.
 {
     return QCoreApplication::sendSpontaneousEvent(receiver, event);
 }
qt_setWindowTitle_helperHelper()
QString qt_setWindowTitle_helperHelper (const QString & title, const QWidget * widget)
Returns a modified window title with the [*] place holder replaced according to the rules described in QWidget::setWindowTitle.
This function assumes that "[*]" can be quoted by another "[*]", so it will replace two place holders by one and a single last one by either "*" or nothing depending on the modified flag.
Warning
This function is not part of the public interface.
Definition at line 6240 of file qwidget.cpp.
Referenced by QDockWidget::changeEvent(), QMdiSubWindowPrivate::getOperation(), QAccessibleWidget::indexOfChild(), QDockWidgetPrivate::init(), QWorkspaceTitleBar::isTool(), QDecorationDefault::paintButton(), QWorkspaceTitleBar::paintEvent(), QWidgetPrivate::setWindowIconText_helper(), QWidgetPrivate::setWindowTitle_helper(), tabTextFor(), QAccessibleWidget::text(), QMdiSubWindowPrivate::updateInternalWindowTitle(), and QDecorationDefault::windowTitleFor().
 {
     Q_ASSERT(widget);
 #ifdef QT_EVAL
     extern QString qt_eval_adapt_window_title(const QString &title);
     QString cap = qt_eval_adapt_window_title(title);
 #else
     QString cap = title;
 #endif
     if (cap.isEmpty())
         return cap;
     QLatin1String placeHolder("[*]");
     int placeHolderLength = 3; // QLatin1String doesn't have length()
     int index = cap.indexOf(placeHolder);
     // here the magic begins
     while (index != -1) {
         index += placeHolderLength;
         int count = 1;
         while (cap.indexOf(placeHolder, index) == index) {
             ++count;
             index += placeHolderLength;
         }
         if (count%2) { // odd number of [*] -> replace last one
             int lastIndex = cap.lastIndexOf(placeHolder, index - 1);
             if (widget->isWindowModified()
              && widget->style()->styleHint(QStyle::SH_TitleBar_ModifyNotification, 0, widget))
                 cap.replace(lastIndex, 3, QWidget::tr("*"));
             else
                 cap.remove(lastIndex, 3);
         }
         index = cap.indexOf(placeHolder, index);
     }
     cap.replace(QLatin1String("[*][*]"), placeHolder);
     return cap;
 }
qt_widget_private()
Q_GUI_EXPORT QWidgetPrivate* qt_widget_private (QWidget * widget)
Definition at line 12920 of file qwidget.cpp.
Referenced by QVGWindowSurface::beginPaint(), QRasterWindowSurface::beginPaint(), QVGGraphicsSystem::createWindowSurface(), QGLGraphicsSystem::createWindowSurface(), QGraphicsViewPrivate::dispatchPendingUpdateRequests(), QInputDialogPrivate::ensureComboBox(), QInputDialogPrivate::ensureLineEdit(), QDirectFBWindowSurface::flush(), QRasterWindowSurface::flush(), QPixmap::grabWidget(), QTabWidgetPrivate::hasHeightForWidth(), QGLWidgetPrivate::init(), macWindowToolbarShow(), QDeclarativeTextInput::mouseReleaseEvent(), QDeclarativeTextEdit::mouseReleaseEvent(), QGraphicsTextItem::mouseReleaseEvent(), QApplication::notify(), QPlatformScreen::physicalSize(), QPlatformScreen::platformScreenForWidget(), qstring_to_xtp(), qt_dirtyRegion(), qt_event_request_window_change(), qt_mac_post_retranslateAppMenu(), qt_mac_send_posted_gl_updates(), qt_mac_update_child_gl_widgets(), qt_mac_update_intersected_gl_widgets(), qt_mac_update_widget_position(), qt_post_window_change_event(), qt_reg_winclass(), QWidgetBackingStoreTracker::registerWidget(), QMdi::ControlContainer::removeButtonsFromMenuBar(), QRasterWindowSurface::setGeometry(), QRuntimeGraphicsSystem::setGraphicsSystem(), QGL2PaintEngineExPrivate::systemStateChanged(), QAccessible::updateAccessibility(), QOpenGLPaintEngine::updateClipRegion(), QTabBarPrivate::updateMacBorderMetrics(), and updateRedirectedToGraphicsProxyWidget().
 {
     return widget->d_func();
 }
qt_x11_set_global_double_buffer()
Q_GUI_EXPORT void qt_x11_set_global_double_buffer (bool enable)
Definition at line 153 of file qwidget.cpp.
 {
     qt_enable_backingstore = enable;
 }
setAttribute_internal()
static void setAttribute_internal (Qt::WidgetAttribute attribute, bool on, QWidgetData * data, QWidgetPrivate * d) static
Warning
This function is not part of the public interface.
This just sets the corresponding attribute bit to 1 or 0
Definition at line 11063 of file qwidget.cpp.
Referenced by QWidget::setAttribute().
 {
     if (attribute < int(8*sizeof(uint))) {
         if (on)
             data->widget_attributes |= (1<<attribute);
         else
             data->widget_attributes &= ~(1<<attribute);
     } else {
         const int x = attribute - 8*sizeof(uint);
         const int int_off = x / (8*sizeof(uint));
         if (on)
             d->high_attributes[int_off] |= (1<<(x-(int_off*8*sizeof(uint))));
         else
             d->high_attributes[int_off] &= ~(1<<(x-(int_off*8*sizeof(uint))));
     }
 }
setDisabledStyle()
void setDisabledStyle (QWidget * w, bool setStyle) inline
Definition at line 8586 of file qwidget.cpp.
Referenced by QWidget::event().
 {
     // set/reset WS_DISABLED style.
     if(w && w->isWindow() && w->isVisible() && w->isEnabled()) {
         LONG dwStyle = GetWindowLong(w->winId(), GWL_STYLE);
         LONG newStyle = dwStyle;
         if (setStyle)
             newStyle |= WS_DISABLED;
         else
             newStyle &= ~WS_DISABLED;
         if (newStyle != dwStyle) {
             SetWindowLong(w->winId(), GWL_STYLE, newStyle);
             // we might need to repaint in some situations (eg. menu)
             w->repaint();
         }
     }
 }
Variable Documentation
qt_button_down
QPointer<QWidget> qt_button_down
Definition at line 188 of file qapplication_mac.mm.
Referenced by QWidgetPrivate::paintBackground().
qt_desktopWidget
QDesktopWidget* qt_desktopWidget
Definition at line 560 of file qapplication.cpp.
Referenced by QApplication::desktop(), and QApplication::~QApplication().