Qt 4.8: /src/gui/painting/qwindowsurface_qws.cpp File Reference
qwindowsurface_qws.cpp File Reference
#include "qwindowsurface_qws_p.h"
#include <qwidget.h>
#include <qscreen_qws.h>
#include <qwsmanager_qws.h>
#include <qapplication.h>
#include <qwsdisplay_qws.h>
#include <qrgb.h>
#include <qpaintengine.h>
#include <qdesktopwidget.h>
#include <private/qapplication_p.h>
#include <private/qwsdisplay_qws_p.h>
#include <private/qwidget_p.h>
#include <private/qwsmanager_p.h>
#include <private/qwslock_p.h>
#include <private/qbackingstore_p.h>
#include <stdio.h>
Functions
static int bytesPerPixel (QImage::Format format)
static void flushUpdate (QWidget *widget, const QRegion &region, const QPoint &offset)
static QScreen * getPrimaryScreen ()
static QScreen * getScreen (const QWidget *w)
bool isWidgetOpaque (const QWidget *w)
static int nextMulOf4 (int n)
void qt_scrollRectInImage (QImage &img, const QRect &rect, const QPoint &offset)
static void setImageMetrics (QImage &img, QWidget *window)
Function Documentation
bytesPerPixel()
static int bytesPerPixel (QImage::Format format) static
Definition at line 97 of file qwindowsurface_qws.cpp.
Referenced by buttonChange(), QVNCServer::convertPixels(), drawImageTiled(), QVNCIntegration::grabWindow(), QRasterWindowSurface::prepareBuffer(), pvrQwsInitFbScreen(), QWSLocalMemSurface::setGeometry(), QWSSharedMemSurface::setGeometry(), QWSLocalMemSurface::setPermanentState(), QWSSharedMemSurface::setPermanentState(), QRfbRawEncoder::write(), and QRfbHextileEncoder< SRC >::write().
 {
     switch (format) {
     case QImage::Format_Invalid:
         return 0;
 #ifndef QT_NO_DEBUG
     case QImage::Format_Mono:
     case QImage::Format_MonoLSB:
         qFatal("QWSWindowSurface: Invalid backingstore format: %i",
                int(format));
 #endif
     case QImage::Format_Indexed8:
         return 1;
     case QImage::Format_RGB32:
     case QImage::Format_ARGB32:
     case QImage::Format_ARGB32_Premultiplied:
         return 4;
     case QImage::Format_RGB16:
     case QImage::Format_RGB555:
     case QImage::Format_RGB444:
     case QImage::Format_ARGB4444_Premultiplied:
         return 2;
     case QImage::Format_ARGB8565_Premultiplied:
     case QImage::Format_ARGB8555_Premultiplied:
     case QImage::Format_ARGB6666_Premultiplied:
     case QImage::Format_RGB666:
     case QImage::Format_RGB888:
         return 3;
     default:
 #ifndef QT_NO_DEBUG
         qFatal("QWSWindowSurface: Invalid backingstore format: %i",
                int(format));
 #endif
         return 0;
     }
 }
flushUpdate()
static void flushUpdate (QWidget * widget, const QRegion & region, const QPoint & offset) inline static
Definition at line 670 of file qwindowsurface_qws.cpp.
Referenced by QWSWindowSurface::flush(), and qt_flush().
 {
 #ifdef QT_NO_PAINT_DEBUG
     Q_UNUSED(widget);
     Q_UNUSED(region);
     Q_UNUSED(offset);
 #else
     static int delay = -1;
     if (delay == -1)
         delay = qgetenv("QT_FLUSH_UPDATE").toInt() * 10;
     if (delay == 0)
         return;
     static QWSYellowSurface surface(true);
     surface.setDelay(delay);
     surface.flush(widget, region, offset);
 #endif // QT_NO_PAINT_DEBUG
 }
getPrimaryScreen()
static QScreen* getPrimaryScreen () inline static
Definition at line 1356 of file qwindowsurface_qws.cpp.
 {
     QScreen *screen = QScreen::instance();
     if (!screen->base()) {
         QList<QScreen*> subScreens = screen->subScreens();
         if (subScreens.size() < 1)
             return 0;
         screen = subScreens.at(0);
     }
     return screen;
 }
getScreen()
static QScreen* getScreen (const QWidget * w) inline static
Definition at line 86 of file qwindowsurface_qws.cpp.
Referenced by effectiveState(), QWSWindowSurface::flush(), QWSOnScreenSurface::isValid(), QWSMemorySurface::preferredImageFormat(), QWSOnScreenSurface::QWSOnScreenSurface(), and setImageMetrics().
 {
     const QList<QScreen*> subScreens = qt_screen->subScreens();
     if (subScreens.isEmpty())
         return qt_screen;
     const int screen = QApplication::desktop()->screenNumber(w);
     return qt_screen->subScreens().at(screen < 0 ? 0 : screen);
 }
isWidgetOpaque()
bool isWidgetOpaque (const QWidget * w) inline
Definition at line 81 of file qwindowsurface_qws.cpp.
Referenced by QWSMemorySurface::beginPaint(), QWSMemorySurface::isValid(), QWSMemorySurface::preferredImageFormat(), and QWSMemorySurface::QWSMemorySurface().
 {
     return w->d_func()->isOpaque && !w->testAttribute(Qt::WA_TranslucentBackground);
 }
nextMulOf4()
static int nextMulOf4 (int n) inline static
Definition at line 134 of file qwindowsurface_qws.cpp.
Referenced by QWSLocalMemSurface::setGeometry(), QWSSharedMemSurface::setGeometry(), QWSLocalMemSurface::setPermanentState(), and QWSSharedMemSurface::setPermanentState().
 {
     return ((n + 3) & 0xfffffffc);
 }
qt_scrollRectInImage()
void qt_scrollRectInImage (QImage & img, const QRect & rect, const QPoint & offset)
Definition at line 345 of file qwindowsurface.cpp.
Referenced by QWSMemorySurface::beginPaint(), and QWSMemorySurface::scroll().
 {
     // make sure we don't detach
     uchar *mem = const_cast<uchar*>(const_cast<const QImage &>(img).bits());
     int lineskip = img.bytesPerLine();
     int depth = img.depth() >> 3;
     const QRect imageRect(0, 0, img.width(), img.height());
     const QRect r = rect & imageRect & imageRect.translated(-offset);
     const QPoint p = rect.topLeft() + offset;
     if (r.isEmpty())
         return;
     const uchar *src;
     uchar *dest;
     if (r.top() < p.y()) {
         src = mem + r.bottom() * lineskip + r.left() * depth;
         dest = mem + (p.y() + r.height() - 1) * lineskip + p.x() * depth;
         lineskip = -lineskip;
     } else {
         src = mem + r.top() * lineskip + r.left() * depth;
         dest = mem + p.y() * lineskip + p.x() * depth;
     }
     const int w = r.width();
     int h = r.height();
     const int bytes = w * depth;
     // overlapping segments?
     if (offset.y() == 0 && qAbs(offset.x()) < w) {
         do {
             ::memmove(dest, src, bytes);
             dest += lineskip;
             src += lineskip;
         } while (--h);
     } else {
         do {
             ::memcpy(dest, src, bytes);
             dest += lineskip;
             src += lineskip;
         } while (--h);
     }
 }
setImageMetrics()
static void setImageMetrics (QImage & img, QWidget * window) inline static
Definition at line 139 of file qwindowsurface_qws.cpp.
Referenced by QWSLocalMemSurface::setGeometry(), and QWSSharedMemSurface::setGeometry().
{
     QScreen *myScreen = getScreen(window);
     if (myScreen) {
         int dpmx = myScreen->width()*1000 / myScreen->physicalWidth();
         int dpmy = myScreen->height()*1000 / myScreen->physicalHeight();
         img.setDotsPerMeterX(dpmx);
         img.setDotsPerMeterY(dpmy);
     }
 }