Qt 4.8: /src/opengl/qwindowsurface_gl.cpp File Reference
qwindowsurface_gl.cpp File Reference
#include <QtGui/QApplication>
#include <QtGui/QColormap>
#include <QtGui/QDesktopWidget>
#include <QtGui/QPaintDevice>
#include <QtGui/QWidget>
#include <qglframebufferobject.h>
#include <qglpixelbuffer.h>
#include <qcolormap.h>
#include <qdesktopwidget.h>
#include <private/qwidget_p.h>
#include "qdebug.h"
#include <private/qt_x11_p.h>
#include <qx11info_x11.h>
#include <GL/glx.h>
#include <X11/Xlib.h>
#include <private/qglextensions_p.h>
#include <private/qwindowsurface_gl_p.h>
#include <private/qgl_p.h>
#include <private/qglpixelbuffer_p.h>
#include <private/qgraphicssystem_gl_p.h>
#include <private/qpaintengineex_opengl2_p.h>
#include <private/qpixmapdata_gl_p.h>
#include <private/qpaintengine_opengl_p.h>
#include <private/qeglcontext_p.h>
Classes
class QGLGlobalShareWidget
struct QGLWindowSurfacePrivate
Macros
#define GLX_SAMPLE_BUFFERS_ARB 100000
#define GLX_SAMPLES_ARB 100001
Functions
static void blitTexture (QGLContext *ctx, GLuint texture, const QSize &viewport, const QSize &texSize, const QRect &targetRect, const QRect &sourceRect)
static void drawTexture (const QRectF &rect, GLuint tex_id, const QSize &texSize, const QRectF &src=QRectF())
Q_GLOBAL_STATIC_WITH_INITIALIZER (QGLGlobalShareWidget, _qt_gl_share_widget, { qAddPostRoutine(qt_cleanup_gl_share_widget);}) static void qt_cleanup_gl_share_widget()
static void qt_cleanup_gl_share_widget ()
void qt_destroy_gl_share_widget ()
const QGLContext * qt_gl_share_context ()
QGLWidget * qt_gl_share_widget ()
bool qt_initializing_gl_share_widget ()
Variables
Q_GUI_EXPORT bool qt_win_owndc_required
Macro Definition Documentation
GLX_SAMPLE_BUFFERS_ARB
#define GLX_SAMPLE_BUFFERS_ARB 100000
Definition at line 81 of file qwindowsurface_gl.cpp.
Referenced by QGLGraphicsSystem::QGLGraphicsSystem().
GLX_SAMPLES_ARB
#define GLX_SAMPLES_ARB 100001
Definition at line 82 of file qwindowsurface_gl.cpp.
Referenced by QGLGraphicsSystem::QGLGraphicsSystem().
Function Documentation
blitTexture()
static void blitTexture (QGLContext * ctx, GLuint texture, const QSize & viewport, const QSize & texSize, const QRect & targetRect, const QRect & sourceRect) static
Definition at line 548 of file qwindowsurface_gl.cpp.
Referenced by QGLWindowSurface::flush().
 {
     glDisable(GL_DEPTH_TEST);
     glDisable(GL_SCISSOR_TEST);
     glDisable(GL_BLEND);
     glViewport(0, 0, viewport.width(), viewport.height());
     QGLShaderProgram *blitProgram =
         QGLEngineSharedShaders::shadersForContext(ctx)->blitProgram();
     blitProgram->bind();
     blitProgram->setUniformValue("imageTexture", 0 /*QT_IMAGE_TEXTURE_UNIT*/);
     // The shader manager's blit program does not multiply the
     // vertices by the pmv matrix, so we need to do the effect
     // of the orthographic projection here ourselves.
     QRectF r;
     qreal w = viewport.width();
     qreal h = viewport.height();
     r.setLeft((targetRect.left() / w) * 2.0f - 1.0f);
     if (targetRect.right() == (viewport.width() - 1))
         r.setRight(1.0f);
     else
         r.setRight((targetRect.right() / w) * 2.0f - 1.0f);
     r.setBottom((targetRect.top() / h) * 2.0f - 1.0f);
     if (targetRect.bottom() == (viewport.height() - 1))
         r.setTop(1.0f);
     else
         r.setTop((targetRect.bottom() / w) * 2.0f - 1.0f);
     drawTexture(r, texture, texSize, sourceRect);
 }
drawTexture()
static void drawTexture (const QRectF & rect, GLuint tex_id, const QSize & texSize, const QRectF & src = QRectF()) static
Definition at line 1092 of file qwindowsurface_gl.cpp.
Referenced by blitTexture(), QGLWindowSurface::flush(), QGLWindowSurface::paintDevice(), QGL2PaintEngineExPrivate::QGL2PaintEngineExPrivate(), and QGLWindowSurface::scroll().
 {
     const GLenum target = GL_TEXTURE_2D;
     QRectF src = br.isEmpty()
         ? QRectF(QPointF(), texSize)
         : QRectF(QPointF(br.x(), texSize.height() - br.bottom()), br.size());
     if (target == GL_TEXTURE_2D) {
         qreal width = texSize.width();
         qreal height = texSize.height();
         src.setLeft(src.left() / width);
         src.setRight(src.right() / width);
         src.setTop(src.top() / height);
         src.setBottom(src.bottom() / height);
     }
     const GLfloat tx1 = src.left();
     const GLfloat tx2 = src.right();
     const GLfloat ty1 = src.top();
     const GLfloat ty2 = src.bottom();
     GLfloat texCoordArray[4*2] = {
         tx1, ty2, tx2, ty2, tx2, ty1, tx1, ty1
     };
     GLfloat vertexArray[4*2];
     extern void qt_add_rect_to_array(const QRectF &r, GLfloat *array); // qpaintengine_opengl.cpp
     qt_add_rect_to_array(rect, vertexArray);
 #if !defined(QT_OPENGL_ES_2)
     glVertexPointer(2, GL_FLOAT, 0, vertexArray);
     glTexCoordPointer(2, GL_FLOAT, 0, texCoordArray);
     glBindTexture(target, tex_id);
     glEnable(target);
     glEnableClientState(GL_VERTEX_ARRAY);
     glEnableClientState(GL_TEXTURE_COORD_ARRAY);
     glDrawArrays(GL_TRIANGLE_FAN, 0, 4);
     glDisableClientState(GL_VERTEX_ARRAY);
     glDisableClientState(GL_TEXTURE_COORD_ARRAY);
     glDisable(target);
     glBindTexture(target, 0);
 #else
     glVertexAttribPointer(QT_VERTEX_COORDS_ATTR, 2, GL_FLOAT, GL_FALSE, 0, vertexArray);
     glVertexAttribPointer(QT_TEXTURE_COORDS_ATTR, 2, GL_FLOAT, GL_FALSE, 0, texCoordArray);
     glBindTexture(target, tex_id);
     glEnableVertexAttribArray(QT_VERTEX_COORDS_ATTR);
     glEnableVertexAttribArray(QT_TEXTURE_COORDS_ATTR);
     glDrawArrays(GL_TRIANGLE_FAN, 0, 4);
     glDisableVertexAttribArray(QT_VERTEX_COORDS_ATTR);
     glDisableVertexAttribArray(QT_TEXTURE_COORDS_ATTR);
     glBindTexture(target, 0);
 #endif
 }
Q_GLOBAL_STATIC_WITH_INITIALIZER()
Q_GLOBAL_STATIC_WITH_INITIALIZER (QGLGlobalShareWidget , _qt_gl_share_widget , { qAddPostRoutine(qt_cleanup_gl_share_widget);})
Definition at line 253 of file qwindowsurface_gl.cpp.
{
                                      qAddPostRoutine(qt_cleanup_gl_share_widget);
                                  })
 static void qt_cleanup_gl_share_widget()
 {
     if (QGLGlobalShareWidget::created)
         _qt_gl_share_widget()->cleanup();
 }
qt_cleanup_gl_share_widget()
static void qt_cleanup_gl_share_widget () static
Referenced by Q_GLOBAL_STATIC_WITH_INITIALIZER().
qt_destroy_gl_share_widget()
void qt_destroy_gl_share_widget ()
Definition at line 271 of file qwindowsurface_gl.cpp.
Referenced by QGLWindowSurface::~QGLWindowSurface(), and QMeeGoGraphicsSystem::~QMeeGoGraphicsSystem().
 {
     if (QGLGlobalShareWidget::created)
         _qt_gl_share_widget()->destroy();
 }
qt_gl_share_context()
const QGLContext* qt_gl_share_context ()
Definition at line 284 of file qwindowsurface_gl.cpp.
Referenced by QGLPixmapData::copy(), QGLPixmapData::copyBackFromRenderFbo(), QGLPixmapData::createPixmapForImage(), QGLPixmapData::ensureCreated(), QGLPixmapData::fromData(), QGLPixmapData::fromFile(), QGLWindowSurface::hijackWindow(), QGLPixmapData::isValidContext(), QGLPixmapData::paintEngine(), QGLPixmapData::resize(), QGLPixmapData::toImage(), QGLPixmapData::~QGLPixmapData(), and QGLWindowSurface::~QGLWindowSurface().
 {
     QGLWidget *widget = qt_gl_share_widget();
     if (widget)
         return widget->context();
     return 0;
 }
qt_gl_share_widget()
QGLWidget* qt_gl_share_widget ()
Definition at line 264 of file qwindowsurface_gl.cpp.
Referenced by QMeeGoGraphicsSystemSwitchHandler::addWidget(), QMeeGoGraphicsSystem::createFenceSync(), QMeeGoGraphicsSystem::createWindowSurface(), QMeeGoPixmapData::destroyEGLSharedImage(), QMeeGoGraphicsSystem::destroyFenceSync(), QMeeGoPixmapData::fromEGLSharedImage(), QMeeGoPixmapData::imageToEGLSharedImage(), QMeeGoLivePixmapData::initializeThroughEGLImage(), QMeeGoLivePixmapData::lock(), QGLPixmapData::paintEngine(), qt_gl_share_context(), QMeeGoLivePixmapData::release(), QGLWindowSurface::updateGeometry(), and QGLWindowSurface::~QGLWindowSurface().
 {
     if (QGLGlobalShareWidget::cleanedUp)
         return 0;
     return _qt_gl_share_widget()->shareWidget();
 }
qt_initializing_gl_share_widget()
bool qt_initializing_gl_share_widget ()
Definition at line 277 of file qwindowsurface_gl.cpp.
Referenced by QGLWidgetPrivate::QGLWidgetPrivate().
 {
     if (QGLGlobalShareWidget::created)
         return _qt_gl_share_widget()->initializing();
     return false;
 }
Variable Documentation
qt_win_owndc_required
Q_GUI_EXPORT bool qt_win_owndc_required
Definition at line 242 of file qapplication_win.cpp.
Referenced by QGLGraphicsSystem::QGLGraphicsSystem(), qt_init(), and qt_reg_winclass().