Qt 4.8: /src/opengl/qwindowsurface_gl_p.h File Reference
qwindowsurface_gl_p.h File Reference
#include <qglobal.h>
#include <qgl.h>
#include <private/qwindowsurface_p.h>
#include <private/qglpaintdevice_p.h>
Classes
class QGLWindowSurface
class QGLWindowSurfaceGLPaintDevice
Functions
Q_OPENGL_EXPORT void qt_destroy_gl_share_widget ()
Q_OPENGL_EXPORT QGLWidget * qt_gl_share_widget ()
bool qt_initializing_gl_share_widget ()
Function Documentation
qt_destroy_gl_share_widget()
Q_OPENGL_EXPORT void qt_destroy_gl_share_widget ()
Definition at line 271 of file qwindowsurface_gl.cpp.
Referenced by QGLWindowSurface::~QGLWindowSurface(), and QMeeGoGraphicsSystem::~QMeeGoGraphicsSystem().
 {
     if (QGLGlobalShareWidget::created)
         _qt_gl_share_widget()->destroy();
 }
qt_gl_share_widget()
Q_OPENGL_EXPORT QGLWidget* qt_gl_share_widget ()
Definition at line 264 of file qwindowsurface_gl.cpp.
Referenced by qt_gl_share_context(), QGLWindowSurface::updateGeometry(), and QGLWindowSurface::~QGLWindowSurface().
 {
     if (QGLGlobalShareWidget::cleanedUp)
         return 0;
     return _qt_gl_share_widget()->shareWidget();
 }
qt_initializing_gl_share_widget()
bool qt_initializing_gl_share_widget ()
Definition at line 277 of file qwindowsurface_gl.cpp.
Referenced by QGLWidgetPrivate::QGLWidgetPrivate().
 {
     if (QGLGlobalShareWidget::created)
         return _qt_gl_share_widget()->initializing();
     return false;
 }