Qt 4.8: /src/gui/inputmethod/qwininputcontext_win.cpp File Reference
qwininputcontext_win.cpp File Reference
#include "qwininputcontext_p.h"
#include "qinputcontext_p.h"
#include "qfont.h"
#include "qwidget.h"
#include "qapplication.h"
#include "qevent.h"
#include "qtextformat.h"
#include "qtextboundaryfinder.h"
Macros
#define IFMETHOD HRESULT STDMETHODCALLTYPE
#define LGRPID_ARABIC 0x000d
#define LGRPID_ARMENIAN 0x0011
#define LGRPID_BALTIC 0x0003
#define LGRPID_CENTRAL_EUROPE 0x0002
#define LGRPID_CYRILLIC 0x0005
#define LGRPID_GEORGIAN 0x0010
#define LGRPID_GREEK 0x0004
#define LGRPID_HEBREW 0x000c
#define LGRPID_INDIC 0x000f
#define LGRPID_INSTALLED 0x00000001
#define LGRPID_JAPANESE 0x0007
#define LGRPID_KOREAN 0x0008
#define LGRPID_SIMPLIFIED_CHINESE 0x000a
#define LGRPID_SUPPORTED 0x00000002
#define LGRPID_THAI 0x000b
#define LGRPID_TRADITIONAL_CHINESE 0x0009
#define LGRPID_TURKISH 0x0006
#define LGRPID_VIETNAMESE 0x000e
#define LGRPID_WESTERN_EUROPE 0x0001
Enumerations
enum StandardFormat { PreeditFormat, SelectionFormat }
Functions
virtual IFMETHOD Activate (BOOL fRestoreLayout)=0
virtual IFMETHOD AssociateContextEx (HWND hWnd, HIMC hIMC, DWORD dwFlags)=0
virtual IFMETHOD ConfigureIMEW (HKL hKL, HWND hWnd, DWORD dwMode, REGISTERWORDW __RPC_FAR *pData)=0
virtual IFMETHOD CreateContext (HIMC __RPC_FAR *phIMC)=0
virtual IFMETHOD Deactivate (void)=0
DEFINE_GUID (IID_IActiveIMMApp, 0x08c0e040, 0x62d1, 0x11d1, 0x93, 0x26, 0x0, 0x60, 0xb0, 0x67, 0xb8, 0x6e)
DEFINE_GUID (CLSID_CActiveIMM, 0x4955DD33, 0xB159, 0x11d0, 0x8F, 0xCF, 0x0, 0xAA, 0x00, 0x6B, 0xCC, 0x59)
DEFINE_GUID (IID_IActiveIMMMessagePumpOwner, 0xb5cf2cfa, 0x8aeb, 0x11d1, 0x93, 0x64, 0x0, 0x60, 0xb0, 0x67, 0xb8, 0x6e)
virtual IFMETHOD DestroyContext (HIMC hIME)=0
virtual IFMETHOD DisableIME (DWORD idThread)=0
virtual IFMETHOD dummy_ConfigureIMEA ()=0
virtual IFMETHOD dummy_EnumRegisterWordA ()=0
virtual IFMETHOD dummy_EscapeA ()=0
virtual IFMETHOD dummy_GetCandidateListA ()=0
virtual IFMETHOD dummy_GetCandidateListCountA ()=0
virtual IFMETHOD dummy_GetCodePageA ()=0
virtual IFMETHOD dummy_GetCompositionFontA ()=0
virtual IFMETHOD dummy_GetCompositionStringA ()=0
virtual IFMETHOD dummy_GetConversionListA ()=0
virtual IFMETHOD dummy_GetDescriptionA ()=0
virtual IFMETHOD dummy_GetGuideLineA ()=0
virtual IFMETHOD dummy_GetIMEFileNameA ()=0
virtual IFMETHOD dummy_GetImeMenuItemsA ()=0
virtual IFMETHOD dummy_GetRegisterWordStyleA ()=0
virtual IFMETHOD dummy_InstallIMEA ()=0
virtual IFMETHOD dummy_IsUIMessageA ()=0
virtual IFMETHOD dummy_RegisterWordA ()=0
virtual IFMETHOD dummy_SetCompositionStringA ()=0
virtual IFMETHOD dummy_UnregisterWordA ()=0
void enableIme (QWidget *w, bool value)
virtual IFMETHOD End (void)=0
virtual IFMETHOD EnumInputContext (DWORD idThread, IEnumInputContext __RPC_FAR *__RPC_FAR *ppEnum)=0
virtual IFMETHOD EnumRegisterWordW (HKL hKL, LPWSTR szReading, DWORD dwStyle, LPWSTR szRegister, LPVOID pData, IEnumRegisterWordW __RPC_FAR *__RPC_FAR *pEnum)=0
virtual IFMETHOD EscapeW (HKL hKL, HIMC hIMC, UINT uEscape, LPVOID pData, LRESULT __RPC_FAR *plResult)=0
virtual IFMETHOD FilterClientWindows (ATOM __RPC_FAR *aaClassList, UINT uSize)=0
QWidget * findParentforPopup (QWidget *w)
virtual IFMETHOD GetCandidateListCountW (HIMC hIMC, DWORD __RPC_FAR *pdwListSize, DWORD __RPC_FAR *pdwBufLen)=0
virtual IFMETHOD GetCandidateListW (HIMC hIMC, DWORD dwIndex, UINT uBufLen, CANDIDATELIST __RPC_FAR *pCandList, UINT __RPC_FAR *puCopied)=0
virtual IFMETHOD GetCandidateWindow (HIMC hIMC, DWORD dwIndex, CANDIDATEFORM __RPC_FAR *pCandidate)=0
virtual IFMETHOD GetCompositionFontW (HIMC hIMC, LOGFONTW __RPC_FAR *plf)=0
static LONG getCompositionString (HIMC himc, DWORD dwIndex, LPVOID lpbuf, DWORD dBufLen)
virtual IFMETHOD GetCompositionStringW (HIMC hIMC, DWORD dwIndex, DWORD dwBufLen, LONG __RPC_FAR *plCopied, LPVOID pBuf)=0
virtual IFMETHOD GetCompositionWindow (HIMC hIMC, COMPOSITIONFORM __RPC_FAR *pCompForm)=0
virtual IFMETHOD GetContext (HWND hWnd, HIMC __RPC_FAR *phIMC)=0
static HIMC getContext (HWND wnd)
virtual IFMETHOD GetConversionListW (HKL hKL, HIMC hIMC, LPWSTR pSrc, UINT uBufLen, UINT uFlag, CANDIDATELIST __RPC_FAR *pDst, UINT __RPC_FAR *puCopied)=0
virtual IFMETHOD GetConversionStatus (HIMC hIMC, DWORD __RPC_FAR *pfdwConversion, DWORD __RPC_FAR *pfdwSentence)=0
static int getCursorPosition (HIMC himc)
virtual IFMETHOD GetDefaultIMEWnd (HWND hWnd, HWND __RPC_FAR *phDefWnd)=0
static HWND getDefaultIMEWnd (HWND wnd)
virtual IFMETHOD GetDescriptionW (HKL hKL, UINT uBufLen, LPWSTR szDescription, UINT __RPC_FAR *puCopied)=0
virtual IFMETHOD GetGuideLineW (HIMC hIMC, DWORD dwIndex, DWORD dwBufLen, LPWSTR pBuf, DWORD __RPC_FAR *pdwResult)=0
virtual IFMETHOD GetIMEFileNameW (HKL hKL, UINT uBufLen, LPWSTR szFileName, UINT __RPC_FAR *puCopied)=0
virtual IFMETHOD GetImeMenuItemsW (HIMC hIMC, DWORD dwFlags, DWORD dwType, void __RPC_FAR *pImeParentMenu, void __RPC_FAR *pImeMenu, DWORD dwSize, DWORD __RPC_FAR *pdwResult)=0
virtual IFMETHOD GetLangId (HKL hKL, LANGID __RPC_FAR *plid)=0
virtual IFMETHOD GetOpenStatus (HIMC hIMC)=0
virtual IFMETHOD GetProperty (HKL hKL, DWORD fdwIndex, DWORD __RPC_FAR *pdwProperty)=0
virtual IFMETHOD GetRegisterWordStyleW (HKL hKL, UINT nItem, STYLEBUFW __RPC_FAR *pStyleBuf, UINT __RPC_FAR *puCopied)=0
virtual IFMETHOD GetStatusWindowPos (HIMC hIMC, POINT __RPC_FAR *pptPos)=0
static QString getString (HIMC himc, DWORD dwindex, int *selStart=0, int *selLength=0)
virtual IFMETHOD GetVirtualKey (HWND hWnd, UINT __RPC_FAR *puVirtualKey)=0
virtual IFMETHOD InstallIMEW (LPWSTR szIMEFileName, LPWSTR szLayoutText, HKL __RPC_FAR *phKL)=0
virtual IFMETHOD IsIME (HKL hKL)=0
bool isInPopup (QWidget *w)
bool isPopup (QWidget *w)
virtual IFMETHOD IsUIMessageW (HWND hWndIME, UINT msg, WPARAM wParam, LPARAM lParam)=0
virtual IFMETHOD NotifyIME (HIMC hIMC, DWORD dwAction, DWORD dwIndex, DWORD dwValue)=0
static void notifyIME (HIMC imc, DWORD dwAction, DWORD dwIndex, DWORD dwValue)
virtual IFMETHOD OnDefWindowProc (HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam, LRESULT __RPC_FAR *plResult)=0
virtual IFMETHOD OnTranslateMessage (const MSG __RPC_FAR *pMsg)=0
virtual IFMETHOD Pause (DWORD __RPC_FAR *pdwCookie)=0
bool qt_sendSpontaneousEvent (QObject *, QEvent *)
void qt_wince_show_SIP (bool show)
virtual IFMETHOD RegisterWordW (HKL hKL, LPWSTR szReading, DWORD dwStyle, LPWSTR szRegister)=0
virtual IFMETHOD ReleaseContext (HWND hWnd, HIMC hIMC)=0
static void releaseContext (HWND wnd, HIMC imc)
virtual IFMETHOD Resume (DWORD dwCookie)=0
virtual IFMETHOD SetCandidateWindow (HIMC hIMC, CANDIDATEFORM __RPC_FAR *pCandidate)=0
virtual IFMETHOD SetCompositionFontA (HIMC hIMC, LOGFONTA __RPC_FAR *plf)=0
virtual IFMETHOD SetCompositionFontW (HIMC hIMC, LOGFONTW __RPC_FAR *plf)=0
virtual IFMETHOD SetCompositionStringW (HIMC hIMC, DWORD dwIndex, LPVOID pComp, DWORD dwCompLen, LPVOID pRead, DWORD dwReadLen)=0
virtual IFMETHOD SetCompositionWindow (HIMC hIMC, COMPOSITIONFORM __RPC_FAR *pCompForm)=0
virtual IFMETHOD SetConversionStatus (HIMC hIMC, DWORD fdwConversion, DWORD fdwSentence)=0
virtual IFMETHOD SetOpenStatus (HIMC hIMC, BOOL fOpen)=0
virtual IFMETHOD SetStatusWindowPos (HIMC hIMC, POINT __RPC_FAR *pptPos)=0
virtual IFMETHOD SimulateHotKey (HWND hWnd, DWORD dwHotKeyID)=0
virtual IFMETHOD UnregisterWordW (HKL hKL, LPWSTR szReading, DWORD dwStyle, LPWSTR szUnregister)=0
Variables
static IActiveIMMApp * aimm = 0
static IActiveIMMMessagePumpOwner * aimmpump = 0
static HIMC defaultContext = 0
static bool haveCaret = false
interface HIMC hIME
static QString * imeComposition = 0
static int imePosition = -1
interface HIMC HIMC __RPC_FAR * phPrev = 0
bool qt_use_rtl_extensions
static DWORD WM_MSIME_MOUSE = 0
Macro Definition Documentation
IFMETHOD
#define IFMETHOD HRESULT STDMETHODCALLTYPE
Definition at line 90 of file qwininputcontext_win.cpp.
LGRPID_ARABIC
#define LGRPID_ARABIC 0x000d
Definition at line 206 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::QWinInputContext().
LGRPID_ARMENIAN
#define LGRPID_ARMENIAN 0x0011
Definition at line 210 of file qwininputcontext_win.cpp.
LGRPID_BALTIC
#define LGRPID_BALTIC 0x0003
Definition at line 196 of file qwininputcontext_win.cpp.
LGRPID_CENTRAL_EUROPE
#define LGRPID_CENTRAL_EUROPE 0x0002
Definition at line 195 of file qwininputcontext_win.cpp.
LGRPID_CYRILLIC
#define LGRPID_CYRILLIC 0x0005
Definition at line 198 of file qwininputcontext_win.cpp.
LGRPID_GEORGIAN
#define LGRPID_GEORGIAN 0x0010
Definition at line 209 of file qwininputcontext_win.cpp.
LGRPID_GREEK
#define LGRPID_GREEK 0x0004
Definition at line 197 of file qwininputcontext_win.cpp.
LGRPID_HEBREW
#define LGRPID_HEBREW 0x000c
Definition at line 205 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::QWinInputContext().
LGRPID_INDIC
#define LGRPID_INDIC 0x000f
Definition at line 208 of file qwininputcontext_win.cpp.
LGRPID_INSTALLED
#define LGRPID_INSTALLED 0x00000001
Definition at line 189 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::QWinInputContext().
LGRPID_JAPANESE
#define LGRPID_JAPANESE 0x0007
Definition at line 200 of file qwininputcontext_win.cpp.
LGRPID_KOREAN
#define LGRPID_KOREAN 0x0008
Definition at line 201 of file qwininputcontext_win.cpp.
LGRPID_SIMPLIFIED_CHINESE
#define LGRPID_SIMPLIFIED_CHINESE 0x000a
Definition at line 203 of file qwininputcontext_win.cpp.
LGRPID_SUPPORTED
#define LGRPID_SUPPORTED 0x00000002
Definition at line 190 of file qwininputcontext_win.cpp.
LGRPID_THAI
#define LGRPID_THAI 0x000b
Definition at line 204 of file qwininputcontext_win.cpp.
LGRPID_TRADITIONAL_CHINESE
#define LGRPID_TRADITIONAL_CHINESE 0x0009
Definition at line 202 of file qwininputcontext_win.cpp.
LGRPID_TURKISH
#define LGRPID_TURKISH 0x0006
Definition at line 199 of file qwininputcontext_win.cpp.
LGRPID_VIETNAMESE
#define LGRPID_VIETNAMESE 0x000e
Definition at line 207 of file qwininputcontext_win.cpp.
LGRPID_WESTERN_EUROPE
#define LGRPID_WESTERN_EUROPE 0x0001
Definition at line 194 of file qwininputcontext_win.cpp.
Enumeration Type Documentation
StandardFormat
enum StandardFormat
Enumerator
PreeditFormat
SelectionFormat
Definition at line 531 of file qwininputcontext_win.cpp.
                     {
     PreeditFormat,
     SelectionFormat
 };
Function Documentation
Activate()
virtual IFMETHOD Activate (BOOL fRestoreLayout) pure virtual
AssociateContextEx()
virtual IFMETHOD AssociateContextEx (HWND hWnd, HIMC hIMC, DWORD dwFlags) pure virtual
ConfigureIMEW()
virtual IFMETHOD ConfigureIMEW (HKL hKL, HWND hWnd, DWORD dwMode, REGISTERWORDW __RPC_FAR * pData) pure virtual
CreateContext()
virtual IFMETHOD CreateContext (HIMC __RPC_FAR * phIMC) pure virtual
Deactivate()
virtual IFMETHOD Deactivate (void) pure virtual
DEFINE_GUID() [1/3]
DEFINE_GUID (IID_IActiveIMMApp , 0x08c0e040 , 0x62d1 , 0x11d1 , 0x93 , 0x26 , 0x0 , 0x60 , 0xb0 , 0x67 , 0xb8 , 0x6e)
DEFINE_GUID() [2/3]
DEFINE_GUID (CLSID_CActiveIMM , 0x4955DD33 , 0xB159 , 0x11d0 , 0x8F , 0xCF , 0x0 , 0xAA , 0x00 , 0x6B , 0xCC , 0x59)
DEFINE_GUID() [3/3]
DEFINE_GUID (IID_IActiveIMMMessagePumpOwner , 0xb5cf2cfa , 0x8aeb , 0x11d1 , 0x93 , 0x64 , 0x0 , 0x60 , 0xb0 , 0x67 , 0xb8 , 0x6e)
DestroyContext()
virtual IFMETHOD DestroyContext (HIMC hIME) pure virtual
DisableIME()
virtual IFMETHOD DisableIME (DWORD idThread) pure virtual
dummy_ConfigureIMEA()
virtual IFMETHOD dummy_ConfigureIMEA () pure virtual
dummy_EnumRegisterWordA()
virtual IFMETHOD dummy_EnumRegisterWordA () pure virtual
dummy_EscapeA()
virtual IFMETHOD dummy_EscapeA () pure virtual
dummy_GetCandidateListA()
virtual IFMETHOD dummy_GetCandidateListA () pure virtual
dummy_GetCandidateListCountA()
virtual IFMETHOD dummy_GetCandidateListCountA () pure virtual
dummy_GetCodePageA()
virtual IFMETHOD dummy_GetCodePageA () pure virtual
dummy_GetCompositionFontA()
virtual IFMETHOD dummy_GetCompositionFontA () pure virtual
dummy_GetCompositionStringA()
virtual IFMETHOD dummy_GetCompositionStringA () pure virtual
dummy_GetConversionListA()
virtual IFMETHOD dummy_GetConversionListA () pure virtual
dummy_GetDescriptionA()
virtual IFMETHOD dummy_GetDescriptionA () pure virtual
dummy_GetGuideLineA()
virtual IFMETHOD dummy_GetGuideLineA () pure virtual
dummy_GetIMEFileNameA()
virtual IFMETHOD dummy_GetIMEFileNameA () pure virtual
dummy_GetImeMenuItemsA()
virtual IFMETHOD dummy_GetImeMenuItemsA () pure virtual
dummy_GetRegisterWordStyleA()
virtual IFMETHOD dummy_GetRegisterWordStyleA () pure virtual
dummy_InstallIMEA()
virtual IFMETHOD dummy_InstallIMEA () pure virtual
dummy_IsUIMessageA()
virtual IFMETHOD dummy_IsUIMessageA () pure virtual
dummy_RegisterWordA()
virtual IFMETHOD dummy_RegisterWordA () pure virtual
dummy_SetCompositionStringA()
virtual IFMETHOD dummy_SetCompositionStringA () pure virtual
dummy_UnregisterWordA()
virtual IFMETHOD dummy_UnregisterWordA () pure virtual
enableIme()
void enableIme (QWidget * w, bool value) inline
Definition at line 658 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::enable(), and QWinInputContext::enablePopupChild().
 {
     if (value) {
         // enable ime
         if (defaultContext)
             ImmAssociateContext(w->effectiveWinId(), defaultContext);
 #ifdef Q_WS_WINCE
         if (qApp->autoSipEnabled())
             qt_wince_show_SIP(true);
 #endif
     } else {
         // disable ime
         HIMC oldimc = ImmAssociateContext(w->effectiveWinId(), 0);
         if (!defaultContext)
             defaultContext = oldimc;
 #ifdef Q_WS_WINCE
         if (qApp->autoSipEnabled())
             qt_wince_show_SIP(false);
 #endif
     }
 }
End()
virtual IFMETHOD End (void) pure virtual
Referenced by gray_render_line().
EnumInputContext()
virtual IFMETHOD EnumInputContext (DWORD idThread, IEnumInputContext __RPC_FAR *__RPC_FAR * ppEnum) pure virtual
EnumRegisterWordW()
virtual IFMETHOD EnumRegisterWordW (HKL hKL, LPWSTR szReading, DWORD dwStyle, LPWSTR szRegister, LPVOID pData, IEnumRegisterWordW __RPC_FAR *__RPC_FAR * pEnum) pure virtual
EscapeW()
virtual IFMETHOD EscapeW (HKL hKL, HIMC hIMC, UINT uEscape, LPVOID pData, LRESULT __RPC_FAR * plResult) pure virtual
FilterClientWindows()
virtual IFMETHOD FilterClientWindows (ATOM __RPC_FAR * aaClassList, UINT uSize) pure virtual
findParentforPopup()
QWidget* findParentforPopup (QWidget * w) inline
Definition at line 641 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::enablePopupChild().
 {
     QWidget *e = QWidget::find(w->effectiveWinId());
     // check if this or its parent is a popup
     while (isInPopup(e)) {
         e = e->window()->parentWidget();
         if (!e)
             break;
         e = QWidget::find(e->effectiveWinId());
     }
     if (e)
         return e->window();
     else
         return 0;
 }
GetCandidateListCountW()
virtual IFMETHOD GetCandidateListCountW (HIMC hIMC, DWORD __RPC_FAR * pdwListSize, DWORD __RPC_FAR * pdwBufLen) pure virtual
GetCandidateListW()
virtual IFMETHOD GetCandidateListW (HIMC hIMC, DWORD dwIndex, UINT uBufLen, CANDIDATELIST __RPC_FAR * pCandList, UINT __RPC_FAR * puCopied) pure virtual
GetCandidateWindow()
virtual IFMETHOD GetCandidateWindow (HIMC hIMC, DWORD dwIndex, CANDIDATEFORM __RPC_FAR * pCandidate) pure virtual
GetCompositionFontW()
virtual IFMETHOD GetCompositionFontW (HIMC hIMC, LOGFONTW __RPC_FAR * plf) pure virtual
getCompositionString()
static LONG getCompositionString (HIMC himc, DWORD dwIndex, LPVOID lpbuf, DWORD dBufLen) static
Definition at line 314 of file qwininputcontext_win.cpp.
Referenced by getCursorPosition(), and getString().
 {
     LONG len = 0;
     if (aimm)
         aimm->GetCompositionStringW(himc, dwIndex, dBufLen, &len, lpbuf);
     else
         len = ImmGetCompositionString(himc, dwIndex, lpbuf, dBufLen);
     return len;
 }
GetCompositionStringW()
virtual IFMETHOD GetCompositionStringW (HIMC hIMC, DWORD dwIndex, DWORD dwBufLen, LONG __RPC_FAR * plCopied, LPVOID pBuf) pure virtual
GetCompositionWindow()
virtual IFMETHOD GetCompositionWindow (HIMC hIMC, COMPOSITIONFORM __RPC_FAR * pCompForm) pure virtual
GetContext()
virtual IFMETHOD GetContext (HWND hWnd, HIMC __RPC_FAR * phIMC) pure virtual
getContext()
static HIMC getContext (HWND wnd) static
Definition at line 285 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::composition(), QWinInputContext::endComposition(), QDeclarativeEnginePrivate::get(), QWinInputContext::mouseHandler(), QWinInputContext::reset(), and QWinInputContext::update().
 {
     HIMC imc;
     if (aimm)
         aimm->GetContext(wnd, &imc);
     else
         imc = ImmGetContext(wnd);
     return imc;
 }
GetConversionListW()
virtual IFMETHOD GetConversionListW (HKL hKL, HIMC hIMC, LPWSTR pSrc, UINT uBufLen, UINT uFlag, CANDIDATELIST __RPC_FAR * pDst, UINT __RPC_FAR * puCopied) pure virtual
GetConversionStatus()
virtual IFMETHOD GetConversionStatus (HIMC hIMC, DWORD __RPC_FAR * pfdwConversion, DWORD __RPC_FAR * pfdwSentence) pure virtual
getCursorPosition()
static int getCursorPosition (HIMC himc) static
Definition at line 324 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::composition().
 {
     return getCompositionString(himc, GCS_CURSORPOS, 0, 0);
 }
GetDefaultIMEWnd()
virtual IFMETHOD GetDefaultIMEWnd (HWND hWnd, HWND __RPC_FAR * phDefWnd) pure virtual
getDefaultIMEWnd()
static HWND getDefaultIMEWnd (HWND wnd) static
Definition at line 275 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::mouseHandler().
 {
     HWND ime_wnd;
     if(aimm)
         aimm->GetDefaultIMEWnd(wnd, &ime_wnd);
     else
         ime_wnd = ImmGetDefaultIMEWnd(wnd);
     return ime_wnd;
 }
GetDescriptionW()
virtual IFMETHOD GetDescriptionW (HKL hKL, UINT uBufLen, LPWSTR szDescription, UINT __RPC_FAR * puCopied) pure virtual
GetGuideLineW()
virtual IFMETHOD GetGuideLineW (HIMC hIMC, DWORD dwIndex, DWORD dwBufLen, LPWSTR pBuf, DWORD __RPC_FAR * pdwResult) pure virtual
GetIMEFileNameW()
virtual IFMETHOD GetIMEFileNameW (HKL hKL, UINT uBufLen, LPWSTR szFileName, UINT __RPC_FAR * puCopied) pure virtual
GetImeMenuItemsW()
virtual IFMETHOD GetImeMenuItemsW (HIMC hIMC, DWORD dwFlags, DWORD dwType, void __RPC_FAR * pImeParentMenu, void __RPC_FAR * pImeMenu, DWORD dwSize, DWORD __RPC_FAR * pdwResult) pure virtual
GetLangId()
virtual IFMETHOD GetLangId (HKL hKL, LANGID __RPC_FAR * plid) pure virtual
GetOpenStatus()
virtual IFMETHOD GetOpenStatus (HIMC hIMC) pure virtual
GetProperty()
virtual IFMETHOD GetProperty (HKL hKL, DWORD fdwIndex, DWORD __RPC_FAR * pdwProperty) pure virtual
GetRegisterWordStyleW()
virtual IFMETHOD GetRegisterWordStyleW (HKL hKL, UINT nItem, STYLEBUFW __RPC_FAR * pStyleBuf, UINT __RPC_FAR * puCopied) pure virtual
GetStatusWindowPos()
virtual IFMETHOD GetStatusWindowPos (HIMC hIMC, POINT __RPC_FAR * pptPos) pure virtual
getString()
static QString getString (HIMC himc, DWORD dwindex, int * selStart = 0, int * selLength = 0) static
Definition at line 329 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::composition().
 {
     const int bufferSize = 256;
     wchar_t buffer[bufferSize];
     int len = getCompositionString(himc, dwindex, buffer, bufferSize * sizeof(wchar_t));
     if (selStart) {
         char attrbuffer[bufferSize];
         int attrlen = getCompositionString(himc, GCS_COMPATTR, attrbuffer, bufferSize);
         *selStart = attrlen+1;
         *selLength = -1;
         for (int i = 0; i < attrlen; i++) {
             if (attrbuffer[i] & ATTR_TARGET_CONVERTED) {
                 *selStart = qMin(*selStart, i);
                 *selLength = qMax(*selLength, i);
             }
         }
         *selLength = qMax(0, *selLength - *selStart + 1);
     }
     if (len <= 0)
         return QString();
     return QString((QChar*)buffer, len / sizeof(QChar));
 }
GetVirtualKey()
virtual IFMETHOD GetVirtualKey (HWND hWnd, UINT __RPC_FAR * puVirtualKey) pure virtual
InstallIMEW()
virtual IFMETHOD InstallIMEW (LPWSTR szIMEFileName, LPWSTR szLayoutText, HKL __RPC_FAR * phKL) pure virtual
IsIME()
virtual IFMETHOD IsIME (HKL hKL) pure virtual
isInPopup()
bool isInPopup (QWidget * w) inline
Definition at line 631 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::enablePopupChild(), findParentforPopup(), and QWinInputContext::updateImeStatus().
 {
     if (w && (isPopup(w) ||  isPopup(w->window())))
         return true;
     else
         return false;
 }
isPopup()
bool isPopup (QWidget * w) inline
Definition at line 623 of file qwininputcontext_win.cpp.
Referenced by isInPopup().
 {
     if (w && (w->windowFlags() & Qt::Popup) == Qt::Popup)
         return true;
     else
         return false;
 }
IsUIMessageW()
virtual IFMETHOD IsUIMessageW (HWND hWndIME, UINT msg, WPARAM wParam, LPARAM lParam) pure virtual
NotifyIME()
virtual IFMETHOD NotifyIME (HIMC hIMC, DWORD dwAction, DWORD dwIndex, DWORD dwValue) pure virtual
notifyIME()
static void notifyIME (HIMC imc, DWORD dwAction, DWORD dwIndex, DWORD dwValue) static
Definition at line 304 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::endComposition(), and QWinInputContext::reset().
 {
     if (!imc)
         return;
     if (aimm)
         aimm->NotifyIME(imc, dwAction, dwIndex, dwValue);
     else
         ImmNotifyIME(imc, dwAction, dwIndex, dwValue);
 }
OnDefWindowProc()
virtual IFMETHOD OnDefWindowProc (HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam, LRESULT __RPC_FAR * plResult) pure virtual
OnTranslateMessage()
virtual IFMETHOD OnTranslateMessage (const MSG __RPC_FAR * pMsg) pure virtual
Pause()
virtual IFMETHOD Pause (DWORD __RPC_FAR * pdwCookie) pure virtual
Referenced by QDeclarativeTimeLinePrivate::advance().
qt_sendSpontaneousEvent()
bool qt_sendSpontaneousEvent (QObject * , QEvent *)
Definition at line 5779 of file qapplication.cpp.
Referenced by QWinInputContext::composition(), QWinInputContext::endComposition(), QWinInputContext::reconvertString(), and QWinInputContext::reset().
 {
     return QCoreApplication::sendSpontaneousEvent(receiver, event);
 }
qt_wince_show_SIP()
void qt_wince_show_SIP (bool show)
Definition at line 394 of file qguifunctions_wince.cpp.
Referenced by enableIme().
 {
     resolveAygLibs();
     if (!ptrAygSHSipInfo)
         return;
     AygSIPINFO si;
     memset(&si, 0, sizeof(si));
     si.cbSize = sizeof(si);
     ptrAygSHSipInfo(SPI_GETSIPINFO, 0, &si, 0);
     si.cbSize = sizeof(si);
     si.fdwFlags = (show ? SIPF_ON : SIPF_OFF);
     ptrAygSHSipInfo(SPI_SETSIPINFO, 0, &si, 0);
 }
RegisterWordW()
virtual IFMETHOD RegisterWordW (HKL hKL, LPWSTR szReading, DWORD dwStyle, LPWSTR szRegister) pure virtual
ReleaseContext()
virtual IFMETHOD ReleaseContext (HWND hWnd, HIMC hIMC) pure virtual
releaseContext()
static void releaseContext (HWND wnd, HIMC imc) static
Definition at line 296 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::composition(), QWinInputContext::endComposition(), QWinInputContext::mouseHandler(), QWinInputContext::reset(), and QWinInputContext::update().
 {
     if (aimm)
         aimm->ReleaseContext(wnd, imc);
     else
         ImmReleaseContext(wnd, imc);
 }
Resume()
virtual IFMETHOD Resume (DWORD dwCookie) pure virtual
SetCandidateWindow()
virtual IFMETHOD SetCandidateWindow (HIMC hIMC, CANDIDATEFORM __RPC_FAR * pCandidate) pure virtual
SetCompositionFontA()
virtual IFMETHOD SetCompositionFontA (HIMC hIMC, LOGFONTA __RPC_FAR * plf) pure virtual
SetCompositionFontW()
virtual IFMETHOD SetCompositionFontW (HIMC hIMC, LOGFONTW __RPC_FAR * plf) pure virtual
SetCompositionStringW()
virtual IFMETHOD SetCompositionStringW (HIMC hIMC, DWORD dwIndex, LPVOID pComp, DWORD dwCompLen, LPVOID pRead, DWORD dwReadLen) pure virtual
SetCompositionWindow()
virtual IFMETHOD SetCompositionWindow (HIMC hIMC, COMPOSITIONFORM __RPC_FAR * pCompForm) pure virtual
SetConversionStatus()
virtual IFMETHOD SetConversionStatus (HIMC hIMC, DWORD fdwConversion, DWORD fdwSentence) pure virtual
SetOpenStatus()
virtual IFMETHOD SetOpenStatus (HIMC hIMC, BOOL fOpen) pure virtual
SetStatusWindowPos()
virtual IFMETHOD SetStatusWindowPos (HIMC hIMC, POINT __RPC_FAR * pptPos) pure virtual
SimulateHotKey()
virtual IFMETHOD SimulateHotKey (HWND hWnd, DWORD dwHotKeyID) pure virtual
UnregisterWordW()
virtual IFMETHOD UnregisterWordW (HKL hKL, LPWSTR szReading, DWORD dwStyle, LPWSTR szUnregister) pure virtual
Variable Documentation
aimm
IActiveIMMApp* aimm = 0 static
Definition at line 181 of file qwininputcontext_win.cpp.
aimmpump
IActiveIMMMessagePumpOwner* aimmpump = 0 static
Definition at line 182 of file qwininputcontext_win.cpp.
defaultContext
HIMC defaultContext = 0 static
Definition at line 620 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::enable(), and enableIme().
haveCaret
bool haveCaret = false static
Definition at line 186 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::endComposition(), QWinInputContext::startComposition(), and QWinInputContext::update().
hIME
interface HIMC hIME
Definition at line 95 of file qwininputcontext_win.cpp.
imeComposition
QString* imeComposition = 0 static
Definition at line 183 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::~QWinInputContext().
imePosition
int imePosition = -1 static
Definition at line 184 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::composition(), QWinInputContext::endComposition(), QWinInputContext::reset(), and QWinInputContext::startComposition().
phPrev
interface HIMC HIMC __RPC_FAR* phPrev = 0
Definition at line 95 of file qwininputcontext_win.cpp.
qt_use_rtl_extensions
bool qt_use_rtl_extensions
Definition at line 266 of file qapplication_win.cpp.
Referenced by QWinInputContext::QWinInputContext().
WM_MSIME_MOUSE
DWORD WM_MSIME_MOUSE = 0 static
Definition at line 213 of file qwininputcontext_win.cpp.
Referenced by QWinInputContext::mouseHandler(), and QWinInputContext::QWinInputContext().