Qt 4.8: /src/gui/kernel/qwindowdefs_win.h File Reference
qwindowdefs_win.h File Reference
#include <QtCore/qglobal.h>
Macros
#define Q_DECLARE_HANDLE(name) struct name##__; typedef struct name##__ *name
#define Q_WINSTRICT
#define STRICT
Typedefs
typedef HICON HCURSOR
typedef long HRESULT
typedef struct tagMSG MSG
typedef HWND WId
Functions
Q_DECLARE_HANDLE (HINSTANCE)
Q_DECLARE_HANDLE (HDC)
Q_DECLARE_HANDLE (HWND)
Q_DECLARE_HANDLE (HFONT)
Q_DECLARE_HANDLE (HPEN)
Q_DECLARE_HANDLE (HBRUSH)
Q_DECLARE_HANDLE (HBITMAP)
Q_DECLARE_HANDLE (HICON)
Q_DECLARE_HANDLE (HPALETTE)
Q_DECLARE_HANDLE (HRGN)
Q_DECLARE_HANDLE (HMONITOR)
Q_GUI_EXPORT HDC qt_win_display_dc ()
Q_CORE_EXPORT int qWinAppCmdShow ()
Q_CORE_EXPORT HINSTANCE qWinAppInst ()
Q_CORE_EXPORT HINSTANCE qWinAppPrevInst ()
Macro Definition Documentation
Q_DECLARE_HANDLE
#define Q_DECLARE_HANDLE (name) struct name##__; typedef struct name##__ *name
Definition at line 65 of file qwindowdefs_win.h.
Q_WINSTRICT
#define Q_WINSTRICT
Definition at line 56 of file qwindowdefs_win.h.
STRICT
#define STRICT
Definition at line 62 of file qwindowdefs_win.h.
Typedef Documentation
HCURSOR
typedef HICON HCURSOR
Definition at line 102 of file qwindowdefs_win.h.
HRESULT
typedef HRESULT(WINAPI *) PtrGetThemePartSize(HTHEME hTheme, HDC hdc, int iPartId, int iStateId, OPTIONAL RECT *prc, enum THEMESIZE eSize, OUT SIZE *psz)
Definition at line 114 of file qwindowdefs_win.h.
MSG
typedef struct tagMSG MSG
Definition at line 117 of file qwindowdefs_win.h.
WId
typedef HWND WId related
Definition at line 118 of file qwindowdefs_win.h.
Function Documentation
Q_DECLARE_HANDLE() [1/11]
Q_DECLARE_HANDLE (HINSTANCE)
Q_DECLARE_HANDLE() [2/11]
Q_DECLARE_HANDLE (HDC)
Q_DECLARE_HANDLE() [3/11]
Q_DECLARE_HANDLE (HWND)
Q_DECLARE_HANDLE() [4/11]
Q_DECLARE_HANDLE (HFONT)
Q_DECLARE_HANDLE() [5/11]
Q_DECLARE_HANDLE (HPEN)
Q_DECLARE_HANDLE() [6/11]
Q_DECLARE_HANDLE (HBRUSH)
Q_DECLARE_HANDLE() [7/11]
Q_DECLARE_HANDLE (HBITMAP)
Q_DECLARE_HANDLE() [8/11]
Q_DECLARE_HANDLE (HICON)
Q_DECLARE_HANDLE() [9/11]
Q_DECLARE_HANDLE (HPALETTE)
Q_DECLARE_HANDLE() [10/11]
Q_DECLARE_HANDLE (HRGN)
Q_DECLARE_HANDLE() [11/11]
Q_DECLARE_HANDLE (HMONITOR)
qt_win_display_dc()
Q_GUI_EXPORT HDC qt_win_display_dc ()
Definition at line 942 of file qapplication_win.cpp.
 {
     Q_ASSERT(qApp && qApp->thread() == QThread::currentThread());
     if (!displayDC)
         displayDC = GetDC(0);
     return displayDC;
 }
qWinAppCmdShow()
Q_CORE_EXPORT int qWinAppCmdShow ()
Definition at line 68 of file qcoreapplication_win.cpp.
 {
 #if defined(Q_OS_WINCE)
     return appCmdShow;
 #else
     STARTUPINFO startupInfo;
     GetStartupInfo(&startupInfo);
     return (startupInfo.dwFlags & STARTF_USESHOWWINDOW)
         ? startupInfo.wShowWindow
         : SW_SHOWDEFAULT;
 #endif
 }
qWinAppInst()
Q_CORE_EXPORT HINSTANCE qWinAppInst ()
Definition at line 58 of file qcoreapplication_win.cpp.
Referenced by create32BitCursor(), qt_reg_winclass(), qt_tablet_cleanup_wce(), qt_wce_get_module_handle(), unregWinClasses(), and QMenuBarPrivate::wceCreateMenuBar().
 {
     return GetModuleHandle(0);
 }
qWinAppPrevInst()
Q_CORE_EXPORT HINSTANCE qWinAppPrevInst ()
Definition at line 63 of file qcoreapplication_win.cpp.
 {
     return 0;
 }