Qt 4.8: /src/gui/widgets/qworkspace.cpp File Reference
qworkspace.cpp File Reference
#include "qworkspace.h"
#include "qapplication.h"
#include "qbitmap.h"
#include "qcursor.h"
#include "qdesktopwidget.h"
#include "qevent.h"
#include "qhash.h"
#include "qicon.h"
#include "qimage.h"
#include "qlabel.h"
#include "qlayout.h"
#include "qmenubar.h"
#include "qmenu.h"
#include "qpainter.h"
#include "qpointer.h"
#include "qscrollbar.h"
#include "qstyle.h"
#include "qstyleoption.h"
#include "qelapsedtimer.h"
#include "qtooltip.h"
#include "qdebug.h"
#include <private/qwidget_p.h>
#include <private/qwidgetresizehandler_p.h>
#include <private/qlayoutengine_p.h>
#include "moc_qworkspace.cpp"
#include "qworkspace.moc"
Classes
class QMDIControl
class QWorkspaceChild
class QWorkspacePrivate
class QWorkspaceTitleBar
class QWorkspaceTitleBarPrivate
Macros
#define COLOR_GRADIENTACTIVECAPTION 27
#define COLOR_GRADIENTINACTIVECAPTION 28
#define SPI_GETGRADIENTCAPTIONS 0x1008
Functions
static QRgb colorref2qrgb (COLORREF col)
static QMenuBar * findMenuBar (QWidget *w)
static bool isChildOf (QWidget *child, QWidget *parent)
QString qt_setWindowTitle_helperHelper (const QString &, const QWidget *)
Returns a modified window title with the [*] place holder replaced according to the rules described in QWidget::setWindowTitle.
Macro Definition Documentation
COLOR_GRADIENTACTIVECAPTION
#define COLOR_GRADIENTACTIVECAPTION 27
Referenced by QWorkspaceTitleBarPrivate::readColors().
COLOR_GRADIENTINACTIVECAPTION
#define COLOR_GRADIENTINACTIVECAPTION 28
Referenced by QWorkspaceTitleBarPrivate::readColors().
SPI_GETGRADIENTCAPTIONS
#define SPI_GETGRADIENTCAPTIONS 0x1008
Referenced by QWorkspaceTitleBarPrivate::readColors().
Function Documentation
colorref2qrgb()
static QRgb colorref2qrgb (COLORREF col) inline static
Definition at line 372 of file qworkspace.cpp.
Referenced by QWorkspaceTitleBarPrivate::readColors().
 {
     return qRgb(GetRValue(col),GetGValue(col),GetBValue(col));
 }
findMenuBar()
static QMenuBar* findMenuBar (QWidget * w) static
Definition at line 1925 of file qworkspace.cpp.
Referenced by QWorkspacePrivate::showMaximizeControls().
 {
     // don't search recursively to avoid finding a menu bar of a
     // mainwindow that happens to be a workspace window (like
     // a mainwindow in designer)
     QList<QObject *> children = w->children();
     for (int i = 0; i < children.count(); ++i) {
         QMenuBar *bar = qobject_cast<QMenuBar *>(children.at(i));
         if (bar)
             return bar;
     }
     return 0;
 }
isChildOf()
static bool isChildOf (QWidget * child, QWidget * parent) static
Definition at line 1037 of file qworkspace.cpp.
Referenced by QWorkspacePrivate::activateWindow(), and QWorkspaceChild::setActive().
 {
     if (!parent || !child)
         return false;
     QWidget * w = child;
     while(w && w != parent)
         w = w->parentWidget();
     return w != 0;
 }
qt_setWindowTitle_helperHelper()
QString qt_setWindowTitle_helperHelper (const QString & title, const QWidget * widget)
Returns a modified window title with the [*] place holder replaced according to the rules described in QWidget::setWindowTitle.
This function assumes that "[*]" can be quoted by another "[*]", so it will replace two place holders by one and a single last one by either "*" or nothing depending on the modified flag.
Warning
This function is not part of the public interface.
Definition at line 6240 of file qwidget.cpp.
Referenced by QWorkspaceTitleBar::isTool(), QWorkspaceTitleBar::paintEvent(), QWidgetPrivate::setWindowIconText_helper(), and QWidgetPrivate::setWindowTitle_helper().
 {
     Q_ASSERT(widget);
 #ifdef QT_EVAL
     extern QString qt_eval_adapt_window_title(const QString &title);
     QString cap = qt_eval_adapt_window_title(title);
 #else
     QString cap = title;
 #endif
     if (cap.isEmpty())
         return cap;
     QLatin1String placeHolder("[*]");
     int placeHolderLength = 3; // QLatin1String doesn't have length()
     int index = cap.indexOf(placeHolder);
     // here the magic begins
     while (index != -1) {
         index += placeHolderLength;
         int count = 1;
         while (cap.indexOf(placeHolder, index) == index) {
             ++count;
             index += placeHolderLength;
         }
         if (count%2) { // odd number of [*] -> replace last one
             int lastIndex = cap.lastIndexOf(placeHolder, index - 1);
             if (widget->isWindowModified()
              && widget->style()->styleHint(QStyle::SH_TitleBar_ModifyNotification, 0, widget))
                 cap.replace(lastIndex, 3, QWidget::tr("*"));
             else
                 cap.remove(lastIndex, 3);
         }
         index = cap.indexOf(placeHolder, index);
     }
     cap.replace(QLatin1String("[*][*]"), placeHolder);
     return cap;
 }