Qt 4.8: /src/gui/embedded/qwscommand_qws_p.h File Reference
qwscommand_qws_p.h File Reference
#include <QtCore/qbytearray.h>
#include <QtGui/qwsutils_qws.h>
#include <QtGui/qfont.h>
#include <QtCore/qdatastream.h>
#include <QtCore/qvariant.h>
#include <QtCore/qrect.h>
#include <QtGui/qregion.h>
#include <QtCore/qvector.h>
#include <QtCore/qvarlengtharray.h>
#include <QtGui/qwsevent_qws.h>
#include "qwsprotocolitem_qws.h"
Classes
struct QWSAddPropertyCommand
struct QWSAddPropertyCommand::SimpleData
struct QWSChangeAltitudeCommand
struct QWSChangeAltitudeCommand::SimpleData
struct QWSCommand
struct QWSConvertSelectionCommand
struct QWSConvertSelectionCommand::SimpleData
struct QWSCreateCommand
struct QWSDefineCursorCommand
struct QWSDefineCursorCommand::SimpleData
struct QWSEmbedCommand
struct QWSFontCommand
struct QWSFontCommand::SimpleData
struct QWSGetPropertyCommand
struct QWSGetPropertyCommand::SimpleData
struct QWSGrabKeyboardCommand
struct QWSGrabKeyboardCommand::SimpleData
struct QWSGrabMouseCommand
struct QWSGrabMouseCommand::SimpleData
struct QWSIdentifyCommand
struct QWSIdentifyCommand::SimpleData
struct QWSIMMouseCommand
struct QWSIMMouseCommand::SimpleData
struct QWSIMResponseCommand
struct QWSIMResponseCommand::SimpleData
struct QWSIMUpdateCommand
struct QWSIMUpdateCommand::SimpleData
struct QWSPlaySoundCommand
struct QWSPlaySoundCommand::SimpleData
struct QWSPositionCursorCommand
struct QWSPositionCursorCommand::SimpleData
struct QWSQCopRegisterChannelCommand
struct QWSQCopRegisterChannelCommand::SimpleData
struct QWSQCopSendCommand
struct QWSQCopSendCommand::SimpleData
struct QWSRegionCommand
struct QWSRegionCommand::SimpleData
struct QWSRegionDestroyCommand
struct QWSRegionDestroyCommand::SimpleData
struct QWSRegionMoveCommand
struct QWSRegionMoveCommand::SimpleData
struct QWSRegionNameCommand
struct QWSRegionNameCommand::SimpleData
struct QWSRemovePropertyCommand
struct QWSRemovePropertyCommand::SimpleData
struct QWSRepaintRegionCommand
struct QWSRepaintRegionCommand::SimpleData
struct QWSRequestFocusCommand
struct QWSRequestFocusCommand::SimpleData
struct QWSScreenTransformCommand
struct QWSScreenTransformCommand::SimpleData
struct QWSSelectCursorCommand
struct QWSSelectCursorCommand::SimpleData
struct QWSSetOpacityCommand
struct QWSSetOpacityCommand::SimpleData
struct QWSSetPropertyCommand
struct QWSSetPropertyCommand::SimpleData
struct QWSSetSelectionOwnerCommand
struct QWSSetSelectionOwnerCommand::SimpleData
Macros
#define MAX_COMMAND_SIZE (16 * 1024)
Functions
QDebug & operator<< (QDebug &dbg, QWSCommand::Type tp)
const char * qws_getCommandTypeString (QWSCommand::Type tp)
bool qws_read_command (QIODevice *socket, char *&simpleData, int &simpleLen, char *&rawData, int &rawLen, int &bytesRead)
void qws_write_command (QIODevice *socket, int type, char *simpleData, int simpleLen, char *rawData, int rawLen)
Macro Definition Documentation
MAX_COMMAND_SIZE
#define MAX_COMMAND_SIZE (16 * 1024)
Definition at line 60 of file qwscommand_qws_p.h.
Referenced by qws_read_command(), qws_write_command(), QWSIdentifyCommand::setData(), QWSRegionNameCommand::setData(), and QWSQCopRegisterChannelCommand::setData().
Function Documentation
operator<<()
QDebug& operator<< (QDebug & dbg, QWSCommand::Type tp)
qws_getCommandTypeString()
const char* qws_getCommandTypeString (QWSCommand::Type tp)
Definition at line 243 of file qwscommand_qws.cpp.
Referenced by RequestAnalyzer::analyze().
 {
     const char *typeStr;
     switch(tp) {
         case QWSCommand::Create:
             typeStr = "Create";
             break;
         case QWSCommand::Shutdown:
             typeStr = "Shutdown";
             break;
         case QWSCommand::Region:
             typeStr = "Region";
             break;
         case QWSCommand::RegionMove:
             typeStr = "RegionMove";
             break;
         case QWSCommand::RegionDestroy:
             typeStr = "RegionDestroy";
             break;
         case QWSCommand::SetProperty:
             typeStr = "SetProperty";
             break;
         case QWSCommand::AddProperty:
             typeStr = "AddProperty";
             break;
         case QWSCommand::RemoveProperty:
             typeStr = "RemoveProperty";
             break;
         case QWSCommand::GetProperty:
             typeStr = "GetProperty";
             break;
         case QWSCommand::SetSelectionOwner:
             typeStr = "SetSelectionOwner";
             break;
         case QWSCommand::ConvertSelection:
             typeStr = "ConvertSelection";
             break;
         case QWSCommand::RequestFocus:
             typeStr = "RequestFocus";
             break;
         case QWSCommand::ChangeAltitude:
             typeStr = "ChangeAltitude";
             break;
         case QWSCommand::SetOpacity:
             typeStr = "SetOpacity";
             break;
         case QWSCommand::DefineCursor:
             typeStr = "DefineCursor";
             break;
         case QWSCommand::SelectCursor:
             typeStr = "SelectCursor";
             break;
         case QWSCommand::PositionCursor:
             typeStr = "PositionCursor";
             break;
         case QWSCommand::GrabMouse:
             typeStr = "GrabMouse";
             break;
         case QWSCommand::PlaySound:
             typeStr = "PlaySound";
             break;
         case QWSCommand::QCopRegisterChannel:
             typeStr = "QCopRegisterChannel";
             break;
         case QWSCommand::QCopSend:
             typeStr = "QCopSend";
             break;
         case QWSCommand::RegionName:
             typeStr = "RegionName";
             break;
         case QWSCommand::Identify:
             typeStr = "Identify";
             break;
         case QWSCommand::GrabKeyboard:
             typeStr = "GrabKeyboard";
             break;
         case QWSCommand::RepaintRegion:
             typeStr = "RepaintRegion";
             break;
         case QWSCommand::IMMouse:
             typeStr = "IMMouse";
             break;
         case QWSCommand::IMUpdate:
             typeStr = "IMUpdate";
             break;
         case QWSCommand::IMResponse:
             typeStr = "IMResponse";
             break;
         case QWSCommand::Font:
             typeStr = "Font";
             break;
         case QWSCommand::Unknown:
         default:
             typeStr = "Unknown";
             break;
     }
     return typeStr;
 }
qws_read_command()
bool qws_read_command (QIODevice * socket, char *& simpleData, int & simpleLen, char *& rawData, int & rawLen, int & bytesRead)
Definition at line 388 of file qwscommand_qws.cpp.
Referenced by QWSProtocolItem::read().
 {
     // read rawLen
     if (rawLen == -1) {
         rawLen = qws_read_uint(socket);
         if (rawLen == -1)
             return false;
     }
     // read simpleData, assumes socket is capable of buffering all the data
     if (simpleLen && !rawData) {
         if (socket->bytesAvailable() < uint(simpleLen))
             return false;
         int tmp = socket->read(simpleData, simpleLen);
         Q_ASSERT(tmp == simpleLen);
         Q_UNUSED(tmp);
     }
     if (rawLen > MAX_COMMAND_SIZE) {
         socket->close();
         qWarning("qws_read_command: Won't read command of length %d, "
                  "connection closed.", rawLen);
         return false;
     }
     // read rawData
     if (rawLen && !rawData) {
         rawData = new char[rawLen];
         bytesRead = 0;
     }
     if (bytesRead < rawLen && socket->bytesAvailable())
         bytesRead += socket->read(rawData + bytesRead, rawLen - bytesRead);
     return (bytesRead == rawLen);
 }
qws_write_command()
void qws_write_command (QIODevice * socket, int type, char * simpleData, int simpleLen, char * rawData, int rawLen)
Definition at line 350 of file qwscommand_qws.cpp.
Referenced by QWSProtocolItem::write().
 {
 #ifdef QWSCOMMAND_DEBUG
     if (simpleLen) qDebug() << "WRITE simpleData " << QWSHexDump(simpleData, simpleLen);
     if (rawLen > 0) qDebug() << "WRITE rawData " << QWSHexDump(rawData, rawLen);
 #endif
 #ifndef QT_NO_SXE
     QTransportAuth *a = QTransportAuth::getInstance();
     // ###### as soon as public API can be modified get rid of horrible casts
     QIODevice *ad = a->passThroughByClient(reinterpret_cast<QWSClient*>(socket));
     if (ad)
         socket = ad;
 #endif
     qws_write_uint(socket, type);
     if (rawLen > MAX_COMMAND_SIZE) {
         qWarning("qws_write_command: Message of size %d too big. "
                  "Truncated to %d", rawLen, MAX_COMMAND_SIZE);
         rawLen = MAX_COMMAND_SIZE;
     }
     qws_write_uint(socket, rawLen == -1 ? 0 : rawLen);
     if (simpleData && simpleLen)
         socket->write(simpleData, simpleLen);
     if (rawLen && rawData)
         socket->write(rawData, rawLen);
 }