Qt 4.8: /src/gui/embedded/qwsutils_qws.h File Reference
qwsutils_qws.h File Reference
#include <QtCore/QIODevice>
Macros
#define QWS_SOCK_BASE QUnixSocket
#define QWS_SOCK_SERVER_BASE QUnixSocketServer
Functions
int qws_read_uint (QIODevice *socket)
void qws_write_uint (QIODevice *socket, int i)
Macro Definition Documentation
QWS_SOCK_BASE
#define QWS_SOCK_BASE QUnixSocket
Definition at line 54 of file qwsutils_qws.h.
Referenced by QWSServerPrivate::_q_newConnection().
QWS_SOCK_SERVER_BASE
#define QWS_SOCK_SERVER_BASE QUnixSocketServer
Definition at line 55 of file qwsutils_qws.h.
Function Documentation
qws_read_uint()
int qws_read_uint (QIODevice * socket) inline
Definition at line 73 of file qwsutils_qws.h.
Referenced by RequestAnalyzer::analyze(), qws_read_command(), QWSDisplay::Data::readMore(), and QWSClient::readMoreCommand().
 {
     if (!socket || socket->bytesAvailable() < (int)sizeof(int))
         return -1;
     int i;
     socket->read(reinterpret_cast<char*>(&i), sizeof(i));
     return i;
 }
qws_write_uint()
void qws_write_uint (QIODevice * socket, int i) inline
Definition at line 84 of file qwsutils_qws.h.
Referenced by qws_write_command().
 {
     if (!socket)
         return;
     socket->write(reinterpret_cast<char*>(&i), sizeof(i));
 }