Qt 4.8: /src/gui/kernel/qx11embed_x11.cpp File Reference
qx11embed_x11.cpp File Reference
#include "qplatformdefs.h"
#include "qx11embed_x11.h"
#include <qapplication.h>
#include <qevent.h>
#include <qpainter.h>
#include <qlayout.h>
#include <qstyle.h>
#include <qstyleoption.h>
#include <qelapsedtimer.h>
#include <qpointer.h>
#include <qdebug.h>
#include <qx11info_x11.h>
#include <private/qt_x11_p.h>
#include <private/qwidget_p.h>
#include <X11/Xlib.h>
#include <X11/Xatom.h>
#include <X11/Xutil.h>
#include <X11/keysymdef.h>
#include <X11/X.h>
Classes
struct functorData
class QHackWidget
class QX11EmbedContainerPrivate
class QX11EmbedWidgetPrivate
Macros
#define None 0
#define XK_ISO_Left_Tab 0xFE20
#define XK_LATIN1
#define XK_MISCELLANY
Enumerations
enum QX11EmbedAccelFlags { XEMBED_ACCELERATOR_OVERLOADED = (1 << 0) }
enum QX11EmbedAccelModifiers {
XEMBED_MODIFIER_SHIFT = (1 << 0), XEMBED_MODIFIER_CONTROL = (1 << 1), XEMBED_MODIFIER_ALT = (1 << 2), XEMBED_MODIFIER_SUPER = (1 << 3),
XEMBED_MODIFIER_HYPER = (1 << 4)
}
enum QX11EmbedFocusInDetail { XEMBED_FOCUS_CURRENT = 0, XEMBED_FOCUS_FIRST = 1, XEMBED_FOCUS_LAST = 2 }
enum QX11EmbedFocusInFlags { XEMBED_FOCUS_OTHER = (0 << 0), XEMBED_FOCUS_WRAPAROUND = (1 << 0) }
enum QX11EmbedInfoFlags { XEMBED_MAPPED = (1 << 0) }
enum QX11EmbedMessageType {
XEMBED_EMBEDDED_NOTIFY = 0, XEMBED_WINDOW_ACTIVATE = 1, XEMBED_WINDOW_DEACTIVATE = 2, XEMBED_REQUEST_FOCUS = 3,
XEMBED_FOCUS_IN = 4, XEMBED_FOCUS_OUT = 5, XEMBED_FOCUS_NEXT = 6, XEMBED_FOCUS_PREV = 7,
XEMBED_MODALITY_ON = 10, XEMBED_MODALITY_OFF = 11, XEMBED_REGISTER_ACCELERATOR = 12, XEMBED_UNREGISTER_ACCELERATOR = 13,
XEMBED_ACTIVATE_ACCELERATOR = 14
}
Functions
static Bool functor (Display *display, XEvent *event, XPointer arg)
static void sendXEmbedMessage (WId window, Display *display, long message, long detail=0, long data1=0, long data2=0)
static int x11ErrorHandler (Display *, XErrorEvent *)
static bool x11EventFilter (void *message, long *result)
static Time x11Time ()
static unsigned int XEmbedVersion ()
Variables
static XKeyEvent lastKeyEvent
static QCoreApplication::EventFilter oldX11EventFilter
const int XButtonPress = ButtonPress
const int XButtonRelease = ButtonRelease
static unsigned int XEMBED_VERSION = 0
Macro Definition Documentation
None
#define None 0
Definition at line 59 of file qx11embed_x11.cpp.
Referenced by QX11EmbedContainerPrivate::acceptClient(), QSpanData::adjustSpanMethods(), QX11EmbedContainerPrivate::checkGrab(), QTextStreamPrivate::getReal(), QMdiSubWindowPrivate::isResizeOperation(), QTransformedScreen::isTransformed(), QAbstractSpinBox::mousePressEvent(), QWSKeyboardHandler::processKeycode(), QAbstractSpinBoxPrivate::reset(), QSpanData::setup(), and QUrl::swap().
XK_ISO_Left_Tab
#define XK_ISO_Left_Tab 0xFE20
Definition at line 67 of file qx11embed_x11.cpp.
XK_LATIN1
#define XK_LATIN1
Definition at line 58 of file qx11embed_x11.cpp.
XK_MISCELLANY
#define XK_MISCELLANY
Definition at line 57 of file qx11embed_x11.cpp.
Enumeration Type Documentation
QX11EmbedAccelFlags
enum QX11EmbedAccelFlags
Enumerator
XEMBED_ACCELERATOR_OVERLOADED
Definition at line 346 of file qx11embed_x11.cpp.
{
     XEMBED_ACCELERATOR_OVERLOADED = (1 << 0)
 };
QX11EmbedAccelModifiers
enum QX11EmbedAccelModifiers
Enumerator
XEMBED_MODIFIER_SHIFT
XEMBED_MODIFIER_CONTROL
XEMBED_MODIFIER_ALT
XEMBED_MODIFIER_SUPER
XEMBED_MODIFIER_HYPER
Definition at line 338 of file qx11embed_x11.cpp.
{
     XEMBED_MODIFIER_SHIFT = (1 << 0),
     XEMBED_MODIFIER_CONTROL = (1 << 1),
     XEMBED_MODIFIER_ALT = (1 << 2),
     XEMBED_MODIFIER_SUPER = (1 << 3),
     XEMBED_MODIFIER_HYPER = (1 << 4)
 };
QX11EmbedFocusInDetail
enum QX11EmbedFocusInDetail
Enumerator
XEMBED_FOCUS_CURRENT
XEMBED_FOCUS_FIRST
XEMBED_FOCUS_LAST
Definition at line 323 of file qx11embed_x11.cpp.
{
     XEMBED_FOCUS_CURRENT = 0,
     XEMBED_FOCUS_FIRST = 1,
     XEMBED_FOCUS_LAST = 2
 };
QX11EmbedFocusInFlags
enum QX11EmbedFocusInFlags
Enumerator
XEMBED_FOCUS_OTHER
XEMBED_FOCUS_WRAPAROUND
Definition at line 329 of file qx11embed_x11.cpp.
{
     XEMBED_FOCUS_OTHER = (0 << 0),
     XEMBED_FOCUS_WRAPAROUND = (1 << 0)
 };
QX11EmbedInfoFlags
enum QX11EmbedInfoFlags
Enumerator
XEMBED_MAPPED
Definition at line 334 of file qx11embed_x11.cpp.
{
     XEMBED_MAPPED = (1 << 0)
 };
QX11EmbedMessageType
enum QX11EmbedMessageType
Enumerator
XEMBED_EMBEDDED_NOTIFY
XEMBED_WINDOW_ACTIVATE
XEMBED_WINDOW_DEACTIVATE
XEMBED_REQUEST_FOCUS
XEMBED_FOCUS_IN
XEMBED_FOCUS_OUT
XEMBED_FOCUS_NEXT
XEMBED_FOCUS_PREV
XEMBED_MODALITY_ON
XEMBED_MODALITY_OFF
XEMBED_REGISTER_ACCELERATOR
XEMBED_UNREGISTER_ACCELERATOR
XEMBED_ACTIVATE_ACCELERATOR
Definition at line 307 of file qx11embed_x11.cpp.
{
     XEMBED_EMBEDDED_NOTIFY = 0,
     XEMBED_WINDOW_ACTIVATE = 1,
     XEMBED_WINDOW_DEACTIVATE = 2,
     XEMBED_REQUEST_FOCUS = 3,
     XEMBED_FOCUS_IN = 4,
     XEMBED_FOCUS_OUT = 5,
     XEMBED_FOCUS_NEXT = 6,
     XEMBED_FOCUS_PREV = 7,
     XEMBED_MODALITY_ON = 10,
     XEMBED_MODALITY_OFF = 11,
     XEMBED_REGISTER_ACCELERATOR = 12,
     XEMBED_UNREGISTER_ACCELERATOR = 13,
     XEMBED_ACTIVATE_ACCELERATOR = 14
 };
Function Documentation
functor()
static Bool functor (Display * display, XEvent * event, XPointer arg) static
Definition at line 418 of file qx11embed_x11.cpp.
Referenced by QX11EmbedContainer::embedClient().
 {
     functorData *data = (functorData *) arg;
     if (!data->reparentedToRoot && event->type == ReparentNotify
         && event->xreparent.window == data->id
         && event->xreparent.parent == data->rootWindow) {
         data->reparentedToRoot = true;
         return true;
     }
     if (!data->clearedWmState
         && event->type == PropertyNotify
         && event->xproperty.window == data->id
         && event->xproperty.atom == ATOM(WM_STATE)) {
     if (event->xproperty.state == PropertyDelete) {
             data->clearedWmState = true;
             return true;
         }
     Atom ret;
     int format, status;
     unsigned char *retval;
     unsigned long nitems, after;
     status = XGetWindowProperty(display, data->id, ATOM(WM_STATE), 0, 2, False, ATOM(WM_STATE),
                     &ret, &format, &nitems, &after, &retval );
     if (status == Success && ret == ATOM(WM_STATE) && format == 32 && nitems > 0) {
             long state = *(long *)retval;
             XFree(retval);
             if (state == WithdrawnState) {
                 data->clearedWmState = true;
         return true;
             }
     }
     }
     return false;
 }
sendXEmbedMessage()
static void sendXEmbedMessage (WId window, Display * display, long message, long detail = 0, long data1 = 0, long data2 = 0) static
Definition at line 370 of file qx11embed_x11.cpp.
Referenced by QX11EmbedContainerPrivate::acceptClient(), QX11EmbedWidgetPrivate::checkActivateWindow(), QX11EmbedWidget::eventFilter(), QX11EmbedContainer::eventFilter(), and QX11EmbedContainer::x11Event().
 {
     XClientMessageEvent c;
     memset(&c, 0, sizeof(c));
     c.type = ClientMessage;
     c.message_type = ATOM(_XEMBED);
     c.format = 32;
     c.display = display;
     c.window = window;
     c.data.l[0] = x11Time();
     c.data.l[1] = message;
     c.data.l[2] = detail;
     c.data.l[3] = data1;
     c.data.l[4] = data2;
     XSendEvent(display, window, false, NoEventMask, (XEvent *) &c);
 }
x11ErrorHandler()
static int x11ErrorHandler (Display * , XErrorEvent *) static
Definition at line 351 of file qx11embed_x11.cpp.
Referenced by QX11EmbedContainer::QX11EmbedContainer(), and QX11EmbedWidget::QX11EmbedWidget().
 {
     return 0;
 }
x11EventFilter()
static bool x11EventFilter (void * message, long * result) static
Definition at line 398 of file qx11embed_x11.cpp.
Referenced by QApplication::isLeftToRight(), and QX11EmbedContainer::QX11EmbedContainer().
 {
     XEvent *event = reinterpret_cast<XEvent *>(message);
     if (event->type == XKeyPress || event->type == XKeyRelease)
     lastKeyEvent = event->xkey;
     if (oldX11EventFilter && oldX11EventFilter != &x11EventFilter)
     return oldX11EventFilter(message, result);
     else
     return false;
 }
x11Time()
static Time x11Time () static
Definition at line 358 of file qx11embed_x11.cpp.
Referenced by QX11EmbedContainerPrivate::acceptClient(), QX11EmbedContainer::eventFilter(), and sendXEmbedMessage().
 {
     return qt_x11Data->time;
 }
XEmbedVersion()
static unsigned int XEmbedVersion () static
Definition at line 364 of file qx11embed_x11.cpp.
Referenced by QX11EmbedContainerPrivate::acceptClient().
 {
     return 0;
 }
Variable Documentation
lastKeyEvent
XKeyEvent lastKeyEvent static
Definition at line 391 of file qx11embed_x11.cpp.
oldX11EventFilter
QCoreApplication::EventFilter oldX11EventFilter static
Definition at line 393 of file qx11embed_x11.cpp.
Referenced by x11EventFilter().
XButtonPress
const int XButtonPress = ButtonPress
Definition at line 291 of file qx11embed_x11.cpp.
Referenced by QX11EmbedContainer::x11Event().
XButtonRelease
const int XButtonRelease = ButtonRelease
Definition at line 292 of file qx11embed_x11.cpp.
Referenced by QX11EmbedContainer::x11Event().
XEMBED_VERSION
unsigned int XEMBED_VERSION = 0 static
Definition at line 305 of file qx11embed_x11.cpp.
Referenced by QX11EmbedContainer::hideEvent(), QX11EmbedWidget::QX11EmbedWidget(), and QX11EmbedContainer::showEvent().