Qt 4.8: /src/gui/image/qxbmhandler.cpp File Reference
qxbmhandler.cpp File Reference
#include <qplatformdefs.h>
#include "private/qxbmhandler_p.h"
#include <qimage.h>
#include <qiodevice.h>
#include <qvariant.h>
#include <stdio.h>
#include <ctype.h>
Functions
static int hex2byte (register char *p)
static bool read_xbm_body (QIODevice *device, int w, int h, QImage *outImage)
static bool read_xbm_header (QIODevice *device, int &w, int &h)
static bool read_xbm_image (QIODevice *device, QImage *outImage)
static bool write_xbm_image (const QImage &sourceImage, QIODevice *device, const QString &fileName)
Function Documentation
hex2byte()
static int hex2byte (register char * p) inline static
Definition at line 60 of file qxbmhandler.cpp.
Referenced by read_xbm_body().
 {
     return ((isdigit((uchar) *p) ? *p - '0' : toupper((uchar) *p) - 'A' + 10) << 4) |
            (isdigit((uchar) *(p+1)) ? *(p+1) - '0' : toupper((uchar) *(p+1)) - 'A' + 10);
 }
read_xbm_body()
static bool read_xbm_body (QIODevice * device, int w, int h, QImage * outImage) static
Definition at line 122 of file qxbmhandler.cpp.
Referenced by QXbmHandler::read(), and read_xbm_image().
 {
     const int buflen = 300;
     char buf[buflen + 1];
     qint64 readBytes = 0;
     // scan for database
     for (;;) {
         if ((readBytes = device->readLine(buf, buflen)) <= 0) {
             // end of file
             return false;
         }
         buf[readBytes] = '\0';
         if (QByteArray::fromRawData(buf, readBytes).contains("0x"))
             break;
     }
     if (outImage->size() != QSize(w, h) || outImage->format() != QImage::Format_MonoLSB) {
         *outImage = QImage(w, h, QImage::Format_MonoLSB);
         if (outImage->isNull())
             return false;
     }
     outImage->setColorCount(2);
     outImage->setColor(0, qRgb(255,255,255));        // white
     outImage->setColor(1, qRgb(0,0,0));                // black
     int           x = 0, y = 0;
     uchar *b = outImage->scanLine(0);
     char  *p = buf + QByteArray::fromRawData(buf, readBytes).indexOf("0x");
     w = (w+7)/8;                                // byte width
     while (y < h) {                                // for all encoded bytes...
         if (p) {                                // p = "0x.."
             *b++ = hex2byte(p+2);
             p += 2;
             if (++x == w && ++y < h) {
                 b = outImage->scanLine(y);
                 x = 0;
             }
             p = strstr(p, "0x");
         } else {                                // read another line
             if ((readBytes = device->readLine(buf,buflen)) <= 0)        // EOF ==> truncated image
                 break;
             p = buf + QByteArray::fromRawData(buf, readBytes).indexOf("0x");
         }
     }
     return true;
 }
read_xbm_header()
static bool read_xbm_header (QIODevice * device, int & w, int & h) static
Definition at line 66 of file qxbmhandler.cpp.
Referenced by read_xbm_image(), and QXbmHandler::readHeader().
 {
     const int buflen = 300;
     const int maxlen = 4096;
     char buf[buflen + 1];
     QRegExp r1(QLatin1String("^#define[ \t]+[a-zA-Z0-9._]+[ \t]+"));
     QRegExp r2(QLatin1String("[0-9]+"));
     qint64 readBytes = 0;
     qint64 totalReadBytes = 0;
     buf[0] = '\0';
     // skip initial comment, if any
     while (buf[0] != '#') {
         readBytes = device->readLine(buf, buflen);
         // if readBytes >= buflen, it's very probably not a C file
         if (readBytes <= 0 || readBytes >= buflen -1)
             return false;
         // limit xbm headers to the first 4k in the file to prevent
         // excessive reads on non-xbm files
         totalReadBytes += readBytes;
         if (totalReadBytes >= maxlen)
             return false;
     }
     buf[readBytes - 1] = '\0';
     QString sbuf;
     sbuf = QString::fromLatin1(buf);
     // "#define .._width <num>"
     if (r1.indexIn(sbuf) == 0 &&
          r2.indexIn(sbuf, r1.matchedLength()) == r1.matchedLength())
         w = QByteArray(&buf[r1.matchedLength()]).trimmed().toInt();
     // "#define .._height <num>"
     readBytes = device->readLine(buf, buflen);
     if (readBytes <= 0)
     return false;
     buf[readBytes - 1] = '\0';
     sbuf = QString::fromLatin1(buf);
     if (r1.indexIn(sbuf) == 0 &&
          r2.indexIn(sbuf, r1.matchedLength()) == r1.matchedLength())
         h = QByteArray(&buf[r1.matchedLength()]).trimmed().toInt();
     // format error
     if (w <= 0 || w > 32767 || h <= 0 || h > 32767)
         return false;
     return true;
 }
read_xbm_image()
static bool read_xbm_image (QIODevice * device, QImage * outImage) static
Definition at line 175 of file qxbmhandler.cpp.
Referenced by QXbmHandler::canRead().
 {
     int w = 0, h = 0;
     if (!read_xbm_header(device, w, h))
         return false;
     return read_xbm_body(device, w, h, outImage);
 }
write_xbm_image()
static bool write_xbm_image (const QImage & sourceImage, QIODevice * device, const QString & fileName) static
Definition at line 183 of file qxbmhandler.cpp.
Referenced by QXbmHandler::write().
 {
     QImage image = sourceImage;
     int        w = image.width();
     int        h = image.height();
     int        i;
     QString    s = fileName; // get file base name
     int        msize = s.length() + 100;
     char *buf = new char[msize];
     qsnprintf(buf, msize, "#define %s_width %d\n", s.toAscii().data(), w);
     device->write(buf, qstrlen(buf));
     qsnprintf(buf, msize, "#define %s_height %d\n", s.toAscii().data(), h);
     device->write(buf, qstrlen(buf));
     qsnprintf(buf, msize, "static char %s_bits[] = {\n ", s.toAscii().data());
     device->write(buf, qstrlen(buf));
     if (image.format() != QImage::Format_MonoLSB)
         image = image.convertToFormat(QImage::Format_MonoLSB);
     bool invert = qGray(image.color(0)) < qGray(image.color(1));
     char hexrep[16];
     for (i=0; i<10; i++)
     hexrep[i] = '0' + i;
     for (i=10; i<16; i++)
     hexrep[i] = 'a' -10 + i;
     if (invert) {
     char t;
     for (i=0; i<8; i++) {
         t = hexrep[15-i];
         hexrep[15-i] = hexrep[i];
         hexrep[i] = t;
     }
     }
     int bcnt = 0;
     register char *p = buf;
     int bpl = (w+7)/8;
     for (int y = 0; y < h; ++y) {
         uchar *b = image.scanLine(y);
         for (i = 0; i < bpl; ++i) {
             *p++ = '0'; *p++ = 'x';
             *p++ = hexrep[*b >> 4];
             *p++ = hexrep[*b++ & 0xf];
             if (i < bpl - 1 || y < h - 1) {
                 *p++ = ',';
                 if (++bcnt > 14) {
                     *p++ = '\n';
                     *p++ = ' ';
                     *p   = '\0';
                     if ((int)qstrlen(buf) != device->write(buf, qstrlen(buf))) {
                         delete [] buf;
                         return false;
                     }
                     p = buf;
                     bcnt = 0;
                 }
             }
         }
     }
 #if defined(_MSC_VER) && _MSC_VER >= 1400
     strcpy_s(p, sizeof(" };\n"), " };\n");
 #else
     strcpy(p, " };\n");
 #endif
     if ((int)qstrlen(buf) != device->write(buf, qstrlen(buf))) {
         delete [] buf;
         return false;
     }
     delete [] buf;
     return true;
 }