Qt 4.8: /src/plugins/platforms/xcb/qxcbwindow.cpp File Reference
qxcbwindow.cpp File Reference
#include "qxcbwindow.h"
#include <QtDebug>
#include "qxcbconnection.h"
#include "qxcbscreen.h"
#include <xcb/xcb_icccm.h>
#include <private/qapplication_p.h>
#include <private/qwindowsurface_p.h>
#include <QtGui/QWindowSystemInterface>
#include <stdio.h>
Classes
struct QtMWMHints
Macros
#define class class_name
Enumerations
enum {
MWM_HINTS_FUNCTIONS = (1L << 0), MWM_FUNC_ALL = (1L << 0), MWM_FUNC_RESIZE = (1L << 1), MWM_FUNC_MOVE = (1L << 2),
MWM_FUNC_MINIMIZE = (1L << 3), MWM_FUNC_MAXIMIZE = (1L << 4), MWM_FUNC_CLOSE = (1L << 5), MWM_HINTS_DECORATIONS = (1L << 1),
MWM_DECOR_ALL = (1L << 0), MWM_DECOR_BORDER = (1L << 1), MWM_DECOR_RESIZEH = (1L << 2), MWM_DECOR_TITLE = (1L << 3),
MWM_DECOR_MENU = (1L << 4), MWM_DECOR_MINIMIZE = (1L << 5), MWM_DECOR_MAXIMIZE = (1L << 6), MWM_HINTS_INPUT_MODE = (1L << 2),
MWM_INPUT_MODELESS = 0L, MWM_INPUT_PRIMARY_APPLICATION_MODAL = 1L, MWM_INPUT_FULL_APPLICATION_MODAL = 3L
}
Functions
static bool isTransient (const QWidget *w)
static Qt::MouseButton translateMouseButton (xcb_button_t s)
static Qt::MouseButtons translateMouseButtons (int s)
Macro Definition Documentation
class
#define class class_name
Definition at line 53 of file qxcbwindow.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MWM_HINTS_FUNCTIONS
MWM_FUNC_ALL
MWM_FUNC_RESIZE
MWM_FUNC_MOVE
MWM_FUNC_MINIMIZE
MWM_FUNC_MAXIMIZE
MWM_FUNC_CLOSE
MWM_HINTS_DECORATIONS
MWM_DECOR_ALL
MWM_DECOR_BORDER
MWM_DECOR_RESIZEH
MWM_DECOR_TITLE
MWM_DECOR_MENU
MWM_DECOR_MINIMIZE
MWM_DECOR_MAXIMIZE
MWM_HINTS_INPUT_MODE
MWM_INPUT_MODELESS
MWM_INPUT_PRIMARY_APPLICATION_MODAL
MWM_INPUT_FULL_APPLICATION_MODAL
Definition at line 308 of file qxcbwindow.cpp.
      {
     MWM_HINTS_FUNCTIONS   = (1L << 0),
     MWM_FUNC_ALL      = (1L << 0),
     MWM_FUNC_RESIZE   = (1L << 1),
     MWM_FUNC_MOVE     = (1L << 2),
     MWM_FUNC_MINIMIZE = (1L << 3),
     MWM_FUNC_MAXIMIZE = (1L << 4),
     MWM_FUNC_CLOSE    = (1L << 5),
     MWM_HINTS_DECORATIONS = (1L << 1),
     MWM_DECOR_ALL      = (1L << 0),
     MWM_DECOR_BORDER   = (1L << 1),
     MWM_DECOR_RESIZEH  = (1L << 2),
     MWM_DECOR_TITLE    = (1L << 3),
     MWM_DECOR_MENU     = (1L << 4),
     MWM_DECOR_MINIMIZE = (1L << 5),
     MWM_DECOR_MAXIMIZE = (1L << 6),
     MWM_HINTS_INPUT_MODE = (1L << 2),
     MWM_INPUT_MODELESS                  = 0L,
     MWM_INPUT_PRIMARY_APPLICATION_MODAL = 1L,
     MWM_INPUT_FULL_APPLICATION_MODAL    = 3L
 };
Function Documentation
isTransient()
static bool isTransient (const QWidget * w) inline static
Definition at line 101 of file qxcbwindow.cpp.
Referenced by QXcbWindow::QXcbWindow().
 {
     return ((w->windowType() == Qt::Dialog
              || w->windowType() == Qt::Sheet
              || w->windowType() == Qt::Tool
              || w->windowType() == Qt::SplashScreen
              || w->windowType() == Qt::ToolTip
              || w->windowType() == Qt::Drawer
              || w->windowType() == Qt::Popup)
             && !w->testAttribute(Qt::WA_X11BypassTransientForHint));
 }
translateMouseButton()
static Qt::MouseButton translateMouseButton (xcb_button_t s) static
Definition at line 623 of file qxcbwindow.cpp.
Referenced by QXcbWindow::handleMouseEvent().
 {
     switch (s) {
     case 1:
         return Qt::LeftButton;
     case 2:
         return Qt::MidButton;
     case 3:
         return Qt::RightButton;
     default:
         return Qt::NoButton;
     }
 }
translateMouseButtons()
static Qt::MouseButtons translateMouseButtons (int s) static
Definition at line 611 of file qxcbwindow.cpp.
Referenced by QXcbWindow::handleMouseEvent().
 {
     Qt::MouseButtons ret = 0;
     if (s & XCB_BUTTON_MASK_1)
         ret |= Qt::LeftButton;
     if (s & XCB_BUTTON_MASK_2)
         ret |= Qt::MidButton;
     if (s & XCB_BUTTON_MASK_3)
         ret |= Qt::RightButton;
     return ret;
 }