Qt 4.8: /src/plugins/platforms/xlib/qxlibscreen.cpp File Reference
qxlibscreen.cpp File Reference
#include "qxlibscreen.h"
#include <X11/extensions/Xfixes.h>
#include "qxlibcursor.h"
#include "qxlibwindow.h"
#include "qxlibkeyboard.h"
#include "qxlibstatic.h"
#include "qxlibclipboard.h"
#include "qxlibdisplay.h"
#include <QtCore/QDebug>
#include <QtCore/QSocketNotifier>
#include <QtCore/QElapsedTimer>
#include <private/qapplication_p.h>
Functions
static Bool checkForClipboardEvents (Display *, XEvent *e, XPointer)
static int qt_x_errhandler (Display *dpy, XErrorEvent *err)
Variables
static int(* original_x_errhandler)(Display *dpy, XErrorEvent *)
static bool seen_badwindow
Function Documentation
checkForClipboardEvents()
static Bool checkForClipboardEvents (Display * , XEvent * e, XPointer) static
Definition at line 362 of file qxlibscreen.cpp.
Referenced by QXlibScreen::waitForClipboardEvent().
 {
     Atom clipboard = QXlibStatic::atom(QXlibStatic::CLIPBOARD);
     return ((e->type == SelectionRequest && (e->xselectionrequest.selection == XA_PRIMARY
                                              || e->xselectionrequest.selection == clipboard))
             || (e->type == SelectionClear && (e->xselectionclear.selection == XA_PRIMARY
                                               || e->xselectionclear.selection == clipboard)));
 }
qt_x_errhandler()
static int qt_x_errhandler (Display * dpy, XErrorEvent * err) static
defined(QT_NO_XINPUT)
Definition at line 64 of file qxlibscreen.cpp.
Referenced by QXlibScreen::QXlibScreen().
 {
 qDebug() << "qt_x_errhandler" << err->error_code;
     switch (err->error_code) {
     case BadAtom:
 #if 0
         if (err->request_code == 20 /* X_GetProperty */
             && (err->resourceid == XA_RESOURCE_MANAGER
                 || err->resourceid == XA_RGB_DEFAULT_MAP
                 || err->resourceid == ATOM(_NET_SUPPORTED)
                 || err->resourceid == ATOM(_NET_SUPPORTING_WM_CHECK)
                 || err->resourceid == ATOM(KDE_FULL_SESSION)
                 || err->resourceid == ATOM(KWIN_RUNNING)
                 || err->resourceid == ATOM(XdndProxy)
                 || err->resourceid == ATOM(XdndAware))
             ) {
             // Perhaps we're running under SECURITY reduction? :/
             return 0;
         }
 #endif
         qDebug() << "BadAtom";
         break;
     case BadWindow:
         if (err->request_code == 2 /* X_ChangeWindowAttributes */
             || err->request_code == 38 /* X_QueryPointer */) {
             for (int i = 0; i < ScreenCount(dpy); ++i) {
                 if (err->resourceid == RootWindow(dpy, i)) {
                     // Perhaps we're running under SECURITY reduction? :/
                     return 0;
                 }
             }
         }
         seen_badwindow = true;
         if (err->request_code == 25 /* X_SendEvent */) {
             for (int i = 0; i < ScreenCount(dpy); ++i) {
                 if (err->resourceid == RootWindow(dpy, i)) {
                     // Perhaps we're running under SECURITY reduction? :/
                     return 0;
                 }
             }
 #if 0
             if (X11->xdndHandleBadwindow()) {
                 qDebug("xdndHandleBadwindow returned true");
                 return 0;
             }
 #endif
         }
 #if 0
         if (X11->ignore_badwindow)
             return 0;
 #endif
         break;
     case BadMatch:
         if (err->request_code == 42 /* X_SetInputFocus */)
             return 0;
         break;
     default:
 #if 0
         if (err->request_code == X11->xinput_major
             && err->error_code == (X11->xinput_errorbase + XI_BadDevice)
             && err->minor_code == 3 /* X_OpenDevice */) {
             return 0;
         }
 #endif
         break;
     }
     char errstr[256];
     XGetErrorText( dpy, err->error_code, errstr, 256 );
     char buffer[256];
     char request_str[256];
     qsnprintf(buffer, 256, "%d", err->request_code);
     XGetErrorDatabaseText(dpy, "XRequest", buffer, "", request_str, 256);
     if (err->request_code < 128) {
         // X error for a normal protocol request
         qWarning( "X Error: %s %d\n"
                   "  Major opcode: %d (%s)\n"
                   "  Resource id:  0x%lx",
                   errstr, err->error_code,
                   err->request_code,
                   request_str,
                   err->resourceid );
     } else {
         // X error for an extension request
         const char *extensionName = 0;
 #if 0
         if (err->request_code == X11->xrender_major)
             extensionName = "RENDER";
         else if (err->request_code == X11->xrandr_major)
             extensionName = "RANDR";
         else if (err->request_code == X11->xinput_major)
             extensionName = "XInputExtension";
         else if (err->request_code == X11->mitshm_major)
             extensionName = "MIT-SHM";
 #endif
         char minor_str[256];
         if (extensionName) {
             qsnprintf(buffer, 256, "%s.%d", extensionName, err->minor_code);
             XGetErrorDatabaseText(dpy, "XRequest", buffer, "", minor_str, 256);
         } else {
             extensionName = "Uknown extension";
             qsnprintf(minor_str, 256, "Unknown request");
         }
         qWarning( "X Error: %s %d\n"
                   "  Extension:    %d (%s)\n"
                   "  Minor opcode: %d (%s)\n"
                   "  Resource id:  0x%lx",
                   errstr, err->error_code,
                   err->request_code,
                   extensionName,
                   err->minor_code,
                   minor_str,
                   err->resourceid );
     }
     // ### we really should distinguish between severe, non-severe and
     // ### application specific errors
     return 0;
 }
Variable Documentation
original_x_errhandler
int(* original_x_errhandler) (Display *dpy, XErrorEvent *) static
Definition at line 61 of file qxlibscreen.cpp.
Referenced by QXlibScreen::QXlibScreen().
seen_badwindow
bool seen_badwindow static
Definition at line 62 of file qxlibscreen.cpp.
Referenced by qt_x_errhandler().