Qt 4.8: /src/plugins/platforms/xlib/qxlibwindowsurface.cpp File Reference
qxlibwindowsurface.cpp File Reference
#include "qxlibwindowsurface.h"
#include "qxlibintegration.h"
#include <QtCore/qdebug.h>
#include <QWindowSystemInterface>
#include "qxlibwindow.h"
#include "qxlibscreen.h"
#include "qxlibdisplay.h"
#include "qpainter.h"
#include <sys/ipc.h>
#include <sys/shm.h>
#include <X11/extensions/XShm.h>
Classes
struct QXlibShmImageInfo
Functions
void qt_scrollRectInImage (QImage &img, const QRect &rect, const QPoint &offset)
Function Documentation
qt_scrollRectInImage()
void qt_scrollRectInImage (QImage & img, const QRect & rect, const QPoint & offset)
Definition at line 345 of file qwindowsurface.cpp.
Referenced by QXlibWindowSurface::flush(), QMeeGoLivePixmapData::scroll(), and QXlibWindowSurface::scroll().
 {
     // make sure we don't detach
     uchar *mem = const_cast<uchar*>(const_cast<const QImage &>(img).bits());
     int lineskip = img.bytesPerLine();
     int depth = img.depth() >> 3;
     const QRect imageRect(0, 0, img.width(), img.height());
     const QRect r = rect & imageRect & imageRect.translated(-offset);
     const QPoint p = rect.topLeft() + offset;
     if (r.isEmpty())
         return;
     const uchar *src;
     uchar *dest;
     if (r.top() < p.y()) {
         src = mem + r.bottom() * lineskip + r.left() * depth;
         dest = mem + (p.y() + r.height() - 1) * lineskip + p.x() * depth;
         lineskip = -lineskip;
     } else {
         src = mem + r.top() * lineskip + r.left() * depth;
         dest = mem + p.y() * lineskip + p.x() * depth;
     }
     const int w = r.width();
     int h = r.height();
     const int bytes = w * depth;
     // overlapping segments?
     if (offset.y() == 0 && qAbs(offset.x()) < w) {
         do {
             ::memmove(dest, src, bytes);
             dest += lineskip;
             src += lineskip;
         } while (--h);
     } else {
         do {
             ::memcpy(dest, src, bytes);
             dest += lineskip;
             src += lineskip;
         } while (--h);
     }
 }