Qt 4.8: /src/xml/sax/qxml.cpp File Reference
qxml.cpp File Reference
#include "qxml.h"
#include "qtextcodec.h"
#include "qbuffer.h"
#include "qregexp.h"
#include "qmap.h"
#include "qhash.h"
#include "qstack.h"
#include <qdebug.h>
Classes
class QXmlAttributesPrivate
class QXmlDefaultHandlerPrivate
class QXmlInputSourcePrivate
class QXmlLocatorPrivate
class QXmlNamespaceSupportPrivate
class QXmlParseExceptionPrivate
class QXmlSimpleReaderLocator
class QXmlSimpleReaderPrivate
struct QXmlSimpleReaderPrivate::ExternEntity
struct QXmlSimpleReaderPrivate::ExternParameterEntity
struct QXmlSimpleReaderPrivate::ParseState
struct QXmlSimpleReaderPrivate::XmlRef
Macros
#define XMLERR_EDECLORSDDECLEXPECTED QT_TRANSLATE_NOOP("QXml", "encoding declaration or standalone declaration expected while reading the XML declaration")
#define XMLERR_ERRORBYCONSUMER QT_TRANSLATE_NOOP("QXml", "error triggered by consumer")
#define XMLERR_ERRORINTEXTDECL QT_TRANSLATE_NOOP("QXml", "error in the text declaration of an external entity")
#define XMLERR_ERRORPARSINGCOMMENT QT_TRANSLATE_NOOP("QXml", "error occurred while parsing comment")
#define XMLERR_ERRORPARSINGCONTENT QT_TRANSLATE_NOOP("QXml", "error occurred while parsing content")
#define XMLERR_ERRORPARSINGDOCTYPE QT_TRANSLATE_NOOP("QXml", "error occurred while parsing document type definition")
#define XMLERR_ERRORPARSINGELEMENT QT_TRANSLATE_NOOP("QXml", "error occurred while parsing element")
#define XMLERR_ERRORPARSINGREFERENCE QT_TRANSLATE_NOOP("QXml", "error occurred while parsing reference")
#define XMLERR_EXTERNALGENERALENTITYINAV QT_TRANSLATE_NOOP("QXml", "external parsed general entity reference not allowed in attribute value")
#define XMLERR_EXTERNALGENERALENTITYINDTD QT_TRANSLATE_NOOP("QXml", "external parsed general entity reference not allowed in DTD")
#define XMLERR_INTERNALGENERALENTITYINDTD QT_TRANSLATE_NOOP("QXml", "internal general entity reference not allowed in DTD")
#define XMLERR_INVALIDNAMEFORPI QT_TRANSLATE_NOOP("QXml", "invalid name for processing instruction")
#define XMLERR_LETTEREXPECTED QT_TRANSLATE_NOOP("QXml", "letter is expected")
#define XMLERR_MORETHANONEDOCTYPE QT_TRANSLATE_NOOP("QXml", "more than one document type definition")
#define XMLERR_OK QT_TRANSLATE_NOOP("QXml", "no error occurred")
#define XMLERR_RECURSIVEENTITIES QT_TRANSLATE_NOOP("QXml", "recursive entities")
#define XMLERR_SDDECLEXPECTED QT_TRANSLATE_NOOP("QXml", "standalone declaration expected while reading the XML declaration")
#define XMLERR_TAGMISMATCH QT_TRANSLATE_NOOP("QXml", "tag mismatch")
#define XMLERR_UNEXPECTEDCHARACTER QT_TRANSLATE_NOOP("QXml", "unexpected character")
#define XMLERR_UNEXPECTEDEOF QT_TRANSLATE_NOOP("QXml", "unexpected end of file")
#define XMLERR_UNPARSEDENTITYREFERENCE QT_TRANSLATE_NOOP("QXml", "unparsed entity reference in wrong context")
#define XMLERR_VERSIONEXPECTED QT_TRANSLATE_NOOP("QXml", "version expected while reading the XML declaration")
#define XMLERR_WRONGVALUEFORSDECL QT_TRANSLATE_NOOP("QXml", "wrong value for standalone declaration")
Typedefs
typedef QMap< QString, QString > NamespaceMap
Enumerations
enum NameChar {
NameBeginning, NameNotBeginning, NotName, NameBeginning,
NameNotBeginning, NotName
}
Functions
static NameChar determineNameChar (QChar ch)
static QString extractEncodingDecl (const QString &text, bool *needMoreText)
static NameChar fastDetermineNameChar (QChar ch)
static bool is_S (QChar ch)
static bool stripTextDecl (QString &str)
static void updateValue (QString &value, const QChar *array, int &arrayPos, int &valueLen)
Variables
static const char Begi = (char)NameBeginning
static const signed char charLookupTable [256]
static const signed char cltAmp = 2
static const signed char cltCB = 9
static const signed char cltDash = 8
static const signed char cltDq = 12
static const signed char cltEm = 7
static const signed char cltEq = 11
static const signed char cltGt = 3
static const signed char cltLt = 4
static const signed char cltOB = 10
static const signed char cltPer = 1
static const signed char cltQm = 6
static const signed char cltSlash = 5
static const signed char cltSq = 13
static const signed char cltUnknown = 14
static const signed char cltWS = 0
static const char nameCharTable [128]
static const char NotN = (char)NotName
static const char NtBg = (char)NameNotBeginning
bool qt_xml_skipped_entity_in_content
Macro Definition Documentation
XMLERR_EDECLORSDDECLEXPECTED
#define XMLERR_EDECLORSDDECLEXPECTED QT_TRANSLATE_NOOP("QXml", "encoding declaration or standalone declaration expected while reading the XML declaration")
Definition at line 70 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parsePI().
XMLERR_ERRORBYCONSUMER
#define XMLERR_ERRORBYCONSUMER QT_TRANSLATE_NOOP("QXml", "error triggered by consumer")
Definition at line 60 of file qxml.cpp.
Referenced by QXmlDefaultHandler::errorString().
XMLERR_ERRORINTEXTDECL
#define XMLERR_ERRORINTEXTDECL QT_TRANSLATE_NOOP("QXml", "error in the text declaration of an external entity")
Definition at line 81 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parsePEReference(), and QXmlSimpleReaderPrivate::processReference().
XMLERR_ERRORPARSINGCOMMENT
#define XMLERR_ERRORPARSINGCOMMENT QT_TRANSLATE_NOOP("QXml", "error occurred while parsing comment")
Definition at line 74 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parseComment().
XMLERR_ERRORPARSINGCONTENT
#define XMLERR_ERRORPARSINGCONTENT QT_TRANSLATE_NOOP("QXml", "error occurred while parsing content")
Definition at line 65 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parseContent().
XMLERR_ERRORPARSINGDOCTYPE
#define XMLERR_ERRORPARSINGDOCTYPE QT_TRANSLATE_NOOP("QXml", "error occurred while parsing document type definition")
Definition at line 72 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parseDoctype().
XMLERR_ERRORPARSINGELEMENT
#define XMLERR_ERRORPARSINGELEMENT QT_TRANSLATE_NOOP("QXml", "error occurred while parsing element")
Definition at line 63 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parseElement(), and QXmlSimpleReaderPrivate::parseProlog().
XMLERR_ERRORPARSINGREFERENCE
#define XMLERR_ERRORPARSINGREFERENCE QT_TRANSLATE_NOOP("QXml", "error occurred while parsing reference")
Definition at line 75 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parseReference().
XMLERR_EXTERNALGENERALENTITYINAV
#define XMLERR_EXTERNALGENERALENTITYINAV QT_TRANSLATE_NOOP("QXml", "external parsed general entity reference not allowed in attribute value")
Definition at line 77 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::processReference().
XMLERR_EXTERNALGENERALENTITYINDTD
#define XMLERR_EXTERNALGENERALENTITYINDTD QT_TRANSLATE_NOOP("QXml", "external parsed general entity reference not allowed in DTD")
Definition at line 78 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::processReference().
XMLERR_INTERNALGENERALENTITYINDTD
#define XMLERR_INTERNALGENERALENTITYINDTD QT_TRANSLATE_NOOP("QXml", "internal general entity reference not allowed in DTD")
Definition at line 76 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::processReference().
XMLERR_INVALIDNAMEFORPI
#define XMLERR_INVALIDNAMEFORPI QT_TRANSLATE_NOOP("QXml", "invalid name for processing instruction")
Definition at line 67 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parsePI().
XMLERR_LETTEREXPECTED
#define XMLERR_LETTEREXPECTED QT_TRANSLATE_NOOP("QXml", "letter is expected")
Definition at line 73 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parseAttlistDecl(), QXmlSimpleReaderPrivate::parseAttType(), QXmlSimpleReaderPrivate::parseEntityDecl(), QXmlSimpleReaderPrivate::parseEntityValue(), QXmlSimpleReaderPrivate::parseMarkupdecl(), QXmlSimpleReaderPrivate::parseName(), QXmlSimpleReaderPrivate::parseNmtoken(), and QXmlSimpleReaderPrivate::parsePEReference().
XMLERR_MORETHANONEDOCTYPE
#define XMLERR_MORETHANONEDOCTYPE QT_TRANSLATE_NOOP("QXml", "more than one document type definition")
Definition at line 62 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parseProlog().
XMLERR_OK
#define XMLERR_OK QT_TRANSLATE_NOOP("QXml", "no error occurred")
Definition at line 59 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::reportParseError().
XMLERR_RECURSIVEENTITIES
#define XMLERR_RECURSIVEENTITIES QT_TRANSLATE_NOOP("QXml", "recursive entities")
Definition at line 80 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::insertXmlRef().
XMLERR_SDDECLEXPECTED
#define XMLERR_SDDECLEXPECTED QT_TRANSLATE_NOOP("QXml", "standalone declaration expected while reading the XML declaration")
Definition at line 71 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parsePI().
XMLERR_TAGMISMATCH
#define XMLERR_TAGMISMATCH QT_TRANSLATE_NOOP("QXml", "tag mismatch")
Definition at line 64 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parseElement(), and QXmlSimpleReaderPrivate::processElementETagBegin2().
XMLERR_UNEXPECTEDCHARACTER
#define XMLERR_UNEXPECTEDCHARACTER QT_TRANSLATE_NOOP("QXml", "unexpected character")
Definition at line 66 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parseAttribute(), QXmlSimpleReaderPrivate::parseAttValue(), QXmlSimpleReaderPrivate::parseChoiceSeq(), QXmlSimpleReaderPrivate::parseElementDecl(), QXmlSimpleReaderPrivate::parseExternalID(), QXmlSimpleReaderPrivate::parseMisc(), QXmlSimpleReaderPrivate::parseNotationDecl(), QXmlSimpleReaderPrivate::parsePI(), and QXmlSimpleReaderPrivate::parseString().
XMLERR_UNEXPECTEDEOF
#define XMLERR_UNEXPECTEDEOF QT_TRANSLATE_NOOP("QXml", "unexpected end of file")
Definition at line 61 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parseBeginOrContinue(), and QXmlSimpleReaderPrivate::unexpectedEof().
XMLERR_UNPARSEDENTITYREFERENCE
#define XMLERR_UNPARSEDENTITYREFERENCE QT_TRANSLATE_NOOP("QXml", "unparsed entity reference in wrong context")
Definition at line 79 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::processReference().
XMLERR_VERSIONEXPECTED
#define XMLERR_VERSIONEXPECTED QT_TRANSLATE_NOOP("QXml", "version expected while reading the XML declaration")
Definition at line 68 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parsePI().
XMLERR_WRONGVALUEFORSDECL
#define XMLERR_WRONGVALUEFORSDECL QT_TRANSLATE_NOOP("QXml", "wrong value for standalone declaration")
Definition at line 69 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parsePI().
Typedef Documentation
NamespaceMap
typedef QMap<QString, QString> NamespaceMap
Definition at line 721 of file qxml.cpp.
Enumeration Type Documentation
NameChar
enum NameChar
Enumerator
NameBeginning
NameNotBeginning
NotName
NameBeginning
NameNotBeginning
NotName
Definition at line 3386 of file qxml.cpp.
 { NameBeginning, NameNotBeginning, NotName };
Function Documentation
determineNameChar()
static NameChar determineNameChar (QChar ch) static
Definition at line 3437 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parseAttribute(), QXmlSimpleReaderPrivate::parseNmtoken(), and QXmlSimpleReaderPrivate::parsePI().
 {
     return fastDetermineNameChar(ch);
 }
extractEncodingDecl()
static QString extractEncodingDecl (const QString & text, bool * needMoreText) static
Definition at line 1596 of file qxml.cpp.
Referenced by QXmlInputSource::fromRawData().
 {
     *needMoreText = false;
     int l = text.length();
     QString snip = QString::fromLatin1("<?xml").left(l);
     if (l > 0 && !text.startsWith(snip))
         return QString();
     int endPos = text.indexOf(QLatin1Char('>'));
     if (endPos == -1) {
         *needMoreText = l < 255; // we won't look forever
         return QString();
     }
     int pos = text.indexOf(QLatin1String("encoding"));
     if (pos == -1 || pos >= endPos)
         return QString();
     while (pos < endPos) {
         ushort uc = text.at(pos).unicode();
         if (uc == '\'' || uc == '"')
             break;
         ++pos;
     }
     if (pos == endPos)
         return QString();
     QString encoding;
     ++pos;
     while (pos < endPos) {
         ushort uc = text.at(pos).unicode();
         if (uc == '\'' || uc == '"')
             break;
         encoding.append(uc);
         ++pos;
     }
     return encoding;
 }
fastDetermineNameChar()
static NameChar fastDetermineNameChar (QChar ch) inline static
Definition at line 3420 of file qxml.cpp.
Referenced by determineNameChar(), QXmlSimpleReaderPrivate::parseElement(), and QXmlSimpleReaderPrivate::parseName().
 {
     ushort uc = ch.unicode();
     if (!(uc & ~0x7f)) // uc < 128
         return (NameChar)nameCharTable[uc];
     QChar::Category cat = ch.category();
     // ### some these categories might be slightly wrong
     if ((cat >= QChar::Letter_Uppercase && cat <= QChar::Letter_Other)
         || cat == QChar::Number_Letter)
         return NameBeginning;
     if ((cat >= QChar::Number_DecimalDigit && cat <= QChar::Number_Other)
                 || (cat >= QChar::Mark_NonSpacing && cat <= QChar::Mark_Enclosing))
         return NameNotBeginning;
     return NotName;
 }
is_S()
static bool is_S (QChar ch) inline static
Definition at line 3380 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::eat_ws(), QXmlSimpleReaderPrivate::parseAttlistDecl(), QXmlSimpleReaderPrivate::parseAttType(), QXmlSimpleReaderPrivate::parseChoiceSeq(), QXmlSimpleReaderPrivate::parseDoctype(), QXmlSimpleReaderPrivate::parseElement(), QXmlSimpleReaderPrivate::parseElementDecl(), QXmlSimpleReaderPrivate::parseEntityDecl(), QXmlSimpleReaderPrivate::parseExternalID(), QXmlSimpleReaderPrivate::parseMisc(), QXmlSimpleReaderPrivate::parseNotationDecl(), QXmlSimpleReaderPrivate::parsePI(), and QXmlSimpleReaderPrivate::parseProlog().
 {
     ushort uc = ch.unicode();
     return (uc == ' ' || uc == '\t' || uc == '\n' || uc == '\r');
 }
stripTextDecl()
static bool stripTextDecl (QString & str) static
Definition at line 189 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parsePEReference(), and QXmlSimpleReaderPrivate::processReference().
 {
     QString textDeclStart(QLatin1String("<?xml"));
     if (str.startsWith(textDeclStart)) {
         QRegExp textDecl(QString::fromLatin1(
             "^<\\?xml\\s+"
             "(version\\s*=\\s*((['\"])[-a-zA-Z0-9_.:]+\\3))?"
             "\\s*"
             "(encoding\\s*=\\s*((['\"])[A-Za-z][-a-zA-Z0-9_.]*\\6))?"
             "\\s*\\?>"
        ));
         QString strTmp = str.replace(textDecl, QLatin1String(""));
         if (strTmp.length() != str.length())
             return false; // external entity has wrong TextDecl
         str = strTmp;
     }
     return true;
 }
updateValue()
static void updateValue (QString & value, const QChar * array, int & arrayPos, int & valueLen) inline static
Definition at line 8481 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::name(), QXmlSimpleReaderPrivate::nameAddC(), QXmlSimpleReaderPrivate::ref(), QXmlSimpleReaderPrivate::refAddC(), QXmlSimpleReaderPrivate::string(), and QXmlSimpleReaderPrivate::stringAddC().
 {
     value.resize(valueLen + arrayPos);
     memcpy(value.data() + valueLen, array, arrayPos * sizeof(QChar));
     valueLen += arrayPos;
     arrayPos = 0;
 }
Variable Documentation
Begi
const char Begi = (char)NameBeginning static
Definition at line 3388 of file qxml.cpp.
charLookupTable
const signed char charLookupTable[256] static
Definition at line 107 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parseContent().
cltAmp
const signed char cltAmp = 2 static
Definition at line 88 of file qxml.cpp.
cltCB
const signed char cltCB = 9 static
Definition at line 95 of file qxml.cpp.
cltDash
const signed char cltDash = 8 static
Definition at line 94 of file qxml.cpp.
cltDq
const signed char cltDq = 12 static
Definition at line 98 of file qxml.cpp.
cltEm
const signed char cltEm = 7 static
Definition at line 93 of file qxml.cpp.
cltEq
const signed char cltEq = 11 static
Definition at line 97 of file qxml.cpp.
cltGt
const signed char cltGt = 3 static
Definition at line 89 of file qxml.cpp.
cltLt
const signed char cltLt = 4 static
Definition at line 90 of file qxml.cpp.
cltOB
const signed char cltOB = 10 static
Definition at line 96 of file qxml.cpp.
cltPer
const signed char cltPer = 1 static
Definition at line 87 of file qxml.cpp.
cltQm
const signed char cltQm = 6 static
Definition at line 92 of file qxml.cpp.
cltSlash
const signed char cltSlash = 5 static
Definition at line 91 of file qxml.cpp.
cltSq
const signed char cltSq = 13 static
Definition at line 99 of file qxml.cpp.
cltUnknown
const signed char cltUnknown = 14 static
Definition at line 100 of file qxml.cpp.
cltWS
const signed char cltWS = 0 static
Definition at line 86 of file qxml.cpp.
nameCharTable
const char nameCharTable[128] static
Initial value:
=
{
    NotN, NotN, NotN, NotN, NotN, NotN, NotN, NotN,
    NotN, NotN, NotN, NotN, NotN, NotN, NotN, NotN,
    NotN, NotN, NotN, NotN, NotN, NotN, NotN, NotN,
    NotN, NotN, NotN, NotN, NotN, NotN, NotN, NotN,
    NotN, NotN, NotN, NotN, NotN, NotN, NotN, NotN,
    NotN, NotN, NotN, NotN, NotN, NtBg, NtBg, NotN,
    NtBg, NtBg, NtBg, NtBg, NtBg, NtBg, NtBg, NtBg,
    NtBg, NtBg, Begi, NotN, NotN, NotN, NotN, NotN,
    NotN, Begi, Begi, Begi, Begi, Begi, Begi, Begi,
    Begi, Begi, Begi, Begi, Begi, Begi, Begi, Begi,
    Begi, Begi, Begi, Begi, Begi, Begi, Begi, Begi,
    Begi, Begi, Begi, NotN, NotN, NotN, NotN, Begi,
    NotN, Begi, Begi, Begi, Begi, Begi, Begi, Begi,
    Begi, Begi, Begi, Begi, Begi, Begi, Begi, Begi,
    Begi, Begi, Begi, Begi, Begi, Begi, Begi, Begi,
    Begi, Begi, Begi, NotN, NotN, NotN, NotN, NotN
}
Definition at line 3392 of file qxml.cpp.
NotN
const char NotN = (char)NotName static
Definition at line 3390 of file qxml.cpp.
NtBg
const char NtBg = (char)NameNotBeginning static
Definition at line 3389 of file qxml.cpp.
qt_xml_skipped_entity_in_content
bool qt_xml_skipped_entity_in_content
Definition at line 104 of file qxml.cpp.
Referenced by QXmlSimpleReader::parse(), QDomHandler::processingInstruction(), and QXmlSimpleReaderPrivate::processReference().