Qt 4.8: /src/xmlpatterns/schema/qxsdschemachecker.cpp File Reference
qxsdschemachecker.cpp File Reference
#include "qxsdschemachecker_p.h"
#include "qderivedinteger_p.h"
#include "qderivedstring_p.h"
#include "qpatternplatform_p.h"
#include "qqnamevalue_p.h"
#include "qsourcelocationreflection_p.h"
#include "qvaluefactory_p.h"
#include "qxsdattributereference_p.h"
#include "qxsdparticlechecker_p.h"
#include "qxsdreference_p.h"
#include "qxsdschemacontext_p.h"
#include "qxsdschemahelper_p.h"
#include "qxsdschemaparsercontext_p.h"
#include "qxsdschematypesfactory_p.h"
#include "qxsdtypechecker_p.h"
#include "qxsdschemachecker_helper.cpp"
Functions
static bool hasCircularUnionInheritance (const XsdSimpleType::Ptr &type, const SchemaType::Ptr &otherType, NamePool::Ptr &namePool)
static bool matchesType (const SchemaType::Ptr &myType, const SchemaType::Ptr &otherType, QSet< SchemaType::Ptr > visitedTypes)
static bool wxsTypeMatches (const SchemaType::Ptr &type, const SchemaType::Ptr &otherType, QSet< SchemaType::Ptr > &visitedTypes, SchemaType::Ptr &conflictingType)
Function Documentation
hasCircularUnionInheritance()
static bool hasCircularUnionInheritance (const XsdSimpleType::Ptr & type, const SchemaType::Ptr & otherType, NamePool::Ptr & namePool) static
Checks whether there is a circular inheritance for the union inheritance.
Definition at line 162 of file qxsdschemachecker.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkCircularInheritances().
 {
     if (type == otherType) {
         return true;
     }
     if (!otherType->isSimpleType() || !otherType->isDefinedBySchema()) {
         return false;
     }
     const XsdSimpleType::Ptr simpleOtherType = otherType;
     if (simpleOtherType->category() == XsdSimpleType::SimpleTypeUnion) {
         const XsdSimpleType::List memberTypes = simpleOtherType->memberTypes();
         for (int i = 0; i < memberTypes.count(); ++i) {
             if (otherType->wxsSuperType() == type) {
                 return true;
             }
             if (hasCircularUnionInheritance(type, memberTypes.at(i), namePool)) {
                 return true;
             }
         }
     }
     return false;
 }
matchesType()
static bool matchesType (const SchemaType::Ptr & myType, const SchemaType::Ptr & otherType, QSet< SchemaType::Ptr > visitedTypes) static
Checks whether the otherType is the same as myType or if one of its ancestors is the same as myType.
Definition at line 117 of file qxsdschemachecker.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkCircularInheritances().
 {
     bool retval = false;
     if (otherType) {
         if (visitedTypes.contains(otherType)) {
             return true;
         } else {
             visitedTypes.insert(otherType);
         }
         // simple types can have different varieties, so we have to check each of them
         if (otherType->isSimpleType()) {
             const XsdSimpleType::Ptr simpleType = otherType;
             if (simpleType->category() == XsdSimpleType::SimpleTypeAtomic) {
                 // for atomic type we use the same test as in SchemaType::wxsTypeMatches
                 retval = (myType == simpleType ? true : matchesType(myType, simpleType->wxsSuperType(), visitedTypes));
             } else if (simpleType->category() == XsdSimpleType::SimpleTypeList) {
                 // for list type we test against the itemType property
                 retval = (myType == simpleType->itemType() ? true : matchesType(myType, simpleType->itemType()->wxsSuperType(), visitedTypes));
             } else if (simpleType->category() == XsdSimpleType::SimpleTypeUnion) {
                 // for union type we test against each member type
                 const XsdSimpleType::List members = simpleType->memberTypes();
                 for (int i = 0; i < members.count(); ++i) {
                     if (myType == members.at(i) ? true : matchesType(myType, members.at(i)->wxsSuperType(), visitedTypes)) {
                         retval = true;
                         break;
                     }
                 }
             } else {
                 // reached xsAnySimple type whichs category is None
                 retval = false;
             }
         } else {
             // if no simple type we handle it like in SchemaType::wxsTypeMatches
             retval = (myType == otherType ? true : matchesType(myType, otherType->wxsSuperType(), visitedTypes));
         }
     } else // if otherType is null it doesn't match
         retval = false;
     return retval;
 }
wxsTypeMatches()
static bool wxsTypeMatches (const SchemaType::Ptr & type, const SchemaType::Ptr & otherType, QSet< SchemaType::Ptr > & visitedTypes, SchemaType::Ptr & conflictingType) inline static
Definition at line 189 of file qxsdschemachecker.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkAttributeConstraints(), QPatternist::XsdSchemaChecker::checkBasicCircularInheritances(), QPatternist::XsdTypeChecker::checkConstrainingFacets(), QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::XsdTypeChecker::checkConstrainingFacetsList(), QPatternist::ConstructorFunctionsFactory::ConstructorFunctionsFactory(), QPatternist::XsdSchemaChecker::hasConstraintIDAttributeUse(), hasIDAttributeUse(), QPatternist::XsdSchemaChecker::hasMultipleIDAttributeUses(), QPatternist::XsdTypeChecker::isValidString(), PerformComparison::operator()(), QPatternist::XsdSchemaResolver::resolveEnumerationFacetValues(), QPatternist::XsdValidatingInstanceReader::selectNodeSets(), QPatternist::XsdValidatingInstanceReader::validateAttribute(), QPatternist::XsdValidatingInstanceReader::validateElementComplexType(), QPatternist::XsdValidatingInstanceReader::validateElementSimpleType(), QPatternist::XsdTypeChecker::valuesAreEqual(), and QPatternist::yyparse().
 {
     if (!otherType)
         return false;
     if (visitedTypes.contains(otherType)) { // inheritance loop detected
         conflictingType = otherType;
         return true;
     } else {
         visitedTypes.insert(otherType);
     }
     if (type == otherType)
         return true;
     return wxsTypeMatches(type, otherType->wxsSuperType(), visitedTypes, conflictingType);
 }