Qt 4.8: /src/xmlpatterns/schema/qxsdschemaparser.cpp File Reference
qxsdschemaparser.cpp File Reference
#include "qxsdschemaparser_p.h"
#include "private/qxmlutils_p.h"
#include "qacceltreeresourceloader_p.h"
#include "qautoptr_p.h"
#include "qboolean_p.h"
#include "qcommonnamespaces_p.h"
#include "qderivedinteger_p.h"
#include "qderivedstring_p.h"
#include "qqnamevalue_p.h"
#include "qxmlquery_p.h"
#include "qxpathhelper_p.h"
#include "qxsdattributereference_p.h"
#include "qxsdreference_p.h"
#include "qxsdschematoken_p.h"
#include <QtCore/QFile>
#include <QtXmlPatterns/QXmlQuery>
Classes
class QPatternist::ElementNamespaceHandler
A helper class for automatically handling namespace scopes of elements.
class QPatternist::TagValidationHandler
Namespaces
QPatternist
The namespace for the internal API of QtXmlPatterns.
Functions
static XsdParticle::List collectGroupRef (const XsdModelGroup::Ptr &group)
static bool isValidUri (const QString &string)
Function Documentation
collectGroupRef()
static XsdParticle::List collectGroupRef (const XsdModelGroup::Ptr & group) static
Returns a list of all particles with group references that appear at any level of the given unresolved group.
Definition at line 215 of file qxsdschemaparser.cpp.
Referenced by QPatternist::XsdSchemaParser::parseRedefine().
 {
     XsdParticle::List refParticles;
     XsdParticle::List particles = group->particles();
     for (int i = 0; i < particles.count(); ++i) {
         if (particles.at(i)->term()->isReference()) {
             const XsdReference::Ptr reference(particles.at(i)->term());
             if (reference->type() == XsdReference::ModelGroup)
                 refParticles.append(particles.at(i));
         }
         if (particles.at(i)->term()->isModelGroup()) {
             refParticles << collectGroupRef(XsdModelGroup::Ptr(particles.at(i)->term()));
         }
     }
     return refParticles;
 }
isValidUri()
static bool isValidUri (const QString & string) inline static
Helper function that works around the limited facilities of QUrl/AnyURI::fromLexical to detect invalid URIs
Definition at line 238 of file qxsdschemaparser.cpp.
Referenced by QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaParser::parseAppInfo(), QPatternist::XsdSchemaParser::parseDocumentation(), QPatternist::XsdSchemaParser::parseNotation(), QPatternist::XsdSchemaParser::parseSchema(), and QPatternist::XsdSchemaParser::readXPathExpression().
 {
     // an empty URI points to the current document as defined in RFC 2396 (4.2)
     if (string.isEmpty())
         return true;
     // explicit check as that is not checked by the code below
     if (string.startsWith(QLatin1String("##")))
         return false;
     const AnyURI::Ptr uri = AnyURI::fromLexical(string);
     return (!(uri->hasError()));
 }