Qt 4.8: /src/xmlpatterns/schema/qxsdtypechecker.cpp File Reference
qxsdtypechecker.cpp File Reference
#include "qxsdtypechecker_p.h"
#include "qabstractdatetime_p.h"
#include "qbase64binary_p.h"
#include "qboolean_p.h"
#include "qdecimal_p.h"
#include "qderivedinteger_p.h"
#include "qduration_p.h"
#include "qgenericstaticcontext_p.h"
#include "qhexbinary_p.h"
#include "qnamespaceresolver_p.h"
#include "qpatternplatform_p.h"
#include "qqnamevalue_p.h"
#include "qvaluefactory_p.h"
#include "qxmlnamepool.h"
#include "qxsdschemahelper_p.h"
#include "qxsdschemamerger_p.h"
#include "qxsdstatemachine_p.h"
#include "qabstractfloat_p.h"
#include "qxsdschemadebugger_p.h"
Functions
static AnySimpleType::Ptr comparableType (const AnySimpleType::Ptr &type)
static int fractionDigitsForDecimal (const QString &lexicalValue)
static int totalDigitsForDecimal (const QString &lexicalValue)
static int totalDigitsForSignedLongLong (long long value)
static int totalDigitsForUnsignedLongLong (unsigned long long value)
Function Documentation
comparableType()
static AnySimpleType::Ptr comparableType (const AnySimpleType::Ptr & type) static
Definition at line 84 of file qxsdtypechecker.cpp.
Referenced by QPatternist::XsdTypeChecker::checkConstrainingFacetsList(), QPatternist::XsdTypeChecker::checkConstrainingFacetsUnion(), and QPatternist::XsdTypeChecker::valuesAreEqual().
 {
     if (!type->isDefinedBySchema()) {
         return type;
     } else {
         const XsdSimpleType::Ptr simpleType(type);
         if (type->category() == SchemaType::SimpleTypeAtomic) {
             return simpleType->primitiveType();
         } else if (type->category() == SchemaType::SimpleTypeList) {
             return simpleType->itemType();
         } else if (type->category() == SchemaType::SimpleTypeUnion) {
             return simpleType->memberTypes().first();
         }
     }
     Q_ASSERT(false);
     return AnySimpleType::Ptr();
 }
fractionDigitsForDecimal()
static int fractionDigitsForDecimal (const QString & lexicalValue) static
Definition at line 152 of file qxsdtypechecker.cpp.
Referenced by QPatternist::XsdTypeChecker::checkConstrainingFacetsDecimal().
 {
     // we use the lexical value here, as the conversion to double might strip
     // away decimal positions
     QString trimmedValue(lexicalValue.trimmed());
     const int pos = trimmedValue.indexOf(QLatin1Char('.'));
     if (pos == -1) // no '.' -> 0 fraction digits
         return 0;
     else
         return (trimmedValue.length() - pos - 1);
 }
totalDigitsForDecimal()
static int totalDigitsForDecimal (const QString & lexicalValue) static
Definition at line 118 of file qxsdtypechecker.cpp.
Referenced by QPatternist::XsdTypeChecker::checkConstrainingFacetsDecimal().
 {
     const QLatin1Char zeroChar('0');
     const int length = lexicalValue.length() - 1;
     // strip leading zeros
     int pos = 0;
     while (lexicalValue.at(pos) == zeroChar && (pos != length))
         pos++;
     QString value = lexicalValue.mid(pos);
     // if contains '.' strip trailing zeros
     if (value.contains(QLatin1Char('.'))) {
         pos = value.length() - 1;
         while (value.at(pos) == zeroChar) {
             pos--;
         }
         value = value.left(pos + 1);
     }
     // check number of digits of remaining string
     int totalDigits = 0;
     for (int i = 0; i < value.count(); ++i)
         if (value.at(i).isDigit())
             ++totalDigits;
     if (totalDigits == 0)
         totalDigits = 1;
     return totalDigits;
 }
totalDigitsForSignedLongLong()
static int totalDigitsForSignedLongLong (long long value) static
Definition at line 103 of file qxsdtypechecker.cpp.
Referenced by QPatternist::XsdTypeChecker::checkConstrainingFacetsSignedInteger().
 {
     QString number = QString::number(value);
     if (number.startsWith(QLatin1Char('-')))
         number = number.mid(1);
     return number.length();
 }
totalDigitsForUnsignedLongLong()
static int totalDigitsForUnsignedLongLong (unsigned long long value) static
Definition at line 112 of file qxsdtypechecker.cpp.
Referenced by QPatternist::XsdTypeChecker::checkConstrainingFacetsUnsignedInteger().
 {
     const QString number = QString::number(value);
     return number.length();
 }