Qt 4.8: /src/xmlpatterns/schema/qxsdschemaresolver.cpp File Reference
qxsdschemaresolver.cpp File Reference
#include "qxsdschemaresolver_p.h"
#include "qderivedinteger_p.h"
#include "qderivedstring_p.h"
#include "qqnamevalue_p.h"
#include "qxsdattributereference_p.h"
#include "qxsdparticlechecker_p.h"
#include "qxsdreference_p.h"
#include "qxsdschemacontext_p.h"
#include "qxsdschemahelper_p.h"
#include "qxsdschemaparsercontext_p.h"
#include "qxsdschematypesfactory_p.h"
Functions
bool hasCircularSubstitutionGroup (const XsdElement::Ptr &current, const XsdElement::Ptr &head, const NamePool::Ptr &namePool)
bool isSubstGroupHeadOf (const XsdElement::Ptr &head, const XsdElement::Ptr &element, const NamePool::Ptr &namePool)
bool isValidWildcardRestriction (const XsdWildcard::Ptr &wildcard, const XsdWildcard::Ptr &baseWildcard)
Function Documentation
hasCircularSubstitutionGroup()
bool hasCircularSubstitutionGroup (const XsdElement::Ptr & current, const XsdElement::Ptr & head, const NamePool::Ptr & namePool)
Definition at line 1002 of file qxsdschemaresolver.cpp.
Referenced by QPatternist::XsdSchemaResolver::resolveSubstitutionGroupAffiliations().
 {
     if (current == head)
         return true;
     else {
         const XsdElement::List elements = current->substitutionGroupAffiliations();
         for (int i = 0; i < elements.count(); ++i) {
             if (hasCircularSubstitutionGroup(elements.at(i), head, namePool))
                 return true;
         }
     }
     return false;
 }
isSubstGroupHeadOf()
bool isSubstGroupHeadOf (const XsdElement::Ptr & head, const XsdElement::Ptr & element, const NamePool::Ptr & namePool)
Definition at line 1051 of file qxsdschemaresolver.cpp.
Referenced by QPatternist::XsdSchemaResolver::resolveSubstitutionGroups().
 {
     if (head->name(namePool) == element->name(namePool))
         return true;
     const XsdElement::List affiliations = element->substitutionGroupAffiliations();
     for (int i = 0; i < affiliations.count(); ++i) {
         if (isSubstGroupHeadOf(head, affiliations.at(i), namePool))
             return true;
     }
     return false;
 }
isValidWildcardRestriction()
bool isValidWildcardRestriction (const XsdWildcard::Ptr & wildcard, const XsdWildcard::Ptr & baseWildcard)
Definition at line 1411 of file qxsdschemaresolver.cpp.
Referenced by QPatternist::XsdSchemaResolver::resolveAttributeInheritance().
 {
     if (wildcard->namespaceConstraint()->variety() == baseWildcard->namespaceConstraint()->variety()) {
         if (!XsdSchemaHelper::checkWildcardProcessContents(baseWildcard, wildcard))
             return false;
     }
     if (wildcard->namespaceConstraint()->variety() == XsdWildcard::NamespaceConstraint::Any &&
         baseWildcard->namespaceConstraint()->variety() != XsdWildcard::NamespaceConstraint::Any ) {
         return false;
     }
     if (baseWildcard->namespaceConstraint()->variety() == XsdWildcard::NamespaceConstraint::Not &&
         wildcard->namespaceConstraint()->variety() == XsdWildcard::NamespaceConstraint::Enumeration) {
         if (!baseWildcard->namespaceConstraint()->namespaces().intersect(wildcard->namespaceConstraint()->namespaces()).isEmpty())
             return false;
     }
     if (baseWildcard->namespaceConstraint()->variety() == XsdWildcard::NamespaceConstraint::Enumeration &&
         wildcard->namespaceConstraint()->variety() == XsdWildcard::NamespaceConstraint::Enumeration) {
         if (!wildcard->namespaceConstraint()->namespaces().subtract(baseWildcard->namespaceConstraint()->namespaces()).isEmpty())
             return false;
     }
     return true;
 }