Qt 4.8: /src/plugins/accessible/widgets/simplewidgets.cpp File Reference
simplewidgets.cpp File Reference
#include "simplewidgets.h"
#include <qabstractbutton.h>
#include <qcheckbox.h>
#include <qpushbutton.h>
#include <qprogressbar.h>
#include <qstatusbar.h>
#include <qradiobutton.h>
#include <qtoolbutton.h>
#include <qlabel.h>
#include <qgroupbox.h>
#include <qlcdnumber.h>
#include <qtextdocument.h>
#include <qlineedit.h>
#include <private/qlineedit_p.h>
#include <qstyle.h>
#include <qstyleoption.h>
#include <qfocusframe.h>
Functions
QList< QWidget * > childWidgets (const QWidget *widget, bool includeTopLevel=false)
QString Q_GUI_EXPORT qt_accHotKey (const QString &text)
QString Q_GUI_EXPORT qt_accStripAmp (const QString &text)
QString Q_GUI_EXPORT qTextAfterOffsetFromString (int offset, QAccessible2::BoundaryType boundaryType, int *startOffset, int *endOffset, const QString &text)
QString Q_GUI_EXPORT qTextAtOffsetFromString (int offset, QAccessible2::BoundaryType boundaryType, int *startOffset, int *endOffset, const QString &text)
QString Q_GUI_EXPORT qTextBeforeOffsetFromString (int offset, QAccessible2::BoundaryType boundaryType, int *startOffset, int *endOffset, const QString &text)
Function Documentation
childWidgets()
QList<QWidget*> childWidgets (const QWidget * widget, bool includeTopLevel = false)
Definition at line 80 of file qaccessiblewidgets.cpp.
Referenced by QAccessibleMainWindow::childAt(), QAccessibleMainWindow::childCount(), QAccessibleMainWindow::indexOfChild(), and QAccessibleMainWindow::navigate().
 {
     if (widget == 0)
         return QList<QWidget*>();
     QList<QObject*> list = widget->children();
     QList<QWidget*> widgets;
     for (int i = 0; i < list.size(); ++i) {
         QWidget *w = qobject_cast<QWidget *>(list.at(i));
         if (!w)
             continue;
         QString objectName = w->objectName();
         if ((includeTopLevel || !w->isWindow())
               && !qobject_cast<QFocusFrame*>(w)
               && !qobject_cast<QMenu*>(w)
               && objectName != QLatin1String("qt_rubberband")
               && objectName != QLatin1String("qt_qmainwindow_extended_splitter")) {
             widgets.append(w);
         }
     }
     return widgets;
 }
qt_accHotKey()
QString Q_GUI_EXPORT qt_accHotKey (const QString & text)
Definition at line 145 of file qaccessiblewidget.cpp.
Referenced by QAccessibleButton::text(), and QAccessibleWidget::text().
 {
     int ampIndex = qt_accAmpIndex(text);
     if (ampIndex != -1)
         return (QString)QKeySequence(Qt::ALT) + text.at(ampIndex + 1);
     return QString();
 }
qt_accStripAmp()
QString Q_GUI_EXPORT qt_accStripAmp (const QString & text)
Definition at line 135 of file qaccessiblewidget.cpp.
Referenced by QAccessibleButton::text(), QAccessibleWidget::text(), QAccessibleToolButton::text(), QAccessibleDisplay::text(), QAccessibleGroupBox::text(), and QAccessibleLineEdit::text().
 {
     QString newText(text);
     int ampIndex = qt_accAmpIndex(newText);
     if (ampIndex != -1)
         newText.remove(ampIndex, 1);
     return newText.replace(QLatin1String("&&"), QLatin1String("&"));
 }
qTextAfterOffsetFromString()
QString Q_GUI_EXPORT qTextAfterOffsetFromString (int offset, QAccessible2::BoundaryType boundaryType, int * startOffset, int * endOffset, const QString & text)
Warning
This function is not part of the public interface.
Definition at line 199 of file qaccessible2.cpp.
Referenced by QAccessibleLineEdit::textAfterOffset().
 {
     QTextBoundaryFinder::BoundaryType type;
     switch (boundaryType) {
     case QAccessible2::CharBoundary:
         type = QTextBoundaryFinder::Grapheme;
         break;
     case QAccessible2::WordBoundary:
         type = QTextBoundaryFinder::Word;
         break;
     case QAccessible2::SentenceBoundary:
         type = QTextBoundaryFinder::Sentence;
         break;
     default:
         // in any other case return the whole line
         *startOffset = 0;
         *endOffset = text.length();
         return text;
     }
     QTextBoundaryFinder boundary(type, text);
     boundary.setPosition(offset);
     boundary.toNextBoundary();
     *startOffset = boundary.position();
     boundary.toNextBoundary();
     *endOffset = boundary.position();
     return text.mid(*startOffset, *endOffset - *startOffset);
 }
qTextAtOffsetFromString()
QString Q_GUI_EXPORT qTextAtOffsetFromString (int offset, QAccessible2::BoundaryType boundaryType, int * startOffset, int * endOffset, const QString & text)
Warning
This function is not part of the public interface.
Definition at line 234 of file qaccessible2.cpp.
Referenced by QAccessibleLineEdit::textAtOffset().
 {
     QTextBoundaryFinder::BoundaryType type;
     switch (boundaryType) {
     case QAccessible2::CharBoundary:
         type = QTextBoundaryFinder::Grapheme;
         break;
     case QAccessible2::WordBoundary:
         type = QTextBoundaryFinder::Word;
         break;
     case QAccessible2::SentenceBoundary:
         type = QTextBoundaryFinder::Sentence;
         break;
     default:
         // in any other case return the whole line
         *startOffset = 0;
         *endOffset = text.length();
         return text;
     }
     QTextBoundaryFinder boundary(type, text);
     boundary.setPosition(offset);
     if (!boundary.isAtBoundary()) {
         boundary.toPreviousBoundary();
     }
     *startOffset = boundary.position();
     boundary.toNextBoundary();
     *endOffset = boundary.position();
     return text.mid(*startOffset, *endOffset - *startOffset);
 }
qTextBeforeOffsetFromString()
QString Q_GUI_EXPORT qTextBeforeOffsetFromString (int offset, QAccessible2::BoundaryType boundaryType, int * startOffset, int * endOffset, const QString & text)
Warning
This function is not part of the public interface.
Definition at line 161 of file qaccessible2.cpp.
Referenced by QAccessibleLineEdit::textBeforeOffset().
 {
     QTextBoundaryFinder::BoundaryType type;
     switch (boundaryType) {
     case QAccessible2::CharBoundary:
         type = QTextBoundaryFinder::Grapheme;
         break;
     case QAccessible2::WordBoundary:
         type = QTextBoundaryFinder::Word;
         break;
     case QAccessible2::SentenceBoundary:
         type = QTextBoundaryFinder::Sentence;
         break;
     default:
         // in any other case return the whole line
         *startOffset = 0;
         *endOffset = text.length();
         return text;
     }
     QTextBoundaryFinder boundary(type, text);
     boundary.setPosition(offset);
     if (!boundary.isAtBoundary()) {
         boundary.toPreviousBoundary();
     }
     boundary.toPreviousBoundary();
     *startOffset = boundary.position();
     boundary.toNextBoundary();
     *endOffset = boundary.position();
     return text.mid(*startOffset, *endOffset - *startOffset);
 }