Qt 4.8: QTexturedBrushData Struct Reference
QTexturedBrushData Struct Reference
Public Functions
QImage & image ()
QPixmap & pixmap ()
QTexturedBrushData ()
void setImage (const QImage &image)
void setPixmap (const QPixmap &pm)
~QTexturedBrushData ()
Public Variables
bool m_has_pixmap_texture
QImage m_image
QPixmap * m_pixmap
Public Variables inherited from QBrushData
QColor color
QAtomicInt ref
Qt::BrushStyle style
QTransform transform
Detailed Description
Definition at line 172 of file qbrush.cpp.
Constructors and Destructors
QTexturedBrushData()
QTexturedBrushData::QTexturedBrushData () inline
Definition at line 174 of file qbrush.cpp.
{
         m_has_pixmap_texture = false;
         m_pixmap = 0;
     }
~QTexturedBrushData()
QTexturedBrushData::~QTexturedBrushData () inline
Definition at line 178 of file qbrush.cpp.
{
         delete m_pixmap;
     }
Functions
image()
QImage& QTexturedBrushData::image () inline
Definition at line 210 of file qbrush.cpp.
Referenced by QBrush::detach().
                     {
         if (m_image.isNull() && m_pixmap)
             m_image = m_pixmap->toImage();
         return m_image;
     }
pixmap()
QPixmap& QTexturedBrushData::pixmap () inline
Definition at line 203 of file qbrush.cpp.
Referenced by QBrush::detach(), and QBrush::setColor().
                       {
         if (!m_pixmap) {
             m_pixmap = new QPixmap(QPixmap::fromImage(m_image));
         }
         return *m_pixmap;
     }
setImage()
void QTexturedBrushData::setImage (const QImage & image) inline
Definition at line 196 of file qbrush.cpp.
Referenced by QBrush::detach(), and QBrush::setTextureImage().
{
         m_image = image;
         delete m_pixmap;
         m_pixmap = 0;
         m_has_pixmap_texture = false;
     }
setPixmap()
void QTexturedBrushData::setPixmap (const QPixmap & pm) inline
Definition at line 182 of file qbrush.cpp.
Referenced by QBrush::detach(), and QBrush::setTexture().
{
         delete m_pixmap;
         if (pm.isNull()) {
             m_pixmap = 0;
             m_has_pixmap_texture = false;
         } else {
             m_pixmap = new QPixmap(pm);
             m_has_pixmap_texture = true;
         }
         m_image = QImage();
     }
Properties
m_has_pixmap_texture
bool QTexturedBrushData::m_has_pixmap_texture
Definition at line 218 of file qbrush.cpp.
Referenced by QBrush::detach(), and qHasPixmapTexture().
m_image
QImage QTexturedBrushData::m_image
Definition at line 217 of file qbrush.cpp.
m_pixmap
QPixmap* QTexturedBrushData::m_pixmap
Definition at line 216 of file qbrush.cpp.
The documentation for this struct was generated from the following file:
/src/gui/painting/qbrush.cpp