Qt 4.8: QList< T >::Node Struct Reference
QList< T >::Node Struct Reference
Public Functions
Q_INLINE_TEMPLATE T & t ()
Public Variables
void * v
Detailed Description
template<typename T>
struct QList< T >::Node
Definition at line 108 of file qlist.h.
Functions
t()
template<typename T> Q_INLINE_TEMPLATE T& QList< T >::Node::t () inline
Definition at line 112 of file qlist.h.
Referenced by QList< T >::iterator::operator*(), QList< T >::const_iterator::operator*(), QList< T >::iterator::operator->(), QList< T >::const_iterator::operator->(), QList< T >::iterator::operator[](), QList< T >::const_iterator::operator[](), and QList< QPostEvent >::toStdList().
         { return *reinterpret_cast<T*>(QTypeInfo<T>::isLarge || QTypeInfo<T>::isStatic
                                        ? v : this); }
Properties
v
template<typename T> void* QList< T >::Node::v
Definition at line 108 of file qlist.h.
The documentation for this struct was generated from the following file:
/src/corelib/tools/qlist.h