Qt 4.8: KeyRecorder Struct Reference
KeyRecorder Struct Reference
Public Functions
void clearKeys ()
KeyRecord * findKey (int code, bool remove)
KeyRecorder ()
void storeKey (int code, int ascii, int state, const QString &text)
Public Variables
KeyRecord deleted_record
int nrecs
KeyRecord records [QT_MAX_KEY_RECORDINGS]
Detailed Description
Definition at line 107 of file qkeymapper_win.cpp.
Constructors and Destructors
KeyRecorder()
KeyRecorder::KeyRecorder () inline
Definition at line 109 of file qkeymapper_win.cpp.
 : nrecs(0) {}
Functions
clearKeys()
void KeyRecorder::clearKeys () inline
Definition at line 157 of file qkeymapper_win.cpp.
Referenced by QKeyMapperPrivate::clearRecordedKeys().
 {
     nrecs = 0;
 }
findKey()
KeyRecord * KeyRecorder::findKey (int code, bool remove) inline
Definition at line 121 of file qkeymapper_win.cpp.
Referenced by QKeyMapperPrivate::isADeadKey().
 {
     KeyRecord *result = 0;
     for (int i = 0; i < nrecs; ++i) {
         if (records[i].code == code) {
             if (remove) {
                 deleted_record = records[i];
                 // Move rest down, and decrease count
                 while (i + 1 < nrecs) {
                     records[i] = records[i + 1];
                     ++i;
                 }
                 --nrecs;
                 result = &deleted_record;
             } else {
                 result = &records[i];
             }
             break;
         }
     }
     return result;
 }
storeKey()
void KeyRecorder::storeKey (int code, int ascii, int state, const QString & text) inline
Definition at line 144 of file qkeymapper_win.cpp.
Referenced by QKeyMapperPrivate::isADeadKey().
 {
     Q_ASSERT_X(nrecs != QT_MAX_KEY_RECORDINGS,
                "Internal KeyRecorder",
                "Keyboard recorder buffer overflow, consider increasing QT_MAX_KEY_RECORDINGS");
     if (nrecs == QT_MAX_KEY_RECORDINGS) {
         qWarning("Qt: Internal keyboard buffer overflow");
         return;
     }
     records[nrecs++] = KeyRecord(code,ascii,state,text);
 }
Properties
deleted_record
KeyRecord KeyRecorder::deleted_record
Definition at line 116 of file qkeymapper_win.cpp.
nrecs
int KeyRecorder::nrecs
Definition at line 115 of file qkeymapper_win.cpp.
records
KeyRecord KeyRecorder::records[QT_MAX_KEY_RECORDINGS]
Definition at line 117 of file qkeymapper_win.cpp.
The documentation for this struct was generated from the following file:
/src/gui/kernel/qkeymapper_win.cpp