Qt 4.8: QAbstractDynamicMetaObject Struct Reference
QAbstractDynamicMetaObject Struct Reference
#include <qobject_p.h>
Public Functions
virtual int createProperty (const char *, const char *)
virtual int metaCall (QMetaObject::Call, int _id, void **)
virtual ~QAbstractDynamicMetaObject ()
Public Functions inherited from QMetaObject
QObject * cast (QObject *obj) const
Returns obj if object obj inherits from this meta-object; otherwise returns 0.
const QObject * cast (const QObject *obj) const
Returns obj if object obj inherits from this meta-object; otherwise returns 0.
QMetaClassInfo classInfo (int index) const
Returns the meta-data for the item of class information with the given index.
int classInfoCount () const
Returns the number of items of class information in this class.
int classInfoOffset () const
Returns the class information offset for this class; i.e.
const char * className () const
Returns the class name.
QMetaMethod constructor (int index) const
Returns the meta-data for the constructor with the given index.
int constructorCount () const
Returns the number of constructors in this class.
QMetaEnum enumerator (int index) const
Returns the meta-data for the enumerator with the given index.
int enumeratorCount () const
Returns the number of enumerators in this class.
int enumeratorOffset () const
Returns the enumerator offset for this class; i.e.
int indexOfClassInfo (const char *name) const
Finds class information item name and returns its index; otherwise returns -1.
int indexOfConstructor (const char *constructor) const
Finds constructor and returns its index; otherwise returns -1.
int indexOfEnumerator (const char *name) const
Finds enumerator name and returns its index; otherwise returns -1.
int indexOfMethod (const char *method) const
Finds method and returns its index; otherwise returns -1.
int indexOfProperty (const char *name) const
Finds property name and returns its index; otherwise returns -1.
int indexOfSignal (const char *signal) const
Finds signal and returns its index; otherwise returns -1.
int indexOfSlot (const char *slot) const
Finds slot and returns its index; otherwise returns -1.
QMetaMethod method (int index) const
Returns the meta-data for the method with the given index.
int methodCount () const
Returns the number of methods known to the meta-object system in this class, including the number of properties provided by each base class.
int methodOffset () const
Returns the method offset for this class; i.e.
QObject * newInstance (QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument()) const
Constructs a new instance of this class.
QMetaProperty property (int index) const
Returns the meta-data for the property with the given index.
int propertyCount () const
Returns the number of properties in this class, including the number of properties provided by each base class.
int propertyOffset () const
Returns the property offset for this class; i.e.
int static_metacall (Call, int, void **) const
const QMetaObject * superClass () const
Returns the meta-object of the superclass, or 0 if there is no such object.
QString tr (const char *s, const char *c) const
QString tr (const char *s, const char *c, int n) const
QString trUtf8 (const char *s, const char *c) const
QString trUtf8 (const char *s, const char *c, int n) const
QMetaProperty userProperty () const
Returns the property that has the USER flag set to true.
Additional Inherited Members
Public Types inherited from QMetaObject
enum Call {
InvokeMetaMethod, ReadProperty, WriteProperty, ResetProperty,
QueryPropertyDesignable, QueryPropertyScriptable, QueryPropertyStored, QueryPropertyEditable,
QueryPropertyUser, CreateInstance
}
Static Public Functions inherited from QMetaObject
static void activate (QObject *sender, int signal_index, void **argv)
static void activate (QObject *sender, int from_signal_index, int to_signal_index, void **argv)
static void activate (QObject *sender, const QMetaObject *, int local_signal_index, void **argv)
static void activate (QObject *sender, const QMetaObject *, int from_local_signal_index, int to_local_signal_index, void **argv)
static void addGuard (QObject **ptr)
static void changeGuard (QObject **ptr, QObject *o)
static bool checkConnectArgs (const char *signal, const char *method)
Returns true if the signal and method arguments are compatible; otherwise returns false.
static bool connect (const QObject *sender, int signal_index, const QObject *receiver, int method_index, int type=0, int *types=0)
static void connectSlotsByName (QObject *o)
Searches recursively for all child objects of the given object, and connects matching signals from them to slots of object that follow the following form:
static bool disconnect (const QObject *sender, int signal_index, const QObject *receiver, int method_index)
static bool disconnectOne (const QObject *sender, int signal_index, const QObject *receiver, int method_index)
static bool invokeMethod (QObject *obj, const char *member, Qt::ConnectionType, QGenericReturnArgument ret, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
Invokes the member (a signal or a slot name) on the object obj.
static bool invokeMethod (QObject *obj, const char *member, QGenericReturnArgument ret, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
static bool invokeMethod (QObject *obj, const char *member, Qt::ConnectionType type, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
static bool invokeMethod (QObject *obj, const char *member, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
static int metacall (QObject *, Call, int, void **)
static QByteArray normalizedSignature (const char *method)
Normalizes the signature of the given method.
static QByteArray normalizedType (const char *type)
Normalizes a type.
static void removeGuard (QObject **ptr)
Public Variables inherited from QMetaObject
struct {
const uint * data
const void * extradata
const char * stringdata
const QMetaObject * superdata
} d
Detailed Description
Definition at line 333 of file qobject_p.h.
Constructors and Destructors
~QAbstractDynamicMetaObject()
virtual QAbstractDynamicMetaObject::~QAbstractDynamicMetaObject () inline virtual
Definition at line 335 of file qobject_p.h.
 {}
Functions
createProperty()
virtual int QAbstractDynamicMetaObject::createProperty (const char * , const char *) inline virtual
Reimplemented in QDeclarativeVisualDataModelDataMetaObject, and QDeclarativeOpenMetaObject.
Definition at line 337 of file qobject_p.h.
Referenced by QMetaObject::indexOfProperty().
 { return -1; }
metaCall()
virtual int QAbstractDynamicMetaObject::metaCall (QMetaObject::Call , int _id, void **) inline virtual
Reimplemented in QDeclarativeVMEMetaObject, QDeclarativeOpenMetaObject, QDeclarativeProxyMetaObject, and QDeclarativeBoundSignalParameters::MetaObject.
Definition at line 336 of file qobject_p.h.
Referenced by QDeclarativeProxyMetaObject::metaCall(), QDeclarativeOpenMetaObject::metaCall(), and QDeclarativeVMEMetaObject::metaCall().
 { return _id; }
The documentation for this struct was generated from the following file:
/src/corelib/kernel/qobject_p.h