Qt 4.8: QWSEmbedCommand Struct Reference
QWSEmbedCommand Struct Reference
#include <qwscommand_qws_p.h>
Public Functions
QWSEmbedCommand ()
void setData (const char *d, int len, bool allocateMem=true)
void setData (WId embedder, WId embedded, QWSEmbedEvent::Type type, const QRegion reg=QRegion())
Public Functions inherited from QWSCommand
QWSCommand (int t, int len, char *ptr)
Public Functions inherited from QWSProtocolItem
void copyFrom (const QWSProtocolItem *item)
QWSProtocolItem (int t, int len, char *ptr)
bool read (QIODevice *s)
void write (QIODevice *s)
virtual ~QWSProtocolItem ()
Public Variables
QRegion region
struct {
WId embedded
WId embedder
int rects
QWSEmbedEvent::Type type
} simpleData
Public Variables inherited from QWSProtocolItem
int bytesRead
bool deleteRaw
char * rawDataPtr
int rawLen
char * simpleDataPtr
int simpleLen
int type
Additional Inherited Members
Public Types inherited from QWSCommand
enum Type {
Unknown = 0, Create, Shutdown, Region,
RegionMove, RegionDestroy, SetProperty, AddProperty,
RemoveProperty, GetProperty, SetSelectionOwner, ConvertSelection,
RequestFocus, ChangeAltitude, SetOpacity, DefineCursor,
SelectCursor, PositionCursor, GrabMouse, PlaySound,
QCopRegisterChannel, QCopSend, RegionName, Identify,
GrabKeyboard, RepaintRegion, IMMouse, IMUpdate,
IMResponse, Embed, Font, ScreenTransform
}
Static Public Functions inherited from QWSCommand
static QWSCommand * factory (int type)
Detailed Description
Definition at line 753 of file qwscommand_qws_p.h.
Constructors and Destructors
QWSEmbedCommand()
QWSEmbedCommand::QWSEmbedCommand () inline
Definition at line 755 of file qwscommand_qws_p.h.
                       : QWSCommand(QWSCommand::Embed,
                                    sizeof(simpleData),
                                    reinterpret_cast<char*>(&simpleData))
     {}
Functions
setData() [1/2]
void QWSEmbedCommand::setData (const char * d, int len, bool allocateMem = true) inline virtual
Reimplemented from QWSProtocolItem.
Definition at line 760 of file qwscommand_qws_p.h.
Referenced by QWSEmbedWidgetPrivate::resize(), QWSEmbedWidgetPrivate::updateWindow(), and QWSEmbedWidget::~QWSEmbedWidget().
     {
         QWSCommand::setData(d, len, allocateMem);
         if( simpleData.rects * int(sizeof(QRect)) > len )
         {
             qWarning( "embed command - region rectangle count %d - buffer size %d - buffer overrun!",
                       simpleData.rects, len );
         }
         else
         {
             region.setRects(reinterpret_cast<QRect*>(rawDataPtr),
                             simpleData.rects);
         }
     }
setData() [2/2]
void QWSEmbedCommand::setData (WId embedder, WId embedded, QWSEmbedEvent::Type type, const QRegion reg = QRegion()) inline
Definition at line 776 of file qwscommand_qws_p.h.
     {
         simpleData.embedder = embedder;
         simpleData.embedded = embedded;
         simpleData.type = type;
         region = reg;
         const QVector<QRect> rects = reg.rects();
         simpleData.rects = rects.count();
         QWSCommand::setData(reinterpret_cast<const char*>(rects.constData()),
                             rects.count() * sizeof(QRect));
     }
Properties
embedded
WId QWSEmbedCommand::embedded
Definition at line 793 of file qwscommand_qws_p.h.
Referenced by QWSServerPrivate::invokeEmbed().
embedder
WId QWSEmbedCommand::embedder
Definition at line 792 of file qwscommand_qws_p.h.
Referenced by QWSServerPrivate::invokeEmbed().
rects
int QWSEmbedCommand::rects
Definition at line 795 of file qwscommand_qws_p.h.
region
QRegion QWSEmbedCommand::region
Definition at line 798 of file qwscommand_qws_p.h.
Referenced by QWSServerPrivate::invokeEmbed().
simpleData
struct { ... } QWSEmbedCommand::simpleData
Referenced by QWSServerPrivate::invokeEmbed().
type
QWSEmbedEvent::Type QWSEmbedCommand::type
Definition at line 794 of file qwscommand_qws_p.h.
Referenced by QWSServerPrivate::invokeEmbed().
The documentation for this struct was generated from the following file:
/src/gui/embedded/qwscommand_qws_p.h