Qt 4.8: QFixed Struct Reference
QFixed Struct Reference
#include <qfixed_p.h>
Public Functions
QFixed ceil () const
QFixed floor () const
bool operator! () const
bool operator!= (const QFixed &other) const
QFixed operator* (int i) const
QFixed operator* (uint i) const
QFixed operator* (const QFixed &o) const
QFixed & operator*= (int i)
QFixed & operator*= (uint i)
QFixed & operator*= (const QFixed &o)
QFixed operator+ (int i) const
QFixed operator+ (uint i) const
QFixed operator+ (const QFixed &other) const
QFixed & operator+= (int i)
QFixed & operator+= (uint i)
QFixed & operator+= (const QFixed &other)
QFixed operator- (int i) const
QFixed operator- (uint i) const
QFixed operator- (const QFixed &other) const
QFixed operator- () const
QFixed & operator-= (int i)
QFixed & operator-= (uint i)
QFixed & operator-= (const QFixed &other)
QFixed operator/ (int d) const
QFixed operator/ (QFixed b) const
QFixed & operator/= (int x)
QFixed & operator/= (const QFixed &o)
bool operator< (const QFixed &other) const
bool operator<= (const QFixed &other) const
QFixed & operator= (int i)
QFixed & operator= (long i)
bool operator== (const QFixed &other) const
bool operator> (const QFixed &other) const
bool operator>= (const QFixed &other) const
QFixed operator>> (int d) const
QFixed ()
QFixed (int i)
QFixed (long i)
QFixed round () const
void setValue (int value)
int toInt () const
qreal toReal () const
int truncate () const
int value () const
Static Public Functions
static QFixed fromFixed (int fixed)
static QFixed fromReal (qreal r)
Private Functions
QFixed operator* (qreal d) const
QFixed & operator*= (qreal d)
QFixed operator+ (qreal i) const
QFixed & operator+= (qreal i)
QFixed operator- (qreal i) const
QFixed & operator-= (qreal i)
QFixed operator/ (qreal d) const
QFixed & operator/= (qreal r)
QFixed & operator= (qreal i)
QFixed (qreal i)
Properties
int val
Detailed Description
Definition at line 62 of file qfixed_p.h.
Constructors and Destructors
QFixed() [1/4]
QFixed::QFixed () inline
Definition at line 64 of file qfixed_p.h.
 : val(0) {}
QFixed() [2/4]
QFixed::QFixed (int i) inline
Definition at line 65 of file qfixed_p.h.
 : val(i<<6) {}
QFixed() [3/4]
QFixed::QFixed (long i) inline
Definition at line 66 of file qfixed_p.h.
 : val(i<<6) {}
QFixed() [4/4]
QFixed::QFixed (qreal i) inline private
Definition at line 144 of file qfixed_p.h.
 : val((int)(i*qreal(64))) {}
Functions
ceil()
QFixed QFixed::ceil () const inline
Definition at line 82 of file qfixed_p.h.
Referenced by QScriptLine::height(), QFontEngineXLFD::leading(), QFontEngineBox::leading(), and QTextureGlyphCache::populate().
 { QFixed f; f.val = (val+63) & -64; return f; }
floor()
QFixed QFixed::floor () const inline
Definition at line 81 of file qfixed_p.h.
Referenced by QFontEngineMac::boundingBox(), QTextEngine::positionInLigature(), qFloor(), QTextureGlyphCache::subPixelPositionForX(), and QFontEngineFT::subPixelPositionForX().
 { QFixed f; f.val = (val) & -64; return f; }
fromFixed()
static QFixed QFixed::fromFixed (int fixed) inline static
Definition at line 71 of file qfixed_p.h.
Referenced by QProxyFontEngine::ascent(), QFontEngineFT::ascent(), QProxyFontEngine::averageCharWidth(), QProxyFontEngine::boundingBox(), QFontEngineXLFD::boundingBox(), QProxyFontEngine::canRender(), QProxyFontEngine::descent(), QFontEngineFT::descent(), QGlyphLayout::effectiveAdvance(), QFontEngineQPA::extractHeaderField(), QFontEngineQPF::extractHeaderField(), QFontEngine::getGlyphPositions(), QFontEngineFT::getUnscaledGlyph(), QFontEngineFT::init(), QProxyFontEngine::leading(), QFontEngineFT::leading(), QProxyFontEngine::lineThickness(), QProxyFontEngine::maxCharWidth(), QProxyFontEngine::minLeftBearing(), QProxyFontEngine::minRightBearing(), QFreetypeFace::properties(), QProxyFontEngine::recalcAdvances(), QFontEngineFT::recalcAdvances(), QProxyFontEngine::underlinePosition(), and QProxyFontEngine::xHeight().
 { QFixed f; f.val = fixed; return f; }
fromReal()
static QFixed QFixed::fromReal (qreal r) inline static
Definition at line 70 of file qfixed_p.h.
Referenced by QFontEngine::addBitmapFontToPath(), QFontEngine::addGlyphsToPath(), QFontEngineQPA::ascent(), QFontEngineQPF::ascent(), QTextDocumentLayoutPrivate::blockIndent(), QFontEngineMac::boundingBox(), QFontEngineWin::boundingBox(), QTextureGlyphCache::calculateSubPixelPositionCount(), QTextEngine::calculateTabWidth(), QProxyFontEngine::canRender(), QFontEngineQPA::descent(), QFontEngineQPF::descent(), QDeclarativeTextLayout::draw(), QTextDocumentLayout::draw(), QTextLayout::draw(), QFontEngineQPF::draw(), QTextLine::draw(), QFontEngineQPF1::draw(), QRasterPaintEngine::drawCachedGlyphs(), QTextDocumentLayoutPrivate::drawFlow(), QTextDocumentLayoutPrivate::drawFrame(), QX11PaintEngine::drawFreetype(), QPainter::drawStaticText(), QPainter::drawText(), QX11PaintEngine::drawXLFD(), QFontMetricsF::elidedText(), QTextDocumentLayout::ensureLayouted(), flowPosition(), QFixedPoint::fromPointF(), QFixedSize::fromSizeF(), QFontEngine::getGlyphPositions(), getLineHeightParams(), QFontEngineMac::getUnscaledGlyph(), QTextDocumentLayout::hitTest(), QTextLine::layout_helper(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutCell(), QTextDocumentLayoutPrivate::layoutFlow(), QTextDocumentLayoutPrivate::layoutFrame(), QTextDocumentLayoutPrivate::layoutTable(), QFontEngineXLFD::leading(), QFontEngineQPA::leading(), QFontEngineQPF::leading(), QFontEngineBox::leading(), QFontEngineQPA::lineThickness(), QFontEngineQPF::lineThickness(), QTextTableData::paddingProperty(), QTextDocumentLayoutPrivate::positionFloat(), QFontEngineMac::QFontEngineMac(), QTextLineItemIterator::QTextLineItemIterator(), QFontEngineMac::recalcAdvances(), QTextInlineObject::setAscent(), QTextInlineObject::setDescent(), QFont::setLetterSpacing(), QTextLine::setLineWidth(), QTextLine::setNumColumns(), QTextLine::setPosition(), QTextInlineObject::setWidth(), QFont::setWordSpacing(), QTextureGlyphCache::subPixelPositionForX(), QFontEngineFT::subPixelPositionForX(), glyph_metrics_t::transformed(), QFontEngineQPA::underlinePosition(), QFontEngineQPF::underlinePosition(), QPAGenerator::writeHeader(), QPFGenerator::writeHeader(), and QTextLine::xToCursor().
 { QFixed f; f.val = (int)(r*qreal(64)); return f; }
operator!()
bool QFixed::operator! () const inline
Definition at line 104 of file qfixed_p.h.
 { return !val; }
operator!=()
bool QFixed::operator!= (const QFixed & other) const inline
Definition at line 99 of file qfixed_p.h.
 { return val != other.val; }
operator*() [1/4]
QFixed QFixed::operator* (int i) const inline
Definition at line 139 of file qfixed_p.h.
 { QFixed f = *this; return (f *= i); }
operator*() [2/4]
QFixed QFixed::operator* (uint i) const inline
Definition at line 140 of file qfixed_p.h.
 { QFixed f = *this; return (f *= i); }
operator*() [3/4]
QFixed QFixed::operator* (const QFixed & o) const inline
Definition at line 141 of file qfixed_p.h.
 { QFixed f = *this; return (f *= o); }
operator*() [4/4]
QFixed QFixed::operator* (qreal d) const inline private
Definition at line 153 of file qfixed_p.h.
 { QFixed f = *this; return (f *= d); }
operator*=() [1/4]
QFixed& QFixed::operator*= (int i) inline
Definition at line 126 of file qfixed_p.h.
 { val *= i; return *this; }
operator*=() [2/4]
QFixed& QFixed::operator*= (uint i) inline
Definition at line 127 of file qfixed_p.h.
 { val *= i; return *this; }
operator*=() [3/4]
QFixed& QFixed::operator*= (const QFixed & o) inline
Definition at line 128 of file qfixed_p.h.
{
         bool neg = false;
         qint64 a = val;
         qint64 b = o.val;
         if (a < 0) { a = -a; neg = true; }
         if (b < 0) { b = -b; neg = !neg; }
         int res = (int)((a * b + 0x20L) >> 6);
         val = neg ? -res : res;
         return *this;
     }
operator*=() [4/4]
QFixed& QFixed::operator*= (qreal d) inline private
Definition at line 152 of file qfixed_p.h.
 { val = (int) (val*d); return *this; }
operator+() [1/4]
QFixed QFixed::operator+ (int i) const inline
Definition at line 84 of file qfixed_p.h.
 { QFixed f; f.val = (val + (i<<6)); return f; }
operator+() [2/4]
QFixed QFixed::operator+ (uint i) const inline
Definition at line 85 of file qfixed_p.h.
 { QFixed f; f.val = (val + (i<<6)); return f; }
operator+() [3/4]
QFixed QFixed::operator+ (const QFixed & other) const inline
Definition at line 86 of file qfixed_p.h.
 { QFixed f; f.val = (val + other.val); return f; }
operator+() [4/4]
QFixed QFixed::operator+ (qreal i) const inline private
Definition at line 146 of file qfixed_p.h.
 { QFixed f; f.val = (val + (int)(i*qreal(64))); return f; }
operator+=() [1/4]
QFixed& QFixed::operator+= (int i) inline
Definition at line 87 of file qfixed_p.h.
 { val += (i<<6); return *this; }
operator+=() [2/4]
QFixed& QFixed::operator+= (uint i) inline
Definition at line 88 of file qfixed_p.h.
 { val += (i<<6); return *this; }
operator+=() [3/4]
QFixed& QFixed::operator+= (const QFixed & other) inline
Definition at line 89 of file qfixed_p.h.
 { val += other.val; return *this; }
operator+=() [4/4]
QFixed& QFixed::operator+= (qreal i) inline private
Definition at line 147 of file qfixed_p.h.
 { val += (int)(i*64); return *this; }
operator-() [1/5]
QFixed QFixed::operator- (int i) const inline
Definition at line 90 of file qfixed_p.h.
 { QFixed f; f.val = (val - (i<<6)); return f; }
operator-() [2/5]
QFixed QFixed::operator- (uint i) const inline
Definition at line 91 of file qfixed_p.h.
 { QFixed f; f.val = (val - (i<<6)); return f; }
operator-() [3/5]
QFixed QFixed::operator- (const QFixed & other) const inline
Definition at line 92 of file qfixed_p.h.
 { QFixed f; f.val = (val - other.val); return f; }
operator-() [4/5]
QFixed QFixed::operator- () const inline
Definition at line 96 of file qfixed_p.h.
 { QFixed f; f.val = -val; return f; }
operator-() [5/5]
QFixed QFixed::operator- (qreal i) const inline private
Definition at line 148 of file qfixed_p.h.
 { QFixed f; f.val = (val - (int)(i*qreal(64))); return f; }
operator-=() [1/4]
QFixed& QFixed::operator-= (int i) inline
Definition at line 93 of file qfixed_p.h.
 { val -= (i<<6); return *this; }
operator-=() [2/4]
QFixed& QFixed::operator-= (uint i) inline
Definition at line 94 of file qfixed_p.h.
 { val -= (i<<6); return *this; }
operator-=() [3/4]
QFixed& QFixed::operator-= (const QFixed & other) inline
Definition at line 95 of file qfixed_p.h.
 { val -= other.val; return *this; }
operator-=() [4/4]
QFixed& QFixed::operator-= (qreal i) inline private
Definition at line 149 of file qfixed_p.h.
 { val -= (int)(i*64); return *this; }
operator/() [1/3]
QFixed QFixed::operator/ (int d) const inline
Definition at line 123 of file qfixed_p.h.
 { QFixed f; f.val = val/d; return f; }
operator/() [2/3]
QFixed QFixed::operator/ (QFixed b) const inline
Definition at line 124 of file qfixed_p.h.
 { QFixed f = *this; return (f /= b); }
operator/() [3/3]
QFixed QFixed::operator/ (qreal d) const inline private
Definition at line 151 of file qfixed_p.h.
 { QFixed f; f.val = (int)(val/d); return f; }
operator/=() [1/3]
QFixed& QFixed::operator/= (int x) inline
Definition at line 106 of file qfixed_p.h.
 { val /= x; return *this; }
operator/=() [2/3]
QFixed& QFixed::operator/= (const QFixed & o) inline
Definition at line 107 of file qfixed_p.h.
{
         if (o.val == 0) {
             val = 0x7FFFFFFFL;
         } else {
             bool neg = false;
             qint64 a = val;
             qint64 b = o.val;
             if (a < 0) { a = -a; neg = true; }
             if (b < 0) { b = -b; neg = !neg; }
             int res = (int)(((a << 6) + (b >> 1)) / b);
             val = (neg ? -res : res);
         }
         return *this;
     }
operator/=() [3/3]
QFixed& QFixed::operator/= (qreal r) inline private
Definition at line 150 of file qfixed_p.h.
 { val = (int)(val/r); return *this; }
operator<()
bool QFixed::operator< (const QFixed & other) const inline
Definition at line 100 of file qfixed_p.h.
 { return val < other.val; }
operator<=()
bool QFixed::operator<= (const QFixed & other) const inline
Definition at line 102 of file qfixed_p.h.
 { return val <= other.val; }
operator=() [1/3]
QFixed& QFixed::operator= (int i) inline
Definition at line 67 of file qfixed_p.h.
 { val = (i<<6); return *this; }
operator=() [2/3]
QFixed& QFixed::operator= (long i) inline
Definition at line 68 of file qfixed_p.h.
 { val = (i<<6); return *this; }
operator=() [3/3]
QFixed& QFixed::operator= (qreal i) inline private
Definition at line 145 of file qfixed_p.h.
 { val = (int)(i*qreal(64)); return *this; }
operator==()
bool QFixed::operator== (const QFixed & other) const inline
Definition at line 98 of file qfixed_p.h.
 { return val == other.val; }
operator>()
bool QFixed::operator> (const QFixed & other) const inline
Definition at line 101 of file qfixed_p.h.
 { return val > other.val; }
operator>=()
bool QFixed::operator>= (const QFixed & other) const inline
Definition at line 103 of file qfixed_p.h.
 { return val >= other.val; }
operator>>()
QFixed QFixed::operator>> (int d) const inline
Definition at line 125 of file qfixed_p.h.
 { QFixed f = *this; f.val >>= d; return f; }
round()
QFixed QFixed::round () const inline
Definition at line 80 of file qfixed_p.h.
Referenced by QFontEngineMac::ascent(), QFontEngineDirectWrite::ascent(), atsuPostLayoutCallback(), QFontEngineMac::averageCharWidth(), QFontEngineMac::boundingBox(), QFontEngineDirectWrite::boundingBox(), QFontEngineFT::boundingBox(), QFontEngineMac::descent(), QVGPaintEngine::drawCachedGlyphs(), QFontEngineMac::leading(), QFontEngineDirectWrite::leading(), QFontEngineMac::recalcAdvances(), QFontEngineDirectWrite::recalcAdvances(), QFontEngineFT::recalcAdvances(), QFontEngineMac::xHeight(), and QFontEngineDirectWrite::xHeight().
 { QFixed f; f.val = ((val)+32) & -64; return f; }
setValue()
void QFixed::setValue (int value) inline
Definition at line 74 of file qfixed_p.h.
 { val = value; }
toInt()
int QFixed::toInt () const inline
Definition at line 76 of file qfixed_p.h.
Referenced by QFontEngineXLFD::bitmapForGlyphs(), QFontEngineWin::drawGDIGlyph(), QFontEngineMac::getUnscaledGlyph(), QTextureGlyphCache::populate(), QTextEngine::positionInLigature(), and qRound().
 { return (((val)+32) & -64)>>6; }
toReal()
qreal QFixed::toReal () const inline
Definition at line 77 of file qfixed_p.h.
Referenced by QFontEngineDirectWrite::addGlyphsToPath(), QFontEngine::addGlyphsToPath(), addGlyphsToPathHelper(), QFontEngineXLFD::addOutlineToPath(), QFontEngineMulti::addOutlineToPath(), addSelectedRegionsToPath(), QPainterPath::addText(), QRawFont::advancesForGlyphIndexes(), QFontEngineDirectWrite::alphaMapBoundingBox(), QFontEngine::alphaMapForGlyph(), alphaMapFromPath(), QTextItem::ascent(), QRawFont::ascent(), QFontMetricsF::ascent(), QRawFont::averageCharWidth(), QFontMetricsF::averageCharWidth(), QFontEngineXLFD::bitmapForGlyphs(), QTextLayout::boundingRect(), QFontMetricsF::boundingRect(), QGLGlyphCache::cacheGlyphs(), QTextLine::cursorToX(), QTextItem::descent(), QRawFont::descent(), QFontMetricsF::descent(), QTextDocumentLayout::draw(), QFontEngineMac::draw(), QTextLine::draw(), QPaintEnginePrivate::drawBoxTextItem(), QVGPaintEngine::drawCachedGlyphs(), QTextDocumentLayoutPrivate::drawFrame(), QTextDocumentLayoutPrivate::drawFrameDecoration(), QPainterPrivate::drawGlyphs(), drawMenuText(), QTextDocumentLayoutPrivate::drawTableCell(), QPainter::drawText(), QEmulationPaintEngine::drawTextItem(), QPicturePaintEngine::drawTextItem(), QPdfEnginePrivate::drawTextItem(), QPdfBaseEnginePrivate::drawTextItem(), QPaintBufferEngine::drawTextItem(), QPainter::drawTextItem(), drawTextItemDecoration(), QPdfEnginePrivate::embedFont(), QVGFontEngineCleaner::fontEngineDestroyed(), QFontEngine::getGlyphBearings(), QFontEngine::getGlyphPositions(), QTextLine::glyphs(), QTextDocumentLayoutPrivate::hitTest(), QFontEngineMac::imageForGlyph(), QFontEngineDirectWrite::imageForGlyph(), QTextLine::layout_helper(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutFlow(), QTextDocumentLayoutPrivate::layoutFrame(), QRawFont::leading(), QFontMetricsF::leading(), QFont::letterSpacing(), QFontMetricsF::lineWidth(), QFontEngineFT::loadGlyph(), QTextLine::naturalTextRect(), operator<<(), QTextureGlyphCache::populate(), QPainterReplayer::process(), QFreetypeFace::properties(), QFontEngine::properties(), qt_draw_decoration_for_glyphs(), QTextInlineObject::rect(), QTextLine::rect(), QFontMetricsF::tightBoundingRect(), QFixedPoint::toPointF(), QFixedSize::toSizeF(), QFontSubset::toTruetype(), QFontSubset::type1AddedGlyphs(), QFontMetricsF::underlinePos(), QRawFont::unitsPerEm(), QTextItem::width(), QFontMetricsF::width(), QFont::wordSpacing(), QRawFont::xHeight(), and QFontMetricsF::xHeight().
 { return ((qreal)val)/(qreal)64; }
truncate()
int QFixed::truncate () const inline
Definition at line 79 of file qfixed_p.h.
Referenced by QTextDocumentLayoutPrivate::layoutTable(), QTextureGlyphCache::populate(), and qFloor().
 { return val>>6; }
value()
int QFixed::value () const inline
Definition at line 73 of file qfixed_p.h.
Referenced by QFontEngine::addBitmapFontToPath(), hb_getFontMetric(), hb_getGlyphMetrics(), QTextEngine::justify(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), setValue(), QTextEngine::shapeText(), QPAGenerator::writeTaggedQFixed(), and QPFGenerator::writeTaggedQFixed().
 { return val; }
Properties
val
int QFixed::val private
Definition at line 154 of file qfixed_p.h.
Referenced by ceil(), floor(), fromFixed(), fromReal(), operator!(), operator!=(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), operator>>(), round(), setValue(), toInt(), toReal(), truncate(), and value().
The documentation for this struct was generated from the following file:
/src/gui/painting/qfixed_p.h