Qt 4.8: QDeclarativeListModelWorkerAgent::Data Struct Reference
QDeclarativeListModelWorkerAgent::Data Struct Reference
Public Functions
void changedChange (int index, int count, const QList< int > &roles)
void clearChange ()
void insertChange (int index, int count)
void moveChange (int index, int count, int to)
void removeChange (int index, int count)
Public Variables
QList< Change > changes
Detailed Description
Definition at line 130 of file qdeclarativelistmodelworkeragent_p.h.
Functions
changedChange()
void QDeclarativeListModelWorkerAgent::Data::changedChange (int index, int count, const QList< int > & roles)
Definition at line 79 of file qdeclarativelistmodelworkeragent.cpp.
Referenced by QDeclarativeListModelWorkerAgent::changedData(), QDeclarativeListModelWorkerAgent::set(), and QDeclarativeListModelWorkerAgent::setProperty().
 {
     Change c = { Change::Changed, index, count, 0, roles };
     changes << c;
 }
clearChange()
void QDeclarativeListModelWorkerAgent::Data::clearChange ()
Definition at line 56 of file qdeclarativelistmodelworkeragent.cpp.
Referenced by QDeclarativeListModelWorkerAgent::clear().
 {
     changes.clear();
 }
insertChange()
void QDeclarativeListModelWorkerAgent::Data::insertChange (int index, int count)
Definition at line 61 of file qdeclarativelistmodelworkeragent.cpp.
Referenced by QDeclarativeListModelWorkerAgent::append(), and QDeclarativeListModelWorkerAgent::insert().
 {
     Change c = { Change::Inserted, index, count, 0, QList<int>() };
     changes << c;
 }
moveChange()
void QDeclarativeListModelWorkerAgent::Data::moveChange (int index, int count, int to)
Definition at line 73 of file qdeclarativelistmodelworkeragent.cpp.
Referenced by QDeclarativeListModelWorkerAgent::move().
 {
     Change c = { Change::Moved, index, count, to, QList<int>() };
     changes << c;
 }
removeChange()
void QDeclarativeListModelWorkerAgent::Data::removeChange (int index, int count)
Definition at line 67 of file qdeclarativelistmodelworkeragent.cpp.
Referenced by QDeclarativeListModelWorkerAgent::clear(), and QDeclarativeListModelWorkerAgent::remove().
 {
     Change c = { Change::Removed, index, count, 0, QList<int>() };
     changes << c;
 }
Properties
changes
QList<Change> QDeclarativeListModelWorkerAgent::Data::changes
Definition at line 131 of file qdeclarativelistmodelworkeragent_p.h.
Referenced by changedChange(), clearChange(), QDeclarativeListModelWorkerAgent::event(), insertChange(), moveChange(), removeChange(), and QDeclarativeListModelWorkerAgent::sync().
The documentation for this struct was generated from the following files:
/src/declarative/util/qdeclarativelistmodelworkeragent_p.h
/src/declarative/util/qdeclarativelistmodelworkeragent.cpp