Qt 4.8: QDeclarativeEnginePrivate::SimpleList< T > Struct Template Reference
QDeclarativeEnginePrivate::SimpleList< T > Struct Template Reference
#include <qdeclarativeengine_p.h>
Public Functions
void append (T *v)
T * at (int idx) const
void clear ()
SimpleList ()
SimpleList (int r)
Public Variables
int count
T ** values
Detailed Description
template<class T>
struct QDeclarativeEnginePrivate::SimpleList< T >
Definition at line 192 of file qdeclarativeengine_p.h.
Constructors and Destructors
SimpleList() [1/2]
template<class T> QDeclarativeEnginePrivate::SimpleList< T >::SimpleList () inline
Definition at line 193 of file qdeclarativeengine_p.h.
             : count(0), values(0) {}
SimpleList() [2/2]
template<class T> QDeclarativeEnginePrivate::SimpleList< T >::SimpleList (int r) inline
Definition at line 195 of file qdeclarativeengine_p.h.
             : count(0), values(new T*[r]) {}
Functions
append()
template<class T> void QDeclarativeEnginePrivate::SimpleList< T >::append (T * v) inline
Definition at line 201 of file qdeclarativeengine_p.h.
{
             values[count++] = v;
         }
at()
template<class T> T* QDeclarativeEnginePrivate::SimpleList< T >::at (int idx) const inline
Definition at line 205 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeEnginePrivate::clear(), and QDeclarativeComponentPrivate::complete().
{
             return values[idx];
         }
clear()
template<class T> void QDeclarativeEnginePrivate::SimpleList< T >::clear () inline
Definition at line 209 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeEnginePrivate::clear().
                      {
             delete [] values;
         }
Properties
count
template<class T> int QDeclarativeEnginePrivate::SimpleList< T >::count
Definition at line 198 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeEnginePrivate::clear(), and QDeclarativeComponentPrivate::complete().
values
template<class T> T** QDeclarativeEnginePrivate::SimpleList< T >::values
Definition at line 199 of file qdeclarativeengine_p.h.
The documentation for this struct was generated from the following file:
/src/declarative/qml/qdeclarativeengine_p.h