Qt 4.8: QAbstractConcatenable Struct Reference
QAbstractConcatenable Struct Reference
#include <qstringbuilder.h>
Static Protected Functions
static void convertFromAscii (const char *a, int len, QChar *&out)
static void convertFromAscii (char a, QChar *&out)
static void convertToAscii (const QChar *a, int len, char *&out)
static void convertToAscii (QChar a, char *&out)
static void convertToLatin1 (QChar a, char *&out)
Detailed Description
Definition at line 78 of file qstringbuilder.h.
Functions
convertFromAscii() [1/2]
void QAbstractConcatenable::convertFromAscii (const char * a, int len, QChar *& out) static protected
Warning
This function is not part of the public interface. Note: The len contains the ending \0
Definition at line 175 of file qstringbuilder.cpp.
Referenced by QConcatenable< char >::appendTo(), QConcatenable< char[N]>::appendTo(), QConcatenable< const char[N]>::appendTo(), QConcatenable< const char * >::appendTo(), and QConcatenable< QByteArray >::appendTo().
 {
 #ifndef QT_NO_TEXTCODEC
     if (QString::codecForCStrings && len) {
         QString tmp = QString::fromAscii(a, len > 0 ? len - 1 : -1);
         memcpy(out, reinterpret_cast<const char *>(tmp.constData()), sizeof(QChar) * tmp.size());
         out += tmp.length();
         return;
     }
 #endif
     if (len == -1) {
         if (!a)
             return;
         while (*a)
             *out++ = QLatin1Char(*a++);
     } else {
         for (int i = 0; i < len - 1; ++i)
             *out++ = QLatin1Char(a[i]);
     }
 }
convertFromAscii() [2/2]
static void QAbstractConcatenable::convertFromAscii (char a, QChar *& out) inline static protected
Definition at line 83 of file qstringbuilder.h.
     {
 #ifndef QT_NO_TEXTCODEC
         if (QString::codecForCStrings)
             *out++ = QChar::fromAscii(a);
         else
 #endif
             *out++ = QLatin1Char(a);
     }
convertToAscii() [1/2]
void QAbstractConcatenable::convertToAscii (const QChar * a, int len, char *& out) static protected
Warning
This function is not part of the public interface.
Definition at line 197 of file qstringbuilder.cpp.
 {
 #ifndef QT_NO_TEXTCODEC
     if (QString::codecForCStrings) {
         QByteArray tmp = QString::codecForCStrings->fromUnicode(a, len);
         memcpy(out, tmp.constData(), tmp.size());
         out += tmp.length();
         return;
     }
 #endif
     if (len == -1) {
         while (a->unicode())
             convertToLatin1(*a++, out);
     } else {
         for (int i = 0; i < len; ++i)
             convertToLatin1(a[i], out);
     }
 }
convertToAscii() [2/2]
static void QAbstractConcatenable::convertToAscii (QChar a, char *& out) inline static protected
Definition at line 93 of file qstringbuilder.h.
     {
 #ifndef QT_NO_TEXTCODEC
         if (QString::codecForCStrings)
             *out++ = a.toAscii(); //###
         else
 #endif
             convertToLatin1(a, out);
     }
convertToLatin1()
static void QAbstractConcatenable::convertToLatin1 (QChar a, char *& out) inline static protected
Definition at line 103 of file qstringbuilder.h.
Referenced by convertToAscii().
     {
         *out++ = a.unicode() > 0xff ? '?' : char(a.unicode());
     }
The documentation for this struct was generated from the following files:
/src/corelib/tools/qstringbuilder.h
/src/corelib/tools/qstringbuilder.cpp