Qt 4.8: QUtf8 Struct Reference
QUtf8 Struct Reference
#include <qutfcodec_p.h>
Static Public Functions
static QByteArray convertFromUnicode (const QChar *, int, QTextCodec::ConverterState *)
static QString convertToUnicode (const char *, int, QTextCodec::ConverterState *)
Detailed Description
Definition at line 68 of file qutfcodec_p.h.
Functions
convertFromUnicode()
QByteArray QUtf8::convertFromUnicode (const QChar * uc, int len, QTextCodec::ConverterState * state) static
Definition at line 64 of file qutfcodec.cpp.
Referenced by QUtf8Codec::convertFromUnicode(), QUtf16Codec::QUtf16Codec(), QUtf32Codec::QUtf32Codec(), QString::toUtf8(), and QStringRef::toUtf8().
 {
     uchar replacement = '?';
     int rlen = 3*len;
     int surrogate_high = -1;
     if (state) {
         if (state->flags & QTextCodec::ConvertInvalidToNull)
             replacement = 0;
         if (!(state->flags & QTextCodec::IgnoreHeader))
             rlen += 3;
         if (state->remainingChars)
             surrogate_high = state->state_data[0];
     }
     QByteArray rstr;
     rstr.resize(rlen);
     uchar* cursor = (uchar*)rstr.data();
     const QChar *ch = uc;
     int invalid = 0;
     if (state && !(state->flags & QTextCodec::IgnoreHeader)) {
         *cursor++ = 0xef;
         *cursor++ = 0xbb;
         *cursor++ = 0xbf;
     }
     const QChar *end = ch + len;
     while (ch < end) {
         uint u = ch->unicode();
         if (surrogate_high >= 0) {
             if (ch->isLowSurrogate()) {
                 u = QChar::surrogateToUcs4(surrogate_high, u);
                 surrogate_high = -1;
             } else {
                 // high surrogate without low
                 *cursor = replacement;
                 ++ch;
                 ++invalid;
                 surrogate_high = -1;
                 continue;
             }
         } else if (ch->isLowSurrogate()) {
             // low surrogate without high
             *cursor = replacement;
             ++ch;
             ++invalid;
             continue;
         } else if (ch->isHighSurrogate()) {
             surrogate_high = u;
             ++ch;
             continue;
         }
         if (u < 0x80) {
             *cursor++ = (uchar)u;
         } else {
             if (u < 0x0800) {
                 *cursor++ = 0xc0 | ((uchar) (u >> 6));
             } else {
                 // is it one of the Unicode non-characters?
                 if (isUnicodeNonCharacter(u)) {
                     *cursor++ = replacement;
                     ++ch;
                     ++invalid;
                     continue;
                 }
                 if (u > 0xffff) {
                     *cursor++ = 0xf0 | ((uchar) (u >> 18));
                     *cursor++ = 0x80 | (((uchar) (u >> 12)) & 0x3f);
                 } else {
                     *cursor++ = 0xe0 | (((uchar) (u >> 12)) & 0x3f);
                 }
                 *cursor++ = 0x80 | (((uchar) (u >> 6)) & 0x3f);
             }
             *cursor++ = 0x80 | ((uchar) (u&0x3f));
         }
         ++ch;
     }
     rstr.resize(cursor - (const uchar*)rstr.constData());
     if (state) {
         state->invalidChars += invalid;
         state->flags |= QTextCodec::IgnoreHeader;
         state->remainingChars = 0;
         if (surrogate_high >= 0) {
             state->remainingChars = 1;
             state->state_data[0] = surrogate_high;
         }
     }
     return rstr;
 }
convertToUnicode()
QString QUtf8::convertToUnicode (const char * chars, int len, QTextCodec::ConverterState * state) static
Definition at line 156 of file qutfcodec.cpp.
Referenced by QUtf8Codec::convertToUnicode(), QString::fromUtf8(), QUtf16Codec::QUtf16Codec(), and QUtf32Codec::QUtf32Codec().
 {
     bool headerdone = false;
     ushort replacement = QChar::ReplacementCharacter;
     int need = 0;
     int error = -1;
     uint uc = 0;
     uint min_uc = 0;
     if (state) {
         if (state->flags & QTextCodec::IgnoreHeader)
             headerdone = true;
         if (state->flags & QTextCodec::ConvertInvalidToNull)
             replacement = QChar::Null;
         need = state->remainingChars;
         if (need) {
             uc = state->state_data[0];
             min_uc = state->state_data[1];
         }
     }
     if (!headerdone && len > 3
         && (uchar)chars[0] == 0xef && (uchar)chars[1] == 0xbb && (uchar)chars[2] == 0xbf) {
         // starts with a byte order mark
         chars += 3;
         len -= 3;
         headerdone = true;
     }
     QString result(need + len + 1, Qt::Uninitialized); // worst case
     ushort *qch = (ushort *)result.unicode();
     uchar ch;
     int invalid = 0;
     for (int i = 0; i < len; ++i) {
         ch = chars[i];
         if (need) {
             if ((ch&0xc0) == 0x80) {
                 uc = (uc << 6) | (ch & 0x3f);
                 --need;
                 if (!need) {
                     // utf-8 bom composes into 0xfeff code point
                     bool nonCharacter;
                     if (!headerdone && uc == 0xfeff) {
                         // don't do anything, just skip the BOM
                     } else if (!(nonCharacter = isUnicodeNonCharacter(uc)) && uc > 0xffff && uc < 0x110000) {
                         // surrogate pair
                         Q_ASSERT((qch - (ushort*)result.unicode()) + 2 < result.length());
                         *qch++ = QChar::highSurrogate(uc);
                         *qch++ = QChar::lowSurrogate(uc);
                     } else if ((uc < min_uc) || (uc >= 0xd800 && uc <= 0xdfff) || nonCharacter || uc >= 0x110000) {
                         // error: overlong sequence, UTF16 surrogate or non-character
                         *qch++ = replacement;
                         ++invalid;
                     } else {
                         *qch++ = uc;
                     }
                     headerdone = true;
                 }
             } else {
                 // error
                 i = error;
                 *qch++ = replacement;
                 ++invalid;
                 need = 0;
                 headerdone = true;
             }
         } else {
             if (ch < 128) {
                 *qch++ = ushort(ch);
                 headerdone = true;
             } else if ((ch & 0xe0) == 0xc0) {
                 uc = ch & 0x1f;
                 need = 1;
                 error = i;
                 min_uc = 0x80;
                 headerdone = true;
             } else if ((ch & 0xf0) == 0xe0) {
                 uc = ch & 0x0f;
                 need = 2;
                 error = i;
                 min_uc = 0x800;
             } else if ((ch&0xf8) == 0xf0) {
                 uc = ch & 0x07;
                 need = 3;
                 error = i;
                 min_uc = 0x10000;
                 headerdone = true;
             } else {
                 // error
                 *qch++ = replacement;
                 ++invalid;
                 headerdone = true;
             }
         }
     }
     if (!state && need > 0) {
         // unterminated UTF sequence
         for (int i = error; i < len; ++i) {
             *qch++ = replacement;
             ++invalid;
         }
     }
     result.truncate(qch - (ushort *)result.unicode());
     if (state) {
         state->invalidChars += invalid;
         state->remainingChars = need;
         if (headerdone)
             state->flags |= QTextCodec::IgnoreHeader;
         state->state_data[0] = need ? uc : 0;
         state->state_data[1] = need ? min_uc : 0;
     }
     return result;
 }
The documentation for this struct was generated from the following files:
/src/corelib/codecs/qutfcodec_p.h
/src/corelib/codecs/qutfcodec.cpp