Qt 4.8: SourceOnlyAlpha Struct Reference
SourceOnlyAlpha Struct Reference
Public Functions
uchar alpha (uchar src) const
quint16 bytemul (quint16 spix) const
Detailed Description
Definition at line 47 of file qblendfunctions.cpp.
Functions
alpha()
uchar SourceOnlyAlpha::alpha (uchar src) const inline
Definition at line 49 of file qblendfunctions.cpp.
Referenced by qt_blend_argb24_on_rgb16(), qt_blend_argb32_on_rgb16(), qt_blend_argb32_on_rgb16_const_alpha(), qt_blend_rgb16_on_rgb16(), Blend_ARGB24_on_RGB16_SourceAlpha::write(), Blend_ARGB24_on_RGB16_SourceAndConstAlpha::write(), Blend_ARGB32_on_RGB16_SourceAlpha::write(), and Blend_ARGB32_on_RGB16_SourceAndConstAlpha::write().
 { return src; }
bytemul()
quint16 SourceOnlyAlpha::bytemul (quint16 spix) const inline
Definition at line 50 of file qblendfunctions.cpp.
 { return spix; }
The documentation for this struct was generated from the following file:
/src/gui/painting/qblendfunctions.cpp