Qt 4.8: QBidiControl Struct Reference
QBidiControl Struct Reference
Public Functions
unsigned int baseLevel () const
QChar::Direction basicDirection () const
bool canPop () const
QChar::Direction direction () const
void embed (bool rtl, bool o=false)
void pdf ()
QBidiControl (bool rtl)
Public Variables
const unsigned int base
unsigned int cCtx
struct {
unsigned int level
bool override
} ctx [MaxBidiLevel]
Detailed Description
Definition at line 256 of file qtextengine.cpp.
Constructors and Destructors
QBidiControl()
QBidiControl::QBidiControl (bool rtl) inline
Definition at line 257 of file qtextengine.cpp.
         : cCtx(0), base(rtl ? 1 : 0), level(rtl ? 1 : 0), override(false) {}
Functions
baseLevel()
unsigned int QBidiControl::baseLevel () const inline
Definition at line 284 of file qtextengine.cpp.
Referenced by QTextEngine::itemize().
{
         return base;
     }
basicDirection()
QChar::Direction QBidiControl::basicDirection () const inline
Definition at line 281 of file qtextengine.cpp.
Referenced by bidiItemize(), and skipBoundryNeutrals().
{
         return (base ? QChar::DirR : QChar:: DirL);
     }
canPop()
bool QBidiControl::canPop () const inline
Definition at line 273 of file qtextengine.cpp.
Referenced by bidiItemize().
 { return cCtx != 0; }
direction()
QChar::Direction QBidiControl::direction () const inline
Definition at line 287 of file qtextengine.cpp.
Referenced by bidiItemize().
{
         return ((level%2) ? QChar::DirR : QChar:: DirL);
     }
embed()
void QBidiControl::embed (bool rtl, bool o = false) inline
Definition at line 260 of file qtextengine.cpp.
Referenced by bidiItemize().
{
         unsigned int toAdd = 1;
         if((level%2 != 0) == rtl ) {
             ++toAdd;
         }
         if (level + toAdd <= MaxBidiLevel) {
             ctx[cCtx].level = level;
             ctx[cCtx].override = override;
             cCtx++;
             override = o;
             level += toAdd;
         }
     }
pdf()
void QBidiControl::pdf () inline
Definition at line 274 of file qtextengine.cpp.
Referenced by bidiItemize().
                       {
         Q_ASSERT(cCtx);
         --cCtx;
         level = ctx[cCtx].level;
         override = ctx[cCtx].override;
     }
Properties
base
const unsigned int QBidiControl::base
Definition at line 296 of file qtextengine.cpp.
cCtx
unsigned int QBidiControl::cCtx
Definition at line 295 of file qtextengine.cpp.
ctx
struct { ... } QBidiControl::ctx[MaxBidiLevel]
level
unsigned int QBidiControl::level
Definition at line 292 of file qtextengine.cpp.
Referenced by appendItems(), bidiItemize(), and skipBoundryNeutrals().
override
bool QBidiControl::override
Definition at line 293 of file qtextengine.cpp.
Referenced by appendItems(), and bidiItemize().
The documentation for this struct was generated from the following file:
/src/gui/text/qtextengine.cpp