Qt 4.8: QAxMetaObject Struct Reference
QAxMetaObject Struct Reference
Public Functions
DISPID dispIDofName (const QByteArray &name, IDispatch *disp)
int numParameter (const QByteArray &prototype)
QByteArray paramType (const QByteArray &signature, int index, bool *out=0)
void parsePrototype (const QByteArray &prototype)
QByteArray propertyType (const QByteArray &propertyName)
QAxMetaObject ()
~QAxMetaObject ()
Public Functions inherited from QMetaObject
QObject * cast (QObject *obj) const
Returns obj if object obj inherits from this meta-object; otherwise returns 0.
const QObject * cast (const QObject *obj) const
Returns obj if object obj inherits from this meta-object; otherwise returns 0.
QMetaClassInfo classInfo (int index) const
Returns the meta-data for the item of class information with the given index.
int classInfoCount () const
Returns the number of items of class information in this class.
int classInfoOffset () const
Returns the class information offset for this class; i.e.
const char * className () const
Returns the class name.
QMetaMethod constructor (int index) const
Returns the meta-data for the constructor with the given index.
int constructorCount () const
Returns the number of constructors in this class.
QMetaEnum enumerator (int index) const
Returns the meta-data for the enumerator with the given index.
int enumeratorCount () const
Returns the number of enumerators in this class.
int enumeratorOffset () const
Returns the enumerator offset for this class; i.e.
int indexOfClassInfo (const char *name) const
Finds class information item name and returns its index; otherwise returns -1.
int indexOfConstructor (const char *constructor) const
Finds constructor and returns its index; otherwise returns -1.
int indexOfEnumerator (const char *name) const
Finds enumerator name and returns its index; otherwise returns -1.
int indexOfMethod (const char *method) const
Finds method and returns its index; otherwise returns -1.
int indexOfProperty (const char *name) const
Finds property name and returns its index; otherwise returns -1.
int indexOfSignal (const char *signal) const
Finds signal and returns its index; otherwise returns -1.
int indexOfSlot (const char *slot) const
Finds slot and returns its index; otherwise returns -1.
QMetaMethod method (int index) const
Returns the meta-data for the method with the given index.
int methodCount () const
Returns the number of methods known to the meta-object system in this class, including the number of properties provided by each base class.
int methodOffset () const
Returns the method offset for this class; i.e.
QObject * newInstance (QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument()) const
Constructs a new instance of this class.
QMetaProperty property (int index) const
Returns the meta-data for the property with the given index.
int propertyCount () const
Returns the number of properties in this class, including the number of properties provided by each base class.
int propertyOffset () const
Returns the property offset for this class; i.e.
int static_metacall (Call, int, void **) const
const QMetaObject * superClass () const
Returns the meta-object of the superclass, or 0 if there is no such object.
QString tr (const char *s, const char *c) const
QString tr (const char *s, const char *c, int n) const
QString trUtf8 (const char *s, const char *c) const
QString trUtf8 (const char *s, const char *c, int n) const
QMetaProperty userProperty () const
Returns the property that has the USER flag set to true.
Properties
QList< QUuid > connectionInterfaces
QHash< QByteArray, DISPID > dispIDs
QHash< QByteArray, QList< QByteArray > > memberInfo
QMap< QUuid, QMap< DISPID, QByteArray > > props
QMap< QUuid, QMap< DISPID, QByteArray > > propsigs
QMap< QByteArray, QByteArray > realPrototype
QMap< QUuid, QMap< DISPID, QByteArray > > sigs
Friends
class MetaObjectGenerator
Additional Inherited Members
Public Types inherited from QMetaObject
enum Call {
InvokeMetaMethod, ReadProperty, WriteProperty, ResetProperty,
QueryPropertyDesignable, QueryPropertyScriptable, QueryPropertyStored, QueryPropertyEditable,
QueryPropertyUser, CreateInstance
}
Static Public Functions inherited from QMetaObject
static void activate (QObject *sender, int signal_index, void **argv)
static void activate (QObject *sender, int from_signal_index, int to_signal_index, void **argv)
static void activate (QObject *sender, const QMetaObject *, int local_signal_index, void **argv)
static void activate (QObject *sender, const QMetaObject *, int from_local_signal_index, int to_local_signal_index, void **argv)
static void addGuard (QObject **ptr)
static void changeGuard (QObject **ptr, QObject *o)
static bool checkConnectArgs (const char *signal, const char *method)
Returns true if the signal and method arguments are compatible; otherwise returns false.
static bool connect (const QObject *sender, int signal_index, const QObject *receiver, int method_index, int type=0, int *types=0)
static void connectSlotsByName (QObject *o)
Searches recursively for all child objects of the given object, and connects matching signals from them to slots of object that follow the following form:
static bool disconnect (const QObject *sender, int signal_index, const QObject *receiver, int method_index)
static bool disconnectOne (const QObject *sender, int signal_index, const QObject *receiver, int method_index)
static bool invokeMethod (QObject *obj, const char *member, Qt::ConnectionType, QGenericReturnArgument ret, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
Invokes the member (a signal or a slot name) on the object obj.
static bool invokeMethod (QObject *obj, const char *member, QGenericReturnArgument ret, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
static bool invokeMethod (QObject *obj, const char *member, Qt::ConnectionType type, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
static bool invokeMethod (QObject *obj, const char *member, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
static int metacall (QObject *, Call, int, void **)
static QByteArray normalizedSignature (const char *method)
Normalizes the signature of the given method.
static QByteArray normalizedType (const char *type)
Normalizes a type.
static void removeGuard (QObject **ptr)
Public Variables inherited from QMetaObject
struct {
const uint * data
const void * extradata
const char * stringdata
const QMetaObject * superdata
} d
Detailed Description
Definition at line 77 of file qaxbase.cpp.
Constructors and Destructors
QAxMetaObject()
QAxMetaObject::QAxMetaObject () inline
Definition at line 79 of file qaxbase.cpp.
Referenced by QAxBasePrivate::metaObject().
     {
         d.data = 0;
         d.stringdata = 0;
     }
~QAxMetaObject()
QAxMetaObject::~QAxMetaObject () inline
Definition at line 84 of file qaxbase.cpp.
     {
         delete [] (int*)d.data;
         delete [] (char*)d.stringdata;
     }
Functions
dispIDofName()
DISPID QAxMetaObject::dispIDofName (const QByteArray & name, IDispatch * disp) inline
Definition at line 168 of file qaxbase.cpp.
Referenced by QAxBase::dynamicCallHelper(), QAxBase::internalInvoke(), QAxBase::internalProperty(), and ~QAxMetaObject().
 {
     DISPID dispid = dispIDs.value(name, DISPID_UNKNOWN);
     if (dispid == DISPID_UNKNOWN) {
         // get the Dispatch ID from the object
         QString unicodeName = QLatin1String(name);
         OLECHAR *names = (wchar_t*)unicodeName.utf16();
         disp->GetIDsOfNames(IID_NULL, &names, 1, LOCALE_USER_DEFAULT, &dispid);
         if (dispid != DISPID_UNKNOWN)
             dispIDs.insert(name, dispid);
     }
     return dispid;
 }
numParameter()
int QAxMetaObject::numParameter (const QByteArray & prototype)
Definition at line 134 of file qaxbase.cpp.
Referenced by QAxBase::dynamicCallHelper(), QAxBase::internalInvoke(), QAxEventSink::Invoke(), and ~QAxMetaObject().
 {
     if (!memberInfo.contains(prototype))
         parsePrototype(prototype);
     return memberInfo.value(prototype).count();
 }
paramType()
QByteArray QAxMetaObject::paramType (const QByteArray & signature, int index, bool * out = 0)
Definition at line 142 of file qaxbase.cpp.
Referenced by QAxBase::dynamicCallHelper(), QAxBase::internalInvoke(), QAxEventSink::Invoke(), and ~QAxMetaObject().
 {
     if (!memberInfo.contains(prototype))
         parsePrototype(prototype);
     if (out)
         *out = false;
     QList<QByteArray> plist = memberInfo.value(prototype);
     if (index > plist.count() - 1)
         return QByteArray();
     QByteArray param(plist.at(index));
     if (param.isEmpty())
         return QByteArray();
     bool byRef = param.endsWith('&') || param.endsWith("**");
     if (byRef) {
         param.truncate(param.length() - 1);
         if (out)
             *out = true;
     }
     return param;
 }
parsePrototype()
void QAxMetaObject::parsePrototype (const QByteArray & prototype)
Definition at line 115 of file qaxbase.cpp.
Referenced by numParameter(), paramType(), and ~QAxMetaObject().
 {
     QByteArray realProto = realPrototype.value(prototype, prototype);
     QByteArray parameters = realProto.mid(realProto.indexOf('(') + 1);
     parameters.truncate(parameters.length() - 1);
     if (parameters.isEmpty()) {
         memberInfo.insert(prototype, QList<QByteArray>());
     } else {
         QList<QByteArray> plist = parameters.split(',');
         memberInfo.insert(prototype, plist);
     }
 }
propertyType()
QByteArray QAxMetaObject::propertyType (const QByteArray & propertyName) inline
Definition at line 129 of file qaxbase.cpp.
Referenced by MetaObjectGenerator::addProperty(), QAxBase::internalProperty(), and ~QAxMetaObject().
 {
     return realPrototype.value(propertyName);
 }
Friends and Related Functions
MetaObjectGenerator
friend class MetaObjectGenerator friend
Definition at line 97 of file qaxbase.cpp.
Properties
connectionInterfaces
QList<QUuid> QAxMetaObject::connectionInterfaces private
Definition at line 99 of file qaxbase.cpp.
Referenced by MetaObjectGenerator::metaObject(), and MetaObjectGenerator::tryCache().
dispIDs
QHash<QByteArray, DISPID> QAxMetaObject::dispIDs private
Definition at line 112 of file qaxbase.cpp.
Referenced by dispIDofName().
memberInfo
QHash<QByteArray, QList<QByteArray> > QAxMetaObject::memberInfo private
Definition at line 108 of file qaxbase.cpp.
Referenced by numParameter(), paramType(), and parsePrototype().
props
QMap< QUuid, QMap<DISPID, QByteArray> > QAxMetaObject::props private
Definition at line 105 of file qaxbase.cpp.
Referenced by QAxEventSink::addProperty(), QAxEventSink::findProperty(), MetaObjectGenerator::metaObject(), QAxEventSink::propertyMap(), and MetaObjectGenerator::tryCache().
propsigs
QMap< QUuid, QMap<DISPID, QByteArray> > QAxMetaObject::propsigs private
Definition at line 103 of file qaxbase.cpp.
Referenced by QAxEventSink::addProperty(), QAxEventSink::addSignal(), MetaObjectGenerator::metaObject(), QAxEventSink::OnChanged(), QAxEventSink::propSignalMap(), and MetaObjectGenerator::tryCache().
realPrototype
QMap<QByteArray, QByteArray> QAxMetaObject::realPrototype private
Definition at line 109 of file qaxbase.cpp.
Referenced by MetaObjectGenerator::metaObject(), parsePrototype(), and propertyType().
sigs
QMap< QUuid, QMap<DISPID, QByteArray> > QAxMetaObject::sigs private
Definition at line 101 of file qaxbase.cpp.
Referenced by QAxEventSink::addSignal(), QAxEventSink::Invoke(), MetaObjectGenerator::metaObject(), QAxEventSink::signalMap(), and MetaObjectGenerator::tryCache().
The documentation for this struct was generated from the following file:
/src/activeqt/container/qaxbase.cpp