Qt 4.8: QSystemLocalePrivate Struct Reference
QSystemLocalePrivate Struct Reference
Public Functions
QVariant amText ()
QVariant currencySymbol (QLocale::CurrencySymbolFormat)
QVariant dateFormat (QLocale::FormatType)
QVariant dateTimeFormat (QLocale::FormatType)
QVariant dayName (int, QLocale::FormatType)
QChar decimalPoint ()
QVariant firstDayOfWeek ()
QChar groupSeparator ()
QVariant measurementSystem ()
QVariant monthName (int, QLocale::FormatType)
QVariant nativeCountryName ()
QVariant nativeLanguageName ()
QChar negativeSign ()
QVariant pmText ()
QChar positiveSign ()
QSystemLocalePrivate ()
QVariant timeFormat (QLocale::FormatType)
QVariant toCurrencyString (const QSystemLocale::CurrencyToStringArgument &)
QVariant toString (const QDate &, QLocale::FormatType)
QVariant toString (const QTime &, QLocale::FormatType)
QVariant toString (const QDateTime &, QLocale::FormatType)
QVariant uiLanguages ()
void update ()
QChar zeroDigit ()
Private Types
enum SubstitutionType { SUnknown, SContext, SAlways, SNever }
Private Functions
QString getLocaleInfo (LCTYPE type, int maxlen=0)
int getLocaleInfo_int (LCTYPE type, int maxlen=0)
QChar getLocaleInfo_qchar (LCTYPE type)
QString & substituteDigits (QString &string)
SubstitutionType substitution ()
Static Private Functions
static QString winToQtFormat (const QString &sys_fmt)
Properties
QByteArray langEnvVar
LCID lcid
SubstitutionType substitutionType
QChar zero
Detailed Description
Definition at line 86 of file qlocale_win.cpp.
Enumerations
SubstitutionType
enum QSystemLocalePrivate::SubstitutionType private
Enumerator
SUnknown
SContext
SAlways
SNever
Definition at line 118 of file qlocale_win.cpp.
{
         SUnknown,
         SContext,
         SAlways,
         SNever
     };
Constructors and Destructors
QSystemLocalePrivate()
QSystemLocalePrivate::QSystemLocalePrivate ()
Definition at line 142 of file qlocale_win.cpp.
     : substitutionType(SUnknown)
 {
     langEnvVar = qgetenv("LANG");
     lcid = GetUserDefaultLCID();
 }
Functions
amText()
QVariant QSystemLocalePrivate::amText ()
Definition at line 387 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     wchar_t output[15]; // maximum length including  terminating zero character for Win2003+
     if (GetLocaleInfo(lcid, LOCALE_S1159, output, 15)) {
         return QString::fromWCharArray(output);
     }
     return QVariant();
 }
currencySymbol()
QVariant QSystemLocalePrivate::currencySymbol (QLocale::CurrencySymbolFormat format)
Definition at line 419 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     wchar_t buf[13];
     switch (format) {
     case QLocale::CurrencySymbol:
         if (GetLocaleInfo(lcid, LOCALE_SCURRENCY, buf, 13))
             return QString::fromWCharArray(buf);
         break;
     case QLocale::CurrencyIsoCode:
         if (GetLocaleInfo(lcid, LOCALE_SINTLSYMBOL, buf, 9))
             return QString::fromWCharArray(buf);
         break;
     case QLocale::CurrencyDisplayName: {
         QVarLengthArray<wchar_t, 64> buf(64);
         if (!GetLocaleInfo(lcid, LOCALE_SNATIVECURRNAME, buf.data(), buf.size())) {
             if (GetLastError() != ERROR_INSUFFICIENT_BUFFER)
                 break;
             buf.resize(255); // should be large enough, right?
             if (!GetLocaleInfo(lcid, LOCALE_SNATIVECURRNAME, buf.data(), buf.size()))
                 break;
         }
         return QString::fromWCharArray(buf.data());
     }
     default:
         break;
     }
     return QVariant();
 }
dateFormat()
QVariant QSystemLocalePrivate::dateFormat (QLocale::FormatType type)
Definition at line 247 of file qlocale_win.cpp.
Referenced by dateTimeFormat(), and winToQtFormat().
 {
     switch (type) {
     case QLocale::ShortFormat:
         return winToQtFormat(getLocaleInfo(LOCALE_SSHORTDATE));
     case QLocale::LongFormat:
         return winToQtFormat(getLocaleInfo(LOCALE_SLONGDATE));
     case QLocale::NarrowFormat:
         break;
     }
     return QVariant();
 }
dateTimeFormat()
QVariant QSystemLocalePrivate::dateTimeFormat (QLocale::FormatType type)
Definition at line 273 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     return QString(dateFormat(type).toString() + QLatin1Char(' ') + timeFormat(type).toString());
 }
dayName()
QVariant QSystemLocalePrivate::dayName (int day, QLocale::FormatType type)
Definition at line 278 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     static const LCTYPE short_day_map[]
         = { LOCALE_SABBREVDAYNAME1, LOCALE_SABBREVDAYNAME2,
             LOCALE_SABBREVDAYNAME3, LOCALE_SABBREVDAYNAME4, LOCALE_SABBREVDAYNAME5,
             LOCALE_SABBREVDAYNAME6, LOCALE_SABBREVDAYNAME7 };
     static const LCTYPE long_day_map[]
         = { LOCALE_SDAYNAME1, LOCALE_SDAYNAME2,
             LOCALE_SDAYNAME3, LOCALE_SDAYNAME4, LOCALE_SDAYNAME5,
             LOCALE_SDAYNAME6, LOCALE_SDAYNAME7 };
     static const LCTYPE narrow_day_map[]
         = { LOCALE_SSHORTESTDAYNAME1, LOCALE_SSHORTESTDAYNAME2,
             LOCALE_SSHORTESTDAYNAME3, LOCALE_SSHORTESTDAYNAME4,
             LOCALE_SSHORTESTDAYNAME5, LOCALE_SSHORTESTDAYNAME6,
             LOCALE_SSHORTESTDAYNAME7 };
     day -= 1;
     if (type == QLocale::LongFormat)
         return getLocaleInfo(long_day_map[day]);
     else if (type == QLocale::NarrowFormat && QSysInfo::windowsVersion() >= QSysInfo::WV_VISTA)
         return getLocaleInfo(narrow_day_map[day]);
     return getLocaleInfo(short_day_map[day]);
 }
decimalPoint()
QChar QSystemLocalePrivate::decimalPoint ()
Definition at line 227 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     return getLocaleInfo_qchar(LOCALE_SDECIMAL);
 }
firstDayOfWeek()
QVariant QSystemLocalePrivate::firstDayOfWeek ()
Definition at line 409 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     wchar_t output[4]; // maximum length including  terminating zero character for Win2003+
     if (GetLocaleInfo(lcid, LOCALE_IFIRSTDAYOFWEEK, output, 4))
         return QString::fromWCharArray(output).toUInt()+1;
     return 1;
 }
getLocaleInfo()
QString QSystemLocalePrivate::getLocaleInfo (LCTYPE type, int maxlen = 0) private
Definition at line 149 of file qlocale_win.cpp.
Referenced by dateFormat(), dayName(), getLocaleInfo_int(), getLocaleInfo_qchar(), monthName(), nativeCountryName(), nativeLanguageName(), timeFormat(), and toCurrencyString().
 {
     QVarLengthArray<wchar_t, 64> buf(maxlen ? maxlen : 64);
     if (!GetLocaleInfo(lcid, type, buf.data(), buf.size()))
         return QString();
     if (GetLastError() == ERROR_INSUFFICIENT_BUFFER) {
         int cnt = GetLocaleInfo(lcid, type, 0, 0);
         if (cnt == 0)
             return QString();
         buf.resize(cnt);
         if (!GetLocaleInfo(lcid, type, buf.data(), buf.size()))
             return QString();
     }
     return QString::fromWCharArray(buf.data());
 }
getLocaleInfo_int()
int QSystemLocalePrivate::getLocaleInfo_int (LCTYPE type, int maxlen = 0) private
Definition at line 165 of file qlocale_win.cpp.
Referenced by toCurrencyString().
 {
     QString str = getLocaleInfo(type, maxlen);
     bool ok = false;
     int v = str.toInt(&ok);
     return ok ? v : 0;
 }
getLocaleInfo_qchar()
QChar QSystemLocalePrivate::getLocaleInfo_qchar (LCTYPE type) private
Definition at line 173 of file qlocale_win.cpp.
Referenced by decimalPoint(), groupSeparator(), negativeSign(), positiveSign(), and zeroDigit().
 {
     QString str = getLocaleInfo(type);
     return str.isEmpty() ? QChar() : str.at(0);
 }
groupSeparator()
QChar QSystemLocalePrivate::groupSeparator ()
Definition at line 232 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     return getLocaleInfo_qchar(LOCALE_STHOUSAND);
 }
measurementSystem()
QVariant QSystemLocalePrivate::measurementSystem ()
Definition at line 373 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     wchar_t output[2];
     if (GetLocaleInfo(lcid, LOCALE_IMEASURE, output, 2)) {
         QString iMeasure = QString::fromWCharArray(output);
         if (iMeasure == QLatin1String("1")) {
             return QLocale::ImperialSystem;
         }
     }
     return QLocale::MetricSystem;
 }
monthName()
QVariant QSystemLocalePrivate::monthName (int month, QLocale::FormatType type)
Definition at line 305 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     static const LCTYPE short_month_map[]
         = { LOCALE_SABBREVMONTHNAME1, LOCALE_SABBREVMONTHNAME2, LOCALE_SABBREVMONTHNAME3,
             LOCALE_SABBREVMONTHNAME4, LOCALE_SABBREVMONTHNAME5, LOCALE_SABBREVMONTHNAME6,
             LOCALE_SABBREVMONTHNAME7, LOCALE_SABBREVMONTHNAME8, LOCALE_SABBREVMONTHNAME9,
             LOCALE_SABBREVMONTHNAME10, LOCALE_SABBREVMONTHNAME11, LOCALE_SABBREVMONTHNAME12 };
     static const LCTYPE long_month_map[]
         = { LOCALE_SMONTHNAME1, LOCALE_SMONTHNAME2, LOCALE_SMONTHNAME3,
             LOCALE_SMONTHNAME4, LOCALE_SMONTHNAME5, LOCALE_SMONTHNAME6,
             LOCALE_SMONTHNAME7, LOCALE_SMONTHNAME8, LOCALE_SMONTHNAME9,
             LOCALE_SMONTHNAME10, LOCALE_SMONTHNAME11, LOCALE_SMONTHNAME12 };
     month -= 1;
     if (month < 0 || month > 11)
     return QString();
     LCTYPE lctype = (type == QLocale::ShortFormat || type == QLocale::NarrowFormat)
             ? short_month_map[month] : long_month_map[month];
     return getLocaleInfo(lctype);
 }
nativeCountryName()
QVariant QSystemLocalePrivate::nativeCountryName ()
Definition at line 577 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     if (QSysInfo::windowsVersion() < QSysInfo::WV_WINDOWS7)
         return getLocaleInfo(LOCALE_SNATIVECTRYNAME);
     return getLocaleInfo(LOCALE_SNATIVECOUNTRYNAME);
 }
nativeLanguageName()
QVariant QSystemLocalePrivate::nativeLanguageName ()
Definition at line 570 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     if (QSysInfo::windowsVersion() < QSysInfo::WV_WINDOWS7)
         return getLocaleInfo(LOCALE_SNATIVELANGNAME);
     return getLocaleInfo(LOCALE_SNATIVELANGUAGENAME);
 }
negativeSign()
QChar QSystemLocalePrivate::negativeSign ()
Definition at line 237 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     return getLocaleInfo_qchar(LOCALE_SNEGATIVESIGN);
 }
pmText()
QVariant QSystemLocalePrivate::pmText ()
Definition at line 398 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     wchar_t output[15]; // maximum length including  terminating zero character for Win2003+
     if (GetLocaleInfo(lcid, LOCALE_S2359, output, 15)) {
         return QString::fromWCharArray(output);
     }
     return QVariant();
 }
positiveSign()
QChar QSystemLocalePrivate::positiveSign ()
Definition at line 242 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     return getLocaleInfo_qchar(LOCALE_SPOSITIVESIGN);
 }
substituteDigits()
QString & QSystemLocalePrivate::substituteDigits (QString & string) private
Definition at line 209 of file qlocale_win.cpp.
Referenced by toCurrencyString(), and toString().
 {
     ushort zero = zeroDigit().unicode();
     ushort *qch = (ushort *)string.data();
     for (ushort *end = qch + string.size(); qch != end; ++qch) {
         if (*qch >= '0' && *qch <= '9')
             *qch = zero + (*qch - '0');
     }
     return string;
 }
substitution()
QSystemLocalePrivate::SubstitutionType QSystemLocalePrivate::substitution () private
Definition at line 179 of file qlocale_win.cpp.
Referenced by toCurrencyString(), and toString().
 {
     if (substitutionType == SUnknown) {
         wchar_t buf[8];
         if (!GetLocaleInfo(lcid, LOCALE_IDIGITSUBSTITUTION, buf, 8)) {
             substitutionType = QSystemLocalePrivate::SNever;
             return substitutionType;
         }
         if (buf[0] == '1')
             substitutionType = QSystemLocalePrivate::SNever;
         else if (buf[0] == '0')
             substitutionType = QSystemLocalePrivate::SContext;
         else if (buf[0] == '2')
             substitutionType = QSystemLocalePrivate::SAlways;
         else {
             wchar_t digits[11];
             if (!GetLocaleInfo(lcid, LOCALE_SNATIVEDIGITS, digits, 11)) {
                 substitutionType = QSystemLocalePrivate::SNever;
                 return substitutionType;
             }
             const wchar_t zero = digits[0];
             if (buf[0] == zero + 2)
                 substitutionType = QSystemLocalePrivate::SAlways;
             else
                 substitutionType = QSystemLocalePrivate::SNever;
         }
     }
     return substitutionType;
 }
timeFormat()
QVariant QSystemLocalePrivate::timeFormat (QLocale::FormatType type)
Definition at line 260 of file qlocale_win.cpp.
Referenced by dateTimeFormat(), and winToQtFormat().
 {
     switch (type) {
     case QLocale::ShortFormat:
         return winToQtFormat(getLocaleInfo(LOCALE_STIMEFORMAT)); //###
     case QLocale::LongFormat:
         return winToQtFormat(getLocaleInfo(LOCALE_STIMEFORMAT));
     case QLocale::NarrowFormat:
         break;
     }
     return QVariant();
 }
toCurrencyString()
QVariant QSystemLocalePrivate::toCurrencyString (const QSystemLocale::CurrencyToStringArgument & arg)
Definition at line 448 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     QString value;
     switch (arg.value.type()) {
     case QVariant::Int:
         value = QLocalePrivate::longLongToString(QLatin1Char('0'), QLatin1Char(','), QLatin1Char('+'), QLatin1Char('-'),
                                                  arg.value.toInt(), -1, 10, -1, QLocale::OmitGroupSeparator);
         break;
     case QVariant::UInt:
         value = QLocalePrivate::unsLongLongToString(QLatin1Char('0'), QLatin1Char(','), QLatin1Char('+'),
                                                     arg.value.toUInt(), -1, 10, -1, QLocale::OmitGroupSeparator);
         break;
     case QVariant::Double:
         value = QLocalePrivate::doubleToString(QLatin1Char('0'), QLatin1Char('+'), QLatin1Char('-'),
                                                QLatin1Char(' '), QLatin1Char(','), QLatin1Char('.'),
                                                arg.value.toDouble(), -1, QLocalePrivate::DFDecimal, -1, QLocale::OmitGroupSeparator);
         break;
     case QVariant::LongLong:
         value = QLocalePrivate::longLongToString(QLatin1Char('0'), QLatin1Char(','), QLatin1Char('+'), QLatin1Char('-'),
                                                  arg.value.toLongLong(), -1, 10, -1, QLocale::OmitGroupSeparator);
         break;
     case QVariant::ULongLong:
         value = QLocalePrivate::unsLongLongToString(QLatin1Char('0'), QLatin1Char(','), QLatin1Char('+'),
                                                     arg.value.toULongLong(), -1, 10, -1, QLocale::OmitGroupSeparator);
         break;
     default:
         return QVariant();
     }
     QVarLengthArray<wchar_t, 64> out(64);
     QString decimalSep;
     QString thousandSep;
     CURRENCYFMT format;
     CURRENCYFMT *pformat = NULL;
     if (!arg.symbol.isEmpty()) {
         format.NumDigits = getLocaleInfo_int(lcid, LOCALE_ICURRDIGITS);
         format.LeadingZero = getLocaleInfo_int(lcid, LOCALE_ILZERO);
         decimalSep = getLocaleInfo(lcid, LOCALE_SMONDECIMALSEP);
         format.lpDecimalSep = (wchar_t *)decimalSep.utf16();
         thousandSep = getLocaleInfo(lcid, LOCALE_SMONTHOUSANDSEP);
         format.lpThousandSep = (wchar_t *)thousandSep.utf16();
         format.NegativeOrder = getLocaleInfo_int(lcid, LOCALE_INEGCURR);
         format.PositiveOrder = getLocaleInfo_int(lcid, LOCALE_ICURRENCY);
         format.lpCurrencySymbol = (wchar_t *)arg.symbol.utf16();
         // grouping is complicated and ugly:
         // int(0)  == "123456789.00"    == string("0")
         // int(3)  == "123,456,789.00"  == string("3;0")
         // int(30) == "123456,789.00"   == string("3;0;0")
         // int(32) == "12,34,56,789.00" == string("3;2;0")
         // int(320)== "1234,56,789.00"  == string("3;2")
         QString groupingStr = getLocaleInfo(lcid, LOCALE_SMONGROUPING);
         format.Grouping = groupingStr.remove(QLatin1Char(';')).toInt();
         if (format.Grouping % 10 == 0) // magic
             format.Grouping /= 10;
         else
             format.Grouping *= 10;
         pformat = &format;
     }
     int ret = ::GetCurrencyFormat(lcid, 0, reinterpret_cast<const wchar_t *>(value.utf16()),
                                   pformat, out.data(), out.size());
     if (ret == 0 && GetLastError() == ERROR_INSUFFICIENT_BUFFER) {
         ret = ::GetCurrencyFormat(lcid, 0, reinterpret_cast<const wchar_t *>(value.utf16()),
                                   pformat, out.data(), 0);
         out.resize(ret);
         ::GetCurrencyFormat(lcid, 0, reinterpret_cast<const wchar_t *>(value.utf16()),
                             pformat, out.data(), out.size());
     }
     value = QString::fromWCharArray(out.data());
     if (substitution() == SAlways)
         substituteDigits( value);
     return value;
 }
toString() [1/3]
QVariant QSystemLocalePrivate::toString (const QDate & date, QLocale::FormatType type)
Definition at line 328 of file qlocale_win.cpp.
Referenced by dateTimeFormat(), toString(), and winToQtFormat().
 {
     SYSTEMTIME st;
     memset(&st, 0, sizeof(SYSTEMTIME));
     st.wYear = date.year();
     st.wMonth = date.month();
     st.wDay = date.day();
     DWORD flags = (type == QLocale::LongFormat ? DATE_LONGDATE : DATE_SHORTDATE);
     wchar_t buf[255];
     if (GetDateFormat(lcid, flags, &st, NULL, buf, 255)) {
         QString format = QString::fromWCharArray(buf);
         if (substitution() == SAlways)
             substituteDigits(format);
         return format;
     }
     return QString();
 }
toString() [2/3]
QVariant QSystemLocalePrivate::toString (const QTime & time, QLocale::FormatType)
Definition at line 347 of file qlocale_win.cpp.
 {
     SYSTEMTIME st;
     memset(&st, 0, sizeof(SYSTEMTIME));
     st.wHour = time.hour();
     st.wMinute = time.minute();
     st.wSecond = time.second();
     st.wMilliseconds = 0;
     DWORD flags = 0;
     wchar_t buf[255];
     if (GetTimeFormat(lcid, flags, &st, NULL, buf, 255)) {
         QString format = QString::fromWCharArray(buf);
         if (substitution() == SAlways)
             substituteDigits(format);
         return format;
     }
     return QString();
 }
toString() [3/3]
QVariant QSystemLocalePrivate::toString (const QDateTime & dt, QLocale::FormatType type)
Definition at line 368 of file qlocale_win.cpp.
 {
     return QString(toString(dt.date(), type).toString() + QLatin1Char(' ') + toString(dt.time(), type).toString());
 }
uiLanguages()
QVariant QSystemLocalePrivate::uiLanguages ()
Definition at line 525 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     if (QSysInfo::windowsVersion() >= QSysInfo::WV_VISTA) {
         typedef BOOL (WINAPI *GetUserPreferredUILanguagesFunc) (
                     DWORD dwFlags,
                     PULONG pulNumLanguages,
                     PWSTR pwszLanguagesBuffer,
                     PULONG pcchLanguagesBuffer);
         static GetUserPreferredUILanguagesFunc GetUserPreferredUILanguages_ptr = 0;
         if (!GetUserPreferredUILanguages_ptr) {
             QSystemLibrary lib(QLatin1String("kernel32"));
             if (lib.load())
                 GetUserPreferredUILanguages_ptr = (GetUserPreferredUILanguagesFunc)lib.resolve("GetUserPreferredUILanguages");
         }
         if (GetUserPreferredUILanguages_ptr) {
             unsigned long cnt = 0;
             QVarLengthArray<wchar_t, 64> buf(64);
             unsigned long size = buf.size();
             if (!GetUserPreferredUILanguages_ptr(MUI_LANGUAGE_NAME, &cnt, buf.data(), &size)) {
                 size = 0;
                 if (GetLastError() == ERROR_INSUFFICIENT_BUFFER &&
                     GetUserPreferredUILanguages_ptr(MUI_LANGUAGE_NAME, &cnt, NULL, &size)) {
                     buf.resize(size);
                     if (!GetUserPreferredUILanguages_ptr(MUI_LANGUAGE_NAME, &cnt, buf.data(), &size))
                         return QStringList();
                 }
             }
             QStringList result;
             result.reserve(cnt);
             const wchar_t *str = buf.constData();
             for (; cnt > 0; --cnt) {
                 QString s = QString::fromWCharArray(str);
                 if (s.isEmpty())
                     break; // something is wrong
                 result.append(s);
                 str += s.size()+1;
             }
             return result;
         }
     }
     // old Windows before Vista
     return QStringList(QString::fromLatin1(winLangCodeToIsoName(GetUserDefaultUILanguage())));
 }
update()
void QSystemLocalePrivate::update ()
Definition at line 585 of file qlocale_win.cpp.
Referenced by winToQtFormat().
 {
     lcid = GetUserDefaultLCID();
     substitutionType = SUnknown;
     zero = QChar();
 }
winToQtFormat()
QString QSystemLocalePrivate::winToQtFormat (const QString & sys_fmt) static private
Definition at line 592 of file qlocale_win.cpp.
Referenced by dateFormat(), and timeFormat().
 {
     QString result;
     int i = 0;
     while (i < sys_fmt.size()) {
         if (sys_fmt.at(i).unicode() == QLatin1Char('\'')) {
             QString text = qt_readEscapedFormatString(sys_fmt, &i);
             if (text == QLatin1String("'"))
                 result += QLatin1String("''");
             else
                 result += QString(QLatin1Char('\'') + text + QLatin1Char('\''));
             continue;
         }
         QChar c = sys_fmt.at(i);
         int repeat = qt_repeatCount(sys_fmt, i);
         switch (c.unicode()) {
             // Date
             case 'y':
                 if (repeat > 5)
                     repeat = 5;
                 else if (repeat == 3)
                     repeat = 2;
                 switch (repeat) {
                     case 1:
                         result += QLatin1String("yy"); // "y" unsupported by Qt, use "yy"
                         break;
                     case 5:
                         result += QLatin1String("yyyy"); // "yyyyy" same as "yyyy" on Windows
                         break;
                     default:
                         result += QString(repeat, QLatin1Char('y'));
                         break;
                 }
                 break;
             case 'g':
                 if (repeat > 2)
                     repeat = 2;
                 switch (repeat) {
                     case 2:
                         break; // no equivalent of "gg" in Qt
                     default:
                         result += QLatin1Char('g');
                         break;
                 }
                 break;
             case 't':
                 if (repeat > 2)
                     repeat = 2;
                 result += QLatin1String("AP"); // "t" unsupported, use "AP"
                 break;
             default:
                 result += QString(repeat, c);
                 break;
         }
         i += repeat;
     }
     return result;
 }
zeroDigit()
QChar QSystemLocalePrivate::zeroDigit ()
Definition at line 220 of file qlocale_win.cpp.
Referenced by substituteDigits(), and winToQtFormat().
 {
     if (zero.isNull())
         zero = getLocaleInfo_qchar(LOCALE_SNATIVEDIGITS);
     return zero;
 }
Properties
langEnvVar
QByteArray QSystemLocalePrivate::langEnvVar private
Definition at line 116 of file qlocale_win.cpp.
Referenced by getWinLocaleName(), and QSystemLocalePrivate().
lcid
LCID QSystemLocalePrivate::lcid private
Definition at line 126 of file qlocale_win.cpp.
Referenced by amText(), currencySymbol(), firstDayOfWeek(), getLocaleInfo(), measurementSystem(), pmText(), QSystemLocalePrivate(), substitution(), toCurrencyString(), toString(), and update().
substitutionType
SubstitutionType QSystemLocalePrivate::substitutionType private
Definition at line 127 of file qlocale_win.cpp.
Referenced by substitution(), and update().
zero
QChar QSystemLocalePrivate::zero private
Definition at line 128 of file qlocale_win.cpp.
Referenced by substituteDigits(), substitution(), update(), and zeroDigit().
The documentation for this struct was generated from the following file:
/src/corelib/tools/qlocale_win.cpp