Qt 4.8: QRelation Struct Reference
QRelation Struct Reference
Public Functions
void clear ()
void clearDictionary ()
void init (QSqlRelationalTableModel *parent, const QSqlRelation &relation)
bool isDictionaryInitialized ()
bool isValid ()
void populateDictionary ()
void populateModel ()
QRelation ()
Public Variables
QHash< QString, QVariant > dictionary
QRelatedTableModel * model
QSqlRelation rel
Properties
bool m_dictInitialized
QSqlRelationalTableModel * m_parent
Detailed Description
Definition at line 145 of file qsqlrelationaltablemodel.cpp.
Constructors and Destructors
QRelation()
QRelation::QRelation () inline
Definition at line 148 of file qsqlrelationaltablemodel.cpp.
 : model(0),m_parent(0),m_dictInitialized(false){}
Functions
clear()
void QRelation::clear (void)
Definition at line 242 of file qsqlrelationaltablemodel.cpp.
Referenced by QSqlRelationalTableModelPrivate::clearChanges(), and QRelation().
 {
     delete model;
     model = 0;
     clearDictionary();
 }
clearDictionary()
void QRelation::clearDictionary ()
Definition at line 236 of file qsqlrelationaltablemodel.cpp.
Referenced by clear(), QRelation(), and QRelatedTableModel::select().
 {
     dictionary.clear();
     m_dictInitialized = false;
 }
init()
void QRelation::init (QSqlRelationalTableModel * parent, const QSqlRelation & relation)
Definition at line 183 of file qsqlrelationaltablemodel.cpp.
Referenced by QRelation().
 {
     Q_ASSERT(parent != NULL);
     m_parent = parent;
     rel = relation;
 }
isDictionaryInitialized()
bool QRelation::isDictionaryInitialized ()
Definition at line 203 of file qsqlrelationaltablemodel.cpp.
Referenced by QSqlRelationalTableModel::data(), QRelation(), and QSqlRelationalTableModel::setData().
 {
     return m_dictInitialized;
 }
isValid()
bool QRelation::isValid ()
Definition at line 249 of file qsqlrelationaltablemodel.cpp.
Referenced by populateDictionary(), populateModel(), QRelation(), and QSqlRelationalTableModel::relationModel().
 {
     return (rel.isValid() && m_parent != NULL);
 }
populateDictionary()
void QRelation::populateDictionary ()
Definition at line 208 of file qsqlrelationaltablemodel.cpp.
Referenced by QSqlRelationalTableModel::data(), QRelation(), QRelatedTableModel::select(), and QSqlRelationalTableModel::setData().
 {
     if (!isValid())
         return;
     if (model ==  NULL)
         populateModel();
     QSqlRecord record;
     QString indexColumn;
     QString displayColumn;
     for (int i=0; i < model->rowCount(); ++i) {
         record = model->record(i);
         indexColumn = rel.indexColumn();
         if (m_parent->database().driver()->isIdentifierEscaped(indexColumn, QSqlDriver::FieldName))
             indexColumn = m_parent->database().driver()->stripDelimiters(indexColumn, QSqlDriver::FieldName);
         displayColumn = rel.displayColumn();
         if (m_parent->database().driver()->isIdentifierEscaped(displayColumn, QSqlDriver::FieldName))
             displayColumn = m_parent->database().driver()->stripDelimiters(displayColumn, QSqlDriver::FieldName);
         dictionary[record.field(indexColumn).value().toString()] =
             record.field(displayColumn).value();
     }
     m_dictInitialized = true;
 }
populateModel()
void QRelation::populateModel ()
Definition at line 190 of file qsqlrelationaltablemodel.cpp.
Referenced by populateDictionary(), QRelation(), and QSqlRelationalTableModel::relationModel().
 {
     if (!isValid())
         return;
     Q_ASSERT(m_parent != NULL);
     if (!model) {
         model = new QRelatedTableModel(this, m_parent, m_parent->database());
         model->setTable(rel.tableName());
         model->select();
     }
 }
Properties
dictionary
QHash<QString, QVariant> QRelation::dictionary
Definition at line 162 of file qsqlrelationaltablemodel.cpp.
Referenced by clearDictionary(), QSqlRelationalTableModel::data(), populateDictionary(), and QSqlRelationalTableModel::setData().
m_dictInitialized
bool QRelation::m_dictInitialized private
Definition at line 166 of file qsqlrelationaltablemodel.cpp.
Referenced by clearDictionary(), isDictionaryInitialized(), and populateDictionary().
m_parent
QSqlRelationalTableModel* QRelation::m_parent private
Definition at line 165 of file qsqlrelationaltablemodel.cpp.
Referenced by init(), isValid(), populateDictionary(), and populateModel().
model
QRelatedTableModel* QRelation::model
Definition at line 161 of file qsqlrelationaltablemodel.cpp.
Referenced by clear(), populateDictionary(), populateModel(), and QSqlRelationalTableModel::relationModel().
rel
QSqlRelation QRelation::rel
Definition at line 160 of file qsqlrelationaltablemodel.cpp.
Referenced by init(), isValid(), populateDictionary(), and populateModel().
The documentation for this struct was generated from the following file:
/src/sql/models/qsqlrelationaltablemodel.cpp