Qt 4.8: QLocalePrivate Struct Reference
QLocalePrivate Struct Reference
#include <qlocale_p.h>
Public Types
typedef QVarLengthArray< char, 256 > CharBuff
enum DoubleForm { DFExponent = 0, DFDecimal, DFSignificantDigits, _DFMax = DFSignificantDigits }
enum Flags {
NoFlags = 0, Alternate = 0x01, ZeroPadded = 0x02, LeftAdjusted = 0x04,
BlankBeforePositive = 0x08, AlwaysShowSign = 0x10, ThousandsGroup = 0x20, CapitalEorX = 0x40,
ShowBase = 0x80, UppercaseBase = 0x100, ForcePoint = Alternate
}
enum GroupSeparatorMode { FailOnGroupSeparators, ParseGroupSeparators }
enum NumberMode { IntegerMode, DoubleStandardMode, DoubleScientificMode }
Public Functions
QString bcp47Name () const
QString countryCode () const
quint16 countryId () const
QString dateTimeToString (const QString &format, const QDate *date, const QTime *time, const QLocale *q) const
QChar decimal () const
char digitToCLocale (const QChar &c) const
QString doubleToString (double d, int precision=-1, DoubleForm form=DFSignificantDigits, int width=-1, unsigned flags=NoFlags) const
QChar exponential () const
QChar group () const
QString languageCode () const
quint16 languageId () const
QChar list () const
QString longLongToString (qint64 l, int precision=-1, int base=10, int width=-1, unsigned flags=NoFlags) const
QLocale::MeasurementSystem measurementSystem () const
QChar minus () const
bool numberToCLocale (const QString &num, GroupSeparatorMode group_sep_mode, CharBuff *result) const
QChar percent () const
QChar plus () const
QString scriptCode () const
double stringToDouble (const QString &num, bool *ok, GroupSeparatorMode group_sep_mode) const
qint64 stringToLongLong (const QString &num, int base, bool *ok, GroupSeparatorMode group_sep_mode) const
quint64 stringToUnsLongLong (const QString &num, int base, bool *ok, GroupSeparatorMode group_sep_mode) const
QString unsLongLongToString (quint64 l, int precision=-1, int base=10, int width=-1, unsigned flags=NoFlags) const
bool validateChars (const QString &str, NumberMode numMode, QByteArray *buff, int decDigits=-1) const
QChar zero () const
Static Public Functions
static double bytearrayToDouble (const char *num, bool *ok, bool *overflow=0)
static qint64 bytearrayToLongLong (const char *num, int base, bool *ok, bool *overflow=0)
static quint64 bytearrayToUnsLongLong (const char *num, int base, bool *ok)
static QLocale::Country codeToCountry (const QString &code)
static QLocale::Language codeToLanguage (const QString &code)
static QLocale::Script codeToScript (const QString &code)
static QString doubleToString (const QChar zero, const QChar plus, const QChar minus, const QChar exponent, const QChar group, const QChar decimal, double d, int precision, DoubleForm form, int width, unsigned flags)
static const QLocalePrivate * findLocale (QLocale::Language language, QLocale::Script script, QLocale::Country country)
static void getLangAndCountry (const QString &name, QLocale::Language &lang, QLocale::Script &script, QLocale::Country &cntry)
static QString longLongToString (const QChar zero, const QChar group, const QChar plus, const QChar minus, qint64 l, int precision, int base, int width, unsigned flags)
static QString unsLongLongToString (const QChar zero, const QChar group, const QChar plus, quint64 l, int precision, int base, int width, unsigned flags)
static void updateSystemPrivate ()
Public Variables
quint16 m_alternate_quotation_end
quint16 m_alternate_quotation_start
quint16 m_am_idx
quint16 m_am_size
quint16 m_country_endonym_idx
quint16 m_country_endonym_size
quint16 m_country_id
quint16 m_currency_digits: 2
quint16 m_currency_display_name_idx
quint16 m_currency_display_name_size
quint8 m_currency_format_idx
quint8 m_currency_format_size
char m_currency_iso_code [3]
quint8 m_currency_negative_format_idx
quint8 m_currency_negative_format_size
quint16 m_currency_rounding: 3
quint16 m_currency_symbol_idx
quint16 m_currency_symbol_size
quint16 m_decimal
quint16 m_exponential
quint16 m_first_day_of_week: 3
quint16 m_group
quint16 m_language_endonym_idx
quint16 m_language_endonym_size
quint16 m_language_id
quint16 m_list
quint16 m_list_pattern_part_end_idx
quint16 m_list_pattern_part_end_size
quint16 m_list_pattern_part_mid_idx
quint16 m_list_pattern_part_mid_size
quint16 m_list_pattern_part_start_idx
quint16 m_list_pattern_part_start_size
quint16 m_list_pattern_part_two_idx
quint16 m_list_pattern_part_two_size
quint16 m_long_date_format_idx
quint16 m_long_date_format_size
quint16 m_long_day_names_idx
quint16 m_long_day_names_size
quint16 m_long_month_names_idx
quint16 m_long_month_names_size
quint16 m_long_time_format_idx
quint16 m_long_time_format_size
quint16 m_minus
quint16 m_narrow_day_names_idx
quint16 m_narrow_day_names_size
quint16 m_narrow_month_names_idx
quint16 m_narrow_month_names_size
quint16 m_percent
quint16 m_plus
quint16 m_pm_idx
quint16 m_pm_size
quint16 m_quotation_end
quint16 m_quotation_start
quint16 m_script_id
quint16 m_short_date_format_idx
quint16 m_short_date_format_size
quint16 m_short_day_names_idx
quint16 m_short_day_names_size
quint16 m_short_month_names_idx
quint16 m_short_month_names_size
quint16 m_short_time_format_idx
quint16 m_short_time_format_size
quint16 m_standalone_long_day_names_idx
quint16 m_standalone_long_day_names_size
quint16 m_standalone_long_month_names_idx
quint16 m_standalone_long_month_names_size
quint16 m_standalone_narrow_day_names_idx
quint16 m_standalone_narrow_day_names_size
quint16 m_standalone_narrow_month_names_idx
quint16 m_standalone_narrow_month_names_size
quint16 m_standalone_short_day_names_idx
quint16 m_standalone_short_day_names_size
quint16 m_standalone_short_month_names_idx
quint16 m_standalone_short_month_names_size
quint16 m_weekend_end: 3
quint16 m_weekend_start: 3
quint16 m_zero
Detailed Description
Definition at line 68 of file qlocale_p.h.
Typedefs
CharBuff
typedef QVarLengthArray<char, 256> QLocalePrivate::CharBuff
Definition at line 166 of file qlocale_p.h.
Enumerations
DoubleForm
enum QLocalePrivate::DoubleForm
Enumerator
DFExponent
DFDecimal
DFSignificantDigits
_DFMax
Definition at line 101 of file qlocale_p.h.
                     {
         DFExponent = 0,
         DFDecimal,
         DFSignificantDigits,
         _DFMax = DFSignificantDigits
     };
Flags
enum QLocalePrivate::Flags
Enumerator
NoFlags
Alternate
ZeroPadded
LeftAdjusted
BlankBeforePositive
AlwaysShowSign
ThousandsGroup
CapitalEorX
ShowBase
UppercaseBase
ForcePoint
Definition at line 108 of file qlocale_p.h.
                {
         NoFlags             = 0,
         Alternate           = 0x01,
         ZeroPadded          = 0x02,
         LeftAdjusted        = 0x04,
         BlankBeforePositive = 0x08,
         AlwaysShowSign      = 0x10,
         ThousandsGroup      = 0x20,
         CapitalEorX         = 0x40,
         ShowBase            = 0x80,
         UppercaseBase       = 0x100,
         ForcePoint          = Alternate
     };
GroupSeparatorMode
enum QLocalePrivate::GroupSeparatorMode
Enumerator
FailOnGroupSeparators
ParseGroupSeparators
Definition at line 123 of file qlocale_p.h.
{
         FailOnGroupSeparators,
         ParseGroupSeparators
     };
NumberMode
enum QLocalePrivate::NumberMode
Enumerator
IntegerMode
DoubleStandardMode
DoubleScientificMode
Definition at line 174 of file qlocale_p.h.
 { IntegerMode, DoubleStandardMode, DoubleScientificMode };
Functions
bcp47Name()
QString QLocalePrivate::bcp47Name () const
Definition at line 206 of file qlocale.cpp.
Referenced by QLocale::bcp47Name().
 {
     if (m_language_id == QLocale::AnyLanguage)
         return QString();
     if (m_language_id == QLocale::C)
         return QLatin1String("C");
     const unsigned char *lang = language_code_list + 3*(uint(m_language_id));
     const unsigned char *script =
             (m_script_id != QLocale::AnyScript ? script_code_list + 4*(uint(m_script_id)) : 0);
     const unsigned char *country =
             (m_country_id != QLocale::AnyCountry  ? country_code_list + 3*(uint(m_country_id)) : 0);
     char len = (lang[2] != 0 ? 3 : 2) + (script ? 4+1 : 0) + (country ? (country[2] != 0 ? 3 : 2)+1 : 0);
     QString name(len, Qt::Uninitialized);
     QChar *uc = name.data();
     *uc++ = ushort(lang[0]);
     *uc++ = ushort(lang[1]);
     if (lang[2] != 0)
         *uc++ = ushort(lang[2]);
     if (script) {
         *uc++ = QLatin1Char('-');
         *uc++ = ushort(script[0]);
         *uc++ = ushort(script[1]);
         *uc++ = ushort(script[2]);
         *uc++ = ushort(script[3]);
     }
     if (country) {
         *uc++ = QLatin1Char('-');
         *uc++ = ushort(country[0]);
         *uc++ = ushort(country[1]);
         if (country[2] != 0)
             *uc++ = ushort(country[2]);
     }
     return name;
 }
bytearrayToDouble()
double QLocalePrivate::bytearrayToDouble (const char * num, bool * ok, bool * overflow = 0) static
Definition at line 3134 of file qlocale.cpp.
Referenced by QByteArray::toDouble(), and QDoubleValidatorPrivate::validateWithLocale().
 {
     if (ok != 0)
         *ok = true;
     if (overflow != 0)
         *overflow = false;
     if (*num == '\0') {
         if (ok != 0)
             *ok = false;
         return 0.0;
     }
     if (qstrcmp(num, "nan") == 0)
         return qt_snan();
     if (qstrcmp(num, "+inf") == 0 || qstrcmp(num, "inf") == 0)
         return qt_inf();
     if (qstrcmp(num, "-inf") == 0)
         return -qt_inf();
     bool _ok;
     const char *endptr;
     double d = qstrtod(num, &endptr, &_ok);
     if (!_ok) {
         // the only way strtod can fail with *endptr != '\0' on a non-empty
         // input string is overflow
         if (ok != 0)
             *ok = false;
         if (overflow != 0)
             *overflow = *endptr != '\0';
         return 0.0;
     }
     if (*endptr != '\0') {
         // we stopped at a non-digit character after converting some digits
         if (ok != 0)
             *ok = false;
         if (overflow != 0)
             *overflow = false;
         return 0.0;
     }
     if (ok != 0)
         *ok = true;
     if (overflow != 0)
         *overflow = false;
     return d;
 }
bytearrayToLongLong()
qlonglong QLocalePrivate::bytearrayToLongLong (const char * num, int base, bool * ok, bool * overflow = 0) static
Definition at line 3186 of file qlocale.cpp.
Referenced by QIntValidator::fixup(), QByteArray::toLongLong(), and QIntValidator::validate().
 {
     bool _ok;
     const char *endptr;
     if (*num == '\0') {
         if (ok != 0)
             *ok = false;
         if (overflow != 0)
             *overflow = false;
         return 0;
     }
     qlonglong l = qstrtoll(num, &endptr, base, &_ok);
     if (!_ok) {
         if (ok != 0)
             *ok = false;
         if (overflow != 0) {
             // the only way qstrtoll can fail with *endptr != '\0' on a non-empty
             // input string is overflow
             *overflow = *endptr != '\0';
         }
         return 0;
     }
     if (*endptr != '\0') {
         // we stopped at a non-digit character after converting some digits
         if (ok != 0)
             *ok = false;
         if (overflow != 0)
             *overflow = false;
         return 0;
     }
     if (ok != 0)
         *ok = true;
     if (overflow != 0)
         *overflow = false;
     return l;
 }
bytearrayToUnsLongLong()
qulonglong QLocalePrivate::bytearrayToUnsLongLong (const char * num, int base, bool * ok) static
Definition at line 3228 of file qlocale.cpp.
Referenced by QByteArray::toULongLong().
 {
     bool _ok;
     const char *endptr;
     qulonglong l = qstrtoull(num, &endptr, base, &_ok);
     if (!_ok || *endptr != '\0') {
         if (ok != 0)
             *ok = false;
         return 0;
     }
     if (ok != 0)
         *ok = true;
     return l;
 }
codeToCountry()
QLocale::Country QLocalePrivate::codeToCountry (const QString & code) static
Definition at line 144 of file qlocale.cpp.
Referenced by getLangAndCountry().
 {
     int len = code.length();
     if (len != 2 && len != 3)
         return QLocale::AnyCountry;
     ushort uc1 = len-- > 0 ? code[0].toUpper().unicode() : 0;
     ushort uc2 = len-- > 0 ? code[1].toUpper().unicode() : 0;
     ushort uc3 = len-- > 0 ? code[2].toUpper().unicode() : 0;
     const unsigned char *c = country_code_list;
     for (; *c != 0; c += 3) {
         if (uc1 == c[0] && uc2 == c[1] && uc3 == c[2])
             return QLocale::Country((c - country_code_list)/3);
     }
     return QLocale::AnyCountry;
 }
codeToLanguage()
QLocale::Language QLocalePrivate::codeToLanguage (const QString & code) static
Definition at line 103 of file qlocale.cpp.
Referenced by getLangAndCountry().
 {
     int len = code.length();
     if (len != 2 && len != 3)
         return QLocale::C;
     ushort uc1 = len-- > 0 ? code[0].toLower().unicode() : 0;
     ushort uc2 = len-- > 0 ? code[1].toLower().unicode() : 0;
     ushort uc3 = len-- > 0 ? code[2].toLower().unicode() : 0;
     if (uc1 == 'n' && uc2 == 'o' && uc3 == 0)
         uc2 = 'b';
     const unsigned char *c = language_code_list;
     for (; *c != 0; c += 3) {
         if (uc1 == c[0] && uc2 == c[1] && uc3 == c[2])
             return QLocale::Language((c - language_code_list)/3);
     }
     return QLocale::C;
 }
codeToScript()
QLocale::Script QLocalePrivate::codeToScript (const QString & code) static
Definition at line 124 of file qlocale.cpp.
Referenced by getLangAndCountry().
 {
     int len = code.length();
     if (len != 4)
         return QLocale::AnyScript;
     // script is titlecased in our data
     unsigned char c0 = code.at(0).toUpper().toLatin1();
     unsigned char c1 = code.at(1).toLower().toLatin1();
     unsigned char c2 = code.at(2).toLower().toLatin1();
     unsigned char c3 = code.at(3).toLower().toLatin1();
     const unsigned char *c = script_code_list;
     for (int i = 0; i < QLocale::LastScript; ++i, c += 4) {
         if (c0 == c[0] && c1 == c[1] && c2 == c[2] && c3 == c[3])
             return QLocale::Script(i);
     }
     return QLocale::AnyScript;
 }
countryCode()
QString QLocalePrivate::countryCode () const
Definition at line 189 of file qlocale.cpp.
 {
     if (m_country_id == QLocale::AnyCountry)
         return QString();
     const unsigned char *c = country_code_list + 3*(uint(m_country_id));
     QString code(c[2] == 0 ? 2 : 3, Qt::Uninitialized);
     code[0] = ushort(c[0]);
     code[1] = ushort(c[1]);
     if (c[2] != 0)
         code[2] = ushort(c[2]);
     return code;
 }
countryId()
quint16 QLocalePrivate::countryId () const inline
Definition at line 81 of file qlocale_p.h.
Referenced by QLocale::countriesForLanguage().
 { return m_country_id; }
dateTimeToString()
QString QLocalePrivate::dateTimeToString (const QString & format, const QDate * date, const QTime * time, const QLocale * q) const
Definition at line 2389 of file qlocale.cpp.
Referenced by QLocale::toString().
 {
     Q_ASSERT(date || time);
     if ((date && !date->isValid()) || (time && !time->isValid()))
         return QString();
     const bool format_am_pm = time && timeFormatContainsAP(format);
     enum { AM, PM } am_pm = AM;
     int hour12 = time ? time->hour() : -1;
     if (time) {
         if (hour12 == 0) {
             am_pm = AM;
             hour12 = 12;
         } else if (hour12 < 12) {
             am_pm = AM;
         } else if (hour12 == 12) {
             am_pm = PM;
         } else {
             am_pm = PM;
             hour12 -= 12;
         }
     }
     QString result;
     int i = 0;
     while (i < format.size()) {
         if (format.at(i).unicode() == '\'') {
             result.append(qt_readEscapedFormatString(format, &i));
             continue;
         }
         const QChar c = format.at(i);
         int repeat = qt_repeatCount(format, i);
         bool used = false;
         if (date) {
             switch (c.unicode()) {
             case 'y':
                 used = true;
                 if (repeat >= 4)
                     repeat = 4;
                 else if (repeat >= 2)
                     repeat = 2;
                 switch (repeat) {
                 case 4:
                     result.append(longLongToString(date->year()));
                     break;
                 case 2:
                     result.append(longLongToString(date->year() % 100, -1, 10, 2,
                                                    QLocalePrivate::ZeroPadded));
                     break;
                 default:
                     repeat = 1;
                     result.append(c);
                     break;
                 }
                 break;
             case 'M':
                 used = true;
                 repeat = qMin(repeat, 4);
                 switch (repeat) {
                 case 1:
                     result.append(longLongToString(date->month()));
                     break;
                 case 2:
                     result.append(longLongToString(date->month(), -1, 10, 2, QLocalePrivate::ZeroPadded));
                     break;
                 case 3:
                     result.append(q->monthName(date->month(), QLocale::ShortFormat));
                     break;
                 case 4:
                     result.append(q->monthName(date->month(), QLocale::LongFormat));
                     break;
                 }
                 break;
             case 'd':
                 used = true;
                 repeat = qMin(repeat, 4);
                 switch (repeat) {
                 case 1:
                     result.append(longLongToString(date->day()));
                     break;
                 case 2:
                     result.append(longLongToString(date->day(), -1, 10, 2, QLocalePrivate::ZeroPadded));
                     break;
                 case 3:
                     result.append(q->dayName(date->dayOfWeek(), QLocale::ShortFormat));
                     break;
                 case 4:
                     result.append(q->dayName(date->dayOfWeek(), QLocale::LongFormat));
                     break;
                 }
                 break;
             default:
                 break;
             }
         }
         if (!used && time) {
             switch (c.unicode()) {
             case 'h': {
                 used = true;
                 repeat = qMin(repeat, 2);
                 const int hour = format_am_pm ? hour12 : time->hour();
                 switch (repeat) {
                 case 1:
                     result.append(longLongToString(hour));
                     break;
                 case 2:
                     result.append(longLongToString(hour, -1, 10, 2, QLocalePrivate::ZeroPadded));
                     break;
                 }
                 break;
             }
             case 'H':
                 used = true;
                 repeat = qMin(repeat, 2);
                 switch (repeat) {
                 case 1:
                     result.append(longLongToString(time->hour()));
                     break;
                 case 2:
                     result.append(longLongToString(time->hour(), -1, 10, 2, QLocalePrivate::ZeroPadded));
                     break;
                 }
                 break;
             case 'm':
                 used = true;
                 repeat = qMin(repeat, 2);
                 switch (repeat) {
                 case 1:
                     result.append(longLongToString(time->minute()));
                     break;
                 case 2:
                     result.append(longLongToString(time->minute(), -1, 10, 2, QLocalePrivate::ZeroPadded));
                     break;
                 }
                 break;
             case 's':
                 used = true;
                 repeat = qMin(repeat, 2);
                 switch (repeat) {
                 case 1:
                     result.append(longLongToString(time->second()));
                     break;
                 case 2:
                     result.append(longLongToString(time->second(), -1, 10, 2, QLocalePrivate::ZeroPadded));
                     break;
                 }
                 break;
             case 'a':
                 used = true;
                 if (i + 1 < format.length() && format.at(i + 1).unicode() == 'p') {
                     repeat = 2;
                 } else {
                     repeat = 1;
                 }
                 result.append(am_pm == AM ? q->amText().toLower() : q->pmText().toLower());
                 break;
             case 'A':
                 used = true;
                 if (i + 1 < format.length() && format.at(i + 1).unicode() == 'P') {
                     repeat = 2;
                 } else {
                     repeat = 1;
                 }
                 result.append(am_pm == AM ? q->amText().toUpper() : q->pmText().toUpper());
                 break;
             case 'z':
                 used = true;
                 if (repeat >= 3) {
                     repeat = 3;
                 } else {
                     repeat = 1;
                 }
                 switch (repeat) {
                 case 1:
                     result.append(longLongToString(time->msec()));
                     break;
                 case 3:
                     result.append(longLongToString(time->msec(), -1, 10, 3, QLocalePrivate::ZeroPadded));
                     break;
                 }
                 break;
             case 't':
                 used = true;
                 repeat = 1;
                 result.append(timeZone());
                 break;
             default:
                 break;
             }
         }
         if (!used) {
             result.append(QString(repeat, c));
         }
         i += repeat;
     }
     return result;
 }
decimal()
QChar QLocalePrivate::decimal () const inline
Definition at line 71 of file qlocale_p.h.
Referenced by QLocale::decimalPoint().
 { return QChar(m_decimal); }
digitToCLocale()
char QLocalePrivate::digitToCLocale (const QChar & c) const inline
Definition at line 224 of file qlocale_p.h.
 {
     const QChar _zero = zero();
     const QChar _group = group();
     const ushort zeroUnicode = _zero.unicode();
     const ushort tenUnicode = zeroUnicode + 10;
     if (in.unicode() >= zeroUnicode && in.unicode() < tenUnicode)
         return '0' + in.unicode() - zeroUnicode;
     if (in.unicode() >= '0' && in.unicode() <= '9')
         return in.toLatin1();
     if (in == plus())
         return '+';
     if (in == minus())
         return '-';
     if (in == decimal())
         return '.';
     if (in == group())
         return ',';
     if (in == exponential() || in == exponential().toUpper())
         return 'e';
     // In several languages group() is the char 0xA0, which looks like a space.
     // People use a regular space instead of it and complain it doesn't work.
     if (_group.unicode() == 0xA0 && in.unicode() == ' ')
         return ',';
     return 0;
 }
doubleToString() [1/2]
QString QLocalePrivate::doubleToString (const QChar zero, const QChar plus, const QChar minus, const QChar exponent, const QChar group, const QChar decimal, double d, int precision, DoubleForm form, int width, unsigned flags) static
Definition at line 2613 of file qlocale.cpp.
Referenced by QString::arg(), doubleToString(), QTextStream::operator<<(), QByteArray::setNum(), QString::setNum(), QSystemLocalePrivate::toCurrencyString(), QLocale::toCurrencyString(), QLocale::toString(), and QString::vsprintf().
 {
     if (precision == -1)
         precision = 6;
     if (width == -1)
         width = 0;
     bool negative = false;
     bool special_number = false; // nan, +/-inf
     QString num_str;
     // Detect special numbers (nan, +/-inf)
     if (qt_is_inf(d)) {
         num_str = QString::fromLatin1("inf");
         special_number = true;
         negative = d < 0;
     } else if (qt_is_nan(d)) {
         num_str = QString::fromLatin1("nan");
         special_number = true;
     }
     // Handle normal numbers
     if (!special_number) {
         int decpt, sign;
         QString digits;
 #ifdef QT_QLOCALE_USES_FCVT
         // NOT thread safe!
         if (form == DFDecimal) {
             digits = QLatin1String(fcvt(d, precision, &decpt, &sign));
         } else {
             int pr = precision;
             if (form == DFExponent)
                 ++pr;
             else if (form == DFSignificantDigits && pr == 0)
                 pr = 1;
             digits = QLatin1String(ecvt(d, pr, &decpt, &sign));
             // Chop trailing zeros
             if (digits.length() > 0) {
                 int last_nonzero_idx = digits.length() - 1;
                 while (last_nonzero_idx > 0
                        && digits.unicode()[last_nonzero_idx] == QLatin1Char('0'))
                     --last_nonzero_idx;
                 digits.truncate(last_nonzero_idx + 1);
             }
         }
 #else
         int mode;
         if (form == DFDecimal)
             mode = 3;
         else
             mode = 2;
         /* This next bit is a bit quirky. In DFExponent form, the precision
            is the number of digits after decpt. So that would suggest using
            mode=3 for qdtoa. But qdtoa behaves strangely when mode=3 and
            precision=0. So we get around this by using mode=2 and reasoning
            that we want precision+1 significant digits, since the decimal
            point in this mode is always after the first digit. */
         int pr = precision;
         if (form == DFExponent)
             ++pr;
         char *rve = 0;
         char *buff = 0;
         QT_TRY {
             digits = QLatin1String(qdtoa(d, mode, pr, &decpt, &sign, &rve, &buff));
         } QT_CATCH(...) {
             if (buff != 0)
                 free(buff);
             QT_RETHROW;
         }
         if (buff != 0)
             free(buff);
 #endif // QT_QLOCALE_USES_FCVT
         if (_zero.unicode() != '0') {
             ushort z = _zero.unicode() - '0';
             for (int i = 0; i < digits.length(); ++i)
                 reinterpret_cast<ushort *>(digits.data())[i] += z;
         }
         bool always_show_decpt = (flags & Alternate || flags & ForcePoint);
         switch (form) {
             case DFExponent: {
                 num_str = exponentForm(_zero, decimal, exponential, group, plus, minus,
                                        digits, decpt, precision, PMDecimalDigits,
                                        always_show_decpt);
                 break;
             }
             case DFDecimal: {
                 num_str = decimalForm(_zero, decimal, group,
                                       digits, decpt, precision, PMDecimalDigits,
                                       always_show_decpt, flags & ThousandsGroup);
                 break;
             }
             case DFSignificantDigits: {
                 PrecisionMode mode = (flags & Alternate) ?
                             PMSignificantDigits : PMChopTrailingZeros;
                 if (decpt != digits.length() && (decpt <= -4 || decpt > precision))
                     num_str = exponentForm(_zero, decimal, exponential, group, plus, minus,
                                            digits, decpt, precision, mode,
                                            always_show_decpt);
                 else
                     num_str = decimalForm(_zero, decimal, group,
                                           digits, decpt, precision, mode,
                                           always_show_decpt, flags & ThousandsGroup);
                 break;
             }
         }
         negative = sign != 0 && !isZero(d);
     }
     // pad with zeros. LeftAdjusted overrides this flag). Also, we don't
     // pad special numbers
     if (flags & QLocalePrivate::ZeroPadded
             && !(flags & QLocalePrivate::LeftAdjusted)
             && !special_number) {
         int num_pad_chars = width - num_str.length();
         // leave space for the sign
         if (negative
                 || flags & QLocalePrivate::AlwaysShowSign
                 || flags & QLocalePrivate::BlankBeforePositive)
             --num_pad_chars;
         for (int i = 0; i < num_pad_chars; ++i)
             num_str.prepend(_zero);
     }
     // add sign
     if (negative)
         num_str.prepend(minus);
     else if (flags & QLocalePrivate::AlwaysShowSign)
         num_str.prepend(plus);
     else if (flags & QLocalePrivate::BlankBeforePositive)
         num_str.prepend(QLatin1Char(' '));
     if (flags & QLocalePrivate::CapitalEorX)
         num_str = num_str.toUpper();
     return num_str;
 }
doubleToString() [2/2]
QString QLocalePrivate::doubleToString (double d, int precision = -1, DoubleForm form = DFSignificantDigits, int width = -1, unsigned flags = NoFlags) const
Definition at line 2602 of file qlocale.cpp.
 {
     return QLocalePrivate::doubleToString(zero(), plus(), minus(), exponential(),
                                           group(), decimal(),
                                           d, precision, form, width, flags);
 }
exponential()
QChar QLocalePrivate::exponential () const inline
Definition at line 78 of file qlocale_p.h.
Referenced by QLocale::exponential().
 { return QChar(m_exponential); }
findLocale()
const QLocalePrivate * QLocalePrivate::findLocale (QLocale::Language language, QLocale::Script script, QLocale::Country country) static
Definition at line 241 of file qlocale.cpp.
Referenced by findLocale(), and QLocale::QLocale().
 {
     const unsigned language_id = language;
     const unsigned script_id = script;
     const unsigned country_id = country;
     uint idx = locale_index[language_id];
     const QLocalePrivate *d = locale_data + idx;
     if (idx == 0) // default language has no associated country
         return d;
     if (script == QLocale::AnyScript && country == QLocale::AnyCountry)
         return d;
     Q_ASSERT(d->languageId() == language_id);
     if (country == QLocale::AnyCountry) {
         while (d->m_language_id == language_id && d->m_script_id != script_id)
             ++d;
         if (d->m_language_id == language_id && d->m_script_id == script_id)
             return d;
     } else if (script == QLocale::AnyScript) {
         while (d->m_language_id == language_id) {
             if (d->m_script_id == script_id && d->m_country_id == country_id)
                 return d;
             ++d;
         }
     } else {
         // both script and country are explicitly specified
         while (d->m_language_id == language_id) {
             if (d->m_script_id == script_id && d->m_country_id == country_id)
                 return d;
             ++d;
         }
     }
     return locale_data + idx;
 }
getLangAndCountry()
void QLocalePrivate::getLangAndCountry (const QString & name, QLocale::Language & lang, QLocale::Script & script, QLocale::Country & cntry) static
Definition at line 357 of file qlocale.cpp.
Referenced by findLocale(), and QSystemLocalePrivate::winToQtFormat().
 {
     lang = QLocale::C;
     script = QLocale::AnyScript;
     cntry = QLocale::AnyCountry;
     QString lang_code;
     QString script_code;
     QString cntry_code;
     if (!qt_splitLocaleName(name, lang_code, script_code, cntry_code))
         return;
     lang = QLocalePrivate::codeToLanguage(lang_code);
     if (lang == QLocale::C)
         return;
     script = QLocalePrivate::codeToScript(script_code);
     cntry = QLocalePrivate::codeToCountry(cntry_code);
 }
group()
QChar QLocalePrivate::group () const inline
Definition at line 72 of file qlocale_p.h.
Referenced by QLocale::groupSeparator().
 { return QChar(m_group); }
languageCode()
QString QLocalePrivate::languageCode () const
Definition at line 162 of file qlocale.cpp.
 {
     if (m_language_id == QLocale::AnyLanguage)
         return QString();
     if (m_language_id == QLocale::C)
         return QLatin1String("C");
     const unsigned char *c = language_code_list + 3*(uint(m_language_id));
     QString code(c[2] == 0 ? 2 : 3, Qt::Uninitialized);
     code[0] = ushort(c[0]);
     code[1] = ushort(c[1]);
     if (c[2] != 0)
         code[2] = ushort(c[2]);
     return code;
 }
languageId()
quint16 QLocalePrivate::languageId () const inline
Definition at line 80 of file qlocale_p.h.
Referenced by QLocale::countriesForLanguage(), findLocale(), and QLocale::QLocale().
 { return m_language_id; }
list()
QChar QLocalePrivate::list () const inline
Definition at line 73 of file qlocale_p.h.
 { return QChar(m_list); }
longLongToString() [1/2]
QString QLocalePrivate::longLongToString (const QChar zero, const QChar group, const QChar plus, const QChar minus, qint64 l, int precision, int base, int width, unsigned flags) static
Definition at line 2775 of file qlocale.cpp.
Referenced by QString::arg(), exponentForm(), longLongToString(), QTextStreamPrivate::putNumber(), QByteArray::setNum(), QString::setNum(), QSystemLocalePrivate::toCurrencyString(), QLocale::toCurrencyString(), QLocale::toString(), and QString::vsprintf().
 {
     bool precision_not_specified = false;
     if (precision == -1) {
         precision_not_specified = true;
         precision = 1;
     }
     bool negative = l < 0;
     if (base != 10) {
         // these are not supported by sprintf for octal and hex
         flags &= ~AlwaysShowSign;
         flags &= ~BlankBeforePositive;
         negative = false; // neither are negative numbers
     }
     QString num_str;
     if (base == 10)
         num_str = qlltoa(l, base, zero);
     else
         num_str = qulltoa(l, base, zero);
     uint cnt_thousand_sep = 0;
     if (flags & ThousandsGroup && base == 10) {
         for (int i = num_str.length() - 3; i > 0; i -= 3) {
             num_str.insert(i, group);
             ++cnt_thousand_sep;
         }
     }
     for (int i = num_str.length()/* - cnt_thousand_sep*/; i < precision; ++i)
         num_str.prepend(base == 10 ? zero : QChar::fromLatin1('0'));
     if ((flags & Alternate || flags & ShowBase)
             && base == 8
             && (num_str.isEmpty() || num_str[0].unicode() != QLatin1Char('0')))
         num_str.prepend(QLatin1Char('0'));
     // LeftAdjusted overrides this flag ZeroPadded. sprintf only padds
     // when precision is not specified in the format string
     bool zero_padded = flags & ZeroPadded
                         && !(flags & LeftAdjusted)
                         && precision_not_specified;
     if (zero_padded) {
         int num_pad_chars = width - num_str.length();
         // leave space for the sign
         if (negative
                 || flags & AlwaysShowSign
                 || flags & BlankBeforePositive)
             --num_pad_chars;
         // leave space for optional '0x' in hex form
         if (base == 16 && (flags & Alternate || flags & ShowBase))
             num_pad_chars -= 2;
         // leave space for optional '0b' in binary form
         else if (base == 2 && (flags & Alternate || flags & ShowBase))
             num_pad_chars -= 2;
         for (int i = 0; i < num_pad_chars; ++i)
             num_str.prepend(base == 10 ? zero : QChar::fromLatin1('0'));
     }
     if (flags & CapitalEorX)
         num_str = num_str.toUpper();
     if (base == 16 && (flags & Alternate || flags & ShowBase))
         num_str.prepend(QLatin1String(flags & UppercaseBase ? "0X" : "0x"));
     if (base == 2 && (flags & Alternate || flags & ShowBase))
         num_str.prepend(QLatin1String(flags & UppercaseBase ? "0B" : "0b"));
     // add sign
     if (negative)
         num_str.prepend(minus);
     else if (flags & AlwaysShowSign)
         num_str.prepend(plus);
     else if (flags & BlankBeforePositive)
         num_str.prepend(QLatin1Char(' '));
     return num_str;
 }
longLongToString() [2/2]
QString QLocalePrivate::longLongToString (qint64 l, int precision = -1, int base = 10, int width = -1, unsigned flags = NoFlags) const
Definition at line 2767 of file qlocale.cpp.
 {
     return QLocalePrivate::longLongToString(zero(), group(), plus(), minus(),
                                             l, precision, base, width, flags);
 }
measurementSystem()
QLocale::MeasurementSystem QLocalePrivate::measurementSystem () const
Definition at line 2218 of file qlocale.cpp.
Referenced by QLocale::measurementSystem().
 {
     for (int i = 0; i < ImperialMeasurementSystemsCount; ++i) {
         if (ImperialMeasurementSystems[i].languageId == m_language_id
             && ImperialMeasurementSystems[i].countryId == m_country_id) {
             return QLocale::ImperialSystem;
         }
     }
     return QLocale::MetricSystem;
 }
minus()
QChar QLocalePrivate::minus () const inline
Definition at line 77 of file qlocale_p.h.
Referenced by QLocale::negativeSign().
 { return QChar(m_minus); }
numberToCLocale()
bool QLocalePrivate::numberToCLocale (const QString & num, GroupSeparatorMode group_sep_mode, CharBuff * result) const
Definition at line 2945 of file qlocale.cpp.
 {
     const QChar *uc = num.unicode();
     int l = num.length();
     int idx = 0;
     // Skip whitespace
     while (idx < l && uc[idx].isSpace())
         ++idx;
     if (idx == l)
         return false;
     while (idx < l) {
         const QChar &in = uc[idx];
         char out = digitToCLocale(in);
         if (out == 0) {
             if (in == list())
                 out = ';';
             else if (in == percent())
                 out = '%';
             // for handling base-x numbers
             else if (in.unicode() >= 'A' && in.unicode() <= 'Z')
                 out = in.toLower().toLatin1();
             else if (in.unicode() >= 'a' && in.unicode() <= 'z')
                 out = in.toLatin1();
             else
                 break;
         }
         result->append(out);
         ++idx;
     }
     // Check trailing whitespace
     for (; idx < l; ++idx) {
         if (!uc[idx].isSpace())
             return false;
     }
     result->append('\0');
     // Check separators
     if (group_sep_mode == ParseGroupSeparators
             && !removeGroupSeparators(result))
         return false;
     return true;
 }
percent()
QChar QLocalePrivate::percent () const inline
Definition at line 74 of file qlocale_p.h.
Referenced by QLocale::percent().
 { return QChar(m_percent); }
plus()
QChar QLocalePrivate::plus () const inline
Definition at line 76 of file qlocale_p.h.
Referenced by QLocale::positiveSign().
 { return QChar(m_plus); }
scriptCode()
QString QLocalePrivate::scriptCode () const
Definition at line 181 of file qlocale.cpp.
 {
     if (m_script_id == QLocale::AnyScript || m_script_id > QLocale::LastScript)
         return QString();
     const unsigned char *c = script_code_list + 4*(uint(m_script_id));
     return QString::fromLatin1((const char *)c, 4);
 }
stringToDouble()
double QLocalePrivate::stringToDouble (const QString & num, bool * ok, GroupSeparatorMode group_sep_mode) const
Definition at line 3092 of file qlocale.cpp.
Referenced by QString::toDouble(), and QLocale::toDouble().
 {
     CharBuff buff;
     if (!numberToCLocale(group().unicode() == 0xa0 ? number.trimmed() : number,
                          group_sep_mode, &buff)) {
         if (ok != 0)
             *ok = false;
         return 0.0;
     }
     return bytearrayToDouble(buff.constData(), ok);
 }
stringToLongLong()
qlonglong QLocalePrivate::stringToLongLong (const QString & num, int base, bool * ok, GroupSeparatorMode group_sep_mode) const
Definition at line 3105 of file qlocale.cpp.
Referenced by QString::toLongLong(), and QLocale::toLongLong().
 {
     CharBuff buff;
     if (!numberToCLocale(group().unicode() == 0xa0 ? number.trimmed() : number,
                          group_sep_mode, &buff)) {
         if (ok != 0)
             *ok = false;
         return 0;
     }
     return bytearrayToLongLong(buff.constData(), base, ok);
 }
stringToUnsLongLong()
qulonglong QLocalePrivate::stringToUnsLongLong (const QString & num, int base, bool * ok, GroupSeparatorMode group_sep_mode) const
Definition at line 3119 of file qlocale.cpp.
Referenced by QString::toULongLong(), and QLocale::toULongLong().
 {
     CharBuff buff;
     if (!numberToCLocale(group().unicode() == 0xa0 ? number.trimmed() : number,
                          group_sep_mode, &buff)) {
         if (ok != 0)
             *ok = false;
         return 0;
     }
     return bytearrayToUnsLongLong(buff.constData(), base, ok);
 }
unsLongLongToString() [1/2]
QString QLocalePrivate::unsLongLongToString (const QChar zero, const QChar group, const QChar plus, quint64 l, int precision, int base, int width, unsigned flags) static
Definition at line 2870 of file qlocale.cpp.
Referenced by QString::arg(), QTextStreamPrivate::putNumber(), QByteArray::setNum(), QString::setNum(), QSystemLocalePrivate::toCurrencyString(), QLocale::toCurrencyString(), QLocale::toString(), unsLongLongToString(), and QString::vsprintf().
 {
     bool precision_not_specified = false;
     if (precision == -1) {
         precision_not_specified = true;
         precision = 1;
     }
     QString num_str = qulltoa(l, base, zero);
     uint cnt_thousand_sep = 0;
     if (flags & ThousandsGroup && base == 10) {
         for (int i = num_str.length() - 3; i > 0; i -=3) {
             num_str.insert(i, group);
             ++cnt_thousand_sep;
         }
     }
     for (int i = num_str.length()/* - cnt_thousand_sep*/; i < precision; ++i)
         num_str.prepend(base == 10 ? zero : QChar::fromLatin1('0'));
     if ((flags & Alternate || flags & ShowBase)
             && base == 8
             && (num_str.isEmpty() || num_str[0].unicode() != QLatin1Char('0')))
         num_str.prepend(QLatin1Char('0'));
     // LeftAdjusted overrides this flag ZeroPadded. sprintf only padds
     // when precision is not specified in the format string
     bool zero_padded = flags & ZeroPadded
                         && !(flags & LeftAdjusted)
                         && precision_not_specified;
     if (zero_padded) {
         int num_pad_chars = width - num_str.length();
         // leave space for optional '0x' in hex form
         if (base == 16 && flags & Alternate)
             num_pad_chars -= 2;
         // leave space for optional '0b' in binary form
         else if (base == 2 && flags & Alternate)
             num_pad_chars -= 2;
         for (int i = 0; i < num_pad_chars; ++i)
             num_str.prepend(base == 10 ? zero : QChar::fromLatin1('0'));
     }
     if (flags & CapitalEorX)
         num_str = num_str.toUpper();
     if (base == 16 && (flags & Alternate || flags & ShowBase))
         num_str.prepend(QLatin1String(flags & UppercaseBase ? "0X" : "0x"));
     else if (base == 2 && (flags & Alternate || flags & ShowBase))
         num_str.prepend(QLatin1String(flags & UppercaseBase ? "0B" : "0b"));
     // add sign
     if (flags & AlwaysShowSign)
         num_str.prepend(plus);
     else if (flags & BlankBeforePositive)
         num_str.prepend(QLatin1Char(' '));
     return num_str;
 }
unsLongLongToString() [2/2]
QString QLocalePrivate::unsLongLongToString (quint64 l, int precision = -1, int base = 10, int width = -1, unsigned flags = NoFlags) const
Definition at line 2862 of file qlocale.cpp.
 {
     return QLocalePrivate::unsLongLongToString(zero(), group(), plus(),
                                                l, precision, base, width, flags);
 }
updateSystemPrivate()
void QLocalePrivate::updateSystemPrivate () static
Definition at line 478 of file qlocale.cpp.
Referenced by QWindowSystemInterface::handleLocaleChange(), QtWndProc(), and systemPrivate().
 {
     const QSystemLocale *sys_locale = systemLocale();
     if (!system_lp)
         system_lp = globalLocalePrivate();
     // tell the object that the system locale has changed.
     sys_locale->query(QSystemLocale::LocaleChanged, QVariant());
     *system_lp = *sys_locale->fallbackLocale().d();
 #if defined(Q_OS_SYMBIAN)
     qt_symbianUpdateSystemPrivate();
 #endif
     QVariant res = sys_locale->query(QSystemLocale::LanguageId, QVariant());
     if (!res.isNull()) {
         system_lp->m_language_id = res.toInt();
         system_lp->m_script_id = QLocale::AnyScript; // default for compatibility
     }
     res = sys_locale->query(QSystemLocale::CountryId, QVariant());
     if (!res.isNull()) {
         system_lp->m_country_id = res.toInt();
         system_lp->m_script_id = QLocale::AnyScript; // default for compatibility
     }
     res = sys_locale->query(QSystemLocale::ScriptId, QVariant());
     if (!res.isNull())
         system_lp->m_script_id = res.toInt();
     res = sys_locale->query(QSystemLocale::DecimalPoint, QVariant());
     if (!res.isNull())
         system_lp->m_decimal = res.toString().at(0).unicode();
     res = sys_locale->query(QSystemLocale::GroupSeparator, QVariant());
     if (!res.isNull())
         system_lp->m_group = res.toString().at(0).unicode();
     res = sys_locale->query(QSystemLocale::ZeroDigit, QVariant());
     if (!res.isNull())
         system_lp->m_zero = res.toString().at(0).unicode();
     res = sys_locale->query(QSystemLocale::NegativeSign, QVariant());
     if (!res.isNull())
         system_lp->m_minus = res.toString().at(0).unicode();
     res = sys_locale->query(QSystemLocale::PositiveSign, QVariant());
     if (!res.isNull())
         system_lp->m_plus = res.toString().at(0).unicode();
 #ifdef QT_USE_ICU
     if (!default_lp)
         qt_initIcu(system_lp->bcp47Name());
 #endif
 }
validateChars()
bool QLocalePrivate::validateChars (const QString & str, NumberMode numMode, QByteArray * buff, int decDigits = -1) const
Definition at line 2999 of file qlocale.cpp.
Referenced by QIntValidator::fixup(), QIntValidator::validate(), and QDoubleValidatorPrivate::validateWithLocale().
 {
     buff->clear();
     buff->reserve(str.length());
     const bool scientific = numMode == DoubleScientificMode;
     bool lastWasE = false;
     bool lastWasDigit = false;
     int eCnt = 0;
     int decPointCnt = 0;
     bool dec = false;
     int decDigitCnt = 0;
     for (int i = 0; i < str.length(); ++i) {
         char c = digitToCLocale(str.at(i));
         if (c >= '0' && c <= '9') {
             if (numMode != IntegerMode) {
                 // If a double has too many digits after decpt, it shall be Invalid.
                 if (dec && decDigits != -1 && decDigits < ++decDigitCnt)
                     return false;
             }
             lastWasDigit = true;
         } else {
             switch (c) {
                 case '.':
                     if (numMode == IntegerMode) {
                         // If an integer has a decimal point, it shall be Invalid.
                         return false;
                     } else {
                         // If a double has more than one decimal point, it shall be Invalid.
                         if (++decPointCnt > 1)
                             return false;
 #if 0
                         // If a double with no decimal digits has a decimal point, it shall be
                         // Invalid.
                         if (decDigits == 0)
                             return false;
 #endif                  // On second thoughts, it shall be Valid.
                         dec = true;
                     }
                     break;
                 case '+':
                 case '-':
                     if (scientific) {
                         // If a scientific has a sign that's not at the beginning or after
                         // an 'e', it shall be Invalid.
                         if (i != 0 && !lastWasE)
                             return false;
                     } else {
                         // If a non-scientific has a sign that's not at the beginning,
                         // it shall be Invalid.
                         if (i != 0)
                             return false;
                     }
                     break;
                 case ',':
                     //it can only be placed after a digit which is before the decimal point
                     if (!lastWasDigit || decPointCnt > 0)
                         return false;
                     break;
                 case 'e':
                     if (scientific) {
                         // If a scientific has more than one 'e', it shall be Invalid.
                         if (++eCnt > 1)
                             return false;
                         dec = false;
                     } else {
                         // If a non-scientific has an 'e', it shall be Invalid.
                         return false;
                     }
                     break;
                 default:
                     // If it's not a valid digit, it shall be Invalid.
                     return false;
             }
             lastWasDigit = false;
         }
         lastWasE = c == 'e';
         if (c != ',')
             buff->append(c);
     }
     return true;
 }
zero()
QChar QLocalePrivate::zero () const inline
Definition at line 75 of file qlocale_p.h.
Referenced by QLocale::zeroDigit().
 { return QChar(m_zero); }
Properties
m_alternate_quotation_end
quint16 QLocalePrivate::m_alternate_quotation_end
Definition at line 185 of file qlocale_p.h.
m_alternate_quotation_start
quint16 QLocalePrivate::m_alternate_quotation_start
Definition at line 185 of file qlocale_p.h.
m_am_idx
quint16 QLocalePrivate::m_am_idx
Definition at line 207 of file qlocale_p.h.
m_am_size
quint16 QLocalePrivate::m_am_size
Definition at line 207 of file qlocale_p.h.
m_country_endonym_idx
quint16 QLocalePrivate::m_country_endonym_idx
Definition at line 215 of file qlocale_p.h.
m_country_endonym_size
quint16 QLocalePrivate::m_country_endonym_size
Definition at line 215 of file qlocale_p.h.
m_country_id
quint16 QLocalePrivate::m_country_id
Definition at line 180 of file qlocale_p.h.
Referenced by bcp47Name(), countryCode(), findLocale(), and QLocale::name().
m_currency_digits
quint16 QLocalePrivate::m_currency_digits
Definition at line 216 of file qlocale_p.h.
Referenced by QLocale::toCurrencyString().
m_currency_display_name_idx
quint16 QLocalePrivate::m_currency_display_name_idx
Definition at line 211 of file qlocale_p.h.
Referenced by QLocale::currencySymbol().
m_currency_display_name_size
quint16 QLocalePrivate::m_currency_display_name_size
Definition at line 211 of file qlocale_p.h.
Referenced by QLocale::currencySymbol().
m_currency_format_idx
quint8 QLocalePrivate::m_currency_format_idx
Definition at line 212 of file qlocale_p.h.
Referenced by QLocale::toCurrencyString().
m_currency_format_size
quint8 QLocalePrivate::m_currency_format_size
Definition at line 212 of file qlocale_p.h.
Referenced by QLocale::toCurrencyString().
m_currency_iso_code
char QLocalePrivate::m_currency_iso_code[3]
Definition at line 209 of file qlocale_p.h.
Referenced by QLocale::currencySymbol().
m_currency_negative_format_idx
quint8 QLocalePrivate::m_currency_negative_format_idx
Definition at line 213 of file qlocale_p.h.
Referenced by QLocale::toCurrencyString().
m_currency_negative_format_size
quint8 QLocalePrivate::m_currency_negative_format_size
Definition at line 213 of file qlocale_p.h.
Referenced by QLocale::toCurrencyString().
m_currency_rounding
quint16 QLocalePrivate::m_currency_rounding
Definition at line 217 of file qlocale_p.h.
m_currency_symbol_idx
quint16 QLocalePrivate::m_currency_symbol_idx
Definition at line 210 of file qlocale_p.h.
Referenced by QLocale::currencySymbol().
m_currency_symbol_size
quint16 QLocalePrivate::m_currency_symbol_size
Definition at line 210 of file qlocale_p.h.
Referenced by QLocale::currencySymbol().
m_decimal
quint16 QLocalePrivate::m_decimal
Definition at line 182 of file qlocale_p.h.
m_exponential
quint16 QLocalePrivate::m_exponential
Definition at line 182 of file qlocale_p.h.
m_first_day_of_week
quint16 QLocalePrivate::m_first_day_of_week
Definition at line 218 of file qlocale_p.h.
Referenced by QLocale::firstDayOfWeek().
m_group
quint16 QLocalePrivate::m_group
Definition at line 182 of file qlocale_p.h.
m_language_endonym_idx
quint16 QLocalePrivate::m_language_endonym_idx
Definition at line 214 of file qlocale_p.h.
m_language_endonym_size
quint16 QLocalePrivate::m_language_endonym_size
Definition at line 214 of file qlocale_p.h.
m_language_id
quint16 QLocalePrivate::m_language_id
Definition at line 180 of file qlocale_p.h.
Referenced by bcp47Name(), findLocale(), languageCode(), QLocale::matchingLocales(), and QLocale::name().
m_list
quint16 QLocalePrivate::m_list
Definition at line 182 of file qlocale_p.h.
m_list_pattern_part_end_idx
quint16 QLocalePrivate::m_list_pattern_part_end_idx
Definition at line 189 of file qlocale_p.h.
m_list_pattern_part_end_size
quint16 QLocalePrivate::m_list_pattern_part_end_size
Definition at line 189 of file qlocale_p.h.
m_list_pattern_part_mid_idx
quint16 QLocalePrivate::m_list_pattern_part_mid_idx
Definition at line 188 of file qlocale_p.h.
m_list_pattern_part_mid_size
quint16 QLocalePrivate::m_list_pattern_part_mid_size
Definition at line 188 of file qlocale_p.h.
m_list_pattern_part_start_idx
quint16 QLocalePrivate::m_list_pattern_part_start_idx
Definition at line 187 of file qlocale_p.h.
m_list_pattern_part_start_size
quint16 QLocalePrivate::m_list_pattern_part_start_size
Definition at line 187 of file qlocale_p.h.
m_list_pattern_part_two_idx
quint16 QLocalePrivate::m_list_pattern_part_two_idx
Definition at line 190 of file qlocale_p.h.
m_list_pattern_part_two_size
quint16 QLocalePrivate::m_list_pattern_part_two_size
Definition at line 190 of file qlocale_p.h.
m_long_date_format_idx
quint16 QLocalePrivate::m_long_date_format_idx
Definition at line 192 of file qlocale_p.h.
Referenced by QLocale::dateFormat().
m_long_date_format_size
quint16 QLocalePrivate::m_long_date_format_size
Definition at line 192 of file qlocale_p.h.
Referenced by QLocale::dateFormat().
m_long_day_names_idx
quint16 QLocalePrivate::m_long_day_names_idx
Definition at line 205 of file qlocale_p.h.
Referenced by QLocale::dayName().
m_long_day_names_size
quint16 QLocalePrivate::m_long_day_names_size
Definition at line 205 of file qlocale_p.h.
Referenced by QLocale::dayName().
m_long_month_names_idx
quint16 QLocalePrivate::m_long_month_names_idx
Definition at line 199 of file qlocale_p.h.
Referenced by QLocale::monthName().
m_long_month_names_size
quint16 QLocalePrivate::m_long_month_names_size
Definition at line 199 of file qlocale_p.h.
Referenced by QLocale::monthName().
m_long_time_format_idx
quint16 QLocalePrivate::m_long_time_format_idx
Definition at line 194 of file qlocale_p.h.
Referenced by QLocale::timeFormat().
m_long_time_format_size
quint16 QLocalePrivate::m_long_time_format_size
Definition at line 194 of file qlocale_p.h.
Referenced by QLocale::timeFormat().
m_minus
quint16 QLocalePrivate::m_minus
Definition at line 182 of file qlocale_p.h.
m_narrow_day_names_idx
quint16 QLocalePrivate::m_narrow_day_names_idx
Definition at line 206 of file qlocale_p.h.
Referenced by QLocale::dayName().
m_narrow_day_names_size
quint16 QLocalePrivate::m_narrow_day_names_size
Definition at line 206 of file qlocale_p.h.
Referenced by QLocale::dayName().
m_narrow_month_names_idx
quint16 QLocalePrivate::m_narrow_month_names_idx
Definition at line 200 of file qlocale_p.h.
Referenced by QLocale::monthName().
m_narrow_month_names_size
quint16 QLocalePrivate::m_narrow_month_names_size
Definition at line 200 of file qlocale_p.h.
Referenced by QLocale::monthName().
m_percent
quint16 QLocalePrivate::m_percent
Definition at line 182 of file qlocale_p.h.
m_plus
quint16 QLocalePrivate::m_plus
Definition at line 182 of file qlocale_p.h.
m_pm_idx
quint16 QLocalePrivate::m_pm_idx
Definition at line 208 of file qlocale_p.h.
m_pm_size
quint16 QLocalePrivate::m_pm_size
Definition at line 208 of file qlocale_p.h.
m_quotation_end
quint16 QLocalePrivate::m_quotation_end
Definition at line 184 of file qlocale_p.h.
m_quotation_start
quint16 QLocalePrivate::m_quotation_start
Definition at line 184 of file qlocale_p.h.
m_script_id
quint16 QLocalePrivate::m_script_id
Definition at line 180 of file qlocale_p.h.
Referenced by bcp47Name(), findLocale(), and scriptCode().
m_short_date_format_idx
quint16 QLocalePrivate::m_short_date_format_idx
Definition at line 191 of file qlocale_p.h.
Referenced by QLocale::dateFormat().
m_short_date_format_size
quint16 QLocalePrivate::m_short_date_format_size
Definition at line 191 of file qlocale_p.h.
Referenced by QLocale::dateFormat().
m_short_day_names_idx
quint16 QLocalePrivate::m_short_day_names_idx
Definition at line 204 of file qlocale_p.h.
Referenced by QLocale::dayName().
m_short_day_names_size
quint16 QLocalePrivate::m_short_day_names_size
Definition at line 204 of file qlocale_p.h.
Referenced by QLocale::dayName().
m_short_month_names_idx
quint16 QLocalePrivate::m_short_month_names_idx
Definition at line 198 of file qlocale_p.h.
Referenced by QLocale::monthName().
m_short_month_names_size
quint16 QLocalePrivate::m_short_month_names_size
Definition at line 198 of file qlocale_p.h.
Referenced by QLocale::monthName().
m_short_time_format_idx
quint16 QLocalePrivate::m_short_time_format_idx
Definition at line 193 of file qlocale_p.h.
Referenced by QLocale::timeFormat().
m_short_time_format_size
quint16 QLocalePrivate::m_short_time_format_size
Definition at line 193 of file qlocale_p.h.
Referenced by QLocale::timeFormat().
m_standalone_long_day_names_idx
quint16 QLocalePrivate::m_standalone_long_day_names_idx
Definition at line 202 of file qlocale_p.h.
Referenced by QLocale::standaloneDayName().
m_standalone_long_day_names_size
quint16 QLocalePrivate::m_standalone_long_day_names_size
Definition at line 202 of file qlocale_p.h.
Referenced by QLocale::standaloneDayName().
m_standalone_long_month_names_idx
quint16 QLocalePrivate::m_standalone_long_month_names_idx
Definition at line 196 of file qlocale_p.h.
Referenced by QLocale::standaloneMonthName().
m_standalone_long_month_names_size
quint16 QLocalePrivate::m_standalone_long_month_names_size
Definition at line 196 of file qlocale_p.h.
Referenced by QLocale::standaloneMonthName().
m_standalone_narrow_day_names_idx
quint16 QLocalePrivate::m_standalone_narrow_day_names_idx
Definition at line 203 of file qlocale_p.h.
Referenced by QLocale::standaloneDayName().
m_standalone_narrow_day_names_size
quint16 QLocalePrivate::m_standalone_narrow_day_names_size
Definition at line 203 of file qlocale_p.h.
Referenced by QLocale::standaloneDayName().
m_standalone_narrow_month_names_idx
quint16 QLocalePrivate::m_standalone_narrow_month_names_idx
Definition at line 197 of file qlocale_p.h.
Referenced by QLocale::standaloneMonthName().
m_standalone_narrow_month_names_size
quint16 QLocalePrivate::m_standalone_narrow_month_names_size
Definition at line 197 of file qlocale_p.h.
Referenced by QLocale::standaloneMonthName().
m_standalone_short_day_names_idx
quint16 QLocalePrivate::m_standalone_short_day_names_idx
Definition at line 201 of file qlocale_p.h.
Referenced by QLocale::standaloneDayName().
m_standalone_short_day_names_size
quint16 QLocalePrivate::m_standalone_short_day_names_size
Definition at line 201 of file qlocale_p.h.
Referenced by QLocale::standaloneDayName().
m_standalone_short_month_names_idx
quint16 QLocalePrivate::m_standalone_short_month_names_idx
Definition at line 195 of file qlocale_p.h.
Referenced by QLocale::standaloneMonthName().
m_standalone_short_month_names_size
quint16 QLocalePrivate::m_standalone_short_month_names_size
Definition at line 195 of file qlocale_p.h.
Referenced by QLocale::standaloneMonthName().
m_weekend_end
quint16 QLocalePrivate::m_weekend_end
Definition at line 220 of file qlocale_p.h.
Referenced by QLocale::weekdays().
m_weekend_start
quint16 QLocalePrivate::m_weekend_start
Definition at line 219 of file qlocale_p.h.
Referenced by QLocale::weekdays().
m_zero
quint16 QLocalePrivate::m_zero
Definition at line 182 of file qlocale_p.h.
The documentation for this struct was generated from the following files:
/src/corelib/tools/qlocale_p.h
/src/corelib/tools/qlocale.cpp