Qt 4.8: IAxServerBase Struct Reference
IAxServerBase Struct Reference abstract
#include <qaxtypes.h>
Public Functions
virtual IUnknown * clientSite () const =0
virtual void emitPropertyChanged (const char *)=0
virtual bool emitRequestPropertyChange (const char *)=0
virtual QObject * qObject () const =0
virtual void reportError (int code, const QString &src, const QString &desc, const QString &context)=0
Detailed Description
Definition at line 62 of file qaxtypes.h.
Functions
clientSite()
virtual IUnknown* IAxServerBase::clientSite () const pure virtual
Implemented in QAxServerBase.
Referenced by QAxBindable::clientSite().
emitPropertyChanged()
virtual void IAxServerBase::emitPropertyChanged (const char *) pure virtual
Implemented in QAxServerBase.
Referenced by QAxBindable::propertyChanged().
emitRequestPropertyChange()
virtual bool IAxServerBase::emitRequestPropertyChange (const char *) pure virtual
Implemented in QAxServerBase.
Referenced by QAxBindable::requestPropertyChange().
qObject()
virtual QObject* IAxServerBase::qObject () const pure virtual
Implemented in QAxServerBase.
reportError()
virtual void IAxServerBase::reportError (int code, const QString & src, const QString & desc, const QString & context) pure virtual
Implemented in QAxServerBase.
Referenced by QAxBindable::reportError().
The documentation for this struct was generated from the following file:
/src/activeqt/shared/qaxtypes.h