Qt 4.8: QTessellatorPrivate::Vertices Struct Reference
QTessellatorPrivate::Vertices Struct Reference
Public Types
enum { default_alloc = 128 }
Public Functions
void done ()
void init (int maxVertices)
Vertex * next (Vertex *v)
const Vertex * next (const Vertex *v) const
int nextPos (const Vertex *v) const
Vertex * operator[] (int i)
const Vertex * operator[] (int i) const
int position (const Vertex *v) const
Vertex * prev (Vertex *v)
const Vertex * prev (const Vertex *v) const
int prevPos (const Vertex *v) const
Vertices ()
~Vertices ()
Public Variables
int allocated
int nPoints
Vertex ** sorted
Vertex * storage
Detailed Description
Definition at line 175 of file qtessellator.cpp.
Enumerations
anonymous enum
anonymous enum
Enumerator
default_alloc
Definition at line 176 of file qtessellator.cpp.
 { default_alloc = 128 };
Constructors and Destructors
Vertices()
QTessellatorPrivate::Vertices::Vertices ()
Definition at line 549 of file qtessellator.cpp.
 {
     storage = 0;
     sorted = 0;
     allocated = 0;
     nPoints = 0;
 }
~Vertices()
QTessellatorPrivate::Vertices::~Vertices ()
Definition at line 557 of file qtessellator.cpp.
 {
     if (storage) {
         free(storage);
         free(sorted);
     }
 }
Functions
done()
void QTessellatorPrivate::Vertices::done ()
Definition at line 575 of file qtessellator.cpp.
 {
     if (allocated > default_alloc) {
         free(storage);
         free(sorted);
         storage = 0;
         sorted = 0;
         allocated = 0;
     }
 }
init()
void QTessellatorPrivate::Vertices::init (int maxVertices)
Definition at line 565 of file qtessellator.cpp.
 {
     if (!storage || maxVertices > allocated) {
         int size = qMax((int)default_alloc, maxVertices);
         storage = q_check_ptr((Vertex *)realloc(storage, size*sizeof(Vertex)));
         sorted = q_check_ptr((Vertex **)realloc(sorted, size*sizeof(Vertex *)));
         allocated = maxVertices;
     }
 }
next() [1/2]
Vertex* QTessellatorPrivate::Vertices::next (Vertex * v) inline
Definition at line 189 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::addEdges(), QTessellatorPrivate::cancelCoincidingEdges(), QTessellatorPrivate::Edge::Edge(), and fillTrapezoid().
{
             ++v;
             if (v == storage + nPoints)
                 v = storage;
             return v;
         }
next() [2/2]
const Vertex* QTessellatorPrivate::Vertices::next (const Vertex * v) const inline
Definition at line 195 of file qtessellator.cpp.
{
             ++v;
             if (v == storage + nPoints)
                 v = storage;
             return v;
         }
nextPos()
int QTessellatorPrivate::Vertices::nextPos (const Vertex * v) const inline
Definition at line 201 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::addIntersection().
{
             ++v;
             if (v == storage + nPoints)
                 return 0;
             return v - storage;
         }
operator[]() [1/2]
Vertex* QTessellatorPrivate::Vertices::operator[] (int i) inline
Definition at line 184 of file qtessellator.cpp.
 { return storage + i; }
operator[]() [2/2]
const Vertex* QTessellatorPrivate::Vertices::operator[] (int i) const inline
Definition at line 185 of file qtessellator.cpp.
 { return storage + i; }
position()
int QTessellatorPrivate::Vertices::position (const Vertex * v) const inline
Definition at line 186 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::addEdges(), and QTessellatorPrivate::removeEdges().
{
             return v - storage;
         }
prev() [1/2]
Vertex* QTessellatorPrivate::Vertices::prev (Vertex * v) inline
Definition at line 207 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::cancelCoincidingEdges().
{
             if (v == storage)
                 v = storage + nPoints;
             --v;
             return v;
         }
prev() [2/2]
const Vertex* QTessellatorPrivate::Vertices::prev (const Vertex * v) const inline
Definition at line 213 of file qtessellator.cpp.
{
             if (v == storage)
                 v = storage + nPoints;
             --v;
             return v;
         }
prevPos()
int QTessellatorPrivate::Vertices::prevPos (const Vertex * v) const inline
Definition at line 219 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::addEdges(), QTessellatorPrivate::addIntersection(), and QTessellatorPrivate::removeEdges().
{
             if (v == storage)
                 v = storage + nPoints;
             --v;
             return v - storage;
         }
Properties
allocated
int QTessellatorPrivate::Vertices::allocated
Definition at line 226 of file qtessellator.cpp.
nPoints
int QTessellatorPrivate::Vertices::nPoints
Definition at line 225 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::addEdges(), QTessellatorPrivate::cancelCoincidingEdges(), QTessellatorPrivate::collectAndSortVertices(), and QTessellatorPrivate::removeEdges().
sorted
Vertex** QTessellatorPrivate::Vertices::sorted
Definition at line 182 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::addEdges(), QTessellatorPrivate::cancelCoincidingEdges(), QTessellatorPrivate::collectAndSortVertices(), and QTessellatorPrivate::removeEdges().
storage
Vertex* QTessellatorPrivate::Vertices::storage
Definition at line 181 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::collectAndSortVertices().
The documentation for this struct was generated from the following file:
/src/gui/painting/qtessellator.cpp