Qt 4.8: QWSIdentifyCommand Struct Reference
QWSIdentifyCommand Struct Reference
#include <qwscommand_qws_p.h>
Classes
struct SimpleData
Public Functions
QWSIdentifyCommand ()
void setData (const char *d, int len, bool allocateMem)
void setId (const QString &i, int lock)
Public Functions inherited from QWSCommand
QWSCommand (int t, int len, char *ptr)
Public Functions inherited from QWSProtocolItem
void copyFrom (const QWSProtocolItem *item)
QWSProtocolItem (int t, int len, char *ptr)
bool read (QIODevice *s)
void write (QIODevice *s)
virtual ~QWSProtocolItem ()
Public Variables
QString id
struct QWSIdentifyCommand::SimpleData simpleData
Public Variables inherited from QWSProtocolItem
int bytesRead
bool deleteRaw
char * rawDataPtr
int rawLen
char * simpleDataPtr
int simpleLen
int type
Additional Inherited Members
Public Types inherited from QWSCommand
enum Type {
Unknown = 0, Create, Shutdown, Region,
RegionMove, RegionDestroy, SetProperty, AddProperty,
RemoveProperty, GetProperty, SetSelectionOwner, ConvertSelection,
RequestFocus, ChangeAltitude, SetOpacity, DefineCursor,
SelectCursor, PositionCursor, GrabMouse, PlaySound,
QCopRegisterChannel, QCopSend, RegionName, Identify,
GrabKeyboard, RepaintRegion, IMMouse, IMUpdate,
IMResponse, Embed, Font, ScreenTransform
}
Static Public Functions inherited from QWSCommand
static QWSCommand * factory (int type)
Detailed Description
Definition at line 144 of file qwscommand_qws_p.h.
Constructors and Destructors
QWSIdentifyCommand()
QWSIdentifyCommand::QWSIdentifyCommand () inline
Definition at line 146 of file qwscommand_qws_p.h.
                          :
         QWSCommand(QWSCommand::Identify,
                    sizeof(simpleData), reinterpret_cast<char *>(&simpleData))
     {
         simpleData.idLen = 0;
         simpleData.idLock = -1;
     }
Functions
setData()
void QWSIdentifyCommand::setData (const char * d, int len, bool allocateMem) inline virtual
Reimplemented from QWSProtocolItem.
Definition at line 154 of file qwscommand_qws_p.h.
{
         QWSCommand::setData(d, len, allocateMem);
         if ( simpleData.idLen > MAX_COMMAND_SIZE )
         {
             qWarning( "Identify command - name length %d - too big!", simpleData.idLen );
             simpleData.idLen = MAX_COMMAND_SIZE;
         }
         if ( simpleData.idLen * int(sizeof(QChar)) > len )
         {
             qWarning( "Identify command - name length %d - buffer size %d - buffer overrun!", simpleData.idLen, len );
         }
         else
         {
             id = QString(reinterpret_cast<const QChar*>(d), simpleData.idLen);
         }
     }
setId()
void QWSIdentifyCommand::setId (const QString & i, int lock) inline
Definition at line 171 of file qwscommand_qws_p.h.
Referenced by QWSDisplay::Data::init(), QWSDisplay::Data::reinit(), and QWSDisplay::setIdentity().
     {
         id = i;
         simpleData.idLen = id.length();
         simpleData.idLock = lock;
         setData(reinterpret_cast<const char*>(id.unicode()), simpleData.idLen*2, true);
     }
Properties
id
QString QWSIdentifyCommand::id
Definition at line 183 of file qwscommand_qws_p.h.
Referenced by QWSServerPrivate::invokeIdentify().
simpleData
struct QWSIdentifyCommand::SimpleData QWSIdentifyCommand::simpleData
Referenced by QWSServerPrivate::invokeIdentify().
The documentation for this struct was generated from the following file:
/src/gui/embedded/qwscommand_qws_p.h