Qt 4.8: QWaylandDisplay Class Reference
QWaylandDisplay Class Reference
#include <qwaylanddisplay.h>
Public Slots
void blockingReadEvents ()
void createNewScreen (struct wl_output *output, QRect geometry)
void flushRequests ()
void readEvents ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
struct wl_visual * argbPremultipliedVisual ()
struct wl_visual * argbVisual ()
struct wl_buffer * createShmBuffer (int fd, int width, int height, uint32_t stride, struct wl_visual *visual)
struct wl_surface * createSurface (void *handle)
void frameCallback (wl_display_frame_func_t func, struct wl_surface *surface, void *data)
QList< QWaylandInputDevice * > inputDevices () const
QWaylandDisplay (void)
struct wl_visual * rgbVisual ()
QList< QPlatformScreen * > screens () const
void setCursor (QWaylandBuffer *buffer, int32_t x, int32_t y)
void syncCallback (wl_display_sync_func_t func, void *data)
struct wl_display * wl_display () const
struct wl_shell * wl_shell () const
~QWaylandDisplay (void)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Functions
void displayHandleGlobal (uint32_t id, const QByteArray &interface, uint32_t version)
void waitForScreens ()
Static Private Functions
static void displayHandleGlobal (struct wl_display *display, uint32_t id, const char *interface, uint32_t version, void *data)
static void handleVisual (void *data, struct wl_compositor *compositor, uint32_t id, uint32_t token)
static void mode (void *data, struct wl_output *wl_output, uint32_t flags, int width, int height, int refresh)
static void outputHandleGeometry (void *data, struct wl_output *output, int32_t x, int32_t y, int32_t width, int32_t height, int subpixel, const char *make, const char *model)
static void shellHandleConfigure (void *data, struct wl_shell *shell, uint32_t time, uint32_t edges, struct wl_surface *surface, int32_t width, int32_t height)
static int sourceUpdate (uint32_t mask, void *data)
Properties
struct wl_visual * argb_visual
struct wl_compositor * mCompositor
struct wl_display * mDisplay
int mFd
QList< QWaylandInputDevice * > mInputDevices
QSocketNotifier * mReadNotifier
QList< QPlatformScreen * > mScreens
bool mScreensInitialized
struct wl_shell * mShell
struct wl_shm * mShm
uint32_t mSocketMask
struct wl_visual * premultiplied_argb_visual
struct wl_visual * rgb_visual
Static Private Attributes
static const struct wl_compositor_listener compositorListener
static const struct wl_output_listener outputListener
static const struct wl_shell_listener shellListener
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 125 of file qwaylanddisplay.cpp.
Constructors and Destructors
QWaylandDisplay()
QWaylandDisplay::QWaylandDisplay (void)
Definition at line 129 of file qwaylanddisplay.cpp.
     : argb_visual(0), premultiplied_argb_visual(0), rgb_visual(0)
 {
     mDisplay = wl_display_connect(NULL);
     if (mDisplay == NULL) {
         qErrnoWarning(errno, "Failed to create display");
         qFatal("No wayland connection available.");
     }
     wl_display_add_global_listener(mDisplay, QWaylandDisplay::displayHandleGlobal, this);
 #ifdef QT_WAYLAND_GL_SUPPORT
     mEglIntegration = QWaylandGLIntegration::createGLIntegration(this);
 #endif
 #ifdef QT_WAYLAND_WINDOWMANAGER_SUPPORT
     mWindowManagerIntegration = QWaylandWindowManagerIntegration::createIntegration(this);
 #endif
     blockingReadEvents();
     qRegisterMetaType<uint32_t>("uint32_t");
 #ifdef QT_WAYLAND_GL_SUPPORT
     mEglIntegration->initialize();
 #endif
     connect(QAbstractEventDispatcher::instance(), SIGNAL(aboutToBlock()), this, SLOT(flushRequests()));
     mFd = wl_display_get_fd(mDisplay, sourceUpdate, this);
     mReadNotifier = new QSocketNotifier(mFd, QSocketNotifier::Read, this);
     connect(mReadNotifier, SIGNAL(activated(int)), this, SLOT(readEvents()));
     waitForScreens();
 }
~QWaylandDisplay()
QWaylandDisplay::~QWaylandDisplay (void)
Definition at line 166 of file qwaylanddisplay.cpp.
 {
     close(mFd);
 #ifdef QT_WAYLAND_GL_SUPPORT
     delete mEglIntegration;
 #endif
     wl_display_destroy(mDisplay);
 }
Functions
argbPremultipliedVisual()
struct wl_visual * QWaylandDisplay::argbPremultipliedVisual ()
Definition at line 92 of file qwaylanddisplay.cpp.
Referenced by screens(), and QWaylandScreen::visual().
 {
     return premultiplied_argb_visual;
 }
argbVisual()
struct wl_visual * QWaylandDisplay::argbVisual ()
Definition at line 87 of file qwaylanddisplay.cpp.
Referenced by QWaylandXCompositeEGLContext::geometryChanged(), QWaylandXCompositeGLXContext::geometryChanged(), QWaylandShmBuffer::QWaylandShmBuffer(), screens(), and QWaylandScreen::visual().
 {
     return argb_visual;
 }
blockingReadEvents
void QWaylandDisplay::blockingReadEvents () slot
Definition at line 221 of file qwaylanddisplay.cpp.
Referenced by inputDevices(), QWaylandDisplay(), QWaylandWindow::waitForFrameSync(), and waitForScreens().
 {
     wl_display_iterate(mDisplay, WL_DISPLAY_READABLE);
 }
createNewScreen
void QWaylandDisplay::createNewScreen (struct wl_output * output, QRect geometry) slot
Definition at line 175 of file qwaylanddisplay.cpp.
Referenced by inputDevices(), and outputHandleGeometry().
 {
     QWaylandScreen *waylandScreen = new QWaylandScreen(this,output,geometry);
     mScreens.append(waylandScreen);
 }
createShmBuffer()
struct wl_buffer * QWaylandDisplay::createShmBuffer (int fd, int width, int height, uint32_t stride, struct wl_visual * visual)
Definition at line 74 of file qwaylanddisplay.cpp.
Referenced by QWaylandShmBuffer::QWaylandShmBuffer(), and screens().
 {
     return wl_shm_create_buffer(mShm, fd, width, height, stride, visual);
 }
createSurface()
struct wl_surface * QWaylandDisplay::createSurface (void * handle)
Definition at line 67 of file qwaylanddisplay.cpp.
Referenced by screens(), and QWaylandWindow::setVisible().
 {
     struct wl_surface * surface = wl_compositor_create_surface(mCompositor);
     wl_surface_set_user_data(surface, handle);
     return surface;
 }
displayHandleGlobal() [1/2]
void QWaylandDisplay::displayHandleGlobal (uint32_t id, const QByteArray & interface, uint32_t version) private
Definition at line 290 of file qwaylanddisplay.cpp.
Referenced by displayHandleGlobal(), inputDevices(), and QWaylandDisplay().
 {
     Q_UNUSED(version);
     if (interface == "wl_output") {
         struct wl_output *output = wl_output_create(mDisplay, id, 1);
         wl_output_add_listener(output, &outputListener, this);
     } else if (interface == "wl_compositor") {
         mCompositor = wl_compositor_create(mDisplay, id, 1);
         wl_compositor_add_listener(mCompositor,
                                    &compositorListener, this);
     } else if (interface == "wl_shm") {
         mShm = wl_shm_create(mDisplay, id, 1);
     } else if (interface == "wl_shell"){
         mShell = wl_shell_create(mDisplay, id, 1);
         wl_shell_add_listener(mShell, &shellListener, this);
     } else if (interface == "wl_input_device") {
         QWaylandInputDevice *inputDevice =
             new QWaylandInputDevice(mDisplay, id);
         mInputDevices.append(inputDevice);
     } else if (interface == "wl_selection_offer") {
         QPlatformIntegration *plat = QApplicationPrivate::platformIntegration();
         QWaylandClipboard *clipboard = static_cast<QWaylandClipboard *>(plat->clipboard());
         clipboard->createSelectionOffer(id);
     }
 }
displayHandleGlobal() [2/2]
void QWaylandDisplay::displayHandleGlobal (struct wl_display * display, uint32_t id, const char * interface, uint32_t version, void * data) static private
Definition at line 279 of file qwaylanddisplay.cpp.
 {
     Q_UNUSED(display);
     QWaylandDisplay *that = static_cast<QWaylandDisplay *>(data);
     that->displayHandleGlobal(id, QByteArray(interface), version);
 }
flushRequests
void QWaylandDisplay::flushRequests () slot
Definition at line 191 of file qwaylanddisplay.cpp.
Referenced by QWaylandXCompositeEGLContext::geometryChanged(), inputDevices(), QWaylandDisplay(), QWaylandWindow::waitForFrameSync(), waitForScreens(), and QWaylandXCompositeGLXContext::waitForSync().
 {
     if (mSocketMask & WL_DISPLAY_WRITABLE)
         wl_display_iterate(mDisplay, WL_DISPLAY_WRITABLE);
 }
frameCallback()
void QWaylandDisplay::frameCallback (wl_display_frame_func_t func, struct wl_surface * surface, void * data)
Definition at line 186 of file qwaylanddisplay.cpp.
Referenced by QWaylandWindow::damage(), and screens().
 {
     wl_display_frame_callback(mDisplay, surface, func, data);
 }
handleVisual()
void QWaylandDisplay::handleVisual (void * data, struct wl_compositor * compositor, uint32_t id, uint32_t token) static private
Definition at line 318 of file qwaylanddisplay.cpp.
Referenced by mode().
 {
     QWaylandDisplay *self = static_cast<QWaylandDisplay *>(data);
     switch (token) {
     case WL_COMPOSITOR_VISUAL_ARGB32:
         self->argb_visual = wl_visual_create(self->mDisplay, id, 1);
         break;
     case WL_COMPOSITOR_VISUAL_PREMULTIPLIED_ARGB32:
         self->premultiplied_argb_visual =
             wl_visual_create(self->mDisplay, id, 1);
         break;
     case WL_COMPOSITOR_VISUAL_XRGB32:
         self->rgb_visual = wl_visual_create(self->mDisplay, id, 1);
         break;
     }
 }
inputDevices()
QList<QWaylandInputDevice *> QWaylandDisplay::inputDevices () const inline
Definition at line 92 of file qwaylanddisplay.h.
Referenced by QWaylandSelection::QWaylandSelection(), QWaylandClipboard::setMimeData(), and QWaylandWindow::~QWaylandWindow().
 { return mInputDevices; }
mode()
void QWaylandDisplay::mode (void * data, struct wl_output * wl_output, uint32_t flags, int width, int height, int refresh) static private
Definition at line 247 of file qwaylanddisplay.cpp.
 {
     Q_UNUSED(data);
     Q_UNUSED(wl_output);
     Q_UNUSED(flags);
     Q_UNUSED(width);
     Q_UNUSED(height);
     Q_UNUSED(refresh);
 }
outputHandleGeometry()
void QWaylandDisplay::outputHandleGeometry (void * data, struct wl_output * output, int32_t x, int32_t y, int32_t width, int32_t height, int subpixel, const char * make, const char * model) static private
Definition at line 234 of file qwaylanddisplay.cpp.
Referenced by mode().
 {
     QWaylandDisplay *waylandDisplay = static_cast<QWaylandDisplay *>(data);
     QRect outputRect = QRect(x, y, physicalWidth, physicalHeight);
     waylandDisplay->createNewScreen(output,outputRect);
 }
readEvents
void QWaylandDisplay::readEvents () slot
Definition at line 197 of file qwaylanddisplay.cpp.
Referenced by QWaylandXCompositeEGLContext::geometryChanged(), inputDevices(), QWaylandDisplay(), and QWaylandXCompositeGLXContext::waitForSync().
 {
 // verify that there is still data on the socket
     fd_set fds;
     FD_ZERO(&fds);
     FD_SET(mFd, &fds);
     fd_set nds;
     FD_ZERO(&nds);
     fd_set rs = fds;
     fd_set ws = nds;
     fd_set es = nds;
     timeval timeout;
     timeout.tv_sec = 0;
     timeout.tv_usec = 0;
     int ret = ::select(mFd+1, &rs, &ws, &es, &timeout );
     if (ret <= 0) {
         //qDebug("QWaylandDisplay::readEvents() No data... blocking avoided");
         return;
     }
     wl_display_iterate(mDisplay, WL_DISPLAY_READABLE);
 }
rgbVisual()
struct wl_visual * QWaylandDisplay::rgbVisual ()
Definition at line 82 of file qwaylanddisplay.cpp.
Referenced by screens().
 {
     return rgb_visual;
 }
screens()
QList<QPlatformScreen *> QWaylandDisplay::screens () const inline
Definition at line 67 of file qwaylanddisplay.h.
Referenced by QWaylandIntegration::screens().
 { return mScreens; }
setCursor()
void QWaylandDisplay::setCursor (QWaylandBuffer * buffer, int32_t x, int32_t y)
Definition at line 183 of file qwaylandcursor.cpp.
Referenced by QWaylandCursor::changeCursor(), and screens().
 {
     /* Qt doesn't tell us which input device we should set the cursor
      * for, so set it for all devices. */
     for (int i = 0; i < mInputDevices.count(); i++) {
         QWaylandInputDevice *inputDevice = mInputDevices.at(i);
         inputDevice->attach(buffer, x, y);
     }
 }
shellHandleConfigure()
void QWaylandDisplay::shellHandleConfigure (void * data, struct wl_shell * shell, uint32_t time, uint32_t edges, struct wl_surface * surface, int32_t width, int32_t height) static private
Definition at line 111 of file qwaylanddisplay.cpp.
 {
     Q_UNUSED(data);
     Q_UNUSED(shell);
     Q_UNUSED(time);
     Q_UNUSED(edges);
     QWaylandWindow *ww = (QWaylandWindow *) wl_surface_get_user_data(surface);
     ww->configure(time, edges, 0, 0, width, height);
 }
sourceUpdate()
int QWaylandDisplay::sourceUpdate (uint32_t mask, void * data) static private
Definition at line 226 of file qwaylanddisplay.cpp.
Referenced by QWaylandDisplay().
 {
     QWaylandDisplay *waylandDisplay = static_cast<QWaylandDisplay *>(data);
     waylandDisplay->mSocketMask = mask;
     return 0;
 }
syncCallback()
void QWaylandDisplay::syncCallback (wl_display_sync_func_t func, void * data)
Definition at line 181 of file qwaylanddisplay.cpp.
Referenced by screens().
 {
     wl_display_sync_callback(mDisplay, func, data);
 }
waitForScreens()
void QWaylandDisplay::waitForScreens () private
Definition at line 272 of file qwaylanddisplay.cpp.
Referenced by inputDevices(), and QWaylandDisplay().
 {
     flushRequests();
     while (mScreens.isEmpty())
         blockingReadEvents();
 }
wl_display()
struct wl_display* QWaylandDisplay::wl_display () const inline
Definition at line 89 of file qwaylanddisplay.h.
Referenced by QWaylandClipboard::createSelectionOffer(), QWaylandEglIntegration::eglDisplay(), QWaylandXCompositeEGLContext::geometryChanged(), QWaylandNativeInterface::nativeResourceForWidget(), QWaylandWindowManagerIntegration::QWaylandWindowManagerIntegration(), QWaylandXCompositeEGLIntegration::QWaylandXCompositeEGLIntegration(), QWaylandXCompositeGLXIntegration::QWaylandXCompositeGLXIntegration(), QWaylandClipboard::retrieveData(), and QWaylandXCompositeGLXContext::waitForSync().
 { return mDisplay; }
wl_shell()
struct wl_shell* QWaylandDisplay::wl_shell () const inline
Definition at line 90 of file qwaylanddisplay.h.
Referenced by QWaylandSelection::QWaylandSelection().
 { return mShell; }
Properties
argb_visual
struct wl_visual* QWaylandDisplay::argb_visual private
Definition at line 119 of file qwaylanddisplay.h.
Referenced by argbVisual(), and handleVisual().
compositorListener
const struct wl_compositor_listener QWaylandDisplay::compositorListener static private
Definition at line 122 of file qwaylanddisplay.h.
Referenced by displayHandleGlobal(), and mode().
mCompositor
struct wl_compositor* QWaylandDisplay::mCompositor private
Definition at line 107 of file qwaylanddisplay.h.
Referenced by createSurface(), and displayHandleGlobal().
mDisplay
struct wl_display* QWaylandDisplay::mDisplay private
Definition at line 106 of file qwaylanddisplay.h.
Referenced by blockingReadEvents(), displayHandleGlobal(), flushRequests(), frameCallback(), QWaylandDisplay(), readEvents(), syncCallback(), wl_display(), and ~QWaylandDisplay().
mFd
int QWaylandDisplay::mFd private
Definition at line 114 of file qwaylanddisplay.h.
Referenced by QWaylandDisplay(), readEvents(), and ~QWaylandDisplay().
mInputDevices
QList<QWaylandInputDevice *> QWaylandDisplay::mInputDevices private
Definition at line 111 of file qwaylanddisplay.h.
Referenced by displayHandleGlobal(), and inputDevices().
mReadNotifier
QSocketNotifier* QWaylandDisplay::mReadNotifier private
Definition at line 113 of file qwaylanddisplay.h.
Referenced by QWaylandDisplay().
mScreens
QList<QPlatformScreen *> QWaylandDisplay::mScreens private
Definition at line 110 of file qwaylanddisplay.h.
Referenced by createNewScreen(), screens(), and waitForScreens().
mScreensInitialized
bool QWaylandDisplay::mScreensInitialized private
Definition at line 115 of file qwaylanddisplay.h.
mShell
struct wl_shell* QWaylandDisplay::mShell private
Definition at line 109 of file qwaylanddisplay.h.
Referenced by displayHandleGlobal(), and wl_shell().
mShm
struct wl_shm* QWaylandDisplay::mShm private
Definition at line 108 of file qwaylanddisplay.h.
Referenced by createShmBuffer(), and displayHandleGlobal().
mSocketMask
uint32_t QWaylandDisplay::mSocketMask private
Definition at line 117 of file qwaylanddisplay.h.
Referenced by flushRequests(), and sourceUpdate().
outputListener
const struct wl_output_listener QWaylandDisplay::outputListener static private
Definition at line 121 of file qwaylanddisplay.h.
Referenced by displayHandleGlobal(), and mode().
premultiplied_argb_visual
struct wl_visual * QWaylandDisplay::premultiplied_argb_visual private
Definition at line 119 of file qwaylanddisplay.h.
Referenced by argbPremultipliedVisual().
rgb_visual
struct wl_visual * QWaylandDisplay::rgb_visual private
Definition at line 119 of file qwaylanddisplay.h.
Referenced by rgbVisual().
shellListener
const struct wl_shell_listener QWaylandDisplay::shellListener static private
Definition at line 158 of file qwaylanddisplay.h.
Referenced by displayHandleGlobal().
The documentation for this class was generated from the following files:
/src/plugins/platforms/wayland/qwaylanddisplay.cpp
/src/plugins/platforms/wayland/qwaylanddisplay.h
/src/plugins/platforms/wayland/qwaylandcursor.cpp