Qt 4.8: QSpanCollection::Span Struct Reference
QSpanCollection::Span Struct Reference
#include <qtableview_p.h>
Public Functions
int bottom () const
int height () const
int left () const
int right () const
Span ()
Span (int row, int column, int rowCount, int columnCount)
int top () const
int width () const
Public Variables
int m_bottom
int m_left
int m_right
int m_top
bool will_be_deleted
Detailed Description
Definition at line 80 of file qtableview_p.h.
Constructors and Destructors
Span() [1/2]
QSpanCollection::Span::Span () inline
Definition at line 87 of file qtableview_p.h.
         : m_top(-1), m_left(-1), m_bottom(-1), m_right(-1), will_be_deleted(false) { }
Span() [2/2]
QSpanCollection::Span::Span (int row, int column, int rowCount, int columnCount) inline
Definition at line 89 of file qtableview_p.h.
         : m_top(row), m_left(column), m_bottom(row+rowCount-1), m_right(column+columnCount-1), will_be_deleted(false) { }
Functions
bottom()
int QSpanCollection::Span::bottom () const inline
Definition at line 93 of file qtableview_p.h.
Referenced by QSpanCollection::addSpan(), QTableViewPrivate::drawAndClipSpans(), QTableView::moveCursor(), QSpanCollection::spanAt(), QSpanCollection::spansInRect(), QSpanCollection::updateRemovedColumns(), and QSpanCollection::updateSpan().
 { return m_bottom; }
height()
int QSpanCollection::Span::height () const inline
Definition at line 95 of file qtableview_p.h.
Referenced by QTableView::moveCursor(), QTableView::scrollTo(), QTableView::setSelection(), QTableViewPrivate::setSpan(), QSpanCollection::updateRemovedColumns(), QSpanCollection::updateSpan(), and QTableViewPrivate::visualSpanRect().
 { return m_bottom - m_top + 1; }
left()
int QSpanCollection::Span::left () const inline
Definition at line 92 of file qtableview_p.h.
Referenced by QSpanCollection::addSpan(), QTableViewPrivate::drawAndClipSpans(), QTableView::indexAt(), QTableView::isIndexHidden(), QTableView::moveCursor(), QTableView::setSelection(), QTableViewPrivate::setSpan(), QSpanCollection::spansInRect(), QSpanCollection::updateRemovedColumns(), QSpanCollection::updateSpan(), QTableView::visualRegionForSelection(), and QTableViewPrivate::visualSpanRect().
 { return m_left; }
right()
int QSpanCollection::Span::right () const inline
Definition at line 94 of file qtableview_p.h.
Referenced by QTableViewPrivate::drawAndClipSpans(), QTableView::moveCursor(), QSpanCollection::spanAt(), QSpanCollection::spansInRect(), and QTableViewPrivate::visualSpanRect().
 { return m_right; }
top()
int QSpanCollection::Span::top () const inline
Definition at line 91 of file qtableview_p.h.
Referenced by QSpanCollection::addSpan(), QTableViewPrivate::drawAndClipSpans(), QTableView::indexAt(), QTableView::isIndexHidden(), QTableView::moveCursor(), QTableView::setSelection(), QTableViewPrivate::setSpan(), QSpanCollection::spansInRect(), QSpanCollection::updateRemovedColumns(), QSpanCollection::updateSpan(), QTableView::visualRegionForSelection(), and QTableViewPrivate::visualSpanRect().
 { return m_top; }
width()
int QSpanCollection::Span::width () const inline
Definition at line 96 of file qtableview_p.h.
Referenced by QTableView::moveCursor(), QTableView::scrollTo(), QTableView::setSelection(), QSpanCollection::updateRemovedColumns(), QSpanCollection::updateSpan(), and QTableViewPrivate::visualSpanRect().
 { return m_right - m_left + 1; }
Properties
m_bottom
int QSpanCollection::Span::m_bottom
Definition at line 84 of file qtableview_p.h.
Referenced by QTableViewPrivate::setSpan().
m_left
int QSpanCollection::Span::m_left
Definition at line 83 of file qtableview_p.h.
Referenced by QSpanCollection::cleanSpanSubIndex(), and QSpanCollection::updateInsertedColumns().
m_right
int QSpanCollection::Span::m_right
Definition at line 85 of file qtableview_p.h.
Referenced by QTableViewPrivate::setSpan().
m_top
int QSpanCollection::Span::m_top
Definition at line 82 of file qtableview_p.h.
Referenced by QSpanCollection::cleanSpanSubIndex(), QSpanCollection::updateInsertedRows(), and QSpanCollection::updateRemovedRows().
will_be_deleted
bool QSpanCollection::Span::will_be_deleted
Definition at line 86 of file qtableview_p.h.
Referenced by QSpanCollection::cleanSpanSubIndex(), and QSpanCollection::updateRemovedRows().
The documentation for this struct was generated from the following file:
/src/gui/itemviews/qtableview_p.h