Qt 4.8: QTestCharBuffer Struct Reference
QTestCharBuffer Struct Reference
#include <qabstracttestlogger_p.h>
Public Types
enum { InitialSize = 512 }
Public Functions
char ** buffer ()
const char * constData () const
char * data ()
QTestCharBuffer ()
bool reset (int newSize)
int size () const
~QTestCharBuffer ()
Properties
int _size
char * buf
char staticBuf [InitialSize]
Detailed Description
Definition at line 104 of file qabstracttestlogger_p.h.
Enumerations
anonymous enum
anonymous enum
Enumerator
InitialSize
Definition at line 106 of file qabstracttestlogger_p.h.
 { InitialSize = 512 };
Constructors and Destructors
QTestCharBuffer()
QTestCharBuffer::QTestCharBuffer () inline
Definition at line 108 of file qabstracttestlogger_p.h.
             : _size(InitialSize), buf(staticBuf)
     {
         staticBuf[0] = '\0';
     }
~QTestCharBuffer()
QTestCharBuffer::~QTestCharBuffer () inline
Definition at line 114 of file qabstracttestlogger_p.h.
     {
         if (buf != staticBuf)
             qFree(buf);
     }
Functions
buffer()
char** QTestCharBuffer::buffer () inline
Definition at line 125 of file qabstracttestlogger_p.h.
     {
         return &buf;
     }
constData()
const char* QTestCharBuffer::constData () const inline
Definition at line 130 of file qabstracttestlogger_p.h.
Referenced by QXmlTestLogger::addBenchmarkResult(), QXmlTestLogger::addIncident(), QXmlTestLogger::addMessage(), QTestLogger::addTag(), QXmlTestLogger::enterTestFunction(), QTestXunitStreamer::formatAttributes(), QTestLightXmlStreamer::formatBeforeAttributes(), QTestLightXmlStreamer::formatStart(), QTestXmlStreamer::formatStart(), QTestLightXmlStreamer::output(), QTestXmlStreamer::output(), and QXmlTestLogger::startLogging().
     {
         return buf;
     }
data()
char* QTestCharBuffer::data () inline
Definition at line 120 of file qabstracttestlogger_p.h.
Referenced by allocateStringFn(), QTestBasicStreamer::formatAfterAttributes(), QTestXunitStreamer::formatAttributes(), QTestBasicStreamer::formatAttributes(), QTestLightXmlStreamer::formatBeforeAttributes(), QTestXmlStreamer::formatBeforeAttributes(), QTestBasicStreamer::formatBeforeAttributes(), QTestXunitStreamer::formatEnd(), QTestLightXmlStreamer::formatEnd(), QTestXmlStreamer::formatEnd(), QTestBasicStreamer::formatEnd(), QTestLightXmlStreamer::formatStart(), QTestXmlStreamer::formatStart(), QTestBasicStreamer::formatStart(), QTestBasicStreamer::outputElementAttributes(), QTestXunitStreamer::outputElements(), QTestBasicStreamer::outputElements(), QTest::printMessage(), QTest::qt_asprintf(), QXmlTestLogger::xmlCdata(), and QXmlTestLogger::xmlQuote().
     {
         return buf;
     }
reset()
bool QTestCharBuffer::reset (int newSize) inline
Definition at line 140 of file qabstracttestlogger_p.h.
Referenced by allocateStringFn(), and QTest::qt_asprintf().
     {
         char *newBuf = 0;
         if (buf == staticBuf) {
             // if we point to our internal buffer, we need to malloc first
             newBuf = reinterpret_cast<char *>(qMalloc(newSize));
         } else {
             // if we already malloc'ed, just realloc
             newBuf = reinterpret_cast<char *>(qRealloc(buf, newSize));
         }
         // if the allocation went wrong (newBuf == 0), we leave the object as is
         if (!newBuf)
             return false;
         _size = newSize;
         buf = newBuf;
         return true;
     }
size()
int QTestCharBuffer::size () const inline
Definition at line 135 of file qabstracttestlogger_p.h.
Referenced by allocateStringFn(), and QTest::qt_asprintf().
     {
         return _size;
     }
Properties
_size
int QTestCharBuffer::_size private
Definition at line 161 of file qabstracttestlogger_p.h.
buf
char* QTestCharBuffer::buf private
Definition at line 162 of file qabstracttestlogger_p.h.
staticBuf
char QTestCharBuffer::staticBuf[InitialSize] private
Definition at line 163 of file qabstracttestlogger_p.h.
The documentation for this struct was generated from the following file:
/src/testlib/qabstracttestlogger_p.h