Qt 4.8: QMenuPrivate::QWceMenuPrivate Struct Reference
QMenuPrivate::QWceMenuPrivate Struct Reference
#include <qmenu_p.h>
Public Functions
void addAction (QAction *, QWceMenuAction *=0)
void addAction (QWceMenuAction *, QWceMenuAction *=0)
QWceMenuAction * findAction (QAction *a)
QWceMenuPrivate ()
void rebuild ()
void removeAction (QWceMenuAction *)
void removeAction (QAction *a)
void syncAction (QWceMenuAction *)
void syncAction (QAction *a)
~QWceMenuPrivate ()
Public Variables
QList< QWceMenuAction * > actionItems
HMENU menuHandle
Detailed Description
Definition at line 344 of file qmenu_p.h.
Constructors and Destructors
QWceMenuPrivate()
QMenuPrivate::QWceMenuPrivate::QWceMenuPrivate ()
Definition at line 435 of file qmenu_wince.cpp.
Referenced by QMenuPrivate::wceMenu().
 :   menuHandle(0)
 {
 }
~QWceMenuPrivate()
QMenuPrivate::QWceMenuPrivate::~QWceMenuPrivate ()
Definition at line 440 of file qmenu_wince.cpp.
 {
     qt_wce_delete_action_list(&actionItems);
     if (menuHandle)
         DestroyMenu(menuHandle);
 }
Functions
addAction() [1/2]
void QMenuPrivate::QWceMenuPrivate::addAction (QAction * a, QWceMenuAction * before = 0)
Definition at line 447 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::addAction().
 {
     QWceMenuAction *action = new QWceMenuAction;
     action->action = a;
     action->command = qt_wce_menu_static_cmd_id++;
     addAction(action, before);
 }
addAction() [2/2]
void QMenuPrivate::QWceMenuPrivate::addAction (QWceMenuAction * action, QWceMenuAction * before = 0)
Definition at line 455 of file qmenu_wince.cpp.
 {
     if (!action)
         return;
     int before_index = actionItems.indexOf(before);
     if (before_index < 0) {
         before = 0;
         before_index = actionItems.size();
     }
     actionItems.insert(before_index, action);
     rebuild();
 }
findAction()
QWceMenuAction* QMenuPrivate::QWceMenuPrivate::findAction (QAction * a) inline
Definition at line 356 of file qmenu_p.h.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::addAction().
{
             for(int i = 0; i < actionItems.size(); i++) {
                 QWceMenuAction *act = actionItems[i];
                 if(a == act->action)
                     return act;
             }
             return 0;
         }
rebuild()
void QMenuPrivate::QWceMenuPrivate::rebuild ()
Definition at line 492 of file qmenu_wince.cpp.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::addAction(), addAction(), QMenuBarPrivate::QWceMenuBarPrivate::removeAction(), removeAction(), QMenuBarPrivate::QWceMenuBarPrivate::syncAction(), syncAction(), and QMenuPrivate::wceMenu().
 {
     if (!menuHandle)
         menuHandle = CreatePopupMenu();
     else
         qt_wce_clear_menu(menuHandle);
     for (int i = 0; i < actionItems.size(); ++i) {
         QWceMenuAction *action = actionItems.at(i);
         action->menuHandle = menuHandle;
         qt_wce_insert_action(menuHandle, action);
     }
     QMenuBar::wceRefresh();
 }
removeAction() [1/2]
void QMenuPrivate::QWceMenuPrivate::removeAction (QWceMenuAction * action)
Definition at line 512 of file qmenu_wince.cpp.
 {
     actionItems.removeAll(action);
     delete action;
     rebuild();
 }
removeAction() [2/2]
void QMenuPrivate::QWceMenuPrivate::removeAction (QAction * a) inline
Definition at line 355 of file qmenu_p.h.
Referenced by removeAction().
 { removeAction(findAction(a)); }
syncAction() [1/2]
void QMenuPrivate::QWceMenuPrivate::syncAction (QWceMenuAction *)
Definition at line 507 of file qmenu_wince.cpp.
 {
     rebuild();
 }
syncAction() [2/2]
void QMenuPrivate::QWceMenuPrivate::syncAction (QAction * a) inline
Definition at line 352 of file qmenu_p.h.
Referenced by syncAction().
 { syncAction(findAction(a)); }
Properties
actionItems
QList<QWceMenuAction*> QMenuPrivate::QWceMenuPrivate::actionItems
Definition at line 345 of file qmenu_p.h.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::addAction(), addAction(), QMenuBarPrivate::QWceMenuBarPrivate::rebuild(), rebuild(), QMenuBarPrivate::QWceMenuBarPrivate::removeAction(), removeAction(), and ~QWceMenuPrivate().
menuHandle
HMENU QMenuPrivate::QWceMenuPrivate::menuHandle
Definition at line 346 of file qmenu_p.h.
Referenced by QMenuBarPrivate::QWceMenuBarPrivate::rebuild(), rebuild(), QMenuPrivate::wceMenu(), and ~QWceMenuPrivate().
The documentation for this struct was generated from the following files:
/src/gui/widgets/qmenu_p.h
/src/gui/widgets/qmenu_wince.cpp