Qt 4.8: QAudioEngineFactoryInterface Struct Reference
QAudioEngineFactoryInterface Struct Reference abstract
#include <qaudioengineplugin.h>
Public Functions
virtual QList< QByteArray > availableDevices (QAudio::Mode) const =0
virtual QAbstractAudioDeviceInfo * createDeviceInfo (const QByteArray &device, QAudio::Mode mode)=0
virtual QAbstractAudioInput * createInput (const QByteArray &device, const QAudioFormat &format=QAudioFormat())=0
virtual QAbstractAudioOutput * createOutput (const QByteArray &device, const QAudioFormat &format=QAudioFormat())=0
Public Functions inherited from QFactoryInterface
virtual QStringList keys () const =0
virtual ~QFactoryInterface ()
Detailed Description
Definition at line 61 of file qaudioengineplugin.h.
Functions
availableDevices()
virtual QList<QByteArray> QAudioEngineFactoryInterface::availableDevices (QAudio::Mode) const pure virtual
Implemented in QAudioEnginePlugin.
Referenced by QAudioDeviceFactory::availableDevices(), QAudioDeviceFactory::defaultInputDevice(), and QAudioDeviceFactory::defaultOutputDevice().
createDeviceInfo()
virtual QAbstractAudioDeviceInfo* QAudioEngineFactoryInterface::createDeviceInfo (const QByteArray & device, QAudio::Mode mode) pure virtual
Implemented in QAudioEnginePlugin.
Referenced by QAudioDeviceFactory::audioDeviceInfo().
createInput()
virtual QAbstractAudioInput* QAudioEngineFactoryInterface::createInput (const QByteArray & device, const QAudioFormat & format = QAudioFormat()) pure virtual
Implemented in QAudioEnginePlugin.
Referenced by QAudioDeviceFactory::createInputDevice().
createOutput()
virtual QAbstractAudioOutput* QAudioEngineFactoryInterface::createOutput (const QByteArray & device, const QAudioFormat & format = QAudioFormat()) pure virtual
Implemented in QAudioEnginePlugin.
Referenced by QAudioDeviceFactory::createOutputDevice().
The documentation for this struct was generated from the following file:
/src/multimedia/audio/qaudioengineplugin.h