Qt 4.8: QDeclarativeVMEMetaData::AliasData Struct Reference
QDeclarativeVMEMetaData::AliasData Struct Reference
#include <qdeclarativevmemetaobject_p.h>
Public Functions
bool isObjectAlias () const
bool isPropertyAlias () const
bool isValueTypeAlias () const
int propertyIndex () const
int valueType () const
int valueTypeIndex () const
Public Variables
int contextIdx
int flags
int propertyIdx
Detailed Description
Definition at line 83 of file qdeclarativevmemetaobject_p.h.
Functions
isObjectAlias()
bool QDeclarativeVMEMetaData::AliasData::isObjectAlias () const inline
Definition at line 88 of file qdeclarativevmemetaobject_p.h.
Referenced by QDeclarativeVMEMetaObject::aliasTarget(), QDeclarativeVMEMetaObject::connectAlias(), isPropertyAlias(), isValueTypeAlias(), and QDeclarativeVMEMetaObject::metaCall().
{
             return propertyIdx == -1;
         }
isPropertyAlias()
bool QDeclarativeVMEMetaData::AliasData::isPropertyAlias () const inline
Definition at line 91 of file qdeclarativevmemetaobject_p.h.
{
             return !isObjectAlias() && !(propertyIdx & 0xFF000000);
         }
isValueTypeAlias()
bool QDeclarativeVMEMetaData::AliasData::isValueTypeAlias () const inline
Definition at line 94 of file qdeclarativevmemetaobject_p.h.
Referenced by QDeclarativeVMEMetaObject::aliasTarget(), and QDeclarativeVMEMetaObject::metaCall().
{
             return !isObjectAlias() && (propertyIdx & 0xFF000000);
         }
propertyIndex()
int QDeclarativeVMEMetaData::AliasData::propertyIndex () const inline
Definition at line 97 of file qdeclarativevmemetaobject_p.h.
Referenced by QDeclarativeVMEMetaObject::aliasTarget(), QDeclarativeVMEMetaObject::connectAlias(), and QDeclarativeVMEMetaObject::metaCall().
{
             return propertyIdx & 0x0000FFFF;
         }
valueType()
int QDeclarativeVMEMetaData::AliasData::valueType () const inline
Definition at line 103 of file qdeclarativevmemetaobject_p.h.
Referenced by QDeclarativeVMEMetaObject::metaCall().
{
             return ((unsigned int)propertyIdx) >> 24;
         }
valueTypeIndex()
int QDeclarativeVMEMetaData::AliasData::valueTypeIndex () const inline
Definition at line 100 of file qdeclarativevmemetaobject_p.h.
Referenced by QDeclarativeVMEMetaObject::aliasTarget(), and QDeclarativeVMEMetaObject::metaCall().
{
             return (propertyIdx & 0x00FF0000) >> 16;
         }
Properties
contextIdx
int QDeclarativeVMEMetaData::AliasData::contextIdx
Definition at line 84 of file qdeclarativevmemetaobject_p.h.
Referenced by QDeclarativeVMEMetaObject::aliasTarget(), QDeclarativeVMEMetaObject::connectAlias(), and QDeclarativeVMEMetaObject::metaCall().
flags
int QDeclarativeVMEMetaData::AliasData::flags
Definition at line 86 of file qdeclarativevmemetaobject_p.h.
Referenced by QDeclarativeVMEMetaObject::metaCall().
propertyIdx
int QDeclarativeVMEMetaData::AliasData::propertyIdx
Definition at line 85 of file qdeclarativevmemetaobject_p.h.
The documentation for this struct was generated from the following file:
/src/declarative/qml/qdeclarativevmemetaobject_p.h