Qt 4.8: QCss::Declaration Struct Reference
QCss::Declaration Struct Reference
#include <qcssparser_p.h>
Classes
struct DeclarationData
Public Functions
Qt::Alignment alignmentValue () const
Attachment attachmentValue () const
void borderImageValue (QString *image, int *cuts, TileMode *h, TileMode *v) const
QBrush brushValue (const QPalette &=QPalette()) const
void brushValues (QBrush *c, const QPalette &=QPalette()) const
QColor colorValue (const QPalette &=QPalette()) const
void colorValues (QColor *c, const QPalette &=QPalette()) const
Declaration ()
QIcon iconValue () const
bool intValue (int *i, const char *unit=0) const
bool isEmpty () const
Origin originValue () const
PositionMode positionValue () const
bool realValue (qreal *r, const char *unit=0) const
QRect rectValue () const
Repeat repeatValue () const
QSize sizeValue () const
int styleFeaturesValue () const
BorderStyle styleValue () const
void styleValues (BorderStyle *s) const
QString uriValue () const
Public Variables
QExplicitlySharedDataPointer< DeclarationData > d
Detailed Description
Definition at line 419 of file qcssparser_p.h.
Constructors and Destructors
Declaration()
QCss::Declaration::Declaration () inline
Definition at line 431 of file qcssparser_p.h.
 : d(new DeclarationData()) {}
Functions
alignmentValue()
Qt::Alignment Declaration::alignmentValue () const
Definition at line 1597 of file qcssparser.cpp.
Referenced by QCss::ValueExtractor::extractBackground(), QCss::ValueExtractor::extractImage(), QCss::ValueExtractor::extractPosition(), and QRenderRule::QRenderRule().
 {
     if (d->parsed.isValid())
         return Qt::Alignment(d->parsed.toInt());
     if (d->values.isEmpty() || d->values.count() > 2)
         return Qt::AlignLeft | Qt::AlignTop;
     Qt::Alignment v = parseAlignment(d->values.constData(), d->values.count());
     d->parsed = int(v);
     return v;
 }
attachmentValue()
Attachment Declaration::attachmentValue () const
Definition at line 1564 of file qcssparser.cpp.
Referenced by QCss::ValueExtractor::extractBackground().
 {
     if (d->parsed.isValid())
         return static_cast<Attachment>(d->parsed.toInt());
     if (d->values.count() != 1)
         return Attachment_Unknown;
     int v = findKnownValue(d->values.at(0).variant.toString(),
                            attachments, NumKnownAttachments);
     d->parsed = v;
     return static_cast<Attachment>(v);
 }
borderImageValue()
void Declaration::borderImageValue (QString * image, int * cuts, TileMode * h, TileMode * v) const
Definition at line 1609 of file qcssparser.cpp.
Referenced by QRenderRule::QRenderRule().
 {
     *image = uriValue();
     for (int i = 0; i < 4; i++)
         cuts[i] = -1;
     *h = *v = TileMode_Stretch;
     if (d->values.count() < 2)
         return;
     if (d->values.at(1).type == Value::Number) { // cuts!
         int i;
         for (i = 0; i < qMin(d->values.count()-1, 4); i++) {
             const Value& v = d->values.at(i+1);
             if (v.type != Value::Number)
                 break;
             cuts[i] = v.variant.toString().toInt();
         }
         if (i == 0) cuts[0] = cuts[1] = cuts[2] = cuts[3] = 0;
         else if (i == 1) cuts[3] = cuts[2] = cuts[1] = cuts[0];
         else if (i == 2) cuts[2] = cuts[0], cuts[3] = cuts[1];
         else if (i == 3) cuts[3] = cuts[1];
     }
     if (d->values.last().type == Value::Identifier) {
         *v = static_cast<TileMode>(findKnownValue(d->values.last().variant.toString(),
                                       tileModes, NumKnownTileModes));
     }
     if (d->values[d->values.count() - 2].type == Value::Identifier) {
         *h = static_cast<TileMode>
                 (findKnownValue(d->values[d->values.count()-2].variant.toString(),
                                         tileModes, NumKnownTileModes));
     } else
         *h = *v;
 }
brushValue()
QBrush Declaration::brushValue (const QPalette & pal = QPalette()) const
Definition at line 1325 of file qcssparser.cpp.
Referenced by QCss::ValueExtractor::extractBackground(), QCss::ValueExtractor::extractBorder(), QCss::ValueExtractor::extractPalette(), and QStyleSheetStyle::setProperties().
 {
     if (d->values.count() != 1)
         return QBrush();
     if (d->parsed.isValid()) {
         if (d->parsed.type() == QVariant::Brush)
             return qvariant_cast<QBrush>(d->parsed);
         if (d->parsed.type() == QVariant::Int)
             return pal.color((QPalette::ColorRole)(d->parsed.toInt()));
     }
     BrushData data = parseBrushValue(d->values.at(0), pal);
     if(data.type == BrushData::Role) {
         d->parsed = QVariant::fromValue<int>(data.role);
         return pal.color((QPalette::ColorRole)(data.role));
     } else {
         if (data.type != BrushData::DependsOnThePalette)
             d->parsed = QVariant::fromValue<QBrush>(data.brush);
         return data.brush;
     }
 }
brushValues()
void Declaration::brushValues (QBrush * c, const QPalette & pal = QPalette()) const
Definition at line 1349 of file qcssparser.cpp.
Referenced by QCss::ValueExtractor::extractBorder(), and QCss::ValueExtractor::extractOutline().
 {
     int needParse = 0x1f; // bits 0..3 say if we should parse the corresponding value.
                           // the bit 4 say we need to update d->parsed
     int i = 0;
     if (d->parsed.isValid()) {
         needParse = 0;
         QList<QVariant> v = d->parsed.toList();
         for (i = 0; i < qMin(v.count(), 4); i++) {
             if (v.at(i).type() == QVariant::Brush) {
                 c[i] = qvariant_cast<QBrush>(v.at(i));
             } else if (v.at(i).type() == QVariant::Int) {
                 c[i] = pal.color((QPalette::ColorRole)(v.at(i).toInt()));
             } else {
                 needParse |= (1<<i);
             }
         }
     }
     if (needParse != 0) {
         QList<QVariant> v;
         for (i = 0; i < qMin(d->values.count(), 4); i++) {
             if (!(needParse & (1<<i)))
                 continue;
             BrushData data = parseBrushValue(d->values.at(i), pal);
             if(data.type == BrushData::Role) {
                 v += QVariant::fromValue<int>(data.role);
                 c[i] = pal.color((QPalette::ColorRole)(data.role));
             } else {
                 if (data.type != BrushData::DependsOnThePalette) {
                     v += QVariant::fromValue<QBrush>(data.brush);
                 } else {
                     v += QVariant();
                 }
                 c[i] = data.brush;
             }
         }
         if (needParse & 0x10)
             d->parsed = v;
     }
     if (i == 0) c[0] = c[1] = c[2] = c[3] = QBrush();
     else if (i == 1) c[3] = c[2] = c[1] = c[0];
     else if (i == 2) c[2] = c[0], c[3] = c[1];
     else if (i == 3) c[3] = c[1];
 }
colorValue()
QColor Declaration::colorValue (const QPalette & pal = QPalette()) const
Definition at line 1303 of file qcssparser.cpp.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), QRenderRule::QRenderRule(), and QStyleSheetStyle::setProperties().
 {
     if (d->values.count() != 1)
         return QColor();
     if (d->parsed.isValid()) {
         if (d->parsed.type() == QVariant::Color)
             return qvariant_cast<QColor>(d->parsed);
         if (d->parsed.type() == QVariant::Int)
             return pal.color((QPalette::ColorRole)(d->parsed.toInt()));
     }
     ColorData color = parseColorValue(d->values.at(0));
     if(color.type == ColorData::Role) {
         d->parsed = QVariant::fromValue<int>(color.role);
         return pal.color((QPalette::ColorRole)(color.role));
     } else {
         d->parsed = QVariant::fromValue<QColor>(color.color);
         return color.color;
     }
 }
colorValues()
void Declaration::colorValues (QColor * c, const QPalette & pal = QPalette()) const
Definition at line 1477 of file qcssparser.cpp.
 {
     int i;
     if (d->parsed.isValid()) {
         QList<QVariant> v = d->parsed.toList();
         for (i = 0; i < qMin(d->values.count(), 4); i++) {
             if (v.at(i).type() == QVariant::Color) {
                 c[i] = qvariant_cast<QColor>(v.at(i));
             } else {
                 c[i] = pal.color((QPalette::ColorRole)(v.at(i).toInt()));
             }
         }
     } else {
         QList<QVariant> v;
         for (i = 0; i < qMin(d->values.count(), 4); i++) {
             ColorData color = parseColorValue(d->values.at(i));
             if(color.type == ColorData::Role) {
                 v += QVariant::fromValue<int>(color.role);
                 c[i] = pal.color((QPalette::ColorRole)(color.role));
             } else {
                 v += QVariant::fromValue<QColor>(color.color);
                 c[i] = color.color;
             }
         }
         d->parsed = v;
     }
     if (i == 0) c[0] = c[1] = c[2] = c[3] = QColor();
     else if (i == 1) c[3] = c[2] = c[1] = c[0];
     else if (i == 2) c[2] = c[0], c[3] = c[1];
     else if (i == 3) c[3] = c[1];
 }
iconValue()
QIcon Declaration::iconValue () const
Definition at line 1646 of file qcssparser.cpp.
Referenced by QCss::ValueExtractor::extractImage(), QRenderRule::QRenderRule(), and QStyleSheetStyle::setProperties().
 {
     if (d->parsed.isValid())
         return qvariant_cast<QIcon>(d->parsed);
     QIcon icon;
     for (int i = 0; i < d->values.count();) {
         const Value &value = d->values.at(i++);
         if (value.type != Value::Uri)
             break;
         QString uri = value.variant.toString();
         QIcon::Mode mode = QIcon::Normal;
         QIcon::State state = QIcon::Off;
         for (int j = 0; j < 2; j++) {
             if (i != d->values.count() && d->values.at(i).type == Value::KnownIdentifier) {
                 switch (d->values.at(i).variant.toInt()) {
                 case Value_Disabled: mode = QIcon::Disabled; break;
                 case Value_Active: mode = QIcon::Active; break;
                 case Value_Selected: mode = QIcon::Selected; break;
                 case Value_Normal: mode = QIcon::Normal; break;
                 case Value_On: state = QIcon::On; break;
                 case Value_Off: state = QIcon::Off; break;
                 default: break;
                 }
                 ++i;
             } else {
                 break;
             }
         }
         // QIcon is soo broken
         if (icon.isNull())
             icon = QIcon(uri);
         else
             icon.addPixmap(uri, mode, state);
         if (i == d->values.count())
             break;
         if (d->values.at(i).type == Value::TermOperatorComma)
             i++;
     }
     d->parsed = QVariant::fromValue<QIcon>(icon);
     return icon;
 }
intValue()
bool Declaration::intValue (int * i, const char * unit = 0) const
Definition at line 1431 of file qcssparser.cpp.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), and QRenderRule::QRenderRule().
 {
     if (d->values.count() != 1)
         return false;
     return intValueHelper(d->values.at(0), i, unit);
 }
isEmpty()
bool QCss::Declaration::isEmpty () const inline
Definition at line 432 of file qcssparser_p.h.
Referenced by QCss::Parser::parsePage(), and QCss::Parser::parseRuleset().
 { return d->property.isEmpty() && d->propertyId == UnknownProperty; }
originValue()
Origin Declaration::originValue () const
Definition at line 1540 of file qcssparser.cpp.
Referenced by QCss::ValueExtractor::extractBackground(), and QCss::ValueExtractor::extractPosition().
 {
     if (d->parsed.isValid())
         return static_cast<Origin>(d->parsed.toInt());
     if (d->values.count() != 1)
         return Origin_Unknown;
     int v = findKnownValue(d->values.at(0).variant.toString(),
                                origins, NumKnownOrigins);
     d->parsed = v;
     return static_cast<Origin>(v);
 }
positionValue()
PositionMode Declaration::positionValue () const
Definition at line 1552 of file qcssparser.cpp.
Referenced by QCss::ValueExtractor::extractPosition().
 {
     if (d->parsed.isValid())
         return static_cast<PositionMode>(d->parsed.toInt());
     if (d->values.count() != 1)
         return PositionMode_Unknown;
     int v = findKnownValue(d->values.at(0).variant.toString(),
                            positions, NumKnownPositionModes);
     d->parsed = v;
     return static_cast<PositionMode>(v);
 }
realValue()
bool Declaration::realValue (qreal * r, const char * unit = 0) const
Definition at line 1394 of file qcssparser.cpp.
Referenced by QTextHtmlParserNode::applyCssDeclarations().
 {
     if (d->values.count() != 1)
         return false;
     const Value &v = d->values.at(0);
     if (unit && v.type != Value::Length)
         return false;
     QString s = v.variant.toString();
     if (unit) {
         if (!s.endsWith(QLatin1String(unit), Qt::CaseInsensitive))
             return false;
         s.chop(qstrlen(unit));
     }
     bool ok = false;
     qreal val = s.toDouble(&ok);
     if (ok)
         *real = val;
     return ok;
 }
rectValue()
QRect Declaration::rectValue () const
Definition at line 1455 of file qcssparser.cpp.
Referenced by QStyleSheetStyle::setProperties().
 {
     if (d->values.count() != 1)
         return QRect();
     if (d->parsed.isValid())
         return qvariant_cast<QRect>(d->parsed);
     const QCss::Value &v = d->values.at(0);
     if (v.type != Value::Function)
         return QRect();
     QStringList func = v.variant.toStringList();
     if (func.count() != 2 || func.at(0).compare(QLatin1String("rect")) != 0)
         return QRect();
     QStringList args = func[1].split(QLatin1Char(' '), QString::SkipEmptyParts);
     if (args.count() != 4)
         return QRect();
     QRect rect(args[0].toInt(), args[1].toInt(), args[2].toInt(), args[3].toInt());
     d->parsed = QVariant::fromValue<QRect>(rect);
     return rect;
 }
repeatValue()
Repeat Declaration::repeatValue () const
Definition at line 1528 of file qcssparser.cpp.
 {
     if (d->parsed.isValid())
         return static_cast<Repeat>(d->parsed.toInt());
     if (d->values.count() != 1)
         return Repeat_Unknown;
     int v = findKnownValue(d->values.at(0).variant.toString(),
                    repeats, NumKnownRepeats);
     d->parsed = v;
     return static_cast<Repeat>(v);
 }
sizeValue()
QSize Declaration::sizeValue () const
Definition at line 1438 of file qcssparser.cpp.
Referenced by QRenderRule::QRenderRule(), and QStyleSheetStyle::setProperties().
 {
     if (d->parsed.isValid())
         return qvariant_cast<QSize>(d->parsed);
     int x[2] = { 0, 0 };
     if (d->values.count() > 0)
         intValueHelper(d->values.at(0), &x[0], "px");
     if (d->values.count() > 1)
         intValueHelper(d->values.at(1), &x[1], "px");
     else
         x[1] = x[0];
     QSize size(x[0], x[1]);
     d->parsed = QVariant::fromValue<QSize>(size);
     return size;
 }
styleFeaturesValue()
int Declaration::styleFeaturesValue () const
Definition at line 1576 of file qcssparser.cpp.
Referenced by QCss::ValueExtractor::extractStyleFeatures().
 {
     Q_ASSERT(d->propertyId == QtStyleFeatures);
     if (d->parsed.isValid())
         return d->parsed.toInt();
     int features = StyleFeature_None;
     for (int i = 0; i < d->values.count(); i++) {
         features |= static_cast<int>(findKnownValue(d->values.value(i).variant.toString(),
                                      styleFeatures, NumKnownStyleFeatures));
     }
     d->parsed = features;
     return features;
 }
styleValue()
BorderStyle Declaration::styleValue () const
Definition at line 1510 of file qcssparser.cpp.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), and QCss::ValueExtractor::extractBorder().
 {
     if (d->values.count() != 1)
         return BorderStyle_None;
     return parseStyleValue(d->values.at(0));
 }
styleValues()
void Declaration::styleValues (BorderStyle * s) const
Definition at line 1517 of file qcssparser.cpp.
Referenced by QCss::ValueExtractor::extractBorder(), and QCss::ValueExtractor::extractOutline().
 {
     int i;
     for (i = 0; i < qMin(d->values.count(), 4); i++)
         s[i] = parseStyleValue(d->values.at(i));
     if (i == 0) s[0] = s[1] = s[2] = s[3] = BorderStyle_None;
     else if (i == 1) s[3] = s[2] = s[1] = s[0];
     else if (i == 2) s[2] = s[0], s[3] = s[1];
     else if (i == 3) s[3] = s[1];
 }
uriValue()
QString Declaration::uriValue () const
Definition at line 1590 of file qcssparser.cpp.
Referenced by QStyleSheetStyle::setProperties().
 {
     if (d->values.isEmpty() || d->values.at(0).type != Value::Uri)
         return QString();
     return d->values.at(0).variant.toString();
 }
Properties
d
QExplicitlySharedDataPointer<DeclarationData> QCss::Declaration::d
Definition at line 430 of file qcssparser_p.h.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), QCss::ValueExtractor::borderValue(), QCss::ValueExtractor::extractBackground(), QCss::ValueExtractor::extractBorder(), QCss::ValueExtractor::extractBox(), QCss::ValueExtractor::extractFont(), QCss::ValueExtractor::extractGeometry(), QCss::ValueExtractor::extractImage(), QCss::ValueExtractor::extractOutline(), QCss::ValueExtractor::extractPalette(), QCss::ValueExtractor::extractPosition(), QCss::ValueExtractor::extractStyleFeatures(), QCss::ValueExtractor::lengthValue(), QCss::ValueExtractor::lengthValues(), parseCSStoXMLAttrs(), QCss::Parser::parseNextDeclaration(), QCss::Parser::parsePrio(), QCss::Parser::parseProperty(), parseStopNode(), QRenderRule::QRenderRule(), QStyleSheetStyle::setProperties(), and QCss::ValueExtractor::sizeValue().
The documentation for this struct was generated from the following files:
/src/gui/text/qcssparser_p.h
/src/gui/text/qcssparser.cpp