Qt 4.8: QStrokerOps::Element Struct Reference
QStrokerOps::Element Struct Reference
#include <qstroker_p.h>
Public Functions
bool isCurveTo () const
bool isLineTo () const
bool isMoveTo () const
operator qfixed2d ()
Public Variables
QPainterPath::ElementType type
qfixed x
qfixed y
Detailed Description
Definition at line 133 of file qstroker_p.h.
Functions
isCurveTo()
bool QStrokerOps::Element::isCurveTo () const inline
Definition at line 140 of file qstroker_p.h.
Referenced by QSubpathFlatIterator::next(), and qt_stroke_side().
 { return type == QPainterPath::CurveToElement; }
isLineTo()
bool QStrokerOps::Element::isLineTo () const inline
Definition at line 139 of file qstroker_p.h.
Referenced by QSubpathFlatIterator::next(), QDashStroker::processCurrentSubpath(), and qt_stroke_side().
 { return type == QPainterPath::LineToElement; }
isMoveTo()
bool QStrokerOps::Element::isMoveTo () const inline
Definition at line 138 of file qstroker_p.h.
Referenced by QSubpathFlatIterator::next().
 { return type == QPainterPath::MoveToElement; }
operator qfixed2d()
QStrokerOps::Element::operator qfixed2d () inline
Definition at line 142 of file qstroker_p.h.
 { qfixed2d pt = { x, y }; return pt; }
Properties
type
QPainterPath::ElementType QStrokerOps::Element::type
Definition at line 134 of file qstroker_p.h.
Referenced by QSubpathBackwardIterator::next(), and QSubpathFlatIterator::next().
x
qfixed QStrokerOps::Element::x
Definition at line 135 of file qstroker_p.h.
Referenced by QSubpathFlatIterator::next(), QDashStroker::processCurrentSubpath(), and qt_stroke_side().
y
qfixed QStrokerOps::Element::y
Definition at line 136 of file qstroker_p.h.
Referenced by QSubpathFlatIterator::next(), QDashStroker::processCurrentSubpath(), and qt_stroke_side().
The documentation for this struct was generated from the following file:
/src/gui/painting/qstroker_p.h