Qt 4.8: QCss::Selector Struct Reference
QCss::Selector Struct Reference
#include <qcssparser_p.h>
Public Functions
quint64 pseudoClass (quint64 *negated=0) const
QString pseudoElement () const
int specificity () const
Public Variables
QVector< BasicSelector > basicSelectors
Detailed Description
Definition at line 555 of file qcssparser_p.h.
Functions
pseudoClass()
quint64 Selector::pseudoClass (quint64 * negated = 0) const
Definition at line 1717 of file qcssparser.cpp.
Referenced by declarations(), QCss::StyleSelector::declarationsForNode(), QStyleSheetStyle::polish(), and QStyleSheetStyle::renderRule().
 {
     const BasicSelector& bs = basicSelectors.last();
     if (bs.pseudos.isEmpty())
         return PseudoClass_Unspecified;
     quint64 pc = PseudoClass_Unknown;
     for (int i = !pseudoElement().isEmpty(); i < bs.pseudos.count(); i++) {
         const Pseudo &pseudo = bs.pseudos.at(i);
         if (pseudo.type == PseudoClass_Unknown)
             return PseudoClass_Unknown;
         if (!pseudo.negated)
             pc |= pseudo.type;
         else if (negated)
             *negated |= pseudo.type;
     }
     return pc;
 }
pseudoElement()
QString Selector::pseudoElement () const
Definition at line 1709 of file qcssparser.cpp.
Referenced by declarations(), QCss::StyleSelector::declarationsForNode(), and QStyleSheetStyle::hasStyleRule().
 {
     const BasicSelector& bs = basicSelectors.last();
     if (!bs.pseudos.isEmpty() && bs.pseudos.at(0).type == PseudoClass_Unknown)
         return bs.pseudos.at(0).name;
     return QString();
 }
specificity()
int Selector::specificity () const
Definition at line 1695 of file qcssparser.cpp.
Referenced by QCss::StyleSelector::matchRule().
 {
     int val = 0;
     for (int i = 0; i < basicSelectors.count(); ++i) {
         const BasicSelector &sel = basicSelectors.at(i);
         if (!sel.elementName.isEmpty())
             val += 1;
         val += (sel.pseudos.count() + sel.attributeSelectors.count()) * 0x10;
         val += sel.ids.count() * 0x100;
     }
     return val;
 }
Properties
basicSelectors
QVector<BasicSelector> QCss::Selector::basicSelectors
Definition at line 557 of file qcssparser_p.h.
Referenced by QCss::StyleSheet::buildIndexes(), QCss::Parser::parseSelector(), and QCss::StyleSelector::selectorMatches().
The documentation for this struct was generated from the following files:
/src/gui/text/qcssparser_p.h
/src/gui/text/qcssparser.cpp