Qt 4.8: QUuid Class Reference
QUuid Class Reference
The QUuid class stores a Universally Unique Identifier (UUID).
#include <quuid.h>
Public Types
enum Variant {
VarUnknown =-1, NCS = 0, DCE = 2, Microsoft = 6,
Reserved = 7
}
This enum defines the values used in the Variant field {variant field} of the UUID.
enum Version {
VerUnknown =-1, Time = 1, EmbeddedPOSIX = 2, Name = 3,
Random = 4
}
This enum defines the values used in the Version field {version field} of the UUID.
Public Functions
bool isNull () const
Returns true if this is the null UUID {00000000-0000-0000-0000-000000000000}; otherwise returns false.
operator GUID () const
Returns a Windows GUID from a QUuid.
operator QString () const
Returns the string representation of the uuid.
bool operator!= (const QUuid &orig) const
Returns true if this QUuid and the other QUuid are different; otherwise returns false.
bool operator!= (const GUID &guid) const
Returns true if this UUID is not equal to the Windows GUID guid; otherwise returns false.
bool operator< (const QUuid &other) const
Returns true if this QUuid has the same Variant field {variant field} as the other QUuid and is lexicographically before the other QUuid.
QUuid & operator= (const GUID &guid)
Assigns a Windows guid to a Qt QUuid.
bool operator== (const QUuid &orig) const
Returns true if this QUuid and the other QUuid are identical; otherwise returns false.
bool operator== (const GUID &guid) const
Returns true if this UUID is equal to the Windows GUID guid; otherwise returns false.
bool operator> (const QUuid &other) const
Returns true if this QUuid has the same Variant field {variant field} as the other QUuid and is lexicographically after the other QUuid.
QUuid ()
Creates the null UUID.
QUuid (uint l, ushort w1, ushort w2, uchar b1, uchar b2, uchar b3, uchar b4, uchar b5, uchar b6, uchar b7, uchar b8)
Creates a UUID with the value specified by the parameters, l, w1, w2, b1, b2, b3, b4, b5, b6, b7, b8.
QUuid (const QString &)
Creates a QUuid object from the string text, which must be formatted as five hex fields separated by '-', e.g., "{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}" where 'x' is a hex digit.
QUuid (const char *)
QUuid (const QByteArray &)
Creates a QUuid object from the QByteArray text, which must be formatted as five hex fields separated by '-', e.g., "{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}" where 'x' is a hex digit.
QUuid (const GUID &guid)
Casts a Windows guid to a Qt QUuid.
QByteArray toByteArray () const
Returns the binary representation of this QUuid.
QByteArray toRfc4122 () const
Returns the binary representation of this QUuid.
QString toString () const
Returns the string representation of this QUuid.
QUuid::Variant variant () const
Returns the value in the Variant field {variant field} of the UUID.
QUuid::Version version () const
Returns the Version field {version field} of the UUID, if the UUID's Variant field {variant field} is QUuid::DCE.
Static Public Functions
static QUuid createUuid ()
On any platform other than Windows, this function returns a new UUID with variant QUuid::DCE and version QUuid::Random.
static QUuid fromRfc4122 (const QByteArray &)
Creates a QUuid object from the binary representation of the UUID given by bytes, as specified by RFC 4122 section 4.
Public Variables
uint data1
ushort data2
ushort data3
uchar data4 [8]
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &s, const QUuid &id)
Writes the UUID id to the data stream s.
QDataStream & operator>> (QDataStream &s, QUuid &id)
Reads a UUID from the stream s into id.
Detailed Description
The QUuid class stores a Universally Unique Identifier (UUID).
Note
This class or function is reentrant.
Using Universally Unique IDentifiers (UUID) is a standard way to uniquely identify entities in a distributed computing environment. A UUID is a 16-byte (128-bit) number generated by some algorithm that is meant to guarantee that the UUID will be unique in the distributed computing environment where it is used. The acronym GUID is often used instead, Globally Unique IDentifiers, but it refers to the same thing.
Actually, the GUID is one variant of UUID. Multiple variants are in use. Each UUID contains a bit field that specifies which type (variant) of UUID it is. Call variant() to discover which type of UUID an instance of QUuid contains. It extracts the three most signifcant bits of byte 8 of the 16 bytes. In QUuid, byte 8 is QUuid::data4[0]. If you create instances of QUuid using the constructor that accepts all the numeric values as parameters, use the following table to set the three most significant bits of parameter b1, which becomes QUuid::data4[0] and contains the variant field in its three most significant bits. In the table, 'x' means {don't care}.
msb0 msb1 msb2
Variant
0 x x
NCS (Network Computing System)
1 0 x
DCE (Distributed Computing Environment)
1 1 0
Microsoft (GUID)
1 1 1
Reserved for future expansion
If variant() returns QUuid::DCE, the UUID also contains a version field in the four most significant bits of QUuid::data3, and you can call version() to discover which version your QUuid contains. If you create instances of QUuid using the constructor that accepts all the numeric values as parameters, use the following table to set the four most significant bits of parameter w2, which becomes QUuid::data3 and contains the version field in its four most significant bits.
msb0 msb1 msb2 msb3
Version
0 0 0 1
Time
0 0 1 0
Embedded POSIX
0 0 1 1
Name
0 1 0 0
Random
The field layouts for the DCE versions listed in the table above are specified in the Network Working Group UUID Specification.
Most platforms provide a tool for generating new UUIDs, e.g. uuidgen and guidgen. You can also use createUuid(). UUIDs generated by createUuid() are of the random type. Their QUuid::Version bits are set to QUuid::Random, and their QUuid::Variant bits are set to QUuid::DCE. The rest of the UUID is composed of random numbers. Theoretically, this means there is a small chance that a UUID generated by createUuid() will not be unique. But it is a very small chance.
UUIDs can be constructed from numeric values or from strings, or using the static createUuid() function. They can be converted to a string with toString(). UUIDs have a variant() and a version(), and null UUIDs return true from isNull().
Definition at line 67 of file quuid.h.
Enumerations
Variant
enum QUuid::Variant
This enum defines the values used in the Variant field {variant field} of the UUID.
The value in the variant field determines the layout of the 128-bit value.
VarUnknown Variant is unknown
NCS Reserved for NCS (Network Computing System) backward compatibility
DCE Distributed Computing Environment, the scheme used by QUuid
Microsoft Reserved for Microsoft backward compatibility (GUID)
Reserved Reserved for future definition
Enumerator
VarUnknown
NCS
DCE
Microsoft
Reserved
Definition at line 69 of file quuid.h.
                  {
         VarUnknown        =-1,
         NCS                = 0, // 0 - -
         DCE                = 2, // 1 0 -
         Microsoft        = 6, // 1 1 0
         Reserved        = 7  // 1 1 1
     };
Version
enum QUuid::Version
This enum defines the values used in the Version field {version field} of the UUID.
The version field is meaningful only if the value in the Variant field {variant field} is QUuid::DCE.
VerUnknown Version is unknown
Time Time-based, by using timestamp, clock sequence, and MAC network card address (if available) for the node sections
EmbeddedPOSIX DCE Security version, with embedded POSIX UUIDs
Name Name-based, by using values from a name for all sections
Random Random-based, by using random numbers for all sections
Enumerator
VerUnknown
Time
EmbeddedPOSIX
Name
Random
Definition at line 77 of file quuid.h.
                  {
         VerUnknown        =-1,
         Time                = 1, // 0 0 0 1
         EmbeddedPOSIX        = 2, // 0 0 1 0
         Name                = 3, // 0 0 1 1
         Random                = 4  // 0 1 0 0
     };
Constructors and Destructors
QUuid() [1/6]
QUuid::QUuid () inline
Creates the null UUID.
toString() will output the null UUID as "{00000000-0000-0000-0000-000000000000}".
Definition at line 85 of file quuid.h.
Referenced by fromRfc4122(), and QUuid().
     {
         data1 = 0;
         data2 = 0;
         data3 = 0;
         for(int i = 0; i < 8; i++)
             data4[i] = 0;
     }
QUuid() [2/6]
QUuid::QUuid (uint l, ushort w1, ushort w2, uchar b1, uchar b2, uchar b3, uchar b4, uchar b5, uchar b6, uchar b7, uchar b8) inline
Creates a UUID with the value specified by the parameters, l, w1, w2, b1, b2, b3, b4, b5, b6, b7, b8.
Example:
// {67C8770B-44F1-410A-AB9A-F9B5446F13EE}
QUuid IID_MyInterface(0x67c8770b, 0x44f1, 0x410a, 0xab, 0x9a, 0xf9, 0xb5, 0x44, 0x6f, 0x13, 0xee)
Definition at line 93 of file quuid.h.
     {
         data1 = l;
         data2 = w1;
         data3 = w2;
         data4[0] = b1;
         data4[1] = b2;
         data4[2] = b3;
         data4[3] = b4;
         data4[4] = b5;
         data4[5] = b6;
         data4[6] = b7;
         data4[7] = b8;
     }
QUuid() [3/6]
QUuid::QUuid (const QString & text)
Creates a QUuid object from the string text, which must be formatted as five hex fields separated by '-', e.g., "{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}" where 'x' is a hex digit.
The curly braces shown here are optional, but it is normal to include them. If the conversion fails, a null UUID is created. See toString() for an explanation of how the five hex fields map to the public data members in QUuid.
See also
toString(), QUuid()
Definition at line 335 of file quuid.cpp.
 {
     if (text.length() < 36) {
         *this = QUuid();
         return;
     }
     const ushort *data = reinterpret_cast<const ushort *>(text.unicode());
     if (*data == '{' && text.length() < 37) {
         *this = QUuid();
         return;
     }
     if (!_q_uuidFromHex(data, data1, data2, data3, data4)) {
         *this = QUuid();
         return;
     }
 }
QUuid() [4/6]
QUuid::QUuid (const char * text)
Warning
This function is not part of the public interface.
Definition at line 358 of file quuid.cpp.
 {
     if (!text) {
         *this = QUuid();
         return;
     }
     if (!_q_uuidFromHex(text, data1, data2, data3, data4)) {
         *this = QUuid();
         return;
     }
 }
QUuid() [5/6]
QUuid::QUuid (const QByteArray & text)
Creates a QUuid object from the QByteArray text, which must be formatted as five hex fields separated by '-', e.g., "{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}" where 'x' is a hex digit.
The curly braces shown here are optional, but it is normal to include them. If the conversion fails, a null UUID is created. See toByteArray() for an explanation of how the five hex fields map to the public data members in QUuid.
Since
4.8
See also
toByteArray(), QUuid()
Definition at line 384 of file quuid.cpp.
 {
     if (text.length() < 36) {
         *this = QUuid();
         return;
     }
     const char *data = text.constData();
     if (*data == '{' && text.length() < 37) {
         *this = QUuid();
         return;
     }
     if (!_q_uuidFromHex(data, data1, data2, data3, data4)) {
         *this = QUuid();
         return;
     }
 }
QUuid() [6/6]
QUuid::QUuid (const GUID & guid) inline
Casts a Windows guid to a Qt QUuid.
Warning
This function is only for Windows platforms.
Definition at line 144 of file quuid.h.
     {
         data1 = guid.Data1;
         data2 = guid.Data2;
         data3 = guid.Data3;
         for(int i = 0; i < 8; i++)
             data4[i] = guid.Data4[i];
     }
Functions
createUuid()
QUuid QUuid::createUuid () static
On any platform other than Windows, this function returns a new UUID with variant QUuid::DCE and version QUuid::Random.
If the /dev/urandom device exists, then the numbers used to construct the UUID will be of cryptographic quality, which will make the UUID unique. Otherwise, the numbers of the UUID will be obtained from the local pseudo-random number generator (qrand(), which is seeded by qsrand()) which is usually not of cryptograhic quality, which means that the UUID can't be guaranteed to be unique.
On a Windows platform, a GUID is generated, which almost certainly will be unique, on this or any other system, networked or not.
See also
variant(), version()
Definition at line 897 of file quuid.cpp.
Referenced by QBBRootWindow::createWindowGroup(), QFontEngineFTRawFont::initFromData(), QMainWindowLayout::insertIntoMacToolbar(), operator>(), QAuBucketQWS::QAuBucketQWS(), QNetworkSessionPrivateImpl::QNetworkSessionPrivateImpl(), and QMacPrintEnginePrivate::setPaperSize().
 {
     QUuid result;
     uint *data = &(result.data1);
 #if defined(Q_OS_UNIX)
     QFile *devUrandom;
 #  if !defined(QT_BOOTSTRAPPED)
     devUrandom = devUrandomStorage()->localData();
     if (!devUrandom) {
         devUrandom = new QFile(QLatin1String("/dev/urandom"));
         devUrandom->open(QIODevice::ReadOnly | QIODevice::Unbuffered);
         devUrandomStorage()->setLocalData(devUrandom);
     }
 # else
     QFile file(QLatin1String("/dev/urandom"));
     devUrandom = &file;
     devUrandom->open(QIODevice::ReadOnly | QIODevice::Unbuffered);
 # endif
     enum { AmountToRead = 4 * sizeof(uint) };
     if (devUrandom->isOpen()
         && devUrandom->read((char *) data, AmountToRead) == AmountToRead) {
         // we got what we wanted, nothing more to do
         ;
     } else
 #endif
     {
         static const int intbits = sizeof(int)*8;
         static int randbits = 0;
         if (!randbits) {
             int r = 0;
             int max = RAND_MAX;
             do { ++r; } while ((max=max>>1));
             randbits = r;
         }
         // Seed the PRNG once per thread with a combination of current time, a
         // stack address and a serial counter (since thread stack addresses are
         // re-used).
 #ifndef QT_BOOTSTRAPPED
         static QThreadStorage<int *> uuidseed;
         if (!uuidseed.hasLocalData())
         {
             int *pseed = new int;
             static QBasicAtomicInt serial = Q_BASIC_ATOMIC_INITIALIZER(2);
             qsrand(*pseed = QDateTime::currentDateTime().toTime_t()
                    + quintptr(&pseed)
                    + serial.fetchAndAddRelaxed(1));
             uuidseed.setLocalData(pseed);
         }
 #else
         static bool seeded = false;
         if (!seeded)
             qsrand(QDateTime::currentDateTime().toTime_t()
                    + quintptr(&seeded));
 #endif
         int chunks = 16 / sizeof(uint);
         while (chunks--) {
             uint randNumber = 0;
             for (int filled = 0; filled < intbits; filled += randbits)
                 randNumber |= qrand()<<filled;
 #if defined(Q_OS_SYMBIAN)
             // Symbian does not have /dev/urandom, so entropy is low.
             // Add more entropy from the kernel tick count (1ms resolution).
             // big multipler used to splatter the tick count bits over the whole 32 bits
             randNumber ^= User::NTickCount() * 0x3b9aca07;
 #endif
             *(data+chunks) = randNumber;
         }
     }
     result.data4[0] = (result.data4[0] & 0x3F) | 0x80;        // UV_DCE
     result.data3 = (result.data3 & 0x0FFF) | 0x4000;        // UV_Random
     return result;
 }
fromRfc4122()
QUuid QUuid::fromRfc4122 (const QByteArray & bytes) static
Creates a QUuid object from the binary representation of the UUID given by bytes, as specified by RFC 4122 section 4.
Since
4.8
1.2. See toRfc4122() for a further explanation of the order of bytes required.
The byte array accepted is not a human readable format.
If the conversion fails, a null UUID is created.
See also
toRfc4122(), QUuid()
Definition at line 421 of file quuid.cpp.
Referenced by operator>>().
 {
     if (bytes.isEmpty() || bytes.length() != 16)
         return QUuid();
     uint d1;
     ushort d2, d3;
     uchar d4[8];
     const uchar *data = reinterpret_cast<const uchar *>(bytes.constData());
     d1 = qFromBigEndian<quint32>(data);
     data += sizeof(quint32);
     d2 = qFromBigEndian<quint16>(data);
     data += sizeof(quint16);
     d3 = qFromBigEndian<quint16>(data);
     data += sizeof(quint16);
     for (int i = 0; i < 8; ++i) {
         d4[i] = *(data);
         data++;
     }
     return QUuid(d1, d2, d3, d4[0], d4[1], d4[2], d4[3], d4[4], d4[5], d4[6], d4[7]);
 }
isNull()
bool QUuid::isNull () const
Returns true if this is the null UUID {00000000-0000-0000-0000-000000000000}; otherwise returns false.
Definition at line 700 of file quuid.cpp.
Referenced by classIDL(), QAxServerBase::internalConnect(), QAxBase::queryInterface(), MetaObjectGenerator::readEnumInfo(), QAxBase::setControl(), variant(), and version().
 {
     return data4[0] == 0 && data4[1] == 0 && data4[2] == 0 && data4[3] == 0 &&
            data4[4] == 0 && data4[5] == 0 && data4[6] == 0 && data4[7] == 0 &&
            data1 == 0 && data2 == 0 && data3 == 0;
 }
operator GUID()
QUuid::operator GUID () const inline
Returns a Windows GUID from a QUuid.
Warning
This function is only for Windows platforms.
Definition at line 159 of file quuid.h.
     {
         GUID guid = { data1, data2, data3, { data4[0], data4[1], data4[2], data4[3], data4[4], data4[5], data4[6], data4[7] } };
         return guid;
     }
operator QString()
QUuid::operator QString () const inline
Returns the string representation of the uuid.
See also
toString()
Definition at line 111 of file quuid.h.
 { return toString(); } // ### Qt5 remove
operator!=() [1/2]
bool QUuid::operator!= (const QUuid & orig) const inline
Returns true if this QUuid and the other QUuid are different; otherwise returns false.
Definition at line 133 of file quuid.h.
     {
         return !(*this == orig);
     }
operator!=() [2/2]
bool QUuid::operator!= (const GUID & guid) const inline
Returns true if this UUID is not equal to the Windows GUID guid; otherwise returns false.
Definition at line 170 of file quuid.h.
     {
         return !(*this == guid);
     }
operator<()
bool QUuid::operator< (const QUuid & other) const
Returns true if this QUuid has the same Variant field {variant field} as the other QUuid and is lexicographically before the other QUuid.
If the other QUuid has a different variant field, the return value is determined by comparing the two variants.
See also
variant()
Definition at line 807 of file quuid.cpp.
 {
     if (variant() != other.variant())
         return variant() < other.variant();
     ISLESS(data1, other.data1);
     ISLESS(data2, other.data2);
     ISLESS(data3, other.data3);
     for (int n = 0; n < 8; n++) {
         ISLESS(data4[n], other.data4[n]);
     }
     return false;
 }
operator=()
QUuid & QUuid::operator= (const GUID & guid) inline
Assigns a Windows guid to a Qt QUuid.
Warning
This function is only for Windows platforms.
Definition at line 153 of file quuid.h.
     {
         *this = QUuid(guid);
         return *this;
     }
operator==() [1/2]
bool QUuid::operator== (const QUuid & orig) const inline
Returns true if this QUuid and the other QUuid are identical; otherwise returns false.
Definition at line 119 of file quuid.h.
     {
         uint i;
         if (data1 != orig.data1 || data2 != orig.data2 ||
              data3 != orig.data3)
             return false;
         for(i = 0; i < 8; i++)
             if (data4[i] != orig.data4[i])
                 return false;
         return true;
     }
operator==() [2/2]
bool QUuid::operator== (const GUID & guid) const inline
Returns true if this UUID is equal to the Windows GUID guid; otherwise returns false.
Definition at line 165 of file quuid.h.
     {
         return *this == QUuid(guid);
     }
operator>()
bool QUuid::operator> (const QUuid & other) const
Returns true if this QUuid has the same Variant field {variant field} as the other QUuid and is lexicographically after the other QUuid.
If the other QUuid has a different variant field, the return value is determined by comparing the two variants.
See also
variant()
Definition at line 836 of file quuid.cpp.
 {
     if (variant() != other.variant())
         return variant() > other.variant();
     ISMORE(data1, other.data1);
     ISMORE(data2, other.data2);
     ISMORE(data3, other.data3);
     for (int n = 0; n < 8; n++) {
         ISMORE(data4[n], other.data4[n]);
     }
     return false;
 }
toByteArray()
QByteArray QUuid::toByteArray () const
Returns the binary representation of this QUuid.
The byte array is formatted as five hex fields separated by '-' and enclosed in curly braces, i.e., "{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}" where 'x' is a hex digit. From left to right, the five hex fields are obtained from the four public data members in QUuid as follows:
Field #
Source
1
data1
2
data2
3
data3
4
data4[0] .. data4[1]
5
data4[2] .. data4[7]
Since
4.8
Definition at line 558 of file quuid.cpp.
Referenced by QFontEngineFTRawFont::initFromData().
 {
     QByteArray result(38, Qt::Uninitialized);
     char *data = result.data();
     _q_uuidToHex(data, data1, data2, data3, data4);
     return result;
 }
toRfc4122()
QByteArray QUuid::toRfc4122 () const
Returns the binary representation of this QUuid.
The byte array is in big endian format, and formatted according to RFC 4122, section 4.1.2 - "Layout and byte order".
The order is as follows:
Field #
Source
1
data1
2
data2
3
data3
4
data4[0] .. data4[7]
Since
4.8
Definition at line 601 of file quuid.cpp.
 {
     // we know how many bytes a UUID has, I hope :)
     QByteArray bytes(16, Qt::Uninitialized);
     uchar *data = reinterpret_cast<uchar*>(bytes.data());
     qToBigEndian(data1, data);
     data += sizeof(quint32);
     qToBigEndian(data2, data);
     data += sizeof(quint16);
     qToBigEndian(data3, data);
     data += sizeof(quint16);
     for (int i = 0; i < 8; ++i) {
         *(data) = data4[i];
         data++;
     }
     return bytes;
 }
toString()
QString QUuid::toString () const
Returns the string representation of this QUuid.
The string is formatted as five hex fields separated by '-' and enclosed in curly braces, i.e., "{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}" where 'x' is a hex digit. From left to right, the five hex fields are obtained from the four public data members in QUuid as follows:
Field #
Source
1
data1
2
data2
3
data3
4
data4[0] .. data4[1]
5
data4[2] .. data4[7]
Definition at line 512 of file quuid.cpp.
Referenced by classIDL(), QBBRootWindow::createWindowGroup(), DumpIDL(), MetaObjectGenerator::readClassInfo(), MetaObjectGenerator::readEventInfo(), MetaObjectGenerator::readInterfaceInfo(), QAxBase::setControl(), and UpdateRegistry().
 {
     QString result(38, Qt::Uninitialized);
     ushort *data = (ushort *)result.unicode();
     _q_uuidToHex(data, data1, data2, data3, data4);
     return result;
 }
variant()
QUuid::Variant QUuid::variant () const
Returns the value in the Variant field {variant field} of the UUID.
If the return value is QUuid::DCE, call version() to see which layout it uses. The null UUID is considered to be of an unknown variant.
See also
version()
Definition at line 756 of file quuid.cpp.
Referenced by operator<(), operator>(), and version().
 {
     if (isNull())
         return VarUnknown;
     // Check the 3 MSB of data4[0]
     if ((data4[0] & 0x80) == 0x00) return NCS;
     else if ((data4[0] & 0xC0) == 0x80) return DCE;
     else if ((data4[0] & 0xE0) == 0xC0) return Microsoft;
     else if ((data4[0] & 0xE0) == 0xE0) return Reserved;
     return VarUnknown;
 }
version()
QUuid::Version QUuid::version () const
Returns the Version field {version field} of the UUID, if the UUID's Variant field {variant field} is QUuid::DCE.
Otherwise it returns QUuid::VerUnknown.
See also
variant()
Definition at line 780 of file quuid.cpp.
 {
     // Check the 4 MSB of data3
     Version ver = (Version)(data3>>12);
     if (isNull()
          || (variant() != DCE)
          || ver < Time
          || ver > Random)
         return VerUnknown;
     return ver;
 }
Friends and Related Functions
operator<<()
QDataStream & operator<< (QDataStream & s, const QUuid & id) related
Writes the UUID id to the data stream s.
Definition at line 630 of file quuid.cpp.
 {
     QByteArray bytes;
     if (s.byteOrder() == QDataStream::BigEndian) {
         bytes = id.toRfc4122();
     } else {
         // we know how many bytes a UUID has, I hope :)
         bytes = QByteArray(16, Qt::Uninitialized);
         uchar *data = reinterpret_cast<uchar*>(bytes.data());
         qToLittleEndian(id.data1, data);
         data += sizeof(quint32);
         qToLittleEndian(id.data2, data);
         data += sizeof(quint16);
         qToLittleEndian(id.data3, data);
         data += sizeof(quint16);
         for (int i = 0; i < 8; ++i) {
             *(data) = id.data4[i];
             data++;
         }
     }
     if (s.writeRawData(bytes.data(), 16) != 16) {
         s.setStatus(QDataStream::WriteFailed);
     }
     return s;
 }
operator>>()
QDataStream & operator>> (QDataStream & s, QUuid & id) related
Reads a UUID from the stream s into id.
Definition at line 666 of file quuid.cpp.
 {
     QByteArray bytes(16, Qt::Uninitialized);
     if (s.readRawData(bytes.data(), 16) != 16) {
         s.setStatus(QDataStream::ReadPastEnd);
         return s;
     }
     if (s.byteOrder() == QDataStream::BigEndian) {
         id = QUuid::fromRfc4122(bytes);
     } else {
         const uchar *data = reinterpret_cast<const uchar *>(bytes.constData());
         id.data1 = qFromLittleEndian<quint32>(data);
         data += sizeof(quint32);
         id.data2 = qFromLittleEndian<quint16>(data);
         data += sizeof(quint16);
         id.data3 = qFromLittleEndian<quint16>(data);
         data += sizeof(quint16);
         for (int i = 0; i < 8; ++i) {
             id.data4[i] = *(data);
             data++;
         }
     }
     return s;
 }
Properties
data1
uint QUuid::data1
Definition at line 179 of file quuid.h.
Referenced by createUuid(), isNull(), operator<(), operator<<(), operator==(), operator>(), QUuid(), toByteArray(), toRfc4122(), and toString().
data2
ushort QUuid::data2
Definition at line 180 of file quuid.h.
Referenced by isNull(), operator<(), operator<<(), operator==(), operator>(), QUuid(), toByteArray(), toRfc4122(), and toString().
data3
ushort QUuid::data3
Definition at line 181 of file quuid.h.
Referenced by createUuid(), isNull(), operator<(), operator<<(), operator==(), operator>(), QUuid(), toByteArray(), toRfc4122(), toString(), and version().
data4
uchar QUuid::data4[8]
Definition at line 182 of file quuid.h.
Referenced by createUuid(), isNull(), operator<(), operator<<(), operator==(), operator>(), QUuid(), toByteArray(), toRfc4122(), toString(), and variant().
The documentation for this class was generated from the following files:
/src/corelib/plugin/quuid.h
/src/corelib/plugin/quuid.cpp