Qt 4.8: QWaylandXCompositeGLXIntegration Class Reference
QWaylandXCompositeGLXIntegration Class Reference
#include <qwaylandxcompositeglxintegration.h>
Public Functions
QWaylandWindow * createEglWindow (QWidget *widget)
void initialize ()
QWaylandXCompositeGLXIntegration (QWaylandDisplay *waylandDispaly)
Window rootWindow () const
int screen () const
QWaylandDisplay * waylandDisplay () const
struct wl_xcomposite * waylandXComposite () const
Display * xDisplay () const
~QWaylandXCompositeGLXIntegration ()
Public Functions inherited from QWaylandGLIntegration
QWaylandGLIntegration ()
virtual ~QWaylandGLIntegration ()
Static Private Functions
static void rootInformation (void *data, struct wl_xcomposite *xcomposite, const char *display_name, uint32_t root_window)
static void wlDisplayHandleGlobal (struct wl_display *display, uint32_t id, const char *interface, uint32_t version, void *data)
Properties
Display * mDisplay
Window mRootWindow
int mScreen
struct wl_xcomposite * mWaylandComposite
QWaylandDisplay * mWaylandDisplay
Static Private Attributes
static const struct wl_xcomposite_listener xcomposite_listener
Additional Inherited Members
Static Public Functions inherited from QWaylandGLIntegration
static QWaylandGLIntegration * createGLIntegration (QWaylandDisplay *waylandDisplay)
Detailed Description
Definition at line 102 of file qwaylandxcompositeglxintegration.cpp.
Constructors and Destructors
QWaylandXCompositeGLXIntegration()
QWaylandXCompositeGLXIntegration::QWaylandXCompositeGLXIntegration (QWaylandDisplay * waylandDispaly)
Definition at line 55 of file qwaylandxcompositeglxintegration.cpp.
     : QWaylandGLIntegration()
     , mWaylandDisplay(waylandDispaly)
 {
     qDebug() << "Using XComposite-GLX";
     wl_display_add_global_listener(waylandDispaly->wl_display(), QWaylandXCompositeGLXIntegration::wlDisplayHandleGlobal,
                                    this);
 }
~QWaylandXCompositeGLXIntegration()
QWaylandXCompositeGLXIntegration::~QWaylandXCompositeGLXIntegration ()
Definition at line 64 of file qwaylandxcompositeglxintegration.cpp.
 {
     XCloseDisplay(mDisplay);
 }
Functions
createEglWindow()
QWaylandWindow * QWaylandXCompositeGLXIntegration::createEglWindow (QWidget * widget) virtual
Implements QWaylandGLIntegration.
Definition at line 73 of file qwaylandxcompositeglxintegration.cpp.
 {
     return new QWaylandXCompositeGLXWindow(widget,this);
 }
initialize()
void QWaylandXCompositeGLXIntegration::initialize () virtual
Implements QWaylandGLIntegration.
Definition at line 69 of file qwaylandxcompositeglxintegration.cpp.
 {
 }
rootInformation()
void QWaylandXCompositeGLXIntegration::rootInformation (void * data, struct wl_xcomposite * xcomposite, const char * display_name, uint32_t root_window) static private
Definition at line 117 of file qwaylandxcompositeglxintegration.cpp.
 {
     Q_UNUSED(xcomposite);
     QWaylandXCompositeGLXIntegration *integration = static_cast<QWaylandXCompositeGLXIntegration *>(data);
     integration->mDisplay = XOpenDisplay(display_name);
     integration->mRootWindow = (Window) root_window;
     integration->mScreen = XDefaultScreen(integration->mDisplay);
 }
rootWindow()
Window QWaylandXCompositeGLXIntegration::rootWindow () const
Definition at line 88 of file qwaylandxcompositeglxintegration.cpp.
Referenced by QWaylandXCompositeGLXContext::geometryChanged().
 {
     return mRootWindow;
 }
screen()
int QWaylandXCompositeGLXIntegration::screen () const
Definition at line 83 of file qwaylandxcompositeglxintegration.cpp.
Referenced by QWaylandXCompositeGLXContext::geometryChanged().
 {
     return mScreen;
 }
waylandDisplay()
QWaylandDisplay * QWaylandXCompositeGLXIntegration::waylandDisplay () const
Definition at line 93 of file qwaylandxcompositeglxintegration.cpp.
Referenced by QWaylandXCompositeGLXContext::geometryChanged(), and QWaylandXCompositeGLXContext::waitForSync().
 {
     return mWaylandDisplay;
 }
waylandXComposite()
wl_xcomposite * QWaylandXCompositeGLXIntegration::waylandXComposite () const
Definition at line 97 of file qwaylandxcompositeglxintegration.cpp.
Referenced by QWaylandXCompositeGLXContext::geometryChanged().
 {
     return mWaylandComposite;
 }
wlDisplayHandleGlobal()
void QWaylandXCompositeGLXIntegration::wlDisplayHandleGlobal (struct wl_display * display, uint32_t id, const char * interface, uint32_t version, void * data) static private
Definition at line 106 of file qwaylandxcompositeglxintegration.cpp.
Referenced by QWaylandXCompositeGLXIntegration().
 {
     Q_UNUSED(version);
     if (strcmp(interface, "wl_xcomposite") == 0) {
         QWaylandXCompositeGLXIntegration *integration = static_cast<QWaylandXCompositeGLXIntegration *>(data);
         integration->mWaylandComposite = wl_xcomposite_create(display,id,1);
         wl_xcomposite_add_listener(integration->mWaylandComposite,&xcomposite_listener,integration);
     }
 }
xDisplay()
Display * QWaylandXCompositeGLXIntegration::xDisplay () const
Definition at line 78 of file qwaylandxcompositeglxintegration.cpp.
Referenced by QWaylandXCompositeGLXContext::doneCurrent(), QWaylandXCompositeGLXContext::geometryChanged(), QWaylandXCompositeGLXContext::makeCurrent(), QWaylandXCompositeGLXContext::platformWindowFormat(), QWaylandXCompositeGLXContext::QWaylandXCompositeGLXContext(), and QWaylandXCompositeGLXContext::swapBuffers().
 {
     return mDisplay;
 }
Properties
mDisplay
Display* QWaylandXCompositeGLXIntegration::mDisplay private
Definition at line 79 of file qwaylandxcompositeglxintegration.h.
Referenced by rootInformation(), xDisplay(), and ~QWaylandXCompositeGLXIntegration().
mRootWindow
Window QWaylandXCompositeGLXIntegration::mRootWindow private
Definition at line 81 of file qwaylandxcompositeglxintegration.h.
Referenced by rootInformation(), and rootWindow().
mScreen
int QWaylandXCompositeGLXIntegration::mScreen private
Definition at line 80 of file qwaylandxcompositeglxintegration.h.
Referenced by rootInformation(), and screen().
mWaylandComposite
struct wl_xcomposite* QWaylandXCompositeGLXIntegration::mWaylandComposite private
Definition at line 77 of file qwaylandxcompositeglxintegration.h.
Referenced by waylandXComposite(), and wlDisplayHandleGlobal().
mWaylandDisplay
QWaylandDisplay* QWaylandXCompositeGLXIntegration::mWaylandDisplay private
Definition at line 76 of file qwaylandxcompositeglxintegration.h.
Referenced by waylandDisplay().
xcomposite_listener
const struct wl_xcomposite_listener QWaylandXCompositeGLXIntegration::xcomposite_listener static private
Definition at line 86 of file qwaylandxcompositeglxintegration.h.
Referenced by wlDisplayHandleGlobal().
The documentation for this class was generated from the following files:
/src/plugins/platforms/wayland/gl_integration/xcomposite_glx/qwaylandxcompositeglxintegration.cpp
/src/plugins/platforms/wayland/gl_integration/xcomposite_glx/qwaylandxcompositeglxintegration.h