Qt 4.8: QWSProtocolItem Struct Reference
QWSProtocolItem Struct Reference
#include <qwsprotocolitem_qws.h>
Public Functions
void copyFrom (const QWSProtocolItem *item)
QWSProtocolItem (int t, int len, char *ptr)
bool read (QIODevice *s)
virtual void setData (const char *data, int len, bool allocateMem=true)
void write (QIODevice *s)
virtual ~QWSProtocolItem ()
Public Variables
int bytesRead
bool deleteRaw
char * rawDataPtr
int rawLen
char * simpleDataPtr
int simpleLen
int type
Detailed Description
Definition at line 61 of file qwsprotocolitem_qws.h.
Constructors and Destructors
QWSProtocolItem()
QWSProtocolItem::QWSProtocolItem (int t, int len, char * ptr) inline
Definition at line 64 of file qwsprotocolitem_qws.h.
                                                : type(t),
         simpleLen(len), rawLen(-1), deleteRaw(false), simpleDataPtr(ptr),
         rawDataPtr(0), bytesRead(0) { }
~QWSProtocolItem()
QWSProtocolItem::~QWSProtocolItem () virtual
Definition at line 432 of file qwscommand_qws.cpp.
Referenced by QWSProtocolItem().
{
     if (deleteRaw)
         delete []rawDataPtr;
 }
Functions
copyFrom()
void QWSProtocolItem::copyFrom (const QWSProtocolItem * item)
Definition at line 472 of file qwscommand_qws.cpp.
Referenced by qt_client_enqueue(), and qt_server_enqueue().
{
     if (this == item)
         return;
     simpleLen = item->simpleLen;
     memcpy(simpleDataPtr, item->simpleDataPtr, simpleLen);
     setData(item->rawDataPtr, item->rawLen);
 }
read()
bool QWSProtocolItem::read (QIODevice * s)
Definition at line 448 of file qwscommand_qws.cpp.
Referenced by RequestAnalyzer::analyze().
{
 #ifdef QWSCOMMAND_DEBUG
     QLatin1String reread( (rawLen == -1) ? "" : "REREAD");
     if (qwsServer)
         qDebug() << "QWSProtocolItem::read reading type " << static_cast<QWSCommand::Type>(type) << reread;
     else
         qDebug() << "QWSProtocolItem::read reading event " << (type < N_EVENTS ? eventNames[type] : "unknown") << reread;
     //qDebug("QWSProtocolItem::read reading event %s", type < N_EVENTS ? eventNames[type] : "unknown");
 #endif
     bool b = qws_read_command(s, simpleDataPtr, simpleLen, rawDataPtr, rawLen, bytesRead);
     if (b) {
         setData(rawDataPtr, rawLen, false);
         deleteRaw = true;
     }
 #ifdef QWSCOMMAND_DEBUG
     else
     {
         qDebug() << "error in reading command " << static_cast<QWSCommand::Type>(type);
     }
 #endif
     return b;
 }
setData()
void QWSProtocolItem::setData (const char * data, int len, bool allocateMem = true) virtual
Reimplemented in QWSFontCommand, QWSEmbedCommand, QWSIMResponseCommand, QWSQCopSendCommand, QWSQCopRegisterChannelCommand, QWSPlaySoundCommand, QWSDefineCursorCommand, QWSFontEvent, QWSRepaintRegionCommand, QWSSetPropertyCommand, QWSIMInitEvent, QWSIMEvent, QWSQCopMessageEvent, QWSPropertyReplyEvent, QWSEmbedEvent, QWSRegionCommand, QWSRegionEvent, QWSRegionNameCommand, QWSIdentifyCommand, and QWSConnectedEvent.
Definition at line 480 of file qwscommand_qws.cpp.
Referenced by QWSQCopRegisterChannelCommand::setChannel(), QWSConnectedEvent::setData(), QWSIdentifyCommand::setData(), QWSRegionNameCommand::setData(), QWSRegionEvent::setData(), QWSRegionCommand::setData(), QWSEmbedEvent::setData(), QWSPropertyReplyEvent::setData(), QWSQCopMessageEvent::setData(), QWSIMEvent::setData(), QWSIMInitEvent::setData(), QWSSetPropertyCommand::setData(), QWSRepaintRegionCommand::setData(), QWSFontEvent::setData(), QWSDefineCursorCommand::setData(), QWSPlaySoundCommand::setData(), QWSQCopRegisterChannelCommand::setData(), QWSQCopSendCommand::setData(), QWSIMResponseCommand::setData(), QWSEmbedCommand::setData(), QWSFontCommand::setData(), QWSQCopMessageEvent::setDataDirect(), QWSPlaySoundCommand::setFileName(), QWSFontCommand::setFontName(), QWSIdentifyCommand::setId(), QWSQCopSendCommand::setMessage(), QWSRegionNameCommand::setName(), and QWSIMResponseCommand::setResult().
{
     if (deleteRaw)
         delete [] rawDataPtr;
     if (!data || len <= 0) {
         rawDataPtr = 0;
         rawLen = 0;
         return;
     }
     if (allocateMem) {
         rawDataPtr = new char[len];
         memcpy(rawDataPtr, data, len);
         deleteRaw = true;
     } else {
         rawDataPtr = const_cast<char *>(data);
         deleteRaw = false;
     }
     rawLen = len;
 }
write()
void QWSProtocolItem::write (QIODevice * s)
Definition at line 438 of file qwscommand_qws.cpp.
Referenced by QWSDisplay::Data::init(), QWSDisplay::Data::reinit(), QWSDisplay::Data::sendCommand(), QWSDisplay::Data::sendSynchronousCommand(), and QWSDisplay::Data::~Data().
{
 #ifdef QWSCOMMAND_DEBUG
     if (!qwsServer)
         qDebug() << "QWSProtocolItem::write sending type " << static_cast<QWSCommand::Type>(type);
     else
         qDebug() << "QWSProtocolItem::write sending event " << (type < N_EVENTS ? eventNames[type] : "unknown");
 #endif
     qws_write_command(s, type, simpleDataPtr, simpleLen, rawDataPtr, rawLen);
 }
Properties
bytesRead
int QWSProtocolItem::bytesRead
Definition at line 87 of file qwsprotocolitem_qws.h.
deleteRaw
bool QWSProtocolItem::deleteRaw
Definition at line 73 of file qwsprotocolitem_qws.h.
Referenced by QWSQCopMessageEvent::setDataDirect(), and QWSQCopSendCommand::setMessage().
rawDataPtr
char* QWSProtocolItem::rawDataPtr
Definition at line 85 of file qwsprotocolitem_qws.h.
Referenced by copyFrom(), QWSConnectedEvent::setData(), QWSRegionEvent::setData(), QWSRegionCommand::setData(), QWSEmbedEvent::setData(), QWSPropertyReplyEvent::setData(), QWSQCopMessageEvent::setData(), QWSIMEvent::setData(), QWSIMInitEvent::setData(), QWSSetPropertyCommand::setData(), QWSRepaintRegionCommand::setData(), QWSFontEvent::setData(), QWSDefineCursorCommand::setData(), QWSPlaySoundCommand::setData(), and QWSEmbedCommand::setData().
rawLen
int QWSProtocolItem::rawLen
Definition at line 72 of file qwsprotocolitem_qws.h.
Referenced by copyFrom(), QWSDisplay::Data::flush(), and QWSServerPrivate::invokeSetProperty().
simpleDataPtr
char* QWSProtocolItem::simpleDataPtr
Definition at line 84 of file qwsprotocolitem_qws.h.
Referenced by copyFrom(), QWSDisplay::grabKeyboard(), QWSDisplay::grabMouse(), QWSDisplay::repaintRegion(), QWSDisplay::setAltitude(), and QWSEvent::window().
simpleLen
int QWSProtocolItem::simpleLen
Definition at line 71 of file qwsprotocolitem_qws.h.
Referenced by copyFrom(), and QWSDisplay::Data::flush().
type
int QWSProtocolItem::type
Definition at line 70 of file qwsprotocolitem_qws.h.
Referenced by QWSEvent::asMouse(), QWSDisplay::Data::dequeue(), QWSServerPrivate::doClient(), QWSDisplay::Data::fillQueue(), QWSDisplay::Data::flush(), QEventDispatcherQWS::processEvents(), qt_client_enqueue(), qt_directpainter_embedevent(), qt_server_enqueue(), qt_try_modal(), qwsEventSourceDispatch(), QApplication::qwsProcessEvent(), QWSRegionEvent::setData(), QWSEmbedEvent::setData(), QWSEmbedCommand::setData(), QWSDisplay::waitForQCopResponse(), QWSDisplay::Data::waitForRegionAck(), QWSDisplay::Data::waitForRegionEvents(), and QWSEvent::window().
The documentation for this struct was generated from the following files:
/src/gui/embedded/qwsprotocolitem_qws.h
/src/gui/embedded/qwscommand_qws.cpp