Qt 4.8: QWSEvent Class Reference
QWSEvent Class Reference
The QWSEvent class encapsulates an event in Qt for Embedded Linux.
#include <qwsevent_qws.h>
Public Types
enum Type {
NoEvent, Connected, Mouse, Focus,
Key, Region, Creation, PropertyNotify,
PropertyReply, SelectionClear, SelectionRequest, SelectionNotify,
MaxWindowRect, QCopMessage, WindowOperation, IMEvent,
IMQuery, IMInit, Embed, Font,
ScreenTransformation, NEvent
}
This enum describes the origin of the event.
Public Functions
QWSMouseEvent * asMouse ()
QWSEvent (int t, int len, char *ptr)
int window ()
int window () const
Public Functions inherited from QWSProtocolItem
void copyFrom (const QWSProtocolItem *item)
QWSProtocolItem (int t, int len, char *ptr)
bool read (QIODevice *s)
virtual void setData (const char *data, int len, bool allocateMem=true)
void write (QIODevice *s)
virtual ~QWSProtocolItem ()
Static Public Functions
static QWSEvent * factory (int type)
Additional Inherited Members
Public Variables inherited from QWSProtocolItem
int bytesRead
bool deleteRaw
char * rawDataPtr
int rawLen
char * simpleDataPtr
int simpleLen
int type
Detailed Description
The QWSEvent class encapsulates an event in Qt for Embedded Linux.
When running a Qt for Embedded Linux application, it either runs as a server or connects to an existing server. All system generated events are passed to the server application which then propagates the event to the appropriate client.
Whenever the server receives an event, it queries its stack of top-level windows to find the window containing the event's position. Each window can identify the client application that created it, and returns its ID to the server upon request. Finally, the server forwards the event, encapsulated by an instance of the QWSEvent class, to the appropriate client.
The server communicates with the client applications over the UNIX domain socket. You can retrieve direct access to all the events a client receives from the server, by reimplementing QApplication's QApplication::qwsEventFilter() function.
QWSEvent provides the Type enum specifying the origin of the event. Internally, each type is represented by a QWSEvent subclass, e.g., QWSKeyEvent.
See also
QWSServer, QWSClient, {Qt for Embedded Linux Architecture}
Definition at line 59 of file qwsevent_qws.h.
Enumerations
Type
enum QWSEvent::Type
This enum describes the origin of the event.
NoEvent No event has occurred.
Connected An application has connected to the server.
Mouse A mouse button is pressed or released, or the mouse cursor is moved. See also Qt for Embedded Linux Pointer Handling.
Focus A window has lost or received focus.
Key A key is pressed or released. See also Qt for Embedded Linux Character Input.
Region A region has changed.
Creation The server has created an ID, typically for a window.
PropertyNotify A property has changed.
PropertyReply The server is responding to a request for a property's value.
SelectionClear A selection is deleted.
SelectionRequest The server has queried for a selection.
SelectionNotify A new selection has been created.
MaxWindowRect The server has changed the maximum window for an application.
QCopMessage A new Qt Cop message has appeared. See also QCopChannel
WindowOperation A window operation, e.g. resizing, has occurred.
IMEvent An input method has been used to enter text for languages with non-Latin alphabets. See also QWSInputMethod.
IMQuery An input method query for a specified property has occurred. See also QWSInputMethod.
NEvent The number of events has changed.
Embed An event used internally to implement embedded windows. See also QWSEmbedWidget.
ScreenTransformation An event used internally to notify the client processes that the screen has changed for example, rotation, etc.
Font
IMInit
Enumerator
NoEvent
Connected
Mouse
Focus
Key
Region
Creation
PropertyNotify
PropertyReply
SelectionClear
SelectionRequest
SelectionNotify
MaxWindowRect
QCopMessage
WindowOperation
IMEvent
IMQuery
IMInit
Embed
Font
ScreenTransformation
NEvent
Definition at line 65 of file qwsevent_qws.h.
               {
         NoEvent,
         Connected,
         Mouse,
         Focus,
         Key,
         Region,
         Creation,
         PropertyNotify,
         PropertyReply,
         SelectionClear,
         SelectionRequest,
         SelectionNotify,
         MaxWindowRect,
         QCopMessage,
         WindowOperation,
         IMEvent,
         IMQuery,
         IMInit,
         Embed,
         Font,
         ScreenTransformation,
         NEvent
     };
Constructors and Destructors
QWSEvent()
QWSEvent::QWSEvent (int t, int len, char * ptr) inline
Warning
This function is not part of the public interface.
Definition at line 61 of file qwsevent_qws.h.
 : QWSProtocolItem(t,len,ptr) {}
Functions
asMouse()
QWSMouseEvent * QWSEvent::asMouse () inline
Warning
This function is not part of the public interface.
Definition at line 90 of file qwsevent_qws.h.
Referenced by QApplication::qwsProcessEvent().
         { return type == Mouse ? reinterpret_cast<QWSMouseEvent*>(this) : 0; }
factory()
QWSEvent * QWSEvent::factory (int type) static
Warning
This function is not part of the public interface.
Definition at line 46 of file qwsevent_qws.cpp.
Referenced by qt_client_enqueue(), QWSDisplay::Data::readMore(), and window().
 {
     QWSEvent *event = 0;
     switch (type) {
     case QWSEvent::Connected:
         event = new QWSConnectedEvent;
         break;
     case QWSEvent::MaxWindowRect:
         event = new QWSMaxWindowRectEvent;
         break;
     case QWSEvent::Mouse:
         event = new QWSMouseEvent;
         break;
     case QWSEvent::Focus:
         event = new QWSFocusEvent;
         break;
     case QWSEvent::Key:
         event = new QWSKeyEvent;
         break;
     case QWSEvent::Region:
         event = new QWSRegionEvent;
         break;
     case QWSEvent::Creation:
         event = new QWSCreationEvent;
         break;
 #ifndef QT_NO_QWS_PROPERTIES
     case QWSEvent::PropertyNotify:
         event = new QWSPropertyNotifyEvent;
         break;
     case QWSEvent::PropertyReply:
         event = new QWSPropertyReplyEvent;
         break;
 #endif // QT_NO_QWS_PROPERTIES
     case QWSEvent::SelectionClear:
         event = new QWSSelectionClearEvent;
         break;
     case QWSEvent::SelectionRequest:
         event = new QWSSelectionRequestEvent;
         break;
     case QWSEvent::SelectionNotify:
         event = new QWSSelectionNotifyEvent;
         break;
 #ifndef QT_NO_COP
     case QWSEvent::QCopMessage:
         event = new QWSQCopMessageEvent;
         break;
 #endif
     case QWSEvent::WindowOperation:
         event = new QWSWindowOperationEvent;
         break;
 #ifndef QT_NO_QWS_INPUTMETHODS
     case QWSEvent::IMEvent:
         event = new QWSIMEvent;
         break;
     case QWSEvent::IMQuery:
         event = new QWSIMQueryEvent;
         break;
     case QWSEvent::IMInit:
         event = new QWSIMInitEvent;
         break;
 #endif
 #ifndef QT_NO_QWSEMBEDWIDGET
     case QWSEvent::Embed:
         event = new QWSEmbedEvent;
         break;
 #endif
     case QWSEvent::Font:
         event = new QWSFontEvent;
         break;
     case QWSEvent::ScreenTransformation:
         event = new QWSScreenTransformationEvent;
         break;
     default:
         qCritical("QWSEvent::factory() : Unknown event type %08x!", type);
     }
     return event;
 }
window() [1/2]
int QWSEvent::window () inline
Warning
This function is not part of the public interface.
Definition at line 92 of file qwsevent_qws.h.
Referenced by QWSDisplay::Data::fillQueue(), QApplication::qwsProcessEvent(), QWSDisplay::Data::waitForRegionAck(), and QWSDisplay::Data::waitForRegionEvents().
 { return *(reinterpret_cast<int*>(simpleDataPtr)); }
window() [2/2]
int QWSEvent::window () const inline
Warning
This function is not part of the public interface.
Definition at line 93 of file qwsevent_qws.h.
 { return *(reinterpret_cast<int*>(simpleDataPtr)); }
The documentation for this class was generated from the following files:
/src/gui/embedded/qwsevent_qws.h
/src/gui/embedded/qwsevent_qws.cpp