Qt 4.8: QVectorTypedData< T > Struct Template Reference
QVectorTypedData< T > Struct Template Reference
#include <qvector.h>
Static Public Functions
static void free (QVectorTypedData< T > *x, int alignment)
Public Variables
T array [1]
Additional Inherited Members
Static Private Functions inherited from QVectorData
static QVectorData * allocate (int size, int alignment)
static void free (QVectorData *data, int alignment)
static int grow (int sizeofTypedData, int size, int sizeofT, bool excessive)
static QVectorData * malloc (int sizeofTypedData, int size, int sizeofT, QVectorData *init)
static QVectorData * reallocate (QVectorData *old, int newsize, int oldsize, int alignment)
Properties inherited from QVectorData
int alloc
uint capacity: 1
QBasicAtomicInt ref
uint reserved: 30
uint sharable: 1
int size
Static Private Attributes inherited from QVectorData
static QVectorData shared_null = { Q_BASIC_ATOMIC_INITIALIZER(1), 0, 0, true, false, 0 }
Detailed Description
template<typename T>
struct QVectorTypedData< T >
Definition at line 94 of file qvector.h.
Functions
free()
template<typename T> static void QVectorTypedData< T >::free (QVectorTypedData< T > * x, int alignment) inline static
Definition at line 99 of file qvector.h.
Referenced by QVector< QPoint >::free(), QVector< QPoint >::operator=(), QVector< QPoint >::realloc(), and QVector< QPoint >::~QVector().
 { QVectorData::free(static_cast<QVectorData *>(x), alignment); }
Properties
array
template<typename T> T QVectorTypedData< T >::array[1]
Definition at line 97 of file qvector.h.
Referenced by QVector< QPoint >::free(), QVector< QPoint >::operator+=(), and QVector< QPoint >::operator==().
The documentation for this struct was generated from the following file:
/src/corelib/tools/qvector.h