Qt 4.8: QWSCommand Struct Reference
QWSCommand Struct Reference
#include <qwscommand_qws_p.h>
Public Types
enum Type {
Unknown = 0, Create, Shutdown, Region,
RegionMove, RegionDestroy, SetProperty, AddProperty,
RemoveProperty, GetProperty, SetSelectionOwner, ConvertSelection,
RequestFocus, ChangeAltitude, SetOpacity, DefineCursor,
SelectCursor, PositionCursor, GrabMouse, PlaySound,
QCopRegisterChannel, QCopSend, RegionName, Identify,
GrabKeyboard, RepaintRegion, IMMouse, IMUpdate,
IMResponse, Embed, Font, ScreenTransform
}
Public Functions
QWSCommand (int t, int len, char *ptr)
Public Functions inherited from QWSProtocolItem
void copyFrom (const QWSProtocolItem *item)
QWSProtocolItem (int t, int len, char *ptr)
bool read (QIODevice *s)
virtual void setData (const char *data, int len, bool allocateMem=true)
void write (QIODevice *s)
virtual ~QWSProtocolItem ()
Static Public Functions
static QWSCommand * factory (int type)
Additional Inherited Members
Public Variables inherited from QWSProtocolItem
int bytesRead
bool deleteRaw
char * rawDataPtr
int rawLen
char * simpleDataPtr
int simpleLen
int type
Detailed Description
Definition at line 90 of file qwscommand_qws_p.h.
Enumerations
Type
enum QWSCommand::Type
Enumerator
Unknown
Create
Shutdown
Region
RegionMove
RegionDestroy
SetProperty
AddProperty
RemoveProperty
GetProperty
SetSelectionOwner
ConvertSelection
RequestFocus
ChangeAltitude
SetOpacity
DefineCursor
SelectCursor
PositionCursor
GrabMouse
PlaySound
QCopRegisterChannel
QCopSend
RegionName
Identify
GrabKeyboard
RepaintRegion
IMMouse
IMUpdate
IMResponse
Embed
Font
ScreenTransform
Definition at line 94 of file qwscommand_qws_p.h.
               {
         Unknown = 0,
         Create,
         Shutdown,
         Region,
         RegionMove,
         RegionDestroy,
         SetProperty,
         AddProperty,
         RemoveProperty,
         GetProperty,
         SetSelectionOwner,
         ConvertSelection,
         RequestFocus,
         ChangeAltitude,
         SetOpacity,
         DefineCursor,
         SelectCursor,
         PositionCursor,
         GrabMouse,
         PlaySound,
         QCopRegisterChannel,
         QCopSend,
         RegionName,
         Identify,
         GrabKeyboard,
         RepaintRegion,
         IMMouse,
         IMUpdate,
         IMResponse,
         Embed,
         Font,
         ScreenTransform
     };
Constructors and Destructors
QWSCommand()
QWSCommand::QWSCommand (int t, int len, char * ptr) inline
Definition at line 92 of file qwscommand_qws_p.h.
 : QWSProtocolItem(t,len,ptr) {}
Functions
factory()
QWSCommand * QWSCommand::factory (int type) static
Definition at line 499 of file qwscommand_qws.cpp.
Referenced by RequestAnalyzer::analyze(), qt_server_enqueue(), and QWSClient::readMoreCommand().
 {
     QWSCommand *command = 0;
     switch (type) {
     case QWSCommand::Create:
         command = new QWSCreateCommand;
         break;
     case QWSCommand::Shutdown:
         command = new QWSCommand(type, 0, 0);
         break;
     case QWSCommand::Region:
         command = new QWSRegionCommand;
         break;
     case QWSCommand::RegionMove:
         command = new QWSRegionMoveCommand;
         break;
     case QWSCommand::RegionDestroy:
         command = new QWSRegionDestroyCommand;
         break;
     case QWSCommand::AddProperty:
         command = new QWSAddPropertyCommand;
         break;
     case QWSCommand::SetProperty:
         command = new QWSSetPropertyCommand;
         break;
     case QWSCommand::RemoveProperty:
         command = new QWSRemovePropertyCommand;
         break;
     case QWSCommand::GetProperty:
         command = new QWSGetPropertyCommand;
         break;
     case QWSCommand::SetSelectionOwner:
         command = new QWSSetSelectionOwnerCommand;
         break;
     case QWSCommand::RequestFocus:
         command = new QWSRequestFocusCommand;
         break;
     case QWSCommand::ChangeAltitude:
         command = new QWSChangeAltitudeCommand;
         break;
     case QWSCommand::SetOpacity:
         command = new QWSSetOpacityCommand;
         break;
     case QWSCommand::DefineCursor:
         command = new QWSDefineCursorCommand;
         break;
     case QWSCommand::SelectCursor:
         command = new QWSSelectCursorCommand;
         break;
     case QWSCommand::GrabMouse:
         command = new QWSGrabMouseCommand;
         break;
     case QWSCommand::GrabKeyboard:
         command = new QWSGrabKeyboardCommand;
         break;
 #ifndef QT_NO_SOUND
     case QWSCommand::PlaySound:
         command = new QWSPlaySoundCommand;
         break;
 #endif
 #ifndef QT_NO_COP
     case QWSCommand::QCopRegisterChannel:
         command = new QWSQCopRegisterChannelCommand;
         break;
     case QWSCommand::QCopSend:
         command = new QWSQCopSendCommand;
         break;
 #endif
     case QWSCommand::RegionName:
         command = new QWSRegionNameCommand;
         break;
     case QWSCommand::Identify:
         command = new QWSIdentifyCommand;
         break;
     case QWSCommand::RepaintRegion:
         command = new QWSRepaintRegionCommand;
         break;
 #ifndef QT_NO_QWS_INPUTMETHODS
     case QWSCommand::IMUpdate:
         command = new QWSIMUpdateCommand;
         break;
     case QWSCommand::IMMouse:
         command = new QWSIMMouseCommand;
         break;
     case QWSCommand::IMResponse:
         command = new QWSIMResponseCommand;
         break;
 #endif
     case QWSCommand::PositionCursor:
         command = new QWSPositionCursorCommand;
         break;
 #ifndef QT_NO_QWSEMBEDWIDGET
     case QWSCommand::Embed:
         command = new QWSEmbedCommand;
         break;
 #endif
     case QWSCommand::Font:
         command = new QWSFontCommand;
         break;
     case QWSCommand::ScreenTransform:
         command = new QWSScreenTransformCommand;
         break;
     default:
         qWarning("QWSCommand::factory : Type error - got %08x!", type);
     }
     return command;
 }
The documentation for this struct was generated from the following files:
/src/gui/embedded/qwscommand_qws_p.h
/src/gui/embedded/qwscommand_qws.cpp