Qt 4.8: QWaylandXCompositeEGLIntegration Class Reference
QWaylandXCompositeEGLIntegration Class Reference
#include <qwaylandxcompositeeglintegration.h>
Public Functions
QWaylandWindow * createEglWindow (QWidget *widget)
EGLDisplay eglDisplay () const
void initialize ()
QWaylandXCompositeEGLIntegration (QWaylandDisplay *waylandDispaly)
Window rootWindow () const
int screen () const
QWaylandDisplay * waylandDisplay () const
struct wl_xcomposite * waylandXComposite () const
Display * xDisplay () const
~QWaylandXCompositeEGLIntegration ()
Public Functions inherited from QWaylandGLIntegration
QWaylandGLIntegration ()
virtual ~QWaylandGLIntegration ()
Static Private Functions
static void rootInformation (void *data, struct wl_xcomposite *xcomposite, const char *display_name, uint32_t root_window)
static void wlDisplayHandleGlobal (struct wl_display *display, uint32_t id, const char *interface, uint32_t version, void *data)
Properties
Display * mDisplay
EGLDisplay mEglDisplay
Window mRootWindow
int mScreen
struct wl_xcomposite * mWaylandComposite
QWaylandDisplay * mWaylandDisplay
Static Private Attributes
static const struct wl_xcomposite_listener xcomposite_listener
Additional Inherited Members
Static Public Functions inherited from QWaylandGLIntegration
static QWaylandGLIntegration * createGLIntegration (QWaylandDisplay *waylandDisplay)
Detailed Description
Definition at line 107 of file qwaylandxcompositeeglintegration.cpp.
Constructors and Destructors
QWaylandXCompositeEGLIntegration()
QWaylandXCompositeEGLIntegration::QWaylandXCompositeEGLIntegration (QWaylandDisplay * waylandDispaly)
Definition at line 55 of file qwaylandxcompositeeglintegration.cpp.
     : QWaylandGLIntegration()
     , mWaylandDisplay(waylandDispaly)
 {
     qDebug() << "Using XComposite-EGL";
     wl_display_add_global_listener(mWaylandDisplay->wl_display(), QWaylandXCompositeEGLIntegration::wlDisplayHandleGlobal,
                                    this);
 }
~QWaylandXCompositeEGLIntegration()
QWaylandXCompositeEGLIntegration::~QWaylandXCompositeEGLIntegration ()
Definition at line 64 of file qwaylandxcompositeeglintegration.cpp.
 {
     XCloseDisplay(mDisplay);
 }
Functions
createEglWindow()
QWaylandWindow * QWaylandXCompositeEGLIntegration::createEglWindow (QWidget * widget) virtual
Implements QWaylandGLIntegration.
Definition at line 73 of file qwaylandxcompositeeglintegration.cpp.
 {
     return new QWaylandXCompositeEGLWindow(widget,this);
 }
eglDisplay()
EGLDisplay QWaylandXCompositeEGLIntegration::eglDisplay () const
Definition at line 83 of file qwaylandxcompositeeglintegration.cpp.
Referenced by QWaylandXCompositeEGLContext::doneCurrent(), QWaylandXCompositeEGLContext::geometryChanged(), QWaylandXCompositeEGLContext::makeCurrent(), QWaylandXCompositeEGLContext::platformWindowFormat(), QWaylandXCompositeEGLContext::QWaylandXCompositeEGLContext(), rootInformation(), and QWaylandXCompositeEGLContext::swapBuffers().
 {
     return mEglDisplay;
 }
initialize()
void QWaylandXCompositeEGLIntegration::initialize () virtual
Implements QWaylandGLIntegration.
Definition at line 69 of file qwaylandxcompositeeglintegration.cpp.
 {
 }
rootInformation()
void QWaylandXCompositeEGLIntegration::rootInformation (void * data, struct wl_xcomposite * xcomposite, const char * display_name, uint32_t root_window) static private
Definition at line 122 of file qwaylandxcompositeeglintegration.cpp.
 {
     Q_UNUSED(xcomposite);
     QWaylandXCompositeEGLIntegration *integration = static_cast<QWaylandXCompositeEGLIntegration *>(data);
     integration->mDisplay = XOpenDisplay(display_name);
     integration->mRootWindow = (Window) root_window;
     integration->mScreen = XDefaultScreen(integration->mDisplay);
     integration->mEglDisplay = eglGetDisplay(integration->mDisplay);
     eglBindAPI(EGL_OPENGL_ES_API);
     EGLint minor,major;
     if (!eglInitialize(integration->mEglDisplay,&major,&minor)) {
         qFatal("Failed to initialize EGL");
     }
     eglSwapInterval(integration->eglDisplay(),0);
     qDebug() << "ROOT INFORMATION" << integration->mDisplay << integration->mRootWindow << integration->mScreen;
 }
rootWindow()
Window QWaylandXCompositeEGLIntegration::rootWindow () const
Definition at line 93 of file qwaylandxcompositeeglintegration.cpp.
Referenced by QWaylandXCompositeEGLContext::geometryChanged().
 {
     return mRootWindow;
 }
screen()
int QWaylandXCompositeEGLIntegration::screen () const
Definition at line 88 of file qwaylandxcompositeeglintegration.cpp.
 {
     return mScreen;
 }
waylandDisplay()
QWaylandDisplay * QWaylandXCompositeEGLIntegration::waylandDisplay () const
Definition at line 98 of file qwaylandxcompositeeglintegration.cpp.
Referenced by QWaylandXCompositeEGLContext::geometryChanged().
 {
     return mWaylandDisplay;
 }
waylandXComposite()
wl_xcomposite * QWaylandXCompositeEGLIntegration::waylandXComposite () const
Definition at line 102 of file qwaylandxcompositeeglintegration.cpp.
Referenced by QWaylandXCompositeEGLContext::geometryChanged().
 {
     return mWaylandComposite;
 }
wlDisplayHandleGlobal()
void QWaylandXCompositeEGLIntegration::wlDisplayHandleGlobal (struct wl_display * display, uint32_t id, const char * interface, uint32_t version, void * data) static private
Definition at line 111 of file qwaylandxcompositeeglintegration.cpp.
Referenced by QWaylandXCompositeEGLIntegration().
 {
     Q_UNUSED(version);
     if (strcmp(interface, "wl_xcomposite") == 0) {
         QWaylandXCompositeEGLIntegration *integration = static_cast<QWaylandXCompositeEGLIntegration *>(data);
         integration->mWaylandComposite = wl_xcomposite_create(display,id,1);
         wl_xcomposite_add_listener(integration->mWaylandComposite,&xcomposite_listener,integration);
     }
 }
xDisplay()
Display * QWaylandXCompositeEGLIntegration::xDisplay () const
Definition at line 78 of file qwaylandxcompositeeglintegration.cpp.
Referenced by QWaylandXCompositeEGLContext::geometryChanged().
 {
     return mDisplay;
 }
Properties
mDisplay
Display* QWaylandXCompositeEGLIntegration::mDisplay private
Definition at line 83 of file qwaylandxcompositeeglintegration.h.
Referenced by rootInformation(), xDisplay(), and ~QWaylandXCompositeEGLIntegration().
mEglDisplay
EGLDisplay QWaylandXCompositeEGLIntegration::mEglDisplay private
Definition at line 84 of file qwaylandxcompositeeglintegration.h.
Referenced by eglDisplay(), and rootInformation().
mRootWindow
Window QWaylandXCompositeEGLIntegration::mRootWindow private
Definition at line 86 of file qwaylandxcompositeeglintegration.h.
Referenced by rootInformation(), and rootWindow().
mScreen
int QWaylandXCompositeEGLIntegration::mScreen private
Definition at line 85 of file qwaylandxcompositeeglintegration.h.
Referenced by rootInformation(), and screen().
mWaylandComposite
struct wl_xcomposite* QWaylandXCompositeEGLIntegration::mWaylandComposite private
Definition at line 81 of file qwaylandxcompositeeglintegration.h.
Referenced by waylandXComposite(), and wlDisplayHandleGlobal().
mWaylandDisplay
QWaylandDisplay* QWaylandXCompositeEGLIntegration::mWaylandDisplay private
Definition at line 80 of file qwaylandxcompositeeglintegration.h.
Referenced by QWaylandXCompositeEGLIntegration(), and waylandDisplay().
xcomposite_listener
const struct wl_xcomposite_listener QWaylandXCompositeEGLIntegration::xcomposite_listener static private
Definition at line 91 of file qwaylandxcompositeeglintegration.h.
Referenced by wlDisplayHandleGlobal().
The documentation for this class was generated from the following files:
/src/plugins/platforms/wayland/gl_integration/xcomposite_egl/qwaylandxcompositeeglintegration.cpp
/src/plugins/platforms/wayland/gl_integration/xcomposite_egl/qwaylandxcompositeeglintegration.h