Qt 4.8: QMetaObject Class Reference
QMetaObject Class Reference
The QMetaObject class contains meta-information about Qt objects.
#include <qobjectdefs.h>
Public Types
enum Call {
InvokeMetaMethod, ReadProperty, WriteProperty, ResetProperty,
QueryPropertyDesignable, QueryPropertyScriptable, QueryPropertyStored, QueryPropertyEditable,
QueryPropertyUser, CreateInstance
}
Public Functions
QObject * cast (QObject *obj) const
Returns obj if object obj inherits from this meta-object; otherwise returns 0.
const QObject * cast (const QObject *obj) const
Returns obj if object obj inherits from this meta-object; otherwise returns 0.
QMetaClassInfo classInfo (int index) const
Returns the meta-data for the item of class information with the given index.
int classInfoCount () const
Returns the number of items of class information in this class.
int classInfoOffset () const
Returns the class information offset for this class; i.e.
const char * className () const
Returns the class name.
QMetaMethod constructor (int index) const
Returns the meta-data for the constructor with the given index.
int constructorCount () const
Returns the number of constructors in this class.
QMetaEnum enumerator (int index) const
Returns the meta-data for the enumerator with the given index.
int enumeratorCount () const
Returns the number of enumerators in this class.
int enumeratorOffset () const
Returns the enumerator offset for this class; i.e.
int indexOfClassInfo (const char *name) const
Finds class information item name and returns its index; otherwise returns -1.
int indexOfConstructor (const char *constructor) const
Finds constructor and returns its index; otherwise returns -1.
int indexOfEnumerator (const char *name) const
Finds enumerator name and returns its index; otherwise returns -1.
int indexOfMethod (const char *method) const
Finds method and returns its index; otherwise returns -1.
int indexOfProperty (const char *name) const
Finds property name and returns its index; otherwise returns -1.
int indexOfSignal (const char *signal) const
Finds signal and returns its index; otherwise returns -1.
int indexOfSlot (const char *slot) const
Finds slot and returns its index; otherwise returns -1.
QMetaMethod method (int index) const
Returns the meta-data for the method with the given index.
int methodCount () const
Returns the number of methods known to the meta-object system in this class, including the number of properties provided by each base class.
int methodOffset () const
Returns the method offset for this class; i.e.
QObject * newInstance (QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument()) const
Constructs a new instance of this class.
QMetaProperty property (int index) const
Returns the meta-data for the property with the given index.
int propertyCount () const
Returns the number of properties in this class, including the number of properties provided by each base class.
int propertyOffset () const
Returns the property offset for this class; i.e.
int static_metacall (Call, int, void **) const
const QMetaObject * superClass () const
Returns the meta-object of the superclass, or 0 if there is no such object.
QString tr (const char *s, const char *c) const
QString tr (const char *s, const char *c, int n) const
QString trUtf8 (const char *s, const char *c) const
QString trUtf8 (const char *s, const char *c, int n) const
QMetaProperty userProperty () const
Returns the property that has the USER flag set to true.
Static Public Functions
static void activate (QObject *sender, int signal_index, void **argv)
static void activate (QObject *sender, int from_signal_index, int to_signal_index, void **argv)
static void activate (QObject *sender, const QMetaObject *, int local_signal_index, void **argv)
static void activate (QObject *sender, const QMetaObject *, int from_local_signal_index, int to_local_signal_index, void **argv)
static void addGuard (QObject **ptr)
static void changeGuard (QObject **ptr, QObject *o)
static bool checkConnectArgs (const char *signal, const char *method)
Returns true if the signal and method arguments are compatible; otherwise returns false.
static bool connect (const QObject *sender, int signal_index, const QObject *receiver, int method_index, int type=0, int *types=0)
static void connectSlotsByName (QObject *o)
Searches recursively for all child objects of the given object, and connects matching signals from them to slots of object that follow the following form:
static bool disconnect (const QObject *sender, int signal_index, const QObject *receiver, int method_index)
static bool disconnectOne (const QObject *sender, int signal_index, const QObject *receiver, int method_index)
static bool invokeMethod (QObject *obj, const char *member, Qt::ConnectionType, QGenericReturnArgument ret, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
Invokes the member (a signal or a slot name) on the object obj.
static bool invokeMethod (QObject *obj, const char *member, QGenericReturnArgument ret, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
static bool invokeMethod (QObject *obj, const char *member, Qt::ConnectionType type, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
static bool invokeMethod (QObject *obj, const char *member, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
static int metacall (QObject *, Call, int, void **)
static QByteArray normalizedSignature (const char *method)
Normalizes the signature of the given method.
static QByteArray normalizedType (const char *type)
Normalizes a type.
static void removeGuard (QObject **ptr)
Public Variables
struct {
const uint * data
const void * extradata
const char * stringdata
const QMetaObject * superdata
} d
Detailed Description
The QMetaObject class contains meta-information about Qt objects.
The Qt Meta-Object System in Qt is responsible for the signals and slots inter-object communication mechanism, runtime type information, and the Qt property system. A single QMetaObject instance is created for each QObject subclass that is used in an application, and this instance stores all the meta-information for the QObject subclass. This object is available as QObject::metaObject().
This class is not normally required for application programming, but it is useful if you write meta-applications, such as scripting engines or GUI builders.
The functions you are most likely to find useful are these:
className() returns the name of a class.
superClass() returns the superclass's meta-object.
method() and methodCount() provide information about a class's meta-methods (signals, slots and other invokable member functions).
enumerator() and enumeratorCount() and provide information about a class's enumerators.
propertyCount() and property() provide information about a class's properties.
constructor() and constructorCount() provide information about a class's meta-constructors.
The index functions indexOfConstructor(), indexOfMethod(), indexOfEnumerator(), and indexOfProperty() map names of constructors, member functions, enumerators, or properties to indexes in the meta-object. For example, Qt uses indexOfMethod() internally when you connect a signal to a slot.
Classes can also have a list of name–value pairs of additional class information, stored in QMetaClassInfo objects. The number of pairs is returned by classInfoCount(), single pairs are returned by classInfo(), and you can search for pairs with indexOfClassInfo().
See also
QMetaClassInfo, QMetaEnum, QMetaMethod, QMetaProperty, QMetaType, {Meta-Object System}
Definition at line 304 of file qobjectdefs.h.
Enumerations
Call
enum QMetaObject::Call
Warning
This function is not part of the public interface.
InvokeSlot
EmitSignal
ReadProperty
WriteProperty
ResetProperty
QueryPropertyDesignable
QueryPropertyScriptable
QueryPropertyStored
QueryPropertyEditable
QueryPropertyUser
CreateInstance
Enumerator
InvokeMetaMethod
ReadProperty
WriteProperty
ResetProperty
QueryPropertyDesignable
QueryPropertyScriptable
QueryPropertyStored
QueryPropertyEditable
QueryPropertyUser
CreateInstance
Definition at line 448 of file qobjectdefs.h.
               {
         InvokeMetaMethod,
         ReadProperty,
         WriteProperty,
         ResetProperty,
         QueryPropertyDesignable,
         QueryPropertyScriptable,
         QueryPropertyStored,
         QueryPropertyEditable,
         QueryPropertyUser,
         CreateInstance
     };
Functions
activate() [1/4]
void QMetaObject::activate (QObject * sender, int signal_index, void ** argv) static
Warning
This function is not part of the public interface. Obsolete. (signal_index comes from indexOfMethod())
Definition at line 3690 of file qobject.cpp.
Referenced by QDeclarativeVMEMetaObject::list_append(), QDeclarativeVMEMetaObject::list_clear(), QDeclarativeVMEMetaObject::listChanged(), QDBusInterfacePrivate::metacall(), QDeclarativeProxyMetaObject::metaCall(), QDeclarativeOpenMetaObject::metaCall(), QDeclarativeVMEMetaObject::metaCall(), QAxBase::qt_metacall(), QDBusAdaptorConnector::relaySignal(), QDeclarativeContext::setContextProperty(), QDeclarativeOpenMetaObject::setValue(), and QDeclarativeVMEMetaObject::writeVarProperty().
 {
     const QMetaObject *mo = sender->metaObject();
     while (mo->methodOffset() > signal_index)
         mo = mo->superClass();
     activate(sender, mo, signal_index - mo->methodOffset(), argv);
 }
activate() [2/4]
void QMetaObject::activate (QObject * sender, int from_signal_index, int to_signal_index, void ** argv) static
Warning
This function is not part of the public interface.
Definition at line 3496 of file qobject.cpp.
 {
     Q_UNUSED(to_signal_index);
     activate(sender, from_signal_index, argv);
 }
activate() [3/4]
void QMetaObject::activate (QObject * sender, const QMetaObject * m, int local_signal_index, void ** argv) static
Warning
This function is not part of the public interface.
Definition at line 3504 of file qobject.cpp.
 {
     int signalOffset;
     int methodOffset;
     computeOffsets(m, &signalOffset, &methodOffset);
     int signal_index = signalOffset + local_signal_index;
     if (!sender->d_func()->isSignalConnected(signal_index))
         return; // nothing connected to these signals, and no spy
     if (sender->d_func()->blockSig)
         return;
     int signal_absolute_index = methodOffset + local_signal_index;
     void *empty_argv[] = { 0 };
     if (qt_signal_spy_callback_set.signal_begin_callback != 0) {
         qt_signal_spy_callback_set.signal_begin_callback(sender, signal_absolute_index,
                                                          argv ? argv : empty_argv);
     }
     Qt::HANDLE currentThreadId = QThread::currentThreadId();
     QMutexLocker locker(signalSlotLock(sender));
     QObjectConnectionListVector *connectionLists = sender->d_func()->connectionLists;
     if (!connectionLists) {
         locker.unlock();
         if (qt_signal_spy_callback_set.signal_end_callback != 0)
             qt_signal_spy_callback_set.signal_end_callback(sender, signal_absolute_index);
         return;
     }
     ++connectionLists->inUse;
     const QObjectPrivate::ConnectionList *list;
     if (signal_index < connectionLists->count())
         list = &connectionLists->at(signal_index);
     else
         list = &connectionLists->allsignals;
     do {
         QObjectPrivate::Connection *c = list->first;
         if (!c) continue;
         // We need to check against last here to ensure that signals added
         // during the signal emission are not emitted in this emission.
         QObjectPrivate::Connection *last = list->last;
         do {
             if (!c->receiver)
                 continue;
             QObject * const receiver = c->receiver;
             const bool receiverInSameThread = currentThreadId == receiver->d_func()->threadData->threadId;
             // determine if this connection should be sent immediately or
             // put into the event queue
             if ((c->connectionType == Qt::AutoConnection && !receiverInSameThread)
                 || (c->connectionType == Qt::QueuedConnection)) {
                 queued_activate(sender, signal_absolute_index, c, argv ? argv : empty_argv);
                 continue;
 #ifndef QT_NO_THREAD
             } else if (c->connectionType == Qt::BlockingQueuedConnection) {
                 locker.unlock();
                 if (receiverInSameThread) {
                     qWarning("Qt: Dead lock detected while activating a BlockingQueuedConnection: "
                     "Sender is %s(%p), receiver is %s(%p)",
                     sender->metaObject()->className(), sender,
                     receiver->metaObject()->className(), receiver);
                 }
                 QSemaphore semaphore;
                 QCoreApplication::postEvent(receiver, new QMetaCallEvent(c->method_offset, c->method_relative,
                                                                          c->callFunction,
                                                                          sender, signal_absolute_index,
                                                                          0, 0,
                                                                          argv ? argv : empty_argv,
                                                                          &semaphore));
                 semaphore.acquire();
                 locker.relock();
                 continue;
 #endif
             }
             QObjectPrivate::Sender currentSender;
             QObjectPrivate::Sender *previousSender = 0;
             if (receiverInSameThread) {
                 currentSender.sender = sender;
                 currentSender.signal = signal_absolute_index;
                 currentSender.ref = 1;
                 previousSender = QObjectPrivate::setCurrentSender(receiver, &currentSender);
             }
             const QObjectPrivate::StaticMetaCallFunction callFunction = c->callFunction;
             const int method_relative = c->method_relative;
             if (callFunction && c->method_offset <= receiver->metaObject()->methodOffset()) {
                 //we compare the vtable to make sure we are not in the destructor of the object.
                 locker.unlock();
                 if (qt_signal_spy_callback_set.slot_begin_callback != 0)
                     qt_signal_spy_callback_set.slot_begin_callback(receiver, c->method(), argv ? argv : empty_argv);
 #if defined(QT_NO_EXCEPTIONS)
                 callFunction(receiver, QMetaObject::InvokeMetaMethod, method_relative, argv ? argv : empty_argv);
 #else
                 QT_TRY {
                     callFunction(receiver, QMetaObject::InvokeMetaMethod, method_relative, argv ? argv : empty_argv);
                 } QT_CATCH(...) {
                     locker.relock();
                     if (receiverInSameThread)
                         QObjectPrivate::resetCurrentSender(receiver, &currentSender, previousSender);
                     --connectionLists->inUse;
                     Q_ASSERT(connectionLists->inUse >= 0);
                     if (connectionLists->orphaned && !connectionLists->inUse)
                         delete connectionLists;
                     QT_RETHROW;
                 }
 #endif
                 if (qt_signal_spy_callback_set.slot_end_callback != 0)
                     qt_signal_spy_callback_set.slot_end_callback(receiver, c->method());
                 locker.relock();
             } else {
                 const int method = method_relative + c->method_offset;
                 locker.unlock();
                 if (qt_signal_spy_callback_set.slot_begin_callback != 0) {
                     qt_signal_spy_callback_set.slot_begin_callback(receiver,
                                                                 method,
                                                                 argv ? argv : empty_argv);
                 }
 #if defined(QT_NO_EXCEPTIONS)
                 metacall(receiver, QMetaObject::InvokeMetaMethod, method, argv ? argv : empty_argv);
 #else
                 QT_TRY {
                     metacall(receiver, QMetaObject::InvokeMetaMethod, method, argv ? argv : empty_argv);
                 } QT_CATCH(...) {
                     locker.relock();
                     if (receiverInSameThread)
                         QObjectPrivate::resetCurrentSender(receiver, &currentSender, previousSender);
                     --connectionLists->inUse;
                     Q_ASSERT(connectionLists->inUse >= 0);
                     if (connectionLists->orphaned && !connectionLists->inUse)
                         delete connectionLists;
                     QT_RETHROW;
                 }
 #endif
                 if (qt_signal_spy_callback_set.slot_end_callback != 0)
                     qt_signal_spy_callback_set.slot_end_callback(receiver, method);
                 locker.relock();
             }
             if (receiverInSameThread)
                 QObjectPrivate::resetCurrentSender(receiver, &currentSender, previousSender);
             if (connectionLists->orphaned)
                 break;
         } while (c != last && (c = c->nextConnectionList) != 0);
         if (connectionLists->orphaned)
             break;
     } while (list != &connectionLists->allsignals &&
         //start over for all signals;
         ((list = &connectionLists->allsignals), true));
     --connectionLists->inUse;
     Q_ASSERT(connectionLists->inUse >= 0);
     if (connectionLists->orphaned) {
         if (!connectionLists->inUse)
             delete connectionLists;
     } else if (connectionLists->dirty) {
         sender->d_func()->cleanConnectionLists();
     }
     locker.unlock();
     if (qt_signal_spy_callback_set.signal_end_callback != 0)
         qt_signal_spy_callback_set.signal_end_callback(sender, signal_absolute_index);
 }
activate() [4/4]
void QMetaObject::activate (QObject * sender, const QMetaObject * m, int from_local_signal_index, int to_local_signal_index, void ** argv) static
Warning
This function is not part of the public interface. Obsolete, called by moc generated code before Qt 4.6 for cloned signals But since Qt 4.6, all clones are connected to their original
Definition at line 3702 of file qobject.cpp.
 {
     Q_UNUSED(to_local_signal_index);
     Q_ASSERT(from_local_signal_index == QMetaObjectPrivate::originalClone(m, to_local_signal_index));
     activate(sender, m, from_local_signal_index, argv);
 }
addGuard()
void QMetaObject::addGuard (QObject ** ptr) static
Warning
This function is not part of the public interface.
Definition at line 390 of file qobject.cpp.
Referenced by QAction::activate(), and QPointer< QAbstractButton >::QPointer().
 {
     if (!*ptr)
         return;
     GuardHash *hash = guardHash();
     if (!hash) {
         *ptr = 0;
         return;
     }
     QMutexLocker locker(guardHashLock());
     QObjectPrivate::get(*ptr)->hasGuards = true;
     hash->insert(*ptr, ptr);
 }
cast() [1/2]
QObject * QMetaObject::cast (QObject * obj) const
Returns obj if object obj inherits from this meta-object; otherwise returns 0.
Warning
This function is not part of the public interface.
Definition at line 283 of file qmetaobject.cpp.
Referenced by QScript::QtFunction::execute(), qobject_cast(), qt_qFindChild_helper(), and qt_qFindChildren_helper().
 {
     if (obj) {
         const QMetaObject *m = obj->metaObject();
         do {
             if (m == this)
                 return obj;
         } while ((m = m->d.superdata));
     }
     return 0;
 }
cast() [2/2]
const QObject * QMetaObject::cast (const QObject * obj) const
Returns obj if object obj inherits from this meta-object; otherwise returns 0.
Warning
This function is not part of the public interface.
Definition at line 304 of file qmetaobject.cpp.
 {
     if (obj) {
         const QMetaObject *m = obj->metaObject();
         do {
             if (m == this)
                 return obj;
         } while ((m = m->d.superdata));
     }
     return 0;
 }
changeGuard()
void QMetaObject::changeGuard (QObject ** ptr, QObject * o) static
Warning
This function is not part of the public interface.
Definition at line 435 of file qobject.cpp.
Referenced by QPointer< QAbstractButton >::operator=().
 {
     GuardHash *hash = guardHash();
     if (!hash) {
         *ptr = 0;
         return;
     }
     QMutexLocker locker(guardHashLock());
     if (o) {
         hash->insert(o, ptr);
         QObjectPrivate::get(o)->hasGuards = true;
     }
     if (*ptr) {
         bool more = false; //if the QObject has more pointer attached to it.
         GuardHash::iterator it = hash->find(*ptr);
         const GuardHash::iterator end = hash->end();
         for (; it.key() == *ptr && it != end; ++it) {
             if (it.value() == ptr) {
                 it = hash->erase(it);
                 if (!more) more = (it != end && it.key() == *ptr);
                 break;
             }
             more = true;
         }
         if (!more)
             QObjectPrivate::get(*ptr)->hasGuards = false;
     }
     *ptr = o;
 }
checkConnectArgs()
bool QMetaObject::checkConnectArgs (const char * signal, const char * method) static
Returns true if the signal and method arguments are compatible; otherwise returns false.
Both signal and method are expected to be normalized.
See also
normalizedSignature()
Definition at line 964 of file qmetaobject.cpp.
Referenced by QObject::connect(), QObject::inherits(), and signalForMember().
 {
     const char *s1 = signal;
     const char *s2 = method;
     while (*s1++ != '(') { }                        // scan to first '('
     while (*s2++ != '(') { }
     if (*s2 == ')' || qstrcmp(s1,s2) == 0)        // method has no args or
         return true;                                //   exact match
     int s1len = qstrlen(s1);
     int s2len = qstrlen(s2);
     if (s2len < s1len && strncmp(s1,s2,s2len-1)==0 && s1[s2len-1]==',')
         return true;                                // method has less args
     return false;
 }
classInfo()
QMetaClassInfo QMetaObject::classInfo (int index) const
Returns the meta-data for the item of class information with the given index.
Example:
class MyClass : public QObject
{
    Q_OBJECT
    Q_CLASSINFO("author", "Sabrina Schweinsteiger")
    Q_CLASSINFO("url", "http://doc.moosesoft.co.uk/1.0/")
public:
    ...
};
See also
classInfoCount(), classInfoOffset(), indexOfClassInfo()
Definition at line 941 of file qmetaobject.cpp.
Referenced by QAccessibleObjectPrivate::actionList(), QDBusAdaptorConnector::addAdaptor(), QMetaObjectBuilder::addMetaObject(), QAxFactory::classID(), classIDL(), clone(), QClassFactory::CreateInstanceHelper(), QAxClass< T >::createObject(), QDeclarativeMetaType::defaultMethod(), QDeclarativeMetaType::defaultProperty(), QDeclarativeCompiler::deferredProperties(), QAxFactory::eventsID(), QAxFactory::exposeToSuperClass(), QClassFactory::GetLicInfo(), QAxFactory::hasStockEvents(), QAxFactory::interfaceID(), QAxServerBase::Invoke(), QAxServerBase::Load(), qax_clean_type(), qax_generateDocumentation(), qax_noSuchFunction(), QClassFactory::QClassFactory(), qDBusGenerateMetaObjectXml(), QAxBase::querySubObject(), QAxFactory::registerActiveObject(), QAxServerBase::registerActiveObject(), QAxServerBase::Save(), and QAxFactory::validateLicenseKey().
 {
     int i = index;
     i -= classInfoOffset();
     if (i < 0 && d.superdata)
         return d.superdata->classInfo(index);
     QMetaClassInfo result;
     if (i >= 0 && i < priv(d.data)->classInfoCount) {
         result.mobj = this;
         result.handle = priv(d.data)->classInfoData + 2*i;
     }
     return result;
 }
classInfoCount()
int QMetaObject::classInfoCount () const
Returns the number of items of class information in this class.
See also
classInfo(), classInfoOffset(), indexOfClassInfo()
Definition at line 519 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addMetaObject(), and clone().
 {
     int n = priv(d.data)->classInfoCount;
     const QMetaObject *m = d.superdata;
     while (m) {
         n += priv(m->d.data)->classInfoCount;
         m = m->d.superdata;
     }
     return n;
 }
classInfoOffset()
int QMetaObject::classInfoOffset () const
Returns the class information offset for this class; i.e.
the index position of this class's first class information item.
If the class has no superclasses with class information, the offset is 0; otherwise the offset is the sum of all the class information items in the class's superclasses.
See also
classInfo(), classInfoCount(), indexOfClassInfo()
Definition at line 424 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addMetaObject(), classInfo(), clone(), indexOfClassInfo(), qDBusGenerateMetaObjectXml(), and qDBusInterfaceFromMetaObject().
 {
     int offset = 0;
     const QMetaObject *m = d.superdata;
     while (m) {
         offset += priv(m->d.data)->classInfoCount;
         m = m->d.superdata;
     }
     return offset;
 }
className()
const char * QMetaObject::className () const inline
Returns the class name.
See also
superClass()
Definition at line 491 of file qobjectdefs.h.
Referenced by activate(), ActiveObject::ActiveObject(), QGraphicsLayoutPrivate::addChildLayoutItem(), QLayout::addChildWidget(), QAccessibleWidget::addControllingSignal(), QMetaObjectBuilder::addMetaObject(), QAxScriptManager::addObject(), QState::addTransition(), QGridLayout::addWidget(), QMacStylePrivate::aquaSizeConstrain(), QStyleSheetStyleSelector::attribute(), check_and_warn_compat(), check_method_code(), check_parent_thread(), check_signal_macro(), QCoreApplicationPrivate::checkReceiverThread(), checkWidget(), classIDL(), QDeclarativeCompiler::compileAlias(), QObject::connect(), QAxClass< T >::createObject(), QLayoutPrivate::createSpacerItem(), QObject::disconnect(), QObject::dumpObjectInfo(), dumpRecursive(), QProxyStylePrivate::ensureBaseStyle(), QApplicationPrivate::enterModal_sys(), err_method_notfound(), QCoreApplication::exec(), QScript::QObjectConnectionManager::execute(), QScript::QMetaObjectWrapperObject::execute(), QApplication::font(), fromScriptValue(), QScript::functionConnect(), QScript::functionDisconnect(), QApplicationPrivate::globalEventProcessor(), QDeclarativeOpenMetaObjectTypePrivate::init(), QNetworkReplyImplPrivate::initCacheSaveDevice(), invokeMethod(), keyTypeForObject(), QApplicationPrivate::leaveModal_sys(), make_widget_eventUPP(), QStyleSheetStyle::nativeFrameWidth(), newInstance(), QScriptEnginePrivate::newQObject(), QStyleSheetStyleSelector::nodeNameEquals(), QStyleSheetStyleSelector::nodeNames(), QDeclarativeEngineDebugService::objectData(), objectInheritsXAndXIsCloserThanY(), QDeclarativeDebugService::objectToString(), operator<<(), QApplication::palette(), parentWidget(), QObject::property(), ptr(), qax_generateDocumentation(), qax_readClassInfo(), qax_readInterfaceInfo(), QAxServerBase::QAxServerBase(), QTest::qExec(), QLayout::QLayout(), QScript::qmetaobjectProtoFuncClassName(), qmlExecuteDeferred(), QScript::qobjectProtoFuncToString(), QTest::qPrintDataTags(), QRenderRule::QRenderRule(), QTest::qSignalDumperCallback(), QTest::qSignalDumperCallbackEndSignal(), QTest::qSignalDumperCallbackSlot(), qt_adopted_thread_watcher_function(), qt_aqua_get_known_size(), qt_mac_send_modifiers_changed(), qt_nograb(), QAccessible::queryAccessibleInterface(), QMetaProperty::read(), QDeclarativeEnginePrivate::registerCompositeType(), QStateMachinePrivate::registerSignalTransition(), QDBusAdaptorConnector::relay(), QCoreApplicationPrivate::removePostedEvent(), QGraphicsLayoutPrivate::reparentChildItems(), QKeyMapper::sendKeyEvent(), QMetaObjectBuilder::serialize(), QNetworkReplyImplPrivate::setCachingEnabled(), QWidget::setLayout(), QObject::setProperty(), QDBusPendingCallPrivate::setReplyCallback(), QThreadPrivate::start(), QmlJSDebugger::AbstractLiveEditTool::titleForItem(), QDeclarativeObjectScriptClass::tostring(), QDeclarativeType::typeName(), QAccessible::updateAccessibility(), QDeclarativeQtScriptExpression::updateGuards(), QGLContext::updatePaintDevice(), VARIANTToQVariant(), writeProperty(), and QDeclarativeInfo::~QDeclarativeInfo().
 { return d.stringdata; }
connect()
bool QMetaObject::connect (const QObject * sender, int signal_index, const QObject * receiver, int method_index, int type = 0, int * types = 0) static
Warning
This function is not part of the public interface. types is a 0-terminated vector of meta types for queued connections.
if signal_index is -1, then we effectively connect all signals from the sender to the receiver's slot
Definition at line 3194 of file qobject.cpp.
Referenced by QScript::QObjectConnectionManager::addSignalHandler(), QDeclarativePropertyPrivate::connect(), QDeclarativeVMEMetaObject::connectAlias(), QDBusAdaptorConnector::connectAllSignals(), QDeclarativePixmap::connectDownloadProgress(), QDeclarativePixmap::connectFinished(), QDeclarativeRectanglePrivate::getPen(), QDeclarativeBorderImagePrivate::getScaleGrid(), QDeclarativeFlickablePrivate::init(), QDeclarativePathViewPrivate::init(), QAxServerBase::internalActivate(), QAxServerBase::internalConnect(), QDeclarativeBorderImage::load(), menuItemEntry(), QDeclarativePixmapReader::networkRequestDone(), QDeclarativePixmapReader::processJob(), QSignalSpy::QSignalSpy(), QStateMachinePrivate::registerSignalTransition(), QTextControlPrivate::setContent(), and QDeclarativeRectangle::setGradient().
 {
     signal_index = methodIndexToSignalIndex(sender->metaObject(), signal_index);
     return QMetaObjectPrivate::connect(sender, signal_index,
                                        receiver, method_index,
                                        0, //FIXME, we could speed this connection up by computing the relative index
                                        type, types);
 }
connectSlotsByName()
void QMetaObject::connectSlotsByName (QObject * object) static
Searches recursively for all child objects of the given object, and connects matching signals from them to slots of object that follow the following form:
void on_<object name>_<signal name>(<signal parameters>);
Let's assume our object has a child object of type QPushButton with the object name button1. The slot to catch the button's clicked() signal would be:
void on_button1_clicked();
See also
QObject::setObjectName()
Definition at line 3406 of file qobject.cpp.
 {
     if (!o)
         return;
     const QMetaObject *mo = o->metaObject();
     Q_ASSERT(mo);
     const QObjectList list = o->findChildren<QObject *>(QString());
     for (int i = 0; i < mo->methodCount(); ++i) {
         const char *slot = mo->method(i).signature();
         Q_ASSERT(slot);
         if (slot[0] != 'o' || slot[1] != 'n' || slot[2] != '_')
             continue;
         bool foundIt = false;
         for(int j = 0; j < list.count(); ++j) {
             const QObject *co = list.at(j);
             QByteArray objName = co->objectName().toAscii();
             int len = objName.length();
             if (!len || qstrncmp(slot + 3, objName.data(), len) || slot[len+3] != '_')
                 continue;
             int sigIndex = co->d_func()->signalIndex(slot + len + 4);
             if (sigIndex < 0) { // search for compatible signals
                 const QMetaObject *smo = co->metaObject();
                 int slotlen = qstrlen(slot + len + 4) - 1;
                 for (int k = 0; k < co->metaObject()->methodCount(); ++k) {
                     QMetaMethod method = smo->method(k);
                     if (method.methodType() != QMetaMethod::Signal)
                         continue;
                     if (!qstrncmp(method.signature(), slot + len + 4, slotlen)) {
                         int signalOffset, methodOffset;
                         computeOffsets(method.enclosingMetaObject(), &signalOffset, &methodOffset);
                         sigIndex = k + - methodOffset + signalOffset;
                         break;
                     }
                 }
             }
             if (sigIndex < 0)
                 continue;
             if (QMetaObjectPrivate::connect(co, sigIndex, o, i)) {
                 foundIt = true;
                 break;
             }
         }
         if (foundIt) {
             // we found our slot, now skip all overloads
             while (mo->method(i + 1).attributes() & QMetaMethod::Cloned)
                   ++i;
         } else if (!(mo->method(i).attributes() & QMetaMethod::Cloned)) {
             qWarning("QMetaObject::connectSlotsByName: No matching signal for %s", slot);
         }
     }
 }
constructor()
QMetaMethod QMetaObject::constructor (int index) const
Returns the meta-data for the constructor with the given index.
Since
4.5
See also
constructorCount(), newInstance()
Definition at line 814 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addMetaObject(), and QScript::metaMethod().
 {
     int i = index;
     QMetaMethod result;
     if (priv(d.data)->revision >= 2 && i >= 0 && i < priv(d.data)->constructorCount) {
         result.mobj = this;
         result.handle = priv(d.data)->constructorData + 5*i;
     }
     return result;
 }
constructorCount()
int QMetaObject::constructorCount () const
Returns the number of constructors in this class.
Since
4.5
See also
constructor(), indexOfConstructor()
Definition at line 445 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addMetaObject(), and QScript::QMetaObjectWrapperObject::execute().
 {
     if (priv(d.data)->revision < 2)
         return 0;
     return priv(d.data)->constructorCount;
 }
disconnect()
bool QMetaObject::disconnect (const QObject * sender, int signal_index, const QObject * receiver, int method_index) static
Warning
This function is not part of the public interface.
Definition at line 3276 of file qobject.cpp.
Referenced by QDeclarativeBoundSignal::disconnect(), QDBusAdaptorConnector::disconnectAllSignals(), QScript::QObjectConnectionManager::removeSignalHandler(), QTextControlPrivate::setContent(), QDeclarativeRectangle::setGradient(), QAxServerBase::UIDeactivate(), and QStateMachinePrivate::unregisterSignalTransition().
 {
     signal_index = methodIndexToSignalIndex(sender->metaObject(), signal_index);
     return QMetaObjectPrivate::disconnect(sender, signal_index,
                                           receiver, method_index);
 }
disconnectOne()
bool QMetaObject::disconnectOne (const QObject * sender, int signal_index, const QObject * receiver, int method_index) static
Warning
This function is not part of the public interface.
Disconnect a single signal connection. If QMetaObject::connect() has been called multiple times for the same sender, signal_index, receiver and method_index only one of these connections will be removed.
Definition at line 3290 of file qobject.cpp.
Referenced by QDeclarativeNotifierEndpoint::disconnect().
 {
     signal_index = methodIndexToSignalIndex(sender->metaObject(), signal_index);
     return QMetaObjectPrivate::disconnect(sender, signal_index,
                                           receiver, method_index,
                                           QMetaObjectPrivate::DisconnectOne);
 }
enumerator()
QMetaEnum QMetaObject::enumerator (int index) const
Returns the meta-data for the enumerator with the given index.
See also
enumeratorCount(), enumeratorOffset(), indexOfEnumerator()
Definition at line 850 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addMetaObject(), QScript::callQtMethod(), classIDL(), QScript::QMetaObjectWrapperObject::deleteProperty(), QAxBase::dynamicCallHelper(), QDeclarativeObjectMethodScriptClass::enumType(), QDeclarativeCompiler::evaluateEnum(), QScript::QMetaObjectWrapperObject::getOwnPropertyDescriptor(), QScript::QMetaObjectWrapperObject::getOwnPropertyNames(), QScript::QMetaObjectWrapperObject::getOwnPropertySlot(), QScript::indexOfMetaEnum(), property(), QScript::QMetaObjectWrapperObject::put(), qax_generateDocumentation(), QBBButtonEventNotifier::QBBButtonEventNotifier(), QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters(), QDeclarativeTypeNameScriptClass::queryProperty(), QDeclarativeCompiler::testQualifiedEnumAssignment(), and QmlJSDebugger::InspectorProtocol::toString().
 {
     int i = index;
     i -= enumeratorOffset();
     if (i < 0 && d.superdata)
         return d.superdata->enumerator(index);
     QMetaEnum result;
     if (i >= 0 && i < priv(d.data)->enumeratorCount) {
         result.mobj = this;
         result.handle = priv(d.data)->enumeratorData + 4*i;
     }
     return result;
 }
enumeratorCount()
int QMetaObject::enumeratorCount () const
Returns the number of enumerators in this class.
See also
enumerator(), enumeratorOffset(), indexOfEnumerator()
Definition at line 481 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addMetaObject(), classIDL(), QScript::QMetaObjectWrapperObject::deleteProperty(), QAxBase::dynamicCallHelper(), QDeclarativeObjectMethodScriptClass::enumType(), QDeclarativeCompiler::evaluateEnum(), QScript::QMetaObjectWrapperObject::getOwnPropertyDescriptor(), QScript::QMetaObjectWrapperObject::getOwnPropertyNames(), QScript::QMetaObjectWrapperObject::getOwnPropertySlot(), QScript::indexOfMetaEnum(), QScript::QMetaObjectWrapperObject::put(), qax_generateDocumentation(), QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters(), QDeclarativeTypeNameScriptClass::queryProperty(), and QDeclarativeCompiler::testQualifiedEnumAssignment().
 {
     int n = priv(d.data)->enumeratorCount;
     const QMetaObject *m = d.superdata;
     while (m) {
         n += priv(m->d.data)->enumeratorCount;
         m = m->d.superdata;
     }
     return n;
 }
enumeratorOffset()
int QMetaObject::enumeratorOffset () const
Returns the enumerator offset for this class; i.e.
the index position of this class's first enumerator.
If the class has no superclasses with enumerators, the offset is 0; otherwise the offset is the sum of all the enumerators in the class's superclasses.
See also
enumerator(), enumeratorCount(), indexOfEnumerator()
Definition at line 382 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addMetaObject(), classIDL(), enumerator(), and indexOfEnumerator().
 {
     int offset = 0;
     const QMetaObject *m = d.superdata;
     while (m) {
         offset += priv(m->d.data)->enumeratorCount;
         m = m->d.superdata;
     }
     return offset;
 }
indexOfClassInfo()
int QMetaObject::indexOfClassInfo (const char * name) const
Finds class information item name and returns its index; otherwise returns -1.
See also
classInfo(), classInfoCount(), classInfoOffset()
Definition at line 788 of file qmetaobject.cpp.
Referenced by QAccessibleObjectPrivate::actionList(), QDBusAdaptorConnector::addAdaptor(), QAxFactory::classID(), classIDL(), clone(), QClassFactory::CreateInstanceHelper(), QAxClass< T >::createObject(), QDeclarativeMetaType::defaultMethod(), QDeclarativeMetaType::defaultProperty(), QDeclarativeCompiler::deferredProperties(), QAxFactory::eventsID(), QAxFactory::exposeToSuperClass(), QClassFactory::GetLicInfo(), QAxFactory::hasStockEvents(), QAxFactory::interfaceID(), QAxServerBase::InternalQueryInterface(), QAxServerBase::Invoke(), QAxServerBase::Load(), qax_clean_type(), qax_generateDocumentation(), qax_noSuchFunction(), QClassFactory::QClassFactory(), qDBusGenerateMetaObjectXml(), qDBusInterfaceFromMetaObject(), QAxFactory::registerActiveObject(), QAxServerBase::registerActiveObject(), QAxServerBase::Save(), and QAxFactory::validateLicenseKey().
 {
     int i = -1;
     const QMetaObject *m = this;
     while (m && i < 0) {
         for (i = priv(m->d.data)->classInfoCount-1; i >= 0; --i)
             if (strcmp(name, m->d.stringdata
                        + m->d.data[priv(m->d.data)->classInfoData + 2*i]) == 0) {
                 i += m->classInfoOffset();
                 break;
             }
         m = m->d.superdata;
     }
     return i;
 }
indexOfConstructor()
int QMetaObject::indexOfConstructor (const char * constructor) const
Finds constructor and returns its index; otherwise returns -1.
Since
4.5
Note that the constructor has to be in normalized form, as returned by normalizedSignature().
See also
constructor(), constructorCount(), normalizedSignature()
Definition at line 582 of file qmetaobject.cpp.
Referenced by newInstance().
 {
     if (priv(d.data)->revision < 2)
         return -1;
     for (int i = priv(d.data)->constructorCount-1; i >= 0; --i) {
         const char *data = d.stringdata + d.data[priv(d.data)->constructorData + 5*i];
         if (data[0] == constructor[0] && strcmp(constructor + 1, data + 1) == 0) {
             return i;
         }
     }
     return -1;
 }
indexOfEnumerator()
int QMetaObject::indexOfEnumerator (const char * name) const
Finds enumerator name and returns its index; otherwise returns -1.
See also
enumerator(), enumeratorCount(), enumeratorOffset()
Definition at line 734 of file qmetaobject.cpp.
Referenced by QAxBase::dynamicCallHelper(), QAxBase::internalInvoke(), QAxServerBase::Invoke(), property(), QBBButtonEventNotifier::QBBButtonEventNotifier(), and QAxServerBase::qt_metacall().
 {
     const QMetaObject *m = this;
     while (m) {
         const QMetaObjectPrivate *d = priv(m->d.data);
         for (int i = d->enumeratorCount - 1; i >= 0; --i) {
             const char *prop = m->d.stringdata + m->d.data[d->enumeratorData + 4*i];
             if (name[0] == prop[0] && strcmp(name + 1, prop + 1) == 0) {
                 i += m->enumeratorOffset();
                 return i;
             }
         }
         m = m->d.superdata;
     }
     return -1;
 }
indexOfMethod()
int QMetaObject::indexOfMethod (const char * method) const
Finds method and returns its index; otherwise returns -1.
Note that the method has to be in normalized form, as returned by normalizedSignature().
See also
method(), methodCount(), methodOffset(), normalizedSignature()
Definition at line 603 of file qmetaobject.cpp.
Referenced by QDeclarativeMetaType::defaultMethod(), QObject::disconnect(), QDBusConnectionPrivate::findSlot(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertySlot(), QNetworkReply::ignoreSslErrors(), QMetaObjectPrivate::indexOfSignalRelative(), invokeMethod(), QTest::invokeMethod(), QStyle::layoutSpacing(), QScript::QObjectDelegate::put(), QDeclarativeExpression::QDeclarativeExpression(), QDeclarativeWatchProxy::QDeclarativeWatchProxy(), QSignalSpy::QSignalSpy(), QTest::qtest_qParseArgs(), QNetworkReply::setSslConfiguration(), and QNetworkReply::sslConfiguration().
 {
     const QMetaObject *m = this;
     int i = indexOfMethodRelative<0>(&m, method, false);
     if (i < 0) {
         m = this;
         i = indexOfMethodRelative<0>(&m, method, true);
     }
     if (i >= 0)
         i += m->methodOffset();
     return i;
 }
indexOfProperty()
int QMetaObject::indexOfProperty (const char * name) const
Finds property name and returns its index; otherwise returns -1.
See also
property(), propertyCount(), propertyOffset()
Definition at line 757 of file qmetaobject.cpp.
Referenced by QDeclarativeCompiler::buildValueTypeProperty(), classIDL(), clone(), QDeclarativeCompiler::compileAlias(), ShaderEffectItem::connectPropertySignals(), QDeclarativePropertyCache::create(), QDeclarativeMetaType::defaultProperty(), QScript::QObjectDelegate::deleteProperty(), QAxBase::dynamicCallHelper(), QAxEventSink::findProperty(), QDeclarativePropertyPrivate::findSignalByName(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertySlot(), QDeclarativeCompiler::indexOfProperty(), QDeclarativePropertyPrivate::initProperty(), QAxServerBase::Invoke(), QScript::isEnumerableMetaProperty(), QAxServerBase::Load(), QAxEventSink::OnChanged(), QDeclarativeBindingCompilerPrivate::parseName(), QObject::property(), QScript::QObjectDelegate::put(), qDBusPropertyGet(), QDeclarativeValueTypeScriptClass::queryProperty(), QStyleSheetStyle::setProperties(), QObject::setProperty(), setupDBusInterface(), and writeProperty().
 {
     const QMetaObject *m = this;
     while (m) {
         const QMetaObjectPrivate *d = priv(m->d.data);
         for (int i = d->propertyCount-1; i >= 0; --i) {
             const char *prop = m->d.stringdata + m->d.data[d->propertyData + 3*i];
             if (name[0] == prop[0] && strcmp(name + 1, prop + 1) == 0) {
                 i += m->propertyOffset();
                 return i;
             }
         }
         m = m->d.superdata;
     }
     if (priv(this->d.data)->revision >= 3 && (priv(this->d.data)->flags & DynamicMetaObject)) {
         QAbstractDynamicMetaObject *me =
             const_cast<QAbstractDynamicMetaObject *>(static_cast<const QAbstractDynamicMetaObject *>(this));
         return me->createProperty(name, 0);
     }
     return -1;
 }
indexOfSignal()
int QMetaObject::indexOfSignal (const char * signal) const
Finds signal and returns its index; otherwise returns -1.
This is the same as indexOfMethod(), except that it will return -1 if the method exists but isn't a signal.
Note that the signal has to be in normalized form, as returned by normalizedSignature().
See also
indexOfMethod(), normalizedSignature(), method(), methodCount(), methodOffset()
Definition at line 627 of file qmetaobject.cpp.
Referenced by QAxServerBase::ActiveXProc(), QState::addTransition(), checkHRESULT(), QObject::disconnect(), QDeclarativeRectanglePrivate::getPen(), QDeclarativeBorderImagePrivate::getScaleGrid(), QDeclarativeFlickablePrivate::init(), QDeclarativePathViewPrivate::init(), QAxServerBase::internalActivate(), QAxEventSink::Invoke(), QDeclarativeKeysAttached::keyPressed(), QDeclarativeBorderImage::load(), menuItemEntry(), QAxEventSink::OnChanged(), QDeclarativePixmapReply::QDeclarativePixmapReply(), QtWndProc(), QStateMachinePrivate::registerSignalTransition(), QDeclarativePixmapReader::run(), QScriptEnginePrivate::scriptConnect(), QScriptEnginePrivate::scriptDisconnect(), QDBusAbstractAdaptor::setAutoRelaySignals(), QTextControlPrivate::setContent(), QDeclarativeRectangle::setGradient(), and QAxServerBase::UIDeactivate().
 {
     const QMetaObject *m = this;
     int i = QMetaObjectPrivate::indexOfSignalRelative(&m, signal, false);
     if (i < 0) {
         m = this;
         i = QMetaObjectPrivate::indexOfSignalRelative(&m, signal, true);
     }
     if (i >= 0)
         i += m->methodOffset();
     return i;
 }
indexOfSlot()
int QMetaObject::indexOfSlot (const char * slot) const
Finds slot and returns its index; otherwise returns -1.
This is the same as indexOfMethod(), except that it will return -1 if the method exists but isn't a slot.
See also
indexOfMethod(), method(), methodCount(), methodOffset()
Definition at line 673 of file qmetaobject.cpp.
Referenced by QAxBase::dynamicCallHelper(), QDeclarativeRectanglePrivate::getPen(), QDeclarativeBorderImagePrivate::getScaleGrid(), QDeclarativeFlickablePrivate::init(), QDeclarativePathViewPrivate::init(), QAxServerBase::Invoke(), QDeclarativeBorderImage::load(), QDeclarativeImageBase::load(), qDBusUpdateDispatchStatus(), QDeclarativePixmapReader::run(), QDBusConnectionPrivate::setConnection(), QDeclarativeRectangle::setGradient(), QDeclarativeBorderImage::setGridScaledImage(), and QGraphicsView::viewportEvent().
 {
     const QMetaObject *m = this;
     int i = QMetaObjectPrivate::indexOfSlotRelative(&m, slot, false);
     if (i < 0)
         i = QMetaObjectPrivate::indexOfSlotRelative(&m, slot, true);
     if (i >= 0)
         i += m->methodOffset();
     return i;
 }
invokeMethod() [1/4]
bool QMetaObject::invokeMethod (QObject * obj, const char * member, Qt::ConnectionType type, QGenericReturnArgument ret, QGenericArgument val0 = QGenericArgument(0), QGenericArgument val1 = QGenericArgument(), QGenericArgument val2 = QGenericArgument(), QGenericArgument val3 = QGenericArgument(), QGenericArgument val4 = QGenericArgument(), QGenericArgument val5 = QGenericArgument(), QGenericArgument val6 = QGenericArgument(), QGenericArgument val7 = QGenericArgument(), QGenericArgument val8 = QGenericArgument(), QGenericArgument val9 = QGenericArgument()) static
Invokes the member (a signal or a slot name) on the object obj.
Returns true if the member could be invoked. Returns false if there is no such member or the parameters did not match.
The invocation can be either synchronous or asynchronous, depending on type:
If type is Qt::DirectConnection, the member will be invoked immediately.
If type is Qt::QueuedConnection, a QEvent will be sent and the member is invoked as soon as the application enters the main event loop.
If type is Qt::BlockingQueuedConnection, the method will be invoked in the same way as for Qt::QueuedConnection, except that the current thread will block until the event is delivered. Using this connection type to communicate between objects in the same thread will lead to deadlocks.
If type is Qt::AutoConnection, the member is invoked synchronously if obj lives in the same thread as the caller; otherwise it will invoke the member asynchronously.
The return value of the member function call is placed in ret. If the invocation is asynchronous, the return value cannot be evaluated. You can pass up to ten arguments (val0, val1, val2, val3, val4, val5, val6, val7, val8, and val9) to the member function.
QGenericArgument and QGenericReturnArgument are internal helper classes. Because signals and slots can be dynamically invoked, you must enclose the arguments using the Q_ARG() and Q_RETURN_ARG() macros. Q_ARG() takes a type name and a const reference of that type; Q_RETURN_ARG() takes a type name and a non-const reference.
You only need to pass the name of the signal or slot to this function, not the entire signature. For example, to asynchronously invoke the animateClick() slot on a QPushButton, use the following code:
QMetaObject::invokeMethod(pushButton, "animateClick",
                          Qt::QueuedConnection);
With asynchronous method invocations, the parameters must be of types that are known to Qt's meta-object system, because Qt needs to copy the arguments to store them in an event behind the scenes. If you try to use a queued connection and get the error message
QMetaObject::invokeMethod: Unable to handle unregistered datatype 'MyType'
call qRegisterMetaType() to register the data type before you call invokeMethod().
To synchronously invoke the compute(QString, int, double) slot on some arbitrary object obj retrieve its return value:
QString retVal;
QMetaObject::invokeMethod(obj, "compute", Qt::DirectConnection,
                          Q_RETURN_ARG(QString, retVal),
                          Q_ARG(QString, "sqrt"),
                          Q_ARG(int, 42),
                          Q_ARG(double, 9.7));
If the "compute" slot does not take exactly one QString, one int and one double in the specified order, the call will fail.
See also
Q_ARG(), Q_RETURN_ARG(), qRegisterMetaType(), QMetaMethod::invoke()
Definition at line 1156 of file qmetaobject.cpp.
Referenced by QNetworkReplyImplPrivate::_q_bufferOutgoingDataFinished(), QHttpNetworkConnectionChannel::_q_disconnected(), QHttpNetworkConnectionChannel::_q_error(), QNetworkReplyImplPrivate::_q_networkSessionConnected(), QGraphicsScenePrivate::_q_polishItems(), QHttpPrivate::_q_slotClosed(), QHttpPrivate::_q_slotError(), QHttpPrivate::_q_slotReadyRead(), QHttpThreadDelegate::abortRequest(), QLayout::addChildWidget(), QHttpPrivate::addRequest(), QHttpNetworkConnectionChannel::allDone(), QAudioOutputPrivate::audioDeviceError(), QAudioInputPrivate::audioDeviceError(), QAudioInputPrivate::audioDeviceFull(), QAudioOutputPrivate::audioDeviceIdle(), QHttpNetworkConnectionChannel::closeAndResendCurrentRequest(), QHttpPrivate::closeConn(), QDeclarativeFolderListModel::componentComplete(), QAbstractSocket::connectToHost(), QGraphicsProxyWidget::createProxyForChildWidget(), QAbstractSocket::disconnectFromHost(), QMacStyle::drawControl(), QHttpSocketEngine::emitConnectionNotification(), QSocks5SocketEnginePrivate::emitConnectionNotification(), QHttpSocketEngine::emitReadNotification(), QSocks5SocketEnginePrivate::emitReadNotification(), QHttpNetworkConnectionPrivate::emitReplyError(), QHttpSocketEngine::emitWriteNotification(), QSocks5SocketEnginePrivate::emitWriteNotification(), QNetworkConfigurationManagerPrivate::enablePolling(), QAbstractItemModel::endResetModel(), QSocketNotifier::event(), QWinEventNotifier::event(), QWorkspace::event(), QObject::event(), QStyledItemDelegate::eventFilter(), QItemDelegate::eventFilter(), QPSQLDriverPrivate::exec(), QAudioInputPrivate::feedback(), QHttpThreadDelegate::finishedSlot(), QHttpThreadDelegate::finishedWithErrorSlot(), QAudioOutputPrivate::freeBlocks(), gtkStyleSetCallback(), QHttpNetworkConnectionChannel::handleStatus(), QHttpNetworkConnectionChannel::handleUnexpectedEOF(), QHttpPrivate::init(), QAudioOutputPrivate::inputReady(), QGraphicsSceneBspTreeIndexPrivate::invalidateSortCache(), QSqlDriver::isIdentifierEscaped(), jump(), QWaylandClipboard::keyboardFocus(), QNetworkReplyImplPrivate::migrateBackend(), QNetworkAccessFileBackend::open(), QDesktopServices::openUrl(), QNetworkConfigurationManagerPrivate::performAsyncConfigurationUpdate(), QNetworkConfigurationManagerPrivate::pollEngines(), QNetworkAccessHttpBackend::postRequest(), QStateMachinePrivate::processEvents(), QBBIntegration::QBBIntegration(), QBBSystemLocaleData::QBBSystemLocaleData(), QDBusAbstractAdaptor::QDBusAbstractAdaptor(), QDBusPendingCallWatcher::QDBusPendingCallWatcher(), QDisabledNetworkReply::QDisabledNetworkReply(), qEventCallback(), QTest::qInvokeTestMethodDataEntry(), QPatternist::QIODeviceDelegate::QIODeviceDelegate(), QNetworkReplyDataImpl::QNetworkReplyDataImpl(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), qNotificationCallback(), QHttpThreadDelegate::readBufferFreed(), QSslSocket::readData(), QHttpNetworkConnectionPrivate::readMoreLater(), QDeclarativeDebugServer::receiveMessage(), QTransportAuth::registerPolicyReceiver(), QHttpNetworkConnectionPrivate::removeReply(), QLayoutPrivate::reparentChildWidgets(), QNetworkManagerEngine::requestUpdate(), QHttpNetworkConnectionChannel::requeueCurrentlyPipelinedRequests(), QHttpNetworkConnectionPrivate::requeueRequest(), QProgressDialog::reset(), QAbstractItemModel::reset(), QHttpNetworkConnectionPrivate::resumeConnection(), QAccessibleTextEdit::scrollToSubstring(), QNetworkAccessHttpBackend::sendCacheContents(), QHttpNetworkConnectionChannel::sendRequest(), QDBusConnectionPrivate::setConnection(), QGraphicsItem::setCursor(), QDirModel::setData(), QDeclarativeFolderListModel::setFolder(), QDBusConnectionPrivate::setPeer(), QGraphicsScenePrivate::setScenePosItemEnabled(), QNetworkReplyImplPrivate::setup(), QBBClipboard::MimeData::setUserMimeData(), QAbstractScrollArea::setViewport(), QTableView::setWordWrap(), QHttpSocketEngine::setWriteNotificationEnabled(), QStyle::standardIcon(), QStateMachine::start(), QHttpThreadDelegate::startRequestSynchronously(), QSqlDriver::stripDelimiters(), QSqlDriver::subscribedToNotifications(), QSqlDriver::subscribeToNotification(), SxeRegistryLocker::SxeRegistryLocker(), QHttpThreadDelegate::synchronousFinishedSlot(), QHttpThreadDelegate::synchronousFinishedWithErrorSlot(), QSingleShotTimer::timerEvent(), QStatusBarPrivate::tryToShowSizeGrip(), QTransportAuth::unregisterPolicyReceiver(), QGraphicsItem::unsetCursor(), QSqlDriver::unsubscribeFromNotification(), QDeclarativeTimer::update(), QGraphicsScene::update(), QNetworkConfigurationManagerPrivate::updateConfigurations(), QTableView::updateGeometries(), QTreeView::updateGeometries(), QGraphicsWidget::updateGeometry(), QAbstractItemView::viewportEvent(), QBuffer::writeData(), QSslSocket::writeData(), and SxeRegistryLocker::~SxeRegistryLocker().
 {
     if (!obj)
         return false;
     QVarLengthArray<char, 512> sig;
     int len = qstrlen(member);
     if (len <= 0)
         return false;
     sig.append(member, len);
     sig.append('(');
     const char *typeNames[] = {ret.name(), val0.name(), val1.name(), val2.name(), val3.name(),
                                val4.name(), val5.name(), val6.name(), val7.name(), val8.name(),
                                val9.name()};
     int paramCount;
     for (paramCount = 1; paramCount < MaximumParamCount; ++paramCount) {
         len = qstrlen(typeNames[paramCount]);
         if (len <= 0)
             break;
         sig.append(typeNames[paramCount], len);
         sig.append(',');
     }
     if (paramCount == 1)
         sig.append(')'); // no parameters
     else
         sig[sig.size() - 1] = ')';
     sig.append('\0');
     int idx = obj->metaObject()->indexOfMethod(sig.constData());
     if (idx < 0) {
         QByteArray norm = QMetaObject::normalizedSignature(sig.constData());
         idx = obj->metaObject()->indexOfMethod(norm.constData());
     }
     if (idx < 0 || idx >= obj->metaObject()->methodCount()) {
         qWarning("QMetaObject::invokeMethod: No such method %s::%s",
                  obj->metaObject()->className(), sig.constData());
         return false;
     }
     QMetaMethod method = obj->metaObject()->method(idx);
     return method.invoke(obj, type, ret,
                          val0, val1, val2, val3, val4, val5, val6, val7, val8, val9);
 }
invokeMethod() [2/4]
static bool QMetaObject::invokeMethod (QObject * obj, const char * member, QGenericReturnArgument ret, QGenericArgument val0 = QGenericArgument(0), QGenericArgument val1 = QGenericArgument(), QGenericArgument val2 = QGenericArgument(), QGenericArgument val3 = QGenericArgument(), QGenericArgument val4 = QGenericArgument(), QGenericArgument val5 = QGenericArgument(), QGenericArgument val6 = QGenericArgument(), QGenericArgument val7 = QGenericArgument(), QGenericArgument val8 = QGenericArgument(), QGenericArgument val9 = QGenericArgument()) inline static
Definition at line 387 of file qobjectdefs.h.
     {
         return invokeMethod(obj, member, Qt::AutoConnection, ret, val0, val1, val2, val3,
                 val4, val5, val6, val7, val8, val9);
     }
invokeMethod() [3/4]
static bool QMetaObject::invokeMethod (QObject * obj, const char * member, Qt::ConnectionType type, QGenericArgument val0 = QGenericArgument(0), QGenericArgument val1 = QGenericArgument(), QGenericArgument val2 = QGenericArgument(), QGenericArgument val3 = QGenericArgument(), QGenericArgument val4 = QGenericArgument(), QGenericArgument val5 = QGenericArgument(), QGenericArgument val6 = QGenericArgument(), QGenericArgument val7 = QGenericArgument(), QGenericArgument val8 = QGenericArgument(), QGenericArgument val9 = QGenericArgument()) inline static
Definition at line 404 of file qobjectdefs.h.
     {
         return invokeMethod(obj, member, type, QGenericReturnArgument(), val0, val1, val2,
                                  val3, val4, val5, val6, val7, val8, val9);
     }
invokeMethod() [4/4]
static bool QMetaObject::invokeMethod (QObject * obj, const char * member, QGenericArgument val0 = QGenericArgument(0), QGenericArgument val1 = QGenericArgument(), QGenericArgument val2 = QGenericArgument(), QGenericArgument val3 = QGenericArgument(), QGenericArgument val4 = QGenericArgument(), QGenericArgument val5 = QGenericArgument(), QGenericArgument val6 = QGenericArgument(), QGenericArgument val7 = QGenericArgument(), QGenericArgument val8 = QGenericArgument(), QGenericArgument val9 = QGenericArgument()) inline static
Definition at line 421 of file qobjectdefs.h.
     {
         return invokeMethod(obj, member, Qt::AutoConnection, QGenericReturnArgument(), val0,
                 val1, val2, val3, val4, val5, val6, val7, val8, val9);
     }
metacall()
int QMetaObject::metacall (QObject * object, Call cl, int idx, void ** argv) static
Warning
This function is not part of the public interface.
Definition at line 249 of file qmetaobject.cpp.
Referenced by QDeclarativeObjectMethodScriptClass::callMethod(), QScript::callQtMethod(), QDeclarativeComponentPrivate::complete(), QDeclarativeNotifier::emitNotify(), QDeclarativeCompiledBindingsPrivate::findproperty(), QDeclarativePropertyPrivate::initProperty(), QMetaMethod::invoke(), QMetaProperty::isDesignable(), QMetaProperty::isScriptable(), QMetaProperty::isStored(), QMetaProperty::isUser(), QDeclarativeVMEMetaObject::metaCall(), QDeclarativeListScriptClass::newList(), QMetaCallEvent::placeMetaCall(), QDeclarativeObjectScriptClass::property(), QDeclarativeListReference::QDeclarativeListReference(), QDeclarativePointFValueType::read(), QDeclarativePointValueType::read(), QDeclarativeSizeFValueType::read(), QDeclarativeSizeValueType::read(), QDeclarativeRectFValueType::read(), QMetaProperty::read(), QDeclarativeRectValueType::read(), QDeclarativeVector2DValueType::read(), QDeclarativeVector3DValueType::read(), QDeclarativeVector4DValueType::read(), QDeclarativeQuaternionValueType::read(), QDeclarativeMatrix4x4ValueType::read(), QDeclarativeEasingValueType::read(), QDeclarativeFontValueType::read(), QDeclarativePropertyPrivate::readValueProperty(), QDeclarativeProperty::reset(), QMetaProperty::reset(), QDeclarativeCompiledBindingsPrivate::run(), QDeclarativeObjectScriptClass::setProperty(), QDeclarativeVisualDataModel::stringValue(), QDeclarativeBinding::update(), QPropertyAnimationPrivate::updateProperty(), QDeclarativePropertyPrivate::write(), QDeclarativePointFValueType::write(), QDeclarativePointValueType::write(), QDeclarativeSizeFValueType::write(), QDeclarativeSizeValueType::write(), QDeclarativeRectFValueType::write(), QMetaProperty::write(), QDeclarativeRectValueType::write(), QDeclarativeVector2DValueType::write(), QDeclarativeVector3DValueType::write(), QDeclarativeVector4DValueType::write(), QDeclarativeQuaternionValueType::write(), QDeclarativeMatrix4x4ValueType::write(), QDeclarativeEasingValueType::write(), QDeclarativeFontValueType::write(), and QDeclarativePropertyPrivate::writeEnumProperty().
 {
     if (QMetaObject *mo = object->d_ptr->metaObject)
         return static_cast<QAbstractDynamicMetaObject*>(mo)->metaCall(cl, idx, argv);
     else
         return object->qt_metacall(cl, idx, argv);
 }
method()
QMetaMethod QMetaObject::method (int index) const
Returns the meta-data for the method with the given index.
See also
methodCount(), methodOffset(), indexOfMethod()
Definition at line 830 of file qmetaobject.cpp.
Referenced by QAccessibleObjectPrivate::actionList(), QGraphicsScene::addItem(), QMetaObjectBuilder::addMetaObject(), QScript::QObjectConnectionManager::addSignalHandler(), QDeclarativePropertyCache::append(), QDeclarativeEngineDebugService::buildObjectDump(), QDeclarativeObjectMethodScriptClass::callOverloaded(), QDBusAbstractInterface::callWithArgumentList(), checkConnectArgs(), classIDL(), QDeclarativeObjectMethodScriptClass::connect(), QDeclarativePropertyPrivate::connect(), QObject::connect(), connectSlotsByName(), QDeclarativePropertyCache::create(), QDeclarativeMetaType::defaultMethod(), QDeclarativeNotifierEndpoint::disconnect(), QDeclarativeObjectMethodScriptClass::disconnect(), QObject::dumpObjectInfo(), QAxBase::dynamicCallHelper(), QScript::QObjectConnectionManager::execute(), QDeclarativePropertyPrivate::findSignalByName(), QDBusConnectionPrivate::findSlot(), findSlot(), QScript::functionConnect(), QScript::functionDisconnect(), QAxScript::functions(), generateInterfaceXml(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertyNames(), QScript::QObjectDelegate::getOwnPropertySlot(), QStateMachinePrivate::handleTransitionSignal(), indexOfMethod(), QDeclarativeTypePrivate::init(), QAxServerBase::internalConnect(), QAxBase::internalInvoke(), QAxServerBase::Invoke(), QAxEventSink::Invoke(), invokeMethod(), QTest::invokeMethod(), QDeclarativeKeysAttached::keyPressed(), QDBusInterfacePrivate::metacall(), QDeclarativeProxyMetaObject::metaCall(), QScript::metaMethod(), QDeclarativeProperty::method(), QScript::QtFunction::mostGeneralMethod(), QDeclarativePropertyCache::Data::name(), QMetaProperty::notifySignal(), QScript::QtFunction::overloadedIndexes(), QScript::QObjectDelegate::put(), qax_generateDocumentation(), qax_noSuchFunction(), qDBusUpdateDispatchStatus(), QTest::qInvokeTestMethods(), QTest::qPrintDataTags(), QTest::qPrintTestSlots(), QScriptContextInfoPrivate::QScriptContextInfoPrivate(), QTest::qSignalDumperCallback(), QTest::qSignalDumperCallbackSlot(), QSignalSpy::QSignalSpy(), QAxBase::qt_metacall(), QAxServerBase::qt_metacall(), queued_activate(), QStateMachinePrivate::registerSignalTransition(), QDeclarativeObjectMethodScriptClass::relatedMethod(), QDBusAdaptorConnector::relay(), QDBusConnectionPrivate::relaySignal(), QScript::QObjectConnectionManager::removeSignalHandler(), QDBusAbstractAdaptor::setAutoRelaySignals(), and setupDBusInterface().
 {
     int i = index;
     i -= methodOffset();
     if (i < 0 && d.superdata)
         return d.superdata->method(index);
     QMetaMethod result;
     if (i >= 0 && i < priv(d.data)->methodCount) {
         result.mobj = this;
         result.handle = priv(d.data)->methodData + 5*i;
     }
     return result;
 }
methodCount()
int QMetaObject::methodCount () const
Returns the number of methods known to the meta-object system in this class, including the number of properties provided by each base class.
These include signals and slots as well as member functions declared with the Q_INVOKABLE macro.
Use code like the following to obtain a QStringList containing the methods specific to a given class:
const QMetaObject* metaObject = obj->metaObject();
QStringList methods;
for(int i = metaObject->methodOffset(); i < metaObject->methodCount(); ++i)
    methods << QString::fromLatin1(metaObject->method(i).signature());
See also
method(), methodOffset(), indexOfMethod()
Definition at line 465 of file qmetaobject.cpp.
Referenced by QAccessibleObjectPrivate::actionList(), QMetaObjectBuilder::addMetaObject(), QDeclarativePropertyCache::append(), QDBusAbstractInterface::callWithArgumentList(), classIDL(), connectSlotsByName(), QDeclarativePropertyCache::create(), QDeclarativePropertyPrivate::findSignalByName(), findSlot(), QAxScript::functions(), generateInterfaceXml(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertyNames(), QScript::QObjectDelegate::getOwnPropertySlot(), QDeclarativeBoundSignal::init(), QDeclarativeTypePrivate::init(), QAxServerBase::internalConnect(), QAxBase::internalInvoke(), QAxServerBase::Invoke(), invokeMethod(), QDeclarativeProxyMetaObject::metaCall(), QDeclarativeVMEMetaObject::metaCall(), qax_generateDocumentation(), qax_noSuchFunction(), qDBusGenerateMetaObjectXml(), QDeclarativeCompiledBindings::QDeclarativeCompiledBindings(), QTest::qInvokeTestMethods(), QTest::qPrintDataTags(), QTest::qPrintTestSlots(), QSignalSpy::QSignalSpy(), QAxBase::qt_metacall(), QDeclarativeObjectMethodScriptClass::relatedMethod(), QDBusAbstractAdaptor::setAutoRelaySignals(), QDeclarativeContext::setContextProperty(), setupDBusInterface(), and QDeclarativePropertyCache::update().
 {
     int n = priv(d.data)->methodCount;
     const QMetaObject *m = d.superdata;
     while (m) {
         n += priv(m->d.data)->methodCount;
         m = m->d.superdata;
     }
     return n;
 }
methodOffset()
int QMetaObject::methodOffset () const
Returns the method offset for this class; i.e.
the index position of this class's first member function.
The offset is the sum of all the methods in the class's superclasses (which is always positive since QObject has the deleteLater() slot and a destroyed() signal).
See also
method(), methodCount(), indexOfMethod()
Definition at line 360 of file qmetaobject.cpp.
Referenced by activate(), QMetaObjectBuilder::addMetaObject(), QScript::QObjectConnectionManager::addSignalHandler(), QDeclarativePropertyCache::append(), QScript::callQtMethod(), classIDL(), QMetaObjectPrivate::connect(), QObject::connect(), QDeclarativeVMEMetaObject::connectAlias(), QDeclarativeVMEMetaObject::connectAliasSignal(), flush_vme_signal(), QAxScript::functions(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertyNames(), QScript::QObjectDelegate::getOwnPropertySlot(), indexOfMethod(), indexOfSignal(), indexOfSlot(), QAxBase::internalInvoke(), QDeclarativeVMEMetaObject::listChanged(), QDBusInterfacePrivate::metacall(), QDeclarativeProxyMetaObject::metaCall(), QDeclarativeVMEMetaObject::metaCall(), method(), methodIndexToSignalIndex(), QMetaProperty::notifySignalIndex(), QScript::QObjectDelegate::put(), qax_generateDocumentation(), QDeclarativeVMEMetaObject::QDeclarativeVMEMetaObject(), QAxBase::qt_metacall(), QStateMachinePrivate::registerSignalTransition(), QScript::QObjectConnectionManager::removeSignalHandler(), QDeclarativeVMEMetaObject::setVmeMethod(), QStateMachinePrivate::unregisterSignalTransition(), QDeclarativeVMEMetaObject::vmeMethod(), QDeclarativeVMEMetaObject::vmeMethodLineNumber(), and QDeclarativeVMEMetaObject::writeVarProperty().
 {
     int offset = 0;
     const QMetaObject *m = d.superdata;
     while (m) {
         offset += priv(m->d.data)->methodCount;
         m = m->d.superdata;
     }
     return offset;
 }
newInstance()
QObject * QMetaObject::newInstance (QGenericArgument val0 = QGenericArgument(0), QGenericArgument val1 = QGenericArgument(), QGenericArgument val2 = QGenericArgument(), QGenericArgument val3 = QGenericArgument(), QGenericArgument val4 = QGenericArgument(), QGenericArgument val5 = QGenericArgument(), QGenericArgument val6 = QGenericArgument(), QGenericArgument val7 = QGenericArgument(), QGenericArgument val8 = QGenericArgument(), QGenericArgument val9 = QGenericArgument()) const
Constructs a new instance of this class.
Since
4.5
You can pass up to ten arguments (val0, val1, val2, val3, val4, val5, val6, val7, val8, and val9) to the constructor. Returns the new object, or 0 if no suitable constructor is available.
Note that only constructors that are declared with the Q_INVOKABLE modifier are made available through the meta-object system.
See also
Q_ARG(), constructor()
Definition at line 169 of file qmetaobject.cpp.
 {
     QByteArray constructorName = className();
     {
         int idx = constructorName.lastIndexOf(':');
         if (idx != -1)
             constructorName.remove(0, idx+1); // remove qualified part
     }
     QVarLengthArray<char, 512> sig;
     sig.append(constructorName.constData(), constructorName.length());
     sig.append('(');
     enum { MaximumParamCount = 10 };
     const char *typeNames[] = {val0.name(), val1.name(), val2.name(), val3.name(), val4.name(),
                                val5.name(), val6.name(), val7.name(), val8.name(), val9.name()};
     int paramCount;
     for (paramCount = 0; paramCount < MaximumParamCount; ++paramCount) {
         int len = qstrlen(typeNames[paramCount]);
         if (len <= 0)
             break;
         sig.append(typeNames[paramCount], len);
         sig.append(',');
     }
     if (paramCount == 0)
         sig.append(')'); // no parameters
     else
         sig[sig.size() - 1] = ')';
     sig.append('\0');
     int idx = indexOfConstructor(sig.constData());
     if (idx < 0) {
         QByteArray norm = QMetaObject::normalizedSignature(sig.constData());
         idx = indexOfConstructor(norm.constData());
     }
     if (idx < 0)
         return 0;
     QVariant ret(QMetaType::QObjectStar, (void*)0);
     void *param[] = {ret.data(), val0.data(), val1.data(), val2.data(), val3.data(), val4.data(),
                      val5.data(), val6.data(), val7.data(), val8.data(), val9.data()};
     if (static_metacall(CreateInstance, idx, param) >= 0)
         return 0;
     return *reinterpret_cast<QObject**>(param[0]);
 }
normalizedSignature()
QByteArray QMetaObject::normalizedSignature (const char * method) static
Normalizes the signature of the given method.
Qt uses normalized signatures to decide whether two given signals and slots are compatible. Normalization reduces whitespace to a minimum, moves 'const' to the front where appropriate, removes 'const' from value types and replaces const references with values.
See also
checkConnectArgs(), normalizedType()
Definition at line 1058 of file qmetaobject.cpp.
Referenced by QAccessibleObjectPrivate::actionList(), QAccessibleWidget::addControllingSignal(), QState::addTransition(), QObject::connect(), QObject::disconnect(), QAxBase::dynamicCallHelper(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertySlot(), QMetaObjectBuilder::indexOfConstructor(), QMetaObjectBuilder::indexOfMethod(), indexOfMethodRelative(), QMetaObjectBuilder::indexOfSignal(), QMetaObjectBuilder::indexOfSlot(), QObject::inherits(), QMetaMethod::invoke(), invokeMethod(), MetaObjectGenerator::metaObject(), newInstance(), QDBusMetaObjectGenerator::parseMethods(), QDBusMetaObjectGenerator::parseSignals(), QDBusConnectionPrivate::prepareHook(), QScript::QObjectDelegate::put(), QSignalSpy::QSignalSpy(), QObject::receivers(), QStateMachinePrivate::registerSignalTransition(), QScriptEnginePrivate::scriptConnect(), QScriptEnginePrivate::scriptDisconnect(), QDBusAbstractAdaptor::setAutoRelaySignals(), QDBusPendingCallPrivate::setReplyCallback(), and signalForMember().
 {
     QByteArray result;
     if (!method || !*method)
         return result;
     int len = int(strlen(method));
     QVarLengthArray<char> stackbuf(len + 1);
     char *d = stackbuf.data();
     qRemoveWhitespace(method, d);
     result.reserve(len);
     int argdepth = 0;
     int templdepth = 0;
     while (*d) {
         if (argdepth == 1) {
             d = qNormalizeType(d, templdepth, result);
             if (!*d) //most likely an invalid signature.
                 break;
         }
         if (*d == '(')
             ++argdepth;
         if (*d == ')')
             --argdepth;
         result += *d++;
     }
     return result;
 }
normalizedType()
QByteArray QMetaObject::normalizedType (const char * type) static
Normalizes a type.
Since
4.2
See QMetaObject::normalizedSignature() for a description on how Qt normalizes.
Example:
QByteArray normType = QMetaObject::normalizedType(" int    const  *");
// normType is now "const int*"
See also
normalizedSignature()
Definition at line 1032 of file qmetaobject.cpp.
Referenced by QMetaType::registerType(), QMetaType::registerTypedef(), QMetaMethodBuilder::setReturnType(), QMetaType::type(), and QMetaType::unregisterType().
 {
     QByteArray result;
     if (!type || !*type)
         return result;
     QVarLengthArray<char> stackbuf(qstrlen(type) + 1);
     qRemoveWhitespace(type, stackbuf.data());
     int templdepth = 0;
     qNormalizeType(stackbuf.data(), templdepth, result);
     return result;
 }
property()
QMetaProperty QMetaObject::property (int index) const
Returns the meta-data for the property with the given index.
If no such property exists, a null QMetaProperty is returned.
See also
propertyCount(), propertyOffset(), indexOfProperty()
Definition at line 871 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addMetaObject(), MetaObjectGenerator::addSlot(), QDeclarativeWatcher::addWatch(), QDeclarativePropertyCache::append(), QDeclarativeCompiler::buildBinding(), QDeclarativeCompiler::buildGroupedProperty(), QDeclarativeEngineDebugService::buildObjectDump(), QDeclarativeCompiler::buildProperty(), QDeclarativeCompiler::buildPropertyLiteralAssignment(), QDeclarativeCompiler::buildPropertyObjectAssignment(), QDeclarativeCompiler::buildPropertyOnAssignment(), QDeclarativeCompiler::buildValueTypeProperty(), classIDL(), clone(), QDeclarativeCompiler::compileAlias(), QDeclarativeVMEMetaObject::connectAlias(), QDeclarativeProperty::connectNotifySignal(), ShaderEffectItem::connectPropertySignals(), QDeclarativeContext::contextProperty(), QDeclarativePropertyCache::create(), QDeclarativeMetaType::defaultProperty(), QScript::QObjectDelegate::deleteProperty(), QDeclarativeCompiler::doesPropertyExist(), QAxBase::dynamicCallHelper(), QScript::QtPropertyFunction::execute(), QDeclarativeBindingCompilerPrivate::fetch(), QDeclarativeCompiledBindingsPrivate::findproperty(), QAxEventSink::findProperty(), QDeclarativePropertyPrivate::findSignalByName(), generateInterfaceXml(), QDeclarativeCompiler::genPropertyAssignment(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertyNames(), QScript::QObjectDelegate::getOwnPropertySlot(), QDeclarativeProperty::hasNotifySignal(), QDeclarativeTypePrivate::init(), QDeclarativeVisualDataModelDataMetaObject::initialValue(), QDeclarativePropertyPrivate::initProperty(), QAxBase::internalProperty(), QAxServerBase::Invoke(), QDeclarativeProperty::isDesignable(), QAxServerBase::isPropertyExposed(), QAxServerBase::Load(), QDeclarativeVMEMetaObject::metaCall(), QDeclarativeProperty::name(), QDeclarativePropertyCache::Data::name(), QAxEventSink::OnChanged(), QDeclarativeBindingCompilerPrivate::parseName(), QDeclarativeValueTypeScriptClass::property(), QDeclarativeProperty::property(), QDeclarativeObjectScriptClass::property(), QObject::property(), QAxBase::propertyBag(), QDeclarativeEngineDebugService::propertyData(), QDeclarativeObjectScriptClass::propertyNames(), QDeclarativeProperty::propertyTypeName(), QScript::QObjectDelegate::put(), qax_generateDocumentation(), qax_noSuchFunction(), qDBusPropertyGet(), QDBusAbstractInterfaceBase::qt_metacall(), QAxBase::qt_metacall(), QDeclarativeValueTypeScriptClass::queryProperty(), readAllProperties(), QDeclarativePropertyPrivate::readValueProperty(), QDeclarativeCompiledBindingsPrivate::run(), QAxServerBase::Save(), QDeclarativePropertyPrivate::saveProperty(), QDeclarativePropertyPrivate::saveValueType(), QStyleSheetStyle::setProperties(), QDeclarativeValueTypeScriptClass::setProperty(), QObject::setProperty(), QAxBase::setPropertyBag(), QDeclarativeQtScriptExpression::updateGuards(), QPropertyAnimationPrivate::updateMetaProperty(), userProperty(), and writeProperty().
 {
     int i = index;
     i -= propertyOffset();
     if (i < 0 && d.superdata)
         return d.superdata->property(index);
     QMetaProperty result;
     if (i >= 0 && i < priv(d.data)->propertyCount) {
         int handle = priv(d.data)->propertyData + 3*i;
         int flags = d.data[handle + 2];
         const char *type = d.stringdata + d.data[handle + 1];
         result.mobj = this;
         result.handle = handle;
         result.idx = i;
         if (flags & EnumOrFlag) {
             result.menum = enumerator(indexOfEnumerator(type));
             if (!result.menum.isValid()) {
                 QByteArray enum_name = type;
                 QByteArray scope_name = d.stringdata;
                 int s = enum_name.lastIndexOf("::");
                 if (s > 0) {
                     scope_name = enum_name.left(s);
                     enum_name = enum_name.mid(s + 2);
                 }
                 const QMetaObject *scope = 0;
                 if (scope_name == "Qt")
                     scope = &QObject::staticQtMetaObject;
                 else
                     scope = QMetaObject_findMetaObject(this, scope_name);
                 if (scope)
                     result.menum = scope->enumerator(scope->indexOfEnumerator(enum_name));
             }
         }
     }
     return result;
 }
propertyCount()
int QMetaObject::propertyCount () const
Returns the number of properties in this class, including the number of properties provided by each base class.
Use code like the following to obtain a QStringList containing the properties specific to a given class:
const QMetaObject* metaObject = obj->metaObject();
QStringList properties;
for(int i = metaObject->propertyOffset(); i < metaObject->propertyCount(); ++i)
    properties << QString::fromLatin1(metaObject->property(i).name());
See also
property(), propertyOffset(), indexOfProperty()
Definition at line 503 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addMetaObject(), QDeclarativePropertyCache::append(), classIDL(), clone(), generateInterfaceXml(), QScript::QObjectDelegate::getOwnPropertyNames(), QAxServerBase::GetSizeMax(), QDeclarativeTypePrivate::init(), QAxBase::internalProperty(), QAxServerBase::Load(), QDeclarativeVMEMetaObject::metaCall(), QAxBase::propertyBag(), QDeclarativeObjectScriptClass::propertyNames(), qax_generateDocumentation(), qax_noSuchFunction(), qDBusGenerateMetaObjectXml(), QAxBase::qt_metacall(), readAllProperties(), QDeclarativeVMEMetaObject::registerInterceptor(), QAxServerBase::Save(), QDeclarativeData::setBindingBit(), QAxBase::setPropertyBag(), QDeclarativePropertyCache::update(), userProperty(), and QDeclarativeValueTypeFactory::valueType().
 {
     int n = priv(d.data)->propertyCount;
     const QMetaObject *m = d.superdata;
     while (m) {
         n += priv(m->d.data)->propertyCount;
         m = m->d.superdata;
     }
     return n;
 }
propertyOffset()
int QMetaObject::propertyOffset () const
Returns the property offset for this class; i.e.
the index position of this class's first property.
The offset is the sum of all the properties in the class's superclasses (which is always positive since QObject has the name() property).
See also
property(), propertyCount(), indexOfProperty()
Definition at line 403 of file qmetaobject.cpp.
Referenced by QDeclarativeFastProperties::accessorIndexForProperty(), QDeclarativeFastProperties::add(), QMetaObjectBuilder::addMetaObject(), QDeclarativePropertyCache::append(), classIDL(), clone(), QDeclarativePropertyCache::create(), QScript::QObjectDelegate::deleteProperty(), QDeclarativeCompiler::genObject(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertyNames(), QScript::QObjectDelegate::getOwnPropertySlot(), indexOfProperty(), QDeclarativeTypePrivate::init(), QAxBase::internalProperty(), QMetaProperty::isDesignable(), QMetaProperty::isScriptable(), QMetaProperty::isStored(), QMetaProperty::isUser(), QDeclarativeProxyMetaObject::metaCall(), QDeclarativePropertyPrivate::metaObjectForProperty(), property(), QAxBase::propertyBag(), QMetaProperty::propertyIndex(), QDeclarativeObjectScriptClass::propertyNames(), QScript::QObjectDelegate::put(), qax_noSuchFunction(), QDeclarativeVMEMetaObject::QDeclarativeVMEMetaObject(), QAxBase::qt_metacall(), QMetaProperty::read(), QMetaProperty::reset(), QAxBase::setPropertyBag(), and QMetaProperty::write().
 {
     int offset = 0;
     const QMetaObject *m = d.superdata;
     while (m) {
         offset += priv(m->d.data)->propertyCount;
         m = m->d.superdata;
     }
     return offset;
 }
removeGuard()
void QMetaObject::removeGuard (QObject ** ptr) static
Warning
This function is not part of the public interface.
Definition at line 406 of file qobject.cpp.
Referenced by QAction::activate(), and QPointer< QAbstractButton >::~QPointer().
 {
     if (!*ptr)
         return;
     GuardHash *hash = guardHash();
     /* check that the hash is empty - otherwise we might detach
        the shared_null hash, which will alloc, which is not nice */
     if (!hash || hash->isEmpty())
         return;
     QMutexLocker locker(guardHashLock());
     if (!*ptr) //check again, under the lock
         return;
     GuardHash::iterator it = hash->find(*ptr);
     const GuardHash::iterator end = hash->end();
     bool more = false; //if the QObject has more pointer attached to it.
     for (; it.key() == *ptr && it != end; ++it) {
         if (it.value() == ptr) {
             it = hash->erase(it);
             if (!more) more = (it != end && it.key() == *ptr);
             break;
         }
         more = true;
     }
     if (!more)
         QObjectPrivate::get(*ptr)->hasGuards = false;
 }
static_metacall()
int QMetaObject::static_metacall (Call cl, int idx, void ** argv) const
Warning
This function is not part of the public interface.
Definition at line 228 of file qmetaobject.cpp.
Referenced by QScript::callQtMethod(), and newInstance().
 {
     const QMetaObjectExtraData *extra = reinterpret_cast<const QMetaObjectExtraData *>(d.extradata);
     if (priv(d.data)->revision >= 6) {
         if (!extra || !extra->static_metacall)
             return 0;
         extra->static_metacall(0, cl, idx, argv);
         return -1;
     } else if (priv(d.data)->revision >= 2) {
         if (!extra || !extra->static_metacall)
             return 0;
         typedef int (*OldMetacall)(QMetaObject::Call, int, void **);
         OldMetacall o = reinterpret_cast<OldMetacall>(extra->static_metacall);
         return o(cl, idx, argv);
     }
     return 0;
 }
superClass()
const QMetaObject * QMetaObject::superClass () const inline
Returns the meta-object of the superclass, or 0 if there is no such object.
See also
className()
Definition at line 494 of file qobjectdefs.h.
Referenced by QDeclarativeFastProperties::accessorIndexForProperty(), activate(), QDeclarativeFastProperties::add(), QMetaObjectBuilder::addMetaObject(), QDeclarativeCompiler::buildPropertyObjectAssignment(), QDeclarativeCompiler::canCoerce(), QDeclarativePropertyPrivate::canConvert(), classIDL(), QDeclarativeCompiler::compileAlias(), QDeclarativePropertyCache::create(), QDeclarativeEnginePrivate::createCache(), QObject::disconnect(), QObject::dumpObjectInfo(), methodIndexToSignalIndex(), QScriptEnginePrivate::newQObject(), QStyleSheetStyleSelector::nodeNameEquals(), QStyleSheetStyleSelector::nodeNames(), objectInheritsXAndXIsCloserThanY(), QDeclarativeObjectMethodScriptClass::property(), qDBusInterfaceInObject(), qDBusIntrospectObject(), QAccessible::queryAccessibleInterface(), QDeclarativeObjectMethodScriptClass::relatedMethod(), QDBusConnectionPrivate::relaySignal(), QDeclarativeType::superType(), QDeclarativeCompiler::toQmlType(), and QDeclarativePropertyCache::updateRecur().
 { return d.superdata; }
tr() [1/2]
QString QMetaObject::tr (const char * s, const char * c) const
Warning
This function is not part of the public interface.
Definition at line 320 of file qmetaobject.cpp.
 {
     return QCoreApplication::translate(d.stringdata, s, c, QCoreApplication::CodecForTr);
 }
tr() [2/2]
QString QMetaObject::tr (const char * s, const char * c, int n) const
Warning
This function is not part of the public interface.
Definition at line 328 of file qmetaobject.cpp.
 {
     return QCoreApplication::translate(d.stringdata, s, c, QCoreApplication::CodecForTr, n);
 }
trUtf8() [1/2]
QString QMetaObject::trUtf8 (const char * s, const char * c) const
Warning
This function is not part of the public interface.
Definition at line 336 of file qmetaobject.cpp.
 {
     return QCoreApplication::translate(d.stringdata, s, c, QCoreApplication::UnicodeUTF8);
 }
trUtf8() [2/2]
QString QMetaObject::trUtf8 (const char * s, const char * c, int n) const
Warning
This function is not part of the public interface.
Definition at line 344 of file qmetaobject.cpp.
 {
     return QCoreApplication::translate(d.stringdata, s, c, QCoreApplication::UnicodeUTF8, n);
 }
userProperty()
QMetaProperty QMetaObject::userProperty () const
Returns the property that has the USER flag set to true.
Since
4.2
See also
QMetaProperty::isUser()
Definition at line 920 of file qmetaobject.cpp.
Referenced by QDataWidgetMapper::mappedPropertyName(), QStyledItemDelegate::setEditorData(), QItemDelegate::setEditorData(), QStyledItemDelegate::setModelData(), and QItemDelegate::setModelData().
 {
     const int propCount = propertyCount();
     for (int i = propCount - 1; i >= 0; --i) {
         const QMetaProperty prop = property(i);
         if (prop.isUser())
             return prop;
     }
     return QMetaProperty();
 }
Properties
d
struct { ... } QMetaObject::d
Referenced by QMetaObjectBuilder::addMetaObject(), QDeclarativeVMEMetaObject::aliasTarget(), buildMetaObject(), cast(), classInfo(), classInfoCount(), classInfoOffset(), QAxBase::clear(), computeOffsets(), QMetaObjectPrivate::connect(), QDeclarativeVMEMetaObject::connectAlias(), constructor(), constructorCount(), QAxBase::control(), QDeclarativeItemPrivate::data_append(), QAxBase::disableClassInfo(), QAxBase::disableEventSink(), QAxBase::disableMetaObject(), enumerator(), enumeratorCount(), enumeratorOffset(), QDeclarativePropertyPrivate::equal(), flush_vme_signal(), QMetaObjectBuilder::fromRelocatableData(), QMetaProperty::hasNotifySignal(), QMetaProperty::hasStdCppSet(), indexOfClassInfo(), indexOfConstructor(), indexOfEnumerator(), indexOfMethodRelative(), indexOfProperty(), QMetaObjectPrivate::indexOfSignalRelative(), QAxBase::indexOfVerb(), QDeclarativeTypePrivate::init(), QAxBase::initialize(), QAxBase::initializeFrom(), QAxBase::initializeRemote(), QAxBase::internalMetaObject(), QAxBase::internalRelease(), QMetaProperty::isDesignable(), QMetaProperty::isEnumType(), QMetaProperty::isReadable(), QMetaProperty::isResettable(), QMetaProperty::isScriptable(), QMetaProperty::isStored(), QMetaProperty::isUser(), QMetaProperty::isWritable(), QMetaObjectPrivate::memberIndexes(), QDeclarativeVMEMetaObject::metaCall(), MetaObjectGenerator::metaObject(), QDeclarativePropertyPrivate::metaObjectForProperty(), method(), methodCount(), methodOffset(), QMetaProperty::name(), normalizedSignature(), QMetaProperty::notifySignalIndex(), QDeclarativeParser::Object::Object(), property(), propertyCount(), propertyOffset(), QAxBase::QAxBase(), QAxMetaObject::QAxMetaObject(), QDeclarativeVMEMetaObject::QDeclarativeVMEMetaObject(), QMetaObject_findMetaObject(), QMetaObject_methods(), QMetaObject_properties(), qNormalizeType(), QAxBase::queryInterface(), QMetaProperty::read(), QMetaProperty::revision(), QAxBase::setControl(), static_metacall(), tr(), trUtf8(), QMetaProperty::type(), QMetaProperty::typeName(), QAxBase::verbs(), QDBusMetaObjectGenerator::write(), QMetaProperty::write(), QAxBase::~QAxBase(), and QAxMetaObject::~QAxMetaObject().
data
const uint* QMetaObject::data
Definition at line 471 of file qobjectdefs.h.
Referenced by QMetaObjectBuilder::addMetaObject(), buildMetaObject(), classInfoCount(), classInfoOffset(), enumeratorCount(), enumeratorOffset(), QMetaObjectBuilder::fromRelocatableData(), QMetaProperty::hasNotifySignal(), QMetaProperty::hasStdCppSet(), indexOfClassInfo(), indexOfConstructor(), indexOfEnumerator(), indexOfProperty(), QMetaProperty::isDesignable(), QMetaProperty::isEnumType(), QMetaProperty::isReadable(), QMetaProperty::isResettable(), QMetaProperty::isScriptable(), QMetaProperty::isStored(), QMetaProperty::isUser(), QMetaProperty::isWritable(), QMetaEnum::key(), QMetaEnum::keysToValue(), QMetaEnum::keyToValue(), QDeclarativeProxyMetaObject::metaCall(), QDeclarativeOpenMetaObject::metaCall(), MetaObjectGenerator::metaObject(), methodCount(), methodOffset(), QMetaProperty::name(), QMetaProperty::notifySignalIndex(), QDeclarativeParser::Object::Object(), propertyCount(), propertyOffset(), QMetaObject_methods(), QMetaObject_properties(), QMetaProperty::read(), QMetaProperty::revision(), QMetaProperty::type(), QMetaProperty::typeName(), QMetaEnum::value(), QMetaEnum::valueToKey(), QMetaEnum::valueToKeys(), QDBusMetaObjectGenerator::write(), and QMetaProperty::write().
extradata
const void* QMetaObject::extradata
Definition at line 472 of file qobjectdefs.h.
Referenced by QMetaObjectBuilder::addMetaObject(), buildMetaObject(), QMetaObjectPrivate::connect(), MetaObjectGenerator::metaObject(), QDeclarativeParser::Object::Object(), and QDBusMetaObjectGenerator::write().
stringdata
const char* QMetaObject::stringdata
Definition at line 470 of file qobjectdefs.h.
Referenced by buildMetaObject(), QDeclarativePropertyPrivate::equal(), QMetaObjectBuilder::fromRelocatableData(), indexOfClassInfo(), indexOfEnumerator(), indexOfMethodRelative(), indexOfProperty(), MetaObjectGenerator::metaObject(), QMetaProperty::name(), QDeclarativeParser::Object::Object(), QMetaProperty::read(), QMetaProperty::typeName(), QDBusMetaObjectGenerator::write(), and QMetaProperty::write().
superdata
const QMetaObject* QMetaObject::superdata
Definition at line 469 of file qobjectdefs.h.
Referenced by buildMetaObject(), cast(), classInfoCount(), classInfoOffset(), computeOffsets(), QDeclarativeItemPrivate::data_append(), enumeratorCount(), enumeratorOffset(), flush_vme_signal(), QMetaObjectBuilder::fromRelocatableData(), indexOfClassInfo(), indexOfEnumerator(), indexOfMethodRelative(), indexOfProperty(), QMetaObjectPrivate::indexOfSignalRelative(), QDeclarativeTypePrivate::init(), QMetaObjectPrivate::memberIndexes(), MetaObjectGenerator::metaObject(), QDeclarativePropertyPrivate::metaObjectForProperty(), methodCount(), methodOffset(), QDeclarativeParser::Object::Object(), propertyCount(), propertyOffset(), QMetaObject_findMetaObject(), and QDBusMetaObjectGenerator::write().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qobjectdefs.h
/src/corelib/kernel/qmetaobject.cpp
/src/corelib/kernel/qobject.cpp