Qt 4.8: QTextHtmlImporter::TableCellIterator Struct Reference
QTextHtmlImporter::TableCellIterator Struct Reference
Public Functions
bool atEnd () const
QTextTableCell cell () const
TableCellIterator & operator++ ()
TableCellIterator (QTextTable *t=0)
Public Variables
int column
int row
QTextTable * table
Detailed Description
Definition at line 163 of file qtextdocumentfragment_p.h.
Constructors and Destructors
TableCellIterator()
QTextHtmlImporter::TableCellIterator::TableCellIterator (QTextTable * t = 0) inline
Definition at line 165 of file qtextdocumentfragment_p.h.
 : table(t), row(0), column(0) {}
Functions
atEnd()
bool QTextHtmlImporter::TableCellIterator::atEnd () const inline
Definition at line 184 of file qtextdocumentfragment_p.h.
Referenced by QTextHtmlImporter::closeTag(), and QTextHtmlImporter::processBlockNode().
 { return table == 0 || row >= table->rows(); }
cell()
QTextTableCell QTextHtmlImporter::TableCellIterator::cell () const inline
Definition at line 186 of file qtextdocumentfragment_p.h.
Referenced by QTextHtmlImporter::closeTag(), and QTextHtmlImporter::processBlockNode().
 { return table->cellAt(row, column); }
operator++()
TableCellIterator& QTextHtmlImporter::TableCellIterator::operator++ () inline
Definition at line 167 of file qtextdocumentfragment_p.h.
{
             if (atEnd())
                 return *this;
             do {
                 const QTextTableCell cell = table->cellAt(row, column);
                 if (!cell.isValid())
                     break;
                 column += cell.columnSpan();
                 if (column >= table->columns()) {
                     column = 0;
                     ++row;
                 }
             } while (row < table->rows() && table->cellAt(row, column).row() != row);
             return *this;
         }
Properties
column
int QTextHtmlImporter::TableCellIterator::column
Definition at line 190 of file qtextdocumentfragment_p.h.
row
int QTextHtmlImporter::TableCellIterator::row
Definition at line 189 of file qtextdocumentfragment_p.h.
Referenced by QTextHtmlImporter::closeTag().
table
QTextTable* QTextHtmlImporter::TableCellIterator::table
Definition at line 188 of file qtextdocumentfragment_p.h.
The documentation for this struct was generated from the following file:
/src/gui/text/qtextdocumentfragment_p.h