Qt 4.8: QUtf16 Struct Reference
QUtf16 Struct Reference
#include <qutfcodec_p.h>
Static Public Functions
static QByteArray convertFromUnicode (const QChar *, int, QTextCodec::ConverterState *, DataEndianness=DetectEndianness)
static QString convertToUnicode (const char *, int, QTextCodec::ConverterState *, DataEndianness=DetectEndianness)
Detailed Description
Definition at line 74 of file qutfcodec_p.h.
Functions
convertFromUnicode()
QByteArray QUtf16::convertFromUnicode (const QChar * uc, int len, QTextCodec::ConverterState * state, DataEndianness e = DetectEndianness) static
Definition at line 269 of file qutfcodec.cpp.
Referenced by QUtf16Codec::convertFromUnicode().
 {
     DataEndianness endian = e;
     int length =  2*len;
     if (!state || (!(state->flags & QTextCodec::IgnoreHeader))) {
         length += 2;
     }
     if (e == DetectEndianness) {
         endian = (QSysInfo::ByteOrder == QSysInfo::BigEndian) ? BigEndianness : LittleEndianness;
     }
     QByteArray d;
     d.resize(length);
     char *data = d.data();
     if (!state || !(state->flags & QTextCodec::IgnoreHeader)) {
         QChar bom(QChar::ByteOrderMark);
         if (endian == BigEndianness) {
             data[0] = bom.row();
             data[1] = bom.cell();
         } else {
             data[0] = bom.cell();
             data[1] = bom.row();
         }
         data += 2;
     }
     if (endian == BigEndianness) {
         for (int i = 0; i < len; ++i) {
             *(data++) = uc[i].row();
             *(data++) = uc[i].cell();
         }
     } else {
         for (int i = 0; i < len; ++i) {
             *(data++) = uc[i].cell();
             *(data++) = uc[i].row();
         }
     }
     if (state) {
         state->remainingChars = 0;
         state->flags |= QTextCodec::IgnoreHeader;
     }
     return d;
 }
convertToUnicode()
QString QUtf16::convertToUnicode (const char * chars, int len, QTextCodec::ConverterState * state, DataEndianness e = DetectEndianness) static
Definition at line 313 of file qutfcodec.cpp.
Referenced by QUtf16Codec::convertToUnicode(), and QString::fromUtf16().
 {
     DataEndianness endian = e;
     bool half = false;
     uchar buf = 0;
     bool headerdone = false;
     if (state) {
         headerdone = state->flags & QTextCodec::IgnoreHeader;
         if (endian == DetectEndianness)
             endian = (DataEndianness)state->state_data[Endian];
         if (state->remainingChars) {
             half = true;
             buf = state->state_data[Data];
         }
     }
     if (headerdone && endian == DetectEndianness)
         endian = (QSysInfo::ByteOrder == QSysInfo::BigEndian) ? BigEndianness : LittleEndianness;
     QString result(len, Qt::Uninitialized); // worst case
     QChar *qch = (QChar *)result.unicode();
     while (len--) {
         if (half) {
             QChar ch;
             if (endian == LittleEndianness) {
                 ch.setRow(*chars++);
                 ch.setCell(buf);
             } else {
                 ch.setRow(buf);
                 ch.setCell(*chars++);
             }
             if (!headerdone) {
                 headerdone = true;
                 if (endian == DetectEndianness) {
                     if (ch == QChar::ByteOrderSwapped) {
                         endian = LittleEndianness;
                     } else if (ch == QChar::ByteOrderMark) {
                         endian = BigEndianness;
                     } else {
                         if (QSysInfo::ByteOrder == QSysInfo::BigEndian) {
                             endian = BigEndianness;
                         } else {
                             endian = LittleEndianness;
                             ch = QChar((ch.unicode() >> 8) | ((ch.unicode() & 0xff) << 8));
                         }
                         *qch++ = ch;
                     }
                 } else if (ch != QChar::ByteOrderMark) {
                     *qch++ = ch;
                 }
             } else {
                 *qch++ = ch;
             }
             half = false;
         } else {
             buf = *chars++;
             half = true;
         }
     }
     result.truncate(qch - result.unicode());
     if (state) {
         if (headerdone)
             state->flags |= QTextCodec::IgnoreHeader;
         state->state_data[Endian] = endian;
         if (half) {
             state->remainingChars = 1;
             state->state_data[Data] = buf;
         } else {
             state->remainingChars = 0;
             state->state_data[Data] = 0;
         }
     }
     return result;
 }
The documentation for this struct was generated from the following files:
/src/corelib/codecs/qutfcodec_p.h
/src/corelib/codecs/qutfcodec.cpp