Qt 4.8: QIntersectionPoint Struct Reference
QIntersectionPoint Struct Reference
Public Functions
bool isAccurate () const
bool isOnLine (const QPodPoint &u, const QPodPoint &v) const
bool isValid () const
bool operator!= (const QIntersectionPoint &other) const
bool operator< (const QIntersectionPoint &other) const
bool operator<= (const QIntersectionPoint &other) const
bool operator== (const QIntersectionPoint &other) const
bool operator> (const QIntersectionPoint &other) const
bool operator>= (const QIntersectionPoint &other) const
QPodPoint round () const
Public Variables
QPodPoint upperLeft
QFraction xOffset
QFraction yOffset
Detailed Description
Definition at line 366 of file qtriangulator.cpp.
Functions
isAccurate()
bool QIntersectionPoint::isAccurate () const inline
Definition at line 370 of file qtriangulator.cpp.
Referenced by QTriangulator< T >::ComplexToSimple::sortEdgeList(), and QTriangulator< T >::ComplexToSimple::splitEdgeListRange().
 {return xOffset.numerator == 0 && yOffset.numerator == 0;}
isOnLine()
bool QIntersectionPoint::isOnLine (const QPodPoint & u, const QPodPoint & v) const
Definition at line 490 of file qtriangulator.cpp.
Referenced by QTriangulator< T >::ComplexToSimple::calculateIntersection(), QTriangulator< T >::ComplexToSimple::sortEdgeList(), and QTriangulator< T >::ComplexToSimple::splitEdgeListRange().
 {
     // TODO: Make code path for coordinates with more than 21 bits.
     const QPodPoint p = upperLeft - u;
     const QPodPoint q = v - u;
     bool isHorizontal = p.y == 0 && yOffset.numerator == 0;
     bool isVertical = p.x == 0 && xOffset.numerator == 0;
     if (isHorizontal && isVertical)
         return true;
     if (isHorizontal)
         return q.y == 0;
     if (q.y == 0)
         return false;
     if (isVertical)
         return q.x == 0;
     if (q.x == 0)
         return false;
     // At this point, 'p+offset' and 'q' cannot lie on the x or y axis.
     if (((q.x < 0) == (q.y < 0)) != ((p.x < 0) == (p.y < 0)))
         return false; // 'p + offset' and 'q' pass through different quadrants.
     // Move all coordinates into the first quadrant.
     quint64 nx, ny;
     if (p.x < 0)
         nx = quint64(-p.x) * xOffset.denominator - xOffset.numerator;
     else
         nx = quint64(p.x) * xOffset.denominator + xOffset.numerator;
     if (p.y < 0)
         ny = quint64(-p.y) * yOffset.denominator - yOffset.numerator;
     else
         ny = quint64(p.y) * yOffset.denominator + yOffset.numerator;
     return qFraction(quint64(qAbs(q.x)) * xOffset.denominator, quint64(qAbs(q.y)) * yOffset.denominator) == qFraction(nx, ny);
 }
isValid()
bool QIntersectionPoint::isValid () const inline
Definition at line 368 of file qtriangulator.cpp.
Referenced by QTriangulator< T >::ComplexToSimple::calculateIntersection().
 {return xOffset.isValid() && yOffset.isValid();}
operator!=()
bool QIntersectionPoint::operator!= (const QIntersectionPoint & other) const inline
Definition at line 373 of file qtriangulator.cpp.
 {return !(*this == other);}
operator<()
bool QIntersectionPoint::operator< (const QIntersectionPoint & other) const
Definition at line 473 of file qtriangulator.cpp.
 {
     if (upperLeft.y != other.upperLeft.y)
         return upperLeft.y < other.upperLeft.y;
     if (yOffset != other.yOffset)
         return yOffset < other.yOffset;
     if (upperLeft.x != other.upperLeft.x)
         return upperLeft.x < other.upperLeft.x;
     return xOffset < other.xOffset;
 }
operator<=()
bool QIntersectionPoint::operator<= (const QIntersectionPoint & other) const inline
Definition at line 376 of file qtriangulator.cpp.
 {return !(*this > other);}
operator==()
bool QIntersectionPoint::operator== (const QIntersectionPoint & other) const
Definition at line 484 of file qtriangulator.cpp.
 {
     return upperLeft == other.upperLeft && xOffset == other.xOffset && yOffset == other.yOffset;
 }
operator>()
bool QIntersectionPoint::operator> (const QIntersectionPoint & other) const inline
Definition at line 374 of file qtriangulator.cpp.
 {return other < *this;}
operator>=()
bool QIntersectionPoint::operator>= (const QIntersectionPoint & other) const inline
Definition at line 375 of file qtriangulator.cpp.
 {return !(*this < other);}
round()
QPodPoint QIntersectionPoint::round () const
Definition at line 463 of file qtriangulator.cpp.
Referenced by QTriangulator< T >::ComplexToSimple::calculateIntersection().
 {
     QPodPoint result = upperLeft;
     if (2 * xOffset.numerator >= xOffset.denominator)
         ++result.x;
     if (2 * yOffset.numerator >= yOffset.denominator)
         ++result.y;
     return result;
 }
Properties
upperLeft
QPodPoint QIntersectionPoint::upperLeft
Definition at line 379 of file qtriangulator.cpp.
Referenced by operator<(), operator==(), qIntersectionPoint(), QTriangulator< T >::ComplexToSimple::sortEdgeList(), and QTriangulator< T >::ComplexToSimple::splitEdgeListRange().
xOffset
QFraction QIntersectionPoint::xOffset
Definition at line 380 of file qtriangulator.cpp.
Referenced by operator<(), operator==(), qIntersectionPoint(), and QTriangulator< T >::ComplexToSimple::splitEdgeListRange().
yOffset
QFraction QIntersectionPoint::yOffset
Definition at line 381 of file qtriangulator.cpp.
Referenced by operator<(), operator==(), qIntersectionPoint(), and QTriangulator< T >::ComplexToSimple::splitEdgeListRange().
The documentation for this struct was generated from the following file:
/src/opengl/gl2paintengineex/qtriangulator.cpp