Qt 4.8: QToolBoxPrivate::Page Struct Reference
QToolBoxPrivate::Page Struct Reference
Public Functions
QIcon icon () const
bool operator== (const Page &other) const
void setIcon (const QIcon &is)
void setText (const QString &text)
void setToolTip (const QString &tip)
QString text () const
QString toolTip () const
Public Variables
QToolBoxButton * button
QScrollArea * sv
QWidget * widget
Detailed Description
Definition at line 93 of file qtoolbox.cpp.
Functions
icon()
QIcon QToolBoxPrivate::Page::icon () const inline
Definition at line 106 of file qtoolbox.cpp.
Referenced by QToolBox::itemIcon().
 { return button->icon(); }
operator==()
bool QToolBoxPrivate::Page::operator== (const Page & other) const inline
Definition at line 108 of file qtoolbox.cpp.
         {
             return widget == other.widget;
         }
setIcon()
void QToolBoxPrivate::Page::setIcon (const QIcon & is) inline
Definition at line 100 of file qtoolbox.cpp.
Referenced by QToolBox::insertItem(), and QToolBox::setItemIcon().
 { button->setIcon(is); }
setText()
void QToolBoxPrivate::Page::setText (const QString & text) inline
Definition at line 99 of file qtoolbox.cpp.
Referenced by QToolBox::insertItem(), and QToolBox::setItemText().
 { button->setText(text); }
setToolTip()
void QToolBoxPrivate::Page::setToolTip (const QString & tip) inline
Definition at line 102 of file qtoolbox.cpp.
Referenced by QToolBox::setItemToolTip().
 { button->setToolTip(tip); }
text()
QString QToolBoxPrivate::Page::text () const inline
Definition at line 105 of file qtoolbox.cpp.
Referenced by QToolBox::itemText().
 { return button->text(); }
toolTip()
QString QToolBoxPrivate::Page::toolTip () const inline
Definition at line 103 of file qtoolbox.cpp.
Referenced by QToolBox::itemToolTip().
 { return button->toolTip(); }
Properties
button
QToolBoxButton* QToolBoxPrivate::Page::button
Definition at line 95 of file qtoolbox.cpp.
Referenced by QToolBoxPrivate::_q_widgetDestroyed(), QToolBox::insertItem(), QToolBox::isItemEnabled(), QToolBox::setCurrentIndex(), QToolBox::setItemEnabled(), and QToolBoxPrivate::updateTabs().
sv
QScrollArea* QToolBoxPrivate::Page::sv
Definition at line 96 of file qtoolbox.cpp.
Referenced by QToolBoxPrivate::_q_widgetDestroyed(), and QToolBox::insertItem().
widget
QWidget* QToolBoxPrivate::Page::widget
Definition at line 97 of file qtoolbox.cpp.
Referenced by QToolBox::insertItem(), operator==(), and QToolBoxPrivate::updateTabs().
The documentation for this struct was generated from the following file:
/src/gui/widgets/qtoolbox.cpp