Qt 4.8: QFactoryInterface Struct Reference
QFactoryInterface Struct Reference abstract
#include <qfactoryinterface.h>
Public Functions
virtual QStringList keys () const =0
virtual ~QFactoryInterface ()
Detailed Description
Definition at line 54 of file qfactoryinterface.h.
Constructors and Destructors
~QFactoryInterface()
virtual QFactoryInterface::~QFactoryInterface () inline virtual
Definition at line 56 of file qfactoryinterface.h.
 {}
Functions
keys()
virtual QStringList QFactoryInterface::keys () const pure virtual
Implemented in QtDBusScriptPlugin, QImageIOPlugin, QX11MenuBarFactory, QFontEnginePlugin, QIconEnginePluginV2, QInputContextPlugin, QNativeWifiEnginePlugin, QGuiPlatformPlugin, QTextCodecPlugin, QBearerEnginePlugin, QPlatformIntegrationPlugin, QGraphicsSystemPlugin, QAccessibleBridgePlugin, QAudioEnginePlugin, QPictureFormatPlugin, QAccessiblePlugin, QKbdDriverPlugin, QMouseDriverPlugin, QScreenDriverPlugin, QIconEnginePlugin, QGenericPlugin, QMultiInputContextPlugin, QStylePlugin, QDecorationPlugin, QSqlDriverPlugin, AccessibleFactory, QTDSDriverPlugin, QGifPlugin, QMngPlugin, QTgaPlugin, QDirectFbIntegrationPlugin, QNetworkManagerEnginePlugin, QTiffPlugin, CompatAccessibleFactory, QConnmanEnginePlugin, QCoreWlanEnginePlugin, QGenericEnginePlugin, QIcdEnginePlugin, QSvgIconPlugin, QSvgPlugin, QICOPlugin, QJpegPlugin, QBBEnginePlugin, QNlaEnginePlugin, ScreenVfbDriver, GfxVncDriver, QDB2DriverPlugin, QIBaseDriverPlugin, QMYSQLDriverPlugin, QOCIDriverPlugin, QODBCDriverPlugin, QPSQLDriverPlugin, QSQLiteDriverPlugin, QSQLite2DriverPlugin, QSymSQLDriverPlugin, DirectFBScreenDriverPlugin, QScreenLinuxFbPlugin, GfxTransformedDriver, DecorationDefault, DecorationStyled, DecorationWindows, QLinuxInputPlugin, QTsLibPlugin, QAhiScreenPlugin, PvrEglScreenPlugin, QLinuxInputKbdDriver, QLinuxTPMouseDriver, QPcMouseDriver, TslibMouseDriver, QCocoaIntegrationPlugin, QUIKitIntegrationPlugin, EGLNullWSScreenPlugin, QGLGraphicsSystemPlugin, QBBIntegrationPlugin, QMinimalIntegrationPlugin, QVFbIntegrationPlugin, QVNCIntegrationPlugin, QMeeGoGraphicsSystemPlugin, QVGGraphicsSystemPlugin, ShivaVGGraphicsSystemPlugin, QTraceGraphicsSystemPlugin, QEglIntegrationPlugin, QLinuxFbIntegrationPlugin, QOpenKODEPlugin, QWaylandIntegrationPlugin, QXcbIntegrationPlugin, QXlibIntegrationPlugin, and QScriptExtensionPlugin.
Referenced by QScriptEngine::availableExtensions(), QScriptEngine::importExtension(), and QFactoryLoader::updateDir().
The documentation for this struct was generated from the following file:
/src/corelib/plugin/qfactoryinterface.h