Qt 4.8: QMenuBarPrivate::QWceMenuBarPrivate Struct Reference
QMenuBarPrivate::QWceMenuBarPrivate Struct Reference
#include <qmenubar_p.h>
Public Functions
void addAction (QAction *, QAction *=0)
void addAction (QWceMenuAction *, QWceMenuAction *=0)
QWceMenuAction * findAction (QAction *a)
QWceMenuBarPrivate (QMenuBarPrivate *menubar)
void rebuild ()
void removeAction (QWceMenuAction *)
void removeAction (QAction *a)
void syncAction (QWceMenuAction *)
void syncAction (QAction *a)
~QWceMenuBarPrivate ()
Public Variables
QList< QWceMenuAction * > actionItems
QList< QList< QWceMenuAction * > > actionItemsClassic
QList< QWceMenuAction * > actionItemsLeftButton
QMenuBarPrivate * d
QPointer< QAction > leftButtonAction
int leftButtonCommand
bool leftButtonIsMenu
HMENU leftButtonMenuHandle
HWND menubarHandle
HMENU menuHandle
HWND parentWindowHandle
Detailed Description
Definition at line 225 of file qmenubar_p.h.
Constructors and Destructors
QWceMenuBarPrivate()
QMenuBarPrivate::QWceMenuBarPrivate::QWceMenuBarPrivate (QMenuBarPrivate * menubar)
Definition at line 410 of file qmenu_wince.cpp.
 :   menubarHandle(0), menuHandle(0), leftButtonMenuHandle(0),
     leftButtonAction(0), leftButtonIsMenu(false), d(menubar)
 {
 }
~QWceMenuBarPrivate()
QMenuBarPrivate::QWceMenuBarPrivate::~QWceMenuBarPrivate ()
Definition at line 416 of file qmenu_wince.cpp.
 {
     if (menubarHandle)
         DestroyWindow(menubarHandle);
     qt_wce_delete_action_list(&actionItems);
     qt_wce_delete_action_list(&actionItemsLeftButton);
     for (int i=0; i<actionItemsClassic.size(); ++i)
         if (!actionItemsClassic.value(i).empty())
             qt_wce_delete_action_list(&actionItemsClassic[i]);
     actionItemsClassic.clear();
     menubarHandle = 0;
     menuHandle = 0;
     leftButtonMenuHandle = 0;
     leftButtonCommand = 0;
     QMenuBar::wceRefresh();
 }
Functions
addAction() [1/2]
void QMenuBarPrivate::QWceMenuBarPrivate::addAction (QAction * a, QAction * before = 0)
Definition at line 519 of file qmenu_wince.cpp.
Referenced by QMenuBar::actionEvent().
 {
     QWceMenuAction *action = new QWceMenuAction;
     action->action = a;
     action->command = qt_wce_menu_static_cmd_id++;
     addAction(action, findAction(before));
 }
addAction() [2/2]
void QMenuBarPrivate::QWceMenuBarPrivate::addAction (QWceMenuAction * action, QWceMenuAction * before = 0)
Definition at line 527 of file qmenu_wince.cpp.
 {
     if (!action)
         return;
     int before_index = actionItems.indexOf(before);
     if (before_index < 0) {
         before = 0;
         before_index = actionItems.size();
     }
     actionItems.insert(before_index, action);
     rebuild();
 }
findAction()
QWceMenuAction* QMenuBarPrivate::QWceMenuBarPrivate::findAction (QAction * a) inline
Definition at line 247 of file qmenubar_p.h.
{
             for(int i = 0; i < actionItems.size(); i++) {
                 QWceMenuAction *act = actionItems[i];
                 if(a == act->action)
                     return act;
             }
             return 0;
         }
rebuild()
void QMenuBarPrivate::QWceMenuBarPrivate::rebuild ()
Definition at line 559 of file qmenu_wince.cpp.
 {
     d->q_func()->resize(0,0);
     parentWindowHandle = d->q_func()->parentWidget() ? d->q_func()->parentWidget()->winId() : d->q_func()->winId();
     if (d->wceClassicMenu) {
         QList<QAction*> actions = d->actions;
         int maxEntries;
         int resourceHandle;
         if (actions.size() < 5) {
             maxEntries = 4;
             resourceHandle = IDR_MAIN_MENU3;
         } else if (actions.size() < 7) {
             maxEntries = 6;
             resourceHandle = IDR_MAIN_MENU4;
         }
         else {
           maxEntries = 8;
           resourceHandle = IDR_MAIN_MENU5;
         }
         Q_ASSERT_X(menubarHandle, "rebuild !created", "menubar already deleted");
         qt_wce_clear_menu(menuHandle);
         DestroyWindow(menubarHandle);
         menubarHandle = qt_wce_create_menubar(parentWindowHandle, qt_wce_get_module_handle(), resourceHandle);
         Q_ASSERT_X(menubarHandle, "rebuild classic menu", "cannot create menubar from resource");
         DrawMenuBar(menubarHandle);
         QList<int> menu_ids;
         QList<int> item_ids;
         menu_ids << IDM_MENU1 << IDM_MENU2 << IDM_MENU3 << IDM_MENU4 << IDM_MENU5 << IDM_MENU6 << IDM_MENU7 << IDM_MENU8;
         item_ids << IDM_ITEM1 << IDM_ITEM2 << IDM_ITEM3 << IDM_ITEM4 << IDM_ITEM5 << IDM_ITEM6 << IDM_ITEM7 << IDM_ITEM8;
         for (int i = 0; i < actionItemsClassic.size(); ++i)
           if (!actionItemsClassic.value(i).empty())
             qt_wce_delete_action_list(&actionItemsClassic[i]);
         actionItemsClassic.clear();
         for (int i = 0; i < actions.size(); ++i) {
             qt_wce_rename_menu_item(menubarHandle, menu_ids.at(i), actions.at(i)->text());
             QList<QAction *> subActions = actions.at(i)->menu()->actions();
             HMENU subMenuHandle = (HMENU) SendMessage(menubarHandle, SHCMBM_GETSUBMENU,0 , menu_ids.at(i));
             DeleteMenu(subMenuHandle, item_ids.at(i), MF_BYCOMMAND);
             for (int c = 0; c < subActions.size(); ++c) {
                 QList<QWceMenuAction*> list;
                 actionItemsClassic.append(list);
                 QWceMenuAction *action = new QWceMenuAction;
                 action->action = subActions.at(c);
                 action->command = qt_wce_menu_static_cmd_id++;
                 action->menuHandle = subMenuHandle;
                 actionItemsClassic.last().append(action);
                 qt_wce_insert_action(subMenuHandle, action);
             }
         }
         for (int i = actions.size();i<maxEntries;++i) {
             qt_wce_rename_menu_item(menubarHandle, menu_ids.at(i), QString());
             qt_wce_disable_soft_key(menubarHandle, menu_ids.at(i));
         }
     } else {
         leftButtonAction = d->defaultAction;
         if (!leftButtonAction)
             leftButtonAction = qt_wce_get_quit_action(actionItems);
         leftButtonIsMenu = (leftButtonAction && leftButtonAction->menu());
         Q_ASSERT_X(menubarHandle, "rebuild !created", "menubar already deleted");
         qt_wce_clear_menu(menuHandle);
         DestroyWindow(menubarHandle);
         if (leftButtonIsMenu) {
             menubarHandle = qt_wce_create_menubar(parentWindowHandle, qt_wce_get_module_handle(), IDR_MAIN_MENU2);
             Q_ASSERT_X(menubarHandle, "rebuild !created left menubar", "cannot create menubar from resource");
             menuHandle = (HMENU) SendMessage(menubarHandle, SHCMBM_GETSUBMENU,0,IDM_MENU);
             Q_ASSERT_X(menuHandle, "rebuild !created", "IDM_MENU not found - invalid resource?");
             DeleteMenu(menuHandle, IDM_ABOUT, MF_BYCOMMAND);
             leftButtonMenuHandle = (HMENU) SendMessage(menubarHandle, SHCMBM_GETSUBMENU,0,IDM_LEFTMENU);
             Q_ASSERT_X(leftButtonMenuHandle, "rebuild !created", "IDM_LEFTMENU not found - invalid resource?");
             DeleteMenu(leftButtonMenuHandle, IDM_VIEW, MF_BYCOMMAND);
         } else {
             menubarHandle = qt_wce_create_menubar(parentWindowHandle, qt_wce_get_module_handle(), IDR_MAIN_MENU);
             Q_ASSERT_X(menubarHandle, "rebuild !created no left menubar", "cannot create menubar from resource");
             menuHandle = (HMENU) SendMessage(menubarHandle, SHCMBM_GETSUBMENU,0,IDM_MENU);
             Q_ASSERT_X(menuHandle, "rebuild !created", "IDM_MENU not found - invalid resource?");
             DeleteMenu(menuHandle, IDM_ABOUT, MF_BYCOMMAND);
             leftButtonMenuHandle = 0;
             leftButtonCommand = qt_wce_menu_static_cmd_id++;
             qt_wce_change_command(menubarHandle, IDM_EXIT, leftButtonCommand);
         }
         if (actionItems.size() == 0) {
             qt_wce_rename_menu_item(menubarHandle, IDM_MENU, QLatin1String(""));
             qt_wce_disable_soft_key(menubarHandle, IDM_MENU);
         }
         for (int i = 0; i < actionItems.size(); ++i) {
             QWceMenuAction *action = actionItems.at(i);
             action->menuHandle = menuHandle;
             qt_wce_insert_action(menuHandle, action);
         }
         if (!leftButtonIsMenu) {
             if (leftButtonAction) {
                 qt_wce_rename_menu_item(menubarHandle, leftButtonCommand, leftButtonAction->text());
                 qt_wce_enable_soft_key(menubarHandle, leftButtonCommand);
             } else {
                 qt_wce_rename_menu_item(menubarHandle, leftButtonCommand, QLatin1String(""));
                 qt_wce_disable_soft_key(menubarHandle, leftButtonCommand);
             }
         } else {
             qt_wce_rename_menu_item(menubarHandle, IDM_LEFTMENU, leftButtonAction->text());
             QList<QAction *> actions = leftButtonAction->menu()->actions();
             qt_wce_delete_action_list(&actionItemsLeftButton);
             for (int i=0; i<actions.size(); ++i) {
                 QWceMenuAction *action = new QWceMenuAction;
                 action->action = actions.at(i);
                 action->command = qt_wce_menu_static_cmd_id++;
                 action->menuHandle = leftButtonMenuHandle;
                 actionItemsLeftButton.append(action);
                 qt_wce_insert_action(leftButtonMenuHandle, action);
             }
         }
     }
     DrawMenuBar(menubarHandle);
 }
removeAction() [1/2]
void QMenuBarPrivate::QWceMenuBarPrivate::removeAction (QWceMenuAction * action)
Definition at line 546 of file qmenu_wince.cpp.
Referenced by QMenuBar::actionEvent().
 {
     actionItems.removeAll(action);
     delete action;
     rebuild();
 }
removeAction() [2/2]
void QMenuBarPrivate::QWceMenuBarPrivate::removeAction (QAction * a) inline
Definition at line 246 of file qmenubar_p.h.
Referenced by removeAction().
 { removeAction(findAction(a)); }
syncAction() [1/2]
void QMenuBarPrivate::QWceMenuBarPrivate::syncAction (QWceMenuAction *)
Definition at line 540 of file qmenu_wince.cpp.
Referenced by QMenuBar::actionEvent().
 {
     QMenuBar::wceRefresh();
     rebuild();
 }
syncAction() [2/2]
void QMenuBarPrivate::QWceMenuBarPrivate::syncAction (QAction * a) inline
Definition at line 243 of file qmenubar_p.h.
Referenced by syncAction().
 { syncAction(findAction(a)); }
Properties
actionItems
QList<QWceMenuAction*> QMenuBarPrivate::QWceMenuBarPrivate::actionItems
Definition at line 226 of file qmenubar_p.h.
Referenced by ~QWceMenuBarPrivate().
actionItemsClassic
QList<QList<QWceMenuAction*> > QMenuBarPrivate::QWceMenuBarPrivate::actionItemsClassic
Definition at line 228 of file qmenubar_p.h.
Referenced by ~QWceMenuBarPrivate().
actionItemsLeftButton
QList<QWceMenuAction*> QMenuBarPrivate::QWceMenuBarPrivate::actionItemsLeftButton
Definition at line 227 of file qmenubar_p.h.
Referenced by ~QWceMenuBarPrivate().
d
QMenuBarPrivate* QMenuBarPrivate::QWceMenuBarPrivate::d
Definition at line 235 of file qmenubar_p.h.
leftButtonAction
QPointer<QAction> QMenuBarPrivate::QWceMenuBarPrivate::leftButtonAction
Definition at line 234 of file qmenubar_p.h.
leftButtonCommand
int QMenuBarPrivate::QWceMenuBarPrivate::leftButtonCommand
Definition at line 236 of file qmenubar_p.h.
Referenced by ~QWceMenuBarPrivate().
leftButtonIsMenu
bool QMenuBarPrivate::QWceMenuBarPrivate::leftButtonIsMenu
Definition at line 233 of file qmenubar_p.h.
leftButtonMenuHandle
HMENU QMenuBarPrivate::QWceMenuBarPrivate::leftButtonMenuHandle
Definition at line 230 of file qmenubar_p.h.
Referenced by ~QWceMenuBarPrivate().
menubarHandle
HWND QMenuBarPrivate::QWceMenuBarPrivate::menubarHandle
Definition at line 231 of file qmenubar_p.h.
Referenced by ~QWceMenuBarPrivate().
menuHandle
HMENU QMenuBarPrivate::QWceMenuBarPrivate::menuHandle
Definition at line 229 of file qmenubar_p.h.
Referenced by ~QWceMenuBarPrivate().
parentWindowHandle
HWND QMenuBarPrivate::QWceMenuBarPrivate::parentWindowHandle
Definition at line 232 of file qmenubar_p.h.
Referenced by QMenuBar::wceCommands().
The documentation for this struct was generated from the following files:
/src/gui/widgets/qmenubar_p.h
/src/gui/widgets/qmenu_wince.cpp