Qt 4.8: QUtf32 Struct Reference
QUtf32 Struct Reference
#include <qutfcodec_p.h>
Static Public Functions
static QByteArray convertFromUnicode (const QChar *, int, QTextCodec::ConverterState *, DataEndianness=DetectEndianness)
static QString convertToUnicode (const char *, int, QTextCodec::ConverterState *, DataEndianness=DetectEndianness)
Detailed Description
Definition at line 80 of file qutfcodec_p.h.
Functions
convertFromUnicode()
QByteArray QUtf32::convertFromUnicode (const QChar * uc, int len, QTextCodec::ConverterState * state, DataEndianness e = DetectEndianness) static
Definition at line 388 of file qutfcodec.cpp.
Referenced by QUtf32Codec::convertFromUnicode().
 {
     DataEndianness endian = e;
     int length =  4*len;
     if (!state || (!(state->flags & QTextCodec::IgnoreHeader))) {
         length += 4;
     }
     if (e == DetectEndianness) {
         endian = (QSysInfo::ByteOrder == QSysInfo::BigEndian) ? BigEndianness : LittleEndianness;
     }
     QByteArray d(length, Qt::Uninitialized);
     char *data = d.data();
     if (!state || !(state->flags & QTextCodec::IgnoreHeader)) {
         if (endian == BigEndianness) {
             data[0] = 0;
             data[1] = 0;
             data[2] = (char)0xfe;
             data[3] = (char)0xff;
         } else {
             data[0] = (char)0xff;
             data[1] = (char)0xfe;
             data[2] = 0;
             data[3] = 0;
         }
         data += 4;
     }
     if (endian == BigEndianness) {
         for (int i = 0; i < len; ++i) {
             uint cp = uc[i].unicode();
             if (uc[i].isHighSurrogate() && i < len - 1)
                 cp = QChar::surrogateToUcs4(cp, uc[++i].unicode());
             *(data++) = cp >> 24;
             *(data++) = (cp >> 16) & 0xff;
             *(data++) = (cp >> 8) & 0xff;
             *(data++) = cp & 0xff;
         }
     } else {
         for (int i = 0; i < len; ++i) {
             uint cp = uc[i].unicode();
             if (uc[i].isHighSurrogate() && i < len - 1)
                 cp = QChar::surrogateToUcs4(cp, uc[++i].unicode());
             *(data++) = cp & 0xff;
             *(data++) = (cp >> 8) & 0xff;
             *(data++) = (cp >> 16) & 0xff;
             *(data++) = cp >> 24;
         }
     }
     if (state) {
         state->remainingChars = 0;
         state->flags |= QTextCodec::IgnoreHeader;
     }
     return d;
 }
convertToUnicode()
QString QUtf32::convertToUnicode (const char * chars, int len, QTextCodec::ConverterState * state, DataEndianness e = DetectEndianness) static
Definition at line 444 of file qutfcodec.cpp.
Referenced by QUtf32Codec::convertToUnicode(), and QString::fromUcs4().
 {
     DataEndianness endian = e;
     uchar tuple[4];
     int num = 0;
     bool headerdone = false;
     if (state) {
         headerdone = state->flags & QTextCodec::IgnoreHeader;
         if (endian == DetectEndianness) {
             endian = (DataEndianness)state->state_data[Endian];
         }
         num = state->remainingChars;
         memcpy(tuple, &state->state_data[Data], 4);
     }
     if (headerdone && endian == DetectEndianness)
         endian = (QSysInfo::ByteOrder == QSysInfo::BigEndian) ? BigEndianness : LittleEndianness;
     QString result;
     result.resize((num + len) >> 2 << 1); // worst case
     QChar *qch = (QChar *)result.unicode();
     const char *end = chars + len;
     while (chars < end) {
         tuple[num++] = *chars++;
         if (num == 4) {
             if (!headerdone) {
                 if (endian == DetectEndianness) {
                     if (endian == DetectEndianness) {
                         if (tuple[0] == 0xff && tuple[1] == 0xfe && tuple[2] == 0 && tuple[3] == 0 && endian != BigEndianness) {
                             endian = LittleEndianness;
                             num = 0;
                             continue;
                         } else if (tuple[0] == 0 && tuple[1] == 0 && tuple[2] == 0xfe && tuple[3] == 0xff && endian != LittleEndianness) {
                             endian = BigEndianness;
                             num = 0;
                             continue;
                         } else if (QSysInfo::ByteOrder == QSysInfo::BigEndian) {
                             endian = BigEndianness;
                         } else {
                             endian = LittleEndianness;
                         }
                     }
                 } else if (((endian == BigEndianness) ? qFromBigEndian<quint32>(tuple) : qFromLittleEndian<quint32>(tuple)) == QChar::ByteOrderMark) {
                     num = 0;
                     continue;
                 }
             }
             uint code = (endian == BigEndianness) ? qFromBigEndian<quint32>(tuple) : qFromLittleEndian<quint32>(tuple);
             if (code >= 0x10000) {
                 *qch++ = QChar::highSurrogate(code);
                 *qch++ = QChar::lowSurrogate(code);
             } else {
                 *qch++ = code;
             }
             num = 0;
         }
     }
     result.truncate(qch - result.unicode());
     if (state) {
         if (headerdone)
             state->flags |= QTextCodec::IgnoreHeader;
         state->state_data[Endian] = endian;
         state->remainingChars = num;
         memcpy(&state->state_data[Data], tuple, 4);
     }
     return result;
 }
The documentation for this struct was generated from the following files:
/src/corelib/codecs/qutfcodec_p.h
/src/corelib/codecs/qutfcodec.cpp