Qt 4.8: QContiguousCacheTypedData< T > Struct Template Reference
QContiguousCacheTypedData< T > Struct Template Reference
#include <qcontiguouscache.h>
Static Public Functions
static void free (QContiguousCacheTypedData *data)
Public Variables
T array [1]
Additional Inherited Members
Static Private Functions inherited from QContiguousCacheData
static QContiguousCacheData * allocate (int size, int alignment)
static void free (QContiguousCacheData *data)
Properties inherited from QContiguousCacheData
int alloc
int count
int offset
QBasicAtomicInt ref
uint reserved: 31
uint sharable: 1
int start
Detailed Description
template<typename T>
struct QContiguousCacheTypedData< T >
Definition at line 81 of file qcontiguouscache.h.
Functions
free()
template<typename T> static void QContiguousCacheTypedData< T >::free (QContiguousCacheTypedData< T > * data) inline static
Definition at line 86 of file qcontiguouscache.h.
Referenced by QContiguousCache< T >::clear(), QContiguousCache< T >::detach_helper(), QContiguousCache< T >::free(), QContiguousCache< T >::normalizeIndexes(), QContiguousCache< T >::operator=(), QContiguousCache< T >::setCapacity(), and QContiguousCache< T >::~QContiguousCache().
 { QContiguousCacheData::free(data); }
Properties
array
template<typename T> T QContiguousCacheTypedData< T >::array[1]
Definition at line 84 of file qcontiguouscache.h.
The documentation for this struct was generated from the following file:
/src/corelib/tools/qcontiguouscache.h