Qt 4.8: QDeclarativeCompiler::BindingContext Struct Reference
QDeclarativeCompiler::BindingContext Struct Reference
Public Functions
BindingContext ()
BindingContext (QDeclarativeParser::Object *o)
BindingContext incr () const
bool isSubContext () const
Public Variables
QDeclarativeParser::Object * object
int owner
int stack
Detailed Description
Definition at line 172 of file qdeclarativecompiler_p.h.
Constructors and Destructors
BindingContext() [1/2]
QDeclarativeCompiler::BindingContext::BindingContext () inline
Definition at line 173 of file qdeclarativecompiler_p.h.
             : stack(0), owner(0), object(0) {}
BindingContext() [2/2]
QDeclarativeCompiler::BindingContext::BindingContext (QDeclarativeParser::Object * o) inline
Definition at line 175 of file qdeclarativecompiler_p.h.
             : stack(0), owner(0), object(o) {}
Functions
incr()
BindingContext QDeclarativeCompiler::BindingContext::incr () const inline
Definition at line 177 of file qdeclarativecompiler_p.h.
Referenced by QDeclarativeCompiler::buildAttachedProperty(), and QDeclarativeCompiler::buildGroupedProperty().
{
             BindingContext rv(object);
             rv.stack = stack + 1;
             return rv;
         }
isSubContext()
bool QDeclarativeCompiler::BindingContext::isSubContext () const inline
Definition at line 182 of file qdeclarativecompiler_p.h.
Referenced by QDeclarativeCompiler::buildProperty(), and QDeclarativeCompiler::buildSubObject().
 { return stack != 0; }
Properties
object
QDeclarativeParser::Object* QDeclarativeCompiler::BindingContext::object
Definition at line 185 of file qdeclarativecompiler_p.h.
Referenced by QDeclarativeCompiler::completeComponentBuild().
owner
int QDeclarativeCompiler::BindingContext::owner
Definition at line 184 of file qdeclarativecompiler_p.h.
Referenced by QDeclarativeCompiler::buildValueTypeProperty().
stack
int QDeclarativeCompiler::BindingContext::stack
Definition at line 183 of file qdeclarativecompiler_p.h.
Referenced by QDeclarativeCompiler::buildScriptStringProperty(), QDeclarativeCompiler::genObjectBody(), and incr().
The documentation for this struct was generated from the following file:
/src/declarative/qml/qdeclarativecompiler_p.h