Qt 4.8: QMenuBarPrivate::QMacMenuBarPrivate Struct Reference
QMenuBarPrivate::QMacMenuBarPrivate Struct Reference
#include <qmenubar_p.h>
Public Functions
void addAction (QAction *, QAction *=0)
void addAction (QMacMenuAction *, QMacMenuAction *=0)
QMacMenuAction * findAction (QAction *a)
QMacMenuBarPrivate ()
void removeAction (QMacMenuAction *)
void removeAction (QAction *a)
void syncAction (QMacMenuAction *)
void syncAction (QAction *a)
~QMacMenuBarPrivate ()
Public Variables
QList< QMacMenuAction * > actionItems
OSMenuRef apple_menu
OSMenuRef menu
Detailed Description
Definition at line 195 of file qmenubar_p.h.
Constructors and Destructors
QMacMenuBarPrivate()
QMenuBarPrivate::QMacMenuBarPrivate::QMacMenuBarPrivate ()
Definition at line 1618 of file qmenu_mac.mm.
                                                       : menu(0), apple_menu(0)
 {
 }
~QMacMenuBarPrivate()
QMenuBarPrivate::QMacMenuBarPrivate::~QMacMenuBarPrivate ()
Definition at line 1622 of file qmenu_mac.mm.
 {
     for(QList<QMacMenuAction*>::Iterator it = actionItems.begin(); it != actionItems.end(); ++it)
         delete (*it);
 #ifndef QT_MAC_USE_COCOA
     if (apple_menu) {
         QMenuMergeList *list = 0;
         GetMenuItemProperty(apple_menu, 0, kMenuCreatorQt, kMenuPropertyMergeList,
                             sizeof(list), 0, &list);
         if (list) {
             RemoveMenuItemProperty(apple_menu, 0, kMenuCreatorQt, kMenuPropertyMergeList);
             delete list;
         }
         ReleaseMenu(apple_menu);
     }
     if (menu)
         ReleaseMenu(menu);
 #else
     [apple_menu release];
     [menu release];
 #endif
 }
Functions
addAction() [1/2]
void QMenuBarPrivate::QMacMenuBarPrivate::addAction (QAction * a, QAction * before = 0)
Definition at line 1646 of file qmenu_mac.mm.
Referenced by QMenuBarPrivate::macMenu().
 {
     if (a->isSeparator() || !menu)
         return;
     QMacMenuAction *action = new QMacMenuAction;
     action->action = a;
     action->ignore_accel = 1;
 #ifndef QT_MAC_USE_COCOA
     action->command = qt_mac_menu_static_cmd_id++;
 #endif
     addAction(action, findAction(before));
 }
addAction() [2/2]
void QMenuBarPrivate::QMacMenuBarPrivate::addAction (QMacMenuAction * action, QMacMenuAction * before = 0)
Definition at line 1660 of file qmenu_mac.mm.
 {
     if (!action || !menu)
         return;
     int before_index = actionItems.indexOf(before);
     if (before_index < 0) {
         before = 0;
         before_index = actionItems.size();
     }
     actionItems.insert(before_index, action);
     MenuItemIndex index = actionItems.size()-1;
     action->menu = menu;
 #ifdef QT_MAC_USE_COCOA
     QMacCocoaAutoReleasePool pool;
     [action->menu retain];
     NSMenuItem *newItem = createNSMenuItem(action->action->text());
     action->menuItem = newItem;
 #endif
     if (before) {
 #ifndef QT_MAC_USE_COCOA
         InsertMenuItemTextWithCFString(action->menu, 0, qMax(1, before_index+1), 0, action->command);
 #else
         [menu insertItem:newItem atIndex:qMax(1, before_index + 1)];
 #endif
         index = before_index;
     } else {
 #ifndef QT_MAC_USE_COCOA
         AppendMenuItemTextWithCFString(action->menu, 0, 0, action->command, &index);
 #else
         [menu addItem:newItem];
 #endif
     }
 #ifndef QT_MAC_USE_COCOA
     SetMenuItemProperty(action->menu, index, kMenuCreatorQt, kMenuPropertyQAction, sizeof(action),
                         &action);
 #else
     [newItem setTag:long(static_cast<QAction *>(action->action))];
 #endif
     syncAction(action);
 }
findAction()
QMacMenuAction* QMenuBarPrivate::QMacMenuBarPrivate::findAction (QAction * a) inline
Definition at line 207 of file qmenubar_p.h.
Referenced by removeAction(), QMenuBarPrivate::QWceMenuBarPrivate::removeAction(), syncAction(), and QMenuBarPrivate::QWceMenuBarPrivate::syncAction().
{
             for(int i = 0; i < actionItems.size(); i++) {
                 QMacMenuAction *act = actionItems[i];
                 if(a == act->action)
                     return act;
             }
             return 0;
         }
removeAction() [1/2]
void QMenuBarPrivate::QMacMenuBarPrivate::removeAction (QMacMenuAction * action)
Definition at line 1766 of file qmenu_mac.mm.
Referenced by syncAction(), and QMenuBarPrivate::QWceMenuBarPrivate::syncAction().
 {
     if (!action || !menu)
         return;
 #ifndef QT_MAC_USE_COCOA
     DeleteMenuItem(action->menu, qt_mac_menu_find_action(action->menu, action));
 #else
     QMacCocoaAutoReleasePool pool;
     [action->menu removeItem:action->menuItem];
 #endif
     actionItems.removeAll(action);
 }
removeAction() [2/2]
void QMenuBarPrivate::QMacMenuBarPrivate::removeAction (QAction * a) inline
Definition at line 206 of file qmenubar_p.h.
Referenced by removeAction().
 { removeAction(findAction(a)); }
syncAction() [1/2]
void QMenuBarPrivate::QMacMenuBarPrivate::syncAction (QMacMenuAction * action)
Definition at line 1705 of file qmenu_mac.mm.
 {
     if (!action || !menu)
         return;
 #ifndef QT_MAC_USE_COCOA
     const int index = qt_mac_menu_find_action(action->menu, action);
 #else
     QMacCocoaAutoReleasePool pool;
     NSMenuItem *item = action->menuItem;
 #endif
     OSMenuRef submenu = 0;
     bool release_submenu = false;
     if (action->action->menu()) {
         if ((submenu = action->action->menu()->macMenu(apple_menu))) {
 #ifndef QT_MAC_USE_COCOA
             QWidget *caused = 0;
             GetMenuItemProperty(action->menu, 0, kMenuCreatorQt, kMenuPropertyQWidget, sizeof(caused), 0, &caused);
             SetMenuItemProperty(submenu, 0, kMenuCreatorQt, kMenuPropertyCausedQWidget, sizeof(caused), &caused);
 #else
             if ([submenu supermenu] && [submenu supermenu] != [item menu])
                 return;
             else
                 [item setSubmenu:submenu];
 #endif
         }
 #ifndef QT_MAC_USE_COCOA
     } else { // create a submenu to act as menu
         release_submenu = true;
         CreateNewMenu(0, 0, &submenu);
 #endif
     }
     if (submenu) {
         bool visible = actualMenuItemVisibility(this, action);
 #ifndef QT_MAC_USE_COCOA
         SetMenuItemHierarchicalMenu(action->menu, index, submenu);
         SetMenuTitleWithCFString(submenu, QCFString(qt_mac_removeMnemonics(action->action->text())));
         if (visible)
             ChangeMenuAttributes(submenu, 0, kMenuAttrHidden);
         else
             ChangeMenuAttributes(submenu, kMenuAttrHidden, 0);
 #else
         [item setSubmenu: submenu];
         [submenu setTitle:qt_mac_QStringToNSString(qt_mac_removeMnemonics(action->action->text()))];
         syncNSMenuItemVisiblity(item, visible);
         syncNSMenuItemEnabled(item, action->action->isEnabled());
 #endif
         if (release_submenu) { //no pointers to it
 #ifndef QT_MAC_USE_COCOA
             ReleaseMenu(submenu);
 #else
             [submenu release];
 #endif
         }
     } else {
         qWarning("QMenu: No OSMenuRef created for popup menu");
     }
 }
syncAction() [2/2]
void QMenuBarPrivate::QMacMenuBarPrivate::syncAction (QAction * a) inline
Definition at line 204 of file qmenubar_p.h.
Referenced by syncAction().
 { syncAction(findAction(a)); }
Properties
actionItems
QList<QMacMenuAction*> QMenuBarPrivate::QMacMenuBarPrivate::actionItems
Definition at line 196 of file qmenubar_p.h.
Referenced by qt_mac_get_accel().
apple_menu
OSMenuRef QMenuBarPrivate::QMacMenuBarPrivate::apple_menu
Definition at line 197 of file qmenubar_p.h.
Referenced by actualMenuItemVisibility(), and QMenuBarPrivate::macMenu().
menu
OSMenuRef QMenuBarPrivate::QMacMenuBarPrivate::menu
Definition at line 197 of file qmenubar_p.h.
Referenced by QMenuBarPrivate::macMenu().
The documentation for this struct was generated from the following files:
/src/gui/widgets/qmenubar_p.h
/src/gui/widgets/qmenu_mac.mm