Qt 4.8: QFreetypeFace Struct Reference
QFreetypeFace Struct Reference
#include <qfontengine_ft_p.h>
Public Types
enum { cmapCacheSize = 0x200 }
Public Functions
void computeSize (const QFontDef &fontDef, int *xsize, int *ysize, bool *outline_drawing)
int fsType () const
HB_Error getPointInOutline (HB_Glyph glyph, int flags, hb_uint32 point, HB_Fixed *xpos, HB_Fixed *ypos, hb_uint32 *nPoints)
bool getSfntTable (uint tag, uchar *buffer, uint *length) const
void lock ()
QFontEngine::Properties properties () const
void release (const QFontEngine::FaceId &face_id)
void unlock ()
Static Public Functions
static void addBitmapToPath (FT_GlyphSlot slot, const QFixedPoint &point, QPainterPath *path, bool=false)
static void addGlyphToPath (FT_Face face, FT_GlyphSlot g, const QFixedPoint &point, QPainterPath *path, FT_Fixed x_scale, FT_Fixed y_scale)
static QFreetypeFace * getFace (const QFontEngine::FaceId &face_id, const QByteArray &fontData=QByteArray())
Public Variables
FcCharSet * charset
glyph_t cmapCache [cmapCacheSize]
FT_Face face
HB_Face hbFace
FT_Matrix matrix
FT_CharMap symbol_map
FT_CharMap unicode_map
int xsize
int ysize
Private Functions
QFreetypeFace ()
~QFreetypeFace ()
Properties
QMutex _lock
QByteArray fontData
QAtomicInt ref
Friends
class QFontEngineFT
class QScopedPointerDeleter< QFreetypeFace >
Detailed Description
Definition at line 83 of file qfontengine_ft_p.h.
Enumerations
anonymous enum
anonymous enum
Enumerator
cmapCacheSize
Definition at line 114 of file qfontengine_ft_p.h.
 { cmapCacheSize = 0x200 };
Constructors and Destructors
QFreetypeFace()
QFreetypeFace::QFreetypeFace () inline private
Definition at line 127 of file qfontengine_ft_p.h.
 : _lock(QMutex::Recursive) {}
~QFreetypeFace()
QFreetypeFace::~QFreetypeFace () inline private
Definition at line 128 of file qfontengine_ft_p.h.
 {}
Functions
addBitmapToPath()
void QFreetypeFace::addBitmapToPath (FT_GlyphSlot slot, const QFixedPoint & point, QPainterPath * path, bool = false) static
Definition at line 532 of file qfontengine_ft.cpp.
Referenced by QFontEngineFT::getUnscaledGlyph().
 {
     if (slot->format != FT_GLYPH_FORMAT_BITMAP
         || slot->bitmap.pixel_mode != FT_PIXEL_MODE_MONO)
         return;
     QPointF cp = point.toPointF();
     qt_addBitmapToPath(cp.x() + TRUNC(slot->metrics.horiBearingX), cp.y() - TRUNC(slot->metrics.horiBearingY),
                        slot->bitmap.buffer, slot->bitmap.pitch, slot->bitmap.width, slot->bitmap.rows, path);
 }
addGlyphToPath()
void QFreetypeFace::addGlyphToPath (FT_Face face, FT_GlyphSlot g, const QFixedPoint & point, QPainterPath * path, FT_Fixed x_scale, FT_Fixed y_scale) static
Definition at line 449 of file qfontengine_ft.cpp.
Referenced by QFontEngineFT::addGlyphsToPath(), and QFontEngineFT::getUnscaledGlyph().
 {
     const qreal factor = 1/64.;
     scaleOutline(face, g, x_scale, y_scale);
     QPointF cp = point.toPointF();
     // convert the outline to a painter path
     int i = 0;
     for (int j = 0; j < g->outline.n_contours; ++j) {
         int last_point = g->outline.contours[j];
         QPointF start = cp + QPointF(g->outline.points[i].x*factor, -g->outline.points[i].y*factor);
         if(!(g->outline.tags[i] & 1)) {
             start += cp + QPointF(g->outline.points[last_point].x*factor, -g->outline.points[last_point].y*factor);
             start /= 2;
         }
 //         qDebug("contour: %d -- %d", i, g->outline.contours[j]);
 //         qDebug("first point at %f %f", start.x(), start.y());
         path->moveTo(start);
         QPointF c[4];
         c[0] = start;
         int n = 1;
         while (i < last_point) {
             ++i;
             c[n] = cp + QPointF(g->outline.points[i].x*factor, -g->outline.points[i].y*factor);
 //             qDebug() << "    i=" << i << " flag=" << (int)g->outline.tags[i] << "point=" << c[n];
             ++n;
             switch (g->outline.tags[i] & 3) {
             case 2:
                 // cubic bezier element
                 if (n < 4)
                     continue;
                 c[3] = (c[3] + c[2])/2;
                 --i;
                 break;
             case 0:
                 // quadratic bezier element
                 if (n < 3)
                     continue;
                 c[3] = (c[1] + c[2])/2;
                 c[2] = (2*c[1] + c[3])/3;
                 c[1] = (2*c[1] + c[0])/3;
                 --i;
                 break;
             case 1:
             case 3:
                 if (n == 2) {
 //                     qDebug() << "lineTo" << c[1];
                     path->lineTo(c[1]);
                     c[0] = c[1];
                     n = 1;
                     continue;
                 } else if (n == 3) {
                     c[3] = c[2];
                     c[2] = (2*c[1] + c[3])/3;
                     c[1] = (2*c[1] + c[0])/3;
                 }
                 break;
             }
 //             qDebug() << "cubicTo" << c[1] << c[2] << c[3];
             path->cubicTo(c[1], c[2], c[3]);
             c[0] = c[3];
             n = 1;
         }
         if (n == 1) {
 //             qDebug() << "closeSubpath";
             path->closeSubpath();
         } else {
             c[3] = start;
             if (n == 2) {
                 c[2] = (2*c[1] + c[3])/3;
                 c[1] = (2*c[1] + c[0])/3;
             }
 //             qDebug() << "cubicTo" << c[1] << c[2] << c[3];
             path->cubicTo(c[1], c[2], c[3]);
         }
         ++i;
     }
 }
computeSize()
void QFreetypeFace::computeSize (const QFontDef & fontDef, int * xsize, int * ysize, bool * outline_drawing)
Definition at line 342 of file qfontengine_ft.cpp.
 {
     *ysize = qRound(fontDef.pixelSize * 64);
     *xsize = *ysize * fontDef.stretch / 100;
     *outline_drawing = false;
     /*
      * Bitmap only faces must match exactly, so find the closest
      * one (height dominant search)
      */
     if (!(face->face_flags & FT_FACE_FLAG_SCALABLE)) {
         int best = 0;
         for (int i = 1; i < face->num_fixed_sizes; i++) {
             if (qAbs(*ysize -  Y_SIZE(face,i)) <
                 qAbs (*ysize - Y_SIZE(face, best)) ||
                 (qAbs (*ysize - Y_SIZE(face, i)) ==
                  qAbs (*ysize - Y_SIZE(face, best)) &&
                  qAbs (*xsize - X_SIZE(face, i)) <
                  qAbs (*xsize - X_SIZE(face, best)))) {
                 best = i;
             }
         }
         if (FT_Set_Char_Size (face, X_SIZE(face, best), Y_SIZE(face, best), 0, 0) == 0) {
             *xsize = X_SIZE(face, best);
             *ysize = Y_SIZE(face, best);
         } else {
             int err = 1;
             if (!(face->face_flags & FT_FACE_FLAG_SCALABLE) && ysize == 0 && face->num_fixed_sizes >= 1) {
                 // work around FT 2.1.10 problem with BDF without PIXEL_SIZE property
                 err = FT_Set_Pixel_Sizes(face, face->available_sizes[0].width, face->available_sizes[0].height);
                 if (err && face->num_fixed_sizes == 1)
                     err = 0; //even more of a workaround...
             }
             if (err)
                 *xsize = *ysize = 0;
         }
     } else {
         *outline_drawing = (*xsize > (QT_MAX_CACHED_GLYPH_SIZE<<6) || *ysize > (QT_MAX_CACHED_GLYPH_SIZE<<6));
     }
 }
fsType()
int QFreetypeFace::fsType () const
Definition at line 170 of file qfontengine_ft.cpp.
Referenced by QFontEngineXLFD::faceId().
 {
     int fsType = 0;
     TT_OS2 *os2 = (TT_OS2 *)FT_Get_Sfnt_Table(face, ft_sfnt_os2);
     if (os2)
         fsType = os2->fsType;
     return fsType;
 }
getFace()
QFreetypeFace * QFreetypeFace::getFace (const QFontEngine::FaceId & face_id, const QByteArray & fontData = QByteArray()) static
Definition at line 207 of file qfontengine_ft.cpp.
Referenced by checkSymbolFont(), fontFile(), QFontEngineFT::init(), and QFontEngineQPF::QFontEngineQPF().
 {
     if (face_id.filename.isEmpty() && fontData.isEmpty())
         return 0;
     QtFreetypeData *freetypeData = qt_getFreetypeData();
     if (!freetypeData->library)
         FT_Init_FreeType(&freetypeData->library);
     QFreetypeFace *freetype = freetypeData->faces.value(face_id, 0);
     if (freetype) {
         freetype->ref.ref();
     } else {
         QScopedPointer<QFreetypeFace> newFreetype(new QFreetypeFace);
         FT_Face face;
         if (!face_id.filename.isEmpty()) {
             QFile file(QString::fromUtf8(face_id.filename));
             if (face_id.filename.startsWith(":qmemoryfonts/")) {
                 // from qfontdatabase.cpp
                 extern QByteArray qt_fontdata_from_index(int);
                 QByteArray idx = face_id.filename;
                 idx.remove(0, 14); // remove ':qmemoryfonts/'
                 bool ok = false;
                 newFreetype->fontData = qt_fontdata_from_index(idx.toInt(&ok));
                 if (!ok)
                     newFreetype->fontData = QByteArray();
             } else if (!(file.fileEngine()->fileFlags(QAbstractFileEngine::FlagsMask) & QAbstractFileEngine::LocalDiskFlag)) {
                 if (!file.open(QIODevice::ReadOnly)) {
                     return 0;
                 }
                 newFreetype->fontData = file.readAll();
             }
         } else {
             newFreetype->fontData = fontData;
         }
         if (!newFreetype->fontData.isEmpty()) {
             if (FT_New_Memory_Face(freetypeData->library, (const FT_Byte *)newFreetype->fontData.constData(), newFreetype->fontData.size(), face_id.index, &face)) {
                 return 0;
             }
         } else if (FT_New_Face(freetypeData->library, face_id.filename, face_id.index, &face)) {
             return 0;
         }
         newFreetype->face = face;
         newFreetype->hbFace = qHBNewFace(face, hb_getSFntTable);
         Q_CHECK_PTR(newFreetype->hbFace);
         newFreetype->ref = 1;
         newFreetype->xsize = 0;
         newFreetype->ysize = 0;
         newFreetype->matrix.xx = 0x10000;
         newFreetype->matrix.yy = 0x10000;
         newFreetype->matrix.xy = 0;
         newFreetype->matrix.yx = 0;
         newFreetype->unicode_map = 0;
         newFreetype->symbol_map = 0;
 #ifndef QT_NO_FONTCONFIG
         newFreetype->charset = 0;
 #endif
         memset(newFreetype->cmapCache, 0, sizeof(newFreetype->cmapCache));
         for (int i = 0; i < newFreetype->face->num_charmaps; ++i) {
             FT_CharMap cm = newFreetype->face->charmaps[i];
             switch(cm->encoding) {
             case FT_ENCODING_UNICODE:
                 newFreetype->unicode_map = cm;
                 break;
             case FT_ENCODING_APPLE_ROMAN:
             case FT_ENCODING_ADOBE_LATIN_1:
                 if (!newFreetype->unicode_map || newFreetype->unicode_map->encoding != FT_ENCODING_UNICODE)
                     newFreetype->unicode_map = cm;
                 break;
             case FT_ENCODING_ADOBE_CUSTOM:
             case FT_ENCODING_MS_SYMBOL:
                 if (!newFreetype->symbol_map)
                     newFreetype->symbol_map = cm;
                 break;
             default:
                 break;
             }
         }
         if (!FT_IS_SCALABLE(newFreetype->face) && newFreetype->face->num_fixed_sizes == 1)
             FT_Set_Char_Size (face, X_SIZE(newFreetype->face, 0), Y_SIZE(newFreetype->face, 0), 0, 0);
 # if 0
         FcChar8 *name;
         FcPatternGetString(pattern, FC_FAMILY, 0, &name);
         qDebug("%s: using maps: default: %x unicode: %x, symbol: %x", name,
                newFreetype->face->charmap ? newFreetype->face->charmap->encoding : 0,
                newFreetype->unicode_map ? newFreetype->unicode_map->encoding : 0,
                newFreetype->symbol_map ? newFreetype->symbol_map->encoding : 0);
         for (int i = 0; i < 256; i += 8)
             qDebug("    %x: %d %d %d %d %d %d %d %d", i,
                    FcCharSetHasChar(newFreetype->charset, i), FcCharSetHasChar(newFreetype->charset, i),
                    FcCharSetHasChar(newFreetype->charset, i), FcCharSetHasChar(newFreetype->charset, i),
                    FcCharSetHasChar(newFreetype->charset, i), FcCharSetHasChar(newFreetype->charset, i),
                    FcCharSetHasChar(newFreetype->charset, i), FcCharSetHasChar(newFreetype->charset, i));
 #endif
         FT_Set_Charmap(newFreetype->face, newFreetype->unicode_map);
         QT_TRY {
             freetypeData->faces.insert(face_id, newFreetype.data());
         } QT_CATCH(...) {
             newFreetype.take()->release(face_id);
             // we could return null in principle instead of throwing
             QT_RETHROW;
         }
         freetype = newFreetype.take();
     }
     return freetype;
 }
getPointInOutline()
HB_Error QFreetypeFace::getPointInOutline (HB_Glyph glyph, int flags, hb_uint32 point, HB_Fixed * xpos, HB_Fixed * ypos, hb_uint32 * nPoints)
Definition at line 179 of file qfontengine_ft.cpp.
Referenced by QFontEngineFT::draw(), QFontEngineQPF::getPointInOutline(), and QFontEngineFT::getPointInOutline().
 {
     if (HB_Error error = (HB_Error)FT_Load_Glyph(face, glyph, flags))
         return error;
     if (face->glyph->format != FT_GLYPH_FORMAT_OUTLINE)
         return HB_Err_Invalid_SubTable;
     *nPoints = face->glyph->outline.n_points;
     if (!(*nPoints))
         return HB_Err_Ok;
     if (point > *nPoints)
         return HB_Err_Invalid_SubTable;
     *xpos = face->glyph->outline.points[point].x;
     *ypos = face->glyph->outline.points[point].y;
     return HB_Err_Ok;
 }
getSfntTable()
bool QFreetypeFace::getSfntTable (uint tag, uchar * buffer, uint * length) const
Definition at line 414 of file qfontengine_ft.cpp.
Referenced by QFontEngineQPF::getSfntTableData(), and QFontEngineQPF::QFontEngineQPF().
 {
     bool result = false;
 #if (FREETYPE_MAJOR*10000 + FREETYPE_MINOR*100 + FREETYPE_PATCH) > 20103
     if (FT_IS_SFNT(face)) {
         FT_ULong len = *length;
         result = FT_Load_Sfnt_Table(face, tag, 0, buffer, &len) == FT_Err_Ok;
         *length = len;
     }
 #endif
     return result;
 }
lock()
void QFreetypeFace::lock () inline
Definition at line 94 of file qfontengine_ft_p.h.
Referenced by QFontEngineQPF::lockFace().
     {
         _lock.lock();
     }
properties()
QFontEngine::Properties QFreetypeFace::properties () const
Definition at line 384 of file qfontengine_ft.cpp.
 {
     QFontEngine::Properties p;
     p.postscriptName = FT_Get_Postscript_Name(face);
     PS_FontInfoRec font_info;
     if (FT_Get_PS_Font_Info(face, &font_info) == 0)
         p.copyright = font_info.notice;
     if (FT_IS_SCALABLE(face)) {
         p.ascent = face->ascender;
         p.descent = -face->descender;
         p.leading = face->height - face->ascender + face->descender;
         p.emSquare = face->units_per_EM;
         p.boundingBox = QRectF(face->bbox.xMin, -face->bbox.yMax,
                                face->bbox.xMax - face->bbox.xMin,
                                face->bbox.yMax - face->bbox.yMin);
     } else {
         p.ascent = QFixed::fromFixed(face->size->metrics.ascender);
         p.descent = QFixed::fromFixed(-face->size->metrics.descender);
         p.leading = QFixed::fromFixed(face->size->metrics.height - face->size->metrics.ascender + face->size->metrics.descender);
         p.emSquare = face->size->metrics.y_ppem;
 //        p.boundingBox = QRectF(-p.ascent.toReal(), 0, (p.ascent + p.descent).toReal(), face->size->metrics.max_advance/64.);
         p.boundingBox = QRectF(0, -p.ascent.toReal(),
                                face->size->metrics.max_advance/64, (p.ascent + p.descent).toReal() );
     }
     p.italicAngle = 0;
     p.capHeight = p.ascent;
     p.lineWidth = face->underline_thickness;
     return p;
 }
release()
void QFreetypeFace::release (const QFontEngine::FaceId & face_id)
Definition at line 321 of file qfontengine_ft.cpp.
Referenced by checkSymbolFont(), getFace(), QFontEngineQPF::QFontEngineQPF(), QFontEngineQPF::~QFontEngineQPF(), and QFontEngineXLFD::~QFontEngineXLFD().
 {
     QtFreetypeData *freetypeData = qt_getFreetypeData();
     if (!ref.deref()) {
         qHBFreeFace(hbFace);
         FT_Done_Face(face);
 #ifndef QT_NO_FONTCONFIG
         if (charset)
             FcCharSetDestroy(charset);
 #endif
         if(freetypeData->faces.contains(face_id))
             freetypeData->faces.take(face_id);
         delete this;
     }
     if (freetypeData->faces.isEmpty()) {
         FT_Done_FreeType(freetypeData->library);
         freetypeData->library = 0;
     }
 }
unlock()
void QFreetypeFace::unlock () inline
Definition at line 98 of file qfontengine_ft_p.h.
Referenced by QFontEngineQPF::unlockFace().
     {
         _lock.unlock();
     }
Friends and Related Functions
QFontEngineFT
friend class QFontEngineFT friend
Definition at line 125 of file qfontengine_ft_p.h.
Referenced by QFontEngineFT::draw().
QScopedPointerDeleter< QFreetypeFace >
friend class QScopedPointerDeleter< QFreetypeFace > friend
Definition at line 126 of file qfontengine_ft_p.h.
Properties
_lock
QMutex QFreetypeFace::_lock private
Definition at line 130 of file qfontengine_ft_p.h.
Referenced by lock(), and unlock().
charset
FcCharSet* QFreetypeFace::charset
Definition at line 106 of file qfontengine_ft_p.h.
Referenced by getFace().
cmapCache
glyph_t QFreetypeFace::cmapCache[cmapCacheSize]
Definition at line 115 of file qfontengine_ft_p.h.
Referenced by getFace().
face
FT_Face QFreetypeFace::face
Definition at line 103 of file qfontengine_ft_p.h.
Referenced by checkSymbolFont(), QFontEngineQPF::doKerning(), QFontEngineQPF::emSquareSize(), getFace(), QFontEngineXLFD::glyphIndexToFreetypeGlyphIndex(), QFontEngineQPF::lockFace(), QFontEngineXLFD::non_locked_face(), and QFontEngineFTRawFont::updateFamilyNameAndStyle().
fontData
QByteArray QFreetypeFace::fontData private
Definition at line 131 of file qfontengine_ft_p.h.
Referenced by QFontEngineFT::draw(), and getFace().
hbFace
HB_Face QFreetypeFace::hbFace
Definition at line 104 of file qfontengine_ft_p.h.
Referenced by getFace().
matrix
FT_Matrix QFreetypeFace::matrix
Definition at line 110 of file qfontengine_ft_p.h.
Referenced by getFace(), QFontEngineQPF::lockFace(), and QFontEngineFT::name().
ref
QAtomicInt QFreetypeFace::ref private
Definition at line 129 of file qfontengine_ft_p.h.
Referenced by getFace(), and QFontEngineFT::initFromFontEngine().
symbol_map
FT_CharMap QFreetypeFace::symbol_map
Definition at line 112 of file qfontengine_ft_p.h.
Referenced by getFace().
unicode_map
FT_CharMap QFreetypeFace::unicode_map
Definition at line 111 of file qfontengine_ft_p.h.
Referenced by getFace().
xsize
int QFreetypeFace::xsize
Definition at line 108 of file qfontengine_ft_p.h.
Referenced by getFace(), QFontEngineFT::invalid(), and QFontEngineQPF::lockFace().
ysize
int QFreetypeFace::ysize
Definition at line 109 of file qfontengine_ft_p.h.
Referenced by getFace(), QFontEngineFT::invalid(), and QFontEngineQPF::lockFace().
The documentation for this struct was generated from the following files:
/src/gui/text/qfontengine_ft_p.h
/src/gui/text/qfontengine_ft.cpp