Qt 4.8: QDBusLockerBase Struct Reference
QDBusLockerBase Struct Reference
#include <qdbusthreaddebug_p.h>
Public Types
enum Condition {
BeforeLock, AfterLock, BeforeUnlock, AfterUnlock,
BeforePost, AfterPost, BeforeDeliver, AfterDeliver,
BeforeAcquire, AfterAcquire, BeforeRelease, AfterRelease
}
Static Public Functions
static void reportThreadAction (int, int, QDBusConnectionPrivate *)
Detailed Description
Definition at line 110 of file qdbusthreaddebug_p.h.
Enumerations
Condition
enum QDBusLockerBase::Condition
Enumerator
BeforeLock
AfterLock
BeforeUnlock
AfterUnlock
BeforePost
AfterPost
BeforeDeliver
AfterDeliver
BeforeAcquire
AfterAcquire
BeforeRelease
AfterRelease
Definition at line 112 of file qdbusthreaddebug_p.h.
     {
         BeforeLock,
         AfterLock,
         BeforeUnlock,
         AfterUnlock,
         BeforePost,
         AfterPost,
         BeforeDeliver,
         AfterDeliver,
         BeforeAcquire,
         AfterAcquire,
         BeforeRelease,
         AfterRelease
     };
Functions
reportThreadAction()
static void QDBusLockerBase::reportThreadAction (int , int , QDBusConnectionPrivate *) inline static
Definition at line 134 of file qdbusthreaddebug_p.h.
Referenced by QDBusConnectionPrivate::customEvent(), QDBusActivateObjectEvent::placeMetaCall(), QDBusConnectionPrivate::postEventToThread(), QDBusMutexLocker::QDBusMutexLocker(), QDBusReadLocker::QDBusReadLocker(), QDBusWriteLocker::QDBusWriteLocker(), QDBusMutexLocker::~QDBusMutexLocker(), QDBusReadLocker::~QDBusReadLocker(), and QDBusWriteLocker::~QDBusWriteLocker().
 { }
The documentation for this struct was generated from the following file:
/src/dbus/qdbusthreaddebug_p.h