Qt 4.8: QHeaderViewPrivate::SectionSpan Struct Reference
QHeaderViewPrivate::SectionSpan Struct Reference
#include <qheaderview_p.h>
Public Functions
void read (QDataStream &in)
int sectionSize () const
SectionSpan ()
SectionSpan (int length, int sections, QHeaderView::ResizeMode mode)
void write (QDataStream &out) const
Public Variables
int count
QHeaderView::ResizeMode resizeMode
int size
Detailed Description
Definition at line 287 of file qheaderview_p.h.
Constructors and Destructors
SectionSpan() [1/2]
QHeaderViewPrivate::SectionSpan::SectionSpan () inline
Definition at line 291 of file qheaderview_p.h.
 : size(0), count(0), resizeMode(QHeaderView::Interactive) {}
SectionSpan() [2/2]
QHeaderViewPrivate::SectionSpan::SectionSpan (int length, int sections, QHeaderView::ResizeMode mode) inline
Definition at line 292 of file qheaderview_p.h.
             : size(length), count(sections), resizeMode(mode) {}
Functions
read()
void QHeaderViewPrivate::SectionSpan::read (QDataStream & in) inline
Definition at line 298 of file qheaderview_p.h.
Referenced by operator>>(), and QHeaderViewPrivate::sectionSpanIndex().
         { in >> size; in >> count; int m; in >> m; resizeMode = (QHeaderView::ResizeMode)m; }
sectionSize()
int QHeaderViewPrivate::SectionSpan::sectionSize () const inline
Definition at line 294 of file qheaderview_p.h.
Referenced by QHeaderViewPrivate::createSectionSpan(), QHeaderViewPrivate::headerSectionPosition(), QHeaderViewPrivate::headerSectionSize(), QHeaderViewPrivate::headerVisualIndexAt(), and QHeaderViewPrivate::setDefaultSectionSize().
 { return (count > 0 ? size / count : 0); }
write()
void QHeaderViewPrivate::SectionSpan::write (QDataStream & out) const inline
Definition at line 296 of file qheaderview_p.h.
Referenced by operator<<(), and QHeaderViewPrivate::sectionSpanIndex().
         { out << size; out << count; out << (int)resizeMode; }
Properties
count
int QHeaderViewPrivate::SectionSpan::count
Definition at line 289 of file qheaderview_p.h.
Referenced by QHeaderViewPrivate::createSectionSpan(), QHeaderViewPrivate::headerSectionCount(), QHeaderViewPrivate::headerSectionPosition(), QHeaderViewPrivate::headerSectionSize(), QHeaderViewPrivate::headerVisualIndexAt(), read(), QHeaderViewPrivate::setDefaultSectionSize(), and write().
resizeMode
QHeaderView::ResizeMode QHeaderViewPrivate::SectionSpan::resizeMode
Definition at line 290 of file qheaderview_p.h.
Referenced by QHeaderViewPrivate::createSectionSpan().
size
int QHeaderViewPrivate::SectionSpan::size
Definition at line 288 of file qheaderview_p.h.
Referenced by QHeaderViewPrivate::createSectionSpan(), QHeaderViewPrivate::headerSectionPosition(), QHeaderViewPrivate::headerVisualIndexAt(), read(), QHeaderViewPrivate::removeSpans(), QHeaderViewPrivate::setDefaultSectionSize(), and write().
The documentation for this struct was generated from the following file:
/src/gui/itemviews/qheaderview_p.h