Qt 4.8: /src/plugins/platforms/wayland/gl_integration/xcomposite_share/wayland-xcomposite-client-protocol.h File Reference
wayland-xcomposite-client-protocol.h File Reference
#include <stdint.h>
#include <stddef.h>
#include "wayland-util.h"
Classes
struct wl_xcomposite_listener
Macros
#define WL_XCOMPOSITE_CREATE_BUFFER 0
Functions
static int wl_xcomposite_add_listener (struct wl_xcomposite *wl_xcomposite, const struct wl_xcomposite_listener *listener, void *data)
static struct wl_xcomposite * wl_xcomposite_create (struct wl_display *display, uint32_t id, uint32_t version)
static struct wl_buffer * wl_xcomposite_create_buffer (struct wl_xcomposite *wl_xcomposite, uint32_t x_window, int width, int height, struct wl_visual *visual)
static void wl_xcomposite_destroy (struct wl_xcomposite *wl_xcomposite)
static void * wl_xcomposite_get_user_data (struct wl_xcomposite *wl_xcomposite)
static void wl_xcomposite_set_user_data (struct wl_xcomposite *wl_xcomposite, void *user_data)
Variables
const struct wl_interface wl_xcomposite_interface
Macro Definition Documentation
WL_XCOMPOSITE_CREATE_BUFFER
#define WL_XCOMPOSITE_CREATE_BUFFER 0
Definition at line 74 of file wayland-xcomposite-client-protocol.h.
Referenced by wl_xcomposite_create_buffer().
Function Documentation
wl_xcomposite_add_listener()
static int wl_xcomposite_add_listener (struct wl_xcomposite * wl_xcomposite, const struct wl_xcomposite_listener * listener, void * data) inline static
Definition at line 67 of file wayland-xcomposite-client-protocol.h.
Referenced by QWaylandXCompositeGLXIntegration::wlDisplayHandleGlobal(), and QWaylandXCompositeEGLIntegration::wlDisplayHandleGlobal().
 {
     return wl_proxy_add_listener((struct wl_proxy *) wl_xcomposite,
                      (void (**)(void)) listener, data);
 }
wl_xcomposite_create()
static struct wl_xcomposite* wl_xcomposite_create (struct wl_display * display, uint32_t id, uint32_t version) static
Definition at line 77 of file wayland-xcomposite-client-protocol.h.
Referenced by QWaylandXCompositeGLXIntegration::wlDisplayHandleGlobal(), and QWaylandXCompositeEGLIntegration::wlDisplayHandleGlobal().
 {
     wl_display_bind(display, id, "wl_xcomposite", version);
     return (struct wl_xcomposite *)
         wl_proxy_create_for_id(display, &wl_xcomposite_interface, id);
 }
wl_xcomposite_create_buffer()
static struct wl_buffer* wl_xcomposite_create_buffer (struct wl_xcomposite * wl_xcomposite, uint32_t x_window, int width, int height, struct wl_visual * visual) static
Definition at line 104 of file wayland-xcomposite-client-protocol.h.
Referenced by QWaylandXCompositeBuffer::QWaylandXCompositeBuffer().
 {
     struct wl_proxy *id;
     id = wl_proxy_create((struct wl_proxy *) wl_xcomposite,
                  &wl_buffer_interface);
     if (!id)
         return NULL;
     wl_proxy_marshal((struct wl_proxy *) wl_xcomposite,
              WL_XCOMPOSITE_CREATE_BUFFER, id, x_window, width, height, visual);
     return (struct wl_buffer *) id;
 }
wl_xcomposite_destroy()
static void wl_xcomposite_destroy (struct wl_xcomposite * wl_xcomposite) inline static
Definition at line 98 of file wayland-xcomposite-client-protocol.h.
 {
     wl_proxy_destroy((struct wl_proxy *) wl_xcomposite);
 }
wl_xcomposite_get_user_data()
static void* wl_xcomposite_get_user_data (struct wl_xcomposite * wl_xcomposite) inline static
Definition at line 92 of file wayland-xcomposite-client-protocol.h.
 {
     return wl_proxy_get_user_data((struct wl_proxy *) wl_xcomposite);
 }
wl_xcomposite_set_user_data()
static void wl_xcomposite_set_user_data (struct wl_xcomposite * wl_xcomposite, void * user_data) inline static
Definition at line 86 of file wayland-xcomposite-client-protocol.h.
 {
     wl_proxy_set_user_data((struct wl_proxy *) wl_xcomposite, user_data);
 }
Variable Documentation
wl_xcomposite_interface
const struct wl_interface wl_xcomposite_interface
Definition at line 54 of file wayland-xcomposite-protocol.c.
Referenced by wl_xcomposite_create().